### ISSUE TITLE
[Bug]: Adding Background to "Site Title" Block Expands Width

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/wp-calypso#62747] opened 2022-04-13 19:20 UTC
### Quick summary

When I have a "Site Title" block in a header template, adding a background color to the header expands the width

### Steps to reproduce

1. Add "Site Title" block to header
2. Add "Background Color"
3. See width expand

### What you expected to happen

Width should remain constant when adding background color.

### What actually happened

Width expanded when adding background color. 

Resetting block removes it and restores to expected behavior

## Screenshots

No Background Color:

<img width="1595" alt="Screenshot on 2022-04-13 at 15-17-56" src="https://user-images.githubusercontent.com/45246438/163254021-9905e57e-49aa-4765-a364-2c024f8e222d.png">

With Background Color:

<img width="1621" alt="Screenshot on 2022-04-13 at 15-17-11" src="https://user-images.githubusercontent.com/45246438/163253910-340d82f7-8783-43a7-bd95-71fb53b87808.png">

Frontend of Site:
<img width="470" alt="Screenshot on 2022-04-13 at 15-18-39" src="https://user-images.githubusercontent.com/45246438/163254147-5ae4bde0-dd58-4dd8-bb77-f028e7999a50.png">

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

Could fix by removing padding from Site Title with CSS. This could would need to be changed:

```
h1.has-background, h2.has-background, h3.has-background, h4.has-background, h5.has-background, h6.has-background {
  padding: 1.25em 2.375em;
}
```

**Comment by john-legg** [comment] 2023-05-24 21:30
📌 REPRODUCTION RESULTS

Tested on Simple – Replicated 
Tested on Atomic – Replicated 
Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to reproduce this on headers and footers using different themes, but after doing more testing, it seems to be normal/expected behavior. The same behavior happens when adding background styles to other text-based blocks (e.g. Paragraph) on pages, posts, etc. However, just to be certain, I will hand this over to the FSE team to make the call.

**Adding background to Site Title block**


https://github.com/Automattic/wp-calypso/assets/96805492/7849942b-de5a-407f-b061-4dd97ee92bb8



**Adding background to Paragraph block**


https://github.com/Automattic/wp-calypso/assets/96805492/3c490159-1652-45fc-8ff3-f06ea119bcba


📌 ACTIONS

Moved to Needs Author/HE Reply column 
Requested team feedback

📌 Message to Team

@Automattic/cylon this seems like normal behavior, but I just wanted to confirm before closing this issue.

**Comment by jeyip** [comment] 2023-05-25 00:12
Hi @john-legg! #cylon has been decommissioned paYE8P-2IT-p2#comment-2083. I'm unsure who's responsible for FSE now -- maybe @Addison-Stavlo or @obenland can help?

**Comment by obenland** [comment] 2023-05-25 10:22
I think this can be picked up by anyone as it's part of the shared ownership on Dotcom.

**Comment by cuemarie** [comment] 2023-05-26 22:39
Thanks for the updates folks! 

I agree this appears to be by design, as other blocks behave the same way. 

📌 ACTIONS
- Closed as by design

**Closed as completed by cuemarie** 2023-05-26 22:39 UTC
Labels: Bug, [Pri] Low, Blocks, Triaged, Empathy Testing
