### ISSUE TITLE
Comments: Only 1 notification for successful comment update

### ISSUE THREAD

**Issue by brbrr** [Automattic/wp-calypso#22155] opened 2018-02-06 06:57 UTC
#### Steps to reproduce
0. Make sure you have few comments
1. Starting at URL: https://wordpress.com/comments
2. Make any comment update (e.g. mark as spam) for few comments at once.
3. Only 1 notification will be shown.

#### What I expected

I receive 1 notification per updated comment, so I will be able to undo any of the modified comment

#### What happened instead

I receive only 1 notification for all updated comments, which means I can undo only last updated comment

#### Browser / OS version

Chrome / Mac OS

#### Screenshot / Video

![screencast 2018-02-06 13-54-09](https://user-images.githubusercontent.com/5654161/35845545-8314d594-0b45-11e8-8b96-6605e09e2674.gif)

**Comment by drw158** [comment] 2018-03-14 14:30
@brbrr I'm marking this as `enhancement` and not `bug` for a few reasons:

- "What happened instead" is the intended behavior. We intentionally did not show a notice for every action. This would annoyingly fill the screen with notices.
- It is standard behavior to show just one notice when repeating a single action multiple times. See Gmail web, Gmail mobile apps, and Spark for macOS.
- You can still access your trashed comments in the Trash folder, so the experience is not broken. If we did not have a Trash folder, this could be considered a bug.

**Comment by worldomonation** [comment] 2021-04-30 21:41
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

As there has been no recent activity on this issue it is being closed with the label `Closed - Won't Fix`.
If this issue should remain open, please feel free to re-open this bug.

**Closed by worldomonation** 2021-04-30 21:41 UTC
Labels: Comments, [Type] Enhancement
