### ISSUE TITLE
Full Site Editing: Site Logo block won't center

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wp-calypso#50408] opened 2021-02-23 23:05 UTC
*Note:* I'm filing this here because it works fine on a dotorg install. There's something going on on dotcom Simple, specifically here.

### Steps to reproduce the behavior

1. Go to the Site Editor (create a Site Editor-enabled site at https://horizon.wordpress.com/new?flags=gutenboarding/site-editor if you don't have one)
2. Add a Site Logo block
3. Try to center align
4. Does not center align (although the center alignment works on the frontend)

#### What I expected to happen

center align

#### What actually happened

stays left aligned

### Context

p7DVsv-ayb-p2

#### Browser / OS version

Firefox 85, Chrome 88
macOS 11.2.1

#### Is this specific to the applied theme? Which one?

`tt1-blocks`, others not yet tested

#### Does this happen on simple or atomic sites or both?

Simple

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Pretty rough, most logos are centered

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent

**Comment by kspilarski** [comment] 2021-06-29 09:33
Same case as 4100861-zen. 

Workaround for 4100861-zen: instead of site logo block, we used image block so it's centered.

**Comment by jeyip** [comment] 2021-11-06 00:49
I can't reproduce this problem anymore @mattwiebe. It appears to be fixed.

![2021-11-05 17 48 38](https://user-images.githubusercontent.com/5414230/140592198-c4675622-4aaa-4ee2-bb58-3e581cdddc5d.gif)

**Comment by jeyip** [comment] 2021-11-08 18:19
Closing this for now @mattwiebe. Feel free to reopen if the problem presents itself again.

**Closed as completed by jeyip** 2021-11-08 18:19 UTC
Labels: Bug, [Goal] Gutenberg, [Goal] Full Site Editing
