### ISSUE TITLE
Post/Page Editor: incorrect alignment in Visibility setting

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#78568] opened 2023-06-23 09:36 UTC
### Quick summary

Inside the Post or Page Editor, the Visibility setting value is aligned incorrectly:

<img width="283" alt="CleanShot 2023-06-23 at 10 26 35@2x" src="https://github.com/Automattic/wp-calypso/assets/14153300/d634c8d0-47c7-4fd1-a37e-d4cf10e93d47">

It doesn't seem to be affected by the Gutenberg version - when the plugin is inactive on an Atomic site, the problem persists

### Steps to reproduce

1. Open a new post or page in a WordPress.com site, simple or Atomic

### What you expected to happen

"Public" should be aligned to the left of "Visibility", like in a self-hosted site:

<img width="1249" alt="CleanShot 2023-06-23 at 10 34 50@2x" src="https://github.com/Automattic/wp-calypso/assets/14153300/13d95666-7a6f-4b0b-b2fa-077ec6d8fa79">

### What actually happened

"Public" displays below "Visibility"

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Chrome 114, Mac OS 13.0.1

**Comment by dsas** [comment] 2023-06-23 10:42
This has been escalated to dotcom because of its visibility p1687512996216709-slack-C02FMH4G8 but I don't think it's urgent.

It looks like this is caused by the [paid newsletters in Jetpack](https://github.com/Automattic/jetpack/blob/a9fb7870d32b1e1f78d766892b64bb41b10fee5d/projects/plugins/jetpack/extensions/blocks/subscriptions/settings.scss#L26): https://github.com/Automattic/jetpack/pull/31224 introduced a change which means that this CSS is added:

```css
.edit-post-post-visibility {
  display: block;
}
```

Other than triggering this bug I can't see what effect setting it to `display:block` has but I might be missing something 🤔 CC @Automattic/gold

**Comment by millerf** [comment] 2023-06-23 12:23
Nice catch @dsas. 

This seems like a small enough task. I'll look into it now as it seems to affect everyone...

**Comment by millerf** [comment] 2023-06-23 12:51
@dsas Fixed in https://github.com/Automattic/jetpack/pull/31544

**Closed as completed** 2023-06-24 15:46 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] High, [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered
