### ISSUE TITLE
Group Block: Missing padding when background image is set

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#82284] opened 2023-09-27 19:21 UTC
### Quick summary

When we set a background image, we don't add padding to the group so text is usually pretty close to the edges. In cases like this, it would be required to manually set the padding.

### Steps to reproduce

1. Add the group block
2. Choose a background image
3. Check the padding

### What you expected to happen

The padding is to be set automatically just like we do in the Cover block or when we set a background color to a paragraph.

<img width="705" alt="Captura de Tela 2023-09-27 às 16 17 29" src="https://github.com/Automattic/wp-calypso/assets/1136160/15fa13b9-a3a9-4dcb-adb2-87fb855eb0f7">

### What actually happened

<img width="747" alt="Captura de Tela 2023-09-27 às 16 16 11" src="https://github.com/Automattic/wp-calypso/assets/1136160/634bcb66-c8e5-4318-ab67-65b842900b03">

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment] 2023-09-27 21:02
📌 REPRODUCTION RESULTS
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
I believe this is by design - the Group block no longer automatically adds padding to content inside of it.

📌 ACTIONS
- Closed as by design

📌 Message to Author
Hey @eduardozulian ! I think this is best suited as feedback in the Gutenberg issue where follow up issues to adding background images to Group blocks are being discussed. You could share that in the comments of the issue below, or submit a feature request to add padding when a background image is set.

- https://github.com/WordPress/gutenberg/issues/54336

**Closed as not planned by cuemarie** 2023-09-27 21:02 UTC
Labels: Bug, [Pri] Normal, Triaged, Gutenberg RC Testing, [Platform] Simple, [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks
