### ISSUE TITLE
Nav Unification: can't scroll sidebar after toggling "Collapse menu" feature

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#50428] opened 2021-02-24 12:03 UTC
### Steps to reproduce the behavior

- Have Nav Unification active
- Choose a page that has fairly little content (i.e. Posts without posts)
- Resize the window so the sidebar doesn’t fully fit the screen
- Scroll to the bottom and click Collapse Sidebar
- Scroll up then down a bit
- Click the Collapse Sidebar icon at the bottom to open the sidebar again

#### What I expected to happen

I should be able to still scroll sidebar items outside the viewport into view

#### What actually happened

I couldn't scroll sidebar items outside the viewport into view anymore

#### Browser / OS version

macOS / Chrome / Simple site

**Comment by tjcafferkey** [comment] 2021-04-07 12:59
Closing this issue as it's no longer reproducible. Potentially fixed by https://github.com/Automattic/wp-calypso/pull/51364

**Comment by BogdanUngureanu** [comment] 2021-04-13 08:43
I've reopened the issue because I was able to reproduce it with similar steps.
https://user-images.githubusercontent.com/995955/114523695-31643e00-9c4d-11eb-9cff-b5b4ab6aced4.mov

https://user-images.githubusercontent.com/995955/114524003-82743200-9c4d-11eb-95ad-4d8e734266f9.mov

**Comment by BogdanUngureanu** [comment] 2021-04-13 09:15
Closing the issue again, I was able to reproduce it only because there's a conflict/issue with [Paid member subscriptions](https://wordpress.org/plugins/paid-member-subscriptions/) plugin and it's not related to nav unification.

**Closed as completed by BogdanUngureanu** 2021-04-13 09:15 UTC
Labels: Bug, [Pri] Normal, [Feature] Calypso & wp-admin Navigation
