### ISSUE TITLE
Block Inserter: Disappeared when searching using characters "S" and "L"

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#47033] opened 2020-11-03 05:04 UTC
This is user report (one report,) and I noticed a similar issue happening on other user sites (they didn't mention it at that time, but when I checked another different issue, I need to add a block and I able to replicate it on the user's site). 

I am able to replicate it on **some** of my test sites, so not all/seemingly random. Feel free to ping me if you need more information.

This happens on **Simple sites** (WordPress.com websites without third-party plugins or third-party themes.)

#### Steps to reproduce

1. Create or edit a post or page

2. Click the `[+]` button to add a block on the editor area
![image](https://cldup.com/abCbC7RQ7F.png)
*Direct link: https://cldup.com/abCbC7RQ7F.png*
![image](https://cldup.com/HDSyqeh98z.png)
*Direct link: https://cldup.com/HDSyqeh98z.png*

3. Type the block name you want to search. I'd suggest you to try search "Spacer" or "Latest Posts" blocks (with character "S" and "L" at the beginning) on the search box ("Search for a block").

4. As soon as you entered the text "s...", the block inserter disappears. Please check the GIF below.
![image](https://cldup.com/hASYplg0Yc.gif)
*Direct link: https://cldup.com/hASYplg0Yc.gif*

I can't find any console errors, so I'm not sure what's going on. 

#### What I expected
The block inserter stays and I able to search the block that I need and use it.

#### What happened instead
The block inserter disappears, and it keeps happening.

#### Browser / OS version
Chrome Version 86.0.4240.183
macOS Catalina 10.15.7

**Comment by Thelmachido** [comment] 2020-11-08 20:27
This is another user report of the same issue. I wasn't able to replicate the issue on my end but the issue is similar to the one stated above. 

User can't select certain items using the plus mark at the right side of a newly-created block. The box instantly vanishes if they to type an "s" (Separator or Spacer) or "e" (Embed). These are the only letters they've noticed so far. 

https://snipboard.io/erbm3H.jpg

- This is a WordPress.com site on a third-party theme also using third-party plugins.

- I can't find any console errors but disabling Gutenberg resolves this

**This is happening on** 
1. Mac Desktop App version 6.3.0
2. Chrome Browser _(more information to be added later)_

**Comment by pablinos** [comment] 2020-11-09 18:03
I think this could be caused by a WPCOM block pattern 'List with Image'. I'm slightly nervous about editing the pattern content, so I've asked the View team about it. p1604944538297500-slack-dotcom-view

**Comment by glendaviesnz** [comment] 2020-11-09 18:06
See https://github.com/Automattic/wp-calypso/issues/47237 - also happens with "a" or "e" in some cases

**Comment by pablinos** [comment] 2020-11-09 18:42
We've changed the block pattern which seems to have fixed it for me. It comes from using a cover block with no content. We should probably log that in Gutenberg core - unless a cover block should always have content of course. It may cause other issues with blocks that have default inner blocks.

**Comment by synora** [comment] 2021-02-15 16:56
@pablinos I'm currently unable to replicate this so I'll close the issue.

**Closed by synora** 2021-02-15 16:56 UTC
Labels: Blocks, Triaged, [Type] Bug
