### ISSUE TITLE
FSE Theme Global Styles: Changes to Layout not saving 

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#69884] opened 2022-11-09 10:23 UTC
### Quick summary

On a simple site, with an active FSE theme (I tried Twenty Twenty-Two, Blank Canvas, and Masu), changes to the layout content width aren't saving.

### Steps to reproduce

1. on a website with an active FSE theme, open the site Editor and navigate to the theme global styles;
2. Choose the option to edit the Layout
3. Change the width of the content
4. Save your changes
5. Notice that, once the page reloads, the changes aren't saved

![fsethemestylesbug](https://user-images.githubusercontent.com/2540430/200805363-fb4a9a75-ed79-47cd-95d3-0018c29ea854.gif)

### What you expected to happen

The changes to content width to be saved and applied to the template.

### What actually happened

Everything stayed as before, no changes were saved.

### Context

pd4QKa-E6-p2
5694729-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

I was able to reproduce this on multiple FSE themes.

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by zachspears** [comment] 2022-11-17 02:44
Able to Reproduce in Quadrat on Simple Site.

**Comment by ClassicRKR27** [comment] 2022-11-19 19:59
- [ ] Another instance here with the `Bryne` theme: 31901192-hc

**Comment by Copons** [comment] 2022-12-08 10:37
Hi folks, thanks for reporting!
I'm closing this as duplicate of https://github.com/Automattic/wp-calypso/issues/67059, which is being currently worked (it seems to require a Core Gutenberg fix; see the [issue](https://github.com/WordPress/gutenberg/issues/45520)).

**Closed as not planned by Copons** 2022-12-08 10:37 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Simple
