### ISSUE TITLE
Social Signup: WordPress.com asks for age-range from Google

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#16564] opened 2017-07-26 06:06 UTC
#### Steps to reproduce
1. Starting at URL: https://href.li/?https://wpcalypso.wordpress.com/log-in with an existing WordPress.com account that hasn't been connected to a Google account
2. Click "Or log in with your existing social profile"
3. Sign in with Google

#### What I expected

The dialog not to show that WordPress.com wants to know age range as AFAIK the existing sign up process does not ask questions about age

#### What happened instead

Dialog shows that WordPress.com wants to know my age range

#### Browser / OS version

Chrome Version 59.0.3071.115 (Official Build) (64-bit) on macOS 10.12.6

#### Screenshot / Video

![screen shot 2017-07-26 at 3 53 07 pm](https://user-images.githubusercontent.com/128826/28606802-2d620a30-721c-11e7-9148-283fd9150971.png)

**Comment by fabianapsimoes** [comment] 2017-07-26 16:21
Duplicate of https://github.com/Automattic/wp-calypso/issues/15391

**Closed by fabianapsimoes** 2017-07-26 16:21 UTC
Labels: Login, Signup, [Type] Question
