### ISSUE TITLE
Nav Unification: Cannot access WP Admin -> widgets.php

### ISSUE THREAD

**Issue by serabi** [Automattic/wp-calypso#48146] opened 2020-12-08 22:58 UTC
#### Steps to reproduce

1. Go to WP Admin -> Appearance -> Widgets
2. When there, you cannot get into the WP Admin widgets section. Instead you are redirected to the Customizer. 

I am reporting this as a bug because:

- To find inactive widgets, you do need to go to that section of WP Admin. The Customizer does not show inactive widgets. 
- If you change themes on a site and want to move widgets that are already added and customized to another section (for example, from sidebar to footer), you have to be able to access WP Admin in order to have the ability drag the widgets from one section to another.  This functionality is not built into the Customizer.

**Comment by cpapazoglou** [comment] 2021-01-05 11:55
Thanks for reporting @serabi!

@obenland I suggest we use `/wp-admin/widgets.php` for widgets cause this functionality 

![](https://cln.sh/W9XaYP+)

is missing from `https://wordpress.com/customize/[DOMAIN]?autofocus%5Bpanel%5D=widgets`

**Comment by obenland** [comment] 2021-01-05 19:59
There's a Widgets link under "Dash" in the superadminbar. Would that meet your needs?

![image](https://user-images.githubusercontent.com/1398304/103693016-7fcab800-4f4d-11eb-8894-68e155dc5638.png)

**Comment by serabi** [comment] 2021-01-13 23:43
My concern is that only offering access to superadmins would mean that people who are working on their sites and want to go retrieve an inactive widget wouldn't have the ability to do so. We could theoretically help them over email or chat if needed, but that would add more of a support burden, not less. 

If the /wp-admin/widgets.php link still also works for regular uses, that could possibly be enough access for users - although we'd need to make sure to document for users that they can still access widgets.php by typing the address in manually.

**Comment by obenland** [comment] 2021-01-15 17:57
Yes, the URL will still work

**Comment by getdave** [comment] 2021-01-25 14:36
Can we update `Widgets` to use the link `/wp-admin/widgets.php` then?

**Comment by getdave** [comment] 2021-01-25 16:28
Needs decision.

**Comment by obenland** [comment] 2021-01-25 16:51
In anticipation of https://github.com/Automattic/wp-calypso/issues/47043 I'm leaning towards keeping it pointed to the Customizer for now.

@serabi Do you think the toggle would cover that use case sufficiently?

**Comment by serabi** [comment] 2021-01-26 02:03
Yes, I do think the toggle would cover the use case sufficiently. Thanks for the tag!

**Comment by katiebethbrown** [comment] 2021-02-10 00:08
@obenland - With the toggle for wp-admin equivalents enabled I'm still seeing the Appearance submenu items for Widgets and Menus redirect to the Customizer instead of opening their respective wp-admin pages. 

Is that the expected behavior?

**Comment by obenland** [comment] 2021-02-10 00:21
It is, yes.

**Comment by katiebethbrown** [comment] 2021-02-10 00:41
>It is, yes.

Thanks. I share the same concerns that @serabi shared above. With the toggle active it seems these links should load the wp-admin pages, since that's what the toggle suggests it does.

The only way to restore inactive widgets is on the `widgets.php` page directly, and plugins like WPML use `nav-menus.php` to [display menu translation settings that aren't available in the Customizer](https://wpml.org/documentation/getting-started-guide/translating-menus/).

**Comment by obenland** [comment] 2021-02-10 18:20
> With the toggle active it seems these links should load the wp-admin pages, since that's what the toggle suggests it does.

Makes sense, let's do that

**Comment by cpapazoglou** [comment] 2021-02-10 18:22
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/49830

**Closed as completed by cpapazoglou** 2021-02-10 18:22 UTC
Labels: Bug, [Pri] Low, [Feature] Calypso & wp-admin Navigation
