### ISSUE TITLE
Google AdWords Credit: Code not generating

### ISSUE THREAD

**Issue by gracie** [Automattic/wp-calypso#18120] opened 2017-09-18 21:12 UTC
#### Steps to reproduce
1. Go to the My Plans page on a site with a Premium or Business Plan, doesn't matter if the site has custom plugins / themes or not - it impacts all of them: https://wordpress.com/plans/my-plan/
2. Find the Adwords Credit area and click Generate Code
3. Accept the Terms and Conditions

#### What I expected

To see an AdWords code

#### What happened instead

The credit code field is greyed-out and blank.

Chrome: 
<img width="494" alt="screen shot 2017-09-18 at 4 50 09 pm" src="https://user-images.githubusercontent.com/21203710/30564922-90196c02-9c94-11e7-8f3a-d0d57a1c299a.png">

Firefox: 
<img width="439" alt="screen shot 2017-09-18 at 4 56 29 pm" src="https://user-images.githubusercontent.com/21203710/30564928-95452f2c-9c94-11e7-9754-ed74b82c83cb.png">

#### Browser / OS version

Firefox 55 on Mac OS X 10
Chrome 60 on Mac OS X 10

#### Context / Source
Reported from a WordPress.com Business Plan user.

This was tested on sites using custom plugins and sites without any custom plugins or themes. We had an almost identical issue in the past that impacted only sites with custom plugins / themes (am I allowed to link to that repo from here?).

**Comment by rahul020691** [comment] 2017-09-20 02:35
Hi there,

A premium user also reported here:
https://woothemes.zendesk.com/agent/tickets/690597

do we have a list of codes to give them while we fix this?

Thanks

**Comment by dcoleonline** [comment] 2017-09-20 14:53
Premium plan: 691811-zd

**Comment by kriskarkoski** [comment] 2017-09-20 14:56
It looks like we've run out of available codes. I have requested those from Google and will update here once we've received them if that fixes this issue.

**Comment by davoraltman** [comment] 2017-09-23 06:59
Business plan: [698352-zd](https://woothemes.zendesk.com/agent/tickets/698352)

**Comment by rahul020691** [comment] 2017-09-25 03:09
@kriskarkoski do we have an ETA on this fix or on the codes? Many users are asking us regarding the code.

Thanks,

**Comment by kriskarkoski** [comment] 2017-09-25 12:02
@rahul020691 It should be fixed now. We are at the mercy of Google getting us the codes in this case since we this is a third-party feature, so the best thing to do is to just keep adding ticket/chat links here so we can follow up quickly with users once it's fixed.

**Comment by kriskarkoski** [comment] 2017-09-25 12:03
Google provided 25,000 additional codes over the weekend that I've uploaded and confirmed are working on one of the accounts noted on this thread. I have followed up with all of the tickets noted here to let them know it should be working now.

@gracie I don't see a ticket link in your original post, so I wanted to CC you in case you remember who it is and want to follow up with them as well.

**Closed by kriskarkoski** 2017-09-25 12:03 UTC
