### ISSUE TITLE
CoBlocks Carousel - Error when trying to change the size

### ISSUE THREAD

**Issue by syhussaini** [Automattic/wp-calypso#72404] opened 2023-01-22 06:01 UTC
### Quick summary

There is an error when trying to change the size of the CoBlocks Carousel.

> TypeError: Cannot read properties of null (reading 'removeEventListener')
    at https://testing.domains/wp-content/plugins/coblocks/dist/404.js:33:3260
    at Or (https://testing.domains/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:73042)
    at Ir (https://testing.domains/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:73228)
    at El (https://testing.domains/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:92472)
    at fl (https://testing.domains/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:85533)
    at zn (https://testing.domains/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:32460)
    at dl (https://testing.domains/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:85899)
    at V (https://testing.domains/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:9850)
    at Ze (https://testing.domains/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:24953)
    at de (https://testing.domains/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:15646)

### Steps to reproduce

1. Install and activate the **CoBlocks** plugin.
2. Add a **Carousel Block** to the Page/Post and change the image size from the block settings.

_Please see this image: https://d.pr/i/zZ9bNm_

### What you expected to happen

I was expecting it to change the image size without an error.

### What actually happened

I see an error: _The editor has encountered an unexpected error._

### Context

A customer on #5886115-zd reported this issue when trying to change the size of the image in CoBlocks Carousel block. 

### Theme-specific issue?

NA

### Browser, operating system and other notes

My Browser: https://whatismybrowser.com/w/G2KL3KE

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

None

**Comment by rinazrina** [comment] 2023-02-07 07:49
Another instance: #5935403-zen

Editing the image and removing the Carousel block causes an error, the same error message as reported above. 
This issue only happens with Gutenberg plugin active.

**Comment by Joshgrygiel** [comment] 2023-03-06 18:29
Another report of the issue here: 38341089-hc

**Comment by kavyagokul** [comment] 2023-03-07 11:08
📌 SCRUBBING : RESULT
- Tested on P2 - Could Not Replicate 
- Tested on Simple - Could Not Replicate 
- Tested on AT - Replicated 
- Tested on Self-hosted - Replicated 
- Replicable on Core - Yes/


📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/71777

**Closed as completed by kavyagokul** 2023-03-07 11:08 UTC
Labels: Bug, [Pri] Low
