### ISSUE TITLE
Slideshow Block: Block remembers Image Captions, so they can't be changed or removed.  

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#51013] opened 2021-03-11 22:48 UTC
### Steps to reproduce the behavior

1. Go to the site's Media Library, and import some images from Pexels (since those come with captions by default)
2. Go to Site - Pages, create a page, add a Slideshow Block to it, and add all of your new Pexels images to the slideshow. Publish the page. 
3. Visit the page, and you'll see all of the captions appearing at the bottom of images. 
4. Go back to your Media Library, click on your images, remove the captions, or change them to something different.
5. Refresh the page that has the existing slideshow on it. The captions do not change. They'll remain as they were when they were originally added to the slideshow block.

#### What I expected to happen
Image Captions to change on the slideshow once they're changed on the actual image.

#### What actually happened
Image captions do not change with the slideshow. The image needs to be removed from the slideshow, saved, then added back in, for the caption to update.

### Context
#user-report

#### Browser / OS version
All
#### Does this happen on simple or atomic sites or both?
Both.
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects all slideshow blocks.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/30731356/110864882-9526d000-8277-11eb-93ba-737b58b08370.png)
![image](https://user-images.githubusercontent.com/30731356/110864897-9b1cb100-8277-11eb-96b9-d6d96dfdd6ca.png)

**Comment by Robertght** [comment] 2021-09-01 06:12
I can confirm this happens on my end as well and to fix it, I had to re-add the slideshow again.

**Comment by yansern** [comment] 2021-09-08 12:18
When the caption of an image has changed, the old caption is being sent by Calypso's media modal to the Slideshow block. An XHR request to update the image caption runs in parallel in the background.

In order to fix this, the new caption taken from the dirty input field (since XHR request is executed later) should already be sent to the Slideshow block.

Start debugging in `calypsoify-iframe.tsx` at `this.mediaSelectPort.postMessage(payload)` and work backwards.
![image](https://user-images.githubusercontent.com/1287077/132508094-ad711735-9b1b-4259-aa2a-d7888f878b94.png)

**Comment by yansern** [comment] 2021-09-27 12:55
**What will be fixed:**
Image caption on Slideshow block is updated when editing the image caption on media library through the **Block Editor**,
PR: https://github.com/Automattic/wp-calypso/pull/56535 

**What won't be fixed:**
Image caption on Slideshow block is updated when editing the image caption on media library through Calypso.
Why? Caption is saved in block meta, it does not fetch caption directly from media library.

**Closed as completed** 2021-09-27 16:21 UTC
Labels: Bug, [Pri] Normal, Slideshow
