### ISSUE TITLE
Intermittent error when publishing, after adding tags or categories: "Publishing failed. Error message: Sorry, you are not allowed to assign the provided terms"

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#36274] opened 2019-09-24 21:20 UTC
I ran into this error in 15468043-hc today. Upon researching it, I found no existing reports, but I did find many Zendesk tickets, all dated from mid-July up until now, where the error was mentioned (all with no resolution):

2281003-zen, 2375861-zen, 2186010-zen, 2336103-zen, 2183102-zen, 2352755-zen, 2243803-zen, 2311951-zen, 2333250-zen, 2161172-zen

As far as I know, these are all simple sites.

The error appears across the top of the editor and looks like this: https://cld.wthms.co/bZ9Rrb

For the tickets where the user was specific enough, the common thread is that they had added a category or tag to the post before trying to publish it. In my chat today, the issue was having added a tag. The post could be published fine without that tag added, but once the tag was added, it could not be published.

As a workaround, the tag could be added via quick edit in wp-admin.

It does not appear to be a browser issue, as I could replicate the issue myself in a support session for the user in chat today, and the issue persisted across multiple browsers (Chrome and Firefox) for that user. 

I also found this when researching the error message - https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php

Any idea what might be causing this?

**Comment by donpark** [comment] 2019-09-24 22:21
Source of the error message is POST REST API handler in Core. When an API is `CREATABLE` or `EDITABLE`, `check_assign_terms_permission()` method of `WP_REST_Posts_Controller` class is called and it's failing when a user lacks permission to assign, meaning create or update, terms.

**Comment by formosattic** [comment] 2019-10-03 22:49
+1 15689980-hc, issue happened when adding tags.

**Comment by donpark** [comment] 2019-10-03 23:00
I was able to reproduce this bug although not consistently.

**Comment by Robertght** [comment] 2019-10-16 19:43
@donpark Found another case here: 2425866-zen

**Comment by donpark** [comment] 2019-10-17 00:38
@Robertght Sorry but I no longer work for A8C.

**Comment by kcswong** [comment] 2019-11-28 16:19
Seems to be another report in 16975579-hc

**Comment by JoshuaGoode** [comment] 2019-12-12 23:36
Encountered this while adding tags to a portfolio project: 17282693-hc & 2557371-zen

**Comment by marcuswisecaesar** [comment] 2020-04-04 17:54
Not intermittent for me happens when publishing a one-word tag like `fashion`, or `music`

19989830-hc & 2847839-zd

**Comment by scosgro** [comment] 2020-09-01 19:11
Another report in 22914939hc

**Comment by donalirl** [comment] 2020-09-15 01:21
Another report in #24119597-hc, though the cause is unclear

**Comment by wynwin** [comment] 2020-09-15 17:17
Another report here: 24133818-hc - I have asked the user if they notice this happen with specific tags/categories, so I can try and reproduce.

**Comment by darnelldibbles** [comment] 2020-09-17 16:02
Another report here: https://wordpress.com/forums/topic/saving-my-post-3/

**Comment by smithkyle45** [comment] 2020-09-25 22:27
New report of this issue in 24409620-hc

**Comment by kristarella** [comment] 2020-09-30 00:28
Another one in 24502294-hc
I asked them to remove the tags and try to publish, which seemed to work.

**Comment by ktyfuller604** [comment] 2020-09-30 21:10
The issue occurred when scheduling as well - 24031031-hc

**Comment by wynwin** [comment] 2020-10-05 19:34
Another one 24570082-hc

**Comment by lakellie** [comment] 2020-11-29 17:18
Another report in 3510459-zen

**Comment by happychait** [comment] 2020-12-10 20:11
A customer reported this on Safari on iPad in 156380-hc

**Comment by JoshuaGoode** [comment] 2020-12-22 22:02
A newer report appears to have been opened that seems related: https://github.com/Automattic/wp-calypso/issues/45758

If it's the same, we can probably close that one in favor of this one and copy over relevant info there.

**Comment by cathymcbride** [comment] 2021-01-05 14:16
Moving to prioritized backlog.

**Comment by kosiew** [comment] 2021-01-11 07:04
#3638164-zen

**Comment by formosattic** [comment] 2021-01-15 23:25
27037033-hc

**Comment by tbradsha** [comment] 2021-01-16 15:13
3642645-zen

**Comment by kriskorn** [comment] 2021-01-25 07:49
3677729-zen

**Comment by fresatomica** [comment] 2021-01-29 11:23
Another report on https://wordpress.com/forums/topic/updating-failed-message-2/.

**Comment by philnick206** [comment] 2021-02-02 19:06
Reported in #13954900-hc

**Comment by bobmatyas** [comment] 2021-02-05 01:42
Reported in #25586965-hc

**Comment by davipontesblog** [comment] 2021-02-06 09:41
May be related to https://github.com/Automattic/wp-calypso/issues/49007

**Comment by happychait** [comment] 2021-02-08 16:36
5631180-hc

**Comment by cathymcbride** [comment] 2021-02-08 16:38
@davipontesblog perhaps? But this issue is quite a bit older.

**Comment by davipontesblog** [comment] 2021-02-08 16:51
> @davipontesblog perhaps? But this issue is quite a bit older.

Sorry, I referenced the wrong issue, just noticed this.

**Comment by khristiansnyder** [comment] 2021-02-08 20:29
Had a user run into this when trying to save a draft today: #10661951-hc

**Comment by JessBoctor** [comment] 2021-02-09 22:52
Reported this issue in #3626777-HC. Customer added tags and categories that weren't saved, but the post published.

**Comment by scosgro** [comment] 2021-02-11 18:12
Another report in #3730058-zen

**Comment by kriskarkoski** [comment] 2021-02-12 18:49
3726375-zen

**Comment by ivan-ottinger** [comment] 2021-02-25 10:14
Just adding here that the user from 3726375-zd-woothemes encountered the issue with another post and here is what they observed:

> It turns out that when I saved the draft it seems to have published the post. Despite the [error] message, the post was published.

In other words, they managed to save and publish the post even the `Publishing failed. Sorry, you are not allowed to assign the provided terms.` error message was still displaying.

I am not sure whether this will help in any way, but wanted to share.

**Comment by wpshellbelle** [comment] 2021-02-27 04:44
Another reported in 3758977-zen

**Comment by devNigel** [comment] 2021-03-01 00:26
Another report 3781399-zen

**Comment by donalirl** [comment] 2021-03-01 06:44
Another case of this in #3780514-zen, pertaining to scheduled posts. What happens:

1. They schedule the post, and the error appears: `Scheduling failed. Sorry, you are not allowed to assign the provided terms`
2. They are able to go back and schedule the post after attempting again.
3. The post is scheduled, but the email notification already went out to their followers about the post that was supposedly scheduled.

**Comment by donalirl** [comment] 2021-03-01 06:45
Another case of this in #3780514-zen, pertaining to scheduled posts. What happens:

1. They schedule the post, and the error appears: `Scheduling failed. Sorry, you are not allowed to assign the provided terms`
2. They are able to go back and schedule the post after attempting again.
3. The post is scheduled, but the email notification already went out to their followers about the post that was supposedly scheduled.

**Comment by davipontesblog** [comment] 2021-03-01 13:53
@cathymcbride I'd like to suggest we raise the priority on this one due to volume and the fact that it's a blocker when users are trying to publish new content. What do you think?

**Comment by fernmed** [comment] 2021-03-02 14:56
Another report of this 22801086-hc

**Comment by jeyip** [comment] 2021-03-02 23:35
Trying to reproduce this issue but not having any luck.  🤔 cc @StefanNieuwenhuis Would you mind giving this a test as well when you get the chance?

- There was some investigation that happened quite a while ago. Don Park and @lakellie pointed to [check_assign_terms_permission()](https://github.com/WordPress/WordPress/blob/3cdbafe16408c54c8f6bad02cb94df9d55a04bd1/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1459-L1481), which seems very plausible to me. We can probably pinpoint the problem easily if we manage to replicate it.
- From the few zendask / happy chats that I looked through, this is only affecting simple sites

@davipontesblog @fernmed or anyone else -- would it be possible to get permission from a client to attempt to reproduce the issue on their site?

**Comment by StefanNieuwenhuis** [comment] 2021-03-03 09:54
> Trying to reproduce this issue but not having any luck. 🤔 cc @StefanNieuwenhuis Would you mind giving this a test as well when you get the chance?

@jeyip sure! I'm unable to reproduce it but I did some digging on the `check_assign_terms_permission()` method to provide some context on the checks/prerequisites.

After retrieving the taxonomies names, we check if the current user has permission to assign them to the post. This happens  [here](https://github.com/WordPress/WordPress/blob/3cdbafe16408c54c8f6bad02cb94df9d55a04bd1/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1474), with the `current_user_can()` method.

The `current_user_can()` method:
1. Retrieves the current user and checks its existence.
2. It then checks if the user has [the correct "capability"](https://github.com/WordPress/WordPress/blob/3cdbafe16408c54c8f6bad02cb94df9d55a04bd1/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1474) (in our case _assign_term_). 
3. The `has_cap` method calls [the `map_meta_cap` method](https://github.com/WordPress/WordPress/blob/3cdbafe16408c54c8f6bad02cb94df9d55a04bd1/wp-includes/capabilities.php#L534), which is a huge switch that checks capabilities.
4. It retrieves the term from the DB, checks if [the term is valid](https://github.com/WordPress/WordPress/blob/3cdbafe16408c54c8f6bad02cb94df9d55a04bd1/wp-includes/taxonomy.php#L862), and returns a `do_not_allow` capability when invalid. **My suspicion is that this is what's causing the error.**

### Next steps
1. replicate the issue on a simple site (like @jeyip suggested)
2. check the user's permissions
3. check how this relates to the above findings.

**Comment by davipontesblog** [comment] 2021-03-03 13:16
> @davipontesblog @fernmed or anyone else -- would it be possible to get permission from a client to attempt to reproduce the issue on their site?

@fernmed would it be possible to follow up with the user here to ask if we can try to reproduce the error on their site? I think this would involve making an update on a post, or maybe creating a draft would suffice... @jeyip is this correct?

**Comment by StefanNieuwenhuis** [comment] 2021-03-03 13:30
> > @davipontesblog @fernmed or anyone else -- would it be possible to get permission from a client to attempt to reproduce the issue on their site?
> 
> @fernmed would it be possible to follow up with the user here to ask if we can try to reproduce the error on their site? I think this would involve making an update on a post, or maybe creating a draft would suffice... @jeyip is this correct?

This is correct! It would be great if we can get some data from the [Dev Tools](https://developers.google.com/web/tools/chrome-devtools) console & network tabs. This helps us to narrow down the issue.

**Comment by fernmed** [comment] 2021-03-05 00:46
I made the request with the user for further testing. 

3794477-zd

**Comment by wpshellbelle** [comment] 2021-03-06 19:02
Another report at 3781308-zen

**Comment by simison** [comment] 2021-03-08 14:04
We have a job that tries to save a post as a draft via API and suffers from this frequently. If we just have a diff that adds logging in all the possible places where this might go wrong, we could try to capture what happens.

Discussed p1615189993041800-slack-dotcom and especially p1615196213117200-slack-create-gardeners

**Comment by jeyip** [comment] 2021-03-08 20:06
> If we just have a diff that adds logging in all the possible places where this might go wrong, we could try to capture what happens.

Great suggestion! I'm in the process of setting up a diff now, but it will definitely need a few extra set of eyes for code review. It'll be my first time using our logging platform and I also want to make sure we're capturing _all_ possible spots this error might be manifesting.

**Comment by mreishus** [comment] 2021-03-09 16:42
Speculation: It sounds like it could be a data race where the capability for attaching the new tag is checked just before the new tag is created.

**Comment by mreishus** [comment] 2021-03-10 22:45
## Steps to Reproduce

* Start creating a new post on a WPCOM simple site. 
* Type something in the title and body
* Create a new tag and assign it to the post: `MyTag1`.  
* Create a new category **with the exact same name of the tag you just made** and assign it to the post: `MyTag1`.
* Press publish and you should see the error message.
* If you are a WP.com SuperAdmin, this _might_ not work as you are patched to have all capabilities. I removed this check when I was testing, however I currently don't know if that was necessary to recreate the bug.

Video:

https://user-images.githubusercontent.com/937354/110703227-1f5c2f00-81b9-11eb-8c99-00dff2e10252.mp4

## Technical Details

* Most of the code involved is core WordPress.org code. However, the bug doesn't happen on a standalone .org site. The bug may belong to .org multisite code, or it may belong to an .com optimization. Currently unsure.
* In my example above, I added a `TestPost10` *category* and a `TestPost10` *post_tag*.  Both of these are stored as **terms** in the WP database.
  * On a standalone .org site, I will have two separate `term_id`s for the `TestPost10` *category* and the `TestPost10` *post_tag*.  
    * For example, the `TestPost10` *category* might be `term_id=12345`, and the `TestPost10` *post_tag* might be `term_id=12346`. 
    * That means the `term_id` alone is specific enough to identify one of those items.
  * On my .com simple site, there will be one `term_id` shared between the `TestPost10` *category* and the `TestPost10` *post_tag*.
    * For example, the `TestPost10` *category* might be `term_id=12345`, and the `TestPost10` *post_tag* might also be `term_id=12345`, the same id. 
    *  That means the `term_id` alone is not specific enough to identify one of those items. You will also have to specify the `taxonomy`, which is either `post_tag` or `category`.
  * The `_terms` table will actually have two different `term_id`s for the terms. However, the `_term_taxonomy` table will file the first term against two different taxonomies.
```
+-----------+------------+------------+------------+
| term_id   | name       | slug       | term_group |
+-----------+------------+------------+------------+
| 123456756 | TestPost10 | testpost10 | 0          |
| 123456757 | TestPost10 | testpost10 | 0          |
+-----------+------------+------------+------------+
There are two TestPost10 terms, the "..56" and "..57" ids.

+------------------+-----------+----------+-------------+--------+-------+
| term_taxonomy_id | term_id   | taxonomy | description | parent | count |
+------------------+-----------+----------+-------------+--------+-------+
| 17               | 123456756 | category |             | 0      | 1     |
| 16               | 123456756 | post_tag |             | 0      | 1     |
+------------------+-----------+----------+-------------+--------+-------+
The "..56" id is set up as both a category and a post_tag, and the "..57" id is unused.
```
  * Some functions that retrieve a `term_id` will have an optional `taxonomy` parameter that can be passed. If it's not passed, the functions will look up all matches to the term_id, and if only one is found, all is good. If two are found, it doesn't know which one should be returned, and throws an error.
    * One of the permission checks if asking if the user is able to assign the term, but it ends up fetching the term by term_id only without specifying a taxonomy, so it is ambiguous if it is looking up the tag or the category.
    * This doesn't seem to be the full story, because after creating the error, you can simply wait a minute or two and try again, then it will work. Why should it start working? Currently unknown.

## Stack Trace
* The posts controller calls `has_cap( 'assign_term', $term_id )` to see if the user can assign the term: [Link](https://github.com/WordPress/WordPress/blob/efaa79d347fbac1f9c4d1bc0494ec809b43e7042/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1498-L1500)
* `has_cap(...)` calls `map_meta_cap(...)`: [Link](https://github.com/WordPress/WordPress/blob/efaa79d347fbac1f9c4d1bc0494ec809b43e7042/wp-includes/class-wp-user.php#L755)
* `map_meta_cap(...)`, when looking up the `assign_term` permission, calls `get_term( $term_id )` to get the term without knowing which taxonomy it belongs to yet: [Link](https://github.com/WordPress/WordPress/blob/efaa79d347fbac1f9c4d1bc0494ec809b43e7042/wp-includes/capabilities.php#L534-L536)
* `get_term( $term )`, when provided an integer `$term` and no optional taxonomy argument, proceeds to call `WP_Term::get_instance( $term, $taxonomy )`. In this case, `$term` is still an integer and `$taxonomy` is the empty string. [Link](https://github.com/WordPress/WordPress/blob/efaa79d347fbac1f9c4d1bc0494ec809b43e7042/wp-includes/taxonomy.php#L886)
* `get_instance( $term_id, '' )` looks up all rows matching that term_id. In the dotcom simple site, it could be multiples. [Link](https://github.com/WordPress/WordPress/blob/efaa79d347fbac1f9c4d1bc0494ec809b43e7042/wp-includes/class-wp-term.php#L131)
* `get_instance( $term_id, '' )` would filter multiple results, if a taxonomy was provided as the second argument.  In this case it isn't, so this filter code won't be used: [Link](https://github.com/WordPress/WordPress/blob/efaa79d347fbac1f9c4d1bc0494ec809b43e7042/wp-includes/class-wp-term.php#L136-L144)
* `get_instance( $term_id, '')`, If not provided a taxonomy filter, looks for multiple results. If multiple results are returned, and there are multiple valid taxonomies, it returns an error: [Link](https://github.com/WordPress/WordPress/blob/efaa79d347fbac1f9c4d1bc0494ec809b43e7042/wp-includes/class-wp-term.php#L152-L163)

## Proposed Fixes
None at this time; I'm currently unsure the best way to fix this, but at least I do have a good handle on what's going on. I would first like to determine if the bug is happening on .org multisite with no .com specific code before deciding on an approach.

## Followup Resources
* p7H4VZ-2Vd-p2 P2 summarizing my findings as of 2021-03-12
* 521-gh-Automattic/dotcom-manage dotcom issue where specific dotcom code is pointed out

**Comment by jeyip** [comment] 2021-03-10 23:16
> Create a new category with the exact same name of the tag you just made and assign it to the post: MyTag1.

~Oof this definitely seems like a problem. @mreishus While I think that what you've found is probably contributing to the problem we're seeing, there are a number of instances where users see the "Publishing failed." error where the post title and post tag / category added _do not_ match.~ 

~Here are a few examples I found:~

- ~17282693-hc~
  - ~Title: “TransAtlantic” at Boston Sculptors Gallery~
  - ~Tag: Boston Sculptors Gallery~
- ~24133818-hc~
  - ~User supposedly tried on a variety of different posts~
  - ~Tag: SEO~
  
~Maybe, to build on your findings, the term doesn't have to exactly match. Maybe the term just has to be included in the title (e.g. The `Boston Sculptors Gallery` tag is part of the `"Transatlantic" at Boston Sculptors Gallery` title) ? I'll test a few things out in my own environment and leave updates here.~

**Update:**
Ah ignore what I wrote above 🤦‍♂️ . I misread your comment. Awesome sleuthing mreishus! This makes a lot of sense. To build on your findings, cases like 17282693-hc and p3hLNG-18a-p2 that dealt with "Publishing failed." error appear to have duplicate terms (`Boston Sculptors Gallery` and `mu-plugins` respectively).

**Comment by donalirl** [comment] 2021-03-10 23:58
Encountered in #27098180-hc. They initially got the error but were able to publish it the second time. There are no categories or tags assigned to the post right now.

**Comment by benchilcote** [comment] 2021-03-11 12:41
Another report 3791219-zen.

**Comment by mreishus** [comment] 2021-03-11 16:25
I have not found a way to recreate the bug on dotorg multisite, both before and after forcing `global_terms_enabled()` to be on. This may be a dotcom specific bug. Up next is investigating just why the tag and the category are getting the same term_id, when they don't on dotorg.
![2021-03-11_10-23](https://user-images.githubusercontent.com/937354/110819709-0ce30380-8254-11eb-8eff-52b98109c6f1.png)
^ This is an incomplete analysis as the bug is happening in the `_term_taxonomy` table, not the `_term` table. I have [updated this comment](https://github.com/Automattic/wp-calypso/issues/36274#issuecomment-796256787) with details. I also rechecked the dotorg site I made and the taxonomy entries are using different term_ids, so the bug remains specific to dotcom.
![2021-03-11_14-53](https://user-images.githubusercontent.com/937354/110853803-a96bcc80-8279-11eb-8c6d-3171aa739290.png)

Edit: I have tracked it down a .com specific plugin.

## Followup Resources
* p7H4VZ-2Vd-p2 P2 summarizing my findings as of 2021-03-12
* 521-gh-Automattic/dotcom-manage dotcom issue where specific dotcom code is pointed out

**Comment by tbradsha** [comment] 2021-03-11 20:42
Got it in 28348375-hc. Trying twice didn't work, so I had them publish without tags or categories (success!) and then add the tags and categories after.

**Comment by tbradsha** [comment] 2021-03-11 20:42
Got it in 28348375-hc. Trying twice didn't work, so I had them publish without tags or categories (success!) and then add the tags and categories after.

**Comment by worldomonation** [comment] 2021-03-12 21:21
Issue reproduced during my `Back to Basics` user testing run.

Steps I took:
1. open a post.
2. add new post tags.
3. click on `Launch`.
4. cancel the new launch flow (one that looks similar to Gutenboarding).
5. see error.

Post link: https://e2eflowtesting2021031201gardening4.wordpress.com/2021/03/12/retro-cameras-galore/

**Comment by kwight** [comment] 2021-03-16 22:52
D58727-code under review.

**Comment by david-binda** [comment] 2021-03-17 16:05
D58727-code has been shipped. Hopefully this addresses the issue 🤞

**Comment by druesome** [comment] 2021-03-25 06:06
@david-binda I just got another report of this happening in 28628867-hc.  User says they entered a bunch of tags and wasn't able to save their draft.  They said they added 17 or so tags.  Reducing the number allowed them to save.  Site is https://photoferret1.com/

**Comment by david-binda** [comment] 2021-03-25 09:55
@druesome my understanding of this issue is that it was WPCOM specific, due to it's multisite nature and global tags turned on (+some custom logic in a mu-plugin). https://photoferret1.com/ is hosted on Atomic, so the issue is likely different.

**Comment by kwight** [comment] 2021-03-25 14:44
@druesome do you know if they got the error given by the OP? If not, a new issue would be best.

**Comment by kwight** [comment] 2021-03-29 21:18
I'm going to close this again – @druesome if there's still an issue, feel free to reopen if the user got the same error, otherwise a new issue would be better. 👍

**Comment by katiebethbrown** [comment] 2021-03-30 20:10
@kwight - I've got an atomic site in chat seeing the same error when adding a tag to posts in 27939677-hc. Happens with just a single tag, and I can replicate in a support session as well.

<img width="612" alt="terms" src="https://user-images.githubusercontent.com/42279181/113050760-70c95f80-9162-11eb-8291-c69d1339f583.png">

<img width="1002" alt="Screen Shot 2021-03-30 at 2 22 59 PM" src="https://user-images.githubusercontent.com/42279181/113051818-a3c02300-9163-11eb-8212-4c60317bf772.png">

**Comment by kwight** [comment] 2021-04-01 20:53
It looks like the additional reports are specific to Atomic; I'm closing this issue, and we can follow up further in https://github.com/Automattic/wp-calypso/issues/51640.

**Closed by kwight** 2021-04-01 20:53 UTC
Labels: Posts, [Closed] Fixed, [Pri] High, [Type] Bug
