### ISSUE TITLE
Earn Block: Stripe Payments block, unable to select the payment plan if there's only one payment plan added.

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-calypso#49796] opened 2021-02-07 11:28 UTC
### Steps to reproduce the behavior

1. One a new site, add the payments block, connect to Stripe (I set up the account right there).
2. Complete the Stripe process, create a new payment plan on Calypso Tools> Earn> Manage Payments. 
3. The payment plan should be for a one-time payment.
4. Add the payment block to the page/post, try to select the only available plan. 

#### What I expected to happen

I expect the block to select the available payment plan.
How it should work-
![stripe payment block working](https://user-images.githubusercontent.com/40609190/107145280-770f3c80-6966-11eb-9119-b71dbc80e6c0.gif)

#### What actually happened

I'm unable to select the payment plan- 
![stripe payment block](https://user-images.githubusercontent.com/40609190/107145001-c6ed0400-6964-11eb-986b-36e2349b8e6b.gif)

### Context

This happened for a user who reached out to us here #3718080-zen. I added the block to my test site and I faced the same issue.

Then I added another payment plan and I was able to select the plan and set up the block. Also, after that I deleted the second payment plan and I was still able to select it. So, essentially adding a second payment plan (recurring) and then removing it worked.

#### Browser / OS version
Version 88.0.4324.96 (Official Build) (x86_64) 
Mac OS Mojave ver 10.14.3

#### Is this specific to the applied theme? Which one?
No.

#### Does this happen on simple or atomic sites or both?
For Now, I tested on my simple site.

#### Is there any console output or error text?
Editor.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Not sure, it just stops user from adding the block properly. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Unable to select the payment plan-
![stripe payment block](https://user-images.githubusercontent.com/40609190/107145001-c6ed0400-6964-11eb-986b-36e2349b8e6b.gif)

Got fixed when I added another payment plan here-
<img width="1067" alt="Screenshot at Feb 07 16-57-44" src="https://user-images.githubusercontent.com/40609190/107145126-9fe30200-6965-11eb-9f87-55876d64efee.png">

How it should work-
![stripe payment block working](https://user-images.githubusercontent.com/40609190/107145280-770f3c80-6966-11eb-9119-b71dbc80e6c0.gif)

**Comment by JoshuaGoode** [comment] 2021-02-15 16:06
I could not reproduce. Rather than closing just yet, can you let me know if you can still reproduce this @ahmadbaig1?

Noting that, while I couldn't reproduce, I did encounter issues creating a plan via the editor in general.  Issues creating a payment plan/subscription was reported today by @druesome and we discussed things internally at p1613396561201300-slack-C0160HSMDQV

That other issue has been reported here: https://github.com/Automattic/wp-calypso/issues/50091

**Comment by ahmadbaig1** [comment] 2021-02-19 23:06
@JoshuaGoode It happened while setting up a new Stripe account while adding the block to the site.
I tried on a different site but could not reproduce it. Perhaps this issue is in the flow of a new Stripe signup?

**Comment by dsas** [comment] 2022-06-09 13:29
I can't reproduce this @ahmadbaig1, the Stripe connection has had a good overall this year, I doubt this bug would've made it through that. I'll close this issue, but please feel free to reopen if you can reproduce.

**Closed as completed by dsas** 2022-06-09 13:29 UTC
Labels: Bug, Earn, [Block] Payment Button, Payments: before Woo, Payment Blocks
