### ISSUE TITLE
Related Posts Block: allow the display of more than 3 items

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#30101] opened 2019-01-10 19:08 UTC
> by default, the maximum number to be displayed is 3. Soon will the max be at 6 ?

It would be nice if the block allowed you to insert more than 3 posts, just like you can customize the number of posts returned with the regular related posts:
https://jetpack.com/support/related-posts/customize-related-posts/#number

Requested here:
https://jetpack.com/2019/01/10/jetpack-6-9-introducing-more-tools-for-the-new-block-editor/#comment-193506

**Comment by simison** [comment] 2019-01-14 11:37
Duplicate of https://github.com/Automattic/jetpack/issues/11014

I'll copypaste your description there and close this.

**Closed by simison** 2019-01-14 11:37 UTC
Labels: Related Posts, [Goal] Gutenberg, [Type] Enhancement
