### ISSUE TITLE
Auto renew toggle gets removed from UI

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#34340] opened 2019-06-27 12:31 UTC
#### Steps to reproduce
1. Starting at URL: /me/purchases
2. Open the purchase info of a WPCOM plan or a Jetpack plan
3. Click the `Renew now` button
4. In the Checkout page, remove item from cart by clicking the Trash icon

#### What I expected

The purchase info page should not be any different than it was before.

#### What happened instead

The auto renew toggle is missing from the purchase info page.

#### Browser / OS version

Chrome/MacOS

#### Screenshot / Video

![giphy (1)](https://user-images.githubusercontent.com/1269602/60266305-6df26880-9905-11e9-94ec-8eae6fa7f75b.gif)

**Comment by DavidRothstein** [comment] 2019-07-02 05:14
Note that the payment method disappears in this case also, which is an existing (although apparently recent) bug on WordPress.com production -- see internal report pNPgK-4Ci-p2.  It is fixed by a page reload.

The two issues are probably caused by the same underlying bug.  If you're able to figure it out and fix it as part of this, that would be great :)

**Comment by southp** [comment] 2019-07-29 07:50
This has been resolved by code-D30657 from the backend.

**Closed by southp** 2019-07-29 07:50 UTC
Labels: Payment Methods
