### ISSUE TITLE
(5P) Page Templates: Auto loading homepage templates not working for Atomic

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#37523] opened 2019-11-12 17:36 UTC
#### Steps to reproduce
1. On a WordPress.com AT site, make sure that the `Full Site Editing` and `Gutenberg` plugins are active, that a static homepage is set, and activate one of the [auto-loading-homepage](https://wordpress.com/themes/filter/auto-loading-homepage) themes.

#### What I expected

* For the homepage template for that theme to be automatically added and set as the homepage.

#### What happened instead

* The homepage template does not load.

#### Context / Source
p1573319925115000-slack-gutenpages

**Comment by obenland** [comment] 2019-11-12 17:54
This would require an update to the FSE plugin, where we check the templates API endpoint for a homepage template, and if available insert that. I suspect the code for that can largely be lifted from the wpcom mu-plugin.

**Comment by davipontesblog** [comment] 2020-03-10 01:29
I couldn't reproduce this in testing today so I am closing the issue for now. If this happens again, make sure the site is set to have a static homepage as opposed to showing the latest posts as the homepage, which would impede the homepage layout to be applied to the site on theme switch.

**Closed by davipontesblog** 2020-03-10 01:29 UTC
Labels: Atomic, Editor
