### ISSUE TITLE
Premium Content block not available for all paid Jetpack users

### ISSUE THREAD

**Issue by lauac** [Automattic/wp-calypso#46582] opened 2020-10-19 23:53 UTC
@mbhthompson tried to add Premium Content block to one of her test Jetpack sites on a paid plan and wasn't able to add the Premium Content block. Megan, can you please provide more information for the team so we can look into this?

- Site URL
- Screenshot if you have it when you try to add Premium Content block'
- Are you able to add other payments blocks (Payments block and Donations block, namely)

https://wpcomhappy.wordpress.com/2020/08/31/donations-block-launch-tomorrow-sept-1/#comment-32096

**Comment by mbhthompson** [comment] 2020-10-20 00:27
Here's some additional info :)

* Site URL: https://jpbackups-mego.mystagingwebsite.com/
* The site is on the Jetpack Premium plan.
* The only plugins installed are Akismet, Code Snippets, and Jetpack.
* I have access to other payments block, but cannot access the Premium Content block. I've included a brief recording below.

![](https://d.pr/i/VGBIff+)
Link: https://d.pr/i/VGBIff

**Comment by mmtr** [comment] 2020-10-20 09:54
The Premium Content block is not part of Jetpack and therefore not available to Jetpack users. This is the expected behavior right now, but we're considering moving it to Jetpack: 185-gh-dotcom-manage.

**Comment by joendotcom** [comment] 2020-10-21 14:53
@mmtr reopening this because I confirmed in testing that if the WordPress.com Editing Toolkit plugin is installed, indeed the Premium Content block is available. I [recorded this video](https://d.pr/v/69FLwj) to demonstrate.

**Comment by mmtr** [comment] 2020-10-21 16:47
Sorry @joendotcom I don't understand the reasoning behind reopening this issue, that's the expected and intended behavior.

The block is part of the Editing Toolkit plugin, so it requires the plugin to be active in order to work.

**Comment by dkmyta** [comment] 2020-10-22 16:47
Followed up to let the user know.

**Closed by dkmyta** 2020-10-22 16:47 UTC
Labels: [Type] Bug
