### ISSUE TITLE
Gifting: Create account while gifting login flow

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#70354] opened 2022-11-24 03:10 UTC
When you click "Gift" on the gifting banner while logged out the checkout redirects you to the login screen.

If you then attempt to create a new account, you're landed on /start/domains, we should instead be landed back to the checkout, skipping site creation entirely.

Acceptance:

- [ ] Redirect back to the checkout after creating a new account.

Possibly related, possibly needs another issue:

- [x] No longer treat the subscription ID as a site ID. See p2 for repro details pdtkmj-Ks-p2#comment-1246 -> Follow up [here](https://github.com/Automattic/dotcom-forge/issues/1292)

**Comment by lupus2k** [comment] 2022-11-24 19:41
- [x] No longer treat the subscription ID as a site ID
☝️ Fixed in #70390

**Comment by lupus2k** [comment] 2022-11-24 20:06
When creating an account, we land on /start/domains before validating the email. I'm thinking accepting payments from an anonymous user is not correct. What do you think about it?

**Comment by lupus2k** [comment] 2022-11-29 21:56
As the registration flow does not allow you to make payments before verifying your email, we have to investigate if we already have developed a flow that allows this process and apply it when creating an account from the payment of gifts. We will have to develop it if we do not have it yet.
On the other hand, it would be nice to know how many users can use this flow (trying to buy a gift and don't have an account yet) and assess if development is worth it.

**Comment by DavidRothstein** [comment] 2022-11-29 23:07
>As the registration flow does not allow you to make payments before verifying your email

Not sure what that means?  WordPress.com should generally always be allowing payments from un-verified email addresses (for example, that happens during signup).

I think the task here should hopefully be straightforward conceptually (although not necessarily straightforward to implement):
- Currently, when you click "Gift" on a site and are not logged in, you get redirected to a URL like `https://wordpress.com/log-in?redirect_to=%2Fcheckout%2Fpersonal-bundle%2Fgift%2F1234567%3Fcancel_to%3D%2Fhome`.  The `redirect_to` is what allows you to go back to checkout after logging in.
- However, if you click "Create a new account" from that page, you wind up at a URL like `https://wordpress.com/start/user` (the `redirect_to` is gone).

So the goal would be to preserve the `redirect_to` and have it work after account creation.

Alternatively, there is a userless checkout option (currently used by Jetpack) where you can visit checkout while logged out and provide an email address on the checkout screen, and then it creates your account automatically.  It's possible using that would be better.... I think we initially felt it would be complicated to get that working, but we also didn't realize that WordPress.com isn't preserving redirect URLs on the account creation screen.

>On the other hand, it would be nice to know how many users can use this flow (trying to buy a gift and don't have an account yet) and assess if development is worth it.

I don't know how many people will be buying gifts in the first place, but I assume the majority of people who want to buy a gift won't have a WordPress.com account yet.  My assumption is that most visitors to sites that happen to be hosted on WordPress.com are not WordPress.com account holders themselves.

**Comment by lupus2k** [comment] 2022-11-30 18:49
Hey @DavidRothstein, you are right about assuming the users don't have a WordPress.com account. 

About the signup flow, I made some tests, and we can keep the `redirect_to` param when creating an account, but when trying to pay, the checkout page doesn't let you and redirect you back to login because the account is not verified yet.

I like the alternative of using the useless checkout option, do you know where it is using it exactly?

**Comment by DavidRothstein** [comment] 2022-12-01 14:37
>we can keep the `redirect_to` param when creating an account, but when trying to pay, the checkout page doesn't let you and redirect you back to login because the account is not verified yet

How do you reproduce that?  I just tried it now and it worked fine for me:
1. As a logged out user, visit `https://wordpress.com/start/account/user?redirect_to=%2Fcheckout%2Fpersonal-bundle%2Fgift%2FXXXXX%3Fcancel_to%3D%2Fhome` (replace `XXXXX` with the subscription ID of the Personal plan that you are gifting).
2. Create an account.
3. I was immediately redirected to checkout (although there was an odd "Building your site" interstitial before that)
4. I was able to successfully make the gift payment.

>I like the alternative of using the useless checkout option, do you know where it is using it exactly?

You can see it by visiting https://cloud.jetpack.com/pricing as a logged out user and choosing a product.

**Comment by JessBoctor** [comment] 2022-12-06 18:32
From planning: 

@michaeldcain has done some initial investigation into this issue.

**Comment by lupus2k** [comment] 2022-12-07 00:14
I created a [Draft PR](https://github.com/Automattic/wp-calypso/pull/70859) to enable user-less checkout

**Closed as completed** 2022-12-08 19:29 UTC

**Comment by DavidRothstein** [comment] 2022-12-09 23:00
That seems like a great fix and the best user experience for the gifting scenario in the end!

I don't want to lose the bug report for the underlying issue, though (where you lose your redirect destination when creating an account) since that seems like a major user experience problem across WordPress.com, and also because I think @michaeldcain started looking into a fix (although it may be complicated).  So I moved that to a new issue now: https://github.com/Automattic/wp-calypso/issues/71027
