### ISSUE TITLE
Images Added in Columns Appear Vertically

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#29946] opened 2019-01-07 19:26 UTC
1. Add a column block in Chrome.
2. Insert an image into the first column (or embed). 
3. Try to add an image or embed to the second column and note that it drops to the next line - 
![screen shot 2019-01-07 at 2 19 34 pm](https://user-images.githubusercontent.com/2545184/50788471-7f788300-1287-11e9-9381-21a1bcf9f6bf.png)
4. Click on Preview or Publish and see the same result.

The same exact procedure shows expected results in Firefox:
<img width="350" alt="screen shot 2019-01-07 at 2 22 48 pm" src="https://user-images.githubusercontent.com/2545184/50788544-be0e3d80-1287-11e9-8ba2-f27c640a4f1d.png">

####Chrome

**Comment by arunsathiya** [comment] 2019-01-08 07:57
@ChrissiePollock Does that happen at Gutenlypso (https://wordpress.com/block-editor/post) or Calypsoified Gutenberg `{site}/wp-admin/post-new.php`? I am not able to reproduce on either at the moment. [Video](https://cloudup.com/cYEjK3DYM7Y) with Gutenlypso and [video](https://cloudup.com/c6Ylq3EKDwF) with Calypsoified Gutenberg.

Does that happen with specific browser widths, and does it happen for specific sites/images? Or, are you consistently able to reproduce it?

**Comment by jonnyruzek** [comment] 2019-01-13 15:09
Seeing this occur in #1711697-zen as well.

**Comment by ChrissiePollock** [comment] 2019-01-14 22:33
@arunsathiya I just replicated again in Chrome in all three editors. It happened with my screen using different sizes, and today I tried a different YouTube url, and it still happened. It's using the YouTube block within the column block. The url I used this time was https://www.youtube.com/watch?v=E-QGkYNc0Ls&start_radio=1&list=RDE-QGkYNc0Ls.

**Comment by kwight** [comment] 2019-03-05 22:04
Still seeing this @ChrissiePollock ? Today we switched to iframing the block editor in Calypso, and I can't replicate myself (Chrome, with the URL in the above comment):

<img width="1378" alt="screen shot 2019-03-05 at 2 03 04 pm" src="https://user-images.githubusercontent.com/349751/53840659-89e58f00-3f4f-11e9-833a-296f457b7d64.png">

**Comment by gwwar** [comment] 2019-10-26 00:13
There's been a number of Column fixes in recent updates. I'm going to close this out for now, since I haven't had any luck reproducing and no recent reports.

**Closed by gwwar** 2019-10-26 00:13 UTC
Labels: [Goal] Gutenberg, [Status] Needs Author Reply, [Type] Bug
