### ISSUE TITLE
Image block: Unable to rotate image on Simple Sites

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#90943] opened 2024-05-21 14:12 UTC
### Quick summary

On Simple sites, rotating images added to an Image Block is not working as expected.

### Steps to reproduce

1. Start from a simple site and add an Image to a pot
2. Select the Image block, and proceed to click on "Crop" > "Rotate"
3. Notice how nothing happens

### What you expected to happen

Here is how the block works on Atomic sites and is supposed to work on Simple sites:

https://github.com/Automattic/wp-calypso/assets/2540430/02798540-c6f8-4326-824d-e762ee0674f9

### What actually happened

And here, how it isn't working on Simple sites:

https://github.com/Automattic/wp-calypso/assets/2540430/c61db938-d56b-4880-afd3-74fa4fb17b1b

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported on 8120224-zd-a8c

**Comment by liviopv** [comment] 2024-05-23 11:00
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/Automattic/wp-calypso/assets/14153300/4047a6ec-0cd4-47bd-94e4-ffe7eaa0d1fe

📌 ACTIONS
- Requested author feedback

📌 Message to Author
@filipanoscampos As you can see above, I couldn't reproduce. Is that still happening for you? Does it happen with a specific file type?

**Comment by liviopv** [comment] 2024-06-13 09:51
@filipanoscampos closing this one, please reopen if you still need it.

**Closed as completed by liviopv** 2024-06-13 09:51 UTC
Labels: Bug, [Closed] Not Reproducible, Needs triage, Customer report [LEGACY], [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks

**Comment by filipanoscampos** [comment] 2024-06-13 11:28
Sorry, Livio. This got lost in a sea of pings.
I am also no longer able to reproduce this. 🍾
