### ISSUE TITLE
BandPage widget: connection button not available on Calypso

### ISSUE THREAD

**Issue by cecilerainon** [Automattic/wp-calypso#5110] opened 2016-04-29 08:31 UTC
I was updating the documentation with steps from Calypso and noticed it wasn't possible to connect a BandPage account from Customizer → Widgets.

#### What I expected
To see the connection button.

#### What happened instead
It says "Press the Connect button above to import your BandPage content." but the button doesn't appear like it does on WP Admin. In the console, there's a message that says "setup_button is not defined"

#### Browser / OS version
Chrome 50

#### Screenshots

On Calypso:
<img width="291" alt="bandpage-widget-calypso" src="https://cloud.githubusercontent.com/assets/16645645/14911403/69772b90-0df5-11e6-8924-656213ffef9b.png">

On WP Admin:
<img width="421" alt="bandpage-widget-wp-admin" src="https://cloud.githubusercontent.com/assets/16645645/14911419/8bedf168-0df5-11e6-8552-51812cb9b27d.png">

**Comment by lancewillett** [comment] 2016-04-29 16:09
Closing as duplicate of #7723-wpcom (not Calypso specific).

**Closed by lancewillett** 2016-04-29 16:09 UTC
Labels: Customizer, [Type] Bug
