### ISSUE TITLE
Store: Settings Pages Don't Warn on Un-Saved Changes

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#18132] opened 2017-09-19 19:51 UTC
#### Steps to reproduce
1. Visit a store settings page ( any seem to work/have the issue ) https://wordpress.com/store/settings/payments/YOURSITE
2. Make a change on the page, for example enable cash on delivery payment
3. Click the Dashboard link in the nav bar
4. Do not click "Save & Finish"

#### What I expected
I expected to be warned that some changes had not been saved when navigating away from the page - akin to what happens on the standard site settings page.

#### What happened instead
The settings page exists without warning, and the changes to settings are lost and un-saved.

**Comment by justinshreve** [comment] 2017-10-03 18:09
Duplicate of #17271.

**Closed by justinshreve** 2017-10-03 18:09 UTC
Labels: Store
