### ISSUE TITLE
Gutenberg: Backspace deletes too much

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#28473] opened 2018-11-12 22:54 UTC
#### Steps to reproduce
1. Create a new post in wp-admin on WP.com with Gutenberg enabled
2. Type a few words
3. Try to delete just the last word, _but not the space before it_
4. Notice the space deletes

#### What I expected
If I type "Hello Ev" and hit backspace twice, I expect to see "Hello " with a space.

#### What happened instead
I get "Hello" instead without a space. 

#### Browser / OS version
Chrome, Mac; also Chrome, Windows

#### Screenshot / Video
https://cloudup.com/cZPJdPOVvvE

#### Context / Source
https://twitter.com/CharlieEdmunds/status/1062064427770503169

**Comment by aisajib** [comment] 2018-11-13 05:55
I was able to replicate this on a WP.com site with Gutenberg enabled on wp-admin.

**Comment by arunsathiya** [comment] 2018-11-14 03:38
Adding `wp-admin` label as this can be seen on /wp-admin dashboard, in addition to being reproducible on Calypso (https://wpcalypso.wordpress.com/gutenberg/post/)

**Comment by RealCarFax** [comment] 2018-11-14 03:47
I just noticed this as well on my (personal) Premium site as I was building a blog post via Calypso. I use Safari 12.0.1 on MacOS Mohave.

**Comment by wynwin** [comment] 2018-11-16 22:43
I had a recent chat here 5053355-hc where the user reported this issue.

**Comment by supernovia** [comment] 2018-11-19 20:36
Another:
https://twitter.com/ashleyawezum/status/1064573298774822914

**Comment by rantoncuadrado** [comment] 2018-11-24 08:20
Another one. 
1573913-zen
Asking if they are also using Chrome

**Comment by arunsathiya** [comment] 2018-11-24 08:48
@rantoncuadrado Possibly that report is from a few days ago? I am not able to reproduce this anymore.

**Comment by arunsathiya** [comment] 2018-11-24 08:48
This is not reproducible anymore for me. 

On a WordPress.com site, launching from `Add` next to `Blog posts`/`Site pages` I don't see this behaviour at this time. [Video](https://cloudup.com/cbKOC5m-uVy) showing that I am not able to reproduce this at the moment.

@gwwar I am assuming this can be closed, but would like to hear your thoughts.

**Comment by rantoncuadrado** [comment] 2018-11-24 09:07
I assume @arunsathiya that you are using Chrome, right? 🤔

**Comment by arunsathiya** [comment] 2018-11-24 09:13
@rantoncuadrado Yes, Google Chrome Version 70.0.3538.77 (Official Build) (64-bit) on macOS 10.14.1 - Mac OS Mojave.

**Comment by gwwar** [comment] 2018-11-25 21:31
In general, for this many reports, issues should be investigated further. Likely its environment specific, or requires more specific steps.

We'll also want to compare against core Gutenberg. Note for folks taking the issue that we can spin up one quickly using steps in p9dueE-rW-p2

**Comment by mmtr** [comment] 2019-03-22 01:14
Closing this since we don't have any recent report and I cannot reproduce it on the iframed block editor (#31196).

**Closed** 2019-03-22 01:16 UTC
Labels: Calypsoify, [Goal] Gutenberg, [Pri] Normal, [Type] Bug, wp-admin
