### ISSUE TITLE
Font Library: conflict with All In One SEO Pack in the Post/Page Editor in the backend

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#85650] opened 2023-12-21 13:13 UTC
### Quick summary

When All In One SEO Plugin is active, custom fonts that are loaded from the WordPress.com Font Library don't display in the Post/Page Editor, but they do appear normally in the frontend.

The same doesn't happen in a self-hosted, which is why I'm reporting this here, not in the plugin forum.

Editing from the Appearance > Editor > Pages loads fonts normally.

Pinging @arthur791004 in case it's related to your work with the Font Library

### Steps to reproduce

1. On an Atomic site, install All In One SEO Pack plugin
2. Open a page or post in the Post/Page Editor
3. Select a test element and choose a custom font from WordPress.com's font options
4. 

### What you expected to happen

Custom fonts should load regardless of the state of the editor

### What actually happened

Custom fonts don't load in the backend

![CleanShot 2023-12-21 at 13 12 26@2x](https://github.com/Automattic/wp-calypso/assets/14153300/40076386-ccb9-46ee-bec7-15d2844a9cba)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by liviopv** [comment] 2023-12-21 13:13
- [ ] 7465336-zd-a8c

**Comment by maciejpilarski** [comment] 2023-12-26 20:47
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated / Could Not Replicate / Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to reproduce the issue on my test site:
![Markup on 2023-12-26 at 21:45:38](https://github.com/Automattic/wp-calypso/assets/9025643/884f154d-ff84-4725-9339-c1e35ce1348a)

📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)

**Closed as completed by maciejpilarski** 2023-12-26 20:47 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Low, Triaged, [Feature] Google Fonts, Customer report [LEGACY], [Platform] Atomic, [Product] WordPress.com
