### ISSUE TITLE
Themes overview: Theme banner button in front of search input field when scrolling

### ISSUE THREAD

**Issue by syndia** [Automattic/wp-calypso#22976] opened 2018-03-04 23:49 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/themes/{your-site-id}
2. Scroll down
3. Look at the theme banner button

#### What I expected
The button behind the search input field

#### What happened instead
The button is in front of the search input field

#### Browser / OS version
Chrome latest version on Mac OS latest versions

#### Screenshot / Video
<img width="500" alt="schermafbeelding 2018-03-05 om 00 33 49" src="https://user-images.githubusercontent.com/1820680/36952258-ac01782c-200d-11e8-9877-5a64ae8bf737.png">

**Comment by andfinally** [comment] 2018-03-05 10:03
It's possible there's a problem with a specific banner, because when I view https://wordpress.com/themes/xxxxxx.wordpress.com it renders OK for me. Could you please give us a bigger screenshot or tell us which banner (if any) is displayed above the search input?

![themes-banner](https://user-images.githubusercontent.com/1647564/36968917-d626404e-205b-11e8-92e9-2b96c4cc893e.png)

**Comment by syndia** [comment] 2018-03-05 10:24
I see the plans banner  is not showing in my browser. Maybe that will be the problem.

Beforescrolling
<img width="1024" alt="schermafbeelding 2018-03-05 om 11 16 40" src="https://user-images.githubusercontent.com/1820680/36969938-2b6c3c56-2067-11e8-91b7-78e6119f7b92.png">

After scrolling
<img width="1021" alt="schermafbeelding 2018-03-05 om 11 17 19" src="https://user-images.githubusercontent.com/1820680/36970033-7a0249fa-2067-11e8-8031-a1e310dde53e.png">

**Comment by rachelmcr** [comment] 2018-03-05 11:02
I can reproduce the issue at a specific point while I'm scrolling down the page — it seems to be a positioning + z-index issue.

The search field seems to jump up to stick to the top of the screen while the bottom half of the banner (including the button) is still on-screen, and the banner's button has a higher z-index than the search field.

Before:
![screenshot 2018-03-05 10 58 53](https://user-images.githubusercontent.com/8658164/36971716-9e262d22-2064-11e8-842e-ba02413c68b5.png)

Scrolling down a tiny bit more, the search field jumps up:
![screenshot 2018-03-05 10 59 03](https://user-images.githubusercontent.com/8658164/36971717-9f328e7c-2064-11e8-9587-4c69067795ab.png)

**Comment by andfinally** [comment] 2018-03-05 11:04
Thanks @rachelmcr, I was just about to say the same thing!  You're dead right, it seems to be a z-index issue when the banner is scrolled up behind the sticky search bar.

![banner](https://user-images.githubusercontent.com/1647564/36971820-fa0baca2-2064-11e8-9862-415229b9579d.gif)

**Comment by andfinally** [comment] 2018-03-05 11:28
Thanks @syndia and @rachelmcr, I've created PR https://github.com/Automattic/wp-calypso/issues/22976 to address this.

**Comment by andfinally** [comment] 2018-03-05 19:58
Hi @syndia, the fix for this issue has now been deployed - it's looking OK for me. Can you please confirm it's good for you (you may have to flush your browser cache) and close this issue if it is?

**Comment by syndia** [comment] 2018-03-05 20:01
Yes, it's working as expected ;)

**Comment by andfinally** [comment] 2018-03-05 20:04
Thanks! I'll close this one.

**Closed by andfinally** 2018-03-05 20:04 UTC
Labels: OSS Citizen, Themes, [Type] Bug
