### ISSUE TITLE
People: followers list infinite scroll triggers maximum update error

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#25609] opened 2018-06-20 03:24 UTC
#### Steps to reproduce
1. Switch to a site with a large followers list, then head to `/people/followers/{site}`
2. Scroll down to activate the infinite list and the HTTP call to grab the next page of users

#### What I expected
The user can scroll up and down an infinite list.

#### What happened instead
The page locks up and triggers an 'update depth exceeded', hinting at a potential side-effect loop somewhere in the component lifecycle.

<img width="642" alt="screen shot 2018-06-20 at 12 00 52 pm" src="https://user-images.githubusercontent.com/6458278/41635563-c9bc5f70-748c-11e8-95dc-ebf1766994f9.png">

#### Browser / OS version
Chrome

#### Screenshot / Video
![jun-20-2018 12-00-30](https://user-images.githubusercontent.com/6458278/41635558-c4134d04-748c-11e8-8bdc-c13061579e13.gif)

#### Context / Source

#dogfooding

**Comment by ramonjd** [comment] 2018-06-20 03:32
Probable duplicate of #23937, but keeping it open since it affects a different subsection of `People`

**Comment by mattsherman** [comment] 2018-09-19 14:49
Closing this as it is a duplicate of #23937 -- that issue has been updated to make note that it happens for Followers as well.

**Closed by mattsherman** 2018-09-19 14:49 UTC
Labels: People Management, [Type] Bug
