### ISSUE TITLE
Contact form entry visible in add link options.

### ISSUE THREAD

**Issue by maciejpilarski** [Automattic/wp-calypso#13743] opened 2017-05-07 20:03 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/page/oceanfronthomeforsaleireland.com/73
2. Click on the 'Insert/edit link' button
3. On the links to existing content, you will notice the submitted contact form entry:
http://cld.wthms.co/eBcfi <br>![screen shot 2017-05-07 at 21 56 10](https://cloud.githubusercontent.com/assets/1119271/25819281/bf021c16-33ea-11e7-8247-1f70ef602919.png)
4. Link to the entry:
https://oceanfronthomeforsaleireland.wordpress.com/wp-admin/edit.php?post_type=feedback
5. It not visible in the wp-admin:
http://cld.wthms.co/YCeNf <br>![screen shot on 2017-05-07 at 21 3a58 3a49](https://cloud.githubusercontent.com/assets/1119271/25819293/c6ea66fe-33ea-11e7-93ee-6b1206b97f8b.png)

#### What I expected
No link to the entry from the contact form on the links list

#### Screenshot / Video
http://cld.wthms.co/eBcfi
http://cld.wthms.co/YCeNf

**Comment by designsimply** [comment] 2017-05-08 18:37
Thank you for the bug report! I'm closing this one as a duplicate of https://github.com/Automattic/wp-calypso/issues/4940 

Please follow 4940 for updates!

**Closed by designsimply** 2017-05-08 18:37 UTC
Labels: Editor, [Type] Bug
