### ISSUE TITLE
Admin navigation: Clicking Feedback, and then Comments, garbles the icons

### ISSUE THREAD

**Issue by jasmussen** [Automattic/wp-calypso#93944] opened 2024-08-27 10:21 UTC
### Quick summary

If you click Feedback, then click another menu item, like Comments, the icons get garbled. GIF:

![bug](https://github.com/user-attachments/assets/82a40061-6496-4613-a2ed-f0fe71d5ea92)

### Steps to reproduce

1. Click "Feedback"
2. Click "Comments"

### What you expected to happen

Icons were unchanged.

### What actually happened

Icons were garbled.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Chrome.

**Comment by retnonindya** [comment] 2024-08-29 05:31
Thanks for the report, @jasmussen! I can't seem able to replicate it:

![Aug-29-2024 13-24-04](https://github.com/user-attachments/assets/e2b84fa4-5a2c-435b-b339-b9a8f0d54080)

That said, I remember this issue was discussed (and is still being discussed) back in July: https://github.com/Automattic/dotcom-forge/issues/8405 -- and the cause was the font icon. Since the team already aware of it and planning to move to SVG icon, I'm going to close this bug report.

**Closed as completed by retnonindya** 2024-08-29 05:31 UTC
Labels: Bug, [Pri] High, [Feature] Calypso & wp-admin Navigation, Triaged, [Platform] Simple, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Other Infrastructure
