### ISSUE TITLE
Greater-than sign appears if replying to a comment by email 

### ISSUE THREAD

**Issue by eurello** [Automattic/wp-calypso#56510] opened 2021-09-23 15:07 UTC
### Quick summary

When you reply to a comment by email, a greater-than symbol is posted after your comment: 

<img width="661" alt="Screen Shot 2021-09-23 at 10 08 56 AM" src="https://user-images.githubusercontent.com/8698879/134533713-a77676c4-2531-4e58-9bb6-553aeb2fed95.png">

### Steps to reproduce

1. Post a comment on your blog. 
2. Open the email notification of the comment. 
3. Click reply in your email client and add a comment, then click send. 
4. The comment appears on the blog, and a greater-than symbol will appear below it. 

This does not happen if you reply to the comment elsewhere other than by email. 

### What you expected to happen

The comment would appear without an extraneous symbol. 

### What actually happened

The comment appeared with a greater-than symbol after it. 

### Context

I've noticed this several times on my own blog and other people's but only just figured out where it was coming from. 

### Operating System

macOS

### Reproducibility

Consistent

### Severity

All

**Comment by formosattic** [comment] 2021-09-28 07:36
Strange, I can't reproduce. I tested with Exford, Twenty Twenty One. Is it still happening?

![image](https://user-images.githubusercontent.com/15944096/135042582-4601b65b-6c7c-49f2-a31f-bf01a53a2594.png)

Pinged for other details: p1632814538296900-slack-C01UW7SB411

**Comment by eurello** [comment] 2021-09-28 13:22
Yes, still happening, and it's not just me. I've seen this symbol appear in author comments on many blogs over the years, but I never figured out what was causing it until it happened to me.

**Comment by eurello** [comment] 2021-09-28 13:23
Theme on my blog is Blank Canvas, but I've definitely seen it with other themes. It's a simple site, not Atomic.

**Comment by formosattic** [comment] 2021-10-02 09:00
Closing as unable to reproduce.

Please, open if it happens again.

**Closed as completed by formosattic** 2021-10-02 09:00 UTC
Labels: Bug, [Status] Needs Author Reply
