### ISSUE TITLE
Nav Unification: Menu tab 'Page' incorrect in Dutch

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/wp-calypso#51439] opened 2021-03-26 09:34 UTC
### Steps to reproduce the behavior

1. Go to account with the language set in Dutch
2. You will view the menu tab 'Page' incorrectly showing in the left-hand menu.

#### What I expected to happen

I expect the page tab to say `Pagina's`

#### What actually happened

It says `Pagina&#039;s`

I am able to replicate on test site: 

![Screenshot](https://d.pr/i/wYAtjm+)
*If you are unable to see this image, please click [here](https://d.pr/i/wYAtjm)*

**Comment by Aurorum** [comment] 2021-03-26 12:23
Duplicate of #51390, though should be fixed by #51418! :)

**Closed as completed** 2021-03-29 11:18 UTC
Labels: Bug, [Feature] Calypso & wp-admin Navigation, Triaged
