### ISSUE TITLE
Stats: Hide the navigation arrows on empty charts

### ISSUE THREAD

**Issue by wilmersondasilva** [Automattic/wp-calypso#72180] opened 2023-01-16 22:49 UTC
Created from this comment: https://github.com/Automattic/wp-calypso/issues/71021#issuecomment-1384557900

Hide the navigation arrows when there's no data is available on the Stats charts

![Image](https://user-images.githubusercontent.com/6406071/212776314-1fcf55b2-89c4-4b67-a1c1-b6de3047d45d.png)

**Comment by kangzj** [comment] 2023-05-15 05:42
I had a look at the issue. IMO we shouldn't disable the previous arrow when there's no data available in the current period, because there could be data in older periods. If we remove the ability to move dates back then these old dates would become in-accessible.

I looked at how the the other charts implemented this.

- Use the date when the feature went online, and disable when the current date is the date: https://github.com/Automattic/wp-calypso/blob/6709845d8e026c473add8cb361d0ac623894bc06/client/my-sites/stats/wordads/index.jsx#L135

- Insights is using the date (year) when the oldest posts were published: https://github.com/Automattic/wp-calypso/blob/6709845d8e026c473add8cb361d0ac623894bc06/client/my-sites/stats/annual-highlights-section/index.tsx#L80

However, I'm not keen to fix this as IMHO it is the expected behavior and also it would cause any security concern, so I'll close the issue for now and feel free to reopen if you think otherwise.

@dognose24 @wilmersondasilva @jeffgolenski

**Closed as completed by kangzj** 2023-05-15 05:42 UTC
Labels: [Feature] Stats
