### ISSUE TITLE
Blank Canvas 3: Font family selector missing in Styles > Typography

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#72919] opened 2023-02-02 14:27 UTC
### Quick summary

One of our customers reported that the fonts on their site changed, seemingly overnight. They are using the Blank Canvas 3 theme. They explained as follows:

>We use Blank Canvas theme with Default font, the font was a sans serif style font. The site was OK yesterday, but today on both mobile and desktop browsers, the font has reverted to a serif font.

I have been able to reproduce this on a test site using the same theme. Other, recent themes display the option to change the font family though.

**Update**: I just did some additional testing, and noticed that rather than setting a display font, Blank Canvas 3 will use the default font set in the user's browser. Is this intended behavior?

### Steps to reproduce

1. Open the Site Editor in **Appearance** > **Editor**
2. Click to edit a template, and open the Styles panel in the upper right
3. Select the main **Typography** option, and then select **Text**
4. Note that when the site uses Blank Canvas 3, there is no option to change the **FONT**
5. If you then switch the site over to another recent theme such as Twenty Twenty-Three, the **FONT** dropdown is available in Styles

### What you expected to happen

When accessing the Typography options in Styles, the editor should present a dropdown to select a **FONT**, like this:

![Capture_2023-02-02 at 16 14 08@2x](https://user-images.githubusercontent.com/2912202/216350819-ea580c34-e522-4944-9db1-a1f27fd13d64.png)

### What actually happened

When the site uses Blank Canvas 3, the **FONT** option is not available.

![Capture_2023-02-02 at 16 26 00@2x](https://user-images.githubusercontent.com/2912202/216351294-a680a678-2c6f-492c-b72f-2e980cd41e6a.png)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Theme: Blank Canvas 3
Report in 5920270-zen

**Comment by ClassicRKR27** [comment] 2023-02-02 14:50
I have another report here: 38697226-hc

Switching to twenty twenty-three to test resolved issue but user wants to keep using blank canvas.

Follow-up ticket: 5922644-zd-woothemes

**Comment by cuemarie** [comment] 2023-02-02 20:56
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Could not replicate
- Tested on AT: Could not replicate
- Tested on Self-hosted: Could not replicate
- Replicable on Core? *No

📌 FINDINGS/SCREENSHOTS/VIDEO
- My AT site showed the same font dropdown under Styles > Typography > Text when using both TT3 and Blank Canvas 3. 

Screenshot of Styles > Typography > Text in Blank Canvas 3 on my test site:

<img width="314" alt="Markup 2023-02-02 at 13 49 15" src="https://user-images.githubusercontent.com/27249804/216446336-6e2cd37b-0cf6-45f1-8946-fe59fb13c3a1.png">

📌 ACTIONS
- Closed as not reproducible

📌 Message to Author
- @ClassicRKR27 and @pauljacobson I checked the sites from the reports above and it looks like their fonts are back - all signs indicate this issue is already resolved!

**Closed as completed by cuemarie** 2023-02-02 20:56 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] High, Triaged, [Platform] Atomic, [Feature] Global Styles
