### ISSUE TITLE
Shortcodes: SoundCloud shortcodes with an invalid link do not display the proper error on the mobile web

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#44722] opened 2020-08-05 21:28 UTC
Steps to reproduce:

1. Create a new post.
1. Add a title.
1. Add a SoundCloud shortcode with an invalid SoundCloud link. Sample code:<br>```[soundcloud url=”https://soundcloud.com/claude-de-lune”] ```
1. Publish and view the post on the web and on the mobile web.

**Result:** using a desktop browser, SoundCloud embeds that have an invalid link display an error that says "You have not provided a valid SoundCloud URL" while on mobile web the error does not show and you see a "Play on SoundCloud" button instead and pressing the button leads to a completely blank page. ([https://cloudup.com/cpYnEc6PXrs 30s]) (​[30s](https://cloudup.com/cpYnEc6PXrs))

<img height="300" alt="6BvcoxWgKw" src="https://user-images.githubusercontent.com/1119271/89465699-c5c9e880-d72f-11ea-9f3f-a0d964990452.png"> <img src="https://user-images.githubusercontent.com/1119271/89465692-c4002500-d72f-11ea-928a-6aaa41878eb9.png" height="300" alt="qMfCzPRa4v"> <img src="https://user-images.githubusercontent.com/1119271/89465690-c2cef800-d72f-11ea-8392-04d642a41c7d.png" height="300" alt="zBvkhkL_gl"> 

<p style="clear:both;"><sup>Tested with Safari 13.1.1 on macOS 10.15.4 and Safari iOS 13.6 on an iPhone 11. Moved from ​WordPress-iOS/13339 then 8221-wpcom.</sup></p>

**Comment by obenland** [comment] 2021-01-18 23:05
I was able to reproduce it on a test site. This seems to be SoundCloud bug, I'm not sure what we'd do about it. What would be the best way to pass that on to them?

**Comment by cathymcbride** [comment] 2021-02-25 16:44
Issue is on the Soundcloud side, so there isn't really anything we can do about it. Closing...

**Closed by cathymcbride** 2021-02-25 16:44 UTC
Labels: Mobile Web, Shortcodes, [Pri] Low, [Size] XS, [Type] Bug
