### ISSUE TITLE
Can't start application

### ISSUE THREAD

**Issue by enahsor** [Automattic/wp-calypso#46254] opened 2020-10-08 03:21 UTC
#### Steps to reproduce
This is my first attempt at contributing to Calypso but unfortunately, I can't seem to get past the getting started section 😅

I followed the instructions in the [Getting Started](https://github.com/Automattic/wp-calypso#getting-started) section of the readme.
Executed commands as listed:
1. `yarn`
1. `yarn start`

#### What I expected

I expected the application to start.

#### What happened instead

Application failed to start and provided me with this nice message 🙁:

```cli
yarn run v1.22.4
$ npx check-node-version --package && node bin/welcome.js
             _
    ___ __ _| |_   _ _ __  ___  ___
   / __/ _` | | | | | '_ \/ __|/ _ \
  | (_| (_| | | |_| | |_) \__ \ (_) |
   \___\__,_|_|\__, | .__/|___/\___/
               |___/|_|

$ yarn run -s build
$ node bin/install-if-deps-outdated.js
$ node bin/download-languages-meta.js
$ npx ncp static public
$ npx lerna run prepare --stream
lerna notice cli v3.20.2
lerna info versioning independent
lerna info Executing command in 23 packages: "yarn run prepare"
@automattic/calypso-color-schemes: $ node bin/prepare-sass-assets.js && node bin/build-css.js
@automattic/components: $ transpile && tsc && copy-assets
i18n-calypso: $ transpile
@automattic/load-script: $ transpile
@automattic/media-library: $ transpile && tsc && copy-assets
@automattic/components: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\components
photon: $ transpile
i18n-calypso: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\i18n-calypso
@automattic/load-script: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\load-script
@automattic/popup-monitor: $ transpile
@automattic/media-library: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\media-library
@automattic/react-i18n: $ tsc --project ./tsconfig.json && tsc --project ./tsconfig-cjs.json
photon: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\photon
@automattic/popup-monitor: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\popup-monitor
@automattic/social-previews: $ transpile && copy-assets
@automattic/social-previews: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\social-previews
@automattic/tree-select: $ transpile
@automattic/viewport: $ transpile
@automattic/tree-select: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\tree-select
wpcom-proxy-request: $ transpile
@automattic/viewport: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\viewport
wpcom-proxy-request: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\wpcom-proxy-request
@automattic/format-currency: $ transpile
@automattic/format-currency: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\format-currency
@automattic/request-external-access: $ transpile
@automattic/calypso-analytics: $ tsc --project ./tsconfig.json && tsc --project ./tsconfig-cjs.json
@automattic/viewport-react: $ transpile
@automattic/request-external-access: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\request-external-access
@automattic/viewport-react: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\viewport-react
@automattic/browser-data-collector: $ tsc --project ./tsconfig.json && tsc --project ./tsconfig-cjs.json
@automattic/data-stores: $ tsc --project ./tsconfig.json && tsc --project ./tsconfig-cjs.json
wpcom: $ run-s build:modules build:bundle
@automattic/composite-checkout: $ tsc --project ./tsconfig.json && tsc --project ./tsconfig-cjs.json
wpcom: $ transpile
wpcom: Building C:\Users\drobinson\Desktop\OS\wp-calypso\packages\wpcom.js
wpcom: $ webpack --display errors-only
wpcom: Insufficient number of arguments or no entry found.
wpcom: Alternatively, run 'webpack(-cli) --help' for usage info.
wpcom: ERROR in Entry module not found: Error: Can't resolve 'C:\Users\drobinson\Desktop\OS\wp-calypso\packages\wpcom.js/dist/esm/index.js' in 'C:\Users\drobinson\Desktop\OS\wp-calypso\packages\wpcom.js'
wpcom: error Command failed with exit code 2.
wpcom: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
wpcom: ERROR: "build:bundle" exited with 2.
wpcom: error Command failed with exit code 1.
wpcom: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run prepare exited 1 in 'wpcom'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

#### Browser / OS version

```
OS Name   Microsoft Windows 10 Pro
Version      10.0.18363 Build 18363

```

Did I miss something?

#### Things I tried

1. Removing `node_modules/`
1. Re-running `yarn`

**Comment by sirreal** [comment] 2020-10-21 15:45
Thanks for the report!

> wpcom: ERROR in Entry module not found: Error: Can't resolve 'C:\Users\…\wp-calypso\packages\wpcom.js/dist/esm/index.js' in 'C:\Users\…\wp-calypso\packages\wpcom.js'

This looks like a platform directory separator problem notice how it starts with Windows paths `C:\` then transitions to `/` after wpcom.js:`C:\Users\…\wp-calypso\packages\wpcom.js/dist/esm/index.js`. It looks like simple concatenation with the `module` line here:

https://github.com/Automattic/wp-calypso/blob/97eafcf5d15ecf1a760e2058785f7ee215d47da7/packages/wpcom.js/package.json#L6 

@enahsor If you modify that line to use Windows-style directory separators (`\`) does it work better, or do you get a different error at least?

**Comment by prabhunimish** [comment] 2020-10-29 23:51
Facing same issue. The dist directory has "esm" and "cjs" folders inside them but both of these folders are empty for some reason.
I tried to run `yarn run clean` and `yarn run prepare` inside wpcom.js folder but got same error again.

**Comment by scinos** [comment] 2020-11-03 06:22
@prabhunimish I think this was caused by a bad path concatenation in `wpcom.js` package. I just merged a fix for it.

Would you mind updating your branch with the latest master and see if the error is still there?

**Comment by enahsor** [comment] 2020-11-03 11:52
Hey guys, thanks for taking the time to address this issue. 
@scinos I merged your fix into main and it fixed the error I had but I'm now getting a completely different error.
Is this the appropriate place to discuss or should I raise a new issue after closing this?

**Comment by scinos** [comment] 2020-11-03 12:36
@enahsor I'm happy to continue diagnosing the problem in this issue, we can do a clean up later when we find the problem.

**Comment by enahsor** [comment] 2020-11-03 13:02
@scinos  awesome! thanks! 
This is the new error I'm getting:
```
$ run-p -s build-css:*
Rendering Complete, saving .css file...
Wrote CSS to C:\Users\drobinson\Desktop\OS\wp-calypso\public\directly.css
Rendering Complete, saving .css file...
Wrote CSS to C:\Users\drobinson\Desktop\OS\wp-calypso\public\reader-mobile.css
Rendering Complete, saving .css file...
Wrote CSS to C:\Users\drobinson\Desktop\OS\wp-calypso\public\editor.css
'BROWSERSLIST_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I assume it's trying to run a script that calls `BROWSERSLIST_ENV`. I took a look at the package.json and quite a few scripts depend on that command.

**Comment by prabhunimish** [comment] 2020-11-03 20:41
Yes, I also tried, yarn command worked fine but facing `BROWSERLIST_ENV` issue now same as mentioned by @enahsor.

I believe instead of setting values it is considering it as an executable. I tried to replace it with `set BROWSERLIST_ENV=evergreen && <next commands>`, which helped to pass to the next commands, but then this error occurred:
`$ set BROWSERSLIST_ENV=evergreen && yarn run start-build-do
$ node ${NODE_ARGS:---max-old-space_size=8192} build/server.js | bunyan -o short
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'D:\Work\Projects\React\calypso\${NODE_ARGS:---max-old-space_size=8192}'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

**Comment by sirreal** [comment] 2020-11-04 13:09
We'd need to use something like [`cross-env`](https://www.npmjs.com/package/cross-env) for all these scripts of the form `ENV_VAR="foo" some-command-to-run`:

https://github.com/Automattic/wp-calypso/blob/cd6080bd6e91fa46efbe5dbf5a49e20a46f636f4/package.json#L82-L94

**Comment by pinguluk** [comment] 2020-11-19 12:37
Any fix for the `'BROWSERSLIST_ENV' is not recognized as an internal or external command,
operable program or batch file.` ?

**Comment by sirreal** [comment] 2020-11-19 19:37
@pinguluk yes, this comment suggests the fix https://github.com/Automattic/wp-calypso/issues/46254#issuecomment-721722235

If someone would like to create a PR, I'd gladly review.

**Comment by enahsor** [comment] 2020-11-19 19:48
You know what, I'll take a at crack it @sirreal

**Comment by enahsor** [comment] 2020-11-20 14:55
@sirreal I added the cross-env package and prefixed most of the scripts that are using the `BROWSERSLIST` env variable. I'm running into another issue though. The application seems to be looking for a `@automattic/calypso-color-schemes/js` but isn't able to find it. I checked both the packages and node_modules folders and there's no `js` folder in the `calypso-color-schemes` folder.
I've also checked locally in a separate project and `@automattic/calypso-color-schemes` just doesn't have a `js` folder. 
Here's the trace I got after running `yarn start`:

```
yarn run v1.22.10
$ npx check-node-version --package && node bin/welcome.js
             _
    ___ __ _| |_   _ _ __  ___  ___      
   / __/ _` | | | | | '_ \/ __|/ _ \ 
  | (_| (_| | | |_| | |_) \__ \ (_) |  
   \___\__,_|_|\__, | .__/|___/\___/ 
               |___/|_|

$ yarn run -s build
$ npx ncp static public && npx ncp client/lib/service-worker public --filter="service-worker(/service-worker\.js)?$"
$ run-p -s build-css:*
Rendering Complete, saving .css file...
Wrote CSS to C:\Users\drobinson\Desktop\OS\wp-calypso\public\directly.css
Rendering Complete, saving .css file...
Wrote CSS to C:\Users\drobinson\Desktop\OS\wp-calypso\public\reader-mobile.css
$ run-p -s start-build-if-web start-build-if-desktop
$ run-p -s start-build-web-if-fallback start-build-web-if-evergreen
$ cross-env BROWSERSLIST_ENV=evergreen yarn run start-build-do
$ node build/server.js ${NODE_ARGS:---max-old-space_size=8192}  | bunyan -o short
Error: Cannot find module '@automattic/calypso-color-schemes/js'
Require stack:
- C:\Users\drobinson\Desktop\OS\wp-calypso\client\webpack.config.js
- C:\Users\drobinson\Desktop\OS\wp-calypso\build\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\drobinson\Desktop\OS\wp-calypso\client\webpack.config.js:21:29)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
Done in 25.16s.
```

**Comment by scinos** [comment] 2020-11-20 15:03
`@automattic/calypso-color-schemes/js` should be created during the initial `yarn install` (or just `yarn`, it is the same). Could you paste that log?

**Comment by enahsor** [comment] 2020-11-20 15:06
Sure 

```
$ yarn
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @automattic/data-stores@1.0.0-alpha.1" has unmet peer dependency "@wordpress/data@^4".
warning "@automattic/data-stores > @wordpress/url > react-native-url-polyfill@1.1.2" has unmet peer dependency "react-native@*".
warning " > @storybook/preset-scss@1.0.3" has unmet peer dependency "css-loader@*".
warning " > @storybook/preset-scss@1.0.3" has unmet peer dependency "sass-loader@*".
warning "@wordpress/components > @emotion/native@10.0.27" has unmet peer dependency "react-native@>=0.14.0 <1".
warning "@wordpress/components > react-dates > react-with-styles@3.2.3" has unmet peer dependency "react-with-direction@^1.1.0".
warning " > @wordpress/npm-package-json-lint-config@3.1.0" has unmet peer dependency "npm-package-json-lint@>=3.6.0".
warning " > @automattic/domain-picker@1.0.0-alpha.0" has unmet peer dependency "@wordpress/data@^4.22.3".
warning " > @automattic/launch@1.0.0" has unmet peer dependency "@wordpress/data@^4.22.3".
warning " > @automattic/plans-grid@1.0.0-alpha.0" has unmet peer dependency "@wordpress/data@^4.22.3".
warning "calypso > fake-indexeddb > realistic-structured-clone > typeson@5.18.2" has unmet peer dependency "core-js-bundle@^3.6.4".
warning "calypso > fake-indexeddb > realistic-structured-clone > typeson@5.18.2" has unmet peer dependency "regenerator-runtime@^0.13.3".
warning "calypso > fake-indexeddb > realistic-structured-clone > typeson-registry > base64-arraybuffer-es6@0.5.0" has unmet peer dependency "core-js-bundle@^3.1.3".
warning " > chai-enzyme@1.0.0-beta.1" has unmet peer dependency "cheerio@0.19.x || 0.20.x || 0.22.x || ^1.0.0-0".
warning " > eslint-plugin-prettier@3.1.4" has unmet peer dependency "prettier@>=1.13.0".
warning " > spec-xunit-reporter@0.0.1" has unmet peer dependency "mocha@^5.2.0".
warning "workspace-aggregator-39cdc8d7-7cdb-4f4f-b833-20a3c1db2d63 > @automattic/i18n-utils > @testing-library/react-hooks@3.4.2" has unmet peer dependency "react-test-renderer@>=16.9.0".
warning "workspace-aggregator-39cdc8d7-7cdb-4f4f-b833-20a3c1db2d63 > @automattic/wpcom-editing-toolkit > @wordpress/scripts > jest-puppeteer@4.4.0" has incorrect peer dependency "puppeteer@>= 1.5.0 < 3".
[5/5] Building fresh packages...
$ test -n "$DISABLEPOSTINSTALL" || ((node -e "process.exit(process.env.CALYPSO_DOCTOR_SKIP !== 'true')" || yarn run calypso-doctor) && yarn run build-packages)
Done in 315.59s.
```

**Comment by scinos** [comment] 2020-11-20 15:16
`$ test -n "$DISABLEPOSTINSTALL" || ((node -e "process.exit(process.env.CALYPSO_DOCTOR_SKIP !== 'true')" || yarn run calypso-doctor) && yarn run build-packages)` should populate `@automattic/calypso-color-schemes/js`.

My guess is that script only works in Unix systems, but I don't know enough about Windows to suggest a potential fix, sorry :(

In general, I think having Calypso in Windows natively is going to be hard. Even if we can figure out all the problems and fix them now, it will be a "delicate equilibrium", there is no guarantee it will remain Windows compatible. I'd suggest looking at using [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/) or a Docker dev environment

**Comment by enahsor** [comment] 2020-11-20 15:27
@scinos  Yikes. Should the readme be updated to indicate this to prevent similar issues being added in the future?
I guess I should close this issue?

**Comment by cathymcbride** [comment] 2021-02-08 17:44
Closing based on the above.

**Closed by cathymcbride** 2021-02-08 17:44 UTC
Labels: Build, OSS Citizen, Windows, [Type] Bug
