### ISSUE TITLE
Gutenberg - Text Links not rendering correctly in the editor

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#41844] opened 2020-05-06 03:14 UTC
The text links are showing as regular text in the editor.
HTML code is there and the text links show ok on the site.

**Temporary solution:** use the Classic block

Issue happened with:

* Gutenberg v8.0
* ~~only on Simple sites~~
* themes like [Independent Publisher 2](https://wordpress.com/theme/independent-publisher-2), [Penscratch 2](https://wordpress.com/theme/penscratch-2), others could apply but I'm not sure what would be the common factor of those themes. 

Also tested with TwentyTwenty, ~~and on a self-hosted site,~~ but that was fine.

![gif](https://user-images.githubusercontent.com/15944096/81135069-522a0b00-8f89-11ea-8ba4-4da5f94880e6.gif)

**Comment by sirreal** [comment] 2020-05-06 12:46
Thanks for the report.

This is not limited to Simple Sites. The issue also appears on Atomic and .org sites for any themes that do not style `a` elements in the editor.

It's a regression in the sense that default link styling has changed in the editor, but themes should be styling links in the editor.

I've created https://github.com/WordPress/gutenberg/issues/22139 in Gutenberg to discuss.

**Comment by sirreal** [comment] 2020-05-06 12:50
We should consider shipping a patch as part of FSE to restore the link colors.

Independently, we can and should patch themes to include link colors in the editor.

**Comment by sirreal** [comment] 2020-05-08 08:11
Gutenberg patched this so we can expect a fix in an upcoming release:

https://github.com/WordPress/gutenberg/pull/22160

**Comment by eduardozulian** [comment] 2020-05-08 14:09
For the record, another case in 15105045-hc

**Comment by sirreal** [comment] 2020-05-08 15:07
Proposed fix in https://github.com/Automattic/wp-calypso/pull/41992

**Comment by eduardozulian** [comment] 2020-05-14 16:26
@sirreal closing this one since it was merged into Calypso. Thanks!

**Closed by eduardozulian** 2020-05-14 16:26 UTC
Labels: Blocks, [Type] Bug
