### ISSUE TITLE
Posts: Reblog/Likes not loading for users in Germany

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#23313] opened 2018-03-14 20:42 UTC
A user has reported that this site isn't showing Likes/Reblogs in Germany, on this post:
https://findesatz.blog/2018/03/13/13-maerz-3/

#### What I expected
Here is what I see:
![screen shot 2018-03-14 at 1 33 23 pm](https://user-images.githubusercontent.com/8921630/37429407-5cfff0f6-278c-11e8-8a6c-6dba90a20ba5.png)

#### What happened instead
Here is what they see:
![2f33803f](https://user-images.githubusercontent.com/8921630/37429409-60c64208-278c-11e8-88dd-3c8641ab01e0.png)

#### Browser / OS version
The user has tested Firefox, Chrome, and Edge, all in Windows (10 I believe).
They also tested their Android smartphone.
They said it has been going on about 5 hours.
They also had their friends try (also in Germany) and they are also not seeing them load.

#### Screenshot / Video
I asked for some screenshots of their console log to get these back:
![4d676632 1](https://user-images.githubusercontent.com/8921630/37429562-f0cd60e8-278c-11e8-9145-bca65fc68d49.png)
 (Chrome)
The full link next to the `No Local meta information provided` is `https://s0.wp.com/_static/??/wp-content/js/postmessage.js,/wp-content/js/jed/jed.js,/wp-content/js/wpcom-proxy-request.js,/wp-content/js/likes-rest-nojquery.js?m=20180221`

#### Context / Source
Came from an email to WPCOM support. 1017994-zen

This is a Personal Site, hosted on WordPress.com

The triage channel thought that perhaps it was related to the German translation, but I put my test site to Deutsch and it still loads fine in the States:
https://18personal.wordpress.com/2018/03/08/small-text/

**Comment by molszewska** [comment] 2018-03-15 08:51
Thanks to a very helpful analysis performed by the user, it looks like wp-german language settings cause the error, while e.g. wp-english, wp-dutch ... don't trigger the error.
(1017994-zen)

**Comment by grvrulz** [comment] 2018-03-15 09:49
Exact same report for this site, in Italian:
https://foodieduepuntozero.com/

#2065920-hc

The user shared screenshots of console:
![screenshot-3](https://user-images.githubusercontent.com/1659416/37455658-94a194c4-2863-11e8-96f0-30f3de3b8028.png)
![screenshot-5](https://user-images.githubusercontent.com/1659416/37455660-96a88548-2863-11e8-8cd1-c4916b18669b.png)

The issue goes away when the site's language is switched to English. I have been unable to reproduce it, but I will switch my computer's language, and try to reproduce it in different browsers in a bit.

**Comment by kriskorn** [comment] 2018-03-15 10:42
Another report here in Italian again - https://woothemes.zendesk.com/agent/tickets/1018073
Site: https://elisabettagnone.blog/

**Comment by lsinger** [comment] 2018-03-15 10:47
On a device set to English but used in Germany: 

- Can reproduce the German site's issue. Site language is German even though device is English. 
- Can't reproduce Italian site's issue. Likes load fine. Site language is English for me, though.

**Comment by rachelmcr** [comment] 2018-03-15 10:51
This issue is also occurring in Japanese, reported in https://github.com/Automattic/wp-calypso/issues/22977. As noted there, since the issue is not in Calypso it was moved to 8016-wpcom.

I'm going to close this report and move the reported cases to that ticket. Please add any further cases on that ticket. Thanks for raising the issue!

**Closed by rachelmcr** 2018-03-15 10:51 UTC
Labels: Posts, [Type] Bug

**Comment by thabotswana** [comment] 2018-03-15 11:26
This issue is also happening on this site:

https://wolfgangschnier.com/
language: German

Jetpack Likes in perpetual state of "Loading..."

https://mc.a8c.com//support-stats/happychat/transcript.php?id=2067066

**Comment by fstath** [comment] 2018-03-15 13:26
I have several users in the forums reporting the same issue for Swedish and German WordPress.com hosted sites. The Like button loads fine on my end though.

Here's the forum thread:
https://mc.a8c.com/happiness/tqr/?topic_id=892886&in_queue=1

These are the reported sites:
https://baraenbildavmig.wordpress.com/
https://ankisbildblogg.wordpress.com/
https://replicantcore.wordpress.com/

Here are a couple of screenshots:
![lzh6mz](https://user-images.githubusercontent.com/32326882/37465879-080e63be-2865-11e8-8e29-0dcfc30b195f.jpg)
![btmnla](https://user-images.githubusercontent.com/32326882/37465894-12c1d1b0-2865-11e8-9c82-935119b05bb4.jpg)

**Comment by lsinger** [comment] 2018-03-15 14:07
> Please add any further cases on that ticket. 

😬
