### ISSUE TITLE
Gutenberg: Publicize switch from "published" to "draft" causes UI toggle breakdown

### ISSUE THREAD

**Issue by mapk** [Automattic/wp-calypso#28701] opened 2018-11-20 00:49 UTC
As found by Jorge Calle, when switching a post from "published" back to "draft" there's a weird UI issue on the toggles in the Publicize pre-publish sheet.

![screen shot on 2018-11-19 at 18-25-40](https://user-images.githubusercontent.com/617986/48744147-e3cd7d80-ec1a-11e8-8aa6-cb5ae3c9aa6d.png)

**Comment by ockham** [comment] 2018-11-20 12:57
It's curious that Gutenberg's [`FormToggle` component](https://github.com/WordPress/gutenberg/tree/015e1440842d1a6bd3c151290adaebc63be0b73a/packages/components/src/form-toggle) doesn't really provide any styling for the `disabled` state.

**Comment by tyxla** [comment] 2018-11-20 12:59
Seems like they suggest providing opacity of 0.5 when disabled in their readme though..

**Comment by ockham** [comment] 2018-11-20 13:00
That looked more like an example to me, TBH. But yeah, that could work for starters. Tho that logic really should be part of the upstream component IMO.

**Comment by tyxla** [comment] 2018-11-20 13:08
> that logic really should be part of the upstream component

I agree.

**Comment by simison** [comment] 2018-11-20 13:20
Visible borders around disabled toggles will be fixed in v5.0: 

https://github.com/WordPress/gutenberg/pull/12091
https://github.com/Automattic/wp-calypso/issues/28659#issuecomment-440228637

We'll need to get it sorted for Calypso separately though: 
https://github.com/Automattic/wp-calypso/issues/28707

**Comment by simison** [comment] 2018-11-20 13:22
I'm not so sure if the above fixes this blue square, though:

<img width="51" alt="image" src="https://user-images.githubusercontent.com/87168/48776251-0b365000-ecd8-11e8-9f2e-3c18eb1317b1.png">

**Comment by ockham** [comment] 2018-11-20 13:43
@simison So this is possibly a dupe of #28707?

**Comment by ockham** [comment] 2018-11-20 18:11
Closing, since this is either a dupe of #28707, or if it isn't, it's fixed by https://github.com/WordPress/gutenberg/pull/12091. Furthermore, #28723 adds more `disabled` styling.

**Closed by ockham** 2018-11-20 18:11 UTC
Labels: Jetpack, [Goal] Gutenberg, [Pri] High

**Comment by simison** [comment] 2018-11-20 18:15
> So this is possibly a dupe of #28707?

It'll still probably look broken in Calypso but in a different way; I'd worry about that later.

Gutenberg PR fixes this for wp-admin Gutenberg so good to close. 👍
