### ISSUE TITLE
CoBlocks Masonry Block: Link to Attachment Pages not working, no link added

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#50120] opened 2021-02-16 10:25 UTC
### Steps to reproduce the behavior

1. Add a Masonry block to a page with a few images
2. Choose Attachment Page under Link Settings > Link to
3. Preview/publish page

#### What I expected to happen

Images will be clickable and load attachment page when clicked

#### What actually happened

Images are not clickable/no link is added

#### Browser / OS version

Firefox 85 on macOS (Big Sur)

#### Is this specific to the applied theme? Which one?

No, observed on multiple themes

#### Does this happen on simple or atomic sites or both?

Both

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="1478" alt="Markup 2021-02-16 at 10 24 15" src="https://user-images.githubusercontent.com/51966986/108050176-2cb24d80-7041-11eb-850d-defda6f507eb.png">

**Comment by WunderBart** [comment] 2021-04-19 13:50
Duplicate of https://github.com/Automattic/wp-calypso/issues/45236

**Closed as completed by WunderBart** 2021-04-19 13:50 UTC
Labels: Bug, Blocks, [Feature] CoBlocks
