### ISSUE TITLE
Store: Disable the "let's go!" button on setup unless all fields are complete

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#18793] opened 2017-10-12 20:42 UTC
Noted in p90Yrv-es-p2. You can click the "let's go" before all required fields have been filled out.

**Comment by ryelle** [comment] 2017-10-30 16:20
This is a duplicate of #18816 -- closing this one (and reassigning) in favor of the other issue, which has more details.

**Closed by ryelle** 2017-10-30 16:20 UTC
Labels: Store, [Type] Bug
