### ISSUE TITLE
Column Block: Stretch to Fill option doesn't appear to work

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#88424] opened 2024-03-12 14:30 UTC
### Quick summary

I set the Stretch to Fill option on all 4 Column blocks within a Columns block and expected them to fill the height of the largest column so that the top and bottom of each column was even, but it did not work. I may be misunderstanding what this setting should do, but am reporting it in case it is not working as expected.

### Steps to reproduce

1. Open page in editor
2. Add Columns block with 4 columns
3. In each Column add one image, one paragraph, and one button, all centered
4. Select the Stretch to Fill option from the toolbar for each Column block
5. Save the page

### What you expected to happen

I expected all of the columns to arrange the content vertically so that they filled the column space of the largest column in the row with the tops of the images aligned and the bottom of the buttons aligned.

### What actually happened

Nothing changed about how the column content was displayed:
![Stretch to Fill](https://github.com/Automattic/wp-calypso/assets/32983813/8d742e27-bccf-44fb-835f-2388acc03888)
Link to test page: https://testforsharing.wordpress.com/test-stretch-to-fill/

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Customer Report:
7871142-zd-a8c

**Comment by rickmgithub** [comment] 2024-03-14 07:19
## 📌 REPRODUCTION RESULTS ##
- Tested on Atomic – Replicated 

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
* When the stretch to fill is applied to the column block it doesn't seem to have any effect at all. VIDEO: https://github.com/Automattic/wp-calypso/assets/13706336/fd2a941f-bb5d-4f1c-aa6c-d27692f6ada2
* Checked the support docs but could only find this reference on Buttons - https://wordpress.com/support/wordpress-editor/blocks/buttons-block/#buttons-block-toolbar

## 📌 ACTIONS ##
Triaged

**Comment by lupus2k** [comment] 2024-07-11 18:17
As part of pb5gDS-3YO-p2, we're aiming to fix/close high-priority issues in [The One Board](https://github.com/orgs/Automattic/projects/391/views/12) 
@andrewserong @tellthemachines can someone from Zenith team pick up this issue to fix it, or if prioritization isn't possible, then please close the issue with the label `Won't Fix` and a comment for the reason.

I asked you because you added this here: https://github.com/WordPress/gutenberg/pull/53325

**Comment by andrewserong** [comment] 2024-07-12 03:26
Thanks for the ping @lupus2k! I'll let you close out this issue if you like.

The stretch to fill option that landed in https://github.com/WordPress/gutenberg/pull/53325 is about the column size itself, not the contents of the column. Here's a quick video of how it works, it's a bit clearer with Column blocks that have a background color:

https://github.com/user-attachments/assets/eaff3251-2a87-47b0-ba77-9ac06565cecd

For any other issues, please open one over in https://github.com/WordPress/gutenberg/issues so they can be tracked there. Thanks!

**Comment by lupus2k** [comment] 2024-07-12 17:31
Thanks @andrewserong, I'll close the issue :tada:

**Closed as not planned by lupus2k** 2024-07-12 17:31 UTC
Labels: Bug, [Pri] High, Triaged, Customer report [LEGACY], [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks
