### ISSUE TITLE
Nav Unification: Consider omitting Mobile Options 

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#48241] opened 2020-12-10 23:41 UTC
#### What I expected

Given that all new themes are responsive. I don't think there is a need to have a Mobile menu under `Appearance`. We should consider removing it from the new navigation.

#### What happened instead
1. We still have the navigation under `Appearance > Mobile`
2. On Calypso, the link takes to `/mobile-options`, relative to the page you're visiting.

#### Browser / OS version

Chrome 87 / Mac Catalina 10.15.7

#### Context / Source

#manual-testing

**Comment by cpapazoglou** [comment] 2021-01-05 15:39
👋 there! Can you give a little bit more context here? I don't have "Mobile" submenu in "Appearance" either in simple or atomic sites. In which plan are you testing? Is that maybe a setting you have selected?

**Comment by obenland** [comment] 2021-01-05 19:50
Hi @eduardozulian, thanks for the report. I wonder if this was fixed in r218221-wpcom? I can't reproduce it anymore.

**Comment by eduardozulian** [comment] 2021-01-11 22:12
@cpapazoglou @obenland not seeing that any longer. Looks like it's all good!

**Closed as completed** 2021-01-11 22:16 UTC
Labels: Task
