### ISSUE TITLE
Auto-play feature for slideshow for simple sites not working 

### ISSUE THREAD

**Issue by Mfarroq1** [Automattic/wp-calypso#89654] opened 2024-04-18 13:54 UTC
### Quick summary

Auto-play feature for slideshow block is not working for simple sites when previewing a page.  it's working fine in the editor.  Also, auto-play feature is working on atomic sites. 

### Steps to reproduce

1. make sure you are on simple sites (starter or explorer plan subscription).
2. open a page 
3. add slide show block 
4. enable auto-play feature 
5. View a page after closing the editor.  (preview a page)

### What you expected to happen

When previewing a page, slideshow should change slides automatically 

### What actually happened

Slides are not changing automatically we have to change the slide manually using navigation arrow.  

### Impact

All

### Available workarounds?

No and the platform is unusable

### Logs or notes

related tickets 

zen-[8057525]
zen-[8054016]

**Comment by Mfarroq1** [comment] 2024-04-18 17:39
another user report here (simple site)
zen-8058429

**Comment by Aurorum** [comment] 2024-04-18 19:59
Duplicate of Automattic/jetpack#36973

**Closed as not planned** 2024-04-19 12:21 UTC
Labels: Bug, [Pri] Low, Needs triage, [Status] Priority Review Triggered

**Comment by zemirajput** [comment] 2024-05-13 13:00
zen-8182707 Atomic site.

**Comment by coder-karen** [comment] 2024-05-17 13:24
For anyone still following this thread instead of https://github.com/Automattic/jetpack/issues/36973, a fix has been deployed and now resolves the issue on Simple sites. Atomic and self hosted were also affected, but likely not when the reports first started coming in as the relevant release hadn't yet made it to those platforms. I'll update the linked issue when Atomic sites have the fix, and Jetpack sites will be in the next Jetpack release.
