### ISSUE TITLE
Gutenberg: Inserting a Photo Library image does not work

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35476] opened 2019-08-16 15:58 UTC
When changing an image in the page (not the header image! that seems to work) to use an image from the “Free Photo Library”, after clicking “Insert”, nothing happens (although the photo does get added to the media library and will work if selected from there).

https://videopress.com/v/jXw3ipkj

**Comment by arunsathiya** [comment] 2019-08-18 06:17
A quick note that I saw this happen on `Media & Text` block as well.

**Comment by Copons** [comment] 2019-08-19 17:56
This is not limited to FSE, it happens regardless.

As it turns out, not all blocks with images are broken, but only those that use the "pencil" icon to change the image, while those using the "swap" icon work fine.

The `Image` block use the "swap" icon and I was able to add and change images from Pexels.
![Screenshot 2019-08-19 at 18 42 31](https://user-images.githubusercontent.com/2070010/63287119-75a10e80-c2b1-11e9-8d99-941a85688530.png)

`Cover` and `Media & Text`, as pointed out by @arunsathiya, instead use the "pencil" icon and don't work.
![Screenshot 2019-08-19 at 18 41 42](https://user-images.githubusercontent.com/2070010/63287120-75a10e80-c2b1-11e9-9066-1478caa0eec4.png)
![Screenshot 2019-08-19 at 18 41 04](https://user-images.githubusercontent.com/2070010/63287121-7639a500-c2b1-11e9-875f-e704f1fd9680.png)

The "swap" icon is new-ish, as I don't remember it from before my leave, so I suppose that, when it was introduced, we noticed it on the `Image` block (which is more common), and updated the integration accordingly, assuming that all media blocks replaced "pencil" with "swap".

_Note: I say icon to be more clear, but the underlying implementation is different too: "pencil" opens the Media Library directly, while "swap" shows the media placeholder, where then we could click on the Media Library to open it._

I think the mess up is somewhere between here:

https://github.com/Automattic/wp-calypso/blob/6b004d1834919054c892f6309fb9237f52e66150/apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js#L698-L738

and here:

https://github.com/Automattic/wp-calypso/blob/6b004d1834919054c892f6309fb9237f52e66150/client/gutenberg/editor/calypsoify-iframe.tsx#L183-L202

**Comment by noahtallen** [comment] 2019-08-20 01:10
Possibly related: https://github.com/Automattic/wp-calypso/issues/31230. I wasn't able to come up with a solution during hack week

**Comment by apeatling** [comment] 2019-08-20 04:05
I'm removing this as a blocker for the 10% launch, but we should look at this in the next sprint.

**Comment by noahtallen** [comment] 2019-09-28 00:58
Confirming that this is still an issue on Gutenberg master with our latest FSE changes synced.

**Comment by noahtallen** [comment] 2019-10-11 19:47
I'm going to move this to the gutenberg integration backlog since it is not an FSE issue.

**Comment by gwwar** [comment] 2019-10-23 17:48
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/32420

**Closed by gwwar** 2019-10-23 17:48 UTC
Labels: Core fix needed, [Pri] Normal, [Type] Bug
