### ISSUE TITLE
Classic blocks: Unable to select multiple paragraphs at once

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#81147] opened 2023-08-28 19:59 UTC
### Quick summary

Initial report: 6736959-zd-a8c

With older Classic blocks – those that _do not_ use the newer pop-up editing modal – selecting multiple paragraphs of text isn't possible, which makes it impossible to copy or style multiple paragraphs at once.

### Steps to reproduce

I'm unsure if it's still possible to insert an older Classic block that _doesn't_ use the pop-up editing modal anymore. Copy/pasting data from an existing Classic block automatically switches to regular blocks or the newer Classic block editing style in my tests. 

1. ~Start with a site that has an older Classic block on a post or page.~ _On a site with a Classic Theme active, add a classic block and compose multiple paragraphs._
2. ~Open the block editor for that post/page.~
3. Try to select multiple paragraphs within the Classic block using a mouse. (Selecting text with keyboards seems unaffected.)

_2023-08-29 updated steps to replicate - cuemarie_

### What you expected to happen

Should be able to select multiple paragraphs at once.

### What actually happened

Unable to select multiple paragraphs. The selection immediately disappears/deselects.

https://github.com/Automattic/wp-calypso/assets/5630717/16f2bd23-aa56-4450-994f-579f4b94a374

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Only tested on Simple so far, as I haven't been able to replicate this myself.

Workarounds: 
* Editing from the "code editor" or classic editor.
* Convert to regular blocks.

**Comment by cuemarie** [comment] 2023-08-30 00:55
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated** 
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated in all test environments.  
- The Classic Block uses the older in-editor block (not the pop-up modal) when the site has a Classic theme active.  

https://github.com/Automattic/wp-calypso/assets/27249804/3405b9de-c823-4fae-8acc-a5986929ff6d

There's an existing Core report about this issue here: https://github.com/WordPress/gutenberg/issues/41432

📌 ACTIONS
- Triage complete

**Comment by annezazu** [comment] 2024-08-29 22:52
Noting that I dug into the Gutenberg report and can no longer replicate. As a result, I'm going to close this out since I closed out the original report: https://github.com/WordPress/gutenberg/issues/41432#issuecomment-2319219406

If that gets reopened, we can reopen this.

**Closed as completed by annezazu** 2024-08-29 22:52 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] Low, [Status] Core Fix Needed, Triaged, Customer report [LEGACY], [Platform] Simple, [Product] WordPress.com, [Feature Group] Editor Experience
