### ISSUE TITLE
[Bug]: Cannot add a credit card for Hong Kong outside of checkout

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#57322] opened 2021-10-25 14:35 UTC
### Quick summary

If you try to add a credit card and choose "Hong Kong SAR China" as the country, you get a "Credit Card data is missing name, country, or postal code" error message when you submit and cannot add the card.

This applies to anywhere you can add a card outside of checkout (adding it during checkout still works).

I have not checked if this applies to any country without a postal code field, or only Hong Kong.

### Steps to reproduce

1. Go to add a card outside of checkout (for example https://wordpress.com/me/purchases/add-payment-method).
2. Fill it in with test data (you can use https://stripe.com/docs/testing to get test credit cards, which actually should work if you're in store sandbox mode).
3. Submit the form.

### What you expected to happen

Either a successful submission, or an error message about an invalid credit card (if it's actually invalid) or whatever else.

### What actually happened

You get a "Credit Card data is missing name, country, or postal code" error message.

### Context

Internal reference: p1635169497034700-slack-C02BEP610

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

You can add a credit card during checkout and the problem doesn't occur, but that requires paying immediately which the user might not want to do.

**Comment by nbloomf** [comment] 2021-12-13 20:07
While looking into this I found what appears to be an unrelated bug in how we get the tax location info from a stripe payment method: D71451-code

**Comment by nbloomf** [comment] 2021-12-13 20:09
I think this issue is fixed by https://github.com/Automattic/wp-calypso/pull/57041. Edit- never mind, I see that is about checkout.

**Comment by nbloomf** [comment] 2021-12-13 20:27
For real this time, I think this was fixed by D68482-code. At any rate I'm not able to reproduce the issue.

**Closed as completed** 2021-12-29 22:24 UTC
Labels: Bug, [Feature] Purchase Management, Payment Methods
