### ISSUE TITLE
Ecommerce Plan: Stuck on store creation wizard

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#32886] opened 2019-05-08 02:50 UTC
#### Steps to reproduce
1. Starting at URL: `https://DOMAIN/wp-admin/admin.php?page=wc-settings`
2. Click on Help, then Setup Wizard
3. Click on the "Setup Wizard" button
4. Presented with the "Let's start setting up." page (`wp-admin/admin.php?page=wc-setup`)
5 Click on "Continue"

**Note: This also happens if you land on the `wc-setup` wizard as part of the signup flow and click "Continue" on the "Select payment methods." step. It is possible that "Continue" is broken on other steps as well.**

#### What I expected
To be taken to the next step on the signup flow

#### What happened instead
Nothing happens. I am stuck and clicking on "Continue" does nothing.

#### Browser / OS version
Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)

#### Screenshot / Video

https://cld.wthms.co/7PdGx3

#### Context / Source
#manual-testing

**Comment by sararosso** [comment] 2019-05-08 14:58
Confirmed I also replicated this bug.

**Comment by zdenys** [comment] 2019-05-21 17:06
Encountered the same error myself.

**Comment by samjhamdy** [comment] 2019-05-21 18:44
Also encountered this issue in #2048107-zen

**Comment by mattsherman** [comment] 2019-06-03 19:10
I had this happen when clicking "Continue" on the "Select payment methods" page.

**Comment by jordesign** [comment] 2019-06-05 03:51
I also encountered this in eCommerce training while in Chrome.

**Comment by mattsherman** [comment] 2019-06-06 18:49
@jonathansadowski @creativecoder I am able to reproduce this 100% of the time. Are you both also able to consistently reproduce it? (No errors in the browser console... the Continue button just does nothing.)

What other information do we need before we can begin diving into this?

**Comment by mattsherman** [comment] 2019-06-10 15:42
@davipontesblog I am unable to follow steps 1-3 in your original issue:

> Steps to reproduce

> 1. Starting at URL: https://DOMAIN/wp-admin/admin.php?page=wc-settings
> 2. Click on Help, then Setup Wizard
> 3. Click on the "Setup Wizard" button

I don't see any "Help" on "wc-settings". Can you please provide more detail so that I can reproduce these steps?

**Comment by davipontesblog** [comment] 2019-06-10 15:56
> @davipontesblog I am unable to follow steps 1-3 in your original issue:
> 
> > Steps to reproduce
> 
> > 1. Starting at URL: https://DOMAIN/wp-admin/admin.php?page=wc-settings
> > 2. Click on Help, then Setup Wizard
> > 3. Click on the "Setup Wizard" button
> 
> I don't see any "Help" on "wc-settings". Can you please provide more detail so that I can reproduce these steps?

@mattsherman try from WooCommerce > Settings, in WP Admin:

![](https://cld.wthms.co/WpBzws+)

**Comment by mattsherman** [comment] 2019-06-10 16:51
@davipontesblog Thanks. Looks like perhaps I was getting a different view because of Calypsoify. I was able to reproduce those steps when starting at `wp-admin` and manually navigating in the sidebar.

**Comment by mattsherman** [comment] 2019-06-10 20:06
@Automattic/isotope From my limited understanding of WooCommerce and WordPress.com integration, this issue seem like it might actually lie in [wc-calypso-bridge](https://github.com/Automattic/wc-calypso-bridge)? Would it be possible for somebody on the team, who is sure to be much more knowledgeable of this area of the product than us, to take a quick look at this and point us to where things would need to be fixed up (or, feel free to actually just fix it if it is obvious/trivial... we won't complain 😄).

 (/cc @joshuatf @timmyc)

**Comment by joshuatf** [comment] 2019-06-11 08:08
Thanks for noting this issue.  I think this is caused by one of the scripts not loading during the onboarding wizard.

I've outlined this issue [here](https://github.com/Automattic/wc-calypso-bridge/issues/445) and will try to have a fix out shortly.  /cc @justinshreve

**Comment by mattsherman** [comment] 2019-06-11 11:50
Thanks @joshuatf!

**Comment by mattsherman** [comment] 2019-06-18 19:38
Verified that this issue is now resolved via https://github.com/Automattic/wc-calypso-bridge/pull/446

**Closed by mattsherman** 2019-06-18 19:38 UTC
Labels: Plans, Signup, [Pri] BLOCKER, [Type] Bug, eCommerce Plan
