### ISSUE TITLE
Gallery Block: Image src URL replace with embed URL

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#62461] opened 2022-04-01 13:09 UTC
### Quick summary

We have two reported cases in which images previously added to a Gallery Block disappear from Simple sites.

### Steps to reproduce

Many attempts to reproduce this on simple sites have been made, yet I have not been able to until now.

Yet, since this is something that affects two different websites, there is definitely something causing this that should be looked into.

Both cases were on long posts, with many galleries and images of content-rich sites.

### What you expected to happen

I expected the Galleries to display the images.

### What actually happened

The Galleries display `This image has an empty alt attribute; its file name is playlist` or  `This image has an empty alt attribute; its file name is 4k5fbQ1`, for example.

### Context

One case was from a user with a Simple Business plan site, the other from a user on a Free plan.

What is seen instead on the published post is this:
![Live site](https://user-images.githubusercontent.com/2540430/161265647-2e74b066-6bb5-41c5-823c-be2547d5054f.png)

And the Editor shows this:
![Editor](https://user-images.githubusercontent.com/2540430/161265730-97776054-2ab7-4d9c-9cdb-27332c7496f0.png)

When we investigate further, the code shows that the src of the gallery images has been replaced with the URL that was added to an embed on the page.
In one case, the URL was on a Youtube playlist.
In another case, the URL was pointing to an Instagram post.

When we attempt to recover from a previous version, the issues persist.
When we check previous versions, this is what we see:
![Screenshot_2022-03-14_at_10_19_48](https://user-images.githubusercontent.com/2540430/161267927-d2481a35-1b46-4f32-aad9-911e0079c078.png)

Tickets:
4889705-zd-woothemes
4821363-zd-woothemes

Investigation P2 post:
p2EDhh-1wb-p2

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No.

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

The affected galleries can be rebuilt by accessing the revisions and retrieving the correct URLs for the missing images.
Yet, given the number of posts affected in one of the cases, this is highly time-consuming.

**Comment by formosattic** [comment] 2022-04-03 08:45
Not sure if we'll be able to replicate this as it seems caused by a core update.

Looking at the revision screenshot above, based on the the unordered list HTML removed, it looks like this is related to Gallery block refactor that was included in [WordPress 5.9](https://wordpress.org/news/2022/01/josephine/), more details:

* https://make.wordpress.org/core/2021/08/20/gallery-block-refactor-dev-note
* https://www.koberoku.com/content/why-wordpress-5-9-broke-your-galleries-and-how-to-fix-it 

A timeline of the core merges to Simple sites:
* 5.9.0 - 2022/01/26, p94tqY-qK-p2
* 5.9.1 - 2022/02/23, p94tqY-rh-p2
* 5.9.2 - 2022/03/11, p94tqY-rp-p2
* 5.9.3 - 2022/03/30, p94tqY-rR-p2

**Comment by pauljacobson** [comment] 2022-04-04 10:22
Hi @formosattic 👋

Thank you for the feedback. Based on the second post you linked to, it seems that one possible workaround is to make a minor change to an affected post (perhaps adding a space), and clicking _Update_. Have I understood that correctly?

**Comment by formosattic** [comment] 2022-04-04 11:57
@pauljacobson : I shared the second link https://www.koberoku.com/content/why-wordpress-5-9-broke-your-galleries-and-how-to-fix-it , for the reference of the unordered list that is now gone. 
I'm not sure that the fix suggested there would apply for WordPress.com, especially because the bug has the other odd behavior of replacing the image  URL with the link of an embed content on the same page. But I'm not familiar enough with the code to know. I guess, it's worth trying though I'm wary it may break other things.

Internal convo: p1649134545554789/1649047692.645469-slack-C7YPUHBB2

**Comment by filipanoscampos** [comment] 2022-04-05 10:46
@pauljacobson and @formosattic 
Yes, in one of the cases the user made many changes to a post and the issue persisted.
So this workaround will not solve the issue at hand.

**Comment by formosattic** [comment] 2022-04-09 01:30
Shared from internal convo with @Greatdane (p1649387812620979/1649032944.419269-slack-C01UW7SB411), here's a similar report, issue happened after changing theme: p2EDhh-1qk-p2

**Comment by inaikem** [comment] 2022-04-19 07:29
@glendaviesnz 👋  This appears to be an edge case and I'm not 100% sure how we should proceed. Based on the work you did on the core Gallery block refactor, is there anything you can suggest as a next step?

**Comment by glendaviesnz** [comment] 2022-04-19 21:07
> @glendaviesnz 👋 This appears to be an edge case and I'm not 100% sure how we should proceed. Based on the work you did on the core Gallery block refactor, is there anything you can suggest as a next step?

@inaikem do you know if there are any old versions of the post that include the images - I think somewhere it mentioned there were previous versions that could be restored, but when restored the same thing happened? If you were able to get me the raw content of an old post revision with the images included I would have a better chance of trying to work out what has gone wrong.

**Comment by inaikem** [comment] 2022-04-20 13:36
@Automattic/dotcom-triage-pa-group, I'm EOD at the moment, is someone around to help answer Glen's question?

**Comment by filipanoscampos** [comment] 2022-04-20 13:46
@glendaviesnz 

What was happening was that, when we attempted to restore to the previous version, the Galleries would still be broken.

We can write to the user and ask them if they can share a post with us we can experiment with.
Do you think that could work?

**Comment by glendaviesnz** [comment] 2022-04-20 20:47
> What was happening was that, when we attempted to restore to the previous version, the Galleries would still be broken.

If you are restoring and opening straight away in the editor then the editor might be rewriting the block content. We would need to try and get the raw post content of the old version of the post without loading it in the editor - not sure what the easiest way to do that is.

> We can write to the user and ask them if they can share a post with us we can experiment with. Do you think that could work?

If you can find a post where we have access to a previous revision that has the image links, and get their permission to have a closer a look at it I will see if I can find if we can get a copy of the raw revision post content somehow.

**Comment by daria2303** [comment] 2022-07-14 08:59
@glendaviesnz user is asking for an update, what are we planning for this issue? :)

**Comment by glendaviesnz** [comment] 2022-07-15 02:12
@daria2303 as [noted here](https://github.com/Automattic/wp-calypso/issues/62461#issuecomment-1104442180), we would need access to a copy of the post with the image links included in order to try and work out why this happened. Because it is a strange edge case that we can't replicate we can't do anything else without that, unfortunately.

There is a slim possibility that it was related to this other bug https://github.com/WordPress/gutenberg/issues/41161, which was fixed here https://github.com/WordPress/gutenberg/pull/41221, and released in 6.0.1 and Gutenberg 13.4, so if you are able to access copies of the post prior to the problem you could try loading them in the editor again and see if the images stay in place now.

**Comment by mriyazuddin** [comment] 2022-08-02 10:22
User had provided the list of posts in #4821363-zd. I just looked at all those posts and could see that the Galleries are appearing fine now. There are no more errors and the images appear fine. I've let the user know and asked them to check and reconfirm. Guess it was indeed related to [WordPress/gutenberg#41161](https://github.com/WordPress/gutenberg/issues/41161). If user confirms its fixed, we can close this issue.

**Comment by cometgrrl** [comment] 2023-01-10 00:43
Closing since it's been > 4 months with no recorded response from the user.

**Closed as completed by cometgrrl** 2023-01-10 00:43 UTC
Labels: Bug, [Pri] Normal, [Status] Core Fix Needed, [Block] Gallery, Images
