### ISSUE TITLE
Page Layouts: Social Icons Block looks wrong in some previews — buttons are too wide and vertical

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#56688] opened 2021-09-30 06:54 UTC
### Quick summary

The Social Icons Block in some Page Layout previews look wrong (too wide):

![image](https://user-images.githubusercontent.com/39308239/135401295-05418311-0e59-4ba4-8d0c-71befdb571b7.png)

Compared to how they look in the Editor once added:

![image](https://user-images.githubusercontent.com/39308239/135401332-443ec731-6d3d-4b0b-aa8a-b2fe30f6ec98.png)

### Steps to reproduce

1. Create a new page in My Site → Pages → Add New
2. Click About section on the left
3. Hover over any of these:
 - Two column about me layout
 - About layout with photo and testimonial
 - About layout with portrait and social links
 - Resume with contact and social links
4. Observe how the Social Icons Block looks like. The buttons are very wide and vertical
5. Click on any of the above layouts to add them to the page
6. Observe how the Social Icons Block looks in the Editor

### What you expected to happen

The Social Icons Block should look the same both in Page Layout preview and in the Editor

### What actually happened

The Social Icons Block in some Page Layout previews look wrong: buttons are wide and vertical

### Context

Observed during a Quick Start session 4337840-zd-woothemes

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Other notes

I found that issues about Page Layouts were previously reported in a different repo, such as 272-gh-Automattic/view-design

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Robertght** [comment] 2021-09-30 07:00
Thank you for reporting this @zdenys !

I know @arcangelini had this already in sight as we could see it the other day in the Customizer, but now I can see it in the editor too.

cc @Automattic/flow-patrol-create

**Comment by davoraltman** [comment] 2021-09-30 11:23
There's also another a different use case for the same issue:

1. Activate Twenty Eleven theme
2. Add the social icons block to a post, at the top (so that they are visible in the excerpt, in the blog posts overview)
3. Make sure that the Infinite Scroll is turned off
4. Scroll down on the Blog posts page and click on Older Posts so that the post where the social icons block is, gets displayed
5. Result:

<img width="754" alt="Screen Shot 2021-09-30 at 1 19 10 PM" src="https://user-images.githubusercontent.com/10340370/135445987-91a02d91-5d80-4ad5-8768-5eedd77415e7.png">

The block will be displayed properly when you navigate on the post itself.

This is on Twenty Eleven. On Twenty Twenty-One, the social icons block isn't displayed at all. On Dalston, it's displayed properly.

I had a case in 31944895-hc (Twenty Eleven theme)and custom CSS did the trick. But it looks like there's a wider issue as the block is inconsistent.

**Comment by desnum** [comment] 2021-11-22 19:47
Another case, where the icons are squished in the other direction:

<img width="1004" alt="Screen Shot 2021-11-22 at 2 46 43 PM" src="https://user-images.githubusercontent.com/43796228/142925326-111fc71f-f7fc-4ea3-a8b2-e89615a2e023.png">

It's a free site, on the Argent theme. I added Custom Design and used some CSS as a temporary workaround:

```
/*fix social button sizing 31330325-hc DF*/
#widget-area-3 .widget ul > li, .widget ol > li {
	text-align: center;
	padding-top: 7px;
}

.wp-social-link {
	width: 40px;
	height: 40px;
}
```

**Comment by arcangelini** [comment] 2021-12-01 17:53
This should be resolved with the following PR - WordPress/gutenberg/pull/37010

I will check back on this when this is merged into WordPress.com and make sure it s working.

**Comment by zdenys** [comment] 2021-12-24 09:27
Another case where a Social Icons Block added as a widget on a Simple Site with WordPress.com Personal Plan has all but the first icon with unnecessary top padding:

![image](https://user-images.githubusercontent.com/39308239/147339854-e0ed68c4-09d5-4335-9137-3ceaa5285ec3.png)

Although in the backend icons look fine. But there is also no way to change the padding in the block settings and CSS is not an option on the Personal plan.

![image](https://user-images.githubusercontent.com/39308239/147339976-0a47ffad-e693-4105-9380-6cb80824b34b.png)

**Comment by arcangelini** [comment] 2022-01-15 10:47
From my testing, it looks like the styling is not being loaded until after the widget is saved and the customizer is reloaded. The PR has been merged into core and is live on WPCOM. It looks like we may need to take a closer look at this. Apex is now looking after the widgets so I will let @yansern and @ivan-ottinger weigh in on this.

**Comment by ivan-ottinger** [comment] 2022-01-17 10:19
We have added this issue to our project board and will investigate further.

**Comment by stefancln** [comment] 2022-02-09 09:09
Another report on 4753843-HC

The first icon from the Social Icons Block added to the footer is unnecessarily padded up, at a different level than the other icons

**Comment by zdenys** [comment] 2022-02-18 15:26
This is affecting many other themes:

- https://github.com/Automattic/themes/issues/4519
- https://github.com/Automattic/themes/issues/2806
- https://github.com/Automattic/themes/issues/5565

**Comment by mashikag** [comment] 2022-10-12 13:23
Seems like many different issues related to `Social Icons` block are raised here. First we need to check whether they are still reproducible and then split it out into multiple specific issues if possible.

**Comment by cuemarie** [comment] 2023-07-27 20:04
Retested today - the current set of Page Layout previews do not show this issue. Ex:

![Markup on 2023-07-27 at 13:02:13](https://github.com/Automattic/wp-calypso/assets/27249804/3e3493d6-e8ae-49de-8123-397c676804c2)

I'll test some of the other behaviors from the comments and open new issues if the problem still presents.

📌 ACTIONS
- Closing as no longer relevant / not reproducible

**Closed as not planned by cuemarie** 2023-07-27 20:04 UTC
Labels: Bug, [Pri] High, Page Layouts

**Comment by cuemarie** [comment] 2023-07-27 20:22
Regarding Social Icons block in widgets, there are issues for both the elongation in the Customizer, and the inappropriate height on the live site. Both correspond to reports in Gutenberg:

- https://github.com/Automattic/wp-calypso/issues/79942
- https://github.com/Automattic/themes/issues/5345

Please report any customer interactions on the `wp-calypso` / `themes` issues. Thanks!
