### ISSUE TITLE
Sidebar: "Add a tag" button has white background which seems awkward

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#49206] opened 2021-01-22 18:13 UTC
The "Add a tag" item in the sidebar fly-out seems like it might have the wrong background color.

<img width="441" alt="Screen Shot 2021-01-22 at 1 07 45 PM" src="https://user-images.githubusercontent.com/2036909/105528701-4ca95800-5cb3-11eb-957d-325801fad5a5.png">

Note, for example, the background of the "Create new list" button, which matches the theme better:

<img width="434" alt="Screen Shot 2021-01-22 at 1 12 14 PM" src="https://user-images.githubusercontent.com/2036909/105528938-9c881f00-5cb3-11eb-86fb-cf154aedc452.png">

**Comment by cpapazoglou** [comment] 2021-02-10 14:20
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/49149

**Closed as completed by cpapazoglou** 2021-02-10 14:20 UTC
Labels: Bug, [Pri] Low, [Feature] Calypso & wp-admin Navigation
