### ISSUE TITLE
Sites: unresponsive link until screenshot loads

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#88848] opened 2024-03-25 11:15 UTC
All sites links are unresponsive while screenshots are loading.

https://github.com/Automattic/wp-calypso/assets/87168/ff74ad16-a015-4774-b8cb-3ab54a141f91

#### Steps to reproduce

Use slow connection; sandboxed with lots of sites is usually slow enough.

1. Starting at URL: /sites
2. Screenshots keep loading / pulsating
3. Try click the site name before screenshot; nothing happens until screenshot(s) finish loading
4. Go back and try "settings" link under three dots; it works right away

**Comment by sejas** [comment] 2024-03-25 17:11
@simison, I took a quick look and found that the slow loading is related to the `/home/$siteSlug` page and not the way we navigate from `/sites`.

Here are the steps to reproduce:
1. Sandbox the API to add some delay in the responses.
2. Navigate to `/settings/general/$siteSlug`
3. Quickly click on `Home` in the left sidebar to navigate to the home dashboard.
4. Observe the URL changes quickly in the browser, but it takes several seconds to load the Home page.


https://github.com/Automattic/wp-calypso/assets/779993/b25bea27-15d5-4c24-8c82-9fee2f46f981

Before realising the problem is in the Home, I tried using `navigate` function and also navigating to Home from the ellipsis menu with same results.

**Comment by maciejpilarski** [comment] 2024-03-25 19:45
📌 ACTIONS
– triaged

**Comment by lsl** [comment] 2024-08-26 04:31
The fullscreen launchpad redirect check seems to block a few things,

https://github.com/Automattic/wp-calypso/blob/955b956b70257df047c88f4343065cf3011641d5/client/my-sites/customer-home/controller.jsx#L63-L80

![Screenshot(7)](https://github.com/user-attachments/assets/af963f08-42cc-47e9-8d5f-c4d8d34a4e2e)

Commenting it out things look a bit better:

![Screenshot(8)](https://github.com/user-attachments/assets/cf60fbeb-c2fe-443c-8281-8871ae618c56)

We could probably add a skip launchpad param to the sites already launched but I'm hesitant to do so when removal of this should be happening near-term, pfuQfP-J5-p2 fyi @bogiii

**Comment by sejas** [comment] 2024-10-23 09:10
Closing this issue because we don't display site screenshots anymore.

![Image](https://github.com/user-attachments/assets/96cea845-5f39-4c48-aa1b-b8fb9ba86623)

**Closed as completed by sejas** 2024-10-23 09:10 UTC
Labels: Bug, Sites, Triaged, [Feature] Launchpad, Sites Management Page, [Pri] TBD
