### ISSUE TITLE
Sites Management Page: "Can't perform a React state update" error for Site Thumbnails

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/wp-calypso#73163] opened 2023-02-09 15:34 UTC
If you quickly start a search after the Sites page is loaded, you can see this error in the console:

![image](https://user-images.githubusercontent.com/36432/217858278-56c8099d-d726-428f-b297-08e39ef3a9a6.png)

I think the problem is that this async fetch isn't completed yet and needs to be cleaned up:

https://github.com/Automattic/wp-calypso/blob/4bde28dc50cd16ab95e5b9830f35b26bac754636/packages/components/src/site-thumbnail/use-mshots-img.tsx#L80-L92

https://github.com/Automattic/wp-calypso/blob/4bde28dc50cd16ab95e5b9830f35b26bac754636/packages/components/src/site-thumbnail/fetch-await-redirect.ts#L1-L7

**Done is:**
* It's no longer possible to reproduce the error.

**Comment by kozer** [comment] 2023-06-29 10:38
It seems it has been fixed in [SMP: Update tests for <SiteThumbnail> #67362](https://github.com/Automattic/wp-calypso/pull/67362). I can't any longer replicate it. I'm closing this issue

**Comment by danielbachhuber** [comment] 2023-06-29 11:39
@kozer This issue was created months after https://github.com/Automattic/wp-calypso/pull/67362 was merged.

If you can't replicate it, you'll need to spend more time figuring out how to do so.

**Comment by kozer** [comment] 2023-06-29 11:48
@danielbachhuber , you are right about the dates. Comparing the functions you provided, and those in the pr (which is the current code that exists), and as I couldn't replicate it, no matter how fast I searched, I concluded that was fixed.

I'll dig more into this.

**Comment by kozer** [comment] 2023-06-29 12:12
Also, next time, please, if something it's not easy to reproduce, include that in the ticket to have a sense of how much effort I should put into that because following the instructions you provided, doesn't make this bug easily reproducible.
Thank you.

**Comment by kozer** [comment] 2023-06-29 12:46
### Investigation
The above error is produced if something is setting the state after a component is unmounted.
I tried to replicate the error by doing some code modifications, to make this bug more easily reproducable. You can redo those changes by applying the following patch:

```
diff --git a/packages/components/src/site-thumbnail/index.tsx b/packages/components/src/site-thumbnail/index.tsx
index 590fb0c046..52ccb4078b 100644
--- a/packages/components/src/site-thumbnail/index.tsx
+++ b/packages/components/src/site-thumbnail/index.tsx
@@ -49,7 +49,7 @@ export const SiteThumbnail = ( {
 		h: height,
 		...mshotsOption,
 	};
-	const { imgProps, isLoading, isError } = useMshotsImg( mShotsUrl, options, [
+	const { imgProps, isLoading, isError } = useMshotsImg( 'test.com', options, [
 		...dimensionsSrcset,
 		{ width, height },
 	] );
diff --git a/packages/components/src/site-thumbnail/use-mshots-img.tsx b/packages/components/src/site-thumbnail/use-mshots-img.tsx
index d48a55834c..51afc035f5 100644
--- a/packages/components/src/site-thumbnail/use-mshots-img.tsx
+++ b/packages/components/src/site-thumbnail/use-mshots-img.tsx
@@ -78,17 +78,14 @@ export const useMshotsImg = (
 		}
 
 		async function checkRedirectImage() {
-			const { isError, isRedirect } = await fetchAwaitRedirect( mshotUrl );
-			if ( isError ) {
-				setIsLoading( false );
-				setIsError( true );
-			}
-			// 307 is the status code for a temporary redirect used by mshots.
-			// If we `follow` the redirect, the `response.url` will be 'https://s0.wp.com/mshots/v1/default'
-			// and the `response.headers.get('content-type)` will be 'image/gif'
-			if ( ! isRedirect ) {
-				setIsLoading( false );
-			}
+			await new Promise( ( res, rej ) => {
+				setTimeout( () => {
+					setIsLoading( false );
+			     	setIsError( true );
+			        console.log( mshotUrl );
+					res();
+				}, 1000 );
+			} );
 		}
 
 		if ( isLoading && retryCount < MAXTRIES ) {
@@ -101,6 +98,7 @@ export const useMshotsImg = (
 
 		return () => {
 			if ( timeout.current ) {
+			    console.log( 'clear timeout' );
 				clearTimeout( timeout.current );
 			}
 		};
```

This patch tries to make the `clearTimeout` to happen **before** the `setState`. 

To do that, you need to:
1. Copy a text (eg: `testtesttesttesttesttesttesttest` ). (You need to make sure that the text doesn't let any site visible under your sites list after search )
2. Load Sites page ( by visiting `/sites` )
3. Quickly paste the text you copied.
4. Do that a few times, till you see in the console the message "clear timeout",  appearing **before** the fake URL.

Unfortunately, after this test, I still couldn't replicate the issue.

My best guess is that applying the following diff, would solve the issue, as it prevents the state to be updated after the cleanup function is called:

```
diff --git a/packages/components/src/site-thumbnail/use-mshots-img.tsx b/packages/components/src/site-thumbnail/use-mshots-img.tsx
index d48a55834c..df3c2da61a 100644
--- a/packages/components/src/site-thumbnail/use-mshots-img.tsx
+++ b/packages/components/src/site-thumbnail/use-mshots-img.tsx
@@ -79,6 +79,9 @@ export const useMshotsImg = (
 
 		async function checkRedirectImage() {
 			const { isError, isRedirect } = await fetchAwaitRedirect( mshotUrl );
+			if ( ! timeout.current ) {
+				return;
+			}
 			if ( isError ) {
 				setIsLoading( false );
 				setIsError( true );
```

however, I'm not 100% sure, so I leave it here for anyone that finds a way to replicate it.

Finally, for anyone interested, a common pattern that is often used in that situation is something like the following:

```
useEffect(() => {
  let isMounted = true;               // note mutable flag
  someAsyncOperation().then(data => {
    if (isMounted) setState(data);    // add conditional check
  })
  return () => { isMounted = false }; // cleanup toggles value, if unmounted
}, []);                               // adjust dependencies to your needs
```

By having the `timeout.current` to be cleared in the cleanup function, I think it can used instead as stated.

**Comment by danielbachhuber** [comment] 2023-06-29 21:42
@kozer Want to submit your proposed fix as a PR, and then I can see if it fixes the issue?

**Comment by kozer** [comment] 2023-06-30 07:25
@danielbachhuber sure thing! I created a pr [here](https://github.com/Automattic/wp-calypso/pull/78828)

**Closed as completed** 2023-07-05 11:04 UTC
Labels: Bug, Sites, [Pri] Normal
