### ISSUE TITLE
Update Design Picker to surface themes based on goal choice

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#95693] opened 2024-10-24 21:08 UTC
From the Onboarding post:

> First path is to select a predesigned theme. Users who choose this approach will land in a redesigned and personalized themes showcase, with the most relevant set of themes for that user’s goals pre-selected and shown at the top. In order to figure out which themes are most relevant for a user’s goals, Matt Miller and team have begun parsing and analyzing 100,000 successfully launched websites, to identify which themes were empirically used for which apparent user goals. While we may have good guesses about which themes will best help users achieve their goals, our users know even better, and we want to rely on their actual behavioral data. Meanwhile, we will also update the presentation of the overall themes showcase. Free themes will be more clearly separated from premium themes, with immediate upsell requests removed. The theme showcase is perhaps our greatest opportunity to help users start off well on WordPress.com, and we want to give users a beautiful, coherent, frictionless, and personalized experience.

### What's the current status?

* Can only filter by one category at a time.
* Global styles don’t require an immediate purchase.
* Paid themes yes. Users can't proceed without upgrading the plan.
* Sorting and curation: There is manual curation that was initially managed by dot org theme designers, but that has stopped. Now, whoever launches a theme has an additional step of moving this newly released theme to the top
* Theme Trends: 

### What needs to be done?

* Correlate new goals with theme features.
* Define the initial order of showcase.
* "Immediate upsell requests removed"
* Figuring out upsells of Paid Themes vs. Global Styles

**Design todo's:**

- [ ] https://github.com/Automattic/wp-calypso/issues/95789

**Comment by nuriapenya** [comment] 2024-10-30 07:41
@autumnfjeld @richtabor is this a duplicate of #95493 ?

**Comment by autumnfjeld** [comment] 2024-10-31 05:00
Yes, sorry about that I must have missed the one Rich created.  Let's keep this one, since it already has content I'll delete the other one.

**Comment by richtabor** [comment] 2024-11-09 01:50
I see this more of a dev task no? Taking the current Design Picker and ensuring the defined goals influence the active theme category.

**Comment by nuriapenya** [comment] 2024-11-26 07:54
Closing in favour of: https://github.com/Automattic/wp-calypso/issues/95789

**Closed as completed by nuriapenya** 2024-11-26 07:54 UTC
Labels: [Feature Group] Appearance & Themes, [Feature] Theme Showcase, [Feature] Design Picker, [Feature] Global Styles, [Experiment] AI labels added

**Comment by autumnfjeld** [comment] 2024-11-27 03:00
I'm deleting this, as there are already many issues related to this:
https://github.com/Automattic/wp-calypso/issues/95495
https://github.com/Automattic/wp-calypso/issues/95789

We won't consider this work part of "onboarding flows" rather it is part of [Design Picker and Theme Showcase](https://github.com/Automattic/wp-calypso/issues/95472#top)
