### ISSUE TITLE
Customizer > Additional CSS -- Variables not saving in Premium.

### ISSUE THREAD

**Issue by danielk-am** [Automattic/wp-calypso#59568] opened 2021-12-27 06:53 UTC
### Quick summary

Customizer > Additional CSS -- Variables not saving in Premium.

Variables not saving for both root (global) and local (within classes) when saving on a Premium plan.

The above works on Atomic sites (tested on Business).

**Expected:** Screen recording (on a Business plan) [35s]:

https://user-images.githubusercontent.com/92185881/147443401-5e5916b2-29cf-4260-a59b-51c92189fc17.mp4

**Results:** Screen recording (on a Premium plan) [1m 05s]:

https://user-images.githubusercontent.com/92185881/147443342-21f21193-43c7-4fff-a773-8a64c58efdb4.mp4

### Steps to reproduce

1. Customizer > Additional CSS (Simple Site)
2. Write a local or global variable (eg: .random-class { --a: 'abc'; }), save and refresh.
3. The class is saved, but the variable is not.

### What you expected to happen

I expected the variable to be saved, similar to the results on an Atomic site (it works on a Business plan).

### What actually happened

Variable wasn't saving.

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

**Comment by formosattic** [comment] 2022-01-04 08:04
Able to reproduce.

Pointing out that this is something we support, see https://wordpress.com/support/editing-css/#preprocessor :

> This is an advanced option for users who wish to take advantage of CSS extensions like variables and mixins.

**Comment by katiebethbrown** [comment] 2022-01-27 19:59
We've run into this issue working on a new Team51 site as well.

I've tested, and I cannot replicate on a Pressable site or an Atomic site. Both of those correct save and use the variables.

The variables are only stripped when added to Additional CSS on simple sites.

**Comment by katiebethbrown** [comment] 2022-01-27 23:48
I wanted to add - the customizer save doesn't indicate that there was any issue. The save completes and there are no changes. 

The missing variables only become obvious once you reload the page, so anyone working in the Customizer could make quite of bit of progress, and have it removed without ever being aware of it.

![CleanShot 2022-01-27 at 16 01 44](https://user-images.githubusercontent.com/42279181/151462082-662e7e80-587d-4746-ab09-341ff3b102f1.gif)

**Comment by arthur791004** [comment] 2022-02-18 09:32
This is CSS Tidy Related issue

**Comment by arthur791004** [comment] 2022-02-18 09:46
This is a duplicate of https://github.com/Automattic/wp-calypso/issues/45409, closing in favor of that one!

**Closed as completed by arthur791004** 2022-02-18 09:46 UTC
Labels: Bug, [Pri] Normal
