### ISSUE TITLE
[Bug]: FSE sites — footer credit link opens site name and logo in customizer

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#60665] opened 2022-01-31 12:41 UTC
### Quick summary

When clicking Footer credits link, I get customizer but no footer credit settings available

FYI @vindl /Cylon to triage.

### Steps to reproduce

Go to settings and click this:

<img width="807" alt="Screenshot 2022-01-31 at 14 39 42" src="https://user-images.githubusercontent.com/87168/151795425-ac610ea4-1355-4926-a073-9d9db3cc4652.png">

End up here:

<img width="359" alt="Screenshot 2022-01-31 at 14 39 59" src="https://user-images.githubusercontent.com/87168/151795454-17d31142-3c6a-452a-906c-6ce911f2f7db.png">

`https://wordpress.com/customize/identity/[SITE]`

### What you expected to happen

Footer credits settings

### What actually happened

No footer credits settings

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by creativecoder** [comment] 2022-03-01 20:20
Duplicate of https://github.com/Automattic/wp-calypso/issues/58798

**Closed as completed by creativecoder** 2022-03-01 20:20 UTC
Labels: Bug, [Pri] Normal, Needs triage
