### ISSUE TITLE
Cover block missing screen width responsiveness

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#66448] opened 2022-08-10 10:42 UTC
### Quick summary

URL:     /fordsfightforlife.com/
The home page is not responsive.
When you try to squeeze the page this occurs - https://d.pr/v/c82ZMs

### Steps to reproduce

* The site has a cover block with text in
<img width="1232" alt="Markup 2022-08-10 at 11 37 56" src="https://user-images.githubusercontent.com/13706336/183881638-b986f8a8-c701-4c59-8ebe-057765a0b8ca.png">
* Tried this on a test site with a Premium plan and the same theme and it also does the same thing.
* Theme is Mordan

* It seems to be a combination of problems
* If you set the alignment of the content within the cover block to center rather than left align then it starts to work -

<img width="1079" alt="Markup 2022-08-10 at 11 33 56" src="https://user-images.githubusercontent.com/13706336/183881838-658068cb-1506-4472-a49a-4958a71afd6a.png">

* If it's set to left it doesn't work. It's not responsive.
* However, you also have to change the numbers "10.7.21" to a paragraph block. If it stays as a heading block it still isn't responsive.
* Also tried on the theme Pendant and the words and buttons become responsive but not the text "10.7.21"

### What you expected to happen

The site to be responsive and the text to wrap when screensize reduces

### What actually happened

Please see video

Uploading Screen Capture on 2022-08-10 at 11-32-38.mp4…

 

### Context

5467135-zd

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

It acts differently on Mordan (the original theme) and on Pendant but neither works correctly.

### Reproducibility

Consistent

### Severity

One

### Workaround details

Yes, but it doesn't produce the result the user wants or what the UI offers.
By center aligning the cover block content and turning the heading to a paragraph block.

**Comment by cuemarie** [comment] 2022-08-11 18:11
📌 SCRUBBING
- Tested on Simple ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- ❌ I was not able to reproduce this issue, following these steps:

**Steps taken to reproduce**

1. On simple site, activate theme Morden
2. New Post
3. Add Cover Block, and add 1 heading block, 1 paragraph block, and 1 buttons block inside
4. Set Cover Block to `Center Left`

**Results**

https://user-images.githubusercontent.com/27249804/184209078-55a699cd-ba40-421f-99de-6091fb370cc2.mov

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
Hi @rickmgithub,Thanks for this report! Following the steps I noted above, I was not able to replicate this issue.  A few requests for you if you find this is still reproducable on your side:

1. Can you please remove the Droplr link you've shared above, and replace that with an uploaded file? For more context, please see: pbg9X-fWF-p2
2. Additionally, it looks like the video you started to upload under **What Actually Happened** wasn't able to finish uploading when you published the report, so that's not visible.
3. If you can reproduce the issue, feel free to reopen, and please include clear steps that we can follow to reproduce the issue during triage. Thanks!

**Closed as completed by cuemarie** 2022-08-11 18:11 UTC
Labels: Bug, [Pri] Normal, Triaged, [Closed] Not Reproducible, [Platform] Simple
