### ISSUE TITLE
Publicize: Re-publicize showing as only available to Premium

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#14307] opened 2017-05-21 12:25 UTC
When you have a site on the free plan the re-publicize option is showing like it was only available for the Premium plan, as follows:

![screen shot 2017-05-21 at 09 07 57](https://cloud.githubusercontent.com/assets/16104522/26283921/b0b955b8-3e06-11e7-97ce-0bb4c3b55132.png)

It should show something like "Upgrade your plan", since it's also available on the Personal plan, but then the message _"Get unlimited premium themes, video uploads, monetize your site and more."_ needs to be changed too, since these features are not included on Personal, to something like _"Get live chat support, more storage and hide the ads from your site"_.

Once you click on the "Upgrade to Premium" button, this is what it loads:

![screen shot 2017-05-21 at 09 08 26](https://cloud.githubusercontent.com/assets/16104522/26283922/b0b9b134-3e06-11e7-8ca1-62a238c0c9d4.png)

This feature is already showing correctly on the Plans page and I also have added on the Publicize support doc page.

**Comment by benhuberman** [comment] 2017-05-23 18:32
I suspect this might be due to the fact the copy was written when this feature was only in the Premium/Business plans. 

"Upgrade your plan" works for the CTA button. For the description, how about:

> Get extra storage, live chat support, and an ads-free website.

Happy to tweak further, @carinapilar!

**Comment by carinapilar** [comment] 2017-05-25 21:05
I loved the description!

**Comment by iamgabrielma** [comment] 2017-07-01 10:43
When checking this from a free site at https://wordpress.com/posts/ I see the following: 

<img width="589" alt="screen shot 2017-07-01 at 12 34 12" src="https://user-images.githubusercontent.com/3812076/27761302-ab5e99fc-5e59-11e7-9316-73306a8f9f82.png">

Seems that this was changed here: https://github.com/Automattic/wp-calypso/pull/15172

Looks like the nudge is based on your current plan, I will need some more testing as I'm not quite sure why is nudging me with a Premium plan if I'm on a free one, skipping the personal one.

Also the price is off, `$8.25` is the Premium plan price / 12 months, but by the image looks like that's the total cost.

**Comment by iamgabrielma** [comment] 2017-07-03 12:08
Looks like the issue might be here: wp-calypso/client/blocks/post-share/publicize-actions-list.jsx  , but I may be off-rails, maybe @retrofox can throw some light here :D

As the feature was intended for Premium+ Business plans alone at the beginning, but not for personal plans, this looks like triggering the Premium upgrade directly: https://github.com/Automattic/wp-calypso/blob/cb0043f57833197a1db08ce426b83c88d0abd653/client/blocks/post-share/index.jsx#L510

I'm happy to take this @retrofox as seems there is only that change to do, but any advice is welcome :)

**Comment by retrofox** [comment] 2017-07-03 12:20
There are another newest which implements the final (at least for now) marketing changes. 
Please, take a look at this one: https://github.com/Automattic/wp-calypso/pull/15356

**Comment by arunsathiya** [comment] 2017-12-19 06:21
I don't get the issue here. Re-publicize feature was/is available only for WordPress.com Premium plan and WordPress.com Business plan users. It's not available for WordPress.com Personal plan users. Everything looks right. What was changed in July?

**Comment by carinapilar** [comment] 2017-12-19 11:20
Yeah @arunsathiya, I tested now and everything looks different from the original issue. :)

**Comment by arunsathiya** [comment] 2017-12-19 11:30
I am confused more, @carinapilar. The original issue was that re-publicize is mentioned to be available only for WordPress.com Premium plan and above, which is right. There is necessarily no need for this issue to be created here on Github. Please let me know if I am missing something.

**Comment by carinapilar** [comment] 2017-12-19 17:07
> The original issue was that re-publicize is mentioned to be available only for WordPress.com Premium plan and above, which is right.

That's true now @arunsathiya, but wasn't at the time I created this. The issue was related to the fact that the upgrade button was saying that you could get the re-publicize feature upgrading to the Premium plan, instead of just upgrading to any plan, since it was available on all of them. When I created the issue the re-publicize feature was also available for the Personal one.

Since now the feature is only available to Premium and Business plans, the issue got resolved already. :)

**Comment by arunsathiya** [comment] 2017-12-19 17:13
Gotcha! I just looked clearly at the second image you had published in this thread originally. "Targeted social media" was available on WordPress.com Personal plan too, which isn't the case now. Thanks for clarifying, @carinapilar!

**Comment by rachelmcr** [comment] 2018-09-03 10:06
Closing as resolved by https://github.com/Automattic/wp-calypso/pull/15356.

**Closed by rachelmcr** 2018-09-03 10:06 UTC
Labels: Sharing, [Status] Needs Copy Review, [Type] Bug, good first issue
