### ISSUE TITLE
WooCommerce Sample Products Replace Pages or Posts with the Same ID

### ISSUE THREAD

**Issue by cat-og** [Automattic/wp-calypso#72043] opened 2023-01-13 05:10 UTC
### Quick summary

The sample_products.csv that is included with WooCommerce has ID values that range from 44 to 90 (skipping a few in between).

If there is currently a post or page ID that falls in that range, and the sample_products.csv is imported, the currently existing content is overwritten by product data, and links in the Navigation block automatically update to direct to the product. 

The overwritten content cannot be found or accessed on the site or restored with the Jetpack Activity Log. 

This happens on Atomic sites, but not self-hosted WordPress sites using WooCommerce. 

### Steps to reproduce

1. Created a fresh AT site.
2. Created a bunch of new posts/pages*
3. Created enough posts/pages to have post IDs that go up to 50.
4. Installed WooCommerce.
5. Imported the products.
6. Checked Posts/Pages > All Posts/Pages, and the posts/pages were disappearing as the import was happening
*This was tested (on separate test sites) with Posts and Pages, same results either way. 

### What you expected to happen

I expected the Sample products to be added to the site without interacting with the existing content. 

### What actually happened

Any posts or pages sharing an ID number with the imported products were completely removed from the site, and Navigation blocks that linked to the page were updated to link instead to the corresponding product. 

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

The preventative workaround would be to ensure that there are copies of any posts/pages that use ID numbers in the 40-90 range so that if they are cleared by overwriting the demo files, they can be replaced. 

The solution if pages or posts need to be restored is to remove the products with the corresponding ID numbers and restore the missing pages via phpMyAdmin or mySQL, then clear the site cache, and has always required HE support in the past.

**Comment by csmcneill** [comment] 2023-01-18 19:01
I helped @cat-og figure out this issue, and it's worth noting that the importing of the sample products occurs during the WooCommerce startup checklist:

<img width="614" alt="Markup 2023-01-12 at 20 12 06 (1)" src="https://user-images.githubusercontent.com/82999806/213270192-64d31118-7b6a-40d1-ad74-b04275422126.png">

This is the option that I used to import the sample products. There are other methods of importing products (e.g. **Tools > Import > Choose From Full List > WooCommerce products (CSV)** or **Products > All Products > Import**), but those were not tested.

**Comment by ilyasfoo** [comment] 2023-01-25 02:42
Hi @cat-og @csmcneill, thank you for the reports. I think this may affect regular, non-AT sites as well. Thus, it would be better if it's fixed in WooCommerce plugin instead.

Will it be ok for you to help transfer the issue to WooCommerce plugin?

**Comment by csmcneill** [comment] 2023-02-06 04:58
> I think this may affect regular, non-AT sites as well. Thus, it would be better if it's fixed in WooCommerce plugin instead.
> 
> Will it be ok for you to help transfer the issue to WooCommerce plugin?

@ilyasfoo Before @cat-og opened up this issue, I tested on a self-hosted (non-Pressable, non-JN) site and was unable to reproduce the issue. I could only reproduce it in an Atomic environment.

**Comment by moon0326** [comment] 2023-02-15 02:38
@ilyasfoo I was only able to reproduce it on an Atomic site.

My best guess is that there is a code snippet somewhere in Atomic site where it sets [update_existing](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/import/class-wc-product-csv-importer.php#L49) param via [woocommerce_product_csv_importer_args](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/API/OnboardingTasks.php#L326) filter.

The best solution is to remove `ID` column unless there is a good reason to keep it. I've tested locally without ID column and the import process worked as expected.

What do you think? We could work on it this week and include it before the code freeze.

**Comment by ilyasfoo** [comment] 2023-02-15 02:51
> @ilyasfoo Before @cat-og opened up this issue, I tested on a self-hosted (non-Pressable, non-JN) site and was unable to reproduce the issue. I could only reproduce it in an Atomic environment.

Thanks for confirming @csmcneill!

> The best solution is to remove ID column unless there is a good reason to keep it. I've tested locally without ID column and the import process worked as expected.
> 
> What do you think? We could work on it this week and include it before the code freeze.

@moon0326 That sounds perfect 👍

**Comment by ilyasfoo** [comment] 2023-02-20 02:27
@moon0326 has fixed this issue in Woo Core by removing product IDs from sample CSV import, https://github.com/woocommerce/woocommerce/pull/36857. It's expected to be included in 7.5 which is slated for mid-March

Please let us know if this isn't fixed by then, or if there is urgency in fixing it for atomic

**Closed as completed** 2023-02-20 02:31 UTC
Labels: Bug, [Pri] Normal, WooCommerce, [Platform] Atomic
