### ISSUE TITLE
Styling broken when visiting /start/account when already logged in

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#47595] opened 2020-11-19 15:43 UTC
#### Steps to reproduce

0. Log into a WordPres.com account
1. Starting at URL: https://wordpress.com/start/account
2. You will be redirected to https://wordpress.com/home/example.com with broken styling

#### What I expected
To be redirected but see normal styling 

#### What happened instead
The styling is broken only when redirected. If you refresh or visit https://wordpress.com/home/example.com directly the styling is correct. 

#### Browser / OS version
Chrome 86

#### Screenshot / Video
<img width="1263" alt="Screen Shot 2020-11-19 at 10 36 56 AM" src="https://user-images.githubusercontent.com/1900444/99688508-e2c2c700-2a53-11eb-9939-216488fa27b0.png">

#### Context / Source

#reallife #dogfooding, #manual-testing

**Comment by obenland** [comment] 2021-01-29 23:25
@simison Is this something Create could look at?

**Comment by simison** [comment] 2021-01-31 13:59
Ah, we've seen this before. It's something at framework level (cc @Automattic/team-calypso and @ciampo who was looking into this).

**Comment by ciampo** [comment] 2021-02-01 07:34
As @simison wrote, we've been aware of this issue for a few months. I started investigating into the problem, and then @jsnajdr took over since the solution would require a substantial refactor of how the routing works in Calypso.

We can probably close this issue and leave the original (#46084) open?

**Comment by jsnajdr** [comment] 2021-02-01 07:35
What is going on:
1. Server renders a page for `/start/account`, which is a mostly empty placeholder which has `is-section-signup` and `is-white-signup` CSS classes on the `body` element.
2. Now the expectation is that the client app renders a `<Layout />` component with a `<BodySectionCssClass section="signup" bodyCssClass="is-white-signup" />` subcomponent. That `<BodySectionCssClass />` will take ownership of the `body` CSS classes, and will remove them when navigating away from Signup.
3. But that render never happens: the client app redirects from `/start/account` to `/home` right away, without ever rendering anything.
4. Home is rendered with `<BodySectionCssClass group="sites" section="home" />`, which adds `is-group-sites` and `is-section-home` CSS classes to `body`. But the old `is-section-signup` and `is-white-signup` stay there, and the first one is the one that actually breaks the Home layout.

Solutions:
- improve the `BodySectionCssClass` component to own any `is-section-*` and `is-section-*` classnames and remove them on change. But that won't remove `is-white-signup`.
- change the Signup controller to "own" the CSS classes and clean them up before redirecting to a location outside Signup.

**Comment by jsnajdr** [comment] 2021-02-01 07:38
> we've been aware of this issue for a few months.

@ciampo I think this issue is different, although both involve the `body.is-section-signup` CSS class. The original one was about a short flash of broken content between the page.js navigation and the `setSection` Redux action dispatch. But here the broken content is permanent.

**Comment by simison** [comment] 2021-02-01 07:38
I'll add one more solution:
- Get rid of blue color on signup (kinda what we're headed but it'll take time) :-)

**Comment by jsnajdr** [comment] 2021-02-01 07:46
Here it's not just the colors that make things break. There is also a `body.is-section-signup .layout__content { padding }` rule that makes the sidebar overlap with the main content. We should refactor these exceptions to a more generic `.has-no-sidebar` CSS class.

**Comment by Aurorum** [comment] 2021-05-04 08:43
Was this fixed by #52055? I can't seem to reproduce it anymore.

**Comment by jsnajdr** [comment] 2021-05-04 08:56
@Aurorum Yes, #52055 implemented the solution I proposed in https://github.com/Automattic/wp-calypso/issues/47595#issuecomment-770639660 -- `<BodySectionCssClass />` now owns all the `is-section-*` CSS classes.

But the `is-white-signup` CSS class will still stay on `<body>` even after navigation to `/home`. That shouldn't be an issue though: all rules, except one, are in the form `.is-section-signup.is-white-signup` and therefore scoped to `.is-section-signup`. The only exception I found is domain price here:

https://github.com/Automattic/wp-calypso/blob/trunk/client/components/domains/domain-product-price/style.scss#L28

If that style can be used outside Signup (I'm not sure), it should be fixed (cc @niranjan-uma-shankar)

**Comment by p-jackson** [comment] 2021-05-10 04:47
The `is-white-signup` CSS class is no longer applied to `<body>` after navigating to `/home`. I don't know what commit changed this behaviour. But I know the class, which is added by SSR, is being removed by the client because of this logic. https://github.com/Automattic/wp-calypso/blob/d833d3c3f4d3a3029f0c90404f8fe4c6ef12ef49/client/signup/controller.js#L118
`removeWhiteBackground()` is being called before the redirect to home.

So that means the broken styling as originally described is no longer reproducible (fixed by #52055), and the potential for a broken style pointed out by @jsnajdr here https://github.com/Automattic/wp-calypso/issues/47595#issuecomment-831786968 is also not a possibility. Marking as fixed.

**Closed by p-jackson** 2021-05-10 04:47 UTC
Labels: Customer Home, Design, My Home Pod, Signup, [Pri] Normal, [Size] S, [Type] Bug
