### ISSUE TITLE
Nav Unification: Stats graph doesn't display when a wp-admin page is open

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#49643] opened 2021-02-03 03:19 UTC
### Steps to reproduce the behavior

1. Toggle on the `replace all pages with WP Admin equivalents when possible` option
2. Click on any link that opens a wp-admin page (I used Settings > General)

#### What I expected to happen

For the stats graph to continue to display

<img width="310" alt="txMT67" src="https://user-images.githubusercontent.com/42279181/106693288-62f8c300-6593-11eb-99f5-d68f03f5aea2.png">

#### What actually happened

The graph is replaced with the words `Hourly views`

<img width="440" alt="A4E49I" src="https://user-images.githubusercontent.com/42279181/106693178-1f9e5480-6593-11eb-9f5d-41eeb5bb40d6.png">

#### Is this specific to the applied theme? Which one?

Not theme specific.

#### Does this happen on simple or atomic sites or both?

Simple for now. My AT sites don't seem to show the stats graph.

#### Is there any console output or error text?

Yes, a 403 error for 
`https://SITTEURL/wp-includes/charts/admin-bar-hours-scale-2x.php?masterbar=1&s=150243501`

**Comment by malihanan** [comment] 2021-02-03 06:19
Hey, may I work on this issue?

**Comment by getdave** [comment] 2021-02-03 13:57
> Hey, may I work on this issue?

Hi @malihanan. Thank you for your interest in contributing to Calypso. It would be great to have your help!

Unfortunately, this particular issue isn't easily reproducible in a public environment so it's going to be tricky for you to work on.

However, we'd really appreciate you taking a look at any of [the Issues labelled with `Good First Issue`](https://github.com/Automattic/wp-calypso/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). These should be ideal and it would be great to have you work on them.

Thanks again for your interest.

**Comment by getdave** [comment] 2021-02-03 13:58
@katiebethbrown I've tried to reproduce this without success. Indeed all my Simple sites are showing a stats graph.

Could you possibly re-check the issue is still occurring? If so please feel free to remove the `Not Reproducible` label and then add me to your site and then DM me the details to I can take a look? It would be much appreciated.

**Comment by obenland** [comment] 2021-02-04 23:59
It's possible that we need to come up with a fancier way to get to the underlying `*.wordpress.com` domain than using [`site_url()`](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php#L190).

@katiebethbrown Is the site you found this on using a custom domain?

**Comment by katiebethbrown** [comment] 2021-02-07 19:25
>Could you possibly re-check the issue is still occurring?

>Is the site you found this on using a custom domain?

Sure. I just checked and I'm still seeing the issue on my simple site, and yes, it has a custom domain as primary.

I checked the console again and there are also warnings about mixed/insecure content related to the stats graph:

<img width="1382" alt="XaCLxC" src="https://user-images.githubusercontent.com/42279181/107157059-37812a00-693f-11eb-8f7b-4e72d74bdc11.png">

```Loading mixed (insecure) display content “https://testrandom456456456.blog/wp-includes/charts/admin-bar-hours-scale-2x.php?masterbar=1&s=150243501” on a secure page```

I can see that it looks like line 212 of `options-general.php` might be using the http version of the address for the src:

<img width="898" alt="j85WaM" src="https://user-images.githubusercontent.com/42279181/107157076-52539e80-693f-11eb-8a32-5d318868e0e8.png">

**Comment by getdave** [comment] 2021-03-08 16:35
This could be an issued with mapped domains.

**Comment by cpapazoglou** [comment] 2021-03-09 13:24
> This could be an issued with mapped domains.

Indeed it happens to `http://automattic.com/wp-admin` and my personal blog where "Redirect" is also shown

![](https://cln.sh/jju9qn+)

**Comment by cpapazoglou** [comment] 2021-03-09 13:51
It's interesting that this was fixed in https://github.com/Automattic/jetpack/pull/18300 but the diff was never deployed in wpcom 😜! Deployed now!

**Closed as completed by cpapazoglou** 2021-03-09 13:51 UTC
Labels: Bug, [Pri] High, [Feature] Calypso & wp-admin Navigation, Triaged
