### ISSUE TITLE
Choosing Pexels from any image block gives a 'cURL 6: could not resolve host: host.docker.internal' error

### ISSUE THREAD

**Issue by geekinthegirl** [Automattic/wp-calypso#62046] opened 2022-03-18 09:57 UTC
### Quick summary

When adding any kind of image to a page or post via the image block or featured image, then choosing Select Image > Pexels, the following error shows:
<img width="1679" alt="Screenshot 2022-03-17 at 11 34 22" src="https://user-images.githubusercontent.com/22247240/158979238-a8006b1c-2c62-4e6a-b5ac-efc5beb51e50.png">

This seems to be happeining intermittently for myself and other members of my team - unsure if it's due to our connection, but it's a constant issue for some of us, while others are unaffected.

### Steps to reproduce

- Create or edit a post, page or template
- Choose to add an image block or set a featured image
- Click Select Image > Pexels
- Search for any image category

### What you expected to happen

A selection of Pexels images from the chosen category should appear, and be clickable in order to be added to the page/post.

### What actually happened

The search is empty, and instead shows 'cURL 6: could not resolve host: host.docker.internal'

### Context

Found during teamm testing of Full Site Editing.

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

We're all using MacOS, but with various browsers (Firefox, Chrome)

### Reproducibility

Intermittent

### Severity

Some (< 50%)

**Comment by Greatdane** [comment] 2022-03-30 05:31
It looks like this is an issue with docker (I am not sure if we use docker or plexels does)
re; https://github.com/docker/for-mac/issues/2965

@geekinthegirl I am unable to replicate it. I am going to close it for now, but if you can reproduce it, can you check if the browser has any console errors as well? We can always reopen the issue with more info!

**Closed as completed** 2022-03-30 05:31 UTC
Labels: Bug, Images, Pexels
