### ISSUE TITLE
Bug: Editor Publicize Custom Message Reverting To Default 

### ISSUE THREAD

**Issue by Sarah-Withers** [Automattic/wp-calypso#12536] opened 2017-03-26 20:40 UTC
#### Steps to reproduce
1. Starting at WP.com new post
2.  Post Settings - Sharing
3. Type customised message to share post via twitter
4. Hit save

#### What I expected
The custom text would save ready for when I decided to publish

#### What happened instead
What I typed reverted back to the default post title.

#### Browser / OS version
Chrome 57.0.2987.98

#### Screenshot / Video
![twitter](https://cloud.githubusercontent.com/assets/26696320/24334970/87c73f00-126c-11e7-9a5e-7ef948ffb0b1.gif)

#### Context / Source
On this occasion this happened after I had selected a previous post to copy and edited. It's happened a number of times this week but I can't remember if I had chosen to copy a post on every occasion.

**Comment by timmyc** [comment] 2017-04-07 18:52
I could not reproduce this on a fresh draft, but was able to confirm the bug when using the copy post flow.  Sounds somewhat similar to #12506 /cc @Copons

**Comment by Copons** [comment] 2017-04-08 00:19
@timmyc It's definitely similar, also because it turned out the issue wasn't fixed with that PR.
It's all currently under investigation, but I still can't quite understand what makes (part of) the post data to "not stick" after a copy.

@Sarah-Withers I'm so sorry you're experiencing this issue and I hope it's not disrupting your workflow too much.
Just in case, though, there's a workaround: copy the post and save it (manually or wait for the autosave to trigger); go back to the draft list and edit the post. Now everything should work fine.

**Comment by timmyc** [comment] 2017-04-10 16:13
>  but I still can't quite understand what makes (part of) the post data to "not stick" after a copy

Could it possibly be related to the mixed state of editor data between flux and redux?

**Comment by Copons** [comment] 2017-04-10 16:25
It's what I've be try ascertain to no avail.

Copying a post sets both Flux and Redux (https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/controller.js#L117-L154).
But what I really can't understand is what causes **some** data (featured image and publicize message - might it be the post meta?) to revert to the original state, nor even when!

The only thing I got is that Copy dispatches pretty much twice the (Redux) actions as I intended to dispatch (and I don't really know how to appropriately debug Flux, so who knows what's going on there!). I guess this is caused by something in [here](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/post-editor.jsx#L399-L436), but I don't know much more yet.

**Closed** 2017-05-12 12:53 UTC
Labels: Editor, OSS Citizen, Sharing, [Type] Bug
