### ISSUE TITLE
Block Widgets: Only Saving on Second Attempt

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#53742] opened 2021-06-16 11:01 UTC
### Steps to reproduce the behavior

1. Open Appearance > Widgets
2. Add one widget
3. Hit Update

#### What I expected to happen
To save the changes and disable the Update button.

#### What actually happened
It keeps the Update button active as if it didn't save, it also shows the warning that you might lose your changes if you leave the page.

#### Browser / OS version
Chrome 91.0.4472.101
OS X 10.15.7

#### Screenshot / Video
![WidgetBlocksIssue1](https://user-images.githubusercontent.com/16104522/122207808-e945df80-ce78-11eb-8abe-92edbafd72df.gif)

**Comment by rinazrina** [comment] 2021-07-30 11:20
Another report: 30881088-hc

On the user's site -- after reordering widgets, the changes are not saving.

**Comment by alshakero** [comment] 2021-08-09 16:01
I can't reproduce this on Atomic sites and simple sites have entirely different UI.

Is anyone able to reproduce now?

**Comment by carinapilar** [comment] 2021-08-10 10:44
I'm not being able to replicate this anymore, no. I tried on Simple and WordPress.org sites, it worked as expected now. 😌

**Comment by alshakero** [comment] 2021-08-10 10:48
Perfect. Thanks a lot! Let's close it for the meantime.

**Closed as completed by alshakero** 2021-08-10 10:48 UTC
Labels: Bug, [Pri] High, Triaged
