### ISSUE TITLE
Site Editor: Content is greyed out

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#84262] opened 2023-11-16 17:08 UTC
### Quick summary

Sometimes the content in a template is greyed out in the Site Editor:
<img width="1769" alt="Screenshot 2023-11-16 at 17 09 06" src="https://github.com/Automattic/wp-calypso/assets/275961/04c47683-ca90-4592-be64-9aeb0d2b47c6">

This is very confusing for users, as it looks like the content cannot be edited.

### Steps to reproduce

1. Log in to a site using the Enroute theme. I saw this on https://pressmentor.org
2. Open the Site Editor
3. Edit the front page template 

### What you expected to happen

The page should appear as it does in the front end.

### What actually happened

All of the content of the template was greyed out.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by liviopv** [comment] 2023-11-18 08:42
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Atomic / Gutenberg 17.0.2 / Chrome 119
![CleanShot 2023-11-18 at 09 35 03@2x](https://github.com/Automattic/wp-calypso/assets/14153300/19fce6a3-7916-4c69-a60e-8dd774f1d08c)

Simple / Gutenberg 17.0.2. / Chrome 119
![CleanShot 2023-11-18 at 09 38 00@2x](https://github.com/Automattic/wp-calypso/assets/14153300/08a97253-569c-4b84-acf7-3bb2ddc03975)

📌 ACTIONS
- Closed as could not replicate 

📌 Message to Author
@scruffian please reopen if the issue reoccurs or if there are any steps I'm missing. It might be worth testing with https://wordpress.org/plugins/accessibe/ deactivated to see if the issue is still present on your site.

**Closed as completed by liviopv** 2023-11-18 08:42 UTC
Labels: Bug, [Pri] High, [Closed] Not Reproducible, Needs triage, [Feature] Full Site Editor, [Status] Priority Review Triggered
