### ISSUE TITLE
Coblocks: custom URLs do not persist in images in Offset gallery

### ISSUE THREAD

**Issue by andreabadgley** [Automattic/wp-calypso#38487] opened 2019-12-17 21:05 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/
2. Add a Coblocks Offset block
3. Add several images to block
4. Select an image and then go to Link Settings > Custom URL
5. Add a custom URL to the field on the image.
6. Publish or Update the page or post
7. Test link in published page or post and it works successfully.
8. Exit the edit screen for the page or post.
9. Re-enter the edit screen for the page or post.
10. Custom URL has disappeared.

This happens in both the original theme it was reported in (Shawburn) and Twenty Seventeen.

#### What I expected
I expected the custom URL Link Setting to persist each time I access the edit screen.

#### What happened instead
After exiting and re-entering the edit screen, the custom URL disappears for each image in the Coblock Offset block.

#### Screencast
https://d.pr/i/tugJTG 

#### Browser / OS version
Chrome Version 78.0.3904.108 (Official Build) (64-bit) and Firefox 71.0 (64-bit)

#### Context / Source
A user reported this in 17377085-hc. They would like to be contacted in 2568392-zen when we have an update.

**Comment by andreabadgley** [comment] 2019-12-17 21:10
As a workaround, I advised the user try column blocks instead, then add their images and the custom URLs in the columns.

**Comment by kathrynwp** [comment] 2019-12-28 20:37
Also reported in 2589538-zen - please notify user when fixed.

**Comment by mmtr** [comment] 2020-01-02 13:00
This is caused by this CoBlocks issue: https://github.com/godaddy-wordpress/coblocks/issues/1227

WP.com auto-fixes invalid blocks like the ones resulted by adding an offset block with custom URLs and during that auto-fix the URL is removed.

To sort out this, we need to update the CoBlocks version used in WP.com once https://github.com/godaddy-wordpress/coblocks/issues/1227 is solved and a new release including it is out.

**Comment by davipontesblog** [comment] 2020-06-12 01:07
Noting that godaddy-wordpress/coblocks#1227 is now closed with CoBlocks. @mmtr what team is responsible for updating CoBlocks in Dotcom?

**Comment by mmtr** [comment] 2020-06-12 09:15
@davipontesblog I believe @Automattic/ajax took over CoBlocks maintenance (paYJgx-FR-p2).

**Comment by cathymcbride** [comment] 2020-09-24 19:47
Bug should be fixed in CoBlocks 1.19.2. We are currently at 2.2.2 and I'm not reproing. 🎉  Closing...

**Closed by cathymcbride** 2020-09-24 19:47 UTC
Labels: Blocks, [Type] Bug
