### ISSUE TITLE
Plans: Show Store sidebar item for Business sites if they selected "Online store" segment during signup

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#33341] opened 2019-05-27 03:55 UTC
As brought up in p58i-7Pk-p2, customers on Business plan have the ability to create a store, but this option is only surfaced after a customer installs a plugin, or a theme. At that point a Store menu item will appear in the nav drawer. Showing the Store menu item immediately after upgrading (and perhaps including it in plan features on `plans/my-plan`, and "thank you" post-purchase pages) would drive more people to use it, and show the unique value of Business plan. 

In the post an idea came up as well, to show the Store item on all plans (similar to how custom CSS option is in the Customizer in all plans), with prompt to upgrade to Business for customers on lower plans.

#### What I expected
For the Store menu item to be immediately available in the nav drawer. What happens after customer clicks still needs figuring out. If we can't step around the requirement to install plugin/theme first, we could at least show a message to that effect. 
I also expected a card on the plan features page/ post-upgrade "thank you" page, that advertises Store feature.

**Comment by alaczek** [comment] 2019-05-28 02:49
I've chatted about this a little bit with @sixhours, and while installing plugin/theme is required, it would be nice if we didn't send off customers interested in Store feature on separate adventure (fraught with broken flows), in order to use it. So one option that might be worth exploring, would be to show customers who haven't installed theme/plugin yet some sort of splash screen, with action button to "Activate store". Clicking the button would install a plugin behind the scenes (plugin choice is an open question), and thus make site Atomic, and enable the Store functionality.

**Comment by mattsherman** [comment] 2019-06-04 19:07
https://github.com/Automattic/wp-calypso/issues/33549 is a duplicate of this. Going to close that one and title this one to more accurately reflect what this issue intends.

**Comment by mattsherman** [comment] 2019-06-06 20:05
We (Samus) are working on a related eCommerce issue (https://github.com/Automattic/wp-calypso/issues/33543). Is there an ETA on when this issue is expected to be addressed? That may influence the details of how we handle the related issue.

**Comment by jffng** [comment] 2019-06-06 21:36
I was planning on looking at this next week. Does that timing work?

**Comment by mattsherman** [comment] 2019-06-07 11:34
@jffng Thanks. I think that timing will work well. If this will be addressed in the near term, then I think we are okay proceeding as we plan in #33543 (showing Business, along with eCommerce, when they select that want to create an online store).  /cc @jonathansadowski @creativecoder

**Comment by jffng** [comment] 2019-06-14 14:14
Made a change to show the store link in the sidenav by default if the user is on a business or ecommerce plan. If a business user hasn't triggered the atomic transfer, clicking on the store sidenav link drops them into this flow: 

<img width="600" alt="Screen Shot 2019-06-14 at 7 11 21 AM" src="https://user-images.githubusercontent.com/5375500/59515384-d7896600-8e73-11e9-93fa-dd97b7482357.png">

@druesome would you be able to identify any implications we're not seeing by making this change?

**Comment by druesome** [comment] 2019-06-15 18:08
This looks like a great way to help users get started with their stores.  I don't see any big implications, as long as the flow is clear and goes through the proper eligibility checks for installing plugins, this should be ok.

May I suggest:

1) Click Store sidenav link
2) System checks if site is eligible (has to have at least Business Plan, site is launched and public, user must be admin and owner, etc) (more here: https://github.com/Automattic/wp-calypso/blob/27b84329e09c55173d1ffc3854e56665a43930da/client/blocks/eligibility-warnings/hold-list.jsx#L20)
3) Site passes criteria, show `Set up my store!` button
4) If not, hide button, give instructions to correct blockers before proceeding

**Comment by jffng** [comment] 2019-06-17 14:49
Thanks for a robust suggestion @druesome. I'm going to mark the PR as a draft until we can implement the correct checks and instructions on the store landing page.

To verify the criteria:
- Plan is business or e-commerce
- User is admin and owner
- Site is launched and public

Right now my solution suggests that the store sidenav link wouldn't show unless the plan is business or higher. 

> In the post an idea came up as well, to show the Store item on all plans (similar to how custom CSS option is in the Customizer in all plans), with prompt to upgrade to Business for customers on lower plans.

As @alaczek suggested above, what if we showed the store sidenav link regardless of the plan, and offered an option to upgrade if needed?

**Comment by davipontesblog** [comment] 2019-06-17 15:14
> As @alaczek suggested above, what if we showed the store sidenav link regardless of the plan, and offered an option to upgrade if needed?

I think this could be a great way to show users on any plans, that yes - it is possible to have a store here on wpcom, and the way to do that would be to upgrade to Business plan. Many people are currently left wondering if that's even an option here or if this is just a blogging platform. It could help bridge that gap, and funnel sales to the higher plans.

**Comment by jffng** [comment] 2019-06-19 23:27
@davipontesblog agree that it is a good opportunity! I do feel that showing the store link to all users needs some design exploration on how to indicate that an upgrade is required.

In the meantime, I'd like to push forward on showing the link to business users. I'm trying to implement the checks suggested by @druesome and show a respective support message if a check is not met: 

- User is admin and owner
- Site is launched and public

I'm lost in the redux store. Could someone help me understand which selectors I could use to validate the above criteria? 

I've tried `isCurrentUserCurrentPlanOwner`: https://github.com/Automattic/wp-calypso/blob/27b84329e09c55173d1ffc3854e56665a43930da/client/state/sites/plans/selectors.js#L186 but this is returning `false` even though I'm the owner.

And when I use `getUser`: https://github.com/Automattic/wp-calypso/blob/27b84329e09c55173d1ffc3854e56665a43930da/client/state/users/selectors.js#L10 it returns a user object with correct data, but it has no `roles` property.

**Comment by sixhours** [comment] 2019-06-20 15:31
> User is admin and owner

Is it necessary that the user be the plan owner? Could they just be an admin to the site? If so, `canCurrentUser` might work:

https://github.com/Automattic/wp-calypso/blob/f68ef71f58cfc423f42e8f35b0f9ede162e7efa8/client/state/selectors/can-current-user.js#L22

**Closed** 2019-09-23 16:07 UTC
Labels: Design, FixTheFlows, Plans, eCommerce Plan
