### ISSUE TITLE
Setting Featured Image Resets Custom Sizes in Image Blocks

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#29827] opened 2018-12-31 20:08 UTC
When I added three images separately using /image and set sizes on them, they stayed the same, even in preview, but as soon as I added the Featured Image, all the custom sizes were removed. 

#### Steps to reproduce
1. Create a post. 
2. Add an image block and pull in an image from the media library - I used /image.
3. In the Block Settings, change the Width (or height and width).
4. Check in Preview. 
5. Go back to draft and see the custom dimensions are there.
6. Add a Featured Image. 
7. Notice all custom sizes are reset and no longer showing.

Edited to add that the initial reporter lost custom dimensions when adding more images. I could not replicate that, but I could by adding a Featured Image.

#### What I expected
All my custom sizes in the blocks to remain.

#### What happened instead
The settings were missing.

#### Browser / OS version
Firefox on MacBook Pro

#### Screenshot / Video
This is the kicker. I totally replicated the issue, but when I went to report it, I could not replicate it. I tried by adding height, adding width and height, initially came up with the error on a site on a free plan, but it was initially reported from a site on the Premium plan. I also tested on a Premium site and tried linking to media files and not and also tested on a Premium plan test site with the same theme as the reporter, but could not replicate any more. 

My screencasts are in the response to the user report, but they don't demonstrate the issue.
#user-report from #1677915-zen

-->

**Comment by torres126** [comment] 2018-12-31 22:16
This seems to be a duplicate of #29557.

**Comment by KristinaKay** [comment] 2019-01-01 22:56
The user came back and added a video. #1677915-zen

**Comment by brezocordero** [comment] 2019-01-02 20:08
I am closing the issue, fixed here https://github.com/Automattic/wp-calypso/issues/29557 
Customer that reported it has been notified.

**Comment by arcangelinis** [comment] 2019-01-10 23:19
This issue may not be fully resolved. Here is what I am seeing.

1. With other Galleries added to the page, create a new Gallery.
2. Select Media Library and add images.
3. Observe the images being removed from all other galleries.

GIF
![Screenshot](https://llamaeatsagiraffe.files.wordpress.com/2019/01/screen-capture-on-2019-01-08-at-14-24-59.gif)

#1708591-zen

**Comment by gwwar** [comment] 2019-01-10 23:22
@arcangelinis do you mind filing a new issue with steps? see also:
p58i-7CN-p2

**Closed by gwwar** 2019-01-10 23:22 UTC
