### ISSUE TITLE
Dropdown menu gets cut if the Navigation is inserted on a Cover Block

### ISSUE THREAD

**Issue by carolframen** [Automattic/wp-calypso#80151] opened 2023-08-02 18:50 UTC
### Quick summary

If you add the navigation menu on a Cover block and your menu has a dropdown, the dropdown gets cut where the cover block ends.

### Steps to reproduce

- Activate a FSE theme
- Add a Cover block to the header and add the navigation menu on it
- Make sure to add a dropdown on the navigation block
- Make sure the cover block is not too long

### What you expected to happen

- You should be able to see all the options on the dropdown menu

### What actually happened

- the dropdown menu is cut off where the Cover block ends, so it is not possible to see all the options

Here's a video I recorded to explain to the user on the simple site

https://github.com/Automattic/wp-calypso/assets/119800062/5e08de47-225a-4394-baa2-7f9e2290a248

Here are some SS from the atomic site
![nav menu editor](https://github.com/Automattic/wp-calypso/assets/119800062/920c7cfb-c6a0-4693-869b-785ef8ea71a7)

![nav menu site](https://github.com/Automattic/wp-calypso/assets/119800062/c033ceef-ed88-4e64-9fe8-3b7a50c18bfe)

- It is possible to solve this by making the cover block longer or removing the cover block

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- tested it on Firefox 115 and Chrome 115 both on Windows 10
-  On the simple site I tested on Twenty Twenty-Three and Zoologist.
- On the atomic site I tested on Blank Canvas
- I know this is happening because the navigation in on the cover block and this is a very niche situation. Not sure if it is possible to fix it, but reporting so we can check

**Comment by cuemarie** [comment] 2023-08-03 20:21
Thanks for this report! This looks like a duplicate of https://github.com/Automattic/wp-calypso/issues/79317

These stem from the core issue reported here: https://github.com/WordPress/gutenberg/issues/52511

📌 ACTIONS
- Closing as duplicate

**Closed as not planned by cuemarie** 2023-08-03 20:21 UTC
Labels: Bug, [Pri] Low, Triaged, [Platform] Simple, [Platform] Atomic
