### ISSUE TITLE
Nav Unification: Set current site when navigating from wp-admin to Calypso

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#50564] opened 2021-02-27 20:50 UTC
**What**
When using Nav Unification, there's an Account Settings menu item (yay!). Clicking on it, however, throws an unsuspecting user to a page with a completely different nav. It'd be nice if there was a "Back to site" link in the `/me` nav.

**Why**
This would make it clear how to get back to the menu they were just on.

**Comment by tjcafferkey** [comment] 2021-03-03 08:38
Clicking "My sites" from the `/me` page after clicking the Account Settings menu item will take you back to your site.

**Comment by cpapazoglou** [comment] 2021-03-03 09:11
This not a regression of "nav-unification". The "Account Settings" menu already existed as "Personal Settings" which exhibited the same behavior. 

![](https://cln.sh/BdoeLB+)

I agree that the redirection is not expected, I would propose removing that menu which is Account wide related from the menu. Removing the "nav-unification" label for the moment.

**Comment by cpapazoglou** [comment] 2021-03-03 09:15
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/50566

**Comment by obenland** [comment] 2021-03-12 23:24
There's a regression when we navigate from wp-admin to Calypso, particularly outside of site-specific screens, where My Sites is not set to the correct site, but to the default site.

To reproduce:

* Starting from https://wordpress.com/home/
* Select a site other than your default site
* Click Users > Account Settings
* Click My Sites
* Notice how you're at My Home of the previously selected site.

Next:
* Click Feedback
* Click Users > Account Settings
* Click My Sites
* Notice how you're at My Home of your default site, not the site where you came from.

Let's find a way to set the current site when we navigate from wp-admin to `/me` or `/me/account`, so My Sites is in the right context.

**Comment by mreishus** [comment] 2021-04-26 18:04
> There's a regression when we navigate from wp-admin to Calypso, particularly outside of site-specific screens, where My Sites is not set to the correct site, but to the default site.
> 
> To reproduce:
> 
>     * Starting from https://wordpress.com/home/
> 
>     * Select a site other than your default site
> 
>     * Click Users > Account Settings
> 
>     * Click My Sites
> 
>     * Notice how you're at My Home of the previously selected site.
> 

Re-testing today, this one is now working for me (without me making any changes): I am brought back to the previously selected site. (Note: I used Users > Personal Settings as Account Settings didn't appear for me).


> Next:
> 
>     * Click Feedback
> 
>     * Click Users > Account Settings
> 
>     * Click My Sites
> 
>     * Notice how you're at My Home of your default site, not the site where you came from.

Confirmed this is still an issue.  (Note: I used Users > Personal Settings as Account Settings didn't appear for me).

**Comment by mreishus** [comment] 2021-04-26 21:01
My current understanding follows:

* Calypso has the concepts of a **default** site and a **selected** site.
* The **default** site is persisted and stored to our backend servers.
* The **selected** site only exists in front-end state and is lost when you leave calypso.
* Urls like `http://calypso.localhost:3000/stats/day/my-cool-site.blog` allow you to automatically set the **selected** blog by providing it in the url. This is done by the [siteSelection router middleware](https://github.com/Automattic/wp-calypso/blob/074781bdb4ee85dab5040ee42e51313f26b373da/client/my-sites/controller.js#L371), which is listed when [setting up an individual route](https://github.com/Automattic/wp-calypso/blob/074781bdb4ee85dab5040ee42e51313f26b373da/client/gutenberg/editor/index.js#L37) ([stats page example](https://github.com/Automattic/wp-calypso/blob/074781bdb4ee85dab5040ee42e51313f26b373da/client/my-sites/stats/index.js#L31-L33)).
* The router entry for `/me/account` does not include `siteSelection` middleware, therefore it is currently not possible to set a **selected** site while coming to `/me/account` as your first page. Which makes sense, because you don't visit "Account Settings" in the context of a site, you just visit "Account Settings".
* The workflow in the bug is to select a site, to leave calypso and visit that site's `/wp-admin/edit.php` page directly, then come back to `/me/account` in calypso, which does not let you choose a selected site.

So a proposed solution is:
* Add the siteSelection middleware to the `/me/account` router
* Add an additional, optional route for `/me/account/mycoolsite.blog`, which also sets your selected site
* Jetpack or wpcom code modifies simple sites to change the outgoing link to `/me/account` to include the current site name
* Ensure that siteless `/me/account` continues to work without new bugs (like possibly resetting your selected site to the default one), and that links to account settings use the siteless version 99% of the time; we only want to change this one scenario

I'll give it a shot. I currently don't have any other ideas for tackling this.

**Comment by mreishus** [comment] 2021-04-26 21:52
~~* Calypso side: https://github.com/Automattic/wp-calypso/pull/52306~~
~~* Jetpack/wpcom side: https://github.com/Automattic/jetpack/pull/19672~~

**Comment by mreishus** [comment] 2021-04-28 14:56
Will be fixed by Automattic/wp-calypso#52362

**Comment by inaikem** [comment] 2021-04-29 08:28
Sweeping feature requests for relevance. Looks good, and is set to be resolved soon. Thanks to everyone involved.

**Comment by cpapazoglou** [comment] 2021-04-29 12:22
> Will be fixed by #52362

@mreishus I am afraid that #52362 doesn't solve all scenarios. While it solves the scenario Calypso -> WP Admin -> Calypso it doesn't account for WP Admin -> Calypso. Meaning that if the site in Calypso is set to `X` and I directly visit WP Admin of `Y` and then click the link to My Account, then Calypso will load site `X` instead of `Y`. 

Sending the WP Admin domain to Calypso while redirecting is something we cannot avoid (like your initial patches). We could explore though, trying to set the current selected site from the referrer domain.

**Comment by mreishus** [comment] 2021-04-29 18:35
Ah, good point. 
* Calypso -> WP Admin -> Calypso is fixed
* WP Admin -> Calypso is not

Possible avenues to fix:
* Reimplement something like Calypso side: #52306 + Jetpack/wpcom side: Automattic/jetpack#19672
* Investigate setting up routing middleware that sets the selected site from the referrer domain (Possibly like `siteSelectionQuery` in #52306, but using referrer instead)

My current iteration is over so I will have to leave this to be picked up later.

**Comment by BogdanUngureanu** [comment] 2021-11-03 13:01
Closing this since I'm not able to reproduce the issue anymore with the following testing steps:
- Went directly to WP-Admin on an Atomic site (a non-default site).
- Clicked on Feedback
- Clicked on Users > Account Settings
- Clicked on My Sites
- Went back to WP-Admin
- Clicked on Users > Profile
- Clicked on My Sites

In both cases I was redirected to wordpress.com/home/non-default-site.

**Closed as completed by BogdanUngureanu** 2021-11-03 13:01 UTC
Labels: Bug, [Pri] Normal, [Feature] Calypso & wp-admin Navigation, Triaged

**Comment by tbradsha** [comment] 2021-11-03 14:37
Confirmed it's working now.
