### ISSUE TITLE
Live Chat: pages dosn't load properly when chat box is open

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#4640] opened 2016-04-11 11:43 UTC
Browser: Chrome.

User see only loading indicator when browsing pages that have live chat open:
![untitled](https://cloud.githubusercontent.com/assets/699132/14425909/3b3ad0c8-ffeb-11e5-8be6-1d3389a3c9a7.png)
![untitled1](https://cloud.githubusercontent.com/assets/699132/14425910/3b4623ce-ffeb-11e5-990e-707fd9876259.png)

Error message on JavaScript console:
> "Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document. "

Source:
https://static.olark.com/jsclient/storage.js?v=1460051854552

**Comment by lancewillett** [comment] 2016-04-19 17:02
Could this be related to an Olark outage? I can't reproduce. Suggest closing unless it's happening to everyone.

**Comment by gziolo** [comment] 2016-04-19 17:05
User said, it was the case for a few weeks period in Chrome, but it was working properly in IE. Maybe he has old version of Chrome, but then he should see browser happy page ¯\_(ツ)_/¯

We can close that one. I should ask for browser version :)

**Comment by lancewillett** [comment] 2016-04-19 17:06
Cool, thanks for your notes.

**Closed by lancewillett** 2016-04-19 17:06 UTC
Labels: Live Chat, [Pri] High, [Type] Bug
