### ISSUE TITLE
Media: Image Editor gets very confused on MS Edge

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#8006] opened 2016-09-09 18:23 UTC
#### Steps to reproduce
1. Starting at URL using MS Edge: https://wordpress.com/post/example.wordpress.com
2. Click the Add Media button
3. Select an image, click Edit, then Edit Image

#### What I expected
To be able to edit images

#### What happened instead
The first image I selected opened as just a blank screen.  The second image opened fine, but then subsequent images were all opening the second image again, or else showing a blank screen.  There are a lot of errors in the console about file access problems:

```js
SEC7120: Origin https://wpcalypso.wordpress.com not found in Access-Control-Allow-Origin header.
hd83newsite.wordpress.com
SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, Could not complete the operation due to error 80700013.
hd83newsite.wordpress.com
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - https://widgets.wp.com/client/boot/stylesheets/style.scss
--- REPEATED for many SCSS files---
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - https://widgets.wp.com/client/suggestions/styles.scss
SEC7120: Origin https://wpcalypso.wordpress.com not found in Access-Control-Allow-Origin header.
hd83newsite.wordpress.com
SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, Could not complete the operation due to error 80700013.
hd83newsite.wordpress.com
SEC7120: Origin https://wpcalypso.wordpress.com not found in Access-Control-Allow-Origin header.
hd83newsite.wordpress.com
SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, Could not complete the operation due to error 80700013.
hd83newsite.wordpress.com
```

#### Browser / OS version
Windows 10 - both via BrowserStack and a local VM
Microsoft Edge 25.10586.0.0
Microsoft EdgeHTML 13.10586

#### Screenshot / Video
![wp-calypso-image-editor-edge](https://cloud.githubusercontent.com/assets/7233112/18398028/cc094a34-7698-11e6-9f0f-a211c2e859f2.gif)

#### Context / Source
#manual-testing

**Comment by gwwar** [comment] 2016-10-25 20:19
@hoverduck retested this against master, and can't reproduce on IE11/Edge. Feel free to reopen if you find otherwise. Most likely this was fixed in previous PR.

**Closed by gwwar** 2016-10-25 20:19 UTC
Labels: Media, [Type] Bug
