### ISSUE TITLE
Plans: Icon colors are incorrect

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#33042] opened 2019-05-14 20:29 UTC
#### Steps to reproduce
1. Starting at URL: `/plans/my-plan/[site]` (Plan should be higher than Free)
2. Check the cards containing features

#### What I expected
That the icons use our current colors.

#### What happened instead
The icons have green in them which I think is for Jetpack.

#### Browser / OS version
Chrome Version 74.0.3729.131 (Official Build) (64-bit)
Mac OS Mojave 10.14.2

#### Screenshot / Video
![Screenshot 2019-05-14 13 28 05](https://user-images.githubusercontent.com/4924246/57729905-1dbc9100-764c-11e9-8427-89e2706f5cc5.png)

**Comment by alaczek** [comment] 2019-05-14 22:04
I'm gonna close this as a duplicate of #32522

**Closed by alaczek** 2019-05-14 22:04 UTC
Labels: FixTheFlows, Plans, [Type] Bug
