### ISSUE TITLE
Tazza Theme - Overlay menu does not work in Safari or Firefox when the Gutenberg plugin is active

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#78552] opened 2023-06-22 21:13 UTC
### Quick summary

When the WordPress.com Gutenberg plugin is active on a site with the Tazza theme, the overlay menu does not open or respond to interaction in the Safari browser.

### Steps to reproduce

1. Start a WordPress.com site and install the Tazza theme.
2. Transfer the site to the Atomic platform.
3. Open the site in a Safari or Firefox browser with a context where the overlay menu will appear.
4. Observe that interacting with the hamburger icon does not open the overlay menu.

### What you expected to happen

The overlay menu should open in the Safari and Firefox browser.

### What actually happened

The overlay menu does not open in the Safari or Firefox browser.

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Safari and Firefox browsers

**Comment by cuemarie** [comment] 2023-06-22 22:38
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic –  **Could Not Replicate** 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Unable to reproduce on 2 different Atomic test sites using Tazza - tested both with Firefox 114.0.2 and Safari 16.5 (18615.2.9.11.4)

#### Screenshots/Recordings

**Tazza theme in Safari 16.5**

![a5yCPH.gif](https://github.com/Automattic/wp-calypso/assets/27249804/d0f0f0ff-f148-485f-bbae-62c8230971f8)

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- @masperber Anything I'm missing from my tests of this?  If this was from an interaction with a user, was a plugin conflict test run as well? Thanks for your insight?

**Comment by masperber** [comment] 2023-06-22 23:22
@cuemarie This was a customer report: 6456606-zen

During the interaction, I did run a plugin conflict test. Only deactivating the Gutenberg plugin allowed the overlay menu to be opened in the Safari and Firefox browsers.

In response to your findings, I activated the Tazza theme on my test site. I activated all of the same plugins, the same PHP version, and I duplicated all of the blocks from their Home template over to my test site. However, I have not been able to reproduce the bug on my test site.

The customer has deactivated the overlay menu as a workaround to the bug for the time being, but take a look and let me know if you can identify any other possible causes.

**Comment by cuemarie** [comment] 2023-06-23 01:38
@masperber I gave the customer's site a look, and can recreate the problem on their site (overlay menu not opening in Safari), but even with all the same plugins installed on a test site, as well as the same font and copied block content from their header, I can't replicate the problem. 

I think for now, that's enough to determine that this is not likely a conflict between Gutenberg and Tazza.  

Next, I might see if they're willing to (or try with their permission doing so from our side) setting up a new navigation block on a test page and seeing if the same problem happens there - could be something odd with the particular menu in place now, that perhaps rebuilding would help resolve?

📌 ACTIONS
- Closed as not reproducible (feel free to reopen if you find anything that points to a bug!)

**Closed as not planned by cuemarie** 2023-06-23 01:38 UTC
Labels: Bug, [Pri] Normal, [Closed] Not Reproducible, [Platform] Atomic
