### ISSUE TITLE
FSE: Styling Fixes with Gutenberg v6.4

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35848] opened 2019-08-28 18:42 UTC
When editing a Header or Footer, it looks like the min-height has changed for the wp_template.

Expected:
<img width="1135" alt="Screen Shot 2019-08-28 at 11 42 48 AM" src="https://user-images.githubusercontent.com/1270189/63883457-1b770c00-c989-11e9-943a-1748c42e2572.png">

Actual:
<img width="1128" alt="Screen Shot 2019-08-28 at 11 35 46 AM" src="https://user-images.githubusercontent.com/1270189/63883466-1f0a9300-c989-11e9-96d0-d439d993ae68.png">

To Reproduce:
- Visit horizon.wordpress.com/start/test-fse and create a new user
- Edit a page
- Click on edit header
- Compare page editing results with horizon.wordpress.com and wordpress.com

**Comment by jasmussen** [comment] 2019-08-29 06:57
It is my sense, the vh unit is mostly decorative for the reading experience. But only Ella can speak on that topic with authority, and I defer to her.

However if the typewriter experience works as intended with a px unit and that makes life easier for you folks, I think it could be worth a core PR to change that. By "works as intended", I mean:

- When you type on an empty canvas, you type normally until you're at about 75% of the editing viewport height, at which point the Typewriter effect kicks in and keeps the caret at that spot.
- If you have a very long document already, and set focus near the top of the screen, the caret is also kept in place there at the top.

**Comment by shaunandrews** [comment] 2019-08-29 13:12
Hmmm. This does break the encapsulated feeling we had previously where it felt like you were editing _just_ the header. With the expanded canvas, I worry people might get confused and think they’re editing a whole page and start adding more and more blocks (since there’s room for them) and mess up their header.

I’d prefer we get back to what we had previously.

**Comment by gwwar** [comment] 2019-08-29 19:07
@kwight do things mostly work okay if we update styling when editing a wp_template? I believe we should add some parent CSS classes to help detect that.

**Comment by kwight** [comment] 2019-08-29 21:52
I don't think we need to update core, it's our particular use-case that benefits from the change back to `px` (and it's just the visual that's affected, behaviour seems the same, as far as I can tell). I can do up an FSE PR to override back to `px`.

**Comment by kwight** [comment] 2019-08-30 16:32
This was addressed by @Copons in #35821 .

**Closed by kwight** 2019-08-30 16:32 UTC
Labels: [Goal] Full Site Editing, [Type] Bug

**Comment by Copons** [comment] 2019-08-30 16:46
Sorry for not noticing this issue earlier! 😢
