### ISSUE TITLE
Website Meta Enabled on a site with a Free Plan

### ISSUE THREAD

**Issue by nellofn** [Automattic/wp-calypso#17554] opened 2017-08-26 19:11 UTC
#### Steps to reproduce
1. Starting at URL: http://multiversocomics.wordpress.com
2. Login as the user
3. Go to Settings > Traffic
4. Website Meta it's enabled on a free plan

#### What I expected
Website Meta shouldn't be enabled.

#### What happened instead
Website Meta it's enabled and the prompt to Upgrade to SEO with Business it's enabled as well. Clicking on "Show Previews" also prompts to update to Business.

#### Screenshot
![planbug-seo](https://user-images.githubusercontent.com/17755234/29744314-b07ac62a-8a70-11e7-8b15-68e61a2f6dc3.png)

#### Context / Source

I've found the bug when a user sent a ticket asking why a site with a Personal plan doesn't have Website Meta, while this one under a Free plan does. Ticket: 648265-zen

#seo #plans

**Comment by rachelmcr** [comment] 2017-08-28 11:16
I checked several test sites on the free plan and confirmed that in most cases the Website Meta section does not appear. It only appeared on a test site where I had set a custom meta description before the change in https://github.com/Automattic/wp-calypso/issues/7560 which restricted Website Meta to the business plan.

This looks like expected behavior, effectively granting someone access to the Website Meta section as long as they already had used it. Once I removed the meta description from that free test site, the section disappeared as expected behind the SEO upgrade nudge.

I'm closing this as it seems like expected behavior in this case. Please comment/reopen if you think this needs further investigation.

**Closed by rachelmcr** 2017-08-28 11:16 UTC
Labels: Plans, Site Settings, [Type] Bug
