### ISSUE TITLE
FSE: Featured Image option isn't available for sites that doesn't have FSE on

### ISSUE THREAD

**Issue by catkit** [Automattic/wp-calypso#36573] opened 2019-10-07 18:07 UTC
#### Steps to reproduce
1. Activate Maywood at an existent site
2. Create a new page
3. Try to add a featured image

#### What I expected
The Featured Image option would be available for existent sites that don't have FSE as an option and aren't part of the AB test.

#### What happened instead
The Featured Image option is missing from all sites.

#### Screenshot / Video
![featured-image-missing](https://user-images.githubusercontent.com/3521683/66336725-05f3eb00-e914-11e9-9188-96091f8fcebe.jpeg)

#### Context / Source
#user-report

**Comment by catkit** [comment] 2019-10-07 19:31
Followup ticket: #2404797-zen

**Comment by noahtallen** [comment] 2019-10-08 05:40
At first look, it seems our code for removing this is not the culprit. I may be wrong, but we might need to look in more places - maybe a Gutenberg update?

**Comment by noahtallen** [comment] 2019-10-09 19:00
@catKit It turns out that this is not a bug. Individual themes include featured image support - so twenty nineteen and child themes like modern buisness included support for featured images, but other themes may not include featured image support. Our new template-first themes (like maywood and others) do not include support for featured images, so the workaround would be to add a full-width image at the top of the post in Gutenberg.

For reasoning, the idea with the new themes is removing customization that happens behind the scenes in the theme, and instead moving all that power to Gutenberg. Since a featured image is just a large image at the top of a post, that can easily be replicated in Gutenberg. There is some other stuff - like social sharing images - which use the featured image. If I recall, something like the social share image is supposed to pull the top image from the post if no featured image exists :)

**Comment by liviopv** [comment] 2019-10-10 08:35
> There is some other stuff - like social sharing images - which use the featured image. If I recall, something like the social share image is supposed to pull the top image from the post if no featured image exists :)

@noahtallen not really, afaik, it's generally random. You can see that for yourself by [running Maywood's demo site through the Facebook Debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fmaywooddemo.wordpress.com)

As you can see, Facebook skips the cover image at the top, and [picks up this image](https://maywooddemo.files.wordpress.com/2019/08/chef-cook-cooked-1327215.jpg?w=1526) instead, which is the third image on the site overall.

**Comment by liviopv** [comment] 2019-10-10 09:07
I pushed this to Varia's repo https://github.com/Automattic/themes/issues/1461#issuecomment-540475196 because it makes more sense there.

Closing this again

**Closed by liviopv** 2019-10-10 09:07 UTC
Labels: ABTest, [Goal] Full Site Editing, [Pri] High, [Type] Bug

**Comment by noahtallen** [comment] 2019-10-10 17:26
Wonderful, thanks for the detailed followup!
