### ISSUE TITLE
iOS WordPress.com app: Image and gallery blocks not loading after edits in web app

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#65478] opened 2022-07-12 07:50 UTC
### Quick summary

Our user reported that Image and Gallery Blocks are not loading in the iOS WordPress.com apps after the posts containing these blocks are edited in the web app at https://wordpress.com

Once the post is edited in the web app, Image and Gallery Blocks render like this:

![IMG_7139](https://user-images.githubusercontent.com/2912202/178436638-bc6a09c8-c0a0-441f-b4e2-2ff225cf67d1.jpeg)

### Steps to reproduce

We received the following steps to reproduce from our user:

1. Create a new article on the iOS tablet application
2. Add an image
3. Save the draft and close the article
4. Open the draft article using the chrome wordPress web application
5. Add a caption to the Image
6. Save the article and close the Chrome WordPress web application
7. Open the article on the iOS tablet application
8. The issue is reproduced

### What you expected to happen

Image and Gallery Blocks should render as expected on all supported devices, even if editing the posts and pages containing these blocks on different platforms.

This is what the user's test post looked like in the editor in the web app:

![IMG_7135](https://user-images.githubusercontent.com/2912202/178437640-8e84fc44-36f0-4ee7-8900-3d3b8ca7b1de.jpeg)

### What actually happened

Editing these blocks in the web app seems to add a `wp-element-caption` class to `figcaption`. This addition correlates with the block failing to load correctly in the iOS app.

### Context

User report in 5357967-zen

- [ ] Please update the user when this issue is resolved

When the post is first created in the iOS app, the underlying code looks like this:

![IMG_7134](https://user-images.githubusercontent.com/2912202/178437413-20503744-0375-4e93-837f-6b75650bcdf4.jpeg)

Note that there is no class applied to the `figcaption` element. Here is the link to the unpublished post: 2cdf6-pb/

### Theme-specific issue?

This is not established.

### Browser, operating system and other notes

WordPress app Version 20.1
IPadOS Version 15.5
IPadOS chrome version 103.0.5060.63

### Reproducibility

Consistent

### Available workarounds?

No but the platform is still usable

### Workaround details

The user could limit themselves to the web app for posts with images and galleries although this issue means they can not use the iOS apps to edit their content if they have touched them with another platform editor.

**Comment by Robertght** [comment] 2022-07-14 05:25
- [ ] 5366775-zen

**Comment by Robertght** [comment] 2022-07-18 08:29
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes/No

📌 SCRUBBING
- Tested on P2 - no
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ but I couldn't replicate this so it might be .com specific only.

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate the issue last week, but I do not know where to flag this forward. I'm checking here p1658132599176889-slack-C03URUK5C

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cuemarie** [comment] 2023-10-05 23:22
Was not able to reproduce today following the steps above.  The WPcom app rendered the image block as expected after I edited the draft post in Chrome and then returned to it in the app:

<img width="400" alt="screenshot" src="https://github.com/Automattic/wp-calypso/assets/27249804/67d5bdac-99af-4ef6-a91b-fcef3a55ad75">

📌 ACTIONS
- Closing as not reproducible (anymore)
- If anyone can reproduce, feel free to reopen and add a comment with your findings. Thanks!

**Closed as completed by cuemarie** 2023-10-05 23:22 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] Normal, User Waiting, Block Rendering, Triaged, iOS, Mobile Application, Customer report [LEGACY], [Product] WordPress.com, [Feature Group] Editor Experience
