### ISSUE TITLE
Settings panel closes after typing a single character while trying to edit Navigation menu items

### ISSUE THREAD

**Issue by mgozdis** [Automattic/wp-calypso#85235] opened 2023-12-13 16:45 UTC
### Quick summary

When trying to edit navigation menu items such as the label or link, the settings panel immediately closes as soon as typing a single character. User are reporting this did not happen until 2-3 days ago and appears related to a recent update. 

Video
https://github.com/Automattic/wp-calypso/assets/121042930/8e04a52c-4db2-4e04-b5f3-bbd896814bf0

User report: 7446489-zd-a8c

### Steps to reproduce

1. Attempt to edit Navigation under Appearance > Editor > Navigation and select a menu to edit.
2. Open the list view, select a menu item, and try to change the label or URL text - see that the settings panel closes as soon as typing a single character. 

Trying to edit the link text directly also produces a similar result. 

### What you expected to happen

You should be able to edit the settings without the panel closing automatically after typing a single character. 

### What actually happened

The settings panel closes automatically as soon as typing a single character. 

### Impact

Most (> 50%)

### Available workarounds?

Select the menu item in the Editor Canvas *before* toggling the List View.
### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

This was reproduced on a test AT site and unknown if affecting Simple sites at this time.

**Comment by liviopv** [comment] 2023-12-20 11:01
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated / Could Not Replicate / Uncertain
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
Atomic, GB 17.2.3
https://github.com/Automattic/wp-calypso/assets/14153300/a8c3769e-ab7f-4dea-96a8-ec38b67d7e34

Steps to repro:
1. Navigate to Appearance > Editor > Navigation
2. Select a menu to edit
3. Important: toggle List View *before* any other action in the editor canvas
4. Select a menu item to edit
5. The Block Inspector sidebar will glitch as if no block is selected
 

📌 ACTIONS
- Triaged

📌 Message to Author
@mgozdis good catch. A workaround is performing any action on the editor canvas like clicking on one of the menu items to select it *before* toggling List View. In that state, I was not able to reproduce any issues, so I lowered the priority to High.

**Comment by mpkelly** [comment] 2024-04-19 07:13
I tried to reproduce this but couldn't. Could you retest @mgozdis and consider closing it down if it is fixed.

**Comment by mgozdis** [comment] 2024-04-19 18:07
@mpkelly Seems to have been fixed as I can no longer reproduce. Thanks!

**Closed as completed** 2024-04-19 18:07 UTC
Labels: Bug, [Pri] High, Navigation, Triaged, [Feature] Full Site Editor, Customer report [LEGACY], [Platform] Atomic, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience
