### ISSUE TITLE
People: Invalid prop-type console warnings

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#20222] opened 2017-11-25 15:51 UTC
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/people/team/:site?s=:searchTerm (use e.g. your name as a search term — it has to return results to reveal both warnings).
1. See dev console for errors:
    > Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `Search`.

    > Failed prop type: Invalid prop `label` of type `array` supplied to `PeopleListSectionHeader`, expected `string`.

#### What I expected

☀️ 🌷 🌷 

#### What happened instead

![image](https://user-images.githubusercontent.com/87168/33232066-4994bddc-d208-11e7-9300-17530c88daf4.png)

The point for the 2nd error seems to be [here in client/my-sites/people/team-list/team.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/people/team-list/team.jsx#L99)

#### Browser / OS version

Chrome 62 / MacOS High Sierra

**Comment by mattsherman** [comment] 2018-03-08 16:11
I am unable to reproduce this anymore. Closing. Please reopen if you are able to reproduce.

**Closed by mattsherman** 2018-03-08 16:11 UTC
Labels: OSS Citizen, People Management, [Type] Bug
