### ISSUE TITLE
Domains: Adding a domain/subdomain doesn't set it to Primary on Atomic sites

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#50050] opened 2021-02-12 17:54 UTC
### Steps to reproduce the behavior

1. Add a domain or subdomain on Atomic site and complete the checkout
2. Navigate to WordPress.com > My Sites > Manage > Domains

#### What I expected to happen
Registered or mapped domain/subdomain set as Primary after being added, just as it is the case on Simple sites
#### What actually happened
The newly added domain is not set as Primary (requiring an extra step from the user which may not be obvious)
### Context
I was adding a mapped subdomain on a series of sites in a row and noticed that on all Simple sites, the newly added subdomain is set as Primary after the Checkout, but on Atomic site that doesn't happen.
#### Browser / OS version
Any
#### Is this specific to the applied theme? Which one?
No
#### Does this happen on simple or atomic sites or both?
Atomic
#### Is there any console output or error text?
No
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Low
#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![](https://d.pr/i/hLssFs+)
_Link: https://d.pr/i/hLssFs_

**Comment by klimeryk** [comment] 2021-02-16 22:13
Thanks for flagging this, @zdenys! Looks like I missed this case when I overhauled this job recently 🙇 I've prepared a patch to address this issue on the backend: D57165-code. cc @aidvu, would love your review there to make sure there's nothing else with Atomic I missed 🙏

**Comment by klimeryk** [comment] 2021-03-01 11:39
Backend patch merged - now `*.wpcomstaging.com` subdomains will be treated like free WPCOM subdomains, meaning a new custom domain will be able to override them automatically as a primary domain 🎉 
Please let me know if you encounter any new instances of this issue (or notice any regressions) 🙇

**Closed as completed by klimeryk** 2021-03-01 11:39 UTC
Labels: Bug, [Feature Group] Emails & Domains
