### ISSUE TITLE
Editor: Dropping an image into the editor breaks on reload of the image

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#433] opened 2015-11-22 16:17 UTC
When I drop an image directly into the editor, on reload it fails and shows a broken image. Example here on my personal blog:

![image-drop](https://cloud.githubusercontent.com/assets/1464705/11324789/1aa0a888-90f1-11e5-8c1e-4bfd170b31c4.gif)

The image upload does work, it is shown in the media library when I open it, and I can insert it from that point just fine. It seems to be an issue exclusively for reloading an image. Tested and happening in the desktop app v0.25.0, and in Chrome 40.0.2.

**Comment by designsimply** [comment] 2015-11-30 07:09
@apeatling, could the problem be with the image itself in this case? If you try uploading an image that is known to have worked in the past on the same blog, does the problem still happen?

<blockquote>Tested and happening in the desktop app v0.25.0, and in Chrome 40.0.2.</blockquote>

Chrome 40 was released in Jan 2015, is that version number correct?

**Comment by apeatling** [comment] 2015-11-30 17:54
@aduth: I think it is a permissions issue with the file. It is returning a 404 for any image I upload. This is probably why it is working on my Jetpack site since the permissions there are okay:

![screen shot 2015-11-30 at 9 53 12 am](https://cloud.githubusercontent.com/assets/1464705/11479719/4f5c3a58-9748-11e5-9fd4-2235a7a96f03.png)

@designsimply This happens for any image, Chrome 46.

**Comment by designsimply** [comment] 2016-02-03 20:12
I've been running into this a lot lately. Once the image uploads, it appears as a broken after it loads but I can still click on it and use the resize options. Right now, it happens consistently for every single image I upload. Here's a video: https://cloudup.com/c_nHnzNjWNr

Console error:

```
Failed to load resource: the server responded with a status of 404 (OK)
https://cute.files.wordpress.com/2016/02/img_7712.jpg?w=2720 
```

<img width="1280" alt="screen shot 2016-02-03 at wed feb 3 11 44 43 am" src="https://cloud.githubusercontent.com/assets/1119271/12795496/4956080a-ca6f-11e5-9f4b-f62612905bba.png">
<sup>Seen at https://wordpress.com/post/cute.wordpress.com/8484 in production using Chrome 47.0.2526.111 on Mac OS X 10.10.5</sup>

**Comment by aduth** [comment] 2016-02-03 20:38
>I've been running into this a lot lately.

Do you encounter a 404 when navigating to the broken URL directly? Wondering if there's some network connectivity issues at play.

**Comment by apeatling** [comment] 2016-02-04 00:29
Definitely wasn't a network issue for me.

**Comment by designsimply** [comment] 2016-02-18 08:21
> Do you encounter a 404 when navigating to the broken URL directly? Wondering if there's some network connectivity issues at play.

I don't see a 404 when navigating to the broken URL directly. The image loads fine in preview and when viewing the source in developer tools too. It also seems to load just fine if I do a hard refresh on the editor page itself. It only looks broken after the initial image refresh when the resized image loads. Even though I have been traveling a lot lately, I don't think it's a network connectivity issue because I'm able to browse and publish and do everything else normally without interruption or any warning messages about connectivity.

Console error:

```
Failed to load resource: the server responded with a status of 404 (OK)
https://cute.files.wordpress.com/2016/02/img_8313.jpg?w=2448 
```

<img width="1280" alt="screen shot 2016-02-18 at thu feb 18 9 09 36 pm" src="https://cloud.githubusercontent.com/assets/1119271/13137370/736badee-d685-11e5-8abb-d4f711c55ad2.png">

**Comment by designsimply** [comment] 2017-12-20 23:57
Closing due to inactivity and because I was unable to reproduce the same problem in testing. Please re-open if it comes up again or is still a problem in your case!

Re-tested with Safari 11.0.1 on macOS 10.13.2 and found that I did have to make a change other than adding an image only to the main content area and once I did that an autosave was triggered and I could refresh the page and the image did not appear broken.

**Closed by designsimply** 2017-12-20 23:57 UTC
Labels: Editor, Media, [Type] Bug
