### ISSUE TITLE
Jetpack: Upgrade nudge in sidebar broken

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#22700] opened 2018-02-22 12:10 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/plans/{site-url}
2. Make sure you're on the free JP plan
3. Click the "Upgrade for full site backups" nudge

<img width="314" alt="richard_s_sandbox_ _wordpress_com" src="https://user-images.githubusercontent.com/2287740/36537868-538286b0-17c9-11e8-8bcc-c6de5db854ca.png">

#### What I expected
To be taken to an upgrade flow.

#### What happened instead
Nothing.

**Comment by keoshi** [comment] 2018-03-01 17:43
Ideally we would redirect the user to this last step on the fullscreen start flow — https://wordpress.com/start/plans —, but with Jetpack specifics. Here's a quick mock:

![image](https://user-images.githubusercontent.com/390760/36859988-0d5fb360-1d78-11e8-8aab-a16d74e4dfdf.png)

**Comment by richardmuscat** [comment] 2018-03-07 10:24
@jaswrks, @jeffgolenski and @keoshi I just realised that this issue as I stated it is a bit of a red herring. 

It _does_ work as expected in most cases (ie: clicking GO takes you to the plans page) but I happen to have viewed and clicked it when I was _already_ on the plans page so it looked like nothing was happening. 

Perhaps the answer is to hide it when already on the plans page? Or else just accept that this is how the nudge currently works.

**Comment by keoshi** [comment] 2018-03-07 11:44
@richardmuscat I noticed that too — maybe the MVP would be to hide the nudge when viewing the plans page (though not ideal), and later we give it a bit more though? I tested this and saw the same as you, but jumped the gun when triaging last week and did a mock anyway. :)

The bottom line is that this is really a non-issue:

- If you see the nudge when not in the plans page: you get redirected.
- After said redirection: the user already knows where the link takes them, so it's no surprise to not have anything happen if on the plans page.
- The most concerning scenario is if you're *already* on the plans page and click the nudge then, expecting something to pop up or get redirected. In this case, can we flash the plans for a second or something visually indicative yet subtle?

**Comment by richardmuscat** [comment] 2018-03-07 11:56
Agree it's a non-issue at this stage. As you say scenario #3 is the only
one of concern (although mild IMO) and doing something subtle might not
actually make it any clearer tbh.

**Comment by keoshi** [comment] 2018-03-07 12:13
Agreed — I think we need more time on this one but not super urgent for right now. Let me know if you want to keep this open/move it to the backlog of fixtheflows/close it.

**Comment by jaswrks** [comment] 2018-03-07 12:20
> The most concerning scenario is if you're already on the plans page and click the nudge then, expecting something to pop up or get redirected. In this case, can we flash the plans for a second or something visually indicative yet subtle?

I like the flash (psuedo-refresh) idea.

**Comment by keoshi** [comment] 2018-03-07 12:38
I just threw that out there, but if more people like the idea let's do it! I do have some concerns about accessibility but it's better than what we have, and we could use it in more places: https://github.com/Automattic/wp-calypso/issues/21610

**Comment by keoshi** [comment] 2018-03-08 10:07
@johnHackworth assigned you to this one to evaluate if this is easily doable in the timeframe we have, or if we should backlog it?

**Comment by jaswrks** [comment] 2018-03-08 20:24
@johnHackworth Hi! :) I had already started giving the pseudo-refresh idea some attention. I went ahead and submitted a PR for your review: https://github.com/Automattic/wp-calypso/pull/23144

**Comment by rachelmcr** [comment] 2018-08-29 14:13
I tested this and confirmed it still works as described above — the upgrade nudge appears on the Plans page, although it doesn't do anything (since you're already on the Plans page).

It's worth noting that the behavior of this nudge is the same for WordPress.com and Jetpack sites; the main difference is the text: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/current-site/domain-to-paid-plan-notice.jsx#L44

The fix suggested in https://github.com/Automattic/wp-calypso/pull/23144#issuecomment-382075080 (hide the banner on the plans page) seems like a simple and effective solution for this.

**Comment by keoshi** [comment] 2021-03-01 17:45
This upgrade notice is no longer visible, closing the issue.

**Closed by keoshi** 2021-03-01 17:45 UTC
Labels: FixTheFlows, Jetpack, Plans, [Type] Bug
