### ISSUE TITLE
Cant "Move to" block widgets across widget areas

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#62545] opened 2022-04-06 01:47 UTC
### Quick summary

The `Move to` options on the WP-Admin widgets and Customizer widgets screens don't do anything!

### Steps to reproduce

1. Open the WP-Admin Widgets page from /wp-admin/widgets.php
2. Click on any widget, three dots, and select `Move to`

1. Open the Customizer → Widgets → any widget area → any existing widget.
2. Click on the three dots on any widget, and click on `Move to`

### What you expected to happen

The `Move to` option should open other available widget areas to move the widget to.

### What actually happened

Nothing happens when I click on `Move to`. It is totally unresponsive.

### Context

User report in 19460407-hc followed up in 4924856-zen

### Available workarounds?

Yes, easy to implement

### Workaround details

In the WP-Admin Widgets screen, we can drag-drop the widgets as shown in this video:  

https://user-images.githubusercontent.com/1519466/161879205-af03a803-f98c-4037-934d-d39a618b4404.mp4

**Comment by happychait** [comment] 2022-04-06 03:26
I tested a bit more with an Atomic site, and found the `Move to` doesn't work on the WP-Admin Widgets screen.

But in the customer, `Move to` menu option is unresponsive and does nothing, but the `Move to widget area` icon on the widget toolbar works as in this screenshot: 
![Atomic Move to](https://user-images.githubusercontent.com/1519466/161889812-423d77c5-839f-4cbc-9dcf-62e1e41753f2.png)

**Comment by vajrasar** [comment] 2022-04-16 20:11
Thanks @happychait for the details bug report and the comments.

I checked and on the AT site - I was able to replicate all the parts of the issue ("Move To" not working either on wp-admin widgets section and also not on the Customizer section, whereas the "Move to icon" works in the customizer and wp-admin widgets section as expected).

However, on the Simple site, the issue (as above) persists, and the only change is that you cannot find the "Move To" option on the widget by clicking on three-dots. Only the "Move to icon" is shown on the customizer at least. 

Still, the issues can be replicated.

**Comment by xpurichan** [comment] 2022-07-18 21:00
Encountered on a Team 51 partner's website (Awesome.blog).

**Comment by sejas** [comment] 2022-07-21 14:38
In my opinion, this is a bad Gutenberg UX, not a bug.

In our documentation, we explain that the button to move the widget is this one: 
<img width="41" alt="Screenshot 2022-07-21 at 15 33 53" src="https://user-images.githubusercontent.com/779993/180240474-5c674f12-e086-49a4-83c3-c7c343363547.png">

https://wordpress.com/support/widgets/#move-blocks-between-widget-areas

The decribed behaviour of `move to` is the same in a core website and also for blocks inside posts and pages. It only toggles the "view" from the Edit to the Select, so the user can drag and drop the block to another place.
IMO, It shouldn't show the dropdown with the widget areas.

It has been reported here: https://github.com/WordPress/gutenberg/issues/35262

@happychait, what do you think?

**Comment by sejas** [comment] 2022-09-16 11:52
I'm unassigning this issue since I'll be AFK for 2 weeks.
The best solution for this issue would be to remove, on Gutenberg core, the `move to` button from the components when we are on the widgets page:

Here is the component `move to`:
https://github.dev/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-settings-menu/block-settings-dropdown.js#L280

p1659026074019309-slack-C0347E545HR

**Comment by mpkelly** [comment] 2022-09-29 01:25
I also had a quick look at this. I found that using `Move to` via the ellipsis menu does actually work but only if you use the arrow keys to move focus and then press `Enter` to move the selected block to its new location. You can see that here:

https://user-images.githubusercontent.com/6851384/192916487-50b91240-5539-4871-a2e2-e9aa64a41b8d.mov

This is obviously not very clear and there should be some hints for the user. A keyboard shortcut for `Move to` would also be great, so you can initiate and complete the action entirely using the keyboard. 

I checked the [Gutenberg core repo](https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+is%3Aopen+%22move+to%22) but there doesn't appear to be an open issue there. I think this ticket should be moved to there and raised as a UX issue as per @sejas's comment. Although, FYI I wasn't able to get drag working after selecting `Move to`, so maybe that is an actual bug.

@happychait

**Comment by danielbachhuber** [comment] 2022-11-17 23:05
@mpkelly Want to create a detailed Gutenberg issue, and we can close this in favor of that one?

**Comment by cuemarie** [comment] 2023-04-12 23:26
It appears this has been resolved by https://github.com/WordPress/gutenberg/issues/48113

Tested AT site with theme **Twenty Twenty One**, **Twenty Seventeen**
- wpadmin widgets `Move To` button works on block widgets
- Customize widgets  `Move To` button works on block widgets

Tested Simple site with theme **Twenty Seventeen**
- wpadmin widgets `Move To` button works on block widgets
- Customize widgets  `Move To` button works on block widgets

**Closed as completed by cuemarie** 2023-04-12 23:26 UTC
Labels: Bug, [Pri] Normal, Block Widgets, Legacy Widgets, Build Maintenance
