### ISSUE TITLE
Site Profiler is not identifying the host of the domain spendbase.co

### ISSUE THREAD

**Issue by renatho** [Automattic/wp-calypso#91719] opened 2024-06-12 14:50 UTC
### Quick summary

When navigating through the migration flow, after informing the site to migrate from, the user should see this step informing their current host.

### Steps to reproduce

1. Start a migration flow.
2. Inform the site `spendbase.co` in the step "Let's find your site".
3. Continue to the step "What do you want to do?".

Or you can directly navigate to https://public-api.wordpress.com/wpcom/v2/site-profiler/hosting-provider/www.spendbase.co

### What you expected to happen

It should identify the site host. Example of a domain with the identified host (Amazon):

<img width="619" alt="Screenshot 2024-06-12 at 11 39 36" src="https://github.com/Automattic/wp-calypso/assets/876340/669bf5bc-ea2b-4329-bd98-8202353ffa60">

### What actually happened

The host was not identified.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

It needs confirmation, but it seems the mentioned host is GoDaddy (through WildWestDomains). See the [who.is](https://who.is/whois/spendbase.co), and [an old forum thread talking about the identified nameserver](https://forumweb.hosting/14393-what-is-domaincontrol-com.html).

More context:

- p1718102446090559-slack-C02NWDZBL0H
- p1718200361284699-slack-C02T4NVL4JJ

**Comment by liviopv** [comment] 2024-06-13 09:33
📌 REPRODUCTION RESULTS
- Tested – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

Site Profiler:
![CleanShot 2024-06-13 at 10 26 51@2x](https://github.com/Automattic/wp-calypso/assets/14153300/01aa4c94-0a6a-4468-98bc-9dbc773a87f2)

Who Hosts This?
![CleanShot 2024-06-13 at 10 27 29@2x](https://github.com/Automattic/wp-calypso/assets/14153300/5a7dee05-26cd-4a04-b09b-e9359215ab19)

@renatho I think it's just a matter of Site Profiler not having information about which host users the IP for the A Records, because external tools point it to https://www.hosteurope.de/en/ as the host.

📌 ACTIONS
- Triaged

@Automattic/bespin I understand the work on the Site Profiler has stopped, but I thought it would be good flag this in case it's a quick fix.

**Comment by gavande1** [comment] 2024-06-13 09:48
Thanks for the report, @renatho and @liviopv, for the ping. 

> I think it's just a matter of Site Profiler not having information about which host users the IP for the A Records

Correct: We need the information to identify the hosting provider for the hosts accurately. We have the internal mapping for some of the well-known hosts, but this mapping is only sometimes up to date.
 
Here, in the case of `spendbase.co` directed to IP `92.205.170.149` with an ASN of `21499`, it belongs to Host Europe GmbH. However, we need this mapping in the backend to identify the host.

**Comment by gavande1** [comment] 2024-06-13 10:06
Created quick fix: D152056-code

**Comment by liviopv** [comment] 2024-06-13 10:20
@gavande1 Thanks! 
Can we close this or do you still need it open?

**Comment by gavande1** [comment] 2024-06-13 10:26
I just deployed this on production in r297324-wpcom. Now, you can close the issue.

**Closed as completed** 2024-06-13 12:26 UTC
Labels: Bug, [Pri] Low, Triaged, [Status] Priority Review Triggered, [Feature] Site Profiler

**Comment by renatho** [comment] 2024-06-13 13:28
Thank you for the quick fix, folks! ♥️
