### ISSUE TITLE
Links to the Support pages for information on the Advanced Dashboard pages are broken for languages other than EN. 

### ISSUE THREAD

**Issue by automattic-ian** [Automattic/wp-calypso#51182] opened 2021-03-18 13:09 UTC
### Steps to reproduce the behavior

1. Go to https://wordpress.com/me/account
2. in any non english language
3. right click on the learn more link about advanced dashboard pages and open in new tab. 
4. see 404 page in support docs. ex https://wordpress.com/de/support/account-settings/#dashboard-appearance

#### What I expected to happen
same as a regular click, I expected a page to load with the relevant info. 

#### What actually happened
the correct support page doesn't load. 
#### Is this specific to the applied theme? Which one?
theme agnostic
#### Does this happen on simple or atomic sites or both?
both
#### Is there any console output or error text?
n/a
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
affects multiple sites.

**Comment by mmtr** [comment] 2021-03-22 13:58
Thanks for reporting this, @automattic-ian! This is the expected behavior at the moment, since the account settings support article has not been translated yet to other languages.

Note that the page is not actually a 404 page, we display info at the beginning saying to the user that the page can be seen in English or translated with Google Translate:

> Dieser Inhalt wurde noch nicht auf Deutsch übersetzt. Du kannst die [Originalversion auf Englisch](http://en.support.wordpress.com/account-settings) lesen oder die Seite mithilfe von [Google Übersetzer](https://translate.googleusercontent.com/translate_c?act=url&depth=1&ie=UTF8&sl=en&tl=de&u=http%3A%2F%2Fen.support.wordpress.com%2Faccount-settings) in deine Sprache übersetzen lassen.

Going to close this issue for now, since from a technical point of view, there is nothing else we can do.

**Closed as completed by mmtr** 2021-03-22 13:58 UTC
Labels: Bug, Navigation, [Feature] Calypso & wp-admin Navigation
