### ISSUE TITLE
Block Widgets: Widgets not displaying consistently after changing themes

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#53721] opened 2021-06-15 19:11 UTC
### Steps to reproduce the behavior

1. Add widgets to the site using the Apostrophe 2 theme
2. Enable the `enable-widget-block-editor` sticker by toggling it on under “Random toggles” on the respective Blog RC
3. Notice the widgets are displayed in Appearance > Widgets
4. Switch to a different theme, in this case, I switched to Twenty Twenty-One
5. Notice the widgets are gone.
6. Notice you can add widgets but clicking on Update doesn't save the widgets.
7. Notice The previous/missing widgets are still displayed on the site
8. Disable the `enable-widget-block-editor` sticker
9. Notice the widgets are back in Appearance > Widgets

#### What I expected to happen

For widgets to work consistently after changing themes

#### What actually happened

The site started behaving in an odd way while having  `enable-widget-block-editor` sticker. It was working fine right before I switched themes

### Context
Asgard Team Testing p58i-axR-p2

#### Browser / OS version
Google Chrome Version 91.0.4472.101 (Official Build) (x86_64) ​
macOS Big Sur 11.4 (20F71)

#### Is this specific to the applied theme? Which one?
I only tested with the Apostrophe 2 theme

#### Does this happen on simple or atomic sites or both?
Tested on simple site

#### Is there any console output or error text?
Yep:

![Screen Shot 2021-06-15 at 14 09 28](https://user-images.githubusercontent.com/3696121/122109739-5149e680-cde3-11eb-9d2b-35bd9d745d3f.png)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
I don't think this applies since it is an experimental feature

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Haven't tried

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/3696121/122109869-79394a00-cde3-11eb-89cb-b2235723dc4d.mp4

**Comment by Robertght** [comment] 2021-06-30 04:38
I can confirm it's been inconsistent for me as well and sometimes the widgets didn't save at all.

**Comment by AtrumGeost** [comment] 2021-08-02 17:01
Got a similar issue here:

30930960-hc

However, the user **did** change themes yesterday from Adventure to Radiate. They didn't have any conflicting plugins installed.

I suggested the [Classic Widgets plugin](https://wordpress.org/plugins/classic-widgets/) in the meantime

**Comment by mreishus** [comment] 2021-08-03 15:30
I'm having difficulty reproducing this issue. Here are the steps that I've taken and what I saw. Broadly, after I switch to the 2021 theme I'm still seeing my widget content. Additionally, I'm running into some calypso vs. wp-admin differences when compared with the original report, which I will also highlight.

### My Steps Taken
1. Use wordpress.com/new to create a new site; selected blank canvas and free plan.
2. Used the RC to turn on the `enable-widget-block-editor` toggle. 
2. Changed site's theme to Apostrophe 2.
3. Used Calypso's Appearance -> Widgets menu, which brought me to the customizer loaded in calypso.
4. Saw 4 different widget areas listed, chose Primary.
5. Clicked "+" and added a paragraph block, added the text "Block Widget" and saved.
6. Visited home page.
7. Changed theme to TwentyTwentyOne
8. Used Calypso's Appearance -> Widgets menu, which brought me to the customizer loaded in calypso.
9. I was automatically brought to the Primary widget area, where my "Block Widget" text was shown.
10. Visited home page; widget was shown.
11. Manually visited /wp-admin/widgets.php, noted contents, then switched back to Apostrophe 2 and repeated.
In all cases, I'm seeing the widget content and widget menu areas displayed.


![2021-08-03_10-21](https://user-images.githubusercontent.com/937354/128041743-9ea459ab-d64c-40d3-93ab-8c89cf1360ad.png)
^ Apostrophe 2 - Customizer

![2021-08-03_10-22](https://user-images.githubusercontent.com/937354/128041808-6358d6f2-2124-4fed-bb37-3d61c5d60481.png)
^ Apostrophe 2 - Home Page

![2021-08-03_10-22_1](https://user-images.githubusercontent.com/937354/128041864-e25fe955-5532-4a02-84f0-bb407ca59e58.png)
^ Apostrophe 2 - Widgets.php

![2021-08-03_10-22_2](https://user-images.githubusercontent.com/937354/128041979-af9e3517-caba-42f5-8c4e-75febf6bb2b8.png)
^ TwentyTwentyOne - Customizer

![2021-08-03_10-23](https://user-images.githubusercontent.com/937354/128042078-1bf9a31e-8495-43ec-9681-7b621f6e06d6.png)
^ TwentyTwentyOne - Home Page

![2021-08-03_10-24](https://user-images.githubusercontent.com/937354/128042170-40144283-c3b5-4a46-8790-164707b4acb7.png)
^ TwentyTwentyOne - Widgets.php

Everything seems to be there and nothing is lost.

### Calypso vs WP-Admin

When I use the sidebar menu to select Appearance -> Widgets, in both calypso and wp-admin, I am brought to the customizer inside calypso to edit widgets. I know there used to be a setting on https://wordpress.com/me/account to control this, but it seems to be removed in favor of a "Screen Options" tab in the top right of pages that allows you to move between the calypso and wp-admin versions of pages. However, that tab does not appear on the customizer.

So I found no natural way to visit the widget settings in wp-admin. Manually editing URLs was the only way. Visiting /wp-admin/widgets.php showed me ok values (as illustrated in my screenshots above). The video in the original issue shows the url 
/wp-admin/themes.php?page=gutenberg-widgets , however I'm not able to visit that URL. After manually entering it, I'm shown:

![2021-08-03_10-29](https://user-images.githubusercontent.com/937354/128043104-0ae7c82e-f6c7-4b5d-8de9-2fb222591a7e.png)

**Comment by mreishus** [comment] 2021-08-03 15:35
I'm currently unsure how to move forward. I'm wondering if the problem was partially caused by the menu link destinations, and if those have changed for @AtrumGeost since the issue was initially reported?

**Comment by AtrumGeost** [comment] 2021-08-03 20:46
I wasn't able to reproduce the issue anymore :( 

I did the following:
- Created a new site
- Added widgets
- Enable the widget block editor sticker
- Confirmed widgets show at /wp-admin/widgets.php
- Switched themes
- Confirmed widgets at /wp-admin/widgets.php are still showing up 🤔

**Comment by mreishus** [comment] 2021-08-04 18:38
Since neither of us are able to reproduce the issue, I'll close it; we can always re-open if it becomes an issue again.

**Closed as completed by mreishus** 2021-08-04 18:38 UTC
Labels: Bug, [Pri] High, Triaged
