### ISSUE TITLE
Contact Form block: Default behaviour disparity on WordPress.com Simple/Atomic sites

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#47222] opened 2020-11-08 07:57 UTC
On Simple sites (WordPress.com websites without third-party plugins or third-party themes), the Jetpack Form block down not auto-populate the form's `Email address to send to` field and allows the form to be saved without an address being entered.

See:

**Simple site Jetpack Form block default UI**

<img width="1079" alt="Form block email address (Simple)" src="https://user-images.githubusercontent.com/66711744/98459680-04ac8600-21d8-11eb-97ab-8959379bfead.png">

---

**Atomic site Jetpack Form block default UI**
![Form block email address (Atomic)](https://user-images.githubusercontent.com/66711744/98459684-0b3afd80-21d8-11eb-90ad-2875b53be41b.png)

### Steps to reproduce

**Example 1: Simple Site**
1. Starting on any post/page on a Simple site, add a new Form block and select "Contact form".
2. View the default Form block settings - no email address is present. Save.
3. Visit the live/preview version of the page, complete and submit the form.
4. Check: `Site > Feedback` on WordPress.com or `Feedback` in WP Admin to confirm the form has submitted.
5. Repeat from step (2) adding an email address. Form submissions can be found in `Site > Feedback` on WordPress.com, `Feedback` in WP Admin and the mailbox for (2).

**Example 2: Atomic Site**
1. Starting on any post/page on an Atomic site, add a new Form block and select "Contact form".
2. View the default Form block settings - the default email address is present. Save.
3. Visit the live/preview version of the page, complete and submit the form.
4. Check: `Site > Feedback` on WordPress.com, `Feedback` in WP Admin and the mailbox for (2).

#### What I expected
- I expected the site's default email address to be set in the form, regardless of the type of site.
- I didn't expect the form could be saved and be useable without an email address set or at least, to be saved in this state without a large and persistent warning/notification to the end-user.

**Comment by obenland** [comment] 2021-01-29 23:22
This looks to be fixed with https://github.com/Automattic/jetpack/pull/17697, I can't reproduce it on dotcom anymore.

**Closed by obenland** 2021-01-29 23:22 UTC
Labels: Blocks, Jetpack, [Pri] Normal, [Type] Bug
