### ISSUE TITLE
Spotify Block: Embed is too big

### ISSUE THREAD

**Issue by fresatomica** [Automattic/wp-calypso#40792] opened 2020-04-05 11:14 UTC
### Steps to reproduce

1. Create a page or a post
2. Add Spotify Block
3. Embed a song
4. Center align the block

#### What I expected
The song would be embedded into the player. It would be great if you could choose the size of the embed.

#### What happened instead

The embed is enormous and, apart from displaying the huge album cover, also leaves a big empty space beneath and there's no way to modify its size.

#### Screenshot / Video

![Screen Shot on 2020-04-05 at 13-08-17](https://user-images.githubusercontent.com/40177971/78473155-9fbf1800-773e-11ea-84bb-2e1afef48203.png)

#### Context / Source
https://wordpress.com/forums/topic/embed-spotify/
#user-report

**Comment by bsanevans** [comment] 2020-10-27 06:40
Another report here: 3439181-zd-woothemes (additional context: pbEMJv-hD-p2)

The user tried embedding a Spotify album. The block renders correctly in the editor, but not on the front end.

Embed link: https://open.spotify.com/album/6JLbp9WJrPu4vsi4cqBQH9

Embed in the editor
![spotify-editor](https://user-images.githubusercontent.com/49054298/97265669-62e97880-186a-11eb-8568-ac9a745d79d8.png)

Published post
![spotify-post](https://user-images.githubusercontent.com/49054298/97265684-6846c300-186a-11eb-8799-e63d1419ff16.png)

The issue was reported on the Carbon theme, and could be reproduced on Hever also.

**Comment by ash1eygrace** [comment] 2020-11-10 14:45
I'm getting the same results on individual embeds on my personal blog using the theme Hever. 

<img width="635" alt="Screen Shot 2020-11-10 at 7 42 38 AM" src="https://user-images.githubusercontent.com/29527450/98688748-6bd95000-2328-11eb-82b3-b8183f5502a4.png">

As a workaround, I put the individual songs into grid layout blocks, while not ideal it looks OK: 

<img width="682" alt="Screen Shot 2020-11-10 at 7 43 07 AM" src="https://user-images.githubusercontent.com/29527450/98688847-89a6b500-2328-11eb-8dfb-aef8c0d9d33e.png">

**Comment by fresatomica** [comment] 2020-11-18 13:43
Another report of this: https://wordpress.com/forums/topic/spotify-links-show-large-blank-space-within-embed-on-free-domain.

Also related: https://github.com/WordPress/gutenberg/issues/18518.

**Comment by galakhyati** [comment] 2020-12-01 12:03
Another report: 3529520-zen

**Comment by susanjanec** [comment] 2021-01-15 13:09
Another report - 27023172-hc

**Comment by katiebethbrown** [comment] 2021-01-29 17:31
Reported in 15184092-hc as well.

Shared this CSS to shorten:

```
/* change height of spotify embed | xx-nnnnnnnnn-hc */
.wp-block-embed-spotify .wp-block-embed__wrapper {
	max-height: 200px;
}
```

**Comment by kristarella** [comment] 2021-02-01 22:07
I ran into this yesterday 27170144-hc
And I was able to replicate on my test site:
https://badaboomtest.wordpress.com/embeds/

Since this user was on Personal plan we couldn't use CSS to fix.
We found that converting the block to a paragraph and unlinking the spotify URL so it was just a plain text URL in a paragraph made a different type of embed that was not too big.

**Comment by ivan-ottinger** [comment] 2021-02-04 14:57
Another report: 27031401-hc

@kristarella, that workaround works great! Thanks so much!

**Comment by synora** [comment] 2021-02-15 18:53
Related https://github.com/WordPress/gutenberg/issues/27720. 
Also noting that I can still replicate this issue. 

@cathymcbride would it be ideal to move this issue to the Gutenberg repo?

**Comment by cathymcbride** [comment] 2021-02-16 16:05
@synora I don't think we need to move this issue to the gutenberg repo, as I think this one is a duplicate of 27720. I would recommend closing this one as a duplicate of that one. Alternatively, leave open and add the label `[Status] Keep Open`, as it might be easier for HEs to find this and see when it's fixed. Then when it's fixed in Gutenberg, we can close this one.

**Comment by edwinho89** [comment] 2021-02-25 02:05
Another report in 3759123-zen

**Comment by cathymcbride** [comment] 2021-03-02 16:00
@synora FYI - we've decided to do away with the [Status] Keep Open label and close issues as appropriate. Closing this as a dupe and removing the label.

**Closed by cathymcbride** 2021-03-02 16:00 UTC
Labels: Blocks, Involves Happiness, Triaged, [Status] Keep Open, [Type] Bug
