### ISSUE TITLE
Editor: Obey taxonomy show_ui flag.

### ISSUE THREAD

**Issue by pento** [Automattic/wp-calypso#10428] opened 2017-01-05 12:24 UTC
#### Steps to reproduce

1. Register a custom taxonomy with the `show_ui` flag set to false
2. Visit the editor, observe that the custom taxonomy is showing in the sidebar

#### What I expected

The custom taxonomy box should be hidden, same as if you visit the wp-admin editor for the same site.

**Comment by lancewillett** [comment] 2017-01-06 13:59
This could be a duplicate of #8757

See also #701 and #700

**Closed** 2017-01-16 22:46 UTC
Labels: Editor, [Type] Bug
