### ISSUE TITLE
Jetpack Post Carousel featured images are not showing up

### ISSUE THREAD

**Issue by Neha93517** [Automattic/wp-calypso#86094] opened 2024-01-08 09:01 UTC
### Quick summary

Post carousel is not showing featured images of posts. 
Theme: Maywood 
Working on others. 

Screenshot from the user:
![image](https://github.com/Automattic/wp-calypso/assets/54591499/ca8263c1-1f32-4cd5-b1f5-30039d0dc5e0)

Zen- 7531672

### Steps to reproduce

1. Install Maywood theme
2. Create a Page / use an existing page
3. Click the (+) icon and type "Post carousel"
4. Select Post carousel block

### What you expected to happen

The carousel should show as below:
![image](https://github.com/Automattic/wp-calypso/assets/54591499/04b19695-a76a-4a2c-9e57-34766135e046)

### What actually happened

The carousel shows as below for Maywood theme:
![image](https://github.com/Automattic/wp-calypso/assets/54591499/a0e3dee7-aa59-4c33-855d-c1faa26716f2)

Test page link: https://neha93517.wordpress.com/test/

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by liviopv** [comment] 2024-01-10 15:29
📌 REPRODUCTION RESULTS
there are several issues related to this reported in the past (handy list in the PR above https://github.com/Automattic/jetpack/pull/34805#issue-2058941598), so closing this one as duplicate.

📌 ACTIONS
- Closed as duplicate / by design

**Closed as completed by liviopv** 2024-01-10 15:29 UTC
Labels: Bug, [Pri] High, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered

**Comment by kathrynwp** [comment] 2024-01-14 20:50
Also reported in 7567532-zd-a8c

Asked them to enable featured images on pages in Content Options for now and gave this CSS as a workaround:

```

/* Hide featured images / re-show featured images within Post Carousel block / 7567532-zen */
.post-thumbnail {
  display: none;
}
.wp-block-newspack-blocks-carousel .post-thumbnail {
  display: inherit;
}

```
