### ISSUE TITLE
Sharing: changes do not get saved if you toggle all of the "Show sharing buttons on" options from checked to unchecked [2]

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22811] opened 2018-02-26 16:21 UTC
Steps to reproduce:

1. Go to My Sites > Sharing > Sharing buttons.
1. Find the "Options" section.
1. Uncheck everything under "Show sharing buttons on."
1. Click the "Save Changes" button.

<strong>Result:</strong> if you toggle all of the "Show sharing buttons on" options from checked to unchecked, changes do not get saved.

<strong>Video:</strong> [36s](https://cloudup.com/cDV0HOIGMTq)

![screen shot 2018-02-26 at mon feb 26 9 19 50 am](https://user-images.githubusercontent.com/1119271/36681630-64aebb92-1ad6-11e8-8e99-9e9d61c32b86.png)
<sup>Seen at https://wordpress.com/sharing/buttons/design5279.wordpress.com (production) using Firefox 58.0.2 on macOS 10.13.3.</sup>

Aside: this bug is really strange, some combinations of saving changes work and some don't. ([4m12s](https://cloudup.com/cP4ZBdt-Eaa))

/hat tip 🤠 @cecoates because a related bug posted in the #triage channel led me to find this bug!

**Comment by nagpai** [comment] 2018-04-02 12:07
I was able to replicate the issue on my test site too, with some of the buttons checked. 

![sharing-button-bug](https://user-images.githubusercontent.com/4162931/38195685-667151c4-369c-11e8-8711-016065842f72.gif)

#1050920-zen

**Comment by jamiepalatnik** [comment] 2018-04-10 18:10
Reported in this chat: 2375165-hc

**Comment by katinthehatsite** [comment] 2018-04-15 22:40
Also reported in #1091646-zen

**Comment by ebastos** [comment] 2018-06-14 18:51
Another report via 4352362-hc

**Comment by juliasydnor** [comment] 2018-08-15 12:06
User report 3957790-hc. I was able to reproduce on several test sites (Free and Premium plans).

**Comment by GeoJunkie** [comment] 2018-08-24 20:18
User ran into issue in 5889561-hc

**Comment by kathrynwp** [comment] 2018-11-12 19:43
Also encountered during a Business Concierge session. Ref 1561558-zen.

**Comment by kathrynwp** [comment] 2018-12-19 15:50
Also reported in #29261

**Comment by jamiepalatnik** [comment] 2019-01-11 13:56
9438998-hc. Selecting Front Page, Archive Pages, and Search Results was not saving unless I selected Orders as well. Then it saved, but Order showed as unchecked.

**Comment by suyogyashukla** [comment] 2019-01-24 21:13
9744174-hc

**Comment by Robertght** [comment] 2019-01-25 08:11
Another one found here: #9753379-hc

**Comment by Robertght** [comment] 2019-01-27 08:42
#8291337-hc

**Comment by kylemcph** [comment] 2019-02-05 08:47
#9974040-hc

**Comment by sophiegyo** [comment] 2019-02-15 16:39
Reporting as well, I encountered it here: 10448703-hc

My findings: it's specifically the post page which does this. 
I tested on one of my own sites and was able to reproduce it.

Activating any/all options for sharing button display: no problem.
Deactivating any but Pages: no problem.
Deactivating several, including Pages: problem.
Deactivating Pages only: problem.

Screencast recordings: 
https://cld.wthms.co/OxLSPO
https://cld.wthms.co/94OKxE

**Comment by chaitanyamsv** [comment] 2019-02-21 00:29
Another report in #10599280-hc

**Comment by Robertght** [comment] 2019-02-26 11:27
2097603-hc - Simple site. Hd to assign it to a Product again.

**Comment by desnum** [comment] 2019-02-27 17:27
Another case in hc-10729527 with the Venture theme

**Comment by nagpai** [comment] 2019-03-01 08:35
Another case in 9311829-hc

**Comment by damiannep** [comment] 2019-03-03 06:21
Another case in #10845695-hc

Looks like you have to keep at least one option checked: https://cld.wthms.co/FzjyeY

**Comment by nickpagz** [comment] 2019-03-09 20:19
Another case in #10285453-hc

**Comment by AtrumGeost** [comment] 2019-03-14 14:38
Another case here 7740966-hc

**Comment by jruud** [comment] 2019-03-14 19:57
Another case in 1869218-zen where one option had to remain selected: https://cld.wthms.co/7Ot5wq

This was a simple site, so I tried _only_ selecting "Products", and then clicked Save Changes, and now none of them are checked.

**Comment by kristarella** [comment] 2019-03-22 05:22
+2
- when I was working on the site johnmichaelwrightcom.wordpress.com
- also 11426727-hc had to use wp-admin to uncheck

**Comment by juliasydnor** [comment] 2019-03-29 11:30
Another report in 1917390-zen.

I was able to get around it by unticking Posts and Pages, and ticking Orders, then saving. Since Orders aren't used on the site, it gets disabled when saving, and leaves Posts and Pages disabled as well.

**Comment by khristiansnyder** [comment] 2019-03-31 15:59
Another report in 1915954-zen

They also think they have a fix:

> The value for the `pages` and `posts` checkboxes (in the sharing_show[] array) are in their singular form (eg "page" instead of "pages"). The impact is that users can't turn those checkboxes off because it's submitting the wrong value.
> 
> Simply changing the checkbox value attribute to "pages" and "posts" (I've edited the html client-side to verify this) makes the `Save Changes` button actually update the database.


I can also replicate this on my test AT site: https://cld.wthms.co/5LVGBD
Has this gotten worse in the last few weeks? I'm noticing this issue consistently across many sites.

**Comment by kristarella** [comment] 2019-04-01 00:46
> Has this gotten worse in the last few weeks? I'm noticing this issue consistently across many sites.

I'm not sure it's gotten worse, I think it consistently affects all sites when trying to edit from Calypso, it's fine in WP Admin.

Taking @juliasydnor 's info into account, it might be related to how the info is being saved. Usually no check = no value so nothing needs to be saved, if changing which items are checked it is easy to save the new arrangement of values, but when they were previously checked, and then nothing is checked there needs to be an action taken, like `if there is a value saved in the database, but no value is submitted now, delete the value in the database`.

**Comment by TeniCola** [comment] 2019-04-04 19:11
Another case in HC-11811878, where the settings for the sharing buttons did not save for the user's site, who wanted to untick the Posts and Pages options

I was able to replicate this in SU-mode, and I borrowed @juliasydnor's solution to tick the Order's option to save/resave until the Posts and Pages were unticked. Followed up with the user in ZD-1937724

**Comment by gwwar** [comment] 2019-04-04 19:40
🤔 I think I can't unset options here.

![sharingbuttons](https://user-images.githubusercontent.com/1270189/55583370-938d1e80-56d6-11e9-8931-b5809c45cfb3.gif)

cc @Automattic/lannister this one is up for grabs, let's get a fix out for related p1HpG7-6vu-p2 flows

**Comment by sophiegyo** [comment] 2019-04-18 12:04
User in #12176243-hc reported the issue also occurs for them in Calypso (Block editor view) for individual posts/pages.

Their recording: https://screencast-o-matic.com/watch/cqfFlcZT5l

**Closed** 2019-04-26 10:10 UTC
Labels: Sharing, Site Settings, [Pri] High, [Type] Bug

**Comment by thuautp** [comment] 2019-05-14 16:13
User also reported this issue here #12702424-hc

**Comment by Copons** [comment] 2019-05-14 16:57
@thuautp Thanks for reporting!

Apparently this has changed in the last few days after https://github.com/Automattic/jetpack/pull/12319 (and its twin diff D28007-code) got merged.

@jeherve Could you please clarify about this?
The change practically prevents people to unset all sharing buttons checks, because they will always fall back to `[ 'post', 'page' ]`

**Comment by tbradsha** [comment] 2019-05-16 18:14
#4839871-hc

**Comment by jeherve** [comment] 2019-05-17 08:36
> The change practically prevents people to unset all sharing buttons checks, because they will always fall back to [ 'post', 'page' ]

@Copons That's a good point, thank you, I hadn't thought about that use case.

Would you mind reviewing D28357-code or https://github.com/Automattic/jetpack/pull/12401, and let me know if that fixes the problem for you?

Thanks!
