### ISSUE TITLE
Can't upload plugin (Upload problem: unknown_plugin)

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/wp-calypso#19662] opened 2017-11-10 05:00 UTC
#### Steps to reproduce
1. Go to My Sites > Plugins > Upload Plugin (for Business plan sites)
2. Download any plugin zip. I tested with https://en-gb.wordpress.org/plugins/two-factor/
3. Select the downloaded zip in the upload screen
4. Upload

#### What I expected
Plugin to be installed

#### What happened instead
This error pops out:
`Upload problem: unknown_plugin.`

#### Browser / OS version
Occurs in both browser and in-app
WordPress App 3.0.0
Chrome Version 62.0.3202.89 (Official Build) (64-bit)
MacOS High Sierra 10.13

#### Screenshot / Video
https://snag.gy/GlTHU8.jpg

**Comment by rachelmcr** [comment] 2017-11-10 11:34
Tested and confirmed the issue on an Atomic site with these steps:

1. Identified a plugin (https://en-gb.wordpress.org/plugins/edit-flow/) that I had previously been able to install on an Atomic site, and confirmed it was not currently installed on the test site.
2. Went to My Sites > Plugins > Upload Plugin on that site.
3. Dragged and dropped the plugin .zip file. Result: The `unknown_plugin` error.
4. Clicked on the upload area and selected the plugin .zip file (to make sure the problem wasn't specific to drag-and-drop). Result: The `unknown_plugin` error.
6. Went back to My Sites > Plugins and searched for the Edit Flow plugin.
7. Opened the plugin page at https://wordpress.com/plugins/edit-flow and clicked the Install button there. Result: The plugin installed successfully.

So plugin installation directly from https://wordpress.com/plugins is working, but plugins cannot be uploaded to install.

**Comment by pippinsplugins** [comment] 2017-11-12 01:24
I just ran into this as well. Custom plugin uploads were working properly for me a few days ago but now I get the `unknown_plugin` error as well.

**Comment by msilbers** [comment] 2017-11-15 19:13
Just had a user with this issue in chat. They were attempting to upload a Gravity Forms plugin they downloaded from Gravity's site. They were able to successfully add a plugin directly from the .com plugins directory already. Received error: Upload problem: unknown_plugin.
Reported in 1035308-hc

**Comment by rossanafmenezes** [comment] 2017-11-17 14:24
User purchased a plugin from https://market.envato.com/ Xmas Advent Calendar, not available on our directory, and is getting the same error when trying to upload. Upload problem: unknown_plugin

**Comment by enejb** [comment] 2017-11-17 20:10
Should be fixed now. Feel free to open this issue if that is not the case and we can take a look at it again.

**Closed by enejb** 2017-11-17 20:10 UTC
Labels: OSS Citizen, Plugin Uploads, [Type] Bug
