### ISSUE TITLE
Editor: gallery inline editing popover overlaps notifications area

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#1486] opened 2015-12-10 23:49 UTC
Could be a `z-index` ordering issue?

Steps to repeat.
1. Log in to wpcalypso.wordpress.com and create a new post.
2. Add images and create a gallery.
3. In the post editor, click the gallery to open the small popover with Edit and Remove icons.
4. Now open notifications (either by moving the mouse, or using N keyboard shortcut).
5. Open a notification content by clicking on it or using keyboard down arrows.
6. See the gallery editing popover is still visible **above** the notification area.

Editing the gallery:
![screen shot 2015-12-10 at 16 46 22](https://cloud.githubusercontent.com/assets/66797/11732070/f292b7fc-9f5d-11e5-80cb-5760444d9661.png)

With notifications open:
![screen shot 2015-12-10 at 16 46 12](https://cloud.githubusercontent.com/assets/66797/11732077/00851044-9f5e-11e5-835e-76441f20e520.png)

**Comment by nylen** [comment] 2016-01-15 02:10
Closed by mistake.  It seems likely that this is still an issue, and that it's the same issue as #1815.  I can't get this to happen reliably, but sometimes the editor does not receive a `blur` event that would [hide the toolbar](https://github.com/Automattic/wp-calypso/blob/c540110/client/components/tinymce/plugins/wpcom/plugin.js#L629).

**Comment by lancewillett** [comment] 2016-04-14 17:54
Re-testing this today, I can still repeat it in Mac-n-Chrome with https://wordpress.com/post/example.wordpress.com

![screen shot 2016-04-14 at 10 52 40](https://cloud.githubusercontent.com/assets/66797/14538172/3a0ffe6c-022f-11e6-94f2-7116a2bd703d.png)

**Comment by lancewillett** [comment] 2016-05-19 21:20
Noting still a valid bug — relooking at it today during a bug scrub.

**Comment by youknowriad** [comment] 2016-10-06 09:54
I was not able to reproduce. On the 4th step, I'm not able to use keyboard shortcuts. I've to click outside the editor or click on the notifications menu to open it, and this hides the popover menu.

**Comment by rachelmcr** [comment] 2017-08-22 14:19
I retested this issue and was also unable to reproduce it (Mac 10.12.6, Chrome 60.0.3112.101). Closing as no longer valid.

**Closed by rachelmcr** 2017-08-22 14:19 UTC
Labels: Editor, [Type] Bug
