### ISSUE TITLE
Form in Footer Widget Area Not Redirecting on Submit

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#62020] opened 2022-03-17 16:57 UTC
### Quick summary

When a Form block is in the footer widget area and is submitted, it is not redirecting to the specified page.

### Steps to reproduce

1. Tested using `Twenty Twenty` but this issue seems to affect other themes such as `Gateway`. 
2. Go to **Appearance > Widgets**, add a Form, set the form to redirect to another page on submission.
3. Open site in a browser, go to footer and submit some information in the form in the footer.

### What you expected to happen

1. The user to be redirected to the specified page on submit.

### What actually happened

1. The page flashes and reloads the same page.

### Context

Discovered here: 4869374-zd-woothemes

Tested and was able to replicate issue on my own site.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Greatdane** [comment] 2022-03-30 05:24
It looks to happen on all the themes tested, so I think it's a block bug rather than a theme issue. Leaving in `calypso` repo.

**Comment by jordesign** [comment] 2022-05-06 06:40
Closing this as a duplicate of https://github.com/Automattic/wp-calypso/issues/62431

**Closed as completed by jordesign** 2022-05-06 06:40 UTC
Labels: Bug, [Pri] Normal, Triaged
