### ISSUE TITLE
Earn: Plan upgrade nudge is missing if Stripe is already connected.

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#35455] opened 2019-08-16 08:05 UTC
Recurring payments management section in Calypso (`https://wordpress.com/earn/payments/SITE`) should normally render an upgrade nudge like so:

<img width="500" alt="Screenshot 2019-08-16 at 10 58 28" src="https://user-images.githubusercontent.com/87168/63152826-6c941100-c015-11e9-8f39-a352916c83f7.png">

For a Jetpack site that _is_ connected to Stripe but does _not_ have a plan, I don't see the nudge:

<img width="500" alt="Screenshot 2019-08-16 at 10 58 55" src="https://user-images.githubusercontent.com/87168/63152868-8897b280-c015-11e9-92d7-429cec99123c.png">

Code:
https://github.com/Automattic/wp-calypso/blob/a763d9c2b54e7880307f914423f1ab74348dbc1e/client/my-sites/earn/memberships/index.jsx#L416-L426

**Comment by sixhours** [comment] 2020-05-13 17:03
I do see this nudge on a Jetpack free site, but I don't have a way to know if my site is connected to Stripe (I do have Stripe sandboxed, though):

<img width="1111" alt="Screen Shot 2020-05-13 at 12 31 48 PM" src="https://user-images.githubusercontent.com/2124984/81842222-a731c800-9519-11ea-8f86-3d621a4c9d45.png">

I don't see an avenue to connect to Stripe when you don't already have a paid account. In an older version of Recurring Payments, we showed the link to connect to Stripe (example in #13233) but now it looks like this:

<img width="709" alt="Screen Shot 2020-05-13 at 12 58 47 PM" src="https://user-images.githubusercontent.com/2124984/81842213-a26d1400-9519-11ea-965d-215b5d308d66.png">

I think this was fixed during the other UpsellNudge work.

**Comment by artpi** [comment] 2020-05-15 17:08
It seems that this would be almost impossible to reproduce - maybe downgrading achieves this goal. I'll put it for later improvements

**Comment by davipontesblog** [comment] 2021-04-08 13:31
@simison when you say this:

> For a Jetpack site that is connected to Stripe but does not have a plan

What would be the steps to try to replicate this type of site? I'd like to try and check if this issue is still reproducible.

Thanks!

**Comment by simison** [comment] 2021-04-08 14:17
Oh wow 😅 

<img width="457" alt="image" src="https://user-images.githubusercontent.com/87168/114042627-437d5f80-988e-11eb-92ed-071dccd01c14.png">

I don't really know anymore, but let's ask @Automattic/view-engineering who've worked on that block more recently.

**Comment by simison** [comment] 2021-04-08 14:19
Just my gut feel tho; since no reports since 2019, and Artur even noted it's hard to repro, I'd just close and move on. :-) But let's leave that decision for the View team since they own this stuff nowadays.

**Comment by apeatling** [comment] 2021-06-14 21:00
Can't reproduce this, we've done a lot of work on it recently. Closing unless someone can reproduce.

**Closed by apeatling** 2021-06-14 21:00 UTC
Labels: Earn, FixTheFlows, [Status] Blocked / Hold, [Type] Bug
