### ISSUE TITLE
Editor: markdown is converted to html when publishing a draft without making any changes after reopening and hitting publish

### ISSUE THREAD

**Issue by habi** [Automattic/wp-calypso#2373] opened 2016-01-13 09:19 UTC
I'm writing all my blog posts in Markdown and rely on the awesome JetPack plugin to do it's thing with the posts afterwards.
When I prepare my posts with the [desktop app](http://desktop.wordpress.com/) (Version 1.2.1 on OS X 10.11.2 (15C50)) the posts get converted from Markdown to HTML when publishing them.
I'd rather not have that, since it also does not happen when I do it in the admin interface of my (self-hosted) blog, which makes after-publishing-editing much more convenient in my view.

**Comment by designsimply** [comment] 2016-01-13 17:49
I tested adding markdown to a new post using the desktop app (version 1.2.1) and the content was not converted from markdown to html on publish.

My testing steps were:

1. Open the desktop app and click "My Sites" and switch to a Jetpack site
1. Click the "Add" button next to Blog Posts on the left
1. Paste in some markdown
1. Click the "Publish" button
1. Click the "View Post" button
1. Close and reopen the desktop app (this isn't really needed)
1. Re-open the previous post for editing
1. Make some edits to the markdown (make sure not to trigger formatting shortcuts in the visual editor)
1. Click the "Update" button
1. Edit again
1. Click the "Update" button
1. Close and reopen the post
1. Check to see if the markdown has been converted to html or not

Result: markdown worked normally and was not converted to html unless formatting shortcuts were triggered by editing in the visual editor and pressing enter after headings or lists (the expected behavior).

Video: https://cloudup.com/cEks9loWtK1
<sup>Tested with WordPress 4.4.1 and Jetpack 3.8.2 with Markdown enabled using the desktop app 1.2.1</sup>

If you're still having trouble and your testing steps are different than mine, please reopen and include your steps and a screencast if possible.

**Comment by habi** [comment] 2016-01-13 22:15
Here's a screencast of the problem that **still** persists for me: https://youtu.be/1OyD8ZwOcH8

1. At first, everything worked as expected in an old post (trimmed at the beginning of the screencast)
2. Click "Add"
3. Write some markdown, including a http**s** link (maybe that's the problem!)
4. Save and Preview the post: https://youtu.be/1OyD8ZwOcH8?t=45s
5. Close and reopen the desktop app
6. Go to 'My Sites' > 'Blog Posts' > 'Drafts' and open the post
7. Click from HTML to Visual and back
8. Publish the post
9. View the post on the web
10. Go back to 'All Posts': https://www.youtu.be/1OyD8ZwOcH8?t=1m38s
11. Click on the just published post
12: Voila, it's in HTML instead of Markdown as seen in the screenshot below

![screen shot 2016-01-13 at 23 15 08](https://cloud.githubusercontent.com/assets/1651235/12309532/8848275c-ba4b-11e5-815a-535e6f754343.PNG)

**Comment by habi** [comment] 2016-01-13 22:18
@designsimply: I cannot *reopen* this issue, can you do that for me?

**Comment by designsimply** [comment] 2016-01-13 23:12
Dang, that is a tricky set of steps! 

I tested and could reproduce the problem but only if I followed your steps precisely. I found that the problem you described _only_ happens when you reopen a draft and publish it without making any changes at all prior to publishing. Can you try the following variation?

1. Start a new post
1. Add a link using markdown (in HTML mode)
1. Save the post as a draft
1. Go to All Posts
1. Reopen post for editing
1. Make any change, a line return, whatever (this is key)
1. Click Publish

**Comment by habi** [comment] 2016-01-14 21:10
If I follow your variation, the problem does *not* show up: https://youtu.be/dLWSUpEcX6E

**Comment by designsimply** [comment] 2016-01-14 21:37
Thanks for checking that. We can leave this open for now, but I consider this issue low priority because it only happens under a very precise set of very specific steps that not very many people are likely to encounter.

**Comment by habi** [comment] 2016-01-15 10:48
I agree that it’s low priority, but nonetheless it’s a bug.
Thanks for acknowledging the bug and leaving it open so it will *eventually* be fixed.

**Comment by lancewillett** [comment] 2016-04-14 16:37
Noting in a bug scrub: still leaving open, future item but low priority.

**Comment by timmyc** [comment] 2017-01-26 19:32
Another report of the issue in 824750-f

**Comment by timmyc** [comment] 2017-01-26 21:07
Debugged this a bit, and the failure is happening when publishing from the prior save draft, when you make no additional changes to the draft.

The markdown plugin does a bit of "magic" to swap the real post content ( rendered HTML from the markdown ) with the value stored in `post_content_filtered`.  When you load a draft in the editor, the API correctly returns the markdown content from `post_content_filtered`.  Since Calypso and the editor consider what is returned from the API as the "truth"/saved value for `post_content` in the WPCOM database, the `post_content` is not considered "dirty" by the editor.

As such, if you load up a draft and do not modify the `post_content`, and click pubilsh - the only values that are sent to the API are the dirty/changed values... which in this case is just the post status.  The same flow in wp-admin works because the markdown copy from `post_content_filtered` is passed regardless of being edited or not in the form's POST.

Since the `post_content` is not sent to the API on publish, the logic grabs `post_content` from the database, which is the non-markdown HTML version of the post, and that is when the value of `post_content_filtered` is replaced with the HTML version of the content.

The same bug is also hit on a published markdown post that is updated from within Calypso ( or any API client that only sends changed fields ) and anything other than the post content is updated.  So for example if I publish a markdown post in one step ( thus the markdown is still correctly persisted ), and come back later and add a forgotten tag to the post - the markdown is lost.

A couple of solutions could be pursued here:

1. Add logic to the calypso editor to sniff out markdown meta, and always send the `post_content` on API requests ( hacky ).
2. Add similar logic to the API that determines if a post is markdown enabled, and if `post_content` is omitted from the request, replace the value with `post_content_filtered`
3. Update the plugin logic to test to see if the existing `post_content` matches what is being passed into `WPCom_Markdown#wp_insert_post_data`, if so skip updating `post_content_filtered` completely.

/cc @mattwiebe

**Comment by naokomc** [comment] 2017-02-07 04:03
Just adding another [report](https://ja.forums.wordpress.com/topic/1897?replies=4) with a GIF video & different set of steps to show the issue. 

GIF: https://giphy.com/gifs/l3q2sziJ2GCaBMwLe

**Steps:**
1. Open a new post
3. Enter some Markdown text
4. Preview the post
5. Publish
6. Edit the post from the frontend "Edit" link

FYI, here are other GIFs where the Markdown formatting was retained:

- https://giphy.com/gifs/l3q2uvXQ3KVM7LSko
- https://giphy.com/gifs/26xBIZsXB3GBpPIcg

**Comment by mattwiebe** [comment] 2017-02-07 21:00
Markdown support has never been addressed in REST API contexts and therefore also not in the Calypso editor.

From @timmyc's [comment](#issuecomment-275513957) above, 2) and/or 3) seem worth pursuing for anyone who wants to solve this more urgently, since it will probably be a good while before I get to it.

**Comment by lancewillett** [comment] 2017-02-07 21:24
I think a viable option is to not support Markdown in Calypso at all. Needs further discussion.

**Comment by lancewillett** [comment] 2017-02-21 15:31
Let's move ahead with disabling Markdown support explicitly in Calypso. [See notes here](https://github.com/Automattic/wp-calypso/issues/529#issuecomment-281376463).

**Comment by lancewillett** [comment] 2017-02-22 22:18
Re-opening this because regardless of whether we reveal Markdown as an option (silently there or turned off) we don't want existing posts to break.

We'll need to address the support in the API as mentioned above by Wiebe either way.

**Comment by designsimply** [comment] 2018-02-13 02:44
#bug-scrub #pre-gutenburg-bug-purge

Moved to https://github.com/WordPress/gutenberg/issues/5019

**Closed by designsimply** 2018-02-13 02:44 UTC
Labels: Editor, OSS Citizen, [Pri] Low, [Type] Bug
