### ISSUE TITLE
Settings: No option to change site address in General settings for AT sites

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wp-calypso#36313] opened 2019-09-25 15:53 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/
2. Look at the “Site Tools” section

#### What I expected
I would expect to see the same options on simple and AT sites.

#### What happened instead
Simple sites have the option to "Change your site address." AT sites do not. Related to this issue: #36301 

#### Screenshot / Video
Screenshot Simple — https://cld.wthms.co/MnZdjO
Screenshot Atomic — https://cld.wthms.co/uCyDLR

#manual-testing

**Comment by gwwar** [comment] 2020-01-30 20:06
Duplicate of https://github.com/Automattic/wp-calypso/issues/36301

**Closed by gwwar** 2020-01-30 20:06 UTC
Labels: Atomic, Site Settings
