### ISSUE TITLE
Shortcode block displays code on templates

### ISSUE THREAD

**Issue by AlexanderSky** [Automattic/wp-calypso#79435] opened 2023-07-14 15:15 UTC
### Quick summary

When adding a shortcode with the Shortcode Block in a template, the shortcodes are not rendered and instead only code is displayed.

### Steps to reproduce

1. Activate a FSE theme like Loudness
2. Open editor
3. Edit Blog Home template
4. Insert Shortcode Block anywhere in the template
5. Add a shortcode. ex: [bandcamp width=350 height=470 album=3477181664 size=large bgcol=ffffff linkcol=0687f5 tracklist=false] or [sitemap]

### What you expected to happen

The shortcode should be rendered and a Bandcamp album should be displayed 

### What actually happened

The shortcode code is displayed on the front-end
![image](https://github.com/Automattic/wp-calypso/assets/7353295/5e3b62a2-4429-4b7b-8452-8e426030a7a2)

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by AlexanderSky** [comment] 2023-07-14 15:17
#6535386-zen

**Comment by cuemarie** [comment] 2023-07-17 18:46
📌 ACTIONS
- Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/77001

📌 Message to Author
- @AlexanderSky this is expected behavior on Simple sites. see: https://github.com/Automattic/wp-calypso/issues/77001#issuecomment-1557627974
- Wrapping the Shortcode in a Template Part allows it to load properly.

**Closed as not planned by cuemarie** 2023-07-17 18:46 UTC
Labels: Bug, [Pri] Normal, Shortcodes, Triaged
