### ISSUE TITLE
Checkout: Domain reneval interval change event does not include interval

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#95130] opened 2024-10-03 15:49 UTC
### Details

 On the checkout page, changing the domain renewal interval triggers calypso_checkout_composite_plan_length_change event. However, its new_product_slug property doesn’t include any information about the renewal interval (e.g., dotblog_domain). This occurs in both the Classic flow and the Stepper flow.

**Comment by renancarvalho** [comment] 2024-10-07 12:46
Hi @escapemanuele 
I checked this issue and cannot reproduce it, I have changed the domain renewal interval drop down, and I can see it being logged with the correct information

![Image](https://github.com/user-attachments/assets/d696abf8-093d-4afe-b078-9ff07e57c17c)

I have compared and debugged start and stepper and both log the same.

**Comment by renancarvalho** [comment] 2024-10-08 07:18
@escapemanuele shall we close it?

**Closed as completed** 2024-10-08 14:56 UTC
Labels: Task
