### ISSUE TITLE
Plans Grid: glitches in sticky action buttons when scrolling

### ISSUE THREAD

**Issue by jsnajdr** [Automattic/wp-calypso#82853] opened 2023-10-11 09:02 UTC
Looking at the plans grid (at `wordpress.com/plans/example.com`) I noticed several glitches related to the "Upgrade" action buttons. They are all visible in the screencast that's attached below.

1. The font size on the buttons changes when they become sticky. (All except the Downgrade button.) There is no reason for that, they continue to be exactly the same buttons. I understand why the labels change to include the price, that's because the price info has scrolled away, but I think no other changes are justified.
2. I was confused by the "Upgrade – €17" label. At first I read it as "minus €17", as a discount (and there actually _is_ a discount there!), and only later I realized it's a "dash followed by the actual price". I think "Upgrade (€17)" would be a better label, ruling out the "minus" interpretation.
3. When I scroll up, then on the bottom edge of the page the action buttons also become sticky (or at least get the sticky styling), but they are not really sticky, they scroll away.

https://github.com/Automattic/wp-calypso/assets/664258/c4533379-256c-4e0e-b4d7-1ffe6f1ae0e3

**Comment by cuemarie** [comment] 2023-10-13 00:43
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated the font size change and 

**Font Size Change**

![DN94Yy.gif](https://github.com/Automattic/wp-calypso/assets/27249804/2e064f8a-43eb-4224-9c0b-22c28a6e2316)

**Button change at bottom of viewport**

![sZVj6L.gif](https://github.com/Automattic/wp-calypso/assets/27249804/a805323e-5960-485e-86e9-d1b255d76089)

📌 ACTIONS
- Triaged
- CC: @Automattic/martech

**Comment by davemart-in** [comment] 2024-10-16 19:51
Still an issue.

**Comment by oswian** [comment] 2024-10-21 04:01
I've opened a [PR](https://github.com/Automattic/wp-calypso/pull/95537) to address 2 out of the 3 issues reported here. However I haven't been able to replicate this issue:

> "When I scroll up, then on the bottom edge of the page the action buttons also become sticky (or at least get the sticky styling), but they are not really sticky, they scroll away."

Does this occur consistently in any particular scenario, browser etc?

**Comment by aneeshd16** [comment] 2024-10-21 20:47
I can reproduce this. The issue is that when the CTAs reach the bottom edge of the screen, the sticky styling is applied to them:
![Image](https://github.com/user-attachments/assets/db4ea5e8-aa34-4102-a498-ae526fe74a01)

**Comment by oswian** [comment] 2024-10-22 00:37
Thanks for taking a look @southp @aneeshd16. I can replicate the issue in Firefox (but not Chrome) and I have a fix on the way. The cause appears to be a difference in the precision of the `intersectionRect.bottom` value between browsers (which is used in the sticky check).

**Comment by jsnajdr** [comment] 2024-10-24 12:07
@oswian The problem seems to be that in Firefox the exact check (`intersectionRect.bottom === rootBounds.bottom`) doesn't work because the values are slightly different (387.4999 vs 387.5):

![Image](https://github.com/user-attachments/assets/c03e9c2e-81c2-413f-b78a-8e46c01e33cf)

A better check would be:
```
entry.boundingClientRect.bottom >= rootBounds.bottom
```
Here we're not checking the intersection rect, but the rect of the `<tr>` element, and checking whether its bottom edge is below the container bottom edge.

**Comment by oswian** [comment] 2024-10-24 23:41
> The problem seems to be that in Firefox the exact check (intersectionRect.bottom === rootBounds.bottom)

@jsnajdr Thanks, yes I came to the same conclusion and introduced an updated check [here](https://github.com/Automattic/wp-calypso/pull/95537/commits/a9ced16ee2586fe8cca8673cb5653a817964a4f2). However your suggested check is simpler and achieves the same result, so I've pushed that [change](https://github.com/Automattic/wp-calypso/pull/95537/commits/c3acaea1d825533910aaaaddf66d13acc06942fc).

**Comment by oswian** [comment] 2024-11-19 03:02
Fix has been deployed: https://github.com/Automattic/wp-calypso/pull/95537

**Closed as completed by oswian** 2024-11-19 03:02 UTC
Labels: Enhancement, [Pri] Low, [Feature Group] A8C Marketing & Sales, Triaged, [Feature] Pricing, [Product] WordPress.com
