### ISSUE TITLE
Gutenberg: Always allow Featured Image to be set

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#28938] opened 2018-11-29 13:52 UTC
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Start a new post on a Gutenberg-enabled site using a certain theme (confirmed with Linen)
3. Note the Featured Image option is not shown

#### What I expected
To be able to set a Featured Image regardless of theme support as it's used by things like Publicized

#### What happened instead
No Featured Image option was shown

#### Browser / OS version
Chrome 70.0.3538.11/OS X 10

#### Screenshot / Video
<img width="1395" alt="screen shot 2018-11-29 at 8 50 44 am" src="https://user-images.githubusercontent.com/1900444/49226196-e61a9f00-f3b3-11e8-9aa4-7f0a37e0b104.png">

#### Context / Source

#manual-testing

**Comment by kwight** [comment] 2018-11-29 19:34
it looks like this may just be a theme-specific (`premium/linen`) bug; I don't have the same problem with other themes. The response to `https://public-api.wordpress.com/wp/v2/sites/:site/themes?status=active` shows support for post thumbnails as `false`, which seems wrong from what I can tell. Will dig a little deeper.

**Comment by KokkieH** [comment] 2018-12-10 04:30
Have another report via [Twitter](https://twitter.com/GeekishBook/status/1071850500746817537)

Site: https://geekishbooks.wordpress.com/

Theme: Retro-fitted (retired)

**Comment by ahmadbaig1** [comment] 2018-12-16 19:33
Confirmed the same issue with another theme- Plane.
Featured Image option not visible in a site with Premium Plan, however, it is visible in an AT site.

Screenshot- [https://prntscr.com/lvq88l](https://prntscr.com/lvq88l)

Site [URL](https://tbitolife.wordpress.com)
User- laurienyc

**Comment by Copons** [comment] 2019-01-04 12:43
Fixed by D22775-code

**Closed by Copons** 2019-01-04 12:43 UTC
Labels: [Goal] Gutenberg, [Pri] High, [Type] Bug
