### ISSUE TITLE
Global Style Changes are not reflected immediately on the live site

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#68893] opened 2022-10-11 10:02 UTC
### Quick summary

After changing the font or other typography-related settings on Block themes, it was not reflected instantly. I was able to reproduce this issue on multiple themes like Zoologist, Livro, etc. I had to reload multiple times or clear browser cache to see the change.

Most users would not be familiar with clearing cache and it is not a good experience to have to clear cache every time a change it made in Global Styles.

I was able to reproduce it only on Simple sites.

### Steps to reproduce

1. Switch to an FSE theme.
2. Go to Appearance > Editor > Global Styles
3. Change different properties like Fonts, Letter case, etc and save it.
4. You will notice you have to reload the site multiple times or manually clear the cache to see the changes.

### What you expected to happen

Changes in Global Styles should be immediately reflected, without having to clear the cache.

### What actually happened

Had to clear the cache and reload multiple times.

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Intermittent

### Available workarounds?

Yes, difficult to implement

### Workaround details

Have to clear the cache, and reload multiple times. It is not easy to implement and is quite frustrating since you need to do it multiple times.

**Comment by zachspears** [comment] 2022-10-12 03:39
Hey @devNigel, I was unable to reproduce this. Do you notice the issue in a particularly browser or theme?

**Comment by Copons** [comment] 2022-10-13 10:15
I think this is related to either of these Core Guten issues:
https://github.com/WordPress/gutenberg/issues/43914
https://github.com/WordPress/gutenberg/issues/43395

There is indeed a small cache (1 minute, IIRC) on Global Styles.
It isn't often noticed while testing, because of how short it is and the number of things triggering a refresh (e.g. changing theme, just to name the most common).
The cache might also be bypassed when testing on the sandbox (at least I have never seen this issue, but was always a bit concerned about that cache while looking at the code. 🙂 

I'll close this issue since it needs to be fixed from Core, but thanks for testing, investigating, and reporting! ✨

**Closed as not planned by Copons** 2022-10-13 10:15 UTC
Labels: Bug, [Pri] Normal, [Status] Needs Author Reply, [Platform] Simple
