### ISSUE TITLE
Safari scrolling issues - Design Picker and Assembler flow

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#73700] opened 2023-02-23 03:20 UTC
When testing the Pattern Assembler on Safari Version 16.2 (18614.3.7.1.5), I noticed two issues related to navigating the UI quickly, clicking and scrolling as fast as possible.

### Testing steps
- Create a new site
- Continue until the design picker
- Scroll down quickly and click "Start designing"
- Add patterns, scroll the list quickly
- Go back and forth to the design picker, scroll the lists up and down

### Design Picker
The component crashes, and the page is blank.

![Image](https://user-images.githubusercontent.com/1881481/220811548-99f79c02-2550-43e3-bdd2-8c3618eff783.png)

**Error**
![Image](https://user-images.githubusercontent.com/1881481/220811561-b005055d-e3c1-4cab-8c7e-558ebef05b8b.png)

### Assembler
The following patterns are only visible when scrolling down, but they won't load randomly if you scroll down quickly. It could be related to the content resizer observer.

![Image](https://user-images.githubusercontent.com/1881481/220812020-71ed019d-6ab8-40a2-9528-5d311a448b61.png)

https://user-images.githubusercontent.com/1881481/220814406-fe29de96-593f-42a9-96a9-b99682b65690.mov

**Comment by miksansegundo** [comment] 2023-02-23 03:23
@Automattic/lego, I found these random issues on Safari when testing the scrolling and performance of the rendering.

**Comment by arthur791004** [comment] 2023-02-23 10:33
hmmm....I cannot reproduce this issue on my side 🥲 What's the version of your Safari?

**Comment by miksansegundo** [comment] 2023-02-24 04:27
> What's the version of your Safari?

Safari Version 16.2 (18614.3.7.1.5)

I also haven't been able to reproduce them again.

**Comment by okmttdhr** [comment] 2023-03-01 03:11
📝 2023/03/01
- Others have encountered this problem.
- Might this be happening when memory is not sufficient (like you're opening Figma)? by @miksansegundo 

---

For the error (`undefined is not an object (evaluating e.static.designs.filter)`), the following would be the corresponding code? 
https://github.com/Automattic/wp-calypso/blob/4e15306765f418b689b9c65b786db29ecb31e4e2/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx#L105

**Comment by arthur791004** [comment] 2023-04-18 06:17
I guess we can close this issue as we cannot reproduce it anymore. If we encounter this issue again in the future, we can just re-open it.

**Closed as completed** 2023-04-18 06:18 UTC
Labels: Bug, [Pri] Normal, [Browser] Safari
