### ISSUE TITLE
First-year discount for plans is no longer shown on the plans page

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#50909] opened 2021-03-09 17:09 UTC
This was originally reported by @niranjan-uma-shankar at https://github.com/Automattic/wp-calypso/pull/49884#pullrequestreview-599497429 (it's a regression caused by that issue).

### Steps to reproduce the behavior

1. Start with an existing account that uses the INR currency.
2. Go to https://wordpress.com/pricing/ and notice that it shows a ₹800/month price (billed annually) for the Business plan, crossed-out and replaced with ₹640 (to reflect the 20% first-year discount).
3. Go to https://wordpress.com/plans for an existing free site and notice that it only says "₹800/month billed annually" here.  **Nothing on this page reflects the 20% discount anymore.**
4. Click upgrade to go into checkout.  This now shows the correct price reflecting the 20% discount (i.e. ₹9,600/year crossed out and replaced with ₹7,680/year, which is equivalent to ₹800/month => ₹640/month).

#### What I expected to happen

The price on the Plans page should match the price shown on the other pages (which is the actual amount the user will pay).  For example, this is how it used to look:

<img width="343" alt="109294608-6c541300-7853-11eb-97d0-e9e85b141807" src="https://user-images.githubusercontent.com/235183/110508976-9d440b80-80cf-11eb-8802-f624646867e6.png">

(Notice also the "Save 20% for 12 months" text, which is important here too to avoid misleading the user. Although perhaps it should be reworded now because it's a bit confusing given that we also offer monthly plans... but the bottom line is that it should indicate the 20% discount is only valid for the first year.)

#### What actually happened

I saw this instead:

![Screenshot from 2021-03-09 12-05-21](https://user-images.githubusercontent.com/235183/110509176-d41a2180-80cf-11eb-88b7-06033c29bded.png)

In the above screenshot I expanded the tooltip to also show another aspect of the bug (the tooltip is referring to the non-displayed discount).

**Comment by michaeldcain** [comment] 2021-03-09 18:56
@paulbonahora: is this something that you can help Marketing triage? It's a regression caused by the monthly plans rollout.

**Comment by aleone89** [comment] 2021-12-15 08:19
Flagging there's another report here: https://wpcomhappy.wordpress.com/2021/10/07/pricing-packaging-international-discounts/

**Comment by aleone89** [comment] 2021-12-15 09:54
This has been reported here: https://wordpress.com/forums/topic/pricing-scam/?view=all

**Comment by niranjan-uma-shankar** [comment] 2021-12-17 10:54
> but the bottom line is that it should indicate the 20% discount is only valid for the first year.

In other places such as logged out pages(LOHP, /pricing) and signup flow plans step - we don't mention that the discount is first-year only. cc @paulbonahora is this something to be addressed?

On Calypso's /plans page, we mention that the discount is first-year only in the tooltip, so I guess that should suffice?

<img width="291" alt="Screenshot 2021-12-17 at 2 52 29 PM" src="https://user-images.githubusercontent.com/1269602/146533817-9d6a0154-1488-4ad5-869a-755f91082024.png">

> Although perhaps it should be reworded now because it's a bit confusing given that we also offer monthly plans.

Here's an idea:
<img width="257" alt="Screenshot 2021-12-17 at 3 01 44 PM" src="https://user-images.githubusercontent.com/1269602/146534938-8dff9014-f55e-484e-8c07-475e76718e36.png">


@paulbonahora @victorespigares would love your feedback on this, or if you think we should word this differently please let me know.

**Comment by donlair** [comment] 2021-12-17 12:47
@niranjan-uma-shankar the two different savings percentages are confusing (the 20% and 39%). In this case, I'd remove the 39% annually bit and keep the "20% off" label since that's the only thing that's actually a discount. 

If we want copy to explain the discount I'd go with something like "Buy today and save 20% for your first year" in the spot where you've got the 39% line. Or remove the "buy today" part if that's too long.

I don't follow why the monthly plans make this confusing - do we offer the 20% discount on monthly plans as well?

**Comment by DavidRothstein** [comment] 2021-12-17 20:00
>I don't follow why the monthly plans make this confusing - do we offer the 20% discount on monthly plans as well?

No -- I just meant that restoring the original wording ("Save X% for 12 months") could be confusing because with monthly plans in the mix, it's no longer clear whether that's referring to the savings you get for the first year of an annual subscription (i.e. the 20% in the above example) or the savings you get from choosing to buy an annual subscription as opposed to paying for a monthly subscription for 12 months in a row (i.e. the 39% in the above example).

The way you proposed doing it avoids that confusion, so it seems fine to me.

**Comment by southp** [comment] 2021-12-20 03:16
It looks like we need one fix and two decisions here:

* Fix: Bring back the slashed-out emphasis to the 1st year discount to /plans like we used to be.
* Decision 1: Do we want to update the wording so we cover both the 1st year discount and the saving done by subscribing annually?
* Decision 2: Do we want to do the same to LOHP and the other landing pages?

Does that sound correct? 

If so, for the fix, I'll prioritize it. For the decisions, @paulbonahora could you help us decide?

**Comment by niranjan-uma-shankar** [comment] 2021-12-20 08:13
@donlair I see what you mean that the two % discounts could be confusing. What do you feel about calling out the actual monies saved with the annual plan instead of percentages? For example, can we say "You're saving INR 1920 by paying annually"? We could also drop this line altogether and go for the 20% bit as you suggested. I leave it to the P&P pod to take a call on the copy. 

Based on what we decide, let's aim for consistency in language across all screens. For example, in the signup flow plans step, we say that the annual plan savings is 24% savings. This is calculated as ( ( INR 1050 - INR 800 ) / INR 1050 ) * 100, based on the full undiscounted annual price:

<img width="408" alt="Screenshot 2021-12-20 at 11 46 43 AM" src="https://user-images.githubusercontent.com/1269602/146731107-8457e6b4-df7b-476a-809c-0e86625ea733.png">

In Calypso /plans step, we say that the annual plan savings is 39%, calculated as ( ( INR 1050 - INR 640 ) / INR 1050 ) * 100, baed on the discounted annual price:

<img width="270" alt="Screenshot 2021-12-20 at 11 47 15 AM" src="https://user-images.githubusercontent.com/1269602/146731590-6ccb123f-da8d-4d4e-a0a7-d225af9c2ac7.png">

To summarise:
* We need consistency in the annual plan savings figure, and it looks to me that the 39% figure is the correct one for the first year. For the second year onwards, the 24% figure is correct.
* For INR, MXN, and PHP currencies, we need to decide which among the two types of savings(20% first year discount vs annual plan savings) we want to project, or if we want to project both. For all other currencies, the annual savings language that we currently have makes sense as that's the only type of discount, so no change required there. 
* On Calypso /plans, should we show the full annual price like we do in the signup flow /plans step?

Signup flow shows the full price:
<img width="228" alt="Screenshot 2021-12-20 at 12 11 48 PM" src="https://user-images.githubusercontent.com/1269602/146734161-8b551dba-1fb4-4014-90fb-f915e5abdbb8.png">

Calypso `/plans` page shows "billed annually" without mentioning the full price:
<img width="268" alt="Screenshot 2021-12-20 at 12 11 36 PM" src="https://user-images.githubusercontent.com/1269602/146734169-ad440bfb-6247-4dc7-bb2e-53ae6c16cd9f.png">

* The billed annually price in the signup flow plans step is incorrect in INR, MXN, and PHP currencies. Separate bug to track that is in https://github.com/Automattic/wp-calypso/issues/59349.

**Comment by paulbonahora** [comment] 2021-12-20 09:57
What if we showed "First year discount included" for the annual discount? In that way we:
- Show only one discount % (annual savings) and avoid confusion in that regard.
- Ensure consistency at checkout?
@DavidRothstein , @niranjan-uma-shankar , what do you think?

**Comment by niranjan-uma-shankar** [comment] 2021-12-20 10:10
> Show only one discount % (annual savings) and avoid confusion in that regard.

Just to clarify, are you proposing that in the UI below, we replace the "You're saving 39% ..." text with "First year discount included"?

<img width="257" alt="Screenshot 2021-12-17 at 3 01 44 PM" src="https://user-images.githubusercontent.com/1269602/146534938-8dff9014-f55e-484e-8c07-475e76718e36.png">

**Comment by claudiucelfilip** [comment] 2022-02-02 07:56
This should be fixed by #60184.
Closing this.

**Closed as completed by claudiucelfilip** 2022-02-02 07:56 UTC
Labels: Bug, [Feature] Plans & Upgrades
