### ISSUE TITLE
Editor: Highlight content that includes a slideshow/gallery, and then click on a Heading size in the toolbar, creates broken shortcodes.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#19200] opened 2017-10-26 21:36 UTC
Steps to reproduce

Create a page with galleries in it, such as:

~~~~
<h6 style="text-align:center;"><u>Ocean View Room</u></h6>
<h6 style="text-align:center;">Our Monkey Room contains one King Bed, and has a private balcony overlooking the gardens and beautiful Pacific Ocean.</h6>
[gallery ids="444,503,199" type="rectangular" orderby="rand"]
~~~~

Highlight all the content in the Visual Editor, text and galleries.

Use the Visual Editor toolbar to select a heading size, such as "Heading 5".

Code is changed into:

~~~~
<div class="wpview-body">
<div class="wpview-content wpview-type-gallery"><a href="https://wpcomwidgets.com/render/">https://wpcomwidgets.com/render/</a></div>
</div>
<h5 style="text-align:center;"><u>Ocean View Room</u></h5>
<h5 style="text-align:center;">Our Monkey Room contains one King Bed, and has a private balcony overlooking the gardens and beautiful Pacific Ocean.</h5>
~~~~

What I expected

The text would be switched to Heading size 5, but the image content would be unaffected.

What happened instead

The image galleries are replaced with:

~~~~
<div class="wpview-body">
<div class="wpview-content wpview-type-gallery"><a href="https://wpcomwidgets.com/render/">https://wpcomwidgets.com/render/</a></div>
</div>
<h5 style="text-align:center;"><u>Ocean View Room</u></h5>
<h5 style="text-align:center;">Our Monkey Room contains one King Bed, and has a private balcony overlooking the gardens and beautiful Pacific Ocean.</h5>
~~~~

Which will only display as:

https://wpcomwidgets.com/render/

When viewing the page. The image gallery is now completely gone.

Browser / OS version

Chrome Beta Version 62.0.3202.62, Debian 9.
 
Screenshot / Video

http://cld.wthms.co/KQf6RK

Context / Source

Issue reported in 112634015-hc, ticket follow-up 757896-zen

**Comment by rachelmcr** [comment] 2018-08-28 11:54
I reproduced this issue on a test site, although the resulting HTML is slightly different from what's reported above:

```
<h5 style="text-align: center;"><u>Ocean View Room</u></h5>
<h5 style="text-align: center;">Our Monkey Room contains one King Bed, and has a private balcony overlooking the gardens and beautiful Pacific Ocean.</h5>
<p class="wpview-selection-before"></p>

<div class="wpview-body" contenteditable="false">
<div class="wpview-content wpview-type-gallery"><iframe class="shortcode-frame shortcode gallery-shortcode" src="https://wpcomwidgets.com/render/" width="680" height="0" frameborder="0" sandbox="allow-scripts">[gallery ids="444,503,199" type="rectangular" orderby="rand"]</iframe></div>
</div>
<p class="wpview-selection-after"></p>

<h5></h5>
```

Here's what I see on my site:

![screenshot 2018-08-28 12 47 46](https://user-images.githubusercontent.com/8658164/44721048-97155300-aac0-11e8-8377-249fb4740b34.png)

However, I tested the same issue in the Gutenberg editor on my WordPress.com simple site by editing the same post (in a Classic editor block), and I couldn't reproduce the issue there. The text was converted to the new heading size and the gallery remained unchanged.

Since we will be replacing the current editor with Gutenberg soon, and the issue will be resolved by that, I'm going to go ahead and close this issue.

**Closed by rachelmcr** 2018-08-28 11:54 UTC
Labels: Editor, [Pri] High, [Type] Bug
