### ISSUE TITLE
Purchases: Upgrades added via Store Admin not displaying in Purchases

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#2403] opened 2016-01-14 01:13 UTC
Originally reported by @joelwills.

Manually adding an upgrade to a user (using admin tools) is done often by Support Staff if the user makes a manual payment or wants a specific change. However the upgrade then does not display in My Purchases.

Staff can reproduce by manually adding an upgrade such as a domain mapping. The upgrade won't appear in the list in /purchases (and it is labeled as Free Trial in the admin tools).

If using WordPress.com credits instead, the upgrade will appear in /purchases but not if renewal date is within 30 days.

This might be a server side issue, and needs some investigation.

cc @scruffian

**Comment by fabianapsimoes** [comment] 2016-03-07 15:01
> Staff can reproduce by manually adding an upgrade such as a domain mapping. The upgrade won't appear in the list in /purchases (and it is labeled as Free Trial in the admin tools).

I can't reproduce this. @joelwills is anything missing from this report for us to reproduce this? Specific instructions would help a lot.

**Comment by joelwills** [comment] 2016-03-07 18:48
@fabianapsimoes I can no longer recreate either. Looks like it has been fixed/no longer occurs :)

**Comment by fabianapsimoes** [comment] 2016-03-07 19:04
I guess that's good news either way :)

I'll close this issue, but please reopen if you run into it again.

**Closed by fabianapsimoes** 2016-03-07 19:04 UTC
Labels: Purchases, [Type] Bug
