### ISSUE TITLE
Non WC Pay Countries are redirected to a blank page when they click on the Add Payments task in the list

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wp-calypso#74841] opened 2023-03-23 13:53 UTC
***Test this from a country outside of the WC Payments coverage***

Click on the "Set up a way to pay" 

If you're in a country supported by WC Pay it will take you to the Stripe gateway setup 

if you're not, it may take you to a blank screen vs the wp-admin screen that suggests other payment gateway options.

**Comment by daledupreez** [comment] 2023-04-24 08:38
@sixhours, I believe this is a duplicate of #75172, which you're already working on in #75642. Could you take a closer look and close one of the issues if this is a duplicate?

**Comment by sixhours** [comment] 2023-04-25 16:05
Yep, this is a duplicate of https://github.com/Automattic/wp-calypso/issues/75172, let's follow up there, or in the linked PR. Closing!

**Closed as completed by sixhours** 2023-04-25 16:05 UTC
