### ISSUE TITLE
Notifications: Youtube Block isn't properly processed

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/wp-calypso#45119] opened 2020-08-21 18:10 UTC
#### Note:
This issue affects both, mention and comment notifications.

#### Scenario: Post Notification
1. Add a new post
2. Insert a Youtube Block
3. Mention **User B**

#### What I expected
Whenever **User B** gets the notification, he should be able to visualize the youtube embed in the Notifications Bar

#### What happened instead
Plain text appears onScreen

#### Browser / OS version
Chrome 84.0.4147.135, macOS Catalina 15.6

#### Screenshot / Video
<img width="300" alt="Screen Shot 2020-08-21 at 15 11 12" src="https://user-images.githubusercontent.com/1195260/90921429-9dddb480-e3c0-11ea-927d-d84b430ee161.png">

#### Context / Source

Sample Content Below!

```
<!-- wp:core-embed/youtube {"url":"https:\/\/www.youtube.com\/watch?v=gEPmA3USJdI","type":"rich","providerNameSlug":"","className":"wp-embed-aspect-16-9 wp-has-aspect-ratio"} -->
<figure class="wp-block-embed-youtube wp-block-embed is-type-rich wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=gEPmA3USJdI
</div></figure>
<!-- /wp:core-embed/youtube -->
```

**Comment by davemart-in** [comment] 2020-09-01 02:20
Thanks! Looks like we got duplicate issues. I'm closing this as a duplicate of: https://github.com/Automattic/wp-calypso/issues/45208

**Closed by davemart-in** 2020-09-01 02:20 UTC

**Comment by jleandroperez** [comment] 2020-09-07 16:28
Thank you Dave!
