### ISSUE TITLE
The comment icon in the Reader post detail screen doesn't do anything

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#93415] opened 2024-08-09 14:31 UTC
### Quick summary

When I click the comment icon, it doesn't do anything

### Steps to reproduce

1. Go to the reader
2. Post any post
3. Click any of the two the comment icons (one on the left and one under the post)

<img width="833" alt="Screenshot 2024-08-09 at 17 27 54" src="https://github.com/user-attachments/assets/98161c73-9d97-4684-89f1-0e5e4a2c7b49">

<img width="232" alt="Screenshot 2024-08-09 at 17 30 40" src="https://github.com/user-attachments/assets/97ab6109-1f25-4e51-96bb-f5aa7740dff0">

### What you expected to happen

See comments or a new comment form

### What actually happened

nothing.

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

### If the above answer is "Yes...", outline the workaround.

The user would need to scroll below the ads and see comments. If they're new, they're unlikely to know what to do.

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Chrome, 13"

**Comment by retnonindya** [comment] 2024-08-11 07:22
📌 REPRODUCTION RESULTS
Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

![Aug-11-2024 15-19-58](https://github.com/user-attachments/assets/869962ed-88df-415c-80da-30b95b2cf1c7)

I checked on Console, and I couldn't find any error. 

📌 ACTIONS
- Triaged

**Comment by lsl** [comment] 2024-08-15 07:10
This condition is being met for some reason:

https://github.com/Automattic/wp-calypso/blob/ddfc11dc39b48f33e0e4d5f4a76d4a417a49e3cd/client/blocks/reader-full-post/index.jsx#L295

Could be that it's getting set on page load instead of after you click.

Other comment buttons on the page aren't working either.

**Comment by BogdanUngureanu** [comment] 2024-08-15 08:27
@lsl The issue has been fixed in https://github.com/Automattic/wp-calypso/pull/93454 (not merged yet, plan to do it today0. 

The problem was that the scrolling was done on the window, however, if you look carefully, the scrollbar is not on the window, but on a custom div (It took me a while until I noticed that :D).

**Comment by lsl** [comment] 2024-08-15 09:06
Ah missed that sorry.

**Comment by dzver** [comment] 2024-08-15 09:17
I wonder, can we also move the 2 related posts below the comment section or remove them?

**Comment by BogdanUngureanu** [comment] 2024-08-15 12:50
Deployed a bugfix with https://github.com/Automattic/wp-calypso/pull/93454. @dzver let me know if you want to make/discuss the related posts changes in the context of this issue. :) Otherwise, feel free to close this one.

**Comment by dzver** [comment] 2024-08-15 14:43
I can create a separate discussion but to answer the question, the comment button is distanced from the comments for no obvious reasons. Do we prefer people to engage with another post rather than comment? We have a lot more page views than we have comments.

**Comment by BogdanUngureanu** [comment] 2024-08-15 15:17
That's a good point, thanks!

**Closed as completed by BogdanUngureanu** 2024-08-15 15:17 UTC
Labels: Bug, [Pri] BLOCKER, [Feature] Reader, [Platform] Simple, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] User Interaction & Engagement
