### ISSUE TITLE
Atomic sites don't have site setup checklist enabled at customer home

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#50523] opened 2021-02-26 11:10 UTC
When creating a new eCommerce site (either via /start or /new onboarding flows), the customer home looks like this:

<img width="1562" alt="Screenshot 2021-02-26 at 12 44 38" src="https://user-images.githubusercontent.com/87168/109292925-c2b15980-7833-11eb-87d0-21fc49ca1085.png">

Other sites have site-setup checklist, with clear indication how to launch their sites:

<img width="1540" alt="Screenshot 2021-02-26 at 12 57 30" src="https://user-images.githubusercontent.com/87168/109292953-cfce4880-7833-11eb-9c42-41498f323aa5.png">

Let's enable this for eCommerce sites as well.

Also if you create regular site but turn it into Atomic by installing plugin before you've finished the checklist, the checklist dissapears.

A good follow-up would be to add a task and link it to WooCommerce onboarding when it hasn't been finished:

<img width="1560" alt="Screenshot 2021-02-26 at 12 46 27" src="https://user-images.githubusercontent.com/87168/109293032-eaa0bd00-7833-11eb-8064-7e1d413ae902.png">

**Comment by razvanpapadopol** [comment] 2021-02-26 14:37
> Other sites have site-setup checklist, with clear indication how to launch their sites: 

This may be something caused by the monthly plan renewal card showing up and not directly related to eCommerce plan. Have you tried also purchasing an annual eCommerce plan? 

Related Slack thread: p1614084130027200-slack-CT1FP5D62

**Comment by simison** [comment] 2021-03-01 09:49
@razvanpapadopol for eCommerce plan the checklist is hidden also with annual plans:

<img width="1665" alt="Screenshot 2021-03-01 at 11 47 58" src="https://user-images.githubusercontent.com/87168/109480352-17e3aa00-7a84-11eb-9833-82b5307e1919.png">

**Comment by simison** [comment] 2021-04-05 21:43
Seems to be the same for all atomic sites, also on business plan.

**Comment by creativecoder** [comment] 2021-04-05 23:49
Related issues, possibly duplicates: https://github.com/Automattic/wp-calypso/issues/42495 and https://github.com/Automattic/wp-calypso/issues/51119

**Comment by creativecoder** [comment] 2021-04-05 23:54
A couple of technical notes:

Something seems to mark the site launch task complete when the site goes Atomic

<img width="765" alt="Screen Shot 2021-04-05 at 18 51 39" src="https://user-images.githubusercontent.com/1699996/113640032-294e4200-9640-11eb-974b-3e9acf7ae773.png">

Additionally, there's still at least some code that gates the checklist to Atomic sites: `\Onboarding_Checklist\is_blog_eligible_for_dotcom_checklist` returns false for Atomic sites.

**Comment by autumnfjeld** [comment] 2021-05-06 06:25
This ticket should be discussed in collaboration with My Home Pod & Simple to Atomic Parity Pod 
cc: @tjcafferkey

**Comment by roo2** [comment] 2021-05-07 01:57
We originally limited the checklist to simple sites in D41072-code the reason given was that "checklists don't fully work at the moment" in atomic. I'll take a look at what is not working on atomic sites, but it would be good to re-afirm that this is still a priority to fix, knowing that it was disabled explicitly @simison .

**Comment by roo2** [comment] 2021-05-07 03:18
I enabled the checklist on atomic sites and tested it, there were quite a few issues:

Site created -> seems to work ✅ 
Name your site -> seems to work ✅ 
Update your homepage -> The link takes us to `wp-admin/edit.php` without a page selected ❌ 
Edit the site menu -> link works, but after editing the main menu, the task does not disappear.  ❌ 
Launch status -> seems to show launched before site is launched ❌ 
Confirm your email address -> seems to work ✅ 
Get the Wordpress app -> seems to work ✅ 

I imagine there will be some more issues that I didn't find

So it seems that there is still quite a bit of work to do in order to get the launch checklist working on atomic sites.

**Comment by simison** [comment] 2021-05-07 08:01
>  I'll take a look at what is not working on atomic sites, but it would be good to re-afirm that this is still a priority to fix, knowing that it was disabled explicitly

@roo2 I think the experience of it disappearing is quite jarring and lack of it on eCommerce is hurting us, so I'd definitely look at the underlying bugs and look at how much work it would be to fix those things. It seems like technical debt that the previous team decided to take in order to ship earlier, but it could be time to pay it back. Worth checking with them.

All that said, do prioritize this with Jeff and in accordance with other bugs to fix as well. It's easy for me to just say "it's important" without knowing what else there is or how much effort this is. :-)

If the menu task is a lot of work to fix, it might make sense to look at alternative guidance instead and remove it as a task, as we talked about in https://github.com/Automattic/wp-calypso/issues/47334#issuecomment-831050475

**Comment by roo2** [comment] 2021-05-10 11:45
Thanks @simison, I raised subtasks for the three not working tasks and spent some time investigating the code to see if there are other things that might be broken.

There are other possible onboarding tasks defined, but it appears that only the 7 that I mentioned before can be shown on the onboarding checklist 👍 

[Update your homepage task](https://github.com/Automattic/wp-calypso/issues/52705)
[Launch your site task](https://github.com/Automattic/wp-calypso/issues/52707)
[Edit the site menu task](https://github.com/Automattic/wp-calypso/issues/52706)

We'll estimate these tasks and prioritize them with Jeff 👍 

( Also, there seems to be special logic to serve woocomerce sites a different checklist, we'll have to check that this checklist is working too. ☑️ )

cc @autumnfjeld

**Comment by simison** [comment] 2021-06-21 07:32
@autumnfjeld is this issue good to close?

**Comment by autumnfjeld** [comment] 2021-06-21 07:50
@simison I believe it is! 🥳   I think  @deBhal  shipped the last bits related to the "Edit menu" check list item on Friday. I'll let he and @roo2 do the honors of closing this ticket (we have Ganon session tomorrow where we review/tidy our [git board](https://github.com/orgs/Automattic/projects/252)). :) And then we'll send out the 🚢  SHIPPED IT 🚢  post.

**Comment by deBhal** [comment] 2021-06-22 01:12
D63125-code will fix this issue when it's deployed.

**Comment by deBhal** [comment] 2021-06-23 04:10
Fixed in D63125-code

**Closed as completed by deBhal** 2021-06-23 04:10 UTC
Labels: Enhancement, Task, Plans: eCommerce, [Feature] My Home, WooCommerce, Simple/Atomic Parity, My Home Pod
