### ISSUE TITLE
People: Email Followers aren't shown is the Stats module is disabled on a Jetpack site

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/wp-calypso#11333] opened 2017-02-10 18:26 UTC
If the Stats module is disabled on a Jetpack site, then the Email Followers aren't available in the People section of Calypso and the following error is returned from the `followers` API call:

`{"code":404,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"invalid_blog","message":"This blog does not have the Stats module enabled"}}`

Related Automattic/jetpack#237

**Comment by jeherve** [comment] 2017-02-10 21:06
Closing as duplicate of #11308

**Closed by jeherve** 2017-02-10 21:06 UTC
Labels: Jetpack, People Management, [Type] Bug
