### ISSUE TITLE
CoBlocks Galleries: Cannot make captions hyperlinked, bold, italic

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#50303] opened 2021-02-20 09:39 UTC
### Steps to reproduce the behavior

1. Add a CoBlocks Gallery Block (Stacked or Masonry for example) with a few images
2. Toggle on the caption feature in the right sidebar and type in a caption for one of the images
3. Select the caption
4. See no toolbar appearing
5. Switch to a different tab and come back
6. See the toolbar appear 
![](https://d.pr/i/8LIVom+)
_Link: https://d.pr/i/8LIVom_
7. Try to click any button (Bold, Italic, Link)

#### What I expected to happen
1. Toolbar to be displayed when any text is selected
2. Clicking Bold, Italic, Link in the toolbar should do the related action
#### What actually happened
1. Toolbar not displayed when any text in the caption is selected
2. Clicking Bold, Italic, Link in the toolbar does nothing
### Context
Reported by the user in 3739629-zen
#### Browser / OS version
Chrome 88 on macOS Big Sur 11.1
#### Is this specific to the applied theme? Which one?
No
#### Does this happen on simple or atomic sites or both?
Simple
#### Is there any console output or error text?
```
Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at setAriaExpanded (??-eJytVNlWwjAQ/SFDQEDhweO3pEkIg9nM0pa/d9KAIkv1iOf0obPcOzO3M6WdJ2C5zkJGusPnPcuwpxmoCEwp1mg5MWAnu/hAR1Kd9+epTKBR8joQSqZ4GuPOJmkT9TorsJGqjGYjgyKd586c28gliJECGOHBxUhcAMSRDegkwy3STdaaREiSIDKBVaRG6HI1XU0Xy+mSIrdxlgqI6fB+B5nSrmGYlPYaBRo4v7n+OjwyFW1Jox1/QytInlzY/9PYgiWGDbrwmwY5ptF2PVlP5rTJoAW1uadghezvaKeOWccrSS6QQju0dz32z8VYiyAhGxZuF/3Kuaf4lqVIrOwOdY7mxc3EFtEM7JX1NpkcKxoWMaG0PQDxRGw+eT1H1sgRfLys4sOPnwjzcNVJfHD9xbpdI0uBoWI1UnW7GRinq7cue69x4QKuJ+o0okMFFx0+Faklx0CH31JR2+QIHANsfyn3T3NupfY33CPFVcgWnB1CjCeyccGUTg7b1sKwE6/mZfY0mz8/Lpaz9e4DRNIX4w==:375)
    at HTMLDocument.init (??-eJytVNlWwjAQ/SFDQEDhweO3pEkIg9nM0pa/d9KAIkv1iOf0obPcOzO3M6WdJ2C5zkJGusPnPcuwpxmoCEwp1mg5MWAnu/hAR1Kd9+epTKBR8joQSqZ4GuPOJmkT9TorsJGqjGYjgyKd586c28gliJECGOHBxUhcAMSRDegkwy3STdaaREiSIDKBVaRG6HI1XU0Xy+mSIrdxlgqI6fB+B5nSrmGYlPYaBRo4v7n+OjwyFW1Jox1/QytInlzY/9PYgiWGDbrwmwY5ptF2PVlP5rTJoAW1uadghezvaKeOWccrSS6QQju0dz32z8VYiyAhGxZuF/3Kuaf4lqVIrOwOdY7mxc3EFtEM7JX1NpkcKxoWMaG0PQDxRGw+eT1H1sgRfLys4sOPnwjzcNVJfHD9xbpdI0uBoWI1UnW7GRinq7cue69x4QKuJ+o0okMFFx0+Faklx0CH31JR2+QIHANsfyn3T3NupfY33CPFVcgWnB1CjCeyccGUTg7b1sKwE6/mZfY0mz8/Lpaz9e4DRNIX4w==:381)
setAriaExpanded @ ??-eJytVNlWwjAQ/SFDQEDhweO3pEkIg9nM0pa/d9KAIkv1iOf0obPcOzO3M6WdJ2C5zkJGusPnPcuwpxmoCEwp1mg5MWAnu/hAR1Kd9+epTKBR8joQSqZ4GuPOJmkT9TorsJGqjGYjgyKd586c28gliJECGOHBxUhcAMSRDegkwy3STdaaREiSIDKBVaRG6HI1XU0Xy+mSIrdxlgqI6fB+B5nSrmGYlPYaBRo4v7n+OjwyFW1Jox1/QytInlzY/9PYgiWGDbrwmwY5ptF2PVlP5rTJoAW1uadghezvaKeOWccrSS6QQju0dz32z8VYiyAhGxZuF/3Kuaf4lqVIrOwOdY7mxc3EFtEM7JX1NpkcKxoWMaG0PQDxRGw+eT1H1sgRfLys4sOPnwjzcNVJfHD9xbpdI0uBoWI1UnW7GRinq7cue69x4QKuJ+o0okMFFx0+Faklx0CH31JR2+QIHANsfyn3T3NupfY33CPFVcgWnB1CjCeyccGUTg7b1sKwE6/mZfY0mz8/Lpaz9e4DRNIX4w==:375
init @ ??-eJytVNlWwjAQ/SFDQEDhweO3pEkIg9nM0pa/d9KAIkv1iOf0obPcOzO3M6WdJ2C5zkJGusPnPcuwpxmoCEwp1mg5MWAnu/hAR1Kd9+epTKBR8joQSqZ4GuPOJmkT9TorsJGqjGYjgyKd586c28gliJECGOHBxUhcAMSRDegkwy3STdaaREiSIDKBVaRG6HI1XU0Xy+mSIrdxlgqI6fB+B5nSrmGYlPYaBRo4v7n+OjwyFW1Jox1/QytInlzY/9PYgiWGDbrwmwY5ptF2PVlP5rTJoAW1uadghezvaKeOWccrSS6QQju0dz32z8VYiyAhGxZuF/3Kuaf4lqVIrOwOdY7mxc3EFtEM7JX1NpkcKxoWMaG0PQDxRGw+eT1H1sgRfLys4sOPnwjzcNVJfHD9xbpdI0uBoWI1UnW7GRinq7cue69x4QKuJ+o0okMFFx0+Faklx0CH31JR2+QIHANsfyn3T3NupfY33CPFVcgWnB1CjCeyccGUTg7b1sKwE6/mZfY0mz8/Lpaz9e4DRNIX4w==:381

```
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Medium
#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/39308239/108591185-17565f80-7370-11eb-8341-62c1b2198d78.mov

**Comment by WunderBart** [comment] 2021-04-19 14:15
Duplicate of https://github.com/Automattic/wp-calypso/issues/49950

**Closed as completed by WunderBart** 2021-04-19 14:15 UTC
Labels: Bug, Blocks, Triaged, [Feature] CoBlocks
