### ISSUE TITLE
Shift + letter in middle of domain search string sends cursor to end of string

### ISSUE THREAD

**Issue by cathymcbride** [Automattic/wp-calypso#48225] opened 2020-12-10 16:42 UTC
#### Steps to reproduce

starting from https://wordpress.com/start/domains
in the domain box, type “aaaa”
move your insertion point to the beginning of the string (or anywhere inside the string) > type “BBBB”

expected: bbbbaaaa (I'm assuming the change of case is expected)

actual: baaaabbb – the cursor pops to the end of the string after the first character is typed

**Comment by klimeryk** [comment] 2021-04-21 13:20
Can't reproduce it anymore - might have gotten fixed by https://github.com/Automattic/wp-calypso/pull/51718.

**Closed as completed by klimeryk** 2021-04-21 13:20 UTC
Labels: Bug, [Pri] Normal, [Feature Group] Emails & Domains
