### ISSUE TITLE
Confirmation Email Message Not Saving 

### ISSUE THREAD

**Issue by freelylovinglife** [Automattic/wp-calypso#74932] opened 2023-03-26 22:43 UTC
### Quick summary

When user attempts to update the "Confirmation email message" under settings and reading, it does not save the changes after hitting save settings button.  ZD- 6064076

### Steps to reproduce

1. Go to Settings-Reading
2. Change message under Confirmation email message
3. Hit Save Sittings
4. Attempt to navigate away from page. 
5. A message displays that You have unsaved changes. Are you sure you want to leave this page?

<img width="712" alt="Screen Shot 2023-03-26 at 6 41 07 PM" src="https://user-images.githubusercontent.com/76487565/227809309-636e0660-c81b-429f-b2e1-b3a8e3a31519.png">

### What you expected to happen

Once changes have been made and you choose save settings, changes should be reflected. 

### What actually happened

Changes are not reflected and when navigating away from the page, it states that there is unsaved content. 

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by worldomonation** [comment] 2023-03-28 01:24
I attempted to reproduce this on Firefox Nightly 113.0a1 (2023-03-26) (64-bit) and macOS Ventura 13.2.1.

I was not able to reproduce this issue. Tried it on multiple test sites with various WordPress.com plans enabled. 
 - Premium
 - Free
 - Business

See video:

https://user-images.githubusercontent.com/6549265/228102644-552e9ce3-ff74-4474-b77b-3f63fdbf4952.mov

**Comment by worldomonation** [comment] 2023-03-28 01:27
I was able to cause the `You have unsaved changes. Are you sure you want to leave this page?` message from Firefox, but it was triggered by making a change on the same page **but on another section** (eg. toggling one of the options under Site Settings), changing the message, then clicking "Save settings" button located in the text field section.

However, even after dismissing the warning and choosing to navigate away from the page, the changes made in the email message still remained, so ultimately I was not able to reproduce the issue.

Returning issue to author for further investigations.

**Comment by syhussaini** [comment] 2023-03-29 02:23
* I was able to reproduce the issue on the user's site - https://d.pr/i/CUNvj5
* I could not reproduce the same on my test site with the same Plan - https://d.pr/i/LvZx9y
* I activated the same theme as the user's site `Baskerville 2` and retested, but couldn't reproduce the issue - https://d.pr/i/lRwNJE

**Comment by cuemarie** [comment] 2023-03-29 03:11
📌 SCRUBBING
 I also tried replicating in a test environment and could not.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- Hey @syhussaini ! Since this is only replicable on one user's site, it'd be best to report this internally here instead: 2EDhh-p2

Also, please always make sure to exclude any user-specific information in your screenshots or details, even those linked.
- [ ] Please edit the report/comment above to use remove user-specific information. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.

**Comment by mashikag** [comment] 2023-04-11 10:10
I am re-openning this issue. This is a real issue. The issue affects any site that has more than two sub-properties in its `subscription_options` site option.

For a bit more-in-depth explanation of the issue, let's consider any brand new WPCOM site. Such site will have a site option named `subscription_options`. The site option is responsible for storing the value of the **Confirmation email message** and the **Comment follow email message**. Such site option value may look as the following:
```json
"subscription_options": {
  "invitation": "Howdy,\nYou recently subscribed to <a href='%1\$s'>%2\$s</a> and we need to verify the email you provided. Once you confirm below, you'll be able to receive and read new posts.\n\nIf you believe this is an error, ignore this message and nothing more will happen.",
  "comment_follow": "Howdy.\n\nYou recently followed one of my posts. This means you will receive an email when new comments are posted.\n\nTo activate, click confirm below. If you believe this is an error, ignore this message and we'll never bother you again."
}
```

However some already existing sites may include some of ours legacy values in their "subscription_options" site option, such as "loggedoutfollow" for example:
```json
"subscription_options": {
  "loggedoutfollow" : "on",
  "invitation": "Howdy,\nYou recently subscribed to <a href='%1\$s'>%2\$s</a> and we need to verify the email you provided. Once you confirm below, you'll be able to receive and read new posts.\n\nIf you believe this is an error, ignore this message and nothing more will happen.",
  "comment_follow": "Howdy.\n\nYou recently followed one of my posts. This means you will receive an email when new comments are posted.\n\nTo activate, click confirm below. If you believe this is an error, ignore this message and we'll never bother you again."
}
```
Such sites with any extra key-value pairs in its `subscription_options` site options, are currently affected, and unable to modify their values for the email messages via Reading Settings, with no workarounds available. I have created a PR that is addressing this issue: https://github.com/Automattic/jetpack/pull/30026

**Closed as completed** 2023-04-12 10:54 UTC
Labels: Bug, [Pri] Normal, Triaged, [Closed] Not Reproducible

**Comment by mashikag** [comment] 2023-04-12 10:56
The [fix](https://github.com/Automattic/jetpack/pull/30026) was now merged to the trunk.

We can expect it to go out to prod with the next jetpack release, which I believe is scheduled for: May 2, 2023.
