### ISSUE TITLE
Adventurer theme: Alignment issues in the post editor

### ISSUE THREAD

**Issue by vinnykaur** [Automattic/wp-calypso#78516] opened 2023-06-22 05:46 UTC
### Quick summary

The post editor is not aligned properly. All of the text is left aligned and there's no margin.
This happens when the Adventurer theme is active.

### Steps to reproduce

1. Activate the Adventurer theme.
2. Add a new post or edit an existing post.
3. Notice how the post displays in the editor.

### What you expected to happen

The post should be aligned properly.

### What actually happened

Everything in the editor is left aligned and there's no margin.

Screenshot from the user's site:

![qmGYok.png](https://github.com/Automattic/wp-calypso/assets/49183855/48db0377-7444-4693-bae4-df9e5837c491)

Screenshot from my test site:

![LxXaHH.png](https://github.com/Automattic/wp-calypso/assets/49183855/180f8d51-3169-461d-88cb-4bf31e9c26b8)

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

The editor looks okay if we align everything within a group block. 

Screenshot:

![pEgRsj.png](https://github.com/Automattic/wp-calypso/assets/49183855/755ec272-18cd-4daf-8818-c27a8c470a6a)

**Comment by vinnykaur** [comment] 2023-06-22 07:07
Follow up ticket at zen-6453579

**Comment by cuemarie** [comment] 2023-06-22 23:16
Duplicate of:

- https://github.com/Automattic/wp-calypso/issues/78473

**Closed as not planned by cuemarie** 2023-06-22 23:16 UTC
Labels: Bug, [Pri] Low, [Platform] Simple, [Platform] Atomic
