### ISSUE TITLE
Wix importer: AT site shows error when trying to import

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/wp-calypso#78245] opened 2023-06-15 10:54 UTC
### Quick summary

Atomic site that is not launched will show an error when trying to import using the Wix importer. It also seems to (sometimes) affect launched sites.

Additionally, it seems to consistently show a 403 on AT sites when previewing the site as a thumbnail. Similar to [this issue.](https://github.com/Automattic/wp-calypso/issues/45586#issuecomment-1558265881)

### Steps to reproduce

1. Start at any AT site that is unlaunched (check in Blog RC to make sure it isn't)
2. Try to import from a Wix site, using the new expanded list of importers (context pcmemI-BQ-p2) [from here](https://github.com/Automattic/wp-calypso/issues/54149#issuecomment-1132561674)
3. Wait for the error 

### What you expected to happen

The site should import.

### What actually happened

Error:

>500 status code for "POST /sites/[BLOG ID]/site-importer/import-site?engine=wix

![image](https://github.com/Automattic/wp-calypso/assets/36608681/c7710bd1-c325-4ba2-8b2e-ec29dfa075fa)

I tested on my public noindex AT site and the import worked as I'd expect.
I set my AT site to private, and received this error instead:

>It looks like we're unable to reach that website address at this time. (ID: f43cabdf-8254-495d-9584-e6ea5bc610ba)

Additionally, screenshot of the 403 on my AT site:
<img width="1259" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36608681/d1711deb-58d8-4859-a9fc-8a40f7c30b16">

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

The workaround should be simple: set the site to public in order to import.
I tested on my public noindex AT site and the import worked as I'd expect.

**Comment by worldomonation** [comment] 2023-06-16 05:31
📌 REPRODUCTION RESULTS
Tested on Simple – not reproducible, import successful
Tested on Atomic – 
Replicable outside of Dotcom – not applicable

📌 FINDINGS/SCREENSHOTS/VIDEO
**AT site** - is unlaunched
<img width="1322" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/e00d9fac-98bd-4e16-a4cd-7d26e8bfad3b">

**Importing**
<img width="1322" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/47c1fc1c-1715-4f1b-92e4-347881fb17ca">

Network request:
```
https://public-api.wordpress.com/wpcom/v2/sites/220213165/site-importer/import-site?engine=wix&_envelope=1

{
	"body": {
		"code": 1000002,
		"message": "It looks like we're unable to reach that website address at this time. (ID: ef9a18c2-d704-4d51-a1c3-d3f1a0aa36b8)",
		"data": null
	},
	"status": 500,
	"headers": {
		"Allow": "POST"
	}
}
```

📌 ACTIONS
- assign High priority.
- move to Caribou column.

📌 NOTE

Feel free to use the Wix site https://me52881.wixsite.com/my-site to test the import.

**Comment by cuemarie** [comment] 2023-06-23 02:50
Escalated with @Automattic/caribou here: p1687488633273859-slack-C01A60HCGUA

**Comment by cuemarie** [comment] 2023-10-10 21:28
📌 ACTIONS
- Due to the age of this issue, I've downgraded the priority from `High` to `Normal` to better reflect its status in the larger context of open bugs in this repo.
- Noting that this is a consequence of this larger issue:
     - https://github.com/Automattic/wp-calypso/issues/45586

**Comment by davemart-in** [comment] 2024-10-16 19:44
Single instance report back in 2023. No additional reports from customers. It's been a while since there were any updates. Going to close this out, but happy to open it back up if additional reports come in.

**Closed as not planned by davemart-in** 2024-10-16 19:44 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Atomic, [Product] WordPress.com, [Feature Group] Developer & Contractor Tools, [Feature] Importing & Exporting
