### ISSUE TITLE
Free Atomic: Google Analytics Restriction

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#51592] opened 2021-03-31 15:52 UTC
### What plan tier is the site on?
Free

### Where are you seeing the issue?

Tools > Marketing features > Traffic 

#### What I expected on the Atomic site
To not have access to the Google Analytics feature as a Free Atomic site. 
![image](https://user-images.githubusercontent.com/7129409/113173469-65843b80-9217-11eb-8c4b-e9e94b25f44d.png)

#### What actually happened
The feature is available 
![image](https://user-images.githubusercontent.com/7129409/113173515-76cd4800-9217-11eb-923d-701069d5ab0d.png)

**Comment by mmtr** [comment] 2021-05-27 10:07
I wonder if we can close this as duplicate of https://github.com/Automattic/wp-calypso/issues/51828? cc @allilevine

**Comment by allilevine** [comment] 2021-05-27 18:17
> I wonder if we can close this as duplicate of #51828?

Yep looks like it. Closing 👍

**Closed as completed by allilevine** 2021-05-27 18:17 UTC
Labels: [Pri] Normal, Task, [Feature Group] A8C Marketing & Sales, Triaged, Simple/Atomic Parity, [Plan] Free
