### ISSUE TITLE
Scrolling is broken occasionally

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#35305] opened 2019-08-12 15:00 UTC
#34829 ## Steps to reproduce
N/A happens periodically when I was blogging and looking a list of my blog posts, but a screen refresh causes it to go away.

#### What I expected
I expected to be able to scroll, but I can't.

#### Steps to reproduce

Approach 1:

1. Open the block editor: https://wordpress.com/block-editor/post/
2. Select a site to create a new post.
3. Click the back arrow in the top left to exit the editor.
4. Try to scroll the posts list, or navigate to another Calypso screen and try to scroll. Notice that it doesn't scroll.
5. Refresh the page. Notice that it scrolls now.
6. Click the Write button in the master to open the block editor again.
7. Click the back arrow in the top left to exit the editor.
8. Try to scroll the posts list. Notice that it scrolls now.

Approach 2:

1. Select one of my posts in the Reader
2. Edit the post from the Reader view
3. Update the post
4. I am unable to scroll on any page in Calypso until I refresh.

In both cases, the `is-iframe` class is added to the `html` tag and isn't removed after closing the block editor. This CSS disables scrolling when that class is present:

https://github.com/Automattic/wp-calypso/blob/39efb82641b89aec78018435e5c13fafda1b1610/client/gutenberg/editor/style.scss#L81-L83

#### Browser / OS version
Latest chrome running on a mac.

**Comment by sarahfg** [comment] 2019-08-25 20:47
I see this same issue looking at any Calypso pages were scrolling in necessary. The issue is resolved by a refresh. This happens on both the latest Chrome and Safari browsers. I run into this daily in my 1:1 concierge screenshare sessions with users.
Example pages include
https://wordpress.com/view/
https://wordpress.com/settings/general/
https://wordpress.com/marketing/sharing-buttons/

**Comment by rachelmcr** [comment] 2019-08-28 18:54
I consistently see this after publishing posts on a site where my workflow is to open the editor first via the editor URL. It doesn't happen after using the classic Calypso editor, or if I start elsewhere in Calypso first and _then_ open the editor.

Here are steps to repro:

1. Open the block editor: https://wordpress.com/block-editor/post/
2. Select a site to create a new post.
3. Click the back arrow in the top left to exit the editor.
4. Try to scroll the posts list, or navigate to another Calypso screen and try to scroll. Notice that it doesn't scroll.
5. Refresh the page. Notice that it scrolls now.
6. Click the Write button in the master to open the block editor again.
7. Click the back arrow in the top left to exit the editor.
5. Try to scroll the posts list. Notice that it scrolls now.

(Tested with Chrome 76.0.3809.100 / macOS 10.14.5.)

**Comment by katiebethbrown** [comment] 2019-08-29 00:04
This happened to me when working on my personal site. I was editing Categories under Settings > Writing > Categories. The list of Categories scrolled fine at first but just stopped working. I didn't see any errors in the console, and refresh returned the scroll-ability.

**Comment by wpericam** [comment] 2019-08-29 00:05
User couldn't scroll on Themes Showcase page past the third row (design > Customize > CSS). I had them refresh to fix. But they came to chat with the issue, so it's worth looking into. 

13115223-hc

**Comment by wpericam** [comment] 2019-08-29 00:08
Another user (within an hour of the one above) who couldn't scroll on the Themes page. Same situation, fixed with a refresh but they came to chat. 

14858336-hc

**Comment by rachelmcr** [comment] 2019-08-29 10:01
At least in the case I observed, this behavior seems to be related to the fix in https://github.com/Automattic/wp-calypso/pull/30530 to remove extra scrollbars in the Gutenberg iframe. cc @gwwar

**Comment by jerrysarcastic** [comment] 2019-09-04 23:30
I had a site owner report this issue in #15031370-hc where Calypso pages would not scroll in Chrome, but worked fine in Safari.  They left before I could confirm if a refresh fixed the issue, but wanted to report here to be safe.

**Comment by aleone89** [comment] 2019-09-06 11:56
There's another report of this in hc-10093458 - in this case the user was using chrome ( http://prntscr.com/ot3a84 ) but I noticed the user had extensions running as well..

**Comment by MindyPostoff** [comment] 2019-09-24 18:59
Another report in 2375859-zen

User explained the issue only ever appears in Chrome.

**Comment by zandyring** [comment] 2019-10-08 13:38
I'm able to reproduce this (cannot scroll on any page) by following the steps below:

1. Select one of my posts in the Reader
2. Edit the post from the Reader view
3. Update the post
4. I am unable to scroll on any page in Calypso until I refresh.

Chrome 77.0.3865.90 and macOS 10.14.6

**Comment by rachelmcr** [comment] 2019-10-08 14:25
I confirmed I can reproduce the issue with @zandyring's steps and the scrolling issue has the same underlying cause. The `is-iframe` class is added to the `html` tag and uses this CSS to disable scroll (even after the editor is closed):

https://github.com/Automattic/wp-calypso/blob/39efb82641b89aec78018435e5c13fafda1b1610/client/gutenberg/editor/style.scss#L81-L83

I added both sets of steps to reproduce and these details to the issue description, for easy reference.

**Comment by tanjoymor** [comment] 2019-10-10 04:46
I run into this often on my own sites and had a user report it as well: #15818726-hc #2411510-zen followup.

**Comment by MaxPhilip** [comment] 2019-10-14 16:13
Another report in 2408201-zen

**Comment by wpericam** [comment] 2019-10-19 20:01
Another report after clicking back button. Refresh fixed it. 15804202-hc

**Comment by Aurorum** [comment] 2019-10-26 13:26
Another approach to reproducing this instead of entering from the Reader is by clicking an "Edit" button directly on a blog itself (then updating the post).

**Comment by gwwar** [comment] 2019-10-29 23:14
As folks noted the `is-iframe` class isn't being removed consistently. We may need to find a more robust integration implementation, depending on the reason. Related code is in https://github.com/Automattic/wp-calypso/blob/3194f7ed3a6108ec74cb8164b4b90566f7fbc5f8/apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js#L538

And see prior example with hardening the trash post action: https://github.com/Automattic/wp-calypso/pull/34855

**Comment by AtrumGeost** [comment] 2019-11-17 14:55
Got a user who reported they are not seeing the scroll bar: 2468960-zen

Confirmed it is only missing in Chrome:

![Screen Shot on 2019-11-17 at 09:53:52](https://user-images.githubusercontent.com/3696121/69009092-2dc96c00-0920-11ea-82d7-2087ca166b04.png)

Other browsers like Safari or Firefox, hide it and then display it when you want to scroll:

![Screen Shot 2019-11-17 at 09 54 37](https://user-images.githubusercontent.com/3696121/69009104-57829300-0920-11ea-9242-fe122d1353cc.png)

**Comment by khristiansnyder** [comment] 2019-11-17 18:21
I have another user on 2498179-zen that reported scrolling broken when viewing their site on the front-end, clicking the Edit button in the bottom right toolbar, and then clicking to go back to the Pages section of Calypso. 
I can replicate this on my site as well. Both cases were in Chrome:

![Screen Capture on 2019-11-17 at 10-18-17](https://user-images.githubusercontent.com/41035049/69011840-ada50580-0923-11ea-82d8-f04b1ea9bb3c.gif)

**Comment by apeatling** [comment] 2019-11-22 19:39
This came up on a recent test also. Adding to experience issues milestone.

**Comment by rickybanister** [comment] 2019-11-22 20:19
To add a note that's more pressing, this bug appeared in our test while the customer was on the plans page considering a purchase, but he couldn't scroll down to see all the features. We cannot let bugs like this sit for three months.

**Comment by ktyfuller604** [comment] 2019-11-24 17:29
Adding another report - #16848425-hc

**Closed** 2019-11-25 15:01 UTC
Labels: [Pri] BLOCKER, [Type] Bug

**Comment by apeatling** [comment] 2019-11-25 19:39
Thanks for working on this @jblz!
