### ISSUE TITLE
User is getting posts re-shared on social media when editing it - Starter plan

### ISSUE THREAD

**Issue by helenaartmann** [Automattic/wp-calypso#85837] opened 2023-12-28 17:32 UTC
### Quick summary

This user is on the Starter plan, and they set up two social media to get their posts published: LinkedIn and Mastodon. They returned to old posts to edit tags, etc, and the posts were re-shared automatically to their social media channels, even with the sharing options turned off. 

### Steps to reproduce

1. Go to posts
2. Click on edit any blog posts
3. Update the post and it will be shared on social media - as per the user's email:  I'd just like to share that I just published a new post to my blog and this time turned off the sharing options under the Jetpack sidebar menu (screenshot), but the new post still got shared to Mastodon and LinkedIn!

### What you expected to happen

The posts shouldn't be re-shared. 

### What actually happened

The posts are shared even when sharing is disabled and despite being on Starter plan. 

<img width="303" alt="Screenshot 2023-12-28 at 9 14 20 AM" src="https://github.com/Automattic/wp-calypso/assets/72891246/8f125bfd-1577-41fa-b07a-d181124b1b22">

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by liviopv** [comment] 2023-12-29 17:17
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Post editing
https://github.com/Automattic/wp-calypso/assets/14153300/b265fbbd-6abe-46c4-ad1f-6e0a28dd16f3

No post shared to https://mastodon.social/@liviopv

📌 ACTIONS
- Requested author feedback
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@helenaartmann I was not able to replicate and the Starter plan doesn't even allow for re-sharing posts - that's only available on Explorer/Premium and above.

Since this affects only one person, it'd be important to share the interaction link so we can review to confirm.

Please reopen if you can reproduce it yourself on a test site or on the user's site if they allow you to - otherwise, there's not enough to justify keeping this open.

**Closed as completed by liviopv** 2023-12-29 17:17 UTC
Labels: Bug, [Pri] High, [Closed] Not Reproducible, [Platform] Simple, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] User Interaction & Engagement, [Feature] Other Marketing Tools
