### ISSUE TITLE
Allow self purchased premium theme deletion

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#27810] opened 2018-10-12 10:10 UTC
As of now, users who wish to delete their site can't if they have a premium theme that they once purchased for their site. To delete their site, they first need to contact us so we can manually remove the site from the SA.

I'm hoping we can add a self-deletion option in Me > Manage Purchases.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/themes/
2. With some credits, purchase a premium theme for a free site.
3. Go to My Site > Settings > General > Delete site to delete the site. You'll be prompted with a message preventing you from deleting the site:
<img width="712" alt="capture d ecran 2018-10-12 a 12 06 40" src="https://user-images.githubusercontent.com/16645645/46863288-4ca12900-ce17-11e8-83b6-82965605e33e.png">
4. Go to Me > Manage Purchases and select the theme upgrade. The theme cannot be canceled and removed:
<img width="761" alt="capture d ecran 2018-10-12 a 12 08 19" src="https://user-images.githubusercontent.com/16645645/46863363-85410280-ce17-11e8-875f-9145afbdb061.png">

#### What I expected
To be able to delete the theme, so I can later delete my site.

#### What I'm suggesting
We could replace the "Renews on" part which isn't necessary (it already says "one-time" in the price box, so it's redundant) with a button to delete the theme. The user would then be prompted with a confirmation box with a message that let them know it can't be undone.

**Comment by melanieharari** [comment] 2018-10-12 17:15
Related: https://github.com/Automattic/wp-calypso/issues/27014

**Comment by melanieharari** [comment] 2018-10-12 17:16
May be the same issue as described here: https://github.com/Automattic/wp-calypso/issues/17012

**Comment by cecilearkay** [comment] 2018-10-12 17:16
Sorry, those didn't come up when I did a search of close/open issues!

**Comment by melanieharari** [comment] 2018-10-12 17:17
No worries! I was just digging through things to see if we're already tracking this somewhere, since it seems important

**Comment by KokkieH** [comment] 2018-10-18 06:18
> May be the same issue as described here: #17012

Technically, this is a duplicate of #9639, but that was closed in favour of #17012 to simply allow deletion of a site with Premium Themes, rather than adding the ability to cancel a premium theme - it's unlikely that someone would want to cancel a premium theme without wanting to delete their site.

Closing this issue as a duplicate, but this is also being worked on in #27917

**Closed by KokkieH** 2018-10-18 06:18 UTC
Labels: Me, Themes, [Type] Enhancement
