### ISSUE TITLE
Editor: Gutenberg image size dropdown is not functioning

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35475] opened 2019-08-16 15:52 UTC
Changing the size of the image via the “Image Size” dropdown does nothing.

https://videopress.com/v/UAxbNZ9k

Can we confirm if this is a Gutenberg regression or something specific to WordPress.com?

**Comment by mmtr** [comment] 2019-08-17 06:13
This issue was already reported in #34969, so I'm closing this as duplicate (I bumped the priority of #34969 to high).

 > Can we confirm if this is a Gutenberg regression or something specific to WordPress.com?

This is specific to WordPress.com, the issue is not reproducible in a self-hosted site.

**Closed by mmtr** 2019-08-17 06:13 UTC
Labels: Editor, [Pri] High, [Type] Bug
