### ISSUE TITLE
Free trials: Mobile styles between 660 and 960 pixels

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#1685] opened 2015-12-16 17:44 UTC
The changes introduced in https://github.com/Automattic/wp-calypso/pull/1565#issuecomment-165108358 don't work well at window sizes between about 660 and 760. One solution to this would be to add a new breakpoint at about 760 pixels, but since this is a big change I wanted to move the discussion to a new issue (this one!). I'll post a follow up PR with a suggestion.

<img width="663" alt="screenshot 2015-12-16 13 37 19" src="https://cloud.githubusercontent.com/assets/275961/11848819/964d5146-a41c-11e5-8ae8-f6868e350949.png">

I'll move forward with this when #1565 is merged.

**Comment by stephanethomas** [comment] 2015-12-17 09:10
I'm not sure we need to introduce a new breakpoint, especially since the length of the text and the description may vary drastically depending on the user's language. This might actually just require some tweaking of the flexbox layout so the `Purchase Now` button moves to the bottom in that case.

**Comment by drewblaisdell** [comment] 2015-12-22 00:14
I spent a bit of time coming up with a solution to this in #1565. The issue with 'Purchase Now' overflowing screenshot above can't be reproduced anymore, and the CTA buttons are all compact now ([screenshot](https://cloudup.com/ciuh_MpKrdI)).

I'm going to close this as fixed. Feel free to open if anyone thinks this fix isn't adequate, but if any issue still exists, I think it is slight enough to belong in the v2 milestone now.

**Closed by drewblaisdell** 2015-12-22 00:14 UTC
Labels: Free Trials, [Type] Bug
