### ISSUE TITLE
Gutenberg: Markdown Footnotes don't work on Simple Sites in Markdown or Classic blocks.

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#33363] opened 2019-05-27 19:54 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post/
2. Add a Classic block.
3. Add text that includes Markdown Footnotes: https://en.support.wordpress.com/markdown-quick-reference/
4. Preview or Publish post. Footnotes are not created.

Also applies to using the Markdown block.
1. Starting at URL: https://wordpress.com/block-editor/post/
2. Add a Markdown block.
3. Add text that includes Markdown Footnotes: https://en.support.wordpress.com/markdown-quick-reference/
4. Preview or Publish post. Footnotes are not created.

#### What I expected
For footnote links to be created.

#### What happened instead
Instead, it's display as plaintext, such as [^1] and [^1]:

Interestingly, on an Atomic site it DOES work in a Classic block. Although in a Markdown block it's still broken.

#### Browser / OS version
Version 74.0.3729.169 (Official Build) (64-bit)

Pop!_OS 18.10

#### Screenshot / Video
![Annotation on 2019-4-1 (2)](https://user-images.githubusercontent.com/10121835/58437350-2a4ed980-808f-11e9-999b-d6ae0e6fc4a9.png)

![Annotation on 2019-4-1 (1)](https://user-images.githubusercontent.com/10121835/58437351-2c189d00-808f-11e9-8c57-138204ff93bb.png)

![Annotation on 2019-4-1](https://user-images.githubusercontent.com/10121835/58437354-2de26080-808f-11e9-8ed7-9d8014c04251.png)

#### Context / Source

12980776-hc

Given the nature of how Markdown Footnotes work, it would be handy if they still worked in other blocks such as Paragraph, barring another option for easily creating Footnote links.

**Comment by bsanevans** [comment] 2020-02-15 00:33
New report here: 2713427-zen

**Comment by rachelmcr** [comment] 2020-02-23 17:57
I just ran into this issue while dogfooding on my blog. It's really confusing especially since the [Markdown quick reference](https://en.support.wordpress.com/markdown-quick-reference/) support doc includes footnote syntax that isn't working.

**Comment by mikeicode** [comment] 2020-05-25 17:59
Requested 20409498-hc 

Also this appears to be related: https://github.com/Automattic/jetpack/issues/11849

**Comment by jeherve** [comment] 2020-05-26 09:31
Closing this as a duplicate of the Jetpack issue @mikeicode mentioned above.

**Closed by jeherve** 2020-05-26 09:31 UTC
Labels: Editor, Editor-Compatibility, [Type] Bug
