### ISSUE TITLE
Editor: word count counts shortcode contents

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#715] opened 2015-11-25 07:20 UTC
I have a post with a gallery. The gallery counts as 3 words!

I thought a picture was supposed to be worth 1000 words?

![screen shot 2015-11-24 at 11 17 28 pm](https://cloud.githubusercontent.com/assets/52152/11390725/ac84e7c0-9301-11e5-94a0-0675f5539524.png)

![screen shot 2015-11-24 at 11 19 04 pm](https://cloud.githubusercontent.com/assets/52152/11390745/cb13bad6-9301-11e5-8b8b-49c9ed3084aa.png)

**Comment by alisterscott** [comment] 2017-05-12 05:36
Confirmed this is still an issue. Since it's low priority (since 2015) I will close this out and we can re-raise if it comes up again.

**Closed by alisterscott** 2017-05-12 05:36 UTC
Labels: Editor, [Pri] Low, [Type] Bug
