### ISSUE TITLE
Dotcom FSE is not activated on Atomic sites after transfer

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#45287] opened 2020-08-31 08:28 UTC
Currently the legacy Dotcom FSE will not be activated on Atomic sites after transfer. I believe that the reason for that is that one of the options that we used to gate activation by is not being transferred correctly from simple sites.

The gating logic is here:

https://github.com/Automattic/wp-calypso/blob/720b5dad4f5217adc9c1de3e2d706b56f6bb7cf9/apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/helpers.php#L52

And I think that `did_insert_template_parts` unexpectedly returns `false` because the corresponding option that it check is not set correctly: `maywood-fse-template-data-v1`.

In general the format of this option is `(theme_slug)-fse-template-data-v1` in case it pops up for other Dotcom FSE supported themes. As a quick workaround, this should be fixable through CLI by adding the option manually:

`wp option add maywood-fse-template-data-v1 true`

The proper code fix should likely include marking this option for transfer in AT code.

cc @donalirl

**Comment by vindl** [comment] 2020-08-31 11:11
cc @noahtallen since you worked on adding the `full-site-editing` option for transfer. Did we ever add the one related to template insertion indicator?

**Comment by noahtallen** [comment] 2020-08-31 18:43
> Did we ever add the one related to template insertion indicator?

No

**Comment by noahtallen** [comment] 2020-08-31 18:43
Closing this as a duplicate of #41825 :)

**Closed by noahtallen** 2020-08-31 18:43 UTC
Labels: [Goal] Full Site Editing, [Type] Bug
