### ISSUE TITLE
Gutenberg: Block Library CSS is missing for logged out users?

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#34932] opened 2019-07-26 21:22 UTC
#### Steps to reproduce
1. Starting at URL: https://iamtakashifreeplan.wordpress.com/2019/07/27/heading-alignment-test/
2. If you're logged in all headings appear as it says.
3. Open the same URL with an incognito window
4. See if the headings alignment.

#### What I expected

All headings appear in the way respects its alignment setting regardless if you're logged in or not.

#### What happened instead

If you're logged out, all headings stay left aligned. 

#### Browser / OS version

Chrome Version 75.0.3770.142, Mac

#### Screenshot / Video

I've tested with Twenty Nineteen, but it's happening with multiple themes. It seems to me the utility class in the block library isn't loaded for logged out users for some reason.

<img width="2557" alt="Screen Shot 2019-07-26 at 22 19 26" src="https://user-images.githubusercontent.com/908665/61982097-95674e80-aff3-11e9-9353-a787a7d9ca72.png">

If I test this in my local install and I can see the CSS class is loaded regardless if I'm logged in or not. I'm using the plugin v6.1.1

![Annotation on 2019-07-26 at 21-15-33](https://user-images.githubusercontent.com/908665/61982128-a2843d80-aff3-11e9-8c39-05e75a4871e9.png)

**Comment by grvrulz** [comment] 2019-07-30 10:31
Reported in 14286000-hc

**Comment by formosattic** [comment] 2019-07-31 04:22
Reported in 14302341-hc

If site has Premium plan, a temporary fix is to add this CSS:

```
.has-text-align-center {
text-align: center;
}
```

**Comment by kwight** [comment] 2019-08-01 19:20
See paYKcK-9S-p2 for more background.

**Comment by Aurorum** [comment] 2019-08-05 08:11
I just published a post and ran into this issue (Harmonic theme)

**Comment by mmtr** [comment] 2019-08-08 06:00
Confirmed this issue is caused by WP.com not loading the Gutenberg plugin if the user has not opted in to the block editor (this includes logged out users).

D31327-code should fix this.

**Comment by KokkieH** [comment] 2019-08-08 07:14
Another case in https://en.forums.wordpress.com/topic/h2-doesnt-remain-centred-with-gutenberg/ - noting here for follow-up once the fix is merged.

**Comment by mmtr** [comment] 2019-08-13 01:39
This issue has been fixed after landing D31327-code. Feel free to reopen it if you still note the missing styles.

**Closed by mmtr** 2019-08-13 01:39 UTC
Labels: [Goal] Gutenberg, [Pri] High, [Type] Bug
