### ISSUE TITLE
Editor: temporary base64 Image embed src does not get replaced with Media Library URL

### ISSUE THREAD

**Issue by mahangu** [Automattic/wp-calypso#16715] opened 2017-07-29 08:33 UTC
After dragging and dropping an Image directly to the Editor's Visual tab text area, if you click through to the HTML tab, the Image's `src` URL is never changed to the correct Media Library URL of the image, even after it completes uploading. The base64 encoded image remains in the Image's `src' attribute.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/ > Blog Posts > Add
2. Make sure you’re on the Visual tab of the Editor.
3. Drag and drop a large (2mb+) Image directly into the Editor’s text area and immediately click the HTML tab of the Editor. 
4. In the HTML tab, you will see the temporary base64 encoding of the image in the `src` attribute, while (I assume) we upload the Image to the Media Library in the background:

<img width="771" alt="28743345-5e05f0ca-7465-11e7-9b09-4d155c0d662e" src="https://user-images.githubusercontent.com/10125810/28743381-2ffbb2b8-7466-11e7-9e24-013b82b860ca.png">

5. Click back to the Visual tab. You will see the Image displayed in the Editor's text area. 

<img width="786" alt="screen shot 2017-07-29 at 1 52 46 pm" src="https://user-images.githubusercontent.com/10125810/28743386-4cecd578-7466-11e7-9ff3-9346a8cec752.png">

6. Go to the HTML tab again. You will still see the base64 encoded image in the `src` attribute, and not the Media Library URL.

7. Hit Publish, and view the Post. The Image will not appear there.

8. Go to the Media Library and notice that the Image was uploaded correctly to the Media Library. It's only that the Image's Media Library URL has not been added to the Image's `src` attribute.

Warning: Step 3 will also likely eat up CPU cycles and make your browser unresponsive for a while.

#### What I expected
No matter what I click on during the Image upload, after it is uploaded, the Image should use its Media Library URL for its `src` attribute.

#### What happened instead
When I clicked through to the HTML tab during upload, the Image retained its base64 encoded `src` attribute, and did not get updated with its Media Library URL after it finished uploading in the background.

#### Browser / OS version
Chrome Version 59.0.3071.115 (Official Build) (64-bit) / Firefox 54.0.1 (64-bit) / Safari 10.0.3 (12602.4.8) on macOS Sierra 10.12.3 (16D30).

This was reported in 3333413-t by a user who ran across this issue when creating new Posts. Please let me know if you need any other information. Thank you!

**Comment by iamgabrielma** [comment] 2019-02-13 08:04
We tend to see recurrent performance problems caused by random base64 content in atomic sites, and this may be very well the reason of them. For example:

- p9F6qB-2pF-p2 
- p9F6qB-2tc-p2
- p9F6qB-25P-p2
- p9F6qB-230-p2
- p9F6qB-1Dm-p2

**Comment by davipontesblog** [comment] 2020-06-09 20:10
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.

**Closed by davipontesblog** 2020-06-09 20:10 UTC
Labels: Editor, Media, [Type] Bug
