### ISSUE TITLE
WooCommerce hung on 'Payments' screen in quick install flow

### ISSUE THREAD

**Issue by janmckell** [Automattic/wp-calypso#65527] opened 2022-07-13 09:25 UTC
### Quick summary

Setting up WooCommerce gets hung up on the Payments setup screen because it can’t load the plugins.

### Steps to reproduce

1. Started at WooCommerce option (in WP dashboard)
2. Began quick WooCommerce install flow
3. At 'Setup payments' the screen hung, since WooCommerce Payments were not installed

### What you expected to happen

I'd be able to set up payment options for WooCommerce.

### What actually happened

The screen just hung..

![Markup on 2022-07-12 at 11:38:18](https://user-images.githubusercontent.com/84089207/178699769-4de82cfe-b1c1-49d9-b483-a3f21d03c875.png)

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Reproducibility

Once

**Comment by lsl** [comment] 2022-07-14 05:31
Could you provide a bit more info about how to reproduce this issue? I think I've followed the right steps but don't see any hanging issue.

**Comment by janmckell** [comment] 2022-07-14 10:24
Thanks @lsl This was discovered after following the steps at: https://github.com/Automattic/wp-calypso/issues/65525

So, this was done:

On a Starter site..

1.     Started at Plugins
2.     Installed WooCommerce Subscriptions
3.     WooCommerce automatically installed
4.     WooCommerce Payments did not automatically install
5.     When attempting to install WooCommerce Payments, I was asked to upgrade to Pro, but did not upgrade to Pro, and as such, did not install WooCommerce Payments -> had tried free version of the plugin.

    
    Afterwards, then these steps were done:

1.     Started at WooCommerce option (in WP dashboard)
2.     Began quick WooCommerce install flow
3.     At 'Set up payments' the screen hung, since WooCommerce Payments were not installed. (See screenshot below)

    
![Markup on 2022-07-14 at 06:23:42](https://user-images.githubusercontent.com/84089207/178961446-9632cf06-4ad5-4188-91cd-ed7acf97ec9e.png)

    I hope this helps. :)

**Comment by lsl** [comment] 2022-07-15 04:07
Thanks, reproduced and found a few extra issues along the way. (Main one here https://github.com/Automattic/wp-calypso/issues/65622)

The error in this case is because the starter plan lacks the `manage_plugins` capability which the setup payments step is expecting.

Its possible installing Woo Payments will prevent this check taking place in the first place so hopefully adding Woo Payments to all woo installs on the starter plan (like @dsas [suggested here](https://github.com/Automattic/wp-calypso/issues/65525#issuecomment-1183615851)) will be enough of a fix. Otherwise we'll need to go into WooCommerce itself and update this step to check the plugin exists before checking capabilities.

![Screenshot_2022-07-15_14-01-02](https://user-images.githubusercontent.com/811776/179147955-11807ec3-1559-437a-be40-9914bafd1a3d.png)

**Comment by obenland** [comment] 2022-07-26 21:02
Closing in favor of #65525

**Closed as completed by obenland** 2022-07-26 21:02 UTC
Labels: Bug, Needs triage, Marketplace
