### ISSUE TITLE
Manage: Sites Followed Number Not Updating

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#18161] opened 2017-09-21 16:07 UTC
On [Manage](https://wordpress.com/following/manage), when a site is followed or unfollowed, the "XX Followed Sites" number should change. In my testing, it's working. But a user named Matt reported that it's not working for him.

https://cloudup.com/cKiAFXL6E2T

@blowery @samouri can you think of any reason that number would get stuck?

**Comment by jancavan** [comment] 2017-09-21 16:46
I tested this and it only updates for me after refreshing.

**Comment by samouri** [comment] 2017-09-21 19:58
Some shortcuts were taken: the code is funky and its definitely too easy to break it.  In general it should always fix itself when the browser is refreshed -- but thats no excuse.

I'll start working on a pull request to get the count logic solid.

**Comment by blowery** [comment] 2017-09-22 20:32
@samouri Just recording what we chatted about back to the issue.

1) We want to start returning the current following count from the API on follow / unfollow. This means updating `WPCOM_JSON_API_Read_Follows_Endpoint` and `WPCOM_JSON_API_Follow_Blog_Endpoint`
2) We need to alter the count (increment on follow / decrement on unfollow) when no count is present in the action. This handles to optimistic update.
2) We need to start looking for that count in the item count reducer and consuming it when it is present. This updates the count from the response.
3) We _may_ want to trigger a resync when the count doesn't match what we expect it to be.

**Comment by gwwar** [comment] 2018-03-15 23:42
Maybe let's target this to fixing the optimistic updates for now. If they still get out of sync eventually we can also look into updating endpoints/polling in follow ups. Note that keeping counts in sync can get quite complex, see a worse case scenario https://github.com/Automattic/wp-calypso/pull/20883

**Comment by bluefuton** [comment] 2018-03-20 01:17
Closing this as a duplicate of #7342.

**Comment by rachelmcr** [comment] 2018-08-30 14:18
I tested this again and confirmed this is still an issue. The followed sites count on the left doesn't update after making changes to my followed sites unless I refresh the page:

![screenshot 2018-08-30 15 15 14](https://user-images.githubusercontent.com/8658164/44857491-d3cf7e80-ac67-11e8-8f16-0424835e889b.png)

**Comment by davemart-in** [comment] 2022-07-28 18:03
Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.

**Closed by davemart-in** 2022-07-28 18:03 UTC
Labels: [Type] Bug, Reader
