### ISSUE TITLE
Unable to Invite Users From People Page on Atomic Sites with SSO On - Inviting users requires WordPress.com sign in

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#39573] opened 2020-02-20 18:39 UTC
This issue exists on Atomic sites.

#### Steps to reproduce
1. Confirm the WordPress.com sign-on is toggled on under Settings > Security
2. Starting at URL: https://wordpress.com/people/team/{SITEURL}
3. Click on Invite

#### What I expected

To be able to invite new users.

#### What happened instead

The fields are greyed out, and there is an error message stating `Inviting users requires WordPress.com sign in` even though it is already enabled.

Clicking on `enable` results in a success message, and the invite page is available after a reload. In several cases listed on the P2 a Jetpack disconnect/reconnect resolved the issue.

So it seems that there may be a variable somewhere that's incorrectly registering the state of the SSO module, and manually updating it via the button or by reconnecting resets the variable to the correct value and allows the Invite page to be used.

The error message seems to be related to this code:

https://github.com/Automattic/wp-calypso/blob/de18db59f34af488ff47092e28b596ad9dade68a/client/my-sites/people/invite-people/index.jsx#L400

#### Screenshot / Video

<img width="775" alt="Screen Shot 2020-02-20 at 11 30 46 AM" src="https://user-images.githubusercontent.com/42279181/74966553-750a4180-53d4-11ea-837b-0fffa9bed27e.png">

Video: https://d.pr/v/tgqOPB

#### Context / Source

#user-report in #p9F6qB-4LI-p2

**Comment by samiff** [comment] 2020-02-22 03:00
More #user-report context in p9F6qB-4QI-p2

This seems to be two issues possibly.

The SSO notice is shown depending on the `showSSONotice` variable:

https://github.com/Automattic/wp-calypso/blob/b2e2caa9f181c188e0b3f8041296c36251e661b9/client/my-sites/people/invite-people/index.jsx#L421

Though the following "not-not" logic isn't clear to me: 

https://github.com/Automattic/wp-calypso/blob/b2e2caa9f181c188e0b3f8041296c36251e661b9/client/my-sites/people/invite-people/index.jsx#L478

In any case, I'm able to reproduce this on my own WPcom test AT sites.

- On initial load, `jetpack.modules.items.__ID__.sso.active` is `true`, while `jetpack.modules.requests.__ID__.sso.activating` hasn't been set so is `null`.
- `!! (null || true)` is truthy, so the SSO notice is shown. 
- On refresh however, I'm not sure what state is supposed to be rehydrating, but `jetpack.modules.items` and `jetpack.modules.requests` are empty objects; `!! (null || null)` is falsy, so the SSO notice is not shown.

**Comment by kosiew** [comment] 2020-02-25 06:50
Another case here - #2741671-zen

There are 3 admins on site.
Only the owner-admin is getting "Inviting users requires WordPress.com sign in".

The other 2 admins are able to invite users without issue.

**Comment by ivan-ottinger** [comment] 2020-02-26 09:35
Another case: #2744957-zen

**Comment by kriskarkoski** [comment] 2020-03-02 17:16
I've had at least 3 of these over the past couple weeks. If I click Enable and refresh I can send it, but the message seems to return with time. The refresh seems to be necessary otherwise the fields remain unable to be selected:

<img width="968" alt="Screen Shot 2020-03-02 at 12 13 32 PM" src="https://user-images.githubusercontent.com/1900444/75700174-a3630900-5c7f-11ea-95e2-69f537504743.png">

3276611-hc

**Comment by kriskarkoski** [comment] 2020-03-11 03:05
Reports of this seem to have tapered off and I can't currently reproduce. We can keep open for another week or two and watch for further reports before closing.

**Comment by chad1008** [comment] 2020-04-26 12:46
Another incident of this in 20596114-hc

SSO was active. Clicking on the Enable button on the alert in /people/new did not toggle SSO, but invites started working. I'm wondering if a JP sync might also have cleared it?

**Comment by katiebethbrown** [comment] 2020-04-27 01:46
Another report in #2893566-zen.

**Comment by chaitanyamsv** [comment] 2020-04-27 23:08
Another report in 20640869-hc

**Comment by eduardozulian** [comment] 2020-05-04 15:31
More in 20828168-hc

**Comment by philnick206** [comment] 2020-05-05 07:04
Reported here as well: #20750862-hc

**Comment by zdenys** [comment] 2020-05-08 15:44
Another case 20752628-hc Clicking Enable and then refreshing the page cleared the issue.

**Comment by samiff** [comment] 2020-05-12 17:23
21044471-hc

**Comment by ChaosExAnima** [comment] 2020-05-20 14:49
Not sure if related, but I have this exact same behavior on my self-hosted JP site.

**Comment by chaitanyamsv** [comment] 2020-06-03 02:36
21604790-hc

**Closed** 2020-06-26 16:10 UTC
Labels: People Management, [Type] Bug
