### ISSUE TITLE
Subscription Management: Make site icons retina ready on sites and comments list.

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#77158] opened 2023-05-19 10:31 UTC
### Quick summary

Icons at subscription page are blurry, and not big enough physically (36px) to fill the size of the image area (48px).

On retina screens I'd expect to see 2x images, too, so 96px images.

<img width="320" alt="image" src="https://github.com/Automattic/wp-calypso/assets/87168/167f824b-b7e8-49e4-a1c9-fbdb3cb2efb3">

<img width="532" alt="Screenshot 2023-05-19 at 13 28 39" src="https://github.com/Automattic/wp-calypso/assets/87168/9465c7b8-ca3e-49c4-b00d-432e3ce7177b">

### Steps to reproduce

1. Open https://wordpress.com/subscriptions/sites/en
2. See sites with icons

### What you expected to happen

Sharp, retina-ready icons

### What actually happened

Blurrry

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by mashikag** [comment] 2023-05-26 12:37
The issue is addressed in: D112020-code

**Comment by yansern** [comment] 2023-05-30 07:41
Now returning 96px, retina ready.

**Closed as completed by yansern** 2023-05-30 07:41 UTC
Labels: Bug, [Pri] Low
