### ISSUE TITLE
Pendant: Archive Page Isn't Filtering By Tag/Category

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#66659] opened 2022-08-17 19:49 UTC
### Quick summary
The archive page on the Pendant theme is showing all posts, not filtering by tag/category.

### Steps to reproduce
1. Activate the Pendant on a site with a couple posts, in different tags or categories
2. Check an archive page - a tag or category page

### What you expected to happen
The archive page should show posts only from the specific category/tag.

### What actually happened
The archive pages are showing all posts.

The archive pages are showing all posts.
### Context
This is just like [an issue from Stewart.](https://github.com/Automattic/themes/issues/5606). We were asked to create [a new copy of the issue for Pendant](https://github.com/Automattic/themes/issues/5606#issuecomment-1217878723) to give it more attention.

It seems to be an issue with this setting on the Query Loop block on the Archive template - it's deactivated on this theme, but only works when activated:

![ArchiveTemplateIssue](https://user-images.githubusercontent.com/16104522/154817195-094332f6-5681-4cc5-874a-3100a4172389.jpg)

### Workaround details
You need to edit the Archive template from the site editor, and enable that option shown on the screenshot above.

**Comment by sharonlaker19** [comment] 2022-08-18 09:01
- [ ]  5483520-zen I've applied the workaround for them.

**Comment by zachspears** [comment] 2022-08-24 00:43
Able to reproduce, changed Priority to Normal due to high impact on bloggers using this theme.

**Comment by supernovia** [comment] 2022-08-25 23:56
We have a case here. I fixed it. https://wordpress.com/forums/topic/categories-doesnt-work/

**Comment by pbking** [comment] 2022-12-13 13:16
This was just addressed here: https://github.com/Automattic/themes/pull/6775

Closing this as fixed.

**Closed as completed by pbking** 2022-12-13 13:16 UTC
Labels: Bug, Posts, [Pri] Normal, Triaged
