### ISSUE TITLE
Framework: Replace `click-outside` by `react-click-outside`

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#5181] opened 2016-05-03 11:52 UTC
We're already using `react-click-outside` in at least one place.

1. It integrates much more cleanly with React.
2. `click-outside` relies on `component-event`, which has `window` checks. That doesn't work with SSR.

**Comment by mtias** [comment] 2016-05-03 11:57
👍  react-click-outside worked quite well when I introduced it.

**Comment by furf** [comment] 2016-05-13 18:45
Further homework here #5268.

**Comment by furf** [comment] 2016-05-13 19:00
**Usage**
[ ] _client/components/dialog/dialog-base.jsx_
[ ] _client/components/popover/index.jsx_

**Comment by furf** [comment] 2016-05-16 22:00
_TODO will need to learn steps to test use of `ignoreContext`_

Found in these scripts, with regard to `this.refs.disabledInfoLabel`:
* client/my-sites/plugins/plugin-action/plugin-action.jsx
* client/my-sites/plugins/plugin-install-button/index.jsx

**Comment by nb** [comment] 2016-05-19 11:46
@furf I think those components are used when you connect a self-hosted WordPress site to WordPress.com using [Jetpack](https://jetpack.com). Then you will get to manage the plugin of your self-hosted site using Calypso.

**Comment by furf** [comment] 2016-05-25 20:54
Update: self-hosted WP site up and running. I've been able to enable the popovers and have been able to do some debugging. I can fake some settings to get popover to appear and I can log the check for ignoreContext. But I can't quite get to the state I need to be in to accurately test. 

I am assuming that the purpose of `ignoreContext` has something to do with ignoring close when interacting with [the HTML that is being injected into the popover's label](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/plugins/plugin-autoupdate-toggle/index.jsx#L77-L112), which contains an external link. I do not know the full set of steps required to reproduce the state where this HTML will be produced and displayed, nor enough about the intent of the code to infer a fix. I attempted disabling autoupdates on my self-hosted instance, using `define( 'AUTOMATIC_UPDATER_DISABLED', true );`. That does not seem to be correct or enough.

Can I borrow some 👀 from someone with experience here? I think I need @enejb's input.

**Comment by furf** [comment] 2016-05-25 20:56
PS–👀 on my code can look [here](https://github.com/Automattic/wp-calypso/blob/remove/5181-click-outside/client/components/popover/index.jsx#L138-L161).

**Comment by enejb** [comment] 2016-06-01 16:12
Hi @furf doing `define( 'AUTOMATIC_UPDATER_DISABLED', true );` should be enough. But in order for that to take into effect. You need to disconnect and reconnect Jetpack. Since that will trigger a sync of data to .com. The data gets displayed in the /me/sites endpoint which doesn't pull the data from the jetpack site. 

You should be able to see the different popovers on /plugins/example.com. Hope this helps with your testing.

**Comment by furf** [comment] 2016-06-01 19:26
_Thanks, @enejb. I didn't even have to reconnect Jetpack. When I restarted my wp-calypso instance, it appears to have taken effect._ I can now see the use case where the popover uses `ignoreContext`, which brings me to my next question...

When an element is passed to `Popover` as `ignoreContext`, I have interpreted it to mean that "all clicks outside of currently open `Popover` should dismiss `Popover`, except clicks on `ignoreContext`." And in my port of the code, this is behaving properly.

In [plugin-action.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/plugins/plugin-action/plugin-action.jsx#L42-L54), `ignoreContext` is used to pass `this.refs.disabledInfoLabel`, which is rendered [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/plugins/plugin-action/plugin-action.jsx#L25-L40) with a click handler that explicitly triggers the `InfoPopover`'s click handler [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/plugins/plugin-action/plugin-action.jsx#L17-L23) which toggles the popovers's visible state [here](https://github.com/Automattic/wp-calypso/blob/master/client/components/info-popover/index.jsx#L57-L60), effectively negating the need use of `ignoreContext` and closing the popover.

Am I missing something? What was the original intent of creating a specialized use case where an element, external to the popover toggle, would be ignored when an outside click is registered?

**Comment by furf** [comment] 2016-06-01 20:25
After speaking with @enejb, the intent may have been to prevent a "double" click event that would allow a click event that is both outside of an open popover and inside the label to close and then reopen the popover.

[The updated Popover component uses a deferred handler](https://github.com/Automattic/wp-calypso/blob/26abc7e8acdd6fd4814477ca302ccbf6e8b28618/client/components/popover/index.jsx#L138-L161) on the "click-outside" event to prevent such an occurrence.

Besides seeing no visible issues with removing code for ignoreContext, I also see no issues with the logging of analytics.

I also verified that [both of the two use cases](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/plugins/plugin-install-button/index.jsx#L110-L136) of `ignoreContext` in the `PluginInstallButton` component were functioning properly.

All uses of `ignoreContext` worked even with the removal of the functionality from `Popover`. It is possible that it is no longer needed.

**Comment by furf** [comment] 2016-06-01 20:29
As an aside, it may be worth noting that there appears to be a space between the labels that trigger the `InfoPopover` in `PluginInstallButton` which creates a dead zone for clicks. Also, I might suggest `cursor:pointer;` to improve visibility of the toggle.

**Comment by ockham** [comment] 2016-08-17 11:15
For better visibility: the corresponging PR is #5404.

**Comment by lancewillett** [comment] 2016-10-04 17:57
Closing as related pull request looks abandoned.

**Closed by lancewillett** 2016-10-04 17:57 UTC
Labels: Framework, [Type] Task
