### ISSUE TITLE
Sign up: click "Create account" results in visual errors.

### ISSUE THREAD

**Issue by anastas10s-afk** [Automattic/wp-calypso#47657] opened 2020-11-23 01:05 UTC
#### What I expected
To not face any visual errors.

#### What happened instead
On step 5, the last step, I saw a visual error on the bottom right corner of the app, referring to Localhost.

#### Browser / OS version
macOS 11.0.1

#### Screenshot / Video
https://d.pr/i/hAmBTU

**Comment by cathymcbride** [comment] 2020-12-01 21:04
@anastas10s-afk can you add more specific repro steps to this? Where did you start to create the account?

**Comment by anastas10s-afk** [comment] 2021-01-30 13:29
Every step was taken through the app, as described above, so this artefact was displayed on step 5. Since the app version has progressed, not sure if this is still relevant tho. Let me know :)

**Comment by cathymcbride** [comment] 2021-02-01 16:40
duplicate of https://github.com/Automattic/wp-calypso/issues/47430

**Closed as completed by cathymcbride** 2021-02-01 16:40 UTC
Labels: [Feature] WordPress Desktop App
