### ISSUE TITLE
Block Inserter: Markdown and SyntaxHighlighting first visible blocks

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#46981] opened 2020-10-30 22:43 UTC
“Markdown” and “SyntaxHighlighting” are showing at the front in the text group. 

<img src="https://user-images.githubusercontent.com/87168/106296199-07100080-625a-11eb-9756-738816e5a228.png" width="400" alt=""/>

Ideas:
- Core blocks should come first unless we really really want to.

**Comment by simison** [comment] 2021-02-09 16:21
Feedback: https://twitter.com/berkun/status/1358950705394929664

Might be something to do with how Jetpack registers blocks in non-standard way? cc @jeherve @kraftbj if you have this also on Jetpack backlogs?

**Comment by jeherve** [comment] 2021-02-09 16:42
I don't believe it's related to Jetpack, it seems to happen with all blocks. Note how the third-party blocks are all ahead of core blocks in the screenshots below:

![image](https://user-images.githubusercontent.com/426388/107395685-54fbf280-6afd-11eb-863b-1f65b03a062d.png)

![image](https://user-images.githubusercontent.com/426388/107396521-1d417a80-6afe-11eb-8eb7-09d1c4ef5843.png)

I believe the problem is currently tracked here:

https://github.com/WordPress/gutenberg/issues/26651

**Comment by Addison-Stavlo** [comment] 2021-02-10 18:01
It seems like this behavior is pretty standard.  Any way I test it locally it seems 3rd party blocks appear before core blocks in the sidebar inserter.  And I don't see any block registration settings that would effect whether or not they appear before or after core blocks in their category.  It may just be simply due to timing of block registration.

So I'm not sure if this issue is actually an issue and more of 'working as expected' (at this point in time at least? - asking for any clarity https://wordpress.slack.com/archives/C02QB2JS7/p1612979789462600).  But if there are concerns that core blocks should really appear first maybe we should open an issue in Gutenberg to discuss?

<hr/>

RE the twitter feedback @simison linked :  https://twitter.com/berkun/status/1358950705394929664

It seems there @mtias is talking about the contextual quick inserter, while the issue we are discussing is specific to the sidebar inserter.

**Comment by Addison-Stavlo** [comment] 2021-02-10 19:06
>  It may just be simply due to timing of block registration.

It looks like with plugins we generally register scripts/blocks on the `init` hook.  While core blocks are not registered until the specific editors load and their `initializeEditor` functions run (ex https://github.com/WordPress/gutenberg/blob/f94414c86562bfd09c810f2f523fef66b8f81a5b/packages/edit-post/src/index.js#L94).  Thus the 3rd party blocks are registered earlier than core blocks, and core blocks appear further down the registered list.  The lists are then filtered by category, but 3rd party blocks will still remain at the top of those categories. 🤔

**Comment by Addison-Stavlo** [comment] 2021-02-17 19:03
with https://github.com/WordPress/gutenberg/pull/28945 merged, this issue will be resolved once the new Gutenberg versions land on dotcom.

**Closed by Addison-Stavlo** 2021-02-17 19:03 UTC
Labels: Blocks, Editor, [Pri] Normal, [Type] Enhancement
