### ISSUE TITLE
Comments: comments-tree update data-layer

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#17547] opened 2017-08-25 19:54 UTC
Update the data-layer to query comments-tree v1.1 and be able to handle the following response:

```
{
    comments-count: 1234,
    comments-tree: {
        [ postA ]: {
            replies: [ 12, 15, 38 ],
            commentReplies: [ [ commentId, parentCommentId ], [ 20, 15 ], [ 40, 15 ] ]
        }
    },
    trackbacks_count: 0,
    trackbacks_tree: {},
    pingbacks_count: 0,
    pingbacks_tree: {}
}
```

**Comment by kwight** [comment] 2017-10-04 19:23
Closing as duplicate of #17546 .

**Comment by kwight** [comment] 2017-10-05 14:52
What am I thinking, not a duplicate at all; assigning myself as the next step.

**Closed** 2017-10-20 18:09 UTC
Labels: [Type] Task
