### ISSUE TITLE
Jetpack Connect: Pre-selected plan is lost when user is not logged into the Jetpack site

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#16086] opened 2017-07-11 11:08 UTC
#### Steps to reproduce
1. Pick a non-connected .org site that has Jetpack installed and activated.
2. Log out from your .org site.
3. Go through the `/jetpack/connect/:flow` flow, for example you can use the `personal` flow.
4. Input your site URL in the JPC form.
5. You will be prompted to log into your Jetpack site. Do it.
6. Click the "Connect" button in wp-admin to initiate connection.
7. Follow along with the connection and authorization process.
8. After auth success, you are thrown to the plans page, without a pre-selected plan.

#### What I expected
To have the Jetpack Personal plan pre-selected, and therefore continue to the checkout process.

#### What happened instead
I was presented with the plans selection page

#### Context / Source
Found while testing the new calypso login form #manual-testing

**Comment by tyxla** [comment] 2017-07-11 11:09
Related: #16084, #16085

**Comment by johnHackworth** [comment] 2017-07-18 07:49
We can't reproduce this bug anymore, so I'm closing this

**Closed by johnHackworth** 2017-07-18 07:49 UTC
Labels: .org Plans, Jetpack, [Type] Bug
