### ISSUE TITLE
Signup: with-themes flow breaks if you navigate away then return to signup

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#7295] opened 2016-08-05 02:16 UTC
#### Steps to reproduce
1. Starting at URL: wordpress.com/cities
2. Click on the signup call to action
3. Get send directly to `domains` step
4. Click `back` in browser nav to return to /cities
5. Click on the signup call to action again
6. Notice you're taken to `design-type` step, which fails, because the theme is already selected
#### What I expected

To be able to navigate back to the vertical landing page to review the promised offering before jumping into purchasing a domain. Then, I'd expect for signup not to break when I made up my mind and returned.
#### What happened instead

I saw a blank page when signup tried to restore my session and kicked me to /design-type
#### Browser / OS version

Chrome, production

`with-themes` flow: https://github.com/Automattic/wp-calypso/blob/master/client/signup/config/flows.js#L83

**Comment by hoverduck** [comment] 2016-12-12 15:37
#bug-scrub

Unable to reproduce, closing.  I tried several times going to various steps in the signup process and then going back to start over and it worked correctly every time.

**Closed by hoverduck** 2016-12-12 15:37 UTC
Labels: Signup, [Type] Bug
