### ISSUE TITLE
Signup: Error message displays HTML code

### ISSUE THREAD

**Issue by demetd** [Automattic/wp-calypso#1365] opened 2015-12-08 13:08 UTC
URL: https://cldup.com/3FT8UO8c77.png

What I expected: To see an error message

Steps to reproduce:
* Log in to this user's account: 2448522-t
* Create a new blog

What happened instead: The error message's link doesn't work and displays HTML code.

**Comment by fabianapsimoes** [comment] 2015-12-09 15:58
Duplicate of #471.

**Closed by fabianapsimoes** 2015-12-09 15:58 UTC
Labels: Signup, [Type] Bug
