### ISSUE TITLE
Block Editor - Simple Site - & symbol not displaying correctly in post editor title area

### ISSUE THREAD

**Issue by dhackneya8c** [Automattic/wp-calypso#45849] opened 2020-09-22 19:04 UTC
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/post/ on a simple site
2. Enter a post title including an `&` symbol
3. Publish post
4. Title within editor shows `&amp;` instead of `&`, but displays `&` normally on the published post

#### What I expected

Ampersand character to remain in title display within editor.

#### What happened instead

Ampersand expressed as code instead in title display within editor. This does not happen on the live post, it's just within the editor.

#### Browser / OS version

Chrome / MacOS 10.15.6

#### Screenshot / Video

![Screen Capture on 2020-09-22 at 11-52-50](https://user-images.githubusercontent.com/24231249/93925907-b3017800-fccb-11ea-9c86-6517e05794c6.gif)

#### Context / Source

User reported this issue in chat. They had also encountered it occurring with apostrophes in titles, but I was not able to replicate that in testing. Does not occur on atomic sites.

**Comment by cathymcbride** [comment] 2020-09-22 19:17
Duplicate of https://github.com/WordPress/gutenberg/issues/20490. Closing in favor of the root issue.

**Closed by cathymcbride** 2020-09-22 19:17 UTC
Labels: [Type] Bug
