### ISSUE TITLE
Cover Block Does't Work Well with Dashes

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/wp-calypso#35683] opened 2019-08-21 21:06 UTC
When trying to use dashes to separate text in a cover block, it will not allow you to add text after the dashes.

#### Steps to reproduce
1. Open a new page
2. Add a cover block and set an image
3. Add the first line of text. Hit enter
4. In line two add three or more dashes `---`
5. Hit enter. 
6. See nothing happens.

#### What I expected
Expected: That another paragraph block would appear after hitting enter.

#### What happened instead
Observed: After hitting enter nothing happens and you do not have the option to add another paragraph block in the cover block

#### Browser / OS version
Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Mac OS 10.14.6

#### Context / Source
#manual-testing

**Comment by arunsathiya** [comment] 2019-08-22 11:43
I am not able to reproduce this on a WordPress.com site and a WordPress.org site. 

Could you share a screenshot or video of this behaviour, please?

Could you also help me understand if this happens only on WordPress.com sites or WordPress.org sites as well? If it's happening on WordPress.org sites as well, you may want to ensure that the Gutenberg plugin version is latest (or if it's the core version that comes with WordPress releases), and report on https://github.com/WordPress/Gutenberg

**Comment by gwwar** [comment] 2019-10-25 23:56
Maybe a more recent update smoothed over behavior? I do see the `---` being converted into a separator block. However I don't get any focus or stuck cursor issues after that happens. There might have been a fix to the rich text editor for that case. 

![cover-sep](https://user-images.githubusercontent.com/1270189/67610500-1a274d00-f748-11e9-8e26-03aab7ceb1dc.gif)

I'm going to close this out for now, but please reopen if folks had additional context on how this breaks.

**Closed by gwwar** 2019-10-25 23:56 UTC
Labels: [Type] Bug
