### ISSUE TITLE
Editor: Disable UPDATE button when no unpublished changes

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#12251] opened 2017-03-16 22:14 UTC
I am not sure if this is a regression in the new editor design

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts
2. Edit an existing post
3. Make zero changes
4. Note that the UPDATE button is enabled

#### What I expected

I haven't made changes so I don't expect UPDATE to be enabled. 

#### What happened instead

UPDATE is always enabled even when I haven't made changes.
I can navigate away without warning since Calypso knows I haven't made changes

#### Browser / OS version

All

#### Screenshot / Video

![changes](https://cloud.githubusercontent.com/assets/128826/24020827/98f8ceea-0ae9-11e7-8637-7d52246f9181.gif)

#### Context / Source
 #dogfooding

**Comment by mcsf** [comment] 2017-03-29 10:38
Looping @mtias in

**Comment by mtias** [comment] 2017-03-29 10:57
This always worked like this, as far as I remember.

**Comment by rachelmcr** [comment] 2018-01-02 22:44
Closing this issue as a duplicate of https://github.com/Automattic/wp-calypso/issues/4794, which has more discussion of the behavior.

#bug-scrub #pre-gutenburg-bug-purge

**Closed by rachelmcr** 2018-01-02 22:44 UTC
Labels: Editor, [Type] Bug
