### ISSUE TITLE
Assembler: Replace page list in Header patterns according to the selection in the Pages screen

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#83745] opened 2023-11-01 06:58 UTC
## Description

See https://github.com/Automattic/wp-calypso/pull/83649#issuecomment-1787378573 and https://github.com/Automattic/wp-calypso/pull/83649#issuecomment-1788478244. As users select pages in the Pages screen, we would like them to be reflected in the Header patterns. This is a good-to-have for the MVP.

![Image](https://user-images.githubusercontent.com/98343583/279414175-634e578d-c8ca-4b61-8985-616ab6159fde.png)

## Acceptance Criteria

- [ ] The list of pages in the Header patterns should reflect pages selected by the user in the Pages screen.
- [ ] Fallback to default if users have not selected any page.

**Comment by fushar** [comment] 2023-11-21 06:29
Duplicate of #84360.

**Closed as not planned by fushar** 2023-11-21 06:29 UTC
