### ISSUE TITLE
NUX: Domains: oAuth error during signup

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#3314] opened 2016-02-15 17:38 UTC
Raised by @alisterscott 

> this Oauth error is that happens a lot in production

![oauth2 token error](https://cloud.githubusercontent.com/assets/66797/13056007/d035575e-d3cf-11e5-9ed4-a11860021e4b.jpg)

Anyone have an idea why it's happening, and how we can fix it?

Not sure if it's related, but I've seen an oAuth token warning in the WP.com REST API PHP error logs a lot recently (2 million cases per 12 hour periods), like:

`OAuth2_Data::get_access_token_by_client_id_user_id_global_scope NO TOKEN`

**Comment by zozep** [comment] 2016-02-18 01:24
Are there any steps that you or @alisterscott might have taken to reproduce this error?

**Comment by alisterscott** [comment] 2016-02-18 05:45
No, this happens intermittently when running our end-to-end signup automated tests against wordpress.com/start. There's no difference between test runs: sometimes it happens and sometimes it doesn't.

**Comment by fabianapsimoes** [comment] 2016-02-18 10:07
cc @drewblaisdell @scruffian for input

**Comment by lancewillett** [comment] 2016-02-18 17:13
I see the oAuth PHP REST API warnings every day with every request — when sandboxing the WP.com public-api URL to my WP.com sandbox server.

**Comment by lancewillett** [comment] 2016-04-26 20:42
Closing since no action in a few months. Feel free to re-open later if it's still happening.

**Comment by scruffian** [comment] 2016-04-28 12:45
@lancewillett are you able to consistently reproduce this? If so I'm happy to jump on screenhero and try to debug it...

**Comment by lancewillett** [comment] 2016-04-28 15:47
Nope: but CC @alisterscott @hoverduck in case they've seen it in test results recently.

**Comment by hoverduck** [comment] 2016-04-28 16:01
I feel like I saw it recently, but I just skimmed back through our failure screenshots on Slack and couldn't find it.  So if it is still happening, it's not frequent.

**Comment by hoverduck** [comment] 2017-04-06 15:41
Reopening - it's still not a frequent error, but it has been happening more recently.  We'll try to narrow it down, or at least add more logging to the e2e tests to see when/why it happens.

**Comment by hoverduck** [comment] 2017-05-10 19:15
By a rough count of the errors showing up in the Slack channels #e2eflowtesting-notif (Canary tests) and #e2e-full-suite-notif, this has happened in our tests ~18 times in the last month, since my last comment.  So it's still not incredibly frequent compared to the number of times the tests are run overall, but it's not trivial.

Are there any server-side logs that indicate when this happens?  If not, maybe adding some (if possible) is a good place to start for trying to narrow down the cause.  Otherwise is there any data that we can try to capture in the e2e tests that would aid in troubleshooting?  I've still never been able to reproduce it manually, unfortunately.

**Comment by allendav** [comment] 2017-05-31 19:27
Another occurrence (twice) today

![1496257526982-failed-mobile-can-then-see-the-secure-payment-page](https://cloud.githubusercontent.com/assets/1595739/26649892/752d85fc-45fc-11e7-9a6d-e6a371d73b96.png)

**Comment by alisterscott** [comment] 2018-07-25 05:39
We haven't seen this for some time, closing now and we can reopen if we see this again

**Closed by alisterscott** 2018-07-25 05:39 UTC
Labels: Domains, Signup, [Pri] High, [Type] Bug
