### ISSUE TITLE
Premium Content Block: Paywalled content showing in feeds

### ISSUE THREAD

**Issue by eoigal** [Automattic/wp-calypso#44554] opened 2020-07-30 08:42 UTC
Posts with Premium Content blocks are showing the pay-walled/premium content to non-subscribers in feed content.

Non-subscribers should not see the premium content until they pay for a subscription.

Reported here - p1596070756469600-slack-earn

**Example**
Premium content is pay-walled: https://desertrosecreations.co/2020/07/17/i-can-have-mercy-on-god/
Premium content is publicly visible: https://wordpress.com/read/feeds/105368351/posts/2815111283

**Comment by blackjackkent** [comment] 2020-08-06 18:02
I'm having some trouble reproducing this issue - both links seem to be showing the logged-out view for me (which I believe is the expected behavior?).

![image](https://user-images.githubusercontent.com/13437011/89566021-08013180-d7e5-11ea-8f65-109b53d10d3e.png)

![image](https://user-images.githubusercontent.com/13437011/89565961-f1f37100-d7e4-11ea-9b05-eaf6904493de.png)

**Comment by kwight** [comment] 2020-08-06 21:59
Hm, my testing indicates this is all working as expected too. Publishing premium content with one account, I can see this from another account (before and after subscribing):

| View        | Not Subscribed           | Subscribed  |
| ------------- |:-------------:|:-----:|
| Front-end     | <img width="500" alt="Screen Shot 2020-08-06 at 2 41 46 PM" src="https://user-images.githubusercontent.com/349751/89586347-5e29a100-d7f4-11ea-8cc9-543b04b83857.png"> | <img width="500" alt="Screen Shot 2020-08-06 at 2 42 35 PM" src="https://user-images.githubusercontent.com/349751/89586348-5ec23780-d7f4-11ea-95cc-d15dec58d8d8.png"> |
| Reader     | <img width="500" alt="Screen Shot 2020-08-06 at 2 41 16 PM" src="https://user-images.githubusercontent.com/349751/89586339-5bc74700-d7f4-11ea-85ec-503617a93609.png"> | <img width="500" alt="Screen Shot 2020-08-06 at 2 44 23 PM" src="https://user-images.githubusercontent.com/349751/89586350-5f5ace00-d7f4-11ea-98cd-f15a697f190a.png"> |

I'm wondering if this is user confusion; maybe they thought anything below the block (the video) would be the premium content, rather than realizing there's a specific tab for the hidden content? The two views certainly show the same content, there's nothing different between the two views.

**Comment by kwight** [comment] 2020-08-06 22:00
@eoigal Did the views look different when you first triaged the issue? Maybe something else is a factor we're not aware of?

**Comment by kwight** [comment] 2020-08-24 21:19
I'll close this as not reproducible – if someone can provide some steps, we're happy to open and pick it up again.

**Comment by jamiepalatnik** [comment] 2021-05-17 17:36
I received another report in 29184356-hc of this issue for these example posts: 

Site: https://pharaohdiaries.com/2021/05/11/mens-aw21-trends/
Reader: https://wordpress.com/read/blogs/181492719/posts/4675

Site: https://pharaohdiaries.com/2021/01/15/course-3-influencer-academy/
Reader: https://wordpress.com/read/blogs/181492719/posts/3094

When I checked in the Reader using an account that was not subscribed to this premium content, I was able to see the subscriber content: https://d.pr/i/60qmb8

Re-opening issue so we can investigate further.

**Comment by Robertght** [comment] 2021-05-20 11:48
@kwight I'm not sure if you're still able to check this, but can we have a hand with this one? It seems like it can affect other websites as well.

**Comment by kwight** [comment] 2021-05-20 14:45
The @Automattic/view-engineering team handles these blocks now (although we're all committed to other projects) – any room for you all to look at this @apeatling ?

**Comment by apeatling** [comment] 2021-05-20 16:22
@andrewserong has a fix in the works for this one.

**Comment by andrewserong** [comment] 2021-05-21 00:09
Fix deployed in D61642-code / r226049-wpcom

I tested the reported sites on an account with access to the paywall content and one that doesn't, and it appears to be working correctly now. Please let us know if you encounter any further issues!

**Comment by ersatzpenguin** [comment] 2021-06-11 19:05
Hey all, this issue seems to have resurfaced somehow, and has been reported in 4060888-zen.

Site: https://chickadeesandcrickets.com/2021/06/11/pretty-nothing/
Reader: https://wordpress.com/read/feeds/118553430/posts/3387820865

@andrewserong Is there a chance recent updates have broken the fix you deployed?

**Comment by andrewserong** [comment] 2021-06-15 02:05
Thanks for reporting @ersatzpenguin! I couldn't replicate the issue, but I added more context in p1623722588204700-slack-CS0SC36SX

**Comment by andrewserong** [comment] 2021-06-16 01:59
We're currently unable to reproduce the issue that related to caching, and I've opened up a couple of feature request issues in relation to Likes behaviour (where a user wishes to exclude a post from Likes in all contexts including the Reader and subscriber emails).

I'll leave this issue open for the rest of the week, in case anyone is able to reproduce any instances of paywalled content being visible in feeds where it shouldn't be.

**Comment by rosepajaroja** [comment] 2022-05-01 01:35
Hello all, this issue seems to be happening again - protected contents appear on the Reader. 

Reported here: hc-35160826

Post - https://shanbae.com/discomforting-revelations/ 
*Note seems like they did a workaround to hide the protected contents from the Reader by using the "More" block. 

I tested and could replicate the issue on my test site: 
Sample post: https://woowebinar.wordpress.com/2022/05/01/testing-premium-content/

**Comment by susanjanec** [comment] 2022-08-15 11:18
User reported in 5478075-zen that their Premium content placed in a Premium content block is showing in reader.

I checked this in my reader and am not subscribed to see their Premium content so not sure why it is showing in Reader.

Example - 
Post: https://zakschafer.com/2022/08/14/everyone-i-know-is-lonely/
Reader: https://wordpress.com/read/feeds/123624228/posts/4194404556

**Comment by jp-imagines** [comment] 2022-08-15 15:18
I wasn't able to replicate the issue from 5478075-zen that @susanjanec reported above – when logged into an account that isn't subscribed, I am not able to see the premium content in the Reader feed (as expected).

There _is_ the option to like the post, however, which is reported in https://github.com/Automattic/wp-calypso/issues/53729. I'm adding that user's report there.

**Comment by simison** [comment] 2024-05-28 08:32
Closing an old issue which is sorted already a while back.

**Closed** 2024-05-28 08:31 UTC
Labels: [Type] Bug, [Pri] Normal, Earn, Premium Content, User Report, Triaged
