### ISSUE TITLE
Guided Tours: loading spinner styling off for site preview in FF

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#5844] opened 2016-06-06 23:07 UTC
More obvious when a site has a lot of content or on a slow connex, the site preview loading spinner styling is odd on Firefox. Note that the spinner for editor/post preview is correct:

https://cloudup.com/cFEq4nWY9Ku
#### Steps to reproduce
1. Starting at URL: wordpress.com on Firefox
2. tap site name to open in-app preview for a site with a lot of content
3. notice broken spinner styling

**Comment by KokkieH** [comment] 2016-07-15 09:10
This issue also occurs on the stats page when switching between Insights/daily/weekly/monthly stats views.

![stats_issue_bar-spinner](https://cloud.githubusercontent.com/assets/11873759/16869286/67ebac4c-4a7c-11e6-989d-5f3ffa359257.png)

Confirmed it happens in Firefox, but not in Chrome.

Reported in 744627-f

**Comment by lsinger** [comment] 2016-10-05 14:12
Unable to reproduce this anymore (FF 48.0.2, macOS):

![loading-spinner](https://cloud.githubusercontent.com/assets/23619/19116617/6cc6abba-8b16-11e6-9d08-ee009399810e.gif)

Closing for now. Feel free to re-open.

**Comment by KokkieH** [comment] 2016-10-05 14:28
Still happening for me, FF 49.0.1, Mac OS X

@lsinger See if you can repro if you simulate a slow connection, say under 1mbps

![spinner](https://cloud.githubusercontent.com/assets/11873759/19117238/98d47d8e-8b18-11e6-8868-e1e9e85437fa.gif)

**Comment by lsinger** [comment] 2016-10-05 15:31
ACK I now was able to reproduce with a slow connection. 

Removing `GuidedTours` and `NUX` labels and adding `Components` label though, since this seems to be an issue with the Spinner component.

**Comment by timmyc** [comment] 2016-12-15 22:26
I can not re-create this in FF 50.0.2, an easy way to test is to open up http://calypso.dev:3000/devdocs/design/spinner which is the component in question.  Working fine for me.

**Closed by timmyc** 2016-12-15 22:26 UTC
Labels: Components, [Type] Bug

**Comment by KokkieH** [comment] 2016-12-16 05:49
It does appear to be working on the stats page for me now as well, despite my slow connection :)
