### ISSUE TITLE
Domains: When trying to renew domain I get a whitescreen

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#21461] opened 2018-01-11 18:05 UTC
I was trying to renew my domain. I got the notification in my sidebar. I clicked the first link which took me to 
https://wordpress.com/me/purchases/enej.wordpress.com/7226051

At first I see 
![screen shot 2018-01-11 at 10 01 46 am](https://user-images.githubusercontent.com/115071/34839459-7ed79438-f6b6-11e7-9946-9e9c04bcd577.png)

but after a while I see 
just the white/gray screen

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases/enej.wordpress.com/7226051

#### What I expected
To be able to renew the domain.

This is what I see in my js console
<img width="652" alt="screen shot 2018-01-11 at 10 04 18 am" src="https://user-images.githubusercontent.com/115071/34839573-dfa25cda-f6b6-11e7-904d-19f6f06ce70e.png">

#### Browser / OS version
Firefox / MacOS

#### Context / Source
#dogfooding

**Comment by aidvu** [comment] 2018-01-16 17:36
Not able to reproduce anymore. Tried figuring it out with @enejb. This is a strange combination of upgrading site to AT and a domain mapping sub being removed.

Closing unless we can reproduce.

**Closed by aidvu** 2018-01-16 17:36 UTC
Labels: Domains, [Type] Bug
