### ISSUE TITLE
CSS panel jumping as it scrolls

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#48287] opened 2020-12-13 14:30 UTC
#### Steps to reproduce

1. Go to the customizer on #3567554-zd
2. As you scroll up and down you see the pane jumping - https://d.pr/v/Vx85xq

#### What I expected
The panel to scroll smoothly

#### What happened instead
It jumps about

**Comment by cathymcbride** [comment] 2020-12-16 20:48
Likely the same as https://github.com/Automattic/wp-calypso/issues/26287

**Comment by Nic-Sevic** [comment] 2021-02-07 14:25
Same happening for me still
to add context, this happens only when there is a lot of CSS added, generally more than 200 lines

**Comment by cathymcbride** [comment] 2021-02-08 16:36
So, yes. this appears to be a duplicate of #26287. Closing...

**Closed as completed by cathymcbride** 2021-02-08 16:36 UTC
Labels: Bug, [Pri] Low, [Feature] Customizer
