### ISSUE TITLE
Editor: Content is cut in half in the editor

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/wp-calypso#34128] opened 2019-06-19 13:58 UTC
#### Steps to reproduce

Shorter steps to reproduce:
- Insert a columns block
- Add an image

![glitch](https://user-images.githubusercontent.com/1270189/60204857-9f373f80-9804-11e9-820e-6e06cc0051dd.gif)

Using Chrome: 

1. Starting at URL: https://wordpress.com/start/
2. Select Business on "What kind of site are you building"
3. Go through the remainder of the signup flow and select "start with a free site" (other options don't matter)
4. A new home page is created with some default blocks
5. Load new home page in the editor, and resize the browser window (error occurs between 1100 and 1500 wide).

#### What I expected

Placeholder content fully loads in all browser sizes

#### What happened instead

The blocks get cut in half on certain browser window sizes. Video: https://cld.wthms.co/yWrezy

Exiting out and returning to the editor the home page results in the same issue. 

#### Browser / OS version

Chrome / Mac

#### Screenshot / Video

Video: https://cld.wthms.co/yWrezy

#### Context / Source
For those that don't know the browser size is the source of the issue, it looks like the content didn't load properly and would not know to resize the browser to see all of it. 

#user-report

**Comment by tijosh** [comment] 2019-06-19 14:58
I helped a user recently who had the same issue, but I'm not sure how they arrived at the problem. 

### Summary

They had a page which included a columns block that had 6 columns and an image in each column. With another block added below the columns block, the page editor view was breaking in Chrome. 

See this video: https://cld.wthms.co/nvfKk0

### What I Did

I exported the site's contents and imported into a test site. The problem persisted on the page that was imported, but I cannot recreate this problem manually by simply adding a columns block with 6 columns on a fresh blank page.

### Context/Source

#11305879-hc

**Comment by adelineyaw** [comment] 2019-06-19 21:31
Just noting here that 2118566-zd has replied that it's no longer a problem for them but keeping this issue open as @ktyfuller604 can still reproduce the error.

**Comment by kathleenjross** [comment] 2019-06-20 14:49
Similar issue in 2122759-zen

I feel like I have seen this issue a few times as well, related to the new Business themes.

**Comment by gwwar** [comment] 2019-06-26 18:46
See related core issue in https://github.com/WordPress/gutenberg/issues/14652

**Comment by gwwar** [comment] 2019-06-26 19:06
I think this is a Chrome rendering bug with flex-basis:

![flex-basis](https://user-images.githubusercontent.com/1270189/60207390-9e091100-980a-11e9-9a27-f45cde3186a7.gif)

Turning Hardware Acceleration on and off doesn't appear to affect this. (Broken in both cases).

**Comment by gwwar** [comment] 2019-06-26 20:06
@glendaviesnz I believe this will need to be fixed upstream in the Gutenberg project. So feel free to target a PR to that repo.

**Comment by gwwar** [comment] 2019-06-27 16:37
https://github.com/WordPress/gutenberg/pull/16325

**Comment by glendaviesnz** [comment] 2019-06-27 20:14
This will be fixed in the next Gutenberg update.

**Comment by isocialtish** [comment] 2019-06-30 18:40
Excited this will be fixed in the next Gutenberg Update! 

I had a very similar issue (only it wasn't using columns) so I wanted to note it here as well. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/page/skyenatureblog.com/1081
2. In the right sidebar, I clicked "Try the new block Editor"
3. When the page loaded, half the screen was blank

#### Screenshot / Video
https://cld.wthms.co/lWt1Rn

#### Video w/ console errors:
https://cld.wthms.co/eCJCSd

#### Browser / OS version
Mac / Chrome Version 75.0.3770.100
Mac / Ghost Version 2.1.0.7 
Mac / Firefox Version 67.0.4 (it was working correctly in Firefox- didn't see the error there)

**Comment by supernovia** [comment] 2019-07-01 17:58
Noting I've seen this myself and it goes away when I move the window :/   That's cool that it'll be fixed though!

**Comment by supernovia** [comment] 2019-07-01 17:59
one more here: https://en.forums.wordpress.com/topic/page-format-7/#post-3333054
chrome / windows

**Comment by sophiegyo** [comment] 2019-07-02 05:17
Just noting that I've noticed it myself on my Windows computer using Chrome, and we also had a report from a user in 2131828-zen who had this browser/computer info:
Browser - Chrome Version 75.0.3770.100
Operating system - Windows NT 10.0
Screen size - 1366 x 768
https://whatsmybrowser.org/b/XYP6MVQ

**Comment by gwwar** [comment] 2019-07-02 16:41
This will be fixed when v6.1 of the Gutenberg plugin is published. We'll try another attempt to get that on WordPress.com on July 10th when it's released.

**Comment by susanjanec** [comment] 2019-07-04 13:45
Report from user in 2144538-zen. 

They had this browser/computer info:
Chrome 75 on Windows 10 
Internet Explorer 11 on Windows 10

**Comment by msilbers** [comment] 2019-07-09 17:31
I had a report of this from a user in #13894213-zen who is unable to edit their homepage (their only page). They are using Chrome. 

They were able to update their site in Safari.

**Comment by lizswafford** [comment] 2019-07-10 19:57
Similar report in #13166098-hc
Only related to the Chrome browser.
Chrome 75.0 on Windows 10.0.0

**Comment by gwwar** [comment] 2019-07-19 23:40
Closing this out since v6.1.1 landed in https://github.com/Automattic/wp-calypso/issues/34386

**Closed by gwwar** 2019-07-19 23:40 UTC
Labels: [Goal] Gutenberg, [Type] Bug
