### ISSUE TITLE
Canard: Missing bottom spacing on Image blocks that center aligned

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#65093] opened 2022-06-29 17:46 UTC
### Quick summary

It appears that the latest update on the theme removed a bottom margin from images that have "align" set to "center", making the text under it look like a caption

### Steps to reproduce

1. Activate the theme Canard
2. Create a new post
3. Add an image block
4. In the image block toolbar, select Align > Align center
5. Add a paragraph with some text just under it

### What you expected to happen

To see some spacing between the image and text:
![Uploading image.png…]()

### What actually happened

There is no spacing under the text and image:
![Uploading image.png…]()

### Context

5336139-zd-woothemes

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Yes, Canard

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

One of the following:

* Change the image alignment (from center to something else)
* Add a line jump to the beginning of the next paragraph
* Use the following CSS code:
```
/* Add bottom margin to images that are center aligned */
.wp-block-image .aligncenter {
margin-bottom: 30px;
}
```

**Comment by aisajib** [comment] 2022-07-10 16:19
📌 SCRUBBING

- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
I wasn't able to reproduce this issue on two simple and one self-hosted site I've tested on. Here's how I see it: 

<img width="880" alt="Screen Shot 2022-07-10 at 10 17 27 PM" src="https://user-images.githubusercontent.com/2541844/178152999-d89390f2-02e4-47c8-b212-db6b9eddc9ea.png">

I can see an issue with margins on an atomic site, though. Here's how this shows up on an atomic site: 

<img width="871" alt="Screen Shot 2022-07-10 at 10 18 15 PM" src="https://user-images.githubusercontent.com/2541844/178153037-8fb506a3-f2fa-43c8-bbb9-53c6370ecc4a.png">

Is this how it shows up on the user's site? @mxhassani I can't see the screenshots you uploaded likely because the upload wasn't finished before you posted it. If you have those screenshots on your computer, perhaps you can upload them again? 

I'm holding for that and then we can move it to the themes repo. 

📌 ACTIONS
- Await author feedback

**Comment by Robertght** [comment] 2022-07-21 11:41
Thank you for working on this @aisajib !

I'm closing this for now, but please reopen if this becomes relevant again.

**Closed as completed by Robertght** 2022-07-21 11:41 UTC
Labels: Bug, [Pri] High, Triaged
