### ISSUE TITLE
AMP 2.0 - cover block content disappears

### ISSUE THREAD

**Issue by kaitohm** [Automattic/wp-calypso#51537] opened 2021-03-30 06:25 UTC
### Steps to reproduce the behavior

1. Make a new post.
2. Add a Cover block with a solid background color
3. Check AMP version

#### What actually happened

AMP off: Red background and black text

<img width="1133" alt="amp-off" src="https://user-images.githubusercontent.com/49054298/112942487-2698ac00-916b-11eb-96aa-00021ffd9d90.png">

Current version of AMP: No background, black text

<img width="885" alt="amp-current" src="https://user-images.githubusercontent.com/49054298/112942524-331d0480-916b-11eb-9123-f6a396cea3a4.png">

AMP 2.0: White background, white text (making the block and content invisible)

<img width="916" alt="amp-2 0" src="https://user-images.githubusercontent.com/49054298/112942562-4203b700-916b-11eb-92bf-19380273215a.png">

### Context

Bug testing this: p58i-aiQ-p2

#### Browser / OS version

Confirmed same behaviour in Chrome and Safari

#### Is this specific to the applied theme? Which one?

No. Confirmed with Brompton and TwentyTwenty

#### Does this happen on simple or atomic sites or both?

Confirmed in Simple

#### Is there any console output or error text?

No

**Comment by simranvijwani** [comment] 2021-03-30 07:23
I found a similar bug of content disappearing: 

When adding animation in the Cover Block, Image Block, and Gallery block, the blocks' content disappears. 
On the Amp page, when you click on the block area, the image shows up. The block is present on the page, and its HTML code is present in the inspector. However, it does not show up on the page. 
I think it affects all the block that supports animation.

**Comment by claudiucelfilip** [comment] 2021-04-05 14:38
Thanks for raising this!

The issue seems to be cause by the fact that these predefined colors are bound to the theme (in this case Bompton or TwentyTwenty). In reader mode, the AMP plugin switches to another theme, thus losing the selected color.
An issue has been raise on the plugin prover's repo: https://github.com/ampproject/amp-wp/issues/6039
Until then a workaround is proposed where the cover will default to a blue background: D59723-code

@simranjeetkaur10 
> When adding animation in the Cover Block, Image Block, and Gallery block, the blocks' content disappears.
> On the Amp page, when you click on the block area, the image shows up. The block is present on the page, and its HTML code is present in the inspector. However, it does not show up on the page.
> I think it affects all the block that supports animation.

I'm not sure if it's related but it might still be a concern.
Can you provide any screenshot, link or video? This would greatly help us pinpoint and/or reproduce the issue.

**Comment by simranvijwani** [comment] 2021-04-06 15:44
Sure, @claudiucelfilip!

Here is the screen recording: 


https://user-images.githubusercontent.com/34896144/113738720-c2eb2180-971c-11eb-8084-44f81e39301f.mov

**Comment by claudiucelfilip** [comment] 2021-04-07 12:02
@simranjeetkaur10 
Thank you for the screenshare. It really helped to sort this out.

From what I see this is an Atomic site, which shouldn't be affected by this rollout. This should have been showing this issue for some time (2.0.11). 
Also, this seems to be an issue between the WP AMP plugin and [CoBlocks](https://wordpress.org/plugins/coblocks/). We probably need to raise an issue on the WP AMP [repo](https://github.com/ampproject/amp-wp).

**Comment by westonruter** [comment] 2021-04-08 04:49
Please take a look at https://github.com/ampproject/amp-wp/pull/6042 for @pierlon's work-in-progress. The lack of editor color palette standardization in themes is causing a key challenge.

**Comment by claudiucelfilip** [comment] 2021-04-09 10:40
Deployed a temporary solution for wpcom, by using the --wp-admin-theme-color.

**Comment by pierlon** [comment] 2021-05-07 11:28
This should now be fixed in the newly released [v2.1](https://github.com/ampproject/amp-wp/releases/tag/2.1.0) of the AMP plugin.

**Comment by WunderBart** [comment] 2021-11-03 15:28
I can confirm it's been fixed with the [v2.1 update](https://github.com/Automattic/wp-calypso/issues/51537#issuecomment-834287524). Closing this one!

**Closed as completed by WunderBart** 2021-11-03 15:28 UTC
Labels: Bug, AMP, [Feature] CoBlocks
