### ISSUE TITLE
Unable to edit blog post with Gutenberg because of updating failed error

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#27239] opened 2018-09-17 10:54 UTC
We should fix an issue preventing a blog post from being edited with Gutenberg:

<img width="624" alt="screenshot" src="https://user-images.githubusercontent.com/594356/45619106-53d35200-ba78-11e8-9b6c-4ebec72360ba.png">

#### Testing instructions

1. Open a [blog post](https://wpcalypso.wordpress.com/gutenberg/post/example.wordpress.com/9) with Gutenberg
2. Click the title, then click the text below to select a different block
3. Notice that an `Updating failed` error is displayed
4. Notice that `Autosaving` and the `Preview` button flicker
5. Notice that the `Update` button is animated

#### Additional notes

The browser's console didn't show any Javascript error.

**Comment by stephanethomas** [comment] 2018-09-17 10:57
The network panel shows multiple calls to https://public-api.wordpress.com/wp/v2/sites/example.wordpress.com/posts/9/autosaves?_envelope=1 with the following response returned:

```json
{
  "body": {
    "code": "rest_post_invalid_id",
    "message": "Invalid item ID.",
    "data": {
      "status": 404
    }
  },
  "status": 404,
  "headers": {
    "Allow": "GET"
  }
}
```

**Comment by gwwar** [comment] 2018-09-17 20:58
Duplicate of https://github.com/Automattic/wp-calypso/issues/27142

**Closed by gwwar** 2018-09-17 20:58 UTC
Labels: [Goal] Gutenberg, [Type] Bug
