### ISSUE TITLE
Jetpack Plugins: superadmins can see network activated plugins in subsite view

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#83] opened 2015-11-18 15:32 UTC
User type | Jetpack network enabled? | Plugins tab allowed in sub-sites? | see plugins in wpcom? | correct?
------------- | ------------------------------------------- | ------------------------------- | ----------- | -----
admin | not network enabled | allowed plugins tab | see plugins | ✓
superadmin | not network enabled | allowed plugins tab | see plugins | ✓
admin | network enabled | not allowed plugins tab | no, plugins don't show up | ✓
superadmin | network enabled | not allowed plugins tab | yes, plugins do show up (see below) | ✗ (see below)

Here's the issue:
1. Log in to subdomain of a network using superadmin
2. Connect this site to Jetpack
3. Go to the plugins page for that site (https://wordpress.com/plugins/site1.yournetwork.org) see this:

![screen shot 2015-11-10 at 12 55 50 pm](https://cloud.githubusercontent.com/assets/11487924/11070584/6645f9d2-87aa-11e5-99b5-6bec8dabdb17.png)

However, this is displaying the full list of plugins available on the network. Here's a screenshot of all the plugins on the network:

![screen shot 2015-11-10 at 12 56 46 pm](https://cloud.githubusercontent.com/assets/11487924/11070624/aad0a70a-87aa-11e5-92c7-68487279a55a.png)

Here's the list of plugins that show up for the sub site:

![screen shot 2015-11-10 at 12 56 56 pm](https://cloud.githubusercontent.com/assets/11487924/11070630/b39b31f2-87aa-11e5-934b-5b3ccb67469e.png)

-> So, **we should only display the plugins available on the sub-site, not the whole network, even for superadmins visiting the plugins page.**

@enejb - maybe we need a message to show why plugins don't show up for the third scenario?
We also need to make sure that only the plugins that are available for a site show up for the fourth scenario - or else not show the plugins the same way it works for the third scenario.

**Comment by designsimply** [comment] 2016-04-21 15:29
Tested and confirmed that I can see all plugins (network-activated or not) when logged in to WordPress.com (superadmin or not) as the connected user for a subdomain site on a network. 

My testing steps:

1. Log in to subdomain of a network
1. Connect the site to Jetpack
1. Enable Jetpack Manage
1. Go to https://wordpress.com/plugins/ and select the site
1. Check to see whether you can see plugins that are not network-activated for the subdomain site you are viewing plugins for

<strong>Result:</strong> I expected to only be able to see plugins that are active or network-activated, but I can see all plugins installed on the network

Here is what I see via the `wordpress.com/plugins` page:

![screen shot 2016-04-21 at thu apr 21 7 55 54 am](https://cloud.githubusercontent.com/assets/1119271/14714511/14caaf42-079a-11e6-871b-19a0ea04294c.png)
<sup>Seen at https://wordpress.com/plugins/wildly.disambiguously.com logged in as a regular WP.com user connected to and linked as an Administrator account on the subdomain site using Safari 9.1 on Mac OS X 10.11.13</sup>

In comparison, I see something similar on the site's `wp-admin/plugins.php` page when logged into the network site as a superadmin:

![screen shot 2016-04-21 at thu apr 21 7 56 23 am](https://cloud.githubusercontent.com/assets/1119271/14714584/6626efc2-079a-11e6-9d1e-6b73fc2a1edd.png)
<sup>Seen at http://wildly.disambiguously.com/wp-admin/plugins.php logged in as a superadmin on the subdomain site using Safari 9.1 on Mac OS X 10.11.13</sup>

Note: none of the plugins on the subdomain site are network-activated in this case:

![screen shot 2016-04-21 at thu apr 21 8 18 45 am](https://cloud.githubusercontent.com/assets/1119271/14714610/81482654-079a-11e6-9d6c-ba4351fd4491.png)
<sup>Seen at http://disambiguously.com/wp-admin/network/plugins.php logged in as a superadmin on the subdomain site using Safari 9.1 on Mac OS X 10.11.13</sup>

Possible enhancement: indicate whether or not a plugin is network-activated or not in the Jetpack Manage > Plugins view on WordPress.com similar to `/wp-admin/network/plugins.php` on the site.

Since it's possible to see the same list of plugins at `wp-admin/plugins.php` on the subdomain site when logged in as a superadmin, I am recommending that we close this issue.

**Comment by designsimply** [comment] 2016-04-25 21:33
Moved to #4997

**Closed by designsimply** 2016-04-25 21:33 UTC
Labels: Jetpack, Jetpack Mods, Jetpack Plugins, [Triage] Close Me, [Type] Bug
