### ISSUE TITLE
SPT: vertical scrollbar is always shown

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#39799] opened 2020-03-02 09:36 UTC
The vertical scrollbar is always shown despite that some templates that don't require the full height for its previsualization.

<img width="1064" alt="Screen Shot 2020-03-02 at 6 33 18 AM" src="https://user-images.githubusercontent.com/77539/75663824-3d12c200-5c50-11ea-96c6-2d6016569fee.png">

**Comment by frontdevde** [comment] 2020-03-02 11:29
The issue seems to be cause by the body in the iframe being pushed down by approximately `5vh`:

<img width="1108" alt="Screenshot 2020-03-02 at 12 14 33" src="https://user-images.githubusercontent.com/1562646/75672357-e5d91580-5c80-11ea-8fff-ec1d0455ab77.png">

The symptom can be fixed by applying `height: 95vh` to `.block-iframe-preview-body`:

<img width="818" alt="Screenshot 2020-03-02 at 12 13 41" src="https://user-images.githubusercontent.com/1562646/75672492-259ffd00-5c81-11ea-861b-94ea37f22c20.png">
 
Applying `height: 95vh` to `.block-iframe-preview-body` removes the additional scrollbar for content that is shorter than the full height while still showing the scrollbar when the content is longer. That said, it seems like fixing the symptom rather than the root cause. At this point it's still not entirely clear to me why the issue appears in the first place. Continuing to look into it...

**Comment by frontdevde** [comment] 2020-03-02 12:03
Upon further investigation the issue seems to be caused by what appears to be a rendering bug. The margins of the top and bottom blocks aren't contained in the parent element. A known CSS remedy for these type of rendering bugs is adding `overflow:hidden` to the parent container.

**Before:** 

<img width="1325" alt="Screenshot 2020-03-02 at 12 55 17" src="https://user-images.githubusercontent.com/1562646/75674753-0fe10680-5c86-11ea-8e5d-d6f8e685ed08.png">

**After:**

<img width="1324" alt="Screenshot 2020-03-02 at 12 55 32" src="https://user-images.githubusercontent.com/1562646/75674777-1cfdf580-5c86-11ea-85c7-2264dd59284a.png">

**Closed** 2020-03-02 16:44 UTC
