### ISSUE TITLE
Checkout fails when upgrading to a shorter length plan to access a theme

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#88378] opened 2024-03-11 15:08 UTC
### Quick summary

Sites with an biannual or longer Starter plan can choose an Explorer theme in the design picker. A Starter theme adds a mandatory upgrade to the annual Explorer plan, but this won't work - we don't allow "upgrades" to a lower length plan.

This is very similar to https://github.com/Automattic/wp-calypso/issues/87281 which is where it was discovered.

> [!IMPORTANT]  
The same issue exists with /themes and the DP

- [X] Fix design picker - https://github.com/Automattic/wp-calypso/pull/89544
- [ ] Fix themes
- [ ] Fix live preview - https://github.com/Automattic/wp-calypso/pull/89798

### Steps to reproduce

1. Go to /start
2. Create a site on a biannual or longer Starter plan, ensuring you go all the way through checkout.
4. Go to choose a theme
5. Choose a theme locked behind the Explorer plan, such as Cakely
6. Press Unlock theme
7. See the dialog that says you're going to be on the Explorer plan
8. Follow the process until you get to the checkout

You don't actually have to start at step one - any site can use the onboarding design picker at any time, indeed it is sometimes linked to by the dashboard.

### What you expected to happen

See a checkout screen with an Explorer plan

### What actually happened

Empty cart with error message including "Sorry, that plan is not a valid upgrade from your current plan"
<img width="1460" alt="Screenshot 2024-03-11 at 15 07 06" src="https://github.com/Automattic/wp-calypso/assets/93301/387da4c4-c522-4122-b1ef-95bec1c910da">

### Impact

One

### Available workarounds?

Yes - choose a different theme

**Comment by filipanoscampos** [comment] 2024-03-12 11:23
📌 ACTIONS
Reproduced exactly as described.
Marking as triaged as this is already assigned to a team.

**Comment by dsas** [comment] 2024-03-12 11:39
Choosing a Community theme on /themes to upgrade to does work, and gives a pop-over checkout rather than a redirect.

**Comment by xavier-lc** [comment] 2024-04-03 16:30
I'm not able to reproduce the issue. This are the steps I'm following:

1. Go to https://wordpress.com/start
2. Choose a domain
3. Get starter plan with a 2 year interval
4. I'm redirected to the checkout page:
![image](https://github.com/Automattic/wp-calypso/assets/8511199/11bf54dd-8479-4c9c-986c-11e054813ff5)
5. Go to https://wordpress.com/themes/xjlctest96.wordpress.com
6. Click on the `Cakely` theme
7. Click on the `Upgrade to activate` button (not `Unlock theme`, as it says on the issue description)
8. I'm redirected to the checkout page for the Explorer plan:
![image](https://github.com/Automattic/wp-calypso/assets/8511199/79fd6faf-67f7-4a27-8e88-056656e435d2)

So I'm not sure if step 2 (`Get a site on an biannual or longer Starter plan`) requires going through the checkout for the 2-year starter plan?

**Comment by dsas** [comment] 2024-04-08 08:22
> So I'm not sure if step 2 (Get a site on an biannual or longer Starter plan) requires going through the checkout for the 2-year starter plan?

Sorry, yes it does. I'll clarify the steps.

**Comment by dsas** [comment] 2024-04-22 08:31
Reopening as we need to do the same thing for live preview and for the theme showcase

**Closed as completed** 2024-05-03 09:06 UTC
Labels: Bug, [Pri] High, Triaged, [Feature] Design Picker, [Status] Priority Review Triggered
