### ISSUE TITLE
Checkout: Domains: Correct highlight color for fields with errors

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#3463] opened 2016-02-22 15:09 UTC
## URL
https://wordpress.com/checkout/:site

## What I expected
Error fields should have thick, red border on focus.

## What happened instead
They have the normal, blue one.

## Steps to reproduce
Visit Checkout, focus a field with a validation error.

## Browser / OS version

Chrome / Linux

## Screenshots
Current version:
![2016-02-22-155855_667x151_scrot](https://cloud.githubusercontent.com/assets/3392497/13222038/6c9eca4a-d97e-11e5-9c83-1e708c2f83c6.png)

Should be:
![2016-02-22-160053_659x153_scrot](https://cloud.githubusercontent.com/assets/3392497/13222047/71a1f094-d97e-11e5-89cb-bcca176d75a0.png)

/cc @umurkontaci

**Comment by umurkontaci** [comment] 2016-02-22 17:06
Duplicate of #2476.

**Closed by umurkontaci** 2016-02-22 17:06 UTC
Labels: Checkout, Domains, [Type] Enhancement

**Comment by klimeryk** [comment] 2016-02-22 17:15
Ugh, my bad, how did I not see that issue? ~_~
