### ISSUE TITLE
Media Upload Using "Classic View" on Simple Sites appears not to work (But it does work)

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/wp-calypso#54397] opened 2021-07-08 19:59 UTC
When using the classic view toggle on Simple Sites and trying to upload new media, it will appear not to work, even though it does work.

### Steps to reproduce the behavior

1. On any simple site, open the media library.
2. Go to "Screen Options" at the top and click on "Classic View"
3. Click add new at the top, and then try to add a media file.
4. It will seem non-responsive, but the media does upload when you refresh the media library later.

#### What I expected to happen
To be shown a progress bar and then see my media appear in the media library when the upload was done.

#### What actually happened
It's non-responsive and I can't tell if the media uploaded or not.

#### Browser / OS version
Tried on FireFox and Chrome.

#### Does this happen on simple or atomic sites or both?
Simple Only

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects all simple sites, doesn't block any purchases.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
I am uploading the file here:

https://user-images.githubusercontent.com/49131029/124982985-a2b95000-dff4-11eb-80a5-c93c21491940.mp4

Refreshing reveals the file did upload.

<img width="1081" alt="Screen Shot on 2021-07-08 at 13-57-35" src="https://user-images.githubusercontent.com/49131029/124983040-b795e380-dff4-11eb-90b0-f9be524cc9fc.png">

**Comment by inaikem** [comment] 2021-07-14 06:48
Able to replicate on a Free and Premium site but _**not**_ a Personal site: I expected to be shown a progress bar and see my media appear in the Media Library when the upload was done. This did not occur.

On the Personal site, I was unable to replicate uploads to the Media Library via the in-line uploader (dragging or using the file dialog) or by dragging media into the main Media Library window.

4x uploads completed successfully with placeholders, progress bars and final thumbnails being created as expected.

**Comment by mpkelly** [comment] 2022-10-24 07:15
@KirkwallDay, I am unable to reproduce this issue after trying a couple of sites. It's likely been fixed. Could you retest it and close the issue down if it's working ok?


https://user-images.githubusercontent.com/6851384/197468812-c3397229-5d74-4bfd-9690-a3d27a653807.mp4

**Comment by vindl** [comment] 2022-12-07 12:22
I can't reproduce this either. @inaikem, feel free to reopen the issue if you can still reproduce it on your end.

**Closed as completed by vindl** 2022-12-07 12:22 UTC
Labels: Bug, [Pri] High, [Feature] Media, Triaged, Build Maintenance
