### ISSUE TITLE
Nav Unification — Cannot access "Settings → Hosting Configuration" when disabling masterbar

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#49364] opened 2021-01-27 21:57 UTC
### Steps to reproduce the behavior

1. Install the Code Snippets plugin: https://wordpress.org/plugins/code-snippets/
2. Create a new snippet called "Hide WPCOM Admin Toolbar"
3. The snippet code can be found in the FG, though I have copied it below. 
4. The "Settings → Hosting Configuration" link is missing, as shown here: https://d.pr/i/zPnQnj/XWLspKGmUA

Code snippet:

```
function disable_wpcomtoolbar ( $modules ) {
    if ( isset( $modules['masterbar'] ) ) {
      unset( $modules['masterbar'] );
    }
    return $modules;
}    
add_filter( 'jetpack_get_available_modules', 'disable_wpcomtoolbar' );
```

#### What I expected to happen

I expected to see the _Hosting Configuration_ menu item.

#### What actually happened

The menu item was missing from the menu. Deactivating the snippet resolved the issue. 

#### Does this happen on simple or atomic sites or both?

Atomic

#### Level of impact

As we've previously shared this code to customers looking to see the standard WordPress.org admin bar, there will likely be users reporting this issue when unable to access SFTP credentials, etc.

#### Screenshot / Video: 

<img width="993" alt="Markup 2021-01-27 at 14 53 02" src="https://user-images.githubusercontent.com/39252765/106059105-6f6eae80-60af-11eb-9be1-538f6fd3539d.png">

**Comment by metabreakr** [comment] 2021-01-28 15:24
Testing with "bleeding edge" Jetpack, as per paYJgx-1af-p2, doesn't seem to resolve the issue.

**Comment by tbradsha** [comment] 2021-01-29 14:38
Note that the issue seems to be that hiding the WPcom toolbar also hides things we need to show for the nav, so there should be a decoupling of masterbar and nav unification.

**Comment by metabreakr** [comment] 2021-01-29 17:09
@tbradsha Thanks for pointing that out! In my test site, I was using the [RTL Tester](https://wordpress.org/plugins/rtl-tester/) plugin which adds a button to the masterbar. For some plugins, there might not be another way to access their functionality.

**Comment by michaeldcain** [comment] 2021-02-01 22:43
@jonnyruzek: I edited the link to use our shorthand for public repos. See: PCYsg-5Xx-p2

**Comment by metabreakr** [comment] 2021-02-01 23:16
> @jonnyruzek: I edited the link to use our shorthand for public repos. See: PCYsg-5Xx-p2

Which link in particular?

**Comment by michaeldcain** [comment] 2021-02-01 23:21
@jonnyruzek: https://github.com/Automattic/wp-calypso/issues/49364#issuecomment-769160755

**Comment by getdave** [comment] 2021-02-02 15:50
Thanks for reporting folks.

We believe this one is going to help to resolve this.

https://github.com/Automattic/jetpack/pull/18586

**Comment by obenland** [comment] 2021-02-05 00:19
It will resolve it on the Calypso side, it will still be hidden in wp-admin

**Comment by cpapazoglou** [comment] 2021-02-10 14:16
Should we change the snippet to disable `nav-unification` also? Chances are that these customers will want to have a WordPress.org native experience.

**Comment by obenland** [comment] 2021-02-10 18:02
Nav unification is part of the masterbar module, so it'll disable it in wp-admin.

@jonnyruzek Is this fixe for you with Jetpack bleeding edge?

**Comment by metabreakr** [comment] 2021-02-10 18:51
@obenland With Jetpack Beta Tester 2.4.6 and bleeding edge Jetpack Version 9.5-alpha-554792241-gb4212cf this issue persists. The code snippet from above still hides the Hosting Configuration link.

**Comment by obenland** [comment] 2021-02-10 18:55
It hides in Calypso?

**Comment by metabreakr** [comment] 2021-02-10 19:01
Correct: https://d.pr/i/Q1arY2/xobnYwnMuC

**Comment by getdave** [comment] 2021-03-08 16:54
@jonnyruzek Is this still an Issue for you? Is it still a problem?

**Comment by metabreakr** [comment] 2021-03-08 18:43
@getdave Yes, with the code snippet activated I cannot access this menu link. Still using bleeding edge Jetpack (Version 9.6-alpha-633183928-g277707b)

**Comment by tbradsha** [comment] 2021-03-09 14:29
Note that this code is active on many user sites (not a majority, but it's also not rare).

**Comment by cpapazoglou** [comment] 2021-03-22 15:58
After having a discussion about this in our team call we came down to the following:

The problem is that `masterbar` & `nav-unification` may be disabled anytime cause they alter the UX in an unwanted way (even if we decouple `nav-unification` from `masterbar`). For these Users, we can "auto" activate another module (in wpcomsh) that will **just** add the required WPCOM menus like "Hosting Configuration", "Stats", "Upgrades" for starters.

**Comment by cpapazoglou** [comment] 2021-03-30 14:19
> After having a discussion about this in our team call we came down to the following:
> 
> The problem is that `masterbar` & `nav-unification` may be disabled anytime cause they alter the UX in an unwanted way (even if we decouple `nav-unification` from `masterbar`). For these Users, we can "auto" activate an other module (in wpcomsh) that will **just** add the required WPCOM menus like "Hosting Configuration", "Stats", "Upgrades" for starters.

Hey @jmdodd, I wonder if you could give us some technical direction here. Is my suggestion above a good practice for Atomic?

**Comment by Nic-Sevic** [comment] 2021-07-19 08:07
This is still occurring after the merge of the referenced similar issue: https://github.com/Automattic/jetpack/pull/18586

current case here: 4158565-zd-woothemes

@jmdodd Could you check the comment from cpapazoglou and see if this sounds workable for AT?

`The problem is that masterbar & nav-unification may be disabled anytime cause they alter the UX in an unwanted way (even if we decouple nav-unification from masterbar). For these Users, we can "auto" activate another module (in wpcomsh) that will just add the required WPCOM menus like "Hosting Configuration", "Stats", "Upgrades" for starters.`

**Comment by mmtr** [comment] 2021-12-21 14:52
> > It hides in Calypso?
> 
> Correct: https://d.pr/i/Q1arY2/xobnYwnMuC

On my tests, that's not the case. As of https://github.com/Automattic/jetpack/pull/18586, the "Settings > Hosting Configuration" menu always shows up in Calypso, even when the `masterbar` module is disabled.

It's only missing in WP Admin, but when a user disables the `masterbar` module, I think they intentionally want the default Core navigation in WP Admin. That was the case at least before Nav Unification was launched.

They shouldn't be expecting the "Settings > Hosting Configuration" menu, since that's not part of the default Core navigation. And if we add mechanisms to force its registration in `wpcomsh` as suggested above, that wouldn't feel like we're honoring our users preferences.

Let's close this issue out for now. Feel free to re-open if we start getting reports about users expecting the "Settings > Hosting Configuration" menu in WP Admin when the `masterbar` module is disabled.

**Closed as completed by mmtr** 2021-12-21 14:52 UTC
Labels: Bug, [Pri] Normal, [Feature] Calypso & wp-admin Navigation
