### ISSUE TITLE
Jetpack Carousel Gallery Opacity Issue

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#54505] opened 2021-07-13 12:52 UTC
### Steps to reproduce the behavior

1. On a simple site with the image carousel enabled, add a gallery block with a few images.
2. On the published version, click the images to launch the Jetpack image carousel.
3. Click forward to the second image, then click back to the first image again
4. Notice the images both have opacity set causing display issues.

![Screen Capture on 2021-07-13 at 05-41-01](https://user-images.githubusercontent.com/41035049/125454353-6c6e86f9-2ab3-443d-a02e-016639236674.gif)

I see the slide has this CSS active causing the opacity. Changing it to 0 seems to fix the issue:

```
.jp-carousel-slide {
    filter: alpha(opacity=25);
    opacity: 0.25;
}
```

Gutenberg: v11.0.0
CoBlocks: 2.10.1
Editing Toolkit: 3.10516
WP AMP: 2.0.5
#### Browser / OS version

Chrome 

#### Does this happen on simple or atomic sites or both?

 Simple

**Comment by khristiansnyder** [comment] 2021-07-13 12:53
Reported initially in #4133502-zen

**Comment by kosiew** [comment] 2021-07-14 06:50
Thanks @khristiansnyder for reporting this.

Closing this as duplicate of https://github.com/Automattic/jetpack/issues/20199

**Closed as completed by kosiew** 2021-07-14 06:50 UTC
Labels: Bug
