### ISSUE TITLE
[Bug]: Blank page when refreshing the confirmation stage of WooCommerce installation flow only for sites that don't have a sufficient plan

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#60684] opened 2022-01-31 19:45 UTC
### Quick summary

For sites that don't have a sufficient plan (WordPress.com Business plan or higher), visiting the last step of the WooCommerce installation flow and refreshing that page results in a blank, white page.

### Steps to reproduce

- Start with a site on the free, WordPress.com Personal plan or WordPress.com Premium plan.
- Click on WooCommerce menu on the left.
- Complete on-screen instructions and reach the last stage of the flow.
- Refresh the page.

### What you expected to happen

The page refreshes and shows the same warning: about requiring a plan upgrade.

### What actually happened

A blank, white page appears instead. Video of this happening:

https://user-images.githubusercontent.com/18581859/151861796-de94fa59-9079-468c-bf0c-2ed2bf6c0627.mov

Console shows this error:

```
Uncaught (in promise) Error: woocommerce-install did not provide the query dependencies [site] it is configured to.
```

### Context

Manual testing.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No and the platform is unusable

**Comment by kimerlin81** [comment] 2022-03-01 22:24
@arunsathiya Thank you for submitting this bug report! I was unable to reproduce this when tested on a Personal site with a custom domain and on a Premium site with no connected domain. Each time I refreshed, the last step page appeared as normal. I'll close this issue for now, but if you are still able to reproduce this, please feel free to reopen and update the comments.

https://user-images.githubusercontent.com/83732167/156259038-6bfb985f-1fb8-443f-ae22-5681093a9896.mp4

**Closed as completed by kimerlin81** 2022-03-01 22:24 UTC
Labels: Bug, [Pri] Low, Triaged, WooCommerce, Woop
