### ISSUE TITLE
Editor: Changing image size using + or - causes caption wonkiness

### ISSUE THREAD

**Issue by andreabadgley** [Automattic/wp-calypso#4654] opened 2016-04-11 20:03 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Add an image to the post using the Add media icon in visual editor.
3. Type a caption for Image 1 via the visual editor, eg `Image 1 caption`.
4. Add another image.
5. Type a caption for Image 2 via the visual editor, eg `Image 2 caption`.
6. Change size of Image 2 using + or - in the visual media editor.
7. Caption for Image 2 changes to caption from Image 1, eg changes from `Image 2 caption` to `Image 1 caption`.
#### What I expected

I expected my Image 2 caption to stay as the Image 2 caption when I edited the image size using + or -.
#### What happened instead

The caption for Image 2 changed to the Image 1 caption.
#### Browser / OS version

Firefox 45.0.1 and desktop app in OSX El Capitan v 10.11.3.
#### Screenshot / Video

https://cloudup.com/clOUczm9MuE

**Comment by supernovia** [comment] 2016-05-14 04:57
I was able to duplicate this as well on Chrome 50 (current) on Yosemite.

**Comment by KokkieH** [comment] 2016-10-03 08:49
Had another report on this in 786099-f, so this issue still exists.

**Comment by rachelmcr** [comment] 2017-12-23 16:29
Dupe of https://github.com/Automattic/wp-calypso/issues/2665.

**Closed by rachelmcr** 2017-12-23 16:29 UTC
Labels: Editor, [Type] Bug
