### ISSUE TITLE
Reader: tag links broken intermittently

### ISSUE THREAD

**Issue by automattic-ian** [Automattic/wp-calypso#40754] opened 2020-04-03 14:01 UTC
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read/
2. click a tag, it will load 
3. click a single post, then click the same tag,
4. it will take you to a blank screen It will also blank if you attempt to visit the tag url directly ex: https://wordpress.com/tag/food

#### What I expected
Tag links and URLS to load regardless of how they are accessed. 

#### What happened instead
Tag links only work in some parts of reader. 
#### Browser / OS version
Macos tested in Opera and Firefox, recorded in opera.

**Comment by lancewillett** [comment] 2020-04-04 19:25
Hi @automattic-ian Can you share if you are logged-in or logged-out?

Screenshots would also help set the context.

**Comment by lancewillett** [comment] 2020-04-04 19:28
I tried this out in Safari desktop on macOS, logged in as a non-a8c user.

From `https://wordpress.com/read` I clicked a tag in my sidebar:

`https://wordpress.com/tag/geography`

<img width="1392" alt="Screen Shot 2020-04-04 at 12 27 15" src="https://user-images.githubusercontent.com/66797/78459688-9f0b8080-766f-11ea-9a97-78bd0bc4d004.png">

Clicked into a single post: `https://wordpress.com/read/blogs/175331873/posts/21`

<img width="1392" alt="Screen Shot 2020-04-04 at 12 27 42" src="https://user-images.githubusercontent.com/66797/78459701-af236000-766f-11ea-8b44-bff6bda0519d.png">

Clicked `portugal` tag below the post title: `https://wordpress.com/tag/portugal`

<img width="1392" alt="Screen Shot 2020-04-04 at 12 28 09" src="https://user-images.githubusercontent.com/66797/78459715-bf3b3f80-766f-11ea-992f-c1c92fd09198.png">

Then, I type in `https://wordpress.com/tag/food` manually to the address bar and hit "Enter" to go to uit:

<img width="1392" alt="Screen Shot 2020-04-04 at 12 28 33" src="https://user-images.githubusercontent.com/66797/78459720-cd895b80-766f-11ea-9a25-611000b5d091.png">

Everything works as expected.

**Comment by automattic-ian** [comment] 2020-04-14 18:42
@lancewillett sorry for the delay. this was while logged in recording here: https://videopress.com/v/ODYbhZPZ

**Comment by bluefuton** [comment] 2020-06-09 03:37
Thanks for the video @automattic-ian. When you get the blank page, is there any error message in the browser console?

I can't reproduce it directly but I have found the `ignore-click` class being applied to those tag links, which seems an odd choice. I'll clean that up for starters.

**Comment by automattic-ian** [comment] 2020-06-09 05:15
@bluefuton  I'll take a peek tomorrow, I was actually going to close this issue today because I couldn't seem to reproduce anymore, so I assumed it had been fixed, but it was consistently reproducible when that video was made :/ if memory serves I didn't see any console errors, or  I think I would have made note of them.

**Comment by bluefuton** [comment] 2020-06-25 00:24
Going to close this for now. If you do manage to repro @automattic-ian please reopen this one 👍

**Closed by bluefuton** 2020-06-25 00:24 UTC
Labels: Reader, [Type] Bug
