### ISSUE TITLE
Layout picker: Barnsbury preview colors don't match thumbnail

### ISSUE THREAD

**Issue by dwolfe** [Automattic/wp-calypso#38066] opened 2019-11-29 18:58 UTC
The Barnsbury theme thumbnail in the layout picker has a green background in the cover block, but the preview cover block background is brown.

### Steps to reproduce
1. Invoke the layout picker, either in the document sidebar; or by signing up as a new user in the test-fse flow and clicking "Edit Homepage" from the checklist
2. Click on the Barnsbury thumbnail
3. See preview with brown cover background (thumbnail background is green)

### What I expected
I guess "layout" doesn't indicate styling - this might be a feature, not a bug, if it makes the point that you're only choosing structure - but I think most users will expect the preview to agree with the thumbnail they've clicked.

#### Screenshot / Video
![Screen Shot 2019-11-29 at 10 53 40 AM](https://user-images.githubusercontent.com/1348738/69886434-c0f69000-1296-11ea-8008-0860e2b89e63.png)

**Comment by obenland** [comment] 2020-03-11 21:27
I'm going to close this as a duplicate of #39352. It will be fixed in D39999-code.

**Closed by obenland** 2020-03-11 21:27 UTC
Labels: [Goal] Page Templates, [Type] Enhancement
