### ISSUE TITLE
Signup: survey step bleeds onto design-type

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#7037] opened 2016-07-26 16:52 UTC
![](https://cloudup.com/cxa2bFoTOYJ+)

#### Steps to reproduce
1. Starting at URL: wordpress.com/start
2. Tap survey option 2x very quickly
3. Survey persists and overlays the design-type step

Tested and repro'ed consistently on Safari, Chrome, and Firefox

**Comment by lancewillett** [comment] 2016-10-17 18:35
I can't repro this as fast as I can click and double-click. What's the real-world scenario we're trying to avoid, a double click?

**Comment by bisko** [comment] 2016-10-18 07:36
This was occurring when the user clicked way too fast through the Survey step in Signup. It seems to be not reproducible right now, probably fixed with some changes that got merged since the bug was opened.

**Closed by bisko** 2016-10-18 07:36 UTC
Labels: NUX, Signup, [Type] Bug
