### ISSUE TITLE
Page Break block not working with Vivre theme.

### ISSUE THREAD

**Issue by radtechgh** [Automattic/wp-calypso#83056] opened 2023-10-16 16:05 UTC
### Quick summary

Page break block added to page. All items under page break missing on Live page. Disabling Gutenberg plugin is a workaround.

### Steps to reproduce

1. Switch theme to Vivre.
2. Add page with content, including Page Break block.
3. Publish page.
4. All content below page break block is missing.

### What you expected to happen

Block should cause all content below block to be added to additional pages, adds pagination links.

### What actually happened

All content below the Page Break block is missing. Page goes directly to footer.

### Impact

One

### Available workarounds?

Yes, easy to implement

**Comment by radtechgh** [comment] 2023-10-16 16:05
7119217-zen

**Comment by cuemarie** [comment] 2023-10-16 18:20
Duplicate of https://github.com/Automattic/wp-calypso/issues/81898

**Closed as not planned by cuemarie** 2023-10-16 18:20 UTC
Labels: Bug, Triaged, Customer report [LEGACY], [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks
