### ISSUE TITLE
Media: JS error prevents completion of upload/interaction

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#7855] opened 2016-09-04 21:31 UTC
#### Steps to reproduce
1. In the editor for a Jetpack site, click to add Media
2. Drag and drop a bunch of images
3. In my case, one apparently triggered this error:

![screen shot 2016-09-04 at 3 26 33 pm](https://cloud.githubusercontent.com/assets/108942/18234011/732e4a78-72b4-11e6-998f-d17a94d56f3c.png)
1. Check console and see this error:

![screen shot 2016-09-04 at 3 26 36 pm](https://cloud.githubusercontent.com/assets/108942/18234013/7a3d8e14-72b4-11e6-8efe-470bbb16bdcb.png)

Don't know if they're specifically related, but wanted to mention here because either way, the JS error that's being thrown should be caught properly. I _think_ the original error is probably because I was uploading a large panorama and my server couldn't handle resizing/processing it.

At this point, my uploads appear to have hung, and the UI is mostly unresponsive, with progress spinners on my not-uploaded-images-yet, but no actual progress happening.

Closing the media modal and opening it back up again shows me the partial state still, so I ended up forcing a refresh of the page.

I repeatedly received a similar UI-based error (not the JS one), but upon checking in wp-admin, the image had in fact uploaded into Media Library, so I'm not sure what was going on there. Perhaps there'ssome sort of returned response that's not being handled properly?
#### Context / Source
# reallife #dogfooding

**Comment by designsimply** [comment] 2016-10-31 21:16
I tried reproducing this problem using the steps provided on a site running WordPress 4.6.1 and Jetpack Beta (Build 1736083) in Safari 10.0 on Mac OS X 10.11.6, including a panorama image that was 10.9 MB, and I was unable to trigger the error: `1 file could not be uploaded because an error occurred while uploading.`

It's possible the image from the original issue was corrupt or perhaps I didn't try uploading an image that was large enough or I didn't use enough images at once. I recommend closing this issue next time it comes up in a #bug-scrub if there are no further reports or added detail about how to reproduce the problem.

**Closed** 2017-02-01 17:32 UTC
Labels: Media, [Type] Bug
