### ISSUE TITLE
Comments: "LikeLike" Text Appears When Comment is Awaiting Moderation

### ISSUE THREAD

**Issue by karenroldan** [Automattic/wp-calypso#82177] opened 2023-09-26 13:21 UTC
### Quick summary

When a user submits a comment and it is awaiting moderation, the preview of the comment displays the text "LikeLike" at the end.

![o0WqvO.png](https://github.com/Automattic/wp-calypso/assets/67279475/bfd0b0f5-f314-4ae9-ab54-37fc0bc74533)

**Actual comment**

![mMN0W0.png](https://github.com/Automattic/wp-calypso/assets/67279475/1d1ccb29-323b-4cc9-9529-086881380e67)

**Approved comment**

![yNrFw8.png](https://github.com/Automattic/wp-calypso/assets/67279475/93872aba-1888-4084-b90f-47b81a167ff6)

### Steps to reproduce

1. Submit a comment on a post. 
2. View the comment while it's awaiting moderation. 
3. Observe the "LikeLike" text at the end of the comment preview. 
4. Once the comment is approved, notice that the "LikeLike" text is replaced with the actual "like" link.

### What you expected to happen

During the moderation preview, the comment should not display the "LikeLike" text. It looks like the user accidentally added that text as part of the comment.

### What actually happened

The text "LikeLike" is appended to the comment while awaiting moderation. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

@Automattic/vertex

**Comment by karenroldan** [comment] 2023-09-29 20:13
Also reported by @davemart-in in p1696012294508049-slack-C02T4NVL4JJ

**Comment by alshakero** [comment] 2023-10-02 09:16
Hi Karen, I have seen this bug but now I can't reproduce in Blank Canvas nor Seedlet. Can you share the theme?

**Comment by alshakero** [comment] 2023-10-02 09:47
Will be fixed in D123837-code

**Comment by alshakero** [comment] 2023-10-02 10:32
Closing as fixed in D123837-code

**Closed as completed by alshakero** 2023-10-02 10:32 UTC
Labels: Bug, [Pri] Low, [Feature] Comments, Triaged, [Platform] Simple, [Product] WordPress.com, [Feature Group] Content Management
