### ISSUE TITLE
Theme Bundling: Site did not revert themes after cancelling plan

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#69999] opened 2022-11-14 15:38 UTC
A user purchased a Business plan and started using the Tsubaki theme. After they cancelled their Business plan, Tsubaki stayed as the active theme instead of the site being reverted to the previous theme.

More details at p1668105570566419-slack-C0Q664T29

**Comment by sixhours** [comment] 2023-03-16 21:35
Additional context in p7DVsv-fH5-p2#comment-42834

**Comment by sixhours** [comment] 2023-03-16 21:58
I'm able to reproduce this, but I think it might be user confusion. Steps I took:

1. Purchase a Business plan, activate Tsubaki theme.
2. Go to Upgrades -> My Plan -> Manage plan -> Cancel plan
3. Confirm cancellation.
4. My site still has the premium features, including Tsubaki.
5. Go back to Upgrades -> My Plan  and notice that the expiration on my Business plan is still one year from the purchase date.
6. Click Manage plan.
7. I clicked "Remove plan", which used to be "Cancel plan".
8. Now I'm asked to confirm the removal, and I do.
9. My site is fully reverted back to it's pre-premium state, including Tsubaki being deactivated.

Maybe the user had paid upfront and had a portion of time left on the Business plan, but did not fully remove it from the site?

**Comment by sixhours** [comment] 2024-03-18 10:25
Closing since this hasn't been reported since.

**Closed as completed by sixhours** 2024-03-18 10:25 UTC
Labels: [Feature Group] Appearance & Themes, Customer report [LEGACY], [Theme] Tsubaki
