### ISSUE TITLE
FSE: Single page template intermittently showing homepage content

### ISSUE THREAD

**Issue by CodeAllNightNDay** [Automattic/wp-calypso#64235] opened 2022-05-23 18:32 UTC
### Quick summary

I have a user who installed the Videomaker White theme and there is an issue with the single page template. When you first go to Appearance > Editor and pull up the single page template, it is also showing the homepage content from a single standalone page set as the homepage. If you navigate to the templates and go back to the single page template from there, then you see the single page template as expected.

5237955-zen

### Steps to reproduce

1. Install Videomaker white theme (or other Block themes) on a simple or Atomic site.
2. Create a homepage with content and set it as the homepage.
3. Go to Appearance > Editor and edit the single-page template.

### What you expected to happen

I expected to only see the single-page template content, not the homepage content.
Please download the video of the issue from here: https://d.pr/v/1sVadu

### What actually happened

I see the single-page content in addition to the homepage content.

### Context

I have one user so far with the issue and can reproduce it on two test sites (one atomic and one simple)

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

I have been able to reproduce on Videomaker so far, both on simple and atomic. I also tried it on the Archeo theme, so this seems to be happening on multiple block themes.

### Browser, operating system and other notes

All my testing has been done in Chrome.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Navigate from single page template to all templates, then select the single page template again and it will show as expected.

**Comment by Robertght** [comment] 2022-06-01 10:40
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes/No

📌 SCRUBBING
- Tested on P2 - No 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can confirm this is an issue with all FSE themes. I tested with 2022 and the same thing happens on WordPress.com and on a self-hosted site.

cc @Automattic/cylon 

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Added to 'HE User Waiting (Need bulk replies)' project board

**Comment by jordesign** [comment] 2022-06-15 03:21
@annezazu @jeffikus Not sure if this should be considered a T22 issue, or Core Gutenberg/FSE issue. Any suggestions?

**Comment by annezazu** [comment] 2022-06-15 05:28
I'm afraid this isn't a bug but this is actually working as intended from what I can see. Essentially, the user is setting a homepage page. When that page is set, it is then displayed when going to Appearance > Editor as that is designed to show what is set to the homepage. From there, when they navigate to the more _general_ template for individual pages (1:41), it's then showing placeholder content as this is the template used for any page on the site. 

Here's a video of me showing/talking this through as this honestly took me a minute to wrap my head around personally since I kept expecting a bug :) A bit later for me for now so happy to answer questions when I'm online in the morning but wanted to at least share what I found:

https://user-images.githubusercontent.com/26996883/173745094-ffd6dd9a-d776-480a-91d5-9cc2f981b0b7.mov

**Comment by Robertght** [comment] 2022-06-15 18:52
Thank you @annezazu! TIL on the above so if there isn't anything else to add here, we can close it. 

Should this part be more explicit in the documentation though?

**Comment by annezazu** [comment] 2022-06-16 01:36
Yes! I think that makes sense to update for docs. It's included in wporg (but lightly): https://wordpress.org/support/article/template-editor/#how-to-edit-templates-via-the-site-editor

**Comment by cuemarie** [comment] 2022-08-24 00:38
📌 ACTIONS
-
- Closing report following thread above. Thanks!

@Robertght as you're familiar with the issue following your triage, would you mind [requesting a WPcom doc update](https://github.com/Automattic/en.support-docs-content/issues/new/choose) following this discussion?

**Closed as completed by cuemarie** 2022-08-24 00:38 UTC
Labels: Bug, [Pri] Normal, Triaged, [Feature] Full Site Editor
