### ISSUE TITLE
Editing Tiled Gallery shows The editor has encountered an unexpected error

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#60335] opened 2022-01-21 07:33 UTC
### Quick summary

When editing an existing Tiled Gallery and adding a new image to the gallery it is showing the `The editor has encountered an unexpected error` error.

I was not able to replicate the issue on my test Atomic site.

The user didn't have any extraordinary plugins installed. Even after deactivating them the issue persisted.

Screencast video on how I was able to replicate the issue on the user's site:

https://user-images.githubusercontent.com/7382505/150485143-5e8ccea7-9bd9-451f-bfdc-cb88bde9dd76.mp4

Here is the error shown from the `The editor has encountered an unexpected error` message:

```
Error: Minified React error Automattic/wp-calypso#185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Pa (https://mexisoulretreats.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:157:57)
    at Me (https://mexisoulretreats.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:110:250)
    at https://mexisoulretreats.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=22350e34cf787011b5a11372d3eba6a4:70:9206
    at Tj (https://mexisoulretreats.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:179:399)
    at unstable_runWithPriority (https://mexisoulretreats.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://mexisoulretreats.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at Ra (https://mexisoulretreats.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:178:368)
    at gf (https://mexisoulretreats.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:161:497)
    at https://mexisoulretreats.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:230
    at unstable_runWithPriority (https://mexisoulretreats.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
```

### Steps to reproduce

1. Add Tiled Gallery to Atomic site page and publish it.
2. Edit the gallery and select Add to gallery option.
3. Select a new image and click on Add to Gallery button.
4. You'll now see the `The editor has encountered an unexpected error` error.

### What you expected to happen

The newly selected image should show up on the Tiled Gallery block.

### What actually happened

The `The editor has encountered an unexpected error` was shown.

### Context

Customer report

**Comment by filipanoscampos** [comment] 2022-01-29 10:15
We have a similar issue on a Simple site.
Reported here 4689855-zd-woothemes.

They shared the following error with us:

```
Pa@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:36479
Me@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:12897
Pv/<@https://s0.wp.com/_static/??-eJyl0s0OwjAIB/AXsq2dczfjs/SDTLauLJRu+vZObx5Nj0DyC5C/2VcVKAtkMWuqI+ZixnqUHng8Jgxms53utTW+Yopmhpcnx1GVB7GEKsVgjvDUC2Y9lZP5F8wkGKBVEZohq4RFGqGdOAaqudXxicKsIKIQN1KflopOXKPDUIvzCdR3t9aPF+ANWBWMoBgOqvXMDWFfj0z9MPflZoe+G+x1OF+mNwVf94w=:74:9207
Tj@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:9:2433
unstable_runWithPriority@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react.min.755b0ae9.js?m=1624062436h:5:3609
Za@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12302
Ra@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:9:1901
gf@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8:2014
$g/<@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12524
unstable_runWithPriority@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react.min.755b0ae9.js?m=1624062436h:5:3609
Za@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12302
$g@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12472
ja@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12405
Pa@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:36634
Me@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:12897
e@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:21706
t@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:21773
Z/d/t.subscribe/o<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:16977
q/instantiate/y</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:15264
p@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:6880
q/instantiate/</</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:12557
i/</</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:11:8781
P/</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:9108
C/</</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:10112
q/instantiate/get dispatch/<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:12872
$/<@https://s0.wp.com/_static/??-eJyl0s0OwjAIB/AXsq2dczfjs/SDTLauLJRu+vZObx5Nj0DyC5C/2VcVKAtkMWuqI+ZixnqUHng8Jgxms53utTW+Yopmhpcnx1GVB7GEKsVgjvDUC2Y9lZP5F8wkGKBVEZohq4RFGqGdOAaqudXxicKsIKIQN1KflopOXKPDUIvzCdR3t9aPF+ANWBWMoBgOqvXMDWFfj0z9MPflZoe+G+x1OF+mNwVf94w=:98:11676
q/instantiate/</</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:12552
i/</</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:11:8781
P/</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:9108
C/</</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:10112
q/instantiate/f</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:13265
6682/</dispatch/</n[e]@https://widgets.wp.com/wpcom-block-editor/wpcom.editor.min.js?ver=20220124213542:22:45938
Wt/l<@https://s0.wp.com/_static/??-eJyl0s0OwjAIB/AXsq2dczfjs/SDTLauLJRu+vZObx5Nj0DyC5C/2VcVKAtkMWuqI+ZixnqUHng8Jgxms53utTW+Yopmhpcnx1GVB7GEKsVgjvDUC2Y9lZP5F8wkGKBVEZohq4RFGqGdOAaqudXxicKsIKIQN1KflopOXKPDUIvzCdR3t9aPF+ANWBWMoBgOqvXMDWFfj0z9MPflZoe+G+x1OF+mNwVf94w=:98:43472
Wa/</d<@https://s0.wp.com/_static/??-eJyl0s0OwjAIB/AXsq2dczfjs/SDTLauLJRu+vZObx5Nj0DyC5C/2VcVKAtkMWuqI+ZixnqUHng8Jgxms53utTW+Yopmhpcnx1GVB7GEKsVgjvDUC2Y9lZP5F8wkGKBVEZohq4RFGqGdOAaqudXxicKsIKIQN1KflopOXKPDUIvzCdR3t9aPF+ANWBWMoBgOqvXMDWFfj0z9MPflZoe+G+x1OF+mNwVf94w=:14:59423
Y/n/<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:15663
n@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:15651
emit@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:15798
i@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:15985
Z/d/t.subscribe/o<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:16977
q/instantiate/y</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:15264
p@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:6880
q/instantiate/</</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:12557
i/</</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:11:8781
P/</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:9108
C/</</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:10112
q/instantiate/f</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:13265
setAttributes@https://s0.wp.com/_static/??-eJyl0s0OwjAIB/AXsq2dczfjs/SDTLauLJRu+vZObx5Nj0DyC5C/2VcVKAtkMWuqI+ZixnqUHng8Jgxms53utTW+Yopmhpcnx1GVB7GEKsVgjvDUC2Y9lZP5F8wkGKBVEZohq4RFGqGdOAaqudXxicKsIKIQN1KflopOXKPDUIvzCdR3t9aPF+ANWBWMoBgOqvXMDWFfj0z9MPflZoe+G+x1OF+mNwVf94w=:14:53527
xe/</</n</</<@https://s0.wp.com/_static/??-eJylkkGOwjAMRS9E6ikw3Y04S5tYrUsSl9gucHvCFrEZZWnZevp6/nDfnOesmBW2aDNlgdnqOGGZ66Yg7P2xO3c9TEYxAImTZYyR7w5vNkagHPDRJcrdKgf4L+6KT88BpRGzFeJC+nQ3Q8NGmOe0sbRSCgZ7uMKmlFtZYdSxEbFoiq5ek1KzbVm46PttjZwpsr9+CUPZR3uXYhUIJAo75sAFEqfKbrHYmrj2LFWD+4fCS/rrh/Nx6H+Hn9P6AuVJM8k=:12:22498
setAttributes@https://s0.wp.com/_static/??-eJx9UVtywjAMvFBtEwqUn06P0nFs1SjxI3Vkkty+ApIOQ2k+PBqvtKuVpIZOmBQJIqnOF4exV67wt4bsOJNBnaut3MlK1QW9VTrGRJowcSFGC6MMGGXTv6g7pVDEItYAddq06hOjUbVPpu0VWKSUBYwdZAxM0P5RYaH3E2fHE7qT50eQlcWeZiF5tfQfdXWMDNqQwOoY/07BTn2xwN65f/ccb74L5GkO8r5qsXEhgwdD2yU+25S2DP4uy6QQSkSaBGnneNhHYGXRA1oHxMs9c6LOSHCxcEPFtc0KWbfYB657lZvbpWZg3e7QscQXgK35wlz6Ed6rw277tt8fN4fmBy9b3yE=:79:9268
4382/y/<@https://s0.wp.com/_static/??-eJx9UVtywjAMvFBtEwqUn06P0nFs1SjxI3Vkkty+ApIOQ2k+PBqvtKuVpIZOmBQJIqnOF4exV67wt4bsOJNBnaut3MlK1QW9VTrGRJowcSFGC6MMGGXTv6g7pVDEItYAddq06hOjUbVPpu0VWKSUBYwdZAxM0P5RYaH3E2fHE7qT50eQlcWeZiF5tfQfdXWMDNqQwOoY/07BTn2xwN65f/ccb74L5GkO8r5qsXEhgwdD2yU+25S2DP4uy6QQSkSaBGnneNhHYGXRA1oHxMs9c6LOSHCxcEPFtc0KWbfYB657lZvbpWZg3e7QscQXgK35wlz6Ed6rw277tt8fN4fmBy9b3yE=:79:7895
5085/A/r/</e.port1.onmessage@https://widgets.wp.com/wpcom-block-editor/calypso.editor.min.js?ver=20220124213542:22:7882
```

**Comment by aleone89** [comment] 2022-02-03 11:27
Another report: hc-31852865

The error was: 

```
Error: Minified React error Automattic/wp-calypso#185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Pa (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:36479)
    at Me (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:12895)
    at https://s0.wp.com/_static/??-eJyl0s0OwjAIB/AXsq2dczfjs/SDTLauLJRu+vZObx5Nj0DyC5C/2VcVKAtkMWuqI+ZixnqUHng8Jgxms53utTW+Yopmhpcnx1GVB7GEKsVgjvDUC2Y9lZP5F8wkGKBVEZohq4RFGqGdOAaqudXxicKsIKIQN1KflopOXKPDUIvzCdR3t9aPF+ANWBWMoBgOqvXMDWFfj0z9MPflZoe+G+x1OF+mNwVf94w=:74:9206
    at Tj (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:9:2433)
    at unstable_runWithPriority (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react.min.755b0ae9.js?m=1624062436h:5:3609)
    at Za (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12302)
    at Ra (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:9:1901)
    at gf (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8:2014)
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12524
    at unstable_runWithPriority (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.4.1/vendor/react.min.755b0ae9.js?m=1624062436h:5:3609)
```

**Comment by KokkieH** [comment] 2022-02-08 05:24
Another report in https://wordpress.com/forums/topic/error-when-editing-gallery-module/?view=all

Simple site.

Noting that their gallery has over 50 images in it. I'm able to replicate on a test site, and it starts happening exactly at 53 images - up to 52 images the gallery works fine, but the moment I add one image over that, the error occurs. So this might be specific to the size of the gallery in question.

The error does not occur when adding more than 52 images to the core gallery block, so suggesting that as a workaround for now.

**Comment by Greatdane** [comment] 2022-02-10 05:35
Nice sleuthing! I can confirm if you add **more than 53 images** on **Simple** site, the error occurs.

```
Error: Minified React error Automattic/wp-calypso#185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Pa (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:7:36479)
    at Me (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:7:12895)
    at https://s0.wp.com/_static/??-eJyl0kkOwjAMBdALkUQdgBXiLBms4jaNK8dp4fYEdixRlralJ9v65tiUpySQxGyxTJiymUotHfBUJwxm73p91qNxBWMwC7wcWQ4qP4jFF8kGU4CnXjHpOZ/Mv2AiQQ+titACSUXM0ggdxMFTSa2Oi+QXBQGFuJH6tFSwYhsdhpKti6C+u7V+PAPvwCpjAMVQqdYzd4Rjq5n6Ye7rrbuM4zBc+3GY3zYu97M=:74:9206
    at Tj (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:9:2433)
    at unstable_runWithPriority (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react.min.755b0ae9.js?m=1644337243h:5:3609)
    at Za (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:6:12302)
    at Ra (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:9:1901)
    at gf (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:8:2014)
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:6:12524
    at unstable_runWithPriority (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react.min.755b0ae9.js?m=1644337243h:5:3609)
```

**Comment by kimerlin81** [comment] 2022-02-25 13:38
Another reported incident - 34371808-hc
This error also occurs when there's an attempt to change the block style.
Seems to be intermittent.

**Comment by dolgelukkig** [comment] 2022-05-08 12:25
Another one 35419650-hc

**Comment by yansern** [comment] 2022-06-13 14:16
Marking this a duplicate of https://github.com/Automattic/jetpack/issues/25017.

**Closed as completed by yansern** 2022-06-13 14:16 UTC
Labels: Bug, [Pri] Normal, [Block] Tiled Gallery, Triaged
