### ISSUE TITLE
Missing CTA for community themes

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#94495] opened 2024-09-12 15:04 UTC
### Quick summary

A CTA isn't always displayed when viewing community themes in the theme showcase. 

 * A site that is capable of installing a community theme (e.g. atomic or business simple) has a "Activate this design" CTA. ![image](https://github.com/user-attachments/assets/6695f067-ffb3-4691-a11d-772f6283db6a)
 * A site that isn't currently capable of installing a community theme (e.g. a free site) doesn't have a CTA.
 * Browsing the theme showcase without a site selected also doesn't show a CTA
 * Browsing the logged-out theme showcase does show a CTA.

This is a side-effect of https://github.com/Automattic/wp-calypso/pull/94264, previously the dotorg themes must have relied upon the presence of the upsell banner removed in that PR.

### Steps to reproduce - incapable site selected

1. Go to wordpress.com/home and select a site on the free/personal/premium plan
2. Navigate to the theme showcase (Appearance → Themes)
3. Search for a community theme for example "Kubrick 2024"
4. Click on the theme

### What you expected to happen  - incapable site selected

To see a CTA that says "Upgrade to activate". 

Something like this but with "Upgrade to activate" on the CTA <img width="1163" alt="Screenshot 2024-09-12 at 15 59 32" src="https://github.com/user-attachments/assets/a9a234e8-eb96-43f6-bd27-15476ddcfd67"> but 

### What actually happened - incapable site selected

No CTA, it's not clear what to do next

<img width="1163" alt="Screenshot 2024-09-12 at 15 59 17" src="https://github.com/user-attachments/assets/d371933c-fb90-44ea-aa14-a913a5e38fdf">

### Steps to reproduce - no site selected

1. Go to wordpress.com/themes
2. Search for a community theme for example "Kubrick 2024"
3. Click on the theme

### What you expected to happen  - no site selected

To see a CTA that says "Select a site for this theme", like the other themes have.

### What actually happened - no site selected

No CTA, it's not clear what to do next

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by m1r0** [comment] 2024-09-12 15:41
I can confirm this one. It looks like it affects many people so I'm leaving it as a high priority.

@eoigal do you have the bandwidth to check this out?

**Comment by Addison-Stavlo** [comment] 2024-09-12 16:21
> @eoigal do you have the bandwidth to check this out? 

Eoin is a teammate and polishing other items at the moment, but I can pick this up.

**Comment by dsas** [comment] 2024-09-12 16:29
You probably need to wrestle something in [theme-options.js](github.com/automattic/wp-calypso/tree/trunk/client/my-sites/themes/theme-options.js) for a CTA to go to the URL that the old banner used to go to (probably can find via https://github.com/Automattic/wp-calypso/pull/94264).

@Copons would probably appreciate a ping once you're done so he can adjust his theme funnels if necessary (he also loves working on theme-options.js). Happy to help if you need it :)

**Comment by Addison-Stavlo** [comment] 2024-09-12 18:59
Thanks @dsas !

This area sure seems to be full of context I am not fully up to speed on 😅 , but I have an initial attempt at resolving here https://github.com/Automattic/wp-calypso/pull/94505

**Comment by dsas** [comment] 2024-09-12 20:35
That's a polite way of saying it is full of dragons and trapdoors 😆 . I've had an initial look but I'll take a look again and test tomorrow. It's a bit fragile.

**Comment by Addison-Stavlo** [comment] 2024-09-13 19:42
> That's a polite way of saying it is full of dragons and trapdoors

🤣  In the context of dragons and trapdoors. 😓  Sounds like the name of a power metal song.

**Comment by rcrdortiz** [comment] 2024-09-27 13:49
These changes are live

**Closed as completed by rcrdortiz** 2024-09-27 13:49 UTC
Labels: Bug, [Pri] High, Triaged, Needs triage, [Feature] Theme Showcase, [Status] Priority Review Triggered, Groundskeeping
