### ISSUE TITLE
Vimeo video widget not playing on Chrome 

### ISSUE THREAD

**Issue by sourourn** [Automattic/wp-calypso#31452] opened 2019-03-14 08:26 UTC
It seems Chrome is blocking vimeo video widgets from playing. User added test videos on this page: https://savegrampiansclimbing.org/test-page/ When you try to play the widgets videos, none of them play. I found the following console errors: https://cld.wthms.co/5v7Di5 It seems to be related to Chrome’s autoplay policy changes: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes . Also the widget videos do start playing after you play the one in the main body content. But if you refresh the page, it won’t work again until you play the video in the body content. Pasting the video link into a text widget does work.

#### Steps to reproduce
1. Starting at URL: My Site > Customize > Widgets 
2. Add Video widget > select add from URL > Paste vimeo URL link > Publish
3. Open the live page and try to play the video in Chrome browser

#### What I expected
Video plays. 

#### What happened instead
Video shows a loading icon but does not play.

#### Browser / OS version

Version 72.0.3626.119 (Official Build) (64-bit)
#### Screenshot / Video

Screencast: https://cld.wthms.co/wYxaWE

Console errors: 
![Screen Shot 2019-03-13 at 10 40 49](https://user-images.githubusercontent.com/39188945/54341753-4d96ea80-4643-11e9-93cb-5bdb1bcc6084.png)

User details:
- Ticket: 1872173-zen
- Site: https://savegrampiansclimbing.org/test-page/

**Comment by zdenys** [comment] 2019-03-15 09:58
I cannot reproduce this in Chrome 72.0.3626.121. For me, the video in the sidebar plays right away, without first playing the video in the body. And I don't see any errors in the Console either https://cld.wthms.co/aDkLG0

**Comment by mdrockwell** [comment] 2019-03-15 14:34
I also tested this on Chrome 72.0.3626.121 and couldn't recreate it. Since we've been getting inconsistent results, I've asked the user for more information about their setup, perhaps they're using an older version of Chrome or it's specific to their configuration.

**Comment by katinthehatsite** [comment] 2019-03-16 12:00
I was not able to replicated either on Chrome `72.0.3626.121`. The user has sent us their browser info which can be found here: https://www.whatismybrowser.com/w/QJMCDDQ
It seems that they are also using the most recent version `72.0.3626.121`. 
I asked them to check if they have any browser extensions, disable all of those, clear cache and try accessing the site again.

**Comment by katinthehatsite** [comment] 2019-03-16 12:09
<img width="1456" alt="Screen Shot 2019-03-16 at 8 08 21 AM" src="https://user-images.githubusercontent.com/25575134/54475020-b658a100-47c2-11e9-928d-ad38fb2e585b.png">

**Comment by katinthehatsite** [comment] 2019-03-16 13:14
Another note is that I tested it with another theme - Ixion - on my test site in incognito window and got the same error:

**Comment by lancewillett** [comment] 2019-05-31 21:09
It is possible Chrome (or Google) could be blocking certain media from playing; but it's more likely something else. Like a Chrome extension, ad blocker software, or some other connectivity issue.

I'm going to close this one since it's a minor edge case — but if you see something wider spread please report it.

**Closed by lancewillett** 2019-05-31 21:09 UTC
