### ISSUE TITLE
Gutenboarding: ensure the site gets created with the correct theme, template, and font pairing

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40561] opened 2020-03-30 08:07 UTC
In Gutenboarding, after customer has chosen design and font pairing, the site should be created with correct:

- [ ] theme
- [ ] template as home page
- [ ] font pairing set in global styles

I haven't confirmed if this already is the case.

**Comment by simison** [comment] 2020-03-30 13:45
@sirreal were you already familiar with these APIs?

**Comment by sirreal** [comment] 2020-03-30 15:04
Duplicate of #40513

**Comment by sirreal** [comment] 2020-03-30 15:05
> @sirreal were you already familiar with these APIs and would you like to look into it?

I've assigned myself to #40513

**Closed by sirreal** 2020-03-30 15:04 UTC
Labels: [Goal] Gutenboarding, [Pri] High, [Type] Task
