### ISSUE TITLE
Facebook Page Plugin widget does not appear on the iPad

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#68354] opened 2022-09-27 16:11 UTC
### Quick summary

When a Facebook Page Plugin widget is added to a footer widget area, it does not show up when viewed from an iPad (other devices might be affected too).

### Steps to reproduce

1. Activate Sela theme.
2. Add a Facebook Page Plugin widget to a footer area.
3. Add a Facebook page URL and save the widget.
4. Visit the site from an iPad.

### What you expected to happen

To see the Facebook page widget on the site footer.

### What actually happened

The widget does not appear.

### Context

5589070-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Issue noticed initially in Sela.
Replicated in Hemingway Rewritten.

**Comment by jamiepalatnik** [comment] 2022-09-29 18:41
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Was able to replicate on iPhone and iPad with multiple themes. 
- Searching further it looks like this is already reported here: https://github.com/Automattic/jetpack/issues/24745

📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/jetpack/issues/24745

📌 Message to Author
- @ariel-maidana I'll add the ticket link in that other report. Thanks!

**Closed as completed by jamiepalatnik** 2022-09-29 18:41 UTC
Labels: Bug, [Platform] Simple
