### ISSUE TITLE
Components: Video Refresh Card icon misaligned on Safari, Chrome v50

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#9000] opened 2016-10-28 14:55 UTC
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/blocks/refresh-cards
2. Use Safari (seen on v9 and v10) or Chrome v50
#### What I expected

The Play icon to be centered in the image
#### What happened instead

The middle of the triangle is centered on the top of the image:

![screen shot 2016-10-28 at 10 46 42 am](https://cloud.githubusercontent.com/assets/7233112/19810687/77bf7270-9cfc-11e6-8c2e-584936f1edda.png)

cc: @samouri #8704 
#### Browser / OS version

Seen in Safari v9 and v10, Chrome v50.  Newer versions of Chrome don't have the problem
#### Context / Source
# automated-testing, #visdiff

**Comment by samouri** [comment] 2016-10-31 22:18
Thanks for noticing this! I'm going to close it though as a dupe of #8987.

**Closed by samouri** 2016-10-31 22:18 UTC
Labels: Components, [Type] Bug
