### ISSUE TITLE
WebPreview: Infinite Scroll not working with a custom domain set as primary

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#6346] opened 2016-06-27 20:54 UTC
#### Steps to reproduce
1. Access a site that has a custom domain as the primary for the website (mysite.com instead of mysite.wordpress.com)
2. Click on the WebPreview
3. Scroll down the preview until you get to the infinite scroll area

#### What I expected

To see the infinite scroll in action.

#### What happened instead

Console displays the following message:

```XMLHttpRequest cannot load https://mysite.com/?iframe=true&theme_preview=true&infinity=scrolling. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mysite.com.wordpress.com' is therefore not allowed access.```

#### Browser / OS version
OS X 10.10.5, tested with Chrome 51.0.2704.103 and Safari 9.1.1

#### Screenshot / Video

![webpreview](https://cloud.githubusercontent.com/assets/1136160/16395386/ee84d012-3c8f-11e6-953d-38ab8ac7439e.gif)

#### Context / Source
#user-report 2716148-t

**Comment by lancewillett** [comment] 2016-09-02 18:04
I confirmed this in testing — with Baskerville theme with footer widgets, meaning the Infinite Scroll is a button you click to load more. When clicking the "Older Posts" button, nothing shows up after the spinner disappears.

Same JS error as reported originally:

`XMLHttpRequest cannot load https://lancetest23.com/?iframe=true&theme_preview=true&infinity=scrolling. Origin https://lancetest23.wordpress.com is not allowed by Access-Control-Allow-Origin.`

**Comment by seear** [comment] 2016-09-09 11:39
Apparently the Calypso web preview always uses the `unmapped_url` (*.wordpress.com), because using non-https domains in the iframe prevented the preview due to insecure content errors. It looks like infinite scroll requests will only work with the primary domain.

It seems that all mapped domains are [now guaranteed](https://en.blog.wordpress.com/2016/04/08/https-everywhere-encryption-for-all-wordpress-com-sites/) to be https, so we could fix this infinite scroll problem simply by changing the preview to use the primary url [here](https://github.com/Automattic/wp-calypso/blob/b2b7ed4db2a06fa7cffe02f85a84adb465f7226a/client/my-sites/design-preview/index.js#L207).

The risk of doing this is that if for some reason there are any sites left using non-https, they will not preview at all.

**Comment by seear** [comment] 2016-09-09 12:51
That said, I'm not convinced of the immediate priority of having infinite scroll work in the preview.

**Comment by lancewillett** [comment] 2016-10-03 17:20
Hi @seear — thanks for your comments, sorry for the slow reply.

>  we could fix this infinite scroll problem simply by changing the preview to use the primary url 

I think we should go ahead with this change and keep an eye out for reports of preview not working.

(Marking as normal priority.)

**Closed** 2016-10-06 14:56 UTC
Labels: Sites, [Type] Bug
