### ISSUE TITLE
Upgrading from Monthly to Yearly Creator plan shows "Contact support" button instead of "Upgrade to Yearly" button

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#90617] opened 2024-05-13 04:03 UTC
### Quick summary

If users who purchased Creator or Entrepreneur plan on monthly subscription before July 2023 try to switch to the annual subscription, they see "Contact support" button instead of "Upgrade to Yearly" button.

### Steps to reproduce

For Creator or Entrepreneur plan subscriptions purchased before July 2023, go to the Plans page.

1. Start on the https://wordpress.com/plans/ 
2. In the drop-down box, select the "Pay yearly" option

### What you expected to happen

The upgrade should change to "Upgrade to Yearly" option to help the user self-serve the purchase.

![Screenshot 2024-05-08 at 7 47 40 PM](https://github.com/Automattic/wp-calypso/assets/1519466/2ff3a194-b872-42ed-a987-c1b3fa537d99)

### What actually happened

Users see the "Contact support" button instead as in the following screenshot.

Users need a checkout URL from HEs to upgrade to the annual subscription, blocking them from self-serving.

On switching to the annual subscription, the site storage drops from 200 GB to 50 GB.

![Screenshot 2024-05-08 at 7 47 08 PM](https://github.com/Automattic/wp-calypso/assets/1519466/11087209-6fd0-4814-ad76-b1a6f12cfd6c)

### Impact

One

### Available workarounds?

Yes. Users can complete the check out if HEs add the annual subscription to the cart and share the direct checkout link.

### Logs or notes

Previous P2 report here: p9F6qB-e61-p2 with a workaround in the **Recommended action** section.
Slack convo: p1715159824482899-slack-C02BEP610

**Comment by happychait** [comment] 2024-05-13 04:07
User reports: 8172425-zen and 8161732-zen (both users didn't mind their site storage dropping from 200 GB to 50 GB).

**Comment by DavidRothstein** [comment] 2024-05-13 16:31
I think this may no longer be reproducible (p1715617849999999/1715159824.482899-slack-C02BEP610).

That said, the bigger issue mentioned above probably still remains?:

>On switching to the annual subscription, the site storage drops from 200 GB to 50 GB.

**Comment by liviopv** [comment] 2024-05-14 11:11
📌 ACTIONS
- Marking as Triaged since it's being handled in the Slack thread above and a similar issue is being discussed here p1715348367682719-slack-C02FMH4G8

**Comment by liviopv** [comment] 2024-05-31 16:51
Based on the outcome of the thread above and https://github.com/Automattic/wp-calypso/pull/90664 I'm going to mark this as Closed

**Closed as completed by liviopv** 2024-05-31 16:51 UTC
Labels: Bug, [Feature] Plans & Upgrades, [Pri] High, [Feature Group] WPCOM Store & Purchases, Triaged, Customer report [LEGACY], [Status] Priority Review Triggered, [Product] WordPress.com
