### ISSUE TITLE
Admin: Editor link not working

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#84158] opened 2023-11-14 10:27 UTC
### Quick summary

The Editor link in the sidebar of my Atomic site has no href - when I click it nothing happens.

### Steps to reproduce

1. Go to https://wordpress.com/themes/scruffianatomic.wpcomstaging.com (logged in as me!)
2. Click on Editor in the sidebar
3. Nothing happen

### What you expected to happen

I should be taken to the editor.

### What actually happened

Clicking the link did nothing.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

<img width="1682" alt="Screenshot 2023-11-14 at 10 23 18" src="https://github.com/Automattic/wp-calypso/assets/275961/3365f4ba-b629-404c-a30e-17034ae47394">

This seems to be a temporary issue that happened when I installed a custom theme. It seems to resolve itself after a few minutes.

**Comment by liviopv** [comment] 2023-11-18 16:05
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Switched the theme to "HEY" as shown in the screenshot, related /themes, and clicked on Appearance > Editor. The Site Editor loaded after a few seconds.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@scruffian I could not reproduce. If it's still happening on your site, I can take a look to see if I can find any pattern - just add me as an admin temporarily as we can't log into a12s sites.

**Closed as completed by liviopv** 2023-11-18 16:05 UTC
Labels: Bug, [Pri] High, [Closed] Not Reproducible, Needs triage, [Platform] Atomic, [Status] Priority Review Triggered
