### ISSUE TITLE
Dashboard color scheme Classic Bright is not working and applies the same colors as Default

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#86892] opened 2024-01-26 10:43 UTC
### Quick summary

When switching dashboard color schemes at https://wordpress.com/me/account, picking Classic Bright sets the colors to the same ones as Default option (which is black).

https://github.com/Automattic/wp-calypso/assets/39308239/acc1cdcd-94e9-4d37-b350-e970984f2efc

### Steps to reproduce

1. Navigate to https://wordpress.com/me/account
2. Select dashboard color scheme to be Classic Bright

### What you expected to happen

See the actual colors applied

### What actually happened

The colors are exactly as the Default option (black)

![EDWhoa.png](https://github.com/Automattic/wp-calypso/assets/39308239/3388bf28-48e6-4184-92e6-b342ac4bb550)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by filipanoscampos** [comment] 2024-01-30 16:56
📌 REPRODUCTION RESULTS

– Tested and reoplicated exactly as described

📌 VIDEO

https://github.com/Automattic/wp-calypso/assets/2540430/0078e1ae-cbf6-43f9-94d9-52c05e0e8a3f




📌 ACTIONS
Triaged.

**Comment by Aurorum** [comment] 2024-02-03 20:38
@mmtr It looks like this was removed by you in https://github.com/Automattic/wp-calypso/commit/1e2a4a48e9ede45bfb0109dec8299fc2dfdec022 - do you happen to remember if this was intentional?!

h/t to @sejas @katinthehatsite for some excellent digging here: https://github.com/Automattic/wp-calypso/pull/84149#issuecomment-1820930229

> I researched it a bit and this post specifying that the plan was to remove it: p9Jlb4-4qv-p2ee

That P2 is private though and I can't find the relevant convo on Slack so I'm not sure how to proceed here! Could either bring back Classic Bright (just spun a branch for this but I'll wait for confirmation before submitting the PR) or remove the option entirely. 

<img width="1649" alt="Screenshot 2024-02-03 at 20 37 41" src="https://github.com/Automattic/wp-calypso/assets/43215253/4e8bdf31-f5a3-4be7-9636-bbf83ad0ff5a">

**Comment by mmtr** [comment] 2024-02-05 09:28
@Aurorum wow, what a blast from the past! I definitely don't remember if that was intentional 😅 

Although after reading through p9Jlb4-4qv-p2, I can see that there was a plan to remove Classic Bright (and a few more schemes) in order to simplify the options available. This is a quote from that post:

> We can align more with core and simplify our color schemes by leaving only the ones that exist in core, plus the two extra themes that are quite popular with customers that change their scheme. This means removing: Classic Blue, Classic Bright, Contrast, Nightfall, Powder Snow & Sunset.

I don't know though what's the current plan for that. Maybe @poligilad-auto (the author of that post) or @lsl (who I believe worked in color schemes in the last year) know more.

What I can confirm is that my changes were unrelated to that, so at this point, since we're currently offering Classic Bright as an option, I think it'd be best to bring back the styles so it works as expected.

**Comment by poligilad-auto** [comment] 2024-02-05 11:48
> I don't know though what's the current plan for that. Maybe @poligilad-auto (the author of that post) or @lsl (who I believe worked in color schemes in the last year) know more.

My post didn't bring along any change to the themes, AFAIK. 

> What I can confirm is that my changes were unrelated to that, so at this point, since we're currently offering Classic Bright as an option, I think it'd be best to bring back the styles so it works as expected.

I agree this is the best option right now.

cc @saygunnyc

**Comment by Aurorum** [comment] 2024-02-05 11:54
Nice, thanks for taking a look! Those other schemes are still there, so I agree it's probably odd to single out Classic Bright from that list. I've proposed re-adding the variables in #87176.

**Comment by lsl** [comment] 2024-02-05 12:34
Looks like it didn't get merged before the priority shakeup https://github.com/Automattic/wp-calypso/pull/85061 cc @agrullon95 - Pretty sure this is unrelated.

**Closed as completed** 2024-02-05 13:27 UTC
Labels: Bug, [Pri] Low, [Feature] Calypso & wp-admin Navigation, Triaged, [Product] WordPress.com, [Feature Group] Other Infrastructure
