### ISSUE TITLE
Classic Themes: Duotone Filter missing on the live site for left, right and center-aligned images on Simple Sites

### ISSUE THREAD

**Issue by jorpdesigns** [Automattic/wp-calypso#75805] opened 2023-04-16 14:06 UTC
### Quick summary

When an Image Block has the [Duotone Filter](https://wordpress.com/support/wordpress-editor/blocks/image-block/#duotone-filter) applied, the colors appear on the backend but not on the frontend. 

This only affects classic themes on Simple sites. Looks like the bug was recently introduced, as noted in 12242641-hc

### Steps to reproduce

1. Ensure the test site is using a Classic theme (e.g. Orvis).
2. Create a page and add an Image Block.
3. **Important!** Set the image alignment option to center, left or right.
4. Click the Duotone Filter button in the block toolbar and set your preferred colors.
5. Publish the page and view on the frontend.

### What you expected to happen

The Duotone effect should appear on the frontend, similar to how it is shown in the Editor.

![gn2ERf.png](https://user-images.githubusercontent.com/40006288/232317053-c4eeeaaa-f0d1-4579-8591-cb7ce6ad9a78.png)

### What actually happened

The Duotone effect does not appear on the frontend.

![QIWYyA.png](https://user-images.githubusercontent.com/40006288/232317090-361e04f0-08e5-4809-a124-5cddca15af48.png)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- Reported in 12242641-hc. Follow-up ticket: 6199292-zen.
- Could reproduce with these themes: Orvis, Business, Twenty Nineteen, Twenty Seventeen, Photos, Radcliffe 2
- The filter worked fine after testing these Site Editing Themes: Blank Canvas, Hey, Archivo
- The duotone filter may be applied via CSS as a workaround but this would only work with the Premium plan.

**Comment by cuemarie** [comment] 2023-04-18 18:04
Hey @jorpdesigns ! Just ran a quick check on this, and was not able to replicate the issue with **Orvis**, **Twenty Nineteen**, or **Twenty Twenty**. Tested on a brand new free site, as well as an older Premium Plan site:

**Twenty Twenty**
![Markup on 2023-04-18 at 10:57:08](https://user-images.githubusercontent.com/27249804/232863836-8eebc2b7-c904-4f4b-a708-89ee7c4662e7.png)

**Orvis**
![9XnS9s.png](https://user-images.githubusercontent.com/27249804/232863671-8676c00e-b631-4daf-8a43-eac445a8f59b.png)

**Orvis on Premium Plan Site**
![KMyrnf.png](https://user-images.githubusercontent.com/27249804/232864751-7b2d8aab-11c4-4978-824c-601c4fe8d64e.png)

---

Are there any other specific steps I can take to try to reproduce this?

**Comment by jorpdesigns** [comment] 2023-04-19 08:57
Hi @cuemarie ! Took a while to reproduce but I finally managed to crack it. 

Looks like the bug only affects images with alignment set to left, right and center (for some reason). Images with alignments set to None, Wide and Full aren’t affected.

I will update the report title and steps to reproduce.

**Comment by cuemarie** [comment] 2023-04-19 19:37
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on **Twenty Nineteen** & **Orvis**

#### Screenshots/Recordings

**Twenty Nineteen**
![Markup on 2023-04-19 at 12:29:34](https://user-images.githubusercontent.com/27249804/233180757-32a96b3c-cdee-4ce5-b7a0-74f24ffe86e8.png)

**Orvis**

The working image shows the following CSS:

![Markup on 2023-04-19 at 12:36:09](https://user-images.githubusercontent.com/27249804/233181578-75895002-1ddc-43ac-93c9-3b405aa0cf10.png)

But the aligned image does not contain the `filter` parameter at all:

![Markup on 2023-04-19 at 12:34:58](https://user-images.githubusercontent.com/27249804/233181212-6a559e2f-c00b-4345-b3a2-b94a34467b36.png)

📌 ACTIONS
- Assigned to Apex

**Comment by hngdny** [comment] 2023-05-02 11:04
Another report here 37361778-hc

Atomic site, using Seedlet theme.

Tested and can confirm same issue can be replicated (Duotone color not applied when alignment is "center")

**Comment by csabarakasz** [comment] 2023-05-07 10:54
[6252844](6252844-zd-woothemes) Setting the image to None did not solve the duotone issue here.

**Comment by cuemarie** [comment] 2023-08-31 18:14
This looks like a duplicate of https://github.com/Automattic/wp-calypso/issues/78442 , but I'll retest before closing as the steps to repro are slightly different.

**Comment by cuemarie** [comment] 2023-08-31 21:47
Retested this - on a self-hosted site with Twenty Sixteen active, image blocks do not show the Duotone filter on the live site, no matter their alignment setting. 

https://github.com/Automattic/wp-calypso/assets/27249804/38f71a7e-4bc9-4a5d-aaa4-d38d75910909

In that case, I'm closing this issue as a duplicate of #78442, where we'll track further issues.

📌 ACTIONS
- Closed as duplicate

**Closed as not planned by cuemarie** 2023-08-31 21:47 UTC
Labels: Bug, [Pri] Normal, Triaged, Images, Customer report [LEGACY], [Platform] Simple
