### ISSUE TITLE
New post notification email: Gravatar incorrect for AT sites

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/wp-calypso#85466] opened 2023-12-19 10:41 UTC
### Quick summary

When creating a new post on an Atomic site and publishing it, the new post notification email does not contain the correct Gravatar, but instead has a black/white auto-generated Gravatar.

User report: 7472264-zen

### Steps to reproduce

1. Start at your Atomic site
2. Ensure you are a subscriber who'll receive the email
3. Create and publish a new post
4. Check the New Post email

### What you expected to happen

The Gravatar should be the one in your https://wordpress.com/me/ settings, as it is with Simple and self-hosted Jetpack sites.

Simple site - screenshot from new post email. My Gravatar is correct:
<img width="577" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36608681/5167c553-14cb-4861-b57a-1e8b47a47d17">

Jurassic ninja site with JP connected - screenshot from new post email:

<img width="648" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36608681/f6dc3526-3aaf-4fb1-bd3f-8d5691656369">

### What actually happened

The Gravatar is a black/white auto-generated one. Screenshot of the new post email from my AT site:

<img width="619" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36608681/55230da3-59e7-4f04-b612-e7021e32b631">

In case it was theme-related I tried a block theme too:

<img width="577" alt="image" src="https://github.com/Automattic/wp-calypso/assets/36608681/724ad2d1-59fc-46fb-9530-c6559679329f">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

I made sure to test on Simple and self-hosted with Jetpack - could not replicate. This seems isolated to AT sites.

I tested both with other plugins and with only Jetpack/Akismet active - same thing.

WordPress version: 6.4.2
Jetpack version: 13.0-a.5
Theme(s) tested: Mayland (Varia child) and Spiel (free a8c block theme)

**Comment by maciejpilarski** [comment] 2023-12-25 19:54
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to reproduce the issue on my test Atomic site:
![Markup on 2023-12-25 at 20:52:30](https://github.com/Automattic/wp-calypso/assets/9025643/887ac52b-93bf-4c00-8b2b-fdfbddf2f6a7)


📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)

**Closed as completed by maciejpilarski** 2023-12-25 19:54 UTC
Labels: Bug, [Pri] High, Triaged, Customer report [LEGACY], [Platform] Atomic, [Status] Priority Review Triggered, [Feature] Site Content Emails, [Product] WordPress.com, [Feature Group] Content Management
