### ISSUE TITLE
Gutenberg: Tags not saving consistently on WordPress.com environment

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#28974] opened 2018-11-30 05:23 UTC
Adding tags to a Gutenberg post on WordPress.com isn't consistent compared to Gutenberg Master

#### Steps to reproduce
1. Starting at URL: Gutenberg Editor
2. Open tag sidebar and add say 8 new tags in quick succession using enter key (eg. a,b,c,d,e,f,g or 1,2,3,4,5,6,7,8)

#### What I expected

All tags saved and against post when published

#### What happened instead

Using Gutenberg on WordPress.com the tags aren't saved consistently
In Gutenberg master the tags are saved consistently

### Gutenberg in Calypso

![calypso g](https://user-images.githubusercontent.com/128826/49270069-bc48a180-f4b3-11e8-8328-a78f592eb5b8.gif)

### Calypsoify Gutenberg (wp-admin on WP.com)

![calypsofy g](https://user-images.githubusercontent.com/128826/49270081-c7033680-f4b3-11e8-938d-f4c56cf35eaf.gif)

### Gutenberg Master

![g core](https://user-images.githubusercontent.com/128826/49270092-cff40800-f4b3-11e8-86f0-53e76da17c55.gif)

#### Browser / OS version

Chrome 70 on macOS Mojave

#### Screenshot / Video

See above

#### Context / Source

Debugging automated e2e tests

**Comment by Copons** [comment] 2018-11-30 14:52
I can reproduce on Core Gutenberg (v4.6.0):

![nov-30-2018 14-41-28](https://user-images.githubusercontent.com/2070010/49295631-28c0a200-f4ae-11e8-8279-5cf3a78abb96.gif)

It seems to be a race condition kind of conflict caused by the fact that, every time you input a tag it first fires a `GET /tags?search=foobar` to see if it's an existing tag, and then when hitting enter `POST /tags { name: "foobar" }` to save the tag.

What seems to happen is that most of the `POST` requests end up as:

```json
{
  "code": "term_exists",
  "message": "A term with the name provided already exists in this taxonomy.",
  "data": {
    "status": 409,
    "term_id": 123
  }
}
```

What I can't seem to figure out, is why some tags get inserted anyway (e.g. in my tests I've always tried with `1 2 3 4 5` etc, so `1` definitely already existed when I recorded the gif, and yet it got added correctly anyway.

**Comment by Stojdza** [comment] 2018-12-02 16:10
In e2e tests we are using `Tag <timestamp>`, so it's unique for every test run. What is strange, sometimes tests were passing on CircleCI, and sometimes they weren't.

> It seems to be a race condition kind of conflict caused by the fact that, every time you input a tag it first fires a GET /tags?search=foobar to see if it's an existing tag, and then when hitting enter POST /tags { name: "foobar" } to save the tag. 

@Copons when I run test locally, I see:
![dec-02-2018 17-03-18](https://user-images.githubusercontent.com/7116222/49341959-ade5bb80-f654-11e8-9031-60cd1219a2f8.gif)

After pressing 'Enter' tag disappear for a moment. Can this be related to this race condition?

**Comment by vindl** [comment] 2018-12-10 10:38
> I can reproduce on Core Gutenberg (v4.6.0):

If that's the case, @alisterscott or @Copons could you please report this as a Gutenberg core issue and close it here, since we can't fix it in integration only?

**Comment by alisterscott** [comment] 2018-12-12 08:00
I wasn't able to reproduce in core as per the above GIF which shows it working

**Comment by damiannep** [comment] 2019-01-31 10:14
Another report in #9835814-hc

**Comment by tbradsha** [comment] 2019-03-12 14:15
Removing the tag and saving is not working either; reported in 9410749-hc and was able to reproduce on a test site as well:

![Image](https://cld.wthms.co/RjsoXv+)

**Comment by kwight** [comment] 2019-03-12 23:45
@alisterscott @vindl I can easily reproduce this today in core; it may also be related to #28775 (which I could _not_ reproduce in core).

**Comment by katiebethbrown** [comment] 2019-12-18 16:31
Another report in #17130673-hc. User adds tags, then saves the post. When they view it or re-open the tags are gone.

**Comment by kwight** [comment] 2019-12-18 17:20
If possible, try and get the details of _what_ the user tried to add as a tag; I'm wondering if it's specific characters or something that's causing sporadic failures.

**Comment by sophiegyo** [comment] 2020-01-10 12:34
Another report in 2617187-zen.
I've asked the user for more details regarding the disappearing tags, including whether they're using Calypso or wp-admin, and what language they're typing in (EN or JP).

**Comment by mriyazuddin** [comment] 2020-01-14 05:34
User in 2617187-zen has replied back saying they access their site through Calypso and not through wp-admin directly. User has also mentioned the add the tags, save and close the post. When they reopen it later the tags disappear but not always. And they're creating tags in English and not in Japanese.

**Comment by katiebethbrown** [comment] 2020-01-21 02:00
User report in 17130673-hc.

User says tags are there when they publish but aren't getting saved. I've emailed for follow-up about how they are entering them when the issue occurs.

**Comment by aleone89** [comment] 2020-02-26 10:30
Hello there, Another report via 2742539-zen.

**Comment by jenlynnemc** [comment] 2020-03-13 09:43
Another case here: 2778581-zen 
User verified that they use the Calypso View not the WP-Admin Dashboard view.

**Comment by tijosh** [comment] 2020-03-19 17:15
#2801817-zen

They're trying to remove the "Featured" tag, and it seemingly disappears from the tag editor. However, it lingers in the list of posts with that tag. 

![Screenshot](https://d.pr/i/tA2kBb+)

**Comment by lancewillett** [comment] 2020-04-02 01:29
I did some stress-testing on these flows today:

- WP Admin, block editor
- Calypso, block editor

I couldn't repeat the error with the tags not saving as expected when added on a P2 themed site from the block editor sidebar.

I think it's safe to close this ticket, since that's the reported case.

There is a still a separate case to solve. When adding P2 tags inline in the block editor such as in a paragraph block with `#tag` syntax — in the body of the post, not via the sidebar — the tags sometimes don't create a new tag and also don't attach the tag to the post.

**Closed by lancewillett** 2020-04-02 01:29 UTC
Labels: [Goal] Gutenberg, [Pri] Normal, [Type] Bug
