### ISSUE TITLE
Email: Comparison link should open in new tab

### ISSUE THREAD

**Issue by matt-west** [Automattic/wp-calypso#95812] opened 2024-10-29 14:25 UTC
### Quick summary

The link to the page comparing email options should open in a new tab and have an external link icon.

![Image](https://github.com/user-attachments/assets/5f88512e-1a28-465e-a4ac-dc3d970ad096)

### Steps to reproduce

1. Go to WP Admin for a site.
2. Go to Hosting ➡️ Domains
3. Add new domain
4. Select a domain

### What you expected to happen

The link should open a new tab and display the external link icon.

### What actually happened

Page opens in the current tab.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment] 2024-10-29 17:09
📌 REPRODUCTION RESULTS
- Tested while adding a new domain

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate the behavior, however, I want to mention that it's not breaking any flows in picking up an email. For example, once I get to the "comparing" page, I get this:

![WkQoj1.png](https://github.com/user-attachments/assets/dc27d6bf-d82f-4dcb-815d-5b9e0cfb62d6)



📌 ACTIONS
- Triaged
- Requested author feedback

📌 Message to Author
@matt-west I'm able to select one of the email services and proceed with my selection. Is this flow currently broken on your end, or should it be different in design?

**Comment by p-jackson** [comment] 2024-10-29 21:52
I've got a fix here: https://github.com/Automattic/wp-calypso/pull/95841

> We don't usually open Calypso links in a new tab, but an exception is warranted here. When the user is purchasing a domain they're in the middle of a purchase flow, and we would prefer to keep them in that flow.
>
> The same comparison link exists at /email/{{ site slug }} when the site already has a custom domain. In this case the user isn't in the middle of a flow, and so the exception doesn't hold in this situation. So it hasn't been updated to an external link here.

@matt-west do you agree with my reasoning for why an exception is warranted in the "domain purchase" case but not the "existing domain" case?

**Comment by p-jackson** [comment] 2024-10-31 01:53
From https://github.com/Automattic/wp-calypso/pull/95841#pullrequestreview-2404179158

> The fact that clicking `Select` on the comparison page takes you back to the purchase flow makes for an odd experience, IMO.

@fredrikekelund brings up a good point. Once you're done comparing and you click `Select` you're taken back to the domain purchasing flow.

https://github.com/user-attachments/assets/c783f70b-5d59-4d20-ac65-4f6015002cf6

It's sort of strange that clicking "Select" doesn't actually select the option, but instead navigates back to the previous page. But it does keep the user in the purchase flow. And I can see why they have to navigate back to the previous page because they need to fill in the Google Email related fields.

@matt-west will be AFK for a couple days, but I think this calls into question whether opening in a new tab really improves the experience. Because now the user has the same flow open in two tabs.

**Comment by wojtekn** [comment] 2024-10-31 09:26
Maybe we should skip this in favor of https://github.com/Automattic/wp-calypso/issues/95864?

**Comment by matt-west** [comment] 2024-10-31 10:07
> do you agree with my reasoning for why an exception is warranted in the "domain purchase" case but not the "existing domain" case?

This make sense to me @p-jackson.

@fredrikekelund makes a good point about this resulting in users having the same flow open in two tabs though. That could be more confusing.

Ideally we fix this by combining the two pages in #95864. I agree with @wojtekn that we should skip this issue in favour of fixing it properly.

**Comment by fredrikekelund** [comment] 2024-10-31 10:15
+1 for closing this in favor of https://github.com/Automattic/wp-calypso/issues/95864

**Comment by p-jackson** [comment] 2024-10-31 23:53
Closing in favour of https://github.com/Automattic/wp-calypso/issues/95864

**Closed as completed by p-jackson** 2024-10-31 23:53 UTC
Labels: Bug, [Pri] High, [Feature Group] Emails & Domains, Triaged, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature] Email Integration, Groundskeeping
