### ISSUE TITLE
Signup: Consider background imagery or other visuals.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#22414] opened 2018-02-13 22:56 UTC
Our signup design, particularly on large screens, looks quite sparse and even unfinished-looking when compared to many competitors.

![screen shot 2018-02-06 at 2 28 29 pm](https://user-images.githubusercontent.com/349751/36178522-f2372e9e-10cd-11e8-84eb-7fb28339a7c7.png)

**Comment by alisterscott** [comment] 2018-06-01 04:31
Raised here: https://www.useronboard.com/how-wordpress-onboards-new-users/?slide=8

<img width="880" alt="screen shot 2018-06-01 at 2 31 21 pm" src="https://user-images.githubusercontent.com/128826/40821149-7cadc306-65a8-11e8-8dd0-a21826e92f40.png">

**Comment by jancavan** [comment] 2018-08-10 19:47
Closing as this is a duplicate of: https://github.com/Automattic/wp-calypso/issues/25213.

**Closed by jancavan** 2018-08-10 19:47 UTC
Labels: Design, NUX, Signup, [Status] Needs Design Review, [Type] Enhancement
