### ISSUE TITLE
Re-Publicize: Toggle button works only when username is clicked

### ISSUE THREAD

**Issue by kriskorn** [Automattic/wp-calypso#16846] opened 2017-08-02 17:59 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Click on blog posts on the left sidebar
3. Click on Share on a blog post
4. Click the Toggle button

#### What I expected

I expected for the Toggle button to enable or disable the sharing to a connected account.

#### What happened instead

The button could be clicked, but it does not modify the state of the Toggle button

#### Browser / OS version

Google Chrome Version 60.0.3112.78 / Windows 10 Pro

#### Screenshot / Video
![re-publicize-error](https://user-images.githubusercontent.com/12064241/28887208-fc50651e-77c4-11e7-85df-93ebb40bc5ec.gif)

However, when the username of the social media account is clicked instead, then the toggling works correctly.

#### Context / Source
#user-report (192361-hc)

**Comment by codestor4** [comment] 2017-08-10 11:51
628498-zen

Also tested this on my end and can confirm the toggle button is broken on users site [jp], my staging site [jp] and on a wp.com site.

**Comment by aheckler** [comment] 2017-08-29 17:59
656942-zen

**Comment by gziolo** [comment] 2017-09-14 15:52
Something goes wrong with event handling, `toggle` method is executed twice. It might be caused by the `click-outside` library. It needs further debugging.

**Comment by jeherve** [comment] 2017-09-14 20:01
I can't seem to reproduce the problem anymore. The toggles appear to work just fine on my end, on my test sites as well as on the user's site.

![screen recording 2017-09-14 at 12 49 pm](https://user-images.githubusercontent.com/426388/30452726-7d77739c-994b-11e7-8fed-eb796d9006f9.gif)

Closing this.

**Closed by jeherve** 2017-09-14 20:01 UTC
Labels: Sharing, [Status] In Progress, [Type] Enhancement, [Type] Good First Change

**Comment by gziolo** [comment] 2017-09-14 21:30
Fixed with #18044 :)
