### ISSUE TITLE
Media & Text Block formatting issue when stack on mobile is enabled.

### ISSUE THREAD

**Issue by catkiinson** [Automattic/wp-calypso#36876] opened 2019-10-18 00:41 UTC
#### Steps to reproduce
Cannot reproduce on my own test site. 

#### What I expected
The media and text block to display the text and image side by side, as it appears in the editor. 

#### What happened instead
Text overlaps the image. This stops happening once "stack on mobile" is disabled. 

#### Screenshot / Video
Editor View: 
![Screen Shot 2019-10-17 at 5 29 34 PM](https://user-images.githubusercontent.com/43645273/67057034-bb3c5500-f103-11e9-80d5-95d3a3c31096.png)

Live Site View: 
![Screen Shot 2019-10-17 at 5 28 27 PM](https://user-images.githubusercontent.com/43645273/67057003-9811a580-f103-11e9-81bf-03e9276ea8dd.png)

Live Site View once "stack on mobile" has been disabled: 
![Screen Shot 2019-10-17 at 5 30 58 PM](https://user-images.githubusercontent.com/43645273/67057089-f5a5f200-f103-11e9-81d6-e978f6f539e4.png)

#### Context / Source

This issue was brought up in two different chats #15825678-hc and #14741103-hc.
The screenshots are from the site in question in #15825678-hc. 

#15825678-hc Simple site, Professional Business theme. 
#14741103-hc Simple site, Modern Business theme.

**Comment by msilbers** [comment] 2019-10-18 00:46
A user has this issue in #16040763-hc using the Professional Business theme. They are unhappy with the work around to disable Stack on Mobile, as they want it to do that on mobile. The site is Atomic and it's happening in a Page.

<img width="966" alt="Screen Shot 2019-10-17 at 5 45 45 PM" src="https://user-images.githubusercontent.com/31680407/67057592-fd669600-f105-11e9-84be-a2b135dc08a9.png">

**Comment by kcswong** [comment] 2019-10-18 00:57
16040054-hc

Same issue, but in the example from this chat it looks like text on the site is appearing behind the images on the right, not in front of them. Theme is Sophisticated Business, but I also tested the other * Business themes with same results. They were given CSS to fix in an earlier chat:

```
@media screen and (min-width:900px){
	.has-media-on-the-right .wp-block-media-text__content {
		grid-column-start: 1 !important;
		grid-column-end: auto !important;
	}
}
@media screen and (min-width:900px){
	.has-media-on-the-right .wp-block-media-text__media {
		grid-column-start: auto !important;
		grid-column-end: auto !important;
	}
}
```

However, it didn't help on mobile view.

**Comment by jordesign** [comment] 2019-10-18 01:50
Another report in 16041825-hc (this time in Professional Business).

CSS fix has been supplied and confirmed it does not fix things on mobile - it remains quite broken.

<img width="343" alt="Screen Shot 2019-10-18 at 12 48 09 pm" src="https://user-images.githubusercontent.com/1842363/67059633-97315000-f1a5-11e9-8ca0-180ec0ce1e54.png">

**Comment by jordesign** [comment] 2019-10-18 02:18
In my testing, it appears that this only effects the TwentyNineteen 'Child' themes (Elegant Business, Modern Business, Sophisticated Business etc).

**Comment by catkiinson** [comment] 2019-10-18 02:30
@jordesign #16040600-hc shows the same bug occurring on the Storefront theme, and turning off "stack on mobile" resolved it.

**Comment by reginabally** [comment] 2019-10-18 03:42
Another report in #12322052-hc using Professional Business theme.

I've shared the CSS code the user in #2430007-zen and let them know they can also turn off the "Stack on mobile" option.

**Comment by mmtr** [comment] 2019-10-18 09:30
This issue has been caused by https://github.com/WordPress/gutenberg/pull/10812 (released in Gutenberg 6.7.0) which removed the grid template areas of the Media & Text block used by the now retired Business themes ([#](https://github.com/Automattic/themes/search?q=media-text-media+media-text-content&unscoped_q=media-text-media+media-text-content)).

I think this should be either fixed by bringing back the grid areas to Gutenberg (cc @jorgefilipecosta) or making an update to the themes (cc @iamtakashi).

**Comment by iamtakashi** [comment] 2019-10-18 10:57
The themes have been retired, but the removal of the grid template areas is breaking badly the business themes, I'm working on an emergency fix in the themes.

**Comment by iamtakashi** [comment] 2019-10-18 12:23
The fix for the following business themes has been deployed. 
* Calm Business
* Elegant Business
* Friendly Business
* Modern Business
* Professional Business
* Sophisticated Business. 

https://github.com/Automattic/themes/issues/1521

**Comment by jorgefilipecosta** [comment] 2019-10-18 14:20
Hi all, thank you for reporting, debugging and fixing the issues in the themes affected. Unfortunately, core can not rely on grid template areas because they are not compatible with IE11. It seems the best path forward is the one that was applied fixing the themes.
But I wonder why there was a need to apply grid area styles on the theme? Was there any limitation on the styles for the block core provides? cc: @iamtakashi

**Comment by mmtr** [comment] 2019-10-18 14:54
Thanks @iamtakashi!

**Closed by mmtr** 2019-10-18 14:54 UTC
Labels: [Goal] Gutenberg, [Type] Bug
