### ISSUE TITLE
FSE - Using the classic editor causes WSOD

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/wp-calypso#35804] opened 2019-08-27 02:51 UTC
The patch D31361-code appears to cause an issue for users that have chosen to stick with classic editor

#### Steps to reproduce
Placeholder steps - TODO: flesh out replication steps
1. On a non-fse site with pages with block content login in with a user and chose option to stick with classic editor
2. Switch site to FSE
3. Try to edit an exiting page
4. Editor tries to make calls to /wp/v2/types?context=edit&_locale=user and wp-json/wp/v2/ endpoints and crashes with unexpected 404s and unexpected json errors

**Comment by glendaviesnz** [comment] 2019-08-30 05:10
I was able to easily replicate the issue @noahtallen encountered with classic block content being broken on a local install - I have split this of into a [separate issue](#35894) as this is unrelated to which editor the user might have set, at point of FSE activation, it happens if classic content exists and the point of enabling FSE. This is probably critical as well @apeatling so have added blocker flag to it, but feel free to revise.

**Comment by apeatling** [comment] 2019-08-30 15:50
Yes, this one needs to be fixed since it's a fatal, better to clean it up now.

**Comment by apeatling** [comment] 2019-08-30 20:44
Changed my mind on this one, I don't think we should spend our time until after the test, because we're limiting to new users.

**Comment by noahtallen** [comment] 2019-09-30 22:04
Also reported in #36375

Copied from @vindl:

----------------
When attempting to load a page on a site that has FSE enabled with a classic editor the WSOD appears.

This is a major issue for support, since HEs opening a customer site for the first time won’t be be automatically using the Block Editor.

I think we should force Gutenberg for all users on FSE enabled sites, regardless of usual per user per site opt-in preferences that we use to determine whether Gutenberg should be loaded.

More info and discussion in this post: paYE8P-8W-p2

----

I'm going to look into this next, as this could be problematic for HEs and we've covered the other blockers :)

**Comment by noahtallen** [comment] 2019-09-30 22:27
This is reproducible with the following steps. To do so:

1. Use a user who defaults to the classic editor (account created before Dec 3, 2018)
2. Do not create a site (new FSE sites default to Gutenberg)
3. Instead, from a new test user with an FSE site, invite the account from step 1 to become an administrator on that site.
4. That invited user will have no setting for the FSE site, so it will default to their account preference, which is Classic.
5. Attempt to edit a page on the site you were invited to from Calypso. You will see the classic editor here, no WSOD. It will try to get you into the block editor, but you can use the classic editor. (In fact, this seems to work as well as typical classic editor / block editor differences work. Nothing weird per FSE.)
6. Attempt to edit a page from wp-admin. You will see a WSOD.

**Comment by noahtallen** [comment] 2019-10-01 00:50
Fix for this here: D33358-code.

**Comment by noahtallen** [comment] 2019-10-04 20:44
I verified the fix in production. Looking good!

**Closed by noahtallen** 2019-10-04 20:44 UTC
Labels: [Goal] Full Site Editing, [Pri] High, [Type] Bug
