### ISSUE TITLE
Enroute theme: Block errors on Front Page template

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#84245] opened 2023-11-16 14:40 UTC
### Quick summary

There are block errors in the Front Page template for Enroute

### Steps to reproduce

1. On an atomic site
2. Switch theme to Enroute
3. Go to edit the home page
4. Notice that there are a lot of block errors:
<img width="1300" alt="Screenshot 2023-11-16 at 14 39 28" src="https://github.com/Automattic/wp-calypso/assets/275961/01a33e54-3b60-4ad5-9200-e38346a5ca6e">
<img width="1454" alt="Screenshot 2023-11-16 at 14 36 04" src="https://github.com/Automattic/wp-calypso/assets/275961/6478e37f-ab99-48b7-8b53-5c85e85aace1">

### What you expected to happen

The theme should not contain block errors.

### What actually happened

The theme did contain block errors.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by maciejpilarski** [comment] 2023-11-27 15:11
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I was unable to reproduce the issue on my side. All blocks are loading fine:
![Markup 2023-11-27 at 16 07 52](https://github.com/Automattic/wp-calypso/assets/9025643/85b92f78-d242-4bca-b02d-00a51c5c1c18)
![Markup 2023-11-27 at 16 08 05](https://github.com/Automattic/wp-calypso/assets/9025643/c525a8f4-6aba-4b29-871a-958447657a08)

📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)

**Closed as completed by maciejpilarski** 2023-11-27 15:11 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Atomic
