### ISSUE TITLE
Auth error: A fresh access token must be used to query information about the current user

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#83660] opened 2023-10-30 18:07 UTC
### Quick summary

<img width="1001" alt="image" src="https://github.com/Automattic/wp-calypso/assets/18581859/f814e52d-d423-477d-a719-20ccb5037d97">

When working through the new [Newsletter](https://wordpress.com/newsletter/) signup flow, I ran into an error `A fresh access token must be used to query information about the current user` (worth noting that it appeared after accepting all cookies)

### Steps to reproduce

- I don't think this is a Newsletter-specific issue, so I don't have proper reproduction steps
- Start on a browser where you may have previously logged in?
- Work through the Newsletter signup flow
- When prompted to accept cookies (banner at the bottom), click "accept all"

### What you expected to happen

If one's already logged in, site creation flow should go through without the error `A fresh access token must be used to query information about the current user`

### What actually happened

An error `A fresh access token must be used to query information about the current user` appears at the top right

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment] 2023-10-30 20:11
📌 REPRODUCTION RESULTS
- Tested on Simple – Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
> I don't think this is a Newsletter-specific issue, so I don't have proper reproduction steps

Agreed, this is likely unrelated to Newsletters at all, and is instead about when reauthorization is needed in a logged-in browser.  Looking into how to manually trigger that expired token here: p1698696613914059-slack-CQD1HH4MA

📌 ACTIONS
- @arunsathiya did this prevent you from moving through the rest of the Newsletter flow, or was it just a confusing error to encounter after trying to allow cookies?
- In Triage

**Comment by arunsathiya** [comment] 2023-10-30 21:03
>did this prevent you from moving through the rest of the Newsletter flow, or was it just a confusing error to encounter after trying to allow cookies?

Unfortunately, I got sidetracked by submitting this bug report and then I closed the tab. 

I tried the flow again, where I don't see that error anymore and the site creation goes through too. So, just a confusing error!

**Comment by cuemarie** [comment] 2023-10-30 22:54
> So, just a confusing error!

Got it, thank you! I'll close this in favor of an enhancement request instead:

- https://github.com/Automattic/wp-calypso/issues/83675

📌 ACTIONS
- Closed as by design

**Closed as not planned by cuemarie** 2023-10-30 22:54 UTC
Labels: Bug, [Pri] Normal, [Product] WordPress.com, [Feature Group] Other Infrastructure, [Feature] Authentication
