### ISSUE TITLE
Blockbase & children: Google fonts not appearing in Global Styles for some sites

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#63229] opened 2022-05-02 22:54 UTC
### Quick summary

Google fonts appear for new atomic sites, but not for some existing ones.

### Steps to reproduce

The easiest way to reproduce this is to find an existing atomic site with the site editor enabled.

1. Visit the site editor
2. Open the Global Styles panel
3. Navigate to typography settings
4. Open the font family dropdown
5. Verify that no google fonts appear ( like `Roboto` or `Space Mono` )

### What you expected to happen

Google fonts should be selectable in the global styles font family dropdown

<img width="1275" alt="Screen Shot 2022-05-02 at 10 52 43 AM" src="https://user-images.githubusercontent.com/5414230/166339296-b70d276b-17d4-446a-abb8-3854c6977ee3.png">
<img width="1276" alt="Screen Shot 2022-05-02 at 10 52 35 AM" src="https://user-images.githubusercontent.com/5414230/166339300-6ce55ba0-3426-4c65-b153-110a7ea046e6.png">

### What actually happened

No google fonts appear

### Simple/Atomic

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jeyip** [comment] 2022-05-06 18:10
We've discovered the root cause of the problem. More in this p2 link paYE8P-1B3-p2

**Comment by jeyip** [comment] 2022-05-11 18:52
Leaving a reminder here to update [jetpack global styles google fonts documentation](https://wordpress.com/support/using-styles/) if we decide to use post title and heading block typography settings in the site editor as the new way to change heading fonts globally.
cc @creativecoder

**Comment by mriyazuddin** [comment] 2022-08-01 06:20
- [ ] Reported here as well: #5416028-zd

**Comment by sudeepbaral** [comment] 2022-08-03 12:25
- [ ] 5444228-zen

Reported here as well. The user has installed Custom Fonts plugin and installed the font as a workaround for now.

**Comment by JoshuaGoode** [comment] 2022-08-10 19:32
Adding tags and to the triage board.

@druesome, I believe you have some findings that might be worth sharing. Can you take a look at this one and see if we can get it to the right dev team(s)?

I think that makes https://github.com/Automattic/wp-calypso/issues/66286 a duplicate.

Related thread: p9F6qB-9Yy-p2

Unsure if this is in @Automattic/serenity's area or not.  Unsure if @Automattic/cylon got to this and if it's more of an FSE thing.

**Comment by jamiepalatnik** [comment] 2022-08-11 13:20
📌 SCRUBBING
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested on AT site, can recreate. 

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Addison-Stavlo** [comment] 2022-08-11 13:39
> Unsure if https://github.com/orgs/Automattic/teams/cylon for to this and if it's more of an FSE thing.

Yes, Cylon added the google fonts module to .com.  There was an issue where users with Blockbase (and child) themes that had previously set fonts via the customizer were not able to see the Google Fonts list in global styles - switching to a new theme or deleting the global styles settings was the work around.

I thought this was resolved with the new version of Blockbase though, for those still experiencing the issue does this still seem to be only on Blockbase and child themes? cc @pbking @jeyip

**Comment by druesome** [comment] 2022-08-16 07:47
>I thought this was resolved with the new version of Blockbase though, for those still experiencing the issue does this still seem to be only on Blockbase and child themes?

@Addison-Stavlo  I looked a bit into this one in the past, and usually manually changing the value of the Global Style post (ie `wp_global_styles_meraki`) to `{"version": 2, "isGlobalStylesUserThemeJSON": true }` fixes it.  A summary of my findings can be found in #65115.  However, I found that the workaround no longer works for the Meraki theme either.

More recently, this issue came up with the Payton theme (a Blockbase Premium child theme) as well (see #66286), but the workaround does not also help as the Global Style immediately gets overwritten after refreshing the editor.

This seems to work okay in Blank Canvas.

**Comment by Addison-Stavlo** [comment] 2022-08-16 13:25
> but the workaround does not also help as the Global Style immediately gets overwritten after refreshing the editor.

I think the new Blockbase version added some logic to migrate fonts settings from customizer settings to the current global styles format, which could be what is overwriting things. But it also sounds like it isn't doing that correctly since the google fonts aren't showing up.

Adding the issue to the theme board as well for more visibility here (or maybe I will when Github stops being dumb, have had this issue before recently). cc @jeffikus @pbking

**Comment by pbking** [comment] 2022-08-16 13:55
This seems to be an[ issue with Payton](https://github.com/Automattic/wp-calypso/issues/66286) because it's still got `fontFamilies` defined in the theme.json file.  I thought I had removed all of those when I upgraded the premium version of Blockbase but I seem to have missed that one.  It looks like it was subsequently tweaked, but the settings remain so the fonts expressed in theme.json are all that are available.

Blockbase has the collection of Google Fonts within the theme and there's a conflict with Jetpack (this was to comply with the GDPR ruling on Google Fonts which Blockbase previously used natively prior to Jetpack's implementation).  So to have all of the fonts available the child them has to leave the `fontFamilies` value empty so that the specific configuration including all of the fonts in the parent Blockbase can be used.

The issue is the same with Videomaker, but the unfortunate situation of that theme being in the `/pub` repo while being a `/premium` theme has created difficulties in keeping those two themes (videomaker, videomaker-white) synced up.

Here's a change that should address both of those themes.

D85999-code

**Comment by Addison-Stavlo** [comment] 2022-08-16 14:53
Thanks @pbking! It sounds like there is also currently an issue with Merkari as well? 

> A summary of my findings can be found in https://github.com/Automattic/wp-calypso/issues/65115. However, I found that the workaround no longer works for the Meraki theme either.

**Comment by blackjackkent** [comment] 2022-08-16 15:56
Serenity has had a couple of issues drift into our queue already (https://github.com/Automattic/wp-calypso/issues/66008, https://github.com/Automattic/wp-calypso/issues/66286) that seem like they might be related to this?

**Comment by pbking** [comment] 2022-08-16 16:02
Yes, pretty sure the change above will fix both items you noted @blackjackkent .

I'm sure I updated Meraki as well but I must have lost those changes at some point.  You're correct, the same change is needed in Meraki.  [Here is a change](https://github.com/Automattic/themes/pull/6405) to address that one.

**Comment by pbking** [comment] 2022-08-17 19:56
I have deployed D85999-code and [#6405](https://github.com/Automattic/themes/pull/6405)

I believe this can be closed now.

**Comment by Robertght** [comment] 2022-08-24 12:43
No further reports for a while. Closing.

cc @pbking @jeyip

**Closed as completed by Robertght** 2022-08-24 12:43 UTC
Labels: Bug, [Pri] High, Triaged, [Feature] Full Site Editor
