### ISSUE TITLE
[Bug] Editor automatically switches quotation marks to chevrons when the primary site language is set to Spanish

### ISSUE THREAD

**Issue by AlexanderSky** [Automattic/wp-calypso#83713] opened 2023-10-31 14:07 UTC
### Quick summary

One set of quotation marks (the ending ones) is changed automatically to chevrons in preview when the site language is set to Spanish.

### Steps to reproduce

Set primary site language to ES from Settings > General
Write in a post/page using the classic or block editor text between double quotation marks " "
Ex: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel vehicula enim. Suspendisse eu varius diam, ut fringilla dolor."
Save and preview.

### What you expected to happen

The quotation marks should stay the same as in the editor

### What actually happened

The ending quotation marks changed to chevron »

![image](https://github.com/Automattic/wp-calypso/assets/7353295/ba7fe270-c143-4fc9-8c9c-ed2b4c7ccae4)

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

Checked on multiple themes in Chrome and Firefox using Windows 11 PC

**Comment by AlexanderSky** [comment] 2023-10-31 14:10
7227077-zen

**Comment by cuemarie** [comment] 2023-10-31 15:06
Duplicate of https://github.com/Automattic/wp-calypso/issues/83404

**Closed as not planned by cuemarie** 2023-10-31 15:06 UTC
Labels: Bug, [Pri] Normal, Needs triage, Customer report [LEGACY]
