### ISSUE TITLE
[Bug]: URL parsing is broken when site URL starts with "free"

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#59251] opened 2021-12-15 18:42 UTC
### Quick summary

Trying to access: `https://wordpress.com/themes/free3nelsonec.wordpress.com` I'm redirected to `https://wordpress.com/themes3nelsonec.wordpress.com` (not found)
![image](https://user-images.githubusercontent.com/3801502/146245488-cd0f9f97-2c3a-481c-9405-b4a276e80522.png)

### Steps to reproduce

1. Create a free site starting with the word "free"
2. Go to calypso -> Appearance -> Themes
3. Click on the address bar
4. Hit Enter/Return

### What you expected to happen

Themes page to open

### What actually happened

Not found page opened

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Other notes

I've tested with 2 different sites. Same problem.
I suspect it's related to the themes filter and the fact that it adds the "free" segment to the URL.
![image](https://user-images.githubusercontent.com/3801502/146246077-92c61432-5030-4c42-a178-7f4b53231cb5.png)

If that's the case, "premium" should have the same effect as "free"

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The user can access the theme page by navigating using the sidebar, instead of the direct URL

**Comment by liviopv** [comment] 2021-12-27 10:51
Also reported in 4633660-zen. Switching priority to "High" since it breaks the theme page for customers.

> The user can access the theme page by navigating using the sidebar, instead of the direct URL

This did not work for me @nelsonec87. Which sidebar are you referring to?

**Comment by JoshuaGoode** [comment] 2021-12-27 16:10
Related: https://github.com/Automattic/wp-calypso/pull/58973

This was shared as an internal report as well p9F6qB-7Tv-p2

@kwight

**Comment by msilbers** [comment] 2021-12-27 18:56
also reported internally on pd4QKa-kC-p2 but I was unable to reproduce it at the time (Nov 16)

**Comment by andres-blanco** [comment] 2021-12-28 20:37
> Related: #58973
> 
> This was shared as an internal report as well p9F6qB-7Tv-p2
> 
> @kwight

[The PR](https://github.com/Automattic/wp-calypso/pull/58973) that fixes this issue is updated and waiting for review.

**Comment by kwight** [comment] 2022-01-03 21:38
Fixed in #58973 .

**Closed as completed by kwight** 2022-01-03 21:38 UTC
Labels: Bug, [Pri] High, Needs triage
