### ISSUE TITLE
[Bug]: Reader does not show the correct number of unread posts

### ISSUE THREAD

**Issue by sarayourfriend** [Automattic/wp-calypso#60235] opened 2022-01-19 11:21 UTC
### Quick summary

I use Reader to keep up with P2. The "unread" count on Reader is helpful for me to know how much time I will need to dedicate to catching up. However, it is currently broken (or changed?) and no longer shows the correct number of unread posts. Right now I count 8 unread posts, 7 of which are cross-posts, but Reader doesn't display anything for the unread count next to the organization name.

### Steps to reproduce

I'm not sure how to explicitly reproduce this, but it should be as easy as going to `https://wordpress.com/read/:org-slug` when that org has unread posts for the account, unless something is wrong with the `a8c` org specifically.

### What you expected to happen

It should display the correct number of unread posts next to the organization name in the Reader side bar.

### What actually happened

It doesn't show the unread count or shows an incorrect number.

### Browser

Mozilla Firefox

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by worldomonation** [comment] 2023-06-16 07:17
📌 REPRODUCTION RESULTS
Tested on Simple – not applicable
Tested on Atomic – not applicable
Replicable outside of Dotcom – not applicable

📌 FINDINGS/SCREENSHOTS/VIDEO
I checked a few internal P2s I'm subscribed to and compared the numbers.

For obvious reasons I will not post screenshots here, but it seems the number of unreads do match up.

📌 ACTIONS
- @sarayourfriend Have you observed this issue recently?
- add Needs Author reply label.

**Comment by sarayourfriend** [comment] 2023-06-19 02:19
> @sarayourfriend Have you observed this issue recently?

My approach to following P2s has changed and I haven't used reader in ages, sorry. I couldn't tell you if the numbers I'm seeing now are accurate.

**Comment by worldomonation** [comment] 2023-06-20 09:13
> > @sarayourfriend Have you observed this issue recently?
> 
> My approach to following P2s has changed and I haven't used reader in ages, sorry. I couldn't tell you if the numbers I'm seeing now are accurate.

Thanks for letting me know! I was not able to reproduce this with A8C P2s, so I will be closing this for as not reproducible for now.

**Closed as completed by worldomonation** 2023-06-20 09:13 UTC
Labels: Bug, [Pri] Low, [Feature] Reader, [Closed] Not Reproducible
