### ISSUE TITLE
Editor: removing link before to insert image triggers browser back button

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#4348] opened 2016-03-28 13:02 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Pick the site where you want to publish your post.
3. Insert a title, some content.
4. Click on the Insert Media button
5. Click on the Pencil icon next to an image you've previously uploaded.
6. Notice a URL in the link field. Click to focus on that field.
7. Hit backspace, as clicking in the field apparently selected the whole URL.
8. Your browser goes back to previous page instead of deleting the field content.

**Comment by aduth** [comment] 2016-03-28 13:05
Not sure I'd go so far as to call this a bug, since it's default browser behavior.

The idea with allowing the user to select the field is that they may want to highlight it and copy it themselves. Since there is a copy button, we could outright disable the field, preventing it from being focused. I'm not sure I'd see this as an improvement though.

Better option may be to simply capture and prevent the default behavior of the backspace button while the input is focused.

**Comment by jeherve** [comment] 2016-03-28 13:08
I would definitely call it a bug, as one would expect to be able to remove the contents of the field once it's in focus and all highlighted in blue.

If the field contents can't be edited, I think the "Copy" button should be enough. I don't think there should be any UI element indicating that one can edit the contents of the field.

**Comment by designsimply** [comment] 2016-03-28 23:52
Since the URL field is not editable, should it be an `input` field at all? Can it be plain text with a copy button next to it instead? If that's not doable, what about just showing a copy button only?

![screen shot 2016-03-28 at mon mar 28 5 46 40 pm](https://cloud.githubusercontent.com/assets/1119271/14093702/1e104052-f50d-11e5-97ae-9d68fca792fa.png)

**Comment by aduth** [comment] 2016-03-29 17:48
Worth noting that the behavior here was intended to resemble that of wp-admin, where the same behavior is present in the media library (sans copy button), including navigate on backspace:

![wp-admin](https://cloud.githubusercontent.com/assets/1779930/14117400/82932a58-f5b2-11e5-810a-8493f8cd97b5.png)

Per specification, `readonly` is a valid attribute of `<input />` elements to designate inputs which are not to be edited:

https://www.w3.org/TR/html-markup/input.text.html#input.text.attrs.readonly

That said, I'm fine with making revisions here if there's a concern about usability. If we were to remove the input field, I'd like some design feedback on how we might (or might not) display the URL text (cc @hugobaeta ). Otherwise, per my previous comment, a more immediate fix may be to prevent the default behavior when backspace is pressed within the input field.

**Comment by hugobaeta** [comment] 2016-03-29 23:57
@aduth What exactly do you want feedback on?

**Comment by aduth** [comment] 2016-03-30 00:05
>What exactly do you want feedback on?

@hugobaeta , given the concerns raised here over usability of a read-only input field for displaying a URL, do you think it makes sense to eliminate the input and, if so, should we keep the URL text visible, or replace it with only a button to copy the URL, or do away with the field altogether (added in #1481)?

Context: In the [Calypso post editor](http://calypso.localhost:3000/post), when viewing the details for a media item, we show the URL in a similar fashion to that of the wp-admin media library, but also including a button to copy the URL directly to the clipboard.

![URL input](https://cloud.githubusercontent.com/assets/1779930/14127800/e2dbe1ee-f5e8-11e5-9b14-052a823f4497.png)

My opinion is at most to disable the default behavior of the backspace keypress while focussing the read-only input, or at a minimum, close this as wontfix (given that this is the effect of default browser behavior).

**Comment by rachelmcr** [comment] 2018-01-02 21:44
Closing as I can no longer reproduce the backspace navigation as described in the original report.

#bug-scrub #pre-gutenburg-bug-purge

**Closed by rachelmcr** 2018-01-02 21:44 UTC
Labels: Editor, Media, [Type] Enhancement
