### ISSUE TITLE
Gutenberg: Contact form styles are off in calypso env

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#29072] opened 2018-12-04 18:00 UTC
#### Steps to reproduce

1. head over to https://wpcalypso.wordpress.com/gutenberg/post 
2. Select a site to start composing a post
3. Add a /Form block
4. Note that on the first screen, the form-fields are not extending to full width
5. Click 'Add form' and note the distance between labels and form-fields

I'd expect these form fields to be full width:

![screen shot 2018-12-04 at 12 59 05 pm](https://user-images.githubusercontent.com/2694219/49462597-772eb300-f7c4-11e8-8cd3-0989dcd8aab9.png)

I'd expect the labels and form-fields to be closer, and all fields to be full width:

![screen shot 2018-12-04 at 12 59 18 pm](https://user-images.githubusercontent.com/2694219/49462633-8a418300-f7c4-11e8-93f1-15df78b71e21.png)

**Comment by torres126** [comment] 2018-12-04 18:03
I believe that this might be a duplicate of #29008. The form fields should be fixed by #28722 and the distance between labels and fields should be fixed by #29018.

**Closed** 2018-12-04 18:12 UTC
Labels: Contact Form, [Goal] Gutenberg
