### ISSUE TITLE
Store - additional product details should be visible on the frontend

### ISSUE THREAD

**Issue by jameskoster** [Automattic/wp-calypso#20775] opened 2017-12-13 13:49 UTC
Currently, adding additional details to a product doesn't actually display them on the frontend. 

I presume it's because we're leaving the "[Visible on the product page](https://cloudup.com/cJeXpTLQLMv)" checkbox unchecked by default.

<img width="210" alt="screen shot 2017-12-13 at 13 29 02" src="https://user-images.githubusercontent.com/1119271/33964799-ee6b7460-e016-11e7-82e4-63e6b5add5df.png">

I believe we should go ahead and display them regardless (rather than adding an option). As we use a different UI for variations, the only reason someone would add additional details in Calypso is _because they want to display them_.

**Comment by designsimply** [comment] 2017-12-13 22:04
Tested and confirmed using the following testing steps:

1. Go to My Site > Store > Products > Add.
1. Add a product name, SKU, and description.
1. Click "Add additional details" and add a Type and Values.
1. View the product on the front end.

<strong>Result:</strong> the additional details for the product do not show up by default.

![screen shot 2017-12-13 at wed dec 13 3 01 45 pm](https://user-images.githubusercontent.com/1119271/33964770-d083128c-e016-11e7-8fc9-7a5927413e88.png)
<sup>Seen at https://madefortesting347.blog/product/hopes-dreams/ using Firefox 57.0.1 on Mac OS X 10.13.1.</sup>

<strong>Question:</strong> I looked for the "Visible on the product page" checkbox but couldn't find it. How do I get to that?

**Comment by jameskoster** [comment] 2017-12-14 15:46
> Question: I looked for the "Visible on the product page" checkbox but couldn't find it. How do I get to that?

Edit a product -> click attributes tab -> open attribute -> find checkbox :)

**Comment by designsimply** [comment] 2017-12-15 22:04
> Edit a product (in wp-admin)

Aha! Big +1 from me for having the additional details show by default then.

**Comment by kellychoffman** [comment] 2018-01-03 21:35
@timmyc - is this a good trash pickup candidate or something bigger?

**Comment by timmyc** [comment] 2018-01-03 23:20
Yes seems like a good quick fix/win, added to the Maintenance project.

**Comment by justinshreve** [comment] 2018-01-22 23:35
This is fixed now. It was reported during product category testing, and since it was a two line fix I included it in #21740.

**Closed by justinshreve** 2018-01-22 23:35 UTC
Labels: Store, [Type] Enhancement
