### ISSUE TITLE
Learning Mode template intermittently broken for Atomic sites

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#85038] opened 2023-12-05 20:05 UTC
### Steps to Reproduce
1. Go through the Sensei onboarding flow on WordPress.com as a new user.
2. From Sensei Home, click _Customize your theme_. (You may need to verify your email address first if you haven't already.)
3. Switch your Learning Mode template to Modern or Video (may also happen with other templates, but I reproduced on these).
4. Click on Templates > Lesson (Learning Mode - Video).
5. See errors in preview window.

NOTE: This issue is intermittent for me and I've only been able to reproduce on a WordPress.com site. If you're not able to reproduce, try leaving the site editor and then coming back in. Or switch to a different Learning Mode template first.

### What I Expected
No block errors and the template to display.

### What Happened Instead
I think this error is relevant as it does not appear when the template loads correctly:

![Screenshot 2023-12-05 at 2 58 27 PM](https://github.com/Automattic/sensei/assets/1190420/190f5c79-0085-412d-b192-1d55c2acd9db)

### Context / Source
Related https://github.com/Automattic/sensei/pull/7317

**Comment by maciejpilarski** [comment] 2023-12-11 18:43
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I have followed the steps to reproduce the issue, to be able to switch between the Default and Modern Appearance, I had to purchase the Sensei Pro version.

I was not able to reproduce the issue, all blocks are loading fine for me when switching templates:
![Markup 2023-12-11 at 19 39 14](https://github.com/Automattic/wp-calypso/assets/9025643/e1da3d17-89e7-4424-ac87-780d040010d0)


📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)

**Comment by donnapep** [comment] 2023-12-11 19:43
There's a fix for this in #85051.

**Closed as completed** 2023-12-13 06:41 UTC
Labels: Bug, [Pri] High, Triaged, [Status] Priority Review Triggered, Sensei Onboarding Flow
