### ISSUE TITLE
Editor: Sticky Button is seemingly hidden

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#18217] opened 2017-09-24 12:13 UTC
#### Steps to reproduce
1. Starting at URL: wordpress.com/post/you.wordpress.com/123
2. Open devtools/elements
3. Search for editor-sticky
4. Note that the element is present, but seemingly missing from the UI

#### What I expected
Expected to see a bookmark icon that, when clicked, toggles the 'sticky' status of my post.

#### What happened instead
The icon is not visible (to the eye) but is clickable if you click in the right place.

#### Screenshot / Video

<img width="1086" alt="screen shot 2017-09-24 at 05 04 56" src="https://user-images.githubusercontent.com/4335450/30782386-3f5bd6dc-a0e6-11e7-832b-e0a2440e58c1.png">
<img width="1085" alt="screen shot 2017-09-24 at 05 05 16" src="https://user-images.githubusercontent.com/4335450/30782385-3f4bb324-a0e6-11e7-8eff-508b272058af.png">
<img width="1085" alt="screen shot 2017-09-24 at 05 05 34" src="https://user-images.githubusercontent.com/4335450/30782384-3f43e9a0-a0e6-11e7-80bc-0ca80ca664c5.png">

#### Context / Source
Refactoring the element, I was looking for it in the UI to write a test plan.

**Comment by rantoncuadrado** [comment] 2017-11-08 11:39
Someone asking about https://woothemes.zendesk.com/agent/tickets/779927

**Comment by spen** [comment] 2017-11-08 11:48
Thanks @rantoncuadrado :)

**Comment by rachelmcr** [comment] 2017-11-08 13:33
A number of reports are also in this duplicate issue: https://github.com/Automattic/wp-calypso/issues/19575

**Comment by ehti** [comment] 2017-11-08 13:35
Influx of reports since yesterday.

What what changed?

**Comment by eduardozulian** [comment] 2017-11-08 13:38
@rachelmcr can you confirm that we're talking about not only the orange label but also about the toggle under the Status tab? Support docs were recently updated with this:

**Comment by rachelmcr** [comment] 2017-11-08 13:44
Ah, I missed the distinction in the other issue about the sidebar toggle also being missing. That is likely new — @spen do you think the missing sidebar toggle could be a side effect of the changes you just made in https://github.com/Automattic/wp-calypso/pull/19294?

**Comment by ehti** [comment] 2017-11-08 13:47
Thanks for pointing that out @eduardozulian 

My user said the same thing that the sticky toggle is now suddenly gone from the sidebar.

**Comment by lancewillett** [comment] 2017-11-08 18:04
Thanks for bringing this up again @ehti -- we'll take a look ("we" = someone on Delta teams).

**Comment by lizkarkoski** [comment] 2017-11-08 19:23
I have two new reports of this in the forums: 

1. https://mc.a8c.com/happiness/tqr/?topic_id=883285&in_queue=1
2. https://mc.a8c.com/happiness/tqr/?topic_id=883282&in_queue=1

I believe that these users are still able to access this function through wp-admin, and the issue is only in Calypso. Commenting now to confirm.

**Comment by supernovia** [comment] 2017-11-08 19:29
Two more reports here: http://en.forums.wordpress.com/topic/sticky-post-option-not-available-under-post-settings

**Comment by MindyPostoff** [comment] 2017-11-08 20:41
The option is actually still there as an invisible flag in Calypso (not under the Status section):

![](http://cld.wthms.co/Hrbp5m+)

**Comment by michaeldcain** [comment] 2017-11-08 22:10
It looks like this is the intended behavior (since March) from 11ea3f6835f53f6e89c6750a566a12874305c2d2. Discussion [here](https://github.com/Automattic/wp-calypso/pull/11536#issuecomment-282664708).

The flag gets displayed only when the toggle from the Post Settings is on.

![sticky-flag](https://user-images.githubusercontent.com/942359/32577360-b1298950-c4a7-11e7-8268-461dba8fddba.gif)

**Comment by supernovia** [comment] 2017-11-08 23:20
@michaeldcain The toggle seems to be missing from the post settings.

**Comment by supernovia** [comment] 2017-11-08 23:21
We've got another report here: https://twitter.com/ohgrowup/status/928387784712134656

**Comment by supernovia** [comment] 2017-11-08 23:24
If it helps:

<img width="1005" alt="screen shot 2017-11-08 at 4 23 36 pm" src="https://user-images.githubusercontent.com/3476361/32580189-5015b75c-c4a1-11e7-99de-c38d88361720.png">

**Comment by spen** [comment] 2017-11-08 23:29
FYI, Looking in to this right now.
At first glance, the render logic is [still here](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/edit-post-status/index.jsx#L109).
My instinct is that either some of the utils that you see in the lines above are giving the wrong value (though I'm doubtful of this) or there's some data issue.

**Comment by alisterscott** [comment] 2017-11-08 23:32
I believe this is a regression from the last couple of days in wp-calypso as a branch I had from a couple of days ago still showed it. I can run a git bisect to find the PR that removed this if you like.

**Comment by spen** [comment] 2017-11-08 23:36
Here's what I see in my debugging when looking at the properties that are used in the conditional that renders the component.

The post type is missing - chances are this relates to one of my recent commits 😬
If so it should be a really quick fix.

```js
{
  type: undefined,
  isPostPrivate: false,
  isPasswordProtected: false
}
```

**Comment by alisterscott** [comment] 2017-11-08 23:40
@spen: introduced in this PR: https://github.com/Automattic/wp-calypso/pull/19414

**Comment by spen** [comment] 2017-11-08 23:42
Thanks Alister, I was just heading back to say the same!
I'll open a quick PR pronto!

**Comment by spen** [comment] 2017-11-09 00:39
A quick fix for the discussed issue open @ #19620

This doesn't close the original issue, though @michaeldcain has cleared that issue up (thanks!).
I would like to quickly discuss that before closing though.

**Comment by spen** [comment] 2017-11-09 01:56
Thanks for finding the original discussion @michaeldcain :)

I've some thoughts on this...
My first thought was that we should make the 'invisible', 'unstickied' icon unclickable.
The problem that leaves is that we're then allowing cases where folks may click the button, not really knowing what it does but then have no obvious way to re-sticky it. Perhaps this person wasn't the same person who stickied it in the first place.
My second thought was that we could then make it purely a visual aid by removing any ability to toggle with this button.

cc/ @shaunandrews have you any opinions on this?

**Comment by nylen** [comment] 2017-11-09 06:39
A few options:

1. Remove the flag icon entirely.  It's confusing and it duplicates functionality already available elsewhere.
2. Make the icon informational only, not clickable in either state.  Preserve the current tooltip and maybe add some text about how to change this setting.
3. Allow clicking the icon.  Show an outline of a flag icon when the current post is not sticky, and the current orange flag when it is sticky.  Make sure the informational tooltip shows with an appropriate message for each case, and make sure the element is keyboard-focusable and has appropriate styles like `cursor: pointer`.  Consider removing the sticky toggle from "Post settings".

**Comment by supernovia** [comment] 2017-11-09 19:45
> Allow clicking the icon. Show an outline of a flag icon when the current post is not sticky, and the current orange flag when it is sticky. Make sure the informational tooltip shows with an appropriate message for each case, and make sure the element is keyboard-focusable and has appropriate styles like `cursor: pointer`.

I like this :)

> Consider removing the sticky toggle from "Post settings".

I'd rather see it left in the Post Settings space as well, since people are used to accessing it there. Is it okay to have more than one way to sticky a post?

**Comment by ehti** [comment] 2017-11-10 12:21
>2. Make the icon informational only, not clickable in either state. Preserve the current tooltip and maybe add some text about how to change this setting.

I'm personally in favor of this as it doesn't make sense to duplicate the functionality, that's already under Post Settings. It just gets confusing.

Either make it informational or remove the flag/icon.

**Comment by shaunandrews** [comment] 2017-11-13 14:00
I'd remove the icon — it seems rather worthless in its current state.

If we do end up keeping it, then I'd suggest option #2 from @nylen's comment above.

**Comment by davipontesblog** [comment] 2020-06-10 03:04
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.

**Closed by davipontesblog** 2020-06-10 03:04 UTC
Labels: Editor, [Type] Bug
