### ISSUE TITLE
Product reviews are not showing in the Comments section

### ISSUE THREAD

**Issue by chrism245** [Automattic/wp-calypso#56043] opened 2021-09-06 20:07 UTC
Steps to reproduce:

1. A WordPress.com AT site.
2. Enable product reviews on WooCommerce Settings.
3. Add a product review, and it won't show in the comment section; it will show just the icon that is a pending comment.

![Annotation on 2021-09-06 at 14-05-06](https://user-images.githubusercontent.com/47186013/132257868-52e341c9-dbc5-4107-8a12-f859e1d21787.png)

The default ULR to see comments is https://wordpress.com/comments/all/XXXXXXX.

* Expected:
It should show all the comments, as it does when you change the URL to https://XXXXXXX/wp-admin/edit-comments.php.

<img width="1425" alt="Markup 2021-09-06 at 13 43 34" src="https://user-images.githubusercontent.com/47186013/132257915-33c70b9c-d617-4031-aa49-0763e3ce0ceb.png">

**Comment by katiebethbrown** [comment] 2021-09-09 17:24
Looks like this might be a duplicate of https://github.com/Automattic/wp-calypso/issues/55568

**Comment by Thelmachido** [comment] 2021-09-09 18:13
Another report here: 30183337 -hc 

Viewing the comments page in classic-view helped.

**Comment by inaikem** [comment] 2021-09-27 06:44
Pinged @chrism245 re Bugomattic and added the issue to the HE Triage board.

**Comment by synora** [comment] 2021-09-28 16:21
Closing as this is a duplicate of #55568

**Closed as completed by synora** 2021-09-28 16:21 UTC
Labels: Bug, Triaged
