### ISSUE TITLE
Storage Add-on Dropdown: Spotlight Plan dropdown list is unintentionally offset

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#87618] opened 2024-02-20 02:03 UTC
### Quick summary

<img width="1430" alt="Screenshot 2024-02-19 at 6 00 50 PM" src="https://github.com/Automattic/wp-calypso/assets/5414230/677ba29c-0177-48c6-bbbd-c9667abfa2d3">

### Steps to reproduce

- Navigate to `/plans`
- Open the storage add-on dropdown for the spotlight plan
- Verify that the list is off center

### What you expected to happen

A dropdown list aligned with the dropdown menu

### What actually happened

Offset dropdown list

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by maciejpilarski** [comment] 2024-02-20 17:24
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue on my test site:
![Markup on 2024-02-20 at 18:23:37](https://github.com/Automattic/wp-calypso/assets/9025643/756195c6-1a49-4e03-a9c6-d90b575d1758)

📌 ACTIONS
– Triaged

**Comment by katinthehatsite** [comment] 2024-09-02 12:47
I tested this on my end and could not reproduce the issue anymore as the dropdown on this page `https://wordpress.com/plans/yearly/ {yourSite}` looks aligned now:

<img width="1295" alt="Screenshot 2024-09-02 at 2 45 16 PM" src="https://github.com/user-attachments/assets/2214f5e8-e08b-4080-b7fd-c279891bff46">

Closing as the issue seems to be solved now.

**Closed as completed by katinthehatsite** 2024-09-02 12:47 UTC
Labels: Bug, [Pri] Normal, Triaged, Bottle Pickup, Groundskeeping
