### ISSUE TITLE
Notifications: loading icon (no notifications) in wpadminbar

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#46182] opened 2020-10-06 02:10 UTC
Reported in https://wordpress.com/forums/topic/notifications-not-working-4/

When the bell icon is clicked on either the site front end or wp-admin (wpadminbar) notifications do not load, and instead an endlessly spinning load icon is displayed.  This issue affects the Opera browser ~only.~  (Now also confirmed in FF and Chrome) Notifications load fine in Calypso, so the issue affects notifications on the site front end and wp-admin only

Checking in the browser console I see the following error: 

`WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403`

Screenshot of the issue and console output:
![Screenshot on 2020-10-05 at 16-00-51](https://user-images.githubusercontent.com/1967448/95150535-10fa7a80-0724-11eb-8db4-780639da3112.png)

#### Steps to reproduce

1. Launch Opera browser
2. Visit site front end or wp-admin
3. Click on notifications (bell) icon
4. No notifications, only endless loading.  :(

#### What I expected
to see notifications load as they do in Calypso directly

#### What happened instead
Loading icon and error messages as shown in screenshot above

#### Browser / OS version
- **Mac OS** 10.15.4 **Opera** 71.0.3770.198
- **Windows 10 home**, build 19041.508 **Opera** 71.0.3770.198

Note:  My version of Opera was out of date (Mac OS v68) and notifications did load there as expected initially, but did not load after updating to v71.0.x, so seems to only affect the most recent version(s) of Opera

**Comment by jerrysarcastic** [comment] 2020-10-07 01:17
Also reported in https://wordpress.com/forums/topic/blog-is-broken-2/

User has mentioned they see this issue in Chrome (Windows 10) as well as Opera.  I can't confirm there is an issue with Chrome when I check on my Mac, so may be specific to the Windows 10 version of Chrome as well

**Comment by KokkieH** [comment] 2020-10-07 04:55
Noting that the notifications drop-down worked for me in Opera 68 on MacOS 10.15.7. After updating to Opera 71, it's broken. So it would appear it's something in the most recent Opera update causing this.

I'm also able to replicate in Opera on Windows 10 using Browserstack, but not Chrome on Windows 10.

**Comment by jerrysarcastic** [comment] 2020-10-14 21:50
User confirms they have not blocked third party cookies in a screenshot here: 

![opera_cookies](https://user-images.githubusercontent.com/1967448/96049220-6b29c880-0e13-11eb-9c09-e3ba2d2620a3.jpg)

**Comment by KokkieH** [comment] 2020-10-16 06:19
Another report in https://wordpress.com/forums/topic/like-problem/

**Comment by KokkieH** [comment] 2020-11-13 04:56
Another report in https://wordpress.com/forums/topic/voting-and-alert-drop-down-not-working/

Using Opera 72.0.3815.320

**Comment by KokkieH** [comment] 2020-11-26 04:56
Another report in https://wordpress.com/forums/topic/bell-wont-open/

Using Chrome 87.0.4280.66 (Official Build) (32-bit) on Windows 7

**Comment by lsl** [comment] 2020-11-26 06:12
I've come across this before and just again on Firefox with an old user profile / test account that I hadn't visited WordPress.com with for a long time.

In my case, logging out and logging in again fixed the issue. I suspect this has something to do with auth cookies/token expiring. (The cause of the 403 response)

I don't know enough about the this system to be sure but given some of the information in that thread:

- It only happens with the black nav bar (wp-admin), 
- Not the blue nav bar (wp-calypso),

I'm suspecting something is being refreshed for WordPress.com but not for the site's domain. The expired cookies on the sites domain are then being used to make ?proxy requests? for notifications and failing.

**Comment by fstath** [comment] 2021-05-09 15:10
Another report in https://wordpress.com/forums/topic/cant-see-notifications-6/

Using Opera 76.0.4017.107 on Windows.

@lsl login/logout trick worked for them.

**Comment by sajmes** [comment] 2021-11-30 07:59
Another case here in Opera 81 with browser extensions disabled. Also in Comodo Dragon browser. 

4534186-zd-woothemes

**Comment by bluefuton** [comment] 2022-06-28 04:52
I've also experienced this on Firefox myself. Updated the description to reflect that the issue happens on multiple browsers.

**Comment by kerrynicl** [comment] 2022-06-28 19:41
@bluefuton  Are you able to replicate this recently? I'm not able to replicate on any browser currently 

📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
Not able to replicate issue on any browser or site 

📌 ACTIONS
- Await author feedback

**Comment by bluefuton** [comment] 2022-06-29 00:15
Thanks for looking @kerrynicl! I was just able to reproduce it on a private site with a mapped domain. Steps to reproduce:

1. Set up a site with a mapped domain, and make it private.
2. Make sure the mapped domain is the primary domain for the site.
3. Go to the homepage of the site, login and click the notifications bell.

This is on a standard user account (not superadmin).

<img width="429" alt="image" src="https://user-images.githubusercontent.com/17325/176325048-52830247-b950-4d50-a696-4035b9f51da7.png">

**Comment by lsl** [comment] 2022-06-29 02:55
That sounds more like a 3rd party cookie issue than cookie expiry like I was discussing above - its possible there is more than one issue here, both with the same outcome.

@bluefuton does a login/logout fix the issue? 

Its possible we need to do something similar to this https://github.com/Automattic/wp-calypso/pull/53125 for that flow where you log in and then setup a mapped domain.

**Comment by bluefuton** [comment] 2022-06-29 04:35
Thanks @lsl! A login/logout doesn't seem to resolve it for me, but switching the site's primary domain to the something.wordpress.com one does resolve the issue.

**Comment by lsl** [comment] 2022-07-13 04:17
Posted an update to the [Jetpack issue](https://github.com/Automattic/jetpack/issues/24832#issuecomment-1182735309) - that one looks limited to Firefox.

We could probably close this but it looks like there are still a few Opera reports unresolved here so leaving open.

Could we differentiate any future reports for Firefox and post those over in https://github.com/Automattic/jetpack/issues/24832.

**Comment by cuemarie** [comment] 2022-08-24 00:49
📌 ACTIONS
-
- Based on the conversation above, moving this over to `Prioritize & Assign` to keep open, but it looks like this doesn't need further triaging.

**Comment by lsl** [comment] 2022-08-24 08:22
I believe the approach taken in https://github.com/Automattic/jetpack/pull/25448 to not show the notification bell when third party cookie access is limited will provide cover for all other non-firefox situations leading to this behavior in the same way. On the flip side, it might also mask separate issues with cookies we want to fix.

Please reopen or create a new issue if anyone still runs into the loading spinner or if someone reports a missing notification bell when you think they have third party cookies enabled and should see their notifications bell.

This isn't the ideal solution but I don't think this ticket is the appropriate place to work on a bigger fix. Moving notifications to a 1st party context is the ultimate goal. Latest update on that approach is over on p2: pcNnmV-89-p2#comment-363

**Closed by lsl** 2022-08-24 08:22 UTC
Labels: [Type] Bug, [Status] Needs Author Reply, Notifications, User Report, 3rd Party Cookies
