### ISSUE TITLE
Editor: Conflict with Calypso and Gutenberg and paragraph tags

### ISSUE THREAD

**Issue by mkaz** [Automattic/wp-calypso#21973] opened 2018-01-30 19:27 UTC
#### Steps to reproduce
1. Create a new post in Gutenberg (Jetpack site)
2. Edit post in Calypso and Save.
3. View post and P tags are removed.
4. Open post in Gutenberg paragraph blocks are modified

#### What I expected

Calypso editor is stripping out the `<p>` tags, which in turn is breaking the Gutenberg blocks. The Gutenberg error of blocks being modified is correct, since Calypso is modifying the blocks by running `removep` filter over post content.

#### Solution

A potential solution would be for Calypso to detect if Gutenberg blocks exists and to not apply the autop filter if they do.

**Comment by mkaz** [comment] 2018-01-31 22:14
I initially thought this was applied on API Side, which it still might be. However, looking at the API, the paragraph tags do not even reach the endpoint. This can be confirmed by adding in paragraph tags in HTML mode, and then switching to Visual and back to HTML and the tags are removed.

**Comment by austinginder** [comment] 2018-02-14 20:07
I believe this is a conflict between Gutenberg 2.1.0 and Jetpack 5.8. Downgrading Gutenberg to 2.0.0 resolves. Also deactivating Jetpack 5.8 resolves. To reproduce: 

* Installed Gutenberg 2.1.0 and Jetpack 5.8 and create a post with content blocks. 
* Reload the editor and see the P tags removed.

See quick screencast walkthrough: https://vimeo.com/255795293/bd24079e24

**Comment by austinginder** [comment] 2018-03-03 02:40
https://github.com/WordPress/gutenberg/issues/3922

**Comment by mkaz** [comment] 2018-03-03 14:26
@austinginder thanks, this issue was hopefully fixed in Gutenberg 2.3.0 which was released yesterday. Please try it out and let me know if it fixes the issue for you.

Here is the relevant Gutenberg PR https://github.com/WordPress/gutenberg/pull/5288

**Comment by nosolosw** [comment] 2018-03-05 11:02
Not sure if related or not, but here's what I see when I try to edit with Calypso a post created with Gutenberg in a Jetpack site:

**In Gutenberg** everything looks like the published post:

![gutenberg-post-dotorg](https://user-images.githubusercontent.com/583546/36971724-0340a07c-206d-11e8-90f5-ebd2ee1cbc14.png)


**In Calypso** there are some formatting issues and some paragraphs are split

![gutenberg-post-calypso](https://user-images.githubusercontent.com/583546/36971552-7705ec02-206c-11e8-971e-8d6c82b9eac7.png)

**Comment by kristarella** [comment] 2018-10-18 06:38
I think this issue may be related: https://github.com/WordPress/gutenberg/issues/10376

I'm closing the other as it seems to be calypso-specific

**Comment by gwwar** [comment] 2018-10-23 23:40
> A potential solution would be for Calypso to detect if Gutenberg blocks exists and to not apply the autop filter if they do.

@mkaz Isn't the issue that we're not running `wpautop` for the published view when published from the classic Calypso editor, and there is a html comment block tag?


### How Paragraphs are Serialized


For more context, classic posts made in the WordPress wp-admin editor and Calypso, stores content in a simpler format:</p>



<h4>Classic</h4>



<p>On the server we'll see paragraphs noted by two line breaks:</p>



<pre class="wp-block-code"><code>My Paragraph 1\n\nMy Paragraph 2</code></pre>



<p>When the editor loads, it runs content through this function which adds p tags:</p>



<pre class="wp-block-code"><code>this.editor.setContent( wpautop( initialValue ) );</code></pre>



<p>And likewise before save on the client, we remove them again:</p>



<pre class="wp-block-code"><code>e.content = removep( e.content );</code></pre>



<p>The server will also run <code>wpautop</code>:</p>



<p>So we'll see the following in the published view:</p>



<pre class="wp-block-code"><code>&lt;p>My Paragraph 1&lt;/p>
&lt;p>My Paragraph 2&lt;/p></code></pre>



<h4>Gutenberg</h4>



<p>But what do Gutenberg paragraphs look like? The client and server both show and store the following:</p>



<pre class="wp-block-code"><code>&lt;!-- wp:paragraph -->
&lt;p>My Paragraph 1&lt;/p>
&lt;!-- /wp:paragraph -->

&lt;!-- wp:paragraph -->
&lt;p>My Paragraph 1&lt;/p>
&lt;!-- /wp:paragraph --></code></pre>



<p>The published view does not display these HTML comments:</p>



<pre class="wp-block-code"><code>&lt;p>My Paragraph 1&lt;/p>
&lt;p>My Paragraph 2&lt;/p></code></pre>

**Comment by supernovia** [comment] 2018-10-24 00:52
I also ran into this; wrote a post in Gutenberg wp-admin, edited in Calypso (because that's what the edit link leads to), then paragraphs were gone.

Only, if I view the HTML in the Gutenberg editor, the paragraph tags are all still there. :/  They don't show up in the revisions, though.

**Comment by lancewillett** [comment] 2018-10-24 21:17
I've been running into this for weeks but assumed I was an early adopter. 😄 Right now I avoid it by only using one editor experience for each P2 post (not switching between contexts or editors).

**Comment by gwwar** [comment] 2018-10-26 21:31
note to self: potentially related D18636-code

**Comment by gwwar** [comment] 2018-10-26 21:39
Verified the issue. Also verified that removing all Gutenberg comments in the classic editor will re-instate the p tag behavior as expected.

**Comment by gwwar** [comment] 2018-10-31 19:10
Folks can't reproduce on master anymore so, something must have fixed the issue in the last few days. Closing this out for now. If folks see other compatibility issues please file a new issue instead of resurrecting this one.

**Closed by gwwar** 2018-10-31 19:10 UTC
Labels: Editor, [Goal] Gutenberg, [Pri] High, [Type] Bug

**Comment by vindl** [comment] 2018-10-31 19:15
Just wanted to confirm that I wasn't able to reproduce this both for Simple and Jetpack sites on current master.

**Comment by vindl** [comment] 2018-11-14 10:20
Not sure if this is relevant yet, but there was an `autop` related change in 4.2 that might have caused a regression? D20219-code

**Comment by tyxla** [comment] 2018-11-15 15:56
Possibly related: 

https://core.trac.wordpress.org/ticket/45290
https://github.com/Automattic/jetpack/issues/10634
https://github.com/Automattic/jetpack/pull/10635

**Comment by jjchrisdiehl** [comment] 2018-11-26 17:02
Just wanted to note that I am seeing this issue on the WordPress.com support theme, see: https://en.support.wordpress.com/wordpress-editor/blocks/common-blocks/

**Comment by gwwar** [comment] 2018-11-26 18:18
@tyxla @jjchrisdiehl if folks are seeing new reports, can we please open new issues with specific steps? autop misbehavior will trigger in various ways, and this will help us fix specific cases.
