### ISSUE TITLE
Pexels Integration: Hitting enter too quickly after typing won't trigger search

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57079] opened 2021-10-15 21:22 UTC
### Quick summary

When using Pexels integration, you can hit enter too quickly after typing your search term, and it won't actually update your search.

### Steps to reproduce

1. Start a post and add an Image Block. Select to use Pexels
2. Type a term and hit enter quickly to search
3. Try a different term and again make sure to hit enter quickly after typing

### What you expected to happen

To see the results for the new search term

### What actually happened

You see the results for whatever the last search term was

### Context

I've been dogfooding a new blog, and I hit this a lot actually - it took me a bit to figure out what was causing it, but I kept finding my search terms not actually being used!

I think keyboard proficient folks might be used to hitting enter pretty quickly after entering a search term.

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No

### Other notes

![pexels_search](https://user-images.githubusercontent.com/26772342/137555046-11fef554-16f6-4a88-bca2-b08ea3b6d51f.gif)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Just wait a bit :)

**Comment by ivan-ottinger** [comment] 2021-11-03 11:55
Here are the outcomes of initial investigation:

The code lives in Jetpack ([projects/plugins/jetpack/extensions/shared/external-media/sources/pexels.js](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/shared/external-media/sources/pexels.js)).

The `PexelsMedia` component is re-rendering every time we make a change to the searched term (even without hitting Enter or clicking on the `Search` button). During this time, the new search is happening (the [getNextPage](https://github.com/Automattic/jetpack/blob/4736d6b62fda26c927f6c0c49522fbc2b6833bf2/projects/plugins/jetpack/extensions/shared/external-media/sources/pexels.js#L30-L44) callback runs) and if during this time we hit Enter (or click the `Search` button), the [onSearch](https://github.com/Automattic/jetpack/blob/4736d6b62fda26c927f6c0c49522fbc2b6833bf2/projects/plugins/jetpack/extensions/shared/external-media/sources/pexels.js#L47-L55) callback is run and the `previousSearchQueryValue.current` [is set](https://github.com/Automattic/jetpack/blob/4736d6b62fda26c927f6c0c49522fbc2b6833bf2/projects/plugins/jetpack/extensions/shared/external-media/sources/pexels.js#L52) to be equal with `searchQuery` (containing the current search query).

As a result, the `Search` button is disabled because of the `searchQuery === previousSearchQueryValue.current` condition that is present on the `Button` component:

```jsx
<Button
	isPrimary
	onClick={ onSearch }
	type="submit"
	disabled={
		! searchQuery.length || searchQuery === previousSearchQueryValue.current || isCopying
	}
>
```

and therefore `onSearch` callback is not triggered and no new results are displayed.

→ If we can prevent the `getNextPage` callback from running while we are typing into the search box, that should fix the issue.

One fix that would prevent the user from getting stuck in a state where the search results aren't updated infinitely could be to utilize `isLoading` and add it to the condition that rules when the `Search` button should be disabled:

```jsx
<Button
	isPrimary
	onClick={ onSearch }
	type="submit"
	disabled={
		! searchQuery.length ||
		isLoading ||
		searchQuery === previousSearchQueryValue.current ||
		isCopying
	}
>
```

This way, the user wouldn't be able to submit the form until the `getNextPage` run is finished. But the user who is quick and hits Enter while the button is disabled would still need to hit Enter again. But at least they won't get stuck.

**Comment by ivan-ottinger** [comment] 2021-11-04 08:35
I am working on a PR and will add it here soon.

**Comment by ivan-ottinger** [comment] 2021-11-09 09:40
The issue is now fixed by https://github.com/Automattic/jetpack/pull/21641.

**Closed as completed by ivan-ottinger** 2021-11-09 09:40 UTC
Labels: Bug, [Pri] Low, [Feature] Media, [Pod] Flow Patrol (Manage)

**Comment by dpasque** [comment] 2021-11-09 15:03
Hurray, thank you so much!! 🎉
