### ISSUE TITLE
Media & Text Block produces invalid content on image focal point adjustment

### ISSUE THREAD

**Issue by nickpagz** [Automattic/wp-calypso#37680] opened 2019-11-18 16:22 UTC
#### Steps to reproduce
1. Start a new page and insert a media and text block.
2. Add an image on the left, and a paragraph block with some text on the right.
3. Click on the image and choose the option **Crop image to fill entire column**
4. In the Focal Point Picker window, drag the focal point to another location.
5. Publish/Update the post and Refresh the page.

#### What I expected
I expected to be able to still edit the block further.

#### What happened instead
Block shows a **This block contains unexpected or invalid content** message. See screencast below.

#### Browser / OS version
Chrome, MacOS 10.14.6

#### Screenshot / Video
Screenshot of Focal point picker settings:
[![oops - image missing](https://cld.wthms.co/2D1Vc6+)](https://cld.wthms.co/2D1Vc6)

Screencast of block failing:
https://cld.wthms.co/RwxrHo

#### Context / Source
#manual-testing #user-report

#2498713-zen

**Comment by nickpagz** [comment] 2019-11-18 16:24
An additional note: After some additional testing, this happens on Simple sites only, Atomic still works as expected.

**Comment by kcswong** [comment] 2019-11-29 18:42
Another report in 16980063-hc, they only had one of a few Media & Text blocks that had the crop option selected and it was the only one failing. Had them deselect that option, which cleared the `unexpected content` message

**Comment by synora** [comment] 2021-01-22 16:09
@sirreal this is an old bug but is it something your team can look into? Or could it be closed?

**Comment by sirreal** [comment] 2021-01-22 16:23
I just tested and was unable to reproduce. Can someone confirm whether this is still an issue and close if not?

**Comment by synora** [comment] 2021-01-22 16:29
I just tested and cannot reproduce. Closing issue.

**Closed by synora** 2021-01-22 16:29 UTC
Labels: Blocks, [Type] Bug
