### ISSUE TITLE
Themes section loads on a separate screen compared to the rest

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#96619] opened 2024-11-21 11:47 UTC
### Quick summary

Quoting from [here](https://github.com/Automattic/dotcom-feedback/issues/330):

>Weird UX when I click on "Themes" from that same account. Plugins doesn't seem to have the same problem

### Steps to reproduce

1. Create a new account
2. Click between Sites, Domains and Themes

### What you expected to happen

To showcase the theme from the same screen and not move me to the dashboard

### What actually happened

It moved me to a separate dashboard screen

https://github.com/user-attachments/assets/6645a5df-8c65-488c-9cb6-3e593e48c0ce

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

**Comment by zaguiini** [comment] 2024-11-22 00:09
@Robertght I cannot reproduce that. Is it intermittent for some users?

Here's what I see:

![Image](https://github.com/user-attachments/assets/10dd6cde-9281-4a83-a42d-22b32061b315)

**Comment by Robertght** [comment] 2024-11-22 05:12
Thanks @zaguiini !

I just tested it again and it's the same here:



To confirm, I tested this proxied and unproxied and on a separate chrome profile.

**Comment by zaguiini** [comment] 2024-11-22 13:22
Right, @dsas. I just arrived at the same results. When entering `/themes` we should not redirect the user. However, the same behavior is observed if you click `Plugins > Manage Plugins`. So, I'm unsure if we should remove that behavior globally or acknowledge this as expected.

**Comment by dsas** [comment] 2024-11-22 13:40
Put this on the Connecting the Dots board as an untangling issue that needs a design decision that needs to be thought through in conjunction with `Plugins > Manage Plugins` as @zaguiini discovered.

**Comment by dsas** [comment] 2024-11-22 13:43
Marked as a T-Rex issue on the oneboard, just so groundskeepers don't keep picking it back up again. It's an untangling issue I think, so any other Marvel team should feel free to pick it up though.

**Comment by BogdanUngureanu** [comment] 2024-11-27 16:05
I think it's fine to point `Plugins > Manage Plugins` to the Global View, plus we already do that for the other ones in the Plugins section.

I've opened a PR with these changes [here](https://github.com/Automattic/wp-calypso/pull/96843).

**Closed as completed** 2024-11-28 17:09 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] High, Triaged, [Feature] Theme Showcase, [Platform] Simple, [Status] Priority Review Triggered, [Product] WordPress.com, [Status] Auto-allocated, [Status] Escalated to Product Ambassadors
