### ISSUE TITLE
Site Editor fails to load homepage when the theme uses Front Page template and "Your homepage displays" set to static page

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#79224] opened 2023-07-11 07:48 UTC
### Steps to reproduce

1. Activate a theme that has Front Page template (e.g. [Kigen](https://github.com/Automattic/themes/blob/trunk/kigen/templates/front-page.html), [Hey](https://github.com/Automattic/themes/blob/trunk/hey/templates/front-page.html))
2. Go to Settings -> Reading.
3. Change the "Your homepage displays" to a static page.
4. Open Appearance -> Editor.

### What you expected to happen

I can see and edit my homepage in the Site Editor.

### What actually happened

The Site Editor shows blank page and I cannot do anything:

<img width="1140" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/3925048d-437e-4db4-b5a7-2954e660b819">

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

See also: pekYwv-28q-p2

**Comment by karenroldan** [comment] 2023-07-12 15:28
📌 REPRODUCTION RESULTS
- **Tested on Simple** – Replicated
- **Tested on Atomic** – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
The issue can be replicated exactly as described above. The site editor is not loading when setting the homepage to a static page and the theme uses a front page template.

**Kigen**

https://github.com/Automattic/wp-calypso/assets/67279475/1bc01c7e-8502-46dc-b9d5-6d0f92ff9e8a



**TT3** 
![4Ay2Nz.png](https://github.com/Automattic/wp-calypso/assets/67279475/24f30ac3-ebb7-448d-86a4-9b1f70152c57)

📌 ACTIONS
- Assigned to @Automattic/lego

**Comment by arthur791004** [comment] 2023-08-02 08:20
I guess it's a Core issue since I can reproduce this issue on the JN site. But it's weird that sometimes it still works well on the JN site 🤔

The root cause is the front-page template uses the patterns registered from the theme, and those patterns don't seem to be loaded or rendered under this scenario.

![image](https://github.com/Automattic/wp-calypso/assets/13596067/26b4db2c-3e6a-4747-9758-e5429de73fa3)

**Comment by arthur791004** [comment] 2023-08-02 10:09
Submitted an issue, https://github.com/WordPress/gutenberg/issues/53264, there. The root cause is the Front Page template doesn't have the post content so that those blocks are not available under this scenario.

**Comment by fushar** [comment] 2023-08-02 10:21
Wow, thanks for investigating this issue @arthur791004! ❤️

**Comment by arthur791004** [comment] 2023-08-03 07:09
This issue would be resolved with Gutenberg 16.4.0 🎉

**Comment by okmttdhr** [comment] 2023-08-16 04:49
Closing, as GB 16.4.0 has been released on all the Simple sites and edge Atomic sites.

**Closed as completed by okmttdhr** 2023-08-16 04:49 UTC
Labels: Bug, [Pri] High, Triaged, [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered
