### ISSUE TITLE
Post locking screen not always displayed

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#83426] opened 2023-10-24 14:16 UTC
### Quick summary

A dotorg install displays this dialog when two users try to edit the same page. 

<img width="484" alt="Screenshot 2023-10-27 at 09 07 24" src="https://github.com/Automattic/wp-calypso/assets/93301/5dd4d2c2-a19d-4edd-8d78-fe789e557793">

This dialog does not appear on dotcom. A similar one can be sometimes triggered.

#### Is the modal broken?
Once the dialog is being displayed, I think it's probably broken when using the calypso page/post editor.

The [iframe bridge](https://github.com/Automattic/wp-calypso/blob/f0de7a9a6fb85848d7390865ee7a46779b4895f1/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L4) has some code related to making the post locking modal work across despite modals. 

It [assumes that the post locked dialog has three buttons](https://github.com/Automattic/wp-calypso/blob/f0de7a9a6fb85848d7390865ee7a46779b4895f1/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L153) but since https://github.com/WordPress/gutenberg/pull/37852 it only has two.

This means it's not overriding the all posts link to bust out the iframe and it's not modifying the take over button to add the frame-nonce.

### Steps to reproduce

1. Create a simple site and add an extra editor user to it
2. As one user create a new post and save it as a draft. Leave this window open
3. In a second profile/private window log in as the second user and then open the same draft as the other user has open.

### What you expected to happen

A dialog to appear to the second user warning them that someone is already working on this page/post. Like the initial screenshot (made using a dotorg install).

### What actually happened

Nothing, I could use the editor as normal.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Logs or notes

In a dotorg install pressing 'Take over' will mean the original user will see a dialog warning them of this:

<img width="484" alt="Screenshot 2023-10-27 at 09 13 17" src="https://github.com/Automattic/wp-calypso/assets/93301/cb933e66-fd11-4b51-bab0-20a5f02aad1d">

This dialog does eventually appear in dotcom, if you start typing in both windows.

**Comment by cuemarie** [comment] 2023-10-26 19:50
Hey @dsas ! Would you like KitKat to replicate this further for you as part of triage? If so, I could use some info on what's expected/what's actually happening - I can't quite tell from the report above what to look for in that test.  Once I know that, happy to test across Simple & Atomic to add further notes/screenshots!

**Comment by dsas** [comment] 2023-10-27 08:22
Hey @cuemarie. Sorry, this was a problem I found while looking at some related code but couldn't get to the affected modal dialog as the user. I've explored the problem a little more and rewritten the issue to be more user-centric.

**Comment by cuemarie** [comment] 2023-10-30 20:52
Much appreciated @dsas !

**Comment by cuemarie** [comment] 2023-10-30 23:14
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described!  I was never notified that someone was _already_ editing a post. I did eventually run into the notification that "Someone else has taken over this post".

https://github.com/Automattic/wp-calypso/assets/27249804/373aea78-153f-4fc1-8315-6d72b991056a

📌 ACTIONS
- Triaged

**Comment by davemart-in** [comment] 2024-10-18 17:34
I'm not sure why this is stripped out. This can be super handy in situations where multiple people are trying to edit a page/post. Otherwise edits can be lost.

**Comment by BogdanUngureanu** [comment] 2024-10-21 14:37
I think this is on purpose in D49393-code and only limited to a12s as a way to prevent blocking users during support sessions.

I've tried to reproduce it with my test (non-a8c) accounts and I couldn't reproduce it.

Closing this. :)

**Closed as completed by BogdanUngureanu** 2024-10-21 14:37 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] Low, Triaged, [Product] WordPress.com, [Feature Group] Editor Experience

**Comment by inaikem** [comment] 2024-10-22 14:58
@BogdanUngureanu, we're running some group triage at the moment and came across this issue. Did you resolve it as part of your Dotcom Groundskeeping rotation this week? Thanks!

**Comment by BogdanUngureanu** [comment] 2024-10-22 15:43
@inaikem yes, I investigated it yesterday.
