### ISSUE TITLE
Block Editor: Unable to select a parent page on a site that has lots of pages 

### ISSUE THREAD

**Issue by rambogenius** [Automattic/wp-calypso#47052] opened 2020-11-03 12:18 UTC
#### Steps to reproduce

1. Starting at URL: https://prestonhistory.com/ (user's site with 400 plus pages)
2. You can try to edit any page and try to find Subjects page to set as its parent page in Page attributes, it cannot be done in Block Editor as it never comes up in search. So user as to rely on WP-Admin Dashboard to make this change
3. It does not happen on sites with less number of pages though

#### What I expected
User should get exact match appeared first in a search so that user can easily select a parent page

#### What happened instead
The page name never comes up in search when the pages are higher on a site

#### Screenshot / Video
https://d.pr/i/G9ncoI

#user-report

**Comment by simison** [comment] 2020-11-03 12:20
Might be fixed with this commit https://github.com/WordPress/gutenberg/commit/77fbd6fab9c79bad0511d8d2f1d6558bd325c2d7

**Comment by stumax** [comment] 2020-11-08 11:12
Additional report of this issue in 3465427-zen

thanks

**Comment by nagpai** [comment] 2020-11-12 15:07
One more report 
#20173473-hc

Simple site 

User's objective was to use parent-child feature for arranging menu. Guided them to use the menu editor instead, for the moment.

**Comment by vparkhere** [comment] 2020-11-14 21:54
Another report:
25637895-hc
 follow-up once fix is implemented: 3489862-zen

Current workaround is to go to Pages via WP Admin and then use "Quick Edit".

**Comment by dolgelukkig** [comment] 2020-11-15 14:47
Another one:

[#3490430-zen](https://woothemes.zendesk.com/agent/tickets/3490430)

Offered workaround via WP Admin and then use "Quick Edit".

**Comment by bsanevans** [comment] 2020-11-16 23:37
Another report here: 3487898-zd-woothemes

Original report: pbEMJv-jY-p2

**Comment by poojashetty18** [comment] 2020-11-17 08:34
Another one: 1362290 - hc

Offered workaround via WP Admin and then use "Quick Edit".

The last HE could see the pages https://d.pr/i/2lvG4E however, me and the user could not see the pages from Calypso. User tried on both Chrome and Internet Explorer

**Comment by as-esu** [comment] 2020-11-21 10:20
One more report: 3497406-zen
Informed them about WP-Admin workaround.
It looks like this thread is possibly related to [#30252](https://github.com/Automattic/wp-calypso/issues/30252)

**Comment by inaikem** [comment] 2020-12-03 01:11
Coming back to this issue to update a customer and noticed the original interaction had not been noted: 3455274-zd

**Comment by simison** [comment] 2020-12-03 10:53
Gutenberg 9.3 with [potential fix](https://github.com/WordPress/gutenberg/pull/26397) is on WordPress.com already — is this still an issue? cc @Automattic/good-mountain

**Comment by sirreal** [comment] 2020-12-03 13:26
I tested and was able to view and search the parent page selector for the site mentioned. I'll close as I believe this has been fixed. Please reopen if there are more report.

**Comment by csonnek** [comment] 2021-05-22 14:32
Reopening this issue as we have another report in this forums thread: https://wordpress.com/forums/topic/lovecraft-cant-add-pages-after-parent-page/

Logged in as the user and confirmed the same behavior as the OP. They have 175 Pages published. 

Advised to use the wp-admin workaround for now.

**Comment by cuemarie** [comment] 2023-04-27 21:41
This looks like a duplicate of this report: https://github.com/Automattic/wp-calypso/issues/49684

Since this report contains user-specific data, I'm closing it in favor of #49684 , which we'll try to get some eyes on!

**Closed by cuemarie** 2023-04-27 21:41 UTC
Labels: [Type] Bug, Editor, Support

**Comment by staproehl** [comment] 2024-05-30 00:58
8201402-zen
