### ISSUE TITLE
Reader: subscriber count for feed and site are different

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#937] opened 2015-11-29 06:21 UTC
Raised by @bluefuton 

@rachelmcr reported that the subscription counts for the same blog are different in feed view and site view.

I've manually fixed the example she originally provided (https://wordpress.com/read/blog/id/77165854 vs https://wordpress.com/read/blog/feed/35435606) but here are screenshots of the problem:

![screen-shot-2015-08-03-at-3-12-34-pm](https://cloud.githubusercontent.com/assets/17325/9074801/599dc816-3ac2-11e5-941a-efcde0781d4f.png)
![screen-shot-2015-08-03-at-3-16-26-pm](https://cloud.githubusercontent.com/assets/17325/9074802/599f9c36-3ac2-11e5-826d-6a1101eca4ee.png)

It looks like the feed count is the wrong one. It comes from Feedbag (feedbag.subs) which doesn't appear to be synced properly with the actual count from the subscription matrix.

Let's track any further examples here.

**Comment by designsimply** [comment] 2015-11-29 06:21
Note from @rachelmcr 

> I have another example from my own blog: http://happylinguist.com/
> Site view (675 followers): https://wordpress.com/read/blog/id/48063327
> Feed view (339 followers): https://wordpress.com/read/blog/feed/33964912

**Comment by SiobhyB** [comment] 2016-02-14 15:52
Another example of this issue [came up on the WP.com forums](http://en.forums.wordpress.com/topic/changed-url-some-things-not-working).

Feed view incorrectly shows 2 followers: https://wordpress.com/read/blog/feed/44067393

<img width="766" alt="screen shot 2016-02-14 at 15 45 42" src="https://cloud.githubusercontent.com/assets/2998162/13034613/0bf0da14-d332-11e5-840c-0117fb18467f.png">

Blog view correctly shows 375 followers: https://wordpress.com/read/blog/id/49378121

<img width="761" alt="screen shot 2016-02-14 at 15 46 23" src="https://cloud.githubusercontent.com/assets/2998162/13034622/2d24527e-d332-11e5-9b14-f7f5f1026a84.png">

**Comment by bluefuton** [comment] 2016-02-14 23:56
Thanks @SiobhyB! 

I've have something in the works to sync the subscriber count with the subscription matrix each time a follow or unfollow happens.

**Comment by blowery** [comment] 2016-03-03 15:43
Should be fixed by #3760

**Comment by bluefuton** [comment] 2016-03-07 01:31
Fixed in #3760.

**Comment by rachelmcr** [comment] 2017-07-17 11:13
This issue seems to be back, and the fix in #3760 doesn't seem to be working anymore.

When I view a site in the Reader, I'm seeing the feed subscriber count instead of the site subscriber count, and there's a discrepancy between the two. I confirmed by checking the site's follower count and the feed follower count returned by the rest api, and the (inaccurate) feed follower count is what appears on the site details page in the Reader.

For example, my site's total follower count is listed as 832 when I check the `/sites/happylinguist.com/stats/followers` endpoint, but it's listed as 533 when I check `/read/feed/47062866` and that's what appears in the Reader: https://wordpress.com/read/blogs/48063327

Reported by a user (internal ref: 204792-h).

**Comment by carladoria** [comment] 2017-10-26 02:16
This was also reported here [637227-hc](/agent/tickets/755321) 
The Reader shows 4878 followers and the Stats show 4153

**Comment by chad1008** [comment] 2017-10-31 15:31
Another report in 760003-zen
Reader shows 509, stats and the  are showing `/stats/followers` endpoint is showing 390.

**Comment by nagpai** [comment] 2017-11-01 06:41
Link of user reported by @chad1008  - https://wordpress.com/read/feeds/39969592

**Comment by alisterscott** [comment] 2017-11-01 06:47
@blowery this has been coming up a bit in user requests - do you think we should up the priority?

**Comment by KokkieH** [comment] 2017-11-05 18:41
Possibly another case in 883030-f

Feed link: https://wordpress.com/read/feeds/73951953

**Comment by bluefuton** [comment] 2017-11-17 18:58
Fixed in https://github.com/Automattic/wp-calypso/pull/19961 🎉

**Closed by bluefuton** 2017-11-17 18:58 UTC
Labels: Reader, [Type] Bug
