### ISSUE TITLE
Nav unification Quick Switcher preferred option is not persisted when SSO is disabled

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#54501] opened 2021-07-13 11:15 UTC
### Steps to reproduce the behavior

1. Go to an Atomic site and make sure it doesn't have any quick switcher preferences.
2. Turn on the show admin toggle in /me/account (this toggle will be removed in another PR).
3. Go to WP-Admin > Jetpack > Dashboard > Settings and disable SSO (WordPress Login)
3. Go to Posts > All posts
4. Use the switcher to land in WP-Admin
5. Notice that the preferred choice is not persisted.

#### What I expected to happen
The quick switcher choice should be persisted.
#### What actually happened
It's not persisted.
#### Is this specific to the applied theme? Which one?
No

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Atomic on sites with SSO disabled.

**Comment by tjcafferkey** [comment] 2021-07-14 07:42
Moving this and adding `Needs spec` label because currently when SSO is disabled, in WP Admin we use the core navigation with _no Calypso links_ so I am not sure if this is even a regression since the Quick Switch. Something to discuss.

**Closed as completed** 2021-07-20 14:12 UTC
Labels: Bug, Needs spec, [Feature] Calypso & wp-admin Navigation, Triaged
