### ISSUE TITLE
Quarantined E2E: refactor `Notification: Trash`

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#66144] opened 2022-08-01 21:28 UTC
### Details

Refactor this test at `notifications__trash.ts`.

Key features/flows that should be covered by this are:
- confirm that notification shows up in the notification sidebar.
- user is able to trash the notification.

Optional flows that should be covered (in which case the spec should be renamed):
- user is able to interact with the notification in other ways (eg. approve)
- user is able to undo their previous action (eg. unapprove)

Gotchas:
- how to parallelize the test so that it can be run on multiple different branches simultaneously?
- how to generate the notification (UI or API)? 

### Checklist

- [ ]
- [ ]

### Related

https://github.com/Automattic/wp-calypso/issues/58683

**Comment by worldomonation** [comment] 2022-09-27 21:50
@john-legg I've assigned this medium-large task. This is part of a larger effort to un-quarantine specs so that there is some coverage.

The issue here is that `Notifications: Trash` was previously a little flaky, but the exact reasons have been lost to time. However, you should be able to glean whether this is flaky by checking out the Quarantined E2E build in TeamCity and its artifacts. [This Field Guide page](PCYsg-KAE-p2) should be useful tor investigation.

Things to think about, in addition to the details in the original comment:
  - [ ] What is the failure mode?
  - [ ] What is the failure rate?
  - [ ] Can the existing test be rewritten to isolate the setup (data generation) part so that it's more reliable? 

Note: this task may involve interaction with the WordPress.com REST API. Feel free to reach out for a primer if you need to.

**Comment by john-legg** [comment] 2022-10-18 01:03
### Quick Update
Hi @worldomonation! Sorry for the delay on this one. I've been taking the time to learn more about notifications and the WordPress.com REST API. Unfortunately, I haven't been able to reproduce any flakiness locally or find failures on any branch using the TeamCity investigation methods.

However, after experimenting with the API for a bit, I believe I can generate the notification needed for the test. I would imagine that this would help make it more reliable as you mentioned in your comment.

I've also been working on adding the following functionality that you suggested earlier:

> - user is able to interact with the notification in other ways (eg. approve)
> - user is able to undo their previous action (eg. unapprove)
> - how to parallelize the test so that it can be run on multiple different branches simultaneously?

Things are moving along, but I just wanted to give a quick update since I haven't commented on this thread yet 😅

**Comment by worldomonation** [comment] 2022-10-19 04:07
Thanks for the heads up @john-legg!

Good to hear the flakiness is not reproducible on your local testing. That's always great.

One piece of advice, if you find that you're getting bogged down with the size of the change, feel free to break it out into smaller pieces to make it more manageable. We recommend that a PR should not exceed about 250 lines of code to make it easier to review. Remember, smaller PRs more frequently is preferable than one massive change.

**Comment by john-legg** [comment] 2022-10-25 19:43
Thank you for your patience on this one @worldomonation - I'm still getting used to the open communication aspect of this 😓 That's great advice and I will definitely make that a goal of mine moving forward!  I just pushed a draft PR of what I have so far [#69446](https://github.com/Automattic/wp-calypso/pull/69446). 

I lost a bit of time to implementing/debugging the REST API flow within the test, so that part isn't fully functional yet. However, I've been recreating the flow in Postman to understand it better and what I'm missing (e.g. parameters) without having to deal with the  implementation part and it's been **very** helpful so far.

**Comment by john-legg** [comment] 2022-11-15 22:59
The associated PR [has been merged](https://github.com/Automattic/wp-calypso/pull/69446), however the test seems to be [failing intermittently on other branches](https://github.com/Automattic/wp-calypso/issues/69857). It looks to be a timeout issue, but I'm still investigating it. I will hopefully have a clearer idea soon.

**Comment by worldomonation** [comment] 2022-12-01 23:13
The work is done for now, thanks John!

**Closed as completed** 2022-12-01 23:13 UTC
Labels: Task, [Size] L
