### ISSUE TITLE
Verse Block Lost its Styling

### ISSUE THREAD

**Issue by sharonlaker19** [Automattic/wp-calypso#72416] opened 2023-01-23 09:25 UTC
### Quick summary

The Verse block appears to have suddenly lost all styling and now looks no different from the Paragraph block.

### Steps to reproduce

1. Create a new page and add the Verse block to it with some text.
2. Add a Paragraph block right below with the same text.
3. Publish the page and compare the appearance of the text on the two blocks.

### What you expected to happen

For the Verse block to have custom styling and look different from the default Paragraph block text.

### What actually happened

The Verse block and Paragraph block text look exactly the same:

![verse block](https://user-images.githubusercontent.com/71630911/214004219-1b705fd6-1528-4bda-863e-64a27737ae5f.jpg)

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

The user would need to go in and set custom font styles for their Verse block, which would be difficult if someone is already using it on many pages like the user in 5888935-zen

**Comment by liviopv** [comment] 2023-02-06 11:45
Another 

- [ ] 5928537-zd-woothemes

**Comment by liviopv** [comment] 2023-02-06 11:47
This seems to be theme-specific, as I couldn't repro on 2020 https://liviofree.wordpress.com/2023/02/06/6639/

**Comment by liviopv** [comment] 2023-02-06 11:56
I imagine it's due to this change https://github.com/WordPress/gutenberg/pull/46560, which makes the block use the theme's default font style for the Verse Block, so what we see now is the expected behaviour.

**Comment by cuemarie** [comment] 2023-03-05 20:30
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Replicated
- Tested on AT: Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Thanks for the context @liviopv ! I can replicate this, but based on the https://github.com/WordPress/gutenberg/pull/46560 note, it seems this is by design.


### AT Examples

**Twenty Twenty-One**

![Markup on 2023-03-05 at 13:28:30](https://user-images.githubusercontent.com/27249804/222984198-77ea2606-c946-4821-bdf8-228449c97254.png)

**Twenty Twenty-Two**

![Markup on 2023-03-05 at 13:24:54](https://user-images.githubusercontent.com/27249804/222984126-f388004c-fe2d-4f98-be92-010c880dea99.png)

### Simple Examples

**Twenty Twenty-Three**

**Zoologist**

![Markup on 2023-03-05 at 13:25:10](https://user-images.githubusercontent.com/27249804/222984121-288135e3-75de-406d-89ef-d275264b854f.png)

### Other Notes

**Twenty Twenty** does not repro the issue because reflects this behavior instead: https://github.com/Automattic/themes/issues/6866

![Markup on 2023-03-05 at 13:23:20](https://user-images.githubusercontent.com/27249804/222984137-af9c63e5-072a-41da-9508-5cacb2750026.png)


📌 ACTIONS
- Closed as by design (per https://github.com/WordPress/gutenberg/pull/46560)

📌 Message to Author
- Feel free to reopen or rereport as a feature request if this is something Users are asking for

**Closed as completed by cuemarie** 2023-03-05 20:30 UTC
Labels: Bug, [Pri] Low, Triaged
