### ISSUE TITLE
Notifications: Shortcode blocks are not parsed.

### ISSUE THREAD

**Issue by guarani** [Automattic/wp-calypso#45208] opened 2020-08-26 01:02 UTC
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/read
2. Open Notifications and locate a notification **from a post** that includes a Shortcode Block which contains a YouTube shortcode
3. Click to open it and reveal the secondary side pane and notice the raw shortcode
4. Open Notifications again and locate a notification **from a post comment** that includes a Shortcode Block which contains a YouTube shortcode
3. Click to open it and reveal the secondary side pane and notice the raw shortcode

#### What I expected

I expected to see the YouTube video itself in both the above scenarios. Perhaps a something instead of the video, like a YouTube icon or similar could also work.

#### What happened instead

Notice that the side panel doesn't display the YouTube video itself, you only see the shortcode itself (e.g. `[youtube https://www.youtube.com/watch?v=fX8YLri4wxU]`)

| Scenario | Screenshot  |
| - | - |
| Post notification ⚠️ | <img alt="Screenshot of post notification showing raw shortcode instead of actual YouTube video" width="1000" src="https://user-images.githubusercontent.com/1898325/91242373-3e134080-e715-11ea-8e7e-65cb9a374071.png" /> |
| Post comment notification ⚠️ | <img alt="Screenshot of post comment notification showing raw shortcode instead of actual YouTube video" width="1000" src="https://user-images.githubusercontent.com/1898325/91242294-0c9a7500-e715-11ea-89e8-2225d10c3bec.png" /> |

#### Browser / OS version

Firefox 79.0

#### Screenshot / Video

See above

**Comment by AtrumGeost** [comment] 2020-09-25 13:29
Hi folks!

Would this issue also cover the rendering in the notification emails?

We got a report from a user ( 3304752-zd-woothemes ) about YouTube videos no longer rendering in the email notifications:

**Before:**

![Markup on 2020-09-25 at 08:20:56](https://user-images.githubusercontent.com/3696121/94272283-7cfd0780-ff08-11ea-8710-176b864d46c1.png)

[Blog post from the screenshot](https://ministerioumcd.org/2020/09/19/ante-la-adversidad-orar/)

**After:**

![Markup on 2020-09-25 at 08:20:25](https://user-images.githubusercontent.com/3696121/94272311-84bcac00-ff08-11ea-8b97-b5abc4f2005a.png)

[Blog post from the screenshot](https://atrumtest03.wordpress.com/2020/09/25/testing-videos-on-email/)

Please, let me know if you need me to create a new issue for this :)

**Comment by guarani** [comment] 2020-09-28 14:07
> Would this issue also cover the rendering in the notification emails?

👋 Hi @AtrumGeost, you can add it here instead: https://github.com/Automattic/dotcom-manage/issues/210

**Comment by guarani** [comment] 2020-09-28 14:12
👋 Hi @AtrumGeost, I think that this issue belongs on a separate (internal) repo, I'll DM you the link.

**Comment by kwight** [comment] 2020-10-08 22:00
This applies to all shortcode blocks; updated the issue title.

**Comment by mmtr** [comment] 2020-10-30 11:08
I wonder if this can be fixed by running [`do_shortcode`](https://developer.wordpress.org/reference/functions/do_shortcode/) when getting the post content in `Notification_Builder::add_post_block`:

```
$post_content = do_blocks( $post->post_content );
$post_content = do_shortcode( post_content );
$post_content = apply_filters( 'the_content', $post_content );
```

**Comment by synora** [comment] 2021-02-15 18:37
I'm still able to replicate this issue: 
<img width="390" alt="Screen Shot on 2021-02-15 at 13-36-44" src="https://user-images.githubusercontent.com/10015451/107982939-f3230900-6f92-11eb-8e21-dc0881358cf9.png">

**Comment by davipontesblog** [comment] 2021-04-14 14:07
Part of the Block Audit milestone: https://github.com/Automattic/wp-calypso/milestone/320
As discussed with @4thhubbard, leaving it for future consideration.

**Comment by yansern** [comment] 2021-05-19 12:42
**Technical analysis:** 

The function `build_note()` in `class.notification-builders-v1-1.php` does not process shortcodes. Hence, shortcodes appear as in on notification sidebar.

The most similar shortcode parsing implementation is the one from comments. A filter called `comment_text` is picked up by `wpcom_do_comment_shortcodes` at `mu-plugins/shortcodes.php`.

I think if we introduce a new filter in notification builders where shortcode plugin can hook and parse shortcodes it'll fix it.

(Also, there was a report about youtube embeds missing in e-mail notifications. That issue is already resolved and is not part of the scope of this issue,)

**Comment by yansern** [comment] 2021-05-21 07:29
**Update:** Upon further digging it appears that the `comment_text` filter does parses shortcode into embed html. 
~However, this parsed html is not used.~ However, the comment text is converted back to shortcode when its fed through `wp_kses` (class.notifications-builders.php @ __construct():295).

**Comment by yansern** [comment] 2021-05-24 16:14
**Here a quick rundown of how the content of a notification is prepared:**

1. **It first renders the post/comment in html.**   
At this stage, shortcodes are converted into embed html.
2. **It strips the html down using `wp_kses()`.**  
At this stage, embed html are converted back into shortcodes. All other tags not part of allowed tags are also stripped off.
3. **It parses this stripped-html node-by-node and create an array of "range items".**     
At this stage, tags unrecognized by this parser is ignored. For example, the parser doesn't handle `<iframe>` tags.
4. **This array of "range items" is rendered as the content of notification on the client side.**

**Earlier attempts I've made:**

I tried messing around with `wp_kses()` but it is impossible to selectively allow embed html from specific vendors (that would require a lot of foolish html parsing work).

I also tried reconverting the shortcode back into embed html after `wp_kses()` strips it off. This seems inefficient but that was to avoid having to mess around with `wp_kses()`.

However, even with the shortcode was converted back into embed html, we still need to convert that embed html into a "range item" (at Step 3), which is impossible because the embed html from different vendors contains different html tags and different html attributes.

**The solution:**

I decided to approach this differently by having shortcodes render into a custom `<wpcom-notifications-custom-html content="escaped_html_here">` tag.

Then, add the `<wpcom-notifications-custom-html>` tag is then added `wp_kses()` whitelist.

Then, update the parser to convert `<wpcom-notifications-custom-html>` into `range_item` on the server-side.

Then, update the range renderer to render this custom html on the client-side.

**The drawback (might be an advantage):**

We will have to manually go through each and every shortcode vendor (youtube, vimeo, instagram, etc.) to enable support for rendering into  `<wpcom-notifications-custom-html>`.

However, this might be an advantage because we are controlling selectively what embed content we allow on the notifications panel rather than opening the flood gates to all embed at once.

I imagine we do not want all embed content to be rendered on the notifications panel anyway.

**Next steps:**

The phab patch D61784-code & PR https://github.com/Automattic/wp-calypso/pull/53120 will be the starting point to allow custom html in notification content (with YouTube as the first vendor to support it). And then we'll enable for each and every vendor we want to support in separate phab patches.

**Comment by yansern** [comment] 2021-06-29 16:10
I moved this back to Needs Triage because this is not a bug but a feature request.

The existing notifications content renderer clearly wants to simplify the content of the post body or comment body. So it was by design embed contents were missing.

What needs to be triaged is the product decision behind this. The question we should ask is: **How do we want to display the embed content in notification?**

Here I think are 2 choices:

**1. Show it as a url.**
The work needed is to verify that every shortcode is rendering the URL properly on the notification content.

**2. Show the embed content.**
The work needed is to make the necessary changes to make sure shortcodes can be successfully rendered on the notification content (which may include additional CSS wrangling to make sure it displays nicely on a narrow viewport, and additional JS wrangling, e.g. for FB embed, FB scripts needs to be injected separately on the page). Every shortcode vendor (YouTube, Facebook, Instagram etc.) is unique and poses it own set of challenges.

Whether we go for no. 1 or no. 2, both require project planning to scope out the breath of the work needed.

Also, I'd just like to make a clear distinction that there are 3 places where this is rendered:
1. Notification Dropdown
2. Reader
3. E-mail

And that each of them may differ _(needs further verification on e-mail part)_ in terms of pipeline of how the content is rendered.

**Comment by kwight** [comment] 2021-06-29 18:36
> I moved this back to Needs Triage because this is not a bug but a feature request.

I'd consider this a bug; the OP image shows a full raw shortcode, as opposed to a clickable link (it feels like the equivalent of showing raw escaped HTML).

**Comment by yansern** [comment] 2021-06-29 20:17
> I'd consider this a bug; the OP image shows a full raw shortcode, as opposed to a clickable link (it feels like the equivalent of showing raw escaped HTML).

Hmm, agree! Thanks for pointing out it was a **full raw shortcode** that was being presented for the user.

In that case, presenting a text link (no. 1) is already good enough, considering the technical challenges that comes with (no. 2).

What do you think? Let's go ahead with no. 1 - presenting text link?

**Comment by kwight** [comment] 2021-06-29 23:46
> What do you think? Let's go ahead with no. 1 - presenting text link?

Sounds good, a definite improvement (I think sorting proper embed rendering for various shortcodes would require a given project).

**Comment by yansern** [comment] 2021-06-30 02:28
Just posting this as a note to myself:

Drawing comparison between Shortcode block and YouTube block.

YouTube block generates a thumbnail with a link to the to the YouTube video. The html looks like this:
```
<div><p class="wpnc__p"><a href="https://www.youtube.com/watch?v=nORg_aXMsmA" target="_blank" rel="noopener noreferrer" class="wpnc__a"><img src="https://i0.wp.com/img.youtube.com/vi/nORg_aXMsmA/0.jpg" class="wpnc__image"></a></p></div>
```

### Post Content on Notification

![2021-06-30_10-22-30](https://user-images.githubusercontent.com/1287077/123892466-3d7ab480-d98d-11eb-853a-59a2a3acf806.jpg)

### Comment Content on Notification

![2021-06-30_10-22-40](https://user-images.githubusercontent.com/1287077/123892476-423f6880-d98d-11eb-9232-a9c784fbdd3c.jpg)

**Comment by yansern** [comment] 2021-09-16 09:53
Shortcodes on notifications are now being tracked our shortcode/embed rendering fallback project. See pd8D2H-h2-p2.

YouTube shortcode is now fixed with https://github.com/Automattic/jetpack/pull/21000, along with Spotify, Soundcloud, Dailymotion, VR as of speaking.

I will close this issue for now.

**Closed by yansern** 2021-09-16 09:53 UTC
Labels: [Type] Bug, [Pri] High, Notifications, Blocks, User Report, Triaged
