### ISSUE TITLE
Navigation block shows HTML formatting

### ISSUE THREAD

**Issue by serabi** [Automattic/wp-calypso#38454] opened 2019-12-16 17:41 UTC
When you add Bold or Italic formatting to a link in the navigation block on a Simple site, the formatting shows in the editor, but HTML shows on the published site. 

#### Steps to reproduce
1. Add a navigation block to a page with a link inside the navigation block
2. Bold or italicize the link:

<img width="623" alt="Screen Shot 2019-12-16 at 12 37 30 PM" src="https://user-images.githubusercontent.com/30205248/70929410-1229b200-2001-11ea-85ca-4180ba43acc3.png">

3. Publish the page

#### What I expected

For the links to be formatted

#### What happened instead

HTML appears around the link text:

<img width="924" alt="Screen Shot 2019-12-16 at 12 37 06 PM" src="https://user-images.githubusercontent.com/30205248/70929449-27064580-2001-11ea-8203-e6c3628ad56d.png">

The site that reported the bug is on the Maywood theme (2565322-zen) I also tested it on Dara and Twenty Twenty.

**Comment by kriskarkoski** [comment] 2020-03-13 17:07
I cannot reproduce this issue on the current version of the Block Editor or the upcoming update available on Edge stickered sites. Marking as done.

**Closed by kriskarkoski** 2020-03-13 17:07 UTC
Labels: Blocks, Editor, Frontend, [Type] Bug
