### ISSUE TITLE
Improve the logged in site upgrade banner

### ISSUE THREAD

**Issue by amamujee** [Automattic/wp-calypso#43896] opened 2020-07-04 13:46 UTC
pbAPfg-BB-p2#comment-1309

@rickybanister  @davemart-in

**Comment by davemart-in** [comment] 2020-07-28 19:48
I'm going to close this out as a duplicate of https://github.com/Automattic/wp-calypso/issues/43896

**Closed by davemart-in** 2020-07-28 19:48 UTC
