### ISSUE TITLE
Publicize: LinkedIn connection problems

### ISSUE THREAD

**Issue by nielslange** [Automattic/wp-calypso#46802] opened 2020-10-27 11:43 UTC
Initially, this problem got reported in https://github.com/Automattic/wp-calypso/issues/32007. While it was fixed, as mentioned in https://github.com/Automattic/wp-calypso/issues/32007#issuecomment-555632166, the problem still seems to occur. Today, we received another report about this problem in 22052362-hc / 3440308-zen.

**Comment by TeniCola** [comment] 2020-11-06 14:36
I encountered another case where the user is unable to connect to Linked in. They mentioned the following in 24982997-hc / 3469046-zen:

> "The connection to LinkedIn is broken. It won't take my password. I know it's the correct password because I just used it to log in to LinkedIn."

When I’m not logged in to Linkedin, I get an `Invalid/missing request nonce` error message when I click "Connect" or "Reconnect" in their account, for any of their websites. For now, I may advise them to try sharing their content manually on Linkedin until there's another fix

**Comment by geekinthegirl** [comment] 2020-11-11 10:22
I've just come across another case of this here: 24004597-hc

The user's LinkedIn connection stopped working, and won't reconnect. Whenever I try to reconnect, the Invalid/missing request nonce error pops up too.

I also advised them to manually share their content to LinkedIn, in the meantime!

<img width="782" alt="Screenshot 2020-11-11 at 10 20 16" src="https://user-images.githubusercontent.com/22247240/98799954-ae258e80-2407-11eb-8f5d-193d1f0aac3a.png">
<img width="782" alt="Screenshot 2020-11-11 at 10 20 25" src="https://user-images.githubusercontent.com/22247240/98799978-b54c9c80-2407-11eb-911b-9aeb984e2a21.png">

**Comment by mlaetitia** [comment] 2020-11-15 14:04
One more report: 3490899-zd

**Comment by formosattic** [comment] 2020-11-18 22:15
+1 18446558-hc

**Comment by obenland** [comment] 2021-01-29 23:02
@ebinnion Do you think there's a chance we've started running into API throttling again that may have caused the above issues?

**Comment by ebinnion** [comment] 2021-02-04 18:56
Looking at the stats in our LinkedIn App, yes, it looks likely. I have some screenshots that I can share to p2 if you have a link handy?

**Comment by obenland** [comment] 2021-02-04 19:55
I don't think there's a P2 for this currently. Would you want to append this to p7fD6U-2Za-p2 ? Or create a new one?

**Comment by ebinnion** [comment] 2021-02-04 23:10
I responded in a comment on that p2. I may start out here by adding some more comprehensive logging so that we can come up with a better fix.

**Comment by ebinnion** [comment] 2021-02-05 04:23
Logging patch here: D56536-code

**Comment by obenland** [comment] 2021-02-05 17:42
Thank you!

**Comment by adelineyaw** [comment] 2021-02-15 02:37
Another case to report via 27747899-hc

**Comment by geekinthegirl** [comment] 2021-03-01 13:39
Just had another case here: 26709912-hc

**Comment by Nic-Sevic** [comment] 2021-03-09 10:55
Also happening here: 3803980-zen

User gets nonce error for all connection types but some (linkedin, twitter, tumblr) then produce pop-up to allow connection. FB does not.

**Comment by farmerfunster** [comment] 2021-03-17 15:33
Also happening with me since early Feb, just for Linkedin.
Twitter, FB etc are still all good.

An API request using https://public-api.wordpress.com/connect/?action=request&kr_nonce=... returns the nonce error, even though LinkedIn reports a successful authorisation. WP app UI just hangs with 'Connecting...'

See forum thread at https://wordpress.com/forums/topic/publicize-linkedin-connection-problem/#post-3649807

![image](https://user-images.githubusercontent.com/25662850/111491945-2e505d80-8734-11eb-915e-2fb1245437a3.png)
![image](https://user-images.githubusercontent.com/25662850/111493888-e16d8680-8735-11eb-80e5-e9a144d1b5c6.png)

**Comment by chrisfromthelc** [comment] 2021-03-18 17:46
I had a user in 28315510-hc for this.

Several reconnection attempts; had them log out and back in, cleared the connection in Publicize, but no success.

It shows Reconnect on LinkedIn, and in the Publicize RC, the connection shows broken.

**Comment by ericamQA** [comment] 2021-03-30 21:41
Another report in 26272052-hc **who would like to be emailed when this is resolved.**

**Comment by obenland** [comment] 2021-03-30 21:52
@ebinnion Has your logging enhancement yielded any fruits yet?

**Comment by ebinnion** [comment] 2021-04-01 02:07
I spent some time debugging and tracing tonight. I was able to reliably reproduce the issue with the following:

- Create LinkedIn connection 
- Go to LinkedIn and revoke connection
- Go to Publicize Report Card and test connection, which should update WPCOM that the connection is broken
- Go to `/marketing/connections/$site` and refresh the connection

After dropping some debug code, I can verify that the token itself does get verified and stored correctly each time I verify it. So, the issue is not rate limiting or verifying the token.

My guess, is that there may be an issue with how we're handling refreshing tokens in Calypso because the only difference that I was able to see is that when I'm creating a new connection to LinkedIn I see the following:

<img width="641" alt="Screen Shot 2021-03-31 at 8 53 56 PM" src="https://user-images.githubusercontent.com/1126811/113233394-be2df580-9264-11eb-8525-5d3a5f0cb2ee.png">

I do not see the same thing when refreshing the connection.

@obenland  – do you think someone from manage can take that thread and debug in Calypso?

For HEs – The workaround that I have figured out for now is to disconnect and then reconnect to LinkedIn.

**Comment by ericamQA** [comment] 2021-04-04 03:47
Another report, says they've been experiencing this for 6+ mos in 3867441-zen

**Comment by ericamQA** [comment] 2021-04-08 02:58
> Another report, says they've been experiencing this for 6+ mos in 3867441-zen

Disconnecting and reconnecting has not worked in the cases I've seen thus far. Though in the instance above, the user said "I tried it on my phone and it did connect, so maybe it is mainly a problem on my laptop or google chrome"

I thought I'd add that note here.

**Comment by kingsleyinfo** [comment] 2021-04-08 17:25
Similar issue here 28892683-hc, follow up ticket here 3891726-zen 
user is getting this for Twitter when they try to connect a new Twitter account. 

Asking them to try these steps as a workaround: https://wordpress.com/support/publicize/#reconnecting-services

Hopefully, it works for them.

**Comment by marianearchimbaud** [comment] 2021-04-15 20:44
Hi!!

I found a similar issue.

This site was having troubles with Facebook and LinkedIn connections.

I disabled both of them and set the connection again. It worked for Facebook but not for LinkedIn.
I am following-up with the user here: 3911669-zd

**Comment by isocialtish** [comment] 2021-04-16 05:05
I have a report of the same error of "Invalid/missing request nonce." with a Facebook connection

Follow up ticket: 3895799-zen

**Comment by thebud15** [comment] 2021-04-20 21:17
@ebinnion @obenland Just wanted to check if we had some updates on how this is coming together.

**Comment by ebinnion** [comment] 2021-04-22 19:20
At the moment, we're still in the same spot. That being said, @cbauerman is going to be taking a pass at this shortly.

**Comment by inaikem** [comment] 2021-04-26 05:14
Nudging here as `3911669-zen` came back into play. Thanks!

**Comment by cbauerman** [comment] 2021-04-28 21:16
Hey all, I just pushed a change ( D60745-code ) which [addresses the issue Eric reproduced above](https://github.com/Automattic/wp-calypso/issues/46802#issuecomment-811585182). Reconnecting via Calypso should now work if the underlying connection was successful.

However, there are likely more issues, so I will be digging into some of the individual reports and seeing if the fix helped.

**Comment by goblinartificer** [comment] 2021-04-28 23:48
quick note just so it's recorded - also in 3834189-zen

**Comment by daria2303** [comment] 2021-05-17 11:05
Another one: 29630943-HC

LinkedIn connection broke down and now when trying to connect it gives popup with "Invalid/missing request nonce."

**Comment by cbauerman** [comment] 2021-05-17 21:50
> Another one: 29630943-HC
> 
> LinkedIn connection broke down and now when trying to connect it gives popup with "Invalid/missing request nonce."

This seems to be unrelated to the specific linkedin issue and more of a larger issues with connections from this blog, which I am investigating.

**Comment by cbauerman** [comment] 2021-05-24 21:17
So, I did some digging into the "Invalid/missing request nonce." and discovered that, unfortunately, due to the way Support Sessions work you will **always** get that as an error when in a session as a user. Basically the request is made unauthenticated, and the nonce provided from Calypso will not work since it was created for a user. This is unideal for us, since it blocks debugging these issues as a user so I will be looking to see if there is an "easy win" that could fix it.

**Comment by metabreakr** [comment] 2022-01-25 20:40
Another report here: https://twitter.com/douglaskarr/status/1486049605498417152

**Comment by youbrokesomething** [comment] 2022-09-20 17:38
I can't reproduce this issue at the moment, and it looks like there haven't been user reports since Jan 2022, so I'm going to close this for now. Please reopen if we get any new reports.

**Closed by youbrokesomething** 2022-09-20 17:38 UTC
Labels: [Type] Bug, Jetpack, [Pri] Normal, Publicize, User Report
