### ISSUE TITLE
Theme Showcase: Trending tab loads empty state "no themes sound" before loading themes

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#54807] opened 2021-07-22 17:29 UTC
Potentially due to my Calypso loading slower for my Automattician user account but stubbing out this issue:

### Steps to reproduce the behavior

1. Create a fresh site
2. Click on Trending in Themes
3. See an empty state component before themes load

Note: If it can't be repro'd I can provide a video.

**Comment by blackjackkent** [comment] 2021-07-28 19:53
Closing as dupe of #54821

**Closed as completed** 2021-07-29 21:14 UTC
Labels: Bug, [Pri] Normal, [Size] XS, [Pod] Design Selection
