### ISSUE TITLE
'Edit template' in Post/Page editor loads template editor with limited height

### ISSUE THREAD

**Issue by wiesenhauss** [Automattic/wp-calypso#70668] opened 2022-12-01 21:30 UTC
### Quick summary

When trying to edit a template while in the post/page editor, the template editor is not loaded with a 100% height, even though the iframe is height: 100%

<img width="2680" alt="Screenshot 2022-12-01 at 18 16 38" src="https://user-images.githubusercontent.com/99455043/205160919-dfbb0539-3707-4f77-a194-739b9d29edbc.png">

Video:

https://user-images.githubusercontent.com/99455043/205162942-048ffff5-3128-4dae-bd17-29788a2db5cf.mov

### Steps to reproduce

1. Activate any FSE theme
2. Create a post or page and edit it
3. In the Settings panel, go to Post (or Page) > Click on the template name > Click on 'Edit template'
4. Template iframe is loaded with limited visibility (not 100% height)

### What you expected to happen

The template being edited should be displayed with a height=100%

### What actually happened

Only part of the template is visible (apparent height ≠ 100%)

### Context

Tested on client site, wpcom test site (5757641-zen), and self-hosted site. Doesn't seem to affect self-hosted sites.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Users can still edit templates in the Site Editor.

**Comment by jamiepalatnik** [comment] 2022-12-02 22:46
Another report in this chat: 38434079-hc

Adding some triage notes as well. 

📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated
- Tested on Self-hosted - Could Not Replicate
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I am able to replicate this on my simple and Atomic test site. 
- A workaround is to access the Site Editor from Appearance > Editor instead of from the page editor.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by jordesign** [comment] 2022-12-05 23:33
Another interaction here: 35989821-hc

It strikes me that this is pretty far reaching, even though we don't have many reports.

**Comment by jamiepalatnik** [comment] 2022-12-09 18:53
Closing this issue as a duplicate of https://github.com/Automattic/wp-calypso/issues/70864

**Closed as completed by jamiepalatnik** 2022-12-09 18:53 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Simple, [Platform] Atomic
