### ISSUE TITLE
Unresponsive Scroll on Mobile for Site Editor Quick Start Videos

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#82376] opened 2023-09-29 03:06 UTC
### Quick summary

The view that pops up when you click start learning can't be scrolled on android (Firefox & chrome)

![Screenshot(14)](https://github.com/Automattic/wp-calypso/assets/811776/c0685cf9-d3fd-4dba-a7d6-ac338034dbfa)

### Steps to reproduce

1. Visit `/home/<your-site>?courseSlug=site-editor-quick-start`, or Go to My Home ->
Click "Start learning" and view on mobile. 
2. Try to scroll down/up. 
3. Observe that scrolling doesn't work on mobile devices or when emulating touch in browsers. 

### What you expected to happen

Be able to scroll with touch in the learning area.

### What actually happened

Can't scroll while using a mobile phone.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

You can replicate on desktop using touch mode, scrolling works with mouse wheel but not click ("touch") and drag

Seems to depend where you touch:

https://github.com/Automattic/wp-calypso/assets/811776/5d0cede0-49be-4d08-9cbc-de62ca0e3404

**Comment by lsl** [comment] 2023-09-29 03:13
cc @Automattic/lego, looks related to https://github.com/Automattic/wp-calypso/pull/70224

**Comment by karenroldan** [comment] 2023-09-29 15:37
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated** 
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to replicate the scrolling issue on mobile view. 

https://github.com/Automattic/wp-calypso/assets/67279475/189434c9-e2ca-47ba-9030-d1c77497ead0

It looks like scrolling becomes possible when directly touching or focusing on the paragraph elements. 


https://github.com/Automattic/wp-calypso/assets/67279475/26d3bd5d-b652-4fca-bece-bb87e404c94b





📌 ACTIONS
- Assigned to @Automattic/lego 
- Updated title and steps to reproduce

**Comment by davemart-in** [comment] 2024-10-16 17:31
We're deprecating My Home and moving everything over to wp-admin dashboard widgets. See pekYwv-4JJ-p2. Closing this issue out since it will no longer exist shortly.

**Closed as completed by davemart-in** 2024-10-16 17:31 UTC
Labels: Bug, [Pri] Low, [Feature Group] Support, [Feature] My Home, Triaged, [Product] WordPress.com
