### ISSUE TITLE
Older notifications don't show up under the bell

### ISSUE THREAD

**Issue by etucker** [Automattic/wp-calypso#49084] opened 2021-01-20 18:51 UTC
# Older notifications don't show up under the bell

#### Steps to reproduce the behavior

1. Go to any-p2.wordpress.com
2. Click on the bell icon to view your notifications, then "comments" or "all" tabs
3. I'm noticing that entries only go back about a day.

#### What I expected to happen

As folks use this feature to stay on top of unread content, especially with P2s in a business sense, they would expect they are shown more than a day's worth of notifications. For example, I was AFK for a holiday on Monday and missed notifications where people replied to me or mentioned me, as I was relying on this system to stay up to date.

### Browser / OS version

This is likely a backend issue, as it happens in Chrome on a Mac as well as in the iOS mobile app.

**Comment by kriskarkoski** [comment] 2021-02-04 19:32
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/48597

**Closed as completed by kriskarkoski** 2021-02-04 19:32 UTC
Labels: Bug, [Feature] Notifications
