### ISSUE TITLE
Munchies Theme :: Mobile child menu/nested items looks like parent

### ISSUE THREAD

**Issue by mdtanjid0** [Automattic/wp-calypso#75549] opened 2023-04-11 12:16 UTC
### Quick summary

[Munchies Theme](https://wordpress.com/theme/munchies/t)'s dropdown menu looks like normal menu items on small devices. 

### Steps to reproduce

1. Install Munchies Theme
2. Create a menu with submenu items. 
3. And check them on small devices ( under 600px ). 

### What you expected to happen

It should show as dropdown/child items on small devices too. 

### What actually happened

It shows 
![Screen Shot on 2023-04-11 at 18:11:01](https://user-images.githubusercontent.com/54123436/231159211-4aa52837-ab2f-4caf-8241-1ea0af8b3e1e.png)
parent menu items. 
![Screen Shot on 2023-04-11 at 18:10:19](https://user-images.githubusercontent.com/54123436/231159164-e0c802f0-2385-4ff0-a874-db7b7b9e5e5a.png)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

Ticket: #6133315-zen 

And I have shared this CSS code as a workaround: 

```
/* Adjust mobile menu submenu items | ( 6133315-zen ) MT */
@media ( max-width: 600px){
    .wp-block-template-part .wp-block-navigation__container li.wp-block-navigation-submenu ul {
        margin-left: 65px;
    }
    /* Child items font size */
    .wp-block-template-part .wp-block-navigation__container li.wp-block-navigation-submenu ul li a {
        font-size: 20px;
    }
    .wp-block-template-part .wp-block-navigation-submenu button {
        display: block !important;
        position: relative;
    }
    .wp-block-template-part .wp-block-navigation-submenu button svg {
        position: absolute !important;
        left: 45px;
        top: -25px;
    }

}
```

**Comment by cuemarie** [comment] 2023-04-11 18:44
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- Based on my testing, this issue does not seem specific to the Munchies theme; it seems this reflects a larger issue with how submenus, when justified center, appear in the overlay menu. 
- For example, I can replicate the same issue in Twenty Twenty-Three and Blank Canvas on various test sites.
- I've opened a new report for the larger issue instead, linked below.

📌 ACTIONS
- Closed as duplicate of issue https://github.com/Automattic/wp-calypso/issues/75576

**Closed as completed by cuemarie** 2023-04-11 18:44 UTC
Labels: Bug, [Pri] Low
