### ISSUE TITLE
Blank Canvas 3: Unpublished Posts and Pages use Index template on Simple Sites using custom domains

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#76660] opened 2023-05-08 09:32 UTC
### Quick summary

On draft pages and posts, they are default to "Index template" which caused wide and full width alignment to be unavailable.

Seems to be affecting only Simple sites.

Workaround:

Publish pages and posts first, then edit width on blocks

### Steps to reproduce

1. Create a new draft page or post
2. Insert either an image, gallery, cover, or column block (where wide width and full width options are available on block toolbar)
3. Attempt to change width alignment on blocks

### What you expected to happen

Blocks can change widths on draft pages and posts.

### What actually happened

Blocks missing options to change into wide and full widths on draft pages and posts.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/34882260/236789413-70cd99e3-b2ea-41a5-af8b-7e64b602b630.png">

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Gutenberg: v15.7.0
Editing Toolkit: 3.64678
WP AMP: 2.0.5
CoBlocks: 2.18.1-simple-rev.4

**Comment by cuemarie** [comment] 2023-05-09 21:09
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I think the issue here is that Simple Sites on **Blank Canvas 3** are defaulting pages & posts to the Index template, instead of their normal default templates. After publishing, the content reverts to it's correct default:
     - Posts to `Single`, and Pages to`Page`.
- Similar to this other issue impacting FSE sites: https://github.com/Automattic/wp-calypso/issues/76440

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/e522956b-4f09-4758-9d75-9cc4f2b9b2fd

📌 ACTIONS
- Assigned to Cylon (will need re-assignment, but hopefully the escalation link below will tell us more)

**Comment by cuemarie** [comment] 2023-05-09 21:11
Escalated here: p1683666696966989-slack-C02FMH4G8

**Comment by ariel-maidana** [comment] 2023-05-15 10:41
6245732-zd-woothemes
Please let the user know once the issue is solved.

**Comment by cuemarie** [comment] 2023-05-16 19:44
Further testing today suggests this is specific to **Simple Sites with Custom Domains set as Primary**:

https://github.com/Automattic/wp-calypso/assets/27249804/511c0895-cd23-4a6f-860e-7c8475938cf0

With that in mind, this seems to be the same issue as https://github.com/Automattic/wp-calypso/issues/76440 , just with slightly different results for this specific theme (using the Index template instead of the 404 template).

In both cases, the correct template is still applied once the post/page is published.

Leaving this open for now to track issues; please check the escalation thread for updates: p1683666696966989-slack-C02FMH4G8

**Comment by cuemarie** [comment] 2023-06-14 22:42
Tested today on Simple Site with custom domain, and the problem no longer presents:

Gutenberg: v16.0.0-rc.5

https://github.com/Automattic/wp-calypso/assets/27249804/4f298dbc-6eda-4b5b-b4bc-4a7c60a8576c

📌 ACTIONS
- Closing as resolved

**Closed as completed by cuemarie** 2023-06-14 22:42 UTC
Labels: Bug, [Pri] Normal, Triaged, [Feature] Full Site Editor, [Platform] Simple
