### ISSUE TITLE
Not Possible Create Two Blockquotes One After The Other

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#21249] opened 2018-01-04 02:48 UTC
Recently, I have been working on my personal site and I needed to add a few quotes one after the other, but at the same time I did not want them to blend into one blockquote. 

I have added them to the editor as two sentences and first applied the blockquote to the first sentence and after to the second. The two sentence ended up within one blockquote instead of two separate blockquotes.

#### Steps to reproduce
1. Add at least two sentences to your editor on two lines one after the other: https://cloudup.com/chkqyfd16y4
2. Apply the blockquote option in the editor to the first sentence: https://cloudup.com/cshwqr6PcPX
3. Apply the blockquote option to the second sentence: https://cloudup.com/c6RFdaz6w5N

#### What I expected

Two different blockquotes like this: https://cloudup.com/cFPQg5ghfw1

#### What happened instead

Two sentences blended in one blockquote: https://cloudup.com/cX0SdtxTv5Q

Additional information:

The code for the quote when you apply it to the second sentence seems to include the second sentence in the blockquote instead of creating a new blockquote: https://cloudup.com/cZJSUZsd9gR

Screencast: https://cloudup.com/crG3UL3-MOm

I have tested in wp-admin and the issue seems to be occurring there as well. 

The workaround I was using is to manually edit HTML to have two separate blockquotes.

**Comment by rachelmcr** [comment] 2018-01-04 17:04
Thanks for this report!

>I have tested in wp-admin and the issue seems to be occurring there as well.

I checked on a self-hosted WP site in WP Admin and confirmed that the issue occurs there, also. This indicates that it's a core issue with TinyMCE, rather than something specific to WordPress.com or Calypso.

I also tested in Gutenberg and the two quote blocks remain separate there. Since we'll be replacing TinyMCE with Gutenberg, I'm going to go ahead and close this issue as the problem will be resolved once Gutenberg launches.

**Closed by rachelmcr** 2018-01-04 17:04 UTC
Labels: Editor
