### ISSUE TITLE
FSE: Stuck on step 4 of the on boarding flow. 

### ISSUE THREAD

**Issue by huguesvincent** [Automattic/wp-calypso#36991] opened 2019-10-23 12:42 UTC
#### Steps to reproduce
1. Start an incognito session.
2. Navigate to https://horizon.wordpress.com/start/test-fse.
3. Select the business vertical and go through the onboarding steps.
4. On step 4, type a name for your site. 

#### What I expected
To complete the onboarding flow until the end.

#### What happened instead
 I got stuck on Step 4 where I input the name of my site. With "Continue" button not sending me to the next page in the onboarding flow.  

#### Browser / OS version
Chrome / MacOS 10.13.6

#### Screenshot / Video

<img width="808" alt="Screen Shot 2019-10-23 at 14 32 02" src="https://user-images.githubusercontent.com/10820560/67393680-24f4ad00-f5a3-11e9-95e6-7e3f7edf1f5f.png">

#### Context / Source
I was signing up with user huguesfsetest. I restarted on Wordpress.com/start without any issue.

**Comment by vindl** [comment] 2019-10-31 01:01
@huguesvincent I'm not able to reproduce this problem and I've likely tested this flow hundreds of times by now. :) Did you capture the output of the console log by any change since that might be helpful for further investigation?

Also, I think it's unlikely that this is related to FSE. It looks like something that onboarding folks might know more about. /cc @Automattic/zelda

**Comment by p-jackson** [comment] 2019-10-31 01:35
Also unable to reproduce, tried FF, Chrome, English, French. Any other tabs open in the incognito session? Not sure what recent change could have caused this.

**Comment by vindl** [comment] 2019-10-31 10:30
Also was you API sandboxed while doing this by any chance?

**Comment by huguesvincent** [comment] 2019-10-31 10:33
I wasn't able to reproduced either today in testing the flow again.
Not sure about being API sandboxed. That might be it.
Sorry for the hassle.

**Comment by vindl** [comment] 2019-10-31 20:33
I'm going to close this for now, but feel free to reopen it if it pops up again.

**Closed by vindl** 2019-10-31 20:33 UTC
Labels: [Goal] Full Site Editing
