### ISSUE TITLE
Sourced Images from Google Drive is not working

### ISSUE THREAD

**Issue by cherwinjayo** [Automattic/wp-calypso#86571] opened 2024-01-18 06:41 UTC
### Quick summary

One issue from a user, their sourced images from Google Drive seemed to stop working a few days ago. Links from Google Drive generated with URLs like https://drive.google.com/uc?id=FILEID are not working and even using the original link https://drive.usercontent.google.com/download?id=FILEID doesn't work.

### Steps to reproduce

1. Create a new Image Block
2. Add the URL from Google Drive

### What you expected to happen

You should see the images loading

### What actually happened

It shows a blank image (screenshot from my test site)
![image](https://github.com/Automattic/wp-calypso/assets/61383447/e3442841-4de5-4d26-84cb-422aa9d653fe)

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

**Comment by code-PA-32** [comment] 2024-01-19 15:16
This should help you)
`https://drive.google.com/thumbnail?id=FILEID&sz=w1000`

**Comment by rickmgithub** [comment] 2024-01-22 09:58
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple/Atomic – Replicated / Could Not Replicate / Uncertain 

## 📌 OTHER REPORTS ##
- Multiple users are also reporting this here - https://wordpress.com/forums/topic/google-drive-direct-link-images-not-loading/

## 📌 ACTIONS ##
Triaged

**Comment by lsl** [comment] 2024-08-05 04:23
Google has blocked hotlinking, see:
- https://issuetracker.google.com/issues/319531488#comment175
- https://workspaceupdates.googleblog.com/2023/10/upcoming-changes-to-third-party-cookies-in-google-drive.html
- https://justin.poehnelt.com/posts/google-drive-embed-images-403/

It doesn't look like there is a good way to embed Google drive media files directly, they need to be embeded with an iframe which has some drawbacks.

Going by the support documentation https://wordpress.com/support/wordpress-editor/blocks/embed-block/#images, and core's https://wordpress.org/documentation/category/embed-blocks/, I don't think we ever intended to support this.

Closing for now as I believe this only effects a small handful of users going by the support forum post. The user in the zendesk ticket has also moved their images over to imgur embeds.

**Closed as not planned by lsl** 2024-08-05 04:23 UTC
Labels: Bug, [Pri] High, Triaged, Customer report [LEGACY], [Platform] Simple, [Status] Priority Review Triggered
