### ISSUE TITLE
Issue displaying posts in IE 11

### ISSUE THREAD

**Issue by markryall** [Automattic/wp-calypso#10716] opened 2017-01-17 22:39 UTC
#### What I expected

Retrieving posts for https://wordpress.com/posts/my/<site> and also the reader for a specific user account on IE 11 does not succeed.

#### What happened instead

The results placeholder remains instead and posts are never displayed

The console logs displayed the following for two subsequent attempts:

![capture_720](https://cloud.githubusercontent.com/assets/1926/22044285/fcdd9ad0-dd67-11e6-8653-294d86e354f3.png)

![capture2_720](https://cloud.githubusercontent.com/assets/1926/22044287/01d893b4-dd68-11e6-9488-da5fe9e41073.png)

#### Browser / OS version

This was reproduced on Windows 7 and Internet Explorer 11.  This account does not exhibit the same issue in other browsers.

#### Context / Source

This issue was been reported for a specific WordPress.com account in 2992695-t.

**Comment by lancewillett** [comment] 2017-01-17 23:34
A few more notes to shed light on this.

The websocket connection failure in console might be a good clue.

<img width="1138" alt="screen shot 2017-01-17 at 16 22 05" src="https://cloud.githubusercontent.com/assets/66797/22044401/d395b4dc-dcd1-11e6-9c76-b53e41360946.png">

(Extremely fuzzy screenshot, but it shows the empty loading page in IE 11.)

It seems to be something specific to this user account — the report came from a WP.com site owner with multiple user accounts, and it's specific to this user account in IE 11.

**Comment by rachelmcr** [comment] 2017-11-27 15:51
#bug-scrub

Given that this was observed in a single account and browser, and we haven't received any additional reports of the same issue or been able to reproduce it in another account, I'm going to close this issue for now.

**Closed by rachelmcr** 2017-11-27 15:51 UTC
Labels: Posts, [Type] Bug

**Comment by ChrissiePollock** [comment] 2018-01-09 18:26
User in #886170-t has a similar issue. We were able to replicate using IE 11 version 11.192.16299.0. Attached is a screenshot of our replication.
![image 6](https://user-images.githubusercontent.com/2545184/34736363-ad38d7aa-f540-11e7-9422-40f2469bdecb.png)
