### ISSUE TITLE
VideoPress: Unable to upload videos to VideoPress on eCommerce plan

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#37745] opened 2019-11-20 02:13 UTC
#### Steps to reproduce
* On a WordPress.com hosted site with an eCommerce plan, make sure the VideoPress module is active and upload a new video file to the Media library in Calypso.
  * The setting for VideoPress in Calypso is in `Manage > Settings > Performance (tab) > 
Enable fast, ad-free video hosting`

#### What I expected

* For the video to be uploaded to VideoPress.

#### What happened instead

* The video is uploaded locally to the site and not processed by VideoPress.
* The same video file uploads just fine to VideoPress on a Business plan site.

#### Context / Source
p58i-84r-p2
p9F6qB-4oo-p2

**Comment by eoinsav** [comment] 2020-03-01 00:25
I spent a while trying to get this working for a user today. Their videos are displaying as links on WooCommerce Product pages because we can't get a VideoPress shortcode for their video.

#19054737-hc
#2754335-zen

**Comment by lancewillett** [comment] 2020-03-02 17:25
Thanks for raising this again. CC @Automattic/serenity

**Comment by gwwar** [comment] 2020-03-02 19:36
cc also @pmcpinto for awareness

**Comment by gwwar** [comment] 2020-03-02 21:20
For folks that take this, some more debugging information is available in p58i-84r-p2 courtesy of @timmyc ✨

**Comment by davipontesblog** [comment] 2020-03-13 15:40
Moved to WordPress.com Ecommerce Plan project for triaging.

**Comment by Robertght** [comment] 2020-08-04 05:16
found another case here: #3194410-zen

And I can confirm this is still happening on my test site.

**Comment by Robertght** [comment] 2020-08-04 08:06
Another user reached us in #23118693-hc

@gwwar is there a way to prioritize this in the near future? :) Thanks!

**Comment by kriskorn** [comment] 2020-08-08 12:39
Another case here: 23226968-hc

**Comment by mlaetitia** [comment] 2020-08-10 09:54
FYI, a customer just left cause this is not working and we're not fixing it... 23261865-hc

**Comment by JoshuaGoode** [comment] 2020-10-06 18:40
Added to Dotcom Manage inbox to see if we can get some eyes on this.

Edit: oops, I see it was added and removed from Dotocom Manage before :|

**Comment by mreishus** [comment] 2020-10-12 22:25
* Difficulties Debugging

I suspect one reason this issue has been difficult to solve is because there's no atomic development environment.  I see the excellent debugging log here: p58i-84r-p2 . To continue down this path, I'd need to ability to sandbox an atomic site and add one-off logging, and/or to make my atomic site used a sandboxed public-api.  As far as I know, both are impossible.

* Likely not an issue: Bundles containing different products

I compared the yearly business bundle with the yearly ecommerce bundle.  I was looking for a product that business contained, but ecommerce was missing.  I don't feel comfortable posting the specifics here, but the only products I found included in business but not ecommerce are related to domain registration, so likely not a case.

* Videopress overridden to be inactive on ecommerce... somewhere.

I created new business and ecommerce sites, then visited /wp-admin/admin.php?page=jetpack#/performance and looked in the redux debugger.  The `JETPACK_SET_INITIAL_STATE` action that's fired indicates that videopress is disabled on the ecommerce site only.  Currently not sure where this is coming from.

![2020-10-12_17-07](https://user-images.githubusercontent.com/937354/95795429-eecaa480-0caf-11eb-93ca-1a71b9db5a3b.png)

![2020-10-12_17-08](https://user-images.githubusercontent.com/937354/95795438-f2f6c200-0caf-11eb-9580-bab64ddf6791.png)

**Comment by cpapazoglou** [comment] 2020-10-14 09:54
It seems that when (2017) that functions was introduced we didn't have ecommerce plans
D4898-code
and when we introduced ecommnerce plans (2018) we didn't update this function. So 🚢  it!

**Comment by mreishus** [comment] 2020-10-14 14:08
Fix has been pushed to prod!

**Closed by mreishus** 2020-10-14 14:08 UTC
Labels: VideoPress, [Pri] Normal, [Type] Bug, eCommerce Plan
