### ISSUE TITLE
Jetpack free plan sometimes not showing for some reason

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#65821] opened 2022-07-21 06:24 UTC
### Objective

If everything looks fine and I get to the Jetpack plan selection page, for some reason I can’t see the Jetpack free plan, so I assume that’s something already picked. If I head back to my self-hosted website, I can’t see anything listed in “My Plans” but if you go to the plans page you can see Jetpack Free plan as an option. See pcmemI-KN-p2#jetpack-free-plan-confusion for videos.

### Approach
Look into the logic behind the Jetpack Free plan appearance and fix it.

**Comment by ouikhuan** [comment] 2022-08-16 06:54
If your self-hosted site is connected to WordPress.com without the user approval, it'll still be considered as connected and redirects you to the `jetpack/connect/plans` page. Once you're on the `/plans` page, we won't be able to get the site information via `sites` state because it's not connected to your user account yet, so it'll be redirected to `jetpack/connect/store`.  And here's the place you'll see the missing free plan. 

When checking to see if we want to show a free plan or not, it'll return false because it's not a jetpack cloud page and that's the reason we're not seeing the Jetpack Free plan here.

**Comment by retnonindya** [comment] 2024-08-28 02:29
I'm triaging this issue, and it seems like the issue is no longer relevant now that we have updated our site migration flow.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

**Closed as completed by retnonindya** 2024-08-28 02:29 UTC
Labels: Bug, [Pri] Low, [Feature] Site Migration
