### ISSUE TITLE
Heading that is made a link doesn't respect styles

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#73012] opened 2023-02-06 16:25 UTC
### Quick summary

Heading that is made a link doesn't respect styles
https://user-images.githubusercontent.com/11535091/217026320-69858dc1-3609-4cb5-aa10-c3a3279bb71f.mov

### Steps to reproduce

1. Add Heading
2. Link it
3. Try to change size (sometimes it happens also with font family)

### What you expected to happen

Size is changed

### What actually happened

Size is set to the one set it Global Styles > Links but if we want to keep it as a heading and edit the style individually it is not possible. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Logs or notes

5932564-zd-woothemes

**Comment by cuemarie** [comment] 2023-03-21 21:02
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/64596

Will shrae the user report noted above on the open issue. Thanks!

**Closed as completed by cuemarie** 2023-03-21 21:02 UTC
Labels: Bug, [Pri] Normal, Triaged, [Feature] Global Styles
