### ISSUE TITLE
Pinterest Embeds Broken

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#13671] opened 2017-05-04 17:39 UTC
#### Steps to reproduce
1. Starting in the Editor: https://wordpress.com/post/ (choose any public site)
2. Paste or type a pinterest.com URL into the Editor

#### What I expected

The URL to turn into an embed, as described in our support docs: https://en.support.wordpress.com/embed-from-pinterest/

#### What happened instead

The URL disappears with no feedback.

#### Screenshot / Video

https://cloudup.com/c4zswLo0-m4

Note that the embeds are also missing from the support doc (bottom of page): https://en.support.wordpress.com/embed-from-pinterest/

**Comment by rachelmcr** [comment] 2018-01-02 22:59
Closing as I can't reproduce the issue at this point.

#bug-scrub #pre-gutenburg-bug-purge

**Comment by alisterscott** [comment] 2018-05-01 07:32
@zyousafi the site you mentioned is set to private and our support docs state:

> Note: Pinterest embeds will not display whenever your blog is marked as Private.
> Note: Pinterest links must have the .com extension. Links with .com.au, for example, will not load.

I tried some embeds on a non-private site and they were working for me - can you please re-test?

**Comment by alisterscott** [comment] 2018-05-01 07:34
Oh, I just saw: 

> and the site was Public at the time

🤔

**Comment by alisterscott** [comment] 2018-05-01 07:36
@zyousafi example post on public site with the pin mentioned embedded: https://eatkibbeling5.wordpress.com/2018/05/01/pin/

**Comment by zyousafi** [comment] 2018-05-01 07:36
Yes, I just made the site **Public** again and tested with the [](https://www.pinterest.com/pin/ATJh0b9ud3jQbXfOBBl8IPKNlY4GlU42NOH7CNgLT02-v7GHOcm45rc/) link and it's still not working for me.

Also, if you look at the support doc here: [](https://en.support.wordpress.com/embed-from-pinterest/), the embeds are missing there as well.

**Comment by zyousafi** [comment] 2018-05-01 07:37
Here's what I see on that site: http://cld.wthms.co/9JhUI0

**Comment by alisterscott** [comment] 2018-05-01 07:38
> Also, if you look at the support doc here: , the embeds are missing there as well.

@zyousafi I can see them, could you test another browser and/or disable add-ons like ad-blocking?

<img width="778" alt="screen shot 2018-05-01 at 5 37 04 pm" src="https://user-images.githubusercontent.com/128826/39465370-6581452c-4d66-11e8-8ca4-baac81184a02.png">

**Comment by alisterscott** [comment] 2018-05-01 07:38
> Here's what I see on that site: http://cld.wthms.co/9JhUI0

Definitely something up with your browser - check your add ons please

**Comment by zyousafi** [comment] 2018-05-01 07:40
Okay, I've disabled Ad Block Plus and that did the trick.  I can now see the embed: http://cld.wthms.co/FDJ6AH

I'm guessing the user must have had some kind of ad blocker on their site as well.  I will let them know.  Thank you for the prompt response here! :)

**Comment by alisterscott** [comment] 2018-05-01 07:41
No worries, closing as not reproducible

**Closed by alisterscott** 2018-05-01 07:41 UTC
Labels: Editor, [Type] Bug
