### ISSUE TITLE
Simple Sites: Some patterns only appears  in the list view as pattern placeholder

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#87770] opened 2024-02-22 12:06 UTC
### Quick summary

This only happens on simple sites, but I couldn't narrow it down when this issue occurs. It's strange, but some patterns only appear in the list view as pattern placeholders. And the patterns won't be rendered in the editor. 

For example, this is a not-yet-launched theme, Low Fi's demo site.
![Screenshot 2024-02-22 at 11 47 25](https://github.com/Automattic/wp-calypso/assets/908665/de62e38d-8052-4c4b-9809-051c5c1c3b7b)

This is an already-launched theme, Bedrock's demo site. All the templates in Bedrock are full-page patterns.
![Screenshot 2024-02-22 at 11 50 15](https://github.com/Automattic/wp-calypso/assets/908665/1ffdfb1c-dd4f-405e-b613-221a6101839e)

But this is not happening on all themes/patterns. For example, with the Cakely theme, the patterns appear as expected.
![Screenshot 2024-02-22 at 11 52 46](https://github.com/Automattic/wp-calypso/assets/908665/8be95219-9771-48d1-9dd9-8da5e2910071)

@kathrynwp has also experienced something similar with TT4 on a simple site.

Cc: @dsas, as we briefly looked into this together.

### Steps to reproduce

1. Open a simple site and activate the Bedrock theme. (I don't believe this is a theme-specific issue though)
2. Open the site editor.
3. Open one of the templates and open the list view.
4. Notice the site editor not rendering anything.

### What you expected to happen

Patterns show up as they do on Atomic and self-hosted sites.

### What actually happened

The pattern only appears in the list view as a pattern placeholder.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by iamtakashi** [comment] 2024-02-22 18:17
Another new theme, Feelin' Good seems fine.

![Screenshot 2024-02-22 at 18 09 13](https://github.com/Automattic/wp-calypso/assets/908665/a80090de-4ca0-49eb-9544-553f06953d08)

@dsas had a good clue about the cause—nested patterns. Low Fi and Bedrock both have nested patterns, whereas Cakely and Feelin' Good don't.

**Comment by dsas** [comment] 2024-02-23 11:26
Here's a link to the slack convo: p1708533803049649-slack-C04DZ8M0GHW

@kathrynwp has also pointed out that it happens with Twenty Twenty-Four on the Blog Home template.

**Comment by liviopv** [comment] 2024-02-28 15:31
📌 REPRODUCTION RESULTS
- Tested on Simple – Uncertain
- Tested on Atomic – Could Not Replicate


📌 FINDINGS/SCREENSHOTS/VIDEO
I was only partially able to reproduce. After activating Bedrock and navigating to the Page Template, clicking the List View showed the Pattern Placeholder block (0:13 to 0:15 on the video), but that quickly changed to the correct list of blocks:

https://github.com/Automattic/wp-calypso/assets/14153300/c3076a2f-1dc8-405c-9a4b-7ffbad1e5c33

📌 ACTIONS
- Triaged

📌 Message to Author
@iamtakashi Marking this as triaged considering the semi-consistent way to repro in Bedrock and @dsas's investigation so far. If there are any other themes you or another theme designer has worked on that could be tested, feel free to ping me or @filipanoscampos (Theme Experience PA) so we can test more.

That said, I searched for "Pattern Placeholder" in Zendesk and there haven't been any matches since 2023, when the original issue occurred, so it's safe to say it doesn't seem to have significant user impact so far.

**Comment by fushar** [comment] 2024-03-06 07:00
@liviopv & @iamtakashi: could you all try this:

- Go to Site Editor
- Click on the three-dot menu on the upper-right corner
- Click Preferences
- Click Blocks

and see if you have the Theme blocks hidden? 

<img src="https://github.com/Automattic/wp-calypso/assets/1525580/02fdd342-cfdf-48b4-98f6-e79def3b9186" width="400">

If so -- could you tick the checkbox then reload the Site Editor? In my case, it will solve the issue.

But still unsure why I have hidden blocks in the first place...

**Comment by iamtakashi** [comment] 2024-03-06 14:13
@fushar, thanks for the tip! That made them show up in the editor, but as you said, we need to find out why they get hidden in the first place.

**Comment by taipeicoder** [comment] 2024-07-01 10:33
De-escalating this issue as it seems to only affect a12s. @miksansegundo and @arthur791004 have been actively troubleshooting this issue, see pbxlJb-5Kl-p2#comment-3728 for more context.

**Comment by miksansegundo** [comment] 2024-07-01 14:23
The fix has been deployed, and this bug won't be reproducible on newly created sites. See pbxlJb-5Kl-p2#comment-3740

**Closed as completed by miksansegundo** 2024-07-01 14:23 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] High, Triaged, [Platform] Simple, [Status] Priority Review Triggered, [Feature] Free Automattic Themes
