### ISSUE TITLE
Media/Jetpack: Unable to upload MP3 to Jetpack site

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#10830] opened 2017-01-20 20:20 UTC
#### Steps to reproduce
1. Create a new post for a Jetpack-connected site
2. Attempt to add an mp3 file

#### What I expected
For the mp3 to embed in the post

#### What happened instead
The file-picker doesn't allow choosing mp3 files by default, but if you do trick it into taking the file you get an "Invalid file type" error (the same as seen [here](https://github.com/Automattic/jetpack/issues/684))

#### Browser / OS version
All (but specifically seen here in MacOS Chrome)

#### Screenshot / Video
<img width="558" alt="screen shot 2017-01-20 at 3 17 03 pm" src="https://cloud.githubusercontent.com/assets/7233112/22164063/90d3324c-df23-11e6-88c9-e8200eb633d6.png">

#### Context / Source
#manual-testing

**Comment by BandonRandon** [comment] 2017-04-20 01:21
I was able to replicate this in Firefox 52.02 Linux. One thing I noticed is that the "All Supported Types" dropdown did not show media on a Jetpack site, but did show for a WordPress.com site which supports media. 

Here's a screen shot from the Jetpack site:
![screenshot_19-04-2017-18 01 05](https://cloud.githubusercontent.com/assets/150348/25208981/e8da535e-252c-11e7-8ba9-966b6569db2e.png)

WordPress.com Business site:
![screenshot_19-04-2017-18 14 26](https://cloud.githubusercontent.com/assets/150348/25208978/e46529a2-252c-11e7-9a2f-3105e08a3fe6.png)

**Comment by starxedsteph** [comment] 2017-04-20 01:22
A user reported this on an AT site.  In testing, I reproduced the same error on both my AT test site as well as on non-AT sites connected through Jetpack on the free Jetpack plan.
When upgrading the plan, I was then able to add audio as expected.
Tested on Mac OS X on Firefox 52.0.2 and Chrome  57.0.2987

**Comment by ashercantrell** [comment] 2017-04-30 04:35
If anyone else finds this and is looking for a workaround, you can still upload audio files through the wp-admin Dashboard!

**Comment by starxedsteph** [comment] 2017-05-03 14:55
I updated the priority since this affects AT sites.

**Comment by designsimply** [comment] 2017-05-09 22:16
Thank you for testing @starxedsteph! I am removing the `[Pri] High` label because this is already in a milestone and part of an ongoing [Calypso Parity milestone](https://github.com/Automattic/wp-calypso/milestone/150) and because we don't have a good idea yet for how many users are affected. Generally, I would consider labeling anything `[Pri] High` to be something that needs immediate attention and for someone to be assigned to work on it. This issue doesn't quite fit that yet. We can re-visit `[Pri] High` again if it starts coming up more often!

**Comment by designsimply** [comment] 2017-05-09 22:17
Based on feedback from @rralian:

> Ultimately, the supported filetypes come from `/me/sites` and Calypso is just interpreting what it gets from the API. We need to make sure there's a change in Jetpack to make it support files appropriately, possibly based on the Jetpack plan.

I've moved this issue to https://github.com/Automattic/jetpack/issues/7159

**Closed by designsimply** 2017-05-09 22:17 UTC
Labels: Jetpack, Media, [Type] Bug
