### ISSUE TITLE
Selected subdomain does not match site subdomain after signup

### ISSUE THREAD

**Issue by zachspears** [Automattic/wp-calypso#67476] opened 2022-09-07 00:30 UTC
### Quick summary

When signing up for a new site, you get a recommended subdomain. After selecting a plan or starting your site the actual subdomain is something with the user's username and random numbers, and not the requested subdomain. 

Example Site: PeeyLs-2-p2
Possible related contact: 36804475-hc
_Thanks @ha-un_ 
Video:
https://user-images.githubusercontent.com/10124024/188762386-d340ce34-abd0-4def-896e-1ffc35669cd3.mov

### Steps to reproduce

1. Start a new site at https://wordpress.com/start/
2. Type in anything
3. Select the free subdomain
4. Continue to checkout and you will see it is now a different subdomain
5. Checkout
6. Even after purchase the incorrect subdomain is setup

### What you expected to happen

The subdomain chosen on the domains page should be the final subdomain. 

### What actually happened

A randomly generated subdomain based on username and random numbers is generated. 

### Context

Was testing another unrelated bug. 

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

N/A

### Browser, operating system and other notes

Tested in Chrom and Firefox.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Direct user to manually edit their subdomain.

**Comment by jamiepalatnik** [comment] 2022-09-08 15:49
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was not able to reproduce this. 
- Tested in Google Chrome and Safari.
- Tested starting with a free site and adding a paid plan during the site creation flow.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs).

📌 Message to Author
- If you are still able to replicate, feel free to reopen with more details. Thanks!

**Closed as completed by jamiepalatnik** 2022-09-08 15:49 UTC
Labels: Bug, [Pri] Normal, [Feature Group] Emails & Domains, Triaged, [Platform] Simple, [Platform] Atomic
