### ISSUE TITLE
Fullpost Refresh: Comments not showing up in some posts

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#8171] opened 2016-09-22 16:47 UTC
Sometimes, comments don't show up in some posts. This normally happens when you get to the post via Related Posts.

**Examples:**

https://wordpress.com/read/blogs/64518624/posts/2919
![vbtcbt7hhb-3000x3000](https://cloud.githubusercontent.com/assets/4924246/18757540/2db4fb9c-80a9-11e6-9f80-7bb61d91739d.png)

https://wordpress.com/read/blogs/60970621/posts/1735367
![screenshot 2016-09-22 09 26 45](https://cloud.githubusercontent.com/assets/4924246/18757574/4f9b1048-80a9-11e6-8efd-c6db87055789.png)

Reported by @gibrown /cc @blowery

**Comment by jancavan** [comment] 2016-09-23 22:21
Another example: https://wordpress.com/read/feeds/52282073/posts/1147487468

This one says 7 Comments, but none of them are displayed. However, unlike the first example, I didn't get to this via RP. I clicked on the post directly from my feed.

![screenshot 2016-09-23 15 19 12](https://cloud.githubusercontent.com/assets/4924246/18802964/1ebd5d02-81a1-11e6-8d9c-f128429b5965.png)

h/t @joanrho

**Comment by alisterscott** [comment] 2016-09-26 23:50
I saw this issue coming into [this post](https://wordpress.com/read/blogs/38180906/posts/2428) via related posts on Chrome OSX. I can't reproduce it directly accessing that post.

**Comment by alisterscott** [comment] 2016-09-26 23:53
I just clicked a related post on another post and saw this issue again [here](https://wordpress.com/read/blogs/48500948/posts/6718): no comments displayed and clicking the comments number throws a console error:

![screen shot 2016-09-27 at 9 51 51 am](https://cloud.githubusercontent.com/assets/128826/18855684/0ea9b718-8498-11e6-951a-2f37147fce66.png)

**Comment by bluefuton** [comment] 2016-09-27 22:22
When this happens, we're getting an empty commentsTree back from the Redux selector, causing the `PostCommentList` to bail out with `null`.

Can be reliably reproduced with:

http://calypso.localhost:3000/read/blogs/62450444/posts/10244

(thanks @jancavan)

**Comment by bluefuton** [comment] 2016-09-30 01:08
Looks like http://calypso.localhost:3000/read/blogs/62450444/posts/10244 may be a red herring because the API 403s when we try to retrieve replies:

<img width="593" alt="screen shot 2016-09-29 at 18 02 43" src="https://cloud.githubusercontent.com/assets/17325/18977477/66375c14-866f-11e6-8b6d-26a7eb2e2b88.png">

Potentially a Jetpack site with commenting disabled?

**Comment by bluefuton** [comment] 2016-09-30 01:09
In other news, this data.blog post definitely has a problem. There is some weirdness on the blog post itself, which displays "8 comments" but doesn't display any comments:

https://design.blog/2016/09/08/ti-chang-on-manufacturing-in-china-as-an-american-designer/#comments

...and we are actually getting back those 8 comments from the API, but we're not displaying them for some reason:

<img width="608" alt="screen shot 2016-09-29 at 18 08 45" src="https://cloud.githubusercontent.com/assets/17325/18977519/db4c5f54-866f-11e6-9d6e-d4d661b83fe5.png">

**Comment by bluefuton** [comment] 2016-09-30 01:41
After further investigating https://github.com/Automattic/wp-calypso/issues/8171#issuecomment-249316198, I notice we're receiving the comments back from the API, they're being put into Redux state, but when we pull them out with `getPostCommentsTree`, the `children` key is empty (usually it contains a list of the comment IDs). I suspect the problem is on design.blog itself, as the same symptoms are apparent on the source site.

**Comment by bluefuton** [comment] 2016-09-30 02:20
So, two red herrings I think - but the third case is a real bug!

I was able to reproduce @alisterscott's report that comments aren't loaded when browsing via Related Posts. There seems to be a React lifecycle problem here in `PostCommentList` - when the related post loads in, the comment list component is not re-mounted, so the comment request never gets kicked off. I'll work up a PR.

**Comment by bluefuton** [comment] 2016-09-30 02:21
Sidenote: the console error @alisterscott mentions in https://github.com/Automattic/wp-calypso/issues/8171#issuecomment-249730734 will be fixed separately in #7892.

**Closed** 2016-09-30 14:16 UTC
Labels: Reader, [Type] Bug
