### ISSUE TITLE
Jetpack Onboarding: do not show site type and onboarding steps for secondary users

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#33352] opened 2019-05-27 12:23 UTC
#### Steps to reproduce
1. Starting with a site that is already connected to a WordPress.com account.
2. On that site, create a brand new admin account.
3. Log out of your site, and log back in using that new account.
4. Log out of your wpcom account, and log back in with a different account.
5. In wp-admin, go to Jetpack > Dashboard and click on the banner to link your account to your wpcom account.
6. Calypso takes you through the onboarding steps although you are not the initial connection owner. 

#### What I expected

I would expect onboarding to only be an option for the Jetpack master user, not for every user that comes after them.

**Comment by simison** [comment] 2019-06-13 06:48
I'll close this as a duplicate of https://github.com/Automattic/wp-calypso/issues/31631

**Closed by simison** 2019-06-13 06:48 UTC
Labels: Checklist, Jetpack, NUX
