### ISSUE TITLE
Reduxify: signup

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#24184] opened 2018-04-14 05:06 UTC
2 stores, only used during signup.
partially reduxified which makes it difficult to figure out what is really going on.

I noticed that `themes-data` and `hint-data` are translated at the module level, so it will never be correct if someone is non-english.

- [ ] `progress-store`:
SignupProgressStore stores the user's progress through a signup flow by storing a list of the steps in the signup flow the user has submitted. Used by 3 non-test files. is ~180 LOC. can definitely be written more simply.
Seems to resume progress from cache... (offline)

- [ ] `dependency-store`:
Already reduxified. The `get()` and `reset()` functions just directly call into redux via getState or a redux dispatch. Seems to have ~10 files that depend on it. All should be easy to convert to using the redux versions.

| task-size | files      | LOC   |
| ----------- | ---------- | ---------- |
| large      | ~20 | ~350 |

**Comment by jsnmoon** [comment] 2018-06-05 20:39
Currently taking a look at the `dependency-store`.

**Comment by jsnmoon** [comment] 2018-06-06 17:22
It looks like this is actually a dupe of #6709, so I'll close this and add more context to the other issue.

**Closed by jsnmoon** 2018-06-06 17:22 UTC
Labels: Signup, [Size] L, [Type] Task
