### ISSUE TITLE
Gutenberg: Cannot center-align image on certain themes

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#28756] opened 2018-11-21 14:07 UTC
#### Steps to reproduce
1. Starting at URL: SITE_URL/wp-admin/post-new.php
2. Add an image block and add an image
3. If the image is full-width, resize it to a smaller size
4. Set alignment to Center-aligned and publish post

#### What I expected
For the image to be center-aligned in the post

#### What happened instead
The image is left-aligned. Right-aligning the image works as expected, but selecting center-alignment causes the image to display left-aligned; or more accurate non-aligned as text from a succeeding paragraph block doesn't wrap as it does if the image is set to left-aligned.

Editing the post in the classic editor also indicates the image as non-aligned.

#### Screenshot / Video

Image in the editor:
![edit_post_ _kokkiestrialtestsite_ _wordpress](https://user-images.githubusercontent.com/11873759/48845691-d8f32400-eda5-11e8-9b62-0cd7fd797995.png)

Published post:
![image_align_ _kokkiestrialtestsite](https://user-images.githubusercontent.com/11873759/48845725-eb6d5d80-eda5-11e8-9b16-830f73d7acca.png)

What I see if I edit the post in the classic editor in WP-Admin:
![edit_post_ _kokkiestrialtestsite_ _wordpress](https://user-images.githubusercontent.com/11873759/48845762-ffb15a80-eda5-11e8-97ac-0b285b6e3bd6.png)

Viewing the block in HTML mode the `class="aligncenter` is applied to the image.

I'm not able to replicate this on a self-hosted site, so it appears to be an issue specifically with WordPress.com.

#### Context / Source
User report in the [support forums](https://en.forums.wordpress.com/topic/centre-aligning-an-image/)

**Comment by KokkieH** [comment] 2018-11-21 14:11
If I set the image to centered in the classic editor and update, it's correctly centered in the published version, but if I then edit the post in Gutenberg again it gives an invalid content warning:

![edit_post_ _kokkiestrialtestsite_ _wordpress](https://user-images.githubusercontent.com/11873759/48846558-148eed80-eda8-11e8-9bd8-6b510646b08f.png)

**Comment by torres126** [comment] 2018-11-21 22:12
Automattic/themes#376

**Comment by supernovia** [comment] 2018-11-26 22:37
Another instance [here](https://en.forums.wordpress.com/topic/centering-images-4/), and few notes:

- My own Gutenberg instance centers properly
- If I copy the exact code from my Gutenberg instance to .com, it is misaligned on .com
- Old wp-admin gives the figure a width; Gutenberg isn't.  If I add a width to the figure, it centers.

**Comment by laurelfulford** [comment] 2018-11-29 22:17
I _think_ the display issues here may both be theme-related.

We've had a couple other reports, with Dara, Baskerville 2, and Manifest, where the issue is that the class `.aligncenter` has the style `display: block`, and that messes up the image block. The image block uses `display: table`, so once `display: block` overrides that, the styles that handle the centring no longer work. 

@KokkieH the user that reported the issue in that thread was using Dara, which we've fixed. Do you happen to remember the other themes you recreated this with?

@supernovia Looking at https://silverwilderness.wordpress.com/2018/11/28/romance-in-ya-is-not-realistic/, I think the issue is coming from these styles in the theme: https://github.com/Automattic/themes/blob/master/libre-2/css/blocks.css#L78-L83. I'm going to make a new issue for that, for us to investigate.

If we can confirm all the themes used for reproducing this issue include some kind of problem styles instead of them coming from WP.com, we can close this issue :) 

@vel

**Comment by KokkieH** [comment] 2018-11-30 05:11
@laurelfulford, my test site where I confirmed this is coincidentally also on Dara, so I did not think to try this on different themes.

In that case, I've had a report in the [WordPress.org forums](https://wordpress.org/support/topic/image-align-center-doesnt-work/) as well, though I wasn't able to replicate this on a self-hosted site with Dara.

**Comment by laurelfulford** [comment] 2018-12-04 17:36
Thanks @KokkieH!

> In that case, I've had a report in the WordPress.org forums as well, though I wasn't able to replicate this on a self-hosted site with Dara.

Okay, I _think_ that's a good sign (or at least a sign in favour of the problem being a theme thing). The problem code in Dara's case was added with some other Gutenberg-related styles. We've been holding off submitting those updates to WP.org, at least until 5.0 is officially released, to see if we can catch some bugs (like this!) in advance.

**Comment by thewritingking** [comment] 2018-12-19 23:30
In Wordpress 5.01, this happens to me on all my sites where I use Gutenberg. Before upgrading to 5.0, it worked fine. Buttons and images simply do not center.

**Comment by desnum** [comment] 2019-01-30 16:38
Another case, on a site with the Baskerville 2 theme:

- When the image is resized and centered in the editor, it shows as left-aligned in the frontend.
- We added display:block; to the CSS as a temporary workaround.
- hc-9976478

**Comment by spencerberry** [comment] 2019-02-14 22:24
Attache also has this issue:
https://wordpress.com/theme/attache

fixed by, but maybe not the best way to do it:
```
.aligncenter{
  text-align: center;
}
```

**Comment by automattic-ian** [comment] 2019-03-11 19:49
Also an issue in https://wordpress.com/theme/professional-business

investigating CSS workaround for now.

**Comment by torres126** [comment] 2019-03-11 20:39
@automattic-ian I'm not able to reproduce an issue with centre image alignment at any screen ratio with that theme.

![gsgfdgfdgfd](https://user-images.githubusercontent.com/43215253/54156151-8d8c8080-443d-11e9-8da8-822f90053101.png)

By any chance, are you referring to the Sophisticated Business theme? I've proposed a fix for that one at Automattic/themes#648, and it's being tracked at Automattic/themes#646.

**Comment by automattic-ian** [comment] 2019-03-11 21:04
@torres126 it appears that I may have been mistaken and that this is a separate issue, it seems to only impact image galleries, not single images, as seen here: 
![image](https://user-images.githubusercontent.com/33329175/54157886-a2f2b200-441f-11e9-89a9-9819e1fb22d2.png)

Where you can see the class .aligncenter however the gallery is still pushed to the left.

**Comment by torres126** [comment] 2019-03-11 21:42
Thanks @automattic-ian! I can reproduce, PR for that issue in Automattic/themes#660.

**Comment by katinthehatsite** [comment] 2019-03-17 11:42
Another site that was affected #1885592-zd

**Comment by mikeicode** [comment] 2019-03-17 16:52
Another on #1847494-zen with tiled galleries, I provided this CSS to resolve it:

```
.entry .entry-content > .wp-block-jetpack-tiled-gallery.aligncenter, 
.entry .entry-summary > .wp-block-jetpack-tiled-gallery.aligncenter {
	margin: 0 auto;
}
```

**Comment by torres126** [comment] 2019-03-17 18:01
@katinthehatsite @mikeicode Just out of curiosity, which theme(s)?

**Comment by mikeicode** [comment] 2019-03-17 21:14
@torres126 
> Just out of curiosity, which theme(s)?

`Professional Business`

**Comment by katinthehatsite** [comment] 2019-03-21 13:59
@torres126 For my case, it was theme Veni

**Comment by reginabally** [comment] 2019-04-26 07:33
Another issue reported in 1988165-zen for [Port theme](https://wordpress.com/theme/port].

**Comment by carinapilar** [comment] 2019-05-06 11:28
I had another report on 12365791-hc where `class="size-full wp-image-902 aligncenter"` wasn't working on the Classic Editor. I had to add a `p` tag for the center alignment to work. Site uses the Boardwalk theme.

**Comment by aleone89** [comment] 2019-06-28 07:42
Another report in HC-13689395 

Theme - Baskerville 2. 

I employed temp solution seen in GH-403

**Comment by nathalieflower** [comment] 2019-07-04 10:49
I seem to be having this issue in the October theme. from playing with the css the only way I can get images to centre is at row level and by removing the display:flex, which isn't ideal

**Comment by KokkieH** [comment] 2019-07-04 12:25
@nathalieflower I think you might be in the wrong repository. This issue is specifically regarding an issue with the block editor and some specific themes on WordPress.com, and October is not a theme offered on WordPress.com.

It would probably be best to contact support for your theme directly about this, as if it's a theme issue, a fix we apply on WordPress.com won't have any effect on your theme.

**Comment by carinapilar** [comment] 2019-10-04 20:13
Another report for the Veni theme, on 15730086-hc.

**Comment by michaelswengel** [comment] 2019-10-04 20:33
Same issue here with Sydney.

**Comment by michaelswengel** [comment] 2019-10-04 20:35
Just tested on **two** of my sites running the same versions of everything. Same issue. This needs to be fixed.

**Comment by michaelswengel** [comment] 2019-10-04 20:44
Testing further with various themes, this does appear to be a Gutenberg issue, not a theme issue. I can set an image to align right, and it does. Aligning center does nothing. Please fix this.

**Comment by Aurorum** [comment] 2019-10-04 21:32
Unless something has changed recently (which I'm pretty sure it hasn't), then this is still a theme issue that generally needs fixing in individual themes. Sydney isn't a theme available on WordPress.com though, and it's probably best to contact the developer of that theme, since any changes to WordPress.com won't have an impact on that.

**Comment by michaelswengel** [comment] 2019-10-04 21:34
As I said, I tested multiple themes. Which theme are you using without problems?
    	
    	

    	Get Outlook for iOS
    
  




On Fri, Oct 4, 2019 at 5:33 PM -0400, "Aurorum" <notifications@github.com> wrote:












Unless something has changed recently (which I'm pretty sure it hasn't), then this is still a theme issue that generally needs fixing in individual themes. Sydney isn't a theme available on WordPress.com though, and it's probably best to contact the developer of that theme, since any changes to WordPress.com won't have an impact on that.

**Comment by michaelswengel** [comment] 2019-10-04 21:35
I should also specify, this is on a self hosted installation. Two self hosted installations actually. 
    	
    	

    	Get Outlook for iOS
    
  




On Fri, Oct 4, 2019 at 5:33 PM -0400, "Aurorum" <notifications@github.com> wrote:












Unless something has changed recently (which I'm pretty sure it hasn't), then this is still a theme issue that generally needs fixing in individual themes. Sydney isn't a theme available on WordPress.com though, and it's probably best to contact the developer of that theme, since any changes to WordPress.com won't have an impact on that.

**Comment by Aurorum** [comment] 2019-10-04 21:44
I use the Harmonic theme on WordPress.com. I can test Sydney on a self-hosted site at some point tomorrow to see if I can reproduce it, but for now, virtually no theme seems to still have this issue.

**Comment by michaelswengel** [comment] 2019-10-04 22:01
@Aurorum, I don't think it's a theme issue.

I just tested with Twenty Nineteen, SmartTheme, Sydney, Twenty Fifteen, Twenty Seventeen, Twenty Sixteen, OceanWP.

It's not a theme problem.

**Comment by michaelswengel** [comment] 2019-10-04 22:17
This is the code of an image that will not center:

`<div class="wp-block-image"><figure class="aligncenter"><img src="https://listbootcamp.com/wp-content/uploads/2019/10/email-click-through-rate.png" alt="Example email CTR in GetResponse" class="wp-image-707"/><figcaption>Example email CTR in GetResponse</figcaption></figure></div>`

Now, if I add `<center></center>` tags, it centers. Gutenberg does not center.

**Comment by michaelswengel** [comment] 2019-10-04 23:57
Ok. Update. It's not a theme issue, but for my at least it was an Elementor issue. It appears Elementor is overriding Gutenberg's alignment. So I added this CSS:

`.elementor .elementor-widget .wp-block-image .aligncenter {
    margin-left: auto;
    margin-right: auto;
}`

That seems to have fixed it for me. So it looks like something Elementor needs to fix.

**Comment by carinapilar** [comment] 2020-01-04 19:23
Got another report on 2602696-zen with the Cubic theme.

**Comment by italocjs** [comment] 2020-02-27 20:43
> Ok. Update. It's not a theme issue, but for me at least it was an Elementor issue. It appears Elementor is overriding Gutenberg's alignment. So I added this CSS:
> 
> `.elementor .elementor-widget .wp-block-image .aligncenter { margin-left: auto; margin-right: auto; }`
> 
> That seems to have fixed it for me. So it looks like something Elementor needs to fix.

This has fixed for me too, add this line into "Appearance > Customize > Additional CSS"
i'm using JupiterX theme

**Comment by carinapilar** [comment] 2020-03-17 19:21
Got another report on 17773353-hc with the Didi theme, now on a Video block.

**Comment by lancewillett** [comment] 2020-03-19 17:23
I've run into this a few times on internal Automattic P2 sites; where the P2 Breathe theme existing CSS doesn't seem to correctly center the image as expected.

**Comment by ianstewart** [comment] 2020-03-19 17:56
@lancewillett I reviewed all our free themes on WP.com and found these issues …

https://github.com/Automattic/themes/issues/1856

**Comment by sourourn** [comment] 2020-04-06 18:08
Another one reported here: #15799442-hc
User has a third party theme: logpixiecassidy

When you center align an image, it looks left aligned in the editor but it does display as center align on the front end. 

![Screen Shot 2020-04-06 at 14 07 54](https://user-images.githubusercontent.com/39188945/78590646-22fc6e80-7810-11ea-89ed-d53726bcf31d.png)
![Screen Shot on 2020-04-06 at 14-07-19](https://user-images.githubusercontent.com/39188945/78590652-27288c00-7810-11ea-89c7-14251e89662f.png)

**Comment by thesacredpath** [comment] 2020-04-13 03:15
There is a related issue happening in the editor. Reported on site with Independent Publisher 2 and also with Canard. Both are simple sites.

**Steps to reproduce**

1. Starting at URL: Site > Pages > Add New
2. Add an image block and add an image
3. Set image to medium size
4. Set image for center alignment
5. Resize image larger or smaller using resize handle

**What I expect**

Image to remain center aligned in editor window and at new size

**What happened**

Image jumps to left aligned in editor, but if you preview the page or post, it will show correctly as center aligned.

Independent Publisher 2 ticket: 2867721-zen
Canard ticket: 2859492-zen

**Comment by obenland** [comment] 2021-03-01 16:47
This seems to have been fixed by https://github.com/WordPress/gutenberg/pull/21167. I couldn't reproduce it with Baskerville 2 or Dara.

Please feel free to re-open if this error re-appears or can be reliably reproduced.

**Closed by obenland** 2021-03-01 16:47 UTC
Labels: Themes, [Goal] Gutenberg, [Type] Bug

**Comment by carinapilar** [comment] 2021-03-01 19:05
> Please feel free to re-open if this error re-appears or can be reliably reproduced.

@obenland, it might be theme-related, but I can still replicate [the one I reported here](https://github.com/Automattic/wp-calypso/issues/28756#issuecomment-600253151).

With the Didi theme, create a new page using the _"Front Template"_, the issue happens with a Vimeo or Youtube block, even though it has `aligncenter`. Here's a screenshot:

![VimeoYoutubeCenterAlignmentIssue](https://user-images.githubusercontent.com/16104522/109545386-930a8780-7aa7-11eb-957f-1c8c593efcac.jpg)

**Comment by obenland** [comment] 2021-03-01 19:58
Yes, it looks to be a theme issue with that page template

**Comment by carinapilar** [comment] 2021-03-01 20:05
Thanks for checking, @obenland! I have reported on the theme's repo. 🙂
