### ISSUE TITLE
Calypso: Add a button next to pro-rated credits notice on plans page to redirect users to our documentation

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#67812] opened 2022-09-14 13:20 UTC
### What

I think it would be helpful to have a button on the pro-rated credit notice on Calypso that redirects users to our support doc where they can read more about that:

https://wordpress.com/support/manage-purchases/#pro-rated-credits

### Why

I still keep getting chats only about pro-rated credits, and I think most HEs also have those interactions regularly. Maybe a button that redirects users to the support doc with more info or displays it on the page as a pop-up would be helpful.

### How

Here is an example of what I think that could be helpful:

![Markup on 2022-09-14 at 10:04:30](https://user-images.githubusercontent.com/50875131/190165094-b5b55c93-3e2c-4124-8727-3437f9b4d930.png)

**Comment by zachspears** [comment] 2022-09-20 01:43
This is a great enhancement request! I know I have had numerous chats about users asking for clarification regarding the pro-rated credits, what they are and how to redeem them. Marking this as High priority due to a high impact.

**Comment by zdenys** [comment] 2022-12-16 13:59
It seems to be a duplicate of this one I opened some time ago since I kept getting chats about the same topic 🤷‍♂️

- https://github.com/Automattic/wp-calypso/issues/61293

**Comment by zdenys** [comment] 2023-02-23 14:41
I'm closing this in favor of https://github.com/Automattic/wp-calypso/issues/61293

**Closed as completed by zdenys** 2023-02-23 14:41 UTC
Labels: Enhancement, [Feature] Plans & Upgrades, [Pri] Normal, Triaged
