### ISSUE TITLE
Reader: longreads pullquote shortcode

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#1557] opened 2015-12-14 18:13 UTC
Longreads has a special `[pullquote]*[/pullquote]` shortcode that they leverage frequently in exclusive content. The pullquote shortcode styling is not rendered in reader (web & native mobile):

Example content: http://blog.longreads.com/2015/12/07/the-art-of-escape/
In reader: https://wordpress.com/read/post/feed/22973954/881363093

web reader:
![](https://cloudup.com/c_H9J_i6Uji+)

ios reader:
![](https://cloudup.com/iJnqy8bYout+)

cc @kjellr

**Comment by kjellr** [comment] 2015-12-14 18:22
I don't think this is really a Reader issue. We should just switch to using `blockquote` tags for these for better compatibility in RSS + email anyway. I can update in the theme itself and report back here when it's all set.

**Comment by blowery** [comment] 2015-12-14 18:23
This is also an API issue. The API is not loading the necessary shortcode handler when processing the request.

**Comment by kjellr** [comment] 2015-12-14 20:02
I've updated the Longreads theme +  notified the editors that we should switch to `blockquote` based pullquotes moving forward. I've gone ahead and updated many of our recent posts to use this instead too. These should display as expected moving forward. 

On longreads.com ( [link](http://blog.longreads.com/2015/12/07/the-art-of-escape/) ): 
<img width="856" alt="screen shot 2015-12-14 at 2 39 13 pm" src="https://cloud.githubusercontent.com/assets/1202812/11792293/592f5afc-a273-11e5-8695-1e8ca77fa1d4.png">

In web Reader ( [link](https://wordpress.com/read/post/feed/22973954/881363093) ):
<img width="853" alt="screen shot 2015-12-14 at 2 38 57 pm" src="https://cloud.githubusercontent.com/assets/1202812/11792308/74383ef4-a273-11e5-9e43-1233266e2acc.png">

iOS Reader: 
![img_0196](https://cloud.githubusercontent.com/assets/1202812/11792358/a4dbdb9c-a273-11e5-9e78-4349b8337704.PNG)

@blowery, not sure if you'd like to keep this open for the API issue or not?

**Comment by designsimply** [comment] 2015-12-14 20:27
Duplicate of https://github.com/Automattic/wp-calypso/issues/796

**Closed by designsimply** 2015-12-14 20:27 UTC
Labels: API, Reader, [Type] Bug
