### ISSUE TITLE
Focused Launch: Selecting domains in the launch modal replaces the site with [object Object]

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#47093] opened 2020-11-04 11:12 UTC
##### Prepare environment
* Make sure you have an active connection to your sandbox, and that your sandbox is clean and up to date
* In three separate terminal windows, from the root of the project, run:
  - `yarn start`
  - `cd apps/editing-toolkit && yarn dev --sync`
  - `cd apps/wpcom-block-editor && yarn dev --sync`
* Sandbox an _unlaunched_ WordPress site created via the `/start` site creation flow by adding it to your host file by going to `/start/domains`.

##### Reproduction steps:
* Visit `/page/SANDBOXED_SITE_ID_CREATED_WITH_START.wordpress.com/home?flags=create/focused-launch-flow`
* Click on "Launch" button — Focused Launch modal should appear
* Click on the "Recommended" domain below the currently selected free `.wordpress.com` domain.
* "Site Title" field will now contain `[object Object]`

#### What I expected
* The site title field value would not change after clicking the recommended domain.

#### What happened instead
* The site title field value changed to `[object Object]`

#### Browser / OS version
* Chrome & Firefox / Mac

#### Screenshot / Video
![object-Object](https://user-images.githubusercontent.com/8639742/98104609-93df3400-1e8e-11eb-8e29-4180977830de.gif)

**Comment by ciampo** [comment] 2020-11-05 18:13
Seems to be fixed in #47141

Feel free to re-open if you can reproduce this issue again after #47141 gets merged

**Closed** 2020-11-06 09:26 UTC
Labels: [Type] Bug
