### ISSUE TITLE
Editor View Is Very Different From Live Page View in Barnsbury

### ISSUE THREAD

**Issue by connorhipps** [Automattic/wp-calypso#60272] opened 2022-01-19 22:22 UTC
Updating to remove user content screenshots. This issue has been fully documented elsewhere.

**Comment by CodeAllNightNDay** [comment] 2022-01-21 00:34
Same issue here. I notice the issue happens in the Cover Block on both sites reported here. In addition to the font colors in the editor not being reflected on the live page (homepage), the fonts do not either. The theme in this instance is Redhill. 33772054-hc 4706374-zen

**Comment by formosattic** [comment] 2022-01-24 07:24
@connorhipps  @CodeAllNightNDay, thanks for the report, will close this in favor of this existing report https://github.com/Automattic/themes/issues/5181, and will add your user reports there.

**Closed as completed** 2022-01-24 12:56 UTC
Labels: Bug

**Comment by csabarakasz** [comment] 2022-02-02 10:04
I wanted to leave a comment here, that this 4706374-zd-woothemes ticket was most likely not a bug, but a custom CSS that was added by the user and we didn't know about it, until now.
