### ISSUE TITLE
Emails: Missing Image Alignment

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#46309] opened 2020-10-09 13:31 UTC
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/posts
2. Create a new post
3. Add an Image block, select an image
4. Add a paragraph block with some content
5. Set the Image block with the Right alignment
6. Publish the post and check the email you will get for it

#### What I expected
To have the email showing the image right-aligned to the text, as it shows on the site.

#### What happened instead
The image shows first, and the text below it.

#### Browser / OS version
OS X 10.15.7
Chrome 86.0.4240.75

#### Screenshot / Video
Here's how it shows on the site:

![ImageAlignmentSite](https://user-images.githubusercontent.com/16104522/95588804-42bc5b80-0a1a-11eb-9da5-265d92baf0e8.png)

And here's what we're now sending on emails to followers:

![ImageAlignmentEmail](https://user-images.githubusercontent.com/16104522/95588825-4c45c380-0a1a-11eb-9220-a66867b3ce9a.png)

#### Context / Source
User reported on 24635169-hc that this behavior changed in the last week, it was working before. They also shared screenshots showing how it was properly working before.

#user-report

**Comment by cathymcbride** [comment] 2020-10-12 19:46
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/45356. Please let me know if you think this is a different issue!

**Closed by cathymcbride** 2020-10-12 19:46 UTC

**Comment by carinapilar** [comment] 2020-10-12 20:18
It seems it's the same issue, yes. It's just odd that the user I got published a post on September 28th that it correctly loaded on the emails, while that report is from September 2nd - even with both posts, the one that worked and the one that didn't, using the Classic block, as the other GH issue mentions to be the workaround (maybe that's what the user complained about recently stopping working? It was working with the Classic block, and now it's not? - if so, maybe this is worth it adding to that other issue).
