### ISSUE TITLE
FSE Product Catalogue template: If the Post Title Block is added to the template, it shows first product name  

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#66549] opened 2022-08-13 10:47 UTC
### Quick summary

When a Post Title Block is added anywhere to the template of the Product Catalogue on a website using the  Twenty Twenty-Two theme, it shows the first product name, instead of the page title.

The post Title block in the Editor:
![Screenshot 2022-08-13 at 11 44 09](https://user-images.githubusercontent.com/2540430/184480250-52f6d1cc-0d8f-4e82-ad94-916ddd1c39b2.png)

It is displaying correctly for other pages:
![Screenshot 2022-08-13 at 11 44 38](https://user-images.githubusercontent.com/2540430/184480264-f7c21f60-51d9-4d3f-a08c-a05da2f57082.png)

Including WooCommerce pages:
![Screenshot 2022-08-13 at 11 46 09](https://user-images.githubusercontent.com/2540430/184480288-8198db65-0030-418f-b3cc-3de9442671d2.png)

But not for the shop page:
![Screenshot 2022-08-13 at 11 44 44](https://user-images.githubusercontent.com/2540430/184480298-9b46f05b-44db-44ed-8421-46f63c1a1d37.png)

### Steps to reproduce

1. Open the Product Catalogue template on the edior
2. Add a Post Title Block anywhere to that template and save your changes
3. Visit the website's shop page and notice how the Post Title Block is displaying the first product name instead.editor

### What you expected to happen

The Post Title Block to show the page title "Shop".

### What actually happened

It showed the first listed product name instead.

### Context

5473452-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

So far, I have been able to replicate this with twenty Twenty-Two and Pendant.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Adding headers to the Shop page template that specifically have the text "Shop", instead of the Post Title Block.

**Comment by jamiepalatnik** [comment] 2022-08-19 03:52
📌 SCRUBBING
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can recreate this on Atomic and self-hosted. 
- Since the issue is for an FSE template added by WooCommerce, I added the issue to the woocommerce/woocommerce-blocks repo and am closing this issue.
- I don't know how often the Post Title block is used outside of a Query Loop block, but I went ahead and transferred the report since if this block is used outside of a Query Loop block, I would expect it to work on the Product Category template the same way it does on other FSE templates. When the Post Title block is in a Query Loop block on the Product Category template, it works as expected.

📌 ACTIONS
- Transferred to woocommerce/woocommerce-blocks external repo: https://github.com/woocommerce/woocommerce/issues/42604

**Closed as completed by jamiepalatnik** 2022-08-19 03:52 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Atomic
