### ISSUE TITLE
[Block] Image: Text wrapping around aligned image block looks different in the Editor vs Live Site

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#76437] opened 2023-04-29 11:17 UTC
### Quick summary

The contents in the editor don't appear in the same layout as the preview or live page.  

### Steps to reproduce

1. Create a new post or page with texts and images. 
2. Align the images to the left and right.
3. Publish the post or page.
4. Visit the preview or live page. 

### What you expected to happen

The layout of the contents in the editor is the same as the preview and live page layout. If the live page will display the texts to the left of the image, it has to be the same in the editor. 

### What actually happened

The layout of the contents in the editor is not the same as the preview and live page layout. 

### Impact

All

### Available workarounds?

Yes, easy to implement

### Logs or notes

Firefox 112, any WordPress.com theme. 

### Editor: 

<img width="1072" alt="Screenshot 2023-04-29 at 13 15 37" src="https://user-images.githubusercontent.com/36863633/235299761-f1c9b427-33c6-48cc-b397-e6fb7f8d4dd1.png">

### Preview / Live page: 

<img width="683" alt="Screenshot 2023-04-29 at 13 14 53" src="https://user-images.githubusercontent.com/36863633/235299742-070405b0-d0cf-46b6-945f-a3f1ccbb7601.png">

User report: 6246398-zd

**Comment by CodingKite** [comment] 2023-04-29 15:06
@kspilarski 

I tried to replicate the issue described above.

But didn't find any difference between the Published Page and Preview

**Published Page with Right Aligned Image**
![Published Page with Right Aligned Image](https://user-images.githubusercontent.com/70031623/235309207-15df0565-9d50-48a3-95f0-9f37e8a3f942.png)

**Preview Page with Right Aligned Image**
![Preview Page with Right Aligned Image](https://user-images.githubusercontent.com/70031623/235309490-c9722421-616c-42bf-a31b-951edb0fd44b.png)

The same occurs with Left Aligned Images(images posted do not contain the left-aligned image).

**There might be a possibility that I couldn't replicate it properly. If the issue still persists, please share more details **

**Comment by kspilarski** [comment] 2023-04-29 15:38
Hi, thanks for trying it out. 
In the editor, add the texts below the right or left-aligned image so there's a space next to the image. If there's a space on the left or right side of the image, this should also be the same layout in the live page or preview. But what's happening is in the live page or preview, the texts below the image gets moved to the space next to the image which is not the case in the editor.

**Comment by cuemarie** [comment] 2023-05-02 17:39
> In the editor, add the texts below the right or left-aligned image so there's a space next to the image. If there's a space on the left or right side of the image, this should also be the same layout in the live page or preview. But what's happening is in the live page or preview, the texts below the image gets moved to the space next to the image which is not the case in the editor.

Hey @kspilarski ! I'm not seeing the behavior you are reporting when I try to replicate either.  As soon as an image is left/right aligned, any paragraph block I place "below" that image immediately starts wrapping around the image, which is by design.

Can you share the following details about your test environment, so I can compare our experiences?

- Theme active in your test environment when you are able to replicate the issue
- WordPress and Gutenberg Version on test site
- Simple/Atomic Test Site
- Can you also check to see if `Use theme styles` is toggled ON in your Editor Preferences, as below?  (Not sure this would impact anything, but want to check)

<img width="550" alt="screenshot" src="https://user-images.githubusercontent.com/27249804/235742016-58eb5898-b5e4-431c-9bf1-5212f5d44d78.png">

**Comment by filipanoscampos** [comment] 2023-05-06 08:44
Hi @cuemarie 

I stumbled on this ticket and was able to reproduce the issue.
I believe this is related to having multiple images, but it still should work as expected.
Here is my test post on an FSE theme: https://wp20211011businessatomic.wpcomstaging.com/?p=6657

**Comment by cuemarie** [comment] 2023-05-09 23:20
Hey @filipanoscampos , thanks for your help in triaging!  Could you let me know what steps you took to replicate the issue, and perhaps share a comparison screenshot between the editor and the live site, that helps display the problem?  

I took a look at your test post, but could use more information on how that reflects this issue. Thanks so much!

**Comment by syhussaini** [comment] 2023-05-11 09:42
I played into the ticket and performed a test on my testing.domains site: https://testing.domains/2023/05/11/sample-post/ and found no issues. Here is a video of my test: https://d.pr/v/ut5kyx

**Comment by cuemarie** [comment] 2023-05-16 20:18
I checked the user's site and can see this is a plugin conflict with the plugin **EmbedPress**. I'm replying to the user and closing this report. 

Please be sure to perform all troubleshooting steps noted here: P9HQHe-jC-p2 before reporting suspected issues as a bug.

**Closed as completed by cuemarie** 2023-05-16 20:18 UTC
Labels: Bug, [Pri] Normal, Triaged, [Closed] Not Reproducible
