### ISSUE TITLE
Jetpack search plugin shows as inactive after purchasing upgrade

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#66111] opened 2022-08-01 08:32 UTC
### Quick summary

Found in https://github.com/Automattic/wp-calypso/pull/65252#pullrequestreview-1049233222:

> When purchasing it on a Jetpack site from Settings > Performance, the plugins status is displayed as "Inactive", and the details page is offering me to purchase it again:
> 
> <table><tr><td><img width="500" alt="Screen Shot 2022-07-25 at 12 21 55" src="https://user-images.githubusercontent.com/1233880/180757571-729990c1-43fe-4245-af5b-320fd955dd12.png"></td><td><img width="500" alt="Screen Shot 2022-07-25 at 12 22 03" src="https://user-images.githubusercontent.com/1233880/180757626-8bfd3ef8-d06c-46eb-8abb-a41383b4165f.png"></td></tr></table>

### Steps to reproduce

- Go to https://wordpress.com/
- Switch to a Jetpack site
- Go to Settings > Performance
- Purchase the Jetpack Search upgrade
- Go to Plugins
- Search for "Jetpack Search"

### What you expected to happen

- The plugin should show up as active
- I shouldn't be able to purchase it

### What actually happened

- The plugin shows up as inactive
- I can purchase it again

### Platform (Simple, Atomic, or both?)

Self-hosted

**Comment by BogdanUngureanu** [comment] 2022-08-17 08:43
Followed the testing steps on a brand new Jetpack site and the issue is not reproducing anymore. 

I'll close the issue for now. If you are still reproducing it, feel free to open the issue again. :)

**Comment by mmtr** [comment] 2022-08-17 09:33
I can still reproduce it:

https://user-images.githubusercontent.com/1233880/185085779-00520181-b05c-41d2-bbbe-73805b8801a0.mov

**Comment by BogdanUngureanu** [comment] 2022-08-17 10:27
Oh, now I can reproduce it too! But this time with a different Jetpack site.

**Comment by BogdanUngureanu** [comment] 2022-08-26 15:50
Closing this since it has been handled in https://github.com/Automattic/wp-calypso/pull/66761

**Closed as completed by BogdanUngureanu** 2022-08-26 15:50 UTC
Labels: Bug, Jetpack, Needs triage, Marketplace
