### ISSUE TITLE
Atomic - Admin Sidebar Submenus out of bounds in wp-admin

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#71457] opened 2022-12-22 12:34 UTC
### Quick summary

When visiting wp-admin atomic sites if the window is too small or the user has many plugins installed, the submenus that are too close to the bottom of the window will not display fully and go out of bounds, making them inaccessible.

### Steps to reproduce

1. Go to any Atomic dotcom site and visit wp-admin
2. Make sure the window height is low enough so the Settings menu is close to the bottom
3. Hover your mouse over the Settings menu

### What you expected to happen

For the submenu to adapt and display to the top, as it does on Calypso and other wp-admin hosts (Pressable)

![image](https://user-images.githubusercontent.com/81776920/209130035-a08ae0ae-1d48-428f-a394-4f05ab9c4fbf.png)

### What actually happened

The submenu doesn't take into consideration the height of the page:
![image](https://user-images.githubusercontent.com/81776920/209135716-6e6ff711-01c1-4846-8125-a5b9a367f043.png)
 

### Context

Any AT site.

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Zooming out on the page.
Or 
Add the following PHP snippet:

```
add_action('admin_head', 'add_custom_css_admin_menu_fix');

function add_custom_css_admin_menu_fix() {
  echo '<style>
#adminmenu li:nth-of-type(n+10).opensub .wp-submenu.wp-submenu-wrap {
  bottom: 0;
  position: absolute !important;
  top: unset !important;
}
</style>';
}
```

![image](https://user-images.githubusercontent.com/81776920/209135417-9702ccb1-84f3-46ec-bf52-321df919340f.png)

**Comment by zachspears** [comment] 2022-12-29 01:27
Able to reproduce consistently, keeping Normal priority due to high impact.

**Comment by katinthehatsite** [comment] 2023-04-12 13:08
Hi @zachspears and @mxhassani - I am working on the fix on this and I am not able to reproduce the issue on my end. This is what I am seeing:

https://user-images.githubusercontent.com/25575134/231467115-916bf829-5033-4288-8e55-5e4ef5a36f68.mp4

Could you please review the screencast above and let me know if I am following the correct steps? Thanks!

**Comment by mxhassani** [comment] 2023-04-17 06:58
@katinthehatsite The issue was happening on wp-admin pages. However, I've just tested on my site and the user's site and the issue appears fixed now.

**Comment by katinthehatsite** [comment] 2023-04-17 08:13
Hi @mxhassani - thanks for getting back! Since we both tested and could not reproduce the issue on `wp-admin` pages, I am going to close this issue for now. If you run into it again, feel free to re-open and we can look into it again.

**Closed as completed by katinthehatsite** 2023-04-17 08:13 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Atomic
