### ISSUE TITLE
Sites: allow uploading and cropping of site icons

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#376] opened 2015-11-21 10:37 UTC
This is currently a bit of a roadblock — not easy to add or change an icon to a site. We need an endpoint in the API to handle this, as well as a cropping tool in the UI to set it.

Ideas for placement were:

* Inline within `<Site>`
* In general site settings.

**Comment by lancewillett** [comment] 2016-03-29 15:49
Duplicate of #37

**Closed by lancewillett** 2016-03-29 15:49 UTC
Labels: API, Components, Site Settings, [Type] Task
