### ISSUE TITLE
CoBlocks Post Carousel: Conflict with Gutenberg on AT sites

### ISSUE THREAD

**Issue by samiff** [Automattic/wp-calypso#41346] opened 2020-04-21 21:50 UTC
#### Steps to reproduce

* Testing with Twenty Twenty theme on a WordPress.com AT site.
* The Post Carousel block being used is from Coblocks `coblocks/post-carousel`
* With Gutenberg (v7.8.1) and Coblocks (v1.24.0) active, I get an error when inserting the first post carousel block, or trying to access the Feed Settings options for the block:
* `TypeError: Cannot convert undefined or null to object in https://c0.wp.com/c/5.4/wp-includes/js/dist/vendor/react-dom.min.js`
* Turning off the Gutenberg plugin allows the post carousel block to work as expected.

#### Context / Source

#user-report
p9F6qB-57X-p2

**Comment by simison** [comment] 2020-04-22 08:08
cc @Automattic/ajax

**Comment by simison** [comment] 2020-04-22 08:09
Would be good to know if upgrading to Gutenberg 7.9.1 fixes this, as we're doing that soonish (p7DVsv-8tt-p2, pbAok1-Fu-p2).

**Comment by alshakero** [comment] 2020-04-22 12:18
Can confirm that this is reproducible in 7.8.1 but is fixed in 7.9.1 :tada:

[It was fixed here. ](https://github.com/WordPress/gutenberg/commit/441e909e72b04cddab28dd8f0e8e3d2d07d876b4#diff-1b1c49e8081943c015861c96b2184474)

**Comment by marekhrabe** [comment] 2020-04-22 12:28
I have tested this in core WP install, with Gutenberg and CoBlocks plugins straight from the plugin repo, latest versions, and I can replicate the bug. 

It has nothing to do with our custom wpcom version (which runs only on Simple) but seems to be a Core vs CoBlocks bug.

**Comment by simison** [comment] 2020-04-22 12:33
@alshakero that's core's `latest-posts` block though? 

@marekhrabe would be great to make sure there's an issue open for this at CoBlocks repo.

**Comment by marekhrabe** [comment] 2020-04-22 12:33
@alshakero I haven't yet seen your comment when I posted mine. I can reproduce the issue in WP w/ CoBlocks 1.24.0 & Gutenberg 7.9.1. Can you confirm?

The link to fix you have posted is for the Latest Posts block from core, which has no relation to CoBlocks. Would it be possible that Latest Posts was updated to break the incompatibility with the Category selector and CoBlocks must do a similar fix?

**Comment by alshakero** [comment] 2020-04-22 12:49
I'm double-checking right now.

**Comment by alshakero** [comment] 2020-04-22 13:21
You're right. It seems the categories get cached and the issue isn't always happening. I could repro in 7.9.1.

**Comment by alshakero** [comment] 2020-04-22 16:03
OK, I did some investigation and I can't figure out what's going on exactly. But I have some interesting findings.

1. The bug is reproducible on both WordPress 5.4 and 5.5-alpha.
2. The bug isn't reproducible in Gutenberg v7.9.1 locally.
3. The bug *is* reproducible in Gutenberg v7.9.1 on an AT site 🤷‍♂️ 

I found that this issue isn't reproducible locally in Gutenberg master. But here is some info on how to reproduce it.

**On your machine:**

1. Clone Gutenboarding#master.
2. Setup your env as instructed in [Gutenberg docs](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/getting-started.md#local-environment).
3. Install Co-blocks extension on your local site.
4. Checkout commit [`4cc8121c95b507809056fca158b6bae60ed22157`](https://github.com/WordPress/gutenberg/commit/4cc8121c95b507809056fca158b6bae60ed22157) the issue should be reproducible.
5. Checkout commit [`16e4f2032777d63984d0dbf53569018c10f77dca`](https://github.com/WordPress/gutenberg/commit/16e4f2032777d63984d0dbf53569018c10f77dca) the issue should be fixed.

These commits come right after each other. Meaning the latter fixes the issue. Although I couldn't find why.

**Comment by marekhrabe** [comment] 2020-04-22 18:55
Thanks for confirmation. I was using Jurassic.ninja sites and on some of them, I can no longer replicate the issue. Some sort of cache might be in play here.

The error, as I understand it, comes from passing null/undefined to the category selector that Posts Carousel block uses (it has category picker in its inspector controls). This happens when you insert the block but the list of categories is not fetched yet.

A wild and unconfirmed guess - if something did change around the way sidebar is instrumented and initialized (which looks like it did in one of those commits you link), I think it might be possible that the sidebar previously pre-fetched categories for its own use, because it also has the same control which you use to set category for the post. That way categories were actually always loaded before you had a chance to insert any block and the Posts Carousel never had to deal with the empty category list. 

Nothing confirmed but I think it might be worth checking and adding some guard against empty categories to CoBlocks or into the category selector component directly.

**Comment by jackiejade** [comment] 2020-05-08 14:51
I have another example of this in #20941806-hc 

Steps to reproduce:

User has added the Post Carousel block on their Atomic site. 
When clicking on "Feed Settings" in options panel we get:

"This block has encountered an error and cannot be previewed."

https://d.pr/i/cFG82W

Deactivating Gutenberg plugin resolved the issue.

**Comment by rosepajaroja** [comment] 2020-06-27 11:36
Possibly another example: #22208321-hc, #3097186-zd

Steps to reproduce:

1. Add CoBlocks/Post Carousel Block on AT site
2. Go to Feed Settings to add a category, and this happens:

https://www.loom.com/share/b25346fce80c47e0b76b6665c39e46f9

**The same thing happens for **Posts block.**

**Comment by Addison-Stavlo** [comment] 2020-07-06 19:39
I am NOT able to reproduce the original issue with the error on inserting the Posts Carousel.  Is anyone still able to reproduce this part (and perhaps have any more specifics)?

I am able to reproduce @rosepajaroja 's issue - Adding a category gives a rest param error (and infinite loading spinner):

![Screen Shot 2020-07-06 at 3 36 30 PM](https://user-images.githubusercontent.com/28742426/86633292-7bbddd80-bf9e-11ea-87ad-9523259ad30c.png)


I tried to test on simple sites for comparison, and encountered another issue there blocking me from doing so (created #43920).  On simple sites, the block can't seem to find my posts the same way 'Blog Posts' or 'Latest Posts' blocks do:

![Screen Shot 2020-07-06 at 3 26 40 PM](https://user-images.githubusercontent.com/28742426/86633507-bc1d5b80-bf9e-11ea-88e7-783f6c23f412.png)

**Comment by samiff** [comment] 2020-07-06 19:44
@Addison-Stavlo I'm _not_ able to reproduce the original issue with Posts Carousel on up to date versions of Gutenberg/CoBlocks.

**Comment by Addison-Stavlo** [comment] 2020-07-06 21:21
Created an Issue for the [Categories bug](https://github.com/Automattic/wp-calypso/issues/41346#issuecomment-650548350) at CoBlocks - https://github.com/godaddy-wordpress/coblocks/issues/1561 - given this is reproducible locally without Gutenberg on WordPress 5.5.

**Comment by yansern** [comment] 2020-08-06 00:30
This is now fixed in this PR. https://github.com/godaddy-wordpress/coblocks/pull/1576
Included in CoBlocks 2.1.0.

**Closed by yansern** 2020-08-06 00:30 UTC
Labels: Atomic, Blocks, [Pri] High, [Type] Bug
