### ISSUE TITLE
Gutenberg: Media: Free Photo Library and Google Photo option missing in editor

### ISSUE THREAD

**Issue by TheSteveK** [Automattic/wp-calypso#28960] opened 2018-11-29 18:17 UTC
#### Steps to reproduce
1. Start a new post on a wp.com site using Gutenberg I used a test site stothek.wordpress.com
2. Select either an image block or the featured image in the document properties
3. Note options for upload, URL or Media library but no Pexels (free photo library)
4. Click the Media library, there's no free photo library option within there either:

![screen shot 2018-11-29 at 1 06 43 pm](https://user-images.githubusercontent.com/12895386/49242356-84b8f700-f3d8-11e8-8b24-2e1a02c02646.png)

![screen shot 2018-11-29 at 1 03 08 pm](https://user-images.githubusercontent.com/12895386/49242564-1a548680-f3d9-11e8-9655-700102e2e416.png)

#### What I expected

An option to use the free media library or google photos

#### What happened instead

No option available

#

I first noticed this on a concierge call with a customer and then tested on my site to find the same issue.

**Comment by KokkieH** [comment] 2018-11-30 12:23
Another request [here](https://en.forums.wordpress.com/topic/adding-images-from-google-picture-library-under-new-editor/).

Just noting this feature is available in the true Calypso Gutenberg editor. It's only in the current Calypsofied version of the core editor that it's not available. See https://github.com/Automattic/wp-calypso/issues/28698#issuecomment-441477101

**Comment by spencerberry** [comment] 2018-12-08 15:42
Another request for atomic sites to have this functionality in the editor itself, via chat #8671586-chat

**Comment by formosattic** [comment] 2018-12-10 05:56
+1 in 1235391-chat

**Comment by vindl** [comment] 2018-12-11 16:54
The problem here is that Calypsoify uses wp-admin version of the editor which only supports core Media Library. Because of that we don't get the look and functionality of Calypso's Media Library.

This will be fixed automatically for Simple sites once Gutenlypso (Gutenberg integration in Calypso) is released.

> Another request for atomic sites to have this functionality in the editor itself

I'd like to note that the above release will not help Atomic sites though, since they will probably stay on Calypsoify even after the Gutenlypso launch.

/cc @apeatling since this might be relevant for our decision on how to handle Jetpack and Atomic sites.

**Comment by vindl** [comment] 2018-12-19 12:03
This has been resolved by the release of Gutenlypso which integrates Calypso's Media Library.

There are no current plans to move from Calypsoify for Atomic sites now due to technical difficulties, so showing the core Media Library in that case is the expected behavior.

**Closed by vindl** 2018-12-19 12:03 UTC
Labels: Atomic, [Goal] Gutenberg, [Pri] Low, wp-admin
