### ISSUE TITLE
Help: Operator gravatars overlap after transfer

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#1564] opened 2015-12-14 18:52 UTC
While testing today, David transferred a chat to me. When I responded soon after David, my Gravatar overlapped with his. I wonder if there's a way we could prevent this with a `clear: right` or something similar.

![overlap](https://cloud.githubusercontent.com/assets/7240478/11790438/1963e150-a259-11e5-812f-55d9b53da624.png)

**Comment by lancewillett** [comment] 2016-04-08 00:13
Is there a way to reliably reproduce this? It's hard to repeat without exact steps.

**Comment by jeremeylduvall** [comment] 2016-04-09 14:14
This is a pretty tricky one to reproduce because it takes two operators. One way to repro would be to do this:

1. Login under your account in Olark assigned to the chat training group that we use for training others
2. Have someone else login to Olark and assign themselves to the chat training group

Now, you'll have two operators accepting chats from the training group. Make sure each operator has a photo of some sort set to display in chat here:

https://www.olark.com/op/current/edit

Then, initiate a chat with yourself (details at P4UnRj-d5-p2). Immediately type `!transfer` to transfer the chat to the other available operator. Have the other operator respond to the user.

The central issue is that Olark drops in the operator photo with the initial message. When the initial messages are back to back, the two images can overlap.

I'll ping you as well. Happy to help repro. It's difficult to do solo.

**Comment by rralian** [comment] 2016-05-05 17:08
cc @dllh @omarjackman

**Comment by kriskarkoski** [comment] 2016-08-23 22:01
Since we haven't fixed this in 9 months and a replacement will be ready soon I am going to close this

**Closed by kriskarkoski** 2016-08-23 22:01 UTC
Labels: Live Chat, Support, [Pri] Normal, [Type] Bug
