### ISSUE TITLE
Suggested article links hanging up

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#41061] opened 2020-04-13 21:30 UTC
When a user (and myself and 2 other HEs) click on a suggested article at the bottom of this page: https://wordpress.com/read/feeds/50178383/posts/2661848051 the destination link doesn't load. 

Screencast: https://d.pr/v/fN3a2H

If you refresh while it's hanging, it will load. If you go back to the previous page (which also requires a refresh) and try another link, same thing happens.

User reported here: #2287304-hc
Follow up ticket here: #2874124-zen

**Comment by aaronrobertshaw** [comment] 2020-04-21 03:19
I'm currently looking into this one. It appears to be related to the addition of https://github.com/Automattic/wp-calypso/pull/40396/files#diff-e4e8dfe9d856c8280a2d8f4e602e654bR129 in PR https://github.com/Automattic/wp-calypso/pull/40396.

**Comment by aaronrobertshaw** [comment] 2020-04-21 06:30
Hi @hewsut can you shed any light on this issue?

It appears the reader full post component gets unmounted after its already been updated with the newly selected post. This leaves it in the loading state.

The issue only seems to be a problem when the initial post being viewed is coming from a feed.

**Comment by serabi** [comment] 2020-05-01 17:24
This ticket came back up in play for me today. @hewsut have you had a chance to look at this yet?

I'll put the ticket back on hold for now. Thank you!

**Comment by tanjoymor** [comment] 2020-05-04 20:14
Turns out that this issue has been resolved (the user advised me) - was that a fix applied via this request or has something else happened, somewhere else to resolve it? @aaronrobertshaw @hewsut 

I've just tested it myself and it is working as expected now.

**Comment by aaronrobertshaw** [comment] 2020-05-04 23:18
@tanjoymor I can confirm the issue has been resolved and is working for me. It looks as if it was fixed by @hewsut [here](https://github.com/Automattic/wp-calypso/commit/59ef4ddf9fb1a11ecd675d3f36b66778213bcad8#diff-e4e8dfe9d856c8280a2d8f4e602e654bR129).

**Closed by aaronrobertshaw** 2020-05-04 23:18 UTC
Labels: [Type] Bug
