### ISSUE TITLE
Post Emails aren't displaying Featured Image or Excerpt for Atomic Sites

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#90066] opened 2024-04-29 23:04 UTC
### Quick summary

On my test Atomic Site, when I publish a post with a featured image and an excerpt, the post email to my test subscriber does not include the Featured Image or the Excerpt even though my Newsletter Settings have those options checked.

This does not happen on my simple sites.

### Steps to reproduce

1. Add a new post to an Atomic site
2. Add a Featured Image and an Excerpt in the Post sidebar
3. Publish the Post

### What you expected to happen

I expected my test subscriber to get an email with the featured image and the excerpt.

### What actually happened

My test subscriber got an email without a Featured image and it displayed the full post.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

I tested my AT site with the Creatio, Twenty Twenty-Four, and Twenty-Seventeen themes activated and got the same result regardless of the theme.

**Comment by liviopv** [comment] 2024-04-30 15:03
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Creating the post

https://github.com/Automattic/wp-calypso/assets/14153300/53201fee-8053-4ae1-8109-8d5a0b4db032

Resulting email:

![CleanShot 2024-04-30 at 15 59 08@2x](https://github.com/Automattic/wp-calypso/assets/14153300/ee9c8943-3d53-41f7-995a-df192ac08803)


📌 ACTIONS
- Triaged

**Comment by enejb** [comment] 2024-04-30 19:44
The issue here is that jepack sync did not working as expected on the atomic sites. 

I have come across where the initial full sync didn't work as with some options being missed.

I opened D147104-code  and D147082-code in order to fix some of these issues. 
I wonder if would make sense to implement a fix for atomic sites to where the option `wpcom_featured_image_in_email` is not set yet and we sync it again from the jetpack side of thing. cc @lezama ?

**Comment by tellisbethel** [comment] 2024-05-21 13:11
New case here: 8215402-zd-a8c
I'm asking the user to try adding an image to the post body instead as a potential workaround.

**Comment by enejb** [comment] 2024-07-08 18:23
@candy02058912 can you help me replicate this issue that you are seeing. 

I was able to recieve this post https://atomictyxla.com/2024/07/08/howdy-5/  as expected. 
See 
<img width="1812" alt="Screenshot 2024-07-08 at 11 21 43 AM" src="https://github.com/Automattic/wp-calypso/assets/115071/fc7e2c3f-947f-42f2-b3dd-853c2d0f4bab">

and 

<img width="950" alt="Screenshot 2024-07-08 at 11 20 40 AM" src="https://github.com/Automattic/wp-calypso/assets/115071/c9f73acb-8fd4-4d51-b410-5fe473d93b52">

I had my setting set to 
<img width="758" alt="Screenshot 2024-07-08 at 11 22 53 AM" src="https://github.com/Automattic/wp-calypso/assets/115071/91b2f7f2-8527-4070-afe2-c987b1780c46">

**Comment by candy02058912** [comment] 2024-07-09 07:50
Thanks @enejb for providing the extra info on the settings!

Here were my settings initially for the atomic site:
![email settings](https://github.com/Automattic/wp-calypso/assets/6586048/51d56747-3d25-43a1-931e-72a7a9a0b01c)
Everything worked once I clicked on "Save settings".
Perhaps it was due to somehow the settings weren't synced before?

So, I created a new atomic site to test, and everything is working! Those settings were on by default.

**I propose that we can close this issue since it is fixed. Can you help close the issue @enejb?**

Appreciate the quick followup!

## Summary for future reference:
* New sites shouldn't be encountering this issue anymore
* For old sites, maybe all it takes is a re-click on "Save settings"
* If the above isn't working, suggest the user a workaround of [adding the image to the post body](https://github.com/Automattic/wp-calypso/issues/90066#issuecomment-2122606610) and reopen this issue

**Comment by enejb** [comment] 2024-07-09 14:14
Closing this issue. If it comes up again. We can reopen it.

**Closed as completed by enejb** 2024-07-09 14:14 UTC
Labels: Bug, [Pri] BLOCKER, Triaged, Customer report [LEGACY], [Platform] Atomic, [Status] Priority Review Triggered, Newsletters, [Feature] Site Content Emails, [Product] WordPress.com, [Feature Group] Content Management
