### ISSUE TITLE
Staging Sites and Server Settings tab are not loading for suspended sites 

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/wp-calypso#94877] opened 2024-09-25 08:02 UTC
Opportunity post: pfS6dH-bF-p2

---

If a user has a suspended blog that is Atomic on their account and try to access `Staging Sites` or `Server Settings` for that site, these tabs would not load at all:

https://github.com/user-attachments/assets/49c3c114-0e8d-4061-88ed-6b7f7a2ad4de

**To reproduce**:

* Use a regular user account and not your Automattician account for testing
* Ensure that the user account has an Atomic site with Business plan
* Suspend the site by adding a black flag to it (you can do that, for example, from User Report Card)
* Navigate to `https://wordpress.com/staging-site/{yourSite}` on a site that you just suspended
* Observe that it either stuck in the loading state or does not load at all
* Refresh that page
* Observe nothing loads at all
* Try navigating to `Server Settings`
* Observe that a similar issues is happening there as well

**Expected**:

* To see the UI for staging sites or server settings even though the site is suspended

**Comment by katinthehatsite** [comment] 2024-09-25 08:39
It might be worth checking if it is an expected behaviour for different graylist flags

**Comment by obenland** [comment] 2024-09-27 19:40
@katinthehatsite Will D162312-code solve this issue? Is it a duplicate of https://github.com/Automattic/dotcom-forge/issues/8801?

**Comment by katinthehatsite** [comment] 2024-09-30 09:22
@obenland no, it is a different issue. The diff is allowing to create a staging site for a **production site that is not suspended** (at the moment, it is not possible). 

The issue that is reported is something else and is related t**o production sites that ARE suspended:** the user can not access the staging sites tab on a suspended site at all. What you get is a blank screen. What you should get is a Calypso UI that tells you that is not possible to create a staging site from a suspended production site. The same issue is happening with Server Settings tab. 

As mentioned in https://github.com/Automattic/wp-calypso/issues/94877#issuecomment-2373436921 , it might be worth double-checking for example with ToS team what is actually the expected behavior first - should the user be able to access these tabs on a production site if it is suspended at all?  and perhaps then, handle this more gracefully in the UI.

**Comment by mmtr** [comment] 2024-10-09 10:44
Turns out we already have a vetted opportunity to improve the user experience of suspended sites (pekYwv-4BU-p2, https://github.com/Automattic/dotcom-forge/issues/8908), so I'm closing this one as duplicate.

**Closed as not planned by mmtr** 2024-10-09 10:44 UTC
Labels: Bug, [Status] Priority Review Triggered, Staging Sites, Groundskeeping
