### ISSUE TITLE
Calypso not loading in Safari private window

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#6555] opened 2016-07-06 14:39 UTC
#### Steps to reproduce
1. In Safari on a computer, go to File > New Private Window, or in Safari on a mobile device, tap Private to open a new private window
2. Go to https://wordpress.com
#### What I expected

I expected Calypso to load as usual.
#### What happened instead

I ended up on a blank screen with the WordPress logo, and the console displayed these errors:

```
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
TypeError: window.AppBoot is not a function. (In 'window.AppBoot()', 'window.AppBoot' is undefined)
```
#### Browser / OS version

Safari 9.1.1 (11601.6.17) / Mac OS X 10.11.5 (15F34)
Safari / iPhone 6 iOS 9.3.2 (13F69)
#### Screenshot / Video

![screen shot 2016-07-06 at 3 34 25 pm](https://cloud.githubusercontent.com/assets/8658164/16621728/32a27d66-438f-11e6-89ab-ad5488a14ac1.png)
#### Context / Source
# user-report

113375-h

**Comment by rwaynick** [comment] 2017-04-21 18:09
I'm still able to re-produce this issue using the same steps and received the same error as mentioned above.

A user initially contacted us about the same issue in a non-Private window on iOS (which I'm not able to re-produce at the moment), but was able to re-produce the issue in a Private window on Mac and iOS (iPad).

Safari Version 10.1 (12603.1.30.0.34), macOS Sierra 10.12.4

![screen shot 2017-04-21 at 3 04 14 pm](https://cloud.githubusercontent.com/assets/10882502/25290380/36f69d86-26a4-11e7-9749-70808b4a3d47.png)

iPad Mini 4, iOS 10.3.1 

![img_0066](https://cloud.githubusercontent.com/assets/10882502/25290415/57819a38-26a4-11e7-9c40-f8c6b3df8bc8.PNG)

**Comment by aduth** [comment] 2017-04-21 18:35
@ehg @gziolo Could this have regressed with boot refactoring in #12395 ?

**Comment by gziolo** [comment] 2017-04-21 18:50
I tested with Safari and private mode to validate if local storage shim works properly.

**Comment by gziolo** [comment] 2017-04-21 18:52
It looks like error related to storage though.

**Comment by umurkontaci** [comment] 2017-04-24 19:27
Safari throws whenever you call `localStorage.setItem` in private browsing, and it seems we are calling `setItem` before setting up the shim.

**Comment by fabianapsimoes** [comment] 2017-05-05 13:40
This issue is also causing problems for social signup. @p3ob7o and @aidvu had reported getting stuck in the `/start/social` after authentication with Google. After a lot of troubleshooting, we noticed this only happens for Safari in private mode.

**Comment by fabianapsimoes** [comment] 2017-05-05 13:43
Steps to reproduce the aforementioned problem:

- Open a private tab in Safari.
- Visit `/start/social` and choose to sign up using a Google account.
- A pop-up for authentication will open. Confirm all the steps there.
- Once the pop-up closes, notice that instead of being redirected to signup's processing screen, you'll be stuck on the `user` step.

In non-private Safari and in other browsers, the issue isn't reproducible.

**Comment by Tug** [comment] 2017-05-08 08:49
@fabianapsimoes The signup bug is actually a different issue, I filled the bug here https://github.com/Automattic/wp-calypso/issues/13747

**Comment by klimeryk** [comment] 2017-05-08 11:22
Created a PR to address this: https://github.com/Automattic/wp-calypso/pull/13748 (or at least get the discussion going ;)).

**Comment by gziolo** [comment] 2017-05-08 11:38
@klimeryk we should rather get https://github.com/Automattic/wp-calypso/issues/13747 merged instead. @aduth opened PR which solves this issue and prevents future occurences caused by Babel's transpilation process :)

**Comment by aduth** [comment] 2017-05-08 12:56
Might it be better to get the minimal fix in place if it's quicker to review, then follow-up with #7232 (think you intended to link to that?)?

**Comment by gziolo** [comment] 2017-05-08 16:09
Yes, #7232 it is :)

**Comment by klimeryk** [comment] 2017-05-08 17:37
I did not see any PRs referenced on this issue, so I assumed nothing is being done to address it and did not search through open PRs - great to know that's not the case 👍 Though, I agree with @aduth - #7232 has been open for a long time and if a minimal fix (I'll try to rework my PR based on his comment there) could be applied now, that'd be great.

**Closed** 2017-05-11 13:11 UTC
Labels: Framework, [Pri] High, [Type] Bug
