### ISSUE TITLE
Editor: Remove or Clarify UTC Time When Scheduling Posts

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/wp-calypso#32173] opened 2019-04-10 11:50 UTC
#### Steps to reproduce
1. In Calypso classic, go to My Site > Blog Posts > Add to create a post.
2. Schedule the post to be published more than 7 days in advance.

#### What I expected

I expected the post's scheduled time to match the timezone in My Site > Settings.

#### What happened instead

If the post is scheduled more than 7 days in advance, only UTC time is shown in the scheduler. There is a small message about this below the UTC time, but it's still confusing.

If the post is scheduled within 7 days, the site's time also appears above the scheduling calendar. This helps a bit, but it's still confusing. The different behaviours depending on how far in advance the post is scheduled also add to the confusion.

#### Screenshot / Video

https://cld.wthms.co/I4tFSb

#### Context / Source

This has been reported by multiple WP.com customers who are **very** confused. They think the posts are being published at the wrong time, and that the scheduled time cannot be changed.

Either changing UTC to their site's timezone or always displaying their site's time above the scheduling calendar (instead of only for posts scheduled within 7 days) would make this more clear.

#user-report #painpoint

**Comment by juliasydnor** [comment] 2019-04-10 11:50
Possibly related: https://github.com/Automattic/wp-calypso/issues/30533

**Comment by jsnajdr** [comment] 2019-04-10 13:57
Thanks for the report! Fixed in #32178 by showing the scheduled time in the site's timezone.

**Comment by pauljacobson** [comment] 2019-04-11 08:31
I have an instance of this issue too in 11786172-hc where a user thought they were unable to schedule a post. I noticed this disconnect between the selected date, and the time/date that the post scheduler reflected (seems to be relative to my timezone - the user is UTC -6, and I'm UTC +3), [here](https://cld.wthms.co/wj9HEl):

![](https://cld.wthms.co/wj9HEl+)

**Comment by KristinaKay** [comment] 2019-11-21 04:19
User says "I'm having problems publishing articles. Is the server down? Everytime I publish a post it says Oops cant be found?"

The URL on the post was showing us this: 
https://theplayfulparent.org/2019/11/20/thanksgiving-dining-entertaining-guide-2

But user is in NY and it’s the 20th. Their time zone is set for NY but the URL is using UTC time.

The problem is that in NY,  the 21st hasn’t happened yet so the URL does not work because the post does not exist.

What I did:

When I changed this date to November 20 and set the time to 12:23 PM on the post, it worked.

New URL:
https://theplayfulparent.org/2019/11/20/thanksgiving-dining-entertaining-guide/

#16803974-hc

**Comment by jsnajdr** [comment] 2020-05-26 08:14
Closing because the classic Calypso Editor is going to be deprecated in just a few days.

**Closed by jsnajdr** 2020-05-26 08:14 UTC
Labels: Editor, [Type] Enhancement
