### ISSUE TITLE
Block Editor: ⨁ plus icon and block toolbar missing in Microsoft Edge 18

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#39072] opened 2020-01-25 15:39 UTC
#### Steps to reproduce
1. Starting at URL: Any Post/Page with some Blocks added
2. Hover over spots in between various Blocks 
3. Select any Block

#### What I expected
- See the ⨁ icon appearing to add a Block in that spot
- See the Block's toolbar above it when any Block is clicked (selected)

#### What happened instead
No ⨁ is appearing and the toolbar is missing

#### Browser / OS version
Reproduced in Windows 10 | Edge 18 (BrowserStack)

#### Screenshot / Video

![](https://d.pr/i/lgdogS+)
_Link: https://d.pr/i/lgdogS_

#### Context / Source
#painpoint #manual-testing #user-report (generated from p1579963357147800-slack-localized-upwork and in 2659692-zen)

**Comment by Robertght** [comment] 2020-01-27 12:28
Another case in 2661904-zen

**Comment by Robertght** [comment] 2020-01-27 14:03
As an alternative, I've used the fixed one at the top.

**Comment by thesacredpath** [comment] 2020-01-27 21:42
Another case here: 392564-hc

**Comment by geekinthegirl** [comment] 2020-01-28 11:03
Had a chat earlier with the same issue: 18230431-hud

Although I was unaware of the fix at the time! They switched to using Firefox instead of Edge, with no issues.

**Comment by zdenys** [comment] 2020-01-28 12:32
Another case 2660605-zen.

**Comment by retnonindya** [comment] 2020-01-29 09:08
User report #18006665-hc -- I suggested them to update their Edge browser to the latest version and informed them about displaying Top Toolbar workaround.

**Comment by lakellie** [comment] 2020-01-29 19:22
Another report in 2671311-zen

**Comment by catkit** [comment] 2020-01-29 20:37
The above user asked to get notified when this is fixed. I'm adding this comment so I can let them know it.

**Comment by edequalsawesome** [comment] 2020-01-30 17:57
Also reported in #10215134-hc

**Comment by chriskmnds** [comment] 2020-01-31 10:29
We just confirmed this in wp-admin on both WPCOM and local WP install using Edge 18. So this doesn't look like a wp-calypso issue per se, so best reported at https://github.com/WordPress/gutenberg to get more insight. I will follow up with an issue there.

**Comment by catkit** [comment] 2020-01-31 18:24
Another report: #2677182-zen

**Comment by GeoJunkie** [comment] 2020-02-05 16:27
Reported in #4268857-hc

Sent the workaround in #2693161-zen

For ease of locating the fix, this is the setting to adjust:

![](https://cldup.com/gbSq4XXYok.png)
Image Link: https://cldup.com/gbSq4XXYok.png

(h/t @retnonindya for the screenshot)

**Comment by tbradsha** [comment] 2020-02-17 18:00
17775546-hc.

**Comment by zdenys** [comment] 2020-02-18 12:55
2696122-zen

**Comment by zdenys** [comment] 2020-02-18 16:24
18773946-hc

**Comment by joweber123** [comment] 2020-02-19 04:45
18614897-hc

Followup Ticket: 2727121-zen

**Comment by zdenys** [comment] 2020-02-19 17:09
13308441-hc

**Comment by GeoJunkie** [comment] 2020-02-19 18:31
Although the [Gutenberg issue is closed](https://github.com/WordPress/gutenberg/issues/19979), it's still happening. Reported in 18512334-hc

**Comment by khristiansnyder** [comment] 2020-02-19 18:47
Another reported in 18807571-hc
Edge 18.18362 on Windows 10.0.0

**Comment by lancewillett** [comment] 2020-02-24 17:31
This could be a case of merging in the Gutenberg core updates into WordPress.com. CC @ockham @Automattic/luna for an expert opinion

**Comment by simison** [comment] 2020-02-24 17:46
Correct — this is fixed in Gutenberg 7.5.0 and we're now on 7.3.0, about to update to 7.4.0.

cc @vindl @ramonjd

**Comment by jjchrisdiehl** [comment] 2020-03-01 20:48
@simison Does this mean a fix is on the horizon? I have another case here 2753696-zen

I can also reproduce the issue in Edge, is there an eta on when this issue should be resolved?

**Comment by arunsathiya** [comment] 2020-03-02 02:33
2756554-zen; recommended "top toolbar" workaround for now.

**Comment by ramonjd** [comment] 2020-03-02 22:20
> Does this mean a fix is on the horizon?

It's on the horizon, but we on are on a slow moving ship 🚢 We've had to hold off on upgrading Gutenberg for at least a week until we fix the titles data migration issue. p58i-8E9-p2

**Comment by gwwar** [comment] 2020-03-03 20:57
Instead of waiting, I think it should be possible to add the polyfill as a wpcom customization then remove it when we're ready for the 7.5.0 update 

https://github.com/WordPress/gutenberg/pull/20110/files

**Comment by kwight** [comment] 2020-03-04 00:26
There's a patch in D39800-code that adds the polyfill to our production Gutenberg v7.3. Having a hard time testing it though – @ramonjd @vindl if someone wants to take a pass at it too 👍

**Comment by kwight** [comment] 2020-03-04 00:44
> Hard time, meaning, my access to Edge 18 is Browerstack, and I'm not convinced I'm hitting my sandbox

Browserstack has a local testing feature that can force all DNS resolution through your local comp 👍

<img width="606" alt="Screen Shot 2020-03-03 at 4 41 43 PM" src="https://user-images.githubusercontent.com/349751/75833547-38dcc680-5d6e-11ea-8f74-bd53c2c3699f.png">

**Comment by ramonjd** [comment] 2020-03-04 01:43
> Hard time, meaning, my access to Edge 18 is Browerstack, and I'm not convinced I'm hitting my sandbox

I have trouble with this too at times 🤕 I tested and could sandbox successfully, but the + icons weren't showing for me with D39800-code applied

![Mar-04-2020 12-40-25](https://user-images.githubusercontent.com/6458278/75836337-b576b000-5e15-11ea-86f3-ed41babd3b55.gif)

**Comment by ramonjd** [comment] 2020-03-04 02:34
I clicked close accidentally :)

**Comment by SiobhyB** [comment] 2020-03-04 09:17
Another report of this issue in 2755126-zen, the user's able to replicate the problem in Edge and Explorer 11. I've suggested the top toolbar option as a workaround for now.

**Comment by kwight** [comment] 2020-03-04 22:07
D39800-code is ready for review, to handle simple sites. https://github.com/Automattic/wpcomsh/pull/401 will handle Atomic.

**Comment by kwight** [comment] 2020-03-04 22:40
> Correct — this is fixed in Gutenberg 7.5.0 and we're now on 7.3.0, about to update to 7.4.0.

@simison @vindl Just double-checking: we're next moving to 7.4, so another version with the same problem? If this is the case, I wonder if the changes in D39800-code should go in the `gutenberg-wpcom` plugin then (but they would then need to be removed as part of upgrading to 7.5+).

**Comment by gwwar** [comment] 2020-03-04 22:50
Thanks @kwight D39800-code tests well for me, we can land that ahead of the Atomic side of things if need be.

**Comment by kwight** [comment] 2020-03-04 23:03
Fixed for simple sites in D39800-code.

**Comment by kwight** [comment] 2020-03-04 23:40
Fix deployed for Atomic sites, the release is already live.

**Comment by ramonjd** [comment] 2020-03-05 00:24
Unfortunately, I think D39800-code broke a lot of sites

p1583367137051600-slack-CBTN58FTJ

This make the case to upgrade to 7.5.0/7.6.0 as soon as practicable. 

cc @Automattic/create

**Comment by gwwar** [comment] 2020-03-05 00:36
@ramonjd We can make a second attempt tomorrow, we missed a detail for folks using latest Gutenberg.

**Comment by gwwar** [comment] 2020-03-05 00:37
Overall I would recommend keeping up in general since WP core releases pull in latest of Gutenberg.

**Comment by ramonjd** [comment] 2020-03-05 00:51
> Overall I would recommend keeping up in general since WP core releases pull in latest of Gutenberg.


This has always been the goal. 

This iteration has been, however, "special" due to the ongoing data migration for incorrectly encoded titles. :)

**Comment by gwwar** [comment] 2020-03-05 01:23
Reopening, until we sort out the Atomic side of things.

**Closed** 2020-03-05 20:48 UTC
Labels: [Goal] Gutenberg, [Impact] High, [Pri] High, [Type] Bug
