### ISSUE TITLE
Marketplace: WooCommerce installation signup wizard isn't able to install woo payments

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#65622] opened 2022-07-15 03:44 UTC
When installing WooCommerce from the plugin screen in marketplace after installation you're [dropped into a broken state](https://github.com/Automattic/wp-calypso/issues/65620), after refreshing a couple of times you get redirected to the profile setup wizard in wc-admin. Following through this signup wizard you're prompted to install Woo Payments but this fails with an error.

This was on a site with a starter plan which I'm guessing is blocking the install of woo payments.

![Screenshot 2022-07-15 at 13-36-04 Setup Wizard ‹ WooCommerce ‹ c3po - Simple Site - Mapped — WooCommerce](https://user-images.githubusercontent.com/811776/179145381-397ea91d-e35f-4d5e-af29-bcf3a5e262dd.png)

- [ ] Install WooCommerce Payments plugin whenever we install WooCommerce on the starter plan
- [ ] Use a hook to filter out the install extra software step from the profile setup wizard on atomic sites with starter plans. This hook can be added to https://github.com/Automattic/wc-calypso-bridge.
- [ ] Investigate why I can't update business details (error happens when you click continue in the same step)

**Comment by cpapazoglou** [comment] 2022-07-15 06:25
I believe installing `WooCommerce Payments` together with WooCommerce _on any plan_ would be to WP.com benefit. What do you think @lsl ?

**Comment by lsl** [comment] 2022-07-16 06:52
Yes but...

I thought there was a plan to integrate it into woo core. Did that not end up happening? 

There is a permanent notification nudge until you go through KYC. Can we disable that?

Can woo pay be removed/hidden if people don't want woo pay installed? I seem to recall the post transfer atomic hooks needing to be repeatable (though I don't think they are repeated) - if they are repeated woo pay would get installed again in attempt to repair state. (Don't think this is a big issue but wondering if there is a gotcha I'm not aware of)

**Comment by cpapazoglou** [comment] 2022-07-28 10:20
> Investigate why I can't update business details (error happens when you click continue in the same step)

I unchecked the `Add recommended business features to my site` and continue button worked for me. Closing this as duplicate of https://github.com/Automattic/wp-calypso/issues/65528, we need to better handle the `plugin_install` permission holistically.

**Comment by cpapazoglou** [comment] 2022-07-28 10:21
Also, Woo Payments is now bundled with woocommerce extensions pdh6GB-1HZ-p2

**Closed as completed by cpapazoglou** 2022-07-28 10:20 UTC
