### ISSUE TITLE
Editor: selecting heading style toggles between heading and paragraph style

### ISSUE THREAD

**Issue by martinremy** [Automattic/wp-calypso#1706] opened 2015-12-16 22:55 UTC
What I did: created a new post that had some headings (Heading 3) and some paragraph text.

What I expected: When I select "Heading 3" for text that is already "Heading 3", that text should remain as "Heading 3".

What actually happened: The text turned into "Paragraph".  I would expect that click to be a no-op, since the style is already Heading 3, but "Heading 3" effectively functions as a toggle between Heading 3 and Paragraph.

I also noticed that in my particular document, Heading 3 was sometimes bold and sometimes not (not with "B" selected, but just appearing bold).

**Comment by designsimply** [comment] 2015-12-17 13:34
> What I expected: When I select "Heading 3" for text that is already "Heading 3", that text should remain as "Heading 3".

I tested at https://www.tinymce.com/ and found the same behavior there. It appears re-selecting the same format again will toggle it on or off by design, see https://github.com/tinymce/tinymce/issues/768

> I also noticed that in my particular document, Heading 3 was sometimes bold and sometimes not (not with "B" selected, but just appearing bold).

This sounds possibly like a case of https://github.com/Automattic/wp-calypso/issues/1601 where the content was copied from another web page or app and may have pulled in some underlying markup along with it when the text was copied. Do you think that might have been the case?

**Comment by designsimply** [comment] 2015-12-17 20:08
I reviewed the original post and found that the first heading was something like:

```
<h3>The First Heading</h3>
```

While the second heading was something like:

```
<h3><span style="font-weight:400;">The Second Heading</span></h3>
```

And that explains why headings were sometimes bold and sometimes not in the WordPress.com editor where a change in font weight is noticeably different in that context. I chatted with @martinremy and confirmed that part of the issue is a duplicate of #1601.

We also discussed https://github.com/tinymce/tinymce/issues/768 and based on that ticket we agreed that re-selecting "Heading 3" is intended to toggle that formatting on/off and so while that behavior does not match other editors such as Pages, it is the intended behavior in TinyMCE.

Closing this as a duplicate, and adding a thank you for reporting the issue and working through the details with me!

**Closed by designsimply** 2015-12-17 20:08 UTC
Labels: Editor, [Type] Bug
