### ISSUE TITLE
People: Edge Browser 404s on widgets.wordpress.com

### ISSUE THREAD

**Issue by joelwills** [Automattic/wp-calypso#2243] opened 2016-01-08 17:42 UTC
Using the latest Edge browser (inPrivate window) on Windows 10, the signup for a new account goes well, but then I get stuck here:

![edge](https://cloud.githubusercontent.com/assets/3228004/12204806/7367f0ce-b5eb-11e5-8ffa-303385906051.PNG)

In the console, the errors are these:

![edge2](https://cloud.githubusercontent.com/assets/3228004/12204810/76962266-b5eb-11e5-949c-6027f172128e.PNG)

Trying to load those URLs directly in Edge whether InPrivate or regular window give a 404 error. 

Note, this works in IE11, including directly loading the URLs, they do not 404 and the flow all worked loading the posts on the new site in Calypso.

**Comment by ebinnion** [comment] 2016-01-08 20:53
I was also able to trigger this in Chrome, so my guess is that this issue may not be related to Edge. However, it is intermittent-ish :disappointed:

**Comment by ebinnion** [comment] 2016-01-11 22:38
@joelwills - In my testing today, I haven't been able to reproduce in Chrome, Safari, or Edge :cry: 

I even checked out a commit from last Friday (although, in all honesty, I just randomly selected one) and was not able to reproduce the issue either.

Would you mind testing again?

**Comment by joelwills** [comment] 2016-01-11 23:07
I just tested again now and cannot replicate either. It almost seemed to be stuck on the sign up screen after submitting but after a few seconds it went through. I can continue to test if you wish?

**Comment by ebinnion** [comment] 2016-01-12 00:06
Yea, I've been noticing how that signup screen seems to be stuck. I believe that's just because of the way we're making the API calls. The other signup/start flows use a loading graphic of sorts that we can probably implement here to make it appear less buggy.

I'll continue to test as I work on other parts of invites. Feel free to test if you'd like, but it's probably not necessary since it's intermittent.

**Comment by ebinnion** [comment] 2016-01-12 19:10
I'm going to go ahead and close this for now as I still haven't been able to reproduce. Feel free to re-open if it is reproduced.

**Closed by ebinnion** 2016-01-12 19:10 UTC
Labels: People Management, [Type] Bug
