### ISSUE TITLE
[Bug]: "Move to widget area" button doesn't work

### ISSUE THREAD

**Issue by mirka** [Automattic/wp-calypso#71866] opened 2023-01-10 14:43 UTC
### Steps to reproduce

Tested with the Twenty Fifteen and Twenty Twenty themes.

1. Add a widget to a widget area.
2. Try to move it to another area using the ["Move to widget area" button](https://wordpress.com/support/widgets/#move-blocks-between-widget-areas) (it looks like a squiggly arrow).

https://user-images.githubusercontent.com/555336/211581296-8a8e22bc-450e-4d3f-bcfd-9f0bfd7cd53b.mp4

### What you expected to happen

The widget to move to the area.

### What actually happened

Nothing happens.

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

Yes, easy to implement

### Workaround details

You can drag the widgets.

**Comment by cuemarie** [comment] 2023-04-12 23:24
📌 ACTIONS
- Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/62545

**Closed as completed by cuemarie** 2023-04-12 23:24 UTC
Labels: Bug, [Pri] Low, Triaged, Block Widgets
