### ISSUE TITLE
Change Authorization header to be more standards based in the API

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#74560] opened 2023-03-17 08:34 UTC
Change the header from `Authorization: Cookie subkey` to `Authorization: X-WPSUBKEY subkey`

**Comment by mashikag** [comment] 2023-03-20 08:37
Duplicate of: https://github.com/Automattic/wp-calypso/issues/74564

**Closed as not planned by mashikag** 2023-03-20 08:37 UTC
Labels: Subscription Management, [SM] API
