### ISSUE TITLE
Product Categories List block encounters error when added as a widget with visibility rule

### ISSUE THREAD

**Issue by wiesenhauss** [Automattic/wp-calypso#62337] opened 2022-03-29 13:32 UTC
### Quick summary

34932041-hc

When used as a widget, the Product Categories List block preview is replaced by an error ("This block has encountered an error and cannot be previewed.") if the user tries to add a visibility rule:

https://user-images.githubusercontent.com/99455043/160619661-9a02ec7d-4b74-4cf2-ae19-63367f68aeb4.mp4

### Steps to reproduce

1. Add Product Categories List block as a widget (Appearance → Widgets)
2. Open block settings
3. Open Advanced and click on "Add new rule" under Visibility

### What you expected to happen

Users should be able to add new visibility rules, with a real-time preview of the block

### What actually happened

Block preview is replaced by an error: "This block has encountered an error and cannot be previewed."
The block can't be used or fixed after that.

### Context

Reported by a user (34932041-hc). I was able to reproduce this on my test site with a different theme and plugins set.

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by vajrasar** [comment] 2022-04-13 18:48
Hey @wiesenhauss thanks for the report. 

I checked and I was able to replicate the issue on my AT WooCommerce site. The issue seems not to be dependent on the theme. 

When the issue pops up (when selecting Visibility Rule from Widget block settings) the following error shows up on the console:

```
react-dom.min.js?ver=5.9.3:1 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Berror%2C%20errorMsg%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at l (react.min.js?ver=5.9.3:1:2112)
    at c (react.min.js?ver=5.9.3:1:2267)
    at Object.toArray (react.min.js?ver=5.9.3:1:9096)
    at v (raw-html.js:25:2)
    at ft (react-dom.min.js?ver=5.9.3:1:43451)
    at Wt (react-dom.min.js?ver=5.9.3:1:50270)
    at ts (react-dom.min.js?ver=5.9.3:1:112276)
    at Fr (react-dom.min.js?ver=5.9.3:1:77758)
    at Dr (react-dom.min.js?ver=5.9.3:1:77686)
    at Rr (react-dom.min.js?ver=5.9.3:1:77549)
```

**Comment by rachelmcr** [comment] 2022-05-09 14:15
I just ran into the same issue while trying to add this widget to my store.

**Comment by Sandkorner** [comment] 2022-11-20 19:34
Hey!

I had this issue in 5727694-zen

Just wanted to ask here if this issue might be resurfaced again. Exact same issue.

**Comment by inaikem** [comment] 2022-11-21 06:05
@Aljullu 👋 Could you take a look at @Sandkorner's nudge above and let us know how we can help resolve the user's issue? 

If there's an interim workaround we can advise them of, please do let us know what it is. Thanks!

**Comment by Aljullu** [comment] 2022-11-21 15:30
Sure, thanks for pinging me, @inaikem!

> Could you take a look at @Sandkorner's nudge above and let us know how we can help resolve the user's issue?

I will need some help setting up the .com site, because after doing so, the option to enable widget visibility controls appears disabled with no option to enable it (the toggle is grayed off).

![imatge](https://user-images.githubusercontent.com/3616980/203093443-a81355bf-0d77-4a8b-9992-a76271573398.png)

So there is no way for me to try to reproduce it right now. :confused: 

@wojtekn, you worked on the previous fix for this issue. Do you have any clues of why it might have resurfaced?

**Comment by inaikem** [comment] 2022-11-22 05:10
Thanks for the reply! Are you referring to a test site above? If so, please go ahead and add my WPcom account as an admin there so I can jump in to review. Sending you a Slack DM now with the details.

@Sandkorner, are you able to replicate this on a test site yourself?

**Comment by wojtekn** [comment] 2022-11-22 08:22
@inaikem I could replicate it on the site with WooCommerce and Storefront theme. I will check it more.

**Comment by jamiepalatnik** [comment] 2022-11-22 23:31
📌 SCRUBBING : RESULT
- Skipped testing this one since this was discussed in comments above and it looks like a fix is already in progress.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Closed as completed** 2022-11-23 08:27 UTC
Labels: Bug, [Pri] Normal, Triaged, WooCommerce, Block Widgets, Build Maintenance

**Comment by wojtekn** [comment] 2022-11-23 08:32
I fixed this issue in the related PR. The fix targets the Jetpack code so that it will be available for Atomic sites according to the deployment schedule (1HpG7-p2).
