### ISSUE TITLE
Submitted comments strip all line feeds / formatting

### ISSUE THREAD

**Issue by gravityrail** [Automattic/wp-calypso#49781] opened 2021-02-05 22:23 UTC
### Steps to reproduce the behavior

1. Go to a blog post in the reader
2. Create a comment with line feeds, dash-bulleted lists, etc.
3. Submit the comment

#### What I expected to happen

My formatting to be preserved

#### What actually happened

All line-feeds are stripped. Reloading the page then shows the proper formatting.

#### Browser / OS version

Chrome 88 on macOS 11.1

**Comment by roo2** [comment] 2023-02-13 02:02
it looks to me like it (now) strips multiple duplicate line feeds but allows one empty line between paragraphs, this is the same as when you reload the page.

I believe this is by design, let's close this. We have talked about a future project to redesign the comments section which may change this behaviour.

**Closed as completed by roo2** 2023-02-13 02:02 UTC
Labels: Bug, [Pri] Normal, [Feature] Reader
