### ISSUE TITLE
Themes: Images Overflowing with Text

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#33769] opened 2019-06-08 15:19 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/theme/radcliffe-2
2. Scroll to "Make it Your Own" 

#### What I expected

The images to be in a row, and not to overlap with the text. 

#### What happened instead

![Screenshot_20190608-161614](https://user-images.githubusercontent.com/43215253/59149099-2dd84e00-8a09-11e9-849a-dc463b1e5bb1.jpg)

#### Browser / OS version

Android 7, Chrome

**Comment by Aurorum** [comment] 2019-12-28 06:08
Related: #38604

**Comment by obenland** [comment] 2021-03-17 23:04
This seems to be fixed now. Please feel free to re-open with updated steps to reproduce if that still happens to you.

**Closed by obenland** 2021-03-17 23:04 UTC
Labels: OSS Citizen, Themes, [Type] Bug
