### ISSUE TITLE
The comment icon says there are comments. In fact, there are not

### ISSUE THREAD

**Issue by bgbg** [Automattic/wp-calypso#16487] opened 2017-07-23 15:15 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/blogs/24832085/posts/3581
2. At the left, there's number 7 besides the "comments" icon
3. However, the comment session on the same page says "NO COMMENTS"

(see the screenshot below)

![image](https://user-images.githubusercontent.com/506547/28500545-d578db00-6fd2-11e7-96a5-4604c2592d65.png)

#### Browser / OS version
Chome on MacOS

#dogfooding

**Comment by mikaelz** [comment] 2017-07-23 15:33
Chromium on Arch Linux looks good
![ss_2017-07-23-17-26-45](https://user-images.githubusercontent.com/454800/28500673-95c72346-6fcc-11e7-8273-de07c6bd7215.jpg)

Also good in Chrome on OSX
![screen shot 2017-07-23 at 17 31 14](https://user-images.githubusercontent.com/454800/28500692-ed5f74e6-6fcc-11e7-82ff-0f0748fdf003.png)

**Comment by bgbg** [comment] 2017-07-23 18:53
Interesting: I clicked the link in my bug report, and was able to see the comments:

![image](https://user-images.githubusercontent.com/506547/28501965-b06b0a54-6ff0-11e7-9600-a8be9b6a59d2.png)


Originally, I arrived at that page from a recommendation. Unfortunately, I can't recall what was the original post that brought me to that page.

**Comment by designsimply** [comment] 2017-07-24 17:54
Closing for now because I was unable to reproduce the problem using the following testing steps:

1. Log in to https://wordpress.com/
1. Go to to the full post view for any WordPress.com post in the Reader, i.e. https://wordpress.com/read/blogs/24832085/posts/3581
1. Click the comment icon in the left sidebar (not the one below the post).
1. Check to see if comments display.

<strong>Result:</strong> all comments displayed as expected.

Please re-open if this comes up again! It may be a timing / caching issue.

**Closed by designsimply** 2017-07-24 17:54 UTC
Labels: Reader, [Type] Bug

**Comment by blowery** [comment] 2017-07-24 18:08
I think this may be a loading issue. We don't appear to have a placeholder; we just show "NO COMMENTS" while we load up the first page of comments..
