### ISSUE TITLE
Theme Switch: Multiple themes don't replace homepage on theme switch  

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#57023] opened 2021-10-14 13:03 UTC
### Quick summary

Affected themes: Zoologist, Quadrat, and Geologist

When I switched to the themes above, the homepage wasn't replaced even I chose the option to replace it.

![zoologist](https://user-images.githubusercontent.com/908665/137322489-4fedfc8c-f970-4b54-83cd-4f2b43b5f157.gif)

cc @ianstewart 

### Steps to reproduce

1. Go to https://wordpress.com/themes/[site_url]
2. Activate a theme other than the three themes listed above.
2. Click one of the three themes to activate it.
3. Choose the option "Replace my homepage content with the ____ homepage."
4. Click the pink-red button to activate.
5. Click the "Edit homepage" button.
6. See the homepage content.

### What you expected to happen

The customer expects the homepage to be replaced with the one from the newly activated theme.

### What actually happened

The homepage stays the same.

### Context

I saw while I was testing something else.

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

All

**Comment by connorhipps** [comment] 2022-12-29 20:04
This issue appears to persist for both Zoologist and Geologist and now also for Zaino. 5823874-zd-woothemes

Quadrat appears to be working as expected.

**Comment by daria2303** [comment] 2023-01-22 15:17
5886771-zd-woothemes

Theme: Muscat

**Comment by sourourn** [comment] 2023-01-24 16:37
Also reported here: #39977200-hc
Zaino theme

**Comment by liviopv** [comment] 2023-04-07 13:19
Archivo:

- [ ] 36904544-hc

**Comment by cuemarie** [comment] 2023-04-13 22:50
This may be the same as

-  https://github.com/Automattic/wp-calypso/issues/75659

@liviopv @sourourn @daria2303 @connorhipps Can y'all check to see if the circumstances of your user reports match the description on #75659 , specifically that the homepage was set to a static page prior to the switch?

**Comment by daria2303** [comment] 2023-04-18 07:03
> that the homepage was set to a static page prior to the switch?

@cuemarie it looks like yes but this is based on the current state, change of this setting doesn't show in Activity Log or Blog RC

**Comment by cuemarie** [comment] 2023-04-19 18:49
Hey @daria2303 ! I'm not quite sure I follow your last message regarding the Activity Log. So far, it seems like the issue here is a duplicate of https://github.com/Automattic/wp-calypso/issues/75659, in which case I'll close this in favor of that one.

Do you see any reason why these need to be separate?

**Comment by daria2303** [comment] 2023-04-23 14:02
@cuemarie I mentioned the Activity Log and Blog RC only because we cannot confirm the state of homepage settings from that time as the changes are not logged in these tools. My report was 3 months ago so it could have been changed by the user.

**Comment by cuemarie** [comment] 2023-04-27 22:12
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate using just the themes alone

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested this on a Simple Site, switching to Muscat theme.  Worked as expected, if the parameters of this existing issue were not in play: 

- https://github.com/Automattic/wp-calypso/issues/75659

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/235002305-15e88365-6b04-4690-999c-5b3af3026ca4.mp4

📌 ACTIONS
- Closed as duplicate of issue #75659

**Closed as completed by cuemarie** 2023-04-27 22:12 UTC
Labels: Bug, [Pri] Normal, Triaged
