### ISSUE TITLE
Plugins: "View version x.x.x details" shows blank screen for outdated plugins

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#60079] opened 2022-01-14 11:38 UTC
### Quick summary

On the plugins page, the link to view the details of an update for an outdated plugin shows a blank screen or an error message to the user.

The console shows the following errors:
![Markup on 2022-01-14 at 11:37:49](https://user-images.githubusercontent.com/14153300/149509570-1df05c0a-d3ec-44dc-b6a3-1265486d7db8.png)

### Steps to reproduce

1. Install an outdated plugin not managed by WordPress.com on an Atomic site
2. Go to My Site > Plugins > Manage Plugins
3. Click on "View version x.x.x details"

### What you expected to happen

The lightbox should show details for the update

### What actually happened

Blank screen or a "WordPress.com couldn't establish a connection" error
![Markup on 2022-01-14 at 11:36:28](https://user-images.githubusercontent.com/14153300/149509435-cf5478fc-daef-4b13-9b50-df422381ff7e.png)

### Context

Customer report 33516812-hc / 4686572-zen

### Simple, Atomic or both?

Atomic

### Browser, operating system and other notes

Tested on Chrome 97 on a Mac 12.0.1

### Reproducibility

Consistent

### Severity

All

**Comment by gcsecsey** [comment] 2022-02-03 12:29
We have a hook that redirects the core plugin install calls to Calypso:
https://github.com/Automattic/wpcomsh/blob/51a665b80c90741041fedba8b040bdbb24269953/feature-plugins/masterbar.php#L247-L254

#60179 has the same root cause. 

We'll need to update this hook to consider more edge cases.

**Comment by cpapazoglou** [comment] 2022-02-24 11:02
Resolved in 824-gh-Automattic/wpcomsh

**Comment by cpapazoglou** [comment] 2022-02-24 13:21
824-gh-Automattic/wpcomsh is now merged and will be deployed today.

**Closed as completed by cpapazoglou** 2022-02-24 13:21 UTC
Labels: Bug, [Pri] Low, [Feature] Plugins, Triaged
