### ISSUE TITLE
Simple payment block - changes not updating on jennistuartartist.com

### ISSUE THREAD

**Issue by sourourn** [Automattic/wp-calypso#34508] opened 2019-07-08 10:21 UTC
#### Summary

User has added some simple payment blocks on their site https://jennistuartartist.com/shop/ . When they re-open the editor and make changes to the simple payment blocks, the changes do not get updated despite clicking to update the page. User is using Safari (Version 12.1.1). 

I was not able to replicate the issue on Safari Version 12.1 or Chrome (Version 75.0.3770.100).
All the changes are being updated on my side. 

As an alternative I asked the user to change something on another block on the same page (ie: paragraph block or heading block) before clicking on Update. User confirmed that all the changes do get updated when they change another block (in addition to the payment block) before clicking Update.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/page/jennistuartartist.com
2. Create a new page / post, add a simple payment block
3. Add a title, price and description to the simple payment block, then click Publish
4. Re-open the page in the editor and edit the payment block's title or description
5. Click on Update to update the changes on the page 

#### What I expected
Changes made on the payment block will display on the live site.

#### What happened instead
Changes do not get displayed on the live site. The old version of the payment block still shows up when you open the live page

#### Browser / OS version
Safari (Version 12.1.1)

#### Screenshot / Video
I was not able to replicate the issue on Safari Version 12.1 or Chrome (Version 75.0.3770.100).
All the changes are being updated on my side. 

![Screen Shot on 2019-07-08 at 11-35-23](https://user-images.githubusercontent.com/39188945/60802971-69864500-a17a-11e9-9cf2-bf1ad86c72ba.png)

![Screen Shot on 2019-07-08 at 11-36-26](https://user-images.githubusercontent.com/39188945/60802989-71de8000-a17a-11e9-969c-e379c789c1e0.png)

However user reported that they were unable to make changes on this page: https://jennistuartartist.com/shop/

#### Context / Source
 #user-report

## Site Info

- URL: jennistuartartist.com
- User: jennistuartartist
- Ticket/Forum/Chat:  13605589-HC and 13607170-HC, following up in 2163553-zen

**Comment by DavidRothstein** [comment] 2019-10-18 20:53
Since this is an old report and not reproducible, I'm going to close it for now.  (Unfortunately there really isn't anything else to do).

If a customer reports something similar in the future, we can handle it as an internal bug report at Automattic rather than here (and the payments team can investigate it then).

**Closed by DavidRothstein** 2019-10-18 20:53 UTC
Labels: Simple Payments
