### ISSUE TITLE
Plans page: Incorrect option to downgrade from lower plan instead of upgrade to higher plans

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#87479] opened 2024-02-15 07:22 UTC
### Quick summary

I noticed that an Admin user who is not a plan subscription owner only sees an option to _Downgrade_ from a lower to higher plan in the plans page. This option is also greyed out (presumably because this Admin user is not the subscription owner).

Take a look here:

![CleanShot 2024-02-15 at 09 14 55](https://github.com/Automattic/wp-calypso/assets/2912202/ec71dc43-a4bf-4a26-ad3e-9b42fe7e6d41)

I was able to reproduce this issue on a site I have Admin access to, but where I am not the plan owner.

### Steps to reproduce

1. Access a site as an Admin, non-subscription owner user;
2. Go to _Upgrades_ > _Plans_;
3. Notice that instead of being presented with buttons to **Upgrade** to a higher plan, the buttons are to **Downgrade** despite the current plan being the WordPress Starter plan.

### What you expected to happen

The call to action buttons should be to **Upgrade** to a higher plan, not **Downgrade**.

### What actually happened

The buttons incorrectly indicate an option to downgrade from a lower to higher plan.

### Impact

Potentially many users

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

I came across this issue when conducting a review of 7742729-zen

**Comment by maciejpilarski** [comment] 2024-02-16 16:38
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue on my test site:
![Markup on 2024-02-16 at 17:36:56](https://github.com/Automattic/wp-calypso/assets/9025643/d5abedf4-b036-428f-a5dd-c8234e6c7ddb)

📌 ACTIONS
– Triaged

**Comment by dzver** [comment] 2024-04-29 11:15
The label is incorrect, however I don't think it's a particularly impactful problem. We can resolve it by changing the label to "Change" instead of "Downgrade".

The issue is that we use `isPlanAvailableForPurchase` for this label and it combines two meanings - the plan is unavailable because it's an unsupported downgrade, and the plan is unavailable because the user is not the site owner.

Sending this to Decepticons with a recommendation to update the button to "Change" or a similar word.

**Comment by southp** [comment] 2024-05-02 08:32
Thanks for the heads up. The same issue was reported by @ddc22 in the past here: https://github.com/Automattic/wp-calypso/issues/76102. I'll bump its priority and triage accordingly.

**Comment by lupus2k** [comment] 2024-07-10 20:16
As part of pb5gDS-3YO-p2, we're aiming to fix/close high-priority issues in [The One Board](https://github.com/orgs/Automattic/projects/391/views/12)
Hey, @aneeshd16, I see you are working on [this PR](https://github.com/Automattic/wp-calypso/pull/92015) that fixes it. Can you update this issue when the PR is merged?

Thanks

**Closed as completed** 2024-08-02 07:33 UTC
Labels: Bug, [Feature] Plans & Upgrades, [Feature Group] WPCOM Store & Purchases, Triaged, Customer report [LEGACY], [Platform] Simple, [Status] Priority Review Triggered, [Product] WordPress.com
