### ISSUE TITLE
Editor: decreasing size on second image of a set of images sets the caption to the caption of the first image

### ISSUE THREAD

**Issue by Luminus** [Automattic/wp-calypso#2665] opened 2016-01-21 17:16 UTC
Steps to reproduce:
1. Create a Page
2. Click on "Add media" button
3. Select 2 images
4. Click "Continue" button
5. Click "Layout" dropdown
6. Select Individual Images
7. Click "Insert" button
8. Click on the second image
9. Click the "-" button in the floating toolbar

**Result:** The caption for the second image is permanently set to the caption of the first image. Increasing or decreasing the size doesn't affect the caption any further.

**Comment by hoverduck** [comment] 2016-04-21 16:57
21Apr16 Bug Scrub

Confirmed this is still a problem, but it doesn't appear to be "permanently set" as indicated in the original issue.  Also note that the first click of the "-" button doesn't actually affect the displayed size of the image, but does change the caption.

![2665-gh-wp-calypso](https://cloud.githubusercontent.com/assets/7233112/14717489/c35d3744-07bf-11e6-8de8-9677c5c1e67a.gif)

**Comment by hoverduck** [comment] 2016-07-18 19:44
#bug-scrub

Confirmed this is still an issue.

**Comment by rachelmcr** [comment] 2017-12-23 16:30
Closing this issue since the Gutenberg image block behavior will supersede this behavior.

#bug-scrub #pre-gutenburg-bug-purge

**Closed by rachelmcr** 2017-12-23 16:30 UTC
Labels: Editor, Media, [Type] Bug
