### ISSUE TITLE
Limited Atomic: Plan information in sidebar doesn't update

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#59834] opened 2022-01-06 22:34 UTC
Removing your subscription on an atomic site leaves the sidebar and calypso assuming you're on a business plan even though you're not. Guess it's checking AT status and making an assumption.

**Comment by JoshuaGoode** [comment] 2022-01-06 23:14
Atomic sites rely on the `jetpack_active_plan` option for the plan info and capabilities.   At least the plan info in the sidebar. 

IIRC, that only syncs up on a daily heartbeat or after a plan upgrade.

For testing, and a workaround for HEs, you can force it to sync up by going to My Site > Jetpack > Dashboard.

**Comment by JoshuaGoode** [comment] 2022-01-06 23:24
A little more context for some of the options.

- `jetpack_active_plan` would definitely be involved in what's changing, or not changing, things in the sidebar and some of the site's capabilities. Waiting for the daily heartbeat or manually syncing it by visiting Jetpack's dashboard is possible but I'm not sure what plan options ya'll are setting.

This issue, in the context of upgrades/renewals/resets, has already been reported: https://github.com/Automattic/wp-calypso/issues/53294#issuecomment-965716158

Other things to keep in mind.

- `at_options` still does a few things.
-  `Atomic_Persistent_Data` is used for some stuff. 

With our current plans and upgrade flows, HEs and users do occasionally encounter issues with each of these options that are similar to what you've reported.

Internal doc for HE workarounds: P9HQHe-14R-p2

**Comment by BogdanUngureanu** [comment] 2022-01-10 16:21
This will be fixed with D71358-code, which is currently in progress (needs really small adjustments).

**Comment by DustyReagan** [comment] 2022-02-01 17:54
It looks like D71358-code will move this issue forward from the back-end, but it still requires a hard refresh to update the plan in the sidebar, so the UI will need some work to improve the user experience. Let's reexamine this issue after the patch lands.

**Comment by BogdanUngureanu** [comment] 2022-02-03 14:56
The patch was deployed in wpcom with r239502-wpcom. Feel free to pick-up the front-end improvement if it's still needed. :)

**Comment by DustyReagan** [comment] 2022-02-03 17:59
Now that D71358-code is applied. The issue is that the plan label in the sidebar doesn't change until the page has a hard refresh. I feel like that is OK in the case of a plan change due to a subscription time-frame trigger, or a change via Store Admin. In other words, I don't feel like we need to constantly check for a plan update. However, when the user personally triggers a plan change, they should see the sidebar update right away to avoid any confusion. See video below.

https://user-images.githubusercontent.com/140841/152400333-85bd3a11-fce1-4566-81f4-d089b16e26a7.mp4

**Comment by obenland** [comment] 2022-02-03 18:06
There are a few occasions where the sidebar should reload in Calypso but doesn't. Like when a comment was moderated and the count in the sidebar doesn't get updated, or a plugin gets activated/deactivated and the menu item it registers doesn't get added/removed.

When Nav Unification was built we stopped shy of iterating on that, I wonder if this effort could be an excuse to start improving that.

[Calypso already uses wordpress hooks](https://github.com/Automattic/wp-calypso/search?q=doAction), maybe we could add `doAction` calls in situations where we need the sidebar to refresh and create listeners that act on that?

**Comment by DustyReagan** [comment] 2022-02-03 22:25
> [Calypso already uses wordpress hooks](https://github.com/Automattic/wp-calypso/search?q=doAction), maybe we could add doAction calls in situations where we need the sidebar to refresh and create listeners that act on that?

Sounds like a good idea.

I noticed when the user upgrades a plan the sidebar updates correctly. It's just not updating on downgrades. What's causing the sidebar to reload on upgrades?

**Comment by obenland** [comment] 2022-02-03 23:01
>What's causing the sidebar to reload on upgrades?

I'm not sure! Does it do a full page reload maybe?

**Comment by DustyReagan** [comment] 2022-02-03 23:30
> Does it do a full page reload maybe?

It looks like it happens client side to me. 🤔 I wonder because it may be that we just need to apply the same trigger on downgrades.

https://user-images.githubusercontent.com/140841/152446184-819ba55d-730c-4a3c-835e-019898651fa4.mp4

**Comment by DustyReagan** [comment] 2022-02-04 20:41
Good explanation of what's going on here. p1643930384084729-slack-C02DQP0FP

~~I drafted a [PR to address this issue here](https://github.com/Automattic/wp-calypso/pull/60861). But I'm a bit concerned with changing the signature of `clearPurchases()` and `removePurchase()` and would like some feedback on that.~~

~~There is also an alternative solution of updating the sidebar on `fetchSitePurchases()`. I [drafted PR here](https://github.com/Automattic/wp-calypso/pull/60857). That fixes this issue with minimum code change, but refreshing the sidebar every time `fetchSitePurchases()` runs could be over doing it.~~

[Better PR here](https://github.com/Automattic/wp-calypso/pull/60889) that updates during `clearPurchases()` and `removePurchase()` with a cleaner way at getting at siteId.

**Closed as completed** 2022-02-07 23:32 UTC
