### ISSUE TITLE
RSS: RSS feed notifying of new post, but no content is present.

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-calypso#46535] opened 2020-10-16 18:34 UTC
#### What I expected

From a contact at Feedly:

```
Hello,
I work at Feedly. It's been awhile since we've communicated so I hope this email still works. Lately, we've been receiving wordpress push requests with no content. E.g. for example, for:
https://newenglandgardenandthread.wordpress.com/feed/
Feedly received a content push request from wordpress at 10/12/2020, 4:00:13 AM pacific time, with 1 new article, but no content in the article. However the RSS feed itself does have content. Could you put me in touch with someone in your technical team so we could track down the problem?
Thanks
Kireet
```
I have requested additional examples to determine if this is a WordPress.com-specific issue, or wider spread, and will update when/if those arrive.

#117491-vip

**Comment by chrisfromthelc** [comment] 2020-10-16 19:16
A reply with more sites from wordpress.com.

```
It's pretty hard for us to check for non *.wordpress.com sites, but we are having issues with multiple *.wordpress.com sites. Here are a few more examples (i apologize if some content is nsfw):

https://fairweatherhouseandgallery.wordpress.com/feed/
https://kirjakoi.wordpress.com/feed/
https://jumpsmanracing.wordpress.com/feed/
https://tiza4251.wordpress.com/feed/
https://blogdelerolico.wordpress.com/feed/
```

**Comment by kireet** [comment] 2020-10-16 21:25
Here is a sample push request body. Notice the article content is wrapped in a `<script>` tag?

```
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
        xmlns:content="http://purl.org/rss/1.0/modules/content/"
        xmlns:wfw="http://wellformedweb.org/CommentAPI/"
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        xmlns:atom="http://www.w3.org/2005/Atom"
        xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
        xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
        xmlns:georss="http://www.georss.org/georss" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#" >

<channel>
        <title>Governo Bolsonaro dá novo passo em plano de privatização &#8211; POLÍTICA EM ROTA</title>
        <atom:link href="https://poliseticathi.wordpress.com/feed/" rel="self" type="application/rss+xml" />
        <link>https://poliseticathi.wordpress.com</link>
        <description>De tanto ver triunfar as nulidades; de tanto ver prosperar a desonra, de tanto ver crescer a injustiça. De tanto ver agigantarem-se os poderes nas mãos dos maus, o homem chega a desanimar-se da virtude, a rir-se da honra e a ter vergonha de ser honesto. Rui Barbosa </description>
        <lastBuildDate>Fri, 16 Oct 2020 21:21:54 +0000</lastBuildDate>
        <language>en</language>
        <sy:updatePeriod>
        hourly  </sy:updatePeriod>
        <sy:updateFrequency>
        1       </sy:updateFrequency>
        <generator>http://wordpress.com/</generator>
<image>
                <url>http://s0.wp.com/i/buttonw-com.png</url>
                <title>Governo Bolsonaro dá novo passo em plano de privatização &#8211; POLÍTICA EM ROTA</title>
                <link>https://poliseticathi.wordpress.com</link>
        </image>
                <item>
                <title>Governo Bolsonaro dá novo passo em plano de privatização</title>
                <link>https://poliseticathi.wordpress.com/2020/10/16/governo-bolsonaro-da-novo-passo-em-plano-de-privatizacao/</link>
                                        <comments>https://poliseticathi.wordpress.com/2020/10/16/governo-bolsonaro-da-novo-passo-em-plano-de-privatizacao/#respond</comments>
                
                <dc:creator><![CDATA[Antgarcia]]></dc:creator>
                <pubDate>Fri, 16 Oct 2020 21:21:54 +0000</pubDate>
                                <category><![CDATA[Uncategorized]]></category>
                <guid isPermaLink="false">https://poliseticathi.wordpress.com/?p=21446</guid>

                                        <description><![CDATA[]]></description>
                                                                                <content:encoded><![CDATA[<script class='o2-data' id='o2-data-21446' data-post-id='21446' type='application/json' style='display:none'>[{"type":"post","id":21446,"postID":21446,"cssClasses":"post post-21446 type-post status-publish format-standard hentry category-uncategorized author-polisgar p2020-unread-post","parentID":0,"titleRaw":"Governo Bolsonaro d\u00e1 novo passo em plano de privatiza\u00e7\u00e3o","titleFiltered":"Governo Bolsonaro d\u00e1 novo passo em plano de&nbsp;privatiza\u00e7\u00e3o","titleWasGeneratedFromContent":false,"contentRaw":"<!-- wp:image {\"id\":21447,\"sizeSlug\":\"large\",\"linkDestination\":\"media\"} -->\n<figure class=\"wp-block-image size-large\"><a href=\"https:\/\/poliseticathi.files.wordpress.com\/2020\/10\/screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99.png\"><img src=\"https:\/\/poliseticathi.files.wordpress.com\/2020\/10\/screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99.png?w=975\" alt=\"\" class=\"wp-image-21447\" \/><\/a><\/figure>\n<!-- \/wp:image -->\n\n<!-- wp:paragraph -->\n<p>O ministro das Comunica\u00e7\u00f5es, F\u00e1bio Faria, entregou nesta ter\u00e7a-feira (14) ao ministro da Secretaria Geral da Presid\u00eancia da Rep\u00fablica, Jorge Oliveira, a proposta que libera o processo de privatiza\u00e7\u00e3o dos Correios. O texto \u00e9 a minuta de um projeto de lei que dever\u00e1 ser apresentado ao Congresso Nacional ap\u00f3s an\u00e1lise da Subchefia para Assuntos Jur\u00eddicos do governo e da Casa Civil.&nbsp;<\/p>\n<!-- \/wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>A medida permite a explora\u00e7\u00e3o dos servi\u00e7os postais pela iniciativa privada e representa um novo passo pol\u00edtico da gest\u00e3o Bolsonaro na lida com a estatal, que est\u00e1 entre os principais pontos da agenda de privatiza\u00e7\u00f5es do ministro da Economia, Paulo Guedes. O projeto tamb\u00e9m prev\u00ea a substitui\u00e7\u00e3o da Ag\u00eancia Nacional de Telecomunica\u00e7\u00f5es (Anatel) pela chamada Ag\u00eancia Nacional de Comunica\u00e7\u00f5es (Anacom), que passar\u00e1 a ser respons\u00e1vel pela regula\u00e7\u00e3o tamb\u00e9m dos servi\u00e7os postais, caso a medida seja aprovada. &nbsp;<\/p>\n<!-- \/wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p><strong>Entenda:&nbsp;<\/strong>Por que o projeto de privatiza\u00e7\u00e3o dos Correios n\u00e3o faz sentido<\/p>\n<!-- \/wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>A proposta de venda da companhia \u00e9 avaliada tecnicamente pelo governo desde agosto deste ano, quando teve in\u00edcio um estudo de modelagem de neg\u00f3cio que est\u00e1 sob a consultoria do BNDES, mas a estatal j\u00e1 estava na mira da agenda neoliberal da gest\u00e3o Bolsonaro h\u00e1 mais tempo.&nbsp;Segundo o ministro F\u00e1bio Faria, a ideia&nbsp;\u00e9 tentar vender a companhia at\u00e9 2021.&nbsp;<\/p>\n<!-- \/wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>A privatiza\u00e7\u00e3o dos Correios \u00e9 considerada bastante impopular e tem entre seus cr\u00edticos parlamentares de oposi\u00e7\u00e3o, especialistas e movimento sindical que re\u00fane trabalhadores da companhia.<\/p>\n<!-- \/wp:paragraph -->\n\n<!-- wp:heading -->\n<h2>BRASIL DE FATO<\/h2>\n<!-- \/wp:heading -->","contentFiltered":"<figure class=\"wp-block-image size-large\"><a href=\"https:\/\/poliseticathi.files.wordpress.com\/2020\/10\/screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99.png\"><img data-attachment-id=\"21447\" data-permalink=\"https:\/\/poliseticathi.wordpress.com\/screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99\/\" data-orig-file=\"https:\/\/poliseticathi.files.wordpress.com\/2020\/10\/screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99.png\" data-orig-size=\"975,654\" data-comments-opened=\"1\" data-image-meta='{\"aperture\":\"0\",\"credit\":\"\",\"camera\":\"\",\"caption\":\"\",\"created_timestamp\":\"0\",\"copyright\":\"\",\"focal_length\":\"0\",\"iso\":\"0\",\"shutter_speed\":\"0\",\"title\":\"\",\"orientation\":\"0\"}' data-image-title=\"screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99\" data-image-description=\"\" data-medium-file=\"https:\/\/poliseticathi.files.wordpress.com\/2020\/10\/screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99.png?w=300\" data-large-file=\"https:\/\/poliseticathi.files.wordpress.com\/2020\/10\/screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99.png?w=940\" src=\"https:\/\/poliseticathi.files.wordpress.com\/2020\/10\/screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99.png?w=975\" alt=\"\" class=\"wp-image-21447\" srcset=\"https:\/\/poliseticathi.files.wordpress.com\/2020\/10\/screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99.png 975w, https:\/\/poliseticathi.files.wordpress.com\/2020\/10\/screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99.png?w=150 150w, https:\/\/poliseticathi.files.wordpress.com\/2020\/10\/screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99.png?w=300 300w, https:\/\/poliseticathi.files.wordpress.com\/2020\/10\/screenshot_2020-10-16-reuniao-bolsonaro-ppi-jpg-webp-image-984-c397-660-pixels-scaled-99.png?w=768 768w\" sizes=\"(max-width: 975px) 100vw, 975px\"><\/a><\/figure><p>O ministro das Comunica\u00e7\u00f5es, F\u00e1bio Faria, entregou nesta ter\u00e7a-feira (14) ao ministro da Secretaria Geral da Presid\u00eancia da Rep\u00fablica, Jorge Oliveira, a proposta que libera o processo de privatiza\u00e7\u00e3o dos Correios. O texto \u00e9 a minuta de um projeto de lei que dever\u00e1 ser apresentado ao Congresso Nacional ap\u00f3s an\u00e1lise da Subchefia para Assuntos Jur\u00eddicos do governo e da Casa Civil.\u00a0<\/p>\n\n\n\n<p>A medida permite a explora\u00e7\u00e3o dos servi\u00e7os postais pela iniciativa privada e representa um novo passo pol\u00edtico da gest\u00e3o Bolsonaro na lida com a estatal, que est\u00e1 entre os principais pontos da agenda de privatiza\u00e7\u00f5es do ministro da Economia, Paulo Guedes. O projeto tamb\u00e9m prev\u00ea a substitui\u00e7\u00e3o da Ag\u00eancia Nacional de Telecomunica\u00e7\u00f5es (Anatel) pela chamada Ag\u00eancia Nacional de Comunica\u00e7\u00f5es (Anacom), que passar\u00e1 a ser respons\u00e1vel pela regula\u00e7\u00e3o tamb\u00e9m dos servi\u00e7os postais, caso a medida seja aprovada. \u00a0<\/p>\n\n\n\n<p><strong>Entenda:\u00a0<\/strong>Por que o projeto de privatiza\u00e7\u00e3o dos Correios n\u00e3o faz sentido<\/p>\n\n\n\n<p>A proposta de venda da companhia \u00e9 avaliada tecnicamente pelo governo desde agosto deste ano, quando teve in\u00edcio um estudo de modelagem de neg\u00f3cio que est\u00e1 sob a consultoria do BNDES, mas a estatal j\u00e1 estava na mira da agenda neoliberal da gest\u00e3o Bolsonaro h\u00e1 mais tempo.\u00a0Segundo o ministro F\u00e1bio Faria, a ideia\u00a0\u00e9 tentar vender a companhia at\u00e9 2021.\u00a0<\/p>\n\n\n\n<p>A privatiza\u00e7\u00e3o dos Correios \u00e9 considerada bastante impopular e tem entre seus cr\u00edticos parlamentares de oposi\u00e7\u00e3o, especialistas e movimento sindical que re\u00fane trabalhadores da companhia.<\/p>\n\n\n\n<h2>BRASIL DE FATO<\/h2>","permalink":"https:\/\/poliseticathi.wordpress.com\/2020\/10\/16\/governo-bolsonaro-da-novo-passo-em-plano-de-privatizacao\/","unixtime":1602883314,"unixtimeModified":1602883314,"entryHeaderMeta":"","linkPages":"","footerEntryMeta":"","tagsRaw":"","tagsArray":[],"loginRedirectURL":"https:\/\/poliseticathi.wordpress.com\/wp-login.php?redirect_to=https%3A%2F%2Fpoliseticathi.wordpress.com%2F2020%2F10%2F16%2Fgoverno-bolsonaro-da-novo-passo-em-plano-de-privatizacao%2F","hasPrevPost":true,"prevPostTitle":"Multa, carro e tr\u00e2nsito unem Bolsonaro ao eleitor que a esquerda&nbsp;abandonou","prevPostURL":"https:\/\/poliseticathi.wordpress.com\/2020\/10\/16\/multa-carro-e-transito-unem-bolsonaro-ao-eleitor-que-a-esquerda-abandonou\/","hasNextPost":false,"nextPostTitle":"","nextPostURL":"","commentsOpen":true,"is_xpost":false,"editURL":null,"postActions":"\t\t\t<nav class=\"o2-dropdown-actions o2-post-actions\">\n\t\t\t\t<button\n\t\t\t\t\taria-haspopup=\"true\"\n\t\t\t\t\taria-expanded=\"false\"\n\t\t\t\t\taria-label=\"Post Actions\"\n\t\t\t\t\tclass=\"p2020-ellipsis-button\"\n\t\t\t\t\tdata-tippy-menu-trigger\n\t\t\t\t>\n\t\t\t\t<\/button>\n\t\t\t\t<div data-tippy-menu-content hidden>\n\t\t\t\t\t<ul class=\"p2020-ellipsis-menu\" role=\"menu\">\t\t\t\t<li role=\"menuitem\">\n\t\t\t\t\t<a href=\"#\"  title=\"Mark as seen\" class=\"seen mark-as-seen\" data-action=\"seen\" data-actionstate=\"default\">\n\t\t\t\t\t\tMark as seen\n\t\t\t\t\t<\/a>\n\t\t\t\t<\/li>\t\t\t\t<li role=\"menuitem\">\n\t\t\t\t\t<a href=\"https:\/\/wp.me\/p2zNN0-5zU\"  title=\"Shortlink\" class=\"genericon genericon-link short-link o2-short-link\" data-action=\"shortlink\" data-actionstate=\"default\">\n\t\t\t\t\t\tShortlink\n\t\t\t\t\t<\/a>\n\t\t\t\t<\/li>\t\t\t\t<\/ul>\n\t\t\t<\/div>\n\t\t<\/nav>","comments":[],"postFormat":"standard","postMeta":{"isSticky":false},"postTerms":{"category":[{"label":"Uncategorized","count":3896,"link":"https:\/\/poliseticathi.wordpress.com\/category\/uncategorized\/"}],"post_format":[]},"pluginData":[],"isPage":false,"mentions":["all"],"mentionContext":"","isTrashed":false,"userLogin":"polisgar","userNicename":"polisgar","isUnread":true}]</script>
]]></content:encoded>
                                        
                                        <wfw:commentRss>https://poliseticathi.wordpress.com/2020/10/16/governo-bolsonaro-da-novo-passo-em-plano-de-privatizacao/feed/</wfw:commentRss>
                        <slash:comments>0</slash:comments>
                
                
                        </item>
        </channel>
</rss>
```

**Comment by kireet** [comment] 2020-10-16 21:27
When can I expect a fix for this? It's causing major usability issues for Feedly users. I don't want to disable Push updates though, as that will cause us to greatly increase our requests to wordpress.com and may trip some request throttling limits?

**Comment by edwk** [comment] 2020-10-19 17:58
Hello @chrisfromthelc @cathymcbride this bug is impacting from sources that have very big follower on Feedly and putting a lot of stress on our support team. Have you had similar issues in the past? Do you have a sense of how quickly a bug like this can be fixed? Thanks! cc @kireet

**Comment by cathymcbride** [comment] 2020-10-19 20:17
@edwk It's near the top of our prioritized backlog right now, but I can't really predict how long it will take to get fixed.

**Comment by obenland** [comment] 2020-10-19 22:30
It looks like we found the cause and @naxoc and @lezama should have a fix in place by eod tomorrow. 
p1603141817235900-slack-C9UMZ71QD

**Comment by kwight** [comment] 2020-10-20 14:47
The presumed fix for this was committed about two hours ago – @edwk @kireet please confirm for us that things look good on your side 👍

**Comment by kireet** [comment] 2020-10-20 16:43
Things look good on our side. Thanks for the quick response!

**Closed** 2020-10-21 14:28 UTC
Labels: Posts, [Pri] High, [Type] Bug
