### ISSUE TITLE
Gutenberg: Categories added in the editor sometimes result in publishing errors.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#45758] opened 2020-09-18 19:02 UTC
Reported in p1600445510031400-slack-automattic

When adding multiple categories to a new post in Gutenberg, publishing the post can appear to fail with an error:

![image](https://user-images.githubusercontent.com/349751/93634836-1dea4080-f9a6-11ea-8334-7ac660e6bc90.png)

The post does indeed publish, and thecategories are created, but the categories will not be assigned to the post, and the editor UI will insist the post is not published (continuing to present the Publish button). The user can add the existing categories upon re-editing the post.

The behaviour is not consistent (I've replicated a few times, but sometimes it all published fine), and I can't replicate on a JN site (with nor without the Gutenberg plugin active), so it may be WordPress.com-specific.

**Comment by kwight** [comment] 2020-09-18 19:03
@Automattic/good-mountain Does this sound familiar for anything Gutenberg 9.0 related?

**Comment by sirreal** [comment] 2020-09-21 10:34
I can confirm that this was reported for a Simple site after the Gutenberg 9 upgrade. However, this doesn't sound familiar. The release went very smoothly and we haven't heard about any significant issues.

**Comment by goblinartificer** [comment] 2020-09-28 04:56
I'm not sure what the cause is, but this occurs on simple sites in:

- 3347189-zen
- 3293169-zen
- 3320934-zen
- 3305529-zen
- 3340568-zen
- 3291890-zen
- 3311669-zen
- 3330418-zen
- 3292703-zen
- 3316381-zen
- 3293488-zen
- 3301764-zen
- 3300156-zen
- 3300479-zen

And at least a few chats, but those are harder to dig up!

**Comment by chaitanyamsv** [comment] 2020-09-28 07:17
4448707-hc and 3254656-zen - `Scheduling failed. Sorry, you are not allowed to edit this post.`

[A forum post: ](https://wordpress.com/forums/topic/red-line-says-updating-failed-sorry-you-are-not-allowed-to-edit-this-post/): `Updating failed. Sorry, you are not allowed to edit this post.`

and a few other user reports: 24331738-hc, 24325923-hc, 3354948-zen

**Comment by cathymcbride** [comment] 2020-09-29 13:36
Similar to https://github.com/Automattic/wp-calypso/issues/45881. Let's see if that fixes it, and if it doesn't we'll bump this one higher in pri.

**Comment by rinazrina** [comment] 2020-11-12 03:47
Another report: #25448289-hc 
They're seeing the error when publishing a post.

**Comment by ktyfuller604** [comment] 2020-11-13 15:18
Another report: #21174578-hc
An error occurred when publishing - removing categories and tags then publishing resolved the issue.

**Comment by scosgro** [comment] 2020-11-18 20:44
Another report in #372787-hc 
Firefox 83.0, Windows 10.

**Comment by jonnyruzek** [comment] 2020-11-19 20:14
25760545-hc

**Comment by jonnyruzek** [comment] 2020-11-19 21:51
24961915-hc

**Comment by adelineyaw** [comment] 2020-11-21 22:28
25460211-hc

**Comment by joaodante** [comment] 2020-11-23 22:49
Another report 25850405-HC

**Comment by yashitamittal11** [comment] 2020-12-01 07:24
Another one- #6886957-hc

**Comment by dolgelukkig** [comment] 2020-12-21 15:19
Another one here: [26485238-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=26485238)

**Comment by JoshuaGoode** [comment] 2020-12-22 22:06
Similar to a much older report: https://github.com/Automattic/wp-calypso/issues/36274

**Comment by yashitamittal11** [comment] 2021-01-05 07:17
Another one- #3616678-zen

**Comment by cathymcbride** [comment] 2021-01-05 14:15
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/36274 - which I have moved up in the priority list.

**Closed by cathymcbride** 2021-01-05 14:15 UTC
Labels: Editor, [Pri] Normal, [Type] Bug
