### ISSUE TITLE
FSE, atomic: underline cannot be turned off

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#66262] opened 2022-08-04 13:54 UTC
### Quick summary

Navigation block items are underlined by default despite the fact that it is not set in the block settings. It is not possible to remove the underline. Our doc describes it differently: https://wordpress.com/support/full-site-editing/theme-blocks/navigation-block/#block-settings-navigation-block

### Steps to reproduce

1) Add Navigation block to the FSE theme on atomic site(I checked Byrne, Archeo and Remote)
2) Try to turn off underline like described in our doc https://wordpress.com/support/full-site-editing/theme-blocks/navigation-block/#block-settings-navigation-block

### What you expected to happen

- menu items are underlined according to the block settings
- it is possible to remove underline

### What actually happened

- underline displays even if the setting is off
- not possible to remove underline

### Context

https://user-images.githubusercontent.com/11535091/182865066-2170f33a-ca54-40d6-bafe-6fbdeb31a008.mov

5452099-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

checked Byrne, Archeo, Remote

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

header .wp-block-navigation__container li a {
	text-decoration: none;
}

**Comment by Joshgrygiel** [comment] 2022-08-09 16:55
📌 SCRUBBING
- Tested on P2 - N/a
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted - Np
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- While testing the Byrne theme on Simple / AT testing sites, I was unable to reproduce the issue as the underline decoration seemed to correctly toggle when saved on my end:


https://user-images.githubusercontent.com/88345647/183711240-3d7d40e9-194d-443e-b439-70be03e22175.mov



📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)


📌 Message to Author
- Hey @daria2303 after testing the navigation block on the Byrne theme, I was unable to actually reproduce the underline issue. Is there any step I may have missed in the video or is there a different workflow to replicating this issue? Thank you!

**Closed as completed by Joshgrygiel** 2022-08-09 16:55 UTC
Labels: Bug, [Pri] Normal, Navigation, Triaged, [Feature] Full Site Editor, [Platform] Atomic

**Comment by daria2303** [comment] 2022-08-10 07:04
@Joshgrygiel  thank you for checking. I am not able to reproduce it anymore on the same sites, the underline is gone. I suspect it was solved within the Gutenberg update.
