### ISSUE TITLE
Editor Preview - Revert #40388 once core Iframe change is ready.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#43818] opened 2020-06-30 23:14 UTC
Once https://github.com/WordPress/gutenberg/pull/21102 lands in core, the fix for the editor preview added in #40388 will no longer be necessary and can be reverted.

**Comment by sirreal** [comment] 2020-07-03 13:38
Duplicate of #43886

**Closed by sirreal** 2020-07-03 13:38 UTC
