### ISSUE TITLE
Block pattern previews don't load consistently and show text only, no thumbnails

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#55854] opened 2021-08-31 08:23 UTC
### Steps to Reproduce

1. Create a new post or page
2. Go to insert a Block Pattern
3. Select Gallery or Contact category from the drop-down

### What I expected to happen

All preview thumbnails for all patterns should load, starting from the top and going down

### What actually happened

The first several pattern previews never load, while some lower down in the list do

<img width="602" alt="Markup 2021-08-31 at 09 18 38" src="https://user-images.githubusercontent.com/51966986/131468515-611ece9b-32ad-4d16-bc6d-4f66c5c42897.png">

### Context

Seen in multiple customer interactions and personal experience

### Operating System

macOS

### OS Version

11.5.2

### Browser

Firefox

### Browser Version(s)

91

### Simple/Atomic

Simple, Atomic

### Number of Users Impacted

Most users (>50%)

### Reproducibility

Consistent

**Comment by Robertght** [comment] 2021-09-08 08:52
Thank you for reporting this @philnick206 ! I can see this might be a core Gutenberg issue here:

https://github.com/WordPress/gutenberg/issues/29436

@Automattic/flow-patrol-create  is this something that you can look into as well?

**Comment by zyousafi** [comment] 2022-05-27 08:53
Unable to reproduce this on an Atomic or Simple site:

1. Simple [site](https://wordpress.com/post/freeplantestsitezyousafi.wordpress.com/68) with the **Blockbase** theme active: https://d.pr/i/DsciQ2
2. Atomic [site](https://atbusinessplantestsitezyousafi.wpcomstaging.com/wp-admin/post.php?post=139&action=edit) with the **Heiwa** theme active: https://d.pr/i/g9NOCL

Closing this issue for now 🙂

**Closed as completed by zyousafi** 2022-05-27 08:53 UTC
Labels: Bug, [Pri] Normal
