### ISSUE TITLE
"Remove this site banner with a paid plan" ad still visible on site despite having a paid plan

### ISSUE THREAD

**Issue by ckmccoy2** [Automattic/wp-calypso#71467] opened 2022-12-22 17:46 UTC
### Quick summary

In 38989900-hc, user is still seeing a "Remove this site banner with a paid plan" ad banner despite having a paid plan on site. It seems that they had accidentally initiated a chargeback for the plan, but a previous HE was able to fix that by updating `Plan sticker fix` in BRC. 

User returned with the same issue. Resolved it by removing plan and adding it again.

### Steps to reproduce

Wasn't able to reproduce as this may involve initiating a chargeback

### What you expected to happen

No ad banner to be present

### What actually happened

Ad banner present, see interaction.

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

None

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Remove and re-add the plan in SA

**Comment by zachspears** [comment] 2022-12-29 01:32
Closing as I am unable to reproduce (possibly due to chargeback being required for testing). Please reopen this issue if there are any additional reports.

**Closed as completed by zachspears** 2022-12-29 01:32 UTC
Labels: Bug, [Pri] Low, Triaged, [Platform] Simple
