### ISSUE TITLE
Group Block: Wide Width and Full Width Options Missing in the Site Editor Only

### ISSUE THREAD

**Issue by sharonlaker19** [Automattic/wp-calypso#73527] opened 2023-02-19 06:40 UTC
### Quick summary

The setting to make a Group block `wide width`, `full width`, and `none` are missing from the Site Editor only, but show up in an individual post or page. 

WORKAROUND: Recommend that the user sets a preferred width manually using the layout settings https://wordpress.com/support/wordpress-editor/blocks/group-block/#layout-settings

### Steps to reproduce

1. On any FSE theme, go to Appearance → Editor.
2. Click to edit a template with the Group block in it.
3. Click on the Group block in the Site Editor.
4. The toolbar that appears on top of the Group block will not have the settings for `wide width`, `full width`, and `none`

![group block editor](https://user-images.githubusercontent.com/71630911/219932919-dd845010-b084-412a-b574-66764e8c4d78.jpg)

5. On the same site + theme, edit an individual post or page with the Group block in it.
6. Click on the Group block.
7. You will see the settings for `wide width`, `full width`, and `none` appear in the toolbar as expected. 

![group block page](https://user-images.githubusercontent.com/71630911/219932988-e05899d2-e34d-4e43-ad40-91cc62fae2e4.jpg)

### What you expected to happen

I expected the toolbar that appears on top of the Group block when you click on it to have the settings for `wide width`, `full width`, and `none` both in an individual page and the Site Editor.

### What actually happened

The toolbar that appears on top of the Group block when you click on it to has the settings for `wide width`, `full width`, and `none` only in an individual page but not the Site Editor.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

**Comment by kavyagokul** [comment] 2023-03-16 10:43
📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/73417

**Closed as completed by kavyagokul** 2023-03-16 10:43 UTC
Labels: Bug, [Pri] Normal, Triaged
