### ISSUE TITLE
Sites page: stats never finish loading for site without stats

### ISSUE THREAD

**Issue by wojtekn** [Automattic/wp-calypso#75072] opened 2023-03-29 12:24 UTC
### Quick summary

We display a small chart showing stats on the Sites page when it's displayed in the table view. For sites that don't have stats enabled, we always display a loading indicator.

![Screenshot 2023-03-29 at 14 16 28](https://user-images.githubusercontent.com/727413/228534839-10960fda-7944-4bab-8933-3482f37b470a.png)

### Steps to reproduce

1. Create a site that doesn't support stats e.g. eCommerce Trial
2. Load the Sites page and check the site on the list

### What you expected to happen

There is no stats chart.

### What actually happened

There is a stats loading indicator that always remains visible.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Request to `/rest/v1.1/sites/$blog_id/stats/insights` endpoint fails with 404 and "This blog does not have the Stats module enabled" message.

**Comment by cuemarie** [comment] 2023-04-04 17:43
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain* 
- Tested on AT: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated the issue with an eCommerce Trial site. The "Loading Chart..." never loads or stops.

**AT Example**
![Screen Capture on 2023-04-04 at 10-38-07](https://user-images.githubusercontent.com/27249804/229873494-0184fdd7-f305-434d-83e1-fc69ca099892.gif)

📌 ACTIONS
- Assigned to Build

**Comment by danielbachhuber** [comment] 2023-04-10 11:35
@javierarce Can you provide some design direction for what we might want to show instead?

**Comment by javierarce** [comment] 2023-04-12 11:38
We could show a flat graph and the reason for the lack of stats in the tooltip (e.g.: "Stats disabled for staging sites" or "Staging stats off") 

![Image](https://user-images.githubusercontent.com/4933/231445011-90f7c7ef-e65f-4efe-8a78-ee03046ce4f8.png)

**Comment by javierarce** [comment] 2023-04-12 11:47
On second thought, it's probably important to indicate clearly that the stats are disabled… I'll design something for this.

**Comment by javierarce** [comment] 2023-04-12 12:07
Here's another idea: we could show a badge and a InfoPopover with an explanation that appears on hover.

Red is more noticeable, and if the user has several sites without stats, it could look like their sites are broken, so it's probably better to go with the gray version.

![Image](https://user-images.githubusercontent.com/4933/231450859-baf1e9db-b8a4-4c8a-9dcb-3fe38e71d051.png)

**Comment by danielbachhuber** [comment] 2023-04-12 12:12
@javierarce I like the gray 'Stats off' label. Nice work 👏

**Comment by katinthehatsite** [comment] 2023-05-09 08:51
I ❤️ this design @javierarce - I will work on it this week!

**Comment by katinthehatsite** [comment] 2023-05-09 10:41
Hi @javierarce and @danielbachhuber - I was testing this today and noticed that the stats loading bar/ behaviour happens in a few cases:

* **issue 1** on E-commerce Trial (as reported in the issue) - should I also use the same wording in the InfoPopover with the `stats are disabled for staging sites` even though it is not an **actual** staging site? I can see the wording possibly causing confusion with the staging sites feature on **Hosting Configuration** page?
* **issue 2:** on **some** staging sites:
<img width="1305" alt="Screenshot 2023-05-09 at 12 21 34 PM" src="https://github.com/Automattic/wp-calypso/assets/25575134/2cd4794d-9d55-463a-8df8-c07d00247132">

In that case, the wording `stats are disabled for staging sites` makes sense but then the stats module looks like this when you access it from `https://wordpress.com/stats/day/{site}`:

<img width="1277" alt="Screenshot 2023-05-09 at 12 26 08 PM" src="https://github.com/Automattic/wp-calypso/assets/25575134/51605896-3748-4fdc-8425-d1218fd5727f">

Since the module for stats is present, I am not sure it makes sense to say `Stats off` or otherwise, it would need to be hidden from `https://wordpress.com/stats/day/{site}`.This probably should be a different issue as this happens only when the parent site does not have any stats. Once the parent site has stats and you create a new staging site from it, the staging stats look correct in the module and on the site management page. For this case, should I apply this change to all staging sites or should I apply this change only to the staging sites created out of the parent site that does not have any stats?

**UPDATE ON ISSUE 2:**  I was trying to reproduce the behavior once again but could not trigger it so it might have been a glitch. To confirm, we are applying this change only to sites that don't support stats or also staging sites?

What do you think?

**Comment by javierarce** [comment] 2023-05-10 11:46
> issue 1 on E-commerce Trial (as reported in the issue) - should I also use the same wording in the InfoPopover with the stats are disabled for staging sites even though it is not an actual staging site? I can see the wording possibly causing confusion with the staging sites feature on Hosting Configuration page?

In this case the message inside the tooltip could be: "Stats aren't available on this plan".

**Closed as completed** 2023-05-23 10:36 UTC
Labels: Bug, [Feature] Stats, [Pri] Normal, Requires Design Library Update, Triaged, [Platform] Atomic, Sites Management Page
