### ISSUE TITLE
Podcast Player Block not updating on simple site upon page update/save

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#51259] opened 2021-03-21 16:46 UTC
The Podcast player on the homepage doesn't update automatically when they save a new podcast post.

Editor looks correct:

<img width="571" alt="Screen Shot 2021-03-18 at 13 04 56" src="https://user-images.githubusercontent.com/39252765/111913117-4aa11280-8a32-11eb-8116-14ba4abcb498.png">

Site does not: 

<img width="624" alt="Screen Shot 2021-03-18 at 13 10 09" src="https://user-images.githubusercontent.com/39252765/111913124-512f8a00-8a32-11eb-8dd5-8463ca5a012c.png">

Perhaps caused by cache on the Simple Site.

### Context

#3834092-zen

**Comment by kosiew** [comment] 2021-08-11 05:58
Closing. 
Duplicate of https://github.com/Automattic/wp-calypso/issues/50740

**Closed as completed by kosiew** 2021-08-11 05:58 UTC
Labels: Bug, Podcasting, Block Rendering
