### ISSUE TITLE
Editor: Post visibility setting doesn't save when trying to change from private

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#16898] opened 2017-08-04 02:04 UTC
Discovered in a live chat today, when you have a post that has been set to "private", you can not successfully change it's visibility back to public or password-protected. It will not let you select "Public" at all. It will let you select "Password Protected", however after updating you'll discover the change wasn't actually saved. If you attempt to refresh the page you'll see browser alerts saying you have unsaved changes, suggesting that nothing actually was saved.

![post-visibilty-bug-video](https://user-images.githubusercontent.com/12596797/28951166-4329568a-7897-11e7-9b7a-30eedb724403.gif)

**Steps to reproduce**
1. Open up any post on a test site, or create one and set the post visibility to "Private". Then Update/Publish.
2. Then try to change that setting to either Public or Password-Protected. Then Update.
3. View the post to see if it actually has been changed from private.

**Browser / OS version**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

cc @mattsherman who I see last made updates (3 days ago) to the post-visibility code in #16710

**Comment by alisterscott** [comment] 2017-08-04 04:02
Confirmed this is a recent issue as this isn't happening in the desktop app. Marking as high priority since there doesn't appear to be a workaround besides using wp-admin

**Closed** 2017-08-04 20:11 UTC
Labels: Editor, [Pri] High, [Type] Bug
