### ISSUE TITLE
Reader: Classic Block ignores text alignment and color settings

### ISSUE THREAD

**Issue by AmandaRiu** [Automattic/wp-calypso#45141] opened 2020-08-22 20:49 UTC
#### Steps to reproduce

1. Create a new post using a classic block.
2. Add indented text
3. Add centered text
4. Add right justified text
5. Set some text to a different color (for example, blue)
6. View the post in the reader on Calypso

#### What I expected
Alignment and text color settings would be rendered as intended.

#### What happened instead
All text that had special alignment assigned are rendered left-aligned. The color setting was ignored - all text in black.

#### Browser / OS version
- Firefox (79.0)
- Chrome (84.0.4147.135)
- Safari (13.1.2)

#### Screenshot / Video

Here's what the post looks like on the web:

![firefox_web](https://user-images.githubusercontent.com/5810477/90965549-0b5c1480-e497-11ea-93ad-459060fa5af2.png)

Here's what the post looks like in the reader:
Chrome | Safari | Firefox
-- | -- | --
![chrome_calypso](https://user-images.githubusercontent.com/5810477/90965558-1dd64e00-e497-11ea-80e7-cefa8d897bcd.png)|![safari_calypso](https://user-images.githubusercontent.com/5810477/90965560-2169d500-e497-11ea-9883-6c278662c060.png)|![firefox_calypso](https://user-images.githubusercontent.com/5810477/90965562-23cc2f00-e497-11ea-9582-6f3dd287a088.png)

#### Context / Source

```
<p>This is a classic block snippet. <strong>This sentence in bold. <em>This sentence in </em></strong><em>italics. </em></p>
<ul>
<li>This is bullet 1</li>
<li>bullet 2
<ul>
<li>nested bullet</li>
</ul>
</li>
<li>bullet 3</li>
</ul>
<ol>
<li>one</li>
<li>two</li>
<li>three
<ol>
<li>nested one</li>
<li>nested two</li>
</ol>
</li>
<li>four</li>
</ol>
<blockquote>
<p>A beautiful quote format</p>
</blockquote>
<p>Regular indent</p>
<p style="padding-left: 40px;">Indented further</p>
<p style="text-align: center;">centered sentence</p>
<p style="text-align: right;">Right justified</p>
<p><del>Strikethrough text</del></p>
<hr />
<p><span style="color: #0000ff;">Using a different color (blue)</span></p>
<p><a href="http://www.google.com">hyperlink</a></p>
```

**Comment by kwight** [comment] 2020-10-28 16:40
Reader changes for the sake of better block rendering needs further investigation; see paYKcK-KO-p2 for context.

**Comment by davipontesblog** [comment] 2021-04-14 14:06
Part of the Block Audit milestone: https://github.com/Automattic/wp-calypso/milestone/320
As discussed with @4thhubbard, leaving it for future consideration.

**Comment by davemart-in** [comment] 2023-02-06 21:29
Note: All styles are going to be stripped for security reasons in https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/post-normalizer/rule-content-remove-styles.js

**Comment by roo2** [comment] 2023-07-11 09:03
Yea it looks like it's by design since as Dave pointed out, we strip style attributes and also the `align` html attribute. I can see why we wouldn't enable custom text color too in case the user had white text on a black background for example

**Comment by roo2** [comment] 2023-07-11 09:03
I'm just going to close this because it's been sitting here for three years and seems to be by design

**Closed by roo2** 2023-07-11 09:03 UTC
Labels: [Pri] Normal, Reader, Blocks
