### ISSUE TITLE
Gutenberg: Embeds: Google Maps embed doesn't work

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#27703] opened 2018-10-10 01:40 UTC
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/
2. Try to add a Google Maps iFrame code to the HTML block editor - or paste into a new block 

`<iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d14158.742138514875!2d153.01188991977534!3d-27.47904779999999!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sau!4v1539065953822" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>`

#### Gutenberg in Calypso Result

![google maps](https://user-images.githubusercontent.com/128826/46708255-103bc480-cc81-11e8-9d32-3382b8b4a843.gif)

#### Calypso Editor Result

Converts to shortcode straight after pasting iFrame

![calypso](https://user-images.githubusercontent.com/128826/46708280-2d709300-cc81-11e8-839f-2f196210d074.gif)

#### Browser / OS version

Chrome 69 on macOS

#### Related

https://github.com/Automattic/wp-calypso/issues/27498

**Comment by codebykat** [comment] 2019-03-12 23:06
Confirmed this is still an issue. After publishing the post it does get converted to a shortcode that works.

**Comment by retrofox** [comment] 2019-03-19 17:06
I think it's already handled.

![gutenberg-test-google-maps](https://user-images.githubusercontent.com/77539/54625881-de5c3480-4a4e-11e9-9df8-c287e8517b4e.gif)

Does it show the desired behavior?

And since they have the same behavior (core and gutenframe) going to close this one. If it isn't the desired behavior let's create a new issue in the core repository.

**Closed by retrofox** 2019-03-19 17:06 UTC
Labels: [Goal] Gutenberg, [Pri] Normal, [Type] Bug
