### ISSUE TITLE
Gutenberg: Audio Block

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27639] opened 2018-10-05 02:50 UTC
Let's be able to upload whitelisted audio file types as expected.

**Comment by vindl** [comment] 2018-10-10 17:01
The apparent file type permission error has been caused by inadequate plan on the site (doesn't work with free plan for example). This has been moved to a separate issue https://github.com/Automattic/wp-calypso/issues/27772, but there is still a problem with Audio block not being rendered on the front end, and `This block has been modified externally.` error on reload which is probably related to attribute pruning issue (https://github.com/Automattic/wp-calypso/issues/27645).

**Comment by Copons** [comment] 2018-10-17 11:32
This is caused by the `audio` tag not being whitelisted in our `wp_kses`.
Fix pending security review: D19531-code.

**Comment by Copons** [comment] 2018-10-19 16:33
Fixed by D19531-code

**Closed by Copons** 2018-10-19 16:33 UTC
Labels: [Goal] Gutenberg, [Type] Task
