### ISSUE TITLE
Building calypso on Windows 10 fails

### ISSUE THREAD

**Issue by adriatic** [Automattic/wp-calypso#34351] opened 2019-06-28 02:41 UTC
#### Steps to reproduce
Run the several step outlined at https://github.com/Automattic/wp-calypso#getting-started

#### What I expected
Successful build

#### Browser / OS version
Chrome Version 75.0.3770.100 (Official Build) (64-bit)

#### Screenshot / Video
Way too many error messages like
```
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!node_modules/sass-loader/lib/loader.js??ref--6-3!client/post-editor/editor-sharing/style.scss:
```
with the explanation:
```
File to import not found or unreadable: c:workÊlypsowp-calypso
    ssetsstylesheetsshared_utils.scss.
```

Note the 'Ê' character in the path above

**Comment by lancewillett** [comment] 2019-07-29 23:01
Thanks for the report, @adriatic.

@stephanethomas If you have some time, could you take a look, please?

**Comment by stephanethomas** [comment] 2019-08-01 10:13
I think it's a duplicate of https://github.com/Automattic/wp-calypso/issues/31059. I'm afraid I won't be able to help because I don't run Calypso on Windows natively (I use [Calypso Bootstrap](https://github.com/Automattic/wp-calypso-bootstrap)), and I'm running after time those days 🙄.

**Closed** 2019-08-01 14:35 UTC
Labels: Build, Windows, [Type] Help Request

**Comment by adriatic** [comment] 2019-08-01 16:32
@lancewillett - seeing a comment from someone who cannot help (@stephanethomas) I expected to see an explanation from someone who can; I certainly did not expect to see this discussion closed 😢 .

Should I take this as the sign of calypso team not supporting windows? I hope not.

I considered using the [Calypso boostrap](https://github.com/Automattic/wp-calypso-bootstrap) - but installing that environment takes away Docker from me, something I would rather not do.

**Comment by lancewillett** [comment] 2019-08-01 19:00
@adriatic Feel free to continue following along on this thread: https://github.com/Automattic/wp-calypso/issues/31059 — as mentioned it's similar and we can leave that one open.

We don't actively support Windows, but are happy that you are giving it a go.

**Comment by adriatic** [comment] 2019-08-01 21:45
Hello, Lance

 

The reference you provided (https://github.com/Automattic/wp-calypso/issues/31059) is related to my own issue only by both being failures when building Calypso on Windows 10. Let me explain (and by the same token show my persistence – as I would really like to get calypso built on my Windows 10 Workstation).

 

Andrew Koung (https://github.com/andrewkoung) seems to be a build error due to incorrect configuration – and could be difficult to debug remotely (by someone on your team).

 

My issue is a lot simpler (I am making an educated guess) – the build fails in:

 

Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!node_modules/sass-loader/lib/loader.js??ref--6-3!client/post-editor/editor-sharing/style.scss:

 

Saying that:

 

File to import not found or unreadable: c:workÊlypsowp-calypso
    ssetsstylesheetsshared_utils.scss.

 

 

This could only be a consequence of bad css files mapping, creating the reference to project’s home file to be c:workÊlypsowp which is obviously incorrect syntax.

 

My interest in this is really not to use your work on creating a JavaScript WordPress, but rather to try my own, (Aurelia) client front end. Let me also add that I am not trying to reinvent a wheel, but rathe to verify whether Calypso approach is too influenced with your team PHP history.

 

Regards

 

Nikolaj Ivancic
