### ISSUE TITLE
Blog Posts block shows placeholder content in FSE templates

### ISSUE THREAD

**Issue by thekingsprojects** [Automattic/wp-calypso#69101] opened 2022-10-15 01:36 UTC
### Quick summary

When adding the Blog Posts block to an FSE template, it shows placeholder content in the Site Editor instead of a preview of the user's actual posts. When adding the Blog Posts block to a page in the standard Block Editor, it shows the user's actual posts instead.

The published site/template does show the selected posts correctly; it's only the Site Editor that shows placeholders.

I'm not sure if this is actually a bug or not, since I know some template blocks show placeholder content in certain situations and this is intentional. [WordPress.com's documentation](https://wordpress.com/support/wordpress-editor/blocks/blog-posts-block/) shows screenshots/gifs of the Blog Posts block with previews, but these are likely screenshots from the Block Editor rather than the Site Editor. It does imply that showing previews is the expected behavior, though.

Additionally, not having previews means the user can't see the changes they're making until they publish (or preview) the page—for example, if they try to limit the block to showing only a certain tag, the editor doesn't update to display only the most recent posts with that tag.

(If this is intentional behavior, then maybe this can be turned into a feature request?)

### Steps to reproduce

1. Activate an FSE theme, such as Twenty Twenty-Two.
2. Go to Appearance > Editor and edit a template.
3. Add a Blog Posts block to the template somewhere.
4. (Optionally) Change the Block Settings for the Blog Posts block to change the selected range of posts, such as only displaying specific posts or limiting it to a certain category.

### What you expected to happen

The Blog Posts block's preview in the editor should show the user's posts (if they have any), as it does when adding the block to a page. If changes are made to the Blog Posts block's settings, those changes should be reflected in the preview.

### What actually happened

The Blog Posts block's preview shows placeholder content, and it does not update to reflect any changes made regarding which posts to show.

<img width="729" alt="Screenshot on 2022-10-14 at 18-42-30" src="https://user-images.githubusercontent.com/82622339/195963204-94435925-726b-43c1-bda0-460f29b5d7fe.png">

### Context

Customer report here: 37342807-hc

(Follow-up ticket here, if needed: 5632733-zen)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Workaround details

* The user can ignore the fact that the preview has placeholder content, as the block still shows their content correctly on the live site. (This does mean they can't test how it looks/which posts they're selecting within the Site Editor, though.)
* The user can try a Query Loop block instead, which does show previews of the selected posts.

**Comment by zachspears** [comment] 2022-10-20 02:00
Able to reproduce. Moving this forward as a bug report but if this is the intended behavior, I recommend changing it to an enhancement request.

**Comment by annezazu** [comment] 2024-08-29 21:55
I can't replicate this on my simple site (nomad.blog):

https://github.com/user-attachments/assets/f61566f4-58c4-4171-bae1-379de53645a4

It shows my content properly. Closing this out due to being unable to replicate and no further nor recent reports.

**Closed as completed by annezazu** 2024-08-29 21:55 UTC
Labels: Bug, [Pri] Low, Triaged, [Feature] Full Site Editor, Customer report [LEGACY]
