### ISSUE TITLE
Can't unlock blocks on pages if editing in FSE

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#91624] opened 2024-06-09 19:55 UTC
### Quick summary

Users editing their pages within the site editor are unable to unlock blocks once locked.

### Steps to reproduce

1. If not already, switch to an FSE theme.
2. Activate Appearance > Editor, select to edit one of your pages.
3. Lock at least one block. The user has the "disable movement" option enabled.
4. Save your changes.
5. Try to unlock that block.

### What you expected to happen

The block should be unlockable from within FSE.

### What actually happened

In the user's case, "disable movement" remains checked even after "apply" is clicked.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

It appears to be browser independent, and can be worked around by visiting /pages and accessing to edit pages from there.

**Comment by arinoch** [comment] 2024-06-09 19:56
Reported in 8305707-zd-a8c and tested by me.

**Comment by liviopv** [comment] 2024-06-10 14:57
📌 ACTIONS

- Closed as duplicate / by design 

It's a dupe of the issue you linked, @arinoch

**Closed as completed by liviopv** 2024-06-10 14:57 UTC
Labels: Bug, [Pri] Normal, Needs triage, [Feature] Full Site Editor, Customer report [LEGACY], [Platform] Simple, [Product] WordPress.com, [Feature Group] Editor Experience
