### ISSUE TITLE
Post Editor: can't update copied post draft

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#20703] opened 2017-12-11 17:47 UTC
## Steps to repro

1. Navigate to `/posts` and switch to the Drafts tab;
2. Select a draft, click on "... More" and hit "Copy";
3. Write something new to the copied draft and hit "Save";
4. You should get an error notice that "Saving of draft failed";
5. The copied draft doesn't get saved and if you reload the page, it will show the old content.

![image](https://user-images.githubusercontent.com/4988512/33845436-c1fe7f9a-dea3-11e7-9f90-5339de753998.png)

/cc @gwwar @Copons

**Comment by designsimply** [comment] 2017-12-11 18:01
Thank you for reporting this! I'm closing this as a duplicate of https://github.com/Automattic/wp-calypso/issues/20668, please follow that issue for updates.

**Closed by designsimply** 2017-12-11 18:01 UTC
Labels: Editor, [Pri] High, [Type] Bug
