### ISSUE TITLE
WooCommerce and WooCommerce conflict causes Add New Page workflow issue

### ISSUE THREAD

**Issue by i11za** [Automattic/wp-calypso#78672] opened 2023-06-27 10:15 UTC
## Describe the bug

When both WooCommerce and WooCommerce Blocks are active the `Add New Page` workflow gets stuck on the pop-up and doesn't redirect to a new page. The pop-up can't be closed. 

User report: 6469905-zd-woothemes

Unable to reproduce on a test site, not sure if it's a WooCommerce, WooCommerce Blocks issue, or WP.com specific issue. 

### Steps to reproduce

1. On the user's site (see below) go to Installed Plugins, make sure both `WooCommerce` and `WooCommerce Blocks` are active. 
2. Go to Pages → Add New Page (or any other workflow in any view)
3. When new page template selector pops up select any template, or `Blank Page`
4. Pop-up doesn't redirect to the new page, and can't be closed w/ `X` or keyboard shortcuts. 

`Edit: User information removed`

### What you expected to happen

In step 4 above selecting a template in the pop-up view should redirect to the new draft page. 

### What actually happened

Pop-up doesn't redirect to the new page, and can't be closed w/ `X` or keyboard shortcuts. 

`Edit: User information removed`

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Workaround: Deactivating WooCommerce Blocks solves the issue.

**Comment by cuemarie** [comment] 2023-06-27 17:46
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Unable to replicate, suggesting this is not a conflict or bug between WooCommerce and WooCommerce blocks, but rather a user site-specific issue.

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/181b4de7-2af9-41c7-8da9-c28934ae2fc2

📌 ACTIONS
- Closed as not reproducible
- Requested author feedback

📌 Message to Author
- @i11za since this isn't replicable outside of the user's site, that strongly suggests a more specific problem, such as a plugin conflict or particular setting issue. Have you had a chance to follow the full troubleshooting checklist here: P9HQHe-jC-p2 ?
-  Additionally, always make sure to exclude any user-specific information in your screenshots or details.
     - [x] Please edit the report/comment above to use remove user-specific information. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.

**Closed as not planned** 2023-06-27 17:47 UTC
Labels: Bug, [Pri] Low, [Closed] Not Reproducible, [Platform] Atomic
