### ISSUE TITLE
People: JS warning when accepting an invite with an existing wpcom user name

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#2708] opened 2016-01-22 21:31 UTC
![screen shot 2016-01-22 at 4 29 33 pm](https://cloud.githubusercontent.com/assets/2694219/12523541/88cba484-c125-11e5-930b-0b63eb1ee51a.png)

**Comment by hoverduck** [comment] 2016-05-12 17:00
12May16 Bug Scrub

Closing, unable to reproduce.  Tested in both Chrome and Firefox on OSX.

**Closed by hoverduck** 2016-05-12 17:00 UTC
Labels: People Management, [Pri] Low, [Type] Bug
