### ISSUE TITLE
Gutenberg Iframe: Audit actions that navigate to another wp-admin section

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#30551] opened 2019-02-01 19:45 UTC
With the `calypsoify/iframe` feature flag enabled, visit /block-editor, and then audit how many actions link to another wp-admin section. These are areas that we'll need to override in this case, for alternative actions in Calypso. In trash a post for example, we should override the default action, and trash via API -> redirect to the Calypso post list.

Currently these sections will refuse to render since X-Frame-Options are by default set to sameorigin.

<img width="913" alt="screen shot 2019-02-01 at 11 44 43 am" src="https://user-images.githubusercontent.com/1270189/52145879-17fbec00-2617-11e9-9b8f-6aaec3f67da8.png">

Please add new areas below:

- [ ] Move To Trash

<img width="277" alt="screen shot 2019-02-01 at 11 51 53 am" src="https://user-images.githubusercontent.com/1270189/52146166-d3bd1b80-2617-11e9-9770-a6adfb4dc322.png">

Let's override the action here, and use the API to trash that post and redirect to the post list with a success action. 

( 5 Days )

- [ ] Revisions

<img width="255" alt="screen shot 2019-02-01 at 11 53 44 am" src="https://user-images.githubusercontent.com/1270189/52146252-14b53000-2618-11e9-8545-420d6c153099.png">

Let's display the Calypso revisions, and enable functionality for restoring a particular version.

( 5 Days )

- [x] View the autosave (resolved by D24109-code)

<img width="940" alt="screen shot 2019-02-01 at 11 55 12 am" src="https://user-images.githubusercontent.com/1270189/52146324-44fcce80-2618-11e9-8893-d2e01a88343e.png">

There's some flexibility in either showing the Calypso revision, or updating the notice message to load the autosave. 

( 5 Days )

**Comment by vindl** [comment] 2019-02-18 16:15
The only additional cases I managed to find were the following:

1. Permalinks above the title and in the sidebar - but these open in a new tab so they are no causing the above issue.

2. Actions that are offered when the post is locked:

<img width="516" alt="screenshot 2019-02-18 at 14 39 33" src="https://user-images.githubusercontent.com/1182160/52963392-ecf7f300-339f-11e9-89a3-0850d647e754.png">

Clicking on `All Posts` or `Take Over` will result in the same error as reported above.

Here is the update on the previously reported issues:

- **Move to Trash** - This is currently being worked on by @rodrigoi, and we have a solution proposed in https://github.com/Automattic/wp-calypso/pull/30701 and D24207-code.

- **Revisions** - This bug is still present, I'll create a separate issue to track it.

- **View the autosave** - Since this is just an action inside the notice, this has already been resolved by a generic fix for notices that we have already deployed in D24109-code.

I'm going to close this issue and open separate ones for all of the problems above that can still be reproduced.

**Closed** 2019-02-18 16:15 UTC
Labels: [Goal] Gutenberg, [Type] Task
