### ISSUE TITLE
Block Editor: Typing hex code to change color and background of text not possible

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#79359] opened 2023-07-13 11:17 UTC
### Quick summary

In Atomic sites, it's not possible to type in a hex code to change the color or background of text in a paragraph block. When trying to do this, typing in anything will make the highlight popup jump to the left of the editor and cause the box to auto-fill with `000000` or even `00000000`.

Screencast: https://d.pr/i/J5mw8w

The only workaround is to type the hex code somewhere else, copy it and paste it into the popup.

### Steps to reproduce

1. Open up an Atomic site
2. Create or edit an existing post
3. Select text in a paragraph block and from the text options in the toolbar, select Highlight
4. Try changing the text or background color by typing in a hex code (ie EEEEEE)

### What you expected to happen

For me to be able to change the text and background colors by typing in the hex code.

### What actually happened

The highlight popup jumps around and I'm unable to type in the hex code that I want.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by karenroldan** [comment] 2023-07-14 16:30
📌 ACTIONS
- Closed as duplicate of issue #59566

📌 Message to Author
- Hi @druesome! Thanks for reporting. I'll close this issue on behalf of #59566 
- Related to https://github.com/WordPress/gutenberg/issues/49286

**Closed as not planned by karenroldan** 2023-07-14 16:30 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] Low, Triaged, [Platform] Atomic
