### ISSUE TITLE
Editor: removing featured image from Edit Post screen doesn't remove it from the Blog Posts screen

### ISSUE THREAD

**Issue by chaitanyamsv** [Automattic/wp-calypso#3821] opened 2016-03-07 10:51 UTC
#### Steps to reproduce
1. Edit a post with a featured image and remove the featured image.
2. Hit Update button.
3. Go back to Blog Posts screen by clicking on Posts link at the upper left.

#### What I expected
Removing featured image from the post in the Edit Post screen and updating the post should remove the featured image from the post in Blog Posts screen as well.

#### What happened instead
The removed featured image still shows up on the post.

#### Browser / OS version
This problem happened in desktop apps (1.3.0 version of both Windows and Mac apps) and in the browser (Firefox 44.0.2. On OSX Yosemite) as well.

#### Screenshot / Video
Mac desktop app screencast: https://cloudup.com/c8vxHWDcZLU
Browser screencast: https://cloudup.com/cgdp_FspSHJ

**Comment by timmyc** [comment] 2016-04-22 20:38
Thank you for the detailed bug report.  I just went to reproduce the bug and was unable to do so using the steps above on https://wordpress.com using chrome and firefox.

I wasn't able to view the browser screencast above either.

Since I can no longer reproduce this error I'm going to close this out.

**Closed by timmyc** 2016-04-22 20:38 UTC
Labels: Editor, OSS Citizen, [Type] Bug
