### ISSUE TITLE
Launch Flow: Chrome "Leave site?" dialog appearing at end of launch flow

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#48886] opened 2021-01-13 19:44 UTC
#### Steps to reproduce the behavior

1. Go to wp.com/new
2. Proceed through to Editor screen
3. Click launch button
4. Proceed through launch flow
5. Get to "Hooray!" screen and observe error below

#### Result

![image](https://user-images.githubusercontent.com/545779/104501502-6fe25200-55a5-11eb-912a-043833061c65.png)

**Comment by pauljacobson** [comment] 2021-01-14 10:05
I have what seems to be a related issue. A user reported that when they publish a post, and then click the option in the block editor pane to the left to create a new post, they see a similar message in Firefox:

<img width="566" alt="Screen Shot 2021-01-13 at 8 59 32 AM" src="https://user-images.githubusercontent.com/2912202/104576147-7da8dd80-5660-11eb-8741-b3c42730cab8.png">

I encountered this issue in the last few days, although I can't seem to reproduce it now. The user's system information is as follows:

Mac OS Big Sur 11.1
Firefox 84.0.2 (64-bit)
Macbook Air M1 chip

I am also on macOS 11.1, using Firefox Developer Edition v85.0b7.

Source: 3641317-zd

**Comment by tbradsha** [comment] 2021-01-14 20:27
Also reported in 3643293-hc.

I was able to reproduce on macOS 11.1, Chrome 87.0.4280.141:

1. Open a page.
2. Add an image block.
3. Update the page.
4. Click "View page":
 ![image](https://user-images.githubusercontent.com/32492176/104645119-e053a680-566b-11eb-8fa0-69456c2968c8.png)
5. Receive the "leave page" alert:
 ![image](https://user-images.githubusercontent.com/32492176/104645203-011bfc00-566c-11eb-8b38-5dbfcd14e02d.png)

Note that if I cancel the alert, it'll still show the Update button as active, and I can repeat steps 3-5 indefinitely (without making any changes to the page).

**Comment by simison** [comment] 2021-01-22 11:10
@Automattic/good-mountain was this something that's fixed in latest Gutenberg?

**Comment by Copons** [comment] 2021-01-22 11:55
I'm not able to repro any of the 3 different issues reported here, tested with Chrome and Firefox on MacOS 11.1.
Since the reports, a new Gutenberg version (9.7 up to 9.7.2) has been [merged](https://github.com/Automattic/wp-calypso/issues/48771) to .com.
At a quick glance of the changelogs, nothing seems related to this issue.

In the off-chance I'm missing something in the repro steps, I'd love to have a new check (at least by @ianstewart as original author) before closing this issue.

**Comment by sirreal** [comment] 2021-01-22 13:34
I don't see any obviously related recent changes and it isn't highlighted in the release notes for [9.6](https://make.wordpress.org/core/2020/12/23/whats-new-in-gutenberg-23-december/) or [9.7](https://make.wordpress.org/core/2021/01/07/whats-new-in-gutenberg-6-january/), both of which received recent upgrades.

It's entirely possible that it has been fixed without me being aware or finding it. I'm also unable to reproduce at this time and I think we can close.

**Comment by simison** [comment] 2021-01-22 13:39
Thanks both! Let's close for now and be on the lookout.

**Closed as completed by simison** 2021-01-22 13:39 UTC
Labels: Bug

**Comment by tbradsha** [comment] 2021-01-22 20:14
Confirmed that I can no longer reproduce this, so let's hope it's fixed!
