### ISSUE TITLE
Opening Gutenberg editor sometimes triggers error messages on Chrome and Firefox

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49374] opened 2021-01-28 00:54 UTC
### Steps to reproduce the behavior

Prereq. there is an existing Post or Page.
Prereq. on Firefox, enable Enhanced Tracking Protection.

1. Select a site.
2. On the sidebar, click on Posts or Pages.
3. Click on Add New (page or post).
4. Quickly navigate back.
5. Open the existing page or post.

#### What I expected to happen
Clicked page or post opens in the Gutenberg editor as soon as feasible, without user-facing errors or unexpected transitions.

#### What actually happened 
Likely because of the Enhanced Tracking Protection enabled in Firefox, there is an error page that is shown to user that connection could not be made.

Given a few seconds, the browsers reload and is able to render the requested page/post in the block editor.

### Context
User scenario manual testing.

#### Browser / OS version
OS: macOS Catalina 10.15.7
Browser: Firefox Nightly 86.0a1
Chrome 88.0.4324.96 (Official Build) (x86_64) (just twice)

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
<strike>Both</strike>
Updated: Atomic only.

#### Is there any console output or error text?
Yes (Firefox):
```
The loading of “https://radicallyrenewedrecordsshop.wpcomstaging.com/wp-login.php?redirect_to=https%3A%2F%2Fradicallyrenewedrecordsshop.wpcomstaging.com%2Fwp-admin%2Fpost.php%3Fpost%3D34%26action%3Dedit%26calypsoify%3D1%26block-editor%3D1%26frame-nonce%3D1611881008%253A6321460%253A943df2a49531be87749e1cc99ce28a5c%26origin%3Dhttps%253A%252F%252Fwordpress.com%26environment-id%3Dproduction%26support_user%3D%26_support_token%3D&reauth=1&calypsoify_cookie_check=true” in a frame is denied by “X-Frame-Options“ directive set to “DENY“.
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
N/A

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Firefox
![Screen Shot 2021-01-27 at 16 37 52](https://user-images.githubusercontent.com/6549265/106074163-3a1e8c80-60c0-11eb-8c7e-ed0aebb24bce.png)

Chrome (reproduced on Simple site only twice)
![Screen Shot 2021-01-27 at 16 42 48](https://user-images.githubusercontent.com/6549265/106074174-3b4fb980-60c0-11eb-91a4-dab5439dbe64.png)

Firefox:
https://user-images.githubusercontent.com/6549265/106074200-43a7f480-60c0-11eb-946a-029d7d49d61e.mov

**Comment by simison** [comment] 2021-01-29 13:53
Sounds like 3rd party cookie issues. @gravityrail @josephscott correct?

**Comment by josephscott** [comment] 2021-01-29 16:21
@simison not based on this item:

> Given a few seconds, the browsers reload and is able to render the requested page/post in the block editor.

If this was an issue with third-party cookies then a difference of a few seconds shouldn't matter.

**Comment by worldomonation** [comment] 2021-03-08 18:51
I have reproduced this issue using Firefox, with Enhanced Tracking Protection enabled, on Atomic sites only. The initial description has been updated to reflect this.

**Comment by simison** [comment] 2021-03-18 13:56
@Automattic/team-calypso this is a bit of head-scratcher for us. Does the error tell anything to you where this problem could originate:

> `The loading of “https://radicallyrenewedrecordsshop.wpcomstaging.com/wp-login.php?redirect_to=https%3A%2F%2Fradicallyrenewedrecordsshop.wpcomstaging.com%2Fwp-admin%2Fpost.php%3Fpost%3D34%26action%3Dedit%26calypsoify%3D1%26block-editor%3D1%26frame-nonce%3D1611881008%253A6321460%253A943df2a49531be87749e1cc99ce28a5c%26origin%3Dhttps%253A%252F%252Fwordpress.com%26environment-id%3Dproduction%26support_user%3D%26_support_token%3D&reauth=1&calypsoify_cookie_check=true” in a frame is denied by “X-Frame-Options“ directive set to “DENY“.`

It happens only with Enhanced Tracking Protection enabled.

**Comment by jsnajdr** [comment] 2021-03-19 06:12
@simison I believe this is an intentional behavior of Gutenframe and Jetpack. To load the iframed editor, the user needs to be logged into the Atomic site and have site-specific auth cookies. With 3rd party cookies blocked, that login is not going to work. There is a Jetpack patch (https://github.com/Automattic/jetpack/pull/16167) that detects cookie blocking (`calypsoify_cookie_check` in query args) and sends the `X-Frame-Options: DENY` header. That make the Gutenframe to fail loading immediately without entering any auth loops.

The Gutenframe code should detect all that and do a top-level navigation to Gutenberg on Atomic site, without iframing.

If the end result is that after few seconds you end up on non-Calypso Gutenberg in the site's wp-admin, it's an expected and intentional behavior.

The error iframes that the browser displays on `X-Frame-Options: DENY` are not very nice and the experience loading the editor is admittedly not a good one. Maybe we could hide the iframe until we know it loaded successfully? Embed iframes do that with a `style="clip( 1px 1px 1px 1px )"` attribute that is removed after successful load.

@worldomonation writes in the issue description:
> Given a few seconds, the browsers reload and is able to render the requested page/post in the block editor.

So, after a few seconds, the post editor actually loads and the user can edit? In that case, everything is as intended.

**Comment by alshakero** [comment] 2021-03-24 16:58
OK so there seems to be two problems.

**1. Users are waiting for five seconds before being redirected**

I wanted to get rid of or at least shorten the waiting time in this ugly state. Because even if we stylize the iframe to be smaller, people will have to wait for 5 seconds before they're redirected. See why below.

I found this [PR](https://github.com/Automattic/wp-calypso/pull/41006). Since we can't tell if the iframe had failed to load and why when cross domain, we poll for 5 seconds to see if the iframe posted any messages and consider the first message a sign of success. Messages are sent before `onLoad` event, so we should be able to check if any message was sent before inside `onload` handler and consider it a success without polling, but surprise surprise, IE can fire `onload` before `onmessage`. So we poll instead, to overcome the race condition between the two events and when it's not a success after 5 seconds, we redirect to wp-admin.

But this means that we'll poll even when the iframe fails to load immediately (like in this issue's case). 

I realized that the IE bug is more likely to be a bug only in the order of events, and maybe waiting one tick can be sufficient. I tested this hypothesis in this [draft PR](https://github.com/Automattic/wp-calypso/pull/51370) and IE seems to work consistently (tested 5 times).

**2. The waiting state is ugly**

This is a matter of styling the iframe, and we may or may not be needed if we make the transition fast enough, I don't know. The problem is that I can't test the above PR, because authentication seems broken when you block 3rd party cookies in calypso.live. This problem only surfaces in localhost and in calypso live. But for reasons I don't understand I can login without 3rd party cookies in wp.com just fine. Maybe because public-api.wordpress.com lives under wordpress.com and not under calypso.live.

I don't know what's the right path forward. I'll ping our friends @noahtallen and @p-jackson because they worked on this polling mechanism and probably understand it better than I do. 

My personal opinion is to test my PR in calypso.live with 3rd party cookies allowed, and take some risk and merge it and then test with 3rd party cookies blocked under wordpress.com. If the transition is swift enough to wp-admin, we can consider this issue done, if still jarring, we can stylize the iframe to be hidden until the first bridge message is received.

**Comment by noahtallen** [comment] 2021-03-24 21:16
I'm absolutely fine removing the polling code. The reason we added it was to try to fix a bad IE11 canary test. Since we're deprecating IE11, I think we should be ok reverting anything that was added just to try to fix that. (Mentioned this in the PR too.)

> authentication seems broken when you block 3rd party cookies in calypso.live

@jsnajdr would know more about this -- I think he's working on resolving related issues with cookies.

**Comment by alshakero** [comment] 2021-03-24 22:24
That's awesome, thanks! I'll update the PR to remove the entire polling code 🎊

**Comment by jsnajdr** [comment] 2021-03-25 05:57
This bug affects only Atomic sites. Simple sites load the frame from a `*.wordpress.com/wp-admin` domain that always has 1st party valid auth cookies. With the Nav Unification project shipping, we are sending more and more Calypso navigations directly to wp-admin for Atomic sites. Like the entire Posts list.

Considering the above, what if we gave up iframing the Atomic Gutenberg completely and were sending users to wp-admin directly? That saves them several seconds of attempting to do the iframing that's increasingly less likely to succeeded.

**Comment by simison** [comment] 2021-03-25 08:46
The problem is that without iframe customers lose several features that are built in calypso and work over the iframe: help FAB and calypso media library as two biggest.

Eventually we want to remove the iframe for all sites but that needs more work (pbAok1-gS-p2).

**Comment by alshakero** [comment] 2021-03-25 10:44
> Considering the above, what if we gave up iframing the Atomic Gutenberg completely and were sending users to wp-admin directly? 

I was thinking of a way that avoids the iframe altogether for users that are unlikely able to use it. This is a variation of this solution, but isn't the criteria too broad? I don't know the stats, but I imagine people who disable 3rd party cookies are a minority. If we could run the cookies check in Calypso in the background and adjust the URLs accordingly that would be more precise IMO.

We can create a hook `useHas3dPartyCookies` that caches the answer at least during the session and use that hook everywhere.

**Comment by noahtallen** [comment] 2021-03-25 21:03
> I imagine people who disable 3rd party cookies are a minority

More and more browsers like Brave are blocking 3rd-party cookies out of the box (I have to disable brave checks to use calypso.live, for example.)

If I'm not mistaken (@jsnajdr can correct me), we are moving away from cookies to JWT for Calyspo to work around these issues?

**Comment by josephscott** [comment] 2021-03-25 21:08
> I imagine people who disable 3rd party cookies are a minority

To be clear, this is entirely incorrect.  Third-party cookies are [disabled by default already in Safari](https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/), and [Chrome is going to remove support for third-party cookies next year](https://blog.chromium.org/2020/01/building-more-private-web-path-towards.html).

In short, third-party cookies are dead.  All users will have them disabled by default.

**Comment by jsnajdr** [comment] 2021-03-26 12:38
> The problem is that without iframe customers lose several features that are built in calypso and work over the iframe: help FAB and calypso media library as two biggest.

@simison With the Nav Unification project shipping, I'm afraid we already gave up on providing these extra features for Atomic sites. The sidebar links that lead to the editor (directly or through a Posts list) already link directly to wp-admin pages.

<img width="435" alt="Screenshot 2021-03-26 at 13 20 16" src="https://user-images.githubusercontent.com/664258/112630829-722f1b00-8e36-11eb-8ef0-b43887502e11.png">

Actually the only current route I found that leads to the iframed Atomic editor is the "Write" button in Adminbar:

<img width="316" alt="Screenshot 2021-03-26 at 13 24 53" src="https://user-images.githubusercontent.com/664258/112631201-de118380-8e36-11eb-8b5e-b5775d1d689d.png">
(someone might fix these links soon 🙂)


That means that de facto the iframed Atomic editor is already deprecated.

To provide the Calypso Media library, Help icon and Happychat to wp-admin users, we'll need to extract these features from Calypso and package them as wp-admin widgets. That's going to happen sooner or later, for now we have some workarounds.

If the site doesn't have a `*.wordpress.com` domain mapping, like Atomic/Jetpack sites don't, it's technically impossible to embed its wp-admin screens in Calypso. Today it still works for Chrome users, but as soon as 3rd party cookie blocking becomes the default there, it will stop working forever.

**Comment by alshakero** [comment] 2021-03-30 11:34
> I imagine people who disable 3rd party cookies are a minority
> To be clear, this is entirely incorrect.

TIL. Thanks!

I removed the 5000ms polling logic [here](https://github.com/Automattic/wp-calypso/pull/51370) (thanks @noahtallen!). Sadly, the error still shows up, although for a much shorter time.


https://user-images.githubusercontent.com/17054134/112982216-86d42180-915c-11eb-8b0a-b4943f9999db.mov

**Comment by simison** [comment] 2021-03-30 12:22
I think the next step would be applying the `style="clip(...` thing described in https://github.com/Automattic/wp-calypso/issues/49374#issuecomment-802584542 while the iframe loads? cc @roo2 @creativecoder

**Comment by alshakero** [comment] 2021-03-30 18:03
Since I touched on this issue and have some context, I created this [PR](https://github.com/Automattic/wp-calypso/pull/51558) for the clipping tweak, to save the next person some time. Should be fairly easy to review.

**Closed as completed** 2021-04-12 12:50 UTC
Labels: [Pri] Normal, [Source] User testing, Triaged, Back to Basics
