### ISSUE TITLE
Navigation block-Universal Themes Menu subitem text color doesn't honor changes

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#68793] opened 2022-10-08 05:07 UTC
### Quick summary

When using the Navigation block in a Universal theme (example Russell, Appleton) changing the text color for "Submenu & Overlay Text" doesn't reflect in the menu, it stays as the default color in the editor and on the live site if you save.

### Steps to reproduce

1. Activate any [Universal theme](https://wordpress.com/themes/filter/universal-theme)
2. Set or create a menu using the Navigation block in the Site Editor and create a subitem
3. In the Settings sidebar for the Navigation block change the color for the "Submenu & Overlay Text"

https://user-images.githubusercontent.com/42655541/194689592-90bf394a-7600-4797-b32f-350b8b6ed4ec.mp4

### What you expected to happen

I expected the Editor and the live site (after saving) to reflect the color change.

### What actually happened

In both the Editor and the live site it stays as the default color.

### Context

Student reported it through WP Courses (while following some of our lesson materials). I then tested it and consistently reproduced it on Simple and Atomic sites for Universal themes only. Dedicated Block (FSE) themes such as Tsubaki, TT2, Archeo, work properly as expected. Classic and Hybrid themes using the Navigation block also work fine.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

All Universal themes only.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Workaround details

It could possibly be overridden with CSS, but only if the site is on a plan that has access to CSS, and we're minimizing the CSS support we provide. (But I couldn't get CSS to work.)

**Comment by cuemarie** [comment] 2022-10-08 16:31
Quick note for triager - it's possible this is related to another open issue here: https://github.com/Automattic/wp-calypso/issues/62017

**Comment by tanjoymor** [comment] 2022-10-09 03:03
Yes the report mentioned above is the same issue, I didn’t find it in my searches. One point of clarification on the other report is that it is only affecting “Universal” themes (these are the ones that still have a Menu section in the Customizer but they aren’t all properly tagged as Universal in the filters).  It is affecting all Universal themes and CSS only works if they have a plan that supports Additional CSS.

**Comment by cuemarie** [comment] 2022-10-11 17:40
Thanks for sharing your thoughts on both issues, @tanjoymor ! 

📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/62017

**Closed as completed by cuemarie** 2022-10-11 17:40 UTC
Labels: Bug, [Feature] Full Site Editor, [Platform] Simple, [Platform] Atomic
