### ISSUE TITLE
Design Picker: Premium Label's Tooltip Displayed without Styles

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#77757] opened 2023-06-02 17:12 UTC
#### Steps to reproduce

1. Starting at URL: `/setup/site-setup/designSetup?siteSlug={ siteSlug }`
2. Find a Premium theme and hover on its "Premium" label.

#### What I expected

To see the tooltip with white text on black background.

#### What happened instead

The tooltip is missing some styles.

#### Screenshot / Video

| Expected | Actual |
|--------|--------|
| <img width="341" alt="Screenshot 2023-06-02 at 18 04 44" src="https://github.com/Automattic/wp-calypso/assets/2070010/62a66988-8fe1-4948-928c-662bab30be22"> | <img width="341" alt="Screenshot 2023-06-02 at 18 03 45" src="https://github.com/Automattic/wp-calypso/assets/2070010/5c312ed6-528a-439d-86c0-36dfd20c94e9"> | 

#### Context / Source

This only happens in non-`development` environments.
In `development`, the Design Picker is being redesigned and does not suffer from the same issue.

In the affected environments, it seems that the custom `.premium-badge__popover` styles are being overwritten by the default `.popover` styles:

For some reason, this does not happen with the WooCommerce label's tooltip, which retrieves its styles from a different source (`entry-stepper.****.min.css`):

| Premium Badge | WooCommerce Badge |
|--------|--------|
| <img width="400" src="https://github.com/Automattic/wp-calypso/assets/2070010/be540c08-5c41-4c22-9312-9a6aa695fe34"> | <img width="500" src="https://github.com/Automattic/wp-calypso/assets/2070010/442862a3-1a31-4c95-aa7a-25168794a3be"> | 

cc @Automattic/t-rex @Automattic/lego

**Comment by john-legg** [comment] 2023-06-02 22:29
📌 REPRODUCTION RESULTS

Tested on Simple – **Replicated** 
Tested on Atomic – **Replicated** 
Replicable outside of Dotcom – Not applicable

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to replicate this on Simple and Atomic (WPCOM) sites with all browsers (Safari, Firefox, and Chrome). The WooCommerce badge tooltip appears fine, so it looks like the premium badge is the only one affected. It's also noticeable on the theme detail page. 

<img width="836" alt="Screenshot 2023-06-02 at 6 03 49 PM" src="https://github.com/Automattic/wp-calypso/assets/96805492/a55dbd9d-a7de-4e1d-870e-448a2dc1e6f3">

<img width="836" alt="Screenshot 2023-06-02 at 6 07 48 PM" src="https://github.com/Automattic/wp-calypso/assets/96805492/e8b4b9a6-cbf5-4ccd-89e1-dc127da950b2">



Outside of the design picker onboarding flow, the premium badge on `Appearance > Themes` appears to be correct.


📌 ACTIONS

Assigned to `T-Rex` column (@Automattic/t-rex)

**Comment by Copons** [comment] 2023-06-05 14:51
Just as a note: https://github.com/Automattic/wp-calypso/issues/77640 too seems to be caused by differing CSS load orders on different environments.

**Comment by mmtr** [comment] 2023-06-12 10:58
I think this is no longer reproducible as of https://github.com/Automattic/wp-calypso/pull/77813 or https://github.com/Automattic/wp-calypso/pull/77675

**Closed as completed by mmtr** 2023-06-12 10:58 UTC
Labels: Bug, [Pri] Low, Triaged, [Feature] Design Picker
