### ISSUE TITLE
Gutenberg: Respect site writing settings

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#29627] opened 2018-12-19 17:27 UTC
Site settings affecting the editor aren't currently used by Gutenberg, as Gutenberg uses a different store (and "ruleset") than Calypso.

For example, Calypso has a "show publish confirmation" option in the Writing settings:
![screenshot 2018-12-19 at 17 12 19](https://user-images.githubusercontent.com/2070010/50236423-42b91a80-03b2-11e9-839c-df8c106c33e9.png)

Gutenberg has such confirmation by default:
![screenshot 2018-12-19 at 17 12 05](https://user-images.githubusercontent.com/2070010/50236458-5bc1cb80-03b2-11e9-9de3-c35acfce3633.png)

This option is handled entirely by Gutenberg, and can be toggled with the "Enable Pre-publish Checks" check in the Options dialog accessible from the More menu.

As I see it, we can solve this in two ways:
- Update Gutenberg so that it syncs the "pre-publish checks" option with Calypso's "show publish confirmation".
- For opted-in to Gutenberg users, remove the option from Calypso's writing settings, and rely only on the Gutenberg's own.

#### Note
We should run an actual audit of Calypso settings and see if there are other discrepancies with Gutenberg.

**Comment by retrofox** [comment] 2019-03-12 21:38
It's still reproducible.

**1)**

![image](https://user-images.githubusercontent.com/77539/54237819-0f2eed80-44d4-11e9-9cbd-1a1c5f9dbd8d.png)

**2)**

![image](https://user-images.githubusercontent.com/77539/54237924-56b57980-44d4-11e9-8274-5dc0c824470d.png)

Moving this one to the backlog.

**Comment by retrofox** [comment] 2019-03-21 19:30
> For opted-in to Gutenberg users, remove the option from Calypso's writing settings, and rely only on the Gutenberg's own.

I guess it's the better path to take since we will weigh the usability of Gutenberg over Calypso. Not sure if it's what we want. Finally, it's easier to do.

**Comment by kwight** [comment] 2019-03-21 19:54
I guess the "proper" fix is to sync the two values; it's always frustrating for users when we make settings appear and disappear for reasons we don't explain nor do they understand.

A third option is to replace the switch and description for Gutenberg users with a helpful paragraph explaining where they can set it within the Gutenberg settings.

**Comment by retrofox** [comment] 2019-03-21 20:05
> I guess the "proper" fix is to sync the two values; it's always frustrating for users when we make settings appear and disappear for reasons we don't explain nor do they understand.

Yes, fair enough.

> A third option is to replace the switch and description for Gutenberg users with a helpful paragraph explaining where they can set it within the Gutenberg settings.

Yes, I like it especially because it seems easier to do. But again does it kinda similar to hide/remove the option in terms of changing the interface according to some things about to the application/system/etc, which the customer doesn't know (and no reason to know)?

**Comment by kwight** [comment] 2019-03-21 21:30
@retrofox At least this way the user is informed of a way forward to accomplish what they want to do; we're not removing something they may have seen at another time and leaving them confused 🙃 . And it avoids the work of syncing the two settings for the time being.

**Closed** 2019-04-10 10:52 UTC
Labels: [Goal] Gutenberg, [Pri] Low, [Type] Bug
