### ISSUE TITLE
Line break formatting not working on Posts Pages or Blog Posts block

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#61055] opened 2022-02-12 22:24 UTC
### Quick summary

I had a user in chat asking how to make their Haikus have the correct formatting on their Posts pages. None of the line breaks were being respected:

<img width="1283" alt="Markup 2022-02-12 at 10 54 33" src="https://user-images.githubusercontent.com/51870544/153730163-317c111b-9c68-4bab-bc82-d540d9250a46.png">

I initially suspected that it was because they were using the Verse block, but upon further testing I found that it doesn't work correctly with the Paragraph or Custom HTML blocks, either.

Chat Transcript: 34101630-hc

**User would like to be notified when there is a fix.**

### Steps to reproduce

1. Create a new post and add line breaks to some text; can use either the Verse, Paragraph, or Custom HTML blocks
2. Save post and make sure that you have a page that is either set as the Posts page or is using the Blog Post block
3. Check the results on the live page

### What you expected to happen

The line breaks should be respected on the Posts pages and within Blog Posts blocks.

### What actually happened

They are all placed inline and don't properly represent the linebreaks.

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

MacOS: Chrome, Firefox, and Safari

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

I tried some things in a test site such as creating a new page with a Blog Post block as well as adjusting the Excerpt/Full Post settings on both the site settings and the block settings, but the only thing I found that would present them correctly is to use the `Latest Posts Block` instead of the `Blog Posts Block` and make sure the settings were set to show the `Full Post`:

<img width="1284" alt="Markup 2022-02-12 at 11 26 36" src="https://user-images.githubusercontent.com/51870544/153730218-ca3a02c3-9acc-4cbe-b8d3-0b71111ad7e4.png">

**Comment by cuemarie** [comment] 2022-03-04 01:36
Took a look at the user's site and found that the issue is no longer occurring. Thinking this could have been resolved in a recent update, so I'll go ahead and close this, but feel free to reopen if you think this is still an issue.

<img width="978" alt="Markup 2022-03-04 at 09 30 54" src="https://user-images.githubusercontent.com/27249804/156682202-7afd0fc1-6c48-4cd1-a39f-4a1baf7bbc92.png">

**Closed as completed by cuemarie** 2022-03-04 01:36 UTC
Labels: Bug, [Pri] Normal, [Block] Blog Posts
