### ISSUE TITLE
Onboarding: Adding a plan to a domain-only site is confusing and possibly broken

### ISSUE THREAD

**Issue by nbloomf** [Automattic/wp-calypso#42857] opened 2020-06-01 18:36 UTC
I noticed this while testing the checkout flow.

#### Steps to reproduce

1. Starting at URL: `http://calypso.localhost:3000/home/:site` with a domain-only site

2. We have the option to create a site by adding a plan. That sounds great! Clicking on "Create site" redirects me to gutenboarding. So far so good.

![Screen Shot 2020-06-01 at 1 08 52 PM](https://user-images.githubusercontent.com/9310939/83441694-908ddb00-a40c-11ea-8afa-a58e45d904ff.png)

3. Eventually I get through checkout, edit my first page, and click "Launch". Then I get an opportunity to pick a domain... but I already have one! Fortunately there is an "already have a domain?" option, which I guess is the right choice.

![Screen Shot 2020-06-01 at 1 10 12 PM](https://user-images.githubusercontent.com/9310939/83440422-8bc82780-a40a-11ea-8764-80851a13d2a6.png)

4. Hmm... now I have to decide whether to transfer or map a domain. I'm not sure what those mean, but "map" sounds better than "transfer", since I'm not interested in moving the domain -- I think! This is still confusing since I got here by trying to "upgrade" a domain I already own. Why didn't they just pick that one by default?

![Screen Shot 2020-06-01 at 1 10 20 PM](https://user-images.githubusercontent.com/9310939/83440568-c8941e80-a40a-11ea-8009-45dd22545835.png)

5. Ok- I can enter my domain name here. But I get an error! Now what? And why do I have _two_ sites now, one with the right domain but no plan, and one with a bunch of random numbers in the domain name?

![Screen Shot 2020-06-01 at 1 11 45 PM](https://user-images.githubusercontent.com/9310939/83441798-bca95c00-a40c-11ea-9ad2-6c547247ea55.png)

#### What I expected

That upgrading my domain only site would upgrade my domain only site to a plan+domain site.

#### What happened instead

Going through the "obvious" upgrade flow created a _new_ site.

#### Browser / OS version
Chrome 80.0.3987.106, macos 10.14.6

#### Context / Source

#manual-testing #anxiety

**Comment by simison** [comment] 2020-06-02 09:00
This isn't related to Gutenboarding (we don't even provision domain-only sites in the new flow at the moment).

@kelliepeterson is this for your team to triage?

**Comment by klimeryk** [comment] 2020-06-02 11:00
Yup, if anything, looks like a regression in the Launch flow 🤔

**Comment by eoinsav** [comment] 2020-09-05 22:23
I just had a user in chat trying to generate an actual site from a domain-only site. They would click the "Create site" button and it takes them through the whole Gutenboarding process. We skipped all of the steps of choosing a domain and selecting a plan, but then it just ends up creating a brand new site each time.

I ended up just transferring the domain to one of these newly created sites and the domain-only site disappeared from their Calypso dashboard.

#23892730-hc

**Comment by eoinsav** [comment] 2020-09-10 15:15
Another report of the above issue: #23756344-hc

The user ended up creating 2 brand new sites so I ended up just moving the domain over to one of the sites.

**Comment by klimeryk** [comment] 2021-02-10 11:33
I've tried to reproduce this issue but was not able to - the domain-only site was properly transformed to a regular one (with the custom domain attached). Please re-open if you encounter this issue "in the wild" 🙇

**Closed by klimeryk** 2021-02-10 11:33 UTC
Labels: Domains, Launch, Pre-launch, [Type] Bug
