### ISSUE TITLE
Inconsistent Menu Experience between Default View and Classic View

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#94489] opened 2024-09-12 12:47 UTC
### Quick summary

The sidebar navigation on the dashboard has an inconsistent menu experience. This throws off not only the users but also Happiness Engineers when navigating the user's site dashboard. 

Some of the issues that I noticed:
1. Menu items change their location ( e.g: `Marketing` gets shifted from `Tools` to `Hosting` in Classic View )
2. Menu items get renamed ( e.g: Backup becomes VaultPress Backup in Classic View )
3. Missing menu items ( e.g: Site Monitoring, Advertising, Monetize, Server Settings, etc are missing in Classic View )

### Steps to reproduce

1. On an Atomic site, go to Settings > General and enable Default View.
2. Observe the sidebar navigation menu items.
3. On a new tab, go to Settings > General and enable Classic View.
4. Observe the inconsistency in navigation menu items. 

### What you expected to happen

Expected the sidebar navigation menu to be consistent

### What actually happened

Sidebar navigation menus are not consistent

Example screenshot for Settings menu in Default View:

![image](https://github.com/user-attachments/assets/07c2dc2b-3c46-48b6-a440-afe53835defd)

Example screenshot for Settings menu in Classic View:

![image](https://github.com/user-attachments/assets/4beca938-14cc-463b-b480-cca881de645b)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by devNigel** [comment] 2024-09-15 18:25
> I don't think this is a fair expectation. As far as I understand these are expected to be different and this is working as intended.

I do think it is a fair expectation from the user's perspective. 

> Classic view enables the core menu for the site. Default view uses wpcom's customized menu.

Understood. But what exactly are the technical reasons for the WPcom customized menu items to:

- jump to a different place,
- have a different name,
- or in some cases, even be called by a different name ?

**Comment by Addison-Stavlo** [comment] 2024-09-16 19:17
> But what exactly are the technical reasons for the WPcom customized menu items to: jump to a different place, have a different name... in the Classic view?

Not so much technical reasons but by design. That was part of the intent behind the untangling and classic view projects.

Previously all WPcom users were on 'default' which is our custom menu that is divergent from core. Many users have no issue with this and are used to it, so there is no reason to change it for them.

With the focus on 'developers^3' the desire was to enable an experience as close to core as possible. So we use the core menu which will have a different ordering and display of items by default. Between default and core, they may also be naming changes or conflicts with the same name. This also requires us to add some menu items to it (like the hosting drawer), where named and positioned strategically throughout the project taking into account user testing and stakeholder input. (@lucasmendes-design and @davemart-in may have more context here)

The have different names and positions because they are expected to. One is expected to hold up to our legacy custom menu which many users are used to, the other is expected to reflect the core experience as much as possible for users who prefer that.

> I do think it is a fair expectation from the user's perspective.

Could you elaborate on this? Why would a user change their interface setting if they want the one they are currently using? Or not change back to the one they preferred?

**Comment by davemart-in** [comment] 2024-09-16 19:28
My perspective aligns with @Addison-Stavlo's. 

I could see us continuing to align these two interface options with time, but this would need to be prioritized as a series of projects, probably a couple months worth of work for a single team.

Happy to keep this issue open, if anything as a reminder that we should eventually get around to this. But for now, I don't know that we should prioritize picking up this work.

**Comment by davemart-in** [comment] 2024-10-14 18:46
I'm going to close this out. It's a known issue and it's intentional for now. Like I said in my previous comment, we should circle back to this, but I'm not sure when it will happen.

**Closed as completed by davemart-in** 2024-10-14 18:46 UTC
Labels: Bug, [Pri] Low, [Feature] Calypso & wp-admin Navigation, Triaged, [Platform] Atomic, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Other Infrastructure
