### ISSUE TITLE
Chat: Time out error on Olark chat endpoint.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#51517] opened 2021-03-29 19:40 UTC
Reported by @beaulebens  in p1617045246024900-slack-C029GN3KD

The Olark endpoint can time out with a 504 error. Reported using Chrome on iOS.

![Image from iOS](https://user-images.githubusercontent.com/349751/112890512-d4cd2480-908b-11eb-9ec0-fd5d5b13cbfb.png)

**Comment by kwight** [comment] 2021-03-29 19:41
This might be the call: https://github.com/Automattic/wp-calypso/blob/38c37bbfe35b8c741c4e346637987ddc0fb3ab59/client/state/happychat/user/actions.js#L29

**Comment by simison** [comment] 2021-03-30 12:04
@mattwondra hi! Does this fall under your purview?

**Comment by mattwondra** [comment] 2021-03-30 21:38
> @mattwondra hi! Does this fall under your purview?

Not explicitly, no. But I have some familiarity with the code paths and checked it out. I'll update the Slack thread above with links to some of what I'm referencing below.

I looked at **Grafana stats for the endpoint** — For API successes, the 95th percentile timings seem in line with recent trends (so majority of cases should not be impacted). The 99th percentile timings are significatly elevated in short bursts, so some small amount of users are seeing slower performance which could ultimately timeout. For API errors, nothing seems off at all. It's not clear to me whether errors like this 504 would actually add to error counts in this stat.

_p95 — No obvious spike right now:_

<img width="1295" alt="Screen Shot 2021-03-30 at 4 25 22 PM" src="https://user-images.githubusercontent.com/518059/113059353-f35b1a80-9174-11eb-9d2e-511f66c12d35.png">

_p99 — Spike more obvious, meaning 1-5% of users are impacted:_

<img width="1298" alt="Screen Shot 2021-03-30 at 4 25 53 PM" src="https://user-images.githubusercontent.com/518059/113059415-08d04480-9175-11eb-9db1-6ef389d751d2.png">



None of the **related code paths** have been changed recently. Those paths reference other WPCOM API functionality (to check the user's subscriptions and sites in order to decide what level of support to offer) so it's possible this performance hit is actually a secondary effect of some other WPCOM subsystem/class having poor performance. Hard to tell without really deep diving, and I'm not sure that's merited at this stage.

The Grafana stats show that this endpoint has had similar sized and duration blips a handful of times in recent months. So it seems very possible that whatever's causing the problem is self-correcting.

#### My thoughts

This will probably also "self-correct" but it may not. I'll set a reminder to re-check the timings in a couple days.

It's hard to say exactly how many users are being impacted. My best guess is that this endpoint failing will result in an inability to contact us (I'd expect the Contact Form would be in a perpetual "loading" state). If we need a next step, maybe that's logstash-logging API errors here from the front-end so we can see how many there are and prioritize accordingly.

If the timings are not improving, finding the underlying cause (with no obvious code changes) would still be basically exploratory surgery. Instead I'd recommend looking at D51782-code and seeing if its performance implications can be improved at all. There's a very clear spike in response time and variance starting with that diff, so just making that faster would lower the baseline and may solve the problem indirectly.

_mean response time over last year, showing marked increase caused by that diff:_

<img width="1295" alt="Screen Shot 2021-03-30 at 4 27 43 PM" src="https://user-images.githubusercontent.com/518059/113060477-4c777e00-9176-11eb-8343-77fc7aa658a1.png">

**Comment by mattwondra** [comment] 2021-04-02 17:59
The poor performance has sustained. Looking at the p95 graph with the past few days included, it seems clearer that the performance has been getting worse slowly over the past few weeks. So maybe there wasn't a single code change, but we've hit a tipping point from some slower growth (a side effect of some new feature as it's being adopted, or a slower launch rollout like Nav Unification?)

<img width="1157" alt="Screen Shot 2021-04-02 at 12 55 35 PM" src="https://user-images.githubusercontent.com/518059/113440997-1246f000-93b3-11eb-9eea-5effd45c9808.png">

I'm deploying logstash logs on these failures (#51654) so we can try to identify commonalities between users who are seeing these problems, and hopefully reproduce it ourselves. I'll add a link to see those logs in the Slack thread mentioned in the issue description.

**Comment by simison** [comment] 2021-04-08 10:50
@mattwondra Thanks for analysing this! Any new insights from those logs?

@obenland would your team be able to look into this?

Another good thing could be to make the error less scary, or hide it entirely. For our purposes we should just log these failures and notice it via anomaly alerts in something like Grafana.

**Comment by obenland** [comment] 2021-04-08 17:13
Not any time soon, I'm afraid.

>  I'd recommend looking at D51782-code and seeing if its performance implications can be improved at all. 

@dzver Would you mind taking a look when you get a chance?

**Comment by mattwondra** [comment] 2021-04-08 17:54
> @mattwondra Thanks for analysing this! Any new insights from those logs?

Based on logs from #51654 this endpoint is only erroring a handful of times per day (not bad for an endpoint that's called with every Calypso pageload). I've only seen a couple 504 timeouts like originally reported. **So even though we're seeing increased response times, I don't know that it's translating to new errors for users.**

The response times are maintaining the patterns shown in the graphs above:
- p95 is getting noisier and trending upward over the past weeks
- p99 spikes hard every day (though not always at the same time)
- median is steady

The way I interpret this is:
- most users are not experiencing any increased response time
- some users are getting responses that are slower but likely don't change their experience using the app
- a few users are getting response times during brief windows of time each day that _could_ impact their experience, but likely only if they are landing on the Contact Form page

I don't love the trend, but it's unlikely right now that users are noticing.

Another small oddity — the spikes don't seem to correlate with endpoint usage. Here's a graph showing p99 and count (how many times the endpoint is requested):

<img width="1244" alt="Screen Shot 2021-04-08 at 12 50 06 PM" src="https://user-images.githubusercontent.com/518059/114073529-ff2b9880-9868-11eb-8698-af0bb403f8ca.png">

The yellow line is `count` and should correlate with Calypso usage. Last week you can see that the green `p99` spikes happened generally at the tail end of each day's traffic peak. But this week the response times seem to spike a bit before traffic peaks. (And there was even noise over the weekend around 0:00 on 04/04, when `count` was at a low point).

I don't know how to interpret those observations, but I'm hoping it maybe triggers a thought with someone who knows WPCOM internals.

**Comment by dzver** [comment] 2021-04-08 21:58
I debugged it and to my surprise, looks like it is D51782-code indeed, no matter how simple it is. The problem is that for some reason, the renews_monthly function queries the transactions table.

I submitted D59946-code that should resolve the problem.

**Comment by mattwondra** [comment] 2021-04-12 21:12
@dzver shipped D51782-code and it's made a notable improvement. Here's the `upper` (worst case) performance from the past few weeks — I'll let you guess when his code deployed :)

<img width="1209" alt="Screen Shot 2021-04-12 at 4 11 52 PM" src="https://user-images.githubusercontent.com/518059/114463317-e34a2e80-9ba9-11eb-8aca-87bd74ba9b6b.png">

I'm going to keep an eye on this for another full week or so before closing this issue.

**Comment by mattwondra** [comment] 2021-04-16 18:43
The performance benefit has continued through the week. The number of error messages users see has remained steady, but still exceptionally low considering the endpoint is hit on every Calypso pageload. It's likely this has always been the error rate for this endpoint.

I'm going to close this issue.

**Closed as completed by mattwondra** 2021-04-16 18:43 UTC
Labels: Bug, [Pri] Normal, Help
