### ISSUE TITLE
Gutenlypso: Contributors can't set post visibility, sticky posts or schedule posts

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#29213] opened 2018-12-07 05:19 UTC
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/block-editor/post/ as a contributor to a simple site
2. Try to set post visibility 

#### What I expected

1. To be able to set post visibility as per the Calypso classic editor
2. To be able to set post as sticky
3. To be able to set date to schedule

#### What happened instead

Can't set post visibility at all, nor sticky or schedule

#### Browser / OS version

Chrome and Safari on macOS

#### Screenshot / Video

<img width="388" alt="calypso classic privacy" src="https://user-images.githubusercontent.com/128826/49629088-6637a900-fa33-11e8-847a-b5049d1a5024.png">

<img width="330" alt="screen shot 2018-12-07 at 4 23 18 pm" src="https://user-images.githubusercontent.com/128826/49631101-743df780-fa3c-11e8-83d6-761a104ddecf.png">

<img width="280" alt="screen shot 2018-12-07 at 3 19 02 pm" src="https://user-images.githubusercontent.com/128826/49629097-72bc0180-fa33-11e8-8b68-7e01fe952958.png">

#### Context / Source

Manual testing new Gutenberg editor in Calypso

**Comment by apeatling** [comment] 2018-12-13 20:57
@vindl This feels bad, but since it's only contributors, and we're still opt-in for existing users it can probably be punted. I would love to see a fast followup on this one though.

**Comment by vindl** [comment] 2018-12-13 21:07
Thanks @apeatling, it's already at the top of the Backlog column so it might be picked up before the release too. cc @Automattic/lannister

**Comment by kwight** [comment] 2018-12-14 22:13
I'm wondering if this has to do with an unverified email. Assuming no other big opt-in related stuff, I'll be able to work on it top priority Monday.

**Comment by kwight** [comment] 2018-12-17 20:54
This had nothing to do with unverified email; this is all consistent with core wp-admin behaviour. I'll start digging into what's involved to add these Calypso-specific elements to Gutenlypso.

**Comment by kwight** [comment] 2018-12-17 23:17
Additional concerns: p7jreA-20B-p2.

**Comment by kwight** [comment] 2018-12-18 17:12
Tagging design review here too; I think we need to first establish if this is **a)** desired behaviour, as it's consistent with core and more "closed", or **b)** a bug, because it's not consistent with Calypso's ongoing behaviour (in which case, maybe the Calypso editor should be tightened up also).

**Comment by kwight** [comment] 2018-12-18 17:13
Oops 🙃 Still very open.

**Comment by kwight** [comment] 2018-12-19 23:31
After discussion on Slack and p7jreA-20B-p2, I'm closing this as expected behaviour, and I've opened #29644 to follow up with rolling back Calypso editor behaviour.

**Closed by kwight** 2018-12-19 23:31 UTC
Labels: [Goal] Gutenberg, [Pri] High, [Type] Bug
