### ISSUE TITLE
Navigation Block: Mobile menu overlaid by content in Cover block

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#81459] opened 2023-09-06 14:36 UTC
### Quick summary

A Navigation block that is inside a Cover block will have it's mobile menu shown "behind" the content in the Cover block.

![CleanShot 2023-09-06 at 15 32 57@2x](https://github.com/Automattic/wp-calypso/assets/51966986/6fea3e0e-5295-4dba-bfa7-cd63eb3d2463)

### Steps to reproduce

1. Add a Navigation menu inside of a Cover block
2. Add another Cover block below that one with content in it
3. Observe how the mobile view of the Navigation menu will be “behind” the content of the Cover block
![CleanShot 2023-09-06 at 15 27 40@2x](https://github.com/Automattic/wp-calypso/assets/51966986/ff2a4fee-c182-4436-9d86-c1aea2e44643)

### What you expected to happen

The menu should be "on-top" of any content on the page/post

### What actually happened

The menu is "under" the content in the Cover block

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Moving the Group+Navigation block outside of the Cover block seemed to resolve the issue.

Tested on Livro theme
Reported in 6737383-zd-a8c

**Comment by cuemarie** [comment] 2023-09-06 22:14
Duplicate of https://github.com/Automattic/wp-calypso/issues/75439

**Closed as not planned by cuemarie** 2023-09-06 22:14 UTC
Labels: Bug, [Pri] Normal, Triaged, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks
