### ISSUE TITLE
Paragraph Font Family overridden by Global Style Link Font Family for links in the Paragraph

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#74280] opened 2023-03-09 15:33 UTC
### Quick summary

When a Paragraph has a link in it, the link does not use the Font Family set for the Paragraph. It uses the link font family as set in Global Styles.

### Steps to reproduce

I used the Zaino theme

1. Go to **Appearance > Editor** and edit the Home template
2. Add a Paragraph block
3. Highlight a few words in the Paragraph block and make them a link
4. Change the Font Family for the Paragraph block to `Texturina`
5. Go to **Styles > Typography > Links**
6. Change the font to EB Garamond
7. Save the template

### What you expected to happen

I expected the entire paragraph, including links, to use the `Texturina` font

### What actually happened

The links used the `EB Garamond` font

### Impact

All

### Available workarounds?

Yes, easy to implement

### Logs or notes

I added this CSS as a workaround:

```
.has-texturina-font-family a:where(:not(.wp-element-button)) {
    font-family: var(--wp--preset--font-family--texturina) !important;
}
```

6028752-zen

**Comment by cuemarie** [comment] 2023-03-12 02:05
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: 
- Replicable on Core? **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated in all 3 testing environments with FSE themes.

**Simple Example**

https://user-images.githubusercontent.com/27249804/224520170-f6682ba7-3456-438a-a51e-b6b049e8240e.mp4

📌 ACTIONS
- Marked as Triaged for Quality Squad review

📌 NOTES
- I've seen a few reports of Global Styles overriding block-specific settings, both here and in `/gutenberg`; wondering if this larger discussion is relevant: https://github.com/WordPress/gutenberg/issues/45086

**Comment by dsas** [comment] 2023-03-27 21:02
@cuemarie, that's right. This issue might explain a bit more directly: https://github.com/WordPress/gutenberg/issues/44931
 
Basically GB is working as intended, but has a confusing UX. I'm going to close this as not specifically related to Dotcom.

Thank you for reporting @ccwalburn   🙇‍♂️

**Closed as not planned by dsas** 2023-03-27 21:02 UTC
Labels: Bug, [Pri] Normal, [Status] Core Fix Needed, Triaged, [Platform] Simple, [Platform] Atomic, [Feature] Global Styles
