### ISSUE TITLE
Domain Management: Change ICANN verification message copy

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2478] opened 2016-01-15 17:41 UTC
Raised by @umurkontaci 

Currently, the wording for the ICANN verification message is a bit lousy. (The bottom part)

![icann-message-in-domains-section](https://cloud.githubusercontent.com/assets/1119271/12360275/04a68fca-bb85-11e5-8b64-3b6d31250653.png)

We could change it to something like "You might be seeing this message due to incorrect contact information"

We should also add link to update contact information.

Comment from @breezyskies 

> Note that @mikeshelton1503 and @ranh have been working on copy for ICANN verification compliance (p6qnuF-uN-p2 #comment-558).
> 
> This particular message could be synced up with their copy (although once implemented, the user would also see the yellow warning at the top of the page). Here's the full screenshot / placement for reference:
> 
> ![icann](https://cloud.githubusercontent.com/assets/3011211/10020226/9ae7f832-60f6-11e5-901d-c9908fbce5aa.png)

**Comment by wensco** [comment] 2016-02-29 18:01
I think it would help to add in a link to our [support documentation](https://en.support.wordpress.com/register-domain/#email-validation-and-verification) since it explains why users have to do this and also shows them what the email should look like.

AFAIK, things that may trigger a verification requirement include:
- a new domain registration
- a change to previous/original contact information
- transfers for domains whose original registration pre-dated ICANN's policy change to require verification
- invalid contact info (which could also be grounds for suspension)

**Comment by wensco** [comment] 2016-03-07 19:19
cc @ranh, based on a comment above, it sounds like you're already working on this. :)

**Comment by folletto** [comment] 2016-05-20 16:02
Was there any update on this? :)

**Comment by ranh** [comment] 2016-05-22 13:33
I had a feeling this was already fixed in a different issue. ATM I can't reproduce this with a newly registered domain (and an unverified email address).

Based on the above screenshot, how about this:

> You have to verify the email address used to register this domain before you can make changes. Look for the verification message in your email.
>
> (Resend verification email)
>
> Go to Contacts and Privacy to update your email address. [Learn more](https://en.support.wordpress.com/register-domain/#email-validation-and-verification).

**Comment by klimeryk** [comment] 2016-08-02 16:01
I was wondering if we could improve this flow while we are at it. Currently, we show a notice:
<img width="717" alt="2016-05-11_1447" src="https://cloud.githubusercontent.com/assets/7942966/15192503/7ed01538-1787-11e6-84ba-416982a2e607.png">

The "Fix it" link takes you to the domain view - where you are shown the ICANN verification message that's been discussed above:

<img width="743" alt="screen shot 2016-08-02 at 17 59 18" src="https://cloud.githubusercontent.com/assets/3392497/17335625/de7741c0-58da-11e6-8845-5a578b27a4f6.png">

However, the position and the design of the message (in the middle of the view) could be confusing for the user - they probably expect something that stands out more. Or even that they _don't_ need to do anything else - they did just click a "Fix it" button ;)

How about simplifying this a bit and just using the notice to resend the verification email as the primary action? With a smaller link to update the contact information?

**Comment by breezyskies** [comment] 2016-08-02 17:59
> How about simplifying this a bit and just using the notice to resend the verification email as the primary action? With a smaller link to update the contact information?

+1

**Comment by ranh** [comment] 2016-08-03 10:15
I suggested "your domain may be lost forever" originally but @wensco noted that this is not actually correct, the domain just gets suspended. So we should also change it to say "Your domain example.com may be suspended if [...]"

**Comment by lancewillett** [comment] 2017-02-06 20:04
See also suggested UX improvements in https://github.com/Automattic/wp-calypso/issues/11208

**Comment by mashmac2** [comment] 2017-04-24 09:51
I've run into quite a few users who keep clicking Resend, but their domain's contact info is set to a different email address, which is why they're not receiving it. 

When this gets reworked, could we please add a warning to the user if their domain contact email is different from their WordPress.com account email (and different from any email forwarding addresses)?

**Comment by wensco** [comment] 2017-04-27 20:21
We could possibly adjust the "success" message when a user clicks resend. Currently we show this:
<img width="673" alt="email success" src="https://cloud.githubusercontent.com/assets/7942966/25502632/68415db6-2b65-11e7-9ae4-f9aff53ae342.png">

We could modify that to "We successfully resent the ICANN verification email to [registrant contact email]." That way they would know which inbox to check.

**Comment by ranh** [comment] 2017-04-30 10:53
A few other ideas for the resend email flow were mentioned in p2MSmN-5Y4-p2

We should refrain from referring to this as the "ICANN verification email". 

ICANN is not a name our users care about and we should not use it in user communications. 

Also, just in general, ICANN is involved with anything related to domains. Since we don't talk about "ICANN domains" or "ICANN renewal reminders" or "ICANN contact information", we should not be talking about "ICANN verification emails".

**Comment by mikeshelton1503** [comment] 2017-07-06 00:17
I created a fix for this in #15880 but did exclude a suggestion made here:

> How about simplifying this a bit and just using the notice to resend the verification email as the primary action? With a smaller link to update the contact information?

I liked this suggestion and had planned to implement however as I got into I realized that relying on the message itself to send the email makes it harder to communicate the 1) issue 2) that the message has been sent and 3) how to resend. All of that could take place in the notice however would cause it to be too long and also notices really aren't great for that kinda of behavior.

**Closed** 2017-07-13 11:38 UTC
Labels: Domains, [Pri] Normal, [Status] Needs Design Review, [Type] Enhancement
