### ISSUE TITLE
FSE beta: Site editor fails to load templates with mapped domain

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#57484] opened 2021-10-29 21:05 UTC
#### Steps to reproduce

On an unpublished test site, I am unable to load anything in the site editor after mapping a domain to the site:

![Screenshot from 2021-10-29 13-05-32](https://user-images.githubusercontent.com/6265975/139501306-afa26ef6-99db-4bea-bda6-f3e0cf7e4290.png)

I get the following error messages:

![Screenshot from 2021-10-29 13-09-18](https://user-images.githubusercontent.com/6265975/139501320-76fd1211-fb9d-42c5-a18a-59cdf5d4249d.png)

This happens even on my phone, so it's not related to sandboxing or anything like that.

I found this error message interesting: `Blocked loading mixed active content "http://noahtallen.com/?_wp-find-template=true"` . Interestingly, if I paste this into the browser, it redirects to https, and completes successfully. Also noting that HTTPS was already provisioned for this domain. (https://noahtallen.com works correctly)

But the weird thing to me is that the site editor is loading nearly everything on the noahtallen.wordpress.com domain... so why is that one request coming from the mapped domain? Unless some major updates happened overnight, **I think this could be related to FSE + mapped domains and/or HTTPS**. 

#### What I expected
The site editor to load with templates and everything

#### What happened instead
No templates or content is loaded

#### Browser / OS version
Linux (PopOS / Firefox), also latest version of mobile Safari

**Comment by zaguiini** [comment] 2021-11-05 18:43
@jeyip and I took a look at this issue and we discovered what's causing the problem.

Whenever someone buys a site with a mapped domain (let's use https://my-custom-domain.com for this example), the domain isn't immediately available -- there is a considerable gap between domain purchasing and global availability. Activating it takes a while.

Following the FSE onboarding flow, when someone finishes checkout, they're redirected to the site editor.

When the site editor opens, it tries to load the theme-provided block template for the current page it's editing. In this case, the home page. It does so by fetching `https://my-custom-domain.com/?_wp-find-template=true`. But as pointed above, the domain is not yet publicly accessible, so the request fails, Gutenberg doesn't get the template and halts execution.

A possible solution would be to hydrate Gutenberg from Calypso with the necessary information. When loading Calypso, we know which theme the customer is using, we also know the slug for the page they're trying to edit, so we can pre-fetch the desired block template and inject it into Gutenberg directly, minimizing the need for that request.

We can still leave the fetching method as a fallback, in case we don't hydrate Gutenberg with the necessary block template. That would keep non-WPCOM sites working as expected.

For non-WPCOM sites, that problem would never happen because the mapped domain will always work. You can't access WP Admin without having the domain publicly accessible.

Would love to hear if anyone has other suggestions and/or if we missed something. Thanks!

**Comment by noahtallen** [comment] 2021-11-05 18:47
Thanks for investigating!

> But as pointed above, the domain is not yet publicly accessible, so the request fails, Gutenberg doesn't get the template and halts execution.

One thing I'm curious about is why it fails to load even now, a week after mapping the domain 🤔 Shouldn't the domain be publicly accessible by this point?

Or, another thought, I wonder if it's an issue with private sites. My site is still set to "coming soon". Does this prevent `?_wp-find-template` from finishing successfully in the context of the request from WordPress?

**Comment by zaguiini** [comment] 2021-11-05 18:55
> Shouldn't the domain be publicly accessible by this point?

It is. I can enter noahtallen.com and see the "Coming soon" message.

> Does this prevent ?_wp-find-template from finishing successfully in the context of the request from WordPress?

I'm not sure. I'm not able to access your site's template configuration, but I do have a site for myself and I can see it, even with it marked as "coming soon".

---

Apparently, the current method of fetching the template it's pretty problematic. Will the proposed solution fail on a more exotic, custom theme structure? Is someone besides Automattic making FSE themes? Will FSE be open-sourced in the future?

**Comment by zaguiini** [comment] 2021-11-05 19:32
For WPCOM domains, I can retrieve the block template settings even though the site is marked as private.

For mapped domains that are private/"coming soon", I cannot retrieve the block template settings using the custom query parameter.

For mapped domains that are publicly available and passed the query parameter, it works.

**Comment by noahtallen** [comment] 2021-11-05 19:37
> Is someone besides Automattic making FSE themes? Will FSE be open-sourced in the future?

Definitely, and FSE is already open source! :P 

That's interesting. So If I set my site to public, it might start working.

**Comment by noahtallen** [comment] 2021-11-05 19:39
> So If I set my site to public, it might start working.

I just tried it, but the site editor isn't working immediately. So it's probably not related to private sites 🤔

**Comment by noahtallen** [comment] 2021-11-05 19:39
I think it could still be related to this:

```
Blocked loading mixed active content “http://noahtallen.com/?_wp-find-template=true”
```

why is it not loading the `https` link? In the browser, it will redirect http to https, but it doesn't do that in the context of the api call

**Comment by zaguiini** [comment] 2021-11-05 19:41
That's one of the problems, yes. The `post.link` attribute, for some reason, has the HTTP protocol, but the site editor is running on HTTPS. That would fix the problem of public sites. Private sites would still fail, though. I can't access the template URL when the site is private + mapped to a custom domain.

**Comment by zaguiini** [comment] 2021-11-05 19:55
Won't work:
- Trying to fetch the template information from a mapped domain that is not activated yet;
- Trying to fetch the template information from a mapped domain that is marked as "coming soon";
- Trying to fetch the template information from a mapped domain from Calypso because of mixed protocols. `post.link` returns the HTTP link and we're not conforming protocols.

Does work:
- Fetch the template information from a WPCOM domain from Calypso since it's the same protocol. `post.link` is right for some reason.

**Comment by noahtallen** [comment] 2021-11-05 20:23
> I can't access the template URL when the site is private + mapped to a custom domain.

I'm wondering if this still works on the local site/backend in question, because it theoretically has permissions to access the domain

**Comment by zaguiini** [comment] 2021-11-09 17:32
There are several problems right now:
- The Gutenberg iframe attempts to make a request to the .wordpress.com subdomain. Unfortunately, because we've mapped a custom domain (ex. .blog), it is now the site's primary domain. As a result, the request is redirected from https://example-site.wordpress.com/?_wp-find-template=true to https://example-site.com/?_wp-find-template=true, which turns into a cross-origin fetch. Because the right CORS headers aren’t present, the request fails;
- Another problem of the redirection happens when the domain isn't yet ready, causing the request to fail even though we could access the .wordpress.com subdomain without mapping or setting the domain as primary;
- The redirected cross-origin fetch triggers flawed WPCOM SSL certification verification logic. SSL certification fails when it should pass for the site, which downgrades our request from HTTPS to HTTP;
- To top it all off, the Gutenberg iframe fetch isn’t passed the correct credentials. Even if the above problems are fixed, requests to private simple sites fail because they're not provided with authentication cookies.

The FSE Design Tools pod is currently looking for solutions. The 4th problem is the easiest to solve and a PR should arrive soon. The other three have some proposed solutions but nothing concrete yet. I'll keep this up to date.

**Comment by zaguiini** [comment] 2021-11-10 15:40
We found out that the root cause is the redirection from the `.wordpress.com` domain to the mapped domain. This happens on WPCOM and simply bypassing it (meaning not redirecting at all if the query parameter is there) fixes the issue, even for private sites and/or domains that are in the process of activation.

The whole discussion is on paYE8P-18P-p2 and the proposed solution at D69819-code.

**Comment by creativecoder** [comment] 2021-11-16 22:27
D69819-code has been deployed, which should resolve this issue. Thanks again @noahtallen for bringing it to our attention!

**Closed as completed by creativecoder** 2021-11-16 22:27 UTC
Labels: [Pri] High, [Goal] Full Site Editing

**Comment by noahtallen** [comment] 2021-11-16 22:32
Thanks a bunch! I just verified my site is now working in the site editor. 🙇
