### ISSUE TITLE
Deleted image still shows in media library (classic and calypso views)

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#57651] opened 2021-11-04 14:37 UTC
### Quick summary

A deleted image file is still showing up in the media library on a site (with a blank thumbnail). This image was used in a post (body) and as a featured image on that post. The image was deleted a week ago.

### Steps to reproduce

1. Go to site and view Media Library or go to post with the deleted image

### What you expected to happen

The deleted image should not appear

### What actually happened

The deleted image shows as a blank thumbnail in the media library

<img width="981" alt="Markup 2021-11-04 at 13 42 59" src="https://user-images.githubusercontent.com/51966986/140333357-05306311-37e5-4275-90e3-151ca458446e.png">

### Context

Customer report #32357184-hc

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Simple

### Reproducibility

Once

### Severity

One

### Available workarounds?

No but the platform is still usable

**Comment by kosiew** [comment] 2021-11-10 08:12
Hi @philnick206 ,

Thanks for reporting this and the detailed steps.

I however could not reproduce this on a Simple site - https://wp20180808.wordpress.com/wp-admin/post.php?action=edit&post=2591

Closing this. Please reopen if you have additional context to add on reproducing the issue.

**Closed as completed by kosiew** 2021-11-10 08:12 UTC
Labels: Bug
