### ISSUE TITLE
Posts: featured image updates not reflected in post list

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#8101] opened 2016-09-16 16:35 UTC
video: https://cloudup.com/cjB_F8eutkv
#### Steps to reproduce
1. Starting at URL: wordpress.com/posts
2. Click to edit a post that has a featured image
3. In editor, remove the featured image from the post
4. Update post to save changes
5. Return to posts list
6. Notice that post cards persist outdated featured image, even after refresh
7. Bonus: change featured img then view posts lists - new image shows. Then, delete the new feat img. Post list will show original img, despite it not being selected.
#### What I expected

The post list to display most current version of the post and post meta

**Comment by lancewillett** [comment] 2016-10-18 23:07
#bug-scrub notes

I was able to repeat most of the steps, except _6. Notice that post cards persist outdated featured image, even after refresh_ — in my testing a page refresh showed the update correctly. Testing with Mac-n-Chrome.

**Comment by rachelmcr** [comment] 2017-08-22 16:03
I can't reproduce the main issue or the bonus issue reported here. Although the featured image in the post list doesn't immediately update when I go back to the list, it's updated as soon as I refresh the page. (Tested with Mac 10.12.6, Chrome 60.)

I'll close this issue for now since I can't reproduce it anymore.

**Closed by rachelmcr** 2017-08-22 16:03 UTC
Labels: Posts, [Type] Bug
