### ISSUE TITLE
Editor: Switching to Visual tab hangs or fails if media present in post

### ISSUE THREAD

**Issue by slfrsn** [Automattic/wp-calypso#3683] opened 2016-03-01 06:28 UTC
#### Steps to reproduce
1. Create a new post or page
2. Add some text to the editor
3. Insert an image
4. Click back and forth on the Visual and HTML tabs until they stop working or produce a delay of many seconds

#### What I expected
Switching between Visual and HTML tabs should be responsive (within reason) and consistent. 

#### What happened instead
When media is added to a post or page, the act of switching Editor tabs becomes delayed (length of delay appears to be intermittent) or fails altogether (requiring a page refresh). Delays have been observed to last anywhere from 1 to 15 seconds.

#### Browser / OS version
Running OS X 10.11.3 and confirmed the issue in Safari 9.0.3, Firefox 44.0.2 and Chrome 48.0.2564.109

#### Screenshot / Video
![feb 29 2016 21 58](https://cloud.githubusercontent.com/assets/6977140/13419490/7ad32c54-df33-11e5-8bfa-365a1aaa30ce.gif)

**Comment by aduth** [comment] 2016-03-11 14:20
This seems to be a duplicate of #3709. Probably less about media being in the post, and more about the post having yet to have been autosaved at the point of switching modes.

**Closed by aduth** 2016-03-11 14:20 UTC
Labels: Editor, OSS Citizen, [Type] Bug

**Comment by aduth** [comment] 2016-03-11 16:46
@slfrsn : With #3983 having been merged, you should find that this is no longer an issue. Please feel free to reopen the issue if you're still having any trouble.

Thanks again for the detailed explanation of the issue.
