### ISSUE TITLE
Editor: Publicize checkboxes should be disabled after publish

### ISSUE THREAD

**Issue by codebykat** [Automattic/wp-calypso#688] opened 2015-11-24 21:49 UTC
- Create a new post and type some content
- Check some publicize boxes in the editor
- Click Publish
- Note the checkboxes remain checked but are not disabled (so you can uncheck them, even though it wouldn’t do anything)
- Refresh the page
- Boxes are properly checked+disabled, reflecting that publicize has already happened

If we want to get extra fancy we can check the post meta to verify that Publicize succeeded.

**Comment by jkudish** [comment] 2015-11-27 22:13
So this is trickier than you'd think, because of Publicize being an async process on the WP.com side.

By the time the post has published and the REST API returns an updated version of the post from the `/post/new` endpoint, publicize hasn't fired off yet, so the metadata returned at that time doesn't yet indicate whether or not the selected publicize services have publicized or not. That's why the UI doesn't disable the checkboxes.

If you update the post shortly after publishing it, regardless of the update, you'll see that the checkboxes are then disabled, since the updated metadata returned at that time, will reflect that publicize has fired. So it's not a UI bug.

We do receive a `_publicize_pending` flag, which indicates Publicize will fire off. We can "naively" disable all Publicize checkboxes when that meta is present. I am not sure if that's better UX than not disabling anything. We'd then automatically do a "proper" update once we have more accurate publicize results.

What do you think?

In a future update of publicize we could return more specific metadata. Here's an idea:

```
publicize_results: [
      1234567: pending,
      1234569: done,
      1237809: failed,
]
```

where each number is a publicize connection

**Comment by alisterscott** [comment] 2017-05-12 05:50
Confirm this is still an issue.

**Comment by designsimply** [comment] 2018-02-13 01:34
#bug-scrub #pre-gutenburg-bug-purge

Tested and confirmed that Sharing checkboxes are incorrectly interactive after publishing a new post and then refreshing the edit page for that post ([56s](https://cloudup.com/cfyLMdYdccE), the screen recording got a bit squished but you can still see the gist of it).

Recommend keeping this open if it causes user confusion. @SiobhyB or @KokkieH, may I have your opinion about severity for this issues—do you think it causes very much user confusion?

**Comment by KokkieH** [comment] 2018-02-13 04:03
I think it would be a good enhancement to somehow indicate in the editor that a post has been publicized - spares users having to go check their social media accounts directly - but I can't say that I've seen any confusion surrounding this. The bulk of Publicize issues I come across are just for Publicize failures.

**Comment by SiobhyB** [comment] 2018-02-13 16:22
I'll echo what Herman said. :) It sounds like a good enhancement but I haven't seen any confusion surrounding this.

**Comment by cathymcbride** [comment] 2020-10-13 18:54
This looks to be OK in the current version. Closing.

**Closed by cathymcbride** 2020-10-13 18:54 UTC
Labels: Editor, Sharing, [Pri] Normal, [Type] Bug
