### ISSUE TITLE
Hamburger button overlapping block inserter button on post editor on wp-admin.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#40426] opened 2020-03-25 07:42 UTC
See fix at: https://github.com/Automattic/wp-calypso/issues/40426#issuecomment-643228577

#### Steps to reproduce

1. Go to `wp-admin/post-editor.php`.
2. Resize your browser to mobile/tablet view (> 782px and below).

#### What happens

The hamburger button appears on top of the block inserter button. It's no longer possible to click on the block inserter menu.

#### Screenshot / Video

| Mobile | Tablet |
|----|----|
| <img width="323" alt="Screenshot 2020-05-11 at 17 41 23" src="https://user-images.githubusercontent.com/790558/81581497-1a6afb00-93af-11ea-8895-d350a87906a2.png"> |  <img width="385" alt="Screenshot 2020-05-11 at 17 49 41" src="https://user-images.githubusercontent.com/790558/81582143-f65be980-93af-11ea-80bc-f5937a0e9a73.png"> |

**Comment by simison** [comment] 2020-03-25 09:18
@jeherve was there some prior work / issue about this?

**Comment by jeherve** [comment] 2020-03-25 09:42
Yes:
https://github.com/Automattic/jetpack/issues/12320

It was previously fixed in https://github.com/Automattic/jetpack/pull/12337 for the Masterbar in wp-admin.

I'm not sure I understand what this issue is about though. Where does this happen? WordPress.com Simple, Atomic, Jetpack, wp-admin, Calypso?

**Comment by simison** [comment] 2020-03-25 11:04
On wp-admin for atomic and simple sites, on block editor when screen is smaller:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/87168/77529884-25b6a580-6e99-11ea-9cda-6cb2d71a91cd.png">

**Comment by jeherve** [comment] 2020-03-25 15:46
Interestingly my default experience is different (though not better) in Atomic, because of Calypsoify:

![image](https://user-images.githubusercontent.com/426388/77555518-9b316e80-6eb7-11ea-84cf-aa10ec9d286e.png)

If I disable Calypsoify I get what you're seeing. This would seem like a regression from https://github.com/Automattic/jetpack/pull/12337 in Jetpack. I reopened https://github.com/Automattic/jetpack/issues/12320 to track this.

This issue may need to remain open for WordPress.com simple though. The masterbar there is different from the one in Jetpack.

**Comment by sirreal** [comment] 2020-05-14 11:23
Brought over some details and screenshots from @millerf in #42060.

**Comment by sirreal** [comment] 2020-05-14 11:53
Brought this up in some masterbar-related discussions: pbAPfg-3G-p2#comment-988

**Comment by yansern** [comment] 2020-06-12 11:47
### Keeping things simple

I updated the description of this issue to limit the scope of the fix that should be done here.

Previously the issue included:
- **Hamburger button overlapping block-inserter menu on post editor on WP-Admin.**
   We'll focus on just fixing this one.

- **Hamburger button overlapping block-inserter menu on post editor on Calypso.**
  This no longer seem to be an issue as the masterbar doesn't seem to appear on Calypso anymore.

- **Unable to exit editor once you're in post editor.**
   Similar work is being done in https://github.com/WordPress/gutenberg/pull/22323 where they want to reuse the W button for this purpose.

Also, it is also interesting to note that:
- There is a bigger conversation going on at pbAPfg-3G-p2 on reviewing how the masterbar's behaviour.
- This PR attempts to reuse the W button to display the sidebar https://github.com/WordPress/gutenberg/pull/22191 (but I think this is just for Calypso and not when it's under WP-Admin?).

----

## Quick fix for the hamburger button overlap

I've created a quick fix to reposition the hamburger button on the masterbar.

The fix is in this phab patch here: D44873-Code.

I'm not sure if that's the right place to modify the CSS file. I can't quite tell if the CSS file is actually a built version that was sync'ed over from jetpack's repository? Even though I can't find the relevant files in jetpack's repository.

![2020-06-12_12-50-05 (1)](https://user-images.githubusercontent.com/1287077/84498066-34e70b80-acb0-11ea-9d3c-1c15c0ece719.gif)

**Comment by razvanpapadopol** [comment] 2020-06-23 10:09
Fixed in D44873-code

**Closed by razvanpapadopol** 2020-06-23 10:09 UTC
Labels: [Type] Bug
