### ISSUE TITLE
Social followers not displaying in stats or subscribe block count

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#71142] opened 2022-12-13 16:28 UTC
### Quick summary

Social follower counts aren't showing in the subscribe block count or in stats (this part historically hasn't been an option AFAIC recall)

Publicize connections look good and I can see that items are successfully sharing. Also intentionally synced Jetpack in case the counts weren't updated yet. 

My test site is linked to Twitter and Tumblr and the user's site is linked to Twitter and LinkedIn, all with at least 1 follower.

Tested on my test site after report from user here: p1670943697560299-slack-C03TY6J1A

Regarding the comment about the social toggle being on but greyed, this was poor communication on my part. The count appears to be on by default but on second look it can be toggled once the "show subscriber count" is toggled on

### Steps to reproduce

1. Make sure site is public and publicize is on
2. connect some socials
3. publish to the socials with a post including the subscribe block with social followers display on 
4. follow with another account on the socials 
5. update or add new post with subscribe block and publicize again
6. see that social followers not counted and not showing in subscribe block

### What you expected to happen

Once socials connected I expected the count to show in stats and in subscribe block count

### What actually happened

seeing 0 followers in both
![2022-12-13 at 17 37](https://user-images.githubusercontent.com/47717887/207388946-5c667072-7999-468e-9d0c-4dac74fdeaf8.jpg)
![2022-12-13 at 18 14](https://user-images.githubusercontent.com/47717887/207388977-d7315e67-222f-42f9-988e-9e7ab20b7352.jpg)

### Context

p1670943697560299-slack-C03TY6J1A
first commented on thread here: p7DVsv-_gqu-p2#comment-43378

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

None

### Severity

None

### Available workarounds?

None

**Comment by TimBroddin** [comment] 2022-12-19 10:38
Hey @Nic-Sevic,

I've done some investigating. It seems like the connections from the original user's site don't have any follower counts set. For LinkedIn this is quite normal, since we've only begun to fetch them last week, but for Twitter this is unusual. Could you please ask them to disconnect and reconnect these connections?

Regarding your test site, I can see in the Jetpack Social Report Card that your Twitter connection has 1 follower (which seems correct), Tumblr has none, which needs looking in to. I'm also seeing a mismatch for Tumblr with my own test account (25 followers - Jetpack RC reporting 13):

| Correct | Incorrect |
|---------|---------|
| ![CleanShot 2022-12-19 at 11 35 34@2x](https://user-images.githubusercontent.com/528287/208406655-73a1d51d-903d-450f-a1ca-66a9c2c686c9.png) | ![CleanShot 2022-12-19 at 11 34 42@2x](https://user-images.githubusercontent.com/528287/208406766-1f65cb04-fef1-4b83-80da-0b3a8636e4a9.png) |

**Comment by Nic-Sevic** [comment] 2022-12-19 12:37
@TimBroddin 
I went ahead and reached out to the user here: 5774778-zd-woothemes

As for my test site. I'm also seeing 1 social follower now. I guess the follower count is pulled in by some process other than a standard jetpack sync action and this is why I wasn't seeing it before (after running an incremental sync)? If it's helpful for me to try and replicate or test anything else please let me know. I'm happy to help.

**Comment by TimBroddin** [comment] 2022-12-19 13:14
@Nic-Sevic I also added a P2 on the investigation: pdDOJh-1ea-p2 
I'll update this with new findings

**Comment by sophiegyo** [comment] 2023-07-18 05:34
We've encountered a similar issue in the forums, in particular for Mastodon.
The user has Mastodon correctly set up in their Connections, but their "social" subscribers shows at 0.

I tried using the regenerate option in the JP Social RC, but no luck there.
The site in question is a free, Simple wpcom site so it's not like there should really be a sync issue AFAIK.

Edit: I also found the user's Mastodon profile; it looks like their follower count is private so I'm guessing that may be why we can't pull it through to our stats.

Forum thread:
https://wordpress.com/forums/topic/mastodon-not-showing-up-in-social-subscriber-count/

**Comment by Gustavo-Hilario** [comment] 2023-08-07 18:14
I had a user whose old Blog Subscriptions (Jetpack) widget wasn't showing LinkedIn followers: 6598191-zen. I could reproduce this issue on a test site using the Subscribe block (first-time connection). The user replied: `I just posted and shared it to LinkedIn, and it looks now that the issue is resolved.`. So, I'm sharing this in case that helps figure out what the issue is here.

**Comment by edwinho89** [comment] 2023-08-11 02:58
6649938-zd-a8c

**Comment by edwinho89** [comment] 2023-08-11 03:06
6649938-zd-a8c

User was certain the number of subscribers in Subscribe block includes LinkedIn followers from the day before.

Today, they see a drop in number of subscribers from the Subscribe block, matching Linkedin followers.

https://wordpress.com/stats/subscribers page do not see followers from Linkedin as well.

Jetpack Social report card (formerly Publicize) shows follower count for Linkedin as `N/A`.

**Comment by marutim** [comment] 2023-08-11 06:24
https://a8c.zendesk.com/agent/tickets/6649938

The user Facebook, LInkedIN, Mastodon, Instagram Business connected to the site but only followers from Facebook are counted towards the subscribers

**Comment by marutim** [comment] 2023-08-11 06:44
6649938-zd-a8c

The user has Facebook, LInkedIN, Mastodon, Instagram Business connected to the site but only followers from Facebook are counted towards the subscribers

**Comment by pauloeaquino** [comment] 2023-09-28 07:05
7026107-zd

There are connections for Facebook, Instagram, and Linkedin on the site. I tried clicking the "Regenerate Jetpack Social Blog Option" button in the RC, but with no effect. Currently, the block will only show site subscribers.

Question - do we know if data is only fetched when content is shared? Or, is there a scheduled sync that runs in order to keep the social counts updated?

**Comment by cat-og** [comment] 2023-12-07 23:46
### 📌 REPRODUCTION RESULTS
- Tested on Atomic – Uncertain; I ran into unrelated issues connecting my test site with the social connections that I will need to look into, and was unable to run a full test. 

I did look into each of the sites linked above, and it looks like none of them are still experiencing this issue. 

@TimBroddin  I see you've been working on this, have there been any changes that would have fixed this recently, or did the sites reconnect over time?

**Comment by druesome** [comment] 2024-02-19 14:18
7685244-zen

User's Social followers are at zero, despite having their LinkedIn and Instagram Business accounts connected.

**Comment by rickmgithub** [comment] 2024-04-11 01:43
Pinged Tim in Slack 
p1712799756035669-slack-C01A60HCGUA

**Comment by rickmgithub** [comment] 2024-04-11 05:58
Spoke to Tim on Slack. As the issue appears to be resolved, closing.
If the issue recurs then Tim suggested Jetpack-reach as a next possible point for contact.

**Closed as completed by rickmgithub** 2024-04-11 05:58 UTC
Labels: Bug, [Pri] Low, Maintenance, Customer report [LEGACY], [Platform] Atomic
