### ISSUE TITLE
Multiple Payment Buttons on one page, select one shows correct payment amount, select second, still shows first amount.

### ISSUE THREAD

**Issue by radtechgh** [Automattic/wp-calypso#86253] opened 2024-01-10 18:51 UTC
### Quick summary

User has two Payment buttons on one page. When selecting the first button, you are presented with the payment amount (say $5). Click the second Payment button (say $10), you are still presented with the same $5 payment amount.
Once the page is refreshed, you can select the other payment button, and see the correct amount.
Page must be refreshed after each click.

### Steps to reproduce

1. added two Payment buttons on one page, with two different payment plans.
2. publish the page.
3. select the first payment button. Cancel
4. Select the second payment button, you will see the same payment option.
5. refresh the page, now the other payment can be viewed.

### What you expected to happen

When clicking on a single payment button, whether having clicked a previous button, I expected to be presented with the appropriate payment amount.

### What actually happened

I was presented with the same payment amount from the first payment button clicked on.

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by radtechgh** [comment] 2024-01-10 18:52
7548044-zen

**Comment by rickmgithub** [comment] 2024-01-12 08:45
## 📌 REPRODUCTION RESULTS ##
- Replicated as described

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##

https://github.com/Automattic/wp-calypso/assets/13706336/db9937c3-b750-449f-bce3-70839c75cb6f


## 📌 ACTIONS ##
Triaged

**Comment by renata-franco** [comment] 2024-01-15 09:47
Another report here: 7561095-zen
User wants to be updated once this is fixed.

**Comment by ccwalburn** [comment] 2024-01-15 18:01
7548044-zen 
Checking on status of this issue stating that it is disrupting their business.

**Comment by Gustavo-Hilario** [comment] 2024-01-18 17:47
Another report: 7605372-zen

**Comment by millerf** [comment] 2024-03-15 14:45
Thanks for the heads up. I'll prioritise it.

**Comment by n3f** [comment] 2024-03-15 16:31
This appears to be a duplicate of https://github.com/Automattic/gold/issues/284.  (Testing today doesn't have the same problem either)

**Closed as completed by n3f** 2024-03-15 16:31 UTC
Labels: Bug, [Pri] High, Triaged, [Feature Group] Customer Seller Experience, Customer report [LEGACY], [Status] Priority Review Triggered, [Product] WordPress.com, [Feature] User Payments & Donations
