### ISSUE TITLE
Post Title: Settings missing

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#84346] opened 2023-11-20 14:16 UTC
### Quick summary

The Post Title block doesn't seem to have any settings on WordPress.com:

<img width="313" alt="Screenshot 2023-11-20 at 14 06 46" src="https://github.com/Automattic/wp-calypso/assets/275961/5c523be6-f207-425a-91ee-b2d179e4411c">

Whereas in core it does:
<img width="301" alt="Screenshot 2023-11-20 at 14 09 36" src="https://github.com/Automattic/wp-calypso/assets/275961/3e0ee101-4955-472f-8cc7-566115d923e8">

This might be a theme issue

### Steps to reproduce

1. Create a site using the Eventual theme
2. Edit a template that contains a Post Title block
3. Select the block
4. Open the block inspector
5. Check whether the block inspector has a styles tab

### What you expected to happen

I expected to see the styles tab for the block.

### What actually happened

There was no styles tab.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by liviopv** [comment] 2023-12-07 09:38
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate using TT4 GB 17.2 (edge)
- Tested on Simple – Could Not Replicate using Eventual GB 17.2 (edge)
- Tested on Atomic – Could Not Replicate using Eventual GB 17.1.4
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
![CleanShot 2023-12-07 at 09 34 07@2x](https://github.com/Automattic/wp-calypso/assets/14153300/f52961b2-9fd7-4d45-951c-9a4664de2132)

![CleanShot 2023-12-07 at 09 35 12@2x](https://github.com/Automattic/wp-calypso/assets/14153300/a3ea4e65-d8c5-452b-a25c-0e0e74ae9286)

![CleanShot 2023-12-07 at 09 37 00@2x](https://github.com/Automattic/wp-calypso/assets/14153300/9b565089-8e39-4345-b447-5060c7a22b21)

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@scruffian I could not replicate it on Eventual or TT4. I guess that a recent GB/ETK/Jetpack merge might have fixed the issue since you reported it.

**Closed as completed by liviopv** 2023-12-07 09:38 UTC
Labels: Bug, [Pri] High, [Closed] Not Reproducible, [Status] Priority Review Triggered
