### ISSUE TITLE
Gutenberg: Ampersand character (&) in title displays &amp; in editor and message

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#29391] opened 2018-12-13 05:09 UTC
Tested that this happens in both wp-admin and Calypso Gutenberg for a simple site. It didn't happen on Gutenberg master (see screenshot below) or wp-admin on a Jetpack site

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post or https://wpcalypso.wordpress.com/block-editor/post for a simple site opted in 
2. Type an & character in title and publish (eg. "Black & White")

#### What I expected

Title in editor and message shouldn't contain &amp; as per Gutenberg core and Calypso Classic

#### What happened instead

Title in editor and message shows &amp;

#### Browser / OS version

Chrome 70 on macOS

#### Screenshot / Video

Calypso:

<img width="913" alt="calypso" src="https://user-images.githubusercontent.com/128826/49916973-f3be4180-fee8-11e8-88c7-56a9dc4b3800.png">

wp-admin:

<img width="907" alt="wp-admin" src="https://user-images.githubusercontent.com/128826/49916979-fa4cb900-fee8-11e8-91e2-3f4ce3695457.png">

Gutenberg Master:

<img width="905" alt="g master" src="https://user-images.githubusercontent.com/128826/49916983-fde04000-fee8-11e8-9a7b-c0c9ae4b1ffe.png">

Calypso Classic Editor:

<img width="915" alt="calypso classic" src="https://user-images.githubusercontent.com/128826/49916987-020c5d80-fee9-11e8-920b-513217953b49.png">

#### Context / Source

#dogfooding

**Comment by mmtr** [comment] 2019-03-12 23:40
This is still reproducible with Gutenframe.

**Comment by joweber123** [comment] 2019-10-08 06:58
Another report of this here: 15802960-hc

**Comment by gwwar** [comment] 2019-10-30 00:32
Still reproducible on wpcom. This is a wpcom issue only. https://github.com/Automattic/wp-calypso/issues/27825 may be related

**Comment by jeraldjuice** [comment] 2019-12-24 06:28
This is an escaping issue and applies to other entities as well. 

<img width="273" alt="Screen Shot 2019-12-24 at 12 43 54 AM" src="https://user-images.githubusercontent.com/8892849/71397505-bf955a80-25eb-11ea-84b6-ebc5836eb7b2.png">

The data displayed in the areas affected is coming from the post revision data, which hasn't been normalized like the post data itself is (ie, `/state/posts/utils.js`). This means that the escaped entities leak through when ultimately displayed in the editor instance in the iframe.

Working on a fix from that angle.

**Comment by mmtr** [comment] 2019-12-24 08:24
Maybe related to https://github.com/Automattic/wp-calypso/issues/38362 which was solved recently in  https://github.com/WordPress/gutenberg/pull/19187

**Comment by jeraldjuice** [comment] 2019-12-24 17:14
It looks like you're right; I'll open up a PR in Gutenberg for the sidebar link after publish. The revisions escaping issue might be applicable to #27825

**Comment by bsanevans** [comment] 2019-12-27 00:45
We have a similar issue happening with apostrophes: 2583624-zen

**Comment by mmtr** [comment] 2019-12-31 08:48
> It looks like you're right; I'll open up a PR in Gutenberg for the sidebar link after publish. 

I think we can apply the same fix than WordPress/gutenberg#19187 and replace `unescape` with `decodeEntities`:

https://github.com/WordPress/gutenberg/blob/ab8af23410f9f89f5a57064b43758b157f392d55/packages/block-library/src/navigation-link/edit.js#L83

> The revisions escaping issue might be applicable to #27825

Yeah, it could help. But it seems the closing quote gets replaced with an HTML-encoded on the published view, so I wouldn't discard KSES as the cause of #27825.

**Comment by gwwar** [comment] 2020-01-08 22:54
Title issue fixed by @glendaviesnz in https://github.com/WordPress/gutenberg/pull/19187. The publish link should be fixed in https://github.com/WordPress/gutenberg/pull/19517

**Comment by gwwar** [comment] 2020-01-09 16:02
closing this out for now, we should pick up the other publish link fix in the next update round

**Closed by gwwar** 2020-01-09 16:02 UTC
Labels: [Goal] Gutenberg, [Pri] Normal, [Type] Bug
