### ISSUE TITLE
Editor: insert/edit link keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by danhauk** [Automattic/wp-calypso#4336] opened 2016-03-26 04:51 UTC
When writing a post in the editor the insert/edit link keyboard shortcut does nothing. Other shortcuts (bold, italic, etc.) work as expected. Clicking the link button in the MCE panel works as expected.

#### Steps to reproduce
1. Start a new post or edit an existing post.
2. Press Cmd/Ctrl + k to insert a link

#### What I expected
I expected the link modal window to appear so I can add a link to the post.

#### What happened instead
Nothing happens.

#### Browser / OS version
OS X 10.11.3
Chrome 49.0.2623.108 & Safari 9.0.3

**Comment by lancewillett** [comment] 2016-04-25 20:18
I'm able to repeat this with Safari 9.1 on OS X 10.11.4.

Also reported by a Linux desktop app user in https://github.com/Automattic/wp-desktop/issues/161

**Comment by lancewillett** [comment] 2016-04-25 20:27
Hmm, this was supposedly fixed with https://github.com/Automattic/wp-calypso/pull/1747 — regression perhaps?

**Comment by DigitalDavo** [comment] 2016-05-04 03:09
Confirmed on version 1.3.2-alpha version of Wordpress.com desktop app on windows too. This is almost the most important feature for using Calypso as a blogging tool.

**Comment by lancewillett** [comment] 2016-05-04 20:59
@DigitalDavo You can add links in other ways: highlight a word, paste (as long as URL is in clipboard). Highlight word and use toolbar icon to add link.

**Comment by DigitalDavo** [comment] 2016-05-05 12:43
Thanks @lancewillett , I never knew I could just paste over the top. I was so used to CTRL-K since Windows Live Writer days that I was happy that it worked in previous versions of calypso desktop.

**Comment by aduth** [comment] 2016-06-20 18:52
Fixed by #6097, props @zpnk

**Closed by aduth** 2016-06-20 18:52 UTC
Labels: Editor, [Type] Bug, [Type] Good First Change
