### ISSUE TITLE
Premium Content Block: Subscribers not able to access content

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#45498] opened 2020-09-09 13:19 UTC
In some cases, the Premium Content block is showing a "Log in" button to logged in users – instead, they should just be seeing the content. When the user clicks that button anyways, they don't see the premium content, but rather a blank content area.

User report - ticket: 3284882-zd-woothemes

**Comment by carinapilar** [comment] 2020-09-11 13:41
User asked for an update, would we have any to share? The user's customers have paid for the content and still can't access it. Thanks!

**Comment by bsanevans** [comment] 2020-09-12 04:41
Once this issue has been resolved, we'll need to update on of their viewers, who has also contacted us here: 3277816-zd-woothemes

Leaving this note, so we can close the ticket and move it out of the queue.

**Comment by AtrumGeost** [comment] 2020-09-19 15:09
Hi folks!

Is there an update we can share with the user? I got the ticket in play mode. I'm putting it on hold for 24-h

**Comment by mmtr** [comment] 2020-09-21 13:37
This is likely the same issue as https://github.com/Automattic/wp-calypso/issues/45663, which hopefully will be fixed by https://github.com/Automattic/wp-calypso/issues/45663

**Comment by kwight** [comment] 2020-09-22 22:54
It looks like this is still an active issue after the proposed fix landed yesterday. I haven't been able to reproduce with a new Premium Content block on a test site, but I can both confirm that the user in p1600793040149500-slack-CDA5HLRD2?thread_ts=1600703764.065000&cid=CDA5HLRD2 sees only a Log In button (and no content), and that the block appears to be set up properly.

Editor | User Logged-in View
--- | ---
<img width="500" alt="Screen Shot 2020-09-22 at 3 46 09 PM" src="https://user-images.githubusercontent.com/349751/93945502-e0f6b480-fceb-11ea-9654-5a95c8b08804.png"> | <img width="500" alt="Screen Shot 2020-09-22 at 3 45 51 PM" src="https://user-images.githubusercontent.com/349751/93945520-ea801c80-fceb-11ea-82b3-bba083115235.png">

**Comment by mmtr** [comment] 2020-09-23 10:53
Confirmed in p1600855523000300-slack-CDA5HLRD2?thread_ts=1600703764.065000&cid=CDA5HLRD2 that the issue above was a side effect of the regressions introduced by WordPress/gutenberg#24155 and Automattic/jetpack#15915.

Those regressions have been fixed by #45777, but while the regressions were happening users had the ability to set a plan to the Subscribe button that was not the same that the plan selected for Premium Content block. These blocks need to be re-published so the selected plan for the Premium Content block is passed down to the Subscribe button (which is a Payments block) and overrides whatever plan the user selected.

**Closed by mmtr** 2020-09-23 10:53 UTC
Labels: Earn, Premium Content, [Team] Serenity, [Type] Bug
