### ISSUE TITLE
Gutenberg: SEO Description missing from editor sidebar

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#27692] opened 2018-10-09 20:36 UTC
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/
2. Start a new post

#### What I expected
I expected to see the sidebar settings matching the existing settings

#### What happened instead
In the sidebar the SEO Description section is missing

#### Browser / OS version
All

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/31110506/46696801-4bca8600-cbd0-11e8-89ad-de6f852eab3f.png)

**Comment by bsessions85** [comment] 2018-10-10 17:28
Closing this since we're not looking to match calypso at this point, only plain Gutenberg for now

**Comment by arunsathiya** [comment] 2018-11-11 07:03
@bsessions85 Considering that the WordPress.com Business plan users cannot add a SEO description in this case, what are your thoughts on reopening this?

Currently the only other option is to use the Calypso editor to add a SEO description.

**Comment by kriskarkoski** [comment] 2018-11-26 18:51
I'm reopening this as this is something we need to bring to Gutenberg for parity with the Calypso editor

**Comment by gwwar** [comment] 2018-11-26 23:19
Folks can reopen this one, but in general feel free to open new issues, if we have specific concerns. This was originally created during an early audit of what was missing for key integration work.

Missing wpcom integrations will be prioritized based on feedback and other considerations.

**Comment by goblinartificer** [comment] 2018-12-11 01:52
Also in 8729147-hc. User re-enabled the classic editor to access SEO options manually under Custom Fields > advanced_seo_description , but is displeased about having to manually add this each time.

**Comment by gpmw** [comment] 2018-12-12 16:31
User reported this in #8772160-hc as well.

**Comment by StefZarb** [comment] 2018-12-17 16:50
User reported in #1652277-ZD.

**Comment by samjhamdy** [comment] 2018-12-21 21:59
I discovered this while walking a user through our Advanced SEO Tools in a 1:1 session: #1661837-zd

**Comment by kriskorn** [comment] 2018-12-27 05:59
Another report #1667598-zen

**Comment by kspilarski** [comment] 2019-01-14 08:51
1716684-zd

**Comment by mlaetitia** [comment] 2019-01-24 10:11
Another report here: 9801982-hc

**Comment by brezocordero** [comment] 2019-01-28 16:52
Another report during a 1:1 session: 1754922-zen

**Comment by aisajib** [comment] 2019-02-06 15:32
We had another user reporting this option going missing after they switched to Gutenberg on Calypso: 10185901-zen.

**Comment by gaymer313** [comment] 2019-02-13 20:30
Missing for me too. Any idea when this is being brought back? Used it for every post. :/

**Comment by sarahfg** [comment] 2019-02-13 22:58
Another person who needs this core functionality reported in 1800985-zen

**Comment by Khrol** [comment] 2019-02-21 10:27
10614171-hc is another case where the feature was needed.

**Comment by sarahfg** [comment] 2019-02-25 19:14
1817755-zen yet another case where this feature is needed

**Comment by nagpai** [comment] 2019-03-08 08:06
10938062-hc  case where the feature is needed

**Comment by eoinsav** [comment] 2019-03-08 19:12
Requested in 11017568-hc

**Comment by simison** [comment] 2019-03-21 14:43
re-opening, still needs https://github.com/Automattic/jetpack/pull/11333

**Comment by GeoJunkie** [comment] 2019-03-25 12:12
User was looking for this option in 8751479-hc

**Comment by jordesign** [comment] 2019-03-27 12:49
Another user looking for this option in 1911376-zen

**Comment by zdenys** [comment] 2019-04-02 15:43
Another user asking for this 11772669-hc

**Comment by lancewillett** [comment] 2019-04-09 02:20
Removing High priority label on this one.

**Comment by kriskorn** [comment] 2019-04-09 05:15
@lancewillett Do you know if this gets merged soon? - https://github.com/Automattic/jetpack/pull/11659

**Comment by dkmyta** [comment] 2019-06-12 21:18
Another self-hosted Jetpack user has reported this here: 2095373-zen

Do we happen to have any progress on a fix for this or potential options for a workaround?

We still appear to have user-facing documentation indicating that this feature is available to eligible Jetpack users here: https://jetpack.com/support/seo-tools/#custom-postpage-meta-description. Should these details be removed for the time being?

**Comment by juliasydnor** [comment] 2019-07-04 11:05
Another report from self-hosted JP user: 2154005-zen

They are upset that they have to use another plugin (Classic Editor) in order to access the SEO tools. They chose to use JP to eliminate the need for additional plugins.

They also requested we update the information here to reflect that: https://jetpack.com/support/seo-tools/

**Comment by aheckler** [comment] 2019-08-09 13:08
Another JP user report: 2262356-zen

Agree with @juliasydnor above, we should remove this from our JP docs/marketing pages if this is not going to be fixed soon. @jeherve seems to indicate this is on the backburner here:

https://github.com/Automattic/jetpack/pull/11659

**Comment by lancewillett** [comment] 2020-03-29 17:03
Tested this today with an Atomic site on the Business plan.

1. Turned on SEO Tools in Calypso under "Tools" > "Marketing" — toggle says "Enable SEO Tools to optimize your site for search engines". **Question**: shouldn't SEO Tools be on by default? **Question**: why does a WordPress.com Business plan site link to a Jetpack help page? (https://jetpack.com/support/seo-tools/ instead of the expected https://wordpress.com/support/seo-tools/)
2. Clicked on "Site" > "Pages" is the sidebar (also tried via WP Admin "Pages" menu)
3. Opened my "homepage" page, looked in the editor sidebar and the Jetpack toolbar in the editor — neither one shows the "SEO Description" meta box I expected to see

<img width="1392" alt="Screen Shot 2020-03-29 at 09 58 47" src="https://user-images.githubusercontent.com/66797/77855284-49813080-71a4-11ea-97ff-49e2aee5fa54.png">

**Comment by jeherve** [comment] 2020-03-30 11:11
That's indeed the intended behaviour for Atomic sites today, as per D32268-code. 

The following 2 PRs will bring the feature to Atomic:
- 431-gh-wpcomsh
- https://github.com/Automattic/jetpack/pull/15189

**Note: the feature will not be available on Jetpack sites.**

**Comment by lancewillett** [comment] 2020-04-02 04:21
@jeherve Thank you for the Atomic, Jetpack, and wpcom changes. `wpcomsh` pull request 431 is tested and approved.

**Closed** 2020-04-02 15:23 UTC
Labels: SEO Tools, [Goal] Gutenberg, [Type] Task

**Comment by jeherve** [comment] 2020-04-02 15:27
This is now fixed. Please note that the fix will only become available on Atomic sites once Jetpack is updated next Tuesday (April 7).

**Comment by lancewillett** [comment] 2020-04-02 15:52
Thank you for fixing this, @jeherve 

CC @chrisfromthelc ⭐️

**Comment by aheckler** [comment] 2020-04-02 17:08
@jeherve 

> Note: the feature will not be available on Jetpack sites.

So we should really update our docs and marketing pages on the JP site then, eh?

**Comment by jeherve** [comment] 2020-04-02 18:22
@aheckler We don't mention the meta description block in our support docs as far as I can tell, so we should be all good there:
https://jetpack.com/support/seo-tools/

If you see it in other places though, it definitely should not be there, feel free to delete!

**Comment by aheckler** [comment] 2020-04-03 13:53
@jeherve On this page:

https://jetpack.com/features/traffic/search-engine-optimization/

There's this text:

> Craft descriptions that catch people’s eyes better and potentially increase the ranking of your posts.

Isn't that inaccurate if standalone JP sites are not getting page/post meta descriptions? We should reword it so that it's about the front page meta description.

**Comment by jeherve** [comment] 2020-04-03 13:55
Good point! That sounds like a good update. 👍

**Comment by aheckler** [comment] 2020-04-03 14:05
Changed to:

> Craft an eye-catching meta description for your site’s front page.
