### ISSUE TITLE
Marketplace plugins remain active after cancelling a plan

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#65235] opened 2022-07-05 12:48 UTC
### Quick summary

https://github.com/Automattic/wp-calypso/pull/59910 introduced a new mechanism that deactivates all the active marketplace plugins on a site when deactivating the required plan needed for them to work.

However, looks like it only covered the removal flow. When cancelling a plan, the marketplace plugins remain active.

To clarify, we have two deactivation flows:
- **Removal flow**: when the purchase has auto-renew OFF (e.g. purchases made with credits). It's handled here: https://github.com/Automattic/wp-calypso/tree/trunk/client/me/purchases/remove-purchase.
- **Cancellation flow**: when the purchase has auto-renew ON (e.g. purchases made with a credit card). It's handled here: https://github.com/Automattic/wp-calypso/tree/trunk/client/me/purchases/cancel-purchase.

We should incorporate the same mechanism into the cancellation flow.

cc @cpapazoglou @gcsecsey

### Steps to reproduce

- Go to https://wordpress.com
- Switch to a Simple site
- Purchase a Pro plan with a credit card (you can use the Sandbox store if you don't want to enter an actual credit card: PCYsg-IA-p2#sandbox)
- Go to Plugins
- Purchase a paid plugin with a credit card
- Go to Upgrades > Purchases
- Cancel the Pro plan

### What you expected to happen

To see a warning indicating that all the marketplace plugin will be cancelled as well, like we do when removing a plan:

<img width="500" alt="Screen Shot 2022-07-05 at 13 51 09" src="https://user-images.githubusercontent.com/1233880/177330880-21aed4d7-d102-43b5-b34c-3063c80d0db7.png">

### What actually happened

There is no warning and all the marketplace plugins remain active

**Comment by gcsecsey** [comment] 2022-07-07 14:03
Thanks for the detailed summary @mmtr! I've reproduced the issue, and indeed the plugins aren't removed when cancelling a plan.

To resolve this issue, I think we just need to add the same prop (`activeSubscriptions`) and the dialog component to the [cancel-purchase](https://github.com/Automattic/wp-calypso/tree/trunk/client/me/purchases/cancel-purchase/index.jsx) page as well. I've added this bug to our sprint board.

**Comment by cpapazoglou** [comment] 2022-07-14 13:23
I started working on it, just wanted to mention that we will need to remove both implementations once we offer premium plugins to free.

**Comment by cpapazoglou** [comment] 2022-07-15 15:16
After finishing a POC for the cancellation flow, it has occurred to me when while the site plan is rendered unavailable when subscription gets removed (and thus we are removing the marketplace subscriptions) cancelling the plan will render it unavailable (remove it) in the next billing cycle. We shouldn't cancel the marketplace subscriptions just because the plan is cancelled. For example

**Scenario 1**
- Site Plan expires on 08/2023
- Marketplace subscriptions expire before 08/2023

The plan will be removed by 08/2023 and by that time the marketplace subscriptions would have been removed.

**Scenario 2**
- Pro plan expires on 08/2023
- Marketplace subscriptions expire after 08/2023

The plan will be removed by 08/2023 and after that time the marketplace subscriptions will not be usable due to requiring a plan.

I guess we should do something to educate users about their actions, but all of this will be obsolete once we launch to free.

Any ideas? To be honest, I am in favour of just closing this.

**Comment by gcsecsey** [comment] 2022-07-18 09:51
@cpapazoglou thanks for breaking down these scenarios! It does seem like this will be a non-issue once we've launched to free, but we'll then need to remove the current implementation. Until then, as a temporary solution, maybe we should add some messaging around how the plan/subscription changes if they cancel?

**Comment by mmtr** [comment] 2022-07-18 10:12
> To be honest, I am in favour of just closing this.

I agree. Given that it has been working for a while like that without causing any major issue (as far as we know), and since the problem will resolve on its own after launching on Free sites, I don't think we need any temporary solution.

Let's just make sure that we revert the current implementation in https://github.com/Automattic/wp-calypso/pull/65404

**Comment by cpapazoglou** [comment] 2022-07-18 14:20
Thanks, let's close this for now.

**Comment by mmtr** [comment] 2022-08-22 08:51
Should we reopen this now that we won't be supporting premium plugins on lower-tier plans? pdtkmj-io-p2#comment-543

**Comment by cpapazoglou** [comment] 2022-08-29 14:50
Discussed this in the sprint planning, let's pop up a modal educating users that their marketplace subscriptions (if they have) will get removed once the plan expires.

**Comment by epeicher** [comment] 2022-09-23 15:01
After some investigation, I have found that the **Cancellation flow** is followed when:
- Purchase was done with money and it was done less than 14 days ago. That means that the money will be refunded and the plan will be **cancelled immediately**

The logic can be found:
- [This](https://github.com/Automattic/wp-calypso/blob/bc7edc479c218d4a798eb86e0d9cff46c9908291/client/me/purchases/manage-purchase/index.jsx#L876-L877) is checking if render the cancel or remove flow 
- [Here](https://github.com/Automattic/wp-calypso/blob/bc7edc479c218d4a798eb86e0d9cff46c9908291/client/me/purchases/manage-purchase/index.jsx#L487) is the condition `isCancelable`
- [Here](https://github.com/Automattic/wp-calypso/blob/bc7edc479c218d4a798eb86e0d9cff46c9908291/client/lib/purchases/index.ts#L497) it is checked if the purchase is refundable

Among other conditions, they are based on `hasAmountAvailableToRefund` being `true` => _Cancelable_ or `false` => _Removable_

The **Removal flow** is supposed to be already covered so we could focus on the **Cancellation flow**. 

@cpapazoglou Should we do the same in the **Cancellation flow** than the **Removal flow** as it terminates the plan immediately?

**Comment by cpapazoglou** [comment] 2022-09-23 16:06
Yes, and we should also cover the case that the plan was purchased more than 14 days ago and as such you won't get a refund and the plan will expire when the subscription expires.

**Comment by epeicher** [comment] 2022-09-26 08:17
The following changes have been suggested in the linked PR https://github.com/Automattic/wp-calypso/pull/65596:
- When the user is only allowed to `Cancel` the site plan ([example video here](https://github.com/Automattic/wp-calypso/pull/65596#issuecomment-1256520553)):
  - The site plan auto-renew is disabled
  - The Marketplace subscription auto-renew is disabled, so it will expire when the subscription ends.
- When the user is allowed to `Cancel and Refund` ([example video here](https://github.com/Automattic/wp-calypso/pull/65596#issuecomment-1257578639)):
  - The site plan is immediately cancelled and refunded
  - The plugin is immediately cancelled and refunded if a refund is possible, otherwise only cancelled

**Closed as completed** 2022-10-03 07:04 UTC
Labels: Bug, [Status] In Progress, [Feature] Purchase Management, Marketplace
