### ISSUE TITLE
Fix domain warning message at the top of the modal

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#68364] opened 2022-09-27 23:32 UTC
Fix this message at the top of the modal (when available):

![image](https://user-images.githubusercontent.com/1044309/192655474-cf7d813c-f6c0-4e85-a5e1-0c75c287fe9d.png)

### Requirements

- We should show this message when receiving a `NO_BUSINESS_PLAN` warning from the backend.
- Make sure this message won't show on the warning lists below the primary message

Context: pdh6GB-26h-p2
Figma: [HOg65lHD0QOfaq0QtzKQbC-fi-1183%3A11200](https://href.li/?https://www.figma.com/file/HOg65lHD0QOfaq0QtzKQbC/?node-id=1183%3A11200)

**Comment by lsl** [comment] 2022-09-28 00:13
Might be duplicate of https://github.com/Automattic/wp-calypso/issues/68247? cc @lupus2k for extra context since you're assigned.

After yesterday I'm wondering about the approach laid out there. It might make more sense to just keep all this localized to CTAButton?

I think the only caveat there is we need to ensure the error notices continue to disable the text correctly as before. (at least until https://github.com/Automattic/wp-calypso/issues/68250 resolves that conflict with new designs for the non modal contexts) That's why I was thinking easier to push through eligibility warnings with optional props.

**Comment by lsl** [comment] 2022-09-28 00:19
Oops, I re-read your actual question in slack, sort of not a duplicate but we can probably just expand the acceptance criteria in that issue to include:

> We should show this message when receiving a NO_BUSINESS_PLAN warning from the backend.

@lupus2k up to you if you want to do both of these issues in one go. Not sure if that makes it easier or harder to get a PR up?

**Comment by lsl** [comment] 2022-09-28 07:24
This should be fixed by https://github.com/Automattic/wp-calypso/pull/68365 now. Could probably split it up if you want but it turned out to be quite tangled up / required for testing.

Basically did the same thing [you did earlier](https://github.com/Automattic/wp-calypso/pull/68048/files#diff-fb9fcef5e87a5fd1b195c3880b0fa2ebf61d0781e4868808e67a37a606b1ccc9R249) but at the CTAButton level instead of inside `EligibilityWarnings`. 

Getting the sense `EligibilityWarnings` needs to be broken down / up.

**Comment by candy02058912** [comment] 2022-09-28 09:03
> Make sure this message won't show on the warning lists below the primary message

Could you tell me a bit more about this? It seems pretty separate from the warnings below, so don't quite understand. (I might be missing some context)

**Closed as completed** 2022-09-28 18:15 UTC
Labels: [Status] In Progress

**Comment by lsl** [comment] 2022-09-29 05:55
Eligibility warnings are for simple site migrations to atomic. (in other words business simple sites can still see this message sometimes)

Since the copy content refers to upgrading to a business plan, I think the plan is to just hide the copy unless one of the "holds" is that you're missing a business plan.
