### ISSUE TITLE
FSE: cover block and full bleed header

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36710] opened 2019-10-14 08:38 UTC
Currently it's not possible to create a full bleed image/video section at the top of the page with the Cover block. If you insert this block at the top of the Header and set Full Width alignment, it will take up the whole width of the page but there will still be some whitespace at the top before it.

<img width="1678" alt="Screenshot 2019-10-14 at 10 40 41" src="https://user-images.githubusercontent.com/1182160/66738552-1ace0280-ee6f-11e9-9ca9-c02ac94b909d.png">

**Comment by Copons** [comment] 2019-10-14 17:43
This is not strictly a bug, but a very nice enhancement nonetheless!

It's caused by the template parts reusing the `.entry-content` class which has vertical margins.

**Comment by Copons** [comment] 2019-11-05 17:59
Fixed in FSE 0.14

**Closed by Copons** 2019-11-05 17:59 UTC
Labels: [Goal] Full Site Editing, [Pri] Normal, [Type] Enhancement
