### ISSUE TITLE
Jetpack plugins: Browse All Plugins list has no header cake to return to main list

### ISSUE THREAD

**Issue by isaackeyet** [Automattic/wp-calypso#2257] opened 2016-01-09 02:26 UTC
<img width="122" alt="screen shot 2016-01-09 at 03 18 42" src="https://cloud.githubusercontent.com/assets/3073557/12213806/c4dbf010-b67f-11e5-837a-df50b5bfb1e4.png">

It's laughable, I know, but I didn't immediately understand what it was far. Now I can't unsee it, but it took me a good 5s to figure out what it was and then clicking it to make sure I was correct.

This is what happened: As I was trying to figure it out in those 5s, my subconscious saw a spikey symbol and a crosshair. I hovered the icon by reflex to see the tooltip but there was none. Finally I clicked and realized -- and felt pretty dumb.

I checked now, there's actually no text there whatsoever -- nothing for screen readers either as far as I can tell. So I'm confused. Why go with an icon (only) when there's plenty of space for text (and even text + icon) and the button right next to it is in text?

EDIT: Forgot this: When you actually click it there's no cake header (?) to come back to the Plugins list.

Point of no return!
<img width="806" alt="screen shot 2016-01-09 at 03 28 09" src="https://cloud.githubusercontent.com/assets/3073557/12213850/091d2856-b681-11e5-9847-4c2b51864daa.png">

**Comment by enejb** [comment] 2016-01-19 18:46
cc @MichaelArestad and @rickybanister

**Comment by rickybanister** [comment] 2016-02-03 20:29
We definitely need to add screen reader and alt text on these icon-only buttons.

I'll also see about adding a header cake to the plugin browser. I noticed that the adding a domain screen is similar.

**Comment by hoverduck** [comment] 2016-05-05 19:15
05May16 Bug Scrub

The button now has a tooltip (seen below, added in #3056), but the plugin browser still has no header cake to get back to the main list.  I'll assume this issue is being left open to track that change.

<img width="199" alt="screen shot 2016-05-05 at 3 12 47 pm" src="https://cloud.githubusercontent.com/assets/7233112/15054126/e981996e-12d3-11e6-8c6d-7f81e56a5d9f.png">

**Comment by designsimply** [comment] 2016-07-25 19:16
#bug-scrub

Tested and confirmed using the following testing steps:

1. Start at https://wordpress.com/plugins
1. Click the "Browse all plugins" icon

<strong>Result:</strong> header navigation is missing so you feel stuck

![screen shot 2016-07-25 at mon jul 25 1 07 52 pm](https://cloud.githubusercontent.com/assets/1119271/17113891/d9105234-5269-11e6-88d0-d0b21c79ff1a.png)
<sup>Seen at https://wordpress.com/plugins/browse using Safari 9.1.1 on Mac OS X 10.11.5</sup>

Since the header navigation from the installed plugins section doesn't really make sense (search works differently, it's a whole different flow), perhaps you could just offer a back link similar to what you see on `/plugins/$plugin` pages.

![screen shot 2016-07-25 at mon jul 25 1 08 31 pm](https://cloud.githubusercontent.com/assets/1119271/17113905/e5edcc20-5269-11e6-93c3-c7ad971b09b8.png)
<sup>Seen at https://wordpress.com/plugins/regenerate-thumbnails using Safari 9.1.1 on Mac OS X 10.11.5</sup>

**Comment by designsimply** [comment] 2016-07-25 19:16
Nitpick: before clicking the plugin icon, aren't you already browsing all plugins? Instead of labeling that icon "Browse all plugins," should it read "Search for plugins" or "Install a new plugin"?

**Comment by MichaelArestad** [comment] 2016-07-25 19:49
I don't think there should be a header cake on it unless navigated to from the plugins list. It can be directly accessed via the sidebar as well. If we could make it conditional, it would be useful.

@designsimply Probably "Add a plugin" instead of browse would be an improvement.

**Comment by rickybanister** [comment] 2016-08-09 15:05
What if we made 'adding plugins' feel like search elsewhere in Calypso?

If you click add you see the plugin browser with the search focused at the top, with an 'X' to the right of the search box. If you click the 'X', you not only close the search, but you exit the whole plugin browser and see 'all your plugins' with the standard sectionNav there?

That would keep most of our interactions standard, except that the content of the page changes when you click the 'add' button.

**Comment by MichaelArestad** [comment] 2016-08-10 14:22
@rickybanister I was actually thinking it might make sense to do something more like the Reader individual post view with a white overlay and an X or < to back out of it.

**Comment by rickybanister** [comment] 2016-08-10 14:28
That sounds really nice. I don't see us having much time to invest in something like that for a while though.

**Comment by MichaelArestad** [comment] 2016-08-10 14:31
@rickybanister I think we could do it with the same design and code as reader, but with @fraying iterating on Reader, I'd rather see what he comes up with before using a pattern that might disappear or change.

**Comment by rickybanister** [comment] 2016-08-10 14:39
Makes sense, that sounds like a fun experiment.

**Comment by lancewillett** [comment] 2016-10-17 23:32
Closing this for now, feel free to re-open in the future once we loop back to it.

**Closed by lancewillett** 2016-10-17 23:32 UTC
Labels: Jetpack Plugins, OSS Citizen, [Status] Needs Design Review, [Type] Bug
