### ISSUE TITLE
Situation Where You Can't Connect a Domain

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#74353] opened 2023-03-11 10:15 UTC
### Quick summary

You aren't able to add a domain connection when we ask for the auth code and the domain is locked for transfers.

### Steps to reproduce

1. Choose the option to add a domain you own to your site, and select the option to connect it.
2. Choose a domain that's currently locked for transfers.

### What you expected to happen

To be able to connect the domain.

### What actually happened

It asks for the auth code, but it can be created since the domain is currently locked for transfers.

### Impact

All

### Available workarounds?

No and the platform is unusable

### Logs or notes

The critical scenario is the following:

- You decide to transfer your site's domain to another registrar (you found a cheaper alternative)
- You proceed with the transfer, and the domain is removed from your site (registration + connection upgrades)
- Your site stops loading with the domain, since there's no domain connection left
- You try to connect the domain again, but you're prompted to add an auth code
- You can't get an auth code from the new registrar, because of the 60-day lock since you just transferred the domain - here's an example for Google Domains:

![transfer-lock-google-domains](https://user-images.githubusercontent.com/16104522/224478283-f599b8fc-d985-4aad-8d78-a5c5cb3c1f5f.png)

The result is that your site stopped loading with your domain, until you reach out to support and have an HE manually add the domain connection for you.

Another odd thing is the message you see when accessing the domain, IIRC, it used to show that a domain mapping upgrade is missing, but it currently shows `site_id mismatch error`:

![missing-connection-error](https://user-images.githubusercontent.com/16104522/224478475-cb3d5668-b193-44cc-a609-095017a89896.png)

The domain was on the WordPress.com site, not a WordPress.org connected with Jetpack.

**Comment by cuemarie** [comment] 2023-03-28 22:35
Hi @carinapilar ! In the situation you've described, where an auth code is not obtainable, there is a process for `Handling Manual Connection Verification` instead, noted here: P6Ya1B-TO-p2

- This more recent post goes into the manual verification process in further detail: pc4f5j-2VH-p2

With this guidance in mind, this seems to be by design.  Closing as such, but

**Closed as completed by cuemarie** 2023-03-28 22:35 UTC
Labels: Bug, [Pri] BLOCKER, [Feature Group] Emails & Domains, Triaged
