### ISSUE TITLE
Kraken: Enable dashes if the search input has dashes in it

### ISSUE THREAD

**Issue by hambai** [Automattic/wp-calypso#24374] opened 2018-04-20 15:33 UTC
When a user enters a search with dashes in it, should we enable dashes in the search suggestions? It makes sense to do so, but how should that play with the "Enable dashes" filter?

**Comment by lucasartoni** [comment] 2018-04-23 11:32
Can we automatically enable the "enable dashes" every time there is a dash in the search query?
Not mission critical for launch, interesting feature nevertheless.

**Comment by jsnmoon** [comment] 2018-05-22 19:32
I also think it's a good time to clarify: what does the dashes filter do? Does it "allow" dashed domain names to be suggested? Or does it blacklist non-dashed domain name suggestions?

**Comment by jsnmoon** [comment] 2018-05-30 21:02
@kelliepeterson and @lucasartoni, could you clarify what the dashes filter should do?

**Comment by lucasartoni** [comment] 2018-05-31 14:35
People in some countries, like Germany, like to have "-" in their URLs. In other countries, like the US, "-' have no fans. The purpose of this filter is to enable/disable dashes in domain names in the results. Some providers allow that via the API call and take care of that, other providers don't and we need to filter on the front-end. 

I hope this clarifies a little.

**Comment by sixhours** [comment] 2018-05-31 16:03
If the issue is mostly a regional one, can we try to get the user's region and enable/disable the setting by default based on that?

**Comment by jsnmoon** [comment] 2018-05-31 17:29
@lucasartoni: 

If I'm understanding you correctly, these should hold true:

- If the dashes filter is disabled, we should only suggest unhyphenated domains.

- If the dashes filter is enabled, we should suggest all domains including hyphenated and unhyphenated domains.

Is this correct?

**Comment by klimeryk** [comment] 2021-02-09 21:46
The dashes filter has been removed from production so marking this as wontfix and closing.

**Closed by klimeryk** 2021-02-09 21:46 UTC
Labels: Domains, [Type] Question
