### ISSUE TITLE
Stats: Jetpack Stats video download count increasing unexpectedly

### ISSUE THREAD

**Issue by tellisbethel** [Automattic/wp-calypso#58137] opened 2021-11-16 18:28 UTC
### Quick summary

This user's File Download Jetpack Static count is increasing for two videos on an unpublished page that has only been seen by the user. The user considers it a bug that:

1. They never actually downloaded the videos, only having viewed them at the video link
2. The video views are considered a download even though the page is not published and never has been
3. Their views of the video count as downloads even though they're the site owner, which doesn't give them an accurate view of actual usage

### Steps to reproduce

1. Head to user's Jetpack Stats page for a specific site: https://wordpress.com/stats/day/
2. Scroll down to the File Downloads section
3. Note the download count
4. Select one of the video file links (which will open up the file for viewing in a new tab)

### What you expected to happen

Expected the count to remain the same since the video wasn't exactly downloaded, and if such views _are_ counted as downloads, didn't expect site owner views to be taken into account.  

### What actually happened

The File Download count stat for the video files increased.

### Context

Found about this from customer in this chat: 32619604-hc

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

**Comment by ivan-ottinger** [comment] 2021-11-24 08:56
When the site is public, videos (and other media) that are uploaded to the Media library can be opened by anyone - even when a post/page where the media is inserted into, is saved as draft. I think this is something we should share with the user.

---

I have tested the behavior and cannot reproduce the issue where the opening of the video file by administrator would increase download stats.

In other words, when I am logged into an administrator account on a test site and click on the video link in the Stats section:
![Markup on 2021-11-24 at 09:48:02](https://user-images.githubusercontent.com/25105483/143204913-aab016e9-b223-4b6a-b558-689b6de2bfa0.png)

the `downloads` number doesn't increase.

On the other hand, when I copy the link and open it in a browser where I am not logged in, the number of downloads increases. From what I see, the feature is working as expected.

There's a possibility that in the specific user's case, the video link was either opened from a browser where they are not logged in - or - it could have been opened by some other anonymous user / crawler.

I am closing this issue, but feel free to reopen in case I missed something. :) Thanks.

**Closed as completed by ivan-ottinger** 2021-11-24 08:56 UTC
Labels: Bug, [Feature] Stats

**Comment by tellisbethel** [comment] 2021-12-02 12:50
Thanks for looking into this Ivan! I'm not sure this is worthy of reopening just yet, but I wanted to note that when I selected the video and it opened in a new tab, the download count definitely increased. This happened on both of the videos in the user's File Downloads stats. It _might_ have been only once the video started playing, though. 

I'll try to test this theory when I have a moment and then will provide an update.

**Comment by ivan-ottinger** [comment] 2021-12-02 12:58
Thank you @tellisbethel! Sure!

Maybe if you had a screen recording available - so I could try to reproduce the issue with exact steps.

**Comment by tellisbethel** [comment] 2021-12-06 15:06
Hey @ivan-ottinger! I think I managed to reproduce the issue. I added an MP4 file via the File block onto a page that I had set to a draft. I then clicked the download button on that page's preview which opened the file in a new tab and played it. This generated the first download count in the Jetpack Stats. From there, I selected the video file from the Jetpack Stats section which opened the video in a new tab. When I went back to the stats and refreshed the page, the count went up by 1. 

Below is a screen recording of the final few steps. It's a bit mind-bendy to watch because the screen recording is one of me using the WordPress.com interface lol I hope this helps!

https://user-images.githubusercontent.com/1767799/144850172-16cb661e-32b8-47cb-9a8e-069b9e54ba4e.mp4

**Comment by ivan-ottinger** [comment] 2021-12-06 16:30
Hey @tellisbethel! Thank you for the details! That helps.

I was able to reproduce the issue this time. It looks like I probably hadn't managed to reproduce it before because of a longer delay between opening the file link and the updated stats being displayed on the Stats page.

I will take a closer look and update this issue once I know more.

**Comment by ivan-ottinger** [comment] 2021-12-07 08:59
Alright. Turns out that the Stats File Download feature was built in a way that _all_ file requests are recorded. This means that it doesn't matter if the user is logged in as administrator or any other (e.g. anonymous) user.

Also, every _file request_ is recorded. As a result, the download count is increased even if the file is opened in a browser (as opposed to being downloaded to the desktop for example) or download did not finish at all.

As the feature likely won't change in the near feature, I think it would be great to clarify the way it works in [our docs](https://wordpress.com/support/stats/).

→ I have created the following request to update the docs to prevent future confusion: 1350-gh-Automattic/en.support-docs-content.

Please let me know if anything. :)
