### ISSUE TITLE
AMP 2.0 - inconsistent top padding with Hever theme

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#51534] opened 2021-03-30 06:03 UTC
Testing AMP 2.0 and found a discrepency in the padding at the top of the site in the Reader view.

https://bakingidea.wordpress.com/2021/01/23/buttercream-cakes-or-fondant-cakes/amp/
VS
- https://bakingidea.wordpress.com/2021/01/23/buttercream-cakes-or-fondant-cakes/amp/?amp-next=1

AMP 2.0 seems to include some additional CSS:

```
@media screen and (max-width: 782px){
html:not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_):not(#_) {
    margin-top: 46px;
}
}
```

Screenshots:
<img width="680" alt="Screen Shot 2021-03-30 at 4 40 14 pm" src="https://user-images.githubusercontent.com/1842363/112941016-b0e80c80-9179-11eb-9a63-8bf45eae38d8.png">
<img width="681" alt="Screen Shot 2021-03-30 at 4 40 05 pm" src="https://user-images.githubusercontent.com/1842363/112941030-b5142a00-9179-11eb-940a-4c3c5dc6b1b6.png">

**Comment by claudiucelfilip** [comment] 2021-04-07 11:37
Thank you for raising this!

The issues seems to happen on other themes as well. It caused by a Marketing Upsell banner, which appears on Free plans. The CSS for this provide some extra top spacing for the banner to fit into. 
Opened D59725-code to remove this extra CSS from the AMP version.

**Comment by claudiucelfilip** [comment] 2021-04-14 10:18
D59725-code has been deployed. The issue should be fixed now.

**Comment by ianstewart** [comment] 2021-05-04 18:54
Just passing through and noticed this was still open. Closing.

**Closed as completed by ianstewart** 2021-05-04 18:54 UTC
Labels: Bug, AMP
