### ISSUE TITLE
Atomic Reset: WooCommerce link on dashboard fails after a site has been reset. 

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#52625] opened 2021-05-05 20:37 UTC
### Steps to reproduce the behavior

1. Create a new Business Plan site. 
2. Click on WooCommerce, and follow the prompts to install/activate/setup WooCommerce (which will make it AT). 
3. Reset your AT site by using the reset tool on the revert page (Blog Report Card - Revert this site - Reset site). 
4. Go back to the WooCommerce link on the dashboard. It will go to https://wordpress.com/woocommerce-installation/ then fail, leading to a broken WooCommerce landing page that says, "Sorry, you are not allowed to access this page."

#### What I expected to happen
The WooCommerce setup flow to function again, since the WooCommerce link is a part of the dashboard.

#### What actually happened
After a reset, the setup flow seems to still think WooCommerce is installed, doesn't try to install, and redirects to a WooCommerce landing page (but WooCommerce is not installed), where it fails.

### Context
User report. 
#### Browser / OS version
All
#### Is this specific to the applied theme? Which one?
All
#### Does this happen on simple or atomic sites or both?
Atomic
#### Is there any console output or error text?
No
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
All Atomic sites where the user requests a reset.

**Comment by JoshuaGoode** [comment] 2021-05-05 20:39
Internal Slack thread for context: p1620247076363200/1620245418.351200-slack-C03TY6J1A

Copying over some of my notes for posterity. 

---

To reproduce, I took a site without Woo on it.

I installed it via the My Site > Woo button which took me to https://wordpress.com/woocommerce-installation/

Then, I reset the site and attempted to do it again.

Something thought that Woo was installed and active on the site so took me to `wp-admin/admin.php?page=wc-admin&from-calypso`

Which cannot be accessed because WooCommerce isn't installed and activated.

---

So, it seems that if a site installs Woo via https://wordpress.com/woocommerce-installation/ , gets reset, and tries to install it that way again it won't work.

Whatever https://wordpress.com/woocommerce-installation/ is calling still thinks WooCommerce is installed and active.

**Comment by JoshuaGoode** [comment] 2021-05-05 20:58
Looks like this installation path queries Jetpack plugin list for the site https://github.com/Automattic/wp-calypso/blob/7305058b3afba928d1b377c19443fb08023e7281/client/my-sites/woocommerce/main.jsx#L30

It'll pull the plugin list from whatever was last synced.

If the site was recently reset, it'll assume WooCommerce is still installed on the site until Jetpack has synced up to the new version of the site.

This issue resolves itself after Jetpack has synced to the newly reset site and WooCommerce is not in that plugin list.

Or, we can speed things up by forcing a Jetpack sync.

Or, the user can install and activate the plugin via the old normal way. 

----

This can probably be closed as won't fix since this is a bit of an edge case, can resolve itself after a Jetpack sync, and also has a quick alternative installation option.

**Closed as completed** 2021-05-19 19:54 UTC
Labels: Bug
