### ISSUE TITLE
CoBlocks animate CSS causes elements to stay invisible

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#54276] opened 2021-07-05 04:32 UTC
CoBlocks is a third-party plugin that [we provide for Atomic sites](https://wordpress.com/support/wordpress-editor/blocks/coblocks/). A CSS class definition for `coblocks-animate` is also loaded on Simple sites by WordPress.com.

```
.coblocks-animate {
    -webkit-animation-fill-mode: forwards;
    animation-fill-mode: forwards;
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 0;
}
```

Screenshot from a Simple site:

![image](https://user-images.githubusercontent.com/33957570/124417025-e81c1a00-dd75-11eb-9fe9-b5c8e5594788.png)

CoBlocks is a third-party plugin. Its CSS should not be active on Simple sites when it doesn't have CoBlocks features.

Because of the CSS related the CoBlocks, after a downgrade from AT to Simple, the elements that have `coblocks-animate` as an additional class would become invisible. 

Current workaround is to ask them to add this CSS code:

```
/* Override '.coblocks-animate' opacity */
.coblocks-animate {
opacity: 1;
-webkit-animation-fill-mode: forwards;
animation-fill-mode: forwards;
-webkit-animation-timing-function: ease-in;
animation-timing-function: ease-in;
}
```

But it would work only on the front end. The elements will stay invisible in the editor.

### Steps to reproduce the behavior

1. Go to a simple site.
2. In a page / post , add an element and add the class `coblocks-animate`.
3. You will notice that the element becomes invisble both in the editor and live page because of CSS code of `coblocks-animate` from WordPress.com

#### What I expected to happen

Elements with `coblocks-animate` should not become invisible in Simple sites.

#### What actually happened

Elements with `coblocks-animate`  became invisible in Simple sites. It is problematic for Atomic sites that were previously using CoBlocks animate.

### Context

Related tcket: 4114240-zd-woothemes

#### Is this specific to the applied theme? Which one?

No.

#### Does this happen on simple or atomic sites or both?

Simple

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

High. Affects all Simple sites.

**Comment by devNigel** [comment] 2021-07-05 08:54
~~Reported in CoBlock repo: https://github.com/godaddy-wordpress/coblocks/issues/1930~~

**Comment by WunderBart** [comment] 2021-07-05 09:27
Thanks for reporting, @devNigel! We do have CoBlocks on Simple sites, although it is a customized build that contains only a selected portion of the plugin functionality. The animations are indeed not a part of it, so it's most probably fixable by patching our custom CoBlocks build for Simple sites.

As for the [upstream issue](https://github.com/Automattic/wp-calypso/issues/54276#issuecomment-873933328) - it does not make sense in this case as the bug is caused by a logic specific to A8c. Would you mind closing it? This one is perfectly fine 👌

**Comment by devNigel** [comment] 2021-07-05 09:44
I have closed the ticket in CoBlocks.

**Comment by WunderBart** [comment] 2021-07-09 15:07
Addressed via D63891-code

**Comment by WunderBart** [comment] 2021-07-09 16:14
The fix has been deployed (D63891-code). @devNigel, could you confirm if the issue has been fixed?

**Closed as completed** 2021-07-10 09:05 UTC
Labels: Bug, [Feature] Post/Page Editor, Needs triage, [Feature] CoBlocks

**Comment by happychait** [comment] 2021-07-10 23:10
@WunderBart  Thank you so much for fixing the bug. I can confirm the home page cover blocks now appear on the customer's site without having to apply the custom CSS fix.

Thanks again!

**Comment by cuemarie** [comment] 2021-08-03 21:27
I have a user who has `coblocks-animate` rendering their content invisible on an AT site here: 4192158-zd-woothemes
I'm recommending they try removing the Additional CSS and seeing if their content looks as expected.
