### ISSUE TITLE
"WP Admin equivalents" setting not respected for widgets and menus

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#49830] opened 2021-02-08 15:53 UTC
### Steps to reproduce the behavior

1. Go to https://wordpress.com/me/account
2. Ensure the "Replace all dashboard pages with WP Admin equivalents when possible." setting is enabled
3. Open a site in Calypso or WP Admin 
4. Note the links still point to Customizer such as Widgets and Menus (it may impact more links, but these are the two I immediately noticed)

#### What I expected to happen

Widgets and Menus to open their WP Admin equivalent

#### What actually happened

They opened in the Customizer

#### Does this happen on simple or atomic sites or both?

Both 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

All sites, but low impact. The pages can still be accessed by direct URL

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screen Shot 2021-02-08 at 10 51 05 AM](https://user-images.githubusercontent.com/1900444/107244228-cbb0c700-69fb-11eb-9705-0bb146a9e36f.png)

**Comment by cpapazoglou** [comment] 2021-02-10 09:48
@obenland I suggest that "Widgets" & "Menus" load the WP Admin screen and not the customizer when "Replace all dashboard pages with WP Admin equivalents when possible" is enabled for Atomic sites only.

Especially customers who use WPML will need `/wp-admin/nav-menus.php`.

**Comment by kriskarkoski** [comment] 2021-02-10 12:19
I'm curious, why only on Atomic sites? That doesn't seem to be respecting the current wording of the setting.

**Comment by cpapazoglou** [comment] 2021-02-10 12:27
> I'm curious, why only on Atomic sites? That doesn't seem to be respecting the current wording of the setting.

That's a good point @kriskarkoski, thanks for raising it.

I suggest doing so only for Atomic cause we:
1) want people to use the customizer for menus & widgets cause it is the way forward for Full Site Editing.
2) Atomic users may install 3rd party plugins that add features to these screens.

**Comment by obenland** [comment] 2021-02-10 15:46
> I suggest that "Widgets" & "Menus" load the WP Admin screen and not the customizer when "Replace all dashboard pages with WP Admin equivalents when possible" is enabled

That's fine, let's also apply that to all environments.

**Comment by obenland** [comment] 2021-02-10 18:24
I'd not consider this launch blocking at this point

**Comment by inaikem** [comment] 2021-09-09 09:27
Reopening this, as it appears nav links to WP Admin versions of the menu and widget pages are once again pointing to the Cusomizer for Atomic sites.

Accessing the pages directly works as expected at `/wp-admin/nav-menus.php` and `/wp-admin/widgets.php`.

User report: 4284607-zen.

**Comment by mmtr** [comment] 2021-09-09 09:56
@inaikem I think that's the intended behavior. See p1628525963071300/1628262477.060300-slack-CB0B2G43X p1628193314037400/1628119959.008100-slack-C021Z8P3RMG. As of https://github.com/Automattic/jetpack/pull/20587, all these menus point to the Customizer.

**Comment by inaikem** [comment] 2021-09-09 10:03
Thanks Miguel! I am curious, though. I was under the impression that we would continue to point Atomic users to the WP Admin screen when they have the "Classic View" selected under screen options - I may well have made that up but would like to clarify all the same!

**Comment by mmtr** [comment] 2021-09-09 10:08
> we would continue to point Atomic users to the WP Admin screen when they have the "Classic View" selected under screen options

Unfortunately, the layout of Customizer screens doesn't offer a screen options button, so we couldn't provide users the ability to choose their preferred view (see https://github.com/Automattic/wp-calypso/issues/55231).

**Comment by inaikem** [comment] 2021-09-09 10:14
Agreed. I appreciate there's limited screen real estate in the Customizer to add a dedicated toggle and should have been clearer: 

I'm advocating that for Atomic sites, whenever the Classic view is active via the screen options panel (regardless of where it was selected), we should be redirecting clicks to `Appearance > Menus`  and `Appearance > Widgets` to their respective WP Admin links and not the Customizer.

**Comment by simison** [comment] 2021-09-09 10:15
Aren't "screen options" meant for setting showing Calypso/wp-admin views, whereas here we have just wp-admin views, and no Calypso views?

**Comment by mmtr** [comment] 2021-09-09 14:54
That's right, I forgot that we link to the WP Admin Customizer, and thus only the classic view is supported by the screen options. 

In order to allow users to switch between `wp-admin/widgets.php` and `wp-admin/customize.php?autofocus%5Bpanel%5D=widgets`, we'd need to implement something completely new.

Alternatively we can keep the default widgets menu registered by Core which links to `wp-admin/widgets.php`, since that screen includes a link to the Customizer:

<img width="1318" alt="Screen Shot 2021-09-09 at 16 53 41" src="https://user-images.githubusercontent.com/1233880/132709673-5c2f7b55-6011-4839-b37d-0a4032854a04.png">

**Comment by inaikem** [comment] 2021-09-14 01:56
Linked issue with user reports here: https://github.com/Automattic/wp-calypso/issues/55388

**Comment by inaikem** [comment] 2021-09-14 01:57
From interaction 18097743-hc

...now WordPress.com has updated to a new Menu creation/editing screen and the old is completely gone. All of the functionality that I relied upon is now completely gone as well. Why would the team get rid of a screen completely. I'd like access to the legacy menu building screen.

**Comment by JoshuaGoode** [comment] 2021-09-14 14:20
Copying over the feedback I've shared on the respective issues related to the core Widgets and Menus navigation.  

This change has been generating numerous support interactions and HE reports. The workaround is to have the user remember or bookmark the direct link to the pages. 

* Appearance > Menus: #55388
* Apperance > Widgets:  #55553

--

Having the option to navigate to the core WP-Admin pages is essential for WordPress.com on Atomic sites using third-party themes and plugins.

If we keep this new behavior, there absolutely needs to be an option to toggle this off or have a workaround for WoA sites that need to use the WP core behavior.

**Why?**
WoA users going to Appearance > Menus and Appearance > Widgets have historically been taken to the proper WP-Admin page and not the Customizer.

Those pages are essential for numerous popular third-party plugins and themes. In some cases, the options are not available in the Customizer.

--

**Example**
Users are having to manually go to the following links. This needs a toggle or option similar to the Screen Options we have now.

• wp-admin/nav-menus.php
• wp-admin/widgets.php

Many sites using a plugin like `megamenu` will have to manually access wp-admin/nav-menus.php using a direct link.
There are other plugins and themes that rely on the WP-Admin Menus page and/or the WP-Admin widgets page.

Additionally, editing block widgets in the Customizer is a bit problematic in its current iteration.  At times, it's much easier to navigate and edit in the dedicated WP-Admin page. 

--

Related internal discussion:

p1631178748139800-slack-C7YPUHBB2

**Comment by mmtr** [comment] 2021-11-01 14:22
Closing this one out, since “Appearance > Widgets” and “Appearance > Menus” now link back to classic “widgets.php” and “nav-menus.php” destinations for Simple and Atomic sites!

**Closed as completed by mmtr** 2021-11-01 14:22 UTC
Labels: Bug, [Pri] High, [Feature] Calypso & wp-admin Navigation
