### ISSUE TITLE
Themes: deleting theme from Jetpack site fails (parent theme?)

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#11048] opened 2017-01-30 15:23 UTC
We have reports of themes failing to be deleted with the message "Check theme is not active.".

1. `twentysixteen`
2. `twentyseventeen`
3. `rennews-child`

/ht @StefMattana @jeherve 

<img width="972" alt="screen-shot-2017-01-30-at-12-39-32" src="https://cloud.githubusercontent.com/assets/4389/22428723/06fdb1ac-e700-11e6-81a2-20a1f24a8d42.png">

![screen-shot-2017-01-30-at-15-47-24](https://cloud.githubusercontent.com/assets/4389/22428725/09d51136-e700-11e6-89fe-08eb29d564fa.png)

**Comment by budzanowski** [comment] 2017-02-24 11:45
Looks like this was fixed by some other changes along the way.
User is able to delete theme as long it is not active or it is not a parent of active theme.

Cant reproduce. Closing.

**Closed by budzanowski** 2017-02-24 11:45 UTC
Labels: Themes, [Type] Bug
