### ISSUE TITLE
Missing https protocol when sharing posts/pages links from Calypso on Simple Sites

### ISSUE THREAD

**Issue by jartes** [Automattic/wp-calypso#57308] opened 2021-10-25 06:32 UTC
### Quick summary

When copying posts/pages links from the Posts/Pages pages from Calypso on Simple Sites with a domain connected, the protocol for these URLs is `http` instead of `https`. Possibly related to #50051.

### Steps to reproduce

1. On a Simple Site with a custom domain connected and as primary address, go to Pages or Posts pages. 
2. Click on the three-dots button for any post/page. 
3. Click on the `Copy link` link.

![138552278-6a28d1a7-5ea8-4554-b9b8-588ac06462a4](https://user-images.githubusercontent.com/1046943/138645559-2ad2e98f-b33b-4f7d-84e5-7d4f2796ce62.png)

### What you expected to happen

Get the post/page URL with the `https` protocol on it.

### What actually happened

Got the post/page URL with the `http` protocol.

### Context

User report: 4383017-zd-woothemes

### Operating System

macOS

### Browser

Google Chrome/Chromium, Apple Safari

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

There is no user impact

**Comment by mreishus** [comment] 2021-11-15 20:45
Alternate reproduction instructions:
* Have two simple sites, one with a custom domain, one without
* Visit https://developer.wordpress.com/docs/api/console/
* Use WP.COM API / v1.2 / GET / `/sites/1234`, where 1234 is the site id
* Notice the `url` key for the custom site uses http, but the non-custom one uses https.

This is caused by [this block](https://github.com/Automattic/jetpack/blob/580a87378c2645988c72d74d3fa5dae16376cd66/projects/plugins/jetpack/class.json-api.php#L187-L192) of code.

This looks to be related to:
* https://github.com/Automattic/jetpack/pull/2603
  * 2015-08-24: This removes the filter, which is what I want to do, but it had to be re-added.
* p1443108993000912-slack-C02DQP0FP (includes a video)
  * 2015-09-24: "The View Site link in Calypso is forcing HTTPS on custom domains which is resulting in warning messages"
* r124548-wpcom
  * 2015-09-24: Revert pushed.
    * Reverts r124538-wpcom, which is an automatic sync from jetpack -> wpcom, which includes https://github.com/Automattic/jetpack/commit/51ef6c8
    * This adds the filter back
* https://github.com/Automattic/jetpack/commit/15a7d38e65601c04c973d8afc7e4dd1ea2f36b9d | Belongs to https://github.com/Automattic/jetpack/pull/2803
  * 2015-10-04: The filter was re-added.
  * There's hardly any documentation here :(

**Comment by mreishus** [comment] 2021-11-15 22:17
In 2016, we offered "free HTTPS for all custom domains hosted on WordPress.com". Blog post: https://wordpress.com/blog/2016/04/08/https-everywhere-encryption-for-all-wordpress-com-sites/
PR: https://github.com/Automattic/jetpack/pull/21747

**Comment by mreishus** [comment] 2021-11-16 22:34
This had to be reverted. Currently, this is basically an intractable problem. We try to provide valid SSL certificates for all simple sites, but some small % do not have them. With the proposed changes, I found at least one site that returned https:// as the url in the sites endpoint, but the browser showed an error when visiting the https:// version of it.

When we are building a response for the `/sites/` endpoint, we do not know which ones have valid endpoints, and which don't. 
There is a `wpcom_domain_has_ssl_cert()` function, but it looks for special HTTP headers set by an external system, so it can only run properly in the context of a request for that site (IE, not public-api). The information is in the ACME/LE system, but not accessible to WordPress.com.

For this to happen, we'll need the systems team to inject the SSL status of a site into the blog object, which is currently on Barry's todo list, but near the bottom. If this happens in the future, we can revisit.

References:
pMz3w-93X-p2#comment-65524
pMz3w-dmd-p2#comment-89642
pMz3w-dvF-p2#comment-90397
pMz3w-6CM-p2

**Comment by kerrynicl** [comment] 2021-11-17 20:37
Since there's a reason for this and that's the expected behaviour, I'll go ahead and close this one for now

**Closed as completed by kerrynicl** 2021-11-17 20:37 UTC
Labels: Bug, [Pri] Normal, Triaged, [Pod] Flow Patrol (Manage)
