### ISSUE TITLE
Bug?: connection restore toaster css updates width

### ISSUE THREAD

**Issue by gfogle** [Automattic/wp-calypso#2057] opened 2016-01-01 08:08 UTC
URL: http://calypso.localhost:3000/start/developer/themes

What I expected: the connection toaster doesnt adjust container width on scroll and goes away over time

What happened instead: the connection toaster doesnt go away adjusts width and appears cropped by adding pinned css class

Steps to reproduce: start stop server and wait for connection restore toaster

Browser OS version: chrome 47 on el capitan

Screenshots/Video:

<img width="795" alt="screen shot 2016-01-01 at 3 00 35 am" src="https://cloud.githubusercontent.com/assets/7015773/12070195/922794e0-b034-11e5-8bad-fc619663b799.png">

<img width="389" alt="screen shot 2016-01-01 at 3 02 08 am" src="https://cloud.githubusercontent.com/assets/7015773/12070196/95ec2be0-b034-11e5-9771-a8fdff97545b.png">

<img width="317" alt="screen shot 2016-01-01 at 3 02 21 am" src="https://cloud.githubusercontent.com/assets/7015773/12070197/9a1f0ad4-b034-11e5-9973-4a20e91c5998.png">

**Comment by lancewillett** [comment] 2016-04-08 00:13
I can't reproduce this today. Closing as "works for me."

**Closed by lancewillett** 2016-04-08 00:13 UTC
Labels: Notifications, OSS Citizen, Themes, [Type] Bug
