### ISSUE TITLE
Media: Number Appended to File Names When Uploading a File with the Same Name as a Deleted File

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/wp-calypso#32987] opened 2019-05-13 15:47 UTC
#### Steps to reproduce
1. Navigate to My Site > Site > Media
2. Upload a media file to your library
3. Delete the file from your media library
4. Upload a new file with the same name as the deleted file.

#### What I expected
The newly uploaded file would retain its file name since the originally uploaded file was deleted.

#### What happened instead
The newly uploaded file has "-1" appended to the end of the file name.

#### Browser / OS version
Tested in Chrome on macOS Mojave, but can be replicated on other browsers as well.

#### Screenshot / Video

Video:
https://d.pr/free/v/oiPUFv

#### Context / Source
First reported by user here: 9952330-hc

#user-report

**Comment by ktyfuller604** [comment] 2019-05-30 21:51
#13134833-hc reported the issue. Visitors bookmark the direct link to the file, so keeping the same file name is important.

**Comment by tbradsha** [comment] 2019-05-31 15:35
13149772-hc

**Comment by tbradsha** [comment] 2019-05-31 15:43
Note that this occurs in /wp-admin as well as Calypso.

**Comment by lancewillett** [comment] 2019-05-31 22:11
I suggest closing this as "works as expected" — this is intended behavior so that file collisions don't occur when you have multiple files with the same name over time.

I believe this is the same behavior in core WordPress.org sites across the web.

_Admin note for healthy bug reporting:_

If this isn't specific to Calypso, let's move it to a different bug tracker.

If only on WP.com — wpcom Trac
If on any WordPress.org site — core Trac

**Closed by lancewillett** 2019-05-31 22:11 UTC
Labels: Feature request

**Comment by mdrockwell** [comment] 2019-06-01 16:28
Thanks for the heads up on where the best place to report bugs like this is! I guess I forgot to test whether this takes place in wp-admin as well.

But after a bit of testing on a self-hosted site, it does the expected behavior there — the number isn't appended to the file name if the original file is deleted. So I'll be submitting this to Trac shortly.
