### ISSUE TITLE
Jetpack Connect: Inaccurate error about existing connection when user restarts connection flow

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#22591] opened 2018-02-19 16:58 UTC
#### Steps to reproduce
These steps are intended to reproduce the flow a user might go through if they stop before completing the Jetpack connection to WordPress.com, and then decide later to finish connecting to WordPress.com:

1. Starting at URL: Self-hosted site's WP Admin dashboard
2. Install and activate Jetpack.
3. Select "Set up Jetpack" to enter Jetpack Connect flow.
4. Before approving the connection to WordPress.com, quit the flow.
5. Go back to WP Admin and select "Set up Jetpack" again.
6. On the "Completing connection" page, note the error message `This site is already connected to a different WordPress.com user, you need to disconnect that user before you can connect another.` and select "Go back to your site" to return to WP Admin.
7. Select "Set up Jetpack" in WP Admin again.
8. Select "Approve" to authorize the connection to WordPress.com.
9 Continue the connection flow as expected.

#### What I expected

I expected that after step 5 I would enter the connection flow and be able to connect my site just as I had started to do earlier.

#### What happened instead

I received the error message in step 6, even though Jetpack had not been connected to WordPress.com (there were no connections to other WordPress.com users).

#### Browser / OS version

macOS 10.13.3 / Chrome 64

#### Screenshot / Video

![screenshot 2018-02-19 16 50 13](https://user-images.githubusercontent.com/8658164/36388841-17392852-1595-11e8-95a9-85b1c58090f4.png)

#### Context / Source
#manual-testing #flow-testing

**Comment by rachelmcr** [comment] 2018-02-19 17:12
In testing, I'm finding that this error often occurs when I connect a Pressable site, even if I didn't previously abandon the connection flow. This may be due to how plans for Pressable sites are provisioned (I haven't tested with other partner hosts but I'd expect a similar issue with them) and how the shadow site is created before the connection flow begins.

**Comment by johnHackworth** [comment] 2018-03-05 15:36
This issue is already fixed, and I've just checked and I couldn't reproduce it anymore, so I'm closing it

**Closed by johnHackworth** 2018-03-05 15:36 UTC
Labels: FixTheFlows, Jetpack, Signup, [Pri] Normal, [Type] Bug
