### ISSUE TITLE
Reader Search on Manage: URL matching things that aren't correct URLs

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#13945] opened 2017-05-11 17:25 UTC
This is partially a display problem, and partly an interaction problem. The detection of what is a host is not very good right now. Should we only do this when there is actually an "http" at the beginning?

<img width="799" alt="screen shot 2017-05-11 at 11 19 10 am" src="https://cloud.githubusercontent.com/assets/820871/25962715/0a18f0fa-363c-11e7-9392-5c36890c30fc.png">

<img width="759" alt="screen shot 2017-05-11 at 11 19 19 am" src="https://cloud.githubusercontent.com/assets/820871/25962720/0e0ebec4-363c-11e7-9a87-d4e6f5188a31.png">

This second one of course won't actually follow what the user wants. It also feels odd how the display changes here.

https://wpcalypso.wordpress.com/following/manage?q=watirmelon.bl

Similar problems occur when trying to search for things like "testingthemind.wordpress.com" or worse "testingthemind.word"

**Comment by fraying** [comment] 2017-05-11 17:34
> The detection of what is a host is not very good right now. 

Great point. What can we do to make this better?


> Should we only do this when there is actually an "http" at the beginning?

That would solve the problem, but I'd hate to go there because if you asked most people for a URL, they'd likely say "whatever.com" - not "http://whatever.com".


> It also feels odd how the display changes here.

Can you define "odd" here? FWIW, the display changing from search results to the single URL result is happening as designed. Maybe it feels off because we're not used to it yet.

Keep in mind that, in the first example, if the user was trying to follow "watirmelon.blog", they'd likely stop typing at "watirm" when they saw that the site they wanted is the first result and just click the follow link. So there'd be no need to type the full URL. This is good! 

All that said, yeah, our URL detection could benefit from some finesse.

**Comment by gibrown** [comment] 2017-05-11 17:53
This also breaks "nytimes.com" or "nytimes.co. Trying to follow either of those fails even though the UI makes it feel like nytimes.co is something that I could follow

<img width="792" alt="screen shot 2017-05-11 at 11 52 14 am" src="https://cloud.githubusercontent.com/assets/820871/25963933/57e2ee18-3640-11e7-88e2-d39783875ca8.png">

This is where I get stuck after I try to follow it.

**Comment by gibrown** [comment] 2017-05-11 17:56
> Can you define "odd" here? FWIW, the display changing from search results to the single URL result is happening as designed. Maybe it feels off because we're not used to it yet.

It makes it feel like this is going to succeed, when in fact, the url is incorrect, so it is actually going to fail. And worse, it will take a while to fail because the server will try to go out and fetch things. I'd like it better if it indicated something like: "we don't have anyone following that yet, but we can go try to fetch it for you". Or if we do have people following it, then make it clear that it will just work.

**Comment by gibrown** [comment] 2017-05-11 18:02
Another good example for testing: "en.blog"

**Comment by fraying** [comment] 2017-05-11 18:21
@gibrown Right. So, how do we account for the fact that "nytimes.co" could be a valid URL to follow?

Some of the limitations in the design process were:
1. the user can enter any URL here and we'll try to follow it
2. it doesn't matter if the URL is in our index or not, and 
3. even if it is in our index, we don't know that at this moment, so we can't do things like display avatars, titles, descriptions, etc.

So, the flow we've got now is a result of those limitations. If we can change one or more of them, then we can change the UX.

In any case, I think "make URL detection as smart as we can" is a goal we can all get behind.

**Comment by blowery** [comment] 2017-05-11 18:34
could we add a special first result to the search results that is a "follow exactly that thing which we think is a URL"?

**Comment by gibrown** [comment] 2017-05-11 18:37
> So, how do we account for the fact that "nytimes.co" could be a valid URL to follow?

I think we should try the following:
- search on all input and try to find a site that matches exactly (return search results to Calypso, and then if there is an exact match, show that one result with the extra meta info)
- if input starts with http(s)://, then immediately show a follow link, but do a search in the background and indicate we are doing it (checking for site). If that check fails still let the user try to follow it.
- if the input doesn't start with "http", then it looks like any other search until we start getting some results.
- If the text looks like a url/host (nytimes.co, nytimes.com/opinion) and we get an exact match for the url/host from search, then highlight that it is an exact match (only show one). Maybe show multiples if we get multiple exact matches. This last one is essentially what @blowery said.

**Comment by fraying** [comment] 2017-05-11 19:36
Hooray for big zoom call just now!

Basically, lots of fiddly bits to work on here, but we're heading in the right direction. None of this should block the call for testing. But we're gonna do two things:

1. Try a branch that requires "http" to show the URL state (instead of X.XX). That way we can at least test search results when you put in a domain (whatever.com without the "http") and see how they are. ( @blowery & @samouri )

2. Design project to figure out if it's possible to show both direct-URL follow and search results at the same time without it being too confusing. (On my list)

Ever forward!

**Comment by samouri** [comment] 2017-05-11 19:50
> Try a branch that requires "http" to show the URL state (instead of X.XX). That way we can at least test search results when you put in a domain (whatever.com without the "http") and see how they are. ( @blowery & @samouri )

done in https://github.com/Automattic/wp-calypso/pull/13957

**Comment by fraying** [comment] 2017-05-11 23:08
> Design project to figure out if it's possible to show both direct-URL follow and search results at the same time without it being too confusing. (On my list)

Posted here: https://github.com/Automattic/wp-calypso/issues/13969

**Comment by fraying** [comment] 2017-05-11 23:32
Nice work, all. I'm gonna close this issue since we've spawned other now.

**Closed by fraying** 2017-05-11 23:32 UTC
Labels: Reader, [Type] Bug
