### ISSUE TITLE
Table of Content links not working from within the Calypso Help Center

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/wp-calypso#86553] opened 2024-01-17 17:08 UTC
### Quick summary

When clicking on support article links from the `?` menu in WordPress.com dashboard, the TOC links are not going to support center articles. 

### Steps to reproduce

1. Start at any page inside Calypso dashboard, e.g. https://wordpress.com/view/{siteURL}
2. Click on the `?` icon to open help center
3. Click on any of the suggested topics to get started, e.g. `Quick Start Guide` which opens up https://wordpress.com/support/getting-started-with-wordpress-com/ inside the dashboard
4. From there, click on one of the Table of Contents items, e.g. `The Basics`

### What you expected to happen

This should open up this link: https://wordpress.com/support/getting-started-with-wordpress-com/#the-basics

### What actually happened

It redirects to this link: https://wordpress.com/view/{siteURL}#the-basics, so therefore just re-opens the Calypso dashboard 

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Related slack conversation: p1705333938195889-slack-C03TY6J1A

**Comment by maciejpilarski** [comment] 2024-01-17 20:09
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue:
![Markup on 2024-01-17 at 21:07:44](https://github.com/Automattic/wp-calypso/assets/9025643/64888108-b1a0-4b6f-95be-5f668d137c0e)


📌 ACTIONS
- Triaged

**Comment by lsl** [comment] 2024-02-01 04:22
Seeing same thing here, the link opens the editor (again) instead of scrolling to the item in the help text.

![Screenshot(103)](https://github.com/Automattic/wp-calypso/assets/811776/cb651775-9da8-4dcf-9d33-675e3aea2d39)

**Comment by lupus2k** [comment] 2024-07-11 19:05
Hey @foleynotrose, As part of pb5gDS-3YO-p2, we're aiming to fix/close high-priority issues in [The One Board](https://github.com/orgs/Automattic/projects/391/views/12)

I tried to reproduce the issue without success. Can you confirm whether the issue is still happening?

https://github.com/user-attachments/assets/2d0001f4-482b-404d-b958-fde97cb9ccd2

**Comment by foleynotrose** [comment] 2024-07-15 14:02
> Can you confirm whether the issue is still happening?


It seems this is *mostly* resolved. If you click on a TOC link while still inside the WordPress.com dashboard help center, it navigates to the expected link inside the dashboard help center as expected. 

The only potential problem is if someone clicked on a TOC link to `open in a new tab`, it would then just redirect back to the WordPress.com dashboard. 

I hope that makes sense!

**Comment by lupus2k** [comment] 2024-07-15 15:07
Thanks @foleynotrose, I'll close the issue since it's resolved. Do you mind to create a new issue for the `Open in a new tab` issue?

Thanks in advance!

**Closed as completed by lupus2k** 2024-07-15 15:07 UTC
Labels: Bug, [Pri] High, [Feature Group] Support, Triaged, [Feature] Help Center, [Status] Priority Review Triggered, [Product] WordPress.com
