### ISSUE TITLE
Using Google Fonts causes low text-HTML ratio SEO issues

### ISSUE THREAD

**Issue by mgozdis** [Automattic/wp-calypso#81046] opened 2023-08-24 22:48 UTC
### Quick summary

When using Google Fonts with the Gutenberg plugin, it adds hundreds to thousands of lines of code for every style variation/encoding. A user reported this is creating low text-HTML ratio issues for SEO reports with Semrush. 
User report: 6719104-zd-a8c

Screenshot: ![cL0ZvB.png](https://github.com/Automattic/wp-calypso/assets/121042930/f7b60ce8-cf49-4351-87de-6491847bbf5c)

A couple of known workarounds are to not use Google Fonts or deactivate Gutenberg plugin. 

### Steps to reproduce

1. Create a new AT site with any FSE theme such as Lativ
2. View the source code of the default homepage and see all the fonts defined

### What you expected to happen

Users may expect Google Fonts to make a single request to the Google Font API for the necessary font rather than including the output and font-face definitions directly in the page so as to not impact low text-HTML ratio.

### What actually happened

It seems the output of a request like the following is included in the page affecting text-HTML ratio: `https://fonts.googleapis.com/css?family=Open+Sans`

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment] 2023-08-25 00:09
📌 REPRODUCTION RESULTS
- Tested on Atomic – **Replicated** 
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
New Atomic site with TT3 active all the google fonts loaded in the page source as described. (`wp-fonts-jetpack-google-fonts` takes up about ~2,000 lines)


https://github.com/Automattic/wp-calypso/assets/27249804/9c2a4fa3-028c-4c2e-a3ea-c4d7463df16b



On a self-hosted site (Pressable) with _only_ Gutenberg active, only `wp-fonts-local` is present, which is much shorter:


📌 ACTIONS
- Triage complete
- cc: @jeherve

**Comment by cuemarie** [comment] 2023-08-25 00:13
Also, due to: 

- https://github.com/Automattic/wp-calypso/issues/78904

customers would need to come to support for help disabling Google Fonts, as it's not a module that they can manage.

**Comment by mgozdis** [comment] 2023-08-25 00:43
@cuemarie Regarding disabling the Google Fonts module for users, I tried that in the related interaction via BRC and it would not disable. The toggle would switch off but refreshing the BRC would show Google Fonts enabled again. I can reproduce the same on a test site's BRC: https://github.com/Automattic/wp-calypso/assets/121042930/66b31c72-91ef-43d4-ac5e-86807f66d2e4

There may be some other issue going on with that module or there are checks to prevent it from being disabled if the fonts are being used. Only deactivating Gutenberg worked but that's not ideal for most users.

**Comment by jeherve** [comment] 2023-08-28 16:32
> The toggle would switch off but refreshing the BRC would show Google Fonts enabled again

Yes, that's done on purpose; the module is automatically enabled on Atomic sites, hence why folks would need to ask support for help to disable it (it works just like the masterbar module behind the scenes, see 918-gh-wpcomsh )

**Comment by csabarakasz** [comment] 2023-08-29 20:56
Same issue here: 6690805-zd-a8c

**Comment by mgozdis** [comment] 2023-08-29 21:52
> Same issue here: 6690805-zd-a8c

Just noting this is the same user I opened the issue for. They must have created multiple tickets. I've explained that this may be expected due to our concatenation and recommended using a plugin that would let them limit the weights, styles, etc that are loaded when using Google Fonts.

**Comment by davemart-in** [comment] 2024-10-15 15:43
No movement on this one in over a year. I'm closing as "won't fix". But happy to re-open if someone wants to take it on.

**Closed as completed by davemart-in** 2024-10-15 15:43 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Normal, Triaged, [Feature] Google Fonts, Customer report [LEGACY], [Plugin] Jetpack, [Product] WordPress.com
