### ISSUE TITLE
Focused Launch: inside editor, color scheme is partly inherited from wp-admin theme

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [Automattic/wp-calypso#48928] opened 2021-01-14 16:28 UTC
Some buttons and some inputs in Focused Launch inherit styling from the user's `wp-admin` theme instead of `wp-calypso`.

Then, because the rest are using Calypso (or onboarding specific) colors, the result is a mix between the two. 

#### Acceptance criteria
- [ ] _Update_ button should use theme color
- [ ] Primary color in both launch flows should be as in design, regardless of the wp-admin theme

#### Launch button
<img width="540" alt="Screenshot 2021-01-12 at 13 37 06" src="https://user-images.githubusercontent.com/12104589/104616637-d1302100-568a-11eb-812f-a201e6cb47e7.png">

#### Focused Launch
<img width="1353" alt="Screenshot 2021-01-14 at 18 26 26" src="https://user-images.githubusercontent.com/12104589/104619140-d17deb80-568d-11eb-8e11-5a2bcab6ca08.png">

<img width="1043" alt="Screenshot 2021-01-14 at 18 23 12" src="https://user-images.githubusercontent.com/12104589/104618970-a5626a80-568d-11eb-9579-9a8bd8c28f34.png">

<img width="1164" alt="Screenshot 2021-01-14 at 18 20 48" src="https://user-images.githubusercontent.com/12104589/104618980-a7c4c480-568d-11eb-8105-2c1e71cbdbde.png">

<img width="1306" alt="Screenshot 2021-01-12 at 13 39 05" src="https://user-images.githubusercontent.com/12104589/104616630-ce353080-568a-11eb-9a1b-2fb12ce79ddd.png">

**Comment by razvanpapadopol** [comment] 2021-09-23 14:57
The issue is still valid but not directly related to `/new` signup flow since it's only inside the editor.

**Comment by youbrokesomething** [comment] 2022-09-22 21:48
Focused Launch is no longer active and has been replaced by other projects. I'm closing this issue.

**Closed as completed by youbrokesomething** 2022-09-22 21:48 UTC
Labels: Bug, [Pri] Normal, Focused Launch
