### ISSUE TITLE
FSE: Ability to remove WordPress.com footer credit without visiting Customizer

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35577] opened 2019-08-19 18:00 UTC
To remove a WordPress.com footer credit on a site, one can visit the Customizer. This is available only on the WordPress.com Business plan sites.

With FSE though, we are hoping to enable users to modify their site pages without the Customizer. So, the ability to remove the footer credit via the footer section feels like an nice idea that we can pursue.

There is also `Footer credit` card on https://wordpress.com/settings/general that we can avoid showing if we decide to pursue this idea.

<img width="794" alt="Screenshot 2019-08-19 at 23 29 31" src="https://user-images.githubusercontent.com/18581859/63287996-41d9df00-c2d9-11e9-8ce1-6141d1990f3f.png">

Tagging as enhancement.

**Comment by apeatling** [comment] 2019-08-19 18:37
Marking as a duplicate of https://github.com/Automattic/wp-calypso/issues/34760

**Closed by apeatling** 2019-08-19 18:37 UTC
Labels: [Goal] Full Site Editing, [Type] Enhancement
