### ISSUE TITLE
Facebook video embed not appearing on mobile (iOS)

### ISSUE THREAD

**Issue by adelineyaw** [Automattic/wp-calypso#46661] opened 2020-10-21 20:36 UTC
#### Steps to reproduce

1. Starting at URL: https://lebanesedaily.com/2020/10/20/%D8%A3%D9%88%D8%AC%D9%87-%D8%A7%D9%84%D8%B4%D8%A8%D9%87-%D8%A8%D9%8A%D9%86-%D8%A8%D9%87%D8%A7%D8%A1-%D9%88%D8%B1%D9%81%D9%8A%D9%82-%D8%A7%D9%84%D8%AD%D8%B1%D9%8A%D8%B1%D9%8A/
2. View this post on an iPhone
3. Click the play icon on the Facebook video embed
4. Video doesn't play

#### What I expected
I expect the video to play as seen on Android

#### What happened instead
Video doesn't play when clicked

#### Browser / OS version
On an iPhone, we've tried Chrome and Safari and the video doesn't play. I've asked for others to test on an iPhone and it was confirmed that the video doesn't play: p1603275003143600-slack-C03TY6J1A

However the video plays as expected on an Android.

#### Screenshot / Video
User provided screenshot: https://lebanesedaily.com/wp-content/uploads/2020/10/Screenshot-Post-with-Video-not-playing.jpeg

#### Context / Source
Chat: #21705797-hc
Follow up ticket: #3426880-zen

**Comment by cathymcbride** [comment] 2020-10-22 20:28
checking with @designsimply to see if this belongs on the iOS repo.

**Comment by designsimply** [comment] 2020-10-22 21:23
Since the problem is reported to be happening with Safari, not the WPiOS app, we should triage it here in the Calypso repo. 👍 

I tested the link provided in step 1, and it works for me! ([31s](https://cloudup.com/cnlz08IyOft), [53s](https://cloudup.com/cZef2n1bBvu))
<sup>Tested using Safari on iPhone 6S iOS 13.7 and iPhone 11 iOS 14.0.</sup>

@adelineyaw @carinapilar is it possible the user made a change that fixed the issue—is the problem still happening for you? Note that you may need to clear cache. If you still cannot get the video to play, may I ask you to comment to note the device types and iOS versions you tested with? 

Suggested steps if you need to troubleshoot further: 

* Make a note of the user's device and OS version.
* Ask how the video was embedded. (pasted a link? added via a block? shortcode? something else?)
* Try testing by creating a post with a Facebook video embedded the same way the user embedded theirs and check to see if it works. If it doesn't, make a note of your testing steps as well as your device and OS version.

For reference, I opened the link in step 1 in a desktop browser (Chrome 85.0.4183.83 on macOS 10.15.6) and viewed the page source and copied out the generated HTML for the video and am including it here in case it's helpful to later troubleshooting efforts:

`<div id="the-sticky-video" class="featured-area"><div class="featured-area-inner"><span class="tie-icon-cross video-close-btn" aria-hidden="true"></span><div class="tie-fluid-width-video-wrapper tie-ignore-fitvid"><iframe src="//www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2F236763870334042%2Fvideos%2F2775551909396966&show_text=0&width=780" width="780" height="439" scrolling="no" frameborder="0" allowTransparency="true" allowFullScreen="true"></iframe></div></div></div>`

**Comment by designsimply** [comment] 2020-10-22 21:46
I also decided to test the link in step 1 on Safari on my laptop for good measure and it did NOT work for me in Safari on desktop 🤔 so this issue may not be related to mobile specifically. Based on looking at the console and network calls in Safari developer tools while trying to play the video, I suspect a conflict with one of the plugins (maybe an ads plugin?) they're running and it would be worth testing to see if the same problem happens for another WordPress.com Business site that has the same type of video embedded the same way but that is not running the same plugins.

Video: [4m35s](https://cloudup.com/cYBXxtNC__v)
<sup>Tested with Safari 13.1.2 on macOS 10.15.6.</sup>

**Comment by carinapilar** [comment] 2020-10-23 10:48
> is it possible the user made a change that fixed the issue—is the problem still happening for you?

I would guess they changed something, yeah, it works for me now, on both Safari and Chrome on my phone. It also worked on desktop Safari. :)

**Comment by benchilcote** [comment] 2020-10-24 11:40
I also tested on iPhone Safari and Chrome and it is working.   On Chrome, it did require clearing my cache.  I conveyed to the user that it appears to be solved and asked them to let us know if they still see the issue.

**Comment by cathymcbride** [comment] 2020-10-28 16:47
Based on the above no repro comments, I'm going to close this issue.

**Closed by cathymcbride** 2020-10-28 16:47 UTC
Labels: [Type] Bug
