### ISSUE TITLE
Atomic: WooCommerce stock options behave inconsistently when WooCommerce Payments is active

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#60547] opened 2022-01-27 11:52 UTC
### Quick summary

When WooCommerce Payments is active, the stock options on Product Data > Inventory will show a `Stock Status` option even when the `Enable stock management at product level` option is checked. 
<img width="900" alt="Markup 2022-01-27 at 11 44 03" src="https://user-images.githubusercontent.com/14153300/151352573-78abf2b5-d0a3-4d08-8083-018912e96f45.png">

Changing the Stock Status and updating the product doesn't save the Stock Status change:

https://user-images.githubusercontent.com/14153300/151370750-a0c96db7-8bc7-4229-9016-c9b1cf83ea14.mp4

### Steps to reproduce

1. Install WooCommerce Payments on a Atomic site
2. Create or edit a simple product
3. Go to the Product Data > Inventory section
4. Check `Enable stock management at product level` 

### What you expected to happen

Checking `Enable stock management at product level` should automatically hide the `Stock Status` dropdown

### What actually happened

Checking `Enable stock management at product level` displays a `Stock Status` dropdown

### Context

Customer report

### Simple, Atomic or both?

Atomic

### Browser, operating system and other notes

Tested on Chrome on a Mac on the most recent versions

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Turning off `Enable stock management at product level`

**Comment by formosattic** [comment] 2022-03-01 09:12
This seems fixed, `Stock status` no longer shows.
Note that I only tested by activating WooCommerce Payments, but didn't configure it.

![image1](https://user-images.githubusercontent.com/15944096/156139404-79f3696f-6967-4ac1-8f1c-b9c6c32ef82b.png)

@liviopv: I'll close this for now. The report didn't have an interaction link for me to check the user's site, but if the problem is still there, please reopen.

**Closed as completed by formosattic** 2022-03-01 09:12 UTC
Labels: Bug, WooCommerce
