### ISSUE TITLE
Image Editor: Unable to edit image on private site

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#13625] opened 2017-05-03 21:05 UTC
When a site is set to private (wordpress.com/settings/SITEURL) it is not possible to edit images in the media library, as the Edit Image button does not appear when viewing image details.

This is a confusing experience for site owners as it is common to set a site to private when "getting set up" which is often a period of time when many images (which might need editing) are added to the site.

#### Steps to reproduce
1. Starting at URL: wordpress.com/settings/SITEURL set the site to private
2. Go to wordpress.com/media/SITEURL and select an image to edit, then click the Edit button
3. In the image details modal, the "Edit Image" button is not visible over the image
4. Setting the site to public makes this option visible as expected

#### What I expected
To be able to edit images regardless of site visibility

#manual-testing, #user-report

**Comment by jerrysarcastic** [comment] 2017-05-03 21:06
Related:  https://github.com/Automattic/wp-calypso/issues/7878

**Comment by jeremeylduvall** [comment] 2017-05-06 18:58
cc @retrofox - it looks like editing images is disabled on private sites per #11465. We're blocking image editing [here.](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/media-modal/detail/detail-item.jsx#L46) Is this a bug or expected occurrence for private sites? It looks like I can edit images in wp-admin when a site is set to private.

**Comment by retrofox** [comment] 2017-05-09 17:38
> it looks like editing images is disabled on private sites per #11465. We're blocking image editing here.

Right.

> Is this a bug or expected occurrence for private sites?

It's an expected occurrence for private sites. it's a CORS limitation which doesn't allow get the private resource.

> It looks like I can edit images in wp-admin when a site is set to private.

I'm not sure but if we can edit private images in wp-admin we should be able to do it in calypso.

**Comment by lancewillett** [comment] 2017-07-10 20:21
See also https://github.com/Automattic/wp-calypso/issues/15303

**Comment by ashercantrell** [comment] 2017-07-18 16:46
It looks like the Edit button appears in the Media Library and when users try to edit the images on a private site, they get an error message: “We are unable to edit this image.”

Should the edit buttons be hidden on a private site? The error is somewhat alarming for users.

**Comment by Lochlaer** [comment] 2017-07-29 19:48
As with @ashercantrell 's user, I have another user who tried to click on the Edit button on an image in this private site, and they get the message: 

![screen shot 2017-07-29 at 2 47 17 pm](https://user-images.githubusercontent.com/6569475/28747782-dc573464-746c-11e7-8dd7-105ac159b241.png)

> Should the edit buttons be hidden on a private site? The error is somewhat alarming for users.

I agree that this should either be hidden, or the message should be changed because it looks like an error message, not a notification that a feature is not available.

**Comment by adelineyaw** [comment] 2017-08-17 05:56
I had a user asking whether this bug had been fixed. Follow up email 7 August then 17 August.

**Comment by jeremeylduvall** [comment] 2017-08-31 21:56
As a temporary workaround, the edit button should now be hidden in Calypso for private sites. Hopefully this will make it a bit less confusing!

**Comment by KokkieH** [comment] 2017-09-14 18:51
Had a query in 876602-f from a user confused about the Edit button no longer being available.

**Comment by sarahgreenlee** [comment] 2017-09-27 13:23
I had a user come across this in MacOS desktop App. The edit button is still visible there for private sites. https://woothemes.zendesk.com/agent/tickets/699996

**Comment by rachelmcr** [comment] 2018-01-02 23:23
I'm closing this issue since it's the expected behavior due to a CORS limitation, which we don't currently have a solution for, and hiding the edit button for private sites seems to have resolved the confusion. We can reopen if we decide to work on this or get more user reports about it.

#bug-scrub

**Closed by rachelmcr** 2018-01-02 23:23 UTC
Labels: Media, [Type] Bug

**Comment by pablinos** [comment] 2018-04-06 15:08
It looks like #17347 that hides the edit button, also hides the edit button for videos, which can be edited on private sites. 

If there's no fix for the CORS issue currently, should we change the logic so that the edit button is available for videos or does that risk causing more confusion?

I see you mention that the CORS issue is related to photon @retrofox, is there any other way that the image could be retrieved?
