### ISSUE TITLE
Cover block: Incorrect rendering in the email template

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#66434] opened 2022-08-10 07:52 UTC
The Cover block is not rendered correctly in the email templates.

| Cover block with Image background | Cover block with Video background|
| ------------- | ------------- |
| ![Image](https://user-images.githubusercontent.com/25105483/183846385-77d5608a-2418-4081-918b-583afa7d1b61.png) | ![Image](https://user-images.githubusercontent.com/25105483/183846384-692af560-8525-4c7d-a910-8ff5ca5501c1.png)  |

## How to reproduce the issue

1. Subscribe to the test site.
2. Create and publish a post with the Cover block in it - you can add an image or a video to the background.
3. Wait for the _New Post_ email to arrive and review it.

---

## Related issues / reports:

- 527-gh-Automattic/dotcom-manage
- 209-gh-Automattic/dotcom-manage
- p1660062515655929-slack-C02TCEHP3HA

**Comment by ivan-ottinger** [comment] 2022-10-07 07:18
I noticed the issue with one of the [latest post](https://wordpress.com/blog/2022/10/06/promote-your-posts-on-wordpress-com/) - where the Cover block includes a video.

**Comment by julsyd** [comment] 2023-04-25 14:09
The Cover Block also does not retain styling from the post in subscription emails.

Example from the post (no overlay):
<img width="1210" alt="Screenshot 2023-04-25 at 10 07 42" src="https://user-images.githubusercontent.com/29981758/234303031-d1d4db78-3378-41d4-a9e9-a23791286266.png">

Example from the subscription email (dark overlay):
<img width="429" alt="Screenshot 2023-04-25 at 10 07 52" src="https://user-images.githubusercontent.com/29981758/234303119-2d624af7-1e8c-4f72-873c-b692f65e6c07.png">

Reported by a user in 6232303-zen, and reproduced by myself on a test site.

**Comment by ukAndrzej** [comment] 2023-04-26 08:40
julsyd raised this as a bug following my support request to Jetpack on 24 April 2022. I consider this as urgent because when cover blocks fail to render correctly in subscription emails, it makes blogs look unprofessional.

**Comment by TimBroddin** [comment] 2023-11-08 13:07
@JuanLucha will review

**Comment by pehaa** [comment] 2023-11-28 13:14
Reported here 7336427-zd-a8c

**Comment by TimBroddin** [comment] 2024-01-23 08:39
We have a patch available here: D89960-code 

However, the cover block is a complex beast, as it allows users to nest arbitrary content and can be customized in an almost infinite ways (video backgrounds, gradients, ...).

Therefore, the patch can only account for some edge cases, and there are currently too many edge cases to merge this patch safely without causing an influx of support tickets.

This diff contains a list of edge cases, but there are probably more. Accounting for all of them would require a bigger project, something we don't have the bandwidth for right now. I'm closing this ticket, but anyone who wants to continue on this is free to reopen.

**Closed as not planned by TimBroddin** 2024-01-23 08:39 UTC
Labels: Maintenance, Email, Customer report [LEGACY], Email Blocks
