### ISSUE TITLE
Atomic and Gutenberg (fullscreen): Scroll not working properly

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#31289] opened 2019-03-07 20:13 UTC
#### Steps to reproduce
1. Setup an AT site
2. Activate Gutenberg and create a long post or page (using Calypso interface)
3. Try to scroll down when clicking on the content, you'll notice it doesn't work (You'll need to try on Chrome or Firefox, it works normally with Safari)

#### What I expected
The scroll to work normally

#### What happened instead
It won't let me scroll unless I click on the sidebar

#### Browser / OS version
Chrome Version 72.0.3626.109 (Official Build) (64-bit)
macOS Mojave 10.14.2 (18C54

#### Screenshot / Video
![53200397-6cc7cc80-35ef-11e9-8bf8-4062e529db62](https://user-images.githubusercontent.com/3696121/53986016-0eb8e000-40eb-11e9-8d27-83d1fde4761a.gif)

**Workaround**

Ask the user to edit the posts/pages using the WP Admin Dashboard and disabling the "Fullscreen" mode:

![screen shot on 2019-03-07 at 15 05 21](https://user-images.githubusercontent.com/3696121/53985739-73276f80-40ea-11e9-8e9f-60cf4809bce8.png)

You won't see the option to disable fullscreen if you access the editor when using Calypso.

#### Context / Source

Initially reported here: 761-gh-atomic

#manual-testing
#user-report

p1551905121469000-Slack-livechat

**Comment by scosgro** [comment] 2019-03-07 21:30
Just got another report of this, and could replicate. #9797619-hc

User is using Chrome, scroll is broken, and there is no option to turn Full Screen Mode off or on.

**Comment by scosgro** [comment] 2019-03-09 21:02
Another report at #1865630-zd

**Comment by susanjanec** [comment] 2019-03-13 15:00
> Another report at #1865630-zd

User replied back:

> My pages get cut off and I can’t use up/down arrows or scroll to see the rest of the articles. This has been going on since Friday 3/8. I don’t have an option when I click on the 3 dots to turn off full screen mode. I have used both explorer and chrome. The only thing that works is using an old version of IE. I can’t write new articles for the same reason.

When I logged into their site using Chrome, I am not able to use the up/down arrows or scroll, and it appears that the Yoast plugin area is overlaying the post.

However, when I logged into their site using Firefox, I am able to scroll to see their entire post.

Perhaps this is an issue that is happening within Chrome and Explorer?

Will suggest to the user to use Firefox to see if they're able to view/edit the post and able to scroll down/up the post.

**Comment by retrofox** [comment] 2019-03-21 21:12
Hi @AtrumGeost, if I'm not wrong, the customer should no be able to edit a post from Calypso for Atomic sites. It's part of calypsoify process. It means that the links either to add or edit a post always will redirect to wp-admin. I've tested with one of my Atomic sites:

![image](https://user-images.githubusercontent.com/77539/54785060-0640c900-4c04-11e9-8ddd-9f34a61a01a1.png)

![image](https://user-images.githubusercontent.com/77539/54785129-2ec8c300-4c04-11e9-936c-6d6626be9766.png)

Could you confirm please if it adds/edits a/the post in Calypso?

**Comment by AtrumGeost** [comment] 2019-03-21 22:01
Hi @retrofox !

Indeed, when clicking on the post/page through calypso, the user would go the the calypsofied version of the editor.

However, when I first reported this issue the scroll wouldn't work. Now that I tested again on 2 AT sites (v1 & v2) the scroll is working normally.

_I used Chrome Version 73.0.3683.86 (Official Build) (64-bit) in my latest test._

@susanjanec or @scosgro, are you still able to reproduce this issue on your end?

**Comment by retrofox** [comment] 2019-03-22 11:40
Hi @AtrumGeost! 👋 

> However, when I first reported this issue the scroll wouldn't work. Now that I tested again on 2 AT sites (v1 & v2) the scroll is working normally.

I would argue that it's a matter of time. Propagate or populate/update the data in calypso takes time. When the Simple site is transferred, we should refresh these links on the fly avoiding to bring to the customer to undesired places: "Editing a new post into calypso for an Atomic site", for instance.

Let's try to research and reproduce this issue again and again, and maybe instead of improve the data propagation (since it could get tricky) what we could do is working on the links which must to updated pointing to the wp-admin (calypsoify scope). It gets more sense since, in the end, we don't mind too much what's the status of the data. What we want to do is get out the user from Calypso as soon as possible.

**Comment by scosgro** [comment] 2019-03-22 18:01
@AtrumGeost @retrofox 

Tested in SSP on #1865630-zd and it was still broken (Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)).
Tested in SSP on #9797619-hc and it was still broken as well (Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)).

Both tests, SSP'd in, went to Blog Posts in Calypso, selected a post, and tried to scroll. Scroll still didn't work.

**Comment by susanjanec** [comment] 2019-03-24 14:27
Hi @retrofox - User from 1865630-zen replied back and said that Firefox did the trick.

They were using Google Chrome 73.0.3683.75 (Official build) (64-bit) and Microsoft Edge 42.17134.1.0

When viewing their site SSO'd in Google Chrome Version 73.0.3683.86 (Official Build) (64-bit) I am able to scroll down the post with no issues.

**Comment by retrofox** [comment] 2019-03-25 17:42
> When viewing their site SSO'd in Google Chrome Version 73.0.3683.86 (Official Build) (64-bit) I am able to scroll down the post with no issues.

could you confirm that you were testing in the wp-admin?

**Comment by susanjanec** [comment] 2019-03-25 18:48
> could you confirm that you were testing in the wp-admin?

Yes, I was testing via wp-admin

**Comment by sdixon194** [comment] 2019-04-11 21:44
Another case [here](https://mc.a8c.com/support-stats/happychat/transcript.php?id=12023986). 

The disable fullscreen option isn't available anymore. User was able to scroll by placing their mouse in the header or settings area, like this: https://cld.wthms.co/DoGkME

**Comment by mmtr** [comment] 2019-05-11 04:58
Fixed by https://github.com/Automattic/jetpack/pull/12279

**Closed by mmtr** 2019-05-11 04:58 UTC
Labels: [Goal] Gutenberg, [Type] Bug
