### ISSUE TITLE
Help: Site picker search is out of place

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#51185] opened 2021-03-18 15:01 UTC
I noticed some weirdness with the site picker search bar on the Help contact form while working on #51184: 
<img width="341" alt="Screen Shot 2021-03-18 at 10 53 41 AM" src="https://user-images.githubusercontent.com/2124984/111647271-bab45c00-87d8-11eb-9494-a2059d222fe7.png">

There appears to be a selector positioning it 67px from the top. Needs more investigation.

_Originally posted by @sixhours in https://github.com/Automattic/wp-calypso/issues/51184#issuecomment-801996715_

**Comment by obenland** [comment] 2021-03-18 17:06
Duplicate of #40195.

**Closed as completed by obenland** 2021-03-18 17:06 UTC
Labels: Bug
