### ISSUE TITLE
Karuna theme: when no menu is set to display in 'header' location, all pages on site show.

### ISSUE THREAD

**Issue by sajmes** [Automattic/wp-calypso#67878] opened 2022-09-15 21:44 UTC
### Quick summary

When no menu is set to display in the header location from My Site → Appearance → Customize → Menus, we'd expect no menu content to show in that location.

Instead, all the published pages on a site show in that location.

![Markup on 2022-09-15 at 14:36:06](https://user-images.githubusercontent.com/76757079/190513106-ece2f868-5f64-4c0b-9d6f-b01bb95bc8f0.png)

When a menu is set to show in this location, it does display properly.

![Markup on 2022-09-15 at 14:37:36](https://user-images.githubusercontent.com/76757079/190513413-f85bf0e0-5d85-4996-9b8f-ec78365f1498.png)

The social menu location behaves as expected.

### Steps to reproduce

1. Switch to Karuna theme.
2. From My Site → Appearance → Customize → Menus → View all Locations, deselect any existing menus for the header location. 

### What you expected to happen

The menu location would appear empty.

### What actually happened

When no menu is set in the header location, all published pages on the site show in that location instead. 

### Context

36911782-hc

I could reproduce on two test sites.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Karuna

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Assign a menu with no items to the header location.

**Comment by cuemarie** [comment] 2022-09-21 00:57
📌 SCRUBBING : RESULT 
- Tested on Simple: Replicated
- Tested on AT: Replicated
- Tested on Self-hosted: Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- According to the theme info page https://wordpress.com/theme/karuna/ , this is actually the intended behavior: 

> Main Menu
>>This theme has one main menu area called “Header.” If you don’t assign a [custom menu](http://header/) to that area, your site’s default page menu is displayed instead.

*Example*

📌 ACTIONS
- Closed as behavior is intended

📌 Message to Author
- Thanks for the report @sajmes ! I'm closing this issue as the behavior reported is intended, according to the themes info page.

**Closed as completed by cuemarie** 2022-09-21 00:57 UTC
Labels: Bug, [Pri] Low, [Platform] Simple, [Platform] Atomic
