### ISSUE TITLE
Marketplace: No visual indicator for selected category for the category select on the mobile view 

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#63839] opened 2022-05-19 23:20 UTC
![Screen Capture on 2022-05-19 at 18-22-30](https://user-images.githubusercontent.com/1035546/169419849-93427aae-bf58-43f9-bc0a-f09fedae27a9.gif)

On the swipable menu when we are in a category list if the selected category is on the middle of the list the user can't see a visual indicator of that category being selected until its scrolled there.

**Comment by lsl** [comment] 2022-05-20 04:59
Probably duplicate of either https://github.com/Automattic/wp-calypso/issues/63791 or https://github.com/Automattic/wp-calypso/issues/63788

Fix in https://github.com/Automattic/wp-calypso/pull/63842 + better fix including title in https://github.com/Automattic/wp-calypso/pull/63846

**Closed as completed** 2022-05-24 17:21 UTC
Labels: [Status] Needs Design, [Status] Design Input Requested
