### ISSUE TITLE
NUX: Email Validation: Alert users trying to publish pages or posts

### ISSUE THREAD

**Issue by melchoyce** [Automattic/wp-calypso#3169] opened 2016-02-08 21:02 UTC
After running a couple users tests, I noticed that not only did users ignore the email validation prompt, but they were also completely stumped when they wrote and published posts and pages, but those pages did not show up on their website. Some of them were able to find the posts/pages in drafts, but didn't make the connection between publishing and email validation. This is further compounded by the fact that we do let them click the publish button, then give them a "post/page published" confirmation, *and* make them look published in the editor. If users have not validated their email addresses, we should think about giving them some sort of notice, alert, or tooltip when they try to publish.

**Comment by melchoyce** [comment] 2016-02-08 21:19
Better yet: eliminate the need for email validation. ;)

**Comment by codebykat** [comment] 2016-02-10 03:28
Thanks @melchoyce ! Dupe of https://github.com/Automattic/wp-calypso/issues/2650

**Closed by codebykat** 2016-02-10 03:28 UTC
Labels: Editor, NUX, Signup, [Type] Enhancement
