### ISSUE TITLE
WoA (Atomic): Recent update to Gutenberg (10.2.0) caused "Auto Draft" text on title appearing on every new post

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#51211] opened 2021-03-19 02:07 UTC
On March 18, 2021, we had Gutenberg update to 10.2.0 on Simple sites and Atomic sites. Then, a user reported that they keep seeing "Auto Draft" on the title area whenever they want to create new post. They informed that the issue happened recently and no changes happened on the website.

I checked Blog RC and I can confirm the latest update was on Gutenberg, hence this GH issue.

I checked the website using Troubleshooting mode (all plugins and custom themes inactive) and the issue persists. I able to replicate it on my test site.

### Steps to reproduce the behavior

1. Open an AT site.
2. Go to Posts area. Click 'Add New'
3. On the title area, you should see 'Auto Draft' text on it

#### What I expected to happen
To have the title area empty with placeholder text "Untitled" 

#### What actually happened
The title area has "Auto Draft" text on it.

I also asked about it here:
p9o2xV-1jZ-p2#comment-4301

**Comment by zdenys** [comment] 2021-03-19 12:09
Encountered during a Quick Start session. Confusing. 3835889-zd-woothemes

**Comment by jeherve** [comment] 2021-03-19 13:44
cc @blackjackkent Do you think this may be caused by 636-gh-wpcomsh? Do you think you could take a look?

**Comment by ajaykj** [comment] 2021-03-19 13:57
Encountered in 26429320-hc

**Comment by blackjackkent** [comment] 2021-03-19 14:31
> cc @blackjackkent Do you think this may be caused by 636-gh-wpcomsh? Do you think you could take a look?

I'm not sure but that change is definitely having side effects so we're going to be reverting that change regardless. Will follow up to see if it undoes this bug.

**Comment by thabotswana** [comment] 2021-03-19 14:44
Another report here: 28517358-hc

**Comment by kwight** [comment] 2021-03-19 15:16
I believe this is fixed now with the revert of 636-gh-Automattic/wpcomsh/

> What I expected to happen: To have the title area empty with placeholder text "Untitled"

I get "Add title" – is that an issue?

Closing, but we can re-open if there are ongoing concerns.

**Closed as completed by kwight** 2021-03-19 15:16 UTC
Labels: Bug

**Comment by retnonindya** [comment] 2021-03-22 13:49
Thank you, @kwight! And yep, "Add Title" is expected 😄 Thanks again!
