### ISSUE TITLE
Twenty Twenty themes are showing up as upgrade required

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/wp-calypso#95170] opened 2024-10-05 07:29 UTC
### Quick summary

I'm sorry if this appears to be a duplicate of another issue. I’ve found these two issues that seem related: https://github.com/Automattic/wp-calypso/issues/94310 and https://github.com/Automattic/wp-calypso/issues/94616.

When switching to any themes from Twenty Twenty One or earlier via the search page, the upgrade prompt appears. This doesn’t happen when switching directly through the theme’s link or by removing `?tab_filter=all` from the URL.

https://github.com/user-attachments/assets/2a193654-24b1-4eca-b6cd-11d3e7b10f20

### Steps to reproduce

1. Go to Appearance → Themes 
2. Search for any themes from `Twenty Twenty One` or below 
3. Check URL has `?tab_filter=all` in the end
4. Click the button to activate the theme
5. See the upgrade prompt

### What you expected to happen

The theme will activate without any prompt to upgrade. 

### What actually happened

It prompts to upgrade to a Business plan. 

### Impact

One

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Activate the theme from the theme's direct link or remove `?tab_filter=all` from the URL. 

### Platform (Simple and/or Atomic)

Simple

**Comment by Robertght** [comment] 2024-12-03 05:11
@dsas The issue is no longer happening for me. 

I'm closing this as it's no longer relevant.

**Closed as completed by Robertght** 2024-12-03 05:11 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Low, Triaged, [Feature] Theme Showcase, [Platform] Simple, [Product] WordPress.com
