### ISSUE TITLE
Map Block: Unable to add MapBox access token

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#68000] opened 2022-09-20 03:14 UTC
### Quick summary

When editing the settings for the Map Block (only on DotCom) it isn't possible to enter/paste any value into the Mapbox Access Token field.

### Steps to reproduce

1. Edit a page or post on the site and insert a Map block.
2. Try and add a MapBox access token in the Sidebar settings for the block.

### What you expected to happen

To be able to add a value to the text field and/or use the Update/Remove buttons

### What actually happened

The text field can be selected - but no value can be pasted or added. Both the Update and Remove buttons remain disabled/greyed.

### Context

Customer Report - #5569889-zen

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jordesign** [comment] 2022-09-20 03:18
I've not been able to recreate this in Jurassic Ninja - so although this is a Jetpack block it seems to only be impacted on DotCom.

**Comment by jamiepalatnik** [comment] 2022-09-23 03:02
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated
- Tested on Self-hosted - Could Not Replicate
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can replicate this, but it looks like there is an existing issue with other user reports: https://github.com/Automattic/wp-calypso/issues/53248
- This seems to be related as well: https://github.com/Automattic/jetpack/issues/20593

📌 ACTIONS
- Closed as duplicate of [#53248](https://github.com/Automattic/wp-calypso/issues/53248)

**Closed as completed by jamiepalatnik** 2022-09-23 03:02 UTC
Labels: Bug, [Pri] Normal
