### ISSUE TITLE
Gutenberg: "i.has is not a function" Error

### ISSUE THREAD

**Issue by torres126** [Automattic/wp-calypso#28893] opened 2018-11-27 19:54 UTC
#### Steps to reproduce
1. Starting at URL: https://horizon.wordpress.com/gutenberg/post
2. Use a block which involves uploading an image (eg. Image/Cover block) 
3. Click the "Upload" button on the block
4. Select an image from your device to upload and attempt to upload it 
5. See error 

#### What I expected

I expected the image to upload without any issues at all, and to be automatically used in the block. This used to happen before, but this issue occasionally happened, and now it's been happening again all day. 

#### What happened instead

An error which says "i.has is not a function" appears and no image is uploaded. 

#### Browser / OS version

Using a Mac OS X 10.6.8 with Chrome 49.0.2623.112 

#### Screenshot / Video
![gfdsdfsgdsfgfdsg](https://user-images.githubusercontent.com/43215253/49107549-ed3f9100-f27d-11e8-8a33-462aa10a9ad2.png)

#### Context / Source

I found this bug whilst trying to create blog posts myself, it occurred several times and is very frustrating. It is worth noting that it does not seem to be specific to the image itself, I tried uploading all kinds of images, transparent, large and small ones, and all came up with this error. 

A workaround for now is, instead of clicking "Upload" on the block, click "Media Library" and then "Add New" in the top left. Uploading the image the way seems to work fine.

**Comment by mmtr** [comment] 2018-12-26 10:47
Thanks for reporting this issue @torres126! However, I'm not able to reproduce it, since I'm able to upload any image with no problems.

Can you double check if the issue is still present on your side? If so, do you apply the same steps you see on [this video](https://cloudup.com/ctm-DZv2AT5)? 

Note that we changed the Gutenberg editor URL from `/gutenberg` to `/block-editor` and it is currenyl available in production, so you can do the test on https://wordpress.com/block-editor

**Comment by torres126** [comment] 2018-12-26 16:08
Yep, I can still recreate this at https://wordpress.com/block-editor using the same steps, which were the ones shown in the video. 

![gfdsgfdsgfsd](https://user-images.githubusercontent.com/43215253/50450838-4f94bb80-0928-11e9-947f-1ce9c4507826.png)

Just to note though, using the Image Block and following the same steps works absolutely fine at https://wordpress.org/gutenberg and provides no error.

**Comment by mmtr** [comment] 2018-12-31 10:05
Interesting. I cannot get that error, so I wonder if this is something related to any special condition on your environment which is triggering the error.

Can you try to reproduce the error under different conditions? For example:
- With a different browser.
- With a different site.
- With a different account.

This will confirm us if the issue is something generic and reproducible under specific conditions.

**Comment by torres126** [comment] 2018-12-31 11:15
Uploading to any site causes this issue, I tried a few! I created another account and tested again, but to no success, and the error still appeared.

If I use my Samsung Galaxy Tab S2 to try and upload an image though, which is running Chrome 70, I don't run into any issues and the image uploads just fine.

**Comment by mmtr** [comment] 2018-12-31 16:02
That's weird! I'm starting to think that the issue could be caused by your browser. Do you get the same error if you try after clearing your browser cache, or from a private / incognito session or with the browser extensions disabled?

**Comment by torres126** [comment] 2018-12-31 18:21
My only browser extensions are a VPN which I had disabled and a screenshots tool, and since they were disabled, I don't think there's an effect there! Unfortunately, clearing cache & cookies and using an incognito tab still resulted in the issue occurring. If this is due to my browser, part of me wonders if there's even much point in investigating a fix further, since Calypso technically doesn't support it, and I'm the only one who seems to be experiencing it so far. The ability to upload images is hugely important, but there's an easy workaround of just using the Media Library. It'd probably help if the error message was more clear in suggesting that though, since I didn't realise there was a workaround at first.

**Comment by mmtr** [comment] 2019-01-01 15:14
Oh, I didn't notice you're using Chrome 49! Thanks for pointing that out.

Indeed, I was able to reproduce the issue in that version, but as you noted, since we don't support it in Calypso (it is almost 3 years old), I'm closing this.

Although you can use the Media Library as workaround, I'd suggest you to update your browser. There could be more issues caused by that 🙂.

Thank you very much for taking the time on reporting this and contributing to make Calypso better. Much appreciated! 💯

**Closed by mmtr** 2019-01-01 15:14 UTC
Labels: [Goal] Gutenberg, [Pri] Low, [Type] Bug

**Comment by torres126** [comment] 2019-01-01 17:00
Sadly it's the highest version my device supports, but no worries, that's completely understandable. Thanks! :)
