### ISSUE TITLE
Reader: reblogs in the Reader main stream are missing a space after the the colon

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#711] opened 2015-11-25 01:28 UTC
Currently, text appears like this, missing a space after ":"

> Originally posted on blogname:Start of excerpt

And it should look like this, with a ":" then a space before the excerpt begins:

> Originally posted on blogname: Start of excerpt

![screen shot 2015-07-22 at wed jul 22 4 03 11 pm](https://cloud.githubusercontent.com/assets/1119271/8835992/f48074f0-308b-11e5-93b5-489797d3db3a.png)
<sup>Seen at https://wordpress.com/ using Chrome 43.0.2357.134 on Mac OS X 10.10.4</sup>

Reported at https://en.blog.wordpress.com/2015/07/13/reader-refresh/ (2260414-t)

From shaunandrews: 

<blockquote>Strange. That doesn't look like a reblog should, which is like this:</blockquote>

![screen shot 2015-07-27 at 12 42 02 pm](https://cloud.githubusercontent.com/assets/191598/8911859/f6b5abe4-345c-11e5-8d6e-d5bc9e8cac43.png)

From blowery:

<blockquote>We're only showing the fancy reblog card when the post passed the ONE_LINER rules, so no images and less than 200 words.</blockquote>

**Comment by blowery** [comment] 2016-01-20 15:34
Fixed with r129999-wpcom for new reblogs. The problem is that the excerpt is stripped of `<br>` and other tags, and there was no space after the `:`. Inserted a space, all should be well now.

**Closed by blowery** 2016-01-20 15:34 UTC
Labels: Reader, [Type] Bug
