### ISSUE TITLE
Tiled Galleries: improve reordering experience

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#32614] opened 2019-04-26 15:30 UTC
When you add a Tiled Gallery to a page and then wants to edit the order of the images, it loads a simple Calypso "Add Media" modal, where you need to uncheck all images and select then again in the order you want to have on the gallery.

#### What I expected

Reordering images should be as fluent and user-friendly as it is in WP Admin, where you can simply drag and drop images to reorder them.

Video: https://cld.wthms.co/A081A1

#### What happened instead

For big galleries, the process becomes much more time consuming and prone to error.

Video: https://cld.wthms.co/aIXZgO

#### Context / Source
#perspective #reallife #painpoint #user-report 

A user whose front page is simply a big gallery (they are an illustrator) needs to completely reorder the gallery every time they want to add a new illustration to show that new artwork at the top of the page.

#9079583-hc

**Comment by simison** [comment] 2019-04-26 17:52
Thanks for the issue!

I'll close this as a duplicate of https://github.com/Automattic/jetpack/issues/11874

**Closed by simison** 2019-04-26 17:52 UTC
Labels: Jetpack, Tiled Galleries
