### ISSUE TITLE
HEVER theme doesn't respect block styles for links

### ISSUE THREAD

**Issue by DavidSaladu** [Automattic/wp-calypso#90725] opened 2024-05-15 03:45 UTC
### Quick summary

The user has a very similar primary and background color which makes links almost invisible. However trying to change the styles on the block doesn't seem to make any change.

### Steps to reproduce

1. Set background and primary color (1st and 3rd) equal or similar (the user had #ffffff and #f9f9f9)
2. While using the Hever theme create a new page with a paragraph and a link
3. While the editor appears correctly, on the frontend the the link appears with the primary color. (text seems to appear correctly, maybe using the foreground color from what it seems)
4. Try to change the style for that block to different colors (either on text or link or even hoover)

### What you expected to happen

After changing the block styles to different colors that block should reproduce those changes.

### What actually happened

The block stays the same and its barely seen.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Sonoma 14.3.1 (23D60)
Chrome Version 124.0.6367.119 (Official Build) (arm64)
Theme hever

**Comment by liviopv** [comment] 2024-05-16 10:23
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate


📌 FINDINGS/SCREENSHOTS/VIDEO

- Set the theme colors as indicated in the instructions
- Created a page with a link
- Applied custom link and hover colors to the link
- Frontend is consistent with backend, no color variation

https://github.com/Automattic/wp-calypso/assets/14153300/d203742c-3a03-4c86-8609-c17a4a4aba99

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@DavidSaladu there might be some other style applied at the block level, possibly Highlight (more specific). Since no interaction was shared, I can't investigate on the user's site.

Also, if an issue is specific to a particular theme, the correct repository is https://github.com/Automattic/themes

**Closed as completed by liviopv** 2024-05-16 10:23 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Low, [Closed] Not Reproducible, Customer report [LEGACY], [Platform] Simple, [Status] Priority Review Triggered, [Product] WordPress.com
