### ISSUE TITLE
Add Link on Mobile Web: flickering, blinking

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#45454] opened 2020-09-08 08:54 UTC
**Update:** already reported:

* https://github.com/WordPress/gutenberg/issues/24592
* https://github.com/WordPress/gutenberg/issues/24532
* https://github.com/WordPress/gutenberg/issues/24482

<hr> 

**Editor config:**
Gutenberg: 8.7.1
CoBlocks: 2.2.2
wpcom-FSE: 238875985

**How to reproduce:**

1. Add a few paragraph of text
2. Try adding a link

**What happens?** The add link modal will flicker, jump around. Sometimes, it takes a few tries to get the flicker, but it eventually gets triggered.

| iPhone with Safari  | Android (S7, Pixel) with Firefox, Chrome |
| ------------- | ------------- |
| ![addlinkflicker_iphone_safari](https://user-images.githubusercontent.com/15944096/92453249-9b1cf500-f1f1-11ea-9144-2307d4c5efc3.gif) |![addlinkflicker_pixel_chrome](https://user-images.githubusercontent.com/15944096/92453303-ae2fc500-f1f1-11ea-9e6c-ebc1126eb4e9.gif) |

Here's also the console log (Android, Firefox):
![img](https://user-images.githubusercontent.com/15944096/92453588-09fa4e00-f1f2-11ea-9f3a-8f08ef61d22f.png)

Internal reference: p1599377403012300-slack-gutenberg-on-dotcom

**Comment by tjcafferkey** [comment] 2020-10-23 12:36
I've been looking into this issue for the best part of my day and here is what I think:

* The cause is because the content is cycling between having a `max-width` and not having a `max-width` [set by the `refresh()` function](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/popover/index.js#L382-L386) inside the `useLayoutEffect()` hook.
* Because of this, the content width keeps changing [and getting recalculated](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/popover/utils.js#L55-L59) and this causes the `max-width` to either be changed again or removed (and set to `auto`). And then goes through this cycle again, and again...
* The value getting returned to be set as the `max-width` is [set here](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/popover/utils.js#L113).

It feels like perhaps there is a flaw in the logic when conditionally calculating values we haven't considered this edge case. At this point I am unable to pin this down to one particular point in the logic.

I have tried various attempts at fixes but by fixing one scenario I cause the same bug in another location, elsewhere in the text.

**Comment by david-szabo97** [comment] 2020-12-16 10:48
Fixed by 27648-gh-WordPress/gutenberg

Keep issue open till it's released on WPcom

**Comment by ciampo** [comment] 2021-04-14 16:41
Hey @david-szabo97 , can this issue be closed? (and [this card](https://github.com/orgs/Automattic/projects/161#card-50790608) archived?

**Comment by david-szabo97** [comment] 2021-04-16 13:09
Yes, just closed it! Thanks for checking in

**Closed** 2021-04-16 13:09 UTC
Labels: Editor, Mobile Web, [Pri] Low, [Type] Bug
