### ISSUE TITLE
Shortcode Forms - Dropdown Menus are Transparent

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#76616] opened 2023-05-05 02:36 UTC
### Quick summary

When creating a Shortcode Form, the dropdown menu background is transparent instead of opaque.

This is evidently a new issue per a customer report, where an existing shortcode form with a dropdown menu became transparent suddenly.

Workaround is to use a Forms Block, but this is inconvenient for users who have been using an existing Shortcode Form.

### Steps to reproduce

1. Create a Shortcode Form with a dropdown menu. For example:

```
<!-- wp:shortcode -->
[contact-form]
[contact-field label="Name" type="name" required="true" /]
[contact-field label="Email" type="email" placeholder="Your Email Address" required="true" /]
[contact-field label="Website" type="url" /]
[contact-field type="select" options="Yes,No"]
[contact-field label="Comment" type="textarea" required="true" /]
[/contact-form]
<strong>[contact-field label='Comments' type='textarea'/][/contact-form]</strong>
<!-- /wp:shortcode -->
```

### What you expected to happen

The dropdown menu background should be opaque

### What actually happened

The dropdown menu background is transparent.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Customer report: 32168339-hc

**Comment by karenroldan** [comment] 2023-05-08 09:54
📌 REPRODUCTION RESULTS

- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

Simple site, Bitácora theme
![simple](https://user-images.githubusercontent.com/67279475/236793487-1fb01d5d-8c6a-42d5-9eae-598ed0b1035f.png)

Atomic site, Appleton theme

![atomic](https://user-images.githubusercontent.com/67279475/236793534-77c38cad-47cc-4a00-a9c7-234659d3d77d.png)

📌 ACTIONS

- Closed as duplicate of issue Automattic/jetpack#41242

**Closed as completed by karenroldan** 2023-05-08 09:54 UTC
Labels: Bug, [Pri] Normal, Shortcodes, Triaged, [Platform] Simple, [Platform] Atomic
