### ISSUE TITLE
Layout Grid Block: Cover block height / overflow issue in some browsers

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#47247] opened 2020-11-09 19:22 UTC
If you add Cover blocks within the columns of a Layout grid the Cover block height is incorrect in some browsers, Firefox specifically. This results in the content on top of the Cover block being cut off.

#### Steps to reproduce

1. Starting at URL: Simple or AT site
2. Add a Layout Grid block to the page
3. Add Cover blocks in each column, make one larger with the content (no size set on the Cover blocks)
4. View the published page in Chrome & Firefox

Editor setup:

![https://d.pr/i/llMnTL](https://d.pr/i/llMnTL+)

#### What I expected

Chrome extends the height of all Cover blocks to the height based on the content in the tallest Cover block:

![https://d.pr/i/CrzdDL](https://d.pr/i/CrzdDL+)

#### What happened instead

Firefox doesn't change the height, so the text overflows incorrectly:

![https://d.pr/i/eLdBE9](https://d.pr/i/eLdBE9+)

I was originally troubleshooting this in mobile to see why the heights looked incorrect and then realized this difference on desktop Chrome / Firefox.

It appears the issue is related to this:

```
.wp-block-jetpack-layout-grid .wp-block-cover {
    max-height: 0;
}
```

On AT this is located at:
```
/wp-content/plugins/layout-grid/blocks/front.css
```

This appears to resolve that:

```
body .wp-block-jetpack-layout-grid .wp-block-cover {
max-height: unset;
}
```

A related question is if the height of the Cover blocks are all _supposed_ to match each other (like they do in Chrome). They don't match the height in the editor (first image above), so I'm not sure if this is intentional.

If they are not supposed to match each other `height: auto;` can be added:

```
body .wp-block-jetpack-layout-grid .wp-block-cover {
max-height: unset;
height: auto;
}
```

![https://d.pr/i/7k9R33](https://d.pr/i/7k9R33+)

#### Browser / OS version
macOS Catalina 10.15.5 (19F101)
Firefox: 81.0.1 (64-bit)

#### Context / Source

25354840-hc

**Comment by jeyip** [comment] 2020-11-10 23:22
I tested this in Chrome, Edge, IE11, Safari, and Firefox. I only see this issue in Firefox.

**Note:**
When recreating the problem and adding text content to the cover block, be sure to set the font color to something that contrasts the background color of the page. I had mine set to the default white font color, which was hard to spot against the white background of the web page.

**Comment by marcuswisecaesar** [comment] 2020-11-25 15:20
Reported in HC-22523861

The user’s homepage is setup in Gutenberg, on the Arcane theme.  With the Layout Grid plugin active cover images expand to their content size and footer content is moved into the main content area: 

![screenshot](https://d.pr/i/yxfmer+)
[Direct Link](https://d.pr/i/yxfmer)

**Comment by serabi** [comment] 2020-12-05 20:06
Reported again in 26135151-HC

With the Layout Grid plugin activated, the user's home page elements overlap on Chrome, directly below their cover block: 

<img width="1886" alt="Screen Shot 2020-12-05 at 3 06 22 PM" src="https://user-images.githubusercontent.com/30205248/101262281-727e9b80-370b-11eb-8006-822bca0da80e.png">

User is running the Stratford theme.

**Comment by isocialtish** [comment] 2020-12-15 22:11
Reported in 26367330-HC

In Chrome, the user's Footer links overlap on a section of the page
<img width="1214" alt="Screen Shot 2020-12-15 at 12 03 06" src="https://user-images.githubusercontent.com/6664819/102278888-64850380-3edf-11eb-9816-27ddbf4ad67e.png">

User is using the Alves theme

As a workaround, I copied each block and pasted it above the Layout Grid block, recreating their same layout without the Layout Grid block and it now works.

**Comment by gwensmithx** [comment] 2020-12-17 01:08
This seems to be related - I have a report of overlapping of elements on a customer's homepage and it appears to be related to the Cover Blocks.

#3580743-zd
#25758480-hc

I was able to fix this up by taking everything out of the Layout Grid and using Columns instead.

Screenshot:

<img width="1524" alt="Screen Shot 2020-12-16 at 6 02 20 PM" src="https://user-images.githubusercontent.com/5779512/102424998-a38f8380-3fc9-11eb-99a3-6fea31d45de9.png">

**Comment by gwensmithx** [comment] 2020-12-17 20:52
We might need to change the priority of this. It seems to be coming up more and more and it takes time to fix these pages.

#25904416-hc

Same issue as my previous post - there's Cover blocks in the Layout Grid. Simple site.

<img width="991" alt="Screen Shot 2020-12-17 at 1 51 04 PM" src="https://user-images.githubusercontent.com/5779512/102542444-0b4bda00-406f-11eb-9847-bff133399ec9.png">

**Comment by pauloeaquino** [comment] 2020-12-22 03:26
Related issue in 26491073-hc

![screenshot](https://d.pr/i/KVdKS0+)

Proposed CSS solution (from OP) resolved this for now.

**Comment by mikeicode** [comment] 2021-02-09 15:30
Another, resolved with the CSS I posted above. 3725297-zd-woothemes

**Comment by synora** [comment] 2021-02-15 18:26
@jeyip There have been several more reports of this issue. It is possible to reconsider the priority of this bug?

**Comment by jeyip** [comment] 2021-02-15 18:37
Thanks for the ping @synora! 

@cathymcbride thoughts on this relative to other maintenance work currently on the board? This seems like a persistent, ugly bug, and there have been consistent reports month-to-month. If I remember correctly, there were possible workarounds, but they require intervention from Happiness Engineers or imposing arbitrary limitations what kind of content the user adds.

**Comment by cathymcbride** [comment] 2021-02-16 16:01
@jeyip I think it's OK to prioritize this higher, since we are seeing a steady stream of reports and, as you say, it is quite ugly. I've bumped the pri and I see it's on the prioritized backlog, which seems appropriate.

**Comment by mikeicode** [comment] 2021-02-22 19:42
Another 27822707-hc

**Comment by jeyip** [comment] 2021-03-04 01:26
I tracked things down to an older change that were made explicitly to solve another bug ( see 20390e6459a79be7f689c814708e49b8a0d8d6ed-GH-block-experiments )

```scss
// Fixes an issue in Firefox where a block in the grid with 100% height causes the grid to increase in height
@-moz-document url-prefix() {
	.wp-block-cover {
		max-height: 0;
	}
}
```

To elaborate further, the original author left an additional message. "If a single column of a grid block contains a block followed by a cover block then the cover breaks out of the grid."

@johngodley I saw that you authored the commit. Would you be able to chime in? I was hoping for more context before making any changes. Setting the max-height to 0 inadvertently cuts off text content of cover blocks nested within a layout grid column.

**Comment by johngodley** [comment] 2021-03-04 08:32
Can we move this to the block experiments repo? This, and other Layout Grid issues, can be looked at in a timely manner there alongside other changes to the block.

For reference, the change was made in https://github.com/Automattic/block-experiments/pull/38 to help with an issue on Firefox. The PR seems to describe the problem well, and @jasmussen may recall further details.

It is possible that Firefox has since been fixed and the change is no longer needed.

We can look at this issue in the next Layout Grid review.

**Comment by jasmussen** [comment] 2021-03-04 09:26
I would echo John, we are working on the Layout Grid block in the block-experiments repository, and it's hard to catch bugs reported for Calypso here. 

I have a fix in https://github.com/Automattic/block-experiments/pull/174, which to John's point needs to be tested a bit as it was added initially to fix a Firefox issue which I can, admittedly, no longer reproduce.

**Comment by jeyip** [comment] 2021-03-04 18:50
> Can we move this to the block experiments repo? This, and other Layout Grid issues, can be looked at in a timely manner there alongside other changes to the block.

> I would echo John, we are working on the Layout Grid block in the block-experiments repository, and it's hard to catch bugs reported for Calypso here.

Thanks for the responses @jasmussen and @johngodley. That makes total sense, and I'll move this issue now. I just found out about the block-experiments repo yesterday, but I'll definitely keep it in mind when we triage future tickets 👍

**Comment by jeyip** [comment] 2021-03-04 19:04
I'm going to close this Calypso issue to avoid duplicate tracking, but everyone can follow along in the issue I created in the block-experiments repo https://github.com/Automattic/block-experiments/issues/176

**Closed** 2021-03-04 19:06 UTC
Labels: Blocks, Involves Happiness, Triaged, [Pri] Normal, [Type] Bug
