### ISSUE TITLE
Header and Footer Template Parts Not Loading on Sites with Dotcom Implementation of FSE

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#56455] opened 2021-09-22 00:09 UTC
### Quick summary

Sites running the dotcom implementation of FSE return block errors when pages are opening in the editor.

The header and footer template parts do not render and instead display 

`This block has encountered an error and cannot be previewed.`

### Steps to reproduce

1. Open a site that is using the dotcom implementation of FSE 
2. Open a page in the editor or create a new one.

### What you expected to happen

For the editor to load without error messages.

### What actually happened

The content portion of the page loads, but the template parts (header/footer) do not. 

<img width="1430" alt="fseerror" src="https://user-images.githubusercontent.com/42279181/134263357-4c8e51c5-f445-442a-819e-d9d84f1bc4db.png">

The console reports TypeErrors:

```
TypeError: can't access property "name", e is undefined
    it https://s0.wp.com/_static/??-eJydktFuwyAMRX9oxE3XdXuZ9i0EGHICdgSmaf9+tKHSNE3d2jcwvocL17DMyjCJI4FY1ByKR8pgEi82oycd1CenmIHcUWAoGCw4i8KpG/MTfFNfpb7U7eCSV0NgM2UYnczaTCroExdRPqEFJOuOdxOSFiSfb6vP7mqXEuYwobQnwZy4Oj/UzqooJJYXWvlgMcvvR4/ccTUrGF1Aciv+Z/URMrklXyDtWy7guvZq5ix5Lavb6dzNNzpxyS78i264Sbddv+n6RmjFv+M2nBwc+r57qdp11s7Dp0UFHJJOp5Z8RKqwj/je75+3m7f96243fgHm1gzu:13
    Lodash 2
    <anonymous> https://s0.wp.com/_static/??-eJydktFuwyAMRX9oxE3XdXuZ9i0EGHICdgSmaf9+tKHSNE3d2jcwvocL17DMyjCJI4FY1ByKR8pgEi82oycd1CenmIHcUWAoGCw4i8KpG/MTfFNfpb7U7eCSV0NgM2UYnczaTCroExdRPqEFJOuOdxOSFiSfb6vP7mqXEuYwobQnwZy4Oj/UzqooJJYXWvlgMcvvR4/ccTUrGF1Aciv+Z/URMrklXyDtWy7guvZq5ix5Lavb6dzNNzpxyS78i264Sbddv+n6RmjFv+M2nBwc+r57qdp11s7Dp0UFHJJOp5Z8RKqwj/je75+3m7f96243fgHm1gzu:13
react-dom.min.edd8b7a6.js:7:28567
```

### Context

User Report in 16168183-hc

### Simple, Atomic or both?

Simple

**Comment by jeyip** [comment] 2021-09-22 00:42
## Technical Details

- I reproduced the problem on a fresh legacy FSE site. That could mean that this issue is occurring for _all_ legacy FSE sites.
- The runtime errors appear to originate from the crowdsignal-forms plugin from the `isPollBlock` function ( [link](https://github.com/Automattic/crowdsignal-forms/blob/ba4d79168d4ecb8979049dbaa532f8670096bd26/client/blocks/poll/subscriptions.js#L15-L18
) )
- If I remove all of the offending crowdsignal-forms source code from my sandbox in `wp-content/mu-plugins/crowdsignal-forms/next/build/editor.js`, legacy FSE template parts **_do_** load properly on a sandboxed site
- The underlying crowdsignal-forms source code, however, hasn't changed in a year.
- If we trace the logic to where the offending function is used, we see that it relies on the `getBlocks` selector defined in Gutenberg
- There _were_ recent changes to `getBlock` and `getBlocks`. ( [link](https://github.com/WordPress/gutenberg/pull/34241) ) I haven't confirmed if it's the causing the problem though.

**Comment by Robertght** [comment] 2021-09-22 05:53
Asking in Slack as well: C029WGXE5T4/p1632289896014600

**Comment by Addison-Stavlo** [comment] 2021-09-22 14:22
We currently set up legacy FSE to run off the previous version of Gutenberg (v11.4.1) as a temporary fix to this issue.
D67210-code, D67214-code, D67226-code

Im leaving this issue open while we investigate and fix the root of the bug and have legacy FSE on the latest Gutenberg version again.

**Comment by jeyip** [comment] 2021-09-23 05:08
I believe I've identified the issue in core Gutenberg that's causing conflicts with legacy FSE. I've made an issue and information about how to reproduce the problem here https://github.com/WordPress/gutenberg/issues/35066.

## Technical Details
- We call the `receiveBlocks` action when loading legacy FSE template parts ( [link](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/dotcom-fse/blocks/template/edit.js#L60) ). 
- Unfortunately, for some reason, calls to `receiveBlocks` insert `undefined` values into `block-editor` state ( [link](https://github.com/WordPress/gutenberg/issues/35066) ). This is what I believe to be the root cause of our issue.
- When `block-editor` state is subsequently read by `crowdsignal-forms` via [getBlocks](https://github.com/WordPress/gutenberg/blob/1620d517274476321fdbc65fc1eeca0ef985ad39/packages/block-editor/src/store/selectors.js#L172-L178) ( [link](https://github.com/Automattic/crowdsignal-forms/blob/ba4d79168d4ecb8979049dbaa532f8670096bd26/client/blocks/poll/subscriptions.js#L110) ), they're not expecting `undefined` blocks.
- Runtime errors are thrown because `crowdsignal-forms` logic attempts to evaluate attributes of the `undefined` blocks ( [link](https://github.com/Automattic/crowdsignal-forms/blob/ba4d79168d4ecb8979049dbaa532f8670096bd26/client/blocks/poll/subscriptions.js#L15-L18) )

**Comment by jeyip** [comment] 2021-09-23 22:34
As Addie mentioned earlier, we've pinned legacy FSE to Gutenberg v11.4 for now. We have [a patch in Gutenberg](https://github.com/WordPress/gutenberg/pull/35076), but it hasn't been introduced to dotcom sites yet. **Legacy FSE, however, should still be working.** The bug was attributed to compatibility problems with Gutenberg v11.5, and pinning to v11.4 avoids compatibility issues entirely.

We're planning to leave legacy FSE sites pinned to an older Gutenberg version, and, at some regular interval in the future (every 2 or 3 months), we plan to revisit and update the pinned Gutenberg version manually. This will allow us to avoid surprises like this template part rendering issue in the future. Doing so will permit us to thoroughly test newer Gutenberg versions against legacy FSE before integrating the two plugins in production.

When we _do_ decide to update the pinned Gutenberg version, it will automatically include [the patch](https://github.com/WordPress/gutenberg/pull/35076) that addresses the root cause of this template parts rendering issue.

Given all of these considerations, I'll be closing this issue for now.

**Closed as completed by jeyip** 2021-09-23 22:34 UTC
Labels: Bug, [Pri] BLOCKER, [Goal] Full Site Editing, [Impact] High
