### ISSUE TITLE
Global notices appear over content

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#14035] opened 2017-05-15 10:47 UTC
This happens in the two factor authentication screens in login, but it seems like it would be a problem with global notices more generally:

Spotted by Hafiz in #13987:

![](https://cloud.githubusercontent.com/assets/266376/26024765/fe34a6b2-3802-11e7-9a13-3cb756b058b9.png)

This error notice shouldn't overlap the text.

Are there other screens that are affected by this? How should we deal with this?

**Comment by fabianapsimoes** [comment] 2017-05-15 10:51
Is it by design that the error notice is displayed at the bottom? Seems like it'd be very easy to miss on mobile.

**Comment by stephanethomas** [comment] 2017-05-15 11:19
I can confirm that it's not specific to this page (e.g. start the signup flow and enter `&` on the `Domains` step to see this notice), and that the position of the notice depends on the width of the viewport. I thought it was made on purpose to have it at the bottom of the screen on mobiles - the idea being that it should always be visible (i.e. the notice should _stick_ to the bottom of the screen). It looks like I'm probably wrong.

@rickybanister worked on global notices [back in January](https://github.com/Automattic/wp-calypso/pull/9443), maybe he will have some insights.

**Comment by scruffian** [comment] 2017-05-15 11:23
@stephanethomas I believe you are correct, but we need to consider cases where the content isn't as tall as the viewport, and where it doesn't scroll.

**Comment by rickybanister** [comment] 2017-05-15 14:30
Yes, the global notice narrowest viewport style is to stick to the bottom of the screen so that it avoids the masterbar and doesn't obscure content in the main part of the viewing area. 

It doesn't seem like this notice needs to be 'global'—couldn't it be inline and appear above the main card?

**Comment by drw158** [comment] 2017-11-15 21:44
I agree, it should be inline somewhere in/around the main card.

**Comment by stephanethomas** [comment] 2017-12-29 16:07
I'm closing this issue as it has been addressed:

<img width="456" alt="screenshot" src="https://user-images.githubusercontent.com/594356/34441249-bdedd66a-ecba-11e7-8e36-ea954d2d1aba.png">

**Closed by stephanethomas** 2017-12-29 16:07 UTC
Labels: Components, [Type] Bug
