### ISSUE TITLE
Domain Manager: Prevent users from adding MX records when they have email forwarding enabled

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#1534] opened 2015-12-13 21:15 UTC
In previous versions of the Domain Manager, a user was given an error message when they had email forwarding enabled and attempted to add another MX record, they had an error:
<img width="645" alt="screen shot 2015-12-12 at 2 31 55 pm" src="https://cloud.githubusercontent.com/assets/8921630/11763558/2f9e54c2-a0de-11e5-9643-3425aa5426d0.png">

In Calypso, MX records can still be added when forwarding is enabled:
![selection_437](https://cloud.githubusercontent.com/assets/8921630/11763561/37f6eeb8-a0de-11e5-8f5f-2178abbdf712.png)

To reproduce:
1) Navigate to /domains and choose a site with a custom domain
2) Under Email, make sure to enable, add and verify a forwarder
3) Under Name Servers and DNS> DNS Records, Add New DNS Record
4) Notice the "Mail handled by WordPress.com email forwarding" MX Record
5) Add a new MX record, it is allowed and saves.

I think the best solution is highlighting the two MX records in red, and alert messaging near the top "Conflicting MX records for %DOMAIN may prevent email from being delivered."

I can see arguments being made for preventing them from adding the MX record altogether, but if their intention is to turn off mail forwarding, they would have to retype their new record another time.

Educating the user on how domain records works instead of forcing them to retype/click around more would be more helpful and aligned with how happiness works.

Another option would be an accept or deny dialog of some sort that deletes one the conflicting MX Records (could be more than one) depending on the user's choice. I'd prefer the first choice.

**Comment by designsimply** [comment] 2016-05-06 00:17
Tested and confirmed that I can add an MX record if I already have email forwarding setup.

![screen shot 2016-05-05 at thu may 5 6 06 30 pm](https://cloud.githubusercontent.com/assets/1119271/15060959/0e52ced4-12ed-11e6-9542-85575e734d5c.png)
<sup>Seen at https://wordpress.com/domains/manage/threedotonefour.com/dns/design5279.wordpress.com using Safari 9.1 on Mac OS X 10.11.4</sup>

However, recommend closing or moving to a milestone where it will be reviewed in a reasonable time since this was opened 144 days ago, was marked `[Pri] Low` 99 days ago, and has had no activity since.

@umurkontaci, we are leaning toward closing very old `[Pri] Low` issues as wontfix, should this issue be closed?

**Comment by umurkontaci** [comment] 2016-05-06 18:18
It's definitely not a priority right now, but I'd rather not forget to fix this in the future since it will break the user's ability to receive emails.

**Comment by dcoleonline** [comment] 2016-11-04 21:47
I also encountered this in ticket 2894181-t while helping a WordPress.com user.

**Comment by klimeryk** [comment] 2021-02-02 11:04
Marking this as wontfix - I like the solution proposed here, but we're focusing on our own custom solution now.

**Closed by klimeryk** 2021-02-02 11:04 UTC
Labels: Domains, [Type] Bug
