### ISSUE TITLE
Gutenboarding: mobile login

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40908] opened 2020-04-08 11:49 UTC
In [Gutenboarding](https://wpcalypso.wordpress.com/new), signup should look like this on mobile:

<img width="393" alt="Screenshot 2020-04-08 at 14 48 34" src="https://user-images.githubusercontent.com/87168/78780957-190d7380-79a8-11ea-8191-20529f650d36.png">

@Automattic/ganon wanna take on this? I haven't actually checked if it already looks like this. 😅

**Comment by ramonjd** [comment] 2020-04-08 21:33
Looks like this is a dupe of #40907

Can I close this in favour of that one?

>  I haven't actually checked if it already looks like this.

I was tooling around with the widths last night and it's nearly there anyway. Needs just a few tweaks in relation colour and maybe sizing of elements.

The challenge is that the font picker page extends the underlying page width beyond the `335px` width of the design and, as a result, the signup modal cannot be narrower than 500px.

**Comment by ramonjd** [comment] 2020-04-08 21:35
Closing in favour of #40907

**Comment by simison** [comment] 2020-04-15 08:45
Looks like this currently:

<img width="323" alt="Screenshot 2020-04-15 at 11 44 15" src="https://user-images.githubusercontent.com/87168/79317516-75274900-7f0e-11ea-8cba-465b1462c0e4.png">

<img width="331" alt="Screenshot 2020-04-15 at 11 44 19" src="https://user-images.githubusercontent.com/87168/79317522-76587600-7f0e-11ea-993e-1eb84461db18.png">

I would suggest saving space by removing the W logo.

@dubielzyk

**Comment by dubielzyk** [comment] 2020-04-15 08:47
Nah, let's keep it. The consistency is nice. If there's one page without it, it'll be a bit weird.

**Comment by sirreal** [comment] 2020-04-15 09:45
Looks like this is settled.

**Closed by sirreal** 2020-04-15 09:45 UTC
Labels: Login, [Goal] Gutenboarding, [Type] Task
