### ISSUE TITLE
XML content import not working on Simple sites

### ISSUE THREAD

**Issue by swoodipto** [Automattic/wp-calypso#55237] opened 2021-08-06 12:15 UTC
### Steps to Reproduce

1. Go to **Tools > Import**
2. Click **WordPress** option
3. Click the **"upload it to import content"** link
4. It redirects back to the **Tools > Import** page again with `?retry=1` appended at the end of the URL. Like so `https://wordpress.com/import/example.wordpress.com?retry=1`

### What I expected to happen

Clicking on "upload it to import content" should have took me to a screen to upload my xml file.taken

### What actually happened

It redirects back to **Tools > Import** page. Even if I click **Choose form full list** and click **Run importer** under WordPress option it still does the same on simple sites. On simple sites, it works fine if we directly import it from this link `https://example.wordpress.com/wp-admin/admin.php?import=wordpress`

Works fine on Atomic.

### Context

Reported by the customer in 4202464-zen and replicated by me on simple sites. Works fine on Atomic.

### Operating System

macOS

### Browser

Chrome/Chromium

### Simple, Atomic or both?

Simple

### Level of impact

High

### Reproducibility

Consistent

**Comment by philnick206** [comment] 2021-08-08 13:07
Another report in #4203481-zen

**Comment by philnick206** [comment] 2021-08-08 13:51
Another report in #4203652-zen

**Comment by kosiew** [comment] 2021-08-11 06:42
Hi @otpidusprime ,

Thanks for reporting this and the detailed steps.


I could not reproduce this.
From  my tests so far, this was a transient issue.

Closing this for now. Please reopen this issue if you have more findings to add.

**Closed as completed by kosiew** 2021-08-11 06:42 UTC
Labels: Bug, [Pri] High
