### ISSUE TITLE
Limit Odie message size

### ISSUE THREAD

**Issue by renancarvalho** [Automattic/wp-calypso#95584] opened 2024-10-22 14:09 UTC
### Quick summary

Currently, users can send massive messages to Odie, the API does not allow that. Maybe we should prevent it from the front end too.

![Image](https://github.com/user-attachments/assets/601a79c8-c6d4-40de-a4ae-5b309453410c)

### Steps to reproduce

Use help center
Send a massive message to Odie

### What you expected to happen

The message should be sent

### What actually happened

Message not sent

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by andregardi** [comment] 2024-10-22 22:06
@renancarvalho 
I could not reproduce the issue. When you refer to Odie, I assume it is the chatbot on help center.
![Image](https://github.com/user-attachments/assets/9325b2fa-d40f-4cca-b811-d0134fa129ec)

I even sent a 13k chars message and were able to get a response.

The API error you posted refer to `.message.text` and 4096 char limit.
Maybe you are not referring to Odie but to the zendesk integration we get after insiste to talk with an human?
In that context `.message.text` is part of the request body and 4096 chars is the exact limit.
When I manually tested it, the client side already prevented me to send more than 4096 chars message.
![Image](https://github.com/user-attachments/assets/5bed69eb-024e-4c27-a5a1-9b4a2aecedfd)

**Comment by supernovia** [comment] 2024-10-23 18:05
📌 REPRODUCTION RESULTS
- Could not replicate


📌 FINDINGS/SCREENSHOTS/VIDEO
I also got a character limit warning, and my message turned pink to indicate it didn't send:
![Image](https://github.com/user-attachments/assets/145128c1-c61f-4f84-89b1-a670aa332e23)
![Image](https://github.com/user-attachments/assets/ceb7681f-9f70-48cf-891b-a41b2654e113)

📌 ACTIONS
- Triaged (for now)
- Requested author feedback


📌 Message to Author
@renancarvalho I believe I was still talking to a bot in my tests and I got a character limit warning.  I'll mark this as Triaged for now, but if you or @andregardi need more help triaging this, please update us here and change the status back to Needs Triage. Thanks!

**Comment by supernovia** [comment] 2024-10-23 18:10
Oops, on second thought I'm moving it back to "In Triage" for now, but please let us know more about what we can do to replicate this.

**Comment by tanjoymor** [comment] 2024-10-24 22:10
Bit of back and forth here haha. But since @renancarvalho is taking another look, marking this as Triaged. Feel free to throw it back at us if you need us to take any action.

**Closed as completed** 2024-11-04 08:46 UTC
Labels: Bug, [Pri] High, Triaged, [Status] Priority Review Triggered
