### ISSUE TITLE
Plan Grid: Essential Plan Feature List

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wp-calypso#75301] opened 2023-04-04 21:07 UTC
Reported by me via the CFT: 

The copy for the feature list of the Essential plan in the "plans grid" on the /plans/ page seems to use the business plan feature list. 

![Image](https://user-images.githubusercontent.com/89872780/229923041-fbca7d73-e05d-4ce4-a39b-d5e7933210a3.png)

It should match the design as seen here

![Image](https://user-images.githubusercontent.com/89872780/229923114-890c8239-9803-4ada-a564-9b53dde8fba6.png)

Creating this as a separate ticket from the final essential plan page because I believe that feature list is stored elsewhere and not directly on the page. 

[Figma for reference](https://www.figma.com/file/lD0gTB4IqGsmSmsnjZNaP6/Free-Trial---E2E-Experience?node-id=2740-24936&t=S6jBZ90hrogyeMNi-0)

**Comment by adrianduffell** [comment] 2023-04-05 09:00
@that-mike-bal This might be better with Serenity. 

It probably depends if copy needs updating (Ghidorah can take), or if this feature is fetching data from the wrong plan (Serenity probably best?)

**Comment by daledupreez** [comment] 2023-04-06 13:48
This is a duplicate of #75288, which we addressed in #75290.

I also want to note that we still have #75383 open to include the expandable feature comparisons.

**Closed as completed by daledupreez** 2023-04-06 13:48 UTC
Labels: Woo Express
