### ISSUE TITLE
Gutenboarding: This block has encountered an error and cannot be previewed.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#57667] opened 2021-11-04 18:22 UTC
### Quick summary

Rarely an error is shown when proceeding along Gutenboarding (as a signed out user) after filling out username/password details for a new account.

### Steps to reproduce

prereq. log out from WordPress.com.

1. navigate to `/start`.
2. choose a blog name.
3. select a free domain.
4. select the blank template.
5. select any font pairing.
6. select `Plugins` in the features page.
7. select 'Free' plan.
8. enter username/password to create a new account and create account.

### What you expected to happen

Gutenboarding proceeds to the next step - Land in Home Dashboard.

### What actually happened

Gutenboarding encountered an error with the following text:

`This block has encountered an error and cannot be previewed.`

### Screenshot
![image](https://user-images.githubusercontent.com/6549265/140397103-2a9c3ada-9481-4507-b6ed-4ac7ffdf5b39.png)

### Video
https://user-images.githubusercontent.com/6549265/140397397-52f4ae8f-78af-4ae8-adad-e5f59048160b.mp4

### Context

Automated end to end tests.

### Other notes

Error logs captured in Playwright trace:
```
62761.b6d666507ddaa8e6e656.min.js:1Error: onboarding-debug {"error":"invalid_token","status":400,"statusCode":400,"name":"InvalidTokenError","message":"The OAuth2 token is invalid."} at https://wpcalypso.wordpress.com/calypso/evergreen/entry-gutenboarding.209b1e05def15538f422.min.js:1:116251 at io (https://wpcalypso.wordpress.com/calypso/evergreen/entry-gutenboarding.209b1e05def15538f422.min.js:1:116365) at ia (https://wpcalypso.wordpress.com/calypso/evergreen/62761.b6d666507ddaa8e6e656.min.js:2:155634) at Va (https://wpcalypso.wordpress.com/calypso/evergreen/62761.b6d666507ddaa8e6e656.min.js:2:165152) at Gi (https://wpcalypso.wordpress.com/calypso/evergreen/62761.b6d666507ddaa8e6e656.min.js:2:208758) at Al (https://wpcalypso.wordpress.com/calypso/evergreen/62761.b6d666507ddaa8e6e656.min.js:2:195057) at Ol (https://wpcalypso.wordpress.com/calypso/evergreen/62761.b6d666507ddaa8e6e656.min.js:2:194985) at Cl (https://wpcalypso.wordpress.com/calypso/evergreen/62761.b6d666507ddaa8e6e656.min.js:2:194848) at bl (https://wpcalypso.wordpress.com/calypso/evergreen/62761.b6d666507ddaa8e6e656.min.js:2:191835) at https://wpcalypso.wordpress.com/calypso/evergreen/62761.b6d666507ddaa8e6e656.min.js:2:141553
```

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

User would likely need to restart Gutenboarding.

**Comment by worldomonation** [comment] 2021-11-11 06:20
Another instance observed on TeamCity build ID 6967156.

**Comment by worldomonation** [comment] 2021-11-11 06:23
Assigning High Priority due to the following criteria:
- hard blocking, no workaround available.
- affects one user at a time.

**Comment by worldomonation** [comment] 2021-11-11 06:48
Slack: p1635985973066500-slack-CBTN58FTJ

**Comment by worldomonation** [comment] 2021-11-23 19:35
Another occurrence in Gutenboarding: 7025702

**Comment by worldomonation** [comment] 2021-12-13 22:24
Yet another instance: https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Pre_Release/7122316?buildTab=artifacts#%2Fscreenshots

**Comment by autumnfjeld** [comment] 2022-01-07 01:02
Hi @worldomonation  @Automattic/ganon-bloggers  could work on this.   I'd just like to clear up a few points of confusion:


* Gutenboarding is /new (not /start). Is your mention of /start in the issue description a mistake?
* As far as I understand we don't provide any external links to wordpress.com/new -- /new is for existing users only, accessible via CTAs in Calypso.   So we wouldn't expect any brand-new (non-logged-in) users to land on wordpress.com/new

**Comment by autumnfjeld** [comment] 2022-01-17 08:24
> Slack: p1635985973066500-slack-CBTN58FTJ

This slack discussion is for headstart erros and was addressed in this issue https://github.com/Automattic/wp-calypso/issues/57837

**Comment by autumnfjeld** [comment] 2022-01-17 08:29
I replated these steps:

- log out of wordpress
- navigate to wordpress.com/new.
- choose a blog name.
- select a free domain.
- select the blank template.
- select any font pairing.
- select Plugins in the features page.
- select 'Free' plan.
- enter username/password to create a new account and create account.

I was taken to My Home, after the last step.  Signup worked as expected.

Closing this issue, but please alert Ganon if the issue is observed again.

**Closed as completed** 2022-01-17 08:29 UTC
Labels: Bug, [Pri] High, Needs triage

**Comment by worldomonation** [comment] 2022-01-20 00:58
Sorry for the late reply here.

The steps you've taken to reproduce the issue are correct; however as noted this issue is intermittent, one that appears to have occur at quite low frequency. 

I've taken a look at all available end-to-ends where this spec was run, and it appears that this spec hasn't failed for some time. If it happens again, I'll file a new issue.

**Comment by autumnfjeld** [comment] 2022-01-28 00:53
@worldomonation Also note that we are phasing out  the /new flow (e.g. Gutenboarding flow) so this issue will become obsolete: pbxNRc-1eh-p2

**Comment by worldomonation** [comment] 2022-01-28 01:01
@autumnfjeld  Good to know, thanks for the heads up.
