### ISSUE TITLE
Two Factor Authentication (2FA) Missing +678 Vanuatu Country Code - Cannot Setup

### ISSUE THREAD

**Issue by gwensmithx** [Automattic/wp-calypso#55796] opened 2021-08-27 14:27 UTC
### Steps to Reproduce

In the 2FA settings on any WordPress.com account, the first steps ask to **Enter Phone Number** whether you are using SMS or an Authenticator app.

You will notice the country Vanuatu is not listed. This prevents 2FA from being setup.

![image](https://user-images.githubusercontent.com/15944096/131474985-dcbbe54b-914c-490a-8d4d-8496379b5c72.png)

### What I expected to happen

Expected Vanuatu to be listed with the other countries.

### What actually happened

Vanuatu is not listed.

### Context

#31284583-hc
Followup #4251636-zd

### Operating System

macOS

### Browser

Chrome/Chromium

### Number of Users Impacted

All users

### Reproducibility

Consistent

**Comment by formosattic** [comment] 2021-08-31 09:08
Vanuatu indeed is missing from the two-steps authentication setup. 

Updated report with screenshot.

**Comment by mreishus** [comment] 2021-08-31 21:16
* Patch to add to country code list: D66157-code

While this definitely adds it to the list, a more important question is, will sending SMSes to the Vanuatu country work? I have no way to test. 
We use twilio to send SMSes for us. While [the capabilities for VU listed on their guidelines page](https://www.twilio.com/guidelines/vu/sms) look quite sparse, [their pricing page for VU does list per message prices](https://www.twilio.com/sms/pricing/vu), which makes me think they are able to send messages to the country.

* Previous discussion here: p58i-29L-p2 (2013) p58i-29L-p2#comment-45486 (2020 bump from @Robertght)

**Comment by mreishus** [comment] 2021-09-14 14:49
DD66157-code has been deployed.

@gwensmithx , it's now on the list of countries available on the 2FA page.
![2021-09-14_09-48](https://user-images.githubusercontent.com/937354/133280326-71e9d176-6f18-4b26-bb18-d94d0c68bd15.png)
However, we have no method to verify that it is functioning correctly. Is it possible to follow up with the user and see if this fixes the problem?

**Comment by formosattic** [comment] 2021-09-18 09:09
Thanks @mreishus!
I've asked the user to give it a try.

Ticket: 4307738-zd-woothemes

**Comment by arinoch** [comment] 2021-09-19 21:36
The user tested, still can't receive the SMS code.

**Comment by mreishus** [comment] 2021-09-22 21:40
Unfortunately, I must have mis-interpreted the twilio pages for the `vu` country. If the SMS messages are not being sent after we add the country to the list, then it means that our provider (twilio) does not support the country. I have backed out the changes here: D66157-code (meaning that VU will no longer display in the list).

Here's a record of the twilio pages `https://www.twilio.com/guidelines/vu/sms`  `https://www.twilio.com/sms/pricing/vu` as I seem them today:
![2021-09-22_16-39](https://user-images.githubusercontent.com/937354/134425742-e5a65647-a8df-4da8-ae80-a48e30adfb53.png)
![2021-09-22_16-40](https://user-images.githubusercontent.com/937354/134425752-c921df44-1e97-4d79-a443-2b20b3ccd460.png)
![2021-09-22_16-40_1](https://user-images.githubusercontent.com/937354/134425758-d1f2ef26-87c5-4e2d-825f-c0ccd08caba2.png)

I'm not sure if we can do anything other than waiting for twilio to add support for the country.

**Comment by flameslash** [comment] 2021-09-24 04:56
I've closed this ticket 4307738-zd-woothemes for now as there is no update.  Please open a new ticket for the user if ever this gets fixed and let them know of the update.

Thank you!

**Comment by cometgrrl** [comment] 2022-08-18 21:21
Currently, you can choose 2FA using an app without entering a phone #. Since we cannot send SMS to Vanuatu, this is working as designed (country not in the list).

**Closed as completed by cometgrrl** 2022-08-18 21:21 UTC
Labels: Bug, [Pri] High, Triaged, 2FA, [Pod] Flow Patrol (Manage)

**Comment by cuemarie** [comment] 2023-06-14 19:40
I've reopened a new (larger) report on this here: 

- https://github.com/Automattic/wp-calypso/issues/78207
