### ISSUE TITLE
Featured Images defaulting ON for pages and posts in Varia and Varia child themes.

### ISSUE THREAD

**Issue by the-misha** [Automattic/wp-calypso#85369] opened 2023-12-15 18:54 UTC
### Quick summary

Multiple users reporting that featured images are showing up on pages and posts where they're not wanted. This is due to the "Featured Images" checkboxes in the Content Options of the Customizer being selected in the theme without user action.

### Steps to reproduce

1. Start on a site with Varia or a child theme active. (Confirmed on Maywood, Stow, Alves.)
2. Go to Customizer →  Content Options.
3. Look under "Featured Images. Many sites will have these checkboxes selected without having done so themselves.

### What you expected to happen

If options are selected, featured images will appear on pages and posts.

If options are deselected, featured images will not appear on pages and posts, but will also not display image previews in post blocks (Blog Posts, Latest Posts, etc.)

### What actually happened

If options are selected, featured images will appear on pages and posts, sometimes duplicating images already present.

If options are deselected, featured images will not appear on pages and posts, but will also not display image previews in post blocks (Blog Posts, Latest Posts, etc.)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Known cases so far:
* 7458679-zd-a8c
* 7458223-zd-a8c
* 7449348-zd-a8c

**Comment by Aurorum** [comment] 2023-12-15 20:21
This is my bad, and a change made in Automattic/themes#7518 - but I was under the impression that Varia themes defaulted on for Featured Images with pages beforehand? 

There used to be an option in the Customizer to disable Featured Images manually, but that was incorrectly implemented. I suspect users who used that option previously would need to do so again. I don't think there's a workaround to avoid that.

**Comment by kerrynicl** [comment] 2023-12-15 22:21
@Aurorum 
**If options are deselected, featured images will not appear on pages and posts, but will also not display image previews in post blocks (Blog Posts, Latest Posts, etc.)**

Please see a user that is missing their blog post images because they do not want to see the blown up featured image on every page 
<img width="1749" alt="Markup 2023-12-15 at 17 18 12" src="https://github.com/Automattic/wp-calypso/assets/83325600/906db740-f1e7-431d-8297-a9f3dd24d620">
<img width="1837" alt="Markup 2023-12-15 at 17 18 43" src="https://github.com/Automattic/wp-calypso/assets/83325600/2ac0064a-591d-4e23-a33c-73a7f31b39f5">


<img width="1212" alt="Markup 2023-12-15 at 17 12 40" src="https://github.com/Automattic/wp-calypso/assets/83325600/39515bd3-ea1c-4bad-92bc-bd8f29418f55">
<img width="1214" alt="Markup 2023-12-15 at 17 13 41" src="https://github.com/Automattic/wp-calypso/assets/83325600/f24cc0ba-99f0-470f-9e0b-56d9f475797d">


Can a fix be worked on for this as this is affecting a good number of users.

**Comment by Aurorum** [comment] 2023-12-16 09:09
Ah, I see how that's a problem. Please correct me if I'm wrong, but this doesn't seem to be an issue with Varia. I can reproduce the same issue on the Canard theme:

| Enabled | Disabled |
|--------|--------|
| <img width="1567" alt="Screenshot 2023-12-16 at 12 04 38" src="https://github.com/Automattic/wp-calypso/assets/43215253/fa343c3d-c37b-4ac3-a423-47c9cda03081"> | <img width="1527" alt="Screenshot 2023-12-16 at 12 04 24" src="https://github.com/Automattic/wp-calypso/assets/43215253/d3009312-d229-4b9c-995d-da16225e7e71"> |

_Note that the river image in the Blog Posts block is also hidden alongside the clouds image_ 

It seems like an issue with Jetpack's Content Options itself. That probably shouldn't override the Featured Image option selected in a block. 

cc @jeherve for if this is worth moving to the Jetpack repo

**Comment by OmarFPG** [comment] 2023-12-17 19:59
I got three related cases this week:
7452750-zen Theme: Dalston (Free)
7449137-zen Theme: Stow (Free)
7459086-zen Theme: Independent Publisher 2 (Free)

Regarding a Workaround, the users can remove the featured images on their pages manually if they don't need them, or if the user has a CSS-enabled site, they can use this snippet:

```
/* Hide Featured Images on Pages */
.page figure.post-thumbnail {
    display: none;
}
```

**Comment by jeherve** [comment] 2023-12-18 09:27
> It seems like an issue with Jetpack's Content Options itself. That probably shouldn't override the Featured Image option selected in a block.

Yes, this is currently tracked in https://github.com/Automattic/jetpack/issues/29286

**Comment by Aurorum** [comment] 2023-12-18 10:11
Thanks! In that case, I see how Varia exposed more people to this bug, but this looks like something which will need to be fixed in Jetpack instead.

**Comment by OmarFPG** [comment] 2023-12-19 00:54
7463738-zen. Provided CSS workaround.

**Comment by vindl** [comment] 2023-12-19 16:21
@OmarFPG, it looks like the CSS workaround also removes the featured images from the Blog Posts, which doesn't seem like a complete solution. In that sense, it's equivalent to removing the `Display on pages` toggle.

**Comment by vindl** [comment] 2023-12-19 17:11
7465066-zd-a8c

I provided the following CSS workaround:

```
/* Hide Featured Images on Pages while retaining them on Blog Posts page | zd-7465066 */
.page figure.post-thumbnail:not(.wp-block-newspack-blocks-homepage-articles figure.post-thumbnail) {
    display: none;
}
```

**Comment by jp-imagines** [comment] 2023-12-19 19:17
Another report in 7448689-zd-a8c (Exford). The more specific CSS code above works well as a workaround.

**Comment by kerrynicl** [comment] 2023-12-19 19:39
7449348-zen

**Comment by jp-imagines** [comment] 2023-12-19 20:57
Another in 7475340-zd-a8c.

**Comment by i11za** [comment] 2023-12-20 16:22
Several sites reported: 7479151-zd-a8c

**Comment by tvolpert** [comment] 2023-12-20 18:07
another report in 7479620-zd-a8c

I just had them turn off the "show on pages" option in the customizer and that worked for this site at least

**Comment by pbking** [comment] 2023-12-20 19:35
This should be fixed with this change to varia themes: https://github.com/Automattic/themes/pull/7567

**Comment by mgozdis** [comment] 2023-12-21 15:54
Getting reports of the featured images on Page setting now being disabled automatically when it was enabled previously. This was causing the featured images to no longer display on the user's homepage with theme `Hever`. I enabled the setting so that images display again: 7483718-zd-a8c

**Comment by jp-imagines** [comment] 2023-12-21 19:45
Experienced the same thing as above in 7484842-zd-a8c – featured images on pages were suddenly disabled, when that setting had previously been enabled.

**Comment by Aurorum** [comment] 2023-12-21 19:50
@jp-imagines It looks like the user in 7484842-zd faced this issue: Automattic/jetpack#29286. 

But I'm not sure why the user in 7483718-zd had this problem because their report was after Automattic/themes#7567 was merged. I worry that the legacy setting from the Customizer is no longer accessible after it has been removed.

**Comment by jp-imagines** [comment] 2023-12-21 21:41
@Aurorum The site in `7484842-zd` is a WoA site, and Jetpack was never disconnected (or deactivated), which seems to be the a requirement to replicate that other issue you mentioned. (The page that user referenced also uses a Blog Posts block like in this report, not a Latest Posts block.)

What I saw there matches what @mgozdis reported with `7483718-zd`: the `Featured images: Display on posts` option was unchecked in the Customizer > Content Options area after the PR was merged. The option is still accessible, it was just toggled without user action. I'm not 100% sure that the PR is the cause, but it definitely seems related from what I understand.

**Comment by Aurorum** [comment] 2023-12-22 06:24
Ah - sorry @jp-imagines - I think this issue has merged into two problems:

1. Jetpack bug - Content Options is preventing thumbnails from displaying where they spoil (on both the Blog Posts block and Latest Posts block; it doesn’t matter, and it’s unrelated to Jetpack connection)
2. The toggle being changed without user action 

Re-reading `7483718-zd` again, it looks like they faced both (with pages though, not posts). But I’m stumped on how to fix the latter, since that PR should have rectified the situation. :/ Will continue digging

**Comment by mgozdis** [comment] 2023-12-22 16:21
Another instance here where the Featured Image setting for `Display on pages` was disabled without user intervention and had to be re-enabled on `Hever` theme: 7488348-zd-a8c

**Comment by mgozdis** [comment] 2023-12-22 17:01
Featured Image setting for `Display on pages` was disabled without user intervention and had to be re-enabled on `Stratford` theme: 7488511-zd-a8c

**Comment by OmarFPG** [comment] 2023-12-26 06:06
7491831-zen,
7496889-zen

**Comment by OmarFPG** [comment] 2023-12-27 23:05
7503293-zen

**Comment by jp-imagines** [comment] 2024-01-08 17:27
Another in 7553378-zd-a8c and 7553483-zd-a8c where `Display on pages` was disabled. Directed both users to re-enable the setting to have their blog pages show post featured images again.

**Closed as completed** 2024-01-10 16:00 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] High, [Feature] Customizer, Triaged, Customer report [LEGACY], [Interaction #] > 20, [Status] Priority Review Triggered, [Product] WordPress.com

**Comment by OmarFPG** [comment] 2024-01-10 20:26
7566104-zen

**Comment by Aurorum** [comment] 2024-01-10 20:29
Just noting that this should be fixed with the next Jetpack release - ie. tonight/tomorrow for Simple sites like the one above.

**Comment by OmarFPG** [comment] 2024-01-11 21:48
7571620-zen, still going on. Maybe a few more days to go.
