### ISSUE TITLE
Gutenberg: Columns block with cover images not displaying properly

### ISSUE THREAD

**Issue by guicmazeredo** [Automattic/wp-calypso#28324] opened 2018-10-24 04:44 UTC
**Describe the bug**
When using Columns block with cover images the front-end is displaying broken. 

**To Reproduce**
1. Create a columns block.
2. Add a cover image and a title.
3. Check the live site.

**Expected behavior**
Images with the same size and the title center aligned. 

**Screenshots**
You can see the difference between the dashboard and the front-end on this video:

http://cld.wthms.co/q9pXLU

The site is live so you can take a look here: 

https://gutenbergsimple.wordpress.com/columns/

**Desktop (please complete the following information):**
 - OS: MacOS
 - Chrome

**Comment by arunsathiya** [comment] 2018-12-12 14:16
I am not able to reproduce this anymore. It works fine with Radcliffe 2 at the moment.

<img width="1281" alt="screenshot 2018-12-12 at 19 43 15" src="https://user-images.githubusercontent.com/18581859/49875260-92de2d00-fe46-11e8-9815-119e81c89e7b.png">
<img width="1281" alt="screenshot 2018-12-12 at 19 43 22" src="https://user-images.githubusercontent.com/18581859/49875261-9376c380-fe46-11e8-95a2-2de5b9ad90e0.png">

So is the case with Twenty Seventeen.

<img width="1281" alt="screenshot 2018-12-12 at 19 45 02" src="https://user-images.githubusercontent.com/18581859/49875268-983b7780-fe46-11e8-9982-9ac46a078b38.png">

I am closing this issue at the moment, but feel free to reopen if this persists.

**Closed by arunsathiya** 2018-12-12 14:16 UTC
Labels: [Goal] Gutenberg
