### ISSUE TITLE
CoBlocks Hero Block: Button toolbar unusable/disapears

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#41501] opened 2020-04-27 23:16 UTC
### Describe the bug:
The toolbar for the buttons within a Hero Block is unusable, or simply doesn't show at all, making it impossible to add a link for the button.

When the block has a background image, the toolbar doesn't show at all. When the image is removed, clicking on a button reveals the toolbar, but the toolbar cannot be clicked:
![](https://d.pr/i/I08LuQ+)

Tested in latest versions Chrome and Firefox. Looks like it is only happening on simple sites.

### To reproduce:

1. On a simple site, create a new, blank page and add the Hero Block
2. Try clicking on a button to add a link to the button. When trying to click the link, the toolbar disappears
3. Add a background image to the Hero block, then click on a button. No toolbar shows.

---

First noted in 20639804-hc, where a user couldn't add links to their buttons.

Workaround: User a cover block and add buttons to it.

**Comment by WunderBart** [comment] 2020-08-26 13:45
Closing as I couldn't reproduce after the recent update (https://github.com/Automattic/wp-calypso/issues/45033). Buttons toolbar works as expected with & without the bg image.

**Closed by WunderBart** 2020-08-26 13:45 UTC
Labels: Editor, [Type] Bug
