### ISSUE TITLE
Legacy Button Block link box floats to the top/can become hidden (Template Relevant)

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#46326] opened 2020-10-09 18:50 UTC
We're still using a Legacy Button Block in some of our Templates, and that Button Block (different from the Buttons Block) behaves  slightly differently.

#### Steps to reproduce

1. On a WordPress.com site (simple, for the example), create a new Page. 
2. When it prompts you to choose a layout, under About, select the third one, highlighted here:

![image](https://user-images.githubusercontent.com/30731356/95620334-dabf4280-0a24-11eb-8b69-9fc16c1cd3e5.png)

3. Scroll down a little bit, click the button that says Contact Me, and try to make it a link.
4. The link box will pop up above the Media & Text Block, which can be hidden if you scroll down too far.

#### What I expected
Ultimately, I'd expect the supported/current Buttons Block to be used instead of the legacy Button Block on templates. For what exists here though, I'd expect the link box to appear visible around the area where the link is being added.

#### What happened instead
The legacy Button Block link box pops up at the top, above the Media & Text Block.

#### Browser / OS version
All

#### Screenshot / Video
Legacy Button Block on the template:
![link](https://user-images.githubusercontent.com/30731356/95620540-338edb00-0a25-11eb-9104-8332b37f1fef.gif)

Supported Buttons Block instead:
![link](https://user-images.githubusercontent.com/30731356/95620694-705ad200-0a25-11eb-9168-7ccb9dbc3029.gif)

#### Context / Source
#user-report

**Comment by yansern** [comment] 2020-11-06 15:22
After some digging, I think the issue is that the `Popover` component used to display the `LinkControl` inside `packages/block-library/src/button/edit.js` doesn't have an `anchorRef` provided to it, therefore, the `Popover` component gets confused how to position itself. I think it should be explicitly anchored to the `ToolbarButton`.

Here's I have a patch that attempts to do that but it seems to introduce 2 issues:
- can't toggle the popover on & off once the popover is open
- it isn't quite anchored directly under the toolbar button, but rather, under the toolbar group.

I'll open a PR for this in gutenberg later after some more experimenting.

```
diff --git a/packages/block-library/src/button/edit.js b/packages/block-library/src/button/edit.js
index 690913ea01..6972f2359b 100644
--- a/packages/block-library/src/button/edit.js
+++ b/packages/block-library/src/button/edit.js
@@ -7,7 +7,7 @@ import classnames from 'classnames';
  * WordPress dependencies
  */
 import { __ } from '@wordpress/i18n';
-import { useCallback, useState } from '@wordpress/element';
+import { useCallback, useState, useRef } from '@wordpress/element';
 import {
 	KeyboardShortcuts,
 	PanelBody,
@@ -92,9 +92,11 @@ function URLPicker( {
 		} );
 		setIsURLPickerOpen( false );
 	};
+	const linkToolbarButtonRef = useRef( null );
 	const linkControl = ( isURLPickerOpen || urlIsSetandSelected ) && (
 		<Popover
 			position="bottom center"
+			anchorRef={ linkToolbarButtonRef.current }
 			onClose={ () => setIsURLPickerOpen( false ) }
 		>
 			<LinkControl
@@ -124,6 +126,7 @@ function URLPicker( {
 							title={ __( 'Link' ) }
 							shortcut={ displayShortcut.primary( 'k' ) }
 							onClick={ openLinkControl }
+							ref={ linkToolbarButtonRef }
 						/>
 					) }
 					{ urlIsSetandSelected && (
@@ -134,6 +137,7 @@ function URLPicker( {
 							shortcut={ displayShortcut.primaryShift( 'k' ) }
 							onClick={ unlinkButton }
 							isActive={ true }
+							ref={ linkToolbarButtonRef }
 						/>
 					) }
 				</ToolbarGroup>

```

![image](https://user-images.githubusercontent.com/1287077/98382999-98ede000-2054-11eb-9eba-3e6141499971.png)

**Comment by yansern** [comment] 2020-11-06 15:33
>  instead of the legacy Button Block

The *legacy*  term here is confusing me. Is `Button` block deprecated? From the code I can see Buttons is a wrapper for Button block, so they both would still need to work together.

> I'd expect the supported/current Buttons Block to be used instead of the legacy Button Block on templates.

Using `Buttons` block instead of `Button` block also exhibits the same issue (although the position of the popover is less far away). Fixing the `anchorRef` should fix the `Buttons` block too (since `Buttons` block uses `Button` block).

> We're still using a Legacy Button Block in some of our Templates

To identify which templates uses `Buttons` block and which template uses `Button` block, the folder to look inside is `wpcom/wp-content/lib/nux-helpers/vertical-content` folder. Since they are JSONified html templates, this will be quite an ordeal task to work on (many JSON files, many template entries).

If I were to approach this I would write quick one-off script to help parse & identify this.

**Comment by scosgro** [comment] 2020-11-06 18:48
> The legacy term here is confusing me. Is Button block deprecated? From the code I can see Buttons is a wrapper for Button block, so they both would still need to work together.

@yansern - It's not possible for a user to add a Button Block (singular) in the normal flow. The Buttons Block (plural) container is the only one that exists when adding blocks, and they appear to function differently with vs without that plural Buttons container.

The only time the Button Block appears on its own at this point is if it's written in manually, or if it is a part of one of these templates/themes. A conversation I had about this previously (where the two were functioning differently again) can be found here: https://github.com/Automattic/wp-calypso/issues/43267

**Comment by david-szabo97** [comment] 2020-12-01 18:43
1. Opened a PR that should fix the problem:

27408-gh-WordPress/gutenberg

2. And another one that should the issue mentioned by @yansern 
> can't toggle the popover on & off once the popover is open

27406-gh-WordPress/gutenberg

**Comment by david-szabo97** [comment] 2021-04-16 13:11
The reported issue is fixed by 27408-gh-WordPress/gutenberg

**Closed by david-szabo97** 2021-04-16 13:11 UTC
Labels: User Report, [Pri] Low, [Type] Bug
