### ISSUE TITLE
Domains: when a domain is not available it does not say but just adds the word blog

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-calypso#5031] opened 2016-04-26 21:30 UTC
I have had this a few times in tests now. If the domain isn't available it doesn't indicate that the domain isn't available, it just adds the word blog. 

This is a really weird experience for a user as a little unexpected. It would be great to somehow visually show the domain isn't available and the blog version is a suggestion.

<img width="603" alt="2016-04-26 at 22 28" src="https://cloud.githubusercontent.com/assets/253067/14834822/5a15dbae-0bfe-11e6-8795-3222657df460.png">

**Comment by folletto** [comment] 2016-05-20 14:32
This make sense, but would be nice to see if there's a way to test if it's worth adding a message, or it's more seamless to just show the alternatives. 
I'd guess it's better to show, just by comparing with other domain services, but I'd like to test since it would add noise.

Quick mock:

![screen shot 2016-05-20 at 15 25 54](https://cloud.githubusercontent.com/assets/4389/15431037/fe950cbe-1e9f-11e6-946a-03897c182b02.png)

/cc @breezyskies for a quick assessment, maybe she already has an answer. :)

**Comment by breezyskies** [comment] 2016-05-20 19:07
We haven't looked at showing unavailable messaging for *.wordpress.com domains yet. I think @folletto's suggestion is a nice simple solution and would make a good test. 

cc: @umurkontaci who was looking for some domain search test ideas. I'm not sure if this will necessarily increase custom domain sales (I think the conversion metric here would be the NUX step conversion), but this might also make the custom domain alternative look better?

**Comment by umurkontaci** [comment] 2016-05-20 19:12
Not sure whether it would increase domain sales overall but I think it will improve the experience as a whole, I think we can test this.

**Comment by umurkontaci** [comment] 2016-12-29 06:44
I think we can go with @folletto 's suggestion, and I think that we can maybe get rid of the notices we are using in domain search when a domain is unavailable. 

There plenty of reasons where a domain is not available (blacklisted, non-supported tld, tld maintenance, mapped to another blog) and there are cases where the domain is registered but available to mapping. I'm thinking integrating all these possibilities might require us to put a message somewhere.

Starting with @folletto 's example, I thought of this:
![image](https://cloud.githubusercontent.com/assets/991022/21538087/0eb200f4-cd4e-11e6-95c8-9c3ec3b04b6b.png)


Current:
![image](https://cloud.githubusercontent.com/assets/991022/21538162/f6ed2b8c-cd4e-11e6-9e40-a1abe9be6679.png)

My approach is similar to mapping suggestion we use at the end of suggested domains:

![image](https://cloud.githubusercontent.com/assets/991022/21538095/2265a394-cd4e-11e6-8670-664a093aa9ae.png)

What are your thoughts?

Ideally, when the domain is registered but mappable, we should provide a way for them to add domain mapping directly to their cart. Could be a link like "I own this domain". We might also want to avoid using red in that case.

What do you think @breezyskies and @folletto ?

**Comment by folletto** [comment] 2017-01-04 18:49
I'm sure I did a design to suggest map there too, but I can't find it again. This to say: I totally agree. We shouldn't stop a user, just say: 

> "The domain is taken, if it's yours and you have registered it somewhere else, map it here"

(maybe with less words). :D 

---

One step back tho, to support reasoning: what are all the cases?

1. Site is already owned/mapped on .com, not by the person doing the search
2. Site is already owned/mapped on .com, by the same person doing the search
3. Site is registered, but not mapped on .com

Any other instance?

If that's the case, 1-2 we should simply say it's not available (and point to the other site management if it's owned by the user). In the third case, we should show the upgrade mapping. 

FWIW, I think that the message stating the address is already taken would be an improvement by itself, so even if we start with that, and then implement more complex logic in a separate PR would work well imho. :)

**Comment by klimeryk** [comment] 2017-06-25 15:19
This has been implemented in `/domains`:
<img width="1005" alt="screen shot 2017-06-25 at 17 18 33" src="https://user-images.githubusercontent.com/3392497/27517289-639f9d98-59ca-11e7-9b15-c88254abb33a.png">

I think it's worth an A/B test showing a similar visual cue in NUX - adding it to the NUX board.

**Comment by alisterscott** [comment] 2018-03-06 06:56
An update on this issue - reading the original post I believe the behaviour was around .wordpress.com addresses and showing results which are only available, but the conversation is also about paid domain names both available and not.

The current behaviour for wordpress.com/start

Specifying an exact *.wordpress.com name when it's **available** shows a message that it's taken, but then shows it as being available - **this looks like a bug:**

<img width="994" alt="screen shot 2018-03-06 at 4 47 09 pm" src="https://user-images.githubusercontent.com/128826/37017914-1c0d4294-215e-11e8-8ee2-6e9f9f8c9569.png">

Specifying an exact *.wordpress.com name when it's **taken** shows a similar but not exact result (adds blog, or site, or a number) - **this I believe is the intention of this issue**

<img width="979" alt="screen shot 2018-03-06 at 4 50 41 pm" src="https://user-images.githubusercontent.com/128826/37018021-88c1d7ce-215e-11e8-9d3c-979331747d96.png">

Searching for a **phrase** that has an exact *.wordpress.com name **available** (without specifying .wordpress.com) looks ok:

<img width="988" alt="screen shot 2018-03-06 at 4 48 34 pm" src="https://user-images.githubusercontent.com/128826/37017956-42131bda-215e-11e8-9337-2add5b53b8a5.png">

Searching for a phrase that has an exact *.wordpress.com name taken (without specifying .wordpress.com) shows a similar but not exact result - not as much of an issue IMO

<img width="976" alt="screen shot 2018-03-06 at 4 52 27 pm" src="https://user-images.githubusercontent.com/128826/37018086-cdd36666-215e-11e8-9bd9-4dbf7319bbfe.png">

Specifying an exact domain name that is taken and exists elsewhere shows a mapping prompt which looks ok;

<img width="989" alt="screen shot 2018-03-06 at 4 53 34 pm" src="https://user-images.githubusercontent.com/128826/37018113-ed98736a-215e-11e8-9572-9d7f200bdbc6.png">

Specifying an exact domain name that is taken and exists in WordPress.com shows a mapping prompt which looks ok:

<img width="987" alt="screen shot 2018-03-06 at 4 54 16 pm" src="https://user-images.githubusercontent.com/128826/37018144-065fd08c-215f-11e8-804b-1633f65c7abf.png">

Specifying an exact domain name that is available shows the result (and the matching wordpress.com result) which looks ok:

<img width="1012" alt="screen shot 2018-03-06 at 4 54 37 pm" src="https://user-images.githubusercontent.com/128826/37018181-2666239a-215f-11e8-9d9f-699bec6ac800.png">

Should we keep this issue open to track any of these that don't look right, or would you rather I split these out into separate issues as necessary so we can prioritize these separately?

**Comment by aidvu** [comment] 2018-03-07 16:03
Weird @alisterscott. I tried it both NUX/Calypso, logged out and logged in, cannot reproduce...

**Comment by alisterscott** [comment] 2018-03-08 06:09
> I tried it both NUX/Calypso, logged out and logged in, cannot reproduce...

@aidvu: which one? I can test again

**Comment by aidvu** [comment] 2018-03-08 14:20
@alisterscott this one:
```
Specifying an exact *.wordpress.com name when it's available shows a message that it's taken, but then shows it as being available - this looks like a bug:```

Tried all the `domainSuggestionTestV6` variations, but couldn't reproduce.

**Comment by alisterscott** [comment] 2018-03-09 01:17
@aidvu I can no longer reproduce that error either

**Comment by alisterscott** [comment] 2018-03-09 01:22
@aidvu the closest I could get to reproducing it, even though I don't think it's exactly the same error:

(I'm in `domainSuggestionTestV6` group: `group_0`)

1. visit wordpress.com/start
2. proceed to domain step
3. search for a domain like testsomethingsomething888.wordpress**.co**
4. message about .co already taken - expected
5. change to **.com**
6. message now displays for .com also:

<img width="1008" alt="screen shot 2018-03-09 at 11 19 32 am" src="https://user-images.githubusercontent.com/128826/37185445-0fd942ea-238c-11e8-8460-3e758689fec5.png">

I didn't do this previously, I was just trying to find a way to reproduce it and found this.

Hope this helps

**Comment by aidvu** [comment] 2018-03-09 13:01
Nice! Yes, this is a bug, because it reuses the old availability result. Thanks @alisterscott!

/cc @jsnmoon Is there a chance this was introduced by your recent refactoring?

**Comment by klimeryk** [comment] 2018-03-17 19:47
Should be fixed by https://github.com/Automattic/wp-calypso/pull/23175

**Closed by klimeryk** 2018-03-17 19:47 UTC
Labels: Domains, NUX, Signup, [Type] Enhancement

**Comment by aidvu** [comment] 2018-03-17 19:53
@klimeryk not sure if the original issue is fixed. :) I just fixed the bug Alister found. 

The original issue is related with the display of unavailable `wp.com` subdomains.

**Comment by klimeryk** [comment] 2018-03-17 19:57
Ah, true, I got confused cause there are a few issues reported here, some of which were fixed. Not sure if worth re-opening or creating a new issue for the ones that do need fixing?

**Comment by aidvu** [comment] 2018-03-17 20:25
Not that easy to display the `unavailable` subdomain. @danhauk do you have ideas for this in the domain search improvements?
