### ISSUE TITLE
Gutenberg: Crash after trying to change permalink options on an autosaved post with no title

### ISSUE THREAD

**Issue by notnownikki** [Automattic/wp-calypso#28321] opened 2018-08-13 17:23 UTC
**Describe the bug**

You can make the title `[object Object]` and have Gutenberg crash if you click in the title field by doing these very specific, "will probably never be done in the wild but, you know, it's Nikki" steps.

**To Reproduce**

1) Start a new post on your favourite P2.
2) Don't click in the title. Click in the first paragraph block and type "woo yay" (doesn't really matter what you type, just type _something_).
3) Wait for autosave to kick in. The "Save Draft" button will change to "Saved".
4) Click in the title field.
5) Click the "Change Permalinks" button.
6) Close the window that is opened (it's a 404 anyway).
7) The title will now be `[object Object]`. Click in the title field.
8) Wonder how on earth Nikki manages to trip over these things.

If you do this in /wp-admin/, the title will not be `[object Object]` but it will still crash if you click in the title field.

This doesn't happen in the current release. It's _probably_ related to us being behind a few versions.

**Comment by kriskarkoski** [comment] 2018-11-16 18:34
Confirmed this is still happening. We should hide the Change Permalinks option completely on Simple sites since it's not available.

**Comment by kwight** [comment] 2018-11-16 23:32
Slightly-better-than-nothing patch at D21023-code for review.

**Comment by kwight** [comment] 2018-11-21 19:32
Improved D21023 so that it should work well for us, ready for review.

**Comment by gwwar** [comment] 2018-11-21 23:33
Thanks to @kwight D21023-code landed. Closing this out, we can follow up with a better fix in https://github.com/Automattic/wp-calypso/issues/28776

**Closed by gwwar** 2018-11-21 23:33 UTC
Labels: [Goal] Gutenberg, [Pri] High, wp-admin
