### ISSUE TITLE
Professional Email in signup: Completing checkout takes one to the site picker list instead of Home

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#55021] opened 2021-07-29 10:10 UTC
### Steps to reproduce the behavior

- Start at https://wordpress.com/start/domains?flags=signup/professional-email-step
- Visit the final stage of the checkout flow
- Complete checkout 

#### What I expected to happen

Completing checkout takes me to the Home page on Calypso.

#### What actually happened

We see the site picker list instead

### Context

Internal testing: p9anKZ-1VR-p2#comment-3861

#### Browser / OS version

Firefox 90.0.2 (64-bit).

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/18581859/127474056-39bfe0c0-cc20-4d26-bf27-7785b0de464e.png)

**Comment by daledupreez** [comment] 2021-07-30 08:07
I walked through this flow this morning, and I am fairly confident this is due to a timing issue around the site slug.

My thinking here is as follows:
 * The user will have bought a domain as part of the signup flow, but the site slug is still the *.wordpress.com subdomain
 * After checkout, we queue up an async job to make this domain the primary domain for the site (which changes the site slug)
 * Depending on how long the user spends reading the Quick Start content, the site slug may have changed out from under them by the time they try to navigate away using a possibly defunct site slug

You can reproduce this by working through the new signup flow from [wpcalypso.wordpress.com/start](https://wpcalypso.wordpress.com/start).
* On the domain step, pick a paid domain
* On the email step, feel free to skip or add Professional Email
* On the plans step, please pick a plan
* Complete checkout and make payment
* When (if?) you get to the Quick Start upsell screen, leave the screen open.
* Look at the URL to find your *.wordpress.com site slug
* Open a second tab/window to access this site: `https://wordpress.com/home/[siteSlug]`
* Refresh the second tab every so often until you get dropped into the site picker - this occurs because the site slug has changed

From looking at the HTTP traffic I see that the site picker is fetching the site list as well as successfully fetching the site using the old slug -- we may want to make the site picker perform an automatic redirect in the case where we can identify the intended site using the old/stale slug.

**Comment by simison** [comment] 2021-07-30 10:18
Can you use site ID instead?

**Comment by daledupreez** [comment] 2021-07-30 10:55
> Can you use site ID instead?

Maybe? But I believe all of the client-side logic is constructing (and expecting) URLs based on the slug, so I think that would be a tough thing to switch in the main routing logic.

I _think_ we can update the site switcher to work out of the slug is associated with a site, and automatically redirect to the correct URL for that site. This would also handle some other situations users can get into when they change the primary domain of their site (or take some action that results in that occurring, like transferring a domain to another site).

**Comment by simison** [comment] 2021-07-30 12:34
ID in the URL should already work fine wordpress.com/home/[ID] in Calypso — I've seen it used in some other cases, perhaps around checkout.

**Comment by dpasque** [comment] 2022-01-26 15:53
Moving to Ganon initially as the above investigation indicates this has to do with the navigation in the `/start` flow rather than specifically adding professional email.

**Comment by daledupreez** [comment] 2022-01-26 18:58
Might this issue be rendered obsolete by the new hero flow? The URL we build for the post-checkout redirect uses `siteId` and not `siteSlug`. (I was testing signup and checkout flows earlier today.)

Ganon should be able to confirm, but truly squishing the bug may depend on the rollout of hero flows.

**Comment by arthur791004** [comment] 2022-02-21 04:43
Yes, I think we can close this issue as we redirect to Hero Flow after onboarding flow. If the user picks the paid domain, the URL of Hero Flow will use `siteId` rather than `siteSlug`. So, we can always fetch the correct site data no matter the `siteSlug` is changed or not. Does it make sense?

**Closed as completed** 2022-03-01 01:28 UTC
Labels: Bug, [Pri] High, [Feature] Signup & Account Creation, Email, Triaged, Professional Email
