### ISSUE TITLE
Image block: Expand on Click won't save in Global Styles on Simple Sites

### ISSUE THREAD

**Issue by happychait** [Automattic/wp-calypso#82789] opened 2023-10-10 05:03 UTC
https://github.com/Automattic/wp-calypso/assets/1519466/8129e922-d01a-45b8-a921-523a5c963b42

### Quick summary

When "Expand on Click" toggle is enabled for Image block from the Styles panel, the choice is not saved and reverting to disabled state.the 

### Steps to reproduce

1. Open the Site Editor
2. Open the Styles panel from the top right
3. Search for the Image block
4. Enable the "Expand on Click" toggle in the Settings section
5. Hit Save and confirm

### What you expected to happen

The "Expand on Click" will remain active and apply to all the image blocks added to the page or post editor.apply

### What actually happened

The "Expand on Click" reverts to the disabled state.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Video of the problem

https://github.com/Automattic/wp-calypso/assets/1519466/dacb86a8-16f7-4b7a-a861-75dc61c4e6a8

**Comment by happychait** [comment] 2023-10-10 05:14
https://github.com/WordPress/gutenberg/pull/54509 mentions "Expand on Click" can be enabled via Global Styles.

**Comment by cuemarie** [comment] 2023-10-10 19:38
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – Could Not Replicate
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
I could replicate this on a Simple Site, but not on Atomic. Outside of Dotcom, the issue is not present either. All sites tested with Theme TT3 and Gutenberg v16.7.1

**Simple Site** - (Gutenberg: v16.7.1)

https://github.com/Automattic/wp-calypso/assets/27249804/6fbc0cfb-533a-4537-b9cc-e119a618ad92

📌 ACTIONS
- Triaged
- @Automattic/lego I see y'all are looking over Global Styles recently - is this something y'all could have a look at as well?

**Comment by Copons** [comment] 2023-10-11 13:00
I'm unfamiliar with the new property (which is about opening the image in a lightbox, and it works fine when used at an individual block level).

The GS API call contains this (among other things) as payload:
```json
{
  "settings": {
    "blocks": {
      "core/image": {
        "lightbox": {
          "allowEditing": true,
          "enabled": true
        }
      }
    }
  }
}
```

The feature then adds lots of `data` attributes to the image element.

Typically, this kind of thing is stripped by the Dotcom KSES (although it doesn't seem to be the case here, since they work at a block level? 🤔 ).

**Comment by dsas** [comment] 2023-10-13 09:54
> The GS API call contains this (among other things) as payload:

To rule out kses, you need to compare the response to the request - if the payload you mentioned isn't echoed back in the response it is very likely to be KSES ime

**Comment by Copons** [comment] 2023-10-13 12:33
> > The GS API call contains this (among other things) as payload:
> 
> To rule out kses, you need to compare the response to the request - if the payload you mentioned isn't echoed back in the response it is very likely to be KSES ime

@dsas Yes, that's what happens.

| Payload | Response |
| - | - |
| <img width="698" alt="Screenshot 2023-10-13 at 13 32 04" src="https://github.com/Automattic/wp-calypso/assets/2070010/fefd7c94-3e53-4d2b-a6af-bc7b377ffaa7"> | <img width="423" alt="Screenshot 2023-10-13 at 13 32 26" src="https://github.com/Automattic/wp-calypso/assets/2070010/f3e764c9-1706-4e38-9212-d8747340587c"> |

**Comment by autumnfjeld** [comment] 2024-01-17 21:10
I tested this on a few pages and image blocks and it consistently worked. 
* I toggle "expand on click" on, 
* I saved
* I tested in the front end and the image expanded
*  I went back to the editor, refresed the page
* Checked that the toggle was still set and it was

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/f66a093e-4189-49e3-9fe9-62af62e3837b)

I'm closing this.  @happychait   can you please test and confirm this feature works as you expect?

**Closed as completed by autumnfjeld** 2024-01-17 21:10 UTC
Labels: Bug, [Pri] High, Triaged, [Platform] Simple, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks, Bugs to watch
