### ISSUE TITLE
Editor: Link Existing Content Shows Feedback Content Type

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/wp-calypso#8151] opened 2016-09-20 05:46 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Click insert link
3. If site has feedback items from contact form submissions those will show in the list of existing content
4. Content is not public but will create link to something like https://<site>.wordpress.com/?post_type=feedback&p=<id>

#### What I expected
The feedback content type should be hidden from existing content

**Comment by lancewillett** [comment] 2016-10-24 19:12
Closing as duplicate of #4940

**Closed** 2016-10-30 06:45 UTC
Labels: Editor, [Type] Bug
