### ISSUE TITLE
Gutenberg Query Loop Block Ignoring Category Filters

### ISSUE THREAD

**Issue by alliebbush2** [Automattic/wp-calypso#63747] opened 2022-05-18 00:35 UTC
### Quick summary

When a user is in editor mode and adding the Query Loop Block, they are able to filter blog posts by category. The filter appears correct in editor but shows all posts (without the filter) on the live and updated page.

In editor:
![QueryLoop1](https://user-images.githubusercontent.com/97132910/168933199-e08ce81c-3aa9-4313-bc8d-43192c7f3009.png)

Live site:
![queryloop2](https://user-images.githubusercontent.com/97132910/168933359-5ef6bd89-fd17-4bbf-8ebe-3ed6015447e2.png)

### Steps to reproduce

1. Create a page and add the Query Loop Block
2. Add a filter using blog categories
3. Update and save page
4. Check posts displayed in editor vs posts displayed on live updated page

### What you expected to happen

You expect the posts to be filtered by category. You expect what is seen on the page editor to be visualized on live site page.

### What actually happened

Posts are not filtered. Editor displays filtered posts, live site does not.

### Context

Customer report here in Chat transcript: 35526823-chat
Please notify user when bug is resolved.

Gutenberg Repo Issue:  https://github.com/WordPress/gutenberg/issues/41067

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

**Comment by tanjoymor** [comment] 2022-05-18 00:49
Another customer report here 35526525-hc

**Comment by donalirl** [comment] 2022-05-18 02:27
#34677217-hc

**Comment by inaikem** [comment] 2022-05-18 02:42
Marking this as triaged since it's coming from Core. 

Please continue adding interaction IDs here. @Automattic/dotcom-pqa-group will track this from the Cross-Repo Watchlist.

Internally flagged here: p1652824408810669/1652822356.165019-slack-CBTN58FTJ

**Comment by ntsekouras** [comment] 2022-05-18 08:30
👋  I can reproduce in `.com` but not in a .org installation. Could this be related to some code atop of GB or core?

**Comment by ClassicRKR27** [comment] 2022-05-18 13:02
Another report here: 35534602-hc

Follow-up ticket here: 5224583-zd-woothemes

**Comment by zyousafi** [comment] 2022-05-18 15:32
Another report here: 34703465-hc

Follow-up ticket here: 5224850-zen

**Comment by MicBosi** [comment] 2022-05-18 16:31
Another report here: 35328769-hc

Follow-up ticket here: 5222967-zen

**Comment by ai2n** [comment] 2022-05-18 19:11
Report: 35029937-hc

Follow up: 5225622-zen

**Comment by filipanoscampos** [comment] 2022-05-19 10:37
Another case, here 5222201-zd-woothemes
Yet, in this user's case, the posts are listed according to the keyword.

One of the Query Loop Blocks is showing the correct post in the editor, but the wrong one on the published page.

They found a way to solve this temporarily but it isn't feasible to expect them to do this every time, since they have a large number of posts.

They took the time to create a copy of the page on a private page and leave the issue visible for us to study.
More details are in the ticket notes.

**Comment by rachelwinspear** [comment] 2022-05-19 11:02
Another report: 35543575-hc
Follow up: 5226975-zen

**Comment by jp-imagines** [comment] 2022-05-19 19:10
Another report in 18893651-hc. Suggested user try the Blog Posts block instead in the meantime.
Follow up: 5228595-zd-woothemes

**Comment by khristiansnyder** [comment] 2022-05-19 20:15
#5227455-zen

**Comment by wpshellbelle** [comment] 2022-05-19 20:20
5228560-zen

**Comment by Greatdane** [comment] 2022-05-20 01:34
35554314-hc (authors missing, related apparently)

**Comment by dragstor** [comment] 2022-05-20 13:18
35220622-HC

Posts are not filtered properly. I suggested using a Blog Posts block as a temporary solution.

**Comment by dermotmccoy** [comment] 2022-05-20 13:48
Experiencing the same issue.. on wordpress.com site. 
Using WordpressRecipeManager (WPRM) in combination with Query loop to filter on "keywords" category. 

Had issues previously as well with this, using the "Recipe" post type (from WPRM) and it resolved once I renamed the "keywords" category to "keys" - but that fix is no longer effective as of the last few days. (coinciding with release of Gutenberg 13.2.1 - which contained query loop improvements)

As above - Query filter - recipe post type - filtered on "Keywords" (not same as keyword!)
Editor shows correctly filtered recipe posts.. preview and published shows ALL published recipe posts (constrained by max items per page setting)

Happy to provide any additional information..

**Comment by dermotmccoy** [comment] 2022-05-21 05:44
> 

Loaded up the site today to investigate further.. and the problem has disappeared. - Query loops correctly showing the filtered posts again.. 
Jetpack shows no relevant updates in the last 8 hours that would push a code change for any WP plugins. 
Not sure where to look for diagnostic feedback - Maybe a host / memory issue that's resolved over time?

**Comment by dermotmccoy** [comment] 2022-05-21 11:08
> 

Loaded up the site today to investigate further.. and the problem has disappeared. - Query loops correctly showing the filtered posts again.. 
Jetpack shows no relevant updates in the last 8 hours that would push a code change for any WP plugins. 
Not sure where to look for diagnostic feedback - Maybe a host / memory issue that's resolved over time?

**Comment by arunsathiya** [comment] 2022-05-21 13:25
Some updates: 

- Gutenberg 13.2.2 fixed this bug: https://github.com/WordPress/gutenberg/issues/41135#issuecomment-1131923762
- Gutenberg 13.2.2 was pushed to WordPress.com sites (both simple sites and those with a plugin installed, AKA Atomic sites) at 1800 UTC on May 20, 2022: p1653069685523539-slack-CB0B2G43X

Closing this issue as it's now fixed. @Automattic/dotcom-pqa-group, could you handle the batch replies?

**Comment by arunsathiya** [comment] 2022-05-21 13:26
Thanks for checking, @dermotmccoy! You don't see the issue anymore because of the reason I have noted here: https://github.com/Automattic/wp-calypso/issues/63747#issuecomment-1133634092

**Closed as completed by arunsathiya** 2022-05-21 13:25 UTC
Labels: Bug, [Pri] High

**Comment by vajrasar** [comment] 2022-05-25 14:07
Hi everyone 👋 

Just a quick note to let you all know @Automattic/dotcom-triage-pa-group have finished following up with affected users reported in this thread. Thanks for the reports, please let us know here if you see any future recurrence of the issue.
