### ISSUE TITLE
Theme Showcase: clearly label and display uploaded third-party themes

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#40245] opened 2020-03-18 13:34 UTC
1. If a third-party theme has been uploaded, and one goes to **Design → Theme**, the only themes that show are "Recommended Themes":

![image](https://user-images.githubusercontent.com/32492176/76964724-c8df4c00-68e8-11ea-8b72-817eda62e0cd.png)

There should be a clear interface to show uploaded themes right off, as generally those are the ones a user will be looking for.

2. An astute user looking for their uploaded theme will see "Show all themes" and click that button. Their uploaded theme will show in an arbitrary section that includes uploaded and previously-used themes, but isn't labelled in any way:

![image](https://user-images.githubusercontent.com/32492176/76965117-65095300-68e9-11ea-8489-e876d4792806.png)

3. When I search for themes, there's no indicator differentiating between third-party uploaded themes and our own:

![image](https://user-images.githubusercontent.com/32492176/76964438-5ec6a700-68e8-11ea-9d32-f26e34b49a5e.png)

This confuses users as to who should be providing support for a theme (see, for example, 13652657-hc).

**Comment by lancewillett** [comment] 2020-03-18 22:37
Just to clarify, this only applies to Atomic sites, right?

One thing to discuss is how to invest more time on this screen versus nudging Atomic users to use WP Admin themes viewer instead. Similar to plugins. I don't have a quick or clear answer, yet the decision would help prioritize a change like this.

**Comment by tbradsha** [comment] 2020-03-19 12:37
Yep, only on Atomic sites. I'm all for pushing users to the WP Admin instead!

**Comment by mdrockwell** [comment] 2020-04-17 21:27
I ran into this issue when working with a user here: 20244748-hc

User thought they were using a theme built-in to WordPress.com, but they were using an uploaded theme instead. But since there is no indicator showing which themes are uploaded and which ones are built-in there was no way to show them that this was the case.

An indicator of some sort would also be helpful when we suggest users switch to a built-in theme, which can be helpful when troubleshooting atomic issues. If there is no indicator showing which themes are built-in its possible that they will switch to another uploaded theme instead.

**Comment by kspilarski** [comment] 2020-05-24 16:49
Same case for AT site 16654513-hc. 

- In Design > Themes, when "Show All Themes" is clicked, the list of uploaded themes appear first, followed by WordPress.com themes. 

- Also when searching for theme features / theme name (for example "news"), if the upload theme(s) have that feature, it will appear first in the theme search results as well. 

There is currently no distinction between uploaded themes (custom / third-party themes) and WordPress.com themes). 
 
<img width="1364" alt="Screen Shot 2020-05-24 at 6 39 19 PM" src="https://user-images.githubusercontent.com/36863633/82759676-2e6f1d80-9def-11ea-8c65-6ed72ab5eaa5.png">

**Comment by tbradsha** [comment] 2021-03-02 14:50
This remains unchanged. Once a user has uploaded third-party themes, has trouble, and asks "well, which themes are yours?", it's hard to explain which ones are WordPress.com themes and which ones are not without some differentiator.

**Comment by ianstewart** [comment] 2021-05-04 16:11
This seems like a regression and somewhat related to the following issues …

https://github.com/Automattic/wp-calypso/issues/51335

https://github.com/Automattic/wp-calypso/issues/51332

**Comment by kwight** [comment] 2021-05-17 17:32
Closing in favour of https://github.com/Automattic/wp-calypso/issues/52566

**Closed by kwight** 2021-05-17 17:32 UTC
Labels: Theme Showcase, Themes, User Report, [Pod] Design Selection, [Type] Enhancement
