### ISSUE TITLE
Users cannot restore a deleted site under /sites, ellipses (three dots) menu not available

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#97347] opened 2024-12-11 17:08 UTC
### Quick summary

Users are unable to see an option to restore deleted sites even though they are the owner and administrator on the site.

https://github.com/user-attachments/assets/6bb6f873-3f9b-4952-936f-eabd2717c371

This has been observed when restoring Dotcom accounts that were closed on accident. After reactivating these accounts, and verifying they are the owner of a deleted site and an administrator on the site (via Network Admin), they still cannot restore any site.

### Steps to reproduce

1. Visit https://wordpress.com/sites
2. Attempt to restore a deleted site

### What you expected to happen

The Restore option should be present

### What actually happened

The ellipses (three dots) menu was not available

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

### Logs or notes

Reported in 9163198-zd-a8c

**Comment by gabrielcaires** [comment] 2024-12-11 17:26
<img width="1390" alt="Image" src="https://github.com/user-attachments/assets/a3c7d20e-406c-4753-a6f7-1badae711961" />
@philnick206 I couldn't reproduce it.

I created a site with a business plan, and then I removed the plan and deleted the site.
Am I missing something?

**Comment by Robertght** [comment] 2024-12-11 17:32
@gabrielcaires I beleive the key detail here is to close the account. I just did with newinbox24. Feel free to test it with this. 

I've marked this as Triaged on our board.

**Comment by philnick206** [comment] 2024-12-11 17:39
Yeah I've had two users recently with this:

1. They've closed their account which caused the sites to be deleted automatically
2. Their account has been reactivated
3. They don't see the option to restore their sites (even though the site is showing as deleted on their /sites page)

**Comment by gabrielcaires** [comment] 2024-12-11 17:56
I just checked that the code is blocking the access because the user cannot manage a site, so the UI is blocking it the restore. 
Let me investigate this case.

**Comment by gabrielcaires** [comment] 2024-12-12 10:58
I asked for guidance p1733940529038679-slack-C029GN3KD it seems very related to the restore process and not the UI

**Comment by philnick206** [comment] 2024-12-15 21:03
Another case in 9178505-zd-a8c

**Closed as completed** 2024-12-18 10:19 UTC
Labels: Bug, [Pri] BLOCKER, Triaged, Customer report [LEGACY], [Product] WordPress.com, [Feature Group] Developer & Contractor Tools, [Feature] Multi-site Management, Groundskeeping, [Status] Escalated to Product Ambassadors
