### ISSUE TITLE
FSE: New sites on WordPress.com are duplicating pages

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#36016] opened 2019-09-06 01:43 UTC
To reproduce, create a new testing simple site. You will notice that there are multiple contact pages created and present in the nav. I'm not sure if this always happens, so try creating a few new sites.

**Comment by noahtallen** [comment] 2019-09-24 00:21
🤔 I definitely also saw this issue a couple weeks ago, but I'm unable to reproduce now.

- I tried a new user / site on the horizon flow. Doesn't duplicate pages, even after creating a new page, or deactivating and reactivating the theme.
- Tried the same thing when creating a new site under that same user. Can't reproduce here either.
- Tried replicating on my main account with a new site and enabled FSE after the fact. Didn't see it there either. 

Is there anything else we could think of which might reproduce this? 

For reference, this was added here: https://github.com/Automattic/wp-calypso/pull/35225/files

**Comment by vindl** [comment] 2019-09-24 14:53
Are we sure that these are created by FSE? We do have some basic checks to prevent duplication in place based on page title: https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/full-site-editing/templates/class-wp-template-inserter.php#L246

Looking at the above screenshot, our code shouldn't execute, so I'm wondering if there is anything else on Dotcom that is trying to create these pages?

**Comment by noahtallen** [comment] 2019-09-25 21:25
I did more testing today, but I'm still struggling to reproduce it in any reliable fashion. I have some possible ideas, but they're vague and I don't know what more to investigate in these areas:

1. Something in headstart is also creating these pages.
2. The SPT project has some code which switches out the home page. This page modification stuff could not be playing well with FSE. (I say this because I did see a case where the home page was duplicated.)

Additionally, a weird thing shows up on my blog report card during headstart.


Time | Who | Event | Object | Note
-- | -- | -- | -- | --
11m | noahtallen13 | headstart complete |   | {"target_blog_id":167273614,"theme":"pub\/maywood","locale":"en","save_existing":false,"images":[],"vertical":"p30v1","segment":1,"annotation":null,"site_contact_info":{"title":"","site_tagline":"","email":"","phone":"","address":""},"site_style":""}
11m | noahtallen13 | delete page | 1 | https://noahtallentest13.wordpress.com/about/
11m | noahtallen13 | headstart begin |   | {"target_blog_id":167273614,"theme":"pub\/maywood","locale":"en","save_existing":false,"images":[],"vertical":"p30v1","segment":1,"annotation":null,"site_contact_info":{"title":"","site_tagline":"","email":"","phone":"","address":""},"site_style":""}

An "about" page is deleted. Why? I have no idea. I certainly didn't trigger it in the UI. I can't find the code which causes that. It may happen on non-FSE sites too, but I'm not sure.

My recommendation is to close this issue for now after a few other folks go through the horizon flows and verify that they cannot reproduce. If folks are reproducing reliably with the latest master version of FSE, please give detailed steps so we can track it down!

**Comment by vindl** [comment] 2019-09-26 15:48
I've gone through the FSE test flow on Horizon a couple of times today and was not able to reproduce the issue. The pages are created as expected for me and I was never able to get into a state with duplicates.

<img width="427" alt="Screenshot 2019-09-26 at 17 45 51" src="https://user-images.githubusercontent.com/1182160/65703717-8a797a80-e085-11e9-8f23-0a87b6a9afde.png">

> My recommendation is to close this issue for now after a few other folks go through the horizon flows and verify that they cannot reproduce. If folks are reproducing reliably with the latest master version of FSE, please give detailed steps so we can track it down!

Agreed. I'm going to close this as not reproducible until we either get detailed steps or an existing site create with latest version of FSE code that has duplicate pages so we can use it as a starting point for investigation.

**Closed** 2019-09-26 15:48 UTC
Labels: [Pri] BLOCKER, [Type] Bug
