### ISSUE TITLE
Navigating to `/settings/:site` or `/sites/:site` results in broken experience

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#17584] opened 2017-08-29 00:30 UTC
For a user with multiple sites, navigating to `/settings/:site` or `/sites/:site` results in a site selector that does nothing upon picking a site:

![calypso-navigation-bug](https://user-images.githubusercontent.com/227022/29799098-f6d79726-8c26-11e7-97a9-ded771cf57f7.gif)

I experienced this error when mistakenly navigating to `/settings/:site` instead of `/settings/general/:site` by editing the URL, then learned that `/sites/:site` is similarly broken.

Since `/settings`, `/settings/general`, and `/sites` all work without a site, we should probably make sure they do something reasonable with `/:site` appended to them as well.

**Comment by lancewillett** [comment] 2017-09-06 16:43
Good find —

A user-centric note for context, most people probably won't type in URLs like we know how to do, though.

**Comment by mikejolley** [comment] 2017-09-14 23:31
This is a duplicate of https://github.com/Automattic/wp-calypso/issues/11543

I submitted an idea for a fix here https://github.com/Automattic/wp-calypso/pull/18053

**Closed by mikejolley** 2017-09-14 23:31 UTC
Labels: Sites, [Pri] Low, [Type] Bug, [Type] Good First Change
