### ISSUE TITLE
Unable to select theme in Design Picker during new site setup

### ISSUE THREAD

**Issue by ironprogrammer** [Automattic/wp-calypso#80512] opened 2023-08-11 17:24 UTC
### Quick summary

While choosing a theme during a new site setup, clicking "Continue" on the selected theme's preview had no effect.

### Steps to reproduce

1. Start on the "Pick a design" screen (`https://wordpress.com/setup/site-setup/designSetup?siteId=...`).
2. Select a theme.
3. On the preview screen, click the "Continue" button.

### What you expected to happen

The theme should be selected and the setup flow should navigate to the next step.

### What actually happened

Clicking the "Continue" button did not seem to have any effect.

Checking the browser's JS console, the following error appeared with each attempted click:
```sh
Unhandled Promise Rejection: NotFoundError: Invalid site specified
```

Each theme I tried resulted in the same issue, so I skipped theme selection and came back to it after completing the rest of the setup flow. The error did not return.

---

_Theme preview screen:_
<img width="1025" alt="SCR-20230811-jlpw" src="https://github.com/Automattic/wp-calypso/assets/824344/936d173d-28c2-4519-a0f6-994cb68b251c">

_Console error logged with click of "Continue" button:_
<img width="1020" alt="SCR-20230811-jmnd" src="https://github.com/Automattic/wp-calypso/assets/824344/7bbd855c-e7a8-43ec-aca3-cf39f133970d">

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

macOS Ventura 13.5, Safari 16.6

Encountered issue on 2023-08-03 at around 17:00 PDT.

**Comment by cuemarie** [comment] 2023-08-14 16:50
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I wasn't able to replicate this during triage - the `Continue` button worked right away for me. 

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/73c6a304-2246-4cc2-8b6f-114a39b51aba


📌 ACTIONS
- Assigned to @Automattic/lego 
- Anyone within Lego recognize the error that @ironprogrammer encountered above?

**Comment by rcrdortiz** [comment] 2023-09-07 12:20
I also can't reproduce the issue in production. Can you still reproduce the issue, @ironprogrammer? If so, could you please provide me with a list of all the steps you're taking, including how you arrived at the Design Picker?

**Comment by cuemarie** [comment] 2023-09-11 20:59
I chatted with @ironprogrammer internally - this site was set up with a Cloudflare domain - I wonder if that could have caused issue on the design page?

- The full URL for the design picker at this stage was `https://wordpress.com/setup/site-setup/designSetup?siteId=SITEID&ref=site-selector&notice=purchase-success`
- It appears they arrived at this step after creating the site & completing checkout for the Premium Plan + domain connection for the cloudflare domain
- Site has the `Build` intent

I'll see if I can get my hands on a cloudflare-registered domain to try to test that, just in case!

**Comment by cuemarie** [comment] 2023-10-02 23:38
📌 ACTIONS
- I haven't been able to track down a cloudflare-registered domain for further testing, so for now I'm closing this report as Not Reproducible. 
- If anyone runs into this same issue, though, please feel free to reopen and add details to your situation, and we'll have another look. Thanks!

**Closed as not planned by cuemarie** 2023-10-02 23:38 UTC
Labels: Bug, [Pri] Low, [Feature Group] Signup & Site Onboarding, Triaged, [Closed] Not Reproducible, [Feature] Design Picker, [Platform] Simple, [Product] WordPress.com
