### ISSUE TITLE
Latest Post Block's "Continue Reading" Links are Broken

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#40500] opened 2020-03-26 21:46 UTC
#### Steps to reproduce

1. Create a new page on WP.com
2. Add the Latest Post Block to your page
3. Enable content to show with just excerpts showing
4. Publish the page
5. View the page and you'll see  "Continue Reading" links that, when clicked on, simply reload the page rather than the post. 

#### What I expected

To be taken to the post when I click on  "Continue Reading"

#### Screenshot / Video

Example of problem here: https://testingannezazu.wordpress.com/ You'll see that the Blog Post block works just fine whereas the Latest Post Block's links don't.

Video of the problem: https://cloudup.com/c9-IjkuZcWv

#### Important note

When viewing the block in the editor, you see a "Read More"  link that correctly includes the URL. When viewing the page though, you see "Continue Reading"  which is broken. 

Within the editor: 
<img width="441" alt="Screen Shot 2020-03-26 at 2 43 03 PM" src="https://user-images.githubusercontent.com/26996883/77699774-400f8280-6f70-11ea-9b1b-65c90bca771d.png">

Viewing the page:
<img width="414" alt="Screen Shot 2020-03-26 at 2 43 17 PM" src="https://user-images.githubusercontent.com/26996883/77699776-4140af80-6f70-11ea-96b3-cc2f51d3075a.png">

#### Context / Source

#user-report #bug

**Comment by lancewillett** [comment] 2020-03-26 22:06
CC @coreymckrill 

Only on WordPress.com? How about a self-hosted site? If yes on self-hosted, look in Gutenberg repo to see if it is already logged.

If only WP.com, we can escalate to a dev team to look further.

**Comment by lancewillett** [comment] 2020-03-26 22:10
Upstream, props @coreymckrill :

- https://github.com/WordPress/gutenberg/pull/20541 from https://github.com/WordPress/gutenberg/issues/20511

**Comment by draganescu** [comment] 2020-03-30 09:38
This should be closed by #40566 20541

**Comment by andrewserong** [comment] 2020-04-20 07:45
I'm just re-opening this as we've had new reports of this issue. It sounds like it should be closed by the upstream Gutenberg changes, but I'm suspicious that we might possibly need to make changes in our Varia theme `excerpt_more`. I'll do some more digging this week, but let's keep an eye on it through the next Gutenberg version upgrade testing.

**Comment by sophiegyo** [comment] 2020-04-20 07:49
Per the Slack thread in gutenberg-on-dotcom, a few screenshots of what's up:

Karuna in the Customizer, showing "Continue Reading" originating from the Latest Posts block, and "Read More" originating from Karuna:
https://d.pr/i/EEMTnQ

The "Read More" correctly links to the post URL, but the "Continue Reading" link just links to the page to which the block is added. Screenshot showing the relevant URL on hover:
https://d.pr/i/6ylkRk

Varia doesn't have an inbuilt "Read More" link, so it uses the one from the Latest Posts block. Customizer screenshot:
https://d.pr/i/no7xUb

The PR which should hopefully help:
https://github.com/WordPress/gutenberg/issues/20510

**Comment by alshakero** [comment] 2020-04-20 18:08
I just checked and it seems this [@draganescu's commit](https://github.com/WordPress/gutenberg/commit/59324b9a8f95d68330aee110f3814a090a75cb1b) does fix the issue. 

It's reproducible in production because Gutenberg 7.9.0 (where this commit lives) is not yet released.

**Comment by supernovia** [comment] 2020-04-21 03:37
https://wordpress.com/forums/topic/read-more-faulty-link/ - another here.

**Comment by darnelldibbles** [comment] 2020-04-21 21:23
Several more reports in the forums as well:

https://wordpress.com/forums/topic/link-to-continue-reading/#post-3473495
https://wordpress.com/forums/topic/continue-reading-21/#post-3473497
https://wordpress.com/forums/topic/view-all-posts-button-leads-to-my-home-page/#post-3473509

**Comment by mdrockwell** [comment] 2020-04-24 17:34
Another report of this here: 2912887-zen

**Comment by thabotswana** [comment] 2020-04-28 08:48
Another report: 2917992-zen

**Comment by mdrockwell** [comment] 2020-04-28 17:32
Another report: 2926091-zen

**Comment by simranjeetkaur10** [comment] 2020-05-01 13:06
Another report: 2935375-zen

**Comment by Addison-Stavlo** [comment] 2020-05-04 19:54
I verified this is working on Gutenberg 8.0, we should be able to roll that update out in the next couple days.  😄

**Comment by thabotswana** [comment] 2020-05-05 08:22
Just adding this report here so we can follow up with user when the fix is deployed:

2940123-zen

**Comment by Addison-Stavlo** [comment] 2020-05-05 21:18
This fix should be live on simple sites.  I will update and close once this gets shipped for atomic as well.

**Comment by sirreal** [comment] 2020-05-06 10:55
This should be fixed for all WordPress.com sites with Gutenberg 8 deployed everywhere.

See p9o2xV-Rm-p2

**Closed by sirreal** 2020-05-06 10:55 UTC
Labels: Blocks, Core fix needed, Editor, [Type] Bug

**Comment by mdrockwell** [comment] 2020-05-06 17:33
I've replied to the user reports of this to let them know that this fix has been released.
