### ISSUE TITLE
Combined Cards: author links in tag streams lead to /read/blogs/undefined

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#12134] opened 2017-03-14 19:58 UTC
Steps to reproduce:

1. Go to a tag stream page where Combined Cards are active:<br>i.e. https://wpcalypso.wordpress.com/tag/ted-blog
1. Scroll until you see Combined Cards.
1. Click the author link for any Combined Card.

<strong>Result:</strong> the author links in tag streams lead to `/read/blogs/undefined`.

![screen shot 2017-03-14 at tue mar 14 1 34 00 pm](https://cloud.githubusercontent.com/assets/1119271/23919198/8e289886-08bb-11e7-8546-33cfa41c9c36.png)
<sup>Seen at https://wpcalypso.wordpress.com/tag/ted-blog using Chrome 56.0.2924.87 on Mac OS X 10.12.3.</sup>

![screen shot 2017-03-14 at tue mar 14 1 25 39 pm](https://cloud.githubusercontent.com/assets/1119271/23919311/01c44330-08bc-11e7-886b-f62db64fbbd3.png)
<sup>Seen at https://wpcalypso.wordpress.com/read/blogs/undefined using Chrome 56.0.2924.87 on Mac OS X 10.12.3.</sup>

Note: I found several cases where I saw the author link point to https://wpcalypso.wordpress.com/read/blogs/undefined however I also spotted at least one case where it appears to be working normally and I'm not sure what the difference is ([screenshot](https://cloud.githubusercontent.com/assets/1119271/23919182/7ff0bb18-08bb-11e7-820d-da460b339250.png) seen at https://wpcalypso.wordpress.com/tag/cnn after scrolling a bit).

#manual-testing

**Comment by bluefuton** [comment] 2017-03-14 20:11
@designsimply this sounds like it's possibly caused by the same thing as https://github.com/Automattic/wp-calypso/issues/12090. When you see this, is the site name in the header missing a link too?

**Comment by fraying** [comment] 2017-03-15 00:55
Also, is that one post getting repeated in your first screenshot, @designsimply? Is that still happening?

**Comment by bluefuton** [comment] 2017-03-15 16:24
Fixed in #12160 🎉

**Closed by bluefuton** 2017-03-15 16:24 UTC
Labels: Reader, [Type] Bug
