### ISSUE TITLE
Gutenboarding: Cannot "continue" to next step when site-name input is focused

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#38681] opened 2020-01-07 08:36 UTC
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenboarding/
2. Choose a vertical and click to enter site name (next step)
3. Set a site name (and keep the focus - don't click elsewhere)
4. Click `Continue ->` button to advance - it should do nothing

#### Browser / OS version

Safari & Chrome

#### What I expected

Continue to the next step/page (template selection).

#### What happened instead

No navigation in either browser. In **Chrome**: `Continue ->` button received a white background and border:

<img width="861" alt="Screenshot 2020-01-07 at 10 24 43 AM" src="https://user-images.githubusercontent.com/1705499/71879958-f4e78f80-3137-11ea-9170-810e9facfd5d.png">

#### Screenshot / Video

![Kapture 2020-01-07 at 10 31 15](https://user-images.githubusercontent.com/1705499/71880433-ffeeef80-3138-11ea-83e3-c273b21a9cf8.gif)

**Comment by simison** [comment] 2020-01-09 11:09
Ah, sorry I missed this. I think this is duplicate of https://github.com/Automattic/wp-calypso/issues/38720 — I'll leave this open and close that one.

**Comment by p-jackson** [comment] 2020-01-12 21:34
The issue with the border around the continue button appears to be fixed in the latest version on `wpcalypso`. But the overarching issue of being tricky to click Continue still exists. See https://github.com/Automattic/wp-calypso/pull/38721#issuecomment-573459485

**Comment by Addison-Stavlo** [comment] 2020-01-20 20:26
I have been playing around with duplicating this and I was having some issues in reproducing this consistently until I figured out it was having to do with how fast i was releasing my mouse-click.  Essentially the 'Continue' button is moving too far vertically in this circumstance and if the mouse-click is released after it has moved too far, clicking the link will not register.

If I click/release after some delay the link will not work, if I click/release as quickly as possible then the link will work.  (Gif below shows 2 attempts with the former, followed by 1 attempt of the latter)
![click_release](https://user-images.githubusercontent.com/28742426/72754135-fcc21d80-3b94-11ea-9e91-37f950a2f4dc.gif)


There are 3 potential directions I can think of for how to fix this issue:

1.  Change the behavior of the footer that contains the Continue button to have a vertical position that is more fixed in vertical height.   That way the Continue button just does not move up/down vertically when steps are selected/deselected.  The downside is this would feel less fluid without the Continue button adjusting along with the height above it.

2.  Add some vertical padding to the bottom of this Continue button to essentially create a 'buffer zone' so that even when the button moves up, the cursor is still within the boundary of its padding when released.  It seems a bit odd to keep some phantom padding to ensure we can click the button, but it will retain the fluid feel.

3.  Always have an 'active' step.  Remove the function that increments the step # from the last step (currently set to the `onBlur` of the site-title input).  This will force site-title to remain as the active step when the input is unfocused instead of moving to the "next" (currently non-existant) step in the stepper-wizard, causing it to shrink in size and move the Continue button too far vertically when attempting a click.  As long as there is an active step, the continue buttons vertical position should not change enough to have an issue.  The downside here is that being able to have no active step gives a nice finalized feeling before Continuing onto the next page.

Any thoughts?

**Comment by andrewserong** [comment] 2020-01-21 00:36
Just my 2 cents (and a designer might have a better insight here than me!), but I like option 1 — the moving Continue button feels a bit awkward to me, like it's asking me to try to chase it with my mouse 😄. Keeping the onboarding block questions section big enough so that it doesn't change the position of the footer seems like it might help the Continue button feel a bit more "solid".

**Comment by simison** [comment] 2020-01-21 07:59
If removing the animation between those two questions fixes the issue, we could do that for now. 

Here's an older PR to do that — it just needs to be reviewed and merged: https://github.com/Automattic/wp-calypso/pull/38704

It was already Okayed by @olesyabrk at https://github.com/Automattic/wp-calypso/issues/38687#issuecomment-571667627 so we can just go ahead and do that.

We'll revisit the intent gather design in later point again, at which point we can improve it some other ways, perhaps even add the animation back.

**Comment by sirreal** [comment] 2020-01-21 09:54
> until I figured out it was having to do with how fast i was releasing my mouse-click

😮 You have a fast click. I hit this almost every time 😆 

I'd like an approach similar to https://github.com/Automattic/wp-calypso/pull/38704 that removes these scaling transitions altogether.

The PR was closed because there are still some design iterations going on, but I think removing the scaling is an improvement. @dwolfe @olesyabrk would you be opposed to removing the question scaling transitions here?

![scaling](https://user-images.githubusercontent.com/841763/72794383-36019880-3c3c-11ea-9e55-224ebae56840.gif)

**Comment by dwolfe** [comment] 2020-01-21 16:45
No objection, go for it.

**Closed** 2020-01-22 16:51 UTC
Labels: [Goal] Gutenboarding, [Goal] Onboarding, [Status] Needs Design Review, [Type] Bug, good first issue
