### ISSUE TITLE
Editor: Drag and Drop Image Issue

### ISSUE THREAD

**Issue by clickysteve** [Automattic/wp-calypso#508] opened 2015-11-23 14:32 UTC
This problem is one that I've experienced for a while - both on the Mac Desktop App, and online, but not been able to figure out how to reproduce until now.

If you drag an image onto the post area where it highlights blue, but then release the file without completing the action, it gets stuck on the blue dropzone.

<img width="1402" alt="screen shot 2015-11-23 at 14 27 35" src="https://cloud.githubusercontent.com/assets/6227598/11338945/dc34fd84-91ee-11e5-94ef-42895f9ac847.png">

This might sound like an uncommon situation, but it happens frequently if you have a photoblog, and drop the images into Photoshop or something whilst composing the post. For example, you have Finder open, Photoshop, and Calypso. You drag an image from Finder down to the Photoshop icon, but it goes across the Calypso content area, triggering the blue dropzone. Since you release the image on Photoshop, without completing the drop in Calypso, it gets stuck. The only way to fix the issue is to refresh the page.

Here's a video that demonstrates what happens better:

https://cloudup.com/cvw34v2Suix

I was on a train at the time, so that explains the slow connection :) - let me know if you've any questions!

**Comment by aduth** [comment] 2015-11-24 05:26
Thanks for the report! This is a duplicate of #359 and is slated to be fixed by #550.

**Closed by aduth** 2015-11-24 05:26 UTC
Labels: Editor, Media, [Type] Bug
