### ISSUE TITLE
Onboarding: Payton screenshot looks off in design selection step.

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#61391] opened 2022-02-22 23:46 UTC
### Quick summary

I just noticed this is how Payton looks in the design selection step:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/4550351/155238340-4529af7b-ecd6-482d-9263-dd6d5ced07df.png">

I checked the demo site and it looks fine.

cc @p-jackson @Automattic/ganon 

### Steps to reproduce

1. Start at wordpress.com/start
2. Pick "Write" or "Build" during the intent step, and then select "View designs" to see themes.
3. Find Payton in the lineup (should show up under Blog). Note the screenshot looks off - the site is too narrow.

### What you expected to happen

I expected the Payton design to fill full width of the screenshot.the 

### What actually happened

The design looks very narrow.

### Reproducibility

Consistent

**Comment by fushar** [comment] 2022-02-28 08:56
Raised PR here: D75779-code

**Comment by alaczek** [comment] 2022-03-11 06:37
Just a quick note that the same thing is happening now with the preview of Bennett, Dorna, and Arbutus.

**Comment by arthur791004** [comment] 2022-03-11 10:01
I think the problem is coming from https://github.com/WordPress/gutenberg/blob/82521331ea679898c5fa8b21fa015d9b174023ca/lib/block-supports/layout.php#L56

The `contentSize` is `684px` and the `wideSize` is `1194px`. If we don't set the layout to wide, the default max width is only `684px`. So, we have to set the layout to wide or full to make the design look better.

**Comment by arthur791004** [comment] 2022-03-11 10:33
~I think the problem is coming from [here](https://github.com/WordPress/gutenberg/blob/9b0e9e411df3db10772ddb67d44d380bd3007934/lib/block-supports/layout.php#L215)~

~When we restore the group inner container, we don’t set the `alignwide` or `alignfull` so that the content size is only `684px` and it looks narrow than original one.~

## UPDATE

the issue contains two problems. The one is solved by D75779-code. But the other one is more difficult as [Gutenberg changes to use “wp_unique_id()” instead of “uniqid()” to generate CSS class names](https://github.com/WordPress/gutenberg/commit/e42655c11983ce9a2a3882b2ccd1a480bea62441#diff-324697e41855298e2f2c74b078f174e0cbc9075cef736ce9c1e2c169bf64652eL153) and it makes the class names might not be unique when we generate the theme preview so that the style is broken.

**Comment by fushar** [comment] 2022-03-14 02:29
We found the root cause. It is explained in this internal docs: pbxlJb-1i1-p2. We'll implement a temporary fix.

**Comment by fushar** [comment] 2022-03-16 02:29
The fix has been shipped! 🎉

**Closed as completed by fushar** 2022-03-16 02:29 UTC
Labels: Bug, [Pri] High, Triaged, [Feature] Design Picker
