### ISSUE TITLE
Post editor scrolls to the top when adding a link

### ISSUE THREAD

**Issue by janicecchua** [Automattic/wp-calypso#27380] opened 2018-09-21 20:43 UTC
#### Steps to reproduce
1. Create a long post
2. Scroll down and choose a text to add link
3. Insert link

#### What I expected
After highlighting the item and inserting the link, the modal window should pop up on the exact same place where the item is on.

#### What happened instead
After clicking on the Insert/edit link button, the modal window scrolls up to the top most part of the post. This could be inconvenient to the user if the user is inserting multiple links.

#### Screenshot / Video
![bug](https://user-images.githubusercontent.com/42043956/45904406-88039580-be1f-11e8-8977-e47e88f69818.gif)

**Comment by chrisfromthelc** [comment] 2018-09-21 22:33
I have a user experiencing the same issue, but with videos and images as well. I tested in Firefox, Safari and Chrome on OSX and was able to duplicate it as well.

**Comment by kriskarkoski** [comment] 2018-09-22 23:50
This is a duplicate of this issue: https://github.com/Automattic/wp-calypso/issues/27226

I will update the title there to indicate it's not just affecting Windows.

**Closed by kriskarkoski** 2018-09-22 23:50 UTC
