### ISSUE TITLE
Domain Picker: Make domain picker resilient against potential Domain Suggestions API failure. 

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#43503] opened 2020-06-20 05:03 UTC
I discovered that the 2nd step domains page could blank out when the domain suggestions API fails.

Granted, my testing environment is a little botched, because I'm pointing `public-api.wordpress.com` to my broken sandbox where php logs are being outputted inside http response causing malformed JSON response. 

**However, I think it's an opportunity to test the resilience of the client-side when server-side API fails.**

![image](https://user-images.githubusercontent.com/1287077/85192626-87818280-b2c3-11ea-9d85-7a7c75894e5b.png)

The `wpcomRequest()` function as used in `packages/data-stores/src/domain-suggestions/resolvers.ts` could return an empty string when API request fails.

When this empty string lands on to places like `domainSuggestions?.map()`, the optional chain operator `?` only checks against`undefined` and `null` when transpiled, that's why an operation like `"".map()` breaks, and the domain picker component fails to render.

![image](https://user-images.githubusercontent.com/1287077/85192637-90725400-b2c3-11ea-8138-45c0fe03dbd4.png)

Another issue I had was instances where `wpcomRequest()` fails without making any network request, this also returns an empty string. I could only replicate this when running e2e test. This empty string occurrence happens inside `useOnLogin()` hook. 

![image](https://user-images.githubusercontent.com/1287077/85192825-42aa1b80-b2c4-11ea-84a8-b2796c1e54dd.png)

I can't explain this behaviour yet but one thing to keep in mind is that e2e test is running as guest (at least initially). It may or may not be the cause of this issue p1592573181429200-slack-CNMU1UHHB (where some user on Chrome iOS don't get pass 2nd step), but at least we can eliminate one possible point of failure.

If the domain picker doesn't blank out completely, at least user can still continue to search for domains, and who knows, maybe the API request only fails the first time, but not the second time around on unstable network.

**Comment by yansern** [comment] 2020-07-30 06:22
Domain Suggestions API also break with unicode characters, which makes this issue a bit more important now.
p1596089767098600-slack-CNMU1UHHB

**Comment by lsl** [comment] 2020-07-30 06:28
> which makes this issue a bit more important now.

To emphasize this a bit more, anyone coming through with a site title from the first step that utilizes non latin characters will hit a stalled state where domains don't finish loading.

You can continue but I'm sure this confuses some people.

![image](https://user-images.githubusercontent.com/811776/88888409-9cb5dd80-d281-11ea-9e26-f62ec9b3e502.png)

**Comment by alshakero** [comment] 2020-09-02 13:07
This is a duplicate of https://github.com/Automattic/wp-calypso/issues/44421

**Comment by ciampo** [comment] 2020-09-02 13:10
> This is a duplicate of #44421

@alshakero I thought that #44421 was more related to domain availability checking, which is slightly different from the domain suggestion errors in this issue?

cc @yansern

**Closed** 2020-09-23 12:42 UTC
Labels: Domains, [Goal] Gutenboarding
