### ISSUE TITLE
WordPress.com on Atomic: Expand blocked plugin installation prevention to plugin details iframe/page

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#54520] opened 2021-07-13 17:17 UTC
Users can install blocked plugins via the WP-Admin plugin details iframe/page

This is more of a low priority feature request to resolve inconsistent behavior than a full bug but filing as a bug.

---

On WordPress.com on Atomic, we [block certain plugins](https://wordpress.com/support/incompatible-plugins/) from being installed via `wpcomsh` and Calypso.

- wpcomsh: wpcomsh.php starting @ L128 
- Calypso:  https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/plugin-compatibility.js

Users that attempt to install a blocked plugin will generally be met with an unsupported message like this one.

![image](https://user-images.githubusercontent.com/4887830/125495461-3c5a3b12-449c-4f03-b28f-4748d085e97b.png)

However, if the user clicks on the plugin's title -- which opens a plugin details page like `/wp-admin/plugin-install.php?tab=plugin-information&plugin=wp-reset` -- an `Install Now` button is present. 

![image](https://user-images.githubusercontent.com/4887830/125495615-ad0d9c5e-4db4-4850-8bde-9a3e2756f7a4.png)

This allows the plugin to be installed and, very briefly, deactivated.  `wpcomsh` will quickly deactivate it but sometimes might leave it activated long enough for a user to use it in a way that we don't want.

Internal example: p9F6qB-7b0-p2#comment-40962

### Steps to reproduce the behavior

1. Go to site's WP-Admin > Plugins > Add new
2. Search for a plugin like WP Reset
3. Click on title to see plugin details iframe or visit the page's content directly at `/wp-admin/plugin-install.php?tab=plugin-information&plugin=wp-reset`
4. See `Install Now` button.

#### What I expected to happen

Not to be able to install the blocked plugin.

#### What actually happened

Install Now button present, installs plugin.

### Context

Internal request, p9F6qB-7b0-p2

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Low priority but possible on all Atomic sites.

**Comment by kosiew** [comment] 2021-07-14 05:51
Thanks @JoshuaGoode for catching and reporting this.

Managed to replicate.

**Comment by cometgrrl** [comment] 2022-08-01 22:29
A lot has changed since this was filed; let's recheck it.

**Comment by cpapazoglou** [comment] 2022-10-10 13:04
I can still reproduce this. BUT, if a user has used a direct link to reach the `/wp-admin/plugins.php` page ( which is currently overridden by the Calypso `/plugins` ) and clicks to an unsupported plugin and then installs it it wouldn't make any difference from directly uploading the same plugin. I mean we cannot do anything to avoid the plugin getting installed. What we can do - and seems working as expected - is deactivate it and disallow activations.

This is now happening in wpcomsh `class-jetpack-plugin-compatibility.php#L167` using `add_action( 'load-plugins.php', array( $this, 'check_plugin_compatibility' ) );` and I don't see any way for a user to use that plugin since `'load-plugins.php'` runs on almost every call to WordPress before rendering anything.

I will close this for now.

**Closed as completed by cpapazoglou** 2022-10-10 13:04 UTC
Labels: Bug, [Pri] Low, [Feature] Plugins, Triaged, Marketplace
