### ISSUE TITLE
Gutenberg: fix auth corner cases

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#29047] opened 2018-12-04 02:31 UTC
@rralian reported that after seeing an open tab try to confirm for 2FA, the open Gutenberg editor tab stopped autosaving/saving correctly. After updating 2FA, the tab didn't recover. (Other fresh tabs worked okay).

First steps here are for folks investigating to reproduce and come up with basic reproduction steps.

**Comment by cuemarie** [comment] 2022-10-04 23:17
Hey @cometgrrl ! Just to check in since this report has been stale for a while and isn't an HE report - would you like this to still go through a triage run from HEs? Or would it help to just move this through to the Quality Squad so they can take a look at it from here?

**Comment by cometgrrl** [comment] 2022-10-05 20:11
@cuemarie Either would work for me. We'll be going through a lot of older issues, not all HE reported, and making sure they are triaged appropriately. If PAs can help with this, that would be awesome, but I also understand if you don't have the bandwidth.

**Comment by cuemarie** [comment] 2022-10-06 01:02
@cometgrrl Got it, thanks for that context! We're in decent shape right now, so I'll move this back to `Needs Triage` to see if we can help put together some reproduction steps here.

**Comment by kavyagokul** [comment] 2022-10-06 13:11
📌 SCRUBBING : RESULT
- Tested on P2 -  Could Not Replicate 
- Tested on Simple -  Could Not Replicate 
- Tested on AT -  Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tried to repro by making all kinds of 2fa changes in a tab while a block editor was open in Calypso, in another tab. Unable to reproduce on Simple and atomic. 

📌 ACTIONS
- Await author feedback
- Closed as could not replicate (please reopen the issue reoccurs)


📌 Message to Author
- I've tested this on a personal account as well, and haven't been able to reproduce. The bug is from 4 years ago, so it's possible that it doesn't happen anymore.

**Closed by kavyagokul** 2022-10-06 13:11 UTC
Labels: [Type] Bug, [Pri] Normal, [Goal] Gutenberg
