### ISSUE TITLE
Redesign Earn emails

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#42802] opened 2020-05-29 14:46 UTC
## Description

Following up from our last retrospective folks expressed interest in revisiting Earn emails and making them more useful and consistent!

@danhauk and @sixhours are already looking at emails for recurring memberships, but we’d like to help prioritize and queue up design work for all others like when someone has their first sale, the monthly reports, and so on.

Related Issues (feel free to edit to add more)
- [ ] Receipt Email https://github.com/Automattic/wp-calypso/issues/43183
- [ ] Refund Email https://github.com/Automattic/wp-calypso/issues/41619
- [ ] Subscription Cancellation https://github.com/Automattic/wp-calypso/issues/41611
- [ ] Subscription Expired https://github.com/Automattic/wp-calypso/issues/41616

See D44056-code

**Comment by gwwar** [comment] 2020-05-29 23:29
Also noting the comment from @artpi: 

This could be a good opportunity, to include this in the designs:

https://github.com/Automattic/wp-calypso/issues/42275 

I don’t think we should treat the subscriber-facing and merchant-facing emails the same. We have 2 series:

One is with all the subscription lifecycle and it is sent to subscriber. 

Second one is for the merchant.

I think it's best to think of them separately, since they have completely different purposes and audiences

**Comment by sixhours** [comment] 2020-06-02 18:45
Visuals of the emails I'll look at updating to use new colors/fonts/font sizes.

<img width="634" alt="Screen Shot 2020-06-02 at 1 51 00 PM" src="https://user-images.githubusercontent.com/2124984/83553396-22631a00-a4d9-11ea-8e67-6fea9c359fd1.png">

<img width="637" alt="Screen Shot 2020-06-02 at 1 54 02 PM" src="https://user-images.githubusercontent.com/2124984/83553403-255e0a80-a4d9-11ea-9d42-ec3181a53e1c.png">
(How does this email come into play for the merchant? It looks subscriber-facing.)

<img width="631" alt="Screen Shot 2020-06-02 at 2 33 46 PM" src="https://user-images.githubusercontent.com/2124984/83556552-19c11280-a4de-11ea-8433-c04f71ce47f6.png">

<img width="638" alt="Screen Shot 2020-06-02 at 2 40 48 PM" src="https://user-images.githubusercontent.com/2124984/83557327-7113b280-a4df-11ea-84fa-a5e70332e6ce.png">

<img width="649" alt="Screen Shot 2020-06-02 at 2 39 22 PM" src="https://user-images.githubusercontent.com/2124984/83557365-84268280-a4df-11ea-919a-6091035694b9.png">

Some of these aren't listed in the Memberships doc. Are any of the above visuals invalid/no longer used for whatever reason? /cc @danhauk @artpi

**Comment by artpi** [comment] 2020-06-08 15:13
> Some of these aren't listed in the Memberships doc. Are any of the above emails invalid/no longer used for whatever reason? 

The "Your verification code" email is not used anymore. Context: p8hgLy-2k2-code

**Comment by danhauk** [comment] 2020-06-12 20:43
Here's some mockups I've been working on that @sixhours can pick up for implementation next week. Feel free to make any tweaks to any of these.

**First sale**
<img width="700" alt="First sale" src="https://user-images.githubusercontent.com/448298/84544526-746f2100-accb-11ea-9a82-1b7c3f9b4454.png">

**New subscriber**
Similar to the "first sale" email above but focused on the subscriber.
<img width="700" alt="New subscriber" src="https://user-images.githubusercontent.com/448298/84544557-8650c400-accb-11ea-9ae3-c1df00805d11.png">

**Issue with Stripe**
<img width="700" alt="Unable to process subscription" src="https://user-images.githubusercontent.com/448298/84544609-9e284800-accb-11ea-8338-f99621ca487b.png">
@artpi Is this one sent each time someone tries to subscribe and the issue isn't fixed? That may affect the copy here.

**Stripe account**
<img width="700" alt="Stripe account" src="https://user-images.githubusercontent.com/448298/84544739-df205c80-accb-11ea-9b81-f46983a272f3.png">

**Comment by danhauk** [comment] 2020-06-12 20:48
@artpi For the monthly sales report, is each item listed for each subscription or are they bundled. For example, if "Subscription A" has 3 subscribers will it be listed 3 times as separate line items or just have one line item with 3x the subscription amount?

I'd love to be able to group things in the sales report to make it easier to read. Especially now that we will have donations in addition to regular payments. Here's what I'm thinking:

<img width="548" alt="image" src="https://user-images.githubusercontent.com/448298/84545029-784f7300-accc-11ea-86b5-deddd68cb40a.png">

**Comment by sixhours** [comment] 2020-07-13 18:33
I've updated four of the emails based on the new designs here: https://code.a8c.com/D44357

**Comment by cathymcbride** [comment] 2021-02-15 18:20
Looks like this is done. Closing.

**Closed by cathymcbride** 2021-02-15 18:20 UTC
Labels: Design Needed, Earn, Email
