### ISSUE TITLE
Help Center: Add Media help doesn't display 

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#72791] opened 2023-01-30 20:03 UTC
### Quick summary

When clicking the Add Media help item under the Help Center for the Media Library, a blank box displays. The other help items display help text as expected.
AT Site
Theme: Snaps

5849867-zen

### Steps to reproduce

I can't reproduce this on my own test AT site but am reporting in case it has been reported by others.

On the affected site it happens by following these steps:

1. Go to Media Library
2. Click the Help Center icon
3. Select Add Media from the list of options

### What you expected to happen

Expected to see the Add Media help text

### What actually happened

Saw a blank box
![Help Center](https://user-images.githubusercontent.com/32983813/215583005-6487718c-bc03-4e19-af02-37385defde9c.png)

### Impact

One

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment] 2023-03-21 18:18
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Replicated
- Tested on AT: Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Looks like the `Add Media` link is displaying a Private Support doc, which is likely why a user couldn't see it.
     - The icon to open in a new tab opens the [Image Block WordPress.com guide](https://wordpress.com/support/wordpress-editor/blocks/image-block/)

Not sure where/how these links are set up, but it appears this link needs to be updated to direct to a public doc, such as the Image Block guide. 

<img width="936" alt="Markup 2023-03-21 at 11 14 42" src="https://user-images.githubusercontent.com/27249804/226704286-583bff6c-a9a3-4c79-b1a2-301abcc598ba.png">


📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by heavyweight** [comment] 2024-04-16 13:01
This is no longer reproducible for me

**Closed as completed by heavyweight** 2024-04-16 13:01 UTC
Labels: Bug, [Pri] Normal, Triaged, [Feature] Help Center, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic
