### ISSUE TITLE
Editor: Word lookup issues in OS X

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#317] opened 2015-11-20 20:10 UTC
Combining four issues with the 3-finger word lookup shrtcut in OS X into this one issue:

Word lookup in title in Chrome:

> What I Did: 
> - Three-finger tap on word in title to look up the word in the built-in OS X dictionary
> 
> What I Expected:
> - To see the word highlighted and the definition in a popover
> 
> What Actually Happened:
> - The word was highlighted offset and the wrong size (Chrome)
> - The word was highlighted corrected (Safari)
> 
> ![dictionary in title](https://cloud.githubusercontent.com/assets/2098816/9554274/cb9dde14-4d92-11e5-80be-5124c88660f5.gif)

Word lookup in post body in Chrome:

> What I Did:
> - Three-finger tap on word in post body to look up the word in the built-in OS X dictionary
> 
> What I Expected:
> - To see the word highlighted and the definition in a popover 
> 
> What Actually Happened:
> - The word is show highlighted offset (this only happens in Chrome, though Safari has its own separate issues that will be recorded in another issue)
> 
> ![dictionary in content - chrome](https://cloud.githubusercontent.com/assets/2098816/9554451/038588d0-4d94-11e5-8dc7-b56d2373da78.gif)

Word lookup in post body in Safari:

> What I Did:
> - Three-finger tap on word in post body to look up the word in the built-in OS X dictionary
> 
> What I Expected:
> - To see the word highlighted and the definition in a popover
> 
> What Actually Happened:
> - Nothing
> - In order to look up word using 3-finger tap, had to select word first and then 3-finger tap (this is not normal behavior for Safari)
> 
> ![dictionary in content - safari](https://cloud.githubusercontent.com/assets/2098816/9554526/77ac61c0-4d94-11e5-8263-4a9ca76c30dd.gif)

Word lookup in title with short browser:

> What I Did:
> - Three-finger tap on word in title to look up the word in the built-in OS X dictionary
> 
> What I Expected:
> - To see the word highlighted and the definition in a popover
> 
> What Actually Happened:
> - Things only work if the browser window is tall enough
> 
> ![dictionary in content - chrome window size](https://cloud.githubusercontent.com/assets/2098816/9554643/5058833c-4d95-11e5-8f40-bb7f5d523b57.gif)

**Comment by designsimply** [comment] 2017-12-20 22:12
I tested with Firefox 57.0.1, Safari 11.0.1, and Chrome 63.0.3239.84 on macOS 10.13.2 and there was a slight offset in the highlighted word in the title in Chrome but not very much.

<img width="458" alt="screen shot 2017-12-20 at wed dec 20 3 09 16 pm" src="https://user-images.githubusercontent.com/1119271/34231135-02736b8a-e598-11e7-9952-32a8e92d0d88.png">

Closing because the issue is minor.

**Closed by designsimply** 2017-12-20 22:12 UTC
Labels: Editor, [Type] Bug
