### ISSUE TITLE
Theme Showcase: Display issue on Activate Theme Site Picker

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#42765] opened 2020-05-28 19:48 UTC
#### Steps to reproduce
On an account with multiple sites,

1. Starting at URL: https://wordpress.com/themes
2. Tap the three dot menu. Opt to activate a theme
3. Try to choose a different site
4. Note the search box is overlaying the scroll

#### What I expected
The search box shouldn't overlap the scroll options

#### What happened instead
It does overlap and makes it harder to see which site I'm choosing

#### Browser / OS version
Chrome 83.0.4103.61 / Mac OS 10.14.6 

#### Screenshot / Video
https://cloudup.com/cAFVX0yuIDH

#### Context / Source
As an HE I have a handful of sites I switch themes on several times every day while helping users, so I ran into this myself while checking a theme's features.

**Comment by obenland** [comment] 2021-03-18 17:04
Duplicate of #40195

**Closed by obenland** 2021-03-18 17:04 UTC
Labels: Site Picker, Theme Showcase, Themes, [Type] Bug
