### ISSUE TITLE
Rename template parts design issue

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#81925] opened 2023-09-19 23:03 UTC
### Quick summary

When you try to rename a template part the context menu doesn't auto-hide and overlaps the rename box.

![TMTavP.png](https://github.com/Automattic/wp-calypso/assets/42655541/8b371f63-8377-459f-964f-1d67d534502d)

### Steps to reproduce

1. Go to Appearance > Editor
2. Go to Patterns
3. Go to Template Parts
4. Duplicate an existing template part
5. Rename the copy template part

### What you expected to happen

I expected the context menu to auto-hide so that I could see the entire rename box.

### What actually happened

The context menu stays open and the rename box is partially hidden behind it.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

I haven't tested on a self-hosted site. The amount of overlap does vary based on screen/window size and jumps around to different locations. It's not a great UX.

**Comment by cuemarie** [comment] 2023-09-21 17:12
📌 REPRODUCTION RESULTS
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated on Self-Hosted site using TT3 theme:

https://github.com/Automattic/wp-calypso/assets/27249804/db2890c0-3539-4f5d-832f-079d7fd09cb6

📌 ACTIONS
- Closing in favor of the core report
- Reported to core: https://github.com/WordPress/gutenberg/issues/54702

📌 Message to Author
Thanks for the report @tanjoymor ! Since this is a core level fix, I'm closing out this one. We can reopen if we need to track user reports here for any reason, but I expect this one may have a fairly low interaction count.

**Closed as not planned by cuemarie** 2023-09-21 17:12 UTC
Labels: Bug, [Pri] Normal, [Status] Core Fix Needed, Patterns, Triaged, [Platform] Simple, [Platform] Atomic, [Product] WordPress.com, [Feature Group] Editor Experience
