### ISSUE TITLE
"Home page / Archive" stats show "We don't have that post on record yet" when using a posts/archive homepage

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#60563] opened 2022-01-27 17:09 UTC
### Quick summary

This appears to be a recent issue – one user that reported it mentioned noticing this change within the past week or so.

When the homepage is set as a "posts page" (blog archive), it is displayed on `/stats/day/{site}` as *Home page / Archives`. Clicking on that entry should bring up the insights for the site's homepage, but instead leads to a possibly invalid URL: 

`https://wordpress.com/stats/post/0/{site}`

There is no stats information shown there, just a warning that `We don't have that post on record yet.`

**Note: I wasn't able to reproduce this on a test site due to delays in stats recording. Unsure if this is theme-specific. Unsure if this applies to atomic.**

### Steps to reproduce

1. Navigate to My Site > Appearance > Customize > Homepage Settings and set the homepage to be a "posts page." (Ideally, this should be done on a site which has used a posts page for some time and has had traffic.)
2. View the homepage to ensure there is traffic/stats to record.
3. Wait for "Home page / Archives" to appear under "Posts & Pages" at My Site > Stats.
4. Click on "Home page / Archives."

### What you expected to happen

This page should show stats for the site's archive homepage.

### What actually happened

You are instead led to this URL: `https://wordpress.com/stats/post/0/{site}`
Possibly because there isn't a post with ID `0`, no stats are displayed and the message `We don't have that post on record yet.` displays instead.

<img width="1586" alt="Markup 2022-01-27 at 12 05 28" src="https://user-images.githubusercontent.com/5630717/151407843-a4e04c2c-09e5-42d1-bd93-d952cfd85bdc.png">

### Context

4720094-zen

Initially mentioned by @liviopv in p1642511428116000-slack-C03TY6J1A

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Unsure.

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by carinapilar** [comment] 2022-01-27 18:18
The same thing happens on my personal site, which is Atomic.

**Comment by ezebecke** [comment] 2022-02-02 17:37
Another report on 33722616-hc

**Comment by nagpai** [comment] 2022-02-05 09:13
Another report here 
4747937-zd

**Comment by nagpai** [comment] 2022-02-05 09:25
Happening on my Jetpack connected Self-hosted site too. Could be a Jetpack core related issue.

**Comment by kimerlin81** [comment] 2022-03-22 17:42
Could this behavior be accurate? It looks like the error: "We don't have that post on record yet. " is based on this context in our Support Docs and on the Forum:

**There are many views that aren’t tied to a post or page URL. The category, tag, date and author archive pages, and search result pages are all examples of other views that only count towards total views. In your stats, this shows in “Home page / Archives”.**  

https://wordpress.com/support/stats/#posts-amp-pages

**Comment by roo2** [comment] 2022-04-13 04:20
good point @kimerlin81 about this maybe being expected?

I think it looks broken and we could/should show a graph for views on the "Home page / Archieves" category.

We should be able to make it work and load something sensible when the user lands on `stats/post/0/$siteSlug`.

In order to reproduce this as an a11n, we can look at the p2 sites which we're a member of. e.g. `https://wordpress.com/stats/day/my-teams-p2.wordpress.com`

I think this could be a good (more challenging) first issue for our new ganon dev's starting in the next few weeks

**Comment by mxhassani** [comment] 2022-09-07 19:43
Reopening. Ran into this issue again in 5528212-zen

There seem to be a bunch of other users facing it too, in the interactions listed here:

210-gh-Automattic/wp-calypso

Copied them below:

2192218-zen
2468699-zen
5518630-zen

**Comment by jamiepalatnik** [comment] 2022-09-15 16:24
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate
- Tested on AT - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I tested this on my simple and Atomic test sites and I was not able to recreate the issue with the message "We don't have that post on record yet." Instead, I see a chart with stats as seems to be expected from this change: https://github.com/Automattic/wp-calypso/pull/64492
- Screenshot:
<img width="1004" alt="Stats homepage" src="https://user-images.githubusercontent.com/30788962/190455706-70e6b1b6-8bb3-4a2a-9b92-ca67cc053452.png">

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @mxhassani I was not able to replicate the issue with the message "We don't have that post on record yet." on my test sites, and I took a quick look at your user report and they are no longer using a posts page on the homepage so I was not able to see the behavior on that site. Checking the other interactions you shared, they seem to be reporting [the other issue you linked](https://github.com/Automattic/wp-calypso/issues/99253).

**Closed as completed by jamiepalatnik** 2022-09-15 16:24 UTC
Labels: Bug, [Feature] Stats, Jetpack, [Pri] Normal, Triaged
