### ISSUE TITLE
Galleries: Live site showing < before a gallery block

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-calypso#66875] opened 2022-08-23 16:03 UTC
### Quick summary

Tiled gallery is showing less than "<" sign before the gallery begins. 

<img width="1337" alt="Markup 2022-08-23 at 21 26 40" src="https://user-images.githubusercontent.com/40609190/186205343-3c0e65e2-0036-4ff7-8954-46da2c5917e5.png">

I thought we could remove this from the code editor, but apparently, this sign is not showing up there.

This is happening on various themes, both on FSE and classic themes.

### Steps to reproduce

1. Create a page on a simple site.
2. Add a tiled gallery.
3. Check the Live Site.

### What you expected to happen

I did not expect the "<" sign before the gallery.

### What actually happened

The "<" sign shows up just before the Tiled gallery.

### Browser

Google Chrome/Chromium, Mozilla Firefox, iOS Safari

### Context

User contacted us at zen-5500682 and I also tested it on my test site, multiple themes, simple as well as atomic site.

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

Only happening on Simple sites, not on atomic. 

< sign not showing up on the code editor.

I upgraded my testing site from simple to AT, and the sign disappeared.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Workaround details

Not sure.

**Comment by ahmadbaig1** [comment] 2022-08-23 16:34
Issue reported here as well- https://github.com/Automattic/wp-calypso/issues/66865
But not sure if that is for all galleries or only Tiled gallery.
Reported here as well- https://github.com/Automattic/wp-calypso/issues/66876

**Comment by carinapilar** [comment] 2022-08-23 17:36
I have just spotted this too with the Gallery block, it also happens on P2 comments. I wasn't able to replicate it on WordPress.org.

**Comment by carinapilar** [comment] 2022-08-23 17:39
This one seems to be the first report: https://github.com/Automattic/wp-calypso/issues/66865 - maybe we can close this in favor of that one?

**Comment by oskosk** [comment] 2022-08-23 20:40
Closing as duplicate of #66865

Fixed in https://github.com/Automattic/jetpack/pull/25795

**Closed as completed by oskosk** 2022-08-23 20:40 UTC
Labels: Bug, [Pri] High, Needs triage, [Platform] Simple
