### ISSUE TITLE
Nav Unification: Earn/WordAds is duplicated + different wording

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#48237] opened 2020-12-10 22:55 UTC
1. WordAds options appears on both `Tools > Earn > View Ad Dashboard > Settings` (Calypso) and on `Settings > Wordads`
2. Also, we refer to it differently under the `Settings` menu: in Calypso, it's `AdControl` whereas in WP Admin, `WordAds`.

#### What I expected

To find all the Earn/WordAds options on a single location.

#### What happened instead

We have two ways to get to the (almost identical pages):

https://wordpress.com/earn/ads-settings/SITEURL.wordpress.com
https://SITEURL.wordpress.com/wp-admin/options-general.php?page=wordads

#### Browser / OS version
Chrome 87 / Mac Catalina 10.15.7

#### Context / Source
#manual-testing

**Comment by cpapazoglou** [comment] 2021-01-05 15:31
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/48238

**Closed as completed by cpapazoglou** 2021-01-05 15:31 UTC
Labels: Task
