### ISSUE TITLE
Reader: scrolling problems in Reader (Firefox)

### ISSUE THREAD

**Issue by kristarella** [Automattic/wp-calypso#37901] opened 2019-11-23 02:23 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/tag/photography (I think it happens on any page, but this tag makes it easier to see)
2. Scroll, keep scrolling
3. Observe the scroll marker on the right of the browser
4. Observe images

#### What I expected
To see smooth-ish scrolling on the right.
To see each post once.

#### What happened instead
The scroll marker jumps rather eratically.

Posts appear to be duplicated, but I'm pretty sure it is just that the page is jumping back to a previous point.

Observe in the video below that when I click a link, and then see the same image again, the link is still outlined, which is why I think it is page jumping, not posts actually being duplicated.

#### Browser / OS version
Firefox 70.0.1
Mac OS X Mojave
Windows 10
Maybe Edge also?

#### Screenshot / Video
https://cld.wthms.co/tn6FmL

#### Context / Source
#user-report
2505176-zen

**Comment by bluefuton** [comment] 2019-12-01 20:47
Thanks for writing this one up @kristarella! I've also seen this since switching to Firefox recently. No solution yet but it's on my radar.

**Comment by Agepeuve** [comment] 2019-12-03 09:27
Another report in the ES forums - https://es.forums.wordpress.com/topic/problemas-con-el-deslizamiento/

**Comment by lakellie** [comment] 2019-12-05 20:39
Another report in 2520151-zen

**Comment by pento** [comment] 2019-12-10 05:09
I've run through a `git bisect`, it seems like this was caused by #37438.

From the debugging I've done so far, it appears that [this call](https://github.com/Automattic/wp-calypso/blob/923a658f5be7720c61213cdd0e08c3b2f5ed2195/client/components/infinite-list/scroll-helper.js#L72) returns `null`, because [`boundsForRef()`](https://github.com/Automattic/wp-calypso/blob/923a658f5be7720c61213cdd0e08c3b2f5ed2195/client/components/infinite-list/index.jsx#L317-L322) isn't finding the `ref`.

@bluefuton, @jsnajdr: I've run into the limits of my knowledge of how this magic works, and my random hacking is not producing anything of value. Could you review this, and help with the next steps?

**Comment by blowery** [comment] 2019-12-10 15:57
@pento taking a look. I bet we need to [forward a ref](https://github.com/reduxjs/react-redux/blob/50883450079356e70828139e531303a962b85458/docs/api/connect.md#forwardref-boolean) somewhere.

**Comment by jsnajdr** [comment] 2019-12-11 10:02
Fixed by #38335, regression introduced in #37553 and #37438. Thanks @kristarella for reporting and @pento for bisecting and debugging! Everyone is invited to test and review the fix.

**Closed** 2019-12-11 13:32 UTC
Labels: Reader, Support, [Type] Bug

**Comment by bluefuton** [comment] 2019-12-11 17:50
High fives all round @kristarella, @pento, @blowery and @jsnajdr. Thanks for getting this fixed ❤️

**Comment by pento** [comment] 2019-12-11 22:19
Thank you for fixing this, @jsnajdr! 💖
