### ISSUE TITLE
Unable to create Instagram connections via settings, block, or widget

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#52993] opened 2021-05-19 06:01 UTC
Unable to connect to Instagram via three areas: Latest Instagram Posts block, Marketing and Integrations settings page, or the Instagram widget. 

#### Steps to reproduce the behavior

1. Add the Latest Instagram Posts block, visit the Marketing and Integration settings page, or add the Instagram widget.
2. Try to connect with an Instagram account and allow.
3. WordPress.com refuses to connect/shows no change, however the connection is shown on Instagram's Apps and Websites section and notification emails from Instagram reach users regarding the WordPress.com connection.

#### What I expected to happen

After logging in and clicking "allow", the connection status should change and show as active on WordPress.com

#### What actually happened

The login window disappears, but the connection status is not updated to reflect either a success or failure on WordPress.com

#### Context

3997777-zd, 4001174-zd

#### Browser / OS version

Confirmed with current versions of Chrome and Firefox on Windows 10 2004.
Also confirmed in the above customer reports. macOS 11.3 and the current version of Chrome.

#### Is this specific to the applied theme? Which one?

Tested on the following themes: Twenty Twenty One, Balasana, and Apostrophe 2.

#### Does this happen on simple or atomic sites or both?

Only simple sites have been tested/reported.

#### Is there any console output or error text?

None.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affecting multiple sites.

**Comment by jartes** [comment] 2021-05-19 10:32
I was able to reproduce this as well in three different Atomic sites with no 3rd party plugins. 

Also, reported on 3998716-zen

**Comment by zdenys** [comment] 2021-05-19 10:47
29671920-hc AT site as well

**Comment by inaikem** [comment] 2021-05-20 03:13
@jartes, @zdenys, this is looking resolved now. It may have been a temporary connection issue between WPcom and IG.

Would you please both check your interactions to confirm if this is the case?

p1621472433192100-slack-CS0SC36SX for reference. Please also nudge there if you're still seeing issues.

**Comment by jartes** [comment] 2021-05-20 06:32
Thanks for checking @inaikem! I've tested this on an AT site and the connection worked as well adding the Latest Instagram Posts block: 

![Markup on 2021-05-20 at 08:29:06](https://user-images.githubusercontent.com/1046943/118930038-8b8ba980-b945-11eb-8b5a-d890ea37ef75.png)

Will follow-up the interaction. Thank you!

**Comment by zdenys** [comment] 2021-05-20 08:15
I followed up with the user in 4004667-zd-woothemes (29671920-hc) to confirm if the issue is solved.

**Comment by synora** [comment] 2021-05-21 17:12
I've tested this on an AT site and it appears the Instagram connection is working again as expexted. I'll close this issue for now but we can always reopen if it crops up again.

**Closed as completed by synora** 2021-05-21 17:12 UTC
Labels: Bug, Blocks, Triaged
