### ISSUE TITLE
Guided Tours: dialog appears out of place

### ISSUE THREAD

**Issue by keoshi** [Automattic/wp-calypso#22252] opened 2018-02-08 16:53 UTC
When switching pages after triggering a guided tour, the dialog appears out-of-bounds, and floating over the sidebar.

![image 1](https://user-images.githubusercontent.com/390760/35986231-6d2835d0-0cf0-11e8-8425-4afde48dd7be.png)

**Comment by lsinger** [comment] 2018-03-07 12:53
@keoshi could you provide steps to reproduce?

**Comment by keoshi** [comment] 2018-03-07 13:36
@lsinger I don't remember exactly but it was something like this:

- Trigger guided tour, don't click it.
- Click on another non-highlighted section from the left sidebar.
- Dialog reappears out of place.


https://github.com/Automattic/wp-calypso/issues/22633 also contains a more detailed flow of how this happened.

**Comment by lsinger** [comment] 2018-03-07 14:49
Thanks @keoshi, I'll try with what we have. 

Judging from the copy in the screenshot, this is the first step of `checklist-site-icon-tour.js`. 

#22633 seems to be a case where Guided Tours can't find the target node to attach to, resulting in (0, 0) as coordinates. This one seems to be a different case still.

**Comment by fditrapani** [comment] 2018-03-07 15:00
> This one seems to be a different case still.

yeah — although they appear similar, these are two different cases. @taggon is working on a fix for https://github.com/Automattic/wp-calypso/issues/22633

**Comment by taggon** [comment] 2018-03-08 02:08
This should be fixed by the PR #23080. :)

**Closed by taggon** 2018-03-08 02:08 UTC
Labels: Guided Tours, [Type] Bug
