### ISSUE TITLE
Media: Edit icon abnormally large in Internet Explorer / Edge

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#3946] opened 2016-03-10 14:49 UTC
This is low priority, as the feature is only enabled in development environments.

When selecting an image in the editor, the toolbar "Edit" icon is very large in Internet Explorer 11 and Microsoft Edge browsers:

![Edit](https://cloud.githubusercontent.com/assets/1779930/13673067/6f6c862a-e6a5-11e5-8055-35442b5d9af0.png)

**Comment by lancewillett** [comment] 2016-05-09 23:03
This could be fixed by 570ff3f — I'm re-testing it now to be sure.

**Comment by lancewillett** [comment] 2016-05-09 23:08
I can't reproduce in IE Edge — but also the edit icon isn't in this toolbar anymore. ¯\_(ツ)_/¯

<img width="1264" alt="screen shot 2016-05-09 at 16 07 56" src="https://cloud.githubusercontent.com/assets/66797/15130846/470b69f0-1600-11e6-8a84-f53142017a1c.png">

**Comment by aduth** [comment] 2016-05-10 12:03
This is still an issue, but the icon is only available in development environments. It's part of a media editing feature that's unfortunately stalled (#307).

![image](https://cloud.githubusercontent.com/assets/1779930/15145775/9e601ae0-1685-11e6-9035-ee1a19013c4a.png)

**Comment by lancewillett** [comment] 2016-05-10 16:16
Oh, sounds good — thanks Andrew.

**Comment by lancewillett** [comment] 2016-10-18 22:27
This is still pending #307 work.

**Comment by rachelmcr** [comment] 2017-11-06 15:02
I tested this in Internet Explorer and Edge (on a Win10 VM) and can't reproduce; the edit icon appears at the expected size:

![editicon - edge](https://user-images.githubusercontent.com/8658164/32447016-a88ba4dc-c302-11e7-808c-39579aa02fc9.png)

**Closed by rachelmcr** 2017-11-06 15:02 UTC
Labels: Editor, Media, [Pri] Low, [Type] Bug
