### ISSUE TITLE
Subscription Management: Misaligned table or header

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#76897] opened 2023-05-12 23:53 UTC
### Quick summary

See the below screenshot. Note that the sort dropdown near the top right is not aligned with the right side of the table below it. This feels incorrect.

<img width="1767" alt="Screenshot 2023-05-12 at 6 11 08 PM" src="https://github.com/Automattic/wp-calypso/assets/1126811/415b8ff0-7053-4a9c-8077-f73dc5593367">

### Steps to reproduce

1. Logged in
2. Go to https://wordpress.com/subscriptions

### What you expected to happen

Better alignment.

### What actually happened

Misalignment

### Impact

All

### Available workarounds?

There is no user impact

### Logs or notes

Tested on Mac OS and Microsoft Edge.

**Comment by JuanLucha** [comment] 2023-05-16 15:06
It seems to be fixed already:

![Image](https://github.com/Automattic/wp-calypso/assets/3832570/2d38e144-2133-497d-befb-829e14a1f13a)

I also tried to reproduce using Edge, and it works too:

![Image](https://github.com/Automattic/wp-calypso/assets/3832570/19a38cf9-f0ac-47a7-9f5e-790ff49c4b0e)

@ebinnion, this could have been fixed recently. Can you try to reproduce it again? If you can't reproduce it anymore, I'll close the task 👍

**Comment by yansern** [comment] 2023-05-17 09:15
Duplicate of https://github.com/Automattic/wp-calypso/issues/76211. Fixed in https://github.com/Automattic/wp-calypso/pull/76829.

**Closed as completed by yansern** 2023-05-17 09:15 UTC
Labels: Bug, [Pri] Normal, Needs triage
