### ISSUE TITLE
WordPress.com app (Android): App freezes and becomes unresponsive when scrolling in the Posts list

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#54172] opened 2021-06-30 15:38 UTC
Our customer reached out to us in Live Chat to let us know that the latest release of the Android app, version 17.6.

### Steps to reproduce the behavior

1. Go to _Blog Posts_
2. Scroll down the list for a few minutes
3. App freezes, and you see the following error

![Screenshot_20210630-193653](https://user-images.githubusercontent.com/2912202/123988138-6d977700-d9d0-11eb-93d9-a02db5daf5f5.png)

#### What I expected to happen

The app would not freeze when scrolling through posts list.

#### What actually happened

The app froze, and became unresponsive.

### Context

Report in Live Chat here: 30405242-hc with a follow-up here: 30405772-hc

The user shared screenshots of the error, and logs in 4106223-zen

#### Browser / OS version

The user said they are using a Motorola G, running Android 7.0

#### Is this specific to the applied theme? Which one?

This doesn't seem to relate to a theme.

#### Does this happen on simple or atomic sites or both?

The site is on a WordPress.com Business plan, although this doesn't seem to be relevant.

#### Is there any console output or error text?

See screenshots of app logs below.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

This seems to be an issue with this version of the app on Android devices. I experienced what may be a related issue on my Android device. More details in the comments on this issue.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

I haven't been able to reproduce this specific issue.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![Screenshot_20210630-195300](https://user-images.githubusercontent.com/2912202/123989053-32497800-d9d1-11eb-8dd3-9da06a0cf4ec.png)
![Screenshot_20210630-195319](https://user-images.githubusercontent.com/2912202/123989058-32e20e80-d9d1-11eb-96b0-b2184f9b46e0.png)
![Screenshot_20210630-195352](https://user-images.githubusercontent.com/2912202/123989060-337aa500-d9d1-11eb-816c-47391957eba8.png)
![Screenshot_20210630-195409](https://user-images.githubusercontent.com/2912202/123989064-34abd200-d9d1-11eb-9f1e-2a3003f775e7.png)
![Screenshot_20210630-195424](https://user-images.githubusercontent.com/2912202/123989068-36759580-d9d1-11eb-977f-799e674af1ae.png)
![Screenshot_20210630-195434](https://user-images.githubusercontent.com/2912202/123989076-383f5900-d9d1-11eb-815f-502a76c6c45c.png)
![Screenshot_20210630-195444](https://user-images.githubusercontent.com/2912202/123989087-3a091c80-d9d1-11eb-851a-3dcfe2e44ece.png)

**Comment by pauljacobson** [comment] 2021-06-30 15:42
I encountered what may be a related issue on my Samsung Galaxy S21, running Android 11, and version 17.6 of the Android app. While I can scroll through my posts (in this case, this is a self-hosted WordPress.org site on Pressable), the posts list disappears after a minute or two.

Here's a demo:

https://user-images.githubusercontent.com/2912202/123990568-8b65db80-d9d2-11eb-8691-a317e2d81d34.mp4

My app logs are here: 29ad3-pb/

**Comment by synora** [comment] 2021-07-02 21:31
@thehenrybyrd Would you happen to know the best repo for an app issue like this?

**Comment by thehenrybyrd** [comment] 2021-07-06 13:21
@synora looks like this was on Android, so https://github.com/wordpress-mobile/WordPress-Android/issues would be the best place for it. For issues with the WordPress app on iOS, https://github.com/wordpress-mobile/WordPress-iOS.

This specific freeze/crash was introduced in WP Android 17.6 and fixed in a hotfix (17.6.1) a few days later. Here's the GH issue where it was first reported: https://github.com/wordpress-mobile/WordPress-Android/issues/14860
I'll close this one as the issue is resolved.

Thanks for reporting @pauljacobson!

**Closed as completed by thehenrybyrd** 2021-07-06 13:21 UTC
Labels: Bug, Triaged
