### ISSUE TITLE
LinkedIn preview image distorting / not removed from cache

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/wp-calypso#21244] opened 2018-01-03 21:07 UTC
#### Steps to reproduce
1. Starting at URL: https://inconditionnelle.com/2017/10/30/retour-sur-le-blend-web-mix-2017-a-lyon/
2. Share the page on LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:6338335247670800384/
3. Compare the cover photo with the LinkedIn preview
4. Change the cover photo and try to force the cache to clear by visiting: https://www.linkedin.com/feed/update/urn:li:activity:6338335247670800384/?1

#### What I expected

A similar look between the two images, and the image to update when the cache is refreshed.

#### What happened instead

The image is distorted. It appears to be because LinkedIn is using the CSS tag `background-size: cover;`. The base image is clear and not distorted:

https://media-exp2.licdn.com/media-proxy/ext?w=439&h=146&f=n&hash=DcCqGpUQN1xcd5tGnqBwgGDjNbA%3D&ora=1%2CaFBCTXdkRmpGL2lvQUFBPQ%2CxAVta5g-0R6nlh8Tw1It6a2FowGz60oISIfYC2G8G2f1spyfNT-tdoDSfbGosgUbeSgHhlI_IfnwEXO5H5b-KNG1A4Eoz8iXVveyQS02XxMyjTl8qYMdKUAN8MeCQ-TiYXMfl757bAmfEI3RY1kNBzUQ0b6FO7btD38h6BPebsDAL9hEC7AvoLMMyVBnoPvfNs0xkadv52c57w_q2a3ZBDdf2aGMCRucVHIlX0_sPtVPkb-ohxmLv0HFgwTFhqWVDL6CH7wn0HGuw7X9QVG8uyFq82YH3V4wv5NsU2OCgfoc-xa0AsA-ZQaeo-rvfX2495YB_D5ErMyHEA6WWmo4vgM6QJ7WrQ

However, the sizing is off on the presentation. This has been tested on other sites with other images in various sizes.

#### Browser / OS version

All browsers

#### Context / Source

#user-report in #661529-hc and #879432-zen . It's difficult to tell if it's something that's being fed improperly from WP.com or if it's just a design decision on LinkedIn's part.

**Comment by rachelmcr** [comment] 2018-01-04 17:11
I confirmed that the open graph image on this post is 1200px wide: https://inconditionnellecom.files.wordpress.com/2017/10/bannic3a8re-blend-web-mix-inconditionnelle-blog.png?w=1200

Given that the background image used on LinkedIn is 439px wide and then increased in size when displayed, it looks like the issue is how the image is handled on their end rather than how it's sent from our end. If that sounds right, I'd recommend closing this issue as I don't see any evidence that the issue is on this end.

**Comment by rachelmcr** [comment] 2018-01-17 11:12
I'll go ahead and close this issue, but please reopen if you find evidence that a change needs to be made on the WordPress.com end for this.

**Closed by rachelmcr** 2018-01-17 11:12 UTC
Labels: Sharing, [Triage] Close Me
