### ISSUE TITLE
Jetpack Mobile Theme is Back

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#49963] opened 2021-02-10 21:49 UTC
### Steps to reproduce the behavior

1. Access a non-A11n WordPress.com account
2. Go to your site's WP-Admin dashboard
3. Check the Appearance menu

#### What I expected to happen
To not see the Mobile menu option, that was retired years ago: https://github.com/Automattic/jetpack/issues/13385

#### What actually happened
It's showing for non-A11n WordPress.com accounts.

### Context
Not sure why it's showing again, and not showing for A12s might be because of the New Nav. I noticed this when I got a couple users this week asking about the mobile theme (that hasn't happened in a long time), and then found this ticket: 3712942-zd-woothemes - which is an account and site that are only a month old. After testing on other accounts, including testing accounts, I noticed that it seems to be showing the menu again, but only for non-A11n WordPress.com accounts.

Found this similar issue: https://github.com/Automattic/wp-calypso/issues/49313, that says:

> This is the same as the Jetpack mobile theme, which was already retired and removed from Jetpack, but it was never removed from simple sites

But iirc, this was removed from Simple sites at some point, and it seems to be back.

**Comment by annacmc** [comment] 2021-03-25 03:38
Tested on a non-A11n account, and was unable to find the Jetpack mobile theme anywhere.

This may be because of the new Nav unification roll out which at the time of the issue opening, was only on A11n accounts. Have tagged this with the Nav Unification label as it may be something which shouldn't be back, and is only temporarily being obscured by the latest nav updates - would be a good thing to watch out for and make sure it doesn't creep back in.

**Comment by mmtr** [comment] 2021-03-29 10:51
@annacmc I'm unable to reproduce it, or maybe I'm missing a testing instruction step. This is the menu I get:

<img width="352" alt="Screen Shot 2021-03-29 at 12 50 28" src="https://user-images.githubusercontent.com/1233880/112826504-5b363600-908d-11eb-8e2d-d6b98087cfa4.png">

Should I see the Mobile settings there? Note that Nav Unification is disabled for Jetpack sites, so not sure if this is related to that feature.

**Comment by carinapilar** [comment] 2021-03-29 13:06
> Should I see the Mobile settings there? 

Yes, it was showing in there, I'm not being able to replicate this anymore.

It wasn't showing with the Nav Unification, and I tested again now on a non-A11n WordPress.com account, where the Nav Unification isn't enabled yet, and I don't see the Mobile menu anymore.

**Comment by carinapilar** [comment] 2021-04-04 12:57
Although it doesn't seem this is available anymore, we got another user with this issue. Account and site were created a month ago, they already have the Nav Unification, but the Mobile menu shows up under Appearance. Ticket is here: 3816124-zd-woothemes

**Comment by obenland** [comment] 2021-04-07 22:06
It looks like the customer had the mobile theme active because the theme they selected when creating the site (Hever) is missing the `responsive-layout` tag. D59890-code will change it to always disable the mobile theme on signup.

**Comment by ianstewart** [comment] 2021-05-04 16:30
@kwight marking this one as Design Selection. Looks like Obenland just needs a review from someone to close this one out.

**Comment by kwight** [comment] 2021-05-04 22:03
@ianstewart I've added it to our review column. 👍

**Comment by ianstewart** [comment] 2021-05-05 19:57
Thanks!

**Comment by kwight** [comment] 2021-05-17 17:37
Closed in D59890-code

**Closed as completed by kwight** 2021-05-17 17:37 UTC
Labels: Bug, Jetpack, [Pri] Normal, [Feature] Calypso & wp-admin Navigation, Triaged, [Pod] Design Selection
