### ISSUE TITLE
People: Prevent owners user role from being changed

### ISSUE THREAD

**Issue by BrookeDot** [Automattic/wp-calypso#3140] opened 2016-02-06 08:01 UTC
Historically speaking we've always prevented the site owner's user role from being changed by another administrator on the site. The reason for this is that the site owner needs to have the ability to manage all aspects of the site. With the new People Management it's possible to lock the Owner out of their site. 

**To Reproduce:**
1) Create a site and then invite a second user as an admin
2) Accept the invite as the new admin and log in to that account
3) Visit people/team/ and click on the site owner
4) Change the role to something other than Admin

https://cloudup.com/cFbtNLLr-Bx

**In WP-Admin**
- Edit link does not show to other admins for the owner's username
- If another admin tries to change the owner's role this results in `wp_die('you can not edit this user')`

**Comment by lizkarkoski** [comment] 2016-02-13 22:20
I tested this recently. When logged in as an Admin there is the option available to delete the site owner. When you click the  'Save changes' button you receive the error message "There was an error deleting @user_name". Since deleting is not permitted we should hide this option.

**Comment by SiobhyB** [comment] 2016-02-14 11:06
@ebinnion: Would you be able to take a look or know who to escalate the issue to?

**Comment by BandonRandon** [comment] 2016-02-14 19:15
> Since deleting is not permitted we should hide this option.
@lizkarkoski  thanks for testing. Do you mind opening a new issue for "hide the delete button for the owner" and referencing this issue?

**Comment by KokkieH** [comment] 2016-02-19 09:28
I just had a case of this in 315834-chat. Follow-up in 2548205-t

**Comment by ebinnion** [comment] 2016-02-19 15:46
This should have been fixed in the API in r131094-wpcom on 2-15-2016. We now return an an error when an admin attempts to change any user information about the site owner. Which, seemed to match previous functionality.

I am leaving the issue open as a reminder to address the Calypso UI so that we don't even show a form to edit the site owner.

@KokkieH I'll look into your ticket and chat to see if the issue was due to a change that occurred before r131094-wpcom.

**Comment by KokkieH** [comment] 2016-02-19 17:37
@ebinnion The user's role was changed two weeks ago, so before the fix.

**Comment by BandonRandon** [comment] 2016-02-21 22:03
Closing as this seems to be fixed.
![screenshot_21-02-2016-14 01 05](https://cloud.githubusercontent.com/assets/150348/13205741/e5ab6aaa-d8a3-11e5-938d-941da1071be0.png)

**Comment by SiobhyB** [comment] 2016-05-07 14:47
@ebinnion: Is there any way to run a check for owners who had their user roles changed during the time this bug was open? Someone contacted us in 2648956-t to let us know that they were seeing an error when attempting to change the user role of the original owner from author back to admin. It'd be good to try and catch other users who had been affected to stop this coming up again.

**Comment by ebinnion** [comment] 2016-05-09 17:09
@SiobhyB – Since the bug has only been reported 3 times to me since people management launched last October, my guess is that this is a bit edge case. Also, from the linked ticket, it seems that the bug is easily verified and fixed. Based on that, I'm not sure that we need to generate a report.

But, if you disagree, I think we'd probably need to ping data on this one.

**Comment by Nic-Sevic** [comment] 2021-12-21 10:29
Another instance of this here: 33285431-hc

I couldn't duplicate on a test site but here another admin was able to change the site owner role and then delete them

**Comment by dpasque** [comment] 2022-01-26 17:13
@Nic-Sevic 👋  I was looking through this issue and chat transcript, and from what I can tell, it actually looks like the transcript may have documented different behavior than this?

Reading through the transcript, it looks like the user was actually _unable_ ultimately to remove the owner from the WordPress.com site ownership. Does that sound right? I might be misunderstanding! Thanks! 😄

**Comment by Nic-Sevic** [comment] 2022-01-27 15:20
@dpasque The related slack thread here can help clarify: p1640080100394100-slack-C03TY6J1A
I may have forgotten details by now but essentially, they were able to remove the site owner user from the site after changing the role. They were not able to remove the WordPress.com account from the site ownership on our side. They shouldn't have been able to remove them from the site at all though. 

Adding to the confusion here, after they changed the role of the site owner, Jetpack appears to have removed the user: 
![2022-02-03 at 09 56](https://user-images.githubusercontent.com/47717887/152303083-38a65dd4-4ff7-48fc-9b20-a0c8c5dba10f.jpg)

It seems like maybe changing the role broke JP which then allowed them to delete the user 

@hideandgeek404 was able to duplicate this

**Comment by dpasque** [comment] 2022-01-27 18:04
@Nic-Sevic Ah, that clarifies so much, thank you for the extra info! This definitely looks like it needs some extra investigation to figure out how this ultimately ended up happening. Maybe some Jetpack team eyes?

**Comment by Nic-Sevic** [comment] 2022-07-10 12:37
A maybe similar case here: p9F6qB-9M6-p2
In this one no role change was necessary to remove the site owner. This is still happening on this site even after verifying that the owner is correctly assigned everywhere on our end and resetting roles

**Comment by druesome** [comment] 2022-07-11 07:45
Seems that in the case above, the non-owner admin was able to delete the site owner because the endpoint was returning the owner's local user ID, rather than their WordPress.com ID.

More details here: 

p9F6qB-9M6-p2#comment-47991

@dpasque are you able to look at this one, or do you think this falls in the hands of Jetpack?  Thank you!

**Comment by wojtekn** [comment] 2022-08-05 14:53
The issue is resolved now for both Atomic and Simple sites.

**Closed** 2022-08-05 14:54 UTC
Labels: [Type] Bug, Jetpack, [Pri] High, People Management
