### ISSUE TITLE
Earn Page Upgrade Flow does not take you back to starting point

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#65453] opened 2022-07-11 14:48 UTC
#### Steps to reproduce

1. On a free site visit Tools > Earn
2. Click the upgrade button
3. Upgrade to starter
4. BUG: wind up on outdated thank you page that won't get you back to the Earn Page

#### What I expected

1. To see the new thank you page.
2. And have a path to getting back to the action on the Earn page.

Would have been fantastic to get back here or maybe right into the stripe flow?

![image](https://user-images.githubusercontent.com/545779/178292097-942a621b-fda4-4624-8096-ccf15dbb127b.png)

#### What happened instead

I (genuinely) got lost.

**Comment by dsas** [comment] 2022-07-15 09:45
Looks like a duplicate of #50033, I'll close in favour of that.

**Closed as not planned by dsas** 2022-07-15 09:45 UTC
Labels: Bug, Payment Blocks
