### ISSUE TITLE
Nav Unification: Media link with advanced dashboard: Uploaded media doesn’t render until refresh on simple sites

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#50961] opened 2021-03-10 20:37 UTC
### Steps to reproduce the behavior

1. Ensure "Advanced Dashboard" setting is on
2. Start at My Sites, and select a simple site
3. Click Media
4. Click Add New
5. Try dragging and dropping an image, or selecting one.

#### What I expected to happen
The media I upload should appear in the section below.

#### What actually happened
It does not appear in the media library until I refresh the page.

If I remove the "extra" part of the URL, it's fine. For example, I'm taken to
`https://veldatest2.wordpress.com/wp-admin/upload.php?return=https%3A%2F%2Fwordpress.com%2Fhome%2Fveldatest2.wordpress.com&from=calypso-unified-menu`
And if I remove everything after upload.php and press enter to load that page, the uploader works fine.

### Context
I was trying to upload an image to help a user in the forums. We don't use a regular editor to write posts there, so I had to upload a file directly to a site's media library. I clicked My Site > Media and ran into the problem, then helped the user, then tested it, confirmed it with others, etc.

#### Browser / OS version
Mac (Big Sur 11.2.3 20D91), Chrome (88.0.4324.192 -- it's now updating)

#### Is this specific to the applied theme? Which one?
No, it happens on multiple sites with multiple themes.

#### Does this happen on simple or atomic sites or both?
@jordesign tried to duplicate it on Atomic and could not, but was able to replicate on simple. For me, it's a bit hit and miss on simple sites, even, but it's easy to reproduce after a few tries.

#### Is there any console output or error text?
No, nothing aside from "samesite" issues in the console (see the screen recording)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It affected several of my sites. I'd imagine it will affect most users who have toggled "advanced" and sometimes use the media library to upload files rather than uploading from a post. So, probably a bit limited to super users.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Intermittent. I have not been able to figure out why some sites don't do it. But I did see if I take the "extra" off the URL, there's no problem.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://cloudup.com/cgD2QDHldag

**Comment by obenland** [comment] 2021-03-10 21:32
From p1615410975146900/1615407960.146200-slack-C01APA37DDW:

While it might be a bug uncovered by nav unification, I’m not sure it’s caused by it. Appending any query parameters seems to cause it. I can replicate it with `/wp-admin/upload.php?foo=bar`

**Comment by supernovia** [comment] 2021-03-10 22:08
@obenland do we know what's causing that string to be appended?

**Comment by mmtr** [comment] 2021-03-11 09:01
> While it might be a bug uncovered by nav unification, I’m not sure it’s caused by it

It's actually caused by Nav Unification. Both `return` and `from` query parameters are set by the nav unification feature in Calypso for all WP Admin URLs. See https://github.com/Automattic/wp-calypso/pull/50586 and https://github.com/Automattic/wp-calypso/pull/50839.

The `return` param is added for returning users back to Calypso after they're done in WP Admin after certain actions (e.g. after closing the customizer). The `from` param is added for avoiding a caching issue on Atomic sites when enabling nav unification on WP Admin for the current segment of the rollout.

**Comment by mmtr** [comment] 2021-03-11 09:02
I'd consider this rather urgent to fix, given it's caused by nav unification and the upload screen can be easily one of the most accessed pages.

**Comment by poojashetty18** [comment] 2021-03-28 10:47
Got a request on 28668778-hc as the scale option is not available on the Calypso edit media library option. For now, shared a direct link as a workaround

**Closed as completed** 2021-04-08 13:12 UTC
Labels: Bug, [Pri] Low, [Feature] Calypso & wp-admin Navigation, Triaged
