### ISSUE TITLE
Checkout: Thank You: Add a message for users that started a free trial in signup

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#4214] opened 2016-03-22 16:56 UTC
In [this comment](https://github.com/Automattic/wp-calypso/pull/4147#issuecomment-199775407), @mikeshelton1503 said:

> Redirecting to the hub is best for users who do not purchase a domain. If they purchase a domain we do need to send them to the thank you page. We should adjust the thank you page though to acknowledge that a free trial was started. I'll provide guidance for that shortly.

**Comment by scruffian** [comment] 2016-03-23 11:59
I think its important that the user gets take to the Plan Overview screen so that they are aware that they starts a free trial - otherwise the first they will hear about it is the email they receive. @mikeshelton1503  what do you think?

**Comment by mikeshelton1503** [comment] 2016-03-23 12:15
The problem is that there is important info about domains that also needs to be shared. Here's what's on the thank you page now for a domain purchase:

![image](https://cloud.githubusercontent.com/assets/12596797/13984850/4682943c-f0cf-11e5-873a-61ee5f8ab0a2.png)

So I'm thinking that we will show them the thank you page but add a prominent cta to the trial hub. I'll post a mockup when ready.

**Comment by scruffian** [comment] 2016-03-23 12:41
Let's wait to see how the test performs before we work on this.

**Comment by fabianapsimoes** [comment] 2016-09-02 11:47
Free Trials are on hold indefinitely while we iterate on our plan offerings. Closing this, since the way trials are offered will have to be reviewed thoroughly once we get back to them.

**Closed by fabianapsimoes** 2016-09-02 11:47 UTC
Labels: Free Trials, [Type] Task
