### ISSUE TITLE
Simple Payments: Button produces a payment error when attempting to make payments in multiple currencies

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#27874] opened 2018-10-16 12:27 UTC
A user reported a difficulty with their Simple Payments buttons on their WordPress.com Premium plan site. There are three Simple Payments buttons on their page, each in different currencies. Clicking on the Simple Payments buttons fails each time.

This appears to be related to issue #22939 although, in this case, the donation amounts don't have decimal places.

### Steps to reproduce

1. Starting at URL: https://themusing.in/website_donations/
2. When I click on a Simple Payments button, a new browser tab opens, and loads starts loading PayPal.com (although the URL doesn't resolve to a PayPal site).
3. The new tab closes abruptly.
4. A message appears above the button stating that **Payment did not create successfully**

### What I expected

Clicking on a Simple Payments button would open a PayPal window to authorize payment.

### What happened instead

Clicking on a button briefly opens a new tab to begin loading a PayPal site. That new tab closes abruptly, and the payment fails.

### Browser / OS version

* Firefox Developer Edition 63.0b14 (64-bit)
* Chrome 69.0.3497.100

Both browsers running on macOS 10.14.

#### The Simple Payments button configuration

![](https://cld.wthms.co/LV17rp+)

#### The error message

![](https://cld.wthms.co/nFNxk2+)

#### Error message in the Console

```
Error: payment_failed
payment/</<@https://s2.wp.com/_static/??-eJyNTUsKAjEMvZA12kFxI56l1FA7kzZhkjJ6ewMudeHm8Xhf2CRk7obdoI0gNErtClqbEAZJr+aOghNJFPApK6qG/MC88LD9rDv4vbDVe0FvGi2VP/hHujAX/7U1daVk+CX4xq1dj6fpfJhivMT5DRLaSEw=:193:16
i@https://s2.wp.com/_static/??-eJyFkNsOwjAIhl/IWmdm3I3xWbrKFmZbaqEu+vT2QqMumyYkQPg4/OgxKgzW5ROwHopdMqTb060HXulfgPLYJyOw9hhesKUgEET7rKLLPQbWnFu2CaMglawj52ic4mV0JBYPzKaHmaqnFh2ozJAKEKRc1dEM960AwxVhbtlEKEg09qwSMN5hTjfHt8Tlhy1RWdDxny+Zxiohcq1Jn3HpOPpDVTf7bVPt6s3wAHV2ojM=:2:27444
fireWith@https://s2.wp.com/_static/??-eJyFkNsOwjAIhl/IWmdm3I3xWbrKFmZbaqEu+vT2QqMumyYkQPg4/OgxKgzW5ROwHopdMqTb060HXulfgPLYJyOw9hhesKUgEET7rKLLPQbWnFu2CaMglawj52ic4mV0JBYPzKaHmaqnFh2ozJAKEKRc1dEM960AwxVhbtlEKEg09qwSMN5hTjfHt8Tlhy1RWdDxny+Zxiohcq1Jn3HpOPpDVTf7bVPt6s3wAHV2ojM=:2:28213
y@https://s2.wp.com/_static/??-eJyFkNsOwjAIhl/IWmdm3I3xWbrKFmZbaqEu+vT2QqMumyYkQPg4/OgxKgzW5ROwHopdMqTb060HXulfgPLYJyOw9hhesKUgEET7rKLLPQbWnFu2CaMglawj52ic4mV0JBYPzKaHmaqnFh2ozJAKEKRc1dEM960AwxVhbtlEKEg09qwSMN5hTjfHt8Tlhy1RWdDxny+Zxiohcq1Jn3HpOPpDVTf7bVPt6s3wAHV2ojM=:4:22744
c@https://s2.wp.com/_static/??-eJyFkNsOwjAIhl/IWmdm3I3xWbrKFmZbaqEu+vT2QqMumyYkQPg4/OgxKgzW5ROwHopdMqTb060HXulfgPLYJyOw9hhesKUgEET7rKLLPQbWnFu2CaMglawj52ic4mV0JBYPzKaHmaqnFh2ozJAKEKRc1dEM960AwxVhbtlEKEg09qwSMN5hTjfHt8Tlhy1RWdDxny+Zxiohcq1Jn3HpOPpDVTf7bVPt6s3wAHV2ojM=:4:26925

./node_modules/post-robot/src/index.js/_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.RESPONSE]@https://www.paypalobjects.com/api/checkout.js:2569:31
receiveMessage@https://www.paypalobjects.com/api/checkout.js:2611:60
messageListener@https://www.paypalobjects.com/api/checkout.js:2632:13
```

This error message seems to be referencing this function:

```js
export function deserializeError(source : CrossDomainWindowType, origin : string, obj : Object) : Error {
    let err = new Error(obj.__message__);
    if (obj.__code__) {
        // $FlowFixMe
        err.code = obj.__code__;
    }
    return err;
}
```

### Context / Source

This is a user report in 1493824-zen.

**Comment by liviopv** [comment] 2018-10-31 10:14
Somewhat similar to https://github.com/Automattic/wp-calypso/issues/26262

**Comment by sandymcfadden** [comment] 2018-11-28 14:19
Do we have any estimate on when this might be looked at?

**Comment by aisajib** [comment] 2019-04-03 16:01
I just had another user reporting a similar problem in #11750872-hc. They weren't trying to make payments in multiple currencies. It looked like a standard $60 payment button in USD but it was failing.

**Comment by gwwar** [comment] 2019-04-03 17:07
For folks looking please investigate for generic steps or identify if this is happening for specific sites and update issue priority respectively.

**Comment by gwwar** [comment] 2019-05-03 23:56
Are you still looking at this @rodrigoi ?

**Comment by rodrigoi** [comment] 2019-05-04 00:13
Since this issue was isolated to one user with one to many PayPal plugins and wasn't reproducible, let's close it.
Please, reopen if there's another report with as much information as possible to reproduce. If there are new reports, please check the list of active plugins and disable anything that looks payment related.

**Comment by TeniCola** [comment] 2019-05-13 22:41
Sorry to reopen but had another recent instance of this in HC-10951073, currently working with user in ZD-2028524 with included screenshot.

It's a standard $100 USD payment but Paypal and the credit card options won't work and give the same `Payment did not create successfully` message. All I've tried so far is removing the decimals from the amount field, but that didn't work. And the site is simple, so there are no plugins to themes that should be conflicting.

**Comment by mgalbritton** [comment] 2019-05-27 11:43
I have another report of this in chat #13051310-hc. The site is a simple site with no plugins so that isn't the issue.

**Comment by CompChris** [comment] 2019-06-14 19:00
Also happening for this user #13242374-hc. Simple site. See notes.

**Comment by samiff** [comment] 2019-06-14 20:50
Noting that in regards to 13431302-hc user tried creating a manual PayPal "Buy Now" button. After grabbing the button link from the Email tab, upon visiting that PayPal link directly, a `Things don't appear to be working at the moment.` generic error was shown. Having user reach out to PayPal to see why that doesn't seem to be working for them.

**Comment by katiebethbrown** [comment] 2019-07-05 00:25
Another report in #2156039-zen.

Button is set to $1 USD, no decimals. The other buttons on the site aren't working either.

Clicking on them matches Paul's steps in the original post - tab opens and closes and the error is displayed.

**Comment by poojashetty18** [comment] 2019-09-06 11:07
Another issue reported: 15037367-hc
It is standard $300 payment

**Closed** 2019-11-05 16:24 UTC
Labels: Simple Payments, [Pri] High, [Type] Bug
