### ISSUE TITLE
Site Editor: Main screen does not load on some sites (progress bar stuck)

### ISSUE THREAD

**Issue by tellisbethel** [Automattic/wp-calypso#87495] opened 2024-02-15 14:43 UTC
### Quick summary

When a user tries to access the site editor, from Appearance > Editor, or the Home page symlink via Pages, the corresponding template in the site editor fails to load.

### Steps to reproduce

1. Head to Plugins page for either inspireandcleen.com or chadgaming.fr 
2. Turn Gutenberg on quickly
3. Select at Appearance > Editor
4. See the issue
5. (Turn Gutenberg back off for the user's sake)

### What you expected to happen

The site editor's default template should load.

### What actually happened

The progress bar get's stuck and the default template won't load. 

![image](https://github.com/Automattic/wp-calypso/assets/1767799/fb7f3196-efef-426e-ae19-d704844eff64)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

**Workaround**: Head to the template directly for editing or turn off Gutenberg.
**Tickets**: 7710959-zd-a8c, 7727313-zd-a8c

### Troubleshooting info

This issue happens on chadgaming.fr (Atomic - Tsubaki theme) and inspireandcleen.com (Simple and then Atomic - Creatio 2 theme).

I unfortunately have not been able to reproduce on my own sites using the same themes. I spun up a Staging site on chadgaming.fr and turned off all plugins but Gutenberg and the issue persisted.

Another HE tried the following with inspireandcleen.com and was unable to reproduce either:

> I spun up a test site with the same theme, plugins, and PHP version as this site. I also copied their home page to my test site. However, I was unable to reproduce the issue, so no bug report. (7727313-zd-a8c)

**Comment by maciejpilarski** [comment] 2024-02-16 16:49
📌 FINDINGS/SCREENSHOTS/VIDEO
Issue already reported

📌 ACTIONS
– Closed as duplicate of issue https://github.com/Automattic/wp-calypso/issues/85530

**Closed as completed by maciejpilarski** 2024-02-16 16:49 UTC
Labels: Bug, [Pri] Low, Triaged, [Feature] Full Site Editor, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Product] WordPress.com, [Feature Group] Editor Experience
