### ISSUE TITLE
Testimonials toggle in Settings > Writing does not disable the Testimonials CPT

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#54755] opened 2021-07-21 11:02 UTC
The Testimonials menu and the CPT is not disabled when using the Testimonials setting in Settings > Writing
### Steps to reproduce the behavior

1. Go to a Jetpack Site in Calypso
2. Click on Settings > Writing
3. Disable the `Testimonials` CPT

#### What I expected to happen
The Testimonials menu should be removed and the CPT should be disabled
#### What actually happened
The menu is still present and the CPT is still accessible.
#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Atomic and Jetpack

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Jetpack sites
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/995955/126478703-c78b8808-721d-4e41-bd8a-d32d8b9015eb.mov

**Comment by mmtr** [comment] 2021-07-21 11:16
I think this is a duplicate of https://github.com/Automattic/wp-calypso/issues/14912

**Closed as completed** 2021-07-21 11:19 UTC
Labels: Bug, Jetpack
