### ISSUE TITLE
Editor: edit toolbar doesn't dock properly on scroll with featured image

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1790] opened 2015-12-18 13:19 UTC
Steps to reproduce:
1. Start a new post at https://wordpress.com/post and set a featured image
2. Expand the sidebar options on the left to give more room to scroll
3. Scroll down as far as you can
4. Scroll back up slowly and watch for when the edit toolbar snaps back into place

<strong>Result:</strong> the edit toolbar doesn't snap back into place until you reached a fixed point near the top of the post that does not account for the featured image ([38s](https://cloudup.com/c17J09Vh5ZG)).

![screen shot 2015-12-18 at fri dec 18 8 16 36 am](https://cloud.githubusercontent.com/assets/1119271/11897709/e447aa06-a55f-11e5-8760-4fbcc369679a.png)
<sup>Tested using Firefox 42.0 on Mac OS X 10.10.5</sup>

/hat tip @kriskarkoski for the original report

**Comment by youknowriad** [comment] 2016-10-04 09:11
I'm not able to reproduce on Mac Firefox 47.0.1 and on Chrome Version 53.0.2785.116 (64-bit)

**Comment by nitrajka** [comment] 2017-07-17 11:30
Me neither. 
Chrome Version: 59.0.3071.115 (Official Build) (64-bit)
Somebody who can, close this issue, please.

**Comment by beaulebens** [comment] 2017-07-17 17:29
Confirmed this is no longer an issue.

**Closed by beaulebens** 2017-07-17 17:29 UTC
Labels: Editor, [Pri] Normal, [Type] Bug
