### ISSUE TITLE
Fonts not updating when saved

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#67328] opened 2022-09-02 15:44 UTC
### Quick summary

While testing some functionality in Gutenberg I ran across a bug where I would update a font, click save, and then the font would revert to the default upon saving.

https://user-images.githubusercontent.com/5634774/188190374-ad1ffd06-3302-42ab-84cc-541892cd0e6c.mp4

### Steps to reproduce

1. Use theme
2. Go to the **BETA Site editor** (not the regular Gutenburg editor)
3. Go to global styles -> Fonts
4. Change a font, line-height or appearance **for button or header** (only two that seem to be affected, text and link work fine)
5. Click save
6. Notice that font reverted to default in global styles

### What you expected to happen

I expected the font to save.

### What actually happened

The font didn't save.

### Context

It's a relatively new site. I think I created it like 2 weeks ago. 

No JS errors in the console. No failed calls in network tab.

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

I was using blockbase. But this has now been replicated on multiple themes.

### Browser, operating system and other notes

Chrome Version 104.0.5112.101
Mac Monterey 12.5.1

### Reproducibility

Intermittent

**Comment by simison** [comment] 2022-09-02 15:55
Could be related https://github.com/Automattic/wp-calypso/issues/67320

Debugging at Slack p1662132292950649-slack-dotcom-create

**Comment by pbking** [comment] 2022-09-02 15:57
It seems to be specific to headings and button elements.
Changing text and link elements seems to work fine, but (as the video demonstrated) changing the button or (as I found) heading element typography doesn’t stick.

Also it doesn’t seem to be Blockbase related.  I just replicated using Pendant (not a Blockbase child) and the result was the same; button elements and heading element font choices don’t stick.

**Comment by pbking** [comment] 2022-09-02 16:04
This seems to be wpcom specific.  The behavior doesn't happen on a wporg instance.

Also (for any fonts provided either by Blockbase or JetPack's Google Fonts Web Font Provider [this issue](https://github.com/WordPress/gutenberg/issues/43397) would still impact this situation; even if this is resolved the fonts likely won't load in the view.

**Comment by cometgrrl** [comment] 2022-09-02 22:09
Might be a duplicate of [this issue](https://github.com/Automattic/wp-calypso/issues/59259) which is being worked on by @Automattic/dotcom-janitors.

**Comment by autumnfjeld** [comment] 2022-09-05 03:08
cc: @Automattic/ganon for awareness since we are in the middle of the Style Selection in onboarding project: pbxlJb-2gk-p2

**Comment by zachspears** [comment] 2022-09-06 00:05
Looks to be a duplicate of this issue: https://github.com/Automattic/wp-calypso/issues/59259 Closing for now.

**Closed as completed by zachspears** 2022-09-06 00:05 UTC
Labels: Bug, Triaged, [Feature] Google Fonts, [Platform] Simple, [Feature] Global Styles
