### ISSUE TITLE
Gutenberg: verify that needed core api middleware is running

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#28777] opened 2018-11-22 00:08 UTC
This is a follow up to #28615, let's verify that all the proper fetch api core middlewares are running as expected. If not, we should implement them and update this issue.

As we fill in the table, verify if we need the middleware, and if we do ensure that these run in each environment.

https://github.com/WordPress/gutenberg/tree/master/packages/api-fetch/src/middlewares

| middleware | wp-admin  | /gutenberg |
| ------------- | ------------- | ------------- |
| [Fetch All Middleware](https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/middlewares/fetch-all-middleware.js) | Needed, https://github.com/Automattic/wp-calypso/issues/28615 (deployed) | Needed, https://github.com/Automattic/wp-calypso/pull/28644 (deployed) |
| [HTTPv1](https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/middlewares/http-v1.js) | Not needed https://github.com/Automattic/wp-calypso/issues/28777#issuecomment-441092609  |  Not needed https://github.com/Automattic/wp-calypso/issues/28777#issuecomment-441092609  |
| [Namespace Endpoint](https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/middlewares/namespace-endpoint.js) | Not needed https://github.com/Automattic/wp-calypso/issues/28777#issuecomment-441095300 | Not needed https://github.com/Automattic/wp-calypso/issues/28777#issuecomment-441095300 |
| [Nonce](https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/middlewares/nonce.js) | Not needed https://github.com/Automattic/wp-calypso/issues/28777#issuecomment-441283156 | Not needed https://github.com/Automattic/wp-calypso/issues/28777#issuecomment-441283156 |
| [Preloading](https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/middlewares/preloading.js) | Optional #28825 | Not needed https://github.com/Automattic/wp-calypso/issues/28777#issuecomment-441290074 |
| [Root URL](https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/middlewares/root-url.js) | Not needed https://github.com/Automattic/wp-calypso/issues/28777#issuecomment-441292603 | Not needed https://github.com/Automattic/wp-calypso/issues/28777#issuecomment-441292603 |
| [User Locale](https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/middlewares/user-locale.js)| Needed D21305-code (deployed) | Needed, but already handled by `wpcom.js`. However, there is an issue on the API (D21445-code) |

**Comment by mmtr** [comment] 2018-11-22 17:39
## HTTPv1
This middleware transforms all the `PATCH`, `PUT` and `DELETE` requests to `POST` requests.

### Analysis (Gutenberg in Core)

#### `PATCH`
There are no `PATCH` requests.

#### `PUT`
- The `saveEntityRecord` action in `@wordpress/core-data` [makes a `PUT` request](https://github.com/WordPress/gutenberg/blob/509fc16b209e31014c29282c1c47d369fa1041ef/packages/core-data/src/actions.js#L123), which is used for [building shortcuts to the `core-data` actions](https://github.com/WordPress/gutenberg/blob/509fc16b209e31014c29282c1c47d369fa1041ef/packages/core-data/src/index.js#L40), but I don't see any place using neither `saveEntityRecord` nor the shortcuts.
- [Save a post manually](https://github.com/WordPress/gutenberg/blob/509fc16b209e31014c29282c1c47d369fa1041ef/packages/editor/src/store/effects/posts.js#L124) (`@wordpress/editor`).
- [Save a reusable block](https://github.com/WordPress/gutenberg/blob/509fc16b209e31014c29282c1c47d369fa1041ef/packages/editor/src/store/effects/reusable-blocks.js#L125-L128) (`@wordpress/editor`).

#### `DELETE`
- [Trash a post](https://github.com/WordPress/gutenberg/blob/509fc16b209e31014c29282c1c47d369fa1041ef/packages/editor/src/store/effects/posts.js#L272) (`@wordpress/editor`).
- [Delete a reusable block](https://github.com/WordPress/gutenberg/blob/509fc16b209e31014c29282c1c47d369fa1041ef/packages/editor/src/store/effects/reusable-blocks.js#L191) (`@wordpress/editor`).

### Needed in Calypsoified Gutenberg?
As we don't apply this middleware in WP.com, requests are indeed not transformed to `POST` requests, but I don't see any issue when saving a post or a reusable block (which perform `PUT` requests) or when trashing a post or deleting a reusable block (which perform `DELETE` requests)

### Needed in Gutenberg in Calypso?
Our custom `wpcomProxyMiddleware` middleware [transforms all the requests to `POST` requests if they are not `GET` or `DELETE` requests](https://github.com/Automattic/wp-calypso/blob/a4ee3560dfc7f32e3d599a51a9e32536c7460a37/client/gutenberg/editor/api-middleware/index.js#L107-L110), so this is getting the same behavior as Gutenberg in Core for `PUT` requests.

`DELETE` requests are not transformed, but like Calypsoified Gutenberg they are not failing when trashing a post or deleting a reusable block.

### Conclusion

Since I get the expected results I get when testing all the places where Gutenberg makes `PUT` and `DELETE` requests, it looks like this middleware is not needed.

Although it would be great to know why the middleware is included in Core and why the `PUT`/`DELETE` requests are not failing when they are not transformed. /cc @aduth @youknowriad

**Comment by mmtr** [comment] 2018-11-22 17:55
## Namespace Endpoint
This middleware sets the request path concatenating the `namespace` and `endpoint` options.

### Analysis (Gutenberg in Core)
All the requests are using a `path` option, so there are no requests using the `namespace` and `endpoint` options.

### Conclusion
Not needed.

**Comment by mmtr** [comment] 2018-11-23 16:39
## Nonce
This middleware adds the `X-WP-Nonce` header to all the requests so the REST API can validate it.

### Analysis (Gutenberg in Core)
The middleware is created when [registering the Gutenberg scripts](https://github.com/WordPress/gutenberg/blob/bd897f6cb78e7625ad264c7a487bfa950118c85c/lib/client-assets.php#L191) so all the requests will contain nonces.

### Needed in Calypsoified Gutenberg / Gutenberg in Calypso?
Both of them uses a `WPCOM` API instance to interact with the WordPress.com REST API that relies on the iframe REST proxy, so the nonces are not needed.

**Comment by mmtr** [comment] 2018-11-23 17:19
## Preloading
This middleware avoids to make requests to the REST API if the given preloaded data object already contains data for the intended request.

### Analysis (Gutenberg in Core)
The middleware is created when [registering the Gutenberg scripts](https://github.com/WordPress/gutenberg/blob/bd897f6cb78e7625ad264c7a487bfa950118c85c/lib/client-assets.php#L1115) so all the requests are affected by this middleware.

### Needed in Calypsoified Gutenberg?
Since this only improves the performance by not making requests if we already have the data in place, and Calypsoified Gutenberg relies on the Gutenberg plugin, so the server is already preloading some data we could avoid to retrieve every time we need it, I'd say this middleware is optional (#28825).

### Needed in Gutenberg in Calypso?
Calypso doesn't preload any data from the API at the moment.

**Comment by mmtr** [comment] 2018-11-23 17:35
## Root URL
This middleware appends a root to the request path, so the URL becomes `root` + `path`.

### Analysis (Gutenberg in Core)
The middleware is created when [registering the Gutenberg scripts](https://github.com/WordPress/gutenberg/blob/bd897f6cb78e7625ad264c7a487bfa950118c85c/lib/client-assets.php#L199) so all the requests will use the value returned by `get_rest_url()` as the API root URL.

### Needed in Calypsoified Gutenberg / Gutenberg in Calypso?
Both of them uses a `WPCOM` API instance to interact with the WordPress.com REST API that relies on the iframe REST proxy, which always has the same API root URL.

**Comment by mmtr** [comment] 2018-11-26 13:22
## User Locale
It adds a `?_locale=user` to all REST API calls ensuring the returned labels are using the locale defined in the profile of the user

### Analysis (Gutenberg in Core)
As the middleware is [already registered in Gutenberg](https://github.com/WordPress/gutenberg/blob/97d117161042ed6c7bb0acf8d1811112b024822c/packages/api-fetch/src/index.js#L127), all the requests contain the `?_locale=user` param

### Needed in Calypsoified Gutenberg?
Yes: D21305-code. 

### Needed Gutenberg in Calypso?
No, since `wpcom.js` injects the localization param by using the [`addLocaleQueryParam`](https://github.com/Automattic/wp-calypso/blob/49adaac05820e1b323408df1e061d1b59a792090/client/lib/wp/localization/index.js#L45) function.

However, this function doesn't specify `user` as value for the `_locale` param. Instead it sets the selected locale (i.e. `?_locale=es`) and this is causing somehow that the API returns the labels untranslated. Labels are only translated when the param is `?_locale=user`. I'll continue investigating why is this happening.

**Comment by kwight** [comment] 2018-11-27 18:13
Looking at `switch_locale_for_request` server-side, I'm thinking that `user` is being identified correctly as an invalid value (we have no `user.mo` file), and therefore your locale setting is being used down the line. But why `es` (which is a valid value) is returning EN I'm not clear. Furthermore, I can't find references to `->switched_locale` being used elsewhere anyways. Does that help? 🙃

**Comment by mmtr** [comment] 2018-11-28 15:11
Thanks @kwight! I think that the problem was caused by something else and I proposed a solution in D21445-code

**Comment by mmtr** [comment] 2018-12-17 16:03
Closing this since all the needed middlewares have been added. Once WordPress/gutenberg#12365 lands, we should revisit this in order to remove the duplicated middlewares by just defining a custom fetch handler.

**Closed by mmtr** 2018-12-17 16:03 UTC
Labels: [Goal] Gutenberg, [Type] Task
