### ISSUE TITLE
Nav Unification: When clicking on Jetpack, Jetpack > Dashboard, Jetpack > Settings, Plugins Menu is Highlighted

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#50692] opened 2021-03-03 08:04 UTC
When I click on Jetpack, Jetpack > Dashboard or Jetpack > Settings, the Plugins menu item is highlighted rather than Jetpack. It is only when I click on Jetpack > Activity Log and so forth that Jetpack becomes highlighted.

### Steps to reproduce the behavior

1. Go to wp-admin
2. Click on Jetpack, Jetpack > Dashboard, or Jetpack > Settings

#### What I expected to happen

For the Jetpack menu item to be highlighted.

#### What actually happened

It is the Plugins menu item that's highlighted.  If we click on other submenu items of Jetpack, ie Backup, Activity Log, etc, that's when Jetpack is highlighted.

#### Does this happen on simple or atomic sites or both?

Tested and confirmed on multiple Atomic sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Screencast: https://d.pr/v/ZMjT4h

**Comment by getdave** [comment] 2021-03-04 06:52
Thank you for reporting. Duplicate of https://github.com/Automattic/wp-calypso/issues/50713.

**Closed as completed by getdave** 2021-03-04 06:52 UTC
Labels: Bug, [Feature] Calypso & wp-admin Navigation, Triaged
