### ISSUE TITLE
Page Layouts: Heading levels are skipped

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#43891] opened 2020-07-03 21:40 UTC
#### Steps to reproduce

1. Create a new page
2. Select one of the following Page Layouts with a red border:

![Screen Shot 2020-07-03 at 4 18 58 PM](https://user-images.githubusercontent.com/3696121/86497939-32c11b80-bd49-11ea-972b-a96b550a7280.png)

![Screen Shot 2020-07-03 at 4 21 26 PM](https://user-images.githubusercontent.com/3696121/86498014-98150c80-bd49-11ea-8ea2-a9afa1a03538.png)

![Screen Shot 2020-07-03 at 4 24 23 PM](https://user-images.githubusercontent.com/3696121/86498067-dad6e480-bd49-11ea-9ad1-a31db4eeb04a.png)

![Screen Shot 2020-07-03 at 4 26 39 PM](https://user-images.githubusercontent.com/3696121/86498181-4f118800-bd4a-11ea-8aa9-7ae33df71a2c.png)

![Screen Shot 2020-07-03 at 4 29 22 PM](https://user-images.githubusercontent.com/3696121/86498297-dced7300-bd4a-11ea-97fc-bae8332b2045.png)

![Screen Shot 2020-07-03 at 4 33 37 PM](https://user-images.githubusercontent.com/3696121/86498513-bc71e880-bd4b-11ea-9b0c-9e940a95d0f5.png)

3. Click on the "Content Structure" button (if one of the red-bordered pages doesn't display a warning, then it was marked because it has a paragraph block that's styled as a heading)

#### What I expected

For the heading levels to be respected: H1 (page title) > H2 > H3 > H4 > H5 > H6

#### What happened instead

Many heading levels are skipped

#### Browser / OS version

Firefox 78.0.1 (64-bit)

#### Screenshot / Video

![Screen Shot 2020-07-03 at 4 12 27 PM](https://user-images.githubusercontent.com/3696121/86497620-ff31c180-bd47-11ea-81dd-30cddaa761c9.png)

#### Context / Source

#dogfooding

**Comment by jeyip** [comment] 2020-11-11 23:40
I was able to reproduce this issue easily with the provided instructions. I didn't check every page, but I did confirm issues with  skipped heading ranks on a sample from the About Page templates, Blog Page templates, Contact Page templates, and Menu Page templates.

It looks like the only reason we skipped heading ranks was to modify font size. I see the easiest solution being to refactor the rendered content for page templates. Rather than using heading ranks to change font size, we can use the correct heading ranks with customized font sizes (from block settings).

Ex. In the one offending Menu Page Template, there is a `h4` header used. We can, alternatively, use an `h2` with a font size of `20px`.

There's a relevant discussion in #43892, an issue that also deals with skipped heading levels, but for Block Patterns instead of Page Templates.

**Comment by davipontesblog** [comment] 2021-03-16 13:12
I am moving this to the triaging board to see if it's still an issue with the new layout picker on simple sites. If so, we can close it.

**Comment by synora** [comment] 2021-03-16 18:54
Keeping open due to the ongoing conversation at https://github.com/Automattic/wp-calypso/issues/43892.

**Comment by kwight** [comment] 2021-04-20 19:57
@ianstewart Would you call this a dupe of #43892, meaning the fix for that issue would fix this at the same time – or are they separate mechanisms?

**Comment by ianstewart** [comment] 2021-04-28 14:14
This is a duplicate. I'll close it for now in favour of that issue.

**Closed by ianstewart** 2021-04-28 14:14 UTC
Labels: Accessibility, Triaged, [Pri] Low, [Type] Bug
