### ISSUE TITLE
Editor: Pattern selector not working properly on mobile

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#51085] opened 2021-03-16 02:21 UTC
### Steps to reproduce the behavior

1. Add a post or a page using a mobile device (I used an iPhone).
2. Click on the + button in the top left corner of the editor. In the overlay switch to the Patterns tab.
3. Click on the list and select a category.
4. I'm not able to preview patterns in the selected category. The whole overlay closes and I'm back in the editor.

Here's a quick video: https://cloudup.com/cxxAbw5q06w

#### What I expected to happen
I expected to be able the select a pattern category and browse patterns.

#### What actually happened
The overlay closes.

#### Browser / OS version
iOS 14.4.1 / Safari

**Comment by cathymcbride** [comment] 2021-03-16 15:44
FYI @apeatling

**Comment by apeatling** [comment] 2021-03-31 16:40
Possible duplicate https://github.com/WordPress/gutenberg/issues/29243

**Comment by apeatling** [comment] 2021-04-08 20:55
Duplicate of WordPress/gutenberg#29243

**Closed as completed by apeatling** 2021-04-08 20:55 UTC
Labels: Bug, Patterns
