### ISSUE TITLE
Horizon Gutenboarding: Fonts screen not loading preview.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#47119] opened 2020-11-04 20:32 UTC
Here's what I'm seeing …

![image](https://user-images.githubusercontent.com/545779/98164834-7cae3f80-1eaa-11eb-9315-d0131061c4d7.png)

What I should be seeing is a preview that matches the design I picked on the previous step …

![image](https://user-images.githubusercontent.com/545779/98164866-8c2d8880-1eaa-11eb-8086-810621fdc074.png)

**Comment by simison** [comment] 2020-11-06 11:19
Does the theme (seedlet-blocks) have a demo site? The endpoint does this and might not recover if that doesn't work:

```php
// If the template name refers to a design demo site that we have especially prepared then let's show that
$demo_url = $template_helpers->get_design_demo_url( $template_name );

// Now let's see if there's a registered theme
if ( ! $demo_url ) {
  $demo_url = wpcom_get_theme_demo_site( 'pub/' . $theme_name );
}
```

**Comment by ianstewart** [comment] 2020-11-06 20:03
https://seedletblocksdemo.wordpress.com/

**Comment by jeyip** [comment] 2020-11-24 23:42
After some digging, the problem is that when the PR to make seedlet blocks on horizon FSE was merged https://github.com/Automattic/wp-calypso/pull/46829, it's accompanying wpcom diff (D51883-code) was never merged. 

I think this was an oversight, but I'll double check with the original author now.

**Comment by jeyip** [comment] 2020-11-24 23:48
I verified that it was a mistake. I'll be merging the wpcom diff shortly.

**Comment by apeatling** [comment] 2020-11-24 23:50
Yes, my mistake I was juggling too many PRs across projects and completely forgot to merge the diff. Thanks for finding!

**Comment by jeyip** [comment] 2020-11-25 00:04
Double checked in production using the FSE horizon onboarding flow. https://horizon.wordpress.com/new?flags=gutenboarding/site-editor

The issue is now fixed and we're good to go 🎉

**Closed** 2020-11-25 00:04 UTC
Labels: [Goal] New Onboarding, [Type] Bug
