### ISSUE TITLE
FSE Round 3 Alpha test - Calendar Block shows blank

### ISSUE THREAD

**Issue by rinazrina** [Automattic/wp-calypso#51887] opened 2021-04-13 09:42 UTC
When adding the Calendar block, it shows a line with blank. No calendar is showing. 

#### What I expected to happen
The calendar is showing as demonstrated in [this support doc](https://wordpress.com/support/wordpress-editor/blocks/calendar-block/#using-the-calendar-block).

#### What actually happened
When adding the block, it only shows a line with a blank content

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/33721365/114532439-6d17fb80-9c7f-11eb-82c2-f551b784a33f.mov

**Comment by david-szabo97** [comment] 2021-05-04 07:49
Anything that I need to do to reproduce this?

Inserted a Calendar block to the Footer template part and the template itself too, both work fine.

**Comment by david-szabo97** [comment] 2021-05-04 11:27
**UPDATE:** It shows a blank line because there are no posts on the site. So the calendar returns nothing in the editor. But for some reason, it renders the calendar on the frontend 🤔

**Comment by david-szabo97** [comment] 2021-05-05 14:58
**UPDATE:** Created a PR 31504-gh-WordPress/gutenberg  that adds an empty state to the block. Since the Calendar is only shown when the site has at least one post. Now I just need to figure out why the calendar is still rendered on WPcom when there are no posts on the site 🤔

**Comment by david-szabo97** [comment] 2021-05-18 15:55
**UPDATE:** Figured out the issue above. Left comments on the PR.

**Comment by david-szabo97** [comment] 2021-07-06 11:15
Fixed by 31504-gh-WordPress/gutenberg

**Closed as completed by david-szabo97** 2021-07-06 11:15 UTC
Labels: Bug, [Goal] Full Site Editing
