### ISSUE TITLE
Problems upgrading to Business and Commerce plans after purchasing storage addon

### ISSUE THREAD

**Issue by s1sfa** [Automattic/wp-calypso#84239] opened 2023-11-16 14:18 UTC
### Quick summary

I was doing some testing at the dotcom division meetup and found some problems upgrading to business and commerce plans after purchasing storage upgrade.

### Steps to reproduce

1. Have a site on premium plan with storage addon
2. goto purchase plans
3. business plans and commerce plans may be greyed out and show "Contact Support".
4. The upgrade button is only available if the storage drop down at the bottom of the plan matches the storage addon purchased
5. I've seen this "Contact Support" displayed as the default in some cases and other cases the default display has the upgrade button enabled.

### What you expected to happen

To be able to upgrade or the the clear way shown to upgrade without contacting support

### What actually happened

Upgrade doesn't appear to be available with no way in the UI telling people why or how to continue to try to upgrade without needing to contact support.

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by s1sfa** [comment] 2023-11-16 14:58
Additionally the drop down for storage still shows additional price and doesn't seem to account that storage addon as already purchased.

**Comment by maciejpilarski** [comment] 2023-11-27 15:19
📌 REPRODUCTION RESULTS
– Tested on Simple – Could Not Replicate 
– Tested on Atomic – Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to reproduce the issue. I have:
1. Purchased the Premium plan
2. Added 50 GB add-on
3. Upgraded to Business plan 

![Markup 2023-11-27 at 16 16 34](https://github.com/Automattic/wp-calypso/assets/9025643/1f25fc2b-9f3a-4734-941e-d5872400735e)

📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)

**Closed as completed by maciejpilarski** 2023-11-27 15:19 UTC
Labels: Bug, [Feature] Plans & Upgrades, [Pri] Normal, [Feature Group] WPCOM Store & Purchases, Triaged, [Platform] Simple, [Platform] Atomic, [Product] WordPress.com
