### ISSUE TITLE
Reader: add username autocompletion to comments

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#797] opened 2015-11-25 20:01 UTC
Raised by @bluefuton 

Usernames with @ should auto-complete:

![mnn8bbniek](https://cloud.githubusercontent.com/assets/17325/8151283/3923e624-135d-11e5-90e4-e508b2bf83e8.png)

**Comment by blowery** [comment] 2015-12-01 19:33
dupe of #933

**Closed by blowery** 2015-12-01 19:33 UTC
Labels: Reader, [Pri] Low, [Type] Enhancement
