### ISSUE TITLE
InlineHelp: Update/Add e2e tests

### ISSUE THREAD

**Issue by retrofox** [Automattic/wp-calypso#44025] opened 2020-07-09 09:45 UTC
We've changed considerably the UI some components related to the inline-help/help-search and its visualization. 
Create and update e2e in order to get more confident with these changes.

**Comment by obenland** [comment] 2020-08-13 15:48
Duplicate of https://github.com/Automattic/wp-calypso/issues/44169

**Closed by obenland** 2020-08-13 15:48 UTC
Labels: [Tests] Includes Tests, [Type] Enhancement
