### ISSUE TITLE
Editor: "Copy All Content" changes Gallery Blocks into List Blocks

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#29921] opened 2019-01-05 13:27 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post/
2. Add a Gallery Block
3. Click on the "Show more tools & options" on the top right
4. Click on "Copy All Content"
5. Open a new post: https://wordpress.com/block-editor/post/
6. Paste the clipboard in the context box
7. All the other paragraphs will be pasted correctly, but the Gallery Block will be turned into a List Block

#### What I expected

Since we're just copying posts in the same site (so it's the same attachment IDs), the Gallery Block should be copied

#### What happened instead

The Gallery was transformed into an empty list

#### Browser / OS version

Mac OS 10.14.2
Chrome 71.0.3578.98

#### Screenshot / Video

http://cld.wthms.co/qAsI2h

#### Context / Source

Reported in 1691525-zen

#user-report

**Comment by arunsathiya** [comment] 2019-01-05 14:15
I am able to reproduce it on core Gutenberg as well - tested on a Jurassic Ninja site. 

@liviopv, since this is reproducible on core Gutenberg, can you report it on `WordPress/Gutenberg`, please? Changes would be ported to WordPress.com's Gutenberg when it's fixed in core.

I am closing this report at the moment.

**Closed by arunsathiya** 2019-01-05 14:15 UTC
Labels: Gutenberg core, [Goal] Gutenberg, [Type] Bug
