### ISSUE TITLE
Coblocks: Custom URLs in galleries invalidates the block content

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#34843] opened 2019-07-23 16:57 UTC
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/block-editor/page
2. Add a Coblocks gallery block.
3. Under "Link Settings" in the Block Settings, choose Custom URL.
4. Enter addresses with http:// or https:// in the gallery image custom URLs.
5. Publish the page/post.

#### What I expected

To be taken to the external website upon clicking the gallery image.

#### What happened instead
You're taken to: https://mygroovysite.wordpress.com/coblocks/www.blah.com

This is odd because A) it creates a coblocks slug and B) we don't actually allow periods in our slugs, we convert them to dashes.

Also, when you open the post in the editor again, it becomes an "Attempt block recovery". If you recover the block, all links are lost.

#### Browser / OS version

Version 75.0.3770.144 (Official Build) (64-bit) Chrome OS

#### Screenshot / Video

![Screen Shot on 2019-07-23 at 11_36_15](https://user-images.githubusercontent.com/10121835/61731331-de43ac80-ad40-11e9-8ed0-760b1ee22c5e.png)

**Comment by AtrumGeost** [comment] 2019-07-28 16:26
Got this same issue. Only that I would get the `This block contains unexpected or invalid content.` error with any custom URL I add.

Here's a quick video:

https://cld.wthms.co/GdJ8NF

**Browser / OS version**
Google Chrome Version 75.0.3770.142 (Official Build) (64-bit) | macOS Mojave 10.14.5 (18F132)

**Comment by katiebethbrown** [comment] 2019-08-16 22:44
I had another report of this today in #13850331-hc. 

I was able to reproduce on my test site as well (simple site). When I try and resolve the block after returning to the post/page I can see it's wanting to remove a trailing slash from the <img> tags and then wrap the links inside an extra figure tag. Here's what I see:

<img src="https://cdn-std.dprcdn.net/files/acc_680347/Z5xX6B">

The console shows the block validation error as well:

<img src="https://cdn-std.dprcdn.net/files/acc_680347/vUBmDv">

**Comment by mmtr** [comment] 2019-08-17 03:06
There are actually 2 issues here:
- WP.com is stripping out the `data-imglink` attributes added to the images, causing the "This block contains unexpected or invalid content." error. This should be fixed by D31657-code.
- The URLs are not being sanitized / validated, so entering an URL without the schema (`http(s)://`) will create a relative URL. This issue is also present in the plugin itself, so I reported it there: https://github.com/godaddy/coblocks/issues/747

**Comment by mmtr** [comment] 2019-08-17 04:49
> I also noticed that there is no correlation between the links set in the link overlay in the block and the "Link Settings" area in the sidebar

This is normal, @katiebethbrown. The "Link Rel" setting is intended to set the [`rel` attribute of the link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-rel).

**Comment by katiebethbrown** [comment] 2019-08-19 03:10
>This is normal, @katiebethbrown. The "Link Rel" setting is intended to set the rel attribute of the link.
Oops - I totally missed that. Thanks for letting me know!

**Comment by kwight** [comment] 2019-08-19 17:26
Closed in D31657-code.

**Closed by kwight** 2019-08-19 17:26 UTC
Labels: [Goal] Gutenberg, [Type] Bug
