### ISSUE TITLE
Problems uploading videos using Add Media Button

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#10618] opened 2017-01-13 15:21 UTC
#### Steps to reproduce
1. Add Media button in Calypso, at https://wordpress.com/page/---/294 to add one of those 2 videos in the media library for this site.
2. The generated shortcode is [wpvideo ---], so it doesn't work as expected and instead of the video‘Uploading’ screen 

#### What I expected
I expected Video correctly uploaded and showing

#### What happened instead
You get an ‘Uploading’ screen 

#### Context / Source
Note: Doing it from https://---.wordpress.com/wp-admin/post.php?post=292&action=edit works neat. And the generated shortcodes, using the wp-admin Add Media button are

['video width="640" height="352" mp4="https://---.files.wordpress.com/2016/12/---.mp4"][/video]
or
['video width="640" height="352" mp4="https://---.files.wordpress.com/2016/12/---.mp4"][/video]

#user-report

**Comment by rachelmcr** [comment] 2017-12-23 16:33
Closing as I can't reproduce this issue with the steps provided.

#bug-scrub #pre-gutenburg-bug-purge

**Closed by rachelmcr** 2017-12-23 16:33 UTC
Labels: Editor, Media, [Type] Bug
