### ISSUE TITLE
Billing History: WordPress.com logo is broken in the receipts.

### ISSUE THREAD

**Issue by chaitanyamsv** [Automattic/wp-calypso#22975] opened 2018-03-04 21:53 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/purchases/billing/
2. Click on View Receipt under any receipt

#### What I expected
See the WordPress.com logo in the receipt.

#### What happened instead
Broken logo link in the receipt like this: 
![broken wpcom logo in the receipts](https://user-images.githubusercontent.com/1519466/36951011-3ef1f76a-2063-11e8-84ea-33c0b9fa9ac5.png)

The logo is linking to https://s2.wp.com/wp-content/themes/a8c/public-api/tabs/images/wpcom-logo-420.png at which I see "We couldn’t find what you were looking for." message.

**Comment by rachelmcr** [comment] 2018-03-05 11:37
Hm, I couldn't reproduce this issue. When I check my receipt (in macOS/Chrome) I see the WordPress.com logo as expected:

![screenshot 2018-03-05 11 29 02](https://user-images.githubusercontent.com/8658164/36973122-916078a4-2069-11e8-950e-4159ded9b59e.png)

The logo source is this: https://wordpress.com/wp-content/themes/h4/tabs/images/wpcom-logo-420.png

**Comment by designsimply** [comment] 2018-03-09 20:49
I spotted this during testing. The logo looks broken for me in both staging and production and in Chrome as well as Firefox. 

The logo source is showing up with a `s2.wp.com` domain for me if I check page source in a browser:

> https://s2.wp.com/wp-content/themes/a8c/public-api/tabs/images/wpcom-logo-420.png

<sup>Seen at https://wordpress.com/me/purchases/billing/28364387 using Firefox 58.0.2 on macOS 10.13.3.
![screen shot 2018-03-09 at fri mar 9 1 25 53 pm](https://user-images.githubusercontent.com/1119271/37229099-20f36646-23a0-11e8-9c13-b58874152b49.png)
</sup>

**Comment by kwight** [comment] 2018-03-12 20:42
Hm, this is a fail on the part of a server-side `get_stylesheet_directory_uri()` call; the theme is being identified as the API's theme, rather than the old `h4`. The URL should be: `/wp-content/themes/a8c/h4/tabs/images/wpcom-logo-420.png`. Really, there's no reason this logo shouldn't be in Calypso itself.

**Comment by kwight** [comment] 2018-03-15 17:00
Fix for review in D10950-code.

**Comment by kwight** [comment] 2018-03-15 21:42
Fixed in r171798-wpcom.

**Closed by kwight** 2018-03-15 21:42 UTC
Labels: Billing, Me, [Type] Bug

**Comment by chaitanyamsv** [comment] 2018-03-15 23:01
Thank you @kwight !
