### ISSUE TITLE
Blog Posts Merging Content in Query Block

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#60209] opened 2022-01-18 19:01 UTC
### Quick summary

The customer had two blog posts. They had the Query block on their home page. The first post was perfect. The second showed the Featured image and title of the second post, but displayed the content of the first post.

![Screen Shot 2022-01-18 at 12 21 29](https://user-images.githubusercontent.com/2545184/150001579-1dd93a3a-8ef1-4c6f-8a5b-e9a347d5cefa.png)

#741744-hc

### Steps to reproduce

I was not able to replicate on my test site. The customer has a Premium plan. 

### What you expected to happen

Each post would show their own unique content.

### What actually happened

The content of the first post merged into the second.

### Workaround details

I had them use the Posts block instead.

**Comment by Greatdane** [comment] 2022-02-03 05:00
Unable to replicate this, and user no longer has it on their blog. Closing this for now, we can re-open if the issue is replicated.

**Comment by JessBoctor** [comment] 2022-03-17 23:14
I ran into this again in #34270386-HC

In this case, the customer's first post content was being merged across pagination pages

**Comment by filipanoscampos** [comment] 2022-03-18 13:07
Another case here: #34741194-hc, and then continued here 4871137-zd-woothemes

I should add that when the sticky post is removed, the Query Loop starts behaving strangely.

The content was then shown on the first post listed on the second blog post list page.

After the user added another post, the issue changed.
A Featured Image appeared beneath the first blog post listed on every Blog Post List page.
And beneath the single posts.

We shared some CSS with the user.
Yet, every time a change is made, we need to change the CSS to solve a new and unexpected issue.

**Comment by eduardozulian** [comment] 2022-03-18 19:10
On top of what @filipanoscampos wrote, I think we have another workaround here.

If the page has only a single query block, check the **Inherit query from template** option on My Site > Site Editor > Template > Index. This will turn paginations from `?query-1-page=2` to `/page/2/.  Since the user in 4871137-zen has only a single query on a blog page, it could help.

I tried to reproduce the actual problem on my end but no luck.

**Comment by Addison-Stavlo** [comment] 2022-10-11 20:18
Is this issue still being experienced?

**Comment by Addison-Stavlo** [comment] 2022-10-31 12:49
Closing since this isnt replicated or had any noted issues since march. Feel free to ping/re-open if its still an issue!

**Closed as completed by Addison-Stavlo** 2022-10-31 12:49 UTC
Labels: Bug, Triaged
