### ISSUE TITLE
Posts list displays "You haven't created any content yet" while loading

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#17348] opened 2017-08-18 19:45 UTC
![2017-08-18t14 42 24-0500](https://user-images.githubusercontent.com/227022/29474984-8af379b8-8423-11e7-9250-a62117662da0.png)

This should just be a loading placeholder instead.

Note I'm loading `/posts/:site` in the screenshot above, but that's with https://github.com/Automattic/wp-calypso/pull/17196 and the `ENABLE_FEATURES=posts/post-type-list` feature flag.

This is the same post listing normally used for custom post types; I didn't see the issue in brief testing with the "standard" post listing but that could use confirmation.

**Comment by mattsherman** [comment] 2017-09-28 16:34
@nylen I can't reproduce this... do you have more detailed steps that I could follow? Here is what I tried to reproduce it...

1. Clear site data (everything except for cookies) (I tried both with clearing and without, with no difference in behavior)
2. Load `/posts/:site` or `/posts/my/:site` (again, no difference)

In every case, I saw the loading placeholder. I was unable to get the "You haven't created any content yet" message to appear.

![screencapture at thu sep 28 12 30 33 edt 2017](https://user-images.githubusercontent.com/2098816/30978643-1e8de812-a449-11e7-8454-02134346ad98.png)

**Comment by nylen** [comment] 2017-10-06 19:18
I'm only able to reproduce this issue on my main a12 account with lots of sites.

I tried on a less-heavily-used test account, including tweaking the timing of API responses so that `/me/sites` takes longer than the list of posts, but I didn't see any problems there.

As far as I can tell, if we want to try to figure out what's going on here, we'll need to use my account.  I'm not sure how much value there is in doing that, if it's really only affecting my account.

**Comment by mattsherman** [comment] 2017-12-01 14:44
@nylen @michaeldcain Is this still occurring for either of you?

**Comment by michaeldcain** [comment] 2017-12-04 15:09
@mattsherman I can't seem to reproduce this, even on my a11n account with all the sites. As an edge case, I'd be fine with closing it.

**Comment by mattsherman** [comment] 2017-12-08 15:38
Closing this. If it crops back up it can be re-opened.

**Closed by mattsherman** 2017-12-08 15:38 UTC
Labels: Posts, [Type] Bug
