### ISSUE TITLE
Hever Theme: Changing Tertiary color affects footer menu link hover color

### ISSUE THREAD

**Issue by ha-un** [Automattic/wp-calypso#71255] opened 2022-12-16 00:17 UTC
### Quick summary

When selecting a color for the `Tertiary` color in the Hever theme, the footer link hover color is affected.

### Steps to reproduce

1. Create a new site
2. Change theme to `Hever`
3. Change `Tertiary` color in the customizer.

### What you expected to happen

When hovering on WordPress.com or other menu links, the link color should be showing the tertiary color set in the customizer (or at least remain in the default gray color)

### What actually happened

When hovered, the link turns light blue (or sometimes white depending on color set).

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Yes, it has been tested with Hever, and did not replicate when testing with Varia, which is its parent theme.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Setting the color back to `#c5c5c5` (its default color) seems to work, but any other colors will not accurately be shown.

**Comment by cuemarie** [comment] 2022-12-24 19:06
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- In my test, the color of links in the hover state follows the **Primary** color, not the Tertiary color:

<img width="1218" alt="Markup 2022-12-24 at 12 05 04" src="https://user-images.githubusercontent.com/27249804/209448471-ffd138c6-c8fd-4d5f-8084-aabcec4a8ecb.png">

📌 ACTIONS
- Closed as by design

📌 Message to Author
- @ha-un is there anywhere that you saw that the Link hover color _should_ be impacted by the Tertiary color for the Hever theme? If so, that may help reopen and clarify this issue.

**Closed as completed by cuemarie** 2022-12-24 19:06 UTC
Labels: Bug, [Pri] Low, [Platform] Simple
