### ISSUE TITLE
Cart and Checkout page not working on Tsubaki theme

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/wp-calypso#80926] opened 2023-08-22 14:26 UTC
### Quick summary

When the Tsubaki theme is active when Woocommerce is activated the Cart and Checkout page don't seem to work. 

It only happens when the Woocommerce settings page displays this in the advanced tab: 

![Markup on 2023-08-22 at 11:39:54](https://github.com/Automattic/wp-calypso/assets/5507879/0c46fc84-fb59-445a-ac3d-28ee9728b2be)

If the pages are created in the old way of selecting pages the theme works as expected:

![Markup on 2023-08-22 at 12:58:28](https://github.com/Automattic/wp-calypso/assets/5507879/5dd905f1-f6fa-4941-b423-890b300a684b)

Inspired on this bug report I tried deactivating Page Optimize and that solved the issue. 
https://github.com/Automattic/wp-calypso/issues/77366

I was able to replicate in a test site. 

### Steps to reproduce

Open a new site, activate Tsubaki and setup a webstore. 

The cart and checkout page are setup as theme template files but when testing the webstore the pages will not open. 

### What you expected to happen

I expected the checkout flow to work 

### What actually happened

The pages stayed blank or returned a 404 error

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

Two possible workarounds:

Create the pages for Cart and Checkout while a classic theme was active and activate Tsubaki afterwards. 
Deactivate the Page Optimize plugin

**Comment by cuemarie** [comment] 2023-08-23 00:05
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
I tried replicating this on Site ID: 221371699

- Site was created 2023-07-17, AT'd on 2023-08-15 
- I activated Tsubaki (first) and then set up a new store for it today
- My `/wp-admin/admin.php?page=wc-settings&tab=advanced` page shows:
![Markup on 2023-08-22 at 17:02:04](https://github.com/Automattic/wp-calypso/assets/27249804/0b76ad0b-2226-4515-881c-4a79ac1773ee)
- I created a quick test product and added it to my cart. Both the `/cart` page and `/checkout` page load as expected.
- **Page Optimize** is active on my site

<details><summary> ⚠️ Woo Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): https://mcqdelete3546435365.wpcomstaging.com
Site address (URL): https://mcqdelete3546435365.wpcomstaging.com
WC Version: 8.0.2
REST API Version: ✔ 8.0.2
WC Blocks Version: ✔ 10.6.5
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.30
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.2
WC Database Prefix: wp_
Total Database Size: 10.44MB
Database Data Size: 7.35MB
Database Index Size: 3.09MB
wp_woocommerce_sessions: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_cache: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.42MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 1.34MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 7
customize_changeset: 3
elementor_library: 1
jetpack_migration: 2
mailpoet_page: 1
page: 17
post: 28
product: 1
revision: 73
shop_order: 1
wp_global_styles: 6
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Crowdsignal Forms: by Automattic – 1.7.0
WordPress.com Editing Toolkit: by Automattic – 3.76085
Gutenberg: by Gutenberg Team – 16.4.0
Jetpack: by Automattic – 12.5-a.11
Layout Grid: by Automattic – 1.8.4
Page Optimize: by Automattic – 0.5.3
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.11

WooCommerce Payments: by Automattic – 6.3.2
WooCommerce: by Automattic – 8.0.2

### Inactive Plugins (2) ###

Classic Editor: by WordPress Contributors – 1.6.3
WP Rollback: by GiveWP.com – 1.7.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #113 - /shop/
Cart: #114 - /cart/
Checkout: #115 - /checkout/
My account: #116 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Tsubaki
Version: 1.2.2
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /wordpress/plugins/woocommerce/8.0.2/packages/woocommerce-blocks/templates/notices/error.php
/wordpress/plugins/woocommerce/8.0.2/packages/woocommerce-blocks/templates/notices/notice.php
/wordpress/plugins/woocommerce/8.0.2/packages/woocommerce-blocks/templates/notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-23 00:22:38 -07:00
Options: ✔
Notes: 61
Onboarding: completed

### WooCommerce Payments ###

Version: 6.3.2
Connected to WPCOM: Yes
Blog ID: 221371699
Account ID: -

### Action Scheduler ###

Complete: 30
Oldest: 2023-08-16 17:21:46 -0700
Newest: 2023-08-22 16:58:56 -0700

Failed: 8
Oldest: 2023-08-16 17:37:35 -0700
Newest: 2023-08-22 17:02:44 -0700

Pending: 3
Oldest: 2023-08-22 17:04:44 -0700
Newest: 2023-08-23 16:55:50 -0700


### Status report information ###

Generated at: 2023-08-22 17:02:56 -07:00
```

</details>

📌 ACTIONS
- Requested author feedback

📌 Message to Author
@dolgelukkig I wasn't able to reproduce this.  Can you spot anything in my test that I ran that differs from what you observed/tested?

**Comment by daledupreez** [comment] 2023-08-29 14:25
Pinging @Automattic/somewherewarm for visibility, as this may have to do with how we're setting up the Woo templates on Atomic sites.

**Comment by cuemarie** [comment] 2023-08-30 23:37
Moving this forward for further tracking/investigation. Thanks @daledupreez !

**Closed as completed** 2024-10-15 15:14 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Low, Triaged, WooCommerce, Woo Express, [Product] WordPress.com, [Feature] .Org Themes

**Comment by beaulebens** [comment] 2024-10-17 22:41
@opr since this sounds like something related to cart/checkout specifically, can someone from Rubik please take a look and see if you can reproduce?

**Comment by mikejolley** [comment] 2024-10-18 08:26
I briefly checked this theme locally and had no issue. I didn't delve too deep because the screenshot in the report was something we reverted/replaced due to similar issues last year which was fixed:

https://github.com/woocommerce/woocommerce-blocks/pull/10773
