### ISSUE TITLE
Blog Posts Block displays only the first 10 posts set on Choose Specific Posts

### ISSUE THREAD

**Issue by RafaelFunchal** [Automattic/wp-calypso#46700] opened 2020-10-22 21:12 UTC
#### Steps to reproduce

1. Add the Blog Posts Block to the content.
2. On `Display Settings`, select `Chosse Specific Posts`.
3. Add more than 10 posts manually to the Posts field.

#### What I expected
See the entire list of posts added to the block.

#### What happened instead
Only the first 10 posts are displayed.

#### Browser / OS version
Latest Firefox and Chrome on macOS Catalina

#### Screenshot / Video
<img width="1616" alt="Screenshot 2020-10-22 at 17 30 45" src="https://user-images.githubusercontent.com/1847217/96929845-33fd8c00-1491-11eb-88de-be961e486a74.png">

#### Context / Source
Reported on 22863341-hc

The user couldn't wait and decided to keep working on the content. They figured out a workaround to display all 23 blog posts:

> I used three separate blocks with up to 10 in each and it seems to have worked

**Comment by cathymcbride** [comment] 2020-10-30 15:33
Does this block use the value from the Blog Post Display Setting, which defaults to 10?
![image](https://user-images.githubusercontent.com/16654218/97724766-babef400-1aa3-11eb-8a83-294293cba9f5.png)

**Comment by RafaelFunchal** [comment] 2020-10-31 13:24
Good point @ @cathymcbride . My understanding is that, since the block settings allow more than 10 posts, it should display them all or at least display the Load More button.

**Comment by cathymcbride** [comment] 2020-11-02 16:30
Can you verify the behavior here? Are you able to repro and does it change when you update the setting? I'm seeing that site setting override the block setting, which is what I would expect, and is what I'm seeing in my ad-hoc testing.
@davemart-in what is your expectation of behavior here?

**Comment by davemart-in** [comment] 2020-11-02 19:38
I'm guessing it uses that default setting. We could expose that setting in the block settings, but customers might be caught off guard when it changes the number of blog posts to display on all post blocks and pages.

This may need some design consideration.

**Comment by kylemcph** [comment] 2020-11-04 10:47
Another case reported in 24794525-hc, follow-up ticket 3457739-zen.

**Comment by xpurichan** [comment] 2020-11-30 17:12
Another report in 23406520-hc.

Just to confirm, if we try and change the feed setting number (defaults to 10) or the blog posts "Display x per page" (defaults to 10) options neither of them have an effect on this limit for the blog posts block.

**Comment by JoshuaGoode** [comment] 2021-02-15 19:10
Tested on Simple but could not reproduce. Added 13 posts and all display in the editor and when viewing the page on the front end.

> Gutenberg: v9.9.2
> CoBlocks: 2.5.3
> Editing Toolkit: 2.19

Video:


https://user-images.githubusercontent.com/4887830/107985010-3da68480-6f97-11eb-985a-1105932b68af.mov


---

This appears to have been resolved by a change in https://github.com/Automattic/newspack-blocks but could not identify associated PR or closed issues there that explicitly detail this issue.

While possibly not the source of the fix, noting that there was a recent refactor to how the block handles specific posts here: https://github.com/Automattic/newspack-blocks/pull/689

Which was merged into Simple via an Editing Toolkit update: https://github.com/Automattic/wp-calypso/pull/49778

Since I could not identify a PR explicitly targeting this issue, closing with not reproducible label.

---

@cathymcbride  As for issues related to Newspack blocks, should they be moved to https://github.com/Automattic/newspack-blocks or should we add a label here for these blocks for that team to review?

**Closed** 2021-02-15 19:18 UTC
Labels: Blocks, Editor, Involves Happiness, [Closed] Not Reproducible, [Pri] Low, [Size] S
