### ISSUE TITLE
Desktop App: User Documentation Background is Black with Black text

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#74802] opened 2023-03-22 20:52 UTC
### Quick summary

When accessing user documentation from a link on your dashboard in the WP.com Desktop App, it displays the support page background in all black so the black text is not readable.

### Steps to reproduce

1. Open your dashboard in the WordPress.com Desktop App
2. Click on the **Do I Need a Website, a Blog, or a Website with a Blog?** link on the My Home page of the dashboard

### What you expected to happen

I expected to be able to read the linked user documentation

### What actually happened

The user documentation opened with a black background and black text so that I can't read it.

<img width="1124" alt="WPCom App" src="https://user-images.githubusercontent.com/32983813/227035033-1d7f8e19-696b-4df5-b3e0-c27a7e597c07.png">

### Impact

All

### Available workarounds?

Yes, easy to implement

### Logs or notes
6060181-zen

_No response_

**Comment by cuemarie** [comment] 2023-03-29 20:16
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described - all documentation seems to open with that dark background, making them unreadable

https://user-images.githubusercontent.com/27249804/228656870-fd4df5c9-f848-41c5-bb03-4c8fbf8eef81.mov

📌 ACTIONS
- Assigned to Vertex
- Escalated here: p1680121206966859-slack-C02T4NVL4JJ

**Comment by renancarvalho** [comment] 2023-03-30 09:04
Hi @cuemarie, thank you for creating this issue. 
I have downloaded the [wp.com desktop app ](https://apps.wordpress.com/desktop/) and checked this issue.

I noticed two interesting things:

1 - It is quite slow for me when loading an article,  this request `https://widgets.wp.com/community-translator/community-translator.min.js?ver=6.2-RC2-55570` is taking a huge time and blocking the page to be displayed and It also fails. But on the video you sent, it seems fine to you, which is weird.

2 - The 1st time I loaded an article, I saw it like you reported on the video, but when I open the developer tools by clicking on `view > developer > developer tools` for investigation, I saw it like it should be displayed, I believe the app is facing some kind of cache issue since the dev tool disables cache. After doing what I mentioned above just once, I cannot reproduce the issue again, which makes me believe that it is a cache issue.

I am not 100% sure but I believe the app uses a web view and just loads the web content like the browser, so cache could be indeed the issue.

I don't believe that it is something on the code itself. Do you know if someone else faced this issue ?

**Comment by cuemarie** [comment] 2023-03-30 14:29
Hey @renancarvalho !

> Do you know if someone else faced this issue ?

Yes, this was originally reported by a customer over email, then replicated by @ccwalburn and then myself.

Followed up in the slack thread with further details: p1680121206966859-slack-C02T4NVL4JJ

**Comment by cuemarie** [comment] 2023-04-03 22:02
This issue was fixed!  See p1680121206966859-slack-C02T4NVL4JJ for further details.

**Closed as completed by cuemarie** 2023-04-03 22:02 UTC
Labels: Bug, Documentation, [Pri] High, [Feature] WordPress Desktop App, Triaged, [Status] Priority Review Triggered
