### ISSUE TITLE
Domains: Creating new *.wordpress.com site that matches username not possible

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#2410] opened 2016-01-14 06:21 UTC
When a user (ex. freshwaterheart) decides to create a new wordpress.com site under an address that matches his username (which they didn't use upon signup), the domain search form does not offer it as an option:

![screenshot](https://cldup.com/JORYGFECkK.png)

Entering the full wordpress.com URL returns a "Sorry, but *.wordpress.com does not appear to be a valid domain name." error:

![](https://cldup.com/RA8_M5s-MV.png)

As a workaround, the user must be given a link to the old signup page (ex. https://signup.wordpress.com/signup/?ref=typo&new=freshwaterheart), which does allow the site to be created under the address matching their username:

![](https://cldup.com/-3H9UEwY0b.png)

**Comment by rachelmcr** [comment] 2016-02-15 18:53
This is a dupe of this issue: https://github.com/Automattic/wp-calypso/issues/288

**Closed by rachelmcr** 2016-02-15 18:53 UTC
Labels: Domains, [Type] Bug
