### ISSUE TITLE
Reader: Image block size is not respected in the Reader. Images show full sized.

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-calypso#69603] opened 2022-10-30 08:15 UTC
### Quick summary

Image blocks on a page/post when set different sizes, all show large (max) size on the Reader.

For example- 
https://wordpress.com/read/blogs/1922632/posts/2932

Another example-
Reader- https://wordpress.com/read/feeds/97334622/posts/4352694667
Live page- https://premiumtest1993.wordpress.com/2022/10/30/reader-testing-post/

### Steps to reproduce

1. Create a post/page with variable image sizes using image block.
2. Check the live page vs the reader.

### What you expected to happen

I expected the images to respect the size set in the image block.

### What actually happened

All images regardless of the resizing or the width setting or the image size setting showed up the same size.
Reader- ![Markup on 2022-10-30 at 13:38:57](https://user-images.githubusercontent.com/40609190/198868829-1f27e627-5970-4ebe-b4e8-8ae941ff70f4.png)
Live Site- ![Markup on 2022-10-30 at 13:39:31](https://user-images.githubusercontent.com/40609190/198868841-e57dec56-00d7-44b2-ba36-99f00c28d953.png)

### Context

User reported this issue here-
zd-5666504 

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

I think the issue is theme independent.

### Browser, operating system and other notes

Not browser dependent.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

### Workaround details

I tried using Columns block with the first and the third column empty, having spaces in paragraph,s and also having spacer blocks, but none of them worked.

**Comment by jordesign** [comment] 2022-11-08 21:19
Interestingly - I'm finding I *can't* recreate this one in my testing.
https://wordpress.com/read/feeds/134829492/posts/4371510710

It seems that it is likely theme specific - as I noticed the theme in your test @ahmadbaig1  doesn't have the image size option (so all images receive the 'large' size in the source code).

@ahmadbaig1 - do you see the image size option for the images in your test?

**Comment by ahmadbaig1** [comment] 2022-11-22 06:32
@jordesign Sorry for the late response.
Thank you for testing. 
That's strange, I am using the Plane theme as well, and the image does have the size options but they are not being respected.

**Comment by vajrasar** [comment] 2022-11-22 18:05
@ahmadbaig1 for clarity do you acknowledge that this is a theme-specific issue?

**Comment by ahmadbaig1** [comment] 2022-11-23 11:36
@vajrasar I tested changing themes from Plane to- Black Canvas, Masu, Bradford, Twenty twenty One, Barsnbury just now. 

The image size still showed constant for the Reader. So, to me, it looks like this is theme-independent. 

To test further, I created another post (copy) using Barnsbury theme, but the issue remains. 
Post- https://premiumtest1993.wordpress.com/2022/11/23/reader-testing-post-2/
Reader- https://wordpress.com/read/feeds/97334622/posts/4398926019

Further, I tested this using another site, that is Personal plan based site (theme- Apostrophe 2), but the results are the same-
Post- https://personaltest1993.wordpress.com/2022/11/23/reader-test-3-new-site/
Reader- https://wordpress.com/read/feeds/120200552/posts/4398930137

The results suggest, that this is theme-independent. I'm not sure why this is not being replicated on @jordesign's site.
@vajrasar Can you try doing a test once on your end? 

If it works for you as well, I'd think something is wrong at my end.

**Comment by NoHopeRadio** [comment] 2022-11-23 19:47
Looking at ahmad's example page above, the code I see that's causing the issue is from CSS in this file?

https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/reader-full-post/_content.scss

The SCSS that unfurls like this, lines 59-87 thereabout:

```
.is-reader-page .reader-full-post__story-content .image-wrapper.three-two img, .is-reader-page .reader-full-post__story-content .image-wrapper.two-three img, .is-reader-page .reader-full-post__story-content .image-wrapper.wide img, .is-reader-page .reader-full-post__story-content .wp-block-gallery .wp-block-image img {
    width: 100%;
}
```

What's perplexing me now is why I don't see this code rendering in Jordan's post. But looking closer, it looks like this rule triggers only in four cases:
An image in a gallery, and preset alignments 2:3, 3:2, and wide. It looks like all of Jordan's images are in the 16:9 alignments, which don't resize. I don't understand why these certain settings are set to render this way, but it's possible that changing a setting away from this option (however it's set) should solve the issue here.

Now the question is finding out how this option is set, since it seems to be independent of any direct image options.

**Comment by jordesign** [comment] 2022-11-23 20:23
Woah - thanks @NoHopeRadio  - that's super helpful.

For the purposes of triaging and assignment - I'm happy that the discrepency there is something worth reporting, and we can ask @Automattic/loop to look into it further.

**Comment by NoHopeRadio** [comment] 2022-11-23 22:41
One more follow-up from me, it looks like this is the js that assigns these image aspect ratio classes to images based on their attributes: 

https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/post-normalizer/rule-add-image-wrapper-element.js

**Comment by davemart-in** [comment] 2022-11-29 15:21
Thanks for the report @ahmadbaig1 and thanks for the breakdown @NoHopeRadio! I've assigned this issue to myself and added it to my list. I'll share an update once I've had time to dig in.

**Comment by pauljacobson** [comment] 2022-12-01 15:29
Just adding ticket references so our bot can pick up on them for follow-ups:

- 5666504-zen

**Closed as completed** 2022-12-15 14:59 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Simple, [Platform] Atomic
