### ISSUE TITLE
Site Settings: Type to select in Timezone Picker

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#5243] opened 2016-05-05 16:16 UTC
#### Steps to reproduce
1. Go to https://wordpress.com/settings/ and select a site
2. Try finding a specific timezone (can't type to select)

#### What I expected
- I'd like to be able to type the first few letters of a timezone name, if possible, or at least the first few letters of a region or city.

#### What happened instead
- We have to scroll through a long list of regions 

#### Browser / OS version
Doesn't matter

#### Screenshot / Video
https://cloudup.com/cOE6ygrmPlM

**Comment by lancewillett** [comment] 2016-05-09 23:11
Closed as a duplicate of #5231.

**Closed by lancewillett** 2016-05-09 23:11 UTC
Labels: Site Settings, [Type] Enhancement
