### ISSUE TITLE
Settings: Fix unexpectedly displayed "Changes you made may not be saved." dialog

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#73147] opened 2023-02-09 09:56 UTC
We addressed the https://github.com/Automattic/wp-calypso/issues/71071 issue present on the new Reading settings page. Similar issue might be present on other settings pages in Calypso.

The goals of this task is to review other settings pages and fix the same issue there - if it exists.

**Comment by mashikag** [comment] 2023-02-09 11:50
> The goals of this task is to review other settings pages and fix the same issue there - if it exists.

I am changing the Apex Project Board's `Project` assignment from `Reading settings` to `Maintenance`.

**Comment by andregardi** [comment] 2024-01-26 16:49
I tried to replicate the "Changes you made may not be saved." problem on al other settings page, on every field that does not use auto save, and could not reproduce the issue. I am closing the ticket.

**Closed as completed by andregardi** 2024-01-26 16:49 UTC
Labels: Task, Maintenance
