### ISSUE TITLE
Slow Performance When Editor Contains Gallery Blocks

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#60435] opened 2022-01-25 08:37 UTC
### Quick summary

When editing posts with gallery block, typing appears to be slowing down, or stuttering when typing them.

While editing posts without gallery block, typing appears to be handling normally without the slowness.

### Steps to reproduce

1. Create a new post, add some contents like paragraph blocks as you would.
2. Add gallery block with multiple images.
3. Add more contents after adding the gallery block with images.

### What you expected to happen

There should be any obvious lag or stutter when adding more contents into editor.

### What actually happened

Existing video from previous HE and user:
https://d.pr/v/sChZVC
https://www.youtube.com/watch?v=sCiOKvse9Lg&ab_channel=FatManLittleTrail

Most recent video when editing older, published post  https://fatmanlittletrail.com/wp-admin/post.php?post=40900&action=edit : https://d.pr/v/h2XvE0

### Context

Attempts were made to deactivate other plugins except JP, leaving only Jetpack and Twenty Twenty One theme, and is reproducible.

In the past, user did not experienced this, so it may be relating to recent updates on JP or WordPress introducing this issue..

I see there may be something to do with how the jquery query https://fatmanlittletrail.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0 loads, as from browser Network log shows images are being loaded repeatedly.

I'm not able to reproduce similar issues on my test site, however it is somewhat consistent under user's AT site.

Reported in 4711628-zd-woothemes

### Simple, Atomic or both?

Atomic

### Reproducibility

Intermittent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

- Remove the existing gallery block temporarily, add contents, then add gallery block back.
- Add all contents there is, before adding gallery block at the end of post.

**Comment by IoanaAMuresan** [comment] 2022-02-01 07:09
Just played into this ticket -> dropping in to say we're well past SLA (-20h) even with a recent message send by Richard yesterday. I'm setting this on hold for 3h for now.

**Comment by glendaviesnz** [comment] 2022-02-03 00:05
I was able to replicate this on a local dev install but only when the CoBlocks plugin was activated. The page performance seems fine with a Gallery block, but as soon as you activate CoBlocks there are long delays in typing and CPU usage of the tab goes 100%+

**Comment by glendaviesnz** [comment] 2022-02-03 02:10
I have logged an [issue with CoBlocks](https://github.com/godaddy-wordpress/coblocks/issues/2264) about this.

**Comment by formosattic** [comment] 2022-02-15 09:28
I can confirm that the issue still happens on an atomic site.

**Comment by mpkelly** [comment] 2024-04-19 06:30
I just now tested this on Simple and Atomic, the latter with and without CoBlocks blocks on the page. I am not seeing any issues. 

@edwinho89 do you think we can close this issue down?

Edit. Edwin is no longer with Automattic. I am going to close this down given such a big gap since the last case and that I cannot reproduce it.

**Closed as completed** 2024-04-22 06:51 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] High, [Feature] CoBlocks, Customer report [LEGACY], [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience
