### ISSUE TITLE
Subscription Management: fails to load when encountering invalid URL in subscriptions

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#76956] opened 2023-05-15 23:34 UTC
### Quick summary

When I try to load my subscriptions in Subscription Management, this is what I see:

<img width="1234" alt="Screenshot 2023-05-16 at 11 27 32 AM" src="https://github.com/Automattic/wp-calypso/assets/17325/b6e9eee2-8e78-4100-82a8-01e97427801a">

It appears that we're trying to create a new URL object with an invalid URL string (one of my subscriptions seems to just have the URL "http:"). We should handle the situation where the URL from subscription_matrix is invalid.

cc @Automattic/apex 

### Steps to reproduce

1. Load https://wordpress.com/subscriptions/sites/en using my subscriptions.

I'm happy to provide a subscriptions export or my user ID to the developer investigating this.

### What you expected to happen

Subscriptions Management loaded successfully.

### What actually happened

Subscriptions Management failed to load with an error in the console.

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by karenroldan** [comment] 2023-05-16 12:51
📌 REPRODUCTION RESULTS

I don't have subscriptions to `http` only -- all are `https` so I cannot reproduce the issue.

📌 ACTIONS

- Assigned to @Automattic/apex 
- Lowered the priority to `Low` since it only affects one for now 

📌 Message to Author

> I'm happy to provide a subscriptions export or my user ID to the developer investigating this. 

Thanks for this! That will help with the investigation.

**Comment by mashikag** [comment] 2023-05-16 16:00
The fix for this issue was shipped today: https://github.com/Automattic/wp-calypso/pull/76944
cc @yansern

**Closed as completed by mashikag** 2023-05-16 16:00 UTC
Labels: Bug, [Pri] Low, Triaged

**Comment by bluefuton** [comment] 2023-05-16 21:29
> The fix for this issue was shipped today: https://github.com/Automattic/wp-calypso/pull/76944

Thanks for the speedy fix! Loading as expected for me now 👍
