### ISSUE TITLE
Sharing: Firefox might display overlapping text when connecting to sharing services

### ISSUE THREAD

**Issue by nebososo** [Automattic/wp-calypso#24045] opened 2018-04-10 17:26 UTC
#### Steps to reproduce
Use Firefox with tracking protection enabled. It is debatable whether this should be considered a bug or not, but this option is enabled by default on all private tabs and is recommended-ish by mozilla: https://blog.mozilla.org/firefox/tracking-protection-always-on/
https://developer.mozilla.org/en-US/Firefox/Privacy/Tracking_Protection

1. Starting at URL: https://wordpress.com/sharing/$YOUR_BLOG
2. Click connect on either LinkedIn or Twitter (might also happen with others)
3. Authorize the app, the popup should close
4. Look at the broken connection dialog

#### What I expected
The dialog to look ok, even if without images

#### What happened instead
The image's alt text is shown on top of the regular text, as Firefox blocks the image because of tracking protection.
"The resource at $url was blocked because tracking protection is enabled"
You are also presented with a scrollbar

#### Browser / OS version
Linux 64
Firefox 58.0.2 64bits

#### Screenshot / Video
Chrome:
![2018-04-10-140344_540x369_scrot](https://user-images.githubusercontent.com/959292/38572817-91614626-3cca-11e8-9d26-4a38a8bec804.png)

Firefox with tracking protection:
![2018-04-10-140409_544x375_scrot](https://user-images.githubusercontent.com/959292/38572818-918c071c-3cca-11e8-94ab-c494d55c0e36.png)

**Comment by designsimply** [comment] 2018-04-23 22:19
I tested with Firefox 59.0.2 on macOS 10.13.4 and couldn't reproduce the bug as described (duplicate/overlapping text) but I did notice that the radio button has a funny gap to the left if there's only one site showing:

![screen shot 2018-04-23 at mon apr 23 4 15 14 pm](https://user-images.githubusercontent.com/1119271/39156028-bce1c306-4711-11e8-9ae7-19b103792b8c.png)
<sup>Seen at https://wordpress.com/sharing/design5279.wordpress.com using Firefox 59.0.2 on macOS 10.13.4.</sup>

Although I do think you could make an argument that a gap where a radio button might otherwise appear is minor enough to skip in favor of working on other, higher priority bugs.

Screenshot of Firefox tracking protection settings for reference:

<sup>Seen at about:preferences#privacy using Firefox 59.0.2 on macOS 10.13.4.</sup>
![screen shot 2018-04-23 at mon apr 23 4 06 33 pm](https://user-images.githubusercontent.com/1119271/39155718-7db5000e-4710-11e8-88f4-8a3b168536fe.png)

@nebososo thank you for reporting this! I'd like to close the issue since I wasn't able to reproduce it as described. If you're still having trouble with it though, please re-open and let me know!

**Comment by designsimply** [comment] 2018-06-13 16:05
Re-opening this because I saw the problem while testing a Twitter re-connection. I do have Preferences > Privacy & Security > Tracking Protection set to Always in Firefox settings and I tested with Firefox 60.0.2 on macOS 10.13.4. 

![connecting-twitter-overlapping-acount-names](https://user-images.githubusercontent.com/1119271/41363452-2ef05424-6ef1-11e8-815a-1b99b8306bed.png)
<sup>Seen at https://wordpress.com/sharing/design5279.wordpress.com (production) using Firefox 60.0.1 on macOS 10.13.4.</sup>

I am not sure why I can see the problem now but was unable to before.

**Closed** 2018-08-08 00:53 UTC
Labels: OSS Citizen, Sharing, [Pri] Low, [Type] Bug
