### ISSUE TITLE
Gutenberg: Editor crashes after copying a page [2]

### ISSUE THREAD

**Issue by aisajib** [Automattic/wp-calypso#33147] opened 2019-05-19 21:26 UTC
This problem occurs only on a single site. I was unable to replicate it on any other sites that I tested. Basically, on this site, if you copy a page and then open the page attributes module on the right, the Editor crashes instantly. 

#### Steps to reproduce
1. SSP into boxepipla (SU doesn't reproduce the issue)
2. Go to My Sites -> Site -> Pages
3. Use the three-dots next to any page and click Copy. Wait for the editor to load with the copied content.
4. Click the Page Attributes module on the right. If it is open by default, wait a few seconds. 

#### What I expected

The editor to keep its content there allowing me to modify changes as I wanted. 

#### What happened instead

The following error shows up, which the user says in English translates to "The editor experienced an unexpected error."

#### Browser / OS version

I tested this on Chrome/74.0.3729.157 with macOS Mojave. But the user said they checked multiple browsers/computers on different connections and they were seeing this error everywhere. 

#### Screenshot / Video

![wp](https://user-images.githubusercontent.com/2541844/57988320-a99c4600-7aae-11e9-8dcd-028370a02a8a.jpg)

#### Context / Source

Originally reported on 12843484-hc, follow-up on 2037234-zd.

**Comment by rachelwinspear** [comment] 2019-05-27 16:01
User has been back into chat asking for an update.
As this seemed like a site related issue, we decided to export content from boxepipla.com to a new test site boxcorfu.wordpress.com - Errors also present in the new site, which leads us to think this is a content-related issue.
As the site and interface were in Greek, I asked the user to change these to English and continued to test. Same errors.
User has uploaded a video of the problem here: https://drive.google.com/file/d/1cOZ3JUp9HQ0DS8fhQtM2hBxBGjbmbQcl/view
Ticket: #2064790-zen

**Comment by retnonindya** [comment] 2019-05-28 00:38
The error provided when I SSP-ed and got the issue:

`TypeError: Cannot read property 'raw' of undefined
    at https://s2.wp.com/_static/??-eJx9z00KAjEMBeAL2SllHJiNeJa2CZLaP5oUndur4FKzDO/j8WIf3VCNeQKyTWyBWCx4waVQXRKf7C9Qm1BE1s18qjkCSRsqCbnFu8kUhh+HKqEVM9DDX/U+sQQEtaXneaOqv/WZbXpj+aprubht2507r+ueXtATeYU=:40:64261
    at Array.map (<anonymous>)
    at https://s2.wp.com/_static/??-eJx9z00KAjEMBeAL2SllHJiNeJa2CZLaP5oUndur4FKzDO/j8WIf3VCNeQKyTWyBWCx4waVQXRKf7C9Qm1BE1s18qjkCSRsqCbnFu8kUhh+HKqEVM9DDX/U+sQQEtaXneaOqv/WZbXpj+aprubht2507r+ueXtATeYU=:40:64201
    at Td (https://s1.wp.com/_static/??-eJyNzEsOwjAMRdEN4ZoCVUeItbiJEQ75KXaKxOrpgCGqGL/zLr4qSHaxe1YMil7UcIllGZLkIegBfwHqVuqu2BLuCcpNKMqbTEoGz3fq0aBS24bd+8rZl4aNydnfEHxJu5jVUWV4WIpfd0vXcZrm02Wcz8fwAaHbYhM=:119:11)
    at be (https://s1.wp.com/_static/??-eJyNzEsOwjAMRdEN4ZoCVUeItbiJEQ75KXaKxOrpgCGqGL/zLr4qSHaxe1YMil7UcIllGZLkIegBfwHqVuqu2BLuCcpNKMqbTEoGz3fq0aBS24bd+8rZl4aNydnfEHxJu5jVUWV4WIpfd0vXcZrm02Wcz8fwAaHbYhM=:128:479)
    at hi (https://s1.wp.com/_static/??-eJyNzEsOwjAMRdEN4ZoCVUeItbiJEQ75KXaKxOrpgCGqGL/zLr4qSHaxe1YMil7UcIllGZLkIegBfwHqVuqu2BLuCcpNKMqbTEoGz3fq0aBS24bd+8rZl4aNydnfEHxJu5jVUWV4WIpfd0vXcZrm02Wcz8fwAaHbYhM=:141:202)
    at Qg (https://s1.wp.com/_static/??-eJyNzEsOwjAMRdEN4ZoCVUeItbiJEQ75KXaKxOrpgCGqGL/zLr4qSHaxe1YMil7UcIllGZLkIegBfwHqVuqu2BLuCcpNKMqbTEoGz3fq0aBS24bd+8rZl4aNydnfEHxJu5jVUWV4WIpfd0vXcZrm02Wcz8fwAaHbYhM=:181:217)
    at Rg (https://s1.wp.com/_static/??-eJyNzEsOwjAMRdEN4ZoCVUeItbiJEQ75KXaKxOrpgCGqGL/zLr4qSHaxe1YMil7UcIllGZLkIegBfwHqVuqu2BLuCcpNKMqbTEoGz3fq0aBS24bd+8rZl4aNydnfEHxJu5jVUWV4WIpfd0vXcZrm02Wcz8fwAaHbYhM=:182:76)
    at Sc (https://s1.wp.com/_static/??-eJyNzEsOwjAMRdEN4ZoCVUeItbiJEQ75KXaKxOrpgCGqGL/zLr4qSHaxe1YMil7UcIllGZLkIegBfwHqVuqu2BLuCcpNKMqbTEoGz3fq0aBS24bd+8rZl4aNydnfEHxJu5jVUWV4WIpfd0vXcZrm02Wcz8fwAaHbYhM=:195:109)
    at Z (https://s1.wp.com/_static/??-eJyNzEsOwjAMRdEN4ZoCVUeItbiJEQ75KXaKxOrpgCGqGL/zLr4qSHaxe1YMil7UcIllGZLkIegBfwHqVuqu2BLuCcpNKMqbTEoGz3fq0aBS24bd+8rZl4aNydnfEHxJu5jVUWV4WIpfd0vXcZrm02Wcz8fwAaHbYhM=:193:492)`

**Comment by maciejpilarski** [comment] 2019-06-03 07:49
The user came back to chat again asking about updates, they are losing their patience and considering canceling their subscription.
Are there any updates about the issue?

**Comment by glendaviesnz** [comment] 2019-06-12 03:52
We think we have narrowed replication of this issue down to site site that have 100+ pages, and in these instances can be replicated without needing to copy a page.

**Steps to replicate:**

1. Log into a site with more than 100 pages and with block editor enabled
2. Choose a page to edit
3. Once page is loaded in the block editor expand Page Attributes in the right hand document attributes bar
4. Wait for several seconds and the editor will crash

**Cause of the issue:**

Where a site has more than 100 pages, the call to the /pages api endpoint is `paged` A `next` header link is generated to provide the link to get the next set of pages, and the client automatically loops and retrieves all of the `pages` in a result set. The api was not including the api path in this header link and so the client failed when trying to retrieve the subsequent `pages`.

We have D29347-code in progress to hopefully resolve this issue.

**Comment by mmtr** [comment] 2019-06-14 03:48
Closing this issue since D29347-code has been deployed and we cannot reproduce it anymore.

**Closed by mmtr** 2019-06-14 03:48 UTC
Labels: Editor, [Goal] Gutenberg, user-waiting

**Comment by aisajib** [comment] 2019-06-14 16:34
Contacted the user here on this follow-up: 2109569-zen
