### ISSUE TITLE
Post/Pages search on Atomic not providing correct results

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#52694] opened 2021-05-09 06:21 UTC
### Steps to reproduce the behavior

1. Go to an AT site and search either the posts or pages for a known title
2. See how you get a mix of results
3. Compare to same search on Simple site

#### What I expected to happen
The search functionality should behave the same on both AT and simple sites

#### What actually happened
the post search on AT sites doesn't seem to be looking for titles and doesn't exclude partial matches; it also brings up posts with no matching text
The page search doesn't seem to be searching page titles, only page content

### Context
user report 39701350-zen

#### Is this specific to the applied theme? Which one?
not theme specific

#### Does this happen on simple or atomic sites or both?
AT

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
On a site with many posts/pages this could make it almost impossible to find the one you want

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Post search:
![search](https://user-images.githubusercontent.com/47717887/117562404-6eceb680-b0a7-11eb-9dca-e78ac716814b.gif)

Page search: 
![search 2](https://user-images.githubusercontent.com/47717887/117562471-d5ec6b00-b0a7-11eb-92e1-960978bb970d.gif)

**Comment by ericamQA** [comment] 2021-05-15 18:25
Unable to reproduce on multiple AT sites. Closing.

**Closed as completed by ericamQA** 2021-05-15 18:25 UTC
Labels: Bug
