### ISSUE TITLE
Themes: Keep getting the thanks modal after purchasing a premium theme.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#8263] opened 2016-09-27 23:44 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/design/<site>
2. Purchase a premium theme.
3. Get the thanks modal, click Back to Themes.
4. navigate to Blog Posts or anything else in the sidebar
5. Get sent back to `/design` and the thanks modal again
6. Click Visit Site, and then the Back button
7. Can now navigate normally.
#### What I expected

We should not be shown the thanks modal more than once.
#### What happened instead

We see it every time we go anywhere in the sidebar.
#### Browser / OS version

Chrome 53 on macOS Sierra
#### Screenshot / Video

![merci](https://cloud.githubusercontent.com/assets/349751/18895827/81af0f9a-84d1-11e6-81a4-fbcf560cc1d6.gif)

**Comment by kwight** [comment] 2016-09-27 23:44
Related to #8262 .

**Comment by ockham** [comment] 2016-09-28 22:29
I can reproduce. This one's new to me. Annoying :-/

**Comment by rachelmcr** [comment] 2017-08-07 15:08
I tested with the steps above and could not reproduce. After dismissing the thanks modal I navigated to Blog Posts and the modal never appeared again.

Closing, but please reopen if you can still reproduce this issue.

**Closed by rachelmcr** 2017-08-07 15:08 UTC
Labels: Themes, [Type] Bug
