### ISSUE TITLE
Plan upgrades not available for atomic sites where the Business plan expired

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#25470] opened 2018-06-13 09:07 UTC
**Context:**

This was originally opened and discussed within the atomic repository here:

- 242-gh-atomic
- 478-gh-atomic
- 213-gh-atomic

After some discussion we decided to re-open it as a Calypso issue, as doesn't affect the atomic setup or infrastructure at all, but is a gap in the interface.

**Issue**:

At the moment, if an atomic site has its Business subscription expired, a new subscription cannot be purchased from the Calypso interface at http://wordpress.com/plans or at http://wordpress.com/pricing, leaving the customer with an Atomic site on a free plan and inability to install more plugins or themes, or get any benefits from the Business plan, for example access to live chat support, as their plan is effectively Free. 

They should be able to renew their plan from their Calypso interface, however there is one caveat: Customers would only be able to renew the plan as a Business (not Personal, or Premium) as explained in detail by @rralian here: 242-atomic/-#issuecomment-305918157 

However, this will not be an actual problem as at the moment customers need to contact support anyway to perform a downgrade from Business-Atomic to any other setup. Which means that enabling the possibility to renew to Business-only would reduce the friction they're suffering now, and they could contact support directly if they prefer to cancel/downgrade/etc, ... instead of being left in a grey zone where they can keep installing plugins/themes on their site but they don't have a Business plan anymore, no access to support, etc, ...

I took the freedom of marking this as High priority, as we are seeing more and more cases as the yearly renewals started to hit a few months ago, and this will only increase every day.

**Comment by GeoJunkie** [comment] 2018-08-02 20:42
Encountered this in 402877-hc . User's plan had expired and was removed. They couldn't get their Business plan back since it couldn't be added from Calypso.

I had to add the Business plan manually with a same-day expiration, then they could go in and renew it, but it required HE intervention to get the user where they could get their site back on the plan.

**Comment by rachelmcr** [comment] 2018-08-30 13:51
I ran into this myself after letting the Business plan expire on an Atomic site I used for testing. (I also let the domain expire and I'm now totally incapable of doing anything with my site, including exporting the content to move elsewhere. It feels like a trap.)

This issue looks like a duplicate of https://github.com/Automattic/wp-calypso/issues/13865 — I'm closing that issue since this one is already assigned/in a project and includes addition links to further discussion.

**Comment by iamgabrielma** [comment] 2018-10-24 13:46
Also for internal reference: 478-gh-atomic

**Closed** 2018-12-12 09:48 UTC
Labels: Atomic, Billing, FixTheFlows, Plans, Purchases, [Pri] High, [Type] Bug

**Comment by simison** [comment] 2019-01-17 10:22
Could there have been a recent regression that affects this feature? @yoavf 

Seems like we had two customers with this scenario, one in 1721138-zen and another p1547720001224400-slack-jpop-support

**Comment by yoavf** [comment] 2019-01-17 13:42
I can confirm the regression - seems like there's an error being returned from the backend. Checking...

**Comment by yoavf** [comment] 2019-01-17 14:01
Not actually a regression, but I only fixed the front end in #25470
code-D23269 should take care of it
