### ISSUE TITLE
Site Transfer to new owner failed to move subscriptions or domain on Atomic 

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#87609] opened 2024-02-19 18:13 UTC
### Quick summary

In 7763004-zen, a customer had just transferred their site to a new owner, but no subscriptions or domains transferred, only the site ownership itself. 

I walked the user through transferring the domain, and transferred the plan manually via SA.

Atomic site; blog_id=`228098855`

### Steps to reproduce

1. Create an AT site with a Creator plan and domain
2. Invite an Admin level user
3. Site Settings > Transfer Site

### What you expected to happen

All subscriptions and domain should transfer

### What actually happened

In this case, only the site ownership itself transferred

### Impact

One

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Gut Check with Reactor: p1708364127203319-slack-C03TY6J1A

**Comment by cuemarie** [comment] 2024-02-19 18:59
Just tried replicating this on a test site and was unable to – all subscriptions transferred as expected. (`blog_id=194192341`)

We might want to check the user's support history – they did try reporting that the transfer wasn't working/was delayed – maybe they didn't verify this transfer or something happened that caused the transfer to only happen partially?

**Comment by maciejpilarski** [comment] 2024-02-20 17:22
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to reproduce the issue on my test sites.

📌 ACTIONS
– Triaged

**Comment by cpapazoglou** [comment] 2024-02-23 12:37
@JulianBustamante can you dig into this specific event?

**Comment by JulianBustamante** [comment] 2024-02-23 16:40
@cpapazoglou, I'm looking into this.

Update:

- No errors were found for the mentioned site in the logs.
- I tested the transfer with a subscription and it worked as expected.
- I'm still investigating a bit more.

**Comment by JulianBustamante** [comment] 2024-03-13 01:23
@cpapazoglou I could not replicate this issue. We can close this issue.

**Comment by gavande1** [comment] 2024-03-13 09:36
Let's close this issue. Feel free to reopen the issue if needed.

**Closed as completed by gavande1** 2024-03-13 09:37 UTC
Labels: Bug, [Feature] Site Settings, [Pri] Low, Triaged, Customer report [LEGACY], [Platform] Atomic, [Product] WordPress.com, [Feature Group] Site Settings & Tools, Site Transfers
