### ISSUE TITLE
Checkout: user is able to purchase Atomic/Simple-incompatible Jetpack products

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#42345] opened 2020-05-18 19:31 UTC
#### Steps to reproduce

1. Starting at URL: https://vaultpress.com/plans/
2. Add a product to your Atomic or WordPress.com simple site via the buttons on this page or URL (i.e. `https://wordpress.com/checkout/jetpack_backup_realtime_monthly/{site_url}`)
3. ~~Checkout will load, but the product won't be added (backups are included with Atomic and simple sites). If there are other products already in that site's cart, you'll see only those products. If there are no other items in that site's cart, you'll just be redirected to `/plans/`. Both result in no visible failure message to the user.~~ [Checkout will load and the user will be able to purchase the incompatible product.](https://github.com/Automattic/wp-calypso/issues/42345#issuecomment-775566201)

#### What I expected

Some sort of messaging explaining what happened: "Backups are already part of your plan. To learn more, click here."

#### How to fix

[We need to implement gating on the `/shopping-cart/` endpoint](https://github.com/Automattic/wp-calypso/issues/42345#issuecomment-778460727) for Atomic- and Simple-incompatible Jetpack products. Similar gating exists for multisite-incompatible products.

**Comment by sirbrillig** [comment] 2020-05-18 20:13
This is caused by this code: 

https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/checkout/index.jsx#L306

It says that when trying to add a jetpack product, only add it if the site is jetpack and not atomic, but there's no behavior if that is false. So the attempt to add the product never even reaches the cart store or the server, and you're left on the checkout page with whatever might be in your cart currently.

**Comment by xpurichan** [comment] 2021-02-09 00:40
It seems the behavior of this bug has changed, but not for the better. Instead of the upgrade missing from the cart it is now added to the cart and the customer can complete checkout. In my test I went to:

https://wordpress.com/checkout/jetpack_backup_realtime_monthly/{site_url}

Replacing `{site_url}` with the domain of my Atomic site. This caused the "Jetpack Backup (Real-time)" product to be added to the cart of my website, eligible for checkout. 

Screenshot:

![Screen Shot 2021-02-08 at 7 33 13 PM](https://user-images.githubusercontent.com/33190975/107299173-5b766580-6a3c-11eb-9303-1c25106e29c9.jpg)

I wonder if this is related to another bug where some Atomic customers will see a prompt to purchase an upgrade to Jetpack Scan in WP Admin: `https://{site_url}/wp-admin/admin.php?page=jetpack#/dashboard`. Not only are the prompted to upgrade (despite being Atomic and already having this upgrade included in their Business plan), but they are allowed to checkout and purchase the upgrade too. You can find that report on:

p9F6qB-6cE-p2

**Comment by michaeldcain** [comment] 2021-02-09 18:38
From our planning call: we need to decide what (if any) Jetpack products can be purchased on an Atomic site and then block the ones that shouldn't be via the `/shopping-cart/` endpoint.

**Comment by sirbrillig** [comment] 2021-02-12 21:18
Just to summarize some of this a little bit more since this issue has been around for a while and checkout has changed quite a bit since it started:

The original bug happened basically because the code in checkout that added products would refuse to add a Jetpack product to an Atomic site. Since that time, that code has been totally replaced and [the new code which adds products](https://github.com/Automattic/wp-calypso/blob/dad21af1e56008926b2d4b5e83ce8ea44289979f/client/my-sites/checkout/composite-checkout/hooks/use-prepare-products-for-cart.ts#L269-L307) has no such guards; it will happily try to add any product to the cart.

The new bug (I believe) is that there are certain conditions (eg: an Atomic site) in which we should not allow Jetpack products to be added to the cart. This sort of logic exists for many other conditions and products and lives in the shopping-cart endpoint itself; it even has the ability to display warnings or notices to the client. We probably just need to add new logic there for these particular conditions.

**Comment by michaeldcain** [comment] 2021-02-15 16:00
Asked for a list of Atomic-incompatible Jetpack products here: p1613403834478800-slack-CQXNTE9K9

**Comment by michaeldcain** [comment] 2021-02-15 16:09
I updated the issue title and description to reflect the current state.

**Comment by michaeldcain** [comment] 2021-02-15 20:14
Here's a list of Atomic-/Simple-incompatible products:

```
// Legacy plans
jetpack-premium
jetpack-business
jetpack-personal
// Plans
jetpack-security-daily
jetpack-security-realtime
jetpack-complete
// Products
jetpack-backup-daily
jetpack-backup-realtime
jetpack-scan
jetpack-scan-realtime
jetpack-anti-spam
jetpack-search
```

**Comment by sirbrillig** [comment] 2021-02-15 20:48
Should be fixed by D57102-code

**Comment by sirbrillig** [comment] 2021-02-19 00:32
Deploying the above fix might be a complicated decision, so I made an internal p2 post and we'll see where it goes from there pbOQVh-Ty-p2

**Closed** 2021-02-26 17:10 UTC
Labels: Checkout, Jetpack, [Pri] High, [Type] Bug
