### ISSUE TITLE
The Classic Block toolbar does not scroll down or appear near the content being edited

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#76652] opened 2023-05-07 16:08 UTC
### Quick summary

The toolbar of the Classic Block remains on top and does not scroll down or appear directly above the section being edited. 

### Steps to reproduce

1. Enable Gutenberg plugin. 
2. Open a page or post.
3. Insert a Classic Block and add contents in that block. 
4. Click a content to edit and the toolbar will appear on top. 
5. Scroll down at the bottom or the page or post and click a content. The toolbar will still remain on top.  

### What you expected to happen

The toolbar will be visible and close to the section of the page or post being edited. 

### What actually happened

The toolbar remains on top and does not scroll down or appear directly above the content being edited. 

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

- Firefox 112 
- Gutenberg version 15.7.0
- User report: 6268864-zd 

- I can replicate the issue only on my AT site: 

<img width="1081" alt="Screenshot 2023-05-07 at 17 45 42" src="https://user-images.githubusercontent.com/36863633/236688303-5fb76235-679f-4550-8dfc-0f23a95aec2e.png">

<img width="1085" alt="Screenshot 2023-05-07 at 17 47 02" src="https://user-images.githubusercontent.com/36863633/236688312-5f3caead-7087-4007-b290-578afe3f0f4d.png">

- Converting the classic block into blocks has no issue with the toolbar.

**Comment by cuemarie** [comment] 2023-05-09 19:04
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Self-hosted – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described, however this is working by design.

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/1b770c2b-5686-4881-b11f-f04571d8cd11

📌 ACTIONS
- Closed as by design

📌 Message to Author
> The toolbar remains on top and does not scroll down or appear directly above the content being edited.

Hey @kspilarski ! I believe this is working as intended. Since any content within the Classic block is explicitly _not made with blocks_, there's no differentiation between paragraphs or pieces of that content that the Block Editor can respond to.  The entire Classic Block's content is all one block, and that's why the Block toolbar (where we see "Convert to blocks") remains at the top of the editor view when scrolling down.

A similar test would be to see how a single, very-long Paragraph block behaves - the block toolbar floats at the top of the editor in this example as well:

![0uoziI.png](https://github.com/Automattic/wp-calypso/assets/27249804/7b147b7a-9398-40b6-807c-33f9f386d56e)

**Closed as completed by cuemarie** 2023-05-09 19:04 UTC
Labels: Bug, [Pri] Normal, Blocks, Triaged, [Platform] Atomic
