### ISSUE TITLE
Image and Paragraph Block: alignment 

### ISSUE THREAD

**Issue by catkiinson** [Automattic/wp-calypso#31943] opened 2019-04-02 00:42 UTC
#### Steps to reproduce
1. Create a new page, add an image block and insert image. 
2. Add a paragraph block below with text. 
3. Resize image and change to left alignment. Text wraps around image. 
4. Preview/publish 

#### What I expected

- Expected the image and text to be almost exactly aligned, as it appears in the editor. 

#### What happened instead

- When previewed/published, the first line of text has a gap above it. 

- Workaround: Adding an empty paragraph block above the image block removes the gap. 

#### Browser / OS version
Chrome Version 73.0.3683.86
macOS Mojave 10.14.3

#### Screenshot / Video
Page creation: 
![Screen Recording 2019-04-01 at 05 29 PM](https://user-images.githubusercontent.com/43645273/55367858-f6e33a80-54a3-11e9-97fe-437cd8595eab.gif)

Before adding empty paragraph block: 
![b33468de4d58b6b4cc095fed8224d5f2 _Image 2019-04-01 at 5 12 00 PM](https://user-images.githubusercontent.com/43645273/55367906-30b44100-54a4-11e9-8097-a33786806203.png)

Empty paragraph block applied in editor: 
![Screen Shot 2019-04-01 at 5 38 49 PM](https://user-images.githubusercontent.com/43645273/55368124-175fc480-54a5-11e9-81c1-f4adcdbbd0b1.png)

After adding empty paragraph block: 
![Screen Shot 2019-04-01 at 5 13 59 PM](https://user-images.githubusercontent.com/43645273/55367914-39a51280-54a4-11e9-8667-330aa452a740.png)

#user-report #manual-testing

**Comment by scruffian** [comment] 2019-04-02 10:28
I think this should be raised in the Gutenberg repo: https://github.com/wordpress/gutenberg/

**Comment by catkiinson** [comment] 2019-04-03 00:03
Thanks! Raised in the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/14782#issue-428498928

**Comment by arunsathiya** [comment] 2019-04-03 09:37
I am not able to reproduce this either on WordPress.org site https://github.com/WordPress/gutenberg/issues/14782#issuecomment-479415245 or on a WordPress.com site `gutenberg.wpcom.arunsathiya.blog`. 

<img width="974" alt="Screenshot 2019-04-03 at 15 02 58" src="https://user-images.githubusercontent.com/18581859/55468970-261fb600-5622-11e9-82b9-5b81c1cd34be.png">
<img width="855" alt="Screenshot 2019-04-03 at 15 03 08" src="https://user-images.githubusercontent.com/18581859/55468972-261fb600-5622-11e9-842f-410bdcff72e2.png">

Even if this is an actual issue, it feels to be a core-specific thing. I am closing this issue for now, in favor of the one you created on the core repository. If we find something specific to WordPress.com, we can always reopen this issue. 👍🏽

**Closed by arunsathiya** 2019-04-03 09:37 UTC
Labels: Gutenberg core, [Goal] Gutenberg, [Type] Bug
