### ISSUE TITLE
Notifications: Slideshow blocks display empty space.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#46964] opened 2020-10-30 17:25 UTC
The Jetpack Slideshow block will be rendered as empty space in a notification.

Front-End | Notification
--- | ---
<img width="700" alt="Screen Shot 2020-10-30 at 10 24 34 AM" src="https://user-images.githubusercontent.com/349751/97737366-23a16e80-1a9a-11eb-9c8b-77b78cb2bfae.png"> | <img width="500" alt="Screen Shot 2020-10-30 at 10 22 39 AM" src="https://user-images.githubusercontent.com/349751/97737379-27cd8c00-1a9a-11eb-9dc7-4c2ce3ddc061.png">

**Comment by kwight** [comment] 2020-10-30 18:57
@sixhours What do you think of just showing the first image and linking it to the slideshow? I know with email, we went the slideshow -> gallery route, but I wouldn't want a 30-slide slideshow to result in a giant, unreadable notification.

**Comment by sixhours** [comment] 2020-10-30 19:03
I think that makes sense, especially if we add a call to action ie "Click to view this slideshow". I could see the image with the link on top (kind of like a cover image) as a preview so it distinguishes it from a regular image.

**Comment by ivan-ottinger** [comment] 2021-07-28 16:27
I did a bit of testing today and it turns out the slideshow images are actually there. They are just obstructed by a `div` with `opacity: 0;`:

<img width="1312" alt="Markup 2021-07-28 at 17 35 04" src="https://user-images.githubusercontent.com/25105483/127360371-9137b8f5-ea57-4bc4-8b2f-b410072fe268.png">

**Comment by ivan-ottinger** [comment] 2021-08-04 11:44
We are working on a notification render fallback for Slideshow block in D65094-code that will help with the issue.

**Comment by ivan-ottinger** [comment] 2021-08-06 13:35
The issue is now fixed with D65094-code and deployed in production:

![Markup on 2021-08-06 at 15:31:52](https://user-images.githubusercontent.com/25105483/128518075-8a54ac26-4dc5-42df-97ba-7def76f5bbdc.png)

We chose a simpler notification display that shows the first slideshow image and then a link "View slideshow (x slide(s))".

This is the fallback UI we came up with. Feel free to iterate on how it looks like in future revisions. :)

**Closed by ivan-ottinger** 2021-08-06 13:35 UTC
Labels: [Type] Bug, [Pri] Normal, Notifications, [Size] XS
