### ISSUE TITLE
Paragraph block: When $ is used on FSE Simple Sites, text disappears when reopened in editor

### ISSUE THREAD

**Issue by benchilcote** [Automattic/wp-calypso#48378] opened 2020-12-15 20:45 UTC
#### Steps to reproduce

1. On an FSE simple site (using Maywood theme) create a new page
2. Add paragraph block 
3. Add a price (ex: $100) at the beginning of a line
4. Publish the page and exit the editor
5. Open the page again in the editor  

#### What I expected

$100 would still be present in the paragraph block

#### What happened instead

"$10" is removed and we are left with only "0".  It seems to remove the "$" and 2 characters after, if the characters are numbers

#### Browser / OS version

Firefox 83
Mac OS 10.12.6

#### Screenshot / Video

Text entered into the editor – paragraph block

![image](https://user-images.githubusercontent.com/18581859/169384813-f3b1113c-acbe-4b2d-a7fc-d709d61dc682.png)

Published page shows the text as expected:

![image](https://user-images.githubusercontent.com/18581859/169384835-c35030f3-e77e-42ba-9575-62553501ee7a.png)

Open the same page again in the editor and some text goes missing:

![image](https://user-images.githubusercontent.com/18581859/169384875-90f04e10-8af4-4020-8a31-e80844fc93fd.png)

Tried another set of text

![image](https://user-images.githubusercontent.com/18581859/169384921-f13ee592-9b89-4d9c-9ab6-308d66c937a4.png)

Published page on second test:

![image](https://user-images.githubusercontent.com/18581859/169384946-4028e8e7-d7c8-4ada-a306-ea44841c5fb0.png)

Re-open the page in the editor:

![image](https://user-images.githubusercontent.com/18581859/169384969-44655022-cae5-4872-809d-d205b5dab391.png)

Change themes, and the text returns when the page is opened in the editor:

![image](https://user-images.githubusercontent.com/18581859/169385014-51fc1eb7-833d-4e8f-9b5f-9019be550d7d.png)

#### Context / Source

#user-report  

User reported they have been dealing with this issue for many months on this page:
https://culturedboards.com/menu/

26337566-hc
Follow up 3574262-zd

**Comment by cathymcbride** [comment] 2020-12-16 20:17
@benchilcote can you repro with any other themes? Or just maywood?

**Comment by benchilcote** [comment] 2020-12-17 03:33
> can you repro with any other themes? Or just maywood?

Based on p7DVsv-7zo-p2#comment-24225, Maywood is the only theme on simple site that supports FSE.  So I was not able to test on another theme while on FSE.  Changing themes will disable FSE.

I tested this on a non-FSE simple site using Maywood and I could not reproduce the issue.

**Comment by cathymcbride** [comment] 2020-12-17 14:43
Thank you @benchilcote! I realized only one theme was supported right after I sent this. 🤦🏻‍♀️ I've added this to the Create Gardners board.

**Comment by arunsathiya** [comment] 2022-05-19 23:59
I am unable to reproduce this. This is when I re-open the published page's editor on Maywood:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/18581859/169384581-441e5779-1a81-42e3-a0d0-44f12baecd68.png">

Closing. We can reopen if this happens again.

**Closed as completed by arunsathiya** 2022-05-19 23:59 UTC
Labels: Bug, [Feature] Post/Page Editor, [Goal] Full Site Editing
