### ISSUE TITLE
Daily Prompt: Post editor crashes when Crowdsignal Polls & Ratings plugin enabled

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#82931] opened 2023-10-12 10:11 UTC
### Quick summary

One of our customers reported that the post editor crashed for them when they tried to respond to the Daily Prompt in the _My Home_ page in their WordPress.com dashboard.  

The customer said they can still create and open regular posts and pages. Something about the Daily Prompt seems to be the differentiator here.

### Steps to reproduce

1. Start at _My Home_ and click on the _Daily Prompt_ to open a new post with the prompt
2. The post editor will start loading, and after beginning to add the title, the editor crashes, displaying an error, like this:

https://github.com/Automattic/wp-calypso/assets/2912202/a4b80c16-aa02-4d87-b641-9bb4121a7bb0

3. It seems that this issue occurs consistently with the Crowdsignal Polls & Ratings plugin enabled, and inconsistently with Google's Web Stories plugin enabled.

### What you expected to happen

If I deactivate all user-installed plugins on the site, the post editor opens as expected so this doesn't appear to be an issue with the Daily Prompt issue, specifically, but rather an interaction with other factors including these plugins:

https://github.com/Automattic/wp-calypso/assets/2912202/7c9ceafb-7419-41b1-8dfb-43e15c4116f0

This is what I expect to happen.

### What actually happened

The post editor crashes as described above when these two plugins are active on the site. As I mentioned, the issue seems to consistently occur with the Crowdsignal Polls & Ratings plugin installed, although somewhat inconsistently with the Web Stories plugin activated.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Logs: 32149-pb/
Chat: 7149984-zen
Follow-up ticket: 7150739-zen

**Comment by cuemarie** [comment] 2023-10-12 17:41
Duplicate of https://github.com/Automattic/wp-calypso/issues/82874

**Closed as not planned by cuemarie** 2023-10-12 17:41 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] High, Needs triage, Crowdsignal, Customer report [LEGACY], [Platform] Atomic, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience
