### ISSUE TITLE
RSS Feed: Layout Grid Block appears to be excluding content from a site's feed

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#46085] opened 2020-10-01 10:24 UTC
A customer reported that when they added post content to a [Layout Grid Block](https://en.support.wordpress.com/wordpress-editor/blocks/layout-grid-block/), this content was excluded from the site's feed when the post was syndicated to Feedly, and shared in a WordPress.com email update using the built-in blog subscription service.

I have borrowed from the customer's private post detailing the issue here.

#### Steps to reproduce

Starting at URL: https://wpcommaven.com/2020/09/30/writing-in-the-wp-admin-classic-editor-a-quick-tour/

> On September 30th I published this post, which I edited about an hour after publication following discovery that the entire content of the Layout Grid, the post’s introduction and jump links, was ignored in my site feed. You can see this below in both the email notification of the post from September 30th and the Feedly version of the post from October 1st, almost 12 hours after the post was published.
> 
> I edited the post to remove both the Spacer block and the Layout Grid block and replaced them with a Paragraph block and List. 

#### What I expected

Feed items should include content added to the beginning of the post in the syndicated feed item.

#### What happened instead

>Once published, the content of the layout grid block was entirely ignored in my site feed.

The customer also noticed this:

>While editing, I noticed that the content of the Layout Grid block rode up over the bottom of the featured image and so I added a Spacer block at the start of the post.

![01_screenshot_2020-09-27-original-post_editing-annotated](https://user-images.githubusercontent.com/2912202/94797436-c8238880-03e8-11eb-99fc-4025f7fd23d8.png)

#### Browser / OS version

This information wasn't shared, although this doesn't appear to be relevant.

The site uses the Hever theme, and is a WordPress.com site on a WordPress.com Business plan, although without plugins.

#### Screenshot / Video

![01_screenshot_2020-09-30-original-post-annotated](https://user-images.githubusercontent.com/2912202/94797416-c0fc7a80-03e8-11eb-93ec-55aa91cc5d89.png)

![02_screenshot_2020-09-30-email](https://user-images.githubusercontent.com/2912202/94797474-d5d90e00-03e8-11eb-9116-498b75d5eec4.png)

Feedly screenshot:

![screenshot_20201001-feedly](https://user-images.githubusercontent.com/2912202/94797483-db365880-03e8-11eb-8ac2-d6d63ec77b2d.jpg)

#### Context / Source

Reported in 3364877-zen

**Comment by aleone89** [comment] 2021-11-02 08:35
Another report in the forums here: https://wordpress.com/forums/topic/layout-grid-block-issues/?view=all

**Comment by aleone89** [comment] 2021-11-02 08:55
Just to add to my findings, it looks like this is being caused by the following CSS: 

```
@media only screen and (min-width: 560px)
.singular .hentry .entry-content>*:first-child.alignfull {
    margin-top: -64px;
}
```
Which is being loaded in this file: /masterbar-overrides/masterbar.css 

I've done some investigation and it looks like this might be related: 

https://github.com/Automattic/wp-calypso/pull/55525#issuecomment-902477515 

Whereby the masterbar CSS is overriding some of the theme's CSS - but I'm not 100% on if this is also the real cause in this instance. 

I also found this pull request here, which details a similar issue: https://github.com/Automattic/jetpack/pull/18124 but again, I'm not sure if this also related?

**Comment by supernovia** [comment] 2021-11-03 17:35
Closing this one out: the feed issue seems to be resolved.

The layout issue is actually a problem with Hever, so I've filed a separate issue here:
https://github.com/Automattic/themes/issues/4978

If the feed problems return, let's open a separate issue for that, too.

**Closed by supernovia** 2021-11-03 17:35 UTC
Labels: [Type] Bug, Posts, Sharing, [Pri] Normal, Reader, User Waiting, Blocks, [Source] User testing, Block Rendering, User Report
