### ISSUE TITLE
HTML Entities in SiteStreams

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#14849] opened 2017-06-07 11:37 UTC
#### Steps to reproduce
1. Go to: https://wordpress.com/read/feeds/34858539
2. Posts [like this one](https://wordpress.com/read/feeds/34858539/posts/1486561202) aren't being decoded properly 

#### What I expected
Title of the post should be: `Macy's New CEO Vows to Keep Shoppers' Attention`

#### What happened instead
`Macy&#039;s New CEO Vows to Keep Shoppers&#039; Attention`

#### Context / Source
Thanks @designsimply for spotting this!

**Comment by blowery** [comment] 2017-06-07 12:26
This is because their feed is broken: https://www.businessoffashion.com/syndication/feed

You don't need to use numeric entities inside CDATA sections. 

We could look for entities and decode them... intentional entities in titles are likely pretty rare. Or at least look for some commons ones. (`&amp;`, `&#039;`, etc)

**Comment by bluefuton** [comment] 2018-03-05 18:01
Duplicate of #12774.

**Closed by bluefuton** 2018-03-05 18:01 UTC
Labels: Reader, [Type] Bug
