### ISSUE TITLE
Markdown Being Removed in Comments

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#31779] opened 2019-03-26 19:09 UTC
User noticed that HTML Markdown in Comments are being removed after being saved in Calypso. This setting works as expected in wp-admin. 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/comment/andrealazzarotto.com/65263 and click edit
2. Apply Unordered list and list item comments for the following two items: 
```
gli URL con msf.ticdn.it funzionano normalmente dalla mia connessione italiana, mentre effettivamente risultano irrisolvibili (proprio già dal DNS) quando mi collego dall’estero (ho provato Svezia e Francia)


gli URL con msf.cdn.mediaset.net funzionano sia dall’Italia che dall’estero
```
3. Save 

#### What I expected
This: https://cld.wthms.co/Jtwaz8

#### What happened instead
The markdown that was just added and save will be removed. This only occurs within Calypso. The markdown is saved it edited within the comments section of wp-admin.

#### Browser / OS version
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0

#### Screenshot / Video
https://www.youtube.com/watch?v=MeaDUhHBSSQ&feature=youtu.be

#### Context / Source
Chat: 70563-hc
Follow Up Ticket: 1910665-zen

**Comment by Lazza** [comment] 2019-12-21 19:49
> It has been inactive in the past 9 months

Is this a joke?

**Comment by Lazza** [comment] 2020-09-20 08:55
Again, is this a joke? We are paying for the product and the bug has not been addressed or even commented at all **for over one year?**

**Comment by Lazza** [comment] 2021-03-19 13:54
What the heck! Seriously?

**Comment by synora** [comment] 2021-03-23 14:47
@gwwar Can we get an update on this? 
See also: https://github.com/Automattic/wp-calypso/issues/21246

**Comment by gwwar** [comment] 2021-03-23 15:16
@obenland @simison would y'all like to help triage this one

**Comment by obenland** [comment] 2021-03-25 21:45
Pointing Comments back to wp-admin might be most expedient way to avoid running into this

**Comment by Lazza** [comment] 2021-03-25 21:47
I respectfully disagree: end users cannot use `wp-admin` to leave comments on WP blogs.

**Comment by obenland** [comment] 2021-03-26 15:47
This issue seems to be specific to editing existing comments from within Calypso. Is that not the case?

**Comment by Lazza** [comment] 2021-03-26 15:58
The issue is not specific to Markdown, the tags get stripped after they are converted to HTML.

They get stripped on the front end as well, see for instance #21246.

To be fair I don't know if the cause is the same, but the final result is the same. Stripped tags while they should be preserved.

**Comment by CoachBirgit** [comment] 2021-10-05 08:16
User turns received customer feedback manually as site admin into comments to a dedicated page. They would like to edit the comments in a later step and add images by adding them with the Markdown options as HTML tag`img` to the comment text.

They demonstrate the process with a video. They use the WP.com view (Calypso).
After saving the comment with valid HTML for the image, the HTML gets stripped of the content.

I could reproduce this on one of my test sites. Editing in WP-Admin works, but if I open and save without changes the same comment afterwards in Calypso, the HTML gets stripped out again.

Context: zen-4346993

/cc @obenland

**Comment by Lazza** [comment] 2022-08-01 11:25
Please do not close this, thank you.

**Comment by zachspears** [comment] 2022-12-30 00:27
Hello @synora and @Lazza, I am having trouble duplicating this issue for testing and prioritizing. andrealazzarotto.com is no longer hosted with WordPress.com so I am unable to follow the original troubleshooting steps. Additionally, I have tried adding my own comments with markdown to a test site in order to test but was unable to successfully recreate the outlined issue. 

Please provide updated troubleshooting steps, preferably that can be recreated in a test site so that we can move this bug report along. Thank you!

**Comment by Lazza** [comment] 2023-01-03 11:57
About a year ago **I abandoned WP.com,** despite having been a paying customer for several years (and a free user before).

This issue, among other bugs I reported or discussed with support, unfortunately shows that there was (is?) zero interest in fixing stuff.

_Fun fact:_ for two consecutive years, support granted me a free custom CSS upgrade rather than fixing a CSS bug for a theme I was using. The fix required two lines of CSS and I had provided them when asking for help.

As you mentioned, my website is not hosted there anymore. It was not feasible to stay on WP.com also for legal reasons, e.g. the impossibility of respecting GDPR while using your SaaS. Hence I will not be able to provide updated troubleshooting steps.

For years I tried to help fixing things (also for other WP.com users) by keeping the issues open and preventing them for becoming stale, given that they were still present. Now it's time to go on with life.

I hope you will understand and, if any of the bugs I reported ever get solved, thank you in advance for the fix!

**Comment by cometgrrl** [comment] 2023-03-10 00:51
This issue has been resolved/does not reproduce anymore.

**Closed by cometgrrl** 2023-03-10 00:51 UTC
Labels: [Type] Bug, [Type] Enhancement, [Status] Needs Author Reply, Comments, User Report, Needs triage
