### ISSUE TITLE
Unlaunched site: Persistent 'Great progress' message 

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#79848] opened 2023-07-25 18:38 UTC
### Quick summary

In an unlaunched site when working on posts or the editor, the message "Great progress!" will continuously appear even "Don't show this again" was selected. 

<img width="648" alt="Screenshot 2023-07-25 at 20 08 47" src="https://github.com/Automattic/wp-calypso/assets/36863633/13ec958c-3f01-4948-a0cb-f05104a596bb">

### Steps to reproduce

1. Create a new site, don't launch it yet. 
2. Create a post or work on the editor. 
3. A "Great progress!" message will appear. 
4. Click "Don't show this again." 
5. Select "Back to edit" or "Next Steps". 
6. Continue to work on your post or editor. 

### What you expected to happen

In "Great progress!" message, when "Don't show this again" is selected, the message will not appear again. 

### What actually happened

In "Great progress!" message, even when "Don't show this again" is selected, the message will continue to appear. 

### Impact

All

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Self-testing.

**Comment by cuemarie** [comment] 2023-07-25 19:31
This was noted in this CfT as well: pdtkmj-1Ay-p2#comment-2883

**Comment by cuemarie** [comment] 2023-07-25 19:41
📌 ACTIONS
- closing as duplicate of https://github.com/Automattic/wp-calypso/issues/76880

**Closed as not planned by cuemarie** 2023-07-25 19:41 UTC
Labels: Bug, [Feature] Site Settings, [Pri] Normal, Triaged, [Platform] Simple, [Platform] Atomic
