### ISSUE TITLE
Focused Launch: HTTP error when opening flow

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#49870] opened 2021-02-09 09:30 UTC
When opening Focused Launch without a domain in cart, there is a 404 error caused by calling `https://public-api.wordpress.com/rest/v1.3/domains//is-available?is_cart_pre_check=true`

Hint: we shouldn't call `select( DOMAIN_SUGGESTIONS_STORE ).isAvailable()` with an empty string at  https://github.com/Automattic/wp-calypso/blob/801dd6abfed0e9b1feadef0e264d56fb8ab9d920/packages/launch/src/hooks/use-domain-selection.ts#L46

**Comment by razvanpapadopol** [comment] 2021-02-11 14:09
a fix is going to be released in https://github.com/Automattic/wp-calypso/pull/49961

**Comment by JoshuaGoode** [comment] 2021-02-15 17:37
Stumbled upon this during triaging.

Appears the fix has been released and merged via Editing Toolkit 2.19 - #49961

Tested and could not reproduce the issue.

Labeling this one as `[Closed] Fixed ` and closing

**Closed as completed** 2021-02-15 17:37 UTC
Labels: Bug, [Pri] Normal, Focused Launch, Triaged
