### ISSUE TITLE
Customizer freezes up after selecting 'Primary' from Menus

### ISSUE THREAD

**Issue by pauloeaquino** [Automattic/wp-calypso#20891] opened 2017-12-17 08:15 UTC
#### Steps to reproduce
1. Starting at URL: https://anotherveganyogi.blog/ (Simple)
2. Visit the user's Customizer
3. Go to Menus
4. Click 'Primary'

#### What I expected
I expected to be able to use the Customizer as usual after selecting 'Primary' to edit the menu.

#### What happened instead
The entire page froze up for about 30 seconds before a strange "Page Unresponsive" prompt came up. 

It seems to happen only with just the 'Primary' option under Menus. All other options in the Customizer seem to be unaffected and are accessible.

#### Browser / OS version
Chrome 63.0.3239.84 / macOS High Sierra 10.13.2

#### Screenshot / Video
Please see screenshot here: https://cloudup.com/cxw9AeNlY7f

#### Context / Source

852802-zen

**Comment by designsimply** [comment] 2017-12-18 17:35
I was unable to reproduce the problem on a WordPress.com Simple test blog using the steps provided. I checked different themes (Ippo, Paulie, Dara, Pique). I tested with Firefox 57.0.1 and Safari 11.0.1 on Mac OS X 10.13.1.

I checked <code>/wp-admin/nav-menus.php</code> for anotherveganyogi.blog and made an edit to the primary menu and saved changes. After doing that, the menus also started working in the Customizer.

I am closing this issue because I was unable to reproduce the problem described in testing. Please re-open if it comes up again! If the problem appears again, please note any browser versions which you tested and also note whether you were able to repeat the problem on a separate test site.

**Closed by designsimply** 2017-12-18 17:35 UTC
Labels: Customizer, OSS Citizen, [Type] Bug
