### ISSUE TITLE
Nav unification: "Backup & Scan" broken menu item

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#50076] opened 2021-02-15 09:59 UTC
There seems to be a markup issue after a site goes AT for the Backup & Scan menu item.

### Steps to reproduce the behavior

1. Go to your WordPress dashboard and under Jetapck>Backup click on "Activate JetpackBackup now".
2. After it's done, I'm seeing this issue:
3. 
![image](https://user-images.githubusercontent.com/6737345/107931156-915ba280-6f84-11eb-99c7-7d1d0a4d00d2.png)

#### What I expected to happen
To see the menu item correctly.

#### What actually happened

This:
![image](https://user-images.githubusercontent.com/6737345/107931156-915ba280-6f84-11eb-99c7-7d1d0a4d00d2.png)

#### Browser / OS version
Chrome / MacOS - latest versions

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
AT

#### Is there any console output or error text?
No

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
@rachelwinspear confirmed she sees the issue as well

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Added above

**Comment by Aurorum** [comment] 2021-02-15 11:17
PR for this issue in #50079. :)

**Comment by mmtr** [comment] 2021-02-15 12:53
Closing this as a duplicate of https://github.com/Automattic/wp-calypso/issues/50039

**Closed as completed by mmtr** 2021-02-15 12:53 UTC
Labels: Bug, [Feature] Calypso & wp-admin Navigation

**Comment by mmtr** [comment] 2021-02-15 12:55
> PR for this issue in #50079. :)

This will still be needed though, even with #50039 fixed by https://github.com/Automattic/jetpack/pull/18826, since we may have other menu items using HTML entities.
