### ISSUE TITLE
FSE: Try the Site Editor = The page requested does not exist (Simple Site)

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#60521] opened 2022-01-27 00:13 UTC
### Quick summary

At wp-admin/themes.php, I see a button that says 
> You are running a theme capable of Full Site Editing! [Try the Site Editor](#)

Try the Site Editor is a button. If I click it, I am sent here:
/wp-admin/themes.php?page=site-editor-toggle

That page says: "The page you requested does not exist, or you do not have have the necessary privileges to access it."

### Steps to reproduce

1 - Create a free site
2 - Go to wp-admin/themes.php
3 - Look for the "Try the Site Editor" button
4 - If you don't see it, switch to another theme: I have seen this on Blank Canvas and Russell
5 - Click the button; you'll be sent to `/themes.php?page=site-editor-toggle`
6 - In my tests, you'll just see a not found error there.

### What you expected to happen

I would expect to either see the block editor, or not see a message inviting me to try it

### What actually happened

I see a message inviting me to try it, but clicking the link gives me a "not found" error

### Context

I was helping the person in this thread:
https://wordpress.com/forums/topic/category-at-top-of-page/

I checked their wp-admin theme.php area before answering; sure enough it said their theme supports FSE.   I _almost_ sent them from-my-head instructions on how to adjust their archive template, but decided to test to be sure. My other FSE test sites are in use right now, so I made another. I get the error on that one.

## Try the site editor
<img width="612" alt="Screen Shot 2022-01-26 at 5 08 57 PM" src="https://user-images.githubusercontent.com/3476361/151267726-6e4aa207-72c2-481d-b8cc-84d35444d298.png">

## Page not found
<img width="809" alt="Screen Shot 2022-01-26 at 5 08 11 PM" src="https://user-images.githubusercontent.com/3476361/151267670-609938f4-8262-4151-9878-322582842d02.png">

### Simple, Atomic or both?

Simple

### Browser, operating system and other notes

I consistently get this no matter which theme I choose.

### Reproducibility

Consistent

**Comment by kerrynicl** [comment] 2022-02-24 16:48
Created a new free site and was not able to reproduce using the blank canvas or russell theme or twenty twentytwo. There was no notification on the page. I'll close this for now, but please reopen if you come across this again.
<img width="581" alt="Screenshot on 2022-02-24 at 11-47-52" src="https://user-images.githubusercontent.com/83325600/155569349-5effa454-5ef8-4f5a-b0d3-358787873cc4.png">

**Closed as completed by kerrynicl** 2022-02-24 16:48 UTC
Labels: Bug, Triaged, [Closed] Not Reproducible, [Feature] Full Site Editor
