### ISSUE TITLE
Editor: Post Settings sidebar tooltips do not position correctly

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#16214] opened 2017-07-13 20:41 UTC
#### Steps to reproduce
1. Create a new post (or edit an existing open)
2. Open the Post Settings sidebar
3. Click the informational icons to show the tooltips
4. (repeat)

#### What I expected

The tooltips to always be positioned completely visible on the page without having to scroll horizontally.

#### What happened instead

The first time, the tooltips appear to display correctly (though, they might be slightly cutoff on the right-hand side -- hard to tell).

The second time, the tooltips are not positioned correctly. They are overflow the right side of the page.

#### Browser / OS version

Happens in Chrome, Safari, and Firefox (and likely other browsers)

#### Screenshot / Video

![post settings tooltips](https://user-images.githubusercontent.com/2098816/28186676-1552b3ea-67ea-11e7-99dc-c5440bd0d078.gif)

#### Context / Source

#manual-testing

**Comment by rachelmcr** [comment] 2018-01-23 18:13
I tested and could not reproduce this issue. I believe it was fixed with https://github.com/Automattic/wp-calypso/pull/19992.

**Closed by rachelmcr** 2018-01-23 18:13 UTC
Labels: Editor, [Type] Bug
