### ISSUE TITLE
Jetpack Plugins: Switching from single site view to all sites view does not refresh list

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/wp-calypso#14974] opened 2017-06-09 20:13 UTC
When viewing the plugin list for a single site, then switching to all sites there is no update to the listing on the page until there is a manual refresh forcing it. It should automatically update that content when switched over. 

#### Steps to reproduce
1. Start at WordPress.com on an account with multiple Jetpack connected sites
2. View details for one of the sites, and go to Plugins to view the full list. 
3. Go to Switch Site → All Sites
4. Note there is no refresh and it continues to show the list for the single site until the page is refreshed manually. 

#### What I expected
The page with the plugin list to refresh, showing the full list for all managed sites

#### What happened instead
Nothing. It stayed listing the single site's plugins. 

#### Browser / OS version
MacOS - Chrome/FF

#### Screenshot / Video
![all sites plugin fail](https://user-images.githubusercontent.com/16127063/26992820-faefa348-4d25-11e7-92ab-4b22cf27105c.gif)

(ignore the errors that pop up when refreshing, there are some outdated sites there that are no longer functional, but still show the connection

#### Context / Source

Reported by Jetpack Premium user in 3255705-t

**Comment by beaulebens** [comment] 2018-02-06 20:26
Confirmed this is still happening.

**Comment by ockham** [comment] 2018-03-07 14:53
The UI has changed quite a bit, and I'm having trouble repro'ing this reliably -- think I managed to repro only once. Just to clarify, do I start at `https://wordpress.com/plugins/manage/<JPsite>`? (I.e. at the `manage/`  route)

**Comment by rtrevellyan** [comment] 2018-03-07 15:25
Yes, start at the plugin management page for a single site, then 'switch site' to 'all my sites'.

FWIW it's been quite a while since I've seen this issue.

**Comment by ockham** [comment] 2018-03-07 18:15
Instructions to repro, courtesy @seear:

> * start on all-sites/stats
> * clear local storage
> * switch to a jetpack site
> * plugins->manage
> * switch to all sites

**Comment by ockham** [comment] 2018-03-08 16:42
_Possibly_ fixed by #23128.

**Comment by alaczek** [comment] 2019-04-30 00:42
I believe this is not an issue anymore, as plugins page is now displayed in the Calypso-ified wp-admin, and it's not possible to switch a site, while remaining on plugins page. Closing.

**Closed by alaczek** 2019-04-30 00:42 UTC
Labels: FixTheFlows, Jetpack, Plugins, [Pri] Normal, [Type] Bug
