### ISSUE TITLE
FSE: Adding a new page and editing header hangs

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#36018] opened 2019-09-06 01:45 UTC
Create a new simple site with FSE enabled. Add a new page. Click the edit header button, the loading spinner shows but nothing happens.

This doesn't happen consistently, but I could reproduce a few times in a row on a page.

This is likely a duplicate of https://github.com/Automattic/wp-calypso/issues/36015 but we need to test and verify the fix.

**Comment by apeatling** [comment] 2019-09-06 01:47
<img width="426" alt="Screen Shot 2019-09-05 at 6 46 56 PM" src="https://user-images.githubusercontent.com/1464705/64395011-92f20e80-d00d-11e9-8299-6eb37140dd0d.png">

**Comment by glendaviesnz** [comment] 2019-09-06 03:22
I could reliably replicate this in Horizon site by adding a new page, selecting blank template and then straight away clicking on the Edit Header button. This causes and Auto Draft save and stuck spinner as noted:

<img width="525" alt="autodraft" src="https://user-images.githubusercontent.com/3629020/64398549-5976dd00-d0b9-11e9-8fe2-1103ec325b22.png">
 
There are no errors in the console when this happens.

I can't replicate the issue using local calypso build against the same site - following the above steps works perfectly every time for me. Didn't have any luck trying to track down the cause of this - suspect some difference between calypso prod build and local dev build that is stopping programmatic nav button click from firing - https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js#L102

**Comment by glendaviesnz** [comment] 2019-09-06 03:50
Have also now managed to replicate this on local install. It is very easy to replicate in this case, just edit an existing page and then try and click the Edit Header button - it is related to this - https://github.com/Automattic/wp-calypso/issues/36015 - in that saving the page does not remove the direct flag - on saving the page you will notice that the 'Update' button stays active, and so https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js#L97 check never passes.

Switching to non-fse theme fixes the dirty flag issue, so trying to work out why FSE is stopping the clearing of this flag on save.

**Comment by glendaviesnz** [comment] 2019-09-23 02:49
This issue should be fixed by whatever solution is found for #36015

**Comment by glendaviesnz** [comment] 2019-09-24 23:14
This is fixed by https://github.com/WordPress/gutenberg/pull/17532

**Comment by noahtallen** [comment] 2019-09-25 21:42
This has been cherry picked into our wpcom Gutenberg update. Will close once that ships.

**Comment by noahtallen** [comment] 2019-09-26 19:27
Gutenberg has landed. Closing!

**Closed by noahtallen** 2019-09-26 19:27 UTC
Labels: [Pri] BLOCKER, [Type] Bug
