### ISSUE TITLE
WordPress.com - My Plans Page Only Gives Ability to Upgrade Storage for 1-year Plans

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#84116] opened 2023-11-10 17:23 UTC
### Quick summary

On the WordPress.com Plans page (https://wordpress.com/plans/{SITEURL}), if the site currently has a 1-year Business or Commerce plan, there is a dropdown menu which allows the customer to upgrade their site storage from 50 GB to 100 or 150 GB. This dropdown menu does not appear if the site has a monthly plan or a multi-year plan, and there is a red Upgrade button which does nothing.

### Steps to reproduce

1. Start a site and purchase a monthly or 2-year Business or Commerce plan.
2. Go to Upgrades > Plans
3. Note that the dropdown to upgrade storage is not present.
4. Note that there is a red Upgrade button that does nothing when clicked.

### What you expected to happen

The customer should be able to purchase the storage upgrade on any plan term.

This is what the plan card looks like with a 1-year plan.

<img width="1080" alt="Screenshot 2023-11-10 at 12 19 03 PM" src="https://github.com/Automattic/wp-calypso/assets/12906034/782a4ebd-83e9-4de7-9abf-df1dc13108b6">

### What actually happened

The customer is unable to purchase the storage upgrade if they have a monthly or multi-year plan. There is a red Upgrade button on the plan card that does nothing when clicked.

This is what the plan card looks like with a 2-year plan.

<img width="1058" alt="Screenshot 2023-11-10 at 12 23 32 PM" src="https://github.com/Automattic/wp-calypso/assets/12906034/03ae9c23-1bb4-41ad-b056-ee7b73a7d7c2">

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by liviopv** [comment] 2023-11-18 15:32
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Simple, 2y plan
![CleanShot 2023-11-18 at 16 19 30@2x](https://github.com/Automattic/wp-calypso/assets/14153300/70411b79-ac2f-4ed3-a097-d4b00d64ad31)

Atomic, monthly plan
![CleanShot 2023-11-18 at 16 24 03@2x](https://github.com/Automattic/wp-calypso/assets/14153300/1b9f0b73-aeda-48c4-bf96-85c547ed08f1)


📌 ACTIONS
- Triaged


📌 Message to Author
@masperber I think this might be an intentional decision, if it is, we'll switch to a Feature Request. Pinging @gmovr to confirm if it's intentional or a bug

**Comment by mmtr** [comment] 2024-07-25 13:58
I think the limitation comes from this line:

https://github.com/Automattic/wp-calypso/blob/a94d9a6e0a66e08d1e83b99d27e034e14790be69/packages/plans-grid-next/src/components/shared/storage/constants.ts#L3

I wonder if it's just a matter of adding `PLAN_BUSINESS_MONTHLY`, `PLAN_BUSINESS_2_YEARS`, etc to that list.

@chriskmnds it seems you added that in https://github.com/Automattic/wp-calypso/pull/91050. Do you know if the limitation is intentional and only yearly plans can upgrade the storage?

**Comment by chriskmnds** [comment] 2024-07-25 14:06
> @chriskmnds it seems you added that in https://github.com/Automattic/wp-calypso/pull/91050. Do you know if the limitation is intentional and only yearly plans can upgrade the storage?

Yes, it's been that way on the grid all along. I recall some chat in Slack about changing it to allow for 2+ year plans, but not sure what the consensus is. @dzver or @southp would know more

@mmtr

**Comment by southp** [comment] 2024-07-26 08:11
@mmtr 

> I wonder if it's just a matter of adding PLAN_BUSINESS_MONTHLY, PLAN_BUSINESS_2_YEARS, etc to that list.

It won't be as simple as that, since there is no monthly, 2-yearly, or 3-yearly counterpart for the storage add-on. Those products will have to be added from the backend first. Some frond-end logics will also need to be updated as described by Dehan here: https://github.com/Automattic/wp-calypso/issues/85773#issuecomment-1908717433.

What's more is that it is considered a low priority work given the low conversions it has generated, so MarTech won't prioritize it in the foreseeable future unless there is a key business case made.

**Comment by lsl** [comment] 2024-07-29 05:05
@southp is it a bug that you can purchase the upgrade separately via the addon's page?

https://wordpress.com/add-ons/test135145.wpcomstaging.com (site with 2year business plan)

![Screenshot 2024-07-29 at 15-02-38 Checkout — WordPress com](https://github.com/user-attachments/assets/0c5bfb5a-5511-409e-8dfa-72e722253c9c)

**Comment by lsl** [comment] 2024-07-29 05:07
I can't replicate the "Upgrade" button issue, for me it's a standard manage plan button with the greyed out storage amount of 50GB. 

If the above isn't a bug we can close this out.

**Comment by southp** [comment] 2024-07-29 06:19
It's not a bug. Any add-on can be purchased there, but only as an annual subscription since they are separated subscriptions from the plan.  
Ideally I wish we could invest time in implementing add-on as something bundled with a plan subscription, so the idea of an add-on is easier to grasp :)

**Closed as not planned** 2024-07-31 03:37 UTC
Labels: Bug, [Feature] Plans & Upgrades, [Pri] Low, [Feature Group] WPCOM Store & Purchases, Triaged, [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered, [Product] WordPress.com
