### ISSUE TITLE
Audit experimental features in WordPress Components Gallery

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#46496] opened 2020-10-15 13:57 UTC
**Master tracking issue**: https://github.com/Automattic/wp-calypso/issues/44251

[WordPress Components Gallery](https://github.com/Automattic/wp-calypso/blob/1790a34b75331668a88f027a6d595e986413ec19/client/devdocs/design/wordpress-components-gallery) is dependant on [experimental](https://github.com/WordPress/gutenberg/blob/1d0eecb53fc3b91b1ad7bd51a368e088243fa8eb/docs/contributors/coding-guidelines.md#experimental-and-unstable-apis) features without a fallback for a scenario where such a feature is not supported anymore. Below is a list of usages that we need to update in this matter:

- [ ] https://github.com/Automattic/wp-calypso/blob/1790a34b75331668a88f027a6d595e986413ec19/client/devdocs/design/wordpress-components-gallery/alignment-matrix-control.tsx#L9
- [ ] https://github.com/Automattic/wp-calypso/blob/1790a34b75331668a88f027a6d595e986413ec19/client/devdocs/design/wordpress-components-gallery/autocomplete.tsx#L9
- [ ] https://github.com/Automattic/wp-calypso/blob/1790a34b75331668a88f027a6d595e986413ec19/client/devdocs/design/wordpress-components-gallery/box-control.tsx#L9
- [ ] https://github.com/Automattic/wp-calypso/blob/1790a34b75331668a88f027a6d595e986413ec19/client/devdocs/design/wordpress-components-gallery/radio.tsx#L10
- [ ] https://github.com/Automattic/wp-calypso/blob/1790a34b75331668a88f027a6d595e986413ec19/client/devdocs/design/wordpress-components-gallery/radio.tsx#L11
- [ ] https://github.com/Automattic/wp-calypso/blob/1790a34b75331668a88f027a6d595e986413ec19/client/devdocs/design/wordpress-components-gallery/text.tsx#L9
- [ ] https://github.com/Automattic/wp-calypso/blob/1790a34b75331668a88f027a6d595e986413ec19/client/devdocs/design/wordpress-components-gallery/toolbar.tsx#L28
- [ ] https://github.com/Automattic/wp-calypso/blob/1790a34b75331668a88f027a6d595e986413ec19/client/devdocs/design/wordpress-components-gallery/tree-grid.tsx#L11
- [ ] https://github.com/Automattic/wp-calypso/blob/1790a34b75331668a88f027a6d595e986413ec19/client/devdocs/design/wordpress-components-gallery/tree-grid.tsx#L12
- [ ] https://github.com/Automattic/wp-calypso/blob/1790a34b75331668a88f027a6d595e986413ec19/client/devdocs/design/wordpress-components-gallery/tree-grid.tsx#L13

**Comment by WunderBart** [comment] 2020-10-15 15:08
@Automattic/team-calypso is this something that you could look into?

**Comment by saramarcondes** [comment] 2020-10-15 15:49
@diegohaz I wonder if you have any insight into the best way to deal with experimental features? Would it be wiser to just not use them at all in this setting or is there a safe way to use them? I'm not familiar with how to do "safe" imports or anything like that.

**Comment by diegohaz** [comment] 2020-10-15 16:52
@saramarcondes 

If it's just for internal usage and we're okay with things unexpectedly breaking, I think it's not a big problem. But, ideally, we shouldn't depend on experimental features.

The problem is that code will eventually break:

> The conversion to a stable API will inherently be considered a breaking change by the mere fact that the function name must be changed to remove the `__experimental` prefix.
>
> [source](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md#experimental-and-unstable-apis)

If we use experimental features, we should set fixed versions in our package.json ([which is currently not the case](https://github.com/Automattic/wp-calypso/blob/bfc86cd4bc4d68f9a3528ecc60927a5f0e95fe92/client/package.json#L54)).

For reference, this has already been a problem because Gutenberg was depending on experimental features of Reakit without fixing the dependency version: https://github.com/reakit/reakit/pull/667#issuecomment-647108385. Reakit has a dedicated section about this that would also apply to Gutenberg usage: https://reakit.io/docs/experimental/

**Comment by saramarcondes** [comment] 2020-10-15 17:32
That's helpful @diegohaz, thank you. I think it's safe for things to break in the components gallery world... however I'm wary of adding another potentially roadblock to upgrading the WordPress dependencies (as today it's already a hassle). I wonder if we should remove these afterall?

This PR https://github.com/Automattic/wp-calypso/pull/46424 _does_ depend on an experimental feature... in fact I don't believe there's any other component that could be used there. Luckily I believe we can switch it to just use a regular `input` because it is ultimately de-styled by the Search component's styles.

**Comment by griffbrad** [comment] 2020-10-15 17:58
I'd recommend doing a pass through the list that @WunderBart provided and asking whether each one provides value in regards to the broader style compatibility efforts for `@wordpress/components` in Calypso. For example, I feel totally fine dropping `AlignmentMatrixControl` out of the gallery. It's a newer component used in particular blocks that is styled with CSS-in-JS, so it's not really important to monitor as we remove global styles from Calypso. `ToolbarItem`, on the other hand, can be used in many core blocks (wherever a straightforward `ToolbarButton` isn't appropriate) and may be used elsewhere in Calypso. 
I'd err on the side of removing the experimental usages to ease future upgrades, like you suggested. Worst-case, though, it's good to keep in mind that removing the usage in the context of the gallery is always pretty trivial. We're not talking about a component really being used for actual functionality.

**Comment by tyxla** [comment] 2020-10-16 07:27
I agree we can drop some of the experimental components out - some of them may never end up being stable ones, and if they end up stable, we can always include them back.

It's worth keeping an eye on the WordPress components gallery every now and then, as the list of experimental components will always change with every new release. 

That being said, it's also worth keeping an open mind that the gallery is far from being a widely used tool at this point, but that is going to start changing as we continue adopting `@wordpress/components` more and more in Calypso.

**Comment by WunderBart** [comment] 2020-10-16 13:41
Worth keeping an eye on this one in case you've missed it: https://github.com/WordPress/gutenberg/issues/25786

**Comment by diegohaz** [comment] 2020-10-16 16:57
> `ToolbarItem`, on the other hand, can be used in many core blocks (wherever a straightforward `ToolbarButton` isn't appropriate) and may be used elsewhere in Calypso.

`ToolbarItem` is an example of a component that dropped the `__experimental` flag. So this will break when upgrading `@wordpress/components`.

**Comment by sirreal** [comment] 2020-11-27 16:35
Closing this as of https://github.com/Automattic/wp-calypso/pull/47712 / p4TIVU-9xW-p2

**Closed by sirreal** 2020-11-27 16:35 UTC
Labels: [Goal] Gutenberg, [Type] Task
