### ISSUE TITLE
Twenty Twenty Two (Red): Templates and Template Parts Uneditable

### ISSUE THREAD

**Issue by druesome** [Automattic/wp-calypso#72118] opened 2023-01-14 06:26 UTC
### Quick summary

Any edits made to templates and template parts cannot be saved on Simple sites using the Twenty-Twenty Two (Red) theme.

Screencast: https://d.pr/v/5b16Wi

### Steps to reproduce

1. Activate Twenty Twenty-Two (Red) theme on a Simple site
2. Edit the Header or Footer template part
3. Try changing the background color of the group block inside the template, or deleting a navigation block
4. Save changes
5. View the live site and navigate to a page using these parts
6. Also try editing the Page template by changing some colors and deleting some blocks
7. View the live site and navigate to a page using this template

### What you expected to happen

I expected the changes to reflect in the template parts and template that were edited.

### What actually happened

None of the changes I made were actually saved.

### Context

Ticket: [#5862994-zen](5862994-zd-woothemes)

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Twenty Twenty-Two (Red) theme, and possibly other Twenty Twenty-Two themes as well.  The same issue happens in the Twenty Twenty-Two (Swiss) theme.  This seems to happen on only Simple sites.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by ianstewart** [comment] 2023-01-17 16:44
I was unable to reproduce with a new site on simple. I was able to make a change to my header template part, save, and see the change reflected in both the editor and front-end of my site.

![image](https://user-images.githubusercontent.com/545779/212959659-16dd4097-74a6-4dc1-ac6d-bf08391809b0.png)

**Comment by druesome** [comment] 2023-01-20 13:18
Hi @ianstewart !  Thanks for checking.  I was able to replicate this again on a different site of mine.  Please check this screencast on what happened:

https://d.pr/v/hSyEI8

As you can see, I am editing the Page template.  I changed the background, text and link colors on the header template part, and also changed the background color of the content area. I saved all changes but this did not reflect on my About page which uses the default page template.  When I refreshed the editor, all the changes I made were gone.

Not sure if I'm missing something obvious, but let me know if I am.  Thanks again!

**Comment by worldomonation** [comment] 2023-01-23 20:25
I attempted to reproduce this issue on a test Simple site.

1. switch theme to 2022 Red, opting to replace the home page contents with one provided by the theme.
2. open the FSE to edit the template part `Heade (dark, small)`.
3. replaced the background color with sky blue.
4. reloaded the home page.

The home page showed sky blue header as expected.

I did some further testing by deleting blocks and changes also took effect.

![Screen Shot 2023-01-23 at 12 23 16 PM](https://user-images.githubusercontent.com/6549265/214142477-dda79fbc-886b-4562-956e-4e7d48d58d81.png)
![Screen Shot 2023-01-23 at 12 21 52 PM](https://user-images.githubusercontent.com/6549265/214142487-149541b5-00df-4ee7-b64e-bcd704fc2400.png)
![Screen Shot 2023-01-23 at 12 21 19 PM](https://user-images.githubusercontent.com/6549265/214142489-3fa755b5-abe0-485a-9687-6c2873a9e8eb.png)

**Comment by danielbachhuber** [comment] 2023-01-23 21:02
@worldomonation Can you share the network requests as you hit save? Are all of the REST API requests successful?

**Comment by worldomonation** [comment] 2023-01-23 21:25
> @worldomonation Can you share the network requests as you hit save? Are all of the REST API requests successful?

@danielbachhuber  I inserted a heading block between the header and the bird image, and this is what I had:

![image](https://user-images.githubusercontent.com/6549265/214152922-8340e357-fb4a-4611-90c5-f4cb8d1d47dc.png)

These are the responses:
2edcc-pb/
2edcd-pb/
2edce-pb/

**Comment by jp-imagines** [comment] 2023-01-25 15:24
Came across this issue on Twenty Twenty-Two (Mint) in 5896680-zd-woothemes. All changes to the `Header` template part (listed as coming from Twenty Twenty-Two) aren't saved. User particularly wanted to remove a menu item, but couldn't do so. Same behavior if changes are made on a template using that template part, or if only the template part itself is being edited.

In the network log, on save, there's a single request (Request URL: `https://public-api.wordpress.com/wp/v2/sites/203758657/template-parts/pub/twentytwentytwo-mint//header?_envelope=1&environment-id=stage&_gutenberg_nonce=104067a238&_locale=user`) which reportedly succeeds (`200`), but the response clearly shows the pre-changes block code. (Specifically, after changing the Nav block from using a _Page List block_ to a series of page links, I still see the `wp:page-list` code in the response.)

**Comment by cuemarie** [comment] 2023-02-02 18:18
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated** during testing here: https://github.com/Automattic/wp-calypso/issues/72684

📌 FINDINGS/SCREENSHOTS/VIDEO
- Could replicate this issue on a Simple Site in TT2 (Red), but not TT2. This seems to be part of a larger issue, closing in favor of #72684 

https://user-images.githubusercontent.com/27249804/216411678-cb9409b5-a639-41bc-b58f-dcdd16fdca04.mov

📌 ACTIONS
- Closed as duplicate of #72684

**Closed as completed by cuemarie** 2023-02-02 18:18 UTC
Labels: Bug, Triaged, [Platform] Simple
