### ISSUE TITLE
Editor: Media: need to click "Close" multiple times after adding a gallery

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#21009] opened 2017-12-20 19:13 UTC
Steps to reproduce:

1. Go to My Sites > Blog Posts > Add.
1. Click Add > Media in the editor toolbar.
1. Insert multiple images in a gallery.
1. Click the "Save" link.
1. Click the "Close" button. Repeat if needed.

<strong>Result:</strong> it takes multiple clicks on the "Close" link before the post actually closes.

<strong>Video:</strong> [36s](https://cloudup.com/cKbNQOkdvFA)

<img width="1280" alt="screen shot 2017-12-20 at wed dec 20 12 11 47 pm" src="https://user-images.githubusercontent.com/1119271/34224139-11487092-e57f-11e7-86d8-5e14cf370b90.png">
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11648 using Firefox 57.0.1 on macOS 10.13.2.</sup>

**Comment by alisterscott** [comment] 2017-12-20 22:05
Duplicate of #20582

**Comment by alisterscott** [comment] 2017-12-20 22:06
This only applies to Firefox AFAIK

**Closed by alisterscott** 2017-12-20 22:05 UTC
Labels: Editor, Media, [Type] Bug
