### ISSUE TITLE
MSEdge: Gutenberg: Impossible to upload files

### ISSUE THREAD

**Issue by jorgefilipecosta** [Automattic/wp-calypso#30545] opened 2019-02-01 16:51 UTC
Originally created in https://github.com/WordPress/gutenberg/issues/13607 by @JessBoctor.

Original issue:

**Describe the bug**

When in Microsoft Edge and a user tries to add a block which uses the media library, the following error appears before they can upload or add any media: `Object doesn't support property or method 'has'`

**To Reproduce**
1. Open Microsoft Edge
2. Log into WordPress.com
3. Go to 'Add' new post
4. Try to add an `audio` block
5. See the error.

**Expected behavior**

The block would show the option to add media and allow access to the media library or uploader

**Screenshots**

![image](https://user-images.githubusercontent.com/12505355/52006717-accce100-2481-11e9-84ec-29d05f8ff239.png)

**Desktop (please complete the following information):**
 - Browser Microsoft Edge

Some additional comments:
I managed to reproduce the issue while testing on WordPress.com.
It happens even for simple image uploads to the image block (on MSEdge). 
I did not manage to reproduce the issue testing with a default WordPress installation.

**Comment by noahtallen** [comment] 2019-07-22 18:56
Gonna give a shot at reproducing this on my crappy windows laptop!

**Comment by noahtallen** [comment] 2019-07-22 19:16
Was unable to reproduce on Simple or Atomic sites running Edge 44.17763.1.0. Edge HTML version 18.17763. (I think this version is from early May 2019, which is newer than the original reproduction.) I tried both image and audio file uploads on both existing and new posts, and they all seemed to work fine.

My guess is that this has been resolved by one of the following:
- Running a newer version of Gutenberg on dotcom now
- Updates to the Edge browser (i.e. they switched to Chromium at some point in the past year)
- Updates to Windows
- Other fixes landed on dotcom in the meantime
- The simple passage of time 😉

I'll close this for now, but feel free to reopen if anyone can reproduce this again!

**Closed by noahtallen** 2019-07-22 19:16 UTC
Labels: [Goal] Gutenberg, [Pri] Normal, [Type] Bug
