### ISSUE TITLE
Preview resulting in "Oops! That page can’t be found."

### ISSUE THREAD

**Issue by mattm** [Automattic/wp-calypso#1097] opened 2015-12-01 11:37 UTC
Whenever I hit the Preview button on a draft post (on the Mac app on a non-Jetpack site), I am always shown a "Oops! That page can’t be found." preview:

<img width="1025" alt="screen shot 2015-12-01 at 6 34 06 am" src="https://cloud.githubusercontent.com/assets/44436/11499658/ac7771e6-97f5-11e5-87e9-a24f6a7d64c5.png">

<img width="994" alt="screen shot 2015-12-01 at 6 34 16 am" src="https://cloud.githubusercontent.com/assets/44436/11499661/b013627e-97f5-11e5-90be-229dee7ac710.png">

The fact that it's not a known issue though makes me suspect it might be an issue specific to my computer somehow otherwise I imagine it would be affecting a lot of users. I'm happy to help debug it as needed if that is the case.

**Comment by designsimply** [comment] 2015-12-01 15:17
Thanks for the report! This is a duplicate of #904. I adjusted the title there to help make it a little more clear.

**Closed by designsimply** 2015-12-01 15:17 UTC
Labels: Editor, [Type] Bug

**Comment by mattm** [comment] 2015-12-02 19:14
Thanks @designsimply. In case it matters when troubleshooting, this was for a WordPress.com site and I was logged in already via Chrome (for his, it was a Jetpack site where he wasn't logged in).
