### ISSUE TITLE
Add an alert message during the domains purchase flow if the user already has a domain associated with their site

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-calypso#27932] opened 2018-10-18 14:50 UTC
As a new Happiness Engineer for WP.com, there's a situation I keep running into repeatedly. This week alone, I've helped three different users who have made this mistake. They register a new domain associated with their existing site (which already has a domain), when what they actually meant to do was create a new site and register a domain for the new site. They think adding a new domain is how they create a new site.

It can sometimes be time consuming to help the user get everything sorted out, show them how to create a new site, and get the domain associated with the new site. We also typically have to issue a refund as well.

I'd like to make a suggestion to add a notification or alert message somewhere during the domains purchase flow, if the user _already_ has a domain associated with their site.

The additional domain is purchased via My Site > Domains > Add.

I think having it pop up at the beginning of the process, like on this screen, would be ideal: http://cld.wthms.co/42m8vc

The message could say something along the lines of:
>You're purchasing an additional domain for CURRENT SITE. Would you like to create a new site instead? If so, click here.

I believe this would clear up a lot of confusion :)

**Comment by arunsathiya** [comment] 2018-11-02 08:21
>They register a new domain associated with their existing site (which already has a domain), when what they actually meant to do was create a new site and register a domain for the new site.

When the page https://wordpress.com/domains/add is launched, a site picker is shown from which it can be noted that a custom domain is already associated to the site.

This is a great suggestion though, @lakellie! It would most certainly help to have the list of registered domains on https://wordpress.com/domains/add, like how it does on https://wordpress.com/domains/manage

**Comment by Aurorum** [comment] 2019-07-30 10:53
This is still an issue, PR in #34990 to add the notice. :)

It doesn't add the list of registered domains though, should this be included in addition to the notice or in replacement of the notice? Here's what the PR proposes currently:

<img width="1207" alt="Screenshot 2019-07-30 at 11 43 28" src="https://user-images.githubusercontent.com/43215253/62123740-7f41e280-b2c0-11e9-9d14-fb076e5561fb.png">

**Comment by wpericam** [comment] 2019-08-20 02:10
I just filed #35593 and closed it to add reports here

**Comment by wpericam** [comment] 2019-08-20 02:14
Reports here: 

- zen-1908600
- zen-1974175
- HC-9206112
- HC-13711178
- zen-2148181
- HC-13841102
- HC-10349709
- HC-14374905
- zen-2265841
- zen-2265841
- HC-14006684
- zen-2282098
- HC-14653046

**Comment by marcuswisecaesar** [comment] 2019-08-21 22:04
Reports here as well

14723791 - hc

**Comment by wpericam** [comment] 2019-08-25 05:59
2298160-zen

User mapped a domain to Site 1 and it was intended for Site 2

**Comment by wpericam** [comment] 2019-09-01 18:40
+1 report here 

2315440-zen

**Comment by sixhours** [comment] 2019-09-02 20:07
This is moving to On Hold as per @wensco 's request in #34990

**Comment by wpericam** [comment] 2019-10-17 00:15
+1 here 16014435-hc

**Comment by wpericam** [comment] 2019-10-30 01:58
10513784-hc

Added a secondary domain instead of a new site and had to create a site and move the domain over.

**Comment by klimeryk** [comment] 2019-10-31 11:54
@wensco, what do you think of @Aurorum's suggestion here? https://github.com/Automattic/wp-calypso/pull/34990#issuecomment-540661732 I like surfacing the option to add a new site there, but I wonder if we won't end up with a new problem - users creating a new site instead of adding a domain to their existing one ;)

**Comment by wensco** [comment] 2019-10-31 22:14
> @wensco, what do you think of @Aurorum's suggestion here? [#34990 (comment)](https://github.com/Automattic/wp-calypso/pull/34990#issuecomment-540661732) I like surfacing the option to add a new site there, but I wonder if we won't end up with a new problem - users creating a new site instead of adding a domain to their existing one ;)

I think we're trying to fit a round peg into a square hole. :) 

I _think_ the issue is that we're conflating domain management and site management in the UI, which as you mention, creates a strong possibility that we will introduce a new problem by fixing the original problem. 

The "add site" button is more subtle than the original banner suggestion but it's functionally the same solution. 

Respectfully, I believe the problem is that it is completely invisible as to how to create a new site within the UI unless the user thinks to click the site switcher ("My Sites") which is not really intuitive. Instead of jamming in site creation into domain management where it doesn't belong imho, why not find a way to expose site creation?

As a compromise, we could consider an informational notice when a user adds a domain - something like "You are adding [domain name] to your existing site [site]" - that would at least cue the user that the domain will be associated with a particular site.

I searched our support docs for "add site" and "create site" and came up with nothing relevant. It wasn't until I searched for "create blog" that I found [this](https://en.support.wordpress.com/create-a-blog/) page. Improving our support docs ti surface this topic better would be a quick win.

**Comment by Aurorum** [comment] 2019-10-31 23:27
> Where do I go to create a new site here? It's (to me) non-intuitive to have to go to My Sites...

I think this example is the exception though. My understanding of this issue is that most people don't have multiple sites, since they're unaware of the way to create a site, therefore removing that problem.

**Comment by wensco** [comment] 2019-11-01 20:47
> I think this example is the exception though. My understanding of this issue is that most people don't have multiple sites, since they're unaware of the way to create a site, therefore removing that problem as "Add New Site" is then always visible on the sidebar.

I'm really not trying to be argumentative, I promise :), but the "add new site" isn't really always visible even if you only have one site. If you expand some of the sidebar menu options (eg, site, manage, design etc), it pushes the "add site" below the fold and you have to scroll to find it: https://d.pr/i/s1UOta

Why not test moving the "add new site" from the bottom of the sidebar to be at the top of the sidebar?
Single site:
<img width="325" alt="2019-11-01_1637" src="https://user-images.githubusercontent.com/7942966/68055031-28d0af80-fcc6-11e9-856d-c3abea84f8c5.png">

Multiple sites (no need to hit the site switcher to see the option to add a new site)
<img width="282" alt="2019-11-01_1638" src="https://user-images.githubusercontent.com/7942966/68055068-3a19bc00-fcc6-11e9-8cec-ec236f042d35.png">

> Just to clarify, where should this go? I'm not sure it's suited for the Checkout, but I can't find an alternative unless it's better to use a Global Notice?

I'm not really sure. I agree on the checkout thing - by the time a user gets there, it's probably not a good experience to realize they meant to make a new site.

Have we considered changing the "Add Domain" button text to "Add domain to this site" or something similar?
<img width="700" alt="2019-11-01_1643" src="https://user-images.githubusercontent.com/7942966/68055382-e8256600-fcc6-11e9-9057-bd7b7a818058.png">

Other idea (with or without the button text change) - a notice to indicate which site they are managing domains on:
<img width="1013" alt="2019-11-01_1641" src="https://user-images.githubusercontent.com/7942966/68055424-f8d5dc00-fcc6-11e9-9794-350265af8822.png">

**Comment by Aurorum** [comment] 2019-11-01 22:23
> Why not test moving the "add new site" from the bottom of the sidebar to be at the top of the sidebar?

I agree, that would definitely be more clear! Would you suggest creating an A/B test for that (I'm not sure if there's anything to measure results, so not certain that's the ideal solution, but I think there's no alternative)?

In the meantime, I think the other two changes are harmless but beneficial in reducing confusion, so I've proposed them in #37259. :)

**Comment by Aurorum** [comment] 2019-11-11 22:12
#37497 is going to render the previous suggestion impossible unfortunately.

**Comment by katiebethbrown** [comment] 2019-12-04 19:57
Another report in 11193734-hc. Seems the user may have misunderstood the domain upsell, thinking this was starting a new site:

<img src="https://cdn-std.droplr.net/files/acc_680347/Q17NVO">

In this case, I don't know that the location of the "Add Site" button matters, but an indication in the domain purchase flow that it would be an additional domain for the current site might be helpful.

**Comment by katiebethbrown** [comment] 2019-12-18 21:55
I had a chat with a user that had registered 4 domains, expecting them to be different sites. A notice of some sort would have likely stopped that from occurring and let them create new sites as they intended.

https://mc.a8c.com/support-stats/happychat/transcript.php?id=17398701

**Comment by fditrapani** [comment] 2020-03-03 19:39
This issue was also brought up here with some other suggestions to fix it: https://github.com/Automattic/wp-calypso/issues/39829

**Comment by Aurorum** [comment] 2020-04-22 16:18
The sidebar change is being proposed in #41372

**Comment by zdenys** [comment] 2021-03-25 09:44
Most recently this topic has been re-discussed here p7DVsv-aXZ-p2

**Comment by kelliepeterson** [comment] 2021-06-17 22:05
This specific issue has been addressed with https://github.com/Automattic/wp-calypso/pull/50762

Closing.

**Closed by kelliepeterson** 2021-06-17 22:05 UTC
Labels: Domains, User Report, [Type] Enhancement
