### ISSUE TITLE
CoBlock Hero Block: Some Text Fields Uneditable

### ISSUE THREAD

**Issue by jacoswan** [Automattic/wp-calypso#39622] opened 2020-02-24 07:24 UTC
Only an issue on WPCOM, not an issue on WPORG.

#### Steps to reproduce
1. Starting in a post/page editor with CoBlocks (tested on Free, Premium and BIZ AT)
2. Add a Hero block
3. Edit Title, Body and both Button text
4. One of the text fields will be difficult/impossible to edit - mostly Button 2's text, but occasionally also Button 1's text

#### What I expected
I expected all the text fields to be easily edited at will and in any order. 

#### What happened instead
Title, Body and Button 1 text was easily edited, but then Button 2 wouldn't activate the text field to be edited. Colleague tested the same, managed to edit Button 2, but then found Button 1 had become uneditable. 

#### Browser / OS version
Issue on Chrome Version 80.0.3987.106 and Safari Version 13.0.4

Not an issue on Firefox 72.0.2
MACOS 10.15.2

On the BIZ AT site the CoBlocks version was 1.21.1

#### Screenshot / Video
![screen-capture-200224](https://user-images.githubusercontent.com/15178758/75134783-fcfb8e80-56e7-11ea-8a06-fb076790a100.gif)

#### Context / Source
It stemmed from a similar, but not quite the same #user-report in #2736913-zen, which also lead to another, not-quite-related [Bug Report](https://github.com/godaddy-wordpress/coblocks/issues/1374) with CoBlocks directly.

**Comment by ockham** [comment] 2020-02-24 14:07
Possible duplicate of #39324?

**Comment by simison** [comment] 2020-02-27 13:20
cc @ramonjd

**Comment by p-jackson** [comment] 2020-02-27 22:17
> Possible duplicate of #39324?

Could be related, but if it was a duplicate then the bug would already be fixed on AT.

I'm not able to reproduce the issue in Chrome or Safari 😕 I'm trying to follow the same steps as in the gif but no luck, so I'm wondering if it has something to do with the theme. I'm using Maywood, do you remember what the theme in the gif was @jacoswan?

**Comment by jacoswan** [comment] 2020-02-28 08:07
@p-jackson I think the gif was recorded in Collective. I also tried it in Twenty Twenty, Maywood and Barnsbury again just now...

I can still recreate the issue, although it seems slightly different and inconsistent, as now Button 2 seems to work, but going back to Button 1 after editing Button 2 doesn't. Exiting and editing the editor seems to 'fix' it, only until you delete the block and add another.

**Comment by damiannep** [comment] 2020-02-28 14:24
Same thing happens to me using P2 theme - https://d.pr/v/dT3qva

It also happens on my personal site using Dyad-2 with only paragraph, quote and heading blocks on the page/post.

**Comment by roo2** [comment] 2020-04-01 00:05
I tried to reproduce this, I couldn't get the exact behavior but saw something strange in safari where the secondary button became selected instead of the primary one... it only happens once, afterwards if I try to select the different buttons it works as expected

 
![gif](https://user-images.githubusercontent.com/22446385/78086086-3c607d80-7400-11ea-8f5b-cbde5ca742f8.gif)

**Comment by roo2** [comment] 2020-04-01 00:19
Upgrading to coblocks 1.23.0 fixes the issue I was seeing

**Comment by WunderBart** [comment] 2020-08-26 13:37
Closing this one as it doesn't seem to be happening anymore after the recent update (https://github.com/Automattic/wp-calypso/issues/45033).

**Closed by WunderBart** 2020-08-26 13:37 UTC
Labels: Blocks, Editor, [Type] Bug
