### ISSUE TITLE
Headstart annotations are creating a bunch of “Attempt block recovery” errors in the editor when applied to a site.

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#57837] opened 2021-11-09 16:36 UTC
## Description
Using this ticket for Blogger Pod work accounting at the moment.   Not yet clear if Ganon  will dive in and fix the issues.  Please evolve this issue description as appropriate.

@alaczek reported [here](p1635979703466600-slack-C02A76B714Z) that headstart annotations are creating a bunch of “Attempt block recovery” errors in the editor when applied to a site.

A number of folks are currently helping out as shown in this slack thread. 
p1635985973066500-slack-CBTN58FTJ

**Comment by alaczek** [comment] 2021-11-09 21:52
Steps to replicate:
1. Activate Payton or Kerr theme on your test site/sandbox (these are not launched so do this from the command line) 
`wp theme activate pub/payton --url=[mytestsite].wordpress.com`
2. Run headstart on the site. For this either go to blog RC, or run this command: 
`wp headstart run --url=[mytestsite].wordpress.com --user=myusername`
3. Go to the site and edit the generated home page. There will be a bunch of "Attempt block recovery" errors on the page:

![image](https://user-images.githubusercontent.com/4550351/141010679-7d201026-746d-4244-8900-627c12074a73.png)

If you open up the console you'll find a bunch of Block validation errors there:
![image](https://user-images.githubusercontent.com/4550351/141010809-15df5232-94ce-4a8a-baa0-f802eaa94791.png)

These are the headstart files used:
* Kerr theme: https://wpcom-themes.trac.automattic.com/browser/kerr/inc/headstart/en.json
* Payton theme: https://wpcom-themes.trac.automattic.com/browser/payton/inc/headstart/en.json

**Comment by creativecoder** [comment] 2021-11-21 17:51
I encountered something very similar while user testing the FSE beta last week: the starter content for a new site has block errors on the homepage when opening the Site editor. Even though the block recovery works to restore the block content, this is a very bad first impression when setting up a new site.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/1699996/142773267-c6e97f19-ccfc-4453-8930-65157d59b3e7.png">

**Comment by p-jackson** [comment] 2021-11-29 02:32
The errors when using Payton have been fixed by D70425-code. Kerr still has an error in the subscribe button.

This:
<img width="1022" alt="Screenshot 2021-11-29 at 3 25 52 PM" src="https://user-images.githubusercontent.com/1500769/143799183-f6fad4cf-9727-4dba-b963-523c130e5cff.png">

Should look like this:
<img width="1022" alt="Screenshot 2021-11-29 at 3 26 27 PM" src="https://user-images.githubusercontent.com/1500769/143799228-8ff1c842-9fa7-40a1-b6ae-6a4023141903.png">

That's because after Headstart has run the block looks like this (some details elided):
```html
<!-- wp:jetpack/subscriptions {"submitButtonText":"u003cstrongu003eSUBSCRIBEu003c/strongu003e"} -->
<div>[jetpack_subscription_form submit_button_text="<strong>SUBSCRIBE</strong>"]</div>
<!-- /wp:jetpack/subscriptions -->
```

When it should really look like this, which includes extra slashes to escape the `<strong>` tags correctly:
```html
<!-- wp:jetpack/subscriptions {"submitButtonText":"\u003cstrongu003eSUBSCRIBE\u003c/strongu003e"} -->
<div>[jetpack_subscription_form submit_button_text="<strong>SUBSCRIBE</strong>"]</div>
<!-- /wp:jetpack/subscriptions -->
```

This appears to be an issue in the way that Headstart is applying the annotation to the site (the annotation contains the slashes, but they aren't being applied to the site correctly), however we could also fix this by removing the `<strong>` style from this subscribe button and regenerating the annotations, which I think would be faster. The `<strong>` isn't needed because with or without it, the button label always appears with a font weight of `700` due to styles in `theme.json`. @alaczek

**Comment by p-jackson** [comment] 2021-11-29 02:39
> I encountered something very similar while user testing the FSE beta last week

D70425-code has been deployed which hopefully fixed this? I tested a new FSE site created with Quadrat, opened `/site-editor` and didn't see any validation errors. But I never tested or reproduced the issue. @creativecoder could you re-test now that D70425-code has been deployed?

**Comment by p-jackson** [comment] 2021-11-29 23:02
@alaczek has updated the Kerr annotation to remove the `<strong>` in the button label. This has fixed the last block validation error 👍

**Closed as completed by p-jackson** 2021-11-29 23:02 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] High, [Feature] Headstart, Blocks
