### ISSUE TITLE
Import: Progress visual issue after hitting start

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#3021] opened 2016-02-03 00:32 UTC
After uploading an import file, and then hitting the start import button, I was presented with this:

<img width="774" alt="screen shot 2016-02-02 at 4 29 14 pm" src="https://cloud.githubusercontent.com/assets/1464705/12769174/723553a2-c9ca-11e5-9ab6-38b97cdeed33.png">

It was unexpected since it has another redundant start button, and a strange line. I expected it to just start the import and for me to see the progress bar.

**Comment by dmsnell** [comment] 2016-02-03 06:07
That's strange @apeatling - it should show author mappings in there. Can you share the WXR for the test?

**Comment by apeatling** [comment] 2016-02-03 17:44
This is in your branch: `update/importer/report-progress` and using the theme test export file available here: https://codex.wordpress.org/Theme_Unit_Test (link to file is in step one on that page)

**Comment by dmsnell** [comment] 2016-02-03 21:34
The reason this looks funny is that the server doesn't return any authors for the mapping in this import file. It _does_ report a successful upload, which makes me believe that were weren't any issues understanding the file, but something must be messed up in parsing and extracting the author list, because they are clearly there in the WXR.

**Comment by roccotripaldi** [comment] 2016-02-09 03:40
This is related to #2031.  I think if we can add API support both `author` and `wp_author` when parsing the XML, we'll close both issues. I'll look into this.

**Comment by roccotripaldi** [comment] 2016-02-10 02:47
TBH, i've never seen `wp_author` used in an import file outside of the Theme Unit Test. Perhaps we should just patch that file to use `author` instead.

But the API should return an error if it cannot parse authors, and i've thrown together a diff at mcpb-1140b

**Comment by dmsnell** [comment] 2016-02-12 21:19
Closing because this is a duplicate of #2031 and also because we should now be throwing an error before getting to this screen if there are no authors available.

**Closed by dmsnell** 2016-02-12 21:19 UTC
Labels: Import, [Type] Bug
