### ISSUE TITLE
Editor: Scroll effect after switching between HTML/Visual on mobile or tablet

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#22761] opened 2018-02-23 15:16 UTC
#### Steps to reproduce

1. Log into WordPress.com in a mobile or tablet device.
2. Starting at URL: https://wordpress.com/post/
3. Enter some text into your new post.
4. Switch from the "Visual" (default) tab to the "HTML" tab. 

#### What I expected

I expected for the screen to stay at the same position, and not to scroll.

#### What happened instead

The screen scrolls down, and you need to scroll back up to see the text you entered at the beginning of the editor.

#### Browser / OS version

Chrome / Android 8.1.0

#### Screenshot / Video

Video here: https://cloudup.com/cs970pqebZm

#### Context / Source

#user-report #painpoint 

Internal reference: 263150-h

**Comment by rachelmcr** [comment] 2018-02-23 17:15
Your video looks like it's a webview within the WordPress app. Did you also observe the same behavior in a mobile browser, separate from the app?

If it's only an issue in the app I think the best solution would be something like https://github.com/Automattic/wp-calypso/issues/13532 to prevent app users from accessing Calypso in app webviews unexpectedly.

**Comment by SiobhyB** [comment] 2018-02-23 17:20
@rachelmcr: You're right, the video was sent to us from the Android Developer Support Team, while they were testing the app. I tested while logged in a browser directly on my Pixel and can confirm it's an issue separate from the app too.

**Comment by rachelmcr** [comment] 2018-02-23 17:35
Thanks! I just realized I've seen this before — I'm going to close this issue as a duplicate of https://github.com/Automattic/wp-calypso/issues/17914.

**Closed by rachelmcr** 2018-02-23 17:35 UTC
Labels: Editor, [Type] Bug
