### ISSUE TITLE
List block: issue removing first items

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#31413] opened 2019-03-12 20:41 UTC
#### Steps to reproduce
1. Create a new post
2. Add a List block
3. Add different list items
4. Select the first ones and delete it

#### What I expected
To delete just the items I selected.

#### What happened instead
No content is removed and each item in the List block is turned into a Paragraph block.

#### Screenshot / Video
When I select a couple list items and hit Backspace this happens:

![GutenLists](https://user-images.githubusercontent.com/16104522/54234372-bf5d2000-44ed-11e9-8bde-d8c4ac12f9c3.gif)

This happens if you select all the list items too, making very confusing to delete the whole block.

**Comment by codebykat** [comment] 2019-03-12 22:16
I can't reproduce this in either Gutenframe or core Gutenberg. @carinapilar What OS/browser?

**Comment by carinapilar** [comment] 2019-03-12 23:12
@codebykat it's OS X 10.13.6, Chrome Version 73.0.3683.75. It's in this page here: https://gutenofficehour.wordpress.com/2019/03/12/guten-lists.

**Comment by patrickmelville** [comment] 2019-03-21 03:58
I saw the same in Win10, Chrome Version 72.0.3626.121 with calypso and and WordPress5.1.1 (both running locally)
I am still familiarizing myself with calypso but I couldn't find code referencing the core/list block other than mentioning it in the devdocs. Would this be an issue solved in the core Gutenberg repo?

**Comment by arunsathiya** [comment] 2019-04-05 06:58
I am able to reproduce this as well, only when the list block has a block above it. Anyway, this is core-specific issue and has been logged here https://github.com/WordPress/gutenberg/issues/8803

I am closing this in favor of the core issue. @codebykat, hope that's correct. If your team needs to reopen, please feel free to.

**Closed by arunsathiya** 2019-04-05 06:58 UTC
Labels: Gutenberg core, [Goal] Gutenberg, [Pri] Normal, [Type] Bug
