### ISSUE TITLE
Editor: contextual menu occasionally appears above preview

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1815] opened 2015-12-18 14:59 UTC
Raised by @melchoyce 

<img width="1339" alt="screen shot 2015-11-13 at 9 54 42 pm" src="https://cloud.githubusercontent.com/assets/2846578/11161722/ffb1d708-8a52-11e5-9b43-dbc95420929c.png">

What I did: click on image to get contextual image menu, then click the "preview" button
What happened: the contextual menu appeared on top of the preview

I wasn't able to replicate it more than once, though. 

Running latest Chrome on Mac 10.10.5.

Note from @timmyc 

> Wondering if we need to unfocus tinymce when the preview button is clicked to fix all of these bleed issues.

**Comment by nylen** [comment] 2016-01-15 02:10
Closed by mistake.  It seems likely that this is still an issue, and that it's the same issue as #1486.  I can't get this to happen reliably, but sometimes the editor does not receive a `blur` event that would [hide the toolbar](https://github.com/Automattic/wp-calypso/blob/c540110/client/components/tinymce/plugins/wpcom/plugin.js#L629).

**Comment by brbrr** [comment] 2017-12-29 06:46
I was unable to reproduce it. Closing as no longer valid.

**Closed by brbrr** 2017-12-29 06:46 UTC
Labels: Editor, [Type] Bug
