### ISSUE TITLE
Featured Image width is not constrained on mobile - Stratford theme

### ISSUE THREAD

**Issue by cintacks** [Automattic/wp-calypso#77466] opened 2023-05-28 10:10 UTC
### Quick summary

User is reporting featured image on mobile (specifically Android) is not resizing to container width

### Steps to reproduce

1. Open https://brainkers.org/2023/05/23/reflejo-de-inmersion-en-mamiferos-interrogantes-a-una-respuesta-fisiologica-parte-1/ on Android device 

I couldn't successfully replicate with Chrome emulation

### What you expected to happen

Featured Image should be constrained to container width

### What actually happened

Image is being blown out of proportion: https://shottr.cc/s/7e5c/SCR-20230528-g3p.png

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

I added a temporary CSS add-on to help them mitigate this while it's being checked. CSS is: 

```
@media screen and (max-width: 800px) {
	figure.post-thumbnail img {
		max-width: 100%;
	}
}
```

**Comment by cintacks** [comment] 2023-05-28 10:48
I just saw this also happen on Shawburn on this ticket: 6327616-zd-woothemes

CSS applied: 

```
.post-thumbnail img {
    max-width: 100%;
}
```

**Comment by cuemarie** [comment] 2023-05-30 18:00
Duplicate of: https://github.com/Automattic/wp-calypso/issues/77561

📌 ACTIONS
- Closing as duplicate

**Closed as not planned by cuemarie** 2023-05-30 18:00 UTC
Labels: Bug, [Pri] Low, [Platform] Simple

**Comment by cuemarie** [comment] 2023-05-31 20:40
A [fix has been deployed](https://github.com/Automattic/wp-calypso/issues/77561#issuecomment-1570917159)

**Comment by cuemarie** [comment] 2023-05-31 21:57
A batch user reply will be sent out to all interactions noted above this comment. Please refer to main issue https://github.com/Automattic/wp-calypso/issues/77561 for updates on that process.
