### ISSUE TITLE
[Bug]: Blank Canvas theme card looks "broken" in Safari

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#72047] opened 2023-01-13 07:56 UTC
### Quick summary

In the theme showcase, Blank Canvas card in the grid looks like it's missing image thumbnail in Safari.

@Automattic/lego 

### Steps to reproduce

1. Use Safari
2. Open the theme showcase (`/themes`)
3. Scroll / search for the Blank Canvas theme

### What you expected to happen

It should look like this:

|Inactive|Active|
|-|-|
|<img alt="image" src="https://user-images.githubusercontent.com/1525580/212267492-6c9d6abc-890f-42a6-99fd-555adcdb45e4.png">|<img  alt="image" src="https://user-images.githubusercontent.com/1525580/212267393-70d46df2-3713-4146-a30b-dddd9f1fba14.png">|

### What actually happened

It looks like this instead in Safari:

|Inactive|Active|
|-|-|
|<img alt="image" src="https://user-images.githubusercontent.com/1525580/212267639-312835bc-2e66-4e2c-bb10-8b57ee6f5fee.png">|<img  alt="image" src="https://user-images.githubusercontent.com/1525580/212267692-d198a86d-7210-4ea4-a8f3-f3dbd76a1c08.png">|

### Browser

Apple Safari

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment] 2023-04-12 19:03
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on DotCom – Replicated
- Replicable outside of DotCom - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described.  The height of the Blank Canvas theme preview in the showcase is also different than the other themes.

**Screenshots/Recordings**

![Markup on 2023-04-12 at 11:54:44](https://user-images.githubusercontent.com/27249804/231557743-35b8712f-a94c-4954-884a-e193dfa7b1a3.png)

📌 ACTIONS
- Assigned to Lego

**Comment by arthur791004** [comment] 2023-04-18 06:11
@cuemarie What's the version of your Safari? I tested with Safari 16.3 (18614.4.6.1.6) and it looks good 🤔

![image](https://user-images.githubusercontent.com/13596067/232686703-b938fabc-4c46-4ba1-bac6-234226b438bb.png)

**Comment by cuemarie** [comment] 2023-04-19 20:08
@arthur791004 Apologies for not including those details!  Looks like I am behind you - currently on Version 16.2 (17614.3.7.1.7, 17614) where the problem occurs.  Let me get that updated and I'll test again!

**Comment by arthur791004** [comment] 2023-04-21 08:42
@cuemarie Looks like you're not able to access the screenshot image. Could you check whether there is any error on your console?

Also, if you open this URL of the screenshot image directly, are you able to access it?
https://i0.wp.com/s2.wp.com/wp-content/themes/pub/blank-canvas-3/screenshot.png?fit=479%2C360

Thank you!

**Comment by okmttdhr** [comment] 2023-05-02 04:38
Some of us could not reproduce this issue. 📝 
p1682061528484859-slack-CRWCHQGUB

**Comment by cuemarie** [comment] 2023-05-02 21:36
Hey folks! Apologies for my delay here - a bit of AFK last week delayed my testing this again.

With Safari updated, now on `Version 16.4 (18615.1.26.11.23)`, the issue does not present for me anymore.  Additionally, I'm able to access the screenshot @arthur791004 shared!

With that in mind, I'll close this out!

**Closed as completed by cuemarie** 2023-05-02 21:36 UTC
Labels: Bug, [Pri] Normal, Triaged, [Closed] Not Reproducible, [Feature] Theme Showcase, [Browser] Safari

**Comment by arthur791004** [comment] 2023-05-03 03:25
Thanks for the update 🎉
