### ISSUE TITLE
Revelar: Image block missing bottom margin

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#70218] opened 2022-11-20 23:13 UTC
### Quick summary

When you add an Image block to a post or page while using the Revelar theme, the theme doesn't add a bottom margin to the Image block, making the next block be too close to the image.

### Steps to reproduce

1. Set your site's theme to Revelar
2. Create a new post or page
3. Add an Image block to that post or page, and follow it up with text

### What you expected to happen

There would be spacing between the blocks

### What actually happened

There isn't:

![Uploading image.png…]()

### Context

#5723215-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Revelar

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Can be resolved with CSS:

```
/* fix margin beneath image blocks | XXXXXX-hc/zen eD */
.wp-block-image figure {
    margin-bottom: 1.3125em;
}
```

**Comment by kavyagokul** [comment] 2022-11-22 14:44
📌 SCRUBBING : RESULT
- Tested on P2 - Uncertain
- Tested on Simple - Replicated 
- Tested on AT - Replicated 
- Tested on Self-hosted - Replicated
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
This is a known reported issue with a number of classic themes

📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/themes/issues/6197

**Closed as completed by kavyagokul** 2022-11-22 14:44 UTC
Labels: Bug, [Pri] Low, [Platform] Simple, [Platform] Atomic
