### ISSUE TITLE
Gutenboarding: ensure there's always free domain suggestion

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40967] opened 2020-04-09 13:49 UTC
In [Gutenboarding](https://wpcalypso.wordpress.com/new/) we rely _always_  having free domain available.

I've gotten the impression that we might not always get a free `.wordpress.com` domain suggestion in API response, depending on the search query? @ockham @sirreal can you confirm?

We've looked into `generate_multiple_wpcom_suggestions()` at the API.

Related API Query:

https://github.com/Automattic/wp-calypso/blob/58442f38b9682f90c2822458b213e552155a42d3/packages/data-stores/src/domain-suggestions/selectors.ts#L75-L86

We might need to ensure we use API correctly, too: https://github.com/Automattic/wp-calypso/issues/40164

**Comment by sirreal** [comment] 2020-04-20 09:42
> I've gotten the impression that we might not always get a free .wordpress.com domain suggestion in API response, depending on the search query? @ockham @sirreal can you confirm?

In my testing, I've noticed that `include_wordpressdotcom` and `only_wordpressdotcom` often gave unexpected results.

- `v1.1/domains/suggestions?query=food&quantity=1&include_wordpressdotcom=1` -> returns 1 result, apparently it's the WordPress.com subdomain. It seems odd that this would be the most reliable way to get a WordPress.com subdomain result.
- `v1.1/domains/suggestions?query=food&only_wordpressdotcom=1` -> 404. Is there a way to ensure we get a result? It's not apparent at https://developer.wordpress.com/

**Comment by ramonjd** [comment] 2020-05-01 01:53
> v1.1/domains/suggestions?query=food&only_wordpressdotcom=1 -> 404. Is there a way to ensure we get a result? It's not apparent at https://developer.wordpress.com/

Looks like the query must be a unique `.wordpress.com` subdomain to return anything. I'm not sure why, but in practice, it's just doing a "is this domain available" check. 🤣 

E.g., domains/suggestions?query=fooddsfdsfsdf&only_wordpressdotcom=true

I might dig deeper later tonight.

**Comment by klimeryk** [comment] 2021-02-10 11:45
I'm pretty sure this has been fixed with some improvements on the backend. I've tried reproducing the issue, but was not able to. The API request looks good too. I'm going to close the issue, but feel free to re-open if it can be reproduced. Happy to help with tweaking the API call or backend logic if that's the case 🙇

**Closed by klimeryk** 2021-02-10 11:45 UTC
Labels: Domains, [Goal] New Onboarding, [Type] Question

**Comment by klimeryk** [comment] 2021-02-10 15:40
Noting that I was able to reproduce this thanks to steps from https://github.com/Automattic/wp-calypso/issues/46752. Basically, search for a digit/number-only query like `12390812391`. There will be no WPCOM suggestion... or there will be a random .blog subdomain 😓 However, I'll keep this one closed and investigate further in https://github.com/Automattic/wp-calypso/issues/46752, as the root issue should be the same.
