### ISSUE TITLE
sharing buttons shows empty

### ISSUE THREAD

**Issue by ttcath** [Automattic/wp-calypso#84319] opened 2023-11-18 13:49 UTC
### Quick summary

 https://wordpress.com/marketing/sharing-buttons/ttcath.org
once I enter this page, it shows empty.

### Steps to reproduce

1. login the account
2. go to the setting and find the tool
3. choose marketing menu, and sharing buttons tab

### What you expected to happen

The setting for the sharing buttons tab must be work

### What actually happened

The setting for the sharing buttons tab shows empty, even I use vpn for it, it still shows empty

![1700314175877](https://github.com/Automattic/wp-calypso/assets/60735821/6dbbe2f6-3363-41ff-8cff-aa4c8b26226f)

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by ttcath** [comment] 2023-11-18 17:09
I also upload the screenshots by which Chrome Developer tools reports:

![1700327169521](https://github.com/Automattic/wp-calypso/assets/60735821/5fb80c62-821e-4da2-b439-eba20948b30a)

**Comment by ttcath** [comment] 2023-11-19 11:11
For the screen video on reproduce this issue, and the logs, please download from here:

Video on reproduce this issue: https://ttcath.files.wordpress.com/2023/11/20231119_185924.mp4
logs on the error by using Lastest Version of Chorme:  https://ttcath.files.wordpress.com/2023/11/20231119_190252.mp4

**Comment by suyogyashukla** [comment] 2023-11-29 10:06
@ttcath Hi! This repo is primarily used for bug reports, and your issue is not a bug but rather a case of blocks put in place by your ISP/Government authority. We're continuing to help you out with this on our support thread, so I'm closing this. Let's keep the conversation going over on email.

7327208-zd-a8c

**Closed as completed by suyogyashukla** 2023-11-29 10:06 UTC
Labels: Bug, [Pri] High, Needs triage, Customer report [LEGACY], [Status] Priority Review Triggered
