### ISSUE TITLE
Food menus: Calypso not showing list of published items

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#15234] opened 2017-06-19 02:55 UTC
When opening the food menus tab on a site that already has some existing menu items, an empty loading state is displayed instead of the list of items.

#### Steps to reproduce
1. Activate a theme that supports Food Menus, for example Canape or Confit.
2. Add some menu items.
3. Click on the "Food Menus" tab in Calypso.
4. Result - an empty loading state. **This means that it's not possible to edit or delete menu items.**

![food_menus_bug](https://user-images.githubusercontent.com/4550351/27267752-1552d85c-54ee-11e7-8d5d-b86c06c852ad.gif)

#### What I expected
To see the list of all existing menu items.

The site I tested on has a number of menu items previously added through wp-admin interface, but none showed on the list either.

**Comment by gracie** [comment] 2017-07-06 22:42
I came across this issue, and I found some differences between WordPress.com Simple and Atomic sites:

I can still publish a Food menu item in Calypso from a WordPress.com Simple site, even though it won't show the published items in the dashboard.

However, I'm unable to publish anything in this module on an Atomic site. Instead, I receive this error message:
`Publishing of Post Failed`

**Comment by amylaneio** [comment] 2017-10-06 16:05
I had another user report this issue in #680482-hc. It's a wpcom simple site on the business plan. We could access the Food Menu CPT in WP Admin, but not in Calypso. I was able to confirm this on a test site, too.

**Comment by kathrynwp** [comment] 2017-11-06 14:35
Another report here: 
https://en.forums.wordpress.com/topic/food-menus-not-showing-up

**Comment by lizthefair** [comment] 2017-12-12 21:40
Another report here:  https://mc.a8c.com/support-stats/happychat/transcript.php?id=1273636  The theme was APPETITE.  It's a WordPress.com Simple site.  The behavior was the same as Gracie described for simple sites above.

**Comment by scosgro** [comment] 2017-12-22 01:11
User came to chat today with this issue as well. Appetite menus show up in WP-Admin, but their Calypso menu section is empty. Business Plan - Not AT.

Domain: thnbarandgrill.com
SA: https://wordpress.com/wp-admin/network/wpcom-paid-upgrades.php?action=search&username=thnbarandgrill 
Username: thnbarandgrill

**Comment by jerrysarcastic** [comment] 2018-01-16 01:44
Also reported in #1533695-hc on a wpcom Simple site

Domain: https://ateliervermeer.ca/
Username:  ateliervermeer
Theme:  Aperitive

**Comment by juliasydnor** [comment] 2018-03-01 10:12
Another report on a Simple site using Restaurant: 1885148-hc
royalindiabelgium.com

I was able to reproduce on a test site.

Food Menus are shown as published, but are not accessible from Calypso. They can only be viewed and edited from WP Admin. https://cloudup.com/cNuTXRmOGwz

**Comment by eurello** [comment] 2018-03-09 20:25
Also reported in #1692803-hc
Follow up in #1007086-zen

Site (simple site, Aperitive theme): https://courtclubitalia.com/

**Comment by rantoncuadrado** [comment] 2018-04-27 07:02
Also reported in #1121201-zen
Possibly related to https://github.com/Automattic/wp-calypso/issues/14442

**Comment by alaczek** [comment] 2018-05-15 02:38
Another report, moved from https://github.com/Automattic/themes/issues/126

User report: #1822654-hc
Follow-up ticket: #1148472-zen
User's site: http://thefodband.wordpress.com

**Comment by msilbers** [comment] 2018-05-16 16:12
issue reported in #1227313-hc as well, nothing appears on Calypso for Food Menus but they have quite a bit set up (on the Premium plan)

**Comment by brookewp** [comment] 2018-08-02 21:43
Another user (christonite) reported they can't see the food menu they created with canape theme here: #5442926-hc
Site: foodbyami.wordpress.com

**Comment by chantalcoolsma** [comment] 2018-08-20 13:31
Another user (trattoria4mori) reported not seeing Food menu on Canape theme. Seemed to work using wp-admin.

Site: http://trattoria4mori.de
#53886-hc

**Comment by desnum** [comment] 2018-10-30 16:48
Another user in chat reported in not seeing posts she created in the Food Menu using the "Aperitive" theme. The posts show up on the frontend, but are missing from the Food Menus tab.

**Plan:** Premium
**Theme:** Aperitive
**Site:** chezmorasse.ca
**Follow up ticket:** https://woothemes.zendesk.com/agent/tickets/1530460

<img width="1257" alt="screen shot 2018-10-30 at 12 37 53 pm" src="https://user-images.githubusercontent.com/43796228/47734561-e9016300-dc40-11e8-9b80-cad6640319e1.png">

However, when I attempted to replicate on my AT site (Activate Aperitive, Add new item under Food Menu, go back to Food Menus) I was able to see my post:

<img width="1214" alt="screen shot 2018-10-30 at 12 46 19 pm" src="https://user-images.githubusercontent.com/43796228/47735046-05ea6600-dc42-11e8-9775-ad97e4b9c32d.png">

**Comment by xpurichan** [comment] 2019-01-24 16:42
Another report on 1741817-Zen using the Canape (Canapé) theme.

**Comment by ivan-ottinger** [comment] 2019-02-17 14:52
Another report: 1808810-zen - Canape theme.

**Comment by donalirl** [comment] 2019-03-06 05:50
This came up in #10930868-hc on the Restaurant theme:

1. Initially, clicking Food Menu → Add in Calypso loaded a completely blank screen at the URL https://wordpress.com/block-editor/edit/nova_menu_item/ but this seems to have resolved itself now. Clicking Add loads the menu item editor in WP Admin.
2. Can successfully add a food menu item in WP Admin, but it does not show in Calypso Food Menus. Shows this even though items have been created:
![food menu calypso](https://cld.wthms.co/ecdUgD+) 
3. Food menus shows up under _Feedback_ in a calypsofied version on WP Admin: 
![feedback](https://cld.wthms.co/GP0wls+) 

Is #3 related or would it be best to open up a separate issue for that?

**Comment by kathrynwp** [comment] 2019-03-24 19:47
Came across this in 1903280-zen with Aperitive.

User has several food-menu items added, but none is showing in Calypso. They are present in WP Admin.

**Comment by lancewillett** [comment] 2019-04-09 01:50
This could be a good candidate for Calypsoify where the link is present in Calypso UI but when clicked loads the WP Admin view with Calypso CSS applied to it.

**Comment by lancewillett** [comment] 2019-04-09 01:54
Changed from Bug to Enhancement since the content is accessible but it'd be even better to improve the flow so customers can edit and view all the CPTs as expected.

**Comment by carinapilar** [comment] 2019-04-09 13:07
Got a user with the same situation on #2879730-hc. When troubleshooting I replicated the same situation Donal explains [above](https://github.com/Automattic/wp-calypso/issues/15234#issuecomment-469977979).

**Comment by donalirl** [comment] 2019-04-23 01:44
Another case in #4373898-hc. The fact that Calypso says `No Menu Items found` even though the items are present, makes it seem like a bug to me. It's confusing for users who don't know to check WP Admin. It would be great to get this fixed.

**Comment by cecoates** [comment] 2019-05-19 17:28
> Came across this in [1903280-zen](https://href.li/?https://automattic.zendesk.com/agent/tickets/1903280) with Aperitive.
> 
> User has several food-menu items added, but none is showing in Calypso. They are present in WP Admin.

Similar case here:

2042243-zen

Also with Aperitive.

**Comment by kosiew** [comment] 2019-07-12 09:29
#2173184-zen
Theme: Canape

**Comment by jsnajdr** [comment] 2019-07-30 15:30
This is a bug in the Jetpack/WP.com REST endpoints that list posts or fetch post counts for a particular CPT (`nova_menu_item` in case of Canape. That CPT is defined in the theme and the endpoint needs to do a call to
```php
$this->load_theme_functions();
```
to define the CPT. Some endpoints do it, some don't.

**Comment by jsnajdr** [comment] 2019-07-31 11:01
Fixing in D31026-code.

**Comment by lancewillett** [comment] 2019-08-07 03:16
@donpark Could you please take a look at the Phabricator patch from Jarda?

**Comment by donpark** [comment] 2019-08-07 04:24
Reviewed and accepted @jsnajdr's patch with which Food Menus side menu now display food menu items.

Sidenote: This is unrelated to the patch nor this issue but I'm seeing `X-Frame-Options` related page crash when browser **redirects to** https://wordpress.com/block-editor/edit/nova_menu_item/{site_slug}/{post_id} after creating or updating a Food menu item. 

Refreshing the crashed page loads the wp-admin Edit Menu Item page.
Pressing Update on the page again crashes the page.

<img width="786" alt="screenshot_835" src="https://user-images.githubusercontent.com/127594/62594705-6b821780-b890-11e9-9e6a-8cce64e4eb74.png">

Haven't dug into it yet.

**Comment by jsnajdr** [comment] 2019-08-12 07:48
D31026-code was deployed a moment ago. [Jetpack PR](https://github.com/Automattic/jetpack/pull/13213) to sync the changes to Jetpack/Atomic is open (not yet merged).

**Closed** 2019-08-15 06:51 UTC
Labels: Custom Post Types (CPT), [Type] Enhancement
