### ISSUE TITLE
Extensions Purchased from the Marketplace Don't Have "Installed" Label (On the eCommerce plan)

### ISSUE THREAD

**Issue by jorpdesigns** [Automattic/wp-calypso#60137] opened 2022-01-17 16:25 UTC
### Quick summary

After a user purchases an extension from the marketplace, the extension appears on their marketplace with pricing still included instead of an "Installed" label.

This only happens on the eCommerce plan.

### Steps to reproduce

1. **Upgrade a new site to ecom plan**
2. Navigate to the Marketplace and purchase the WooCommerce Subscriptions extension (or any other extension, I only tested with WooCommerce Subscriptions).
3. After plugin has been installed, navigate back to the Marketplace. 

### What you expected to happen

The recently purchased extension should display an "Installed" label.

### What actually happened

The recently purchased extension displays pricing information, as if it is yet to be purchased.

### Context

Reported in 30321500-hc

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

There is no user impact

### Workaround details

It doesn't really matter as the extension is still installed and active.

**Comment by cpapazoglou** [comment] 2022-01-18 10:38
> After plugin has been installed, navigate back to the Marketplace.

Can you clarify how you navigated back to the Marketplace?

**Comment by jorpdesigns** [comment] 2022-01-18 11:05
> > After plugin has been installed, navigate back to the Marketplace.
> 
> Can you clarify how you navigated back to the Marketplace?

I clicked on **Plugins** in the menu - https://wordpress.com/plugins/

**Comment by cpapazoglou** [comment] 2022-01-18 12:48
After checking out you should have landed to the thank you page
![SS 2022-01-18 at 14 43 38](https://user-images.githubusercontent.com/12430020/149939657-6f4cd70f-85c6-4579-bcee-b265392d65fa.gif)

- Did you click "X" or "Explore Plugins"? 
- Is there a chance that you navigated to **Plugins** from another tab?

Sorry for following up with questions, it is just that I cannot reproduce it. It seems like an edge case and any little piece of info would be very valuable.

**Comment by jorpdesigns** [comment] 2022-01-18 13:58
Looks like I explained this wrong, my bad.

Here's a screenshot of my installed plugins: 

<img width="1260" alt="marketplace1" src="https://user-images.githubusercontent.com/40006288/149950687-6178e61d-3afd-49b6-b5c9-08b2a69aceb9.png">

You will see that Woo Subscriptions is currently installed and active.

However, when you open the Plugins page, you see that Woo Subscriptions still shows pricing instead of the "Installed" label:

<img width="1610" alt="marketplace2" src="https://user-images.githubusercontent.com/40006288/149950748-b1cfb73c-b100-47ec-8db8-f9201cf313aa.png">

Here's what it should look like (as seen on the Business plan):

<img width="1205" alt="marketplace3" src="https://user-images.githubusercontent.com/40006288/149950915-e89e992a-41e9-4395-99b0-73ddb563477f.png">

**Comment by cpapazoglou** [comment] 2022-01-18 14:02
Thanks for following up, that makes more sense now! I suspect that this is a site - not plan - related problem. Can you confirm:

- the same happens with any of your free plugins - they don't show as installed but show "Free"
- your Jetpack connection is broken? in which case we already have an issue https://github.com/Automattic/wp-calypso/issues/59943

**Comment by cpapazoglou** [comment] 2022-01-18 14:07
nvm, I just used the su to your ecom site and I can see the bug which doesn't relate to a "Jetpack broken connection"

**Comment by cpapazoglou** [comment] 2022-01-18 14:23
While I can't reproduce it on my "old" ecom site, I could reproduce it to a new ecom site.

**Comment by cpapazoglou** [comment] 2022-01-18 14:26
It seems like the api response for `https://public-api.wordpress.com/rest/v1.1/sites/[SITE_ID]/plugins?http_envelope=1`
contains invalid slugs 
![SS 2022-01-18 at 16 24 37](https://user-images.githubusercontent.com/12430020/149955573-461bd79e-3bfa-4ed7-85ff-6c9d883981ed.png)
`woocommerce-com-shipment-tracking` instead of `woocommerce-shipment-tracking` and I can't reproduce that to my old ecom site.

**Comment by kerrynicl** [comment] 2022-01-18 14:27
I was just able to replicate on my ecom site as well

**Comment by cpapazoglou** [comment] 2022-01-18 14:35
Indeed, the problem is plan specific. Downgrading my ecom site to free and then upgrading to biz while also triggering an Atomic transfer results in all slugs of previously bought plugins to report correctly without the `-com-` interference.

**Comment by cpapazoglou** [comment] 2022-01-18 14:49
I am getting mixed results. 

- Downgraded again to free
- Removed all subs
- Upgraded to ecom
- Bought "WooCommerce Subscriptions"
- Plugin slug seems ok
<img width="1594" alt="SS 2022-01-18 at 16 48 11" src="https://user-images.githubusercontent.com/12430020/149959791-c6b18557-f589-4bfc-8941-02da07615fe2.png">

Can't identify yet what triggers this edge case with slugs containing `-com`

**Comment by gavande1** [comment] 2022-01-23 04:20
The issue has been discussed here: p9o2xV-1Of-p2

**Comment by cpapazoglou** [comment] 2022-01-25 09:55
On the meantime we probably should add a fallback slug with `woocommerce-com` prepended to check against the installed plugins.

p9o2xV-1Of-p2#comment-5500

**Closed as completed** 2022-02-01 03:09 UTC
Labels: Bug, [Pri] High, [Status] In Progress, [Feature] Plugins, Plans: eCommerce, Triaged, Marketplace
