### ISSUE TITLE
Plugins: manage page sometimes does not display

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#17815] opened 2017-09-05 18:36 UTC
#### Steps to reproduce
1. For a non-Jetpack site, visit URL: `/plugins/[siteid]`
2. Click "Switch Site" in the sidebar and change to "All sites".
3. Click "Manage" button in sidebar next to "Plugins".

#### What I expected

To see the Plugins management page.

#### What happened instead

Still on Plugins "browse" page, although the URL correctly changes to `/plugins/manage` and the header changes. Clicking the "Add plugin" and "Manage plugins" buttons in the header toggles the routes and the header, but not the page contents.

A page refresh when on the `/plugins/manage` route "fixes" the UI.

<img width="593" alt="screen shot 2017-09-05 at 5 00 44 pm" src="https://user-images.githubusercontent.com/2036909/30083279-dc423ef8-925b-11e7-99aa-40e97b7e5b3e.png">

<img width="586" alt="screen shot 2017-09-05 at 5 01 08 pm" src="https://user-images.githubusercontent.com/2036909/30083283-defc958a-925b-11e7-8530-0859b58f6c9e.png">

**Comment by sirbrillig** [comment] 2017-09-05 18:55
The issue seems to be that `props.plugins` is empty in `PluginsMain` when switching from a Simple site to multi-site view and it doesn't get fetched. Then `renderPluginsContent()` does not show `PluginsList`.

**Comment by sirbrillig** [comment] 2017-09-06 00:06
I started trying to fix this in #17824 by adding a Query component, but it doesn't seem to work. This may just be my inexperience with Query components, however.

**Comment by jsnajdr** [comment] 2017-09-06 11:29
This is caused by a bug in interaction between the sites list in the Flux store (lib/sites-list) and the one in Redux store.

**What happens?**
When showing a `/plugins/manage` or a `/plugins/:plugin` page, we use `sites.getSelectedOrAllWithPlugins()` to get a list of sites relevant for this page.

If a site is selected (i.e., we are on a route with `:site` suffix), this list has just one item. If no site is selected, this list contains all Jetpack sites.

Then we retrieve the list of plugins relevant to this list of sites:
```js
PluginsStore.getPlugins( sites );
```
It's either a list for one site, or for all sites.

Then we render this list. It comes in two variants, for single site (with activation toggles etc) or for all sites (with the site count shown).

Now, when we have a site selected, and in the site selector, we switch to "All Sites", there is a bug that causes that the Redux store's "selected site" is changed to `null`, but the "selected site" in Flux store remains non-`null`. The stores are out of sync!

`sites.getSelectedOrAllWithPlugins()` then returns the wrong list. Instead of the list for all sites, it returns the list for the last selected site. If it was a Simple site, there are no plugins, hence empty list. If it was a Jetpack site, the "all sites" list displays info for that one Jetpack site, not for all.

All places that use `getSelectedOrAllWithPlugins()` are affected: list of installed plugins, info page about a single plugin, disconnect-jetpack page...

Fixed in #17846.

**Closed** 2017-09-07 07:56 UTC
Labels: Plugins, [Type] Bug
