### ISSUE TITLE
Mailchimp Block: Doesn't respect Double Opt-In settings.

### ISSUE THREAD

**Issue by chaitanyamsv** [Automattic/wp-calypso#40730] opened 2020-04-02 23:30 UTC
#### Steps to reproduce

1. Create a Mailchimp campaign with [Double Opt-In](https://mailchimp.com/help/about-double-opt-in/) enabled.
2. Add a Mailchimp block [to a post ](https://chaittestpress.com/2020/04/03/mailchimp-opt-in-test/).
3. Add the email address on the block and click `JOIN MY EMAIL LIST` button.

#### What I expected

The block should display the double opt-in message similar to the one shown in this screenshot of the popup form: https://d.pr/i/glDusn

#### What happened instead

The block ignores opt-in and says `Success! You're on the list.`

In the Mailchimp account, the email address is shown as `Subscribed` as shown in this screenshot:  https://d.pr/i/6ZCxIk

User report: 2831620-zen

**Comment by kristarella** [comment] 2020-04-03 05:21
Duplicate of https://github.com/Automattic/jetpack/issues/14828

**Comment by lancewillett** [comment] 2020-04-04 19:24
Closing in favor of Jetpack issue.

**Closed by lancewillett** 2020-04-04 19:24 UTC
Labels: Mailchimp, [Type] Bug
