### ISSUE TITLE
Email forwarding: POST 500 error for subdomains

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#15601] opened 2017-06-28 08:29 UTC
When trying to add email forwarding to a subdomain, you'll get this non-user friendly error:

`500 status code for "POST /domains/my.subdomain.com/email/new"`

#### Steps to reproduce assuming you have a subdomain

1. Go to https://wordpress.com/domains/manage/my.subdomain.com/email-forwarding/my.subdomain.com
2. Enter the required information to create a forwarding email address
3. Click "Add New Email Forward"
4. See this big red message:

![email-fwd](https://user-images.githubusercontent.com/16645645/27627399-f25469ba-5beb-11e7-900b-2e38d4cc2f1f.png)

#### What I expected

Since adding emails to subdomain is not doable, the Email tab at https://wordpress.com/domains/manage/my.subdomain.com/ should not be accessible at all so users can't add either Email Forwarding or G Suite.

#### What happened instead

I got access to the Email tab and it broke. ¯\_(ツ)_/¯

**Comment by klimeryk** [comment] 2021-02-02 13:42
I've tested this again and cannot reproduce it anymore - closing as resolved.

**Closed by klimeryk** 2021-02-02 13:42 UTC
Labels: Domains, [Type] Bug
