### ISSUE TITLE
[Bug]: White screen when switching site context from purchase cancellation page.

### ISSUE THREAD

**Issue by jboland88** [Automattic/wp-calypso#64712] opened 2022-06-16 19:26 UTC
### Quick summary

Switching sites when at the path `/purchases/subscriptions/:site/:purchase_id/cancel/` results in a white screen.

### Steps to reproduce

1. Choose a site that has cancellable purchases.
2. Navigate to Purchases for that site, select the purchase and click on "Cancel" or "Cancel and Refund" from the purchase page. This will take you to the `/cancel` page.
3. From the cancel page, use the site switcher to select another site.
4. A white screen appears.

### What you expected to happen

I expect the purchases for the selected site to appear.

### What actually happened

A white screen shows instead.

### Browser

Google Chrome/Chromium

### Other notes

Testing primarily with Jetpack sites.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment] 2023-05-03 20:58
Closing as dupe of https://github.com/Automattic/wp-calypso/issues/71956 (Part 2 of report)

**Closed as completed by cuemarie** 2023-05-03 20:58 UTC
Labels: Bug, [Pri] Low, [Feature] Purchase Management, Site Switcher i1
