### ISSUE TITLE
Me: Fix the current flow for Sign Out when using 2FA

### ISSUE THREAD

**Issue by Tug** [Automattic/wp-calypso#3666] opened 2016-02-29 15:21 UTC
#### Steps to reproduce
1. Have 2FA enabled on your account
2. Starting at URL: http://calypso.localhost:3000/
3. You want to log out
4. You click on your avatar on the top right and are redirected to http://calypso.localhost:3000/me
5. You are asked for a verification code before you can do anything else, including signing out
#### What I expected

Being able to log out from an account without knowing the verification code for it.
#### What happened instead

I was asked for a verification code I may not have (if it is not my account).
#### Screenshot

![just wanna log out](https://cloud.githubusercontent.com/assets/66797/14358069/4f0c1498-fca0-11e5-9c49-9eba1977da3e.jpg)

**Comment by lancewillett** [comment] 2016-04-07 15:38
Might be a duplicate of #202

**Comment by aduth** [comment] 2016-04-07 15:40
>Might be a duplicate of #202 

#202 was technically first, but yes, I agree with assessment this is duplicate.

**Comment by lancewillett** [comment] 2016-04-07 15:40
Duplicate of means that one is first, yes. :)

**Comment by lancewillett** [comment] 2016-04-07 15:41
Closing in favor of older issue.

**Comment by aduth** [comment] 2016-04-07 15:42
Err, sorry, I was referring to #4272, which is newer than this issue and should have been kept open. #202 I feel is a separate issue.

**Comment by lancewillett** [comment] 2016-04-07 15:44
See also #960 — similar UX problem for changing a password.

**Comment by lancewillett** [comment] 2016-04-07 16:09
One quick improvement would be to make the `Not you? Sign out` link stand out more:

![just wanna log out](https://cloud.githubusercontent.com/assets/66797/14358083/59d9a0c0-fca0-11e5-9515-35cbbb0f30f0.jpg)

**Comment by Tug** [comment] 2016-04-07 21:58
Agreed, I didn't notice it was there actually!

**Comment by aduth** [comment] 2016-04-11 15:30
Possibly better tracked as a separate issue and certainly worrying: following the flow described in the original comment, another consequence of the stale token is that navigating to the Me section causes the `/me/settings/profile-links` endpoint to be requested _infinitely_.

**Comment by Tug** [comment] 2016-04-12 09:44
So this is design issue IMO.
I think we could show a small card about the current user profile with the gravatar image and the name of the account. Then you would notice if it's not yours and find quickly the "Not you?" attached to this card.

**Comment by lancewillett** [comment] 2016-04-26 20:39
@Tug Love that idea, much more visually rich and communicates which user is logged in.

**Comment by ryanboren** [comment] 2016-05-16 13:44
I always overlook sign out links that are prefixed with "Not you?" type text. I've stared at this screen looking for and missing the sign out link on several occasions. I am certain to overlook sign out links embedded in text. Amazon is the classic case of this.

> When I’m on the desktop computer at the office and finish ordering books on Amazon.com for an article I’m working on, for instance, I can never find a simple log-out button. Instead, I scroll down a column marked “Hello, Natasha — Your Account” and then click on an option that reads: “Not Natasha? Sign Out.” But the notion that in order to sign off, I have to deny that I am me always gives me pause.

>“It’s really clever — they want you to do something that is counterintuitive and maybe a little freaky to you,” Mr. Nodder said. “There’s an element of ‘Maybe I just won’t sign out this time.’”

http://www.nytimes.com/2016/05/15/technology/personaltech/when-websites-wont-take-no-for-an-answer.html?_r=0

I overlook sign out. Once I do finally notice it, I have to deny my identity.

**Comment by ryanboren** [comment] 2016-05-16 13:44
Also, on iOS, tapping Notifications doesn't dismiss the 2FA dialog, contributing to a trapped feeling.

**Comment by ryanboren** [comment] 2016-05-16 16:22
I suggest "Sign out" standing alone. This dialog is an intrusion in flow that usually features a prominent Sign out button.

<img width="276" alt="screen shot 2016-05-16 at 11 14 36 am" src="https://cloud.githubusercontent.com/assets/2047747/15295857/517243d4-1b58-11e6-8745-952d81d212e7.png">

![img_9663](https://cloud.githubusercontent.com/assets/2047747/15295887/770b988e-1b58-11e6-9ba8-2779931ac169.PNG)

**Comment by folletto** [comment] 2016-05-16 16:41
The quick fix would be just to move "Sign Out" in the dialog below, since all the Dialog actions are meant to stay below:

![screen shot 2016-05-16 at 17 36 10](https://cloud.githubusercontent.com/assets/4389/15296340/e110a114-1b8c-11e6-9df1-5c3d5aa6f462.png)

_(btw apparently there's a bug there on mobile where the button falls below)_

---

However... that screen shouldn't be a Dialog. Dialogs should be avoided as much as possible, and in this scenario it doesn't make sense design-wise (even I'm sure there was a technical reason to make it that way):

![2fa-inpage-i1](https://cloud.githubusercontent.com/assets/4389/15296393/24007706-1b8d-11e6-8d4f-81257045ec45.png)

In this design concept the "dialog" isn't really a dialog (we could even design it to look entirely different) but a "lock" on the specific area of the screen that is impacted in practice by the lock. The sidebar is still functional (navigating isn't locked) and this allows the access to any section that doesn't have the lock... or to see again the log if even other sections are actually locked.

**Comment by drw158** [comment] 2016-06-02 22:24
I remember the discussion of the design of this modal, but I can't find it. I quicker solution would be to make "Send SMS Code" a link instead of a button, and make "Sign Out" a button at the bottom.

**Comment by kriskarkoski** [comment] 2016-10-17 19:07
I don't have a stale 2fa to grab a screenshot, but this still exists as in the original screenshot with the Sign Out link inline and easy to overlook. +1 to @drw158 quick fix suggestion above since I don't think a revamp of this design is on anyone's roadmap near-term.

**Comment by mcsf** [comment] 2017-07-06 10:00
Closed per #15095

**Closed by mcsf** 2017-07-06 10:00 UTC
Labels: Me, [Status] Needs Design Review, [Type] Bug
