### ISSUE TITLE
Editor: Media: Add via URL "Upload" button truncated Safari (Desktop and iOS)

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#3485] opened 2016-02-23 01:10 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Click "Add Media"
3. Click "Add via URL"

#### What I expected
Button to say "Upload" as per other browsers (Chrome, Firefox)

#### What happened instead

Buttons shows "Upl..." (Desktop) and "U..." (iOS iPhone 6+)

#### Browser / OS version

iOS 9.2.1 Safari
Safari 9.0.3 OSX 10.11.3

#### Screenshot / Video

![iphone 6](https://cloud.githubusercontent.com/assets/128826/13238288/89cdc05e-da1d-11e5-8251-f30fbe689402.png)

![add via url button safari](https://cloud.githubusercontent.com/assets/128826/13238307/b5183938-da1d-11e5-97b3-5c745b1762da.png)

**Comment by hoverduck** [comment] 2016-04-21 17:52
21Apr16 Bug Scrub

Confirmed this is still an issue.  Even with the Safari (v9.1, OSX 10.11.4) stretched the full width of a 27" monitor, the text in the button is cutoff.  This was also observed in IE11 on Windows 7.

![image](https://cloud.githubusercontent.com/assets/7233112/14718952/7c0ce6b6-07c7-11e6-914a-aedb78ae7000.png)

**Comment by designsimply** [comment] 2016-07-20 01:25
Closing because I was unable to reproduce the problem using the testing steps provided. The Add Media > Add via URL > "Upload" button appears normally using Safari 9.1 on Mac OS X 10.11.5 or Safari iOS 9.3.2 on iPhone 6S:

![screen shot 2016-07-19 at tue jul 19 7 18 15 pm](https://cloud.githubusercontent.com/assets/1119271/16972070/e47e82ae-4de5-11e6-8e50-f00f205e48cb.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com using Safari 9.1 on Mac OS X 10.11.5</sup>

<img alt="img_7925" src="https://cloud.githubusercontent.com/assets/1119271/16972140/5c30d02c-4de6-11e6-836b-dd688dc1f4db.PNG" width="400" />
<sup>Seen at https://wordpress.com/post/saratogafood.wordpress.com using Safari iOS 9.3.2 on iPhone 6S</sup>

**Closed by designsimply** 2016-07-20 01:25 UTC
Labels: Editor, Media, [Type] Bug
