### ISSUE TITLE
Full Site Editing: Minor Site Description Improvements

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34141] opened 2019-06-19 22:14 UTC
1. Update "Site Description2" in registration to "Site Description"
<img width="538" alt="Screen Shot 2019-06-19 at 3 14 59 PM" src="https://user-images.githubusercontent.com/1270189/59805076-1ae53980-92a5-11e9-9b4d-c2753127413b.png">

2. Verify if we need a specific Block Logo here cc @jasmussen 
<img width="848" alt="Screen Shot 2019-06-19 at 3 16 25 PM" src="https://user-images.githubusercontent.com/1270189/59805151-508a2280-92a5-11e9-8731-4c2bf0012d82.png">

3. The save button is meant to be temporary here, but are there any styling suggestions for the PlainText component used in isolation? It does stand out a bit 
<img width="848" alt="Screen Shot 2019-06-19 at 3 16 25 PM" src="https://user-images.githubusercontent.com/1270189/59805189-6861a680-92a5-11e9-96ad-b4de3c9c3760.png">

4. Add unsaved changes warning if we attempt to leave without a block save.

**Comment by kwight** [comment] 2019-06-19 22:28
#34096 fixes the typo.

**Comment by jasmussen** [comment] 2019-06-20 07:23
Thanks for the ping!

> Verify if we need a specific Block Logo here

You're referring only to the tagline right? And by tagline, I mean it updates this field, correct?

<img width="622" alt="Screenshot 2019-06-20 at 09 19 33" src="https://user-images.githubusercontent.com/1204802/59829054-a958ca00-933c-11e9-9e1e-3cd85b43ed04.png">

If it's not that, and it's meant to be a longer description, we can use [this icon](https://material.io/tools/icons/?search=descrip&icon=description&style=outline). If it's actually "tagline", let's use [this short text icon](https://material.io/tools/icons/?search=text&icon=short_text&style=outline):

```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"/><path d="M4 9h16v2H4V9zm0 4h10v2H4v-2z"/></svg>
```

> The save button is meant to be temporary here, but are there any styling suggestions for the PlainText component used in isolation? It does stand out a bit

The design principles for the block design suggest that when the block is unselected, the tagline should look exactly like it would on the frontend. So whatever theme styles present should bleed in here.

When the block is selected, it's okay for additional UI to be present. I don't feel an actual input field is necessary — it isn't for the Paragraph block. 

About the save button — would it work to simply remove it? Or is an explicit save action necessary for this field to be updated? Ideally the contents would autosave as soon as you're done typing, or deselect the block.

**Comment by kwight** [comment] 2019-06-24 19:15
> You're referring only to the tagline right? And by tagline, I mean it updates this field, correct? If it's actually "tagline", let's use this short text icon

Indeed 👍 Fixed:

<img width="415" alt="Screen Shot 2019-06-24 at 12 06 21 PM" src="https://user-images.githubusercontent.com/349751/60045164-02946680-9679-11e9-9307-9f998e02010b.png">

> The design principles for the block design suggest that when the block is unselected, the tagline should look exactly like it would on the frontend. So whatever theme styles present should bleed in here.

✅

> About the save button — would it work to simply remove it? Or is an explicit save action necessary for this field to be updated? Ideally the contents would autosave as soon as you're done typing, or deselect the block.

Saving it means an API call every time, so it would get expensive quickly (Gutenberg has no concept of site options, so individual API calls are our only fetch/updating process at this point).

**Comment by glendaviesnz** [comment] 2019-06-25 01:55
> When the block is selected, it's okay for additional UI to be present. I don't feel an actual input field is necessary — it isn't for the Paragraph block.

Suggested fix for this in #34256

**Comment by jasmussen** [comment] 2019-06-25 06:25
> Saving it means an API call every time, so it would get expensive quickly (Gutenberg has no concept of site options, so individual API calls are our only fetch/updating process at this point).

Gotcha. If you forget to hit the save button, will any changes you made still be saved when you publish or update the post/page?

In absence of that, I would try and emulate the existing design pattern that exists for Reusable Blocks, so at least it's the same UI.

**Comment by kwight** [comment] 2019-06-25 18:22
> Gotcha. If you forget to hit the save button, will any changes you made still be saved when you publish or update the post/page?

No – I don't believe we have a mechanism for that, since Gutenberg itself is unaware of site options, or anything not saved within post content. Am I getting that right, @gwwar ? I think I've been assuming that that's an acceptable risk at this point; no-one will lose paragraphs of writing (or maybe I'm underestimating the user's perception of the flow?).

**Comment by gwwar** [comment] 2019-06-25 19:01
@glendaviesnz is currently looking for options to allow for using the single save button for both post_content and outside sources like site options. This save button per block is temporary until we have that in place. (ie we won't ship this to customers)

For what we have currently I don't believe any loss will occur. The unsaved warnings hook should fire as expected.

The unsaved warnings

**Comment by jasmussen** [comment] 2019-06-26 06:33
To clarify, even if there was some loss, I don't think it would be the end of the world. Just thinking a bit ahead here, on how we can move in the best long term direction. All sounds good.

**Comment by glendaviesnz** [comment] 2019-06-27 20:20
>4. Add unsaved changes warning if we attempt to leave without a block save.

With the decision to remove the save buttons and use temporary attribute updates instead the remaining point above should be covered by #34287 - this change will cause the editor content to be flagged as dirty so the normal prompt to save mechanisms should kick in.

**Comment by glendaviesnz** [comment] 2019-06-28 04:10
> Add unsaved changes warning if we attempt to leave without a block save.

Have confirmed that #34350 resolves the above as the standard editor unsaved changes prompts now kick in. 

I am pretty sure everything in this issue is covered now so going to close.

**Closed by glendaviesnz** 2019-06-28 04:10 UTC
Labels: [Goal] Full Site Editing, [Status] Needs Design Review, [Type] Task
