### ISSUE TITLE
Subscriber Stats: Glitch with the data

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/wp-calypso#81011] opened 2023-08-24 09:50 UTC
I checked stats and the Subscriber tab loads with a glitch, changing the order and labels on the All-time stats.

https://github.com/Automattic/wp-calypso/assets/25607244/16e3b8fc-2f9e-45f0-9799-a06c738f5358

**Comment by kangzj** [comment] 2023-08-24 20:59
Thanks for reporting this @crisbusquets. I'll take a look earlier next week. 🤝

**Comment by cuemarie** [comment] 2023-08-24 23:05
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated / Could Not Replicate / Uncertain
- Tested on Atomic – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated consistently across Simple and Atomic

**Atomic**

https://github.com/Automattic/wp-calypso/assets/27249804/ada9b351-639d-42d5-b855-f01382832175

📌 ACTIONS
- Triage Complete
- Marking as In Progress since @kangzj is taking this one on. Thanks!

**Comment by kangzj** [comment] 2023-08-29 21:55
Fixed with #81162

**Closed as completed by kangzj** 2023-08-29 21:55 UTC
Labels: Bug, [Feature] Stats, [Pri] Normal
