### ISSUE TITLE
Gutenberg 16.7.1: Can't add new WooCommerce products with Beta product editor

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#82892] opened 2023-10-11 20:52 UTC
### Quick summary

On an atomic site with WooCommerce active version 8.2.0 _using the Beta product editor_, and Gutenberg active on version 16.7.1, I was able to identify this bug today:

---

When trying to create new products in the Beta Product Editor, clicking in the Summary field or typing in the Name field causes the page to immediately blank out, non-responsive (however the WordPress.com sidebar on the left still works) so you can move away from there. If I deactivate Gutenberg v16.7.1, the bug no longer occurs.

I was able to identify the following Console error:

<img width="1792" alt="Screenshot 2023-10-11 at 16 40 09" src="https://github.com/Automattic/wp-calypso/assets/31009008/779d0b0b-3d3c-45a6-8f70-812337d18552">

### Steps to reproduce

1. On a WooCommerce site, open `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features` 
2. Check the box next to `Try the new product editor (Beta)`
3. Follow the steps shared below:

- Products
- Add New
- Click the field "Summary"
or

- Products
- Add New
- Click the field "Name"
- Add any characters in the field

### What you expected to happen

Continue editing

### What actually happened

Screen blanks out.

### Impact

Some (< 50%)

### Available workarounds?

~No and the platform is unusable~

Customers can disable the New Product Editor, which is still Beta, from **Settings > WooCommerce > Advanced > Features** (`/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`), by unchecking this box:

![Markup on 2023-10-12 at 10:11:42](https://github.com/Automattic/wp-calypso/assets/27249804/f74e0e45-30d3-4578-a1ff-6e0be66ff0ee)

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

User report 7154503-zen

**Comment by cuemarie** [comment] 2023-10-11 20:58
Escalation thread: p1697057700636149-slack-C02FMH4G8

**Comment by cuemarie** [comment] 2023-10-11 21:07
📌 ACTIONS
- Unable to replicate yet - test sites are operating as expected, so downgrading priority from `Blocker` to `High`

**Comment by cuemarie** [comment] 2023-10-11 21:25
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Not replicable on test sites. The user deleted Gutenberg right after the chat above, so we cannot test further on their site either, without their permission.

📌 ACTIONS
- Closed as could not replicate (we can reopen if we're able to replicate this with further testing)
- I've sent a follow up email to the user for further troubleshooting: 7154703-zen

**Comment by msilbers** [comment] 2023-10-12 15:42
Just had the same issue in 7159571-zd and thanks to this issue I was able to quickly resolve it by deactivating Gutenberg. Reopening this since we have a second case.

I am trying to replicate this but unsure how to activate the beta product form where this bug occurs. It does not seem to occur on the default Woo form, just the beta. I am not sure if that was the case for @davipontesblog as well based on the screenshot

**Comment by msilbers** [comment] 2023-10-12 15:46
Replicated on a  test Commerce site with no other plugins
You can enable the feature from Settings > WooCommerce > Advanced > Features
Then, editing or adding any product, the editor will crash when you click into Summary. You can't add any text
Deactivating the Gutenberg plugin resolves it

**Comment by cuemarie** [comment] 2023-10-12 16:58
Thanks @msilbers ! I was just able to replicate as well with the beta product editor - that's what we were missing yesterday!

**Comment by cuemarie** [comment] 2023-10-12 17:06
📌 REPRODUCTION RESULTS
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO

Replication requires the beta product editor be active. Open `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features` and check the box next to `Try the new product editor (Beta)`, and then the issue will occur.

Gutenberg 16.6.0 does not reproduce, and **neither does 16.8.**

📌 ACTIONS
- Updated title & steps to replicate
- Triaged
- Pinged folks in the escalation thread now that we can reproduce: p1697130336733819/1697057700.636149-slack-C02FMH4G8

**Comment by cuemarie** [comment] 2023-10-12 17:14
Also reported here: https://github.com/Automattic/woocommerce/issues/283

**Comment by cuemarie** [comment] 2023-10-12 17:29
This conflict is resolved in **Gutenberg 16.8**, which should hit Atomic sites very shortly.

**Comment by cuemarie** [comment] 2023-10-17 19:52
Retested today with Gutenberg 16.8.1 and I'm able to use the Beta Product Editor without issue.

📌 ACTIONS
- Closing as resolved

**Closed as completed by cuemarie** 2023-10-17 19:52 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] Normal, Triaged, caused-by-gutenberg-upgrade, Customer report [LEGACY], [Platform] Atomic, [Product] WordPress.com, [Feature Group] Editor Experience
