### ISSUE TITLE
Editor: Facebook & Twitter Embeds Not Generating Preview

### ISSUE THREAD

**Issue by RealCarFax** [Automattic/wp-calypso#32088] opened 2019-04-06 17:35 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Paste in this link: https://twitter.com/wordpressdotcom/status/1080467237897670656

#### What I expected
In the past, when you paste in a link to a Facebook or Twitter post, the post will display an embed preview in the visual editor.

#### What happened instead
The editor removes the link and show a very small blinking cursor but no embed preview.

If you switch to the HTML editor tab you'll see the link.
If you switch to the Preview or Publish the page you can see the embed.

#### Browser / OS version
Confirmed on Safari Version 12.1 (14607.1.35.1) and Google Chrome Version 73.0.3683.86

#### Screenshot / Video
An example of the Twitter Embed: https://cloudup.com/coODR_i5wzi

#### Context / Source
This was originally reported by a user, but confirmed on my own testing sites #user-report

**Comment by arunsathiya** [comment] 2019-04-06 18:00
I tested as well, and I can reproduce this behaviour. I also noticed this error on the console.

```
TypeError: Class constructor tt cannot be invoked without 'new'
    at t (vendors~post-editor.58f91dec60d219a33ca3.min.js:1)
    at new t (vendors~post-editor.58f91dec60d219a33ca3.min.js:1)
    at ao (vendors~build.a62d2d5e9c6d6ffb98cc.min.js:61)
    at Ti (vendors~build.a62d2d5e9c6d6ffb98cc.min.js:61)
    at Ni (vendors~build.a62d2d5e9c6d6ffb98cc.min.js:61)
    at Bu (vendors~build.a62d2d5e9c6d6ffb98cc.min.js:61)
    at Vu (vendors~build.a62d2d5e9c6d6ffb98cc.min.js:61)
    at Ps (vendors~build.a62d2d5e9c6d6ffb98cc.min.js:61)
    at Cs (vendors~build.a62d2d5e9c6d6ffb98cc.min.js:61)
    at xs (vendors~build.a62d2d5e9c6d6ffb98cc.min.js:61)
```

<img width="810" alt="Screenshot 2019-04-06 at 23 23 01" src="https://user-images.githubusercontent.com/18581859/55673288-c1838600-58c3-11e9-92f1-a197e0d3e7a3.png">

Making a guess here, but could it be related to https://github.com/Automattic/wp-calypso/pull/30768? I tested on a local branch prior to https://github.com/Automattic/wp-calypso/pull/30768 and embed previews seem to work properly.

**Comment by nickpagz** [comment] 2019-04-06 18:26
Reporting an additional case from a user experiencing the same with Youtube embeds. Was able to replicate on a test site, but seems to be work in wp-admin, not calypso.

**Comment by RealCarFax** [comment] 2019-04-06 18:28
Yes, @nickpagz I forgot to mention that as I noticed it as well - embedding via WP Admin seems to work properly, it's only the Calypso classic editor that I'm noticing the issue on.

**Comment by sgomes** [comment] 2019-04-06 19:13
The issue has been identified and a fix is in progress. I'll keep this issue updated.

**Comment by sgomes** [comment] 2019-04-06 19:38
The fix has been merged, will be deployed soon.

**Closed** 2019-04-06 19:37 UTC
Labels: Editor, Support, [Pri] High, [Type] Bug

**Comment by sgomes** [comment] 2019-04-06 19:49
The fix has been deployed. Should be working again, please let me know if there are any other user reports!
