### ISSUE TITLE
Reader: Slideshow block rendered as bulleted list

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#46330] opened 2020-10-09 19:54 UTC
The slideshow block currently renders as a bulleted list in the Reader.

![image](https://user-images.githubusercontent.com/545779/95625985-1535d900-0a3f-11eb-9c7b-69350503adcf.png)

Expecting it may be difficult to render a slideshow there a simple quick fix could be to update the styles for that ul element to remove the bullets and margin.

**Comment by kriskarkoski** [comment] 2021-02-08 14:32
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/45085

**Closed by kriskarkoski** 2021-02-08 14:32 UTC
Labels: Blocks, Reader, [Closed] Duplicate, [Pri] Low, [Type] Bug
