### ISSUE TITLE
Bug/Authorizing-Instagram-Widget-Runaround

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wp-calypso#4613] opened 2016-04-08 19:27 UTC
Hey folks!

As I attempt to authorize the instagram widget via the customizer I get a runaround that won't allow me to authorize it. It just ends up reloading the customizer without the widget I've added. Will definitely be frustrating for a lot of users. (And yes, I'm already logged into the desired instagram account with my browser)

**Steps to reproduce:**

1) Enter the customizer. Add the instagram widget

<img width="467" alt="screen shot 2016-04-08 at 3 20 11 pm" src="https://cloud.githubusercontent.com/assets/214813/14395053/7a7224da-fd9d-11e5-9fbc-0358e3d82cb3.png">

2) Click "Authorize..." Chrome wants to navigate away from customizer... I expected an Instagram dialog to open so I could authorize WordPress.com

![screen shot 2016-04-08 at 3 17 20 pm](https://cloud.githubusercontent.com/assets/214813/14395074/95b394d6-fd9d-11e5-9932-de29ac194756.png)

3) Customizer is reloaded, sans any widgets I've added since the last "save & publish." Instagram is not authorized.

![screen shot 2016-04-08 at 3 26 25 pm](https://cloud.githubusercontent.com/assets/214813/14395103/bcd7fc00-fd9d-11e5-8b39-2cffc126f68f.png)

**Technical Details:**
Browser: Chrome  49.0.2623.110 (64-bit)
OS: Mac OSX v 10.11.1 (El Capitan)

**Comment by kwight** [comment] 2016-04-11 15:42
The problem is when a user clicks the big blue button without first saving the widget (noted by the Confirm Navigation alert). Was that your case?

We recently improved the instructions by adding "Click Save & Publish above..." to the widget notice, but perhaps all anyone sees is the big blue button and don't read first (sounds like something I would do). Maybe the big blue button needs to be the Save action if necessary first, and _then_ allow authorization.

I'll close this since it's a Customizer issue rather than Calypso-specific, and follow up on the dotcom side.

**Closed by kwight** 2016-04-11 15:42 UTC
Labels: Customizer, [Type] Bug
