### ISSUE TITLE
Message: "enable JavaScript in order to use Gutenberg" on AT site 

### ISSUE THREAD

**Issue by ezebecke** [Automattic/wp-calypso#30326] opened 2019-01-22 17:42 UTC
#### Steps to reproduce
1. Starting at URL: https://paularvin.com
2. Deactivate Classic Editor plugin.
3. Go to page editor.
4. message that they need to enable JavaScript in order to use Gutenberg

#### What I expected

No error messages.

#### What happened instead

![gutenberg-js](https://user-images.githubusercontent.com/24919469/51554245-70263780-1e3a-11e9-812c-13c105e9345c.png)

Message says that they need to enable JavaScript in order to use Gutenberg or to try Classic Editor plugin. Block editor seems to work.

#### Browser / OS version

The same error appears on Edge, Firefox, and Chrome. I was able to reproduce that on their site from my end.

#### Screenshot / Video

https://cld.wthms.co/HXljK5

**Comment by arunsathiya** [comment] 2019-04-05 12:41
I had a look at this site, and I do not see such a notice at the moment. Same WooCommerce checkout page that you had shown on the screenshot. What caused that issue earlier feels unrelated to the Gutenberg implementation on WordPress.com, to me, or maybe it was a notice caused by a different plugin. 

For now, I am closing this GitHub issue as a non-issue, but if you do run into a similar one or if you do see something off on this user's site, feel free to reopen! I would be happy to look along, @ezebecke.

**Closed by arunsathiya** 2019-04-05 12:41 UTC
Labels: Atomic, [Goal] Gutenberg

**Comment by ezebecke** [comment] 2019-04-10 03:42
Thanks for taking a look at this @arunsathiya! I don't see the error message anymore and they have quite a few plugins so it's possible that it was caused by a plugin.
