### ISSUE TITLE
Signup: Misaligned label for domain availability

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#16560] opened 2017-07-25 22:27 UTC
During signup (start at homepage, logged out, go through signup flow) you are asked to select a domain. You will be told that the domain is available in WordPress.com Premium, but the label that says that is not quite aligned with the other strings being shown there.

I saw this on Chrome/OSX.

<img width="1011" alt="screen shot 2017-07-25 at 3 59 02 pm" src="https://user-images.githubusercontent.com/108942/28596512-291ee658-7156-11e7-9648-5a355286038a.png">

@fditrapani assigning to you just because I know you've been dabbling in signup recently, and hopefully this is a quick fix.

**Comment by klimeryk** [comment] 2017-07-25 22:37
Probably duplicate of https://github.com/Automattic/wp-calypso/issues/11521

**Comment by klimeryk** [comment] 2017-07-25 22:38
But patches are more than welcome :)

**Comment by fditrapani** [comment] 2017-07-26 02:44
Thanks @beaulebens and @klimeryk. I've created a Trello card for it on the Customer marketing board: https://trello.com/c/yuucF15w/398-alignment-issue-on-the-domains-sign-up-page

**Closed** 2017-08-02 13:14 UTC
Labels: Domains, Signup
