### ISSUE TITLE
FSE: Clicking Dashboard link from Templates list page causes error

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#60110] opened 2022-01-16 22:38 UTC
### Quick summary

When I try to use the Dashboard link to go back to the dashboard from the Templates list page, I get an error and don't go back to the dashboard.

### Steps to reproduce

1. Select Appearance > Editor
2. Click Toggle Navigation to see the sidebar
3. Select Templates from the sidebar
4. Click the Dashboard link in the sidebar 

### What you expected to happen

I expected to go back to the dashboard.

### What actually happened

I got this error:
<img width="444" alt="FSE ERROR" src="https://user-images.githubusercontent.com/32983813/149680977-5f9b5c9d-7abf-43f0-8e52-67976ddf9fce.png">

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

**Comment by kerrynicl** [comment] 2022-01-17 13:01
Hi @ccwalburn Could you say if this happens on a specific theme? I tried testing in on my site but was not able to replicate. Could you say if the steps followed below are correct:

https://user-images.githubusercontent.com/83325600/149773624-bf81f604-64a3-4918-88d6-99a79e969651.mp4

**Comment by ccwalburn** [comment] 2022-01-18 15:00
Hi @kerrynicl I'm using the Zoologist theme on a Free site. This is what happens for me:

https://user-images.githubusercontent.com/32983813/149961931-05b956f5-02c6-416f-9a08-1eaf7f204669.mp4

**Comment by ckmccoy2** [comment] 2022-01-18 21:47
Same thing happens on my site: fseckm2.wordpress.com: https://d.pr/v/8ng34E

I'm using the Arbutus theme.

**Comment by vindl** [comment] 2022-01-26 21:37
Pulling this to our board. To consistently reproduce this you can follow the steps in https://github.com/Automattic/wp-calypso/issues/60490.

**Comment by davipontesblog** [comment] 2022-01-28 17:20
I also noticed a bug there when I click “Dashboard” it takes me to /wp-admin/index.php instead of `My Site > My Home` which should be the default wpcom experience.

**Comment by zaguiini** [comment] 2022-01-29 00:49
Will pair with @jeyip on Monday.

**Comment by jeyip** [comment] 2022-02-03 15:56
I can replicate the problem. One thing to note is that, for me, it only happens when visiting the site editor from the Calypso UI. If I navigate to the full site editor from wp-admin, things appear to work as expected.

**Comment by jeyip** [comment] 2022-02-04 09:16
@Addison-Stavlo made [a great observation](https://github.com/Automattic/wp-calypso/issues/59818).

> It seems that our Fill for the "< Dashboard" slot is not working when the other nav items are selected. Either there is an issue with our plugin adding the fill requiring a fix on dotcom, OR the slot is not present when these other navigation items are selected requiring a fix in core.

After some digging, here's what I've found:

- Here is where the default back to dashboard button is defined in Gutenberg ( [link](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/navigation-sidebar/navigation-panel/index.js#L79-L85) )
- Here is where our plugin overwrites the default back to dashboard button in Calypso ( [link](https://github.com/Automattic/wp-calypso/blob/f4948a9859c50e2a538069b5a54b67d2baa81b15/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#535-L556) )
- I removed our dashboard button slot fill logic from the `registerPlugin` call and embedded it into Gutenberg itself. In doing so, I verified that our overwrites behave as expected, even after selecting other navigation items like "Templates".
- This leads me to believe that our issue is with the `registerPlugin` call which will require a fix in core.
- I haven't pinpointed exactly what about `registerPlugin` is causing the problem yet

**Comment by zaguiini** [comment] 2022-02-21 21:15
It looks like we're throwing away all information about the filled slot after clicking another item and that's why we're losing our override. The plugin is _registered_ even after clicking on `Templates`:

![image](https://user-images.githubusercontent.com/26530524/155026794-20823397-76a2-4649-b002-7c350fc9d4d3.png)

Being registered does not mean it's being rendered. It looks like we're causing some kind of refresh when clicking on a link on the sidebar. That URL when hovering `Templates` is very suspicious:

![image](https://user-images.githubusercontent.com/26530524/155027050-85221d86-849a-4e4d-bba0-a8e409925ee8.png)

Why does it point to WP Admin instead of preserving the actual, current URL? Regardless, we're losing the slot override and that's what's causing our problem. If we manage to keep the state after the "refresh" we can fix this problem.

And it's not WPCOM specific as @Addison-Stavlo suspected.

If you spin up a `wp-env` Gutenberg instance, go to site editor, open DevTools and run this code:

```js
var el = wp.element.createElement;
var Fill = wp.components.Fill;
var registerPlugin = wp.plugins.registerPlugin;

registerPlugin( 'test', {
  render: function() {
    return el(
      Fill,
      { name: '__experimentalMainDashboardButton' },
      el('span', {}, 'hello, world')
    );
  }
} );
```

You'll see `hello, world` in the navigation bar, but as soon as you click on `Templates` it will disappear:

https://user-images.githubusercontent.com/26530524/155028556-2f6db0e0-3338-44a4-877e-a64e8eb19c06.mov

So it's something in Core. It's not a problem with `registerPlugin` as I pointed out above. The plugin is still registered. My best guess is that we're losing the slot contents anywhere between renders/faux-refreshes?

**Comment by zaguiini** [comment] 2022-02-21 22:27
@diegohaz @sarayourfriend I see your names all over the slot implementation `git blame` 😅  Maybe you could have more information on why ☝️  is happening and how to fix it?

All `slots` and `fills` are lost inside `useSlotRegistry` when switching pages. I tried looking for clues about a reset (using `key` property for example) but found nothing.

**Comment by zaguiini** [comment] 2022-02-24 20:38
Just found the problem. Spinning a PR soon!

**Comment by zaguiini** [comment] 2022-02-24 21:04
There's our bugfix: https://github.com/WordPress/gutenberg/pull/39078

Do not forget to sync the most current ETK to your sandbox while testing on WPCOM. Otherwise, you'll not see the navigation drawer.

**Comment by zaguiini** [comment] 2022-02-25 18:52
The PR is merged, awaiting Gutenberg release.

**Comment by Addison-Stavlo** [comment] 2022-03-16 18:57
Noting that the fix is currently live on `edge` sites running G v12.8+ and should make its way to production in the next couple days.

**Comment by Addison-Stavlo** [comment] 2022-03-17 16:44
This fix is now live on dotcom.

**Closed as completed by Addison-Stavlo** 2022-03-17 16:44 UTC
Labels: Bug, [Pri] Normal, Testing, [Goal] Full Site Editing, Triaged
