### ISSUE TITLE
 WordPress.com Editing Toolkit: Atomic site stuck in Coming Soon mode after ETK plugin deactivated

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#79763] opened 2023-07-22 15:47 UTC
### Quick summary

On WordPress.com Atomic Sites, users can deactivate the WordPress.com Editing Toolkit plugin while their site is unlaunched. 

When the plugin is deactivated, a notice says that the site will be made public, however, the site remains stuck in Coming Soon (Unlaunched) via Privacy Settings, and the front end still shows the Coming Soon page. 

https://github.com/Automattic/wp-calypso/assets/29527450/d76425de-f15a-4011-9d92-bad34f55ebff

### Workaround: 

To make the site Public you still have to Navigate to My Site > Settings > General and Launch the site.

### Steps to reproduce

1. Create a new WordPress.com site, add a Business plan, and [Activate the Hosting Features](https://wordpress.com/support/hosting-configuration/#activate-hosting-configuration). 
2. Navigate to Plugins > Installed Plugins > Locate WordPress.com Editing Toolkit and click Deactivate. 
4. Click OK on the popup that says, "Disabling this plugin will make your site Public"
5. Navigate to Settings > General and see your site is still not launched or pubic. 

### What you expected to happen

Since the popup told me my site would be made public, I expect my Privacy Settings via My Site > Settings > General to now display that my site is Public like this: 
<img width="738" alt="image" src="https://github.com/Automattic/wp-calypso/assets/29527450/83b30162-c98a-459c-a91e-f29055b4bdee">

Additionally, I expect my site to be Public when I access my live site's domain.  

### What actually happened

My site is still stuck as Unlaunched via My Site > Settings > General in Calypso: 
<img width="627" alt="image" src="https://github.com/Automattic/wp-calypso/assets/29527450/b9aafd64-5c5e-46a1-8155-078d1befb50e">
 
And Coming Soon is still displayed on the front end of my site via my address. 

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Related interaction: 

 p1689961338712459-slack-C03TY6J1A

**Comment by cuemarie** [comment] 2023-07-24 20:06
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Replicated** - _somewhat_

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated - I am able to deactivate the ETK while the site is unlaunched, and I'm shown the warning that my site will become public, even though that doesn't change.
- However, I am able to launch the site, and switch between Public & Coming Soon, so this suggests that the ETK is no longer responsible for Coming Soon mode.

#### Screenshots/Recordings

_Deactivating ETK_

https://github.com/Automattic/wp-calypso/assets/27249804/609e063b-afb0-4272-82d1-959d60df141a

_Launching & Switching Privacy Statuses_


https://github.com/Automattic/wp-calypso/assets/27249804/2b595bbc-c86f-4a36-b9ea-424c4b975f5c

📌 ACTIONS
- Requested Dev feedback

📌 Message to Author
- I suspect that the underlying assumption to this and https://github.com/Automattic/wp-calypso/issues/79764 - that the ETK is responsible for Coming Soon mode - may no longer apply, which is why the ETK plugin isn't impacting site privacy statuses.  Working on confirming that so we can move forward on this with the right next steps. _(i.e. If ETK is no longer tied to Coming Soon, then we need to disable that warning when deactivating the plugin while site is unlaunched)._

**Comment by cuemarie** [comment] 2023-07-24 20:19
Update! Found: https://github.com/Automattic/wp-calypso/pull/73249 // Internal: p9dueE-6jY-p2

Coming Soon is now built into `jetpack-mu-wpcom`, so it no longer relies on the ETK.  Thus, deactivating the plugin will have no impact on the site's privacy status.

📌 ACTIONS
- Closing as by design
- I'll submit a report about the privacy warning when the ETK plugin is deactivated so that we can get that removed, and share the link here.

**Closed as not planned by cuemarie** 2023-07-24 20:19 UTC
Labels: Bug, [Pri] Normal, Editing Toolkit, [Platform] Atomic

**Comment by cuemarie** [comment] 2023-07-24 20:25
New Issue: 

- https://github.com/Automattic/wp-calypso/issues/79804
