### ISSUE TITLE
SPT: Some blocks are invalid

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#46268] opened 2020-10-08 08:59 UTC
Some SPT (~Single~Starter Page Template) blocks are invalid and should be fixed.

#### Steps to reproduce

1. Load the SPT page editor for a Simple site: `/wp-admin/post-new.php?post_type=page`
1. Observe _block validation failure_ errors reported in the console.

You may want to filter console messages like `Block validation: Block validation failed for`

There appear to be two affected blocks:
- `core/embed` - rearranged classes and missing saved `wp-block-embed-youtube` class.
- `core/media-text` - rearranged classes

Example errors:

```
Block validation: Block validation failed for `core/embed` (Object).

Content generated by `save` function:

<figure class="wp-block-embed alignfull is-type-rich is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=pB5gaJloeRU
</div></figure>

Content retrieved from post body:

<figure class="wp-block-embed-youtube alignfull wp-block-embed is-type-rich wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=pB5gaJloeRU
</div></figure>
```
```
Block validation: Block validation failed for `core/media-text` (Object).

Content generated by `save` function:

<div class="wp-block-media-text alignfull is-stacked-on-mobile has-tertiary-background-color has-background"><figure class="wp-block-media-text__media"><a href="#"><img src="https://seedletdemo.files.wordpress.com/2020/08/plants_2x2.png?w=590" alt="" class="wp-image-201 size-full"/></a></figure><div class="wp-block-media-text__content"></div></div>

Content retrieved from post body:

<div class="wp-block-media-text alignfull is-stacked-on-mobile has-tertiary-background-color has-background"><figure class="wp-block-media-text__media"><a href="#"><img src="https://seedletdemo.files.wordpress.com/2020/08/plants_2x2.png?w=590" alt="" class="wp-image-201"/></a></figure><div class="wp-block-media-text__content">

</div></div>
```

There are many successful migrations which should be updated (https://github.com/Automattic/wp-calypso/issues/46269), but that's a lower priority issue with a different fix.

#### Context / Source

props: @fullofcaffeine (p1602108571422000-slack-C015AL3QL7M testin p7DVsv-9rP-p2)

**Comment by simison** [comment] 2020-10-08 09:19
How come Gutenberg doesn't migrate these blocks automatically? Is there transformation missing in core for `wp-block-embed-youtube` → `wp-block-embed is-provider-youtube`

**Comment by mattwiebe** [comment] 2020-10-08 21:13
> How come Gutenberg doesn't migrate these blocks automatically?

I'm not sure, but it sure is annoying!

I did not get finished, but I believe that we're in a good place for fixing these. Here are some things I learned:

1. SPT plugin loads the templates by calling the `templates` API endpoint, caches stuff, and inlines them, all from PHP. This makes trying to debug whether your changes are successful incredibly difficult. The fetching logic is [here](https://github.com/Automattic/wp-calypso/blob/4fabc36a42f2f1acc12849fc738a6c8ee36c41e0/apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/class-starter-page-templates.php#L205) and gets dumped on the page inside the `starterPageTemplatesConfig` JS var. There is no way that I can tell to test changes on a sandbox before deploying, as you can't sandbox the REST API from your sandbox itself.
2. The offending blocks appear to have been in the Portfolio layout (already updated on the master templates site), and also from the Seedlet and Leven. The Leven one is already deployed.

I am heading out for the weekend soon and don't feel comfortable deploying, but here's handing the baton with what needs doing.

1. Build and deploy the new SPT annotation file with instructions in p2-PCYsg-m0L (you only need to generate the JSON annotation file)
2. Build and deploy the Headstart annotation for the Leven theme
3. Translations are trickier. Nothing technically needs translating as this update will only change some markup. Probably just some tedious work in a text editor. 
2.

**Comment by ianstewart** [comment] 2020-10-08 21:22
> Build and deploy the Headstart annotation for the Leven theme

This part should be done, at least. :) I deployed it a few hours ago.

**Comment by autumnfjeld** [comment] 2020-10-09 06:30
Per my gardening goals, I tried to navigate through the path of block loading / block validation / Starter Page Templates if only to understand what this issue was about for my own learning.   

I believe I found the offending embed markup in the Portfolio template, or hopefully at least found something useful to share:
https://d.pr/i/Bl5jOL
https://d.pr/i/eT2Po8

@ianstewart Is it safe to assume this can be picked up by the View team?

**Comment by ianstewart** [comment] 2020-10-09 19:01
> the offending embed markup in the Portfolio template

That's been updated on the source site for that template, I believe. (I updated the page yesterday.) Wiebe's list above will still need working through, however.

cc @apeatling

**Comment by tjcafferkey** [comment] 2020-10-19 12:31
>1. Build and deploy the new SPT annotation file with instructions in PCYsg-m0L-p2 (you only need to generate the JSON annotation file). (You will not be able to test the new annotations for reasons detailed above. It *should* work.)

Done as part of code-D51261 although trying to verify it has worked is proving difficult? Smoke tests indicate no functionality has changed/broken though.

Is there a way to ensure I am not getting a cached response?

cc @ianstewart @mattwiebe

**Comment by noahtallen** [comment] 2020-10-19 18:56
> Is there a way to ensure I am not getting a cached response?

I think we might have to modify the PHP sourcecode in the editing toolkit and make sure that is synced to the sandbox

**Comment by mattwiebe** [comment] 2020-10-19 19:30
> Is there a way to ensure I am not getting a cached response?

If you the site is sandboxed and you have `WP_DEBUG` defined to true and have deployed the annotations, you should get fresh results. [Here's the code](https://github.com/Automattic/wp-calypso/blob/7488235c2d931d2f7aaa4f223eae5748fc1b226c/apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/class-starter-page-templates.php#L209) of interest.

**Comment by noahtallen** [comment] 2020-10-20 00:53
I spent most of my day on this issue. Here's where we're at.

I deployed code-D51261 to wpcom, and verified that we are seeing fewer block validation errors. Thanks for generating this @autumnfjeld!

Then, I noticed we had several other errors which I narrowed down to two themes. 

## Leven homepage

One is an issue with the columns block in the leven layout. Specifically, the homepage annotation includes an encoded space character, which is causing the block validation issue.

<img width="2063" alt="Screen Shot 2020-10-19 at 12 40 00 PM" src="https://user-images.githubusercontent.com/6265975/96526375-30b89500-1232-11eb-9bb2-842903ecaa33.png">

Here are the steps I took to fix that issue:
1. Removed the offending space character in the code editor of the leven theme demo site.
2. Regenerated the leven theme headstart annotation.
3. Tested, committed, and deployed the update to the leven theme. (D51444-code)
4. Reset the wp object cache for the leven theme's "homepage template" in the template-first-themes code.
5. Verified that I no longer see issues for the leven homepage block invalidation!

## Seedlet homepage

This leaves one final issue with the seedlet homepage:

<img width="2063" alt="Screen Shot 2020-10-19 at 12 36 35 PM" src="https://user-images.githubusercontent.com/6265975/96526502-9dcc2a80-1232-11eb-807f-2bc4751e387a.png">

Specifically, the problem is that the `media-text` block contains an attribute for a URL, which is set to the seedlet demo site. However, when the headstart annotation was generated, the URL was stripped from the HTML markup (and changed to `#`), but the URL was not changed in the accompanying block attribute. Basically, the block attribute and accompanying rendered HTML markup do not match. I found this out by comparing the _invalid_ text in SPT, and the apparently valid text in the seedlet demo site:

<img width="1404" alt="Screen Shot 2020-10-19 at 1 13 56 PM" src="https://user-images.githubusercontent.com/6265975/96526755-585c2d00-1233-11eb-9297-03b422feb348.png">

I thought originally this was an issue with the annotation generator, but after a lot of debugging, I accidentally realized that the seedlet annotation simply hasn't been updated in a while.

I generated the seedlet headstart annotation in this diff: D51460-code. If you look carefully, you'll notice that the generated markup for the homepage no longer contains the issue where the media-text attribute and the href are mismatched. I've confirmed that by pulling this annotation into the API endpoint, it fixes the issue in SPT.

## Next steps:

1. Get more eyeballs on D51460-code. Since there are a lot of unpublished changes, we should run this by the team responsible for the team.
2. Commit and deploy that diff.
3. Bust the cache for the seedlet homepage.

**Comment by noahtallen** [comment] 2020-10-20 18:34
I deployed D51460-code, and the cache is still referencing a correct version of the file, so I think we're good to go. If you are still experiencing issues, they will likely be resolved as the caches update over the next 24 hours. Let me know if you notice anything else!

I've just verified that there are no block validation errors in SPT any longer:

<img width="1689" alt="Screen Shot 2020-10-20 at 11 33 06 AM" src="https://user-images.githubusercontent.com/6265975/96629189-21842680-12c8-11eb-98f6-7d74e1f9c697.png">

**Closed by noahtallen** 2020-10-20 18:34 UTC
Labels: Blocks, Editing Toolkit, [Pri] High, [Type] Bug
