### ISSUE TITLE
Missing login screen when deep linking into Calypso

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/wp-calypso#30501] opened 2019-01-30 18:54 UTC
#### Steps to reproduce
1. Starting as a logged out WordPress.com user (incognito window is fine)
2. Go to URL: https://wordpress.com/themes/[any url] example: https://wordpress.com/themes/jesse.blog
3. You should see a nearly blank screen instead of the nicer login screen you'd see https://wordpress.com/stats/jesse.blog

#### What I expected
I expected to see a screen like this: 
![screen shot 2019-01-30 at 12 29 19 pm](https://user-images.githubusercontent.com/1749986/52004665-aba5af00-2495-11e9-9d13-b71ba4fc6685.png)

#### What happened instead
I got a screen that is essentially blank:
![screen shot 2019-01-30 at 11 50 38 am](https://user-images.githubusercontent.com/1749986/52004681-b3fdea00-2495-11e9-9694-3f1a77e62ec9.png)

#### Browser / OS version
All browsers, all devices/comps

#### Screenshot / Video
see above

#### Context / Source
JITMs, hosts, affiliates all deep link to Calypso.  Users will also likely bookmark Calypso pages, not to mention newsletters, and other emails that promote Calypso usage.  Most of these links are going to blank login screens.  We need to present the same login screen consistently no matter where the user is trying to deep link to. 

cc/ @johnHackworth @joanrho

**Comment by jsnajdr** [comment] 2019-02-01 11:52
Duplicate of #23785.
Has a fix PR in review: #30537.

**Closed by jsnajdr** 2019-02-01 11:52 UTC
