### ISSUE TITLE
Search Block - Reusable search block is not displayed fully in Edit mode. However it appears correctly in preview mode

### ISSUE THREAD

**Issue by sowmya2709** [Automattic/wp-calypso#52377] opened 2021-04-28 11:27 UTC
The reusable search block is not displayed fully in Edit mode. However, it appears correctly in preview mode

### Steps to reproduce the behavior

1. Create a search block with some features and add it to reusable block
2. Navigate to another section of the page add a reusable search block
3. Check-in Edit mode and in preview mode

#### What I expected to happen
I expect to see the added reusable search block in edit mode

#### What actually happened
In edit mode, I just see a blank block instead of a reusable search block. However, in preview mode the search block is visible.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://www.loom.com/share/0a1edc9b82504839ae3e23456327b1bc

**Comment by kosiew** [comment] 2021-05-27 06:40
Hi @sowmya2709 ,

Thanks for reporting this and the detailed steps.

I tested this with Gutenberg version 10.7.1 and could not reproduce this.

![Screenshot](https://d.pr/i/j5wDwz+)
*if image does not load, please click on this link  : https://d.pr/i/j5wDwz*

I am closing this.
If you are still encountering this, can you add more details for me to reproduce this.
Thanks.

**Closed as completed by kosiew** 2021-05-27 06:40 UTC
Labels: Bug, OSS Citizen, [Closed] Not Reproducible
