### ISSUE TITLE
Editor: geotagging not working, location doesn't display on front-end

### ISSUE THREAD

**Issue by eurello** [Automattic/wp-calypso#4099] opened 2016-03-16 22:42 UTC
The Geotagging feature is not currently functioning when added from Calypso on WordPress.com. To reproduce: 
1. Create a post in WP Admin and add a location. 
2. Post displays location: 

<img width="968" alt="screen shot 2016-03-16 at 4 39 33 pm" src="https://cloud.githubusercontent.com/assets/8698879/13830928/bc6e1c82-eb95-11e5-87a1-cb489445980f.png">
1. Create a post on the same site from Calypso, and add location. There is no real way to ensure the location is applied through the interface: 

<img width="1247" alt="screen shot 2016-03-16 at 4 36 05 pm" src="https://cloud.githubusercontent.com/assets/8698879/13830945/d28bf1a6-eb95-11e5-917f-ce815c995ec5.png">
1. Publish the post, no location data is displayed: 

<img width="895" alt="screen shot 2016-03-16 at 4 40 52 pm" src="https://cloud.githubusercontent.com/assets/8698879/13830951/dea260c4-eb95-11e5-9f5f-bf8fe658c0cb.png">

**Comment by eurello** [comment] 2016-03-22 16:05
Links to posts: 

https://eurellotest.wordpress.com/2016/03/16/geotag-test-calypso/
https://eurellotest.wordpress.com/2016/03/16/geotag-test-olddash/

**Comment by aduth** [comment] 2016-03-22 16:17
The metadata is correctly saved to the post, but is not exposed anywhere on the front-end because it lacks the meta indicating that the location should be publicly published. There are additional user settings which are not being considered in the Calypso editor for checking to see whether the geolocation should be made public.

In fact, this is likely related to 507-gh-io , as this could be processed with the post as it's saved to the REST API.

**Comment by obenland** [comment] 2016-03-24 16:05
I was about to report the same bug. For me it manifests itself differently though.

I have a preexisting post, tried to add a location, and it didn't show up on the front end:
![screen shot 2016-03-24 at 8 57 55 am](https://cloud.githubusercontent.com/assets/1398304/14022915/3484ad58-f19f-11e5-8752-494ee430ef75.png)

I then went into wp-admin where the location button just showed geo coordinates, not the name of the location:
![screen shot 2016-03-24 at 8 58 09 am](https://cloud.githubusercontent.com/assets/1398304/14022924/3c533568-f19f-11e5-99bc-6544821f2ad8.png)

Once I searched it again in wp-admin and saved, the location button showed the name of the location and it also showed up in the front-end.

http://konstantin.obenland.it/2016/03/23/point-vicente-lighthouse/

**Comment by lancewillett** [comment] 2016-04-07 17:49
Closed #1443 as a duplicate.

**Comment by aduth** [comment] 2016-04-07 20:46
My previous assessment turned out to be incorrect. Instead, it seems we're simply not accounting for posts being saved via the REST API instead of from wp-admin.

Two questions though:

- Where exactly does one manage their setting to share posts publicly by default? I'm having the hardest time finding this option.
- Should we just assume that posts saved with location data should have that location data shared publicly? Our [support documentation](https://en.support.wordpress.com/geotagging/) doesn't really do much to indicate that it'd ever not be public, and the feature doesn't seem very useful unless included in the front-end markup of the post.

**Comment by obenland** [comment] 2016-04-11 09:09
I don't know where to set that up either, but given that we've been showing this data historically I wouldn't be too concerned to continue doing so from Calypso.

**Comment by lancewillett** [comment] 2016-05-19 18:52
If we're still waiting on the questions above, might be worth a further discussion (say on an internal P2) to get more opinions on it.

**Comment by lancewillett** [comment] 2016-10-10 18:20
CC @supernovia as you mentioned Geo-tagging recently as not working equally in Calypso as it does in wp-admin.

**Comment by beaulebens** [comment] 2017-02-05 18:25
Related; this functionality should ideally be exposed for, and shipped with, Jetpack.

**Comment by formosattic** [comment] 2017-05-22 04:21
User recently asked about it in #3223210-t .

Also, some (kind of) recent internal discussion around Geotag/Location usage on p4hfux-1qy-p2 .

**Comment by kathrynwp** [comment] 2017-12-27 18:51
Another user report:

https://en.forums.wordpress.com/topic/showing-geotagged-location-in-the-post

**Comment by Robertght** [comment] 2018-03-13 13:25
Another user report: 1014356-zen

**Comment by lancewillett** [comment] 2018-07-24 21:06
Confirmed this is fixed with #24905 🎉 

Editing the location in post sidebar before publishing:
![screen shot 2018-07-24 at 14 05 27](https://user-images.githubusercontent.com/66797/43166162-b17429ce-8f4a-11e8-9924-22449a2075d8.png)

The location shows on the front-end now:
![screen shot 2018-07-24 at 14 05 17](https://user-images.githubusercontent.com/66797/43166167-b62d1de0-8f4a-11e8-8789-f4f4322cc9e3.png)

**Closed by lancewillett** 2018-07-24 21:06 UTC
Labels: Editor, [Pri] High, [Type] Bug

**Comment by obenland** [comment] 2018-07-24 21:37
w00t!

**Comment by lancewillett** [comment] 2018-08-06 17:34
Noticed when prompted to upgrade to a Business plan, I got an AT warning message:

<img src="https://user-images.githubusercontent.com/66797/43731706-57ad7ebc-997d-11e8-8d32-21c67ff09a15.png" width="480" />

Now that geolocation is supported we should remove this particular warning, CC @jhnstn / @Automattic/atomic
