### ISSUE TITLE
Editor: Image thumbnails don't appear in editor

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#12620] opened 2017-03-29 11:23 UTC
When adding image(s) to a post, there is no visible thumbnail of the image(s), only the image titles show up. However, the single image/gallery is visible when viewing the post on the actual site.   To see the images while editing the post, one must save the draft and reload the page a couple times.

Unfortunately, I am unable to reproduce the issue at the moment, although there were multiple user reports earlier.

#### Browser / OS version
Issue appeared on Chrome, Firefox, and Safari.

#### Screenshot / Video
<img width="778" alt="imageuploaded" src="https://cloud.githubusercontent.com/assets/11635760/24452170/83eaaaf8-14b4-11e7-9574-0ee0e6a2b4bf.png">

#user-report

**Comment by SiobhyB** [comment] 2017-03-29 12:37
Thanks for posting this @vparkhere! My user's details can be found in 273667-hc and 3135237-t.

They were able to replicate the issue in both Firefox and Safari.

I wasn't able to replicate while chatting with the user but have since been able to reproduce in Chrome by following the steps to upload a new image, in this screencast:

![images](https://cloud.githubusercontent.com/assets/2998162/24454691/b2ea4ad2-1484-11e7-9685-6dae045f039d.gif)

You'll see from the screencast that the image appears broken in the editor but that it's visible when the post is previewed.

**Comment by ehti** [comment] 2017-03-29 14:38
Another report in #274220-hc

**Comment by cecilerainon** [comment] 2017-03-30 14:49
Another report in #3134580-t

**Comment by laurelfulford** [comment] 2017-03-31 22:22
Another report in #274183-hc (follow up #3135807-t).

**Comment by designsimply** [comment] 2017-04-06 22:24
Closing because I checked the user reports noted on this thread and they all say the issue has been resolved. 

(internal ref: r153651-wpcom)

**Closed by designsimply** 2017-04-06 22:24 UTC
Labels: Editor, [Pri] High, [Type] Bug
