### ISSUE TITLE
Atomic sites are not using WordPress.com translations for Gutenberg

### ISSUE THREAD

**Issue by guicmazeredo** [Automattic/wp-calypso#29309] opened 2018-12-11 14:23 UTC
#### Steps to reproduce
1. Change a site's language to anything different from English (e.g. French). 
2. Edit an existing page/post or add a new one and add a block.
3. Check the Blocks Settings Sidebar or the Block interface and you'll notice that not everything is translated.  

#### What I expected

If Gutenberg blocks are translated on WordPress.com translations I expected to see the interface translated like we do for Simple Sites. It's pretty weird for a user that had everything translated on their simple site and once they get their site AT'd the blocks are not translated anymore. 

#### What happened instead

It would be great to use WordPress.com translations on Atomic sites for consistency. 

#### Context / Source

This was reported here:
p1544532027263400-slack-gutengroup-wpcomhappy

**Comment by vindl** [comment] 2018-12-11 16:58
@kwight I vaguely remember us fixing the translations for Calypsoify before. Any ideas why this might not be working for Atomic sites?

**Comment by kwight** [comment] 2018-12-11 17:56
I don't know if Atomic/Jetpack was part of all that, I think more testing is needed first to narrow down exactly what parts are involved (eg. parts of the sidebar come from different API calls).

**Comment by vindl** [comment] 2018-12-11 18:10
@akirk any ideas why this might be happening? Are there any known issues with wp-admin translations on Atomic sites?
/cc @Automattic/atomic

**Comment by jeherve** [comment] 2018-12-12 09:12
This seems to be a duplicate of #29244

**Comment by guicmazeredo** [comment] 2018-12-12 17:31
I'm not sure if they are related. It looks like the issue #29244 is related to the Jetpack blocks only and it was also occurring in Simple Sites. This one is happening with all blocks and is only occurring in Atomic sites.

**Comment by akirk** [comment] 2018-12-13 12:04
It looks like this patch for Core, scheduled for 5.0.2, will resolve this: https://core.trac.wordpress.org/ticket/45528

**Comment by akirk** [comment] 2018-12-13 12:33
See p9o2xV-cH-p2 for more details.

**Closed** 2018-12-18 13:14 UTC
Labels: Atomic, [Goal] Gutenberg, [Pri] High, [Type] Bug, wp-admin

**Comment by pratikawari28** [comment] 2018-12-19 17:34
Got a user in chat reporting this issue in Japanese language: hc-8783842
It's an AT site - wellvill.com
Follow-up here : zen-1656223
Reference screenshot here : http://cld.wthms.co/Z3QIRR

**Comment by jeherve** [comment] 2018-12-19 17:44
@pratikawari28 The issue will be fixed once both WordPress and Jetpack are updated (WP 5.0.2 on one hand, Jetpack 6.9 on the other).

While WP 5.0.2 should be released very soon, Jetpack 6.9 won't be released until January 10. 

If the site owner would like to apply the work-around on their site sooner, they can do so thanks to [the Jetpack Beta plugin](http://jetpack.com/beta) and by searching and using this PR in Jetpack > Beta once the Beta plugin is installed: 
https://github.com/Automattic/jetpack/pull/10982
