### ISSUE TITLE
Editor: Cannot scroll while drag-and-dropping images within a post

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/wp-calypso#10418] opened 2017-01-05 01:42 UTC
Images can be drag-and-dropped to change their location with a post, but only if it doesn't require scrolling.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/$site
2. Add media, insert several images using the "Individual Images option"
3. Select an image further down the post and attempt to drag-and-drop it at the top of the post
4. Notice you cannot drag the image any further than the amount of post that is available, the post will not scroll up.

#### What I expected

As I drag the image up and down the post, the scroll bar should scroll up/down and allow me to drag the image to any location on the post and drop it

#### What happened instead

I can drag the post and drop it within the amount of space I can see without scrolling, but not scrolling will happen.

#### Browser / OS version
Replicated on Chrome/macOS and Firefox/macOS

#### Screenshot / Video
https://cloudup.com/cykdRowCxJA

#### Context / Source

This may not break the editor as a whole, but can certainly break some folks' workflows. In 570825-chat a user would drag-and-drop in this manner previously but seems to not be available anymore.

In the context of a photographer with 100 images in a post, trying to tell a story, they may want to drag and test out the images in a variety spots in a way that cut+paste would be cumbersome.

**Comment by hoverduck** [comment] 2017-01-05 16:24
Related (possibly duplicate) - https://github.com/Automattic/wp-calypso/issues/10237

**Comment by lancewillett** [comment] 2017-01-16 22:47
Closed as a duplicate of #10237

**Closed by lancewillett** 2017-01-16 22:47 UTC
Labels: Editor, Media, [Type] Bug
