### ISSUE TITLE
Editing Text in Widgets Results in Jumps

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#20781] opened 2017-12-13 16:23 UTC
Originally reported in https://github.com/wordpress-mobile/AztecEditor-iOS/issues/851#issuecomment-350811122

But it's not app behavior. It appears to be Calypso.

Expected behavior

When editing a widget (ex: adding an address to a contact widget) one could tap in the box and edit the text.
Actual behavior

The cursor jumps around as if there is a calibration error.
Steps to reproduce the behavior

Go to Widgets in Customizer and attempt to edit a widget such as the Contact Info & Map Widget
Original issue and screencast from #244974-h on https://cloudup.com/c8nrbgbIwsd

Screencasts from Customizer and from Browser on

https://cloudup.com/cs12cKkHr4W  

Replicated on [iPhone SE], iOS [11.1.2], Aztec [8.9]

**Comment by designsimply** [comment] 2017-12-14 01:17
I tested using Calypso in Chrome 63.0.3239.84 on Mac OS X 10.13.1 and was unable to reproduce the problem there. Because of this, I think this issue may need to move to https://github.com/wordpress-mobile/WordPress-iOS/

**Comment by designsimply** [comment] 2017-12-14 01:33
I also tested with Safari on iPhone 6S, iOS 11.2.1 and couldn't see the same problem happen there either. (p4k3M4-2uR-p2)

**Comment by designsimply** [comment] 2017-12-14 01:44
I tested with iPhone 6S, iOS 11.2.1, WPiOS 9.0.0.20171213 and was unable to reproduce the issue in the app using the following steps:

1. Start from the WPiOS app using a site that has several widgets in a sidebar area already.
1. Go to My Site > Themes > Customize > Widgets > Add a Widget.
1. Add a contact widget or a text widget.
1. Try to type into the text areas.

<strong>Result:</strong> I was able to type into text areas in widgets without any problems and without the app jiggering.

<strong>Video:</strong> [2m53s](https://cloudup.com/cEzxGa5A1pZ)

@ChrissiePollock if you are able to reliably reproduce the problem, could you have a look at the steps/video above and let me know if you're doing something different in your testing compared to mine?

**Comment by ChrissiePollock** [comment] 2017-12-16 19:58
@designsimply I can very reliably reproduce the issue. The only step that I have different from you is the fact that I am editing information on a widget that is already in the Customize widget area. 

Here is my most current screen recording in which you can see the cursor is not aligning, nor are all the letters I type reflected: https://automattic.helpshift.com/admin/issue/246647/

I tried this in wifi as well as 3g with the same result. iOS 11.2.1; iPhone SE; WordPress app version 8.9

**Comment by lancewillett** [comment] 2018-07-24 20:51
Closing this one due to low priority and the fact that Customizer isn't part of Calypso (it loads from WP Admin).

**Closed by lancewillett** 2018-07-24 20:51 UTC
Labels: Customizer, [Type] Bug
