### ISSUE TITLE
Classic Editor & Block - Media Library keeps reloading when trying to add a new image to a post/page

### ISSUE THREAD

**Issue by StefZarb** [Automattic/wp-calypso#34464] opened 2019-07-04 14:41 UTC
#### Steps to reproduce
1. Starting at URL: WordPress.com/posts
2. Add a new post or edit an existing one
3. Create a new Classic Block (or use the Classic Editor as primary editor) and select Add Media
4. Select an Image 

#### What I expected
To be able to add an image to a post/page. 

#### What happened instead
The Media Library keeps reloading as you scroll.
#### Browser / OS version
Chrome v.75
Firefox v.67

#### Screenshot / Video

https://monosnap.com/file/dAkBnIw6UQvSMOGyAW6iPtQScTqim0

#### Context / Source

Reported in 13800802-hc
#user-report

**Comment by nickpagz** [comment] 2019-07-04 15:23
Also saw this in this ticket:
#2155011-zen

Was able to replicate when SSP'd to the user's account. They have the classic editor enabled, and this happened in Calypso, but worked fine in wp-admin.

https://cld.wthms.co/GHaA8W

And was able to replicate on a test site with Gutenberg active, but using a Classic block.

**Comment by tijosh** [comment] 2019-07-04 17:31
User reported a similar issue in #4453066-hc

They said that they couldn't add a Featured Image:

> When I click on the "featured Image" on the right side of the page, instead of linking me to my media and photos to select an image, all that I get is a horizontal line in that box.  I can't do anything with it.  

I started a Support Session for the user and then tried adding a Featured Image to new blank post in Calypso. The behavior outlined above in the other comments was replicated.

I directed the user to add a Featured Image via WP Admin

**Comment by guicmazeredo** [comment] 2019-07-04 18:02
Another report: #2155008-zen

**Comment by ashercantrell** [comment] 2019-07-04 19:15
Report here: https://mc.a8c.com/support-stats/happychat/transcript.php?id=196826

This was also happening to @cesarabeid during our team meeting today

**Comment by jeremyb1** [comment] 2019-07-04 19:22
Also happening here, from forums: [post-3334527](https://en.forums.wordpress.com/topic/unable-to-scroll-my-existing-blog-media-to-insert-into-blog/#post-3334527)

**Comment by scosgro** [comment] 2019-07-04 19:28
Also happening in #10219740-hc in the Block Editor with a Gallery Block. 

.gif here: https://cloudup.com/cGFv5tlFzzA

**Comment by jeremyb1** [comment] 2019-07-04 19:31
One more from my day today: 2155832-zen

**Comment by TeniCola** [comment] 2019-07-04 19:45
Another one from today, after the user switched browsers and cleared their cache: HC-13809024

**Comment by cesarabeid** [comment] 2019-07-04 19:48
Also seeing this in p2s: https://d.pr/v/pEmDup

**Comment by scosgro** [comment] 2019-07-04 19:56
Another one in #13793282-hc

**Comment by katiebethbrown** [comment] 2019-07-04 20:12
Another report in #2155819-zen

**Comment by tijosh** [comment] 2019-07-04 20:47
Another one in #13810041-hc

**Comment by kwight** [comment] 2019-07-04 21:04
This may have been caused by the merge of #33705 cc/ @donpark. Investigating.

**Comment by kwight** [comment] 2019-07-04 21:19
https://github.com/Automattic/wp-calypso/pull/34468 may be our revert fix for this.

**Comment by tbradsha** [comment] 2019-07-04 21:34
#8890520-hc

**Comment by kwight** [comment] 2019-07-04 21:37
#34468 is deployed now; feel free to reopen if users are still seeing this after a browser reload.

**Closed by kwight** 2019-07-04 21:37 UTC
Labels: [Type] Bug
