### ISSUE TITLE
FSE versions of Newspack blocks not working when Newspack plugin is active

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#41530] opened 2020-04-28 10:09 UTC
While wanting to compare the new Posts Carousel block side by side to its Newspack block counterpart, I noticed that currently, it's not possible to have both active at the same time. I'm not sure whether this is a bug or by design. I'd assume we'd want both to work alongside each other?

#### Steps to reproduce

1. Add FSE plugin
2. Create a post and add Posts Carousel block
3. Add Newspack plugin
4. Add Article Carousel block to the same post
5. Observe Posts Carousel block not working anymore

#### Screenshot / Video

<img width="816" alt="Screenshot 2020-04-28 at 11 55 43" src="https://user-images.githubusercontent.com/1562646/80475368-110e7700-8949-11ea-8a1b-3812ad6dec5a.png">

**Comment by obenland** [comment] 2020-04-28 16:28
It's by design since the two plugins use the same PHP constants with different values.
Introduced in https://github.com/Automattic/wp-calypso/pull/39208

Is there an instance where we'd expect both being active at the same time?

**Comment by obenland** [comment] 2020-07-16 15:36
Let's close this one, we're actively preventing both plugins from being active at the same time

**Closed by obenland** 2020-07-16 15:36 UTC
Labels: [Goal] Full Site Editing, [Type] Bug
