### ISSUE TITLE
Reader: regression in Conversations when expanding comments

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#79212] opened 2023-07-11 02:33 UTC
### Quick summary

In /read/conversations, you can click 'Read More' to expand comment threads.

This still expands the comment thread, but also navigates you to the full post view for the parent post, which is unexpected.

### Steps to reproduce

1. Start at https://wordpress.com/read/conversations.
2. Find a conversation with nested comments (you might need to follow a new post to do this).
3. Click 'Read More' to expand a longer comment.

### What you expected to happen

The comments are expanded in-place.

### What actually happened

I unexpectedly navigate to the full post view of the page.

If I return to the Conversations view, the comments are expanded.

![2023-07-11 14 32 14](https://github.com/Automattic/wp-calypso/assets/17325/1b2225fb-1ad6-4ec0-9466-4c34d30ae875)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment] 2023-07-12 21:47
Duplicate of https://github.com/Automattic/wp-calypso/issues/78677

**Closed as not planned by cuemarie** 2023-07-12 21:47 UTC
Labels: Bug, [Pri] Normal, [Feature] Reader, Triaged
