### ISSUE TITLE
Twenty Eleven: Image Block caption color is white in Gutenberg

### ISSUE THREAD

**Issue by joashrajin** [Automattic/wp-calypso#53403] opened 2021-06-04 09:55 UTC
This might be fixed in https://github.com/WordPress/gutenberg/pull/28233, but I am reporting it here in case it isn't

### Steps to reproduce the behaviour

1. Create a new page and add an Image Block, then add an image to it
2. You should then notice that the caption has this CSS Code applied to it in the editor: 
```
.is-dark-theme .wp-block-image figcaption {
    color: hsla(0,0%,100%,.65);
}
```
3. On the frontend, the colour is correct

#### What I expected to happen
The caption colour should be dark (same as the frontend)

#### What actually happened
The caption is white in the editor

#### Browser / OS version
Chrome version 91.0.4472.77 / MacOS 11.4

#### Is this specific to the applied theme? Which one?
Twenty Eleven

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Gutenberg: 
![image](https://user-images.githubusercontent.com/16253818/120783648-84f75780-c52b-11eb-9f0c-1d2113676be9.png)

Front-end: 
![image](https://user-images.githubusercontent.com/16253818/120783771-a6f0da00-c52b-11eb-94cc-d2b0744e2027.png)

4042145-zd-woothemes

**Comment by syds87** [comment] 2021-06-04 16:23
A similar case seems to be happening on 29394749-HC with a different theme (Gema)

**Comment by ericamQA** [comment] 2021-06-04 16:51
Reproduced. Tested on a few other themes too and, even on a dark background, the same problem didn't happen in themes I tested with, other than TwentyEleven.

**Comment by khristiansnyder** [comment] 2021-06-07 09:46
Just came across this on an AT site and the **Gazette** theme. Image block captions are white in the editor against a white background.

**Comment by nagpai** [comment] 2021-06-08 02:07
Another user report 
#1067377-hc

Asked user to edit captions using HTML mode as  a workaround while this is being fixed.

**Comment by marutim** [comment] 2021-06-09 05:02
Another user report here: 28733500-hc

**Comment by marutim** [comment] 2021-06-09 10:38
Another report here: 29868273-hc

**Comment by mrsjaved** [comment] 2021-06-11 14:55
Another similar issue:
4061336-zd-woothemes

The theme customer is using is Gema and TextBook.

**Comment by formosattic** [comment] 2021-06-13 22:42
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/53422

**Closed as completed by formosattic** 2021-06-13 22:42 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Normal, [Feature Group] Support, Triaged
