### ISSUE TITLE
Mailchimp block: adding block to page without list still renders the form

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#30845] opened 2019-02-18 09:54 UTC
It's possible to add Mailchimp block to editor, not reconnect and get it visible at the view side.

Submitting that form will then just render an error.

I expected view side not to render at all or render admin-only _"this block needs to be connected"_ -type message.

<img width="739" alt="image" src="https://user-images.githubusercontent.com/87168/52942406-9f659100-3373-11e9-96c1-8dd7507f213a.png">

<img width="620" alt="image" src="https://user-images.githubusercontent.com/87168/52942582-e8b5e080-3373-11e9-92c5-f1e88c9d7594.png">

<img width="414" alt="image" src="https://user-images.githubusercontent.com/87168/52942426-aab8bc80-3373-11e9-86dc-1bbcd811ded5.png">

<img width="594" alt="image" src="https://user-images.githubusercontent.com/87168/52942462-b7d5ab80-3373-11e9-834c-162c21bfb8cb.png">

**Comment by simison** [comment] 2019-02-18 09:55
I didn't check what happens when you first insert functioning form and then disconnect it from wp.com admin — same as here?

**Comment by jeffersonrabb** [comment] 2019-02-19 15:36
Close to a dupe of https://github.com/Automattic/jetpack/issues/11290? Should be resolved in https://github.com/Automattic/jetpack/pull/11377.

**Comment by jeffersonrabb** [comment] 2019-02-20 14:30
This should now be resolved in https://github.com/Automattic/jetpack/pull/11377. Just to be sure I've understood this issue correctly could you verify that this is resolved before closing?

**Comment by simison** [comment] 2019-02-20 14:52
>Just to be sure I've understood this issue correctly

So I had connected to mailchimp but just had not chosen the list from the dropdown. I will have time to test tomorrow if you'd like.

**Comment by scruffian** [comment] 2019-02-28 13:42
I've tested:
- a site with no connection
- a site with a connection but no list connected
- a site which had a connection that I disconnected

In no case did I see the block displayed. Closing.

**Closed by scruffian** 2019-02-28 13:42 UTC
Labels: Mailchimp, [Goal] Gutenberg, [Type] Bug
