### ISSUE TITLE
Front-End Toolbar: Mobile Safari Icons Misaligned

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#47386] opened 2020-11-12 19:21 UTC
It appears that our front-end toolbar is responding incorrectly in mobile Safari. With icons seemingly randomly placed.

![image](https://user-images.githubusercontent.com/545779/98985820-b6ee9100-24e9-11eb-9541-f4c6a2760e28.png)

Here's a closer look. The red boxes are all the same size.

![image](https://user-images.githubusercontent.com/545779/98985941-dd143100-24e9-11eb-959b-84f225609d5a.png)

**Comment by obenland** [comment] 2020-11-17 23:32
@frontdevde Could you help me recall if this ticket was supposed to be moved to the Janitor board or closed as a duplicate of a ticket there? I can't seem to find a duplicate right now.

**Comment by frontdevde** [comment] 2020-11-19 08:44
I remember seeing this as an issue re: spacing in the masterbar similar to this during the first Janitor rotation. IIRC it was reported by Lance a long time ago. That said, I can't seem to find it on the Janitor board (anymore). So let's keep it as an issue and add it to the Janitor board.

**Comment by ianstewart** [comment] 2020-12-15 22:06
It appears to have taken on a new form that is looking broken on mobile in a new way now.

![image](https://user-images.githubusercontent.com/545779/102278530-9c944280-3eef-11eb-9584-f378beac38b7.png)

**Comment by sixhours** [comment] 2020-12-16 18:13
It's broken in Chrome, too: 
<img width="381" alt="Screen Shot 2020-12-16 at 1 13 13 PM" src="https://user-images.githubusercontent.com/2124984/102388966-7f6b7c80-3fa0-11eb-9264-187eaa343bb8.png">

**Comment by sixhours** [comment] 2020-12-16 18:39
Looks like this may have been partially broken in D44873-code where we're setting 54px of left padding on the admin container to accommodate the hamburger menu in the editor on mobile.

But I don't see a hamburger menu on mobile in the editor any more, nor do I see the admin bar (although there are plenty of layout problems in the editor toolbar on mobile...):

Atomic
<img width="328" alt="Screen Shot 2020-12-16 at 1 33 20 PM" src="https://user-images.githubusercontent.com/2124984/102391278-7f20b080-3fa3-11eb-8472-e89ed353c2e4.png">

Simple
<img width="340" alt="Screen Shot 2020-12-16 at 1 33 55 PM" src="https://user-images.githubusercontent.com/2124984/102391281-7f20b080-3fa3-11eb-94db-3bda33f15c00.png">

@yansern Do you happen to know if the hamburger menu has been removed from the masterbar since this change was made back in March? Is it safe to remove the left padding fix? If not, I'll look at making the rule more specific...

**Comment by obenland** [comment] 2021-01-29 23:13
@yansern @sixhours Any chance you could take another look at this?

**Comment by yansern** [comment] 2021-02-01 10:49
> @yansern Do you happen to know if the hamburger menu has been removed from the masterbar since this change was made back in March?

I don't think the hamburger menu has been removed from the masterbar (as in the masterbar with the black background, right?) as from a recent PR (on Gutenberg) I see it is there https://github.com/WordPress/gutenberg/pull/28526.

> Is it safe to remove the left padding fix? If not, I'll look at making the rule more specific...

I think perhaps old fix do not apply to new ones. It's most likely there are changes over time and probably would be easier to apply a new fix that works and keeping old ones in.

(This is just a quick reply, I'll take a look a little deeper and post an update again as I'm on gardening rotation now.)

**Comment by sixhours** [comment] 2021-04-06 18:56
This might be fixed by D59796-code

**Comment by cuemarie** [comment] 2023-06-29 23:46
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
Quite a bit of time has past since this was last updated, and things are looking good on mobile Safari!  

**My Home**
![IMG_FC8B4D9D31CE-1](https://github.com/Automattic/wp-calypso/assets/27249804/490526fd-e060-445a-a4dd-8be1a31682a7)

**Post Editor**
![IMG_A3D961D324C8-1](https://github.com/Automattic/wp-calypso/assets/27249804/05dfa512-f593-490c-8ea4-2c11d93db3bd)

📌 ACTIONS
- Closing as resolved

**Closed by cuemarie** 2023-06-29 23:46 UTC
Labels: [Type] Bug, [Pri] Low, [Browser] Safari
