### ISSUE TITLE
Gutenberg: fix media upload on chrome in dev environments (requests are cancelled by the browser)

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27497] opened 2018-09-28 19:33 UTC
As a follow up to #27485 @Copons discovered that we can upload media on Chrome to production environments but not local ones.

On a local dev instance, Chrome (but not other browsers) appear to be cancelling the request immediately in the browser. This may be due to security or CORS issues.

> There might be something going on with file uploads on our dev environments that is not related to this change in particular.
I've tried uploading an image in /media (which uses WP.COM 1.1) and it doesn't work as well locally and on live (although, it works on wpcalypso and stage).

<img width="842" alt="46216894-7ac33b00-c338-11e8-88cc-a07b27ba0bc5" src="https://user-images.githubusercontent.com/1270189/46229612-0a59f100-c31b-11e8-85f6-51451b391053.png">

To reproduce this behavior
- npm start
- visit /gutenberg
- select a site
- insert an image block, and select a file to upload
Expected: the image is uploaded
Actual: A transient image is shown, and the upload request is immediately cancelled in the browser.

cc @mdawaffe if you had any ideas 🤔

**Comment by gwwar** [comment] 2018-09-28 22:32
Thanks @mdawaffe we'll give that a try ✨

**Comment by dmsnell** [comment] 2018-10-05 15:59
Just a quick note: somebody was working on local HTTPS dev for Calypso, might be related

see: https://a8c.slack.com/archives/C03DY3RJ5/p1538684802000100

**Comment by sirreal** [comment] 2018-10-05 16:08
Linking HTTPS PR: #27271

**Comment by vindl** [comment] 2018-12-19 11:59
Closing since this issue is no longer reproducible.

**Closed by vindl** 2018-12-19 11:59 UTC
Labels: [Goal] Gutenberg, [Type] Bug
