### ISSUE TITLE
Selecting different Heading font in Styles causes Editor to crash

### ISSUE THREAD

**Issue by radtechgh** [Automattic/wp-calypso#94033] opened 2024-08-29 18:31 UTC
### Quick summary

Site editor crashes when selecting different font for Headings in Styles

### Steps to reproduce

1. Personal test site
2. installed Pendant theme
3. browse to Editor, then Styles. 
4. Was given the option to Try Styles (normally requires Premium or above).
5. Drilled down into Styles to Headings.
6. Selected H1.
7. Fonts, select any other font.
8. Editor crashed with error: The editor has encountered an unexpected error.

### What you expected to happen

I expected the font to change to the selected font, and be usable.

### What actually happened

Editor crashed. Unable to continue.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by radtechgh** [comment] 2024-08-29 18:36
8665499-zen

**Comment by Imran92** [comment] 2024-08-29 20:33
📌 REPRODUCTION RESULTS

I can reproduce.

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/user-attachments/assets/bd357e0e-ae2a-41f2-bbe1-9076e2e743ca

**Comment by annezazu** [comment] 2024-08-29 21:17
I can't replicate this on nomad.blog:

https://github.com/user-attachments/assets/f916d09b-6a9e-4b6e-b56a-780566f8b90d

To be safe, adding to the connecting the dots board but would be curious to see if more can replicate and what the environment is.

**Comment by Imran92** [comment] 2024-08-29 21:23
Hi @annezazu 👋 I've found the underlying reason and a fix too. I'm just giving it a final check, but looks like the fix will be on Gutenberg, in which case I'll move the issue to that repo.

To reproduce it, you need to
- Install the Pendant theme
- Go to the site editor
- Select "Styles" on the left side panel
- Select the Dark Navy or the Pink style
- Then go to Typography -> Headings -> Select H1

I'll add these instructions in my comment above as well

**Comment by annezazu** [comment] 2024-08-29 22:29
@Imran92 thank you for following up! Can you point me to where the fix is on Gutenberg exactly? That would be great to cross connect.

**Comment by annezazu** [comment] 2024-08-30 21:48
Please always cross connect the issues opened: https://github.com/WordPress/gutenberg/issues/64952

**Comment by Imran92** [comment] 2024-08-30 22:40
Thanks @annezazu !

Here's the update about this issue-

This was actually a Gutenberg issue. So created one there - https://github.com/WordPress/gutenberg/issues/64952

I've also published PR with a fix for it - https://github.com/WordPress/gutenberg/pull/64953

Closing it on calypso now in favor of the GB issue.

**Closed as completed by Imran92** 2024-08-30 22:40 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] High, Needs triage, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Feature] Global Styles, [Status] Priority Review Triggered, [Product] WordPress.com, Groundskeeping
