### ISSUE TITLE
Reader Stream Refresh: Embedded SoundCloud widget not displayed in card

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#9414] opened 2016-11-16 05:39 UTC
Reported by @alisterscott:

> For posts with an embedded SoundCloud widget, this no longer appears in the stream (you need to drill into the post to see it)

![screenshot 2016-11-15 21 39 29](https://cloud.githubusercontent.com/assets/4924246/20336017/ff03f41c-ab7b-11e6-8262-aabd265f1662.png)

**Comment by blowery** [comment] 2016-11-16 14:26
For reference, this was an active decision to keep iframes out of the stream, as iframes do bad things to overall browser performance, especially when scrolling.

**Comment by bluefuton** [comment] 2017-01-11 08:30
Could we give this a similar treatment to the one we've given Youtube and Vimeo videos @samouri?

**Comment by samouri** [comment] 2017-01-12 14:37
@bluefuton that would be my vote! I think @fraying had some feelings on this

**Comment by fraying** [comment] 2017-01-12 17:33
Indeed I do! And the are ... This is not a bug. This is as designed. 

Do we need click-to-display things for audio like we have for video? Maybe. But it's a much lower priority than the rest of the things on this list that I think we should close this bug for now. Also, if we go this route, I think the design needs to communicate the difference between audio and video, so there's more work to do here.

**Closed** 2017-01-12 17:33 UTC
Labels: Reader, [Type] Bug
