### ISSUE TITLE
FSE Beta: Upgrade Nudge on Cover Blocks Breaks Layout in Site Editor

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#59501] opened 2021-12-22 18:33 UTC
### Quick summary

There's an upgrade nudge on Cover blocks shown only in the Site Editor.

### Steps to reproduce

1. Use a test site on a Free plan
2. Activate a theme and choose to have the homepage set with its content
3. Open the Site Editor

### What you expected to happen

To see in the editor the content as it shows on the live site.

### What actually happened

It shows an upgrade nudge on every Cover block you have on the page.

### Context

This doesn't happen if you edit the page through the Pages menu, but this is what you get in the Site Editor:

![CoverBlockUpgradeNudge](https://user-images.githubusercontent.com/16104522/147139047-93114808-677f-49c1-9113-38d69e5d0a14.jpg)

Sometimes the nudge changes the layout quite a bit, here's an example with the theme's content (with Quadrat):

![CoverBlockUpgradeNudge2](https://user-images.githubusercontent.com/16104522/147139094-dd2d9e9a-dc3d-4f57-93be-081be29863e4.jpg)

**Comment by formosattic** [comment] 2021-12-28 08:58
Looks like this is already fixed. I'm unable to reproduce.

![troubleshooting](https://user-images.githubusercontent.com/15944096/147547820-89d63393-54c3-4381-9674-b42cc982a2aa.gif)

Closing, but open if it happens again.

**Comment by carinapilar** [comment] 2021-12-28 09:11
I can still replicate this, I'm testing on a Simple free site. I followed the steps below now:

1. I have Quadrat White now.
2. Created a new page with a Cover block.
3. Set that new page as the site's homepage.
4. Open the Site Editor from Appearance.

And this is what I get:

![CoverNudge](https://user-images.githubusercontent.com/16104522/147549477-56ec2519-affd-4416-96a8-f171be01ab97.jpg)

**Comment by formosattic** [comment] 2021-12-28 10:08
Thanks @carinapilar!

I removed the Premium plan on my test site, and was able to see all the upsell nudges.

I updated the steps in the initial post to include the "Free plan" requirement.

**Comment by simison** [comment] 2022-01-28 12:22
Happening with "Blank" option when creating a new FSE site via https://horizon.wordpress.com/start/domains

![image](https://user-images.githubusercontent.com/87168/151546184-eb8432ee-fff3-4a3a-80df-5a8e49b6af9e.png)

**Closed as completed** 2022-02-09 16:29 UTC
Labels: Bug, [Pri] High
