### ISSUE TITLE
FSE Round 3 Alpha test - Applying Background Color to Heading Block affects the width of text area.

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#51939] opened 2021-04-14 11:54 UTC
### Steps to reproduce the behavior

1. Add a Heading Block.
2. Enter some text/ 
3. Apply Background Color to the Heading Block.
4. The width of the text area is affected.

#### What I expected to happen

Applying Background Color should not affect the width of the text area

#### What actually happened

The width of the text area was changed.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://d.pr/i/oUNcye

**Comment by jeyip** [comment] 2021-11-06 01:03
Can reproduce this on dotcom simple sites and core Gutenberg, although it only affects the editor and _not_ the frontend. I think priority should be normal or low because of this.

@creativecoder @zaguiini

**Comment by jeyip** [comment] 2021-11-17 20:46
I did some digging, and it appears as if this behavior is intentional.

<img width="1868" alt="Screen Shot 2021-11-17 at 12 37 17 PM" src="https://user-images.githubusercontent.com/5414230/142278668-65460904-cb42-484a-94ae-5878bccf9c68.png">

The styling in Gutenberg source code automatically applies padding for blocks with a `.has-background` classname. [Take the list block as an example](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/list/style.scss#L6-L8):

```
// packages/block-library/src/list/style.scss

ol,
ul {
	// Break long strings of text without spaces so they don't overflow the block.
	overflow-wrap: break-word;

	&.has-background {
		padding: $block-bg-padding--v $block-bg-padding--h;
	}
}
```

I'm going to move this issue over to the core Gutenberg repo to see if they have thoughts about this. I understand how this might have been convenient for the block-editor, but now that we're dealing with site structure in the site editor, the mysterious padding and jumping content warrants discussion.

**Comment by jeyip** [comment] 2021-11-17 22:58
Closing this in favor of https://github.com/WordPress/gutenberg/issues/36586

**Closed as completed by jeyip** 2021-11-17 22:58 UTC
Labels: Bug, [Pri] Normal, [Goal] Full Site Editing
