### ISSUE TITLE
Import Stats icons to Gridicons repo

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#69495] opened 2022-10-26 23:34 UTC
This task is a follow-up related to #69311.

- Import new Stats icons in the Design to the [Gridicon repository](https://github.com/Automattic/gridicons). (**UPDATED**: Temporarily shelved)
- Transform the tooltip items text case to align with the Design.

![image](https://user-images.githubusercontent.com/6869813/198158635-8197c709-d26f-437c-bb5e-6cced48d8de5.png)

**Comment by dognose24** [comment] 2022-10-27 02:33
As @jsnmoon discussed with me, we plan to shelve the icons importing as a separate issue to tackle. I will update the uppercase texts first.

**Comment by jsnmoon** [comment] 2022-10-27 18:08
I am closing this issue as a duplicate of #69530; we can use #69178 to track [the title casing enhancement](https://github.com/Automattic/wp-calypso/pull/69508).

**Closed as not planned by jsnmoon** 2022-10-27 18:08 UTC
