### ISSUE TITLE
Tiled Galleries: Don't show scrollbars

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#29706] opened 2018-12-21 08:33 UTC
When editing the tiled gallery block, sometimes individual images may have scrollbars. Particularly on small viewports or in the styles picker in the block sidebar:

![screen shot 2018-12-21 at 09 31 59](https://user-images.githubusercontent.com/841763/50332729-588a2500-0503-11e9-8f45-e8a13018783b.png)

Make sure they do not appear.

**Comment by simison** [comment] 2018-12-21 08:41
Yap — duplicate of https://github.com/Automattic/wp-calypso/issues/28909 — I actually just made a quick fix for this morning — I'll PR it.

**Comment by sirreal** [comment] 2018-12-21 09:06
Duplicate of  #28909

**Comment by sirreal** [comment] 2018-12-26 09:16
I'm reopening this. #28909 is specific to the block style picker, however scrollbars may also appear in the content. The description has been updated to remove style picker references and focus on scrollbars in the block content.

**Comment by MichaelArestad** [comment] 2018-12-27 17:57
Sometimes the scrollbars show up and make it so the image cannot be removed. Once we remove scrollbars from appearing, this should be fixed as well.

**Comment by sirreal** [comment] 2018-12-27 18:02
> Sometimes the scrollbars show up and make it so the image cannot be removed. Once we remove scrollbars from appearing, this should be fixed as well.

Nice observation, if the caption is overflowing, there's no way to select the image _without_ selecting the text.

**Comment by MichaelArestad** [comment] 2018-12-27 18:08
You know. I'm starting to think this is a core issue as well. I'm able to reproduce on core galleries.

**Comment by MichaelArestad** [comment] 2018-12-27 18:12
Okay, so the more I mess with this, the more I think we need to leave the scrollbar in place for scrolling the longer captions. However, core needs to raise the z-index of the close button (I think).

**Comment by simison** [comment] 2019-04-01 09:17
Closing as the current block iteration doesn't have captions and this is tracked also at https://github.com/Automattic/jetpack/issues/11794

**Closed by simison** 2019-04-01 09:17 UTC
Labels: Design, Tiled Galleries, [Goal] Gutenberg, [Type] Defect
