### ISSUE TITLE
Plugin Details: Use the Dynamic catalog to get plugin data

### ISSUE THREAD

**Issue by WBerredo** [Automattic/wp-calypso#71323] opened 2022-12-19 13:24 UTC
Use the Dynamic catalog on Jetpack Search to retrieve plugin data, instead of retrieving it from the .com and .org API as it's done currently.

It depends on: D95375-code

**Comment by cpapazoglou** [comment] 2023-01-16 12:54
Duplicate of https://github.com/Automattic/dotcom-forge/issues/1482

**Closed as completed by cpapazoglou** 2023-01-16 12:54 UTC
