### ISSUE TITLE
Theme modal on Atomic: Preview not working on private sites

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#66023] opened 2022-07-27 18:15 UTC
The modal that pops up when activating a theme in an Atomic site shows the wrong preview if the site is private.

| Expected  | Actual result |
| ------------- | ------------- |
| <img width="778" alt="image" src="https://user-images.githubusercontent.com/375980/181342474-3c6e6299-6852-4ebd-8817-278115ecc462.png"> | <img width="773" alt="image" src="https://user-images.githubusercontent.com/375980/181342616-199d0be8-068d-41fc-bd59-f9f6d58a69ea.png">  |

If the site is published the preview works fine.

The problem seem to be related to the different domains, the preview comes normally from `*.wpcomstaging.com` while the modal runs on `wordpress.com`.

A good compromise seems to be detecting this condition before showing the modal and replacing the preview with an image/text describing the situation and what are the steps to fix it.

It's worth noting that the modal functionallity is NOT impacted. 

Slack discussion: p1658943337617899-slack-C0Q664T29

**Comment by blackjackkent** [comment] 2022-08-01 16:41
@SaxonF Our thought here is to display some sort of static design for users in this scenario (private site, trying to switch themes - i.e. "your site is currently private and cannot be previewed". Can you provide a more specific design for this?

**Comment by SaxonF** [comment] 2022-08-02 01:49
@blackjackkent are we able to treat this as a separate small project since that's current behaviour? Its actually an issue we looking at as part of the build team work as well, so whatever we decide there can also apply here.

**Comment by blackjackkent** [comment] 2022-08-02 15:46
@SaxonF Sure - meaning you'd like us to push this to i.e. next sprint? We can do that - do you have a link to the build team issue just so I can keep an eye on that discussion as well?

**Comment by nelsonec87** [comment] 2023-03-16 22:00
Closing as we can't reproduce it anymore.

**Closed as completed by nelsonec87** 2023-03-16 22:00 UTC
Labels: [Feature] Theme Showcase
