### ISSUE TITLE
Purchases: Google Apps: Expiration warning on day 1

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#3809] opened 2016-03-06 23:10 UTC
Under My Purchases, Google Apps products show an expiration warning from day 1, saying that it will expire in a year and must be renewed.

For the record, I didn't change any setting about renewing at all.

![image](https://cloud.githubusercontent.com/assets/991022/13557972/8ef33aac-e3ad-11e5-8db0-48815666a585.png)

**Comment by fabianapsimoes** [comment] 2016-03-07 13:30
Did you purchase this with credits? The blue notice is displayed for all unsubscribed purchases. If you purchased with credits, your purchase is automatically unsubscribe since there's no way for us to enable auto renwal.

**Comment by fabianapsimoes** [comment] 2016-03-15 16:43
I'm unable to reproduce this, so I'll close this issue for now. Feel free to reopen if you have more information.

**Comment by umurkontaci** [comment] 2016-03-15 16:47
Sorry for the late response. The answer is yes, I did purchase this with credits. Nevertheless, buying with credits is a feature that we support. I think showing a message that a product will expire in a year is confusing when it's bought by credits. Maybe we can show it when it's closer to expiration?

**Comment by fabianapsimoes** [comment] 2016-03-15 16:53
That's the current approach for all unsubscribed purchases. They can subscribe again by adding a payment method to the subscription, and that will get rid of the blue notice.

cc @mikeshelton1503 for input.

**Comment by umurkontaci** [comment] 2016-03-15 19:32
I understand the technicality but our users don't have know about this. Also from what I remember, the only way to get rid of the message is to pay again by renewing now; which adds another year to the subscription.

**Comment by fabianapsimoes** [comment] 2016-03-16 14:32
> I understand the technicality but our users don't have know about this. 

Yup, I know. Which is why I'm asking for Mike's input :)

> Also from what I remember, the only way to get rid of the message is to pay again by renewing now; which adds another year to the subscription.

That used to be the case. Now users can resubscribed by adding a new payment method as well.

**Comment by umurkontaci** [comment] 2016-03-17 19:09
> That used to be the case. Now users can resubscribed by adding a new payment method as well.

Ah. GTK. :+1:

**Comment by fabianapsimoes** [comment] 2016-03-18 15:23
This seems to be a duplicate of https://github.com/Automattic/wp-calypso/issues/732, so closing this one so we can continue the discussion there.

**Closed by fabianapsimoes** 2016-03-18 15:23 UTC
Labels: Purchases, [Status] Needs Design Review, [Type] Bug
