### ISSUE TITLE
Image block does not render filters in widgets

### ISSUE THREAD

**Issue by syds87** [Automattic/wp-calypso#62094] opened 2022-03-20 11:20 UTC
### Quick summary

When adding an image block in a widget area and applying a filter to it (like Saturation or Grayscale), the image is showing the applied filters only on some pages/posts. Other pages/posts will show the original image. 

### Steps to reproduce

1. Go to Appearance > Customize > Widgets
2. Choose a widget area and add an Image block
3. Apply a filter to it (I've tried Grayscale and Saturation)
4. Save the settings

### What you expected to happen

All pages and posts should show the filtered image in the widget area.

### What actually happened

Some pages/posts are showing the filtered image, some others (apparently without a reason/pattern) are showing the original one.

### Context

A user reported this on Twenty-Fourteen theme. I've replicated this on my website using Twenty-Fourteen, Twenty-Twentyone, and Twenty-Twenty.

I have added this image to my widget area and applied the Grayscale filter: 
<img src="https://cdn-std.droplr.net/files/acc_1121608/ZfZs5a"> 

After saving the settings, the image is properly filtered on my homepage:

<img src="https://cdn-std.droplr.net/files/acc_1121608/H901bJ">

But if I check a random post on my website, it's displayed like this:

<img src="https://cdn-std.droplr.net/files/acc_1121608/JlPSSQ">

This does not seem to happen on every post, as another random post on my website seems to show this properly.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

I have replicated this on Twenty-Fourteen, Twenty-Twentyone, and Twenty-Twenty.

### Reproducibility

Consistent

**Comment by poeticabdul** [comment] 2022-03-20 12:46
User mentioned here 4868650-zen that newer articles were able to apply the filter but not the older articles

**Comment by Greatdane** [comment] 2022-03-30 05:44
Going to leave this open for another @Automattic/dotcom-triage-pa-group triager to test, we have had two reports, but I am unable to replicate myself.

**Comment by kimerlin81** [comment] 2022-04-14 12:11
I was unable to reproduce this on any of my test sites. Unable to figure out a pattern either. leaving open for others to review.

**Comment by vajrasar** [comment] 2022-04-14 12:33
Hi @syds87 Like @Greatdane and @kimerlin81 I was also not able to replicate the issue either on Simple or AT site. I tested with different themes on both sites.

Closing this since the issue cannot be replicated. However, if you can replicate this on a new site, please consider creating maybe a screen recording while sharing the report. Thanks. 🙇‍♂️

**Closed as completed by vajrasar** 2022-04-14 12:33 UTC
Labels: Bug, [Pri] Low, Block Widgets
