### ISSUE TITLE
Archeo: Featured image cropped on mobile

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#71596] opened 2022-12-30 17:32 UTC
### Quick summary

When the Archeo theme is active, post featured images are copped on mobile.

### Steps to reproduce

1. Activate the Arecheo theme.
2. Create a post and set a featured image with a landscape layout.
3. Visit that post from a mobile device.

### What you expected to happen

To see the full featured image.

### What actually happened

The image appears cropped.

### Context

5825198-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Archeo.

### Reproducibility

None

### Severity

None

### Available workarounds?

None

**Comment by cuemarie** [comment] 2023-01-13 20:58
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Replicated - By Design
- Tested on AT: Replicated - By Design

📌 FINDINGS/SCREENSHOTS/VIDEO
- On my test sites, the featured image on posts appears to match how the live demo for this theme looks. 
- On the Single Template for Archeo, the Post Featured image block is set to Scale "Cover" by default, which means the `Image is scaled and cropped to fill the entire space without being distorted`.

<img width="908" alt="Markup 2023-01-13 at 14 55 29" src="https://user-images.githubusercontent.com/27249804/212417550-d2192f71-d0d1-43d1-8f6c-1d4421c77c4f.png">

Switching the block's Scale setting to **Contain** would be the fix here, as with this setting, the `Image is scaled to fill the space without clipping nor distorting`.

<img width="1408" alt="Markup 2023-01-13 at 14 57 02" src="https://user-images.githubusercontent.com/27249804/212417755-8927a059-924f-41fe-9616-107cef73ebb7.png">

📌 ACTIONS
- Closed as by design

**Closed as completed by cuemarie** 2023-01-13 20:58 UTC
Labels: Bug, Triaged, [Feature] Full Site Editor, [Platform] Simple
