### ISSUE TITLE
A toggle for switching Email Notifications On/Off for posts you publish on simple sites.

### ISSUE THREAD

**Issue by Sandkorner** [Automattic/wp-calypso#51279] opened 2021-03-22 16:24 UTC
What
I have heard from several users, that they want to have an option to switch email notifications off for their users (for one post, but it might be also for a longer time for several posts that they are publishing)

Why
This will help our users to publish their content as they see fit. 

How
I would think it would be a good option to have here: 
<img width="668" alt="Screenshot 2021-03-22 at 18 22 48" src="https://user-images.githubusercontent.com/71094068/112023200-b327e680-8b3b-11eb-9377-4e10b9effd3b.png">

**Comment by jordesign** [comment] 2021-08-05 23:54
Closing this as a duplicate of https://github.com/Automattic/wp-calypso/issues/44263

**Closed as completed** 2021-08-05 23:56 UTC
Labels: Enhancement, Feature Request
