### ISSUE TITLE
Customer has paid but keeps seeing "Your cart is awaiting payment"

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#30828] opened 2019-02-16 03:38 UTC
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. sign on as user

Will see https://cld.wthms.co/pcGAUU

#### What I expected

"Your cart is awaiting payment" should not display for a fully paid Customer.

#### Browser / OS version
Chrome

#### Screenshot / Video
https://cld.wthms.co/pcGAUU

**Comment by kosiew** [comment] 2019-02-16 03:44
@Automattic/onboarding-dev , can you take a look?

**Comment by kosiew** [comment] 2019-02-16 06:06
In https://a8c.slack.com/archives/C7RGB8CT1/p1550293233005000, used quick work around to empty Customer's cart to get rid of the message.f

Underlying issue, her purchased items were still in her cart.

**Comment by kosiew** [comment] 2019-02-16 09:52
In discussion, concluded that this could have arisen due to user action.
Closing this.

**Comment by KristinaKay** [comment] 2019-04-24 05:26
A few users have mentioned that items keep appearing in their cart and I too thought it personal error, but after tonight I believe there is a bug.

I am having the same issue on my personal site. I paid to renew domain today but item still remains in cart. 

**Steps taken:**
Delete item from cart
Refresh Page
Item back in cart.
Cleared Cache
Item back in cart.
Delete item from cart
Refresh Page
Item back in cart.

**Expected**
Item should not be in cart.

https://cld.wthms.co/ApIPtq

**Comment by southp** [comment] 2020-01-20 04:23
@KristinaKay If you have some spare time, could you help me test if you can still reproduce this? The GIF is no longer accessible so I'm afraid I have to ask you to try again. I'm asking because staled cart content could lead to very frustrating situation like excessive nudges for paying, both from the notification inside of calypso and the direct emails. e.g. it could be one of the culprit of p2-p9jf6J-2iV.

**Comment by davipontesblog** [comment] 2020-03-13 15:26
Moved to Checkout Redesign for triaging.

**Comment by michaeldcain** [comment] 2020-04-28 15:50
Removed this from the Checkout project board, since it seems to be an issue from the abandoned cart campaign: p9jf6J-2iV-p2

@southp: if this is resolved, can you close it?

**Comment by worldomonation** [comment] 2021-02-12 00:20
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

As there has been no recent activity on this issue it is being closed with the label `Closed - Won't Fix`.
If this issue should remain open, please feel free to re-open this bug.

**Closed by worldomonation** 2021-02-12 00:20 UTC
Labels: Checkout, [Type] Bug
