### ISSUE TITLE
Unable to Create New Page In Mobile Browser

### ISSUE THREAD

**Issue by cat-og** [Automattic/wp-calypso#93852] opened 2024-08-23 07:04 UTC
### Quick summary

I am unable to create a new page in my mobile browser. Tested in both Safari and Chrome; when I create a new page from the Dashboard, it takes a moment to load. The patterns appear briefly, and then the page refreshes itself. The patterns appear again for a short time, and then the entire page closes and I see a browser error. 

iPhone 15
iOS 17.5.1
Tested in Chrome and Safari

### Steps to reproduce

1. Start on mobile Dashboard in a browser, not the Jetpack app
2. Use mobile Dashboard navigation to Create a New Page
3. The new page will not load, and the browser will eventually return an error message. 

### What you expected to happen

A new post will be created which I can then edit and publish.

### What actually happened

The browser returns an error message. If I hit back from there, it brings me to the last post I was working on, not back to the Dashboard. 

https://github.com/user-attachments/assets/5210d62f-f34f-4259-8716-feda0d03e549

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by TimBroddin** [comment] 2024-08-23 09:33
📌 REPRODUCTION RESULTS

I can reproduce.

📌 FINDINGS/SCREENSHOTS/VIDEO
Same results as above.

**Comment by xavier-lc** [comment] 2024-08-23 12:13
Unassigning myself, I only own Android devices and the flow works fine on them.

**Comment by TimBroddin** [comment] 2024-08-23 13:05
I'm having a hard time remote debugging this on my iPhone, but my hunch is that this is an OOM error, caused by rendering the block previews.

The heap sizes of Calypso + editor iframe + block previews probably overflows the max memory allowed (which depending on source is somewhere between [384](https://stackoverflow.com/questions/74506298/how-much-the-memory-limitation-is-on-the-ios-device-browser) and [500](https://discussions.unity.com/t/what-is-the-best-practice-for-minimizing-the-memory-occupied-by-runtime-in-a-webgl-build/899768) MB).

The` <BlockPreview />` component lives in Gutenberg: https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/block-preview.

The modal lives here: https://github.com/Automattic/wp-calypso/tree/trunk/packages/page-pattern-modal 

@p-jackson (don't bother reading this until you get back from leave): as the author of the pattern modal, do you have any idea on how to best resolve this?

**Comment by Imran92** [comment] 2024-08-26 09:06
> I'm having a hard time remote debugging this on my iPhone, but my hunch is that this is an OOM error, caused by rendering the block previews.
> 
> The heap sizes of Calypso + editor iframe + block previews probably overflows the max memory allowed (which depending on source is somewhere between [384](https://stackoverflow.com/questions/74506298/how-much-the-memory-limitation-is-on-the-ios-device-browser) and [500](https://discussions.unity.com/t/what-is-the-best-practice-for-minimizing-the-memory-occupied-by-runtime-in-a-webgl-build/899768) MB).
> 
> The` <BlockPreview />` component lives in Gutenberg: https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/block-preview.
> 
> The modal lives here: https://github.com/Automattic/wp-calypso/tree/trunk/packages/page-pattern-modal
> 
> @p-jackson (don't bother reading this until you get back from leave): as the author of the pattern modal, do you have any idea on how to best resolve this?

Wondering if https://github.com/Automattic/wp-calypso/issues/83472 has fixed this issue as well

**Comment by miksansegundo** [comment] 2024-09-06 11:23
This looks like a rendering issue with a memory leak. I haven't reproduced the page crash when the page loads but I can reproduce it by just doing clicks on the screen, no need to scroll.

https://github.com/user-attachments/assets/e1720ef1-9c7c-4c50-aa28-6f72ae606ed3

I'll continue debugging the rendering in Chrome Dev Tools next week. I expect to find a React memo that is not working as expected or it's missing to prevent unnecessary renders.

**Comment by miksansegundo** [comment] 2024-09-10 06:02
This issue is affecting the pattern rendering in all the editors. Safari mobile crashes when exploring patterns in the page, post and site editors.

I have created an [issue](https://github.com/WordPress/gutenberg/issues/65178) in Gutenberg to address the pattern rendering performance issue there.

**Comment by miksansegundo** [comment] 2024-09-11 11:15
@TimBroddin I have found that reverting the diff D109323-code to use the map provider `mapbox` rather than `mapkit` (which uses Apple maps in iOS) improves the pattern rendering performance a lot and helps prevent the browser crash. Do you know the context of using `mapkit`?

Using Mapbox won't fix the issue totally but it helps a lot. Otherwise, Safari crashes every time a pattern with an Apple map is rendered. Sometimes on the first load, others on the second load but it always crashes. 

I believe the root cause is multiple issues because of the features Dotcom adds to the editor. I'm still debugging the features in the plugin `jetpack-mu-wpcom` one by one to find more issues. 

The modal itself can also use more memoizations. I'll follow up with more later with a PR. 

This GB performance [issue](https://github.com/WordPress/gutenberg/issues/64732) can affect here too.

**Comment by TimBroddin** [comment] 2024-09-11 11:20
@miksansegundo Thanks for digging into this.

The main reason for switching the map block to Mapkit was savings. We spent a ton on Mapbox, and Mapkit is free. 

We could use Mapbox or a static image when rendering the pattern selector if we can somehow determine that we're being rendered there. The downside would be that the map would look different on insertion. I can look into that if you want.

**Comment by p-jackson** [comment] 2024-09-12 23:11
Would a quick fix simply be to bypass the modal on mobile devices and just start with a blank page?
It feels warranted given this currently blocks the "create new pager" flow on mobile.

> @p-jackson (don't bother reading this until you get back from leave): as the author of the pattern modal, do you have any idea on how to best resolve this?

Things have definitely changed in this modal since it was first created. A lot about patterns has changed. It originally showed jpeg screenshots of the patterns which is much more memory friendly. Check out this page 359fb-pb/. But this was all before patterns were in the core editor.

Now the block inserter menu shows live previews of patterns, and using mShots isn't an approach that would work for Core. By using dynamic previews it means the previews are more easily translatable and can use the correct styling based on `theme.json`. Using an mShot approach would mean taking jpeg screenshots of many many permutations of each pattern.

But yeah, all those iframes are pretty heavy 😬

I was just testing the block inserter menu on my phone, and even some of those pattern previews cause the site to crash for me!

**Comment by TimBroddin** [comment] 2024-09-13 07:02
I did some digging and using something like this works:

```
useEffect(() => {
		if ( document.querySelectorAll('body.modal-open').length > 0 ) {
			setIsInsidePatternList(true);
		}
	}, []);

if ( preview ||  isInsidePatternList ) {
		const mapStyleObject = styles.find( styleObject => styleObject.name === mapStyle );

		content = (
			<div className="wp-block-jetpack-map__map_wrapper">
				<img
					alt={__('Map Preview', 'jetpack')}
					src={mapStyleObject ? mapStyleObject.preview : previewPlaceholder}
					style={{ width: '100%', height: 'auto' }}
				/>
			</div>
		);
```
(Note that there's already a `preview` attribute that triggers the display of a jpg instead of a full map here).

However, it would be great if there was a hook `useIsInsideBlockPreview` that would get this value from a provider higher up. Checking the existence of a class name feels hacky.

**Comment by obenland** [comment] 2024-09-27 20:05
@TimBroddin Any update on this?

**Comment by TimBroddin** [comment] 2024-10-08 06:17
> [@TimBroddin](https://github.com/TimBroddin) Any update on this?

If this pattern picker is going to go away in the future, the hacky way I suggested above might be a viable option 👍

**Comment by davemart-in** [comment] 2024-10-14 19:04
Removing this from The One Board and removing the Groundskeeper label since Quake team took ownership.

**Closed as completed** 2024-10-16 06:24 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] High, [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience
