### ISSUE TITLE
Editor: Cannot scroll in preview in iOS

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#1066] opened 2015-11-30 20:51 UTC
Reported in 271879-chat (iOS 9.1, Safari 9) and confirmed in iOS Simulator (iPad on iOS 8.2):

![ios-cannot-scroll-preview](https://cloud.githubusercontent.com/assets/227022/11484050/a1b5efaa-9771-11e5-932b-aa13027cb62f.gif)

**Comment by designsimply** [comment] 2015-12-01 15:21
Thank you for reporting this! Closing as a duplicate of #312.

**Closed by designsimply** 2015-12-01 15:21 UTC
Labels: Editor, [Type] Bug
