### ISSUE TITLE
Editor: post title completely disappears on scroll

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1584] opened 2015-12-15 02:13 UTC
Raised by @jblz 

What I Did:
* Opened the editor
* Typed in a post title
* Scrolled down

What I Expected:
* The post title to be "anchored" somewhere regardless of how far down I scroll

What Actually Happened:
* The post title slides underneath the masterbar
* The editor header gets "pinned"
* I'm staring at a blank field without any reference to what it is I'm trying to create

Naming things [is hard](http://martinfowler.com/bliki/TwoHardThings.html). We should reward / honor the cognitive effort a user has spent in naming their post by leaving it visible. Having the title visibly anchored would also help me focus on the thesis of what I'm creating.

Here's some places where it might fit:

<img width="1064" alt="screen_shot_2015-09-01_at_10_12_41_am" src="https://cloud.githubusercontent.com/assets/1587282/9606631/88b7bebe-5092-11e5-8748-31a024eae479.png">

**Comment by folletto** [comment] 2016-10-05 12:36
That's by design.

Notice also that in practice if the field is blank, the page won't scroll down. No text = no scroll. However, that wasn't true at the time when this issue was raised since we didn't have the sidebar scrolling independently yet. Once that was fixed, a taller sidebar didn't make the main content column to scroll when empty, thus making the problem above disappear (even if we haven't really made it sticky, it's not the case anymore in practice).

Closing.

**Closed by folletto** 2016-10-05 12:36 UTC
Labels: Editor, [Type] Enhancement
