### ISSUE TITLE
Search Block Input Field Background Color

### ISSUE THREAD

**Issue by CodeAllNightNDay** [Automattic/wp-calypso#94868] opened 2024-09-25 00:22 UTC
### Quick summary

The Search Block Input field's background color cannot be changed; editing the background color only changes the associated button. There's no separation when editing the input field independent of the search button.

8779080-zd-a8c

### Steps to reproduce

1. Open a simple or atomic site and insert a Search Block or edit an existing one.
2. The site can be on WordPress.com or WordPress.org
3. Use a classic or block theme.
4. This can be done on a page, post, or template (for FSE themes).
5. Select the search block and change the background color in the block settings.

### What you expected to happen

1. To have the ability to change the background color of the Search Block input field.

### What actually happened

1. Changing the background color of the Search Block only affects the associated search button.

![Screenshot 2024-09-24 at 8 10 55 PM](https://github.com/user-attachments/assets/ab43b9d4-4210-4951-aad7-b01fbf477af4)

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Apply custom CSS:
```
.wp-block-search .wp-block-search__input[type="search"] {
background-color: [#97E7F5](editor://hashtag#97E7F5)
}
```

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

**Comment by Robertght** [comment] 2024-09-27 12:24
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 
- Replicable outside of Dotcom – Yes

📌 ACTIONS
- Closed as duplicate 

- 📌 Message to Author
Thank you for reporting this @CodeAllNightNDay. It looks like this was also reported in the Gutenberg core a while back here: https://github.com/WordPress/gutenberg/issues/65343

**Closed as completed by Robertght** 2024-09-27 12:24 UTC
Labels: Bug, [Pri] Normal, [Feature] Full Site Editor, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Product] WordPress.com, [Feature Group] Editor Experience
