### ISSUE TITLE
Free Trials: Updated thank you pages for free trials

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#1122] opened 2015-12-01 16:25 UTC
_From @breezyskies_

In no-cc free trials, the user won't be going through a checkout form anymore, so we need to adjust the thank you page they see after signing up for the free trial:

Premium | Business
------------ | -------------
<img width="991" alt="ymxp2zml-0-3000x3000" src="https://cloud.githubusercontent.com/assets/3011211/9550613/30910b2a-4d61-11e5-84bf-e147d4e08ed6.png"> | <img width="987" alt="xe9mjk7h8s-3000x3000" src="https://cloud.githubusercontent.com/assets/3011211/9550612/308ccb6e-4d61-11e5-91a9-960994a81555.png">

**Comment by mikeshelton1503** [comment] 2015-12-07 19:38
These changes as outlined above have already been addressed. However, I'm leaving this open because now that we are offering domains as part of the free trials (officially pending), we need to update this page to include info about using your domain credit.

**Comment by spncrb** [comment] 2015-12-11 18:57
Now that we've confirmed domains will not be part of the no-cc free trials this issue can continue as before.

**Comment by fabianapsimoes** [comment] 2015-12-11 22:42
> These changes as outlined above have already been addressed. 

Closing since the new changes are no longer needed.

**Closed by fabianapsimoes** 2015-12-11 22:42 UTC
Labels: Free Trials, Post Checkout, [Type] Task
