### ISSUE TITLE
Additional characters pasted into Visual editor using Edge

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#13418] opened 2017-04-26 14:20 UTC
Pasting text into the Visual editor using Edge v40, adds additional characters.

#### Steps to reproduce
Using Edge v40:
1. Load a page on any website
2. Copy text from the page
3. Create a new post: https://wordpress.com/post/
4. Paste the copied text into the visual editor

#### What I expected
Text to be pasted into the editor in the same format as the source.

#### What happened instead
Text is pasted into the editor with additional characters.

![edge-paste-issue-1](https://cloud.githubusercontent.com/assets/11627765/25438849/8f1c63b4-2a92-11e7-9f9a-b307b84ea7e3.jpg)

The same behaviour occurs if:

1. Text is copied from other sources such as Google Docs.
2. Text is converted to plan text before pasting into the editor.

#### Browser / OS version
Windows 10 / Edge v40. The issue does not occur in IE11 or Chrome.

#### Screenshot / Video

![edge-paste-issue](https://cloud.githubusercontent.com/assets/11627765/25438654/13757962-2a92-11e7-88c5-b1319427e7ed.gif)

#### Context / Source
#manual-testing, #user-report

**Comment by dahlsdata** [comment] 2017-06-07 10:54
I get the exact same problem. But in Wordpress self hosted editor. Did you find a solution?

**Comment by rachelmcr** [comment] 2017-08-16 17:44
I tested using Windows 10 / Edge v. 40 (VirtualBox) using the steps above and could not reproduce the issue. The copied text was pasted without any additional, unwanted characters. (I also tested with the same source text as in the screenshot/GIF above, in case it was specific to that text.)

Closing this issue as it seems to be resolved, but we can reopen if the issue persists in certain cases.

**Closed by rachelmcr** 2017-08-16 17:44 UTC
Labels: Editor
