### ISSUE TITLE
Gutenframe: Editing an image takes one to the editor page, but does not show the image

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#31350] opened 2019-03-11 14:26 UTC
#### Steps to reproduce 

- Start with a WordPress.com site
- Opt-in to use Gutenberg
- This takes one to https://wordpress.com/block-editor/post/{site}
- Click on the featured image section on the right sidebar (add an image block, or do anything to show the media modal)
- Upload an image, or choose an image
- Click on `Edit image`

![Screenshot 2019-03-11 at 19 54 22](https://user-images.githubusercontent.com/18581859/54131061-98dcad80-4437-11e9-8027-9abbf1618b98.png)

#### What is expected 

A new page opens up with the image, for editing

#### What happens instead 

A new page opens up for editing, but the image is nowhere to be seen

![Screenshot 2019-03-11 at 19 54 25](https://user-images.githubusercontent.com/18581859/54131054-94b09000-4437-11e9-9935-30afd7b18f71.png)

#### Notes 

A sample link for the image looks like https://gutenbergwpcomarunsathiyablog.wordpress.com/wp-admin/post.php?post=884&action=edit&frame-nonce=85ed2be6c2&image-editor

Removing the `frame-nonce` parameter on this link shows the image as expected. The new URL becomes https://gutenbergwpcomarunsathiyablog.wordpress.com/wp-admin/post.php?post=884&action=edit&frame-nonce=85ed2be6c2&image-editor

![Screenshot 2019-03-11 at 19 54 57](https://user-images.githubusercontent.com/18581859/54131041-8febdc00-4437-11e9-8497-c4c9d46c54e3.png)

Further investigation indicates that this happens only for Gutenframe (Gutenberg launched from WordPress.com dashboard) and not for Gutenberg on wp-admin. 

Originally reported by @yashitamittal11 - p1552108535075900-slack-gutengroup-wpcomhappy

**Comment by arunsathiya** [comment] 2019-03-11 14:27
On an extra note, this likely needn't be addressed because we are going to replace the core media experience with the Calypso media experience as per https://github.com/Automattic/wp-calypso/issues/31294 cc @kwight

**Comment by gwwar** [comment] 2019-03-11 15:58
Thanks @arunsathiya ! I'm closing this as a duplicate of https://github.com/Automattic/wp-calypso/issues/31298 I'll add a note on the other issue that we had another report

**Closed by gwwar** 2019-03-11 15:58 UTC
Labels: Media, [Goal] Gutenberg, [Pri] Normal, [Type] Bug
