### ISSUE TITLE
Themes: Problem with modal after premium theme checkout

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#59258] opened 2021-12-15 20:02 UTC
### Details

After buying a premium theme (after checkout), I'm redirected to the themes page and a strange modal is shown for a while:

![image](https://user-images.githubusercontent.com/3801502/146255470-2ddfeb51-a0ef-4ac8-aff4-ed18f653ef28.png)

It's similar to the one that shows when it's simply activating a theme: 

![image](https://user-images.githubusercontent.com/3801502/146256290-19e875ce-3025-47ea-98fc-dab59fafd55f.png)

But:
- Without the view site icon
- without the overlay
- with the buttons "clickable"
- without the "loading" animation.

#### Steps to reproduce

1. Use a free site
2. Navigate to the premium themes
3. Buy one
4. Right after the checkout you'll see the modal.

**Comment by sixhours** [comment] 2022-01-03 21:11
Hmm, I wonder if this is a network lag/disconnected sandbox issue. The modal resolves to this for me:
<img width="363" alt="Screen Shot 2022-01-03 at 4 10 37 PM" src="https://user-images.githubusercontent.com/2124984/147980787-1a97464b-2f5a-4211-a75a-c544229dd5c6.png">

I do see the loading animation/icon/etc while it's resolving:

https://user-images.githubusercontent.com/2124984/147980902-d12d25fd-a9bc-4fd2-9498-500d09e99ac3.mov

**Comment by sixhours** [comment] 2022-01-17 17:35
@mreishus Just to be safe, are you able to reproduce this issue? If not, I think this was a fluke.

**Comment by mreishus** [comment] 2022-01-17 17:51
I see a modal with a waiting icon and the button reading "Activating theme..." for a while, then it changes to "Thanks for choosing Skivers".

https://user-images.githubusercontent.com/937354/149817653-a53980e9-ee96-4194-902c-fcce8a91f6e7.mp4

**Comment by mreishus** [comment] 2022-01-17 17:52
Probably what's strange about it is the loading animation is subtle and the only text explaining what's happening is on the button.

**Comment by sixhours** [comment] 2022-01-17 18:02
OK, the missing loader/icon in the original report appears to have been a fluke. I'm going to close this since it's behaving as expected for now!

**Closed as completed by sixhours** 2022-01-17 18:02 UTC
Labels: [Feature] Theme Showcase
