### ISSUE TITLE
CoBlocks Masonry Gallery: Link to Custom URL makes Captions Inaccessible

### ISSUE THREAD

**Issue by jacoswan** [Automattic/wp-calypso#39100] opened 2020-01-28 08:01 UTC
This issue does not happen on a WPORG install with no other plugins and CoBlocks 1.20.1, but can be recreated on Personal plan sites.  Mentioned in #37090 and might be related.

#### Steps to reproduce
1. Add Masonry block with images
2. Select an image and toggle Captions » ON
3. Add a caption
4. With same image select, change Link Settings » Link to » Custom URL
5. The caption is now hidden behind the URL box, and can't be reached. 

#### What I expected
When the image is selected, the URL box appears and shifts the caption upwards. Both remain visible and editable.

#### What happened instead
The URL box overlays either partially, or completely depending on the image size. 

#### Browser / OS version
Chrome 79.0.3945.130 / Firefox 72.0.2
MacOS Catalina 10.15.2

#### Screenshot / Video

On Personal plan: Image with a caption and Link to » None

![image](https://user-images.githubusercontent.com/15178758/73243948-7c617500-41b1-11ea-9f01-6b14603012de.png)

Same image, same captions, but Link to » Custom URL

![image](https://user-images.githubusercontent.com/15178758/73244074-c0547a00-41b1-11ea-9a92-db4dcb93a04b.png)

Same as above, but the check-button turns whites when you click it. On WPORG the icon initially is the "return/enter" symbol, and changes only to a checkmark when clicked.

![image](https://user-images.githubusercontent.com/15178758/73244010-9c913400-41b1-11ea-9ac9-6069a6d1da0f.png)

On local host with WPORG: 

![image](https://user-images.githubusercontent.com/15178758/73245144-3ce85800-41b4-11ea-819f-059ff605ad86.png)

Same image when editing the Caption (placement of formatting controls are less than ideal though):

![image](https://user-images.githubusercontent.com/15178758/73245346-b41dec00-41b4-11ea-9a72-eb64ba1b0a76.png)

**Comment by chaitanyamsv** [comment] 2020-01-31 02:42
Another report in 18166930-hc

**Comment by kriskarkoski** [comment] 2020-03-11 16:15
Confirmed I can still see this issue in Chrome 79.0.3945.13 on a Premium site

**Comment by mlaetitia** [comment] 2020-05-13 07:57
New report: 21042056-hc

**Comment by rickmgithub** [comment] 2020-06-05 13:29
New Report - 3036883-hc

**Comment by davipontesblog** [comment] 2020-06-12 01:01
This should be fixed now with this PR: https://github.com/godaddy-wordpress/coblocks/pull/1527
Please reopen if needed.

**Comment by kcswong** [comment] 2020-08-18 03:59
Reported in 23429394-hc, can replicate on different themes and on a Personal plan site and a Business plan site with plugins installed.

**Comment by WunderBart** [comment] 2020-08-26 14:04
Closing as I cannot reproduce after the recent update (https://github.com/Automattic/wp-calypso/issues/45033). The caption is accessible when the custom URL setting is on:
 
![image](https://user-images.githubusercontent.com/1451471/91313486-b9c4ca00-e7b5-11ea-80a8-cde9fcfe2c1d.png)

**Closed by WunderBart** 2020-08-26 14:04 UTC
Labels: [Type] Bug, [Type] Enhancement
