### ISSUE TITLE
Publishing Pages Shows a Followers Warning

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#61872] opened 2022-03-12 20:14 UTC
### Quick summary

When publishing a page from the editor, a warning appears stating that followers will be notified. 

### Steps to reproduce

* Go to Pages>Add a Page
* Give the page a title 
* Click Publish
* Note that a warning appears stating that the post will go out to readers:

![Pages to Followers](https://user-images.githubusercontent.com/2545184/158033099-a304e597-116d-4b98-a64a-23959a3b7a52.jpg)

### What you expected to happen

I would expect it to show no warnings since it's a page not a post. And even if a warning showed, it should say Page rather than post. So this is almost a double-issue here.

### What actually happened

A message pops up warning that the post will go out to readers.

I can replicate on my Premium test site with the Canape theme and he had it with Traveler:

![Screen Shot 2022-03-10 at 1 22 59 PM](https://user-images.githubusercontent.com/2545184/158033453-d2f3f73e-2678-4af3-abd8-78208743deb1.png)

I did not have the issue on mu atomic site. On that site, I didn't get any warning before publishing my page.

### Context

Reported by my (rightfully) very confused husband who was creating a site. 

### Simple, Atomic or both?

Simple

### Browser, operating system and other notes

I used Firefox, and he used Chrome.

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by kriskarkoski** [comment] 2022-03-14 13:26
Duplicate of https://github.com/Automattic/wp-calypso/issues/61515?

**Comment by kimerlin81** [comment] 2022-03-15 18:27
Thanks for submitting this report @ChrissiePollock! I will be closing this incident in favor of https://github.com/Automattic/wp-calypso/issues/61515. Kudos to your husband for recognizing this though :)

**Closed as completed by kimerlin81** 2022-03-15 18:27 UTC
Labels: Bug, Pages, [Pri] Normal, Triaged
