### ISSUE TITLE
Reader: Post has duplicate gravatar

### ISSUE THREAD

**Issue by mikaelz** [Automattic/wp-calypso#16721] opened 2017-07-30 11:34 UTC
I don't know now if it's a feature or bug, but the `.author-compact-profile` has two gravatar images.

![ss_2017-07-30-13-24-38](https://user-images.githubusercontent.com/454800/28752967-906a0af8-752b-11e7-829a-8b2ddfdf16da.jpg)

Same in WordPress tablet app

![screenshot_2017-07-30-12-00-43](https://user-images.githubusercontent.com/454800/28752971-a184db9c-752b-11e7-98a6-f97b816bb2ce.png)

**Comment by samouri** [comment] 2017-08-01 16:43
Technically:
- one of the images is a gravatar (user specific image)
- the other image is a blavatar (blog specific image)

Most of the time they are different, but sometimes they are the same which is frustrating.
We picked the current solution because we thought it looked best most of the time, but may need to revisit this and/or figure out how to dedupe if they are the same image.

this issue is a dupe of the punted: https://github.com/Automattic/wp-calypso/issues/8659
Closing for now

**Closed by samouri** 2017-08-01 16:43 UTC
Labels: OSS Citizen, Reader, [Type] Question
