### ISSUE TITLE
FSE: Images blocks have two "replace image" buttons in sidebar

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#55370] opened 2021-08-11 09:57 UTC
### Steps to Reproduce

1. In an FSE site click and image block and check the right sidebar settings
2. See two replace buttons

![image](https://user-images.githubusercontent.com/47717887/129009617-e84440e9-fd7d-4bbe-a744-78a41d0fd215.png)

### What I expected to happen

should only have one button to replace

### What actually happened

two appear

### Context

empathy testing

### Operating System

macOS

### Browser

Chrome/Chromium

**Comment by formosattic** [comment] 2021-08-17 09:13
Thanks @Nic-Sevic for reporting this and the detailed steps.

I could not reproduce this (with theme Blockbase, Mayland (Blocks), Seedlet (Blocks)) and am closing this for now. Please feel free to re-open if you have further findings to add.

![image](https://user-images.githubusercontent.com/15944096/129698143-ca425d91-3c68-40b0-96a8-2f16ad6fce2e.png)

**Closed as completed by formosattic** 2021-08-17 09:13 UTC
Labels: Bug, [Goal] Full Site Editing, Triaged, [Closed] Not Reproducible, Empathy Testing
