### ISSUE TITLE
Editor: Instead of cutting off title, shrink the font size to fit?

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#4281] opened 2016-03-24 00:44 UTC
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Start a new post
3. Give it a long title, enough to be longer than the available space
4. When I click out, the title is cut off and it's not obvious how to get to the rest

#### What I expected
To see the whole title after clicking out

#### What happened instead
The title was cut off

#### Browser / OS version
Any

We could either use a smaller font size as the title gets longer, or just use a smaller title font in general, or let titles wrap. It's really a pain on mobile, as you only have a few characters to work with and there's no way to get to the title that's off screen.

![screenshot](https://cldup.com/uISXiqkAajc/Akps1S.png)

**Comment by designsimply** [comment] 2016-03-28 18:51
Duplicate of #1059

**Closed by designsimply** 2016-03-28 18:51 UTC
Labels: Editor, [Type] Bug
