### ISSUE TITLE
Editor: Post body does not autosave

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#1061] opened 2015-11-30 19:37 UTC
We have had a few reports of the posts content not being saved. It seems that the title and the tags/categories are being saved but not the body. This may be isolated to Chrome on Windows. Here are a few reports:

> I opened a new post in WP. I typed the entire post. Added gifs. Then, set my categories and tags. I checked preview. Got a blank page. Tried again to check preview. Got a blank page. Hoped it was okay and hit publish. got a blank page. Pulled down the page and rewrote the post. Checked preview. Got a blank page. Set it for scheduled. Started looking for help.

---

> I just published a post, but there’s no content there… Has anyone experienced this? It might magically appear if I wait a little longer, but in case it doesn’t, I want to get right on it. Is there any way I can recover an older version – an auto-saved draft?

In these cases no revisions are being saved, simply the post title and meta data. Wish I could provide more information but at this time I don't know the steps to reproduce simply that it's happening/

Related #310 #315

**Comment by lancewillett** [comment] 2016-03-11 21:07
Closing this one, as it hasn't been reported again since Nov 2015.

**Closed by lancewillett** 2016-03-11 21:07 UTC
Labels: Editor, [Type] Bug

**Comment by lancewillett** [comment] 2016-05-03 18:14
We're seeing a few more reports of post body going missing after publishing. Going to keep an eye out — the hard part is reproducing it. Seems to be from iOS app sometimes, but could be API related since it's not just that one app.

**Comment by designsimply** [comment] 2017-03-16 20:56
Raised with additional detail at #12246
