### ISSUE TITLE
Calypso "People" interface has no sorting/pagination options, may cause browser issues with significant numbers of users.

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#58088] opened 2021-11-16 00:01 UTC
### Quick summary

There are no sorting/pagination options on the Calypso user management interface (people/team, for example).

### Steps to reproduce

1: Create, or visit, a site that has a significant number of users (the site I encountered this issue on has 79, as of the last time I looked at it).
2: Navigate to Users > All Users on that site.

### What you expected to happen

I expected to be able to navigate the entire user list.

### What actually happened

the user list doesn't scroll, and there are no pagination options. Nor are there options for sorting.

### Context

Reported by a user in 31309539-hc, tested and verified by me. The user's list consists of 79 people, not all of them are visible.

### Simple, Atomic or both?

Simple, Atomic

### Other notes

Trying to navigate the user interface with this many users caused my Chrome to give me an out-of-memory error, after the site kept trying to go unresponsive. On this machine (128 GB of memory), there's no reason for Chrome to have done that.

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Users can switch to the WP Admin view and see their entire list. Additionally, if a user knows the username of the person they're looking for (Calypso's search feature won't return results on an email address), the user can narrow that list to just the user they're looking for.

**Comment by Robertght** [comment] 2021-11-17 14:02
Thank you for the report @arinoch !

There seem to be two requests here. One is the case related to #31309539-hc and the second one is to add more flexibility on the People page.

For the first one, the counters from Calypso and wp-admin/users are matching.

The second one is a feature request so I'll relabel this.

If I misread something from this report, please let me know.

**Comment by arinoch** [comment] 2021-11-17 14:09
@robert - The two are related. The counters are correct, but the user was reaching out because while the counters are accurate, not all of the users you can see in WP Admin show up in Calypso. The user in question, for instance, would have been well down the list (the list in Calypso is sorted alphabetically), except that you can't get there from here. The list in Calypso stops with users beginning with BR, this user began with S. The user reached out because they know this user exists, but couldn't see them on the Calypso list. I reproduced this.

**Comment by Robertght** [comment] 2021-11-18 06:04
Thank you for following up @arinoch !

I was able to see the all users on my end up to "Y":

![image](https://user-images.githubusercontent.com/6737345/142361117-9f38957d-7911-490f-9af0-b3f6556a2317.png)

**Comment by arinoch** [comment] 2021-11-18 13:22
@Robertght  - I can see select users on this page, but I cannot see all 78 users on this page. For example, if the current user's (the user who reported this issue) display name is "Jim Bob", I should be able to--on this page, if all 78 users are visible--do a control+f and find "Jim Bob" in the list. When I have this page loaded, I cannot. In addition, when I scroll to the end of the Calypso user list, it doesn't load more users--the initial batch of users generated remains the only batch of users I see.

In Chrome 96, the Calypso People Management screen eventually (after a few minutes) starts to become unresponsive and Chrome gives me an out of memory error. If I reload the page to recover from that out of memory error, the complete list of users I saw before is not regenerated--I could see up to y before, with some users (for example, the user who reported the issue) missing from that list, but after a reload it shows me only up to m.

In contrast, if the user goes to wp-admin/users.php, the entire userlist is visible--and paginated--without issue. I can manipulate the list on this page without error/complication, and all users--including, as in my example, the user who reported the issue), are present.

I can provide more specific examples on a platform that is not this one if it will aid in your testing/triaging.

**Comment by kimerlin81** [comment] 2021-11-18 16:50
Thanks, James! I see what you're saying. I was able to reproduce this bug in Chrome Version 96.0.4664.45 (Official Build) (x86_64)

When I SSP'd in Safari, the users loaded A-Z without any errors. This issue seems to only affect Chrome.
For privacy reasons, I have not included the screen recordings, but I have them saved any team would like to review them.

**Comment by mreishus** [comment] 2021-11-23 16:14
This page uses infinite scrolling, which I agree is not ideal. However, I was not able to replicate some of the problems seen here in Chromium 96.
I was on a P2 with 446 members. My URL was `/people/team/<sitename>`. I was able to scroll all the way to the bottom, across all 446 members, ending with a `z` username.

Problems I could not replicate:
* Additional batches of users not loading. As I scrolled down, more batches of users loaded. Sometimes there would be a few seconds delay, but I was able to scroll all the way down to 'z'.
* Memory errors. I used Chromium's Memory tab in the debug tools to snapshot the heapsize before and after scrolling to the bottom. Before: 30MB. After: 32.9MB.
![2021-11-23_10-06](https://user-images.githubusercontent.com/937354/143060328-bb3bd997-64af-4595-b307-580d4640376e.png)

Any additional information on replicating these would be helpful.

Problems I could replicate: 
* Ctrl-f does not work properly.
  * Even after scrolling down to the bottom, ctrl-f for say, "Aaron" will fail. This is because the top entries are unloaded by the InfiniteList as you scroll down, to save memory.

**Comment by arinoch** [comment] 2021-11-23 20:28
@mreishus - My test was performed in Chrome, as was @kimerlin81's verification. I didn't test in Chromium, but given the bug couldn't be reproduced in other browsers I suspect it's specific to Chrome itself. Can you ping me with the P2 link? I'd be interested in seeing if I can reproduce it.

**Comment by mreishus** [comment] 2021-11-23 20:54
It seems that p2s are different and are working fine. When looking at the user and site described here, 2ac61-pb , with google chrome and the support session extension, I am seeing the undesired behavior. While there are only 77 users, I can only scroll down into the "K" area before the scrollbar disappears and I get a popup from chrome telling me it has become unresponsive.

Edit: @arinoch points out that it could also be a support session only bug, since we can't rule out P2s via support session.

Edit 2: Tried again and I wasn't able to replicate it on the same site+user. Hmm..

**Comment by kimerlin81** [comment] 2021-11-27 12:33
Hi @arinoch! Sometimes third-party themes/plugins can influence how the dashboard behaves. We notice that the user has a plugin called user-role-editor. Since we're not able to replicate this issue outside of a support session, we'd like you to continue troubleshooting to rule out any type of plugin/theme conflict. We'll close this issue for now, but please feel free to reopen if needed.

**Closed as completed by kimerlin81** 2021-11-27 12:33 UTC
Labels: Bug, [Pri] Normal, People Management, Triaged, [Browser] Chrome
