### ISSUE TITLE
CoBlocks: Multiple Hero Block Issues (toolbars not clickable, button text not editable)

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#39324] opened 2020-02-07 21:44 UTC
#### Steps to reproduce
1. On a WordPress.com Simple Site, create a page, and add a Hero Block
2. Add a new button to the right of the Secondary Button
3. Attempt to edit the text of all three buttons.
4. Click on Toolbars above any of the buttons.
5. Editing text appears to sometimes work, or frequently not work at all. My hover for my mouse 
also changes, depending on whether or not I can edit the text.
6. The toolbars are not clickable. You click through them to the block underneath. 

#### What I expected
Buttons to be editable, toolbar options to be clickable.

#### What happened instead
Button text at some point locks up, and cannot be edited. Toolbars do not work at all.

#### Browser / OS version
The text editing and toolbar issue are both in Chrome Version 80.0.3987.87 (Official Build) (64-bit).

Text editing for buttons **works** in Firefox, but the toolbar is still broken in Firefox 72.0.2 (64-bit). 

#### Screenshot / Video
![heroblock](https://user-images.githubusercontent.com/30731356/74067661-9a4b8880-49ae-11ea-8f01-de926ad30276.gif)

#### Context / Source
 #painpoint. #manual-testing #user-report if applicable.

**Comment by p-jackson** [comment] 2020-02-09 21:31
This issue has also been reported in vanilla CoBlocks godaddy-wordpress/coblocks#1252 and has a fix underway (godaddy-wordpress/coblocks#1329).

It doesn't mention the issue of not being able to edit text on Chrome, but I suspect fixing the z-index issues will address this too.

**Comment by p-jackson** [comment] 2020-02-09 21:48
I tested godaddy-wordpress/coblocks#1329 locally and was unable to reproduce the text editing issue in Chrome 👍

**Comment by kriskarkoski** [comment] 2020-03-11 03:16
Closing since it's been addressed in core CoBlocks plugin

**Closed by kriskarkoski** 2020-03-11 03:16 UTC
Labels: [Type] Bug
