### ISSUE TITLE
Block Editor: Featured Image panel only shows partial image 

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#40064] opened 2020-03-11 17:49 UTC
Images I upload to the **Featured Image** panel appear cut in half. This is only an issue when the block editor is enabled.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Upload a featured image to the post via the **Featured Image** panel in the right sidebar.

#### What I expected

After uploading to the **Featured Image** panel, I'd expect to see the full image that I'd uploaded in that panel.

#### What happened instead

I only see a partial/cropped version of the image. It appears to be cut in half:

<img width="1640" alt="Screenshot 2020-03-11 at 17 46 54" src="https://user-images.githubusercontent.com/2998162/76447331-6c4bd080-63c0-11ea-898f-f8165762494d.png">

I was also able to replicate this with Barnsbury, Redhill, and Intergalactic 2. In addition, @chaitanyamsv first reported this issue [here](https://github.com/Automattic/themes/issues/1750) and was able to replicate with Gateway, Hever, Dara, and Portrait. I'd be curious to see if others are able to replicate this, as I'd have assumed we'd have had more reports if it was an issue for everyone.

This was reported in 2782129-zen, by a user who is also seeing the same issue.

#### Browser / OS version

Chrome (version 80.0.3987.132) / MacOS Catalina (version 10.15.3)

#### Screenshot / Video

Here's a .gif of me testing this with the Stow theme, using an image that's 2000px wide by 1200px high (as recommended in [that theme's documentation](https://wordpress.com/theme/stow)).

![featuredimage](https://user-images.githubusercontent.com/2998162/76446523-1dea0200-63bf-11ea-82c9-66d006229ba9.gif)

#### Context / Source

#user-report, #reallife

**Comment by davipontesblog** [comment] 2020-03-12 19:04
I can replicate this on both simple and atomic sites, in both the iframed calypso editor and in wpadmin directly.

**Comment by kriskarkoski** [comment] 2020-03-12 19:16
I cannot reproduce on a .org site hosted elsewhere, but that may be more up-to-date than what we're currently running (tested using Jurassic Ninja)

**Comment by kwight** [comment] 2020-03-12 19:32
I’m seeing something different with a simple site through Gutenframe: the image displayed full (that _is_ the full image, it's not cut off), but within a span with a huge inline bottom padding.

<img width="1149" alt="Screen Shot 2020-03-12 at 12 30 14 PM" src="https://user-images.githubusercontent.com/349751/76560024-7bcd2700-645d-11ea-94f5-2686bf520e76.png">

**Comment by lancewillett** [comment] 2020-03-13 08:16
Worth testing in Gutenberg 7.7.1 (bleeding edge version) to see if it is resolved with a core merge. See p7DVsv-8gl-p2.

**Comment by kriskarkoski** [comment] 2020-03-13 13:24
Testing on Gutenberg 7.7.1 on a simple site that's Edge stickered and I see the same as @kwight, the full image is shown but with inline padding (56% in my case, so maybe based on window size?)

<img width="354" alt="Screen Shot 2020-03-13 at 9 19 10 AM" src="https://user-images.githubusercontent.com/1900444/76624681-21d76a80-650c-11ea-9936-9c3ea2fc29bb.png">

This looks to have been reproduced in core and reported here: https://github.com/WordPress/gutenberg/issues/20697

**Comment by lancewillett** [comment] 2020-03-18 00:23
Fixed in core Gutenberg: https://github.com/WordPress/gutenberg/pull/20892

Likely with our improved cadence of merging in Gutenberg releases to WordPress.com the fix will arrive sooner than later.

Closing for now. (@simison Please correct me if I'm wrong in assuming we _wouldn't_ cherry-pick certain fixes ahead of normal merges.)

**Closed by lancewillett** 2020-03-18 00:23 UTC
Labels: Editor, [Goal] Gutenberg, [Impact] High, [Type] Bug
