### ISSUE TITLE
Notification Settings: I get notifications of "likes on my comments" even though I have that setting off

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#73125] opened 2023-02-08 22:21 UTC
### Quick summary

I have unchecked "likes on my notifications" here:
https://wordpress.com/me/notifications/comments

But I still get "bell" notifications for likes on my comments.

Is this working as intended?
<img width="1404" alt="Screen Shot 2023-02-08 at 3 10 22 PM" src="https://user-images.githubusercontent.com/3476361/217664027-f42610d6-7a01-459e-b392-b4f078de23d3.png">

### Steps to reproduce

1. Turn off "likes" under notifications here: https://wordpress.com/me/notifications/comments
2. Ask someone to like some of your comments

### What you expected to happen

I expect likes to be suppressed in notifications if I have that setting turned off. 

### What actually happened

"Likes" can still fill up the notification panel

### Impact

All

### Available workarounds?

Yes, easy to implement

### Logs or notes

You can click on comments to get around all the likes, but it would be nice to just be able to suppress them in the first place. If I've misunderstood what that setting is supposed to do, let me know.

**Comment by cuemarie** [comment] 2023-03-21 21:49
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on AT: Replicated - May be by design?

📌 FINDINGS/SCREENSHOTS/VIDEO
Hey @carinapilar ! I noticed while testing that `My Profile > Notifications Settings > Comments` is only for **"Comments on other sites"**.

There are also site-specific notification settings under `My Profile > Notifications Settings > Notifications`.  Once I disabled "Likes on my comments" under the bell for my specific site, I stopped receiving notifications when my comments on "my sites" were liked.

Our internal P2s are considered "our" sites when we follow them - I think that's where the confusion might be (I had to think through it myself 😄 )  Are the notifications you're getting happening on P2s that show up in the list of sites  under https://wordpress.com/me/notifications ?

- If so, you can save a change to your notifications across All your sites, to unsubscribe to those likes all at once!

![Markup on 2023-03-21 at 14:44:14](https://user-images.githubusercontent.com/27249804/226748806-b38a33c7-5121-4428-b767-f88d9fab08c3.png)

📌 ACTIONS
- Closed as could not replicate (please reopen if there's more to the issue here that I've missed!)

**Closed as completed by cuemarie** 2023-03-21 21:49 UTC
Labels: Bug, [Pri] Normal, [Feature] Notifications, Triaged

**Comment by carinapilar** [comment] 2023-03-22 12:10
Sorry, @cuemarie, I'm not sure I understand why I was pinged on this one, maybe you meant Velda? 🙂

**Comment by cuemarie** [comment] 2023-03-30 14:08
Sure did 😁 Sorry about that! 

@supernovia meant to ping you in my reply above!

**Comment by supernovia** [comment] 2023-04-04 17:46
Ah! Thank you! That makes sense.
