### ISSUE TITLE
Editor: Disable "Edit" links in post previews

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#1067] opened 2015-11-30 20:53 UTC
In 271879-chat a user reported that they could not use the "Edit" link in the preview to return to the editor.  I suspect they were trying to click the "Edit" link next to the previewed post:

![image](https://cloud.githubusercontent.com/assets/227022/11484147/19f62caa-9772-11e5-90a3-f5d4515bcc7d.png)

If possible, we should disable these links in post previews.

**Comment by designsimply** [comment] 2016-07-20 00:50
Closing because I was unable to reproduce the problem using the following testing steps:

1. Start at https://wordpress.com/post
1. Add a title and some content and make sure a draft is saved
1. Click the Preview button
1. Find and click the Edit link for the post inside the preview

<strong>Result:</strong> the post is re-opened for editing in a new tab (opening in a new tab is not ideal but works)

<strong>Note:</strong> ideally, instead of disabling the Edit link, the preview modal would simply close if you click the Edit link inside a post you were already editing or a new edit page would load if you click on the Edit link for a different page you browsed to within the preview

Tested with Safari 9.1 and Firefox 47.0.1 on Mac OS X 10.11.5

**Closed by designsimply** 2016-07-20 00:50 UTC
Labels: Editor, [Type] Enhancement
