### ISSUE TITLE
Media: We don't load more than 20 Jetpack media items

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#9165] opened 2016-11-04 23:25 UTC
1. Navigate to http://calypso.localhost:3000/post
2. Select a Jetpack site with more than 20 media items
3. Only 20 items display in the media modal

see also: pbg9X-bdL-p2

**Comment by gwwar** [comment] 2016-11-04 23:44
I believe this is because wpcom returns next_page meta and jetpack sites do not:
![screen shot 2016-11-04 at 4 43 33 pm](https://cloud.githubusercontent.com/assets/1270189/20025674/fb38b880-a2ad-11e6-8f20-afd797b50667.png)

![screen shot 2016-11-04 at 4 17 45 pm](https://cloud.githubusercontent.com/assets/1270189/20025676/ffa4a1e0-a2ad-11e6-91de-b52e8b24dec4.png)

**Comment by gwwar** [comment] 2016-11-04 23:46
cc @aduth does it look like the Jetpack api changed, or did we never handle this?

**Comment by jeherve** [comment] 2016-11-05 00:48
This seems to be a duplicate of #1191. 

This bug has existed since the editor was first launched.

**Comment by aduth** [comment] 2016-11-07 14:42
Hmm, we should probably close one or the other of this and #1191, but I believe you're right @gwwar that the likely reason for this not working is the lack of `meta` response property from Jetpack sites.

**Comment by aduth** [comment] 2016-11-07 15:03
Fixed in r145158-wpcom , Jetpack change sync pending at https://github.com/Automattic/jetpack/pull/5529

**Closed by aduth** 2016-11-07 15:03 UTC
Labels: Media, [Type] Bug
