### ISSUE TITLE
Reader: tiled galleries are not formatted as galleries

### ISSUE THREAD

**Issue by yaelirub** [Automattic/wp-calypso#45137] opened 2020-08-22 01:14 UTC
#### Steps to reproduce

1. On the web for a WP.com or Jetpack site, create a new post.
2. Add a paragraph.
3. Add a tiled gallery block with several images.
4.Add a few more tiled gallery blocks with various settings.
5. Add another paragraph.
6.Publish the post.
7. View the post in the Reader.

#### What I expected
I expected the tiled gallery to be formatted correctly

#### What happened instead
The tiles appear vertically one after the other 

### How it looks like in the Reader
<img width="298" alt="Screen Shot 2020-08-21 at 1 15 12 PM" src="https://user-images.githubusercontent.com/1335657/90945467-ece41380-e3d9-11ea-89cc-3a43e7a538c1.png">

### How it looks like in the post
<img width="785" alt="Screen Shot 2020-08-21 at 6 13 11 PM" src="https://user-images.githubusercontent.com/1335657/90945518-27e64700-e3da-11ea-9464-58d13f9145ef.png">

**Comment by davipontesblog** [comment] 2021-04-14 14:09
This is a duplicate of https://github.com/Automattic/wp-calypso/issues/45122.

**Closed by davipontesblog** 2021-04-14 14:09 UTC
Labels: Blocks, Reader, Triaged, [Type] Bug
