### ISSUE TITLE
Gutenlypso: Media & Text block: cannot add an image

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#28195] opened 2018-10-31 13:50 UTC
#### Steps to reproduce
1. Starting at URL: http://wpcalypso.wordpress.com/gutenberg
2. Add a Media & Text block.
3. Click Media Library.
4. Select and add an image.

#### What I expected
The image should have been added to the block.

#### What happened instead
The image isn't added.

I see this in the console but I'm not sure if it's related:

> Uncaught (in promise) Error: Invalid parameter(s): per_page

#### Browser / OS version
Chrome 70.0.3538.77 on macOS 10.13.6

#### Screenshot / Video
![screen shot 2018-10-31 at 7 47 28 am](https://user-images.githubusercontent.com/1119271/47792354-73999f00-dce1-11e8-9d05-f2bfa7f41632.png)

**Comment by arunsathiya** [comment] 2018-12-12 14:04
I am not able to reproduce this on a free WordPress.com site, when I start at https://wpcalypso.wordpress.com/block-editor/post/

I was able to add the image to the WordPress Editor editor just fine, and appears fine on the live site as well.

<img width="811" alt="screenshot 2018-12-12 at 19 33 59" src="https://user-images.githubusercontent.com/18581859/49874622-f6675b00-fe44-11e8-9858-a79d6186ec3a.png">
<img width="674" alt="screenshot 2018-12-12 at 19 34 23" src="https://user-images.githubusercontent.com/18581859/49874625-f6fff180-fe44-11e8-9c2f-dff6691ba865.png">

Can you help check what the status is at your end, @designsimply?

**Comment by torres126** [comment] 2018-12-31 12:32
I bumped into this same issue today (on a site with the Free Plan), using a Mac OS X 10.6.8 with Chrome 49. The steps and result are the same as above, but I got a different console error, and I started at https://wordpress.com/block-editor/post. I can also recreate on Horizon though. 

When I use my Samsung Galaxy Tab S2 with Chrome 70, there aren't any issues with the upload. Here's the console error when the image doesn't upload:

![sgdfsdgfsfdggsd](https://user-images.githubusercontent.com/43215253/50560348-dd412400-0cf7-11e9-8b98-6e2d3efbe5bf.png)

**Comment by arunsathiya** [comment] 2018-12-31 13:37
Thanks for testing, @torres126! I am definitely unable to see this behaviour though - [video](https://cloudup.com/cXmE83c3qg6). I am tagging this post for developers' attention. 

It works fine on Calypsoified Gutenberg as well for me - `{site}/wp-admin/post-new.php` - [video](https://cloudup.com/ceKsSZ77K3T).

**Comment by Copons** [comment] 2018-12-31 15:07
I didn't know about this block, it's so neat!

Though, I can't reproduce this in Gutenlypso on Chrome 71.0.3578.98, macOS 10.14.2, both with the Media Library and via direct upload.
The image insertion seems to work exactly the same as for the simple Image block (meaning: it works fine but the experience could be more polished).

@torres126: Chrome 49 is almost 3 years old.
I understand that it's the last version you can run on Snow Leopard (by far my favourite OS ever, I miss it so much!), but both Calypso and Gutenberg Core officially support the last 2 major Chrome versions only:
- https://github.com/Automattic/wp-calypso#browser-support
- https://make.wordpress.org/core/handbook/best-practices/browser-support/

I'm closing this because it's not relevant anymore: Gutenlypso was in a very different place when this was opened.

**Closed by Copons** 2018-12-31 15:07 UTC
Labels: [Goal] Gutenberg, [Type] Bug
