### ISSUE TITLE
Cover block/site accelerator: images blurry with Jetpack CDN on for cover blocks 

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#60119] opened 2022-01-17 11:20 UTC
### Quick summary

It seems to be a trend that cover block images handled by Jetpack CDN are lower res than expected even if all the other images on the site display fine. 

If there was a way to exempt cover block images from CDN that would be an okay workaround but there's not a way to select a specific block with the existing [photon skip code option](https://jetpack.com/2013/05/03/skip-a-image-with-photon/)

### Steps to reproduce

1. add a cover block to a page with a suitably large image
2. make sure site accelerator is on for images
3. check how image displays on front end
4. compare to with cdn off

### What you expected to happen

The higher quality image should be shown when there isn't something else restricting image size

### What actually happened

For whatever reason the 750 size is routinely displayed even if the connection and the screen allow larger.

Without CDN on: 
![2022-01-17 at 13 13](https://user-images.githubusercontent.com/47717887/149759882-5582f81c-bf16-4634-a9b0-d6d6a3437566.jpg)

With CDN on:
![2022-01-17 at 13 14](https://user-images.githubusercontent.com/47717887/149759922-f06819c1-1d9f-4322-89fa-e5d9ef6dca68.jpg)

### Context

Current case: p9F6qB-87Z-p2

prev case: 3845509-zd-woothemes

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

no

### Workaround details

The workaround is turning off site accelerator for images which impacts the entire site performance

**Comment by cometgrrl** [comment] 2022-01-27 00:34
@Automattic/jetpack is this something y'all could look into?

**Comment by jeherve** [comment] 2022-01-27 08:26
This is something that has come up in the past, https://github.com/Automattic/jetpack/issues/10984, as well as #46420 and #54321. 

I would recommend closing this as duplicate of https://github.com/Automattic/jetpack/issues/10984

**Comment by KirkwallDay** [comment] 2022-03-03 21:38
Another instance here: 4827375-zen

**Comment by rickmgithub** [comment] 2022-05-11 09:31
5205736-zd

**Comment by vajrasar** [comment] 2022-06-21 11:51
Another instance here:

35858932-hc

- [ ] 5313472-zen

**Comment by upwardmomentum84** [comment] 2022-06-23 13:53
Another instance here: 35883217-hc

**Comment by kimerlin81** [comment] 2022-07-01 16:06
And another one - 30744568-hc

- [ ] Please follow up once resolved: 5341490-zd-woothemes

**Comment by jartes** [comment] 2022-10-26 06:31
Another case on [16397704-hc](16397704-hc)

I've deactivated Photon module.

**Comment by wynwin** [comment] 2022-11-05 10:44
Another report in 5685669-zen

**Comment by brittanygray902** [comment] 2022-11-21 18:37
Seeing another case here 38170969 - hc

**Comment by cometgrrl** [comment] 2023-01-14 01:57
> I would recommend closing this as duplicate of https://github.com/Automattic/jetpack/issues/10984

Sounds good to me!  If we get more reports, let's add them to the Jetpack issue.

**Closed as completed** 2023-01-14 01:58 UTC
Labels: Bug, Jetpack, [Pri] Normal, Triaged
