### ISSUE TITLE
Customizer: Changes are not being Saved

### ISSUE THREAD

**Issue by annbingle** [Automattic/wp-calypso#53431] opened 2021-06-05 01:46 UTC
Have seen this issue in 3 interactions now, 2 chats and 1 ticket in which any changes made on their Customizer doesn't get saved when clicked on the Save Changes button. The settings go back to default.

### Steps to reproduce the behavior
(In one of the issues we encountered so far) This is when changing the Colors settings in the Customizer.

1. Go to Appearance > Customize.
2. Click on Colors & Background.
2. Click on Save Changes.

#### What I expected to happen
1. When I make changes in the Customizer, the changes will be displayed on the Preview section and these will remain the same once the changes are saved.

#### What actually happened
1. Once the Save Changes button is clicked, everything resets back to default thus the changes made are not applied on the live site.

### Context

So far same issue happened on these three other interactions.

#### Is this specific to the applied theme? Which one? 
No, so far themes in which the issue is observed are Gema, Dynamic News, Morden, Karuna

#### Does this happen on simple or atomic sites or both?
So far only on Simple Sites

#### Is there any console output or error text?
None.

**Comment by annbingle** [comment] 2021-06-05 01:48
The issues observed on the following tickets:
4044491-zen
4044298-zen
4042732-zen

**Comment by AtrumGeost** [comment] 2021-06-05 15:21
Got another report here:

29967785-hc

I tried deactivating all the plugins and the issue persisted:


https://user-images.githubusercontent.com/3696121/120896454-46bf6e00-c5e7-11eb-8331-759ec98bfb33.mp4

The user asked us to notify when this is solved:

Follow-up: 4045664-zd-woothemes

**Comment by JessBoctor** [comment] 2021-06-05 19:24
Helped with this issue yesterday in #28549294-HC and came across it on a different site today in #29985650-HC. Both were atomic sites.

I found that the issue was being caused by the `theme_mods_{currentTheme}` setting in the options table being set to `-`.

Screenshot here:
![Annotation on 2021-06-05 at 12-22-24](https://user-images.githubusercontent.com/1398304/121056526-22909800-c773-11eb-83fb-d744b3e620c0.png)

This should normally be an array that looks something like this:  `a:9:{ bunch of array text that holds the theme options;}`

I think since the option already exists, the theme can't create a new version. However, since it isn't returning an array as the customizer expects it to, it also can't update the already existing option.

**Comment by JessBoctor** [comment] 2021-06-05 19:38
Just thought I would mention, I did a test and can produce the behavior by manually changing the `theme_mods` option in the DB to `-`

**Comment by ericamQA** [comment] 2021-06-06 00:34
Another instance here: 29988408-hc

Atomic, third party theme (OceanWP)

**Comment by Jaccuse** [comment] 2021-06-06 04:52
I found another case here: 4043466-zen

This one relates to the site's menus, it is a Simple site.

Steps to reproduce: 

1.  Go to Appearance -> Customize -> Menus, pick any menu
2. Select a menu area for that menu, either Primary or Social
3. Save the changes
4. Check the published site or reload the customizer.
5. Both menu areas will be empty.

**Comment by Agepeuve** [comment] 2021-06-06 08:37
Another case in 4043466-zen.

**Comment by louinel** [comment] 2021-06-06 10:19
Another case here: 4045394-zen.

**Comment by hanananah** [comment] 2021-06-06 20:12
Another case: #29987019-hc / #4047801-zen

**Comment by adelineyaw** [comment] 2021-06-07 02:45
Adding more cases: 
4046845-zen
4042773-zen
4046092-zen
4045264-zen
731632-hc / 4049137-zen
30030311-hc / 4052407-zen
22409075-hc
7879291-hc / 4068911-zen

**Comment by vajrasar** [comment] 2021-06-07 08:59
Another case with the theme set as Gema here: 29953587-hc / 4048963-zen

**Comment by jartes** [comment] 2021-06-07 09:28
Another one on 29843673-hc using Storefront. Restoring the site to the previous day solved the issue

**Comment by JuniorTak** [comment] 2021-06-07 11:29
Another case here 4047544-zen, the theme is Dara, the plan  Personal.

**Comment by abcrsol** [comment] 2021-06-07 14:26
Another case reported here #4047879-zen | Personal plan | Theme: Radcliffe 2.

**Comment by syds87** [comment] 2021-06-07 15:19
Another case reported here: #4049887-zen | Premium plan | Theme: Redhill

**Comment by rossanafmenezes** [comment] 2021-06-07 15:38
Another case reported here: 4049893-zen

**Comment by nickpagz** [comment] 2021-06-07 15:59
Another case here #30015580-hc. Site menus on GeneratePress theme.

Fixed using the work-around for AT sites.

**Comment by nickpagz** [comment] 2021-06-07 16:05
Believe this is happening here as well:
#30014756-hc

Premium plan, Shoreditch theme. Background images not saving.

**Comment by JoshuaGoode** [comment] 2021-06-07 16:07
29991578-hc, Premium plan, Twenty Twenty-One.

**Comment by JoshuaGoode** [comment] 2021-06-07 16:12
Checked in on this internally in triage:  p1623082129032400-slack-C02FMH4G8

**Comment by cpapazoglou** [comment] 2021-06-07 16:27
On a second thought, I believe https://github.com/Automattic/wp-calypso/issues/53447 is the root cause. 
While Gutenberg 10.7.1-10.7.3 is live any user that submits the form in `/wp-admin/options-general.php` will have the following 

- their site theme will revert to the default
- their theme mods will be lost

**While pushing a new Gutenberg version will resolve the issue for users submiting the form in `/wp-admin/options-general.php` in the future, it will not fix it for users who already have so**. Since setting the theme to a default is pretty catastrophic, I assume the users affected have already contacted us. In any other case we should seek and restore these settings for the users affected.

Related Gutenberg issue: https://github.com/WordPress/gutenberg/issues/32486
Related WPCOM issue: https://github.com/Automattic/wp-calypso/issues/53447

**Comment by lizswafford** [comment] 2021-06-07 16:36
Another report in 30015931-hc  Personal plan  Coutoire theme.
And, possibly the same for 24845270-hc.

**Comment by cpapazoglou** [comment] 2021-06-07 17:01
For Atomic sites, a quick fix could be 

- Do a full site backup
- Restore to a time prior to user having submitted the form in `/wp-admin/options-general.php`
- Go to https://wordpress.com/hosting-config/ 
- Open phpMyAdmin
- Run `SELECT option_value FROM wp_options WHERE option_name = 'theme_mods_{replace_with_current_theme}';`
- Copy the value
- Restore back to the full site backup
- Go to phpMyAdmin
- Run `UPDATE wp_options set option_value = 'THE_VALUE_YOU_COPIED_ABOVE' WHERE option_name = 'theme_mods_{replace_with_current_theme}';`

**Comment by katiebethbrown** [comment] 2021-06-07 17:28
> For Atomic sites, a quick fix could be

For now we've been pulling a known good copy of the option from a backup and manually restoring it. Full steps here:

p9F6qB-70P-p2

The catch is that if they edit the options-general.php page again it breaks again and we have to repeat the process.

**Comment by sourourn** [comment] 2021-06-07 18:34
Another report: #29971486-hc premium plan, promenade theme.

**Comment by katiebethbrown** [comment] 2021-06-07 18:36
Another report: 28810026-hc
Simple site.

**Comment by cpapazoglou** [comment] 2021-06-07 18:50
There has been a fix just shipped for Simple sites
p1623090391082100/1623077046.081200-slack-C02A41GCS

**Comment by kwight** [comment] 2021-06-07 20:16
Thanks @cpapazoglou !

**Comment by katiebethbrown** [comment] 2021-06-08 00:27
@cpapazoglou  & @kwight - Does the fix stop the issue from occurring, or does it fix sites where it's broken, or both?

Tested on the simple site mentioned here and the changes are still not saving:
p1623098824209400/1623093167.207800-slack-CB0B2G43X

**Comment by happychait** [comment] 2021-06-08 01:44
A customer reached out in 30022883-hc and I couldn't save the menu location.

**Comment by kosiew** [comment] 2021-06-08 05:08
#4051508-zen

https://adahkampspapasblog.com/
AT site

#4051271-zen
https://cordeirorosa.com/
AT site

For both cases, theme_mod_options does not return - 
ref: p9F6qB-70P-p2

**Comment by devNigel** [comment] 2021-06-08 06:02
Another report for a simple site.

20522128-hc
4051635-zen

**Comment by cpapazoglou** [comment] 2021-06-08 06:09
> @cpapazoglou & @kwight - Does the fix stop the issue from occurring, or does it fix sites where it's broken, or both?
> 
> Tested on the simple site mentioned here and the changes are still not saving:
> p1623098824209400/1623093167.207800-slack-CB0B2G43X

It will stop the issue from occurring to more users, affected users will still have a broken experience.

I am reopening this as the fix is not shipped in AT sites.

**Comment by KokkieH** [comment] 2021-06-08 06:13
@cpapazoglou 

> affected users will still have a broken experience

Broken as in the customizations that were removed will still be lost, but they should be able to start using the Customizer again, or broken as in they'll still be unable to save Customizer changes?

**Comment by fresatomica** [comment] 2021-06-08 06:39
I just tested on this site where the user reported the issue, and the settings are still not saving: https://wordpress.com/forums/topic/menus-not-saving/.

**Comment by sanjeev00733** [comment] 2021-06-08 06:56
Another user reported in 30002351-hc

Site: https://thimbletheatrejournal.com/

* Not able to add logo and save changes in customize panel.

**Comment by fresatomica** [comment] 2021-06-08 07:14
Another report: https://wordpress.com/forums/topic/balasana-customizer/

**Comment by cpapazoglou** [comment] 2021-06-08 07:36
> @cpapazoglou
> 
> > affected users will still have a broken experience
> 
> Broken as in the customizations that were removed will still be lost, but they should be able to start using the Customizer again, or broken as in they'll still be unable to save Customizer changes?

All users who have saved the form in `/wp-admin/options-general.php` will still be unable to save Customizer changes unless they are manually restored p9F6qB-70P-p2

The fix just stops the spread. We will look into the possibility of mass restoring the settings for the affected Users.

**Comment by fresatomica** [comment] 2021-06-08 09:16
Another one: https://wordpress.com/forums/topic/wordpress-lost-my-2020-theme/

**Comment by fresatomica** [comment] 2021-06-08 09:45
Another report: https://wordpress.com/forums/topic/pique-one-page-menu-disappeared/

**Comment by mikeicode** [comment] 2021-06-08 12:04
4049861-zen menu and widget aren't updating on the Simple site after saving in the Customizer.

**Comment by fresatomica** [comment] 2021-06-08 12:34
Another one from the forums:
https://wordpress.com/forums/topic/singl-theme-not-customizing/

**Comment by maciejpilarski** [comment] 2021-06-08 13:08
Another report for a simple site.

30018272-hc
4052608-zen

**Comment by Nic-Sevic** [comment] 2021-06-08 13:17
another simple site here: 4048183-hc
asking them to try setting a default theme

**Comment by Sandkorner** [comment] 2021-06-08 16:39
4052568-zen
Simple site that is not saving in the customiser.

**Comment by sbathompson-he** [comment] 2021-06-08 17:03
28805109-hc
A simple site that is not saving in the customizer. The logo will not show or update.

**Comment by sbathompson-he** [comment] 2021-06-08 17:09
24154934-hc
A simple site that is not saving in the customizer. The logo will not show or update.

**Comment by sbathompson-he** [comment] 2021-06-08 17:19
3203272-hc
A simple site that is not saving in the customizer. The logo will not show or update.

**Comment by chrisfromthelc** [comment] 2021-06-08 17:24
Another one in 163212-hc.

**Comment by abcrsol** [comment] 2021-06-08 17:30
Two cases: 4053222-zen and 4052705-zen

**Comment by chrisfromthelc** [comment] 2021-06-08 17:55
Another: 30037126-hc

**Comment by dhackneya8c** [comment] 2021-06-08 18:03
Another report: 22951768-hc

**Comment by macmanx2** [comment] 2021-06-08 18:09
Two more: https://wordpress.com/forums/topic/theme-background-3/ and https://wordpress.com/forums/topic/page-attributes-26/

**Comment by noteeth** [comment] 2021-06-08 18:09
Another report: 30036865-hc

**Comment by ckmccoy2** [comment] 2021-06-08 18:24
One more: 30036677-hc.

Logo and site icon will not show or update similarly as to what others have mentioned above. User was using cerauno theme, but when changed to twentytwentyone, logo did display.

**Comment by wprhunt** [comment] 2021-06-08 18:43
Another one:
30037732-hc

Their logo was removed after saving a change. I had to add CSS for them to add the logo back.

**Comment by dcoleonline** [comment] 2021-06-08 19:01
I had one with the Luxury theme at #28159019-hc.
I wasn't able to tell for sure if the cause was this issue or third party plugins/configuration/code they added.
For now I gave them a CSS workaround to show the image as the background for the logo link element. They already had a CSS plugin active, so I added it there instead of in the customizer.

Edit, sharing to the new issue here https://github.com/Automattic/wp-calypso/issues/53517#issuecomment-857030684

**Comment by sourourn** [comment] 2021-06-08 19:56
Another report: #28746123-hc the logo will not show or update

**Comment by jp-imagines** [comment] 2021-06-08 20:28
30039256-hc
User unable to update their site's menu.

**Comment by dhackneya8c** [comment] 2021-06-08 21:47
Another report: 4053327-zen

**Comment by kcswong** [comment] 2021-06-08 22:42
Report and follow up in 4050997-zen

**Comment by ersatzpenguin** [comment] 2021-06-09 15:23
Another report of this—settings in the Customizer are saving (and are visible when returning to the customizer), but are not being applied to the site itself.

Follow up here: 4056281-zen

**Comment by davipontesblog** [comment] 2021-06-09 15:44
@kwight I think we need to leave this issue open until the following is true:
- Existing sites are fixed
- Sites in both simple and atomic are fixed
So we know this is not an issue anymore for customers in general.
What options are we entertaining to this measure, at this time? Would restoring WordPress.com to a previous version of Gutenberg fix this in the contexts outlined above? Do we need another point release shipped? Trying to understand the issue a bit better.
Thanks!

**Comment by metabreakr** [comment] 2021-06-09 17:11
4052185-zen

**Comment by ckmccoy2** [comment] 2021-06-09 18:19
4054412-zen

**Comment by mikeicode** [comment] 2021-06-09 19:34
Simple site 4053784-zd-woothemes (needs to be notified when resolved)

**Comment by Jaccuse** [comment] 2021-06-09 19:35
Another report from a Simple site: 23527050-hc

**Comment by syedshaon** [comment] 2021-06-10 04:01
4052869-zen 
Theme: Escutcheon

**Comment by KokkieH** [comment] 2021-06-10 05:47
Another: https://wordpress.com/forums/topic/theme-background-changed/

Their theme was changed automatically five days ago, and while they can switch back to the original theme, they can't save any changes.

**Comment by cpapazoglou** [comment] 2021-06-10 07:40
Initial discovery of the sites affected pa1C6h-10X-p2#comment-6664

Here is some draft code used for the research 
D62614-code

**Comment by ivan-ottinger** [comment] 2021-06-10 07:55
Another one: 4048687-zd-woothemes

The site's theme also switched from `Nikau` to `Pique` automatically.

**Comment by aleone89** [comment] 2021-06-10 09:32
Another one: zen-4047533 

The theme in use in this instance is/was: Button 2.

**Comment by ahmadbaig1** [comment] 2021-06-10 15:59
30036437-hc
A simple site that is not saving in the customizer. The logo will not show or update.

**Comment by AtrumGeost** [comment] 2021-06-10 17:32
Hi folks!

The user in 4045134-zd-woothemes is asking if we have an estimated time for a fix. They want to know if changing themes might help them fix the issue.

**Comment by kriskarkoski** [comment] 2021-06-10 18:10
4059624-zd
Maywood theme
Unable to save title/tagline or get a menu to display. 
Changing themes and back did not help before I realized it was this issue

**Comment by TambahBaikCom** [comment] 2021-06-11 01:29
Hi, I was offered to get help added the CSS from the back-end? (I don't know what to call it). So I provided the CSS code and a friendly Happiness Engineer helped me to put the code to the Additional CSS. Unfortunatelly the change was also failed to save. It seems the issue will not let people make change to the customizer even if it was done from the Happiness Engineer side. I think the short-term solution is to ask user to use any other unaffected themes until the problem solved. In my case, I can do change to Independent Publisher 2 theme and still can't do any change for my beloved Twenty Twenty & Twenty Twenty One theme.

**Comment by nagpai** [comment] 2021-06-11 03:55
#16258878-hc

Atomic site 
Custom theme - Cakecious

Error persists even after changing themes
Shared WP admin option to change menu. Did not work

**Comment by aleone89** [comment] 2021-06-11 08:18
Another report: zen-4056504 

obsidian theme in use.

**Comment by aleone89** [comment] 2021-06-11 11:04
Another report: hc-29825074

Shawburn theme in use.

**Comment by ClassicRKR27** [comment] 2021-06-11 16:35
Another report here with Seedlet theme: 28812304-hc

Follow-up ticket is here: 4061821-zd-woothemes

**Comment by ezebecke** [comment] 2021-06-11 18:20
Another report here with Ixion theme: 30090916-hc

Follow-up ticket is here: 4061895-zd

**Comment by lizswafford** [comment] 2021-06-11 21:11
4060267-zen  Rowling theme.

**Comment by kaitohm** [comment] 2021-06-12 02:46
Another case: 4051635-zd-woothemes

**Comment by the-misha** [comment] 2021-06-12 18:39
Another report: 4050480-zd-woothemes

**Comment by nerdysandy** [comment] 2021-06-12 21:58
Gema theme #4044298-zd-woothemes

**Comment by sourourn** [comment] 2021-06-13 11:47
Another report: #30116280-hc
AT site, health-center theme. Menu not saving or displaying.

**Comment by philnick206** [comment] 2021-06-14 14:01
Another report #30027352-hc

**Comment by dolgelukkig** [comment] 2021-06-14 16:11
Another one, simple site, theme Cyanotype #4067678-zd

**Comment by metabreakr** [comment] 2021-06-14 17:32
30095515-hc / 4068184-zn

**Comment by kwight** [comment] 2021-06-14 17:47
@cpapazoglou Just curious what stage this is at – are the additional reports indicating that the initial cause is still active, or are you at the "attempt to backfill" stage?

**Comment by sbathompson-he** [comment] 2021-06-14 17:50
This occurred here: 30137706-hc

**Comment by cpapazoglou** [comment] 2021-06-15 06:16
> @cpapazoglou Just curious what stage this is at – are the additional reports indicating that the initial cause is still active, or are you at the "attempt to backfill" stage?

- The initial cause is not active for blogs having Gutenberg 10.7.4, just tested it in both Simple & Atomic sites.
- We are on an attempt to mass fix the affected sites 
pMz3w-dg9-p2_mods_stylesheet-option-values-in-wpcom-for-a-list-of-blog_ids/
D62614-code

**Comment by CoachBirgit** [comment] 2021-06-15 10:53
simple site (personal plan) | Rivington theme → user can't save menu position settings | zen-4068021

**Comment by Sandkorner** [comment] 2021-06-15 17:34
ZEN-4069658
AT Site, Quintus theme - Cannot save the background color of the main content area in the customiser.

**Comment by thesacredpath** [comment] 2021-06-16 02:42
> > @cpapazoglou Just curious what stage this is at – are the additional reports indicating that the initial cause is still active, or are you at the "attempt to backfill" stage?
> 
>     * The initial cause is not active for blogs having Gutenberg 10.7.4, just tested it in both Simple & Atomic sites.
> 
>     * We are on an attempt to mass fix the affected sites
>       pMz3w-dg9-p2_mods_stylesheet-option-values-in-wpcom-for-a-list-of-blog_ids/
>       D62614-code

Any update on the progress on this fix? Have one user back in Chat asking about the progress.

Transcript: #30162729-hc

**Comment by cpapazoglou** [comment] 2021-06-16 08:32
> > > @cpapazoglou Just curious what stage this is at – are the additional reports indicating that the initial cause is still active, or are you at the "attempt to backfill" stage?
> > 
> > 
> > ```
> > * The initial cause is not active for blogs having Gutenberg 10.7.4, just tested it in both Simple & Atomic sites.
> > 
> > * We are on an attempt to mass fix the affected sites
> >   pMz3w-dg9-p2_mods_stylesheet-option-values-in-wpcom-for-a-list-of-blog_ids/
> >   D62614-code
> > ```
> 
> Any update on the progress on this fix? Have one user back in Chat asking about the progress.
> 
> Transcript: #30162729-hc

Still waiting for the correct data to do the restore, **simple** blogs created before May 27, 2021 should be OK! Blogs created after May 27, 2021 (like the one you mentioned) are on the waitlist pMz3w-dg9-p2#comment-89079 as also Atomic blogs.

**Comment by SuzzieG** [comment] 2021-06-17 06:07
4068620- zen using theme: Redhill

**Comment by kriskarkoski** [comment] 2021-06-22 16:14
4044298-zen was asking for an update. I offered them a partial refund for the trouble and to move their plan and content to another site that should not be impacted since we don't know when a fix will be ready.

**Comment by metabreakr** [comment] 2021-06-22 19:38
4086494-zen, also following Kris' lead.

**Comment by cpapazoglou** [comment] 2021-06-23 08:00
👋 there! The data restoration to Simple (pMz3w-dg9-p2#comment-89273) & Atomic (pbuNQi-1pA-p2#comment-2526) sites has been finished yesterday (June 22nd). There might be cases where we didn't have a restore value cause of:

(a) the date specified was older than the backup retention policy.
(b) the site was created after the backup prior to the timestamp specified. 
(c) restored tables don’t have good data in them because the option was initially created in a corrupted state during the duration of the bug, not transformed from a known-good state to a corrupted one.

For the above problematic cases, and only for **currently** corrupted values I have updated them to the following defaults:

(a) stylesheet -> twentytwentyone
(b) theme_mods_% -> a:2:{s:18:"nav_menu_locations";a:0:{}s:18:"custom_css_post_id";i:-1;}

The above will allow Users to save new changes to the customizer.

Noting here, that _there still might be some edge cases_ where blogs have corrupted values. We should handle them manually:
- Simple sites, use `wpsh` shell in wpcom sandbox and run an update query. In Simple sites we are going to restore defaults, since we don't have a good value in a backup. p7DVsv-bZF-p2
- Atomic sites, p9F6qB-70P-p2

**Comment by cpapazoglou** [comment] 2021-06-23 08:02
> 4044298-zen was asking for an update. I offered them a partial refund for the trouble and to move their plan and content to another site that should not be impacted since we don't know when a fix will be ready.

> 4086494-zen, also following Kris' lead.

Can you let me know whether the bug was reproducible before posting here?

**Comment by marianearchimbaud** [comment] 2021-06-24 19:56
This user reported the same issue, and it has not been solved. I was able to reproduce this: 4050480-zen Using theme Promenade

**Comment by jp-imagines** [comment] 2021-06-24 21:26
User reported this in 4090205-zen (Coutoire theme). I was able to replicate on my end.

**Comment by radtechgh** [comment] 2021-06-24 21:30
User reported this in 4093227-zen (Radcliffe 2 theme). Was able to reproduce, menu reverts to none.

**Comment by devNigel** [comment] 2021-06-25 03:47
The issue still persists on their new account with the theme Libre 2 for the case 4086494-zen

I also see other reports about the issue. Hence, I am reopening this issue.

cc: @kriskarkoski @jonnyruzek

**Comment by sanjeev00733** [comment] 2021-06-25 06:05
Another report in 13388644-hc

Theme: Rebalance
The site logo isn't saving

**Comment by cpapazoglou** [comment] 2021-06-25 07:42
I have fixed:
- 4050480-zen cc @marianearchimbaud 
- 4090205-zen cc @JeffPare 
- 4093227-zen cc @Camaropilot 
- 4086494-zen for theme `libre-2` cc @devNigel 
- 13388644-hc for theme `Rebalance` cc @sanjeev00733 

Please refer to this P2 p7DVsv-bZF-p2 for future reports / incidents.

**Comment by kosiew** [comment] 2021-06-25 08:12
Hi @cpapazoglou ,

Reopening - #4094027-zen too has the same issue.
Theme: Fortune
They tried to set site identity logo 
https://d.pr/i/4Uk2tf but it does not save.

Can you take a look?
Thanks

**Comment by kosiew** [comment] 2021-06-25 08:25
Closing this in deference to p7DVsv-bZF-p2

**Comment by kosiew** [comment] 2021-06-25 08:26
Close.

**Comment by AlexanderMonsanto** [comment] 2021-06-26 10:11
another report from yesterday 4094725-zen

**Comment by ahmadbaig1** [comment] 2021-06-28 09:39
Reopening as found another report.
Site logo not getting changed even after saving. 
30364477-hc
Theme- Stow

**Comment by cpapazoglou** [comment] 2021-06-28 13:36
Please do not reopen this issue as the root cause has been fixed. 

Please refer to this P2 p7DVsv-bZF-p2 for future reports / incidents on how to fix the data corrupted.

**Closed as completed by cpapazoglou** 2021-06-28 13:36 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] High, [Feature] Customizer, [Impact] High, Triaged
