### ISSUE TITLE
Reader: Tracks property `subscription_count` is not working

### ISSUE THREAD

**Issue by martinremy** [Automattic/wp-calypso#47678] opened 2020-11-23 17:32 UTC
This property should be [present for all reader events](https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/reader/stats.js#L114), but is 0 or missing for most/all reader Tracks events.  p5PDj3-4WA

**Comment by bluefuton** [comment] 2020-11-23 20:39
Long-standing bug this one :(  

Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/14470.

**Closed as completed by bluefuton** 2020-11-23 20:39 UTC
Labels: Bug, [Feature] Reader
