### ISSUE TITLE
Settings: Site selection is broken when browsing to /settings/:slug

### ISSUE THREAD

**Issue by jblz** [Automattic/wp-calypso#15011] opened 2017-06-12 19:34 UTC
#### Steps to reproduce
Browse to URL: https://wordpress.com/settings/anyslugyoutryherewillcausethis.example.com

#### What I expected
* When supplying a slug for a site which I am an admin, I expected to be redirected to the settings for that site
* When supplying a slug for a site which does not exist or for which I'm not an admin, the site selector UI should work

#### What happened instead
Regardless of the slug provided, I'm shown a site selector UI & clicking a site in the list does nothing.

#### Browser / OS version
Chrome 59. Mac Sierra

**Comment by alisterscott** [comment] 2017-07-31 04:13
Duplicate of #11543

**Closed by alisterscott** 2017-07-31 04:13 UTC
Labels: Site Picker, Site Settings, Sites, [Type] Bug
