### ISSUE TITLE
Site Timezone Type - Bucarest instead of Bucharest in EN-GB Interface Language

### ISSUE THREAD

**Issue by mdomocos** [Automattic/wp-calypso#83600] opened 2023-10-27 16:51 UTC
### Quick summary

There'a a typo on the value of the timezone selector for Europe/Bucharest, it's Bucarest instead of Bucharest

### Steps to reproduce

1. You are logged into https://wordpress.com/
2. Enter any site
3. Go into Settings - General
4. In Site Timezone look for Bucharest

### What you expected to happen

I'd expect to see Bucharest

### What actually happened

I see Bucarest

### Impact

All

### Available workarounds?

There is no user impact

**Comment by mdomocos** [comment] 2023-10-27 16:52
![image](https://github.com/Automattic/wp-calypso/assets/4470916/e9a11391-0c50-4ae4-b1a8-4b94b4a9df9e)

**Comment by cuemarie** [comment] 2023-10-30 20:27
📌 REPRODUCTION RESULTS
- Tested on Simple – ~Could Not Replicate~ – [see below](https://github.com/Automattic/wp-calypso/issues/83600#issuecomment-1796859518)
- Tested on Atomic – ~Could Not Replicate~ – [see below](https://github.com/Automattic/wp-calypso/issues/83600#issuecomment-1796859518)

📌 FINDINGS/SCREENSHOTS/VIDEO
Checked on multiple sites, and with my interface set to a few different languages, but all tests showed the correct spelling. 

![Markup on 2023-10-30 at 13:21:35](https://github.com/Automattic/wp-calypso/assets/27249804/b71b4bcd-b0c9-4fb5-91cf-b48ae7f87954)

📌 ACTIONS
- Requested author feedback

📌 Message to Author
It's possible this was resolved since this report was opened. @mdomocos are you still seeing the incorrect `Bucarest` spelling on your site?

**Comment by mdomocos** [comment] 2023-10-31 06:50
@cuemarie this is odd, i logged in again, into another site and i have the same issue. I tested it in Chrome.

https://wordpress.com/settings/general/staging-15db-electronicbrowser9.wpcomstaging.com

![image](https://github.com/Automattic/wp-calypso/assets/4470916/1a81ee9a-1710-47ef-bc8c-aba2df3e5762)

**Comment by cuemarie** [comment] 2023-11-06 22:18
@mdomocos interesting, thanks for checking another site!  It looks like if the **Interface Language** under `https://wordpress.com/me/account` is set to EN GB or English (UK), that's where the `Bucarest` spelling occurs, no matter what browser:

![Image](https://github.com/Automattic/wp-calypso/assets/27249804/64659c24-5b80-4493-90fa-0d63b7434532)


![Image](https://github.com/Automattic/wp-calypso/assets/27249804/b52dc274-c863-4ad0-990c-c9481e2fdf33)


📌 ACTIONS
- Triaged

**Comment by katinthehatsite** [comment] 2024-09-02 18:56
The problem was the type in this string in Glotpress: https://translate.wordpress.com/projects/wpcom/en-gb/default/?filters%5Bterm%5D=Bucharest&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

It should be fixed once the translations are released next Monday!

**Comment by katinthehatsite** [comment] 2024-09-03 18:18
The translations were deployed and I can see the spelling correctly on my end now with UK English:

<img width="739" alt="Screenshot 2024-09-03 at 8 17 58 PM" src="https://github.com/user-attachments/assets/7d9d6c81-8fd8-45e0-a371-fabe9a9be3ba">

I am closing this as completed on my end.

**Closed as completed by katinthehatsite** 2024-09-03 18:18 UTC
Labels: Bug, [Feature] Site Settings, [Pri] Normal, Triaged, [Product] WordPress.com, [Feature Group] Site Settings & Tools, Groundskeeping
