### ISSUE TITLE
Site setup complete; crashing customer home after launch

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#51311] opened 2021-03-23 12:51 UTC
Customer home checklist crashes after site launch for sites without menu.

### Steps to reproduce the behavior

1. Go to wordpress.com/new/
2. Enter a site name
3. Pick a free domain
4. Pick a design with the blank canvas theme, one of these will do:

    <img width="500" alt="Screenshot 2021-03-23 at 14 44 50" src="https://user-images.githubusercontent.com/87168/112148607-bd52ef00-8be6-11eb-8fe6-17699bc2e13d.png">

5. When in the editor, hit "launch"

    <img width="500" alt="Screenshot 2021-03-23 at 14 45 25" src="https://user-images.githubusercontent.com/87168/112148760-ed9a8d80-8be6-11eb-8480-35f7fa753695.png">

6. When at confirmation, press "back home"

    <img width="500" alt="Screenshot 2021-03-23 at 14 45 55" src="https://user-images.githubusercontent.com/87168/112148726-e2dff880-8be6-11eb-8d66-10ed821d3ce9.png">

7. At customer home, press Show site setup

    <img width="500" alt="Screenshot 2021-03-23 at 14 46 11" src="https://user-images.githubusercontent.com/87168/112148803-fab77c80-8be6-11eb-94f7-6e15940149b2.png">

8. Observe completed site list appear for a moment, and then the whole page to crash with error in console:

    <img width="1452" alt="Screenshot 2021-03-23 at 14 41 38" src="https://user-images.githubusercontent.com/87168/112148859-0b67f280-8be7-11eb-8e69-d6de1f7e3917.png">

    Something here:

    <img width="500" alt="Screenshot 2021-03-23 at 14 41 55" src="https://user-images.githubusercontent.com/87168/112148868-0dca4c80-8be7-11eb-87cb-8a8a520751ea.png">

    See https://github.com/Automattic/wp-calypso/search?q=START_SITE_SETUP

**Comment by alshakero** [comment] 2021-03-23 14:20
I tried reproducing this in Chrome, FF, Edge, and Safari and couldn't. And because the error seems to involve React DevTools, I tried to repro on FF and Chrome with RDT installed, and still couldn't reproduce it. 

Might there be any more context?

**Comment by creativecoder** [comment] 2021-03-23 16:01
I was able to reproduce locally in Firefox, selecting the Fredrickson theme.

I’m not clear about the detailed workings of the checklist these days, but generally what’s happening is
- The first task has an id of `start_site_setup`
- The task is autocompleted (since it's actually resolved during the onboarding flow), and a request is made to the `/checklist` endpoint to mark it's completion
- The response comes back with a revised checklist, at this point all tasks are actually complete and this causes `start_site_setup` to be removed from the list of tasks on the server.
- The `SiteSetupList` component still has `start_site_setup` as the current task id… but the task has disappeared from the state tree, so there's an error...

Started on a PR to address this: https://github.com/Automattic/wp-calypso/pull/51324

**Comment by creativecoder** [comment] 2021-03-24 19:32
Digging into this over the last day, I'm increasingly convinced the root cause is how we duplicate checklist logic between server and client. The [entire get-task.js file](https://github.com/Automattic/wp-calypso/blob/37f6e8f4a1a5008763fe390d182b63033371dfc4/client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js) (the origin of the JS error) bolts on information about tasks that comes from the server and should be integrated with server side code and then deleted.

---

But for now, here are some smaller changes that fix the issue. The diff is the primary fix.

D59219-code

The wp-calypso PR isn't strictly necessary, but hardens some issues I saw while exploring a fix.

https://github.com/Automattic/wp-calypso/pull/51324

Both are ready for review.

**Comment by creativecoder** [comment] 2021-03-30 19:32
D59219-code has been deployed, so I'm closing the issue.

Though https://github.com/Automattic/wp-calypso/pull/51324 still needs a review.

**Closed as completed by creativecoder** 2021-03-30 19:32 UTC
Labels: Bug, [Pri] Normal, [Feature] My Home
