### ISSUE TITLE
Manage Page: Follow by URL not detecting things you already follow

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#16152] opened 2017-07-12 18:38 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/following/manage
2. Enter the URL of something you're already following

#### What I expected

Page to show me that I'm already following that URL. And, if I still submitted the form, display an error that says "You're following URL." 

#### What happened instead

The page allows me to follow the already-followed URL, a new placeholder appears and never resolves.

#### Browser / OS version

Safari, OS X, latest

#### Screenshot / Video

<img width="795" alt="screen shot 2017-07-12 at 11 32 11 am" src="https://user-images.githubusercontent.com/24388/28133906-3914bffc-66f6-11e7-84d7-03c8c3132162.png">

In the screen above, the blue "Follow coldantlerfarm.blogspot.com" should be green "Following coldantlerfarm.blogspot.com".
 
<img width="883" alt="screen shot 2017-07-12 at 11 32 18 am" src="https://user-images.githubusercontent.com/24388/28133949-5f2cb988-66f6-11e7-9a75-95eeb6818a7d.png">

Once submitted, the notification makes it appear that I wasn't following the URL before, and the new placeholder never resolves.

cc @samouri

**Comment by samouri** [comment] 2017-07-12 18:55
A few things:

The first part of this issue: `incorrect following status`,  we can't solve yet with our current infrastructure.  We won't be able to for sure know if you are following a url because the actual feed_url may change during the following process. (e.g. redirecting `/` to `/feed.xml` etc).

Given that we can't solve number1,  we have a second issue: the optimistic notification. I'm not sure what we want to do here.  In order to stop errantly sending out the notice for this edgecase we would need to turn off all optimistic notices.

Lastly theres the problem with the placeholder.  This is just a bug and we should fix it

**Comment by samouri** [comment] 2017-07-12 18:58
potentially a regression since: https://github.com/Automattic/wp-calypso/issues/13934

**Comment by fraying** [comment] 2017-07-12 19:00
Thanks for the added info, @samouri! I don't think we want to change the optimistic notification. Usually it's the right thing to do.

So let's just make this issue about the placeholder?

Is there an issue on the incorrect following status, at least for tracking?

**Comment by jeherve** [comment] 2017-09-21 19:05
I can't seem to reproduce this right now; the site I already follow appears at the top of the page:

![screenshot 2017-09-21 at 21 05 08](https://user-images.githubusercontent.com/426388/30713740-939a5764-9f10-11e7-9a83-90367ab2e957.png)

**Comment by samouri** [comment] 2017-09-21 19:41
Thanks for the prod @jeherve !

the incorrect following status only happens in specific cases.
If the placeholder issue is fixed then lets close this issue!

**Comment by samouri** [comment] 2017-09-21 19:42
I've just confirmed the placeholder issue is fixed.  
Feel free to reopen if I misunderstood what you were getting at @jeherve

**Closed by samouri** 2017-09-21 19:42 UTC
Labels: Reader, [Type] Bug
