### ISSUE TITLE
Nav Unification: "Show Advanced" Option Hides "Add New" Theme Button on Simple Biz Sites

### ISSUE THREAD

**Issue by ersatzpenguin** [Automattic/wp-calypso#51672] opened 2021-04-04 15:28 UTC
### Steps to reproduce the behavior

1. Enable the "Show advanced dashboard pages" option in account settings.
2. Navigate to a simple AT site.
3. Open the "Themes" page.
4. Try to add/upload a theme.
5. See error

#### What I expected to happen
I expected to be given the option to upload a theme, which is present in the Calypso themes page for simple Business plan sites, and which looks like this on an AT'd site with Nav Unification and the "Show advanced" setting turned on:

![atomic themes page](https://user-images.githubusercontent.com/10101587/113513423-46472000-952f-11eb-8517-ef7e701330a0.png)

#### What actually happened
There is a WP-Admin style themes page displayed, but it's missing the options to add a new theme:

![non-at biz themes page](https://user-images.githubusercontent.com/10101587/113513405-37f90400-952f-11eb-94d1-bc1b04f221d8.png)

### Context
This came up in: 3878828-zd-woothemes

#### Browser / OS version
N/A. This appears to impact all browsers.

#### Is this specific to the applied theme? Which one?
No.

#### Does this happen on simple or atomic sites or both?
The issue is specific to simple Business plan sites.

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
This does not block purchases, but it requires a workaround where we direct folks to Tools > Hosting Configuration to AT their site when they should be able to upload a theme and AT their site straight from the Themes page.

A major selling point of the Business plan is that it allows uploading third-party themes, so for the option to be missing when using the "Show advanced" setting seems significant.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
See above.

**Comment by cpapazoglou** [comment] 2021-04-05 16:25
@ersatzpenguin Thanks for reporting. This is a regression. We should always show the Calypso Themes screen for Simple sites.

Probably a faster workaround would be going to `https://wordpress.com/themes/` directly for that site for the time being.

cc @mrfoxtalbot for visibility

**Comment by zdenys** [comment] 2021-04-06 07:58
Possibly a duplicate of https://github.com/Automattic/wp-calypso/issues/51663?

**Comment by cpapazoglou** [comment] 2021-04-06 08:46
Correct @zdenys, closing this as duplicate of #51663.

**Closed as completed by cpapazoglou** 2021-04-06 08:46 UTC
Labels: Bug, [Pri] High, [Feature] Calypso & wp-admin Navigation
