### ISSUE TITLE
Editor background is dark gray when not using theme styles

### ISSUE THREAD

**Issue by tvolpert** [Automattic/wp-calypso#86082] opened 2024-01-06 20:45 UTC
### Quick summary

With Gutenberg plugin active, and the `use theme styles` setting turned off under Preferences in the page/post editor, the editor background turns dark gray, but still uses black text, making it practically unreadable. **Deactivating Gutenberg resolves the issue.**

<img width="1493" alt="Screenshot 2024-01-06 at 2 29 37 PM" src="https://github.com/Automattic/wp-calypso/assets/34486913/c19cf056-4e43-4278-a9a6-fe9680175c27">

### Steps to reproduce

1. start with an atomic site and make sure the Gutenberg plugin is active
2. add a new page or post (or edit an existing one)
3. click the three-dots in the top-right corner of the editor, then preferences > appearance, and turn off `use theme styles`
4. crank up your monitor's brightness to read any of the text in the editor
![Screen Capture on 2024-01-06 at 14-31-13](https://github.com/Automattic/wp-calypso/assets/34486913/17b28b36-f58d-45e4-8975-444d1fbcfb61)

### What you expected to happen

if not using the theme's styles, the editor should still be legible. there's barely any contrast between the font color and the background here making it all but impossible to work with

### What actually happened

the background is dark gray with black text

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

It seems to only affect block themes - I tried a few classic themes and didn't have the same issue there

**Comment by tvolpert** [comment] 2024-01-06 20:45
reported in 7545301-zd-a8c

**Comment by rw-ye** [comment] 2024-01-08 05:37
Another report here: 7541861-zd-a8c

Theme: Masu

Asked the user to enable `Use theme styles` in the page editor as a workaround.

**Comment by maciejpilarski** [comment] 2024-01-08 20:35
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue on my side:
![Markup on 2024-01-08 at 21:33:43](https://github.com/Automattic/wp-calypso/assets/9025643/158a0fb8-9c39-4d44-aa55-c48ec86ec41a)

📌 ACTIONS
- Triaged

**Comment by jp-imagines** [comment] 2024-01-11 17:04
Another report in `7570885-zd-a8c` (Payton theme). Suggested enabling `use theme styles` toggle as a workaround.

Edited to add: this user is requesting a follow-up once this is fixed.

**Comment by danielbachhuber** [comment] 2024-01-14 16:49
I ran into this with the Beaumont theme.

**Comment by liviopv** [comment] 2024-05-11 10:44
Not exactly the same issue, but it looks like the GB 18.3 merge yesterday triggered more issues related to theme styles not showing in the Post/Page Editor.

8176884-zd-a8c

This site has Skivers active with a custom background, and when Gutenberg is active, the editor shows a white background, even when the "Use theme styles" is active.

I wasn't able to reproduce on my Atomic site with the same theme/setup.

**Comment by liviopv** [comment] 2024-05-11 14:27
Same as https://github.com/Automattic/themes/issues/7777

**Comment by Robertght** [comment] 2024-05-11 14:28
7875379-zen
Theme: Sten

Work ok if I disable Gutenberg. 
I was able to replicate this locally.

**Comment by upwardmomentum84** [comment] 2024-05-11 19:05
8177939-zd-a8c

Works ok if Gutenberg is deactivated.

**Comment by Greatdane** [comment] 2024-05-12 23:25
I also noticed this with a site, Deactivating Yoast SEO fixed the issue on that occasion

**Comment by Greatdane** [comment] 2024-05-13 00:52
8181276-zd-a8c
Gutenberg disabled fixed the issue

**Comment by MaggieCabrera** [comment] 2024-05-20 15:53
Hi! in 18.3 we made [this](https://github.com/WordPress/gutenberg/pull/60873) change but we still have [this CSS](https://github.com/WordPress/gutenberg/blob/a4dfd4e52c0ff919319fe36f54a243f87e7dd861/packages/block-editor/src/components/iframe/index.js#L281) that should color the body white. I could not reproduce this with Sten and the Use theme styles deactivated. It should be showing white instead of gray (and in any case, our change was setting the gray to #ddd which shouldn't be as dark as the report suggests. I would welcome help reproducing this

**Comment by liviopv** [comment] 2024-06-13 13:18
@MaggieCabrera I can't repro anymore. I think the fix for https://github.com/Automattic/themes/issues/7777 also fixed it. Closing.

**Closed as completed by liviopv** 2024-06-13 13:18 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] High, Triaged, Customer report [LEGACY], [Platform] Atomic, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience
