### ISSUE TITLE
Expand Photo Cards In Place

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10188] opened 2016-12-20 19:32 UTC
This is an idea to make full photos easier to get to.

Photo cards would load as normal:

![default](https://cloud.githubusercontent.com/assets/24388/21364847/71d6ac00-c6a7-11e6-985c-ef5d5ee8cd0b.jpg)

But clicking anywhere in the photo would change the display to show the whole photo. After click:

![clicked](https://cloud.githubusercontent.com/assets/24388/21364873/8c046f72-c6a7-11e6-9f19-7a1b73fd3e93.jpg)

Since the image is already loaded, this change would be instant.

Clicking the photo again would go to the fullpost page as normal.

There's no way to "close" the photo to go back to the default view. I thought about it, but I don't think the added UI is necessary. This matches the way Video cards work – you can click to expand, but there's no way to contract. You just keep scrolling as normal.

I'd like to give this a try to address some of the complaints. What do you think, @jancavan?

**Comment by fraying** [comment] 2016-12-20 19:55
Thinking through the logic: 

On the first click, the bounding box should expand to the height of the image, or the height of the browser, whichever is smaller. In other words, the photo shouldn't be allowed to get taller than one screen. If the photo is still larger than the bounding box, it'll center within the box, as it does already.

This possible?

**Comment by jancavan** [comment] 2016-12-21 00:05
I think this is a good solution we could try as this doesn't take users to an entirely new page. If the images are really tall though, might feel a bit jumpy transitioning from (what seems to be) landscape to portrait.

![screenshot 2016-12-20 16 02 13](https://cloud.githubusercontent.com/assets/4924246/21372744/0728013e-c6ce-11e6-92f9-0ed33cdb6020.png)

![screenshot 2016-12-20 16 04 38](https://cloud.githubusercontent.com/assets/4924246/21372745/0916e15e-c6ce-11e6-89a0-fa2ca76f553e.png)

I also don't think it's quite obvious that clicking/tapping on a photo would show you the full view since the expected behavior now is for all cards to jump to full-post, but part of me also thinks that it's really not a big deal once users figure it out.

**Comment by fraying** [comment] 2016-12-21 00:08
Yeah! Let's try it!

**Comment by fraying** [comment] 2016-12-21 00:08
I was also thinking we could add a link title to the image like "Click to expand" to help people discover it.

**Comment by fraying** [comment] 2016-12-21 00:10
Also note that, in my mockup, I preserved the bottom fade and title in the expanded view. I think it's important to keep those. Helps reinforce the idea that you're expanding what's there already.

**Comment by samouri** [comment] 2016-12-30 18:36
closing this because we landed #10215

**Closed by samouri** 2016-12-30 18:36 UTC
Labels: Reader, [Type] Enhancement
