### ISSUE TITLE
Reader: Minor display issue with longer words in Spanish

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#84164] opened 2023-11-14 14:06 UTC
On the `/discover` page, sometimes longer titles wrap incorrectly in Spanish.

![image](https://github.com/Automattic/wp-calypso/assets/917632/7e03ed57-dd0b-4531-90d5-cdb9ac5fac3f)

Original report: p1699911613566089/1699910120.541379-slack-C02FMH4G8

**Comment by liviopv** [comment] 2023-12-27 09:26
📌 REPRODUCTION RESULTS
- Tested on Chrome for Android – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
![Screenshot_20231227-092315](https://github.com/Automattic/wp-calypso/assets/14153300/08185b25-ed7f-44d5-a14a-50b1026fb1bc)

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@markbiek it looks like this might have been fixed already, as I could not reproduce on Chrome for Android. If you still see this issue in another browser/device combo, please reopen.

**Closed as completed by liviopv** 2023-12-27 09:26 UTC
Labels: Bug, [Feature] Reader, [Closed] Not Reproducible, [Pri] TBD
