### ISSUE TITLE
Categories/Taxonomies: Error When Updating Descriptions on Simple Sites

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#88590] opened 2024-03-17 10:54 UTC
### Quick summary

It is currently not possible to update categories or taxonomies in Calypso.

### Steps to reproduce

1. Go to `/settings/taxonomies/category` on a Simple site 
2. Try to edit a category description 
3. Save

### What you expected to happen

The category should update.

### What actually happened

The button remains disabled, and nothing happens. There is the following console error:

<img width="1219" alt="Screenshot 2024-03-17 at 10 54 11" src="https://github.com/Automattic/wp-calypso/assets/43215253/ddcdceb0-6e31-45d6-a7b9-d4cd9c29b26f">

### Impact

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

7890888-zen 

Seems to work fine when using WP-admin.

**Comment by retnonindya** [comment] 2024-03-20 12:48
📌 REPRODUCTION RESULTS
- Tested on Simple – Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
I can't replicate the issue. At least on my end here.

![Mar-20-2024 20-46-58](https://github.com/Automattic/wp-calypso/assets/44726232/99fd0d79-1239-4762-8bd5-ecea9896dca5)

That said, I'm not sure what I did wrong or if I missed something. 

📌 ACTIONS
- Triaged
- Requested author feedback

📌 Message to Author
@Aurorum, thanks for the report! I'm not sure why I can't replicate it. I provided GIF screenshot above. Can you check and see if I might have missed anything?

**Comment by Aurorum** [comment] 2024-03-21 22:43
Hi @retnonindya - not sure how/why it’s working for you! I can still reproduce this issue. Could you maybe try updating the “Uncategorised” one?


https://github.com/Automattic/wp-calypso/assets/43215253/a92db227-95e1-475f-a344-5e7cb5aa242d

**Comment by Aurorum** [comment] 2024-03-23 12:39
I've added some error handling in #88831 so Calypso at least continues being usable upon encountering this.

**Comment by tyxla** [comment] 2024-03-25 15:05
As part of looking at https://github.com/Automattic/wp-calypso/pull/88831 I wasn't able to reproduce either, and I tried out with a non-proxied user too, with no success.

**Comment by jerren1327** [comment] 2024-04-10 09:34
7977550-zen

**Comment by mmtr** [comment] 2024-11-26 13:12
I cannot replicate this either, so I'm closing this one out. @Aurorum if the issue still persists for you, feel free to re-open and we can take a look at your account.

**Comment by Aurorum** [comment] 2024-11-26 13:16
Thanks @mmtr. I can still reproduce - feel free to play around with any of the test sites on my account: https://wordpress.com/settings/taxonomies/category/kitten929.wordpress.com

**Comment by mmtr** [comment] 2024-11-28 11:50
@Aurorum oh wait, I see the same happening in other sites (e.g. torres12643.wordpress.com).

Do you create these sites in special way? Just wondering why the cache is wrong for all the sites from your account that I checked 🤔 

FWIW, you can fix the cache yourself by going to `/wp-admin/edit-tags.php?taxonomy=category` and make some changes to a category there (I already did this for torres12643.wordpress.com and kitten929.wordpress.com).

**Comment by Aurorum** [comment] 2024-11-28 12:02
Thanks @mmtr - no, nothing special about the way those sites were created (I only ever really go directly to `/start` for them). I now have an error where I can’t update only the description on those sites though.

![Image](https://github.com/user-attachments/assets/4934f81c-1133-4a48-ab6f-72e52f68febe)

**Comment by Aurorum** [comment] 2024-11-28 13:48
> Is it because you always manually change the view using this selector after you create a site?

I do have a habit of doing this, but for what it’s worth, I vaguely remember one person who reported this being unfamiliar with the difference between WP-Admin and Calypso, so I’m not sure that’s the problem. 

>  I don't see that in any of the two sites I played around with. Are you getting that on a different site?

Same site, I’m afraid! https://wordpress.com/settings/taxonomies/category/kitten929.wordpress.com

**Comment by mmtr** [comment] 2024-11-28 14:37
Alright, I think I found the culprit: it's the en-gb language. 

I can reproduce the issue consistently by following these steps:
- Go to https://wordpress.com/me/account and change the interface language to English (UK)
- Go to https://wordpress.com/start and create a new site
- Go to Posts > Categories and edit the Uncategorized category
- An error occurs

I need to further investigate this, but I found interesting that during the Headstart process (something we run internally to populate the default site content) we execute this line:

```php
$localized_slug = sanitize_term_field( 'slug', __( 'uncategorized' ), $term_id, $taxonomy, 'db' );
wp_update_term( $term_id, $taxonomy, [ 'name' => $localized_name, 'slug' => $localized_slug ] );
```

My guess is that for the en-gb language, the `uncategorized` slug is translated as `uncategorised` and that messes up the queries that we use later to find the categories.

**Comment by mmtr** [comment] 2024-12-02 13:18
Investigated this a bit further and found the underlying issue.

Turns out that the category is created with a mismatching name and slug for `en-gb`:
- Name is translated as `Uncategorized`
- Slug is translated as `Uncategorised`

This creates a conflict later because there is logic that tries to reconcile the slug with the name, so the _frontend_ slug (used by the API, what users see, etc) changes to `uncategorized` which no longer matches what's in the DB, so the API is unable to find the category.

In theory, the issue should be solved if everything is translated as `uncategorised`, so I went ahead and did that in https://translate.wordpress.com/. 

New translations are not deployed immediately though, so it'll take some time to be reflected. I'll comment here once new translations are live.

**Comment by mmtr** [comment] 2024-12-03 15:58
The issue has been solved for new sites. For `en-gb` users, the default category is now created with the correct name which matches the slug, so it can be edited successfully:

![Image](https://github.com/user-attachments/assets/c5ceae61-63c0-401d-96e6-6fe2d799a9e1)

On existing sites the category will remain as "Uncategorized" and therefore will produce an error if users try to edit.

One way to fix this is by running a backfill script that updates the category on existing sites. But such scripts are always non-trivial to implement, so I'm considering leaving things as they are because of the following reasons:

- The issue only affects existing sites of `en-gb` users. New users should work as expected.
- The issue only affects the default category (Uncategorized). Other categories should work as expected.
- The issue only affects Calypso. WP Admin should work as expected.

It seems that that only a low volume of users would be affected by this (we only got two reports), and we're going to replace soon the Calypso screen for categories with WP Admin.

So considering all the above, I'm going to close this issue. We can always re-open and revisit the decision if needed.

**Closed as completed by mmtr** 2024-12-03 15:58 UTC
Labels: Bug, [Pri] Low, [Feature] Calypso & wp-admin Navigation, Triaged, Customer report [LEGACY], [Platform] Simple, [Feature Group] Content Management, [Feature] Categories & Tags, [Experiment] AI labels added
