### ISSUE TITLE
Site Settings: "Add a Custom Address" button wraps to multiple lines

### ISSUE THREAD

**Issue by mattmiklic** [Automattic/wp-calypso#3050] opened 2016-02-03 19:05 UTC
The "Add a Custom Address" button on Site > Settings > General makes assumptions about the length of the button text and the width of the viewport that aren't always true. In English, the button wraps to multiple lines if the browser window is at certain widths. The button wraps to multiple lines at any width in most of the "popular languages" in Calypso.

![narrow](https://cloud.githubusercontent.com/assets/1396552/12793435/a0735570-ca7e-11e5-8049-4f8bebf9b0d0.png)

![lang](https://cloud.githubusercontent.com/assets/1396552/12793436/a2f68cd6-ca7e-11e5-9f59-a2fb0dfcc368.png)

Because the height of the input matches the height of the button, it grows very large in some languages. The multiple-line button looks particularly awkward because the second line sits below the `+` icon on the top line. Perhaps there's a better way to float this button, or it should be displayed below the input?

**Comment by lancewillett** [comment] 2016-10-17 17:43
Bug scrub note: reported issue is still valid. In addition, not just with long domain names or other languages — the same issue occurs in smaller screen sizes such as tablets and small laptops.

<img width="749" alt="screen shot 2016-10-17 at 10 42 33" src="https://cloud.githubusercontent.com/assets/66797/19448395/8451cc08-9456-11e6-8cdb-249dac1cd743.png">

**Comment by lancewillett** [comment] 2016-10-18 22:30
See also a similar report (closed as duplicate): #8112

**Settings: Site Address button label has a line break**
Happens in viewports that are about `<1065px`. This causes the Site Address field to look really large:

![screenshot 2016-09-16 16 09 57](https://cloud.githubusercontent.com/assets/4924246/18603623/193b787e-7c28-11e6-8879-58de1046cfa8.png)

**Comment by jsnmoon** [comment] 2018-06-04 22:17
I can confirm that this is still an issue. Using a default zoom, the issue occurs when the viewport is between 661px and 1051px in width.

We can fix most of this issue by changing the breakpoint used by the stylesheet for the page. I'll spin up a small PR for this shortly.

**Comment by lancewillett** [comment] 2020-05-06 19:48
Closing this due to inactivity. Please re-open if we decide to further improve the layout of this button.

Here are two screenshots for reference, Safari desktop on macOS.

Larger viewport
<img width="749" alt="Screen Shot 2020-05-06 at 12 47 38" src="https://user-images.githubusercontent.com/66797/81221536-d4b9c700-8f97-11ea-97bd-e6966b96459e.png">

Smaller viewport
<img width="501" alt="Screen Shot 2020-05-06 at 12 47 47" src="https://user-images.githubusercontent.com/66797/81221540-d71c2100-8f97-11ea-8ff2-708a0c4dea76.png">

**Closed by lancewillett** 2020-05-06 19:48 UTC
Labels: Domains, Site Settings, [Type] Bug
