### ISSUE TITLE
Subscribing via Paid Content Block using Newsletter Plan does not grant access to Newsletter content

### ISSUE THREAD

**Issue by cat-og** [Automattic/wp-calypso#82433] opened 2023-10-01 19:27 UTC
### Quick summary

Once a Paid Newsletter is added as a Payment plan, it can be selected as a plan option for the Paid Content block. However, if a user subscribes to this Newsletter plan via the Paid Content block, they are still not considered a paid subscriber to the site, and will not get Newsletter notifications. 

They can only be added as subscribers to the site if they also subscribe via the subscription block so through the Subscribe interface you get when hitting a paywal directly. 

If you have two users, one who signsup via the subscription block and a second who subscribes via the Paid Content block, only the first user will appear on the Subscriber list. They will both appear in the Supporters list as being on the exact same plan, but they will have different content experiences, as only the first user will actually get Newsletter notifications. 

The Paid Content block either needs to correctly add users as subscribers when using a Newsletter payment plan, or those Newsletter plans should not be an option in the Paid Content block, as users will find that expected subscribers are not getting any notfications.

### Steps to reproduce

1. Add Newsletter Payments Plan in Earn settings
2. Add Paid Content block to a new page, and select the Newsletter plan from the plan options: 

![UcBkS1.png](https://github.com/Automattic/wp-calypso/assets/27249804/33f1c33b-d636-4f35-a8fe-a522008517c6)

3. Subscribe to the new Paid Content block in incognito mode with a test email

### What you expected to happen

Because they subscribed to the Newsletter plan, I expected that the test email would be added to my subscriber list, and they would be included as a paid subscriber. 

I expected that they would get an email notification when a new post was published on the site.  

### What actually happened

 - This new subscriber will appear on the Supporters list in the Earn Settings, but not on the Subscriber list. 
- If a new post is created and the access is limited to paid subscribers, this new subscriber will not contribute to the paid subscriber count. 

![qQF206.png](https://github.com/Automattic/wp-calypso/assets/27249804/b845aee4-47ba-48b2-a661-1167c4040143) 

- They will not be notified by email when the new post is published, regardless of privacy status on the post. 

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment] 2023-10-03 00:05
The ability to set a Newsletter plan as the plan for the Paid Content Block is fairly recent (if intentional), as this has been a feature request in discussion over here:

- https://github.com/Automattic/wp-calypso/issues/78285

Back in June, @romarioraffington shared the following insight into the complications between these 2 blocks:

> 1. When users purchase a newsletter plan, we only give them access to newsletter content ( i.e. newsletter gated posts )
>2. When users purchase a plan from a premium content block, we only give them access to the premium content if the plan ID matches what was purchased.
>
>When we allowed newsletter plans to be purchased from the premium content block, this also gave customers access to newsletter content. Should we allow customers to purchase newsletter plans from other blocks, we would have to change how we're gating newsletter posts.

@Automattic/zap & @Automattic/gold , have there been more recent updates to how these blocks are intended to relate to one another?

**Comment by cuemarie** [comment] 2023-10-03 17:07
@millerf confirmed in [this comment](https://github.com/Automattic/wp-calypso/issues/78285#issuecomment-1744427317) the intentional design of the blocks now:

> So using those "newsletter" plans on a premium content block or pay block grants you access to that premium-content, but also subscribes you to the site newsletters (and also gives you access to paywalled content accordingly.

I'll triage this report next to see if I can reproduce the issue Cat reported above.

**Comment by cuemarie** [comment] 2023-10-03 17:46
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
On a Premium Plan test site, I set up a Paid Content block with a one-time Newsletter subscription, then subscribed to the block & newsletter from another account.  After doing so, I published a Paid Subscribers only post from my Premium plan site, and my new subscriber who signed up via the paid content block did receive that email.

A couple items I noticed:

**Checkbox for exclusive member updates**

There's an option to sign up for "exclusive member updates" on the payment form when I subscribed, **which I did check,** as I assume this is what actually gives permission for the newsletter emails - @millerf , can you let me know if this checkbox is being used for newsletter sign up, or if that's unrelated? 

<img width="300" alt="screenshot" src="https://github.com/Automattic/wp-calypso/assets/27249804/44dc6f75-1fde-48a0-8f4c-0696bb36b8bd">

---

**0 new paid subscribers**

The "Access" modal and on the post itself does show `Paid subscribers only (0)`, as does the post-publish sidebar and my Stats > Subscribers page - but that email did actually reach me; so this is either a caching delay, or just an issue with how we update that count.

![Markup on 2023-10-03 at 10:42:21](https://github.com/Automattic/wp-calypso/assets/27249804/64aadd46-d247-4e7c-adac-3981be851a79)

| ![Markup on 2023-10-03 at 10:37:08](https://github.com/Automattic/wp-calypso/assets/27249804/f01f7e0b-bcea-47da-93d5-def49d504043) | ![Markup on 2023-10-03 at 10:36:55](https://github.com/Automattic/wp-calypso/assets/27249804/aaede3e9-fc9e-40f5-9653-930108cbb758) |
| ------------- | ------------- |

![Markup on 2023-10-03 at 10:39:25](https://github.com/Automattic/wp-calypso/assets/27249804/c3483e17-7155-4432-92b0-120266ade2e9)

📌 ACTIONS
- Closing as could not replicate
- I'll check back in on this site later today, and if the Paid Subscriber count still hasn't updated to 1, then I'll submit a new report about that issue specifically

**Closed as not planned by cuemarie** 2023-10-03 17:46 UTC
Labels: Bug, [Pri] Normal, [Feature] Subscriptions, Triaged, [Closed] Not Reproducible, [Feature Group] Customer Seller Experience, [Product] WordPress.com
