### ISSUE TITLE
Jetpack Connect: doesn't recognize sites where WP lives in a subdirectory

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5142] opened 2016-05-02 08:56 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/jetpack/connect
2. Enter a site URL where [WP lives in a subdirectory](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory)
3. ![screen shot 2016-05-02 at 10 53 29 am](https://cloud.githubusercontent.com/assets/426388/14950720/46c463c2-1054-11e6-9d21-c40484ba9c67.png)
4. Because you can't access the dashboard just by `wp-admin` to the site URL, the tool doesn't recognize the site.
5. The tool only seems to work if I manually enter my site's WordPress address:

![screen shot 2016-05-02 at 10 55 48 am](https://cloud.githubusercontent.com/assets/426388/14950747/73e972a2-1054-11e6-9e2f-b74b317e05ef.png)

**Comment by johnHackworth** [comment] 2016-05-18 16:08
fixed in the API :+1:

**Comment by jeherve** [comment] 2017-09-29 10:36
Reopening as this is happening again, as per p8oabR-5F-p2

**Comment by rachelmcr** [comment] 2018-02-16 17:08
I confirmed that this is still an issue, although the steps have changed slightly:

1. Starting at URL: https://wordpress.com/jetpack/connect
2. Enter a site URL where WP lives in a subdirectory
3. The URL is accepted but always suggests installing Jetpack (even when Jetpack is already installed/activated):
<img width="1437" alt="screenshot 2018-02-16 16 50 03" src="https://user-images.githubusercontent.com/8658164/36319613-6615e638-133b-11e8-9f5a-fc5a12e9398e.png">
4. Selecting "Install Jetpack" adds `/wp-admin/plugin-install.php?tab=plugin-information&plugin=jetpack` to the site URL that was entered, which leads to a 404 page because you can't access the dashboard just by adding `/wp-admin` to the site URL.

If I enter the full URL where WordPress is installed, then it works.

**Closed** 2018-06-11 13:27 UTC
Labels: FixTheFlows, Jetpack, Signup, [Pri] Normal, [Type] Bug
