### ISSUE TITLE
Advanced SEO: Tokens can Merge/Split

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#7934] opened 2016-09-07 16:15 UTC
In the title editor, you can place the cursor in a token, then add another token and it will split it up:

![site-name-bug](https://cloud.githubusercontent.com/assets/789137/18319669/8f119e56-74db-11e6-9b87-2b03d67b2696.gif)

cc @dmsnell

**Comment by roundhill** [comment] 2016-09-07 16:16
Related: If you insert multiple tokens without spaces then save the title, these are combined into a really long token (which is removed with one click/tap)

![combining](https://cloud.githubusercontent.com/assets/789137/18319698/b1140b88-74db-11e6-9a32-1bff20c82a2f.gif)

**Comment by dmsnell** [comment] 2016-09-07 17:47
The first part of this should be resolved when #7887 gets resolved and the second part is a duplicate of #7886 so I'm going to close this issue, but thanks for reporting it @roundhill!

**Closed by dmsnell** 2016-09-07 17:47 UTC
Labels: Plans, [Type] Bug
