### ISSUE TITLE
Image block: image size feature does nothing

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/wp-calypso#43197] opened 2020-06-11 13:38 UTC
The _Image size_ feature of the Image block doesn't seem to work on WordPress.com. It works fine on self-hosted.

#### Steps to reproduce

1. Add an Image block with an image
2. Choose a size in the dropdown for _Image size_
3. Notice it does nothing

#### What I expected

The image to adapt to the size I chose.

#### What happened instead

Nothing.

#### Screenshot / Video

![Screen Shot on 2020-06-11 at 15:37:58](https://user-images.githubusercontent.com/16645645/84391648-8ed8ca00-abf9-11ea-804a-db94e43919b9.png)

EDIT: It was reported in 3039744-zd

**Comment by tanjoymor** [comment] 2020-06-12 03:20
I was able to reproduce this in various themes: Hever, Scrawl and Gazette

**Comment by tbradsha** [comment] 2020-06-12 20:34
Same issue in 3058622-zen; confirmed on my test site.

**Comment by bsanevans** [comment] 2020-06-13 01:51
Another user report: 21672507-hc --> 3059202-zen

Site is Atomic, using the Arcane theme. Size settings in the block do not change the block in either the editor or the front-end of the site.

**Comment by bsanevans** [comment] 2020-06-13 01:58
Another user report: 21845661-hc

Simple site on Soho theme where changing image sizes does not work. In fact, the image size code conflicts with theme styling, making it impossible to set an image to `alignfull`. Manually removing the image size class in the block code makes `alignfull` possible.

**Comment by zdenys** [comment] 2020-06-13 10:20
I had a related case involving Floral theme (retired premium) and initially, I thought it was about Image Block P1591890840110400-slack-dotcom-manage, but seems to be theme specific so it's reported here 3092-wpcom-premium-themes I remember they mentioned that changing Image size did nothing indeed, so exactly as described above.

>Up until 2 weeks ago, setting the Image Block to Full Width in the Editor, the user got the full view like this ​https://d.pr/i/iqORQF but now it’s not working anymore and they see it like this ​https://d.pr/i/GTNGjy
>Adding the alignfull class (as per this ​https://wordpress.com/support/adding-additional-css-classes-to-blocks/#make-use-of-existing-custom-css-classes) to each image fixes the issue

**Comment by zdenys** [comment] 2020-06-16 11:10
After some more testing, I can see the issue on a fresh install of https://jurassic.ninja/ + latest Gutenberg Plugin. Here's the screencast: https://d.pr/v/cOXxJF

On https://jurassic.ninja/ site without Gutenberg Plugin the Image Block has no issues: https://d.pr/v/jEUheH

I haven't had the time to check if it's reported at https://github.com/WordPress/gutenberg yet but should be reported there to be fixed.

**Comment by zdenys** [comment] 2020-06-16 16:10
Another case: 3063194-zen. 

I started a Slack thread p1592323637160400-slack-CS108SDLZ to see if it can be prioritized.

**Comment by retnonindya** [comment] 2020-06-18 02:41
Another report: #21990733-HC

The user also reported slowness on the editor, and they wondered if the editor slowness has anything to do with this issue.

**Comment by supernovia** [comment] 2020-06-18 17:53
Another here:
https://github.com/Automattic/wp-calypso/issues/43197

Also do we know if this is happening in Gutenberg itself?

**Comment by razvanpapadopol** [comment] 2020-06-22 09:10
> The user also reported slowness on the editor, and they wondered if the editor slowness has anything to do with this issue.

This issue has nothing to do with the slowness issue which have been solved by Coblocks patch release 2.0.1. p9F6qB-5ok#comment-30161

> Also do we know if this is happening in Gutenberg itself?

Yes and the [proposed fix in Gutenberg](https://github.com/WordPress/gutenberg/pull/23342) has been merged and it will be included in the next [Gutenberg release](https://github.com/WordPress/gutenberg/milestone/123?closed=1).

**Comment by razvanpapadopol** [comment] 2020-06-22 14:42
On hold until [Gutenberg 8.4](https://github.com/WordPress/gutenberg/releases/tag/v8.4.0-rc.1) is deployed on WordPress.com.

**Comment by zyousafi** [comment] 2020-06-28 06:54
Another user report here #18727906-hc

I suggested disabling the **Gutenberg** plugin and directed the user to the `WP-Admin` editor.  When using the editor there, they have no problems with the resizing when using the Image Block

**Comment by tellyworth** [comment] 2020-08-05 05:01
I can reproduce this with Twenty Twenty and the Photos themes.

Additionally, the "Image Dimensions" settings don't seem to allow for an image larger than 640px wide. Even if I manually enter a width and height of say 1024 x 768, I get a 580px image in the post. This is with a jpeg that is 2400x1600.

This is pretty catastrophic for photoblogging. Here's a sample screenshot of a recent post on my blog, with the largest image I can insert:

<img width="2239" alt="Screen Shot 2020-08-05 at 2 59 36 pm" src="https://user-images.githubusercontent.com/7200686/89373541-50a8e400-d72c-11ea-8ab3-d5467b92ba63.png">

(Is this the same issue or should I report it separately?)

**Comment by yansern** [comment] 2020-08-05 23:00
This is now fixed for Gutenberg >= 8.4.0. Production is still on 8.3.0. Won't be long for the new release to roll in.
https://github.com/WordPress/gutenberg/pull/23342

**Closed by yansern** 2020-08-05 23:00 UTC
Labels: Media, [Impact] High, [Pri] Normal, [Status] Blocked / Hold, [Type] Bug
