### ISSUE TITLE
Gutenboarding Design Picker: Image not loading in Rivington Thumbnail

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#50919] opened 2021-03-09 21:11 UTC
### Steps to reproduce the behavior

1. Visit wp.com/new
2. Proceed to design picker
3. Notice that the Rivington design is missing an image

![image](https://user-images.githubusercontent.com/545779/110538378-9aeeab00-80e9-11eb-8557-c6130e4438bd.png)

#### What I expected to happen

The image loads here on the fonts screen …

![image](https://user-images.githubusercontent.com/545779/110538445-ac37b780-80e9-11eb-93aa-2fed99f28e41.png)

**Comment by jeyip** [comment] 2021-03-12 07:01
Reproduced this following the given instructions in Chrome, Firefox, IE11, Edge, and Safari. I'm on the fence about priority. This doesn't affect any workflows on the site -- the user can still select the theme and, but it very well might be the user's first impression of the .com platform. Setting the priority as normal, but it's definitely up for discussion.

**Comment by jeyip** [comment] 2021-03-12 07:04
It looks like there was some discussion surrounding this. Basically, the theory is that there is some lag when loading the demo site for the first time. The screenshot taken for the thumbnail is captured before the image can render.

p1615436364208200-slack-CS0SC36SX

cc @ramonjd

**Comment by andrewserong** [comment] 2021-03-22 06:00
I've created a diff to cheat rendering the Slideshow block in a static way, which should 🤞 work around the mShots rendering issue for this block: D59099-code — the diff will add an additional param for the endpoint to generate the preview, so if it all looks good and gets merged in, I'll create a small PR for Gutenboarding to use the param in the design step.

**Comment by andrewserong** [comment] 2021-03-24 01:20
D59099-code has been deployed, so I have an update for Gutenboarding to use the override ready for review in #51361

**Comment by andrewserong** [comment] 2021-03-24 02:44
Fixed in #51361

**Closed as completed by andrewserong** 2021-03-24 02:44 UTC
Labels: Bug, [Pri] Normal, Triaged
