### ISSUE TITLE
Cannot exit Customizer by single clicking the X at top left

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#47927] opened 2020-06-24 22:36 UTC
Steps to reproduce:

1. Go to My Site > My Home > Quick Links > Edit menus.
1. Single click on the X at the top left corner.
1. Note the customizer does not close.
1. Double click on the X at the top left corner.

**Result:** you must double click the X at top left in order to leave the Customizer but I expected that a single click  would work. ([3m17s](https://cloudup.com/cbh1YbKO0_B), [54s](https://cloudup.com/c0JptZqU5t0)) 

<img src="https://user-images.githubusercontent.com/1119271/85634233-28f83380-b638-11ea-99db-bde9537442e7.png" width="33%" alt="edit-menus"> <img width="33%" alt="Screen Shot 2020-06-24 at Jun 24 4 34 35 PM" src="https://user-images.githubusercontent.com/1119271/85634479-b5a2f180-b638-11ea-8c9d-8dd0eacc02f9.png"> <img src="https://user-images.githubusercontent.com/1119271/85634238-2c8bba80-b638-11ea-9b76-caa999dd430c.png" width="33%" alt="sorry-the-customizing-tools-did-not-load-correctly">

<p style="clear:both;"><sup>Tested with WPDesktop 6.0.0-beta3 on macOS 10.15.4.</sup></p>

**Comment by ericamQA** [comment] 2021-06-04 22:14
I'm not able to reproduce this and it hasn't been touched or added to in a while. Closing for now.

**Closed by ericamQA** 2021-06-04 22:14 UTC
Labels: Desktop App, [Closed] Not Reproducible, [Pri] Low, [Type] Bug
