### ISSUE TITLE
Payton: Default font doesn't apply on the editor 

### ISSUE THREAD

**Issue by rinazrina** [Automattic/wp-calypso#66037] opened 2022-07-28 07:16 UTC
### Quick summary

The editor is showing a different font than the default. The issue only occurs in desktop view. The font looks correct on Mobile view and Tablet view. It's also correct on the Preview in new tab and on the published version. 

Noting there is another report on Payton font here that might be related: https://github.com/Automattic/themes/issues/6289 

### Steps to reproduce

Start with a site on a Payton theme.

1. Go to Posts or Pages > open one of the existing posts or pages, or create a new one
2. Check the font on the editor compared to the Preview
3. On the editor, compare the Desktop view with the font on Tablet view and Mobile view. Also compare it with the Preview in a new tab version

### What you expected to happen

The default font should be applied to Desktop view on the editor.

### What actually happened

Desktop view on the editor is showing a different font. 

Screenshots below: 

**Editor - Desktop view**

<img width="948" alt="Screenshot on 2022-07-28 at 14-47-19" src="https://user-images.githubusercontent.com/33721365/181442766-240597a1-1538-416c-bc25-90695f738a28.png">

---

**Editor - Tablet view**

<img width="954" alt="Screenshot on 2022-07-28 at 14-47-42" src="https://user-images.githubusercontent.com/33721365/181442815-4d81f17c-e0ce-456b-952d-678bc9c46293.png">

---

**Editor - Mobile view**

<img width="949" alt="Screenshot on 2022-07-28 at 14-47-58" src="https://user-images.githubusercontent.com/33721365/181442874-9d4a96c2-0b6d-4ea5-9e88-549bd9868c94.png">

---

**Preview in a new tab & Published version**

<img width="936" alt="Screenshot on 2022-07-28 at 14-48-17" src="https://user-images.githubusercontent.com/33721365/181442927-594bba5f-08fa-46a5-b226-2b02dd1d779e.png">

### Context

Customer report: 5429621-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Yes, Payton. 

Doesn't occur on Twenty Twenty. 

### Browser, operating system and other notes

Tested in Chrome. Mac OS Big Sur. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

User can check the font by opening Preview in a new tab.

**Comment by Robertght** [comment] 2022-07-28 10:44
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on P2 - no
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted - no

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can confirm the behavior described here and in https://github.com/Automattic/themes/issues/6289

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Flagged it for @Automattic/serenity 

We have another Premium theme issue [here](https://github.com/Automattic/wp-calypso/issues/66008)(non-related to this) but potentially causing issues since the Blockbase 3.0 update.

**Comment by i11za** [comment] 2022-07-31 12:36
User report: 5426964-zd-woothemes
Simple site. 

UPD: Workaround doesn't work for the site.

**Comment by andres-blanco** [comment] 2022-08-04 19:34
asked about this here: p1659641626707519-slack-C029FM1EH

**Comment by andres-blanco** [comment] 2022-08-05 18:06
Potential fix D85486-code

**Comment by andres-blanco** [comment] 2022-08-08 15:02
CLosed by D85486-code

**Closed as completed by andres-blanco** 2022-08-08 15:02 UTC
Labels: Bug, [Pri] High, Triaged, [Platform] Simple, [Platform] Atomic
