### ISSUE TITLE
Reader: navigation gets stuck in recommended posts

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#6297] opened 2016-06-24 18:06 UTC
Video of end result: https://cloudup.com/cf_SixxGSGt

#### Steps to reproduce
1. Starting at URL: wordpress.com logged in (reader view)
2. Click through a WordPress.com article on reader
3. Click through to a recommended article at the bottom of the page
4. Click through to another recommended article at the bottom of the page
5. Click top left arrow expecting to get back to reader, or at least 1 layer back (to previous article)
6. Get back to original article & notice that arrow redirects you to one of the recommended posts instead of main reader page in a loop

I found this on FF, staging. It's not 100% reproducible at those steps, so I'll dig a bit more to find the cause/symptoms. Wanted to log it here in case others had run into it and wanted to add info!

**Comment by lancewillett** [comment] 2016-10-14 19:27
No further reports, and I couldn't reproduced in Firefox latest stable on OS X 10.12. Closing for now — feel free to rep-open if it happens again.

**Closed by lancewillett** 2016-10-14 19:27 UTC
Labels: Reader, [Type] Bug
