### ISSUE TITLE
Domain Search: The back button doesn't work as expected

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#95922] opened 2024-10-31 01:33 UTC
### Quick summary

The back button seems to take users to the domains management page which is not always the expected behavior.
See the back button in the screenshot below for reference:

![Image](https://github.com/user-attachments/assets/f9db5cd4-fa61-482e-bc05-659271e59df9)

### Steps to reproduce

1. Start at /mailboxes/:domain
2. Click on the "Just search for a domain" button
3. Once in the domain search screen, click on the back button
4. The user is taken to the domain management page instead of the "My Mailboxes" screen

### What you expected to happen

To be taken back to the last visited page

### What actually happened

Landed on the domains management page

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment] 2024-10-31 11:09
📌 REPRODUCTION RESULTS
- Tested on the platform – Could Not Replicate 


📌 ACTIONS
- Requested author feedback

📌 Message to Author
@taipeicoder it appears that I'm missing a step or two from the instructions shared above. Is it possible to share a video recording of this process instead perhaps?

**Comment by taipeicoder** [comment] 2024-10-31 11:41
Thanks for the follow-up. The issue is that if I started the user journey in "My Mailbox" (/mailboxes/:domain), then click on the "Just search for a domain" button:

![Image](https://github.com/user-attachments/assets/72189bc9-933f-4d2a-8625-ac0a4c97aaaa)

I land on the Domains Search page. If I click on the Back button:

![Image](https://github.com/user-attachments/assets/70c51243-4f9a-43a7-ad13-cbb5cb504ff9)

I expected to be back in "My Mailbox". Instead, I was taken to the Domains page (/domains/manage/:domain).

**Comment by m1r0** [comment] 2024-11-01 13:32
Thanks for the clarifications @taipeicoder!

I was able to reproduce it and submitted a quick [fix](https://github.com/Automattic/wp-calypso/pull/95988).

**Comment by Robertght** [comment] 2024-11-01 16:14
Thank you @taipeicoder and @m1r0 for looking into it! :)

**Comment by m1r0** [comment] 2024-11-06 10:34
I am changing it to low priority because there are [plans](https://github.com/Automattic/wp-calypso/pull/95988#pullrequestreview-2413706855) to update/remove these screens.

**Comment by m1r0** [comment] 2024-11-15 13:09
I am closing in favor of https://github.com/Automattic/wp-calypso/issues/95623.

**Closed as completed by m1r0** 2024-11-15 13:09 UTC
Labels: Bug, [Pri] Low, [Feature Group] Emails & Domains, Triaged, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature] Domain Management, Fit and Finish
