### ISSUE TITLE
Components: Store card with gridicon shrinking

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#8624] opened 2016-10-10 14:52 UTC
#### Steps to reproduce
1. add a domain to your cart
2. go to checkout
3. viewport: 860px width
#### What happened instead

Gridicon is misaligned in Safari 

`flex-shrink: 0;` on the div containing the icon fixes it
#### Browser / OS version

Safari 9.1.2
El Capitan Mac OS X
#### Screenshot / Video

![screen shot 2016-10-10 at 9 42 17 am](https://cloud.githubusercontent.com/assets/618551/19240171/df9e2ae4-8ece-11e6-87f5-f1b11d1e1fd0.png)
#### Context / Source

I called it a component because we used this same card elsewhere, even though it is undocumented as far as I know.

**Comment by rachelmcr** [comment] 2017-08-22 14:25
I tested this on Mac 10.12.6, Safari 10.1.2 and could not reproduce the issue (at 860px width or other widths I tested). Closing as no longer valid.

**Closed by rachelmcr** 2017-08-22 14:25 UTC
Labels: Checkout, Components, [Type] Bug
