### ISSUE TITLE
Hide link to enable and disable auto-updates for plugins on Atomic sites

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#55213] opened 2021-08-05 18:00 UTC
### What

Since automatic updates on all registered plugins are managed by WordPress.com and cannot be changed by customers, we should eliminate the link for customers to enable/disable auto-updates

### Why

It is confusing to go to the plugins list on a site and see the option to enable/disable auto-updates for plugins when this setting has no effect.

<img width="1176" alt="Markup 2021-08-05 at 16 54 44" src="https://user-images.githubusercontent.com/51966986/128398675-c44caf30-386d-44db-934c-7799c6f42af8.png">

### How

Hide the setting entirely and don't show Disable/Enable auto-updates for non-managed plugins

or

Change the text to "Managed by host" for any plugins that will get automatic updates

**Comment by amustaque97** [comment] 2021-08-05 18:32
Hi @philnick206, I would love to work on this issue. I want to work on this  "Managed by host" approach since it will give users a better idea about who all are controlling these plugins. Recently, I started contributing to WordPress. I have a quick question. Do I need to change it in this calypso repo only or how to find places where I need to update this text?

**Comment by JoshuaGoode** [comment] 2021-08-06 14:51
Hi @philnick206!

> Since automatic updates on all registered plugins are managed by WordPress.com and cannot be changed by customers, we should eliminate the link for customers to enable/disable auto-updates

Being able to control update settings for non-WPCOM plugins is now expected behavior after some recent platform changes.  The settings now work.

While an announcement was made, we'll get a more specific internal announcement + documentation updates going.

> Change the text to "Managed by host" for any plugins that will get automatic updates

This only applies to plugins we install, manage, and symlink on the WordPress.com platform.  The `Managed by host` plugins are installed by default and are symlinked.   Also, the symlink can be removed so the user can install the plugin directly from the repo and control the update settings.

Internal notes: p7DVsv-cgt-p2
Internal discussion: p1628260556108400-slack-C7YPW6K40
Internal discussion 2: p1628260639136300/1628218889.120800-slack-C3GP81E05

**Comment by JoshuaGoode** [comment] 2021-08-06 14:56
If the WPCOM product decides this isn't a good idea, we can reopen this feature request and get it to the right teams.

For now, I might mark this as closed as this is now intentional behavior.

**Closed as completed** 2021-08-06 18:38 UTC
Labels: [Feature] Plugins, Feature Request, [Status] Close
