### ISSUE TITLE
Block widget editor on .com enters constant refresh loop

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#53448] opened 2021-06-07 08:46 UTC
This can be harder to replicate, but we're seeing the experimental block widget editor on .com go into a refresh-loop:

https://user-images.githubusercontent.com/87168/120986777-9dfb4500-c785-11eb-9830-8f2839b02ea6.mp4

https://user-images.githubusercontent.com/87168/120986781-9e93db80-c785-11eb-92b9-83aa62f21544.mp4

via p58i-axR-p2/#comment-50850

> The moment I go to Appearance > Widgets is when I experience the constant refresh of the Widgets Editor screen.
>
> I can click within a widget to attempt to make changes but the screen will still refresh. The Widgets Editor sticker is enabled for the site in the BlogRC. This seems to occur whether or not the “Show wp-admin pages if available” toggle is on. 

The feature is going to be released in WP 5.8 July by which time we should have this fixed, although we might want to release the feature earlier on .com.

**Comment by simison** [comment] 2021-06-07 08:48
Block editor has a similar issue (https://github.com/Automattic/wp-calypso/issues/53448) but Jacopo mentioned (p58i-aCg-p2#comment-50871) it doesn't seem exactly the same:

> Looking at the various videos, I’m kind of inclined to think the Site Editor one is a routing loop; at least the Widget Editor loads! 🤔

**Comment by taggon** [comment] 2021-06-08 06:48
After hours of investigation, I found the root cause is one of the legacy widget hooks not called. When it comes to iframe request, the hook is supposed to define `IFRAME_REQUEST` to prevent `wpcom-frame-handling` mu-plugin from reloading the top frame over and over again. But it is not called due to the order of hooks.

While working on the fix, I'm noticed [the fix already has been merged](https://github.com/WordPress/gutenberg/pull/32300) to the Gutenberg project. What we need is only checkpicking. :)

**Comment by simison** [comment] 2021-06-08 07:29
Oh, fantastic! Good sleuthing.

The fix is included in Gutenberg 10.8 which seems fine to wait (should be in a week?). If cherry-picking that all-PHP change is easy enough, that's also worth it. FYI @fullofcaffeine @WunderBart 

FYI @noisysocks @draganescu that the above PR fixes this refresh issue on .com.

**Closed as completed** 2021-09-13 14:14 UTC
Labels: Bug, [Goal] Block widget editor
