### ISSUE TITLE
Custom Color Picker Slider Closes Prematurely

### ISSUE THREAD

**Issue by gwensmithx** [Automattic/wp-calypso#49056] opened 2021-01-19 23:57 UTC
**I think this might be related to this issue as it's very similar:** https://github.com/WordPress/gutenberg/issues/21163

#### Steps to reproduce the behavior

1. Go to a page and highlight some text on the page to change the colour of.
2. Select the dropdown arrow in the toolbar and select the Text Color option.
3. Then when the colour picker comes up, select "custom colour" link and try to slide the colour picker to pick your colour. You will notice the colour picker closes right as you try to slide and select a colour.

#### What I expected to happen
- expected to be able to use the slider to pick a colour

#### What actually happened
- colour picker closes before I can pick a colour

#### Context
Originally reported #27118585-hc / #3663826-zd

### Browser / OS version
Chrome Version 87.0.4280.141 (Official Build) (x86_64)

### Is this specific to the applied theme? Which one?
Happens on multiple themes

### Does this happen on simple or atomic sites or both?
Both Atomic and Simple (tested)

### Is there any console output or error text?
I'm seeing this:
`wp.editor.RichTextToolbarButton is deprecated. Please use wp.blockEditor.RichTextToolbarButton instead.`

Are we not supposed to use the toolbar feature? 

### Level of impact (Does it block purchases? Does it affect more than just one site?)
Impacts multiple sites

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/5779512/105108177-f18b2180-5a76-11eb-816a-52e2c35c4d2d.mov

**Comment by AtrumGeost** [comment] 2021-11-05 16:00
Got another report here:

32265259-hc

The interface changed a bit but the issue persists:

https://user-images.githubusercontent.com/3696121/140540579-4aef27d4-35ed-4d6a-8a5f-f7064f7e0a38.mp4

**Comment by Robertght** [comment] 2021-11-05 16:48
This seems to be a duplicate of this one: https://github.com/Automattic/wp-calypso/issues/57687

Closing

**Closed as completed by Robertght** 2021-11-05 16:48 UTC
Labels: Bug
