### ISSUE TITLE
Nav Unification: Subscription / People settings missing for Jetpack sites

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#49188] opened 2021-01-22 13:00 UTC
### Steps to reproduce the behavior

1. Start from a Jetpack site connected to WordPress.com, running either Jetpack `master` or the current stable.
2. In wp-admin, go to Jetpack > Settings > Discussion
3. Click on "View your Email Followers"
4. You'll land in Calypso, in `https://wordpress.com/people/email-followers/yoursite.com`. That page does not have a corresponding menu item in the sidebar, though.

**Comment by jeherve** [comment] 2021-01-22 13:04
Related: #49187

**Comment by cpapazoglou** [comment] 2021-01-22 16:47
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/49187

**Closed as completed by cpapazoglou** 2021-01-22 16:47 UTC
Labels: Bug, Jetpack, People Management, [Feature] Subscriptions, [Feature] Calypso & wp-admin Navigation
