### ISSUE TITLE
[Bug]: Returning from Woo seller flow back to simple

### ISSUE THREAD

**Issue by SaxonF** [Automattic/wp-calypso#61436] opened 2022-02-24 06:57 UTC
### Quick summary

The "simple" sell intent button breaks if a user starts going down the Woo path but then backs out.

### Steps to reproduce

1. Create a new site via wordpress.com/start
2. Choose the sell intent
3. Select "more power" (Woo) option
4. Click back and choose "simple"
5. Notice the simple "Continue" button is broken

### What you expected to happen

The button should take someone down the simple flow

### What actually happened

It isn't registering but doesn't throw any errors as far as I can see.

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

**Comment by nelsonec87** [comment] 2022-02-24 11:45
Seems to be a duplicate (#61016)

**Comment by markbiek** [comment] 2022-02-28 18:31
Some quick notes on what I've noticed so far. I think the original fix from #61016 _did_ cover one of the ways this issue manifests itself and this is a different behavior with the same outcome.

(Caveat, this is my first time looking at the signup flow so please correct me if I'm misunderstanding anything).

Here's what I'm seeing in the Redux store when I go through the steps to reproduce:

1. After clicking **Upgrade** (prior to clicking **Back**), the `progress` is empty
![image](https://user-images.githubusercontent.com/917632/156038263-77162dbe-959a-45f6-965e-5d233dc1c29b.png)

2. After we click **Back** and end up on back at the intent options, `progress/store-features/status` is now `in-progress`. 
![image](https://user-images.githubusercontent.com/917632/156038279-5324f5dd-54f8-4319-a618-93a3143a34fd.png)

3. _But_, when we click **Continue** to choose the "Start Simple" option, `progress/store-features/status` gets set to `completed`. 
![image](https://user-images.githubusercontent.com/917632/156038308-2f120f7e-253d-438a-aa23-cc99b3ec36a6.png)


I'm assuming that's why clicking **Continue** doesn't do anything. The intent thinks everything is complete and there are no further actions to take.

My next step is to try and figure out where/why it gets set to `completed`.

**Comment by markbiek** [comment] 2022-02-28 19:54
After more testing, I'm starting to think I was incorrect with the above.

Now it seems like maybe the issue is related to the value of `signup.flow.currentFlowName` in the store. After clicking the **Back** button, the `currentFlowName` is still set to `woocommerce-install` when it should be `setup-site`.

Trying to figure out which action to dispatch so I can manually set it to the correct value as a test.

**Comment by markbiek** [comment] 2022-02-28 20:58
At this point, I'm not sure what's going on.

This file is a dump of the `signup` part of the store the first time you hit `/start/setup-site/store-features` before anything else has happened.
[state-normal.txt](https://github.com/Automattic/wp-calypso/files/8156674/state-normal.txt)

This file is a dump of the `signup` part of the store after going to the upgrade path, then clicking the back button.
[state-broken.txt](https://github.com/Automattic/wp-calypso/files/8156673/state-broken.txt)

There are a number of differences that you'll see.

I tried manually dispatching events through redux dev tools to update the `signup` state back to the normal state:
```
{
  type: 'SIGNUP_COMPLETE_RESET'
}

{
  type: 'SIGNUP_DEPENDENCY_STORE_UPDATE',
  dependencies: {
    siteSlug: 'markbiek61016k740424232.wordpress.com',
      intent: 'sell',
      siteTitle: '',
      tagline: ''
  }
}

{
  type: 'SIGNUP_PROGRESS_ADD_STEP',
  step: {
        stepName: 'intent',
        lastKnownFlow: 'setup-site',
        lastUpdated: 1646078871708,
        status: 'pending',
        providedDependencies: {
          intent: 'sell'
        }
  }
}

{
  type: 'SIGNUP_FLOW_RESET_EXCLUDED_STEPS'
}
```

But that didn't have any effect.  The "Start simple" button still doesn't work.

I also see a warning on the new call to `branchSteps` in `signup/steps/store-features/index.tsx`
> Warning: Cannot update a component (`SupportArticleDialogLoader`) while rendering a different component (`StoreFeaturesStep`). To locate the bad setState() call inside `StoreFeaturesStep`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
StoreFeaturesStep@app:///./signup/steps/store-features/index.tsx:42:76

but I reverted that change and the "Start simple" button still doesn't work so the issue is somewhere else.

**Comment by markbiek** [comment] 2022-03-01 18:53
To add to the above:

When you hit `/start/setup-site/store-features` the first time, `signup.progress` has the following steps

* `intent`
* `store-features`
* `store-options`

When you go to ** More power - Upgrade **, `signup.progress` only has

* `store-features`

It seems like it can't continue with ** Start simple - Continue ** because it's lost the fact that the user is in the `sell` intent.

That's the simplest explanation I've been able to find but I'm definitely going to need some help figuring out if that's correct and how best to fix it.

**Comment by blackjackkent** [comment] 2022-03-01 20:23
@markbiek, @sixhours and I sat down and discussed this for a while earlier and our general conclusion (aligned with Mark's info above) is that this problem stems from the sign up system basically considering the user to be done with the flow after the `store-features` step and entering a completely new sign-up flow when we navigate the user to WooCommerce onboarding. Consequently, all the past step dependencies are wiped out and can't be restored when the user uses the back button to navigate back into the Sell flow.

Our current theory is that, rather than navigate from one flow to another, we could simply add the existing Woo-related steps to the Sell flow as well,  thus ensuring that the user remains in one flow the whole way through and can (theoretically at least) navigate back and forth through it all the way through.

@obenland is there any insight from the Woo side of things regarding this solution and whether it seems reasonable? It shouldn't interfere with any other flows since it would simply be adding existing steps to our own flow.

/cc @kwight @ianstewart

**Comment by obenland** [comment] 2022-03-01 21:16
> @obenland is there any insight from the Woo side of things regarding this solution and whether it seems reasonable?

I don't think so. The steps are specified in the signup config, so theoretically it should be possible to use them in multiple flows? I've never tried that though and I'm too unfamiliar with the signup framework to be able to say that it would work. But maybe worth a shot?

**Comment by markbiek** [comment] 2022-03-02 19:13
The other idea we discussed is the possibility of carrying the `intent` step data forward into the Woo flow.

Obviously the Woo flow doesn't care about that data but, by carrying the data forward, it may make it possible to restore it once we've gone back into the signup flow.

I'm going to try and explore that option over the next few days and try and figure out the level of difficulty there.

**Comment by andres-blanco** [comment] 2023-05-30 12:09
Closing since the More Power flow does not exist anymore.

**Closed as completed by andres-blanco** 2023-05-30 12:09 UTC
Labels: Bug, [Pri] Normal, [Feature Group] Customer Seller Experience
