### ISSUE TITLE
Post Editor: post content not displaying for Editor role

### ISSUE THREAD

**Issue by mdza8c** [Automattic/wp-calypso#97607] opened 2024-12-18 12:46 UTC
### Quick summary

User reports not seeing post content in the editor when logged in on an account with the Editor role for the site.
Administrator accounts can see the same post in the editor.
Issue can be replicated, both proxied and unproxied.

### Steps to reproduce

1. Log in as provenzaec via Support Session.
2. Go to https://provenzaeccom.wordpress.com/wp-admin/post.php?post=4&action=edit

### What you expected to happen

The post editor should display correctly, including post content.

![Image](https://github.com/user-attachments/assets/2a1bb8a3-faf7-4410-843c-087107da32cb)

### What actually happened

The post editor displays information about existing content in side panels, but does not display the actual content to edit.

![Image](https://github.com/user-attachments/assets/4b3bfd16-58ee-49ef-b0cb-8c227228b969)

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

Links and discussion in Slack thread: p1734521686347949-slack-C03TY6J1A

Console error:

```
Uncaught SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin 'blob://' in a call to 'postMessage'.
    at VM4459 jquery.wpcom-proxy-request.js:1:2689
    at VM4459 jquery.wpcom-proxy-request.js:1:2990
```

Plugin info:
Gutenberg: v19.8.0
Editing Toolkit: 
WP AMP:

**Comment by Agepeuve** [comment] 2024-12-19 12:40
Hey! I've been testing, and it looks like the issue is resolved. We're just waiting on the user to confirm so we can close this out.

**Comment by abonnar** [comment] 2024-12-19 17:03
User has reached out and confirmed that the issue has been resolved on their end. Issue can be closed! 
https://a8c.zendesk.com/agent/tickets/9186145

**Comment by Agepeuve** [comment] 2024-12-22 08:34
Glad to read it. I'm going to go ahead and close this now. Thank you both!

**Closed as completed by Agepeuve** 2024-12-22 08:34 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] High, Needs triage, [Product] WordPress.com, [Feature Group] Editor Experience
