### ISSUE TITLE
Flaky E2E: Homepage Redirect (es)

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#72113] opened 2023-01-14 00:21 UTC
### Spec file

specs/i18n/i18n__logged-out-redirect.ts

### Logs

```
page.waitForURL: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for navigation to "https://wordpress.com/es/" until "load"
============================================================
at /home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/i18n/i18n__logged-out-redirect.ts:21:15
```

**Comment by worldomonation** [comment] 2023-01-14 00:22
@yuliyan Not urgent, but figured you might want to know that this spec seems to be failing at this step almost constantly.

![image](https://user-images.githubusercontent.com/6549265/212440791-48db728a-46ff-44bc-8634-da518339c8b7.png)

**Comment by yuliyan** [comment] 2023-01-16 13:50
Thank you for the ping @worldomonation! We're currently looking into homepage redirects. I'll let you know when we resolve the problem so we can re-enable the tests (I see that they are currently ignored).

**Comment by worldomonation** [comment] 2023-01-16 19:28
Looks like it's passing again on trunk!
![image](https://user-images.githubusercontent.com/6549265/212753256-3ecb6b98-4c4c-4f5d-80f2-8914715a5d5a.png)

**Comment by yuliyan** [comment] 2023-01-16 21:05
The redirects on the homepage had stopped working due to a new caching mechanism. The problem is now fixed - see p1673875046741509-slack-C02AVAR9B for more context.

**Closed as completed** 2023-05-23 06:01 UTC
Labels: Flaky E2E
