### ISSUE TITLE
Comments: Can't submit comment with single emoji on OS X

### ISSUE THREAD

**Issue by roundhill** [Automattic/wp-calypso#4968] opened 2016-04-22 17:44 UTC
When entering a comment with the OS X emoji menu, the 'SEND' button remains disabled

#### Steps to reproduce
1. From OS X, Starting at URL: https://wordpress.com/posts/my/(site)
2. Click on the comment button of a post
3. Press control+command+space to bring up the emoji menu
4. Select an emoji of your choice
5. Observe that the 'SEND' button is still disabled. If you type another character it will become enabled.

#### Browser / OS version
Safari / OS X 10.11.5 beta

#### Screenshot / Video
https://cloudup.com/iHCmdfaTpcD

**Comment by bluefuton** [comment] 2016-04-25 10:43
Well spotted @roundhill. This also affects comment entry in the Reader full post view.

**Comment by designsimply** [comment] 2016-07-20 21:41
#bug-scrub

Closing because I was unable to reproduce the problem using the testing steps provided. I tested with Safari 9.1.1, Firefox 47.0.1, and Chrome 51.0.2704.106 on Mac OS X 10.11.5 ([20s](https://cloudup.com/ckU3dcqCQtS))

<img width="1280" alt="screen shot 2016-07-20 at wed jul 20 3 27 29 pm" src="https://cloud.githubusercontent.com/assets/1119271/17003900/67df0c1e-4e8f-11e6-8f21-251f85123b57.png">
<sup>Seen at https://wordpress.com/posts/my/design5279.wordpress.com using Safari 9.1.1 on Mac OS X 10.11.5</sup>

<img width="1280" alt="screen shot 2016-07-20 at wed jul 20 3 28 35 pm" src="https://cloud.githubusercontent.com/assets/1119271/17003918/7ccf8770-4e8f-11e6-8448-5bd1d778404a.png">
<sup>Seen at https://wordpress.com/read/feeds/42873943/posts/1094150403#comments using Safari 9.1.1 on Mac OS X 10.11.5</sup>

**Closed by designsimply** 2016-07-20 21:41 UTC
Labels: Comments, Reader, [Type] Bug
