### ISSUE TITLE
Premium & Blockbase themes: Unable to modify templates from parent theme on simple sites

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#72172] opened 2023-01-16 19:46 UTC
### Quick summary

Changes made to specific templates on children of the Blockbase (Premium) theme (e.g. Byrne, Payton) are not retained after saving. These templates are all listed as being added by `Blockbase (Premium)` in the template list, and there's no indication that changes aren't saved.

### Steps to reproduce

1. Activate Byrne theme (or any child of Blockbase (Premium)).
2. Navigate to _Appearance > Editor > Templates > Manage all templates_.
3. See some templates (e.g. Archive) are listed as added by Blockbase (Premium). This **not** consistent with AT sites.
4. Click on one of the Blockbase (Premium) templates to edit it, and make any changes. Save changes.
5. View the live site, refresh the page, or exit and re-enter the Site Editor.

### What you expected to happen

Changes should be saved.

### What actually happened

After refreshing or re-entering the editor, nothing has changed on the edited template. There's no indication that changes aren't being saved during saving, and no indication that changes were ever made on the template or template list.

### Context

39556765-hc / 5867872-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Replicated on Byrne on simple only.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by jp-imagines** [comment] 2023-01-22 15:18
Also came across this while working with 5861761-zd-woothemes. This site is using the retired `blank-canvas-blocks` theme, a child of Blockbase (not Blockbase Premium).

Updating the issue title to reflect that. Also updating the `platform` response, as I think this only affects Simple sites (on Premium or lower), as both Blockbase themes seem to be restricted to the Business plan or higher.

**Comment by carinapilar** [comment] 2023-01-24 20:35
Seems to be the same issue I found with the Attar theme here: https://github.com/Automattic/wp-calypso/issues/72389 - I'll close that one in favor of this thread.

**Comment by kerrynicl** [comment] 2023-01-30 12:18
also reported by a user on 5908143-zen, using appleton theme

**Comment by carinapilar** [comment] 2023-01-30 17:31
Another one on 5908955-zd-woothemes - with the Kerr theme.

**Comment by cuemarie** [comment] 2023-02-02 18:23
Thank you for these reports! Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/72684

Will share the user reports there

**Closed as completed by cuemarie** 2023-02-02 18:23 UTC
Labels: Bug, [Pri] High, Triaged, [Platform] Simple
