### ISSUE TITLE
Nav Unification: nav locale does not match calypso locale

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#50372] opened 2021-02-23 12:19 UTC
### Steps to reproduce the behavior

1. Set your general user locale to a non-english locale
2. Create a new site — site will be created in the locale defined in point 1
3. Change your general user locale to another non-english locale
4. Go to customer home for the site created at point 2
5. Notice locale differences between the nav and the rest of the UI — the nav uses the site's locale, while most of the UI uses the current user settings' UI

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="1790" alt="Screenshot 2021-02-23 at 13 12 00" src="https://user-images.githubusercontent.com/1083581/108842574-c6e23a80-75d9-11eb-90f6-c5926b985778.png">

**Comment by cpapazoglou** [comment] 2021-02-25 11:23
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/50312

**Closed as completed by cpapazoglou** 2021-02-25 11:23 UTC
Labels: Bug, [Pri] Normal, [Feature] Calypso & wp-admin Navigation
