### ISSUE TITLE
Store: Disable "Let's Go" button on store setup untill all fields are filled out

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#18816] opened 2017-10-13 12:12 UTC
Users can click in "Let's Go" without adding all the required information, this is allowed and users can continue setting up the store without a valid address, and sometimes causes the screen as well as the button to get stuck and needs a refresh in order to be able to add the info again, this can be seen here: p90Yrv-es-p2 on the minute 2.

They should not be able to click the next button until our expected fields are filled out, and the button should show greyed out.

**How to reproduce:** 
1) Go to http://wordpress.com/store/domain.com
2) Fill some fields and click "Let's Go"

<img width="993" alt="screen shot 2017-10-13 at 14 01 14" src="https://user-images.githubusercontent.com/3812076/31545515-04243f0c-b020-11e7-88f1-6b7a5c2517b6.png">

The button greys out, but the screen gets blocked and no action can be taken until is refreshed.

When this does not happen, here's an example of the setup continuing without valid information:

- http://cld.wthms.co/gJDHyp (cannot upload, gif > 10mb)

**Comment by ryelle** [comment] 2017-10-30 16:22
This was a duplicate of #18793 – this one has more details, so I've moved over the assigned dev and project.

**Closed** 2017-11-13 19:19 UTC
Labels: Store, [Type] Bug
