### ISSUE TITLE
Jetpack checklist: ensure popup arrow is pointing to the toggle

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#33780] opened 2019-06-10 06:52 UTC
In Jetpack checklist guided tour, a popup can be pointing to the empty space between toggle and label text, instead of the toggle:

<img width="637" alt="Screenshot 2019-06-10 at 09 49 40" src="https://user-images.githubusercontent.com/87168/59177564-2463f880-8b65-11e9-9fd1-39ee197a1048.png">

Here's the whole screenshot in case this depends on window width:

![image](https://user-images.githubusercontent.com/87168/59177582-347bd800-8b65-11e9-9b05-85dfbf7240e4.png)

#### Steps to reproduce
1. Have a Jetpack site
2. Go to `https://wordpress.com/plans/my-plan/:site`
3. Press "do it" for downtime monitor task
4. Observe modal

There are similar issues with other modals in other checklist steps as well. 

#### What I expected
<img width="488" alt="image" src="https://user-images.githubusercontent.com/87168/59177674-7147cf00-8b65-11e9-984e-aafcd23c808e.png">

**Comment by ockham** [comment] 2019-06-10 10:11
Dupe of #25932 :grimacing:

**Comment by simison** [comment] 2019-06-10 10:41
Nice, that has some further technical research already so I'll close this one. 👍

**Closed** 2019-11-26 17:45 UTC
Labels: Checklist, Guided Tours, Jetpack, [Type] Bug
