### ISSUE TITLE
Please improve the performance

### ISSUE THREAD

**Issue by ttcath** [Automattic/wp-calypso#74277] opened 2023-03-09 14:55 UTC
### Quick summary

at Mar 09 2023, 22:40:37 from Adelaide, Australia, 146.185.214.151 the average load speed of the website is 5.18 sec.

### Steps to reproduce

1. add ttcath.org into the monitor list at uptima
2. go to the monitoring pattern
3. find the logs on the speed monitoring.
4. read the summary of the speed monitoring.
5. find the result

### What you expected to happen

There is no down and bad performace at WordPress.com Host Website.

### What actually happened

at Mar 09 2023, 22:40:37 from Adelaide, Australia, 146.185.214.151 the average load speed of the website is 5.18 sec.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by ttcath** [comment] 2023-03-09 15:06
@tyxla pls

**Comment by tyxla** [comment] 2023-03-09 15:59
Hi, @ttcath thanks for your report.

Unfortunately, there's not much information in this report on top of what was already provided in #73794. 

I'm fine with keeping the issue open if that helps.

**Comment by ttcath** [comment] 2023-03-10 17:49
@tyxla according to the report given by Uptima, it says:

Mar 11 2023, 01:08:49 SSL monitor invalid at the check point IP: 149.248.7.54 and  31.13.213.16 and 45.32.139.74 and 51.75.170.220

Please check this issue. thx

**Comment by jeherve** [comment] 2023-03-13 12:14
Closing as duplicate of #74358.

**Closed as completed by jeherve** 2023-03-13 12:14 UTC
Labels: Bug, [Pri] Normal
