### ISSUE TITLE
Post Checkout: missing translations in post domain purchase

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#3850] opened 2016-03-08 17:03 UTC
#### Steps to reproduce
1. Starting at URL: wordpress.com/checkout (French locale)
2. Buy a domain (I used WP.com credits in this case)
3. On the success message page the main column is squished against the left sidebar (see screenshot below)
4. Several French strings are unfortunately in English

#### Browser / OS version
Mac-n-Chrome

#### Screenshot / Video
![checkout-fr-broken](https://cloud.githubusercontent.com/assets/66797/13609150/009cbfee-e515-11e5-853b-1682b853c7ce.png)

**Comment by fabianapsimoes** [comment] 2016-03-15 16:39
I can't really reproduce this layout issue. Might have been a temporary issue as we deployed the changes to that page. This is what I see:

![screenshot-wpcalypso wordpress com 2016-03-15 17-25-43](https://cloud.githubusercontent.com/assets/1248436/13785411/bf685f96-ead3-11e5-9c66-a3149e794f4d.png)

There is something weird with the strings though. I don't see some of them in GP even though the code seems to be correctly localized. We're investigating.

**Comment by fabianapsimoes** [comment] 2016-03-16 12:15
> There is something weird with the strings though. I don't see some of them in GP even though the code seems to be correctly localized. We're investigating.

This has been fixed with the help of @hewsut. You might still see the strings in English for a while, until we get them translated.

**Closed by fabianapsimoes** 2016-03-16 12:15 UTC
Labels: Post Checkout, [Type] Bug

**Comment by lancewillett** [comment] 2016-03-16 17:24
I can't repro the layout issue now, either. :+1:
