### ISSUE TITLE
Atomic: Broken wp-admin styling when enabling the classic dashboard in the Hosting Configuration

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#85011] opened 2023-12-08 05:41 UTC
### Quick summary

This has occured only with one user and goes like this:

### Steps to reproduce

1. Make sure you have an AT site.
2. Activate the wp-admin styling under Settings > Hosting configuration.
3. Check the wp-admin dashboard vs the modern dashboard.

### What you expected to happen

The classic dashboard should just show up as expected.

### What actually happened

This is what I see on the user's site:

![image](https://github.com/Automattic/wp-calypso/assets/6737345/b4ec7050-816d-456e-a806-fbd50d8c0116)

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

As a workaround, I had to set the styling to Default(Calypso).

I was only able to replicate it on the user's site, but not locally.

Turning off the plugins and switching the theme and clearing the cache helped a bit earlier, but I think we might've seen that if the user made the dashboard change themselves.

Reported here: 7418723-zd-a8c

One other thing I've noticed is that on my test site I've lost access to the Page Optimize settings, but that's working on the user's site.

Slack thread: p1701944548305829-slack-C03TY6J1A

**Comment by maciejpilarski** [comment] 2023-12-25 20:19
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to reproduce the issue both on my test site and the user site. The Classic WP-admin Dashboard loads fine:
![Markup on 2023-12-25 at 21:17:45](https://github.com/Automattic/wp-calypso/assets/9025643/1a2c14b7-08b2-4e07-8db3-cca77e590545)


📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)

**Closed as completed by maciejpilarski** 2023-12-25 20:19 UTC
Labels: Bug, [Pri] Low, [Feature] Calypso & wp-admin Navigation, Triaged, Customer report [LEGACY], [Platform] Atomic, [Product] WordPress.com, [Feature Group] Other Infrastructure
