### ISSUE TITLE
Editor: Media: cannot add “Media from Google” or "Free photo library" if logged in as a contributor

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#22829] opened 2018-02-26 22:53 UTC
#### Steps to reproduce
1. Log in as Contributor. 
2. Create a post and Add Media from Google Photos, or Free photo library
3. Select an Image 

#### Screenshot / Video
http://g.recordit.co/cm7te1GNLc.gif

#### Context / Source
975529-zen #user-report

**Comment by designsimply** [comment] 2018-02-26 23:14
Tested and confirmed that an image disappears if I try to Add > Media from Google to a post while logged in as a contributor ([1m8s](https://cloudup.com/cE0fw5R83Sx)).

![screen shot 2018-02-26 at mon feb 26 4 13 15 pm](https://user-images.githubusercontent.com/1119271/36701298-1242aaf0-1b10-11e8-8a6f-cbb05fd874ee.png)
<sup>Seen at https://wordpress.com/post/madefortesting426.wordpress.com/2570 using Firefox 58.0.2 on macOS 10.13.3.</sup>

**Comment by thebud15** [comment] 2018-03-28 23:07
@designsimply Hey! Just double checking if we have an update on this issue, as the ticket came back into play at 975529-zen

**Comment by arunsathiya** [comment] 2019-06-01 18:56
This seems to happening because contributors do not have that capacity to upload files to media library. They can only insert from an URL. 

I'm also able to reproduce this behavior with "Free photo library"

In both cases the file would need to be copied to the media library itself. 

I think we could close this issue, as this is the expected behavior.

**Comment by automattic-ian** [comment] 2019-06-03 03:07
@arunsathiya We should not show that as an option then, or Show an error when it happens instead of the current behaviour because it's not great for the users.

**Comment by arunsathiya** [comment] 2019-06-03 03:13
@automattic-ian great point! I am going to tag this with `Fix the flows`.

**Comment by arunsathiya** [comment] 2019-06-03 06:39
I have updated the title and description to indicate that this happens for both `Google Photos library` and `Free photo library`.

**Comment by sixhours** [comment] 2019-06-06 18:35
I started looking into this. It's tricky, because that menu is part of TinyMCE, which is just a wrapper component, not a traditional React component. Ideally we would check a user's permissions before choosing which buttons to display, but I'm not sure how to access the methods to do that from outside a React component, or how to access them from the store if they exist already.

**Closed** 2019-07-11 00:45 UTC
Labels: Editor, FixTheFlows, Media, [Type] Bug
