### ISSUE TITLE
Parent pages do not show up in page editor dropdown when there are many parent/children

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#76170] opened 2023-04-25 03:25 UTC
### Quick summary

This is a hard one to reproduce, as you need a complex site with many pages and a lot of parent and child pages. But it seems like while all the children and parents will show up in wp-admin, when you search for them in the calypso-based page editor, they will not show;

Referring to this section;

![1p6Zn3.png](https://user-images.githubusercontent.com/5075840/234166548-657bddba-e1e7-4ea3-8ba9-df090300c2e1.png)

### Steps to reproduce

1. Have a site with many pages, and parent/child pages.
2. Create a new page, and search for the parent page within the page editor
3. The parent page will not show up. 

### What you expected to happen

The parent will should show up

### What actually happened

The parent page does not show up after a certain number of child/parent pages are created.

See this post for an example; p2EDhh-1Vs-p2

Workaround is to use wp-admin quick edit on the pages dash to select the parent page (it shows up there). 

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment] 2023-04-27 21:40
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/49684

**Closed as completed by cuemarie** 2023-04-27 21:40 UTC
Labels: Bug, [Pri] Low
