### ISSUE TITLE
Site Logs: Webserver (nginx) data from May 1 -22 not available

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#77800] opened 2023-06-05 13:26 UTC
### Quick summary

Not all available log data is available in the dashboard for at least the period of May 1 - 22. 
Data begins showing again on the 23rd. 
Based on what's in logstash I would expect to see data (on today) from May 6th until today. 
I was able to replicate this on 2 user sites and one test site

PHP logs seem to be working fine, only the webserver logs are missing data

As a separate issue: We used to keep this data for 3 months but it seems like we significantly shortened how long it's retained. However, in the site-log area it looks like users can select from much further back. We might want to add to the no data available notice to let users know about this limit. 

### Steps to reproduce

1. on a WoA site, got to site-logs
2. click on the Webserver Logs tab.
3. try to pull up webserver logs from may 1-22 (or any period within)
4. verify that data is present in logstash
5. compare what's returned in logstash to site-logs

### What you expected to happen

should show any data that's available in logstash still

### What actually happened

data in dashboard
![2023-06-05 at 16 09](https://github.com/Automattic/wp-calypso/assets/47717887/24bb8272-d06e-45c0-8856-442087b19bb6)

Data in logstash
![2023-06-05 at 16 10](https://github.com/Automattic/wp-calypso/assets/47717887/f0128742-f363-46a5-8fdb-6e3c66fc3a6f)

On my test site I saw some errors but these aren't happening on the user site so it seems unrelated. On one user's site I did get this network failure though: `https://public-api.wordpress.com/wpcom/v2/sites/188319254/hosting/logs?_envelope=1&_locale=fr`

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

**Comment by worldomonation** [comment] 2023-06-06 05:11
📌 REPRODUCTION RESULTS
Tested on Simple – n/a
Tested on Atomic – not reproducible
Replicable outside of Dotcom – n/a

📌 FINDINGS/SCREENSHOTS/VIDEO
On a WoA test site of mine I was not able to reproduce this issue - 937 entries between May 1 - 22 matches the count in Logstash.

<img width="1451" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/baced62b-5114-4900-a885-0f51cff735be">

<img width="726" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/8eb35fc5-9016-48e7-906a-0ef8fd88ec1f">

📌 ACTIONS
- set priority to Normal.
- remove Escalated and Needs Triage labels.

**Comment by Nic-Sevic** [comment] 2023-06-06 05:37
Hey @worldomonation 👋 It looks like you tested this for the php logs but not for the webserver ones. The php ones are loading fine, it's only the NGINX logs that are the issue. I switched this back to high to match my conversation with @zaguiini yesterday - p1685967738434309/1685945617.787939-slack-C04H4NY6STW

**Comment by worldomonation** [comment] 2023-06-06 07:15
@Nic-Sevic Got it, I tested it again with a site with `atomic_site_id` of 149888409 and indeed the Webserver Logs don't show anything for between May 1 - 22 despite Logstash > nginx-* showing some entries for the same period.

FYI, the step to click the `Webserver Logs` should be called out in the repro steps. I've added it to the original comment.

**Comment by zaguiini** [comment] 2023-06-06 15:34
@p-jackson could you give this bug some attention? It seems reproducible and affecting users.

**Comment by p-jackson** [comment] 2023-06-12 03:26
FYI, there's work going on with regard to this issue here: p9o2xV-3bh-p2

**Comment by p-jackson** [comment] 2023-09-05 05:24
This issue was discussed and fixed in pMz3w-hHa-p2 and p9o2xV-3bh-p2. We've switched to a new method of finding logs that occurred in the past. I'm no longer able to reproduce this issue in my testing.

**Closed as completed by p-jackson** 2023-09-05 05:24 UTC
Labels: Bug, [Pri] High, [Platform] Atomic
