### ISSUE TITLE
Masterbar: gravatar container looks a bit rough on non-retina displays

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#5058] opened 2016-04-27 16:18 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. On a non-retina monitor the bounding circle around the gravatar looks a bit raggedy and a bit off center (see below)
3. On a retina monitor it appears less raggedy but still off center (see below)
4. Seems to have just happened recently

Chome Version 49.0.2623.112 (64-bit) on OSX El Capitan 10.11.4
External monitor: HP 2010i at 1600x900 via Thunderbolt to DVI-D

#### Screenshot / Video

Non-retina:
![screen shot 2016-04-27 at 9 12 35 am](https://cloud.githubusercontent.com/assets/1595739/14859380/c241de94-0c58-11e6-8ea1-6779372ea3a1.png)

Retina:
<img width="272" alt="screen shot 2016-04-27 at 9 16 54 am" src="https://cloud.githubusercontent.com/assets/1595739/14859398/d289ee9a-0c58-11e6-80c3-3d0095673988.png">

**Comment by drw158** [comment] 2016-04-27 16:42
Hm that is strange. I can't reproduce on Chrome or Safari.

**Comment by shaunandrews** [comment] 2016-04-27 17:14
I'm willing to bet $100 you have your browser zoomed.

**Comment by designsimply** [comment] 2016-05-03 20:20
Closing after testing with Chrome 50.0.2661.94 on Mac OS X 10.11.4 with zoom set to 100% without being able to reproduce the problem.

**Closed by designsimply** 2016-05-03 20:20 UTC
Labels: Masterbar, Navigation, [Type] Bug
