### ISSUE TITLE
Widgets Screen: Widgets placed randomly in Veni theme

### ISSUE THREAD

**Issue by Sandkorner** [Automattic/wp-calypso#46658] opened 2020-10-21 19:41 UTC
#### Steps to reproduce

1. Starting at URL: /wp-admin/themes.php?page=gutenberg-widgets
2. Activate the Veni theme - https://wordpress.com/theme/veni
3. Add different widgets to different widget areas (i.e Calendar, Image, Search)
4. Save the changes in editor
5. Compare front-end widget placement to back-end

#### What I expected
All widgets should show exactly in the same place as added.

#### What happened instead
Widgets seem to be placed randomly in different widget areas. 

#### Browser / OS version
Version 86.0.4240.75 (Official Build) (64-bit) // Windows 10 Pro Version 2004

#### Screenshot / Video
![Scrambled](https://user-images.githubusercontent.com/71094068/96773255-ea5b6580-13ec-11eb-9303-c4a24016ab80.gif)

#### Context / Source

#manual-testing

More context: p58i-9wi-p2#comment-47757

**Comment by ericamQA** [comment] 2021-04-23 17:04
Unable to reproduce (testing with Dashboard Appearance setting both on and off) on Mac. Also tested in Windows 10, not reproducible. Closing issue.

**Closed** 2022-01-26 16:18 UTC
Labels: [Closed] Not Reproducible
