### ISSUE TITLE
Nav drawer: Should Plugins have external link icon?

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#33007] opened 2019-05-14 03:24 UTC
I was examining the plugin installation flow, and I noticed that Plugins don't have the external link icon (see the Import item below for comparison). 
![image](https://user-images.githubusercontent.com/4550351/57668598-32e4f000-764b-11e9-9a63-b8f68c3f4e7f.png)

I think it would make sense to use the same icon with Plugins, since both Plugins and Import link to Calypsoified version of wp-admin, which has very different nav design. I think this would only apply to Business and Ecommerce plans tho (so whenever the Calypsoified plugins page kicks in), since lower level plans are showing a Calypso page instead, with a nudge to upgrade.

For comparison:
* plugins page on a site with Premium plan:
![image](https://user-images.githubusercontent.com/4550351/57668449-b18d5d80-764a-11e9-865f-661c41f93e80.png)

* plugins page on a site with Business plan (and at least one plugin installed):
![image](https://user-images.githubusercontent.com/4550351/57668526-faddad00-764a-11e9-8551-8add02e0738f.png)

#dogfooding, #manual-testing,

**Comment by sixhours** [comment] 2019-05-17 18:57
We're going to hold off on doing anything with this until we have a better sense of how the new sidebar carries over to Calypsoify.

**Comment by sixhours** [comment] 2019-06-25 17:21
I personally think we should only use the external link icon to visually indicate that we're opening a new tab or window, since I think that's the most common expected behavior. @lcollette since you're working on the accessibility of the ExternalLink component right now, this is tangentially related!

**Comment by sixhours** [comment] 2019-07-01 16:53
Looking at this again, Import and Export both open in a new window, so they use the external link icon. I think if we want to add this icon to Plugins, it should follow the same behavior and open in a new window.

Whether we should actually be opening these menu items in a new window has yet to be determined... :)

**Comment by lcollette** [comment] 2019-07-17 18:05
Plugins now has an external link icon. Going to close this out.

**Closed by lcollette** 2019-07-17 18:05 UTC
Labels: FixTheFlows, Navigation
