### ISSUE TITLE
Editor: Media: Stuck scrolling in gallery preview

### ISSUE THREAD

**Issue by ryanboren** [Automattic/wp-calypso#3389] opened 2016-02-18 17:07 UTC
Gallery preview often will not scroll. Scrolling gets stuck for all layouts except Individual Images. I've seen this in Macnchrome and the Mac App. In the screenshot below, the preview grid cannot be scrolled. Scrolling instead bleeds through to the page beneath.

![screen shot 2016-02-18 at 10 45 39 am](https://cloud.githubusercontent.com/assets/2047747/13151321/462ee126-d62f-11e5-972e-dea2c6d08257.png)

More details and a screencast:
https://test.wordpress.com/2016/02/11/editor-media-stuck-scrolling-and-scroll-bleed-in-gallery-preview/

**Comment by ryanboren** [comment] 2016-03-08 14:18
Stuck scrolling also occurs in the editor embed view of the gallery, especially when the gallery is first inserted. The preview and embed views both regularly exhibit stuck scrolling. For embed views, I've taken to flipping to HTML and back to clear stuck scrolling and bring back the gallery's inline toolbar when it goes missing. These three bugs ruin gallery flow.

**Comment by designsimply** [comment] 2016-03-22 15:05
Short 58s screencast in case it's helpful: https://cloudup.com/c-QN9we8OhX

**Comment by ryanboren** [comment] 2016-09-08 16:07
I experienced this again with thumbnail grid.

https://test.wordpress.com/2016/09/08/session-notes-reader-notifications-gallery-grid-publicize-nonce-expired-domain-macnchrome/

**Comment by lancewillett** [comment] 2016-09-08 18:32
@aduth Can you have a look, please? In case it's a regression.

**Comment by aduth** [comment] 2016-09-08 18:59
From the post and my own testing, I believe it may be a separate but related issue with our utility to calculate frame dimensions. It still appears to scroll correctly when the height exceeds the preview area, and can often be fixed by toggling to a different display type and back to thumbnail grid, but occasionally it appears to incorrectly crop the height too short, and it's not possible to reveal the rest of the preview. It might be caused by the images loading (and consuming more space) after the markup is displayed in the frame, though the frame size calculation _should_ be accounting for this already.

**Comment by aduth** [comment] 2016-09-26 22:51
Fixed in r142756-wpcom . While we were monitoring the [document for mutation events via `MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver), this did not take image loading into account, so the dimensions of the frame could be inaccurate. By simply adding a `load` event listener to the window of the frame and sending a resize message when triggered, the frame correctly resizes after images load. This is similar to how we [forcefully trigger the TinyMCE `autoresize` command after images load in our media plugin](https://github.com/Automattic/wp-calypso/blob/705535ae7ce91bf70f5f0ae5ce4095ddef6e3be9/client/components/tinymce/plugins/media/plugin.jsx#L665).

Since we've duplicated this logic into the [`<ResizableIframe />` component](https://github.com/Automattic/wp-calypso/tree/master/client/components/resizable-iframe), I'll plan to follow-up with a pull request to update this component. This may also resolve cases where we've seen clipping of oEmbed frames in the editor.

**Closed by aduth** 2016-09-26 22:51 UTC
Labels: Editor, Media, [Pri] BLOCKER, [Type] Bug
