### ISSUE TITLE
Redirect to WooCommerce -> Home after Woocommerce Bookings purchased (role issue)

### ISSUE THREAD

**Issue by wprhunt** [Automattic/wp-calypso#65214] opened 2022-07-04 21:26 UTC
### Quick summary

After the purchase of the WooCommerce Bookings plugin through the WordPress.com dashboard, there becomes a role issue with the WordPress.com user and all links in the wp-admin/ redirect to WooCommerce -> Home (wp-admin/admin.php?page=wc-admin)

### Steps to reproduce

Haven't been able to reproduce yet but my assumption would be:

1. Be on the Pro plan with a new site
2. Purcahse the WooCommerce Bookings plugin
3. Attempt to access any wp-admin/ pages (redirect occurs)

### What you expected to happen

No further action should be required for the user to have access to all WooCommerce and wp-admin pages after purchasing.

### What actually happened

No wp-admin pages can be accessed and they all redirect to the Home section of WooCommerce.

### Context

HC-35958467

### Simple, Atomic or both?

Atomic

### Reproducibility

Once

### Severity

One

### Available workarounds?

Yes, difficult to implement

### Workaround details

The fix we tried is for an HE to run the following CLI commands:
`$ wp role reset --all
$ wp plugin deactivate woocommerce
$ wp cache flush
$ wp plugin activate woocommerce`

However, this then appears to cause a conflict where they now lose access to the WooCommerce Bookings plugin and will get a "You need a higher level of permission. Sorry, you are not allowed to edit posts in this post type." message when they visit the bookings page (wp-admin/edit.php?post_type=wc_booking)

The next fix is then to set their user role to add shop_manager via CLI: `> wp user add-role ID#here shop_manager`

It's unclear if the issue is just that the shop_manager role needs to be added when the Bookings plugin is installed after purchase but that would be my guess as to the cause.

**Comment by edwinho89** [comment] 2022-07-08 03:32
35675805-hc

User does not have any other Woo extensions other than WC Payments though

**Comment by edwinho89** [comment] 2022-07-08 04:28
Maybe related to https://github.com/woocommerce/woocommerce/issues/32045 ?

**Comment by maxlaf** [comment] 2022-07-11 02:06
Another case in 5364213-zen

No Woo extensions aside from WCPay.

**Comment by cuemarie** [comment] 2022-07-12 17:47
📌 SCRUBBING
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- Was not able to replicate this. Summary of test:

- On a site with WooCommerce active and set up, I tested /wp-admin and WooCommerce pages - all behaving normally.
- I then purchased the WooCommerce Bookings plugin via the Plugins page.
- After purchasing that, all WooCommerce and wp-admin pages continued operating like normal.
- Able to visit `/wp-admin/edit.php?post_type=wc_booking` as well

https://user-images.githubusercontent.com/27249804/178556956-4aeaf587-aaa6-47ee-b70b-97c15f672858.mp4

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- It seems that just purchasing and activating WooCommerce Bookings doesn't trigger the underlying role issue. 
- My test site does have more Woo Extensions active, but I wasn't able to cause any redirection issues with deactivations either. 
- If we can determine how to replicate the underlying issue, please reopen this issue (or report anew if WC Bookings is not the key trigger of the issue.

**Comment by edwinho89** [comment] 2022-07-22 02:02
Reopen GH as it occurred again in 31899886-hc , where user constantly redirects to `wp-admin/admin.php?page=wc-admin` on any wp-admin navigations.

No WooCommerce Booking extension, however the workaround does work in resolving the issue.

```
$ wp role reset --all 
$ wp plugin deactivate woocommerce 
$ wp cache flush 
$ wp plugin activate woocommerce
```

**Comment by syhussaini** [comment] 2022-09-26 07:43
Here is another one caught with the same behavior.

5584906-zen

I tried the steps mentioned by @edwinho89
WooCommerce activated a Safe Mode after that.

**Comment by maxlaf** [comment] 2022-09-30 22:40
5596378-zen. No Woo extensions aside from WCPay. Tried to replicate this on an AT site a little while ago but was unable to. The workaround solved the issue.

**Comment by ericfri** [comment] 2022-10-01 21:20
5599477-zen

The workaround worked once, then the issue came back. I wasn't able to gain access to the WooCommerce settings, they kept redirecting to the WooCommerce home page.

I tried running the workaround reset multiple times and it would somewhat work but the issue kept coming back.

**Comment by wpshellbelle** [comment] 2022-10-02 12:40
37206872-hc

Workaround worked for this user

**Comment by wpshellbelle** [comment] 2022-10-03 18:59
37028143-hc

Workaround worked here

**Comment by ericfri** [comment] 2022-10-07 21:43
37306331-hc

Workaround seems to have worked.

**Comment by cuemarie** [comment] 2022-10-11 17:33
📌 ACTIONS
- escalated with Woo folks to see where we can direct this to get more eyes on it. p1665509505157279-slack-C3NCP7ZJ6

**Comment by cuemarie** [comment] 2022-10-11 19:08
📌 ACTIONS
- Since this is only happening within WPcom, it was recommended this stay in `/wp-calypso`
- Marking as Triaged for Quality Squad review. 

📌 Message to Quality Squad
- This has been tough to replicate, but based on the reports above it's still happening with some consistency

**Comment by tvolpert** [comment] 2022-10-18 15:54
- [ ] 25173624-hc

This user didn't have the Bookings extension installed. Based on the description in the original post, I tried `wp user add-role ID#here shop_manager` without resetting the other roles first, and that seems to have worked here.

**Comment by edwinho89** [comment] 2022-10-21 03:02
- [ ] 5647838-zd-woothemes

Applied workaround in WPCLI

**Comment by wpshellbelle** [comment] 2022-11-21 14:54
26853317-hc

Workaround worked for this user

**Comment by jartes** [comment] 2022-12-03 08:47
Another one in 37880237-hc

The workaround worked. Thanks for it!

**Comment by edwinho89** [comment] 2022-12-08 07:19
38573928-hc

Ran `role reset --all` alone seems to do the trick.

**Comment by wpshellbelle** [comment] 2022-12-21 13:37
38955702-hc

Workaround worked here, too. :-)

**Comment by wyter** [comment] 2023-02-28 14:18
6002163-zen

**Comment by epeicher** [comment] 2023-04-13 13:34
**Backlog grooming:** I have been able to reproduce it. This is the request with the redirect
<img width="772" alt="CleanShot 2023-04-13 at 15 32 42@2x" src="https://user-images.githubusercontent.com/3519124/231775252-07e86d2d-6bb4-48b0-b95b-ee35c76b1810.png">

**Comment by wpshellbelle** [comment] 2023-05-01 20:09
43090958-hc 
Workaround worked here

**Comment by cpapazoglou** [comment] 2024-12-05 13:13
Closing this as https://github.com/Automattic/wp-calypso/issues/73547 is more broad.

**Closed as completed by cpapazoglou** 2024-12-05 13:13 UTC
Labels: Bug, [Pri] Normal, Triaged, WooCommerce, Customer report [LEGACY], [Platform] Atomic
