### ISSUE TITLE
New editor: links disappear when adding several in one paragraph

### ISSUE THREAD

**Issue by ValeDeOro** [Automattic/wp-calypso#5352] opened 2016-05-12 10:06 UTC
I have an link-problem (or rather, the user has) I ​*think*​ this is a Calypso issue, but do correct me if I am wrong.

When adding multiple links to a same paragraph, the last link sometimes voids all previously added links of the post. User says "This has only begun happening since the "new and improved" editor became available. I did my edits on the "old and usually reliable" editor (MacBook running 10.6.8 and Firefox 46.0.1).”

Theme: Twenty Ten
Ticket: 2656582-t

I was not able to replicate, but he has reported the same problem a second time, so there might be something to it?

**Comment by ValeDeOro** [comment] 2016-05-12 10:55
Additional info from the user: 

"This has also happened in previous posts, but I thought it was a temporary glitch that you or others would catch and report. I guess it is good to speak up.

The action of it is the same from the last several years;
highlight the appropriate text
insert the link via the toolbar
repeat for the next link.

Now, however, sometimes it works; but, sometimes only the most recent link remains. In this case, even the final link was unlinked (which I thought had remained in the final draft but evidently it is gone now, too.)"

**Comment by designsimply** [comment] 2016-05-12 15:57
I tried the steps outlined above and was not able to reproduce the problem where links disappear. Here is a video and a list of steps I tried: https://cloudup.com/cpR6PNyIWHZ

1. Start a new post at https://wordpress.com/post 
1. Add a title and a few paragraphs of text and save
1. Highlight a word
1. Click the link icon in the visual editor toolbar
1. Fill in the URL field
1. Click the Add Link button
1. Repeat the last 4 steps a few times for a few words that are close together

Results: links are always added normally in my testing. I used Firefox 46.0.1 on Mac OS X 10.11.4 for this test.

I am closing this issue because there aren't any reliable steps to reproduce the problem. If further reports come in (currently this is just one report from one person) or if you are able to find different steps for testing, please re-open the issue.

**Closed by designsimply** 2016-05-12 15:57 UTC
Labels: Editor, OSS Citizen, [Type] Bug
