### ISSUE TITLE
Page and Post Title paste function is deleting the current content

### ISSUE THREAD

**Issue by TPilgs** [Automattic/wp-calypso#66326] opened 2022-08-06 01:59 UTC
### Quick summary

On any page or post title in the editor, trying to paste any content in addition to what is already there will delete the old title and replace it with the new. This happens as if the previous content was highlighted, but is occurring even without content being highlighted and with the cursor at the end of the current word/title. 

Here's a video: https://d.pr/v/uxXDiU @

### Steps to reproduce

1. Open any page or post, and add any word to the title.
2. Copy another word to your clipboard.
3. Place the cursor anywhere at the front or back of the current title without highlighting anything.
4. Paste the other word, and the previous word will disappear as if it were highlighted instead of being added to.

### What you expected to happen

The pasted content should just add to where the cursor was selected.

### What actually happened

The paste function deletes all of the previous content, regardless of where the cursor is located.

### Context

36238450-hc

Also, this is a self-hosted and old Gutenberg version of what should be happening: https://d.pr/v/fETmXP

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Because of the inherently short nature of post or page titles, all they need to do is just manually add in the content without pasting.

**Comment by Joshgrygiel** [comment] 2022-08-09 16:35
📌 SCRUBBING
- Tested on P2 - N/a
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can confirm that on my simple and AT testing sites, when trying to paste a post title from the clipboard, the paste replaces all content that was previously saved as the title rather than applying the pasted text to the end of the title:


https://user-images.githubusercontent.com/88345647/183707666-cae43911-dcbf-4471-88f4-ccdaccd02097.mp4



📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Greatdane** [comment] 2022-08-10 05:11
Gutenberg issue:
- https://github.com/WordPress/gutenberg/issues/43066

and the likely culprit:
- https://github.com/WordPress/gutenberg/pull/42321

**Comment by Greatdane** [comment] 2022-08-10 05:21
Would like to be notified; 5460407-zd-woothemes

**Comment by Jaccuse** [comment] 2022-08-13 22:51
Would like to be notified, another case in 36459243-hc

**Comment by TeniCola** [comment] 2022-08-18 22:02
Another case I could replicate in 5489437-zen -- the user would like to be notified.

**Comment by aamills** [comment] 2022-08-19 20:53
Wouldn't hurt to notify the user in 5491934-zen

**Comment by syhussaini** [comment] 2022-08-27 04:01
> Wouldn't hurt to notify the user in 5491934-zene 

Notified the user.

**Comment by youbrokesomething** [comment] 2022-09-29 14:59
This was fixed as part of Gutenburg v14.0 and I cannot reproduce the issue anymore. Please reopen this ticket if it comes up again.

**Closed as completed by youbrokesomething** 2022-09-29 14:59 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] Normal, Triaged, [Block] Page List, [Platform] Simple, [Platform] Atomic

**Comment by cuemarie** [comment] 2023-06-08 01:04
_Decision was made here: p1683245378229639-slack-C0160HSMDQV that batch replies for users impacted by this issue will not be sent out._
