### ISSUE TITLE
Self-Hosted Sites: Cannot Exit Gutenberg using "W" or "Reader" Buttons

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/wp-calypso#49435] opened 2021-01-28 23:52 UTC
### Description

On a self-hosted site (e.g. created with J-Ninja) with SSO enabled, unable to use the "WordPress" or "Reader" buttons to exit the Gutenberg editor.

### Steps

1. Create a site on J-Ninja, enable Jetpack and add a WordPress.com user. Enable SSO from Jetpack settings of the site.
2. As the WordPress.com user, select the Jetpack site and click the "write post" button
3. Attempt to navigate out of the editing view with the "W" or "Reader" buttons (top-left). 

**Got**: These buttons don't seem to work and the user is stuck in the editor view.
**Expected**: I would be transported to the WordPress.com dashboard or the Reader, respectively.

Was able to reproduce in both Safari and Chrome.

![self-hosted-cannot-exit-editor](https://user-images.githubusercontent.com/8979548/106212950-ea57c800-6188-11eb-8d1d-6e4985218009.png)

**Comment by nsakaimbo** [comment] 2021-01-28 23:56
👋  pinging @cpapazoglou to help raise visibility on this one - this seems like an easily-encountered, high-priority issue that would leave many self-hosted users stuck if attempting to use the editor.

**Comment by cpapazoglou** [comment] 2021-01-29 07:48
👋 @nsakaimbo! Thanks for the ping! 
Can you confirm that the issue you describe is the same as https://github.com/Automattic/wp-calypso/issues/49122 . The fix will be shipped in Jetpack 9.4 (next week).

**Comment by getdave** [comment] 2021-02-08 11:50
@nsakaimbo Were you able to have a moment to confirm this?

**Comment by nsakaimbo** [comment] 2021-02-09 17:47
@getdave I'm not sure if this fix is supposed to have been shipped yet, but I just tested with a newly created Jetpack site and the bug is still present ("Reader" and "My Sites" buttons are broken) - I confirmed that the Jetpack version installed is v9.4.

**Comment by cpapazoglou** [comment] 2021-02-10 09:16
@nsakaimbo 
- Is nav-unification enabled on this site? It should not, since it is neither a Simple nor Atomic
- Using `?calypsoify=0` in the URL seems to resolve the issue for me

@mmtr is there a chance you know what is going wrong here?

**Comment by getdave** [comment] 2021-02-10 10:18
I've replicated this issue. The `Write` button (top right) uses a different URL than `Posts -> New`. Will update with more details.

To replicate:

* Create a site on J-Ninja, 
* Enable Jetpack.
* Add a WordPress.com user. 
* Enable SSO from Jetpack settings of the site.
* Click `Write`.
* You will go through to the editor loading screen but it will show "Loading failed". Sit tight  and wait.
* The page will auto-load and redirect you to a "Calyipsoified" URL `https://your-ja-site.com/wp-admin/post-new.php?calypsoify=1&block-editor=1`.
* Attempting to return using `W` icon or hitting back will send you to the Calyipsoified version of the page.
* In addition when attempting to view the site again via Calypso you will be served a menu containing only the "Calypsoified" plugins items:

<img width="274" alt="Screen Shot 2021-02-10 at 10 22 32" src="https://user-images.githubusercontent.com/444434/107496994-e749d800-6b89-11eb-90c9-f605ebe61969.png">

This is cached in IndexDB so you cannot escape without taking the following steps:

* deleting IndexDB
* hitting `Write` again, waiting...
* modifying the resulting URL to `calypsoify=0`

I'd say given that this can trap users in Calypsoify we might consider this a Blocker.

**Comment by mmtr** [comment] 2021-02-10 10:59
This is not a new issue introduced by the nav unification, since I was able to reproduce it in the _old_ navigation (currently enabled for all non-a12s). Furthermore, I believe this only happens on Jurassic Ninja sites since I cannot reproduce it on my local Jetpack site. Likely the "loading failed" screen displayed when going to the editor is caused by a cross-domain-origin issue which may be specific to JN sites.

I will further test this with a Jetpack site hosted on Pressable, but since the issue is not related to the nav unification, I wouldn't consider it a blocker.

> The Write button (top right) uses a different URL than Posts -> New

On my tests, both the Write button and the Posts -> New menu item use the same URL, so it happens when clicking on any pf them. The issue is that the editor refuses from being loaded in the Calypso iframe, so Calypso redirects to the Calypsoified editor as a fallback, which is the correct and expected behavior. 

What we have to fix, is that when the user clicks on the W button in the Calypsoified editor for going back to Calypso, Calypsoify should be turned off to avoid unexpected Calypsoified screens.

**Comment by mmtr** [comment] 2021-02-10 11:18
> I will further test this with a Jetpack site hosted on Pressable

The issue is reproducible on Pressabe sites as well, so likely any Jetpack issue is affected by this.

I think we can close this issue as a duplicate of https://github.com/Automattic/wp-calypso/issues/36400. cc @getdave

**Closed as completed** 2021-02-10 14:30 UTC
Labels: Bug

**Comment by getdave** [comment] 2021-02-11 10:18
This response from Kirk summarises the situation https://github.com/Automattic/wp-calypso/issues/36400#issuecomment-536083060
