### ISSUE TITLE
Gutenberg: are we missing core client block CSS?

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27635] opened 2018-10-05 02:44 UTC
Let's investigate if we're missing an enqueue for core blocks on published posts for Simple Sites.

Make sure to test this on a site that is opted in already to Gutenberg in wp-admin

Participating themes may also include additional CSS on the published view with:
```
add_theme_support( 'wp-block-styles' )
```

**Comment by vindl** [comment] 2018-10-10 15:55
I've verified that this is not the case and that blocks that I initially flagged as problematic in the audit are actually working as expected (most likely my testing setup was flawed). I can still reproduce some of the minor bugs with Image and Gallery blocks, but since they are not related to the above generic problem I think we can close this issue.

I've created two more specific and smaller ones for the remaining bugs: https://github.com/Automattic/wp-calypso/issues/27744 and https://github.com/Automattic/wp-calypso/issues/27748.

**Closed by vindl** 2018-10-10 15:55 UTC
Labels: [Goal] Gutenberg, [Pri] High, [Type] Task
