### ISSUE TITLE
Gutenberg v10.1.0 - Crashing editor/browser when latest Instagram posts block is added

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#50778] opened 2021-03-04 21:57 UTC
1. On both AT and simple sites with Gutenberg 10.1.0 active...
2. Add the Latest Instagram Posts block and connect it to an Instagram account and try to publish the page. (Or open a page where that block is already published)
3. The editor crashes and uses a tremendous amount of browser resources. 

#### Browser / OS version

Chrome Version 88.0.4324.192 (Official Build) (x86_64)

#### Does this happen on simple or atomic sites or both?

 Both

#### Is there any console output or error text?
![Markup 2021-03-04 at 13 50 24](https://user-images.githubusercontent.com/41035049/110035494-9cd2fb80-7cf0-11eb-80bf-e3ba047569d3.png)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Affects any editor that has the Latest Instagram Posts block connected to an Instagram account.

**Comment by jordesign** [comment] 2021-03-04 22:23
I've been able to recreate on a WPCOM simple site as well.

Different console error though..

```
Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at setAriaExpanded 
    at HTMLDocument.init
```

**Comment by jordesign** [comment] 2021-03-04 22:42
Also recreated on a Vanilla WordPress installation with TT1 active and only Jetpack and Gutenberg plugins installed.

**Comment by gwensmithx** [comment] 2021-03-05 00:31
This seems to be related. I have a customer on a simple site and Instagram gallery block was crashing the homepage. I opened the Classic Editor and removed it.

#28053687-hc / #3794424-zd

**Comment by jordesign** [comment] 2021-03-05 04:51
Another user affected in #28193265-hc. they're going to wait out the fix

**Comment by pablinos** [comment] 2021-03-08 06:35
Noting that [Gutenberg 10.1.1](https://github.com/WordPress/gutenberg/releases/tag/v10.1.1) has been released (p7DVsv-aMy-p2) to WordPress.com, which solves this issue.

**Comment by Gilmoursa** [comment] 2021-03-08 15:51
Unable to reproduce in Gutenberg 10.1.1. Closing the issue

**Closed as completed by Gilmoursa** 2021-03-08 15:51 UTC
Labels: Bug, [Feature] Post/Page Editor, Triaged
