### ISSUE TITLE
Domains: Inline error messaging too narrow on tablet sized screens

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#12630] opened 2017-03-29 14:49 UTC
On the domain contact information screen the inline error messaging is difficult to read because of the narrow confines of the form layout.

![image](https://cloud.githubusercontent.com/assets/12596797/24460796/5a09c116-146d-11e7-9c7d-be05b22eea74.png)

**Comment by designsimply** [comment] 2017-03-29 19:21
I have seen this happen on large screens in some cases as well (ignore the console warning, it's unrelated):

![screen-shot-2017-03-13-at-mon-mar-13-6-41-17-pm](https://cloud.githubusercontent.com/assets/1119271/24472338/9411bcfa-1482-11e7-8210-d1c81e71f151.png)
<sup>Seen at https://wordpress.com/checkout/no-site using Safari 10.0.3 on Mac OS X 10.12.3.</sup>

(internal ref: p8hwqp-jU-p2 #comment-138)

**Comment by klimeryk** [comment] 2017-07-20 01:00
As @designsimply mentioned, this was caused by https://github.com/Automattic/wp-calypso/issues/12559 which was fixed in https://github.com/Automattic/wp-calypso/pull/12744.
Screenshot proof 😉:
<img width="442" alt="screen shot 2017-07-20 at 02 58 46" src="https://user-images.githubusercontent.com/3392497/28395871-94d3bbac-6cf7-11e7-9ef6-4e6bfc473f84.png">

**Closed by klimeryk** 2017-07-20 01:00 UTC
Labels: Domains, [Type] Bug
