### ISSUE TITLE
Editor: remove margin from last item in visibility

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1816] opened 2015-12-18 15:03 UTC
Raised by @mtias 

Minor thing, but remove the bottom margin here:

![image](https://cloud.githubusercontent.com/assets/548849/11191774/876fdb12-8c9d-11e5-91ca-85da61317b5f.png)

**Comment by mtias** [comment] 2015-12-18 15:17
Duplicate of #374.

**Closed by mtias** 2015-12-18 15:17 UTC
Labels: Editor, [Pri] Low, [Type] Bug, [Type] Janitorial
