### ISSUE TITLE
Nav unification: Hide option to select Admin Color Scheme in `profile.php`

### ISSUE THREAD

**Issue by frontdevde** [Automattic/wp-calypso#47037] opened 2020-11-03 08:53 UTC
This issue is part of the effort of combining color schemes in the Nav unification project. 
For the approved direction please see https://github.com/Automattic/wp-calypso/issues/45675#issuecomment-714664414.

Move Matthew's work to Jetpack.

pbAPfg-Ou-p2#comment-1965

**Comment by mreishus** [comment] 2020-11-03 14:35
* The wp-admin color scheme setting is currently hidden on non-Atomic sites (redirect to Calypso).
* Picture of setting: 
![color-schemes](https://user-images.githubusercontent.com/937354/97998270-82732a80-1daf-11eb-928c-4c86c8fa9a30.png)

**Comment by mreishus** [comment] 2020-11-03 14:38
554-gh-wpcomsh

**Comment by mreishus** [comment] 2020-11-06 15:43
Currently waiting for a way to control who sees it and who doesn't on atomic.

**Comment by cpapazoglou** [comment] 2020-12-09 13:36
Eventually we will keep this in wpcomsh (paYJgx-1cP-p2#comment-1483). It will be triggered by a filter in jetpack `jetpack_color_schemes_loaded` https://github.com/Automattic/jetpack/pull/18034/files .

Addressed here 554-gh-Automattic/wpcomsh

**Comment by cpapazoglou** [comment] 2020-12-14 12:58
Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/47038

**Closed by cpapazoglou** 2020-12-14 12:58 UTC
Labels: Nav Unification
