### ISSUE TITLE
Primary domain on paid plan stays primary when moved to free site.

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#62153] opened 2022-03-23 02:01 UTC
### Quick summary

A primary domain that is associated with site A (paid plan) can keep its primary status, or be allowed to set a primary status, when moved to site B (free).

### Steps to reproduce

1. Create a site with domain and the WordPress.com Personal plan.
2. Set that domain as primary, if not already.
3. Create, or choose at random, a free site.
4. Transfer that primary domain to the created or chosen free site.

### What you expected to happen

The free site should maintain its *.wordpress.com address.

### What actually happened

The primary domain on the old site is now the primary domain on the new site, no plan required.

### Context

Discovered when fixing 4883791-zd-woothemes.

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Available workarounds?

There is no user impact

**Comment by edequalsawesome** [comment] 2022-03-23 21:12
The user from that ticket's account was set as exempt from Primary with Plan Only, so this is the expected behavior -- more about that here: P6Ya1B-Nh-p2

Closing this since the expected behavior 😃

**Closed as completed by edequalsawesome** 2022-03-23 21:12 UTC
Labels: Bug
