### ISSUE TITLE
NUX: /start/survey page yields blank WordPress logo

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#8419] opened 2016-10-03 20:11 UTC
#### Steps to reproduce
1. Open URL: https://wordpress.com/start (which redirects to /start/survey)

#### What I expected
To begin the NUX flow

#### What happened instead
The only thing displayed is a blank WordPress logo

#### Browser / OS version
Observed in OSX and Linux Chrome and Firefox

#### Screenshot / Video
![screen shot 2016-10-03 at 4 09 44 pm](https://cloud.githubusercontent.com/assets/7233112/19052187/d5512e2e-8983-11e6-935c-82c2b901dea2.png)

#### Context / Source
#automated-testing

**Comment by ockham** [comment] 2016-10-03 20:48
Caused by #7600, fixed by #8420.

**Closed by ockham** 2016-10-03 20:48 UTC
Labels: NUX, [Type] Bug
