### ISSUE TITLE
People: Do not display UI for editing WP.com site owner

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#3447] opened 2016-02-21 22:54 UTC
Currently, when an admin attempts to edit the site owner of a site, an error notice is displayed. Since we don't allow editing, we shouldn't even show the form that would allow editing a site owner.

Originally reported in #3140. I fixed the issue in the API in r131094-wpcom.

**Comment by BandonRandon** [comment] 2016-02-21 22:56
Closing as duplicate of: #3299

**Closed by BandonRandon** 2016-02-21 22:56 UTC
Labels: People Management, [Type] Task
