### ISSUE TITLE
Post Preview in Firefox Not Working

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#65755] opened 2022-07-19 19:45 UTC
### Quick summary

Previewing a post on a Premium site with Firefox isn't working as expected -- I'm seeing a page not found error

### Steps to reproduce

1. Create a site with the WordPress.com Premium plan on Firefox with a custom domain
2. Create a new post, save as a draft
3. Attempt to preview the post

### What you expected to happen

That I would be able to see the post preview

### What actually happened

I was taken to a 404 page

### Context

5377841-zen

~I was originally able to duplicate this on my test site, but for some reason haven't been able to since my initial test -- I've been able to do this reliably when SSP'd in as the customer in the ticket with a draft post there, though.~ I must have gotten a cookie somewhere along the line for my test site, but I'm able to duplicate it with a new site:

![2022-07-19 16 14 43](https://user-images.githubusercontent.com/4000628/179840314-c3532bc9-a999-45e6-9ba6-2167c4647914.gif)

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

macOS Firefox 103.0b9, Firefox 102.0.1

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by supernovia** [comment] 2022-07-19 23:59
Could this be related? https://github.com/Automattic/wp-calypso/issues/65716

**Comment by Robertght** [comment] 2022-07-20 04:25
Isn't it the same as this: https://github.com/Automattic/wp-calypso/issues/57812 ?

**Comment by JoshuaGoode** [comment] 2022-07-25 13:26
> Isn't it the same as this: #57812 ?

Yes, I'd consider this a duplicate. Probably easier to reproduce on Firefox due to default security/cookie settings.

**Comment by JoshuaGoode** [comment] 2022-07-25 13:32
Copied notes over and closing in favor of https://github.com/Automattic/wp-calypso/issues/57812

**Closed as completed by JoshuaGoode** 2022-07-25 13:32 UTC
Labels: Bug, [Pri] High, [Platform] Simple
