### ISSUE TITLE
Arbutus: unordered lists not showing bullet points in Gutenberg

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#86948] opened 2024-01-29 13:32 UTC
### Quick summary

When the Arbutus theme is active, the bullets in the unordered lists don't appear in the editor. They do show in the preview and live view.

### Steps to reproduce

1. Activate Arbutus.
2. Open the post editor.
3. Adda. List block, then add some items (unordered list).

### What you expected to happen

Bullet points should show in the editor as they do in the live view.

### What actually happened

Bullet points don't show in the editor:

![Screenshot 2024-01-29 at 10-30-55 Edit Post ‹ Site title — WordPress com](https://github.com/Automattic/wp-calypso/assets/4965723/76b25d0f-a265-42ec-9e43-6500b30a4206)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported in 7594073-zen

**Comment by ariel-maidana** [comment] 2024-01-29 13:39
7594073-zen Please notify the user once we have a fix.

**Comment by liviopv** [comment] 2024-01-31 16:05
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
backend
![CleanShot 2024-01-31 at 16 01 38@2x](https://github.com/Automattic/wp-calypso/assets/14153300/ea5e5f0d-c2f0-4336-8389-3853d874a095)

frontend
![CleanShot 2024-01-31 at 16 03 19@2x](https://github.com/Automattic/wp-calypso/assets/14153300/1ea86da1-fa8d-4732-8770-d388eade3971)

Dupe of https://github.com/Automattic/themes/issues/7613

📌 ACTIONS
- Closed as duplicate / by design 


📌 Message to Author
@ariel-maidana please search for duplicates in future bug reports.

**Closed as completed** 2024-01-31 16:06 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] High, Needs triage, Customer report [LEGACY], [Platform] Simple, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience
