### ISSUE TITLE
Plugins: difference of opinion between Plugins > Manage and sidebar

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#22718] opened 2018-02-22 17:54 UTC
On a Jetpack site, you can often end up in a situation where the Plugins > Manage view declares that you have no updates available, but the sidebar indicates that you do:

![plugins_ _life_of_beau_lebens_ _wordpress_com_and_wp_com_business_atomic_ _wordpress_com](https://user-images.githubusercontent.com/108942/36555158-6c372996-17be-11e8-8d90-b0b227ccdfd1.png)

I believe this happens due to a difference in the data source being used to drive each of these views. We should bring them in line either way to make sure that they agree with each other (and ideally eliminate whatever source is inaccurate).

In this specific case, I saw the sidebar notice, clicked through to the plugin management view, then saw that there were actually no updates available. At that point I went to the Activity Log and noticed that Jetpack had just been updated (using the Beta plugin, with autoupdates).

**Comment by tyxla** [comment] 2018-03-07 14:02
Note that the site indicator will show that there are updates available not only if there are plugin updates. Some of these cases are when the site has:

* an older (not the latest) version of WordPress
* one or more themes that have new versions
* translation updates available

So in those cases, the site indicator is accurate. Should we keep it as-is in that case @beaulebens?

**Comment by beaulebens** [comment] 2018-03-12 16:45
@tyxla yep, I don't want to mess with the other statuses right now. All this issue is concerned with is the fact that you can come to this page and have the sidebar tell you that there are plugin updates available, and the main page content tell you that there are none.

The most common situation when I've seen this follows the one reported:

> I saw the sidebar notice, clicked through to the plugin management view, then saw that there were actually no updates available.

I've definitely seen it from plugins other than the Jetpack Beta one as well.

**Comment by lezama** [comment] 2018-03-19 19:48
I couldn't replicate so far, @beaulebens anything in particular I could do to reproduce it?

**Comment by beaulebens** [comment] 2018-03-19 20:08
My hunch is that this is related to having a plugin which is set to autoupdate, which has an update available, and that update is (for some reason) triggered while you're in Calypso. I'm not 100% sure about that, but I _think_ that's a common thread.

So you visit Calypso for a site that has a plugin with autoupdates enabled, and an update available. By visiting the plugins page, you trigger the update, so when you land there, there's nothing left to update. The sidebar hasn't realized yet though, so it still shows the update available icon.

I just tried another variation and it looks like if you have plugins which do _not_ have autoupdate enabled, and navigate to the "Updates" tab under Plugin Management and manually update them, then the sidebar updates/clears correctly.

**Comment by beaulebens** [comment] 2018-03-19 20:10
If you have a site with a plugin that has an update available, that is _not_ auto updating, and you navigate to the individual plugin page, and update from there, the sidebar does _not_ clear properly.

**Comment by beaulebens** [comment] 2018-03-19 20:18
Here's a sequence of screenshots showing the above (perhaps variation, perhaps related to the same data/state management): https://cloudup.com/cao28nTBY7U

**Comment by rachelmcr** [comment] 2018-08-29 15:34
I tested today with a Jetpack site that had a plugin update notice (for a plugin that doesn't autoupdate):

1. Open My Sites in Calypso and see the sidebar notice about a plugin update.
2. Click the notice to go to the plugin updates page.
3. Update the plugin.

Result: The sidebar notice immediately cleared when I saw the success notice for the successful plugin update.

I also tested on a site with a plugin set to autoupdate, and once the autoupdate finished (while I was in Calypso) the sidebar cleared as well.

I'm closing this issue as it seems to be working as expected now, but please reopen if this is still reproducible under certain conditions.

**Closed by rachelmcr** 2018-08-29 15:34 UTC
Labels: FixTheFlows, Jetpack, Plugins, [Pri] High, [Type] Bug
