### ISSUE TITLE
Jetpack Connect: Respect URL redirect for detecting Jetpack

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#10981] opened 2017-01-26 21:54 UTC
Related: #10980

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/jetpack/connect/personal
2. Enter a URL that redirects to a Jetpack site

#### What I expected

To be prompted with checkout for Personal plan.

#### What happened instead

I'm prompted to activate Jetpack:

![screen shot 2017-01-26 at 4 49 26 pm](https://cloud.githubusercontent.com/assets/1779930/22351789/8f3d5d72-e3e7-11e6-9225-c7f2c8e7b4a9.png)

#### Context

This is most confusing when considering that many users will not differentiate between `www.example.com` and `example.com` . In fact, this is the trap I suffered myself. Assuming the example case, I'd entered `example.com`, when my site's canonical URL is `www.example.com`. This being the first time I've activated Jetpack, I wasn't really sure what to expect (the "What I expected" is a lie, I only really knew after figuring out the bug). Therefore I got stuck in this loop where I was constantly trying to activate VaultPress for my site and being sent through the Connect flow. Not knowing any better at the time, I couldn't figure out why VaultPress was never becoming activated. It turns out that the connect flow couldn't detect the redirect and thought that Jetpack had yet to be activated on my site.

p1485465371024635-slack-jpop-support

**Comment by johnHackworth** [comment] 2017-04-07 13:09
so let me see if I got this... your site was already connected, but without using www in its url, and once you entered the same url, using www, it treated it as a completely new site?

**Comment by sirreal** [comment] 2017-04-25 15:14
Here are the steps I'm following:

1. I have a Jetpack site. Jetpack is activated, but not currently connected (it _has_ been previously connected).
1. Visit https://wordpress.com/jetpack/connect/personal
1. Enter URL with 301 redirect to Jetpack site (request has the following HTTP headers).
   > HTTP/1.1 301 Moved Permanently
   > Location: ...
1. The redirection seems to be resolved correctly because I wind up at the authorize screen for my Jetpack site (where the 301 points to).
1. After authorization, I end up at https://wordpress.com/jetpack/connect/plans/jonsurrell.wpsandbox.me. This is where the flow differs, when using the direct URL (not behind the redirect) I end up at the checkout screen. 

The problem that I can see now is that you don't end up at the checkout with the Personal plan selected as we'd expect. I'm not being asked to activate Jetpack on a site where it's already activated.

@aduth Can you confirm whether this is an accurate description of the problem right now or if I'm missing something?

**Comment by aduth** [comment] 2017-04-25 17:49
>I'm not being asked to activate Jetpack on a site where it's already activated.

@sirreal Do you mean you _are_ being asked? If so, that sounds about right.

**Comment by sirreal** [comment] 2017-04-25 17:58
> Do you mean you are being asked?

I was not asked to activate Jetpack. I have not been able to reproduce that part of your original issue. I would like to see if you can still reproduce that.

The only problem I see from your original issue is the following:

**I expect to** be sent to Checkout with the Personal plan in my cart.

**Instead** I end up at the Plans page, to pick a plan.

**Comment by aduth** [comment] 2017-04-25 18:05
@sirreal I'm still prompted to activate Jetpack on the original site where Jetpack is already activated. The one mentioned in the original Slack conversation. It works with `www` but not with the `www` omitted.

p1485466270024664-slack-C0CMN0V97

(This is a live, non-test site)

**Comment by sirreal** [comment] 2017-07-13 16:32
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/Automattic/wp-calypso/issues/10981](https://trello.com/c/LBT2ePHg/68-https-githubcom-automattic-wp-calypso-issues-10981)

**Comment by sirreal** [comment] 2018-03-05 12:57
This is a backend issue, Calypso is behaving as expected.

I've been doing some basic debugging in D10658-code. This may not be a quick fix.

**Comment by sirreal** [comment] 2018-03-05 17:14
A bit of information I've found out.

Some implementation details mean that redirects work transparently for some parts of this Jetpack site check and others are do not. A particularly funny case is that:

A site which is _already connected_ and _behind a redirection_ reports that Jetpack is not active. This is because an already connected site gives a particular error response, which falls through to a connection test against a site_id which fails. At the same time, other checks succeed in verifying that the site has Jetpack installed, all of which, together, leads to this behavior. I'll explore a solution in D10658-code

**Comment by sirreal** [comment] 2018-06-04 15:35
This was fixed by D12573-code (landed).

**Closed by sirreal** 2018-06-04 15:35 UTC
Labels: FixTheFlows, Jetpack, [Pri] High, [Type] Bug
