### ISSUE TITLE
Biyearly Plans show full cost per year on subscription page

### ISSUE THREAD

**Issue by kerrynicl** [Automattic/wp-calypso#65991] opened 2022-07-26 20:23 UTC
### Quick summary

Bi yearly plans are showing the full cost of the subscription for an annual period ( full Cost / year)

### Steps to reproduce

- Add a biyearly plan to an account
- Visit the subscription page from the Purchases page on the account

### What you expected to happen

To show correct price per year or price per period 

### What actually happened

It shows the full cost per year (when it should be two years)
<img width="550" alt="Markup 2022-07-26 at 15 18 06" src="https://user-images.githubusercontent.com/83325600/181104296-efc5c576-a9e1-469a-bef8-d0fae90654af.png">
![Annotation on 2022-07-26 at 15-18-45](https://user-images.githubusercontent.com/83325600/181104419-614045f9-d980-43aa-84de-14e7dcdc89cf.png)

### Context

Discovered from 35415720-HC

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

There is no user impact

**Comment by Joshgrygiel** [comment] 2022-08-02 20:36
📌 SCRUBBING
- Tested on P2 - N/A
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted - N/a 
- Replicable on Core - N/a

📌 ACTIONS
- Closed as duplicate of this report: https://github.com/Automattic/wp-calypso/issues/66025

**Closed as completed by Joshgrygiel** 2022-08-02 20:36 UTC
Labels: Bug, [Feature] Plans & Upgrades, [Pri] Normal, [Feature] Purchase Management, [Feature Group] WPCOM Store & Purchases, Triaged
