### ISSUE TITLE
Editor - Encountered Unexpected error

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#33487] opened 2019-05-31 04:32 UTC
#### Steps to reproduce
1. SSP into user –  and get into the site.
2. Create a new test post, or open an existing test post (there were three when i checked).
3. When you add the title, or try to change anything within Page settings on right side, or even after a few seconds, you will see this error:
![image](https://user-images.githubusercontent.com/6737345/58681685-244e4680-8376-11e9-821f-c3875d66d2e9.png)

Additional info:
@CompChris tried to replicate this changing the language to Chinese as well, but no luck.

This is happening on all devices the user tries.
This user is operating within China.

#### Context / Source
#2058000-zen

**Comment by pauljacobson** [comment] 2019-06-02 06:47
The user shared information in a chat that may be significant. When they sign into WordPress.com with the site owner's account, they're unable to use the block editor. The Classic Editor works fine for them with this account.

On the other hand, if they sign into WordPress.com with their personal WordPress.com account, they can use both the block editor and the Classic Editor. This seems to be specific to the site owner's account.

For more information see p1559225062003500-slack-C02FMH4G8

**Comment by obenland** [comment] 2021-02-08 23:02
I was not able to reproduce it through SSP. Given the age of this ticket there's a good chance this has been fixed in the meantime. The 400+ posts of this user suggest so as well.

Closing for now, please feel free to reopen when this can be reliably reproduced again.

**Closed by obenland** 2021-02-08 23:02 UTC
Labels: Editor, [Pri] Normal, [Type] Bug, user-waiting
