### ISSUE TITLE
The Premium plan should not need to buy the premium theme

### ISSUE THREAD

**Issue by htdat** [Automattic/wp-calypso#14896] opened 2017-06-08 07:38 UTC
#### Steps to reproduce

1. Go to a premium theme like this https://wordpress.com/theme/floral

2. Click the “Pick this design $xx” button 

3. Select my premium site. E.g: premium.wordpress.com

4. The button “Purchase” displays

5. I am redirected to https://wordpress.com/checkout/premium.wordpress.com/theme:floral

6. Looks wrong to me. I delete this theme from the cart. 

7. I go to this link https://wordpress.com/themes/premium.wordpress.com. I can add any theme freely here. 

#### What I expected

- The steps 4 and 5 should not be there: no “Purchase” button and no checkout page
- I can activate the theme right away. 

#### What happened instead

- I am seeing the steps 4 and 5. 

#### Browser / OS version

I am using Mac on Chrome.

#### Context / Source

- Chat: 430947-hc 
- I noticed the issue by myself.

**Comment by designsimply** [comment] 2017-06-08 14:15
Tested and confirmed that with a Premium Plan active I can activate premium themes from within my Calypso site dashboard at https://wordpress.com/themes/:site: but I am asked to pay for the theme for the same site if I start from https://wordpress.com/themes such as https://wordpress.com/theme/floral or from the All Sites view.

**Comment by ockham** [comment] 2017-06-21 19:05
Dupe of https://github.com/Automattic/wp-calypso/issues/157? I hope that after ridding `ThemesSiteSelectorModal` of `sites-list`, we might finally be able to implement something like this. Feel free to ping me for further info.

**Comment by mendezcode** [comment] 2017-06-21 19:11
Hey @ockham, I have been testing for a bit, and yes, indeed it is a duplicate. I'll ping you later on, so we can work together on this.

**Comment by ockham** [comment] 2017-06-26 14:23
@mendezcode https://github.com/Automattic/wp-calypso/pull/9368 might be helpful to get in first

**Comment by lancewillett** [comment] 2018-02-22 17:02
This came up again in a customer feedback survey:

> Customers are occasionally charged for premium themes even when they have a Premium plan

**Comment by rachelmcr** [comment] 2018-08-29 12:12
I ran into this while testing https://github.com/Automattic/wp-calypso/issues/21075. I can reproduce it with the steps above for an account with multiple sites, and for an account with a single site (a more likely case since most users have only one site).

Here's a screencast on an account with a single site (on the Premium plan):

![premium-theme-activate](https://user-images.githubusercontent.com/8658164/44786418-f9875580-ab8b-11e8-9327-4319e592f311.gif)

I got hopeful when I first saw the message "Woohoo! You don't owe us anything!" on the checkout page, but that was while the price was being calculated. That message was then replaced by the checkout screen charging me for the theme.

However, for accounts with only one site, I noticed that if you wait on the theme detail page for a bit, the "Pick this design $xx" button changes to "Activate this design" and you can activate the theme for free. So it seems it's more of an issue for accounts with multiple sites.

**Comment by donpark** [comment] 2019-07-17 05:43
As I mentioned [here](https://github.com/Automattic/wp-calypso/issues/21075#issuecomment-512096258), how about changing how we handle `/theme` to work like how /customize is handled: require site selection before showing themes?

**Comment by Aurorum** [comment] 2019-07-17 16:01
If that's done, it's probably worth ensuring that users who aren't signed in don't need to select a site, as is currently the case.

**Comment by mreishus** [comment] 2021-05-07 21:08
PR Here: Visiting /themes while logged in forces you to select a site #52686

**Comment by mreishus** [comment] 2021-05-20 19:35
#52686 is deployed, which forces logged in users to select a site context when visiting `/themes`.
After visiting `/themes` while logged in, if you have multiple sites, you'll be prompted to select a site, and be redirected to `/themes/<siteurl>`. From there, if you click info on a theme, you'll be brought to `/theme/twentytwentyone/<sitename>`.

However, a logged in user can visit `https://wordpress.com/theme/floral` directly and run into the original issue, but I'm not sure how they would get there (perhaps an outside link). This might be worth looking at or maybe not.

**Comment by kwight** [comment] 2021-05-27 21:56
> However, a logged in user can visit https://wordpress.com/theme/floral directly and run into the original issue, but I'm not sure how they would get there (perhaps an outside link). This might be worth looking at or maybe not.

I think we'll have no choice but to lock down direct links too as the next step – I could see us causing problems by promoting themes in email blasts with direct links, for example.

**Comment by nickpagz** [comment] 2021-06-02 17:36
> I think we'll have no choice but to lock down direct links too as the next step

FWIW, this kills HE work-flow when helping users in tickets or chat. Just saying. 
I understand if it HAS to be done, but would be great if the themes were directly accessible.

**Comment by kwight** [comment] 2021-06-02 22:05
> FWIW, this kills HE work-flow when helping users in tickets or chat. Just saying.

Ah, good point – that's more important than me worrying about potential future what-ifs. 👍

**Comment by nickpagz** [comment] 2021-06-03 01:38
I was also referring to #52686 which `...forces logged in users to select a site context when visiting...`.
Again, not ideal when helping user's. Suggesting a bunch of themes (via links) to users now requires we either a) strip out our test site slug from the url via some sort of Alfred workflow, or b) we SU as the user and copy the links from the theme section on their site. Testing option a) now seems to break things, so it's no longer an option. I get a url like `https://wordpress.com/checkout/null/theme:floral/freetestsite214934814.wordpress.com` which just gives me a blank screen. So that's out. (Test by using a direct link like [https://wordpress.com/theme/floral](https://wordpress.com/theme/floral), then click on the **Pick this design** button, pick a site, then I get a blank screen - no bueno).
I think this is the exact scenario @mreishus mentioned above, ie `However, a logged in user can visit https://wordpress.com/theme/floral directly and run into the original issue, but I'm not sure how they would get there (perhaps an outside link). This might be worth looking at or maybe not.`
So yeah, we need to get HE's to stop sharing those "outside" links to themes directly.

We're now left with option b).

Is there a way to fix the original issue without changing the theme access flow?

**Comment by michaeldcain** [comment] 2021-06-03 19:47
@nickpagz can you use the logged-out view of the Showcase (via an incognito browser)? It doesn't require a site context for either the themes list or single theme pages, and I believe the links are all the same.

**Comment by michaeldcain** [comment] 2022-01-18 15:44
@sixhours: does this issue exist for the newly bundled A8C premium themes? If not, I think we can close it.

**Comment by sixhours** [comment] 2022-01-26 20:09
I can't reproduce it now. Closing!

**Closed by sixhours** 2022-01-26 20:09 UTC
Labels: [Type] Bug, Themes, [Pri] Normal, OSS Citizen, User Report, Theme Showcase, [Pod] Design Selection
