### ISSUE TITLE
Email Notifications: Tags are showing up on the content area of post notification emails

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-calypso#46808] opened 2020-10-27 14:21 UTC
The tags on a post have recently started appearing on the emails in the content area of the post. 

Tags appearing on emails is normal, but tags appearing in the area of the content (twice) is not.

#### Steps to reproduce

1. Create a new post with tags, publish it.
2. Check the email for the post notification.

#### What I expected

Expected the tags to be visible only on this area-
<img width="834" alt="correct email" src="https://user-images.githubusercontent.com/40609190/97313255-6db50500-188c-11eb-927c-825689f5aaa0.png">

#### What happened instead

Instead, the tags appear twice, once on the content are and once where they are supposed to show up anyway-
<img width="919" alt="incorrect email" src="https://user-images.githubusercontent.com/40609190/97313553-c71d3400-188c-11eb-8bda-82cbbafaf61b.png">

#### Screenshot / Video

Tested at my end too-
<img width="624" alt="test " src="https://user-images.githubusercontent.com/40609190/97313793-09df0c00-188d-11eb-8b23-a64eb9e5479b.png">

#### Context / Source

User reported this here- #3433361-zd

**Comment by sdixon194** [comment] 2020-11-13 16:50
Another case here 25225124-hc  - except when using Cyrillic characters, it appears encoded and messy: 

![download](https://user-images.githubusercontent.com/33553323/99098034-6b4ded00-25a6-11eb-9d22-c24fcae9e531.png)

**Comment by obenland** [comment] 2021-01-29 22:54
@ahmadbaig1 Which theme is running on the sites where you noticed that behavior? I was not able to reproduce it on a test site with Twenty Twenty enabled.

**Comment by ahmadbaig1** [comment] 2021-02-06 09:47
I'm sorry I missed noting it down, it should be Twenty Twenty or Hever as per my blog RC.

**Comment by arcangelini** [comment] 2021-07-29 22:06
Currently investigating this but am not able to replicate anything. I have tested on Free and Premium plan with the following themes:

* Blank Canvas
* Hever
* Maxwell

@ahmadawais are you able to replicate this still? If so would you mind sharing the test site you are working on in hopes to narrow in on this issue.

[![Screenshot](https://d.pr/i/ke2uyr+)](https://d.pr/i/ke2uyr)

**Comment by arcangelini** [comment] 2021-08-02 19:32
I was able to test this exact post and it looks like the issue has been resolved.

[![Screenshot](https://d.pr/i/Gp1QUF+)](https://d.pr/i/Gp1QUF)

**Comment by alshakero** [comment] 2021-08-03 11:10
Yup and I tried with the post fully expanded as in the first screenshot, seems to be fixed as well

![image](https://user-images.githubusercontent.com/17054134/128005807-224eccca-ce14-4591-9151-c2b01dd6d8d8.png)

**Comment by arcangelini** [comment] 2021-08-03 21:29
Closing issue. Let me know if we are missing something.

**Closed by arcangelini** 2021-08-03 21:29 UTC
Labels: Email, Notifications, User Report, [Type] Bug
