### ISSUE TITLE
Global Styles: Changes to Layout dimensions are not being saved and it resets to default values

### ISSUE THREAD

**Issue by sudeepbaral** [Automattic/wp-calypso#68895] opened 2022-10-11 10:18 UTC
### Quick summary

While testing  [Feature: Limit Global Styles to Paid Plans ](pdtkmj-EG-p2), our team found the layout dimensions changes are not being saved and it resets to the default 650 for content size and 1000 for wide size.

Video showing the bug:

https://user-images.githubusercontent.com/3326057/195063553-16f259b9-6d16-4a89-ac4d-966783887224.mp4

### Steps to reproduce

1. Create a new site and enable the `wpcom-limit-global-styles` sticker.
2. Open the site editor and toggle the Global Styles sidebar.
3. Go to layouts and change the dimensions
4. Save the changes
5. The dimensions will not be saved and it will reset to the default dimensions

### What you expected to happen

The layout dimension changes should have been saved.

### What actually happened

Layout dimensions were reset back to the default 650 and 1000 px

### Context

CfT for [Feature: Limit Global Styles to Paid Plans](pdtkmj-EG-p2)

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

We tested on Heiwa, Zoologist, Appleton, Livro

### Browser, operating system and other notes

Chrome 105.0.5195.125
Firefox 105

### Reproducibility

Consistent

### Severity

All

**Comment by Joshgrygiel** [comment] 2022-10-11 17:52
📌 TRIAGE REPORT

📌 ACTIONS
- Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/67344

This issue seems to be directly related to that report, with users reporting that the bug affects all of the global styles options, not just the Block Spacing.

**Closed as completed by Joshgrygiel** 2022-10-11 17:52 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Simple
