### ISSUE TITLE
Posts: can't see email addresses in comments on posts

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#13072] opened 2017-04-13 00:56 UTC
This should apply to /pages also [if pages showed comments also](https://github.com/Automattic/wp-calypso/issues/13071).

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts
2. Click comment icon on post with comment

#### What I expected

Can see user's email address (as per wp-admin)

#### What happened instead

No email address shown

#### Browser / OS version

Chrome OSX

#### Screenshot / Video

Calypso:

<img width="1070" alt="screen shot 2017-04-13 at 10 52 30 am" src="https://cloud.githubusercontent.com/assets/128826/24985456/911bba94-2037-11e7-9d84-10029e107684.png">

wp-admin comments view

<img width="885" alt="screen shot 2017-04-13 at 10 54 46 am" src="https://cloud.githubusercontent.com/assets/128826/24985485/cd904aa8-2037-11e7-8bdc-33d91d6281ce.png">

#### Context / Source

#reallife #dogfooding #gaps

**Comment by designsimply** [comment] 2017-05-29 23:39
Tested and confirmed that the commenter's email address is not displayed in My Sites > Blog Posts > {comment icon} whereas it is displayed for the comment view in WP Admin > Posts > {comment icon}.

![screen shot 2017-05-29 at mon may 29 5 33 01 pm](https://cloud.githubusercontent.com/assets/1119271/26563823/968a0ab2-4495-11e7-96a8-c62f2cd56f3d.png)
<sup>Seen at https://wordpress.com/posts/my/design5279.wordpress.com using Firefox 53.0.3 on Mac OS X 10.12.5 logged in as design5279.</sup>

![screen shot 2017-05-29 at mon may 29 5 36 54 pm](https://cloud.githubusercontent.com/assets/1119271/26563824/998e82c4-4495-11e7-9548-346fc1fc1a4a.png)
<sup>Seen at https://design5279.wordpress.com/wp-admin/edit-comments.php?p=10989&comment_status=approved using Firefox 53.0.3 on Mac OS X 10.12.5 logged in as design5279.</sup>

cc @drw158 since you have been involved in recent comment management design work.

**Comment by drw158** [comment] 2017-05-30 16:58
Thanks for the ping. I don't think /posts should be compared with the Comment WP Admin view, but we will have a way for you to see the email in the new Comments section we are working on. It is doubtful that we will add the email on /posts or /pages.

**Comment by designsimply** [comment] 2017-05-30 19:46
Thanks for looking at this @drw158!

I checked one more view, which is looking at comments in the post edit view directly and I can see the commenter email there as well in wp-admin:

![screen shot 2017-05-30 at tue may 30 1 42 08 pm](https://cloud.githubusercontent.com/assets/1119271/26601644/de1cf1f2-453d-11e7-9cb3-d5ccc5420781.png)
<sup>Seen at https://design5279.wordpress.com/wp-admin/post.php?post=10989&action=edit using Firefox 53.0.3 on Mac OS X 10.12.5 logged in as design5279.</sup>

In light of this comment though:

<blockquote>It is doubtful that we will add the email on /posts or /pages.</blockquote>

I am closing this issues as wontfix with a note that email will be available in the Comments section which is currently under development. If this comes up in future user reports, we can re-open the issue at that time.

**Closed by designsimply** 2017-05-30 19:46 UTC
Labels: Comments, Pages, Posts, [Type] Enhancement
