### ISSUE TITLE
[Block] Post Carousel - missing first post when added to FSE Templates

### ISSUE THREAD

**Issue by ezebecke** [Automattic/wp-calypso#73171] opened 2023-02-09 16:55 UTC
### Quick summary

When adding the Post Carousel inside the Index template the carousel starts displaying from the second most recent published post. The new post is skipped. 

Current workaround: Move the Carousel block out of the template and inside the page content. 

### Steps to reproduce

1- Insert the Carousel Post block on the Index template on your FSE theme.
2- Set either the homepage or another page as the Post Page. 
3- Check the post page live.

### What you expected to happen

To view the carousel starts with the most recent published post

### What actually happened

Carousel skips first post. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported on 5925571-zd-woothemes

**Comment by ezebecke** [comment] 2023-02-20 21:20
Another case on 5966669-zd-woothemes

**Comment by tanjoymor** [comment] 2023-02-21 00:26
Another case 40789630-hc 

Did some testing and this happens in Atomic sites as well as Simple.

**Comment by cuemarie** [comment] 2023-03-05 20:09
Very similar issue here:  [**[Block] Blog Posts Block missing first post when added to FSE Templates**](https://github.com/Automattic/wp-calypso/issues/69306)

- This seems to have to do with how the loops that pull posts work on pages versus templates.

📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Could Not Replicate
- Tested on AT: Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Had a hard time replicating - need further details for a better repro test

📌 ACTIONS
- Await author feedback

📌 Message to Author
- @ezebecke & @tanjoymor - what themes did you use to test this? Can you provide more detailed steps to replicate, and screenshots from any test sites as an example?

**Comment by cuemarie** [comment] 2023-03-29 02:03
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**

I suspect the explanation @dsas shared regarding the Blog Posts block applies to this block as well: https://github.com/Automattic/wp-calypso/issues/69306#issuecomment-1327297921 :

> .(a8c/blog-posts) is an [alias of the newspack-blocks/homepage-articles block](https://github.com/Automattic/wp-calypso/blob/67aa5a0e9dd5ec27011a57fe41dac55dbfdabc0e/apps/editing-toolkit/editing-toolkit-plugin/newspack-blocks/index.php#L24-L26) which is synced from the [newspack repo](https://github.com/Automattic/newspack-blocks/tree/master/src/blocks/homepage-articles).
>
>The block does not show the current item in the WordPress loop:
>
>    The [block calls Newspack_Blocks::build_articles_query](https://github.com/Automattic/newspack-blocks/blob/master/src/blocks/homepage-articles/view.php#L24)
>    Newspack_Blocks::build_articles_query specifically says [ignore the current item in The Loop, unless in specific mode](https://github.com/Automattic/newspack-blocks/blob/dc0bb40472f2564e53bf5520b684edb536605fcd/includes/class-newspack-blocks.php#L579-L590).
>
>This has been the case since [June 2020](https://github.com/Automattic/newspack-blocks/commit/030024d70135fa655985aff801568bee2550caa0), the rationale being if you used this block inside a blog post then you wouldn't want to include the current post.
>
>An alternative explanation is that the posts are already appearing on the page via another instance of this block, in which case they might get excluded.

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on a re-triage.  If the Posts shown in the carousel block are missing featured images, the block will break due to https://github.com/Automattic/newspack-blocks/issues/1379 ; something to keep in mind when testing.

**Simple Example - Appleton theme, Index Template (default posts page)**
![Markup on 2023-03-28 at 19:12:59](https://user-images.githubusercontent.com/27249804/228409194-9d5f3e38-a59a-4b31-88b9-864af01bbfc9.png)

📌 ACTIONS
- Assigned to Cylon

**Comment by sophiegyo** [comment] 2023-05-17 12:28
Replicated on Simple, free site. Case: https://wordpress.com/forums/topic/4th-blog-not-displaying/

**Comment by thesacredpath** [comment] 2023-05-26 04:11
Another report here: 6331918-zd-woothemes

**Comment by zdenys** [comment] 2023-06-27 09:43
Another case 6466418-zd-woothemes

**Comment by metabreakr** [comment] 2023-07-17 20:34
Encountered in pdEkSe-43T-p2

**Comment by sophiegyo** [comment] 2023-07-24 05:34
Encountered in https://wordpress.com/forums/topic/the-blog-posts-block-does-not-update-properly/?view=all#post-3974165
Theme: Tenaz

Related to [69306](https://github.com/Automattic/wp-calypso/issues/69306#issuecomment-1638463314)

**Comment by zdenys** [comment] 2023-07-25 08:12
6540472-zd-woothemes Theme Bibimbap

**Comment by jp-imagines** [comment] 2023-09-06 14:40
Another report in 6777525-zd-a8c on Blank Canvas (3). Notably, if the site only has one published post, the Post Carousel block fails to render entirely, which is a bit confusing.

**Comment by caitlindawn** [comment] 2024-01-30 16:11
Reported in 7663430-zen

**Comment by rw-ye** [comment] 2024-05-02 04:59
8134712-zd-a8c - Spiel Theme, Front Page template.

**Comment by adelineyaw** [comment] 2024-06-18 20:56
8352262-zd-a8c - Creatio 2 Theme, Home Template

**Comment by filipanoscampos** [comment] 2024-08-10 08:32
Another case here 8519741-zd-a8c
Assembler theme.

**Comment by philnick206** [comment] 2024-08-11 18:41
Reported in 8595398-zd-a8c

Theme is Twenty Twenty-Four, Blog Home template

**Comment by hacchism** [comment] 2024-08-12 04:42
Reported in 8581068-zd-a8c

Nook theme, Index template.

**Comment by tanjoymor** [comment] 2024-08-20 18:03
Another report on the TT4 theme: 8590913-zd-a8c

**Comment by alaczek** [comment] 2024-08-20 23:59
What's interesting, is that the editor preview is showing the correct posts, the issue only seems to affect the frontend of the site (tested with Poema, Index template).

**Comment by dsas** [comment] 2024-08-21 08:28
> I suspect the explanation @dsas shared regarding the Blog Posts block applies to this block as well: [#69306 (comment)](https://github.com/Automattic/wp-calypso/issues/69306#issuecomment-1327297921) 

I completely missed this ping at the time but your suspicions are correct @cuemarie, the Carousel block uses the same `Newspack_Blocks::build_articles_query` as the Blog Posts block and the problem is identical.
 
> > .(a8c/blog-posts) is an [alias of the newspack-blocks/homepage-articles block](https://github.com/Automattic/wp-calypso/blob/67aa5a0e9dd5ec27011a57fe41dac55dbfdabc0e/apps/editing-toolkit/editing-toolkit-plugin/newspack-blocks/index.php#L24-L26) which is synced from the [newspack repo](https://github.com/Automattic/newspack-blocks/tree/master/src/blocks/homepage-articles).
> > The block does not show the current item in the WordPress loop:
> > The [block calls Newspack_Blocks::build_articles_query](https://github.com/Automattic/newspack-blocks/blob/master/src/blocks/homepage-articles/view.php#L24)
> > Newspack_Blocks::build_articles_query specifically says [ignore the current item in The Loop, unless in specific mode](https://github.com/Automattic/newspack-blocks/blob/dc0bb40472f2564e53bf5520b684edb536605fcd/includes/class-newspack-blocks.php#L579-L590).
> > This has been the case since [June 2020](https://github.com/Automattic/newspack-blocks/commit/030024d70135fa655985aff801568bee2550caa0), the rationale being if you used this block inside a blog post then you wouldn't want to include the current post.
> > An alternative explanation is that the posts are already appearing on the page via another instance of this block, in which case they might get excluded.

**Comment by kelasante** [comment] 2024-08-22 16:19
Another report in 8641073zd-a8c

**Closed as completed** 2024-08-27 14:49 UTC
Labels: Bug, [Pri] Low, Triaged, [Block] Post Carousel, [Feature] Full Site Editor, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Interaction #] > 10
