### ISSUE TITLE
Login: password reset form elements overlap in Chrome

### ISSUE THREAD

**Issue by megsfulton** [Automattic/wp-calypso#40677] opened 2020-04-01 20:30 UTC
#### Steps to reproduce

Password reset email -> password reset form 

#### What happened
New password field and "generate strong password" button are different lengths and overlap

#### Browser / OS version
Chrome (Version 80.0.3987.149) on Mac

#### Screenshot / Video
<img width="665" alt="Screen Shot 2020-04-01 at 1 22 03 PM" src="https://user-images.githubusercontent.com/161697/78183460-ccacbb80-741c-11ea-9258-bb9e1c791774.png">

**Comment by lancewillett** [comment] 2020-04-04 16:01
Here's what the flow looks like in Safari 13.1 on macOS Catalina.

Log in screen: `https://wordpress.com/log-in` — toolbar says WordPress.com, dark blue, pink primary action button.

<img width="1392" alt="Screen Shot 2020-04-04 at 08 55 50" src="https://user-images.githubusercontent.com/66797/78455263-1af6d000-7652-11ea-9ba9-b33e9dfa3abb.png">

Clicking `Lost your password?` goes to `https://wordpress.com/wp-login.php?action=lostpassword` — design changes a lot, toolbar now WP.org light blue and "Powered by WordPress" instead of WordPress.com branding. Primary action button blue. Note: the "back" links also change, which is inconsistent with the previous login screen.

<img width="1392" alt="Screen Shot 2020-04-04 at 08 55 47" src="https://user-images.githubusercontent.com/66797/78455284-3e217f80-7652-11ea-9554-5b065f9b4a65.png">

Enter email address and click "Get New Password". Enter a confirmation screen which appears to be a login screen, too, but looks nothing like the WordPress.com `/log-in` experience in step one above.

<img width="1392" alt="Screen Shot 2020-04-04 at 08 54 35" src="https://user-images.githubusercontent.com/66797/78455331-8d67b000-7652-11ea-8240-200d7113c05e.png">

Email arrives. Example from Gmail:

<img width="892" alt="Screen Shot 2020-04-04 at 08 54 51" src="https://user-images.githubusercontent.com/66797/78455327-850f7500-7652-11ea-8395-7cbf33043ba9.png">

Clicking the link takes me to the screen mentioned by @megsfulton in the issue itself, `https://wordpress.com/wp-login.php?action=rp`:

<img width="1392" alt="Screen Shot 2020-04-04 at 08 54 37" src="https://user-images.githubusercontent.com/66797/78455364-bb4cf480-7652-11ea-8aa1-8d1770d42ed6.png">

**Comment by cathymcbride** [comment] 2021-02-25 15:43
Duplicate of #33924. Closing this one.

**Closed by cathymcbride** 2021-02-25 15:43 UTC
Labels: Login, [Status] Needs Design Review, [Type] Bug
