### ISSUE TITLE
WordPress.com Editing Toolkit plugin causes error when adding a block as a widget through the Customizer

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/wp-calypso#87202] opened 2024-02-05 20:33 UTC
### Quick summary

When adding an Instagram block to a widget area in a classic theme through the Customizer, an error is shown that `The editor has encountered an unexpected error`

This error only occurs when the WordPress.com Editing Toolkit plugin is active on the site and only in the Customizer -- adding the widget through the `Appearance > Widgets` area works as expected, as does adding the Instagram block to another page or post!

*Update:* In further testing, I've seen this is also causing issues with the Map, Embed, Image, and Gallery blocks, and will likely be an issue with other blocks that I haven't gotten to test yet as well!

### Steps to reproduce

1. Set your site to use a classic theme on an Atomic site that has the WordPress.com Editing Toolkit plugin active
2. Go to the Apperance → Customize area of WordPress.com
3. Head to the Widgets panel, and attempt to add an Instagram, Map, Embed, Image, or Gallery widget

### What you expected to happen

The block would be rendered as it normally would, and would ask for the URL of the post to display

![CleanShot 2024-02-05 at 15 31 57](https://github.com/Automattic/wp-calypso/assets/4000628/d920e004-6979-4cb9-8cb5-9401d3ff0e85)

### What actually happened

A notice appears saying that `The editor has encountered an unexpected error`, and the following error is thrown:

```
TypeError: Cannot destructure property 'setShowHelpCenter' of '(0 , c.useDispatch)(...)' as it is null.
at p (https://siteURL/wp-content/plugins/full-site-editing/wpcom-block-description-links/dist/wpcom-block-description-links.min.js?ver=fe7266970d0ff5b9ed9f:6:30318)
at wt (https://c0.wp.com/c/6.4.3/wp-includes/js/dist/vendor/react-dom.min.js:10:47637)
at js (https://c0.wp.com/c/6.4.3/wp-includes/js/dist/vendor/react-dom.min.js:10:120584)
at wl (https://c0.wp.com/c/6.4.3/wp-includes/js/dist/vendor/react-dom.min.js:10:88659)
at bl (https://c0.wp.com/c/6.4.3/wp-includes/js/dist/vendor/react-dom.min.js:10:88587)
at yl (https://c0.wp.com/c/6.4.3/wp-includes/js/dist/vendor/react-dom.min.js:10:88450)
at il (https://c0.wp.com/c/6.4.3/wp-includes/js/dist/vendor/react-dom.min.js:10:85274)
at fl (https://c0.wp.com/c/6.4.3/wp-includes/js/dist/vendor/react-dom.min.js:10:85661)
at Nn (https://c0.wp.com/c/6.4.3/wp-includes/js/dist/vendor/react-dom.min.js:10:32474)
at https://c0.wp.com/c/6.4.3/wp-includes/js/dist/vendor/react-dom.min.js:10:83226
```

![2024-02-05 15 25 07](https://github.com/Automattic/wp-calypso/assets/4000628/e66cc480-c09d-4b16-aa4f-f53949c9d10f)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

* Tested on Twenty Seventeen and Alves, but is likely an issue with all classic themes
* Same results on Firefox and Chrome (latest versions)
* Follow-up in #7696032-zen

**Comment by agrullon95** [comment] 2024-02-06 00:40
@edequalsawesome - I deployed a fix for this issue. You can apply the latest changes by updating the Editing toolkit plugin. Please don't hesitate to let me know if you see any other issues, otherwise we can close this issue.

**Comment by liviopv** [comment] 2024-02-07 15:17
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/Automattic/wp-calypso/assets/14153300/322f1b2f-5b10-4526-b68c-d5d68170e875



📌 ACTIONS
- Closed as fixed

📌 Message to Author
@edequalsawesome I'm closing this as it seems to be fixed already, but please reopen if it's still needed

**Closed as completed by liviopv** 2024-02-07 15:17 UTC
Labels: Bug, [Pri] Low, Triaged, Customer report [LEGACY], [Platform] Atomic, [Product] WordPress.com, [Feature Group] Other Infrastructure, [Feature] Managed Plugins & Themes
