### ISSUE TITLE
Guided tours: Some tours positioned below sidebar

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#26707] opened 2018-08-15 15:54 UTC
Guided tours on the post editor may appear below an open editor sidebar.

#### Steps to reproduce
1. Open the post editor
2. Go to https://wordpress.com/checklist/SIMPLE_SITE_SLUG
3. Start the edit contact page task
4. Notice that with the editor sidebar open, the tour is positioned below.

#### Screenshot / Video

<img width="574" alt="below" src="https://user-images.githubusercontent.com/841763/44158060-ee0f3700-a081-11e8-958f-db2a02512e9d.png">

**Comment by rachelmcr** [comment] 2018-08-21 12:50
Thanks for the report! Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/26441.

**Closed by rachelmcr** 2018-08-21 12:50 UTC
Labels: Design, Guided Tours, [Type] Bug
