### ISSUE TITLE
Editor: social icons disappearing after classic block

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#45764] opened 2020-09-20 10:20 UTC
#### Steps to reproduce

1. Starting at URL: https://dead-horse-canyon.com/blog/meet-the-authors/
2. Tried to add social media icons block after classic block.
3. On preview or live view, block doesn't show. Can find in dev console but height set to 0.

#### What I expected
Icons should show like other set on page

#### What happened instead
- could only get icons to show if placed block above classic block
- also, when look in code editor, see what looks like code for social icons but wrapped in paragraphs (not showing and left from user)
- unable to replicate on test page
- asking user to verify that adding as social media block 

#### Browser / OS version
chrome

#### Screenshot / Video
Visual editor:
 https://snipboard.io/6mJMZO.jpg

code editor:

```
<p>Pete showing his grandson, Skyler, some of his hand-made sweet grass braids used in sacred ceremonies.<!-- wp:social-link {"url":" {YOUTUBE} ","service":"youtube"} /--></p>
<p><!-- /wp:paragraph --></p>
<p><!-- wp:social-links --></p>
<ul class="wp-block-social-links"><!-- wp:social-link {"url":"{FACEBOOK}","service":"facebook"} /--></ul>
<p><!-- wp:social-link {"url":"{EMAIL}","service":"mail"} /--></p>
<p><!-- wp:social-link {"url":"{AMAZON}","service":"amazon"} /--></p>
<p><!-- wp:social-link {"url":"{YOUTUBE}","service":"youtube"} /--></p>
<p><!-- /wp:social-links --></p>
<p><!-- wp:paragraph --></p>
<p><!-- /wp:paragraph --></p>
```

#### Context / Source
#user-report
3331757-zen

**Comment by cathymcbride** [comment] 2020-09-21 20:09
@Nic-Sevic I'm not able to repro either. Did the user verify they were using the social block?

**Comment by synora** [comment] 2021-01-22 16:56
I was able to reproduce this if the icons did not contain a URL. Once I added a URL to the icons, the icons appeared. 

Video: https://d.pr/v/16d2B2

I'll close this issue since 3331757-zen showed them how to convert the Classic Blocks to Paragraph Blocks instead. Social links are appearing as expected on https://dead-horse-canyon.com/blog/meet-the-authors/

**Closed by synora** 2021-01-22 16:56 UTC
Labels: Blocks, Editor
