### ISSUE TITLE
Block Editor: Sometimes autosaves get "stuck" and do not persist changes

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#36191] opened 2019-09-18 19:05 UTC
Some folks are reporting that autosaves get "stuck" without actually persisting content. Unfortunately when this happens and a save is in progress, users cannot manually save because the UI is in a waiting/loading state.

See https://github.com/Automattic/wp-calypso/issues/33362 for some details (though I suspect this can happen in other ways). 

Instead of trying to reproduce: 
- [ ] Simulate the error case, (say an autosave failing or erroring on success), and make sure that the save button UI doesn't get stuck with an appropriate error notice that the autosave did not work.
- [ ] Offer an emergency modal or easy way to copy local work before folks attempt to refresh.

**Comment by davoraltman** [comment] 2020-01-19 15:22
One more report of this. Site 148687910 in 2644913-zen

The auto-saving gets stuck:

![Screen Shot 2020-01-19 at 4 20 51 PM](https://user-images.githubusercontent.com/10340370/72683437-b2c73200-3ad7-11ea-9495-071fbc2bc269.png)

The post in draft can't be published and sometimes the preview can't be viewed.

**Comment by joweber123** [comment] 2020-01-20 10:02
@gwwar The site mentioned in the above comment by @davoraltman may be a good one to take a look at as this issue can be reproduced consistently by trying to create a post on this site and clicking the save button. 

Here is a video: https://d.pr/i/ftkCRd
![Screen Capture on 2020-01-20 at 18-59-56](https://user-images.githubusercontent.com/15944096/125396196-d0304000-e3de-11eb-898b-77d820b237ec.gif)

The error that I am seeing in the console after clicking the save button is the following.

`uncaught exception: Object`

**Comment by joweber123** [comment] 2020-01-20 10:12
**Update:**  I have done some more testing and it appears that this is connected to the theme Full-Frame.

https://wordpress.com/theme/full-frame

I am able to reproduce this on a test site as well when this theme is activated as well.  So far this is the only theme I have seen this issue on.  I get the same error as above and am unable to save.

**Comment by davoraltman** [comment] 2020-01-20 13:09
Great find, @joweber123 ! I can confirm I can reproduce this on my test site with the Full Frame theme activated.

**Comment by gwwar** [comment] 2020-01-20 17:36
cc @johnHackworth for triage

**Comment by cathymcbride** [comment] 2020-10-13 20:22
Moving this over to the themes repo. This issue appears to only happen on this retired premium theme.

**Comment by gwwar** [comment] 2021-04-12 15:58
cc @obenland for triage, as a reminder for devs simulate an error case and see if the UI is still locked.

**Comment by formosattic** [comment] 2021-07-13 05:31
Another report, with the active premium theme [Twotone](https://wordpress.com/theme/twotone).

More details at p2EDhh-1iQ-p2

**Comment by pauljacobson** [comment] 2023-02-15 15:16
I have a report of this issue in 5929222-zen where the site uses Independent Publisher 2.

**Comment by cuemarie** [comment] 2023-04-19 18:38
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Autosave getting stuck and not resolving does not appear to be connected to a specific theme.  Activated **Full Frame**, **TwoTone**, and **Independent Publisher 2** on test sites and confirmed that the autosave feature still works with those themes.

**Example - Simple Site, Full Frame**

https://user-images.githubusercontent.com/27249804/233167763-5092f2f5-f019-498d-a598-ba82327bd69f.mp4

**History**

This has had reports periodically over the years, as well, such as:

- https://github.com/Automattic/wp-calypso/issues/315
- https://github.com/Automattic/calypso-pre-oss/issues/11765

But it doesn't seem that a consistent bug has been identified - it's just an unpleasant experience for the user when this happens.

---

📌 ACTIONS
- Closed as could not replicate (please open a new report with as many details as possible if you find a bug impacting autosaving)

📌 Next Steps
- Since there's nothing here we can really replicate or trigger, I've opened a feature request instead: https://github.com/Automattic/wp-calypso/issues/75976

For users, we also offer advice here on best practices to ensure autosave preserves their work correctly: https://wordpress.com/support/editors/page-post-revisions/#recover-lost-content-on-a-post-or-page

**Closed by cuemarie** 2023-04-19 18:38 UTC
Labels: [Type] Bug, Themes, [Pri] Normal, [Goal] Gutenberg, User Report, Needs triage
