### ISSUE TITLE
Manage Following Refreshing: formatting when only one recommended site is shown

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#14084] opened 2017-05-16 04:56 UTC
When only one recommended site is shown the follow button looks a bit lonely:

<img width="792" alt="one item" src="https://cloud.githubusercontent.com/assets/128826/26090335/9eec6086-3a47-11e7-9786-4c3eef430cf3.png">

This is particularly obvious when dismissing sites and you are left with one:

![remove sites](https://cloud.githubusercontent.com/assets/128826/26090365/d2e9b294-3a47-11e7-973f-7c3f840b6b7b.gif)

**Comment by samouri** [comment] 2017-05-16 20:53
weird. are you seeing any errors in your console?

Whenever it gets down to 2 it should make requests for more and fill really quickly.

**Comment by samouri** [comment] 2017-05-16 20:53
its busted actually. i'll look into this

**Comment by blowery** [comment] 2017-05-17 14:58
@samouri any updates on this one?

**Comment by samouri** [comment] 2017-05-17 16:54
Got sidetracked yesterday. I'm back on course!

**Comment by samouri** [comment] 2017-05-17 17:26
Root cause analysis:
- The api won't respect the number of sites requested.  Even though we are always requesting 4 site recs, it can (and often does) return < 4.  I think this started when we started adding filtering so that it won't return already-followed sites.
- The code relies on having the exact number requested as a mechanism to make sure it doesn't send out duplicate requests.  This is clearly too fragile.

I'll need to build out a more robust store for site recs

**Comment by samouri** [comment] 2017-05-19 05:21
fix in the works here: https://github.com/Automattic/wp-calypso/pull/14247

**Comment by bluefuton** [comment] 2017-05-22 08:33
I believe this should be fixed in #14247 👍

**Comment by bluefuton** [comment] 2017-05-24 09:54
Reopening because it's still possible to get one recommendation:

<img width="791" alt="screen shot 2017-05-24 at 11 53 14" src="https://cloud.githubusercontent.com/assets/17325/26397765/b0ec96ee-4077-11e7-9460-ed32434afffa.png">

**Comment by aaronyan** [comment] 2017-05-26 19:43
@samouri: Yep, I think we can change the API to return the correct number of requested sites. Diff ready for review at D5768.

cc: @gibrown

**Comment by samouri** [comment] 2017-05-26 20:58
@bluefuton, do you have any repro steps? I don't know how to replicate that

**Comment by gibrown** [comment] 2017-05-29 17:04
@bluefuton @samouri it is always going to be possible to get an odd number of recommendations, or to run out of recommendations (after dismissing some). Agree we can make the API better, but the UI should still handle the case where we run out of recos. 

The sun will rise, hail will fall, and server requests will fail.

**Comment by bluefuton** [comment] 2017-05-30 06:37
@samouri No consistent repro steps, but it definitely happens from time to time. 

> Agree we can make the API better, but the UI should still handle the case where we run out of recos.

+1 :)

**Comment by aaronyan** [comment] 2017-06-05 22:09
Deployed changes to API (D5768) that returns the correct number of requested recommendations (as long as we don't run out). Changeset 157404.

**Comment by samouri** [comment] 2017-06-07 11:24
Seeing as we want to look pretty even during hailstorms, I think this becomes a designer question right? 

cc @jancavan @fraying

**Comment by jancavan** [comment] 2017-06-07 15:34
> how should the ui look when we only have one site to recommend?

I think it's fine how it looks now. I've removed the extra padding (as shown on that mockup^^) around a single site rec.

**Closed** 2017-06-07 15:36 UTC
Labels: Reader, [Type] Bug
