### ISSUE TITLE
Premium: Customer is unable to access Chat option at https://wordpress.com/help/contact

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#52315] opened 2021-04-27 03:52 UTC
### Steps to reproduce the behavior

1.  SU to this user of this ticket - #3930016-zen
2.  Go to [https://wordpress.com/help/contact](https://wordpress.com/help/contact)

#### What I expected to happen

Customer sees option to Chat

#### What actually happened

Customer only sees option to Send Email

**Comment by kosiew** [comment] 2021-04-27 03:53
Checked URC and there is no block on chat.

**Comment by inaikem** [comment] 2021-04-27 08:24
Per our support docs, _"Live Chat support is currently available in English. Spanish and Portuguese-speaking Business / eCommerce plan customers will also have access to live chat support in those languages, based on operator availability."_

I have tested but am unable to replicate the ability to access live chat with the interface set to an unsupported language.

**Comment by inaikem** [comment] 2021-04-27 08:27
NB, Additional related discussion here: pcbce7-1eC-p2

**Comment by pauljacobson** [comment] 2021-04-27 14:32
@inaikem This isn't a question of access to chat in languages other than English, but more as the customer put it:

>I had access to live chat in English while using a French interface. Why this isn’t possible anymore?

Based on initial, internal discussions, it seems that the customer ought to be able to access live chat with a qualifying plan, regardless of the language their UI is set to. Reopening this issue so we can investigate further.

Here's the internal thread: p1619529856170500-slack-C6MMLQHAB

**Comment by carinapilar** [comment] 2021-04-27 15:57
This seems expected. [This doc about localized support](https://wordpress.com/support/help-support-options/#localized-support) mentions the following:

> Annual Business and eCommerce plan customers with their language set to French, Italian, German, Dutch, Swedish and Japanese will continue to receive English-language support via live chat and email.

Since the user has a Premium plan, they will only get email support, in French. They would need to change the interface to English to get live chat. Or get a Business and eCommerce plan.

**Comment by inaikem** [comment] 2021-04-28 01:00
Thanks for the input @pauljacobson , @carinapilar. I'm happy to leave this open to foster additional discussion. Leaving this for reference again: pcbce7-1eC-p2

**Comment by kwight** [comment] 2021-05-05 15:30
I'm understanding that this is expected behaviour then, and can be closed as such? (Not optimum behaviour, but not a bug requiring fixing at this point.)

**Closed as completed** 2022-05-12 05:36 UTC
Labels: [Pri] Low, [Status] Needs i18n Review, Happychat, Triaged
