### ISSUE TITLE
Editing published date to the past doesn't work.

### ISSUE THREAD

**Issue by noam87** [Automattic/wp-calypso#7511] opened 2016-08-17 00:55 UTC
#### Steps to reproduce

I tried setting the date to the past, the click "Publish". It set the date to current day.

Also tried opening the date menu again and clicking "update". Also tried just selecting the date.

#### What I expected

For the date to be set back.

#### What happened instead

Date stayed to current day.

**Comment by omarjackman** [comment] 2016-08-30 21:00
I was unable to reproduce the behavior your reporting.

@noam87 Did you make sure to click on a specific day on the calendar before clicking "Update" or "Publish"?

**Comment by lancewillett** [comment] 2016-09-02 18:30
Closing as no reply yet from original author — feel free to re-open if anyone can reproduce this.

**Closed by lancewillett** 2016-09-02 18:30 UTC
Labels: Editor, OSS Citizen, [Type] Bug
