### ISSUE TITLE
Comments: Placeholder text and Log In prompt not translated to site language

### ISSUE THREAD

**Issue by ricklabsdotn8** [Automattic/wp-calypso#82101] opened 2023-09-25 10:56 UTC
### Quick summary

WordPress allows you to change language, and supports most common languages, such as French.

However, it appears that the sites are not being translated automatically, even into commonly used languages such as French.

This issue does not occur on self-hosted sites

Themes
- FSE
- Classic

### Steps to reproduce

1. Change the site language to French, or other language

### What you expected to happen

WordPress elements such as the comments form should be translated

### What actually happened

No translation occurs, and the English version still shows

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

7077523-zen

**Comment by cometgrrl** [comment] 2023-09-25 22:42
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate
- Replicable outside of Dotcom – N/A

📌 FINDINGS/SCREENSHOTS
This seems specific to Verbum comments, but is not reproducible for me on Simple or Atomic sites.

<img width="695" alt="SCR-20230925-nrnr" src="https://github.com/Automattic/wp-calypso/assets/86427589/038702c6-5583-4a35-858c-838a2d1da4c0">
<img width="502" alt="SCR-20230925-nrma" src="https://github.com/Automattic/wp-calypso/assets/86427589/4f489abe-2280-45fb-a461-f98bb1ee27d5">

📌 ACTIONS
- Requested author feedback

📌 Message to Author
@ricklabsdotn8 do you have any more information on this? I can't reproduce it. Although I do see that "Write a comment" inside the box is still in English.

**Comment by cometgrrl** [comment] 2023-09-25 23:19
Asked in Slack: p1695682075092719-slack-C02T4NVL4JJ about the "Write a comment..." text.

**Comment by cuemarie** [comment] 2023-09-28 01:23
Looks like the issue here is specific to the "Write a comment" placeholder text, as well as the "Log in to leave a reply" text. I've left a note on the slack link above as well. 

![Markup on 2023-09-26 at 11_17_16](https://github.com/Automattic/wp-calypso/assets/27249804/cd991412-e2bb-452d-b499-fece198c703a)

📌 ACTIONS
- Triage complete

**Comment by janmckell** [comment] 2024-03-25 19:09
This may be fixed, it seems, as per Slack thread in Vertex channel:
p1710832855023829-slack-C02T4NVL4JJ
Asked the user to test and confirm in the new Ticket that their original Ticket has been merged to:
7875495-zd-a8c

**Closed as completed** 2024-03-25 19:12 UTC
Labels: Bug, [Pri] Normal, i18n, [Feature] Comments, Triaged, Customer report [LEGACY], [Platform] Simple, [Product] WordPress.com, [Feature Group] Content Management
