### ISSUE TITLE
Editor: More Options: explain how excerpts are used in the excerpts info bubble

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22677] opened 2018-02-22 00:39 UTC
Steps to reproduce:

1. Go to https://wordpress.com/ > Blog Posts > (click any post) > More Options.
1. Click the (i) info bubble next to "Excerpt."

<strong>Result:</strong> there is an explanation for what excerpts are but not for what they do. The current description says:

<blockquote>Excerpts are optional hand-crafted summaries of your content.</blockquote>

![screen shot 2018-02-21 at wed feb 21 5 36 27 pm](https://user-images.githubusercontent.com/1119271/36513700-1cbacf52-172e-11e8-8eaa-55dba3839c5b.png)
<sup>Seen at https://wordpress.com/post/madefortesting426.wordpress.com/2353 using Safari 11.0.3 on macOS 10.13.3.</sup>

/hat tip 🤠 @beaulebens for reporting this issue at p4k3M4-2uX-p2. #dogfooding #painpoint

**Comment by benhuberman** [comment] 2018-02-23 19:24
The trickiness here is that what excerpts do -- if at all -- really depends on one's theme and some other settings (excerpts vs. full posts in emails/feeds, etc.). So there's only so much specificity that would make sense here. Would something like the following help?
> An excerpt is a brief summary or description of your content. Some themes display excerpts on your site's homepage and archive pages.

**Comment by beaulebens** [comment] 2018-02-23 19:48
I _think_ we use them in email notifications maybe as well?

**Comment by benhuberman** [comment] 2018-02-23 19:55
Yeah, I mentioned it in my first comment -- the problem is that it's not the default (afaik). So you'd need to mention emails and immediately throw in a caveat about other settings. Unless I'm wrong, and once you add an excerpt, it becomes the default text sent to email subscribers instead of the full post?

**Comment by andfinally** [comment] 2018-03-05 20:12
Is this a duplicate of https://github.com/Automattic/wp-calypso/issues/1580?

I like your wording @benhuberman, it's more informative than the `Excerpts are optional hand-crafted summaries of your content that can be used in your theme` in wp-admin. It's not easy to cover all the possible uses.

**Comment by andfinally** [comment] 2018-03-08 19:58
I've created https://github.com/Automattic/wp-calypso/pull/22973 to hopefully address this and https://github.com/Automattic/wp-calypso/issues/1580.

**Comment by andfinally** [comment] 2018-03-17 17:31
Hi @designsimply, we've merged https://github.com/Automattic/wp-calypso/pull/22973 with Ben's wording

>An excerpt is a short summary you can add to your posts. Some themes show excerpts alongside post titles on your site's homepage and archive pages.

Are we OK to close this issue and the duplicate issue https://github.com/Automattic/wp-calypso/issues/1580?

**Closed** 2018-04-07 17:15 UTC
Labels: Editor, [Status] Needs Copy Review, [Type] Enhancement
