### ISSUE TITLE
Nav Unification: Access to the widgets showing on WP-admin Dashboard page

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#52445] opened 2021-04-30 12:59 UTC
There are multiple widgets showing by default as well as from plugins on the WP-Admin dashboard, that the users have been lost access since we've released the Nav Unification.

What:
It would be great to show the widgets that make most sense somewhere on our new dashboard as well as allow the plugins to show the widgets from them too. Link in case of users using LearnDash ProPanel plugin which shows the information in the widget on the dashboard. 

Why:
Showing the widgets will help the users to not miss the features they were most used to and are now completely missing. 

Sample screenshot of how the widgets come with lots of information on the dashboard:

![Markup on 2021-04-30 at 18:27:27](https://user-images.githubusercontent.com/7382505/116698275-cbfca500-a9e1-11eb-8559-670deb9509e1.png)

Chat: 29281077-hc

**Comment by mmtr** [comment] 2021-05-17 08:37
Thanks for your report, @galakhyati. I think this is a duplicate of https://github.com/Automattic/wp-calypso/issues/50945, where we're discussing different options for keeping the WP Admin dashboard more accessible for users, so I'm closing this issue out in favor of that.

**Closed as completed by mmtr** 2021-05-17 08:37 UTC
Labels: Feature Request, [Feature] Calypso & wp-admin Navigation
