### ISSUE TITLE
"View Post" preview connects to front page instead of individual posts

### ISSUE THREAD

**Issue by gracie** [Automattic/wp-calypso#14614] opened 2017-05-31 00:13 UTC
This issue only happens on WordPress.com subdomains. If a site uses a custom domain, the View button links to the individual post, unless the issue was happening on the site and then it switched to a custom domain (in which case the error also occurs).

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts
2. Beneath one of the posts listed, click "View"

#### What I expected
To see a preview of the specific individual post.

#### What happened instead
The iframe previewed the front page of the site. Clicking through to the post takes me to the front page.

#### Browser / OS version
Chrome 58 on Mac OS X (El Capitan)

#### Screenshot / Video
![hjgjgjh](https://cloud.githubusercontent.com/assets/21203710/26610233/53460f8c-4574-11e7-8f5b-d6ba77e85342.gif)

This was reported in #3220844-t and reproduced on https://graceofbase.wordpress.com

**Comment by lancewillett** [comment] 2017-06-05 17:45
Possibly related to #14456

**Comment by designsimply** [comment] 2017-06-12 22:14
Closing because I was unable to reproduce the problem using the following testing steps. Please re-open if you find something different or can still repeat the problem in testing!

1. Go to https://wordpress.com/posts/cute.wordpress.com (logged in as designsimply).
1. Click "View" beneath the any post that isn't the latest post.
1. Check to see whether the preview opens the relevant post or the blog home page.

<strong>Result:</strong> the preview showing the relevant post opened normally.

<strong>Video:</strong> <a href="https://cloudup.com/coq18xg60jv">18s</a>

![screen shot 2017-06-12 at mon jun 12 4 10 02 pm](https://user-images.githubusercontent.com/1119271/27057616-22dfdb0a-4f8a-11e7-9917-fe97799b4a95.png)
<sup>Seen at https://wordpress.com/posts/cute.wordpress.com using Safari 10.1.1 on Mac OS X 10.12.5.</sup>

**Closed by designsimply** 2017-06-12 22:14 UTC
Labels: Posts, [Type] Bug

**Comment by gracie** [comment] 2017-06-12 22:26
@designsimply thank you for looking! I tested and it works for me now. Here's to the things that get fixed without going in to fix them.

**Comment by lancewillett** [comment] 2017-06-12 22:52
This should have been fixed by recent work by Delta's Team Samus, including:

https://github.com/Automattic/wp-calypso/pull/14815
https://github.com/Automattic/wp-calypso/pull/14844
