### ISSUE TITLE
People: when inviting users, make sure that 'next' button continues to the next field on Android

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#4110] opened 2016-03-17 01:35 UTC
#### Steps to reproduce
1. Go to add a new user either on Android at people/new/$site
2. Type in a username and then click on the 'next' arrow in the keyboard:
![next-arrow-1](https://cloud.githubusercontent.com/assets/11487924/13833744/f037c72e-ebbe-11e5-875d-53d820f06f97.png)
3. See that the username gets saved. Type on the 'next' arrow again:
![next-arrow-2](https://cloud.githubusercontent.com/assets/11487924/13833746/f26ae9c2-ebbe-11e5-960e-f386a47a3095.png)
4. See that the invitation gets sent prematurely.
![next-arrow-3](https://cloud.githubusercontent.com/assets/11487924/13833748/f4fbb1bc-ebbe-11e5-9b55-f27fe4c01c40.png)
![next-arrow-4](https://cloud.githubusercontent.com/assets/11487924/13833749/f5056720-ebbe-11e5-8f09-6ef294cdd62f.png)

#### What I expected
I expected the 'next' arrow to lead me to the next available field. In this case, the Role field. And then the 'Custom Message' field. And then I expect the 'next' arrow to either send the invitation, or be disabled and force me to close the keyboard and use the usual blue button to send the invite (that would probably be ideal, so no accidental invites are sent).

#### Browser / OS version
Android 6.0.1 on Nexus 6, using Chrome 49.0

**Comment by hoverduck** [comment] 2016-05-12 19:52
12May16 Bug Scrub

Confirmed that this is still an issue, as seen above using the default Google Keyboard.  The difference I see when using an alternative keyboard like Swype, however, is that the button never says "Next" (equivalent to Tab), it only ever says "Go" (equivalent to Enter).  So I _think_ part of the problem here is that the default keyboard is displaying Next/Tab when it's actually executing a Go/Enter.

**Comment by hoverduck** [comment] 2016-08-23 19:35
#bug-scrub

Confirmed this is still an issue as documented above.  Since it hasn't been touched in months I'm going to go ahead and close it.  Feel free to re-open.

**Closed by hoverduck** 2016-08-23 19:35 UTC
Labels: People Management, [Pri] Low, [Type] Bug
