### ISSUE TITLE
Plans: Cannot Add Plan to Cart After Cancelling Business on Automated Transfer

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/wp-calypso#13865] opened 2017-05-10 13:52 UTC
#### Steps to reproduce
1. Create a Business site and push through Automated Transfer
2. Visit wordpress.com/me/purchases 
3. Cancel and refund your business plan
4. Visit wordpress.com/plans/$site
5. Notice a lack of ability to upgrade to a plan

#### What I expected

To be able to re-purchase my business plan, or any plan.

#### What happened instead

No upgrade button to add a plan to my cart. 

#### Browser / OS version

Chrome 58

#### Screenshot / Video

![pasted_image_5_10_17__9_50_am](https://cloud.githubusercontent.com/assets/933450/25901894/14ea0842-3566-11e7-8e12-56a5356be526.jpg)

#### Context / Source

User goes through automated transfer, cancels Business plan while also talking to support.
While working with support decides to re-purchase Business and cannot on the Plans page.

#user-report

3202769-t

**Comment by jjchrisdiehl** [comment] 2017-11-21 21:08
**Steps to reproduce**

1. User let Business account expire
2. Site reverted to Free
3. Upgrade buttons on Plans page disappear

**What I expected**

I expected to be able to repurchase upgrades from the plans page.

**What happened instead**

Buttons appeared briefly, but then disappeared quickly.

**Browser / OS version**
Version 62.0.3202.94 (Official Build) (64-bit)

**Screenshot / Video**
Looked the same as above^^

What my Chrome Inspector looked like, see below for explanation vvv
https://cloudup.com/cHjRygo9UbK

**Context / Source**
User let Biz sub expire, cannot resub from plan page since buttons are missing. I checked the space where the buttons are supposed to exist and I noted that the `.plan-features__actions-button` class on a working site is `.plan-features__actions-buttons` with an s after button...perhaps this is causing an issue.

**Comment by gwwar** [comment] 2018-02-10 00:23
@jhnstn can we close this as a duplicate?

**Comment by jhnstn** [comment] 2018-02-19 18:59
@gwwar I've closed out the duplicate issue so we can track progress on this issue.

**Comment by rachelmcr** [comment] 2018-08-30 13:51
I'm closing this as a duplicate of https://github.com/Automattic/wp-calypso/issues/25470, since that one is already assigned/in a project and includes further details.

**Closed by rachelmcr** 2018-08-30 13:51 UTC
Labels: Atomic, Plans, [Type] Bug
