### ISSUE TITLE
Widgets: Welcome to Block Widgets pop-up loads in loop

### ISSUE THREAD

**Issue by aetta** [Automattic/wp-calypso#82831] opened 2023-10-10 20:36 UTC
### Quick summary

When accessing Appearance> Widgets (_./wp-admin/widgets.php_) the Welcome to Block widgets load every time. 

### Steps to reproduce

1. Access your WP.COM account and navigate through Appearance > Widgets (non-FSE themes);
2. Close the "Welcome to Blocks Widget" pop-up or navigate through the Next button until it closes (hitting the Get Started button); 
3. Reload the page and it will load again.

### What you expected to happen

It's expected that the Welcome pop-up will not show every time you access the widget.php page or at least once in a while.

Even if you add a widget, update, and reload the page, the pop-up will load again. 

### What actually happened

The Welcome to Blocks Editor loads every time you access the page.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- Reproducible with Firefox 118.0.1 (64-bit) and Chrome Version 117.0.5938.149 (Official Build) (64-bit);
- Reproducible with Simple sites only;
- Tested with different non-fse themes (Dara, Hever, twenty-twenty-one, etc);
- 7144317-zen

![image](https://github.com/Automattic/wp-calypso/assets/54185702/2d843827-77d0-4682-92be-112c52acd7c7)

**Comment by cuemarie** [comment] 2023-10-10 21:07
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – Could Not Replicate
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated on Simple only with theme Twenty Twenty-One:

https://github.com/Automattic/wp-calypso/assets/27249804/a800bfa6-27b6-4b92-8bd4-0c1703409d5a

📌 ACTIONS
- Triaged

**Comment by ivan-ottinger** [comment] 2024-09-24 15:58
I cannot reproduce this issue. Tested with different non-FSE themes and multiple browsers, including the latest Firefox. → Closing the issue.

**Closed as not planned by ivan-ottinger** 2024-09-24 15:58 UTC
Labels: Bug, [Pri] Normal, [Feature Group] Support, Guided Tours, Triaged, Block Widgets, Customer report [LEGACY], [Platform] Simple, Groundskeeping
