### ISSUE TITLE
Classic view: Settings > General menu item should link to General Settings page

### ISSUE THREAD

**Issue by wongasy** [Automattic/wp-calypso#94451] opened 2024-09-11 20:18 UTC
### Quick summary

We have an A4A WoA site configured to "Classic" View. The "General > Settings" menu item is expected to link to the General Settings page with a "Site Profile" box. However, the menu item takes us to the Settings page (Hosting settings page) instead. As a result, users cannot edit any of the site profile details, like Site Title. Issue reported here: p1726081657524279-slack-C0347E545HR 

| Actual | Expected |
|-------|-----------|
|<img width="1357" alt="Screen Shot 2024-09-11 at 3 57 23 PM" src="https://github.com/user-attachments/assets/40da5dfc-b28c-4022-a139-e7f7a42fb1d2">|<img width="1401" alt="Screen Shot 2024-09-11 at 3 19 49 PM" src="https://github.com/user-attachments/assets/31566367-4967-47b0-8b83-fc09fd88ba63">|

The issue can be reproduced for the site `fuzzydelightfully.wpcomstaging.com` under the `a4ademo` account. See account access details: pfunGA-1mD-p2#details

### Steps to reproduce

1. Log in to the `a4ademo` account.
2. Go to wordpress.com/sites
3. Search for `fuzzydelightfully`
4. Click on "WP Admin" in site overview to get to wp-admin of that site.
5. Select "Settings > General".
6. You'll land on the "Settings" (Hosting Settings) page.

### What you expected to happen

Users should land on the "General Settings" page with a "Site Profile" box, where users can edit the site title.
<img width="1401" alt="Screen Shot 2024-09-11 at 3 19 49 PM" src="https://github.com/user-attachments/assets/31566367-4967-47b0-8b83-fc09fd88ba63">

### What actually happened

Users landed on the "Settings" page without a "Site Profile" box and cannot edit the site title.
<img width="1357" alt="Screen Shot 2024-09-11 at 3 57 23 PM" src="https://github.com/user-attachments/assets/40da5dfc-b28c-4022-a139-e7f7a42fb1d2">

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

To edit Site Title, the user may:

* Go to the wp-admin general settings page directly via: `https://{site-url}/wp-admin/options-general.php`
* Switch to "Classic" admin interface. Then "Settings > General" should take users to `wp-admin/options-general.php`.

Although, what I've noticed is, after changing to "Classic" view, changing back to "Default" view throws an error. 

<img width="1779" alt="Screen Shot 2024-09-11 at 4 15 36 PM" src="https://github.com/user-attachments/assets/fc0da95e-d66a-40fc-9667-6bae62e3493d">

And we remain in some weird state where there's a mix of UI, where "Settings > General" links users to `wp-admin/options-general.php` instead of the General Settings Calypso page. 

<img width="1668" alt="Screen Shot 2024-09-11 at 4 18 10 PM" src="https://github.com/user-attachments/assets/bb44449a-36aa-472b-800d-a9a929ec1166">

This issue can be reproduced with the site `delightfulbuttery.wpcomstaging.com`.

**Comment by autumnfjeld** [comment] 2024-09-12 00:41
Tangential to this, I was wondering:  shouldn't we remove the option to switch to Default style for all A4A sites?
     
<img width="672" alt="image" src="https://github.com/user-attachments/assets/00c5ba23-5f7b-4f9c-bcdb-e23b692cf4f6">

**Comment by wongasy** [comment] 2024-09-12 01:42
@autumnfjeld We're definitely removing it for fully agency managed sites: pdtkmj-2Te-p2#comment-5628

**Comment by arthur791004** [comment] 2024-09-12 02:47
The "Site Profile" box is hidden for the site with the `wp-admin` interface by https://github.com/Automattic/wp-calypso/pull/87709.

Something weird on this WoA site is
* It doesn't have the option, `is_fully_managed_agency_site`
* The value of the `wpcom_admin_interface` is empty instead of `wp-admin`

**Comment by wongasy** [comment] 2024-09-13 17:42
>Could you help to create a new A4A WoA site to check the following options are configured correctly by default:
>
>* `is_fully_managed_agency_site -1`
>* `wpcom_admin_interface - wp-admin`

@arthur791004 Sorry for the late response! The `is_fully_managed_agency_site` is not expected to be present for all A4A sites. It should only be set when the site was created with the "Allow clients to use the WordPress.com Help Center and hosting features." checkbox **unchecked**.

<img width="666" alt="Screen Shot 2024-09-13 at 1 17 13 PM" src="https://github.com/user-attachments/assets/5b070595-2c68-4282-b9f3-acf5464271d7">

`wpcom_admin_interface` is set to `wp-admin` as part of the provisioning process for A4A sites.

I created an A4A site, SSH to the site and ran `wp option get wpcom_admin_interface` to get option value. The initial run failed, throwing a bunch of warnings. I suspect the dust is still settling after transferring to Atomic? I ran the CLI a second time and was able to confirm that `wpcom_admin_interface` is set to `wp-admin`.

```
150768503@awongtestagency1.wpcomstaging.com:~$ wp option get wpcom_admin_interface
wp-admin
Warning: Undefined array key "terms" in /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-sync/src/modules/class-full-sync-immediately.php on line 395
Warning: Undefined array key "sent" in /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-sync/src/modules/class-module.php on line 437
Warning: Undefined array key "themes" in /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-sync/src/modules/class-full-sync-immediately.php on line 395
Warning: Undefined array key "posts" in /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-sync/src/modules/class-full-sync-immediately.php on line 395
Warning: Undefined array key "sent" in /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-sync/src/modules/class-posts.php on line 968
Warning: Undefined array key "comments" in /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-sync/src/modules/class-full-sync-immediately.php on line 395
Warning: Undefined array key "term_relationships" in /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-sync/src/modules/class-full-sync-immediately.php on line 395
Warning: Undefined array key "sent" in /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-sync/src/modules/class-module.php on line 437
150768503@awongtestagency1.wpcomstaging.com:~$ wp option get wpcom_admin_interface
wp-admin
```

>The value of the `wpcom_admin_interface` is empty instead of `wp-admin`.

Are all sites expected to have a non-empty `wpcom_admin_interface` value? i.e. it must be either `calypso` or `wp-admin`?

I've also noticed a weird behaviour for some sites (not just A4A sites), where they're on the `Default` admin interface, while also having a blog sticker `classic-interface-enabled`. I guess the blog sticker is mainly used for metrics and shouldn't have any impact on the functionality. Thought I'd flag it regardless, in case it rings any bells.

**Comment by wongasy** [comment] 2024-09-13 18:56
This could be related: https://github.com/Automattic/wp-calypso/issues/94558

**Comment by Robertght** [comment] 2024-09-27 12:34
📌 REPRODUCTION RESULTS
- Tested on an A4A site - replicated

📌 ACTIONS
- Triaged
- Raised priority from Low to High because this is one of the first pages the users will check while navigating on set up their site.

📌 Message to Author
- Thank you for raising this @wongasy 
- @p-jackson I'm pinging you as well in case this is related to the recent changes [here](https://github.com/Automattic/wp-calypso/issues/94558)

**Comment by phcp** [comment] 2024-09-30 23:05
`delightfulbuttery.wpcomstaging.com` mixing classic and default views: This is an expected behavior due to the preferred view. For "Users" or "Settings > General" pages, when you switch between views using the tab at the top left, the selection is saved and used to render the sidebar the next time.

`fuzzydelightfully.wpcomstaging.com` not linking to the classic view: The `wpcom_admin_interface` option was out-of-sync. It's `wp-admin` on the wpcom side, but it's empty on the remote side. When the menu is rendered, it checks for the option on the Jetpack side. If it's empty, it falls back to the default view. Checking the audit logs, it's unclear when it happened (for the remote to be empty), possibly when the site was provisioned. But I just set this option through Calypso, and it's working correctly now.

@wongasy, do you have more examples of sites with the same issue?

**Comment by wongasy** [comment] 2024-09-30 23:46
>@wongasy, do you have more examples of sites with the same issue?
@phcp No, don't have other examples to share with similar issues of mixed views. 

>The `wpcom_admin_interface` option was out-of-sync.
I wonder if we're not setting the option properly (as persistent data). 

I logged in with the `a4ademo` account and noticed the site `behavearchitecture.wpcomstaging.com` with admin interface set to default. Note that I selected that particular site on purpose because it's a fairly recent site created on September 15. The logic for defaulting `wpcom_admin_interface` to `wp-admin` is definitely in place in September, unless someone explicitly updated the setting after site creation, that site should be using Classic view.

**Comment by phcp** [comment] 2024-10-01 15:58
`behavearchitecture.wpcomstaging.com` has a slightly different scenario, it was created first and then connected to an agency. In that case, the `wpcom_admin_interface` isn't updated to `wp-admin` while connecting, so it kept the previous option (which is unset in this case, falling back to the default). We can consider setting it to `wp-admin` when adding an existing site to an agency if the option is empty, or overriding the previous selection if this is the intended behavior. What do you think?

**Comment by wongasy** [comment] 2024-10-01 16:23
>behavearchitecture.wpcomstaging.com has a slightly different scenario, it was created first and then connected to an agency. In that case, the wpcom_admin_interface isn't updated to wp-admin while connecting, so it kept the previous option

@phcp Ah, that makes sense!  I'd say no change is required then. We shouldn't change the UI for users just because they connected the site to A4A. 

I am no longer seeing the broken behaviour on `delightfulbuttery.wpcomstaging.com` and `fuzzydelightfully.wpcomstaging.com`. I was able to set the admin interface style for both sites and was linked to the correct page when clicking on Hosting > Settings and General > Settings. I've also tested a few more A4A sites on my account and didn't notice mixed classic/default UI. 

If you're able to confirm the A4A site provision logic is indeed setting the `wpcom_admin_interface` option properly without causing the setting to be out-of-sync, I'm comfortable with closing this bug.

**Comment by phcp** [comment] 2024-10-01 18:11
> If you're able to confirm the A4A site provision logic is indeed setting the wpcom_admin_interface option properly without causing the setting to be out-of-sync, I'm comfortable with closing this bug.

Yes, that's correct. The logic for setting `wpcom_admin_interface` to `wp-admin` while provisioning is in place and works fine, and the `wpcom_admin_interface` is included in the allowlist for syncing (added four months ago D152078-code). So, I'll go ahead and close this issue, feel free to reopen if anything similar pops up.

**Closed as completed by phcp** 2024-10-01 18:11 UTC
Labels: Bug, [Pri] High, Triaged, Customer report [LEGACY], [Status] Priority Review Triggered, A4A, Groundskeeping
