### ISSUE TITLE
Gutenberg: Gutenberg Data Causes Conflicts When Switching to Classic Editor in Calypso

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/wp-calypso#32038] opened 2019-04-04 17:45 UTC
#### Steps to reproduce
1. In Calypso, create a page or post with Gutenberg, including an Image block.
2. Convert the site back the Calypso Classic editor.
3. Try to edit the image and other page/post content.

#### What I expected

I expected to be able to be able to edit the page/post normally after converting it from Gutenberg to Calypso Classic.

#### What happened instead

I was able to edit the text, but was not able to edit the image. HTML view shows Gutenberg data is left in the page/post after converting it to Calypso Classic.

While this test was only with Paragraph and Image blocks, the remaining Gutenberg data/tags from other blocks also create conflicts like this: 3688-gh-jpop-issues

#### Browser / OS version

Chrome Version 73.0.3683.86 (Official Build) (64-bit)
macOS Mojave 10.14.4

#### Screenshot / Video

https://cld.wthms.co/79q3aL

**Comment by jeherve** [comment] 2019-04-05 08:25
> Create a page or post with Gutenberg, including an Image block.

Could you specify which editor you used in this case? Was this in wp-admin, or in Calypso? Your screencast looks like Calypso; does this happen in wp-admin as well, after installing the Classic Editor plugin?

**Comment by juliasydnor** [comment] 2019-04-05 09:33
This test was in Calypso on a simple site. The same happens on an AT site in Calypso.

I justed tested again in WP Admin on the same site. I am able to edit the image in WP Admin after converting to the Classic editor, despite Gutenberg data/tags still being there.

I've edited the original post to make that more clear.

**Comment by noahtallen** [comment] 2019-09-15 16:34
I was able to reproduce this on a clean account/site.

**Comment by noahtallen** [comment] 2019-09-15 17:04
Actually, I take it all back. You can actually edit this _very specifically_. If you drag over the content, it will select it.... but you can't select it directly.

See this gif:
![2019-09-15 12 57 26](https://user-images.githubusercontent.com/6265975/64925039-e6f0b600-d7b8-11e9-8125-e76a56869f4e.gif)

My guess is that it's not selecting into the correct image div, since it's surrounded by the gutenberg divs and such.

For example, the HTML for the converted image is:
```
<!-- wp:image {"id":17,"sizeSlug":"large"} -->
<figure class="wp-block-image size-large">
  <img class="wp-image-17" 
    src="https://noahtallentest9.files.wordpress.com/2019/09/pexels-photo- 
    1591447.jpeg?w=819" alt="" />
</figure>
<!-- /wp:image -->
```

For a normally inserted image, this is:

```
<img class="alignnone size-full wp-image-17" src="https://noahtallentest9.files.wordpress.com/2019/09/pexels-photo-1591447.jpeg" alt="pexels-photo-1591447" width="1000" height="1250" />
```

without the surrounding figure element.

To solve this, I imagine we could either strip the outer div (sounds bad, since it could cause issues converting back to blocks), or make the classic editor select the inner div.

**Comment by davipontesblog** [comment] 2020-06-10 03:20
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.

**Closed by davipontesblog** 2020-06-10 03:20 UTC
Labels: Editor, Editor-Compatibility, [Goal] Gutenberg, [Type] Bug
