### ISSUE TITLE
Slow performance opening the editor from Calypso

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#52651] opened 2021-05-07 01:19 UTC
### Steps to reproduce the behavior

1. Go to customer home
2. Do a hard refresh to clear caches. (e.g. ctrl-shift-r or cmd-shift-r)
2. Click on "edit home page"
3. Wait 5-10 seconds for anything to happen
4. The editor starts loading

#### What I expected to happen
There should not be a long delay at step 4.

#### What actually happened
There was a long delay.

### Context

I verified that the delay goes away when I comment out this line of code: https://github.com/Automattic/wp-calypso/blob/8dd4403aedd323372a9c1b8c96c18558521bde8c/client/gutenberg/editor/controller.js#L202 As a result, this was likely introduced in #51108, which waits to load the editor until calypso preferences are present. This is slightly surprising because we would have already loaded the site in customer home before attempting to load the editor, so it's odd the info wasn't already there. 

Regardless, I don't think a 10s delay is an acceptable trade-off for this feature, so I wonder if there is another way to accomplish it without blocking render. This would also be problematic just loading the editor page from a cold cache without loading calypso first. cc @pablinos  

#### Browser / OS version
Firefox

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
High, all navigations into the editor from Calypso URLs.
 
#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent with cold cache

**Comment by noahtallen** [comment] 2021-05-07 01:23
It's also possible that it wasn't a change in #51108, but one of the underlying promises that waits on, which causes the delay. Either  way, I'm not sure it makes sense to block render at all, since editor load performance is already so terrible

**Comment by pablinos** [comment] 2021-05-07 05:00
I'd agree, 10 seconds is not acceptable. Could there be something about requesting the Calypso preferences that is also causing the delay? A round trip API request doesn't usually take that long.

Before this change we were waiting for the editor preference, so I'd be interested to see if commenting out the additional request to get the Calypso preferences also solves the issue.

If the preferences are consistently unavailable at this point, then perhaps the solution involves ensuring the query component is being rendered.

**Comment by simison** [comment] 2021-05-07 09:13
@pablinos could you elaborate a bit on the original change reasoning? This is how I understood it, and please feel free to correct me or provide more context if I'm missing something:

### Problem

With the "advanced" toggle enabled, the "view pages" in this sidebar is linking to calypso when it should link to wp-admin (issue https://github.com/Automattic/wp-calypso/issues/51058)

   <img width="338" alt="image" src="https://user-images.githubusercontent.com/87168/117426815-065bca00-af2d-11eb-89e3-0ce528fc859a.png">

### What happened
The solution in https://github.com/Automattic/wp-calypso/pull/51108 was to open all editor instances in wp-admin directly, without the iframe.

The outcome of that is (apart from the performance issue) that we lose a lot of features that were previously available:
- Help bubble
- Focused launch flow
- In-editor checkout
- Calypso in-editor media modal
- Floating help fab
- etc 

### What I expected to happen

Since the _contents_ of the iframe is already a wp-admin page, I don't see why we should redirect these customers out of that iframe.

Instead, I expected that "view pages" to link to the right place, while the editor stays in the iframe.

**Comment by pablinos** [comment] 2021-05-16 07:53
It's not just that link, I think there are others too, but yes, the idea is to ensure that someone remains in wp-admin and isn't landed in Calypso.

I see what you're saying about the iframe, but we treat the iframe as a Calypso app URL, which loads other features and changes the navigation. There are other considerations here, because there are other circumstances we can't use the iframe, and so we shouldn't be tying the loading of features to the presence of it.

The performance issue is interesting. I haven't had an opportunity to investigate it properly, but we were using the same technique to wait for the editor preference and this change has been in place for a while before the performance issue was noticed. It seems like there could be a combination of things that has caused it.

The Dashboard appearance setting is designed to default to wp-admin, so loading the iframe in this instance will probably create other issues, even if we use a different mechanism for correcting the navigation links.

**Comment by pablinos** [comment] 2021-05-17 09:46
After a bit of trying I managed to replicate this, but the problem was partly related to having 2FA on my account, and that preventing the user settings from being read. Visiting `/me/account` and entering a code, meant that it started working again.

The root cause was that the user settings were being read and not the user preferences, which has a caching mechanism around it, and doesn't require the additional security.

#52911 hopefully resolves the problem by swapping to using the preferences part of the state, rather than user settings.

**Closed as completed** 2021-05-21 21:15 UTC
Labels: Bug, [Pri] High, [Impact] High
