### ISSUE TITLE
Purchases: incorrect copy on Premium theme cancellation

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#4698] opened 2016-04-13 09:31 UTC
The confirmation dialog for Premium Theme cancellation contains plan related copy:

![screenshot-wordpress com 2016-04-13 10-22-15](https://cloud.githubusercontent.com/assets/1248436/14488972/c41592e8-0162-11e6-832e-ec57a4e96bc1.png)

We need to update this with correct copy. cc @ranh 

Steps to reproduce:

- Purchase a Premium Theme from `/design`.
- Go to `/purchases`, find the new theme and hit Cancel and Refund.
- A dialog will show with incorrect copy.

**Comment by ranh** [comment] 2016-04-13 10:55
Instead of "All plan features and custom changes will be removed from your site", we can say "Your site's appearance will revert to its previously selected theme". This is based on what we say in the confirmation email sent after canceling a premium theme.

**Comment by fabianapsimoes** [comment] 2016-04-13 10:58
@spncrb can you confirm that's indeed the current behavior?

**Comment by ranh** [comment] 2016-04-13 11:13
For reference, I tested on this site: https://ranhartstein201604131350.wordpress.com/

**Comment by spncrb** [comment] 2016-04-13 11:37
@fabianapsimoes  Confirmed - seeing the plan copy in cancellation window:
<img width="533" alt="screen shot 2016-04-13 at 12 35 46 pm" src="https://cloud.githubusercontent.com/assets/8921630/14492040/7bb27662-0174-11e6-9a6a-57fc41d7bf91.png">

**Comment by spncrb** [comment] 2016-04-13 14:32
I misunderstood the question.

> Your site's appearance will revert to its previously selected theme

This is an accurate statement. :+1:

**Comment by drewblaisdell** [comment] 2016-05-10 23:43
That dialog appears for all refundable purchases except domains. This probably isn't a big deal for legacy upgrades, but we also should fix this for Google Apps:

<img width="528" alt="screen shot 2016-05-10 at 4 40 15 pm" src="https://cloud.githubusercontent.com/assets/1130674/15165883/532a6974-16ce-11e6-9762-b1c1c43a932c.png">

**Comment by ranh** [comment] 2016-05-11 08:55
Not sure what actually happens when canceling GA. @Lochlaer what do you think we should say here? 

I imagine it's something like "All email addresses and messages will be deleted, as well as any other Google Apps services you used".

**Comment by fabianapsimoes** [comment] 2016-05-11 08:57
Thanks for the input, @ranh. What should we have for the legacy upgrades? Just a generic message as Drew suggested would probably work.

**Comment by ranh** [comment] 2016-05-11 09:09
A generic message like "It will be removed from your site and you will be refunded etc." could work. Getting into any more details could be tricky, for example canceling a space upgrade and custom design is very different.

**Comment by BandonRandon** [comment] 2016-05-16 17:35
> Not sure what actually happens when canceling GA.
When a user cancels Google Apps with us, the reseller relationship is ended. This means we no longer have any control over managing Google Apps for the user (password resets, verify domain, billing management etc). Management is all done for the user via Google directly once cancelled.

Depending on the age of the account one of two things will happen:
**Less than 30 days:** Google will contact user to let them know that the Google Apps trial on the domain is ending. To continue using Google Apps they must provide Google directly with payment

**More than 30 days** The Google Apps account goes back to Google for the duration of the subscription (one year from expiration). As we are not refunded if the user is not in the trial, I would not recommend allowing refunds post 30 days via automated refunds. 

For Google Apps what about a message like:
> Are you sure you want to cancel and remove Google Apps from site? Once cancelled, your account will be managed directly by Google.

Not sure that's the most succinct/clear way to say that (open to suggestions). 

cc: @ranh @fabianapsimoes

**Comment by fabianapsimoes** [comment] 2016-05-18 09:48
@ranh any thoughts on the copy suggested by Brooke?

**Comment by ranh** [comment] 2016-05-18 12:12
This is tricky since it sounds like Google Apps cannot, in fact, be simply "canceled". 

The main question here is how this affects the domain. Specifically, what happens to the DNS records that make the GA account work? Does everything keep working normally, the only difference being that we are no longer acting as middlemen? Or will the service be interrupted in some way?

**Comment by klimeryk** [comment] 2016-05-18 14:07
@Lochlaer and/or @matthusby might be the best person to answer this question :)

**Comment by matthusby** [comment] 2016-05-18 14:42
> Does everything keep working normally, the only difference being that we are no longer acting as middlemen?
Yes, the plan will be moved over to google and they will handle the billing and management going forward.  The service will not be interrupted at all.

For billing, if its less then 30 days old we will refund them and they will need to setup billing directly with google, if its more then 30 days there is no refund.

**Comment by BandonRandon** [comment] 2016-05-18 17:49
> The main question here is how this affects the domain. Specifically, what happens to the DNS records that make all the GA stuff work? 

There are five main cases I see regarding the domain name:
**Domain stays registered with WordPress.com _with_ WordPress.com NS**
 We don't remove the MX and TXT records when the user cancels the plans even if we send things back to Google. Everything will continue to work as long as the account is in good standing (paid for) at Google.

**Domain stays registered with WordPress.com _without_  WordPress.com Name Servers**
User will need to add the MX Records provided by Google at their new NS provider/host. Many host also sell Google Apps and the records needed are standard. They can be found here:
https://support.google.com/a/answer/174125?hl=en

**Domain is transferred away from WordPress.com _with_ WordPress.com Name Server**
We can help the user double check the MX records needed are on their account. (same as first item)

**Domain is transferred away from WordPress.com _without_ WordPress.com Name Server**
User is now responsible for adding the Google MX Reccord and work with their new registrar/host. 

**Domain is cancelled**
Google Apps will no longer have access to the needed MX Records for email to work. The email will stop working.

**Comment by ranh** [comment] 2016-05-19 13:17
How about this for GA?

> Are you sure you want to remove your Google Apps account from WordPress.com? You will be refunded ($88), but your Google Apps account will continue working without interruption. You will be able to manage your billing directly on Google Apps.

@BandonRandon I didn't understand your last comment. Are those scenarios that apply to this flow?

@BandonRandon or @Lochlaer, do you know if there will be a difference in pricing after canceling with us and switching to manage directly with Google?

**Comment by BandonRandon** [comment] 2016-05-19 18:01
@ranh This copy looks fine, except for this part:
> You will be able to manage your billing directly on Google Apps.

This is a bit confusing, but Google Apps is the name of the product that WordPress.com and other resellers sell. Meaning that I think we should say something like this:
> You will be able to manage your  Google Apps billing directly on Google.

---
> I didn't understand your last comment. Are those scenarios that apply to this flow?

That's correct, those are all cases that could apply when cancelling Google Apps with us. Only one of the five cases will apply. It all depends on what happens with the domain and its DNS.

> do you know if there will be a difference in pricing after canceling with us and switching to manage directly with Google?

While Google pricing can be a bit of a mystery, this[ support document on Google](https://support.google.com/a/answer/1247360?hl=en) states the prices are the same ($50 a year) when using the annual plan that we sell.

**Comment by fabianapsimoes** [comment] 2016-05-23 08:46
@ranh is the change suggested by Brooke OK for you?

**Comment by ranh** [comment] 2016-05-23 13:33
👍

**Comment by BandonRandon** [comment] 2016-05-23 17:31
Now that I look back at it, I think "through Google" is clearer than "on Google". How about:

> You will be able to manage your Google Apps billing directly through Google.

cc @ranh @fabianapsimoes

**Comment by Lochlaer** [comment] 2016-05-24 20:12
Sorry, I was AFK when all this was happening! 

@BandonRandon's copy suggestions look good. It's super important to make sure that the copy reflects exactly when the user cancels: if the cancelation is within 30 days after purchase, we can issue a refund. If it's 31+ days after purchase, they will not get a refund.

**Closed** 2016-05-30 13:04 UTC
Labels: Purchases, [Type] Bug
