### ISSUE TITLE
Stats: Insights page doesn't load on direct navigation without local storage

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#22034] opened 2018-02-01 07:51 UTC
Jetpack sites dashboard in wp-admin link straight into WordPress.com Calypso Insights which fails the first time when no local storage is present

This affects all sites, not just Jetpack ones

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/insights/yoursite.com
2. Clear local storage
3. Refresh page

#### What I expected

Stats Insights to show

#### What happened instead

Blank screen, console errors:

```
TypeError: t is undefined
Stack trace:
value@https://wordpress.com/calypso/async-load-my-sites-stats-stats-insights.5bed08ca7f96b5463539.min.js:1:57325
s@https://wordpress.com/calypso/vendor.ac69b005900cda7ca7e0.min.js:63:44455
beginWork@https://wordpress.com/calypso/vendor.ac69b005900cda7ca7e0.min.js:63:48854
r@https://wordpress.com/calypso/vendor.ac69b005900cda7ca7e0.min.js:63:52822
a@https://wordpress.com/calypso/vendor.ac69b005900cda7ca7e0.min.js:63:53143
i@https://wordpress.com/calypso/vendor.ac69b005900cda7ca7e0.min.js:63:53379
L@https://wordpress.com/calypso/vendor.ac69b005900cda7ca7e0.min.js:63:56902
g@https://wordpress.com/calypso/vendor.ac69b005900cda7ca7e0.min.js:63:56639
h@https://wordpress.com/calypso/vendor.ac69b005900cda7ca7e0.min.js:63:55771
f@https://wordpress.com/calypso/vendor.ac69b005900cda7ca7e0.min.js:63:55175
enqueueSetState@https://wordpress.com/calypso/vendor.ac69b005900cda7ca7e0.min.js:63:45613
./node_modules/react/cjs/react.production.min.js/h.prototype.setState@https://wordpress.com/calypso/vendor.ac69b005900cda7ca7e0.min.js:71:1231
value/<@https://wordpress.com/calypso/build.85f1a9af56ef9d228d4c.min.js:1:80146
M/<@https://wordpress.com/calypso/stats.63fedb8b8fc96531e351.min.js:1:2675
```

#### Browser / OS version

Tested firefox, chrome, safari on macOS

#### Screenshot / Video

![stats insights](https://user-images.githubusercontent.com/128826/35667169-5a2b1c9a-0778-11e8-96c8-9c72fdfb4cea.gif)

#### Context / Source

Testing Jetpack sites: Jetpack sites have a direct link into this page so a new Jetpack site will see this error

**Comment by rachelmcr** [comment] 2018-02-01 15:03
This isn't only an issue with direct navigation; I just encountered it while navigating from the Stats Traffic tab to the Stats Insights tab on a Jetpack site. I also encountered it on a WordPress.com Simple site, so it doesn't seem to be Jetpack-specific.

**Comment by alisterscott** [comment] 2018-02-01 23:07
> This isn't only an issue with direct navigation; I just encountered it while navigating from the Stats Traffic tab to the Stats Insights tab on a Jetpack site. I also encountered it on a WordPress.com Simple site, so it doesn't seem to be Jetpack-specific.

Thanks, yes I tested it on simple site too as per the GIF, but I've tried to make that clearer in my report and I removed the Jetpack label in case this was misleading.

**Comment by unDemian** [comment] 2018-03-06 13:15
This cannot be reproduced anymore, I think we can close this.

**Comment by timmyc** [comment] 2018-06-04 20:03
Looking into old Stats bugs as part of HACK week and I'm not able to reproduce this anymore. Closing out.

**Closed by timmyc** 2018-06-04 20:03 UTC
Labels: Stats, [Pri] High, [Type] Bug
