### ISSUE TITLE
Payment: "Submitting Payment" step of a WP-premium renew throws a JS error

### ISSUE THREAD

**Issue by TooTallNate** [Automattic/wp-calypso#3551] opened 2016-02-25 00:33 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/checkout/forest.beer (more likely _any_ checkout page, not specific to this blog).
2. Hit the "Renew" button (this blog has WP Premium and was due for a renew)
3. "Submitting Payment" step never finishes in the UI.
4. Stuck at this point…

#### What I expected

The "Submitting Payment" step would complete and the UI would show a "success" status and/or redirect back to the Plans page.

#### What happened instead

The "Submitting Payment" notification in the corner never disappears, and a JS error is exposed in the Web Console (see screenshot below).

#### Browser / OS version

Chrome / OS X.

#### Screenshot / Video

"Submitting Payment" step (it's stuck at this point)

![](https://cloudup.com/cWY2KEpJ798+)

JS Error:

![](https://cloudup.com/cLcdzrSH9Ad+)

**Comment by gziolo** [comment] 2016-03-10 10:52
I couldn't reproduce this one

**Comment by gziolo** [comment] 2016-03-14 08:26
@peterbutler Can you try to reproduce this one and close if it works properly also for you?

**Comment by gziolo** [comment] 2016-03-22 10:15
Let's close it as we couldn't reproduce.

**Closed** 2016-03-22 10:15 UTC
Labels: Checkout, [Type] Bug
