### ISSUE TITLE
List Block: Editing a copy of a link applies changes to the first link, not the copy

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#65836] opened 2022-07-21 11:39 UTC
### Quick summary

When you try to edit a link on a copied list item, it updates the previous item's link.

### Steps to reproduce

1. Using the List block, add one list item with a link
2. Copy that first item and create a second one with it
3. Edit the link on the second item

### What you expected to happen

To edit the link on the second item.

### What actually happened

The link changes on the first item instead.

### Context

Here's a screenrecording:

![editing-links-on-list](https://user-images.githubusercontent.com/16104522/180204530-f0cb6c98-88ca-4420-a306-85f5460fe29f.gif)

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

It works the second time you edit the link.

**Comment by cuemarie** [comment] 2022-07-28 17:20
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- Thank you for the clear report! This issue was consistently reproducable on Simple, AT, and Self-Hosted test sites. 
- Copying and pasting a link in a list, then editing the new link, applied the changes to the original copied link instead.  This happened whether or not the link was pasted as a second list item, or a third. 
- As noted in the workaround section, editing the link a second time applied changes correctly - however, the original link remains changed as well, so it's necessary to correct that as well.

**Self-Hosted Test:** (same as S & AT)

![Screen Capture on 2022-07-28 at 10-07-42](https://user-images.githubusercontent.com/27249804/181597450-8d1935bb-db54-4407-9725-51e4819ed993.gif)

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Reported in Gutenberg Repo: https://github.com/WordPress/gutenberg/issues/42784

**Comment by youbrokesomething** [comment] 2022-09-29 16:46
FYI for those trying to track this issue on the core side, [this is the current open issue](https://github.com/WordPress/gutenberg/issues/41771).

**Comment by getdave** [comment] 2022-11-09 23:59
Needs re-test as the block now uses inner blocks for individual items and not rich text.

**Comment by getdave** [comment] 2022-11-10 00:03
https://user-images.githubusercontent.com/444434/200967895-f13edd08-c5f2-430e-bc77-cf381915aef5.mp4

Re-tested with the List View v2 block and the problem no longer manifests due to the use of inner blocks.

**Closed as completed by getdave** 2022-11-10 00:03 UTC
Labels: Bug, [Pri] Normal, Blocks, Triaged
