### ISSUE TITLE
Feature request: Set up a theme demo site on Atomic

### ISSUE THREAD

**Issue by alaczek** [Automattic/wp-calypso#66737] opened 2022-08-19 04:35 UTC
So far all the themes in the Theme Showcase, both premium and free, are set up as simple sites. Now that we're looking at adding themes featuring WooCommerce (and possibly other plugins in the future) to the theme showcase, we need to figure out if using an Atomic demo site will have any adverse/unexpected effects. 

My understanding of the importance of where the demo site is setup (and it's URL in particualr) is limited, so it's possible there won't be much to do here, besides testing and making sure the theme works properly in theme showcase. We currently have one premium theme in the works - [Thriving Artist](https://thrivingartistdemo.wpcomstaging.com) - that could serve as a test subject. 

A few things to investigate:
* Atomic sites have an URL in wpcomstaging.com subdomain. Some of our demos already use alternative URL structure (eg. merakithemedemo.wordpress.com, because merakidemo.wordpress.com was taken). The demo site creation checklist(PNEWy-e4U-p2) has a contigency for this that requires editing two files to account for that (check at the very bottom of the doc). Will it work with a custom URL, for example thrivingartistdemo.wpcomstaging.com?
* Theme demo sites have a `theme-demo-site` sticker and a blue flag that makes them protected. Is this applicable/relevant when the demo site is Atomic? 
* Demo sites typically have an activation bar on top. Exploration is needed to determine if it's possible and how hard it would be to display the bar on Atomic demo site. It would be also good to check stats on the actual usage of this feature, as customers are able to access demo site preview in calypso as well.

**Comment by valterlorran** [comment] 2022-08-23 12:20
Hey! I'm adding the information that I'm gathering here: paYKcK-20V-p2

**Comment by valterlorran** [comment] 2022-08-24 19:20
I noticed that the `stylesheet` option for the [Thriving Artist](https://thrivingartistdemo.wpcomstaging.com/) is defined as `thriving-artist`, but it should be `premium/thriving-artist`. This will cause problems when running the command to generate the headstart annotation because it uses this option to locate the theme's directory.

**Comment by alaczek** [comment] 2022-08-26 06:24
Where exactly are you seeing that option?

**Comment by valterlorran** [comment] 2022-08-29 12:25
Through the command line from my sandbox.

**Comment by alaczek** [comment] 2022-08-30 00:02
Hi @valterlorran could you clarify what command? I'm not seeing anything relevant in the theme files.

**Comment by valterlorran** [comment] 2022-08-30 13:19
Yes, I ran `wp option get stylesheet --url=thrivingartistdemo.wpcomstaging.com`

**Comment by valterlorran** [comment] 2022-09-16 18:05
@alaczek we won't be able to reproduce the exact behavior of the demo bar on atomic sites. You can understand more about it in this discussion here: p1663273197375359-slack-C0Q664T29

**Comment by valterlorran** [comment] 2022-10-07 13:24
Hey @alaczek @iamtakashi. We had a slight change of plans, and the demo bar will be a [plugin](https://github.com/Automattic/theme-demo-bar-plugin). So we'll need to update the guide to launching atomic demo sites, adding a new step to install the [plugin](https://github.com/Automattic/theme-demo-bar-plugin).

p1664983518636999-slack-C0Q664T29
p1665063660862579-slack-C0Q664T29

The demo bar is almost complete. I only need to fix the currency, which is only in USD.

**Comment by valterlorran** [comment] 2022-10-18 20:03
Closing this as we merged the last part of the code to add the demo bar on atomic sites. D89981-code

**Closed as completed by valterlorran** 2022-10-18 20:03 UTC
