### ISSUE TITLE
Site Editor: Make sure theme styles and Global Styles work appropriately on both Atomic and Simple

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#54459] opened 2021-07-12 17:15 UTC
When a site moves to Atomic, not all styles work as expected.

- The site loses all the styles, reverting to the browser’s default CSS and fonts.
This might be caused by the `wp_global_styles` CPT not being transferred, or by the generated CSS not being enqueued appropriately or in the correct order (e.g. messing up the CSS3 variables).

- The color palette in Global Styles reverts to the Gutenberg default (no more custom colors, no more theme palette).

See also p58i-aCg-p2#comment-50940

EDIT: Global Styles has some issues on Simple as well!

### Main Tasks
- [x] ~https://github.com/WordPress/gutenberg/pull/34147~

### Other Tasks
- [x] 738-gh-Automattic/wpcomsh
- [x] ~https://github.com/Automattic/page-optimize/pull/66~
- [x] ~https://github.com/WordPress/gutenberg/pull/34188~
- [x] https://github.com/Automattic/themes/pull/4446
- [x] https://github.com/Automattic/themes/pull/4439
- [x] https://github.com/WordPress/gutenberg/pull/34293

**Comment by jeyip** [comment] 2021-07-14 22:38
## Steps to Reproduce

* Create an FSE enabled site ( [Link](https://horizon.wordpress.com/new?flags=gutenboarding/site-editor) )
* Navigate to the site editor
* Modify global styles like text color, font size, and line height
* Save the changes
* Purchase a business plan
* Install the "Hello Dolly" plugin to take the site atomic
* Navigate to the site editor again and verify that some global styles aren't being applied correctly
* **Note:** I'm having trouble reproducing issues where the color palette isn't transferred.

Video: Will upload soon

## Technical Details
* Global styles work as expected on dotcom simple sites and on the dockerized WordPress instance for local Gutenberg development.
* Global styles on atomic, however, don't behave as expected. I have confirmed one issue so far (Problem 1). I haven't completely confirmed nor completely disproven the second issue (Problem 2).
* **Problem 1:** For atomic sites, global styles are being overridden by css resets from Gutenberg 
    * It appears as if recent changes to how css resets are enqueued might be the cause ( [Link 1](https://github.com/WordPress/gutenberg/pull/30034) and [Link 2](https://github.com/WordPress/gutenberg/blob/5f5b838a315c8044b17781b87b4c1f6cf4fe8a78/packages/block-library/src/reset.scss#L8-L23) )

<img width="1280" alt="Screen Shot 2021-07-14 at 3 57 37 PM" src="https://user-images.githubusercontent.com/5414230/125703571-cd42a380-6a30-486d-8e3a-c1855fa8fa29.png">

* **Problem 2:** Global styles CPT names contain theme paths which aren't updated during an atomic transfer. These theme paths may need to be updated depending on how global styles are retrieved.
    * From what I can tell, global styles are carried over and evaluated correctly after an atomic transfer, as long as the overriding styles from Problem 1 are removed.

## Proposed Fixes
- Potential fix https://github.com/WordPress/gutenberg/pull/33522
- Alternative approaches p1626716595094500-slack-CHN6J22MP

**Comment by jeyip** [comment] 2021-07-21 19:03
Potential fix:
https://github.com/WordPress/gutenberg/pull/33522

**Comment by jeyip** [comment] 2021-08-18 17:22
## Status Update
- We're seeing some oddities with block-specific global styles on atomic + simple sites. Some blocks have their global styles overridden. More context [here](https://github.com/Automattic/themes/issues/4435).

**Comment by jeyip** [comment] 2021-08-18 22:48
## Status Update

- We [hotfixed](https://github.com/Automattic/page-optimize/pull/66) global styles on atomic sites earlier this week. Most user customized global styles should be loading properly now. The [core Gutenberg patch](https://github.com/WordPress/gutenberg/pull/33522) which implements the same code from the hotfix is still awaiting feedback.
- Grant has [a PR](https://github.com/WordPress/gutenberg/pull/34147) in progress to fix ensure that inline global styles are loaded _after_ theme styles on the frontend. This ensures that styles with competing specificities prefer global styles user customizations.
- We're investigating block-specific global styling problems [alongside the themes team](p1629226103080900-slack-C029FM1EH) for the button block, cover block, and site title block. These, to me, seem like relatively minor problems, since **all other block styling appears to be working**.

**Comment by jeyip** [comment] 2021-08-25 11:19
## Status Update

There's one more outstanding PR to address whereby block-level global styles are displaying color options in an unexpected way. https://github.com/WordPress/gutenberg/pull/34293

Once resolved, I believe we can close out this ticket.

**Closed as completed** 2021-08-27 18:44 UTC
Labels: [Pri] BLOCKER, [Status] In Progress, Task, [Goal] Full Site Editing, [Team] Cylon

**Comment by Copons** [comment] 2021-08-30 09:42
Astounding job here @jeyip! ✨
