### ISSUE TITLE
Editor: Gallery images not displaying correctly for Jetpack site

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#4601] opened 2016-04-07 22:49 UTC
At https://wordpress.com/post/nylen.io::blog/87, note that the images in the gallery do not display correctly:

![image](https://cloud.githubusercontent.com/assets/227022/14369224/d6518ef4-fce8-11e5-86c2-fc46298ee88a.png)

This is because of a mixed content error:

> Mixed Content: The page at 'https://wpcomwidgets.com/render/' was loaded over HTTPS, but requested an insecure image 'http://i0.wp.com/nylen.io/blog/wp-content/uploads/2016/04/DSCN0791.jpg?resize=768%2C576'. This request has been blocked; the content must be served over HTTPS.

The post itself loads fine - http://nylen.io/blog/2016/04/04/sf-golden-gate-bridge-skyline-etc/

Perhaps relevant:
- This is a Jetpack site that does not use HTTPS
- The site is installed into a subfolder of the nylen.io domain

**Comment by aduth** [comment] 2016-04-08 12:03
Which browser is this, and have you changed security settings? Typically mixed content has been permitted for [passive content](https://developer.mozilla.org/en-US/docs/Security/Mixed_content#Mixed_passivedisplay_content), unless the browser is configured to have much higher security settings.

**Comment by nylen** [comment] 2016-04-09 05:04
Chrome v49 on OS X - I didn't change any security settings from the defaults.

**Comment by aduth** [comment] 2016-04-09 15:36
Not running a Chrome variant (Chromium, Canary)? Running with any flags from the command line? Reproducible? Is there a shield icon that would allow you to enable and/or change the default setting for mixed content?

My understanding is that the default for Chrome is to _warn_, but not _block_ mixed passive content (images): https://security.googleblog.com/2015/10/simplifying-page-security-icon-in-chrome.html

Previous discussion: 11436-gh-calypso-pre-oss

**Comment by nylen** [comment] 2016-04-11 23:18
Stock, regular stable channel Chrome; reproducible every time - I use a couple of command line flags related to proxy usage, but just confirmed with a fresh browser profile and no flags.

Passive mixed content loaded from the Calypso page itself displays warnings, but is not blocked:

> Mixed Content: The page at 'https://wpcalypso.wordpress.com/post/nylen.io::blog/87' was loaded over HTTPS, but requested an insecure image 'http://nylen.io/blog/wp-content/uploads/2016/04/sf-golden-gate-bridge-1200x700.png'. This content should also be served over HTTPS.

Passive mixed content loaded from the https://wpcomwidgets.com/render/ iframe is blocked as described above.  Given the additional info you posted, I'm not sure why that would be the case.

**Comment by designsimply** [comment] 2016-06-27 19:44
Tested and confirmed that gallery images do not show up in the WordPress.com editor for a non-HTTPS Jetpack site. 

Notes: in my case, the gallery appears to be missing completely and I don't see any broken image placeholders like you can see in @nylen's screenshot above, however, the featured image at the top of the editor seems to be working fine.

![screen shot 2016-06-28 at tue jun 28 7 28 36 am](https://cloud.githubusercontent.com/assets/1119271/16393150/ac39ab00-3d03-11e6-942b-5c2ff5c1b1f7.png)
<sup>Seen at https://wordpress.com/post/designsimply.com/2022 using Chrome 51.0.2704.84 on Mac OS X 10.11.5 on production (unproxied).</sup>

Console warnings/errors:

```
Mixed Content: The page at 'https://wordpress.com/post/designsimply.com/2022' was loaded over HTTPS, but requested an insecure image 'http://designsimply.com/wp-content/uploads/GOPR1391.jpg?w=2924'. This content should also be served over HTTPS.

2022:1 Mixed Content: The page at 'https://wordpress.com/post/designsimply.com/2022' was loaded over HTTPS, but requested an insecure image 'http://designsimply.com/wp-content/uploads/GOPR1391.jpg?w=900'. This content should also be served over HTTPS.

build-production.343c0fd….min.js:20 Mixed Content: The page at 'https://wordpress.com/post/designsimply.com/2022' was loaded over HTTPS, but requested an insecure image 'http://designsimply.com/wp-content/uploads/GOPR1391.jpg?w=2924'. This content should also be served over HTTPS.

build-production.343c0fd….min.js:20 Mixed Content: The page at 'https://wordpress.com/post/designsimply.com/2022' was loaded over HTTPS, but requested an insecure image 'http://designsimply.com/wp-content/uploads/GOPR1391.jpg?w=900'. This content should also be served over HTTPS.

Failed to parse SourceMap: https://widgets.wp.com/notifications/build.min.js.map?6a0b66a8f2bf309ea22cb7a194121f6d
```

Here's how that post looks live on the site showing the gallery above the content in the body of the post:

![screen shot 2016-06-28 at tue jun 28 7 29 20 am](https://cloud.githubusercontent.com/assets/1119271/16393085/6585754a-3d03-11e6-9dce-e41108195249.png)
<sup>Seen at http://designsimply.com/2014/09/20/skydiving-in-utah/ using Chrome 51.0.2704.84 on Mac OS X 10.11.5 on production (unproxied).</sup>

Here's how the same post looks in `wp-admin` with a gallery preview showing as expected: 

![screen shot 2016-06-28 at tue jun 28 7 34 48 am](https://cloud.githubusercontent.com/assets/1119271/16393089/70290b06-3d03-11e6-82f0-e500145816a1.png)
<sup>Seen at http://designsimply.com/wp-admin/post.php?post=2022&action=edit using Chrome 51.0.2704.84 on Mac OS X 10.11.5</sup>

**Comment by lancewillett** [comment] 2016-10-18 17:54
Marking as high priority as we are trying to reduce Jetpack / WP.com UX differences, and galleries should display normally for Jetpack sites in Calypso.

**Comment by lancewillett** [comment] 2016-11-07 19:42
Re-testing this today during a bug scrub, using a self-hosted test site on Dreamhost with Jetpack 4.3.2 (browser: Mac-n-Chrome).

I'm able to repeat the missing images — and related network HTTP errors, visible in console — on a Jetpack site that doesn't have HTTPS enabled on its primary domain. For a Jetpack site **with** HTTPS on, it doesn't happen.

Here's a visual record.

First, in Calypso — created a new post and started uploading 4 new images.
![screen shot 2016-11-07 at 12 27 49](https://cloud.githubusercontent.com/assets/66797/20072620/4f3c6d20-a4e6-11e6-885a-6fc0b8e06d07.png)

I got an error uploading the files (it was a problem with RAM on my VPS).
![screen shot 2016-11-07 at 12 27 55](https://cloud.githubusercontent.com/assets/66797/20072791/1016e7d2-a4e7-11e6-88d5-5648c2a17f39.png)

Tried uploading again; the images are visible as thumbnails in the media library.
![screen shot 2016-11-07 at 12 30 09](https://cloud.githubusercontent.com/assets/66797/20072817/2a550a34-a4e7-11e6-9462-047799196a5c.png)

Next, started the gallery creation steps — and images are not working now (except one seems to, which uploaded earlier).
![screen shot 2016-11-07 at 12 30 38](https://cloud.githubusercontent.com/assets/66797/20072824/355acc3e-a4e7-11e6-9d6c-a9915d2decbc.png)

Inserting the gallery in the post.
![screen shot 2016-11-07 at 12 30 51](https://cloud.githubusercontent.com/assets/66797/20072845/4922019c-a4e7-11e6-95a7-4810858fd88c.png)

Viewing console errors
![screen shot 2016-11-07 at 12 31 06](https://cloud.githubusercontent.com/assets/66797/20072856/52c9dcf6-a4e7-11e6-8a79-7bf313a2d424.png)

HTML view of the same post, for reference.
![screen shot 2016-11-07 at 12 34 05](https://cloud.githubusercontent.com/assets/66797/20072899/7c443950-a4e7-11e6-80ca-2954f95987d5.png)

This is the same site, media library in wp-admin:
![screen shot 2016-11-07 at 12 31 13](https://cloud.githubusercontent.com/assets/66797/20072867/5d8d4a10-a4e7-11e6-9ac5-ad3b6a361a95.png)

Published the post.
![screen shot 2016-11-07 at 12 33 33](https://cloud.githubusercontent.com/assets/66797/20072876/65aa8fe6-a4e7-11e6-855d-420ec2e9118f.png)

Front-end, published post and images look fine.
![screen shot 2016-11-07 at 12 33 40](https://cloud.githubusercontent.com/assets/66797/20072891/70218e8e-a4e7-11e6-87e3-64a57a097305.png)

<hr>

Here's a second try, this time with a Jetpack site with HTTPS support.

![screen shot 2016-11-07 at 12 36 16](https://cloud.githubusercontent.com/assets/66797/20072922/8f2ea82a-a4e7-11e6-9f60-f8d1e11ac0a6.png)
![screen shot 2016-11-07 at 12 36 29](https://cloud.githubusercontent.com/assets/66797/20072921/8f2baddc-a4e7-11e6-87fa-6f43dc205a8d.png)
![screen shot 2016-11-07 at 12 36 36](https://cloud.githubusercontent.com/assets/66797/20072920/8f2b3488-a4e7-11e6-8262-77abd692bb0e.png)
![screen shot 2016-11-07 at 12 36 45](https://cloud.githubusercontent.com/assets/66797/20072925/8f30225e-a4e7-11e6-97c3-2e1750785388.png)
![screen shot 2016-11-07 at 12 36 59](https://cloud.githubusercontent.com/assets/66797/20072923/8f2f488e-a4e7-11e6-832a-14548d6e2f6a.png)
![screen shot 2016-11-07 at 12 42 09](https://cloud.githubusercontent.com/assets/66797/20072941/9db0ede0-a4e7-11e6-949b-8dfacdd5b537.png)

**Comment by aduth** [comment] 2016-11-07 19:53
@lancewillett : Do you have Photon enabled for your site?

Related to the comment I just left at https://github.com/Automattic/wp-calypso/issues/313#issuecomment-258942397, if we were to start forcing Photon for the images, this issue would resolve itself, since Photon is served over HTTPS.

If we don't use Photon or at least choose to respect the site's Photon preference, there's nothing we can do to resolve mixed content errors, since those images are loaded from the site directly. 

(Still noting as mentioned above that not all browsers and browser configurations are as strict with mixed content on images, since images are considered [passive mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content)).

**Comment by lancewillett** [comment] 2016-11-07 20:59
@aduth Yes, Photon is on for both the Jetpack sites I tested with.

**Comment by lancewillett** [comment] 2016-11-07 21:01
Side note: I wonder how much we could encourage hosts and site owners to switch to full SSL — I've noticed it's gotten much easier lately to set up, especially with Let's Encrypt. Maybe we can require it in the future with nags in wp-admin and Calypso UI.

**Comment by aduth** [comment] 2016-11-07 21:01
Oh I see now that the markup uses Photon, but as HTTP. I wonder if that's something we need to adjust in Jetpack? Seems like we should always be using HTTPS. In the worst case, we might be able to forcefully override it from Calypso.

**Comment by aduth** [comment] 2016-11-07 21:03
I expect that browsers will only become more strict over time with regards to mixed content, so it's probably good to anticipate this and perhaps provide a graceful fallback (shortcode text or maybe a placeholder) for sites which we determine to not be HTTPS.

**Comment by aduth** [comment] 2016-11-07 21:20
Marking this as fixed pending https://github.com/Automattic/jetpack/pull/5534 , though that still requires that Photon be enabled for the Jetpack site. We will still want to pursue a good fallback for sites without Photon enabled.

**Comment by lancewillett** [comment] 2016-11-07 21:32
Quick notes after testing https://github.com/Automattic/jetpack/pull/5534 fix — using my same non-HTTP Jetpack site. Mac-n-Chrome. Jetpack 4.3.2 with `update/photon-https` branch.

Images appear perfectly in gallery preview, in Calypso editor. w00t!
![screen shot 2016-11-07 at 14 24 28](https://cloud.githubusercontent.com/assets/66797/20076739/d29d4242-a4f6-11e6-892d-585d77650920.png)

I made another test post, worked well — a few mixed content warnings but they didn't block the images from appearing
![screen shot 2016-11-07 at 14 28 31](https://cloud.githubusercontent.com/assets/66797/20076755/e1092a30-a4f6-11e6-9aa2-c4d32a306799.png)
![screen shot 2016-11-07 at 14 30 16](https://cloud.githubusercontent.com/assets/66797/20076756/e11b5502-a4f6-11e6-9a21-34778b444bfa.png)

**Closed** 2016-11-08 03:28 UTC
Labels: Editor, Jetpack, [Pri] High, [Type] Bug

**Comment by aduth** [comment] 2016-11-08 15:01
Created #9221 for tracking improved handling for Jetpack sites with Photon disabled.
