### ISSUE TITLE
Domain Mapping supposedly allowed with a Free plan during signup

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#17568] opened 2017-08-28 20:02 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start as a DWPO user (meaning a new user that has to buy a paid plan to have a custom domain on their site)
2. Select domain mapping on the domains step
3. Get presented with the Plans selection page.
4. Choose Free.
5. Proceed to Checkout.

#### What I expected
Domain Mappings are also subject to DWPO, so they should _not_ be allowed with a Free plan. Unless we changed that, but in that case, this is still a bug.
Either the Free plan should be respected or not offered at all for Domain Mappings.

#### What happened instead
Premium plan was auto-added to cart, because of DWPO rules.

#### Context / Source
#manual-testing

**Comment by rachelmcr** [comment] 2017-12-13 15:05
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/11948.

**Closed by rachelmcr** 2017-12-13 15:05 UTC
Labels: Domains, NUX, Plans, [Type] Bug
