### ISSUE TITLE
Gutenberg: Attempt a v6.1.1 update [3]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34386] opened 2019-07-01 21:57 UTC
Let's update the Gutenberg Plugin for Simple and Atomic sites to v6.1.x

- [x] Test the 6.1 Gutenberg RC for both Simple and Jetpack Sites (7/8) and make it available on horizon https://github.com/WordPress/gutenberg/releases/tag/
  - D30287-code
  - D30283-code
- [x] Test the 6.1 Gutenberg plugin for both Simple and Jetpack Sites (7/10)
  - D30309-code
  - D30314-code
- [x] Update patch for 6.1.1 instead of 6.1.0 https://github.com/WordPress/gutenberg/releases/tag/v6.1.1
  - D30392-code
  - D30412-code
  - D30393-code
- [x] Disable Experimental Section in the Customizer - Widget Blocks (Experimental) 
  - D30393-code
- [x] Reserve testing time in the Calypso queue, land 6.1.1 phab diff, then land E2E updates https://github.com/Automattic/wp-calypso/pull/34097. E2E Master may go red for a build.
- [x] Report and help fix related issues in the core project / Jetpack / wpcom
- [x] If no issues are found attempt to deploy the wpcom diff for Simple Sites
- [x] Fix Switch to Classic option in dropdown ( https://github.com/Automattic/wp-calypso/pull/34669 D30460-code )
- [x] Fix E2E tests and re-enable the Gutenberg suites (https://github.com/Automattic/wp-calypso/pull/34668)
- [x] If simple sites are stable, file a related request to update the atomic Gutenberg plugin version.
  - pMz3w-a65-p2

See also steps in PCYsg-m14-p2

**Comment by vindl** [comment] 2019-07-05 14:25
RC should be ready on Monday, that's when we can start working on this. Let's try to use the new script available in D29862-code.

**Comment by vindl** [comment] 2019-07-09 13:30
So far it seems to be working fine with latest Jetpack version, and I'm noticing the following console error on Dotcom:

```
Uncaught TypeError: Cannot set property attributes of #<Object> which has only a getter
    at index.js?m=1562670240h&ver=1562670240:55
    at index.js?m=1562670238h&ver=1562670238:1
    at index.js?m=1562670199h&ver=1562670199:2
    at Array.map (<anonymous>)
    at ne (index.js?m=1562670199h&ver=1562670199:2)
    at O (editor-beta.js?m=1562652733h&ver=wpcom:12)
    at Module.<anonymous> (editor-beta.js?m=1562652733h&ver=wpcom:24)
    at i (editor-beta.js?m=1562652733h&ver=wpcom:1)
    at Object.<anonymous> (editor-beta.js?m=1562652733h&ver=wpcom:24)
    at i (editor-beta.js?m=1562652733h&ver=wpcom:1)
```

Not sure what or if any functionality is impacted by this based on smoke testing.

**Comment by gwwar** [comment] 2019-07-09 22:38
Browser stops on this error breakpoint:

<img width="820" alt="Screen Shot 2019-07-09 at 3 34 02 PM" src="https://user-images.githubusercontent.com/1270189/60927570-3cf82900-a25f-11e9-91ad-b42e1b3b47be.png">

Which I think maps back to https://github.com/WordPress/gutenberg/blob/5cb8b8f3a025e4ecf24b9b3ec31988b2c7b02d5c/packages/block-editor/src/hooks/custom-class-name.js#L155

**Comment by gwwar** [comment] 2019-07-09 23:19
I added a reminder task to land https://github.com/Automattic/wp-calypso/pull/34097 if this makes it in

**Comment by youknowriad** [comment] 2019-07-10 08:44
@talldan Could this be related to the "deprecated" filter we're applying now?

**Comment by vindl** [comment] 2019-07-10 13:32
> This is likely from the missing Jetpack Tiled Gallery block

Based on my testing it also seems to be caused by some interplay with Jetpack. While testing this on a self-hosted site with Jetpack plugin I'm seeing the same error, so it's not Dotcom specific. Deactivating Jetpack on said site removes the console error.

**Comment by youknowriad** [comment] 2019-07-11 09:34
Is anyone able to confirm that this PR fixes the issue? https://github.com/WordPress/gutenberg/pull/16518

We've had trouble reproducing but we expect this PR to fix the problem.

**Comment by gwwar** [comment] 2019-07-11 15:45
@youknowriad we can try and verify today with Jetpack and that branch

**Comment by gwwar** [comment] 2019-07-11 17:32
@youknowriad https://github.com/WordPress/gutenberg/pull/16518  @mattwiebe confirmed that 💯 fixes the Jetpack Tiled Gallery. He had trouble reproducing the original WSOD, but we'll be able to repro that pretty quickly on horizon if that's still the case.

**Comment by vindl** [comment] 2019-07-11 21:08
@youknowriad @gwwar after some hurdles with the setup, I finally managed to reproduce this with my local Jetpack install (latest master) running Gutenberg 6.1.0, and verified that https://github.com/WordPress/gutenberg/pull/16518 fixies the issue.

**Comment by gwwar** [comment] 2019-07-11 21:46
As @vindl found, the missing piece for folks that had trouble reproducing the WSOD is having an active Jetpack connection.

**Comment by vindl** [comment] 2019-07-15 20:15
Dotcom diff and Calypso E2E tests have been merged. This leaves us with the Atomic update.

**Comment by vindl** [comment] 2019-07-16 16:27
Closing since all of the above tasks have been completed. For reference, this issue took up ~7 points to complete.

**Closed by vindl** 2019-07-16 16:27 UTC
Labels: [Goal] Gutenberg, [Type] Task
