### ISSUE TITLE
Sites: Jetpack site preview always uses HTTPS 

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#9654] opened 2016-11-27 20:04 UTC
#### Steps to reproduce

1. Starting with a Jetpack site connected to WordPress.com. That site must **not** be using HTTPS.
2. Go to wordpress.com and click on My Sites
3. Select the Jetpack site
4. Click the site title to bring up the site preview

#### What I expected
I expected to see the site preview without any errors.

#### What happened instead
The preview loads an HTTPS version of the site, which may not be available if the site doesn't use HTTPS.

**Comment by rralian** [comment] 2017-01-24 17:31
Just a note, this won't be an issue for Automated Transfer sites, because we'll be using letsencrypt to get SSL certs for all of these sites.

**Comment by lsinger** [comment] 2017-06-21 10:45
FWIW, we'll need to fallback to opening the site in a new tab afaik.

**Comment by lancewillett** [comment] 2017-07-13 16:20
As discussed in a call with JPOP ( cc @beaulebens ) -- we can't force everyone using Jetpack to have SSL turned on. Due to many factors with hosts, costs of buying a certificate, and education around it. While we'll continue to suggest and nudge hosts we work with to go HTTPS 100%, we'll need to have a workaround for new tab/window in place probably permanently for those types of sites.

So to close this one out — let's check for SSL capability. If it's good to go — everything should stay in the Calypso environment. Yet if it's not available on the target Jetpack domain, open preview in a new tab/window.

**Comment by rralian** [comment] 2017-07-16 16:14
FWIW all Atomic sites have SSL, so we could target based on that. But I agree that it would be best to test for SSL capability and keep previews inside calypso for all who can support it.

**Comment by lancewillett** [comment] 2017-07-25 18:04
@marekhrabe Could you add this one to your list to check + test once preview changes are ready for Jetpack sites?

**Comment by marekhrabe** [comment] 2017-07-26 12:01
@lancewillett sure, it's on our radar! thanks for assigning me :)

**Comment by lancewillett** [comment] 2017-09-04 21:20
I think this one is working as intended now.

I see this message when I click View Site for a non-HTTPS Jetpack site:

<img width="997" alt="screen shot 2017-09-04 at 14 18 59" src="https://user-images.githubusercontent.com/66797/30038661-03ce14c8-917c-11e7-9dbb-11e613d9e9df.png">

And the "Open" link works as expected.

From the https://github.com/Automattic/wp-calypso/blob/master/client/components/web-preview/README.md

>  Bear in mind that not all front-end links are previewable — Jetpack sites, for instance, may not be supported for a number of reasons, including absent HTTPS support.

**Closed by lancewillett** 2017-09-04 21:20 UTC
Labels: Jetpack, Sites, [Type] Bug
