### ISSUE TITLE
Cover block: Content misalignment for Free & Personal plan sites

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#51670] opened 2021-04-04 08:54 UTC
### Steps to reproduce the behavior

1. Make sure your site has a Personal plan
2. Create a cover block and check if the content is center aligned

---

1. Create a new site on WP.com with a free plan.
2. Add a cover block to a page.
3. Change the background colour in the placeholder.
4. Start typing and notice that the text defaults to right-align.

#### What I expected to happen

To have the content centered

#### What actually happened

The content is shifted to the right because of an extra element in there.

### Context

3878183-zen / asked in Slack as well

#### Browser / OS version

Chrome / MacOS

#### Is this specific to the applied theme? Which one?

Tested with a few(Morden, Blank Canvas, Hever)

#### Does this happen on simple or atomic sites or both?

Simple/Personal plan to be more specific

#### Is there any console output or error text?

No, but we have an extra element that forces this layout

![image](https://user-images.githubusercontent.com/6737345/113503749-65987a00-953c-11eb-9f50-e2434e608399.png)

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It affects all the Personal plan sites.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Added above

**Comment by inaikem** [comment] 2021-04-04 09:14
Confirmed: I was able to replicate on WPcom Free and Personal sites. Unable to replicate on Premium, or Atomic sites.

The bug is apparent after an image has been set: https://d.pr/i/jl6yTp

**Comment by Sandkorner** [comment] 2021-04-04 10:25
I had a few cases already as well. Both Cover Block text forced to the right from the shown extra element. Personal plans on both sites.

**Comment by retnonindya** [comment] 2021-04-05 00:44
Confirmed. I tested on my Personal test sites and I able to replicate it.

**Comment by yashitamittal11** [comment] 2021-04-05 01:25
Another one - #3878569-zen

**Comment by Nic-Sevic** [comment] 2021-04-05 11:07
A note to clarify: this appears to be only happening in the editor. It appears to display as expected on live site:
https://d.pr/i/sQWuDA

**Comment by simison** [comment] 2021-04-05 12:42
cc @WunderBart @fullofcaffeine any recent Gutenberg upgrades affecting this?

cc @Automattic/view-engineering  since this is happening only on free & personal sites, could this be due to upgrade nudges somehow?

**Comment by cpapazoglou** [comment] 2021-04-05 16:31
This is the conflicting html `<div class="paid-block-media-placeholder"><div class="components-drop-zone"></div></div>`

**Comment by pauloeaquino** [comment] 2021-04-07 00:52
Came across another issue in #3885255-zen

**Comment by zdenys** [comment] 2021-04-08 16:22
28881347-hc

**Comment by ianstewart** [comment] 2021-04-08 19:36
Updated the title and testing instructions as this does not appear to be limited to a personal plan but seems to be reproduce-able with new free plan sites.

**Comment by ianstewart** [comment] 2021-04-08 20:07
Tested with new sites and older themes like Twenty Nineteen and Penscratch 2. Appears to be a theme independent issue. 

Also is affecting default content in new sites like this restaurant-focused design.

![image](https://user-images.githubusercontent.com/545779/114089716-17f17980-987c-11eb-86e5-a72d28f06298.png)

**Comment by donalirl** [comment] 2021-04-09 02:12
Seen in #3892002-zen

**Comment by ramonjd** [comment] 2021-04-09 05:12
It looks to be the `paid-block-media-placeholder` element in [paid-blocks](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/media-placeholder.js#L56)

<img width="1236" alt="Screen Shot 2021-04-09 at 3 07 15 pm" src="https://user-images.githubusercontent.com/6458278/114131208-8e0de300-9945-11eb-9a72-b6a5ef301d6d.png">

Removing [the width](https://github.com/Automattic/jetpack/blob/96c05f153090eb012a38078002f2e811dd36eb7f/projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/editor.scss) fixes it, but maybe it needs that width to work. If that's the case, maybe we can conditionally apply the width to the placeholder (?)

cc @retrofox

**Comment by roo2** [comment] 2021-04-09 05:14
it looks like this was introduced [in this gutenberg PR](https://github.com/WordPress/gutenberg/pull/29813), I pinged the authors there

**Comment by jasmussen** [comment] 2021-04-09 05:27
Hi @roo2, help me understand how this is a core gutenberg issue. I have indeed managed to reproduce on a WordPress.com sign-in using a personal plan, and I do see that the "paid-block-media-placeholder" is present and causing the misalignment. However that div is not part of the core offering, so it seems like something being added through a WordPress.com filter. As it is, I'm unsure how we'd fix this in the core plugin.

**Comment by roo2** [comment] 2021-04-09 05:52
ahh ok, so it looks like https://github.com/WordPress/gutenberg/pull/29813 introduced a drop zone for drag and dropping an image background, but jetpack is intercepting this drop zone and wrapping it in the `paid-block-media-placeholder` element for free and personal plans. This `paid-block-media-placeholder` element has `width: 100%` and is causing the alignment 
issue

**Comment by roo2** [comment] 2021-04-09 08:02
raised this jetpack issue https://github.com/Automattic/jetpack/issues/19488

**Comment by ciampo** [comment] 2021-04-09 13:10
Tentative hotfix:  Automattic/jetpack#19489

Closing this issue in favour of the new one opened in the Jetpack repository: Automattic/jetpack#19488

**Comment by davipontesblog** [comment] 2021-04-09 17:07
This is now fixed on simple sites, and will be fixed on atomic on Tuesday when Jetpack 9.6.1 merges:
https://github.com/Automattic/jetpack/milestone/189?closed=1

**Comment by simison** [comment] 2021-04-16 12:10
Jetpack 9.6.1 is live so closing.

**Closed as completed by simison** 2021-04-16 12:10 UTC
Labels: Bug, [Pri] High, [Feature] Media, Blocks, Triaged
