### ISSUE TITLE
[Bug] Check box for bulk actions on classic view is not showing on the Posts section on simple sites

### ISSUE THREAD

**Issue by carolframen** [Automattic/wp-calypso#77109] opened 2023-05-18 17:58 UTC
### Quick summary

On simple sites, the bulk action check boxes are not displayed in the Posts section.
I was able to see them on the Pages section and I was able to see them on atomic sites.

Website on Premium plan, boxes are not displayed:
![image](https://github.com/Automattic/wp-calypso/assets/119800062/df2b9e5f-5f8c-4814-b4b2-bbc8ce3bf462)

Website on Business plan, atomic, boxes are displayed:
![image](https://github.com/Automattic/wp-calypso/assets/119800062/1c334d22-10dd-4f20-bbad-1c6f770abf7d)

Website on Premium plan, pages section, boxes are displayed:
![image](https://github.com/Automattic/wp-calypso/assets/119800062/b605c341-5fe2-441c-9569-25ab726c4719)

I also tested this on a website with the Personal plan and free plan. All simple sites had the issue.

### Steps to reproduce

1. Go to the Posts sections on a simple site
2. Change to Classic view

### What you expected to happen

There should be check boxes next to the posts so you could select them to do bulk actions

### What actually happened

The boxes are not there

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- [Chrome 113 on Windows 10](https://www.whatismybrowser.com/detect/what-version-of-chrome-do-i-have)

**Comment by carolframen** [comment] 2023-05-18 17:58
Forgot to add the ticket #6303960-zen

**Comment by cuemarie** [comment] 2023-05-18 20:05
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/76852

**Closed as completed by cuemarie** 2023-05-18 20:05 UTC
Labels: Bug, [Pri] BLOCKER, Needs triage, [Platform] Simple, [Status] Priority Review Triggered
