### ISSUE TITLE
"Empty" links (<a> tags without href) causing block errors

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#58083] opened 2021-11-15 22:45 UTC
### Quick summary

I've come across this in two separate interactions now. While I'm able to reproduce the behavior by manually adding empty `<a> </a>` tags in with the code editor, **I'm not sure how either user ended up with these empty tags to begin with**.

For completeness, I _have_ tried adding a link using the hovering block toolbar without an address, and that doesn't seem possible. It also doesn't seem possible to remove an existing link's URL and leave it blank.

### Steps to reproduce

1. Create a new post or page.
2. Insert some text; the type of block used should not matter.
3. Switch to the Code Editor.
4. Add "empty" anchor (`<a> </a>`) tags around some of the text.
5. Switch back to the Visual Editor.
6. Click on the new faulty link.

<img width="1480" alt="Markup 2021-11-15 at 17 41 37" src="https://user-images.githubusercontent.com/5630717/141864406-c3d8a871-ea2b-4e46-98c6-e5a6d4b1007c.png">

### What you expected to happen

No error, and the ability to change the link to a proper URL.

### What actually happened

`This block has encountered an error and cannot be previewed` message, preventing the URL or the link text from being edited.

<img width="861" alt="Markup 2021-11-15 at 17 42 37" src="https://user-images.githubusercontent.com/5630717/141864483-f1122ad8-7fae-4532-a2a2-f16809ae56aa.png">
<img width="846" alt="Markup 2021-11-15 at 17 42 44" src="https://user-images.githubusercontent.com/5630717/141864485-cbc8bc5c-4dc6-4c44-ad15-1f0929d15b53.png">

### Context

4454716-zen
32746380-hc

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No.

### Other notes

Browser console shows `TypeError: e.url is undefined` in `react-dom.min.edd8b7a6.js` when clicking the faulty link to trigger the block error.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

To resolve the error, you can access the Code Editor and delete any pair of empty `<a> </a>` tags.

**Comment by Robertght** [comment] 2021-11-16 09:57
I think this is the expected behavior for now as it contains invalid code and I can replicate this on a self-hosted site.

cc @Automattic/flow-patrol-create for a second look

**Comment by jp-imagines** [comment] 2021-11-18 16:13
Ran into another instance of this in 4302039-hc and asked the user about it. Based on page revisions, the empty `<a></a>` tag was present since the page was created, and the user said they copy/pasted the content in from Microsoft Word. I imagine that's where they're coming from.

I appreciate that this is expected behavior and present in Core WP, but I wonder if there's a way (for us or core folks) to "strip" these blank tags when pasting in from an external source. They definitely cause some confusion and frustration, since the text becomes uneditable as a result.

**Comment by alshakero** [comment] 2021-12-01 13:59
Very nice documentation of the issue. Thank yo so much!

Fix is ready in https://github.com/WordPress/gutenberg/pull/37034.

**Comment by edwinho89** [comment] 2022-01-26 04:14
33396918-hc

User reported having similar issues when attempting to add links to a paragraph.

It is unclear to how user add links to their post (asking for it) however the scenario above is similar.

**Comment by Greatdane** [comment] 2022-02-17 05:19
Looks like this will be fixed in core soon! https://github.com/WordPress/gutenberg/pull/37034

**Comment by alshakero** [comment] 2022-03-25 15:27
Closing as fixed in https://github.com/WordPress/gutenberg/pull/37034.

**Closed as completed by alshakero** 2022-03-25 15:27 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] Low
