### ISSUE TITLE
Query Loop Block: Sticky posts do not stay at the top when used in template

### ISSUE THREAD

**Issue by thekingsprojects** [Automattic/wp-calypso#61785] opened 2022-03-10 02:17 UTC
### Quick summary

When using the Query Loop block to show posts as part of an FSE template (e.g., on the theme's "Index" template), any sticky posts appear in the normal post flow, rather than at the top/front of the post list.

This does not seem to happen when a Query Loop block is used within the content of a page; I've only been able to replicate it in a template so far.

### Steps to reproduce

1. Make a post sticky.
2. If the sticky post would be the newest post, create another, non-sticky post that is newer.
3. Open the Editor on an FSE-enabled site.
4. Open a template that contains a Query Loop set to show posts, or add this block to a template.
5. Make sure that the "Sticky posts" setting for the Query Loop is set to "Include", not Exclude or Only.

### What you expected to happen

Any sticky posts should appear above other, more recent posts.

### What actually happened

Posts appear in the normal newest-to-oldest sort order, ignoring any "sticky" settings.

### Context

Customer report here: 4839669-zen

Confirmed by testing on my own Atomic site.

Possibly related to [this issue](https://github.com/Automattic/wp-calypso/issues/61620)? In this case, however, both the editor and the live site are ignoring the sticky setting, rather than the live site still functioning correctly.

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Option 1: Add a second Query Loop above the first one. Set the "top" query loop to show Only sticky posts, while the "bottom" one Excludes sticky posts.

Option 2 (not applicable to every case, but was offered to this user): Write the desired text (in this case, an introduction) directly into the template, above the Query Loop, instead of relying on a sticky post.

**Comment by kimerlin81** [comment] 2022-03-11 01:21
Thanks for submitting this bug report @thekingsprojects! I was able to reproduce this on a test site with several themes activated. I've added this report to the HE Cross-Reference Watchlist since there is a related issue in the Gutenberg Repo: https://github.com/WordPress/gutenberg/issues/38979

**Comment by jamiepalatnik** [comment] 2022-03-12 18:09
Another report: 4839596-zd-woothemes

Edit: Looks like this is a different report for the same user site.

**Comment by helenaartmann** [comment] 2022-05-02 19:27
Another report: 5183244-zen

Gave them the two workarounds suggested above.

**Comment by kimerlin81** [comment] 2022-06-20 12:40
Another report of this. Shared option 1 workaround

- [ ]  please update user in 5311021-zd-woothemes once this is fixed

**Comment by Trekky12** [comment] 2022-12-11 12:28
Unfortunately the workaround option 1 is not usable since the sticky posts option is hidden when the query is inherit.
Is there another option to create two query loops with and without sticky posts?

**Comment by cuemarie** [comment] 2023-12-13 23:10
Encountered this issue here: 7448744-zen

**Comment by cuemarie** [comment] 2023-12-13 23:12
Its unclear if this was fixed in core or not, based on https://github.com/WordPress/gutenberg/issues/38979

**Comment by annezazu** [comment] 2024-08-30 23:57
https://github.com/user-attachments/assets/a3c5b905-a481-4bec-8043-da84951705bf


Definitely fixed :) Closing this out both due to no further reports and inability to replicate.

**Closed as completed by annezazu** 2024-08-30 23:57 UTC
Labels: Bug, [Pri] Normal, Triaged, [Feature] Full Site Editor, [Block] Query Loop, Customer report [LEGACY]

**Comment by lancewillett** [comment] 2024-08-31 00:07
Question for @cuemarie CC @tashabishop02 & @andrewspittle

Do we need reach back out to all the above "attached" customer reports in Zendesk (etc.) to close the loop after a fix?

Or, how would we handle getting the word out if someone had this issue?

Reading the comments on this ticket, there are a few that say, "Please update the customer when this is fixed." But, it's from 2022... so maybe we missed the window of opportunity.

**Comment by andrewspittle** [comment] 2024-09-02 19:20
I'll defer to @tashabishop02 here on the decision. In an ideal world I think we follow up with people. But, as you note, that may require a more timely fix than we arrived at here.

**Comment by cuemarie** [comment] 2025-03-20 00:29
Hey @lancewillett ! 

When I was triaging Dotcom issues (2023), batch replying to customers impacted by a particular bug was a time consuming process with what felt, to me, like not a lot of payoff, so even if folks wanted updates, we reserved batch replies for high impact issues.

Because this was ultimately a core issue that was impacting Dotcom customers, that to me is another reason to _not_ to send out updates here – as we don't update customers on all feature requests or new fixes within Gutenberg. 

BUT, with @inaikem now heading up all things Dotcom Product Quality, I recommend we see what he thinks!

**Comment by cuemarie** [comment] 2025-03-20 00:32
@ceslava I'd recommend reaching out to our support engineers for your WordPress.com site (https://wordpress.com/support/help-support-options/), and they can take a closer look to see if that's this same bug, or something else causing the trouble.   We're happy to help!

**Comment by ceslava** [comment] 2025-04-19 18:12
Thank you @cuemarie but I was talking of a self-hosted WP.
