### ISSUE TITLE
CoBlocks: Hyperlinks getting removed from pictures when editing the Masonry Gallery

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/wp-calypso#39807] opened 2020-03-02 12:00 UTC
This issue was previously reported [here](https://github.com/Automattic/wp-calypso/issues/36691). 

When editing a Masonry gallery to add a new picture, the hyperlinks that were set for the other pics that were in the gallery get removed once the new picture is added.

#### Steps to reproduce

1. Add a Masonry Gallery to a page or post.
2. Add a few images to the gallery.
3. Click on one of the images and select Custom URL under the Link settings tab. Then add URL to one or more pics.
4. Then, click on the **Upload** or **Media** button on the gallery to add an image to the gallery.
5. Check the images that were in the gallery already and notice that the URLs set in the previous step are gone.

#### What I expected

Newly uploaded image gets added and should not affect the previously added images to the gallery. 

#### What happened instead

New image gets uploaded, but the Custom URLs of the other images in the gallery get removed.

#### Browser / OS version
Google Chrome Version 80.0.3987.122 (Official Build) (64-bit)
macOS Mojave 10.14.6 (18G3020)

#### Screenshot / Video
https://www.loom.com/share/bd297b88297c4cffb296c28e5ca27c14

Test Site: https://testpremiumrose.wordpress.com/

**Comment by kriskarkoski** [comment] 2020-03-11 02:39
@rosepajaroja Are you still able to reproduce this? I tested on Atomic, Simple WP Admin, and Simple Calypso and have not been able to reproduce the issue.

**Comment by kriskarkoski** [comment] 2020-03-25 16:30
Another report in #19692258-hc

**Comment by andreabadgley** [comment] 2020-03-25 20:05
Another report in 19697715-hc. User would like to be notified when it's repaired, pretty please, in https://woothemes.zendesk.com/agent/tickets/2818673

**Comment by khristiansnyder** [comment] 2020-04-03 21:37
Another report in 18897488-hc. I was able to replicate on the user's site as well.

Follow up ticket: 2845786-zen

**Comment by WunderBart** [comment] 2020-08-26 13:39
Closing this one as I couldn't reproduce after the recent update (https://github.com/Automattic/wp-calypso/issues/45033). URLs remain as they were after updating the gallery.

**Closed by WunderBart** 2020-08-26 13:39 UTC
Labels: Editor, [Type] Bug
