### ISSUE TITLE
[Bug]: Nav unification menu doesn't update after installing Jetpack CRM

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-calypso#59768] opened 2022-01-05 15:46 UTC
### Quick summary

I'm not quite sure where the failure lies, but essentially the Jetpack CRM menu items don't show after install until one refreshes the page.

It only did this on the initial Atomicization + install + activate.

### Steps to reproduce

1. Create a new WordPress.com site with a Business plan
2. Go to plugins and search for CRM
3. Installed Jetpack CRM from the search results

During this process, the site is auto-Atomicized and the plugin is installed and activated. One is then redirected to `/wp-admin/plugins.php`, but the Jetpack CRM menu items are not present until refresh.

### What you expected to happen

Since Jetpack CRM is active, its menu items should show. Also, I'd expect it to jump into the CRM setup wizard, which it does not do.

### What actually happened

Jetpack CRM's menu items don't show after activating the plugin until one refreshes the page.

### Context

Discovered while triaging a potential CRM bug with WoA

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple, Atomic

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Refresh the page.

**Comment by cuemarie** [comment] 2023-06-28 19:12
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on New Site - **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO
- There's been some updates to the landing pages after installing a plugin, but the description above did match - I didn't see the Jetpack CRM nav item until after refreshing the dashboard, even when clicking around from the 'Manage Plugins' screen to home.  
- Not sure if this is a symptom specific to Jetpack CRM, or just reflective of the time it takes to transfer a new site to AT on it's first plugin installation.

**Recording**

https://github.com/Automattic/wp-calypso/assets/27249804/a0db98e8-eeba-47e5-8561-bae20266eb2a

📌 ACTIONS
- Assigned to Other
- CC: @jeherve

**Comment by jeherve** [comment] 2023-06-29 08:12
> just reflective of the time it takes to transfer a new site to AT on it's first plugin installation.

I would tend towards this hypothesis. From the video, it looks as if the site still loads the WordPress.com Simple toolbar after the plugin is installed, because the page hasn't been refreshed yet. When you refresh, you start loading the WoA site and its contents, including the nav bar for WoA and all the additional menu items that may be added by plugins.

**Comment by cuemarie** [comment] 2023-06-29 19:03
Makes sense to me! Since we've no user reports of this, I'll close as it seems to be reflecting expected behavior, unrelated to Jetpack CRM.

📌 ACTIONS
- Closed as won't fix.

**Closed as not planned by cuemarie** 2023-06-29 19:03 UTC
Labels: Bug, [Pri] Low, [Feature] Plugins, [Feature] Calypso & wp-admin Navigation, Triaged, [Plugin] Jetpack
