### ISSUE TITLE
Expanding list view covers the overlay menu items on navigation

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#65667] opened 2022-07-18 09:31 UTC
### Quick summary

On Page editors, when clicked to expand Navigation block with "always" on overlay menu, the list view expands and covers the overlay menu items.

### Steps to reproduce

1. Create a page
2. Insert Navigation block with menu items
3. On the Navigation block, select "always" on overlay menu.
4. Expand list view on editor

### What you expected to happen

The page editor should reduce in size after expanding list view.

### What actually happened

![image](https://d.pr/i/vO4bpe+)

Gif: https://d.pr/i/vO4bpe

### Context

Initially reported from https://github.com/Automattic/wp-calypso/issues/65526

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Turn overlay menu option back to "default" or off.

**Comment by renata-franco** [comment] 2022-07-27 14:44
📌 HOUSEKEEPING (To be removed once checked)


- Transfer to A8C Repos if needed, or Create new issue in Gutenberg



📌 SCRUBBING

- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - Yes

------

📌 FINDINGS/SCREENSHOTS/VIDEO 

I was able to replicate this issue on posts and pages on Simple, AT, and Self-Hosted as well. 

However, it takes a bit more steps to get to the issue. 

1. Create a page or post. 
2. Add a Navigation Block. 
3. Fill in the Navigation with new items or an already made menu. 
4. Open the extra settings of the Navigation Block.
5. In the "Overlay Menu" options, select "Always".
6. Open the List View of the editor.  




I recorded a video here: 


https://user-images.githubusercontent.com/81378719/181270768-70530a28-b739-4a0b-8a85-730a358356bb.mp4






------

📌 ACTIONS

- Marked as Triaged for Quality Squad review

**Comment by Greatdane** [comment] 2022-10-20 05:54
@renata-franco was this ever posted on https://github.com/WordPress/gutenberg/issues as well (if it affects self-hosted)?
I can still reproduce it, so will also post on core if you didn't add there already

**Comment by Greatdane** [comment] 2022-10-20 05:55
Actually, closing this as its a duplicate of https://github.com/Automattic/wp-calypso/issues/65526
Which has been added to core as well!

**Closed as completed by Greatdane** 2022-10-20 05:55 UTC
Labels: Bug, [Pri] Low, Navigation, Blocks, Triaged, [Platform] Simple, [Platform] Atomic
