### ISSUE TITLE
Pages: Don't show default Blog Posts page in Scheduled list

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#18417] opened 2017-09-30 13:00 UTC
Currently, when I have pages scheduled to publish at a future date, and I visit https://wordpress.com/pages/scheduled, I see my Blog Posts page. This feels weird because I can't actually act on the default page and the page isn't actually scheduled at all.

#### Steps to reproduce
1. Starting at URL: wordpress.com/pages
2. Schedule a page
3. Visit wordpress.com/pages/scheduled
4. See default "Blog Posts" page in the list of scheduled pages.

#### Screenshot

<img width="974" alt="pjqzyw" src="https://user-images.githubusercontent.com/7240478/31045969-f3a56e08-a5ac-11e7-9f41-94978ce343ef.png">

**Comment by arunsathiya** [comment] 2018-10-27 09:44
Noting that from my tests, this is not the case anymore. I scheduled a page on `wordpress.com/pages`, but I do not see the blog archive page on the scheduled list. This is with the `Homepage Settings` having a page as the homepage, and another page being a blog archive section.

## Scheduled pages

<div align="center"><img width="780" alt="screenshot 2018-10-27 at 11 44 45" src="https://user-images.githubusercontent.com/18581859/47602139-d5af8700-d9f7-11e8-9b18-25b9f7c76949.png"></div> 
<div align="center"><sup>Image indicating that the blog archive page is not seen on the scheduled pages list</sup></div> 

## "Homepage Settings" on the Customizer

<div align="center"><img width="398" alt="screenshot 2018-10-27 at 11 43 26" src="https://user-images.githubusercontent.com/18581859/47602140-d811e100-d9f7-11e8-8e03-8640cc23be45.png"></div> 
<div align="center"><sup>Image indicating the settings from the "Homepage Settings" section of the Customizer</sup></div>

**Comment by mattsherman** [comment] 2018-10-30 00:18
@arunsathiya Thanks for testing this again.

I also cannot reproduce this anymore. Closing.

**Closed by mattsherman** 2018-10-30 00:18 UTC
Labels: Pages, [Type] Bug
