### ISSUE TITLE
Marketplace: Disable scrollToTop in category routes

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#63792] opened 2022-05-19 02:08 UTC
Clicking on a category shouldn't scroll to the top of the page, this behavior is especially jarring on mobile.

- [x] Disable [scrollToTop](https://github.com/Automattic/wp-calypso/blob/0b1198ce5237a2540aaeeff024da4d5532a84acb/client/my-sites/plugins/index.js#L94-L100) in category routes
- [x] Disable it wherever else we can, I suspect the only place we need it is onSearch which means we can probably remove it from everywhere and add a scrollToTop in doSearch instead.

**Comment by lsl** [comment] 2022-05-26 05:33
WIP in here https://github.com/Automattic/wp-calypso/pull/63405

**Comment by Rolilink** [comment] 2022-05-26 22:12
Can we maybe do a smarter scroll? only if the user has scrolled past down an anchor point (like the beginning of the list).

**Comment by lsl** [comment] 2022-05-27 02:40
I don't think there are any anchor points. I really just want to remove this from the middleware. If there needs to be auto scrolling it should happen in react components.

**Comment by Rolilink** [comment] 2022-05-27 16:09
>  If there needs to be auto scrolling it should happen in react components.

+10000

**Comment by candy02058912** [comment] 2022-08-26 06:38
Closing issue as discussed with @lsl.
The original intent was to clean up things. Extra code has been introduced in #66805 In order to preserve intended behaviors. Therefore, we think it's not worth it making this change.

**Closed as completed by candy02058912** 2022-08-26 06:38 UTC
Labels: [Status] In Progress, Good First Issue, Marketplace UI: Categories + Navigation

**Comment by lsl** [comment] 2022-08-29 02:04
>  Extra code

Just clarifying, the issue we were seeing was too much extra code introduced. Its possible this is worth doing some other way, like moving a call to this in some other part of the middleware that's always called for these routes?
