### ISSUE TITLE
Customizer: label "You are customizing Menus" is invisible when cursor is over it

### ISSUE THREAD

**Issue by igladun** [Automattic/wp-calypso#22122] opened 2018-02-05 08:09 UTC
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Log in and select your site
3. Select Themes -> Customize
4. Select Menus

#### What I expected
When I move cursor over label "You are customizing Menus"  it is still visible

#### What happened instead
Label "You are customizing Menus" is invisible when cursor is over it

#### Browser / OS version
macOS 10.13.3
Chrome 64.0.3282.140
Reproducible in recent Firefox and Chrome Canary

#### Screenshot / Video
![customizer-menu](https://user-images.githubusercontent.com/4245201/35793974-6a0c0c32-0a5c-11e8-816d-f280d6fa33a6.gif)

#### Context / Source
Not reproducible with other items in the customizer menu (site identity, fonts, etc.)

**Comment by rachelmcr** [comment] 2018-02-05 15:02
Thanks for the report! Closing this as a duplicate of https://github.com/Automattic/wp-calypso/issues/19915.

**Closed by rachelmcr** 2018-02-05 15:02 UTC
Labels: Customizer, [Type] Bug
