### ISSUE TITLE
After editing uploaded image and editing other image, you get JS error

### ISSUE THREAD

**Issue by lamosty** [Automattic/wp-calypso#7467] opened 2016-08-15 13:00 UTC
While testing #7446, I stumbled upon a JS error. Steps to repro:

1. Go to http://calypso.localhost:3000/post and select a site;
2. Upload new image and click Edit;
3. Click Edit Image in the top right corner;
4. Click Done;
5. Select some other, already uploaded image and click Edit;
6. Click on Edit Image again and then Done;
7. Now, click on Edit in bottom left corner and you'll get the following error:

![selection_020](https://cloud.githubusercontent.com/assets/4988512/17665019/7936d294-62f8-11e6-89fd-74815ad19791.jpg)

Full stack trace:

![selection_021](https://cloud.githubusercontent.com/assets/4988512/17665028/8f5ac3aa-62f8-11e6-82e6-edf309355e01.jpg)

Video:

https://drive.google.com/file/d/0B8e-IpRwSdjteDk2SWdmb28yRUE/view

OS: Ubuntu
Browser: Chrome latest

The problem is that user can't do anything after the error occurs. Can't close the modal, etc. Needs full reload.

cc @gwwar @robobot3000

**Comment by retrofox** [comment] 2016-09-08 20:47
@lamosty I can't reproduce it now. Can you take a look when you have the chance please?

**Comment by gwwar** [comment] 2016-09-09 17:52
Nice, I think @hoverduck found repro steps in https://github.com/Automattic/wp-calypso/issues/8005

**Comment by gwwar** [comment] 2016-09-28 21:40
This was fixed in #8261

**Closed by gwwar** 2016-09-28 21:40 UTC
Labels: Media, [Pri] High, [Type] Bug
