### ISSUE TITLE
Layout issue on Reader first load

### ISSUE THREAD

**Issue by belcherj** [Automattic/wp-calypso#49275] opened 2021-01-25 19:46 UTC
### Steps to reproduce the behavior

1. Be in a site
2. Open the reader

I was not able to reporduce.

#### What I expected to happen

I expect the left nav menu to load properly.

#### What actually happened

The nav menu is tucked up under the top bar.

<img width="276" alt="Screen Shot 2021-01-25 at 2 34 09 PM" src="https://user-images.githubusercontent.com/6817400/105757035-75338b00-5f1b-11eb-9a17-d982d84bcb49.png">

When I opened dev tools and made the viewport smaller I got this:
<img width="537" alt="Screen Shot 2021-01-25 at 2 37 35 PM" src="https://user-images.githubusercontent.com/6817400/105757170-a4e29300-5f1b-11eb-8130-979b72692086.png">

When I refreshed I got whitespace between the top menu and the nav:
<img width="428" alt="Screen Shot 2021-01-25 at 2 38 36 PM" src="https://user-images.githubusercontent.com/6817400/105757219-b3c94580-5f1b-11eb-83df-e6bd7bb8ec7b.png">

After the next refresh, everything worked as expected.

#### Browser / OS version

Chrome OSX Latest

#### Is this specific to the applied theme? Which one?

N/A

#### Does this happen on simple or atomic sites or both?

N/A

#### Is there any console output or error text?

None

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Blocks navigating reader

**Comment by getdave** [comment] 2021-02-03 14:05
I was able to reproduce this.

If you have a large number of items under any of the top level menus (eg: Followed Sites) then if you scroll down the page when these are expanded it will cause both the sidebar and the main page content to scroll. The sidebar should stick whilst the page should scroll.

Possibly related to https://github.com/Automattic/wp-calypso/issues/49175

**Comment by obenland** [comment] 2021-03-11 23:35
@belcherj Is this something you can still reproduce? I wonder if it was fixed by https://github.com/Automattic/wp-calypso/pull/49999

**Comment by belcherj** [comment] 2021-03-18 05:16
I cannot readily reproduce it but I have seen it in the last day or two.

**Comment by belcherj** [comment] 2021-03-18 05:19
If I make my browser thinner I still get blank screens. 
<img width="519" alt="Screen Shot 2021-03-18 at 1 17 46 AM" src="https://user-images.githubusercontent.com/6817400/111577056-fffc6d80-8787-11eb-859f-a405b29ee105.png">
<img width="707" alt="Screen Shot 2021-03-18 at 1 17 35 AM" src="https://user-images.githubusercontent.com/6817400/111577059-00950400-8788-11eb-84bd-607e0d08fc83.png">

**Comment by tjcafferkey** [comment] 2021-03-22 15:56
Steps to reproduce:

1. Open reading, and all nav items
2. Scroll down the content on the right and lazy-load in new content
3. Resize window and scroll up.

**Comment by jordesign** [comment] 2021-11-03 10:21
I'm not currently able to recreate this behaviour.

**Comment by davemart-in** [comment] 2022-07-28 20:00
Looks like the top bar is auto-resizing now. Someone must have fixed this issue. Woot! Closing...

**Closed as completed by davemart-in** 2022-07-28 20:00 UTC
Labels: Bug, [Pri] Normal, [Feature] Reader, Sidebar
