### ISSUE TITLE
Editor: No template dropdown in Calypso when theme supports Template Post Types

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/wp-calypso#16249] opened 2017-07-14 18:20 UTC
In WordPress 4.7, it became possible to assign templates to post types other than pages: https://core.trac.wordpress.org/ticket/18375

However, when a theme supports this, the template dropdown does not appear in Calypso.

On WordPress.com we currently have one theme that supports this (Verity), but there will be more down the road.

#### Steps to reproduce
1. Set up a site using the theme Verity.
2. Edit a post using /wp-admin.
3. See that there is an option available to switch the post's template in the right sidebar (note: you may need to enable 'Post Attributes' under the 'Screen Options' tab at the top of the page)
4. Edit the same post using Calypso.

#### What I expected
To see an option to change the post's template, under a 'Post Attributes' header.

#### What happened instead
No option appeared available, under any of the sections.

#### Screenshot / Video
The template option for posts in /wp-admin using the Verity theme:

![Image](https://cldup.com/rZkq9T-mdc-3000x3000.png)

All post options in Calypso, editing the same post as above on a site using the Verity theme:

![Image](https://cldup.com/vr4yni0Mqu-3000x3000.png)

#### Context / Source
I noticed this while reviewing a future theme for WordPress.com that also supports this feature.

**Comment by alisterscott** [comment] 2017-12-20 23:49
Tested this on the Verity theme and I can confirm this still isn't available in Calypso

**Comment by crunnells** [comment] 2018-03-30 19:44
Verity released another update which included post templates for Portfolio items, but you cannot select them in Calypso.

**Comment by rachelmcr** [comment] 2018-08-29 15:45
I tested and confirmed this issue in the Calypso editor. However, I also tested in Gutenberg and templates are working for both posts and portfolio items there:

![screenshot 2018-08-29 16 38 36](https://user-images.githubusercontent.com/8658164/44799029-e0da6800-abaa-11e8-8640-bcde44606fdb.png)

Since editor development efforts are focused on Gutenberg, and this should be resolved with the Gutenberg launch, I'm closing this issue for now.

**Closed by rachelmcr** 2018-08-29 15:45 UTC
Labels: Editor, Posts, [Pri] High, [Type] Bug
