### ISSUE TITLE
Gutenboarding: show Calypso signup form if user isn't authenticated (frankenflow)

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#39140] opened 2020-01-29 14:58 UTC
When pressing top-right corner "create site" here:

<img width="1847" alt="Screenshot 2020-01-29 at 16 52 18" src="https://user-images.githubusercontent.com/87168/73367597-6a1e2e80-42b8-11ea-8504-71fe5f4d2379.png">

... it pops up this error in the console:

<img width="974" alt="Screenshot 2020-01-29 at 16 52 28" src="https://user-images.githubusercontent.com/87168/73367636-799d7780-42b8-11ea-987e-0282e92871e9.png">

It's fine if we just ask folks to test as authenticated for now, but I wonder if we can pop up Calypso signup screen? They could login or create an account and continue the flow.

The signup form can take in an "redirect" URL if I remember correctly.

**Comment by sirreal** [comment] 2020-01-30 14:08
Duplicate of #39170

**Closed by sirreal** 2020-01-30 14:08 UTC
Labels: [Goal] Gutenboarding

**Comment by simison** [comment] 2020-01-30 14:28
haha, I thought I wrote about this somewhere already but couldn't figure out where. 👍
