### ISSUE TITLE
Editor: Only a single Emoji can be displayed in tags

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#8316] opened 2016-09-29 09:09 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Create a new post, and add an Emoji as a tag. 👍
3. Publish that post.
4. Start writing a new post.
5. Add another Emoji as a tag. 🚀
6. When the post is saved, 🚀 will be replaced by 👍.

**Comment by rachelmcr** [comment] 2017-08-07 15:17
I tested using the steps above and couldn't reproduce this issue. Both of my posts display the correct, different emoji tags and the two tags appear in my Writing settings:

![screen shot 2017-08-07 at 4 13 22 pm](https://user-images.githubusercontent.com/8658164/29032985-681e2406-7b8b-11e7-82ef-aaeb5f3e7dd9.png)

I also confirmed that I can use two different emoji tags on the same post, and they are displayed correctly on the published post.

Closing as I can't reproduce this issue, but please reopen if it persists in some cases.

**Closed by rachelmcr** 2017-08-07 15:17 UTC
Labels: Editor, [Type] Bug
