### ISSUE TITLE
If a plan is renewed from email but signed into another account, the renewal overrides existing plan.

### ISSUE THREAD

**Issue by zachspears** [Automattic/wp-calypso#74310] opened 2023-03-10 00:20 UTC
### Quick summary

As seen in this correspondence: 6021799-zd-woothemes

The user got an email to renew their expired plan (see Mar 8th email attachments) and when they followed the instructions and purchased the renewal they were signed into another account and renewed the wrong site. This overrode the existing site plan (the new plan was business but the site already had an active ecom plan). This means the current site had a lower plan and had paid for two plans while the intended renewal was still outstanding.

### Steps to reproduce

1. Create two WPCOM accounts. 
2. One site with Ecom plan and one with a Biz plan. (Not sure if these exact plans are required)
3. Let the Biz plan expire. 
4. Renew Biz plan from the expiration/renewal email while signed into the account with the Ecom plan. (It appears this was done on mobile which may or may not be relevant.)

### What you expected to happen

Some kind of notice that the renewal is for the wrong site, or at the very least that it is incompatible (because the renewal is for a lower plan and over top of an existing plan). 

### What actually happened

The existing plan is overridden and the intended site is never renewed. 

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

I have no idea how specific this issue is, but it's very detrimental to the users affected, and we should probably have some guardrails in place for things like overriding existing plans with renewals.

**Comment by zachspears** [comment] 2023-03-10 00:28
Added "No and the platform is unusable" to Available workarounds? as it requires an HE to go in and sort out the site plans for both sites, including verifying two separate accounts. You also cannot use the plan you paid for in the interim.

**Comment by cometgrrl** [comment] 2023-03-10 00:31
Lowered to `high` priority, since this probably doesn't happen often or to too many customers, but it's still a pretty bad bug.

**Comment by cuemarie** [comment] 2023-03-28 22:06
📌 SCRUBBING : 
- quick note - I'm working on triaging this, awaiting the automatic email to come through following the expiration so I can try to replicate the issue.

📌 ACTIONS
- moving to `Needs reply` for now while I wait for the next steps.
- Some discussion with Shilling here: p1680041893805319-slack-C03TY6J1A

**Comment by cuemarie** [comment] 2023-03-29 23:45
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Here's how I tried to reproduce this:

Account A
- Owns a Premium Plan Site, among others
- Set this premium plan's expiration date to tomorrow

Account B
- Owns 1 eCommerce plan site
- Logged into WordPress.com in a Chrome browser

Via internal tools, I copied the `Renew Now` link that would be sent out to Account A's email, then pasted that into a browser where Account B is logged into WordPress.com.  Instead of being redirected to any checkout screen, I am redirected to https://wordpress.com/me/purchases

- this behavior was consistent in desktop and mobile chrome browsers.

You can find the exact linnk I copied and pasted here: p1680132563545849/1680041893.805319-slack-C03TY6J1A


📌 ACTIONS
- Going to try this once more tomorrow from the actual email (I've updated my plan owned by Account A to expire tomorrow, to try to trigger that email to come my way), but if I can't repro there, I'm not sure we can bet to the bottom of what happened for this user.

**Comment by DavidRothstein** [comment] 2023-04-03 16:58
I think a lot of what happened here is that the user got redirected to https://wordpress.com/me/purchases (as noted above, that was because they were logged in as a different account and therefore didn't have access to the renewal URL they clicked on in the email), and then probably got confused about what was going on and navigated somewhere else and purchased a business plan on a different site instead.  To prevent that, the user experience here could be improved to explain why the initial redirect to https://wordpress.com/me/purchases happened:
- https://github.com/Automattic/wp-calypso/issues/75240

The business plan purchase was a new purchase (not a renewal) but it was indeed on a site that already had an eCommerce plan.  I am not sure where they got a link to do that (normally one wouldn't be shown to them, e.g. on the Plans page, since they already own a higher plan) and as a result this scenario is rare, but if you somehow **do** get that link, nothing in particular stops you from downgrading, and that's what happened here.  In this case, I think it's no different than "downgrading" by first cancelling the old plan and then buying a new one, but we should still prevent it from happening this way because it's not a downgrade path that's intended (and not communicated to the user that that's what they're doing):
- https://github.com/Automattic/payments-shilling/issues/1525

I think between the above two issues this is mostly covered (although it still would be interesting to know where they wound up getting the checkout URL for the new business plan purchase), but for this specific customer, I noticed they now have a Business plan **and** an eCommerce plan on the same site -- @zachspears, I think you probably intended to remove the old Business plan when you added the eCommerce plan back.  Should that be done now?

**Comment by cuemarie** [comment] 2023-04-04 23:35
Back to update my triaging notes once more - 

I was able to test this with the actual email on both desktop and mobile (as the report above notes the user was in a mobile environment).  In either case, I was redirected to https://wordpress.com/me/purchases just as expected.

**Renewal Email -> Desktop**

https://user-images.githubusercontent.com/27249804/229944347-5b0acfcd-30e5-45f0-b40c-c5b02ac08066.mp4

**Renewal Email -> Mobile**

https://user-images.githubusercontent.com/27249804/229944998-399fe6e8-1bb8-49e7-a202-c4c213d32a70.mp4

---

Thanks for your insight @DavidRothstein !  How this user got into this situation is a mystery to me - I'm not able to find a way to accidentally renew the wrong plan.  Perhaps @zachspears can weigh in with any other ideas.

**Comment by michaeldcain** [comment] 2023-04-11 17:09
From planning:

It looks like we can remove the business plan from the user's site (and verify that the site isn't downgraded). Then we can close this issue.

**Comment by michaeldcain** [comment] 2023-04-18 04:27
@zachspears I removed the Business plan (and refunded it), and verified that the site wasn't downgraded from Atomic. You're welcome to follow-up with the user. Given that we have two open issues to address the different things that happened here, I'm going to close this issue.

**Closed as completed by michaeldcain** 2023-04-18 04:27 UTC
Labels: Bug, [Feature] Plans & Upgrades, [Pri] Normal, [Feature] Billing Emails, Triaged
