### ISSUE TITLE
Themes: default to all results instead of none if no search matches

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#7307] opened 2016-08-05 18:12 UTC
Right now, if you search something like “politics,” or “candy,” or “shoe store” (not off-the-wall, typo'ed things), you get `no themes found` with Drake in the Calypso theme showcase. Our intention here is to help the user find a theme, not leave them themeless because they searched the "wrong" thing.

![](https://cloudup.com/ch2HsrXc8G7+)

Suggestion: flip the script from showing nothing to showing everything or showing the most popular/generic/extensible themes, with a little inline notice that says something to the tune of ~“darn, we couldn’t find anything particular for your search, but these popular themes can be edited to build almost anything.”

**Comment by folletto** [comment] 2016-08-05 18:13
Very good suggestion. Thanks!

**Comment by folletto** [comment] 2017-01-18 17:58
I just noticed it was a duplicate of https://github.com/Automattic/wp-calypso/issues/2641, closing.

**Closed by folletto** 2017-01-18 17:58 UTC
Labels: Themes, [Status] Needs Design Review, [Type] Enhancement
