### ISSUE TITLE
Editor: previewing changing posts on Jetpack sites broken

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#5607] opened 2016-05-26 12:59 UTC
#### Steps to reproduce
1. select a jetpack site, make sure you're logged in there
2. go to edit a blog post, make a change but don't save it
3. click the "View" button (what's "Preview" on non-JP sites)
#### What I expected

either opens new tab with a preview of the changed post, _or_ doesn't do a preview and just shows me the post as it is (with the button reflecting which one is going to happen)
#### What happened instead

opens new tab, but jetpack site gives me a message like "Sorry, you are not allowed to preview drafts."

**Comment by aduth** [comment] 2016-05-26 14:05
To clarify, this only appears to affect previewing edits to a published post. Previewing a draft works correctly for me.

**Comment by lancewillett** [comment] 2016-10-14 18:15
Confirmed in testing on a Jetpack site, with the same steps above.

Screenshot:

![screen shot 2016-10-14 at 11 15 02](https://cloud.githubusercontent.com/assets/66797/19398038/7dc988d4-91ff-11e6-97a2-5b3731f41399.png)

**Comment by lancewillett** [comment] 2017-02-04 23:28
See also #904

**Comment by lancewillett** [comment] 2017-02-10 00:39
Re-testing this same flow today, I got a 500 error on the Jetpack side. This is the PHP error:

`[10-Feb-2017 00:37:27 UTC] PHP Notice:  Undefined index: HTTP_X_REQUEST_ID in /scripts/env.php on line 98`

![screen shot 2017-02-09 at 17 38 00](https://cloud.githubusercontent.com/assets/66797/22809296/838ea938-eeee-11e6-91f3-6a353c04d63b.png)

**Comment by rralian** [comment] 2017-02-10 19:02
I haven't looked into this, but I can share offhand that one likely related issue is that you cannot delay the opening of a new tab upon an asynchronous operation. Browsers won't allow it. So you can't click "preview", have that trigger the save, and only after the save completes, open the new tab.

So I think this issue could be avoided if we used the preview pane instead, which I believe should be possible for all jetpack sites that support ssl on the front-end. We should do that when possible anyway because it's a better user experience.

A quickfix for the non-ssl-supporting jetpack sites could simply be to disable the "preview" button while the post is in a "dirty" state.

^^ This is just me dropping in with ideas without having looked deeply into the underlying issue. We should fix that too if possible. 😄

**Comment by artpi** [comment] 2017-02-17 09:26
I have confirmed that this is an issue for ALL jetpack sites regardless if user is logged in or not in wp-admin

Should we move this issue to jetpack repo?

**Comment by lancewillett** [comment] 2017-02-17 14:44
@artpi Can you reproduce from the wp-admin flow on a Jetpack site? We were operating under the impression it was Pressable hosting or related calling the preview from Calypso.

**Comment by artpi** [comment] 2017-02-17 14:57
Steps to reproduce on my **wpsandbox.me sandbox**:
1. Edit published post
2. Dont save
3. Click "View"

![screen shot 2017-02-17 at 15 56 57 pm](https://cloud.githubusercontent.com/assets/3775068/23069993/c31fee4a-f529-11e6-8df3-4162cb02f80a.png)

I get this, **even though i am logged in to wp-admin** of the site

**Comment by rralian** [comment] 2017-02-21 20:17
I'm seeing the same thing as @artpi on a regular jetpack (i.e., not Automated Transfer) site. And I can confirm that the "autosave" endpoint returns a preview URL that does not work. I get this response.

![autosave response](https://cloudup.com/c_ICfej5O_J+)

I expect to be able to take that preview url and just load a new tab with it, but when I do that I see the same error as @artpi posts above. I need to dig a little further, but it looks like we're creating that nonce with the wrong assumptions.

**Comment by gwwar** [comment] 2017-02-23 23:27
Doing some quick testing if a post is published, further updates in wp-admin have a fixed `preview_id` in the preview url, while Calypso appears to increment this number.

**Comment by rralian** [comment] 2017-02-28 08:09
The `preview_id` incrementing or not incrementing isn't the issue. First we have a bug in the `action` string used to create the nonce (should be `post_preview_[preview_id]` not `post_preview_[post_id]`, which will be addressed in https://code.a8c.com/D4546. But even correcting that doesn't fix it. From what I see looking at [the nonce code here](https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/pluggable.php#L1785) I think the problem is that we're creating the nonce with the `user_id` of the user from wpcom, but we're verifying it with the `user_id` of the user in the jetpack site. We need an alternate nonce generator for Jetpack that can create the nonce using the user's ID in the remote system. I'll pick this up in the morning, but I want to see if this is a known issue in Jetpack (with an existing solution) before I push further.

**Closed** 2017-02-28 22:19 UTC
Labels: Editor, Jetpack, [Pri] High, [Type] Bug
