### ISSUE TITLE
Me: Display name doesn't update on save, slashes not alllowed?

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#11894] opened 2017-03-08 16:12 UTC
Start at https://wordpress.com/me

### Bug 1

1. Login
2. Change your display name. Save. Notice it doesn't update on the left rail.

### Bug 2

1. Reload. 
2. Change your display name to `\/\/inning`
3. Save
4. Reload
5. Notice your display name is now `//inning`. The backslashes have been removed.

Movie: https://cloudup.com/cVLat2q5zyT

**Comment by philtim** [comment] 2017-03-09 19:26
In addition to Bug 2:

- Escaping the escape character produces the wanted output: blo\\/\\/ery will create the name blow\/\/ery
- After a page refresh, the input field 'Public Display Name' will strip away the first set of escape characters, leaving the string as 'blo\/\/ery'

**Comment by rachelmcr** [comment] 2017-12-11 22:39
#bug-scrub

I can no longer reproduce the first issue; when I change my display name it updates immediately in the left sidebar as expected.

The second issue persists, but as noted you can enter backslashes by escaping them. Given that there is a workaround, and we haven't received any additional reports, what do you think of closing this issue or setting a low priority for it?

**Comment by blowery** [comment] 2017-12-12 14:30
> Given that there is a workaround, and we haven't received any additional reports, what do you think of closing this issue or setting a low priority for it?

Low priority sounds good.

**Comment by worldomonation** [comment] 2021-02-02 18:20
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I was able to reproduce the second portion of the issue (name shows as `//inning` instead of `\/\/inning`.

However, as there has been no recent activity on this issue, the issue is being closed with the label `Closed - Won't Fix`.
If work is scoped and tabled for a milestone, please feel free to re-open this bug.

**Closed by worldomonation** 2021-02-02 18:20 UTC
Labels: Me, [Type] Bug
