### ISSUE TITLE
Gutenberg: Opt in by Calypso editor is broken after opting out.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#38297] opened 2019-12-09 20:27 UTC
Reported by @retnonindya in p1575878314180400-slack-calypso

> Not sure if this is sitewide yet or not (lets hope not!) but an HE and I found a bit of issue when user switched to Classic Editor, then clicked Switch to new editor button on their post/page editor, the button didn’t do anything. The editor didn’t switch at all. I was able to replicate it on the user’s dashboard — but I couldn’t replicate it on my test site :sweat_smile: The workaround for this issue is to set the editor directly from User RC. Once the editor is set from User RC, the button works.

**Comment by kwight** [comment] 2019-12-09 20:36
Oh, I think I got this wrong about the admin notice in WP Admin; this is referring to the Calypso editor modal box:

<img width="1028" alt="Screen Shot 2019-12-09 at 12 35 40 PM" src="https://user-images.githubusercontent.com/349751/70470687-763bfb80-1a80-11ea-85c6-5a38e2cfed52.png">

**Comment by kwight** [comment] 2019-12-09 20:55
Hm, I'm having problems replicating this. I can switch back and forth successfully between Classic (with the top-right ellipsis dropdown (Switch to Classic Editor) and Gutenberg (with the opt-in modal from the sidebar). @retnonindya @rinazrina any other ideas?..

**Comment by kwight** [comment] 2019-12-09 21:01
Also did a support session as the user in the site mentioned, no problems 🤔

**Comment by kwight** [comment] 2019-12-09 21:02
Moving this to backlog until we can get more reports and repeatable steps to reproduce.

**Comment by rinazrina** [comment] 2019-12-10 03:23
@kwight Thanks for opening this issue. We were able to replicate the issue when we did a support session on user's site. The "Switch to new editor" button didn't work on Calypso. While the other button to switch to Classic worked.

However, the issue is fixed once we set the editor's preference to Gutenberg via User RC.

**Comment by retnonindya** [comment] 2019-12-10 03:37
Thank you for checking and opening this issue, @kwight! 

And yes, the issue on the users' dashboard resolved once we re-assign the editor from URC. 

At that time, I suspected it might happen on new websites (created in less than 48 hours) and switched to Classic Editor from Block Editor and wanted to switch back. But both @rinazrina and I unable to replicate the issue on our test sites and accounts 😔 

And yep, moving this issue to backlog would be a good move as we can't replicate it. I will keep an eye for similar issues (lets hope not!) and see how it goes. I really appreciate you checking this, Kirk! Thank you so much!

**Comment by kriskarkoski** [comment] 2020-03-13 18:26
No further reports in 3 months. Closing this one for now.

**Closed by kriskarkoski** 2020-03-13 18:26 UTC
Labels: Editor, [Pri] Normal, [Type] Bug
