### ISSUE TITLE
Editor: Inserting red heart emoji (❤️) in the title doesn't work on Chrome

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#5254] opened 2016-05-06 00:06 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/
2. Enter a title with a red emoji heart (❤️)

#### What I expected

Red emoji heart (❤️)

#### What happened instead

First it shows a black square, then using backspace on that square shows a black heart (see video below)

#### Browser / OS version

Chrome OSX 50.0

Tested Safari and Firefox and could not reproduce

#### Screenshot / Video

![red heart](https://cloud.githubusercontent.com/assets/128826/15060796/9c9a4940-1371-11e6-9a23-e3494e796ab6.gif)

**Comment by lancewillett** [comment] 2016-05-09 17:15
Hi @alisterscott — thanks for this one. Closing as a duplicate of #997 (known Chrome issue).

**Closed by lancewillett** 2016-05-09 17:15 UTC
Labels: Editor, [Type] Bug
