### ISSUE TITLE
Block Widget: blank screen shown if in mobile viewport size

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#59960] opened 2022-01-11 20:05 UTC
### Quick summary

The Block Widget editor screen (Appearance > Widgets) is a blank, white screen if in mobile viewport.

### Steps to reproduce

1. log in.
2. navigate to Apparance > Widgets.
3. either resize browser window to a narrow size (simulating mobile viewport) or use the built-in profiles on Firefox/Chrome.

### What you expected to happen

Block Widget editor is resized for mobile viewport.

### What actually happened

Block Widget editor is a blank, white page with only the navbar showing.
![Screen Shot 2022-01-11 at 11 55 36 AM](https://user-images.githubusercontent.com/6549265/149012535-1b175e54-cc5c-4962-821e-92dcbf5197d3.png)

Issue occurs when the `body class=wp-admin` loses the `sticky-menu`, which occurs at around ~780px.

### Context

Automated end to end tests.

### Browser

Mozilla Firefox, Apple Safari

### Other notes

Many errors and warnings are loaded when the Block Widget editor page is loaded, but unsure if they are related to this issue.

Edit: @cometgrrl could not reproduce on Core, so this appears to be a dotcom issue.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

### Workaround details

Unworkable if user only has a mobile device.

Avoidable if user is using a desktop or tablet sized browser.

**Comment by cometgrrl** [comment] 2022-01-12 18:23
I was able to reproduce this on my iPhone (using Chrome), the screen is unusable.

**Comment by worldomonation** [comment] 2022-01-12 22:15
@Automattic/team-calypso I was informed that Team Calypso helps with this feature - could I request someone look into this?

**Comment by nagpai** [comment] 2022-01-15 03:31
Reported in #4682098-zen

**Comment by nagpai** [comment] 2022-01-15 03:47
I was unable to replicate the issue on a local WP site. (self hosted test) 
Issue seems to be related to Gutenberg 12.3.2 

On a localWP test site, I was not able to replicate it with the Gutenberg plugin disabled. (older Gutenberg version bundled with 5.8.2) . 

On enabling Gutenberg 12.3.2 plugin, the widgets tend to show a background in desktop view, but then shows blank in mobile screen viewport.

**Comment by nagpai** [comment] 2022-01-15 03:49
Workaround - open the widget editor from the customizer (for non FSE themes ) 
My Site(s) >> Appearance >> Customize >> Widgets.

**Comment by nagpai** [comment] 2022-01-15 09:47
Reported bug here in core Gutenberg repo 
https://github.com/WordPress/gutenberg/issues/38002

**Comment by nagpai** [comment] 2022-02-03 13:04
Fix expected in Gutenberg 12.5 as per the patch in core here:
https://github.com/WordPress/gutenberg/issues/38002

**Comment by nagpai** [comment] 2022-02-05 11:59
This is now fixed, with Gutenberg 12.5 up and running! I tested this on simple as well as atomic sites.

**Closed as completed by nagpai** 2022-02-05 11:59 UTC
Labels: Bug, [Feature Group] Support, [Status] Core Fix Needed, Mobile Web, [Status] Fix Inbound, Needs triage, Block Widgets
