### ISSUE TITLE
Checkout: ToS Foldable card rerenders itself causing it to close immediately after opening

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#86074] opened 2024-01-05 20:54 UTC
### Quick summary

The new foldable card implementation seems to have a bug that causes the card to collapse after opening it if you open the card too early during the checkout render. I suspect state above the ToS card forces a rerender.

It may be best to consider hiding the foldable card until the checkout cart loading state is completed, then render the ToS foldable card.

### Steps to reproduce

1. Go to checkout
2. Quickly scroll down and click on the 'Read more' header
3. The card should open then collapse shortly after

### What you expected to happen

I expect the card to stay open until I click to close it again.

### What actually happened

The card collapses right away.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by maciejpilarski** [comment] 2024-01-08 20:05
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to reproduce the issue on either the latest version of Chrome or Safari. The tab stays open.

📌 ACTIONS
– Requested author feedback

📌 Message to Author
Hi @jjchrisdiehl ! 👋 

Thanks for the report. I was not able to reproduce the issue on my side. Does the problem still occur on your side? If yes, are you able to tell us more about your browser/testing environment?

Thanks in advance!

**Comment by sirbrillig** [comment] 2024-01-09 15:59
This will be fixed by https://github.com/Automattic/wp-calypso/pull/86077

**Closed as completed** 2024-01-09 21:01 UTC
Labels: Bug, [Pri] High, Triaged, [Status] Priority Review Triggered
