### ISSUE TITLE
Permafail E2E: Translations for Welcome Guide

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#74985] opened 2023-03-27 19:34 UTC
### Spec file

specs/i18n/i18n__editor.ts

### TeamCity ID

9708521

### Logs

```
locator.waitFor: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for frameLocator('iframe.is-loaded').locator('body.block-editor-page').locator('.wpcom-tour-kit-step-card__heading:has-text("Welcome to WordPress!")') to be visible
============================================================
at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/i18n/i18n__editor.ts:309:7)
```

**Comment by worldomonation** [comment] 2023-03-27 19:34
![image](https://user-images.githubusercontent.com/6549265/228047678-9aeb6d11-2fec-47d4-a023-5b02047d3621.png)

**Comment by worldomonation** [comment] 2023-03-27 19:36
@yuliyan Just a heads up that this started failing on the i18n tests run on 2023/03/22. Not sure what changed, and I don't expect that you'd drop everything to fix this, just a heads up!

I have been looking at the EditorPage component in the last week or so, and the existing work to un-iframe the editor in https://github.com/Automattic/wp-calypso/pull/74384 should help make the EditorWelcomeGuideComponent more reliable once the iframe is removed.

**Comment by yuliyan** [comment] 2023-03-28 12:22
@worldomonation, thank you for the ping! I've looked into the failing tests and it seems like the problem is within the Welcome Guide component, which is currently not showing when editing posts/pages.

It seems like the issue has been introduced in https://github.com/Automattic/wp-calypso/pull/74242 and doesn't seem to be the intended behavior.

I've reported it to the team who worked on that PR.

**Comment by yuliyan** [comment] 2023-03-29 09:15
The problem has been resolved with https://github.com/Automattic/wp-calypso/pull/75043.

**Closed as completed by yuliyan** 2023-03-29 09:15 UTC
Labels: Flaky E2E
