### ISSUE TITLE
Focused Launch: 404 error when opening Domain Details view too early

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#49871] opened 2021-02-09 09:34 UTC
## What

Domain details view in Focused Launch appears broken to the user if visited too early (e.g. when data from backend hasn't loaded yet)

1. Open Focused Launch modal
2. Quickly click on "view all domains" in order to open domain details view
3. Notice the 404 error in the console about the domains rest API

https://user-images.githubusercontent.com/1083581/107344093-5d830780-6ac2-11eb-8196-1629e740ba64.mp4

## Why

It seems like we make the request `https://public-api.wordpress.com/rest/v1.3/domains/[DOMAIN}/is-available?is_cart_pre_check=true` too early, when `DOMAIN` is still not defined / an empty string.

## A/C

I can see 2 ways of solving this issue:

Either we solve it in the context of Focused Launch flow: 

- [ ] Disable domain details link until data has loaded

Or in the Domain Picker package:

- [ ] Wait before hitting the APIs until the `DOMAIN` is a valid value.

## Context

We should also apply similar changes for the Plan Details view / plans-grid package, in case.

**Comment by razvanpapadopol** [comment] 2021-02-11 14:10
a fix is going to be released in #49961

**Comment by JoshuaGoode** [comment] 2021-02-15 17:35
Stumbled upon this during triaging.

Appears the fix has been released and merged via Editing Toolkit 2.19 - #49961

Tested and could not reproduce the issue.

Labeling this one as `[Closed] Fixed ` and closing

**Closed as completed** 2021-02-15 17:35 UTC
Labels: Bug, [Pri] High, [Feature Group] Emails & Domains, Focused Launch, Triaged

**Comment by ciampo** [comment] 2021-02-15 18:33
Thank you @JoshuaGoode !
