### ISSUE TITLE
Sharing > Sharing Buttons should not show "Reblog" for Jetpack sites

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#12787] opened 2017-04-04 21:25 UTC
On Sharing > Sharing Buttons, we show the "Reblog" label for Jetpack sites, but there is currently no Reblog functionality available for them.

![sharing_ _jp2_ _wordpress_com](https://cloud.githubusercontent.com/assets/108942/24679573/d11f893e-194a-11e7-846f-21f1baf916f7.png)

**Comment by lancewillett** [comment] 2017-04-06 18:09
Closing as duplicate of #9816

**Closed by lancewillett** 2017-04-06 18:09 UTC
Labels: Jetpack, Sharing, [Type] Bug
