### ISSUE TITLE
Launch flow: Flashes a brief error when checking out a plan

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#47900] opened 2020-12-01 11:47 UTC
**Steps to repro**

1. Create a site via Gutenberg onboarding
2. Click on launch from the editor
3. Add a paid plan to cart, and click on the launch button.

**What I expected**

To be taken to checkout without errors

**What happened**

A brief error was flashed before being shown the checkout

![lf](https://user-images.githubusercontent.com/1269602/100736931-794e9b00-33f9-11eb-9de5-680552ccb9f6.gif)

**Comment by niranjan-uma-shankar** [comment] 2020-12-01 11:53
cc @Automattic/luna for triaging.

**Comment by ciampo** [comment] 2020-12-01 15:26
Looks like a duplicate of #47150 — closing this issue in favor of the original one.

Feel free to re-open in case it's actually not a duplicate :)

**Closed as completed** 2020-12-01 15:27 UTC
Labels: Feature [Launch], [Goal] New Onboarding
