### ISSUE TITLE
Deleted wp import still appears processing in wp-calypso

### ISSUE THREAD

**Issue by samanthainnes** [Automattic/wp-calypso#17340] opened 2017-08-18 15:46 UTC
#### Steps to reproduce
1. Starting at URL: https://example.wordpress.com/wp-admin/admin.php?import=wordpress
2. Stalled WordPress import was deleted in wp-admin.

#### What I expected
Expected to see the deleted job cleared in Calypso.

#### What happened instead
https://wordpress.com/settings/import/example.com
The spinner indicates the job is still processing. Concerning to user.

#### Browser / OS version
Google Chrome / OS X Yosemite

#### Screenshot / Video
![dframe-calypso](https://user-images.githubusercontent.com/30804862/29466165-ccb09922-8409-11e7-9a6d-114dc9ea6fa2.png)

#### Context / Source

We'd also love to know how you found the bug: 
Live chat: `583384-hc`
Also reported in: `581691-hc`

**Comment by guicmazeredo** [comment] 2017-08-22 15:17
I have a user with the same case. I'm adding the information here so there is more material to investigate.

**Summary**
The user tried to import from Medium through Calypso and the import process got stuck for more than 5 days and there is no button to stop/cancel.

**Steps to reproduce**
I'm not sure because I tried to import the same file on my test site and worked smoothly. 

**Relevant links**
Site: andylindquist.wordpress.com
User RC: https://mc.a8c.com/tools/reportcard/user/?id=76951008 
Blog RC: https://mc.a8c.com/tools/reportcard/blog/?blog_id=132793236
SA: https://wordpress.com/wp-admin/network/wpcom-paid-upgrades.php?action=search&username=andylindquist

**Screenshot**
![](https://cl.ly/0h0T2f281U2A)

**Comment by RealCarFax** [comment] 2017-08-24 14:54
I've encountered this issue on a user's site as well: supportdrivenbeta.wordpress.com
Live Chat: 576651-hc
Ticket: 634790-zd-woothemes

When I tried to import their content on my test site it hung up there too! My test site is carissastrial.com

Both sites are showing the loading icon indefinitely (been going on for over a week on both) with no option to cancel or clear that out. I've deleted the imports on both sites too.

**Comment by RealCarFax** [comment] 2017-08-24 16:25
This is also happening on meccacentercom.wordpress.com
Live Chat: 597227-hc

**Comment by isocialtish** [comment] 2017-09-04 20:07
I encountered this issue in:
Ticket: 648025-zd-woothemes

Seeing the loading icon indefinitely and there is no option to cancel the import in WP-ADMIN

**Comment by supernovia** [comment] 2017-09-06 14:48
Encountered here: #875687-tqr

**Comment by lancewillett** [comment] 2017-09-06 16:49
Thanks for these reports, please keep adding as you encounter them.

Is it fixed if the customer does a hard refresh, or logs in and out of Calypso?

Worth investigating more to see if there are JS errors in the console, pattern for the OS and browser versions, etc.

**Comment by KokkieH** [comment] 2017-09-11 22:44
Another case in 876096-f

I've asked the user to try the troubleshooting steps suggested above to see if we can get some more information on this.

**Comment by otpidusprime** [comment] 2017-09-18 11:44
Encountered this case here: [#686900-zen](https://woothemes.zendesk.com/agent/tickets/686900)

**Comment by gemmagarner** [comment] 2017-09-21 11:31
Another report in #877287-f

I also have the same issue on my personal test site and haven't been able to clear the loading icon with a hard refresh or logging out/in again.

**Comment by jaymendoza** [comment] 2017-10-04 18:13
Seeing this issue in 717861-zd-woothemes

There is no job to clear in wp-admin

**Comment by blazevivan** [comment] 2017-10-17 12:39
Same case - 736608 in ZD

I was able to delete the job from wp-admin, but Calypso is still processing the import.

**Comment by molszewska** [comment] 2017-11-08 08:57
Same case:
Live chat: 963662-hc
site: https://inredningsfrun.wordpress.com

**Comment by otpidusprime** [comment] 2017-11-15 13:22
Same case:
Chat: https://mc.a8c.com/support-stats/happychat/transcript.php?id=1032766
Ticket: https://woothemes.zendesk.com/agent/tickets/793761
Site: https://physics.com.hk/

**Comment by gemmagarner** [comment] 2017-12-13 09:06
Another report in 885866-f (loading icon spinning indefinitely).

**Comment by gemmagarner** [comment] 2017-12-15 09:52
Same issue in 886003-f

**Comment by GeoJunkie** [comment] 2017-12-19 20:59
Same issue in 857591-zen. I see it also when I SU into the account, with the spinning icon.

**Comment by otpidusprime** [comment] 2017-12-20 06:43
Another report: 858589-zd-woothemes

Cannot find any job to clear via WP-Admin.

**Comment by gemmagarner** [comment] 2017-12-27 16:51
886744-f

Cleared an import through WP Admin but the loading icon is still spinning.

**Comment by hacchism** [comment] 2018-01-03 04:34
Another report: https://ja.forums.wordpress.com/topic/2943?replies=1
Site: n2n2nori.wordpress.com

Cannot find any job to clear via WP-Admin.

**Comment by otpidusprime** [comment] 2018-01-05 10:36
Another report: 882354-zd-woothemes
Site: shuizmz.wordpress.com

Cannot find any job to clear via WP-Admin.

**Comment by gemmagarner** [comment] 2018-01-10 09:28
883537-zen

Cleared the import through WP Admin but the loading icon is still spinning.

**Comment by simison** [comment] 2018-01-10 12:04
Another case: 686900-zen

Deleted import job from wp-admin but Calypso is still spinning. Asked for the file they attempted to import so that I could have a closer look.

I can see a weird response coming from the API. Note 0 count for both "completed" and "total":

URL: `https://public-api.wordpress.com/rest/v1.1/sites/###SITE_ID###/imports/`

```json
{
    "code": 200,
    "headers": [{
        "name": "Content-Type",
        "value": "application\/json"
    }],
    "body": {
        "importId": "######",
        "siteId": "######,
        "type": "wordpress",
        "importStatus": "importing",
        "customData": {
            "sourceAuthors": [{
                "login": "user",
                "name": "###USERNAME###"
            }],
            "title": "###USERNAME###"
        },
        "progress": {
            "post": {
                "completed": 0,
                "total": 0
            },
            "page": {
                "completed": 0,
                "total": 0
            },
            "attachment": {
                "completed": 0,
                "total": 0
            },
            "comment": {
                "completed": 0,
                "total": 0
            }
        }
    }
}
```

**Comment by simison** [comment] 2018-01-10 14:08
I checked two more users from tickets 883537-zen and 882354-zen (both have spinning cicles still under wp-import).

I can see they both get 0-responses from the API:

```
        "progress": {
            "post": {
                "completed": 0,
                "total": 0
            },
            "page": {
                "completed": 0,
                "total": 0
            },
            "attachment": {
                "completed": 0,
                "total": 0
            },
            "comment": {
                "completed": 0,
                "total": 0
            }
        }
```

Hope this helps!

**Comment by spncrb** [comment] 2018-01-10 23:26
Another in 1499769-hc - site is simplychurch167385423.wordpress.com

**Comment by simison** [comment] 2018-01-11 14:18
Another in `893301-zen`

Based on info at above ticket I found a way to replicate this.

1. Create a private new wp.com blog, free plan
1. Have a import file bigger than 15 MB (tested with 25,7 MB)
1. Upload it at `https://wordpress.com/settings/import/:site` and start import
1. Observe spinner appearing, no info about number of posts or media
1. Observe API from `https://public-api.wordpress.com/rest/v1.1/sites/#######/imports/?http_envelope=1&locale=en-gb` returning:
    ```
    {
        "code": 200,
        "headers": [{
            "name": "Content-Type",
            "value": "application\/json"
        }],
        "body": {
            "importId": "5a576e9055422",
            "siteId": #######,
            "type": "wordpress",
            "importStatus": "importing",
            "customData": {
                "sourceAuthors": [{
                    "login": "",
                    "name": ""
                }]
            },
            "progress": {
                "post": {
                    "completed": 0,
                    "total": 0
                },
                "page": {
                    "completed": 0,
                    "total": 0
                },
                "attachment": {
                    "completed": 0,
                    "total": 0
                },
                "comment": {
                    "completed": 0,
                    "total": 0
                }
            }
        }
    }
    ```
1. Spinner is stuck:
    ![screen shot 2018-01-11 at 16 15 11](https://user-images.githubusercontent.com/87168/34829832-a05b0c50-f6ea-11e7-9bc3-6f563148c83f.png)
1. Go to `#######.wordpress.com/wp-admin/admin.php?import=wordpress` and observe "job completed"

**Comment by gemmagarner** [comment] 2018-01-11 14:43
Another report in 887899-f

Cleared the import through WP Admin but the loading icon is still spinning.

**Comment by hacchism** [comment] 2018-01-12 08:28
Another in https://ja.forums.wordpress.com/topic/2968
There is no job to clear in wp-admin

**Comment by erricgunawan** [comment] 2018-01-22 10:29
Another report in 913876-zen/1504085-hc.

There is no job to clear in WP-Admin. 
A sample of the XML file has been sent and when I tried to import to my private site, it works well (no spinning circle and the import is done).

**Comment by spncrb** [comment] 2018-01-31 19:44
Another report in 903916-zen

**Comment by rachelmcr** [comment] 2018-03-05 15:06
I just ran into this issue while using the WordPress.com desktop app (macOS 10.13.3/desktop app version 3.2.0). It's especially frustrating there as you have to leave the app entirely to get to WP Admin as a workaround.

**Comment by thebud15** [comment] 2018-03-07 21:54
There was not import to clear in WP-Admin as shown here in this ticket: 1002784-zen. I'll have this user try the import again through WP Admin.

**Comment by allykmyta** [comment] 2018-03-09 21:42
I encountered this issue in:
Ticket: #1007174-zen

Seeing the loading icon indefinitely and there is no job to clear in WP-ADMIN. Will ask user to send a sample import file so I am able to upload and test.

**Comment by MindyPostoff** [comment] 2018-03-26 14:11
I encountered this issue in:
Ticket: 1039668-zd-woothemes

Seeing the loading icon indefinitely and there is no option to cancel the import in WP-ADMIN

**Comment by lancewillett** [comment] 2018-03-26 14:20
@jblz Jeff, could @Automattic/delta-samus take a look at this one please?

**Comment by bisko** [comment] 2018-03-26 17:26
@lancewillett unfortunately the REST API endpoint has a separate way of keeping the status of the current import, which can get desynchronized with the one that the `wp-admin` interface uses. 

We'll handle that in an iteration in our imports improvement efforts!

**Comment by bisko** [comment] 2018-03-26 19:21
This should be fixed with r172321-wpcom . If a similar issue occurs in the future, I'd love to take a look!

**Comment by jesscga** [comment] 2018-06-05 18:18
Appears to have happened in 3614038-hc

Suggested that user try importing from wp-admin for now, waiting to hear back

**Comment by erricgunawan** [comment] 2018-06-06 01:18
User in 1204167-zen (follow up from 3614038-hc reported by @jesscga above) reported that:

> Everything is work well now. Tks for your great support.

**Comment by scosgro** [comment] 2018-06-14 19:59
User in 4353955-hc has an import that has been spinning for "over a week."

Checked WP-Admin, and don't see any activity. Asked them try to import through WP-Admin, but they were unresponsive the whole chat.

**Comment by lancewillett** [comment] 2018-07-04 00:03
Please open a new issue for new reports as a lot has changed in the interface since the original report. Thanks!

**Closed by lancewillett** 2018-07-04 00:03 UTC
Labels: Import, OSS Citizen, [Pri] High, [Type] Bug
