### ISSUE TITLE
Mobile Browser: block color setting is not working

### ISSUE THREAD

**Issue by rinazrina** [Automattic/wp-calypso#64741] opened 2022-06-17 15:21 UTC
### Quick summary

Clicking the Color Setting on any blocks via mobile browser doesn't do anything. 

### Steps to reproduce

1. Open a mobile browser. I've checked this with Chrome browser.
2. Open WordPress.com > My Sites > Pages or Posts > open a new page/post or open an existing page/post.
3. Add a Paragraph block or any block that has the Color setting, such as Heading block or Buttons block.
4. Click the Settings icon on the top right > under the Block tab, locate the Color setting.
5. Click on Text, Background, or Link. It doesn't open the color options. 

### What you expected to happen

When clicking the Text, Background or Link on the Color setting, it should open the color options. 

### What actually happened

Clicking the Text, Background, or Link on the Color setting doesn't do anything. 

<img width="434" alt="Markup 2022-06-17 at 23 11 05" src="https://user-images.githubusercontent.com/33721365/174326543-4cb9150e-cdde-4047-81aa-459a7c2ced11.png">

### Context

User report: 

- [ ] 5304418-zd-woothemes 

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No. Tested thin Blank Canvas, Twenty Twenty-Two, and Karuna. 

### Browser, operating system and other notes

Chrome

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Change the block color via the mobile app or desktop.

**Comment by rinazrina** [comment] 2022-06-20 05:40
Another report: 29963214-hc

**Comment by filipanoscampos** [comment] 2022-06-28 14:18
Here is another report:

- [ ] 5329917-zd-woothemes

Both I and @csabarakasz were able to reproduce and Csaba shared the following recording:

https://user-images.githubusercontent.com/2540430/176202045-fe99692d-47d4-44d7-abe5-d3220cf83b58.mp4

**Comment by galakhyati** [comment] 2022-06-30 11:38
📌 HOUSEKEEPING
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate the issue on simple and Atomic sites, whereas the feature works on a Jurassic ninja site.

**Comment by sejas** [comment] 2022-08-25 14:23
I couldn't replicate this issue on my iPhone (iOS 15,0,2) nor using an android simulator browserstack (Android v12).

**Comment by mpkelly** [comment] 2022-10-19 04:37
I am also unable to reproduce this issue using a Pixel 6. @rinazrina, @filipanoscampos, can you retest this?

**Comment by rinazrina** [comment] 2022-10-19 06:07
Thanks for checking, all! I'm no longer able to reproduce the issue. I'm using Android 12. The color setting is working as expected now.

**Comment by sejas** [comment] 2022-10-24 08:56
@rinazrina , Thanks for confirming,  I'll close this issue 👌

**Closed as completed by sejas** 2022-10-24 08:56 UTC
Labels: Bug, [Pri] Normal, Mobile Web, Needs triage, Build Maintenance
