### ISSUE TITLE
NUX: Signup: "Do you want to register" subdomain doesn't persist

### ISSUE THREAD

**Issue by sararosso** [Automattic/wp-calypso#5727] opened 2016-06-01 13:21 UTC
#### Steps to reproduce
1. Starting at URL: any WordPress.com site which doesn't exist. 

(I know this will affect only a small percentage of users but worth noting the experience is broken.)

You see: 

<img width="978" alt="screen shot 2016-06-01 at 3 00 49 pm" src="https://cloud.githubusercontent.com/assets/4126822/15710848/153a3ae6-280c-11e6-8e04-c96ab1dd8b34.png">

If you click on "Do you want to register ........wordpress.com?" it starts NUX. 

#### What I expected

That it will remember the subdomain from earlier. 

#### What happened instead

It doesn't. 

The first click takes you to: 
https://wordpress.com/start?ref=typo&new=ksjdflkajsldfa

and ends up redirecting to : https://wordpress.com/start/domains

<img width="1021" alt="screen shot 2016-06-01 at 3 01 05 pm" src="https://cloud.githubusercontent.com/assets/4126822/15710900/41916f9c-280c-11e6-8dc5-ec2d64cf21f0.png">

**Comment by lancewillett** [comment] 2016-06-01 15:34
I think this is a duplicate of #5462.

**Comment by sararosso** [comment] 2016-06-01 15:37
Good catch! Feel free to close.

**Closed** 2016-06-01 15:40 UTC
Labels: NUX, Signup, [Type] Bug
