### ISSUE TITLE
[Bug]: Popover component styling breaks on smaller browser sizes

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#58927] opened 2021-12-07 21:06 UTC
### Quick summary

The [Popover component's](https://wpcalypso.wordpress.com/devdocs/design/popover), and subsequently the InfoPopover component, functionality breaks when used in conjunction with media queries that hide the parent button that the Popover is linked to. This tends to happen on pages like Plans where the number of columns shrinks as the browser width is narrowed.

It appears that when the parent button is set to `display: none` _while the Popover is toggled to 'open'_, the Popover rerenders but at position `0,0`.

### Steps to reproduce

Start at https://wordpress.com/plans

Click on one of the info icons to toggle a Popover component:

![image](https://user-images.githubusercontent.com/16580129/145097354-f296bf69-f92b-4455-afd0-fb2c3033f1e4.png)

Shrink the browser window down to a smaller size, roughly around 960px and observe the Popover position being rerendered at 0,0:

![image](https://user-images.githubusercontent.com/16580129/145097554-a4d74851-68e5-4950-ab79-c51f4fcd330b.png)

### What you expected to happen

In this case, I expect the Popover to be toggled off if the parent element's display attribute is set to `none`. Ie, if the button is no longer showing then the Popover should be unmounted.

### What actually happened

Instead, the Popover is rerendered, but I suspect it cannot find its parent button and instead just sets its position to the upper left of the window.

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by mmtr** [comment] 2022-05-02 14:49
@sejas and I have been taking a look at this today, and it looks like the issue is no longer reproducible since the Plans page uses now a new design where popovers are displayed on hover.

We also took at look at the other pages to check if the issue was happening in other places, but we didn't find anything.

So we think we can close this one out. Please, feel free to reopen if we missed any page where the issue is still happening.

**Closed as completed by mmtr** 2022-05-02 14:49 UTC
Labels: Bug, [Pri] Low, Triaged, Build Maintenance
