### ISSUE TITLE
Popover: Occasionally fails to auto-position itself

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#21129] opened 2017-12-28 16:03 UTC
Occasionally (@michaeldcain and I have seen this in the posts list with the ellipsis menus), a `Popover` will show off-screen (its auto-positioning feature does not correctly adjust for the viewport boundaries) or it will not correctly adjust its position when the window scrolls or resizes.

I wasn't able to trigger this condition reliably, but I suspect it is because of the following code.

Each time **any** popover instance unmounts, we unbind the **global** event handlers that update the viewport boundaries:

- [`Popover#componentWillUnmount`](https://github.com/Automattic/wp-calypso/blob/61e1a136/client/components/popover/index.jsx#L146)
- [`util.unbindWindowListeners`](https://github.com/Automattic/wp-calypso/blob/61e1a136/client/components/popover/util.js#L66)

But really, these event handlers should only be unbound when there are no more `Popover` instances mounted.

A way to check whether this code is the cause of this issue would be to uncomment the `unbindWindowListeners()` call and see if the issue reappears.

**Comment by rachelmcr** [comment] 2018-08-28 11:37
I tested the popover auto-positioning on the blog posts page, with posts' sharing section expanded or collapsed. Cases I tested:

- Open the popover and scroll so the popover has to adjust position (opening up v. down).
- Open the popover and resize the window height so the popover has to adjust position (opening up v. down).
- Open the popover and resize the window so the popover is of screen. Scroll to the popover and ensure it adjusts position to be on screen.

In each case, I couldn't trigger the issue. Since there aren't reliable repro steps I'm hesitant to close this as resolved without confirmation. @michaeldcain do you think this needs to stay open?

**Comment by michaeldcain** [comment] 2018-08-28 13:36
@rachelmcr I was able to reproduce this by loading the posts list, scrolling down the page, and then clicking a popover near the bottom of the window:

![popover](https://user-images.githubusercontent.com/942359/44726250-4e9c6c00-aaa5-11e8-8853-5c6e9466d3aa.gif)

That being said, continuing to scroll the window immediately causes a re-render of the popover in the correct direction, so I'd say this is a very low priority bug. I'll try James's theory this week to see if there's an easy solution.

**Comment by mattsherman** [comment] 2018-08-28 15:05
Agreed. This is low priority, but if there is an easy fix, it would be nice to address.

**Comment by michaeldcain** [comment] 2021-03-16 15:52
Can't seem to reproduce. Closing.

**Closed by michaeldcain** 2021-03-16 15:52 UTC
Labels: Components, [Pri] Low, [Type] Bug
