### ISSUE TITLE
Page Freezing While Scrolling Through Posts List

### ISSUE THREAD

**Issue by sageBrownell** [Automattic/wp-calypso#12505] opened 2017-03-24 15:26 UTC
#### Steps to reproduce
1. Starting at URL: (see p2UL9c-3n9-p2)
2. Scroll through the user's posts list in Calypso

#### What I expected
The posts would load as per normal, allowing access to the older posts.

#### What happened instead
Eventually, the entire page freezes and js errors appears in the console. (internal ref: 18ee5-pb)

#### Browser / OS version
Chrome 56

#### Screenshot / Video
![screen-shot-2017-03-23-at-9-00-59-pm](https://cloud.githubusercontent.com/assets/3833099/24300811/e7480fda-106a-11e7-8773-2fca13588f40.png)

#### Context / Source
#user-report

**Comment by rachelmcr** [comment] 2017-11-27 18:48
#bug-scrub

I retested the issue as described with this user's posts list and couldn't reproduce. I successfully scrolled through the posts list to the first list on the site without any freezing. Closing as no longer reproducible.

Tested in Mac OS X 10.12.6, Chrome 62.

**Closed by rachelmcr** 2017-11-27 18:48 UTC
Labels: OSS Citizen, Posts, [Type] Bug
