### ISSUE TITLE
Comments form in Pages template showing "NaN responses" when opening the page in Site Editor

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#84034] opened 2023-11-09 04:39 UTC
### Quick summary

When opening a page via Site Editor (the URL will look like `*.wordpress.com/wp-admin/site-editor.php?postType=page&postId=<id>)`, the Comments block will show "NaN responses" and a never-ending loading icon.

### Steps to reproduce

1. Create a new site (wordpress.com/start).
2. Choose a domain.
3. Choose a plan.
4. In the Goals selection, just click "Skip to dashboard".
5. Open Appearance -> Editor.
6. Click Pages.
7. Open the auto-generated About page.
8. Scroll to the bottom of the page.

### What you expected to happen

The Comments block to make sense.

### What actually happened

It shows "NaN responses" with a never-ending spinning icon, which looks broken.

<img width="1015" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/013fdbc1-2978-42d7-9c7f-f91ff3b6de8d">

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

It does not happen in a fresh Jurassic Ninja site, so this doesn't look like a Core/Gutenberg issue.

**Comment by retnonindya** [comment] 2023-11-10 08:42
I can replicate the issue too when I did a CfT on Assembler "Add New Pages" that I shared here:
pdtkmj-20J-p2#comment-3591

**Comment by liviopv** [comment] 2023-11-18 15:04
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Simple, GB 17.0.2
![CleanShot 2023-11-18 at 15 58 32@2x](https://github.com/Automattic/wp-calypso/assets/14153300/05889631-d483-4186-9709-f1f6383f6fbe)

Atomic, GB 17.0.2
![CleanShot 2023-11-18 at 16 03 11@2x](https://github.com/Automattic/wp-calypso/assets/14153300/23e9f01b-8eca-41bd-9aee-f5bfdacc47d7)


📌 ACTIONS
- Triaged

**Comment by arcangelini** [comment] 2023-12-05 11:41
### Tested this with Simple, Atomic, and Jetpack sites.

The issue is only happening in Simple.

### Tested with Verbum, Highlander, and just plain comments from WordPress core.

All of them produced the same results

### Hypothesis

Since Simple sites need to access comments using the public-api endpoint the core endpoint would not return any data and thus producing the results shown above.

I think we will need to intersect that apiFetch with some middleware to rewrite to comments. I am not sure if this was in place before and broke or if it never existed. Here is the API call from the block - https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/comments-title/edit.js#L67-L74

**Comment by miksansegundo** [comment] 2023-12-06 01:28
A fix is on the way in D131041-code

**Comment by taipeicoder** [comment] 2024-01-17 03:46
Closing this as D131041-code has been merged for a while now. Please reopen if the issue persists.

**Closed as completed by taipeicoder** 2024-01-17 03:46 UTC
Labels: Bug, [Pri] High, [Feature] Comments, Triaged, [Feature] Full Site Editor, Customer report [LEGACY], [Platform] Simple, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience
