### ISSUE TITLE
Unable to keep Editor's View - Fullscreen mode disabled

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/wp-calypso#69680] opened 2022-11-02 03:44 UTC
### Quick summary

Cannot keep the editor's View → Fullscreen mode unchecked. It will work while editing a post/page, but after publish and create a new post/page, it shows checked again. 

![Alt text](https://d.pr/i/a3sy4Y/QOQjcGDf63+)

### Steps to reproduce

1. Create/Edit a page/ost. 
2. Uncheck "Fullscreen mode" 
3. Publish page/post.
4. Create/Edit a post/page again. 
5. Check "Fullscreen mode" is now checked again. 

### What you expected to happen

For the fullscreen mode to remain unchecked. 

### What actually happened

The fullscreen mode is enabled each time.

**Comment by cuemarie** [comment] 2022-11-10 23:23
📌 ACTIONS
- Closed as duplicate of  #64324

**Closed as completed by cuemarie** 2022-11-10 23:23 UTC
Labels: Bug, [Feature] Post/Page Editor, Triaged
