### ISSUE TITLE
Customizer: Cannot select Visibility Options in Widget

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#7240] opened 2016-08-03 04:44 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/customize/
2. Select a site
3. Go to Widgets
4. Add any widget
5. Click Visibility
6. Try changing options

#### What I expected
The options should stay selected

#### What happened instead
The options reset

#### Browser / OS version
Chrome / Mac but users have said this happens in various browsers.

#### Screenshot / Video
https://cloudup.com/ctJb99cCPEN

#### Context / Source
#user-report

**Comment by kriskarkoski** [comment] 2016-08-04 01:27
Confirmed this issue occurs in Safari and Firefox on Mac as well. The setting seems to be cleared when the save and page refresh happens (almost immediately in my testing). The Widget Visibility still works as expected in WP Admin.

**Comment by mattwiebe** [comment] 2016-08-04 17:29
Closing here since it's not really a Calypso thing. a12s will see where it's moved above.

**Closed by mattwiebe** 2016-08-04 17:29 UTC
Labels: Customizer, [Pri] High, [Type] Bug
