### ISSUE TITLE
Cart: Graphic glitch in the modal window (vertical grey stripe is displayed next to the prices)

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#60360] opened 2022-01-22 12:27 UTC
### Steps to reproduce

- Add an item to the cart (such as a plan or a domain)
- Exit the cart but keep the items there
- Click the 🛒 cart icon in the toolbar to see the preview of what's there

### What you expected to happen

No vertical grey stripe should display to the right of the prices

### What actually happened

An odd vertical grey stripe is displayed to the right of the prices

Free Plan Site | Personal Plan Site 
--- | --- 
![image](https://user-images.githubusercontent.com/39308239/150638468-fd81d64b-e9b1-44f4-824e-f68f7252f4bd.png) |  ![image](https://user-images.githubusercontent.com/39308239/150638480-d9cca516-f52a-4025-ae1c-2096437a995d.png)

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

macOS Monterrey 12.1 with Chrome 97

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by zdenys** [comment] 2022-01-22 12:30
Seems to be an unnecessary padding on the `ul` element.

![image](https://user-images.githubusercontent.com/39308239/150638584-ab9d7201-74c9-4ff9-aa28-c11c8c705504.png)

**Comment by Greatdane** [comment] 2022-02-24 05:48
Do you still see this @zdenys - I am unable to replicate;

<img width="588" alt="Markup 2022-02-24 at 14 47 36" src="https://user-images.githubusercontent.com/5075840/155465661-13beed98-81fd-4453-a691-a9b51e5ead90.png">

**Comment by zdenys** [comment] 2022-02-28 07:34
@Greatdane I can still reproduce with macOS Monterrey 12.2.1 with Chrome Version 98.0.4758.109 (Official Build) (x86_64)

![image](https://user-images.githubusercontent.com/39308239/155942284-c0327577-5dbe-47ea-a50e-7b73c3c5562b.png)

**Comment by Greatdane** [comment] 2022-03-02 06:50
Putting back in the triage queue for someone else to test - I am unable to reproduce.

**Comment by edequalsawesome** [comment] 2022-03-10 20:03
I wasn't able to duplicate this on my computer (Version 99.0.4844.51 (arm64)), but @msilbers was able to duplicate on Version 98.0.4758.80 (Official Build) (x86_64) and the latest release of Chrome:

<img width="562" alt="Screen Shot 2022-03-10 at 3 00 58 PM" src="https://user-images.githubusercontent.com/4000628/157745342-91e8d960-8334-4ca4-8479-71f3f0c3c6fe.png">

@zdenys Are you still seeing this, too? If so, are you using an Intel Mac or an M1 Mac?

**Comment by zdenys** [comment] 2022-03-11 06:55
>@zdenys Are you still seeing this, too? If so, are you using an Intel Mac or an M1 Mac?

Still seeing with MacBook Pro (16-inch, 2019) 2,3 GHz 8-Core Intel Core i9 macOS Monterrey 12.2.1 with Google Chrome Version 99.0.4844.51 (Official Build) (x86_64).

**Comment by inaikem** [comment] 2022-04-06 03:14
Internal ping to help get this allocated to a team here: p1649214825571449-slack-C7YPUHBB2

**Comment by jsnajdr** [comment] 2022-04-06 06:40
This is something that @sirbrillig will be interested in, as he implemented the mini-cart styles. I can't reproduce the bug and I'm not sure that the suspected padding is really a padding. When the list of items is too long to fit into the cart modal, this "padding" is exactly the place where a scrollbar would appear. So maybe it's a scrollbar glitch that appears only in some browsers on certain platforms, possibly depending on OS-level settings about scrolling?

**Comment by sirbrillig** [comment] 2022-04-06 14:55
@jsnajdr is right; what you're seeing is the scrollbar. It appears only when the list of items is too tall and/or your OS settings display scrollbars (Mac OS defaults to hiding them). I'm not sure what the best UI fix would be for this... I can see if there's a way to hide the scrollbar even if the OS is set to display one, but that might be an accessibility problem. Maybe there's a way to style the scrollbar to make it more obvious what it is. I'll experiment, but suggestions are welcome!

**Comment by sirbrillig** [comment] 2022-04-08 21:18
I think I have a solution: https://github.com/Automattic/wp-calypso/pull/62642

**Closed as completed** 2022-04-13 19:52 UTC
Labels: Bug, [Pri] Normal, [Feature] Shopping Cart
