### ISSUE TITLE
Discrepancy in Font Size between Editor and Front End.

### ISSUE THREAD

**Issue by saginpj** [Automattic/wp-calypso#86570] opened 2024-01-18 05:07 UTC
### Quick summary

This bug is occurring on websites using themes like Kingsley ([Kingsley Theme](https://wordpress.com/theme/kingsley)), Arbutus, and Geologist.

Upon closer examination, it seems to affect other themes categorized under [Universal Themes](https://wordpress.com/themes/filter/universal-theme/) (Byrne, Videomaker, Arbutus, Geologist).

In the page or post editor, the paragraph font size becomes unexpectedly small, creating readability challenges. However, on the front end, the font size appears normal. Users who regularly add or manage posts find this issue problematic. I've replicated this problem on my test sites; refer the screen recording below.

![font-size-issue](https://github.com/Automattic/wp-calypso/assets/23011051/63f38a15-d85d-46c8-8d95-75592c78c0a2)

To address this, I've provided users with a solution. Navigate to the dashboard → "Appearance" → "Editor" → "Styles." Click "Edit," go to the "Block" section at the bottom right, locate the "Paragraph" block, and set the size according to the front-end size.
![font-size (1)](https://github.com/Automattic/wp-calypso/assets/23011051/1040dcff-9234-4abb-9807-f70b56dfcddd)

However, users on the Starter plan and Free plan will encounter the following message during this process, leading to annoyance due to the lack of style customization support on these plans:

"Your site includes premium styles that are only visible to visitors after upgrading to the Explorer plan or higher."

![image004 (1)](https://github.com/Automattic/wp-calypso/assets/23011051/82cd73ea-4890-4917-beb2-ff0869d17f5c)

### Steps to reproduce

1. Install themes such as Kingsley, Byrne, Videomaker, Arbutus, and Geologist.
2. Create a new post by navigating to the dashboard → posts.
3. In the paragraph, add sample data.

### What you expected to happen

Font size on the paragraph block in both the editor and the frontend will be consistent.

### What actually happened

The paragraph font size is small in the editor, but on the frontend, it is normal. This causes inconsistency.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by saginpj** [comment] 2024-01-18 05:09
- [ ] zen - 7586547
- [ ] zen - 7600903
- [ ] zen - 7604439

**Comment by cat-og** [comment] 2024-01-21 00:44
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this on simple sites only. Of the Blockbase child themes, only Creatio 2 was not affected. 
- Themes affected:
   - Arbutus
   - Videomaker
  - Skivers
  - Bryne
  - Payton
  - Baxter
  - Kerr
  - Jackson
  - Geologist
  - Russell
  - Zoologist

Recording of a post on my site, refreshing the post after switching from Creatio 2 to Zoologist:

https://github.com/Automattic/wp-calypso/assets/86028337/5faea450-c0d9-4aa6-9744-24cbee73ae7a


📌 ACTIONS
- Triaged, tested on all Blockbase Child themes in theme marketplace

**Comment by kathrynwp** [comment] 2024-01-22 21:47
Around the same time this change happened, user reported that a second change occurred in Geologist - Slate, along with the too-small editor text.

Titles are barely legible in the editor:

<img width="873" alt="Edit_Post_‹_Sam_s_Astrology_—_WordPress_com_—_Private_Browsing" src="https://github.com/Automattic/wp-calypso/assets/7662449/9b557720-39a1-4525-af03-bd23aaabee45">

reported in 7590667-zd-a8c

**Comment by cat-og** [comment] 2024-01-23 07:32
7586518-zd-a8c from closed duplicate here: https://github.com/Automattic/themes/issues/7612

**Comment by saginpj** [comment] 2024-01-25 06:55
- [ ] zen - 7604439 (Zoologist theme)
- [ ] zen - 7635308 (Calvin theme)

**Comment by kathrynwp** [comment] 2024-01-25 21:01
Reported here for Byrne: 7634309-zd-a8c

**Comment by jerrysarcastic** [comment] 2024-01-26 22:59
Multiple reports in https://wordpress.com/forums/topic/sudden-blog-font-change-while-editing-creating-new-posts/

**Comment by jerrysarcastic** [comment] 2024-01-27 21:54
Also reported in https://wordpress.com/forums/topic/small-text-on-the-edit-screen/

**Comment by marutim** [comment] 2024-02-15 06:46
Another report with the Geologist theme here: 7742672-zen

**Comment by mdtanjid0** [comment] 2024-03-05 12:41
Another case here:

- [ ]  7831131-zen (needs to be followed up)

Theme Name: Byrne

That happens due to this CSS: 

```
.wp-die-message, p {
    font-size: 13px;
    line-height: 1.5;
    margin: 1em 0;
}

```

![CleanShot 2024-03-05 at 18 41 03@2x](https://github.com/Automattic/wp-calypso/assets/54123436/d42d42d1-f0b7-4b1b-b305-60e596df3710)

**Comment by jorpdesigns** [comment] 2024-04-17 17:28
Reported in 8056292-zen 
Theme: Arbutus

**Comment by joseprthur** [comment] 2024-04-18 17:50
Reported in 8008522-zen
Theme: Payton (Premium)

**Comment by jorpdesigns** [comment] 2024-05-16 08:07
Reported in 8189860-zen
Theme: Payton

**Comment by rickmgithub** [comment] 2024-05-22 11:41
Reported in 8191577-zd-a8c
Theme: Twenty Twenty Three

**Comment by dsas** [comment] 2024-10-25 14:36
Couldn't repro in Kingsley or Geologist. In Geologist - Slate though I get 16px font size in the editor and 20px on the front-end though.  I don't get the title issue mentioned upthread.

**Comment by dsas** [comment] 2024-10-25 14:54
@inaikem / @mmtr I assume you could reproduce this a few days ago, could you share how?

**Comment by mmtr** [comment] 2024-11-12 11:52
@dsas I cannot remember right now, but I think I only activated Kingsley on a Free Simple site and then published a new post. However, I cannot replicate it now on my site where Kingsley was active, so either the issue fixed itself or maybe we actually didn't reproduce this issue.

So I'm closing this one. We can re-open if we get reports that the issue still persists.

**Closed as not planned by mmtr** 2024-11-12 11:52 UTC
Labels: Bug, [Pri] Normal, Blocks, Triaged, [Closed] Not Reproducible, Customer report [LEGACY], [Platform] Simple, [Interaction #] > 10, [Status] Priority Review Triggered
