### ISSUE TITLE
Gutenboarding: click outside the domain picker to close

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#40890] opened 2020-04-08 09:10 UTC
#### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/new/design
2. Click _sitename.com is available_ 
3. See the overlay open. Click outside the overlay

#### What I expected
When clicking outside the overlay, I expect the overlay to close, just like clicking the X button would.

#### What happened instead
It didn't close when clicking outside the overlay.

**Comment by simison** [comment] 2020-04-08 12:13
Could it be we need the latest version of `@wordpress/components` for it to work? 🤔 

https://github.com/Automattic/wp-calypso/pull/39644

**Comment by yansern** [comment] 2020-04-09 14:24
It seems that `onClickOutside` is deprecated. The new prop is called `onFocusOutside`.

**Comment by simison** [comment] 2020-04-09 14:38
oh, we don’t list `@wordpress/components` in `package.json` as a dependency :sweat_smile:

Would be good to figure out which prop we need to use with the version we have (https://unpkg.com/ can be useful).

**Comment by yansern** [comment] 2020-04-09 15:07
The issue is that the Popover element was never focused because of `focusOnMount=false`. Previously, I set `focusOnMount=false` because the popover was automatically focusing on the first element on the domain picker which is the close button.

If you focus on anywhere in the domain picker, then click outside again, it will close the popover.

The `@wordpress/popover` element uses `higher-order/with-focus-outside` HOC to detect whether the element was blurred. However, it does so by comparing against the previous activeElement. Since the domain picker was never in focus, that HOC doesn't trigger when focused outside. I think that HOC can be smarter, for one, it doesn't have to rely on activeElement.

But anyway, I think I can fix both this issue and the auto-focus issue in one PR since they are related.

In the DOM tree, I would move the close button after the search input, and use absolute positioning to move it to the top right corner. Then `focusOnMount=false` can be removed, and we can rely on Popover's autofocusing to focus on the search input element for us automatically.

**Comment by yansern** [comment] 2020-04-10 03:38
This PR fixes it. https://github.com/Automattic/wp-calypso/pull/41007

**Comment by yansern** [comment] 2020-04-10 10:24
UPDATE: https://github.com/Automattic/wp-calypso/pull/41007 is now closed for a more simple solution at https://github.com/Automattic/wp-calypso/pull/41014. @alshakero

**Comment by alshakero** [comment] 2020-04-10 10:49
Closing as fixed in #41014

**Closed by alshakero** 2020-04-10 10:49 UTC
Labels: Domains, [Goal] Gutenboarding, [Type] Bug
