### ISSUE TITLE
Gutenberg: add support for video uploads

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27499] opened 2018-09-28 20:46 UTC
Video blocks don't appear to fully work. We can select a video to upload, and it will be uploaded to the site, but it doesn't appear that the preview in the editor is updated, or that the published post contains the video

**Comment by vindl** [comment] 2018-10-10 17:03
The apparent file type permission error has been caused by inadequate plan on the site (doesn't work with free plan for example). This has been moved to a separate issue #27772, but the problem with videos not being rendered on the front end still remains.

**Comment by Copons** [comment] 2018-10-17 11:32
This is caused by the `video` tag not being whitelisted in our `wp_kses`.
Tentative fix: D19531-code.

**Comment by Copons** [comment] 2018-10-19 16:33
Fixed by D19531-code

**Closed by Copons** 2018-10-19 16:33 UTC
Labels: [Goal] Gutenberg, [Pri] High, [Type] Bug
