### ISSUE TITLE
Media: Inserting media that hasn't been added yet causes errors.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#31230] opened 2019-03-05 21:53 UTC
When setting a featured image, we can access the Pexels API from the "Free Photo Library" dropdown in the media modal. As soon as we select an image, we can immediately insert it (with the primary action button), even though it hasn't completed uploading to our library.

In Calypso, this will give console errors but corrects itself somehow; however, when using the media modal with an iframed block editor, the failure will leave the featured image loader spinning forever unresolved.

Additionally, you'll get the same console errors when trying to insert a still-uploading image in the block editor, but it works itself out with no issues. Only in the context of the featured image in the block editor is this an issue.

The core media modal gets around this by not allowing you to insert an image until it has been uploaded. (Seems this could be a possible solution, though not as slick a UX.)

<img width="388" alt="screen shot 2019-03-05 at 1 45 35 pm" src="https://user-images.githubusercontent.com/349751/53839977-bdbfb500-3f4d-11e9-9862-11b32720a463.png">
<img width="508" alt="screen shot 2019-03-05 at 1 45 50 pm" src="https://user-images.githubusercontent.com/349751/53840077-024b5080-3f4e-11e9-86eb-cf6121758dd9.png">

Note that if we then remove the featured image, we can reapply it successfully, since the media has completed uploading.

#12000 may point to a solution.

To Replicate
* At `https://wordpress.com/post`, select a site that's opted in to the block editor.
* Select Set Featured Image, and choose Free Photo Library from the top left corner dropdown.
* Enter a search term, select an image, and click Insert.
* Note the console error, and the missing featured image.

(You can also replicate this by uploading a local picture and then inserting it as a featured image before it has finished uploading.)

Note: after resolving this issue, also make sure you can no longer reproduce #33362.

**Comment by donalirl** [comment] 2019-06-02 00:42
This came up in #5711931-hc. We did not succeed with the workaround of removing the featured image and re-selecting it from the site's Media. It must be some theme/plugin conflict because it did work fine on my atomic site.

**Comment by noahtallen** [comment] 2019-07-25 01:35
The console errors are caused because the media modal does the following synchronously:
1. Assigns the images a temporary IDs before uploading
1. Calls the code to upload the items
2. Returns immediately (i.e. before the upload is done)
3. Then whatever context you opened the modal from gets the images with their temporary IDs, since they have not yep finished uploading.
4. That context (i.e. the image block or the featured images sidebar area) immediately performs a `GET` for the image, like `https://public-api.wordpress.com/wp/v2/sites/160923989/media/media-15`. In this case, `media-15` is the transient (temporary) ID of the media that is currently uploading.

**Comment by noahtallen** [comment] 2019-07-27 00:59
Turns out the above is unrelated - the code we have for update image blocks is specifically for editing an image (see D26023-code) and doesn't fire when inserting an image in the first place.

**Comment by arunsathiya** [comment] 2019-09-05 02:54
This was reported here https://github.com/Automattic/wp-calypso/issues/35987 as well, and I am able to reproduce. I also noticed that, when the featured image is removed and when I open the media library again, the photo from `Free photo library` can be seen.

That is, the featured image action fails, and when we remove that image to check the media library, the file can be seen to be successfully uploaded. 

But, trying to set new images as featured again, from `Free photo library`, fails.

**Comment by kwight** [comment] 2019-10-04 21:40
Confirmed this is still an issue today, but didn't get far on a solution.

**Comment by zdenys** [comment] 2019-11-05 17:15
Confirming that it is still happening and I encountered it many times during Quick Start Sessions.

**Comment by zdenys** [comment] 2020-01-28 14:55
As per pbAPfg-1z-p2#comment-94 it should not be happening anymore. Can others confirm this too so we can close the issue?

**Comment by gwwar** [comment] 2020-01-28 19:53
Let's verify if this is still an issue

**Comment by gwwar** [comment] 2020-01-29 22:23
@zdenys this was fixed by @Addison-Stavlo in https://github.com/Automattic/wp-calypso/pull/38488 💖

The insert button will be disabled until the image is fully uploaded.

![Jan-29-2020 14-22-21](https://user-images.githubusercontent.com/1270189/73402752-d2faac00-42a2-11ea-9263-4e58fb89747e.gif)

**Closed by gwwar** 2020-01-29 22:23 UTC
Labels: Editor, [Goal] Gutenberg, [Pri] High, [Type] Bug
