### ISSUE TITLE
Pique Theme - Cannot Set the Background to white

### ISSUE THREAD

**Issue by syhussaini** [Automattic/wp-calypso#62157] opened 2022-03-23 06:44 UTC
### Quick summary

The background color does not set to white through _Customizer → Colors & Backgrounds_. All other colors are working fine.

### Steps to reproduce

1. Activate the theme "Pique"
2. Now go to _Customizer → Colors & Backgrounds_ and select white color for _Alternate Panel background_.

_See image below for reference_
![pique](https://user-images.githubusercontent.com/8070771/159637767-b5324037-0665-4da7-96ec-714923019ea6.gif)
_Please [click here](https://d.pr/i/C2dglk) if you are unable to see the image above_

### What you expected to happen

When selecting the white color for _Alternate Panel background_ from _Customizer → Colors & Backgrounds_ I expected it to show white background for the site in the Pique theme.

### What actually happened

The color does not change to white. 
Other colors are working as expected.

### Context

Found this issue on 4881557-zen
Tested in my simple site to replicate the issue.

Adding the custom CSS did not help.
Even forced the custom CSS, but that did not help.

### Theme-specific issue?

I tested Ixion, Twenty Twenty, and Twenty Sixteen. Found no issues there.
Happens only on Pique Theme

### Browser, operating system and other notes

My System Details: https://www.whatsmybrowser.org/b/PN9TM

User's System Details:
Screen Size: 2560 x 1440
Browser Size: 1926 x 1236
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

No but the platform is still usable

**Comment by edequalsawesome** [comment] 2022-03-23 19:40
This is the expected behavior -- the site title and menu are set to white and can't be changed through the Colors & Backgrounds panel of the Customizer, and it looks like there's a function in the `/inc/wp-colors.php` that prevents the Alternate Panel Background color from being set to white.

Since this is expected, I'm going to close this issue 😃

**Closed as completed by edequalsawesome** 2022-03-23 19:40 UTC
