### ISSUE TITLE
Blog Posts - Wrong link for Author page

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#40546] opened 2020-03-29 05:44 UTC
The **Display Name** shows correctly but the link is broken as it's not using the username.

![Screen Shot on 2020-03-29 at 13:42:31](https://user-images.githubusercontent.com/15944096/77842288-287c0800-71c3-11ea-99d9-a578837732a9.png)

### Temporary solution

* change **Display Name** to match **Username**
* or, disable the option **Show Author**

Ticket: #28226930-zen

**Comment by arunsathiya** [comment] 2020-03-29 09:02
I believe this must be fixed by https://github.com/Automattic/newspack-blocks/pull/407. A release is not published so far https://github.com/Automattic/newspack-blocks/releases

Going by this comment https://github.com/Automattic/wp-calypso/pull/40518#issuecomment-605534225 it looks like Newspack may release by Monday, at which stage Calypso side of things https://github.com/Automattic/wp-calypso/pull/40518 must be merged.

@laurelfulford / @noahtallen, could you confirm if this is the case?

**Comment by noahtallen** [comment] 2020-03-29 23:46
Spot on! It should now be fixed in Newspack. The order of events will be:

- Fix merged in newspack (complete)
- Newspack publishes release
- We merge the release into the FSE plugin in wp-calypso
- We deploy the FSE plugin

**Comment by noahtallen** [comment] 2020-04-01 00:33
We are on the last step: working on the deploy and sync of the plugin to wpcom. hopefully this will be done tomorrow

**Comment by arunsathiya** [comment] 2020-04-03 05:22
Now that https://github.com/Automattic/wp-calypso/pull/40518 is merged, the issue is resolved. I have tested as well on my test site `gutenberg-wpcom.arun.be`. Informing user.

**Closed by arunsathiya** 2020-04-03 05:22 UTC
Labels: Blocks, [Goal] Gutenberg, [Type] Bug
