### ISSUE TITLE
Vertical step: Pre-selected vertical not being populated correctly in the input field

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#64808] opened 2022-06-21 10:12 UTC
## Description
In the vertical question step, when a site vertical has already been set, then the input field will be pre-populated with the vertical text. Currently, there is an issue where even though the vertical text is being pre-populated in the input field, the value is not correctly set to the component state, causing the selected vertical being cleared when the user clicks on the Continue button. See recording of the issue:

https://user-images.githubusercontent.com/797888/174774714-7db70ce8-0d6f-4c68-8b21-61c2edc24939.mp4

As seen from the recording above, the first the "Food" vertical is submitted it is set correctly, so the user sees the generated design picker. When the user goes back to the vertical question screen, they see the text "Food" in the input field, and without making any changes, they click on the Continue button. This time, they see the static design picker. Finally, when going back to the vertical question screen again, they find out that the input field is empty.

## Acceptance Criteria
- [ ] When a site vertical is set, the input field should be properly pre-populated with the site vertical so that the user will (1) see the vertical text in the input field, and (2) the vertical value is set in the component state.

**Comment by arthur791004** [comment] 2022-06-21 10:47
This is caused by https://github.com/Automattic/wp-calypso/blob/a8b9ea1ad2779a1e4cda4bce3881c390e3855924/client/landing/stepper/declarative-flow/internals/steps-repository/site-vertical/form.tsx#L30 that was introduced from https://github.com/Automattic/wp-calypso/pull/64699. I'll fix it later.

**Comment by arthur791004** [comment] 2022-06-22 03:31
Close it as it's completed

**Closed as completed by arthur791004** 2022-06-22 03:31 UTC
Labels: Bug
