### ISSUE TITLE
JS error for State when going through onboarding in the ecommerce plan

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wp-calypso#37172] opened 2019-10-30 07:46 UTC
#### Steps to reproduce
1. Sign up for the ecommerce plan.
2. Attempt to continue the onboarding wizard.
3. Got stuck and found the error in console.

#### What I expected

That my state would be properly populated.

#### What happened instead

Seems like my state is not being populated correctly. https://cloudup.com/ctkvS5O3ktp

#### Screenshot / Video

Here's the error in console : https://cloudup.com/cYmtbWryy2P 

#### Context / Source
Testing the new ecommerce plan.

**Comment by timmyc** [comment] 2020-03-10 21:11
I am still unable to reproduce this. Closing this out - also this looks like the new OBW so would be an issue in wc-admin.

**Closed by timmyc** 2020-03-10 21:11 UTC
Labels: eCommerce Plan
