### ISSUE TITLE
FSE: Site Editor Sidebar Link Disappears After Switching Themes.

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/wp-calypso#52983] opened 2021-05-18 18:56 UTC
### Steps to reproduce the behavior

1. Create site from https://horizon.wordpress.com/new?flags=gutenboarding/site-editor
2. Select the Blank Canvas Theme during site creation.
3. Switch theme to Storefront.
4. Switch theme back to Blank Canvas

#### What I expected to happen

The Site Editor link to return to the sidebar.

#### What actually happened

The Site Editor link was no longer available within the sidebar.

#### Browser / OS version

Chrome 90 on macOS 10.15.7

**Comment by Copons** [comment] 2021-05-19 16:53
I think this is caused by the fact that the Blank Canvas theme shown in the Themes page is _not_ the FSE version of Blank Canvas (which would be "Blank Canvas Blocks"), which means that it's correct that the Site Editor link doesn't show up in the sidebar anymore.

Related: apparently the Blank Canvas theme offered in the onboarding is not the FSE version as well. 🤔 

I've written a bit more at paYE8P-Tg-p2#comment-786, but haven't performed a proper investigation yet.

**Comment by AashikP** [comment] 2021-06-05 04:41
Just wanted to add that after reverting a site, when all other themes are gone, you can view the site Editor Option again.

![https://d.pr/i/gv2DSZ+](https://d.pr/i/gv2DSZ+)

ref pca54o-1mt-p2#comment-1951

**Comment by jeyip** [comment] 2021-11-06 00:18
@Copons can we close this?

**Comment by Copons** [comment] 2021-11-08 11:33
> @Copons can we close this?

@jeyip Yup!
Blank Canvas is not used anymore, and anyway we sorted out the sidebar toggling the Site Editor item after a theme switch a long time ago already. 🙂

**Closed as completed by Copons** 2021-11-08 11:33 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Normal, [Goal] Full Site Editing, Triaged
