### ISSUE TITLE
Marketplace: Translate upcoming woo extensions

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#58898] opened 2021-12-07 09:19 UTC
We decided to include the following woo extensions in the Marketplace:

- [x] ~~Follow-Ups~~
- [x] ~~Checkout Field Editor~~
- [x] FedEx Shipping Method
- [x] WooCommerce Deposits
- [x] WooCommerce Points and Rewards
- [x] WooCommerce One Page Checkout
- [ ] ~~PayPal Payments Pro~~
- [x] WooCommerce Pre-Orders
- [x] Min/Max Quantities
- [x] Product Vendors
- [x] Jetpack Search (New)
- [x] WooCommerce Paid Courses (New)

Let's make sure they have adequate translations.

Related Convo: pdh6GB-9D-p2#comment-335

**Comment by emmnyc85** [comment] 2022-01-18 09:00
**Let's remove:** follow-ups, checkout field editor, paypal payments pro

**Let's add:**
Jetpack Search
WooCommerce Paid Courses

I'm in the process of another review and will provide another update by end of this week.

cc: @cpapazoglou, @dlind1

**Comment by dlind1** [comment] 2022-02-01 02:22
`Points And Rewards` is fully translated and everything is configured properly.
I've created PRs to fix the inclusion of languages folder in the release ZIP for three extensions:
https://github.com/woocommerce/woocommerce-deposits/pull/405
https://github.com/woocommerce/woocommerce-min-max-quantities/pull/146
https://github.com/woocommerce/woocommerce-bookings/pull/3264 (regression issue)

**Comment by cpapazoglou** [comment] 2022-02-08 17:10
@dlind1 any updates of plugins ready except `Points And Rewards`?

**Comment by dlind1** [comment] 2022-02-08 20:55
@cpapazoglou The three PRs all got approved and seem to be in QA at the moment, although I'm not sure what's the process for creating a new release once they'd be merged, so I've followed-up with Darin Kotter for clarifications.
The current release of `WooCommerce Deposits` has a valid set of language packs, so we could include that since the fix only applies to future releases.
WooCommerce One Page Checkout has a wrong text domain in code, but is fully translated, so it could be the quickest one to fix next. 
I'm checking the remaining extensions and would create PRs for them this week.

**Comment by dlind1** [comment] 2022-02-24 12:59
[woocommerce-shipping-fedex](https://translate.wordpress.com/projects/woocommerce/extensions/woocommerce-shipping-fedex/), [woocommerce-mix-max-quantities](https://translate.wordpress.com/projects/woocommerce/extensions/woocommerce-min-max-quantities/) and [woocommerce-xero](https://translate.wordpress.com/projects/woocommerce/extensions/woocommerce-xero/) are now fully translated, but require code changes to be merged or waiting for new release to enable language packs delivery.

**Comment by dlind1** [comment] 2022-03-11 14:41
[woocommerce-pre-orders](https://translate.wordpress.com/projects/woocommerce/extensions/woocommerce-pre-orders/) and [woocommerce-product-vendors](https://translate.wordpress.com/projects/woocommerce/extensions/woocommerce-product-vendors/) would be sent for translation on Monday.
PRs were created for [woocommerce-one-page-checkout](https://github.com/woocommerce/woocommerce-one-page-checkout/pull/475) and [woocommerce-shipping-fedex](https://github.com/woocommerce/woocommerce-shipping-fedex/pull/196) to fix issues with displaying translations.

**Comment by lsl** [comment] 2022-04-27 08:01
Just came across this while searching for something else, this might need reprioritizing or could be closed out?

**Closed as completed** 2022-07-25 13:21 UTC
Labels: Marketplace + Woo Extensions
