### ISSUE TITLE
Unable to choose free plan after clicking "Choose my domain later" in new site flow

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#65580] opened 2022-07-14 07:01 UTC
### Quick summary

When attempting to create a new free site, the free site plan does not appear if a user clicks "Choose my domain later" link.
![CleanShot 2022-07-14 at 15 54 31@2x](https://user-images.githubusercontent.com/83020905/178920708-0f9a97fd-2b33-4817-8726-1049fa6b0d8a.png)

Video:

https://user-images.githubusercontent.com/83020905/178921642-cf9b0787-3f93-42af-988c-10a5ba832304.mp4

### Steps to reproduce

1. Start from https://wordpress.com/start/plans or https://wordpress.com/start?ref=calypso-selector (Add new site in dashboard)
2. Do not enter anything in domain box and click "Choose my domain later"
3. Plans page does NOT feature free plan link

### What you expected to happen

Users should be able to see the free plan link regardless of whether they enter something into domain search or if they click "Choose my domain later"

### What actually happened

The free plan link should be available.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

User must choose the free domain after searching.

**Comment by kuropixel** [comment] 2022-07-26 04:58
6673319-hc 
Another report, user already had a plan but wanted to create a free site and was unable to until I explained they had to type in a domain, then choose at the very bottom "skip". From a user's perspective, this seems a bit deceitful.

**Comment by cometgrrl** [comment] 2022-07-28 23:13
Now that the pro/starter plans have been reverted, this is back to how it's been for years.

It's also being discussed here: p58i-cJS-p2. Closing this for now, as there's not a bug, even if the flow is a bit misleading.

**Closed as completed by cometgrrl** 2022-07-28 23:13 UTC
Labels: Bug, [Pri] Normal, [Platform] Simple, [Platform] Atomic

**Comment by kuropixel** [comment] 2022-07-30 22:27
@cometgrrl The discussion link didn't work for me. If possible, could you share that again? Thank you!

**Comment by cometgrrl** [comment] 2022-08-01 18:59
> The discussion link didn't work for me. If possible, could you share that again? Thank you!

Ah sorry, since it's in shorthand, I guess I can't make it a clickable link. Updated my original comment. Hope that helps!

**Comment by DavidRothstein** [comment] 2022-08-01 19:50
>Now that the pro/starter plans have been reverted, this is back to how it's been for years.

Nope: p58i-cJS-p2#comment-54846

Personally, I would keep this issue open (it's definitely not a "Won't Fix") but I guess as long as it's being actively discussed on that internal P2 it's OK for now.

**Comment by cometgrrl** [comment] 2022-08-01 21:12
Interesting, I was referring to this comment: p58i-cJS-p2#comment-54799, and also in slack, this behavior was mentioned to date back to 2019. See: p1658318312429269/1658315949.602159-slack-C031TFM2NKC.

I don't disagree that we should make a change, I'd just prefer to let the people having conversations and analyzing the data determine the best changes to make, rather than dictating a solution in this bug (with outdated screenshots).

**Comment by cometgrrl** [comment] 2022-08-01 23:36
> (it's definitely not a "Won't Fix")
Agreed that this label may not be appropriate, so I removed it. I think` [Closed] By Design` might b more appropriate?

**Comment by DavidRothstein** [comment] 2022-08-02 20:43
Yeah, maybe "By Design" at least for the specific solution proposed here, since it sounds like the intended goal is to not show the free plan.

But I think the expectation that clicking "Choose my domain later" shouldn't lock you in to a paid plan is a legitimate expectation, so either changing the wording of that link or addressing the confusion otherwise is probably going to be a valid solution.

**Comment by cometgrrl** [comment] 2022-08-19 18:57
FYI: pbxNRc-1V5-p2
