### ISSUE TITLE
Fix Coutoire in the template selector preview

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37685] opened 2019-11-18 20:00 UTC
The theme does not render correctly, this looks like a responsive css issue.

<img width="764" alt="Screen Shot 2019-11-18 at 11 59 13 AM" src="https://user-images.githubusercontent.com/1464705/69086070-114e3200-09fb-11ea-8636-1f438e499b8c.png">

**Comment by apeatling** [comment] 2019-11-18 23:53
To be clear, this is using the Coutoire homepage layout with Maywood active as the theme.

**Comment by apeatling** [comment] 2019-11-19 21:57
@danieldudzic Assigning you to this one, now that the FSE changes have merged to dotcom, you should be able to reproduce this more easily.

**Comment by iamtakashi** [comment] 2019-11-19 22:17
It doesn't seem to be the theme-specific issue though. The inherited paddings in one of the CSS in SPT is breaking the layout. What's the purpose of this?

<img width="1434" alt="Screenshot 2019-11-19 at 22 13 13" src="https://user-images.githubusercontent.com/908665/69191311-28377600-0b1a-11ea-8539-8991bc781db3.png">

**Comment by danieldudzic** [comment] 2019-11-19 22:23
This indeed seems to be caused by that extra padding.

**Comment by iamtakashi** [comment] 2019-11-19 23:36
I find some visual inconsistency in the preview and what I get in the editor with the same theme. I opened a new issue here #37742 with the test process that I took. I think the preview should be as close as possible to what the user get once they add the layout into the editor.

**Comment by apeatling** [comment] 2019-11-20 04:25
@Copons For the sake of the user test would you be willing to exclude this theme from the response? Let's fix this after the test (unless you know of an easy padding fix for this).

**Comment by Copons** [comment] 2019-11-20 11:13
@apeatling I'm totally willing (also said it right at the end of paYE8P-eB-p2 🙂).
I'll also exclude the Stratford layout that has a broken Cover block.

@iamtakashi I noticed those inconsistencies too but didn't have enough spare cycles to fully investigate them.
I'll continue the discussions in #37742 and assign it to Cylon.

**Comment by iamtakashi** [comment] 2019-11-21 12:02
@Copons

> I'll also exclude the Stratford layout that has a broken Cover block.

I recovered the block and the layout is fine on the demo site now. What needs to be done to feed the layout picker the latest? Would Cylon be able to update it? :) If this can be automated or can be done through a MC page it would be ace so that designers don't need to bother every time blocks on page layouts break. 

> noticed those inconsistencies too but didn't have enough spare cycles to fully investigate them.
I'll continue the discussions in #37742 and assign it to Cylon.

👍

**Comment by Copons** [comment] 2019-11-21 12:10
@iamtakashi I'll reenable Stratford ASAP, thanks for the fix!

I'm not sure how to automatize the process though, but adding/removing layout is a very simple API change, that doesn't involve any FSE plugin work, so it can be shipped immediately (users will still have a 1-day cache for the API response though).

**Comment by Copons** [comment] 2019-11-21 14:23
@iamtakashi I've checked the demo site and the block looks still broken to me, nor do I see any revisions in the last month. 🤔 

<img width="1409" alt="Screenshot 2019-11-21 at 14 22 23" src="https://user-images.githubusercontent.com/2070010/69346292-73f93500-0c6a-11ea-9a4d-d6bc0c139f9e.png">

(btw this only happens in the block editor, the front end looks perfectly fine as it renders the Cover block straight from its code)

**Comment by iamtakashi** [comment] 2019-11-22 09:28
> I've checked the demo site and the block looks still broken to me, nor do I see any revisions in the last month.

@Copons I've updated it again after hitting "attempt block recovery", but if I open the page in the editor again, the block it's broken again :/ I'll see what I can do to recover the block.

**Comment by iamtakashi** [comment] 2019-11-22 09:37
@Copons OK, it looks like "attempt block recovery" didn't change anything other than removing the error message. Anyway, the block doesn't seem to like setting the vertical position to `0%`. I've now changed it to `1%` and save it. It seems working for me, but let me know if it's still broken for you.

**Comment by iamtakashi** [comment] 2019-11-22 10:19
@Copons 

> (users will still have a 1-day cache for the API response though)

Oh, does this mean that the changes that designers make on layouts will _automatically_ be reflected in the layout picker after the cache cleared?

**Comment by Copons** [comment] 2019-11-22 11:40
@iamtakashi Thanks this seems to have worked! ✨ 

About the caching: we have _two_ caches going on with the layouts.
One in the API that stores the layouts to avoid slow too many file system searches, and one in the Starter Page Templates plugin that stores the API response.
Both are 1-day long, but aren't in sync.
The plugin one is also automatically cleared at every plugin version changes.

This means that changes on the demo sites will automatically appear in the layout selector in less than 1 day.

We've been keeping them at 1 day because we don't expect many urgent changes on the layouts, but let me know if y'all think we need to lower it.
(I'm personally not good at cache and performance, but I can pass your request along to more skilled people 😄).

**Comment by Copons** [comment] 2019-11-22 12:24
Actually @iamtakashi, your fix is correct but I've just noticed that the API fetches the layouts from the headstart JSONs (in the sandbox, not in the theme repo), not straight from the demo site. 🤦‍♂ 

I've tried applying your fix directly to the files and it seems to work fine.
I'm currently enquiring about how to do it automatically, but I think you shouldn't have to do anything else. 👍

**Comment by iamtakashi** [comment] 2019-11-22 13:12
> the API fetches the layouts from the headstart JSONs

That was what I suspected :)

> I'm currently enquiring about how to do it automatically, but I think you shouldn't have to do anything else.

Thank you!! Obviously it depends on the cost to make it happen, but it'd be nice if designers don't need to feel that they'll bother engineers whenever layouts need to be updated :)

**Comment by Copons** [comment] 2019-11-22 14:16
@iamtakashi I'll update you as soon as I find out the procedure, which is still unknown to me and apparently all the people who worked on it are in other timezones. 😄

**Comment by jeryj** [comment] 2019-12-17 21:40
Using Coutoire with FSE appears to be fixed by https://github.com/Automattic/wp-calypso/pull/38065

Screenshot taken using the Maywood theme with latest from `wp-calypso master` and Gutenberg 7.1.0:
<img width="1779" alt="Screen Shot 2019-12-17 at 3 16 49 PM" src="https://user-images.githubusercontent.com/967608/71036274-fa2a5f00-20e2-11ea-9a07-f26a433b89fb.png">

**Comment by jeryj** [comment] 2019-12-20 15:38
After further review, it seems like this is only fixed when the FSE plugin is active, which @obenland says is not the case for everyone on WPcom yet.

**Comment by lancewillett** [comment] 2020-03-09 17:43
I tested this today with the "Add New" page flow in both Calypso and WP Admin. _Testing with Firefox 73 on macOS Catalina with `testerlance` user._

I didn't see Coutoire in the Homepage layouts list any more. With that, closing as likely not a valid issue any more. (If this is a mistake, please feel free to re-open.)

<img width="1392" alt="Screen Shot 2020-03-09 at 10 41 13" src="https://user-images.githubusercontent.com/66797/76241726-a9626800-61f2-11ea-9890-a3aef52f1750.png">
<img width="1392" alt="Screen Shot 2020-03-09 at 10 41 16" src="https://user-images.githubusercontent.com/66797/76241739-ad8e8580-61f2-11ea-9755-edaa2dbb23c3.png">

**Closed by lancewillett** 2020-03-09 17:43 UTC
Labels: Themes, [Pri] High, [Type] Bug

**Comment by jeryj** [comment] 2020-03-10 20:15
I believe Coutoire was removed from the API response as an option for the Home Page layouts because of the broken layout. The template selector preview just had a big update released (https://github.com/Automattic/wp-calypso/pull/39628), so I wouldn't be surprised if this layout is fixed or at least significantly better.
