### ISSUE TITLE
Gutenboarding: Theme Showcase, Bowen Theme shows a broken Form block on the Blog Page. 

### ISSUE THREAD

**Issue by marcuswisecaesar** [Automattic/wp-calypso#50506] opened 2021-02-25 23:00 UTC
### Steps to reproduce the behavior

1. Go through Gutenboarding until you are selecting a theme.
2. Select the Bowen Theme and a Font Pairing
3. Pick A Plan
4. Proceed to Edit the Site
5. Select the Blog Page to Edit

#### What I expected to happen
- Expected blocks in a theme demo to be working without error. 

#### What actually happened

The subscription form block in a column on the right is broken. 

[GIF Link](https://d.pr/i/JvdHm0)

![screenshot](https://d.pr/i/okxlCv+)
[Direct Link](https://d.pr/i/okxlCv)

### Context
Gutenboarding Flow 
#### Browser / OS version
Chrome: version 88.0.4324.192 (Official Build) (x86_64)
macOS Big Sur: version 11.2.1 (20D74)

#### Is this specific to the applied theme? Which one?
Bowen

#### Does this happen on simple or atomic sites or both?
N/A

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects the onboarding process. 

#### 
Related to:
* https://github.com/Automattic/jetpack/pull/18936
* D57652-code

**Comment by jeyip** [comment] 2021-03-02 22:43
cc @cathymcbride I reproduced this following the given instructions. Feel free to change the priority, but I set it as "low" because:

- I can introduce a new subscribe button manually
- I can recover the block successfully
- The frontend of the site continues to render the block correctly, with or without recovering the block

I can't tell if it's a themes issue or a gutenberg issue without deeper investigation

**Comment by StefanNieuwenhuis** [comment] 2021-03-04 09:26
I've upscaled the priority since this issue has a direct impact on (paying) customers (see p1614755830083400/1614718793.075600-slack-C013QHLF28Y).

After merging https://github.com/Automattic/jetpack/pull/18936 &  D57652-code this issue is fixed now, hence I closed this issue.

**Comment by StefanNieuwenhuis** [comment] 2021-03-04 09:27
I've upscaled the priority since this issue has a direct impact on (paying) customers (see p1614755830083400/1614718793.075600-slack-C013QHLF28Y).

After merging https://github.com/Automattic/jetpack/pull/18936 &  D57652-code this issue is fixed now, hence I closed this issue.

**Closed as completed by StefanNieuwenhuis** 2021-03-04 09:27 UTC
Labels: Bug, [Pri] High, [Goal] New Onboarding, Triaged, [Feature] Theme Showcase
