### ISSUE TITLE
Domain Only:  TT3 default content showing under wordpress.com/posts and /pages

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#82960] opened 2023-10-13 00:02 UTC
### Quick summary

We had a domain owner report that the were able to see "posts" for sites on their domains by going to https://wordpress.com/posts

I've anonymized the domains, but post are shown in groups of 3 per domain as indicated in my screenshot.  The user has several domains so the end effect is ~60 posts, 3 posts for each domain.

<img width="1124" alt="Screen Shot 2023-10-12 at 4 53 30 PM" src="https://github.com/Automattic/wp-calypso/assets/1967448/b4838a8f-7e46-4e5c-9abb-b11e8c181e59">

They look to be  demo content for TT3, but no sites are indicated under the user's account

### Steps to reproduce

I have not been able to replicate by registering a new domain, may affect transfers (Not sure if just Google Domains or any transfer) only.

### What you expected to happen

No posts to be shown, since no sites are listed under https://wordpress.com/sites/

### What actually happened

Posts are shown that have no function, cannot be visited, edited, placed in the trash, etc.  They cannot be dismissed.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Logs or notes

Reported in https://wordpress.com/forums/topic/random-posts-in-posts-on-my-account/

**Comment by cuemarie** [comment] 2023-10-13 00:11
Huh - strange! That's all the default content from TT3 - they have demo pages appearing under their WordPress.com/pages as well! 

I pulled up a random selection of customers who have domain-only domains on their accounts, and I see the same thing - TT3 demo posts and pages associated with those domain.

---

@Automattic/nomado is this the expected behavior for Domain-Only sites?

**Comment by cuemarie** [comment] 2023-10-13 00:31
📌 REPRODUCTION RESULTS
- Tested on Domain-Only – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
I checked a handful of other domain-only sites (by pulling up domain-only customers in Zendesk or 2MSmN-p2 , and I found default theme pages and posts under all of them - but it was not always consistent.

One example: userID `238981799`, owns 3 domain-only sites, but only 1 of them had content associated with it under WordPress.com/posts and WordPress.com/pages:

![Markup on 2023-10-12 at 17:24:06](https://github.com/Automattic/wp-calypso/assets/27249804/2fc88d36-e754-4d77-9e35-8aa535d97e70)

Others had posts or pages for all their subscriptions.  This example did not have TT3 content specifically, just the default "Hello World" post, one for each domain:

![Markup on 2023-10-12 at 17:20:26](https://github.com/Automattic/wp-calypso/assets/27249804/c4c6c296-f07e-4cf0-a040-42f92b99550e)

📌 ACTIONS
- Triaged

**Comment by lsl** [comment] 2024-07-04 05:59
These domain transfers have headstart log entries in blogrc that shouldn't be happening for domain only sites.

Is someone from @Automattic/nomado able to take a look at this? I'm guessing we need an additional check in `can_be_headstarted` to prevent headstart running on these sites.

**Comment by ramynasr** [comment] 2024-07-04 17:04
> These domain transfers have headstart log entries in blogrc that shouldn't be happening for domain only sites.
> 
> Is someone from @Automattic/nomado able to take a look at this? I'm guessing we need an additional check in `can_be_headstarted` to prevent headstart running on these sites.

I doubt that we need that on domain-only sites. I agree that we should skip domain-only sites in `can_be_headstarted`

**Comment by delputnam** [comment] 2024-07-18 17:01
I have added this to Nomado's backlog and scheduled it for the sprint starting on July 28.

**Comment by mpkelly** [comment] 2024-08-19 03:04
I've just bought a domain-only site and found Headstart still runs. I will look at a fix and ping Nomado for a review. 


![Image](https://github.com/user-attachments/assets/b9fe84d3-a6e8-42be-93ed-ec1e512f028b)

**Comment by mpkelly** [comment] 2024-08-19 03:33
Adding this patch means Headstart no longer runs: 

![Image](https://github.com/user-attachments/assets/e645896d-bbc4-4164-a23f-403147b8974b)

But we still get a validation error log entry:

![Image](https://github.com/user-attachments/assets/abf61a68-5345-4c72-836d-2559771a841b)

So I think we want to check for domain-only sooner and have a check in the `static` `can_be_headstarted` function.

**Comment by mpkelly** [comment] 2024-08-19 05:20
Looking at the stacktrace, I would say we can return early if it's a domain only site nad never start the Headstart Lifecycle. 

```
[19-Aug-2024 05:06:06 UTC] [e8a3-2973848] #0 /home/wpcom/public_html/wp-content/lib/headstart/class-headstart-lifecycle.php(94): switch_theme('pub/twentytwent...')
#1 /home/wpcom/public_html/wp-content/lib/headstart/class-headstart-lifecycle.php(65): Headstart_Lifecycle->maybe_switch_to_theme('pub/twentytwent...', false)
#2 /home/wpcom/public_html/wp-content/lib/headstart/class-headstart-lifecycle.php(34): Headstart_Lifecycle->prepare_meta_on_blog_creation(Array)
#3 /home/wpcom/public_html/wp-content/lib/headstart/class-headstart-lifecycle.php(29): Headstart_Lifecycle->headstart_on_blog_creation(236137837, 219393573, Array)
#4 /home/wpcom/public_html/wp-includes/class-wp-hook.php(324): Headstart_Lifecycle::blog_creation_action_handler(236137837, 219393573, 'jjjjjsdotorg.wo...', '/', 1, Array)
#5 /home/wpcom/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /home/wpcom/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#7 /home/wpcom/public_html/wp-includes/plugin.php(746): do_action_ref_array('wpmu_new_blog', Array)
#8 /home/wpcom/public_html/wp-includes/ms-site.php(198): do_action_deprecated('wpmu_new_blog', Array, '5.1.0', 'wp_initialize_s...')
#9 /home/wpcom/public_html/wp-includes/ms-functions.php(1497): wp_insert_site(Array)
#10 /home/wpcom/public_html/wp-content/lib/blogs/blogs.php(140): wpmu_create_blog('jjjjjsdotorg.wo...', '/', 'jjjjjs.org', 219393573, Array)
#11 /home/wpcom/public_html/wp-content/lib/store/checkout/helpers.php(143): Blogs::create('jjjjjsdotorg', 'jjjjjs.org', 1, 1, Array)
#12 /home/wpcom/public_html/wp-content/lib/store/checkout/helpers.php(97): WPCOM\Store\Checkout\Helpers::create_domain_only_site(Object(Store_Shopping_Cart))
```
So, at the start of `blog_creation_action_handler,` we can check if it is domain-only and return early. I will prepare a patch to do that.

**Comment by mpkelly** [comment] 2024-08-19 07:49
My diff is here. https://code.a8c.com/D158702

**Comment by mpkelly** [comment] 2024-08-20 01:49
Headstart no longer runs for domain-only sites since D158702 was deployed. Closing.

**Closed as completed by mpkelly** 2024-08-20 01:49 UTC
Labels: Bug, [Pri] High, [Feature Group] Emails & Domains, Triaged, Customer report [LEGACY], [Status] Priority Review Triggered, [Product] WordPress.com, [Feature] Domain Transfers, Groundskeeping
