### ISSUE TITLE
Theme Showcase: broken "Next theme" links when browsing premium themes

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#93464] opened 2024-08-12 18:16 UTC
### Quick summary

Theme Showcase: when navigating "Partner" themes, the “Next theme” links at the bottom of single theme showcase pages point to a retired theme “A Simpler Time”

This seems to happen for all "Partner" theme views, example URL: https://wordpress.com/theme/organic-stax?tab_filter=recommended&tier_filter=partner

### Steps to reproduce

1. Logged out, visit the Themes Showcase at wordpress.com/themes

<img width="1818" alt="Screenshot 2024-08-12 at 11 03 22" src="https://github.com/user-attachments/assets/8a9f5400-fd51-4f76-a8b9-d6c9b5934599">

2. Click "Partner" from the view dropdown

<img width="946" alt="Screenshot 2024-08-12 at 11 11 59" src="https://github.com/user-attachments/assets/310d5a6d-95ea-466a-a255-92f49333f33f">

3. Scroll down to `Features` section of the page (this is on a single theme view)

<img width="1317" alt="Screenshot 2024-08-12 at 11 03 39" src="https://github.com/user-attachments/assets/8b2183e9-e3b9-43b9-bb71-110c1963e181">

4. Click `Next theme` — and, _op!_ — it’s a retired theme called "A Simpler Time"

<img width="1818" alt="Screenshot 2024-08-12 at 11 03 53" src="https://github.com/user-attachments/assets/66078bc6-c0bb-44b3-893b-b059e27b913f">

### What you expected to happen

I expected “Next theme” links to navigate me the “next” Partner theme in the current view — or in the collection of themes I was browsing — based on search or category.

### What actually happened

I see the same retired theme each time: https://wordpress.com/theme/a-simpler-time

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Chrome latest, macOS
Happens both logged out and logged-in
CC @ianstewart for feedback on the bug report: anything I missed?

**Comment by jartes** [comment] 2024-08-13 10:39
📌 REPRODUCTION RESULTS
- Tested on Calypso – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I tried to replicate this on Chrome and Firefox, and when I click on the `Next Theme` button, I'm always redirected to the `Alonso` theme: 

https://github.com/user-attachments/assets/94becf2a-fe0b-402b-9262-ba136eed3eaf

📌 ACTIONS
- Requested author feedback
- Closed as I could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
👋🏻 @lancewillett Thanks for the detailed report! I'm not able to reproduce this issue. Are you still getting redirected to the `a-simpler-time` theme?

**Comment by ianstewart** [comment] 2024-08-13 12:04
> feedback on the bug report: anything I missed?

LGTM. The URL to a specific example theme was especially helpful as I also wasn't able to reproduce (proxied or unproxied) and that helped me confirm quickly when triple-checking.

> Are you still getting redirected to the a-simpler-time theme when clicking on the Next Theme button?

Still happening consistently?

**Comment by lancewillett** [comment] 2024-08-14 15:23
@jartes I can't reproduce today likely because of the cache issue Bogdan mentions above. Let's keep it open — fix involves making sure Partner themes are returned in a `next` search from the WP.com Themes API.

**Comment by JulianBustamante** [comment] 2024-08-21 20:57
@BogdanUngureanu Since the [Theme details: Remove the Next theme button #93562](https://github.com/Automattic/wp-calypso/pull/93562) PR gets merged, I moved this issue to Done.

**Closed as completed** 2024-08-21 22:02 UTC
Labels: Bug, [Pri] High, Triaged, [Status] Priority Review Triggered
