### ISSUE TITLE
Public site shows "login to activate admin features " at top of site

### ISSUE THREAD

**Issue by dchymko** [Automattic/wp-calypso#79149] opened 2023-07-07 21:57 UTC
### Quick summary

I create a new site on the Personal Plan with a custom domain via the web. I was waiting for that domain to become active. I was away from my desk and marked the site as "Public" in the Jetpack mobile app and it then showed the content and theme However it had a header at the top saying "Is this a new site and you are the site owner? Login to activate admin features." Logging in on the desktop just took me into the sites admin and didn't alleviate the issue. I had to change the active domain to the wordpress.com one and back to the custom domain to resolve the issue. This flow may(?) only affect A12s

### Steps to reproduce

1. Create a new personal site with a custom domain.
2. Wait for the domain to resolve. Once it does, use the Jetpack mobile app to set the site to "Public" under site settings
3. Navigate to the Custom domain via a private browser and the "login to activate admin features " header will appear at the top of the public-facing site.

### What you expected to happen

The header should not be there if I mark the site as public from the Jetpack mobile app.

### What actually happened

The "login to activate admin features " header appeared at the top of the public site.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

The site in question was okbikepackers.ca

**Comment by cuemarie** [comment] 2023-07-12 18:06
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I took the following steps to replicate:

1. Create new site and new domain
2. With .wordpress.com domain still primary, I set the site to public from the mobile app
     - No banner shown on mobile or desktop browser
3. On desktop, I set the still-activating domain as Primary
     - No banner shown on mobile, but desktop browser shows the `Is this your new site? Log in to activate admin features and dismiss this message` banner as shown below:

#### Screenshots/Recordings

![Markup on 2023-07-12 at 10:58:58](https://github.com/Automattic/wp-calypso/assets/27249804/d97dcfd7-7b96-4ac8-8271-9b83788b6842)

📌 ACTIONS
- Closed as by design

📌 Message to Author
- Hey @dchymko ! This banner is actually working by design, in order to set cookies on a newly purchased domain. This P2 talks through this project in more detail: pcNnmV-5c-p2 
- Based on the P2 and the behavior you reported and I'm seeing, it seems this is working as intended - basically prompting you to log in when visiting that newly purchased domain, so that WordPress.com can set those third party cookies on that new domain.

**Closed as not planned by cuemarie** 2023-07-12 18:06 UTC
Labels: Bug, [Pri] Normal, [Feature Group] Emails & Domains, Triaged, [Feature] 3rd Party Cookies Management, [Platform] Simple, [Feature] Launchpad

**Comment by dchymko** [comment] 2023-07-12 18:45
Okay, the challenge I think I ran into is when I would then log in through the banner, I just came into the site admin for all my sites without any sort of clear call to action. If I went to the admin of my site I didn't see anything there either indicating that I had to do x in order for my  site to become live. I.e. I don't know what "activate admin features" means or where/how I do that.

Even after logging in, that banner still appeared even in private windows on other devices, etc.

**Comment by cuemarie** [comment] 2023-07-18 21:59
> Okay, the challenge I think I ran into is when I would then log in through the banner, I just came into the site admin for all my sites without any sort of clear call to action. If I went to the admin of my site I didn't see anything there either indicating that I had to do x in order for my site to become live. I.e. I don't know what "activate admin features" means or where/how I do that.

I've submitted a feature request with this feedback here: https://github.com/Automattic/wp-calypso/issues/79577

> Even after logging in, that banner still appeared even in private windows on other devices, etc.

Hm, the banner should be permanently dismissed either:

1. 24 hours have passed since the domain was registered.
2. After the first login to the domain.

Were you consistently seeing the message in private windows/other browsers for a long time past when you logged in via that banner?
