### ISSUE TITLE
Cart: postcode input in G Suite checkout form won't accept inputs

### ISSUE THREAD

**Issue by andfinally** [Automattic/wp-calypso#25550] opened 2018-06-18 08:22 UTC
#### Steps to reproduce
1. In a site which doesn't have G Suite, starting at https://wordpress.com/domains/manage/email/XXXXX
2. Click the "Add G Suite" button.
3. On the next page, enter a random email address and click the "Continue" button. You should be on https://wordpress.com/checkout/XXXXX.
4. Make sure the form inputs contain a first name, last name and country. Try to enter a postcode in the Postal Code input.

#### What I expected
I'm able to input a postcode

#### What happened instead
I'm unable to input a postcode.

#### Browser / OS version
Chrome 66 / macOS High Sierra

#### Screenshot / Video
![screen shot 2018-06-18 at 09 18 53](https://user-images.githubusercontent.com/1647564/41525377-af6dfcc4-72d8-11e8-86fe-9b74e08236e1.png)

#### Context / Source
#journey #reallife #user-report

**Comment by klimeryk** [comment] 2018-06-21 07:47
Closing as a duplicate of #25547.

**Closed by klimeryk** 2018-06-21 07:47 UTC
Labels: Checkout, Google Apps, Purchases, [Type] Bug

**Comment by ramonjd** [comment] 2018-06-21 08:01
Looking at  #25547 now. Thanks for pinging me @klimeryk 👍
