### ISSUE TITLE
Domains: Can't  Add a DNS Record for Root Domain (Requires Subdomain)

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-calypso#3318] opened 2016-02-15 19:40 UTC
When adding a DNS Record for a domain with WordPress.com Name Servers it is currently not possible to add a record for the root domain. For example if I wanted to use Google's MX record I would enter something like the following:
![screenshot_15-02-2016-11 31 53](https://cloud.githubusercontent.com/assets/150348/13058393/d811d1ac-d3d7-11e5-88cf-c03bb166a2ae.png)
Which results in:
![screenshot_15-02-2016-11 32 23](https://cloud.githubusercontent.com/assets/150348/13058396/dd9a7066-d3d7-11e5-8c70-3bf2e5a13ef1.png)

In a perfect world the flow would look like this:

![screenshot_15-02-2016-11 38 15](https://cloud.githubusercontent.com/assets/150348/13058524/9ec82f26-d3d8-11e5-8f45-961879e5c0a8.png)
(using @ but should also accept domain name or blank)
resulting in:
![screenshot_15-02-2016-11 38 58](https://cloud.githubusercontent.com/assets/150348/13058543/be60d5d6-d3d8-11e5-822e-f2ec97d00c82.png)

Once we allow a blank or @ to be entered for DNS settings this should no longer be an issue. 

I'm not 100% sure but I think this may have started with the merge of #2262. 

FWIW I also tested #3150 which also has the issue reported above by requiring a subdomain. See: https://github.com/Automattic/wp-calypso/pull/3150#issuecomment-184352596

Related: #1604 (blank MX records)  and #234  (root A Records)

cc:// @andreabadgley @richardmtl

**Comment by andreabadgley** [comment] 2016-02-15 21:25
I've encountered this issue several times in live chat, where a user attempts to add blank MX records, as in step 17 in [adding email through Google Apps](https://en.support.wordpress.com/add-email-through-google-apps/), and they are not able to add the records. If the user enters mygroovydomain.com in the host field, the record ends up being "mygroovydomain.com.mygroovydomain.com" as @BandonRandon mentioned above. If the field is left blank, the user receives an `Invalid Name` error for the host field:

<img width="711" alt="screen shot 2016-02-15 at 4 23 18 pm" src="https://cloud.githubusercontent.com/assets/9036382/13060590/a1c9595c-d400-11e5-90f2-8d284bff9d3a.png">

The user ends up opening a live chat and we add the records via wordpress.com/my-domains (Atlas).

**Comment by klimeryk** [comment] 2016-02-16 00:22
Thank you for a detailed report @BandonRandon and @andreabadgley, but this is a duplicate of https://github.com/Automattic/wp-calypso/issues/1604.
Also, as already discussed (https://github.com/Automattic/wp-calypso/issues/1604#issuecomment-170755762), using `@` as a special/magical character that denotes a root domain is far from ideal. It's something that Google might be using, but it's not a standard and is plain confusing - how would the user discover that he/she should input `@.example.com` to set the root domain?

**Comment by BandonRandon** [comment] 2016-02-16 08:49
@klimeryk I'm not thinking this is a duplicate of #1604 It's actually a regression. When #1604 was reported you could actually enter the root domain, and get a valid record. For example, if your domain was example.com and you entered `Example.com` in the MX field you'd get back `example.com` as the root for the MX Record. What is currently happening is you enter `example.com` in the MX field and get back `example.com.example.com`

I'm reopening this but happy to move the discussion over to #1604. IMHO it went from "not a blocker" to "blocker" as it now is preventing valid MX records from being entered.

**Comment by BandonRandon** [comment] 2016-02-16 08:58
I'm changing this to "normal" as #3235 allows blank MX records making this no longer a blocker. Sorry for the panic.

**Comment by richardmtl** [comment] 2016-02-16 14:33
> but it's not a standard and is plain confusing - how would the user discover that he/she should input @.example.com to set the root domain?

Google's [own docs say to use @](https://support.google.com/a/answer/174125?hl=en) ; I suspect that a lot of people see those instructions and will attempt it. Also, I may be misunderstanding this document, but it *does* appear to be part of a standard ; see this [Stackoverflow comment](http://serverfault.com/a/83877) and the linked document. Again though, I'm not an expert, but it does seem to be something that is used de facto by many places, including the big one (Google Apps), so I think we should support it.

**Comment by BandonRandon** [comment] 2016-02-16 17:25
While I do agree that we should support @ (even if we convert it to the domain name on save) IMHO that's the core of #1604. This issue is open to allow the full domain name to be entered into the host field (as our documentation currently states) without using the domain as a subdomain.

**Comment by klimeryk** [comment] 2016-02-16 18:07
> Google's own docs say to use @ ; I suspect that a lot of people see those instructions and will attempt it. Also, I may be misunderstanding this document, but it does appear to be part of a standard ; see this Stackoverflow comment and the linked document. Again though, I'm not an expert, but it does seem to be something that is used de facto by many places, including the big one (Google Apps), so I think we should support it.

They say `Blank or @` - it seems more intuitive to me to support a blank subdomain as meaning "root domain" than `@` (which is usually connected with an email address for most people). @breezyskies agreed with this in https://github.com/Automattic/wp-calypso/issues/1604#issuecomment-170755762
BTW, thanks for pointing out that how it's defined in the RFC - but for me that's an implementation detail that we shouldn't bother the user with. Just as we don't tell them about FQDN vs DN, etc.

> This issue is open to allow the full domain name to be entered into the host field (as our documentation currently states) without using the domain as a subdomain.

I'm sorry - I'm kinda lost. The current implementation is that the `Host` field has the domain part automatically appended (which is hinted by the `.example.com` suffix in the input field). The user only has to input the subdomain (which, in some cases, is optional). Requiring the user to input the whole domain into the input field does not make sense - looking at it from the UI. But when implementing this, I _did_ add support for such a corner case - if you input `test.example.com` into the `Host` field, the domain part will be stripped and `test` will be used.

You are right that inputting just the root domain (`example.com`) will result in `example.com.example.com` - which is a bug that I'll fix. I'll also add a corner case for `@` so that our HEs don't have to deal with additional work :heart: But this is still a corner case and inputting the root domain in this manner should not be officially supported - if that's how the documentation is recommending it right now, then they should be changed. Please ping me on Slack if I should bother someone directly or if you already know who can help out with this :)

Please don't misunderstand me - I'm more than happy to lessen the workload for our Happiness Engineers. But the way this issue was phrased seemed to me like you want to have `@` or `example.com` as the main and official way of inputting root domain, while the new UI is strongly suggesting just leaving the field blank. Hence my apprehensive approach to this issue.

**Comment by BandonRandon** [comment] 2016-02-16 21:11
Thanks for the detailed response @klimeryk 
> But the way this issue was phrased seemed to me like you want to have @ or example.com as the main and official way of inputting root domain,
I can see how it seems that way. I think it's more important that we allow for user error. It's not uncommon for a user to want to use `@` in the subdomain field. Even if our documentation and Happiness teams encourage leaving it blank we can only reach so many users. By converting `@` to blank on save we can avoid some confusion. 

> But this is still a corner case and inputting the root domain in this manner should not be officially supported - if that's how the documentation is recommending it right now, then they should be changed. 
Up until #3235 leaving the root field blank resulted in an error. For this reason we recommended/required the domain name be entered into the field. Myself and others can work on re-creating the screenshots/updating the documentation. However, if we support `example.com` and removing it on save that would be best for now. In other words, save MX `example.com` as `example.com` instead of `example.com.example.com`. I would argue if someone entered `example` then we save that as `example.example.com`. The exception only applying when the full domain is entered.

**Closed** 2016-02-23 11:13 UTC
Labels: Domains, [Pri] Normal, [Type] Bug
