### ISSUE TITLE
Updates to all e2e tests for Nav Unification

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#49250] opened 2021-01-25 10:00 UTC
The e2e test suite in Calypso is designed for the existing Calypso navigation and is not ready for the Nav Unification feature.

As we've changed the DOM structure it's likely we're going to need to visit all the tests and check that they will work with the new feature active.

This will likely require:

1. Identifying core reusable helper components (eg: [`SidebarComponent`](https://github.com/Automattic/wp-calypso/blob/c5c6765ed1e0f46d18a7b256312e86a698df1d06/test/e2e/lib/components/sidebar-component.js)) and adjusting to expect the new Navigation - one time fix which propagates to all test using this helper component.
2. Identifying edge cases - any tests that don't use the helpers or rely on specific assertions will need adjusting manually on a case-by-base basis.

@bsessions85 @cathymcbride Do you have any ideas on how we can best handle a migration of the test suite to be ready to handle the Nav Unification feature.

Currently the Nav Unification feature is only available to a12s so we may need a mechanism to conditionally enable it [the feature] within e2e tests so we add conditionals within existing tests or create additional helper components.

Any advice here would be much appreciated.

### Issues List

The progress is tracked as a milestone https://github.com/Automattic/wp-calypso/milestone/334

**Comment by getdave** [comment] 2021-01-25 11:18
Related https://github.com/Automattic/wp-calypso/issues/49243

**Comment by mmtr** [comment] 2021-01-25 15:52
@WunderBart provided a comprehensive list with what's needed to start working on this while the feature is not enabled to all users: pciE2j-bk-p2#comment-264

**Comment by bsessions85** [comment] 2021-01-26 18:47
Yes, @WunderBart  did a great job outlining the best way to do this. I'm happy to help where I can with this.

**Comment by cpapazoglou** [comment] 2021-02-16 20:39
While running the tests, I discovered that we need to adjust the following:

- a way to hide the nav-unification modal, otherwise all elements underneath are not "clickable". We can follow this https://github.com/Automattic/wp-calypso/blob/c32e02f590db39784444a0209b3bfdb574b4418e/test/e2e/lib/gutenberg/gutenberg-editor-component.js#L672
- a way to properly "navigate" in the sidebar. The current implementation uses an `li` attribute `data-tip-target` https://github.com/Automattic/wp-calypso/blob/25b7ee52633a566d8073f7a79100199c8cd7fc6b/test/e2e/lib/components/sidebar-component.js#L177 which is arbitrarily set for each menu item registered https://github.com/Automattic/wp-calypso/blob/8be8a7d309a206eed75fef8e896f52dcca83c2c9/client/my-sites/sidebar/index.jsx#L842. Adding the `data-tip-target` attribute in the admin-menu endpoint seems straightforward but will make the response bigger. Otherwise we may resort in checking against the `data-e2e-sidebar` (which is translatable)?
- there are cases where e2e tests expand to WP Admin pages https://github.com/Automattic/wp-calypso/blob/c9d506afa6cf93d676e086a4b3e2b4fb84d6a0ca/test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js#L61.  
- There are several WP Admin helpers `test/e2e/lib/pages/wp-admin` that will need to be checked if they still make sense. Mainly used by `specs-jetpack`.
- We will need to consider adding new tests especially for nav-unification features like eg "Replace all dashboard pages with WP Admin equivalents when possible." toggle

I have drafted #50144 so we can run the tests with nav-unification enabled. We need to at least resolve the first two issues, so that we potentially can discover more.

**Comment by cpapazoglou** [comment] 2021-02-17 07:46
👋 @bsessions85 can you help us reach some technical decisions here? I would appreciate it 🙏!

1. There is a modal shown after login
![](https://cln.sh/igfEOT+) 
is interacting with it and closing it the best way to go here? I am only asking cause it appears on almost all tests and will surely make them slower. 
2. Since our menu items are generated dynamically, they don't have the `data-tip-target` needed to be used for e2e navigation. What's your take here? 
- manipulate the endpoint so that it contains the `data-tip-target` static keywords and possibly change nothing in https://github.com/Automattic/wp-calypso/blob/25b7ee52633a566d8073f7a79100199c8cd7fc6b/test/e2e/lib/components/sidebar-component.js#L177. The downside here is that we make the api response bigger / slower.
- use the `data-e2e-sidebar` which already exist. The downside here is that these are translatable labels and they may change thus breaking the tests.

Moreover, we will probably need to make some changes in several tests. Is there a preference here?
- create new specs / helpers
- enhance the existing ones by using conditionals
I assume that the decision per case might be different, but thought checking early for some context will help.

**Comment by tjcafferkey** [comment] 2021-02-17 14:11
Firstly amazing sleuthing @cpapazoglou, and thanks for laying this out in an easy to understand/consume format.

>a way to hide the nav-unification modal, otherwise all elements underneath are not "clickable". We can follow this

This makes sense, looking at the welcome modal they appear to be using the same `<Guide />` component so dismissing it should be a lift & shift task into a more generic class for future uses of this modal component.

>is interacting with it and closing it the best way to go here?

An alternative would be to not render the modal in the test scenario, as this wont be around forever as it wont always be considered 'new'. However personally I'm leaning towards interacting with it in the tests as this is the experience customers will be going through and being that it covers the entirety of the users screen we'd rather know if there are any issues.

>Adding the data-tip-target attribute in the admin-menu endpoint seems straightforward but will make the response bigger.

Adding this attribute, depending on the effort involved makes sense. I can't imagine the increased response size would be significant but please tell me if I'm wrong here.

The `data-tip-target` looks more like a slug meaning if any labels change or translations occur could be less likely to report false negatives.

Would we need to make any futher amends to this sidebar lib. The behaviours between the two navigations are slightly different. E.g. on the current nav each parent item expands on click, on the unified nav they toggle on hover. I can also see a `expandDrawerItem` in the sidebar lib [here](https://github.com/Automattic/wp-calypso/blob/25b7ee52633a566d8073f7a79100199c8cd7fc6b/test/e2e/lib/components/sidebar-component.js#L22).

>Moreover, we will probably need to make some changes in several tests. Is there a preference here?

Just to confirm, do you mean in several existing tests because we need to ensure our updates for the unified nav don't break the current nav specs?

**Comment by mmtr** [comment] 2021-02-17 14:31
> An alternative would be to not render the modal in the test scenario, as this wont be around forever as it wont always be considered 'new'. However personally I'm leaning towards interacting with it in the tests as this is the experience customers will be going through and being that it covers the entirety of the users screen we'd rather know if there are any issues.

👍 

> Adding the data-tip-target attribute in the admin-menu endpoint seems straightforward but will make the response bigger

Can we reuse the menu slugs as values of the `data-tip-target` attributes? That way we wouldn't need to change anything in the API.

> > Moreover, we will probably need to make some changes in several tests. Is there a preference here?
> Just to confirm, do you mean in several existing tests because we need to ensure our updates for the unified nav don't break the current nav specs?

I had the same question. Do we need to maintain the tests for the existing navigation? I assumed we only needed to migrate the tests to the new unified menu.

**Comment by bsessions85** [comment] 2021-02-17 16:48
1. For the modal, It would be better to just make sure the modal shows up in one test and then force dismiss it in later tests if that is driven by cookie. If it isn't, then we can just run through it every time. It will add a few seconds but it shouldn't matter much. Like was mentioned above, it is what the user would be experiencing so we want to stick to that.

2. I would lean towards getting the data-tip-target in there unless performance is noticeably reduced because of it.  It really helps make things more stable.

> I had the same question. Do we need to maintain the tests for the existing navigation? I assumed we only needed to migrate the tests to the new unified menu.

Are we looking to carry both versions for a while or just switch everyone over as soon as we're comfortable with the quality? Maintaining two versions is a pain with the e2es, so if we're going to be switching everyone over soon, lets just have the tests ready to go  in a PR and replace the existing tests.

**Comment by cpapazoglou** [comment] 2021-02-17 16:53
@bsessions85 thanks for chiming in!

> Are we looking to carry both versions for a while or just switch everyone over as soon as we're comfortable with the quality? Maintaining two versions is a pain with the e2es, so if we're going to be switching everyone over soon, lets just have the tests ready to go in a PR and replace the existing tests.

Nav-unification will be rolled out gradually. I can imagine 1 - 2 months (max) of having some users with nav-unification and the rest having it disabled. The rollout period depends only on the issues that may arise, so it may be much less too.

**Comment by cpapazoglou** [comment] 2021-02-17 17:02
> Would we need to make any futher amends to this sidebar lib. The behaviours between the two navigations are slightly different. E.g. on the current nav each parent item expands on click, on the unified nav they toggle on hover. I can also see a `expandDrawerItem` in the sidebar lib [here](https://github.com/Automattic/wp-calypso/blob/25b7ee52633a566d8073f7a79100199c8cd7fc6b/test/e2e/lib/components/sidebar-component.js#L22).

@tjcafferkey, sorry I should have already mentioned that possibly we won't need to change something more in the lib, as the `expandDrawerItem` https://github.com/Automattic/wp-calypso/blob/25b7ee52633a566d8073f7a79100199c8cd7fc6b/test/e2e/lib/components/sidebar-component.js#L41 didn't create any problems during my tests.

**Comment by getdave** [comment] 2021-02-18 09:57
> Are we looking to carry both versions for a while or just switch everyone over as soon as we're comfortable with the quality? Maintaining two versions is a pain with the e2es, so if we're going to be switching everyone over soon, lets just have the tests ready to go in a PR and replace the existing tests.

@bsessions85 The issue is we don't know if/when everyone will be comfortable to leave Nav Unification "on". That said, due to the lack of evidence to the contrary at this stage, I think we have to plan for it being a permanent change but one which is rolled out gradually.

Therefore should we 

1. Update the e2e tests at the same time Nav Unification goes live? 
2. Maintain both versions of the tests for a short period whilst the rollout occurs. Once done we removed the other version.

The complexity of #2 seems high but I'm concerned about breaking deployment flows and losing confidence in our automated quality assurance during the rollout period.

**Comment by tjcafferkey** [comment] 2021-02-18 10:36
Apologies if this has already been considered/answered elsewhere but just making sure.

Aside from writing new E2E tests so that they cover the unified navigation experience. Have we also discussed writing E2E tests to cover the two different experiences a user will encounter when toggling between Calypso and WP Admin links?

And furthermore are there any tests that are asserting against the URL visited as this will change based on the toggle.

**Comment by mmtr** [comment] 2021-02-18 10:48
> I think we have to plan for it being a permanent change but one which is rolled out gradually.

We should be pragmatic here. Since it's going to be a permanent change, let's not invest any effort on maintaining the existing navigation. We can switch the new unified nav on the E2E tests, even if the feature is rolled out gradually. The existing navigation has been quite stable for the last months/years, and it's extremely unlikely that a regression is introduced while the new new unified navigation is being rolled out, so I think we'll be fine without E2E tests covering the existing navigation.

> Have we also discussed writing E2E tests to cover the two different experiences a user will encounter when toggling between Calypso and WP Admin links?

I'd consider this a nice-to-have, but not something needed prior to launch, so it can be a follow-up. The only thing that is required prior to launching is to update the existing E2E suite and make sure all their tests pass with the new unified navigation.

**Comment by cpapazoglou** [comment] 2021-02-18 11:02
> ... The only thing that is required prior to launching is to update the existing E2E suite and make sure all their tests pass with the new unified navigation.

Exactly this is the scope of this issue. Writing new tests to cover WP Admin screens (which is where Users will land with the toggle on) will be really painful.

**Comment by tjcafferkey** [comment] 2021-02-18 11:05
>Exactly this is the scope of this issue. Writing new tests to cover WP Admin screens (which is where Users will land with the toggle on) will be really painful.

Okay great sounds good. Was just making sure 😀

**Comment by getdave** [comment] 2021-02-22 12:10
Removing the `Blocker` label as this is tracked elsewhere on our roadmap.

**Closed as completed** 2021-04-01 16:42 UTC
Labels: Task, Testing, [Feature] Calypso & wp-admin Navigation
