### ISSUE TITLE
Site style for links overrides the block style for links

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#78013] opened 2023-06-09 13:16 UTC
### Quick summary

If I set a custom Font Family for a Page Link block, that font is shown correctly in the editor and site:

![gMfPVDWbcMoCjZnyLkCIsIhL5WbyNq13UhSZOf6n.jpg](https://github.com/Automattic/wp-calypso/assets/51966986/ba499106-e78a-4344-807d-0bd9d5b648f6)

However, if I then set a different Font Family than “Default” for my site’s Links under global styles, that Font Family will override the setting set on the individual Page Link blocks in the Navigation block:

![SHslGSVLfgS6rghruH47qEXBnt6mvEAtczuiLGAB.jpg](https://github.com/Automattic/wp-calypso/assets/51966986/8b3cb44e-bf9e-4162-800e-ab956e3de738)

The same behavior can be observed for size and color settings.

### Steps to reproduce

1. Set a font family for Page Links in the Navigation block to a font other than the default
2. Change the font family to a different font again for Links in the site's styles editor 

### What you expected to happen

All links on the site should show the font family specified in the site's styles editor EXCEPT where the font family was set to something different on an individual block.

### What actually happened

All links on the site changed to the font family specified in the site's styles editor, no matter what their local block settings for links were set to.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Tested on theme Upsidedown

**Comment by john-legg** [comment] 2023-06-09 22:29
📌 REPRODUCTION RESULTS

Tested on Simple – **Replicated** 
Tested on Atomic – **Replicated** 
Replicable outside of Dotcom – **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to reproduce the issue on Chrome, Firefox, and Safari with different plans and themes on Simple and Atomic (WPCOM and self-hosted).

https://github.com/Automattic/wp-calypso/assets/96805492/914b23b1-fc1d-4fc8-bbd6-f41ef6836aec

It also appears that changing the local style _after_ setting the sitewide style still doesn't allow the block style to be changed.

https://github.com/Automattic/wp-calypso/assets/96805492/982d19ce-0f95-4029-9fdc-4f87332e07a1



📌 ACTIONS

Assigned to `T-Rex` column (@Automattic/t-rex). Please feel free to reassign if needed!

**Comment by cuemarie** [comment] 2023-06-14 22:52
I think this is actually a duplicate of:

- https://github.com/Automattic/wp-calypso/issues/74234

@john-legg Do you agree?

**Comment by john-legg** [comment] 2023-06-15 21:26
Ah, great catch, Marie! I definitely agree, so I'll close this as a duplicate of https://github.com/Automattic/wp-calypso/issues/74234.

**Closed as not planned by john-legg** 2023-06-15 21:26 UTC
Labels: Bug, [Pri] Normal, [Platform] Simple, [Platform] Atomic
