### ISSUE TITLE
Using Jetpack Connect fails after logging in with Login component

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/wp-calypso#14145] opened 2017-05-17 02:12 UTC
#### Steps to reproduce
1. Starting at URL: calypso.localhost:3000/jetpack/connect ( running master )
2. Ensure you are logged out of wordpress.com
3. Enter the URL of an unconnected Jetpack site
4. When you land on the create your account page ( calypso.localhost:3000/jetpack/connect/authorize ) click 'Already have an account? Login'
5. Login to a non-2fa wordpress.com account
6. Click 'Approve' and get an error
7. Click 'Approve' again, and it should work just fine

#### What I expected
That clicking 'Approve' would work correctly on the first try.

I can look into this when I have some time as I've worked a lot with the JPC components. But perhaps someone who's worked on login can also take a peek. 

CC: @sirreal @scruffian

**Comment by stephanethomas** [comment] 2017-06-19 09:24
Is this still happening, or has it been fixed? https://github.com/Automattic/wp-calypso/issues/14683 seems to be slightly related to this problem by the way.

**Comment by oskosk** [comment] 2017-06-26 17:07
@roccotripaldi I'm not able to reproduce this anymore. Tried a few times, the approve click works as expected the first time. Could you close this if you're not able to reproduce ?

**Comment by oskosk** [comment] 2017-06-26 18:19
@roccotripaldi disregard my last comment. I've just witnessed this error.

**Comment by oskosk** [comment] 2017-06-26 23:47
After checking some things, I noticed that the first request to `/jetpack-blog/login` is returning a response body of
```
{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"not_verified","message":"Could not verify your request."}}
```

**Comment by stephanethomas** [comment] 2017-08-25 08:56
Circling back on old issues, is this still a concern? :)

**Comment by stephanethomas** [comment] 2017-12-01 10:17
@roccotripaldi, @oskosk: can we close that issue?

**Closed** 2018-01-19 14:42 UTC
Labels: Jetpack, Login, [Type] Bug
