### ISSUE TITLE
Jetpack: Subfolder installs returned to jetpack/connect after connecting

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#13855] opened 2017-05-10 09:08 UTC
After a Jetpack site installed in a subfolder (`example.com/jetpack-site`) is connected, the user is returned to the Jetpack connect screen (same as `wordpress.com/jetpack/connect`).

The URL appears to be correct (`https://wordpress.com/jetpack/connect/plans/example.com::jetpack-site`), but the corresponding page is not displayed.

Refreshing with the updated URL _does_ display the plans page as expected.

#### Steps to reproduce
1. Connect a Jetpack site installed in a subfolder

#### What I expected

See the plans page as the URL indicates.

#### What happened instead

I'm on the Jetpack connect page.

#### Browser / OS version

macOS / Chrome 60

#### Context / Source

This particular site is part of a multisite install.

**Comment by jeherve** [comment] 2017-05-10 12:52
Closing as duplicate of #13509

**Closed by jeherve** 2017-05-10 12:52 UTC
Labels: Jetpack, [Type] Bug
