### ISSUE TITLE
Cover Block - Special characters not working in Full Width alignment

### ISSUE THREAD

**Issue by smithkyle45** [Automattic/wp-calypso#44770] opened 2020-08-07 17:55 UTC
#### Steps to reproduce

_(tested with Mayland theme on Business/AT site)_

1. Add a cover block to a page, choose an image
2. Insert heading (or paragraph) text that includes a special character, **i.e. Reesé Puffs**
3. Set *Full Width* alignment 
4. Preview or view the live page

#### What I expected

To view the text as it was input.

#### What happened instead

With Full Width alignment set on the cover block, the text is converted to **ReesÃ© Puffs** on the live page or preview. _It will appear correctly in the editor_.

#### Browser / OS version
Chrome 84.0.4147.105  / macOS Catalina 10.15.5

#### Screenshot / Video

<img width="1139" alt="cover-block-special-characters" src="https://user-images.githubusercontent.com/45518174/89672601-2b3de680-d8a2-11ea-870a-ce20a1e486ae.png">

#### Context / Source

User reported this behaviour in 23212023-hc
I was able to replicate this on my own test site.

Ticket Follow up: 3206595-zen

**Comment by ockham** [comment] 2020-08-11 10:25
Duplicate of #44759. Should be fixed now.

**Closed by ockham** 2020-08-11 10:25 UTC
Labels: Blocks, [Type] Bug
