### ISSUE TITLE
Gutenberg: Gallery block is not rendered correctly

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#27748] opened 2018-10-10 15:54 UTC
Gallery block works as expected in the editor shell, but when the post is saved its images are not positioned correctly. Instead of being show in multiple columns, the rendered images are displayed bellow each other (in one column, one image per row).

**Comment by vindl** [comment] 2018-10-10 20:03
After some further testing I've managed to narrow down the reproductions steps - this only occurs when center alignment is applied to the gallery block. The same issue is present when saving posts from Gutenberg in `wp-admin`.

**Comment by vindl** [comment] 2018-10-10 20:51
This issue is present in core Gutenberg too - I tested it with lastest master on docker local dev environment.

**Comment by Copons** [comment] 2018-10-11 11:01
I can confirm that the block is rendered appropriately by the theme, and the issue with center alignment happens on Core as well (looks like it has been [already reported](https://github.com/WordPress/gutenberg/issues/9531) too).

Closing because this is not part of our integration effort.

**Closed by Copons** 2018-10-11 11:01 UTC
Labels: [Goal] Gutenberg, [Type] Bug

**Comment by vindl** [comment] 2018-10-11 13:02
> looks like it has been already reported too

@Copons I've read through this report but I don't think it's describing the same thing. To clarify, before applying any alignment to Gallery the block is rendered properly:

<img width="392" alt="screen shot 2018-10-11 at 15 00 06" src="https://user-images.githubusercontent.com/1182160/46805868-7a7a6500-cd66-11e8-913f-c23022e315fb.png">

But after I apply alignment and update the post it turns into this:

<img width="133" alt="screen shot 2018-10-11 at 15 00 23" src="https://user-images.githubusercontent.com/1182160/46805919-8f56f880-cd66-11e8-9101-3e50d80aaead.png">

**Comment by vindl** [comment] 2018-10-11 13:12
I was about to report it in the core repo but found the one that fits the description: https://github.com/WordPress/gutenberg/issues/9533. In any case, I think we can keep this one closed for now and possibly look into contributing a core fix later.
