### ISSUE TITLE
Plans navigation tab dropdown auto closes early on some clicks (mobile) 

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#64395] opened 2022-06-07 06:26 UTC
#### Steps to reproduce

With a mobile viewport, view the plans screen, e.g. http://calypso.localhost:3000/plans/example.com

Select the plans dropdown to change "tabs"

When selecting the dropdown, it sometimes automatically closes.

This happens mostly on first load sometimes, other times if you double/tripple click fast enough and get it into the right state it can be reproduced that way too.

#### Screenshot / Video

Video below shows the issue on the first click of the first load, after that I'm not able to repro

https://user-images.githubusercontent.com/811776/172310300-ad799735-f86f-4fea-bdbb-7946124697fc.mp4

#### Context / Source

This is currently failing the e2e test for plan renewal on mobile.

p1654264833113049-slack-C1A1EKDGQ

Likely related to this similar issue https://github.com/Automattic/wp-calypso/issues/56038

**Comment by worldomonation** [comment] 2022-06-07 19:34
Related issue on e2e framework side: https://github.com/Automattic/wp-calypso/issues/64389

My understanding of this (from a black box perspective) is that this is caused by rest of the page loading past the `networkidle` event firing. The lazy loading ends up swallowing the click to toggle open the Navtab.

On the e2e framework side, I can work around this by waiting for the `main` element to be stable, which _should_ wait for the element to be stable (ie. finish animations and/or lazy loading).

Interestingly, this isn't observed on other places where Navtabs are used! eg. Media page.

Ideally though, an code wrangler would:
- take stock of all instances of Navtabs used in Calypso;
- ensure they all derive from the same implementation;

**Comment by cuemarie** [comment] 2023-05-17 21:05
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Atomic on Safari Mobile - Could Not Replicate

📌 ACTIONS
- Closing as resolved

**Closed as completed by cuemarie** 2023-05-17 21:05 UTC
Labels: Bug, [Pri] Normal, Mobile Web, Triaged
