### ISSUE TITLE
Store - Promotions: Unable to add particular product

### ISSUE THREAD

**Issue by kristarella** [Automattic/wp-calypso#21782] opened 2018-01-24 06:56 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/store/promotion/paraphernaliauniversity.com/c1400
2. Search products for Melanin
3. Click [Select Variations] for “Melanin World Tour”
4. Choose options

#### What I expected
Except variations to appear as a listing with a checkbox next to it

#### What happened instead
Nothing at all

As interim solution I asked user to add via wp-admin

#### Browser / OS version
Chrome/Mac OS 10.13.2

#### Screenshot / Video

Variant chosen, but product not added:

![image](https://user-images.githubusercontent.com/2031017/35318462-9abe8872-012f-11e8-91fe-210e2d2192bd.png)

Different product added as normal:

![image](https://user-images.githubusercontent.com/2031017/35318487-ba0c56e6-012f-11e8-8929-c3385337d21c.png)

#### Context / Source

#user-report 1594037-hc

**Comment by designsimply** [comment] 2018-02-22 23:58
I tried opening https://wordpress.com/store/promotion/paraphernaliauniversity.com/c1400 and it says, "some of your site settings couldn't be retrieved" so I couldn't test on that site.

I tried recreating the conditions using the following steps and I was unable to reproduce the problem described:

1. Start with WordPress.com Business Plan site with WooCommerce installed
1. Go to Store > Products > Add.
1. Turn the option on for "[Product] has variations, like size and color."
1. Add a "Color" variation with "Red, Green, Blue".
1. Add a "Size" variation with "Small, Medium, Large".
1. Add a "Type" variation with "Long Sleeve, Short Sleeve".
1. Add Inventory, Price, and Dimensions & weight for each variation.
1. Save changes.
1. Go to Store > Promotions > Add promotion.
1. Set "Applies to" to "Specific Products."
1. Click "Select variations" and select something for each variation dropdown that displays.

<strong>Result:</strong> the checkbox next to the product appears normally after I have clicked "Select variations" for the promotion and selected something for all three variations displayed for the product.

![screen shot 2018-02-22 at thu feb 22 4 45 06 pm](https://user-images.githubusercontent.com/1119271/36570599-ff9a1406-17ef-11e8-88c8-8a6b239c0713.png)
<sup>Seen at https://wordpress.com/store/promotion/madefortesting347.blog/c109 using Chrome 64.0.3282.167 on macOS 10.13.3.</sup>

I'm not sure what is different in my test case compared to what the user setup for their "Melanin World Tour" product.

I wondered if it might be browser related. I tested with Firefox 58.0.2 and Safari 11.0.3 and Chrome 64.0.3282.167 on macOS 10.13.3 and couldn't reproduce the problem on my own site in any of those.

The next best debugging information to collect here would be to either come up with a better set of steps that reliably reproduces the problem (my steps might be missing something that I don't know about), or try it on a working site with the problem active where the promotions page can be loaded successfully, and then [check the browser console for errors](https://en.support.wordpress.com/browser-issues/advanced-browser-troubleshooting/#javascript-errors-in-google-chrome). Since a workaround was provided in the case of 1594037-hc, and since this problem has only been reported the one time, I would recommend leaving that case as is and checking for errors the next time we have a case where the problem is visible.

**Comment by rachelmcr** [comment] 2018-03-01 12:59
>Since a workaround was provided in the case of 1594037-hc, and since this problem has only been reported the one time, I would recommend leaving that case as is and checking for errors the next time we have a case where the problem is visible.

Agreed. Closing this for now; we can reopen when we have reliable steps to reproduce.

**Closed by rachelmcr** 2018-03-01 12:59 UTC
Labels: Store, [Pri] Low, [Triage] Close Me, [Type] Help Request
