### ISSUE TITLE
Editor: Media: Jetpack connected site seeing only 20 images in Media Library

### ISSUE THREAD

**Issue by lschuyler** [Automattic/wp-calypso#1191] opened 2015-12-02 17:30 UTC
When using the Calypso editor to write a new post or page for a Jetpack connected site, only the last 20 images are available in the Media Library from the "Add Media" button. There is no way for a user to add previously uploaded images into their post or page.

Reported in 2441445-t.

**Comment by lancewillett** [comment] 2016-03-11 22:11
I'm able to confirm this — it's not just images, but the last 20 "media items" including video, audio, and images.

Testing with a Jetpack site, themebreaker.wordpress.net — I see 50 items in wp-admin media library:

<img width="1250" alt="screen shot 2016-03-11 at 15 10 59" src="https://cloud.githubusercontent.com/assets/66797/13716958/873747ee-e79b-11e5-9057-1984f615fe59.png">

In Calypso I see only 20:

<img width="1255" alt="screen shot 2016-03-11 at 15 10 21" src="https://cloud.githubusercontent.com/assets/66797/13716960/90dd5734-e79b-11e5-8f71-47fb08d00ece.png">

**Comment by jeherve** [comment] 2016-03-31 17:15
Also reported here:
https://wordpress.org/support/topic/in-client-not-all-images-show?replies=1&view=all

**Comment by hoverduck** [comment] 2016-05-19 16:33
19May16 Bug Scrub

Confirmed this is still an issue.  I can only see 20 out of 30 media items (all images in this case) from Calypso.

**Comment by thehenrybyrd** [comment] 2016-08-22 20:13
Confirmed again in #452463-chat #user-report

**Comment by lancewillett** [comment] 2016-10-31 19:02
I confirmed this in a test today during a bug scrub. Added to Jetpack Sites / Posts Parity milestone, because if you move from WP.com to self-hosted — you'll immediately not have access to older uploaded files. That seems pretty bad.

**Comment by aduth** [comment] 2016-11-07 15:03
Fixed in r145158-wpcom , Jetpack change sync pending at https://github.com/Automattic/jetpack/pull/5529

**Closed by aduth** 2016-11-07 15:03 UTC
Labels: Jetpack, Media, [Pri] High, [Type] Bug
