### ISSUE TITLE
Purchase Management: Remove the "You purchased X with credits" message

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#70011] opened 2022-11-14 20:07 UTC
### What

When a subscription has been purchased with credits, you get a "You purchased X with credits" message like this at the top:

![credits](https://user-images.githubusercontent.com/235183/201755155-ee59f8db-604a-4042-af5f-1de20f6e5f3a.png)

This message isn't shown in other cases where the subscription has no payment method attached.  So let's remove it here (or alternatively, add something like it for the others).

Based on some discussion in pdrWKz-El-p2.

### Why

We now have other messages on the screen (as shown above) which encourage people to add a payment method if they don't have one, so this historical message that's specific to credits seems redundant.

**Comment by DavidRothstein** [comment] 2022-11-14 20:19
Actually, it's weird that the "You don’t have a payment method to renew this subscription" message (in the bottom right of this screenshot) isn't clickable -- maybe we should add a clickable "Add one" sentence to it as part of this, which would be an overall improvement.

**Comment by michaeldcain** [comment] 2022-11-15 19:00
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/69497. Let's consolidate the logic for non-rechargeable payment method notices.

**Closed as completed by michaeldcain** 2022-11-15 19:00 UTC
Labels: Enhancement, [Feature] Purchase Management, Quick Fix
