### ISSUE TITLE
Images size responsivness issues

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#73518] opened 2023-02-18 09:52 UTC
### Quick summary

A user reached out to us via email regarding the images they have on the site and that they are not resizing well on mobile.

### Steps to reproduce

1. Create a new page and add a Row block
2. Try to add 3 image blocks of the same size in the row
3. Check for the results both on desktop and on mobile

### What you expected to happen

The images to have the same size.

### What actually happened

The images are different sizes on mobile:

![image](https://user-images.githubusercontent.com/6737345/219853497-7a7bc326-0f19-459c-a531-3de625c504a2.png)

![image](https://user-images.githubusercontent.com/6737345/219853948-424322e1-73ff-40fb-8687-3374da905c02.png)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Theme: TwentyTwenty-Two

The images were added on the user's site through the Index template, but it's not any different if we use a page/post.

Using the Columns block appears to help, but it could limit the layout options. I've tested the workaround again using another theme(Quadrat) and now I'm not sure what's the issue.

5951322-zen

**Comment by cuemarie** [comment] 2023-03-22 20:45
📌 Message to Author
- Hey @Robertght ! I'm not sure I understand the problem here.  It appears from your provided screenshots that the images are all different widths, and are responding by adjusting to the same height.  With the built-in white space around the graphic within each image, that makes them look quite differently sized. 
- Can you provide steps to reproduce this with similar test images, so we can try to replicate any underlying issues?
     - _Always make sure to exclude any user-specific information in your screenshots or details._
     - [ ] Please edit the report/comment above to use remove user-specific information. Don't forget to [delete the previous revision](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) from history.

**Comment by cuemarie** [comment] 2023-03-30 22:30
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- User reported this issue while on the Premium plan and using theme TT2.  I've used the same images they were using in my tests, and cannot reproduce the issue they ran into when the 3 images are set up inside a row block.

https://user-images.githubusercontent.com/27249804/228977767-8800171f-21fe-456c-a6ec-816f42b5b336.mp4

- Since the user report was on a template, and they've implemented a workaround, I can't dig any further into how their set up differed from my tests.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

**Closed as completed by cuemarie** 2023-03-30 22:30 UTC
Labels: Bug, [Pri] Low, Triaged, [Closed] Not Reproducible, [Platform] Simple
