### ISSUE TITLE
Purchases: Cancel Privacy Protection consistency cleanup

### ISSUE THREAD

**Issue by breezyskies** [Automattic/wp-calypso#2139] opened 2016-01-05 23:51 UTC
Canceling Privacy Protection looks inconsistent with the standard product cancelation screen:

Standard Cancel | Privacy Cancel
------------ | -------------
![screen_shot_2016-01-05_at_3_47_56_pm](https://cloud.githubusercontent.com/assets/3011211/12130983/cae9e2c8-b3c3-11e5-8c5e-4cd671996b11.png) | <img width="750" alt="screen_shot_2015-12-30_at_4_10_45_pm" src="https://cloud.githubusercontent.com/assets/3011211/12130943/70dab906-b3c3-11e5-97d8-e2cc11edafb0.png">

Another thought: Canceling Privacy on it's own seems pretty edge case, so maybe we don't need to give it the prominence that canceling the domain in full has (i.e. right in the purchase details navigation). Not sure about this one, but just something to think about.

cc: @mikeshelton1503

**Comment by fabianapsimoes** [comment] 2016-03-18 15:13
Duplicate of #1938.

**Closed by fabianapsimoes** 2016-03-18 15:13 UTC
Labels: Purchases, [Type] Enhancement
