### ISSUE TITLE
Logged in but settings asks me to upload a profile photo

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-calypso#13338] opened 2017-04-24 13:32 UTC
I was using Chrome and refreshed a few times to make sure. As you can see it pulls my avatar for the bar, but it isn't showing on my profile - most peculiar.

![2017-04-24 at 14 31](https://cloud.githubusercontent.com/assets/253067/25339506/e12dc2a4-28fa-11e7-8ebf-59fa3c7e3879.png)

**Comment by karmatosed** [comment] 2017-04-24 13:34
Worth adding that the app has my profile:

![2017-04-24 at 14 34](https://cloud.githubusercontent.com/assets/253067/25339590/28bdb2a0-28fb-11e7-9c07-181c302a29d7.png)

**Comment by rachelmcr** [comment] 2017-12-11 22:41
#bug-scrub

I can no longer reproduce this issue in Chrome 62.0.3202.94, Mac OS 10.12.6. Closing as I can't reproduce this, but please reopen if it persists for you!

**Closed by rachelmcr** 2017-12-11 22:41 UTC
Labels: Me, [Type] Bug
