### ISSUE TITLE
Gallery Block: error when link to is set to media file

### ISSUE THREAD

**Issue by catkit** [Automattic/wp-calypso#38408] opened 2019-12-13 14:35 UTC
This user reported that whenever they add a gallery block and "Link to" is set to "Media File" option and they try to edit the post again, the block looks broken and displays the "This block contains unexpected or invalid content." warning. I was able to reproduce this error in my test site.
If convert to HTML is selected the gallery works as expected, but then it's an HTML block.
If convert to block is selected the gallery is replaced by a single image block.
Sometimes it will display the "The backup of this post in your browser is different from the version below." warning.
Clicking "Restore the backup" fix the gallery block, but after coming back to edit the post it will look broken again and the restore backup option won't appear again.

#### Steps to reproduce
1. Create a new post and add a gallery block
2. Save the post and close it
3. Open the post to edit it again

#### What I expected
The gallery block shouldn't look broken.

#### What happened instead
The gallery block looks broken and displays the "This block contains unexpected or invalid content." warning

#### Screenshot / Video
![gallery-block-bug](https://user-images.githubusercontent.com/3521683/70806898-1785c300-1d9b-11ea-98bd-b179df9e9848.gif)

#### Context / Source
#manual-testing, #user-report

Chat: https://mc.a8c.com/support-stats/happychat/transcript.php?id=198934
Followup ticket: https://woothemes.zendesk.com/agent/tickets/2556341

**Comment by kriskarkoski** [comment] 2020-03-13 18:10
I am not able to reproduce this on an Edge stickered site and there have been no further reports. Closing.

**Closed by kriskarkoski** 2020-03-13 18:10 UTC
Labels: Blocks, [Type] Bug
