### ISSUE TITLE
[Gutenberg] Broken layout on mobile/tablets in wp-admin

### ISSUE THREAD

**Issue by millerf** [Automattic/wp-calypso#42060] opened 2020-05-11 15:51 UTC
#### Steps to reproduce

1. Starting at URL: go to wp-admin
2. Put your browser in device-mode
3. Create a new post

#### What happens

The wp-admin menu button goes on top of the gutenberg header:

#### Browser / OS version
Most mobile and tablet versions. Tested with iphone X, pixel 2, iPad

#### Screenshot / Video

| Mobile | Tablet |
|----|----|
| <img width="323" alt="Screenshot 2020-05-11 at 17 41 23" src="https://user-images.githubusercontent.com/790558/81581497-1a6afb00-93af-11ea-8895-d350a87906a2.png"> |  <img width="385" alt="Screenshot 2020-05-11 at 17 49 41" src="https://user-images.githubusercontent.com/790558/81582143-f65be980-93af-11ea-80bc-f5937a0e9a73.png"> |

**Comment by sirreal** [comment] 2020-05-13 17:13
Good issue, thanks.

This is a problem with the WordPress.com masterbar on mobile. Compare it with standard core (left):

![Screen Shot 2020-05-13 at 18 55 16](https://user-images.githubusercontent.com/841763/81841872-59ce4e80-954b-11ea-87fa-4cd67afab21d.png)

In general, it seems odd to me that the top bar appears on smaller screens, but I think we should continue to follow core patterns there. I'd like to gather more feedback before taking action here.

**Comment by sirreal** [comment] 2020-05-14 11:21
This is a duplicate of https://github.com/Automattic/wp-calypso/issues/40426

**Closed by sirreal** 2020-05-14 11:21 UTC
Labels: Design Needed, Editor, Mobile, Mobile Web, OSS Citizen, [Goal] Gutenberg, [Type] Bug
