### ISSUE TITLE
Block editor: Cover block in layout grid has higher z-index than mobile navigation block

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#58921] opened 2021-12-07 19:41 UTC
### Quick summary

Reported in 4548665-zd-woothemes

Cover block in layout grid has higher z-index than mobile navigation block:
Menu closed | Menu open
------------- | -----------
<img width="427" alt="Screen Shot 2021-12-07 at 2 32 46 PM" src="https://user-images.githubusercontent.com/1689238/145094169-8d647cf0-0139-4185-9cdd-2ca72d9aef51.png"> | <img width="429" alt="Screen Shot 2021-12-07 at 2 32 27 PM" src="https://user-images.githubusercontent.com/1689238/145094173-3449775b-ac54-44e3-ad49-c1c59a6b2be4.png">

### Steps to reproduce

1. Add a Navigation Block with items to a page. Select the option to show the overlay menu on mobile (the default).
2. Below it, add a Layout Grid (block) with Cover Blocks.
3. Preview the page at mobile size and click to open the overlay menu.

### What you expected to happen

The menu should overlay the Cover Blocks.

### What actually happened

The Cover Block stays above the mobile menu.

### Context

Customer report

### Browser

Mozilla Firefox

### Simple/Atomic

Simple

### Other notes

Using Blank Canvas theme.

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, difficult to implement

### Workaround details

Using different blocks in the Layout Grid.

**Comment by ClassicRKR27** [comment] 2021-12-29 21:12
I have another report of this here: 31276571-hc

@edequalsawesome was able to give me the following CSS workaround:

`/* adjust z-index for cover block overlay on front page | XXXXXX-hc eD */
.home .wp-block-cover .wp-block-cover__gradient-background {
	z-index: 0;
}`

Also wanted to note that this is theme and browser agnostic according to my testing.

**Comment by jasmussen** [comment] 2022-01-26 09:28
Thank you for the report! I'm not able to reproduce:
![test](https://user-images.githubusercontent.com/1204802/151137626-723819ae-f9fb-4531-8aa7-8a489a452a45.gif)

Are you able to provide some example markup I can copy, perhaps a theme wherein it's broken?

**Comment by cuemarie** [comment] 2023-07-18 22:44
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/Automattic/wp-calypso/assets/27249804/33de5d84-49d4-41e0-8719-fe87eeaec541

📌 ACTIONS
- Closed as not reproducible / no longer relevant

**Closed as not planned by cuemarie** 2023-07-18 22:44 UTC
Labels: Bug, Triaged, [Closed] Not Reproducible
