### ISSUE TITLE
Backup: Empty files are not restored on WoA sites

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#96616] opened 2024-11-21 11:21 UTC
### Quick summary

Some plugins like [UICore Framework](https://www.uicore.co/framework/) can have empty files that are loaded with `include`/`require`. 

These empty files are backed up properly by Jetpack Backup, but they are not restored on WoA sites. They are restored on self-hosted sites, so apparently there is something in the Atomic platform that ignores/excludes empty files during restore.

For reference, these are the blog IDs of the two tests I did:
- 239229428 – WoA site – Empty file was not restored
- 239229469 – Self-hosted site – Empty file was restored

This is what happened in 9058465-zd-a8c, where we restored a backup of a WoA site with the UICore Framework plugin, but the plugin couldn't be activated because of a fatal error caused by a missing empty file which was not restored from the backup.

### Steps to reproduce

- Go to wordpress.com and switch to a WoA site
- Install this test plugin which loads an empty file: [my-plugin.zip](https://github.com/user-attachments/files/17844668/my-plugin.zip)
- Go to Jetpack > Backup and generate a backup
- Once the backup is done, download it (you can just mark plugins), and check the files of the `my-plugin` plugin
- Note how the empty file is there: ![Image](https://github.com/user-attachments/assets/49197e0d-588b-43dd-8344-686de2f7f999)
- Go to Plugins > Installed plugins and delete the test plugin
- Go to Jetpack > Backup and restore the backup (you can just mark plugins)
- Go to Tools > Plugin File Editor
- Select the test plugin (My Plugin) and note how the empty file is missing: ![Image](https://github.com/user-attachments/assets/99535294-1084-4f73-b642-4066452f5581)
- Go to Plugins > Installed plugins and activate the test plugin (My Plugin)
- Note how the plugin cannot be activated because of a fatal error: ![Image](https://github.com/user-attachments/assets/adb12cbe-7c64-4d6e-9562-3088b908b743)

### What you expected to happen

- The empty file to be restored
- The test plugin to be working after the backup restore

### What actually happened

- The empty file is missing
- The test plugin causes a fatal error:

```
PHP Fatal error:  Uncaught Error: Failed opening required '/srv/htdocs/wp-content/plugins/my-plugin/includes/empty.php' (include_path='/:.') in /srv/htdocs/wp-content/plugins/my-plugin/plugin.php:12
Stack trace:
#0 /wordpress/core/6.7/wp-admin/includes/plugin.php(2387): include_once()
#1 /wordpress/core/6.7/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('my-plugin/plugi...')
#2 /wordpress/core/6.7/wp-admin/plugins.php(60): activate_plugin('my-plugin/plugi...', 'https://testmmt...', false)
#3 {main}
  thrown in /srv/htdocs/wp-content/plugins/my-plugin/plugin.php on line 12
```

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

**Comment by jartes** [comment] 2024-11-21 15:28
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 ACTIONS
- Triaged
- Lowering priority from `High` to `Normal` as it could only affect a few users that restore their site.

@jeherve sorry for asking, but, which team should have this issue assigned? It's a customer report that we are pc4f5j-4Yq-p2. Thank you!

**Comment by jeherve** [comment] 2024-11-22 10:06
> which team should have this issue assigned?

I see the issue is already assigned to the Jetpack Backup team, so you've done the right thing!

**Comment by jeherve** [comment] 2024-11-22 14:33
I'll let @jwebbdev weigh in :)

**Comment by jwebbdev** [comment] 2024-11-22 15:48
@mmtr Could you include the site urls or blog ids for the two tests (self-hosted and atomic) that you did or noted in the initial description?  I want to take a look at the logs and see if it might be a case of a different restore flows with some discrepancy between them that we can fix on our end.

**Comment by mmtr** [comment] 2024-11-22 16:58
@jwebbdev sure thing, these are the blog IDs:

- 239229428 – WoA site – Empty file was not restored
- 239229469 – Self-hosted site – Empty file was restored

Also added them to the issue description

**Comment by jwebbdev** [comment] 2024-11-22 21:48
A couple notes.  Both sites are atomic, as Jurassic Ninja runs on Atomic infrastructure these days.  The main difference is that the Jurassic Ninja site had previously failed a restore over HTTPS so it fell back on an SSH restore. 

To validate this I disabled HTTPS restores for this site (DPC) from the VPMC and ran another restore.  The empty file was restored.

So it seems the issue is that "DPC restores should restore empty files".  Probably it assumes an empty file is in error, but we can check the size against what we expect, and if we expect it to be zero then we can go ahead and write it.  We'll tackle this fix in the current sprint.  Thanks for raising it @mmtr

**Closed as completed** 2024-11-29 18:29 UTC
Labels: Bug, [Pri] Normal, [Feature] Backup, Triaged, Customer report [LEGACY], [Platform] Atomic, [Status] Escalated to Product Ambassadors
