### ISSUE TITLE
Blog posts block: Posts displayed in wrong number of columns when "borders" is selected

### ISSUE THREAD

**Issue by rakshitwesley** [Automattic/wp-calypso#69167] opened 2022-10-18 04:49 UTC
### Quick summary

When selecting to display posts with borders, the blog posts block displays one less column. For example, if we select the post to be displayed in 3 columns with border selected, it instead displays in 2 columns. 

I was able to reproduce this issue on my test site

### Steps to reproduce

1. Add "Blog posts" block to a page
2. Select "Borders" under Style.
3. Set column to 3 
![EU7sp6.png](https://user-images.githubusercontent.com/95758851/196336906-aa4a484a-a16e-48df-918d-6a46a7e76903.png)
4. Preview the page. Only 2 columns are displayed
![7BuIw3.png](https://user-images.githubusercontent.com/95758851/196336702-a3c09cbe-26f8-4d44-be3c-f30ce1e9e6fb.png)
6. Uneven border is displayed if we increase the number of columns
![pHQEpu.png](https://user-images.githubusercontent.com/95758851/196336854-71e74533-a80c-48e0-a137-adaa6e6dee7e.png)

### What you expected to happen

Post should be displayed in the number of columns selected

### What actually happened

Posts displayed in one less column

### Context

Reported here: 5610389-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by zachspears** [comment] 2022-10-21 03:38
Hello @rakshitwesley, I was unable to reproduce the issue. Is it possible this happening on a specific theme? 

![ENroq7.png](https://user-images.githubusercontent.com/10124024/197106090-c33d4794-d2df-4bf2-92b7-446342f70113.png)

**Comment by rakshitwesley** [comment] 2022-10-24 06:31
@zachspears You're right! Issue appears to be on a few specific themes. So far, I was able to replicate this issue with the following:

- Skatepark
- Pixl
- Twenty Twenty-Two 
- Archeo
- Spearhead Blocks
- Masu
- Disco
- Lettre
- Vivre
- Pendant
- Remote

**Comment by jamiepalatnik** [comment] 2022-11-04 00:28
Moving this back to Needs Triage so we can test again with one of these themes.

**Comment by cuemarie** [comment] 2022-11-10 23:41
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**
- Tested on Self-hosted: Not a core block
- Replicable on Core? No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate the Columns discrepancy issues above in both AT and Simple environments. Screenshots show results on TT2:

***Example of 3 Columns Result***

_AT Editor_
![Markup on 2022-11-10 at 16:35:05](https://user-images.githubusercontent.com/27249804/201228259-b25bc2a7-7a1f-4f02-a2ba-678a5acbebf7.png)

_AT Live Site_
![Markup on 2022-11-10 at 16:35:28](https://user-images.githubusercontent.com/27249804/201228274-22ab43dc-880d-45a5-af37-4a92982206a3.png)

_Simple Live Site_
![Markup on 2022-11-10 at 16:35:52](https://user-images.githubusercontent.com/27249804/201228283-14e3b2a3-2d47-4dfd-862a-036699a37360.png)

***Example of 4 Columns Result***

_AT Editor_
![Markup on 2022-11-10 at 16:37:08](https://user-images.githubusercontent.com/27249804/201228451-3bc71780-bda2-4004-a66d-41384ac2bf98.png)

_AT Live Site_
![Markup on 2022-11-10 at 16:37:36](https://user-images.githubusercontent.com/27249804/201228465-d7768d1e-b9b5-4981-b2f4-03dfa4f9593b.png)

📌 ACTIONS
- Marked as Triaged for Quality Squad review

📌 Message to Quality Squad
- Please note the specific themes that have replicated by this issue [in the comment above](https://github.com/Automattic/wp-calypso/issues/69167#issuecomment-1288485760)

**Comment by cometgrrl** [comment] 2022-12-28 19:37
@yansern Is this something Apex can look at, or should it go over to themes/Marvel?

**Comment by cuemarie** [comment] 2023-05-17 01:05
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate


📌 FINDINGS/SCREENSHOTS/VIDEO
- Retested on simple site with themes **Remote**. **TT2**, and **Skatepark**, and the issue no longer occurs.

📌 ACTIONS
- Closed as no longer relevant (issue likely resolved)

**Closed as completed by cuemarie** 2023-05-17 01:05 UTC
Labels: Bug, [Pri] High, Triaged, [Block] Blog Posts, [Feature] Full Site Editor, [Platform] Simple, [Platform] Atomic
