### ISSUE TITLE
Launch Bar: The bar is visible only if the users scrolls up.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#58355] opened 2021-11-22 16:34 UTC
Reported by @ollierozdarz p1637277533047900-slack-C029SB8JT8S

Sometimes when loading a view with the launch bar, the page is scrolled down enough to hide the launch bar behind the admin bar.

**Comment by autumnfjeld** [comment] 2021-12-09 17:18
Adding my recent screenshots:

After I publish & view my post:

<img width="1043" alt="Writing an Intent" src="https://user-images.githubusercontent.com/5665959/145444219-1dbc8cc6-3eb8-43fe-8f7c-03da814f562c.png">

Then when I scroll up I can see the Launch Bar
<img width="1046" alt="Writing an Intent" src="https://user-images.githubusercontent.com/5665959/145444247-3c8434fe-7d91-4603-81dc-8255d6d3ebbb.png">


I feel like this is a high priority issue, it breaks the flow we are trying to provide to users to continue to the next step in their post-publish journey.

Can we bump this up to get fixed ASPA?

cc: @ollierozdarz

**Comment by autumnfjeld** [comment] 2021-12-09 17:23
> Sometimes when loading a view with the launch bar, the page is scrolled down enough to hide the launch bar behind the admin bar.

I think this is happening all the time. Not just sometimes.  For me it has been consistently reproducible.

Could also get ganon devs to have a look if necessary. :)

**Comment by kwight** [comment] 2021-12-09 23:25
@blackjackkent can you take a look when you're next in please?

**Comment by blackjackkent** [comment] 2021-12-13 19:12
Opened D71444-code with a fix that I believe addresses this issue. I could only reproduce this behavior when navigating to a post from the post editor.

**Comment by blackjackkent** [comment] 2021-12-13 22:17
(Kirk has pointed out that the above fix introduces a regression, so I will be doing further work on this.)

**Comment by blackjackkent** [comment] 2021-12-14 22:42
After further discussion with Kirk, we've decided to merge the fix at D71444-code after all. That diff reverts a fix which was made to address https://github.com/Automattic/wp-calypso/issues/57156, so it reintroduces that issue but fixes this one which would have been visible to more people.

Further explained context - during the redesigned launchbar development we encountered intermittent issues where, if a user dismissed the bar and then refreshed the page, it would get hidden behind the masterbar. We implemented D68684-code to fix this. However, it turns out that the issue had been specifically limited to a few themes, like Rockfield, which have a sticky header that is managed with a slight autoscrolling on pageload to put it underneath the masterbar. 

Our fix did resolve #57156 for those themes; however, in doing so, it introduced this new issue for *all* themes whenever the user loaded a new tab. Consequently, we have reverted that change and will need to find a new solution for #57156, as it is more of an edge case.

@autumnfjeld @ollierozdarz Can you confirm that this fix has resolved the issue you were encountering?

**Comment by autumnfjeld** [comment] 2021-12-15 00:08
@blackjackkent 

The fix at  D71444-code fixed the issue.   I tested by going through the Blogger Flow, all the way to publishing & viewing a post and the launch bar showed as I expected.
   ![bitmoji](https://sdk.bitmoji.com/render/panel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)

![image](https://user-images.githubusercontent.com/5665959/146098950-4a54f13c-595d-4ebb-b2fe-aebeb94d2eab.png)

**Comment by ollierozdarz** [comment] 2021-12-16 05:47
Also confirming this now works as expected. Great job!

**Comment by autumnfjeld** [comment] 2021-12-18 00:50
Should we close this issue?

**Comment by ollierozdarz** [comment] 2022-01-10 04:08
@autumnfjeld just double checked it again and it's resolved for me. Can probably be closed.

**Closed as completed** 2022-01-10 16:06 UTC
Labels: Bug, [Pri] Normal, [Size] XS, Blogger Experience Pod
