### ISSUE TITLE
FSE-0: Portfolio template links link out to a demo site

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#38029] opened 2019-11-28 19:45 UTC
#### Steps to reproduce
1. Create a new site from here: `https://horizon.wordpress.com/start/test-fse`
2. Pick the Dalston template.
3. Make your way to the editor or the front end of the site.
4. The link in the cover image goes to a demo site (Try it here: fbomb420.wordpress.com)

#### What I expected
Any content links created on new sites would link to pages on the site.

#### What happened instead
I get taken to a demo site instead: https://dalstondemo.wordpress.com/project-1/

#### Browser / OS version
Chrome on MacOS

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/6981253/69829343-956b9b00-11ed-11ea-9c94-5895daaa6efc.png)

**Comment by iamtakashi** [comment] 2019-12-03 11:42
The theme was designed for a portfolio site in mind, and the demo site shows off its portfolio layout by linking to the internal page.

To fix this issue, we'd need to
* In addition to the homepage, also add the internal pages that the demo site has when the theme is activated.
* And change the URL on the links to use relative paths, like `/project-1/`

**Comment by michaeldcain** [comment] 2019-12-06 14:22
Alternatively, we could just use `#` and allow the user to update the links, instead of the added complexity of adding additional pages on theme switch.

**Comment by fditrapani** [comment] 2019-12-06 16:16
Could another option be to open the image in a modal and display alt text as a description?

**Comment by jblz** [comment] 2019-12-06 22:28
This is also happening on the "Morden" template. Links on the homepage are pointing to, e.g. https://mordendemo.wordpress.com/about/.

Headstart `post_content` is here: 23479-pb

Like @michaeldcain said, at very least, I'd expect these to just resolve to a hash.  Ideally, we'd reference existing pages & update the targets accordingly.

**Comment by obenland** [comment] 2020-03-11 21:15
Duplicate of #39315. Fixed in #39703.

**Closed by obenland** 2020-03-11 21:15 UTC
Labels: [Goal] Page Templates, [Type] Enhancement
