### ISSUE TITLE
My Sites: Single Jetpack site doesn't display

### ISSUE THREAD

**Issue by csonnek** [Automattic/wp-calypso#1248] opened 2015-12-03 22:11 UTC
User reported in 2441431-t that their Jetpack site doesn't display in My Sites. Here are the specifics:

- User has three sites. Two WordPress.com and one Jetpack (we'll call them example1.wordpress.com, example2.wordpress.com, and example.com). 
- User has hidden the two WordPress.com sites on WordPress.com under `/wp-admin/index.php?page=my-blogs` and leaving the Jetpack site visible:

![my-blogs](https://cloud.githubusercontent.com/assets/2814452/11575668/25c5d858-99c7-11e5-8cbe-e2b223efd10a.png)

- Clicking "My Site" after logging into WordPress.com takes you to the stats page for "example1.wordpress.com" with no way to select another site:

![stats](https://cloud.githubusercontent.com/assets/2814452/11575722/6b3f9478-99c7-11e5-96c9-51a18e70ee0e.png)

I tried cycling the visibility of both WordPress.com sites and the Jetpack sites, and the only way you can view or select the Jetpack site in Calypso (both in the app and in the browser) is by having one WordPress.com site visible. 

Let me know if you need more information.

**Comment by jeherve** [comment] 2015-12-07 16:43
Also reported here:
https://wordpress.org/support/topic/selfhosted-site-fails-to-appear-on-wpcom-admin-panel

**Comment by rralian** [comment] 2015-12-09 22:13
We figured this out. The issue is that the user had hidden their primary blog. But in calypso we show your primary blog regardless. So when the user had hidden all but one other blog, their visible-blog-count was 1, which means we don't show the site-picker controls and just showed the primary blog. The fix here was just to set the user's primary blog to the one they really wanted.

A deeper fix would be to update the hidden/visible interface so you cannot hide your primary blog. We also may want to update the controls for setting primary blog so that setting one of your hidden blogs to primary blog would make it visible again (I will add an issue for this). I also opened https://github.com/Automattic/wp-calypso/issues/1432 because in the course of finding this, we found that the primary-blog-selector can lack enough context to be useful. I'm closing this issue here.

**Closed by rralian** 2015-12-09 22:13 UTC
Labels: Jetpack, Site Picker, Sites, [Pri]  BLOCKER, [Type] Bug
