### ISSUE TITLE
Unable to update notifcation settings for followed sites (Intermittent)

### ISSUE THREAD

**Issue by cometgrrl** [Automattic/wp-calypso#60574] opened 2022-01-27 18:14 UTC
### Quick summary

I'm trying to update my reader subscriptions and notifications, and I'm seeing a repeated error:

`Sorry, we had a problem updating that subscription. Please try again.
`

Note: the issue is really neither simple vs atomic since it relates to the reader, and not my site

https://user-images.githubusercontent.com/86427589/151417027-ca953d31-eb3b-4d4b-b5d6-680d13a76788.mov

### Steps to reproduce

1. Start at https://wordpress.com/read
2. Select a followed site from list on the left
3. Click settings (under follow) on the top right
4. Change some settings (toggle on/off Email me new posts, change Instantly/Daily/Weekly, etc)

### What you expected to happen

I expect the selected changes to be applied

### What actually happened

This error appears:

`Sorry, we had a problem updating that subscription. Please try again.
`

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

Mac OS, Latest Chrome

I am proxied.  

### Reproducibility

Intermittent

### Available workarounds?

No but the platform is still usable

### Workaround details

This is intermittent, and I was able to make the changes by leaving the settings dialog and going back again. However, I'm trying to update settings for many followed sites, and this happened for every 2 or 3rd site.

**Comment by Greatdane** [comment] 2022-02-25 07:10
@cometgrrl I was able to replicate it by spamming the follow buttons on/off quickly;

<img width="1182" alt="Markup 2022-02-25 at 16 08 24" src="https://user-images.githubusercontent.com/5075840/155670716-4cac33cb-dfa3-4cb7-8dbc-1f0fd2b096d3.png">

Could it simply be there is some type of time limit to avoid spammers doing mass follows/unfollows? (you mentioned you where updating many settings) - I think this may be expected behaviour.

**Comment by cometgrrl** [comment] 2022-02-25 18:41
I suppose it's possible. I haven't tried to reproduce it since then. However, when it first happened, while I was updating the settings for a lot of followed P2s, I wouldn't have expected to trigger any rating limiting (like 5-10 sites changed in a minute, not 100+).

The frustrating thing is that if it is rate limited, the try again seems to cause it to continue. Not a pleasant user experience. Maybe we should file this as an improvement to see if the language can be more straightforward for the user?  What do you think @Greatdane?

**Comment by Greatdane** [comment] 2022-03-01 08:31
@cometgrrl  To confirm, do you suggest we label it as a `[Type] Enhancement`?

**Comment by cometgrrl** [comment] 2022-03-04 22:28
Yes!  Are we still using that label? Or did we consolidate that into feature requests?  I haven't seen one in a while.

**Comment by Greatdane** [comment] 2022-03-04 22:30
Yes, I believe we are still using it!

**Comment by davemart-in** [comment] 2022-07-28 20:08
I tested this one. Clicking one of the toggles with at least a second between clicking another seems to behave as expected. Clicking rapidly with no time between indeed seems to be hitting some sort of API throttle. 

Gonna close this one for now. Happy to re-open if additional customers report it or if someone wants to work on it.

**Closed as completed by davemart-in** 2022-07-28 20:08 UTC
Labels: Enhancement, [Pri] Low, [Feature] Reader
