### ISSUE TITLE
[Bug]: Block color selector is not successful in applying the desired color

### ISSUE THREAD

**Issue by sailerbe** [Automattic/wp-calypso#67583] opened 2022-09-08 23:13 UTC
### Quick summary

Block color selector is not successful in applying the desired color on https://wordpress.com/go/.

### Steps to reproduce

1. Create or edit a blog post on wordpress.com/go/.
2. Add a Table of Contents with the Table of Contents block
3. Use the block color selector to apply a background color to the table of contents
4. Update and view the live post

### What you expected to happen

The selected color should appear behind the table of contents.

### What actually happened

Nothing visible is happening.

### Browser

Google Chrome/Chromium

### Context

Experienced this bug while doing my work. I think this may only apply to wordpress.com/go/.

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

One

**Comment by sophiegyo** [comment] 2023-03-07 12:37
We've had a report of this on a Simple site too in 5996728-zen.

I was able to replicate this issue on my own Simple site as well. 

This is with Gutenberg 15.2.4 on the Simple sites.

I could not replicate it on my self-hosted site (WP 6.1.1, Gutenberg 15.2.4)

**Comment by cuemarie** [comment] 2023-04-13 23:03
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Since this report is a bit old and referencing older versions of Gutenberg, just ran a quick test on AT for now, and could not replicate.

#### Screenshots/Recordings

![De2hCP.png](https://user-images.githubusercontent.com/27249804/231901210-27d9d403-0952-4bab-9778-2fba949a1e2c.png)

![ShyJmA.png](https://user-images.githubusercontent.com/27249804/231901190-c64d675e-cc30-4726-a106-b6ea97866548.png)

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- Hey @sailerbe and @sophiegyo ! 

With a quick test on AT, I wasn't able to reproduce this.  WordPress.com sites are now on Gutenberg 15.5.1.  Are either of you still able to replicate this issue with the Table of Contents block not accepting a background color? If so please reopen and let me know what steps I can take to try to replicate. Thank you!

**Closed as completed** 2023-04-13 23:03 UTC
Labels: Bug, [Pri] Low, Triaged, [Closed] Not Reproducible, [Platform] Atomic
