### ISSUE TITLE
Checkout: Site with plan can't clear cart in step 1

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#40073] opened 2020-03-11 20:11 UTC
1. Create a site with a plan. 
2. Click on the global cart notice
3. Can't clear cart on checkout

<img width="513" alt="Screen Shot 2020-03-11 at 1 09 33 PM" src="https://user-images.githubusercontent.com/1270189/76459588-b40b3180-6399-11ea-8ca7-3b905deb4323.png">

<img width="947" alt="Screen Shot 2020-03-11 at 1 05 49 PM" src="https://user-images.githubusercontent.com/1270189/76459577-b077aa80-6399-11ea-8459-745f49390205.png">

**Comment by gwwar** [comment] 2020-03-11 20:20
Folks have to advance to step 3 currently to remove items:

<img width="695" alt="Screen Shot 2020-03-11 at 1 19 04 PM" src="https://user-images.githubusercontent.com/1270189/76460364-1dd80b00-639b-11ea-9825-e43934bb5d5b.png">

**Comment by sirbrillig** [comment] 2020-03-11 20:30
Thank you! I personally find this super-annoying, but it is by design. We have plans to change this, and it should be handled by this card: https://github.com/Automattic/wp-calypso/projects/89#card-32126427

**Comment by millerf** [comment] 2020-03-11 20:48
@gwwar I can give it a try...

**Comment by gwwar** [comment] 2020-03-11 20:54
@millerf this one is likely a littler trickier to work on (probably needs server changes). Were there any types of issues you were interested in? I can maybe round up a few good ones.

**Comment by millerf** [comment] 2020-03-11 21:01
@gwwar Server changes, really? I thought it was a matter of "moving" step 3 to step 1... I was just getting started.
If you have some ideas of issues, I would like to get onto stuff that are not one-liners fixes :) Or I am pretty good at refactoring / structural changes (although the later seems to be pretty well handled in this project)...

**Comment by millerf** [comment] 2020-03-11 21:13
Silly question, but why can I do it?


![Uploading Screenshot 2020-03-11 at 22.11.23.png…]()

**Comment by gwwar** [comment] 2020-03-11 21:17
I'll defer to @sirbrillig here. I think the team is testing a few more design variations. So not sure what they had in mind.

I did start up this milestone for intermediate issues that I'll be adding to:
https://github.com/Automattic/wp-calypso/milestone/306

**Comment by sirbrillig** [comment] 2020-03-11 21:28
@millerf you're looking at the old checkout; the new checkout (which is still being abtested but you can see it for everything in our testing environment on https://horizon.wordpress.com) is completely re-written. This issue is for the new (aka: "composite") checkout.

You can read more about [the composite checkout package here](https://github.com/Automattic/wp-calypso/blob/master/packages/composite-checkout/README.md). You can see [our project board here](https://github.com/Automattic/wp-calypso/projects/89). @fditrapani is working on this issue alongside a few others in [this card](https://github.com/Automattic/wp-calypso/projects/89#card-34375356) but we also have [a card specifically for this issue](https://github.com/Automattic/wp-calypso/projects/89#card-32126427).

If you'd like to try re-ordering the steps, feel free to create a PR, but also we're working on this area pretty heavily so don't feel obligated.

**Comment by millerf** [comment] 2020-03-13 12:31
Thanks @sirbrillig I'll look into it. If I feel like it, I'll create a PR...

**Comment by fditrapani** [comment] 2020-03-13 12:38
@millerf I have a new design in the works that deals with this issue. It's probably best to hold off on any changes until I post the design.

**Comment by millerf** [comment] 2020-03-13 12:40
@fditrapani roger that. Keep me posted.

**Comment by michaeldcain** [comment] 2020-04-14 18:04
Fixed by #40873

**Closed by michaeldcain** 2020-04-14 18:04 UTC
Labels: Checkout, [Type] Bug
