### ISSUE TITLE
Overlay Menu (Hamburger menu) auto closes before you can select a page

### ISSUE THREAD

**Issue by isocialtish** [Automattic/wp-calypso#88581] opened 2024-03-15 20:43 UTC
### Quick summary

Hamburger menu (overlay menu) will close before being able to select a page. 

Customer originally reported the error on 7896268-zen

### Steps to reproduce

1. From Appearance>Editor make sure the Navigation block in the header is set for the "OVERLAY MENU" to appear "ALWAYS"
2. Visit the site
3. Click on the hamburger icon for the menu
4. Scroll down with mouse to select a page from the menu
5. Menu will close before you're able to select a page. 

Video of the error:
https://github.com/Automattic/wp-calypso/assets/6664819/fd757935-a0ad-4e2b-a939-c7ec998f5b3e

### What you expected to happen

To be able to select a page from the hamburger menu

### What actually happened

It auto closes before I can select a page

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Tested on Chrome and Safari
Tested this on the themes: Dorna and Twenty Twenty-Four

**Comment by liviopv** [comment] 2024-03-20 15:34
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce it on a Simple Site and Local Site with the same menu structure as present in the site linked in the interaction, which is:

- Menu Item (Published)
- Menu Item with submenu items (Published)
- Menu Item (draft)

The presence of a Draft Page linked in the menu seems to trigger the bug

![CleanShot 2024-03-20 at 15 32 32@2x](https://github.com/Automattic/wp-calypso/assets/14153300/efd3fb76-3408-4767-a423-a6e3c97cd8d6)


https://github.com/Automattic/wp-calypso/assets/14153300/14e44696-81bb-4d64-99cd-ac4f0d10141e



📌 ACTIONS
- Triaged
- Needs upstream issue


📌 Message to Author
@isocialtish please reply to the customer and help them remove the draft pages from the menu, which should fix the issue for them.

**Comment by ellatrix** [comment] 2024-08-27 13:08
Having trouble reproducing this with Twenty Twenty Four in core. Is it still an issue?

![hamburger-tt4](https://github.com/user-attachments/assets/e14360ba-d8ea-4c77-9df1-8cb7cc2c2f8d)

**Comment by annezazu** [comment] 2024-08-30 23:01
I can't replicate this either and it sounds oddly similar to prior issues that were resolved around this time:

https://github.com/WordPress/gutenberg/issues/60371
https://github.com/WordPress/gutenberg/issues/60048
https://github.com/WordPress/gutenberg/issues/63067

Going to close this out since there aren't further reports and we cannot replicate.

**Closed as completed by annezazu** 2024-08-30 23:01 UTC
Labels: Bug, [Pri] Low, [Status] Core Fix Needed, Triaged, [Feature] Full Site Editor, Customer report [LEGACY], [Platform] Simple, [Status] Priority Review Triggered
