### ISSUE TITLE
[E-mails] Pingback emails are badly formed

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#63053] opened 2022-04-26 15:15 UTC
### Quick summary

The pingback emails are badly formed, user reports it has changed recently. 

### Steps to reproduce

n/a

### What you expected to happen

Emails are formed as pingbacks notifications, not empty. 

### What actually happened

"This email is a multi-part MIME message as the text/plain part looks OK, but the text/html part is truncated before is really gets to say anything, just after the opening “body” HTML tag."

The doc and screenshots they sent: 

[PingBack Email View Source.txt](https://github.com/Automattic/wp-calypso/files/8564475/PingBack.Email.View.Source.txt)

![0FIRVj0dRKc1jqrm](https://user-images.githubusercontent.com/11535091/165332485-1bbb4f26-7fde-4b23-8e35-6fb58001339e.png)

### Context

4966913-zd-woothemes

### Simple, Atomic or both?

Simple

### Severity

One

**Comment by ivan-ottinger** [comment] 2022-04-27 10:49
Thank you for the report. I have added the issue to our project board and will investigate it further.

The root cause will be likely similar to an issue we had with "Comment moderation" email template which we fixed in D79214-code.

**Comment by mashikag** [comment] 2022-04-28 16:56
Hi @daria2303 ! 👋 Thank you for raising this issue with us by creating this ticket. 🙇 

I had a brief look at the issue. It seems like the issue is no longer reproducible. The issue was reported before the D79214-code patch from https://github.com/Automattic/wp-calypso/issues/62939 was implemented. It looks as if the patch most likely also fixed the reported issue.

Please re-open this ticket if the user still experiences the issue.

**Closed as completed by mashikag** 2022-04-28 16:56 UTC
Labels: Bug, [Pri] Normal
