### ISSUE TITLE
Help: Contact Form does not load in Google Chrome in Windows 7 Operating System

### ISSUE THREAD

**Issue by graciemae** [Automattic/wp-calypso#4484] opened 2016-04-01 20:07 UTC
#### Steps to reproduce:
1. Log into a WordPress.com account using Windows 7, Google Chrome Version 49.0.2623.110
2. Navigate to https://wordpress.com/help/contact 

#### What I expected:
To see the contact form load and look like this:
![screen shot 2016-04-01 at 4 02 55 pm](https://cloud.githubusercontent.com/assets/13108965/14218672/b786d4e4-f823-11e5-8339-73113b0b8175.png)

#### What happened instead:
The contact form did not load, remaining on the blank screen like this:
![screen shot 2016-04-01 at 4 06 43 pm](https://cloud.githubusercontent.com/assets/13108965/14218681/c76750dc-f823-11e5-83a4-781252b4ab40.png)

#### Browser / OS version:
Google Chrome Version 49.0.2623.110 in Windows 7 Operating System

Reported by user and reproduced.

**Comment by hoverduck** [comment] 2016-05-19 19:19
19May16 Bug Scrub

Closing, unable to reproduce.  I used Browserstack to get Win7 / Chrome v49, and also a Win7 VM with Chrome v50 (latest), and this is what the Contact Us form looks like now:

![screen shot 2016-05-19 at 3 17 52 pm](https://cloud.githubusercontent.com/assets/7233112/15406552/03a1731c-1dd5-11e6-91e8-e771ea3c4815.png)

**Closed by hoverduck** 2016-05-19 19:19 UTC
Labels: Support, [Type] Bug
