### ISSUE TITLE
Price in upgrades\purchases appears wrong in biyearly plans

### ISSUE THREAD

**Issue by DavidSaladu** [Automattic/wp-calypso#66682] opened 2022-08-18 09:31 UTC
### Quick summary

Inside upgrades\purchases, with biyearly plans, the price is shown /year instead of /biyearly which can led to confusion

![image](https://user-images.githubusercontent.com/79575219/185360709-8d446c03-f61d-4fc7-be2f-94b1a55498b1.png)

### Steps to reproduce

1. Go to a site with a biyearly plan
2. access upgrades\purchases
3. Click on the plan
4. Check the price that appears on the main screen:

![image](https://user-images.githubusercontent.com/79575219/185360923-e7e2a0af-f496-4d9e-ac95-7b4392575223.png)

### What you expected to happen

The price should be tagged as `/ bi-yearly `(instead of `/ year`)

### What actually happened

The price appears as `/ year`

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Browser, operating system and other notes

MacOs Monterrey 12.3.1
Chrome Version 103.0.5060.134 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

There is no user impact

**Comment by zachspears** [comment] 2022-08-24 00:49
Able to reproduce, leaving priority Normal due to possible impact of pricing confusion.

**Comment by DavidRothstein** [comment] 2022-08-24 20:25
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/66025.

**Closed as completed by DavidRothstein** 2022-08-24 20:25 UTC
Labels: Bug, [Feature] Plans & Upgrades, [Pri] Normal, Triaged, [Platform] Simple, [Platform] Atomic
