### ISSUE TITLE
FSE Image Alignment not Appearing Outside Blocks

### ISSUE THREAD

**Issue by cat-og** [Automattic/wp-calypso#61654] opened 2022-03-04 06:48 UTC
### Quick summary

When I add an image on an FSE theme (in Editor or in pages/posts) the image toolbar does not show the control to edit the alignment. This only changes when the image is added to a group. 

### Steps to reproduce

1. Start with FSE theme (I tested Bryne and TwentyTwentyTwo)
2. Add image to page. 
3. To add the missing alignment command, add the block to a group. 

I've created a video here from my test site: 

https://user-images.githubusercontent.com/6737345/157702933-c0012b21-5418-460c-8f0c-e12378e51a15.mp4

### What you expected to happen

I expected to be able to add an image and edit the image alignment from the toolbar. 

### What actually happened

The alignment option did not appear until I added the image to a group. 

### Context

This came up during FSE training with Team Aquila. 

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

I use Google Chrome on a Mac. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The image alignment can be changed when the image is added to a group.

**Comment by Robertght** [comment] 2022-03-10 16:25
I tried to replicate this but I wasn't able to.  I thought this was similar to [this](https://github.com/Automattic/themes/issues/5636) but that's an issue on the frontend. 

@cat-og could you check if this is still an issue on your end, please?

**Comment by cat-og** [comment] 2022-03-14 23:56
Hi @Robertght, I tried it again on my [testing site](testingtestsite.com) and I'm still seeing the same thing. I realized I may have left out that this is all in the Editor. Specifically, I was making changes to the Home template with the Twenty TwentyTwo theme.

**Comment by Greatdane** [comment] 2022-04-21 06:13
I was able to confirm this behavior in the site editor. 

It looks like a core issue, as the same behavior happened on a self-hosted site. Added to core and cross-repo watch list;
https://github.com/WordPress/gutenberg/issues/40500

**Comment by Greatdane** [comment] 2022-04-21 07:28
Closing, Core said this is intended behaviour; https://github.com/WordPress/gutenberg/issues/38802#issuecomment-1040353976

**Closed as completed** 2022-04-21 07:28 UTC
Labels: Bug, [Status] Core Fix Needed, Triaged, [Feature] Full Site Editor
