### ISSUE TITLE
wp-admin plugin page margin wrong with RTL languages

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#52960] opened 2021-05-18 11:18 UTC
### Steps to reproduce the behavior
set dashboard to display RTL and site to display LTR (or possibly vice versa?)
go to the plugin page

#### What I expected to happen
the page should just swap with the alignment ratios preserved

#### What actually happened
either the sidebar (usually on the left) doesn't flip sides or it does and the margin doesn't match where the side bar is

### Context

29646917-hc

This seems to be coming from Jetpack and this CSS file: https://c0.wp.com/p/jetpack/9.7/modules/masterbar/admin-menu/admin-menu.min.css adding a left margin to the footer
<img width="366" alt="Markup 2021-05-18 at 12 36 01" src="https://user-images.githubusercontent.com/47717887/118642157-ae9e4800-b7e3-11eb-9c0d-68f1300613fb.png">

On my test side it ends up looking like this with the account lang set to hebrew and the site lang set to eng
<img width="558" alt="Markup 2021-05-18 at 14 06 31" src="https://user-images.githubusercontent.com/47717887/118641997-7dbe1300-b7e3-11eb-9554-11801a0e441b.png">

On their site with lang set as arabic it looked like this:
<img width="1622" alt="Markup 2021-05-18 at 12 24 37" src="https://user-images.githubusercontent.com/47717887/118642107-9e866880-b7e3-11eb-9d59-05b46acf6a1a.png">

#### Is this specific to the applied theme? Which one?
not theme specific

#### Does this happen on simple or atomic sites or both?
tested on AT

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
not consistent in the same ways?

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
see above

**Comment by cpapazoglou** [comment] 2021-06-25 14:05
Reserved for onboarding.

**Comment by cpapazoglou** [comment] 2021-07-06 15:59
I cannot reproduce it and @Nic-Sevic replied he cannot reproduce it either.

Probably the combination of the following 
https://github.com/Automattic/jetpack/blob/8463c84690df627d6bfa3abb3e505cfd3b1325a5/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L56-L58
https://github.com/Automattic/jetpack/blob/bfbce34cdc8a8fc11e53814cb918550f8323ce38/projects/plugins/jetpack/modules/masterbar/masterbar/class-masterbar.php#L126-L130

have resolved the issue.

I will go ahead and close it for now, let's keep an eye and reopen if needed.

**Closed as completed by cpapazoglou** 2021-07-06 15:59 UTC
Labels: Bug, [Pri] Normal, Good First Issue, wp-admin
