### ISSUE TITLE
[Bug]: Jetpack plans outside the refund window show both "Cancel" and "Remove" links on the purchase management page

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#68049] opened 2022-09-20 16:58 UTC
### Quick summary

If you buy a Jetpack plan and wait until it's outside of the refund window, you see both "Cancel" (which turns off auto-renew) and "Remove" (which fully removes the subscription) links on the purchase management page:

![jetpack-cancel-and-remove](https://user-images.githubusercontent.com/235183/191318560-35e7932f-1616-418b-a059-636e2a49fbe2.png)

In keeping with how other products work, you should only see "Cancel" (if auto-renew is on) or "Remove" (after turning auto-renew off).

### Steps to reproduce

1. Buy a Jetpack plan, a.k.a. "bundle" (such as Jetpack Security) -- note this doesn't seem reproducible with regular Jetpack products.  As of now, the bug also isn't reproducible if you buy it with WordPress.com Store credits, so you need to actually pay (e.g. with a fake credit card in store sandbox mode, for Automatticians).
2. Wait for the subscription to be outside the refund window.  (Or since that takes weeks, you could modify the code in the `Store_Subscription::is_refundable()` method to return `false` on your sandbox.)
3. Go to the purchase management page (e.g. `/me/purchases` and click on your subscription).

### What you expected to happen

To only see a "Cancel" link if auto-renew is on, or only see a "Remove" link if auto-renew is off, similar to how other subscriptions work.

### What actually happened

I saw both links at the same time.

### Reproducibility

Consistent

**Comment by DavidRothstein** [comment] 2022-10-04 14:16
I think I stumbled upon the reason for this while looking at the code for something else:

https://github.com/Automattic/wp-calypso/blob/96a0bfe5244a393fa0f6f578895ca936b3152b57/client/lib/purchases/index.ts#L523

It seems to be a pretty simple reason :smile: 

We could look at this history of why that line was added, and it would of course require some testing, but most likely this can be fixed simply by removing that line of code.

**Comment by michaeldcain** [comment] 2022-10-04 17:17
From planning:

> We could look at this history of why that line was added, and it would of course require some testing, but most likely this can be fixed simply by removing that line of code.

Should Jetpack plans have a remove button? If the product is within the refund window, this action will bypass the refund, so at minimum, we shouldn't show it until after.

**Comment by AnasMansy** [comment] 2022-10-06 13:46
can i work on this

**Comment by dsvwilson** [comment] 2022-10-07 00:42
> can i work on this

Feel free to work on issues in public repositories @AnasMansy 
You're welcome and encouraged to submit a PR for this for the team to review.

**Comment by mayankagnihotri7** [comment] 2022-10-07 11:37
Can I please take up this issue?

**Comment by sirbrillig** [comment] 2022-11-02 21:28
FWIW, that line was added in https://github.com/Automattic/wp-calypso/pull/25927. It reads "The only difference from https://github.com/Automattic/wp-calypso/pull/25473 is a fix which allows Jetpack purchases to be removed regardless of their expiration." but it doesn't really say _why_.

**Comment by jjchrisdiehl** [comment] 2022-11-02 22:46
@sirreal It looks like a condition was added to the `isRemovable` function on the Purchases page to allow Jetpack plans to be removed while in a disconnected state. 

It now looks like this is leading to both the 'Remove' and 'Cancel' buttons to be shown on Jetpack plans after the plan leaves the refund window as noted above. Before I go ahead and remove the `isJetpackPlan` condition in the `isRemovable` function, was there a particular reason why this was implemented this way originally?

**Comment by sirreal** [comment] 2022-11-07 16:01
I'm sorry, I don't recall a lot of details from those changes 4 years ago. There are details in 1642-gh-jpop-issues about motivations.

It seems that the goal was to allow management of plans for disconnected Jetpack sites. I'd suggest following the testing instructions from https://github.com/Automattic/wp-calypso/pull/25927 to make sure there are no regressions, otherwise I don't have much to add here.

**Comment by jjchrisdiehl** [comment] 2022-11-10 03:27
It looks like there were two main testing flows in the original issue that Jon linked to: 

1. Ensure that a customer can still cancel/remove a Jetpack plan from a disconnected JP site. 
2. Ensure that a removed WordPress.com user could still cancel any owned plans from the site they were removed from

I tested both flows, the first worked as expected. I added a Jetpack plan to jjcd.blog (test self-hosted site) and disconnected Jetpack. Then, from Purchases I successfully canceled, then, removed the plan (and neither cancel or remove buttons showed at the same time)

As for the WordPress.com flow, it looks like at some point we implemented a change where a user cannot be removed from a site that they own a purchase on until that purchase is transferred to another admin on the site. So this flow seems 'safe':

<img width="719" alt="image" src="https://user-images.githubusercontent.com/16580129/200993397-a7990ef7-4267-4f1c-a096-7b1b78350b1a.png">


> and it would of course require some testing

@DavidRothstein I'm not sure if you had any other flows in mind that we should test before removing this condition?

**Comment by jjchrisdiehl** [comment] 2022-11-11 02:57
Update: As far as I can tell, [this PR ](https://github.com/Automattic/wp-calypso/pull/69772)should be ready to merge. From the testing above, removing the `isJetpackPlan` condition doesn't adversely affect our customers' ability to cancel and remove a disconnected Jetpack plan from their site (which is why this condition was added in the first place).

**Closed as completed** 2022-11-15 20:25 UTC
Labels: Bug, [Status] In Progress, [Feature] Purchase Management, Good First Issue, Quick Fix
