### ISSUE TITLE
Site Editor: Twenty Twenty-one Blocks layout looks off in design picker

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#48276] opened 2020-12-11 18:31 UTC
The preview in design picker is not matching what's shown on site's front end once it's created. The cover blocks alignment is not full width.

<img width="507" alt="Screenshot 2020-12-11 at 19 30 17" src="https://user-images.githubusercontent.com/1182160/101940869-76b52800-3be7-11eb-982d-ad15f907035a.png">

**Comment by Addison-Stavlo** [comment] 2020-12-15 15:59
Im wondering if this is related to the `layout-grid` stuff also effecting https://github.com/Automattic/wp-calypso/issues/48149 ?   If this is an image taken from the site editor, that would make sense.

**Comment by jeyip** [comment] 2021-01-08 03:11
> Im wondering if this is related to the layout-grid stuff also effecting #48149 ? If this is an image taken from the site editor, that would make sense.

I'd wager that you're right. I'm looking at the site thumbnails generated for gutenboarding in Calypso (`static/images/design-screenshots/twentytwentyone-blocks_twentytwentyone-blocks_twentytwentyone-blocks.jpg`) and they also have the cover blocks alignment issue.

**Comment by david-szabo97** [comment] 2021-01-12 16:33
Update: Waiting for https://github.com/Automattic/wp-calypso/issues/48149 to be merged. That should fix this issue as well as #48149

**Comment by Addison-Stavlo** [comment] 2021-01-13 16:31
Update - https://github.com/Automattic/block-experiments/pull/156 is merged.  Once the next release (newer than 1.3) goes out we can regenerate the images for the picker.

**Comment by ianstewart** [comment] 2021-01-15 21:20
I'm in the process of cleaning up the starter design for twenty twenty one in the site editor flow so for reproducing this error later we'll need to grab the homepage revision to reproduce this and check the fix.

**Comment by Addison-Stavlo** [comment] 2021-02-01 18:42
The underlying issue with the layout-grid is fixed and should be live.  It looks like this block is no longer used in the starter design either though so this should be good to close.

> I'm in the process of cleaning up the starter design for twenty twenty one in the site editor flow

👍   -  Should be good to use that block again if you want that back in the design.  Other than that Im not sure if there is anything left to follow up on here. (feel free to re-open if i am mistaken).

**Closed as completed by Addison-Stavlo** 2021-02-01 18:42 UTC
Labels: Bug, [Pri] High, [Goal] Full Site Editing
