### ISSUE TITLE
Editor: double alignment class on images with captions

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#1778] opened 2015-12-17 23:53 UTC
Adding an image with a caption in the Calypso editor adds the `.alignleft`/`.alignright` class to both the `img` and the `figure` elements - as opposed to just the `figure` element as wp-admin would do. This causes a shift in both the image and the caption text. 

It's most noticeable on a theme like Twenty Fourteen, particularly with an empty Content Sidebar widget area (Twenty Fourteen has a pull effect on left/right aligned images, and removing that sidebar increases the size of the container)

Steps to reproduce:
- Activate Twenty Fourteen and remove all widgets from the Content Sidebar (removing the widgets doesn't cause the bug, but it makes it much more visible)
- Create or edit a post and add an image
- Click on the image and select one of the preset thumbnail sizes (custom sizes are affected, but no where near as badly)
- Align the image to the left or right
- Add a caption
- Publish & view

Depending on the settings you've chosen, the image will be shifted to the left/right with the caption alongside it:

![screen shot 2015-12-17 at 6 35 05 pm](https://cloud.githubusercontent.com/assets/13856531/11885147/1134d156-a4ed-11e5-9172-aebd453710d1.png)

---

To compound the issue, changing the alignment to the opposite direction updates the alignment class of the `img` is updated, but the `figure` remains the same, causing the text of the post to overlap the image:

![screen shot 2015-12-17 at 6 37 31 pm](https://cloud.githubusercontent.com/assets/13856531/11885562/9d5345ea-a4ee-11e5-95e6-5e3e765fc0a6.png)

Removing `.alignleft`/`.alignright` from the `img` moves everything back into place

2461665-t

**Comment by hoverduck** [comment] 2016-04-21 16:08
21Apr16 Bug Scrub

Confirmed this bug is still active: https://hd83eblog.wordpress.com/2016/04/21/test-post-1778/

![image](https://cloud.githubusercontent.com/assets/7233112/14716144/afc41eb0-07b9-11e6-8b1d-56bc5d093756.png)

![image](https://cloud.githubusercontent.com/assets/7233112/14716160/bca9730a-07b9-11e6-9ab6-e22e3202ff92.png)

**Comment by hoverduck** [comment] 2016-07-18 19:11
#bug-scrub

Closing, looks like it's fixed.  For the test post from my previous comment I had to delete and re-add the offending image to get it to add cleanly.  New images seem to work fine.

<img width="776" alt="screen shot 2016-07-18 at 3 05 39 pm" src="https://cloud.githubusercontent.com/assets/7233112/16926979/3c2caa5a-4cf9-11e6-8477-d65afdf47a8d.png">

**Closed by hoverduck** 2016-07-18 19:11 UTC
Labels: Editor, [Type] Bug
