### ISSUE TITLE
WooCommerce menu missing after transfer

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#60429] opened 2022-01-25 05:19 UTC
Woocommerce menu missing after transfer

https://user-images.githubusercontent.com/811776/150915788-5fa0beb1-bfd5-4986-ac66-7963dccf6bdc.mp4

Transfer finishes around 53s.

Not sure why menu isn't showing up, could be caching, could be network miss, could be timing.

**Comment by Rolilink** [comment] 2022-01-25 11:51
This happened to me too when testing the "we hit a snag" track events implementation

**Comment by DustyReagan** [comment] 2022-01-26 21:45
I time-boxed some research into this one. It seems this only happens (and happens consistently) on transfers. It doesn't happen on installs on existing Atomic sites. Additionally, it doesn't appear to be related to timing.

I experimented by removing the auto redirect in React, then waited a long moment after the transfer finished, opened a new tab, then went to wp-admin (I tried wc-admin too) on the new Atomic site. The WooCommerce menu item was not there. If I refreshed the page it appeared. This is consistently reproducible.

So, my intuition is telling me maybe the masterbar is creating and using some sort of cache on the first page load of the new Atomic site, then thereafter that cached masterbar is updated to show the WooCommerce menu item. This is really tough to dev because any changes made to a dev Atomic site are blown away during a transfer. :/

It would be a bit of a hack, but I wonder if we can fix this issue by somehow preloading the new Atomic site before redirecting, or redirecting the user to a "pass-through" page that would load the masterbar, then redirect them wc-admin.

**Comment by lsl** [comment] 2022-01-27 01:55
Thanks for looking into this.

> It would be a bit of a hack, but I wonder if we can fix this issue by somehow preloading the new Atomic site before redirecting

Not likely - that initial redirect is where users are sent on a redirect chain to pick up auth cookies.

**Comment by lsl** [comment] 2022-01-27 06:40
Went through a bit of our menu code across jetpack / wpcom / wc-bridge, turning up empty, can't see why it wouldn't show unless the plugin hasn't been activated. (which it has by the time we redirect :shrug: )

> So, my intuition is telling me maybe the masterbar is creating and using some sort of cache on the first page load of the new Atomic site, then thereafter that cached masterbar is updated to show the WooCommerce menu item.

Certainly looks that way. Might be worth pinging someone on #atomic.

**Comment by allilevine** [comment] 2022-01-31 21:35
This might be a wider Atomic-Calypso issue that needs to be resolved.

**Comment by obenland** [comment] 2022-02-08 22:32
There is no way that I can think of how we'd debug that. The menu item appears on reload and I can't add debug code to a site before it exists.

My suggestion would be to remove that filter in the Woocommerce menu item definition and see if that fixes it.

**Comment by obenland** [comment] 2022-02-08 23:48
Spent a bit more time on it.

The wpcomsh filter in `feature-plugins/masterbar.php` does seem to work. It hides the Calypso menu item because the plugin is active.

So I wonder if it's something on the WooCommerce side where the admin menu code is not loaded correctly?

**Comment by lsl** [comment] 2022-02-09 02:04
I seem to recall a few checks that check plugin install status but not activation status. Its possible it's a timing issue but for me its 100% repro so I don't think that's likely unless it's something like the first request activates plugins or something like that.

> So I wonder if it's something on the WooCommerce side where the admin menu code is not loaded correctly?

Maybe look at how wc-calypso-bridge loads things again - I know it can mess with the menu, not sure if it does in our case.

**Comment by lsl** [comment] 2022-02-09 05:18
This looks like a first load issue not a timing issue. Marketplace / plugin install flow has the same issue. (cc @cpapazoglou - this might be something we want to bring into the next sprint) 

Clicking "Manage plugin" at the end of the install process takes you to plugins.php but WooCommerce isn't available in the menu.

**Comment by obenland** [comment] 2022-02-09 17:38
> Marketplace / plugin install flow has the same issue. 

For sites that need a transfer? Or does that include sites that are already on Atomic?

**Comment by lsl** [comment] 2022-02-10 00:41
> For sites that need a transfer?

Only transfer.

**Comment by allilevine** [comment] 2022-02-10 16:34
Hi @Automattic/proton 👋 Can you help us debug why the WooCommerce menu item is missing after Atomic transfer? It's missing on first load, but appears again on a reload of wp-admin.

**Comment by jeffstieler** [comment] 2022-02-10 16:54
Hi @allilevine, I'm going to loop in @Automattic/isotope since this is likely in the Calypso bridge plugin.

**Comment by ilyasfoo** [comment] 2022-02-15 03:48
I'm having a hard time debugging this, I've attempted to use WoA developer blog to provide my own wpcomsh with some manual logging. However, the issue is only reproducible when menu is immediately requested after a transfer. I've tried triggering a transfer via Hosting Configuration and installing WooCommerce after, but WC menu shows on the first load.

I think this isn't related to Calypso bridge plugin since adding WooCommerce menu isn't bridge's responsibility.

**Comment by ilyasfoo** [comment] 2022-02-15 06:41
Adding my observation that while installing WooCommerce via plugins flow (search, install & activate) is able to reproduce the issue, installing WooCommerce via plugin upload does not.

**Comment by joshuatf** [comment] 2022-02-15 18:44
I have not tested this yet, however, I do wonder if this is a priority issue with the hook we introduced to remove the WC item when we don't detect it.

https://github.com/woocommerce/woocommerce-admin/blob/1b94c04b15d43a52a04c151d91b8e8fbf96220a9/src/Features/Homescreen.php#L121-L138

For context, we need to register the WC menu item when a user doesn't have default WC menu item capabilities but still needs to access some WCA pages.

**Comment by allilevine** [comment] 2022-02-15 22:15
Thank you @ilyasfoo and @joshuatf!
 
> For context, we need to register the WC menu item when a user doesn't have default WC menu item capabilities but still needs to access some WCA pages.

It sounds like updating the hook to check different permissions might be the next step here. Is that correct, and who should make that change?

**Comment by lsl** [comment] 2022-03-08 23:57
Confirming this is still an issue. Retested after I noticed D75867-code might have fixed this as a side effect. It did not :smiling_face_with_tear:

**Comment by ilyasfoo** [comment] 2022-03-10 10:13
Apologies for the long wait, @allilevine. Not being able to debug this has been a blocker for me. Uploading my own code to my site just hides the bug away. Just letting you know that I'm not working on this at the moment.

**Comment by allilevine** [comment] 2022-04-11 15:05
@blackjackkent I realized this is another open WooCommerce installation flow issue. It happens consistently but has been difficult to debug.

**Comment by daledupreez** [comment] 2023-02-17 07:23
This may be related to some other bugs where there may _also_ be a timing issue - when we're transferring a site, I believe that the transfer status is independent of any software being installed as part of the transfer. So waiting for "transfer complete" is not actually enough -- in a context like this, we may also need to wait for WooCommerce to be installed and activated before we request an updated menu.

Related: #73307 / #73381

**Comment by markbiek** [comment] 2023-03-16 21:04
2023-03-16: Confirming that this is still an issue.

This is most likely because WooCommerce isn't finished installing at the point that we end up at the dashboard. There is a new `wait-for-plugin-install` step that fixes this issue.

We should be able to add this step before redirecting to the dashboard.

**Comment by andres-blanco** [comment] 2023-04-13 15:34
Closing this. It's not happening anymore:

https://user-images.githubusercontent.com/375980/231810348-f3c362b2-4c54-4162-b170-c18fba5e52b1.mp4

**Closed as completed by andres-blanco** 2023-04-13 15:34 UTC
Labels: Bug, [Feature Group] Customer Seller Experience
