### ISSUE TITLE
Gutenboarding: Clicking outside the domain overlay should close it

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#40948] opened 2020-04-09 08:03 UTC
#### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/new/design
2. Click _sitename.com is available_ 
3. See the overlay open. Click outside the overlay

#### What I expected
When clicking outside the overlay, I expect the overlay to close, just like clicking the X button would.

#### What happened instead
It didn't close when clicking outside the overlay.

**Comment by razvanpapadopol** [comment] 2020-04-09 12:46
Duplicate of #40890

**Closed by razvanpapadopol** 2020-04-09 12:46 UTC
Labels: [Goal] Gutenboarding, [Type] Task
