### ISSUE TITLE
Comment likes being "lost" after refresh in Reader

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#85276] opened 2023-12-14 09:27 UTC
### Quick summary

As reported in p1702541010734839-slack-CBG1CP4EN, we have a user reporting an issue where liking a comment in the Reader and then refreshing the page causes the like to disappear.

The behaviour seems very similar to https://github.com/Automattic/wp-calypso/issues/84213, which was a very similar behaviour for posts in the Reader that we addressed a few weeks ago.

### Steps to reproduce

1. Visit a feed in the Reader where one or more posts have comments
2. Like a comment and then refresh the page.

You may need to throttle your network connection to make it easier to reproduce.

### What you expected to happen

The comment should show as liked by the current user after the refresh.

### What actually happened

The comment doesn't always show as liked after the refresh.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

I took a quick look at this as I worked on the previous issue with likes for Reader posts, and it looks like we have a related issue to do with client-side state.

When I took a look at https://github.com/Automattic/wp-calypso/blob/6c2c5f9e3bd92a81a4b926161ae7032e6e31064b/client/state/data-layer/wpcom/sites/comments/likes/new/index.js, it seems like we're only updating the client-side state _after_ we get the response back from the server. If that's true, it would be more user-friendly to optimistically update the client-side state and roll the update back if there was an error.

**Comment by markbiek** [comment] 2024-01-17 16:48
I'm not able to reproduce this any more, even throttling my connection.

Do we know if we're still getting reports of this issue?

**Comment by sixhours** [comment] 2024-02-05 18:28
I've also been unable to reproduce this FWIW.

**Comment by sixhours** [comment] 2024-03-18 10:45
Since two of us can't reproduce this and we're unlikely to work on Reader enhnancements soon, I'm going to close it for now.

**Closed as completed by sixhours** 2024-03-18 10:45 UTC
Labels: Bug, [Pri] Normal, [Feature] Reader, Triaged, [Product] WordPress.com, [Feature Group] User Interaction & Engagement
