### ISSUE TITLE
Publicize/Reader/Email Subscribers: Bulk scheduling of posts sometimes results in unsuccessful sharing to Publicize, Reader, and Email Followers

### ISSUE THREAD

**Issue by cecoates** [Automattic/wp-calypso#21807] opened 2018-01-24 23:18 UTC
Ticket #916086-zen

#### Steps to reproduce

A user who schedules quite a few posts has noticed that in a handful of cases posts will publish, but then not share to Facebook/Twitter, send out an email to followers, or display properly in the Reader (via following the blog or by tag search).

Posts are scheduled weeks, sometimes months in advance. Two posts a day, one at 7am UK time and one at 7PM UK time.

Posts are scheduled between multiple members of the site. Some use Calypso, some WP-Admin. There does not seem to be a pattern to posts failing more for any specific user or editor.

From the user:

> - I write about 1 - 3 general posts a day to schedule them in and larger batches on weekends while approving guest submissions of 5 - 15 posts I'd say

So it seems like anywhere between 1 and 20 posts could be scheduled a day, or pending approval for scheduling. With larger batches on weekend days.

Going back approximately six months, I found approximately 13 posts that fall into the category of having failed to Publicize properly. If that's a realistic average, it's happening to about ~3% of posts (twice a day, every day, 365x2=730, with about 25 failed posts a year).

Examples of posts that didn't publicize/share correctly:

https://katzenworld.co.uk/2017/07/28/photo-fun-meowjesty-queen-nubia/
https://katzenworld.co.uk/2017/07/31/street-cats-winner-chi-keung-wong/
https://katzenworld.co.uk/2017/07/29/story-share-need-help/
https://katzenworld.co.uk/2017/06/11/oliver-nubia-celebrating-fathers-day/

More listed in the ticket. However, I did not find any pattern to the posts, either in their content, scheduling, who posted them, etc.

At the moment, there are about 60 pending scheduled posts, but given the above information that will vary.

#### What I expected

Scheduled posts share to Facebook, Twitter, email subscribers, and the Reader once they're published.

#### What happened instead

The majority of posts schedule without issue, but a small handful, seemingly random, will publish, but then fail to email followers, share to social media, or display in the Reader. 

On the most recent post that did not publish/publicize correctly: https://katzenworld.co.uk/2018/01/22/homesitters-ltd-proud-sponsors-katzenworld/

I could see that the post was published/visible, but could not be viewed in the Reader. It also failed to Publicize to Facebook and Twitter, or send out an email to subscribers.

In these cases, scheduling the post again (for example one minute in the future) seems to "kickstart" it, so that it publishes/publicizes all around as expected.

At the moment this means the user subscribes to their own blog, and when they notice an email is not sent out, this prompts them to check the Reader and social media to see if the post published there as expected.

**Comment by blazevivan** [comment] 2018-01-30 07:42
User contacted us again requesting to add the following new post with the same behavior: https://katzenworld.co.uk/2018/01/30/happy-trt-tummy-rub-tuesday-week-183/

**Comment by blazevivan** [comment] 2018-01-30 07:49
The user noticed that the pingback to a previous post linked to from this post didn’t happen either. The pingback was only generated after they force re-publishing (marks as a draft - publish again).

**Comment by donalirl** [comment] 2018-02-06 00:27
Here is another post from this user that has been affected by this issue:

https://katzenworld.co.uk/2018/02/01/purrsday-poetry-cat-naps-anxious-hearts/

From the user:

> my contributor just pointed out that no one was able to like this and that it didn't appear in the reader as it normally does:
> i've just force republished it to make it at least work for any future visitors...

#942716-zen

**Comment by donalirl** [comment] 2018-02-06 07:28
Here is another post from this user that has been affected by this issue:

https://katzenworld.co.uk/2018/02/06/happy-trt-tummy-rub-tuesday-week-184/

From the user:

> I just had to change it back to draft and manually re publish to push it through to the reader, social and generate the email. Prior to that it showed on the blog to people visiting directly but again you couldn’t like it and of course it didn’t generate the other bits :(

#942716-zen

**Comment by dromero20** [comment] 2018-02-06 08:13
Another post with similar issue, but a little different:

https://katzenworld.co.uk/2018/02/06/happy-trt-tummy-rub-tuesday-week-184/

In this case they couldn't publish their post by using Publicize because the checkboxes were greyed out:

<img width="1492" alt="captura de pantalla 2018-02-06 a las 8 51 22" src="https://user-images.githubusercontent.com/23258551/35848209-85ccfd20-0b1d-11e8-8654-7e2ad5d1ff35.png">

Even in Calypso:

<img width="1331" alt="captura de pantalla 2018-02-06 a las 8 34 37" src="https://user-images.githubusercontent.com/23258551/35848217-8f0efdb6-0b1d-11e8-89e6-5b3e715e0167.png">

I tried to revert the post as a draft and mark them. You can mark them in Calypso but as soon as you publish the post, they're unmarked again (and not posting in their social networks).

#1729975-hc

**Comment by scosgro** [comment] 2018-02-06 20:51
Another post with this issue from a different site:

https://fabulouslyfighting.com/2018/02/06/raw-red-pepper-and-chia-salad/

User has a lot of scheduled posts going ahead to about 24 days. This most recent one published and didn't go out via email or get shared on social media. Posts from yesterday all went out via email/social properly. #1736244-hc

**Comment by MarcKatzenworld** [comment] 2018-02-07 20:46
Hi guys,

Decided to create an account to add the posts that failed directly on here. And see if there is any way I can contribute to fixing this issue once and for all. :)

Latest post that failed: https://katzenworld.co.uk/2018/02/07/party-animal-discriminated-contest/

This posost failed to send an email, publish to social, publish to reader and while visible if directly going to the blog it wasn't possible to like these

Also if anyone could provide me with the log files around the failed posts (publicise and connection to jetpack) I'd be happy to see if I can spot something that could help in reproducing this on my test server...

@scosgro do you know if posts of the site that you flagged as having the same issue shows the author profile as "other" instead of the name on the iphone app? That's the one thing that stands out to me that all posts on Katzenworld don't show the author name.

**Comment by MarcKatzenworld** [comment] 2018-02-08 19:07
Today's evening post failed as well but in a strange way:

https://katzenworld.co.uk/2018/02/08/purrsday-poetry-dancing-freedom-haiku/

It appeared as if it was live but no email, publicise action and liking did not work for wordpress users.

I went in to the backend wp-admin and before i even got the post list it sent 2 of everything, 2 emails, 2 tweets, 2 facebook posts. :(

**Comment by kraftbj** [comment] 2018-04-10 19:28
Specific to the Reader issue, there was two feedbag feeds for the site -- one tied to the Jetpack site, one tied to the RSS feed (which had the majority of the followers). I merged the two to link the RSS feed to the Jetpack site, which should help WordPress.com's Reader be aware of new posts faster than a pull RSS method.

All in all, I suspect this is mainly a Jetpack Sync issue relative to the new posts not Publicizing, etc and should be referred to the Jetpack side of the coin.

I'm closing this to defer to a new issue generated on the Jetpack side if the issue continues.

**Closed by kraftbj** 2018-04-10 19:28 UTC
Labels: Sharing, [Pri] High, [Type] Bug
