### ISSUE TITLE
Unable to purchase plan via Launchpad > domain-upsell after starting a free site from /pricing

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#83661] opened 2023-10-30 18:24 UTC
### Quick summary

After creating an account and a free site via the WordPress.com/free page and reaching the Launchpad, I'm unable to add a domain and select a plan and checkout.  The Plans page instead shows `Downgrade` and `Please contact support to downgrade your plan` under all plans.

### Steps to reproduce

1. https://wordpress.com/pricing/
2. Select Free plan
3. Create an account (I used email login)
4. Select a theme & Styles
5. Arrive at the launchpad, URL: `https://wordpress.com/setup/free/launchpad?siteSlug=SITEADDRESS`
6. Add a domain
7. Choose any domain to register, or try connecting a domain
8. Arrive at the plans page, URL:  `https://wordpress.com/setup/domain-upsell/plans?siteSlug=SITEADDRESS&flowToReturnTo=free&new=Free%20Site`

### What you expected to happen

I'd be able to purchase any of our plans, since I am currently on the Free plan.

### What actually happened

![Markup on 2023-10-30 at 11:14:44](https://github.com/Automattic/wp-calypso/assets/27249804/5cd83438-0e90-47f2-9a15-3b38006ae930)

---

**Full Recording**

https://github.com/Automattic/wp-calypso/assets/27249804/e933e5a9-84a8-4315-b431-eb5a1556070d

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

If the user goes `back` to the launchpad and skips the rest of the steps to arrive on the dashboard, they can then register/connect a domain & add a plan using upsells and tools from the dashboard.

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Tested in Firefox 119.0 on macOS 14.0

**Comment by cuemarie** [comment] 2023-10-30 18:27
Raised awareness here: p1698690462035789-slack-C01LXBU1N21

**Comment by markbiek** [comment] 2023-10-31 12:12
@cuemarie I was able to reproduce this yesterday but can't reproduce it today.

That makes me think it may have been a manifestation of the issue that was fixed in https://github.com/Automattic/jetpack/pull/33872.

When you have some time, can you see if the issue is still happening for you?

**Comment by cuemarie** [comment] 2023-10-31 18:52
@markbiek I am still able to reproduce this using the steps above. Tested today on Chrome Version 118.0.5993.117

![Markup on 2023-10-31 at 11:49:59](https://github.com/Automattic/wp-calypso/assets/27249804/4b3cce73-c1fa-467e-9f91-ebd166680413)

**Comment by markbiek** [comment] 2023-10-31 19:02
Thanks @cuemarie. I can confirm that it's still happening _but_ only when I create a new WordPress.com account. I don't see the issue if I use my Automattic account (which is why I thought it was working this morning).

**Comment by cuemarie** [comment] 2023-11-30 18:01
This may be fixed by https://github.com/Automattic/wp-calypso/pull/83775

Would need to retest to confirm

**Comment by daledupreez** [comment] 2024-01-05 10:36
@valterlorran, did https://github.com/Automattic/wp-calypso/pull/83775 end up fixing this issue?

**Comment by andres-blanco** [comment] 2024-01-09 15:02
This seems to not be happening anymore. Closing.

https://github.com/Automattic/wp-calypso/assets/375980/297d0114-3062-49fb-9665-a2741a856f16

**Closed as completed by andres-blanco** 2024-01-09 15:02 UTC
Labels: Bug, [Pri] High, [Feature Group] Signup & Site Onboarding, Triaged, [Feature] Site Goals & Onboarding Paths, [Platform] Simple, [Feature] Launchpad, [Status] Priority Review Triggered, [Product] WordPress.com, Needs retest
