### ISSUE TITLE
Gutenberg: investigate console error on load

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#31372] opened 2019-03-11 22:21 UTC
Some sites are seeing the following error on load:

<img width="333" alt="Screen Shot 2019-03-11 at 3 20 44 PM" src="https://user-images.githubusercontent.com/1270189/54162013-45576900-4411-11e9-9e2c-f929cf767c7a.png">

Please update this summary/title when we get a better stacktrace/error

**Comment by Copons** [comment] 2019-03-19 16:14
This error might be caused by the same issue causing #29928.

Currently, the block editor does not refresh the image blocks when their images are updated in the Media Modal.
This can happen, for example, when editing an image (e.g. rotating, resizing, etc.), but definitely happens when inserting images from external sources (Pexels and Google Photos).

The reason is that the image is inserted into the block immediately (hotlinked to its source and with a transient ID such as `media-123`), while the image gets uploaded to WP.com in background.
When the upload finishes, the images obtains permanent URL and ID.
Ideally, at this point we should update the block with these URL and ID, but we don't.
So, the block is stuck with a transient ID and a hotlink URL.
The transient ID is what causes the console error: the block fires a `/media/:id` call which inevitably fails because an image `media-123` doesn't exist.

This error happens both when the image is temporarily assigned to the block while it's uploaded, and at every editor load.

I've proposed a fix in #31540, which should prevent the error to happen on load, but it wouldn't help with the `/media/:id` call that is fired immediately when the image is inserted in the block.
I wonder if it would make sense to do a check on `:id` and blocking calls to `GET /media/:id` with a non-numeric id. 🤔

**Comment by Copons** [comment] 2019-03-20 17:41
This should be fixed by #31540.
I'm closing the issue even if I'm not 100% sure, because the error in the description is consistent with what I've fixed in that PR.

**Closed by Copons** 2019-03-20 17:41 UTC
Labels: [Goal] Gutenberg, [Type] Bug
