### ISSUE TITLE
i18n: fix non-Latin special characters display issue (Turkish, others)

### ISSUE THREAD

**Issue by jenial** [Automattic/wp-calypso#3452] opened 2016-02-22 11:04 UTC
## Issue description

During the recent signup testing, the Turkish translator reported: "Turkish special characters : "ş" and "ğ" are displayed slightly different than the rest of the character fonts. This is an issue only with these special characters, other TR special characters are displayed consistently with the rest of the fonts."
## Screenshots

![tr_desktop_4_account_screenshot1453779561482](https://cloud.githubusercontent.com/assets/7637835/13216461/91abc1c2-d964-11e5-8a85-4caeb62d77f0.png)
![tr_desktop_0_home_screenshot1453779534139](https://cloud.githubusercontent.com/assets/7637835/13216531/fcc33594-d964-11e5-924c-8a208381026c.png)
![tr_tablet_6_next_steps_screenshot1453779672440](https://cloud.githubusercontent.com/assets/7637835/13216533/fd4a5ba0-d964-11e5-9115-592323164944.png)

@oguzkocer @umurkontaci could you please lend your Turkish language expertise and comment to confirm that this is indeed an issue, and perhaps recommend a solution in terms of fonts to use?

**Comment by oguzkocer** [comment] 2016-02-22 11:45
I can confirm the different look of the special characters, a designer should check what's going on. TR is most likely not the only one which has this issue.

**Comment by umurkontaci** [comment] 2016-02-26 17:40
This a common issue with fonts not compatible with Unicode. Solution is to use a font that is compatible with Unicode. 

Sometimes fonts at Google Fonts can provide a Latin charset along with a Unicode one, but in order to save bytes, default setting might be just to use Latin. First action I'd recommend is to look whether the font itself has a Unicode version, and if not, look for a similar font with Unicode support.

**Comment by kriskarkoski** [comment] 2016-08-01 18:10
I checked the WordPress.com homepage and signup flow and instances of ş and ğ look to be displaying correctly there now, but I do see the character ı in a number of words and it's rendered differently in titles versus regular text blocks:

![turkish character highlighting](https://cloud.githubusercontent.com/assets/1900444/17304053/98516386-57f1-11e6-8174-0b1a0310b312.jpg)

Could someone confirm if that's normal for this character in different fonts or if this issue should remain open to audit for character issues in different languages like this one?

**Comment by umurkontaci** [comment] 2016-08-01 18:16
The one below looks OK. The bigger one looks like it's missing the proper charset and defaulting to some other font.

**Comment by kriskarkoski** [comment] 2016-10-31 19:01
To my non-Turkish reading eyes it looks like this is still an issue. @umurkontaci or @demetd. Would either of you mind checking the WordPress.com signup or my screenshot below and confirm these font issues are still present. Thank you!

![tr font signup issues](https://cloud.githubusercontent.com/assets/1900444/19867610/da12baec-9f7a-11e6-9388-eb1aa6d42e87.jpg)

**Comment by oguzkocer** [comment] 2016-10-31 19:04
@kriskarkoski It looks correct to me.

**Comment by kriskarkoski** [comment] 2016-10-31 19:17
Perfect! In that case I'm marking as closed unless we get further reports/comments of issues.

**Closed by kriskarkoski** 2016-10-31 19:17 UTC
Labels: i18n, Signup, [Type] Bug
