### ISSUE TITLE
Pexels Search Broken

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#54271] opened 2021-07-04 03:32 UTC
### Steps to reproduce the behavior

**Add an Image Block**
1. Create a new page/post and add in an Image Block
2. Click "Select Image' > Pexels Free Photos
3. View error "Unable to retrieve list" 

I am not seeing an error in the console. 

![Markup on 2021-07-04 at 12:24:47](https://user-images.githubusercontent.com/24914028/124372058-d9285f80-dcc2-11eb-8dfd-631e96d0f3a5.png)

**Search in the Media Library**
1. Go do My Sites > Media > Pexels fee photos
2. Seach for a common term such as 'river'.
3. No images will be returned

The error I am seeing in the console here is `Error: Promised response from onMessage listener went out of scope`

![Markup on 2021-07-04 at 12:28:14](https://user-images.githubusercontent.com/24914028/124372116-5227b700-dcc3-11eb-90dc-389868326dae.png)

#### What I expected to happen
I expected images to show when searched for. 

#### What actually happened
No images are shown and/or an error message appears.

### Context
4114570-zen

#### Browser / OS version
Does not appear to be browser-specific.  I can replicate in Firefox, Safari, Chrome

#### Is this specific to the applied theme? Which one?
Does not appear to be theme specific

#### Does this happen on simple or atomic sites or both?
Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
This appears to be affecting all sites on WordPress.com

**Comment by joweber123** [comment] 2021-07-04 03:50
I am also able to reproduce this on a self-hosted site using Jetpack.

**Comment by jordesign** [comment] 2021-07-04 10:30
Seems to be working again now - but leaving this open in case we should better test error handling for the future.

**Comment by davipontesblog** [comment] 2021-07-05 12:10
I can't reproduce this either, testing from My Site > Media, and also from the Editor. Closing this for now, please reopen if new reports arrive.

**Comment by retnonindya** [comment] 2021-09-01 02:14
Reopen the issue. I received report from user:
30866458-hc

HEs able to replicate it too (even unproxied):
p1630462059384100-slack-C03TY6J1A

**Comment by synora** [comment] 2021-09-03 00:34
Fixed per p1630462530036500-slack-CB0B2G43X/. Closing issue.

**Closed as completed by synora** 2021-09-03 00:34 UTC
Labels: Bug, API, [Closed] Not Reproducible
