### ISSUE TITLE
Post list: Search query should hide on navigation

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#18268] opened 2017-09-26 13:08 UTC
#### Steps to reproduce
1. Visit `https://wordpress.com/posts/{siteSlug}`
1. Click the search icon
1. Enter a query
1. Click "Switch site"
1. Pick any site, including the same one.
1. Notice that the search query remains visible but is not applied to the post list.

#### What I expected

The search query should be applied to the posts list. Alternatively, it should not be visible and the non-search bar should be shown.

#### What happened instead

Posts are shown unfiltered and the query is visible. This seems incoherent.

#### Screenshot / Video

![search-bug](https://user-images.githubusercontent.com/841763/30861912-80593a7a-a2cc-11e7-8a94-b871f169ba39.gif)

#### Context / Source

Noticed while reviewing https://github.com/Automattic/wp-calypso/pull/18113

**Comment by rachelmcr** [comment] 2017-11-27 18:57
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/453.

**Closed by rachelmcr** 2017-11-27 18:57 UTC
Labels: Posts, [Type] Bug
