### ISSUE TITLE
Gutenberg: Block Translation is Inconsistent

### ISSUE THREAD

**Issue by marcuswisecaesar** [Automattic/wp-calypso#50917] opened 2021-03-09 20:23 UTC
### Steps to reproduce the behavior

1. Go to My Site > Manage > Settings 
2. Click on Site Language and change to another language such as German, and also change your interface to match.
3. Open a page in the Editor and click in the Upper Left on the + button to add a block
4. See That some of the Blocks are not translated 

#### What I expected to happen
I expected blocks to translate to my interface language. 

#### What actually happened
Certain blocks kept their English names and did not translate to my chosen interface language.

### Context
First reported in zd - 3802506

#### Does this happen on simple or atomic sites or both?
I can replicate this behavior on a Simple Site, but not on an Atomic site. 

#### Is there any console output or error text?
No console output or errors

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Effects sites whose interface language is different from English. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![screenshot](https://d.pr/i/Q6ddfJ+)
[Direct Link](https://d.pr/i/Q6ddfJ)

**Comment by synora** [comment] 2021-03-16 16:47
Triaged. Tested and can replicate on a simple site. Works as expected on Atomic sites.

**Comment by gwensmithx** [comment] 2021-06-06 01:21
This seems to be happening on both AT and Simple Sites as reported #4044979-zen

**Comment by marianearchimbaud** [comment] 2021-06-08 15:40
This is happening also on my test sites. A few time ago I was able to look for blocks typing "encabezados..." Now I need to type the block name in English "heading" even though my site and account are set to Spanish.

**Comment by tellisbethel** [comment] 2021-06-08 15:45
This is happening to an Italian WPcom user here 4048664-zd-woothemes

**Comment by sophiegyo** [comment] 2021-06-09 10:32
I can reproduce this on a Simple site of my own, both in French and Swedish.

Screenshot of the Swedish on my Simple site: 
<img width="1156" alt="Markup 2021-06-09 at 12 11 12" src="https://user-images.githubusercontent.com/36608681/121338705-0b41de00-c91e-11eb-85bd-9f0772194da9.png">

Additional reports: 4055174-zen and 3975188-zen

**Comment by daria2303** [comment] 2021-06-15 12:20
Another report: 4066813-zd-woothemes

**Comment by ClassicRKR27** [comment] 2021-06-16 13:23
Another report here for a Japanese language site: 4065319-zd-woothemes

**Comment by ezebecke** [comment] 2021-06-18 15:03
Another report with German: 4077700-zd

**Comment by ghost** [comment] 2021-06-20 05:17
Another report for a Chinese language site: hc-28871478

**Comment by emilyaudela** [comment] 2021-06-21 16:31
This should be resolved here: https://meta.trac.wordpress.org/ticket/5737. Translations for block names and descriptions are still trickling back in. 

Please note that translation percentage varies by language: https://translate.wordpress.org/projects/wp-plugins/gutenberg/

**Comment by JuniorTak** [comment] 2021-06-24 10:54
Another report for a French-language site: 4089846-zen

**Comment by hngdny** [comment] 2021-06-26 19:49
Another report (French): 4092476-zen

**Comment by MaxPhilip** [comment] 2021-06-28 08:00
Another report here (German): 4075751-ZD

**Comment by fetenlakhal** [comment] 2021-06-28 13:36
Another report (French) : 4100527-zen

**Comment by dlind1** [comment] 2021-06-28 16:34
All locales with more than 60% translations were deployed now. Please let us know if any locale still doesn't display translated block titles/descriptions.

**Comment by dlind1** [comment] 2021-07-21 12:51
With 5.8 release on Atomic the translations should be fixed everywhere, closing it.

**Closed as completed by dlind1** 2021-07-21 12:51 UTC
Labels: Bug, [Pri] Normal, Blocks, Triaged
