### ISSUE TITLE
When opening submenu in safari, hitting back brings you back to 

### ISSUE THREAD

**Issue by paxblueribbon** [Automattic/wp-calypso#69798] opened 2022-11-04 18:29 UTC
### Quick summary

On a customer's site, in safari when you open the sub-menu and click an item, then hit the back button, you return to the homepage with the navigation menu still open.

### Steps to reproduce

Go to customer's site in Safari (or I'll use this one as an example (https://demo.studiopress.com/infinity/)

1. (In this example only) Shrink the browser so the mobile menu appears
2. Click to expand layouts
3. Click Content/Sidebar
4. Click the back button in the browser.

### What you expected to happen

Homepage should be loaded as if new.

### What actually happened

Homepage is loaded with menu expanded.

### Context

The example page comes from this bug report on another piece of software: https://github.com/studiopress/responsive-menus/issues/4

We don't have info on this site but this bug report contains some relevant information on the cause of the bug.

See zd-5681681 for relevant information on site here.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

I don't think so, customer is using Winkel but example page I'm not sure what theme they're using.

### Reproducibility

Intermittent

### Severity

Some (< 50%)

**Comment by cuemarie** [comment] 2022-11-11 00:19
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated in** ***mobile only***
- Tested on AT: **Replicated in** ***mobile only***
- Tested on Self-hosted: **Replicated in** ***mobile only***

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated the persistent open dropdown menu within **Safari on iOS** in the following environments:
     - AT site, **Shoreditch** theme
     - Simple site, **Twenty Twenty** and **Winkel** themes 
          - Both the classic site menu and the Navigation Block behaved the same way in these tests
     - Self-Hosted site, **Twenty Fifteen**

- Also replicated the behavior in **Chrome on iOS** on Self-Hosted, Simple, and AT
- ⚠️ Not able to replicate the persistent menu open in Safari on Desktop, even when using theme **Winkel**

**_Examples_**

_AT site_
https://user-images.githubusercontent.com/27249804/201231681-02b6e67b-fe35-40a6-b086-a12040612ef3.MP4

_Simple Site_
https://user-images.githubusercontent.com/27249804/201231724-9e040796-adf0-4520-b837-b411fd633049.MP4

_Self-Hosted Site_
https://user-images.githubusercontent.com/27249804/201231868-a1dbb047-c992-4e21-af7b-65dc36f2e227.MP4

📌 ACTIONS
- Await author feedback

📌 Message to Author
- @paxblueribbon , is the user's report related to Safari on _mobile_, or in Safari on their desktop?

From my tests, the consistency of the open menu when hitting `back` on mobile browsers seems to indicate this may be an intentional design (whether thats from WP or the browsers, I don't know). The external bug you linked to for reference is referring to iOS browsers.

I couldn't tell from the chat or the report above if the issue is happening in Safari on desktop, or just on mobile. Thanks for letting us know!

**Comment by donalirl** [comment] 2022-11-13 21:00
> I couldn't tell from the chat or the report above if the issue is happening in Safari on desktop, or just on mobile. Thanks for letting us know!

User is using Safari 16 on desktop (OS X 10.15.7): https://www.whatsmybrowser.org/b/FB52P

**Comment by inaikem** [comment] 2022-11-20 07:44
Moving back to the main queue following an HE update with the requested context.

**Comment by jamiepalatnik** [comment] 2022-11-22 23:07
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I checked one of my sites and the site from the user report to test the dropdown menu behavior on Safari on desktop.
- I was not able to replicate the issue on Safari on desktop.
- From [this comment](https://github.com/Automattic/wp-calypso/issues/69798#issuecomment-1311069533) it sounds like @cuemarie could not replicate on desktop either.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @paxblueribbon Since the user is reporting this issue is on desktop but we could not replicate it, I would recommend following up with them to let them know and possibly help them with browser troubleshooting.

**Closed as completed by jamiepalatnik** 2022-11-22 23:07 UTC
Labels: Bug, Triaged, [Browser] Safari, [Platform] Simple, [Platform] Atomic
