### ISSUE TITLE
Update "showing latest posts" wording when a non-blog theme uses home.html for static content

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#69171] opened 2022-10-18 06:46 UTC
# Description
This copy "The homepage is showing your latest posts." makes no sense in the context of themes that:
* don't have a "real" page
* use home.html for page content

UDPATE: I think this should apply to all FSE themes, but need to get confirmation from a theme developer.

As far as I'm aware this includes ([Pendant](https://href.li/?https://pendantdemo.wordpress.com/), [Cultivate](https://href.li/?https://cultivatedemo.wordpress.com/), [Archeo](https://href.li/?https://archeodemo.wordpress.com/), [Yuga](https://href.li/?https://yugademo.wordpress.com/)) and the[ new Blank Canvas ](https://github.com/Automattic/themes/pull/6665)

![Image](https://user-images.githubusercontent.com/5665959/196355310-e20f11d5-0ca1-47ad-b7ed-bdfd49faffb6.png)

# Testing
see https://ganonp2.wordpress.com/2022/10/14/reviewing-the-theme-switch-modal-messaging/#comment-1909 for testing flow
* activate any theme that satisfies the described constraints, see that the virtual page shows instead of "The homepage is showing your latest posts." 
* classic themes should still display this message "The homepage is showing your latest posts."

**Comment by arthur791004** [comment] 2022-10-18 06:49
https://github.com/Automattic/wp-calypso/pull/69070 has addressed this issue, it will show the Home page (Home template) and the empty page section will be gone

**Comment by autumnfjeld** [comment] 2022-10-18 06:51
That was just occurring to me.  GREAT! :)

**Comment by fushar** [comment] 2022-10-19 10:04
@autumnfjeld @arthur791004 

What if the Reading setting is set to "static page", but the user adds a Front Page template? Should we show a virtual page?

The homepage will display that Front Page template, but right now, in @arthur791004 's [PR](https://github.com/Automattic/wp-calypso/pull/69070), the Pages list is still incorrect:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/1525580/196661512-1d3fa1c0-dbf6-4886-8930-fd911ec78c14.png">

(Here, the Test Page is set as the static page. However, it is misleading as the homepage is actually the Front Page template)

**Comment by arthur791004** [comment] 2022-10-19 10:23
> What if the Reading setting is set to "static page", but the user adds a Front Page template? Should we show a virtual page?
> The homepage will display that Front Page template,

I tested but my homepage is my Home Page. How do you see the Front Page template as the homepage?

![image](https://user-images.githubusercontent.com/13596067/196665593-52ab0c9a-fc9b-4224-a55a-4f4df113828f.png)

**Comment by fushar** [comment] 2022-10-19 10:26
- Go to `/site-editor/<siteSlug>`, the template will be Front Page
- Or just visit the site directly, the content of the Front Page template will be used

**Comment by fushar** [comment] 2022-10-19 10:34
Maybe we can open a new issue for this (the Front Page case), as currently this problem shows up even on production (without the PR).

But it means we need to modify Arthur's PR, because the PR assumes that the homepage template is always Home template.

**Comment by arthur791004** [comment] 2022-10-19 10:41
I think it's a bug, and it has to show the template used by the Home page 🤔

Additionally, I saw query block is showing the posts in the site editor, but it's showing the pages when I'm visiting the site...so I don't notice my home page is showing the Front Page template 😂

**Comment by fushar** [comment] 2022-10-19 11:10
> I think it's a bug, and it has to show the template used by the Home page

No it's not a bug. It's the expected behavior according to the template hierarchy. Front Page overrides everything if it exists. Ref: https://developer.wordpress.org/themes/basics/template-hierarchy/#front-page-display

**Comment by arthur791004** [comment] 2022-10-19 11:14
Oh yes, that's why we want to avoid using Front Page template 😭

**Comment by autumnfjeld** [comment] 2022-10-20 00:50
@arthur791004 @fushar 
To summarize:
* The Reading settings are for selecting a WP page, not a template (noting that for my own clarification)
* In the PA flow, Blank Canvas, or any other theme will never use front-page template, because of @fushar's point above, the template hierarchy
* if the user chooses to add a front-page.html template, we should have consistency in the calypso UI
  * if this is a pre-existing bug, please file a new issue
  * we don't need to worry about this for the PA project, because the PA project has a very well defined setup (it doesn't use front-page.html)   
-----

> What if the Reading setting is set to "static page", but the user adds a Front Page template? Should we show a virtual page?

Yes we should show a virtual page but this has nothing to do with the PA project.  Please make an issue for this and put in post MVP.

Anything that isn't related to the PA project, please file a bug and indicate what you think the priority is.

-----

Also can we agree on a consistent and exact terminology:
* homepage = what the user sees on their root page mysite.com/
* home.html = the home template which in PA case will show as a virtual page
* Home page = an actual wordpress page (that is how I would read it) or maybe we should use the term Home WPpage 😄

**Comment by fushar** [comment] 2022-10-20 02:44
Sorry I think this discussion should be on https://github.com/Automattic/wp-calypso/issues/69158 instead; didn't realize that there are multiple issues here 😂

**Comment by autumnfjeld** [comment] 2022-10-23 23:05
You can add a link from that issue to this one @fushar so trail of discussion is clear.

I think we can close this now, ya?

**Comment by fushar** [comment] 2022-10-24 02:26
> You can add a link from that issue to this one @fushar so trail of discussion is clear.

Yup, done!

> I think we can close this now, ya?

I think so. cc @arthur791004

**Comment by arthur791004** [comment] 2022-10-24 02:36
Close it 🙂

**Closed as completed by arthur791004** 2022-10-24 02:36 UTC
