### ISSUE TITLE
Image Editor: Inline Edit Button

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#8306] opened 2016-09-28 23:05 UTC
Clicking on an image in the post editor brings up an in-context menu. Let's add an edit icon to that menu. When we click on that the inline edit button will bring up the details view of that image.

<img width="692" alt="screen shot 2016-09-28 at 4 02 04 pm" src="https://cloud.githubusercontent.com/assets/1270189/18935462/129f122a-8595-11e6-9742-5de4fb3769ca.png">

Media Modal Details View:
<img width="1068" alt="screen shot 2016-09-28 at 3 54 13 pm" src="https://cloud.githubusercontent.com/assets/1270189/18935467/17b51c50-8595-11e6-8aea-39ab1aa0a220.png">

**Comment by aduth** [comment] 2016-09-29 13:36
Related: #307, #2085, gh-10349-calypso-pre-oss

Design-wise, there's been many discussions in the past about whether it should open the full details view or some custom view. If opening as the full details view, we should consider the effects of all possible actions (e.g. delete? return to library view [maybe replaces]?).

**Comment by aduth** [comment] 2016-09-29 13:37
This kinda feels like a duplicate of #307

**Comment by gwwar** [comment] 2016-09-30 00:28
Thanks @aduth for the links! I can close this in favor of #307

**Comment by rralian** [comment] 2017-02-15 18:48
#307 is more broad and includes expanding the image modal to include other options. I would treat these separately and prioritize this one as the top priority for improving image-editing flow. It's most important that you can get to the existing image editor controls from an inline image.

**Comment by rralian** [comment] 2017-02-15 18:50
I'm setting the priority of this as a blocker for the image-editor v2 flow. IMHO it's the main point of the project and should be the first thing we do.

**Comment by jblz** [comment] 2017-05-22 16:22
Fixed via merging #14143

**Closed by jblz** 2017-05-22 16:22 UTC
Labels: Editor, Media, [Pri] BLOCKER, [Type] Enhancement
