### ISSUE TITLE
WordPress.com Login Bug for Automatticians

### ISSUE THREAD

**Issue by pmaiorana** [Automattic/wp-calypso#81595] opened 2023-09-11 15:18 UTC
### Quick summary

When I visit a site requiring authentication on WordPress.com (e.g., a P2) and log in to my account, I routinely "land" on this page on build.codepoet.com after authenticating:

![remote-login-bug](https://github.com/Automattic/wp-calypso/assets/194155/d0c8d507-2a27-41bd-8387-6efb1b1f772f)

I suspect this is specific to my account or perhaps a small number of Automattician accounts, not a widespread problem.

### Steps to reproduce

1. Confirm you are not logged-in to WordPress.com
2. Visit a P2 permalink
3. Log in to WordPress.com
4. Land on error message/build.codepoet.com

### What you expected to happen

I expected to land on the WordPress.com dashboard.

### What actually happened

I landed on the page captured in the screenshot above.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment] 2023-09-11 18:32
Duplicate of https://github.com/Automattic/wp-calypso/issues/65737

**Closed as not planned by cuemarie** 2023-09-11 18:32 UTC
Labels: Bug, [Pri] Low, Needs triage, [Platform] Simple
