### ISSUE TITLE
Themes: Different experience between Simple and Atomic when using the classic view

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#59290] opened 2021-12-16 09:40 UTC
### Quick summary

Atomic sites users don't get the same experience as Simple sites users when browsing themes through `wp-admin/themes.php`

### Steps to reproduce

- Go to https://wordpress.com.
- Switch to a Simple site.
- Go to Appearance > Themes.
- Use the "Screen options" tab and switch to the classic view.
- Take a look at the themes available.
- Now switch to an Atomic site, and repeat the steps.

### What you expected to happen

Users should have access to the same themes available on Simple sites:

<img width="1519" alt="Screen Shot 2021-12-16 at 10 34 39" src="https://user-images.githubusercontent.com/1233880/146346815-d1312af7-d096-4dc1-a7ac-f0c897e76e3f.png">
 

### What actually happened

We only display themes currently installed in the site:

<img width="1520" alt="Screen Shot 2021-12-16 at 10 34 49" src="https://user-images.githubusercontent.com/1233880/146346933-34e1612d-dc0c-435c-8556-dbcb7d204a94.png">

**Comment by Copons** [comment] 2021-12-16 11:50
I think this might be a very nasty technical challenge though.

What if we simply added a banner saying something like "browse all the themes in Calypso", linking to `https://wordpress.com/themes/:site`?

**Comment by mmtr** [comment] 2021-12-16 12:28
Another option that was discussed yesterday: p1639581231333800/1639580038.330800-slack-C0113HTN28N

Completely ditch the WP Admin version, and incorporate the missing functionality (access to dotorg themes) into Calypso.

**Comment by cuemarie** [comment] 2023-07-18 22:27
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple/Atomic - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- This difference is still in place, but this is currently by design. AT sites show _Installed Themes_, while Simple sites show a /wp-admin version of the WordPress.com Themes showcase, as installing themes is only a feature of AT sites.

![Markup on 2023-07-18 at 15:24:37](https://github.com/Automattic/wp-calypso/assets/27249804/74edaccd-968a-4714-bd88-ae45300f85b9)

📌 ACTIONS
- Closed as not reproducible / no longer relevant
- If this still feels like a concern, I suggest opening a feature request regarding this parity.

**Closed as not planned by cuemarie** 2023-07-18 22:27 UTC
Labels: Bug, [Feature Group] Appearance & Themes, Needs triage, Simple/Atomic Parity, [Platform] Atomic
