### ISSUE TITLE
Gutenlypso: Classic block's More tag shows broken image

### ISSUE THREAD

**Issue by otpidusprime** [Automattic/wp-calypso#29709] opened 2018-12-21 10:57 UTC
#### Steps to reproduce
1. Create a post or page and add a classic block with content 
2. Add "More tag" from the toolbar
3. Click Publish

You will notice that it appears when we initially add it but breaks and shows a broken image symbol when we Publish the post and when the editor is refreshed.

#### What I expected

To see the Read More link or button on the site and not have the broken image symbol shown. It works when I switch to Calypso Editor and add the More tag element again.

#### What happened instead

Shows a broken image symbol instead:

#### Screenshare:
![gutenberg issue rec](https://user-images.githubusercontent.com/29238672/50338749-50e67280-053b-11e9-8903-1f268c0c3d21.gif)

#### Browser / OS version

**Browser:** Vivaldi 2.2.1388.34
**OS:** macOS Mojave 10.14.2

#### Context / Source
Found this issue due to a user-report and was able to replicate it on their's as well as my test site.

**As of now, an alternative fix for this is to convert the Classic block to independent blocks and use the "More" Gutenberg block:**

![redmorefix](https://user-images.githubusercontent.com/29238672/50339300-20073d00-053d-11e9-80bb-9fc8171a04e7.gif)

Referance: #8222730-hc and #1660980-zen

**Comment by benchilcote** [comment] 2018-12-22 19:55
Adding another case of this.  #1663513-zen

**Comment by arunsathiya** [comment] 2018-12-25 05:11
I can reproduce this on Gutenlypso as well, but not on Calypsoified Gutenberg. 👍🏽 

My understanding is that the `Read more` feature should appear only for the posts page (blog archive), and not the actual blog post.

**Comment by vindl** [comment] 2018-12-26 14:19
This is a duplicate of https://github.com/Automattic/wp-calypso/issues/29643.

**Closed by vindl** 2018-12-26 14:19 UTC
Labels: [Goal] Gutenberg, [Type] Bug
