### ISSUE TITLE
XMLRPC-API "getUsersBlogs" fails on WordPress.com Atomic & Jetpack sites

### ISSUE THREAD

**Issue by hydrixos** [Automattic/wp-calypso#20946] opened 2017-12-19 11:22 UTC
#### Steps to reproduce
Our app Ulysses uses the XMLRPC-API to communicate with WordPress.com. We're experiencing problems with the API call "wp.getUsersBlogs" for WordPress.com users that have a Pro or Business account.

Send the following XMLRPC-Request to the endpoint `https://wordpress.com/xmlrpc.php`:

```
<?xml version="1.0"?>
<methodCall>
    <methodName>wp.getUsersBlogs</methodName>
    <params>
        <param><value><string>USERNAME</string></value></param>
        <param><value><string>PASSWORD</string></value></param>
    </params>
</methodCall>
```

(Replace USERNAME and PASSWORD with the username and password of a Bussiness or Pro account.)

The request will be replied by the following unexpected response:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<methodResponse>
    <params>
        <param>
            <value>
                <array>
                    <data></data>
                </array>
            </value>
        </param>
    </params>
</methodResponse>
```

This problem *only* occurs with (some?) Pro and Business-Accounts. It does not seem to occur with Free accounts. We have a test account that allows to reproduce the problem reliably. Please contact us  via Mail to get access to this account.

#### What I expected

Sending this request for a Pro / Business-Account should return a list of the user's blogs.

#### What happened instead

It provides an empty response.

**Comment by hydrixos** [comment] 2018-01-04 13:29
Further detail: If a WordPress account has two blogs, a free blog and a a Pro blog, only the free blog is returned by getUsersBlogs.

**Comment by rachelmcr** [comment] 2018-08-30 15:55
I tested and confirmed that not all sites are returned by this endpoint. WordPress.com Simple sites are always included (regardless of plan), but WordPress.com Atomic and Jetpack sites are not.

**Comment by hydrixos** [comment] 2018-08-31 09:45
Until this issue has been fixed, it would be really helpful if you could tell us, whether there is any workaround our users can try? E.g. disabling a certain feature on their accounts/blogs? 

Thanks!

(I'm also not sure what a "WordPress.com Atomic" site is…)

**Comment by rachelmcr** [comment] 2018-08-31 10:35
Hi @hydrixos, unfortunately there isn't a workaround that I can think of. I mentioned Atomic sites as that's an internal designation that will help our team investigate further, but it isn't something that can be changed/worked around in this case, as far as I'm aware.

**Comment by hydrixos** [comment] 2018-09-03 14:07
Okay, thanks!

**Comment by edequalsawesome** [comment] 2018-09-21 15:01
Hi, @hydrixos!

As a work-around, if you add the WordPress.com Business site to Ulysses like you would a self-hosted site, and use the WordPress.com username with a password generated from the `/wp-admin/profile.php` page, it'll allow Ulysses to connect and publish to the site.

**Comment by cryptochrome** [comment] 2019-11-16 10:18
Hi,
as an affected end user I am wondering when this bug will get a fix? The last comment made to this issue dates back to August and the priority has been dropped. The bug was opened almost two years ago. As a paying Wordpress Business customer I wonder why there is no progress. It seems to have dropped off of Automattic's radar. Please escalate.

Thanks
Sascha

**Comment by msdurex** [comment] 2020-11-24 08:52
> Hi,
> as an affected end user I am wondering when this bug will get a fix? The last comment made to this issue dates back to August and the priority has been dropped. The bug was opened almost two years ago. As a paying Wordpress Business customer I wonder why there is no progress. It seems to have dropped off of Automattic's radar. Please escalate.
> 
> Thanks
> Sascha

No, it too so funny that in 2020, they didn't fix a 3 years ago issue. But @edequalsawesome workaround could help you.

**Comment by cathymcbride** [comment] 2021-02-25 14:57
Looks like Ulysses is pulling all sites now. Closing...

**Comment by hydrixos** [comment] 2021-02-25 15:01
@cathymcbride We didn't change our way of requesting blogs via XMLRPC. We also had some reports recently regarding this problem. If we understood it correctly, it only affects certain WordPress.com-blogs. So probably this issue is still existing.

**Comment by edequalsawesome** [comment] 2021-02-25 17:00
@cathymcbride I just tried it, and I'm still not able to view Atomic sites in the list of sites that's shown in Ulysses when connecting with the WordPress.com authentication method, so this is still ongoing from what I can tell -- the work-around that I outlined previously is still the only way to connect Ulysses to an Atomic site afaik!

When I try to connect Ulysses to a site on my test WordPress.com account, the site picker shows 10 sites available:

[![List of Accounts](https://d.pr/i/oJkf45/d1Zu3z3Qou+)](https://d.pr/i/oJkf45/d1Zu3z3Qou)

And it's not showing the test Atomic site on that account:

[![Missing Site](https://d.pr/i/7bc1K8/1lMpgQifQz+)](https://d.pr/i/7bc1K8/1lMpgQifQz)

**Comment by cathymcbride** [comment] 2021-02-25 18:10
Fair enough. I thought it was showing one of my atomic test sites, but it appears I was mistaken. Reopening...

**Comment by gwensmithx** [comment] 2022-04-11 16:46
Just wanted to drop a note here that I ran into this scenario today. Site is on a Business Plan / Atomic and they're having issues with connecting the app. 35123753-hc / 4939292-zd for tracking purposes.

**Comment by gwensmithx** [comment] 2022-04-11 16:46
Will send over the workaround commented above!

**Comment by edequalsawesome** [comment] 2022-05-05 15:58
Version 26 of Ulysses is using the WordPress REST API, and I was able to successfully connect it to my Atomic Business plan site without the workaround, so this is resolved 🥳

**Closed by edequalsawesome** 2022-05-05 15:58 UTC
Labels: [Type] Bug, Jetpack, OSS Citizen, Login, Atomic
