### ISSUE TITLE
Mobile menu not working in Storefront

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/wp-calypso#56586] opened 2021-09-27 15:39 UTC
### Quick summary

The mobile menu is not working in Storefront. 

### Steps to reproduce

- Activate the theme Storefront. 
- Add a Primary menu and also check the Handheld menu option
-  When visiting the site the mobile menu button is showing but not responding when clicked. 

### What you expected to happen

I would expect the menu to open when the menu button is clicked on mobile devices. 

### What actually happened

Clicking the button shows no difference. Nothing seems to happen. 

### Context

4330190-zen
4330196-zen

Handheld menu is checked and AMP is turned off. 

Tested in my own site with all plugins turned off, only the Storefront theme active and the result was the same. 

### Operating System

Windows, macOS

### Browser

Google Chrome/Chromium, Microsoft Edge

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Yes, theme is Storefront
Also happens for Storefront child themes:
- Homestore
- Bookshop
- Galleria

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by kspilarski** [comment] 2021-09-27 15:44
I have the same case with a user on Storefront theme (3.9.0) where their mobile menu  is not clickable. Mobile  menu is also not clickable in theme demo (mobile) and customizer (mobile view). CLI shows that theme is updated and don't have any errors. Changing to another theme like Twenty Twenty works. 
4330146-zen

**Comment by sajmes** [comment] 2021-09-27 15:48
Another report here: 4329948-zd-woothemes.

- Handheld menu option was checked.
- I can replicate on my test site.

**Comment by mikeicode** [comment] 2021-09-27 15:55
I'm seeing a few errors in Console related to minified JS files not loading. This specific menu issue appears to be that this file isn't loading:

```
/wp-content/themes/storefront/assets/js/navigation.min.js
```

To confirm I tested linking to this unminified file and the mobile menu worked:

```
/wp-content/themes/storefront/assets/js/navigation.js
```

**Comment by AtrumGeost** [comment] 2021-09-27 16:27
Got a report here: 4330049-zd-woothemes

**Comment by CompChris** [comment] 2021-09-27 17:08
Another report here: 30168725-hc
4330542-zen

**Comment by thekingsprojects** [comment] 2021-09-27 17:51
Another report: 31902766-hc

**Comment by kelasante** [comment] 2021-09-27 18:14
Another report here: 31869628-hc

**Comment by TheSteveK** [comment] 2021-09-27 18:24
Another report 4330726-zen

**Comment by Thelmachido** [comment] 2021-09-27 18:33
Another report 31890508 - HC

**Comment by mikeicode** [comment] 2021-09-27 18:40
Homestore - 31904042-hc

We linked to the file I mentioned above using the Headers plugin to resolve, they need a followup to remove that snippet when the theme bug is updated. 4330865-zd-woothemes

**Comment by cuemarie** [comment] 2021-09-27 18:48
Another report: 31903545-hc
User also tried deactivating all plugins, and the issue persisted.

**Comment by the-misha** [comment] 2021-09-27 19:16
Another report, using Galleria (Storefront child theme): 31903889-hc
Follow-up ticket: 4330871-zd-woothemes

**Comment by the-misha** [comment] 2021-09-27 19:25
Another report: 31900595-hc
Follow-up ticket: 4330782-zd-woothemes

**Comment by edequalsawesome** [comment] 2021-09-27 19:45
Reported here: 31904815-hc
Also provided the workaround mentioned by Mike, so we'll need to follow-up with them to deactivate Insert Headers & Footers by email when this is resolved: 4331008-zen

**Comment by katiebethbrown** [comment] 2021-09-27 20:25
A fix for this is in place now in Storefront 3.9.1:

https://github.com/woocommerce/storefront/issues/1800#issuecomment-928196332

And that update has been pushed to all eCom sites that have the theme symlinked:

p1632772651346300-slack-C7YPW6K40

**Comment by TeniCola** [comment] 2021-09-27 20:39
I had a report of this as well, but just found that this has been resolved; I'll advise the user to update their Storefront theme as needed, thanks!

For reference, 4330498-hc

**Comment by nielslange** [comment] 2021-09-28 00:54
@dolgelukkig, @kspilarski, @sajmes, @mikeicode, @AtrumGeost, @CompChris, @thekingsprojects, @kelasante, @TheSteveK, @Thelmachido, @cuemarie, @edequalsawesome, @katiebethbrown & @TeniCola: The broken mobile menu had been fixed and Storefront 3.9.1 had been released. Could you inform the users, and ask them to update their Storefront theme accordingly? Thanks in advance! 🙌

**Closed as completed by nielslange** 2021-09-28 00:54 UTC
Labels: Bug

**Comment by mxhassani** [comment] 2021-11-05 21:36
A user seems to have ran into the issue. Reported here: 32568416-hc.
Testing on my own site with Page Optimize both on and off showed similar behavior. 

**Workaround** 
Change the AMP setting to Reader and pick one of the themes under Reader Theme.
Details in p1636146646186800-slack-C01UW7SB411

The user in the interaction would want to be notified once the issue is solved.

**Comment by inaikem** [comment] 2021-11-07 03:04
@mxhassani can you please open this as a new issue? It looks like the original was based on AMP being disabled and we'd want to keep a distinction here as you mention it in your notes above. Thanks!

**Comment by daria2303** [comment] 2022-01-19 12:49
Found @mxhassani error again and added it here: https://github.com/Automattic/wp-calypso/issues/60240
