### ISSUE TITLE
i18n: Missing/bad translations in the Post Editor

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93915] opened 2024-08-26 10:06 UTC
## Description
See [context](https://wp.me/p58i-hYA/).

What's New modal

![Image](https://github.com/user-attachments/assets/02ca06f6-becf-482c-901f-91ebe20f19e6)

Writing prompt

![Image](https://github.com/user-attachments/assets/db1716a9-5cb4-42f2-9f16-21be8fa76e45)

Welcome Tour

![Image](https://github.com/user-attachments/assets/b753a168-eb23-4072-be4b-f35dc0f70461)

"Siguiendo los siguentes pasos"

![Image](https://github.com/user-attachments/assets/a85adf70-a82e-417f-95d8-16de1133b432)

AI Assistant

![Image](https://github.com/user-attachments/assets/d3c88bd0-77b4-48e2-a2a3-5f0249055704)

First post published modal

![Image](https://github.com/user-attachments/assets/5aaa699d-ae9a-42a7-9699-463ae13efb3f)

**Comment by javierarce** [comment] 2024-08-26 16:45
Related to the writing prompt modal, I suggested removing it in [this issue](https://github.com/orgs/Automattic/projects/927/views/2?pane=issue&itemId=76019519)

**Comment by davemart-in** [comment] 2024-08-26 18:24
Let's double check that these strings are set up to be translated in the code, then double check with the i18n team to figure out the status on these string translations for this language. I thought we had pretty good coverage for Spanish.

**Comment by mmtr** [comment] 2024-09-04 13:17
I think this is a duplicate of https://github.com/Automattic/i18n-issues/issues/858

**Comment by Addison-Stavlo** [comment] 2024-09-04 14:34
> I think this is a duplicate of https://github.com/Automattic/i18n-issues/issues/858

Seems quite likely. What do you think about closing in favor of that other issue? It seems to be on the "Now" column of the i18n roadmap.

**Closed as not planned** 2024-09-04 16:00 UTC
Labels: [Pri] High, Fit and Finish
