### ISSUE TITLE
Signup: can't select a subdomain when picking a custom domain

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#5230] opened 2016-05-05 09:29 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/
2. Create a new site and enter a subdomain of a domain you already own.
3. You receive the following error message:

![screen shot 2016-05-05 at 11 13 04 am](https://cloud.githubusercontent.com/assets/426388/15040163/b1081e44-12b2-11e6-834b-ed718022f559.png)

4.I would expect to receive an option to purchase mapping for that subdomain instead of an error messagctivi, since it is valid. The mapping option in fact appears at the bottom of the list of suggested domains, but the error message is misleading, and the list of suggestions is so long that I don't see the mapping suggestion.

**Comment by klimeryk** [comment] 2016-05-10 09:08
Thanks for reporting! :) But this seems like a duplicate of https://github.com/Automattic/wp-calypso/issues/859, so I'll be closing this one.
Additional comment on the issue - promoting domain mapping is a double-edged sword. Some users are confused about domain mapping vs domain registration. They think that if they've mapped a domain then it's available and now they own it :/ So promoting it more prominently might come bite us in the back. We _will_ try to improve the error message though 👍

**Closed by klimeryk** 2016-05-10 09:08 UTC
Labels: Domains, Signup, [Type] Bug
