### ISSUE TITLE
Media gallery: Pexel images not being added to cover image block

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#31335] opened 2019-03-09 15:26 UTC
#### Steps to reproduce
1. Starting at URL: wordpress.com/block-editor/post
2. Add a new cover image (Doesn't happen with the regular image or gallery block)
3. Select Pexel library 
4. Search for an image
5. Pick an image
6. Click insert

#### What I expected
Pexels image I selected to load into cover image block.

#### What happened instead
Nothing. I needed to open the image gallery to see that the image I selected was added to my media gallery under all images. 

#### Browser / OS version
Chrome on Mac OS

#### Screenshot / Video
![gallery](https://user-images.githubusercontent.com/6981253/54073463-5c515c00-4255-11e9-94e1-8d2659d3c2e5.gif)

#### Context / Source

I came across this trying to edit a new site I created in our onboarding flow.

**Comment by arunsathiya** [comment] 2019-04-05 07:00
I can confirm that this is still reproducible. It looks like it was not added to the proper project so far, adding now.

**Comment by fditrapani** [comment] 2019-04-05 11:52
Thanks @arunsathiya

**Comment by gwwar** [comment] 2019-10-23 18:09
Closing as a duplicate of the more general https://github.com/Automattic/wp-calypso/issues/32420

Thanks for the report!

**Closed by gwwar** 2019-10-23 18:09 UTC
Labels: Media, [Goal] Gutenberg, [Type] Bug
