### ISSUE TITLE
Atomic users' usernames/display names don't update when they change them on WordPress.com.

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#57876] opened 2021-11-09 23:53 UTC
### Quick summary

If a user name or display name is changed in the WordPress.com profile, that change is not carried over to atomic sites. The change currently only reflects on simple sites.

### Steps to reproduce

1: Create a test account, or use a test account you don't mind changing the info for.
2: Create a site with the features required to make it atomic.
3: View people/team/yoursite.wpcomstaging.com, confirm what your username/display name is for that site.
4: Navigate to WordPress.com/me, change your display name. Navigate to WordPress.com/me/account, change your username.
5: Refresh people/team/yoursite.wpcomstaging.com.

### What you expected to happen

The info should match atomic to simple. IF the username changes in wpcom, it should change on the atomic site as well.

### What actually happened

Nothing. All information is the same as it was before the change.

### Context

Reported in 4443005-zd-woothemes as the customer has changed their display name in their profile, and it's updated everywhere but their one atomic site.

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Available workarounds?

There is no user impact

### Workaround details

Users may need to contact us in order for us to make the change(s) manually.

**Comment by Robertght** [comment] 2021-11-12 21:03
I know I've seen this mentioned somewhere. I'm not sure if we should keep it here or move it to the Atomic repo.

cc @JoshuaGoode for a second look.

**Comment by arinoch** [comment] 2021-11-12 22:35
@Robertght - This and #57464 strike me as long-standing issues that have probably come up before. I couldn't find them in a search, but that means nothing. I think both atomic issues are oversights on our part that could stand to be addressed.

**Comment by JoshuaGoode** [comment] 2021-11-15 14:48
> I know I've seen this mentioned somewhere. I'm not sure if we should keep it here or move it to the Atomic repo.

The Atomic repo is no longer used so this can stay in Calypso's.

However, I think we can reopen an original issue and then do some merges as it looks like we have multiple open for the same thing.

There was an older issue but this was the most recent for syncing WPCOM username and email information to Atomic: https://github.com/Automattic/wp-calypso/issues/46077

That was closed on September 6th as it was fixed by a pod and by https://github.com/Automattic/jetpack/pull/20479

However, I  guess it's not working at all any longer or can break in some cases. 

All of these can essentially be merged.

- https://github.com/Automattic/wp-calypso/issues/55175
- https://github.com/Automattic/wp-calypso/issues/57876
- https://github.com/Automattic/wp-calypso/issues/57464

These are somewhat related:

- https://github.com/Automattic/wp-calypso/issues/49650
- https://github.com/Automattic/wp-calypso/issues/55645

And, again, https://github.com/Automattic/wp-calypso/issues/46077 was the primary issue used for the initial work to fix this.  @Robertght

**Comment by cometgrrl** [comment] 2021-11-19 22:56
Closing this since it's a duplicate of [Display Name Not Updating Across Atomic Site #55175](https://github.com/Automattic/wp-calypso/issues/55175) which is already being worked on.

**Closed as completed by cometgrrl** 2021-11-19 22:56 UTC
Labels: Bug, People Management
