### ISSUE TITLE
Gallery block forces media carousel attachments

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#53985] opened 2021-06-24 10:49 UTC
### Steps to reproduce the behavior

1. Create a page with the standard Gallery block
2. Verify that attachment set to none and lightbox off
3. view in preview and/or live to see that attachment carousel shows anyway
4. try turning on lightbox and see that both it and attachment carousel now show

#### What I expected to happen
if the attachment is set to none then you should not be able to click the images to see a larger version. This is how it works for images

- if you change the settings, such as turning on the lightbox, only that option should show, not it and the attachment carousel

#### What actually happened
the attachment carousel is always there regardless of the settings

### Context
30303958-hc
follow-up: 4091746-zen

also found a similar stale issue here: https://github.com/Automattic/wp-calypso/issues/37079

#### Browser / OS version
tested in chrome

#### Is this specific to the applied theme? Which one?
tested on 2021, veni, and exford; doesn't seem theme dependent

#### Does this happen on simple or atomic sites or both?
both

#### Is there any console output or error text?
no

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
seems like all sites with gallery blocks

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
lightbox duplication
![lightbox](https://user-images.githubusercontent.com/47717887/123249832-0e2df880-d4f2-11eb-9308-5c85ab56524f.gif)

difference between gallery and image:
![attachment page](https://user-images.githubusercontent.com/47717887/123250532-d6738080-d4f2-11eb-9589-90947b821b37.gif)

**Comment by kosiew** [comment] 2021-07-01 08:32
Thanks @Nic-Sevic for the report and for mentioning the earlier issue too!

Closing this as duplicate of your mentioned issue - https://github.com/Automattic/wp-calypso/issues/37079

**Closed as completed by kosiew** 2021-07-01 08:32 UTC
Labels: Bug, Blocks
