### ISSUE TITLE
Site Picker: unable to switch to sites listed below the fold in Android

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#149] opened 2015-11-18 23:15 UTC
Originally raised by @fabianapsimoes 

I'm having troubles selecting some sites with the Site Picker using an Android phone. 

The picker works fine when I select sites listed above the fold. But it won't activate the correct site if I select any of the sites listed below the fold. It activates some other site listed above the fold instead.

I'm using Android on a Sony Xperia Z3 Compact. Browser is Firefox 39.0.

Here is a screencast: https://cloudup.com/iHFd_z_6-4w

**Comment by gwwar** [comment] 2015-12-03 19:08
I wasn't able to reproduce this so far in the Nexus 5x (phone) or Nexus 6P emulator. The scrolling for the site picker is broken though, since both the list and background content scrolls at the same time. I'll try to reproduce on another device.

**Comment by gwwar** [comment] 2015-12-04 19:42
@fabianapsimoes do you recall what Android Version, Phone, and Browser you were using?

**Comment by fabianapsimoes** [comment] 2015-12-08 14:52
> I'm using Android on a Sony Xperia Z3 Compact. Browser is Firefox 39.0.

Not sure which Android version though. I'm no longer able to reproduce this though, so I'll close this for now. Thanks for the ping!

**Closed by fabianapsimoes** 2015-12-08 14:52 UTC
Labels: Site Picker, [Pri] High, [Type] Bug

**Comment by gwwar** [comment] 2015-12-08 15:17
@fabianapsimoes Thanks for testing again!
