### ISSUE TITLE
AMP: White banner with `Save` button partially overlays the left sidebar

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#55895] opened 2021-09-01 09:58 UTC
### Steps to Reproduce

1. Go Atomic
2. Visit AMP section in the dashboard (plugin version installed should be 2.1.4)
3. Scroll up and down

### What I expected to happen

No overlay of the white banner with `Save` button with the left sidebar

### What actually happened

White banner of the AMP plugin with `Save` button partially overlays the left sidebar

### Context

Manual testing

### Operating System

macOS

### OS Version

BigSur 11.5.2

### Browser

Chrome/Chromium

### Browser Version(s)

92

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple/Atomic

Atomic

### Number of Users Impacted

Most users (>50%)

### Available Workarounds

Nope

### Reproducibility

Consistent

### Other information

https://user-images.githubusercontent.com/39308239/131651651-b102b875-9cd0-4031-af40-d63f9c90a8dc.mov

**Comment by zdenys** [comment] 2021-09-01 13:02
Resizing the browser window can help reproduce the issue more easily:


https://user-images.githubusercontent.com/39308239/131675775-0dd41421-c4db-4888-b357-376557e48df2.mov

**Comment by kosiew** [comment] 2021-09-09 06:03
Hi @zdenys ,

Thanks for reporting this and the detailed steps.

I could reproduce this on a AT site.
Further confirmed it is specific to AT site and does not happen on Jurassic Ninja site.

![Markup on 2021-09-09 at 14:01:31](https://user-images.githubusercontent.com/29057562/132631613-b8830499-d160-46b4-ae66-04e8101ca173.png)

Triaging for developers' further investigation.

**Comment by cometgrrl** [comment] 2022-08-18 21:28
Closing, since we removed AMP. pdKhl6-48-p2

**Closed as completed by cometgrrl** 2022-08-18 21:28 UTC
Labels: Bug, [Pri] High, AMP, Triaged, Atomic Upgrade Flows
