### ISSUE TITLE
FSE: Permission issue when creating page as author or contributor roles

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35526] opened 2019-08-18 06:56 UTC
When creating a page on a FSE site (details on p58i-7YJ-p2), using an author or contributor role account, the page doesn't load with this error:

```
You need a higher level of permission.

Sorry, you are not allowed to create posts as this user.
```

<img width="854" alt="Screenshot 2019-08-18 at 12 23 18" src="https://user-images.githubusercontent.com/18581859/63221218-6b004f80-c1b3-11e9-894e-54407f510928.png">

However, creating pages on a non-FSE site with same roles works fine!

Creating posts on both FSE and non-FSE sites work fine as well!

**Comment by gwwar** [comment] 2019-08-19 18:15
Bumping to high to frontload any needed API work.

@apeatling let us know if you had any specific feature requests, but otherwise we'll try to match capabilities expected in wp-admin.

For folks implementing this, note that roles are tied to a list of wp capabilities. Sites may alter what list of capabilities each role has. Sometimes certain API permissions checks may be mis-aligned with what wp-admin actually calls in the backend.

Names can also be misleading, so please verify by reading code :D See also https://github.com/Automattic/wp-calypso/issues/17687 on an example of this happening.

https://wordpress.org/support/article/roles-and-capabilities/

**Comment by apeatling** [comment] 2019-08-22 18:13
Yes, this should match the same capabilities that wp-admin uses.

**Comment by noahtallen** [comment] 2019-08-22 21:17
We currently only allow users with `edit_theme_options` permission to work with templates. This is the capability which allows the user to use the customizer. Currently, that option is [only available to admins and super admins](https://wordpress.org/support/article/roles-and-capabilities/#capability-vs-role-table), which is why we have this issue. Which "Capability" should we use for templates?

I think all we'll have to do is modify this:
https://github.com/Automattic/wp-calypso/blob/888d4189d35115c6c37dacddbdfcfcabf053db3e/apps/full-site-editing/full-site-editing-plugin/full-site-editing/templates/class-wp-template-inserter.php#L327-L338

**Comment by noahtallen** [comment] 2019-08-22 21:20
Ahhh I see I misread the issue description. Maybe it's still related to the above, though, since we would be trying to access the templates when creating a new page. :P

**Comment by noahtallen** [comment] 2019-08-22 21:23
I'm also confused - the WP guide says that authors and contributors are not allowed to edit pages. Do we change that on wpcom?

<img width="754" alt="Screen Shot 2019-08-22 at 2 22 46 PM" src="https://user-images.githubusercontent.com/6265975/63550832-57712380-c4e8-11e9-8988-ce9ccdd7b752.png">

**Comment by gwwar** [comment] 2019-08-22 21:59
> I'm also confused - the WP guide says that authors and contributors are not allowed to edit pages. Do we change that on wpcom?

Roles are modifiable to change what capabilities they include per site. I would recommend seeing what's allowed in wp-admin, then mirroring that on the API checks.

So for example as an author, can they visit /wp-admin/edit.php?post_type=page or https://gwwartest.wordpress.com/wp-admin/edit.php?post_type=wp_template are they able to edit?

**Comment by gwwar** [comment] 2019-08-22 22:12
@arunsathiya how did you get in that state? I don't see authors having page list access for a normal Simple Site? Anything else we're missing?

<img width="303" alt="Screen Shot 2019-08-22 at 3 08 49 PM" src="https://user-images.githubusercontent.com/1270189/63553380-0a448000-c4ef-11e9-9e4a-1f2cee0a134f.png">

wp-admin is a little unfriendly here, showing the pages in the sidebar, but it returns:

<img width="586" alt="Screen Shot 2019-08-22 at 3 11 11 PM" src="https://user-images.githubusercontent.com/1270189/63553444-3f50d280-c4ef-11e9-8f12-b43dd49f8f2d.png">


<img width="1045" alt="Screen Shot 2019-08-22 at 3 11 16 PM" src="https://user-images.githubusercontent.com/1270189/63553432-36600100-c4ef-11e9-920a-7276d2af9697.png">

**Comment by gwwar** [comment] 2019-08-22 22:17
@arunsathiya @noahtallen I'm going to close this as a no-op, as I think this is expected behavior unless folks have additional steps.

**Closed by gwwar** 2019-08-22 22:17 UTC
Labels: [Goal] Full Site Editing, [Pri] High, [Type] Bug

**Comment by arunsathiya** [comment] 2019-08-28 01:32
>I'm going to close this as a no-op, as I think this is expected behavior

Looks like this is indeed the expected behaviour; apologies about any confusions earlier!

I am not sure what I did different when I mentioned `However, creating pages on a non-FSE site with same roles works fine!` in the original report. But that just seems to be incorrect.
