### ISSUE TITLE
Media Library: AT sites unable to upload .ppsx

### ISSUE THREAD

**Issue by kylemcph** [Automattic/wp-calypso#30426] opened 2019-01-26 08:44 UTC
#### Steps to reproduce
1. On either a simple or an AT site, try to upload a .ppsx file to the Media Library via Calypso.
[sample-ppsx.ppsx](https://github.com/Automattic/wp-calypso/files/6013014/test.ppsx.zip) (Please unzip)

#### What I expected
- The file would successfully upload, according to [Accepted File Types](https://en.support.wordpress.com/accepted-filetypes/).

#### What happened instead
- Error displayed: `1 file could not be uploaded because an error occurred while uploading.`
- Tested in wp-admin > Media > Add New and error thrown: `“sample-ppsx.ppsx” has failed to upload.
Sorry, this file type is not permitted for security reasons.`

#### Context / Source

- User report: 1744326-zen (Es support)

**Comment by kylemcph** [comment] 2019-01-26 09:02
Als reported in 1744341-zen (es support)

**Comment by kylemcph** [comment] 2019-01-26 09:04
Found a [similar issue here](https://github.com/Automattic/atomic/issues/297), but that pertains only to AT sites so starting a new thread, as this is also affecting simple sites.

**Comment by torres126** [comment] 2019-01-26 09:09
Similar issue with identical error: #30251

**Comment by AtrumGeost** [comment] 2019-01-29 20:52
It is worth mentioning that this is happening on simple sites as well (e.g. 1744341-zen) 

For AT sites as a temporal fix you can install this plugin:

https://wordpress.org/plugins/wp-add-mime-types/

And then add this value:

> ppsx	= application/vnd.openxmlformats-officedocument.presentationml.slideshow

**Comment by fresatomica** [comment] 2019-01-30 11:40
Another affected user #1759137-zen (es support)

**Comment by chrism245** [comment] 2019-01-30 16:03
Also reported in #1754236 (es support)

**Comment by fresatomica** [comment] 2019-02-01 12:08
Another one #1765647-zen.

**Comment by KokkieH** [comment] 2019-02-06 10:39
Another report in the [forums](https://en.forums.wordpress.com/topic/does-not-allow-uploading-ppsx-files-to-the-media-library/)

**Comment by kriskarkoski** [comment] 2019-02-07 00:45
1780375-zen

**Comment by iamgabrielma** [comment] 2019-02-09 05:35
Noting that as per 1780375-zen and @AtrumGeost [comment](https://github.com/Automattic/wp-calypso/issues/30426#issuecomment-458702286), I have tried to use a workaround with the following snippet:

```
function gma_zen_1780375_custom_upload_mimes($mimes = array()) {
 
    $mimes['ppsx'] = "application/ppsx";
    return $mimes;
}
add_action('upload_mimes', 'gma_zen_1780375_custom_upload_mimes');
```

as well as with `  $mimes['ppsx'] = "application/vnd.openxmlformats-officedocument.presentationml.slideshow"`, but this didn't work and I keep seeing the same error message. 

This snippet however works for other blocked types, [like .kml](https://gist.github.com/iamgabrielma/2afaa728e30f3827a224ec5d0e1cc3be).

**Comment by liviopv** [comment] 2019-02-10 11:12
Another in 1790582-zen

**Comment by liviopv** [comment] 2019-02-10 11:15
Sounds related to https://core.trac.wordpress.org/ticket/40175?

**Comment by lancewillett** [comment] 2019-02-11 14:16
Fixed in r187312-wpcom

**Comment by thabotswana** [comment] 2019-02-16 10:50
User is still having trouble uploading a .ppsx file to their site. I was able to replicate the issue

#1780375-zen

**Comment by lancewillett** [comment] 2019-04-09 02:26
@thabotswana Could you please re-open again with more details on the steps to duplicate? I'm going to close as no other reports have come in since the fix.

**Comment by thabotswana** [comment] 2019-04-09 10:59
Yes. I was able to replicate the issue again following these steps:

1. SSP as the user `familymentalwealth`
2. Go to *My Site -> familymentalwealth.com*
2. Go to the Media Library
3. Upload the file StS-Lessons-v11.ppsx

After a few minutes, the upload fails to complete and an error is displayed

![screenshot](https://cld.wthms.co/7xZeVc+)

However, I was able to upload the file in WP Admin

#1780375-zen

**Comment by lancewillett** [comment] 2019-04-10 00:51
Thanks for the additional details. Looks like an Atomic site — we might not load the mu-plugin helper file in that context. CC @xknown

**Comment by xknown** [comment] 2019-04-10 07:46
@thabotswana can you please upload somewhere else the `StS-Lessons-v11.ppsx` file so I can reproduce this issue? Thanks!

**Comment by xknown** [comment] 2019-04-10 08:42
Added some code in r190173-wpcom, it should probably fix the issue but given that I don't have a file to test I wasn't able to confirm.

**Comment by thabotswana** [comment] 2019-04-10 15:34
@xknown you should be able to download the file from this link:
 
https://drive.google.com/file/d/1vqr0VSqVcdRb4XII5dH8xptoGd_fq8Zk/view?usp=sharing

**Comment by xknown** [comment] 2019-04-11 07:55
> @xknown you should be able to download the file from this link:
> 
> https://drive.google.com/file/d/1vqr0VSqVcdRb4XII5dH8xptoGd_fq8Zk/view?usp=sharing

It looks like the commit above fixed this issue, I was able to upload this file to my test site without any problems.

**Comment by iamgabrielma** [comment] 2019-04-15 06:49
@thabotswana  1780375-zen was auto-marked as resolved as was left "pending" , I've asked them to test again on 1949135-zen

**Comment by lancewillett** [comment] 2019-04-15 17:34
Thanks for the updates, @xknown — I'll close this and HEs please re-open if you hear back that things are **not** working as expected.

**Comment by nickpagz** [comment] 2019-04-29 14:37
@lancewillett I have a report of this happening with .xlsx files now. The user is on a simple site, and it's happening in both Calypso and wp-admin. I downloaded one of their xlsx files from their media library and attempted to upload it to a test site and got the same message. So it's something in our system that's changed recently as they have been successfully uploading these in the past.
I'll re-open this issue, but can move it or start another if that's better.

1995637-zen

**Comment by lancewillett** [comment] 2019-05-01 18:19
@nickpagz Please ping @xknown privately with the file in question so he can test the existing patches.

**Comment by zdenys** [comment] 2019-05-02 08:47
1990419-zen

User tried uploading `Tower-of-Babel-Lesson.ppt`. File size was 7.1Mb and was a *.ppt file created in LibreOffice 6.0.2. Uploaded using Firefox 66.0.3 (64-bit). On our suggestion they tried in Calypso and WP Admin with no luck. We were able to reproduce it on our end. The file can be found in the ticket.

They receive the error: `Tower-of-Babel-Lesson.ppt   HTTP error`. They tried re-saving the file and, again, get the following security error: `Sorry, this file type is not permitted for security reasons.`

Smaller files seem to work. The one that uploaded without any issue was 5.8~Mb. `Its just getting into the mid 8Mb range that I run into snags on *.ppt files.`

**Comment by gemmagarner** [comment] 2019-05-02 14:09
We've received a report of this happening with an .xls file in [this thread](https://en.forums.wordpress.com/topic/cant-upload-a-file/) — there is a link to the file there. Trying to upload this file on a test site resulted in the following error:

> Child Phonology Analyzer 6.4.xls” has failed to upload.
> Sorry, this file type is not permitted for security reasons

Noting the file size is only 4.4MB.

**Comment by xknown** [comment] 2019-05-03 12:41
@gemmagarner I committed some code to address some of the recent issues, are you still unable to upload the file you mention? I can upload it without any issues.

**Comment by gemmagarner** [comment] 2019-05-03 15:54
Thanks @xknown! The file is now uploading for me — I'll follow up with the user and let you know if there any more problems.

**Comment by JoshuaGoode** [comment] 2019-05-14 14:29
User reported that they received 'this file type is not permitted for security reasons' when attempting to upload a .PPSX file via both Calypso and WP-Admin. 

As a workaround, user opted to resave the file, and future files, in PPS and PPTX formats in order to upload. 

12536259-hc

**Comment by arunsathiya** [comment] 2020-01-20 05:07
There are a few times when the file does get uploaded to the site, but we continue to see the error. Refreshing media library or check media library on wp-admin shows the file, as expected. I haven't been able to reproduce this actively, but ran into an user report - 2643884-zen

**Comment by aisajib** [comment] 2020-10-11 17:29
I had a user on 24777383-hc who reported being unable to upload ppt files. I was able to replicate it on my end. I couldn't upload their and my own ppt file on my own test sites as Calypso kept showing the error `1 file could not be uploaded because an error occurred while uploading.`. 

I was able to upload the file after installing this plugin: https://wordpress.com/plugins/disable-real-mime-check - however, it only worked on wp-admin -> Media Library. Calypso didn't work even with this plugin active.

**Comment by ash1eygrace** [comment] 2020-11-13 20:37
Another report of this in 25501701-hc. 

I provided the following workarounds in 3487631-zd. 

1. Conver to .PPTX files, which work.
2. Install the plugin called wp-add-mime-types, and add the code `ppsx = application/vnd.openxmlformats-officedocument.presentationml.slideshow` to the plugin settings via wp-admin > Settings > Mime Type Settings.

**Comment by nerdysandy** [comment] 2020-11-23 22:45
reported on #25833306-hc

**Comment by susanjanec** [comment] 2020-12-08 12:33
Reported here - 23840548-hc - provided workaround in 3556667-zd

**Comment by obenland** [comment] 2021-02-19 22:03
@xknown Any chance you might be able to take another look at this? I was able to reproduce it with a ppsx file I converted from a powerpoint file: https://github.com/Automattic/wp-calypso/files/6013014/test.ppsx.zip

It looks like it's passing the filter you added as expected, but I've been unable to determine what happens after that makes that request fail.

**Comment by cathymcbride** [comment] 2021-02-25 18:57
It worked for me on simple, but not atomic.

**Comment by JoshuaGoode** [comment] 2021-03-03 19:41
There's a similar and older instance of this issue for Keynote and Zip files specifically on Atomic at https://github.com/Automattic/wp-calypso/issues/18601

**Comment by xknown** [comment] 2021-03-04 13:50
> be able to take another look at this? I was able to reproduce it with a ppsx file I converted from a powerpoint file: https://github.com/Automattic/wp-calypso/files/6013014/test.ppsx.zip

Sorry for the delayed reply. How did you test this? I was able to upload this without any issues on wp-admin (WP.com).

**Comment by isocialtish** [comment] 2021-03-11 02:40
I just had this come up again in 3810685-zen. The user was able to bypass it and get the .ppt file to upload after installing the "Disable Real MIME Check" plugin.

**Comment by retrofox** [comment] 2021-03-30 16:41
> > be able to take another look at this? I was able to reproduce it with a ppsx file I converted from a powerpoint file: https://github.com/Automattic/wp-calypso/files/6013014/test.ppsx.zip
> 
> Sorry for the delayed reply. How did you test this? I was able to upload this without any issues on wp-admin (WP.com).

It works as expected to me for **Simple** sites. The app did two POST requests. The first one with an ID `22498`, and the second one with the proper markup that's used to render the UI.

In **Atomic** sites, the error is silent, but it's possible to inspect the error response:

![image](https://user-images.githubusercontent.com/77539/113024696-6f496880-915d-11eb-88c3-08356deecd22.png)

**Comment by sixhours** [comment] 2021-04-23 15:31
Just confirming this is still an issue for Atomic sites:

<img width="664" alt="Screen Shot 2021-04-23 at 11 31 35 AM" src="https://user-images.githubusercontent.com/2124984/115894626-7b0c1000-a427-11eb-89e9-67e981ad5ccd.png">

**Comment by sixhours** [comment] 2021-04-23 16:10
The filter is in an mu-plugin on WP.com simple sites, so my guess is similar logic needs to be added to wpcomsh for parity. Spinning up an ephemeral site to do some testing.

**Comment by sixhours** [comment] 2021-04-23 16:33
Confirmed my ephemeral site does not allow PPSX file types at first:

<img width="1394" alt="Screen Shot 2021-04-23 at 12 26 28 PM" src="https://user-images.githubusercontent.com/2124984/115901713-8b27ed80-a42f-11eb-9c40-7d782888fbd3.png">

But patching it with the mu-plugin through the SH plugin allows the file type:

<img width="1399" alt="Screen Shot 2021-04-23 at 12 26 41 PM" src="https://user-images.githubusercontent.com/2124984/115901755-9b3fcd00-a42f-11eb-82a3-cea7676397f8.png">
<img width="929" alt="Screen Shot 2021-04-23 at 12 27 18 PM" src="https://user-images.githubusercontent.com/2124984/115901766-9bd86380-a42f-11eb-8f0a-9b3d786ac9a4.png">

I'm not sure this is the best approach or if I'm missing something about the Atomic architecture, but I'll spin up a PR on the SH plugin to show my work.

**Comment by sixhours** [comment] 2021-04-23 16:49
~~Started in Automattic/wpcomsh#674~~

Moved to Automattic/jetpack#19655

**Comment by daria2303** [comment] 2021-06-23 14:54
30287822-hc
cannot upload ppt

**Comment by metabreakr** [comment] 2021-06-27 17:35
26718976-hc

**Comment by happychait** [comment] 2021-07-28 09:15
Documenting a workaround I spent time testing:

For Atomic sites: All files including .pptx files upload without any issues.  To upload .ppsx, .pps, and .ppt files though, I had to use the [WP Add Mime Types ](https://wordpress.org/plugins/wp-add-mime-types/) plugin and set it up as following: ![](https://cln.sh/ygfMBj+) ![](https://cln.sh/hSnRqj+)


Here are the mime types to use for ppsx files with the [WP Add Mime Types ](https://wordpress.org/plugins/wp-add-mime-types/) plugin: (pptx files upload without any issues and hence without needing this plugin though!)
```
ppsx	= application/vnd.openxmlformats-officedocument.presentationml.slideshow
pps	= application/vnd.ms-powerpoint
ppt	= application/vnd.ms-powerpoint

```

**Comment by metabreakr** [comment] 2021-07-30 21:42
28352946-hc

**Comment by mikeicode** [comment] 2021-09-28 18:46
5230885-hc

Used the solution from happychait above.

**Comment by atrumgeost** [comment] 2022-07-27 16:30
I ran a quick test and confirmed the issue is fixed on Simple sites. But it persists on AT sites.

**Comment by simison** [comment] 2022-08-26 09:30
List of office file formats that should be supported: https://github.com/Automattic/wp-calypso/blob/08e0bfbd794776b54075371829427f0d78f8581b/client/lib/media/constants.js#L142-L176 (also according to docs https://wordpress.com/support/accepted-filetypes/#documents)

I edited the heading to reflect that bug doesn't affect Simple sites anymore as per https://github.com/Automattic/wp-calypso/issues/30426#issuecomment-1196982820

**Comment by danielbachhuber** [comment] 2022-08-31 16:45
For Atomic, it seems like the underlying problem is that WordPress core doesn't allow `.ppsx` for some reason:

<img width="1540" alt="image" src="https://user-images.githubusercontent.com/36432/187730325-54f21197-902e-4d67-a59f-150108c80873.png">

I see it in `wp_get_mime_types()` however: https://github.com/WordPress/wordpress-develop/blob/1356e3b18d85a95173b392ce97ccd70a4a05f94a/src/wp-includes/functions.php#L3427

Aha! The underlying problem is in `wp_check_filetype_and_ext()`.

`wp_check_mimetype()` works just fine: https://github.com/WordPress/wordpress-develop/blob/1356e3b18d85a95173b392ce97ccd70a4a05f94a/src/wp-includes/functions.php#L3065-L3071

```
[31-Aug-2022 16:37:20 UTC] array (
  'ext' => 'ppsx',
  'type' => 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
)
```

However, the function bails for arbitrary `application/*` mime types that aren't explicitly covered: https://github.com/WordPress/wordpress-develop/blob/1356e3b18d85a95173b392ce97ccd70a4a05f94a/src/wp-includes/functions.php#L3211-L3219

Gaining clarity p1661972863783759-slack-C4EUDHL80

**Closed** 2022-09-01 19:59 UTC
Labels: [Type] Bug, Media, Atomic, User Report, Triaged, Build Maintenance, [Interaction #] > 10
