### ISSUE TITLE
Editor: Sharing: Partially revealing non-shared connections from other users

### ISSUE THREAD

**Issue by jkudish** [Automattic/wp-calypso#867] opened 2015-11-26 17:29 UTC
We are partially revealing non-shared connections from other users, when they are returned by the `/publicize-connections` REST API endpoint. The Sharing accordion ends up in this state of showing services but not individual connections:

![screenshot from 2015-11-26 09-24-40](https://cloud.githubusercontent.com/assets/260253/11428435/3708d252-9420-11e5-84b6-8e8ca9573c55.png)

**Comment by aduth** [comment] 2015-11-26 17:37
Noted that this could have been a regression of #338, though the changes there did not have much of an impact on how connections were used in rendering the Sharing accordion, so I expect that it's been an issue since before it was merged.

**Closed** 2015-12-09 21:28 UTC
Labels: Editor, Sharing, [Type] Bug
