### ISSUE TITLE
Framework: Console error for single-site-user

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#5191] opened 2016-05-03 18:40 UTC
I have noticed that I consistently see a console error that appears related to webpack when I load calypso for a single-site-user. I have seen this in chrome both locally and in production. It looks like this:

![single-site-user error](https://cloudup.com/cB3r5bpPDZP+)

When I click on the error to see more, it just shows me what appears to be boilerplate webpack code. While it's an ugly error, I haven't found any functional issues cause by this error.

Could use some help figuring this out. I'm not sure who is most familiar with our webpack implementation at this point.

/cc @mtias @blowery

**Comment by lancewillett** [comment] 2016-05-04 19:34
I can't repeat this — following these steps.

1. Log into https://wpcalypso.wordpress.com/ with Chrome on OS X, using a user with only 1 site (`lancetest556`).
2. Go to Reader, My Sites, other places and watch JS console.

![screen shot 2016-05-04 at 12 33 14 pm](https://cloud.githubusercontent.com/assets/66797/15026685/7d2820f6-11f4-11e6-906f-4b7e14804781.png)

![screen shot 2016-05-04 at 12 33 40 pm](https://cloud.githubusercontent.com/assets/66797/15026688/80a84c38-11f4-11e6-8899-908d7f1c1915.png)

Is it maybe related to zero Reader subscriptions?

**Comment by rralian** [comment] 2016-05-04 20:47
I'm not sure... I guess it must be something else specific to that test site. I am using the test user `bobraliantest211`. Feel free to login and see if you can recreate with the same account. I see this in both wpcalypso and staging.

**Comment by lancewillett** [comment] 2016-05-04 21:03
I can repeat when logged in as that user — another clue is signup email is not confirmed for that user account.

**Comment by lancewillett** [comment] 2016-05-04 21:06
Tried with yet another account (user `testeruserlance1` with no sites) and saw the error in console this time.

Error is from https://widgets.wp.com/notificationsbeta/webpack:/webpack/bootstrap 847849b379fc66d01ce1

![screen shot 2016-05-04 at 2 05 18 pm](https://cloud.githubusercontent.com/assets/66797/15029180/551127b8-1201-11e6-8e26-d00d955da7d3.png)

**Comment by blowery** [comment] 2016-05-05 01:11
Oh, it's coming from notifications?? cc @dmsnell

**Comment by dmsnell** [comment] 2016-06-03 21:33
yes @blowery this was probably coming from the notifications client when it gets a 404 for PingHub's `newest_note_data` channel. That should be resolved in a recent [update to the notifications client](https://github.com/Automattic/notifications-client/commit/4436712d0c53cc996509b530631c938a6578b90d) and also to the `wpcom.js` family of libraries.

I'm going to close since this should already be fixed. On that note, it's still only in beta, but I plan on deploying the update to production after a week or so of testing internally.

**Closed by dmsnell** 2016-06-03 21:33 UTC
Labels: Framework, [Type] Bug
