### ISSUE TITLE
Post options showing in front of content

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#53831] opened 2021-06-18 18:16 UTC
### Summary
We weren't able to replicate this, even from the user's account. When editing a post, the post options that should be at the bottom are in front of the content in the editor.

#### Does this happen on simple or atomic sites or both?
We have seen in Simple and Atomic sites.

#### Screenshot / Video.
![PostOptionsScreen1](https://user-images.githubusercontent.com/16104522/122601642-fa911680-d047-11eb-8807-52ffce4fee50.jpg)

![PostOptionsScreen2](https://user-images.githubusercontent.com/16104522/122601667-041a7e80-d048-11eb-8887-e7397eedffef.jpg)

Reports:
4063820-zd-woothemes
30175086-hc

**Comment by kosiew** [comment] 2021-06-30 08:42
Thanks @carinapilar for the report.
Since it is not reproduceable,  I added a Good First Issue label and closed this.
Feel free to reopen this if it is possible to reproduce.

**Closed as completed by kosiew** 2021-06-30 08:42 UTC
Labels: Bug, Good First Issue

**Comment by carinapilar** [comment] 2021-06-30 10:58
> Since it is not reproduceable, I added a Good First Issue label and closed this.

Okay. I tried to replicate the issue again, no luck. One thing I noticed though, is that in both cases it shows _"Document"_ on the footer, which seems to be sort of a breadcrumb for what's selected in the editor. Not sure when exactly that shows up though, because if you're editing a post or page, it will show Post or Page, not _"Document"_. I don't know if it's related to the issue, or the user accessed the editor from a different place, might be a clue if someone wants to troubleshoot further.

**Comment by carinapilar** [comment] 2021-07-07 11:13
I have the feeling that this issue is somehow related to [the black overlay one](https://github.com/Automattic/wp-calypso/issues/53401). The first image on that one, also says _"Document"_, and the post options are also shown on a black overlay. It seems it will get fixed soon. 🙏
