### ISSUE TITLE
Blog posts block: posts belonging to more than one category won't appear twice 

### ISSUE THREAD

**Issue by sourourn** [Automattic/wp-calypso#55648] opened 2021-08-22 20:10 UTC
### Steps to reproduce the behavior

1. Go to Posts and create a post
2. Allocate two categories to the post (eg: category 1 and category 2)
2. Open a page add two blog posts blocks. Select category 1 under the first blog posts block and category 2 under the second blog posts block. Let's say you want to display all posts under category 1 under one heading (block posts block for category 1) and then all posts under category 2 in a second heading ( (block posts block for category 2) , all in the same page.

#### What I expected to happen

If posts belong to more than one category, they should show up under each blog posts block (ie: appear twice for example).

#### What actually happened

Post only appears on one blog posts block but won't appear in the second block posts block, even though it belongs to that category

#### Does this happen on simple or atomic sites or both?

Both.

#### Is there any console output or error text?

<img width="1440" alt="Screen Shot on 2021-08-22 at 16-03-03" src="https://user-images.githubusercontent.com/39188945/130368627-781d7c84-c32c-4fdb-a600-63d7b4f5dbe8.png">

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="1299" alt="Screen Shot 2021-08-22 at 15 53 00" src="https://user-images.githubusercontent.com/39188945/130368643-0b5511b9-62ca-4668-8660-fb5f02336c2e.png">

<img width="942" alt="Screen Shot 2021-08-22 at 15 58 51" src="https://user-images.githubusercontent.com/39188945/130368666-486c558a-53c1-4aeb-804b-9ae6c40b927e.png">

<img width="1342" alt="Screen Shot 2021-08-22 at 15 57 25" src="https://user-images.githubusercontent.com/39188945/130368654-4b4fb7d6-09b5-4952-a1d9-b5e3b004b75f.png">
<img width="1384" alt="Screen Shot 2021-08-22 at 15 57 55" src="https://user-images.githubusercontent.com/39188945/130368675-0df18b8b-716e-4c8e-9c87-2b6e8a7e0bae.png">

Reported here: #31255752-hc

**Comment by zdenys** [comment] 2021-08-25 10:23
Seems to be a duplicate of https://github.com/Automattic/newspack-blocks/issues/675 that hasn't gotten any attention so far 😞

**Comment by inaikem** [comment] 2021-09-27 10:42
Pinged @sourourn re Bugomattic and added the issue to the HE Triage board.

**Comment by Robertght** [comment] 2021-09-29 10:45
Flagging this for @Automattic/flow-patrol-create

**Comment by dcoleonline** [comment] 2021-10-01 13:25
4340416-zd

**Comment by alshakero** [comment] 2021-10-05 20:05
Closing as won't fix because it's intended behavior. It's explained by Tracy quite well [here](https://github.com/Automattic/newspack-blocks/issues/675#issuecomment-934392236) and a workaround is also provided. Thanks everyone!

**Closed as completed by alshakero** 2021-10-05 20:05 UTC
Labels: Bug, [Pri] High, Triaged
