### ISSUE TITLE
Saving certain site settings (E.g. in Advanced General) breaks/reverts theme

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#53447] opened 2021-06-07 08:35 UTC
### Summary

On a simple and AT sites, when any setting is changed in _Advanced General_, the theme breaks and completely reverts to a different theme or just shows broken/blank homepage for the site.  I tested with Karuna and Twenty Twentyone active and after saving some new sittings in Advanced General, my test site switched to Twenty Fifteen.
WP-Admin/themes shows an error: `The active theme is broken. Reverting to the default theme.`

### Steps to reproduce the behavior

1. On a simple or AT site, make sure one of our internal themes is activated (such as Twenty Twentyone) and then save any setting in Settings ➤ Advanced General 
2. After saving the settings, the theme is broken and reverts to a different theme. For example, I had Twenty TwentyOne active, and that was reverted to Twenty Sixteen.
3. WP-Admin ➤ Themes has an error: `the active theme is broken. Reverting to the default theme.`

<img width="433" alt="Theme Break" src="https://user-images.githubusercontent.com/41035049/120985517-8b0a5580-c730-11eb-8826-2b7a730af1af.png">

#### Is this specific to the applied theme? Which one?

Seems to happen in both block-based themes and premium themes.

#### Does this happen on simple or atomic sites or both?

Simple and AT, but so far only tested themes in our internal library

**Comment by poojashetty18** [comment] 2021-06-07 09:03
Another report on 30008759-hc
Theme: Verity

The AT site user also made changes to Advanced General settings and changed the New User Default Role from "Customer" to "Vendor"

**Comment by cpapazoglou** [comment] 2021-06-07 12:08
I have been looking to the issue, but still don’t have a clue. 
It’s unrelated to nav-unification or the menu entry “Advanced General”.

Just a hint: It doesn't reproduce on eCommerce plans.

**Comment by cpapazoglou** [comment] 2021-06-07 12:27
`validate_current_theme` returns `false` because `file_exists( get_stylesheet_directory() . '/style.css' )` is `false`.

It seems that `stylesheet` option gets empty when saving the form in `wp-admin/options-general.php` 

![](https://cln.sh/PuhYRb+)

**Comment by katiebethbrown** [comment] 2021-06-07 13:19
If the `stylesheet` option is empty, could that also be what's causing the `theme_mods_{themeslug}` option to get overwritten with `-`, causing the issues we're seeing saving customizer changes?

https://github.com/Automattic/wp-calypso/issues/53431

If I'm reading it right (I might not be), JP sync uses the `stylesheet` option to sync the theme_mods:

https://github.com/Automattic/jetpack/blob/05de5b8f8fba2bd86c607abbc3e98e49c9cc739c/projects/packages/sync/src/modules/class-options.php#L228

**Comment by cpapazoglou** [comment] 2021-06-07 13:32
> theme_mods_

I am not sure yet if these issues are related. FWIW, saving the form in `wp-admin/options-general.php` will both empty the `stylesheet` and `theme_mods_{themeslug}` as a result of both of them being in the `$allowed_options` `array`. 

I am now trying to find how they get added there.

**Comment by cpapazoglou** [comment] 2021-06-07 13:48
Tested in an Atomic site, disabling Gutenberg plugin resolved the problem...

**Comment by cpapazoglou** [comment] 2021-06-07 14:08
I just booted a local Gutenberg 10.7.2 and the problem reproduces clearly over there!

**Comment by cpapazoglou** [comment] 2021-06-07 14:13
Here is the offending code
https://github.com/WordPress/gutenberg/blob/27afc4d43f02713fd40f4a35b6f6f8fabc175d0f/lib/rest-api.php#L190-L217

which is already fixed in https://github.com/WordPress/gutenberg/pull/32229

**Comment by cpapazoglou** [comment] 2021-06-07 15:02
> If the `stylesheet` option is empty, could that also be what's causing the `theme_mods_{themeslug}` option to get overwritten with `-`, causing the issues we're seeing saving customizer changes?
> 
> #53431
> 
> If I'm reading it right (I might not be), JP sync uses the `stylesheet` option to sync the theme_mods:
> 
> https://github.com/Automattic/jetpack/blob/05de5b8f8fba2bd86c607abbc3e98e49c9cc739c/projects/packages/sync/src/modules/class-options.php#L228

As it seems these two issues are unrelated. #53431 is still reproducible with Gutenberg disabled.

**Comment by cpapazoglou** [comment] 2021-06-07 15:03
Related convo about pushing a custom build for Simple sites p1623062896261500-slack-C7YPUHBB2

Atomic Sites will need to wait for the next release of Gutenberg on Wednesday Jun 9.p1623080514158400/1623076293.157800-slack-C45SNKV4Z

**Comment by cpapazoglou** [comment] 2021-06-10 09:26
Related convo about restoring the affected sites `stylesheet` & `theme_mods_%`
p1623083655133000-slack-C020SHYRB24

**Comment by formosattic** [comment] 2021-06-11 09:27
+1 4048860-zd-woothemes

**Comment by cpapazoglou** [comment] 2021-06-16 08:34
We have stopped the spread of the issue and we are trying to restore the correct `stylesheets` to the affected blogs. It will be resolved as part of https://github.com/Automattic/wp-calypso/issues/53431. Let's continue the discussion there.

**Comment by cpapazoglou** [comment] 2021-06-23 08:03
https://github.com/Automattic/wp-calypso/issues/53431#issuecomment-866620141

**Closed as completed by cpapazoglou** 2021-06-23 08:03 UTC
Labels: Bug, [Pri] High, Triaged
