### ISSUE TITLE
People: add ability to search Followers and Viewers

### ISSUE THREAD

**Issue by kevmarsden** [Automattic/wp-calypso#12255] opened 2017-03-16 23:49 UTC
In the **People** section of Calypso it's possible to search for **Team** members and **Email Followers,** but the search icon does not appear on the **Followers** and **Viewers** tabs.  

Some sites have a lot of Followers or Viewers and it would be useful to quickly locate a specific Follower or Viewer. The current views are shown in the screenshots below:

![screen shot 2017-03-16 at 4 39 14 pm](https://cloud.githubusercontent.com/assets/2282189/24023230/10e51760-0a68-11e7-9d5f-83d9546d2ffd.png)
![screen shot 2017-03-16 at 4 41 56 pm](https://cloud.githubusercontent.com/assets/2282189/24023235/14978a3c-0a68-11e7-9322-8fec5134e07b.png)

#user-report in 248097-chat

**Comment by kevmarsden** [comment] 2017-03-17 19:48
The same user indicates that the search functionality is sometimes available under Viewers, so maybe this is a bug instead of an enhancement

3114734-t

**Comment by jeremeylduvall** [comment] 2017-03-23 12:47
It looks like we hide the ability to search here intentionally for viewers and followers:

https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/people/people-section-nav/index.jsx#L62

@ebinnion and @lezama It looks like you two worked on this previously. Sanity check? Looks like the conditional was added back in 10327-gh-calypso-pre-oss.

**Comment by ebinnion** [comment] 2017-03-23 14:39
It's been a while, but from memory, there were performance issues with searching viewers and/or followers, which is why removed the search functionality. It's possible to fix with something like an elasticsearch layer on top of viewers and followers. But, I'm not sure that it's something we'll do right now.

**Comment by jeremeylduvall** [comment] 2018-01-11 16:33
cc @ebinnion - who would know more about the performance limitations around search? That way, we can either keep this open or close as wontfix.

**Comment by ebinnion** [comment] 2018-01-11 17:58
It's been a while since I've looked at how the data is structured, but I think the issue is this:

The followers table only stores a user ID. So, to search the followers table, we then have to join the users table with the followers table, and I believe that just wasn't going to be performant for production.

Now, it's possible that if we started putting followers into Elasticsearch, that we could provide this search functionality. But, right now, I don't think we're going to do that.

**Closed** 2018-01-11 17:59 UTC
Labels: People Management, [Type] Enhancement
