### ISSUE TITLE
Launchpad: When classic theme is selected, edit site button gives compatibility error 

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#76819] opened 2023-05-11 10:55 UTC
### Quick summary

If the user still has the launchpad present when they have selected a classic theme, clicking 'edit design' results in the launchpad trying to launch the site editor, which returns in an error. 

As launchpad is supposed to help new users, this is actually a bad bug as it makes you think the site is broke. 

### Steps to reproduce

1. Start a new site to get launchpad running. 
2. Set a classic design/theme, or skip the launchpad and manually choose a classic theme. 
3. Go back to the launchpad, click edit design. 
4. You will get the error **The theme you are currently using is not compatible with the Site Editor.**

### What you expected to happen

The site editor should not try and load on a classic theme. Either it is skipped, or customizer is loaded. Needs to be some type of check. 

### What actually happened

See Video:

https://github.com/Automattic/wp-calypso/assets/5075840/1438d8ee-2f62-4463-8fdd-40d6fd894cbd

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

We had a customer churn due to this error.

**Comment by karenroldan** [comment] 2023-05-11 13:31
📌 REPRODUCTION RESULTS

- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO

- Replicated as described. After activating a classic theme and you click `Edit design` on the launchpad, you'll get an error: **The theme you are currently using is not compatible with the Site Editor**

**Theme: Varia**

https://github.com/Automattic/wp-calypso/assets/67279475/2aab04a4-ed8c-4aac-8f94-d699ffeee830




📌 ACTIONS

- Assigned to @Automattic/lego

**Comment by daledupreez** [comment] 2023-05-11 14:39
I have switched this up to Serenity, as the issue is in the launchpad rather than in the theme itself.

**Comment by daledupreez** [comment] 2023-05-15 07:05
This was addressed by #76872 (which was a re-application of #76820): we no longer show the "Edit Design" overlay for any themes.

**Closed as completed by daledupreez** 2023-05-15 07:05 UTC
Labels: Bug, [Pri] High, [Status] In Progress, [Platform] Simple, [Platform] Atomic, [Feature] Launchpad, [Status] Priority Review Triggered
