### ISSUE TITLE
Incorrect refund amount at cancellation if a user has upgraded one plan to another and canceled both the plan and their domain registered with the plan's domain credit

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#51832] opened 2021-04-10 04:15 UTC
### Steps to reproduce the behavior

1. Purchase an annual Personal plan($48) and register a custom domain at the same time by using the plan's domain credit
2. Upgrade the site to an annual Premium plan($96)
3. Cancel both the plan and domain in https://wordpress.com/me/purchases **within 96 hours**(Our domain refind window)

#### What I expected to happen

User should get a full refund which means $96.

#### What actually happened

User gets only a partial refund($78) minus domain cost($18).

**Comment by michaeldcain** [comment] 2021-04-29 20:36
I believe this is related to c/lSOH1Vyi-tr. I'll add it to the Shilling backlog to talk about it in our next planning call.

**Comment by DavidRothstein** [comment] 2021-05-04 20:01
I think it's the same as pNPgK-4ZM-p2 actually.  Or at least, that was the only way I could reproduce it -- specifically, if you cancel the plan and domain at the same time, everything works fine.  But if you cancel the plan first and then cancel the domain **after**, that's where you miss out on the second refund (the one for the domain).

In any case, I'll leave a comment on that internal issue pointing to this (and clarifying the steps to reproduce; the example here does show that you can use the domain credit earlier than noted in the discussion there).

**Comment by DavidRothstein** [comment] 2021-05-04 20:08
Done.  I'll close this issue now, since we're tracking it elsewhere and it's not a Calypso issue.

**Closed as completed by DavidRothstein** 2021-05-04 20:08 UTC
Labels: Bug, [Feature Group] WPCOM Store & Purchases
