### ISSUE TITLE
Customizer: Video Widget fails to load YouTube video when added by URL

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#25195] opened 2018-05-31 11:30 UTC
This report is from a user report: 4010287-hc.

#### Steps to reproduce

1. Opened the Customizer in WordPress.com, opened the Widgets section
2. Clicked on the button to `Add a Widget`
3. Selected the `Video` widget from the list
4. Clicked on the button to `Add Video`
5. Clicked on the link to `Insert from URL`
6. Pasted the following URL into the field: https://www.youtube.com/watch?v=NNCEVYMTRtM

![](http://cld.wthms.co/CXSmal+)

#### What I expected

After adding the YouTube video URL, a video preview should appear in the window, enabling the user to add the video to their widget to complete the process.

#### What happened instead

An error appeared, stating the following:

>Sorry, we can’t load the video at the supplied URL. Please check that the URL is for a supported video file (.mp4, .m4v, .webm, .ogv, .flv) or stream (e.g. YouTube and Vimeo).

![](https://cld.wthms.co/7HIlN5+)

#### Browser / OS version

User: Chrome 66.0 on Windows 10 0.0.0 
Tester: Firefox Developer Edition 61.0b9 on macOS 10.13.4

#### Observations

This issue also manifested when testing with the older `Widgets` interface in WP Admin, in `Appearance`.

I was able to embed a YouTube video in a Text Widget on the user's site using a YouTube link. I pasted the link into the text field of the Text Widget and the link resolved into an embedded video:

![](http://cld.wthms.co/WsA7oG+)

#### Context / Source

#user-report #manual-testing

**Comment by aamills** [comment] 2018-05-31 15:54
Additional report #4017714-hc

**Comment by hermawan22** [comment] 2018-05-31 16:58
Hi guys, sorry.
I don't know where u guys see user report? This only for internal team of automattic?
Thanks guys. :)

**Comment by kylemcph** [comment] 2018-05-31 18:18
Same issue,
#1194419-zen / #4012834-hc

**Comment by designsimply** [comment] 2018-05-31 20:41
> Hi guys, sorry.
> I don't know where u guys see user report? This only for internal team of automattic?
> Thanks guys. :)

Hi @hermawan22 ! Thank you for asking about that. Yes, the codes such as 1234567-hc are internal references that we use for tracking some of our internal reports. Knowing how many times something was reported by users is one factor we use when determining prioritization for issues. Thank you for noticing them and for your interest in the Calypso project!

**Comment by hermawan22** [comment] 2018-06-01 02:21
> Hi @hermawan22 ! Thank you for asking about that. Yes, the codes such as 1234567-hc are internal references that we use for tracking some of our internal reports. Knowing how many times something was reported by users is one factor we use when determining prioritization for issues. Thank you for noticing them and for your interest in the Calypso project!

Awesome, thanks for the explanation @designsimply , hopefully can contribute much more in Calypso. :+1:

**Comment by jesscga** [comment] 2018-06-01 11:26
Reported in #4037261-hc, user is OK with Text widget workaround for now

**Comment by jesscga** [comment] 2018-06-01 11:45
Reported in #131484-hc

**Comment by nielslange** [comment] 2018-06-01 11:56
Another one in #4037888-hc

**Comment by arunsathiya** [comment] 2018-06-01 15:43
#3908100-hc / #1196243-zen

**Comment by Robertght** [comment] 2018-06-03 08:02
#1198951-zen

**Comment by arunsathiya** [comment] 2018-06-03 18:52
On testing, it seems to be affecting video links from most of  the sites shown on https://en.support.wordpress.com/videos/ 

I have been able to reproduce this error with Instagram, DailyMotion, Vimeo, YouTube and Facebook so far.

**Comment by sarahcada** [comment] 2018-06-04 08:47
Also reported at #4095614-hc

**Comment by rantoncuadrado** [comment] 2018-06-04 12:52
Also #1201581-zen and #4099233-hc

**Comment by jjchrisdiehl** [comment] 2018-06-04 18:17
Also #4107998-hc

**Comment by KokkieH** [comment] 2018-06-05 07:00
A report in the [forums](https://en.forums.wordpress.com/topic/the-video-widget-on-the-side-bar-will-not-accept-a-youtube-video/)

**Comment by kriskarkoski** [comment] 2018-06-05 12:55
#350262-hc

**Comment by rezzap** [comment] 2018-06-05 13:06
Have had another report in #4121839-hc

The alternative solution using the text widget instead worked for the user.

**Comment by eoinsav** [comment] 2018-06-05 22:27
#1204959-zen

**Comment by pauljacobson** [comment] 2018-06-06 11:51
I have another report in 4152594-zen. I recommended using a Text Widget in the meantime, too.

**Comment by kamikazeballoon** [comment] 2018-06-07 00:08
4167757-hc, text widget also worked

**Comment by sophiegyo** [comment] 2018-06-08 14:48
4205796-hc text widget works here, for Youtube videos.

**Comment by thabotswana** [comment] 2018-06-08 17:33
I got this report #2852964-hc. Advised them to use the Text Widget

**Comment by rantoncuadrado** [comment] 2018-06-10 08:22
another one #1212508-zen

**Comment by zyousafi** [comment] 2018-06-11 06:21
Another report here 3748082-hc.  Suggested they use the **Text Widget** for now.

**Comment by aamills** [comment] 2018-06-11 16:30
Reported #3589870-hc

Text widget workaround used for now, but they are training a team future staff how to build and use the site and were hoping to continue to use the video widget in training.

**Comment by kristarella** [comment] 2018-06-12 00:22
4279968-hc will suggest text widget

**Comment by sophiegyo** [comment] 2018-06-12 06:59
4285382-hc - suggested text widget, confirmed that the text widget workaround works for them.

**Comment by KokkieH** [comment] 2018-06-12 08:35
[Forums](https://en.forums.wordpress.com/topic/youtube-url-no-longer-working-in-video-widget/). Suggested the workaround.

**Comment by kylemcph** [comment] 2018-06-14 11:42
3911478-hc - suggested text widget, confirmed that the text widget workaround works for them.

**Comment by Robertght** [comment] 2018-06-18 11:18
That occurs with the Vimeo videos as well.

**Comment by aamills** [comment] 2018-06-18 17:33
4427579-hc - Suggested text widget in chat as an alternative, but not sure they understood.

**Comment by thebud15** [comment] 2018-06-18 23:50
4431936-hc User unable to add YouTube link to video widget

**Comment by jamiepalatnik** [comment] 2018-06-19 19:51
Reported here: 1229858-zen

**Comment by KokkieH** [comment] 2018-06-21 05:37
https://en.forums.wordpress.com/topic/widget-adding-a-video-to-my-sidebar/

**Comment by fstath** [comment] 2018-06-21 07:08
If you insert the video link and click on the "Add to widget" button before the message pops up, the video is properly embedded.

I have found that by accident when I tested it on a site and I was in a hurry.

**Comment by lsl** [comment] 2018-06-22 06:10
#2338655-hc - text as a workaround.

**Comment by pauljacobson** [comment] 2018-06-25 12:10
Here's another report: 2088776-hc

I also explained the workaround.

**Comment by hacchism** [comment] 2018-06-28 09:01
Another report: 1248114-zen

**Comment by zandyring** [comment] 2018-07-03 20:05
Also in 1247490-zen

**Comment by lancewillett** [comment] 2018-07-03 21:48
For future reference — no need to move this one, but next time — this isn't a Calypso bug since Customizer runs WP Admin *inside* Calypso and is a separate tech stack and codebase — and we have a different repo for it at `Automattic/customization`.

**Comment by jblz** [comment] 2018-07-03 22:08
Looks like this has something to do with the media js calling the oembed proxy endpoint differently on WPCOM sites.

On my test site, the client makes a request that looks like:
`https://public-api.wordpress.com/oembed/1.0/sites/1234/proxy?_envelope=1&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DvchLJE-RceM&discover=false`

...& it `404`s.

---

On a Jetpack-connected site, the request looks like:
`https://adjective-noun.jurassic.ninja/wp-json/oembed/1.0/proxy?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DvchLJE-RceM&discover=false`

...& it gets the proper media metadata in response.

---

Further, the WPCOM site shows an error in the console:

`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.youtube.com/watch?v=vchLJE-RceM with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

Investigating.

**Comment by nylen** [comment] 2018-07-04 01:20
Thanks @jblz for jogging my memory with those API URLs.  This should be fixed as of r177925-wpcom.

**Comment by mishivee** [comment] 2019-08-03 16:57
Hi there @nylen and @jblz! This issue needs to be reopened. I am seeing the same exact error today - same steps to reproduce on simple sites only. 

Video: https://cld.wthms.co/4S2N4H


![](https://cld.wthms.co/bM7IFx+)

Direct link to image: https://cld.wthms.co/bM7IFx

**Comment by tbradsha** [comment] 2019-08-03 16:59
Another in #2246322-zen.

**Comment by tbradsha** [comment] 2019-08-03 17:01
Workaround for now: paste the YouTube URL in a text widget.

**Comment by KokkieH** [comment] 2019-08-03 18:04
This is not a Calypso issue, as the widget code doesn't live in Calypso, and this happens in /wp-admin/widgets.php as well.

Reported earlier in 8153-wpcom

**Comment by suyogyashukla** [comment] 2019-11-10 18:41
Reopening this as it looks like embedding YouTube video on non-AT sites isn't working, same error as reported originally. 

What I have tried:

- WPORG install, works as expected.
- WPCOM AT, works as expected.
- WPCOM Simple (Premium or Biz), gives:

>Sorry, we can’t load the video at the supplied URL. Please check that the URL is for a supported video file (.mp4, .m4v, .webm, .ogv, .flv) or stream (e.g. YouTube and Vimeo).

**Comment by suyogyashukla** [comment] 2019-11-10 18:44
Closing this and moving to 8153-wpcom

**Comment by gwwar** [comment] 2020-02-27 11:38
Reserving this comment for debugging:

Noting that this is likely a malformed client request:
![image_720](https://user-images.githubusercontent.com/1270189/75441424-f1b19880-595d-11ea-8f7b-d359cb7b847f.png)

**Comment by gwwar** [comment] 2020-03-03 00:23
While I work on a fix, I believe dropping the http or https protocol will allow for youtube video embedding. So for example:

`youtube.com/watch?v=EQx6fyrZDWM` instead of `https://youtube.com/watch?v=EQx6fyrZDWM`

**Comment by mmtr** [comment] 2020-03-03 12:56
> this is likely a malformed client request

I think you are correct. Apparently we're making the request with the URL to embed as a body param, but the oEmbed proxy is expecting it as a query param. D39741-code should fix this.

**Comment by lancewillett** [comment] 2020-03-03 16:06
Confirmed the patch listed above works as expected. Woot!

(Using Firefox latest stable on macOS with a WordPress.com Simple test site.)

Before:
<img width="1392" alt="Screen Shot 2020-03-03 at 08 59 42" src="https://user-images.githubusercontent.com/66797/75794548-2cd11480-5d2e-11ea-8ace-78447e20e4b4.png">
<img width="1392" alt="Screen Shot 2020-03-03 at 08 59 51" src="https://user-images.githubusercontent.com/66797/75794556-30649b80-5d2e-11ea-9b9a-09b0cf04a3fe.png">

After:
<img width="1392" alt="Screen Shot 2020-03-03 at 09 03 26" src="https://user-images.githubusercontent.com/66797/75794558-30fd3200-5d2e-11ea-81db-2f3de1ebc9d4.png">
<img width="1392" alt="Screen Shot 2020-03-03 at 09 03 33" src="https://user-images.githubusercontent.com/66797/75794562-322e5f00-5d2e-11ea-8b32-2e7f1a448476.png">
<img width="1392" alt="Screen Shot 2020-03-03 at 09 03 52" src="https://user-images.githubusercontent.com/66797/75794569-335f8c00-5d2e-11ea-9c8a-a8337eded3fd.png">

**Comment by lancewillett** [comment] 2020-03-03 16:07
Adding a few UX notes, not a blocker for this change.

In the widget pane:

1. Change the placeholder from `http://` to `https://`
2. Possibly show a larger video preview in the widget pane

**Comment by gwwar** [comment] 2020-03-03 19:54
> Adding a few UX notes, not a blocker for this change.

@lancewillett these suggestions make sense. 👍 

This is the core video widget so it might be better to follow up as an upstream contribution versus adding a customization here.

**Comment by gwwar** [comment] 2020-03-03 19:57
Noting that @mmtr fixed this in D39741-code. Thanks for the reports y'all. ✨

If this breaks again in the future, please favor filing a new issue over reopening. This mainly reduces the amount of reading/history on the issue and sometimes an issue break for different reasons. It's not a problem to copy paste the summary for example if reproduction steps are the same.

**Closed by gwwar** 2020-03-03 19:57 UTC
Labels: Customizer, [Type] Bug
