### ISSUE TITLE
Domain email verification interface does not update the contact email address 

### ISSUE THREAD

**Issue by flaviozavan** [Automattic/wp-calypso#23852] opened 2018-04-03 13:54 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/manage/$YOUR_BLOG
1. Click add domain, choose a domain, follow the screens until you get to the "Domain Contact Information" form
1. Fill the form, enter a dummy email address say "dummy@example.com"
1. Complete the process, the website should let you know that your email address needs to be verified
1. There should now be a "Please verify $YOUR_DOMAIN" message with a fix button on the top left of the page. Click the fix button.
1. You should see "Important: Verify Your Email Address" and "Check your email — instructions sent to dummy@example.com." and two options "send again" and "change email address".
1. Click "change email address", change the dummy email address to something real like "real@realdomain.com". Submit the form.
1. Click the fix button on the top left of the page again.
1. Click "send again"

#### What I expected
To be presented with "Check your email — instructions sent to real@realdomain.com"

#### What happened instead
I was presented with "Check your email — instructions sent to dummy@example.com."
After a couple of minutes, the actual email was sent to real@realdomain.com and I was able to verify the domain.

#### Browser / OS version
Firefox 58.0.2 (64 bit)
Linux 4.15.8

#### Screenshot / Video
Screenshots edited slightly.

![pleaseverify](https://user-images.githubusercontent.com/959292/38252687-341d9180-372b-11e8-9879-5d5cdb4b98f5.png)
![sent](https://user-images.githubusercontent.com/959292/38252693-37b9e942-372b-11e8-81ce-e7209fa9b8ea.png)

#### Context / Source
Found while setting up a testing blog and realizing I would have to verify the email address.
Possibly unrelated to #22847 as my account's email address is neither the dummy nor the real address used when registering the domain.

**Comment by klimeryk** [comment] 2018-04-05 12:54
I'd guess the root cause is the fact that we have domain-related info stored within Calypso in two types of stores: old, flux ones (most of Domain Management) and newer, Reduxified (only Domain Warnings?). When the WHOIS is updated, it updates the old flux store, but not the Redux one. And as a result, the change is not reflected in the warning shown in the sidebar (which is powered by the Redux store).

**Comment by klimeryk** [comment] 2021-02-09 21:44
Almost three years later (sigh) - but the bug has been fixed in the meantime thanks to the recent domain management revamp.
I've checked and the new (unverified) email address is automatically and instantaneously updated:

<img width="740" alt="Screenshot 2021-02-09 at 21 43 20" src="https://user-images.githubusercontent.com/3392497/107432501-f72cd200-6b1f-11eb-8a57-0d8188d9918b.png">

**Closed by klimeryk** 2021-02-09 21:44 UTC
Labels: Domains, OSS Citizen, [Type] Bug
