### ISSUE TITLE
Themes: on mobile (iOS) the preview is not showing and undismissable

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#2566] opened 2016-01-19 11:34 UTC
Testing the logged out theme showcase (M3) at `/design` on iOS has a non-working preview.

Portrait:

<img src="https://cloud.githubusercontent.com/assets/4389/12417461/23d81364-bea0-11e5-8bdb-1ee884630658.jpg" width="200">

Landscape:

<img src="https://cloud.githubusercontent.com/assets/4389/12417462/26811f70-bea0-11e5-8984-517639f2bd58.jpg" width="400">

Notes:

1. On a desktop preview it works, so it's happening only on device
2. The preview doesn't load
3. The controls overlap the masterbar on portrait views
4. Might be preview component issue, not strictly themes

/cc @sixhours

**Comment by ehg** [comment] 2016-01-19 12:06
This looks like a duplicate of #2129

**Comment by folletto** [comment] 2016-01-19 12:37
Might be, but there are some slight differences, so I'm not 100% sure. The differences for me are the overlapping masterbar (no access to the bar) and the fact that I can't reproduce on Chrome/Firefox. So... I don't know. I guess we'll discover once we start fixing either. :D

**Comment by folletto** [comment] 2016-02-17 15:31
I tested #3350 after the merge and unfortunately there are still oddities on both Theme preview and Editor preview:

1. Chrome/Mac: there's a blank gap above, the [iframe is cut](https://cloud.githubusercontent.com/assets/4389/13114306/e190bdb0-d58a-11e5-8e0d-577830dc969e.png)
2. Firefox/Mac: seems ok (some oddities in the menu tho)
3. Safari/Mac: seems ok (some oddities in the menu tho), double scrolling depending on where the mouse is placed
4. Safari/iOS: the positioning is correct, but doesn't scroll  — the page below scrolls, making it unusable

/cc @aduth

**Closed** 2016-02-19 12:53 UTC
Labels: Themes, [Type] Bug
