### ISSUE TITLE
Reader: Jetpack slideshow block displays as bulleted image list

### ISSUE THREAD

**Issue by aforcier** [Automattic/wp-calypso#45085] opened 2020-08-21 00:53 UTC
#### Steps to reproduce

1. Create a new post with a Slideshow block
2. View that post in the reader (Calypso, WPAndroid, or WPiOS)
3. Observe that the images show up as a bulleted list

#### What I expected

Possibly the slideshow in gallery format, or at least no bullets.

#### Browser / OS version

Tested and found the issue to exist everywhere on Mac Chrome & Firefox, and in the WPAndroid and WPiOS readers, as well as email.

Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/12738
iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/14701

#### Screenshot / Video

<img width="334" alt="calypso-reader-slideshow-bullet-list" src="https://user-images.githubusercontent.com/9613966/90840045-ec288e80-e393-11ea-9f74-88a66409b1e8.png">

#### Context / Source

#dogfooding

**Comment by dhackneya8c** [comment] 2020-09-17 18:34
Complaint from user for this issue in #24211449-hc

**Comment by yashitamittal11** [comment] 2021-02-09 00:22
Another one- #3720981-zen

**Comment by davipontesblog** [comment] 2021-04-14 14:11
Part of the Block Audit milestone: https://github.com/Automattic/wp-calypso/milestone/320
As discussed with @4thhubbard, leaving it for future consideration.

**Comment by karenroldan** [comment] 2023-08-25 13:25
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
The issue can be replicated exactly as described above. 

**Live Page**

![kM72F0.png](https://github.com/Automattic/wp-calypso/assets/67279475/89daa9a0-8d7e-4761-8a83-031c2f6d0dcd)

**Reader**

![LubWsN.png](https://github.com/Automattic/wp-calypso/assets/67279475/08133028-13f5-4c68-8372-47f9b9be8817)

**Comment by sixhours** [comment] 2023-12-04 20:53
It looks like at one point we did support a version of the Jetpack Slideshow block in the Reader, but the slideshow block changed and now it's not supported. We still look for the `.jetpack-slideshow` embed here:

fbhepr%2Skers%2Spnylcfb%2Spyvrag%2Spbzcbaragf%2Srzorq%2Qpbagnvare%2Svaqrk.wfk%3Se%3Q58nn7nr7%2316-og

But that doesn't work because the parent selector and the carousel library have changed, from cycleJS to Swiper:

fbhepr%2Skers%2Spnylcfb%2Spyvrag%2Spbzcbaragf%2Srzorq%2Qpbagnvare%2Svaqrk.wfk%3Se%3Q58nn7nr7%23159%2Q193-og

So we may need to take a similar approach as what I'm looking at for the Post Carousel in https://github.com/Automattic/wp-calypso/pull/84833

**Comment by sixhours** [comment] 2023-12-06 20:58
This has been addressed by https://github.com/Automattic/wp-calypso/pull/84833

**Closed by sixhours** 2023-12-06 20:58 UTC
Labels: [Type] Bug, Jetpack, [Pri] Normal, [Feature] Reader, User Report, Triaged, Customer Report, [Product] WordPress.com, [Feature Group] User Interaction & Engagement
