### ISSUE TITLE
Fullpost keyboard j & k shortcuts

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#10097] opened 2016-12-15 20:10 UTC
On the fullpost view, hitting j & k used to move you back & next. I guess this dropped out in the fullpost refresh. Bring it back?

**Comment by designsimply** [comment] 2016-12-28 19:03
Duplicate of https://github.com/Automattic/wp-calypso/issues/7421

> Bring it back? 

Yes, pls!

**Comment by samouri** [comment] 2016-12-30 21:44
I've been poking at what I think the changes needed to support this are....and its surprisingly hefty.
We used to have the Stream loaded but hidden while FullPost was open which made the FullPost implementation essential come for free. 

Now that we are full unmounting the stream, we are going to need to start recording currentStream in some capacity.  I'm not sure the best way to go about this and right now and my first instinct after looking through relevant code bits is:

1. short term solution: use an optional query param `storeId`
2. long term solution: record like currentStream, currenltySelected in the redux state tree

**Comment by blowery** [comment] 2016-12-31 00:40
I was going to stash it in a module level variable in controller-helper.

**Comment by samouri** [comment] 2017-01-02 19:19
@blowery good idea! Thats a better short-term solution than a query param 👍 
I'll move it (and clean up the duped code --> utils.js )

**Comment by samouri** [comment] 2017-01-11 00:41
pr merged so closing this

**Closed by samouri** 2017-01-11 00:41 UTC
Labels: Reader, [Type] Task
