### ISSUE TITLE
Gutenberg: Reusable blocks creating infinite loops: Published posts front-end, Post list in Calypso, and Editor not loading. 500 errors present.  

### ISSUE THREAD

**Issue by aleone89** [Automattic/wp-calypso#49007] opened 2021-01-18 17:03 UTC
#### Steps to reproduce

**Frontend:** 
https://lescarnets.home.blog/ > click on continue reading on a post > no post loads > Console: https://d.pr/i/2gM188

**Backend**
https://lescarnets.home.blog/ > /wp-admin > Posts > click edit on a post that is published > Console: https://d.pr/i/P7a5WF

#### What I expected

Frontend > to see the post content

Backend > to see the post content 

#### What happened instead

Frontend > Site is visible, the post title is visible, the post content does not load. 

Backend > Nothing loads, just a white screen is visible.
 
#### Browser / OS version

Chrome 87
FF 84.0.2 

#### Screenshot / Video

Frontend - example site: https://lescarnets.home.blog/

<img width="1621" alt="Screen Shot on 2021-01-18 at 16-22-32" src="https://user-images.githubusercontent.com/39101026/104944179-bc1b0100-59ae-11eb-9852-15620d06572e.png">

backend - example site: https://lescarnets.home.blog/

<img width="1604" alt="Screen Shot on 2021-01-18 at 16-22-49" src="https://user-images.githubusercontent.com/39101026/104944302-ea004580-59ae-11eb-9d48-16903c572b9a.png">

#### Context / Source

Reported on public forums here: https://wordpress.com/forums/topic/how-come-when-i-go-to-my-blog-and-see-the-posts-and-click-continue-reading-it-only-shows-the-title-of-the-post-2/ 

Example sites reported (so far): 

https://lescarnets.home.blog/
https://backyardhobbyfarm.home.blog/

**Comment by JoshuaGoode** [comment] 2021-01-18 19:14
These sites all have at least one reusable block that calls back to itself, creating an infinite loop that then crashes the editor, Calypso page/post list, and front end.  The GETs related to the posts fail with 500.

The question is, have the sites always had these infinite loops but it just started causing issues after an update? Or, did something change within the editor that makes it easier to edit a block and create these loops? 

A longer discussion of the issue here with @nickpagz and @cathymcbride : p1610986104013800-slack-C02FMH4G8 

We haven't been able to report our findings just yet as we've both been chatting. 

**Identifying the loop**
To find the broken block, one can navigate to `wp-admin/edit.php?post_type=wp_block`.  There, open the blocks in the Classic Editor.   Then, look for reusable blocks calling themselves. For example, reusable block with ID 41 would be having the issue if its content was  `<!-- wp:block {"ref":41 } /-->`

**Comment by JoshuaGoode** [comment] 2021-01-18 19:40
Reusable blocks don't appear to have a revision history so I can't easily tell if the blocks have been like this for some time and just now started causing the 500s after an update -- or if a change was made that makes accidentally editing these reusable block easier. 

In a test, it was very easy for me to add a reusable block and then accidentally add it to itself. 

I also just updated the title to be a bit closer to describing the issue at hand.

**Comment by sirreal** [comment] 2021-01-18 19:57
This looks like an example of https://github.com/WordPress/gutenberg/issues/18704, which is a known issue.

Note that the block need not reference itself. Larger loops will trigger the problematic behavior.

**Comment by JoshuaGoode** [comment] 2021-01-18 20:00
Highlighting that we just started getting these specific reports starting around January 15th and this completely breaks the Post/Page lists in Calypso and prevents post and reusable block editing on the impacted posts.

I suspect that it must now be easier to accidentally edit reusable blocks and create such loops.  

The steps to fix these sites is to access the reusable block list in the site's wp-admin at `wp-admin/edit.php?post_type=wp_block`, edit the blocks using the Classic Editor, identify the block(s) causing the loop, and remove the reference.

**Comment by JoshuaGoode** [comment] 2021-01-18 20:06
Other sites that started having the issue just recently:

3655949-zen: scarletsmods.com
24860869-hc & 3661010-zen: travelwithintent.wordpress.com

The reusable blocks causing the issue were identified and repaired.  Discussed internally at p1610986104013800-slack-C02FMH4G8

**Comment by sirreal** [comment] 2021-01-18 20:18
For reference:

- Gutenberg 9.6 was activated on 2021-01-11 r219216-wpcom
- Gutenberg 9.7 was activated on 2021-01-14 r219435-wpcom

**Comment by JoshuaGoode** [comment] 2021-01-18 20:43
Related to https://github.com/Automattic/wp-calypso/issues/38929 & https://github.com/WordPress/gutenberg/issues/18704 --  however, we're seeing an unusual influx of new reports and it does appear to be due to how easy it is to edit and add content within a reusable block.   Once a user does this, Calypso, the editor, and the post's front end all break and generate 500 errors.

**Comparison of Current vs Previous Reusable Block Editing**
I've recorded a quick demonstration of how easy it is to edit reusable blocks when creating a new post after recent updates (includes audio commentary): https://d.pr/v/hGhS3L


Here's how things are handled in WP Core, without the Gutenberg plugin active, and on an Atomic site with 9.5.2.  It's much harder to create such a loop and the user has to intentionally edit the reusable block:
https://d.pr/v/Ok1cEj

**Comment by JoshuaGoode** [comment] 2021-01-18 20:58
@glendaviesnz mentioned there was a recent reusable block refactor: https://github.com/WordPress/gutenberg/pull/27887

Seems to have made some good usability improvements to reusable blocks; however, it has also made it very easy to create these loops.

**Comment by Copons** [comment] 2021-01-19 15:27
I gave this a quick try and I agree that this is caused by reusable blocks referencing themselves, and that it also happens on Core Gutenberg.
I'm not exactly sure _how_ folks have managed to get a reusable block to self-ref, as whenever I've tried it, it basically crashed my browser before I had a chance to save the block. 😅 

Either way, this needs to be fixed from Core, by preventing the loop in the first place.

I've added `[Pri] Normal` as I'd argue that while this is a very nasty issue, it will hardly affect a large number of sites.

---

I've checked the various sites reported in this issue, and AFAICS only `backyardhobbyfarm.home.blog` has still troubles (cc @aleone89).
The site only has one reusable block, which indeed references itself.
Its content is literally only the self-reference, so my recommendation for a quick fix would be to delete the reusable block, which would result in the block not rendering anything, without breaking the site.

**Comment by JoshuaGoode** [comment] 2021-01-19 17:32
Thanks, @Copons!

Looks like it depends on the content of the reusable block.  In the cases I examined, the culprit was often a reusable customized Spacer block that doesn't seem to crash the browser when self-referenced and allows users to Update/Publish their changes.

An example of this [was in my comparison video](https://github.com/Automattic/wp-calypso/issues/49007#issuecomment-762462521), I didn't encounter a browser freeze/crash but it was slow for a moment.

**Comment by nickdaugherty** [comment] 2021-01-19 19:00
> A longer discussion of the issue here with @nickdaugherty and @cathymcbride : p1610986104013800-slack-C02FMH4G8

@JoshuaGoode you may have meant to tag @nickpagz...unless I just have a really bad memory...

**Comment by tbradsha** [comment] 2021-01-19 21:17
3660798-zen

**Comment by nagpai** [comment] 2021-01-20 04:02
3663909-zen

**Comment by sirreal** [comment] 2021-01-20 09:21
There's very good feedback here that we need to surface to the Gutenberg project. The struggles that users have and demonstrations like [these](https://github.com/Automattic/wp-calypso/issues/49007#issuecomment-762462521) can help to inform the design and development.

@inaikem is that something you'd like to work on as a product ambassador? I'm happy to assist.

**Comment by kdevnel** [comment] 2021-01-20 11:53
I just had this come up again in 27132890-hc

The issue here was that we had to remove the content from the reusable block so they could edit it and restore the actual content. Trouble is, every time they tried to edit it the block broke again. Getting them to edit directly in the reusable block editor seems to have worked.

**Comment by Copons** [comment] 2021-01-20 13:36
A couple of updates from Core:

- There is a [relatively recent PR](https://github.com/WordPress/gutenberg/pull/27012) open to fix the infinite loop.

- The confusing UI is recognized, and there are [talks](https://github.com/WordPress/gutenberg/issues/28285) to make it consistent with the FSE's template part blocks (basically add an outline on hover/focus/selection).
A stop-gap [PR](https://github.com/WordPress/gutenberg/pull/28283) that adds simple outline to the parent block when a child is selected was merged and will be included in Gutenberg 9.9.

**Comment by Nic-Sevic** [comment] 2021-01-20 14:23
Again here and resolved
3666143-zen

**Comment by Nic-Sevic** [comment] 2021-01-20 16:20
3656219-zen
cleaned up references and seems resolved

**Comment by kelasante** [comment] 2021-01-20 21:20
3667493-zen removed references. Seems resolved.

**Comment by xpurichan** [comment] 2021-01-20 22:33
3643465-zen seems like it may be related but I haven't gotten to the bottom of it yet. From my understanding there is at least one reusable block that is blank (but it should have content) and some reusable blocks duplicate content (unclear if they duplicate their own content or other content) and cause issues when trying to save and leave the page.

I'm working to get more clarity on this one so we can start investigating.

**Comment by scosgro** [comment] 2021-01-20 22:59
Just had 2 more of these show up in Slack from chat support. 

If anyone makes their way here, and are looking for a solution to the crashing, you can view/delete the reusable blocks from WP-Admin, here:

/wp-admin/edit.php?post_type=wp_block

Then edit in the Classic Editor, using:

/wp-admin/post.php?post=24479&action=edit&classic-editor

Where the ID# in the URL is the ID# for the block.

Or possibly Calypso (doesn't always work), here:

https://wordpress.com/types/wp_block/

It requires removing the reusable block entirely, or editing it (if it allows you).

**Comment by donalirl** [comment] 2021-01-22 01:18
Occurred in #3658435-zen

**Comment by happychait** [comment] 2021-01-22 01:27
Another instance in 27179267-hc

**Comment by kriskarkoski** [comment] 2021-01-22 18:28
26909375-hc

**Comment by eurello** [comment] 2021-01-22 21:09
I had another one in 26522721-hc

@sirreal and @Copons I understand this is a core issue, but I don't suppose there is any way we can improve this for our customers meanwhile? It is happening pretty frequently.

**Comment by jartes** [comment] 2021-01-23 08:47
Another report here: 3667625-zen

**Comment by inaikem** [comment] 2021-01-24 09:35
> @inaikem is that something you'd like to work on as a product ambassador? I'm happy to assist.

@sirreal, yes please. I'd like to post a P2 to Happiness. I'll start drafting something immediately.

Adding my 2¢ here, I'm 100% certain that this is new behaviour on WPcom. Testing editing a reusable block on a WPorg site behaves exactly as this WPcom support guide suggests: https://wordpress.com/support/wordpress-editor/blocks/reusable-block/. 

_"If you’d like to edit a reusable block, select the reusable block and click on Edit. When you’re done with the changes, hit the Save button."_

However, WPcom sites now permit reusable blocks to be edited with a single click inside the block. In addition, the visual cue and click-to-edit button for these blocks no longer appears:

![Editing RB - WPcom vs org](https://user-images.githubusercontent.com/66711744/105626878-f16f9500-5e6d-11eb-9894-d4892499201f.png)

Adding to @JoshuaGoode's [screencast here](https://github.com/Automattic/wp-calypso/issues/49007#issuecomment-762462521), and [comment above](https://github.com/Automattic/wp-calypso/issues/49007#issuecomment-762462521),  alongside the above screenshot, I believe the simpler, "click to edit" nature of the blocks makes them both earlier to edit and easier to make these inadvertent recursive changes.

Are we able to trace this back to a recent update?

Cc @eurello

**Comment by rinazrina** [comment] 2021-01-25 03:11
Another report: #3679815-zen

**Comment by inaikem** [comment] 2021-01-25 03:27
Could this be related? Via @katiebethbrown : https://github.com/WordPress/gutenberg/pull/27887

**Comment by sirreal** [comment] 2021-01-25 12:28
Internal post from @inaikem p7DVsv-alB-p2

https://github.com/WordPress/gutenberg/pull/28405 and https://github.com/WordPress/gutenberg/pull/28428 addressed this and I'll advocate for a patch release including those fixed.

We don't really have good solutions for improving this without a Gutenberg release.

**Comment by thesacredpath** [comment] 2021-01-26 06:53
Another report here: #3676992-zen

**Comment by marcuswisecaesar** [comment] 2021-01-26 17:52
Another report here: #27280818-hc

**Comment by thabotswana** [comment] 2021-01-27 14:26
Another report here: 3687664-zen

**Comment by philnick206** [comment] 2021-01-28 09:24
Another report here: #3676255-zen

**Comment by scosgro** [comment] 2021-01-29 21:39
Another one - #3670104-zen

**Comment by kristarella** [comment] 2021-01-31 23:48
23391318-hc

Sending block to Trash, and then restoring (which goes to Draft), and then editing as draft worked.

**Comment by TeniCola** [comment] 2021-02-01 02:31
Another report -- #27408256-hc

**Comment by JoshuaGoode** [comment] 2021-02-01 21:02
Encountered on 23372432-hc

**Comment by donalirl** [comment] 2021-02-01 22:28
#3701283-zen

**Comment by donalirl** [comment] 2021-02-01 23:57
#27436081-hc

**Comment by jackiejade** [comment] 2021-02-02 18:01
#10834155-hc

**Comment by philnick206** [comment] 2021-02-03 09:07
#3706291-zen

**Comment by yashitamittal11** [comment] 2021-02-04 06:56
#3710575-zen

**Comment by rachelwinspear** [comment] 2021-02-04 16:19
Another report here: #3711599-zen

**Comment by desnum** [comment] 2021-02-04 18:20
hc-26238505

**Comment by sirreal** [comment] 2021-02-04 18:28
Some mitigation with styling D56058-code deployed in r220537-wpcom

**Comment by kriskarkoski** [comment] 2021-02-07 16:44
3719126-zen had this issue on 3 blocks

**Comment by carinapilar** [comment] 2021-02-08 17:26
Another one on 27460617-hc with 2 Reusable blocks.

**Comment by donalirl** [comment] 2021-02-08 22:24
#18659345-hc

**Comment by dolgelukkig** [comment] 2021-02-09 10:50
#27618315-hc

**Comment by rachelwinspear** [comment] 2021-02-09 11:48
#27620402-hc

**Comment by vinnykaur** [comment] 2021-02-10 05:18
#27639197-hc

**Comment by scosgro** [comment] 2021-02-11 22:11
#11656743-hc

**Comment by villanovachile** [comment] 2021-02-12 21:53
Another #3726284-zen

**Comment by isocialtish** [comment] 2021-03-05 18:57
This came up in #28206056-hc. It was such a problem it was affecting their launch and I needed to offer a refund for a month of their Business plan

**Comment by cathymcbride** [comment] 2021-03-09 18:30
@isocialtish I believe this should have been fixed with Gutenberg 9.9. Do you happen to know what your user was using?

**Comment by simison** [comment] 2021-03-12 10:28
We can probably close and let's re-open if we get any reports, or open a new issue if this happens, because it's likely unrelated. Upstream issue: https://github.com/WordPress/gutenberg/issues/18704

cc @WunderBart @fullofcaffeine who were working on shipping fixed Gutenberg.

**Closed as completed by simison** 2021-03-12 10:28 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] Normal, Blocks, [Status] Fix Inbound
