### ISSUE TITLE
Gutenberg: WordPress.com Media Modal does not appear in place of core media modal

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#31298] opened 2019-03-08 01:59 UTC
**Describe the bug**
Edit from @gwwar:

The Core Media Library displays instead of the WordPress.com Media Library. 

To reproduce:
- Select a site with a mapped domain
- Visit /block-editor
- Click on any item that will trigger the media modal, like the feature cover block, image, or media. 

See p1552024521367100-slack-lannister

Likely the message passing isn't making it through to the parent iframe. 

cc @Automattic/lannister to follow up

**To Reproduce**
1. For an affected site
2. Click on Posts - Add
3. Try clicking on the "media modal" for any blocks like image

**Follow-up**
#1861657-zd 

#### What I expected
They expected an Insert from URL option to be available on the Media & Text Block. 
They expected the Media Library button on the same block to have more functionality, that they claim to have lost. 

#### What happened instead
Insert From URL is no longer available on Media & Text
Media Library button has reduced functionality compared to a previous version. 

#### Browser / OS version
All

#### Context / Source
 #empathy #perspective #reallife #flowsharing #anxiety #anxiety-flow #stresscase #painpoint.

#user-report

**Comment by richardeschloss** [comment] 2019-03-08 04:08
Can I confirm with the screenshot, the same issue? 
![image](https://user-images.githubusercontent.com/5906351/54007007-12655a80-411d-11e9-9a7f-774e0c02dfd5.png)

I'm really to new to the project, but if I understand the UI element that's missing feature, I may be able to troubleshoot.

**Comment by scosgro** [comment] 2019-03-08 04:54
> Can I confirm with the screenshot, the same issue?

Yep, correct! Compare that to a Media Block alone, which does have the Insert from URL option available.

As for the Media Library part, I don't have any screenshots available for comparison on Gutenlypso vs Gutenframes.

**Comment by richardeschloss** [comment] 2019-03-08 05:02
ok, I'm wondering if this related to tinymce drop-zone.jsx. Lemme check that code.

**Comment by gwwar** [comment] 2019-03-08 05:25
The lack of insert from URL appears to be a core WordPress behavior for the Media and Text Block. (I suspect to help with the smaller space).

After clicking on "Media Library: is the following visible?

<img width="376" alt="screen shot 2019-03-07 at 10 21 03 pm" src="https://user-images.githubusercontent.com/1270189/54009339-b05e2280-4127-11e9-813e-10819cd7a503.png">

**Comment by richardeschloss** [comment] 2019-03-08 05:32
Yes. Good point Kerry! And I also notice the ability to specify URL near that part too.. 
![image](https://user-images.githubusercontent.com/5906351/54009635-d801ba80-4128-11e9-8916-e08db6db9098.png)

So, the features *are* there, in what seems to be pretty logical place...

**Comment by scosgro** [comment] 2019-03-08 05:37
> The lack of insert from URL appears to be a core WordPress behavior for the Media and Text Block. (I suspect to help with the smaller space).
> 
> After clicking on "Media Library: is the following visible?
> 
> <img alt="screen shot 2019-03-07 at 10 21 03 pm" width="376" src="https://user-images.githubusercontent.com/1270189/54009339-b05e2280-4127-11e9-813e-10819cd7a503.png">

Not visible. .gif here for reference:
https://cloudup.com/cOB6sLTDlcm

**Comment by gwwar** [comment] 2019-03-08 05:41
Thanks @scosgro that gif helps, what is appearing there is the standard WordPress vs WordPress.com media modal. 

Which browser are you using, and what URL was that taken from?

`wordpress.com/block-editor/my-site` or
`mysite/wp-admin/post-new.php`

**Comment by scosgro** [comment] 2019-03-08 05:43
>Which browser are you using, and what URL was that taken from?

.gif was taken from wordpress.com/block-editor/my-site in Google Chrome Version 72.0.3626.121 (Official Build) (64-bit), Windows 10.

**Comment by richardeschloss** [comment] 2019-03-08 06:07
Also, fwiw, the issue is also slightly repeatable at wordpress.org/gutenberg . (Might be high priority if people attempt to play with it there...you'll see when you play with it)

**Comment by torres126** [comment] 2019-03-08 06:34
Just noting that this is possible a duplicate of #31294, and fixing this would probably fix #31165 too.

**Comment by gwwar** [comment] 2019-03-11 15:59
We had another report of this failing in https://github.com/Automattic/wp-calypso/issues/31298 where folks are able to reproduce this without a console error on editor load.

**Closed** 2019-03-11 17:54 UTC
Labels: [Goal] Gutenberg, [Pri] High, [Type] Bug
