### ISSUE TITLE
Sharing: Twitter custom message is not respected.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#49798] opened 2021-02-07 20:42 UTC
If a custom message is entered for Twitter sharing before publishing a post, the tweet it produces will not have the custom message. Instead, the resulting text will match the post title.

| Custom Message | Result |
| --- | --- |
<img width="295" alt="Screen Shot 2021-02-07 at 12 38 32 PM" src="https://user-images.githubusercontent.com/349751/107158925-d6a72100-6941-11eb-8344-9d076d651265.png"> | <img width="629" alt="Screen Shot 2021-02-07 at 12 31 27 PM" src="https://user-images.githubusercontent.com/349751/107158932-dc9d0200-6941-11eb-893f-821f56cdcbbc.png">

**Comment by cathymcbride** [comment] 2021-02-08 16:50
Closing as duplicate of https://github.com/Automattic/jetpack/issues/40663

**Closed as completed by cathymcbride** 2021-02-08 16:50 UTC
Labels: Bug, [Feature] Sharing
