### ISSUE TITLE
WordPress.com Checkout: Copy of user's completed cart

### ISSUE THREAD

**Issue by MindyPostoff** [Automattic/wp-calypso#26311] opened 2018-07-25 20:22 UTC
I have received a few reports of WordPress.com users noticing the pop-up message in their dashboard that they can complete their order, after they have successfully paid for a plan. 

I haven't been able to reproduce the issue (as I haven't paid for an actual order), but the item in the user's cart is the same plan that they have already purchased.

#user-report in the following:
5143264-hc
1299855-zen

I believe this issue may have been brought up a couple weeks ago, but I can't find any other reports. @andrewspittle - your name came up when discussing this. Does it sound familiar to you?

The workaround I presented is to manually go into the checkout and trash the item in the cart.

**Comment by andrewspittle** [comment] 2018-07-25 22:07
I noticed this come up once but was also unable to reproduce it myself. It seemed somewhat similar to #24579 which deals with invalid products in the cart. Past that I don't have any more details or hypotheses as to what's happening.

**Comment by prettyboymp** [comment] 2018-08-01 20:02
Do you have any idea of when this started happening?

Trying to track down possible causes.

**Comment by MindyPostoff** [comment] 2018-08-02 04:13
@prettyboymp - I think I recall the first reports around July 20th (give or take a couple days).

**Comment by yoavf** [comment] 2018-08-02 09:16
Sorry about this - it's a known issue for users who went through a redirect-type checkout between 2018-06-18 and 2018-07-11 - which is the case for both users mentioned here.

I'll close this for now.
We may still get new reports - if those are from  a different kind of users, please reopen this.

**Comment by yoavf** [comment] 2018-08-02 09:16
(You can simply instruct users to clear their cart)

**Closed by yoavf** 2018-08-02 09:16 UTC
Labels: [Type] Bug
