### ISSUE TITLE
Login & Sign out issues

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#13571] opened 2017-05-02 18:21 UTC
Log in issues in Chrome:

#### Steps to reproduce
1. Starting at URL: wordpress.com, logged out
2. Hit "Log in" in top right
3. 500 error

![](https://cloudup.com/c3O1foZGIyZ+)

Log out issues on Firefox:

#### Steps to reproduce
1. Starting at URL: wordpress.com, logged in
2. Navigate to profile
3. Hit "sign out" under avatar
5. redirect failure
6. refreshing or navigating away and back shows session is persisted (not logged out)

![](https://cloudup.com/c1rWjzNB65x+)

**Comment by designsimply** [comment] 2017-05-02 18:39
I was unable to reproduce the problem where a 500 error appears after clicking "Log In" at https://wordpress.com/  

![screen shot 2017-05-02 at tue may 2 12 36 42 pm](https://cloud.githubusercontent.com/assets/1119271/25633375/199729de-2f34-11e7-84bf-7e2ceba88ff1.png)
<sup>Seen at https://wordpress.com/wp-login.php?redirect_to=https%3A%2F%2Fwordpress.com%2F after going to https://wordpress.com/ and clicking "Log In" at top right. Tested with an incognito window in Chrome 58.0.3029.81 on Mac OS X 10.12.4 on production (unproxied).</sup>

**Comment by designsimply** [comment] 2017-05-02 18:42
I was unable to reproduce the problem where the "Log Out" button on the profile menu resulted in a blank screen using the testing steps provided.

![screen shot 2017-05-02 at tue may 2 12 40 29 pm](https://cloud.githubusercontent.com/assets/1119271/25633567/cc6f8196-2f34-11e7-9d05-dacca5f22d17.png)
<sup>Seen at https://wordpress.com/?apppromo using  after going to https://wordpress.com/me while logged in and clicking the "Log Out" button. Tested with Firefox 53.0 on Mac OS X 10.12.4 on production (unproxied).</sup>

**Comment by designsimply** [comment] 2017-05-02 18:55
Updated to Chrome 58.0.3029.96 on Mac OS X 10.12.4 and tested again. Still unable to reproduce. I'll try getting some additional eyes on this for testing.

**Comment by designsimply** [comment] 2017-05-02 19:02
I found out there was a short outage — should be fixed now. Sorry for the trouble!

**Closed by designsimply** 2017-05-02 19:02 UTC
Labels: Login, OSS Citizen, [Type] Bug
