### ISSUE TITLE
Gutenberg: Reusable block uneditable in post or page

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33000] opened 2019-05-13 22:31 UTC
1) Use the Block Editor with a simple WordPress.com site in either /block-editor, or /wp-admin
2) Insert a reusable block
<img width="355" alt="Screen Shot 2019-05-13 at 3 30 02 PM" src="https://user-images.githubusercontent.com/1270189/57658515-0fab3980-7594-11e9-8e72-5ae1333cc63a.png">
3) Click on the reusable block to gain focus

<img width="909" alt="Screen Shot 2019-05-13 at 3 29 01 PM" src="https://user-images.githubusercontent.com/1270189/57658478-eb4f5d00-7593-11e9-9a6b-44fd2790cb9e.png">

Expected: Edit button is clickable
Actual: Edit button is disabled

**Comment by dmsnell** [comment] 2019-05-17 01:11
Some initial investigation:

The `<ReusableBlockedit />` component [decides if the author can edit](https://github.com/WordPress/gutenberg/blob/39f568faf2e62c57736bb80d7088a996eb067944/packages/block-library/src/block/edit.js#L166) its given reusable block.

```js
canUpdateBlock: !! reusableBlock && ! reusableBlock.isTemporary && !! canUser( 'update', 'blocks', ref )
```

This is used to determine the enabled/disabled state of that button. This also limits our problem domain to whether we thing a reusable block `isTemporary` or if we aren't getting sufficient permission.

In some console debugging I discovered that `isTemporary` and `ref` were fine which led me to investigate the permissions check.

In Core the `wp_block` API endpoint call returns [permissions information in a request header](https://github.com/WordPress/gutenberg/blob/bb8debab915e9fab373e24f9e9dd9469ac27779a/packages/core-data/src/resolvers.js#L179) as `Allow: GET, [PUT], [POST], [DELETE], […]`

<img width="1112" alt="Screen Shot 2019-05-16 at 6 03 46 PM" src="https://user-images.githubusercontent.com/5431237/57896356-2b694680-7805-11e9-9fdc-d37a429b76b3.png">

On WordPress.com / `public-api.wordpress.com` that header is not coming through and thus the permissions information isn't getting set inside of Gutenberg. The editor doesn't consider the absence of the header information as a failure but rather as a positive confirmation that the requisite permissions are missing.

<img width="1266" alt="Screen Shot 2019-05-16 at 6 06 59 PM" src="https://user-images.githubusercontent.com/5431237/57896429-974baf00-7805-11e9-8caa-d4a6c05e71cf.png">

However, we can see that due to the `_envelope` query argument we _are_ getting the `Allow` header but it's coming in as a `headers` property on the message body vs. in the actual HTTP section of the packet.

<img width="497" alt="Screen Shot 2019-05-16 at 6 09 04 PM" src="https://user-images.githubusercontent.com/5431237/57896502-edb8ed80-7805-11e9-9ece-e7d6cf833755.png">

I'm not sure if we should already be able to safely use the `_envelope` query arg and not have it impact the editor but we should **probably make sure that the `_envelope` is handed in the appropriate `apiFetch` middleware** and that it's working as we expect.

**Comment by mmtr** [comment] 2019-05-17 06:53
Nice investigation @dmsnell!

We were already handling enveloped responses for the fetchAll middleware. The problem was caused by our custom apiFetch middleware always parsing the response and returning an object with the body data rather than a fetch-like object with all the info needed, including the headers.

D28355-code should fix that.

**Comment by kwight** [comment] 2019-05-17 17:37
Closed via D28355-code.

**Closed by kwight** 2019-05-17 17:37 UTC
Labels: [Goal] Gutenberg, [Pri] High, [Type] Bug
