### ISSUE TITLE
FoldableCard: expand/collapse causes jump and slide of following content

### ISSUE THREAD

**Issue by mladenplavsic** [Automattic/wp-calypso#14309] opened 2017-05-21 20:12 UTC
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/design/foldable-card
2. Click on the "expand" arrow on first "FoldableCard" item
3. Any HTML content below the block jump and slide during the change

#### What happened
Bottom margin is animated from 16px to 8px, and combined with instant open of ```foldable-card__content``` it makes HTML content below the block to jump and slide

#### Browser / OS version
Chrome / Ubuntu 14.04

#### Screenshot / Video
![screenshot from 2017-05-21 21 41 15](https://cloud.githubusercontent.com/assets/1327535/26286873/4036ea1c-3e6f-11e7-9fa0-a7031a43106a.png) 

Is this what is intended to happen?

**Comment by designsimply** [comment] 2017-05-22 15:07
I tested with Chrome 58.0.3029.110 on Mac OS X 10.12.4 and the card below the first "FoldableCard" item does slide down but I'm not sure I'm seeing the same jumpiness you're describing. Would you mind taking a look at the following video to confirm whether it shows the same behavior that you are seeing? https://cloudup.com/cr_mofuxXBT

**Comment by mladenplavsic** [comment] 2017-05-23 07:07
That's the same thing that I am seeing. When you click on the arrow, content of the card is closed immediately, and the next block is having a bit of animation to change the margin between the two elements. So on expanding, next HTML blocks are jumping down, and sliding a bit up. On collapse, content jumps up, and then slide a bit down.

Is that what design intended to happen?

**Comment by designsimply** [comment] 2017-05-23 16:26
I am not sure! It looks intentional to me, and I've also tagged this issue with the `[Status] Needs Design Review` label to get a quick 2nd opinion.

**Comment by drw158** [comment] 2017-05-23 16:41
Probably not intentional, but also not a bug. Just a quirk as a result of one thing happening instantly and another being transitioned over a period of time. Creates a nice bouncy effect.

I'm not sure there is anything to fix here unless anyone wants to suggest an improvement.

**Comment by designsimply** [comment] 2017-05-24 17:08
@mladenplavsic, I can see that the behavior is functionally sound and has not been reported by others that I know of. I am going to close this issue with a note that we can re-open it if it comes up again. Thank you for taking the time to discuss it!

**Closed by designsimply** 2017-05-24 17:08 UTC
Labels: Components, OSS Citizen, [Type] Question
