### ISSUE TITLE
Vivre: Font choices not being respected.

### ISSUE THREAD

**Issue by arinoch** [Automattic/wp-calypso#71685] opened 2023-01-04 22:13 UTC
### Quick summary

Websites using the Vivre theme display in Times New Roman, regardless the font selected.

### Steps to reproduce

1. Set any site to the Vivre theme.
2. In the site editor, global styles, choose any font. The user who reported this was using Roboto.

### What you expected to happen

Your font choice (Roboto in the user's case) should be reflected on the site.

### What actually happened

In my testing, Times New Roman was the font instead.

### Context

Reported in 36488169-hc, tested by me and other HEs in p1672868164809219-slack-C03TY6J1A. Follow-up in 5838577-zd-woothemes at user's request.

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Vivre

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by dsas** [comment] 2023-01-05 16:55
Duplicate of https://github.com/Automattic/wp-calypso/issues/71641

**Closed as not planned** 2023-01-05 16:55 UTC
Labels: Bug, [Pri] High, [Platform] Simple
