### ISSUE TITLE
[Post Excerpts]: Add support to show font styling used in the post's content

### ISSUE THREAD

**Issue by joweber123** [Automattic/wp-calypso#43893] opened 2020-07-04 08:38 UTC
#### Steps to reproduce

1. Add any font style (Bold, Italics, Underline, etc) to a post.
2. Add the Blog Posts block to a page.

#### What I expected
I expected that font styles would be displayed in the excerpt of the posts in the Blog Posts block

#### What happened instead
Styles are stripped from the excerpt of the post.  

#### Screenshot / Video
![Screen Shot on 2020-07-04 at 17:37:37](https://user-images.githubusercontent.com/24914028/86508689-1393be00-be1d-11ea-888e-2b39a3df4702.png)

**Comment by jp-imagines** [comment] 2022-07-25 15:54
Had a user request this in 36159671-hc.

I confirmed on a test site that this affects the Blog Posts block, Latest Posts block, and the Query Loop block.

**Comment by cuemarie** [comment] 2022-08-11 18:31
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - Yes, reported here: https://github.com/WordPress/gutenberg/issues/43163

📌 FINDINGS/SCREENSHOTS/VIDEO
- Reproducable. Anywhere that displays a `Post Excerpt` rather than the `Full Post` removes font styling.

**Post with Styles:**

![Markup on 2022-08-11 at 11:17:37](https://user-images.githubusercontent.com/27249804/184210765-d50e6672-1bf7-4048-9427-8bb9e1082d56.png)

**Blog Posts Block Result:**

![Markup on 2022-08-11 at 11:16:10](https://user-images.githubusercontent.com/27249804/184210617-901c3dfc-9bea-419c-9431-d2afeb910b76.png)

**Self-Hosted:**

![Markup on 2022-08-11 at 11:28:52](https://user-images.githubusercontent.com/27249804/184213245-921b5999-0755-4106-9423-f150a0fad4a8.png)

📌 ACTIONS
- Added to 'HE Cross-repo Watchlist' project board
- Reported in Gutenberg external repo: [link](https://github.com/WordPress/gutenberg/issues/43163)
- Feature request kept

**Comment by annezazu** [comment] 2024-09-05 22:18
Hey folks! This is working as intended afaik based on how the excerpt has always been defined: https://github.com/WordPress/gutenberg/issues/43163 As a result, I closed out the original Gutenberg report and am closing out this one too.

**Closed by annezazu** 2024-09-05 22:18 UTC
Labels: [Pri] Low, [Type] Feature Request, [Status] Core Fix Needed, User Report, Triaged, [Feature Group] Editor Experience, [Feature] Core Blocks
