### ISSUE TITLE
Posts: deleted post doesn't disappear after being trashed/deleted

### ISSUE THREAD

**Issue by koke** [Automattic/wp-calypso#3886] opened 2016-03-09 09:51 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/posts/kokejb7.wordpress.com
2. Trash a post
3. Switch to trashed posts
4. Permanently delete it
5. Switch back to published posts

#### What I expected

Post should be gone

#### What happened instead

Post is still there

#### Browser / OS version

Safari 9.0.3 on OSX 10.11.3. **Private Window**

#### Screenshot / Video

https://cloudup.com/cLnVRP-hW93

There are a few other variants shown in the video:

- Trash a post, switch to trashed, switch back to published. The post is still there. Trashing it again permanently deletes it. Switching to trashed still shows the already deleted post.
- Trash a post. Switch to trashed, switch back to published. Trashed section disappears for a second. Switch back to trashed. Post is there, but the UI doesn't show restore/delete permanently, instead you can "move to trash" (which deletes)

**Comment by hoverduck** [comment] 2016-04-14 17:20
14Apr16 Bug Scrub

Unable to reproduce with OSX Chrome v49, Safari v9.1, or Safari 8 (via Browserstack).  Closing.  Feel free to re-open if it's still a problem for anyone else.

**Closed by hoverduck** 2016-04-14 17:20 UTC
Labels: Posts, [Type] Bug

**Comment by koke** [comment] 2016-04-15 05:32
Confirmed, seems to work fine now for me as well
