### ISSUE TITLE
Block Editor: Missing Pages Parent Page Dropdown

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/wp-calypso#38894] opened 2020-01-17 09:43 UTC
- I can replicate the issue
- It only happens on the Block Editor 

#### Steps to reproduce
1.  Create/Edit a new page on Block Editor
2.  Go to **Page Attributes**
3. Click **Parent Page** dropdown 

#### What I expected

See and select any Parent Page

#### What happened instead

Not all pages are available

#### Browser / OS version

Safari 13.0.4
Firefox 72.0.1
macOS Catalina 10.15.2

#### Video

https://www.loom.com/share/4ada669334284e60b490ee1367981fba

#### Context / Source

2639823-zd
17958804-hc

**Comment by davipontesblog** [comment] 2020-03-12 19:29
@rosepajaroja is this still happening? I cannot replicate this issue on a test simple site on WordPress.com using the block editor. Could you provide more information such as what theme the site is using, and what pages are showing, and which ones are not? Tha can help pinpoint what the issue is here. I am gonna close it for now until we can get more information and confirmation that this is still happening.

**Closed by davipontesblog** 2020-03-12 19:29 UTC
Labels: Editor, Pages, [Type] Bug
