### ISSUE TITLE
Domain mapping: dissonant messaging about expiry and renewal

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#5416] opened 2016-05-17 16:36 UTC
After renewing domain mapping for trailnose.com, I was shown the following messages:

<img width="965" alt="screen shot 2016-05-16 at 11 32 51" src="https://cloud.githubusercontent.com/assets/17325/15330459/ca53938e-1c11-11e6-9c9d-ad7cda5c93ae.png">

First message: Oh great, it's been renewed! And it'll auto renew next time. Fantastic.
Second message: It expires again in a year. Okay. But it'll be removed from my site? I thought it would auto renew?

#### Possible solutions

* Perhaps we should hide the "Domain mapping will expire in a year..." message unless the expiry is fairly soon (perhaps a month before expiry?)
* Perhaps we should reword the message if auto-renew is enabled, something like:
"Domain mapping will expire in a month and will be auto-renewed."
...or hide the message completely if auto-renewal is enabled?

**Comment by fabianapsimoes** [comment] 2016-05-20 09:11
I see Payment Method is set to None. Did you complete this renewal with credits? If that's the case, because of the lack of payment method, we're not able to switch the purchase to subscribed. That blue notice is only displayed for unsubscribed purchases.

I'll close this as a duplicate of #4554, but feel free to reopen if you have anything to add.

**Closed by fabianapsimoes** 2016-05-20 09:11 UTC
Labels: Domains, Purchases, [Type] Enhancement

**Comment by bluefuton** [comment] 2016-05-20 16:51
Yes, completed with credits, so looks like a dup of #4554. Thanks @fabianapsimoes!
