### ISSUE TITLE
error while npm start

### ISSUE THREAD

**Issue by suiwenfeng** [Automattic/wp-calypso#22787] opened 2018-02-25 08:44 UTC
#### Steps to reproduce
1. npm start

#### What happened instead

```
✓ expecting node: 8.9.4 (Your version: 8.9.4)
✓ expecting npm: 5.6.0 (Your version: 5.6.0)

chunk {zoninator} zoninator.js (zoninator) 332 kB {build} {plugins} {wp-job-manager} [rendered]

ERROR in ./node_modules/_notifications-panel@2.1.5@notifications-panel/src/Notifications.jsx
Module parse failed: Unexpected token (33:19)
You may need an appropriate loader to handle this file type.
| 
| export class Notifications extends PureComponent {
|   static propTypes = {
|     customEnhancer: PropTypes.func,
|     customMiddleware: PropTypes.object,
 @ ./client/notifications/index.jsx 36:0-71
 @ ./client/layout/masterbar/notifications.jsx
 @ ./client/layout/masterbar/logged-in.jsx
 @ ./client/layout/index.jsx
 @ ./client/controller/index.web.js
 @ ./client/boot/project/wordpress-com.js
 @ ./client/boot/app.js
 @ multi webpack-hot-middleware/client ./client/boot/app
webpack: Failed to compile.

Ready! You can load http://calypso.localhost:3000/ now. Have fun!
```

#### Browser / OS version
 
   System Software Overview:

      System Version: macOS 10.13.3 (17D102)
      Kernel Version: Darwin 17.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: rovski.swa’s MacBook Pro
      User Name: rovski.swa (rovski.swa)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2 days 4:55

**Comment by designsimply** [comment] 2018-03-07 01:10
I tested `npm start` just now on macOS 10.13.3 and could not see the error shown in your output above. 

Is it possible for you to try a fresh install and let me know if the problem is still happening for you?

**Comment by designsimply** [comment] 2018-03-13 19:49
Closing this for now because I was unable to reproduce the issue. Please re-open with more information if needed!

**Closed by designsimply** 2018-03-13 19:49 UTC
Labels: Framework, OSS Citizen, [Type] Help Request

**Comment by suiwenfeng** [comment] 2018-03-23 09:24
![image](https://user-images.githubusercontent.com/2735407/37821561-ee5edd44-2ebe-11e8-9736-530b159857ce.png)

which version you are using ？
✓ expecting node: 8.9.4 (Your version: 8.9.4)
✓ expecting npm: 5.6.0 (Your version: 5.6.0)

**Comment by Kastrcn** [comment] 2018-05-11 18:40
me to error
![image](https://user-images.githubusercontent.com/19508899/39940927-7dab94ac-558d-11e8-8d8f-7a8454007cd8.png)
![image](https://user-images.githubusercontent.com/19508899/39940984-afa7c1c4-558d-11e8-9237-df0ae04a5b2e.png)
![image](https://user-images.githubusercontent.com/19508899/39941016-cc2dbb8c-558d-11e8-94de-d28ff308fc13.png)
![image](https://user-images.githubusercontent.com/19508899/39940889-5c3778f4-558d-11e8-930b-e87b451c17b9.png)
