### ISSUE TITLE
Nav unification:  Feedback menu reverts to old menu styles

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/wp-calypso#49146] opened 2021-01-21 19:19 UTC
### Steps to reproduce the behavior

1. Go to site 
2. Click on Feedback link in left nav

#### What I expected to happen
Navigation would remain consistent with new unified nav

#### What actually happened
Nav reverted to old calypso styles

![feedback](https://user-images.githubusercontent.com/3629020/105401021-87e36100-5c8a-11eb-8eb7-5ce33508232e.gif)

**Comment by obenland** [comment] 2021-01-21 19:46
Thanks for that feedback @glendaviesnz! It looks like you're running into Calypsoify there, that should be fixed with the next Jetpack release.

Appending `?calypsoify=0` to the URL or activating Jetpack Beta on your Atomic site and setting it to "Bleeding Edge" should fix that.

**Comment by glendaviesnz** [comment] 2021-01-22 00:54
I still get it with that param on a simple site:

<img width="921" alt="Screen Shot 2021-01-22 at 1 52 53 PM" src="https://user-images.githubusercontent.com/3629020/105430777-2edef180-5cb9-11eb-8c79-67e51f1f64a0.png">

but happy for you to close this if it is a known/fixed issue.

**Comment by cpapazoglou** [comment] 2021-01-22 16:08
It is not calypsoificiation. This should be a problem with the color-scheme not set in calypso. This needs investigation.

**Comment by cpapazoglou** [comment] 2021-01-22 16:09
Possibly related to https://github.com/Automattic/wp-calypso/issues/49173

**Comment by obenland** [comment] 2021-01-22 22:26
Oh yes, my bad. 

Feedback being edited in wp-admin is expected behavior. It's part of the menu structure document linked to from the Project thread: pbAPfg-Ou-p2

**Comment by getdave** [comment] 2021-01-25 14:05
Agreed. I think we can safely close this as it's addressed in other issues. Thanks @glendaviesnz.

**Closed as completed by getdave** 2021-01-25 14:05 UTC
Labels: Bug, [Feature] Calypso & wp-admin Navigation
