### ISSUE TITLE
Editor: Media: Add Via URL does not support YouTube URLs

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/wp-calypso#2135] opened 2016-01-05 22:54 UTC
When you go to "Add Media" and use the "Add Via URL" button,  pasting a video URL results in this error:

> The file could not be uploaded because the file type is not supported.

Here is a GIF showing this in action:

<span style="border:1px solid black;">![add-via-url](https://cloud.githubusercontent.com/assets/3505172/12129534/e4362682-b3c9-11e5-83a4-761dce35f7f8.gif)</span>

In wp-admin, pasting a video URL simply results in that URL being pasted onto it's own line, and auto-embedded.

For instance, you can paste this URL into the "Insert from URL" field in wp-admin:

`https://www.youtube.com/watch?v=MJwOAucWJJg`

This will be the result in the Text/HTML editor:

`[embed]https://www.youtube.com/watch?v=MJwOAucWJJg[/embed]`

I recommend that we fix Calypso's feature to work in the same manner as wp-admin's implementation.

Reported in 2479243-t

**Comment by aduth** [comment] 2016-01-06 13:02
Not a bug because it's true that the media library does not support _uploads_ from YouTube. Question is if and how we should accommodate these _inserting_ workflows. As was pointed out, in wp-admin, there is an additional tab for inserting content from a number of sources (including plain URL, using oEmbed).

At one point, we had talked about better content discoverability features in the media modal (e.g. searching from Dropbox or Getty). We should probably account for oEmbed link insertion when we start iterating on these designs.

/cc @kellychoffman

**Comment by kellychoffman** [comment] 2016-01-07 00:47
Right. For now, you can easily add a youtube link directly in the editor content. 

> At one point, we had talked about better content discoverability features in the media modal (e.g. searching from Dropbox or Getty). We should probably account for oEmbed link insertion when we start iterating on these designs.

Yes. I have yet to start on the designs, but better discoverability is the goal here.

**Comment by rachelmcr** [comment] 2017-12-22 21:42
Closing as Gutenberg will have separate blocks for different kinds of media (including embeds for discoverability).

#bug-scrub #pre-gutenburg-bug-purge

**Closed by rachelmcr** 2017-12-22 21:42 UTC
Labels: Editor, Media, [Type] Enhancement
