### ISSUE TITLE
Duotone image filter not working on Simple Sites or AT sites with Gutenberg active

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#59787] opened 2022-01-05 23:54 UTC
### Quick summary

Duotone image filter appears to not display on the front end on Simple Sites, or when the Gutenberg plugin is active on AT sites. Image appears correctly (duotone) in the editor, but displays in full color on the front end.

### Steps to reproduce

1. Start a new page on a Simple Site, or Atomic site with Gutenberg plugin active
2. Insert an image and make it duotone
3. Publish and view page

### What you expected to happen

The image should appear in duotone (and match editor)

### What actually happened

Image appears in full color

### Context

Discovered as part of #4663406-zen.

I've done further testing to narrow down when it occurs, and also that it seems to effect self-hosted sites with the latest version of Gutenberg.

### Theme-specific issue?

To my testing this effects all themes *except* Block themes. Confirmed so far with:

* All Varia themes
* Seedlet
* TwentyTwentyOne
* TwentyTwenty

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

For Atomic sites - the user can deactivate the Gutenberg plugin and duotone filter will work.

**Comment by jordesign** [comment] 2022-01-05 23:54
Nothing that we will need a core GB issue for this - but I wanted to open a stub for us to track things here.

**Comment by jordesign** [comment] 2022-01-06 00:06
Turns out there is an issue already.....
https://github.com/WordPress/gutenberg/issues/37598

**Comment by zdenys** [comment] 2022-01-06 08:14
It has been reported already some time ago and transferred to Themes repo 🤷‍♂️ https://github.com/Automattic/themes/issues/5259

**Comment by jordesign** [comment] 2022-01-06 19:43
Bringing over the interactions from https://github.com/Automattic/themes/issues/5259 as this is a GB issue instead of theme issue:

* #4634506-zen
* #4634686-zen
* #4644527-zen
* #4634686-zen
* #4636226-zen
* https://wordpress.com/forums/topic/duotone-now-not-working-on-my-site-suddenly/?view=all#post-3773186
* #4652083-zen

**Comment by Robertght** [comment] 2022-01-11 05:25
Another case in #4676859-zen

**Comment by filipanoscampos** [comment] 2022-01-12 14:31
Another case here 4681038-zd-woothemes with the Hever theme.

**Comment by tvolpert** [comment] 2022-01-13 22:53
Another case of this bug here: #4685220-zen with the Stow theme

**Comment by TPilgs** [comment] 2022-01-20 20:33
Another report here: #4705682-zen using the Hever theme.

**Comment by ClassicRKR27** [comment] 2022-01-26 18:44
I've got another report here also with the Hever theme: [33616556-hc](https://hud.happychat.io/chat/33616556)

**Comment by CompChris** [comment] 2022-01-26 19:53
Another report (Twenty Twenty-One) - 31664225-hc

**Comment by ClassicRKR27** [comment] 2022-01-26 19:54
Another one here for Shoreditch: [33004462-hc](https://hud.happychat.io/chat/33004462)

**Comment by the-misha** [comment] 2022-01-26 21:33
Another one, on Shawburn: 12851682-hc

**Comment by rinazrina** [comment] 2022-01-27 09:07
Another case (Twenty Twenty) - 4724100-zd-woothemes

**Comment by cometgrrl** [comment] 2022-01-28 01:14
@jordesign since it looks like this will be fixed in Gutenberg 12.5 and WP 5.9.1, should we move this to the cross-repo watchlist?

**Comment by jordesign** [comment] 2022-01-31 01:16
Thanks @cometgrrl - great point. There doesn't seem to be an open PR or issue to reference - but we can keep an eye for this when 5.9.1 rolls out!

**Comment by samvaidya** [comment] 2022-02-01 00:06
Another case on the Coutoire theme:  #4737838-zen

**Comment by Robertght** [comment] 2022-02-03 07:07
Another case in #4742855-zen

Theme: Hever

**Comment by cometgrrl** [comment] 2022-02-04 22:23
Looks like this should be fixed as[ Gutenberg 12.5.1](https://github.com/WordPress/gutenberg/issues/37598#issuecomment-1024998614) is rolled out to everyone. Right now it's only out for simple sites.

If anyone sees evidence that contradicts this, please ping me!

**Comment by Greatdane** [comment] 2022-02-17 05:12
Closing now this is fixed on core! I cannot reproduce the original issue on WordPress.com

**Comment by marcuswisecaesar** [comment] 2023-08-31 18:47
Reopening this issue as this has cropped up again in this interaction - #6635907-zen

Theme: Byrne 

The Duotone is working as expected on desktop view, but under mobile view in Safari, Chrome, iPhone, or Android, the Duotone is stripped out. 

How it looks on mobile:
![image](https://github.com/Automattic/wp-calypso/assets/36801460/5d76a2c2-4373-4db8-9c4f-1b27ac6954a8)

How it is supposed to look: 
![image](https://github.com/Automattic/wp-calypso/assets/36801460/c61a52f5-1f80-4159-9474-73559f6251b9)

**Comment by cuemarie** [comment] 2023-08-31 19:33
Hey @marcuswisecaesar ! I'm also looking into this here: https://github.com/Automattic/wp-calypso/issues/78442 ~and here: https://github.com/Automattic/wp-calypso/issues/75805 - it's been reported in a few places!~

Going to close this issue again bc of the high number of reports, it can add to the confusion. ~but I'll work on getting an up to date issue with steps to repro, and then share that here.~

Please share your Customer report on #78442 instead - thank you!

**Closed as completed by cuemarie** 2023-08-31 19:33 UTC
Labels: Bug, [Pri] High, Triaged, Customer report [LEGACY], [Interaction #] > 10, [Status] Priority Review Triggered
