### ISSUE TITLE
Lodestar: Image block displayed with no bottom margin

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#69827] opened 2022-11-07 17:25 UTC
### Quick summary

On the Lodestar theme, Image blocks are displayed with no bottom margin. This affects both new blocks as well as existing blocks that were displayed correctly in the past.

### Steps to reproduce

1. Activate Lodestar.
2. Create a post.
3. Add several consecutive Image blocks.
4. Publish the post.

### What you expected to happen

1. To see a gap between consecutive images on the live view.

### What actually happened

No gap between the images.

### Context

5691088-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Seems to be related to a similar issue that affects other themes: https://github.com/Automattic/themes/issues/6197

### Available workarounds?

Yes, easy to implement

### Workaround details

Add this code to Additional CSS:
figure.wp-block-image {
	margin-bottom:10px;
}

**Comment by ariel-maidana** [comment] 2022-11-07 17:28
5691088-zd-woothemes
Please inform the user once this issue is fixed.

**Comment by kavyagokul** [comment] 2022-11-10 12:38
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated 
- Tested on Self-hosted - Replicated 
- Replicable on Core - Yes


📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/themes/issues/6197

**Closed as completed by kavyagokul** 2022-11-10 12:38 UTC
Labels: Bug, [Pri] Low, [Platform] Atomic
