### ISSUE TITLE
Free domain CTA in dashboard sidebar: Unable to dismiss the offer

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#94162] opened 2024-09-04 01:54 UTC
### Quick summary

My blog runs on a WordPress.com paid plan that includes a free domain as part of the plan. However, my site uses a domain that predates my purchase of a WordPress.com plan. As I currently have no need of a domain, I would like to be able to permanently dismiss the CTA to claim the free domain, as it takes up room in the sidebar and feels distracting.

More context: p58i-i4X-p2#comment-64222

### Steps to reproduce

1. Create a site and select a paid plan
2. Add a custom domain that you already own to your site (Hosting > Domains > Add new domain > Use a domain I own)
3. Get your site working with your mapped domain

### What you expected to happen

Once my existing domain has been set up for my site, I expect the "Free domain available" CTA in the left-hand sidebar to no longer be visible _or_ for me to be able to permanently dismiss it. It will still be visible from the https://wordpress.com/domains/manage/ URL in a less visible place should I be looking at domains in the future.

### What actually happened

The CTA is present and it cannot be dismissed:

![image](https://github.com/user-attachments/assets/fde8234d-d23b-4087-ad3e-0da554f20375)

On the domains screen there is still a bigger "Claim your free domain" offer further down the page. I think that one is fine to remain there, but I'd like to be able to permanently dismiss the one at the top left:

![image](https://github.com/user-attachments/assets/70877071-7910-4e0e-894b-92cb16f5e5e1)

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by jartes** [comment] 2024-09-04 14:17
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
It could be great to do the same as we do with domain sales offerings: 

![Markup on 2024-09-04 at 16:15:49](https://github.com/user-attachments/assets/65023206-bab7-4583-9df7-bc9e0b1ae0a5)


📌 ACTIONS
- Triaged
- Lowered priority from `Blocker` to `Normal`

**Comment by hambai** [comment] 2024-10-16 19:24
This one is duplicate of https://github.com/Automattic/wp-calypso/issues/56133

**Closed as completed by hambai** 2024-10-16 19:24 UTC
Labels: Bug, [Pri] Normal, Triaged, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered, [Feature] JITM
