### ISSUE TITLE
Activity Log: WP Admin Editor theme edits aren't recorded

### ISSUE THREAD

**Issue by anaemnesis** [Automattic/wp-calypso#43749] opened 2020-06-29 06:52 UTC
According to Jetpack's Activity Log support page (https://jetpack.com/support/activity-log/), the Activity Log will record:

- **Themes**: installations, edits, deletions, switches, network enable/disable actions

However, we have a user in 3094557-zen who is reporting that theme _edits_ are, in fact, _not_ recorded.

To replicate:

1. Log into WP Admin, and navigate to **Appearance --> Editor**
2. Pick any file from a theme, and make edits to it. I have test with JS, CSS and PHP assets
3. Force a fresh sync of the site's data via Jetpack Debugger
4. Navigate to the Activity Log for the site in question from WordPress.com, via **My Sites --> Tools --> Activity Log**
5. Ensure that no filter, or the correct filter is applied
6. There is no theme edit activity

Expected result, according to the documentation:

Theme edits will show in the Activity Log alongside a backup point

I also tested with edits to theme options via the Customizer, and those aren't showing either. So I'm reporting as a bug for now, but I suspect there's ambiguity in the documentation and 'edit' might not mean edits to theme files.

**Comment by StefMattana** [comment] 2020-07-13 08:16
I [bumped](https://a8c.slack.com/archives/C02DQP0FP/p1594628103005200) @brucea8c ping in Slack again to see if someone can take a look at this of us.

**Comment by mattgawarecki** [comment] 2020-07-13 12:15
I'm checking on this issue today with a couple of teams that work with the Activity Log -- will report back with updates.

**Comment by mattgawarecki** [comment] 2020-07-13 15:40
Early investigation is showing that `jetpack_edited_theme` events aren't being recorded correctly, which would cause the reported behavior. Discussion about who specifically will address the issue is ongoing, but this definitely looks like a back-end issue.

I'm cc'ing @vianasw here, who may be able to provide more info as investigations continue.

**Comment by mzakariya** [comment] 2020-07-21 19:16
Any updates on this @mattgawarecki or @vianasw? Thanks! :)

**Comment by vianasw** [comment] 2020-07-31 20:53
Sorry for the delay. I've found a bug that is preventing the event from reaching the Activity Log, and I've created a patch here:
https://code.a8c.com/D47418

However, that's not all. The UI for the _theme modified_ event seems a bit off (I guess it should be similar to the plugin edited event, see picture below):

<img width="749" alt="theme modified" src="https://user-images.githubusercontent.com/298685/89075894-7bd3b200-d37f-11ea-93cc-cecad47d8478.png">
<img width="1105" alt="theme modified calypso" src="https://user-images.githubusercontent.com/298685/89076237-32379700-d380-11ea-93bf-ee49be5641e8.png">

And it's not triggering a backup but neither is the _plugin modified_ event, so I'm starting to doubt if it should. I'll keep digging, but I guess someone from Voyager should take a look at the UI issue for the _theme modified_ event.

**Comment by anaemnesis** [comment] 2020-08-01 14:59
Pinging @Automattic/jetpack-voyager per the comment above

**Comment by mattgawarecki** [comment] 2020-08-04 12:34
>The UI for the theme modified event seems a bit off (I guess it should be similar to the plugin edited event [...])

I've created a new issue on our end (`1164141197617539-as-1187358993941905`) for Voyager to address this.

**Comment by mattgawarecki** [comment] 2021-03-01 13:31
Apologies for not following up here. This issue was fixed as of Jetpack v8.9, via the PR Automattic/jetpack#16702. @anaemnesis Can we re-test and close if appropriate?

**Comment by cuemarie** [comment] 2023-06-28 23:59
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Atomic - **Could not replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested with customizer updates, and those were tracked as expected in the Activity Log. 

![Markup on 2023-06-28 at 16:58:48](https://github.com/Automattic/wp-calypso/assets/27249804/9d8ec0bb-4c16-43d2-ad95-af7e7347c803)

📌 ACTIONS
- Given that and the latest update from 2+ years ago, closing this as resolved.

**Closed by cuemarie** 2023-06-28 23:59 UTC
Labels: [Type] Bug, Jetpack, Activity Log, User Report
