### ISSUE TITLE
Some Discovery feed item's comment doesn't show sometimes 

### ISSUE THREAD

**Issue by flexpeace** [Automattic/wp-calypso#23096] opened 2018-03-07 19:10 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/discover
2. Attached Image of post
3. Comments shows 64
4. However, https://wordpress.com/read/blogs/53424024/posts/32176#comments shows no comment

#### What I expected
I expected to see the list of comments 

#### What happened instead
No comment showed up 

#### Browser / OS version
Chrome Version 65.0.3325.146 (Official Build) (64-bit)
Mac High Sierra version 10.13.3

#### Screenshot / Video
<img width="910" alt="screen shot 2018-03-07 at 10 03 23 pm" src="https://user-images.githubusercontent.com/5002192/37112601-f51ae230-2253-11e8-8390-4b7ec6c82ead.png">
<img width="1313" alt="screen shot 2018-03-07 at 10 03 45 pm" src="https://user-images.githubusercontent.com/5002192/37112602-f5463b06-2253-11e8-99db-6e9df1f58bf2.png">

**Comment by jancavan** [comment] 2018-03-07 19:15
Thanks for reporting this @flexpeace! This is a duplicate of: https://github.com/Automattic/wp-calypso/issues/16477 so closing this issue.

**Closed by jancavan** 2018-03-07 19:15 UTC
Labels: OSS Citizen, Reader, [Type] Bug
