### ISSUE TITLE
Themes: The theme activation dialog occasionally loses theme author name

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#6074] opened 2016-06-16 00:25 UTC
#### Steps to reproduce
1. Starting at URL: http://wordpress.com
2. Locate a new theme and click "Activate"

#### What I expected

The theme activation dialog should show the theme author

#### What happened instead

Occasionally, and not reproducibly, the theme author is now shown (see screenshots below)

#### Browser / OS version

Chrome/Firefox OSX

#### Screenshot / Video

![theme dialog with no author](https://cloud.githubusercontent.com/assets/128826/16101765/8fa96ba2-33ac-11e6-9438-1803347dd720.png)

##### DOM as it appears

![dom with no author](https://cloud.githubusercontent.com/assets/128826/16101770/9bbde828-33ac-11e6-9eed-bb845e1eaf46.png)

#### Context / Source
 #dogfooding  #manual-testing

**Comment by ockham** [comment] 2016-06-16 13:16
Thanks for reporting! This is a duplicate of #5699, where I've added some notes on the reason and a possible fix.

**Closed by ockham** 2016-06-16 13:16 UTC
Labels: Themes, [Type] Bug
