### ISSUE TITLE
Me: No automatic refresh on logout if account set to not-English

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#16750] opened 2017-07-31 13:56 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Set interface language to a language other than English 
3. Click the Sign Out button
4.

#### What I expected
For the page to refresh, and to be back at the Log In page

#### What happened instead
Nothing. No refresh at all, and it appears that I'm still signed in. I can navigate to other pages in Calypso, even create a post, but if I try to save anything I get a "That method is not allowed" error or a "An active access token must be used" error.

Refreshing the screen takes me back to the Log In screen revealing that I'm actually logged out.

#### Browser / OS version
Replicated in Firefox and Chrome on Mac. The user reporting it uses Internet Explorer 11

I've confirmed with the nl, de, ca and es locales.

#### Screenshot / Video
Console error when trying to log out

![mijn_profiel_ _wordpress_com](https://user-images.githubusercontent.com/11873759/28780887-a6ae890a-7608-11e7-9cee-89e77ded5a8a.png)

#### Context / Source

Reported in 871648-f

**Comment by KokkieH** [comment] 2017-08-01 09:21
Thanks for the fix, @Tug

**Comment by carinapilar** [comment] 2017-08-08 21:02
@Tug, this started happening to me today and we already got 3 Portuguese users with the same issue. This is what we get:

![screen shot 2017-08-08 at 16 30 22](https://user-images.githubusercontent.com/16104522/29094334-61d93f76-7c63-11e7-8e6b-f2fa39e9d712.png)

**Comment by eduardozulian** [comment] 2017-08-08 21:13
Just reported on 564362-zd

**Comment by eduardozulian** [comment] 2017-08-08 21:27
Now on 564267-zd

**Comment by Tug** [comment] 2017-08-08 21:47
@carinapilar Are you sure this issue is related? This screenshot shows an error happening on login, not logout.

**Comment by eduardozulian** [comment] 2017-08-08 22:05
Another here: 626250-zd

It definitely appears to be a login issue, Tug, so I'm trying to gather more info from some of our users since I was not able to replicate the issue yet with my account set up to `pt-br`.

**Comment by catkit** [comment] 2017-08-08 22:37
@Tug I have experienced this error @carinapilar has shared today as well when trying to SSP. I think it has to do with not being able to properly logout? I came across the error described by @KokkieH also but I didn't relate both issues. I'll pay attention if the login error happens after the logout error. It seems maybe somehow the system thinks I'm still logged to an active session and therefore won't let me log back in.

**Comment by eduardozulian** [comment] 2017-08-08 22:38
I was able to reproduce the log out issue on one of accounts using `pt-br` as the interface language. Steps:

1. Starting at URL: https://wordpress.com/me/account
2. Make sure your language is set to Brazilian Portuguese
3. Click the Sign Out / Sair button

Here's the result in the console:

<img width="1680" alt="7nexpu" src="https://user-images.githubusercontent.com/1136160/29097609-220b2392-7c71-11e7-9324-0dffb850f2a4.png">

**Comment by Tug** [comment] 2017-08-08 22:43
I see this redirection is annoying
Created https://github.com/Automattic/wp-calypso/pull/17029 to fix it.
Feel free to test it on https://calypso.live/me?branch=fix/logout

**Comment by Tug** [comment] 2017-08-08 22:50
cc @pento 
This is reproducible from https://wordpress.com/log-in/pt-br as well! We might need to revert https://github.com/Automattic/wp-calypso/pull/16901 after all.

**Comment by catkit** [comment] 2017-08-09 00:12
Yet another: 626077-zd (just to track and answer when solved.

**Comment by pento** [comment] 2017-08-09 01:01
This is a server side issue, currently being worked on in D6760.

**Comment by pento** [comment] 2017-08-09 02:19
D6760 has landed, so changes to Calypso are no longer necessary.

**Closed by pento** 2017-08-09 02:19 UTC
Labels: i18n, Login, Me, [Type] Bug
