### ISSUE TITLE
Install wpcom themes in Jetpack multisites

### ISSUE THREAD

**Issue by eliorivero** [Automattic/wp-calypso#17566] opened 2017-08-28 16:19 UTC
Today we went through a Jetpack site with @beaulebens that wasn't showing Premium themes. The site was a multisite. Right now, we're not installing themes, neither free nor premium, in multisite installations.

This was disabled [back in this PR](https://github.com/Automattic/wp-calypso/pull/11499), which prevents uploads and theme listing in Calypso. It was a temporary measure until [this PR](https://github.com/Automattic/jetpack/pull/6201) by @roccotripaldi was merged in Jetpack.

At the time this restriction was introduced we were only installing free themes so it was kind of harmless, now that premium themes are part of the Professional plan offer, users should be able to use the premium themes in a multisite.

@bb explained that one of the reasons is an issue with management rights on multi network multi sites installations connected through Jetpack and that Calypso UI needs to catch up with WP Admin in terms of management capabilities in multisites

**Comment by jeherve** [comment] 2018-03-30 10:45
Closing as duplicate of #12660

**Closed by jeherve** 2018-03-30 10:45 UTC
Labels: Themes, [Type] Enhancement
