### ISSUE TITLE
Private Atomic sites don't allow access to "Sharing Buttons" settings

### ISSUE THREAD

**Issue by jackiejade** [Automattic/wp-calypso#43988] opened 2020-07-08 13:35 UTC
(Edit - Feb 9 2021 - This now only seems to be an issue on atomic + private sites:  https://github.com/Automattic/wp-calypso/issues/43988#issuecomment-776242471 )
#### Steps to reproduce

1. Create a new site, or set an existing site to Coming Soon
2. Go to Tools > Marketing
3. Sharing Buttons tab is no where to be found

![Missing sharing tab](https://d.pr/i/fajq7v+)

#### What I expected

The ability to choose Sharing Buttons and decide which to display on the site.

#### What happened instead

Sharing Buttons option is missing

#### Context / Source

This has been reported a few times by users and also recently as part of Team Griswold Feedback project.

**Comment by mmtr** [comment] 2020-08-17 09:48
Seems this is no longer an issue, I see the Sharing Buttons tab on both private and coming soon issues (note that the tab is only visible to site admins).

Feel free to re-open if the issue is still reproducible.

**Comment by donalirl** [comment] 2020-10-10 23:22
Re-opening this issue as the sharing buttons settings (My Site → Tools → Marketing → Sharing Buttons) do not appear on sites that are in Coming Soon mode:
<img width="601" alt="sharinbuttongs" src="https://user-images.githubusercontent.com/30727666/95666920-8e057400-0baa-11eb-93fe-0af6002a1277.PNG">

This is confusing because the Like button can appear on posts before launching, but there's no way to access the settings to turn it off. 

It would make more sense to have the setting be permanently accessible, regardless of Coming Soon mode. This presents a more consistent experience for site owners pre-launch and post-launch. If they do not see a setting for sharing buttons under Tools → Marketing before launching the site, it is not intuitive to then check that same spot for it post-launch.

Seen during #24762420-hc

**Comment by donalirl** [comment] 2020-11-08 04:59
Another case affected by this #25467596-hc

**Comment by donalirl** [comment] 2020-11-21 16:02
Another case in #25797026-hc

**Comment by eduardozulian** [comment] 2020-11-23 15:46
Another report in 25834444-hc

**Comment by ramonjd** [comment] 2020-12-22 23:47
This is strange. I can't reproduce, even on private sites (I only checked Simple could it be Atomic-only?). 

> It would make more sense to have the setting be permanently accessible, regardless of Coming Soon mode.

The only (maybe) relevant condition is that we check if a user has [permission to manage options before showing the sharing button](https://github.com/Automattic/wp-calypso/blob/0b37e3b7b2031ed21aefd3cb626a02d9cced4660/client/my-sites/marketing/main.jsx#L156).

It's not linked to Coming Soon in any way that I can find.

There might be some strange behaviour around private sites and user permission, but without a reliable path to testing, it's hard to know the reason.

I'd probably remove the references to coming soon now to avoid a red herring.

**Comment by p-jackson** [comment] 2021-02-03 06:35
I also can't reproduce and can't quite figure out what's going wrong. The other thing I wondered about was are these Jetpack sites? I'm guessing those users don't end up in happy chat though, so probably not.

If I _do_ test with a Jetpack site (without enabling sharing in the Jetpack plugin settings) I do get the behaviour exactly like the screenshot in the description. There's no marketing link in the Calypso sidebar for Jetpack sites though, I have to navigate to the url directly.

The reproduce steps explicitly say "create a new site" though, so I'm really at a loss 😕

**Comment by Addison-Stavlo** [comment] 2021-02-09 21:03
I can **kind of** repro - but it only seems to be on atomic, and only with "private" mode (not "coming soon").

1.  I have a new simple site that I enabled Business plan on, activated a plugin to initiate atomic transfer.
2. If I load calypso while the site is in "private" mode, there is no "Sharing Buttons" tab in Tools->Marketing
3. If I then change the privacy setting to anything else (including "Coming Soon"), "Sharing Buttons" appears.
4. Changing the privacy setting back to "private" again, "Sharing Buttons" is now still present in Tools->Marketing.
5. Reloading calypso again with the site in private mode, "Sharing Buttons" is missing.
6. When calypso loads with any privacy setting other than "private", it works as expected (and switching to private works as expected).

Definitely a bit funky 🤔 

(Edit - with v2 of "Coming Soon" mode being based on the public option the above makes sense, so this now strictly seems like a private + atomic issue - will update issue title).

**Comment by JoshuaGoode** [comment] 2021-02-15 23:25
To clarify this only appears on Atomic sites and only when the older Coming Soon v1 or Private is enabled.

**Resolving issues**
If you encounter this on an Atomic site using Coming Soon mode, this means they are using v1 and they can switch to v2 by toggling to Private or Public and then back to Coming Soon.  More on Coming Soon v2, how to check the version in use, and switching is at p7DVsv-9Uo-p2

---

 _**Noting that we don't default to Private on Atomic any longer and we use Coming Soon v2 instead.**_ This means that users experiencing this have either intentionally activated Private or are still using Coming Soon v1. To access these modules, the user will need to switch to Public or Coming Soon v2.

More on this behavior, and a little about why it is this way, is detailed internally on PCYsg-py7-p2 .  Atomic Ambassadors also have this documented at P9HQHe-yS-p2


**Recap**
Private mode, and Coming Soon v1, intentionally disable multiple Jetpack modules -- including `sharedaddy`.

This is done via `wpcomsh` and the list of all modules deactivated are available in private-site.php, starting on line 31. 

> 	'publicize',
	'sharedaddy',
	'json-api',
	'enhanced-distribution',
	'google-analytics',
	'photon',
	'photon-cdn',
	'sitemaps',
	'verification-tools',
	'videopress',
	'wordads',
	

Since this is intentional behavior, I'm not sure if this issue needs to be open unless we want to change that behavior.

**Comment by JoshuaGoode** [comment] 2021-02-15 23:35
With my last comment in mind, I suppose we could leave this open as an enhancement request since it's currently intentional behavior.  Or, mark as `[Closed] By Design`,  cc @Addison-Stavlo

**Comment by Addison-Stavlo** [comment] 2021-02-16 20:25
Hi @JoshuaGoode, thanks for checking in on this!

> Since this is intentional behavior, I'm not sure if this issue needs to be open unless we want to change that behavior.

Id be happy to close if its intentional behavior, however the inconsistency makes it seem like it is not intentional:
* Simple Private sites = always has the "Sharing Buttons" option.
* Atomic Private sites = does not have the "Sharing Buttons" option when calypso is initially loaded in the 'private' setting. (but appears/persists if we switch to 'private' in calypso)

So somewhere there seems to be inconsistent behavior between simple and atomic.  Or is it intentional that in this circumstance atomic and simple site behavior diverges?

If we want the simple/atomic experience to be the same here, we should figure out how to move forward.  But if you still see this inconsistency as intentional, I think its fair to close now.

**Comment by Addison-Stavlo** [comment] 2021-02-16 20:34
I see what you mean about intentionally disabling on atomic.  Generally I often hear "there **should** be no difference between simple and atomic experiences", which makes me wonder if we should be updating simple sites to not show this in private mode either?  Or if having this option in simple+private enables a benefit worth the divergence in experience between the two platforms. 🤔

**Comment by simison** [comment] 2021-02-18 18:03
Can we confirm if share settings on Atomic are accessible for regular private sites, regardless of coming soon mode?

If they are not, I think we should change that.

Otherwise, if this is just about coming soon v1, I think it's safe to close. cc @ramonjd

**Comment by JoshuaGoode** [comment] 2021-02-18 19:14
> Can we confirm if share settings on Atomic are accessible for regular private sites

The Sharedaddy Jetpack module is required for that and is intentionally disabled on WoA Private sites via `wpcomsh`.

A full list of modules disabled here: https://github.com/Automattic/wp-calypso/issues/43988#issuecomment-779491630

Not sure why but it was decided to do that at some point to make the site truly private when WoA private was first developed. 

It's important to note that new Atomic sites are not private-by-default any longer so new sites would have to manually change the site to private after launching it to encounter this issue.   @simison 

> Otherwise, if this is just about coming soon v1,

Private and Coming Soon v1 rely on the same `private-site.php` in `wpcomsh` so this is an issue lingering for Private.

**Comment by ramonjd** [comment] 2021-02-18 22:58
> Otherwise, if this is just about coming soon v1, I think it's safe to close. 

Thanks for your input, everyone. I'll close by design for now. If it becomes a point of user frustration we can revisit.

**Closed by ramonjd** 2021-02-18 22:58 UTC
Labels: Atomic, Sharing, Triaged, [Pri] Normal, [Type] Enhancement
