### ISSUE TITLE
Hero block displays removed text on preview

### ISSUE THREAD

**Issue by poojashetty18** [Automattic/wp-calypso#54506] opened 2021-07-13 12:54 UTC
### Steps to reproduce the behavior

1. Open a page or post editor
2. Insert a new Hero block
3. Add some text to the paragraph block
4. Update the page 
5. Now remove the paragraph block from the Hero block and preview the page.

You will still see the removed text in the preview but not on the front end or page editor.

Note: The preview link should be the one with the preview ID like `?preview_id=1046&preview_nonce=fa438eea3e&preview=true`

You can right click on the Preview option if you do not see the preview ID URL when you try to preview it.

#### What I expected to happen

The preview page also should not display the text as the front end and editor page

#### What actually happened

The removed text was still visible

#### Does this happen on simple or atomic sites or both?
Simple sites

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

I could recreate it intermittently but user was able to consistently recreate it

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Video from my test site:

https://user-images.githubusercontent.com/44837596/125454822-def3bfb6-04e3-445f-82a7-c1c1ccdf32d4.mp4

Reported on 6439541-hc
Followed up: 4135665-zen

Removing the blank heading block within the hero block as well worked for the user

**Comment by kosiew** [comment] 2021-07-14 06:44
Thanks @poojashetty18  for reporting this.

I could not reproduce this either.
Closing for now, but please reopen if you have more information on how to reproduce it.

**Closed as completed by kosiew** 2021-07-14 06:44 UTC
Labels: Bug
