### ISSUE TITLE
Themes: Deprecated/retired theme showing up

### ISSUE THREAD

**Issue by ehti** [Automattic/wp-calypso#4751] opened 2016-04-14 15:10 UTC
A WordPress.com user contacted us in 346657-chat. They had issues trying to activate "Dusk to Dawn" theme - it was a new account so not sure why they were being shown this theme.

It shows up in their _/design_ - but can't be activated and the page gets 'stuck' when you click activate.

Able to reproduce this on two new test accounts, 5 months and 1 day old.
#### Steps to reproduce
1. Create a new account
2. Visit /design
2. Search for _dawn_

#### Browser / OS version
Chrome, Windows 10, latest.

#### Screenshot / Video
![image](https://cloud.githubusercontent.com/assets/6505293/14532435/7d5db6b4-027a-11e6-86b7-d936bd7ac957.png)

**Comment by lancewillett** [comment] 2016-04-14 17:09
Confirmed: retired themes show up at `/design` on a brand new account.

Dusk to Dawn, Ever After, and a few others.

Testing with https://wordpress.com/design/lancetest556.wordpress.com?s=dusk — new signup, test user and blog.

Interesting to note API calls seem to return differently whether calling the theme search from Calypso:

https://public-api.wordpress.com/rest/v1.2/sites/110014164/themes?http_envelope=1&search=dusk&tier=all&page=1&number=20

![screen shot 2016-04-14 at 10 07 51](https://cloud.githubusercontent.com/assets/66797/14536749/d8f07af4-0228-11e6-9488-29e1a91230d0.png)

Or when using WordPress.com dev console to call the API, logged in as this user at https://developer.wordpress.com/docs/api/console/

![screen shot 2016-04-14 at 10 09 02](https://cloud.githubusercontent.com/assets/66797/14536766/ef8bccaa-0228-11e6-9662-80787573ff6a.png)

Could the Calypso call be missing a blog ID for context somehow?

**Comment by lancewillett** [comment] 2016-04-15 16:32
Also: I think we should hide retired themes *completely* in `/design` for *all* users — not by user ID or age or anything else. This collection should be the best, not everything from early days before rigorous standards.

If an author really, really wants to use a retired theme — and has access — they can get to it via wp-admin/themes.php.

**Comment by seear** [comment] 2016-04-22 09:45
>  I think we should hide retired themes completely in /design for all users

This allow us to remove some tricky code which has been a source of a few similar bugs, so I'm all for it :)

**Comment by seear** [comment] 2016-04-22 10:19
@lancewillett: how about purchased, retired premium themes? Think it's ok to go through wp-admin for those as well?

**Comment by seear** [comment] 2016-04-22 12:01
I've found the problem, which is a chicken-and-egg thing with the retirement procedure and the elasticsearch index. If we decide to not show free retired themes at all it will become moot.

> Interesting to note API calls seem to return differently whether calling the theme search from Calypso

Incidentally, calling this API without a `sites` param will never show any retired themes, logged-in or not, since retirement goes by site id and not user id.

**Comment by seear** [comment] 2016-04-22 14:40
I've re-indexed the Elasticsearch index that backs the API, which has fixed the issue for now:
![screen shot 2016-04-22 at 15 37 16](https://cloud.githubusercontent.com/assets/7767559/14744816/4f4f0544-08a0-11e6-801e-8ffc7a185c72.png)

And I'll await the outcome of the discussion going on elsewhere regarding showing retired themes to implement the proper fix.

**Comment by lancewillett** [comment] 2016-04-22 16:50
> @lancewillett: how about purchased, retired premium themes? Think it's ok to go through wp-admin for those as well?

Yes, in my opinion it's very edge case and wp-admin works well for that.

**Comment by seear** [comment] 2016-04-27 14:00
Removal of retired themes from API: D1676

**Comment by lancewillett** [comment] 2016-04-27 17:29
Tested the API changes. 👍

**Comment by lancewillett** [comment] 2016-04-27 17:35
API console is also empty for `dawn` search now:

![screen shot 2016-04-27 at 10 34 58](https://cloud.githubusercontent.com/assets/66797/14861846/c6c946ea-0c63-11e6-85f8-be27ccb39485.png)

**Comment by seear** [comment] 2016-04-28 11:06
Fixed in wpcom-135057.

Thanks @lancewillett :)

**Closed by seear** 2016-04-28 11:06 UTC
Labels: Themes, [Type] Bug

**Comment by lancewillett** [comment] 2016-04-28 15:46
Thanks, Steve. :)

Confirmed again in Calypso, not seeing anything for `dusk` in `/design` for my sites. Yay.
