### ISSUE TITLE
Pexels suggested search term returns potentially problematic images

### ISSUE THREAD

**Issue by sajmes** [Automattic/wp-calypso#53014] opened 2021-05-19 15:55 UTC
When adding images from Pexels into an image block, the Pexels search opens with various search terms such as 'clouds', 'mountains', etc. autosuggested to get the user started with adding an image. 

One of the search terms I have had suggested to me when starting the process adding an image from Pexels is 'patterns'. That suggested search returns results which are nearly all cannabis related (something like 30 of the first 35 results).

It seems that this could well be problematic for some users to encounter as a suggested result when trying to add an image to their site from Pexels.

The search term 'pattern' rather than 'patterns' returns nearly the same content but I don't believe that has been autosuggested to me. 

#### Steps to reproduce

1. Add a gallery/image block in the block editor. 
2. Select image source as Pexels.
3. Pexels opens with a (randomised?) suggested search term.When adding images from Pexels into an image block, the block autosuggests various search terms. 

![](https://d.pr/i/6RzqEN+)

**Comment by devNigel** [comment] 2021-07-19 07:19
Another report for the keyword `tyranny` 

![image](https://user-images.githubusercontent.com/33957570/126118486-bab91cd8-4b45-4033-b427-4ae94c2e4d3b.png)

User report: 28026552-hc

**Comment by johngodley** [comment] 2021-07-19 08:01
I've just tried now and the 'pattern' and 'patterns' keywords no longer return cannabis pictures, and 'tyranny' returns no results.

**Comment by johngodley** [comment] 2021-07-19 08:35
Just to confirm:

![image](https://user-images.githubusercontent.com/1277682/126129075-94a06d20-b9df-4508-86e3-090aced436be.png)

![image](https://user-images.githubusercontent.com/1277682/126129195-dffbc2f9-dfac-4d69-bbcd-d2fab2bdb0b7.png)

![image](https://user-images.githubusercontent.com/1277682/126129246-aadc42a0-3dd2-4479-b79d-3f5989717895.png)

![image](https://user-images.githubusercontent.com/1277682/126129278-944b93d1-9213-4052-b3cb-ada180a9af75.png)

We return the same as what is returned on pexels.com.

As we don't control the images returned then any keywords that does return results of a questionable nature can be reported directly to Pexels through their contact form, mentioning that this is part of the Automattic integration:

https://pixels.com/contactus.html?tab=contactus

**Comment by msilbers** [comment] 2021-07-20 14:28
This is happening for me too, and occurs for any set of random text. If I search for vtjliecsdfjvs or aekjefjfsd it returns the results shown in the second comment on this issue. It kinda seems like it's showing those images for anything it doesn't have results for.

This happens on any of my WordPress.com sites, Simple or Atomic, and on P2

The images are not what Pexels.com reports:

<img width="990" alt="Screen Shot 2021-07-20 at 10 27 29 AM" src="https://user-images.githubusercontent.com/31680407/126341722-17875da3-3975-45bb-982a-87a18240c7de.png">

<img width="1291" alt="Screen Shot 2021-07-20 at 10 27 21 AM" src="https://user-images.githubusercontent.com/31680407/126341744-8a3f3aa9-076a-41f1-a4d8-4a7fc8839d78.png">

**Comment by devNigel** [comment] 2021-07-20 14:40
These are my new findings:

1. I am able to reproduce on all sites in 2 different WPCOM accounts when using the browser but not on the third WPCOM account
2. I am not able to reproduce the issue on any of the accounts when searching using the WordPress app.

**Comment by johngodley** [comment] 2021-07-21 08:26
I've tracked the problem down to a NSFW filter that was only applied to `en` locales (and not `en-gb` as was mine) that was had some unfortunate side-effects. The problem should now be solved and I'll close this issue.

**Closed as completed by johngodley** 2021-07-21 08:26 UTC
Labels: Enhancement
