### ISSUE TITLE
Gutenberg: Reusable block: Missing in Preview and Published post

### ISSUE THREAD

**Issue by Stojdza** [Automattic/wp-calypso#27734] opened 2018-10-10 15:43 UTC
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/gutenberg/
2. Create Paragraph block
3. Select More options -> Add to Reusable Blocks -> Save
4. Select Preview or Publish and view post

#### What I expected
To see Paragraph block. 

#### What happened instead
Paragraph block is missing. 

#### Browser / OS version
Chrome 69 / OS X

#### Screenshot / Video
<img width="801" alt="screen shot 2018-10-10 at 17 39 47" src="https://user-images.githubusercontent.com/7116222/46748438-dd5ef400-ccb3-11e8-8028-b044d406bb5d.png">
<img width="687" alt="screen shot 2018-10-10 at 17 39 56" src="https://user-images.githubusercontent.com/7116222/46748458-e64fc580-ccb3-11e8-8a27-f68be8ea27b2.png">

**Comment by vindl** [comment] 2018-10-23 21:58
I couldn't reproduce this with reusable paragraph block containing some text and an inline image. Was this tested on WP.com simple site?

**Comment by vindl** [comment] 2018-10-25 00:44
Closing as obsolete for now, please reopen if the issue is still present.

**Closed by vindl** 2018-10-25 00:44 UTC
Labels: [Goal] Gutenberg
