### ISSUE TITLE
WordPress.com/go action bar text looks strange

### ISSUE THREAD

**Issue by renata-franco** [Automattic/wp-calypso#66400] opened 2022-08-09 11:48 UTC
### Quick summary

When going to WordPress.com/go the action bar to follow the site on the bottom right seems to be having some CSS issues. 
The "follow" text is not centered and does not look as usual. 

It looks like this: 

![imagen](https://user-images.githubusercontent.com/81378719/183639201-17c5a11a-076c-43e0-9ffc-7ba75e8f1fe4.png)

### Steps to reproduce

1. Visit WordPress.com/go

### What you expected to happen

It should look like this:

<img width="1781" alt="imagen" src="https://user-images.githubusercontent.com/81378719/183639726-2e67d768-726b-49f7-b00e-4b706296fa20.png">

### What actually happened

The "follow" text looks strange. 

### Context

This was an HC report here: pd4QKa-Az-p2
And, I asked for a CSS fix here: p1660044475934889-slack-C03TY6J1A

I've added the following CSS: 

```
div#actionbar span {
  font-family: inherit;
  color: inherit;
  font-size: inherit;
  line-height: inherit;
}
```

That worked and the site looks proper now. However, I wanted to report in case this is happening somewhere else. 

### Theme-specific issue?

WordPress.com GO

### Available workarounds?

Yes, easy to implement

### Workaround details

CSS: 

```
div#actionbar span {
  font-family: inherit;
  color: inherit;
  font-size: inherit;
  line-height: inherit;
}
```

**Comment by Joshgrygiel** [comment] 2022-08-09 16:19
📌 SCRUBBING
- Tested on P2 - N/a 
- Tested on Simple - N/a
- Tested on AT - N/a
- Tested on Self-hosted - N/a
- Replicable on Core - N/a

📌 FINDINGS/SCREENSHOTS/VIDEO
![Annotation on 2022-08-09 at 11-15-29](https://user-images.githubusercontent.com/88345647/183704171-6e12cbc1-72c6-47f3-8e9a-212f05f5397f.png)
- After testing the https://wordpress.com/go page on Chrome, FireFox and Safari, I was unable to reproduce the issue of the "Follow" button appearing without CSS applied

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)


📌 Message to Author
- Hey @renata-franco! I was unable to reproduce this issue on my end during testing, is there specific step or workflow to reproduce that I may have missed?

**Closed as completed by Joshgrygiel** 2022-08-09 16:19 UTC
Labels: Bug, [Pri] Low, [Feature] Reader, Triaged

**Comment by renata-franco** [comment] 2022-08-09 17:03
> Hey @renata-franco! I was unable to reproduce this issue on my end during testing, is there specific step or workflow to reproduce that I may have missed?

Nope. This was only on that page https://wordpress.com/go. I haven't seen this anywhere else. But I was asked to report this so here I am. The CSS fixed it.
