### ISSUE TITLE
Accessibility: Look at not disabling zoom

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#2003] opened 2015-12-29 01:24 UTC
This issue has been split out from: https://github.com/Automattic/wp-calypso/issues/697

Disabling zoom with `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">` is considered bad practice for accessibility. Mainly because many times, users with poor vision need to pinch and zoom to see items and read things.

**Comment by rachelmcr** [comment] 2018-01-02 21:21
Confirmed this is still an issue.

#bug-scrub #pre-gutenburg-bug-purge

**Comment by davidakennedy** [comment] 2019-04-15 19:11
I'd like to reopen this, and pitch it as a good "Fix the Flows" issue.

> By setting maximum-scale=1.0, you are disabling the functionality to use pinch zoom on certain mobile devices, forcing people to view your page a certain way.
From: https://a11yproject.com/posts/never-use-maximum-scale/

Having this in place across Calypso means users can't pinch and zoom when needed. Removing it would give our users more freedom to use our interfaces however they need to. It's also an easy fix. 😄 

I discovered this doing some quick accessibility testing in Calypso when aXe.

**Comment by sixhours** [comment] 2019-04-27 16:16
Is there any backstory on why we disabled zoom in the first place? If no, let's just do this.

**Comment by scruffian** [comment] 2019-04-29 12:10
I dug into the history from before Calypso was open source - this was just added as part of the initial page with no obvious reasoning.

**Comment by alaczek** [comment] 2019-06-04 23:48
I think this issue is good to close, since the PR was merged a while back.

**Closed by alaczek** 2019-06-04 23:48 UTC
Labels: Accessibility, FixTheFlows, [Type] Bug
