### ISSUE TITLE
Post editor shows error when media library shown in HTML mode before site has loaded

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-calypso#15781] opened 2017-07-03 11:11 UTC
In HTML mode if you try and show the media library while the post editor is loading a JS error is thrown because the site data isn't valid.

Some warnings are also shown, probably related to the missing data.

The editor continues to work once the site data has loaded.

#### Steps to reproduce
1. Edit a post and switch to HTML mode
2. Open devtools console
3. Hard refresh the page and click the media button while the page status (top right corner) says 'loading' - you may need to slow your connection down
4. Note these warnings:
<img width="881" alt="warnings" src="https://user-images.githubusercontent.com/1277682/27790441-5438ecfa-5fe8-11e7-95da-c2f3d04420f4.png">
5. Note this error:
<img width="805" alt="error" src="https://user-images.githubusercontent.com/1277682/27790471-6e7daac4-5fe8-11e7-82ee-215f715c41c4.png">

**Comment by rachelmcr** [comment] 2018-01-23 18:03
I tested with the steps in the original report in Chrome 63 with the DevTools network throttling set to Slow 3G. I couldn't reproduce the console warnings.

I'll optimistically close this as resolved, but if it's still an issue please reopen.

**Closed by rachelmcr** 2018-01-23 18:03 UTC
Labels: Editor, [Type] Bug
