### ISSUE TITLE
Gutenboarding: if .com domain is available, recommend it

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#40974] opened 2020-04-09 14:15 UTC
In [Gutenboarding](https://wpcalypso.wordpress.com/gutenboarding) domain suggestions dropdown we should aim to suggest common domains when they are available, over uncommon TLDs, e.g. `.com` over `.vodka` 😛 

![image](https://user-images.githubusercontent.com/87168/78904741-a8d51f80-7a85-11ea-8d81-33a1a882883a.png)

**Comment by klimeryk** [comment] 2020-04-09 14:19
This might be a slippery slope, TBH. We worked hard with our domain suggestions provider to make sure that the suggestions are ordered in terms of relevancy, etc. If this is not the case then there might be something wrong with the endpoint - or the particular query triggered a case that's simply not handled properly (it does happen with all the possible combinations). We should not however try to workaround that by re-ordering the results based on one report, IMHO.

I'm _guessing_ that the `potato` part of `mesopotatoia` got associated with `vodka`. But .com should have been higher anyway. If that's indeed the order that was returned by the suggestions provider, then it's worth raising it as an issue with them instead.

**Comment by xpurichan** [comment] 2021-02-08 22:25
Per the above comment I'll close this request as the product is functioning "by design".

**Closed by xpurichan** 2021-02-08 22:25 UTC
Labels: Domains, [Closed] By design, [Goal] New Onboarding, [Type] Enhancement
