### ISSUE TITLE
Customer home: Install mobile app task not dismissed correctly

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/wp-calypso#44894] opened 2020-08-12 22:55 UTC
#### Steps to reproduce

1. Start a new site with a user hat has not installed the mobile app
2. Choose the option to 'Skip for now' for the mobile app setup
<img width="660" alt="Screen Shot 2020-08-13 at 10 37 47 AM" src="https://user-images.githubusercontent.com/3629020/90075743-3a191300-dd52-11ea-985a-f3badf2098eb.png">
3. Reload customer home and check the contents of the /checklist endpoint call, and the `mobile_app_installed` task still shows `isCompleted` as false
<img width="1027" alt="Screen Shot 2020-08-13 at 10 29 13 AM" src="https://user-images.githubusercontent.com/3629020/90075880-92501500-dd52-11ea-9106-6e9f75ea2afb.png">

This was causing the site setup indicator to still show as incomplete, as in above screenshot, even though all the site setup tasks were dismissed from the customer home.

The incorrect display of the site setup percentage indicator has been fixed in #44847, but it would be good to verify:

If  'skip for now' should in fact flag the mobile app installation as completed, and if so work out why this isn't happening
or 
Is that task supposed to stay as incomplete so messaging can be displayed to users at a later stage if it is initially skipped, in which case nothing further needs to be done and this issue can be closed

**Comment by p-jackson** [comment] 2021-05-05 23:59
The setup progress bar currently not appearing due to nav unification #52630

That issue should eventually be fixed, but it should be possible to work on this issue using the `?disable-nav-unification` query param.

**Comment by p-jackson** [comment] 2021-05-10 03:52
I think I understand the issue now. The probably with the progress bar has been addressed in #44847, but this issue is a follow up to check whether the "skip for now" button is really supposed to be treated the same as completing the task.

> If 'skip for now' should in fact flag the mobile app installation as completed, and if so work out why this isn't happening
or
Is that task supposed to stay as incomplete so messaging can be displayed to users at a later stage if it is initially skipped, in which case nothing further needs to be done and this issue can be closed

Everything appears to be working exactly as designed. The backend makes no distinction about _how_ a task was marked completed, it's either completed or it's not. So it appears to be very much by design that skipping sets the `isCompleted` flag to `true`.
Same story on the client-side, the skip code is intentionally marking the task as "complete".
https://github.com/Automattic/wp-calypso/blob/d833d3c3f4d3a3029f0c90404f8fe4c6ef12ef49/client/my-sites/customer-home/cards/notices/celebrate-site-launch/index.jsx#L33
https://github.com/Automattic/wp-calypso/blob/d833d3c3f4d3a3029f0c90404f8fe4c6ef12ef49/client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx#L79
https://github.com/Automattic/wp-calypso/blob/d833d3c3f4d3a3029f0c90404f8fe4c6ef12ef49/client/state/checklist/reducer.js#L37

I think the "Skip for now" langauge is still correct. I think it could reassure the user that clicking "Skip" won't lock them out of _ever_ using the app.

> Is that task supposed to stay as incomplete so messaging can be displayed to users at a later stage

I think we could always remind the user of the app, but it'd make sense to use a flag other than the site setup checklist. For instance, has the user ever signed in to the mobile app, has their site been connected to a mobile app. So IMO I think the setup checklist has all the features we need.

Does that seem reasonable @glendaviesnz @mmtr?

**Comment by autumnfjeld** [comment] 2021-05-10 05:30
Given that WP app is not really a step needed for site launch, is there a more appropriate location for this suggestion?  To me, as a new user, it is not related to the other items in the list.  It could even be a friction point: I'm a new user, focused on my desktop site creation progress and this odd item at the bottom of the list causes me to try to understand why I need the app, do I need to verify something in the app?

**Closed** 2021-05-10 22:07 UTC
Labels: Checklist, Customer Home, My Home Pod, [Pri] Low, [Type] Bug

**Comment by p-jackson** [comment] 2021-05-10 22:09
> do I need to verify something in the app

No nothing needs to be verified in the app. I think you're right we may want to move this out of the checklist.

In terms of the API though, I believe what we have now is fit for purpose.
