### ISSUE TITLE
New checkout: Phone number field jumps off screen after focusing on it in iPhone Safari

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#38966] opened 2020-01-21 10:57 UTC
#### Steps to reproduce
1. On a phone, starting at URL: https://horizon.wordpress.com/plans
2. Select a site with a free plan.
3. Select the Personal plan.
4. On the checkout screen, select a payment method.
5. In the billing information section, tap into the "Phone number" field.

#### What I expected

I expected to enter my phone number.

#### What happened instead

The phone number field disappeared. When I dismissed the keyboard, I noticed that it had jumped down on the screen.

#### Browser / OS version

Safari / iPhone XS 13.3

#### Screenshot / Video (Optional)

<img src="https://user-images.githubusercontent.com/8658164/72799217-a0b2d400-3c3c-11ea-9e17-c9e17a5adbba.png" width="50%">

@sirbrillig, @nbloomf, @fditrapani

**Comment by fditrapani** [comment] 2020-03-10 19:00
Thanks for reporting this. It's been a while since it was reported and we've made a number of updates — including replacing this form all together. I am unable to reproduce the error so I will close this issue for now.

**Closed by fditrapani** 2020-03-10 19:00 UTC
Labels: Checkout, [Type] Bug
