### ISSUE TITLE
Domain Search Results: searching for _ addresses or special symbols shows wrong error message

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#19502] opened 2017-11-06 03:02 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/domains/add/ (or https://wordpress.com/start and navigate to domains step)
2. Seach for a term with an underscore
3. Search for a special symbol by itself

#### What I expected

An informative error message

#### What happened instead

`Sorry, there was a problem processing your request. Please try again in a few minutes.
`

#### Browser / OS version

Chrome macOS

#### Screenshot / Video

<img width="760" alt="underscore" src="https://user-images.githubusercontent.com/128826/32423525-94c63da0-c2f2-11e7-95e1-8295c83480cc.png">

<img width="776" alt="special character" src="https://user-images.githubusercontent.com/128826/32423529-9cb8b2cc-c2f2-11e7-9a38-40cf5bee5596.png">

#### Context / Source
 #reallife #dogfooding

**Comment by klimeryk** [comment] 2017-11-06 11:41
Thanks for the report and related PR - I'll review it ASAP. This seems to be a duplicate of https://github.com/Automattic/wp-calypso/issues/16763, though :)

**Closed** 2017-11-08 20:57 UTC
Labels: Domains
