### ISSUE TITLE
Block Widget Error with Blank Screen or 500 errors on Simple Sites

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#58085] opened 2021-11-15 23:16 UTC
### Quick summary

When going to Appearance > Widgets on a Simple Site the Block Widget Editor does not appear. 2 different presentations so far:

* 500 error (on user site - https://eata.wordpress.com/wp-admin/widgets.php - no longer showing as classic widgets are enabled)
* Blank screen

<img width="1763" alt="Screen Shot 2021-11-16 at 10 11 50 am" src="https://user-images.githubusercontent.com/1842363/141867394-46261369-dbd4-4535-bdf1-9722d621edd1.png">

Console error on line 126 of widgets.php:

```
Uncaught SyntaxError: Unexpected identifier
```

### Steps to reproduce

1. Start at any Simple Site
2. Go to Appearance > Widgets

### What you expected to happen

To see the block widget editor

### What actually happened

A blank page/frame within WP Admin

### Context

User report: #32752960-hc

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Workaround details

For most users - editing widgets in the Customizer will still work. If not - we can temporarily switch users to the Classic widget editor in Blog RC. But once resolved we should switch them back.

**Comment by jeyip** [comment] 2021-11-15 23:23
There also appears to be a bug with the beta site editor. The site editor shows a blank screen when users navigate to Appearance > Editor. The root cause of our problems might be related.

**Comment by adelineyaw** [comment] 2021-11-15 23:34
User reported via 136342-hc
Follow up: 4458246-zen

**Comment by arinoch** [comment] 2021-11-16 00:35
32475976-hc, followup in 4458311-zd-woothemes.

**Comment by vindl** [comment] 2021-11-16 00:53
This seems to be caused by r235089. We'll look into reverting it until a proper fix can be found by the team that introduced the change.

**Comment by creativecoder** [comment] 2021-11-16 03:25
This should be resolved by D70135-code and no longer affecting sites in production.

**Comment by kraftbj** [comment] 2021-11-16 03:27
Reverted via r235097-wpcom

**Closed as completed by kraftbj** 2021-11-16 03:27 UTC
Labels: Bug, [Pri] High

**Comment by jordesign** [comment] 2021-11-16 09:26
Looks like all users/interactions have been replied too now (thanks @adelineyaw)
