### ISSUE TITLE
Reader: Sharing feature is not working on some Atomic sites

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#45607] opened 2020-09-14 05:03 UTC
There have been some reports from users that they unable to share posts from Reader. Upon clicking the 'Share' button, the link redirected to empty editor.

Unfortunately, not *all* AT sites have this issues. However, the common thread among the issues is the editor is redirecting to `wp-admin` instead of `block-editor`

#### Steps to reproduce

1. Starting at URL on Reader: https://wordpress.com/read
2. Select a post from the Reader list (not your site), then click the share icon to open sharing options for that post
3. Select a site on your account from the list. Try to choose an AT site (a WordPress.com website with customized plugins/themes installed)
4. The screen will redirect to editor so user can enter additional texts on the post.

#### What I expected
For the editor to open the reblogged/shared posts.

#### What happened instead
Post will load blank instead of showing the content of the post being reblogged.

#### Additional findings

I have ensured that:
- Classic Editor plugin is **inactive**
- Preferred editor is set to **Gutenberg** on User RC
- Deactivate or reactivate Gutenberg plugin is not affecting anything

1. With the problematic site (the editor opened blank/empty page), I found the URL always displays as `https://DOMAINNAME.COM/wp-admin/post-new.php?block-editor=1&frame-nonce=...`
2. While the correct/expected URL should be `https://wordpress.com/block-editor/post/DOMAINNAME.COM...`
3. At some point, I tried to clear editor preference from User RC. At first, it *looks* working (displaying `block-editor...` instead of `wp-admin...`) but it displays an error "DOMAINNAME.COM refused to connect" *then* rerouted to this: `https://DOMAINNAME.COM/wp-admin/post-new.php?calypsoify=1&block-editor=1&frame-nonce...`
4. I also find that for some reason, the pages and posts on the user’s Calypso is always pointing to /wp-admin link path

#### Context / Source
#user-report 

The issue is user-report and can be found here: p9F6qB-5TQ-p2

Feel free to ping me if you need more information about this. Thank you.

**Comment by kwight** [comment] 2020-09-16 21:25
This has something to do with failing Gutenframe checks, and then being instead redirected to WP Admin (the redirect fails to carry the post content with it). The checks for which Gutenframe will fail (PCYsg-lwV-p2) are:

* The site’s Jetpack plugin must be v7.3 or later. This does not apply to simple sites or Atomic sites, all of which meet this requirement.
* The site to be iframed must have an SSL certificate (https). This does not apply to simple sites or Atomic sites, all of which meet this requirement.
* The user must be opted in to the block editor.
* The site must not have the Classic Editor plugin active.
* The site must not have any problematic plugins active.

@retnonindya Since the first two are invalid, and you've checked 3 and 4, it is likely a https://github.com/Automattic/wp-calypso/pull/32915/files#diff-c5eeae718548baa022e9a4c821efc8b8R228 (which you can verify using the MC tools (PCYsg-lOu-p2).

This should still be expected to work, though. It looks like there are `title`, `text`, and `url` query params for the shared post that go missing. Doing a quick test of manually adding them didn't work though, so there's still another piece missing beyond that.

**Comment by retnonindya** [comment] 2020-09-17 04:02
Hi @kwight! Thanks for checking into this.

I checked your links (massive thank you!) and I noticed the user has WPBakery plugin active and it's on "Denied" list, so I deactivated the plugin and tried again. Still, no luck.

We even got the same report here: p9F6qB-5TQ-p2#comment-33171 -- and on that site, all plugins on the site is on "Accepted" list. When I deactivated Classic Editor plugin, the issue persists. 

I'm sorry I can't find further findings on this :( Do you have any insights on this, or maybe you know other folks that I can ping about this? Thank you in advance.

**Comment by kwight** [comment] 2020-09-17 21:03
> all plugins on the site is on "Accepted" list. When I deactivated Classic Editor plugin, the issue persists.

Hm, then I have no explanation 🙃

> Do you have any insights on this, or maybe you know other folks that I can ping about this?

Not at the moment, no – we'll need to try to fit it in for deeper digging.

**Comment by eoinsav** [comment] 2020-09-19 01:20
I had a user saying that they couldn't Reblog a Post to their Atomic site: #24241116-hc

When they click the `Reblog` button on another WordPress.com site, their Simple Sites appear in the list but not their Atomic site.

I'm not sure if this is expected behavior, but this bug report seemed to be for the same thing.

**Comment by katiebethbrown** [comment] 2020-09-19 23:40
Another report in 24259683-hc.

They have the Classic Editor plugin active. When I deactivate it and use the block editor the share works just fine.

**Comment by kwight** [comment] 2020-09-21 17:33
> So is it expected behavior that the share function just fails silently and loads a blank classic editor screen when the Classic Editor plugin is active? That seems... Less than optimal.

Expected at this point, yes – and very not optimal. Basically, our Gutenframe fallback is unaware of features like Sharing, so the support would need to be added (to carry through the shared content for populating the new post).

**Comment by kwight** [comment] 2020-09-21 17:39
> When they click the Reblog button on another WordPress.com site, their Simple Sites appear in the list but not their Atomic site.

@eoinsav You're right, confirmed that myself; I have a feeling it may have been intentional (as in, support hasn't been added yet similar to this issue). Can you create a separate issue though please, since reblogging is not possible from the Reader (which this issue is focussed on)? Thanks!

**Comment by joweber123** [comment] 2020-09-23 03:52
Another report here #3304942-zen  On my end, when testing, if the Classic Editor is not enabled this is working normally on an Atomic site.

**Comment by kwight** [comment] 2020-09-23 15:02
> if the Classic Editor is not enabled this is working normally on an Atomic site

If the the Atomic site has no other factors that force a redirect to WP Admin, then yes, Gutenframe will apply (`wordpress.com/block-editor/`), and Sharing will work as expected.

**Comment by sourourn** [comment] 2020-10-18 21:02
Another report here: #24966793-hc  
Follow up ticket: #3418103-zen

User reported that it's happening on both of their atomic sites: https://moneyclipblog.com/ and https://hintenanstellen.de/

I deactivated the classic editor plugin on both sites and set the block editor as the preferred editor on their user RC, however it's still not working and the share button (from the Reader) keeps loading a blank page on both sites.

**Comment by scosgro** [comment] 2020-10-20 23:29
User has come back repeatedly asking for a solution on this one: 25028665-hc.

It's important to them, and they're not happy.

**Comment by retrofox** [comment] 2020-10-27 19:20
moneyclipblog.com is a paticular case.

![image](https://user-images.githubusercontent.com/77539/97351205-320c4200-1870-11eb-943a-70a7f812da77.png)

For some reason it gets :this: error and the iFrame redirect to wp-admin, losing the ability to populate the title and description of the post to share.

**Comment by fashuvo** [comment] 2020-11-18 02:53
User came back asking for an update #25713789-hc

**Comment by kwight** [comment] 2020-11-18 19:27
This is unlikely to be prioritized any time soon: pbAPfg-15y-p2

**Comment by nagpai** [comment] 2020-11-20 05:02
User asking for update #25759305-hc

**Comment by hacchism** [comment] 2020-12-12 06:22
The same user came back asking for update although they ghosted in the middle: #26283193-hc

**Comment by iamgabrielma** [comment] 2020-12-12 13:08
@kwight The customer is back asking for updates and I see this was moved to the Prioritized Backlog, is something that has come back to our radar to be fixed soon? Or should we set expectations that will not work for a while?

**Comment by kwight** [comment] 2020-12-14 21:17
@iamgabrielma No, there are no plans currently for Manage to address it soon. It's in the prioritized backlog just for hopeful visibility (although even those on janitor rotation are focused on higher priority projects, and only addressing urgent, fatal janitor issues).

**Comment by eoinsav** [comment] 2020-12-16 00:12
Same user is back again: #26368941-hc

**Comment by JoshuaGoode** [comment] 2020-12-23 17:26
> Same user is back again: #26368941-hc

User returned on 26516930-hc

**Comment by katiebethbrown** [comment] 2021-01-04 00:55
Same user from previous reports returned again on 1/3 in 26732309-hc. This feature is important to them and they are understandably frustrated that it isn't being resolved.

I reiterated that we are aware, but that all fixes are prioritized and there are other things that are ahead of this one, so that they need to be patient. I attempted to set expectations appropriately and be clear that this is unlikely to be resolved soon.

I also offered to follow things and contact them with any updates or progress, so that they don't need to contact us repeatedly to check on status. If/when things change on this issue I will let them know.

**Comment by Gilmoursa** [comment] 2021-01-07 21:16
another issue to report at: #23872072-hc

**Comment by jartes** [comment] 2021-01-18 15:40
Another report here: 23658957-hc. The AT site doesn't have the Classic Editor plugin enabled and when trying to share from the Reader, they're redirected to `wp-admin/post-new.php?post_type=post&calypsoify=1`

**Comment by desnum** [comment] 2021-01-18 15:42
Another report: hc-23658957

**Comment by metabreakr** [comment] 2021-01-18 22:14
User is back, again: 27099040-hc

**Comment by katiebethbrown** [comment] 2021-02-05 01:30
Another report (different user) - 26626130-hc

**Comment by cathymcbride** [comment] 2021-02-25 19:22
I repro consistently with the classic editor activated, but it looks like deactivating doesn't fix it for everyone.

**Comment by blackjackkent** [comment] 2021-03-09 21:31
Picking this up as part of Serenity's deep dive this sprint into some outstanding issues. I was able to reproduce it on the atomic site on my account so hopefully I'll be able to nail down something concrete this week.

There's been a lot of discussion on this topic so a quick summary of where we seem to be at at this point -
* This is the expected behavior if the user has the "Classic Editor" plugin enabled, but it is still manifesting in scenarios where that is not the case, which is the problem.
* Initial theory was that this would be occurring because of a problematic plugin installed on the site manifesting the issue. However, deactivating said plugins doesn't seem to consistently resolve the issue.
* It looks as if the content to display in Gutenberg may get lost at a point where an iframe X-Frame-Options error takes place - possibly something to do with trying to pull up a login prompt, based on the error message? (see https://github.com/Automattic/wp-calypso/issues/45607#issuecomment-717479345) Although I'm not sure why it would be pulling up a login prompt if the user is trying to share from a logged-in Calypso screen.

Further updates to follow as I delve deeper into this.

**Comment by scosgro** [comment] 2021-03-11 01:56
User in 28211610-hc came back again asking for an update. They're a repeat requester on this thread, and still aren't happy. Great timing, so appreciate you looking in, @blackjackkent!

**Comment by blackjackkent** [comment] 2021-03-11 16:06
Continuing to work on this today. The current struggle is getting it to happen consistently; it was reproducing on my Atomic site on my account and then stopped, so I'm trying to figure out why. (If anyone has an account/site where it is happening consistently that I can try and make use of, please let me know.)

**Comment by blackjackkent** [comment] 2021-03-11 22:33
I have now been able to reproduce this issue consistently on one atomic site but not another, making use of the exact same share URL except for the blog ID (thanks @scosgro for info on a reproducible blog). I'm currently trying to go through discrepancies between the two to see what might be the problem- some heretofore unidentified issue with a plugin seems most likely to me, so I'm going to start there.

**Comment by kwight** [comment] 2021-03-11 22:59
@blackjackkent I can turn this on and off reliably; sites using Gutenframe (`wordpress.com/post/`) work, while those that don't (`domain.com/wp-admin/post`) do not work. You should be able to create a new WoA site, share successfully, then install a denied plugin (like Elementor), and get the empty editor on the next share attempt. As mentioned up [here](https://github.com/Automattic/wp-calypso/issues/45607#issuecomment-693674052), fixing it would likely involve ensuring the query params with the post data (`title`, `text`, `url`) get passed along in the redirect to WP Admin for sites not able to use Gutenframe.

**Comment by kwight** [comment] 2021-03-12 16:55
We've confirmed that we are getting the correct parameters passed in the WP Admin redirect, it's just that there's no support for the feature yet in WP Admin Atomic (since the feature works in Calypso/Gutenframe regardless of Atomic or not, the current support is likely in Calypso itself).

This will likely require a `wpcomsh` patch that can inject the content into the post via the `wp_insert_post` hook, based on the parameters (somewhat similar to the [Copy Post Jetpack module](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/copy-post.php#L33)).

**Comment by kwight** [comment] 2021-03-17 21:48
This will be (mostly) fixed with 636-gh-Automattic/wpcomsh, but will leave a sizing bug with the embeds. We'll track that separately in https://github.com/Automattic/wp-calypso/issues/51154, so this issue can be closed with the `wpcomsh` merge.

**Comment by mreishus** [comment] 2021-03-19 14:37
We had to revert the changes in 636-gh-Automattic/wpcomsh, because it was breaking contact forms on Atomic. Main issue: https://github.com/Automattic/wp-calypso/issues/51213 Possible related issue: https://github.com/Automattic/wp-calypso/issues/51211

**Closed** 2021-03-25 19:18 UTC
Labels: Editor, Reader, Support, [Pri] Normal, [Type] Bug
