### ISSUE TITLE
[Templates] Page using Custom Template previews with default template on Atomic sites

### ISSUE THREAD

**Issue by ricklabsdotn8** [Automattic/wp-calypso#81770] opened 2023-09-15 12:47 UTC
### Quick summary

Loading a custom template to a page does not load the appropriate preview.

### Steps to reproduce

Create a custom page/post template
1. Create a custom page/post template under Appearance → Editor → Templates
2. Click on Add Template (plus button)
3. Select `Custom Template`
4. Style the Custom Template accordingly

Apply the page/post template
1. Create a post/page
2. On the page/post settings, change the template to the custom template

### What you expected to happen

The page/post should be updated to preview the custom template

### What actually happened

Nothing happens, and the template can only be previewed on the frontend. Reloading the page does not help.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Logs or notes

6832681-zen

Current workaround

**Comment by cuemarie** [comment] 2023-09-18 21:28
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO
Quick triaged on Simple for now, and I am able to replicate.  Previewing doesn't show the custom template, but publish/update does apply the correct template.


https://github.com/Automattic/wp-calypso/assets/27249804/35d5d933-defc-49c5-9043-5fab33d210f6

📌 ACTIONS
- Lowering priority to Normal
- Moving to In Triage for now - will return and test outside of Dotcom and Atomic as well.

**Comment by cuemarie** [comment] 2023-09-28 01:18
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – **Replicated** 
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
I can replicate this only on an Atomic site within WordPress.com.

**Atomic**

https://github.com/Automattic/wp-calypso/assets/27249804/19237d49-9e1f-4918-bab2-3f2a08f5970c

**Simple**

https://github.com/Automattic/wp-calypso/assets/27249804/91673548-023e-4a45-946e-1a3a60c01ca3

**Self-Hosted**
tested with GB 16.6.0 and 16.7.0 - both work as expected.

https://github.com/Automattic/wp-calypso/assets/27249804/beb84408-baf7-474c-8e16-1b6563b98f9b

📌 ACTIONS
- Triage complete

**Comment by annezazu** [comment] 2024-09-03 18:31
Noting that this matches this issue in Gutenberg: https://github.com/WordPress/gutenberg/issues/28208

**Comment by davemart-in** [comment] 2024-10-15 18:48
Closing this out as a duplicate of https://github.com/WordPress/gutenberg/issues/28208

**Closed as completed by davemart-in** 2024-10-15 18:48 UTC
Labels: Bug, [Pri] Normal, [Status] Core Fix Needed, Triaged, [Feature] Full Site Editor, Customer report [LEGACY], [Platform] Atomic, [Product] WordPress.com, [Feature Group] Editor Experience
