### ISSUE TITLE
Images on the Gallery block and Tiled Gallery block are frozen on the Android devices, Chrome (latest version) and MS Edge

### ISSUE THREAD

**Issue by AnjanaV93** [Automattic/wp-calypso#85063] opened 2023-12-11 05:29 UTC
### Quick summary

Images on the Gallery and Tiled Gallery blocks are frozen on Android devices, Chrome (latest version), and MS Edge. If you click on a single image, the x button to close the image and return to the post doesn't work. 

However, it works fine on Safari and Mac OS devices and the previous Chrome versions. 

### Steps to reproduce

1. Open page/post editor.
2. Add images using Gallery or Tile Gallery block.
3. Publish the page/post.
4. Visit the page using Android devices, MS Edge, or Chrome (latest version).
5. Click on one of the images on the Gallery block and then try to go back by clicking x button, you will see the frozen screen. 

### What you expected to happen

To go back to the Gallery and access the other images.

### What actually happened

The close (x) option won't work. 

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

The affected browsers are latest version of Chrome and MS Edge.

**Comment by ClassicRKR27** [comment] 2023-12-11 16:04
Another report here: 7435686-zd-a8c

I did some testing on one of my own sites and found that this is also affecting the gallery when using the Classic block, so it's affecting all galleries at this time.

User would like to be notified when this is resolved, please.

**Comment by i11za** [comment] 2023-12-12 13:22
Here's the interaction from the original report 7431162-zd-a8c
They came back to check for updates here: 7440378-zd-a8c 
User would like an update when resolved, please.

**Comment by Joshgrygiel** [comment] 2023-12-12 18:08
Another report: 7441820-zd-a8c

**Comment by paxblueribbon** [comment] 2023-12-12 20:15
Customer asking for followup in 7442519-zd-a8c

**Comment by OmarFPG** [comment] 2023-12-12 23:27
Another report, the customer is asking for a follow up as well. 7430958-zen

**Comment by Aurorum** [comment] 2023-12-13 08:48
7440528-zen - in the meantime, the Esc button still works to exit the gallery

**Comment by katiebethbrown** [comment] 2023-12-13 17:12
I'm running into this in Arc (Chromium under the hood) as well.

I'm seeing a `pointer-events: none` being added to the carousel overlay at an element level when it's opened. That seems to be what's blocking the click events:

![image](https://github.com/Automattic/wp-calypso/assets/42279181/30a87574-d590-487f-9f04-b053260606f3)

I also noticed that in Arc, I'm able to click on underlying buttons, like the search button in the primary nav, which shouldn't be clickable when the carousel is open:

<img width="300px" src="https://github.com/Automattic/wp-calypso/assets/42279181/d8b03b1f-3f03-461c-923f-67d653159903">

**Comment by supernovia** [comment] 2023-12-13 20:09
We have multiple reports in this forum thread:
https://wordpress.com/forums/topic/image-carousel-next-prev-close-buttons-not-working-in-brave-or-edge/

**Comment by retnonindya** [comment] 2023-12-14 06:48
**Tiled Gallery Block:**

📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on P2 (optional) – Replicated
- Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
The Tiled Gallery Block is displayed as usual on the post, but when clicked, the carousel is unresponsive. Not only the X button to close the carousel but also the other elements.

I tested in several scenarios:

**Simple site, Carousel Off:**
The image on Tiled Gallery Block is unresponsive/unclickable -- expected.

**Atomic site, Carousel Off:**
The image on Tiled Gallery Block is unresponsive/unclickable -- expected.

**Simple site, Carousel On, Link to None:**
Carousel appears and unresponsive.

**Atomic site, Carousel On, Link to None:**
Carousel appears and unresponsive.

**Atomic site, Carousel On, Link to None, Gutenberg Off:**
Carousel appears and unresponsive.

**Simple site, Carousel On, Link to Media File:**
Carousel appears and unresponsive.

**Atomic site, Carousel On, Link to Media File:**
Carousel appears and unresponsive.

---

**Gallery Block:**

📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
The Gallery Block is displayed as usual on the post, but when clicked, the carousel is unresponsive. Not only the X button to close the carousel but also the other elements.

I tested in several scenarios:

**Simple site, Carousel Off:**
The image on the Gallery Block is unresponsive/unclickable -- expected.

**Atomic site, Carousel Off:**
The image on the Gallery Block is unresponsive/unclickable -- expected.

**Simple site, Carousel On, Link to None:**
Carousel appears and unresponsive.

**Atomic site, Carousel On, Link to None:**
Carousel appears and unresponsive.

**Atomic site, Carousel On, Link to None, Gutenberg Off:**
Carousel appears and unresponsive.

**Simple site, Carousel On, Link to Media File:**
Carousel appears and unresponsive.

**Atomic site, Carousel On, Link to Media File:**
Carousel appears and unresponsive.

---

I also tested (Tiled) Gallery inside Classic Block, and:
- Atomic: The carousel is not responding.
- Classic: The carousel responds _on the first time_. When the carousel is closed and reopened, the carousel stopped responding.

📌 ACTIONS
- Triaged and escalated/assigned to Jetpack

**Comment by OmarFPG** [comment] 2023-12-14 14:47
Another report here: 7428054-zen. The user is checking in on this report and expecting a solution soon. The customer also mentioned that file names of other photos are appearing behind the photo when moving the cursor over it, and the photo information button is not working.

**Comment by OmarFPG** [comment] 2023-12-14 18:18
7431162-zen is complaining about no updates and still not working.

**Comment by jenhooks** [comment] 2023-12-14 19:54
I think this is what this Jetpack user is reporting, also: 7430592-zen

**Comment by druesome** [comment] 2023-12-15 09:58
7457021-zen

**Comment by jeherve** [comment] 2023-12-15 12:09
Let's continue the conversation in the issue in https://github.com/Automattic/jetpack/issues/34657

**Closed as completed by jeherve** 2023-12-15 12:09 UTC
Labels: Bug, [Pri] High, Triaged, Customer report [LEGACY], [Status] Priority Review Triggered
