### ISSUE TITLE
Login: English log-in page shows link "Also available in English" which redirects to same page with same message

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#15699] opened 2017-06-30 01:21 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/log-in with language set to English
2. See "Also available in English"
3. Click English
4. URL changes to https://wordpress.com/log-in/en - message still shown

#### What I expected

If I am visiting in English I wouldn't expect to see the message "Also available in English"

#### What happened instead

Message shown and clicking English link doesn't change it

#### Browser / OS version

Chrome, Safari and Firefox on macOS 10.12.5

#### Screenshot / Video

![screen shot 2017-06-30 at 11 18 27 am](https://user-images.githubusercontent.com/128826/27717095-39fa4686-5d86-11e7-9c5a-167c6ca2b522.png)

**Comment by fabianapsimoes** [comment] 2017-06-30 09:54
Duplicate of https://github.com/Automattic/wp-calypso/issues/14965

**Closed by fabianapsimoes** 2017-06-30 09:54 UTC
Labels: Login, [Type] Bug
