### ISSUE TITLE
Email Stats: "Email Opens" stats exceed number of recipients

### ISSUE THREAD

**Issue by ezebecke** [Automattic/wp-calypso#78713] opened 2023-06-27 22:27 UTC
### Quick summary

This was reported on 6472930-zd-woothemes and could not be replicated on my test sites

Site: [redacted] _please find site in internal ticket link above._

Stats under "Latest Emails" > "Email Opens" seem odd. "Total opens" and "Open rate" seem broken.

Examples: ![u1fzP8.png](https://github.com/Automattic/wp-calypso/assets/24919469/1a3e3c64-ae4b-44e3-8748-12092c0519c4) from https://wordpress.com/stats/email/opens/day/14659/SITE_ADDRESS

![TtvhAl.png](https://github.com/Automattic/wp-calypso/assets/24919469/553e0843-3a2c-4ea7-aea3-a2ac221cf174) from https://wordpress.com/stats/email/opens/day/14657/SITE_ADDRESS

### Steps to reproduce

1. SU and go into "Stats"
2. Under "Emails" > "Latest Emails" click on any last post email.
3. Check stats under "Email Opens".

### What you expected to happen

"Total opens" number should be equal to or less than "Recipients".

### What actually happened

I might be missing something, but it I'm confused as to why Not sure why "total opens" is higher than "Recipients".

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment] 2023-06-28 00:18
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic - Could not replicate

📌 FINDINGS/NOTES 
- Tried to replicate this issue by opening up the post from the same subscriber to one of my sites multiple times, including cache clearing and multiple devices, and forwarding the post to another reader.  So far, I've not seen the Open rate increase above 25% (my 1 recipient), but will keep an eye on this.

User Specific Case: 
- Confirmed the presence of the Open rate over 100% on the user site, but this strikes me as something that would be by design - if any user opened the content from their email more than once, I don't see why we would not track that.

📌 ACTIONS
- Requested team feedback

📌 Message to Team
- @Automattic/apex is it expected for the `Total opens` and `Open rate` numbers to be able to exceed the number of recipients?  In other words, is the user's site above working as expected, or is that behavior unexpected and in need of some troubleshooting?  Thanks for weighing in!

**Comment by cuemarie** [comment] 2023-06-28 21:50
Asked in team channel: p1687989002269089-slack-C02TCEHP3HA

**Comment by cuemarie** [comment] 2023-06-28 23:13
Looks like this is indeed by design! 

> Yes, we are tracking all the open events, so it's possible that Total opens exceeds the number of recipients. 

📌 ACTIONS
- Closing as by design

📌 Message to Author
- @ezebecke FYI if you'd like to let the user know this update.

**Closed as not planned by cuemarie** 2023-06-28 23:13 UTC
Labels: Bug, [Pri] Low, [Platform] Atomic

**Comment by ezebecke** [comment] 2023-06-28 23:20
Oh, that makes sense now! Thanks @cuemarie, thanks for the fast triage! Will let the user know.
