### ISSUE TITLE
Editor: Portfolio Shortcode does not filter project types using Shortcode Block 

### ISSUE THREAD

**Issue by openfist** [Automattic/wp-calypso#45535] opened 2020-09-10 03:42 UTC
#### Steps to reproduce

1. Starting at URL: elcastleberry.wordpress.com
2. using portfolio shortcode [portfolio display_types=true display_tags=false include_type=client-blog columns=3 order=DESC] in shortcode block does not filter project types properly
3. Went to Classic Editor in wp-admin and entered [portfolio display_types=true display_tags=false include_type=Feature columns=3 order=DESC] in the body
4. This works

#### What I expected

- Expected [portfolio display_types=true display_tags=false include_type=Feature columns=3 order=DESC] to as normal in Shortcode editor

#### What happened instead

- shortcode did not filter project types as expected

#### Screenshot / Video

[Screen Shot 2020-09-09 at 8.48.33 AM.pdf](https://github.com/Automattic/wp-calypso/files/5199066/Screen.Shot.2020-09-09.at.8.48.33.AM.pdf)

#### Context / Source

#manual-testing, #user-report

**Comment by openfist** [comment] 2020-09-10 03:44
(SITE/SUBSCRIPTION/ACCOUNT) - emmacastleberry.com

(WHAT DOES THE CUST WANT) - customer wants to show portfolio in page Client Blog using portfolio shortcode

(WHAT I DID) - asked customer to try shortcode i modified

https://woothemes.zendesk.com/agent/tickets/3288176

**Comment by cathymcbride** [comment] 2020-09-10 20:02
@openfist Is this something you can reproduce on a test site? It's not clear to me what's not working here, and I am not able to reproduce myself.

**Comment by openfist** [comment] 2020-09-15 12:49
@cathymcbride 

Hi,

I tried replicating it on a dummy site but i also cannot get the result i encountered.

However if you go to the Client Blog page and open the editor, you will notice the shortcode is bordered by <p>

<p>[portfolio display_types=true display_tags=false include_type=client-blog columns=3 order=DESC]</p>

I wonder if this is significant. The rest of the other shortcodes work. Only client-blog has the glitch.

![Screen Shot 2020-09-15 at 20 47 46](https://user-images.githubusercontent.com/11617249/93212224-e6587a00-f794-11ea-870c-bb4e9b92f830.png)


Hopw this helps

**Comment by cathymcbride** [comment] 2020-09-15 15:56
We're not able to replicate, and the customer is good to go, so I'm going to close this bug. If someone runs into this again, please feel free to re-open and we'll triage from there.

**Closed by cathymcbride** 2020-09-15 15:56 UTC
Labels: Editor, Shortcodes
