### ISSUE TITLE
Editor: Adding link causes type error

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#34379] opened 2019-07-01 17:15 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post/example.com
2. Type some text into the (Gutenberg) editor.
3. Highlight some of the text and press the Link button to create a new link.
4. Paste a link into the field that appears and press Enter.

#### What I expected

The link to be created (and sometimes it is actually created).

#### What happened instead

No link is created and a JavaScript type error is thrown which reads `cannot read property 'type' of undefined`.  If the error is not immediately visible, you may need to have your JavaScript console open during the link creation. 

#### Browser / OS version

Mac OS Chrome, latest

#### Screenshot / Video

Video: https://cloudup.com/cGSySFtHYOn

**Comment by gwwar** [comment] 2019-10-30 00:21
Are you still able to reproduce this one @sirbrillig ? Please re-open if so. I'm going to close out for now, since I think we should have seen more reports if this one didn't get fixed by an update.

**Closed by gwwar** 2019-10-30 00:21 UTC
Labels: [Type] Bug
