### ISSUE TITLE
Help Center: Non-Owner Admins not getting priority support

### ISSUE THREAD

**Issue by csonnek** [Automattic/wp-calypso#89984] opened 2024-04-26 18:41 UTC
### Quick summary

We had a paid site forums thread where the person got routed to the forums and not paid support: https://wordpress.com/forums/topic/sftp-access/?view=all - 

The original poster is a listed Administrator for the Creator site owned by another user - https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=207154266

We thought that even non-owner admins would be able to reach out via the Help Center and get email or live chat support. However, this did not seem to happen in this case as the presence of the `wpcomhelp` tag on the thread indicates the request came from the Help Center (https://wordpress.com/help).

See related Slack thread for discussion: p1714053806473009-slack-C06ST3C477T

### Steps to reproduce

n/a

### What you expected to happen

The non-owner Administrator user of the Creator Plan site would get priority support. 

### What actually happened

The user was routed to the free support forums where they waited nearly two weeks for help. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by kriskarkoski** [comment] 2024-04-26 19:24
I believe this may be an issue when there is a Jetpack connection issue or identity crisis of some kind on an Atomic site. On the account in question the site shows as a free Jetpack site, rather than a paid WordPress.com Atomic site. I tested this on as test account on a site with a good Jetpack connection/showing properly in Calypso and got the expected support options.

Before adding the user as an admin:

![Screenshot 2024-04-26 at 3 11 54 PM](https://github.com/Automattic/wp-calypso/assets/1900444/42241b7b-3e2f-46da-a027-0a21b0b6d9e3)

After:

![Screenshot 2024-04-26 at 3 15 00 PM](https://github.com/Automattic/wp-calypso/assets/1900444/8bd8ecd3-5909-4740-8535-4e3a2bc71b98)

@escapemanuele Vertex has worked on Help Center in the past, but I'm unsure if you are still the owner and if this needs to be fixed in Help Center or something with Atomic identification. Can you let me know if your team will be able to take a look?

This is a particularly important one since we're using admin status on multiple sites as one of our Developer identifiers (though hopefully they wouldn't experience this across all of the sites simultaneously to minimize impact). With our changes to forum staffing resulting in less staffing there that makes it more impactful when they end up in a less monitored channel without a way to contact us directly.

**Comment by escapemanuele** [comment] 2024-04-29 15:38
Hey @kriskarkoski, we can try to give this a look.

I'm having some trouble understanding the problem, you say that `on a site with a good Jetpack connection/showing properly in Calypso and got the expected support options`. So if things are set correctly, it works as expected?

**Comment by liviopv** [comment] 2024-04-30 14:45
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

I think @kriskarkoski hypothesis is correct, I was able to reproduce it.

What I did:

1. Accessed the Jetpack Debugger and forcefully broke the Jetpack connection for my non-a8c account on my personal site
2. Access my non-a8c account - the site wasn't listed on My Sites, but going to wp-admin directly logged me in.
3. When I pull up the Help Center, I'm shown the contact form to post on the forums:

![CleanShot 2024-04-30 at 15 37 49@2x](https://github.com/Automattic/wp-calypso/assets/14153300/8bc6cbc8-81e4-446b-b8a3-cca397c532d8)

@escapemanuele the problem here seems to be when there is a connection issue for a specific user on the site. In the example above, the site's connection still exist and the connection owner (my a8c account) had no issues. However, my non-a8c experienced the same as @csonnek reported.

* Site connected & user connected > Help Center > Chat
* Site connected & user with connection issues > Help Center > Forum

Ideally, we would route Admins to chat, even if there's a connection issue on the account (or the site), as chat would be the best way to resolve quickly.

📌 ACTIONS
- Triaged

**Comment by kriskarkoski** [comment] 2024-04-30 18:52
@escapemanuele I think Livio answered this but yes, if the connection is good it works as expected, it's when there is a connection issue that the wrong options are shown. Basically the support options shown should be based on the site's plan only and the connection status shouldn't impact the experience.

**Comment by escapemanuele** [comment] 2024-05-01 08:31
Ok, I was able to replicate, thanks for explaining how to do it.

We'll try to see if support options can be shown based on site's plan and not on user's connection status.

**Comment by kriskarkoski** [comment] 2024-05-24 14:11
8233672-zd-a8c is a report of this where the owner can access support, but an admin cannot. In this case the Jetpack connection in CLI and debug looks okay, but it does show DNS issues in Calypso and is using a localization plugin that's appending the language to the URL that may be interfering.

**Comment by kriskarkoski** [comment] 2024-05-28 19:20
In 8249529-zd-a8c the user reported being sent to the forums while their site was experiencing a Jetpack connection issue due to a bad plugin update. Interestingly, they also have Woo Express and their own Creator plan that should also give then the ability to contact us so it looks like the Jetpack issue took precedence and somehow forced them to the forums despite having other eligibility as well.

**Comment by rinazrina** [comment] 2024-05-29 04:34
Another instance in 8250293-zd-a8c
The owner can access support, but an admin cannot. Jetpack connection and CLI and JP debugger look OK and the admin's interface language is English.

**Comment by upwardmomentum84** [comment] 2024-05-30 16:41
> Another instance in 8250293-zd-a8c
The owner can access support, but an admin cannot. Jetpack connection and CLI and JP debugger look OK and the admin's interface language is English.

We advised the user to send an email to us but when they do, they receive a response explaining that "It looks like you have a free WordPress.com account." and then explains how they can get help. I have manually created a ticket and email the non-owner admin user here: 8259013-zd-a8c

**Comment by jamiepalatnik** [comment] 2024-05-30 17:15
Another case where the admin contacted us via the forums. We didn't discuss what support options they saw but I noticed they are an admin on other accounts with paid plans, so I would expect them to be able to reach us directly. 

Ticket: 8258695-zd-a8c

**Comment by janmckell** [comment] 2024-06-04 14:45
This user also had the same issue where two administrators on their site can only access the Forum support option.
8205167-zd-a8c

**Comment by kriskarkoski** [comment] 2024-06-04 17:14
Another report in 8277657-zd-a8c where the user posted to the forums because they couldn't contact us. In this case they own the site, but not the upgrades. Jetpack connection seems fine. 

@escapemanuele Any updates on this?

**Comment by agrullon95** [comment] 2024-06-04 19:26
@kriskarkoski - We were able to reproduce with a local admin on an atomic site. We're testing further and looking into the issue.

<img width="400" alt="CleanShot 2024-06-04 at 15 26 44@2x" src="https://github.com/Automattic/wp-calypso/assets/10482592/50baed31-9bcd-4a9f-b650-131e2a238cb3">

**Comment by escapemanuele** [comment] 2024-06-07 13:36
This should have been fixed by https://github.com/Automattic/wp-calypso/pull/91529.

We are working on handling users without a Jetpack connection, we'll redirect them to https://wordpress.com/help/ in that case, where they will be able to get support.

**Comment by escapemanuele** [comment] 2024-06-30 17:45
The issue has been fixed

**Closed as completed by escapemanuele** 2024-06-30 17:45 UTC
Labels: Bug, [Pri] High, [Feature Group] Support, Triaged, [Feature] Help Center, Customer report [LEGACY], [Platform] Atomic, [Product] WordPress.com

**Comment by kriskarkoski** [comment] 2024-07-01 15:33
@escapemanuele Is there a PR or other reference on what we changed to resolve it fully?

**Comment by escapemanuele** [comment] 2024-07-02 09:00
Hey @kriskarkoski I believe that PR https://github.com/Automattic/wp-calypso/pull/91529 fixed the issue, with [this](https://github.com/Automattic/wp-calypso/pull/91630) PR that implemented the redirect in case of broken connection.
