### ISSUE TITLE
Gallery Block: Pexels Free Photo Gallery shows URLs instead of images

### ISSUE THREAD

**Issue by correliebre** [Automattic/wp-calypso#47025] opened 2020-11-02 20:25 UTC
#### Steps to reproduce

1. Create a new post or a new page
2. Add a Gallery Block and select "Select Images" and "Pexels Free Photo"
3. Pick 2 (or more) images from Pexels
4. Publish the post/page

#### What I expected

I expected to get a gallery with images from Pexels. I also expected to be able to edit that gallery's captions. 

#### What happened instead

This is how the published post looks like:

![](https://d.pr/i/M8QUMA+)

Once published, and with that result, if you go to Edit it, it's not possible:

![](https://d.pr/i/CkaZsL+)

#### Additional steps to test
1. Create a new post or a new page
2. Add a Gallery Block > Select Images > Pexels Free Photo
3. Add 2 (or more) images from Pexels
4. Delete the captions from the images 
![](https://d.pr/i/y0yBly+)
5. Publish the post/page
6. The images with no captions show with no issue, the one with a caption shows the same way as earlier
![](https://d.pr/i/R1Y4Q6+)

#### Browser / OS version

Firefox 82.0 (64-bit)
MacOS Catalina 10.15.7

#### Context / Source

I ran into this issue when trying to test how a post with only images would look in the new Spearhead theme. I didn't have any media on my testing site, so I tried with Pexels. Once I saw the issue happening, I tested it with a second theme and saw the same result. 
#manual-testing

**Comment by xpurichan** [comment] 2020-11-04 15:04
This problem does not appear limited to Pexel images. I had a customer report today and they were using their own gallery images. I was able to replicate this on my own website, which is ironically using Pexel images. Here's the code and console errors we see on my test site with Pexels (not showing the customer site for privacy reasons).

![Screen Shot 2020-11-04 at 8 48 27 AM](https://user-images.githubusercontent.com/33190975/98127266-1ad6e100-1e7c-11eb-8159-eb04cc3bfb5e.jpg)
![Screen Shot 2020-11-04 at 8 41 47 AM](https://user-images.githubusercontent.com/33190975/98127295-23c7b280-1e7c-11eb-84fd-12ea440fd33d.jpg)

**Comment by xpurichan** [comment] 2020-11-04 15:17
This appears to be a duplicate of another bug report here:
https://github.com/Automattic/wp-calypso/issues/46813

**Closed** 2021-02-03 19:37 UTC
Labels: [Pri] Normal, [Type] Bug
