### ISSUE TITLE
Gutenberg: Images are oversized on the editor when the dimensions are bigger than the column width

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#68930] opened 2022-10-11 20:49 UTC
### Quick summary

When creating columns with single images, the images are oversized on the editor whenever the image size is bigger than the column width. 

### Steps to reproduce

1. Create a new page or post.
2. Add the columns block. To make it easy to reproduce this issue, I'd suggest adding 3-5 columns.
3. Add an image to each of the columns. At this point, the images should be constrained within their respective column.
4. Change image dimensions settings. If the images are big enough, they will overflow the column in the Editor.

Screencast:

https://user-images.githubusercontent.com/50875131/195195555-410afa4b-0a40-4787-89f7-15934a346f2e.mp4

### What you expected to happen

I would expect the image dimensions setting to be linked to the width of the columns so it would not overflow the column if the size is less than 100%.

### What actually happened

Large images are oversized and overlap other images and columns on the editor.

### Context

Noticed this here: p9cu9o-3zX-p2. I also have seen that on other sites.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

I could reproduce this on several themes. It seems related to Gutenberg only.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jamiepalatnik** [comment] 2022-10-13 15:17
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on Self-hosted - Replicated
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- I am able to replicate this.
- I found several open issues in the Gutenberg repo that seem to be related. Will close this issue as a duplicate.

📌 ACTIONS
- Closed as duplicate of https://github.com/WordPress/gutenberg/issues/36789

**Closed as completed by jamiepalatnik** 2022-10-13 15:17 UTC
Labels: Bug, [Pri] High, [Platform] Simple, [Platform] Atomic
