### ISSUE TITLE
Gallery block: adding/editing additional gallery blocks clears existing galleries

### ISSUE THREAD

**Issue by jonnyruzek** [Automattic/wp-calypso#30104] opened 2019-01-10 21:09 UTC
In pages that have multiple gallery blocks, editing or adding a gallery will clear out all other galleries in that page. This also can occur when adding images to the Media Library while creating a new gallery block.

Please note: I have also seen this issue (#1708002-zen) where a user simply tries to edit an existing gallery. The Media Library briefly appears, and then all gallery blocks are empty again. Animated GIF below.

#### Steps to reproduce

1. Add Page
2. Add a gallery block (or two)
3. Add another gallery block, this time inserting new images into the Media Library
4. Click on Insert (or Cancel), and notice the existing gallery blocks have been cleared of their images

#### What I expected

I expected to be able add multiple gallery blocks, and edit existing blocks, so that my page contains multiple galleries.

#### What happened instead

The existing gallery blocks in the Page were all cleared of their content. The blocks remained, just not the images (except for the new block).

#### Browser / OS version

 - OS: macOS 10.14.2
 - Browser: Chrome
 - Version: 71.0.3578.98

#### Screenshot / Video

- Here's a video from my WP.com test site: https://cld.wthms.co/U8KStk
- Here's an animated GIF from a live site: https://cld.wthms.co/Ofi8A3

#### Context / Source

Bug was discovered by: #manual-testing, #user-report

**Comment by simison** [comment] 2019-01-11 09:35
@rodrigoi I'm assuming the fix is going to be in how Calypso-Gutenberg handles media and thus if Tiled Gallery block (or future Slider block) are affected, they'll get fixed at the same time?

**Comment by rodrigoi** [comment] 2019-01-11 13:11
@simison everything seems to point to a problem on the media library itself, so hopefully yes, there will be a single fix for every block with a media dependency 😉

**Comment by arcangelinis** [comment] 2019-01-12 16:37
Seeing this issue in #1708591-zen as well:

![Screenshot](https://llamaeatsagiraffe.files.wordpress.com/2019/01/screen-capture-on-2019-01-08-at-14-24-59.gif)

**Comment by arcangelinis** [comment] 2019-01-12 16:40
I am seeing this issue on #1708591-zen it appears too.

GIF: https://cld.wthms.co/wDJExO

**Comment by mdrockwell** [comment] 2019-01-12 19:31
Another report of this here: #1712989-zen.

**Comment by mishivee** [comment] 2019-01-12 20:57
Another report can be seen at #1713278-zen.

**Comment by jonnyruzek** [comment] 2019-01-13 16:47
Another report here: #1715066-zen

**Comment by mdrockwell** [comment] 2019-01-14 15:41
Another report here: #1717379-zen

**Comment by mmtr** [comment] 2019-01-15 11:14
I wonder if this is related to https://github.com/Automattic/wp-calypso/pull/29791

**Comment by rodrigoi** [comment] 2019-01-16 18:08
@mmtr I've been sitting on this for a few days trying to work out options to save the code from #29791, because as you pointed out, it's not only related, it is the source of the problem.

I think we have overengineered the problem a bit, and we don't really need to refresh all the blocks when something changes on the media. I think we can safely remove that code and live with blocks preserving deleted images.

We are moving away from Gutenlypso and this is not a problem with Calypsoify, we can leave this on the backlog.

What do you think?

**Comment by mmtr** [comment] 2019-01-17 10:53
@rodrigoi We're not updating all the blocks, we're just updating the ones containing changed images so I think that the source of the problem is something else, probably related to the fact that we have 2 different stores handling the media (Calypso and Core) and they're not sync.

In any case and since we're moving away from Gutenlypso I agree that we can remove that code and live with blocks preserving the images.

**Comment by AMcGrady** [comment] 2019-01-23 20:38
Tested this on a user site and I can now add or edit multiple Galleries on a page or post without the galleries going blank. Is it safe to assume this issue is resolved?

**Comment by edwinho89** [comment] 2019-01-25 04:20
I was testing this on user's site on #1708591-zen, on the page named "Completed Projects" and are able to reproduce this.

**Comment by brezocordero** [comment] 2019-01-29 12:45
Another report: 1754419-zen

**Comment by KokkieH** [comment] 2019-01-30 07:15
Another report from the [forums](https://en.forums.wordpress.com/topic/gutenberg-edition-problems-problems-problems/#add-note)

Affected page: https://palmos.info/photos-playback-%cf%88/

**Comment by damiannep** [comment] 2019-01-30 16:29
Another report in #9835814-hc

**Comment by KokkieH** [comment] 2019-01-31 05:59
A report from the [forums](https://en.forums.wordpress.com/topic/adding-images-to-galleries-in-new-editor-is-chancy/#add-note)

**Comment by zdenys** [comment] 2019-02-06 18:19
Another user reported this in #9567432-HC. I was able to reproduce it on my site (by copying user's content): http://cld.wthms.co/zTo4AD

**Comment by lakellie** [comment] 2019-02-06 19:16
Another user reported in #1759009-zen

**Comment by samiff** [comment] 2019-02-08 22:03
Another report for simple site in #1787750-zen

**Comment by khristiansnyder** [comment] 2019-02-13 18:12
Another report for a simple site using Firefox: #3394182-hc
A workaround is to use a Classic Block and add a gallery within it.

**Comment by adamleone** [comment] 2019-02-14 17:05
Another report in 1803107-zen

As above, suggested keeping the galleries in a classic block.

**Comment by donalirl** [comment] 2019-02-19 05:51
Two more cases: #1810291-zen and #1810276-zen

**Comment by mdrockwell** [comment] 2019-02-19 16:56
Another report here: 10063254-hc

**Comment by lakellie** [comment] 2019-02-21 20:27
Another report in 1820175-zen

**Comment by mdrockwell** [comment] 2019-02-23 15:50
Another report in 10676047-hc

**Comment by tanjoymor** [comment] 2019-02-23 20:55
Returning user regarding this issue looking for an update 1826270-zen (original 1803107-zen)

**Comment by damiannep** [comment] 2019-02-24 10:53
Another report of this in #1791348-zen. The user said that the gallery is removed when using old images but not new ones.

**Videos submitted by user:**
Creating new post with gallery (of old photos) and adding image (shows bug) 
https://youtu.be/YcT4orV3ejU

And then the same process with recent photos (no bug) 
https://youtu.be/FJMRUhTImrU

**Comment by sophiegyo** [comment] 2019-02-26 10:46
I have another user who reported the problem in #10653491-hc

Page in question: 
/tour-salzburg-nach-bad-gastein/

**Comment by jonnyruzek** [comment] 2019-02-26 16:07
Another: 1833694-zen

**Comment by rezzap** [comment] 2019-03-02 08:03
Another report in 1838588-zen

**Comment by thebud15** [comment] 2019-03-04 00:39
Reported in 9497905-hc

**Comment by damiannep** [comment] 2019-03-04 06:15
Another report in #1842633-zen

**Comment by AtrumGeost** [comment] 2019-03-04 15:42
Another report here: 10898256-hc

**Comment by tanjoymor** [comment] 2019-03-05 19:22
Another report here: 1849325-zen

**Comment by rodrigoi** [comment] 2019-03-12 22:31
Thanks everyone for the patience. This should have been fixed when we deployed #31196. Please reopen if there's another report.

**Comment by damiannep** [comment] 2019-03-14 16:08
Hurrah! Thanks for the update @rodrigoi!

**Comment by zdenys** [comment] 2019-10-01 14:53
Another report in 2385061-zen. Pre-existing images in a Gallery Block become un-checked when adding new images to the same Gallery and hence become missing.

**Comment by gwwar** [comment] 2019-10-26 00:25
I'm having trouble breaking the Gallery block, closing this issue since the original problem was fixed.

@zdenys if you're still seeing this behavior do you mind filing a fresh issue with steps, or a quick screenshot or video for more hints on reproducing?

**Closed by gwwar** 2019-10-26 00:25 UTC
Labels: [Goal] Gutenberg, [Type] Bug
