### ISSUE TITLE
Reblog button is missing and the Like button is not working on mobile iOS

### ISSUE THREAD

**Issue by rinazrina** [Automattic/wp-calypso#49704] opened 2021-02-04 08:47 UTC
### Steps to reproduce the behavior

1. Log into your WordPress.com account on iOS mobile browser 
2. Go to a WordPress.com post/page that enables Reblog and Like buttons (e.g. https://rebornpipes.com/2021/02/03/new-life-for-a-patent-era-1915-18-dunhill-a-bruyere-66-standing-billiard/ and https://thepipesteward.com/2020/02/02/welcome/ )
3. Locate the sharing buttons below the post
4. Click on the Like button and see if the Reblog icon is missing

#### What I expected to happen
The Reblog button is showing and the Like button is working when clicked

#### What actually happened
The Reblog button is missing and the Like button is loading in loop when clicked.

### Context
#3710845-zen

#### Browser / OS version
This issue is reproduced in iPhone 10S and iPhone X, in Chrome and Safari browsers. We can't reproduce this on Android and on iPhone 11. 

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Simple sites

#### Is there any console output or error text?
-

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
This seems to happened in certain devices and this affect more than one site. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Screenshot of the missing Reblog button:
<img width="324" alt="Screenshot on 2021-02-04 at 16-40-03" src="https://user-images.githubusercontent.com/33721365/106866974-0d91f280-6708-11eb-897b-f79e940aac4c.png">

Screen recording when the Like button is clicked:

https://user-images.githubusercontent.com/33721365/106867119-30240b80-6708-11eb-9d4d-cc30ce2705f3.mp4

**Comment by cathymcbride** [comment] 2021-02-04 14:18
Duplicate of https://github.com/Automattic/wp-calypso/issues/35140

**Closed as completed by cathymcbride** 2021-02-04 14:18 UTC
Labels: Bug
