### ISSUE TITLE
Editor: Excerpt field removed from Page edit screen in some themes.

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/wp-calypso#18947] opened 2017-10-18 02:09 UTC
#### Steps to reproduce
1. Activate Twenty Ten or Radcliffe 2
2. Create a new Page or edit an existing Page
3. Expand More Options to see Excerpt field

#### What happened instead
The Excerpt field seems to be missing on some themes for the Page editor. Twenty Ten, Radcliffe 2, and Sketch are ones I've found currently exhibiting the issue.

#### Browser / OS version
OSX/Chrome, Firefox

#### Screenshot / Video
http://cld.wthms.co/Ao3wq8

#### Context / Source
A user contacted support attempting to change the excerpt on a page in Twenty Ten. They could not find the Excerpt box in Calypso.

I SU'd into the account, and verified it was not appearing, and then replicated on a test site of my own. I also replicated on a separate browser, with a non-A8C account and unproxied. I cleared the cache and cookies before logging in to provide a fresh cache of Calypso. I was able to replicate with Twenty Ten, Radcliffe 2, and Sketch. Various other themes seemed unaffected.

**Comment by KokkieH** [comment] 2017-10-20 08:13
Another case in Hemingway Rewritten in 880569-f. In this case it's effectively preventing the user from controlling the og:description content that appears when sharing to Facebook - currently it's sharing the default excerpt that was set on creating the site with no way to change it.

**Comment by rachelmcr** [comment] 2017-12-12 15:25
I tested with the themes mentioned here (Twenty Ten, Radcliffe 2, Sketch, and Hemingway Rewritten) and could not reproduce the issue. Closing as it no longer seems to be a problem.

**Closed by rachelmcr** 2017-12-12 15:25 UTC
Labels: Editor, [Pri] High, [Type] Bug
