### ISSUE TITLE
FSE: Full Width Blocks wider than page editor

### ISSUE THREAD

**Issue by separatelyunited** [Automattic/wp-calypso#39155] opened 2020-01-29 21:29 UTC
#### Steps to reproduce
1. Starting on a simple site with FSE enabled, go to My Site -> Site -> Pages and choose any page to edit.
2. In the editor add any block that allows for full width to be chosen (image, column block, cover, or group block all work well for this test)
3. Change block width to full width
4. Attempt to change block type or edit using the block toolbar.

#### What I expected

I expected full-width blocks to fit within the page editor "page" width and all block options to be available.

#### What happened instead

The full-width blocks are larger than the editor area and options to the left are hidden off the screen.

#### Browser / OS version

Google Chrome on Mac OS Mojave 10.14.6 (18G1012)

The user also tested using Microsoft Edge.

I could replicate this on Simple Sites but do not have an Atomic site with FSE to test with.

#### Screenshot / Video

![Block wider than editor](https://snipboard.io/JRw1IN.jpg)

![Changing Width](https://cl.ly/774a125fe155/Screen%252520Recording%2525202020-01-29%252520at%25252002.29%252520PM.gif)

Additional References:

I found a similar issue; however, it was closed over 2 months ago:  https://github.com/Automattic/wp-calypso/issues/37686

**Comment by jacoswan** [comment] 2020-02-02 17:00
I can confirm this happens on my plain AT site also, not FSE enabled (as far as I'm aware). Currently TwentyNineteen is enabled, and it looks like this (Cover block, full width, is selected so should show the bar at the top of the block): 

![image](https://user-images.githubusercontent.com/15178758/73611731-8b9b5500-45ed-11ea-97ad-5c61e2fea534.png)

My understanding of what exactly controls this might be muddled, but in the CSS below, unchecking `left` and `width` brings the block to within the confine of the editor: 

![image](https://user-images.githubusercontent.com/15178758/73611778-0a908d80-45ee-11ea-9853-d788515d70db.png)

**Comment by davipontesblog** [comment] 2020-03-09 18:26
Closing in favor of https://github.com/Automattic/themes/issues/7174

**Closed by davipontesblog** 2020-03-09 18:26 UTC
Labels: [Goal] Full Site Editing, [Type] Defect
