### ISSUE TITLE
Reader: Add xkcd hover text within the reader

### ISSUE THREAD

**Issue by dllh** [Automattic/wp-calypso#8941] opened 2016-10-25 03:04 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/ 
2. Subscribe to xkcd.com.
3. View the feed in the reader.
4. Hover over one of the delightful, clever comics.
5. Clutch your head in anguish as you discover that the hover text isn't pulled into the reader.

#### What I expected
- Wit
- Occasional subversiveness
- Title/hover/whatever text corresponding to what displays on xkcd.com

#### What happened instead
No hover text. :( I miss it, like the deserts miss the rains.

#### Browser / OS version
Mac/chrome  53.0.2785.143 (64-bit) and the desktop app.

#### Screenshot / Video
![no-xkcd-titles-makes-me-sad-like-10](https://cloud.githubusercontent.com/assets/2738252/19671563/a2d6072e-9a3d-11e6-97ab-91c842694956.gif)

#### Context / Source
Long ago, I used Feedly, and it did pull in these titles, so I know it's possible. I don't imagine most image titles matter all that much, but they're pretty much an essential part of the xkcd content, and I'd like to suggest that for this site, making sure we parse the title is worthwhile, even if only to delight the probably limited audience.

**Comment by blowery** [comment] 2016-10-25 12:00
@dllh it's a step removed, but if you click on the card and open the full post view, the title is intact there. We just don't carry it along into the featured image preview. 

![screenshot](http://i.giphy.com/aDRPYKPSOGrUQ.gif)

**Comment by lancewillett** [comment] 2016-10-26 17:59
Closing as "works as intended."

**Closed by lancewillett** 2016-10-26 17:59 UTC
Labels: Reader, [Type] Enhancement
