### ISSUE TITLE
[Bug]: Latest Posts: Improve handling of .webp featured images

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#64099] opened 2022-05-27 00:50 UTC
### Quick summary

When using the latest posts block set to show featured images, if the featured image is set to use an image that is in `.webp` format, it does not display correctly on the site front end.  Instead, it displays at approx. half of its raw size in pixels.

<img width="1283" alt="Markup 2022-05-26 at 17 43 23" src="https://user-images.githubusercontent.com/1967448/170606430-894b9182-8bf6-4f32-8ffc-a382390bb997.png">

### Steps to reproduce

1. set up two blog posts on your test site
2. set one post to use a featured image in the `.webp` format
3. set the other post to use a featured image in either `.png` or `.jpg` format
4. On a test page add the Latest Posts block and set it to display featured images

### What you expected to happen

All images should come in at the correct size as set in the block settings

### What actually happened

Images in `.jpg` or `.png` display at the correct size, as expected,  but `.png` images display at 50%

### Context

https://wordpress.com/forums/topic/keeping-featured-images-full-sized

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple/Atomic

Simple

### Other notes

Tested against several themes with the same result, so the issue is not specific to themes.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Use either the Query Loop block or the Blog Posts block

**Comment by worldomonation** [comment] 2023-05-23 03:14
📌 REPRODUCTION RESULTS

    Tested on Simple – Not reproduced
    Tested on Atomic – Not reproduced
    Replicable outside of Dotcom – Not reproduced

📌 FINDINGS/SCREENSHOTS/VIDEO

    Unable to reproduce issue on all platforms tested (Simple, Atomic, self-hosted with Jetpack).
    WEBP and JPEG featured images are shown at the same width, and changing the featured image size affects both    equally.

    **Simple (block is showing post content as well**
<img width="658" alt="Screenshot 2023-05-23 at 12 07 23 PM" src="https://github.com/Automattic/wp-calypso/assets/6549265/f2ddcbc5-5c05-4663-9018-3b922a4a56c0">


    **Atomic**
<img width="716" alt="Screenshot 2023-05-23 at 12 10 27 PM" src="https://github.com/Automattic/wp-calypso/assets/6549265/a1254f27-5d6f-42c8-9ea8-725710ed0ff1">

    **Self-hosted**
<img width="602" alt="Screenshot 2023-05-23 at 12 12 34 PM" src="https://github.com/Automattic/wp-calypso/assets/6549265/b45ee6c9-5841-4ef5-aa67-5e34e1af3c48">


📌 ACTIONS
    Closed as not reproducible. Please feel free to reopen.

**Closed as completed by worldomonation** 2023-05-23 03:14 UTC
Labels: Bug, [Pri] Low, [Closed] Not Reproducible
