### ISSUE TITLE
Strange rendering/loading issue with gutenboarding in the add new site flow.

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#45662] opened 2020-09-15 07:26 UTC
Strange rendering/loading issue with gutenboarding in the add new site flow.

See video: https://cloudup.com/cM26KGT-xh8

#### Steps to reproduce

1. Go to customer home.
2. Click switch site.
3. Click add new site.
4. See the strange rendering/loading that happens before it lands in gutenboarding `/new`.

#### Screenshot / Video

<img width="1080" alt="2020-09-15_10-23-16" src="https://user-images.githubusercontent.com/1287077/93179044-ce094080-f73d-11ea-9b36-675a92df4e7a.png">

**Comment by ciampo** [comment] 2020-09-18 15:57
After spending some time investigating the issue, my conclusion is that **this issue is caused by the `is-section-signup` class being added to the page's `<body />`, while the rest of the page still shows the markup from the previous section (e.g. home)**

I was able to find the code that applies the classname update:

- The signup section is defined in [`client/sections.js`](https://github.com/Automattic/wp-calypso/blob/99784ab0954bf557253fcc81af9ad966cbcaba5f/client/sections.js#L171-L177)
- When clicking on the "Add new site" link in the sidebar, the module containing the code for the signup section is loaded and then activated (see [`client/sections-middleware.js`](https://github.com/Automattic/wp-calypso/blob/99784ab0954bf557253fcc81af9ad966cbcaba5f/client/sections-middleware.js#L98))
- When the signup section gets activated, a `SECTION_SET` redux action is dispatched, and the store is updated to reflect that 'signup' is the new section (see [`client/sections-middleware.js`](https://github.com/Automattic/wp-calypso/blob/99784ab0954bf557253fcc81af9ad966cbcaba5f/client/sections-middleware.js#L24-L27))
- This causes the `<Layout />` component, which is connected to the Redux store, to receive the updated value of the current section. This value is passed down to the `<BodySectionCssClass />` component (see [`client/layout/index.jsx`](https://github.com/Automattic/wp-calypso/blob/99784ab0954bf557253fcc81af9ad966cbcaba5f/client/layout/index.jsx#L173)
- The `<BodySectionCssClass />` component finally adds the `is-section-signup` class to the `<body />` element (see [`client/layout/body-section-css-class.js`](https://github.com/Automattic/wp-calypso/blob/4537033c6794449ce0a10b69d72daf5fa658d553/client/layout/body-section-css-class.js#L38))
- The signup section entry file (see [`client/signup/index.web.js`](https://github.com/Automattic/wp-calypso/blob/a1501fea47cbd5e3fccf09b7f39aaf3eaae86d98/client/signup/index.web.js)) defines the routes handler (using pagejs). In my tests, the route handlers are called _after_ the `is-signup-section` classname is added to the body


### Next steps

Keep investigating, and find the reason why the signup section is rendered in the page with so much delay compared to when the `is-section-signup` class get added to the `<body />`

**Comment by ciampo** [comment] 2020-10-01 10:52
Closing as superseded by #46084, which explain the more generic problem behind this issue

**Closed by ciampo** 2020-10-01 10:52 UTC
Labels: [Goal] Onboarding
