### ISSUE TITLE
Editor: Gallery preview unavailable in Visual mode

### ISSUE THREAD

**Issue by megsfulton** [Automattic/wp-calypso#20441] opened 2017-12-02 22:37 UTC
#### Steps to reproduce
1. Navigate to a page with a gallery
2. Open the page in the editor
3. Sometimes there's no preview for the gallery / images in the visual mode 

#### What happened
Image gallery doesn't appear in the visual mode of the editor, the short code for the gallery is visible in the HTML. 

If you click on an a certain area in the visual editor you can grab the 1px tall area for the gallery to get into the gallery editor. But the gallery preview doesn't appear in the visual editor after saving changes to the gallery. 

#### Browser / OS version
Chrome / Mac OS

#### Screenshot / Video

<img width="758" alt="screen shot 2017-12-02 at 2 31 38 pm" src="https://user-images.githubusercontent.com/161697/33520364-6bdb5e12-d76e-11e7-9b79-2a702a0e85ce.png">
<img width="725" alt="screen shot 2017-12-02 at 2 31 45 pm" src="https://user-images.githubusercontent.com/161697/33520365-6bf024aa-d76e-11e7-8e84-e39254c779b0.png">
<img width="740" alt="screen shot 2017-12-02 at 2 33 06 pm" src="https://user-images.githubusercontent.com/161697/33520366-6c048ada-d76e-11e7-86b2-62f5d15e5fca.png">

**Comment by rachelmcr** [comment] 2017-12-10 12:34
In my testing, I could reproduce the issue in either the post or page editor after adding a gallery with the Square Tiles or Slideshow styles. Other gallery styles worked as expected.

**Comment by MindyPostoff** [comment] 2018-06-19 19:04
I may have had another report of this issue in 1213964-zen. 

Both the user and I tried the Tiled Columns style, and it seems the gallery vanishes from the Visual editor after making edits to at least one individual image within the gallery.

Screencast of my test site here: http://recordit.co/C67JpPKDY8

**Comment by lizthefair** [comment] 2018-07-30 22:47
Another report in 1314597-zen.  This user experienced the problem when adding any new gallery to a page.  Like the other reports, the gallery did appear in the HTML view, and could be published, but could only be edited via WP-admin or HTML.

**Comment by KokkieH** [comment] 2018-07-31 13:11
Another report in the [forums](https://en.forums.wordpress.com/topic/visual-editor-not-displaying-gallery-images/).

In this case it's a Business Plan site using plugins. I can see the issue viewing any post with a gallery on that site, and if I copy the HTML of an affected post on that site into a new post on a test site it happens on the test site as well. But the moment I replace the gallery in the copied post with a new one the issue no longer occurs.

Ruled out theme or plugins as the cause. Happens when gallery type is ‘Tiled Mosaics’, ‘Square Tiles’ , ‘Circles’ or ‘Tiled Columns’, but not ‘Individual Images’, ‘Thumbnail Grid’ or ‘Slideshow’.

**Comment by rantoncuadrado** [comment] 2018-08-03 13:31
Related https://github.com/Automattic/atomic/issues/518
I've taken a look at the previous comments and it seems there are cases with Oxygen, Ovation and Veni

Another report here (ATOMIC/VENI): https://atomicrequests.wordpress.com/2018/08/03/margaretrajic-com-galeries-preview-not-visible/

Video: ​http://cld.wthms.co/aDbv3N (password L52z1gk9e2798ihhfdsljkhn )

I created a trac issue to get another insight on this problem and linked it with the other 2 GH issues
https://wpcom-premium-themes.trac.automattic.com/ticket/2440#ticket

**Comment by rachelmcr** [comment] 2018-08-30 13:37
Thanks for the reports! I tested this in Gutenberg and couldn't reproduce it there. Since our current development priority is on Gutenberg, and this issue (which doesn't affect the published post) will be resolved with that launch, I'm going to close this for now.

**Comment by ajaykj** [comment] 2019-06-04 12:30
Reopening this thread as got another case in 13192252-hc.

**Closed** 2019-06-04 14:22 UTC
Labels: Editor, Media, [Pri] High, [Type] Bug
