### ISSUE TITLE
(8P) Editor: no warning or error given when adding media to media blocks that cause site to exceed storage limit 

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#43785] opened 2020-06-30 00:17 UTC
Steps to reproduce:

1. For a WordPress.com Free site, go to My Sites > Site > Media.
1. Add items until you run out of space.
1. Go to My Sites > Site > Posts > Add new post.
1. Add a title and an image block.
1. Drag an image onto the block that exceeds the site storage limit.

**Result:** I expected to see a warning about going over storage capacity, but no error ever appears and the spinner seems stuck. You never get a warning or error message but you can see a quick preview of the image uploading even though the upload won't ever go through! ([11m58s](https://cloudup.com/caqpvTM-__H))

![no-storage-warning-at-all-in-calypso-gutenberg](https://user-images.githubusercontent.com/1119271/86068034-9094f100-ba33-11ea-977c-453a8f031b48.png)

<p style="clear:both;"><sup>Tested using Safari 13.1 macOS 10.15.4 on WordPress.com Free site gotravelrewards.blog logged in as testuser0313 unproxied.</sup></p>

**Comment by davemart-in** [comment] 2020-07-15 12:34
Note: For Business and eCommerce customers who signed up prior to August 2019 we need to make it so that the 200GB upload quota does not apply and they do not see any upload error messages. Let's chat about this once this issue gets picked up.

**Comment by obenland** [comment] 2020-08-13 21:54
Notes from Backlog Grooming:
*  90% sure image uploads can show an error (at least a generic one) when the upload fails.
* maybe we are just returning it wrong from the endpoint and the block editor doesn't understand things have failed?
* It’s important to keep in mind how the file was trying to be uploaded since there are different handlers. MediaPlaceholder, MediaReplaceFlow, just dropping in the editor canvas (don’t know whats the component here, guessing some embed?). This seems to be a MediaPlaceholder component
* For all blocks supporting any kinds of uploads, there is a shared part of the code and a custom one specific to this block. we need to definitely determine where this fits as we might be affecting many blocks (and we might want to, as the upload limit goes far beyond just images)

**Comment by obenland** [comment] 2020-08-13 21:55
I also wonder if it's connected to how these space errors are returned from the API, with that `|` as mentioned in https://github.com/Automattic/wp-calypso/issues/43783#issuecomment-651859534

**Comment by obenland** [comment] 2020-08-18 17:42
Testing with `add_filter( 'get_space_allowed', '__return_zero' );` I get the following error:

![image](https://user-images.githubusercontent.com/1398304/90546236-a45cf980-e13e-11ea-9731-341384087ba1.png)

I'll try and replicate differently.

In image blocks it's using the `wp/v2/media` endpoint, so the bug mentioned in https://github.com/Automattic/wp-calypso/issues/43783#issuecomment-651859534 is not the cause here.

**Comment by designsimply** [comment] 2020-08-18 20:59
I re-tested this issue today and found the problem is still happening where if I drag an image into the block editor on a blog where the storage limit has been reached then the media upload fails silently without giving a helpful error message. ([13m32s](https://cloudup.com/cpFiiUl6POp))

<p style="clear:both;"><sup>Tested using Safari 13.1.1 macOS 10.15.4 on WordPress.com Free site gotravelrewards.blog logged in as testuser0313 unproxied.</sup></p>

Next level: instead of saying 14 KB needed, consider adding a call to action such as "Upload limit has been reached. Please review your plan." I didn't find the "14 KB needed" part of the message very helpful from a user perspective. Let me know if you'd like me to open a separate issue for this part!

**Comment by obenland** [comment] 2020-08-18 22:33
It works fine in Chrome but I was able to reproduce it in Safari when dragging an image into the block editor without adding a block first. It looks like the API request to upload the image never fires, so I wonder if it's a Gutenberg bug on multisites in Safari.

**Comment by designsimply** [comment] 2020-08-19 04:07
I couldn't get it to work in Chrome! 😕 ([1m13s](https://cloudup.com/cgpL97208eM))
<sup>Tested using Chrome 84.0.4147.125 macOS 10.15.4 on WordPress.com Free site gotravelrewards.blog logged in as testuser0313 unproxied.</sup>

**Comment by mreishus** [comment] 2020-08-26 16:22
Unable to reproduce in *linux/firefox/80.0b8*, *linux/chromium/85*, *ios/safari/13.6.1*.  

Test Steps:
* Added filter `add_filter( 'get_space_allowed', '__return_zero' );` to sandbox.
  * Also tried `add_filter( 'get_space_allowed', function () { return 5; } );` in case 0 was a special case.
* Site used: https://testsite10mmr.wordpress.com/ while sandboxed
* Verified media library showed 100% space used
* Created new post
* Desktop browsers:
  * New image block, click upload
  * New image block, drag into image blocka
  * Drag image into empty space without adding an image block
* Mobile Browser:
  * New image block, click upload
  
In all cases I saw the "Not enough space to upload. 2,453 KB needed" message.

Above we have reports of the issue happening in mac/chrome/84 and mac/safari/13.1.1.

**Comment by frontdevde** [comment] 2020-08-27 06:47
> logged in as testuser0313 unproxied.

@mreishus Not sure it could be related but just in case have you tried whether proxied/unproxied yields a different result?

**Comment by mreishus** [comment] 2020-08-27 14:04
Hmm, have not, I was proxied the entire time I was testing.  That could be it.

**Comment by cpapazoglou** [comment] 2020-08-28 14:40
Switched to User through store admin and I can reproduce it. I will report later my findings or just fix it.

**Comment by cpapazoglou** [comment] 2020-08-28 15:00
The problem derives from the fact that `add_filter( 'get_space_allowed', '__return_zero' )` returns no available space at all where in fact the reality is totally different for most of our users. Let's say a user has 1mb left space, uploading an image of exact 1024kb would be very surprisingly and rare. Let's assume they upload an image of 1000kb. The space left then would be 24kb insufficient for any image upload.

**Cases:**
1) uploading through the media library or the image block return the correct error (the api is triggered)
2) dragging the image to the editor stalls, the api is never triggered

**Steps to reproduce (2)**
* Got to /wp-admin/upload.php in your sandbox
* Check how much space you have available
![](https://cln.sh/mvkHHJ+)
* Go to /wp-admin/options.php 
* Change the `blog_upload_space` so that you have available less than 100kb (value should be in mb, accepts decimal). Be careful to note down the previous value
* Go to the editor, open the network in developer tools 
* Go to the editor, drag n drop an image > 100kb
* You will see that the image is converted from blob but then not api is triggered

I assume it is something Gutenberg related as the user suggested they have seen this behaviour again in a non WordPress.com site. I keep digging.

**Comment by cpapazoglou** [comment] 2020-08-28 17:03
To debug Gutenberg on your environment you may use pc9Uba-1F-p2

**Comment by jeryj** [comment] 2020-08-28 22:22
I think I've tracked down the issue. I'm not sure how best to solve for it, but here's what's happening:

- The uploader uses `maxUploadFileSize` to determine [if we should open a request or not to upload the file](https://github.com/WordPress/gutenberg/blob/8afed75c6f2daa2624b0f91781aa4bee163d4e93/packages/media-utils/src/utils/upload-media.js#L149-L160)
- It assumes that `maxUploadFileSize` will be consistent
- it uses [`wp_max_upload_size()` to set it](https://github.com/WordPress/gutenberg/blob/6b1999ef5ad3aded974bb311d0f72cd2eef134b1/lib/edit-site-page.php#L106)
- On multisites, `wp_max_upload_size()` is actually variable determined by the maximum file size OR the amount of space left after it gets filtered through this function:
```
function upload_size_limit_filter( $size ) {
	$fileupload_maxk = KB_IN_BYTES * get_site_option( 'fileupload_maxk', 1500 );
	if ( get_site_option( 'upload_space_check_disabled' ) ) {
		return min( $size, $fileupload_maxk );
	}

	return min( $size, $fileupload_maxk, get_upload_space_available() );
}
```
- Back to Gutenberg... If there’s not enough space left when you try to upload a file, **it returns the error without ever trying to upload the file**
- **Our error messages are waiting for an error response from the API, which never happens, because the request never goes through.**

After removing that check for the `maxUploadFileSize` in order to force an upload, we get this correct behavior:
![image upload error from server](https://user-images.githubusercontent.com/967608/91619484-c3cfff80-e952-11ea-822a-666fa6066b4f.gif)

I'm not sure what the best route to fix this would be. Do we:
- Use a different function than `wp_max_upload_size()` to set the `maxUploadFileSize` so that it's consistent? 
- Change the behavior of ``wp_max_upload_size()` in core so that it's always consistent?
- ... something else?

**Comment by cpapazoglou** [comment] 2020-08-31 11:38
Thanks @jeryj for looking into this. From my point of view, the problem is that wp-calypso (or Gutenberg) doesn't do anything (?) on the error reported by Gutenberg. It seems like a callback function is not firing or a render doesn't happen.

> Back to Gutenberg... If there’s not enough space left when you try to upload a file, it returns the error without ever trying to upload the file

In fact, it is far better to **prevent the upload itself** and show the error than wait for the API to respond with the error. This way:
- we can provide a faster experience to the User
- use less server resources.

**Comment by jeryj** [comment] 2020-08-31 13:43
> Actually, I assume we need to fix the following
WordPress/gutenberg#21559

Agreed! That looks like one of the issues. I guess there are two separate things:
1. The image drag/drop into the canvas max upload size is not being caught correctly.
2. The `maxUploadFileSize` is not always the correct error. We should have a way to catch the difference between a file being uploaded that is too large for the system, vs a file that is exceeding the amount of space left on the server.

**Comment by cpapazoglou** [comment] 2020-08-31 16:40
> The maxUploadFileSize is not always the correct error. We should have a way to catch the difference between a file being uploaded that is too large for the system vs a file that is exceeding the amount of space left on the server.

You are right @jeryj! Thanks for bringing this up! It seems that they used `maxUploadFileSize` as a shortcut for two different things. Are you up on creating a separate issue to address/triage it?

**Comment by cpapazoglou** [comment] 2020-08-31 17:37
I have tested and reviewed the following PR which will ultimately close the current issue
https://github.com/WordPress/gutenberg/pull/24398

**Comment by jeryj** [comment] 2020-08-31 20:54
Issue created for the incorrect Gutenberg upload error message: https://github.com/WordPress/gutenberg/issues/24948

**Comment by cpapazoglou** [comment] 2020-09-02 09:57
I created a new PR so we can make progress faster
https://github.com/WordPress/gutenberg/pull/25004

**Comment by cpapazoglou** [comment] 2020-09-09 14:34
The PR is merged, so the fix will be shipped with the next Gutenberg version in WordPress.com

**Closed by cpapazoglou** 2020-09-09 14:34 UTC
Labels: Editor, Media, [Type] Bug
