### ISSUE TITLE
New Site: Example site names require Spanish translation

### ISSUE THREAD

**Issue by Rolilink** [Automattic/wp-calypso#62116] opened 2022-03-22 03:27 UTC
### Quick summary

When creating a new site the example site names on the site name input are expected to be translated to the selected language, right now in Spanish we have an incomplete experience with english names.

<img width="1512" alt="Screen Shot 2022-03-18 at 5 58 57 PM" src="https://user-images.githubusercontent.com/1035546/159401480-c9f7c271-abb4-4762-809b-6ec1be2cca65.png">

### Steps to reproduce

1. Navigate into `/new?ref=calypso-selector`.
2. Change language to Spanish
3. Site names examples are still showcasing in english

### What you expected to happen

We should have Spanish site examples like in other languages example in french:
<img width="1512" alt="Screen Shot 2022-03-21 at 10 25 48 PM" src="https://user-images.githubusercontent.com/1035546/159401916-e2434a33-5a90-4b35-81df-19e984e6e1b2.png">

### What actually happened

Is showing english names

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari, iOS Safari, Android Chrome

### Simple/Atomic

Simple, Atomic

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

Probably just need some translations!

**Comment by cuemarie** [comment] 2023-05-24 22:45
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - Unable to repro

📌 FINDINGS/SCREENSHOTS/VIDEO
- Is this site title step still a part of the new site flow?  Starting from WordPress.com/start, I didn't encounter this step

📌 ACTIONS
- Needs reply

📌 Message
- @Automattic/lego is the step shown above (to create a site title) still a part of the new site flow, or has that been removed in favor of the launchpad now?

**Comment by cuemarie** [comment] 2023-05-30 21:23
The reported problem is on the “My site is called _________” step of the new site onboarding, directed to start from `/new?ref=calypso-selector`  - however, it doesn't seem like this step is still part of the process.

When I start from `/new?ref=calypso-selector`, I’m redirected to `/start`, and then the steps are as follows:

1. choose a domain
2. choose a plan
3. site goals (chose writing)
4. Blog name and tagline
5. suggested set up
6. Launchpad

And step 4, the "Blog name and tagline" step, looks like this for me when I proceed through with my language set to Spanish:

![Markup on 2023-05-30 at 14:20:04](https://github.com/Automattic/wp-calypso/assets/27249804/446f2c57-d528-48ad-8f5b-9359eb76c728)

With all that in mind, I'm going to close this out as not reproducible, as it seems we've updated the UI since this report and it's no longer relevant.

📌 ACTIONS
- Closed as not reproducible

**Closed as not planned by cuemarie** 2023-05-30 21:23 UTC
Labels: Bug, [Pri] Normal, i18n, Triaged, [Closed] Not Reproducible, Back to Basics
