### ISSUE TITLE
Table Block: Navigation bug using up and down keyboard keys when in cells

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#33791] opened 2019-06-10 12:19 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/page/DOMAIN/PAGEID
2. Add a Table Block
3. Set up the table with some rows and columns
4. Click on one of the cells
5. Use the keyboard "Up" or "Down" keys to navigate the cells in the Table

#### What I expected
To navigate to the cell immediately above or below when using "Up" or "Down", respectively

#### What happened instead
I was moved to another block on the page entirely

#### Browser / OS version
Google Chrome
Version 74.0.3729.169 (Official Build) (64-bit)

#### Screenshot / Video
https://cld.wthms.co/kRE4XV

#### Context / Source
I was testing out some blocks on my test site and found this bug.
#manual-testing

**Comment by arunsathiya** [comment] 2019-08-17 08:54
I am not able to reproduce this anymore. I tested on Firefox Quantum 66.0.5 (64-bit) with a WordPress.com site without FSE enabled. 

I am closing this report for now, but could you test again, please? Probably something changed between the time it was originally reported and now.

**Closed by arunsathiya** 2019-08-17 08:54 UTC
Labels: [Goal] Gutenberg, [Type] Bug
