### ISSUE TITLE
Editor: top toolbar appears inside the preview window if you click a link to the same blog inside a preview

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#6912] opened 2016-07-20 00:36 UTC
Steps to reproduce:

1. Create and save a new draft with a link to another post on the same blog
1. Click the Preview button

<strong>Result:</strong> the top toolbar appears inside the preview modal

<img width="1280" alt="screen shot 2016-07-19 at tue jul 19 4 32 36 pm" src="https://cloud.githubusercontent.com/assets/1119271/16971277/a07c1e78-4ddf-11e6-98d2-b7d398343555.png">
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/10114 using Firefox 47.0.1 on Mac OS X 10.11.5</sup>

**Comment by mtias** [comment] 2016-07-20 09:05
Duplicate of #2013.

**Closed by mtias** 2016-07-20 09:05 UTC
Labels: Editor, [Type] Bug

**Comment by designsimply** [comment] 2016-07-20 22:10
Ack. Thanks!

**Comment by mtias** [comment] 2016-07-21 10:03
No problem :)
