### ISSUE TITLE
Pages are not showing up consistently in Calypso in wordpress.com/pages

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#84312] opened 2023-11-18 09:23 UTC
### Quick summary

It often happens that our users will see the following message when they try to access the pages in Calypso:

"You haven't published any pages yet".

The causes vary depending on the setup, but the main ones are usually plugin conflicts or a Jetpack sync issue.
Sometimes the user installs a new plugin in the meantime, a plugin update happens or it just happens out of nowhere. 

Here's one from @tanjoymor  opened a while back:
https://github.com/Automattic/wp-calypso/issues/53680 - although it's a Simple site case
https://github.com/Automattic/wp-calypso/issues/56183 - this seems specific to Divi and slightly different in nature but relative to this

### Steps to reproduce

1. Install and Elementor 
2. Create pages using Elementor. 
3. Go to https://wordpress.com/pages/sitename

Note: The steps are fairly generic as I wasn't able to find a clear pattern on why/how this happens.

### What you expected to happen

To see the list of pages.

### What actually happened

![image](https://github.com/Automattic/wp-calypso/assets/6737345/1a8a071e-ccb6-464d-b6b0-2888b8685beb)
(If we check the count of pages above that message, the pages are there, just not visible)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

The immediate workaround it to access them through WP-Admin instead, but a Jetpack sync or a plugin conflict test is usually required.

My suggestion would be to turn off the Calypso view for pages/posts if a third-party builder is installed to avoid further issues. Also, this should help the users get faster to their preferred builder instead of first going through the initial single-page Calypso view.

Slack thread: p1700231540476579-slack-C03TY6J1A
Ticket: 7314877-zd-a8c

cc @Copons

**Comment by maciejpilarski** [comment] 2024-01-01 16:39
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I have followed the steps and was not able to reproduce the issue, Elementor created pages are visible on the list of Pages:

![Markup on 2024-01-01 at 17:37:26](https://github.com/Automattic/wp-calypso/assets/9025643/9af171bf-ed43-4b34-b4af-b07ac1e5d4a5)

📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)

**Closed as completed by maciejpilarski** 2024-01-01 16:39 UTC
Labels: Bug, [Pri] Low, Feature Request, [Feature] Calypso & wp-admin Navigation, Triaged, Customer report [LEGACY], [Platform] Atomic, [Product] WordPress.com, [Feature Group] Other Infrastructure

**Comment by Robertght** [comment] 2024-01-03 05:31
@maciejpilarski Can/should we keep this open for @Copons and his team to be reviewed as per p1700231540476579-slack-C03TY6J1A, please?

**Comment by Copons** [comment] 2024-01-03 09:33
Readded to our backlog — it's not our highest priority though.

**Comment by dsas** [comment] 2025-03-17 11:06
Going to close this on the boards, untangling this page has side-stepped the issue.
