### ISSUE TITLE
Themes: Restoration of previous theme isn't working

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#66500] opened 2022-08-11 13:43 UTC
#### Steps to reproduce

1. Assign a free theme to your site.
2. Purchase a premium theme for your site.
3. Remove the premium theme purchase.
4. Instead of your original free theme being restored, you'll be assigned a random theme.

Full discussion: p1659985142358919-slack-C0160HSMDQV

paYKcK-1V9-p2 has some comments outlining where the code for restoring the previous theme is.

**Comment by DavidRothstein** [comment] 2022-08-16 19:55
I can't reproduce this as written -- when I cancel my premium theme via Calypso, it automatically switches me back to the previous theme that I was using beforehand.

I do think this behavior only works (and was probably only ever implemented) for users _self-cancelling_ the theme via Calypso, though.  If the premium theme gets removed any other way -- for example by a happiness engineer, or if the user had access to the theme via a WordPress.com plan but then the plan is removed -- in that case they probably do go back to a random theme.  So it sounds like there's room for improvement there; would just need to be careful to make sure the code correctly handles the situation where the site on which the theme is being removed is not equal to the current active site returned by `get_current_blog_id()`.

**Comment by mreishus** [comment] 2022-08-16 20:35
### Two Linked Functions not always called in succession

I've found a Store Admin cancellation of a legacy purchase calls `disable_premium_theme_purchase()` without calling `restore_previously_selected_theme_for_site()` right after.
Locations: wpcom-store-admin-page.php around 220 or wpcom-store-admin.php 337

The canonical `cancel_theme` does run `disable_premium_theme_purchase()` then `restore_previously_selected_theme_for_site()`.

One step for improvement could be either ensuring that every call to `disable_premium_theme_purchase()` is followed by a call to `restore_previously_selected_theme_for_site()`, or to make the first function call the second automatically.

---

### Unable to cancel legacy purchases

I was not able to test by canceling a premium theme purchase in Calypso. It won't let me, and if I patch in the remove purchase button:

```diff
diff --git a/client/me/purchases/remove-purchase/index.jsx b/client/me/purchases/remove-purchase/index.jsx
index 789927b90c..a13ce6c56c 100644
--- a/client/me/purchases/remove-purchase/index.jsx
+++ b/client/me/purchases/remove-purchase/index.jsx
@@ -337,9 +337,11 @@ class RemovePurchase extends Component {
                const { className, purchase, translate, useVerticalNavItem } = this.props;
                const productName = getName( purchase );
 
+               /*
                if ( ! isRemovable( purchase ) ) {
                        return null;
                }
+               */
 
                const defaultContent = (
                        <>
```
The POST to `/wpcom/v2/purchases/1234/delete` fails:
![2022-08-16_15-33](https://user-images.githubusercontent.com/937354/184979847-35106a5c-2977-4926-abce-daa70b51c803.png)

I suppose I need to apply some of the new subscription based patches to try that out.

**Comment by markbiek** [comment] 2022-08-17 12:10
@mreishus Not sure if it applies to this case but I ran into an issue with `restore_previously_selected_theme_for_site` while working on the new theme subscription stuff.

Basically, `restore_previously_selected_theme_for_site` was restoring the theme from the subscription I was cancelling.

D85191-code has an attempt at a fix if it's useful. See line 792 of `store-subscription-cancellations.php` in that diff.

**Comment by DavidRothstein** [comment] 2022-08-17 15:27
>Unable to cancel legacy purchases

It should be possible to cancel as long as the purchase is within the refund window -- there will be a "Cancel and Refund" link on the purchase management page in Calypso.  (If it's no longer refundable, I guess it doesn't let you cancel at all, based on the theory that it's a one-time purchase which you can keep forever without paying more money...)

To test that you probably need to purchase the theme in store sandbox mode, e.g. with a fake credit card.

**Comment by mreishus** [comment] 2022-08-24 18:29
To fix [*Two Linked Functions not always called in succession*] in store admin, I have D86514-code, which is waiting for D86160-code first, to help prevent another p58i-cXE-p2 from happening.

**Comment by mreishus** [comment] 2022-09-07 18:16
D86160-code is complete and merged, so now D86514-code is waiting for review.

**Comment by sixhours** [comment] 2024-03-18 10:09
The proposed fix PR is well out of date and since this hasn't seemed to come up on the user end, I'm closing. Please reopen if it's still a user-facing issue.

**Closed as completed by sixhours** 2024-03-18 10:09 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Normal
