### ISSUE TITLE
Layouts: Repeating Image in Preview

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#39340] opened 2020-02-10 16:36 UTC
Chrome and MacOS. The repeating image looks strange here:

![image](https://user-images.githubusercontent.com/545779/74169451-f6055400-4bf0-11ea-8dce-e8863964f4e3.png)

@iamtakashi @alaczek

**Comment by obenland** [comment] 2020-02-10 20:04
This looks to me like an error with the “Crop image to fill entire column” option in Gutenberg's media & text block. Disabling that fixes it for me (although it doesn't fill the entire column anymore)

**Comment by WunderBart** [comment] 2020-02-25 12:35
> This looks to me like an error with the “Crop image to fill entire column” option in Gutenberg's media & text block.

I can confirm that ☝️. Using that option when the `text` content exceeds the image height causes strange artifacts. Here's another example created outside the template selector:

![image](https://user-images.githubusercontent.com/1451471/75247718-d9f9d900-57d2-11ea-9153-837b7fd39be7.png)

I couldn't find a related issue in Gutenberg so I'll add one now.

**Comment by frontdevde** [comment] 2020-02-25 14:26
I was looking into a related issue, so leaving a driveby comment:
It looks like the styles for the “Crop image to fill entire column” option aren't applying correctly (anymore). The actual image should be visually hidden, while the background-image should be set to `background-repeat: no-repeat` and `background-size:cover`.  When these are applied, it looks as intended.

**Comment by WunderBart** [comment] 2020-02-25 15:27
Thanks, @frontdevde. The styles you mentioned were already there, but the problem was a wrong class name used to style the media container element. The fix is here: https://github.com/WordPress/gutenberg/pull/20439, so feel free to give it a look when you have a sec! 🙏

**Comment by WunderBart** [comment] 2020-02-26 12:15
Fixed in https://github.com/WordPress/gutenberg/pull/20439, will be shipped with Gutenberg v7.7.

**Closed by WunderBart** 2020-02-26 12:15 UTC
Labels: [Goal] Page Templates, [Type] Defect
