### ISSUE TITLE
Update Default Layout for New Sites

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#44151] opened 2020-07-14 18:02 UTC
As a part of the cleanup effort by View team, I cleanup the current default layout for new sites and simplified the block usage in it.

| Before  | After |
| ------------- | ------------- |
|![screencapture-iamtakashinuxtest2020071416915-wordpress-2020-07-14-18_47_07](https://user-images.githubusercontent.com/908665/87459596-7ba78880-c603-11ea-8acc-ff4f10de448c.jpg)|![screencapture-defaultstarter-wordpress-2020-07-14-18_45_03](https://user-images.githubusercontent.com/908665/87459648-8e21c200-c603-11ea-9c96-4fc5292f3265.jpg)|

I've also set up a starter site for it just like other starter designs. https://defaultstarter.wordpress.com/

It'd be great if we can deploy it so that new users are getting a little better layout :)

cc @niranjan-uma-shankar @ianstewart

**Comment by ianstewart** [comment] 2020-07-14 18:18
cc @ramonjd and @josephscott since we were talking about this particular layout and the default images and how they connect with signup+headstart in another thread. No action needed — just a heads up!

**Comment by josephscott** [comment] 2020-07-14 22:56
My concern has been around hotlinking images on new sites.

There has been expressed some concern about the storage usage with uploading them as media to new sites.  The other possibility that I've brought up today is including the headstart images in the theme files.

**Comment by ramonjd** [comment] 2020-07-14 23:01
> My concern has been around hotlinking images on new sites.

If there are still only a couple of images for this starter theme, we _could_ create an exception and always upload **and** fix hotlinks for `/start`

It's another bit of mortar on a wobbly wall though...

**Comment by ramonjd** [comment] 2020-07-29 05:30
There's an issue in relation to the repetition of the post content https://github.com/Automattic/wp-calypso/issues/44430

**Comment by ianstewart** [comment] 2020-10-08 22:56
@apeatling we should see about getting this cleaned up and on the roadmap.

**Comment by simison** [comment] 2020-10-30 14:02
Just updating the copy will help — "edit this page by clicking on the Edit link" doesn't really work in Gutenberg editor, even if it does in some other context:

<img width="800" alt="Screenshot 2020-10-30 at 16 01 19" src="https://user-images.githubusercontent.com/87168/97713989-4008cf80-1ac9-11eb-812d-29b1ae4e3561.png">

Since homepages are viewed in Customizer, Gutenberg, and different previews, it's not currently helpful to have guidance that references UI.

**Comment by iamtakashi** [comment] 2020-10-30 14:23
Sure, I can remove the sentence from https://defaultstarter.wordpress.com/. A shorter body text helps to not having centre aligned paragraph.

**Comment by ianstewart** [comment] 2021-05-07 20:14
@simison with the design picker project progressing … want to just close this one out?

**Comment by alshakero** [comment] 2021-05-19 15:43
Patch here D61607-code

**Comment by StefanNieuwenhuis** [comment] 2021-05-24 07:26
[nitpick/], while testing D61607-code, the background color of the email address subscribe field is dark-gray instead of white.

<img width="841" alt="Screenshot 2021-05-24 at 09 21 48" src="https://user-images.githubusercontent.com/12104589/119311936-ff91be80-bc71-11eb-8c88-c7c57d961c30.png">

Site: Pd5Jgv-5-p2

**Comment by razvanpapadopol** [comment] 2021-05-24 08:42
@StefanNieuwenhuis, can you check also the frontend of the site? Since the site isn't launched yet, we just see the "Coming soon" page? I'm asking because this is how what is in production looks:

- in Editor
<img width="1088" alt="Screenshot 2021-05-24 at 11 40 01" src="https://user-images.githubusercontent.com/14192054/119321145-feb65800-bc84-11eb-8be2-804742f4b75f.png">

- on the Frontend
<img width="1084" alt="Screenshot 2021-05-24 at 11 40 15" src="https://user-images.githubusercontent.com/14192054/119321183-07a72980-bc85-11eb-8357-d5f2d0fabf8d.png">

**Comment by StefanNieuwenhuis** [comment] 2021-05-24 08:45
> @StefanNieuwenhuis, can you check also the frontend of the site? Since the site isn't launched yet, we just see the "Coming soon" page? I'm asking because this is how what is in production looks:

The frontend looks as intended 👍 

### Body content

<img width="1070" alt="Screenshot 2021-05-24 at 10 44 42" src="https://user-images.githubusercontent.com/12104589/119321556-0e31a300-bc7d-11eb-81c9-e68241656c6f.png">

### Email subscription

<img width="822" alt="Screenshot 2021-05-24 at 10 42 55" src="https://user-images.githubusercontent.com/12104589/119321320-cf9be880-bc7c-11eb-96f0-768207c0ed64.png">

**Comment by razvanpapadopol** [comment] 2021-05-28 09:08
@StefanNieuwenhuis, @alshakero, with D61607-code deployed, is this issue completed? ✅

**Closed** 2021-05-28 12:50 UTC
Labels: Page Layouts, Signup, [Type] Enhancement

**Comment by alshakero** [comment] 2021-05-31 10:02
Yes!
