### ISSUE TITLE
Gallery block: images added via "Free photo library" do not appear in the media modal

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#32420] opened 2019-04-19 01:54 UTC
Steps to reproduce:

1. Go to Blog Posts > Add.
1. Add a gallery block.
1. Click the "Media Library" button.
1. Select the Free photo library" option.
1. Search for and select some images.
1. Click the "Copy to media library" button.
1. Check to see whether the images appear in the media modal as expected.
1. Click the "Insert" button.
1. Save the post as a draft.
1. Check to see whether the images are in the media library.

<strong>Result:</strong> images selected for the gallery block using the "Free photo library" option do not show up in the media modal. ([1m41s](https://cloudup.com/cdWLGwpv6yJ))

![free-photo-library](https://user-images.githubusercontent.com/1119271/56400810-06d47b80-6213-11e9-95d4-1afeeb912a1b.png)

![copy-to-media-library-button](https://user-images.githubusercontent.com/1119271/56400809-063be500-6213-11e9-96dc-0910137c662a.png)

<sup>Tested with Firefox 66.0.3 on macOS 10.14.4 on a WP.com Business Plan site `artindesignco.wordpress.com`.</sup>

**Comment by gwwar** [comment] 2019-10-30 23:32
One image selected is updated okay, multiple are added, but are not visible in the media modal until adding other images or a full editor refresh.

**Comment by mmtr** [comment] 2019-11-08 16:49
I cannot reproduce this anymore. Maybe it has been fixed after the update to Gutenberg 6.8.0 which includes a gallery block redesign?

**Comment by davipontesblog** [comment] 2020-06-12 02:24
I cannot reproduce this anymore either. Closing it, if any new reports, please reopen.

**Closed by davipontesblog** 2020-06-12 02:24 UTC
Labels: Editor, [Goal] Gutenberg, [Type] Bug
