### ISSUE TITLE
Flaky E2E: Flaky test on start site flow

### ISSUE THREAD

**Issue by renancarvalho** [Automattic/wp-calypso#70948] opened 2022-12-08 15:19 UTC
### Spec file

packages/calypso-e2e/src/lib/flows/start-site-flow.ts

### TeamCity ID

39538

### Logs

This test has been failing probably because of the `timeout`
Needs further investigation, more context on [this thread](p1670497387258159-slack-C02DQP0FP)

**Comment by karenroldan** [comment] 2022-12-08 15:41
Duplicate of #70945

**Comment by karenroldan** [comment] 2022-12-21 08:11
Closing as duplicate.

**Closed as completed by karenroldan** 2022-12-21 08:11 UTC
Labels: Flaky E2E
