### ISSUE TITLE
Editor: WPCOM - Redirects to WP-Admin with "Calypsoified look" under certain circumstances

### ISSUE THREAD

**Issue by CompChris** [Automattic/wp-calypso#45028] opened 2020-08-19 13:31 UTC
#### Steps to reproduce

1. Starting at URL: Support Session as *** [1]
2. Select site *** [2]
3. Open a page from the editor in Calypso
4. Page redirects with parameter `calypsoify=1` to WP-Admin

See user/site in Internal Oncebin #156254

#### What I expected

Page should open in newer block editor

#### What happened instead

User gets broken WP-Admin page

#### Browser / OS version

Chromium/Edge 83.0.478.37 / macOS 10.14.6 (browser/OS agnostic)

#### Screenshot / Video

![Markup on 2020-08-19 at 09:24:19](https://user-images.githubusercontent.com/6847710/90640273-c9fd0800-e1fd-11ea-8cb2-0f60badd90bd.png)

#### Context / Source

Slack: C02DQP0FP/p1597772323111500

**Comment by CompChris** [comment] 2020-08-19 13:33
cc @cathymcbride / @pablinos / @creativecoder / @glendaviesnz

**Comment by creativecoder** [comment] 2020-08-19 13:53
Note that this issue seems to be specifically caused by the domain configuration for the site. See details at p2MSmN-7ZV-p2

**Comment by cathymcbride** [comment] 2020-09-08 19:58
@CompChris it is my understanding that the original issue is fixed. Are you able to repro this on any other site?

**Comment by cathymcbride** [comment] 2020-09-14 15:35
Spoke to @CompChris and he has not seen this on any further sites. Closing...

**Closed by cathymcbride** 2020-09-14 15:35 UTC
Labels: Calypsoify, [Pri] High, [Type] Bug
