### ISSUE TITLE
Domains: Show explanation why Email Forwarding is not enabled with custom MX records

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#3870] opened 2016-03-08 22:59 UTC
In `wp-admin` it is clearly shown when a domain has custom MX records set up and thus Email Forwarding is not available:

<img width="1060" alt="screen shot 2016-03-08 at 23 49 24" src="https://cloud.githubusercontent.com/assets/3392497/13619307/96759324-e588-11e5-80f3-5c87b20a8245.png">

In Calypso, you can get this information only by looking at the DNS records directly:

<img width="733" alt="screen shot 2016-03-08 at 23 58 23" src="https://cloud.githubusercontent.com/assets/3392497/13619488/b174cf40-e589-11e5-93ec-7a20c65f4d60.png">

We should include the explanation (for Email Forwarding not being avaiable) somewhere in Domain Management.

As reported in `p2MSmN-4A2-p2`.

**Comment by umurkontaci** [comment] 2016-05-11 22:51
Dupe of #3145

**Closed by umurkontaci** 2016-05-11 22:51 UTC
Labels: Domains, [Type] Enhancement
