### ISSUE TITLE
Error when trying to edit a non-FSE theme like Twenty Twenty

### ISSUE THREAD

**Issue by syhussaini** [Automattic/wp-calypso#63479] opened 2022-05-11 01:04 UTC
### Quick summary

When trying to edit the Twenty Twenty theme it throws an error:
![image](https://user-images.githubusercontent.com/8070771/167747871-1dab6ec1-a065-48ba-abca-ca696ecb5268.png)

### Steps to reproduce

1. Activate Twenty Twenty Theme
2. Click on Edit button next to the theme to see the error.

![image](https://user-images.githubusercontent.com/8070771/167747978-6b0ce597-7b94-4183-890a-9b94d7720f7e.png)

### What you expected to happen

I expected the "Customize" button to be there instead of "Edit" button.
The "Customize" button flashes there for a moment when refreshing the page and shows "Edit" button upon fully loading the page.

### What actually happened

When trying to edit, the theme throws an error:
![image](https://user-images.githubusercontent.com/8070771/167747871-1dab6ec1-a065-48ba-abca-ca696ecb5268.png)

### Context

The customer reported that they cannot edit the theme as it keeps throwing the error:

Sorry, you are not allowed to access this page.

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Seems to happen when you switch from an FSE theme to a non-FSE theme. 
Similar reports with Balasana and Astra too

### Browser, operating system and other notes

User Details:

Screen Size: 1536 x 864
Browser Size: 1536 x 713
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

- Switch to another theme, for example Twenty Twenty Two.
- For Atomic sites, you can run a `jetpack sync start` in CLI.

**Comment by sharonlaker19** [comment] 2022-05-22 13:37
I have also had two of the same error when trying to edit the theme now. One was using Astra in 35508391-hc and another was on Balasana in 5234637-zen.

For both users, I was able to resolve by running a `jetpack sync start` in CLI. Seems to be an issue with newly created sites that switch to a non-FSE theme.

**Comment by supernovia** [comment] 2022-05-24 00:56
> Seems to be an issue with newly created sites that switch to a non-FSE theme.

I was able to reproduce this on an older site just by switching to Twenty Twenty.

**Comment by Robertght** [comment] 2022-05-24 10:37
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/62755# as per p1653353850460649-slack-C01UW7SB411

**Comment by Greatdane** [comment] 2022-05-25 05:39
Closing for real!

**Closed as completed by Greatdane** 2022-05-25 05:39 UTC
Labels: Bug
