### ISSUE TITLE
Writting prompt duplicates if the post is copied on a P2

### ISSUE THREAD

**Issue by DavidSaladu** [Automattic/wp-calypso#71001] opened 2022-12-09 13:02 UTC
### Quick summary

If a post on a P2 that has an unused writing prompt is copied, the writing prompt appears duplicated in the new post. (If the post is copied multiple times

### Steps to reproduce

1. Go to p7DVsv-fW8-p2
2. Create a new post
3. schedule it
4. Copy it making a duplicate

### What you expected to happen

The copy should have either no writing prompt or only a single one.

### What actually happened

Each time the post is copied, the writing prompt from the original carries over.

![image](https://user-images.githubusercontent.com/79575219/206708355-137a6cfa-4eb9-42f0-bd7a-1f25f4b32fc9.png)

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

P2

### Browser, operating system and other notes

MacOS Monterrey 12.6
Google Chrome Version 107.0.5304.121 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The "prompts" can be deleted as blocks

**Comment by davemart-in** [comment] 2022-12-12 15:04
@DavidSaladu just clarifying whether you see this as a duplicate of @jordesign's [issue here](https://github.com/Automattic/wp-calypso/issues/70741). In your description, under step 4 you said: "Copy it making a duplicate". I wasn't sure if you manually copy and pasted the blocks to a new post or used the copy link like he outlined. Mind clarifying?

**Comment by DavidSaladu** [comment] 2022-12-13 12:43
It was while using the copy option on the post after it was scheduled. So basically I created a post, ignored the prompt, added the content, and scheduled it. And copied it, and that's where the prompt appeared by duplicate.

I noticed the issue while creating the next coupons for 2023 to be more precise.

**Comment by roo2** [comment] 2022-12-23 05:12
This will no longer be an issue now that we're not showing blogging prompts placeholder by default https://github.com/Automattic/jetpack/pull/27919

**Closed as completed by roo2** 2022-12-23 05:12 UTC
Labels: Bug, [Pri] Low, [Platform] Simple
