### ISSUE TITLE
Editor: Permalink for home shows incorrect URI for homepage

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/wp-calypso#4516] opened 2016-04-04 23:00 UTC
I created a new WordPress.com site to do some testing, and one of the first things I did was edit the homepage. 

When I did, I noticed its permalink read "https://home":
<img width="190" alt="screen shot 2016-04-04 at 21 45 46" src="https://cloud.githubusercontent.com/assets/376315/14266532/db46afea-fac0-11e5-8b61-7133ae666d04.png">

That's not right!

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/page/thestrawberrymilkshakes.wordpress.com/2
2. Edit the homepage. 
3. Check out the permalink.

#### What I expected
Permalink should have been "https://thestrawberrymilkshakes.wordpress.com"

#### What happened instead
Permalink read "http://home"

#### Browser / OS version
FirefoxDeveloperEdition / OS X El Capitan

#### Screenshot / Video
<img width="190" alt="screen shot 2016-04-04 at 21 45 46" src="https://cloud.githubusercontent.com/assets/376315/14266532/db46afea-fac0-11e5-8b61-7133ae666d04.png">

**Comment by jeremeylduvall** [comment] 2016-04-10 19:19
Looks like this is a duplicate of #3563. Closing in favor of that one.

**Closed by jeremeylduvall** 2016-04-10 19:19 UTC
Labels: Editor, [Type] Bug
