### ISSUE TITLE
Search failing for author list on posts when using the Block Editor

### ISSUE THREAD

**Issue by nickpagz** [Automattic/wp-calypso#46548] opened 2020-10-17 19:29 UTC
#### Steps to reproduce

Not able to replicate this as it requires several authors to be added to the site, so referencing the user's site.

1. Starting at URL: [https://wordpress.com/posts/my/blk-pediatric-practice.com](https://wordpress.com/posts/my/blk-pediatric-practice.com)
2. Click on **Add new Post**
3. In the new post, click in the **Author** search box and start typing an existing author.

#### What I expected and what happens instead
Searching for an existing author mostly fails (watch the video below). Whether they're in the list or not, the search only seems to turn up results for the admin, at least on this site.

Video:
[https://d.pr/v/Jez93j](https://d.pr/v/Jez93j)

**PS.** This only happens in the Block editor. All authors are visible in classic and quick edit.

#### Browser / OS version
Chrome, MacOS. User also sees same result in Safari.

#### Context / Source

#user-report

**Comment by retnonindya** [comment] 2020-11-04 04:00
Hello! It seems like I have the same issue too (user report). In this case, a user with public display name "Guest Author". 

Feel free to ping me if you folks need more info. Thank you!

**Comment by samiff** [comment] 2020-11-20 20:26
Another in 3507080-zd-woothemes

User would like to know when this issue is resolved.

**Comment by obenland** [comment] 2021-01-29 21:44
Duplicate of #46536.

**Closed by obenland** 2021-01-29 21:44 UTC
Labels: Editor, [Type] Bug
