### ISSUE TITLE
Gutenberg: Post Content Lost After Editing Image in Media Modal 

### ISSUE THREAD

**Issue by Aurorum** [Automattic/wp-calypso#34281] opened 2019-06-25 18:25 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/post/
2. Add a title, add some text
3. Add an Image Block
4. Select Media Library 
5. Click an image
6. Select "Edit"
7. Select "Edit Image"
8. Click "Cancel" or "Done"
9. Insert
10. Post content lost

![ezgif-3-b5fcf90a8f41](https://user-images.githubusercontent.com/43215253/60123207-cd723c00-977e-11e9-9951-76c4f1bd539e.gif)

#### What I expected

I'd return to the post with the new image.

#### What happened instead

All post content was wiped. 

#### Browser / OS version

Chrome 75 on macOS

#### Context / Source

Accidentally came upon whilst writing a post. :)

**Comment by ivan-ottinger** [comment] 2019-07-08 07:57
Another report #2162007-zen

**Comment by tanjoymor** [comment] 2019-07-13 19:48
Another case: #13648781-hc

I agree with Ivan... this is a pretty serious issue.

**Comment by tanjoymor** [comment] 2019-07-14 16:45
This is a video that shows how the image itself won't insert after editing it:

https://monosnap.com/file/Uvl17d7Q5QKdeqRUxv6EhD0cZusn0H

And this video demonstrates how the content goes missing if you add/edit an image before an autosave/save has been performed:

https://monosnap.com/file/CICMElrhsYmpViwySJdUzCMVS5ZwLS

**Comment by tanjoymor** [comment] 2019-07-14 17:32
Have also confirmed that it doesn't happen in wp-admin because the interface is different. When you're inserting images through wp-admin the edit button is on the right and opens in a new window rather than in the iframe.

**Comment by glendaviesnz** [comment] 2019-07-22 00:37
Have been able to replicate this on a local calypso dev instance using the above steps. 

Additional notes:

- It is not necessary to actual edit the image in the image editor window - just opening the editor window and clicking done replicates the bug
- On a new post all content is lost, but on an existing post any new content added after openining the post to edit is wiped - existing saved content remains
- There are no console errors after clicking on `Insert`

**Comment by xpurichan** [comment] 2019-07-22 02:28
I had another report in 2174695-zd. I had actually opened a new bug report about it here, but closed it after being notified of this one. My old report:

https://github.com/Automattic/wp-calypso/issues/34665

**Comment by glendaviesnz** [comment] 2019-07-22 02:55
After a bit more debugging I have narrowed down the issue to the loading of the Edit Image dialog. The post content is actually wiped as soon as the Edit Image dialog is opened, not on the clicking of the Insert button. 

Opening the Edit image dialog causes two re-renders of the CalypsoifyIframe component - on the second re-render the editor content is wiped. Haven't managed to work out why yet.

**Comment by glendaviesnz** [comment] 2019-07-22 19:40
So the exact cause of the issues is that at https://github.com/Automattic/wp-calypso/blob/master/client/gutenberg/editor/calypsoify-iframe.tsx#L575 `isRequestingSite( state, siteId )` returns true when the image edit dialog loads, which sets `shouldLoadIframe` to false and this causes a reload of the iframe and the loss of content.

Now just need to work out how to stop this happening.

**Comment by aisajib** [comment] 2019-07-23 19:02
Just had a user report this problem to us at 10118046-hc. They said the problem started about two weeks ago. 

I've offered to follow up with them when this is fixed.

**Closed** 2019-07-24 01:56 UTC
Labels: [Pri] High, [Type] Bug

**Comment by glendaviesnz** [comment] 2019-07-24 02:07
Just pushed an update to production which should fix this issue in both WP.com Simple Sites and JetPack sites.
