### ISSUE TITLE
Post Checkout: do not display free domain tip if the purchase already included a free domain

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2503] opened 2016-01-16 15:02 UTC
Raised by @stephanethomas 

Steps to reproduce:

1. Start at https://wordpress.com/domains/add
1. Click "Add Domain"
1. Enter a domain and click "Add" or select a suggested domain
1. Click "No thanks"
1. Click "Upgrade now" in the notice at the top of the Cart sidebar on the left
1. Fill out the form and click "Add Privacy Protection"
1. Complete the payment
1. Click "Add Free Domain"
1. Note you are taken back to https://wordpress.com/domains/add

<strong>Result:</strong> the thank you page says to add a free domain even though I've already just added one.

![screen shot 2016-01-16 at 09 55 26](https://cloud.githubusercontent.com/assets/1119271/12372986/1c384bc0-bc38-11e5-8608-b212151a9b6b.png)

**Comment by fabianapsimoes** [comment] 2016-03-15 16:21
Duplicate of #4040

**Closed by fabianapsimoes** 2016-03-15 16:21 UTC
Labels: Post Checkout, [Type] Bug
