### ISSUE TITLE
Double footers on FSE

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#60808] opened 2022-02-03 10:08 UTC
### Quick summary

On one of the pages on my own site the footer credit appears twice.

### Steps to reproduce

<img width="1395" alt="Markup 2022-02-03 at 09 59 24" src="https://user-images.githubusercontent.com/13706336/152320791-0374d96f-5b52-4a21-9022-81a81bb2d787.png">

I couldn't see where to remove it, or why two credits were appearing.

There is a footer block in the template itself 

The page is here - https://publicspeakerworld.com/769-2/

<img width="1863" alt="Markup 2022-02-03 at 10 06 45" src="https://user-images.githubusercontent.com/13706336/152321888-0f4fa495-d4e7-4af4-9707-adca2f512f11.png">

The site uses Zooologist.

### What you expected to happen

One footer to appear

### What actually happened

Two footers appear

### Context

Own site - https://publicspeakerworld.com/769-2/

### Simple, Atomic or both?

Atomic

### Available workarounds?

No but the platform is still usable

**Comment by Greatdane** [comment] 2022-02-25 07:56
@rickmgithub are you able to replicate this issue on another site? I am struggling to replicate it here..

**Comment by formosattic** [comment] 2022-03-01 08:51
I think I've experienced it before when editing the default theme footer in FSE, but can't reproduce it anymore.

Currently, the Footer Credit setting in Customize gets applied correctly.

Closing for now, but please re-open if the issue still happens.

**Closed as completed by formosattic** 2022-03-01 08:51 UTC
Labels: Bug
