### ISSUE TITLE
Semantic Template Parts: Area value is null

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#50015] opened 2021-02-11 22:35 UTC
### Description
The area taxonomy for template parts is returning null when we create a new, custom template part, or when we update a theme provided template part.

<img width="386" alt="Screen Shot 2021-02-11 at 12 23 38 PM" src="https://user-images.githubusercontent.com/5414230/107706727-9dd6b700-6c75-11eb-93e5-b1eab8e40520.png">

### Steps to reproduce the behavior

1. Sandbox a simple site with the tt1-blocks theme
2. Patch the sandbox with these changes
3. Upload the latest commit for gutenberg master into the sandbox
  - This will include Addie's changes from her corresponding Gutenberg PR  
  - Follow instructions under Gutenberg Enters the Sandbox (see PCYsg-t5D-p2)
4. Checkout gutenberg master locally
5. Open `packages/block-library/src/template-part/edit/index.js` and add `console.log( { entityRecord } );` to line 57
6. Run requestly  (see pc9Uba-1F-p2)
7. Add this block of code to `wpcom/public_html/wp-content/themes/pub/tt1-blocks/experimental-theme.json` in the sandbox
   
```
	"templateParts": {
		"header": {
			"area": "header"
		},
		"footer": {
			"area": "footer"
		}
	},
```
8. Refresh the page and open the dev console
  - Evaluate the `entityRecord` from console logs
  - Ensure that there is an area attribute with the appropriate header or footer value

**Comment by david-szabo97** [comment] 2021-04-19 12:25
I couldn't reproduce. We had a couple of Gutenberg updates since this issue. So this might be fixed by now.

**Comment by Addison-Stavlo** [comment] 2022-06-22 19:44
closing as this seems to have been resolved

**Closed as completed by Addison-Stavlo** 2022-06-22 19:44 UTC
Labels: Bug
