### ISSUE TITLE
Editor: Cover block with button and text breaks on reload

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37053] opened 2019-10-24 22:55 UTC
A cover block with text and a button will break on reload of the editor saying that there is unexpected or invalid content:

<img width="1002" alt="Screen Shot 2019-10-24 at 3 53 45 PM" src="https://user-images.githubusercontent.com/1464705/67531186-7ae65500-f676-11e9-9ca0-7155a86f19a7.png">

The only way to fix this is to hit the three dots menu, and select "Attempt block recovery", which returns it to this:

<img width="994" alt="Screen Shot 2019-10-24 at 3 56 00 PM" src="https://user-images.githubusercontent.com/1464705/67531257-cef13980-f676-11e9-90f8-f88c46413bfb.png">

Hitting the Resolve button shows this change:

<img width="1107" alt="Screen Shot 2019-10-24 at 3 54 58 PM" src="https://user-images.githubusercontent.com/1464705/67531228-ac5f2080-f676-11e9-805d-4f481e952f97.png">

There is nothing unusual about this setup, and no custom markup. You can reproduce the error by accessing this post. Ping @apeatling if you can't get access to this post:

https://wordpress.com/block-editor/page/testsiteandyp2019.wordpress.com/2

**Comment by mmtr** [comment] 2019-12-23 13:03
Seems that the affected block is actually the cover block rather than the hero block. I updated the title/summary to clarify that.

Anyway, I'm unable to reproduce this in both a Simple or an Atomic site. This is the block markup I used:

```html
<!-- wp:cover {"url":"https://***/wp-content/uploads/2019/12/accessories-accessory-bag-322207.jpg","id":17,"dimRatio":60,"overlayColor":"foreground-dark","align":"full"} -->
<div class="wp-block-cover alignfull has-background-dim-60 has-foreground-dark-background-color has-background-dim" style="background-image:url(***/wp-content/uploads/2019/12/accessories-accessory-bag-322207.jpg)"><div class="wp-block-cover__inner-container"><!-- wp:heading {"align":"center","level":1} -->
<h1 class="has-text-align-center">Heading</h1>
<!-- /wp:heading -->

<!-- wp:button {"borderRadius":50,"gradient":"blush-bordeaux","align":"center"} -->
<div class="wp-block-button aligncenter"><a class="wp-block-button__link has-background has-blush-bordeaux-gradient-background" href="https://wordpress.com" style="border-radius:50px">WP.com</a></div>
<!-- /wp:button --></div></div>
<!-- /wp:cover -->
```

 @apeatling is this still happening on your test site? If so, could you please invite me to it, so I can check the exact markup?

**Comment by gwwar** [comment] 2020-01-07 18:25
I'll go ahead and close this out for now. @apeatling feel free to reopen if this is still happening

**Closed by gwwar** 2020-01-07 18:25 UTC
Labels: Editor, [Type] Bug
