### ISSUE TITLE
PROXIED V2 banner appears on all Legacy Widgets in Block Widgets

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#54985] opened 2021-07-28 20:26 UTC
### Steps to reproduce the behavior

1. Be proxied/logged in (like a Happiness Engineer, for example)
2. Go to Appearance - Customize - Widgets - Select a location - + - Legacy Widget - Add one and set its options (any legacy widget)
3. View the widget. A large PROXIED V2 banner will cover up the top portion of it. 

![image](https://user-images.githubusercontent.com/30731356/127390879-69a801ba-8cc1-401b-bc68-b34481a90f1e.png)

#### What I expected to happen
To see the widget
#### What actually happened
The PROXIED V2 banner covers up portions of widgets.
#### Does this happen on simple or atomic sites or both?
Atomic is the only one with block widgets currently.
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/30731356/127390947-4f3b06ba-c1cc-4363-b529-c40b2e8a31ce.png)

**Comment by synora** [comment] 2021-07-30 19:30
Duplicate of  54756-gh-Automattic/wp-calypso. 
Merge happening in 733-gh-Automattic/wpcomsh

**Closed as completed by synora** 2021-07-30 19:30 UTC
Labels: Bug, Triaged
