### ISSUE TITLE
Carousel Not Loading on Gallery Blocks Added After Gutenberg 6.5 Update

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#36406] opened 2019-09-27 20:52 UTC
#### Steps to reproduce

Choose a simple site (should all have Gutenberg 6.5 now). Confirm that the carousel option is enabled under WP Admin > Settings > Media. 

1. Add a new post
2. Insert a Gallery Block and add images
3. Set the "link to" setting and publish the post
4. View the gallery on the published page

#### What I expected

Setting the "link to" option to "Media File" should open the images in the carousel, based on this support document:

https://en.support.wordpress.com/wordpress-editor/blocks/gallery-block/#linking

#### What happened instead

Setting the "link to" settings had the following results:

None = nothing opens, images not clickable
Media File = opens the individual media file
Attachment Page = mixed results. On some posts this opens the carousel, and on others I get non-clickable images.

Tested on Twenty Nineteen and on Lodestar (that was theme from the user-report)

#### Browser / OS version

Tested on Firefox 69.0.1 and Chrome 77.0.3865.90

#### Screenshot / Video - Example/Test Pages

**Simple Site (free plan):** 
The gallery set to Attachment Pages loads the carousel
https://test1234444blog.wordpress.com/testcarousel/

Then another page on the same site set to Attachment Pages has non-clickable images
https://test1234444blog.wordpress.com/new-gallery-page/

**Simple Site (free plan):**
The gallery set to Attachment Pages loads the carousel here also:
https://test829463584.wordpress.com/2019/09/27/testing-gallery-blocks/

**Jurassic Ninja Site w/ Gutenberg 6.5 plugin:**
Gallery set to Attachment Pages has non-clickable images
https://spotty-polecat.jurassic.ninja/2019/09/27/gallery-test/

#### Context / Source

#user-report in #15519887-hc

**Comment by kwight** [comment] 2019-09-27 21:57
It looks like https://github.com/WordPress/gutenberg/pull/17101 modified markup, that is likely important to the Jetpack carousel code. Investigating.

**Comment by mikeicode** [comment] 2019-09-27 22:00
Ran into this on 15348312-hc also confirmed on a test site

**Comment by kwight** [comment] 2019-09-27 22:03
Jetpack PR where carousel support was added: https://github.com/Automattic/jetpack/pull/10646/. This references `ul` markup, which is no longer used by the Gallery block as of https://github.com/WordPress/gutenberg/pull/17101, so that's our culprit.

**Comment by kwight** [comment] 2019-09-27 22:42
Jetpack fix in progress: https://github.com/Automattic/jetpack/pull/13582

**Comment by brezocordero** [comment] 2019-09-28 16:01
Also reported on 2383880-zen

**Comment by KokkieH** [comment] 2019-09-29 07:31
Another report in https://en.forums.wordpress.com/topic/gallery-not-clickable/ - noting for follow-up once fixed.

**Comment by ivan-ottinger** [comment] 2019-09-29 08:20
Another report in #2384009-zen.

**Comment by KokkieH** [comment] 2019-09-29 09:16
https://en.forums.wordpress.com/topic/wordpress-image-wont-display-as-carosel/

**Comment by joweber123** [comment] 2019-09-30 01:36
I have a user reporting the same issue but from a Simple site using the Classic editor.  I am able to reproduce the same on a test site of my own.  When the carousel option is selected under layout options, the link to "Attachment page" and "Media file' both do not open to the selected option.  

2387435-zen

**Comment by kriskorn** [comment] 2019-09-30 05:28
Another report in 2387318-zen.

**Comment by CoachBirgit** [comment] 2019-09-30 12:40
Another report in #2386558-zen

**Comment by CoachBirgit** [comment] 2019-09-30 12:45
Another report in #2386416-zen

**Comment by nickpagz** [comment] 2019-09-30 14:07
Received another report in #2388326-zen

However, an additional issue that appeared on this user's site - regardless of the attachment setting, if the gallery includes only one image, the carousel will not open (image is not clickable - except for "link to media file" which opens in a new page).
Hopefully this also gets resolve in the fix.

**Comment by tijosh** [comment] 2019-09-30 14:16
Another report of this in #14065512-hc

**Comment by tijosh** [comment] 2019-09-30 14:32
Another report in #12697591-hc 

No follow up needed

**Comment by automattic-ian** [comment] 2019-09-30 15:07
new report in: #14942807-hc
follow up requested in: #2389144-zen

**Comment by jeherve** [comment] 2019-10-01 07:13
This should be fixed on WordPress.com already. A fix will be included in Jetpack in version 7.9, scheduled to be released in early November.

**Closed by jeherve** 2019-10-01 07:13 UTC
Labels: [Type] Bug

**Comment by CoachBirgit** [comment] 2019-10-01 10:53
another report in #2388003-zen

**Comment by kriskarkoski** [comment] 2019-10-03 12:05
@jeherve Would this fix be in Jetpack beta? I'm trying to brainstorm how to fix this on Atomic so they don't have to wait a month since the fix is already done, right?

**Comment by jeherve** [comment] 2019-10-03 12:39
@kriskarkoski It's in the current Bleeding Edge, yes. Here is the fix:
https://github.com/Automattic/jetpack/pull/13582

**Comment by tijosh** [comment] 2019-10-05 18:46
@jeherve Noting that with Atomic being on Gutenberg 6.6 now, this gallery carousel issue is starting to pop up in tickets for Atomic sites. Is there an ETA on when the above fix will land on Atomic sites?

**Comment by kriskarkoski** [comment] 2019-10-05 19:19
@tijosh It will be early-November with the next Jetpack release unless we do a point release. Details at p9F6qB-496-p2
