### ISSUE TITLE
Marketplace: Visiting a plugin in the global plugins view results in a hidden update routine

### ISSUE THREAD

**Issue by ebinnion** [Automattic/wp-calypso#92241] opened 2024-07-01 14:48 UTC
### Quick summary

If I visit a specific plugin in the global plugins view, I then see a set of notices that indicate plugins are being updated followed by some other notices that indicate success or error.

![CleanShot 2024-07-01 at 09 40 11@2x](https://github.com/Automattic/wp-calypso/assets/1126811/f294f074-c7bd-4c27-80ce-3affa077e6c7)
![CleanShot 2024-07-01 at 09 40 29@2x](https://github.com/Automattic/wp-calypso/assets/1126811/81bdae18-7d48-44dc-adc9-59be82ce747e)
![CleanShot 2024-07-01 at 09 44 10@2x](https://github.com/Automattic/wp-calypso/assets/1126811/0938f0bc-fe9b-4b4d-9b99-61974a3ab116)

There are some issues with this:

1. It's unclear to me what's getting updated. Does this update routine only happen when I view Calypso? Or, does it happen other times?
2. The notice that plugins are updating seems to trigger from the moment that I hit the page. Even before the site is loaded. See second screenshot above.
3. Even when I don't have plugins on a site, the notice says it's updating the site. 3rd screenshot above ... I don't use WP Bakery anywhere to my knowledge.

Overall, the UX here feels off and I don't believe that it's been updated since we've explored the a4a panel, scheduled plugin updates, core auto-updates, etc. If I recall, the first versions of this UX were very much driven by Calypso with API calls. Is that still the case?

### Steps to reproduce

1. Go to global plugins views at https://wordpress.com/plugins.
2. Click a single plugin.
3. See that auto-updates notice is appearing.

### What you expected to happen

I don't think that auto-updating as a user visits a UI is the right UX nor do I think a notice is the right UI. 

### What actually happened

A notice appeared that confused me.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by lupus2k** [comment] 2024-07-02 21:49
I was able to reproduce an error message, but not the same as the first screenshot:
![image](https://github.com/Automattic/wp-calypso/assets/402286/c8ed001a-aa2d-448b-a65a-56e6014fc8e0)

I tried to reproduce the "an error occurred while updating" error without success.

The second message is caused by the Jetpack beta / Jetpack dev / Mu WPcom Plugin. Those plugins fail to update, and, apparently, it should not appear in the site plugins, like in the `/plugins/:site` endpoints.

I added more details here: p1719866457103339-slack-CDLH4C1UZ

**Comment by lupus2k** [comment] 2024-07-11 13:58
Error messages were fixed [here](https://github.com/Automattic/wp-calypso/pull/92284) and [here](https://github.com/Automattic/dotcom-forge/issues/8084), about the plugins not updating, I created a new issue [here](https://github.com/Automattic/dotcom-forge/issues/8202#top)

**Comment by davemart-in** [comment] 2024-07-15 20:30
Closing this out since it's been fixed.

**Closed as completed by davemart-in** 2024-07-15 20:30 UTC
Labels: Bug, Needs triage
