### ISSUE TITLE
New Onboarding: Missing starter pages and other issues

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#53545] opened 2021-06-09 12:08 UTC
### Steps to reproduce the behavior

1. With your account's interface set to English, create a new site
2. Go over the new onboarding flow
3. Finish the site creation, with a free address, and free plan
4. Check the Pages of your new site

#### What I expected to happen
To see the starter pages we used to have, Home, Blog, Contact, and About.

#### What actually happened
It seems that the starter pages are created based on the template you select on the onboarding, which seems to have either only a Home page, or Home and Blog. No Contact and About anymore.

This happens on this new onboarding flow:

![Onboarding 1](https://user-images.githubusercontent.com/16104522/121348732-133e5580-c8ff-11eb-93a9-0b4c93cbe7da.jpg)

While if I start a new site with another language, Portuguese for example, I get this onboarding flow:

![Onboarding 2](https://user-images.githubusercontent.com/16104522/121348867-41bc3080-c8ff-11eb-9d3e-3296347e9f8e.jpg)

On this flow, I get the 4 pages: Home, Blog, Contact, and About. When checking the Contact page, the buttons on the Social Icons block are duplicated:

![Onboarding 3](https://user-images.githubusercontent.com/16104522/121349345-c60eb380-c8ff-11eb-89d0-f24eeb8fed03.jpg)

**Comment by autumnfjeld** [comment] 2022-02-13 22:03
@carinapilar  Thank you for filing this issue.  😄  Some info that will hopefully help explain what you observed:

> While if I start a new site with another language, Portuguese for example, I get this onboarding flow:

This is correct behavior.   The /new flow (which is the onboarding flow you are describing here) is for English language only and only for existing customers via the "Add a new site" button.   Other users are directed to the /start flow.  You can try both of these yourself via wordpress.com/start and wordpress.com/new.   It is admittedly confusing, this P2 might help:  pdgK6S-vG-p2

> It seems that the starter pages are created based on the template you select on the onboarding, which seems to have either only a Home page, or Home and Blog. No Contact and About anymore.

I believe this is also the intended behavior with the Design Picker in the /new flow.

I'm closing this issue because we are deprecating the /new flow soon in favor of the /start flow experience.
pbxNRc-1jD-p2
pbxNRc-1eh-p2


cc: @roo2  could fact check my statements. :)

**Closed as completed** 2022-02-17 19:01 UTC
Labels: Bug, [Pri] Normal, [Feature Group] Signup & Site Onboarding, [Goal] New Onboarding, Triaged
