### ISSUE TITLE
Themes: theme info page for the current theme does not load completely

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#12743] opened 2017-04-03 18:15 UTC
Steps to reproduce:

1. Go to Themes.
1. Click the Info button to the right of the current theme in the first heading bar.
1. Or, search for the current theme, click the ellipsis menu, then click Info.
1. (You may need to click cmd+shift+R to trigger the problem.)

<strong>Result:</strong> the theme info page doesn't load properly. 

![screen shot 2017-04-03 at mon apr 3 12 09 49 pm](https://cloud.githubusercontent.com/assets/1119271/24623846/1a0347d8-1867-11e7-95b7-c01ff00773c5.png)
<sup>Seen at https://wordpress.com/theme/boardwalk/madefortesting347.wordpress.com using Safari 10.1 on Mac OS X 10.12.4 logged in with test account user157, unproxied.</sup>

![screen shot 2017-04-03 at mon apr 3 12 12 19 pm](https://cloud.githubusercontent.com/assets/1119271/24623853/2072d89a-1867-11e7-95c9-f607a5159a12.png)
<sup>Seen at https://wordpress.com/theme/twentyfifteen/design5279g.wordpress.com using Firefox 52.0.2 on Mac OS X 10.12.4 logged in with test account design5279, unproxied.</sup>

Found while #manual-testing the desktop app.

**Comment by folletto** [comment] 2017-04-03 18:23
I can reproduce on my test .com site, current theme even when hit directly typing the URL. 
No errors in console seems related.

**Comment by alisterscott** [comment] 2017-04-03 18:30
In a development environment I see a console warning on this page which could be related:

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ThemesSelectionWithPage component.`

**Comment by ockham** [comment] 2017-04-03 18:32
> I can reproduce on my test .com site, current theme even when hit directly typing the URL.

I think I can only repro for the currently active theme. Can you try direct-hitting an inactive one?

> No errors in console seems related.

The `customer-dev.mediawallahscript.com` stuff seems correlated tho...

**Comment by alisterscott** [comment] 2017-04-03 18:33
There is also another console error I see sometimes locally, could this issue be related to server-side rendering of the theme information?

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) " data-reactid="1"><!-- react-empty: 2 -
 (server) " data-reactid="1"><header id="header" c
```

**Comment by folletto** [comment] 2017-04-03 18:35
It happens only on the **single site view**, **current active theme** for me.

**Comment by folletto** [comment] 2017-04-03 18:36
> The customer-dev.mediawallahscript.com stuff seems correlated tho...

I meant in my console. :)
In the above I can't tell. Seems a tracking script.

**Comment by ockham** [comment] 2017-04-03 18:46
@alisterscott That's a React reconciliation error (which is known, and can't be fixed entirely in the dev console) -- should be unrelated.

**Comment by ockham** [comment] 2017-04-03 18:50
Okay, so we're apparently stuck at `loading` stage because `this.props` doesn't have a `screenshots` field like it should for a WP.com theme...

**Comment by ockham** [comment] 2017-04-03 18:55
...which is due to a `THEMES_REQUEST_SUCCESS` Redux action fired (as `receiveThemes`) in response to a `requestActiveTheme` action, I think. The action object returned from the active theme endpoint has fewer attrs than the "full" theme endpoints -- it's missing `screenshots`, among others.

**Comment by ockham** [comment] 2017-04-03 19:00
And instead of getting merged into the existing object, the latter is overridden. We added the logic to obtain info from the active theme endpoint to have at least some basic data (enough for the 'Current Theme Bar') available for retired themes. But this is a very undesired side-effect. I wonder for how long this has been going on...

**Comment by ockham** [comment] 2017-04-03 19:25
We might be able to use `QueryManager`'s [`patch`](https://github.com/Automattic/wp-calypso/blob/7c49c26183594f906ddcc328ea693b7fcec5633e/client/lib/query-manager/index.js#L215) option here. However, that might mean we'll have to add an additional param to `receiveThemes` to indicate whether to `patch` or not.

**Closed** 2017-04-04 11:37 UTC
Labels: Themes, [Pri] High, [Type] Bug
