### ISSUE TITLE
Editor Help section is misplaced in OS X Safari

### ISSUE THREAD

**Issue by kwonye** [Automattic/wp-calypso#6842] opened 2016-07-16 02:03 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Click "new post" button in top-left of masterbar
3. Notice on the bottom left that the help option is partially hidden/misplaced

#### What I expected
Help link/icon below discussion options

#### What happened instead
Help link/icon underneath location settings

#### Browser / OS version
Safari 9.1.1 / OS X 10.11.5

#### Screenshot / Video
<img width="274" alt="screen shot 2016-07-15 at 8 54 27 pm" src="https://cloud.githubusercontent.com/assets/1158819/16892148/5233fcda-4acf-11e6-95d7-7b7581897c76.png">

**Comment by timmyc** [comment] 2016-08-15 20:58
So it appears this is not related to the editor sidebar, but is the [SidebarFooter](https://github.com/Automattic/wp-calypso/blob/master/client/layout/sidebar/footer.jsx) component.  Screen grab of the component in chrome vs safari, with the more options accordion expanded:

![new_post_ _trout_bummin_ _wordpress_com_and_new_post_ _testingtimmy2_wordpress_com_ _wordpress_com](https://cloud.githubusercontent.com/assets/22080/17679428/37ab0406-62f0-11e6-9e79-8323b1d39abd.png)

**Comment by timmyc** [comment] 2016-08-15 22:27
Oh it appears this is a duplicate of #6615, note the comment [here](https://github.com/Automattic/wp-calypso/issues/6615#issuecomment-235411136) - closing this one out.

**Closed by timmyc** 2016-08-15 22:27 UTC
Labels: Navigation, [Type] Bug, [Type] Janitorial
