### ISSUE TITLE
Site Editor: "invalid parameter(s)": post error when uploading images

### ISSUE THREAD

**Issue by wiesenhauss** [Automattic/wp-calypso#85732] opened 2023-12-22 18:57 UTC
### Quick summary

When trying to upload images in the Site Editor, an "invalid parameter(s)" error message appears, and the image fails to upload. This issue appears to be specific to the Site Editor; uploading images still works fine in the post/page editor and the Media Library. I've tested this with various Full Site Editing (FSE) themes, and the error persists regardless of the theme used.

### Steps to reproduce

1. Load the Site Editor (Appearance > Editor) 
2. Add an Image or Media & Text block (or any other block that allows for image uploads)
3. Try to upload an image file

### What you expected to happen

The image is correctly uploaded and displayed.

### What actually happened

User sees "invalid parameter(s)" error
<img width="1323" alt="Markup 2023-12-22 at 15 32 31" src="https://github.com/Automattic/wp-calypso/assets/99455043/8dd283b9-768b-4400-9d77-a92e7d250edd">

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by liviopv** [comment] 2023-12-26 11:32
📌 ACTIONS
- Closed as duplicate

📌 Message to Author
@wiesenhauss this is a duplicate of https://github.com/Automattic/wp-calypso/issues/85373 but good finding that this is affecting all image uploads.

**Closed as completed by liviopv** 2023-12-26 11:32 UTC
Labels: Bug, [Pri] High, [Feature] Full Site Editor, [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience
