### ISSUE TITLE
Atomic: User management page always opens the classic WP Admin interface

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#79155] opened 2023-07-09 02:28 UTC
### Quick summary

If you click **Users** on Atomic sites, the user management page always opens the classic WP Admin interface no matter which view you choose as a default view(either Default view or Classic view).

### Steps to reproduce

1. Open the dashboard of any Atomic site.
2. Click Users.
3. Click on the View tab in the upper right corner and select the **Default view**(Calypso interface).
4. Once the user management page in the Default view was loaded, click Users in the left sidebar again.

### What you expected to happen

It opens the user management page in the Default view(https://wordpress.com/people/team/XXXXX) respecting the preferred view you selected.

![Screen Shot on 2023-07-09 at 11:29:57](https://github.com/Automattic/wp-calypso/assets/32432463/ca4edaab-cdeb-44e3-a47c-d5bcabfd006b)

### What actually happened

It opens the user management page in the classic view(https://XXXXX/wp-admin/users.php) ignoring the preferred view you selected.

![Screen Shot on 2023-07-09 at 11:30:26](https://github.com/Automattic/wp-calypso/assets/32432463/265a57ff-8e9a-44b3-a79a-8ad7a0c4bc74)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

**Workaround:**
We can share a direct URL for those needing access to the Default view - https://wordpress.com/people/team/XXXXX

**Comment by retnonindya** [comment] 2023-07-09 04:09
I can replicate it on my test site too. At first, I thought the WP Admin link for Users appeared because I accessed it while I'm in WP Admin area. However, when I'm in My Home area (Calypso) and I tried accessing "Users", I see it linking to the WP Admin link.

![Screenshot 2023-07-09 at 12 08 52 PM](https://github.com/Automattic/wp-calypso/assets/44726232/40d61b2e-3e30-455a-8df2-e4c888bff6aa)

**Comment by hacchism** [comment] 2023-07-11 05:09
Another report: 6518541-zen

User unintendedly added a few members to their site through the Classic view so the newly-added members were having issues getting into the site.

**Comment by karenroldan** [comment] 2023-07-12 16:40
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
The issue can be replicated exactly as described above. The default link to Users is `/wp-admin/users.php` regardless if you choose to view the Calypso interface.

📌 ACTIONS
- Assigned to @Automattic/caribou 

📌 Message to Author
Thank you for reporting, @hacchism! 

> User unintendedly added a few members to their site through the Classic view so the newly-added members were having issues getting into the site.

This seems to be the side effect of this issue. Could you kindly please create a separate issue for this? Thank you!

**Comment by vishnugopal** [comment] 2023-07-20 05:24
I can no longer reproduce this. @karenroldan Can you check if this is still the case?

**Comment by karenroldan** [comment] 2023-07-20 12:54
📌 REPRODUCTION RESULTS
- **Tested on Simple** – Could Not Replicate
- **Tested on Atomic** – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Looks like the issue no longer exists! 
- The Users page loads the selected view as expected.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message

@vishnugopal, thanks for checking. I can't replicate it anymore.

**Closed as not planned by karenroldan** 2023-07-20 12:54 UTC
Labels: Bug, [Pri] Low, Triaged, [Feature] User Management, [Platform] Atomic
