### ISSUE TITLE
Checkbox in the Form Alignment off (extra box showing) - Obsidian theme

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/wp-calypso#55340] opened 2021-08-10 22:43 UTC
### Steps to Reproduce

* Set the theme to Obsidian. 
* Create a post or page.
* Add the Form Block.
* Add a Checkbox Block.
* Add Items.
* Preview or publish.
* Notice and extra checkbox appears, and the other checkbox alignment is off. 
* Change the theme to another (I used TwentyTwenty).
* Note that without touching the page in the editor (same exact code), the form looks correct. 

### What I expected to happen

The form should look the same across themes. 

### What actually happened

The formatting changed.

### Context

Reported in 31065034-hc

From my personal HE test site:

**Obsidian**

![Annotation on 2021-08-10 at 18-37-12(1)](https://user-images.githubusercontent.com/2545184/128943970-469d0827-fc80-4e5c-b49f-a27954a60eec.png)

**TwentyTwenty**

<img width="973" alt="Screen Shot 2021-08-10 at 18 29 12" src="https://user-images.githubusercontent.com/2545184/128944029-abdec6f0-6909-4020-bdd2-3e6297d5edc3.png">

### Operating System

macOS

### Browser

Firefox

### Is this specific to applied theme? If so, what is the theme name?

Obsidian

### Simple, Atomic or both?

Atomic

### Available Workarounds

Need to use CSS to manually remove extra box, see 31065034-hc.

### Reproducibility

Consistent

**Comment by formosattic** [comment] 2021-08-17 08:24
Thanks for the report @ChrissiePollock.
I've updated the issue, noting that CSS can be used to remove any extra elements.

That said, I wasn't able to reproduce the issue. The user's page with the form looks ok now, without any custom CSS, so looks like they managed to tweak the form.

Closing this for now. Please feel free to re-open if you have further findings to add.
(As it sounds like this only happened with Obsidian, I'm moving this to the theme repo).

**Closed by formosattic** 2021-08-17 08:24 UTC
Labels: [Type] Bug, User Report
