### ISSUE TITLE
[Navigation Block] Submenus in Overlay do not Collapse

### ISSUE THREAD

**Issue by NoHopeRadio** [Automattic/wp-calypso#67943] opened 2022-09-18 19:03 UTC
### Quick summary

In a navigation block with a submenu, when selecting Open on click and Always Overlay, the submenu items do not collapse and the open to show an arrow is not selectable. The arrow is also not present.

<img width="1162" alt="Screenshot on 2022-09-18 at 14-54-41" src="https://user-images.githubusercontent.com/71042895/190923870-842d74c3-5ac3-450b-92dd-130f85dd1e6d.png">

This behavior continues on the live page. It looks like there is a visibility rule that doesn't get toggled in this view. Here's a workaround with CSS:

```
.wp-block-navigation-item.open-on-click .wp-block-navigation-submenu__toggle[aria-expanded="false"] ~ ul.wp-block-navigation__submenu-container {
    visibility: hidden;
}
```

### Steps to reproduce

1) Create navigation block with submenu
2) Select overlay Always and toggle On-click
3) Save, submenus always active, no arrow visible.

### What you expected to happen

Submenus should collapse.

### What actually happened

They don't, and there's no option to change it. I understand that these options might not be as desirable in the overlay menu as the in-line menu, but there's a disparity between the visible options and what happens, and it should probably be an option.

### Context

zen-5566307

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Available workarounds?

Yes, easy to implement

### Workaround details

CSS:

```
.wp-block-navigation-item.open-on-click .wp-block-navigation-submenu__toggle[aria-expanded="false"] ~ ul.wp-block-navigation__submenu-container {
    visibility: hidden;
}
```

**Comment by Greatdane** [comment] 2022-09-22 05:42
📌 HOUSEKEEPING (To be removed once checked)

📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated
- Tested on Self-hosted - Replicated
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- Not 100% sure if this is a bug or intended. 
- Replicated on all environments;

![zHQLSS.png](https://user-images.githubusercontent.com/5075840/191666619-2fc06f9e-7c5b-41d1-a27b-ef7ebd41b95a.png)

- Added to core; https://github.com/WordPress/gutenberg/issues/44346

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Greatdane** [comment] 2022-09-28 07:54
Closing this, as Gutenberg said it is intended behavior. See; https://github.com/WordPress/gutenberg/issues/44346

**Closed as completed by Greatdane** 2022-09-28 07:54 UTC
Labels: Bug, [Pri] Low, Triaged, [Platform] Simple, [Platform] Atomic

**Comment by NoHopeRadio** [comment] 2022-10-01 15:36
I see this is closed, but I did just receive another request for this, so maybe I should report this as a feature request instead of a bug.

A variation on the CSS I provided before that worked in this slightly different case:

```
/* collapse mobile submenus */
@media screen and (max-width: 599px) {
.wp-block-navigation-item.open-on-hover-click .wp-block-navigation-submenu__toggle[aria-expanded="false"] ~ ul.wp-block-navigation__submenu-container {
    display: none;
}
.wp-block-navigation__responsive-container.is-menu-open .wp-block-navigation__responsive-container-content .wp-block-navigation__submenu-icon {
    display: block;
}
.wp-block-navigation .wp-block-navigation__submenu-icon {
    align-self: unset;
}
}
```

37198043-hc
