### ISSUE TITLE
Tortuga: Domain being removed from cart during NUX 

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#15131] opened 2017-06-14 19:48 UTC
I was testing out something with Tortuga for new users today. I started through the Tortuga flow, chose my domain, theme, and plan then created my account. The site creation came up as normal and it mentioned the domain that I was attempting to register. However then once checkout popped up the domain was not my cart, only the plan. I proceeded with the checkout process just to see if the domain was still registered but it wasn't. It was seemingly removed from the purchase experience between the site creation step and checkout.

Steps to reproduce:
1. While logged out, go to `wordpress.com/domains`
2. Search for and select a domain.
3. Choose a theme and a plan (I chose Premium if it matters).
4. Create your account.
5. When the checkout screens comes up, check to see if your domain is in your cart.

**Comment by klimeryk** [comment] 2017-07-13 01:20
@mikeshelton1503 Are you sure this domain was not already taken? Sometimes our suggestion engines suggest a domain that is already taken - when it's actually added to cart, we run the availability check and if it's taken, we remove it from cart (I know, not the best UX, but better than failed registrations, refunds, etc.). That's the only case that comes to my mind that could explain this behaviour.

**Comment by mikeshelton1503** [comment] 2017-07-13 12:31
I tested it with several different domains and while I don't remember what domains I was trying to register I usually test with nonsense names.

**Comment by klimeryk** [comment] 2021-02-02 13:32
Cannot reproduce this (and we have the new shopping cart too), so closing this.

**Closed by klimeryk** 2021-02-02 13:32 UTC
Labels: Domains, [Type] Bug
