### ISSUE TITLE
Tax ID field for Brazil payments is too long when an error message is displayed

### ISSUE THREAD

**Issue by nbloomf** [Automattic/wp-calypso#45076] opened 2020-08-20 20:02 UTC
To reproduce:
- Enter checkout with Brazil payment methods enabled (either Ebanx card processing or TEF payments)
- Proceed to the payment step and select the Brazil specific method (card or TEF), but leave the tax ID field blank
- Try to submit and observe the chaos

![image](https://user-images.githubusercontent.com/9310939/90819954-483cd580-e2f6-11ea-9c0e-a93b835717d2.png)

**Comment by DavidRothstein** [comment] 2021-03-05 21:04
Doesn't seem likely to actually be stale, so I'm leaving a comment to keep it open...

**Comment by vishnugopal** [comment] 2021-06-14 10:55
Just a note that I'm not able to reproduce the error now: 
![CleanShot 2021-06-14 at 16 24 54](https://user-images.githubusercontent.com/533/121881578-18e7d100-cd2d-11eb-90f3-15f4026a1421.png)

Trying to figure out what changed in between. 

Edit: I tried to dig into which commit possibly fixed this issue, but commits from about the date of the report can no longer be built easily so I'm giving up here. For what it's worth, this issue seems fixed on trunk and current Wordpress.com

**Comment by royalpinto007** [comment] 2022-12-27 20:22
Hello, can you please assign this issue to me?

**Comment by cuemarie** [comment] 2023-04-13 23:33
Per @vishnugopal 's [findings](https://github.com/Automattic/wp-calypso/issues/45076#issuecomment-860592332), it seems this is resolved. Closing the issue.

**Closed by cuemarie** 2023-04-13 23:33 UTC
Labels: [Type] Bug, [Pri] Low, Checkout, Good First Issue
