### ISSUE TITLE
Checkout: Rendering issue with a strange flash of styled confetti when selecting a plan

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38083] opened 2019-11-29 20:37 UTC
#### Steps to reproduce
1. Starting at URL: horizon.wordpress.com/start/test-fse
2. Select a plan in signup on the plans screen
3. Notice a flash of styled confetti …

It looks like this content …

![image](https://user-images.githubusercontent.com/545779/69889291-b7c8eb80-12b5-11ea-9bdc-85705a7f4219.png)

loads suddenly, only to be quickly replaced by …

![image](https://user-images.githubusercontent.com/545779/69889299-c6af9e00-12b5-11ea-907b-eaa4c34b0d91.png)

… that content.

cc @fditrapani

**Comment by niranjan-uma-shankar** [comment] 2019-12-06 08:30
Duplicate of https://github.com/Automattic/wp-calypso/issues/36557.

Bonus issue: check comment https://github.com/Automattic/wp-calypso/issues/36557#issuecomment-538912319

**Comment by davipontesblog** [comment] 2020-03-10 01:41
Closing this in favor of https://github.com/Automattic/wp-calypso/issues/36557.

**Closed by davipontesblog** 2020-03-10 01:41 UTC
Labels: Checkout
