### ISSUE TITLE
Cannot visit WordPress.com Hosted Website in some location 

### ISSUE THREAD

**Issue by ttcath** [Automattic/wp-calypso#74407] opened 2023-03-14 07:28 UTC
### Quick summary

From 2023-03-08 23:58:07 to Mar 12, 2023, 17:13:07. some visitors from the location out of China, cannot visit our website 

### Steps to reproduce

1. Using HostTracker monitor the website.
2. Get email alerts.

Also, I use Uptimia monitor the website too.

### What you expected to happen

There is no error on visiting our website.

### What actually happened

The incidents reported by  Uptimia.com shows following:
Mar 12, 2023, 17:12:11 - Mar 12, 2023, 17:13:07 visitors from Orlando, United States(92.38.133.18), Copenhagen, Denmark(192.36.27.88),Vilnius, Lithuania(192.36.61.24) cannot establish connection to our website.
Mar 12, 2023, 08:12:40 - Mar 12, 2023, 08:13:23 visitors from London(51.75.170.220), Mexico City, Mexico(216.238.71.251),Vilnius, Lithuania(192.36.61.24) also cannot establish the connection to our website.
Mar 09, 2023, 22:40:37 visitors from Adelaide, Australia(146.185.214.151) can not establish the connection to our website.

HostTracker monitor provide the incident report shows following:

Current time 2023-03-09 00:00:28

Operation restored at 2023-03-08 23:59:13

       Los Angeles, California, United States - Ok
       Seattle, WA, United States - Ok
       Erfurt, Thüringen, Germany - Ok
       Paris, France - Ok
       Kyiv, Ukraine - Ok
       Nerva, Estonia - HTTP response timed out
       Chisinau, Moldova, Republic of - HTTP response timed out
       Kharkiv, Ukraine - HTTP response timed out

URL was down as a result of:

       HTTP response timed out
       Tallin, Estonia - HTTP response timed out
       Naaldwijk, Netherlands - Connection Reset
       Meppel, Netherlands - Connection Reset
       Kyiv, Ukraine - Connection Reset
       Oslo, Norway - Connection Reset
       Prague, Czech Republic - Connection Reset
       Vilnius, Lithuania - HTTP response timed out
       Palermo, Italy - Ok

First error was detected at 2023-03-08 23:57:22

Last error was detected at 2023-03-08 23:58:07

Downtime total 1 min(s) 51 sec(s).

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by ttcath** [comment] 2023-03-14 07:30
@tyxla @jeherve Please have a look on this, and do some investigation at once.

**Comment by ttcath** [comment] 2023-03-14 07:35
Also, as Uptimia.com Speed Monitoring reports today

ttcath speed monitor | Speed Monitoring | Kyiv, The Ukraine | March 14th, 2023, 14:39 | Down | 0.00 sec
ttcath speed monitor | Speed Monitoring | Fortaleza, Brazil | March 14th, 2023, 13:30 | Down | 0.00 sec
ttcath speed monitor | Speed Monitoring | Fremont (CA), United States | March 14th, 2023, 12:48 | Down | 0.00 sec
ttcath speed monitor | Speed Monitoring | London #2, United Kingdom | March 14th, 2023, 11:20 | Down | 0.00 sec
ttcath speed monitor | Speed Monitoring | Phnom Penh, Cambodia | March 14th, 2023, 10:37 | Down | 0.00 sec
ttcath speed monitor | Speed Monitoring | Gravelines, France | March 14th, 2023, 09:23 | Down | 0.00 sec
ttcath speed monitor | Speed Monitoring | Gravelines, France | March 14th, 2023, 09:22 | Down | 0.00 sec
ttcath speed monitor | Speed Monitoring | Phnom Penh, Cambodia | March 14th, 2023, 09:10 | Down | 0.00 sec
ttcath speed monitor | Speed Monitoring | London #2, United Kingdom | March 14th, 2023, 08:14 | Down | 0.00 sec
ttcath speed monitor | Speed Monitoring | Strasbourg, France | March 14th, 2023, 08:12 | Down | 0.00 sec
ttcath speed monitor | Speed Monitoring | Ashburn (VA), United States | March 14th, 2023, 06:28 | Down | 0.00 sec
ttcath speed monitor | Speed Monitoring | Strasbourg, France | March 14th, 2023, 04:57 | Down | 0.00 sec
ttcath speed monitor | Speed Monitoring | Manila, Philippines | March 14th, 2023, 02:14 | Down | 0.00 sec

The IP addresses, please find https://www.uptimia.com/monitoring-checkpoints

**Comment by jeherve** [comment] 2023-03-14 12:47
Closing as duplicate of #74358

**Closed as completed by jeherve** 2023-03-14 12:47 UTC
Labels: Bug, [Pri] High, Needs triage, [Status] Priority Review Triggered
