### ISSUE TITLE
Post & Pages: Repetitive jump icon and text per row

### ISSUE THREAD

**Issue by johnmaeda** [Automattic/wp-calypso#32252] opened 2019-04-12 16:53 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/posts/automattic.design?startDate=2019-04-12

#### What I expected
I expected to click on the Views count entry to send me to the statistics view. And I expected to click on the Title name entry to take me to the actual article. 

#### What happened instead
There's a jump icon with a "View" text on every line. The entire row signififes jumping to a statistics view (with the exception of the jump icon and View). I expected there not to be so many "View" messages for each post or page, and for there to be a minimal set of actions: 1/ Look at the piece of content, and 2/ Go deeper on statistics. 

#### Browser / OS version
Chrome.

#### Screenshot / Video
<img width="864" alt="Screen Shot 2019-04-12 at 11 23 59 AM" src="https://user-images.githubusercontent.com/2140796/56052868-84cee900-5d20-11e9-917c-179dc3327421.png">

#### Context / Source

#dogfooding

**Comment by donpark** [comment] 2019-04-12 22:52
Some thoughts on this page:

- Posts and pages are like apples and oranges, meaning mixing their view stats offers little or no insights. Options are to split into 1) two columns or 2) two pages.
- Title link should map to post or page.
- View link should map to stats detail page.
- View counts should be closer to title than link to stats.
- View text links could be replaced with sparklines, rendered on the client-side using inlined SVG or using JS from inlined per-item trend data, to link destination clearer.

**Comment by jeffgolenski** [comment] 2019-04-29 17:48
Working on some analyzation of the flows around this now. Getting some quick mocks together!

**Comment by jeffgolenski** [comment] 2019-04-29 18:58
I did some deep diving into the quant data and some flow exploration. I've got a simple solution that I think will allow folks to keep getting their stats info and simplify some things for better skim-ability, and easier actions for small mobile screens.

It's important to keep in mind the customers intent on this page, and that's to view stats, anything else on the stats page is a secondary goal. 

It's also important to take the more holistic picture into account with where customers are coming from and where they're going.

**Current flow:**

* The view buttons take the customer into a new window and away from their wpcom dashboard. Why? We have the power to show them previews within the dashboard (and preview multiple device sizes), so let's keep them there instead of sending them down a one-way street that's not mobile friendly. (see image below)
* For small screens fitting so many links on one line is bothersome, let's streamline that and have each entire line take the customer to the next step (see image below).
* The current flow branched into an unnecessary nonlinear flow that can lose people.

**Proposed enhancements:**

* Remove external links to view page or posts in new tab or window
* Keep customers within the calypso dashboard so they don't get lost
* Create a better mobile experience
* Allow folks to edit post or page during detailed view (inside preview)

**Current & Proposed flow mocks**

   
![bottle-pickup-stats-proposal](https://user-images.githubusercontent.com/214813/56919625-12d00100-6a8f-11e9-94bc-edfc89256d60.jpg)

**Comment by alaczek** [comment] 2019-04-30 06:14
I really like the idea of removing the view link - I think it's adding unnecessary ambiguity (is it view the post or view the stats?). I agree that the whole line being a link to individual stats details page makes a lot more sense, and is the expected behaviour in this context.. 

Code wise, it looks like we'd only need to remove the "View" link from the widget, and from the list view? The "View post" link is already there in the top bar on the details page. I can take care of removing it, but let me know if I'm missing something.

**Comment by jeffgolenski** [comment] 2019-04-30 13:11
That sounds great @alaczek - that should be it. And probably just adding behavior to make sure the if anywhere in the row is clicked or tapped, it'll act as a link for the customer. Thanks for taking that on.

**Comment by alaczek** [comment] 2019-05-01 02:41
While working on a PR for this I discovered a couple more places where this pattern is being used:
Authors stats:
![image](https://user-images.githubusercontent.com/4550351/57003933-9ca5d880-6c0d-11e9-9602-c9c5035102af.png)

![image](https://user-images.githubusercontent.com/4550351/57003936-a62f4080-6c0d-11e9-83da-b89f2ac5dca4.png)

Videos:
![image](https://user-images.githubusercontent.com/4550351/57003941-b810e380-6c0d-11e9-8a7c-202603afede0.png)

![image](https://user-images.githubusercontent.com/4550351/57003949-c3640f00-6c0d-11e9-9435-be579dbaba5d.png)

@jeffgolenski I'm wondering if the same changes should be applied in those items as well for consistency?

**Comment by jeffgolenski** [comment] 2019-05-01 13:28
@alaczek Yes that sound fantastic.

**Comment by alaczek** [comment] 2019-05-06 04:41
Merged & deployed!

**Closed by alaczek** 2019-05-06 04:41 UTC
Labels: FixTheFlows, Stats

**Comment by jeffgolenski** [comment] 2019-05-08 16:16
Thanks @alaczek !
