### ISSUE TITLE
Logos missing on themes using jetpack_the_site_logo function after Gutenberg v10.7.4

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/wp-calypso#53517] opened 2021-06-08 18:18 UTC
Some themes can no longer display their site logo after the release of Gutenberg v10.7.4 on WordPress.com Simple.

Here's a shortlist of themes we've seen this impact so far:

* Soho, Luxury, Didi, Obsidian, Blask, Maisha, Puzzle, Pique

It appears this mostly impacts themes using the `jetpack_the_site_logo` function:
https://github.com/Automattic/jetpack/blob/ba2dd6c30be137baad96aafb2466d0aed7e182e5/projects/plugins/jetpack/modules/theme-tools/site-logo/inc/functions.php#L103

Gutenberg v10.7.4 patch:
* r226861-wpcom
* D62435-code

That release was for addressing other Customizer and site setting issues reported on the following.
* https://github.com/Automattic/wp-calypso/issues/53447
* https://github.com/Automattic/wp-calypso/issues/53431

Originally, I opened an issue here: 
https://github.com/Automattic/themes/issues/4026

We then moved the internal discussion to p1623174912090300-slack-CBTN58FTJ

I'm opening this issue up for tracking this new issue.

### Steps to reproduce the behavior

1. Visit a WordPress.com Simple site with Soho, Luxury, or Didi active. Or, create a new one and activate one of those themes.
2. Set a logo.
3. See error

#### What I expected to happen

A logo to appear as seen in the original demo.

![image](https://user-images.githubusercontent.com/4887830/121228194-732ef080-c85a-11eb-8ffa-03b350ea8d40.png)

#### What actually happened

No logo, even of the demos of the themes.

![image](https://user-images.githubusercontent.com/4887830/121228155-64483e00-c85a-11eb-85b4-a6f56a0dec36.png)

### Context

* User report: 29618704-hc
* Follow-up ticket: 4053426-zen
* Internal discussion: p1623174912090300-slack-CBTN58FTJ

#### Is this specific to the applied theme? Which one?
Multiple. Soho, Luxury, and Didi, Obsidian, Blask, Maisha, Puzzle, Pique are confirmed to have the issue.

#### Does this happen on simple or atomic sites or both?

Simple for now. Might impact Atomic later if certain patches are applied.

#### Is there any console output or error text?
No.

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Sites using the noted themes.

**Comment by mikeicode** [comment] 2021-06-08 18:27
Obsidian & Blask themes appear to have the issue also

**Comment by louinel** [comment] 2021-06-08 18:48
User reported this here 4053599-zen-woothemes, theme Maisha

**Comment by sajmes** [comment] 2021-06-08 18:51
Puzzle also seems to have the issue. User report here 28874358-hc.

I replicated on my Premium site.

**Comment by hanananah** [comment] 2021-06-08 19:10
Another report: #4053721-zen
Theme: Blask

**Comment by jackiejade** [comment] 2021-06-08 19:10
Another user report - theme Pique
30038172-hc
follow up ticket #4053828-zen

**Comment by dcoleonline** [comment] 2021-06-08 19:13
Luxury theme on #28159019-hc

I wasn't able to tell for sure if the cause was this issue or third party plugins/configuration/code they added.
For now I gave them a CSS workaround to show the image as the background for the logo link element. They already had a CSS plugin active, so I added it there instead of in the customizer.

**Comment by davipontesblog** [comment] 2021-06-08 19:14
moving to Flow Patrol for triaging. This is affecting lots of sites.

**Comment by deke207** [comment] 2021-06-08 19:16
Another user affected: twenty fifteen theme
#4053729-zen

**Comment by desnum** [comment] 2021-06-08 19:28
Another case at 410063-hc with the Cubic theme

**Comment by xpurichan** [comment] 2021-06-08 19:32
Reported on the Rosalie theme in 29772888-hc.

**Comment by desnum** [comment] 2021-06-08 19:47
A case on the Blask theme: 29570427-hc

**Comment by kcswong** [comment] 2021-06-08 19:48
Maisha, Atomic site, follow up in 4053766-zen

**Comment by ersatzpenguin** [comment] 2021-06-08 20:04
Also occurring with Canard, follow up in 4053931-zen

**Comment by kcswong** [comment] 2021-06-08 20:12
Atomic using Patch theme, follow up 4053957-zen. The theme demo is showing the same issue as well

**Comment by desnum** [comment] 2021-06-08 20:24
A case with the Edin theme, 29570427-hc

**Comment by JessBoctor** [comment] 2021-06-08 20:31
Another two user reports

29938050-HC
Theme: TwoTone
Follow up 4054014-Zen

23590218-HC
Theme: Arcane
Follow up: 4053962-Zen

**Comment by kcswong** [comment] 2021-06-08 20:35
Sela is retired, but happening here as well, follow up in 4054017-zen

**Comment by desnum** [comment] 2021-06-08 20:48
A case on the Aquene theme: 29570427-hc

**Comment by desnum** [comment] 2021-06-08 20:58
A case on the Healthy Living theme: 29570427-hc

**Comment by ChrissiePollock** [comment] 2021-06-08 21:00
Canard theme with this issue: 29532561-hc

**Comment by sbathompson-he** [comment] 2021-06-08 21:05
Seems I got quite a few today. Here they are:
4053849-zd-woothemes - Melody
4053469-zd-woothemes - Twenty Sixteen / Happening on only 2 sites with that theme
4053446-zd-woothemes - Illustratr
4053376-zd-woothemes - Obsidian
4054003-zd-woothemes - Toujours

**Comment by villanovachile** [comment] 2021-06-08 21:32
Another report: 4053955-zen
Atomic site using Twenty Fifteen

**Comment by creativecoder** [comment] 2021-06-08 21:46
Note, an initial fix for this has been deployed in D62504-code. That should take care of the issue for Simple Sites. Users may need to re-save the logo in the Customizer before it will display.

**Comment by villanovachile** [comment] 2021-06-08 21:48
@creativecoder My user's site is Atomic. Any idea when a fix may be incoming for Atomic users?

**Comment by dhackneya8c** [comment] 2021-06-08 21:49
Simple site with Blask theme: 22951768-hc

**Comment by JessBoctor** [comment] 2021-06-08 22:29
I have another report in 30040760-HC

Theme: Twotone
AT Site

Follow-up: 4054255-Zen

**Comment by scosgro** [comment] 2021-06-08 22:31
Another report in 30040831-HC
Theme: Radiate
AT Site.

**Comment by dhackneya8c** [comment] 2021-06-08 22:54
Report: 30041043-hc 
Atomic site using Luxury theme

**Comment by katiebethbrown** [comment] 2021-06-08 23:15
Another report in 5684053-hc (atomic site)

**Comment by sourourn** [comment] 2021-06-08 23:19
Another report in #30039458-hc (atomic site).

**Comment by sourourn** [comment] 2021-06-08 23:25
Another report in #28746123-hc (simple site)

**Comment by isocialtish** [comment] 2021-06-08 23:51
Report in #30041094-hc (atomic)
Follow-up #4054408-zen

**Comment by creativecoder** [comment] 2021-06-09 01:49
A fix for Atomic sites has been deployed as well in wpcomsh, about 2 hours ago.

The fixes are preliminary--we'll need to follow up with some additional work to address the root cause. I'll keep this open for now so we can watch for additional reports.

**Comment by TheSteveK** [comment] 2021-06-09 11:36
Another report (simple site) #4054004-zen

**Comment by zdenys** [comment] 2021-06-11 06:07
30067634-hc with Radcliffe 2 theme.

**Comment by davipontesblog** [comment] 2021-06-11 11:11
Shifting priorities as there has been a surge of new reports in the last few days.

**Comment by creativecoder** [comment] 2021-06-11 16:09
The sites mentioned in both 4054004-zen and 30067634-hc have the logo showing, when I checked them just now.

I'm going to close this issue, as it appears resolved. But feel free to reopen if you find that a Site logo that is set is not showing in the Customizer and/or on the front-end of the site so we can investigate.

**Comment by fullofcaffeine** [comment] 2021-06-11 23:36
> I'm going to close this issue, as it appears resolved. But feel free to reopen if you find that a Site logo that is set is not showing in the Customizer and/or on the front-end of the site so we can investigate.

**Comment by daria2303** [comment] 2021-07-02 09:19
Issue persists here: 4108288-zd-woothemes
After refresh in customizer logo is gone

**Comment by pablinos** [comment] 2021-07-02 09:42
@creativecoder If this is still an issue, I'm thinking it should be solved when Automattic/jetpack#20192 ships to WordPress.com. What do you think?

**Comment by creativecoder** [comment] 2021-07-02 14:06
Thanks for that report @daria2303 . It looks like the site mentioned in 4108288-zd-woothemes is using the Shoreditch theme, which uses the Core `custom-logo` feature rather than the Jetpack logo feature referenced in this issue.

This looks like a variation of https://github.com/Automattic/wp-calypso/issues/54055; I'll add details to that issue and we can track it there.

**Closed as completed by creativecoder** 2021-07-02 14:06 UTC
Labels: Bug, [Feature Group] Appearance & Themes, Jetpack, [Pri] High, Logo

**Comment by creativecoder** [comment] 2021-07-02 14:15
@pablinos I think that PR will help for some sites, but in the case where the theme uses the custom-logo feature, there's a Gutenberg bug that needs to be fixed--still trying to track that down.
