### ISSUE TITLE
Tiled Gallery Doesn't Show Images

### ISSUE THREAD

**Issue by poojashetty18** [Automattic/wp-calypso#47546] opened 2020-11-18 14:45 UTC
## Steps to reproduce

1. Add a new Tiled Gallery Block
2. Add multiple images to it

#### What I expected

Images to appear as tiled gallery.
 
#### What happened instead

However, they appear grey on both the Editor and actual page preview. I tested it on Chrome, user was on Safari

#### Screenshot / Video

Full video link: https://d.pr/i/NFvOxN

#### Context / Source

Similar reports here: https://github.com/Automattic/wp-calypso/issues/47223 and https://github.com/Automattic/wp-calypso/issues/45138 but did not add to it as it appears when directly 

25535495-hc
3499939-zd

 #user-report

**Comment by cathymcbride** [comment] 2020-11-18 15:51
@poojashetty18 I'm not reproing on a simple site, but do see on atomic. Do you see that as well? Also, is there anything related in the console?

**Comment by ockham** [comment] 2020-11-18 18:23
We incidentally upgraded Gutenberg from v9.2.2 to v9.3.0 on Simple Sites (D52940-code) shortly after this was reported by @poojashetty18, and on Atomic Sites (p9o2xV-19s-p2) after @cathymcbride reported she wasn't able to repro there. Could y'all try again and see if the new GB version might've fixed the issue?

**Comment by poojashetty18** [comment] 2020-11-19 07:54
Hey @cathymcbride and @ockham , I rechecked it and the issue still exists. The user is on an Atomic site

Here are a few console errors I see: https://d.pr/i/rsoQHc

**Comment by cathymcbride** [comment] 2020-11-19 15:08
@ockham I'm still seeing the same thing. Works on simple, repros as written on atomic.

**Comment by ockham** [comment] 2020-11-26 20:42
Thanks @poojashetty18 and @cathymcbride for confirming! I can also repro (on an actual Atomic site; not on an ephemeral one, however).

> Here are a few console errors I see: https://d.pr/i/rsoQHc

The 403 errors for image URLs on `i[0-2].wp.com` are relevant I believe. Embedding the image here for increased exposure:

<img width="1664" alt="Screenshot on 2020-11-19 at 11-52-36" src="https://user-images.githubusercontent.com/96308/100390354-5bb3b700-3030-11eb-8ed8-0ceae92adc4a.png">

Adding to the Create Gardeners' board. Also cc'ing @Automattic/ganon based on the _very_ wild guess that this might have to do with private sites/Coming Soon mode.

**Comment by ramonjd** [comment] 2020-11-26 21:33
> Adding to the Create Gardeners' board. Also cc'ing @Automattic/ganon based on the very wild guess that this might have to do with private sites/Coming Soon mode.

Is this happening in private mode (or coming soon mode v1, which is private)?

It sounds related to the existing bug here: https://github.com/Automattic/wp-calypso/issues/41272#issuecomment-732204924

In which case, we'd recommended that the user toggle between public and coming soon mode, which should migrate them to coming soon mode 2 (public not-indexable).

**Comment by ramonjd** [comment] 2020-11-26 21:36
I just checked the user's account setting. Their site is set to private, so it sounds like a dupe of #41272

**Comment by cathymcbride** [comment] 2020-12-04 20:23
OK - based on 👆 this being a dupe of #41272, I'm going to close this bug...but I am going to copy ramonjd's workaround recommendation for ease of finding.

"In which case, we'd recommended that the user toggle between public and coming soon mode, which should migrate them to coming soon mode 2 (public not-indexable)."

**Closed by cathymcbride** 2020-12-04 20:23 UTC
Labels: Blocks, [Type] Bug
