### ISSUE TITLE
FSE Site Editor (Beta): Editing the Post Title in Editor (Beta) Crashes the Editor

### ISSUE THREAD

**Issue by i11za** [Automattic/wp-calypso#58845] opened 2021-12-05 20:02 UTC
### Quick summary

When editing a page/post in FSE Site Editor (Beta), editing the Post Title in Editor (Beta) crashes the editor. 

### Steps to reproduce

1. Activate FSE Site Editor (Beta)
2. Add a new page/post or edit an existing page/post in Editor (Beta)
3. Edit Post Title

### What you expected to happen

Post Title is successfully edited. 

### What actually happened

**1. Post Title block displays an error:** `"The editor has encountered an unexpected error" ` as seen on the screenshot below. 

![image](https://user-images.githubusercontent.com/84193945/144761594-90a2a339-ad0b-4823-8193-f6031da74b4d.png)

And another example of this happening on a test site: 

![image](https://user-images.githubusercontent.com/84193945/144761724-2cbfa873-5a35-4f1f-b248-c5bba9a30bcf.png)

**2. Editor crashes, with the following error**: 
![image](https://user-images.githubusercontent.com/84193945/144761687-6dec763b-726b-40f4-88e1-2447aaeaef6d.png)
Error message:
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Sh (https://domain.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:152:165)
    at Qj (https://domain.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:174:181)
    at unstable_runWithPriority (https://domain.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://domain.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at eb (https://domain.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:170:163)
    at gf (https://domain.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:317)
    at https://domain.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:230
    at unstable_runWithPriority (https://domain.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://domain.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at $g (https://domain.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:176)
```

### Context

Initially spotted in 4534687-zd-woothemes. 

As discussed internally, submitting for further testing/triage. 

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

One

**Comment by Greatdane** [comment] 2021-12-09 05:54
I am unable to replicate with the Zoologist theme and FSE on (see video). Can you expand on Steps to reproduce? I added a new post, then added the post title block. 


https://user-images.githubusercontent.com/5075840/145342147-b90effc8-6738-4f37-a7e3-0e690003f5b8.mp4

**Comment by synora** [comment] 2021-12-12 16:24
@Greatdane 👋 
I can replicate this on Zoololgist. After you've added the Post Title Block, save it, and leave the Site Editor. Open the Site Editor again, and the error message will appear. 

https://user-images.githubusercontent.com/10015451/145720553-014bfa6e-57a5-449b-8473-aeb526b13827.mp4

**Comment by Robertght** [comment] 2021-12-15 12:02
It looks like this is theme-dependent. cc @jordesign

**Comment by thebud15** [comment] 2021-12-21 19:51
I encountered a similar issue when testing this. 

I first activated Geologist and was met with a "The block has encountered an error and cannot be previewed" message in place of a Post Title block. I removed and re-added this block successfully. 

Once I changed themes again to the FSE-first theme Quadrant, the error re-appeared. 

Here's how that looked:
<img width="1636" alt="Screen Shot on 2021-12-21 at 11_25_23" src="https://user-images.githubusercontent.com/29046778/146989241-164654a4-4ed1-4470-82e5-6d14121adc5c.png">

**Comment by janmckell** [comment] 2022-02-24 10:55
4712639-zen

This error message was also seen here, but it is a simple site.

• The user gets a WSOD on the editor when they try to edit or just add a space and press the return button.
• User sees error as well: [](https://d.pr/i/XGnJyG)

Previous Steps taken

- cleared browser cache
- issue does not occur in Firefox
- User has a retired theme. I activated the same theme on my site but could not recreate.
- enabled third-party cookies
- User had disabled all extensions

Information

- user's browser information: [](https://www.whatsmybrowser.org/b/TLN6P)
- could not reproduce issue following user's steps: [](https://d.pr/v/1DtS5s)

Error message:

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.    at Sh ([ https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:7:34065](https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:7:34065) )    at Qj ([ https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:8:8377](https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:8:8377) )    at unstable_runWithPriority ([ https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react.min.755b0ae9.js?m=1644337243h:5:3609](https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react.min.755b0ae9.js?m=1644337243h:5:3609) )    at Za ([ https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:6:12302](https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:6:12302) )    at eb ([ https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:8:6339](https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:8:6339) )    at gf ([ https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:8:2335](https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:8:2335) )    at [https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:6:12524](https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:6:12524)    at unstable_runWithPriority ([ https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react.min.755b0ae9.js?m=1644337243h:5:3609](https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react.min.755b0ae9.js?m=1644337243h:5:3609) )    at Za ([ https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:6:12302](https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:6:12302) )    at $g ([ https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:6:12470](https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.5.4/vendor/react-dom.min.edd8b7a6.js?m=1644337243h:6:12470) )
```

**Comment by aleone89** [comment] 2022-02-24 15:27
This has also been reported here: 4764076-zen - I'm asking them for more details.

**Comment by arunsathiya** [comment] 2022-05-20 00:00
I am unable to reproduce this. This is on a simple site:


https://user-images.githubusercontent.com/18581859/169394004-8df24952-2770-450d-a763-c1389fb4f633.mov

And on an Atomic site:

https://user-images.githubusercontent.com/18581859/169393879-37f11624-19d3-40cd-b69a-1c4343f276d0.mov

Both with Zoologist. It's possible that things improved in the past few Gutenberg releases. I'll close this for now, please feel free to reopen if you can reproduce.

**Closed as completed by arunsathiya** 2022-05-20 00:00 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Normal, Triaged
