### ISSUE TITLE
Block themes: minicart doesn't allow users to checkout

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#70204] opened 2022-11-19 11:43 UTC
### Quick summary

If you use a Block theme like Blockase/Attar/etc and add the Mini cart block to the nav menu the footer of that mini cart won't show up on mobile, being covered by the browser bar

### Steps to reproduce

1. Activate Blockbase
2. Add the Minicart block to the header
3. Add a product to your cart and click on the cart icon
4. You should see the cart section, but you won't be able to click on the bottom checkout option.

### What you expected to happen

To see the entire section

### What actually happened

The section was cut:
![Uploading IMG_A92B650CE41B-1.jpeg…]()

### Context

5719527-zen

5697160-zen

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Block themes

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

Change the theme or find a CSS workaround.

**Comment by kavyagokul** [comment] 2022-11-22 15:47
📌 SCRUBBING : RESULT
- Tested on P2 - Uncertain
- Tested on Simple - Uncertain
- Tested on AT - Uncertain 
- Tested on Self-hosted - Uncertain 
- Replicable on Core - Yes/No

📌 FINDINGS/SCREENSHOTS/VIDEO
- The footer seems to be there, just hidden below the fold. It needs one to scroll to show.
[Screencast from 2022-11-22 21-15-11.webm](https://user-images.githubusercontent.com/1659416/203358248-1333e373-df9f-42cf-90bf-2dbec80429e0.webm)


📌 ACTIONS
- Await author feedback


📌 Message to Author
@Robertght I see that you started adding a screenshot, but it didn't work. I was not able to replicate this as shown in my findings. Can you add your screenshot/screencast so we have more info to be able to replicate this?

**Comment by Robertght** [comment] 2022-11-23 05:02
Sure! Here it is:

![IMG_2CFF1EFC5A20-1](https://user-images.githubusercontent.com/6737345/203472263-83428901-08a5-4233-9a05-3241771b6cc3.jpeg)

Please check the above on a mobile device.

**Comment by zachspears** [comment] 2022-11-23 06:05
Testing the above issues on mobile I had a related issue, leaving this open for further testing. In both Firefox and Safari the Mini Cart did not not display the item in my cart, and was formatted incorrectly:

https://user-images.githubusercontent.com/10124024/203481806-fca1a16e-8807-4db4-9f84-4461cd9cce89.mp4

https://user-images.githubusercontent.com/10124024/203481837-ed4e74e0-7a88-4da2-bac4-dd343ee3893f.mp4

**Comment by cuemarie** [comment] 2022-11-29 17:04
Thanks @zachspears for including your test results! This issue (with the blank cart) looks like a separate bug than the issue originally reported - perhaps one of these?

- https://github.com/Automattic/wp-calypso/issues/66683
- https://github.com/Automattic/wp-calypso/issues/65662
- https://github.com/woocommerce/woocommerce-blocks/issues/6874

_Update - I saw the same issue on my test site; deactivating Page Optimize restored the cart contents (though they ain't pretty), so I'm thinking that's the issue you were encountering as well_

**Comment by cuemarie** [comment] 2022-11-29 17:34
📌 SCRUBBING : RESULT 
- Tested on AT: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Thanks for the updates to your steps to replicate, @Robertght ! Here's what I was able to replicate:

1. Add `Mini Cart` block to header in Blockbase
2. Deactivate **Page Optimize** to avoid issue #65662
3. Open site on mobile browser - I tested with iOS Safari & Chrome
4. Add multiple items to the cart
5. Tap the Cart from the header and scroll down

**Results** - With only one item in my cart, I have to scroll down in the cart section to view and select "Go to Checkout".  With multiple products in the cart, when I first scroll down to see the "go to checkout" button, only the contents of the cart scroll, and not the entire sidebar. This results in me not being able to view the button. When I scroll down a second time, the button appears.  There seems to be a 

**_iOS Chrome (single product vs multiple products):_**

https://user-images.githubusercontent.com/27249804/204601081-a388b097-3f13-4105-8256-d898dc9eb960.mov

_**iOS Safari (multiple products):**_

https://user-images.githubusercontent.com/27249804/204601207-08bfb287-45a6-4f15-8c5f-a058e1a8fffa.MP4

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Gustavo-Hilario** [comment] 2022-12-19 23:10
Another report:

- [ ] 5800852-zen

I could reproduce this issue on the `Tsubaki` demo site: https://tsubakidemo.wpcomstaging.com/

I've helped the user above with a CSS code workaround for now:

```
/* Fix the issue with the Checkout button missing on the mini-cart on mobile | XXXXXX-hc/zen GH */
@media (max-width: 600px) {
.wc-block-mini-cart__title {
    flex-basis: 10%;
}
.wc-block-mini-cart__items {
    flex-basis: 65%;
}
.wc-block-mini-cart__footer {
    flex-basis: 25%;
}
}
 
/* End  | XXXXXX-hc/zen */
```

I'm not sure if the code will work for all sites, and a different media query might be necessary. Please test the code before sharing.

**Comment by kavyagokul** [comment] 2023-01-03 12:35
Context from closed duplicate
- #38844553-hc

**Comment by kuropixel** [comment] 2023-01-24 00:53
Another report (Theme: Tsubaki):
39928718-hc

Sharing CSS workaround resolved the issue.

**Comment by Aljullu** [comment] 2023-02-27 13:52
Howdy folks, have you received new reports of this bug? I think it was fixed in https://github.com/woocommerce/woocommerce-blocks/pull/8351, so I guess we can close this issue?

**Comment by cuemarie** [comment] 2023-07-27 19:05
Retesting today, Mini-Cart block on a Blockbase theme works as expected in both desktop and mobile responsive views:

_Desktop_

![41cHJX.gif](https://github.com/Automattic/wp-calypso/assets/27249804/a8718aa8-aff5-42d7-b6cc-22e92b4f8f49)

_Mobile Responsive View_

https://github.com/Automattic/wp-calypso/assets/27249804/330a0efc-f219-4cae-8184-b255a114e177

📌 ACTIONS
- Closing as resolved

**Closed as completed by cuemarie** 2023-07-27 19:05 UTC
Labels: Bug, [Pri] High, Mobile Web, Triaged, [Platform] Atomic
