### ISSUE TITLE
Sharing button disappears when Official Buttons is chosen on Chrome

### ISSUE THREAD

**Issue by kaitohm** [Automattic/wp-calypso#47992] opened 2020-12-03 08:10 UTC
#### Steps to reproduce

1. Navigate to My-site > Tools > Marketing > Sharing Buttons
2. Use Edit Sharing button > Select the LinkedIn button
3. Select Button style - `Official Buttons`

#### What happened
LinkedIn button is missing from both settings screen and front-end

Settings screen:
<img width="860" alt="Screen Shot 2020-12-03 at 17 08 24" src="https://user-images.githubusercontent.com/49054298/100981571-530c3500-358a-11eb-9b6f-da427b3e6995.png">

Front-end:
<img width="663" alt="Screen Shot 2020-12-03 at 17 07 29" src="https://user-images.githubusercontent.com/49054298/100981625-615a5100-358a-11eb-860e-52bbd2f8bb47.png">

#### Context / Source

Originally posted internally: pbEMJv-mF-p2
Based off this customer interaction: 3531992-zd-woothemes

**Comment by retnonindya** [comment] 2021-02-09 09:04
Hello! It seems like this now affecting **all** buttons. I can replicate it on my own site(s). This is the screen recording (GIF):
https://cldup.com/y5cMRtCQee.gif

You can see all social media accounts are checked, yet they are not visible when "Official Buttons" is selected.

![image](https://cldup.com/sXI_wdhB-Y.png)
*Direct link: https://cldup.com/sXI_wdhB-Y.png*

**Update**: 

- This issue happens on **Chrome**. I can confirm the issue not happened on Safari and Firefox.

- It seems like the issue happened on non-A8C WordPress.com account. I can't replicate the issue on my A8C WordPress.com account/Super Admin when I'm on Chrome.

- The buttons are visible on front-end/live site, but not visible on Calypso dashboard.

- This is the console error:
```
Access to XMLHttpRequest at 'https://public-api.wordpress.com/rest/v1.1/meta/sharing-buttons' from origin 'https://widgets.wp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
public-api.wordpress.com/rest/v1.1/meta/sharing-buttons:1 Failed to load resource: net::ERR_FAILED
```

**Comment by simison** [comment] 2021-02-09 10:23
Does the button still show up at the homepage of the site?

**Comment by retnonindya** [comment] 2021-02-09 10:59
Hi @simison! Thanks for checking this issue. I'm already EOD so I can't confirm your inquiry. However, the buttons are visible on the live site -- so I presume it should be visible on posts and pages (live site/front-end view) 🤔

On Calypso-side, it's not visible on Chrome when viewed using non-A8C WordPress.com account.

**Comment by davipontesblog** [comment] 2021-02-09 11:41
Upon further scrubbing, I am not able to repro this on my end. Neither on atomic, or on simple sites.
When choosing the official buttons they do take a second or two to come up. I am using Chrome Version 88.0.4324.146 (Official Build) (x86_64). 
Upon further inspecting a test site of mine, I found a hint that may explain what is happening here. On this older test site, I had two posts that were still using classic blocks, and I believe these were coming from when we made the block editor the default editor in WordPress.com. None of these two posts were showing any sharing buttons, no matter if I had "official" style selected, or any other styles. When I checked the Jetpack settings on the post, the option to display sharing buttons was unselected, which I then activated. When doing this, the buttons now show without a problem. I wonder if this is affecting more sites.

Here is a screenshot showing this:

<img width="1321" alt="Screen Shot 2021-02-09 at 08 32 55" src="https://user-images.githubusercontent.com/31009008/107358010-9961a100-6ab1-11eb-8686-bd51b48e2737.png">

Test site URL: Pay77C-hP-p2

<img width="776" alt="Screen Shot on 2021-02-09 at 08-39-25" src="https://user-images.githubusercontent.com/31009008/107358739-81d6e800-6ab2-11eb-8a85-e91d14043711.png">

**Comment by retnonindya** [comment] 2021-02-12 08:40
... aaaand the buttons are appearing (insert `:confused-dog:` Slack reactmoji here)

Thank you for checking this, @davipontesblog! I just got the opportunity to check this GitHub issue, and when I tried it on my end, I now able to see the buttons properly again now. I also can confirm my Chrome is Version 88.0.4324.150 (Official Build) (x86_64)

@simison -- Uhhh, I guess we can close this issue? 😅  It seems like the issue is now resolved. I'm going to close it now. In case this issue reappears in the wild, we can reopen it again with more details.

Thanks again for looking into this, all! 🙏

**Comment by Nic-Sevic** [comment] 2021-02-28 09:03
this seems to be happening again here with a twist: 3775860-zen
sharing isn't showing regardless of whether official buttons or not; also buttons are not showing on live site, preview, or in the calypso settings
On Hever theme and I can replicate on test site

**Comment by retnonindya** [comment] 2021-04-28 07:18
There is no detail on which browser the user is using and they are using Timepiece, but there is similar report about it here:
3929589-zd-woothemes

I able to see the sharing buttons, but the user couldn't. And the buttons are disappearing when I checked the Sharing Buttons section on the dashboard.

**Comment by daria2303** [comment] 2021-04-30 12:17
I got this again, The official facebook sharing button not working, checked on my test atomic site - got the same
28673247-hc
3950434-zd-woothemes

**Comment by aleone89** [comment] 2021-04-30 12:21
I've just had a report of this here hc-24253342 on a simple site, the Facebook button as above wasn't showing.

**Comment by daria2303** [comment] 2021-04-30 14:54
another one 3951216-zd-woothemes

**Comment by ezebecke** [comment] 2021-04-30 18:03
Another report with Facebook button not displaying: 29330008-hc

**Comment by JessBoctor** [comment] 2021-05-24 19:24
I had a report of none of the buttons working in 29769045-hc

**Comment by davipontesblog** [comment] 2021-05-25 10:09
Moving back to Prioritization since it's been reopened.

**Comment by scosgro** [comment] 2021-06-22 20:42
Just had a new report of this, where Facebook was going missing, and in testing, everything seemed to be going missing, in 29058786-hc.

Followup in 4087798-zd

Workaround in the meantime was to switch to a different button style (anything but Official Buttons).

**Comment by KirkwallDay** [comment] 2021-07-18 19:25
Found a new incidence of this here: 27993965-hc

Only affects Chrome, and they did try other browsers and they were fine. Also go the "What is my Browser" link here: https://whatismybrowser.com/w/956LEBX

**Comment by hacchism** [comment] 2021-08-14 23:42
Another case in 31132154-hc. I could see the issue on all browsers(Chrome, Firefox, Safari).

The user was okay with switching to a different button style so I suggested that.

**Comment by dcoleonline** [comment] 2021-11-15 02:08
Encountered in 4455111-zen where a customer was using a Blog Posts block to show posts inside of a page.

I tried the workaround of a different button style, but it only worked initially.
Once I refreshed, the icons disappeared again.

I tested a few sharing settings, and it noticed that the sharing buttons were only configured to show on posts.
Once I also enabled them on pages, the icons appeared consistently on the page.

This is what the customer had originally when the buttons were failing:

![image](https://user-images.githubusercontent.com/3505172/141710980-9850420a-fe81-4fc9-b2a4-953cdda7af01.png)

This is how the buttons looked as a result:

![image](https://user-images.githubusercontent.com/3505172/141711074-6f9fb46d-bd6f-41bc-a03f-ac865a954051.png)

I activated the sharing buttons on pages:

![image](https://user-images.githubusercontent.com/3505172/141710951-6971b76d-5220-4b29-9733-ef92de4db071.png)

This is how the buttons looked as a result:
![image](https://user-images.githubusercontent.com/3505172/141711122-47d0f91c-cf75-429a-9819-a904669e6847.png)

**Comment by edwinho89** [comment] 2022-03-11 07:47
4847758-zd-woothemes

Had the same issue on AT site - deactivating user plugins does not help, and toggling around settings makes no differences.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/34882260/157824556-3405c68e-b6ef-4a68-a7cd-8a61be5c95fd.png">


```
https://widgets.wp.com/sharing-buttons-preview/?service%5B%5D%5B0%5D=twitter&service%5B%5D%5B1%5D=facebook&service%5B%5D%5B2%5D=linkedin&more=More

widgets.wp.com/:1 Access to XMLHttpRequest at 'https://public-api.wordpress.com/rest/v1.1/meta/sharing-buttons' from origin 'https://widgets.wp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

https://s0.wp.com/wp-includes/js/jquery/jquery.js

jquery.js:688          GET https://public-api.wordpress.com/rest/v1.1/meta/sharing-buttons net::ERR_FAILED 200
```

**Comment by simison** [comment] 2022-03-11 10:54
@Automattic/team-calypso-frameworks do you know what has changed so that share-button preview loaded from `widgets.wp.com` [is not respecting](https://github.com/Automattic/wp-calypso/issues/47992#issuecomment-1064858352) `access-control-allow-origin: *` header?

**Comment by jsnajdr** [comment] 2022-03-23 14:30
> `widgets.wp.com/:1 Access to XMLHttpRequest at 'https://public-api.wordpress.com/rest/v1.1/meta/sharing-buttons' from origin 'https://widgets.wp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource`

@simison The offending request is a REST request to `public-api.wordpress.com`, and these don't support CORS and don't return `Access-Control-Allow-Origin` header. They are supposed to be called from same-origin, typically through the REST proxy.

Here it seems that some script on `widgets.wp.com` is sending a direct request to `public-api.wordpress.com`, instead of going through the proxy.

(sorry for a late reply, I missed the original ping and noticed it only now)

**Comment by as-esu** [comment] 2022-04-22 08:23
4966339-zen
as a workaround, they are using _Icon & Text_ display style.

**Comment by youbrokesomething** [comment] 2022-09-20 20:15
I'm not able to reproduce this issue and it's been five months since this issue was last updated. I'm going to close this issue, please re-open it if there's any new user reports.

**Closed as completed by youbrokesomething** 2022-09-20 20:15 UTC
Labels: Bug, [Feature] Sharing, [Pri] Normal, Publicize, Triaged
