### ISSUE TITLE
Calvin: bold text not applied in preview/live site

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/wp-calypso#73780] opened 2023-02-24 19:48 UTC
### Quick summary

Bold text applied to specific words using the Bold icon on the Gutenberg block toolbar show correctly in the editor but do not show on the preview or the live version.

### Steps to reproduce

1. Activate the Calvin theme.
2. Create a page and add some text to a Paragraph block.
3. Select some text and make it bold.
4. Publish the page.
5. View the live version and the preview.

### What you expected to happen

I would expect the text which is bold in the editor to appear as bold in the preview and live version too.

### What actually happened

Text is not bold in the editor, neither in the live version.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by ariel-maidana** [comment] 2023-02-24 19:49
Please notify the user when the issue is solved.
5990132-zd-woothemes

**Comment by cuemarie** [comment] 2023-03-23 21:05
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Could Not Replicate
- Tested on AT: Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Bolded text appeared as expected on the live site and previews in both simple and AT environments.


**AT Example**
<img width="1185" alt="Screen Shot 2023-03-23 at 2 04 33 PM" src="https://user-images.githubusercontent.com/27249804/227360899-9eb2ec5d-c8ea-44ae-a8be-ea9b7e51a75a.png">

**Simple Example**

<img width="998" alt="Screen Shot 2023-03-23 at 2 04 49 PM" src="https://user-images.githubusercontent.com/27249804/227360997-39b2f3cc-83ba-44f7-ac68-aae4e175182e.png">

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

**Closed as completed by cuemarie** 2023-03-23 21:05 UTC
Labels: Bug, [Pri] High, Triaged, [Closed] Not Reproducible, [Platform] Atomic

**Comment by cuemarie** [comment] 2023-03-23 21:09
I followed up with the user to confirm the issue is resolved for them here: 6067664-zd-woothemes
