### ISSUE TITLE
CoBlocks: Changing "Focal Point" in the Hero block settings causes "Attempt block recovery"

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#34944] opened 2019-07-28 16:18 UTC
#### Steps to reproduce
1. Add the Hero block to a page or post
2. Select a background image and change the "Focal Point" by clicking on "Background Settings"
3. Publish/Update the changes
4. Reload the editor

#### What I expected
To be able to normally edit the Hero block I just updated

#### What happened instead
Got this error on the block:

> This block contains unexpected or invalid content.

If I click on "Attempt Block Recovery” the block loads normally. However, the next time I refresh or open the editor the error will show up again.

#### Browser / OS version
Google Chrome Version 75.0.3770.142 (Official Build) (64-bit) | macOS Mojave 10.14.5 (18F132)

#### Screenshot / Video

Video link: https://cld.wthms.co/HQRjek 

#### Context / Source

#testing #dogfooding

**Comment by mmtr** [comment] 2019-08-17 03:28
Thanks @AtrumGeost! I'm not able to reproduce this issue (I followed the same steps you shared on that video), so I wonder if this has been fixed somehow after upgrading CoBlocks to 1.12.0 in WP.com.

Feel free to reopen this issue if you still get the same behavior.

**Comment by AtrumGeost** [comment] 2019-08-18 16:55
Hi @mmtr !

I was able to reproduce the issue again. I'm using the Modern Business theme, and also tried with the Redhill theme. So I don't think it is theme-specific.

Here's another video:

https://cld.wthms.co/vOkCSe

And the blog post where I added the block:

https://atrumtest01.wordpress.com/2019/08/18/hero-block-2/

Let me know if you need more information or if you want me to test something else :)

**Comment by kwight** [comment] 2019-08-19 22:30
Hm, I'm rather confused too – unable to replicate. To be clear, @AtrumGeost does this happen for you for every Hero block you add, or just that site maybe?..

**Comment by kwight** [comment] 2019-08-19 22:38
@AtrumGeost @mmtr Oh! I might be on to something: does it happen if you use the UI buttons (the "plus" on the left, or the popular shortcuts on the right), but _not_ if you use the text shortcut (`/hero`)?

<img width="856" alt="Screen Shot 2019-08-19 at 3 37 40 PM" src="https://user-images.githubusercontent.com/349751/63304306-644b0880-c297-11e9-854b-c9440de20a2b.png">

**Comment by AtrumGeost** [comment] 2019-08-20 12:57
Hi @kwight! Thanks for checking, but I got the same result with both options. Here's a video:

https://cld.wthms.co/eTXcZf

**Comment by kwight** [comment] 2019-08-20 17:19
Le sigh – my comments above were regarding https://github.com/godaddy/coblocks/issues/750.

**Comment by AtrumGeost** [comment] 2019-08-20 18:00
Oh, oh. Yes, sorry. I missed what you mentioned about the text shortcut 😅

In any case, the "This block contains unexpected or invalid content." error still appears when I change the "Focal Point". Doesn't matter the way I add the block :/

**Comment by kwight** [comment] 2019-09-06 16:53
Since this is specific to our integration with the Cover block, I'll close this in favour of https://github.com/Automattic/wp-calypso/issues/35762 and track progress there.

**Closed by kwight** 2019-09-06 16:53 UTC
Labels: [Goal] Gutenberg, [Type] Bug
