### ISSUE TITLE
Scheduled Posts Tab: Publish Time is Not Based on the Site's Time Zone

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/wp-calypso#41726] opened 2020-05-02 15:18 UTC
#### Steps to reproduce

1. Ensure that the site's time zone is different than your computer's time zone.
2. Navigate to My Site > Site > Posts, click on "Add New Post".
3. Schedule the post to publish at some point in the future.
4. Navigate to My Site > Site > Posts > Scheduled

#### What I expected
The time shown in the Scheduled tab should be displayed in the same time zone as your site.

#### What happened instead
The time shown in the Scheduled tab is different than what is shown in the editor. The editor shows the time based on the site's time zone whereas the Scheduled tab shows it based on your devices' time zone.

#### Browser / OS version
Chrome 81 and macOS 10.15.4

#### Screenshot / Video
![Screen Shot 2020-05-02 at 11 16 41](https://user-images.githubusercontent.com/42454301/80868130-90ac8680-8c66-11ea-80dc-7eb7aecefad1.png)
![Screen Shot 2020-05-02 at 11 16 58](https://user-images.githubusercontent.com/42454301/80868133-930ee080-8c66-11ea-85bc-5ae4d5b116a3.png)

#### Context / Source

#user-report here: 2932498-zen

**Comment by sserafini1** [comment] 2020-05-06 06:11
Hello :)

Which is the difference between the use of {localize} from 'i18n-calypso' and { withLocalizedMoment } from 'components/localized-moment'

Thank you in advance,
Have a great day!

**Comment by Robertght** [comment] 2020-05-20 12:00
Our user fixed the issue changing the timezone:

> Hi, we were able to fix the issue by changing the Time zone to UTC+3 instead of UTC+2.

**Comment by philnick206** [comment] 2020-06-01 13:48
Another report/example of this in #21236032-hc

**Comment by davipontesblog** [comment] 2020-06-01 14:00
Another report here: #21560992-hc:

![Screen Shot 2020-06-01 at 09 32 38](https://user-images.githubusercontent.com/31009008/83416457-ad1b1a80-a3ee-11ea-86f5-ff3e7d59d46b.png)

![Screen Shot 2020-06-01 at 09 49 21](https://user-images.githubusercontent.com/31009008/83416467-b1473800-a3ee-11ea-910f-3d24aedf2780.png)

**Comment by donalirl** [comment] 2020-07-27 00:31
Another case in #22741467-hc 
<img width="168" alt="schedule 1" src="https://user-images.githubusercontent.com/30727666/88493377-1a64b980-cff4-11ea-863a-9abee7fdd04a.PNG">
<img width="176" alt="schedule 2" src="https://user-images.githubusercontent.com/30727666/88493380-1cc71380-cff4-11ea-833e-9e69bed3c41c.PNG">

**Comment by aisajib** [comment] 2020-09-21 15:31
I had another issue today reported in #24240344-hc - it's confused to say the least as the user thought changing the timezone so they see the correct time on the Scheduled tab will solve it, when that wouldn't be the case. I was able to replicate it on my test site too so seems like the issue is still here.

**Comment by davipontesblog** [comment] 2021-04-08 14:03
I can not reproduce this issue because I ran into another bug while trying to do this. Clicking "Schedule" in the editor first did nothing, and then on a second click, it crashed the editor.

See here:

https://d.pr/i/ldRK0J/NduXhe5t48

The error that got copied is this:

`TypeError: Cannot read property 'isBeingScheduled' of undefined
    at Mi (https://s0.wp.com/_static/??-eJylkc1OAzEMhF8Ib7oU0V4Qz5Ifs7hN4pWddOHtyVZqJfaAgBzH8XyajM0yg+dcMBczxzpRVjPVJh3K1F4EzWXcDU/DDsQPo3GVYjBn/HRsJYC+sxRfixrKAT+Gkz6YfxELnzFDJC29pIUleK65G+Qi+zNgoMLSywq22KtNOHZ3tc5hJfaCUvuchVqoP5NgVesiwrW1bpyiXFBAKSAINlb3Bf52x2X2nLYaMDkMW3OqcPNrdeqF5kLc1BvHyMttnbKPNaCak5pr40OivGXZ0IZ33GQTQuKAq6dt3fUPESZkaBewa4Rv4vceK9rSUmmO1/QyPo+H4/7xuD+cvgCBPIG9:111:591)
    at we (https://s0.wp.com/wp-content/plugins/gutenberg-core/v10.4.0-rc.1/vendor/react-dom.min.de439aae.js?m=1599596311h:8:293)
    at zj (https://s0.wp.com/wp-content/plugins/gutenberg-core/v10.4.0-rc.1/vendor/react-dom.min.de439aae.js?m=1599596311h:14:21223)
    at Th (https://s0.wp.com/wp-content/plugins/gutenberg-core/v10.4.0-rc.1/vendor/react-dom.min.de439aae.js?m=1599596311h:11:728)
    at tj (https://s0.wp.com/wp-content/plugins/gutenberg-core/v10.4.0-rc.1/vendor/react-dom.min.de439aae.js?m=1599596311h:11:657)
    at Te (https://s0.wp.com/wp-content/plugins/gutenberg-core/v10.4.0-rc.1/vendor/react-dom.min.de439aae.js?m=1599596311h:10:7238)
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/v10.4.0-rc.1/vendor/react-dom.min.de439aae.js?m=1599596311h:7:1114
    at unstable_runWithPriority (https://s0.wp.com/wp-content/plugins/gutenberg-core/v10.4.0-rc.1/vendor/react.min.e713ea3b.js?m=1599596311h:3:3396)
    at Da (https://s0.wp.com/wp-content/plugins/gutenberg-core/v10.4.0-rc.1/vendor/react-dom.min.de439aae.js?m=1599596311h:7:824)
    at Pg (https://s0.wp.com/wp-content/plugins/gutenberg-core/v10.4.0-rc.1/vendor/react-dom.min.de439aae.js?m=1599596311h:7:1060)`

**Comment by kwight** [comment] 2021-04-08 14:32
> Clicking "Schedule" in the editor first did nothing, and then on a second click, it crashed the editor.

Being tracked here: https://github.com/Automattic/wp-calypso/issues/51767#issuecomment-815545152

**Comment by ericamQA** [comment] 2021-06-04 18:52
Closing as this was fixed for WPcom.

**Closed by ericamQA** 2021-06-04 18:52 UTC
Labels: Editor, User Report, [Status] Fix Inbound, [Type] Bug
