### ISSUE TITLE
Tiled Gallery block: Adding A Block from The Toolbar Sends Me Back to the Top of the Post

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/wp-calypso#29796] opened 2018-12-28 20:48 UTC
When adding a Tiled Gallery block using the block toolbar at the top to a post with lots of existing content, after adding images from the Media Library, I'm sent back to the top of the post.

I'd expect to go to the Tiled Gallery block so that I can continue to modify that to my liking.

To replicate:
1. Create a post with content. I added a Tiled Gallery block, an Image block and a paragraph block.
2. Add a Tiled Gallery with the block button in the toolbar.
3. Add images to the block from the Media Library. 
4. Click Insert.

Notice that you're sent back to the top of the post rather than remaining in the block itself.

**Comment by sirreal** [comment] 2019-01-07 19:36
I'm unable to reproduce this. What environment was this in?

**Comment by tmmbecker** [comment] 2019-01-07 21:23
It was in the calypso testing. I'm not able to reproduce it in wp-admin with Jetpack  Beta though so maybe it just fixed itself?

**Comment by sirreal** [comment] 2019-01-08 07:02
👍 Sounds like this was fixed by other work.

**Closed by sirreal** 2019-01-08 07:02 UTC
Labels: Tiled Galleries, [Goal] Gutenberg, [Type] Bug
