### ISSUE TITLE
New site flow via "All sites" or "Account" pages asks to create account

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#84402] opened 2023-11-22 08:44 UTC
### Quick summary

There's extra "continue" step in new site creation flow.

### Steps to reproduce

1. Have a user without any sites
2. Go to All sites `/sites`, site switcher sidebar, or Account at `/me/account` and create new site:

<img width="1279" alt="Screenshot 2023-11-22 at 10 41 29" src="https://github.com/Automattic/wp-calypso/assets/87168/e96dc8b1-1146-4dcf-b970-0deaee57d9e9">
<img width="1278" alt="Screenshot 2023-11-22 at 10 42 30" src="https://github.com/Automattic/wp-calypso/assets/87168/cff38016-5ed0-4a60-ac9d-d2e3a4957b94">
<img width="299" alt="Screenshot 2023-11-23 at 11 58 24" src="https://github.com/Automattic/wp-calypso/assets/87168/f54a5dc0-97e2-4b6d-8fd1-508e08bd6fa6">

3. It'll ask to "continue" or "login" which is unnecessary:

<img width="1289" alt="Screenshot 2023-11-22 at 10 42 56" src="https://github.com/Automattic/wp-calypso/assets/87168/7c2fb2fe-409e-4bf2-a522-d9a3ad50c269">

### What you expected to happen

Just continue to domains.

### What actually happened

Login screen.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by escapemanuele** [comment] 2023-11-23 11:50
The problem is [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/config/flows.js#L344): detectHistoryNavigation.loadedViaHistory() is false when we directly go to [wordpress.com/start](http://wordpress.com/start) in a new page, but it is true when clicking on the button. 
When it is true, the user step is not removed from the flow ( it doesn't call removeUserStepFromFlow( flow ) ), and so we go to the user social.

It was strange to me that this was affected by changes to `user-social`, so I tested using the old User step: bug is still there. So this has been around for a while!

**Comment by maciejpilarski** [comment] 2023-12-11 17:59
📌 REPRODUCTION RESULTS
– Tested on Simple – Could Not Replicate 


📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to recreate the issue on my test account without any sites.

When clicking on "create new site" I was directed to domain selection screen without the need to login again:
![Markup 2023-12-11 at 18 53 42](https://github.com/Automattic/wp-calypso/assets/9025643/d3faadf2-19d1-4705-9435-f30eb62dcbcc)


📌 ACTIONS
– Hey @simison and @escapemanuele are you still able to reproduce the issue on your side?

**Comment by escapemanuele** [comment] 2023-12-14 11:36
I'm still able to reproduce, clicking on the button here. You may have to try a couple of times

![image](https://github.com/Automattic/wp-calypso/assets/52076348/07a709b9-bacd-4a75-95c4-cca457359316)

**Comment by mmtr** [comment] 2024-07-24 11:25
Closing this one out, since apparently is no longer replicable:

https://github.com/user-attachments/assets/b71bb9e6-6804-4b8e-87d5-992d594c50ca


https://github.com/user-attachments/assets/3495f063-9206-4e01-99fe-0b804027709a

Feel free to reopen is the issue still persists.

**Closed as not planned by mmtr** 2024-07-24 11:25 UTC
Labels: Bug, Sites, [Pri] High, Triaged, [Closed] Not Reproducible, [Status] Priority Review Triggered
