### ISSUE TITLE
Sharing buttons: More sharing button unresponsive, and doesn't reveal hidden sharing buttons

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#47916] opened 2020-12-01 15:33 UTC
Our user has sharing buttons enabled through the options in _Tools_ > _Marketing_ > _Sharing Buttons_ in their WordPress.com dashboard. They have configured the buttons on this particular site as follows:

<img width="720" alt="Markup 2020-12-01 at 15 29 22" src="https://user-images.githubusercontent.com/2912202/100760641-a485ba00-33fa-11eb-8ec0-58bfc67ce04a.png">

Unlike their other site, the _More_ button doesn't reveal the hidden icons, whether on mouse hover, or by clicking on the button. Here's a comparison:

![20201201_153142_screenshot](https://user-images.githubusercontent.com/2912202/100760674-aea7b880-33fa-11eb-9ebd-c48bee23fb1d.gif)

This issue may be related to #42151

#### Steps to reproduce

1. Starting at URL: https://kenschristiandevotions.com/2020/12/01/gods-moment/
2. Scroll down to the sharing buttons at the end of the post
3. Mouse over the _More_ button, and click on it, to reveal the hidden icons

I noticed that when I hovered my mouse over the _More_ link, my browser suddenly indicated that the browser session was not fully secured over SSL. I took a closer look at the links for the sharing buttons, and noticed that the Blogger icon had a `http://` link -

```
<li class="share-custom share-custom-blogger"><a rel="nofollow noopener noreferrer" data-shared="" class="share-custom share-custom-blogger sd-button share-icon no-text" href="https://kenschristiandevotions.com/2020/12/01/gods-moment/?share=custom-1533382753&amp;nb=1" target="_blank" title="Click to share on Blogger"><span style="background-image:url(&quot;http://Blogger.com&quot;);"></span><span class="sharing-screen-reader-text">Click to share on Blogger (Opens in new window)</span></a></li>
<li class="share-end"></li>
```

I removed the button, and the SSL issue seemed to go away -

<img width="1007" alt="Markup 2020-12-01 at 15 39 30" src="https://user-images.githubusercontent.com/2912202/100760729-bff0c500-33fa-11eb-833d-1709613da652.png">

This didn't seem to resolve this current issue, though.

#### What I expected

On mouse hover, the _More_ button would reveal the hidden icons, like the button behaves on the user's other site, here:

![20201201_151920_screenshot](https://user-images.githubusercontent.com/2912202/100760817-d7c84900-33fa-11eb-8723-51f988ae4b38.gif)

#### What happened instead

Instead, the _More_ button is unresponsive.

#### Browser / OS version

I tested this on macOS 11.0.1 with the following browsers:

- Firefox Developer Edition v84.0b6, and
- Brave Version 1.17.73 Chromium: 87.0.4280.67 (with, and without Shields)

The site is using the [Plane Theme](https://wordpress.com/theme/plane). Switching to the Twenty Twenty theme in preview in the Customizer didn't produce a different result.

The user appears to have been on Windows. 

#### Screenshot / Video

See above.

#### Context / Source

This is a referral from a customer in 26030837-hc with a follow-up in 3535030-zen

**Comment by kriskarkoski** [comment] 2020-12-02 20:19
@sgomes It looks like your fix for https://github.com/Automattic/wp-calypso/issues/47705 is not working. Can you check if this is the same cause as before?

**Comment by wynwin** [comment] 2020-12-02 20:23
Another report here 25949754-hc

**Comment by sgomes** [comment] 2020-12-03 10:31
Thank you for pointing me to this, @kriskarkoski! This appears to be a separate issue, but possibly related to my work as well. Investigating.

**Comment by sgomes** [comment] 2020-12-03 10:40
It appears that the More menu is opening, but in the wrong location (further up the page). Investigating.

**Comment by sgomes** [comment] 2020-12-03 12:12
The fix for the menu positioning issue is ready for review at D53698-code. That appears to be only part of the issue of what @pauljacobson was reporting, however, so it may not close this issue.

**Comment by katiebethbrown** [comment] 2020-12-06 21:23
Another report in 3550634-zd-woothemes

I've let the user know they can set the buttons as main sharing buttons instead of having them under the "More" heading, and shared that I'd let them know when the issue was resolved.

**Comment by sgomes** [comment] 2020-12-07 10:05
Still waiting for a review on D53698-code.

**Comment by sgomes** [comment] 2020-12-08 10:51
D53698-code has been deployed.

@pauljacobson: I have checked and this appears to have fixed the issue. Could you please take a look as well? Thank you!

**Comment by katiebethbrown** [comment] 2020-12-12 03:46
@sgomes - Just wanted to drop a note that I checked on the site from my report above and the fix appears to be working as intended. The more buttons again display and are functional on hover:

<img width="540" alt="W0pIrW" src="https://user-images.githubusercontent.com/42279181/101971910-f3e59a80-3bf1-11eb-9601-fbba5b296bfd.png">

**Comment by sgomes** [comment] 2020-12-14 10:50
Thank you for letting me know, @katiebethbrown! 👍 It's great to hear it's working beyond the sites I've tested it in 🙂

**Comment by cathymcbride** [comment] 2021-01-28 19:34
closing based on final comment.

**Closed as completed by cathymcbride** 2021-01-28 19:34 UTC
Labels: Bug, [Feature] Sharing, [Pri] Normal, User Waiting, Publicize, [Source] User testing
