### ISSUE TITLE
New Launch + Nav Unification: Blank white screen

### ISSUE THREAD

**Issue by psealock** [Automattic/wp-calypso#50781] opened 2021-03-05 01:13 UTC
### Steps to reproduce the behaviour

This is Gutenberg's new launch flow. The error messages at the end suggest the problem may lie with Nav Unification.

```
Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('is-new-launch-flow is-nav-unification') contains HTML space characters, which are not valid in tokens.
```

1. Create a new site at https://wordpress.com/new?ref=calypso-selector
2. Choose a domain
3. Choose a theme
4. Choose a font
5. Choose some features. Here I selected ones that led me to the eComm plan, ie Store. I haven't tried other combinations
6. Select a plan
7. See the site being built
8. Then see the white blank screen

<img width="1617" alt="Screen Shot 2021-03-05 at 2 02 34 PM" src="https://user-images.githubusercontent.com/1922453/110052349-5b0f8700-7dbc-11eb-91e1-5d419f34ed16.png">

#### What I expected to happen

To see the checkout page

#### What actually happened

White screen + errors in the console.

### Context

Proxxy'ed and logged in as Automattician with Nav Unification turned on

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

I can't purchase, so seems important

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

100% consistent

**Comment by getdave** [comment] 2021-03-05 11:17
We're working on a fix for this now.

Note accepting a variable to `document.body.classList.add()` is the cause. Ideally, we should avoid this as it's too easy to introduce an error, especially for IE11.

https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

**Closed as completed** 2021-03-05 11:53 UTC
Labels: Bug, [Pri] BLOCKER, [Feature] Calypso & wp-admin Navigation, Triaged
