### ISSUE TITLE
Help: Chat box disappears until operator replies

### ISSUE THREAD

**Issue by vparkhere** [Automattic/wp-calypso#1818] opened 2015-12-18 15:29 UTC
When I clicked on "Chat with us," the chat box appeared at the lower right corner rather than being taken to a new window with the chat inside it.

After typing in the chat box and pressing "Enter," the chat box immediately disappeared and did not appear until the operator responded.  After a response, if I didn't answer fast enough, the chat box disappeared on its own after a little over 10 seconds.

Here's a screencast: https://cldup.com/bDA2wEZgLN.mov

I was unable to reproduce the issue.  Talked to Daryl about it, it's possibly because of cookies that I had in the browser beforehand that allowed me to double-click "Chat with us" and made the old chat window pop up rather than be directed to a new window with the chat embedded.  After opening up a new incognito window, chat worked beautifully.

Working from Chrome 47 on OSX El Capitan.

**Comment by dllh** [comment] 2015-12-18 18:48
I think this may be resolved with some changes we shipped late last night (this was part of yesterday's testing session, right?). I've not ever managed to repro, and if we can't repro, I'm not sure we can ship a fix. Will leave this open so that we can dig into it some more and try to repro, though.

**Comment by eurello** [comment] 2015-12-18 21:07
I have been able to reproduce this in both Calypso and WP Admin if I have more than one tab open at once. From what I can figure out, if you have the chat going in two tabs simultaneously, it persists in the first tab, but in the second tab, the box disappears sporadically.

**Comment by dllh** [comment] 2015-12-18 21:17
We had another issue with chat in multiple tabs reported in #1508. I doubt they're related, but I thought it worth mentioning just in case.

**Comment by eurello** [comment] 2015-12-18 21:42
I had that issue as well. I don't think it's the same as the disappearing chat box, except that just in general, this doesn't seem to work super well if you have multiple tabs open. That might not matter, except for some of the links in Calypso open in a new tab automatically, like Portfolios. 

For me, when I did that, the chat box didn't stay visible in the new tab (WP Admin) unless I closed out the Calypso tab I'd just come from. But then, I tried to walk another HE through this and they couldn't repro, so not sure if it was just me.

**Comment by dllh** [comment] 2015-12-18 21:55
I've just spent a few minutes trying to reproduce this, so far with no luck. I started a chat in Calypso and then opened a wp-admin link in a tab. Then I chatted from both tabs a little bit in hopes of seeing the issue. I toggled operator availability too, thinking perhaps that if the operator goes away while you're chatting in one tab, the other tab will get confused and disappear, but that didn't trigger the issue. 

The issue I noted above was manifest, but I could never get the tab to go away. If you can reproduce reliably, I'd be glad to give it a try with repro steps. For the moment I'm at a loss.

**Comment by eurello** [comment] 2015-12-18 22:12
Last time I did this, I could reliably reproduce it every time. But! I just tried again and now I cannot at all, in Calypso or in WP Admin. I sort of wonder if, because @vparkhere repro'd it too but not in an incog window, if there's some HE extension or script we're both using that was interfering. 

Either way, Kris couldn't repro at the time, and I can't now, so feel free to close.

**Comment by dllh** [comment] 2015-12-18 22:18
Alrighty. I think that sometimes our accounts and cookies get so cluttered with various garbage that we wind up seeing bugs that normal users won't see, so hopefully that's what we're experiencing here.

**Closed by dllh** 2015-12-18 22:18 UTC
Labels: Support, [Type] Bug
