### ISSUE TITLE
Blog Posts Block should ignore manual excerpt length and respect the block's excerpt length settings

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#56094] opened 2021-09-08 10:03 UTC
### What

Make the Blog Posts Block ignore any existing manual excerpt length and force the post excerpt to be displayed as per the Block settings.

### Why

When a manual excerpt is set, the Blog Posts Block's excerpt length setting is not respected, creating a visually jarring and inconsistent experience.

Example:
&nbsp;

![Markup on 2021-09-08 at 17:54:29](https://user-images.githubusercontent.com/66711744/132488390-1a919122-c135-4de4-9fc7-a66a0d8c9df1.png)

&nbsp;
The above screenshot shows the excerpt length set to 10 words. When a manual excerpt is set in the lock Editor, the excerpt length will not change regardless of if the excerpt length in the block is set to 10 or 100 words.

### How

The excerpt length should change based on the settings selected by the user, even with a manual excerpt is set in the Block Editor.

We could do this by adjusting the length of the manual excerpt or by overriding it completely and taking the first block of text from the page.

The latter will be undesirable for users who have hand-crafted excerpts created for SEO or related purposes.

**Comment by zdenys** [comment] 2021-09-10 10:01
I think it's a duplicate of https://github.com/Automattic/wp-calypso/issues/51415 Isn't it?

**Comment by synora** [comment] 2021-09-15 13:17
@inaikem this issue seems like a duplicate of [#51415](https://github.com/Automattic/wp-calypso/issues/51415). Your experience matches what's going on in the other issue, which I'm also able to replicate. I'll close this one for now but feel free to open it back up.

**Closed as completed by synora** 2021-09-15 13:17 UTC
Labels: Enhancement, Blocks, Triaged, [Block] Blog Posts
