### ISSUE TITLE
Editor: changing a featured image doesn’t show up in the preview

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#22772] opened 2018-02-23 19:41 UTC
Steps to reproduce:

1. Go to My Sites > Blog Posts > Add.
1. Add a title, body, and featured image then publish the post.
1. Change the featured image and click the "Preview" button.

<strong>Result:</strong> previews on published posts do not reflect changes to featured images.

<strong>Video:</strong> [1m1s](https://cloudup.com/cL2bYS3oNa1)

![screen shot 2018-02-23 at fri feb 23 12 39 36 pm](https://user-images.githubusercontent.com/1119271/36613458-cd84ebba-1896-11e8-9812-7bdbc43766c5.png)

<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11801 using Firefox 58.0.2 on macOS 10.13.3.</sup>

/hat tip 🤠 @beaulebens for reporting this issue at p4k3M4-2uX-p2. #dogfooding #painpoint

**Comment by rachelmcr** [comment] 2018-02-26 15:54
Looks like this is a duplicate of https://github.com/Automattic/wp-calypso/issues/22083.

**Closed by rachelmcr** 2018-02-26 15:54 UTC
Labels: Editor, [Type] Bug
