### ISSUE TITLE
Blog Post Block Post Spacing

### ISSUE THREAD

**Issue by sbathompson-he** [Automattic/wp-calypso#62318] opened 2022-03-28 22:12 UTC
### Quick summary

It appears the spacing on the last two posts in a blog post block is adding an extra space that is unwanted. Here is what it looks like.
<img width="624" alt="Markup 2022-03-28 at 13 03 55" src="https://user-images.githubusercontent.com/77308634/160495648-f1c08b9c-5d0f-4534-bcc6-695727cd32c4.png">
<img width="1629" alt="Screenshot on 2022-03-28 at 12-57-40" src="https://user-images.githubusercontent.com/77308634/160495658-72d3f48b-bd7b-489c-beda-79154184b46e.png">
 

### Steps to reproduce

Only occurring on this site. 

### What you expected to happen

No spacing like this. The next post should show up next to it. 

### What actually happened

Spacing

### Simple, Atomic or both?

Simple, Atomic 
4901558-zd-woothemes

### Reproducibility

Once

### Severity

One

**Comment by edwinho89** [comment] 2022-03-31 07:07
Looks to be expected result as blog post tends to justify posts there. I replied to the user and shared screenshots as comparison on different columns.

**Comment by vajrasar** [comment] 2022-04-13 18:19
Hey @sbathompson-he thanks for the report. 

I checked and I was able to replicate the issue on both the Simple and Atomic sites, and the issue does not seem to be dependent on the themes. 

The issue seems to be showing up when you put an odd Column value on the block, and not when the value is even. I checked with the 3 vs. 2 column layout, and the 3-column layout showed the issue.

![Screen Shot on 2022-04-13 at 23:41:46](https://user-images.githubusercontent.com/2210243/163244805-edb0af04-efaf-47dc-895a-a6e9f006b2b6.png)

@edwinho89 can you please elaborate more on your comment?

**Comment by vykes-mac** [comment] 2022-06-16 22:59
This issue was fixed in the newspack-block repo https://github.com/Automattic/newspack-blocks/pull/1173

**Comment by metabreakr** [comment] 2022-08-16 14:27
Re-opening this issue. User is 36492363-hc has just encountered it again.

**Comment by vykes-mac** [comment] 2022-08-17 21:21
This issue is actually resolved however the fix is not synced to Wordpress.com as yet. The newspack team will include it in their next team call. See [slack conversation ](p1660763548381799-slack-CUXC1FUTH)

**Comment by mpkelly** [comment] 2022-10-24 07:56
Confirmed that this is fixed now in prod. If anyone disagrees please reopen the issue. 

![image](https://user-images.githubusercontent.com/6851384/197476049-f5fe35c7-2c58-4972-b86a-d6ba23a2f3b2.png)

**Closed as completed by mpkelly** 2022-10-24 07:56 UTC
Labels: Bug, [Pri] High, [Block] Blog Posts, Build Maintenance
