### ISSUE TITLE
Nav Unification: Links manager missing

### ISSUE THREAD

**Issue by jackiejade** [Automattic/wp-calypso#51188] opened 2021-03-18 15:26 UTC
If a user is utilizing the Links Widget, they are not able to find the link manager that used to be in the sidebar of WP Admin. As seen here in the support page:

https://wordpress.com/support/blogroll/

If the user wants to edit these links they can still do so with a direct link appending `/wp-admin/link-manager.php` to their domain. 

This might be good to fall under customization in the customizer. Or it may fit under Appearance.

**Comment by supernovia** [comment] 2021-03-19 00:27
I understand [we intentionally removed it](https://github.com/Automattic/wp-calypso/issues/48177). Noting another complaint here:
https://wordpress.com/forums/topic/links-258/

**Comment by csonnek** [comment] 2021-03-19 13:57
Another user having trouble with that link missing: https://wordpress.com/forums/topic/add-and-edit-links/

**Comment by obenland** [comment] 2021-03-19 21:43
@mmtr It looks like we'll have to be a bit more surgical with our approach and leave it in place for customers that are using the feature.

On Simple Sites the feature is currently kept active through a filter (see p58i-1gB-p2/#comment-13859), I wonder if we could only have that return true on sites where the links are different from the default set. Or even better, have that option reflect the true state. [`maybe_disable_link_manager()`](https://developer.wordpress.org/reference/functions/maybe_disable_link_manager/) does something similar in a crude way.

**Comment by kaitohm** [comment] 2021-03-23 06:39
Noting this user is missing the Links in the nav, while another admin on the site DOES see it. 3839654-zd-woothemes
They are confused by this, as they would expect all admins to have the same view.

**Comment by jackiejade** [comment] 2021-03-23 19:55
Another user looking for this: 28019006-hc

**Comment by obenland** [comment] 2021-03-23 20:11
@tjcafferkey @mmtr Could we prioritize this to just after we did the next rollout bump?

**Comment by synora** [comment] 2021-03-24 11:29
Another report #3844279-zen.

**Comment by tjcafferkey** [comment] 2021-03-24 16:25
This has been fixed for WPCOM Simple sites and will be fixed for Atomic on the next WPCOMSH deployment which should be soon.

**Comment by mmtr** [comment] 2021-03-24 16:36
The fix for Atomic is now live.

**Comment by Thelmachido** [comment] 2021-03-27 11:05
Reopening this one because some sites are not showing the links option in Dashboard as expected. 

If the site had never used or added links, the [Links section](https://en-support.files.wordpress.com/2008/12/links-full-screen.png) will be missing in the Dashboard. You will only be able to view the links by opening this link ` /wp-admin/link-manager.php`. Once you add a link then you will have the links option in Dashboard. 

On this account [thelmachido](https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=thelmachido), I now have the Links section on all sites after [adding a link here](https://home123943606380.wordpress.com/wp-admin/link-manager.php) 

On this account [thelmapractise](https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=thelmapractise) we don't have the Links Section on all the sites.

**Comment by mmtr** [comment] 2021-03-29 10:31
That's the intended behavior @Thelmachido. We don't what to show the Links section to users who have not used it, since the feature was deprecated a long time ago. See https://github.com/Automattic/wp-calypso/issues/48177. 

The Links Manager was itself removed from core [8 years ago](https://core.trac.wordpress.org/ticket/21307#comment:73) and replaced with a plugin. Users looking into this feature in general are better off just creating an actual menu and adding it as a Navigation Menu Widget.

**Closed as completed by mmtr** 2021-03-29 10:31 UTC
Labels: Bug, [Pri] BLOCKER, [Feature] Calypso & wp-admin Navigation

**Comment by supernovia** [comment] 2021-04-07 22:37
Just noting we had a super edge case where someone had a site without a blogroll, used a direct link to add three links, and still did not see the Links Manager link in their sidebar.

A fourth link at /wp-admin/link-add.php did the trick.
