### ISSUE TITLE
Homepage banner checklist showing up

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#71404] opened 2022-12-21 11:29 UTC
### Quick summary

A user contacted us in 37564209-hc asking why is the "Update your Homepage" banner showing up now.

![WS5zuX.png](https://user-images.githubusercontent.com/6737345/208893936-15aae7af-8915-48aa-b57d-79070cafd590.png)

cc @Automattic/cylon as discussed in Slack

### Steps to reproduce

I couldn't replicate this locally but I asked here: p1671621470712569-slack-C02DQP0FP

### What you expected to happen

For the banner to go away as soon as I updated it or to remain inactive if that task was completed(I cannot verify if this was true when the user contacted us, but I noticed their site was already built for a couple of months)

### What actually happened

I updated the homepage by clicking o the "Update" button from that page and then the banner notification went away but only after a few minutes.

Also, when clicking o the "Edit Homepage" button, that would lead them to create new post instead of the homepage. I couldn't replicate this either

### Context

37564209-hc

5806888-zd-woothemes (followup)

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Once

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Update the homepage and wait for the banner to update itself on the home dashboard.

**Comment by zachspears** [comment] 2022-12-29 00:22
Since this cannot be reproduced, I am closing the issue for now. If there are additional reports, please reopen.

**Closed as completed by zachspears** 2022-12-29 00:22 UTC
Labels: Bug, [Pri] Low, Triaged, [Platform] Atomic
