### ISSUE TITLE
Block Widgets: Not Possible to Select a Group Block Added to Widgets Without Using the List View Or Adding Contents

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#56151] opened 2021-09-09 18:57 UTC
### Quick summary

Once a group block has been added to a block widget area, there is no way to select it to see the block toolbar without using the List view on the `widgets.php` page. This means block selection/editing/removal isn't available for group blocks in the customizer.

### Steps to reproduce

1. Open a site's Customizer view and navigate to a widget area.
2. Add a group block.
3. Click on the block to select it.

### What you expected to happen

The UI to indicate that the group block is selected and a block toolbar or editing options to be available.

### What actually happened

Nothing at all.

It is possible to select the group block in the full-page `widgets.php` view by clicking on it in the list view.

### Context

Noticed during other testing.

Screenshots:

In the Customizer:
![selectgroupcustomizer](https://user-images.githubusercontent.com/42279181/132746079-67f73e21-1940-4b87-8acf-00ddeed58ba2.gif)

On widgets.php:
![selectgroupwidgetsphp](https://user-images.githubusercontent.com/42279181/132746123-32e0a1fb-c14a-4c75-b297-5a1fbd76510c.gif)

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Workaround details

The group block can be selected using the list view option on widgets.php, but we redirect the menu item that opens this page, so users would need to know it and enter it manually to get there.

**Comment by katiebethbrown** [comment] 2021-09-09 18:59
Adding that I did find a workaround:

I was able to select the group block once I added a block inside of it, using the nested block's "parent block" setting, but it wasn't intuitive or labeled in a way that made it easy to discover.

<img width="522" alt="Screen Shot 2021-09-09 at 12 58 12 PM" src="https://user-images.githubusercontent.com/42279181/132746695-06d07172-9899-47df-930e-d64825b6ee79.png">

It also feels less than optimal to require users to add a nested block inside the parent block just to be able to see the option to remove the parent block.

**Comment by katiebethbrown** [comment] 2021-09-09 23:24
Ran into this again in 31586169-hc. 

User had an empty paragraph block in a sidebar, causing the sidebar to display on the site as an empty space. Clicking on the block does not select it (in either customizer or widgets.php view) until you add actual text to it.

The Widget view in the Customizer wasn't styled in a way that made it clear that there was a block there:

<img width="321" alt="emptyparagraph" src="https://user-images.githubusercontent.com/42279181/132775115-c4dbf288-e68f-40ab-a3cd-e00dc1dcbbaf.png">

**Comment by cometgrrl** [comment] 2022-08-18 21:59
This is reproducible in core WordPress. Also, it is selectable by clicking on it, although sometimes it pops up the menu to select a block to add to the group, and other times the block toolbar is displayed.

**Comment by jamiepalatnik** [comment] 2022-08-25 19:31
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated
- Tested on Self-hosted - Replicated
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- Was able to replicate this in all tests.
- Noting that the menu item for Appearance > Widgets in the WordPress.com dashboard opens WP Admin widgets. It no longer redirects to the Customizer.

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Added to 'HE Cross-repo Watchlist' project board
- Transferred to Gutenberg external repo: https://github.com/WordPress/gutenberg/issues/43619

**Comment by cuemarie** [comment] 2023-10-05 00:05
Looks like this was fixed in core: https://github.com/WordPress/gutenberg/issues/43619#issuecomment-1228321738

Tested on simple and confirmed this is working well now.

📌 ACTIONS
- Closing as resolved

**Closed as completed by cuemarie** 2023-10-05 00:05 UTC
Labels: Bug, [Pri] Normal, [Status] Core Fix Needed, Triaged, [Goal] Block widget editor, Block Widgets
