### ISSUE TITLE
[Bug]: ETK: translation isn't working almost everywhere in the ETK

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#63611] opened 2022-05-13 13:08 UTC
### Quick summary

The ETK is only rendering English UI. I'm not sure why, but I've found out that [this function](https://github.com/Automattic/wp-calypso/blob/add/reset-helpcenter-store/packages/i18n-utils/src/locale-context.tsx#L40) is unable to detect the locale. Because `language` is always undefined. 

/cc @p-jackson @noahtallen 

### Steps to reproduce

1. Start a new page in a non-English user.
2. The patterns will be in English.

### What you expected to happen

They should be in the user's language.

### What actually happened

They're in English.

### Context

May be related to: https://github.com/Automattic/wp-calypso/pull/63227

### Reproducibility

Consistent

**Comment by noahtallen** [comment] 2022-05-14 20:39
Oh no. Another guess is that it could be related to how we have to pass the locale to the window object, cc @arthur791004. Some more references to that:

- https://github.com/Automattic/wp-calypso/pull/55527

I was refactoring it here https://github.com/Automattic/wp-calypso/pull/62897#discussion_r853507397

and I noticed that the window locale data was only used by a couple of the apps. I'm curious if those apps _are_ working and if we need to apply that solution to the other apps as well.

**Comment by noahtallen** [comment] 2022-05-14 20:42
An example of where that is used is: https://github.com/Automattic/wp-calypso/blob/27c0527647b7c7d96767890c170e5d53391006f8/apps/editing-toolkit/editing-toolkit-plugin/tags-education/src/add-tags-education-link.js#L31

**Comment by p-jackson** [comment] 2022-05-16 04:20
Darn, I'd just recently tested this as part of #63227, so I feel like this must be a recent regression.

> 1. Start a new page in a non-English user.
> 2. The patterns will be in English.

In terms of the new page modal, I don't believe the pattern thumbnails themselves will actually be translated using the user's UI language. That's because the patterns will use the _site's_ language. It's this way because you're going to insert the pattern into the site, so it should match the language of the site content.

In saying that, the `Pick a pre-defined layout or start with a blank page.` copy at the top of the modal should use the UI language.

**Comment by noahtallen** [comment] 2022-05-16 16:33
Some findings testing on a user account with ES locale but site with EN locale

- What's new is correctly translated
- The text of page patterns text is _not_ translated (it's EN), which is technically correct
- The page patterns UI text is _not_ translated (it's EN), which is incorrect
- Nav sidebar _is_ translated
- Timeline block is at least partially translated
- A8c block patterns (not page patterns) _are translated_, both UI and text, even though the site's locale is EN. (So it's not using the site locale for patterns, but it is using my user locale for the UI)

So it seems like the site locale is used inconsistently with patterns and with page patterns (which are two different things in ETK). UI translation for many features does seem to be correct, outside of the page patterns modal :thinking:

**Comment by lsl** [comment] 2022-06-14 07:20
Does ETK configure a `<LocaleProvider />` like [the readme suggests](https://github.com/Automattic/wp-calypso/blame/trunk/packages/i18n-utils/README.md#L13-L16)?

Trying to figure out why `useLocale` / `i18n-utils` is looking at ETK window globals re https://github.com/Automattic/wp-calypso/pull/63608.

Ran into an issue with the window deref in `/log-in` SSR.

**Comment by noahtallen** [comment] 2022-07-11 21:18
I'm guessing it doesn't. That could also be awkward to do, considering that much of ETK is a collection of "mini react apps." Or my other thought is that Gutenberg might add that provider. Most (all??) of everything in Gutenberg would be rendered within the Gutenberg react tree after all

**Comment by cuemarie** [comment] 2023-05-17 21:48
_This report was found during a recent backlog sweep._

📌 ACTIONS
- Assigned to @Automattic/i18n

**Comment by lsl** [comment] 2024-11-07 03:00
ETK is now in Jetpack wpcom mu plugin and I think this is resolved per https://github.com/Automattic/i18n-issues/issues/858

e.g. welcome tour is translated:

<img src="https://github.com/user-attachments/assets/28434fcc-2438-4a44-b0c5-55575a5efa8a" width=300 />

**Closed as completed by lsl** 2024-11-07 03:00 UTC
Labels: Bug, [Pri] High, [Pri] Normal, i18n, Editing Toolkit, Needs triage, Groundskeeping
