### ISSUE TITLE
Gravatar My Profile tab closes automatically from /me

### ISSUE THREAD

**Issue by cecilerainon** [Automattic/wp-calypso#6942] opened 2016-07-21 09:36 UTC
Hello! I noticed a strange issue while wanting to update my Gravatar info. Basically the tab closes itself automatically after clicking on My Profile. I noticed there was the following link extension, which could be the culprit? `wpcc-no-close`
#### Steps to reproduce
1. Go to https://wordpress.com/me
2. Click your profile picture. It opens Gravatar in a new tab
3. In the Gravatar tab, click My Profile
4. The tab closes automatically
#### Screencast

![gravatar](https://cloud.githubusercontent.com/assets/16645645/17018179/dfac54ac-4f36-11e6-8fb1-4d4d6766e315.gif)
#### What I expected

Being able to access My Profile
#### What happened instead

The tab closed
#### Browser / OS version

Latest Google Chrome and Firefox
#### Reproduced?

Same situation on another account

**Comment by hoverduck** [comment] 2016-10-31 19:48
#bug-scrub

Closing, unable to reproduce in OSX Chrome, Firefox, Safari, or Windows 10 Edge

**Closed by hoverduck** 2016-10-31 19:48 UTC
Labels: Me, [Type] Bug

**Comment by geshultz** [comment] 2016-11-04 22:10
I'm having the exact same problem as the OP in Chrome.

**Comment by KDNX** [comment] 2017-07-22 01:07
I'm having the same problem, running Windows 8 (.1?) on Google Chrome.

**Comment by davewallace** [comment] 2017-08-14 05:08
Same problem on new Macbook Pro, Sierra, using Chrome.
