### ISSUE TITLE
Premium content block: member can access the content after the first 24 hours

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#68506] opened 2022-10-03 05:50 UTC
### Quick summary

We have someone who is unable to access their content in the first approx 24 hours after the subscription is renewed.

The user tried to log out/in and to clear the cache, but this didn't help:

>I also tried using an incognito Chrome browser (no cookies), signed in again, and got the same result.
I have tried different browsers (Chrome, Safari)
This behaviour happens on the monthly anniversary of my subscription.

Other info:

>I am based in Australia, so perhaps this is a timezone-related issue in your payment code.

cc @Automattic/ajax for further help 

bcc @inaikem 

### Steps to reproduce

We cannot replicate the issue, however the user shared a video in the ticket

### What you expected to happen

To be able to see the content after the renewal

### What actually happened

It didn't work.

### Context

5584857-zen 

Please check the ticket with the video they shared.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

No

**Comment by Robertght** [comment] 2022-10-04 05:18
Another report in #5604470-zen

![image](https://user-images.githubusercontent.com/6737345/193740227-31b14080-552f-4e03-a924-08c43a825dde.png)

It's related to the above case.

**Comment by cuemarie** [comment] 2022-10-04 20:48
📌 SCRUBBING : RESULT 
- Tested on AT: **Could Not Replicate** on separate test site

📌 FINDINGS/SCREENSHOTS/VIDEO
- For good measure, I tried replicating this issue on a test site with the same plugins installed, and the same theme installed as the user above. 
- The Login button was available right away after subscribing, and worked as expected. 

*Before Subscribing*

![Markup on 2022-10-04 at 13:40:43](https://user-images.githubusercontent.com/27249804/193923754-d68e971c-a14c-44da-a879-043ab9b649bb.png)

*Confirmation of Subscription*

![Markup on 2022-10-04 at 13:41:22](https://user-images.githubusercontent.com/27249804/193923809-591cfb45-4404-4a7c-a0ec-306ce5f0f59c.png)

*After Subscribing*

https://user-images.githubusercontent.com/27249804/193924272-bd35079c-f8f3-412f-964a-f2c147eda6a2.mp4

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Escalated here: p1664916725926879-slack-CJS75TX3R

**Comment by rcrdortiz** [comment] 2022-10-05 06:29
I'll add this issue to team Ajax's board so that we can have a look as soon as possible.

**Comment by cuemarie** [comment] 2022-10-31 23:04
Cross-posting this similar issue with Premium Content: https://github.com/Automattic/wp-calypso/issues/69427

The subscribers that are noted in that report cannot see premium content even after the first 24 hours, it seems, but wanted to note it here in case these issues have a shared underlying cause.

**Comment by mmtr** [comment] 2024-07-24 10:54
Hey @Automattic/gold, this sounds like an issue you can help with. Do you mind taking it a look? Thanks!

**Comment by lsl** [comment] 2024-08-06 05:48
> Cross-posting this similar issue with Premium Content: https://github.com/Automattic/wp-calypso/issues/69427

This does look related, added it to the board as well.

**Comment by TimBroddin** [comment] 2024-08-20 12:06
I tried reproducing this but failed. @Automattic/gold has more background in this area of the code, I think they're in the bets position to take a stab at this.

(cc @miksansegundo )

**Comment by millerf** [comment] 2024-08-20 12:32
CC @pottedmeat You might be the one with latest knowledge about this. 
We tried to fix this so many times I lost track.

**Comment by millerf** [comment] 2024-08-21 09:35
This seems to be a duplicate of https://github.com/Automattic/wp-calypso/issues/80974
Can we close this @TimBroddin ?

**Closed as completed** 2024-08-21 09:36 UTC
Labels: Bug, [Pri] High, Earn, Premium Content, [Feature Group] Customer Seller Experience, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature] User Payments & Donations
