### ISSUE TITLE
Nav Unification: Add Bulk Editing link to Pages and Posts

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#50869] opened 2021-03-08 23:16 UTC
**What**
The Pages and Posts options in Calypso don't offer bulk editing so once Nav Unification is implemented, it will be more difficult for users to access that feature.

**Why**
Sometimes users want to be able to bulk edit or delete their posts or pages.

**How**
We could add a "Bulk Edit" option after the "Add New" option that would link to the WP Admin Pages or Posts page: 

![screenshot](https://d.pr/i/Dcw5pI+)
Image URL: https://d.pr/i/Dcw5pI

**Comment by cpapazoglou** [comment] 2021-03-10 07:18
Thanks for reporting @ccwalburn! Indeed bulk editing is a much needed feature and we could port it to Calypso All Posts screen. Adding a new menu should be avoided though. On the meantime, advanced users can change their dashboard appearance through https://wordpress.com/me/account so that "All Posts" redirects to WP Admin

![](https://cln.sh/aM9o1v+)

**Comment by kriskarkoski** [comment] 2021-03-16 16:39
Since we won't be adding another menu I am closing this as a duplicate of https://github.com/Automattic/wp-calypso/issues/10742 to add bulk editing throughout Calypso which has some recent discussion.

**Closed as completed by kriskarkoski** 2021-03-16 16:39 UTC
Labels: [Pri] Normal, Feature Request, [Feature] Calypso & wp-admin Navigation, Triaged
