### ISSUE TITLE
Editor: Post-publish preview: Ugly permalinks for scheduled posts

### ISSUE THREAD

**Issue by mcsf** [Automattic/wp-calypso#17006] opened 2017-08-08 17:20 UTC
#### Steps to reproduce
1. Starting at URL: `/post/example.wordpress.com/`
1. Start a post by providing a title and some content
1. Click the link icon left of the title. Notice the slug that is automatically created.
1. Hit the calendar icon right of the Publish button, pick a date in the future
1. Hit Schedule
1. Wait for the post-publish preview to appear

#### What I expected
The URL presented in WebPreview's header should match the URL seen in aforementioned step 2.

#### What happened instead
The URL presented in WebPreview's header is a non-prettified link of format `…/?p=123`.

#### Further
- It is debatable whether post-publish preview should even be presented when a post is marked Scheduled rather than Published.
- As @lancewillett can further explain, WP Admin also provides `/?p=`-type URLs for scheduled posts, the reasoning likely being that the post's publish date and title may still change.
- That doesn't change the fact that it creates a dissonance for users, as described in § Context.
- ~This reveals a secondary issue: the URL on the link element shows the current date instead of the scheduled date. However, WordPress helpfully knows how to re-route these, i.e. `example.wordpress.com/2017/08/08/foo` → `example.wordpress.com/2017/08/10` once the post is automatically published on Aug 10th.~

#### Screenshot
![screen shot 2017-08-08 at 18 12 18](https://user-images.githubusercontent.com/150562/29084824-356e9722-7c65-11e7-97de-d87878090cb2.png)
![screen shot 2017-08-08 at 18 12 31](https://user-images.githubusercontent.com/150562/29084825-35715aa2-7c65-11e7-96a2-404ae92fe987.png)

#### Context / Source
Reported via a user that noticed the mismatch between the two URLs and wondered whether URL formats had changed on their website, or whether they had otherwise done something wrong, and wasn't sure which URL to use to share their posts (to schedule sharing on social media).

@mattsherman

**Comment by mattsherman** [comment] 2017-08-08 18:20
> It is debatable whether post-publish preview should even be presented when a post is marked Scheduled rather than Published.

I think it is valuable to show the post-publish preview when a post is scheduled. One of the reasons we show the post-publish preview is to allow the user to see their post as it will be shown to visitor to their site, to allow them to quickly confirm that things look as they intended. That scenario still holds true in the scheduled case -- that is likely the last time the user will see the post before it goes out to the world.

One thing we could consider, is to somehow denote that the post is scheduled. We show it in the notice, but perhaps something more permanent/visible in the preview header would help to make it more clear to the user that the post is scheduled.

> This reveals a secondary issue: the URL on the link element shows the current date instead of the scheduled date. However, WordPress helpfully knows how to re-route these, i.e. example.wordpress.com/2017/08/08/foo → example.wordpress.com/2017/08/10 once the post is automatically published on Aug 10th.

We should split this into a separate issue.

**Comment by mcsf** [comment] 2017-08-08 18:38
> > This reveals a secondary issue: the URL on the link element shows the current date instead of the scheduled date. However, WordPress helpfully knows how to re-route these, i.e. example.wordpress.com/2017/08/08/foo → example.wordpress.com/2017/08/10 once the post is automatically published on Aug 10th.
> 
> We should split this into a separate issue.

I was actually digging into this one, and I think it's a non issue. I had probably grabbed the URL _in between_ marking the post as future _and_ saving that change.

**Comment by mattsherman** [comment] 2017-10-06 00:20
This is an enhancement, not a bug. Behavior is consistent with wp-admin.

I agree that this can be confusing for users.

**Comment by mattsherman** [comment] 2017-10-06 00:26
@lancewillett Given the consistent behavior between Calypso and wp-admin in this regard, and the reasoning behind using the `/?p=` style URLs instead of nicer permalinks with date and title, I am inclined to close this.

There is a separate enhancement issue (#18067) to make scheduled previews more clear.

**Closed** 2017-10-06 18:28 UTC
Labels: Editor, [Type] Enhancement, [Type] Question
