### ISSUE TITLE
Publicize: Sometimes we cannot connect accounts to LinkedIn

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#32007] opened 2019-04-03 22:06 UTC
Let's investigate why some folks are reporting a connection issue during certain times of day. We may need to add more logging to the server endpoint to help track down the root cause.

See related:
p1554252168055200-slack-calypso
p1554328695072200-slack-calypso

**Comment by JoshuaGoode** [comment] 2019-04-03 22:31
Reported impact on my own self-hosted, simple, and AT sites:
p1554330212075700-slack-calypso

Never connected to these sites in the past.
Receiving `The LinkedIn connection could not be made because no account was selected` after authorization attempt.

**Comment by mdawaffe** [comment] 2019-04-03 22:54
We're being rate limited by LinkedIn:

```http
HTTP/1.1 429 Too Many Requests

{"serviceErrorCode":101,"message":"Resource level throttle limit for calls to this resource is reached.","status":429}
```

https://developer.linkedin.com/docs/rest-api#hero-par_longformtext_0

Looks like we get ~100,000 requests to /me per day (that number can apparently vary), and that's the endpoint we use to test that the connection is working :)

See D26459-code.

**Comment by gwwar** [comment] 2019-04-03 23:00
So speedy @mdawaffe ! 💖

**Comment by scosgro** [comment] 2019-04-04 21:36
Had another user have this happen to them. 

> The LinkedIn connection could not be made because no account was selected.

#11839424-hc

Told them I'd pass this along, but I don't have an ETA on a fix at the moment.

**Comment by jamiepalatnik** [comment] 2019-04-04 23:08
Reported again here: 11841178-hc

**Comment by scosgro** [comment] 2019-04-04 23:22
Reported again here: 10191128-hc

**Comment by jamiepalatnik** [comment] 2019-04-05 23:35
Reported in 6547317-hc

**Comment by gwensmithx** [comment] 2019-04-08 22:06
Reported here: 11748107-hc

**Comment by kcswong** [comment] 2019-04-08 22:39
Reported here: 2414248-hc

**Comment by jamiepalatnik** [comment] 2019-04-08 23:35
Another issue with LinkedIn connection, but the error is a little different: "There was a problem creating your connection. Please go back and try again." Guessing it may be related. 6604428-hc

**Comment by annbingle** [comment] 2019-04-10 03:10
Another user reported this. Error message is "There is an issue connecting to LinkedIn”.
HC: https://hud.happychat.io/chat/11972500
Ticket:  https://woothemes.zendesk.com/agent/tickets/1951088

**Comment by semihakocer** [comment] 2019-04-10 14:39
Another user reported this issue:
HC: 11968170
Ticket: 1928676

**Comment by jamiepalatnik** [comment] 2019-04-10 23:22
Reported in 6141899-hc.

**Comment by erricgunawan** [comment] 2019-04-12 07:34
Reported in 1955717-zd. 
Error message: `There was a problem creating your connection. Please go back and try again.`

**Comment by ccwalburn** [comment] 2019-04-12 22:24
Reported again here: 1957938-zd

**Comment by vparkhere** [comment] 2019-04-12 23:00
Happening here: 4688219-hc

**Comment by fashuvo** [comment] 2019-04-15 04:21
Reported again in 12091978-hc

**Comment by kristarella** [comment] 2019-04-15 23:42
> Reported here: 2414248-hc
> Ticket started here: 1948087-zd

I'm not sure if this is the same thing as the rate-limiting issue because there was still a broken connection listed in the Publicize RC

**Comment by formosattic** [comment] 2019-04-15 23:49
12113991-hc (and 1964347-zen)

<img width="1015" alt="Screen Shot 2019-04-16 at 07 27 08 1" src="https://user-images.githubusercontent.com/15944096/56171789-16887000-6019-11e9-9def-9b3b8a86df67.png">

**Comment by formosattic** [comment] 2019-04-15 23:54
9933982-hc, same symptom:

> LinkedIn connection could not be made because no account was selected

**Comment by jordesign** [comment] 2019-04-16 08:08
Reported again in 1964590-zd

**Comment by guicmazeredo** [comment] 2019-04-16 23:37
Another report in 1966820-zd.

**Comment by mishivee** [comment] 2019-04-17 00:14
Reported again at HC-12140658
1966939-zd

**Comment by eamcgill90** [comment] 2019-04-17 23:06
Reported here: 1969254-hc

**Comment by erricgunawan** [comment] 2019-04-26 03:04
7373023-hc

**Comment by eamcgill90** [comment] 2019-04-26 21:53
1989940-zd

**Comment by gwensmithx** [comment] 2019-04-27 16:43
> 1989940-zd

Just FYI I'm going to close this ticket since I'm uncertain how long this will take to resolve. I'm writing this down as a ticket we need to follow-up on though so we can update the customer once it's resolved.

**Comment by erricgunawan** [comment] 2019-04-28 23:24
Another report: 1994053-zen

**Comment by fernmed** [comment] 2019-06-06 19:10
User is having this issue as well. Not sure if it's to do with rate limiting as it is a bit after this timeframe, but it's the same issue mentioned above. 

2091411-zd

**Comment by jburciaga0** [comment] 2019-06-14 20:32
I responded to Fernando's above ticket explaining that we do not have a set timeframe for a fix on this issue but we are working on it slowly.

**Comment by ersatzpenguin** [comment] 2019-08-14 20:25
Not sure if this is related, but I have a user receiving the same error but in reference to Eventbrite. Details on this can be found in 2267212-zen.

If this is a separate problem, I can create a separate issue. But this seems too similar to not at least mention it here.

**Comment by guicmazeredo** [comment] 2019-10-11 15:11
Another user reported this issue: 13481965-hc

If I understood correctly, there isn't a short-term fix right?

**Comment by separatelyunited** [comment] 2019-10-25 23:30
Another report here: 15971446-hc

This user had an odd case where they were able to reconnect LinkedIn but it wasn't working. In Publicize it showed as broken. When they attempted to disconnect and reconnect they got the "No account was selected" error.

I tested my own account and got the same error.

![Image](https://cldup.com/tnf8kJ_ruH.png)

**Comment by samiff** [comment] 2019-10-28 21:28
2454128-zd

Currently unable to connect my own account, as well as another HE. Getting the same `The LinkedIn connection could not be made because no account was selected` message.

**Comment by chaitanyamsv** [comment] 2019-10-28 21:47
16198447-hc 

Error message: `The LinkedIn connection could not be made because no account was selected.`

**Comment by khristiansnyder** [comment] 2019-10-28 21:59
14112915 -hc 

`my LinkedIn account shows disconnected, but trying to reconnect fails.`

**Comment by allykmyta** [comment] 2019-10-28 22:02
16279134-hc
Followup: 2454196-zen

Error: `The LinkedIn connection could not be made because no account was selected.`

**Comment by mishivee** [comment] 2019-10-28 22:20
16280416-hc
Followup: 2454279-zen


I am also currently unable to connect my own account, as well as another HE. Getting the same The LinkedIn connection could not be made because no account was selected message.

**Comment by jordesign** [comment] 2019-10-28 22:43
Also reported in 2454129-zen.
Same Error: `The LinkedIn connection could not be made because no account was selected.`

This seems to have risen steeply in the last 12 hours after really being a problem - dp we have a direction on where to look? Is it likely to be a rate limiting thing again?

**Comment by mishivee** [comment] 2019-10-28 22:53
15587433-HC
2454331-zen
Same error as above

**Comment by kcswong** [comment] 2019-10-28 22:54
Reported in 16246292-hc. I tried to connect as well on a test site with own account, got same error message: `The LinkedIn connection could not be made because no account was selected.`

**Comment by tavilla61** [comment] 2019-10-29 21:14
Another report in 16307172-hc. They had been connected previously, but the connection broke and they're not able to reconnect.

**Comment by mbhthompson** [comment] 2019-10-29 22:59
Another report in 2456916-zen.

Error: `The LinkedIn connection could not be made because no account was selected.`

**Comment by jordesign** [comment] 2019-10-29 23:54
Hey @mdawaffe - I notice you'd been able to check if this error was being caused by us being rate-limited by LinkedIn last time it happened in April.

Could you please take a quick look again to see if it is a similar problem this time?

**Comment by joendotcom** [comment] 2019-10-30 12:19
Another report in 2456656-zen

Error: `There is an issue connecting to LinkedIn.`

**Comment by lakellie** [comment] 2019-10-30 14:48
Another report in 13619135-hc

**Comment by ktyfuller604** [comment] 2019-10-30 19:03
Another report - #16328686-hc

**Comment by pauloeaquino** [comment] 2019-10-30 19:23
Chat: 16329289-hc
Followup: 2459124-zen

**Comment by JoshuaGoode** [comment] 2019-10-30 19:48
> The LinkedIn connection could not be made because no account was selected.

16329079-hc

2459174-zen

**Comment by jenhooks** [comment] 2019-10-30 19:58
A Jetpack user is reporting this in 2439753-zen

`The LinkedIn connection could not be made because no account was selected`

**Comment by ntpixels** [comment] 2019-10-30 20:50
The user from [this earlier comment](https://github.com/Automattic/wp-calypso/issues/32007#issuecomment-547874538) has followed up to let us know the issue seems resolved for them.

2456656-zen

**Comment by smithkyle45** [comment] 2019-10-30 21:20
Chat: 16231374-hc
Follow Up: [2459328-zen](https://woothemes.zendesk.com/agent/tickets/2459328)

**Comment by ash1eygrace** [comment] 2019-10-30 22:05
Chat: 16331711
Follow-Up: https://woothemes.zendesk.com/agent/tickets/2459399

**Comment by chaitanyamsv** [comment] 2019-10-31 01:10
2454109-zen

**Comment by bikedorkjon** [comment] 2019-10-31 05:05
In 2459408-zen they are only seeing "There is an issue connecting to LinkedIn" in Calypso.

**Comment by juliasydnor** [comment] 2019-10-31 20:19
2461581-zen

**Comment by khristiansnyder** [comment] 2019-10-31 21:22
13432344-hc
User requesting follow up when fixed.

**Comment by macmanx2** [comment] 2019-10-31 22:17
Also reported at https://en.forums.wordpress.com/topic/linkedin-sharing-not-reconnecting/

**Comment by macmanx2** [comment] 2019-10-31 22:22
Also reported at https://en.forums.wordpress.com/topic/issues-with-connecting-to-linkedin/

**Comment by snowmads** [comment] 2019-10-31 22:26
2461810-zen
Promised a follow up when fixed

**Comment by eoinsav** [comment] 2019-10-31 22:36
16355649-hc

**Comment by brucea8c** [comment] 2019-11-01 10:56
Also in 2461923-zen

**Comment by macmanx2** [comment] 2019-11-01 21:34
Also reported at https://en.forums.wordpress.com/topic/cannot-refresh-my-blog-connection-to-linkedin/

**Comment by dkmyta** [comment] 2019-11-01 22:48
Reported in 2463918-zen

**Comment by macmanx2** [comment] 2019-11-02 00:01
Also reported at https://wordpress.org/support/topic/public-api-wordpress-com-returns-500-error-when-connecting-to-linkedin/

**Comment by jmcd73** [comment] 2019-11-02 00:29
When does the rate limit count reset? Presuming linkedin is domiciled in CA perhaps trying at 00:01 Pacific Time will get a successful connection?

**Comment by tmmbecker** [comment] 2019-11-04 12:17
@mdawaffe we've had a lot of these over the course of the last few days. Do you think this still due to rate-limiting?

**Comment by macmanx2** [comment] 2019-11-04 21:39
Also reported at https://wordpress.org/support/topic/publicize-will-not-connect-to-linkedin/

**Comment by JoshuaGoode** [comment] 2019-11-04 21:39
Reported on 3361226-hc

**Comment by mdrockwell** [comment] 2019-11-04 22:35
Another user unable to connect with LinkedIn here: 2469758-zen

**Comment by xpurichan** [comment] 2019-11-04 22:36
Another report in 2469997-zen. I disconnected the broken connection and asked them to try again tomorrow morning.

**Comment by tmmbecker** [comment] 2019-11-05 12:24
This is being managed in p7fD6U-2Za-p2

**Comment by eoinsav** [comment] 2019-11-06 23:21
Reported in 16488994-hc

**Comment by aicee** [comment] 2019-11-06 23:45
Reported in 2474947-zen

**Comment by chaselivingston** [comment] 2019-11-07 16:18
2475295-zen

**Comment by tanjoymor** [comment] 2019-11-07 23:02
3831477-hc

**Comment by csonnek** [comment] 2019-11-08 16:06
2477335-zen

**Comment by snowmads** [comment] 2019-11-18 22:05
2499074-zen

**Comment by ebinnion** [comment] 2019-11-19 18:02
I deployed a commit today that should greatly minimize our usage of the `/me` resource, which I believe will also fix or minimize the occurrence of this issue.

p7fD6U-2Za-p2

**Closed** 2019-11-25 23:10 UTC
Labels: Publicize, [Type] Task

**Comment by daria2303** [comment] 2020-12-16 17:22
The issue appeared again and persists for the third day now: 
HC: https://mc.a8c.com/support-stats/happychat/transcript.php?id=26219396
ZD: https://woothemes.zendesk.com/agent/tickets/3579800

**Comment by metabreakr** [comment] 2021-03-25 18:39
28641126-hc
