### ISSUE TITLE
Nav Unification: when returning to Posts view, non-calypso posts page is intermittently loaded

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49648] opened 2021-02-03 06:39 UTC
### Steps to reproduce the behavior

Prereq. there is a post published.

1. Go to View Posts.
2. Click on the post to open it in editor.
3. Once loaded, click on the WordPress icon on top left.
4. Click `View Posts`.
5. Repeat Steps 2-4. It may take possibly take 10+ tries.

#### What I expected to happen
Calypso is consistently loaded when user requests to return from editor to view posts.

#### What actually happened
Occasionally, the old `wp-admin` based page is loaded.

### Context
User scenario manual testing, back to basics.

#### Browser / OS version
Browser: Safari Version 14.0.2 (16610.3.7.1.9)
OS: macOS Big Sur 11.1 (20C69)

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Tested with Simple.

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor - user will be confused why their `Posts` view looks different.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

In this video, I was able to reproduce it in one go:
https://user-images.githubusercontent.com/6549265/106708269-6ac26280-65a7-11eb-941a-27f5019d68b9.mov

**Comment by obenland** [comment] 2021-02-04 22:22
Thanks for pointing this out!

I was personally unable to reproduce that, but since [we're filtering that value](https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx#L99-L105) and it defaults to wp-admin, I wouldn't be surprised if you managed to click it before the filter was able to kick in.

It's probably acceptable for folks to end up in wp-admin on the off chance this doesn't get replaced in time, particularly with nav-unification on the horizon?

**Comment by obenland** [comment] 2021-02-04 22:22
I'm going to close this for now, I'm not sure there's much there that could be improved or fixed, I'm afraid.

**Closed as completed by obenland** 2021-02-04 22:22 UTC
Labels: Bug, [Source] User testing, Back to Basics
