### ISSUE TITLE
Re-enable Gutenberg tips on WordPress.com and update the copy to be specific and relevant for new users.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#38299] opened 2019-12-09 20:49 UTC
Suggested, I believe, by @shaunandrews and/or @apeatling. We've disabled Gutenberg tips on WP.com. Can we re-enable them but with content related to our flow and onboarding experience?

**Comment by ianstewart** [comment] 2019-12-09 20:57
![image](https://user-images.githubusercontent.com/545779/70472036-09caf780-1a94-11ea-9577-f6842082a3ef.png)

![image](https://user-images.githubusercontent.com/545779/70472064-151e2300-1a94-11ea-84fe-34742a26dcda.png)

![image](https://user-images.githubusercontent.com/545779/70472089-21a27b80-1a94-11ea-9d49-5b10a4d5829b.png)

![image](https://user-images.githubusercontent.com/545779/70472124-2bc47a00-1a94-11ea-9657-2d651d5a81da.png)

**Comment by shaunandrews** [comment] 2019-12-09 21:06
The Tips can be some finicky, and don't _always_ point at the right place. But, I think they're still better than nothing.

There was some movement around adding an introduction Modal in Core: https://github.com/WordPress/gutenberg/pull/18041

However, even though that PR is marked as "merged" I've never seen it in reality. Could be a good solution to walking people through their first time experience with Gutenberg.

**Comment by ianstewart** [comment] 2019-12-09 21:07
I think we could probably just filter the first sentence in the first block?

"Welcome to our Page Editor!"

And correct the core bug in the final tip with some logic for Update vs Publish …

**What I saw:**

A tip that says, `Just click "Publish" and you're good to go.` That pointed to a button that says, "Update."

**What I expected:**

The tip would use the work "Update" when the button says "Update."

**Comment by ianstewart** [comment] 2019-12-09 21:15
> [The onboarding modal] could be a good solution to walking people through their first time experience with Gutenberg.

+1

**Comment by simison** [comment] 2019-12-10 14:52
>The Tips can be some finicky, and don't always point at the right place. But, I think they're still better than nothing.

Right to assume we'll rely on this mechanism in the future anyway? — so finding any issues and fixing them upstream would be great!

**Comment by ianstewart** [comment] 2019-12-10 15:44
If we used the tips we could potentially add a custom "final" tip (making the current "publish" tip the second last one) directing people to update their "starter content."

![image](https://user-images.githubusercontent.com/545779/70544407-a42d4880-1b31-11ea-9164-29c7a2339b31.png)

**Comment by ianstewart** [comment] 2019-12-10 15:47
And for non-FSE …

![image](https://user-images.githubusercontent.com/545779/70544512-cde66f80-1b31-11ea-8a55-13882a33979c.png)

… we could potentially make the last tip hang off the first heading or paragraph block on the page. Inviting people to update their content after getting to know the Editor.

**Comment by Copons** [comment] 2019-12-11 17:28
Apparently there are no tips anymore in Core Guten, they’ve been fully replaced by the [intro modal](https://github.com/WordPress/gutenberg/pull/18041).

The [`DotTip` component](https://github.com/WordPress/gutenberg/tree/f92fed76e073424f42aa89244264839ec98897b1/packages/nux/src/components/dot-tip) is still there, but nothing uses it anymore.

At a quick glance, it seems it's a big pain to implement as per design suggestions, since it's intended to be relatively positioned to the element that contains it.
Or, in other words, I have no idea how to nest it into a block component, for example.
It might also become deprecated at some point.

On the other hand, the new [`WelcomeGuide`](https://github.com/WordPress/gutenberg/blob/f92fed76e073424f42aa89244264839ec98897b1/packages/edit-post/src/components/welcome-guide/index.js) seems to be using all standard components (aka exported and ready to use).

As far as I can see, we have two clear paths:
1. We re-enable the Core NUX, and show the Core `WelcomeGuide`.
2. We keep disabling the Core `WelcomeGuide`, and instead provide our own, fully customized for our needs.

I understand it's not exactly the same experience as the `DotTip`, but it also gives us much more design flexibility.

**Comment by ianstewart** [comment] 2019-12-11 20:37
Is there any reason _not_ to turn on the core modal Welcome Guide as-is on WP.com?

**Comment by ianstewart** [comment] 2019-12-11 20:39
https://github.com/Automattic/wp-calypso/issues/32472

It looks like we turned off the core NUX features previously because it was showing up once _per site_ (or browser cache) and not _once per user_ as expected.

**Comment by gwwar** [comment] 2019-12-11 21:04
I'd recommend not using the core NUX tour directly and creating our own. (We can make our own redux store and re-use existing components, without worrying about integration points from a Gutenberg plugin update).

**Comment by lcollette** [comment] 2019-12-11 21:17
>I'd recommend not using the core NUX tour directly and creating our own.

+1 to @gwwar's suggestion and reasoning.

**Comment by Copons** [comment] 2019-12-11 21:35
IIRC the old Core NUX (aka the tips) also had some positioning issues caused by the fact that WPCOM forces Gutenberg in full screen.

Also, the new NUX uses the same check as the old tips (`select( 'core/nux' ).areTipsEnabled()`), so WPCOM's `disableTips` will automatically disable the new NUX as well.

Anyway, if y'all think the [new Core NUX](https://github.com/WordPress/gutenberg/pull/18041) is the way to go, I'll start working on the infrastructure ASAP.
We can work copy and images in at a later moment.

**Comment by apeatling** [comment] 2019-12-11 22:37
@Copons Can we turn on the core nux modal view above for now, but make no changes to it? Keep the tips disabled since that's where it sounds like the issues are.

Then we can look at how we might customize this with our own implementation, and also estimate the amount of work to do that.

**Comment by simison** [comment] 2019-12-12 12:19
>It looks like we turned off the core NUX features previously because it was showing up once per site (or browser cache) and not once per user as expected.

Yep, in core it's indeed cookie-based (visit from another browser and you'll see NUX again).

We'll need our own db-backed mechanism for sure and that's good moment to change it to show up per-user. Again maybe something to contribute to core the way or the other?

**Comment by zdenys** [comment] 2020-02-15 17:12
I noticed that some tips are cut off at the top. Here's an example of it on a site with plugins:

![](https://d.pr/i/j1qBbX+)
_Link: https://d.pr/i/j1qBbX_

**Comment by simison** [comment] 2020-02-17 08:55
@zdenys is that on Atomic or Simple site? If on Atomic, what's the Gutenberg plugin version?

**Comment by zdenys** [comment] 2020-02-18 13:21
@simison It was indeed an Atomic site with Gutenberg plugin 7.3 (hence not the most recent version). I don't

**Closed** 2020-02-18 16:21 UTC
Labels: Design Needed, [Pri] High, [Type] Enhancement
