### ISSUE TITLE
Investigate why purchasing may take a long time.

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#22424] opened 2018-02-14 00:21 UTC
Sometimes, it feels like a purchase can take a very long time ~30s to a minute. Let's investigate to see if there are any bottlenecks we can help clear up.

Timebox to a 1 day or so, okay to close out if nothing is obvious, but please add findings on what you investigated. Folks may also opt to help review D10737-code instead.

**Comment by gwwar** [comment] 2018-03-14 16:20
Related: D10737-code

We may want to help test this patch ^^

**Comment by michaeldcain** [comment] 2021-03-08 18:44
From the comments on the backend diff, it looks like the speed was related to our testing tables. If this can't be reproduced, I'm going to close it.

**Closed by michaeldcain** 2021-03-08 18:44 UTC
Labels: Purchases, [Type] Task
