### ISSUE TITLE
Widget block editor: Error thrown in various scenarios with Image or Tiled Gallery Blocks

### ISSUE THREAD

**Issue by kdevnel** [Automattic/wp-calypso#58835] opened 2021-12-04 06:46 UTC
### Quick summary

I am moving this issue from [this comment](https://github.com/Automattic/wp-calypso/issues/56922#issuecomment-984955683) as requested by @jeherve now that we have more details

Related to 4547072-zen

### Steps to reproduce

1. Activate Scratchpad theme.
2. Visit Customizer > Widgets
2. Add Tiled Gallery Block - see error immediately
3. Add image block
4. Try to Select Image, Upload, or Insert from URL - see error

### What you expected to happen

No errors should appear

### What actually happened

You receive an editor error for the Image block and also the Tiled Gallery Block.

Also, on this site, you cannot select the Pinterest block.

### Context

Copied from linked issue:

>Same thing happens with Image block, or Tiled Gallery block. "The editor has encountered an unexpected error." when viewed through Customizer -> Widgets.
Adding Tiled Gallery block throws error immediately.
Image block shows error when trying to Select Image, Upload, or Insert from URL.
Scratchpad theme.
Cannot delete Image or Tiled Gallery block.
Image block that was already there (already has image), try to select...throws error.
Pinterest block cannot be selected
Note: Appearance -> Widgets does NOT show ANY installed blocks.
>
> TEST SITE:
Atomic. 2017 theme.
Customizer -> Widgets, choose widget area.
Adding Tiled Gallery block throws error immediately.
Image block shows error when trying to Select Image, Upload, or Insert from URL.
Note: Can remove block by going directly to Appearance -> Widgets

### Simple, Atomic or both?

Atomic

**Comment by jartes** [comment] 2021-12-04 11:04
Probably related (or same issue) as #58742

**Comment by formosattic** [comment] 2022-01-11 08:59
On a Simple site with Twenty Fourteen theme, also ran into error 500 (same as in #58742) when visiting the widgets page. The page is just blank, but console shows error.

![image1](https://user-images.githubusercontent.com/15944096/148911434-8e110a7b-1a90-4c37-8184-e4645dd80f2f.png)

Widgets still load ok in Customize, so as workaround, can create widgets in a page draft, then paste the blocks via Customize.

Ticket: 4676616-zd-woothemes

**Comment by annbingle** [comment] 2022-01-12 01:03
Reported here as well 19326339-HC . This is a simple site.

**Comment by formosattic** [comment] 2022-01-25 07:19
I followed the steps from the initial report but am unable to reproduce the error. But I checked the case in https://github.com/Automattic/wp-calypso/issues/58835#issuecomment-1009730632 , and Widget block editor on the user's site is still loading blank.

So, it seems like the Widget block editor is crash inconsistently.

**Comment by Greatdane** [comment] 2022-02-02 05:29
I am unable to replicate on a Simple or Atomic site. It seems to be a very internment/rare bug, so closing for now. 

<img width="866" alt="Markup 2022-02-02 at 14 26 24" src="https://user-images.githubusercontent.com/5075840/152098181-2ba0eed5-9205-4628-a867-c246fef6eed4.png">

**Closed as completed by Greatdane** 2022-02-02 05:29 UTC
Labels: Bug, [Pri] High, Triaged, Block Widgets
