### ISSUE TITLE
Site Editor: Template navigator exits Site Editor rather than traversing menu

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#74128] opened 2023-03-06 18:29 UTC
### Quick summary

After entering the Site Editor, it looks like I can't navigate back, once I selected "Template", or "Template Parts" in the Design menu. It takes me out of the Site Editor entirely.

https://user-images.githubusercontent.com/1398304/223198487-bbadedf3-9f63-41b1-a2fd-1e1689e8be53.mov

### Steps to reproduce

1. Start at wordpress.com to load Calypso
2. Select a site with a block theme.
3. Select Appearance > Editor.
4. Click "Template".
5. Click the Back triangle.
6. Find yourself back in Calypso.

### What you expected to happen

To navigate back to the template or template part selection menu within the Site Editor.

### What actually happened

I was directed back to Calypso.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by ntsekouras** [comment] 2023-03-07 06:34
Could have this been resolved by this GB PR: https://github.com/WordPress/gutenberg/pull/48731. Can you test with GB from that PR because it's going to land in GB 15.4?

**Comment by dpasque** [comment] 2023-03-07 15:35
So, I did some triage/scrubbing, and this seems to be caused somehow by our Calypso-specific wrappers/integration:

On `wp-admin` on WPCOM sites (simple, and atomic),  and self-hosted sites, this does NOT reproduce. (They're all running GB 15.2.4.)

On WPCOM sites when you use the Calypso wrapper at `/site-editor/<site-name>`, it DOES reproduce. 

Even though this has workarounds (use the wp-admin site editor), I think this warrants leaving at High because it feels pretty rough!

**Comment by mattwiebe** [comment] 2023-03-13 17:52
This was fixed in #74178

**Closed as completed by mattwiebe** 2023-03-13 17:52 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] High, Triaged, Needs triage, [Feature] Full Site Editor, [Platform] Simple
