### ISSUE TITLE
Update flow linked to `Start with eCommerce` button in the landing page

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#34179] opened 2019-06-21 09:12 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Click the `Start with eCommerce` button:

<img width="1535" alt="Screenshot 2019-06-21 at 2 25 02 PM" src="https://user-images.githubusercontent.com/1269602/59911757-45183200-9432-11e9-8e4d-3de22ee2d4b0.png">

3. This takes to the `ecommerce` flow([#](https://github.com/Automattic/wp-calypso/blob/master/client/signup/config/flows-pure.js#L275)), showing an About step and all plan options.

#### What I expected

I expected it to take to the `ecommerce-onboarding` flow ([#](https://github.com/Automattic/wp-calypso/blob/master/client/signup/config/flows-pure.js#L282)) which shows the Site Type step and only the Business and eCommerce plans in the plans step. 

#### What happened instead

It takes to the `ecommerce` flow([#](https://github.com/Automattic/wp-calypso/blob/master/client/signup/config/flows-pure.js#L275)), showing an About step and all plan options.

**Comment by jancavan** [comment] 2019-07-09 16:52
> I expected it to take to the ecommerce-onboarding flow (#) which shows the Site Type step and only the Business and eCommerce plans in the plans step.

For some reason, I'm unable to repro. This is what's currently happening upon checking now.

> It takes to the ecommerce flow(#), showing an About step and all plan options.

Do you mean the plan lineup gets presented to you again even after you've selected "eCommerce" from the wpcom Home page? @niranjan-uma-shankar

**Comment by niranjan-uma-shankar** [comment] 2019-07-09 17:20
@jancavan Here's a screen recording of what I'm seeing: https://cloudup.com/c5USXDota_c.

**Comment by jancavan** [comment] 2019-07-09 18:11
Thanks for the screen recording @niranjan-uma-shankar ; that was really helpful.

It looks like there's currently a test that's ongoing called `improvedOnboarding`. You may be thrown in the `main` test hence you're seeing the "old" steps.

If you switch to `onboarding`, you should be seeing just these two plans:

![Screenshot 2019-07-09 11 10 11](https://user-images.githubusercontent.com/4924246/60912430-28556a00-a23a-11e9-9de5-54fd098bb12e.png)

**Comment by jancavan** [comment] 2019-07-09 18:17
Actually, I just learned that this test is technically already inactive so I'm confirming that what you're seeing is a bug.

**Comment by timmyc** [comment] 2020-03-10 21:02
I can not reproduce this today, after selecting the ecomm plan, I proceed to the checkout flow. Closing out.

**Closed by timmyc** 2020-03-10 21:02 UTC
Labels: Plans, Signup, [Type] Task, eCommerce Plan
