### ISSUE TITLE
Marketplace: Menu badges don't render correctly for atomic sites on wp.com

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#65621] opened 2022-07-15 03:23 UTC
After installing WooCommerce subscriptions the menu contains notifications badges in menu items that don't render correctly on WordPress.com.

Notice "Subscriptionsstaging" and "Home 6", the 6 is meant to be a notification badge pointing out there 6 signup notifications. The staging word is likely some other kind of badge. I believe Woo Payments also has something similar on install.

![Screenshot_2022-07-15_13-12-35](https://user-images.githubusercontent.com/811776/179143514-1444429e-e798-4d76-928e-d321d57402af.png)

- [ ] Can we render the label / badges correctly or hide them completely while on wp.com?
- [ ] "Home 6" (WooCommerce plugin)
- [ ] "Subscriptionstating" (WooCommerce Subscriptions plugin)
- [ ] "Payments 1" (WooCommerce Payments plugin)
- [ ] Possibly good to implement something that solves this for all woo plugins that do this.

This is how it renders on wp-admin:

![Screenshot 2022-07-15 at 13-36-27 Home ‹ WooCommerce ‹ c3po - Simple Site - Mapped — WooCommerce](https://user-images.githubusercontent.com/811776/179145273-a4f57cba-b1d4-4c51-bae8-3bd31468c336.png)

**Plan: Starter**

**Comment by cpapazoglou** [comment] 2022-07-15 06:24
@mmtr are there any discussions on how WooCommerce behaves on limited atomic?

**Comment by mmtr** [comment] 2022-07-15 08:23
I think this is a duplicate of https://github.com/Automattic/wp-calypso/issues/65479. Can we close this one?

> are there any discussions on how WooCommerce behaves on limited atomic?

None that I'm aware of. AFAIK it should behaves as always, just like in a normal Atomic site.

I think this is a Nav Unification issue though, since the menu renders correctly in WP Admin. There is probably some misbehavior in the `admin-menu` endpoint that parses these badges and serializes them to be consumed by Calypso.

**Comment by cpapazoglou** [comment] 2022-07-15 08:31
> I think this is a Nav Unification issue though, since the menu renders correctly in WP Admin. There is probably some misbehavior in the admin-menu endpoint that parses these badges and serializes them to be consumed by Calypso.

Ahh, yeah... Closing this in favor of https://github.com/Automattic/wp-calypso/issues/65479

**Closed as completed by cpapazoglou** 2022-07-15 08:31 UTC
