### ISSUE TITLE
Marketplace: Plugins Automatically Removed from Cart

### ISSUE THREAD

**Issue by kspilarski** [Automattic/wp-calypso#59950] opened 2022-01-11 15:12 UTC
### Quick summary

After exiting the checkout page, then waiting a while or clicking on the cart icon in the masterbar, the plugins previously added to cart are automatically removed. 

### Steps to reproduce

1. go to Plugins
2. select a plugin to purchase 
3. click Purchase and activate and you'll be taken to the checkout page
4. leave the checkout page, wait a while or manually click cart in the masterbar

### What you expected to happen

The plugins added in the cart will remain there unless manually removed. 

### What actually happened

The plugins got automatically removed from the cart. 

### Context

To start, I added a Business plan and three domains in my cart (total of 4 items): 

<img width="519" alt="Screen Shot 2022-01-11 at 3 01 36 PM" src="https://user-images.githubusercontent.com/36863633/148956792-bfd785e1-44ee-4695-a3a5-293d4d467fb9.png">

I exited the checkout page, went to Plugins and selected WooCommerce Subscriptions for purchase. 

<img width="1021" alt="Screen Shot 2022-01-11 at 3 02 44 PM" src="https://user-images.githubusercontent.com/36863633/148956931-4d6d9c33-83f3-4658-9e33-41531db7aee7.png">

I exited the checkout page again to add WooCommerce Bookings to the cart: 
<img width="1014" alt="Screen Shot 2022-01-11 at 3 14 05 PM" src="https://user-images.githubusercontent.com/36863633/148958820-f498c242-82ff-4142-9b26-1b39aede0cb9.png">

By now, I have 6 items in the cart. 

<img width="175" alt="Screen Shot 2022-01-11 at 3 14 44 PM" src="https://user-images.githubusercontent.com/36863633/148958936-01bcf785-19f5-4470-b2e8-3e639206b14e.png">
 
If I wait a bit, or click the cart icon, the plugins added are removed, and I am left with the items I added at the beginning (Business plan, 3 domains): 

<img width="519" alt="Screen Shot 2022-01-11 at 3 15 44 PM" src="https://user-images.githubusercontent.com/36863633/148959127-b60df39f-372b-4319-afc4-d221fcc39e89.png">

### Simple, Atomic or both?

Simple, Atomic

### Browser, operating system and other notes

Firefox 95
Mac OS 12.1

### Reproducibility

Consistent

### Severity

All

**Comment by sirbrillig** [comment] 2022-01-11 20:37
cc @cpapazoglou I imagine this might have to do with D72599-code and the discussion in https://github.com/Automattic/wp-calypso/pull/59732#issuecomment-1005607732 (although it seems that there's no notice displayed, which is odd)

**Comment by sirbrillig** [comment] 2022-01-11 22:46
It may be that when the cart item is added, the guard added in D72599-code works correctly, but then when the cart refreshes (eg: when clicking the cart icon), the `load` functionality of the cart endpoint does not correctly understand that the business plan is in the cart and removes the marketplace products. This would not show an error because way that the `load` functionality validates its products does not add user-visible error messages. I'm trying to verify all this (and possibly create a fix) but there's some issues with our test infrastructure that are making it difficult.

**Comment by sirbrillig** [comment] 2022-01-11 23:52
I created a test to reproduce this bug in D72869-code but I've disabled the test currently since it is failing (which is a good thing in this case). Next I'll see if I can come up with a way to make the test pass and hopefully resolve this bug.

**Comment by sirbrillig** [comment] 2022-01-12 06:52
This should be fixed by D72875-code

**Comment by arunsathiya** [comment] 2022-01-12 08:36
I reproduced the same issue when testing something else:

https://user-images.githubusercontent.com/18581859/149092340-c913cdb7-2a4b-45b2-913b-ef595ecd86a6.mov

**Comment by sirbrillig** [comment] 2022-01-12 16:43
Deployed the above diff. Hopefully this should be fixed now!

**Closed as completed by sirbrillig** 2022-01-12 16:43 UTC
Labels: Bug, Needs triage, Marketplace
