### ISSUE TITLE
Gutenberg: Loss of Post history and changes to post when switching editors

### ISSUE THREAD

**Issue by automattic-ian** [Automattic/wp-calypso#29934] opened 2019-01-07 15:02 UTC
Unable to reproduce however steps user took are as follows. 
#### Steps to reproduce
1. Starting at URL: Post in block editor (gutenburg) 
2. make changes to post 
3. Switch back to classic editor
4. changes lost on post and changes cannot be found in revision history. 

#### What I expected
Changing from block editor to classic should not lead to content loss. 

#### What happened instead
swapping editors led to content disappearing from post and revision history

#### Browser / OS version
User agent of user's browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15

#### Context / Source
appears to be related to https://github.com/Automattic/wp-calypso/issues/20265
Found via: #user-report in #3886689-hc
-->

**Comment by kristarella** [comment] 2019-01-08 06:38
It's a hard one to replicate, but I've heard a number of similar reports, would be good to see if certain blocks are the cause.

**Comment by gwwar** [comment] 2019-01-08 23:20
Probably better to safeguard here and verify if unsaved changes are firing, or make sure an autosave happens before navigation.

**Comment by gwwar** [comment] 2019-05-04 00:15
Looks like we didn't have any reports in the meantime. Closing out for now, but folks are welcome to reopen if there were new one.

**Closed by gwwar** 2019-05-04 00:15 UTC
Labels: Editor, Editor-Compatibility, Support, [Goal] Gutenberg, [Pri] Normal, [Type] Bug
