### ISSUE TITLE
Baskerville 2: Editor theme styles cannot be deactivated

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#69789] opened 2022-11-04 12:53 UTC
### Quick summary

On websites using the Baskerville 2 theme, turning off the option to use theme styles inside the editor doesn't stay disabled after the page/post editor is reloaded and needs to be turned off every time the editor loads.

I was able to replicate this on a simple site with a Personal plan, but I had to start it from scratch.
On my older test websites (2021 sites) this bug was not reproducible.

### Steps to reproduce

1. Start a new site (I needed to do this to replicate)
2. Activate the Baskerville 2 theme
3. Load a page or post in the editor and open the editor preferences 
4. Toggle the option "Use theme styles" off
5. Leave the page/post, and return to check the editor preferences again
6. Notice "Use theme styles" is still on

![baskervillebugeditorpreferences](https://user-images.githubusercontent.com/2540430/199979901-48602ef7-ca9f-4c28-abd1-291822599475.gif)

### What you expected to happen

The option to "Use theme styles" under editor preferences to stay turned off after reloading the editor.

### What actually happened

It was still on.

### Context

Reported by an HC, here:
pd4QKa-DY-p2

Related ticket
5681323-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Baskerville 2

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by cuemarie** [comment] 2022-11-10 23:44
📌 ACTIONS
- Closed as duplicate of #64324

📌 Message to Author
- This looks to me like a symptom of a more widespread issue with the editor preferences not saving across sessions. Closing in favor of that report.

**Closed as completed by cuemarie** 2022-11-10 23:44 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] Normal, Triaged, [Platform] Simple
