### ISSUE TITLE
Sharing: Reblog button not visible

### ISSUE THREAD

**Issue by molszewska** [Automattic/wp-calypso#22491] opened 2018-02-15 12:37 UTC
We've got a report that Reblog button is missing on multiple WordPress.com sites.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com > My Sites
2. Go to Sharing > Sharing Buttons
3. Check whether "Show reblog button" option is turned on
http://cld.wthms.co/VWvWfn
4. Double check wp-admin if the setting is reflected there as well:
http://cld.wthms.co/FC697k
4. Go to Site's URL and navigate to any post, to notice that Reblog button is nowhere to be found:
http://cld.wthms.co/I4hvi1

#### What I expected
Seeing reblog button under posts.

#### What happened instead
Reblog button is not found under the posts.

#### Browser / OS version
Tested in Chrome, FF, Safari both on my own test site and users' sites:
https://utopiayouarestandinginit.com
https://travel-gourmet.com

#### Follow-up
960459-zen

**Comment by kriskorn** [comment] 2018-02-15 12:42
Another one: 255466-hc

**Comment by rezzap** [comment] 2018-02-15 13:34
And another one: 419490-hc 

Site URL: https://dreambigdreamoften.co/

**Comment by rachelmcr** [comment] 2018-02-15 15:01
@gravityrail any chance this is related to the fix you made for https://github.com/wordpress-mobile/WordPress-iOS/issues/8615?

**Comment by wynwin** [comment] 2018-02-15 18:05
Another reported here: 960796-zen

**Comment by annacmc** [comment] 2018-02-16 00:01
Another report of this here: 1819299-hc
Site URL: https:/bozznet.wordpress.com

**Comment by adelineyaw** [comment] 2018-02-16 03:52
Another user in chat has reported this issue: 448488-hc
Follow up ticket: 961799-zen
URL: lindaghill.com

**Comment by angelica10000** [comment] 2018-02-16 11:49
Another user in chat has reported this issue: 1709747-hc
Follow up ticket: 962176-zen
URL: https://frankjtassone.com/

**Comment by rwaynick** [comment] 2018-02-19 13:08
Another report in 1845623-hc

**Comment by katinthehatsite** [comment] 2018-02-19 19:36
Another report in: 1846776-hc
URLs: 
fbreporter.wordpress.com
miodragnovakovic.wordpress.com
facebookreporter.org

**Comment by designsimply** [comment] 2018-02-20 17:32
Tested and confirmed that a reblog button does not show up on individual posts even though the My Sites > Sharing > Sharing Buttons > "Show reblog button" option is checked.

Here is how the Reblog button looks in the preview in my site settings:

![screen shot 2018-02-20 at tue feb 20 10 26 44 am](https://user-images.githubusercontent.com/1119271/36439046-e883544e-1628-11e8-8c60-aed38bcc386d.png)
<sup>Seen at https://wordpress.com/sharing/buttons/design5279.wordpress.com using Firefox 58.0.2 on macOS 10.13.3.</sup>

However, I cannot see the Reblog button on a post:

<sup>Seen at https://design5279.wordpress.com/2018/01/30/blockquote-%e2%9d%a4%ef%b8%8f/ using Firefox 58.0.2 on macOS 10.13.3.
![screen shot 2018-02-20 at tue feb 20 10 27 08 am](https://user-images.githubusercontent.com/1119271/36439157-3c404416-1629-11e8-9f1a-1f64e1b2ec98.png)
</sup>

**Comment by designsimply** [comment] 2018-02-20 17:34
Also reported at https://en.forums.wordpress.com/topic/reblog-button-has-disappeared-from-blogs?replies=31 /hat tip @KokkieH

**Comment by designsimply** [comment] 2018-02-20 17:34
Also reported in a live chat at 512467-hc /hat tip @ehti

**Comment by designsimply** [comment] 2018-02-20 17:34
Also reported in a Helpshift message at 261504-h /hat tip @SiobhyB

**Comment by designsimply** [comment] 2018-02-20 17:34
Also reported in a Helpshift message at 262204-h /hat tip @SiobhyB

**Comment by designsimply** [comment] 2018-02-20 17:34
Also reported in a live chat at  1823334-hc /hat tip @gilmoursa

**Comment by designsimply** [comment] 2018-02-20 17:35
Also reported in an email help request at 965971-zen /hat tip @rantoncuadrado

**Comment by designsimply** [comment] 2018-02-20 17:35
Also reported in a live chat at  1844984-hc /hat tip Zohair

**Comment by designsimply** [comment] 2018-02-20 17:35
Also reported in an email help request at 960232-zen /hat tip @otpidusprime

**Comment by designsimply** [comment] 2018-02-20 17:35
Also reported in an email help request at 961676-zen /hat tip @lizkarkoski

**Comment by designsimply** [comment] 2018-02-20 17:35
Also reported in an email help request at 960545-zen /hat tip @Lochlaer

**Comment by designsimply** [comment] 2018-02-20 17:35
Also reported in a live chat at  83949-hc /hat tip @krutidugade

**Comment by designsimply** [comment] 2018-02-20 17:36
Also reported in an email help request at 960933-zen /hat tip @donalirl

**Comment by designsimply** [comment] 2018-02-20 17:36
Also reported in an email help request at 955389-zen /hat tip @liviopv

**Comment by designsimply** [comment] 2018-02-20 17:37
Also reported in a live chat at  1822278-hc /hat tip @eduardozulian

**Comment by sarahblackstock** [comment] 2018-02-20 18:43
Reported in mobile support: #262611-h

**Comment by spncrb** [comment] 2018-02-20 20:59
Reported in HC 682202-hc

**Comment by sarahgreenlee** [comment] 2018-02-20 21:33
Reported in email help request at 966937-zen

**Comment by sdixon194** [comment] 2018-02-20 22:00
Reported in 967718-zen

**Comment by hacchism** [comment] 2018-02-20 22:38
Reported in 968873-zen

**Comment by jerrysarcastic** [comment] 2018-02-20 23:45
Reported in #966745-zen

**Comment by gravityrail** [comment] 2018-02-21 00:28
Yeah looks like it worked - for me. Can someone else clear their caches and spot check some sites?

**Comment by adelineyaw** [comment] 2018-02-21 01:11
I've just checked a users site at https://lindaghill.com/blog/ as I reported it here a few days ago and the 'reblog' button isn't there. They have enabled the 'reblog' option within Sharing > Sharing Buttons as well.

**Comment by gemmagarner** [comment] 2018-02-21 11:07
Reblog button missing in #966774-zen

**Comment by rachelmcr** [comment] 2018-02-21 15:46
@gravityrail I cleared caches and I'm not seeing the reblog button yet. I see in r170381-wpcom you updated this script source:
`https://s0.wp.com/_static/??/wp-content/js/postmessage.js,/wp-content/js/jed/jed.js,/wp-content/js/wpcom-proxy-request.js,/wp-content/js/likes-rest-nojquery.js?m=20180213`

But when I check my network requests, the sites are still requesting the old source: 
`https://s0.wp.com/_static/??/wp-content/js/postmessage.js,/wp-content/js/jed/jed.js,/wp-content/js/wpcom-proxy-request.js,/wp-content/js/likes-rest-nojquery.js?m=20180212`

**Comment by gravityrail** [comment] 2018-02-21 18:27
@rachelmcr and @gemmagarner and @adelineyaw - I deployed another change which forces clearing of caches at our end. Can you please take another look at let me know if it's fixed for you?

**Comment by adelineyaw** [comment] 2018-02-21 20:45
@gravityrail Awesome! Looks like it's fixed for lindaghill.com/blog - thank you (will let the user know)

**Comment by gemmagarner** [comment] 2018-02-22 10:28
Reblog button is back in 966774-zen — thank you!

**Comment by rachelmcr** [comment] 2018-02-22 16:34
I also confirmed the fix; closing this issue as resolved. Thank you for wading through this one, Dan! :)

**Closed by rachelmcr** 2018-02-22 16:34 UTC
Labels: Sharing, [Pri] High, [Type] Bug
