### ISSUE TITLE
Post by Email: Images not uploaded to Atomic

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#53846] opened 2021-06-19 13:18 UTC
### Summary

When using [post by email](https://wordpress.com/support/post-by-email/) we can publish a blog post with text and images. This feature appears to be working fine on simple sites currently, but on Atomic sites only the text is published - no images are uploaded and there is no evidence (such as code) where the missing images should have been added.

I also tested using the special `media+YOUR_SECRET_EMAIL@post.wordpress.com` email address to upload images directly to my Atomic site's Media library and found that the images were not loaded.

The user who reported this says the always use this feature and that the issue began about two days ago (which would be around June 17th). I did note the update to Gutenberg 10.8.1 on their site on June 16th, but I also found that they have Gutenberg deactivated on their site (and Gutenberg was activated on my test site), so this may be irrelevant. 

### Steps to reproduce the behavior

1. Choose an Atomic site and enable Post by Email: https://wordpress.com/support/post-by-email/#business-and-ecommerce-sites-with-plugins
2. Create a new email and include a title as well as both text and image(s) in the body of the email
3. After about a minute you can find the new post published to your Atomic site. Note that it includes your title and text, but no images.

#### What I expected to happen
Images added to post-by-email emails should be included in the published blog post.

#### What actually happened
Images are not added and the post is published as text only.

### Context
User report in 4079323-hc

#### Browser / OS version
n/a

#### Is this specific to the applied theme? Which one?
n/a

#### Does this happen on simple or atomic sites or both?
Atomic only

#### Is there any console output or error text?
n/a

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Normal - effects all Atomic sites using the Post by Email feature.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent

**Comment by zdenys** [comment] 2021-06-19 13:30
I thought it was some AT issue first, but now I think it's the case here too: 4078331-zd-woothemes

**Comment by xpurichan** [comment] 2021-06-19 13:32
I received an automatic email reply from my site about the media attachment failure from the test on my AT site. It reads:

```
Some attachments were rejected from the following WordPress.com Post by Email:

https://DOMAINCOM/?p=148

- IMG_3820.jpeg - Unknown token
- IMG_3821.jpeg - Unknown token
- IMG_3822.jpeg - Unknown token
```

**Comment by JoshuaGoode** [comment] 2021-06-19 13:47
This appears to be impacting self-hosted Jetpack sites as well.   We should probably move this to Jetpack's repo or create an associated issue there.

Overall, this is a Jetpack feature that isn't being worked on right now: p9F6qB-6e2-p2#comment-35482

The `Unknown token` issue seems newer.  Here are some previous internal reports.

- p9F6qB-6e2-p2
- p9F6qB-6Gj-p2

**Comment by Nic-Sevic** [comment] 2021-06-21 14:08
I went to open an issue in Jetpack but found a comparable one already open here: https://github.com/Automattic/jetpack/issues/20132#issue-925933569

Added a comment there to tie the two together

**Comment by jeherve** [comment] 2021-06-21 14:45
cc @miguelxpn; I believe this may have been caused by your changes in D63003-code, maybe what you pass to `Jetpack_Data::get_access_token` compared to what was passed before. 

Do you think you could take a look at this?

Thank you!

**Comment by miguelxpn** [comment] 2021-06-21 14:48
> Jetpack_Data::get_access_token

I'll take a look!

**Comment by miguelxpn** [comment] 2021-06-21 17:18
I just deployed a fix and from what I could tell on my test site it's working now! If there's still some issue please let me know!

**Comment by jeherve** [comment] 2021-06-21 17:23
Thank you!

Closing this issue now, but this can be reopened later if the problem remains on some sites.

---------

Internal reference: D63104-code

**Closed as completed by jeherve** 2021-06-21 17:23 UTC
Labels: Bug, Jetpack

**Comment by renata-franco** [comment] 2022-01-23 11:26
Another one here: 4668106-zd-woothemes
