### ISSUE TITLE
Editor/API: publishing post reflects creation date, not publish date

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#9014] opened 2016-10-28 22:08 UTC
One of our users published a post, and rather than the post reflecting a publish date of "today" (October 28), it showed a couple of days prior (October 26). He has since corrected the published date. I'm not sure whether the post was published with the "created" date or "last modified" date. I just know it did not correctly reflect today for the published date.

The site was a Jetpack site. The post was edited in Calypso. Multiple people edited the post. The post was published from the post-editor page. This was a savvy user. DM me on slack for details.

I have not yet been able to recreate this in Calypso for a dotcom or Jetpack site, nor have I been able to recreate in wp-admin for dotcom or Jetpack. And I cannot recreate the issue in the mobile apps. I _was_ able to recreate the effect by using the post-scheduler in the post-editor and selecting a date in the past. Then when I clicked "publish" it posted with the date in the past. But I don't believe that's what happened to the user in this case.

Edit: Not a jetpack issue, see comment below.

**Comment by lancewillett** [comment] 2016-11-02 16:38
Asked around a bit on this one:

Rachel McR:
> I have heard of that one (9014) happening before but have never been able to find steps to reproduce.

Kris K:
> Same as ^ and it seems like it’s been awhile since I’ve heard of it happening until this case

Scott S:
> I’m pretty sure I saw that happen once, but was never able to repro.  I’m pretty sure I created the post on mobile as a draft and published later from the web, but I’m not certain.

Rachel McR:
> Ooh, mobile + web … that could be. The apps do some different things with setting/managing post dates, I think, so it’s possible that they don’t play well with Calypso. We’ve also made changes in the apps with how post dates are handled, so if the draft was originally from before those changes it might be something that has been since resolved.

**Comment by aduth** [comment] 2017-01-02 18:59
Was the post scheduled @rralian ? If possible, would be good to get concrete steps to reproduce.

Might this issue be related to your inability to fix the date? #10297

**Comment by rralian** [comment] 2017-01-02 21:11
I don't believe I had scheduled it, but come to think of it I think it was behaving as if I had. I clicked the date and rather than saying "update" I believe the action button said "schedule". I shoulda left it in its incorrect state, but I didn't want to leave my blog messed up. :-)

**Comment by akirk** [comment] 2017-01-19 13:28
I have just experienced this in Calypso posting to a P2. The post had its date set to the time when I created the first draft. This can also be seen in the revision list of the post.

**Comment by retrofox** [comment] 2017-01-19 13:31
Added to https://github.com/Automattic/wp-calypso/projects/19

**Comment by retrofox** [comment] 2017-01-19 13:31
Thanks @akirk

**Comment by lizthefair** [comment] 2017-02-15 15:51
The owner of this site, https://trailtopeaktheadventurouspath.com/ expirences this problem everytime she posts.  Here is what she says about her process:

> I am working on a MacBook Pro Retina (mid 2012) on Mac OS Sierra version 10.12.3 (but it was happening with earlier versions of the software). Usually I work directly in Chrome. Sometimes Safari. And sometimes (though rarely) the Wordpress desktop app. I always start with a draft, sometimes changing the title of the post as I write (so my titles sometimes don't match the url). I always come back to the post and edit it before posting, using the spell checker. I always come back and edit it multiple times as my hubby likes the sneak peak (and catches some of my typos). When I do that editing, I might edit, entering from my phone (an iphone7), or working in chrome, safari or the wordpress app... and not always the platform on which the post was started. 

She also says one of her fellow bloggers https://daveplyadventures.wordpress.com/ never has the problem.

**Comment by rwaynick** [comment] 2017-02-17 12:42
Related issue on, https://brotkasten.blog

> In one case it may be dated back one day, in other cases, as with my latest blogpost, it’s dated back 14 days. My latest blog post I published last Friday, the 10th February 2017, but WordPress dates it back to 27th January 2017 – and I started writing the article long before this date so that’s no the reason for that.

> I started writing it on January the 13th and I always saved it as a Draft until I finished it and then published it on Feb 10th.

Post the user is referring to, https://brotkasten.blog/2017/01/27/die-leiden-des-jungen-amiga/

The user only writes in Calypso.

**Comment by jblz** [comment] 2017-03-13 19:29
I just experienced this when posting to a p2.

I _did_ set a scheduled publish time, but then hit the `Publish` button resulting in the post being published immediately with a creation date ( & URL slug :( ) of the date the post draft was originally created.

For some reason, the button never changed to `Schedule`. I wonder if the post draft being > 1 day old is contributory.

**Comment by akirk** [comment] 2017-03-13 19:44
In wp-admin the post date of a new post is not a time but "Immediately":
<img width="289" alt="screen shot 2017-03-13 at 20 42 28" src="https://cloud.githubusercontent.com/assets/203408/23872231/c1f2c94a-082d-11e7-9c44-14bcb8c23eaf.png">

In Calypso it's the time when the first draft was saved:

<img width="272" alt="screen shot 2017-03-13 at 20 44 03" src="https://cloud.githubusercontent.com/assets/203408/23872250/d92476b8-082d-11e7-8911-f1c32af50c0b.png">

Hence, when you return to your post later on and publish it, it will be published with a date in the past.

**Comment by designsimply** [comment] 2017-04-14 00:28
I tried testing this but was unable to reproduce the problem using the following testing steps:

1. Create several drafts.
1. Wait a few days.
1. Open a draft, make a change, click publish.
1. Open a draft, click Publish immediately.
1. Go to Posts > Drafts and click Publish on one of the drafts in the post list.
1. Open a really old draft (i.e. 8 months), click Publish.
1. Open a draft, click on Status, click on the date, click Publish.

<strong>Result:</strong> publishing a post always resulted in the date updating to the publish date as expected, none of the posts in my testing used the creation date instead of the publish date.

<strong>Video:</strong> [3m27s](https://cloudup.com/cupVNYQcwhP)

Because I was unable to reproduce the problem in testing and because the issue is several months old, I have removed the `[Pri] High` label but would still like to check in to see if the problem is still happening. Maybe I am missing something in my testing steps?

@rralian just to check, do you recall seeing the problem happen recently by chance?

**Comment by ashercantrell** [comment] 2017-07-05 04:15
User saw something similar in #3274366-t. According to them, they made a draft, didn't finish it right away, and published it 5 days later, and when they did so, it showed as being posted 5 days ago.

User's steps:
> I just created a draft and then 5 days later I updated and posted it.

**Comment by hewsut** [comment] 2017-08-06 18:20
My wife encountered this today. I'm not up on the inner workings of our Reader in surfacing content, but it feels like this is a fairly painful bug if the backdate posting behavior means fewer potential readers are less likely to see content surface in their tags.

She says:
1. She started the post originally on her phone.
2. She switched back and forth revising the draft on phone and computer over the next 24 hours.
3. She published in Calypso from her computer.

She never intentionally adjusted any date settings -- just hit "Publish".

**Comment by hewsut** [comment] 2017-08-06 18:31
What's more -- I've looked back through her last ten posts by comparing the slugs vs the timestamp in emails I've received from her blog. She's had this happen on four of the ten.

**Comment by rwaynick** [comment] 2017-08-15 18:07
User in 619909-zen reported similar behavior,

> My site timezone is at UTC-8
> 
> Most of my post has been going up on time, if I schedule it ahead of time.
> 
> But I noticed, when I write a draft, for example, on a Monday. Work on the draft a few days later and publish it later it the week, that post will instead show up on the day (Monday) it was first drafted.

**Comment by lancewillett** [comment] 2017-09-04 21:31
This *should* be solved with the API changes described in https://github.com/Automattic/wp-calypso/issues/4330 

r160864-wpcom (Jetpack sites will need a future update for the updates to the endpoint).

@iandunn Just a quick check with you on:

a) Do you agree your changes will fix this reported issue also?
b) Is there a related Jetpack change we can link to?

**Comment by iandunn** [comment] 2017-09-05 23:06
> a) Do you agree your changes will fix this reported issue also?

I think `r160864-wpcom` should have fixed [Jeff's issue](https://github.com/Automattic/wp-calypso/issues/9014#issuecomment-286217350), but it doesn't seem like it'd affect the others.

It only applies to situations where the post was scheduled to be published automatically at a date in the future, and then the user published it manually before that date. If I'm reading the previous comments correctly, though, it doesn't seem like all of the reports involved scheduled posts.

I've tried to reproduce the bug in many ways and haven't been able to, but given all the previous attempts, that doesn't give me any confidence that it's fixed.

I looked through the API endpoint and Calypso to see if I could find anything that'd suggest a potential cause, but came up empty.

> b) Is there a related Jetpack change we can link to?

No, the changes in `r160864-wpcom` haven't been synced to Jetpack yet.

**Comment by lancewillett** [comment] 2017-09-28 16:27
Hi @iandunn Could update this thread with any recent updates or changes? What's left close it?

**Comment by iandunn** [comment] 2017-10-02 16:09
I've been focusing on wrapping up a few other PRs, and haven't dug any deeper on this. It does seem like the reports have dropped off, so maybe I was wrong about `r160864-wpcom` not fixing it.

I'll go ahead and re-close it for now, and we can always re-open it if we start getting reports again.

**Comment by SiobhyB** [comment] 2017-11-03 12:12
Reopening as I there was another report in 769786-zen. I left specific details in the notes of that ticket and am asking the blogger for more information about their browser.

**Comment by benchilcote** [comment] 2017-11-03 17:44
User replied that they started the post on their iPad.  They later worked on it through their computer.  They mentioned that they use Safari on both.

**Comment by MindyPostoff** [comment] 2017-11-13 22:22
Another user report here: 789831-zen. Looks like the Calypso published time under the Post status section is 3 hours later than what's stored everywhere else:

Post Status (8:24pm):
![](http://cld.wthms.co/sztRK+)
_Screenshot Link:_ http://cld.wthms.co/sztRK

Calypso post listing (5:24pm):
![](http://cld.wthms.co/57up60+)
_Screenshot Link:_ http://cld.wthms.co/57up60

WP-Admin post editor (5:24pm):
![](http://cld.wthms.co/VvgeRI+)
_Screenshot Link:_ http://cld.wthms.co/VvgeRI

**Comment by MindyPostoff** [comment] 2017-11-16 13:41
I'm leaving another comment, with reference to what I reported [above](https://github.com/Automattic/wp-calypso/issues/9014#issuecomment-344079085). 

With ticket 789831-zen I have done more digging. I discovered that Calypso displays the published time in one's local time, so that's why I saw the difference. WP-Admin displays it in the user site's time zone. So, my comment above is not a problem. However, with that understood, I kept trying to figure out the main problem that the user came to us with:

**The Stats > Insights calendar is displaying posts published at 00:00 on the previous calendar date.**

When the user first reported the issue, I noticed that there were a number of posts published at 00:00. One of them was published on Oct. 25, but in the calendar, it was displayed as being published on Oct. 24:

![](http://cld.wthms.co/OduDld+)
_Screenshot Link:_ http://cld.wthms.co/OduDld

Since 00:00 is an edge case, I tried changing the published time to 03:00. If done in WP-Admin, the Insights calendar reflects the correct published date immediately. If changed through Calypso, there might be some caching, as it's not reflected in the calendar right away (however, the user and I believe the correction in the calendar eventually displays).

Has anything changed in Calypso recently (the user claims the change in the calendar happened recently), that would impact time calculations? 00:00 as a published time on a given calendar date should maintain that same date in the Insights calendar.

@iandunn - I see you were working on this issue before. Any thoughts about this?

**Comment by erricgunawan** [comment] 2017-11-19 14:51
Adding @MindyPostoff  comment for the same ticket: 789831-zen.

I tried editing the published date of one of my post on my test site. Similar to what Mindy has said:

> If done in WP-Admin, the Insights calendar reflects the correct published date immediately. If changed through Calypso, there might be some caching, as it's not reflected in the calendar right away 

Changing in the WP-Admin will be reflected immediately. However, if editing from Calypso, I have to clicked some other pages first before going back to Insight page and found the change reflected.

That said, editing an old post by giving it 00:00 as a published time for **different dates** always works for me. The post has June 30th as the original published date. I moved backward to June 29th, and moved it forward to July 1st and 2nd, they're always reflected on the Insight correctly (with a caching note if edited from Calypso).

However, from the other comments above, I found several other cases that include creating a draft in one day, then published it on another day that might trigger the issue.

Also, using Scheduled post is another case where this issue cropped up.

Since the user in the original ticket has made use of the scheduled post (to always post on Wednesdays), I'll give this a try.

I have now made a Scheduled post for tomorrow at 00:00 and see if this issue will hit me. 

Will get back tomorrow with the result.

**Comment by erricgunawan** [comment] 2017-11-24 10:02
I just realized what @MindyPostoff said earlier in her comment:

> I discovered that Calypso displays the published time in one's local time, so that's why I saw the difference. WP-Admin displays it in the user site's time zone.

And I can confirm I have the same experience as [here](https://github.com/Automattic/wp-calypso/issues/9014#issuecomment-344079085).

While this might not be an issue, the difference in time displayed between **Calypso Post Listing** and **Calypso Post Editor** can be somewhat confusing, **if** a user is editing a post where their local timezone is **not the same** with the site's timezone.

A case that might happen is as follow:
1. Site's Timezone set to UTC+0.
2. User's Timezone is UTC+3.
3. User scheduled a Post to be published on 2017-11-25 00:00 AM set **from Calypso**. Note that this happened on UTC+3 following the user's timezone.
4. What would happen then was the post published date would be stored as **2017-11-24 10:00 PM** and the Insight stat will also display the post published on 2017-11-24. This to follow the Site Timezone in UTC+0.

Of course, this scenario won't happen if User's Timezone is the same as Site's Timezone. (This might need to be confirmed with the user).

However, 

if *WP-Admin Post Listing* displays the same published datetime with the *WP-Admin Post Editor*, 

then *Calypso Post Editor* should also display the same published datetime with its *(Calypso) Post Listing*.

This to avoid any confusion or the sample case mentioned above, that is **if** the User's Timezone is different with Site Timezone.

**Comment by JesseStu** [comment] 2017-11-29 21:58
@erricgunawan Letting you know that the user answered your question [from this ticket](https://woothemes.zendesk.com/agent/tickets/789831) that you noted, asking <em>if he's ever edited a post using a device that has a different timezone with his Site Timezone</em>.

> As far as I know, me, my devices, and my blog are all in the same time zone.

**Comment by rachelmcr** [comment] 2018-08-30 09:14
This does look like a bug with how Calypso and the WP apps set the post's publish date. I can't reproduce it working entirely within Calypso, but I can when I publish a post in Calypso after working on it in the apps.

I can consistently reproduce the backdating issue in the following scenarios:

- Create a post in Calypso, edit it in the WPiOS app, and then edit and publish it in Calypso. Result: The post is published with the creation date.
- Create a post in WPiOS, and then edit and publish it in Calypso. Result: The post is published with the creation date.
- Create a post in WPAndroid, and then edit and publish it in Calypso. Result: The post is published with the creation date.

And a slight variation when created in Calypso and edited in the WPAndroid app:

- Create a post in Calypso, edit it in the WPAndroid app, and publish it in Calypso. Result: The post is published with the date it was last edited in WPAndroid.

In each case, when I open the post in the Calypso editor after working on it in the apps, I see that it is backdated. This happens even though the post settings in the app are set to publish the post immediately.

cc @Automattic/hogwarts

**Comment by chrisfromthelc** [comment] 2018-09-18 02:31
I had a user who also is experiencing the draft/publish date mismatch. It appears they were also using the app.

**Comment by tijosh** [comment] 2019-09-25 14:08
We had another report of this in #2376256-zen

**Comment by KristinaKay** [comment] 2019-11-21 04:17
Did not mean to post here. Sorry.

**Comment by nerdysandy** [comment] 2021-02-10 21:14
Closing it as duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/10188 or as something which is being tracked on that link.

**Closed by nerdysandy** 2021-02-10 21:14 UTC
Labels: API, Editor, Jetpack, [Type] Bug
