### ISSUE TITLE
Onboarding: launchpad shows design selected when I never selected a design. 

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#94087] opened 2024-08-30 21:30 UTC
#### Steps to reproduce

1. Go to WordPress.com
2. Click getting started and go through flow until you reach three actions to take that include drafting a post, watching blogging videos, and picking a design. Choose the option to draft a post.  
3. After publishing the post or drafting and previewing it, notice that when you are brought to the launchpad the option to select a design is checked off even though you never picked a design or had a choice. 

#### What I expected

To be nudged to select a design I wanted and guided in that process. 

#### What happened instead

I was presented with a theme I never chose, never presented with other themes, and the option was checked off for me. 

#### Browser / OS version

MacOS, Chrome 

#### Screenshot / Video

I took this video for another bug but it demonstrates the problem still:

https://github.com/user-attachments/assets/522a31a8-a531-442a-89e2-7b1c872c8043

**Comment by dsas** [comment] 2024-09-04 06:12
Duplicate of https://github.com/Automattic/wp-calypso/issues/93901

**Closed as not planned by dsas** 2024-09-04 06:12 UTC
Labels: Bug, [Feature] Site Goals & Onboarding Paths, [Pri] TBD
