### ISSUE TITLE
Posts: Controls overlap in header on small landscape viewports for multi-author sites

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#16921] opened 2017-08-04 17:45 UTC
#### Steps to reproduce
1. View `/posts` for a multi-author site with a small viewport, such as landscape mode on an iPhone 6s

#### What I expected

The layout to adapt to my viewport, showing me things without controls being overlapped.

#### What happened instead

Controls are overlapped.

#### Browser / OS version

iPhone 6s

#### Screenshot / Video

![img_5986](https://user-images.githubusercontent.com/2098816/28980069-71c1c65c-791a-11e7-8949-22e7b341b11f.png)

#### Context / Source

Found while testing other issues.

**Comment by alisterscott** [comment] 2017-12-21 00:56
No longer occurring, the posts become a drop-down:

<img width="477" alt="screen shot 2017-12-21 at 10 55 20 am" src="https://user-images.githubusercontent.com/128826/34235448-818f442a-e63d-11e7-8da5-4446b5aa2920.png">

**Comment by FlyteWizard** [comment] 2017-12-21 19:46
This is def. still a problem and should be re-opened. 

![capture d ecran 2017-12-21 a 11 43 39](https://user-images.githubusercontent.com/10472448/34272222-6c6d945a-e644-11e7-83c3-8fb5c79f3e8e.png)

**Comment by millerf** [comment] 2018-03-05 14:26
What would be the best approach for this?

- pushing the 'author' selection on another line would lose a lot of space
- what about having the 'author' selection be a dropdown as well for this type of screen width?

**Comment by mattsherman** [comment] 2018-03-06 02:07
We actually already have a working approach for this... the breakpoints that trigger it just need to be tweaked it seems:

<img width="478" alt="screencapture at mon mar 5 21 05 10 est 2018" src="https://user-images.githubusercontent.com/2098816/37010352-25c5cb62-20b9-11e8-9d22-9d076bc7028c.png">

**Comment by millerf** [comment] 2018-03-06 10:54
@mattsherman the problem is happening between   661px and about 710px.

And breakpoints are:
480px, 660px, 960px, 1040px, 1280px, 1600px

So it cannot triggered by the actual breakpoints, and I don't think added one breakpoint would be the solution :)

I also realized there is a "is_dropdown" class added to the "published" selector at around 770px:
https://github.com/millerf/wp-calypso/blob/a85848cd070c46a04e275695a916fc625acbc56a/client/components/section-nav/tabs.jsx#L77-L86

I keep on investigating...

**Comment by mattsherman** [comment] 2018-10-30 00:15
@naquiuddin If you create a PR and mention me on it I can review it.

**Comment by millerf** [comment] 2020-02-09 20:48
@mattsherman Has this been fixed in the end?

**Comment by millerf** [comment] 2020-02-09 20:51
Nope...

![Screenshot 2020-02-09 at 21 51 02](https://user-images.githubusercontent.com/790558/74109739-4bf0e200-4b86-11ea-9856-c9f38fb6e561.png)

**Comment by millerf** [comment] 2020-02-09 21:40
Fixed on

**Comment by lancewillett** [comment] 2020-03-13 06:52
Confirmed the suggested changes in #39332 work well. I'm going to start a new pull request, though.

**Closed** 2020-03-13 16:43 UTC
Labels: Posts, [Type] Bug, good first issue
