### ISSUE TITLE
FSE: Cannot add a new template

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#62054] opened 2022-03-18 10:58 UTC
### Quick summary

We can't add a new template when we try so

### Steps to reproduce

Access the Site editor 
Click on Templates
Click on Add new template

### What you expected to happen

To see the option to add a new template

### What actually happened

The option is hidden underneath the main templates list.

### Context

https://user-images.githubusercontent.com/6737345/158991044-c01947c1-5149-4456-ab53-d49a4451dfbf.mp4

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No and the platform is unusable

**Comment by Addison-Stavlo** [comment] 2022-03-18 11:27
After quickly testing this seems related to Gutenberg 12.8.0 Upgrade.

On dotcom, running G 12.7 we can click this button and access the dropdown selection:

![Screen Shot 2022-03-18 at 7 24 01 AM](https://user-images.githubusercontent.com/28742426/158995052-7fb67a61-b0f4-47db-a386-f01cb8ea0c2f.png)

However, with 12.8 this dropdown now seems to be hidden behind the template list section itself:

![Screen Shot 2022-03-18 at 7 25 14 AM](https://user-images.githubusercontent.com/28742426/158995129-d22d31e4-4302-4aea-ad0e-23c3afb2a849.png)

**Comment by Addison-Stavlo** [comment] 2022-03-18 11:46
Digging Further, it looks like this was a temporary regression in Gutenberg itself that is resolved on `trunk` branch:
* Running local Gutenberg on branch `v12.8.0` reproduces the problem.
* Running local Gutenberg on `trunk` the problem seems resolved.

Odd side note... when I run the `v12.8.0` branch, the Gutenberg version in plugins is listed as `12.8.1` 😕  then when I run trunk its listed as `12.8.0`. 😵  Were noticing the problem with 12.8.0 on dotcom, so we would need to ensure this fix is picked into any point release like 12.8.1.

**Comment by pauljacobson** [comment] 2022-03-18 11:52
I also reported this issue here: #62052

**Comment by Addison-Stavlo** [comment] 2022-03-18 11:55
Also found this reported in Gutenberg repo - https://github.com/WordPress/gutenberg/issues/39548

**Comment by Sandkorner** [comment] 2022-03-18 14:04
Have the same issue just testing it on my own site. 
<img width="1884" alt="Screenshot 2022-03-18 at 15 14 43" src="https://user-images.githubusercontent.com/71094068/159017406-57978f85-451c-4706-bccf-8522779a8466.png">

**Comment by Addison-Stavlo** [comment] 2022-03-18 17:43
This fix is now live on simple sites with the release of Gutenberg v12.8.1 and should be live on AT as well shortly.

Closing the issue, but feel free to open if this resurfaces or isn't resolved with 12.8.1.

**Closed as completed by Addison-Stavlo** 2022-03-18 17:43 UTC
Labels: Bug, [Pri] High, [Feature] Full Site Editor
