### ISSUE TITLE
Buttons Block: Theme's style is overridden on the front of the site

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#67428] opened 2022-09-06 12:14 UTC
### Quick summary

In WP.com, the theme style for buttons is overridden when viewed at the front of the site. Therefore, the button looks strange in front of the site, and the button looks as expected in the editor.

It seems to be a WP.com issue since I can't replicate the issue in my local setting WP v.6.0.2 + Gutenberg trunk.

### Steps to reproduce

1. Make sure that a block theme is activated on your site. e.g. Remote, Cultivate, etc.
2. Add a button to a page or post.
3. Compare the button appearance between the editor and the front of the site.

### What you expected to happen

They should appear the same.

### What actually happened

The button's background colour is #32373D, and the size is also wrong if the theme changes the button text size.

### Browser

Google Chrome/Chromium

### Context

I realised while testing something else.

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

| Editor (as expected) | Front of the site (broken) |
| ----------- | ----------- |
| Remote ![Screenshot 2022-09-06 at 13 01 39](https://user-images.githubusercontent.com/908665/188630123-643a071e-532e-4fd7-8945-d61182fe76c9.jpg) | ![iamtakashi wordpress com_2022_09_01_button-test_ (2)](https://user-images.githubusercontent.com/908665/188630068-7c028387-5154-4ae2-aa6a-e6fca0037196.png) 
| Cultivate ![Screenshot 2022-09-06 at 13 04 14](https://user-images.githubusercontent.com/908665/188630557-db3aae06-c48b-4543-a78e-48a925a6bd6b.jpg) | ![iamtakashi wordpress com_2022_09_01_button-test_](https://user-images.githubusercontent.com/908665/188630594-3326976d-98f1-4fcf-9ae2-32056f0642e7.png)
| Yuga ![Screenshot 2022-09-06 at 13 07 39](https://user-images.githubusercontent.com/908665/188631379-81510b22-1e02-471f-b672-906020a7ea2f.jpg) | ![iamtakashi wordpress com_2022_09_01_button-test_ (3)](https://user-images.githubusercontent.com/908665/188631491-ce273ed2-bbf7-4886-b560-981fb9060a9b.png)

### Reproducibility

Consistent

### Severity

All

### Workaround details

Not sure why, but I can't replicate the problem with a block theme, Disco.

**Comment by fullofcaffeine** [comment] 2022-09-13 00:06
It looks like this is the cause: https://github.com/WordPress/gutenberg/pull/43022. This seems restricted to WPCOM simple sites. I couldn't reproduce it on an AT site. More context: p1663027553766049/1662734279.580389-slack-C01DF571R5Y.

**Comment by cuemarie** [comment] 2023-05-03 19:06
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested with Remote theme on Simple site:

#### Screenshots/Recordings

**Editor**
![Markup on 2023-05-03 at 12:05:56](https://user-images.githubusercontent.com/27249804/236018626-79d8a7de-69ee-442d-a484-94a15ca1d46e.png)

**Live Site**
![Markup on 2023-05-03 at 12:06:04](https://user-images.githubusercontent.com/27249804/236018667-56c80fe6-0e32-4214-ac9d-d0ab58d64b36.png)


📌 ACTIONS
- Closed as no longer relevant

**Closed as completed by cuemarie** 2023-05-03 19:06 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Simple
