### ISSUE TITLE
Extra metabox has randomly appeared

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#32836] opened 2019-05-06 18:30 UTC
I'm seeing a meta box at the bottom of the editor:

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/191598/57246394-22a99100-700b-11e9-9778-744177bfeaec.png">

I'm fairly certain this wasn't there a few days ago, and I'm seeing this on multiple sites. If it helps, the screenshot above is from my test: https://wordpress.com/block-editor/post/conceptualwig.com

**Comment by kwight** [comment] 2019-05-07 23:29
@shaunandrews Are you still seeing this? I can't replicate myself.

**Comment by shaunandrews** [comment] 2019-05-08 15:36
<img width="948" alt="image" src="https://user-images.githubusercontent.com/191598/57388087-82c44280-7185-11e9-8bd1-141f0f8f3872.png">

Yup, still there.

**Comment by codebykat** [comment] 2019-05-09 00:19
@shaunandrews I'm not 100% sure how to reproduce this exact state, but I did just find and fix a bug on WPCOM that *might* have been the cause. Can you check it again please? (D27994-code)

If you're still seeing these weird boxes, it would be helpful to know if it's in wp-admin too or just in wordpress.com/block-editor. And if you have any sites where it isn't happening?

**Comment by gwwar** [comment] 2019-05-15 20:46
Closing, please reopen if folks are still seeing this.

**Closed by gwwar** 2019-05-15 20:46 UTC
Labels: [Goal] Gutenberg, [Type] Bug

**Comment by shaunandrews** [comment] 2019-05-16 15:55
Yay, the boxes are gone!
