### ISSUE TITLE
Pay with PayPal Block Widget broken on Premium Plan Sites

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#58535] opened 2021-11-25 23:17 UTC
### Quick summary

The Pay with PayPal *block* widget seems to be quite broken on Premium Plan sites. The widget doesn't save all the title and description added in the editor, and the widget won't display on the live site, when using either method of building widgets.

While the block can't be _used_ on lower plan sites, I am able to edit the block and see the stand-in message telling me to upgrade my plan on a Personal plan site, which seems to indicate either an issue with the Premium plan specifically, or whatever features of the Premium plan enable that block to be used on sites.

#### Option 1: Appearance > Widgets
1. Open a test site on a Premium Plan
2. Go to Appearance > Widgets
3. Add the (non-legacy) Pay with PayPal block widget
4. Try entering information and Updating the page

#### Option 2: Appearance > Customize > Widgets
1. Open a test site on a Premium Plan
2. Go to Appearance > Customize > Widgets
3. Add the (non-legacy) Pay with PayPal block widget
4. Enter in all required information and Saving Changes

### What you expected to happen

Either way, I expect to be able to add in all required information and save those changes, then see them reflected accurately when I return to the Widget editor and when I visit the live site.

#### Option 1: Appearance > Widgets

Here, I can add the block, but to enter information, I must key every character twice, across the entire block. This does not happen with any other block widget.

From there, `Update` appears greyed out, though this is possibly a larger issue.

https://user-images.githubusercontent.com/27249804/143505462-2a6a9c8d-3dd1-4b2a-84d3-72f2e7aee048.mov

#### Option 2: Appearance > Customize > Widgets

In the Customizer, I'm able to add all details into the block widget, but it does not appear in the customizer's preview or on the live site:

https://user-images.githubusercontent.com/27249804/143505581-7193a0ab-45b9-45d1-8f98-9af3cb673691.mov

Live site results:
<img width="1304" alt="Screen Shot 2021-11-25 at 3 46 14 PM" src="https://user-images.githubusercontent.com/27249804/143505658-a71ccf9e-4d2f-4a14-af28-0728c3b25516.png">

When I refresh the Customizer, the details added to "Item Name" and "Description" don't save:

https://user-images.githubusercontent.com/27249804/143505681-37e52fc8-87cc-4d18-9363-9086ffb6f6cb.mov

### Context

 User reported they weren't able to see the widget appear on their live site here: 

- 4465786-zd-woothemes

### Operating System

macOS

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

Tested on Independent Publisher 2 and Twenty Twenty One

### Other notes

Other issues that may be appearing in these tests:

The way the **Pay with PayPal** *Block* widget appears in Appearance > Customize > Widgets is consistent across all my test sites.  (See screenshots below)

The `Update` button not responding in my Premium Test site's Appearance > Widgets area is behaving this way even without the **Pay with PayPal** *Block* widget, so this may be another issue as well

### Other tests run:

- Business AT, theme: Independent 2: works as expected, keeping in mind notes above:
<img width="1437" alt="Screen Shot 2021-11-25 at 4 09 44 PM" src="https://user-images.githubusercontent.com/27249804/143506709-527fdbb2-439d-4213-81df-ece98e8cac60.png">

- Personal plan, theme: Independent 2: works as expected, showing the 'upgrade to use this premium block' content in the site preview:
<img width="1291" alt="Screen Shot 2021-11-25 at 3 57 43 PM" src="https://user-images.githubusercontent.com/27249804/143506624-e94ff75c-4712-4122-a100-8b33b8340d2d.png">

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

I wasn't able to get the Legacy Widget to work either for the user who reported this originally.  Looks like there is at least one bug open related to the Legacy widget here: #55333

For the user, I recommended using the Pay with PayPal block outside of Widgets, instead. Not an ideal workaround as this won't behave like the widget.

With Block Widgets disabled temporarily for troubleshooting purposes, I _could_ add the legacy widget in Appearance > Widget and then the Customizer, but once block widgets were restored, I ran into issues being able to edit the Legacy Widget.

**Appearance > Widgets with Block Widgets temporarily disabled:**
<img width="998" alt="Screen Shot 2021-11-25 at 4 10 52 PM" src="https://user-images.githubusercontent.com/27249804/143506760-da33aa22-916b-4d4b-892d-354d5f5cb94f.png">

**Appearance > Customizer with Block Widgets temporarily disabled:**
<img width="1393" alt="Screen Shot 2021-11-25 at 4 12 02 PM" src="https://user-images.githubusercontent.com/27249804/143506809-c925f726-f35f-4cdc-b036-1bb2758e3d3d.png">

**Appearance > Customizer with Block Widgets enabled:**
<img width="1336" alt="Screen Shot 2021-11-25 at 4 13 01 PM" src="https://user-images.githubusercontent.com/27249804/143506849-a67eeb86-fa08-4e07-b7a9-a13f1e6eff40.png">

**Comment by kosiew** [comment] 2021-11-29 01:37
Hi @cuemarie ,

Thanks for reporting this and the detailed steps.

I could reproduce this on a Simple site.

Triaging for developers' further investigation.

**Comment by CodeAllNightNDay** [comment] 2021-11-29 19:44
I ran into another site where the Pay with PayPal Block is not showing on the live site. The plan was recently upgraded to Premium.
4550438-zd-woothemes

I can see the existing Pay with PayPal Block in the footer section when trying to edit it, but the area is totally blank on the live site. I also noticed nothing happened when I tried to add a new Pay with PayPal Block in this area.

**Comment by Robertght** [comment] 2021-12-21 09:04
@michaeldcain is this something the team can look into in the near future?

**Comment by AtrumGeost** [comment] 2022-01-18 13:28
I got another report here:

4696463-zd-woothemes

The user purchased the Premium plan to add the Pay with PayPal block. I was able to reproduce the issue on my test site:


https://user-images.githubusercontent.com/3696121/149946166-9ab29b8b-32bc-4f82-b222-3fe5d50c5266.mp4



The block title won't be saved and the block won't be displayed on the actual site.

I turned off the Widget Block Editor, and was able to add the Pay with PayPal widget.

**Comment by michaeldcain** [comment] 2022-01-18 21:55
@Automattic/ajax @Copons: I missed this in my notifications and David just found it. Do you think this falls within Ajax's front-end issues?

**Comment by dsas** [comment] 2022-01-19 10:26
Looks like something for us @michaeldcain, it's on our backlog.

**Comment by dsas** [comment] 2022-01-19 10:28
I can't reproduce the double typing thing. I can reproduce the not saving title/description on a simple site via standalone widgets page but standalone jetpack works fine.

**Comment by Copons** [comment] 2022-01-19 13:13
@michaeldcain Yeah this looks like a full-fledged Gutenberg issue, so it falls into Ajax domain.
Note that as per Artur triage, we are delaying most work on the Pay with PayPal block, and it's not part of our current iteration.

**Comment by jromales** [comment] 2022-01-20 09:36
Another report here: 4702682-zd-woothemes

They are on a Premium plan, and I disabled Widget Block Editor so user can add the block in the Customizer area as a temporary solution.

**Comment by aleone89** [comment] 2022-02-08 10:54
Hello, there's another report here:  zen-4755526 with the natural theme. 

I also stumbled across this GH too: https://github.com/Automattic/themes/issues/5274 

Are these the same issue:

**Comment by Copons** [comment] 2022-02-14 15:45
Note: this also seems to happen in the site editor.

**Comment by Jaykame** [comment] 2022-02-18 04:58
Hi there, I replicated this issue on another case here: 4789408-zen

**Comment by ahmadbaig1** [comment] 2022-02-20 06:02
Another one here- 4794713-zen

**Comment by kingsleyinfo** [comment] 2022-02-21 09:42
Another one here 4798290-zen

**Comment by csabarakasz** [comment] 2022-03-13 08:14
Same issue as described in the original report: 4854517-zd-woothemes

I have implemented the mentioned workaround to the user, but it anything would need to be changed on the Block widget, it will break again.

**Comment by BogdanUngureanu** [comment] 2022-03-15 12:50
Fixed in 607-gh-Automattic/dotcom-manage.

**Closed as completed by BogdanUngureanu** 2022-03-15 12:50 UTC
Labels: Bug, [Pri] Normal, Triaged, [Block] Pay with PayPal
