### ISSUE TITLE
Gutenberg: Search on block picker breaks after typing "s" character

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#47217] opened 2020-11-07 08:28 UTC
#### Steps to reproduce

- Start with a WordPress.com site on the simple platform or Atomic (WordPress.com site with a plugin or third-party theme installed) platform.
- Open the post/page editor.
- Click on `+` icon for the block picker to appear.
- On the search box, type `s`. (for example, start typing `social`)
- After typing `s`, the search box loses focus, thus breaking user's typing action.

#### What I expected

The search box does not lose focus and I am able to finish typing `social`

#### What happened instead

Search box loses focus, thus breaking my typing.

#### Browser / OS version

Firefox 82.0.2 (64-bit)

#### Screenshot / Video

Here is a video that indicates that I could type `ocial`, but when I try trying `social`, search box loses focus after typing `s` - https://d.pr/v/EIzEYq/eImoLOlnxd

#### Context / Source

#user-report. 3470832-zen

**Comment by arunsathiya** [comment] 2020-11-07 08:37
It's worth noting that I cannot see the same issue on a Dotorg (WordPress.org) website with Gutenberg 9.3.0. My tests on the Atomic site were having Gutenberg 9.2.2, and the same version of Gutenberg seems to be on simple sites as well:

<img width="247" alt="Screenshot 2020-11-07 at 2 06 55 PM" src="https://user-images.githubusercontent.com/18581859/98436582-803c0380-2102-11eb-8ad0-00ae39794c21.png">

**Comment by cathymcbride** [comment] 2020-11-10 17:42
Looks like this is a duplicate of https://github.com/Automattic/wp-calypso/issues/47033. Closing this one in favor of the earlier one.

**Closed by cathymcbride** 2020-11-10 17:42 UTC
Labels: Editor, [Goal] Gutenberg, [Type] Bug
