### ISSUE TITLE
Display name is not updating for past comments, and can't be edited with Calypso

### ISSUE THREAD

**Issue by mdtanjid0** [Automattic/wp-calypso#61773] opened 2022-03-09 18:23 UTC
### Quick summary

I can see a similar issue on the Atomic site:
#55175

If a user updates the _display name_, that doesn't update on the past comments on the simple site. 

Also, they can't even change the _display name_ from the comments admin; editing the comment does not allow us to do so. 

But it works fine if we try that with the classic view.

So there are two issues: 

* Updated _display name_ is not showing on the past comments. 
* Display name can't be changed by editing the past comments with Calypso, but it works fine with the Classic Editor. 

With Classic Editor:
![Annotation on 2022-03-14 at 22-35-44](https://user-images.githubusercontent.com/54123436/158219426-7d3ed916-473d-4d0b-bc97-ae682ac41c2b.png)

WIth Calypso:

![Annotation on 2022-03-14 at 22-38-39](https://user-images.githubusercontent.com/54123436/158219407-98a0b25b-263a-40ca-9638-fe1f4039c6e6.png)

### Steps to reproduce

Make sure you have a simple site with some comments on the blog. 

1. Click on the profile.
2. Change the display name from the profile settings. 
3. And the check back past comments
4. See, the display name is not updated. 
5. And then go to "comment" from the dashboard. 
6. And try editing the display name of a comment with Calypso. 
7. And try the same with Classic Editor by clicking on the top-right corner where it says "view." 

### What you expected to happen

The display name should update on the past comments as well so that users don't need to update them manually. 

And display name should be changeable from the Calypso screen in the same way as the "Classic editor" does. 

### What actually happened

Users can't change the username from Calypso, and changing the username is not updating on the past comments.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari, iOS Safari, Android Chrome

### Simple/Atomic

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

The workaround is changing the user's name from the classic view by going to the comment admin panel. 

It requires to change for each comment.

**Comment by cuemarie** [comment] 2023-05-25 22:07
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Simple - **Replicated**
- Tested on Atomic - **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I am able to replicate this on Simple and Atomic - same behavior. When a comment is left on either site, the comment name matches the display name at the time, and doesn't update to reflect a new display name. 

![QqsDqn.png](https://github.com/Automattic/wp-calypso/assets/27249804/9bce152b-7819-4aae-8269-c228e24d411e)

📌 ACTIONS
- This honestly looks like the intended behavior, esp since the behavior matches across Simple & AT. @jeherve perhaps you could weigh in on this? (there's lots of discussion on this issue as well: https://github.com/Automattic/wp-calypso/issues/55175 )

**Comment by jeherve** [comment] 2023-05-26 15:56
> This honestly looks like the intended behavior, esp since the behavior matches across Simple & AT.

Yup, I believe that's the expected behavior. 👍

**Comment by cuemarie** [comment] 2023-05-31 17:22
📌 ACTIONS
- Closing as by design

📌 Message to Author
- As this seems to be the expected behavior, closing this issue.  If need be, feel free to open a new feature request about this instead.

**Closed as completed by cuemarie** 2023-05-31 17:22 UTC
Labels: Bug, [Pri] Low, [Feature] Comments, Triaged, [Platform] Simple, [Platform] Atomic
