### ISSUE TITLE
Editor: Cannot use inline text toolbar on iOS

### ISSUE THREAD

**Issue by nylen** [Automattic/wp-calypso#4905] opened 2016-04-20 21:06 UTC
The inline text toolbar with copy/paste functions disappears immediately on iOS (Simulator; iPhone 6 / iOS 8.2):

![title-copy-ios](https://cloud.githubusercontent.com/assets/227022/14690528/215f015a-0712-11e6-840a-21467c84d19b.gif)

Happens in title, content, and option inputs like slug/excerpt.

Noticed while testing #4826.

**Comment by hoverduck** [comment] 2016-07-18 18:15
#bug-scrub

Closing, unable to reproduce on iPad Air 2 iOS 9.3.1.  If it's still an issue on other iOS devices, please feel free to re-open.

**Closed by hoverduck** 2016-07-18 18:15 UTC
Labels: Editor, [Type] Bug
