### ISSUE TITLE
Media Library not loading thumbnails for image selection in editor

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#95173] opened 2024-10-06 18:11 UTC
### Quick summary

When selecting images from media library (i.e. in a Gallery block or Image block) the media thumbnails are very slow to load or will break.  

https://github.com/user-attachments/assets/bb689831-66be-4caa-987f-8203a3ad7717

![Image](https://github.com/user-attachments/assets/ec3533db-31b2-44f6-b412-e6e380dfdd5d)

### Steps to reproduce

1. Add a Gallery block
2. Select media from media gallery
3. Scroll media, change thumbnail size
4. Cancel selection
5. Reopen select from media window again

### What you expected to happen

Media thumbnails should load quickly

### What actually happened

Media thumbnails load slowly or not at all

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported in 8832581-zd-a8c and 8831443-zd-a8c

**Comment by supernovia** [comment] 2024-10-06 19:27
PAs: This _might_ be related but we'd need to verify: https://github.com/Automattic/wp-calypso/issues/92607

**Comment by Robertght** [comment] 2024-10-07 11:43
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate 
 
📌 FINDINGS/SCREENSHOTS/VIDEO
- I was unable to replicate the broken thumbnails, but I can confirm the images loaded fairly slow. I've used Chrome in the process.

📌 ACTIONS
- Triaged
- Requested author feedback
- Changed priority to "High"


📌 Message to Author
- @philnick206 I'm not able to replicate the broken thumbnails on my end, however, could you let us know if you're using any particular browser?

**Comment by taipeicoder** [comment] 2024-10-07 13:47
Using Firefox, checked the user's site and confirmed that the thumbnails load very slow but not broken. Could probably mark as duplicate in favor of https://github.com/Automattic/wp-calypso/issues/92607.

**Comment by synora** [comment] 2024-10-07 14:09
There's another report (with a screenshot) of this in 8839058-zen-a8c. 
I can replicate this when I attempt to add the given file to their media library. Their screenshot appears to be Chrome which is what I'm using as well (my version 129.0.6668.90 (Official Build) (arm64))

**Comment by taipeicoder** [comment] 2024-10-08 09:00
Proposing D163310-code as a fix.

**Comment by supernovia** [comment] 2024-10-08 10:24
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated, and it's very similar to another issue

📌 ACTIONS
- Triaged
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/92607

📌 Message to Author
@philnick206  and @synora , this seems to be same issue as https://github.com/Automattic/wp-calypso/issues/92607 so I am closing in favor of that and moving the interactions over. The workaround is to use the classic view, but given it's a broken experience for users, I will increase the priority of the other issue.

**Closed as completed by supernovia** 2024-10-08 10:24 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] High, Customer report [LEGACY], [Platform] Simple, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience, Groundskeeping
