### ISSUE TITLE
Ensure editor mobile zoom works

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#42148] opened 2020-05-13 10:05 UTC
Editor's zoom might be broken on iOS devices:

<img src="https://user-images.githubusercontent.com/87168/81799651-54a4db80-951a-11ea-87f2-0f15b344a5ea.jpeg" alt="" width="320"/>
<img src="https://user-images.githubusercontent.com/87168/81799655-57073580-951a-11ea-84f7-7819e0ed89d6.png" alt="" width="320"/>

On my Iphone 11 Pro, running chrome in incognito mode.

**Comment by sirreal** [comment] 2020-05-13 15:11
I've been testing via iOS simulators and Safari, and I've been unable to reproduce this error.

I don't have the hardware necessary to test Chrome on a recent iOS device.

**Comment by yansern** [comment] 2020-05-14 11:04
I think the quick fix is to find a way to set this to "Mobile" when a mobile browser is detected on editor launch.

![image](https://user-images.githubusercontent.com/1287077/81927105-630afa00-95e3-11ea-9c04-b6ec60796613.png)

**Comment by sirreal** [comment] 2020-05-14 12:00
There may be some insights here: https://github.com/WordPress/gutenberg/pull/21102
That might fix any issues like this.

**Comment by tjcafferkey** [comment] 2020-10-20 14:43
After some investigation I found that these styles getting applied in the Block Editor from this file (26dde-pb) are causing the issue. Commenting them out appears to fix the issue but we don't want to do that.

I have logged an issue https://github.com/Automattic/block-experiments/issues/152 to understand more about why they exist as I'm sure there's a reason they belong there.

**Comment by roo2** [comment] 2020-12-16 03:30
@tjcafferkey @simison @yansern   I've raised https://github.com/Automattic/block-experiments/pull/161 which is a potential solution to allow the editor to work intuitively for mobile and still support the current preview mode

**Comment by cathymcbride** [comment] 2021-02-04 21:56
@worldomonation this should be fixed from a recent check in. Can you verify that?

**Comment by worldomonation** [comment] 2021-02-04 23:24
> @worldomonation this should be fixed from a recent check in. Can you verify that?

I took a look. My understanding of the issue is that when entering the editor using an iOS browser, the editor is not sized for the mobile phone screen.

If my understanding is correct, then I can confirm the editor experience on iOS Safari is as I would expect. For more information, please see attached screen recording of my interactions:
https://d.pr/v/O72Sce

**Comment by worldomonation** [comment] 2021-02-04 23:36
I also checked the Column block type on mobile and tested the responsive breakpoints:
![スクリーンショット 2021-02-04 15 33 38](https://user-images.githubusercontent.com/6549265/106968914-aa4f9280-66fe-11eb-9f16-8a93633350a7.png)
![Edit Post ‹ Edwin's Test Site 1 — WordPress](https://user-images.githubusercontent.com/6549265/106968926-b0de0a00-66fe-11eb-94e5-86c6523981e8.png)

**Comment by worldomonation** [comment] 2021-02-04 23:51
I've also checked on desktop Firefox that following works:

1. insert Layout Grid block.
2. fill in some content in each of the columns.
3. from block options, select `Mobile` for Responsive Breakpoint.
4. enter preview.
5. change preview mode to `Mobile`.

The resulting preview is in line with the selected breakpoint.

**Comment by johngodley** [comment] 2021-02-05 14:02
This should now be fixed as part of https://github.com/Automattic/block-experiments/pull/161 - the preview dropdown is hidden on mobile, and the grid will display the mobile breakpoint by default.

I'll close this as resolved. If there are remaining problems please create an issue for them [here](https://github.com/Automattic/block-experiments). Thanks!

**Closed by johngodley** 2021-02-05 14:02 UTC
Labels: Mobile Web, [Goal] Gutenberg, [Pri] High, [Type] Bug
