### ISSUE TITLE
Embedding Twitter Feed displays Nothing to see here - yet

### ISSUE THREAD

**Issue by mgozdis** [Automattic/wp-calypso#78913] opened 2023-07-03 17:17 UTC
### Quick summary

Using the [Twitter Block](https://wordpress.com/support/wordpress-editor/blocks/twitter-block/#embed-a-single-tweet) to embed a Twitter Feed no longer displays the feed and displays "Nothing to see here - yet".

Not sure if this is related to recent API changes and restrictions on Twitter's end, but a user reported it and they claimed the feed was working recently. It seems to possibly be an outage or restriction on Twitter's end as 3rd-party plugins are  returning feed errors as well. 
User report: 6492425-zd-woothemes

The feed in our documentation is also displaying the same error at the time of reporting: ![0P9W4q.png](https://github.com/Automattic/wp-calypso/assets/121042930/db4c8d1d-6cc3-4b2b-a0db-13d25c26b793)

### Steps to reproduce

1. Add a Twitter block to a page
2. Configure the block with a Twitter account and embed

### What you expected to happen

The feed should be displayed.

### What actually happened

The feed displays "Nothing to see here - yet"

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

**Comment by cuemarie** [comment] 2023-07-03 19:23
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated** 
- Tested on Atomic – **Replicated** 
- Replicable outside of Dotcom – **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on Simple, Atomic, and self-hosted sites in the same way. 
- I suspect this is related to the more recent limits Twitter is enforcing (see https://twitter.com/elonmusk/status/1675187969420828672 ). By comparison, the Twitter embed block has not been updated anytime recently: https://wordpress.org/documentation/article/twitter-embed/#changelog

#### Screenshots/Recordings

Atomic & Simple site behavior:
![Markup on 2023-07-03 at 12:09:40](https://github.com/Automattic/wp-calypso/assets/27249804/89bac7dd-4dc0-406a-8385-c88816904a42)

Self-Hosted: 
<img width="923" alt="Screenshot 2023-07-03 at 12 23 17 PM" src="https://github.com/Automattic/wp-calypso/assets/27249804/0f49f479-250d-4628-bc28-158bf459b779">

📌 ACTIONS
- Scrubbed, awaiting assignment
- Reported in `/gutenberg`: https://github.com/WordPress/gutenberg/issues/52260

**Comment by cuemarie** [comment] 2023-07-04 21:56
From Core issue I opened:

> It's a big bummer for many publishers. However, it might just be a temporary: [Elon Musk claims Twitter login requirement just 'temporary'](https://mashable.com/article/elon-musk-twitter-login-requirement-temporary) (Source: Mashable)

📌 ACTIONS
- I've removed the `Core fix needed` label and dropped priority on this to `High`, mainly because there's not something internal that's blocking this from happening; it's just the current way Twitter works (or doesn't). We'll need to wait and see what happens there.
- Moving to `ON HOLD`

**Comment by AnjanaV93** [comment] 2023-07-05 05:45
Another report in 6495792-zen

**Comment by ezebecke** [comment] 2023-07-05 15:37
Another case 6501714-zd-woothemes

**Comment by cuemarie** [comment] 2023-07-05 23:23
Thanks y'all.  As this is all dependent on Twitter, I'm going to close this to avoid confusion as to whether this is a bug. It's not a WordPress.com bug - it's just Twitter's latest rules. As such, there's no need to track interactions with users on this issue.

Internally, we're working on getting p7DVsv-hfB-p2 updated to be a main post you can refer to for updates on Twitter changes and their impact on WordPress.com and our customers. 

📌 ACTIONS
- Closed as this is not a bug we can fix, but a change on the 3rd party's side.

**Closed as not planned by cuemarie** 2023-07-05 23:23 UTC
Labels: Bug, [Pri] High, Triaged, [Block] Embed, [Status] Priority Review Triggered, [Status] 3rd Party Fix Needed

**Comment by daria2303** [comment] 2023-07-18 15:19
@cuemarie I got another case with this issue. Shall we update our documentation? https://wordpress.com/support/wordpress-editor/blocks/twitter-block/

**Comment by cuemarie** [comment] 2023-07-18 21:07
Good idea @daria2303 ! I've requested that update on the docs issue here: https://github.com/Automattic/en.support-docs-content/issues/2029
