### ISSUE TITLE
Push Notifications: Firefox opens new tab instead of focusing existing Calypso

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#6222] opened 2016-06-22 15:28 UTC
#### Steps to reproduce
1. Enable desktop Push Notifications on Firefox
2. Keep a tab open with Calypso running
3. Spawn a notification and click on it

#### What I expected
The existing tab to be focused

#### What happened instead
A new tab was opened to https://wordpress.com with the notifications pane expanded

#### Browser / OS version
OSX 10.11.5 Firefox 46.0

#### Context / Source
#manual-testing

**Comment by hoverduck** [comment] 2016-06-22 18:42
Also tested on the latest version of Firefox (v48) and this is not an issue there.

**Comment by mjuhasz** [comment] 2016-06-23 21:50
Thank you for the report!

Here is a summary of how this bug affects different Firefox versions:

- The issue was reported against Firefox v46.
- I tested Firefox v47, and I was unable to reproduce the issue with that version. Version 47.0 was first offered to Release channel users on June 7, 2016. The new Release version, v47 replaced the prior v46 version, and the prior version was abandoned as to security and stability updates. Nevertheless Calypso supports the latest two versions of all major browsers.
- In the previous comment it was confirmed that Firefox v48 also works as expected.

**Comment by lancewillett** [comment] 2016-10-14 19:35
Since latest stable version and 1 back are working as expected, closing.

**Closed by lancewillett** 2016-10-14 19:35 UTC
Labels: Notifications, [Type] Bug
