### ISSUE TITLE
P2 Editor back end: not all selected text becomes hyperlink

### ISSUE THREAD

**Issue by fylgjur** [Automattic/wp-calypso#43427] opened 2020-06-18 08:31 UTC
#### Steps to reproduce

In P2 back end - happens intermittently with no discernable pattern.
A8C P2. 
I have not been able to reproduce this in a non P2 blog or in front end.

- Select the text and add a link. 
- I expect all the text I selected to become a hyperlink.
- Only part of the text that was selected becomes a link.

#### Browser / OS version

Windows 10 Home, 10.0.18363
Chrome: Version 83.0.4103.106 (Official Build) (64-bit)
#user-report

#### Screenshot / Video

First example:

![bug2](https://user-images.githubusercontent.com/65490337/84928381-35bfd900-b0c6-11ea-982b-fc65f3c74556.gif)

Second example:

![bug10](https://user-images.githubusercontent.com/65490337/84997064-fd5fdf80-b145-11ea-8755-c159d6be5264.gif)

**Comment by klimeryk** [comment] 2020-06-18 10:21
I can reproduce this reliably if while selecting the text, I move my pointer outside the editor area. Though it seems from the second example above that is not always needed. FWIW, I'm using Firefox 77.0.1 on macOS 10.15.5.

**Comment by jasmussen** [comment] 2020-06-18 10:32
Thanks for the steps. I can reproduce reliably on:

- Calypso block editor
- WordPress.com block editor (in wp-admin)
- My own standalone WordPress website running Gutenberg version 8.3

I cannot reproduce on anything that runs the latest build of the Gutenberg plugin (8.4 prerelease). That suggests that this is an issue that has already been fixed in the WordPress core project.

**Closed** 2021-02-27 17:00 UTC
Labels: OSS Citizen
