### ISSUE TITLE
Editor: can't paste an image caption

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#10254] opened 2016-12-23 12:26 UTC
#### Steps to reproduce
1. in the post editor, insert an image and choose to add a caption
2. put the cursor into the caption
3. use Command+V to paste in your clipboard contents

#### What I expected

I expected the pasted text to be inserted into the caption area. 

#### What happened instead

Instead, the pasted text appeared below the caption area. 

#### Browser / OS version

Safari Technology Preview Release 20 on macOS 10.12.2. 

#### Screenshot / Video

![cant-paste-caption](https://cloud.githubusercontent.com/assets/23619/21453813/4daa3478-c913-11e6-812c-24a30b9d8d31.gif)

#### Context / Source

Trying to paste in the caption a few times results in the following source:

```
[caption id="attachment_1119" align="aligncenter" width="1024"]<img class="aligncenter size-large wp-image-1119" src="https://leif.me/wp-content/uploads/2016/12/diffusion-of-innovations-how-new-ideas-spread-individual-process-1024x110.png" alt="diffusion-of-innovations-how-new-ideas-spread-individual-process" width="1024" height="110" /> Enter a caption[/caption]

The innovation-decision process for individuals according to Rogers.

The innovation-decision process for individuals according to Rogers.

The innovation-decision process for individuals according to Rogers.
```

**Comment by thepelkus-too** [comment] 2016-12-23 21:55
Can repro in Chrome v55.0.2883.95 on OSX 10.12.1.

I'm not super familiar with the ins and outs of TinyMCE, esp. in WordPress, but removing the paste plugin from client/components/tinymce/index.jsx made the paste functionality work at least _closer_ to what was expected, though the caption box started behaving a little odd with multiple pastes.

**Comment by melchoyce** [comment] 2017-04-04 23:30
Encountered this bug today. :/

**Comment by pento** [comment] 2017-04-23 06:22
This is [fixed in Core](https://core.trac.wordpress.org/changeset/38756) as of WordPress 4.7, I don't know what the process is for porting the fix to Calypso editor.

**Comment by lsinger** [comment] 2017-04-24 13:15
Good catch! Thanks for the note, @pento. I'll ask around.

**Comment by aduth** [comment] 2017-04-28 15:03
Duplicate of #1658

**Closed** 2017-04-28 17:04 UTC
Labels: Editor, [Triage] Close Me, [Type] Bug
