### ISSUE TITLE
Devdocs: button component docs broken

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#43095] opened 2020-06-09 11:44 UTC
Styles seem to be missing at least for button component at Devdocs:

https://wpcalypso.wordpress.com/devdocs/design/button

![image](https://user-images.githubusercontent.com/87168/84143697-af6d1c80-aa5f-11ea-9553-0df650d6ced0.png)

**Comment by jsnajdr** [comment] 2020-06-09 12:06
Duplicate of #41051.

**Closed by jsnajdr** 2020-06-09 12:06 UTC
Labels: DevDocs, [Type] Bug
