### ISSUE TITLE
Email notifications: not all email clients format the email templates the same

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#91227] opened 2024-05-29 07:44 UTC
### Quick summary

We heard from a user who noticed that on the email templates not getting the same formatting(especially side margins/padding) 

The user reported the issues appearing more on the email apps on mobile(especially Apple Email).

### Steps to reproduce

The most obvious for me was Titan Email so you can test a new post notification email there.

### What you expected to happen

Quoting the user:

Take a look at the screenshots I have below. The first ones are WordPress. The second ones are from a different company.

The first one is the WordPress email notification to my subscribers. There is no margin around the email at all. Including around the title of the post, and even the "continue reading" button (which you cannot control in the editor). 

I know from a web design perspective, you never put text from edge to edge like this with no margin.

![image](https://github.com/Automattic/wp-calypso/assets/6737345/672b9fb7-f991-4979-9c2e-72da867ef121)

![image](https://github.com/Automattic/wp-calypso/assets/6737345/ce99a84a-5545-42f3-9749-a46b4af7ad61)

Now, below is a screenshot from another company, whose emails have margins. This is how it should look.

![image](https://github.com/Automattic/wp-calypso/assets/6737345/fb8db009-0d25-4196-acbb-302e243fa025)

The reason why most people you talk to won't be able to see this is because,  certain email apps put a margin around the email itself.

The problem is most evident when using Apple Mail on an iPhone, using dark mode, but the problem exists on any email app. 

I have tested on:

-multiple iPhones
-using both Apple Mail and Outlook

it's clear that there are no margins on any titles, text, images, or buttons.

Here is a screenshot from Outlook on iPhone. It's harder to tell because Outlook puts margins around your email itself. But if you take a close look, you'll see that there's no margin on the WordPress email itself. Only the margins that the outlook app is putting in itself.

![image](https://github.com/Automattic/wp-calypso/assets/6737345/3855980b-8898-459f-8df8-70a424308907)

---

My findings were obvious only when using the Titan Email inbox on desktop: 

![esBvHL.png](https://github.com/Automattic/wp-calypso/assets/6737345/e4222d6c-10d7-4d96-88ba-eeb246d272b0)

### What actually happened

To work the same regardless of the email environment.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

8246574-zen

I asked the user to share their iOS and model of iPhone so we can continue to try and replicate this.

cc @Automattic/apex

**Comment by suyogyashukla** [comment] 2024-05-31 10:04
The user followed up and shared:

> Hi, yes I am using an iPhone 14 Pro Max, but I have also tested it on an iPhone 14 Plus. 

> I am running iOS 17.4.1.

**Comment by liviopv** [comment] 2024-05-31 10:16
📌 REPRODUCTION RESULTS
- Tested on Simple – Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
Titan Email, Desktop:
![CleanShot 2024-05-31 at 11 08 47@2x](https://github.com/Automattic/wp-calypso/assets/14153300/a90261e2-7bd0-494a-875f-3ce606af1f51)

Titan, Android App
![Screenshot_20240531-111132](https://github.com/Automattic/wp-calypso/assets/14153300/5c396ad9-b99a-4afd-b3e0-689c3f0f72d3)

Gmail, desktop
![CleanShot 2024-05-31 at 11 12 44@2x](https://github.com/Automattic/wp-calypso/assets/14153300/be8fdda6-69fb-4d9b-ba5f-aba6eb2ea629)

Gmail, Android app
![Screenshot_20240531-111311](https://github.com/Automattic/wp-calypso/assets/14153300/3fe62610-6bf8-4a32-ba1a-14e023a89d3e)


📌 ACTIONS
- Requested author feedback

📌 Message to Author
@Robertght @suyogyashukla if there is an issue, it's likely specific to iOS. Do any of you have iPhones where you can test this on?

Also cc @mrfoxtalbot @inaikem and @rickmgithub in case you have iPhones to test this

**Comment by simison** [comment] 2024-05-31 11:16
More debugging welcome! We'll try to replicate & fix this with Zap.

**Comment by Robertght** [comment] 2024-06-02 05:07
I couldn't see the issue on my iPhone 13 Pro using the Mail app.

**Comment by simison** [comment] 2024-06-04 08:26
Similar internal feedback in peKye1-RV-p2

**Comment by pkuliga** [comment] 2024-06-13 09:45
I wasn't able to replicate this on Apple Mail on mobile. Newsletter email looks ok there for me:

![441929628_963002755608218_2261633836595317379_n](https://github.com/Automattic/wp-calypso/assets/4068554/8655eec9-f4fc-4901-901c-6abe612fca1c)

On a desktop though when you shrink the preview window width I noticed the issue and fixed it (D151899-code).

| Before | After |
|--------|--------|
| <img width="547" alt="Screenshot 2024-06-12 at 12 08 37" src="https://github.com/Automattic/wp-calypso/assets/4068554/23dfc08f-9a66-4719-b892-fb1210b76459"> | <img width="547" alt="Screenshot 2024-06-12 at 12 08 42" src="https://github.com/Automattic/wp-calypso/assets/4068554/bb6454a4-c40a-477d-94d7-a9e60d830d7c"> |

I'll continue investigating the issue with the Titan Email on desktop.

**Comment by candy02058912** [comment] 2024-07-09 08:53
I don't see an issue with my normal settings.

Sharing what the email looks like in Gmail in Arc Browser desktop (Version 1.49.1 (51495) Chromium Engine Version 126.0.6478.127)
![email](https://github.com/Automattic/wp-calypso/assets/6586048/40acc44a-5895-48be-a89b-f2ff2f0e963e)

Gmail App in iOS 17 on iPhone 11
<img width="414" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6586048/04cfcf0e-ba55-43d8-9c42-99a8e0a65782">


Hi @Automattic/zap @simison @pkuliga, checking in on the status/priority of the issue?
As part of pb5gDS-3YO-p2, we’re trying to ensure that every blocker/high priority issue on  [The One Board](https://github.com/orgs/Automattic/projects/391/views/12) is being actively worked on (has updates to it within 2 weeks) to reflect the priority of the issue.

1. If prioritization isn't possible, please close the issue with the label "Won't Fix" and comment with the reason for future reference.
2. If the issue is fixed, let's close the issue until future reports come in.

Thanks 🙏

**Comment by rickmgithub** [comment] 2024-07-12 06:14
I have a very similar case.

The emails sent to subscribers do not reflect the color scheme or layout of the actual post.

The example is https://anlilmusic.com/2024/07/01/forbidden-captured-by-koko/

When viewed in the email client, there is a white background and formatting is lost (8466263-zd-a8c)

The same issue occurs with the reader version too - https://wordpress.com/read/blogs/207150541/posts/1427

The user also has Titan email attached to their account. 

I tested on a separate test site and replicated it using the same theme, Assembler by Automattic and Hevor. The same problem occurred.

The colour had been set manually in the global styles by the look of it rather than picking a specific palette.

On the simplest level you can see my post has a black background
![Markup on 2024-07-12 at 16:12:40](https://github.com/user-attachments/assets/c30ffe4f-d7cc-4aa7-b0df-387a1c2a2609)

While the email does not
![Markup on 2024-07-12 at 16-13-35](https://github.com/user-attachments/assets/4dc213f4-92f8-4843-a9de-d140d30282b5)

**Comment by lsl** [comment] 2024-08-06 01:35
Closing per @candy02058912 not being able to reproduce after the fix from @pkuliga [mentioned here](https://github.com/Automattic/wp-calypso/issues/91227#issuecomment-2165153061).

> I have a very similar case.

@rickmgithub this should be covered by the new Jetpack issue: https://github.com/Automattic/jetpack/issues/38372

**Closed as completed** 2024-08-06 01:35 UTC
Labels: Bug, [Pri] High, Triaged, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered, [Feature] Site Content Emails, [Product] WordPress.com, [Feature Group] Content Management
