### ISSUE TITLE
Gallery Block: Make sure older images are removed when newer images are still uploading

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37291] opened 2019-11-03 22:22 UTC
Please watch the "Editing a Page Template: Gallery Block" testing video on this post: p58i-8d4-p2

If you remove existing images in a gallery block while new images are still uploading, the existing images that you removed will reappear. The user in this testing video struggled with this multiple times.

**Comment by Addison-Stavlo** [comment] 2019-12-13 21:07
I have opened a PR in core for this - https://github.com/WordPress/gutenberg/pull/19134

**Comment by lancewillett** [comment] 2020-03-09 17:45
Closing as a duplicate of https://github.com/WordPress/gutenberg/pull/19134

No need to track it in two places; and once fixed it'll be merged into WordPress.com in a future Gutenberg core merge.

**Closed by lancewillett** 2020-03-09 17:45 UTC
Labels: Core fix needed, Design Needed, Editor, [Pri] High, [Type] Bug
