### ISSUE TITLE
Cover Block "Styles" not working on Atomic sites

### ISSUE THREAD

**Issue by eoinsav** [Automattic/wp-calypso#41724] opened 2020-05-02 01:25 UTC
When applying the Styles (Top Wave or Bottom Wave) to the Cover Block on an Atomic site, they appear in the editor but not on the live site. It works on Simple sites, so it appears to be related to the CoBlocks plugin on Atomic sites.

#### Steps to reproduce

1. Create a new page on an Atomic site.
2. Add a Cover Block.
3. Select a Style from the right side.
4. Publish the page and look at it on the live site.

#### What I expected
It should look like it does in the editor, as shown here:

<img width="1200" alt="Cover Block Styles Editor png" src="https://user-images.githubusercontent.com/35590156/80851640-cb1b1280-8bd7-11ea-8c08-8520af6013c8.png">

#### What happened instead
The image is just a regular unstyled Cover Block image, as shown here:

<img width="1200" alt="Cover Block Styles Live Site" src="https://user-images.githubusercontent.com/35590156/80851656-e0903c80-8bd7-11ea-9a35-4368fd2e030c.png">

#### Browser / OS version
Any.

#### Screenshot / Video
See above.

#### Context / Source

#user-report in #2937208-zen

**Comment by edwinho89** [comment] 2020-05-06 10:08
Another issue reported in #2949969-zen

**Comment by KristinaKay** [comment] 2020-05-07 01:34
Another report here: #20900423-zen

**Comment by kosiew** [comment] 2020-05-09 06:09
#2958442-zen too

**Comment by reginabally** [comment] 2020-05-09 07:17
is-style-top-wave is not working in #20957564-hc

**Comment by AMcGrady** [comment] 2020-05-13 21:23
is-style-bottom-wave is not working in #21053432-hc

**Comment by kathleenjross** [comment] 2020-05-20 20:31
is-style-bottom-wave is not working in #21268817-hc

**Comment by eoinsav** [comment] 2020-05-21 15:56
Another report in #21276293-hc

**Comment by davipontesblog** [comment] 2020-06-12 02:12
I tested this on a test site, atomic, with Gutenberg 8.2.1, and cannot replicate the issue anymore. Also tested on one of the user report sites, on #21276293-hc, and the issue is not happening there either.

I am closing the issue for now. If there are any other reports please reopen.

**Closed by davipontesblog** 2020-06-12 02:12 UTC
Labels: Atomic, Blocks, [Type] Bug
