### ISSUE TITLE
Email: Post tags are not being included correctly in email updates sent to email followers

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#25851] opened 2018-07-03 09:33 UTC
This issue was communicated in 1255946-zen. The user said that emails that are sent to email followers with Post updates don't include the correct tags.

#### Steps to reproduce

1. Publish a new post.
2. The post is sent by email to email followers.

#### What I expected

Email updates sent to email followers should include the correct tags, drawing on the tags added to the source Posts.

#### What happened instead

The correct tags are omitted, and replaced with a tag that wasn't actually included in the first place.

#### Browser / OS version

Not OS/browser specific.

#### Screenshot / Video

This is the tag field in the emails:

![](http://cld.wthms.co/rGZDsB+)

These are the tags that appear in the post itself:

![](http://cld.wthms.co/rKKCoe+)

#### Context / Source

Ticket support request.

**Comment by rachelmcr** [comment] 2018-08-22 15:47
Thanks for the report! Since email notifications aren't part of Calypso, I'm going to go ahead and close this issue.

I also tested the issue on a test blog using the steps provided, and the email notification was sent with the correct tags on the post. This may require further investigation to determine if there is a user/site-specific problem in this case, or if there are some steps missing to reproduce the issue. If you can reproduce the issue on a test site, I'd recommend opening a new trac ticket to follow up with those details.

**Closed by rachelmcr** 2018-08-22 15:47 UTC
Labels: Email, Posts, Sharing, [Type] Bug
