### ISSUE TITLE
Embed Amazon Kindle - We're sorry. This preview is unavailable.

### ISSUE THREAD

**Issue by mrsjaved** [Automattic/wp-calypso#52263] opened 2021-04-24 21:06 UTC
### Steps to reproduce the behavior

1. Go to pages or posts.
2. Embed Amazon Kindle Book by copy pasting the link for example this: https://www.amazon.com/dp/B08QWH3817?ref_=k4w_embed_dp_err
3. Click on "FREE PREVIEW " under the embed either inside the editor or on preview.
4. See error:
Kindle
We're sorry. This preview is unavailable.

#### What I expected to happen
A preview of the book.

#### What actually happened
Error shared above. 

#### Browser / OS version
Chrome browser on Mac Big Sur.

#### Is this specific to the applied theme? Which one?
I checked it on multiple Varia themes and old themes for example Gateway and Business. Same issue.

On TwentyTwentyOne it opened the preview in a new window instead of displaying the preview in embed area. This is still better but not an expected output. 

#### Does this happen on simple or atomic sites or both?
Both.

#### Is there any console output or error text?
Nope!

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
No

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://d.pr/i/ZHpPz4/EKjPLCTN3r
![image](https://user-images.githubusercontent.com/15944096/136734953-76f851d9-3798-4c90-bcff-2efd7c6177a9.jpg)

**Comment by fresatomica** [comment] 2021-07-28 09:08
Reported here: https://wordpress.com/forums/topic/amazon-kindle-embedding/

**Comment by lsl** [comment] 2021-07-29 06:35
This was caused by an issue on Amazon's side of things, there are reports this is resolved now so closing the issue. 

@fresatomica the site linked from that post looks fixed now too.

**Closed as completed by lsl** 2021-07-29 06:35 UTC
Labels: Bug
