### ISSUE TITLE
Screen stuck after purchasing Jetpack Search from Marketplace

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#66110] opened 2022-08-01 08:28 UTC
### Quick summary

Found in https://github.com/Automattic/wp-calypso/pull/65252#pullrequestreview-1049233222:

> I also got stuck on this screen when purchasing the plugin from the Marketplace on an Atomic site or on a Jetpack site. There is a JS error that looks related:
>
> <img width="500" alt="Screen Shot 2022-07-25 at 12 24 00" src="https://user-images.githubusercontent.com/1233880/180757990-f5eccce2-3fd2-4cb7-b06f-090222693f12.png">
>
> The plugin is correctly installed though

### Steps to reproduce

- Go to https://wordpress.com
- Switch to a Jetpack or Atomic site
- Go to Plugins
- Purchase the Jetpack Search plugin

### What you expected to happen

To land on a thank you page after the plugin is installed

### What actually happened

The flow gets stuck at the loading screen

**Comment by BogdanUngureanu** [comment] 2022-08-11 11:47
I've followed the steps but couldn't reproduce the issue. @mmtr can you confirm that it's not reproducing anymore?

**Comment by mmtr** [comment] 2022-08-11 11:59
Yeah, I cannot reproduce this any longer! I guess it was either a temporary glitch or something that has been fixed in the meantime.

**Comment by BogdanUngureanu** [comment] 2022-08-11 12:09
Closing it since it's not reproduced anymore :)

**Closed as not planned by BogdanUngureanu** 2022-08-11 12:09 UTC
Labels: Bug, Needs triage, Marketplace
