### ISSUE TITLE
Scrolling: Scrolling in the sidebar also scrolls the main content frame

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/wp-calypso#20568] opened 2017-12-06 16:32 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/mikey.blog
2. If I scroll the sidebar to view more items, the main content frame scrolls as well
3. Tested on Firefox and Chrome, only happening in Chrome right now (even Incognito)
4. Happens on both Staging and Production
5. Also happens on the https://wordpress.com/me page

#### What I expected
Only the area I am scrolling in to scroll.  

#### What happened instead
Both the area I'm scrolling in and other areas scroll, too.

#### Browser / OS version
Chrome 62.0.3202.94
MacOS Sierra

#### Screenshot / Video
![sidebar-scrolling](https://user-images.githubusercontent.com/3220162/33672629-8523c1cc-da5f-11e7-849c-16a9f95cfd68.gif)

**Comment by designsimply** [comment] 2017-12-08 18:53
Tested and confirmed that if use Chrome 62.0.3202.94 on Mac OS X 10.13.1 and browse to various sections in Calypso's left navigation menu then switch to a site and try using the magic mouse to scroll just the sidebar that both the sidebar and the primary content area are both scrolled.

Note: if I grab the left navigation scrollbar by clicking with the mouse and then dragging it, the same problem does not happen.

**Comment by designsimply** [comment] 2017-12-08 19:07
Turns out this appears to be default browser behavior (internal ref: p1512759332000352-slack-calypso). Closing for now, but please re-open if it comes up a lot of times in the future or if you'd like to make a case for a change if that's possible.

**Closed by designsimply** 2017-12-08 19:07 UTC
Labels: Navigation, [Type] Bug
