### ISSUE TITLE
Notifications: Unread bell icon showing in wp-admin even though there are no unreads

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#95005] opened 2024-09-27 19:15 UTC
### Quick summary

Reported here: p1727456193128819-slack-C06DN6QQVAQ

The user has no unread notifications, but the unread icon (red circle) is showing in wp-admin in the admin bar. Also, the notifications panel isn't loading in wp-admin, but redirecting to Calypso. That sounds like notifications JS isn't loading in wp-admin.

This error shows in the console, on the Calypso notifications page:
`WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: `

### Steps to reproduce

1. Go to wp-admin for the affected site.
2. See the unread icon.

### What you expected to happen

No unread icon, and notifications panel slides out.

### What actually happened

Unread icon shows, and bell redirects to Calypso.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by pauljacobson** [comment] 2024-09-30 13:25
Just adding the interaction reference: 8762541-zen

**Comment by gius80** [comment] 2024-10-01 16:54
I've started doing some investigation. According to the code, the redirect seems to be the expected behaviour when 3rd party cookies are not enabled (I was able to replicate the issue with my user). The notification panel is loaded inside an iframe.

Here is the related code:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sabgrf%2Snqzva%2Qone%2Qi2.wf%3Se%3Q06n897q5%23576%2Q582-og

**Comment by Addison-Stavlo** [comment] 2024-10-01 18:37
> Also, the notifications panel isn't loading in wp-admin, but redirecting to Calypso.

This part sounds like third party cookies are disabled.

I wonder if the dot is related, showing an outdated state since 3PCs were disabled and cannot load the widget code to update the dot?

**Comment by gius80** [comment] 2024-10-04 15:14
I did some test locally and it seems that `/notifications/seen` endpoint is not called if 3rd party cookies are not allowed. I asked HE to reach out the user. p1728054723490639/1727456193.128819-slack-C06DN6QQVAQ

**Comment by Addison-Stavlo** [comment] 2024-10-04 15:47
> I did some test locally and it seems that /notifications/seen endpoint is not called if 3rd party cookies are not allowed.

That is true. I don't think a request to `/notifications/seen` goes out until the panel opens (and items are seen). But with 3PCs disabled the panel doesnt open and redirects to */notifications.

If they view the notifications elsewhere (*/notifications, within calypso, etc.) then the /notifications/seen should be updated. But the dot in wp-admin seems to be out of sync still.

**Comment by gius80** [comment] 2024-10-04 16:04
I've manually reset `notes_last_marked_seen` user meta, since even if they enable cookies the db would be updated only if the see an unseen note. I support session the notification disappeared.

**Comment by davemart-in** [comment] 2024-10-14 19:33
Removing this from The One Board since Loop picked it up.

**Comment by gius80** [comment] 2024-10-15 13:34
We reach out the user 10 days ago (8832566-zd-a8c) to double check their cookie settings. I SU into user account and everything looks good now, so I think it's safe mark this issue as solved.

**Comment by davemart-in** [comment] 2024-10-15 14:07
Thanks for the update! Closing this issue.

**Closed as completed by davemart-in** 2024-10-15 14:07 UTC
Labels: Bug, [Pri] High, Needs triage, Customer report [LEGACY], [Platform] Simple, [Status] Priority Review Triggered
