### ISSUE TITLE
Cover block: poor video quality

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#85130] opened 2023-12-12 06:27 UTC
### Quick summary

Video backgrounds on cover blocks have worse quality than self-hosted sites.

### Steps to reproduce

1. Download a video from Pexels: https://www.pexels.com/search/videos/4k/
2. Create a new page.
3. Insert a cover block and set its background source to the video you downloaded on step 1
4. See the results

### What you expected to happen

To see the video as closer to the original as possible.

Self-hosted example:

https://psbbobwoo2020com.mystagingwebsite.com/cover-block-test-4k/

Screenshot:

![gZKkc4.png](https://github.com/Automattic/wp-calypso/assets/6737345/f9646750-4411-4560-a70e-5d2d44fd64c4)

### What actually happened

The video quality on WordPress.com is worse:

![olOhnY.png](https://github.com/Automattic/wp-calypso/assets/6737345/704455b6-c3d1-438e-a136-a1bd225b78b8)

The user's case:

![VW3Ydd.png](https://github.com/Automattic/wp-calypso/assets/6737345/60d9d2e4-a0cd-4ed3-8fe6-d561359bca9f)

User's video: https://varanmika3.files.wordpress.com/2023/12/sequence-01_3.mp4

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

I tried using Handbrake to compress it with the recommendations we have in the public [doc](https://wordpress.com/support/videopress/recommended-video-settings/) but this didn't help.

Issue reported initially in chat. Follow up ticket: 7423380-zd-a8c

**Comment by liviopv** [comment] 2023-12-20 11:49
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated, there's a clear loss of sharpness in the video https://liviopremium.wordpress.com/cover-block-video-quality/
- Tested on Atomic – Uncertain, it looked almost the same as uncompressed
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
Side-by-side comparison between a Local Site, Atomic site with Site Accelerator and VideoPress modules active, and a simple site:

https://drive.google.com/file/d/1-xPODxP-djK4KsXLUuSMnObevMu6vgeZ/view?usp=sharing (video too big for GH)

📌 ACTIONS
- Triaged

**Comment by mpkelly** [comment] 2024-04-22 09:07
Hi @Robertght, @liviopv, I have just compared the Pexels wave video side-by-side at pexels.com and on the self-hosted site above. I can't see a difference. 

I also uploaded my own and compared that. 

pfEE8U-c-p2

It seems like the issue might have been fixed. Can you try and reproduce it and consider closing it down if it works okay?

**Comment by taipeicoder** [comment] 2024-07-01 13:33
@Robertght @liviopv could you help and see if this issue is still reproducible? Thank you very much!

**Comment by Robertght** [comment] 2024-07-01 14:54
Apologies for the delayed reply here! From what I see, the quality is the same on both ends.

I'm leaving this open in case @liviopv wants to double-check it.

**Comment by liviopv** [comment] 2024-07-05 15:36
I just checked the example https://liviopremium.wordpress.com/cover-block-video-quality/ and it looks very sharp. Since there hasn't been any recent reports, I'm going to close it.

**Closed as completed by liviopv** 2024-07-05 15:36 UTC
Labels: Bug, [Pri] High, [Feature] VideoPress, Triaged, Needs triage, Customer report [LEGACY], [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks
