### ISSUE TITLE
Twitter block not embedding timeline on Simple and Atomic sites

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#59936] opened 2022-01-11 07:42 UTC
### Quick summary

A user reported that their Twitter widget (non-legacy) was not working. 

On both my test sites simple and atomic, I was not able to embed a timeline using the Twitter block.

My test embed URL was https://twitter.com/wordpressdotcom/

I tried both the widgets.php method and going through the customizer widgets section, both not working.

https://user-images.githubusercontent.com/83020905/148900631-8c5ebe24-6433-4575-8681-373c8c120aac.mov

### Steps to reproduce

1. Start in WordPress.com dashboard
2. Go to either widgets.php or through Customizer > Widgets
3. Add standard Twitter block
4. Paste in URL of a Twitter account (ex: https://twitter.com/wordpressdotcom/)
5. Click Embed.

### What you expected to happen

The timeline should embed with options.

### What actually happened

The widget turns into a paragraph block.

### Context

4676989-zen
I was able to reproduce the issue on test simple and atomic sites. I used two themes, Canard and Karuna, both of which have sidebars for widgets.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

I've tested with 2 themes so far, Canard and Karuna.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by jeherve** [comment] 2022-01-11 09:40
This appears to be a long-standing issue with Twitter embeds in WordPress. I'll close this issue as duplicate of this Core ticket:
https://core.trac.wordpress.org/ticket/54789

**Closed as completed by jeherve** 2022-01-11 09:40 UTC
Labels: Bug
