### ISSUE TITLE
Blaze campaign location not saved

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#97270] opened 2024-12-10 14:06 UTC
### Quick summary

When a campaign is created and set to target specific countries, the preference isn't saved.

### Steps to reproduce

1. Create a Blaze campaign. MAke sure to tet a specific country as target
2. Submit your campaign
3. Navigate to the campaign details and notice that your preferences were not saved.

### What you expected to happen

My preferences for the target should be saved.

![Image](https://github.com/user-attachments/assets/a6cf9c4c-e6c8-4403-8f92-c4c0ae68894b)

### What actually happened

The campaign is set to run everywhere:
![Image](https://github.com/user-attachments/assets/27d90910-e8f0-49fd-a34d-cd40b200e097)

Campaign link: https://dsp.tumblr.net/campaigns/124279/ads/210948

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by Robertght** [comment] 2024-12-10 17:53
📌 REPRODUCTION RESULTS
- Tested on WordPress.com - I could replicate this.

📌 FINDINGS/SCREENSHOTS/VIDEO
- This is what I'm seeing after selecting my country:

![rolCdr1IKdMgmugcHc2xLdyjQaI9RhvdQTFl8bdw.jpg](https://github.com/user-attachments/assets/c91fdc79-2e73-4744-ad1c-ed66a59fde42)

📌 ACTIONS
- Triaged

@timur987  is this something your team can look at?

**Comment by timur987** [comment] 2024-12-10 18:33
@Robertght, sure thing, the fix is here: https://github.tumblr.net/Tumblr/a8c-dsp/pull/2925.

The discussion is here: https://a8c.slack.com/archives/C03TY6J1A/p1733705335847239

**Comment by zyousafi** [comment] 2024-12-11 07:04
User report here: 9156047-zen

They're planning multiple campaigns so we should reach out to them once the issue is resolved

**Comment by Robertght** [comment] 2024-12-11 07:30
Thank you @timur987!

I can see the code was deployed so is it ok to consider this as fixed and close the issue?

**Comment by timur987** [comment] 2024-12-11 07:55
> I can see the code was deployed so is it ok to consider this as fixed and close the issue?

Confirm, it's okay to close the issue, therefore closing it 😁 .

**Closed as completed by timur987** 2024-12-11 07:55 UTC
Labels: Bug, [Pri] BLOCKER, Triaged, Customer report [LEGACY], [Product] WordPress.com, [Feature Group] User Interaction & Engagement, [Status] Escalated to Product Ambassadors
