### ISSUE TITLE
Navigation block: Links are displaying left-justified when alignment is set to "Space between items"

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#58327] opened 2021-11-21 14:28 UTC
### Quick summary

Links in the Navigation block are displaying left-justified when alignment is set to "Space between items".

### Steps to reproduce

1. Add a Navigation block to a page/post
2. Add a new menu and add links to the block
3. Set the width to full width and alignment to "space between items"

<img width="1472" alt="Markup 2021-11-21 at 14 24 46" src="https://user-images.githubusercontent.com/51966986/142765933-1938315c-1982-455e-92f6-f38199b69d1e.png">

### What you expected to happen

The items in the Navigation Block should be spaced equally across the entire horizontal space, as shown here:

<img width="1459" alt="Markup 2021-11-21 at 14 22 08" src="https://user-images.githubusercontent.com/51966986/142765799-afa165ec-5ee1-4f21-b668-2e0ca6d50bb4.png">
 

### What actually happened

The items in the Navigation Block are left-justified instead, as shown in the first example here: 
![Uploading Markup 2021-11-21 at 14.15.46.png…]()

### Context

Customer reported this in #4532536-zen

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Tested with Leven, Twenty Twenty One, and Zoologist

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by synora** [comment] 2021-11-22 17:04
Tagging @Automattic/flow-patrol-create for help in this issue 🙏

**Comment by Greatdane** [comment] 2022-10-20 07:16
Closing as I am unable to reproduce. May be fixed.

![7ZzLWS.png](https://user-images.githubusercontent.com/5075840/196881436-0f6b4fcb-7438-4e61-a781-ab246b2f1fab.png)

**Closed as completed by Greatdane** 2022-10-20 07:16 UTC
Labels: Bug, [Pri] Normal, Blocks, Triaged
