### ISSUE TITLE
Plugins: after updating last plugin, Drake won't show his squeaky head

### ISSUE THREAD

**Issue by isaackeyet** [Automattic/wp-calypso#3070] opened 2016-02-04 08:20 UTC
<img width="1074" alt="screen shot 2016-02-04 at 15 13 19" src="https://cloud.githubusercontent.com/assets/3073557/12809511/5aabaa0e-cb52-11e5-83ef-bd9ff7863235.png">
<img width="388" alt="screen shot 2016-02-04 at 15 13 46" src="https://cloud.githubusercontent.com/assets/3073557/12809514/617c6ada-cb52-11e5-8d6a-1415c631491d.png">

I can't reproduce currently as I don't have any pending plugin updates, but this is how I got the above:

* Got security alert about out-of-date plugin, went to Calypso to update (easiest).
* Clicked the refresh icon in the site toggle and it took me to the plugins page.
* Clicked Update All, it did its thing with the toast, but after completion Drake just wasn't having it. Maybe he had some bad seaweed today and is not feeling all too well -- I'll give him the benefit of the doubt for now.

The resource opened fine when I opened it in a new tab with the full URL. I don't think it's a http/https issue, probably just how the image is fetched (or not fetched) when the page is updated.

:v:

**Comment by klimeryk** [comment] 2016-02-10 02:34
Well, he _can_ be quite shy :dragon: But in this case, you might be right and it could be a case of bad seaweeds - have you tried [getting rid of them](https://en.support.wordpress.com/browser-issues/#force-refresh) and trying again?

**Comment by isaackeyet** [comment] 2016-02-11 08:19
I did not, I guess I shouldn't have to do that to make an image load though.

**Comment by klimeryk** [comment] 2016-02-11 10:34
You are absolutely right. But in ideal world every browser would implement the web standards in the same way, did not have bugs that changes its behaviour and we'd all be on fiber connections that never drop a single packet :grinning:
Please don't get me wrong - I'm not dismissing your issue. Especially since it's well written and documented (you have my sincere thanks for that :bow:). But given that the image loaded on your computer when you accessed it directly, hard refresh and/or clearing your browser cache seemed like the obvious first step. Believe me - I'm no fan of "have you tried turning it off and on again" solutions that hide the underlying problem, but this seems like a one-off issue. If you can reproduce it reliably (or even semi-reliably) then I'd love to investigate it further :)

**Comment by isaackeyet** [comment] 2016-02-11 10:49
I'll try to remember to load the tab the way I did here next time I have plugins to update.

**Comment by lancewillett** [comment] 2016-04-29 00:01
No reply with notes to repeat in last few months — closing for now. Feel free to re-open if it Drake continues not to rear his squeaky head as expected. :P

**Closed by lancewillett** 2016-04-29 00:01 UTC
Labels: Jetpack Plugins, OSS Citizen, [Type] Bug

**Comment by isaackeyet** [comment] 2016-04-29 11:31
Yeah every time I updated since this has not happened so I would say #wontfix
