### ISSUE TITLE
Framework: console errors when logged in as user without sites

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#6395] opened 2016-06-29 06:46 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Log in as a user that has no sites - a reader only user
3. Check console
#### What I expected

No console errors
#### What happened instead

Multiple console errors:

`Error: https://widgets.wp.com/notifications/build.min.js?6a0b66a8f2bf309ea22cb7a194121f6d 10:14250 Uncaught TypeError: Cannot read property 'type' of undefined
`
#### Browser / OS version

Chrome latest OSX 10.11.5
#### Screenshot / Video

![screen shot 2016-06-29 at 4 45 23 pm](https://cloud.githubusercontent.com/assets/128826/16442899/ea116c22-3e18-11e6-81c4-32cc2b4e3a68.png)
#### Context / Source

 #automated-testing

**Comment by iurii-kyrylenko** [comment] 2016-10-13 10:05
There is a corresponding closed issue #5191, related to the **external** `notifications` widget.

A simple way to reproduce it:

1. Login to the WordPress (to get authentication cookie)
2. Navigate to the widget page: http://widgets.wp.com/notificationsbeta/?language=en
3. Observe the error to appear each 30s.

@dmsnell, do you have any update?

**Comment by rachelmcr** [comment] 2017-08-28 16:39
I tested this again in Chrome 60, Mac OSX 10.12.6 and couldn't reproduce it. I tried the steps in the original report as well as checking http://widgets.wp.com/notifications/ and http://widgets.wp.com/notificationsbeta/ and in each case I didn't get any console errors. Closing this as resolved.

**Closed by rachelmcr** 2017-08-28 16:39 UTC
Labels: Framework, [Type] Bug
