### ISSUE TITLE
AMP Validation Error From Cover Block

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/wp-calypso#51829] opened 2021-04-09 21:42 UTC
### Steps to reproduce the behavior

1. On a simple site with any theme and AMP enabled...
2. Create a new post and add a cover block. Publish the post.
3. Try to validate the AMP version of the page here: https://validator.ampproject.org/
4. The cover block seems to have CSS but is missing `amp-custom` in the style tag, causing validation to fail with an error: `The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'`

![Simple Site AMP](https://user-images.githubusercontent.com/41035049/114243268-22297b80-9941-11eb-9291-cd6d11f63c34.png)

#### What I expected to happen

I believe cover block CSS style tag needs to be formatted as "<style amp-custom=", like this (screenshot form an AT site):

![Amp AT](https://user-images.githubusercontent.com/41035049/114242968-9dd6f880-9940-11eb-91c7-7b951926d660.png)

#### What actually happened

AMP validation fails. I had a user in #28500399-hc who reported " Google excluded 18 pages from the search results." 
#### Browser / OS version

Chrome

#### Is this specific to the applied theme? Which one?

Tested in Rowling and Blank Canvas, so likely all themes.

#### Does this happen on simple or atomic sites or both?

Simple. AT seems to work fine.

**Comment by jartes** [comment] 2021-04-10 15:03
Other reports on: 
- 3896815-zen
- 3896792-zen
- 28931748-hc

**Comment by jartes** [comment] 2021-04-10 15:06
Adding that this post (pcMHUt-45-p2) has the `<style>` tag in the AMP version and doesn't have a Cover block.

Just has in at the start of the HTML document: 

```
<!doctype html>
<html amp lang="es-ES">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1">
		<style>
		.wp-block-cover {
			background-color: var(--wp-admin-theme-color);
		}
	</style>
```

**Comment by kelasante** [comment] 2021-04-10 20:03
Another report in 3896986-zen

**Comment by fsalazarleon** [comment] 2021-04-11 03:07
Another report in 3897665-zen

**Comment by rinazrina** [comment] 2021-04-11 15:55
Other reports: 

- 3897481-zd-woothemes (this one has a screenshot of the AMP error in Google Search Console. See below.)
- 3896854-zd-woothemes
- 3899130-zd-woothemes
- 3896798-zd-woothemes
- 3898018-zd-woothemes
- 3898314-zd-woothemes
- 3896886-zd-woothemes
- 3898276-zd-woothemes
- 3898933-zd-woothemes
- 3896922-zd-woothemes
- 3899283-zd-woothemes
- 3897783-zd-woothemes
- 3896979-zd-woothemes
- 3899170-zd-woothemes
- 3897374-zd-woothemes
- 3896863-zd-woothemes
- 3897293-zd-woothemes
- 3899022-zd-woothemes
- 3898192-zd-woothemes
- 3897177-zd-woothemes
- 3898459-zd-woothemes
- 3896825-zd-woothemes
- 3897638-zd-woothemes
- 3899513-zd-woothemes
- 3899583-zd-woothemes
- 3897272-zd
- 3897299-zd-woothemes
- 3899040-zd-woothemes

<img width="1159" alt="Markup 2021-04-12 at 02 41 03" src="https://user-images.githubusercontent.com/33721365/114317038-c4f81a80-9b38-11eb-91e6-bab56e296047.png">

**Comment by BrandiBoyd** [comment] 2021-04-12 01:45
Another report at #3897242-zd
Not using the cover block

**Comment by jerrysarcastic** [comment] 2021-04-12 03:41
Also reported in the following public forums posts
- https://wordpress.com/forums/topic/google-search-console-reports-amp-issues-with-all-my-sites/
- https://wordpress.com/forums/topic/only-amp-boilerplate-and-amp-custom-style-tags-are-allowed-and-only-in-the-do/

**Comment by rinazrina** [comment] 2021-04-12 07:45
Same to @jartes report above -- many of the sites that I checked don't have Cover Block in their content. But have the style tag on the header. It's true on [my test page](https://freeena12345site.wordpress.com/2020/02/14/flora-fauna/amp/) too. 

<img width="735" alt="Screenshot on 2021-04-12 at 15-28-14" src="https://user-images.githubusercontent.com/33721365/114358403-76cd3080-9ba5-11eb-8c51-e5f11b40fa94.png">

**Comment by Sandkorner** [comment] 2021-04-12 08:32
Another:
3897880-zen

**Comment by aleone89** [comment] 2021-04-12 10:47
This has been reported here: https://wordpress.com/forums/topic/recd-google-message-only-amp-boilerplate-tags-allowed/

**Comment by mrsjaved** [comment] 2021-04-12 11:20
Another report 3899837-zd-woothemes

**Comment by aleone89** [comment] 2021-04-12 12:57
Just as an additional note with https://wordpress.com/forums/topic/recd-google-message-only-amp-boilerplate-tags-allowed/ > the sites mentioned do not use a cover block, similar to @jartes and @rinazrina

**Comment by susanjanec** [comment] 2021-04-12 14:24
Another report - 28864413-hc

**Comment by AtrumGeost** [comment] 2021-04-12 15:11
Got another report here: 14867849-hc

**Comment by csonnek** [comment] 2021-04-12 15:48
Another report in https://wordpress.com/forums/topic/error-on-two-blog-pages/ (site does use cover block).

**Comment by metabreakr** [comment] 2021-04-12 17:45
28971558-hc / 3902214-zen

The user shared 3 posts, none of which used the cover block.

**Comment by csonnek** [comment] 2021-04-12 18:23
Also reported in https://wordpress.com/forums/topic/style-amp-boilerplate-error/

**Comment by kriskarkoski** [comment] 2021-04-12 18:41
3897449-zen

**Comment by kwight** [comment] 2021-04-12 19:15
I think the problem is that the style is being added in the first place, not that it's missing the attribute. For instance, [this post](https://aurorakreativ.wordpress.com/2020/08/21/featured-coloring-pages-2-august-2020/amp/) doesn't seem have any Cover blocks in it, but has the style (like many others mentioned in this thread). It might be a `wp_add_inline_style` call happening that shouldn't be in the AMP context.

**Comment by obenland** [comment] 2021-04-12 21:45
Introduced in D59723-code. @claudiucelfilip @danielwrobert Could you please have a look?

**Comment by macmanx2** [comment] 2021-04-12 21:49
also reported at https://wordpress.com/forums/topic/style-amp-boilerplate-error-2/

**Comment by kwight** [comment] 2021-04-12 22:17
I've revert D59723-code, closing as fixed. @claudiucelfilip @danielwrobert when redoing, I think it'll need the missing attribute, plus a check to only output if the block is present would be good.

**Closed as completed by kwight** 2021-04-12 22:17 UTC
Labels: Bug, [Pri] High, AMP

**Comment by claudiucelfilip** [comment] 2021-04-13 09:22
Thank you for addressing this and sorry for missing this.

The `style` tag is supposed to be caught by the AMP_Style_Sanitizer and included into the single `style amp-custom` tag. This, however, doesn't seem to be happening on WP AMP 1.4.2.
Another fix has been created which is restricted to WP AMP 2.0.5 (or newer) posts with the Cover block present (ty @kwight): D60085-code

**Comment by daria2303** [comment] 2021-04-20 09:56
3913675-zd-woothemes

Asking if this is still happening.
