### ISSUE TITLE
When WooCommerce is Active, Scheduled Posts' Publish Times are Displayed Incorrectly

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#72746] opened 2023-01-29 03:33 UTC
### Quick summary

When the WooCommerce plugin is active, there is a discrepancy in the displayed publish time of a scheduled post. The editor displays an offset between the selected publish time and the displayed publish time equal to the offset between the site time zone and the UTC time zone.

<img width="372" alt="Screenshot 2023-01-28 at 10 30 04 PM" src="https://user-images.githubusercontent.com/12906034/215303209-78e2fb23-9749-4d68-9b10-629e6e308856.png">

### Steps to reproduce

1. Create a site and set the time zone to any time zone other than UTC.
2. Install and activate the WooCommerce plugin.
3. Create a new post. Set a scheduled publish time.

### What you expected to happen

The displayed publish time should match the scheduled publish time.

### What actually happened

The displayed publish time is offset equal to the offset between the site time zone and the UTC time zone.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Customer report: 5900931-zen

**Comment by kavyagokul** [comment] 2023-02-14 13:35
📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/71529

**Closed as completed by kavyagokul** 2023-02-14 13:35 UTC
Labels: Bug, [Pri] High, [Platform] Atomic
