### ISSUE TITLE
Theme Showcase: Theme switch UI can sometimes show an "only users who can switch themes on this blog can preview them" error.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#61184] opened 2022-02-16 22:24 UTC
Theme switch UI can sometimes show a only users who can switch themes on this blog can preview them error:

![image](https://user-images.githubusercontent.com/545779/154367361-aea4c6e8-2ffb-429f-8bd4-ef5e1a1e4e7f.png)

**Comment by sixhours** [comment] 2022-02-22 21:43
I haven't been able to reproduce this, but I started looking into it.

This error comes from `wp-theme-preview.php` when `current_user_can_preview_theme` returns `false`. This is a filter applied to `current_user_can( 'switch_themes' )`.

The only place we use this filter is in the `site-preview.php` bin script, where we return `true` at the default priority -- IIRC this is done so we can preview sites outside the Customizer (as in the case of the Theme Showcase modal).

I wonder if occasionally something gets run in a different order, and the filter on `current_user_can( 'switch_themes' )` doesn't get applied in time, or is overwritten by another filter later on down the line. Will check.

**Comment by sixhours** [comment] 2022-02-22 22:04
We apply another filter on `current_user_can( 'switch_themes' )` for Theme Butler, and that filter `show_theme_butler` occasionally returns `false` (example: in the Theme Preview plugin, it has a priority of 99, which I believe means it would run later than `current_user_can_preview_theme`). Maybe it's overriding the `current_user_can_preview_theme` filter.

This makes me think there may be a conflict with Theme Butler (which would only be an issue for Automatticians). 🤔 But I'm not able to reproduce the issue with Theme Butler enabled or disabled, so maybe not.

**Comment by nelsonec87** [comment] 2022-03-01 18:06
The only way I found to [partially] reproduce the problem was to directly access the preview URL using a site I'm not a user:

![image](https://user-images.githubusercontent.com/3801502/156223566-184c7c55-5434-4d24-aee2-1c239f57f2b3.png)

But calypso doesn't let access the theme page for this site: `https://wordpress.com/theme/twentytwentytwo/<site>.wordpress.com`. I get redirected to the "pick a site" page.

**Comment by nelsonec87** [comment] 2022-03-07 23:20
@sixhours Any new ideas on how to try reproducing this? :)

**Comment by sixhours** [comment] 2022-03-08 17:19
@nelsonec87 Nope, I would probably close this as "Not reproducible" unless @ianstewart has other ideas! We can always reopen it if we get more information down the line. :)

**Closed as completed** 2022-03-14 16:12 UTC
Labels: Bug, [Pri] Normal, [Size] S, [Feature] Theme Showcase
