### ISSUE TITLE
AT Site Unable to Transfer Domain to Another WordPress.com Site. 

### ISSUE THREAD

**Issue by socalthrills** [Automattic/wp-calypso#18283] opened 2017-09-26 19:13 UTC
Customer is trying to transfer one of his Domains to another WP.com site and not getting the option to do that.

Here is the ticket number: 704252-zd-woothemes

All the customer see's is: Transfer to another Registrar.

This is visible from: https://wordpress.com/domains/manage/:site/transfer/:domain

Any ideas/ suggestions would be appreciated. Also if this can be done at all.

**Comment by iamgabrielma** [comment] 2017-09-28 08:04
What you see here is expected, as the site is atomic and having a custom domain is one of the requirements that need to be in place in order to trigger the AT process, otherwise the site cannot go through AT.

There's a process in place to make the change manually by an HE, this involves switching the primary domain and transferring the "old" domain to a new site, please check FG for more info on how to do this :)

**Comment by klimeryk** [comment] 2017-09-28 08:17
The thing is, I'm not sure being a primary domain on the WPCOM side is the same as being a primary domain at Pressable. And I've seen those go out of sync.
Looping in @lamosty, the Watcher for AT this week.

**Comment by KokkieH** [comment] 2017-10-24 06:32
Just to note the option to transfer domain ownership, i.e. to another admin on the site, also doesn't exist here. So if the site owner wishes to transfer ownership of the site to someone else, there's no way to transfer the domain.

**Comment by klimeryk** [comment] 2017-10-24 17:17
_That_ case should be fine - though, I'd love for someone familiar with AT development to chime in on this issue 😓

**Comment by klimeryk** [comment] 2017-10-25 16:57
Could someone from @Automattic/stark chime in here or point to the team responsible for this functionality?

**Comment by jhnstn** [comment] 2017-10-25 19:39
We've run into Automated Transfer issues when the plan or the domain is owned by someone other than the site owner.  The domain issues should be limited to the primary domain. Transferring ownership of a non-primary domain should be fine.

**Comment by donpark** [comment] 2017-10-25 19:53
Hi there.

> I'm not sure being a primary domain on the WPCOM side is the same as being a primary domain at Pressable. And I've seen those go out of sync.

There is only one Primary Domain from user's perspective. From developer perspective, primary domain is the DNS A Record on Wordpress Name Server. There is also only one host, at Pressable. Complication starts with having two endpoints: Pressable and WPCOM Proxy to Pressable.

* When an Atomic site is created, DNS A Record points to WPCOM because it takes time for a) DNS records to propagate and b) SSL cert on Pressable side to be issued.
* After some reasonable delay (7 days currently), DNS A record is changed to point to Pressable.
* There are one or more places where DNS A record is reverted back to WPCOM under certain conditions. This may be what's been described as *going out of sync* problem. Tracking that down is on my TODO list.

Does this help? Missing features will eventually be re-enabled when issues and missing pieces we didn't get to initially are resolved and built.

**Comment by lamosty** [comment] 2017-10-26 03:15
> I'm not sure being a primary domain on the WPCOM side is the same as being a primary domain at Pressable. 

Yes, that's true. A domain needs to be primary on both Pressable and WP.com. Pressable handles the redirects while WP.com handles the showing of primary domain in Calypso and our systems.

The AT MC tool `change_primary_domain` does both.

> When an Atomic site is created, DNS A Record points to WPCOM because it takes time for a) DNS records to propagate and b) SSL cert on Pressable side to be issued.
> After some reasonable delay (7 days currently), DNS A record is changed to point to Pressable.

We run a cron job each hour on WP.com which tries to point all new transferred sites' domains to Pressable. However, it won't point the domain until Pressable doesn't have ssl cert for it. We keep proxying the domain for 7 days after creation – either new transfer or calling `change_primary_domain` AT MC tool. So ideally, it's pointed in the first hour since Pressable is usually pretty fast with getting the ssl cert. 7 days of proxying is just a "fallback" for the domain's A record change to propagate throughout the world.

**Comment by klimeryk** [comment] 2017-11-01 08:59
> From developer perspective, primary domain is the DNS A Record on Wordpress Name Server.

Unless I'm missing something, this is not true from WordPress.com perspective - the primary domain is the one that has the `primary_blog` set to `1` in `domain_mapping` table. We can have multiple domains pointing to the same site (and, of course, IPs, because all simple WPCOM sites share the same pair of IPs), but through the `domain_mapping` table we figure out which one is the primary one (in other words, to which domain all other domains for the given site should redirect to).

What I'm getting from the above comments is that there's no reliable way from WordPress.com side to figure out which domain is primary in both senses? (WordPress.com's and Pressable's) If there _is_, then we would be able to fix this issue, at least for non-primary domains.

**Comment by lamosty** [comment] 2017-11-01 12:42
> What I'm getting from the above comments is that there's no reliable way from WordPress.com side to figure out which domain is primary in both senses? (WordPress.com's and Pressable's) If there is, then we would be able to fix this issue, at least for non-primary domains.

Pressable has an API to check for this. We wrote some wrapper around it in `Transfers\ping_pressable` fn.

**Comment by molszewska** [comment] 2017-12-04 14:13
Not sure if that's the right place,  but I noticed that the option to transfer the domain to another registrar is visible on Atomic sites, while it seems it shouldn't be possible.

Screenshot from my site: http://cld.wthms.co/79ldzn
domain: magdatestdomain.com

**Comment by klimeryk** [comment] 2017-12-04 14:57
I'd say that's expected and a good thing - if we prevented that we'd be in violation of ICANN rules. Though, how it's handled with regards to the AT site is a different matter 😁

**Comment by blazevivan** [comment] 2019-05-10 11:38
Hi all! 

As I encountered this issue again I wanted to refresh this thread in case we can find another workaround/solution for this. Having in mind that V2 is in production, this might have different flow now. Thanks to Herman for the reminder!

**Comment by klimeryk** [comment] 2021-02-02 13:53
Marking this as fixed - confirmed that all the usual transfer options are available now for Atomic sites:

<img width="755" alt="Screenshot 2021-02-02 at 13 52 57" src="https://user-images.githubusercontent.com/3392497/106609930-0af39980-655e-11eb-979f-208afb32d105.png">

**Comment by jartes** [comment] 2022-01-20 08:41
Re-opening as this option is not available again on Atomic sites  with the new domains pages redesign: 

![Markup on 2022-01-20 at 09:39:06](https://user-images.githubusercontent.com/1046943/150303056-b02dafcf-ebb5-4fd4-b6ff-e17fd3a74d00.png)

Reported by a user here: 33654263-hc

cc @klimeryk

**Comment by klimeryk** [comment] 2022-01-21 14:34
@jartes, please don't re-open old issues, but start new one. The context is different, it's not useful to re-open a year-old issue. It makes it harder to follow the conversation, what's been done, etc.
A new issue, with a link to this one (kudos on searching and finding it!) will be a great, fresh starting point. Some teams (I know the Domains team does) have alerts for _new_ issues with the relevant labels. So they'll get an alert for a new issue with Domains label. But they will _not_ get an alert of an issue being re-opened. I got an alert because I was on the team at the time, but I no longer am. So your report could go unnoticed.

**Closed by klimeryk** 2022-01-21 14:34 UTC
Labels: [Type] Bug, Domains, OSS Citizen, Atomic

**Comment by jartes** [comment] 2022-01-26 17:24
@igotdes thank you so much for the heads-up and the complete explanation 😄 

And yes, it totally makes sense to open a new issue and mention this one.
