### ISSUE TITLE
Site Selector should allow you to arrow down from the search box

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#2075] opened 2016-01-04 15:44 UTC
When I start filtering my sites by searching I should be able to use up and down arrows and the enter key to select a different site. Breaks the user flow to have to use the mouse once you are typing.

(this is probably true of every search box: posts, pages, ...)

**Comment by lancewillett** [comment] 2016-01-04 17:25
Could you add basic details about your environment, just in case it's applicable? Browser and OS version.

**Comment by gibrown** [comment] 2016-01-04 19:30
This is probably more of a feature request than a bug IMO, I don't think it is a feature that exists anywhere outside of the notifications menu.

I was trying to do this in the OS X app, but have also tried in Chrome.

Also, I think the 'esc' key should cancel the search and take me back to where I was.

**Comment by mtias** [comment] 2016-01-08 17:03
Duplicate of #8.

**Closed by mtias** 2016-01-08 17:03 UTC
Labels: Site Picker, [Type] Bug
