### ISSUE TITLE
Upgrades: Purchasing Just a Domain Flow doesn't let you complete the purchase

### ISSUE THREAD

**Issue by rezzap** [Automattic/wp-calypso#51447] opened 2021-03-26 13:05 UTC
### Steps to reproduce the behavior

1. Go to My Sites > Upgrades > Domains
2. Click on Manage All Your Domains and 'Add a domain'
3. Type in your desired domain and select.
4. Click on 'Just buy a domain' You'll see a screen here about your site is getting ready.
5. You'll then be brought to 'Select a Site to Open Checkout'
6. Select a site and see 'You have no items in your cart'
7. Click on browser our plans and you'll end up back to calypso's plans page for the site. 

#### What I expected to happen

I'd expect to be able to finish purchasing the domain only and manage it from the https://wordpress.com/domains/manage page.

#### What actually happened

I can't complete the purchase of the domain unless I attach it to an existing site and follow the add a new domain from the site's domain page.

### Context

Reported in chat here: 28633270-hc

#### Browser / OS version

Chrome Version 89.0.4389.90 (Official Build) (x86_64) (incognito) Could not reproduce on an account without nav unification enabled. 
macOS Cataline 10.15.7

#### Is this specific to the applied theme? Which one?

No

#### Does this happen on simple or atomic sites or both?

Both

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Blocks purchases

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Consistent on an account with nav unification enabled. Though I've gotten stuck on a blank page at 'Select-domain' a few times also. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Can provide full screen-recording of the broken flow privately as it includes details of my account. 

https://user-images.githubusercontent.com/10325627/112637457-16fd2880-8e36-11eb-9e50-778d37292e1b.mp4

**Comment by klimeryk** [comment] 2021-03-26 14:12
I can't reproduce this - neither with my test (no nav unification) or a8c (nav unification) accounts. I've also tried on the user's account (nav unification enabled) but was not able to reproduce either 🤔 Maybe the bug that was causing this was fixed by someone in the meantime? Can you still reproduce?

**Comment by rezzap** [comment] 2021-03-27 07:22
@klimeryk  I'm still replicating the same issue on my end. It's only when using the 'add a domain' button from https://wordpress.com/domains/manage though. It doesn't seem to matter which site I select from the list though to get there.

**Comment by cpapazoglou** [comment] 2021-03-30 08:55
Removed nav unification label as it could be initially reproduced **on an account without nav unification enabled**.

**Comment by rezzap** [comment] 2021-04-01 07:23
@cpapazoglou Apologies, that was supposed to read consistently on an account **with** nav unification enabled. I have not been able to reproduce this on an account using the old flow where nav unification is disabled. 

I'll re-add that tag for now.

**Comment by cpapazoglou** [comment] 2021-04-01 08:36
Thanks @rezzap for following up on this! I just tested with nav-unification disabled (both in Calypos and WPCOM) and I also get the same problem

Starting the flow from `/domains/manage` end up in `/checkout/no-site?signup=1` where selecting any site will result to **You have no items in your cart**


https://user-images.githubusercontent.com/12430020/113266071-7dbe8e00-92dd-11eb-9d66-fc1b69421227.mp4

**Comment by hambai** [comment] 2021-04-01 11:17
Okay I have a PR that fixes the issue ready for review

**Closed as completed** 2021-04-05 11:49 UTC
Labels: Bug, [Feature Group] Emails & Domains, [Feature] Purchase Management
