### ISSUE TITLE
Gutenframe: TypeError when loading classic block

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#31417] opened 2019-03-12 22:11 UTC
#### Steps to reproduce
1. Starting at URL: http://wordpress.com/block-editor/page/:site/:post_id
2. Insert a Classic block with some text
3. Save the draft.
4. Reload the page.

#### What I expected
No error

#### What happened instead
Receive the following error:
> Uncaught TypeError: Cannot read property 'activeElement' of undefined

**Comment by mmtr** [comment] 2019-03-21 05:30
I'm not able to reproduce this. @obenland do you have any additional step I might be missing?

![Mar-21-2019 14-28-07](https://user-images.githubusercontent.com/1233880/54734805-9facb280-4be5-11e9-8ab8-445dbecc80ba.gif)

I checked in both `/block-editor/page` and `/block-editor/post` URLs.

**Comment by obenland** [comment] 2019-03-21 15:14
Hm, I wonder if you might need to try multiple times? This is what I get: https://cloudup.com/clSgWzcq9vB

**Comment by mmtr** [comment] 2019-03-22 00:24
Thanks for the video. I was expecting an error on the UI, not on the console. Anyway, I still don't have luck trying to reproduce it. Do you see the error on all your sites? Does it appear on `wp-admin` as well?

**Comment by mmtr** [comment] 2019-03-22 04:14
Uhm, interesting. I just was able to reproduce it but only on my sandbox site. Will try to investigate further and see if I can detect the root cause.

**Comment by mmtr** [comment] 2019-03-22 05:10
Opened a diff fixing this issue: D25894-code

**Comment by mmtr** [comment] 2019-03-23 00:09
Closed by D25894-code

**Closed by mmtr** 2019-03-23 00:09 UTC
Labels: Jetpack, [Goal] Gutenberg, [Type] Bug
