### ISSUE TITLE
Free plans do not enforce 1 GB storage limit, allow 3 GB, and usage displays incorrectly

### ISSUE THREAD

**Issue by mgozdisk** [Automattic/wp-calypso#78332] opened 2023-06-16 14:02 UTC
### Quick summary

Still a bit of a noob here and understand this may have been a marketing decision with plan changes in the past with Free plan storage limits changing from 3 GB to 500 MB to 1 GB. The limit and stats displayed on a Free plan appear to only be a "display limit" and not an "enforced limit". 

On a brand new Free plan, 1 GB of storage is displayed in the Media Library, however, users can actually upload 3 GB of storage while the usage continues to remain at 100% of 1 GB. Users will only receive a notice that they've reached the plan's storage limit once hitting 3 GB. 

Since the usage displays incorrectly, the problem is that users who have reached the limit believe they've only used 1 GB of storage, when they've actually used 3 GB. When they upgrade their plan to Personal, they'll suddenly see the correct usage and 50% of their new plan already used. This creates a bad user experience as seen in this ticket: 6396268-zd-woothemes

I am unsure if this also affects legacy Free plans that may have a 500 MB "display limit". 

### Steps to reproduce

1. Create a new Free site.
2. Add 1 GB of media to the Media Library until it displays 100% used.
3. Continue to add media until getting messaging that you've reached the plan's limit (can upload additional 2 GB of media).
4. See that the usage remains at 100% of 1 GB while actually consuming 3 GB (this can be verified in File Tools).
5. Upgrade to Personal and see the correct usage displayed if you like, but this step is not necessary.

For testing, a large image like [this](https://cdn.spacetelescope.org/archives/images/large/heic0506a.jpg) can be used and then have a macro keep adding it to the Media Library by URL. Alternatively, use some other large test data to hit the limit quickly. 

### What you expected to happen

The Free plan's marketed storage limit (1 GB) should be enforced or we should market it as having the enforced limit (3 GB) and display the correct usage. 

### What actually happened

The Free plan allows users to consume more than the marketed storage limit, while displaying incorrect usage, causing shock when upgrading and then seeing the correct usage. A false lower "display limit" to try and entice users to upgrade feels like blackhat marketing. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment] 2023-06-16 21:15
📌 SCRUBBING : RESULT
- Have not tested yet due to the process for reproing - in process

📌 ACTIONS
- Pinging to @Automattic/martech for their insight
- Awaiting reply

📌 Message to devs
- Hey folks! As I work on repro-testing this, can you confirm whether we _should be_ enforcing the 1GB storage limit?
- As far as I could dig up, we dropped from 3GB down to 500MB during the Plan overhaul, then upped 500MB to 1GB after some feedback, but the only PR I could find on that (https://github.com/Automattic/wp-calypso/pull/62513) was about the way we display that on our pricing pages, not the actual cap.

**Comment by cuemarie** [comment] 2023-06-23 01:10
Asked here: p1687482635403199-slack-CFFF01Q4V

**Comment by cuemarie** [comment] 2023-06-28 01:12
📌 ACTIONS
- Closing as by design

📌 Message to Author
- @mgozdisk it looks like this is indeed by design - please see reasoning over here: p1687528954420429/1687482635.403199-slack-CFFF01Q4V
- I think the user experience you brought up is definitely worth sharing though! I'd recommend sharing this feedback internally, perhaps in that same slack thread or in the main channel there.

**Closed as not planned by cuemarie** 2023-06-28 01:12 UTC
Labels: Bug, [Pri] Normal, [Plan] Free, [Platform] Simple
