### ISSUE TITLE
Signup: "Back" layout spacing issue

### ISSUE THREAD

**Issue by jenial** [Automattic/wp-calypso#3431] opened 2016-02-20 13:28 UTC
## URL:
https://wordpress.com/start/domains/

## Issue description
During signup, step 2 "Let's find a domain" has a minor layout issue, in mobile, for some locales: the "<" and "BACK" are on separate lines for FR and DE (the design is EN-centric, so in English "< BACK" is on a single line).

Suggestion to fix: change layout to allow more space for "< BACK" translations.

### Screenshots
_English_
![en_mobile_2b_domain_map_existing_screenshot1453776781724](https://cloud.githubusercontent.com/assets/7637835/13196929/85bb6c02-d7e6-11e5-85cf-4dca3cf236a5.png)

_German_
![de_mobile_2b_domain_map_existing_screenshot1453773428337](https://cloud.githubusercontent.com/assets/7637835/13196882/0edb4bbc-d7e5-11e5-97da-4e4fc78c245f.png)

_French_
![fr_mobile_2b_domain_map_existing_screenshot1453774055235](https://cloud.githubusercontent.com/assets/7637835/13196885/1ceb2b8c-d7e5-11e5-87f6-f9be25bc3b94.png)

**Comment by fabianapsimoes** [comment] 2016-02-22 15:34
Duplicate of #143 .

**Closed by fabianapsimoes** 2016-02-22 15:34 UTC
Labels: i18n, Signup, [Type] Bug

**Comment by adambbecker** [comment] 2016-02-22 16:27
@jenial: Thanks for the report. Do you happen to know which browser these screenshots are from?
