### ISSUE TITLE
Notifications: Post Likes Aren't Being Sent

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#55335] opened 2021-08-10 20:28 UTC
### Steps to Reproduce

1. Publish a new post on a Public site.
2. Access the post on another browser, with a different WordPress.com account.
3. Leave a like on the post. 

### What I expected to happen

As the post's author, I would expect to get notifications for the like, as set on my account, by email and on the notification area for example.

### What actually happened

Nothing happened. It shows the likes on the Stats page, and the list of posts, by the post, but no notification is sent to the user.

### Context

Reported here: 4204718-zd-woothemes

### Operating System

macOS

### Browser

Chrome/Chromium, Firefox

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Other information

Was able to replicate this on a Premium test site, I don't get any notification about post likes, by email or the notification area, even though I have set to receive them on my [account's notification settings](https://wordpress.com/me/notifications), and [the site's discussion settings](https://wordpress.com/settings/discussion).

EDIT: it took a while, but I did get an email about the post like, but no notification. I also left a like on the user's site, but didn't show any email for that on Logstash. From the user's account, you can also see that there's no recent post likes notifications.

**Comment by inaikem** [comment] 2021-08-11 07:53
@alshakero, is this something you'll be able to take a look at? Happy to drop it into your board 👍

**Comment by carinapilar** [comment] 2021-08-11 11:09
It's interesting that I see post likes on the notification area from our P2s.

**Comment by KirkwallDay** [comment] 2021-08-18 21:16
This is triaged so closing 4204718-Zen for now, they will need a new follow-up ticket to notify them once this is resolved.

**Comment by thekingsprojects** [comment] 2022-03-11 05:05
Have what might be another case of this here: 4846225-zen

Atomic. The user has email notifications for likes turned off, but for some reason some of their recent posts are not showing like notifications in the notifications list. The likes do appear on the Stats page, and there is a comment notification in the notification list, but no likes.

I did try testing this on my own site briefly, but was unable to replicate; I did see a notification for the like I added from another account. (Although I think it didn't show the little badge to let me know there was something there?)

**Comment by wynwin** [comment] 2022-08-19 15:32
Another example 5488196-zen

**Comment by hacchism** [comment] 2022-08-26 23:38
Another case reported.
Chat: 27240496-hc
Follow-up ticket: 5502462-zen

**Comment by nellofn** [comment] 2022-09-30 14:53
Just recording a user who is still asking for this issue in 5595541-zen. Is this being looked at?

**Comment by ccwalburn** [comment] 2022-10-24 15:57
Another report here: 5644131-zen

**Comment by inaikem** [comment] 2022-11-04 02:08
5595541-zen is back and hoping for an update. @cometgrrl / @yansern do either of you have a sense of when we might be able to look into this a little deeper?

**Comment by cometgrrl** [comment] 2022-11-04 20:01
@ebinnion Is there someone who can look into this? If it would be useful, I can ask my team to see if we can reproduce it.

**Comment by nelsonec87** [comment] 2023-01-03 19:15
@carinapilar , the notifications are working for me (after I enabled them 😄)

Can you still reproduce it?

![image](https://user-images.githubusercontent.com/3801502/210425101-bcbee53d-c367-442b-87c7-4507cbd8292b.png)

**Comment by nelsonec87** [comment] 2023-01-03 20:28
I've tested with Free, Premium, and Atomic sites. I got the e-mail every time, but the notifications don't appear under Bell -> Likes

![image](https://user-images.githubusercontent.com/3801502/210436143-bd909d07-261b-4daf-9f7e-482f045a2828.png)

**Comment by nelsonec87** [comment] 2023-01-04 19:32
Update: the notifications appear when I test sandboxed 🤦‍♂️

![image](https://user-images.githubusercontent.com/3801502/210634630-1ad4fea5-64f6-46b4-a451-712c326e33cb.png)

**Comment by carinapilar** [comment] 2023-01-05 20:03
Hey @nelsonec87! From what I can see on my account, this seems to be working now, I have been seeing notifications for post likes recently. Maybe there's something else happening in the most recent reports?

**Comment by worldomonation** [comment] 2023-01-23 21:55
I tried reproducing this issue today (2023/01/23) on test sites associated with my work WordPress.com account, blog ID 185845003.

I wrote a new post, opened the post as another user (not associated with my main WordPress.com account in any way) and liked the post.

![image](https://user-images.githubusercontent.com/6549265/214158690-ac0ebe77-9613-411e-b955-ade1984f129f.png)

Made two posts this way, but I am yet to received notifications for both "likes".

**Comment by ebinnion** [comment] 2023-02-06 23:56
I dug into this a bit today and what I found is interesting. There is a condition just before the notification callback that will not send a notification if the liker does not have a gravatar. Note how the liker in Edwin's screenshot has a fallback avatar but the one in Nelson's screenshot has a photo of a person?

This is around notes-hooks.php of the Dotcom codebase, around like 542. 

I haven't dug too deeply, but my gut is that this is to minimize the like button getting spammed. We could consider relaxing this restriction perhaps.

**Comment by cometgrrl** [comment] 2023-02-07 00:57
Wouldn't any spamming already be limited by needing a WordPress.com account?  Also, using the presence of a gravatar as the limiting factor for notification feels broken. This generates a fair number of customer tickets, so it seems worth fixing.

**Comment by ebinnion** [comment] 2023-02-07 23:55
The case that I pointed out above for this issue has been addressed in D100651-code.

**Comment by candy02058912** [comment] 2023-03-02 10:28
Tested on: Simple, Atomic
Tried with Liker that had a Gravatar, and one that didn't

Results:
Email notification: NO
Bell notification: NO

Investigation:
`Likes::is_post_likeable` is `false` (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sabgrf%2Sabgrf%2Qubbxf.cuc%3Se%3Q5326s3or%23529-og), therefore `! Likes::is_post_likeable` ends the code early and doesn't send out any notification.

A deeper dive into `is_post_likeable`, when I create a new site, the value of `get_post_meta( 3, 'switch_like_status', true );`(fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Syvxrf%2Syvxrf.cuc%3Se%3Q8s69o719%23116-og) is 
```
Array
(
    [0] =>
)
```
which when coerced into a boolean, is always going to be `true`. This results in fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Syvxrf%2Syvxrf.cuc%3Se%3Q8s69o719%23119%2Q121-og going into the if statement and sets `$post_likes_enabled` to be `false`.

When I set `is_post_likeable` to be true manually(hard coded), I received both email and bell notifications.

Next steps:
* Why is`switch_like_status` an array on a new site, is it supposed to be that way?
* From the two reports above ([#](https://github.com/Automattic/wp-calypso/issues/55335#issuecomment-1372674441), [#](https://github.com/Automattic/wp-calypso/issues/55335#issuecomment-1371335215)), it seems like that the notifications worked? @nelsonec87, @carinapilar it would be helpful if you could share the process of how it was tested 🙏

**Comment by candy02058912** [comment] 2023-03-02 10:47
@worldomonation According to https://github.com/Automattic/wp-calypso/issues/55335#issuecomment-1401047927, did you by any chance received the email notifications? Or were it aligned with what I [got](https://github.com/Automattic/wp-calypso/issues/55335#issuecomment-1451641333)? No bell, no email notifications.

**Comment by carinapilar** [comment] 2023-03-03 11:27
@candy02058912, I tested this again today, following the steps outlined in my first message, and it worked for me. I created a new post, left a like using another WordPress.com account, and I received the notification by email and in the notification area, as I have set up on my account's notification settings. 🙂

**Comment by candy02058912** [comment] 2023-03-07 08:04
Thanks @carinapilar for retesting this.

I also retested it today and when I was doing `get_post_meta( post_id, 'switch_like_status', true );` in wpsh for the new posts I made today, it was false, hence `$post_likes_enabled` mentioned [here](https://github.com/Automattic/wp-calypso/issues/55335#issuecomment-1451641333) became true.

I tested it for a couple more times and played around with the like button settings:
* In Marketing -> Sharing buttons
![like buttons in marketing](https://user-images.githubusercontent.com/6586048/223360993-1b642da1-0b64-42ca-ba31-9e3e9e9c3d0e.png)

* In the individual post (Jetpack menu)
![jetpack menu](https://user-images.githubusercontent.com/6586048/223361048-15806ef2-e5d7-44ae-9534-3d4cab4a4335.png)

I couldn't reproduce the issue anymore.

**Comment by lupus2k** [comment] 2023-03-08 00:05
I tested on Simple and Atomic sites. I can't reproduce the bug when creating a new post, I always receive the bell notifications. 
On the other hand, the `Hello World!` default post likes don't send me any notification. 🤔

**Comment by candy02058912** [comment] 2023-03-08 10:44
I’ve confirmed for the default post, the get_post_meta( default_post_id, 'switch_like_status', true ); has a value
```
Array
(
    [0] =>
)
```
which new posts won’t have.
But I’m not sure where this is coming from.

In this case, this bug becomes much more minor since it only happens on the default post.

**Comment by ebinnion** [comment] 2023-03-08 14:41
If the issue is only on the default post, then I suggest we close the issue.

**Comment by lupus2k** [comment] 2023-03-08 14:51
Created a [follow-up](https://github.com/Automattic/wp-calypso/issues/74213) and closed the issue in favor it

**Closed as completed by lupus2k** 2023-03-08 14:51 UTC
Labels: Bug, [Pri] High, [Feature] Notifications, Triaged
