### ISSUE TITLE
Subscription Management: Rename "Follow" labels to "Subscriptions" equivalent (behind feature flag).

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#78373] opened 2023-06-19 09:56 UTC
Rename follow labels to subscriptions equivalent.

These are the first 4 labels, we will seek out more as we discover.

![2023-06-14_17-26-49](https://github.com/Automattic/wp-calypso/assets/1287077/d4e71c44-234d-48f6-bc84-87fcffd597b8)

**Comment by yansern** [comment] 2023-06-19 09:58
Duplicate of https://github.com/Automattic/wp-calypso/issues/78374. Maybe I pressed twice too quickly.

**Comment by yansern** [comment] 2023-06-27 10:30
Reopening as there's one more phab patch needed.

**Comment by mashikag** [comment] 2023-06-28 07:24
The issue is also addressed in: D114790-code

**Closed as completed** 2023-06-28 09:42 UTC
Labels: Subscription Management, [SM] Reader Portal
