### ISSUE TITLE
Images with descriptions output HTML as well as image

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#44897] opened 2020-08-13 03:28 UTC
#### Steps to reproduce

1. Create a new blog post
2. Add a featured image - making sure the image has a 'Description' in the metadata
3. Publish post.
4. Create a new page and insert a "Latest Post' block that includes the post you just created and shows featured images
5. Set an alignment on the 'Latest Posts' block (left/right/center/wide width/full width).
6. Publish the page

#### What I expected

I expect the most recent post to show the feature image and then post title

#### What happened instead

Underneath the feature image some HTML code of the image src is output
This appears to not occur on self-hosted sites but on both SImple and AT sites on WPCOM

#### Browser / OS version

Mac OSX/Chrome

#### Screenshot / Video

<img width="1668" alt="Screen Shot 2020-08-13 at 1 24 52 pm" src="https://user-images.githubusercontent.com/1842363/90090854-6a6bac00-dd68-11ea-94ff-a3943a810fc5.png">

<img width="614" alt="Screen Shot 2020-08-13 at 1 24 59 pm" src="https://user-images.githubusercontent.com/1842363/90090863-6f306000-dd68-11ea-9807-f880b778e59f.png">

#### Context / Source

This was uncovered originally in #3220085-zen and then further tested by @JoshuaGoode and myself.

**Comment by lsl** [comment] 2020-08-13 05:42
Somewhat debugged in D48055-code looks like it might be a wider issue, you can likely replicate this in more contexts using html e.g. `<strong>Test</strong>` in the image description.

**Comment by jordesign** [comment] 2020-08-13 12:13
Have tested this in a .org/JurassicNinja site and could not recreate - even with HTML in the image description.

**Comment by lsl** [comment] 2020-08-14 06:23
It seems limited to the wpcom context, I was not able to repro the issue on .org with a default jetpack setup activated. (I was potentially missing an activating a JP module or something?)

I suspect this is related to the issues seen in jetpack here: 
- https://github.com/Automattic/jetpack/issues/13428
- https://github.com/Automattic/jetpack/issues/13531

**Comment by lsl** [comment] 2020-08-14 06:24
@jeherve would it make sense to move this issue into the Jetpack repo or is it ok to track this here too?

**Comment by jeherve** [comment] 2020-08-14 07:06
> I was not able to repro the issue on .org with a default jetpack setup activated. (I was potentially missing an activating a JP module or something?)

If you still have your Jetpack site setup, could you try to activate the Carousel module under Jetpack > Settings? 

![image](https://user-images.githubusercontent.com/426388/90222967-69d92100-de0d-11ea-84f0-5434b805e9be.png)

If the issue appears with the module on, I think it's safe to close this issue in favor of #13428.

**Comment by jordesign** [comment] 2020-08-14 07:14
> If you still have your Jetpack site setup, could you try to activate the Carousel module under Jetpack > Settings?

I've just tried this on my .org test - and can't reproduce even with the Carousel module active

**Comment by jeherve** [comment] 2020-08-14 07:21
Hm, that's an odd one. On WordPress.com Simple and Atomic sites we also run the Gutenberg plugin; maybe the Latest Posts Block was recently modified in Gutenberg and the bug was introduced then? What happens when you activate the Gutenberg plugin on your Jetpack site?

**Comment by jordesign** [comment] 2020-08-16 23:52
I've been able to recreate slightly different symptoms on
https://specific-guanaco.jurassic.ninja/testing-latest-posts-block/

This is with Jetpack Modules enabled _and_ Gutenberg plugin activated.

<img width="855" alt="Screen Shot 2020-08-17 at 9 50 06 am" src="https://user-images.githubusercontent.com/1842363/90346750-136b1d00-e06f-11ea-99c6-f09289a518a4.png">

No code output - but they still seem broken - no links on titles when image has a description.

<img width="483" alt="Screen Shot 2020-08-17 at 9 52 03 am" src="https://user-images.githubusercontent.com/1842363/90346785-5dec9980-e06f-11ea-838d-a38bc865eed2.png">

**Comment by jordesign** [comment] 2020-08-16 23:57
Further testing - the issue is not seen when Gutenberg plugin is active *and* Carousel mode is turned off. So a conflict between the two?

**Comment by jeherve** [comment] 2020-08-17 08:12
Yes, it would seem like it, and that's most likely something that would be fixed by https://github.com/Automattic/jetpack/issues/13428

**Comment by lsl** [comment] 2020-08-17 09:19
So turns out that note about requiring an alignment (even if its a center alignment) is quite important.

:wave: @ockham, @jeherve

The jetpack carousel module augments the latest-posts block featured images with some extra attributes. I'm assuming this is to apply some jetpack styling/features.

This augmentation includes adding an image description which will by way of `wpautop` always include some [html](https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.php#L485). 

The html is being [escaped here](https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.php#L509) and [injected here](https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.php#L434)

When an alignment is added to this latest posts block, the [alignment block supports code](https://github.com/WordPress/gutenberg/blame/master/lib/block-supports/index.php#L46) in Gutenberg is triggered leading to an [`mb_convert_encoding`](https://github.com/WordPress/gutenberg/pull/24447/files#diff-79942759090688cf5154713c92dc608bR54) to make use of DomDocument.

This `mb_convert_encoding` call and subsequent [reversal](https://github.com/WordPress/gutenberg/pull/24447/files#diff-79942759090688cf5154713c92dc608bR87) seems to be what causes the issue we see here.

The issue seems to be that the fix for WordPress/gutenberg/issues/24445 is decoding html entities it probably shouldn't be in its attempt to rollback the encoding it had to do to use DomDocument cleanly.

I can't really think of a good fix other than doing a dodgy temp replacement of anything that's already encoded but I'm not really sure how safe that is. Then again, it does work so there's that. https://github.com/lsl/gutenberg/commit/126b1a34c6fcc524bfaaa5926da086c1111484ef

Should I move this to a Wordpress/Gutenberg issue (if one doesn't exist?) - Or do you think we should fix this on ourside? (remove image descriptions from Jetpack's carousel data attributes?)

**Comment by jeherve** [comment] 2020-08-17 09:39
> The jetpack carousel module augments the latest-posts block featured images with some extra attributes. I'm assuming this is to apply some jetpack styling/features.

Ideally, the Carousel module should not add extra attributes here, I think. This may be the best approach here.

**Comment by ockham** [comment] 2020-08-17 10:20
Flagging for @sirreal @fullofcaffeine @WunderBart since this is related to our Gutenberg encoding fix :confused:

**Comment by ockham** [comment] 2020-08-17 10:39
Thanks for flagging @lsl!
> I can't really think of a good fix other than doing a dodgy temp replacement of anything that's already encoded but I'm not really sure how safe that is. Then again, it does work so there's that. [lsl/gutenberg@126b1a3](https://github.com/lsl/gutenberg/commit/126b1a34c6fcc524bfaaa5926da086c1111484ef)

Dodgy doesn't sound great TBH :grimacing: As a rule of thumb, the further upstream we go, the cleaner our fixes should be. So: Gutenberg should handle things in a clean fashion; okay to have a workaround in Jetpack, if need be.

On a more practical level -- did you check whether Gutenberg unit tests still pass with your fix applied?

> Should I move this to a Wordpress/Gutenberg issue (if one doesn't exist?) - Or do you think we should fix this on ourside? (remove image descriptions from Jetpack's carousel data attributes?)

Leaning towards Jetpack.

There's a bit of a chance that https://github.com/WordPress/gutenberg/pull/24447 also affects other downstream projects that inject attributes into the rendered HTML, but I'm not sure we can construct a char replacement function that still fixes https://github.com/WordPress/gutenberg/pull/24445 but doesn't break attributes injected by 3rd parties (such as Jetpack). If we can, all the better, but my intuition says no, so this might just be a pill that downstream projects have to swallow.

**Comment by lsl** [comment] 2020-08-18 05:33
> On a more practical level -- did you check whether Gutenberg unit tests still pass with your fix applied?

The expected tests do, a separate css test was failing (so yes, it was a dodgy fix after all :grimacing:!) 

> Leaning towards Jetpack.

I found [a better way to fix this](https://github.com/lsl/gutenberg/commit/e623758b5225ee690a1c04bada2b7bd274f606e8) ([based on](https://gist.github.com/Xeoncross/9401853#gistcomment-1967429)), all tests pass and I've confirmed the desired behavior for WordPress/gutenberg#24445 is maintained.

I would appreciate any ideas around what to cover when writing a couple of tests for this new fix. 

Also is dropping `LIBXML_HTML_NOIMPLIED` a problem? I think we can keep this in if its required.

**Comment by ockham** [comment] 2020-08-18 16:50
@lsl Great, thanks! I left a [comment](https://github.com/lsl/gutenberg/commit/e623758b5225ee690a1c04bada2b7bd274f606e8#commitcomment-41550657) on the commit. Let's discuss there (or better yet, on a PR in the Gutenberg repo :slightly_smiling_face: )

**Comment by lsl** [comment] 2020-08-20 04:23
This will be fixed in the next Gutenberg rollout of v8.8

**Closed by lsl** 2020-08-20 04:23 UTC
Labels: Posts, [Pri] High, [Type] Bug

**Comment by sirreal** [comment] 2020-08-24 16:47
I was expecting to fix this for Simple and Atomic sites running 8.7.1, but I've been unable to reproduce the issue.

Is this issue still present on Simple and Atomic (not running 8.8)?

**Comment by lsl** [comment] 2020-08-25 02:12
Seems to be https://testing705633960.wordpress.com/home/ 8.7.1 simple site business plan.
