### ISSUE TITLE
Payments - Can't See More than 20 Plans

### ISSUE THREAD

**Issue by sdixon194** [Automattic/wp-calypso#45516] opened 2020-09-09 17:33 UTC
#### Steps to reproduce

I have a site with 75 Payment plans on it, but no more than twenty will show on the Payments Plan page, or when going to add the Payments block to a page. 

When adding a new plan, the bottom-most one disappears. Deleting a plan makes another another re-appear, so it seems this is an issue with how the page and block are handling pagination. 

In this gif, you can see how it adds the new plan and things seem fine, but on a refresh the last item goes missing.

![Screen Capture on 2020-09-09 at 13-30-54](https://user-images.githubusercontent.com/33553323/92633506-dde9d600-f2a0-11ea-8c4e-c5161a2ba7cd.gif)

#### Context / Source

p1599663244336400-slack-earn

-->

cc @kwight

**Comment by kwight** [comment] 2020-09-09 23:28
Closing as duplicate of #45517

**Closed by kwight** 2020-09-09 23:28 UTC
