### ISSUE TITLE
"No activity for this period" displays on mobile menu

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#22477] opened 2018-02-15 00:26 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats on a mobile sized view in Chrome or Firefox (Safari OK) on a site with no views (eg. private blog)
2. Close the stats page to see the mobile sidebar

#### What I expected

Can't see "No activity for this period"

#### What happened instead

The label comes through from the stats page

#### Browser / OS version

Firefox or Chrome mobile width screens

#### Screenshot / Video

<img width="649" alt="screen shot 2018-02-15 at 10 20 28 am" src="https://user-images.githubusercontent.com/128826/36235134-88667be6-123a-11e8-9634-6e3ed44d862b.png">

#### Context / Source

Related to https://github.com/Automattic/wp-calypso/issues/22258 which was fixed

**Comment by alisterscott** [comment] 2018-02-15 00:27
@kwight @gwwar I noticed this when doing some regression testing. It **wasn't** introduced in https://github.com/Automattic/wp-calypso/pull/22271 but it wasn't fixed by that fix either

**Comment by kwight** [comment] 2018-02-15 00:44
I've seen it too, it's the same issue (that text comes from the stats page). #22271 has been reverted because of regressions in the Reader :|

Closing as duplicate of #22258 .

**Closed by kwight** 2018-02-15 00:44 UTC
Labels: Design, Sites, [Type] Bug
