### ISSUE TITLE
Sharing: i18n: Custom Message passed to Fb is very long in Japanese

### ISSUE THREAD

**Issue by naokomc** [Automattic/wp-calypso#4150] opened 2016-03-18 14:19 UTC
#### Steps to reproduce
1. Enable Jetpack with Publicize to Facebook feature.
2. Open a new post and type in some Japanese text in the title & body (you can use text from [Japanese Wikipedia](https://ja.wikipedia.org/wiki/メインページ)). Make sure there is no ASCII text/symbol/number.
3. Publish the post while Publicize to Facebook is enabled.
#### What I expected

The Publicized Facebook post to have a short text. 60 words are shown for English posts, so about 150-200 characters in Japanese looks about the same length. There is no space between words in Japanese, so it's best to go by the number of characters.
#### What happened instead

A long text (480 characters, 37 words) is attached to the Publicized Facebook post with a Read More link.

<img width="535" alt="long-message" src="https://cloud.githubusercontent.com/assets/34067/13879808/b6e7959a-ed5c-11e5-9ad4-57ebed0ee407.png">

If the same post is Publicized from wp-admin, the title of the post is shown in place of the text taken from the body.

**Comment by aduth** [comment] 2016-03-18 14:55
You mention "custom message" in the title, but it's not clear from your steps whether you're modifying the message to be sent via Publicize. Can you clarify whether this is the case? In other words, at any point are you expanding the Sharing accordion and changing the message via the textarea field?

**Comment by naokomc** [comment] 2016-03-18 23:34
I didn't enter any custom message for Publicize, I was just referring to the box itself.

Here's a capture of the test post. There's the title of the post in the custom message box, which I didn't enter on my own. The content of this box was not what was shared on Facebook.

<img width="1148" alt="publicize" src="https://cloud.githubusercontent.com/assets/34067/13894578/c3904878-edac-11e5-96b5-05db1343633c.png">

**Comment by aduth** [comment] 2016-03-22 12:59
Looked at this some more this morning.

First, I wasn't able to reproduce the issue that the Calypso editor Publicizes content any differently than the wp-admin editor. In my testing, the Publicize result is identical:

Calypso|wp-admin
---|---
![Calypso](https://cloud.githubusercontent.com/assets/1779930/13952289/ff411ae4-f00b-11e5-921d-b8718215eb53.png)|![wp-admin](https://cloud.githubusercontent.com/assets/1779930/13952283/f5567a7e-f00b-11e5-8f67-c8632e369df7.png)

Looking at the implementation, I do see that it's very clear that we're extracting content from the post with the following arguments: `array( 'max_words' => 60, 'max_chars' => 512 )`

This would likely explain why more of the Japenese text is used. Would you suggest that we decrease the maximum number of characters extracted from a post?

**Comment by naokomc** [comment] 2016-03-23 05:10
Hmm, I'm still seeing the difference:

Calypso|wp-admin
---|---
![Calypso](https://cloud.githubusercontent.com/assets/34067/13975912/d46b2092-f0fd-11e5-81f6-ca1705003d50.png)|![wp-admin](https://cloud.githubusercontent.com/assets/34067/13975913/d51bcc6c-f0fd-11e5-8efc-0748d1250cd4.png)

> Would you suggest that we decrease the maximum number of characters extracted from a post?

Yes, having a character-based limit works for Japanese, Chinese & Thai. These three languages have no spaces between words.
200 characters for `ja`/`zh-ch`/`zh-tw` look fine. `th` looks ok with even more characters.

**Comment by aduth** [comment] 2016-03-23 15:38
@naokomc : Could it be that the posts were drafted not exactly the same? 

I've proposed some changes to reduce the maximum character length used for Publicize posts (ref: D1401-code ).

**Comment by andreabadgley** [comment] 2016-04-14 16:06
A user experienced a similar issue for posts written in Hindi and publicized to Facebook:
![hindi fb](https://cloud.githubusercontent.com/assets/9036382/14534848/f7008682-0238-11e6-8f49-3eeab1c95e4f.jpg)
2626562-t

**Comment by aduth** [comment] 2016-04-14 20:13
Took another look at this one. I've discovered there's some pretty low-level issues with how we're generating excerpts on WordPress.com in not correctly accounting for maximum character length (only using maximum word count), so my previously proposed solution would not be effective enough in solving the problem.

**Comment by hoverduck** [comment] 2016-07-18 17:53
#bug-scrub

Confirmed this is still an issue, although I'm also seeing the same results from Calypso as I am from wp-admin.  Also, the original problem description indicates needing to use a Jetpack site, but I was able to reproduce with a wpcom site as well.

**Comment by lancewillett** [comment] 2016-10-18 17:50
This still needs fixing (#bug-scrub).

**Comment by jeherve** [comment] 2017-02-21 13:21
Also reported here:
https://wordpress.org/support/topic/publicize-failed-auto-excerpt-in-japanese/

**Comment by fumikito** [comment] 2017-07-10 11:49
Any updates?

**Comment by jeherve** [comment] 2018-09-12 09:41
Closing this as this is not valid anymore, since we do not publish to Facebook Profiles anymore, and we do not attempt to post content excerpts to Facebook Pages.

**Closed by jeherve** 2018-09-12 09:41 UTC
Labels: Editor, Sharing, [Type] Bug, i18n
