### ISSUE TITLE
AMP Lightbox effect doesn't work on images if alignment is applied in Non-FSE themes 

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#62774] opened 2022-04-14 13:21 UTC
### Quick summary

The Lightbox effect won't work on images if alignment is applied to the image.

https://user-images.githubusercontent.com/84539773/163399352-a3bfcef7-06e3-47ac-8452-3322e7859a36.mp4

Could replicate the issue on my test site. Atomic.

### Steps to reproduce

1. Use AMP Standard settings.
2. Insert images with AMP Lightbox effect.
3. Adjust the alignment on the image to None
4. Lightbox effect works.
5. Change the alignment on the image to something else.
6. Lightbox effect won't work anymore

### What you expected to happen

Lightbox would work unrelated to alignment. 

### What actually happened

Lightbox effect only works if alignment is set to none

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

User used Baskerville 2 theme.
I tested on 2011, so

Not theme specific!

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Change the alignment to none.

**Comment by cuemarie** [comment] 2022-04-19 20:23
**Replicated?** ✅ in Non-FSE Themes
**Browsers Tested:** Firefox 
**Themes Tested:** 

- Independent Publisher 2, Twenty Twenty One - issue replicated. 
- Zoologist, Blockbase - _could not replicate._ 

**Environments Tested:** AT

**Notes:**

First tested this with Zoologist theme activated, and the AMP lightbox effect worked no matter the alignment settings on my images. 

After switching to **Independent Publisher 2**, the image with alignment set would not open.

https://user-images.githubusercontent.com/27249804/164088921-b6ca2521-3d5f-443a-8e91-a74b8f6bc2ce.mov

Also, switching AMP to Transitional or Reader prevented either image from opening in a lightbox.

**Comment by inaikem** [comment] 2022-05-18 11:41
@cuemarie, can you confirm this bug is specific to AMP features only present when the AMP plugin is active?

If so, then IIRC, we'd want to post it here and move this to the cross-repo watchlist: https://github.com/ampproject/amp-wp.

**Comment by inaikem** [comment] 2022-06-01 03:03
@cuemarie - quick nudge on the above 🙏

**Comment by Robertght** [comment] 2022-06-15 11:00
Reported it here: https://github.com/ampproject/amp-wp/issues/7154 as it happens on self-hosted sites.

**Comment by wojtekn** [comment] 2022-09-06 12:28
I've checked this issue, and I reproduced it in Baskerville 2 and Twenty Eleven themes. It worked well for me in Twenty Twenty Two, though. 

It looks like the issue is being [fixed in the AMP plugin in version 2.3.1](https://github.com/ampproject/amp-wp/issues/7154) which is not released yet.

**Comment by danielbachhuber** [comment] 2022-12-05 20:45
@cometgrrl Given the problem is fixed upstream, is it alright if we close this issue?

**Comment by cometgrrl** [comment] 2022-12-06 21:56
Yep, I'll close it!

**Closed as completed by cometgrrl** 2022-12-06 21:56 UTC
Labels: Bug, [Pri] Normal, AMP, Triaged, Images, Build Maintenance
