### ISSUE TITLE
Stats: bars for the Month view never loads, instead a spinner spins forever.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#83735] opened 2023-11-01 03:26 UTC
### Quick summary

When loading the Month view in Odyssey Stats, the bars do not load. Instead, the spinner spins forever.

Left is an AT site running Jetpack version `12.7-beta-6484569065-gac9b5651` (fairly old).
Right is a Simple site running current Moon deploy, revision `0a681403ae7a6c7914c4138187955e8ea8af3c61`.
![image](https://github.com/Automattic/wp-calypso/assets/6549265/816d7a60-40d2-4015-b158-8090ab29fd9b)

https://github.com/Automattic/wp-calypso/assets/6549265/02541845-61eb-44ba-b3e8-af36b84017d2

### Steps to reproduce

1. log in to WordPress.com.
2. navigate to Sidebar > Stats.
3. halfway down the page, click on the dropdown and select Month.

### What you expected to happen

After a brief moment, the bars for Month view loads.

### What actually happened

Bars for the Month view never loads.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment] 2023-11-02 17:24
📌 REPRODUCTION RESULTS
- Tested on Simple – Could not replicate
- Tested on Atomic – Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Unable to reproduce this on production Simple/AT sites, but it is possible this could still pop up in an upcoming deploy?
A few additional notes on this here: p1698808499177669/1698687786.195139-slack-CQD1HH4MA

📌 ACTIONS
- FYI @jeherve

**Comment by jeherve** [comment] 2023-11-06 09:23
> Unable to reproduce this on production Simple/AT sites, but it is possible this could still pop up in an upcoming deploy?

That's a good question. I added the issue to the Stats board for the Red team (currently maintaining stats).

**Comment by kangzj** [comment] 2024-09-26 23:11
I'm not able to reproduce this, and closing the issue. Please do reopen if it's still the case. Thanks all!

**Closed as completed by kangzj** 2024-09-26 23:11 UTC
Labels: Bug, [Pri] Normal, Triaged, [Plugin] Jetpack, [Platform] Simple, [Platform] Atomic, Odyssey Stats, [Product] WordPress.com
