### ISSUE TITLE
Full and wide width options missing from Site Editor

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#78707] opened 2023-06-27 20:58 UTC
### Quick summary

Some blocks seem to have full and wide width alignment options in the post/page block editor, but _not_ when editing the same content in the Site Editor.

### Steps to reproduce

1. Activate a block/FSE theme.
2. Create a page and add a Slideshow or Gallery block to it. Save changes.
3. Open the same page in the Site Editor.
4. View the alignment options for the Slideshow or Gallery block in both editors.

### What you expected to happen

There should be consistent settings in both editors.

### What actually happened

In the Site Editor, full and wide with settings are missing:

![knxW9G.png](https://github.com/Automattic/wp-calypso/assets/5630717/aafdba07-6369-436a-a19c-b0fdc7c2c1f2)

Compared to the page editor:

![5CVj3K.png](https://github.com/Automattic/wp-calypso/assets/5630717/af118874-60b2-4dd7-8d6a-eae728c99662)

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Tested on Atomic so far, reproduced on _Heiwa_ and _Antonia_. Unsure if this also affects simple or self-hosted sites.

Initially reported here: 6472568-zd-woothemes

For posts and pages (other than the latest posts page or default homepage), the settings are still available in the post/page block editor. For template-only pages, you need to add the affected block(s) into a Group with `inner blocks use content width` enabled for the options to be available.

**Comment by cuemarie** [comment] 2023-06-28 00:59
Possibly related: https://github.com/WordPress/gutenberg/issues/51685

**Comment by cuemarie** [comment] 2023-06-28 01:02
Also possibly related: https://github.com/WordPress/gutenberg/issues/45915

> When a block that supports alignment (None, Wide, Full) is placed inside of a container (i.e. Group) and "
Inner blocks use content width" is toggled off in the contrainer, the alignment controls in the block toolbar of the child block should not display since they do nothing. 

In other words, this may be by design in Core, but confusing, especially with the Post Content block on templates.

**Comment by cuemarie** [comment] 2023-06-28 01:06
Did more digging, and I think this guide from WordPress.org confirms this is by design: https://wordpress.org/documentation/article/layout-settings-overview/#customizing-layout-width

> Toggle off **Inner blocks use content width** so that the nested inner blocks fill the width of the parent container.

> Toggle on **Inner blocks use content width** so that the nested inner blocks use content width with options for full and wide widths.

---

My test on AT site with the Slideshow block matches this behavior:

https://github.com/Automattic/wp-calypso/assets/27249804/722cbaca-023f-488a-b44d-c7f3071e8aac

📌 ACTIONS
- Requested feedback

📌 Message to Author
- @jp-imagines Just to check, do you think I've understood what you're reporting correctly here, based on the WPorg guidance above?

**Comment by jp-imagines** [comment] 2023-06-28 13:23
> Just to check, do you think I've understood what you're reporting correctly here, based on the WPorg guidance above?

I think so. 

The WPorg guidance makes some sense, but it's still _very_ confusing. At least on my site (and I assume this is standard):

* In the block editor, I can choose full or wide width options. There's no Group (or similar) block around the Slideshow etc. (from what can be seen in the page editor) to suggest that would be related.
* If I access template editing through the page editor as in your video, I can see the Post Content block which (for my site) defaults to the `inner blocks use content width` setting **enabled**, and so the full and wide width options are still available. So far so good.
* If I open that page in the Site Editor (via Appearance > Editor), the options are missing. The Post Content block is entirely locked, so the `inner blocks use content width` setting isn't even visible, and the missing alignment/width options suggests it's toggled off, which is inconsistent.

![FUMIBY.png](https://github.com/Automattic/wp-calypso/assets/5630717/26e2627d-9d1f-453f-9293-cba76fbc1fa1)

* If I then enable template editing from the Site Editor (_"Page" tab > Edit template_), the Post Content block is still locked, but I can see the `inner blocks use content width` setting which is **enabled**, which suggests the width settings should be available in the Site Editor. (In this view, I can't select those widths on individual blocks on the page, since the Post Content block is reverted to its placeholder state.)

Everything seems consistent _except_ that you can't set the blocks to full or wide width when editing the page from Appearance > Editor, even though everything else suggests that you should be able to. You can also end up in a state where a block was set to full width from outside the Site Editor, but that option remains missing inside the Site Editor:

![nWJY44.png](https://github.com/Automattic/wp-calypso/assets/5630717/d1ff75c9-2c80-4798-a2fe-ec50af946570)

**Comment by cuemarie** [comment] 2023-06-28 22:02
Haha, you're definitely right, it is confusing @jp-imagines ! Appreciate the breakdown and screenshots. 

As you've seen, I asked over here: p1687989204474379-slack-C03EUR81G3V for some help connecting this to any larger existing conversations in `/gutenberg` about the layout hierarchy that we're discussing.  I think that'll help offer better context, and that'll be an AWESOME place to share the feedback and experience you just outlined!

**Comment by cuemarie** [comment] 2023-07-05 23:11
Ok, recapping some of the relevant conversations and next steps recommended in the thread above!

- The Gutenberg conversation that's most closely covering this topic is: https://github.com/WordPress/gutenberg/issues/42385
- There's also been some relevant feedback on this regarding[ improving the wording](https://github.com/WordPress/gutenberg/issues/36082#issuecomment-959715947) and some [user examples of expectations](https://github.com/WordPress/gutenberg/issues/36082#issuecomment-1147856508)
- [Improving the Documentation](https://github.com/WordPress/Documentation-Issue-Tracker/issues/711#issuecomment-1612578622) around this feature has already been requested, h/t to @mrfoxtalbot 

📌 ACTIONS
- Closing as `by design` / in favor of the larger Gutenberg issues noted above

**Closed as not planned by cuemarie** 2023-07-05 23:11 UTC
Labels: Bug, [Pri] Normal, [Status] Needs Author Reply, [Status] Core Fix Needed, Triaged, [Platform] Atomic
