### ISSUE TITLE
[Bug]: Creating site with `/start` doesn't set correct page on front when `lang="en-gb"`

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#59924] opened 2022-01-10 22:15 UTC
### Steps to reproduce

1. Set language to `en-gb`
2. Create a new site at `/start`
3. Choose the "build" intent
4. Choose "Ames" theme (this is the one I tested with, but others might have the issue too)
5. Check out the front end of the created site 

### What you expected to happen

The homepage of the site has something on it. It shouldn't be blank.

### What actually happened

The homepage of the site is blank. If you take a look at the settings you can see that the front page hasn't been set. The homepage looks blank because it's showing latest posts, and there aren't any.

### Context

Discovered while testing paYE8P-1nV-p2

### Other notes

The headstart logs have a message about the `en-gb` locale not being supported. I suspect this error is causing part of the headstart process to bail, and skip setting the page on front setting.

Creating a site with `/new` doesn't have this issue.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

The user can temporarily change their locale to `en`. However, since most users coming to `/start` are brand new, they won't be familiar with the settings in `/me`. They would have been auto-assigned the `en-gb` language.

**Comment by roo2** [comment] 2022-01-11 05:18
EDIT: it looks like it's not happening every time which just lead me to chase my tail and report something incorrect 😅 

I can reporduce it with the "English" language selected as well as the "English (UK)" Language selected, but it is intermittent in both cases

**Comment by roo2** [comment] 2022-01-12 12:21
ok, Via a painful process of elimination, I think I've narrowed this down to being caused by the 'headstart_delete_posts' async job.

using `sandbox_async_job` I confirmed that if the job is not run, the issue will never happen (tested 10 times)
When the job is run manually in my sandbox the issue happens (maybe 1/3 times)

**Comment by roo2** [comment] 2022-01-13 01:31
ok, I've tracked down the exact spot where there is a race condition:
 * There is a 'before_delete_post' hook that resets `page_on_front` if the deleted post was the page on front (in the `headstart_delete_posts` thread).
 * Headstart changes the `page_on_front` (in the main thread)
 * When the delete hook is triggered for the old page, it is possible that the "is page_on_front" check will pass, then, in the main thread, the `page_on_front` will be changed, then back in the `headstart_delete_posts` thread, since the check passed, `page_on_front` will be cleared.
 
### Diagram
```
headstart_delete_posts job                      main headstart thread
                 .                                       .
  Check deleted post for being                           .
   the page_on_front                                     .
                 . ----------------------------------->  .
                 .                                       .
                 .                           Change the page_on_front
                 .                                       .
                 .  <----------------------------------  .
                 .                                       .
   Since deleted post was
   page_on_front, set 
    page_on_front to 0
```


I put log messages in and confirmed that this is the order that things happen in when this issue occurs.

I wonder if caching of option values is involved, because this looks like it should be extremely unlikely to occur, but it is quite common. I think I'll create a p2.

I don't think this is related to en-gb. It may be more likely to affect themes with the number of pages more likely to cause this specific timing.

**Comment by p-jackson** [comment] 2022-01-14 02:30
Holy cow this is great digging @roo2!

What if we delayed the firing off the delete posts job until all of HS has finished running. That way we wait for everything that we want to be done synchronously to be finished first, and _then_ we say it's ok to start doing all of the long job processing?

That way we know that the first time the `headstart_delete_posts` thread queries the `page_on_front` setting, it'll be the latest value and not some old cached value.

**Comment by roo2** [comment] 2022-01-14 05:29
Ooo I didn't think of putting the deletes after the insertions. I think that makes sense, hmmm the only possible downside is that it may make it possible for the new user to see the soon-to-be-deleted posts on their new site.

Other options would be:
* Make the delete synchronous again
  * Would fix the issue but degrade performance
* Some kind of locking mechanism?? 
  * I haven't seen anything like this in wpcom yet, and even my theoretical knowledge of how to implement this is so rusty... I think we would need some mechanism to delay and retry the action if there's a conflict. I'm not sure if we can implement it with just writing a different site option or if there needs to be like a built in locking primitive?
* Investigate this caching hypothesis
  * I was thinking that having the statements interleave like this should be incredibly unlikely. What might explain it would be if there is some kind of caching of site option values within the async job. So for example, when `headstart_delete_posts` reads the value of `page_on_front`, it is reading a value that was saved _when the job started_ rather than whatever the current value is.
  * I'm not sure if knowing whether this is true or not would actually help us solve this issue? it would certainly help to explain it!

**Comment by roo2** [comment] 2022-01-14 06:09
I made a p2 post about this pbxlJb-SG-p2 especially trying to get help with the more advanced fixes

**Comment by roo2** [comment] 2022-01-25 01:08
closed by D73127-code

**Closed as completed by roo2** 2022-01-25 01:08 UTC
Labels: Bug, [Pri] High, [Size] S, Blogger Experience Pod
