### ISSUE TITLE
The Form block's Checkbox Group block doesn't like commas

### ISSUE THREAD

**Issue by detlefholtz** [Automattic/wp-calypso#35110] opened 2019-08-02 21:27 UTC
When adding a Checkbox Group block to the Form block, if there are commas between words then that is registered as a line break and it automatically creates another item in the list. 

So when this is entered in the editor:
![image](https://user-images.githubusercontent.com/30025667/62399709-57fa4800-b542-11e9-8ab0-bd0e0102b47e.png)

This is what it looks like published: 
![image](https://user-images.githubusercontent.com/30025667/62399684-444ee180-b542-11e9-9e98-a3d340b8d381.png)

**Comment by georgestephanis** [comment] 2019-08-13 14:28
This is a legacy Contact Forms bug, not specific to Gutenberg or Calypso.

https://github.com/Automattic/jetpack/issues/2917
https://github.com/Automattic/jetpack/issues/7633
https://github.com/Automattic/jetpack/issues/9967

**Comment by khristiansnyder** [comment] 2019-09-09 19:40
Another report here:

HC-15134562

A workaround is to use a different character for the comma, such as https://www.compart.com/en/unicode/U+066B

**Comment by nunyvega** [comment] 2019-10-20 13:41
Another report here:
ZD - 2432901

**Comment by chrisfromthelc** [comment] 2019-12-04 17:51
Another report in hc-17104987.

**Comment by kavyagokul** [comment] 2020-06-30 04:01
Another report in 22276959-hc

I suggested using the html entity for comma(`&#44;`), which works great

**Comment by rinazrina** [comment] 2020-08-07 09:10
Another report here: 3204785-zen

**Comment by dcoleonline** [comment] 2020-10-31 15:01
Another report 25306258-hc

**Comment by jordesign** [comment] 2021-05-19 20:45
Should we close this in favour of the JP issue this is caused by? Or is it useful for tracking separately here?
https://github.com/Automattic/jetpack/issues/2917

**Comment by cuemarie** [comment] 2023-06-29 00:03
_This report was found during a recent backlog sweep._

> Should we close this in favour of the JP issue this is caused by? Or is it useful for tracking separately here?

I don't think we need to keep both open for tracking; we can track user reports in either repo. Closing this in favor of https://github.com/Automattic/jetpack/issues/2917

📌 ACTIONS
- Closed as duplicate

**Closed by cuemarie** 2023-06-29 00:03 UTC
Labels: [Type] Bug, [Goal] Gutenberg, User Report
