### ISSUE TITLE
2FA: twostep_auth cookie not setting in Chrome when developing locally

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#46127] opened 2020-10-02 18:13 UTC
#### Steps to reproduce
ONLY reproducible in local env (http://calypso.localhost:3000) and when using Chrome.

1. Starting at URL: http://calypso.localhost:3000/me in the Chrome browser
2. Delete your existing `twostep_auth` cookie in DevTools > Application
3. Refresh
4. Enter the 2FA verification code when prompted

#### What I expected
To see a new `twostep_auth` cookie in DevTools > Application.

#### What happened instead
There's no new cookie and if I refresh I'm asked for the verification code again.
There are also errors related to loading user settings when I navigate to security settings:
<img width="564" alt="Screen Shot 2020-10-02 at 2 08 00 PM" src="https://user-images.githubusercontent.com/1689238/94955570-c32e0a00-04b8-11eb-8369-5d53308c6d5b.png">

#### Browser / OS version
Chrome on MacOS 10.15.6

#### Context / Source

Found while testing #36811

**Comment by frontdevde** [comment] 2020-11-05 11:42
+1 I just ran into this issue while trying do some local dev on /me/account. This issue leads to /me section remaining in loading state in Chrome. Can confirm that I'm not seeing this issue in Firefox.

**Comment by marekhrabe** [comment] 2020-11-05 11:44
+1, preventing development in chrome

**Comment by youbrokesomething** [comment] 2022-09-22 19:50
Hi, @allilevine I'm reviewing issues that haven't been updated in a long time and came across this. I can't reproduce the original error anymore on local in chrome. I'm going to close this but please reopen it if you're still able to reproduce the issue.

**Closed by youbrokesomething** 2022-09-22 19:50 UTC
Labels: [Type] Bug, [Pri] Normal, Triaged, 2FA
