### ISSUE TITLE
Theme: Rowling - Quote block missing styling in editor, looks like Paragraph block

### ISSUE THREAD

**Issue by cuemarie** [Automattic/wp-calypso#69724] opened 2022-11-03 01:25 UTC
### Quick summary

In the theme Rowling, text inside a quote block looks the same as regular paragraph blocks, making it hard to find in the editor.

### Steps to reproduce

1. Activate **Rowling** theme
2. In a page or post, add a quote block

### What you expected to happen

The quote block to show any kind of indentation or styling, making it stand out as a different block.

### What actually happened

The content inside the quote block looks like a normal paragraph block.

**ATOMIC**

<img width="1459" alt="Markup 2022-11-02 at 18 17 54" src="https://user-images.githubusercontent.com/27249804/199631607-e822251e-c88d-425a-99c8-86d9ac8963b7.png">

**SIMPLE**

![Markup on 2022-11-02 at 18:23:49](https://user-images.githubusercontent.com/27249804/199631751-1b40e469-b892-4172-9d5e-59b654fb74b6.png)

### Context

Reported here: 5664186-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Rowling

Quick-tested by switching to Twenty Sixteen, another Classic Theme, and the issue was not present there.

### Browser, operating system and other notes

Quote block still stands out on the live site: 

<img width="1061" alt="Markup 2022-11-02 at 18 20 10" src="https://user-images.githubusercontent.com/27249804/199631790-82fa1df9-98bd-412f-92d5-1d30329e7707.png">

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by kavyagokul** [comment] 2022-11-08 11:30
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated 
- Tested on AT - Replicated
- Tested on Self-hosted - Replicated 
- Replicable on Core - No


📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/themes/issues/3515
- Added info from here to the existing bug

**Closed as completed by kavyagokul** 2022-11-08 11:30 UTC
Labels: Bug, [Pri] Normal, [Platform] Simple, [Platform] Atomic
