### ISSUE TITLE
Simple Payments: Payment error for prices having decimal value

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#22939] opened 2018-03-02 05:38 UTC
**Steps to reproduce**: Follow the steps below to reproduce the issue. 

1. Start creating a Simple Payments listing.
2. Use decimal value pricing.
3. Save the listing.
4. Try paying as an user. 

**What is expected:** Payment is being processed.

**What happens instead:** PayPal popup appears (doesn't show the login view though) and closes in a split second. We see a "Payment did not create successfully" error later on.

![image](https://user-images.githubusercontent.com/18581859/36884900-beb27ba2-1e09-11e8-8c6f-a2fac6237ac5.png)

(Edited, note that currencies like JYP do not support decimal units, so client validation in that case is expected).

**Comment by arunsathiya** [comment] 2018-03-02 05:41
#1945868-hc

**Comment by rachelmcr** [comment] 2018-03-02 18:26
>More information: We see a notice that decimal values cannot be used on certain currencies.

To clarify, are you also seeing this notice in the case described in this report? Or is this additional information. (That notice is expected for currencies that can't contain decimal values.)

cc @kristarella as you were troubleshooting another case involving certain values not working; not sure if this is the same as the issue you saw.

**Comment by arunsathiya** [comment] 2018-03-05 12:19
>To clarify, are you also seeing this notice in the case described in this report? Or is this additional information. (That notice is expected for currencies that can't contain decimal values.)

Hi @rachelmcr, reiterating what I mentioned earlier: **We see this notice only for HUF and JYP, and not for other currencies.**

Sorry, I should have mentioned this point above the image.

**Comment by millerf** [comment] 2018-03-05 16:11
Hi,

I wanted to work on this issue, but I cannot find how to create a Simple Payments listing without having to upgrade my plan...

**Comment by nielslange** [comment] 2018-03-09 07:30
#1957716-hc
#985422-zen
#983281-zen
#994143-zen

**Comment by rachelmcr** [comment] 2018-03-09 11:41
Thanks @arunsathiya. The expectation from PayPal's documentation is that decimal values aren't supported for those currencies in particular, but they are for other currencies, so that notice is working as expected.

@millerf As far as I'm seeing this is a backend issue and not in Calypso, so it will likely need to be resolved internally. That said, if you'd still like to investigate it or other issues with paid plans I'd be happy to add you to a test site with a plan where you can take a look. Please let me know your WordPress.com username and I'll take care of that for you. :)

We also have a related issue for Simple Payments requests handling in https://github.com/Automattic/wp-calypso/issues/22388. (cc @iamtakashi in case you know who might tackle this and what priority it should have.)

**Comment by millerf** [comment] 2018-03-09 12:49
@rachelmcr Yes, I would be happy to have a try. I think I saw a couple of other issues that I wouldn't mind investigate in the near future. My wordpress account is @millerf81. Thanks

**Comment by rachelmcr** [comment] 2018-03-09 14:00
@millerf Great! I sent you an invitation to a test site; please feel free to investigate as needed there. Thanks again for getting involved with Calypso. :)

**Comment by retrofox** [comment] 2018-03-09 19:35
Hi folks,

My first question is how you are able to set a decimal price when the currency is `JYP` `HUF`.
The field validation seems to work well, avoiding adding or editing a new product when you try to define a decimal value.

![image](https://user-images.githubusercontent.com/77539/37226097-998d8728-23b7-11e8-96c5-b2a9ec6a3dd7.png)

Anyway, maybe we should improve the data validation when the product is saved in the server-side.

**Comment by designsimply** [comment] 2018-03-09 19:42
Tested and confirmed I cannot create a payment button in USD for an amount such as $103.24.

Video: [1m34s](https://cloudup.com/cnb6SufKiKM)

![payment-button-strange-error](https://user-images.githubusercontent.com/1119271/37226472-4c9547c8-2397-11e8-9e9c-2b18270c7c16.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11926 (Business Plan) using Firefox 58.0.2 on macOS 10.13.3.</sup>

![payment-button-error-after-a-purchase-attempt](https://user-images.githubusercontent.com/1119271/37226478-502a3664-2397-11e8-9666-ee98a71c0ea7.png)
<sup>Seen at https://design5279.wordpress.com/2018/03/09/payment-button-test/ using Firefox 58.0.2 on macOS 10.13.3.</sup>

**Comment by alisterscott** [comment] 2018-03-09 22:47
This looks like it's actually ok if you use .25 decimal increments, so 1.25, 1.50, 1.75 etc. but not any other values after the decimal.

**Comment by gwwar** [comment] 2018-03-09 22:50
@alisterscott are you still seeing the issue? This should have been resolved by D10823-code

**Comment by alisterscott** [comment] 2018-03-09 22:54
@gwwar kind of. It's working for me fine in Firefox and Safari now, but in Chrome I'm not seeing the Paypal button at all - separate issue? 

Test post: https://eatkibbeling2.wordpress.com/2018/02/28/payment-button/

**Comment by alisterscott** [comment] 2018-03-09 22:55
Tampermonkey - sorry - all fine now

**Comment by alisterscott** [comment] 2018-03-09 22:56
I can no longer reproduce this issue so I'm going to close this

@arunsathiya would you mind re-checking and comment/re-open as necessary?

**Closed by alisterscott** 2018-03-09 22:56 UTC
Labels: OSS Citizen, Simple Payments, [Pri] High, [Type] Bug

**Comment by poojashetty18** [comment] 2019-09-05 06:34
Another issue reported: 15037367-hc
