### ISSUE TITLE
FSE: Edit Header button disappears after editing Header.

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35419] opened 2019-08-15 19:46 UTC
via @ianstewart 

- Made changes to my header template.
- Clicked Update.
- Clicked Back to Page.
- Did not see Edit Header button. Did not know how to make changes to my Header.

**Comment by noahtallen** [comment] 2019-08-15 19:55
I am unable to reproduce this on the current version. Perhaps the user didn't select the header again?

**Comment by apeatling** [comment] 2019-08-15 20:20
@ianstewart Can you confirm even when clicking on the header you did not see the edit button?

**Comment by gwwar** [comment] 2019-08-19 17:24
If folks can reproduce, a video or gif would be lovely

**Comment by ianstewart** [comment] 2019-08-19 18:11
> Can you confirm even when clicking on the header you did not see the edit button?

It was even when clicking. Tried to reproduce just now. Can't reproduce on the current version. I'll close the issue.

**Closed by ianstewart** 2019-08-19 18:11 UTC
Labels: [Goal] Full Site Editing, [Pri] High, [Type] Bug
