### ISSUE TITLE
Stats: stats don't display for non-admin users on Atomic sites

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#26918] opened 2018-08-27 04:53 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/ for an Atomic site where user is not administrator (eg. editor)

#### What I expected

To see Stats Menu
For Stats to work

As per support [doco](https://en.support.wordpress.com/stats/):

> What users can see my site’s stats?
> All of your site’s users can see the stats: Administrators, Editors, Authors, and Contributors.

#### What happened instead

Can't see Stats
Trying to view stats via URL shows stats with empty data and console error:

`Unhandled Promise Rejection: ForbiddenError: You do not have the capability to manage settings for this site.
`

#### Browser / OS version

Chrome and Safari on macOS

#### Screenshot / Video

<img width="1431" alt="screen shot 2018-08-27 at 2 52 43 pm" src="https://user-images.githubusercontent.com/128826/44641133-e13afd80-aa08-11e8-8eaf-9dd55bd80e14.png">

#### Context / Source
#dogfooding

**Comment by rachelmcr** [comment] 2018-08-29 17:11
Thanks for the report! :) Closing this as a duplicate of https://github.com/Automattic/wp-calypso/issues/14151.

**Closed by rachelmcr** 2018-08-29 17:11 UTC
Labels: Atomic, Stats, [Type] Bug
