### ISSUE TITLE
Blogger.com importer does not import videos

### ISSUE THREAD

**Issue by jeroenpf** [Automattic/wp-calypso#50744] opened 2021-03-04 07:42 UTC
The blogger.com importer is currently not importing videos that have been uploaded by the user on their Blogger site and added to a post. If possible, we should ensure the video is imported and added to the post properly.

Instead of a video, an empty separator div is added: 

```html
<div class="separator" style="clear:both;text-align:center;"></div>
```

A video is represented in the exported content as follows:

```html
<object class="BLOG_video_class" contentid="df8c8bd546119ad8" height="266" id="BLOG_video-df8c8bd546119ad8" width="320"></object>
```

### Steps to reproduce the behavior

1. On blogger.com, create a post for a site and add a video to the post by uploading it.
2. Export the blogger.com site
3. Go to WordPress.com and import the blogger.com export file
4. Open the post and see an empty separator div has been added in the place where the video should appear.

**Comment by kosiew** [comment] 2021-11-22 09:48
@vishnugopal ,

I added a video on a blogger post - https://oracleprofessional.blogspot.com/2021/11/blog-post.html but the video does not load.

Since the platform is not actively developed anymore, I highly recommend assigning this a low priority or close it altogether.

**Comment by gikaragia** [comment] 2024-09-23 13:06
Tried this and indeed videos are not imported. The way importing works is that the user downloads a backup of their site which it uploads to the importer. Here how videos are exporterd:
```
class="BLOG_video_class" contentid="b734447cbaf4dc38" height="266" id="BLOG_video-b734447cbaf4dc38"
```
This when displayed in blogger has a video with source:
```
https://www.blogger.com/video.g?token=AD6v5dzWrvPknPDNDDuDxAxBLeVcLcQ8QaQobKTguK9M9Ga1z9C-L8bMySyxHAt-_c7z987MP-y41yhYacGL0soDX84-xqYalvo4sO7Aoyup2x-cu0_inseSnk1UWDoLRjZHWRDulInL
```

The problem is that there is no clear way of how to get the source from the exported values. So I think we should resolve this as:
- It is very difficult (probably impossible) to implement
- The import for blogger.com has very low traffic.

**Closed as completed by gikaragia** 2024-09-23 13:06 UTC
Labels: Bug, Import
