### ISSUE TITLE
PDF Embed Not Loading on Live Site

### ISSUE THREAD

**Issue by cat-og** [Automattic/wp-calypso#90964] opened 2024-05-21 18:47 UTC
### Quick summary

On Simple sites, the File block will not display the PDF embed on the live site, even when the `Show inline embed` option is selected. The embed appears correctly in the draft view of the page, but is missing on the live site. 

Draft page: 
<img width="2868" alt="Markup 2024-05-21 at 11 39 57" src="https://github.com/Automattic/wp-calypso/assets/86028337/d8e40b45-6be9-4c78-b354-12f7d24554ba">

Live Site: 
<img width="1512" alt="Markup 2024-05-21 at 11 41 41" src="https://github.com/Automattic/wp-calypso/assets/86028337/07b41110-d5c8-49be-b773-1d1fb1397665">

This appears to be unrelated to [this other PDF embed issue](https://github.com/Automattic/wp-calypso/issues/90865). 

### Steps to reproduce

1. Add a File block to the page
2. Add a PDF, and ensure the option 'Show Inline Embed' is selected. The preview should show in the draft.
3.  Save changes. 
4. Check live site. 

### What you expected to happen

For the file preview to work correctly on the live site. 

### What actually happened

The PDF embed does not load at all, only a blank space above the download button. 

This seems to be somewhat inconsistent as well; the user who initially reached out only saw this on one PDF on their site, while the other worked as expected. However, when I tried both of those PDFs on my own simple site, neither worked. Nor did any of the test PDFs I've used successfully in the past. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by cat-og** [comment] 2024-05-21 18:48
Reported here: 8219866-zd-a8c (Simple Site, Assembler theme)

**Comment by ariel-maidana** [comment] 2024-05-22 17:16
Another report here: 8224801-zd-a8c (Simple site, pub/illustratr theme with the locale ja).

**Comment by RafaelFunchal** [comment] 2024-05-22 18:14
A user reported the issue on the pt-BR forum. https://wordpress.com/pt-br/forums/topic/incorporacao-pdf/

**Comment by liviopv** [comment] 2024-05-23 10:17
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Could Not Replicate
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO

### Simple
![CleanShot 2024-05-23 at 11 07 33@2x](https://github.com/Automattic/wp-calypso/assets/14153300/e294bc68-c3cc-4851-90d9-032060e84bfd)

![CleanShot 2024-05-23 at 11 04 33@2x](https://github.com/Automattic/wp-calypso/assets/14153300/dc7947f5-9799-4134-913d-c5d2d3bec794)

### Atomic
![CleanShot 2024-05-23 at 11 16 10@2x](https://github.com/Automattic/wp-calypso/assets/14153300/25938206-ef0e-4948-aab8-58e4c1830712)


![CleanShot 2024-05-23 at 11 06 44@2x](https://github.com/Automattic/wp-calypso/assets/14153300/f368221f-fccc-430b-b138-bcdb69f49c2a)

📌 ACTIONS
- Triaged

Considering it's happening only on Dotcom Simple Sites, @devicenull could this be related to the other issues with media files on Simple Sites?

**Comment by devicenull** [comment] 2024-05-23 14:56
I'm not sure that's related - the issues in #87642 are not relevant to content not appearing on the public side of things.  I looked at your simple test page and I don't see the browser attempting any sort of request for the PDF file.  This would lead me to believe it's unrelated to the existing issue.

**Comment by caitlindawn** [comment] 2024-05-23 15:48
Reported in 8225450-zen
Theme: Zoologist

**Comment by jamiepalatnik** [comment] 2024-05-23 17:57
Another report: 8229728-zd-a8c
Looks like there some other new reports on this issue: https://github.com/Automattic/wp-calypso/issues/83224

**Comment by DavidSaladu** [comment] 2024-05-23 21:46
Another report 8230714-zd-a8c.

**Comment by wiesenhauss** [comment] 2024-05-24 14:23
Another report: 8225251-zd-a8c

**Comment by joseprthur** [comment] 2024-05-24 16:20
Another report: 8233210 zen
theme: Dara

**Comment by dhackneya8c** [comment] 2024-05-25 15:55
Another report: 8237925-zd-a8c

**Comment by tellisbethel** [comment] 2024-05-27 18:42
Another case here: 8245105-zd-a8c

**Comment by jamiepalatnik** [comment] 2024-05-27 20:02
Another report: 8212524-zd-a8c
I let the user know we would share an update when this is fixed. I also suggested embedding Google Docs as a workaround in the meantime.

**Comment by hacchism** [comment] 2024-05-28 00:01
Another report: 8245456-zd-a8c

I offered to update the user when this is fixed.

**Comment by saginpj** [comment] 2024-05-28 06:34
- [ ] 8245271 - zen

**Comment by sanjeev00733** [comment] 2024-05-28 09:39
8237925-zd-a8c
The user came back asking for an update on the fix. I have informed them that we will provide an update once this is resolved.

**Comment by jorpdesigns** [comment] 2024-05-29 08:25
8251779-zen

**Comment by joseprthur** [comment] 2024-05-29 21:35
8254307 -zen

**Comment by deancroyal** [comment] 2024-05-30 21:19
Report: 8260086-zd-a8c
Theme: Sela

**Comment by lupus2k** [comment] 2024-05-31 14:31
This is now fixed by this diff (D150456-code)
> [!IMPORTANT]  
> Posts/Pages that contain PDF and are not displaying will need to add the PDF and save again to see the preview.

**Comment by mxhassani** [comment] 2024-05-31 15:06
@lupus2k To confirm, the fix will not backroll and all users that have PDF embeds need to edit all their pages?

**Comment by lupus2k** [comment] 2024-06-03 14:04
> @lupus2k To confirm, the fix will not backroll and all users that have PDF embeds need to edit all their pages?

@mxhassani, Only users who included PDFs could not see it on the page.

**Comment by liviopv** [comment] 2024-06-13 13:08
Closing this.

**Closed as completed by liviopv** 2024-06-13 13:08 UTC
Labels: Bug, [Pri] High, [Feature] Media, Triaged, Customer report [LEGACY], [Platform] Simple, [Interaction #] > 10, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks
