### ISSUE TITLE
Customizer: Unable to close Customizer when opened from Quick Links >> Edit Menus

### ISSUE THREAD

**Issue by kamlesh08** [Automattic/wp-calypso#47654] opened 2020-11-22 20:51 UTC
**Steps to reproduce**

1. Starting at WordPress.com Desktop App (Ubuntu)
2. Click on My Home >> Quick Links >> Edit Menus.
3. Now, Customizer will be opened.
4. Click on the close button (X) at the top of the Customizer.
5. See error.

**What I expected**
When I click on the close button (X) at the top-left of the Customizer, I expect the Customizer to be closed and I should be taken to My Home.

**What happened instead**
When I clicked on the close button (X) at the top-left of the Customizer, the page reloaded and I was still on Customizer.
I wasn't redirected to My Home.

**Browser / OS version**
Ubuntu 20.04.1 LTS - 64-bit

**Screenshot / Video**

**_Step 1_**
![Screenshot from 2020-11-23 02-19-11](https://user-images.githubusercontent.com/22547800/99916826-75a08180-2d32-11eb-9167-615af8b40610.jpg)

**_Step 2_**
![Screenshot from 2020-11-23 02-15-38](https://user-images.githubusercontent.com/22547800/99916758-ff9c1a80-2d31-11eb-8ae8-f57479c29922.jpg)

**Context / Source**

#dogfooding, #manual-testing

**Comment by ericamQA** [comment] 2021-06-04 22:07
Unable to reproduce. Closing.

**Closed as completed by ericamQA** 2021-06-04 22:07 UTC
Labels: Bug, Menus, [Closed] Not Reproducible
