### ISSUE TITLE
Renewal fails with "Cannot add product for this type of cart."

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#18661] opened 2017-10-09 13:13 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/checkout/value_bundle/renew/6885258/futonbleupremium.wordpress.com

#### What I expected

One year premium renewal to appear in the cart.

#### What happened instead

Messaging says that I owe nothing, and I see the error notice ""Cannot add product for this type of cart."

<img width="887" alt="screen shot 2017-10-09 at 14 08 51" src="https://user-images.githubusercontent.com/17325/31339735-bae780c8-acfb-11e7-90f3-83cf2fe01d67.png">

I followed the link from a email saying my automatic renewal had failed:

<img width="645" alt="screen shot 2017-10-09 at 14 12 36" src="https://user-images.githubusercontent.com/17325/31339801-ff10ef96-acfb-11e7-812f-9f7e17edf1f2.png">

I originally paid for this test upgrade using credits.

**Comment by rralian** [comment] 2018-01-31 22:21
We believe this is related to subscriptions purchased with credits. Adding it to a backlog of issues associated with renewals and credits.

**Comment by rachelmcr** [comment] 2018-08-29 13:00
I happened to have a renewal email for a test account/site that I used to test this issue. The renewal email and plan weren't exactly the same, but the original purchase was made with credits and the link in the email did lead me to a similar purchase flow:

https://wordpress.com/checkout/business-bundle/renew/:purchaseId/:domain

Here's the email I received:

![screenshot 2018-08-29 13 52 25](https://user-images.githubusercontent.com/8658164/44789003-681be180-ab93-11e8-9ea5-234a90113bcb.png)

However, the renewal flow worked as expected for me. I didn't get the reported error or have any trouble completing the renewal purchase.

Since I didn't exactly reproduce the original conditions, I'm not sure the case in the original report is resolved, but I'm hopeful that it might be if the issue was tied to renewing subscriptions purchased with credits. I'll try again with a more similar purchase (Premium plan on a site with no custom domain, purchased with credits) and see if I can reproduce the issue that way.

**Comment by rachelmcr** [comment] 2018-08-31 12:51
I tested again with a WordPress.com Premium plan purchased with credits. I received the same "Auto renew failed" email as in the original report:

![screenshot 2018-08-31 11 01 45](https://user-images.githubusercontent.com/8658164/44913146-66355800-ad24-11e8-8c59-f085072f800c.png)

In my testing, though, the product was added successfully to my card:

![screenshot 2018-08-31 11 01 51](https://user-images.githubusercontent.com/8658164/44913195-8c5af800-ad24-11e8-8be7-19a315e1d284.png)

And I completed the renewal successfully:

![screenshot 2018-08-31 11 02 07](https://user-images.githubusercontent.com/8658164/44913202-94b33300-ad24-11e8-86cc-cfaf94a5c469.png)

Since the flow described in the original issue also seems to be working as expected, I'm going to close this issue. Please reopen if you think there's something here that needs further investigation.

**Closed by rachelmcr** 2018-08-31 12:51 UTC
Labels: Checkout, [Pri] High, [Type] Bug
