### ISSUE TITLE
Unable to double click to select text in FSE

### ISSUE THREAD

**Issue by thebud15** [Automattic/wp-calypso#59469] opened 2021-12-21 19:45 UTC
### Quick summary

When trying to double click a word or highlight text using my mouse, I was unable to do so within the FSE (tested on themes Quadrat White and Geologist Cream)

### Steps to reproduce

1. Activate FSE and a FSE-first theme (such as Quadrat or Geologist)
2. Add written content to a new page or post. 
3. Try to highlight words by double clicking or dragging your mouse across this text.

### What you expected to happen

I expected the words to be highlighted.

### What actually happened

Nothing was highlighted.

### Context

This came up during FSE team testing. Here's a clip:
![Screen Capture on 2021-12-21 at 11-33-00](https://user-images.githubusercontent.com/29046778/146988646-06a4046c-251a-4e3a-aa74-d96a98ba3a7c.gif)

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

This seems FSE-specific (tested on Quadrant and Geologist)

### Browser, operating system and other notes

Google Chrome 95.0.4638.69
MacOS Mojave version 10.14.6

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

A clunky workaround is to position a mouse and backspace over the affected text.

**Comment by Greatdane** [comment] 2021-12-23 00:20
I am unable to reproduce this. I seem to get the same functionality on FSE or non FSE sites. 

@thebud15 Have you tried a different test site and it happens on all? Any other blocks present or embedded? Also using the same browser and OS as you.

**Comment by brittanygray902** [comment] 2021-12-23 01:25
I was able to replicate this when using the theme Blockbase.

Site Plan: Business
Initially I deactivated all plugins (except Gutenberg) and the issue continued to persist.

I was going on to my site to see if I can replicate and show you but now I am seeing this, when trying to enter FSE:
https://d.pr/v/LcOTa4

Essentially, what I am seeing now is that it will not even load for me.

@thebud15  Maybe you can double check your site and see if this is happening to yours now, as well?

**Comment by thebud15** [comment] 2021-12-29 01:17
@Greatdane Seems like it works fine on another test site of mine, so it might just be a site-specific fluke.

**Comment by kerrynicl** [comment] 2022-01-24 15:39
I'm not able to replicate on any of my test sites so I'll be closing this issue for now.

**Closed as completed by kerrynicl** 2022-01-24 15:39 UTC
Labels: Bug, [Goal] Full Site Editing, Triaged, [Closed] Not Reproducible
