### ISSUE TITLE
Notifications: "Replied To" Comment Indicator Goes Missing on AT

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#42973] opened 2020-06-04 06:57 UTC
When you reply to a comment on your site, the Notifications area shows an arrow indicator to mark that you have replied to the comment:
<img width="572" alt="Image 2020-06-04 at 1 52 51 PM" src="https://user-images.githubusercontent.com/30727666/83723477-1d8d9a00-a682-11ea-9352-0452da79055d.png">

After the site becomes atomic, the indicator no longer appears, even on new comments replied to post-AT:
<img width="809" alt="Image 2020-06-04 at 4 20 14 PM" src="https://user-images.githubusercontent.com/30727666/83723815-9a207880-a682-11ea-9881-2ae10139e224.png">

#### Steps to reproduce

1. Starting with a blog post on a simple site, leave a comment.
2. As the site owner, check the notifications bar for the comment, and use the in-notification reply feature to post a reply. Note the "replied to" arrow icon.
3. Trigger the transfer to atomic on the site.
4. Leave another comment on the post
5. As the site owner again, check the notifications bar for the comment, and use the in-notification reply feature to post a reply. Note that the "replied to" arrow icon no longer appears.

#### What I expected

I expected the "replied to" arrow indicator to show when I've replied to a comment, making it easy to track which comments I have replied to and which I haven't.

#### What happened instead

The arrow indicator for replied-to comments is not supported on atomic, making it difficult to track which comments a user has replied to across all their post - especially annoying if you receive a lot of comments across many posts.

#### Browser / OS version

Chrome, latest. Windows 10.

#### Context / Source

#21633495-hc #3032838-zen #user-report 

-->

**Comment by zdenys** [comment] 2021-02-20 08:54
Related: https://github.com/Automattic/jetpack/issues/3019

**Comment by obenland** [comment] 2021-03-09 22:33
I'm almost certain this is a duplicate of Automattic/jetpack#3019.

**Comment by sourourn** [comment] 2021-03-15 20:28
Another report here: #28117777-hc

**Comment by dcoleonline** [comment] 2021-07-30 14:49
Another report in #4178909-zen

If we do update this, we should notify the customer.

**Comment by rickmgithub** [comment] 2021-08-01 10:10
User replied with more information related to the last in this thread - #4178909-zen

The full response is in the ticket with a few more details from their testing.

> A few things are still a puzzle, only some comment numbers have appeared in the comment list and no spam at all which is surprising. I used to get stacks, more than one every 15 mins previously. This makes me wonder whether the new way of commenting has stopped some attack spam but is also slowing the system and causing errors. I am mentioning this because about a year ago when I manually introduced a filter to trash this particular spam immediately, it caused a real mess with stuff missing under the bell, and I had to remove it.

**Comment by davipontesblog** [comment] 2021-08-16 20:54
Added to Subscriptions pod for consideration. Please note this is possibly related to this existing Jetpack repo issue from 2015: https://github.com/Automattic/jetpack/issues/3019. It continues to come up with users, though not very often.

**Comment by davipontesblog** [comment] 2021-08-16 20:56
Added priority High as there is no workaround available currently. pciE2j-oG-p2 for internal context.

**Comment by kwight** [comment] 2021-08-17 16:41
We're not likely to get to this for the Subscriptions pod, but I've kept it on our board in case we do. 👍

**Comment by lupus2k** [comment] 2023-01-05 00:42
I created a firts approach to fix this: D97082-code

**Comment by lupus2k** [comment] 2023-01-05 23:39
This issue is fixed and deployed with this diff: D97082-code

**Comment by lupus2k** [comment] 2023-01-06 21:08
Reopened because of a bug in the merged diff: D97082-code
A new code diff fixes it: D97223-code

**Comment by lupus2k** [comment] 2023-01-17 19:03
Fixed on D97223-code

**Closed by lupus2k** 2023-01-17 19:03 UTC
Labels: [Type] Bug, [Pri] High, Notifications, Atomic, Subscriptions, User Report, Triaged, Simple/Atomic Parity
