### ISSUE TITLE
i18n: Localize "Learn more about Privacy Protection"

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#12985] opened 2017-04-11 05:21 UTC
When going through the signup flow or when you try to add a new domain, the "Learn more about Privacy Protection" string is not localized yet.

You can check it here: https://github.com/Automattic/wp-calypso/blob/c67ee054e5d46ee2b79c1d94c3248f068c6a9130/client/my-sites/upgrades/checkout/privacy-protection.jsx#L82

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Change UI to any other language than English (pt-br, in my case)
3. Save changes
4. Visit http://wordpress.com/domains/add
5. Follow the process until you reach the checkout page

#### Screenshot / Video

<img width="741" alt="captura de tela 2017-04-11 as 00 12 29" src="https://cloud.githubusercontent.com/assets/1136160/24893858/e4d643f4-1e4b-11e7-9959-7878f42eab13.png">

#### Context / Source
i18n rotation: #dogfooding, #manual-testing

**Comment by rachelmcr** [comment] 2017-08-15 12:21
Closing this as a dupe of https://github.com/Automattic/wp-calypso/issues/13854.

**Closed by rachelmcr** 2017-08-15 12:21 UTC
Labels: i18n, [Type] Bug, [Type] Good First Change
