### ISSUE TITLE
Group block position: Sticky not responding when set

### ISSUE THREAD

**Issue by brittanygray902** [Automattic/wp-calypso#83129] opened 2023-10-17 21:39 UTC
### Quick summary

User was attempting to make their menu "sticky" with FSE theme Twenty Twenty-Three. I had the user add the navigation block to a Group block and then set that position as "sticky". When the user set the position to sticky the live site did not reflect the changes and menu stayed at top of screen and is scrolled past. 

After that, we tried bringing the group block outside of the Header, and the editor displayed the menu scrolling with the screen as intended - but on the live site the entire menu was gone completely. 

Testing on plugins was performed and deactivating all plugins did not help with sticky menu displaying on the live site. Chat reference: 7180889-zen

### Steps to reproduce

1. Set theme Twenty Twenty-Three
2. Switch menu / navigation block into Group block
3. Set position to "sticky" 
4. Menu should stay at top of page when scrolling

### What you expected to happen

The expected behavior when setting the menu / group block position to sticky, is that it should allow the menu to display and remain at the top of your screen when scrolling through the page. 

### What actually happened

On the users site the menu completely disappeared but was working as intended in the editor, even after all plugins were deactivated to test if they were affecting the live site. 

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

User didn't want to try using CSS - but I'd imagine CSS could be used to fix the menu position, while bug is being fixed.

**Comment by cuemarie** [comment] 2023-10-19 19:56
Hey @brittanygray902 , thanks for the detailed report on this one!

However, it is expected that only top-level groups can be set as sticky. See: https://wordpress.com/support/wordpress-editor/blocks/group-block/#position-settings

> Only top-level groups can be set as sticky. Ensure the Group block is not nested inside any other block for the sticky effect to work. 

If you set the group block that is inside of the Header template part as sticky, then the group will be sticky only within that template part. You might notice this text underneath the sticky setting when setting the child-group-block as sticky:

> The block will stick to the scrollable area of the parent Header block.

<img width="550" alt="screenshot" src="https://github.com/Automattic/wp-calypso/assets/27249804/e77c0d05-9035-4e75-bbc2-906a8b452d7f">

---

📌 FINDINGS/SCREENSHOTS/VIDEO

The right solution is to place the Header Template Part inside of it's own Group block, and make that top-level Group block sticky instead, like this:

![Markup on 2023-10-19 at 12:49:40](https://github.com/Automattic/wp-calypso/assets/27249804/72f47771-b532-40f5-bba8-712851e8bccc)

**Result:**

https://github.com/Automattic/wp-calypso/assets/27249804/3924371a-05cb-4c6b-ac93-19c36dd86cdd

📌 ACTIONS
- Closed as by design

📌 Message to Author
- @brittanygray902 I'd recommend following up with the user by email to have them try placing the Header template part inside a group block instead - that should do the trick.

**Closed as not planned by cuemarie** 2023-10-19 19:56 UTC
Labels: Bug, [Pri] Low, Triaged, Customer report [LEGACY], [Platform] Atomic, [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks
