### ISSUE TITLE
Customizer: Homepage replaced with theme's one without confirmation if `Try & Customize` is used to activate a theme.

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#52012] opened 2021-04-16 10:32 UTC
### Steps to reproduce the behavior

1. Go to https://wordpress.com/themes
2. Click on `...` on any of the visible Block-first themes (e.g. Spearhead)
3. See the modal asking you to either keep the current homepage (`Use X without changing my homepage content.`) which is the option selected by default or replace it with the theme's one (`Use X's homepage content and make my existing homepage a draft.`) 
![](https://d.pr/i/M7E8ko+)
_Link: https://d.pr/i/M7E8ko_
4. Click away and now click `...` and then `Live demo` and then `Try & Customize`
5. Once in the Customizer, click `Activate & Save`
6. See no modal asking for confirmation as in step 3 and the homepage is replaced with the theme's homepage

#### What I expected to happen

- See a modal asking to either keep the current homepage (`Use X without changing my homepage content.`) with the option selected by default or replace it with the theme's one (`Use X's homepage content and make my existing homepage a draft.`)

OR

- At least have a warning about the fact that the homepage will be replaced with the theme's one

OR

- Not have the homepage be replaced, just as it would happen at step 3 where the default option selected is `Use X without changing my homepage content.`

#### What actually happened

The homepage is replaced with the theme's one without a warning

### Context
Manual testing but also observed during Quick Start session. The most recent work that implemented the modal confirmation was done in https://github.com/Automattic/wp-calypso/pull/39700
#### Browser / OS version
Any
#### Is this specific to the applied theme? Which one?
All of these themes https://wordpress.com/themes/filter/auto-loading-homepage
#### Does this happen on simple or atomic sites or both?
So far I tested on Simple Sites
#### Is there any console output or error text?
No
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Medium
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/39308239/115010916-ad14f380-9eb6-11eb-968f-a2752a030622.mov

**Comment by blackjackkent** [comment] 2021-05-24 19:24
@andres-blanco and I did some exploring today to look into this; it seems like, while the themes showcase modal popup is managed by React, the Customize screen "Activate & Save" button is managed entirely by WP Core PHP code. We had a look at the `customizer-fixes.php` and `customizer-fixes.js` files in `mu-plugins` and it seems like we might be able to mimic the functionality there easily enough.

@kwight I'd like to touch base with you tomorrow for your opinions on the best way to execute this; I think there may be existing functionality in trunk that I can build on but so far trying to plug into it is proving a little elusive.

**Comment by kwight** [comment] 2021-05-25 16:58
We discussed this today. The first step would be to see if the WP.com Customizer iframe has a mechanism like `wpcom-block-editor` does, for passing Calypso data back and forth with the iframe. Assuming that doesn't already exist, it wouldn't be worth implementing it from scratch just for this; in that case, the next step would be getting something working using the existing `customizer-fixes` plugin (which will also need to be ported to `wpcomsh` for Atomic to work).

**Comment by blackjackkent** [comment] 2021-05-26 14:41
I looked into the Calypso/wp-admin bridge approach yesterday but it doesn't seem like there's a similar thing already implemented forthe Customizer and as Kirk said, i don't think we have the bandwidth to fully implement that right now. So I'll be working on adding an addition to `customizer-fixes` (in both trunk and wpcomsh) that checks the theme being activated and displays a confirmation dialog.

**Comment by blackjackkent** [comment] 2021-05-26 19:06
Diff opened at D61935-code - I ended up going with option #2 of the three options expressed in the issue for possible expected behaviors here, so the customizer displays a confirmation dialog indicating that the homepage replacement will occur if the user proceeds.

**Comment by sixhours** [comment] 2021-06-02 19:03
We chatted about this in Slack; a quick summary:

* When you "Try & Customize" a theme, you're brought to the Customizer where you'll see your existing content skinned with the new theme. Clicking Activate & Save will save your site AND run the autoloading hompage/template-first themes (TFT) actions to swap your homepage.
* It doesn't make sense to run the TFT actions on save here, because the goal of the Customizer is "what you see is what you get". Rather than adding a warning that things are going to change, we should disable the TFT behavior when saving changes in the Customizer. This reduces confusion and is the least "destructive" behavior.
*  Digging into it, it appears we run TFT on the `switch_theme` hook, which is why it's triggered when you save from the Customizer. I think this means we can check to see if we're in the Customizer and bail on the TFT actions if so; that way the Theme Showcase still offers this functionality, but the Customizer does not.

@blackjackkent Let me know if that make sense or if I missed anything!

**Comment by blackjackkent** [comment] 2021-06-02 19:45
Nope, that covers it. Thank you again for the help/insight, @sixhours !

I'm going to work on building a new diff that short-circuits our custom logic for that hook if the user is on the Customizer.

**Comment by kwight** [comment] 2021-06-09 19:28
Fixed by @andres-blanco in D61935-code

**Closed as completed by kwight** 2021-06-09 19:28 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Low, [Feature] Customizer, [Status] Needs Design, [Feature] Theme Showcase, [Pod] Design Selection
