### ISSUE TITLE
Login to "view site in Reader" from action bar: redirect URL on login page replaces BLOG ID with FEED or POST ID.

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/wp-calypso#61729] opened 2022-03-08 08:43 UTC
### Quick summary

When not logged in on WordPress.com and browsing a site or post, clicking "view this site/post in the Reader" the login page loads up. When it loads up, the redirect URL in [the action bar](https://wordpress.com/support/admin-bar/#action-bar) is incorrect, and so is the "or visit [person's blog]" link.

Essentially the redirect URL and that link are taking the feed ID or post ID and putting it where the blog ID should be.

### Steps to reproduce

1. Start at any WordPress.com-hosted Simple site and view an individual post, while not logged in, eg: wordpress.com/blog/ (feed ID 25823)
2. Click Action Bar > View site in Reader  [leads to `https://wordpress.com/read/feeds/25823` for wordpress.com/blog/]
3. Redirect URL on login page looks incorrect (but it does redirect correctly on login)
4. "Or visit" link goes to incorrect place.

Screenshot:
![feedidasblogid](https://user-images.githubusercontent.com/36608681/157198014-d776cf0d-baaf-4719-989d-dd80c82bc6c6.png)

Link from that screenshot is `https://conocimientos.wordpress.com/` (blog ID 25823)

OR

1. Start at any WordPress.com-hosted Simple site and view an individual post, while not logged in, eg: wordpress.com/blog/2022/02/28/celebrating-black-history-month/ (post ID 45907)
2. Click Action Bar > View post in Reader  [leads to `https://wordpress.com/read/blogs/3584907/posts/45907` for wordpress.com/blog/2022/02/28/celebrating-black-history-month/]
3. Redirect URL on login page looks incorrect (but it does redirect correctly on login)
4. "Or visit" link goes to incorrect place.

Screenshot:
![postidasblogid](https://user-images.githubusercontent.com/36608681/157198946-ce47e0cf-3dd8-4e43-9082-ab3f7e61e955.png)

Link from that screenshot is `bWr-p2`(blog ID 45907)

I'm also not too sure why viewing a site in the reader would lead to `https://wordpress.com/read/feeds/FEEDID` while viewing an individual post in the reader goes instead to `https://wordpress.com/read/blogs/BLOGID/posts/POSTID`, but I'm guessing there's a good reason for that.

### What you expected to happen

The redirect/or-visit links should not substitute the feed (for a site) or post (for an individual post) ID for the blog ID.

### What actually happened

Logging in does redirect me to the right place.  But it looks jarring and surprising for visitors to find a suggestion to visit a site that's totally unrelated to the one they wanted to browse in the Reader.

I'm not sure how to class the impact of this - it is reproducible and clearly something in Calypso/the action bar (or the relationship between them) but it's not like this is breaking site usability - after logging in I'm correctly directed anyway. It's more a cosmetic(?) issue, I think.

### Context

User report 4840980-zen

### Simple, Atomic or both?

Simple

### Browser, operating system and other notes

Mac OS 11.6 (I know, I know)
Firefox 96.0.3

### Reproducibility

Consistent

**Comment by formosattic** [comment] 2022-03-15 08:30
Thanks @sophiegyo , the second example made it easy to reproduce!

To summarize, with this example:

* Link https://wordpress.com/blog/2022/02/28/celebrating-black-history-month/
* Blog ID: 3584907 
* Post ID: 45907

The redirect link is:

* [https://wordpress.com/log-in?site=**45907**&redirect_to=%2Fread%2Fblogs%2F3584907%2Fposts%2F**45907**](https://wordpress.com/log-in?site=45907&redirect_to=%2Fread%2Fblogs%2F3584907%2Fposts%2F45907)

But what is expected is:

* [https://wordpress.com/login?site=**3584907**redirect_to=%2Fread%2Fblogs%2F3584907%2Fposts%2F**45907**](https://wordpress.com/log-in?site=3584907&redirect_to=%2Fread%2Fblogs%2F3584907%2Fposts%2F45907)

**Comment by roo2** [comment] 2022-04-13 03:57
very interesting, so the `site` parameter is used to add the page subtitle "_or visit $site_title_" but because we pass the post id instead of the blog id, we get an essentially random other persons blog in that subtitle 😂 "_or visit **Pixie on the net**_"

Ganon has some new devs starting in the next few weeks. This looks like a good issue to save for them.

**Comment by arthur791004** [comment] 2022-06-30 04:58
Close it as https://github.com/Automattic/wp-calypso/pull/65072 is shipped 🚢

**Comment by caimin-j** [comment] 2022-09-26 07:52
This issue seems to be be back. I got the message below when trying to view a post with the ID 2391 (the ID of Outside The Box is also 2391).

<img width="352" alt="Screenshot 2022-09-25 at 10 44 30" src="https://user-images.githubusercontent.com/37620825/192222570-ff271ec8-2bc3-466e-a10b-ca8b368e56dd.png">

**Comment by arthur791004** [comment] 2022-09-26 11:03
@caimin-j I tried to reproduce the issue via accessing [View site in Reader](https://wordpress.com/read/feeds/109971660) but I saw the screenshot below and it linked to the original site correctly.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/13596067/192260590-38eee913-a5eb-4d3b-a01a-756648d9b031.png">

Could you provide the link for that screenshot? thanks!

**Comment by caimin-j** [comment] 2022-09-26 13:30
@arthur791004 No worries :) This is the link I followed:

https://wordpress.com/post/INTERNALDOMAIN/2391

...which redirects me to:

https://wordpress.com/post?site=2391

_(edited after getting a Slack auto ping)_

**Comment by arthur791004** [comment] 2022-09-27 11:13
@caimin-j thanks! Could you also help to get the link from customers? I saw the link of the screenshot in that ticket starts with `/read/feeds/...` (see the `redirect_to` in the URL). I think this issue is highly related to the URL, so we might need to collect all possible links. Otherwise, the customers might encounter the same issue again with a different URL.

**Comment by arthur791004** [comment] 2022-10-03 10:48
Oooops! I got the reason why I cannot reproduce the issue mentioned in 4840980-zen as its original issue of this ticket and it had been resolved on [Jun 30](https://github.com/Automattic/wp-calypso/issues/61729#issuecomment-1170764027)...

As a result, https://github.com/Automattic/wp-calypso/issues/61729#issuecomment-1257637926 is another issue when the user lands on `https://wordpress.com/post/<not-your-site>/2391`.

**Comment by autumnfjeld** [comment] 2022-10-04 01:19
> As a result, https://github.com/Automattic/wp-calypso/issues/61729#issuecomment-1257637926 is another issue when the user lands on https://wordpress.com/post/<not-your-site>/2391.

@arthur791004 @caimin-j  Should we close this and open a new issue?

**Comment by arthur791004** [comment] 2022-10-04 07:08
I'm okay with both as the new issue is still related to “replaces BLOG ID with FEED or POST ID”

**Comment by arthur791004** [comment] 2022-10-12 02:21
@caimin-j I think the issue has been fixed, could you kindly help to check again? thanks!

**Comment by caimin-j** [comment] 2022-10-12 08:42
@arthur791004 Just tested: it's working as expected now. Thanks!

**Comment by arthur791004** [comment] 2022-10-12 12:29
👍

**Closed as completed by arthur791004** 2022-10-12 12:29 UTC
Labels: Bug, [Pri] Low, Triaged, V13n Build Flow
