### ISSUE TITLE
Gutenberg in Calypso: switching to block editor as contributor creates console error

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#29217] opened 2018-12-07 06:31 UTC
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/posts as contributor user using classic editor
2. Use switch to new editor
3. Check browser console

#### What I expected

No errors

#### What happened instead

Console error: `Unhandled Promise Rejection: ForbiddenError: Sorry, you are not allowed to create posts as this user.`

#### Browser / OS version

Safari macOS

**Comment by kwight** [comment] 2018-12-12 21:53
@alisterscott I was unable to replicate this; are you still seeing it? (I _did_ see the "No Content-Disposition" [mentioned elsewhere](https://github.com/Automattic/wp-calypso/pull/28743#issuecomment-440784371) that's unrelated).

**Comment by kwight** [comment] 2018-12-12 23:53
Oh! I can see it now 👍

**Comment by kwight** [comment] 2018-12-13 00:01
Related: #29213

**Comment by kwight** [comment] 2018-12-14 22:07
@alisterscott out of curiosity, does the failing user have either a) an automattic.com email, or b) an unverified email? Can you DM me the username?

**Comment by kwight** [comment] 2018-12-14 23:37
Noting that functionality (in spite of the warning) seems fine and as expected (a contrib can submit for review and have that post successfully published by an admin).

**Comment by obenland** [comment] 2019-03-12 21:19
With Gutenframe I couldn't reproduce that error, I received another one instead:
> Unhandled promise rejection ForbiddenError: "You do not have the capability to manage settings for this site."

**Comment by retrofox** [comment] 2019-03-12 21:25
I haven't seen any error. Tested with FF, contributor user.

![swtiching-editor ](https://user-images.githubusercontent.com/77539/54237174-99765200-44d2-11e9-99c8-9ad3585a8622.gif)

**Comment by kwight** [comment] 2019-03-12 22:30
I don't see this anymore either, closing.

**Closed by kwight** 2019-03-12 22:30 UTC
Labels: [Goal] Gutenberg, [Pri] Low, [Type] Bug
