### ISSUE TITLE
Jetpack: can't access sites where URL matches an old mapped WordPress.com site

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#6779] opened 2016-07-14 14:00 UTC
I believe this is a fairly recent issue, the following used to work, at least up until a week ago:
#### Steps to reproduce
1. Start by creating a WordPress.com site.
2. Add a domain mapping to that site, to map it to a domain you already own.
3. You can now access this site's settings in Calypso using the new mapped URL in the Calypso URL.
4. Change the domain's NS records to point the domain to a new hosting provider.
5. Create a new site on that host, and install WordPress.
6. Install and activate Jetpack.
7. Up until very recently, you were then able to access that site's settings in Calypso using the site URL in the Calypso URL.
8. Right now, however, that site URL loads the old WordPress.com site settings.

A good example is blog ID `94957111`, that now loads settings from `33644320`.

**Comment by lancewillett** [comment] 2016-09-02 16:42
More discussion here: p7rcWF-6N-p2

**Comment by kristarella** [comment] 2016-09-27 07:30
Also have this issue for sites where the domain is registered with us and then the user moves to Jetpack site. 
Reported in 472831-chat

**Comment by jeherve** [comment] 2016-09-28 09:16
More discussion here: p2MSmN-5rU
-p2

**Comment by lancewillett** [comment] 2016-10-10 17:15
This is still pending a fix on the domains API side, on WordPress.com.

**Comment by designsimply** [comment] 2017-04-14 18:06
Tested and confirmed that I cannot access a Jetpack site if I setup a mapped domain there and then move to a Jetpack setup.

* WP.com site: madefortesting347 (Blog ID 105644731)
* Pressable site: watchingstormsrollby.me (Blog ID 127398684)

These posts actually belong to the madefortesting347 WP.com site:

<img width="1280" alt="screen shot 2017-04-14 at fri apr 14 12 02 59 pm" src="https://cloud.githubusercontent.com/assets/1119271/25051605/cadeb802-210a-11e7-9abe-5c656212a3fb.png">
<sup>Seen at https://wordpress.com/posts/watchingstormsrollby.me using Firefox 52.0.2 on Mac OS X 10.12.4 logged in as user157 unproxied.</sup>

These are the posts I expected to be able to see in calypso for watchingstormsrollby.me:

<img width="1280" alt="screen shot 2017-04-14 at fri apr 14 12 05 26 pm" src="https://cloud.githubusercontent.com/assets/1119271/25051610/cee79784-210a-11e7-9199-1e75aeefb2d1.png">
<sup>Seen at https://watchingstormsrollby.me/wp-admin/edit.php using Firefox 52.0.2 on Mac OS X 10.12.4 logged in as watchingstormsrollby via Pressable.</sup>

**Comment by lezama** [comment] 2017-04-17 17:40
@enejb has been working hard 
https://poseidonp2.wordpress.com/2017/02/25/calypso-fixing-the-the-domain-to-blog_id-mapping-issue-server-side-issue-continued/ on fixing this one, not sure what happened in this particular case

**Comment by enejb** [comment] 2017-05-08 21:43
I create a PR that addressed this issue on the calypso side. @designsimply can you test it and see if it work for you as expected?

**Comment by designsimply** [comment] 2017-05-08 22:43
I checked http://calypso.localhost:3000/posts/watchingstormsrollby.me with the `update/use-blog_id-in-api-requests` branch applied and the correct posts appear ("Test Post" and "Storm Watching"). LGTM

![screen shot 2017-05-08 at mon may 8 4 33 42 pm](https://cloud.githubusercontent.com/assets/1119271/25828218/3fcece90-340c-11e7-9955-e891d75c6240.png)
<sup>Seen at http://calypso.localhost:3000/posts/watchingstormsrollby.me using Firefox 53.0 on Mac OS X 10.12.4 logged in as user157 and unproxied.</sup>

In comparison, I see incorrect posts when testing the same url at https://wordpress.com/
![screen shot 2017-05-08 at mon may 8 4 08 46 pm](https://cloud.githubusercontent.com/assets/1119271/25828346/f3971504-340c-11e7-9756-3fb557bb5647.png)
<sup>Seen at https://wordpress.com//posts/watchingstormsrollby.me using Firefox 53.0 on Mac OS X 10.12.4 logged in as user157 and unproxied.</sup>

The only point of confusion I can see from here is that the watchingstormsrollby.me domain is managed at `/domains/manage/madefortesting347.wordpress.com` and not `/domains/manage/watchingstormsrollby.me` (which results in a "Domains are not available for this site." error). Does this point of confusion belong with this issue or should a new issue be created after 13670 is shipped?

**Comment by jeherve** [comment] 2017-05-12 16:36
Also reported here:
https://wordpress.org/support/topic/jetpack-stats-dont-work-in-the-wordpress-com-dashboard/

**Comment by benchilcote** [comment] 2017-05-17 17:53
Reporting another possible case for emmaeatsandexplores.com. 
Following up here: https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=3217690
Original Chat: https://mc.a8c.com/support-stats/happychat/transcript.php?id=386006

**Comment by VR51** [comment] 2017-05-18 20:46
And several more cases to report of Jetpack stats no longer displaying in the dashboard. Also, popular posts appear to have vanished from some affected sites.

**Comment by designsimply** [comment] 2017-05-22 23:05
@VR51 this issue is very specifically about Jetpack sites which were previously using a mapped domain at WordPress.com and had migrated to Jetpack setups in the past. For Jetpack stats not displaying in general, I think #14253 was probably the more relevant issue and has already been fixed. If the other case you mentioned where popular posts appear to have vanished is still happening, can you please report that at https://en.forums.wordpress.com/ and tag it with "modlook" and include a specific example if possible? Thank you!

**Comment by aheckler** [comment] 2017-05-23 15:02
Another case in 3219594-t with `godtiglasset.com`, similar to @kristarella's example where the domain is reg'ed with WP.com but they've moved to a JP site.

**Comment by csonnek** [comment] 2017-05-26 18:32
Another case in 3223599-t for `chasingskinnyblog.com` - same factors (domain registered at wpcom and moved to a JP site). Logged in as the user to verify.

**Comment by aheckler** [comment] 2017-05-29 20:06
3232720-t

**Comment by kristarella** [comment] 2017-06-01 11:17
I have seen 4 more instances of this. Sorry, I don't have the ticket numbers right now, let me know if you need me to find them. 3 were for wpcom sites that used to be Jetpack sites, one for a Jetpack site that used to be wpcom. All customers came to us saying they were unable to create a post because when they tried to choose their site it would just go back to the site chooser.

I tested it and recorded the results here:
https://cloudup.com/cdmISFRHzTp

I was able to access the Jetpack site, but not the wpcom site that had the same domain mapped.

**Comment by designsimply** [comment] 2017-06-02 16:12
@kristarella ticket numbers would be great if you can get them!

**Comment by designsimply** [comment] 2017-06-02 16:21
@csonnek I fixed chasingskinnyblog.com manually by adding the `has_matching_jetpack_domain	` sticker via the blog report card (under the "Primary Domain Fix" section). It's no longer a good test case for this bug because of that, but it should be working now.

**Comment by designsimply** [comment] 2017-06-02 22:01
@aheckler, for 3219594-t, godtiglasset.com has been fixed by toggling the "has matching jetpack domain" setting on the blog report card.

**Comment by designsimply** [comment] 2017-06-02 22:28
@benchilcote, I checked emmaeatsandexplores.com just now and it appears to be working normally.

**Comment by aheckler** [comment] 2017-06-13 18:30
@tyxla Looks like the fix was merged? I am still seeing this happen in 3262620-t.

**Comment by csonnek** [comment] 2017-06-13 20:34
Replied to `chasingskinnyblog.com` to let her know it's been fixed.

**Comment by tyxla** [comment] 2017-06-13 23:12
It was merged, then reverted because it was breaking a test. We are doing another try to merge it tomorrow. @aheckler @csonnek

**Comment by tyxla** [comment] 2017-06-14 11:18
#15048 and #14685 have just landed as separate approaches to fix the issue and reduce the chance for it to happen, so I'm closing this one. Feel free to reopen if any cases of it pop up again. Special kudos to @enejb, @lezama and @aduth for all of the hard work with both of these!

@aheckler @csonnek @kristarella @benchilcote @VR51 it would be great if you can give the sites from your tickets another try - thanks in advance!

**Closed by tyxla** 2017-06-14 11:18 UTC
Labels: Jetpack, [Pri] High, [Type] Bug

**Comment by aheckler** [comment] 2017-06-14 19:46
All tickets and forums threads have now been replied to if needed.
