### ISSUE TITLE
Settings: Cannot add values to "Disallowed comments"

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#47844] opened 2020-11-29 20:12 UTC
Possibly related to #47840

#### Steps to reproduce

1. Starting at URL: https://wordpress.com/settings/discussion/example.wordpress.com
2. Add term(s) to "Disallowed comments"
3. See success message
4. Refresh and the terms have been removed

This issue is also present with the synced field Comment Blocklist in WP Admin. If an existing list is edited it is also lost with no way to recover the terms. Since I imagine some users have curated this over time I am marking this as high priority cc @cathymcbride 

#### What I expected

To be able to add terms to "Disallowed comments"

#### What happened instead

The values cannot be saved.

**Comment by KristinaKay** [comment] 2020-11-29 20:59
Just coming to create a Bug Report for this! Thanks @kriskarkoski 

Here is another case: #3526322-zen

**Comment by fstath** [comment] 2020-11-30 17:01
Another report in the forums:
https://wordpress.com/forums/topic/empty-comment-blocklist/

**Comment by khristiansnyder** [comment] 2020-12-01 16:14
Another case in #3530164-zen and I can confirm on my test site as well that I cannot save any comment moderation blocklists in Calypso or WP-Admin.

**Comment by mmtr** [comment] 2020-12-02 11:13
This is a regression introduced by https://github.com/Automattic/jetpack/pull/17820, where the already deprecated `blacklist_keys` option was removed in favor of the new `disallowed_keys` option. cc @jeherve 

Calypso still uses the `blacklist_keys` option: https://github.com/Automattic/wp-calypso/blob/e476e50a5159defecd1744d439ab86045248dba3/client/my-sites/site-settings/form-discussion.jsx#L535-L545

**Comment by mmtr** [comment] 2020-12-02 11:32
I think we need to add back the `blacklist_keys` option to the site endpoint, since WP.com still uses it (the migration to `disallowed_keys` was intentionally left out of the core merge 5.5 in D47633-code).

**Comment by mmtr** [comment] 2020-12-02 12:12
~Fix ready for review: D53617-code.~

Just realized that we have some compatibility hacks in place that makes possible to use the new options as an alias of the legacy ones.

Due to that, I think it'd be better if we simply update Calypso to use the new names: https://github.com/Automattic/wp-calypso/pull/47954

**Comment by KokkieH** [comment] 2020-12-03 05:29
@mmtr I checked the site of the user in https://wordpress.com/forums/topic/empty-comment-blocklist/, and their blocklist is still empty. Is there any way to recover the blocklist terms that were wiped out due to this?

**Comment by mmtr** [comment] 2020-12-04 11:05
@KokkieH I took a look and couldn't identify yet why their blocklist is empty. The issue here was preventing to make changes to the blocklist terms, but it shouldn't have removed them. They reported the issue shortly after the legacy options were removed from the site API endpoints (r217404-wpcom, r217406-wpcom) but I don't see the relation yet.

@jeherve do you have any idea of what happened?

I'm going to take a look at the audits and logs for their site, and see if I'm able to determine when the blocklist terms were removed.

**Comment by mmtr** [comment] 2020-12-04 12:33
> I'm going to take a look at the audits and logs for their site, and see if I'm able to determine when the blocklist terms were removed.

Unfortunately I didn't find any log where we can check blog options changes. Do HEs use any tool for debugging them?

**Comment by mmtr** [comment] 2020-12-04 12:45
Alright, just found the issue. I only focused on the blocklist management from Calypso, which has the issue I mentioned above (users couldn't change them) and was fixed by #47954.

However, the blocklist terms can be managed in WP Admin as well, and the issue is different there: any change ends up with the list of terms completely removed. I think this needs coordination with the systems team given this is caused by the upgrade to Core 5.5, so I'll let them know. cc @david-binda

**Comment by mmtr** [comment] 2020-12-04 13:05
p94tqY-nv-p2

**Comment by KokkieH** [comment] 2020-12-04 13:53
Thanks for digging into it :)

**Comment by mmtr** [comment] 2020-12-04 14:30
I prepared a fix for the WP Admin side in D53769-code. Unfortunately it won't recover the lost data, it will only prevent the issue from happening again. 

Let's see if systems can come up with a way of restoring it.

**Comment by cathymcbride** [comment] 2020-12-04 18:13
@mmtr since this issue is fixed, and recovering the lost data is a separate task, can we keep this closed and log a new issue for systems to restore it?

**Comment by mmtr** [comment] 2020-12-07 09:20
D53769-code has been deployed, so the issue shouldn't occur anymore.

To recap, lost data was only happening on sites where the terms have been updated via WP Admin. Updates done via Calypso didn't result in lost data.

Regarding the restore, our systems team believes that the only option would be to get a backup for affected sites and restore those manually. You can report the affected sites in p94tqY-nv-p2

@cathymcbride not sure if I need to open a new issue in that case.

**Closed as completed by mmtr** 2020-12-07 09:20 UTC
Labels: Bug, [Feature] Site Settings, [Pri] High

**Comment by cathymcbride** [comment] 2020-12-07 18:01
@mmtr agreed. I don't think so either. Thank you!
