### ISSUE TITLE
Purchases: Give some indicator of progress when updating a credit card

### ISSUE THREAD

**Issue by peterbutler** [Automattic/wp-calypso#6246] opened 2016-06-22 20:46 UTC
When updating a credit card for a subscription, upon hitting "Save Card", there's  no indication that anything is happening, leading many users to believe that nothing is happening - leading them to submit several times. 

See below: 
![card-update-interaction](https://cloud.githubusercontent.com/assets/331500/16282891/d7157262-3887-11e6-9c3d-862c40c0fa37.gif)

(note: credit card number used above is not valid)

Note that I'm able to edit the card details, get other error messages, etc, while the submission is happening, before receiving the real error message.

We should indicate that the details are being submitted at the very least, and ideally also prevent further interaction with the form while waiting for a response.

**Comment by fabianapsimoes** [comment] 2016-06-23 08:51
Duplicate of https://github.com/Automattic/wp-calypso/issues/221.

**Closed by fabianapsimoes** 2016-06-23 08:51 UTC
Labels: Checkout, Purchases
