### ISSUE TITLE
Domain Transfers: Cancel transfer button confusing or incorrect

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#20271] opened 2017-11-28 01:18 UTC
During a transfer, on the domains settings screen there is an action that says "Cancel Transfer". However when clicking on it it takes you to the purchases screen where there is no action.

I'm not certain what is the proper flow here. Should you be able to cancel at this point? If so, then we need to fix this screen and provide a proper cancel flow:

![image](https://user-images.githubusercontent.com/12596797/33297600-f4dae5ce-d3af-11e7-92ee-3c7a52d533fb.png)

cc @danhauk @aidvu

**Comment by klimeryk** [comment] 2017-11-28 10:46
Had the same happen to me during testing - not sure what are the steps to reproduce, IIRC @aidvu could not reproduce it on his account?

**Comment by mikeshelton1503** [comment] 2017-11-28 14:50
**Steps to reproduce:**
- Start a domain transfer. Go all the way through the purchase process, but don't complete the transfer yet.
- Go to Domains, click on the domain you're transferring (it should have the notices associated with it).
- Click on "Cancel Transfer".
- Observe grayed out purchase details with no actions (the screenshot above).

**Comment by danhauk** [comment] 2017-11-28 15:00
This bug is also showing up for me. Even going directly to the purchase in `/me/purchases`. But mine isn't grayed out.

![image](https://user-images.githubusercontent.com/448298/33326428-f252c0c4-d422-11e7-8ef5-9c2e56dc6a3d.png)

**Comment by aidvu** [comment] 2017-11-28 15:02
It's a weird one related to the expiration date. Have a back end fix already.

**Comment by aidvu** [comment] 2017-11-28 15:28
Merged. Please recheck this one. :)

**Comment by mikeshelton1503** [comment] 2017-11-28 16:40
I now see what Dan's screenshot shows above. IT's not grayed out anymore but there no option to actually cancel it.

**Comment by aidvu** [comment] 2017-11-28 16:41
Ahhh, now I get it. I disable the button if not cancellable. :) I should also hide the button on the domain management screen?

**Comment by mikeshelton1503** [comment] 2017-11-28 16:48
Yep that's the confusion. If it's not possible to cancel we should not offer the option anywhere.

**Comment by danhauk** [comment] 2017-11-28 19:46
@aidvu At what point can I cancel a transfer? If I just purchased a domain transfer why is it not possible to cancel it?

**Comment by aidvu** [comment] 2017-11-28 20:37
Credit purchases aren't cancellable or refundable. @danhauk is that your case?

**Comment by danhauk** [comment] 2017-11-28 21:19
@aidvu Yep, that would be it. Probably the case for @mikeshelton1503 too?

**Comment by GeoJunkie** [comment] 2017-12-06 12:02
I'm having this problem, too. I went all the way through the process with queerderbytaco.com. Paid  credit card. I inadvertently hit the "cancel" instead of "approve" link on the final approval email from the other registrar (after approving on the WordPress end - bad layout on the losing registrar). So I wanted to cancel the transfer on the WP end, but when I go, I just get taken to the transfer purchase  page with no option to cancel (see attached)
![2017-12-06 07_01_51](https://user-images.githubusercontent.com/7596032/33660855-62e33234-da53-11e7-9009-462b7c6e0918.gif)

**Comment by KokkieH** [comment] 2017-12-07 13:16
> Credit purchases aren't cancellable or refundable

If purchased as part of a plan, shouldn't it be cancellable and the plan domain credit restored, to allow for the plan domain credit to be re-used for a different domain if the transfer can't proceed? I know that's not how it works for regular registrations and mappings, and once the transfer is complete it shouldn't be possible to cancel the domain without cancelling the plan. But while the transfer is in progress there is specifically an option to stop the transfer even after it's been confirmed on our end, so I'd expect the upgrade to subsequently be removable.

And even if purchased with regular credits and/or not connected to a plan, it should be possible to cancel and remove the upgrade like it's possible with stand-alone domain upgrades.

I have a domain where I cancelled the transfer from the losing registrar's end after initiating and confirming, and now that transfer is essentially stuck. I can't restart the transfer, but can't remove it either.

**Comment by aidvu** [comment] 2017-12-09 02:17
Yep, working on it @KokkieH. Should have a fix. :)

**Closed** 2017-12-12 00:29 UTC
Labels: Domains, [Type] Bug
