### ISSUE TITLE
Image Block: Legacy Div Impacting Images on Editor

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#72973] opened 2023-02-03 20:48 UTC
### Quick summary

Images added to older posts are loading really small in the editor, but correctly on the live site.

### Steps to reproduce

I wasn't able to replicate the issue, since it seems to happen on older posts. From the user's site, we can see that the Image blocks with the issue were starting with `<div class="wp-block-image">`, which doesn't seem to be added these days anymore. So all posts with this DIV code show images really small in the editor, but full width on the site.

Here's how it looks like on the user's posts in the editor (it's a mockup):

![Image-Issue](https://user-images.githubusercontent.com/16104522/216706938-5b251023-e2ba-412b-b6d5-f186f983a78d.png)

### What you expected to happen

That the images load correctly in the editor.

### What actually happened

Because of that DIV, they load really small in the editor.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Logs or notes

The workaround is to edit the post, open the Code Editor, and go back to the Visual Editor, this seems to fix whatever is wrong with the code, and render the images correctly.

Reported on 5922820-zd-woothemes

**Comment by cuemarie** [comment] 2023-03-21 20:11
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Could Not Replicate**
- Tested on AT: **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Was not able to replicate this issue.  Tried wrapping images in the `<div class="wp-block-image">` syntax, but this only moved the image to a Classic Block, and did not cause any size changes in the editor.

**AT Example**

https://user-images.githubusercontent.com/27249804/226729006-a76cbdd1-6e92-4b27-aa5b-49c7f61055a7.mp4

---

**Simple Example**

Also tried wrapping the entire `<figure>` in the `<div>`, but this lead to the same result:

![Markup on 2023-03-21 at 13:06:42](https://user-images.githubusercontent.com/27249804/226729053-9544e66f-0dcf-4318-bffc-7902e8316f11.png)

![Markup on 2023-03-21 at 13:06:55](https://user-images.githubusercontent.com/27249804/226729144-62226b05-6d93-492b-b1b3-a045ebce87c3.png)

I also tried checking out the posts from the user's ticket, but saw no images there that were improperly sized (this may be due to the workaround recommended).

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- @carinapilar if you can replicate this, please let me know what steps I might be missing here!  Feel free to reopen if we can determine how to replicate. Thanks!

**Comment by carinapilar** [comment] 2023-03-22 12:36
Hey @cuemarie! I wasn't able to replicate this issue back then, it seemed to be an issue with how the editor was rendering old content, so my guess was that a dev team would be able to investigate this further and fix it. It seems it was a temporary bug though, I found on the user's site other old posts that still have the DIV (from Aug 2020), here's what it looks like on the live site:

![div-image-block](https://user-images.githubusercontent.com/16104522/226903381-76de7fc3-17ce-47ba-9a1b-edced001aad6.jpg)

The editor now only adds that `figure` tag for new content, and posts that have the images with that "wrong" `div` are loading fine in the editor now. 😌

**Comment by cuemarie** [comment] 2023-03-30 14:07
Thanks for that additional info, @carinapilar ! To clarify, in the content from your screenshot, the problem is still happening, right? (Wanted to make sure I didn't misunderstand what you meant by a temporary bug)

**Comment by carinapilar** [comment] 2023-03-31 11:10
@cuemarie, even though the old posts still have the `div` code that was causing the issue, the editor seems to have been fixed, so it's properly showing the images, it looks all set now! 🙌

**Closed as completed** 2023-04-05 17:19 UTC
Labels: Bug, [Pri] Low, Triaged, [Closed] Not Reproducible, Images
