### ISSUE TITLE
Editor: Contact Form: Edit button is missing hover text

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#4116] opened 2016-03-17 03:43 UTC
#### Steps to reproduce
1. Open editor where new contact form is enabled (eg. calypso.localhost:3000 on branch)
2. Insert contact form via toolbar
3. Hover over edit icon

#### What I expected

Hover text

#### What happened instead

No hover text

#### Browser / OS version

Chrome  49.0.2623.87 & Firefox 45.0 on OSX 10.11.2

#### Screenshot / Video

![hover text](https://cloud.githubusercontent.com/assets/128826/13835694/2b8f414e-ec46-11e5-972f-4ff6c4174998.gif)

**Comment by hoverduck** [comment] 2016-05-12 19:15
12May16 Bug Scrub

Confirmed this is still an issue.

It looks like the remove button is a full component named `ContactFormDialogFieldRemoveButton`, which has a `Popover` as a sub-component.  The pencil icon is just a standalone `<button>` element with a `Gridicon` component inside.

**Comment by hoverduck** [comment] 2016-08-23 18:46
#bug-scrub

Confirmed this is still an issue.  I'm adding the `Good First Change` label, since this seems like it should be an easy fix.

**Comment by gwwar** [comment] 2016-09-07 23:18
Just FYI that this doesn't seem like a good first change. I took a quick look and this will either mean updating the foldable card to accept arbitrary popover values, or perhaps require creating a generic button/popover component to pass through as a child in the foldable card

**Comment by hoverduck** [comment] 2016-09-20 22:09
This was fixed by #7938

**Closed by hoverduck** 2016-09-20 22:09 UTC
Labels: Editor, [Pri] Low, [Type] Bug
