### ISSUE TITLE
Store: bug in checkout flow

### ISSUE THREAD

**Issue by rralian** [Automattic/wp-calypso#4230] opened 2016-03-22 20:59 UTC
I was testing out the checkout flow for a premium theme to see if there was a good place for a plans upgrade in that process, and I ran into a fatal error. I opened the console and it looks like we have an unhandled error. Possibly when you have conflicting items in your cart. But the result was that the content of the page never loaded.

![premium theme checkout](https://cloudup.com/cAqeXfIZc1H+)

I'm not sure where this one lands... maybe @gziolo could point in the right direction? I'm attaching to our current milestone just to track it for now, but hoping store team can steal it from us?

**Comment by gziolo** [comment] 2016-03-23 07:28
I'm moving it to Gold backlog. I'm going to work on it today :)

**Comment by gziolo** [comment] 2016-03-23 12:17
I was able to reproduce this bug. There are two issues that need to be fixed caused by the fact that as part of business plan you get also unlimited themes:

* when there is a premium plan in your cart we shouldn't add any premium theme to the cart
* when there is a premium theme in your cart we should remove it once we add business plan to the cart

In both cases we should display some information to the user.

/cc @breezyskies @peterbutler

**Comment by janm6k** [comment] 2016-03-24 15:58
Reviewed and deployed both backend patches. Good job!

**Comment by rralian** [comment] 2016-03-24 17:36
Thanks for running with this @gziolo (and reviewing the backend @janm6k)!

**Comment by janm6k** [comment] 2016-03-25 17:48
D1415 was reverted, we have missed that it caused removing domains when plan was added :(

**Comment by janm6k** [comment] 2016-03-25 18:01
code-D1441 has updated version of the fix.

**Comment by janm6k** [comment] 2016-03-31 14:31
code-D1441 deployed again, thanks @gziolo for tests!

**Closed by janm6k** 2016-03-31 14:31 UTC
Labels: Checkout, [Type] Bug
