### ISSUE TITLE
Empty comments can't be deleted

### ISSUE THREAD

**Issue by davoraltman** [Automattic/wp-calypso#18197] opened 2017-09-23 08:32 UTC
The user reached out in 698378-zd reporting that there are empty comments they can't delete via calypso. The workaround is to delete them via WP Admin.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/comments/trash/39014270
2. There's an empty blinking comment which can't be deleted

http://cld.wthms.co/qNQ1c6

#### What I expected

I should be able to delete the comment.

#### What happened instead

I am not able to delete it.

#### Browser / OS version

Latest version of Chrome on Mac 10.12.6

**Comment by Copons** [comment] 2018-03-23 16:12
This is likely related to a bunch of corner cases where the `comments-tree` endpoint returned some incorrect comments for a variety of reasons.
If I recall correctly, we eventually got around to fix this issue, but anyway since then we also moved back to the `comments-list` endpoint which should be safe from this kind of problems.

I'm going to close this issue for now since I can't reproduce it (the site has no empty comments right now), but feel free to ping @Automattic/lannister if something else related to comments pop up again. 🙇

**Closed by Copons** 2018-03-23 16:12 UTC
Labels: Comments, [Type] Bug
