### ISSUE TITLE
No Jetpack Connection on Newly Created Staging Site

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/wp-calypso#82544] opened 2023-10-03 18:43 UTC
### Quick summary

After creating a Staging Site I'm unable to install plugins. Navigating to the Plugin Upload page shows the message

`Installation in progress. Just a minute! Please wait until the installation is finished, then try again.`

Followed by `To continue you'll need to` with no listed next steps.

<img width="400px" src="https://github.com/Automattic/wp-calypso/assets/42279181/4e6f701b-3d2a-411e-985b-94846559071e">

This appears to be happening because Jetpack isn't connected, and is reporting a token health issue.

<img width="400px" src="https://github.com/Automattic/wp-calypso/assets/42279181/8013615e-ad43-40f6-96ee-1890e09875b7">

### Steps to reproduce

1. Start at Settings > Hosting.
2. Create a new staging site.
3. Click on `Manage staging site`.
4. Navigate to Plugins, and select `Upload`.
5. See error message.

### What you expected to happen

For the staging site to "just work" with an active Jetpack connection, so I'm able to install plugins.

### What actually happened

I get an error message on the plugin upload page with no indication of next steps. The site was created 10+ minutes ago, and I still get the error after refresh.

It seems that there's no Jetpack connection to the site, which is the root cause of the error. 

### Impact

One

### Available workarounds?

No and the platform is unusable

### Logs or notes

Related Issues:
- p1696177512930139-slack-C03TY6J1A
- p1694439325851659-slack-C03TY6J1A

**Comment by katiebethbrown** [comment] 2023-10-03 18:45
Looking at the RC, it seems that the connection tried to auto-heal before the user was added to the site. Without the user on the site it fails and says manual intervention is required.

Slack thread w/ details and RC link:
p1696358528178299/1696358049.701289-slack-C03TY6J1A

**Comment by cuemarie** [comment] 2023-10-03 19:03
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Tried replicating on a 1-week old Atomic test site, and the issue did not occur - the staging site was created smoothly, with no user token issues logged in BRC

📌 ACTIONS
- Downgrading to `Normal` for now as this 🤞 hopefully was a rare misstep in the creation process

**Comment by Nic-Sevic** [comment] 2023-11-22 09:37
I'm not 100% that this is the same issue but it sounds similar to p1700644455642249-slack-C03TY6J1A

- Staging site simple site was created but transfer wasn't completing 
- I saw the same "Installation in progress" error on the staging site when I tried to send AT from Settings > Hosting config
- Then I looked at prod site in Hosting Config as the owner user and got a notice about JP connection on the prod site being bad
- - this notice did not show for the non-owner user so they didn't know how to resolve (**If I'm reading the code right it looks like not showing this notice on all admin users might be intentional; I think we should show for all**)
- once prod site JP connection was resolved, staging site finished transferring without issue

![image](https://github.com/Automattic/wp-calypso/assets/47717887/0f51c78c-32d0-4541-9bbd-77ade4d4466c)

**Comment by wojtekn** [comment] 2024-03-28 15:51
@Nic-Sevic as we spotted this once, and couldn't reproduce it, let's close it for now. We can reopen if we have another report.

**Closed as completed by wojtekn** 2024-03-28 15:51 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Atomic, [Feature] Staging Sites, [Product] WordPress.com, [Feature Group] Developer & Contractor Tools
