### ISSUE TITLE
Duotone filter not applied on Cover block on front end on Simple site

### ISSUE THREAD

**Issue by sguzovskaia** [Automattic/wp-calypso#74379] opened 2023-03-13 15:19 UTC
### Quick summary

The custom duotone filter is not displayed on the front end on existing and new Cover blocks. The bug is present with GB 15.3.1. FSE theme

### Steps to reproduce

On a simple site running Gutenberg: v15.3.1 add a Cover block to a page
Apply a custom duotone filter to the cover block
View the page on the front end

### What you expected to happen

The image should appear in duotone (and match editor)

**Editor view**:

![Markup on 2023-03-13 at 15:08:09](https://user-images.githubusercontent.com/47414943/224743160-122b5a3c-cd90-4794-8975-728b048a0284.png)

### What actually happened

Cover image appears in full color

**Fron end view**:

![Markup on 2023-03-13 at 15:09:44](https://user-images.githubusercontent.com/47414943/224743597-f44c02b0-f8db-4cff-8fc6-cb8cf6a706e1.png)

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Noticed on a simple site using Varese theme. Premium plan.

Custom duotone that was used:
![Markup on 2023-03-13 at 15:11:59](https://user-images.githubusercontent.com/47414943/224744272-657b4f56-c593-4aa1-bdf1-39c8821b3389.png)

Replicated the same on my test site on Premium plan. Tested by adding a new Cover block to the Front page template.

When applying a preset duotone, it works as expected.

**Comment by sguzovskaia** [comment] 2023-03-13 15:20
First noticed in 6034729-zen

**Comment by kavyagokul** [comment] 2023-03-16 11:06
📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/74357

**Closed as completed by kavyagokul** 2023-03-16 11:06 UTC
Labels: Bug, [Pri] High, Triaged, [Platform] Simple, [Status] Priority Review Triggered
