### ISSUE TITLE
Importing content between Atomic sites returns error

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#76715] opened 2023-05-09 12:45 UTC
### Quick summary

When attempting to import an XML file containing content (posts, pages, etc) from one Atomic site, to another Atomic site, the importer does not recognize the XML as containing any content and returns the error:

```
No import file found.
Make sure you are using a valid WordPress export file in XML or ZIP format.
```

This happens regardless of the size of the file.

Imports work fine to Simple sites.

### Steps to reproduce

1. Export content from XML
2. Attempt to import it to Atomic site
3. Notice the error

### What you expected to happen

The import should start and content should appear on the site it was imported to.

### What actually happened

It returned the following error:

```
No import file found.
Make sure you are using a valid WordPress export file in XML or ZIP format.
```

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

p1683631429511679-slack-C03TY6J1A
6274068-zd-woothemes
43205785-hc

**Comment by karenroldan** [comment] 2023-05-09 12:58
📌 REPRODUCTION RESULTS

- Tested on Simple – Could Not Replicate
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

**Simple**

I was able to upload the XML file that was downloaded from the Atomic site. 

![Screenshot 2023-05-09 at 14 57 56](https://github.com/Automattic/wp-calypso/assets/67279475/c3d6b3b7-1bdd-4da0-92f9-97daf7b868e9)


 **Atomic**

After uploading the XML file, the importer started processing it but later displayed an error message indicating `No import file found`

![Screenshot 2023-05-09 at 14 54 42](https://github.com/Automattic/wp-calypso/assets/67279475/9dfd3e06-3755-4fa8-b79e-a9065dc60170)

![Screenshot 2023-05-09 at 14 50 00](https://github.com/Automattic/wp-calypso/assets/67279475/1f3d08be-2c6d-4def-8396-4663ec711ae4)



📌 ACTIONS

- Assigned to @Automattic/caribou

**Comment by DavidSaladu** [comment] 2023-05-09 13:07
Another one 6270161-zd-woothemes

**Comment by karenroldan** [comment] 2023-05-09 13:41
@Automattic/caribou I encountered the same error in Atomic when importing from Blogger. The import was successful in a Simple site.

![Screenshot 2023-05-09 at 15 39 38](https://github.com/Automattic/wp-calypso/assets/67279475/38e448d5-42b7-4273-be0c-ca03f99cc9e7)

**Comment by zaerl** [comment] 2023-05-09 14:38
The bug has been fixed. Can you please verify? Thanks.

pMz3w-hvY-p2#comment-108739

**Comment by filipanoscampos** [comment] 2023-05-09 15:06
It is working on my end.
Thank you so much, @zaerl.

**Comment by upwardmomentum84** [comment] 2024-01-05 18:39
It looks like this bug may be back: 7540262-zd-a8c

I was able to replicate on a test Atomic site. I found enabling the WordPress Importer from Tools > Import > Choose from full list > Install Now (under WordPress) and then using Run Importer took me to `wp-admin/admin.php?import=wordpress` and I was able to import the file then.

![Markup 2024-01-05 at 13 38 15](https://github.com/Automattic/wp-calypso/assets/93800099/07870fbf-86bb-4ae4-a17a-c931fd2e8b98)

**Comment by ouikhuan** [comment] 2024-01-06 01:25
Hi @upwardmomentum84  👋  It appears our media library was full, it's been cleaned so it should be fine now, could you verify this once you have a moment please? 🙏

**Comment by upwardmomentum84** [comment] 2024-01-06 12:42
Yes, I can confirm the import is working now without any errors showing!

**Comment by ouikhuan** [comment] 2024-01-06 14:54
> Yes, I can confirm the import is working now without any errors showing!

Thanks for the confirmation @upwardmomentum84 ! I'll close this ticket for now as this is resolved 🙂

**Closed as completed by ouikhuan** 2024-01-06 14:54 UTC
Labels: Bug, [Pri] High, Customer report [LEGACY], [Status] Priority Review Triggered
