### ISSUE TITLE
Redirection to dashboard's home on new sites that have not been launched yet when trying to edit post/pages or Site Editor 

### ISSUE THREAD

**Issue by renata-franco** [Automattic/wp-calypso#87416] opened 2024-02-13 12:28 UTC
### Quick summary

When the user creates a new site that has not been launched yet, sometimes going to edit a post or page, or the Site Editor, will redirect them to https://wordpress.com/setup/design-first/launchpad?siteSlug=SITE and then to https://wordpress.com/home/

https://github.com/Automattic/wp-calypso/assets/81378719/d3eea0d3-2fe9-4d2b-8f3b-6155f9b85ccb

Up until now, the case has been with one simple site (7689569-zen) and one AT (7727769-zen).

Also, looks like it does not happen for all sites. I tried replicating on a simple site recently created, and nothing. It worked normally.

Video attached. 

### Steps to reproduce

1. Go to Site Editor on a site that has yet to be launched. 
2. Get redirected. 

### What you expected to happen

View the Site Editor or the page/post to edit it. 

### What actually happened

Redirection to https://wordpress.com/home/ after visiting temporarily https://wordpress.com/setup/design-first/launchpad?siteSlug=SITE

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Workarounds

Launch the site. Put in "Coming Soon" and then change to "Public". Repeat a couple more times and leave on "Coming Soon" at the end. This usually fixes it.

**Comment by vinnykaur** [comment] 2024-02-16 10:17
One more, simple site -  7713526-zd-a8c

**Comment by maciejpilarski** [comment] 2024-02-16 15:30
📌 REPRODUCTION RESULTS
– Tested on Simple – Could Not Replicate 

📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to recreate the issue on my new test site, which hasn't been launched yet. All worked as expected.

📌 ACTIONS
– Closed as could not replicate (please reopen if the issue reoccurs)

**Comment by csonnek** [comment] 2024-03-15 16:44
I have another report from the forums: https://wordpress.com/forums/topic/edit-site-loop/

I can replicate by trying to open the site editor on the user's site that has not been launched: https://marriedwithadog1f902d4731.wordpress.com/

It stops loading the site editor partway through, then redirects to `https://wordpress.com/setup/design-first/launchpad?siteSlug=marriedwithadog1f902d4731.wordpress.com` then completes the redirect to the user's dashboard.

**Comment by csonnek** [comment] 2024-03-15 17:58
Another report: https://wordpress.com/forums/topic/cant-edit-site-14/

Site: https://millennialdigitaltimes.wordpress.com/ not launched yet - same `/setup/design-first/` URL before redirecting to the dashboard

**Comment by jorpdesigns** [comment] 2024-05-13 10:34
- Reported on unlaunched Atomic site in 8182209-zen.
- Toggling Launch Site → Public → Coming Soon didn't help. 
- Site Editor isn't affected and issue doesn't occur on newly-created pages (possibly due to following suggestions in paYE8P-2BZ-p2  
- Suggested creating new pages as workaround (no content in existing pages).

**Comment by galakhyati** [comment] 2024-05-20 07:52
Another simple site that was not launched in 8213067-zd-a8c. The Editor link was getting redirected to the dashboard. I've suggested the workaround to try.

**Comment by chekle** [comment] 2024-06-26 22:48
8317102-zd-a8c Another user reported the same issue on a staging site using the Assembler theme. The suggested fixes didn't work. Changing themes did resolve the issue, switching to the Classic admin allowed the pages to be edited.

**Comment by janmckell** [comment] 2024-07-07 15:35
This user had the same issue, usign the Pixl theme. Toggling 'Coming Soon'/'Public' a few times fixed it for them.
8448275-zd-a8c

**Comment by daledupreez** [comment] 2024-08-27 09:35
Thanks to @supernovia sharing a customer use case, I am fairly confident that https://github.com/Automattic/wp-calypso/pull/90706 is closely related to this, and I have firmer steps to reproduce:
* Create a new site via https://wordpress.com/setup/start-writing/
* Work through the flow to publish your first post
* After publishing, you should be taken to the fullscreen launchpad.
  - You may see a congratulatory modal instead -- if so, pick "Next steps" to get taken to the launchpad
* On the fullscreen launchpad, select the "Skip for now" option in the top right corner to take you to Customer Home
* Navigate to the Site Editor via _Appearance_ => _Editor_
* Make one or more changes to the template and save them.
* Reload the site editor.
* You should be redirected to the launchpad screen and then back to Customer Home.

**Closed as completed** 2024-08-29 14:29 UTC
Labels: Bug, [Pri] Low, Triaged, [Feature] Full Site Editor, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Product] WordPress.com, [Feature Group] Editor Experience

**Comment by daledupreez** [comment] 2024-08-29 15:06
Due to the deployment strategy for code in `wpcom-block-editor`, this was eventually deployed via D159963-code.
