### ISSUE TITLE
[Block] Navigation block font color not displaying properly

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#75196] opened 2023-04-01 19:06 UTC
### Quick summary

Setting the font color directly on the Navigation block in the Site Editor is not properly reflected on the live site.

Reported in Forums: https://wordpress.com/forums/topic/navigation-menu-text-color-live-not-what-is-set-in-editor/

### Steps to reproduce

1. Existing or new site
2. Free or Personal plan
3. Activate theme: Zoologist, Quadrat, Geologist
4. Go to the Site Editor in edit mode
5. Select the Navigation block
6. Set the Text color for the block
7. Save and view

### What you expected to happen

I expected all parent items of the menu to be the color I selected.

### What actually happened

Only items that had a sub-item updated to the new color.

<img width="1576" alt="Markup 2023-04-01 at 12 29 58" src="https://user-images.githubusercontent.com/42655541/229309451-b85a6374-789e-4dfd-b446-9153de03b92b.png">
<img width="1573" alt="Markup 2023-04-01 at 12 30 17" src="https://user-images.githubusercontent.com/42655541/229309455-a8b37548-1813-4355-ab87-edbc66f75b1d.png">

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Confirmed it happens on: Zoologist, Quadrat, Geologist
Doesn't happen on: Appleton, Meraki, Russell

Work around: add a sub-item to each menu item but don't add a new link, and turn off the show arrow option. Live site will update to the correct color without behaving like there are sub-items for the menu.

I haven't tested this on the Premium plan, Atomic sites or self-hosted sites. It is consistently reproducible on Simple sites with the Free or Personal plan.

Other findings:
Seems to be coming from this inline CSS that's being added to the index:
```
<style id='wp-block-navigation-link-inline-css'>
.wp-block-navigation .wp-block-navigation-item__label{overflow-wrap:break-word;word-break:normal}.wp-block-navigation .wp-block-navigation-item__description{display:none}
.wp-block-navigation-link{background-color: transparent;color: var(--wp--custom--color--foreground);}
</style>
```
Possibly related to: https://github.com/WordPress/gutenberg/issues/42253

**Comment by mdtanjid0** [comment] 2023-04-02 14:13
Could replicate the same with Geologist - Slate theme. 

6067099-zd ( needs to follow up ). 

Looks like this CSS causes that: 
<img width="1375" alt="Screen Shot 2023-04-02 at 20 03 49" src="https://user-images.githubusercontent.com/54123436/229358516-31bf34af-bc20-46a9-9913-3d8ef20b8da5.png">

**Comment by cuemarie** [comment] 2023-04-04 20:31
📌 ACTIONS
- Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/74984

**Closed as completed by cuemarie** 2023-04-04 20:31 UTC
Labels: Bug, [Pri] Low, Triaged, [Platform] Simple
