### ISSUE TITLE
Jetpack Plan: Pricing displayed strangely in checkout

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#22739] opened 2018-02-23 02:39 UTC
- start connecting a jetpack site
- select monthly prices
- select a personal plan
- go to checkout

You will see that the price is shown as "3.5 USD" which is pretty weird.

![screen shot 2018-02-22 at 4 23 43 pm](https://user-images.githubusercontent.com/108942/36575405-0a050a14-1808-11e8-8af3-a67aa70fd83f.png)

**Comment by gravityrail** [comment] 2018-03-03 00:22
Just wanted to add a note here: The cart API returns a `total_cost_display` value for the cart, in the form of `{currency}{amount}`, but does not do so for cart _items_, which receive `cost` (e.g. `3.5`) and `currency` (e.g. "USD") values separately. 

We either need code in Calypso which translates `cost` and `currency` into the proper string implementation, or more likely add a localised string version of the cart item amount to the API response.

Also: UGH.

**Comment by Viper007Bond** [comment] 2018-03-09 02:46
I have a fix for this but it requires an API change: D10795

**Comment by rachelmcr** [comment] 2018-08-29 14:52
I tested and confirmed that this is still an issue as originally reported. (The proposed API change in D10795-code was never merged.)

**Comment by beaulebens** [comment] 2019-08-29 18:36
I just confirmed that this is still happening

<img width="1115" alt="Screen Shot 2019-08-29 at 12 35 45 PM" src="https://user-images.githubusercontent.com/108942/63966914-8f80e500-ca59-11e9-88c4-84ba1b2e7162.png">

**Comment by lancewillett** [comment] 2020-02-21 17:18
Noting this needs retesting after Neutron rolls out the most recent checkout page redesign, February 2020.

**Comment by sirbrillig** [comment] 2020-02-21 18:15
FWIW, even though we're not using the new checkout for Jetpack plans yet, this should not be an issue there because of how we handle prices (still worth verifying).

**Comment by michaeldcain** [comment] 2020-07-19 14:55
This will indeed be fixed with the new Checkout:

<img width="948" alt="Screen Shot 2020-07-19 at 10 54 31 AM" src="https://user-images.githubusercontent.com/942359/87877795-51ace800-c9ae-11ea-8c84-4a7a148f7c30.png">

**Comment by sirbrillig** [comment] 2020-08-12 19:20
Closing because this will be fixed as soon as #22739 is closed.

**Closed by sirbrillig** 2020-08-12 19:20 UTC
Labels: Checkout, Jetpack, Plans, [Type] Bug
