### ISSUE TITLE
Sharing: Invalid/missing request nonce, clickable buttons

### ISSUE THREAD

**Issue by ossvn** [Automattic/wp-calypso#1259] opened 2015-12-04 00:48 UTC
When I tried to connect to social network for sharing, I got this message:

"Invalid/missing request nonce."

The link on browser: https://public-api.wordpress.com/connect/?action=request&kr_nonce=638907dc5b&nonce=f466acdafa&for=connect&service=google_plus&kr_blog_nonce=8a01c4e892&magic=keyring&blog=6417127

Also, while the button say "Connecting", but I still can click on it (the button's color fade out)

Question: Do we have the roadmap to make Calypso compatiable with Metabox & Post type?, what's the branch I should follow?

**Comment by lancewillett** [comment] 2015-12-04 15:36
> Question: Do we have the roadmap to make Calypso compatiable with Metabox & Post type?, what's the branch I should follow?

See #587 and #588. No current roadmap, but you can vote their with your suggestions.

**Comment by lancewillett** [comment] 2015-12-04 15:37
> When I tried to connect to social network for sharing, I got this message:

Which social network account did this happen with? Can you share details of your browser, OS version, and maybe add a screenshot or video?

**Comment by ChrissiePollock** [comment] 2017-05-23 20:36
This appears to be a similar issue: 190435-h. It was for Twitter, and the user provided the following details: Device is Sony Xperia z2 tablet..using latest chrome..was using app but it reverts to chrome when I make blogs.

I was able to replicate on a MacBook using Chrome. Screenshot from my end attached.
<img width="1217" alt="nonce" src="https://cloud.githubusercontent.com/assets/2545184/26375165/d2fbf858-3fd5-11e7-8182-60c7e5ce07be.png">

**Comment by designsimply** [comment] 2017-05-29 20:18
I was unable to reproduce the problem from test account design5279 and was able to disconnect/reconnect Twitter without any problems there. 

@ChrissiePollock, I should have thought to ask earlier, but just to make sure, I would recommend asking the user to complete the Reconnecting Twitter steps at https://en.support.wordpress.com/publicize/#reconnecting-services if they haven't already tried that (it involves clearing browser cache and trying to connect after that). If that doesn't help the issue, could you let me know a little bit more about the screenshot you posted earlier? Does that "Invalid/missing request nonce" error appear right after clicking "Connect" for Twitter on the https://wordpress.com/sharing page?

**Comment by designsimply** [comment] 2017-06-09 20:59
I checked up on this and found that the user reported back on 31-May that following the Reconnecting Twitter steps at https://en.support.wordpress.com/publicize/#reconnecting-services solved the problem in their case.

Closing for now. If this problem comes up again, please re-open and share details including your browser/OS version and add a screenshot or video if possible!

**Closed by designsimply** 2017-06-09 20:59 UTC
Labels: OSS Citizen, [Type] Help Request

**Comment by maciejpilarski** [comment] 2017-07-01 23:02
I have another issue related to LinkedIn:
https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=3299710

Each time user tries to connect he is seeing the "Invalid/missing request nonce" error.
I asked him to clear cache and reconnect by follwing the steps from  https://en.support.wordpress.com/publicize/#reconnecting-services but it didn't help.

**Comment by StefMattana** [comment] 2017-12-28 13:55
Got another user who had the same issue during a 1:1 Concierge chat - ticket being 868259-zen
I tried replicating it and clearing the cache worked out for me. Checking if that solved the problem also on the user's end
