### ISSUE TITLE
Editor: Adding a link and caption to an image breaks all the things

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#16405] opened 2017-07-20 15:03 UTC
#### Steps to reproduce
1. Start a new post/page/whatev — just load the editor somehow.
2. Add an image to your fabulous new post.
3. Now, that image deserves a link. Give it one.
4. You know what else that image needs? A caption! Give it a caption...
5. Boom, nice work. You broke it.

Safari Version 10.1.1 (12603.2.4)
Latest MacOS

<img width="360" alt="screen_shot_2017-07-20_at_16 54 56_720" src="https://user-images.githubusercontent.com/191598/28424137-da09a3ce-6d3a-11e7-9ff4-81e0aaa1277d.png">

**Comment by designsimply** [comment] 2017-07-20 15:54
Tested and confirmed that linking an image then adding a caption effectively removes the link. I found in my testing that the order matters—linking then captioning breaks the link.

<strong>Video:</strong> <a href="https://cloudup.com/cFrEVoCZhhO">2m22s</a>

![screen shot 2017-07-20 at thu jul 20 9 51 34 am](https://user-images.githubusercontent.com/1119271/28426747-52bbb5aa-6d31-11e7-8123-7b58febdb13a.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11297 using Firefox 54.0.1 on Mac OS X 10.12.5.</sup>

Linking then captioning an image results in the link being moved outside the image and rendering it ineffective:

1. Insert an image into a post or page.
1. Click the image.
1. Click the link icon in the editor toolbar.
1. Select a past post.
1. Click the image.
1. Click the caption icon in the image toolbar.
1. View the HTML and check to make sure the image is linked properly.

<strong>Result:</strong> the images not linked—the HTML for the link was pushed outside of the captioned image. 

Captioning then linking an image works:

1. Insert an image into a post or page.
1. Click the image.
1. Click the caption icon in the image toolbar.
1. Click the image.
1. Click the link icon in the editor toolbar.
1. Select a past post.
1. View the HTML and check to make sure the image is linked properly.

<strong>Result:</strong> the image was linked as expected.

**Comment by rachelmcr** [comment] 2017-11-21 17:34
This one has been around a while. Closing as a dupe of https://github.com/Automattic/wp-calypso/issues/7781.

**Closed by rachelmcr** 2017-11-21 17:34 UTC
Labels: Editor, [Type] Bug
