### ISSUE TITLE
CPTs: Missing from slide-out sidebar even if CPT is active in a theme

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#14235] opened 2017-05-18 19:17 UTC
When you open the slide-out sidebar dashboard from the front end in a theme that declares support for Testimonials or Portfolios (or where the site has activated support for those CPTs via Settings > Writing in WP Admin), those CPTs are missing from the sidebar. You can only access those items by going into the full dashboard.

#### Steps to reproduce
1. Starting at URL: Front page (or any page) of any WP.com site
2. Activate a theme that declares support for portfolios or testimonials, like Illustratr (portfolios)
3. Go to My Sites

#### What I expected

To see the Portfolios item in the slide-out sidebar dashboard.

#### What happened instead

There was no Portfolios item in the slide-out sidebar dashboard. To access Portfolios, you have to click one of the slide-out sidebar items first, to open the full-page dashboard.

The same thing happens for themes that declare support for Testimonials.

Screencast:
 
https://cloudup.com/cUNylkCbYOL

Theme: Illustratr

For comparison, screenshot of full dashboard, where the CPTs _are_ visible:

![blog posts kp test site wordpress com](https://cloud.githubusercontent.com/assets/7662449/26219429/eccba000-3bdc-11e7-814e-47bdb2745213.png)

#### Browser / OS version

Firefox 53.0.2

#### Context / Source

#user-report

Reported by a premium-theme seller on WordPress.com.

**Comment by designsimply** [comment] 2017-05-29 23:31
I tested this just now and I can see the options for Testimonials and Portfolio in both the My Sites menu within Calypso as well as in the slide-out My Sites menu as viewed from the masterbar on the site front-end. Here are a few screenshots: 

![screen shot 2017-05-29 at mon may 29 5 24 47 pm](https://cloud.githubusercontent.com/assets/1119271/26563753/678733a8-4494-11e7-923d-467fc10aad08.png)
<sup>Seen at https://wordpress.com/stats/day/design5279.wordpress.com using Firefox 53.0.3 on Mac OS X 10.12.5 logged in as design5279.</sup>

![screen shot 2017-05-29 at mon may 29 5 24 45 pm](https://cloud.githubusercontent.com/assets/1119271/26563754/6b49228a-4494-11e7-89f1-5755f1fb17da.png)
<sup>Seen at https://design5279.wordpress.com/ using Firefox 53.0.3 on Mac OS X 10.12.5 logged in as design5279.</sup>

I tested both with the WP Admin > Settings > Writing > "Testimonials" and "Portfolio Projects" options enabled as well as disabled.

@kathrynwp, would you mind checking on this again to see if I've missed something in my latest testing or if the masterbar My Sites menu is now working as expected for Testimonials and Portfolios?

**Comment by dashkevych** [comment] 2017-05-30 00:05
Could it be possible that this issue appears only on private websites?

For example, on the theme's demo website, which can be viewed by anyone, the options for Testimonials are available through the slide-out My Sites menu.

However, the options for Testimonials are missing when try to open it in the sandbox.

**Comment by kathrynwp** [comment] 2017-05-30 14:54
@designsimply The issue is still present for me. Here is what I did:

1. Activated Illustratr on my test site
2. Went to the front end of my test site
3. Clicked My Sites

**Result:** Portfolios was not visible in the slide-out sidebar:

![kp test site a very nice tagline](https://cloud.githubusercontent.com/assets/7662449/26589534/481bd8ce-4526-11e7-83cd-33af910b1ebc.png)

Note: the site is private, but is not a sandbox.

**Comment by kathrynwp** [comment] 2017-05-30 15:00
Just repeated the test with a non-private site and saw the same result as the above.

**Comment by designsimply** [comment] 2017-06-13 18:19
I tested with a private site (Premium Plan) for user798 (registered on 2014/06/04) and the "Portfolio" option was missing in that case:

![screen shot 2017-06-13 at tue jun 13 11 54 50 am](https://user-images.githubusercontent.com/1119271/27097270-ef722758-5030-11e7-8bc2-39a128957055.png)
<sup>Seen at https://madefortesting764.wordpress.com using Safari 10.1.1 on Mac OS X 10.12.5 logged in as user798.</sup>

Next, I tested with a private site (both with a Free Plan then a Premium Plan) for the same user (user798) on a blog (design5279.wordpress.com) where that user is a Contributor and I can see the "Portfolio" option in My Sites on the front-end in that case:

![screen shot 2017-06-13 at tue jun 13 11 59 39 am](https://user-images.githubusercontent.com/1119271/27097330-1bd19e46-5031-11e7-8c97-f078f7be8ef5.png)
<sup>Seen at https://design5279.wordpress.com using Safari 10.1.1 on Mac OS X 10.12.5 logged in as user798.</sup>

I also tested with a non-private (AT) site, and and I can see the "Portfolio" option in My Sites on the front-end in this case too:

![screen shot 2017-06-13 at tue jun 13 11 26 34 am](https://user-images.githubusercontent.com/1119271/27095716-e48f80c4-502b-11e7-9f10-7eaaf67f025e.png)
<sup>Seen at https://designsimply-automated-transfer-6.blog using Safari 10.1.1 on Mac OS X 10.12.5 logged in as user907.</sup>

Neither privacy option nor the plan type seem to be the limiting factor, and it doesn't seem to happen for all blogs using the steps to reproduce provided. It does seem to be blog-specific. I'm not seeing a pattern though!, and so I would like to wait for more user reports (based on the information here, it appears there has only been one user report so far).

**Comment by lancewillett** [comment] 2017-09-04 22:23
I looked at this a bit today — this isn't related to Calypso code specifically, but is a front-end plugin for WP.com "admin-bar.php" and baked into Jetpack, as well.

Looks like there are several possible things going on:

1) If a site has more than 3 items to appear under the Publish menu, anything more is simply hidden away (in the older wp-admin navigation they were hidden in a submenu to save space).
2) The way the post types are retrieved from the WP.com API is cached by user locale, so that could have varying results if the API call comes back empty, or the cache isn't matched correctly.
3) The post types are retrieved from the current user's primary site, and not the current site.

To fix this, I'd recommend we start by not limiting the number of links in the publish menu, and for WP.com match Jetpack's masterbar implemention and hard-code Testimonials and Portfolios for now as the only two CPTs we officially support.

**Comment by brbrr** [comment] 2018-02-13 07:53
I've reproduced using these steps:
1. change theme to `Illustratr`
2. load the front page of the site - `Portfolios` was visible in the side menu
3. went to site settings -> Writing -> enable `Testimonials`.
4. load the front page of the site - `Testimonials` wasn't visible in the side menu

**Comment by lancewillett** [comment] 2018-03-24 23:12
Fixed in r172277-wpcom

**Closed by lancewillett** 2018-03-24 23:12 UTC
Labels: Custom Post Types (CPT), Editor, [Type] Bug
