### ISSUE TITLE
Block themes may be incompatible with WooCommerce Bookings's calendar

### ISSUE THREAD

**Issue by csmcneill** [Automattic/wp-calypso#59508] opened 2021-12-22 22:45 UTC
### Quick summary

When a Block theme is used in conjunction with [WooCommerce Bookings](https://woocommerce.com/products/woocommerce-bookings/?aff=10486&cid=1131038), the calendar is not displayed.

### Steps to reproduce

1. Install Arbutus
2. Install Bookings
3. Create a Bookable product
4. Access the product from the front-end
5. The calendar does not appear as expected
6. Change the theme to a default theme, like Twenty Twenty One
7. The calendar is now visible

### What you expected to happen

The calendar should be visible.

### What actually happened

The calendar is not visible.

### Context

4625331-zen, p1640158718370100-slack-C029FM1EH

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Arbutus

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by hacchism** [comment] 2021-12-22 22:57
**Additional Info:**

The user(mentioned in the Context section above) tried Twenty Twenty-One and Alves too. The issue couldn't be replicated with these two themes though they are also block themes.

**Comment by kosiew** [comment] 2021-12-31 06:57
Hi @csmcneill ,

Thanks for reporting this.

I could not reproduce this on my test site and am closing this for now. 

![image](https://user-images.githubusercontent.com/29057562/147808521-0c72d37e-aae1-4665-87a1-cef1713a1334.png)

https://wpstore101.wpcomstaging.com/product/bookable-product-require-confirmation/

Please feel free to re-open if you have further findings to add.

**Closed as completed by kosiew** 2021-12-31 06:57 UTC
Labels: Bug
