### ISSUE TITLE
FSE: Saving a template part and then going back to page shows warning

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#36015] opened 2019-09-06 01:43 UTC
To reproduce:

* Create a new simple site for testing
* Edit the header template part
* Hit the update button
* Hit the "Back to Page" button

see this, even though you just saved:

<img width="530" alt="Screen Shot 2019-09-05 at 6 53 26 PM" src="https://user-images.githubusercontent.com/1464705/64395283-8621ea80-d00e-11e9-832b-203488125667.png">

**Comment by apeatling** [comment] 2019-09-06 01:54
This does not happen on a local install.

**Comment by glendaviesnz** [comment] 2019-09-06 05:05
I can replicate this locally. It happens every time I edit and existing page - saving the change does not clear the isDirty flag: 

![page](https://user-images.githubusercontent.com/3629020/64402027-8af6a500-d0c7-11e9-991b-aa35f34fa149.gif)

It also happens sometimes when editing the templates, but only seems to be when adding new blocks rather than editing the default blocks, and in will sometimes wipe the dirty flag with the second save:

![template](https://user-images.githubusercontent.com/3629020/64402214-330c6e00-d0c8-11e9-9396-dcd593e2713d.gif)

I tried to work out when this issue crept in, but it seems to go right back to https://github.com/Automattic/wp-calypso/pull/35075/files if I checkout commit just before this locally the dirty flag gets wiped with ever save - but haven't managed to work out why the changes in this commit change anything as still essentially just doing `() => <InnerBlocks.Content />` in the post content change.

**Comment by glendaviesnz** [comment] 2019-09-23 02:21
Since the changes at https://github.com/Automattic/wp-calypso/pull/35075/files, for some reason the post content returns as a non transient edit from getEntityRecordNonTransientEdits https://github.com/WordPress/gutenberg/blob/master/packages/core-data/src/selectors.js#L184, even if the post has been saved. I suspect it is because the content is seen by this method as containing the template blocks
`"<!-- wp:a8c/template {"templateId":9,"className":"… {"templateId":10,"className":"site-footer"} /-->"`
but the saved content will be just the post content with the template wrappers stripped.

Somehow we need to get the editor to ignore the template wrappers when assessing if there are any changes since the last save.

**Comment by glendaviesnz** [comment] 2019-09-24 00:40
> I suspect it is because the current content is seen by this method as containing the template blocks
> `"<!-- wp:a8c/template {"templateId":9,"className":"… {"templateId":10,"className":"site-footer"} /-->"`
> but the last save of content will be just the post content with the template wrappers stripped

I was wrong about the above - from the editors point of view the post content being saved and retrieved from the API contains the template wrappers as the wrapping and stripping is all handled on the server

**Comment by noahtallen** [comment] 2019-09-24 00:51
As far as I can tell, reproduction is as simple as:

1. Open the page editor and do nothing else
2. Try to close the page editor with any back button
3. Observe "unsaved changes" prompt

**Comment by glendaviesnz** [comment] 2019-09-24 02:11
Could be something to do with https://github.com/WordPress/gutenberg/blob/master/packages/core-data/src/actions.js#L156 - looks like the isEquals check at https://github.com/WordPress/gutenberg/blob/master/packages/core-data/src/actions.js#L164 may fail due to spacing and line break differences in content

**Comment by glendaviesnz** [comment] 2019-09-24 02:47
<img width="875" alt="Screen Shot 2019-09-24 at 2 45 23 PM" src="https://user-images.githubusercontent.com/3629020/65477294-fd45f280-ded9-11e9-9492-946ba10d9928.png">

Definitely seems to be related to getRawEntityRecord selector at https://github.com/WordPress/gutenberg/blob/master/packages/core-data/src/actions.js#L144 changing the line breaks. If I remove all line breaks from the record value and editedRecordValue as above the editor dirty state disappears on a second save (eg. takes to clicks of update to clear dirty state)

**Comment by glendaviesnz** [comment] 2019-09-24 03:29
maybe related - https://github.com/WordPress/gutenberg/issues/17264

**Comment by glendaviesnz** [comment] 2019-09-24 23:13
This is fixed by https://github.com/WordPress/gutenberg/pull/17532

**Comment by noahtallen** [comment] 2019-09-25 21:42
This has been cherry picked into our wpcom Gutenberg update. Will close once that ships.

**Comment by noahtallen** [comment] 2019-09-26 19:27
Gutenberg has landed. Closing!

**Closed by noahtallen** 2019-09-26 19:27 UTC
Labels: [Pri] BLOCKER, [Type] Bug
