### ISSUE TITLE
[Bug]: Design picker preview looks different than the demo site

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#61661] opened 2022-03-04 15:46 UTC
### Quick summary

Some themes may have a preview that looks different than the demo site, because of how the preview is loaded from public-api.

### Steps to reproduce

Compare the preview vs the demo site for the Dorna theme

| **Demo site** | **API preview** |
| - | - |
| PdKsXk-2-p2 | https://public-api.wordpress.com/rest/v1.1/template/demo/pub/dorna/dorna |
| <img width="500" src="https://user-images.githubusercontent.com/1699996/156795023-efb8ba6a-a81a-4e8c-a643-f140e88103df.png" /> | <img width="500" src="https://user-images.githubusercontent.com/1699996/156793777-0791594f-3097-476e-83a6-2727e21343d7.png" /> |

In context of the design picker
(/new flow)

<img width="679" alt="image" src="https://user-images.githubusercontent.com/1699996/156793960-2373219c-ad6e-4933-beaa-003beedc6bf6.png">

### What you expected to happen

For the preview to look the same.

### What actually happened

The preview is missing full with images and the content width is compressed.

### Context

#61592

### Browser

Mozilla Firefox

### Other notes

This appears to be a combination of issues. One is that at the time Gutenberg JSON resolver checks the theme for various block filter issues, the theme registers as `public-api` rather than `pub/dorna`.

This can be resolved by calling `WP_Theme_JSON_Resolver_Gutenberg::clean_cached_data()` at the right time. But this actually makes the issue worse, possibly because some styles are not loaded.

https://public-api.wordpress.com/rest/v1.1/template/demo/pub/dorna/dorna

![image](https://user-images.githubusercontent.com/1699996/156791003-c8bfe325-a317-421b-b7ee-d6b876718841.png)

And here's part of a diff of the demo site html compared to the public-api generated preview, notice the missing styles

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/1699996/156792744-971b9c3b-1c56-4d91-8cbd-ffedbdfe1b1d.png">

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by simison** [comment] 2022-03-11 12:43
@creativecoder how widespread does this seem, or is it one-off theme, and happens only in /new flow? We're about to remove /new and focus only on /start this month.

@autumnfjeld If this happens in /start, I think this issue would be good for Ganon to look into as part of maintenance.

**Comment by arthur791004** [comment] 2022-03-11 13:18
We're working on https://github.com/Automattic/wp-calypso/issues/61391 and I think the root cause is the same. @fushar found a weird problem and will write up a p2 about this issue.

**Comment by fushar** [comment] 2022-03-14 02:29
We found the root cause. It is explained in this internal docs: pbxlJb-1i1-p2. We'll implement a temporary fix.

**Comment by fushar** [comment] 2022-03-16 02:29
The fix has been shipped! 🎉

**Closed as completed by fushar** 2022-03-16 02:29 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Normal, Needs triage, [Feature] Design Picker, V13n Build Flow
