### ISSUE TITLE
Domains: Can't complete checkout flow without a space in postcode

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/wp-calypso#18854] opened 2017-10-15 09:14 UTC
I just had a really terrible experience attempting to set up a domain, and it turned out it was a programming inflexibility I'll admit I assumed we wouldn't have done. 

It's particularly odious that we're stripping out the space and then refusing to accept the postcode without it—so we're basically introducing that error ourselves.

#### Steps to reproduce
1. Starting from: https://wordpress.com/plugins/upload/ for any site that doesn't have a custom domain set. (Note: the messaging displayed here is really confusing too.)
2. Click through to purchase a domain. 
3. Select a domain + no email. 
4. Enter your information.
5. When you get to the postcode, enter the beginning of a postcode with a space: "EH7 " and pause.
6. Notice that the space is automatically removed, so being able to type it in can be extremely difficult.
7. Enter the full postcode (I used EH74BW).
8. Get an unhelpful error message.

#### What I expected

I expected that the validation would be able to accept a postcode entered with or without a space. 

#### What happened instead

It gave me an super unhelpful and straight-up false error message: "Make sure this is a valid postcode." 

#### Browser / OS version

All, but I was using a Windows PC 10 via an attached display screen.

#### Screenshot / Video

![img_1593](https://user-images.githubusercontent.com/376315/31583243-37812c5a-b18f-11e7-9693-9fdc09e048de.JPG)
![img_1594](https://user-images.githubusercontent.com/376315/31583244-37af2fe2-b18f-11e7-9481-4b9089cef6b6.JPG)

![screen 20capture 20on 202017-10-15 20at 2010-08-03](https://user-images.githubusercontent.com/376315/31583325-54df9780-b191-11e7-82a6-4f5aed6774e0.gif)

#### Context / Source

We're staffing a WordPress.com booth at SFN Expo in Glasgow this weekend and decided to try setting up a WooCommerce site on .com as a demo on one of our display screens. Apparently you need a domain to install plugins, which... really? But okay, so I'll buy a .blog and give that a go, but then I got totally stuck trying to get through the checkout flow.

Super pleased I wasn't trying to do this live with a potential customer, since I got completely blocked and frustrated trying to make it work out.

#dogfooding

Vaguely related: 16956

**Comment by klimeryk** [comment] 2017-10-15 09:26
I hear your frustration - it's a known issue: https://github.com/Automattic/wp-calypso/issues/8681 and one I'd love to fix. We _do_ allow spaces in that field, just not as a trailing one. There's a pause before we remove it, hopefully giving enough time to enter another character, though I agree in some cases it will be not enough and it will lead to a confusing validation error.

This particular case is further complicated by the fact that in UK postal codes, the space sometimes go after the first three characters, sometimes after four (the rules for which really should not be this complicated). UK postal codes are by far the most complicated ones I've seen (slightly ahead Ireland and their Eircodes - which at least are unique and useful in that regard).

Thank you for a detailed report, but I'm going to close it as a duplicate of https://github.com/Automattic/wp-calypso/issues/8681

**Closed by klimeryk** 2017-10-15 09:26 UTC
Labels: Checkout, Domains, [Type] Bug

**Comment by sarahmonster** [comment] 2017-10-20 10:40
My apologies for the aggressive tone here—I was frustrated and impatient and in a bit of a stress case.

This sort of thing is a source of frustration with web forms, and I didn't realise it was the registries that were requiring the strict space-including formatting. Hopefully this is something we can devise a solution for on our end, so it's easier for our users to buy things! 🙂

Thanks for looking into this further!
