### ISSUE TITLE
Anchor.FM: Can't search for site/site list is broken

### ISSUE THREAD

**Issue by serabi** [Automattic/wp-calypso#50815] opened 2021-03-06 15:42 UTC
### What I did: 

1. Clicked the "Create a podcast episode" button after pressing "post" on a post
2. Was taken to the "Howdy! Anchor would like to connect to your WordPress.com site" dialogue
3. The display for the current site I was on was broken
4. When I clicked the arrow to find a different site, the display remained broken and there was no way for me to search for the specific site I wanted to connect to my podcast

#### Screenshots

Initial connection screen: 
<img width="743" alt="Screen Shot 2021-03-05 at 10 43 33 AM" src="https://user-images.githubusercontent.com/30205248/110212230-61f3d380-7e68-11eb-98fe-0f1e8fc8b947.png">

I also have a screenshot of the list of sites but some of the sites are internal P2s, so I did not upload that screenshot. Am happy to upload if needed! 

#### Browser / OS version

Chrome 88.0.4324.192 (Official Build) (x86_64) // Mac OS Big Sur 11.1

**Comment by simison** [comment] 2021-03-08 08:26
Cc @Automattic/explorers @Automattic/serenity seems critical? 

Related? https://github.com/Automattic/wp-calypso/issues/50822

**Comment by pablinos** [comment] 2021-03-08 09:35
That looks mainly like it's not loading the site's logo/favicon properly. I've checked it with my main Automattic account and a test account with multiple sites, and it renders ok for me. 

Just noting that you can't search, it's dropdown that you have to scroll through, I'm guessing this problem was preventing the dropdown from scrolling? Perhaps there was a problem downloading some static assets, and the CSS and default image were temporarily broken.

Is anyone able to reproduce this?

**Comment by simison** [comment] 2021-03-08 10:32
Could the image not load be 3rd party cookie issue? It would then replicate e.g. on Safari.

Separately, when the image doesn't load (for whatever reason), the site list shouldn't break too badly.

**Comment by edequalsawesome** [comment] 2021-03-08 16:12
FWIW, when I tried the same flow as @serabi, I was trying to connect with one site (`jpbeta.fancytest.site`) but, when I got to the connection flow, it tried to connect the site listed as my primary site on WordPress.com instead (`nearlycoherent.com`):

![Screenshot_2021-03-03 Authorize Anchor](https://user-images.githubusercontent.com/4000628/110347403-96999380-7ffe-11eb-87ec-f0303543d75a.png)

I'd have expected the site I launched the connection process from to be the one selected at the top. I can create a new issue for that, but in regard to searching for sites not being available, trying to complete the connection was a _pain_ since the wrong site was chosen -- admittedly my list of sites was significantly larger than a standard user might have, but I had to scroll for a few minutes to find the site I was looking for, which wasn't ideal.

**Comment by kwight** [comment] 2021-03-08 18:49
Correct, the expected behaviour is for the default site to be set at the top of the OAuth site selector (which is a dropdown, and not searchable as @pablinos has pointed out).

I'll close this since the original reported issue is not unexpected, and have opened https://github.com/Automattic/wp-calypso/issues/50852 instead to track improving the user experience with the referring site being preloaded instead.

**Closed as completed by kwight** 2021-03-08 18:49 UTC
Labels: Bug
