### ISSUE TITLE
Intermittent: Customizer CSS is missing after site goes Atomic

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#81593] opened 2023-09-11 14:26 UTC
### Quick summary

Similar to #76642 — when a simple site is built and CSS is added through the Customizer, that CSS is lost when a site goes Atomic — the Customizer's Additional CSS field is blank, similar to when one theme is switched for another.

### Steps to reproduce

1. Activate a Varia theme (e.g. Shawburn) on a simple site
2. Add some custom CSS to the Customizer
3. Push the site to Atomic
4. Open the Customizer again, and observe that the CSS is missing

### What you expected to happen

I expected the CSS to remain in the Customizer after the site goes Atomic.

### What actually happened

Any CSS added in the Customizer is removed, and needs to be added again. 

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

This most recently occurred when building pdEkSe-4WM-p2

**Comment by cuemarie** [comment] 2023-09-11 21:29
📌 REPRODUCTION RESULTS
- Tested on TT3 – Could Not Replicate 
- Tested on Varia – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

I was not able to reproduce this issue on Varia or TT3 🤔 

Varia: 

https://github.com/Automattic/wp-calypso/assets/27249804/a693a1af-a3d9-4863-a920-1ba7eb443208

TT3:

https://github.com/Automattic/wp-calypso/assets/27249804/c0701eef-3eed-4883-ac07-c76cc51e4bb3

---

Will try again with some child themes and report back...

**Comment by metabreakr** [comment] 2023-09-11 23:34
@cuemarie Hmm. I will try and replicate this again in the same way that I built the site in the P2 (not that it's anything out of the ordinary)

**Comment by metabreakr** [comment] 2023-09-12 14:06
I couldn't reproduce this again, so will close this issue for now until it happens again.

**Comment by ccwalburn** [comment] 2023-09-27 19:04
Reopening this issue as this has happened again.
7093294-zd-a8c
User was using the Morden theme on a Premium plan and did not change themes after upgrading and going AT.

**Comment by cuemarie** [comment] 2023-09-28 00:39
THanks @ccwalburn - I just ran a site using Morden through 2 tests and still wasn't able to repro:

- Test 1: Simple Business Site -> Atomic Business site (transferred to AT via plugin install) [Recording](https://github.com/Automattic/wp-calypso/assets/27249804/0eeb1ae8-04f0-481d-b5a3-28bbfe041fb5)
- Test 2: Simple Premium Site -> Atomic Business site (upgraded and transferred to AT via plugin install) [Recording](https://github.com/Automattic/wp-calypso/assets/27249804/235cb2bc-89a7-4e2c-8fcb-2b4436e2e5ad)

---

📌 ACTIONS
- I'll leave this open to see if anyone else runs into it.

📌 Message to Future HEs
- Transferring AT alone does not seem to explain this behavior - if you run into users who report this, try to get as much information as you can about the steps they took to upgrade, when the CSS was originally added to their site, etc, so that we can try to identify any patterns. Thank you!

**Comment by metabreakr** [comment] 2023-10-03 14:40
@cuemarie Could this be related to #82363 ?

**Comment by cuemarie** [comment] 2023-10-04 18:40
> Could this be related to https://github.com/Automattic/wp-calypso/issues/82363 ?

It certainly seems like a similar issue - intermittently losing theme customizations (whether that's via CSS, global styles, or templates) when sites go AT.  It's tough to find a pattern tho as we haven't been able to reproduce either one consistently, though, so for now we'll need to keep both open and see if we can find a pattern if/when more reports come in.

**Comment by davemart-in** [comment] 2024-10-15 16:41
Looks like this may be resolved? Closing this out since it's not seen any momentum in over a year.

**Closed as completed by davemart-in** 2024-10-15 16:41 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Low, [Feature] Customizer, Triaged, Customer report [LEGACY], [Platform] Atomic, [Product] WordPress.com

**Comment by jartes** [comment] 2025-05-16 10:05
I had another instance here 9780217-zd-a8c

I'm not sure if we should reopen the issue, as this seems to be an edge case.

In this case, the user has always been using the Twenty-Twenty Five theme, and they were using the Additional CSS option from the Customizer to add CSS while they were on the Premium plan. After upgrading to Business, the site went to atomic, and that option disappeared, but the CSS was rendered (as it was saved in the Safecss custom post type).
