### ISSUE TITLE
Site Editor: white stripe below footer not removable

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#65344] opened 2022-07-07 11:20 UTC
### Quick summary

There is a white stripe under the footer if the site is created in the Site Editor that is not removable from the editor and hard to address via CSS. 

### Steps to reproduce

1. Add footer in the Site Editor
2. Give it a background color other than white

### What you expected to happen

There isn't anything below the footer. Footer touches the bottom line of the viewport.

### What actually happened

There is a white stripe not removable from the Site Editor. 

### Context

5356004-zd-woothemes
However, I noticed it on many sites.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

 FSE themes. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

/* remove white stripe below editor | 000000-ZD DZ */
.wp-site-blocks > div.wp-block-group:last-child {
	margin-top: 0;
	height: 0; 
}

Bear in mind that this code can hide some other things too. There isn't specific enough class to address it and the block is not available from the editor so a class cannot be added.

**Comment by jamiepalatnik** [comment] 2022-07-14 15:07
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Need more information

📌 SCRUBBING
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- There is no option to add a background color to the footer in the Site Editor, so I think we need more information to test this. 
- It seems the space below the footer added in the Site Editor will be whatever color is set as the background color in Global Styles—it's not always white.
- Noting that there is a similar issue here: https://github.com/Automattic/themes/issues/6066

📌 ACTIONS
- Await author feedback

📌 Message to Author
 - @daria2303 Can you clarify the steps to reproduce to explain how to add a background color to the Footer? In my test there is no option in the Site Editor to add a background color to the Footer template, only to blocks in the footer.

**Comment by daria2303** [comment] 2022-07-18 08:50
@jamiepalatnik thank's for checking. I was not precise enough. The color is needed only to notice it and it needs to be added in a block inside the Footer, you are right. If the footer background is white it just looks like a must-have space but the HTML is there. One example is our team meetup project where we had this issue: https://polarismeetuptheme.wpcomstaging.com/ 
![Markup on 2022-07-18 at 10:48:54](https://user-images.githubusercontent.com/11535091/179476248-f55e1d61-51aa-4867-a317-6ade0f2c60e4.png)

**Comment by Jaykame** [comment] 2022-08-11 16:34
Another case here: 5467273-ZD
FSE theme. Applied CSS.

**Comment by cuemarie** [comment] 2022-08-24 01:20
📌 ACTIONS
-
- Moving this back to Needs Triage to get retriaged with the updated information above.

**Comment by zachspears** [comment] 2022-09-01 00:54
Hello, @daria2303 this just came back up for triage. In my testing it looks resolved, are you still seeing this issue? Thanks!

**Comment by daria2303** [comment] 2022-09-01 07:26
@zachspears unfortunately, I do: ![HU0qW1.png](https://user-images.githubusercontent.com/11535091/187856576-4a74efe9-2c15-44f2-895f-a4896c514835.png)
The site it public: https://polarismeetuptheme.wpcomstaging.com/

**Comment by cuemarie** [comment] 2022-09-13 18:04
📌 FINDINGS/SCREENSHOTS/VIDEO
- Thanks for the update @daria2303 . I'm still not able to replicate this issue based on the steps above. 
- Your test site https://polarismeetuptheme.wpcomstaging.com/ looks like it's showing the same symptoms identified in https://github.com/Automattic/themes/issues/6066 , which based on the comments is impacting more than just the themes in the title. 

Does this test site have the footer credit hidden via the Customizer?
- If so, I think this may be reflecting the same issue reported here. 

📌 ACTIONS
- Await author feedback

**Comment by daria2303** [comment] 2022-09-19 09:28
@cuemarie thank you!
> Does this test site have the footer credit hidden via the Customizer?
Yes, it does. 

> https://github.com/Automattic/themes/issues/6066 , which based on the comments is impacting more than just the themes in the title.
Agree that it may be the same.

**Comment by cuemarie** [comment] 2022-09-21 00:10
Thanks @daria2303 ! With this in mind, I think it's best we close this issue in favor of https://github.com/Automattic/themes/issues/6066 , and I'll bring over the reports and relevant workaround details. Looks like that report has some traction, so we hopefully will see some movement there! Thanks for staying on top of these requests for more details! 😃

**Closed as completed by cuemarie** 2022-09-21 00:10 UTC
Labels: Bug, [Pri] Normal, Triaged, [Feature] Full Site Editor

**Comment by mgozdis** [comment] 2022-12-22 17:55
I realize this is closed, but adding some relevant information as I am seeing this on test sites I created as well as some user reports in tickets while onboarding. For me, I am seeing `var(--wp--style--root--padding-bottom)`, which is 1rem, being applied to `.wp-site-blocks`. It is happening on plans that should have a footer credit, but the Blank Canvas theme has a bug where the footer credit is never displayed too, which may impact this. 

Rather than custom CSS, a work-around for me was to view the _Global styles_ > _Layout_. In my test cases, padding shows as 0 and simply moving the slider, setting it back to 0, and then saving causes `--wp--style--root--padding-bottom: 0px;` to be applied. 

It seems there are some default padding values being applied globally during site creation that do not match the global settings and simply saving the global settings causes the correct values to be used.
