### ISSUE TITLE
SIte Logo Block: No options to change size

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#71289] opened 2022-12-17 10:11 UTC
### Quick summary

The Site Logo Block used in the Site Editor isn't showing any options to change or set the logo size.

### Steps to reproduce

1. On a Personal Plan site with a Site Editor theme without a set site logo, add a site logo block to the Header or select one of the Header patterns with Site Logos.
2. Choose the logo image
3. Notice how no options to change the size of the logo show

### What you expected to happen

The tools and options to resize the logo as explained in our [support documentation](https://wordpress.com/support/site-editing/theme-blocks/site-logo-block/) to be available.

### What actually happened

There are no options to resize the logo.

### Context

This user asked for help regarding this, here: 5796662-zd-woothemes
We then tested this thoroughly in this Slack thread: p1671268363616429-slack-C03TY6J1A
Behaviour was consistent for me across both Atomic and Simple sites, but not for @syhussaini who could only reproduce this on a site with a personal Plan.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Site Editor themes.

Themes tested so far: Arbutus, Masu, Maverick.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Using an Image Block linking to the Homepage is one of the available workarounds, though certainly not the User experience we want to offer our users.

**Comment by ClassicRKR27** [comment] 2022-12-17 19:48
- [ ] another report here: 38855452-hc

**Comment by metabreakr** [comment] 2022-12-19 15:31
This also happens with Pendant, Meraki and Tú. 

I have been using the image block as a workaround in the meantime.

**Comment by ClassicRKR27** [comment] 2022-12-20 14:44
- [ ] Another instance here with the `Yuga` theme: 5799335-zd-woothemes

**Comment by thesacredpath** [comment] 2022-12-22 04:29
Another report here - Arbutus theme - AT site.

5808349-zen

**Comment by rickmgithub** [comment] 2022-12-22 09:16
5808139-zd

**Comment by zachspears** [comment] 2022-12-28 03:42
Confirmed this bug, and recommend the theme Muscat for testing. Leaving Normal due to impact.

**Comment by jartes** [comment] 2022-12-30 11:00
It could be related to the version of Gutenberg plugin, and it seems that on the version 14.8 will be fixed if I'm not wrong: https://github.com/WordPress/gutenberg/issues/46544

**Comment by supernovia** [comment] 2024-10-10 21:18
📌 FINDINGS/SCREENSHOTS/VIDEO
I just came across this while looking for something else. I tested it on simple and I believe it's solved; we've got oodles of logo size and fit options now!

📌 ACTIONS
- closing :)

**Closed as completed by supernovia** 2024-10-10 21:18 UTC
Labels: Bug, [Pri] Normal, Triaged, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic
