### ISSUE TITLE
Gutenboarding: Entering example.com in domain search shows domains that look like internal attributes

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#49353] opened 2021-01-27 18:33 UTC
### Steps to reproduce the behavior

Prereq. User is signed in.
Prereq. User language is set to English.

1. Add new site (initiate Gutenboarding).
2. Enter any site name in the initial Gutenboarding step.
3. Clear existing domain suggestion and enter `example.com`.
4. Select `object.id` domain name and click next.

#### What I expected to happen
3. I would not expect `.id` domains to show up.
4. If a domain is shown on the `domains` page, I would expect it to be purchasable.

#### What actually happened
3. `object.id` and `form.id` appear to be internal attributes that have leaked through?
4. `object.id` is an unavailable domain, yet it is shown in the `domains` page. Attempting to continue with `object.id` results in an `unavailable` message after a delay.

### Context
User workflow manual testing.

#### Browser / OS version
OS: macOS Catalina 10.15.7
Browser: Firefox Nightly 86.0a1

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
N/A

#### Is there any console output or error text?
N/A

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Minor.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screen Shot 2021-01-27 at 10 05 05](https://user-images.githubusercontent.com/6549265/106037033-fb221400-608a-11eb-8a78-fa68904af7a0.png)
![Screen Shot 2021-01-27 at 10 07 58](https://user-images.githubusercontent.com/6549265/106037039-fc534100-608a-11eb-9e3c-cf4f439a3b9d.png)

https://user-images.githubusercontent.com/6549265/106054943-8c9c8080-60a1-11eb-8ad5-ab81b5028bfe.mov

**Comment by worldomonation** [comment] 2021-01-27 19:29
Not sure why the title was cut off, but I have fixed it.

**Comment by razvanpapadopol** [comment] 2021-01-27 20:32
> If a domain is shown on the domains page, I would expect it to be purchasable.

This is not the case also on `/start` flow. I guess checking the availability for all domain suggestions before the user tries to select them was decided to be a waste of resources / bandwidth. 
cc: @Automattic/cobalt 

<img width="1071" alt="Screenshot 2021-01-27 at 22 25 21" src="https://user-images.githubusercontent.com/14192054/106049213-94cedd00-60ee-11eb-8b8e-fcf6a8c24a98.png">

> I would not expect .id domains to show up.

Yes, indeed. I see the results are quite different from those on `/start` so we should look at the API call parameters to see what's wrong.

**Comment by worldomonation** [comment] 2021-01-27 21:12
> This is not the case also on `/start` flow. I guess checking the availability for all domain suggestions before the user tries to select them was decided to be a waste of resources / bandwidth.

Interesting, I did not know that!

Should I update the bug title to reflect that the issue seems to be different results between `/start` and `gutenboarding` flow?


I have also uploaded a video recording of the flow in question.

**Comment by razvanpapadopol** [comment] 2021-01-27 21:59
> Should I update the bug title to reflect that the issue seems to be different results between /start and gutenboarding flow?

No, adding this information to the description should be enough to help with debugging.

**Comment by klimeryk** [comment] 2021-01-28 08:44
Hi, @worldomonation 👋 I understand that `object.id` could seem like an internal variable name from Javascript, but `.id` is actually a ccTLD (country level TLD) for Indonesia that we do support on WordPress.com 😅 So it _is_ expected to show up - especially for a very generic term like `example`.

> This is not the case also on /start flow. I guess checking the availability for all domain suggestions before the user tries to select them was decided to be a waste of resources / bandwidth.
> cc: @Automattic/cobalt

Yes, given our scale, it'd probably kill our third-party partners API :) It's also not needed in most cases - but for generic searches like yours, the engine struggles with a meaningful suggestion, so you might see some odd ones. Availability checking during suggestion generation is not 100% accurate, because it has to be performant as well. So, there's an additional availability check implemented on our side, just before the user adds the domain to cart, to ensure it's indeed available.

I'm not sure why any of this is new information, though :) There seems to be already an open issue for this? https://github.com/Automattic/wp-calypso/issues/48634 I also thought this was already done in Gutenboarding: https://github.com/Automattic/wp-calypso/pull/45698 Was there a regression?

**Comment by daledupreez** [comment] 2021-01-28 08:47
So I think there are two entangled issues that we should be clear on:
1. `.id` domains are perfectly reasonable suggestions, and they tend to get additional prominence for certain kinds of generic searches. They are also the country-specific TLD for Indonesia, though there has been a push to get them used in contexts related to identification. (The same is true for `.co` and `.me`, the TLDs for Colombia and Montenegro, respectively.)
2. The `form.id` and `object.id` suggestions not being available is a trickier issue. The trouble here has multiple layers:
  - The provider we use for searches doesn't have perfect availability data, and the quality of that data varies from TLD to TLD (I believe it's less good for `.id` in particular)
  - We have some technical limitations on the number of availability checks we can perform, and as a starting point, checking every suggestion we show would almost certainly exceed those limits
  - Separate from the limits, availability checks for some TLDs are _slooow_, with `.id` actually being one of the worst (though the situation should have improved since we last explored the timings)
  - We do make sure that we check availability when users select a domain, as we want to double-check that it's available before they have firmer expectations about the domain being "theirs" (e.g. only checking once we're in checkout)
  - Given the above, paired with the fact that a relatively low percentage of users end up selecting unavailable domains, we decided to settle for the current behaviour.
  - For a _lot_ more context and specifics on the above, see this internal thread p99Zz8-19a-p2#comment-3381

Regarding the different suggestions, the actual API calls look very similar, with the only difference being the fact that one requests a `*.wordpress.com` subdomain suggestion and the other doesn't. I suspect this was likely something coming from our suggestions vendor rather than something in WordPress.com.

**Comment by razvanpapadopol** [comment] 2021-01-29 06:21
> I'm not sure why any of this is new information, though :) There seems to be already an open issue for this? #48634 I also thought this was already done in Gutenboarding: #45698 Was there a regression?

You're right. The availability check is done in Gutenboarding when you press _Continue_ button to confirm the domain selection. The open issue is to do this check when we initialize DomainPicker with a previously selected domain (which might be unavailable).

@worldomonation, since both issues were clarified I think we can close this ticket.

**Comment by Copons** [comment] 2021-01-29 16:07
Closing as not an issue. 🙂

**Closed as completed by Copons** 2021-01-29 16:07 UTC
Labels: Bug, [Pri] Normal, [Feature Group] Emails & Domains, [Source] User testing, [Goal] New Onboarding

**Comment by worldomonation** [comment] 2021-01-29 19:18
Added closure label.

> since both issues were clarified I think we can close this ticket.

Thanks for clarifying the set of behavior described in this issue.

For the domain availability behavior - clarification of how it works under the hood is much appreciated and I will give the P2s a read today.

As for the `.id` ccTLD - there are counterexamples with similarly generic queries returning more relevant suggestions, but it isn't an important issue.
