### ISSUE TITLE
Shortlinks show "301 moved permanently" error when shared in Facebook

### ISSUE THREAD

**Issue by kathleenjross** [Automattic/wp-calypso#63388] opened 2022-05-06 18:03 UTC
### Quick summary

Surfaced in 35404733-hc.

The user reports that when they share the shortlink for a post in Facebook or Twitter, it frequently leads to a "301 moved permanently" error and the post doesn't show.

I was able to reproduce when I got a shortlink and ran it through the Facebook Debugger. It showed the 301 error, but then was fixed if I shared the original post.

Guide to get shortlink: https://wordpress.com/support/shortlinks/#shortlink-from-the-block-editor

### Steps to reproduce

1. On Atomic site, grab a shortlink from a published post.
2. Add to Facebook and share, or got to Facebook Debugger and hit "Debug"
3. You should see "301 moved permanently" error in the Link Preview area

### What you expected to happen

The post should be shared, with a title and image preview.

### What actually happened

You see the 301 error: 

<img width="839" alt="screenshot test" src="https://user-images.githubusercontent.com/14097527/167193293-0a0be130-072e-48ec-b533-c917a57271b8.png">

### Simple, Atomic or both?

Atomic

**Comment by formosattic** [comment] 2022-05-17 09:44
I'm unable to reproduce on my atomic test site.

What  I did:

* Publish a new post
* Scrape the shortlink directly to the debug tool https://developers.facebook.com/tools/debug/

The preview displays fine:
![image1](https://user-images.githubusercontent.com/15944096/168781439-2e473552-30da-4bd5-8941-e25b83896ddb.png)

I suspect it may be some plugin conflict, so worth having users run through this http://en.support.wordpress.com/plugins/#identifying-plugin-conflicts

Closing for now. 
Open only if you can reproduce on your test site. If the issue reappears on the user's site, please post internally first.

**Closed as completed by formosattic** 2022-05-17 09:44 UTC
Labels: Bug, Jetpack
