### ISSUE TITLE
Import: error "failed to load external entity"

### ISSUE THREAD

**Issue by jackiejade** [Automattic/wp-calypso#13156] opened 2017-04-17 19:52 UTC
User on chat has tried to import their WP XML file from their self-hosted installation of WordPress. It is just showing as never ending on their end. I’m seeing it as finished. I’ve downloaded the XML file and tried to import it again on my end.

I ran it through the terminal and got this error:
warning: failed to load external entity “rogerbowman-wordpress-2017-04-12.xml”

When I import the file, I get this error:
Sorry, there has been an error.
This does not appear to be a WXR file, missing/invalid WXR version number

#import 

#user-report

Was fixed in p2UL9c-3pY-p2, with this comment:

There were some weird characters in some comments in the import file. I was able to find and fix them using xmllint.

**Comment by supernovia** [comment] 2017-04-17 22:10
I've had a few cases similar to this, where it shows as finished on our end, but the user sees an indicator saying it's still importing.

**Comment by supernovia** [comment] 2017-07-11 17:47
Just noting another case of this.

**Comment by dllh** [comment] 2017-07-21 18:01
The `restapi_import_manager_data` isn't being cleared or updated properly when the import gets stuck, so figuring out what conditions are leading to that situation and fixing that is the likely root cause fix here.

**Comment by jamiepalatnik** [comment] 2017-12-15 17:14
I think this is a similar case in 849487-zen. I got the same error messages:

In Terminal: 
warning: failed to load external entity “pogadajmyopeerelu.wordpress.2017-12-15.xml”

When I import the file, I get this error:
Sorry, there has been an error.
This does not appear to be a WXR file, missing/invalid WXR version number

**Comment by supernovia** [comment] 2018-08-20 22:10
Another instance here.
https://en.forums.wordpress.com/topic/import-167/#post-3166764

**Comment by rachelmcr** [comment] 2018-08-30 12:06
I tested the export file from the original report and confirmed that the importer gets stuck when I try to import it. I get a spinner that never goes away:

![screenshot 2018-08-30 12 45 41](https://user-images.githubusercontent.com/8658164/44850104-1a1ae280-ac54-11e8-8ec3-cf69bbdc6522.png)

When I check the import job, I get the same error message reported above:
> Sorry, there has been an error.
> This does not appear to be a WXR file, missing/invalid WXR version number

I checked the import file and the underlying issue is ASCII control characters (`SOH` or `<0x01>`) included in spam comments in the export file. In another import file reported here, there was a single character (`SYN` or `<0x16>`) in a comment in the export file. Removing these characters resolves the issue so the import succeeds.

Could we handle these ASCII characters (e.g. find and strip them) before trying to complete the import?

cc @Automattic/delta-samus and @Automattic/tanooki (fyi as you're working on importers)

**Comment by mattsherman** [comment] 2018-08-30 20:08
I removed the `[Pri] High` label as this doesn't seem to occur frequently and the issue has existed for some time. Delta does have this on our radar now though, so we will look into how/when we can address this.

**Comment by mattsherman** [comment] 2018-10-22 22:40
@bisko @pablinos @andfinally Do you think this is a relatively quick fix, and something we might be able to work into one of our current/upcoming importer projects?

**Comment by bisko** [comment] 2018-10-23 09:40
@mattsherman I wouldn't say it would be a "relatively quick fix" as there are some edge cases that might prove our working theory problematic. For example broken characters that appear in serialized data (post meta and such) can cause issues with the imported data. We have to be careful when working with this to make sure we account for them. 

With that said, we can try to scope out the fix and have a preliminary fix in place that we can test with while we manage to catch most issues and then ship to the general public.

**Comment by mattsherman** [comment] 2018-10-23 16:39
Thanks @bisko.

Tracking backend investigation and work here: https://github.com/Automattic/samus-private/issues/34

**Comment by bisko** [comment] 2020-02-21 08:13
I'm going to close this one as I'm not sure this is still happening. We did quite a few improvements to the Calypso importers, especially around broken characters that occur in some XML files.

**Closed by bisko** 2020-02-21 08:13 UTC
Labels: Import, [Type] Bug
