### ISSUE TITLE
Gutenberg: Typing Space in Bold and Italic turns into &nbsp; 

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#30932] opened 2019-02-21 13:15 UTC
#### Steps to reproduce
1. On the paragraph block, add a few line of texts.
2. Convert text on the paragraph block into either bold or italic.
3. Continuing adding more text within the bold/italic style.

#### What I expected
You can continue add more text within the bold/italic without any issues.

#### What happened instead
As you add more text within the bold/italic style, spaces are being added as `&nbsp;` characters.

For example:

"Your dad taught you to drive with half of the truck on dry ground and half of the truck on snow." is seen as:

```
Your&nbsp;dad&nbsp;taught&nbsp;you&nbsp;to&nbsp;drive&nbsp;with&nbsp;half&nbsp;of&nbsp;the&nbsp;truck&nbsp;on&nbsp;dry&nbsp;ground&nbsp;and&nbsp;half&nbsp;of&nbsp;the&nbsp;truck&nbsp;on&nbsp;snow.
```

#### Screenshot / Video

![image](https://cldup.com/NTmrrMhbsw-3000x3000.png)
image link: https://cloudup.com/cItIwc-IhSx

#### Context / Source
* User report: 10397005-hc
* Follow-up: 1819471-zen

####Additional note: 
If you add text before setting them as bold/italic, existing spaces will not convert into `&nbsp;`.

**Comment by arunsathiya** [comment] 2019-02-21 14:54
@edwinho89 I am not able to reproduce - [video](https://cloudup.com/ckSaqGilzEb). Any chance you have a video recording of this behaviour? Happy to test further!

**Comment by edwinho89** [comment] 2019-02-22 15:52
Hi @arunsathiya it took me a little getting used to the new screen recording app, but here you go! - https://cloudup.com/chtm2qbpf6c

It's a little messy, but you should be able to see the results at the end of the post after adding italic text [here](https://ho89test.com/2019/02/22/test-1819471-zen/).

**Comment by howarddc** [comment] 2019-03-27 00:32
I am seeing this behavior as well in latest version of WP with Genesis/Breakthrough Pro theme. It seems to happen on save/update rather than while typing.

**Comment by gwwar** [comment] 2019-10-26 00:22
I'm having a bit of trouble reproducing this one, closing for now since there have been many updates to the rich text editor in the meantime.

**Closed by gwwar** 2019-10-26 00:22 UTC
Labels: Support, [Goal] Gutenberg, [Type] Bug
