### ISSUE TITLE
Editor: Flash of unstyled editor before editor finishes loading

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#18703] opened 2017-10-10 17:17 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Select the "Write" button in the masterbar.
3. Select a site to start a new post.

#### What I expected

I expected the editor to open.

#### What happened instead

I saw a flash of the unstyled editor (with the publish confirmation sidebar info at the top) before the editor loaded. This only seems to happen the first time you open the editor, so if you don't see the issue try doing a hard refresh first.

#### Browser / OS version

Seen on Mac OS 10.12.6 in Chrome 61 and Firefox 56. I didn't see the same issue in Safari 11.

#### Screenshot / Video

![posteditor-flashofsidebar](https://user-images.githubusercontent.com/8658164/31400353-2ff76dd8-ade7-11e7-947b-1cc062a6f70a.jpg)

GIF showing the screen in the flow:

![posteditor-flashofsidebar](https://user-images.githubusercontent.com/8658164/31400329-197a85c2-ade7-11e7-9ee2-09899521a5f6.gif)

#### Context / Source
#manual-testing

**Comment by bisko** [comment] 2017-10-12 06:32
cc @stephanethomas This is the issue I mentioned yesterday.

It's really visible when network throttling is enabled in the Chrome Dev Tools, so it takes longer for the CSS to load.

**Comment by jeremeylduvall** [comment] 2017-10-20 11:51
Also mentioned in #19029.

**Comment by mattsherman** [comment] 2017-10-23 16:40
I too am seeing this daily now. It is quite noticeable.

**Comment by lancewillett** [comment] 2017-10-24 13:12
Testing this today at the Tanooki (Delta) meetup, several people can replicate after a force-refresh in wordpress.com, then opening the editor. @stephanethomas Can you confirm that you’re seeing the same issue?

**Comment by hoverduck** [comment] 2017-10-24 14:00
Here's an animation of it occurring with our e2e testing account (a single-site user) -

![wp-calypso-editor-flash](https://user-images.githubusercontent.com/7233112/31947362-24eaf656-b8a2-11e7-8f31-c0a0dec69b32.gif)

**Comment by hoverduck** [comment] 2017-10-24 14:44
@ryelle - Can you take a look at this and see if it's related to the changes you made in #18823?

cc: @stephanethomas

**Comment by ryelle** [comment] 2017-10-24 15:09
It's not related to my change directly, but it is the CSS splitting - that unstyled view is what happens while post-editor.css is loading, which was a change made in #18194

**Comment by alisterscott** [comment] 2017-10-26 03:34
@stephanethomas: since this looks like it was introduced in your PR (#18194) would you be able to take a look at this issue?

**Comment by stephanethomas** [comment] 2017-10-29 16:36
Sorry for the late reply - I was off last week.

It's lined up first on our Trello board, and hopefully we should be able to fix that this week.

**Comment by alisterscott** [comment] 2017-11-03 05:21
Assigning @stephanethomas as #19396 is WIP

**Comment by lancewillett** [comment] 2017-11-15 23:35
Is this still happening to anyone? I haven't seen it in about a week. Looks like a change hasn't merged yet, though.

**Comment by jeremeylduvall** [comment] 2017-11-15 23:41
I still see it on a clear cache when I toggle my network speed to slow 3g. Once I load the editor and we load the stylesheet, I can then navigate away and come back without experiencing the issue until I do a hard refresh.

**Comment by mattsherman** [comment] 2017-11-16 00:31
I still see this regularly. Just saw it a minute ago actually.

**Comment by alisterscott** [comment] 2017-11-16 04:19
I think the current state of #19396 is a big improvement current functionality so I'd like to see that merged and then subsequent improvements worked on in separate PRs?

**Comment by designsimply** [comment] 2017-12-22 19:30
I have noticed the flash of unstyled editor problem happen more often lately. 

<img width="1280" alt="screen shot 2017-12-22 at fri dec 22 12 28 15 pm" src="https://user-images.githubusercontent.com/1119271/34310283-e7e9531a-e713-11e7-84b2-a0d26ac5401a.png">
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11491 (staging) using Chrome 63.0.3239.84 on macOS 10.13.2.</sup>

**Comment by lancewillett** [comment] 2017-12-22 19:33
Is this one on your radar still, @stephanethomas ? CC @jsnajdr for another 👁 .

**Comment by stephanethomas** [comment] 2017-12-26 09:49
Not really @lancewillett. @designsimply, what exact steps should we follow in order to reproduce that problem? We've addressed many scenarios in https://github.com/Automattic/wp-calypso/pull/19396, but it's possible we've missed a use case.

**Comment by stephanethomas** [comment] 2017-12-26 10:08
Nevermind, I could reproduce it very easily with:

1. Open the [`Site Pages` page](https://wordpress.com/pages) or the [`Blog Posts` page](https://wordpress.com/posts) in a new tab
2. Click the name of any page or post
3. Notice that the editor loads with a flash of unstyled content

I've also found that we don't preload the editor for this scenario:

1. Open the [`Blog Posts` page](https://wordpress.com/posts) in a new tab
2. Click the Edit menu item that appears when you click the three dots in front of each page
3. Notice that the editor loads with a flash of unstyled content

**Closed** 2017-12-26 15:59 UTC
Labels: Editor, [Pri] High, [Type] Bug
