### ISSUE TITLE
Incorrect automatic creation of pages when mp4 videos are uploaded to media

### ISSUE THREAD

**Issue by tiniacoleyba** [Automattic/wp-calypso#84141] opened 2023-11-13 11:18 UTC
### Quick summary

I discovered a prospective bug while helping a friend with her WordPress.com site last weekend. If I upload a mp4 video through the media tab in Calypso on an Atomic WordPress.com site, a new page is automatically created for my site with the name of the video. For example, if the video file name is my-video.mp4 and the website is mywebsite.com, a new page will be created at mywebsite.com/my-video-mp4. 

- The site where I found the bug is doctorabelen.com. She uploaded multiple videos to her site through media on Calypso.
- These videos are now available doctorabelen.com/{video-file-name}-mp4
- She doesn't want those pages automatically created when she uploads a video. I agree. This doesn't seem to be the usual WordPress behavior. Could It be some custom code we are configuring on top of WordPress?
- Moreover and more dangerous, even videos marked as private on the video settings on media are displayed on those pages, and anyone can play them logged out. More interestingly, not all private videos can be played on those automatically created pages, but there is an automatically created page for every video she uploads. For example, both private videos "huesos.mp4" and "infarto-de-corazon.mp4" automatically created the pages "doctorabelen.com/huesos-mp4" and "doctorabelen.com/infarto-de-corazon-mp4", both are private, one of them can be played on that page but not the other one. I believe the privacy issue is a separate one, which might be an ongoing issue potentially related to [#33975](https://github.com/Automattic/jetpack/issues/33975) and [#33293](https://github.com/Automattic/jetpack/issues/33293). Notice that for "doctorabelen.com/infarto-de-corazon-mp4" the video doesn't play because the VideoPress player says the video doesn't exist, but it does exist. It is just marked as private, which can be confusing. That might be another feature or bug in itself.
- We were able to fix the private video issues by installing the JetPack VideoPress plugin, which is not installed by default in Business plans, which signals an integration problem between JetPack VideoPress and Atomic sites. As soon as we deactivated the VideoPress plugin, some of the private videos became playable for logged-out users on doctorabelen.com/{video-file-name}-mp4

### Steps to reproduce

Automatic video page creation:
1. Go to a WordPress.com Atomic site (It happened on a Business subscription on doctorabelen.com)
2. Go to the media tab and upload an mp4 video (note the file name)
3. Once the video upload is complete, navigate to yourwebsite.com/your-video-name-mp4
4. A new page was created with the video's name and automatically published with it.

Playable private videos while logged out:
1. Mark the above video as private on the video details on the media tab. Save the changes.
2. Navigate to {thewebpage}/{video-file-name}-mp4
3. Sometimes, you can play the video logged out on another device. The behavior is chaotic, and I couldn't find out why some private videos are playable and logged out and others are not. However I suspect that it has to do with how the video was uploaded, through the media tab on Calypso or a video block with the Gutenberg editor on a post.

### What you expected to happen

I expected nothing to happen. I didn't expect a new page to be automatically created every time I upload a video to the media library. WordPress does not typically create new pages automatically when a video is uploaded to the media library if I recall correctly.

### What actually happened

There was a new page automatically created and published at {website}.com/{video-file-name}-mp4

The behavior may result from a specific theme or plugin that I had installed on the WordPress site. So I enabled the troubleshooting mode and switched themes, deactivated every plugin, and the page was still there if the video was on media even with no plugins installed and with different themes, even the default ones such as twenty-twenty-one.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

- Theme: I tried multiple themes. The behavior seemed to happen with every theme I tried.
- Plugins: I tried deactivating all plugins and troubleshooting the site. The page was automatically created as long as the video I uploaded was on media. Even with all plugins deactivated.

**Comment by liviopv** [comment] 2023-11-18 15:50
📌 REPRODUCTION RESULTS
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
Expected behavior, they are [attachment pages](https://developer.wordpress.org/themes/template-files-section/attachment-template-files/)

📌 ACTIONS
- Closed by design 

📌 Message to Author
@tiniacoleyba that's expected behavior. Those pages are [Attachments](https://developer.wordpress.org/themes/template-files-section/attachment-template-files/), which are custom post type designed to serve media files in a single place. It happens with both images and videos.

**Closed as completed by liviopv** 2023-11-18 15:50 UTC
Labels: Bug, [Pri] High, [Feature] Media, Needs triage, [Platform] Atomic, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Content Management
