### ISSUE TITLE
Purchases: Allow users to remove purchases from their account

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#2199] opened 2016-01-07 19:30 UTC
Right now, when a user clicks through 'Manage Purchase' to cancel a purchase, we disable auto-renew on the purchase. The user then sees a notice on the 'Manage Purchase' page for this purchase indicating that the purchase will be removed once it expires. There is no way, at this point, to fully cancel the purchase and have the e.g. plan removed from their account.

After a couple discussions (p1452193266003544-slack-store and p6qnuF-Rp-p2), the general consensus so far seems to have been that we should allow users to remove subscriptions from their account entirely.

One aspect of this issue that might be tricky is the fact that we currently refer to disabling auto-renew as 'Canceling'. We'll probably need another verb/phrase to differentiate removing a purchase.

@fabianapsimoes I saw some similar issues, so please let me know if this issue already exists.

cc @BandonRandon @supernovia

**Comment by BandonRandon** [comment] 2016-01-07 23:09
> One aspect of this issue that might be tricky is the fact that we currently refer to disabling auto-renew as 'Canceling'. We'll probably need another verb/phrase to differentiate removing a purchase.

I'm wondering if we can add a new action, something like "Cancel and Remove" and make it clear there is a difference between the two. 
![screenshot_07-01-2016-15 05 59](https://cloud.githubusercontent.com/assets/150348/12185534/45df9774-b550-11e5-968b-b8efe610ad9d.png)

This could even be two buttons. I'll let the designers figure out the best way to display it, but I think they should be two different options. We could even maybe show an overlay like we do for adding privacy after cancel is clicked letting them to choose to remove it or not. I don't think we need to find a new word.

**Comment by fabianapsimoes** [comment] 2016-01-08 09:48
@drewblaisdell closing this as a duplicate of https://github.com/Automattic/wp-calypso/issues/1402

@BandonRandon I've posted your suggestion to the other issue.

**Closed by fabianapsimoes** 2016-01-08 09:48 UTC
Labels: Purchases, [Type] Enhancement
