### ISSUE TITLE
Reader: back button missing in full post on mobile

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#20597] opened 2017-12-07 15:08 UTC
@shaunandrews noticed that we have some layout regressions in full post on mobile:

![_720](https://user-images.githubusercontent.com/17325/33721924-5a85208a-db60-11e7-955b-8db62149252b.png)

The back button is present but is hidden behind the masterbar.

**Comment by jancavan** [comment] 2017-12-07 17:32
I'm seeing some alignment issues on the byline, but I think it's because we put the gravatars on top of the blavatars and this one doesn't have a blavatar.

**Comment by jancavan** [comment] 2018-02-06 03:21
This is a duplicate of: https://github.com/Automattic/wp-calypso/issues/19948 so closing.

**Closed by jancavan** 2018-02-06 03:21 UTC
Labels: Reader, [Type] Bug
