### ISSUE TITLE
Reader: Following/Unfollowing from full post view closes modal

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#686] opened 2015-11-24 21:24 UTC
Steps to reproduce:

1. Open any post in the full post view
1. Click on the '...' menu
1. Click on follow (or unfollow depending)

<strong>Result:</strong> Boom! The modal closes.

![single-post-menu-clicks](https://cloud.githubusercontent.com/assets/66797/10090485/dffaf3c6-62e4-11e5-90d6-23da0c8f4a60.gif)

From blowery:

<blockquote>The popover component attaches it's nodes outside the dialog that contains it. Clicks on those nodes are intercepted by the listener that the Dialog attaches to the root, and then the dialog closes.

Maybe we should stopProp on popover clicks. I'm generally not a fan of stopProp, but .... seems like a sane case here.</blockquote>

<blockquote>Can't use stopPropagation because of how React binds events. DOM events are bound to the document element, same as the clickOutside handler that the Dialog uses, and the Dialog's handler ends up firing first. Stopping the event has no effect.</blockquote>

<blockquote>You have two overlays that are both bound to the root of the document that are trying to pick up clicks outside the Dialog. We'd need to either root the popover inside the Dialog, which breaks it being able to render outside the bounds of the Dialog, or somehow teach the Dialog to ignore clicks from certain roots.

Or we could drop the Dialog entirely and move to a solution where we don't use an overlay / dialog to show full posts.</blockquote>

**Comment by vsukhomlinov** [comment] 2015-11-26 07:22
@blowery Current popover can only be attached to document.body by design https://github.com/component/tip/blob/master/index.js#L204
So how about making Dialog ignore clicks from .popover nodes?

**Comment by blowery** [comment] 2015-12-02 20:26
> So how about making Dialog ignore clicks from .popover nodes?

Yup, I think that's what we're going to have to do.

**Comment by dongseok0** [comment] 2015-12-02 22:30
Hi guys,

The full post view is closing not only following button but also any click on popover view even just click on divider too.

It seems full post component is wrapped by dialog and dialog's [clickOutside](https://github.com/Automattic/wp-calypso/blob/master/client/components/dialog/dialog-base.jsx#L40) is problem.
And I thought clickOutside handler should not attached for full screen dialogs. So I tried to use isFullScreen property but there are a number of components already use dialog and isFullScreen prop is used as default true. 

Finally, I just intercept onClickOutside prop from full-post component to prevent default action.
https://github.com/Automattic/wp-calypso/pull/1208

**Comment by blowery** [comment] 2015-12-04 01:47
Closing thanks to @dongseok0 !

**Closed** 2015-12-04 01:47 UTC
Labels: Reader, [Pri] High, [Type] Bug
