### ISSUE TITLE
Problems with Calypso on iOS

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#36714] opened 2019-10-14 11:54 UTC
### Expected behavior
The text editing area for posts should fill more of the screen than just a couple of lines

### Actual behavior
There are only a few lines of editing space e.g. https://cld.wthms.co/Lx0dqI

### Steps to reproduce the behavior
* Using the normal WordPress website but on a mobile device ie not using the app
* Go to edit a post.
* Only a few lines of editing space appear
* Editor is set to use the classic editor
* User says it's happened since updating to iOS 13 on an iPhone XS
* Screenshot - https://cld.wthms.co/Lx0dqI
* This was tested on Firefox too and produced this - https://cld.wthms.co/gkEC9t
* Tested in browserstack but couldn't recreate it with the iPhone XS and iOS13
* Simple site, Premium plan (no plugins)
* 2411978-zen

##### 
iPhone XS iOS 13, multiple browsers (Safari/Firefox)

**Comment by rachelmcr** [comment] 2019-11-11 11:17
Closing this as a duplicate of https://github.com/Automattic/wp-calypso/issues/36763, since there is more discussion on that issue. Thanks for the report!

**Closed by rachelmcr** 2019-11-11 11:17 UTC
