### ISSUE TITLE
Editor: drafts count doesn't account for capabilities

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1806] opened 2015-12-18 14:35 UTC
Raised by @aduth 

![Drafts](https://cloud.githubusercontent.com/assets/1779930/11127167/dd22aeb4-8940-11e5-9896-fc69cda9f095.png)

**Steps to reproduce:**
1. Log in as a user with Author or Contributor role assigned
2. Navigate to https://wordpress.com/post
3. Select a site
   - The chosen site should have posts drafted by other authors
4. Note that the Drafts counter displays all drafts for the site
5. Click Drafts
6. Note that only drafts written by the user themselves are shown

**Expected result:**

The draft count should only reflect the number of posts which are presented as options for the current user.

**Actual result:**

The draft count reflects all drafts for the site, even those which aren't accessible for the current user.

Notes from @rachelmcr 

> For comparison, when an Author or Contributor visits <a href="https://wordpress.com/posts/drafts/">My Sites > Blog Posts</a> and selects "Everyone" they also see the full drafts count, even those which aren't accessible for the current user.
> 
> This screenshot shows the count that shows for an Author who only has 2 drafts on the site (and only 2 draft posts appear in the list):
> 
> ![screen shot 2015-11-13 at 1 43 27 pm](https://cloud.githubusercontent.com/assets/8658164/11147285/c8266e3e-8a0c-11e5-904f-0770593929d3.png)

Reply from @mtias 

> I'd be ok moving to just the user for the list and the count.

**Comment by lancewillett** [comment] 2017-02-16 19:29
This seems related to multi-user sites, since you can filter you/everyone in the UI, and the counts should update accordingly.

Matt recently reported this on ma.tt:

> there are 6 drafts [in the right sidebar], when the page gets skinny and it puts drafts in the menu — it only says there's 1"

<img width="558" alt="screen shot 2016-12-12 at 4 14 08 pm" src="https://cloud.githubusercontent.com/assets/66797/23036927/d6feb254-f441-11e6-8e3f-b7ed0e1965e1.png">

I wasn't able to reproduce this exactly but wanted to note it here — could be Jetpack specific, with a site with multiple authors.

Possible related:
- https://github.com/Automattic/wp-calypso/issues/9871
- https://github.com/Automattic/wp-calypso/issues/1806
- https://github.com/Automattic/wp-calypso/issues/1231
- https://github.com/Automattic/wp-calypso/issues/10550
- https://github.com/Automattic/wp-calypso/pull/8406

Here's a quick screencast, testing this on a Jetpack self-hosted site editing in Calypso.

I _think_ this indicates this is fixed now.

![drafts-count](https://cloud.githubusercontent.com/assets/66797/23037415/7a8442a8-f443-11e6-9210-bc9236c1d652.gif)

**Comment by lancewillett** [comment] 2017-02-16 19:29
If you notice this behavior again — multiple authors, draft counts are NOT accurate in both the sidebar and the section nav — please re-open.

**Closed by lancewillett** 2017-02-16 19:29 UTC
Labels: Editor, [Type] Bug
