### ISSUE TITLE
Plan cancellation after upsell/upgrade does not give full refund

### ISSUE THREAD

**Issue by senff** [Automattic/wp-calypso#17377] opened 2017-08-21 01:42 UTC
#### Steps to reproduce
1. Purchase a Personal Plan
2. Upgrade to Premium Plan (pay the difference only)
3. Cancel Premium Plan

#### What I expected
It should be either:
- downgrade to the **Free** plan and give a refund for the **full** amount, OR
- downgrade to the **previous** plan and give a refund for the **upgraded** amount (difference between plans)

#### What happened instead
Plan is now Free plan, but only the _difference_ between Personal plan and Premium plan is refunded. If the user wants the remaining amount refunded, they will need to specifically ask for it through Support.

#### Screenshot / Video
https://cloudup.com/csLsN5ztAj4

#### Context
Somewhat related to https://github.com/Automattic/wp-calypso/issues/2177 which is more focused on the actual message (see screenshot above).
The issue is closed, because the actual message is correct and represents the amount that will be refunded.

Reproduced with username **senffpaymenttest** (remaining amount has not been refunded yet from Store Admin to give you some time to see the error)

**Comment by thehenrybyrd** [comment] 2017-08-22 09:26
Thank you for creating this issue!
I see this quite frequently, and it definitely frustrates and confuses our users.
I agree with your expectation that _either_ a full refund should be given _or_ the previous plan should be used.
We could even give the user the choice!

**Comment by melanieharari** [comment] 2017-08-22 21:22
This is a known issue, unfortunately. A related issue is here: #2048

**Comment by senff** [comment] 2017-09-09 11:18
> Reproduced with username senffpaymenttest (remaining amount has not been refunded yet from Store Admin to give you some time to see the error)

Refunded myself the remaining amount, just in case I would forget later -- but you can see the flow in the SA: https://wordpress.com/wp-admin/network/wpcom-paid-upgrades.php?action=txn_id_search&paypal_txn_id=stripe_ie%3Ach_1At4KgEBJVABl8iBV8yTeMdF

**Comment by GeoJunkie** [comment] 2017-10-05 18:01
User encountered same issue: [#](https://mc.a8c.com/support-stats/happychat/transcript.php?id=678482)
SA: https://wordpress.com/wp-admin/network/wpcom-paid-upgrades.php?action=search&username=snmorganufl

Purchased Personal Plan, then upgraded to Premium. Then decided they didn't want Premium and cancelled the upgrade. Reverted to Free but was only refunded the upgrade amount.

**Comment by prettyboymp** [comment] 2018-07-17 20:33
This was fixed back in 2018/02/05, please reopen if it's still an issue.

**Comment by Gustavo-Hilario** [comment] 2024-01-25 18:57
I don't think this is fixed yet because what we would expect isn't what is happening yet. We don't do full refunds and don't downgrade to the previous plan.

I think in this specific scenario, when the user upgrades from plan X to Z and wants to cancel plan Z, we should have the option to go back to plan X. I think it makes sense whether plan X is or isn’t out of the refund period as they have paid for it!

**Comment by OmarFPG** [comment] 2024-01-25 19:03
7635009-zen
7312929-zen

**Comment by OmarFPG** [comment] 2024-01-25 19:03
Maybe we can provide users an option to cancel & refund the upgrade → go back to the previous plan option if it was an upgrade instead of a first-time purchase, and the upgrade is still within the refund window.

**Comment by michaeldcain** [comment] 2024-05-31 09:24
This was raised in Slack: p1717129723367469-slack-C0117V2PCAE

I've moved it to the Shilling Inbox to investigate.

**Comment by DavidRothstein** [comment] 2024-05-31 14:38
>#### What I expected
>It should be either:
>- downgrade to the **Free** plan and give a refund for the **full** amount, OR
>- downgrade to the **previous** plan and give a refund for the **upgraded** amount (difference between plans)

As far as I know we already do the first, so I think we can close this issue.  The second seems like a feature request and is tracked at https://github.com/Automattic/payments-shilling/issues/1401.

As for the "purchase + immediately renew + cancel/refund" bug (in the comment above mine), that is actually at c/lSOH1Vyi-tr/313-making-multiple-payments-and-then-cancelling-within-the-refund-window-only-refunds-the-last-payments but we should probably move it to GitHub instead.  As far as I know, it does not require any refunds through Store Admin to reproduce this -- should be reproducible if you just go to cancel the plan in Calypso after you renew it.  In Slack, @michaeldcain pointed out that it's related to https://github.com/Automattic/payments-shilling/issues/1340 also (which I guess is more of a feature request, but is potentially a different way to solve it).

I'll leave this in the Inbox for now so we can figure out how to sort everything out.

**Comment by DavidRothstein** [comment] 2024-05-31 14:45
>c/lSOH1Vyi-tr/313-making-multiple-payments-and-then-cancelling-within-the-refund-window-only-refunds-the-last-payments

Sigh, that doesn't seem to be generating the link correctly and I have no way to put the actual link here.  I put it at https://github.com/Automattic/payments-shilling/issues/1340#issuecomment-2142424851 instead (for those who have access).

**Comment by DavidRothstein** [comment] 2024-08-13 21:19
>As for the "purchase + immediately renew + cancel/refund" bug (in the comment above mine), that is actually at c/lSOH1Vyi-tr/313-making-multiple-payments-and-then-cancelling-within-the-refund-window-only-refunds-the-last-payments but we should probably move it to GitHub instead.

Now moved here: https://github.com/Automattic/payments-shilling/issues/3043

Closing this issue.

**Closed by DavidRothstein** 2024-08-13 21:19 UTC
Labels: [Type] Bug, [Feature] Plans & Upgrades, [Feature] Purchase Management, [Feature Group] WPCOM Store & Purchases, Customer Report, [Pri] TBD
