### ISSUE TITLE
Site Editing (FSE): Missing fonts 

### ISSUE THREAD

**Issue by wpshellbelle** [Automattic/wp-calypso#73776] opened 2023-02-24 17:22 UTC
### Quick summary

FSE themes, or Site Editing themes, are suddenly missing several font options in Styles in the Site Editor. 

User reported user FSE theme Heiwa. They had **Source Sans Pro** set for Headings and Text and **Montserrat** set for Hadings. Suddenly, fonts changed on site and Source Sans Pro and Montserrat are not available. Styles in Site Editor shows font is set to **Default**. 

This issue is only present on Atomic sites. Simple sites using same theme has all font options while Atomic sites have limited font options. 

Could this me related to the recent update to WordPress.com Editing Toolkit? 

### Steps to reproduce

1. Activate theme Heiwa
2. Access Site Editor
3. Find that Source Sans Pro and Montserrat (and many other) font options are not available 

### What you expected to happen

I expected to be able to use any of the fonts I can use on a simple site on the same theme on my Atomic site. 

### What actually happened

Limited font options are available. Source Sans Pro and Montserrat are not available. 

Atomic fonts available:

<img width="323" alt="Screen Shot 2023-02-24 at 12 19 18 PM" src="https://user-images.githubusercontent.com/77413972/221245381-5bb95e19-d247-476c-996a-d6cbf22f28df.png">

Simple site fonts available: 

https://user-images.githubusercontent.com/77413972/221245755-5388650d-3751-4824-a731-1d40bd4597d4.mp4

Both sites are using the same font. 

### Impact

Most (> 50%)

### Available workarounds?

Deactivate Gutenberg or add custom CSS like: 
```
html {
font-family:"DM Sans"!important;
}
```

### Platform (Simple and/or Atomic)

Atomic

**Comment by synora** [comment] 2023-02-24 17:23
Another report about this is in 5989831-zen.
Theme: Meraki.

**Comment by wpshellbelle** [comment] 2023-02-24 17:24
5989952-zen

**Comment by connorhipps** [comment] 2023-02-24 19:18
5990344-zd-woothemes

**Comment by connorhipps** [comment] 2023-02-24 19:18
5990344-zen

Theme: Heiwa

Fonts: **Open Sans** was converted to **Times**.

**Comment by mgozdis** [comment] 2023-02-24 19:31
36880118-hc
Theme: Quadrat White

Missing Arial and Mayweather over night.

**Comment by hacchism** [comment] 2023-02-25 23:51
5992266-zen
Theme: Heiwa

Missing DM Sans, Inter, and IBM Plex Mono

**Comment by cat-og** [comment] 2023-02-26 01:03
Another two cases, 5994472-zen with the Appleton theme 

and 5994455-zen with the Zoologist theme. 

In both cases, Open Sans was converted to Times.

**Comment by sudeepbaral** [comment] 2023-02-26 10:01
- [ ] 5993527-zen

Theme: Quadrat Red

**Comment by retnonindya** [comment] 2023-02-27 04:54
5997505-zd-woothemes
Theme: Appleton 
Missing fonts: Raleway and Open Sans

Please update the user once the issue is resolved. Thanks!

**Comment by Gustavo-Hilario** [comment] 2023-02-27 16:06
Another report: 36214661-hc
**Theme: Marl
Font: Roboto**

**Comment by ariel-maidana** [comment] 2023-02-27 17:30
5999331-zd-woothemes
Theme: Quadrat Green
Font: DM Sans

Workaround applied. Please notify the user once resolved.

**Comment by mgozdis** [comment] 2023-02-27 19:53
41086839-hc
Theme: Heiwa
Font: Red Hat Display

**Comment by mdtanjid0** [comment] 2023-02-28 10:26
Theme: Quadrat Red
Missing font: Futura

- [ ] 5998834-zen ( needs to follow up ). 

Update: the user later mentioned that they're unsure if that's the Futura font, but it was similar.

**Comment by kavyagokul** [comment] 2023-02-28 11:53
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate 
- Tested on AT - Replicated 
- Tested on Self-hosted - Replicated 
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Only happens with the Gutenberg plugin active
- Doesn't happen on self-hosted, even with the Gutenberg plugin active'
- Nothing changes with or without the `WordPress.com editing toolkit`

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by jartes** [comment] 2023-02-28 12:15
40908033-hc
Theme: Quadrat White
Font: DM Sans

Deactivated Gutenberg in the meanwhile.

**Comment by crisbusquets** [comment] 2023-02-28 14:39
5999732-zen.
Theme: Meraki.
Font: they had Roboto but now it has disappeared (screenshot attached). It loads Jost and Times instead.

![image](https://user-images.githubusercontent.com/25607244/221885848-73d37599-f9c3-495f-b49d-d3537a5c87c1.png)

**Comment by upwardmomentum84** [comment] 2023-02-28 15:52
Another case: 40886255-hc

Theme: Russell

**Comment by kimerlin81** [comment] 2023-02-28 16:05
Reported here: 38340558-hc
Theme: quadrat-white

**Comment by jromales** [comment] 2023-03-01 03:18
Another report in 37139143-hc
Font: DM Sans
Theme: Zoologist

**Comment by sudeepbaral** [comment] 2023-03-01 07:25
- [ ] 5999978-zen

Theme: Appleton

**Comment by devNigel** [comment] 2023-03-01 08:54
Another report: 6004885-zd-woothemes

Font: DM Sans
Theme: Blank Canvas

**Comment by jartes** [comment] 2023-03-01 13:49
39166542-hc

Font: System Font
Theme: Barnett

**Comment by jorpdesigns** [comment] 2023-03-01 15:01
- Reported in 38531230-hc
- Theme: Meraki / Font: Nunito
- [ ] Follow Up: 6005917-zd-woothemes

**Comment by Gustavo-Hilario** [comment] 2023-03-01 15:10
Another report: 41152479-hc

**Font: Default → DM Sans
Theme: Quadrat Yellow**

**Comment by Gustavo-Hilario** [comment] 2023-03-01 17:59
Another report: 36562804-hc

**Font: Default → DM Sans
Theme: Attar**

**Comment by Gustavo-Hilario** [comment] 2023-03-01 18:29
Another report: 38928305-hc

**Font: Default → DM Sans
Theme: Jackson**

**Comment by thekingsprojects** [comment] 2023-03-02 00:47
Another case here: 6007310-zd-woothemes

Using Quadrat White theme. The theme originally had Poppins set, but Poppins is now missing from the list and replaced with a default "serif" font. (I was also unable to find Poppins on a test site with Zoologist.)

Deactivating Gutenberg restores the font, so offered that to the user as a workaround.

**Comment by retnonindya** [comment] 2023-03-02 06:12
6006612-zd-woothemes

The theme is a third-party theme (ColorMag) but the user noticed the font is missing from the font dropdown box in the editor.

**Comment by rw-ye** [comment] 2023-03-02 06:33
6005999-zd-woothemes 

Font: DM Sans
Theme: Attar

**Comment by mxhassani** [comment] 2023-03-02 15:28
6008568-zd-woothemes

Font: DM Sans
Theme: Attar

Workaround: Deactivate Gutenberg.

Updated report to highlight available workarounds.

**Comment by essleeung** [comment] 2023-04-22 16:32
~~Another case here: 6222005-zd-woothemes~~
Only these fonts show up- Default, DM Sans & Space Mono
Theme: Thriving Artist

EDIT: Probably not a case of this, since I fixed it by Installing Gutenberg.

**Comment by cuemarie** [comment] 2023-05-17 00:28
📌 ACTIONS
- Moving over to @Automattic/t-rex instead of Cylon.

**Comment by BogdanUngureanu** [comment] 2023-05-29 14:39
I wasn't able to reproduce this issue anymore with GB 15.8.1 and the Heiwa theme. I'm closing this issue. :)

**Closed as completed by BogdanUngureanu** 2023-05-29 14:39 UTC
Labels: Bug, [Pri] High, Triaged, [Platform] Atomic, [Interaction #] > 10
