### ISSUE TITLE
Submenu and overlay text color not working

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#66569] opened 2022-08-15 12:56 UTC
### Quick summary

The sub-menu and overlay text controls are not assigning the color to the menu. 

### Steps to reproduce

Set up a menu with a submenu in the site editor
Set the colors for the submenu.
Video of problem -

https://user-images.githubusercontent.com/13706336/184638941-2f37ebaf-a850-4391-abbd-89b521f89ef8.mov

 

### What you expected to happen

The choice of color to be reflected on the site.

### What actually happened

The color remained black.

### Context

5476916-zd

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Happens on both Wingel and Blank Canvas

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Joshgrygiel** [comment] 2022-08-16 19:08
📌 SCRUBBING
- Tested on P2 ❌
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅  
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- After testing on Simple/AT/SH I was able to confirm that the submenu text color does not change from blank, no matter which color it is set to within the Navigation Block Color settings:

![Proofofnavcolor](https://user-images.githubusercontent.com/88345647/184961581-4eb615d2-10a5-4129-8122-c37e5f299ce3.png)

LIVE VIEW (No color change): 

![NavTextColor](https://user-images.githubusercontent.com/88345647/184960880-addbfd75-7a71-4ff2-bc5f-651c3f252657.png)

📌 ACTIONS
- Closed as duplicate of https://github.com/WordPress/gutenberg/issues/41146

**Closed as completed by Joshgrygiel** 2022-08-16 19:08 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Simple, [Platform] Atomic
