### ISSUE TITLE
File block: PDF not embedding on Safari

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#83224] opened 2023-10-19 05:46 UTC
### Quick summary

Embedded PDF on Safari web browser is not loading

### Steps to reproduce

1. [Embed PDF on file block](https://wordpress.com/support/embed-a-pdf-file/) on a page or post
2. Enable "Show inline embed" on file block
3. Preview the embedded PDF on Safari web browser

### What you expected to happen

Embedded PDF loading as expected

### What actually happened

The embedded PDF isn't loading, and from Web inspectir, you can see multiple errors 404 relating to Gutenberg 16.8.1 plugin.

![image](https://github.com/Automattic/wp-calypso/assets/34882260/1696ca0d-cb4f-4189-9f82-c99ba0c264df)

Also reproducible when viewing https://wordpress.com/support/embed-a-pdf-file/ on Safari

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- Deactivate Gutenberg v16.8.1 plugin on Atomic sites

**Comment by edwinho89** [comment] 2023-10-19 05:47
7187451-zd-a8c

**Comment by cuemarie** [comment] 2023-10-19 18:40
📌 REPRODUCTION RESULTS

- Replicable outside of Dotcom – **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
I can replicate this on a self-hosted site not connected to WordPress.com, starting with Gutenberg v16.7.0.

📌 ACTIONS
- Triaged
- Reported here: https://github.com/WordPress/gutenberg/issues/55493

**Comment by mgozdis** [comment] 2023-10-28 18:23
Additional report here: 7229622-zd-a8c

Disabling "show inline embed" is a workaround.

**Comment by cuemarie** [comment] 2023-10-30 19:03
This was fixed at the Core level with https://github.com/WordPress/gutenberg/pull/55667

📌 ACTIONS
- Retested today by checking https://wordpress.com/support/embed-a-pdf-file/ in Safari, and it's now working as expected!
- Closing as resolved.

**Comment by mgozdis** [comment] 2023-11-14 22:53
User reporting a newish instance of this on a Simple site: 7304933-zd-a8c

I am able to reproduce on a Simple site with comments enabled on the post/page that has the embedded PDF and seems partially related to this bug: https://github.com/Automattic/wp-calypso/issues/84132

It appears to potentially be affecting the 20% of Simple sites using Verbum p7DVsv-j4Q-p2, which this site is. It also works on my test site when unproxied, since Verbum only loads when proxied. Is there a way to disable Verbum on this site to determine if it's the cause or not?

**Comment by dhackneya8c** [comment] 2024-05-13 19:59
Another report of this issue in 8183827-zd-a8c on a simple site. Able to replicate on a test simple site as well.

**Comment by deancroyal** [comment] 2024-05-22 14:58
Another report here 8224188-zd-a8c on a simple site. 

I created a test site and tested across several free themes and found the same issue to persist consistently across them all. In fact, I could not get PDF inline embed to work on any theme I tried. I experienced the same result on both Safari and Chrome web browsers.

**Comment by nazilya06** [comment] 2024-05-22 15:39
Reopened the issue as we have new reports.

**Comment by annezazu** [comment] 2024-09-10 21:29
The original Gutenberg issue was never reopened so I reopened it so we can track this going forward: https://github.com/WordPress/gutenberg/issues/55493

**Comment by annezazu** [comment] 2024-09-11 21:33
Closing back out as it cannot be replicated! Let’s reopen if there are more recent reports.

**Closed as completed by annezazu** 2024-09-11 21:33 UTC
Labels: Bug, [Pri] Normal, [Status] Core Fix Needed, Triaged, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks
