### ISSUE TITLE
Widget block editor causes 500 internal server error

### ISSUE THREAD

**Issue by stronenv** [Automattic/wp-calypso#58742] opened 2021-12-02 10:50 UTC
### Quick summary

Following up on this ticket 4562105-zd-woothemes further troubleshooting caused an error in the widget area: 

- Enabling the widget block editor is causing the widget editor to serve a 500 internal server error to the backend widget area. 
- Also, when using the old widget editor moving widgets from Primary Sidebar to Inactive Widgets works for some widgets, but not all. I.e. moving all widgets to Inactive widgets and reloading the page causes "Search", "Categories", and "Follow Blog:" to reappear in the Primary Sidebar area.
- Changing the order of widgets in the old editor works as expected.
- There is an error in the console for widgets.php:
`Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://site.url/wp-admin/') with script ('https://site.url/?service-worker'): The script resource is behind a redirect, which is disallowed.`

### Steps to reproduce

1. Enable the widget block editor
2. Go to the widget editor

### What you expected to happen

The widget block editor should be in use but perhaps display an error message.

### What actually happened

500 Internal server error. 

### Simple, Atomic or both?

Simple

### Theme-specific issue?

The site has Twenty Fourteen as the active theme.

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

It's possible to change the order and content of the widgets using the old widget editor.

**Comment by jartes** [comment] 2021-12-03 15:30
Had another report on an Atomic site here: 4566493-zd-woothemes

I was able to reproduce on an Atomic test site, getting the following error: 

```
TypeError: Cannot read properties of null (reading 'scrollTop')
    at https://example.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=56ef77368d5b1dcf18d4c1f510f4780a:69:1731
    at Bj (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:144:41)
    at Qj (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:176:361)
    at unstable_runWithPriority (https://example.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at eb (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:170:163)
    at gf (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:317)
    at https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:230
    at unstable_runWithPriority (https://example.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
```

**Comment by jartes** [comment] 2021-12-04 11:05
Another one on 33047027-hc

Installed Classic Widgets plugin as a workaround.

**Comment by formosattic** [comment] 2022-01-25 07:16
This looks very similar to https://github.com/Automattic/wp-calypso/issues/58835#issuecomment-1009730632 , Widget block editor also crashed on Simple site using Twenty Fourteen. Will close this one in favor of the other bug report.

Also noting that I can't reproduce this issue on Simple or Atomic site.

@jartes : is there any way you can see if you can reproduce the issue? If so, can you share the steps and reopen this? Thanks.

**Closed as completed by formosattic** 2022-01-25 07:16 UTC
Labels: Bug

**Comment by Greatdane** [comment] 2022-02-04 05:22
We had another report here, but used customizer as a work around. 4731037-zd-woothemes
