### ISSUE TITLE
Editor: On pages turn likes and sharing buttons OFF by default

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#37283] opened 2019-11-03 20:04 UTC
They are on, and often this looks bad on our gutenberg template-first themes. There's also no block representation of these options. They can be turned off and on in the Jetpack menu in the editor, which is also confusing for users.

**Comment by apeatling** [comment] 2019-11-06 23:14
@adamziel Would Zelda be able to take this one? I think @michaeldcain mentioned that yesterday. It's also possible I made that up.

**Comment by donalirl** [comment] 2019-11-08 00:14
I came here to report the same thing! Nowadays I get on average 10 requests per week asking how to turn them off.

**Comment by apeatling** [comment] 2019-11-08 03:10
Thanks for that data point @donalirl

**Comment by michaeldcain** [comment] 2019-12-06 14:24
From #37886 

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/
2. Follow the steps to create a new site
3. When landing in calypso, go to Tools > Marketing > Sharing Buttons
4. Check if the options show that sharing buttons are enabled for pages

#### What I expected
To not see it enabled for pages, but they are enabled by default. The buttons are not well suited for pages - they show on the site as unintended, and outside of the context of the layout and design associated with the rest of the page content, like regular buttons and other text on the site. The color palette of these buttons also doesn't change with the theme or color palette picked for the site, so they stand out. The sharing buttons also don't show when editing a page in the WordPress editor, so when a user sees them on the live version of the page it can come as a surprise.

#### Screenshot / Video

![Annotation on 2019-11-22 at 12-33-52 (1)](https://user-images.githubusercontent.com/31009008/69453848-d3227c80-0d32-11ea-8dfc-d9f670ecd970.png)

**Comment by michaeldcain** [comment] 2021-06-16 20:15
Closed in #53605

**Closed by michaeldcain** 2021-06-16 20:15 UTC
Labels: Editor, [Type] Bug
