### ISSUE TITLE
Video blocks contain unexpected or invalid content

### ISSUE THREAD

**Issue by withinboredom** [Automattic/wp-calypso#30854] opened 2019-02-18 15:51 UTC
#### Steps to reproduce
1. Create a video block and choose a videopress video
2. Save the post as a draft
3. Close the tab
4. Go back to edit that draft
5. See that the block contains unexpected or invalid content

#### What I expected
A video block

#### What happened instead
![image 1](https://user-images.githubusercontent.com/1883296/52962151-d2704a80-339c-11e9-8d0e-6c889dc9cac7.png)

#### Browser / OS version
Chrome 72.0.3626.109 (Official Build) (64-bit) -- Linux and ChromeOS

#### Context / Source

cc: @Automattic/gutenpack @Automattic/lannister @notnownikki 

See p1550501568176300-slack-automattic for discussion

**Comment by notnownikki** [comment] 2019-02-18 15:55
Making notes here as I'm afk partway through tomorrow, travelling to a meetup to talk about Gutenberg.

First thing: the video block is getting transformed into an embed block here. Second: for some reason, when the post is loaded the videopress block is not expecting the internal `div` and URL, but that _is_ getting saved in the published post, if I'm reading that correctly.

**Comment by gwwar** [comment] 2019-02-18 16:57
Was this being edited at /wp-admin or /block-editor in Calypso?

cc @mmtr

**Comment by withinboredom** [comment] 2019-02-18 16:58
In calypso

**Comment by mmtr** [comment] 2019-02-18 17:51
I'm not able to reproduce this. When I edit the draft I still see the video block there. At first, I thought it might be related to a bad implementation of how we deprecate the video block when the VideoPress extension is deactivated (https://github.com/Automattic/wp-calypso/issues/30814 fixed by https://github.com/Automattic/wp-calypso/pull/30848) but seems to be unrelated to this.

@withinboredom you mentioned something in the discussion in Slack that can be relevant:

> My wife has been working on a blog post, and I spent the morning trying to help her work around these

While you are proxied, you have access to all the [beta extensions](https://github.com/Automattic/wp-calypso/blob/aa9a964e126a301afc127ce9a928d9e0c9bc181c/client/gutenberg/extensions/presets/jetpack/index.json#L15-L21).

Since the VideoPress extension is still in beta (not enabled yet on production), the core video block is generating different HTML output depending on the environment you're editing the post. I'm assuming that your wife was not proxied when she worked on the post and that would explain why do you see blocks with unexpected content.

**Comment by simison** [comment] 2019-02-18 17:53
>Since the VideoPress extension is still in beta (not enabled yet on production), the core video block is generating different HTML output depending on the environment you're editing the post. I'm assuming that your wife was not proxied when she worked on the post and that would explain why do you see blocks with unexpected content.

Would that be similar to enabling/disabling Jetpack plugin between edits, or exporting content written with Jetpack to a non-Jetpack site?

**Comment by withinboredom** [comment] 2019-02-18 17:59
> Since the VideoPress extension is still in beta (not enabled yet on production), the core video block is generating different HTML output depending on the environment you're editing the post. I'm assuming that your wife was not proxied when she worked on the post and that would explain why do you see blocks with unexpected content.

That makes so much sense! She probably had opened the post in the editor to preview the post.

**Comment by mmtr** [comment] 2019-02-18 18:59
> Would that be similar to enabling/disabling Jetpack plugin between edits, or exporting content written with Jetpack to a non-Jetpack site?

Yup! Exactly the same behavior.

**Comment by withinboredom** [comment] 2019-02-18 19:09
Thinking about it a bit more @mmtr, but why does it break when I open it? Even if she had auto-saved it while trying to preview, why would it be "broken" when I try to edit it again? (that screenshot came from my computer, while proxied)

**Comment by mmtr** [comment] 2019-02-19 11:24
@withinboredom because the new `guid` attribute of the block is removed when you edit the post without being proxied.

If you add a video block while proxied, it'll produce this markup:

```html
<!-- wp:video {"id":1234,"guid":"ABCDEFG"} -->
<figure class="wp-block-video wp-block-embed is-type-video is-provider-videopress"><div class="wp-block-embed__wrapper">
https://videopress.com/v/ABCDEFG
</div></figure>
<!-- /wp:video -->
```

When you open it on a environment not having available the beta extensions (production, not proxied) the `guid` attribute doesn't exist, so the editor will remove it:

```html
<!-- wp:video {"id":1234} -->
<figure class="wp-block-video wp-block-embed is-type-video is-provider-videopress"><div class="wp-block-embed__wrapper">
https://videopress.com/v/ABCDEFG
</div></figure>
<!-- /wp:video -->
```

So, when you open it again while proxied, your video block doesn't contain the `guid` attribute. And what does the VideoPress extension in these cases? It fallbacks to the core video block:

https://github.com/Automattic/wp-calypso/blob/3821d109b6db17a5621d33d1f56e011eb86142eb/client/gutenberg/extensions/videopress/save.js#L10-L20

Since we're missing the `src` attribute as well, the [core video block won't render anything](https://github.com/WordPress/gutenberg/blob/23e59d1f3601164788278297e5cbb33d0c1d31e5/packages/block-library/src/video/index.js#L114-L124), making the expected block content to be `<figure class="wp-block-video wp-block-embed is-type-video is-provider-videopress"></figure>`.

**Comment by mmtr** [comment] 2019-02-20 13:07
Closing this since there is not much we can do in order to handle environments where the extension is not available.

**Closed by mmtr** 2019-02-20 13:07 UTC
Labels: VideoPress, [Goal] Gutenberg, [Pri] Normal, [Type] Bug
