### ISSUE TITLE
Tumblr Post Embed Block shows narrow site name text in sidebar widget

### ISSUE THREAD

**Issue by gwensmithx** [Automattic/wp-calypso#72539] opened 2023-01-25 01:45 UTC
### Quick summary

Tumblr Post Embed block displays the Tumblr blog name in a long narrow column only in a sidebar widget theme. It affects both simple and atomic sites. It seems to display fine on the main page content. I'm able to repro this issue on multiple themes that have sidebar widget areas (non-FSE).

![Markup on 2023-01-24 at 17:30:57](https://user-images.githubusercontent.com/5779512/214460993-6b39ee2a-b238-4afb-abb6-ca24e937f79c.png)

### Steps to reproduce

1. Activate a sidebar theme like Dara
2. Set homepage to display posts under Customize --> Homepage Settings
3. Under Appearance --> Widgets add a Tumblr block
4. Embed a post
5. View the page on the front-end

### What you expected to happen

I expected the site name to display as it shows in the widget editor, on one line like this:

![Markup on 2023-01-24 at 17:41:16](https://user-images.githubusercontent.com/5779512/214461412-effb4857-274c-4bdf-8a79-476b5ca90414.png)

### What actually happened

The site name displayed in one narrow column as per my first screenshot.

### Context

First reported here: #5888900-zd

### Theme-specific issue?

No. I've tried it on other themes like Capoverso that has a sidebar widget area with the same issue occurring.

### Browser, operating system and other notes

Chrome 109.0.5414.87 / MacBook Pro Mac OS Version 12.5

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by cuemarie** [comment] 2023-03-17 21:28
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Could not replicate
- Tested on AT: Could not replicate
- Tested on Self-hosted: Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested on AT: Apostrophe 2, Dara
- Tested on S: Capoverso, Dara
- Tested on SH: Skatepark (FSE with columns on template)

**AT Example**
![Markup on 2023-03-17 at 14:22:36](https://user-images.githubusercontent.com/27249804/226056416-77c1a054-6e2d-45f4-80ca-82ae77997cf2.png)

**Simple Example**
![Markup on 2023-03-17 at 14:22:36](https://user-images.githubusercontent.com/27249804/226056425-8ba7d038-b41a-4f12-98bd-e4301a6e7875.png)

Also ran a quick test with the tumblr account in the example above, and the title did not wrap the way it did in the original report (Simple site, Dara theme):

![Markup on 2023-03-17 at 14:26:18](https://user-images.githubusercontent.com/27249804/226056602-1c333ed6-a421-4aef-a182-411d867f7543.png)


📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)

📌 Message to Author
- @gwensmithx I was not able to replicate this.  We may need to look into other troubleshooting steps if the problem is still happening on the user's site
- If you're able to replicate this on a test site with additional steps, feel free to reopen and share those, thank you!

**Closed as completed by cuemarie** 2023-03-17 21:28 UTC
Labels: Bug, [Pri] Low
