### ISSUE TITLE
Account settings: Prevent unset "Primary site" state

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#30300] opened 2019-01-22 12:28 UTC
I am not entirely sure what causes this, but we should probably prevent this weird state where there is no `Primary site` set.

<img width="704" alt="screenshot 2019-01-22 at 17 51 43" src="https://user-images.githubusercontent.com/18581859/51535467-906fe980-1e6e-11e9-90c6-5f70b450d239.png">

It causes the dropdown to appear in a malformed way.

<img width="712" alt="screenshot 2019-01-22 at 17 51 56" src="https://user-images.githubusercontent.com/18581859/51535465-906fe980-1e6e-11e9-8581-9be0700eec3f.png">

It also causes the default Calypso dashboard state to look malformed with no site to render.

<img width="1917" alt="screenshot 2019-01-22 at 17 56 14" src="https://user-images.githubusercontent.com/18581859/51535644-11c77c00-1e6f-11e9-9ec2-b4d8be1e854f.png">

**Comment by formosattic** [comment] 2019-03-14 06:12
+1 1853037-zen

**Comment by apeatling** [comment] 2019-05-03 20:52
@arunsathiya Can you provide steps to reproduce this please?

**Comment by arunsathiya** [comment] 2019-05-04 13:36
@apeatling Unfortunately I have not found the exact cause/steps to reproduce so far. I have noticed this happen once on my account and once with an user's - as reported by @formosattic above. Not much details on that ticket to reproduce though.

I will look around a bit more and add details as I find.

**Comment by htdat** [comment] 2019-12-26 03:37
@arunsathiya - it sounds like this is a duplicate of this issue https://github.com/Automattic/wp-calypso/issues/24539 ?

**Comment by cathymcbride** [comment] 2020-09-08 20:07
Closing as duplicate of #24539

**Closed by cathymcbride** 2020-09-08 20:07 UTC
Labels: [Type] Bug
