### ISSUE TITLE
Settings: Site Address button label has a line break

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#8112] opened 2016-09-16 23:10 UTC
Happens in viewports that are about `<1065px`. This causes the Site Address field to look really large:

![screenshot 2016-09-16 16 09 57](https://cloud.githubusercontent.com/assets/4924246/18603623/193b787e-7c28-11e6-8879-58de1046cfa8.png)

**Comment by lancewillett** [comment] 2016-10-18 22:30
Closing as a duplicate of #3050.

**Closed by lancewillett** 2016-10-18 22:30 UTC
Labels: Site Settings, [Type] Bug
