### ISSUE TITLE
[Bug]: "Please moderate" Emails are blank.

### ISSUE THREAD

**Issue by zachspears** [Automattic/wp-calypso#62939] opened 2022-04-21 04:52 UTC
### Quick summary

Reports of some emails sent to users are completely blank. Specifically, "Please Moderate" emails that are sent when a visitor posts a comment. 

### Steps to reproduce

1. Make a post on a Premium Site.
2. Make sure your settings are set to receive an email for new comments on the site, and require comment approval
3. Using another account or email address, comment on that post. 
4. Check your email for "Please moderate" email. 

### What you expected to happen

Email should contain content such as a link to the comment moderation. 

### What actually happened

The email is blank. 

### Context

Three customer reports. 

### Browser

Google Chrome/Chromium

### Simple/Atomic

Simple

### Other notes

Contacts: 
35229147-hc
21515857-hc
https://wordpress.com/forums/topic/notifications-of-comments-on-pages

Initially noted in Slack thread: p1650455644022449-slack-CB0B2G43X

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

None that I have found.

**Comment by benchilcote** [comment] 2022-04-21 12:23
Another case: 33290575-hc
I tested and was able to reproduce.  Here's a screenshot of an email I received in my testing: https://d.pr/i/g2NO1a

![image1](https://user-images.githubusercontent.com/15944096/164882576-7d99b831-5e58-4f52-899a-823146be3e46.png)

**Comment by kelasante** [comment] 2022-04-24 02:10
It looks like this specific bug has been fixed.

However, users still have feedback about changes to the email template.

**Comment by formosattic** [comment] 2022-04-24 08:38
Note to @Automattic/dotcom-triage-pa-group: if it applies, this may need to be transferred to Jetpack, see https://github.com/Automattic/jetpack/issues/24036.

@kelasante: could you share what their feedback is, and leave the ticket or chat link. There also a few reported issues at https://github.com/Automattic/jetpack/issues/24036 that you can +1 at. Thanks!

**Comment by yansern** [comment] 2022-04-25 07:15
Fixed with D79214-code.

**Closed as completed by yansern** 2022-04-25 07:15 UTC
Labels: Bug, Needs triage
