### ISSUE TITLE
Audio block doesn't work in subscriber emails

### ISSUE THREAD

**Issue by desnum** [Automattic/wp-calypso#46895] opened 2020-10-29 02:09 UTC
#### Steps to reproduce

1. Starting at URL: https://drscottlear.com/
2. Create a post
3. Add an Audio Block with an audio file
4. Publish post
5. Check subscriber email

#### What I expected
A link to the audio file in the email. Like this first post that had an audio file, but in a Classic Block:
<img width="956" alt="first-post-audio-works" src="https://user-images.githubusercontent.com/43796228/97516576-c5756e00-1969-11eb-953e-4c20b267e1ce.png">

#### What happened instead
The audio file doesn't appear -- neither does a link  -- when the audio was added to the post via an Audio Block:
<img width="956" alt="second-audio-doesnt-work" src="https://user-images.githubusercontent.com/43796228/97516609-d920d480-1969-11eb-8d23-90903e0bb5ad.png">

#### Browser / OS version
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

#### Screenshot / Video
See above

#### Context / Source

User-reported in chat hc25237149

**Comment by alshakero** [comment] 2020-12-03 12:22
Tested on a simple site and couldn't reproduce with and without a caption. I'll test on an atomic site. The site mentioned above is indeed atomic.

**Comment by alshakero** [comment] 2020-12-03 12:39
I couldn't reproduce on Atomic sites too. Dug deeper and found that this was fixed in D51950-code by @sixhours on the same day this issue was opened!

Closing as done.

Feel free to let the user know that this was fixed.

**Closed by alshakero** 2020-12-03 12:39 UTC
Labels: Audio Block, [Pri] Normal, [Type] Bug
