### ISSUE TITLE
Checklist and summary box don't match and box is missing info

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/wp-calypso#30244] opened 2019-01-18 18:17 UTC
@Automattic/onboarding-dev

#### Steps to reproduce
1. Regarding 9642601-HC
2. SSP user and view Stats page (may need to refresh the page the first time in)
3. Checklist box shows a percentage complete but no text or links
4. Checklist page indicates that everything is complete

#### What I expected
I expected to see the instructions for the next step in the box. And I expected the checklist to show incomplete steps.

#### What happened instead
The box on the stat page didn't provide any information beyond the percentage complete.
The checklist says that everything is completed.

#### Browser / OS version
Google Chrome is up to date Version 71.0.3578.98 (Official Build) (64-bit)
macOS High Sierra Version 10.13.6
(Didn't ask the user what they were on. And another HE verified that they get the same outcome, didn't ask about their Browser or OS either.)

#### Screenshot / Video
https://monosnap.com/file/VVTL7TigGstSSD9riv57zIrPXavKVt

#### Context / Source
#user-report

**Comment by torres126** [comment] 2019-01-18 18:32
Duplicate of #28700?

**Comment by tanjoymor** [comment] 2019-01-19 01:34
My apologies, yes it would seem so. This was my first time reporting a new issue, I'll pay more attention to looking for duplicates in future.

**Comment by arunsathiya** [comment] 2019-01-19 10:07
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/28700

**Closed by arunsathiya** 2019-01-19 10:07 UTC
Labels: Checklist
