### ISSUE TITLE
Site address changing during the importing process

### ISSUE THREAD

**Issue by ouikhuan** [Automattic/wp-calypso#65830] opened 2022-07-21 08:14 UTC
### Objective

During the importing, the screen changed slightly. Originally, it said “Restoring to domain.wordpress.com” and then it changed to “Restoring to domain.wpcomstaging.com.” This might confuse users.

### Approach

Review this in the codebase and fix it.

**Comment by vishnugopal** [comment] 2022-07-26 06:32
1. Start with a new simple site
2. Migrate from anywhere
3. xxx.wordpress.com -> xxx.wpcomstaging.com 

How do we communicate to customer early in the process that their WordPress.com site address will change?

**Comment by retnonindya** [comment] 2024-08-28 02:39
I'm triaging this issue, and it seems like the issue is no longer relevant now that we have updated our site migration flow. 

As for website address change, we have updated the Support doc to communicate it with users here:
https://wordpress.com/support/activate-your-business-plan/#activate-your-plan-features 

📌 ACTIONS

Closed as could not replicate (please reopen if the issue reoccurs)

**Closed as completed by retnonindya** 2024-08-28 02:39 UTC
Labels: Bug, [Pri] Low, [Feature] Site Migration
