### ISSUE TITLE
Blaze Campaign Start/End Date Unclear or Wrong

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#94060] opened 2024-08-30 10:42 UTC
### Quick summary

It's unclear when a campaign starts or ends

### Steps to reproduce

1. Buy a 2-day campaign
2. Go to the campaign details, https://wordpress.com/advertising/campaigns/111046/125098293 for example
3. You'll see 3 days mentioned there isntead of 2 (bug)
4. However, since the moment I start the campaign, it is not clear that the campaign starts tomorrow, this should be indicated somewhere (feature request)

### What you expected to happen

- Have it abundantly clear when the campaign starts and ends
- The period should be 2 days rather than 3 if I bought a 2-day campaign

### What actually happened

<img width="633" alt="Screenshot 2024-08-30 at 13 39 03" src="https://github.com/user-attachments/assets/c5125a74-0173-475f-96b8-1d7bead3ddde">
- August 27-29 - that's 3 days, not 2.
- Not really clear if the campaign will run for 2 or 3 days given the inconsistency, and the exact start time is not displayed anywhere

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jartes** [comment] 2024-09-03 15:25
📌 REPRODUCTION RESULTS
- Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- This information about the campaign duration is also inaccurate when creating a campaign: 

![Markup on 2024-09-03 at 17:20:28](https://github.com/user-attachments/assets/c43f114e-7490-4899-9836-6114e5e6fb32)

📌 ACTIONS
- Triaged

**Comment by jartes** [comment] 2024-09-04 14:19
Is it possible to see the date and time when a campaign started (scheduled) by hovering over the `Scheduled` status label on the campaigns page https://wordpress.com/advertising/campaigns/example.com? 

And, it could be that the displayed hour is in UTC as my local time is 04:12 pm and the scheduled time for this ad, is 3:23 pm

![Markup on 2024-09-04 at 16:12:54](https://github.com/user-attachments/assets/49347914-ea1f-4d97-ac36-1ab27b28c38f)

**Comment by candy02058912** [comment] 2024-09-18 07:51
> - August 27-29 - that's 3 days, not 2. - Not really clear if the campaign will run for 2 or 3 days given the inconsistency, and the exact start time is not displayed anywhere

Yes I feel the same confusion. After looking into the API response we do have data we can utilize, seeing the time helps clarify the situation :

`start_date`: 2022-12-21T07:55:15.000Z
`end_date`: 2022-12-23T07:55:15.000Z

Which will result in the UI showing
![duration](https://github.com/user-attachments/assets/bed0e2d8-2f7f-4ac1-bc8b-bc846e3f88c0)
And leading to the confusion whether this is 2 days or 3 days.

With the complete start and end time info, it clarifies the confusion.

@sbarbosa could you help take a look at this issue as I noticed I have to regain access to the tumblr DSP repo in order to add the time information to the UI.

cc: @inaikem Groundskeeping notes: I felt passing this issue to people who have repo access would be more efficient.

**Comment by sbarbosa** [comment] 2024-09-18 12:59
Thanks for the ping and all the information! 
I will create a ticket in the DSP repo to improve this.

**Comment by candy02058912** [comment] 2024-09-19 06:15
Link to related Slack thread: p1726648880033179-slack-C0351BKR0M6

Thanks for following up @sbarbosa! Since I'll be off Groundskeeping next week, I'll assign the ticket to you (I couldn't find your team's group; feel free to change it to your team) so that other Groundskeeper will know where to reach out. 🙏

**Comment by donnapep** [comment] 2024-10-08 16:11
Howdy @sbarbosa. 👋🏻  Just checking in to see if there's any new progress to report for this one?

**Comment by sbarbosa** [comment] 2024-10-08 16:21
No progress for this one yet. The team is working on making changes to the campaign details page, but after checking the new designs, we see that they still don't fully cover this ticket. 

I will move the other ticket I created to the project and ping our designer to see if we can include an improvement on that work.

**Comment by sbarbosa** [comment] 2024-10-17 14:41
Hi @supernovia! The ticket I created mentioned the time, so we will need to see if we can add it, or it may not be necessary.

The change we are going to make in the campaign details page is to add a Graph with what the campaign delivered each day:
![Image](https://github.com/user-attachments/assets/2f9f8cc2-20e6-475a-946e-dafa1580158f)

Maybe that will be enough for the user to know that it started one day and continued to be delivered until the final day. Based on the number of impressions delivered each day, the user should notice that the start/end days didn't deliver as much as the rest (didn't run for the entire day). 

But it's true that now we place less emphasis on the campaign start/end date and will need to consider campaigns that have yet to deliver. The task is still pending, and in the ticket I created, I mentioned syncing with our designer and trying to improve this problem.

I will add a note to the ticket so we can be sure to tackle this problem 👍, to be sure to have a Sync with Bart before making the changes.

Let me tag @bartoszbak here just to let him know of this issue.

**Comment by therocket-gr** [comment] 2024-12-03 10:03
I think we can close this ticket. 
we have this pr 2874-gh-tumblr/a8c-dsp
that will show this in the widget

![Image](https://github.com/user-attachments/assets/74622c3f-7bfe-4977-baf5-ffed47137856)

in calypso after our recent changes we don't have the duration in full (and we don't have x days etc) so I thin we have handled the issue

**Comment by sirreal** [comment] 2024-12-27 09:35
Closing this based on https://github.com/Automattic/wp-calypso/issues/94060#issuecomment-2514091492.

**Closed as completed by sirreal** 2024-12-27 09:35 UTC
Labels: Bug, [Pri] High, Triaged, [Feature] Blaze on WordPress.com, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] User Interaction & Engagement, Groundskeeping
