### ISSUE TITLE
Cannot Connect New Service for Atomic Sites w/ Calypsoify

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/wp-calypso#30147] opened 2019-01-14 03:34 UTC
Originally reported on 3325-gh-jpop-issues and related to pafL3P-7k-p2

**Summary**
A 403 error is displayed when trying to add a new Publicize connection through the Gutenberg interface.

Accessing the same settings page via WP-Admin > Settings > Sharing results in the page loading successfully.

**Potential Cause:**
The new post link in calypso goes to: wp-admin/post-new.php?calypsoify=1

The sharing link goes to: /wp-admin/options-general.php?page=sharing&publicize_popup=true

The sharing link is disabled when calypsoify is enabled:

https://github.com/Automattic/jetpack/blob/master/modules/calypsoify/class.jetpack-calypsoify.php#L186

In Calypso for an Atomic Site:

Blog Posts [Add] => Publish => Connect new Service

<img width="278" alt="50798145-86f25900-1294-11e9-809b-ebf3a753a22d" src="https://user-images.githubusercontent.com/3812076/51095483-b00c6f80-17e7-11e9-8cb7-332d1eb06051.png">

Related:
Automattic/wp-calypso#28332
Automattic/wp-calypso#28528

cc: @gwwar

**Comment by gwwar** [comment] 2019-01-24 23:22
Not sure what the preferred flow is here, maybe open in new tab?

cc @Automattic/gutenpack

**Comment by mmtr** [comment] 2019-02-26 14:41
Can folks still reproduce this? Seems to be solved by https://github.com/Automattic/wp-calypso/pull/29228

Sharing settings always open in a new tab in all environments:
- Simple sites: Gutenlypso, Gutenframe, WP Admin, Calypsoified WP Admin
- Jetpack & Atomic sites: WP Admin, Calypsoified WP Admin

**Comment by kwight** [comment] 2019-02-26 20:50
I get the same results as @mmtr : link is to an external tab, and once the connection is created and the connections tab closed, the Publicize sidebar section updates to show the new connection.

**Comment by mmtr** [comment] 2019-02-27 09:35
Thanks for confirming @kwight! I'll close the issue then :) We can always reopen it if we're missing anything.

**Closed by mmtr** 2019-02-27 09:35 UTC
Labels: Calypsoify, Sharing, [Goal] Gutenberg, [Type] Bug, user-waiting
