### ISSUE TITLE
Editor: get stuck in <a> after linking via paste URL in FireFox

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#5186] opened 2016-05-03 16:34 UTC
https://cloudup.com/iQmsNkh_tDA

#### Steps to reproduce
1. Starting at URL: wordpress.com/post/:site on firefox (specific to moz)
2. Copy a url to your clipboard, then link a word using the paste URL shortcut (select word to set as anchor and paste)
3. Notice that as you type after the linked word, you are "stuck" in the `a` tag (cursor is set before `</a>` making it impossible to escape the link in visual editor)
![](https://cloudup.com/iH5w_TF8afn+)
4. Only way to continue writing is to switch to HTML editor or to preempt this and only use paste-to-link on words that are already followed by unlinked text.

**Comment by lancewillett** [comment] 2016-05-04 20:54
I'm able to repeat this with the steps described above, using Firefox stable on OS X 10.11.4.

A few notes:

1. This seems to only occur on the **first** link in the editor — in testing in Firefox the second, third, fourth time I highlight a word and paste the link — and move to keep typing, it works as expected.
2. Addition to `4. Only way to continue writing is to switch to HTML editor`  — you can also hit Enter or Return to go to next line, then back up.
3. We also have a `Command-k` shortcut to add a link, but it's currently broken, see #4336.

**Comment by lancewillett** [comment] 2016-05-04 20:56
Hmm, after more testing it seems inconsistent.

![keyboard-firefox-links](https://cloud.githubusercontent.com/assets/66797/15028910/0a2fb4ea-1200-11e6-9bea-397e00815ff7.gif)

**Comment by lancewillett** [comment] 2016-05-04 20:58
Confirmed Safari and Chrome latest versions on Mac OS X don't have this behavior — specific to Firefox.

**Comment by lancewillett** [comment] 2016-05-04 21:13
I think it could be a difference of — works fine when you use punctuation (`This is a link.` and only highlight the words before the period.) If you do that the bad behavior doesn't happen.

**Comment by designsimply** [comment] 2016-08-10 00:16
Closing because I was unable to reproduce the problem using the testing steps with Firefox 48.0 on Mac OS X 10.11.5. ([59s](https://cloudup.com/cZFgJ02Wm0A))

**Closed by designsimply** 2016-08-10 00:16 UTC
Labels: Editor, [Type] Bug
