### ISSUE TITLE
Signup flow loads blank screen

### ISSUE THREAD

**Issue by wongasy** [Automattic/wp-calypso#67832] opened 2022-09-14 20:23 UTC
### Quick summary

There's an intermittent issue where the signup flow (e.g. `/start/domains`, `/start/onboarding-with-email`) loads up a blank screen. There's are no web console errors, so it's difficult to determine what the underlying issue might be. The only warning messages I saw is css-related, which doesn't appear to be the root cause of the issue. Note that the rest WordPress.com loads up fine, it's just the signup flows that are blanking out. It's also worth noting that when I load the navigate to `/start/domains` in Incognito mode, the page loads up fine.

I have encountered this blank page error multiple times. Previously, the issues fixed itself without any action being taken, which led me to think the issue might be cookie related (once a certain cookie expired, the issues cleared itself). However, the latest occurrence I've encountered persisted, I've been seeing a blank screen all week.

### Steps to reproduce

Unfortunately, there doesn't seem to be any way to consistent reproduce the issue. I was testing out the signup flow a lot, and that was how ended up in the "blank screen" state. I would suggest the following steps for reproducing the issue:

1. Visit https://wordpress.com/start
2. Go through the signup flow
3. Navigate forward / backward within the signup flow
4. Abandon / skip the setup steps after checkout (I find that issues are more likely to come up when we don't go through the "regular" steps
5. Go back to the signup flow https://wordpress.com/start

### What you expected to happen

Begin the signup process.

### What actually happened

A blank screen showed up.

<img width="1518" alt="Screen Shot 2022-09-14 at 4 06 33 PM" src="https://user-images.githubusercontent.com/104910361/190251802-8c7fa965-7c7f-4b60-95bc-be3a27c237f2.png">

Here's a video recording of what I saw:
https://user-images.githubusercontent.com/104910361/190252792-dec1ae24-50c5-4335-9a88-4443037a4477.mov

The WordPress logo would "flash" then I landed on a blank screen.

### Context

When this was first reported: p1662424145365549/1662418845.147659-slack-C029GN3KD

### Browser, operating system and other notes

Chrome 104.0.5112.101, macOS Monterey 12.5.1

### Reproducibility

Intermittent

**Comment by zachspears** [comment] 2022-09-20 02:04
I was unable to reproduce the blank page issue, however, I did get stuck on the "loading" screen. Adding Normal priority due to the inability to sign up when impacting a user.

**Comment by michaeldcain** [comment] 2024-07-30 18:36
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/64756. Feel free to re-open this if it's different.

**Closed as completed by michaeldcain** 2024-07-30 18:36 UTC
Labels: Bug, [Pri] Normal, Triaged
