### ISSUE TITLE
Gutenberg: Enhancement - Scheduled posts don't appear in datepicker

### ISSUE THREAD

**Issue by ashercantrell** [Automattic/wp-calypso#28567] opened 2018-11-14 23:10 UTC
In Calypso, the datepicker calendar shows faint gray circles around dates that have a post already scheduled, and mousing over that shows the number of posts scheduled for that day and their names.

You can see a screenshot of that behavior here: http://cld.wthms.co/A26y6A

Calypsofied Gutenberg currently doesn't do this, and only shows the calendar itself. I think it would be good to have this info showed there as well.

This was requested by a user in #1567530-zen

**Comment by kwight** [comment] 2018-11-15 18:34
Marking enhancements of this sort as low priority for now.

**Comment by KokkieH** [comment] 2018-11-20 08:46
Noting we've had another request for this in the [forums](https://en.forums.wordpress.com/topic/new-editor-unable-to-see-other-scheduled-posts/).

**Comment by supernovia** [comment] 2018-11-20 23:59
Another complaint here. This one hits our diehard bloggers.
https://twitter.com/sarahhardy681/status/1065012897099722761

**Comment by ahmadbaig1** [comment] 2018-11-25 07:55
Another enquiry for it through tickets-
[Zen_1593708](https://woothemes.zendesk.com/agent/tickets/1593708)

I have informed them that the issue is in our list of enhancements and will be added in the future.

**Comment by sixhours** [comment] 2018-11-30 17:37
Another request from a user in 1567530-zen

They'd like a follow-up when this is implemented, please and thanks!

**Comment by ahmadbaig1** [comment] 2018-12-10 06:52
The user- 1633273-zen would also like an update when this is added.

**Comment by kwight** [comment] 2018-12-19 20:13
Bumping priority due to vocal feedback.

**Comment by KokkieH** [comment] 2018-12-26 07:48
Another request [here](https://en.forums.wordpress.com/topic/block-editor-3/)

**Comment by donalirl** [comment] 2019-01-29 00:44
Another request in #1756730-zen

**Comment by hannahswain** [comment] 2019-01-29 14:08
Another request in 1748062-zen

**Comment by lakellie** [comment] 2019-02-05 21:49
Another request in #3054688-hc

**Comment by supernovia** [comment] 2019-02-06 22:42
Another via Twitter: 
/PhotosEmily/status/1093226553566220295

**Comment by mikeicode** [comment] 2019-02-07 17:03
Another request #8663118-HC

Testing this I see that aside from the scheduled posts not showing on the calendar the current day (today), is not shown on the calendar like it was previously.

This: https://cld.wthms.co/bmfIeN
Compared to this: https://cld.wthms.co/MqXVmU

**Comment by ezraalamsyah** [comment] 2019-02-07 17:16
Another request in 1784263-ZD

**Comment by torres126** [comment] 2019-02-10 12:25
Request here: https://en.forums.wordpress.com/topic/blog-post-calender/

**Comment by AtrumGeost** [comment] 2019-02-15 14:31
Another request here 1800713-zen

**Comment by BigDaddyLinux** [comment] 2019-05-05 12:51
Would love to see this enhancement in Gutenberg

**Comment by torres126** [comment] 2019-05-06 06:20
Request here: https://en.forums.wordpress.com/topic/post-scheduling-7/

**Comment by jesscga** [comment] 2019-05-27 18:55
Another request on 4613987-hc - user asked to switch to classic editor for unrelated reasons which should resolve the calendar issue.

**Comment by spencerberry** [comment] 2019-06-08 14:36
Requested in 13133129-hc as they accepted the block editor but rely on this feature to have a well-distributed schedule of content.

**Comment by tijosh** [comment] 2019-06-13 18:59
Another request for this in #13111861-hc  

Followup: #2105059-zen

**Comment by supernovia** [comment] 2019-08-30 20:32
Noting there's an issue on core about this too with some design discussion:
https://github.com/WordPress/gutenberg/issues/13713

**Comment by samiff** [comment] 2020-05-21 20:48
1525757-hc

**Comment by Kheas** [comment] 2020-05-21 20:52
Blogger here at Latetothegame.blog.  This function is essential to scheduling blogs.  Please find a way to implement it prior to launch.

**Comment by Kheas** [comment] 2020-05-21 20:59
If it can not be implemented can we at least still have access to the classic editor until it is?

**Comment by deancroyal** [comment] 2020-08-26 19:24
Another in [forums](https://wordpress.com/forums/topic/showing-scheduled-posts/).

**Comment by khristiansnyder** [comment] 2020-08-31 21:10
Requested in 12114494-hc

> In the new editor (which is garbage) the calandar does not bring up the other post you have up or upcoming. This was a pretty fundamental feature. How can I get it back?

**Comment by davemart-in** [comment] 2020-09-01 15:57
Heh. Here's one more duplicate issue: https://github.com/WordPress/gutenberg/issues/13713 :-P

**Comment by Fangthewonderdog** [comment] 2020-09-02 19:29
I need this feature too.  It is needed for efficient and correct scheduling. What priority has been given to the fix please?

**Comment by macmanx2** [comment] 2020-09-02 19:39
Also requested at https://wordpress.com/forums/topic/publishing-future-date/

**Comment by fernmed** [comment] 2020-09-03 19:50
Another request 457171-hc

**Comment by samiff** [comment] 2020-09-05 20:34
Requested in 3289831-zd-woothemes

**Comment by abdul5ashraf** [comment] 2020-09-08 09:09
Another request 3297295-hc

**Comment by mriyazuddin** [comment] 2020-09-09 02:52
Another one #3299468-zd

**Comment by fsalazarleon** [comment] 2020-09-11 04:22
Another one #3275085-hc

**Comment by aleone89** [comment] 2020-09-17 18:07
More request here: hc-14523525 and zen-3326301

**Comment by carladoria** [comment] 2020-09-20 20:31
another request in 3333184-zen

**Comment by kriskarkoski** [comment] 2020-09-21 19:18
Requested in 3330991-zd as well

**Comment by aisajib** [comment] 2020-09-22 16:55
Another chat requesting this: #24324028-hc

**Comment by donalirl** [comment] 2020-09-25 00:49
Another request in #16099825-hc

**Comment by rossanafmenezes** [comment] 2020-10-10 14:00
Another request here 3389519-zen

**Comment by tbradsha** [comment] 2020-10-14 16:06
2741645-hc

**Comment by supernovia** [comment] 2020-10-30 16:52
Another request here:
https://wordpress.com/forums/topic/calendar-markers/ 

Glad to see this is in the works. :)

**Comment by fsalazarleon** [comment] 2020-11-05 23:46
Another request here 3466246-zen

**Comment by SBATHOMPSON** [comment] 2020-11-14 00:01
I had a user request this feature today. 
https://woothemes.zendesk.com/agent/tickets/3471369

**Comment by mikeicode** [comment] 2020-11-28 13:19
Requested 3511304-zd-woothemes

**Comment by aleone89** [comment] 2021-01-06 11:48
Another request via twitter: 

/downthebookhole/status/1346629013930913792

**Comment by rachelwinspear** [comment] 2021-02-22 08:30
Another request: #3755376-zen

**Comment by sixhours** [comment] 2021-03-17 15:06
Another request for this in en.blog comments: https://wordpress.com/blog/2021/03/15/block-editor-updates-2/#comment-418971

**Comment by retrofox** [comment] 2021-04-08 20:34
Today we've merged the first approach to address this issue. https://github.com/WordPress/gutenberg/pull/29716
Let me close the issue.

**Closed by retrofox** 2021-04-08 20:34 UTC
Labels: [Goal] Gutenberg, [Pri] Normal, [Size] M, [Type] Feature Request
