### ISSUE TITLE
Form Block: Field color not changing

### ISSUE THREAD

**Issue by ezebecke** [Automattic/wp-calypso#72965] opened 2023-02-03 17:34 UTC
### Quick summary

On Form blocks changing the Field color changes the color on the editor page but not on the live one.

How it looks on editor:

![qdsskb.png](https://user-images.githubusercontent.com/24919469/216669490-d9cf4096-4d52-4ad6-9b04-d0d4b4715875.png)

How it looks on live page:

![7ssHb7.png](https://user-images.githubusercontent.com/24919469/216669622-74f38ba0-29d8-48f9-8b77-cf02a7c418b3.png)

### Steps to reproduce

1- Start a Form block.
2- Try updating the color on a field.
3- Check live page.

### What you expected to happen

The field display the color on the editor and live views displays

### What actually happened

Color not getting applied on live view.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

I was able to replicate this on different themes. 

Reported on 5923349-zd

**Comment by dpasque** [comment] 2023-02-21 20:04
I believe this has since been fixed by this PR: https://github.com/Automattic/jetpack/pull/28212

I tried replicating on WPCOM, but wasn't able to reproduce it right now. 

@ezebecke -- are you still seeing this happen in your testing conditions? If not, we should be able to close this as fixed!

**Comment by vajrasar** [comment] 2023-02-24 18:38
Closing this. @ezebecke please feel free to reopen if you can replicate the issue.

**Closed as completed by vajrasar** 2023-02-24 18:38 UTC
Labels: Bug, [Pri] High, [Platform] Simple, [Platform] Atomic
