### ISSUE TITLE
Congratulate new subscriptions

### ISSUE THREAD

**Issue by jidanni** [Automattic/wp-calypso#86685] opened 2024-01-21 05:40 UTC
### Quick summary

Hard to realize subscribing actually worked, even though it did.

### Steps to reproduce

1. User gets confirmation mail as in #86573 .
2. User successfully clicks the link and is brought to https://wordpress.com/subscriptions/comments/en
3. User sees his/her new subscription at the top of the list.

### What ought to also happen

There should also be some congratulation message that "you have confirmed your subscription." 

Not all users "naturally realize the first item has been added nicely like they hoped". Therefore they should still be congratulated.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Logs or notes

Note I am not a Wordpress user at all. I just subscribe to something occasionally.

**Comment by jidanni** [comment] 2024-02-05 04:21
And today I had a similar thing happen.
I got this mail,
[k.eml.gz](https://github.com/Automattic/wp-calypso/files/14160429/k.eml.gz)
and instead of seeing any "You have successfully subscribed", my browser just sends me to the page where I subscribed from. 


Happily moments later I got an email,

> Cool, you are now subscribed to weeklyosm.eu and will receive an
> email notification when a new post is published.

**Comment by inaikem** [comment] 2024-10-22 15:10
@Automattic/apex 👋 Is this issue something you can look at as related to #86573?

**Comment by inaikem** [comment] 2024-10-22 15:20
@jidanni, thanks for submitting this report. 

I'd like to clarify if the success messaging you suggest is related to "_site_" or "_comment_" subscriptions. Perhaps both?

It would also be very helpful if you could let us know:

- If the issue is still present
- Your device's operating system (macOS Sonoma / Windows 11) and browser (Chrome, Safari, etc.).

**Comment by Robertght** [comment] 2024-10-24 17:47
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate 

FINDINGS

This is what I got as a new subscription:

![Image](https://github.com/user-attachments/assets/814b379f-201b-4615-a7c1-39ec535dac70)


📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @jidanni I'm closing this for now, but feel free to re-open and include more details so we could look further into it.

**Closed as completed by Robertght** 2024-10-24 17:47 UTC
Labels: Enhancement, [Pri] Low, Triaged, [Closed] Not Reproducible, Fit and Finish
