### ISSUE TITLE
Layout Modal: a blog layout is missing

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#69878] opened 2022-11-09 06:25 UTC
### Quick summary

Currently, there is only one blog layout available in the modal at the moment. However, in Dotcom Patterns, there is [one more layout](https://dotcompatterns.wordpress.com/2022/10/19/grid-of-posts-4x2/) that is tagged with `layout` and published under the `blog` category. I thought when a layout was published in Dotcom Patterns, it became available in the modal just like patterns. What am I missing?

![Screenshot 2022-11-08 at 22 55 12](https://user-images.githubusercontent.com/908665/200752291-39900a18-e1c6-45a2-81ba-73cfe7199d32.jpg)

Also, how can we change the categories shown on the left side? I'm not sure if we need to keep `Home` anymore.

I was told that the original engineers who worked on this feature have moved on to other teams. What team can own this?

### Steps to reproduce

1. Add a new page
2. Click the `blog` category on the left.
3. See one layout is available.

### What you expected to happen

All the layouts published in Dotcom Patterns appear in this modal.

### What actually happened

I don't see all of them. I am most likely missing something.

### Reproducibility

Consistent

**Comment by cuemarie** [comment] 2023-04-28 00:11
Duplicate of https://github.com/Automattic/wp-calypso/issues/68716

**Closed as completed by cuemarie** 2023-04-28 00:11 UTC
Labels: Bug, [Pri] Low, Patterns, Triaged
