### ISSUE TITLE
Jetpack Connect: Pre-selected plan is lost when Jetpack is not installed

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#16084] opened 2017-07-11 11:03 UTC
#### Steps to reproduce
1. Pick a non-connected .org site that does not have Jetpack installed.
2. Go through the `/jetpack/connect/:flow` flow, for example you can use the `personal` flow.
3. Input your site URL in the JPC form.
4. You will be presented with the installation instructions.
5. Install and activate Jetpack.
6. Click the "Connect" button in wp-admin to initiate connection.
7. Follow along with the connection and authorization process.
8. After auth success, you are thrown to the plans page, without a pre-selected plan.

#### What I expected
To have the Jetpack Personal plan pre-selected, and therefore continue to the checkout process.

#### What happened instead
I was presented with the plans selection page

#### Context / Source
Found while testing the new calypso login form #manual-testing

**Comment by tyxla** [comment] 2017-07-11 11:05
Related: #16085

**Comment by johnHackworth** [comment] 2017-07-18 07:50
We can't reproduce this bug anymore, so I'm closing this

**Closed by johnHackworth** 2017-07-18 07:50 UTC
Labels: .org Plans, Jetpack, [Type] Bug
