### ISSUE TITLE
Nav Unification: Manage Plugins shown in menu first

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/wp-calypso#49235] opened 2021-01-23 15:41 UTC
### Steps to reproduce the behavior

1. Logged into my test sites.
2. Saw `Manage Plugins` at the top of the menu

![Screenshot](https://d.pr/i/oG38WI+)

![Screenshot](https://d.pr/i/02iCIA+)

#### What I expected to happen

I expected to see 'Manage Plugins' under the option 'Appearance' in the left-hand menu

#### What actually happened

The menu option 'Manage Plugins'  is showing at the top of the menu. I tested further and clicked around a bit, and it remains up at the top of the left-hand menu bar.

**Comment by getdave** [comment] 2021-02-03 14:08
@rachelwinspear Thanks for reporting. I cannot reproduce this.

Please could you re-test. If it still occurs then please feel free to remove the `Not Reproducible` label.

Also please can you advise on whether this is Simple or Atomic (assume Atomic).

Also would you mind inviting me to your test site and DM'ing me on Slack so I can see this happening?

Much appreciated.

**Comment by obenland** [comment] 2021-02-05 00:24
This should be fixed with Jetpack 9.4 being out now. It's caused by Calypsoify being active together with nav-unification.

@rachelwinspear Please feel free to reopen if this still happens with latest Jetpack.

**Closed as completed by obenland** 2021-02-05 00:24 UTC
Labels: Bug, [Feature] Calypso & wp-admin Navigation, [Closed] Not Reproducible
