### ISSUE TITLE
Additional comment box appears under the "Leave a Comment" box on posts

### ISSUE THREAD

**Issue by synora** [Automattic/wp-calypso#73443] opened 2023-02-16 17:42 UTC
### Quick summary

A user report(5964950-zen) came about a comment box being hidden by their footer. This box appears out of place since the correct post comment box appears as it should above it. The user reports this box appearing yesterday which coincides with the Gutenberg update. 

![Annotation on 2023-02-16 at 12-40-47](https://user-images.githubusercontent.com/10015451/219445100-b38bdf46-ecf5-4d67-b081-3ac61b65b789.png)

### Steps to reproduce

1. Enable comments in your site discussion settings
2. Write a post, enable comments for the post, and publish the post
3. Start typing in the correct comment box titled "Leave a Comment"
4. As you type, you'll notice a smaller, out-of-place, looking box appears below the "Leave a Comment box" and its settings. out-of-place

### What you expected to happen

For just the "Leave a Comment" box and its settings to appear on the post. 

### What actually happened

The "Leave a Comment" box (and settings appear) in addition to a smaller comment box. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

The user's theme is Blank Canvas. I'm able to replicate it on my Atomic site with Blank Canvas as well.

**Comment by vajrasar** [comment] 2023-02-16 18:28
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate
- Tested on AT - Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- I replicated the issue on the AT site with the multiple (FSE and non-FSE) themes. It seems to be the Reblog box showing up.
- I also tested with GB deactivated, and the issue persists. 

![kS8PxI.png](https://user-images.githubusercontent.com/2210243/219454890-db1e08d7-fa9f-4226-8671-8a5b196b3836.png)

**Comment by dpasque** [comment] 2023-02-16 21:26
Pinging @fullofcaffeine since some folks had mentioned this aligned with the timing of the Gutenberg update

**Comment by ariel-maidana** [comment] 2023-02-18 18:15
5964950-zd-woothemes
Please notify the user once the issue is fixed.

**Comment by karenroldan** [comment] 2023-10-10 13:51
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

**AT - Blank Canvas**

I couldn't replicate the issue anymore.  

**Desktop** 

![g6jYgV.png](https://github.com/Automattic/wp-calypso/assets/67279475/d24bd507-f906-4f45-8a8a-aa3d9f120cbb)

**Mobile**
![bdQA79.png](https://github.com/Automattic/wp-calypso/assets/67279475/ba4f3e58-bd6e-46b4-a5a0-c592d7307977)

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

**Closed as not planned by karenroldan** 2023-10-10 13:51 UTC
Labels: Bug, [Pri] High, [Feature] Comments, Triaged, [Closed] Not Reproducible, Customer report [LEGACY], [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Content Management
