### ISSUE TITLE
Spotify Block: Resize for smaller devices results in large bottom margin

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#87859] opened 2024-02-25 02:34 UTC
### Quick summary

Spotify embed block is adding too much margin at the bottom when the "Resize for smaller devices" option is selected.

### Steps to reproduce

1. add spotify embed block
2. set block to 'Resize for smaller devices'
3. Note margin below block, which persists on the site front end when published

### What you expected to happen

tighter spacing between Spotify block and blocks added below it

### What actually happened

See screenshot:

<img width="2233" alt="Screenshot 2024-02-24 at 6 29 40 PM" src="https://github.com/Automattic/wp-calypso/assets/1967448/bdebb2d9-6b55-451d-afa6-0a804532104c">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Only workaround currently is to uncheck Resize for smaller devices option.  May be related to https://github.com/Automattic/wp-calypso/issues/82615

**Comment by liviopv** [comment] 2024-02-28 15:53
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
Atomic: 
![CleanShot 2024-02-28 at 15 46 23@2x](https://github.com/Automattic/wp-calypso/assets/14153300/3c245332-e3a4-4447-99c4-0ed524737c1d)

Simple:
![CleanShot 2024-02-28 at 15 48 02@2x](https://github.com/Automattic/wp-calypso/assets/14153300/afde8d60-fedf-45fe-9b71-fe1e60aece8e)

Local site:
![CleanShot 2024-02-28 at 15 49 18@2x](https://github.com/Automattic/wp-calypso/assets/14153300/32b2e890-52a2-4131-a568-bfecf4bda788)




📌 ACTIONS
- Closed as duplicate / by design 

📌 Message to Author
closing as dupe of https://github.com/Automattic/wp-calypso/issues/82615. It has been reported in core here https://github.com/WordPress/gutenberg/issues/51212

**Closed as completed by liviopv** 2024-02-28 15:53 UTC
Labels: Bug, [Pri] High, Triaged, [Status] Priority Review Triggered
