### ISSUE TITLE
FSE: Vertical alignment between the header preview and the full page preview are different.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#36608] opened 2019-10-08 18:16 UTC
Vertical alignment between the header preview (first image) and the full page preview (second image) are different:

<img width="1137" alt="Screen Shot 2019-10-08 at 10 36 11 AM" src="https://user-images.githubusercontent.com/349751/66421607-03010500-e9bd-11e9-8eff-c56c605d0b2b.png">

<img width="1135" alt="Screen Shot 2019-10-08 at 10 35 41 AM" src="https://user-images.githubusercontent.com/349751/66421618-08f6e600-e9bd-11e9-8414-20ac2c5e4ca8.png">

**Comment by noahtallen** [comment] 2019-10-08 18:50
cc @Copons 

This is likely because the style is set to X, but in a block context, there is a bunch of padding/margin around blocks so that the "plus" block inserter button displays.

**Comment by Copons** [comment] 2019-10-09 14:57
This seems to be caused by some totally annoying spacing issues with the `PlainText`'s `textarea`.
The good news is that we are moving away from `PlainText` in all FSE blocks, replacing it with `RichText` (see #36588) which renders the input field as a `contenteditable` element (such as `p` in the Site Description case).

In other words, instead of having to painstakingly replicate the spacing of elements across three screens, we will be able to simply reuse whatever the front-end use for, for example, `p.site-description`.

I'll close this, but I'll also keep in mind to constantly double check on every screen for regressions.

**Closed by Copons** 2019-10-09 14:57 UTC
Labels: [Goal] Full Site Editing, [Type] Bug
