### ISSUE TITLE
[Bug]: "Plugins" breadcrumb link doesn't change on "Switch Site"

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/wp-calypso#66666] opened 2022-08-17 23:26 UTC
### Quick summary

When browsing the Plugins Marketplace, if you switch sites while viewing a plugin, the "Plugins" link in the breadcrumbs still points to the previous site.

https://user-images.githubusercontent.com/140841/185260354-6d3c984f-eca9-411f-a84c-56298034cc3b.mp4

### Steps to reproduce

1. Go to https://wordpress.com/plugins/[site_slug]
2. Click on a plugin
3. Use "Switch Sites" in the upper left menu to change sites.
4. Notice that the "Plugins" link in the breadcrumbs does not update to the site you switched to.

### What you expected to happen

The "Plugins" link in the breadcrumbs should update to link to the "switched site".

### What actually happened

The "Plugins" link in the breadcrumbs points to the previous site you were on.

### Reproducibility

Consistent

**Comment by Rolilink** [comment] 2022-08-18 01:03
Leaving a comment here, this breadcrumbs are being generated by the `PluginDetails` component [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/plugin-details.jsx#L212-L235).

**Comment by lsl** [comment] 2022-08-18 04:58
This isn't the first bug like this, I think the breadcrumbs state implementation should be replaced entirely. 

Thinking some kind of hook that route controllers must call a `setBreadcrumbs` method on layout setup. Then in the same hook provide an `appendBreadcrumb` function like the existing one, that way we have a clear way to reset at the global level on navigation but also have the ability to modify as needed when clicking around without hitting the router.

Could we do this as the fix for this bug?

**Comment by lsl** [comment] 2022-08-18 05:18
More evidence there is something bigger to fix here: pdh6GB-1QJ-p2

Could acceptance for this issue be:

- [ ] Replace breadcrumb state management with a hook or something like it
- [ ] Ensure breadcrumb base plugin link updates site url portion of its crumb when selected site is switched (this bug)
- [ ] Ensure the base plugin link always takes you back to /plugins on click (clicking from a plugin page after searching for it results in needing to be clicked it twice)

**Comment by lsl** [comment] 2022-08-22 05:51
Got a fix for this specific issue in https://github.com/Automattic/wp-calypso/pull/66794

**Comment by lsl** [comment] 2022-08-22 05:55
Can't see the issue leading to the double click problem. Created a follow up issue https://github.com/Automattic/wp-calypso/issues/66795  to track that as its looking more separate. Holding off on a wider fix until I've figured out the root cause.

**Closed as completed** 2022-08-23 06:45 UTC
Labels: Bug, [Status] In Progress, Needs triage
