### ISSUE TITLE
Customizer: AMP section only visible in atomic sites

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#36319] opened 2019-09-25 17:44 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/
2. Go to Design > Customize

#### What I expected
On sites where no extra plugins have been installed, we expect the list of items for a given theme to be the same between simple and atomic sites.

#### What happened instead
AMP option appears in the Atomic site. Simple sites also have AMP, but it doesn't show in the Customizer)

#### Screenshot / Video
Screenshot Simple --  https://cloudup.com/cGiW6GalMlo
Screenshot Atomic -- https://cloudup.com/cCKqTnstEb6

#manual-testing

**Comment by rachelmcr** [comment] 2020-02-20 14:21
I couldn't reproduce this issue. While testing an issue with AMP today, I confirmed that once I launched my new site and it was public (per the [support doc](https://en.support.wordpress.com/amp-accelerated-mobile-pages/)) AMP was enabled and I saw the AMP section in the customizer on a simple site.

**Comment by rachelmcr** [comment] 2020-02-25 12:51
I'm going to close this since I don't think it's an issue anymore, but please reopen if it's still occurring.

**Closed by rachelmcr** 2020-02-25 12:51 UTC
Labels: Atomic, Customizer
