### ISSUE TITLE
Stepper: Seah's onboarding flow 2nd test results

### ISSUE THREAD

**Issue by skim1220** [Automattic/wp-calypso#95106] opened 2024-10-02 21:18 UTC
I tested the Stepper onboarding flow for a few different scenarios and checked if [the key signup events](https://analyticsorienteddata.wordpress.com/2024/08/02/decoding-signup-process-key-steps-moments/) are firing and working as expected. I also checked it against the Classic onboarding flow to verify if there is any difference between two flows. 
- Stepper: https://wordpress.com/setup/onboarding/es/?ref=seahtest
- Classic: https://wordpress.com/start/onboarding/es/?ref=seahtest 

All the information and details are in [this Google Doc](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit?usp=sharing), but I am sharing it as an issue in our Github board as well. 

(cc: @escapemanuele , @MicBosi )

## Summary

In all test scenarios, the key signup events fired correctly, without duplication and in the proper order. The main event properties used in analytics, including the flow and step properties, were accurate and consistent throughout the user journey. I also verified the events triggered by interactions with dropdown menus.

### Things that are not blockers for our experiment but ideal to be fixed soon

1 **[Stepper Tracking]** `calypso_signup_complete` event is incorrectly logging `signup_domain_origin` property, which always appears as `not-set`: 

- [Test #01 (Custom Domain + Paid Plan)](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.dipjs98cnazn)
   Stepper: signup_domain_origin: not-set → Incorrect, it should be ‘custom’ 
   Classic: signup_domain_origin: custom → Correct

- [Test #02 (Use Own Domain + Paid Plan)](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.4ycj0si1o42l)
   Stepper: signup_domain_origin: not-set → Incorrect, it should be ‘use-your-domain’  
   Classic: signup_domain_origin: not-set → Incorrect, it should be ‘use-your-domain’ 

- [Test #03 (Skip Domain + Paid Plan)](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.gm5wzjjvq7y)
   Stepper: signup_domain_origin: not-set → Incorrect, it should be ‘choose-later’  
   Classic: signup_domain_origin: choose-later → Correct

- [Test #04 (Own Domain + Free Plan)](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.9bj0te5qyfq0)
   Stepper: signup_domain_origin: not-set → Incorrect, it should be ‘free’ 
   Classic: signup_domain_origin: free → Correct

- [Test #05 (Free Domain + Free Plan)](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.eupqro9bfmvk)
   Stepper: signup_domain_origin: not-set → Incorrect, it should be ‘free’ 
   Classic: signup_domain_origin: free → Correct

- [Test #06 (Skip Domain + Paid Plan)](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.kwtutkcow9lt) 
   Stepper: signup_domain_origin: not-set → Incorrect. It should be ‘choose-later’
   Classic: signup_domain_origin: choose-later → Correct 

2 **[Stepper Tracking]** Upon clicking “Use my own domain” option at the Domain Selection step in the Stepper flow, `calypso_signup_start` event fires but it shouldn’t. See [this screenshot](https://d.pr/i/9zGlLD). The detailed event log is available in the [Test #02](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.4ycj0si1o42l) results. This does not happen in the Classic flow. 

→ We could filter out this false `calypso_signup_start` event by checking `user_id`. This event will have a numeric user_id attached whereas the _true_ `calypso_signup_start` event would have `anonid`. However, this type of filtering could get complicated when we start considering the existing users entering the signup flows.. So, it would be great to fix this soon so that we do not need to do any extra filtering. 

3 **[Stepper Tracking]** `calypso_signup_actions_submit_step` (`step: use-my-domain`) fires two times. See the details in the [Test #02](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.4ycj0si1o42l) results. 

### Other observations: 

1 **[Stepper Tracking]** On the Checkout page, the Stepper flow logs a step called `create-site` and a step called `site-creation-step` with the following events. These steps however don’t seem to exist in the Classic flow. 

`calypso_signup_step_start` (step: create-site; step: site-creation-step)
`calypso_signup_actions_submit_step` (step: create-site; step: site-creation-step)
`calypso_signup_actions_complete_step` (step: create-site) 

- While it might be good to record the moment of site creation as a separate step like this, `create-site` and `site-creation-step` feel redundant. It would be good to keep just one. The event details are available in all the Test results below. 

- For both `step:create-site` and `step:site-creation-step`, `calypso_signup_actions_submit_step` fires before `calypso_signup_step_start`. Please see [this recording](https://d.pr/v/bgXtQX). It should be the other way around: `calypso_signup_step_start` should fire before `calypso_signup_actions_submit_step`. 

- We do not use these steps in the signup analytics. In case we need to use it in the future, it is better to use `step:create-site` because `calypso_signup_actions_complete_step` event fires only for `step: create-site` (not for `step: site-creation-step`).

2 **[Stepper Tracking]** The checkout page in the Stepper flow fires multiple `calypso_page_view` events and `calypso_signup_step_start` events for three different steps (that seem to be happening behind the scenes): `create-site`, `site-creation-step`, `processing`. This doesn't affect signup analytics, as we don't track these steps—just noting for reference.
 
3 **[Stepper Tracking]** [This PR](https://github.com/Automattic/wp-calypso/pull/94817) introduced `skip_step_render` property to `calypso_signup_step_start`, `calypso_page_view`, and `calypso_signup_actions_complete_step` events. However, I haven’t seen this property with these events during my audit. (cc: @chriskmnds) 

4 **[Classic vs. Stepper]**  When I landed on the Account Creation step, the Classic flow displayed the message “Also available in English” ([screenshot](https://d.pr/i/JxlsIU)), but it didn’t appear in the Stepper flow. 

5 **[Classic vs. Stepper]** I observed three instances where Stepper tracking is more accurate than Classic! 😄 
- In the Account Creation step, the Classic flow logs it as step:user-social, while the Stepper flow logs it as step:user, which is clearer and more accurate.
- On the Domain Selection step, the Classic flow fires `calypso_page_view` (path: /start/domain/es) twice, while the Stepper flow fires it once, as expected.
- The Stepper flow correctly fires both `calypso_signup_actions_submit_step` (step:domains) and `calypso_signup_actions_complete_step` (step:domains) after completing the Domain Selection step and moving to Plan Selection. In contrast, the Classic flow fires `calypso_signup_actions_complete_step` (step: domains) on the Checkout page instead of the Plan Selection page. I think the Stepper tracking is more accurate in this case. 

**6** On the right pane of the checkout page, clicking the upsell button ([screenshot](https://d.pr/i/dDwpDk)) didn’t trigger any Tracks event. This happens in both Classic and Stepper. It would be nice to track this interaction as well. 

**7** On the checkout page, changing the domain renewal interval triggers calypso_checkout_composite_plan_length_change event. However, its new_product_slug property doesn’t include any information about the renewal interval (e.g., dotblog_domain). This occurs in both the Classic flow and the Stepper flow.

## Results 

Please find all the test details in the Google Doc links below. For each test scenario, you can see the steps taken as well as the key Tracks events and properties checked in the chronological order (in the order of firing).

- [Test #01 (Custom Domain + Paid Plan)](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.dipjs98cnazn)
- [Test #02 ((Use Own Domain + Paid Plan)](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.4ycj0si1o42l)
- [Test #03 (Skip Domain + Paid Plan)](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.gm5wzjjvq7y)
- [Test #04 (Own Domain + Free Plan)](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.9bj0te5qyfq0)
- [Test #05 (Free Domain + Free Plan)](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.eupqro9bfmvk)
- [Test #06 (Skip Domain + Paid Plan)](https://docs.google.com/document/d/1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s/edit#heading=h.kwtutkcow9lt) - Skipped domain selection in a different way than in Test 02

**Comment by chriskmnds** [comment] 2024-10-03 08:19
> [Stepper Tracking] Upon clicking “Use my own domain” option at the Domain Selection step in the Stepper flow, calypso_signup_start event fires but it shouldn’t. See [this screenshot](). The detailed event log is available in the 1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s-gdoc results. This does not happen in the Classic flow.
> 

I can also investigate here. However, I want to highlight something:

> → We could filter out this false calypso_signup_start event by checking user_id. This event will have a numeric user_id attached whereas the true calypso_signup_start event would have anonid. However, this type of filtering could get complicated when we start considering the existing users entering the signup flows.. So, it would be great to fix this soon so that we do not need to do any extra filtering.

Filtering out on the analytics ends **should** be the way forward. Unless we are looking at a bug (like the [50-times bug](https://github.com/Automattic/wp-calypso/pull/95028) from the other day), then we need to accept that Stepper may record the same event multiple times given whatever logic may be causing a rerender. I am not sure why I feel the need to repeat this over and over, it doesn't excuse fixing potential bugs either (the above could be a bug), but it is a decision that we agreed on in https://github.com/Automattic/wp-calypso/issues/94175, and it will become especially prevalent once https://github.com/Automattic/wp-calypso/issues/94108 is fully deployed. 

@skim1220 / @MicBosi / @escapemanuele Just saying, we need to make sure we are properly aligned behind this, otherwise detract from it. Otherwise, it will look weird. Just want to make sure we have agreement (especially @skim1220 since you bring it up without any sort of footnote). "extra filtering" will be the norm going forward, and "no filtering" the exception e.g. for flows that want to capture the whole spectrum/variation of props being passed through.

**Comment by skim1220** [comment] 2024-10-03 09:41
Hey @chriskmnds , sorry that my intention wasn't clear. I'd like to clarify the reasoning behind the request you mentioned. 

> "Extra filtering" will be the norm going forward, with "no filtering" being the exception (e.g., for flows that need to see the full range of properties being passed through).

I understand we’ll never reach a point where no filtering is needed—it’s simply not feasible, and it’s not our goal. Instead, we're aiming to standardize tracking so that filtering is applied as consistently as possible throughout the user signup journey, preferably across all signup flows and steps.

If we don’t address this, we’ll need to introduce extra filtering just to handle this "Use my own domain" case at the Domain Step—something that isn't necessary for other domain choices as well as for other signup steps. Moreover, this issue may not even exist in other signup flows, making the filtering overly specific to this one case.

My point was that we could implement extra filtering as a temporary fix until the issue is resolved, rather than relying on extra filtering as the long-term solution.

Does this make sense? Let me know what you think.

**Comment by chriskmnds** [comment] 2024-10-03 12:02
Thanks @skim1220 for replying. 

I think we need to approach things a little differently - and I feel some of the messaging may not have been clear through https://github.com/Automattic/wp-calypso/issues/94175

I am not arguing that this instance of `calypso_signup_start` firing in the middle of a flow isn't due to a bug. However, what I am arguing for is that it shouldn't surprise us.

> My point was that the issue needs to be resolved because it is not aligned with our primary usage of calypso_signup_start event in the analytics. 

The way we are encoding things right now, as I explained above and in the various discussions, is that any event may fire at any interval throughout a flow. This was the decision and the flexibility we are giving flow implementations. **No exceptions** to this rule. So you may find `calypso_signup_start` event being recorded over and over as long as the flow decided to wrap it with any form of "changing" or "async" data to record. It should not surprise you, and I think the only to run with this is to embrace it. If we keep flagging exceptions, then we'll never rest. I explain more below.

What matters to you, from a "typical" analytics POV, is whether the first instance of that event matches your expectations i.e. whether it's as accurate and as semantically meaningful as you would expect it. This is the guarantee the code gives while remaining flexible to keep things SIMPLE for the API we are building for **unconditionally** (double empasis) extending the event props.

This will be the "new way" of handling events in Stepper. You will need to embody whatever filtering is necessary, update P2s and FG pages, make it part of the "new standard". There's just no other way around this to avoid ambiguities. 

For posterity, I didn't come up with any of the above - I merely took a suggestion and ran with it (it started with @MicBosi 's suggestion [here](https://github.com/Automattic/wp-calypso/issues/94175#issuecomment-2334569529), which I carried on discussing in that issue, also [here](https://github.com/Automattic/wp-calypso/pull/94248#discussion_r1745992249), and a little bit [here](https://github.com/Automattic/wp-calypso/pull/93983)). Allowing events to be recorded multiple times is a workaround to investing in a more ambiguous and complex system to allow flows to extend props unconditionally (see https://github.com/Automattic/wp-calypso/issues/94108 ). IMO we either accept and embrace or leave it.

**Comment by MicBosi** [comment] 2024-10-03 13:52
I'll expand on my position regarding my commend [here](https://github.com/Automattic/wp-calypso/issues/94175#issuecomment-2334569529) to make it 100% crystal clear:

Example cases where given the complexities is OK to see multiple events fire and we'll handle at data analytics time:

- Users refreshes browser, page is redrawn and events are fired again
- Users clicks back, goes to previous step, page is redrawn, events fire again, user might even take different actions compared to previous visit to the same step
- Somehow the flow allows users to revisit previous steps, which are redrawn and Tracks events fire again

Gray cases:
- Somehow we decide to send users to a step that users have no access to (like `domains` when logged out) and redirect them somewhere else to fulfil the preconditions (like log-in) then revisits the step they were supposed to see at the beginning... as long as we can distinguish the real step starts from non real ones it's ok. The fundamental issue here is bad UX and having Tracks events actually can be helpful in monitoring this issue.

In cases such as the ones above I don't think it's worth/simple/safe for Calypso to try and synthesise in real time a "cleaned" up version of the users's journey through Tracks events, removing "duplicate" step start events, providing an overall final version of what the user did etc. Going down this path is complex and just asking for trouble I think.

Example cases that are not OK:

- Tracks events firing out of order. 
   This is a big one. Violating this principle outright breaks tools like Tracks Funnels, Tracks Sessions and others and makes any analytics way more difficult.

- Firing multiple times the same event for no reason / not firing at all for unknown reasons:
  This can be trickier than it seems because establishing if there is a reason and whether that reason is reasonable, requires people talking to each other so we'll inevitably reach out to devs whenever things look off and don't have an explanation.

In my mind these are some useful north starts to keep in mind:

- Tracks events should simply be a close reflection of what the user does and experiences in realtime.
- Tracks events should be timely, ie fire as the user experiences/triggers a step, choice, view etc. 
  As opposed to being cached, delayed, batched, saved for later to be fired where a more convenient piece of code gets activated etc.
- Tracks events should reflect what users do, not how a given framework is implemented. 
  The implementation should follow the semantics of a Tracks event, not the other way around, although historically for Calypso that's been the case many times unfortunately.

---

@chriskmnds my understanding is that this issue falls under the _"Tracks events firing out of order"_ category, which I don't see why it should be surprising that @skim1220 is reporting it, unless you think Tracks events order can be random and disjoint from the order in which users experiences things?

**Comment by chriskmnds** [comment] 2024-10-03 14:06
@MicBosi I will reply tomorrow - but want to just emphasise something concerning:

> @chriskmnds my understanding is that this issue falls under the "Tracks events firing out of order" category, which I don't see why it should be surprising that @skim1220 is reporting it, unless you think Tracks events order can be random and disjoint from the order in which users experiences things?

I mentioned above:

> What matters to you, from a "typical" analytics POV, is whether the first instance of that event matches your expectations i.e. whether it's as accurate and as semantically meaningful as you would expect it. This is the guarantee the code gives while remaining flexible to keep things SIMPLE for the API we are building for unconditionally (double empasis) extending the event props.

So the guarantee is that events will fire in the correct order, irrespective if they fire multiple times (for whatever reason e.g. some async property changes value). I'm trying to keep things simple i.e. we accept a (any) scenario that a given event can fire multiple times and have a guarantee that the first time it fires is the correct from an "order" point of view e.g. you won't see the first instance of `calypso_signup_start` get recorded after a `calypso_signup_step_submit`. This is the simplicity that I'm referring to. Allowing the scenario of multiple records only on exclusive cases is a can of worms. I've seen it over and over - some dependency is introduced, not ignored, some other ignored, etc. At the basis, I think it should be a pretty boolean/discrete semantic.

**Comment by MicBosi** [comment] 2024-10-03 14:54
@chriskmnds Thanks for clarifying your position. I think I get it now. Unfortunately I don't think that is a blank check that we can sign for Stepper, accepting that the same event can be fired both at its expected place and also at any random place after that.

Even for things as simple as `calypso_page_views` this would be a pretty outrageous expectation to have.

If the user hasn't started a new signup why in the world would it be acceptable to fire it again? Same goes for any other event, especially key ones during onboarding.

If Classic could do it, I don't think is too much to ask for Stepper to just not spam us with spurious Tracks events and then assume we'll have to cleanup the mess at analytics time, with no recourse, regardless of the cause of the duplicate events.

We are willing to work with some reasonable degree of noise, especially if that noise is a reflection of the true user behaviour, definitely not if it's a regression from Classic due to some implementation detail - that, if anything, is hinting at fundamental flaws in the design.

I think is also worth mentioning that we don't care about all events in the same way. Maybe for some events it does makes sense or is more practical doing what you are proposing but things like `calypso_signup_start/complete`,`calypso_signup_step_start/calypso_signup_actions_submit_step/calypso_signup_actions_complete_step` we'd expect them to not regress from Classic, especially for the key steps, like domain, plan, user.

**Comment by escapemanuele** [comment] 2024-10-03 15:43
Opened a few issues to keep track/work on the problems:

- https://github.com/Automattic/wp-calypso/issues/95124 for `signup_domain_origin`
- https://github.com/Automattic/wp-calypso/issues/95125 for `calypso_signup_start`
- https://github.com/Automattic/wp-calypso/issues/95126 for `calypso_signup_actions_submit_step`

**Comment by chriskmnds** [comment] 2024-10-03 16:16
Thanks for clarifying @MicBosi 

> [@chriskmnds](https://github.com/chriskmnds) Thanks for clarifying your position. I think I get it now. Unfortunately I don't think that is a blank check that we can sign for Stepper, accepting that the same event can be fired both at its expected place and also at any random place after that.
> 
> Even for things as simple as `calypso_page_views` this would be a pretty outrageous expectation to have.
> 
> If the user hasn't started a new signup why in the world would it be acceptable to fire it again? Same goes for any other event, especially key ones during onboarding.
> 
> If Classic could do it, I don't think is too much to ask for Stepper to just not spam us with spurious Tracks events and then assume we'll have to cleanup the mess at analytics time, with no recourse, regardless of the cause of the duplicate events.
> 
> We are willing to work with some reasonable degree of noise, especially if that noise is a reflection of the true user behaviour, definitely not if it's a regression from Classic due to some implementation detail - that, if anything, is hinting at fundamental flaws in the design.

Ok. Let's just put that to rest then. I'm glad to be out of this discussion with whatever resolution. What suddens me is this spurred from your proposal, I've expressed how weird `calypso_signup_start` getting recorded multiple times may look, I've pinged over and over in discussions. I feel like we've done a bit of a circle, at least what looks to me 🤯 

> I think is also worth mentioning that we don't care about all events in the same way. Maybe for some events it does makes sense or is more practical doing what you are proposing but things like `calypso_signup_start/complete`,`calypso_signup_step_start/calypso_signup_actions_submit_step/calypso_signup_actions_complete_step` we'd expect them to not regress from Classic, especially for the key steps, like domain, plan, user.

All the same to me :-)

**Comment by MicBosi** [comment] 2024-10-03 19:02
> What suddens me is this spurred from your proposal

Thanks @chriskmnds, I am flattered by the credit you give me based on that 1 comment 😄 where I'm asking your (plural) expert opinion on the pros and cons of chasing every rabbit hole and corner case to avoid "duplicate" events.

I was trying to make your life a bit easier so you don't feel pressured to implement and maintain some complex new system that Classic does not have, even before we are on par with Classic. As a corollary, I also wanted to make it clear that this requirement is not coming from us in Data.

_However_, Classic still remains the baseline. Let's not do worse than Classic™.

Saying you don't need to fix today all the corner case flaws that Classic had, does not imply we can now introduce a host of new ones, or we can run for the hills with a radically different approach that is not compatible with the existing infrastructure.

I'm not even sure how relevant or theoretical this discussion is, since, also thanks to all your great work so far, it feels like we are pretty close to match Classic and the issues Seah reported are relatively minor at this point.

This is why is important to have these discussions, to find alignment, test in real life conditions, and figure out a reasonable path forward.

I hope tomorrow we can approach this with fresh minds and I also want to reiterate how much we appreciate your help in figuring these things out and in getting Stepper over the finish line so we can all celebrate!

**Comment by agrullon95** [comment] 2024-10-07 17:57
Thanks for the test results @skim1220.
>2 [Stepper Tracking] Upon clicking “Use my own domain” option at the Domain Selection step in the Stepper flow, calypso_signup_start event fires but it shouldn’t. See [this screenshot](). The detailed event log is available in the 1BPDrnHB2lA3TBfVOrDIp-arsOCCUZ6LAWXVoT1xCy-s-gdoc results. This does not happen in the Classic flow.

I don't see the `calypso_signup_start` event triggered when I click the "Use my own domain" option on the Domain selection step. Can you test this again when you get a chance?

**Comment by skim1220** [comment] 2024-10-08 07:23
👋 @agrullon95 , thanks for taking a look at this! 
I tested it on [https://wordpress.com/setup/onboarding/es/?ref=seahtest](https://wordpress.com/setup/onboarding/es/?ref=seahtest), and it still happens to me. Please see [the recording](https://d.pr/v/J3h6CM):

https://github.com/user-attachments/assets/33eca525-1426-49f6-85a5-2326a5620a8f

`calypso_signup_start` fires correctly once when the flow is initiated. 
However, when I select the "Use your domain" option at the Domain Selection step, `calypso_signup_start` event fires again.

**Comment by escapemanuele** [comment] 2024-10-08 15:35
@skim1220 just did some testing and... It's because of the `ref` parameter! We'll take a look

**Comment by escapemanuele** [comment] 2024-12-20 10:43
Closing this as no longer actual. Thanks for the great testing Seah!

**Closed as completed by escapemanuele** 2024-12-20 10:43 UTC
