### ISSUE TITLE
Front-End Toolbar behaving strangely on small Viewports

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#52985] opened 2021-05-18 19:17 UTC
The front-end toolbar appears to be behaving strangely on small viewports. A few examples:

Chrome dev tools view:

![image](https://user-images.githubusercontent.com/545779/118710209-99291e00-b7e3-11eb-9cce-bb834f0a1364.png)

Unlaunched site:

![image](https://user-images.githubusercontent.com/545779/118710221-9f1eff00-b7e3-11eb-89f7-69a061a72e7a.png)

Changing the viewport size on desktop:

![image](https://user-images.githubusercontent.com/545779/118710301-b6f68300-b7e3-11eb-8844-31db560cdbc9.png)

#### What I expected to happen

Something akin to the current back-end view.

![image](https://user-images.githubusercontent.com/545779/118710316-bd84fa80-b7e3-11eb-966a-a405c7d04498.png)

**Comment by donlair** [comment] 2021-05-20 15:35
I've got a diff for this at D61661-code

**Comment by sixhours** [comment] 2021-05-20 21:06
Are you still able to reproduce this one Ian? I tested it while I was reviewing Don's patch and wasn't able to see what you're seeing:


https://user-images.githubusercontent.com/2124984/119048785-b6015500-b98d-11eb-822d-ddd359bc58de.mov

**Comment by danielwrobert** [comment] 2021-05-21 00:29
I'm not able to produce the issue on the un-launched site (the floating `ul` dropping down - see https://test211367648.wordpress.com/), which is consistent with what @sixhours is seeing.

However, I am able to produce the missing elements described for the launched site (see https://test929607703.wordpress.com/). Both sites are on the Free plan.


**https://test211367648.wordpress.com (un-launched):**
![CleanShot 2021-05-20 at 20 18 34](https://user-images.githubusercontent.com/481776/119064303-118d0c00-b9a9-11eb-96bd-1921a7f507af.gif)


**https://test929607703.wordpress.com (launched):**
![CleanShot 2021-05-20 at 20 20 58](https://user-images.githubusercontent.com/481776/119064335-279acc80-b9a9-11eb-8813-4c5fa57dc503.gif)

**Comment by ianstewart** [comment] 2021-05-21 20:12
I can reproduce on a launched site using the same test site as Dan.

![image](https://user-images.githubusercontent.com/545779/119193254-fc66ba80-ba46-11eb-8d3e-6c3c75a31d47.png)

Happens around that breakpoint.

**Comment by ianstewart** [comment] 2021-05-21 20:13
> I'm not able to produce the issue on the un-launched site

@simison what kind of device was that screenshot from?

**Comment by simison** [comment] 2021-05-25 14:48
> what kind of device was that screenshot from?

Samsung A71 on Firefox or Chrome. Likely .com simple site.

Sorry can't see what site it was anymore. :-(

**Comment by danielwrobert** [comment] 2021-05-25 17:16
> Sorry can't see what site it was anymore. :-(

@simison Feel free to use the un-launched test site I posted above (https://test211367648.wordpress.com/) and let us know if you can reproduce it there.

**Comment by yansern** [comment] 2021-05-27 07:36
It appears that when `admin-bar.css` is loaded the header button goes away. D61661-code#1269965

**Comment by donlair** [comment] 2021-05-28 13:34
The fix for this is now deployed.

**Comment by yansern** [comment] 2021-06-01 21:12
> It appears that when admin-bar.css is loaded the header button goes away. 

Found the culprit.

This seems to be caused by AMP requiring core's admin-bar's stylesheet as a dependency.
See: https://github.com/ampproject/amp-wp/pull/4382/files#diff-4d201f41a17fa3b698d9548b8d417866cb3f03780acd8692b7accac477efeb65R115

A WPCOM site with AMP enabled will exhibit this issue.

Update: More context here: p1622582091014800-slack-CME773H8S

**Comment by simison** [comment] 2021-06-02 08:05
>  caused by AMP requiring core's admin-bar's stylesheet as a dependency.

What's the solution? All simple sites have AMP enabled I believe.

**Comment by yansern** [comment] 2021-06-02 10:21
> What's the solution? All simple sites have AMP enabled I believe.

The solution is to hook into some filter and remove the `admin-bar` dependency from `amp-icons` from the WPCOM side.
In the middle of figuring this out lol.

**Comment by WunderBart** [comment] 2021-06-04 10:57
FYI this seems to have been causing our mobile E2Es to fail against trunk since May 29th https://teamcity.a8c.com/buildConfiguration/calypso_WPComTests_gutenberg_mobile/6245917

<img width="408" alt="Screenshot 2021-06-04 at 12 59 04" src="https://user-images.githubusercontent.com/1451471/120791650-c0e2ea80-c534-11eb-8912-88a04e852577.png">

Some slack context:
- p1622745527036300-slack-C1A1EKDGQ
- p1622801191246700-slack-CBG1CP4EN

**Comment by yansern** [comment] 2021-06-04 11:25
This just increases the urgency of getting it fixed. On it.

**Comment by yansern** [comment] 2021-06-04 15:43
The proper phab patch fix has landed: D62348-code

**Closed as completed** 2021-06-10 12:06 UTC
Labels: Bug, Mobile Web
