### ISSUE TITLE
Pages: "Front page" indicator is missing for the home page

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#14796] opened 2017-06-06 10:06 UTC
#### Steps to reproduce
1. Starting at the customizer for an AT site: https://atraultest.blog/wp-admin/customize.php
2. Select a page (Home) as a Front Page. Click on the Save & Publish button
3. Click on the Pages link on Calypso to see the list of published pages (https://wordpress.com/pages/atraultest.blog)

#### What I expected
I expected an icon/mark/flag showing which one is the front page as in regular WordPress.com sites. Example with loscavilas.com attached:
![pages raulanton wordpress com 2017-06-06 11-54-41](https://cloud.githubusercontent.com/assets/6404071/26823744/02dc4602-4aaf-11e7-809a-d526739b554b.png)

#### What happened instead
There is no such a mark/flag
![pages site title wordpress com 2017-06-06 11-55-47](https://cloud.githubusercontent.com/assets/6404071/26823783/2d2d9834-4aaf-11e7-9d15-08be1014561c.png)

#### Browser / OS version
This is Browser independient

#### Screenshot / Video
Already added 

#### Context / Source
Found while looking for another issue on 431147-hc
So the issue is also viewable at davidlee2017.com

**Comment by designsimply** [comment] 2018-02-16 20:02
Tested and confirmed using the following testing steps:

1. Go to My Sites > Customize > Homepage Settings.
1. Select the "A static page" radio button.
1. Select any page for the "Homepage" option.
1. Click the "Publish" button to save changes.
1. Click the "x" at top left.
1. Go to My Sites > Site Pages.
1. Check to see if the page selected in step 3 has a "Front page" indicator.

<strong>Result:</strong> the page set as the home page in My Sites > Customize > Homepage Settings does not have a designated "Front Page" indicator in My Sites > Site Pages.

**Comment by rachelmcr** [comment] 2018-08-29 11:26
All Atomic and Jetpack sites will show incorrect information for the site's front page, due to an API issue reported in 7940-wpcom. The underlying API issue needs to be resolved to fix this display issue in Calypso.

I confirmed that the issue still exists, and I'll leave this issue open for now for visibility.

**Comment by rachelmcr** [comment] 2018-08-29 11:41
Sorry, I was mistaken about Jetpack sites — those are also resolved, although it takes a little time for the API to update when you change those settings on the site. (If you test this issue, be sure to wait a moment for Calypso to update when the front page setting is changed.)

I'm closing this issue and the related 7940-wpcom as resolved.

**Closed by rachelmcr** 2018-08-29 11:41 UTC
Labels: API, Jetpack, Pages, [Pri] High, [Type] Bug
