### ISSUE TITLE
[Editor] Preferences are not being saved

### ISSUE THREAD

**Issue by ricklabsdotn8** [Automattic/wp-calypso#80852] opened 2023-08-21 09:49 UTC
### Quick summary

When changing the preferences for the editor, they are removed when the page is reloaded.

### Steps to reproduce

1. Edit a page/post
2. Go to preferences
3. Turn on/off any of the settings
4. Reload the pages

### What you expected to happen

The preferences should have been updated

### What actually happened

The preferences are not saved

https://github.com/Automattic/wp-calypso/assets/78526686/28a8cc5f-5368-4ddf-89a0-3d42715f9bd6

### Impact

All

### Available workarounds?

No and the platform is unusable

### Logs or notes

Browser
- MS Edge, 

OS
- Windows

Source
- 6689722-zen

**Comment by cuemarie** [comment] 2023-08-21 17:16
Noting this looks quite like this issue, closed as solved in April: https://github.com/Automattic/wp-calypso/issues/64324

My first try at reproing in Mac OS > Firefox, I could not replicate in any environment. Will check the repro steps on that issue as well.

**Comment by cuemarie** [comment] 2023-08-21 17:23
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic –**Could Not Replicate**
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on Simple, following the repro steps found here: https://github.com/Automattic/wp-calypso/issues/64324#issuecomment-1467011892

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/43f4267e-563a-4195-8046-2e507052822e

📌 ACTIONS
- @Automattic/explorers FYI, this looks very similar to an issue y'all fixed earlier! https://github.com/Automattic/wp-calypso/issues/64324

**Comment by autumnfjeld** [comment] 2024-01-17 20:59
Putting this on Lego's board @Automattic/lego

**Comment by arthur791004** [comment] 2024-01-18 07:58
Tested on my simple sites and the issue seems to be resolved.

### Site Editor

https://github.com/Automattic/wp-calypso/assets/13596067/41df5ad3-08e0-4b74-8368-1beab06c7a36

### Post Editor

https://github.com/Automattic/wp-calypso/assets/13596067/fc79df37-72e4-4339-a503-3ac9167dd21d

**Comment by arthur791004** [comment] 2024-01-22 07:48
I'm closing this issue as it's not reproducible. Feel free to re-open the issue if you encounter it again 🙂

**Closed as completed by arthur791004** 2024-01-22 07:48 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] High, Triaged, Customer report [LEGACY], [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience
