### ISSUE TITLE
Email (powered by Titan) : Managing Email Accounts on Titan Prompts Create New Email Account Popup

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#52387] opened 2021-04-28 15:29 UTC
### Steps to reproduce the behavior

1. Go to "My Sites > Upgrades > Domains" and click **Add** under the email column on the domain you would like to register.
2. Generate as many Mailbox as you like, then click "Add Email".
3. Complete checkout, then proceed to click on "Manage Email" > "Manage your email settings and accounts".
4. You will then be redirected to https://manage.titan.email/email-accounts to manage your emails there.

#### What I expected to happen

Admins are able to manage email accounts right away.

#### What actually happened

The "Create new email account" popup appeared instantly, suggesting to create more email accounts (which I've created them in Step 2 on WordPress.com)

### Context

Domain Verification for the email account was not verified at first, so it could be related to that.

The issue resolved itself after 15-20 minutes time as I no longer see the "Create new email account" popup when visiting https://manage.titan.email/email-accounts

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.

Intermittent, it only happens once when the domain was recently registered and created email account. 

I'm not able to reproduce this for the second time under a different domain names, or on test accounts.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image link 2](https://cldup.com/pnjRc96zPq.png)
image link: https://cloudup.com/cI0jwN-W2K2

**Comment by kosiew** [comment] 2021-05-27 07:09
Hi @edwinho89 ,

Thanks for reporting this and the detailed steps.

I am closing this since it's not reproduceable.
It is important anyway as a report of an issue (you did manage to reproduce it once).

If you or anyone encounters this again, can you add more details for us to reproduce this.
Thanks.

**Closed as completed by kosiew** 2021-05-27 07:09 UTC
Labels: Bug, [Feature Group] Support, Professional Email, [Closed] Not Reproducible, Empathy Testing
