### ISSUE TITLE
BALASANA Buttons Are Created and Behave Differently from Button Blocks

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#43267] opened 2020-06-13 23:51 UTC
####  Steps to reproduce

1. This seems to vary theme to theme, but the Balsana template's buttons seem to function differently, and appear differently in the code editor, from a standard Button Block. 
2. Discovered on Appetite, so start by activating Appetite theme.
3. Create a new Page, and use the Balsana Template. Publish it and check out the alignment of the buttons.
4. View the Code Editor, highlight and copy the columns section for those buttons in Balsana, then create a new page, paste that code into the code editor.
5. Switch to Visual, and manually add columns with a Heading, text, and a Button Block. Group them, make them wide width in the group. Align them each to Center, publish the page, and note the difference between the Balasana columns and manually created columns. 
6. They seem to function differently across different themes, but why would the template's buttons be created differently/specially compared to a standard button block?

#### What I expected
The template to follow the same rules as if someone were manually creating it.

#### What happened instead
The template is created in a way that doesn't seem to be possible to recreate manually using blocks, and it functions differently as a result.

#### Browser / OS version
All.

#### Screenshot / Video

The top is a manual recreation and the bottom is the Balasana Template:
![image](https://user-images.githubusercontent.com/30731356/84581302-d6478d80-ad94-11ea-8eba-764f9dbe2920.png)

Here is how the buttons look when manually created in the Code Editor:
![image](https://user-images.githubusercontent.com/30731356/84581322-eeb7a800-ad94-11ea-853b-d00cff7e3d3d.png)

And here's how they look when using the Balasana template in the Code Editor:
![image](https://user-images.githubusercontent.com/30731356/84581346-fecf8780-ad94-11ea-9900-840e0c42c6aa.png)

And the differences behave differently. The template version is not able to be manually recreated, but it's used in our template, and has interesting behaviors across different themes.

#### Context / Source

#reallife #painpoint #user-report

**Comment by simison** [comment] 2020-06-15 09:16
Assuming "Appetite" and "Balsana" are either pattern, page template or theme names? 🙃

**Comment by scosgro** [comment] 2020-06-16 00:25
> Assuming "Appetite" and "Balsana" are either pattern, page template or theme names? 🙃

Appetite is a theme: https://wordpress.com/theme/appetite

Balasana is both a theme: https://wordpress.com/theme/balasana

And a template (layout?): 
![image](https://user-images.githubusercontent.com/30731356/84718325-248f9480-af2d-11ea-826f-ca225a44c1ab.png)

**Comment by simison** [comment] 2020-06-16 07:24
I see. The difference seems to be that you have `buttons` (container of many buttons) and a `button` (a single button) blocks. Latter doesn't center-align.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/87168/84744067-7121b100-afbb-11ea-8a26-43e277b74277.png">

@kjellr :wave: Have there been issues with button alignments in themes, specifically in _Appetite_ theme?

**Comment by kjellr** [comment] 2020-06-17 14:41
It's very possible that there's an issue in Appetite. This should be filed over in the Premium Themes Trac.

**Comment by scosgro** [comment] 2020-06-17 17:12
> It's very possible that there's an issue in Appetite. This should be filed over in the Premium Themes Trac.

Is there a reason the Balasana template is using something different from a Button Block as it's added? If it used the actual button block (container?), it should work across all themes.

The issue is that the template can be used regardless of the active theme, since users are prompted to add a template (layout?) to a page whenever a new page is created. Themes seem to know how to handle the Button Block, but however it's added to Balasana (an individual button - not a block?), other themes don't seem to be prepared to know how to handle that.

**Comment by simison** [comment] 2020-06-18 08:29
>Is there a reason the Balasana template is using something different from a Button Block as it's added? If it used the actual button block (container?), it should work across all themes.

@ianstewart question for ya :-)

**Comment by ianstewart** [comment] 2020-06-18 14:57
They appear to work as expected in other Varia-themes. Coutoire, for example.

![image](https://user-images.githubusercontent.com/545779/85036697-0fdc1800-b14a-11ea-9195-41d5a3f46250.png)

**Comment by ianstewart** [comment] 2020-06-18 15:00
And can appear broken in non-Varia-themes. Twenty Twenty, for example.

![image](https://user-images.githubusercontent.com/545779/85037118-8e38ba00-b14a-11ea-9433-9f63f9d4ab60.png)

**Comment by ianstewart** [comment] 2020-06-18 15:27
(Still looking at the issue with re-creating the layout in the WP.com Editor with @iamtakashi.)

**Comment by ianstewart** [comment] 2020-06-18 17:43
I also can't get re-build the Balasana Layout from scratch in Balasana because I can't add a single Button Block on it's own and the Single Buttons, center-aligned in columns, aren't center-aligning.

![image](https://user-images.githubusercontent.com/545779/85054168-4709f380-b161-11ea-8bbd-02fe10516798.png)

**Comment by ianstewart** [comment] 2020-06-18 17:45
> The difference seems to be that you have buttons (container of many buttons) and a button (a single button) blocks. Latter doesn't center-align.

> however it's added to Balasana (an individual button - not a block?)

I think there's a few issues here. 

1. Single Buttons in the Buttons Block are not center-aligning in non-Varia themes..
2. Single Buttons in the Buttons Block are not aligning in any themes including Varia themes.
3. How did we get a single button outside the buttons block in the Balasana homepage layout?

**Comment by ianstewart** [comment] 2020-06-18 17:54
> The difference seems to be that you have buttons (container of many buttons) and a button (a single button) blocks. Latter doesn't center-align.

> however it's added to Balasana (an individual button - not a block?)

I think there's a few issues here. 

1. Single Buttons in the Buttons Block are not center-aligning in non-Varia themes..
2. Single Buttons in the Buttons Block are not aligning in any themes including Varia themes.
3. How did we get a single button outside the buttons block in the Balasana homepage layout?

We can update the layout but I think we'll still need to fix the theme issues.

**Comment by simison** [comment] 2020-06-18 17:58
> How did we get a single button outside the buttons block in the Balasana homepage layout? 

It might've been possible in older editor versions but has since been deprecated.

**Comment by kjellr** [comment] 2020-06-18 18:33
Hmm, if this is happening in _all_ themes (and I think it is, based on my testing), I think this is probably a regression that should be fixed on Gutenberg's side. I'll do a little digging in later today.

**Comment by kjellr** [comment] 2020-06-18 22:40
Yeah, this does indeed seem like a regression in Gutenberg. Gutenberg provides front-end styles to ensure that buttons are center aligned in the _Buttons_ block, but it does not do so for the old _Button_ block. I've filed an issue here: https://github.com/WordPress/gutenberg/issues/23291

**Comment by yansern** [comment] 2020-08-05 22:51
Looks like this is fixed in https://github.com/WordPress/gutenberg/pull/23381.

**Closed by yansern** 2020-08-05 22:51 UTC
Labels: [Goal] Page Templates, [Type] Bug
