### ISSUE TITLE
Exmoor, Bute theme fonts broken upon content layout width change in site editor

### ISSUE THREAD

**Issue by metabreakr** [Automattic/wp-calypso#81525] opened 2023-09-06 20:21 UTC
### Quick summary

For themes such as Exmoor and Bute:

When the default content width is changed, the theme font (e.g. Roboto) reverts to a default serif font upon saving in the site editor. This can be undone if the site editor has not been closed after immediately making the change. The font (e.g. Roboto) can not be selected in global styles after this change has been made. 

https://github.com/Automattic/themes/assets/39252765/4aa811f1-d25b-4051-8c3a-1ef94ac71213

### Steps to reproduce

1. Activate Exmoor
2. Go to Site Editor → Styles → Layout
3. Change the layout to something other than the default
4. Save the changes
5. Observe that the theme font defaults to a serif font
6. Visit Site Editor → Styles → Typography → Text, and observe that the theme font (e.g. Roboto) is not present in the list

### What you expected to happen

I expected to change the template layout without the font appearance changing.

### What actually happened

The theme fonts became unavailable.

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

This appears to happen on simple sites, as a quick test on Atomic (with or without Gutenberg active) doesn't yield the same results.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

None

**Comment by cuemarie** [comment] 2023-09-07 19:22
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated on Simple site only; AT site tested with Bute did not show the same issue
Simple site using TT3 also did not show the same issue, though default fonts for TT3 were set to "default" and "system font" rather than another selection.

**Simple Site, Exmoor theme**

https://github.com/Automattic/wp-calypso/assets/27249804/7e30f7f0-ee61-40dc-9dd0-543426327a22

📌 ACTIONS
- Transferred to `wp-calypso`
- FYI @Automattic/t-rex

**Comment by alaczek** [comment] 2024-08-28 01:02
I wasn't able to replicate this on either simple or atomic. The fact that in previous test the issue was only on simple makes me think it's something Gutenberg related, that has since been fixed.
I'm closing this one - feel free to reopen if it happens again or I missed something.

**Closed as completed by alaczek** 2024-08-28 01:02 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Normal, Triaged, [Platform] Simple, [Feature] Global Styles, [Product] WordPress.com
