### ISSUE TITLE
FSE: no option to update when change block padding settings

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#55374] opened 2021-08-11 10:14 UTC
### Steps to Reproduce

1. open page template
2. select a block and try to adjust padding width without making other changes
3. see that option to update doesn't happen until other changes are made

![padding](https://user-images.githubusercontent.com/47717887/129011948-a3f8b819-fdf9-43ea-a0fc-d1791f809156.gif)

### What I expected to happen

any change to settings should prompt ability to update template

### What actually happened

update button stayed greyed out

### Context

empathy testing

### Operating System

macOS

### Browser

Chrome/Chromium

### Reproducibility

Consistent

**Comment by jordesign** [comment] 2021-08-24 02:18
Recreated and confirmed: It looks like changing the padding on elements in the Site Editor does *not* register as a change which allows saving.

**Comment by jeyip** [comment] 2021-11-06 00:27
@creativecoder @zaguiini  This seems to fall under the purview of the site design tools pod. 

I confirmed the problem as well. Curious if either of you have thoughts on priority -- I think normal or low makes sense since the workaround is relatively easy.

**Comment by creativecoder** [comment] 2021-11-08 18:57
If this is not WP.com specific, I think the next step is opening a Gutenberg issue.

**Comment by jeyip** [comment] 2021-11-11 18:53
I'll open a Gutenberg issue soon. After more investigation, I think we might want to bump this up to a high / normal priority.

From what I can tell, a large number of block editor settings deal with this issue (text color, link color, typography, etc.), but there is a more nuance than first laid out in the issue description.

The first set of changes to _any_ of the aforementioned settings is recognized correctly. After saving, however, subsequent changes to the same setting are not recognized, and will not refresh the save or update button in the site editor.

**Comment by jeyip** [comment] 2021-11-11 19:46
Closing this in favor of https://github.com/WordPress/gutenberg/issues/36417

**Closed as completed by jeyip** 2021-11-11 19:46 UTC
Labels: Bug, [Pri] Normal, [Goal] Full Site Editing, Empathy Testing
