### ISSUE TITLE
Earn: "New" badge is sidebar is distracting for new customers

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/wp-calypso#38293] opened 2019-12-09 16:31 UTC
The Earn item in the Calypso sidebar now (#37912) has a "new" badge.

<img width="291" alt="image" src="https://user-images.githubusercontent.com/191598/70453604-0b39f700-1a77-11ea-9239-c9d06a7b8972.png">

This makes sense if you're an existing customers, but for new customers coming in the door literally everything is _new_. It feels strange and distracting to mark the Earn section as something _new_ for new customers.

Perhaps we can only show this badge for customers for which the Earn section is _actually_ new — that is, customers who have had a account before the existence of the New section.

@davemart-in @artpi @apeatling @rickybanister

**Comment by rickybanister** [comment] 2019-12-09 18:09
I agree. For new customers it's probably more valuable to give them a prompt to visit Earn at the right time in their journey, either in an email, or a post-launch customer home item, or something contextual.

**Comment by ianstewart** [comment] 2019-12-12 16:43
Relatedly, it doesn't appear to update (and lose it's "new" status) after investigating the Earn page.

**Comment by Aurorum** [comment] 2019-12-15 14:31
PR in #38440 for hiding the badge for new users. I agree with @ianstewart that it should also disappear after the Earn page is visited, but I think that's a separate issue which is out of scope of that PR. :)

**Comment by artpi** [comment] 2019-12-17 09:30
> Relatedly, it doesn't appear to update (and lose it's "new" status) after investigating the Earn page.

That was never the intended behavior.
As I mentioned in #38440 - this badge should be good to completely remove. 

@Aurorum - you have to be aware that these discussions also are fleshing out our business decisions, so sometimes we will completely change direction. Thank you for your PR! :)

**Closed** 2019-12-18 14:16 UTC
Labels: Earn, [Type] Defect
