### ISSUE TITLE
Not able to edit embedded blocks/ Block toolbar not visible in the Editor

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#95944] opened 2024-10-31 13:07 UTC
### Quick summary

When editing a Page:
- the block toolbar does not show,
- embedded blocks are not visible in the Editor's "list view"
- Clicking the three dot icon on a block does not show options to "Add before" and "add after".

Could not repro on a test site, also "simple" site.

I initially reported this on p1730379472430379/1730292536.850279-slack-CB0B2G43X.

Possibly related to Gutenberg 19.5.0 update.

### Steps to reproduce

1. Start at the WordPress page editor for an existing page on a site with the latest Gutenberg version.
2. Notice the UI for zoomed out view (the up and down arrows on the left side of a block, for example, are a good hint).
3. Notice only top-level blocks shown in the List View with no ability to discover what's embedded (child-level blocks).
4. Click "zoom out" icon in the Editor, then click to zoom back in to return to the regular Editor view.
5. Notice the Editor goes back to normal as expected.

### What you expected to happen

The zoomed out view should not persist in the regular Editor canvas view.

### What actually happened

The zoomed out view persists.

### Impact

One

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

1. Click "zoom out" icon in the Editor, then click to zoom back in to return to the regular Editor view.
2. Notice the Editor goes back to normal as expected.

### Platform (Simple and/or Atomic)

Simple

**Comment by davipontesblog** [comment] 2024-10-31 13:09
Seen on this user report: 8965320-zd-a8c

**Comment by jartes** [comment] 2024-11-21 15:44
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
👋🏻 @davipontesblog Thanks for reporting this one! This was already fixed recently with a never version of GB. I can't reproduce it :)

**Closed as not planned by jartes** 2024-11-21 15:44 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] Low, Needs triage, Customer report [LEGACY], [Platform] Simple, [Product] WordPress.com, [Feature Group] Editor Experience
