### ISSUE TITLE
Possible Incompatibility with Out-of-Date Safari Browsers and Top Toolbar

### ISSUE THREAD

**Issue by masperber** [Automattic/wp-calypso#76686] opened 2023-05-08 21:36 UTC
### Quick summary

Today I encountered two separate reports from users who were having difficulty the Gutenberg toolbar when the "Top Toolbar" option was enabled. Both users were using out-of-date versions of Safari.

It seems that the top toolbar simply does not appear in the correct context when a block is selected.

Example screenshot, cropped for privacy:

<img width="728" alt="Screenshot 2023-05-08 at 5 32 55 PM" src="https://user-images.githubusercontent.com/12906034/236940050-cb80ecfe-c098-485c-9c70-36e9650daf8b.png">

Customer reports:
43152663-hc - Safari version 15.4
6266068-zen - Awaiting reported Safari version

### Steps to reproduce

I have not been able to reproduce this on my end, since my version of Safari is not out of date, and it would be cumbersome to downgrade.

### What you expected to happen

The top toolbar should change context, showing options for the selected block.

### What actually happened

The top toolbar does not change context.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment] 2023-05-09 22:19
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on BrowserStack (Atomic test site) - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Gave this a try using BrowserStack, testing Safari versions 15.6 and 14.1 - but the top toolbar behaved as expected on my test AT site in those scenarios. 

#### Screenshots/Recordings

![Markup on 2023-05-09 at 15:13:00](https://github.com/Automattic/wp-calypso/assets/27249804/08dc7d01-d357-4392-a621-34483d2cec05)

![Markup on 2023-05-09 at 15:13:21](https://github.com/Automattic/wp-calypso/assets/27249804/2c2384d6-1ffa-425a-9f31-30078045b862)

📌 ACTIONS
- Assigned to Non-Urgent

📌 Message to Author
- Thanks for the report, @masperber ! Understandably a hard one to try to repro test.
- Marked this as `Low` priority for now, let's see if we get additional reports of the matter and are able to narrow in on any patterns with reports.

If future HE's run into this with users, please share at least the user's Safari version in your report.  Thank you!

**Comment by wynwin** [comment] 2023-06-07 18:20
Another report in 6380112-zen. 

Missing tools related to top-toolbar in Safari 16.5. 

How it shows in Safari: 
<img width="749" alt="Screenshot 2023-06-08 at 5 53 15 AM" src="https://github.com/Automattic/wp-calypso/assets/31700597/b24e52db-a157-4e00-a20c-9a519f61ddd6">


Here is how it shows in Chrome: 
<img width="374" alt="Screenshot 2023-06-08 at 5 54 25 AM" src="https://github.com/Automattic/wp-calypso/assets/31700597/ae66152f-00d8-4a3a-8022-da4dea2ba084">

**Comment by cuemarie** [comment] 2023-06-07 23:22
Hey @wynwin ! Your droplr links are password protected and not visible. Can you please upload those directly to GH instead, so we can see them, and they won't expire?

**Comment by liviopv** [comment] 2023-06-16 14:49
@cuemarie I think this is more widespread than initially thought.

I was able to reproduce on my site with a custom domain in Safari 16.1:


https://github.com/Automattic/wp-calypso/assets/14153300/3f9100ef-dee9-4751-867c-0d9bfe42a98f

**Steps**
1. Atomic site with custom domain
2. Open a new post or page
3. Enable top toolbar
4. Add an Image Block
5. Switch the alighment
6. The toolbar disappears completely

**Comment by liviopv** [comment] 2023-06-16 15:03
Escalated it here p1686927769338249-slack-C02FMH4G8

**Comment by cuemarie** [comment] 2023-06-21 00:53
📌 FINDINGS/SCREENSHOTS/VIDEO
- Hey @liviopv ! I'm able to replicate what you're seeing on Simple, Atomic, and self-hosted sites, regardless of the primary address, once an Image block is added to the post.   
- Since this report started on a different topic, I think it'll be clearer to move this to a new report.

📌 ACTIONS
- Closing in favor of a new issue specific to this: https://github.com/Automattic/wp-calypso/issues/78453

**Closed as completed** 2023-06-21 01:01 UTC
Labels: Bug, [Pri] Low, [Browser] Safari, [Platform] Simple, [Platform] Atomic
