### ISSUE TITLE
Domains: able to select a domain that is taken

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#36435] opened 2019-09-30 21:37 UTC
- Entered a domain that was taken during some signup testing.
- Saw a notice that the domain was taken.
- But also saw that the was available for selection.

Did not expect to be able to select a domain that was taken. See screenshot below.

![image](https://user-images.githubusercontent.com/545779/65918927-91afc980-e3a0-11e9-8794-6db549bee1d8.png)

**Comment by michaeldcain** [comment] 2020-10-12 15:02
I just tested this again and am unable to reproduce it. I'm going to go ahead and close this.

<img width="1085" alt="Screen Shot 2020-10-12 at 11 01 39 AM" src="https://user-images.githubusercontent.com/942359/95761449-549c3980-0c7a-11eb-87f3-388f550f22e8.png">

**Closed by michaeldcain** 2020-10-12 15:02 UTC
Labels: Domains, [Type] Bug
