### ISSUE TITLE
Domains: Hide email verification messaging for .me domains

### ISSUE THREAD

**Issue by spncrb** [Automattic/wp-calypso#11552] opened 2017-02-22 22:12 UTC
.me domains do not require email address verification, therefore we should make it possible to hide verification messages in calypso.

We should make this an option that we can toggle per tld, as I suspect other TLDs we add may also lack the verification requirement.

Right now we for sure show it on the left sidebar:
<img width="261" alt="screen shot 2017-02-22 at 2 08 19 pm" src="https://cloud.githubusercontent.com/assets/8921630/23234885/6e668d54-f908-11e6-98da-e649cac212bd.png">

As well as a the top of the plans page (Which is where the "fix" link goes), as well as the top of /domains/$SITENAME/manage/$DOMAIN.me:
<img width="789" alt="screen shot 2017-02-22 at 2 08 23 pm" src="https://cloud.githubusercontent.com/assets/8921630/23234954/a347441e-f908-11e6-8981-ea1d155c547f.png">

We also add the resend email button in domains/manage/$SITENAME/edit/$DOMAIN.me:
<img width="756" alt="screen shot 2017-02-22 at 2 11 19 pm" src="https://cloud.githubusercontent.com/assets/8921630/23235014/cc95545a-f908-11e6-9c1d-a7b16ca583b1.png">

@wensco for prioritization.

**Comment by wensco** [comment] 2017-02-22 22:53
Thanks for posting this @spncrb. As discussed in Slack/p2, we moved new .me registrations to use OpenHRS today and email verification is not supported for this TLD since it's a ccTLD and not subject to the ICANN verification requirement.

I believe the root cause is that we initially store a status of "unverified" for .me domains. We either need to change the status value for .me upon registration to be "verified" (or something else that won't trigger user-facing elements related to verification), or we need to somehow hide the elements.

I like Spencer's idea: 

> We should make this an option that we can toggle per tld, as I suspect other TLDs we add may also lack the verification requirement.

Cc @dzver this could be something to consider as part of our TLD database work

**Comment by umurkontaci** [comment] 2017-02-22 23:24
I think this shouldn't be a concern of Calypso and API should provide the appropriate value.

**Comment by klimeryk** [comment] 2017-02-22 23:50
Thanks for reporting @spncrb - this should be fixed now. @dzver made a quick fix that marks all new `.me` domains as verified and he also seems to have updated existing `.me` domains (with OpenHRS) as verified :)

**Closed by klimeryk** 2017-02-22 23:50 UTC
Labels: Domains
