### ISSUE TITLE
Paragraph Block: Sudden Invalid content error

### ISSUE THREAD

**Issue by damiannep** [Automattic/wp-calypso#36979] opened 2019-10-23 06:36 UTC
Paragraph blocks in a column block all say "This block contains unexpected or invalid content" in Calypso. Clicking resolve shows an error due to the font attribute:

![font error](https://cld.wthms.co/PCFtp7+)
*Link: https://cld.wthms.co/PCFtp7*

The user says that they created the page using blocks only, and it was working fine, until this error suddently appeared. I'm trying to replicate this on my test site but hasn't so far. @mmtr  noticed that when using a custom font size for paragraphs such as 17.5px, the block should have the `has-custom-size` class, but it is missing in the screenshot I shared. 

As discussed in p1571745571002300-slack-gutenberg-on-dotcom, this issue needs further testing to see what may be causing it, and if we have some reproducible steps.

#### Context / Source
 #user-report in 2439277-zen (need to update user when/if we know something)

**Comment by damiannep** [comment] 2019-10-25 10:58
User is also getting the following error when they try to update some pages `not a valid JSON response`. I can't recommend a conflict test as they are only running our plugins:

![our plugins](https://cld.wthms.co/BgXnWt+)

**Comment by gwwar** [comment] 2019-10-30 00:27
@vindl did @Automattic/cylon want to take this one? Looks like this customer has some standard FSE plugin setup.

**Comment by gwwar** [comment] 2019-10-30 00:28
@vindl  please kick back to us if this is unrelated to FSE.

**Comment by noahtallen** [comment] 2019-10-30 00:58
> they are using a theme from us, Wanderer

No FSE code should be running if they're not on Maywood, so I think it wouldn't be related to our stuff. Let us know if you still want us to take a look!

**Comment by vindl** [comment] 2019-10-30 11:56
> @vindl did @Automattic/cylon want to take this one? Looks like this customer has some standard FSE plugin setup.

@gwwar The proper way to check for FSE activation status is in Blog RC. All Atomic sites have FSE plugin activated by default, to enable related functionality like SPT for example, even though FSE proper might be off (determined by site option flag that's set during transfer). As @noahtallen pointed out this site is also not using Maywood, but Wanderer theme, which doesn't support FSE.

> @vindl please kick back to us if this is unrelated to FSE.

I don't think this is FSE related.

**Comment by arunsathiya** [comment] 2022-05-21 16:52
Since it has been many years since the original report, and no reports from other customers, I'll close this issue. Gutenberg and WordPress.com has changed a lot since 2019, so the issue isn't likely reproducible anymore.

**Closed by arunsathiya** 2022-05-21 16:52 UTC
Labels: [Type] Bug, User Waiting, [Goal] Gutenberg, User Report
