### ISSUE TITLE
.org Plans: Disconnecting Jetpack means you can't cancel

### ISSUE THREAD

**Issue by aheckler** [Automattic/wp-calypso#17008] opened 2017-08-08 17:29 UTC
To repro:

1. Have a Jetpack site connected to WordPress.com.
2. Purchase a plan for it.
3. Disconnect the site from WordPress.com.
4. Try to cancel the plan. You can't.

If the site is disconnected, the place where you'd cancel the plan never loads:

<img width="890" alt="screen shot 2017-08-08 at 13 28 42" src="https://user-images.githubusercontent.com/5512652/29085505-87639ed8-7c3d-11e7-9108-ff16144168f0.png">

This creates support load for something that, as a user, I should be able to do for myself.

Inspired by 615408-zen, where the user was shutting down his site and didn't cancel his JP plan before deleting the site itself.

**Comment by rachelmcr** [comment] 2017-12-13 14:42
Looks like this is a duplicate of https://github.com/Automattic/wp-calypso/issues/13421; closing this issue and adding these details in a comment there.

**Closed by rachelmcr** 2017-12-13 14:42 UTC
Labels: .org Plans, Jetpack, [Type] Bug
