### ISSUE TITLE
"Flash" of visitors/visits bars across Stats and Insights page

### ISSUE THREAD

**Issue by eamcgill90** [Automattic/wp-calypso#39792] opened 2020-03-01 23:02 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/[anysite]
2. If you do not see it upon loading the page, try refreshing. 

#### What I expected

There should be no flash of these bars.

#### What happened instead

![screenshot](https://cdn-std.droplr.net/files/acc_734386/BegSa6)

#### Browser / OS version

Happening across Safari, Firefox and Chrome across Mac OS and PC
(Am on a team meetup and my team is able to recreate the issue as well)

#### Screenshot / Video

Example videos:
https://d.pr/v/1VTaVS
https://d.pr/i/sEFWaj

**Comment by kriskarkoski** [comment] 2020-03-11 02:45
I was seeing this for some time, but can not reproduce at this time. @eamcgill90 Are you still able to reproduce this?

**Comment by lancewillett** [comment] 2020-03-11 07:18
I've been seeing this multiple times a day — both Safari and Chrome desktop browsers, with different users.

Seems kind of bad... it looks clunky and broken for 1-2 seconds before correcting itself.

**Comment by kriskarkoski** [comment] 2020-03-11 12:45
After some further testing I think something in stats must be cached locally so this only happens consistently the first time you view them until that's cleared. 

I think I've been seeing it often when checking user's sites that I haven't loaded before, but couldn't reproduce on my main sites because I've viewed them all recently. Once I checked a site I check less frequently I was able to reproduce the issue.

**Comment by katiebethbrown** [comment] 2020-03-11 15:23
I can still reproduce this as well, but only only the first stats load for any given site.

**Comment by eamcgill90** [comment] 2020-03-11 17:45
I can no longer reproduce the issue.

**Comment by lancewillett** [comment] 2020-03-11 18:33
Heh, funny that a "welcome back" behavior would be to show the broken UI for a second. 😄 

@eamcgill90 That's likely why you don't see it again, already cached from a recent visit.

What is likely the underlying fix is to preload or fetch the bars before rending the graph.

**Comment by lancewillett** [comment] 2020-03-12 06:52
Shared this in Slack today to hopefully get a look from a @Automattic/team-calypso developer. In case it's something that might indicate a timing issue or performance change in recent refactoring. CC @griffbrad

**Comment by simison** [comment] 2020-03-12 07:41
This could depend on CSS bundles loading order, which depends on order you visit pages on Calypso.

**Comment by tyxla** [comment] 2020-03-13 22:44
I've been trying to reproduce, but unsuccessfully. Is it possible that this occurs only on certain sites? I've started clean multiple times, for different sites (with little and with a LOT of stats) and no luck. Can anyone reproduce consistently with a certain site/user?

**Comment by lancewillett** [comment] 2020-03-16 23:26
Here's one way to reproduce, with a user that has more than 1 site — ideally 5 to 10 sites or more that you don't visit often.

Steps:

1. Log in with Safari, and go to Stats (`/stats/day/example.com`
2. Click "Switch Site" at top left of sidebar
3. Choose another site from the list — one you haven't used in a while
4. Watch the stats graph; it'll be all the lines for a second or two

**Comment by tyxla** [comment] 2020-04-05 10:03
Sorry about that, but I'm currently on a long leave, perhaps someone else could take a look?

**Comment by lancewillett** [comment] 2020-04-05 15:08
Testing in Safari, Firefox, and Chrome today across 3 different WordPress.com users I was not able to repeat the behavior any more.

Closing for now as "works for me."

**Closed by lancewillett** 2020-04-05 15:08 UTC
Labels: Stats, [Type] Bug
