### ISSUE TITLE
Settings: Date and Time Format Isn't Saving

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#55807] opened 2021-08-28 13:15 UTC
### Steps to Reproduce

1. Set your interface language to "Português do Brasil" on your WordPress.com account's settings
2. Go to your site's Writing settings, on Configurações > Escrita
3. Click on "Formato de data e hora" (Date and time format)
4. Change from/to the first and last custom option
4. Click on "Salvar configurações" (Save settings)
5. Refresh the page.

### What I expected to happen

For the date and time format to be saved.

### What actually happened

It shows the warning saying that there are unsaved changes on the page, when you try to refresh. And once you do, your changes aren't saved.

### Context

Reported here: https://wordpress.com/pt/forums/topic/nao-consigo-salvar-alteracoes-nas-configuracoes/

I wasn't able to replicate this with my interface set in English, might be related to this other issue: https://github.com/Automattic/wp-calypso/issues/53339

### Operating System

macOS

### Browser

Chrome/Chromium

### Simple/Atomic

Simple

### Console and/or error logs

None.

### Available Workarounds

Change the interface to English, make the change, and change it back to Portuguese.

### Reproducibility

Consistent

**Comment by formosattic** [comment] 2021-08-31 09:44
I was able to reproduce with other languages , setting both Date and Time to Custom just won't save. 
English was fine for me as well.

![troubleshooting](https://user-images.githubusercontent.com/15944096/131480478-9749698f-d561-4ad3-9c3c-208d522f7d9b.gif)

When testing other options for Time, the Custom will start showing extra slashes.
![image](https://user-images.githubusercontent.com/15944096/131480597-1a97c6e1-7666-4df2-a335-e44b82365966.png)

**Comment by Robertght** [comment] 2021-09-07 19:32
A similar case is solved here with more details: p2-p2EDhh-1kl

For my case, I changed the format through wp-admin directly to `g:i a` which seems to have fixed it.

**Comment by mreishus** [comment] 2021-09-13 18:15
My initial investigation shows that this is related to the word "de" being used in the pt-br date formats. I haven't looked at the code yet, but here's what I've noticed from looking at the front end.

* **Some date formats work completely fine. You are able to select them, save, reload, and see them selected.**

https://user-images.githubusercontent.com/937354/133134591-003029e0-c135-493e-b80e-cf2f55d0a128.mp4

^ Correct Save 1


https://user-images.githubusercontent.com/937354/133134614-83b4dcb0-5c46-4b7c-9da1-f64deec6d17e.mp4

^ Correct Save 2

* **The "13 de setembro ..." acts oddly even before you save it.** With the working formats, when selecting that format, the radio selection next to that format stays filled in. For "13 de setembro ...", the selected radio jumps down to the custom format, even though I didn't select a custom format.


https://user-images.githubusercontent.com/937354/133134786-432b5c13-ca97-4571-8c46-149ead67f31a.mp4

^ This date format's radio button cannot be selected

* *Why backslashes are needed*. If you examine the custom date format for the "13 de setembro..." selection, you'll see `\d\e`. Why is this? It's because we want to display the literal word "de". In the date format specification, "d" and "e" are special codes; just like yyyy-mm-dd uses the letters y, m, and d for special codes instead of those literal letters. To display the actual letters `d` and `e`, we use `\d` and `\e`. This is probably related to the root cause of the bug.


https://user-images.githubusercontent.com/937354/133135234-5e2e9d4b-e9db-4a40-8315-7288b2dcae91.mp4

^ Why backslashes are needed

* **Extra slashes added after saving**. When I have `\d\e` in a custom format, save, and reload, I now see `\\d\\e`.
  * It also thinks I have unsaved changes when I press F5, even though I don't.

https://user-images.githubusercontent.com/937354/133135302-e60022f5-6c5d-4b6d-8333-82290b299179.mp4

^ Double backslash after save + Incorrect unsaved changes warning

--

The behavior is inconsistent. sometimes I can select the first!

https://user-images.githubusercontent.com/937354/133141605-8d9ed619-c8cc-4f3d-93b2-6cda37f5ee7a.mp4

**Comment by mreishus** [comment] 2021-09-13 18:47
Data sent over the wire when updating to custom format "Y-m-d \d\e".

REQUEST
```
POST /rest/v1.4/sites/123456/settings
{"default_post_format":"0","timezone_string":"America/Chicago","date_format":"Y-m-d \\\\d\\\\e","time_format":"H:i","start_of_week":"1","jetpack_testimonial":false,"jetpack_testimonial_posts_per_page":10,"jetpack_portfolio":false,"jetpack_portfolio_posts_per_page":10,"posts_per_page":10,"posts_per_rss":10,"rss_use_excerpt":false,"wpcom_publish_posts_with_markdown":false,"infinite_scroll":true,"infinite_scroll_blocked":false,"podcasting_category_id":0}
```

RESPONSE
```
{"code":200,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"updated":{"date_format":"Y-m-d \\\\d\\\\e"}}}
```

**Comment by mreishus** [comment] 2021-09-13 20:41
PR Up for review: https://github.com/Automattic/wp-calypso/pull/56221

**Comment by carinapilar** [comment] 2021-09-22 20:54
Another report on 4306488-zd-woothemes

**Comment by mreishus** [comment] 2021-09-22 21:04
We deployed a fix for this about 1 hour ago. I'm not able to access 4306488-zd-woothemes, so I can't tell if that happened before or after we deployed it.

**Comment by carinapilar** [comment] 2021-09-22 21:18
Ah, great, thanks @mreishus! It was a request from last week. I'm happy to know that this will get fixed! 🎉

**Comment by mreishus** [comment] 2021-09-23 15:18
Great, it is now fixed :)

**Closed as completed by mreishus** 2021-09-23 15:18 UTC
Labels: Bug, [Feature] Site Settings, [Pri] High, i18n, Triaged, [Pod] Flow Patrol (Manage)
