### ISSUE TITLE
Checkout: Lack of next steps on Thank You page after Premium theme purchase

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#13574] opened 2017-05-02 18:54 UTC
There's no content underneath the "What Now" heading on the Thank You page after purchasing a standalone Premium theme.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start
2. Follow the screen prompts and choose a Premium theme at /start/themes.
3. Choose a free site address at /start/domains and the free plan at /start/plans.
4. Follow the remaining steps to set up a new site and make payment for the Premium theme.

#### What I expected

To be led to a Thank You page that contains some useful links to next steps. This expectation is based on how the Thank You page appears after purchasing a domain or a paid plan.

#### What happened instead

The Thank You page had a "What Now" heading but there was no content underneath it.

#### Browser / OS version

Chrome 57.0.2987.133 / MacOS Sierra 10.12.3

#### Screenshot / Video

<img width="1069" alt="screen shot 2017-05-02 at 19 36 17" src="https://cloud.githubusercontent.com/assets/2998162/25633482/1dacd416-2f6f-11e7-9885-b5c18f3cc1ca.png">

#### Context / Source

#dogfooding, #manual-testing

**Comment by jeremeylduvall** [comment] 2017-05-23 13:13
I took a look at this one, but I'm having a hard time reproducing. I can't seem to find a Premium theme available on wordpress.com/start/themes during signup. I believe [these are the themes](https://github.com/Automattic/wp-calypso/blob/master/client/lib/signup/themes-data.js) that should be displaying, and it looks like they're all free.

Siobhan, do you happen to remember which theme you purchased to trigger this?

**Comment by SiobhyB** [comment] 2017-05-26 16:14
@jeremeylduvall: Sorry, my steps to replicate were actually wrong. The correct steps are:

1. Google "WordPress.com themes" while logged out of WordPress.com and click on the first link to arrive at: https://wordpress.com/themes
2. Select the three dots next to a Premium theme and then "Pick this design".
3. Follow the screen prompts to set up a new site. Choose a free site address at /start/domains and the free plan at /start/plans.
4. Follow the remaining steps to set up a new site and make payment for the Premium theme.

It can also be replicated by purchasing a Premium theme on an existing free or Personal site. You'll need to actually make payment for the theme to replicate, using credits doesn't seem to produce the same effect.

**Comment by jeremeylduvall** [comment] 2017-05-26 17:10
Awesome - thank you! I think I was missing this:

> using credits doesn't seem to produce the same effect.

I'll take a peek next week!

**Comment by gwwar** [comment] 2018-02-16 00:16
I'm having trouble reproducing this one either from the /themes flow or purchasing a theme on an existing site. Note that I'm not using credits, but am using a fake card.

Here's what I see on the new user flow, starting from /themes logged out.
![screen shot 2018-02-15 at 4 13 44 pm](https://user-images.githubusercontent.com/1270189/36287732-6f0c1fe4-126b-11e8-92f3-7cefbdc233d0.png)

**Comment by gwwar** [comment] 2018-02-16 21:24
Going to close this one out since I suspect we completely redid the thank you page. Feel free to reopen if this is not the case.

**Closed by gwwar** 2018-02-16 21:24 UTC
Labels: Post Checkout, [Pri] High, [Type] Bug

**Comment by SiobhyB** [comment] 2018-02-23 11:16
@gwwar: Sorry for the delay getting back to you! I can confirm that I'm no longer able to replicate. Thanks for looking.
