### ISSUE TITLE
Reader: Captions from tiled galleries appear to be included in the text on default cards 

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#10241] opened 2016-12-22 20:16 UTC
This is supposed to be displayed as a gallery card. Instead, it's showing up as a regular card:

https://wpcalypso.wordpress.com/read/feeds/23059853/posts/1164416389
![screenshot 2016-12-22 12 12 33](https://cloud.githubusercontent.com/assets/4924246/21438875/03f67ab8-c840-11e6-8627-71d93eb84652.png)

Another example:
https://wordpress.com/read/blogs/5276229

<img width="388" alt="screen-shot-2016-12-22-at-thu-dec-22-12-35-36-pm" src="https://cloud.githubusercontent.com/assets/4924246/21439353/66832af8-c842-11e6-9cb5-261a794c76fd.png">

H/t @designsimply

**Comment by fraying** [comment] 2016-12-22 21:17
Sneaky captions! They should not be part of excerpts.

**Comment by thepelkus-too** [comment] 2016-12-23 18:49
I thought about picking up this ticket since it seemed like the fix is pretty easy, but I had a few questions once I looked into the implementation; maybe y'all could offer a more informed opinion?

— A sensible way to fix the caption part of this appeared to be by adding the right selector to the list in rule-create-better-excerpt.js, but I couldn't tell whether to add the selector closest to the caption, ```.tiled-gallery-caption```, or whether to remove the gallery altogether by adding ```.tiled-gallery```. Thoughts?

— @jancavan mentioned that this should be displayed as a gallery card. It appears to be failing the test in normalization-rules.js that looks for enough images (4) of a large enough size (at least 350px wide) that would set ```post.displayType``` to ```DISPLAY_TYPES.GALLERY```. (In this case, the gallery images are all not wide enough.) Should a separate issue be made for this? Is there an obvious solution?

**Comment by jancavan** [comment] 2016-12-23 22:04
@thepelkus-too Thanks for offering to help!

>  It appears to be failing the test in `normalization-rules.js` that looks for enough images (4) of a large enough size (at least 350px wide)

In this example https://wordpress.com/read/blogs/5276229, they do appear <350px, but the images on https://wpcalypso.wordpress.com/read/feeds/23059853/posts/1164416389 are all pretty large so I'm not sure why it's not being displayed as a gallery card. They used to so this is a possible regression.

**Comment by thepelkus-too** [comment] 2016-12-27 21:52
> @thepelkus-too Thanks for offering to help!

My pleasure!

> the images on https://wpcalypso.wordpress.com/read/feeds/23059853/posts/1164416389 are all pretty large 

Looking at the page itself, I'm inclined to agree with you. However, when I'm stepping through the debugger, I see that the post images in the parsed DOM have widths of ["163", "163", "162", "246", "246"]. Checking against the payload from the AJAX request for this post, the content field shows that these are indeed the image widths in the HTML that's delivered. Not having looked at that piece of the API yet, I'm not sure what determines those widths, but that could certainly be an issue.

Regarding regression behavior, do you have a sample commit for when it worked as expected? It looks like the image width requirement (which is admittedly only one piece of this puzzle) was added in commit 8ecc3d6f885638b42fc99c9b163331da340cc1a7, which was rolled into the last tagged release.

**Comment by bluefuton** [comment] 2017-01-11 08:20
Thanks for looking into this @thepelkus-too! I see that the misclassification of the post is now fixed (I believe by @samouri's sterling work on #10310).

> I couldn't tell whether to add the selector closest to the caption, .tiled-gallery-caption, or whether to remove the gallery altogether by adding .tiled-gallery. 

I think we may as well remove the whole `.tiled-gallery` there, because with the captions gone, there'll be no other content to include in the excerpt. I'll work up a quick PR to do that :)

**Closed** 2017-01-11 14:10 UTC
Labels: Reader, [Type] Bug
