### ISSUE TITLE
Customizer: Save Changes cog is missing on some unlaunched sites.

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#54430] opened 2021-07-10 23:34 UTC
Customizer options lost on unlaunched sites, which left the Customizer stuck in Draft Saved mode on unlaunched sites that had the Customizer set to Draft prior to this bug.

I can only half replicate this. I'm not sure how the user got to Draft, unless a new change was introduced recently that broke the switching function, and got them stuck there.

### Steps to reproduce the behavior

1. Create a new WordPress.com simple site.
2. Select a theme (Nature in the example, but every theme I've tested seems to work as well). Do NOT launch the site.
3.  Go to the Customizer and make a change. 
4. Try to save the changes in the Customizer as a Draft. There are no options available to move the Customizer from Publish to Draft. For this user, they are stuck in Draft, and can't switch it to Publish.

#### What I expected to happen
The Customizer to have a cogwheel option available to switch between Draft/Published options:

![image](https://user-images.githubusercontent.com/30731356/125178596-80ae0200-e19b-11eb-9506-cce70c32ff62.png)

#### What actually happened
Those options are not available.

![image](https://user-images.githubusercontent.com/30731356/125178680-003bd100-e19c-11eb-9375-824d0e36a3b4.png)

### Context
A user had their Customizer set to the Save Draft option, and lost their ability to switch it to Save Changes. They're stuck in Draft Mode. 

![image](https://user-images.githubusercontent.com/30731356/125178693-134ea100-e19c-11eb-96a9-031ec8cc53b8.png)

Launching the site seems to resolve the issue in my testing. 
#### Browser / OS version
All
#### Is this specific to the applied theme? Which one?
All I've tested
#### Does this happen on simple or atomic sites or both?
Simple sites only
#### Is there any console output or error text?
Not that I'm aware of.
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Seems to affect all sites. If someone was in Draft Saved previously, they might be stuck there.
#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Edit to add original report in 4121417-zd

**Comment by kwight** [comment] 2021-07-12 15:41
@andres-blanco I think you were in this area recently, can you take a look please?

**Comment by andres-blanco** [comment] 2021-07-12 15:56
Yes, I can!

**Comment by andres-blanco** [comment] 2021-07-13 19:36
I can verify that the cog doesn't appear, that's a behaviour that seems desired since it's hidden on purpose. But I don't understand why.

I tried to get the `Save Draft` button from a new site and I wasn't able to reproduce it.

I will keep trying to find out why the cog is hidden for new sites.

**Comment by andres-blanco** [comment] 2021-07-14 11:47
One thing to note is that the cog is only hidden trough CSS (not server side), so if you enable it in the chrome inspector you can see it and check the ‘Save Draft’ option. If you save as draft then when you reload you will get to the state described in the issue.

That was the only way I could find to reproduce the issue.

**Comment by scosgro** [comment] 2021-07-15 21:26
Another report in 26854311-hc. They were looking to switch to Draft mode, but no cogwheel was present (site is not yet launched).

**Comment by sixhours** [comment] 2021-08-04 15:35
It appears the extra settings are hidden on purpose, since there's potential for confusion when saving a draft of a site that isn't launched, or scheduling the changes to go live on a site that isn't launched.

The CSS indicates we really intend to hide that button:

```
#customize-save-button-wrapper.is-wpcom-unlaunched #publish-settings {
    display: none !important; /* overrides an inline style */
}
```

I see a few potential options:

* Don't hide the settings for unlaunched sites. Maybe hiding the cog wheel is more confusing than the alternative. -- This is the easiest option, obviously, but there may be unintended side effects. I'll do some testing.
* Only hide the options if the Customizer settings are set to "Save Changes", not draft or schedule -- Also relatively easy to implement, although again, I'm not sure what unintended side effects there are from allowing sites to save drafts or schedule customizations on unlaunched sites.
* Set the Customizer setting to "Save Changes" automatically when a site is unlaunched -- We'd probably need to find a hook that fires on site creation/at the point a site is set to unlaunched. Trickier to track down that place.

**Comment by sixhours** [comment] 2021-08-04 15:58
Chatted with @michaeldcain about this and it turns out these options won't work if a new user hasn't confirmed their email address. D38569-code has the backstory.

I'd suggest we un-hide the button for folks who *have* confirmed their email address to at least avoid confusion for more users. A stretch goal would be to add some kind of messaging to the Customizer when a user hasn't confirmed their email address.

**Comment by sixhours** [comment] 2021-08-04 17:03
Started working on this in D65128-code

**Comment by sixhours** [comment] 2021-08-06 14:41
Deployed in r229924-wpcom. Created a feature request for more clarity in the Customizer about non-verified users; closing this as fixed!

**Closed as completed by sixhours** 2021-08-06 14:41 UTC
Labels: Bug, [Pri] High, [Feature] Customizer, Triaged
