### ISSUE TITLE
Ads: Incorrect link for "view earnings"

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#22699] opened 2018-02-22 12:08 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/traffic/{site-url}
2. Click the "View your earnings" link

#### What I expected
To be view my earnings.

#### What happened instead
1. Taken instead to: https://wordpress.com/stats/day/{site-url}
2. Was also half-way down the page

**Comment by rachelmcr** [comment] 2018-02-23 11:01
I couldn't reproduce this issue with the steps above. When I click the "View your earnings" link I'm taken to https://wordpress.com/ads/earnings/{site-url} as expected, and I see my earnings there.

I checked with two Jetpack sites on the Premium plan, one with ads set up with existing earnings and one where I had just enabled ads for the first time. It worked as expected both times.

**Comment by beaulebens** [comment] 2018-02-23 17:34
I have a feeling this is related to a brand new site, and data not syncing yet perhaps? @richardmuscat can you confirm was this a brand new site, or a site that you had just upgraded to a plan?

If not, if no one else can reproduce we might close.

**Comment by tyxla** [comment] 2018-03-07 14:20
I am able to reproduce this - it's not really about the link itself, but more about visiting `https://wordpress.com/ads/earnings/:site` before the site has loaded. 

Steps to repro:
* Clean your Redux store.
* Go to `https://wordpress.com/ads/earnings/:site` where `:site` is a Jetpack site.
* You'll be redirected to `/stats`.

This is a Calypso issue - we need to add a little different treatment to the ads earnings page, so it will wait for the site to load, if it hasn't loaded yet.

So, grabbing this one, unless you object @lezama 😉

**Comment by tyxla** [comment] 2018-03-07 15:20
Addressed by #23079.

**Closed** 2018-03-13 15:27 UTC
Labels: Ads, FixTheFlows, Jetpack, [Pri] High, [Status] In Progress, [Type] Bug
