### ISSUE TITLE
Calypso (Simple Sites) - Latest Posts Block Options Not Saving

### ISSUE THREAD

**Issue by scosgro** [Automattic/wp-calypso#29999] opened 2019-01-08 20:04 UTC
#### Steps to reproduce
1. Starting at URL: Any WordPress.com Simple Site
2. Site must have multiple published posts, with posts added to different categories
3. Insert a Latest Posts block, and designate a category under Block Options
4. Change the Order By as well.
5. Publish the Post
6. The published post will not follow those post settings, and display all posts by default.
7. Refresh the editor.
8. The editor reverts back to default settings.

#### What I expected
1. Latest Post Settings to stick when saving/updating/publishing a page. 

#### What happened instead
1. The options revert back to default after publishing.

#### Browser / OS version
All.

#### Screenshot / Video
.gif showing workflow and issue, here: https://cloudup.com/cS49ctg65Hb

#### Context / Source

We'd also love to know how you found the bug: #manual-testing #user-report

**Comment by gwwar** [comment] 2019-01-08 21:55
May be related to https://github.com/Automattic/wp-calypso/issues/27963

**Comment by gwwar** [comment] 2019-01-08 22:03
We'll close this out as a duplicate of https://github.com/Automattic/wp-calypso/issues/27963

**Closed by gwwar** 2019-01-08 22:03 UTC
Labels: [Goal] Gutenberg, [Type] Bug
