### ISSUE TITLE
Plans view when switching between a wpcom and a jetpack site broken

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#2787] opened 2016-01-26 15:56 UTC
How to reproduce:
- View the plans page for a Jetpack site, eg: wp.com/plans/{your-jetpack-site}
- Use the site switcher to switch to a wpcom site
- The page will not update itself and neither will the URL in the address bar
- Also broken going the other way, ie: viewing plans for a wpcom site and switching to a Jetpack site

The flow works fine when switching from a wpcom site to another wpcom site or from a jetpack site to another jetpack site.

Using Chrome on production.

@johnHackworth thinks its related to: 
https://github.com/Automattic/wp-calypso/commit/01c54b4c

**Comment by designsimply** [comment] 2016-01-26 21:00
@richardmuscat, I think this is a duplicate of https://github.com/Automattic/wp-calypso/issues/2610. Agree?

**Comment by richardmuscat** [comment] 2016-01-27 11:26
@designsimply, yup looks like the same thing.

**Comment by scruffian** [comment] 2016-01-28 09:59
Closing in favour of #2610

**Closed by scruffian** 2016-01-28 09:59 UTC
Labels: .org Plans, Plans, [Type] Bug
