### ISSUE TITLE
Task: Ensure we refresh the WPCOM plan data after completing a migration

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#91187] opened 2024-05-28 09:09 UTC
### Details

We're receiving a number of reports that sites are not showing the correct plan after completing an inbound migration. We should ensure that we refresh the plan information as part of our post-migration cleanup.

We can do that using the following code:
```php
$plan_updated = \Automattic\Jetpack\CurrentPlan::refresh_from_wpcom();
```

We may also need to verify that we have the correct site ID locally before we can run the above successfully:
```php
$site_id = \Automattic\Jetpack\Connection\Manager::get_site_id();
if ( is_wp_error( $site_id ) ) {
	// Log a failure and return early
	return;
}
```

Note that because we are also (re)connecting Jetpack during the post-migration cleanup, we need to wait for that cleanup to wrap up before we can run this code.

### Checklist

- [ ] After an inbound Migrate Guru migration, we should show the correct plan on the Atomic site

**Comment by zdenys** [comment] 2024-05-28 09:27
For context, it was mentioned here p9Jlb4-bVO-p2#comment-11539

**Comment by nelsonec87** [comment] 2024-06-17 14:53
Related diff D151712-code

**Comment by markbiek** [comment] 2024-06-19 12:21
I wanted to note that I spent a bunch of time testing yesterday and still haven't been able to reproduce this. 🤔

**Comment by mgozdis** [comment] 2024-07-02 14:08
On dotcom sites, after a fresh Jetpack connection, typically the correct plan will show if going to `Jetpack > Settings` and then refreshing the Dashboard or going to any other page. 

I'm not sure what going to settings does exactly, but it may test credentials. Accessing RWDB, which triggers testing credentials, also typically solves the issue with the wrong plan showing on dotcom sites.

**Comment by markbiek** [comment] 2024-07-02 14:14
> On dotcom sites, after a fresh Jetpack connection, typically the correct plan will show if going to `Jetpack > Settings` and then refreshing the Dashboard or going to any other page.
> 
> I'm not sure what going to settings does exactly, but it may test credentials. Accessing RWDB, which triggers testing credentials, also typically solves the issue with the wrong plan showing on dotcom sites.

Thanks for that context!

We have an async job that runs after migration to do various types of cleanup. We can investigate if maybe we can mimic the above process as part of that.

**Comment by andres-blanco** [comment] 2024-12-20 18:47
Closing this issue since there haven't been reports in half a year and the underlying process changed a lot.

**Closed as not planned by andres-blanco** 2024-12-20 18:47 UTC
Labels: Task, Customer report [LEGACY], [Feature] Site Migration
