### ISSUE TITLE
Popover: Light font weight and aliased in Firefox

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/wp-calypso#7510] opened 2016-08-16 23:36 UTC
Followup to #7217 I think?

On Windows 10 using Firefox Developer Edition 50.0a2 (2016-08-15), the font weight is very lightweight and aliased in the new popovers:

![stats_ _viper007bond com_ _wordpress com_-_firefox_2016-08-16_16-30-05](https://cloud.githubusercontent.com/assets/406254/17719347/c336dcdc-63ce-11e6-866a-2eef4ab3dd39.png)

It's looks a lot better in Chrome:

![stats_ _viper007bond com_ _wordpress com_-_google__2016-08-16_16-33-40](https://cloud.githubusercontent.com/assets/406254/17719416/35208884-63cf-11e6-97b5-c7794de33d8a.png)

**Comment by hoverduck** [comment] 2016-12-12 16:14
#bug-scrub

Confirmed that the fonts appear differently on Firefox and Chrome, both on Windows and Mac.  Likely a similar problem to #598

Marking as low priority because it only affects one browser, and doesn't interfere with the use of the site.

**Comment by Viper007Bond** [comment] 2018-01-12 01:38
Still an issue in Firefox 58.0b15.

**Comment by worldomonation** [comment] 2021-01-29 23:12
Hi! I am triaging older issues as part of Quality Squad's efforts to reduce issues.

I checked using Firefox 86.0a1 on Windows 10 and it looks like this:

![image](https://user-images.githubusercontent.com/6549265/106336634-33208700-6244-11eb-9ce6-8472d902ee44.png)

It looks like the text is now rendering similar to how Chrome rendered in the original post. Would it be acceptable to close this issue with the appropriate label?

**Closed** 2021-02-01 19:12 UTC
Labels: Components, [Closed] Not Reproducible, [Type] Bug
