### ISSUE TITLE
Patterns - Extract patterns from demo sites and themes into the Dotcom pattern library

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/wp-calypso#76338] opened 2023-04-27 07:35 UTC
## What

Extract patterns from demo sites and themes into the Dotcom pattern library.

## Why

Because we need them all in the Dotcom library.

## How

Let's do it manually for now and learn how the process can be automated.

**Comment by taipeicoder** [comment] 2023-06-28 02:46
Closing as it's a duplicate of https://github.com/Automattic/wp-calypso/issues/77127

**Closed as completed by taipeicoder** 2023-06-28 02:46 UTC
