### ISSUE TITLE
Template title changes on page refresh

### ISSUE THREAD

**Issue by kerrynicl** [Automattic/wp-calypso#85251] opened 2023-12-13 21:38 UTC
### Quick summary

user is editing the “Product Catalog” theme template - If you access that template from Appearance -> Editor -> Templates, it displays the name of the template in the command bar as Product Catalog
![Markup 2023-12-06 at 08 37 54](https://github.com/Automattic/wp-calypso/assets/83325600/f171f990-ff05-44fe-9af5-8fcc3222e083)

However if you just refresh the page, it changes to: archive-product and the user does not like this.
![Markup 2023-12-06 at 08 38 30](https://github.com/Automattic/wp-calypso/assets/83325600/3232c97c-1967-4f8f-a942-d43d0f426a53)

I noticed the “Single Product” template does the same as well

### Steps to reproduce

access that template from Appearance -> Editor -> Template> Product Catalog > Edit
Refresh page

### What you expected to happen

Template title to remain Product Catalog

### What actually happened

It changes to archive-product

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by rickmgithub** [comment] 2023-12-21 06:26
## 📌 REPRODUCTION RESULTS ##
- Tested on Atomic – Could Not Replicate 

## 📌 ACTIONS ##
Triaged 
- Closed as could not replicate (please reopen if the issue reoccurs) 

##Message to author##
Thanks so much for the report @kerrynicl I couldn't replicate the issue. Was this with a particular theme perhaps? Feel free to reopen if you can still replicate.

**Closed as completed by rickmgithub** 2023-12-21 06:26 UTC
Labels: Bug, Triaged, [Feature] Full Site Editor, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience

**Comment by Robertght** [comment] 2024-01-29 06:51
The user came back for an update. I've started investigating and it looks like they deactivated and deleted Gutenberg.

With Gutenberg deactivated, I was able to replicate it, but I don't think it's a relevant case.
