### ISSUE TITLE
Editor: padding is momentarily lost on switch from HTML to Visual

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#1805] opened 2015-12-18 14:32 UTC
Steps to reproduce:
- Start a new post and enter some text
- Switch to HTML mode
- Switch back to visual
- Observe that the top of the content is briefly flush with the top of the content area, then jumps down
- Repeat the above with the kitchen sink open
- Observe that the top of the content is briefly underneath the toolbar, then jumps down

Video: https://cloudup.com/cN5HxluXN5p

**Comment by youknowriad** [comment] 2016-10-04 08:48
This seems already fixed for me or I'm not able to reproduce.

**Comment by nitrajka** [comment] 2017-07-13 12:30
Agree with @youknowriad. Whoever can close this issue, do it, please.

**Closed** 2017-07-13 12:43 UTC
Labels: Editor, [Pri] Normal, [Type] Bug
