### ISSUE TITLE
Premium Content: Atomic content is sometimes only available after visiting WP Admin.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#46126] opened 2020-10-02 17:42 UTC
Reported by @pauljacobson in pbMlHh-H2-p2:

Premium Content blocks on Atomic sites can sometimes have their subscriber content be inaccessible to the site owner. If the user visits WP Admin, the block's content will then be available.

This may be specific to the original user, as it is not an issue across all Atomic sites.

**Comment by ericamQA** [comment] 2021-04-23 18:35
Unable to reproduce on multiple atomic test sites, though OG report mentioned it's not consistent across all atomic sites. If we get more reports, we can reopen and gather more info to troubleshoot with. Closing for now.

**Closed** 2021-04-23 18:57 UTC
Labels: [Closed] Not Reproducible
