### ISSUE TITLE
Checkout: First-year promotional discounts are shown as upgrade credit

### ISSUE THREAD

**Issue by aneeshd16** [Automattic/wp-calypso#83956] opened 2023-11-07 08:54 UTC
### Quick summary

When creating a new site with a plan along with a first-year promotional discount, the discount is incorrectly labelled as "Upgrade Credits". 

<img width="1241" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5436027/4677a528-27f8-48f7-bc43-c0cc46509cce">

### Steps to reproduce

1. Switch to a currency that has a first year promotional discount. (326bf-pb)
1. Go to https://wordpress.com/start
2. On the plans page, select any paid plan and proceed to checkout.

### What you expected to happen

The discount should be labelled as "Discount for the first year". I found an old screenshot: 
![image](https://github.com/Automattic/wp-calypso/assets/5436027/1dcc3728-8a5d-4c70-af12-84c95420f65d)

### What actually happened

The discount is shown as "Upgrade Credits".

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Not 100% sure, but I think the bug originated from this PR: https://github.com/Automattic/wp-calypso/pull/77720

**Comment by sirbrillig** [comment] 2023-11-15 16:20
I believe that when https://github.com/Automattic/wp-calypso/pull/77720 was merged, there was no easy way to determine if a discount was caused by an upgrade credit or not, and so the code just assumes that all price differences are due to an upgrade credit.

Since D124660-code and some associated changes, we now have [a list of cost overrides](https://github.com/Automattic/wp-calypso/blob/a7c2207d0929c98991013206153a6277e747a6a1/packages/shopping-cart/src/types.ts#L444) on each shopping cart item, each of which has a code to identify its source. Upgrade credits should always be listed in this array with the code `recent-plan-proration`, along with the price change details, so it should now be possible to refactor [the upgrade credit calculation](https://github.com/Automattic/wp-calypso/blob/a7c2207d0929c98991013206153a6277e747a6a1/packages/wpcom-checkout/src/checkout-line-items.tsx#L845) to use accurate information instead.

**Comment by rickmgithub** [comment] 2023-11-18 09:25
📌 REPRODUCTION RESULTS
Can replicate on different plans from both /start and within an existing free plan site by selecting "upgrade" option

**Comment by sirbrillig** [comment] 2024-01-15 16:40
This should be fixed by https://github.com/Automattic/wp-calypso/pull/86415

**Closed as completed** 2024-01-15 16:53 UTC
Labels: Bug, [Pri] High, Needs triage, [Status] Priority Review Triggered
