### ISSUE TITLE
Marketplace: Visual search field bug in Safari

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#67614] opened 2022-09-09 19:17 UTC
From: pdh6GB-1Vu-p2 there's a visual bug in the search field in Safari.

![safari search](https://user-images.githubusercontent.com/1689238/189426354-1a9ffc68-306c-4e90-9b02-04880ed5207a.png)

Acceptance criteria:
- [ ] You've tried to reproduce this issue in desktop and mobile Safari.
- [ ] If replicable, a fix for the issue.

**Comment by allilevine** [comment] 2022-09-09 19:19
@pablohoneyhoney Can you share any additional browser details about this one? I'm not seeing it in Safari 15.6.1 desktop.

**Comment by cpapazoglou** [comment] 2022-11-21 13:57
Closing this as I can't reproduce either. In case we have more details we can reopen it.

**Closed as completed by cpapazoglou** 2022-11-21 13:57 UTC
Labels: Bug, Marketplace
