### ISSUE TITLE
Editor: empty tooltips displaying on editor (Firefox)

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#5101] opened 2016-04-28 23:12 UTC
![](https://cloudup.com/cUtMaPhtZtV+)

#### Steps to reproduce
I'm not able to reproduce consistently, but I saw what looks like an empty tool tip over the scheduler upon returning to editor after my computer had been asleep. I later saw it when loading notifications over editor in the region atop these guys: https://cloudup.com/cXMlnUEQY-q but wasn't quick enough to grab a screenshot. These phantom tooltips seem to show while a component is in a loading state and disappear after a couple seconds.

**Comment by designsimply** [comment] 2016-04-29 17:05
Tested and confirmed. I can also see something similar happening in the stats insights calendar. To reproduce the bug, try swooshing the mouse over two active buttons in a row really fast while a page is still loading. Seems more prevalent in Firefox to me than other browsers. 

<strong>Video:</strong> [47s](https://cloudup.com/cOsGYFLC2O1)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/10035 using Firefox 46.0 on Mac OS X 10.11.4</sup>

**Comment by lancewillett** [comment] 2016-04-29 17:06
Thanks for your notes, @designsimply.

Question for you @meremagee: does it happen when you hover your mouse over quickly? Could be a "hover intent" behavior where there's not enough delay on the interaction.

Or, are they just present on the screen with no mouse movement at all?

**Comment by lancewillett** [comment] 2016-05-02 21:42
I saw this today when using wpcalypso with Firefox stable on OS X 10.11.4, on a test site `lancetest35.wordpress.com/`

Steps to repeat:
1. Start a blog post or edit a draft.
2. Click publish.
3. Just after you click the publish button move the mouse right (over and away from the publish button).
4. You'll see the tooltip appear. I think this corresponded with a console error `NetworkError: A network error occurred.`
5. It disappears once the post publishes.

I wasn't able to capture it in a screencast, but will keep trying. This is where I ended up just after:

<img width="1763" alt="screen shot 2016-05-02 at 2 39 18 pm" src="https://cloud.githubusercontent.com/assets/66797/14968866/07ea3f4e-1074-11e6-98d6-ce9561595568.png">

**Comment by lancewillett** [comment] 2016-05-02 21:44
I tried the same steps again, wasn't able to reproduce. But did see the same network error.

![tooltips-firefox](https://cloud.githubusercontent.com/assets/66797/14968913/4be290e8-1074-11e6-8f11-740582b2406e.gif)

**Comment by lancewillett** [comment] 2016-05-02 21:45
Got it! It has to be a previously edited post, saved as a draft.

![tooltips-firefox-2](https://cloud.githubusercontent.com/assets/66797/14968957/900cfbdc-1074-11e6-9ce9-c76af62401b8.gif)

**Comment by meremagee** [comment] 2016-05-10 00:49
Just got one of these lil things to persist!

![](https://cloudup.com/c-4r9HTDF6V+)

**Comment by lancewillett** [comment] 2016-05-10 16:13
Without even knowing how it works code-wise, my guess is the tip is empty of text and this looks broken — data is missing in the view.

**Comment by thehenrybyrd** [comment] 2016-05-14 15:51
Seeing the same thing in stats/day view. Very similar experience to @designsimply's video above.

Steps to reproduce:
1. Load https://wordpress.com/stats/day/
2. Run the mouse wildly from one end of the days to another.
3. Try it again, a bit more intentionally, but still quickly.

I didn't see any console errors occur during this process.

Gif: https://cloudup.com/cUcNsGGokc7
Seen at https://wordpress.com/stats/day/ahbusinesstest.wordpress.com using Chrome 50.0.2661.94 on Mac OS X 10.10.5

**Comment by thehenrybyrd** [comment] 2016-05-17 12:29
Here's a user reporting this in Edge and Chrome: 2663631-t
Lots of screenshots, and user is describing the same experience:
"when I move the mouse across the graph it seems the info box at the bottom sticks"

**Comment by travisw** [comment] 2016-05-17 17:08
I'm also able to reproduce this in the stats/days section and it is a very similar element on the page that persists. Just a couple of different classes compared to @meremagee screenshot above.
I'm using Chrome Version 50.0.2661.102 (64-bit)

<img width="784" alt="screen shot 2016-05-17 at 9 58 22 am" src="https://cloud.githubusercontent.com/assets/690843/15331467/384ef032-1c16-11e6-95de-af28fc02d35a.png">

<img width="598" alt="screen shot 2016-05-17 at 9 58 48 am" src="https://cloud.githubusercontent.com/assets/690843/15331468/38625a64-1c16-11e6-8d46-d7a3f2723ce6.png">

**Comment by designsimply** [comment] 2016-05-19 20:13
Spotted another case of a phantom tooltip on the "Edit Post URL" icon, just to the left of the title field in the Editor, see [23s](https://cloudup.com/cLILYx-iHRI).

**Comment by juliaamosova** [comment] 2016-05-29 15:38
User in [Ticket #2663631](https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=2663631) already mentioned above sent more screenshots in order to help investigate the issue further: 

![screenshot_2](https://cloud.githubusercontent.com/assets/19143190/15634443/ba15ce40-2591-11e6-99a8-57b21634fcb8.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/19143190/15634444/c0ff5b0e-2591-11e6-9aa4-ff979448b7e7.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/19143190/15634446/c55574c2-2591-11e6-9a7f-1bc8a0a7efec.png)

![screenshot_5](https://cloud.githubusercontent.com/assets/19143190/15634448/c89d788c-2591-11e6-8515-8ae4c261bbed.png)

**Comment by juliaamosova** [comment] 2016-06-03 03:34
More screenshots from user in 2663631-t already mentioned above:

![4ba56cf26dc64661893bde2a56a41601](https://cloud.githubusercontent.com/assets/19143190/15767925/7b2f5138-291a-11e6-98a1-4382da0e4093.png)

![screenshot_7](https://cloud.githubusercontent.com/assets/19143190/15767929/8721dbbe-291a-11e6-9a66-a04dbf2bcda4.png)

**Comment by meremagee** [comment] 2016-06-03 18:46
Had another visitor in the editor today: https://cloudup.com/c7cqjgYonqE

**Comment by dcoleonline** [comment] 2016-06-21 18:56
More screenshots from user in 2663631-t already mentioned above:

![screenshot_2](https://cloud.githubusercontent.com/assets/3505172/16242428/f43687da-37b7-11e6-83c1-76679f5b23a5.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/3505172/16242429/f43a1882-37b7-11e6-9369-e022b9961140.png)

**Comment by dcoleonline** [comment] 2016-06-22 14:12
Another report in 404123-chat from a different user on Windows Vista using FIrefox 47.
They weren't able to make a screenshot, so I asked them to use a different browser for now.

**Comment by rralian** [comment] 2016-07-14 23:12
I was able to reproduce this pretty easily in firefox by loading a stats page (viewing days) and then just moving my mouse quickly back and forth over the different days. The result I get is a ton of extra empty tooltip artifacts in the html.

![tooltip in html](https://cloudup.com/cA3FWHlGse3+)

I think the event that we are relying upon to clean up the tooltips just isn't reliably firing. It's worse in firefox, but I can get it to happen in chrome as well with some vigorous shaking of the cursor. (curse you cursor!)

![in chrome too](https://cloudup.com/c_xxPbOnZXf+)

I suspect this may be a bug/limitation of the `component-tip` [npm module](https://github.com/component/tip) that we rely upon. Maybe we need to fix it at the source, or maybe we need to write our own. I see some Automatticians have our names all over that module, so maybe one of them can check it out? @ockham @TooTallNate @retrofox

**Comment by ockham** [comment] 2016-07-15 11:48
> Maybe we need to fix it at the source, or maybe we need to write our own.

IMO ideally we'd replace it with something more React-ish (and thus e.g. SSR compatible), see #4072.

**Comment by rralian** [comment] 2016-07-22 15:24
I've added "high" priority because this seems to be a rather common bug in firefox. It was certainly very simple for me to recreate.

**Comment by gwwar** [comment] 2016-08-16 22:20
This should be fixed by #7217

**Closed by gwwar** 2016-08-16 22:20 UTC
Labels: Components, Framework, [Pri] High, [Type] Bug

**Comment by rralian** [comment] 2016-08-17 22:13
Thanks for taking this on @retrofox, was a big project, and I think this significantly improves the user experience. Nice work! 🎆

**Comment by designsimply** [comment] 2016-08-22 17:42
Tested and confirmed I can no longer reproduce the bug where phantom tooltips would show up in Firefox when you moused over various popover areas. w00t! Thanks @retrofox!
