### ISSUE TITLE
Signup: Space between sticky search bar and masterbar on mobile

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#25143] opened 2018-05-28 19:34 UTC
#### Steps to reproduce
1. Starting at URL: http://wordpress.com/start/domains/
2. Resize screen to ~960px wide or less
3. Search for a domain and scroll down until the search bar "sticks" to the top
4. Note there are a few pixels' space between the top of the search bar and the bottom of the masterbar, as seen in this screenshot:

![img_3246](https://user-images.githubusercontent.com/2124984/40627231-c363b726-628b-11e8-9951-74bfe1fc19d7.PNG)

#### What I expected

For the search bar to align flush with the masterbar when sticking.

#### What happened instead

There's a small margin between the search bar and the masterbar where the content underneath shows through. This looks a bit sloppy.

#### Browser / OS version

iPhone 7 iOS 11.3, Chrome, but it also happens whenever the screen size is less than 960px and greater than 480px.

**Comment by hermawan22** [comment] 2018-05-29 07:35
Hi @sixhours, i can reproduce this issue only on ipad / table view.

May i help to fix for this one? It will be my first contribution for calypso.
It's cause calypso have `margin-top` style for sticky panel for width less than 960px (breakpoint).

But wanna make sure, should we implement this behavior for all component that use sticky panel component, for example customize theme and some other component.

![theme](https://user-images.githubusercontent.com/6385048/40644335-7d262544-6355-11e8-9801-a5c5e2664309.png)

Thanks.

**Comment by sixhours** [comment] 2018-05-29 13:27
> May i help to fix for this one? It will be my first contribution for calypso.

Welcome! :)

> But wanna make sure, should we implement this behavior for all component that use sticky panel component, for example customize theme and some other component.

Good question. I think it looks odd in signup because the sticky search doesn't have a left or right margin with the surrounding content. In the above context (signed in, within Calypso) it's not as jarring and I probably wouldn't change it without more input from others.

**Comment by hermawan22** [comment] 2018-05-29 14:26
Got it @sixhours , do u have any suggestion what the best way to fix it?

I was thinking, to create another props `mobileMarginTop` to passing down to sticky-panel and then it will be determine either the sticky panel should have margin or not via css class `.mobile-margin-top`.

Will send my commit for it, hopefully u can more understand what i mean through my code.
Hihihi.

Thanks @sixhours :pray:

**Comment by hermawan22** [comment] 2018-05-29 14:45
Just push my new commit for it. :)

**Comment by klimeryk** [comment] 2021-02-02 11:40
Marking this as fixed - I cannot reproduce. I'm guessing the component itself was fixed in the meantime.

**Closed by klimeryk** 2021-02-02 11:40 UTC
Labels: Domains, Signup, [Type] Bug
