### ISSUE TITLE
Editor: Warn users when pasting prohibited code

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#7650] opened 2016-08-24 20:13 UTC
Currently, we prohibit users from using some [common embed codes](https://en.support.wordpress.com/code/) like flash, iframes, and any kind of JavaScript. When they copy and paste the code from a third-party service, the code is stripped leaving the user with no real idea of why the code isn't working or how to fix it. 

It would be really cool if we were able to show an alert any time we stripped out code including an explanation of why the code won't work and a link to contact support in case there's a possible workaround.

I'm not sure how feasible this would be, but I imagine it would save a good bit of frustration for users.

h/t @mattsherman from his support week (p3Ex-1tM-p2).

**Comment by designsimply** [comment] 2018-01-05 23:39
#bug-scrub #pre-gutenburg-bug-purge

Tested and confirmed using the following testing steps:

1. Go to My Sites > Blog Posts > [any post].
1. Paste in some sample JavaScript code.
1. Switch to HTML mode.
1. Check to see whether the code was stripped.
1. Re-paste in some sample JavaScript code.
1. Switch to Visual mode. 
1. Check to see whether the code was stripped.

<strong>Result:</strong> JavaScript code that is not allowed is silently stripped from a post when switching between editing modes or publishing a post.

<strong>Note:</strong> I tested this with the Gutenberg editor and found that the JavaScript sample code I used was preserved, but this is still a WordPress.com-specific issue because arbitrary JavaScript (and other) code has traditionally been disallowed for security reasons.

<strong>Sample JavaScript code used:</strong>

```
<script>
document.write(1200 + 34);
</script>
```

**Comment by davipontesblog** [comment] 2020-06-10 03:02
I am closing this as the classic editor in calypso is being deprecated in favor of the block editor. If needed, please feel free to reopen.

**Closed by davipontesblog** 2020-06-10 03:02 UTC
Labels: Editor, [Type] Enhancement
