### ISSUE TITLE
Purchases: Can't cancel and refund site Redirect

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#1175] opened 2015-12-02 09:15 UTC
I purchased a `Site Redirect` and wanted to cancel & refund it. Everything went smoothly until the last step. When I click on confirmation link it redirects from WP-Admin to `/my-upgrades` page and the following message is presented:
![screen shot 2015-12-02 at 10 09 44](https://cloud.githubusercontent.com/assets/699132/11526798/4ceb252c-98dd-11e5-9160-c425261d5c2a.png)

What's strange it worked without any hassle when I tried to reproduce using another test site.

By the way, we should change email confirmation link redirect from `/my-upgrades` to `/purchases`.

**Comment by fabianapsimoes** [comment] 2016-03-15 17:03
I'm unable to reproduce this problem, and it seems it didn't happen consistently for you as well. Since we didn't get more reports of this, I'll close this issue. Feel free to reopen if you have more information.

**Closed by fabianapsimoes** 2016-03-15 17:03 UTC
Labels: Purchases, [Type] Bug
