### ISSUE TITLE
Social Icons Block - Icons Broken Upon Addition

### ISSUE THREAD

**Issue by aamills** [Automattic/wp-calypso#47154] opened 2020-11-05 16:15 UTC
#### Steps to reproduce

1. Starting at URL: From a new page, or existing page on a site.
2. Add Social Icons Block.
3. Block appears with three circles - that are non-clickable/editable.
4. The social icons used to appear in this block to edit/add links too.
5. Now the + icon must be clicked next to them, and a social service searched for and added to the block.

Screen capture of experience:
![AddingAsocialIcon](https://user-images.githubusercontent.com/29556134/98266099-22af8780-1f47-11eb-9e88-16d65c426a20.gif)

#### What I expected
This was non-intuitive and doesn't match [the current setup guide.](https://wordpress.com/support/wordpress-editor/blocks/social-links-block/) 

Setup video from guide:
![SocialLinksAddition](https://user-images.githubusercontent.com/29556134/98265947-ec720800-1f46-11eb-8802-018b81f27b4e.gif)

#### What happened instead
The icons didn't appear upon addition of the block to the page, instead the circles where the icons look like they should be, are non-clickable and non-functional, and the + block inserter must be clicked to add a relevant social icon.

#### Context / Source

 #manual-testing, #user-report

**Comment by shaunandrews** [comment] 2020-11-05 18:09
This is the intended behavior. The placeholder state for the social icons block was updated in https://github.com/WordPress/gutenberg/pull/25941

**Comment by cathymcbride** [comment] 2020-11-05 18:45
@shaunandrews If this is the intended behavior, it seems like we should update https://wordpress.com/support/wordpress-editor/blocks/social-links-block/?

**Comment by shaunandrews** [comment] 2020-11-05 18:51
Yup, that seems like a good idea.

**Comment by cathymcbride** [comment] 2020-11-09 19:02
Docs bug: 860-gh-Automattic/en.support-docs-content
and closing this one....

**Closed by cathymcbride** 2020-11-09 19:02 UTC
Labels: Blocks, Involves Happiness, [Pri] Normal, [Type] Bug

**Comment by mkaz** [comment] 2020-11-13 16:34
Thanks for the report, additionally we are trying to address usability improvements in #26953
