### ISSUE TITLE
Translation issue on Calypso: Japanese

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#26304] opened 2018-07-25 15:24 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/me/account
2. Change the interface language to Japanese
3. Check some pages in the dashboard

#### What I expected
All the menus, the buttons and the texts in Calypso are translated to Japanese

#### What happened instead
Some menus and buttons are not translated. So, we see the mix of English and Japanese in Calypso dashboard as you can see in the screenshots below.

#### Browser / OS version
Chrome 67.0.3396.99 , Safari 10.1.1
OS X 10.12.5

#### Screenshot / Video
![screen shot on 2018-07-25 at 10_56_01](https://user-images.githubusercontent.com/32432463/43210175-629ec270-8ffc-11e8-86ec-1cfd36a46da5.png)

![screen shot on 2018-07-25 at 11 19 10](https://user-images.githubusercontent.com/32432463/43210314-bcca070a-8ffc-11e8-8586-8aa130d5b795.png)

**Comment by Agepeuve** [comment] 2018-07-26 09:24
Some Spanish accounts are also affected by this issue:

![Spanish](https://cdn-pro.dprcdn.net/files/acc_639176/lZmGMd)

I've been testing other languages, like French or Deutsch, and they are also affected on those accounts.

**Comment by rachelmcr** [comment] 2018-07-31 11:27
I checked both Japanese and Spanish with a test account and all of the translations are loading as expected for me. Could you test again and see if this is still an issue for you?

**Comment by Agepeuve** [comment] 2018-07-31 11:42
I just checked it and the issue is completely solved. It seems that some translations strings where removed by mistake during an update but the change has already been reverted :)

**Comment by rachelmcr** [comment] 2018-07-31 11:48
Thanks for confirming! Closing as resolved.

**Closed by rachelmcr** 2018-07-31 11:48 UTC
Labels: [Status] Needs Author Reply, [Type] Bug, i18n
