### ISSUE TITLE
"That method is not allowed" payment error

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/wp-calypso#20834] opened 2017-12-14 17:24 UTC
The error "That method is not allowed." appears when trying to complete a renewal payment using a card or PayPal.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Go to [Manage Purchases](https://wordpress.com/me/purchases)
3. Click through to the upgrade due for renewal
4. Click Renew Now
5. Enter card details (or attempt to pay through PayPal)
6. Click the Renew button

#### What I expected

To be able to make a successful renewal payment.

#### What happened instead

The error message "That Method is not Allowed" was displayed when trying to renew using either a card or PayPal.

I haven't been able to replicate the issue on my own sites. The payments team have confirmed there was no issue with the transaction itself and suggested it could be related to the Calypso API.

#### Browser / OS version

* Chrome for Mac
* Renewal was successful in Safari

_Awaiting more information._

#### Screenshot / Video

<img width="311" alt="not-allowed" src="https://user-images.githubusercontent.com/11627765/34005393-a206135a-e0f2-11e7-83a2-6d287cc6dd99.png">

#### Context / Source
#user-report

831853-zen

I’ve found several recent instances of similar issues also affecting renewals:

815396-zen
769074-zen
776145-zen

**Comment by designsimply** [comment] 2017-12-19 17:43
I was unable to reproduce the problem using the steps provided. I used a personal Visa card to make a renewal payment as test user user803. Tested with Firefox 57.0.1 on Mac OS X 10.13.1.

![screen shot 2017-12-19 at tue dec 19 10 40 05 am](https://user-images.githubusercontent.com/1119271/34170777-6c712eae-e4a9-11e7-82c2-61fd4a9ea742.png)
<sup>Seen at https://wordpress.com/me/purchases/madefortesting426.wordpress.com/9424791 using Firefox 57.0.1 on Mac OS X 10.13.1.</sup>

**Comment by designsimply** [comment] 2017-12-19 18:02
If you come across any new cases for this issue, it would be helpful to try to find a trend in what types of transactions are experiencing the problem. Answers to the following things may help:

* Was the item up for renewal transferred to you from another user in the past?
* What OS/browser version are you using?
* What payment type did you use (i.e. Visa, PayPal, etc.)?
* What country are you making the payment from?

**Comment by gemmagarner** [comment] 2017-12-21 14:32
Thanks @designsimply, will do!

**Comment by KokkieH** [comment] 2018-01-10 15:27
Another case in 887956-zen. Still waiting on exact browser info from the user, but the issue sounds familiar so I did some digging. 

Found pNPgK-34I-p2 and pNPgK-2CS-p2 referencing this error. It seems using an AMEX card is a common denominator - also what this user has.

Can't find the report I was thinking of, though, but I remember in that case deleting saved payment info on the Billing History page allowed new payment info to be added via the Purchases page, so I've suggested that to the user.

**Comment by rralian** [comment] 2018-01-31 21:08
Looking through some error logs, we think the issue is that the Jetpack site was unavailable when the payment was attempted. Adding Jetpack tag, to see if this is a known issue.

**Comment by kwight** [comment] 2018-03-07 18:11
Digging through the various instances in previous comments, the only thing in common really is the error.
* It can happen regardless of card or PayPal (831853-zen),
* for both Jetpack and WordPress.com sites (815396-zen),
* it can also happen when people are just trying to update their card (769074-zen),
* multiple browsers have been used to succeed (Safari, IE, and presumably Chrome?),
* and a manual payment seems to always work fine.

**Comment by rachelmcr** [comment] 2018-08-31 10:30
I noticed that the error message "That method is not allowed" comes from a 405 error. The pattern I'm seeing in these reports is some sign (not always the same) that there's an authentication issue.

Most of these reports also come as replies to the subscription renewal email that has a "Keep my subscription" link. Could there be an issue with users who aren't fully authenticated when they try to enter their payment details, especially after using that link? That would also explain why switching browsers works, regardless of which browser it is, since presumably the user would log in again from scratch there.

From 815396-zen:

> When I hit the "keep my subscription" key in this email it takes me to the same update page but it is flashing and does not load properly.

From 887956-zen:

> And when I click the ‘keep my subscription” in the original email I get a blank never loaded screen.

From 769074-zen:

> I just tried to enter the credit card information via the link you provided below and once I clicked the Save Card button, I received the following message: An active access token must be used to query information about the current user.

**Comment by adelineyaw** [comment] 2019-01-24 02:52
User reported issue via 1738200-zen

**Comment by lakellie** [comment] 2019-01-24 21:45
Another user experienced this in #1746294-zen and it was also via the subscription renewal email

**Comment by lancewillett** [comment] 2019-04-09 02:37
CC @rralian if you don't mind investigating this one again.

**Comment by lakellie** [comment] 2019-11-06 20:50
Another instance in 2471735-zen

**Comment by dkmyta** [comment] 2019-11-22 20:48
Neutron uses Autopay P2 as a medium for reporting and triage of issues related to payments and billing. Here's a guide which contains information on this: https://fieldguide.automattic.com/reporting-issues-related-to-billing-or-payments/

Issue logged on Autopay, please add any additional instances to the post comments: https://autopay.wordpress.com/2019/11/22/that-method-is-not-allowed-payment-error/

Associated Trello card for tracking: https://trello.com/c/zRUaivXy/218-that-method-is-not-allowed-payment-error

**Closed by dkmyta** 2019-11-22 20:48 UTC
Labels: Checkout, Jetpack, Payment Methods, [Pri] High, [Type] Bug
