### ISSUE TITLE
Gutenberg: Cannot manage Sharing settings

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/wp-calypso#28554] opened 2018-11-14 19:16 UTC
#### Steps to reproduce
1. Starting at URL: wordpress.com
2. Start a new post in Gutenberg on a simple site
3. Note the Sharing options are missing to control where the post is shared to, customizing the shared message, or enabling/disabling sharing buttons and likes

#### What I expected
To be able to manage sharing settings in Gutenberg

#### What happened instead
They are not present

#### Browser / OS version
OS X 10, Chrome 70.0.3538.77

#### Screenshot / Video
Gutenberg

<img width="1405" alt="screen shot 2018-11-14 at 2 06 55 pm" src="https://user-images.githubusercontent.com/1900444/48506415-65866b00-e817-11e8-9ad7-fdff4407aa14.png">

Classic 

<img width="1381" alt="screen shot 2018-11-14 at 2 08 40 pm" src="https://user-images.githubusercontent.com/1900444/48506485-8058df80-e817-11e8-862b-41340645610a.png">

#### Context / Source
#manual-testing, #user-report

**Comment by KokkieH** [comment] 2018-11-15 04:10
Appears to be a duplicate of #28528

**Closed** 2018-11-15 13:48 UTC
Labels: [Goal] Gutenberg, [Pri] Normal, [Type] Bug
