### ISSUE TITLE
Post and page titles: Ampersand character displayed as &amp;

### ISSUE THREAD

**Issue by mikeicode** [Automattic/wp-calypso#45355] opened 2020-09-02 13:05 UTC
#### Steps to reproduce

1. Starting at URL: Simple Site
2. Add new page, add an ampersand character to the title
3. Save Page 
4. Refresh screen

#### What I expected

Character should be `&`

![https://d.pr/i/3wgRX6](https://d.pr/i/3wgRX6+)

#### What happened instead

Character is `&amp;`

![https://d.pr/i/CiIblo](https://d.pr/i/CiIblo+)

#### Context / Source

Same issue on multiple themes. This issue is only on Simple Sites. The correct image above is from an AT site using Alves, the issue image is a Simple Site using Alves.

18913905-hc

**Comment by cathymcbride** [comment] 2020-09-02 18:20
This is a duplicate of https://github.com/WordPress/gutenberg/issues/20490. Closing this in favor of the root issue.

**Closed by cathymcbride** 2020-09-02 18:20 UTC
Labels: Involves Happiness, [Type] Bug
