### ISSUE TITLE
Empty popup upon clicking "Manage sites" on a plugin page

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#81713] opened 2023-09-14 06:05 UTC
### Quick summary

On a plugin page like https://wordpress.com/plugins/tinymce-advanced, clicking on `Manage sites` button shows a popup without any site.

### Steps to reproduce

- Start at a plugin page like https://wordpress.com/plugins/tinymce-advanced
- Click on `Manage sites`

### What you expected to happen

A list of sites appear, and potentially show a button to install the plugin on that site, or upgrade site to a plan that supports it? (like in the image below, which is when I visit the same plugin page but for a specific site -- see the site address in the URL)

<img width="1263" alt="image" src="https://github.com/Automattic/wp-calypso/assets/18581859/39f941d5-060b-4089-8b7d-a4156d6f2094">

### What actually happened

An empty popup appears.

<img width="1120" alt="image" src="https://github.com/Automattic/wp-calypso/assets/18581859/373a55c5-995d-487b-9645-4176be64af3a">

<img width="1156" alt="image" src="https://github.com/Automattic/wp-calypso/assets/18581859/3e7ec190-ec88-4024-80bb-4f004c5f1aaa">

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by karenroldan** [comment] 2023-09-14 08:59
📌 REPRODUCTION RESULTS
- Tested on an account without business plans – **Replicated**
- Tested on an account with business plans – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO

**The issue can be replicated when you use an account without sites on a Business plan.** Since you cannot install plugins when using a Premium plan and below, there are no sites to list. 

However, there should still be a better way to communicate this instead of displaying an empty popup.  

**Site 1 - AT - Business** 

**NOTE:** I noticed that one of my sites that is on a Business plan is not listed here. 🤔 

![CT9EnB.png](https://github.com/Automattic/wp-calypso/assets/67279475/cc41700b-7738-4400-bf87-18faa6e1d15e)


**Site 2 - The highest plan is Premium only**

![ePOTQ4.png](https://github.com/Automattic/wp-calypso/assets/67279475/963405a5-ccd8-4cd7-bb7a-1f7e237ec62c)

📌 ACTIONS
- Lowered the priority to `Normal`.
- Assigned to @Automattic/bespin 

📌 Message to Author
Hi @arunsathiya thanks for reporting the issue! Your idea of giving a nudge to upgrade the site to a plan that supports sounds like a good idea also!

**Comment by WBerredo** [comment] 2023-10-26 17:32
This task was split in:

- [ ] #83535
- [ ] #83536

**Comment by cpapazoglou** [comment] 2024-08-26 10:07
This was fixed a long ago 🤦

**Closed as completed by cpapazoglou** 2024-08-26 10:07 UTC
Labels: Bug, [Pri] Normal, [Feature] Plugins, Triaged, [Product] WordPress.com, [Feature Group] Other Infrastructure
