### ISSUE TITLE
[Bug]: Dashboard button doesn't work in FSE Beta

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#60490] opened 2022-01-26 13:41 UTC
### Quick summary

There is an edge case in Site Editor that breaks the functionality of the Dashboard button.

### Steps to reproduce

1. Use a test site with FSE enabled.
2. Open the Site Editor.
3. Click on the Template dropdown in the top toolbar.
4. Click on "Browse All Templates".
5. Click on Dashboard menu item.

### What you expected to happen

The app navigates back to the My Home screen.

### What actually happened

Broken page with "[URL] refused to connect." error message.

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by dpasque** [comment] 2022-01-26 15:07
This is a duplicate of #60110, closing in favor of that one!

**Closed as completed by dpasque** 2022-01-26 15:07 UTC
Labels: Bug, [Pri] High, [Goal] Full Site Editing
