### ISSUE TITLE
Sharing: Email and Print sharing buttons not working, only open project page in new tab

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#24836] opened 2018-05-13 05:59 UTC
#### Steps to reproduce

1. Starting at URL: https://bakerealestate.com/portfolio/just-sold-16263-linden-court-northville-remodeled-5-bedroom-4-1-bath-3737-sqft-cape-cod-on-cul-de-sac-with-finished-walkout-lower-level-closed-at-777000/
2. Click on the Email or Print buttons to share by email, or print (respectively), here:

![](http://cld.wthms.co/PpgWNn+)

#### What I expected

When clicking on the email icon, my email app should open so I can email the project page (Portfolio post type).

When clicking on the print icon, a print dialogue should open enabling me to print the project page.

#### What happened instead

Clicking on either button opens the same project page in a new browser tab.

#### Browser / OS version

Firefox Developer Edition 61.0b4, and Chrome 66.0.3359.170
macOS 10.13.4

#### Context / Source

1151733-zen

A user reported this issue. I confirmed this in my browsers.

**Comment by ChrissiePollock** [comment] 2018-05-13 22:44
Update that the most recent post has the problem, too.

**Comment by topher1kenobe** [comment] 2018-05-15 18:01
Email share links that work end this way: ```/?share=email&amp;nb=1```  Share links that don't work end this way: ```?share=email```

**Comment by topher1kenobe** [comment] 2018-05-15 18:29
Print buttons are exactly the same on pages where they work and where they don't.

**Comment by topher1kenobe** [comment] 2018-05-15 19:09
The site owner just discovered that the issue only exists on the latest post. When a newer one is posted, it has the problem and all previous posts are fine.

**Comment by designsimply** [comment] 2018-05-16 23:46
I tested the email and print sharing buttons at https://bakerealestate.com/portfolio/just-sold-16263-linden-court-northville-remodeled-5-bedroom-4-1-bath-3737-sqft-cape-cod-on-cul-de-sac-with-finished-walkout-lower-level-closed-at-777000/ using Chrome 66.0.3359.117 on macOS 10.13.4 just now and can confirm they are both working as expected. 

I also tested and confirmed that both the print and email sharing buttons are working normally on a WordPress.com test site (design5279wordpress.com).

Since there is an earlier comment saying it's working now and because I couldn't reproduce the problem in my own testing, I'm closing this issue. Thank you for the report @pauljacobson. 

Thank you for the updates @topher1kenobe !!! 🙂 It's nice to see you 'round here.

**Closed by designsimply** 2018-05-16 23:46 UTC
Labels: Sharing, [Type] Bug

**Comment by designsimply** [comment] 2018-05-18 18:18
I re-tested this by creating a new blog post on a WP.com Simple site (design5279.wordpress.com) and the email and print sharing buttons worked as expected.

I also tested with a WP.com Business Plan site with plugins installed (madefortesting347.blog) and the email and print sharing buttons worked as expected there as well.

**Comment by designsimply** [comment] 2018-05-18 18:20
I tested the latest post mentioned and confirmed the email sharing button at https://bakerealestate.com/portfolio/just-sold-413-adams-street-in-the-city-of-plymouth-4-bedroom-2-5-bath-2392-sqft-craftsman-cottage/ is linked to https://bakerealestate.com/portfolio/just-sold-413-adams-street-in-the-city-of-plymouth-4-bedroom-2-5-bath-2392-sqft-craftsman-cottage/?share=email

I also re-tested the email sharing button at https://bakerealestate.com/portfolio/just-sold-16263-linden-court-northville-remodeled-5-bedroom-4-1-bath-3737-sqft-cape-cod-on-cul-de-sac-with-finished-walkout-lower-level-closed-at-777000/ is linked to https://bakerealestate.com/portfolio/just-sold-16263-linden-court-northville-remodeled-5-bedroom-4-1-bath-3737-sqft-cape-cod-on-cul-de-sac-with-finished-walkout-lower-level-closed-at-777000/?share=email&nb=1

@zdenys can you please ask the user exactly what their steps for publishing are in case there is something different they are doing that we're not thinking of for testing? Can you also please make a note of what plugins are installed on the site and ask on `+atomicrequests` what the next best steps for troubleshooting this issue are if the problem is not happening on WP.com simple site? I suspect the answer will be to test without third-party plugins enabled but would like a 2nd opinion. 😍
