### ISSUE TITLE
oEmbedded WordPress posts on WordPress.com obscure text

### ISSUE THREAD

**Issue by gamebits** [Automattic/wp-calypso#33884] opened 2019-06-12 20:05 UTC
#### Steps to reproduce
1. Paste a WordPress link on its own line in the editor of a WordPress.com site.
2. Paste a large paragraph of text next (in its own block if using Gutenberg).
3. Preview or publish the post.
4. The embedded preview of the WordPress.com post will obscure the text beneath it.

I am unable to reproduce this issue on WordPress sites hosted elsewhere than WordPress.com, or with oEmbed of other kinds of content (YouTube, Giphy).

#### What I expected

The oEmbed to push the text down / the text to wrap around the oEmbed.

#### What happened instead

The oEmbed and the subsequent paragraph start on the same line, overlapping each other, with the embedded content on top.

#### Browser / OS version

Safari 12.1.1 (13607.2.6.1.2), macOS 10.13.6 (17G7024)

#### Screenshot / Video

Demoed using my own public / personal WordPress.com websites:

* Gutenberg
  * [Screencast](https://cld.wthms.co/50H5H9)
  * [Resulting post](https://ilovevizslas.wordpress.com/2019/06/12/test/)
* Calypso
  * [Screencast](https://cld.wthms.co/4smev1)
  * [Resulting post](https://ilovevizslas.wordpress.com/2019/06/12/test-2/)
* Classic editor
  * [Screencast](https://cld.wthms.co/pNFp0h)
* [Link to post being used for oEmbed](https://techcrunch.com/2019/06/12/nfc-gets-a-lot-more-powerful-in-ios-13/)

**Comment by gwwar** [comment] 2019-10-29 00:53
Thanks for the report @gamebits I'm going to close this one as a related duplicate of https://github.com/Automattic/wp-calypso/issues/36416

**Closed by gwwar** 2019-10-29 00:53 UTC
Labels: [Type] Bug
