### ISSUE TITLE
Documentation URLs on Embed Blocks

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#86688] opened 2024-01-22 00:58 UTC
### Quick summary

Embed blocks for specific platforms (Reddit, Spotify, etc.) are missing the support link that is present on other blocks. The blocks instead have a support link that is confusing to a .com audience.

### Steps to reproduce

1. Visit the editor.
2. Add a generic Embed block.
3. View the "learn more" link in the block description:
![Annotation on 2024-01-22 at 11-39-04](https://github.com/Automattic/wp-calypso/assets/30727666/4c045a97-947f-40b3-bae6-439c938fcb69)

5. Add a specific platform embed block (Spotify, Twitter, Reddit, etc.)
6. Notice there is no "learn more" link in the block description:
![Screenshot 2024-01-22 at 11 50 50 am](https://github.com/Automattic/wp-calypso/assets/30727666/707aa237-3cfa-4c6e-9a85-1068a7b07abd)

### What you expected to happen

I expected the same "learn more" link in the description of the embed block variants, since it contains helpful information about embedding content and using the block settings.

### What actually happened

The 'learn more' link is missing. Instead, there is a "Learn more about embeds" link in the block itself:
![Annotation on 2024-01-22 at 11-37-16](https://github.com/Automattic/wp-calypso/assets/30727666/6cebc4a7-b9be-42c6-8afb-ca1a147be7d9)

However, that link contains information about the oEmbed protocol that is not relevant to the typical WordPress.com user. I suggest removing this link or updating it to this page targeted at the Dotcom audience: https://wordpress.com/support/wordpress-editor/blocks/embed-block/

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by filipanoscampos** [comment] 2024-01-23 16:53
📌 REPRODUCTION RESULTS


– Tested on Simple:  Replicated /
– Tested on Atomic: Replicated 


📌 FINDINGS & VIDEOInclude 

Replicated as described.
Only the embed block shows the support doc link.
The other blocks show no link.

https://github.com/Automattic/wp-calypso/assets/2540430/e4464da0-d4d8-49b5-94ec-cb3c4fbf8186




📌 ACTIONS
– Triaged.

**Comment by lupus2k** [comment] 2024-07-12 20:10
I noticed the support dock on the sidebar was renamed to `Block guide` [here](https://github.com/Automattic/wp-calypso/pull/86327), and not all blocks have a support link. On the other side, the Embed support doc is still pointing to WPorg.
About the Embed support link, it keeps pointing to WPorg support doc.

![image](https://github.com/user-attachments/assets/816c7921-48bf-41d7-ad17-2388b6f3c179)

As part of pb5gDS-3YO-p2, we're aiming to fix/close high-priority issues in [The One Board](https://github.com/orgs/Automattic/projects/391/views/12) 
Can someone from the @Automattic/martech team look into this issue to confirm whether we should update the support documentation to the WPcom documentation or whether we should keep it as is and close the issue?

**Comment by southp** [comment] 2024-07-15 03:36
Hey @lupus2k , thanks for the ping 👋
However, our team doesn't work on this area often so I don't think we will be able to answer your request within a practical time frame. @agrullon95 could you help look into this? I'm pinging you both here since you are the author of the linked PR above :)

**Comment by arcangelini** [comment] 2024-08-12 15:15
I have a PR that is adding this but I am not sure how many cases I should account for here... Is there a list of the guides we have for these somewhere? @donalirl

**Comment by arcangelini** [comment] 2024-08-12 15:45
Well how about this, I added the links for a few of the major ones and followed it up with adding the default embed block link for everything else.

**Comment by donalirl** [comment] 2024-08-13 01:05
> I have a PR that is adding this but I am not sure how many cases I should account for here... Is there a list of the guides we have for these somewhere? @donalirl

This URL is suitable for all embeds since it contains a list of all supported platforms and how to use the block to embed from those platforms: https://wordpress.com/support/wordpress-editor/blocks/embed-block/

There are some more embed-specific guides here: https://wordpress.com/support/category/content-and-media/blocks/embed-blocks/ but we've already retired a bunch of those (including Spotify, Reddit) in favor of the generic doc.

**Closed as completed** 2024-08-13 14:33 UTC
Labels: Bug, [Pri] High, [Pri] Low, Triaged, [Block] Embed, [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks
