### ISSUE TITLE
Installation : fails on npm start

### ISSUE THREAD

**Issue by psylock** [Automattic/wp-calypso#18426] opened 2017-10-01 14:04 UTC
Hi, 

#### What I expected
I follow installation guidelines available in the README.md, but obtain a fatal error when trying to start calypso. 

#### What happened instead
`npm run -s build`
fails. 

`$ npm bugs wp-calypso
npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "wp-calypso"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/wp-calypso
npm ERR! 404 
npm ERR! 404  'wp-calypso' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tnntwister/Documents/Informatique/js/projets/wp-calypso/npm-debug.log
`
[npm-debug.log](https://github.com/Automattic/wp-calypso/files/1347164/npm-debug.log)

#### Browser / OS version
My system is Elementary Loki (Ubuntu 16.04 fork). 
node v4.2.6
npm v3.5.2

Thanks,

**Comment by samouri** [comment] 2017-10-02 18:55
Hi @psylock!

According to your dev logs it looks like you are running node v4.2.6: 
> npm ERR! node v4.2.6

wp-calypso requires a node version of [v6.11.2](https://github.com/Automattic/wp-calypso/blob/master/package.json#L169)

Can you try upgrading and then try again?

**Comment by psylock** [comment] 2017-10-03 06:40
thanks samouri, 
i've managed to upgrade to node v6.11.3
Unfortunately, there are still errors.
[npm-debug.log](https://github.com/Automattic/wp-calypso/files/1351342/npm-debug.log)

**Comment by hoverduck** [comment] 2017-10-27 14:44
@psylock I wonder if it's something related to the `run-p` command that's executing all the build steps in parallel.  What if you try just `npm run build-server` directly?

The `npm start` command executes a full series of subcommands.  Maybe try breaking it down into its components from `package.json` and see which one it's actually breaking on.

**Comment by claytoncollie** [comment] 2017-11-15 17:04
@psylock Any luck on sorting this out? I am getting the same errors after upgrading npm and node

**Comment by designsimply** [comment] 2017-11-15 21:09
I just tested a fresh clone of `wp-calypso` and was able to start the local server without problems after running `npm start`. I used node v8.9.1 and npm 5.5.1 in my test.The npm-debug.log file from Oct 3 says:

> info using npm@3.10.10

That seems outdated as well. I thought updating node would update npm (?) but perhaps you need to update that as well.

**Comment by designsimply** [comment] 2017-11-21 22:50
Since I can't reproduce the issue, I'm going to close this but we can revisit if the problem persists.

**Closed** 2017-11-21 22:51 UTC
Labels: OSS Citizen, [Type] Help Request
