### ISSUE TITLE
Unable to access Reusable blocks/patterns in Editor

### ISSUE THREAD

**Issue by kerrynicl** [Automattic/wp-calypso#83010] opened 2023-10-13 19:15 UTC
### Quick summary

Unable to add a reusable block to a post or editor

### Steps to reproduce

Click "+" sign in editor to add reusable block.

### What you expected to happen

section to add synced patterns 
![synced-patterns](https://github.com/Automattic/wp-calypso/assets/83325600/53225a93-627c-4fb8-a1eb-572fcb4cc4ab)

### What actually happened

No section to add synced patterns 
![Screenshot on 2023-10-13 at 15-13-43](https://github.com/Automattic/wp-calypso/assets/83325600/bb9dee3b-2b7d-4c0e-878a-0cd9fa4fd09b)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes
reported in zdm_7164172
_No response_

**Comment by cuemarie** [comment] 2023-10-16 21:11
If I understand correctly, the separate Synced Patterns tab was removed on purpose in Gutenberg 16.7:

- https://github.com/WordPress/gutenberg/pull/54007

> Currently it is confusing that synced patterns are in a separate tab, and also causes performance issues because patterns are not paged.
> - Removes the synced patterns tab from inserter
> - Updates the store patterns selector to get synced and unsynced patterns so both display in the existing patterns tab
> - Adds paging to the patterns list to account for large numbers of synced patterns in some sites
> - Adds a filter to allow users to limit pattern list to just theme, or user patterns, and another filter when user patterns selected to limit to synced or unsynced patterns

📌 ACTIONS
- Closed as by design
- Feel free to reopen if anyone understands this change differently and thinks we should look into this further - thanks!

📌 MESSAGE TO AUTHOR
- @kerrynicl just pinging you so you see this update. 👍

**Closed as not planned by cuemarie** 2023-10-16 21:11 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] High, Triaged, [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience
