### ISSUE TITLE
Editor: Post Settings has rounded blue underline?

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#16345] opened 2017-07-19 02:24 UTC
I'm not sure whether this is intentional or a visual regression?

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Click "Post Settings"

#### What I expected

Previous visual appearance:

<img width="564" alt="previously" src="https://user-images.githubusercontent.com/128826/28347859-00181f32-6c7d-11e7-8c07-0933ae7d884d.png">

#### What happened instead

Currently:

<img width="564" alt="post settings" src="https://user-images.githubusercontent.com/128826/28347919-55ca1cb4-6c7d-11e7-9222-c7781826ab10.png">

#### Browser / OS version

Chrome OSX 

#### Context / Source
#dogfooding

**Comment by folletto** [comment] 2017-07-19 08:02
Seems a visual regression. That's not a pattern we use.

**Comment by jameskoster** [comment] 2017-07-28 14:20
I've noticed a few other buttons being rounded that perhaps shouldn't be;

Back arrow:
![round](https://cldup.com/ZGiRlxYh0B-3000x3000.png)

Preview:
![round2](https://cldup.com/ZGiRlxYh0B-3000x3000.png)

**Comment by folletto** [comment] 2017-07-28 14:25
Yeah, same regression unfortunately. Well spotted.

**Comment by lsinger** [comment] 2017-08-08 12:59
I can't reproduce any of those anymore. Good to close?

**Comment by lsinger** [comment] 2017-08-08 13:04
Ah! Nope. Found another one:

<img width="93" alt="screen shot 2017-08-08 at 2 03 34 pm" src="https://user-images.githubusercontent.com/23619/29073152-70a97a46-7c42-11e7-9ca6-f371e0c43808.png">

**Comment by rachelmcr** [comment] 2018-01-02 23:17
Closing as I can't reproduce any of these anymore, including around the help icon.

#bug-scrub #pre-gutenburg-bug-purge

**Closed by rachelmcr** 2018-01-02 23:17 UTC
Labels: Design, Editor, [Type] Bug
