### ISSUE TITLE
Problems with Babel Module Exports

### ISSUE THREAD

**Issue by thething76** [Automattic/wp-calypso#18388] opened 2017-09-29 10:33 UTC
Hi, 

i had some difficulties to start the local server. I had to remove the module.export declarations in 
/server/bundler/babel/babel-loader-cache-identifier

```
	/*
	'babel-loader': getModuleVersion( 'babel-loader' ),
	'babel-core': getModuleVersion( 'babel-core' ),
	'babel-plugin-transform-wpcalypso-async': getModuleVersion( '../babel-plugin-transform-wpcalypso-async' ),
	*/
```

The via npm installed babel packages had no version info. On starting via npm start the process stopped: Error: Cannot find module ... '/node_modules/babel-loader/lib/package.

After removing the declarations it works. (or am i missing something :D?)

**Comment by designsimply** [comment] 2017-11-15 21:10
I just cloned a new instance of Calypso and I was able to start the local server without any trouble. I was running node v8.9.1 on Mac OS X 10.12.6 for my testing. If you aren't using the latest versions of node and npm, could you try updating those? Then would you mind trying a fresh install to see if the problem is still happening for you?

**Comment by designsimply** [comment] 2017-11-21 22:50
Since I can't reproduce the issue, I'm going to close this but we can revisit if the problem persists.

**Closed** 2017-11-21 22:51 UTC
Labels: OSS Citizen, [Type] Help Request
