### ISSUE TITLE
Flaky E2E: wp-signup__paid 'See secure payment' times out

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57958] opened 2021-11-11 16:03 UTC
### Details

TeamCity ID: 6968636

Looking at the picture, it doesn't think we actually added something to our cart! 😱 

```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-testid="review-order-step--visible"] .checkout-line-item >> text=WordPress.com Personal" to be visible
============================================================
at CartCheckoutPage.validateCartItem (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/cart-checkout-page.ts:85:19)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-signup__paid.ts:81:28)
    at Promise.then.completed (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:390:28)
    at callAsyncCircusFn (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:315:10)
    at _callCircusTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at _runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-
3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:167:21)
    at jestAdapter (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

![wp-signup__paid-see-secure-payment](https://user-images.githubusercontent.com/26772342/141329732-7285c8c1-9c3e-4294-8faf-142542b19b39.png)

**Comment by dpasque** [comment] 2021-11-11 16:25
Error in console:
```
We were rate-limited from checking if your requested Payment Request options are allowed. Please test again before going live.
```

**Comment by dpasque** [comment] 2021-11-16 20:33
On this one, I'm not sure there's a lot we can do apart from fixing the related bug that is behind this: #57960

**Comment by worldomonation** [comment] 2021-11-20 01:12
As an alternative, I am thinking it may make sense to walk through the flow right up until the checkout occurs, but not actually perform the checkout.

For the next sprint I may modify a bunch of the tests in the Quarantined E2E spec to do this, so we have coverage of the flows at least.

**Comment by sirbrillig** [comment] 2021-11-24 00:43
I suspect that the rate limiting is a red herring, but we should be able to find out the actual cause from the changes in https://github.com/Automattic/wp-calypso/pull/58428 which should actually display whatever error is causing this.

**Comment by worldomonation** [comment] 2021-12-04 01:19
Interestingly, I haven't seen this issue pop up at all since then. Granted the spec which includes this step (Signup: Paid) has been demoted to Quarantined tests, but they do still run every 3 hours, 7 days a week.

Will continue to monitor but if it isn't reproducible for some more time, it may be good to close this issue for now.

**Comment by worldomonation** [comment] 2021-12-06 21:45
Deciding to close this for now, since in the 3+ weeks since reporting it hasn't happened again.

**Comment by worldomonation** [comment] 2021-12-06 21:51
Okay, as soon as I wrote the above and closed this issue, I found an instance of it happening.

TeamCity: https://github.com/Automattic/wp-calypso/pull/58833

@sirbrillig How would I be able to look up the logs for a run at 15:03 UTC on December 6? Would it be contained in the trace file or be items in Logstash?

**Comment by sirbrillig** [comment] 2021-12-06 22:03
> How would I be able to look up the logs for a run at 15:03 UTC on December 6? Would it be contained in the trace file or be items in Logstash?

The easiest thing is probably to examine the visual recording of the e2e test run; you should be able to see the error message displayed on the page when signup fails. I'm not sure where to find that in this particular case.

Alternatively, we may be able to find an error in the server logs at that time, although some errors might not show up. Do you know what the username is for the user that ran the test?

**Comment by worldomonation** [comment] 2021-12-06 22:21
> > How would I be able to look up the logs for a run at 15:03 UTC on December 6? Would it be contained in the trace file or be items in Logstash?
> 
> The easiest thing is probably to examine the visual recording of the e2e test run; you should be able to see the error message displayed on the page when signup fails. I'm not sure where to find that in this particular case.

I will try looking in the trace file later today, that should tells us more.

> Alternatively, we may be able to find an error in the server logs at that time, although some errors might not show up. Do you know what the username is for the user that ran the test?

The user that ran the test is `e2eflowtestingpaid1638802915108`.

**Comment by worldomonation** [comment] 2021-12-06 23:07
Looking in the trace file, there are two identical errors at the plan selection screen:

```
No current user found
```

I've seen this before (p1637252482014700-slack-C1A1EKDGQ), but there was no solution that we reached in the thread. There is another older thread (p1624280629449000-slack-C01VA100LEA) which also mentions the string `No current user found`, but that's in the context of Happychat. 

What it sounds like from reading the first thread is that the user is created successfully but _something_ messes with the cookie or the logged in state and requires the user to re-authenticate.

**Comment by sirbrillig** [comment] 2021-12-07 00:07
That seems to confirm my suspicion that there was some sort of auth or race condition that was preventing the cart endpoint from working (since it requires a user). I've seen suggestions of this before in various places but I haven't been able to track it down. I think the issue is with the user creation part of signup (and the links you shared above seem to agree) and I don't know much about that part of the flow. 😟

**Comment by worldomonation** [comment] 2022-09-20 23:00
This is no longer an issue now that we've refactored this spec.

**Closed as completed by worldomonation** 2022-09-20 23:00 UTC
Labels: [Pri] Normal, Task, Flaky E2E, [Type] Monitoring
