### ISSUE TITLE
Atomic Classic: Admin color scheme not inheriting from the site's pre-transfer Simple Classic state

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94970] opened 2024-09-27 01:58 UTC
### Quick summary

My primary site is set to Ectoplasm.

![SCR-20240927-jbcv](https://github.com/user-attachments/assets/cfe5170e-c6b6-46ed-9445-84076a75a13e)

Creating a new site, the new site has the color scheme Midnight (not sure why).
![SCR-20240927-jbnh](https://github.com/user-attachments/assets/6b241991-fa7c-49df-978c-ee1df0dfc116)

Switching to Classic Simple, the color scheme remains to be Midnight.
![SCR-20240927-jbsu](https://github.com/user-attachments/assets/5869d4a0-4a11-4bb6-8a68-7cb2046c9fff)

Then I transferred the site to Atomic, by upgrading via Settings > Permalinks and activating the transfer via the Hosting Features tab on the Hosting Management Panel. The site is now Atomic Classic, but the color scheme changed from Midnight to Ectoplasm.

![SCR-20240927-jcjd](https://github.com/user-attachments/assets/39502d2d-e39b-4183-98f2-8cfa966b5c8a)

![SCR-20240927-jcnx](https://github.com/user-attachments/assets/551b68c8-36ae-44e5-974a-5360276f1703)

Note that at no point I updated the color scheme.

### Steps to reproduce

See above.

### What you expected to happen

For the Atomic Classic site to have the color scheme Midnight.

### What actually happened

The Atomic Classic site had the color scheme Ectoplasm.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by fushar** [comment] 2024-09-27 02:14
I think I have an idea why it's happening. There are two issues here:

> Creating a new site, the new site has the color scheme Midnight (not sure why).

I think this is the value of the `admin_color` at your user level:

```
wp> get_user_meta(get_current_user_id(), 'admin_color');
=> string(8) "midnight"
```

When creating a new site, I guess we use that value at user level. Note that it is currently not possible to change the user-level admin color anymore; I think we just missed it.

Proposing this solution: when creating a new site, the admin color scheme should be Default (or Modern, or whatever is set when we create a new user; it should be consistent). It means we always ignore the (old) color scheme at user level.

---

> Then I transferred the site to Atomic, by upgrading via Settings > Permalinks and activating the transfer via the Hosting Features tab on the Hosting Management Panel. The site is now Atomic Classic, but the color scheme changed from Midnight to Ectoplasm.

This is a bug which I haven't investigated yet. There must be something wrong here: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sjcpbz%2Qhfre%2Qcebsvyr%2Sjcpbz%2Qfvzcyr%2Qfvgr%2Qyriry%2Qhfre%2Qcebsvyr.cuc%3Se%3Q198637s7%23125-og

**Comment by taipeicoder** [comment] 2024-09-27 02:40
> Proposing this solution: when creating a new site, the admin color scheme should be Default (or Modern, or whatever is set when we create a new user; it should be consistent). It means we always ignore the (old) color scheme at user level.

+1.

**Comment by okmttdhr** [comment] 2024-10-11 01:13
> > Then I transferred the site to Atomic, by upgrading via Settings > Permalinks and activating the transfer via the Hosting Features tab on the Hosting Management Panel. The site is now Atomic Classic, but the color scheme changed from Midnight to Ectoplasm.
> 
> This is a bug which I haven't investigated yet. There must be something wrong here: uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sjcpbz%2Qhfre%2Qcebsvyr%2Sjcpbz%2Qfvzcyr%2Qfvgr%2Qyriry%2Qhfre%2Qcebsvyr.cuc%3Se%3Q198637s7%23125-og

I conducted some tests, but the issue didn’t occur when I _changed_ the admin color scheme _before_ transferring. It only happens when the site is freshly created and then transferred without modifying the admin color from its default setting.

I suspect the issue arises because there’s no initial **site-level** admin color value set. Therefore, the diff proposed by @fushar  (D163521-code) should likely resolve this issue as well.

**Comment by okmttdhr** [comment] 2024-10-11 01:24
> > Then I transferred the site to Atomic, by upgrading via Settings > Permalinks and activating the transfer via the Hosting Features tab on the Hosting Management Panel. The site is now Atomic Classic, but the color scheme changed from Midnight to Ectoplasm.
>
>I suspect the issue arises because there’s no initial site-level admin color value set. Therefore, the diff proposed by @fushar ([D163521-code](https://href.li/?D163521-code)) should likely resolve this issue (for new sites) as well.

I confirmed this patch D163521-code resolved the issue for newly created sites! The admin color stayed Default (`fresh`) after switching to Atomic. 

For existing sites, setting the initial admin color to `fresh`, even when no site-level admin color is set during migration to Atomic, might be a good approach. Could you explore this further, @fushar?

**Comment by fushar** [comment] 2024-10-11 04:44
>  It only happens when the site is freshly created and then transferred without modifying the admin color from its default setting.

I tried this and checked logs. I think something is wrong, the user ids are parsed incorrectly and thus it's not saving the user options. I'm checking further...

![Image](https://github.com/user-attachments/assets/dd7f81b7-bb26-4d56-ad62-4742e52a0e72)

**Comment by fushar** [comment] 2024-10-11 07:29
UPDATE: It looks like `wp user list` command, which is being used in the Atomic transfer to set the user profile (uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sjcpbz%2Qhfre%2Qcebsvyr%2Sjcpbz%2Qfvzcyr%2Qfvgr%2Qyriry%2Qhfre%2Qcebsvyr.cuc%3Se%3Q198637s7%23125-og), is failing due to Core bug.

More info here: p9F6qB-g4E-p2.

I'm thinking how to resolve this 😅

**Comment by fushar** [comment] 2024-10-14 11:01
Proposing these patches which should completely solve the issue:

- D163739-code => fixes the incorrect color issue after Atomic transfer when the site has not yet set a site-level admin color scheme.
- D163521-code => always use consistent default admin color scheme when creating a new site.

**Comment by fushar** [comment] 2024-10-15 08:48
The patches have been deployed. I've confirmed the issue is now fixed.

**Closed as completed by fushar** 2024-10-15 08:48 UTC
Labels: Bug, [Pri] High, [Feature] Calypso & wp-admin Navigation, Needs triage, Lego Maintenance, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Content Management, [Feature] Classic Interface
