### ISSUE TITLE
Log in: Edge: Space under the Jetpack banner

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#15285] opened 2017-06-20 10:10 UTC
On Edge there is a space under the Jetpack banner on /log-in:

<img width="623" alt="screen shot 2017-06-20 at 11 08 40" src="https://user-images.githubusercontent.com/275961/27328148-f9d7e322-55a8-11e7-81f8-153c9f936d7d.png">

**Comment by fabianapsimoes** [comment] 2017-06-30 09:59
Duplicate of #15373

**Closed by fabianapsimoes** 2017-06-30 09:59 UTC
Labels: Login, [Pri] Low
