### ISSUE TITLE
Hero Block leads to invalid content when coming back to edit

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#36586] opened 2019-10-08 09:30 UTC
Hero Block causes invalid content

#### Steps to reproduce
1. Starting at URL:  https://wordpress.com/block-editor/page/katiaartofliving.com/968
2. The Hero Block when created works fine 
3. Save the page
4. Come back to edit the page and this time it reports invalid content - https://cld.wthms.co/Zc9x6S
5. Tried on a test page and it does the same - https://wordpress.com/block-editor/page/katiaartofliving.com/1041

#### What I expected
For there not to be an error.

#### Browser / OS version
Unsure of the users set up ( 2404952-zen)
Mine is MacOS MacBookPro

**Comment by glendaviesnz** [comment] 2019-10-09 04:31
This sort of error is usually caused by filters stripping some of the CoBlock attributes. 

I ran through all of the Hero block settings and for me everything saved correctly except setting the focal point of the background image.

![hero](https://user-images.githubusercontent.com/3629020/66451788-6d4b9f80-eaba-11e9-83c7-27ff17331567.gif)

It must be saving this as some sort of html attribute rather than as part of the block attributes.

@rickmgithub - do you know if the user was setting the background focal point ?

**Comment by galakhyati** [comment] 2019-10-11 12:07
The user returned to chat and said they did not add a background image to the Hero block, so there is no way they knew about the focal point.

They created a new page with Hero block and set it to Homepage, and were able to edit the page fine with no errors, so they were unable to replicate the issue. 

I tried to have the same setup on my test site and was unable to replicate the issue too.

I am assuming the original page had some HTML code missing, hence caused the issue. 

The user is going to use Cover, columns, button, paragraph, etc. blocks to have a similar layout like Hero block to avoid any issues as experienced before.

Feel free to close the issue.

Chat: #15884541-hc

**Comment by katiaartofliving** [comment] 2019-10-12 11:07
The issue with the hero block is still present but only manifests if the background colour of the hero block is set to clear. Please refer to this description:
https://github.com/godaddy/coblocks/issues/729

The concept of focal point is not relevant to this issue as the image display is driven from the page being a home page. Whatever is set as the home page with the theme "TheFour" gets a background image without the user adding one. The background image is either the header image, or the featured image if there is one set.  This happens whether there is a hero block or not. Specifying the  home page is done under Customise > Home Page Setting.
I am no longer using the hero block because it becomes un-editable whenever I make the background colour clear. Because of the home page setting functionality I don't need to use the Cover block either. I am using regular paragraphs and it works fine. Hope this helps.

**Comment by glendaviesnz** [comment] 2019-10-16 03:33
The block validation definitely fails if the background focal point is changed, so maybe we want to list a separate bug for that  - I will check tomorrow if it is a wpcom specific issue, or a wider gutenberg version related issue, and will file then file a relevant bug with coblocks.

**Comment by kwight** [comment] 2019-10-30 20:59
I'm also unable to replicate the original reported issue, let's consider it dealt with.

> The issue with the hero block is still present but only manifests if the background colour of the hero block is set to clear.

This is also no longer the case with the current 1.16.1.

> The block validation definitely fails if the background focal point is changed, so maybe we want to list a separate bug for that

Yep, we already have https://github.com/Automattic/wp-calypso/issues/35762. Closing.

**Closed by kwight** 2019-10-30 20:59 UTC
Labels: [Type] Bug
