### ISSUE TITLE
Full Site Editing: Classic editor WSOD

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#36375] opened 2019-09-26 20:25 UTC
When attempting to load a page on a site that has FSE enabled with a classic editor the WSOD appears.

This is a major issue for support, since HEs opening a customer site for the first time won’t be be automatically using the Block Editor.

I think we should force Gutenberg for all users on FSE enabled sites, regardless of usual per user per site opt-in preferences that we use to determine whether Gutenberg should be loaded.

More info and discussion in this post: paYE8P-8W-p2

**Comment by noahtallen** [comment] 2019-09-30 22:03
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/35804. Will summarize everything there since there is already some conversation around this.

**Closed by noahtallen** 2019-09-30 22:03 UTC
Labels: [Goal] Full Site Editing, [Pri] High
