### ISSUE TITLE
Page Layout picker: shows wrong themplate when using a language other then english

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#44739] opened 2020-08-06 13:50 UTC
#### Steps to reproduce

1. Starting at URL: Switch the UI language to German in the User settings. 
2. Create a new page. 
3. Notice that if you select certain layouts such as Twenty Twenty that an unexpected templates shows up in the preview.

#### What I expected
To see the translated version of the selected template. 

#### What happened instead
I saw a complete different template. 

#### Browser / OS version
Firefox/ OSx

#### Screenshot / Video
<img width="1468" alt="Screen Shot 2020-08-06 at 3 48 08 PM" src="https://user-images.githubusercontent.com/115071/89539710-65ed4380-d7fc-11ea-885b-2a39112e3618.png">

**Comment by davipontesblog** [comment] 2021-03-16 13:11
I am moving this to the triaging board to see if it's still an issue with the new layout picker on simple sites. If so, we can close it.

**Comment by synora** [comment] 2021-03-16 18:43
I'm unable to reproduce this issue and it's no longer an issue with the new layout picker. Closing.

**Closed by synora** 2021-03-16 18:43 UTC
Labels: Page Layouts, Triaged, [Closed] Not Reproducible, [Type] Bug
