### ISSUE TITLE
hr HTML tags Breaking Paragraph Blocks and Classic Revisions Unless it's Inside <!-- wp:separator -->

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#94184] opened 2024-09-04 13:18 UTC
### Quick summary

Adding an HTML code that code that contains the `<hr>` code results in an eventually broken block. Block recovery attempts recovers what's before the `<hr>` tag but not what's after it.

If using classic revisions (wp-admin). If a revision contains that `<hr>` tag, all the content will be visible in the revisions view but anything under the tag will not be included in the restored version.

### Steps to reproduce

1. Using Gutenberg, on any post.
2. Add a paragraph block and write anything - "Test"
3. Edit the paragraph block as HTML and add an `<hr>` to the end, followed by some text.
4. Click Edit visually.
5. You will get an Attempt Block Recovery button
6. Clicking it removes the `<hr>` tag and all that's after it

There are 

### What you expected to happen

To either just remove the `<hr>` tag or convert it into a separator block.

### What actually happened

The `<hr>` tag is removed and all that's after it, inside that paragraph block.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Regarding the code.
- Use the code editor to remove the HR tags manually 

Regarding the revisions.
- Make sure to use the Gutenberg revisions and not the classic revisions. The Gutenberg revisions do bring the content that's after the `<hr>` tag but the block remains "fragile". 

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

8631891-zen
The user mentioned using Word and paste to Classic block when creating content.

**Comment by retnonindya** [comment] 2024-09-05 07:52
@mxhassani - I'm afraid I can't see your report clearly here. This is what I see on my end:

<img width="827" alt="Screenshot 2024-09-05 at 3 51 21 PM" src="https://github.com/user-attachments/assets/84464746-19d5-44c7-9b17-db185445f5fa">

It might be the text you shared got markdown-ed (? Is that even a word?) Can you reshare the message, Mohamed? Thanks!

**Comment by mxhassani** [comment] 2024-09-05 08:06
@retnonindya Thanks! It was the HR tags at it again, I put them inside quotes.

**Comment by inaikem** [comment] 2024-10-15 03:44
Moving this to the main triage queue since we received an author reply >month ago.

**Comment by Robertght** [comment] 2024-10-25 12:00
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated 
- Tested on P2 (optional) – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
https://github.com/user-attachments/assets/bd4e9f3a-9ebd-4b25-9c15-3e99496df49e

📌 ACTIONS
- Triaged

📌 Message to Author
@mxhassani I'm not sure if it's permitted to have <hr> elements inside other ones, like paragraphs on Gutenberg, but I agree it could create mayhem for some users, especially with revisions.
At the same time, I could not find another report so I've raised this as a bug on core: https://github.com/WordPress/gutenberg/issues/66467

cc @inaikem if you need to review this with someone from the Gutenberg team.

**Comment by Robertght** [comment] 2024-10-28 10:59
@mxhassani I'm going to close this for now as we've heard from the core folks it's not planned thing, yet there's some room for improvement.

Ref: https://github.com/WordPress/gutenberg/issues/66467#issuecomment-2439953247

Please reopen if you find more cases like this.

**Closed as completed by Robertght** 2024-10-28 10:59 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] Low, [Status] Core Fix Needed, Triaged, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Product] WordPress.com, [Feature Group] Editor Experience
