### ISSUE TITLE
Gutenberg: Page Preview 404s

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/wp-calypso#30744] opened 2019-02-13 02:55 UTC
#### Steps to reproduce
1. Starting at URL: p1550008422013400-slack-gutengroup-wpcomhappy
2. Open a page in block editor
3. Click Preview
4. Preview shows a 404 error

#### What I expected
Expected an updated preview

#### What happened instead
404 page showed in preview

#### Browser / OS version
Chrome 71.0.3578.98
Windows 10

#### Screenshot / Video
1550024637-pb

#### Context / Source

7229915-hc

**Comment by arunsathiya** [comment] 2019-02-13 07:44
I am closing this is as a duplicate of https://github.com/Automattic/wp-calypso/issues/29324

I might be overseeing something. If your issue is different from the one I have linked to, please feel free to re-open it.

**Closed by arunsathiya** 2019-02-13 07:44 UTC
Labels: [Goal] Gutenberg, [Type] Bug
