### ISSUE TITLE
Menu: unable to delete items from menu

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#4560] opened 2016-04-07 04:54 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/menus/julesaustest.wordpress.com

2. Click on the "edit" icon for a menu item
3. Click on the trashcan icon to delete the item.
4. Click on the "Delete Item" button.

#### What I expected
The item to be deleted from the menu

#### What happened instead
The item remained in the menu

I was able to delete items from other menus, so it could be related to the Default Menu or first menu.

#### Browser / OS version
Chrome Version 50.0.2661.66 beta (64-bit),  OSX Yosemite 10.10.5

#### Screenshot / Video
![menu delete](https://cloud.githubusercontent.com/assets/5952255/14340952/16e13884-fcd0-11e5-86bd-8f7f78d7c020.gif)

**Comment by lancewillett** [comment] 2016-04-07 15:26
Sorry for the incorrect label — I'm working on a bot and it messed up with the capitalized "B" in your username. :)

**Comment by lancewillett** [comment] 2016-04-07 20:15
@deBhal Any JS console errors?

**Comment by deBhal** [comment] 2016-04-07 22:44
No console errors.

I also turned on all the menu related debug I could find, but the only messages were out of menu-item-types before I did any clicking:

`localStorage.debug = 'calypso:menus:categories-options, calypso:menus:option-list, calypso:menus:post-list, calypso:menus:taxonomy-list, calypso:menus:location-picker, calypso:menus:index, calypso:menus:delete-button, calypso:menus:editable-item, calypso:menus:menu-items-list, calypso:menus:menu-item-types, calypso:menus:menu, calypso:menus:menu-picker, calypso:menus:menu, calypso:menus:save-button';
`
->

![menus_ _my_test_blog_ _wordpress_com_and_calypso_ _bash_ _131x35](https://cloud.githubusercontent.com/assets/5952255/14369048/4498b5dc-fd65-11e5-9b4d-07777e86a46d.jpg)

The types looks pretty sensible - "Posts", "Pages", "Media" and "Testimonials".  I'm happy to provide more details, but they don't seem relevant.

**Comment by designsimply** [comment] 2016-04-07 23:43
Tested deleting various menu items using Safari 9.1 on and Chrome 49.0.2623.87 on Mac OS X 10.11.13 and couldn't reproduce!

@deBhal, just to make sure, in the gif you posted it looks like the "Save" button never gets activated (it should turn dark blue) after you click the "Delete Item" button, can you confirm that's the case? 

Any chance you might also be able to try it from a stable version of a different browser? (I noticed you're using Chrome beta.)

**Comment by alisterscott** [comment] 2016-04-07 23:48
I can only reproduce this by deleting _during a save_, which isn't what's being shown in the recording above unfortunately.

![menus](https://cloud.githubusercontent.com/assets/128826/14370199/18bc8024-fd6f-11e5-91f9-98facc30d728.gif)

**Comment by designsimply** [comment] 2016-04-08 00:59
Hold on! Figured out that the problem only happens on a 2nd attempt to change the default menu. Here are my steps to reproduce the problem:

1. Go to a WordPress.com site where you have never tried editing the default menu before
1. Go to My Site > Menus
1. Make any change to the default menu
1. Verify that a new menu was created and is now selected at top right and showing the change
1. Try making another change to the default menu (note the change is not reflected)
1. Click the Save button

<strong>Result:</strong> the first time you try to make a change to the default menu, it works normally, however, after any subsequent attempt to change the default menu the changes are not reflected and you are no longer redirected to the new menu after clicking the Save button

<strong>Video:</strong> [1m50s](https://cloudup.com/cYDA_cNtaoT)

**Comment by lancewillett** [comment] 2016-04-14 18:29
Good sleuthing, Sheri. :)

Since it's edge-case — I'm suggesting we close it for now.

**Closed by lancewillett** 2016-04-14 18:29 UTC
Labels: Menus, [Type] Bug
