### ISSUE TITLE
[Bug]: Domain connections included with plan without payment method display "no payment method" warning

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#67516] opened 2022-09-07 17:46 UTC
### Quick summary

A user who has a Domain Connection is seeing a "You don't have a payment method to renew this subscription" warning in the list of Active Upgrades for their site, even though the Domain Connection is included with their plan.

<img width="1087" alt="Screen_Shot_2022-09-07_at_1_40_10_PM" src="https://user-images.githubusercontent.com/2036909/188944066-46f760f3-fc2b-4bc3-9f7f-410ae6ef2e10.png">

Note that on the _single_ purchase page for that purchase, it reads "Included with plan".

<img width="971" alt="Screen_Shot_2022-09-07_at_1_56_57_PM" src="https://user-images.githubusercontent.com/2036909/188946883-1d34975e-7699-473a-a4b3-3383b9c31b29.png">

For the warning message to be displayed on the list page, the mapping must have a payment method attached that is not rechargeable – I don't see any payment method attached, so that's probably not it – or it must have _no_ payment method but have auto-renew enabled. It looks like the mapping may have been added by an HE directly and has no payment method attached, so that's probably why the message is shown.

https://github.com/Automattic/wp-calypso/blob/e305f0316e9305391dee27474d144a513bdcc98e/client/me/purchases/purchase-item/index.jsx#L412-L419

I think the front-end should probably be made aware of bundled products and not display that message for them; we could probably use the same technique used elsewhere in that component.

https://github.com/Automattic/wp-calypso/blob/e305f0316e9305391dee27474d144a513bdcc98e/client/me/purchases/purchase-item/index.jsx#L320-L322

**Comment by sirbrillig** [comment] 2022-09-07 17:47
Original Slack report of this bug: p1662562505638729-slack-C02DQP0FP

**Comment by retnonindya** [comment] 2022-09-11 01:45
The original report from the user: 5539578-zd-woothemes

The user expected to be informed once the issue is resolved.

**Comment by jjchrisdiehl** [comment] 2022-10-14 22:11
PR https://github.com/Automattic/wp-calypso/pull/69100

**Comment by jjchrisdiehl** [comment] 2022-10-19 22:43
This has been resolved in https://github.com/Automattic/wp-calypso/pull/69100

**Closed as completed by jjchrisdiehl** 2022-10-19 22:43 UTC
Labels: Bug, [Feature] Purchase Management, Good First Issue
