### ISSUE TITLE
Assembler color styles are not applied properly within Safari

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#89324] opened 2024-04-08 15:58 UTC
#### Steps to reproduce

1. Open Safari
2. Starting at URL: https://wordpress.com/setup/with-theme-assembler/pattern-assembler
3. Add two patterns to the page.
4. Select "Select styles"
5. Select a premium style with a background color.

#### What I expected
To see the background color of the style applied to my patterns. It works as expected in Chrome.

#### What happened instead
The patterns maintain a background color of white, making it seem like the style is much less expressive and boring. 

#### Browser / OS version
Safari, latest. 

#### Screenshot / Video
![CleanShot 2024-04-08 at 11 58 05](https://github.com/Automattic/wp-calypso/assets/1813435/48539773-4018-4f40-995c-8ccd53e933e1)

**Comment by taipeicoder** [comment] 2024-04-09 09:22
Sharing my findings below:

This issue is caused by a recent change in Gutenberg https://github.com/WordPress/gutenberg/pull/59377 where the iframe body is explicitly set to have a white background. This was later fixed in https://github.com/WordPress/gutenberg/pull/60106 where the CSS rule's specificity was reduced. Fixing this on Calypso side would require a version upgrade of the @wordpress/block-editor version from 12.22.0 to 12.23.0.

I've requested assistance from the Calypso team in https://github.com/Automattic/wp-calypso/pull/89343#issuecomment-2044526628 for the package upgrade.

**Closed as completed** 2024-04-10 05:17 UTC
Labels: Bug, [Feature] Pattern Assembler, [Pri] TBD
