### ISSUE TITLE
Woo-Connect Insights: Add prev/next arrows in mobile Traffic Stats

### ISSUE THREAD

**Issue by raoulwegat** [Automattic/wp-calypso#14207] opened 2017-05-18 02:34 UTC
Add back the Previous and Next time period arrows at <660px view in Traffic Stats that were removed in #10360 at [#issuecomment-271521378](https://github.com/Automattic/wp-calypso/pull/10360#issuecomment-271521378) Some more background: p1494998114597798-calypso-design

**Arrows are visible at >660px.**

![screen shot 2017-05-18 at 12 23 33 pm](https://cloud.githubusercontent.com/assets/2627210/26183964/5d3fb0a0-3bc5-11e7-96d6-172d3562b987.png)

**Arrows not visible at <660px.**

![screen shot 2017-05-18 at 12 24 01 pm](https://cloud.githubusercontent.com/assets/2627210/26184008/989b7418-3bc5-11e7-8678-b4dc4a1a5158.png)

**Comment by psealock** [comment] 2017-06-01 01:02
This appears to be by design
https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/stats/stats-period-navigation/style.scss#L21-L23

It can get a bit crowded if the period selected is not days
![screen shot 2017-06-01 at 1 00 56 pm](https://cloud.githubusercontent.com/assets/1922453/26660206/7924a1c6-46ca-11e7-8091-cb5be2cc307f.png)

**Comment by timmyc** [comment] 2017-12-20 17:59
Closing out this issue since it does appear to be by design, and how site stats works as well.

**Closed by timmyc** 2017-12-20 17:59 UTC
Labels: Store, [Type] Bug
