### ISSUE TITLE
CoBlocks: Issue with Lightbox on Galleries

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#40422] opened 2020-03-24 23:31 UTC
#### Steps to reproduce

1. Create a new page
2. Add the Stacked block, or the Carousel one
3. Select some images for the gallery
4. Enable the Lightbox feature on the block
5. Publish the page
6. Go to the live page and click on an image in the gallery

This issue doesn't seem to happen on WordPress.com Simple sites and WordPress.org, only on Atomic sites.

#### What I expected

The Lightbox feature to properly load the images.

#### What happened instead

The images are showing left aligned and with some odd HTML text below it.

#### Browser / OS version
Chrome 80.0.3987.149
Mac OS X 10.15.3

#### Screenshot / Video

![Screen Shot 2020-03-24 at 20 24 49](https://user-images.githubusercontent.com/16104522/77486111-9b752f80-6e0d-11ea-92bd-dfefd06b63f6.png)

#### Context / Source
#user-report

**Comment by WunderBart** [comment] 2020-08-26 13:41
Closing as I couldn't reproduce after the recent update (https://github.com/Automattic/wp-calypso/issues/45033). Lightbox seems to be rendering correctly now.

**Closed by WunderBart** 2020-08-26 13:41 UTC
Labels: Atomic, [Goal] Gutenberg, [Type] Bug
