### ISSUE TITLE
Clicking on WooCommerce to set up a store, got stuck on the Building your Store screen.

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#50833] opened 2021-03-08 08:23 UTC
I was in a Quick Start today, and the customer clicked on WooCommerce to set up a store, and it got stuck on the Building your Store screen. After a while, we resolved by adding the WooCommerce plugin from Tools>Plugins and activating. Even after that, the store was stuck until we opened wp-admin and started setting up from there. 

https://user-images.githubusercontent.com/12430020/110295010-44a23f00-7ff9-11eb-941f-2984c0aa572b.mp4

After waiting for 22 minutes, I tried from my end then activated the plugin ( WP Admin ).

_Originally posted by @ChrissiePollock in https://github.com/Automattic/wp-calypso/issues/50616#issuecomment-792076254_

**Environment**
Atomic

**Plan**
Business

**Comment by cpapazoglou** [comment] 2021-03-08 08:35
@mattsherman, just wanted to raise visibility on this one since it seems to be related to "Store" deprecation?

**Comment by selectedselections** [comment] 2021-03-08 21:43
I ran into this issue here hc-27179103

Deactivating everything other than Woo in CLI allowed the progress to go further but then it stalled out again. 

Clicking on Woo from the wp-admin dashboard just redirects me back to calypso each time.

**Comment by ilyasfoo** [comment] 2021-03-09 02:38
@cpapazoglou Yes, this is related to Store deprecation. Thank you for creating this issue. However, I'm unable to reproduce this issue with my business site so far.

>Clicking on Woo from the wp-admin dashboard just redirects me back to calypso each time.

@selectedselections The link was supposed to only redirect back to calypso if WooCommerce plugin is not installed. Can you confirm whether that was the case? Also, are there any error logs or other detail that I can dig into?

**Comment by mattsherman** [comment] 2021-03-10 16:02
Hmm... this sounds awfully similar to https://github.com/Automattic/wp-calypso/pull/50599

In that case, things never, ever, progressed to the WooCommerce onboarding wizard. In this case, it sounds like it sometimes is stalling out?

@ilyasfoo We could consider adding some Tracks events to the workflow... that would allow us to better pinpoint if there is a specific spot where things get stuck (we could create a funnel to detect the dropoff). We did something similar with importing in the past, where we had a similar progress screen that could sometimes get stuck. And/or, some logstash entries.

A timeout (as you suggested in Slack) could also be a good idea... this isn't supposed to take a long time. But, I question whether whatever check we do after timeout would just suffer from the same issue as what is causing this stalling... it seems like something perhaps might not be properly reflected in the state we are checking to determine if everything is installed.

**Comment by selectedselections** [comment] 2021-03-10 16:18
Hi there @ilyasfoo !

I noticed the issue persisted after I installed WooCommerce from CLI. It took a few tries to get to the Woo settings in wp-admin. I was able to get there after the Store set up flow progressed a little further. So the timeline was like this: 

1. Click set up store and see empty progress bar that doesnt move
2. Install WooCommerce from CLI 
3. Click on Woo settings in wp-admin -> be redirected back to calypso
4. Try the store set up again, see empty progress bar
5. Deactivate all plugins except Woo in CLI
6. This time, the store progress bar made it half way
7. Then, I was able to access the Woo wp-admin settings and the user decided to continue from there.

**Comment by mattsherman** [comment] 2021-03-10 18:00
Thanks for the detailed timeline @selectedselections -- that will help us track things down.

**Comment by mattsherman** [comment] 2021-03-10 18:06
> @cpapazoglou Yes, this is related to Store deprecation. Thank you for creating this issue. However, I'm unable to reproduce this issue with my business site so far.

I just hit this when testing out another PR with a new Business site (I find that re-using sites can make reproducing things more difficult, since the state of things is often slightly different after you start manually trying to put things back in the correct state to reproduce something).

**Comment by mattsherman** [comment] 2021-03-10 23:50
We should also look and ensure that the initial state is loaded/available to us when the page initially renders, or that we are properly waiting for it. That refreshing the page (often) seems to fix the issue seems to suggest that perhaps the state isn't available initially. Just a thought. I can help dig into the code more tomorrow if you don't fix it all up before then, @ilyasfoo!

**Comment by ilyasfoo** [comment] 2021-03-11 11:51
@mattsherman Sorry, I wasn't able to get much into this today, I've only tested this 3 times (3 new sites) and able to reproduce it once. I noticed when the hangup happens, the `install` WPCOM API was not called despite the progress bar started progressing. The console does not show anything either.

>We should also look and ensure that the initial state is loaded/available to us when the page initially renders, or that we are properly waiting for it.

I've tried to copy and diff the whole redux state where it works and didn't, but the diff was too large to look at manually (probably copied at the wrong timing). I'll continue this tomorrow.

**Comment by mattsherman** [comment] 2021-03-11 19:49
@ilyasfoo I have a in-progress PR to improve this issue. I do not believe it fully addresses all possible hangs, but I do think it improves the situation where the hang occurs right at the beginning after clicking "Set up my store!".

I have a suspicion that some of the hanging might be related/caused by #49925, as I did see some lines in my dev console mentioning a redirect to a crowdsignal forms url being blocked during one or two of my tests.

I'll keeping digging/testing!

**Comment by mattsherman** [comment] 2021-03-11 22:06
@ilyasfoo I have went ahead and put #51005 up for review, as I believe that it is worth merging, even if it doesn't fully address the issue.

I think the next step would be to dig into https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/woocommerce/dashboard/required-plugins-install-view.jsx and see if there is obsolete code that can be removed. The state handling (which came over directly from the existing Store code) looks very complicated in there. I think by getting rid of unused paths, we can more easily see if there are scenarios that aren't accounted for, causing the hangs.

I will not get to this until tomorrow morning. So, if you decide to work on anything related to this, please just let me know and post an in-progress PR/description so that I don't step on your toes tomorrow!

**Comment by ilyasfoo** [comment] 2021-03-12 08:27
@mattsherman I have tested #51005 with 5 sites, and could not reproduce this issue 🙌 . As you mentioned however, I don't think it fixed all the issues, since I've noticed that one of the symptoms that it actually fixes is when **the progress bar remains empty** indefinitely. The way I tested this was by nullifying [`fetchPlugins`](https://github.com/Automattic/wp-calypso/blob/b6e84c0404388aa8ca2cf37234186c42dbc0862c/client/state/plugins/installed/actions.js#L538) so that plugin data never loads (inspired by your fix in #51005). Since there are reports that the progress bar had some progress and before stalling, I'm fairly confident that there are other issues at play.

>I have a suspicion that some of the hanging might be related/caused by #49925, as I did see some lines in my dev console mentioning a redirect to a crowdsignal forms url being blocked during one or two of my tests.

I was not able to get this since the bug was not reproduced in all of my 5 tests.

I've pushed a PR #51019 as an interim solution for UX, users should get notified if the setup stalled and be able to contact support to continue. I've also added a track to hopefully assist some debugging. Let me know if this helps!

**Comment by ilyasfoo** [comment] 2021-03-16 01:32
> I think by getting rid of unused paths, we can more easily see if there are scenarios that aren't accounted for, causing the hangs.

@mattsherman Based on my observation, `automatedTransferStatus` had always been `completed` or `null` and `hasPendingAT` was always `false` by the time we've installed a plugin and turned the site into Atomic. Since we're checking the site's Atomic status before showing the WooCommerce installation menu and before accessing the install screen, do you think it's possible to remove the code paths that use them? I'm not 100% if Atomic will always work like this, but it's a huge chunk of logic that could be unnecessary.

**Comment by mattsherman** [comment] 2021-03-16 18:52
> @mattsherman Based on my observation, `automatedTransferStatus` had always been `completed` or `null` and `hasPendingAT` was always `false` by the time we've installed a plugin and turned the site into Atomic. Since we're checking the site's Atomic status before showing the WooCommerce installation menu and before accessing the install screen, do you think it's possible to remove the code paths that use them? I'm not 100% if Atomic will always work like this, but it's a huge chunk of logic that could be unnecessary.

@ilyasfoo 💯 As you say, the way we show this "WooCommerce" menu item now, it doesn't show at all until the site is Atomic. So, I think it is safe and proper to remove checks for Atomic in the installation page. That would be a great simplification to the logic.

**Comment by ilyasfoo** [comment] 2021-03-17 04:06
@mattsherman I did more tests and found out the transfer statuses `inquiring` and `start` was also in the mix. I was only able to test `start`, which still result in a successful setup, though our setup code does not handle and results in `NaN` for progress (follow-up PR https://github.com/Automattic/wp-calypso/pull/51128). So far it's hard to test the whole flow for all cases to be confident making the change, which is a bummer.

**Comment by simison** [comment] 2021-03-24 12:42
@ilyasfoo @mattsherman what are good next steps for addressing the issue discussed above?

**Comment by mattsherman** [comment] 2021-03-24 19:13
@ilyasfoo @simison Looking at the recently added `calypso_woocommerce_setup_timeout` Tracks event, and the `working_on` property, almost all of the timeouts are occurring when installing the `woocommerce` plugin (roughly 10 a day). Also, almost all timeouts occur when the `engine_state` is in the `INSTALLING` state, though there are a handful in the `ACTIVATING` and `INITIALIZING` states.

@ilyasfoo Can you think of any further things we could log to help get to the bottom of why this is timing out? Also, do we have any Tracks event available to us to know how many setups are succeeding? It would be good to know how common this failure is.

I'm on Isotope porter duty this week and AFK next week, so unfortunately I can't dig deeply into this right now.

/cc @becdetat

**Comment by ilyasfoo** [comment] 2021-03-25 10:30
@mattsherman 

>Can you think of any further things we could log to help get to the bottom of why this is timing out?

On the top of my head, I think of logging the list of installed & activated plugins, since that might have something to do with a support case mentioned by selectedselections. I'm thinking we might need to use logstash here to be able to view the details of each case.

>Also, do we have any Tracks event available to us to know how many setups are succeeding? It would be good to know how common this failure is.

For now, we do have a rough approximation by observing trend for `calypso_woocommerce_setup_timeout` vs `calypso_woocommerce_dashboard_action_click`. Looking at the numbers our setup stall rate is around 10% - 15%.

Since there are so many variances of setup states that ended up stalling, I'm considering to increase the timeout threshold by 15 seconds for plugin installation & activation, as I suspect there might still be cases where setup was not actually stalled, but slow.

**Comment by ilyasfoo** [comment] 2021-03-25 10:30
@mattsherman I have a [WIP PR](https://github.com/Automattic/wp-calypso/pull/51394) is here for adding more debug info. 

Since WooCommerce plugin makes up the most of the timeout cases, I'll be looking to see if there are more info to be captured for plugin status from `client/state/plugins/installed` tomorrow.

**Comment by mattsherman** [comment] 2021-03-25 19:04
> Since there are so many variances of setup states that ended up stalling, I'm considering to increase the timeout threshold by 15 seconds for plugin installation & activation, as I suspect there might still be cases where setup was not actually stalled, but slow.

That's a good idea.

**Comment by mattsherman** [comment] 2021-03-25 19:04
> @mattsherman I have a [WIP PR](https://github.com/Automattic/wp-calypso/pull/51394) is here for adding more debug info.
> 
> Since WooCommerce plugin makes up the most of the timeout cases, I'll be looking to see if there are more info to be captured for plugin status from `client/state/plugins/installed` tomorrow.

Great. Thanks for digging into this more!

**Comment by ilyasfoo** [comment] 2021-04-01 02:31
#51394 is merged, I'll be monitoring logstash logs with the filter `feature: calypso_client and message: "woocommerce setup timeout"`. Logs with timestamp starting from 1st April 2AM should be logged by users.

**Comment by ilyasfoo** [comment] 2021-04-13 05:50
Latest findings
-----
I have been looking at logstash and tracks data from 1st - 12th April. In total, 29 hangups occurred during this period. The good news is the number of timeouts is trending downwards since changing the time limit to 30 seconds for plugin installation. This means that in some cases, plugin installation takes more time to finish. We could potentially increase this time limit some more to be sure that we're not catching false positives.

For setup hangups, I think that there may be multiple issues at play. I've identified 3 different categories of hangup:

**1. Hangup during installing plugins**
```js
{
  "state": {
    "workingOn": "woocommerce",
    "engineState": "INSTALLING"
  },
  "pluginsStatus": {
    "woocommerce": { "status": "inProgress" }
  }
}
```
This takes the cake for the most number of hangups. For the most part, this happens during WooCommerce plugin installation. This is also where I would suspect false positives that may still occur since the duration of plugin installation is not as predictable.

**2. Hangup between installing plugins**
```js
{
  "state": {
    "workingOn": "",
    "engineState": "INSTALLING"
  },
  "pluginsStatus": {
    "woocommerce": { "status": "completed" }
  }
}
```

There were 7 cases where the hangup occurred between after WooCommerce plugin successful install and the next plugin install. By manually tracing the [code path](https://github.com/Automattic/wp-calypso/blob/f349803f0eb5e695b138da15baac8aab31b9d65d/client/my-sites/woocommerce/dashboard/required-plugins-install-view.jsx#L352), theoretically `workingOn` state should never be empty, as the engine is supposed to start processing the next plugin in `toInstall`.

**3. Hangup while waiting for plugin list to load**
```js
{
  "state": {
    "workingOn": "WAITING_FOR_PLUGIN_LIST_FROM_SITE",
    "engineState": "INITIALIZING"
  },
  "pluginsStatus": false,
  "plugins": []
}
```
This is a peculiar case that warrants more investigation.`WAITING_FOR_PLUGIN_LIST_FROM_SITE` value in `workingOn` should not be possible since we're [checking the plugin list](https://github.com/Automattic/wp-calypso/blob/7305058b3afba928d1b377c19443fb08023e7281/client/my-sites/woocommerce/main.jsx#L31) load status via [`isLoaded`](https://github.com/Automattic/wp-calypso/blob/f349803f0eb5e695b138da15baac8aab31b9d65d/client/state/plugins/installed/selectors.js#L53) selector before rendering our component. The fact that this occurs signals an issue with either our plugin list fetching or the selector's logic.

Other observations
-----
- Based on the 29 logstash records, not a single plugin is in all of the sites affected except for Jetpack. I have tried to install plugins with at least 10 installs from all the sites in a new site and did not get to reproduce Woo setup hangup. Based on this, I think we can rule out the issue of setup hangup being dependant on having a specific/combination of plugins.
- I have tried to look for any relevant logs for plugin install in calypso. Suspiciously, both the `calypso_plugin_installed_error` and `calypso_plugin_installed_success` event does not show WooCommerce plugin the whole period, even with so many successful installs. I think our logging might be flawed there.
- It seems a site's atomic transfer status is not relevant to all hangups.

Next steps
------
- Add a `destroyTimeoutTimer` immediately after a plugin is [found](https://github.com/Automattic/wp-calypso/blob/1f52c6f547740e9677a3a5d08bc109555ba860de/client/my-sites/woocommerce/dashboard/required-plugins-install-view.jsx#L351). This would hopefully eliminate category #2.
- In order to reduce false positives further, I think increasing the timeout for plugin installation to one minute should be sufficient.
- Start debugging as close to the WPCOM API as possible. I'm thinking to add a logstash log around `install` and `activate` [here](https://github.com/Automattic/wp-calypso/blob/update/1438-account-creation-connection-flow-copy-update/packages/wpcom.js/src/lib/site.plugin.js).
- Look into how our plugin list is obtained, its fetching process, and check if it's possible that the state is not accurate by the time we load our `RequiredPluginsInstallView` component.

Other things to consider
------
- Fix logging around calypso's plugin installation.
- @mattsherman has mentioned that we should retry the setup process at least once before suggesting users to contact support. Since we've got this far and have not got to the bottom of the issue, I think this would be worthwhile.

**Comment by mattsherman** [comment] 2021-04-13 20:22
Excellent investigation @ilyasfoo ! 🙌 

> There were 7 cases where the hangup occurred between after WooCommerce plugin successful install and the next plugin install. By manually tracing the [code path](https://github.com/Automattic/wp-calypso/blob/f349803f0eb5e695b138da15baac8aab31b9d65d/client/my-sites/woocommerce/dashboard/required-plugins-install-view.jsx#L352), theoretically `workingOn` state should never be empty, as the engine is supposed to start processing the next plugin in `toInstall`.

I don't follow this. The code you link to shows `workingOn` set to empty. So, isn't that the exact state we are seeing? This code is very difficult to follow.

> Add a destroyTimeoutTimer immediately after a plugin is found. This would hopefully eliminate category #2.

Ah, I see... yeah, I think that would be a great improvement.

> This is a peculiar case that warrants more investigation.WAITING_FOR_PLUGIN_LIST_FROM_SITE value in workingOn should not be possible since we're checking the plugin list load status via isLoaded selector before rendering our component. The fact that this occurs signals an issue with either our plugin list fetching or the selector's logic.

Hmm... I haven't traced through everything, but `isLoaded` actually doesn't seem to really tell us whether the plugin list has been loaded. Just whether it is currently requesting the list. So, it seems ripe for some oddness.

> I have tried to look for any relevant logs for plugin install in calypso. Suspiciously, both the calypso_plugin_installed_error and calypso_plugin_installed_success event does not show WooCommerce plugin the whole period, even with so many successful installs. I think our logging might be flawed there.

Where are these events fired? I did not see any results when searching the repo for those strings.

> In order to reduce false positives further, I think increasing the timeout for plugin installation to one minute should be sufficient.

We should definitely do this. It doesn't have a downside, other than a user waiting a bit longer in cases where it is already either (1) slow, or (2) bound to fail regardless of how long we wait.

> Start debugging as close to the WPCOM API as possible. I'm thinking to add a logstash log around install and activate here.

That would be good. Do we log on the server-side in the API as well?

> Look into how our plugin list is obtained, its fetching process, and check if it's possible that the state is not accurate by the time we load our RequiredPluginsInstallView component.

Definitely.

> @mattsherman has mentioned that we should retry the setup process at least once before suggesting users to contact support. Since we've got this far and have not got to the bottom of the issue, I think this would be worthwhile.

I wonder if we could "easily" just re-trigger the entire process. Maybe by forcing a refresh or redirecting or something equally heavy-handed. That way, we could retry without having to rework the code.

**Comment by mattsherman** [comment] 2021-04-13 20:25
> I have been looking at logstash and tracks data from 1st - 12th April. In total, 29 hangups occurred during this period.

Do we have any idea what users did immediately after this? I'd be curious if they contacted support or if they tried again themselves or if they just gave up. No need to dig deeply into this if the answer isn't easily obtained... just curious!

**Comment by ilyasfoo** [comment] 2021-04-14 05:41
Thanks, @mattsherman!

>I don't follow this. The code you link to shows workingOn set to empty. So, isn't that the exact state we are seeing? This code is very difficult to follow.

Sorry, my statement was inaccurate. What I meant is because the `workingOn` is empty during timeout, it means the timeout must have occurred between the engine loop interval because otherwise, it would contain a plugin's name. The loop is only 17 milliseconds apart, so I thought it would be very unlikely that it'd expire during that small window. 

Anyway, this was my mistake to miss adding a reset after each plugin is found. A fix should be quick

>Where are these events fired? I did not see any results when searching the repo for those strings.

It's logged via a [helper](https://github.com/Automattic/wp-calypso/blob/22f4aa4e1c951fa8e2ea155df283a28677cfea47/client/state/plugins/installed/actions.js#L385-L390) which prepends the track name with `calypso_plugin_installed`.

>I wonder if we could "easily" just re-trigger the entire process. Maybe by forcing a refresh or redirecting or something equally heavy-handed. That way, we could retry without having to rework the code.

I'm thinking we could have a refresh with a GET param `retry=1` to indicate the second try. The user wouldn't have to click on "Set up" again, it'll run the setup straightaway. If it fails again, it'll just do the usual timeout. This should be a minimal change.

>Do we have any idea what users did immediately after this? I'd be curious if they contacted support or if they tried again themselves or if they just gave up. No need to dig deeply into this if the answer isn't easily obtained... just curious!

Unfortunately, we did not track this, so there's no easy way to look at the funnel.. I think adding an additional track for clicking the contact support button would be helpful (even for the long run, since I don't think this kind of issue will disappear entirely).

On users retrying on their own, I'm not sure how the track funnelling works, but would it be possible to check a user that does `calypso_woocommerce_setup_timeout` twice? If that's possible that might be a viable proxy to retries

**Comment by ilyasfoo** [comment] 2021-04-14 09:43
I've [posted a PR](https://github.com/Automattic/wp-calypso/pull/51932) is up to address 3 things:
- Fix unintended timeout occurring between engine intervals by destroying the timeout after finding the plugin present.
- Increasing the plugin installation and activation time limit to 60 seconds.
- Add a new track `calypso_woocommerce_setup_contact_support` to better understand user behaviour after experiencing setup timeout or failure.

[Another PR](https://github.com/Automattic/wp-calypso/pull/51935) to address issue with tracking `calypso_plugin_installed_success` and `calypso_plugin_installed_error`

**Comment by ilyasfoo** [comment] 2021-04-19 01:47
Both PRs mentioned above was deployed around 16th April 3:00 AM UTC+0

**Comment by ilyasfoo** [comment] 2023-05-31 13:39
I think this can be closed since it's old. Please reopen if necessary.

**Closed as completed by ilyasfoo** 2023-05-31 13:39 UTC
Labels: Bug, Store, Plans: eCommerce, WooCommerce
