### ISSUE TITLE
Can't hide Fiverr Logo Maker ad on My Home

### ISSUE THREAD

**Issue by wpshellbelle** [Automattic/wp-calypso#74590] opened 2023-03-17 18:21 UTC
### Quick summary

From _My Site → My Home_, users are presented several advertisements and prompts to help them set up their site. All of these allow you to hide them (for 1 day - forever). The ad that says "Grab a professionally designed logo in 10 minutes" can't be hidden. 

### Steps to reproduce

1. Head to _My Site → My Home_
2. View "Grab a professionally designed logo in 10 minutes"  ad 
3. Select option to hide ad/prompt
4. See a loading screen - ad is not hidden 

### What you expected to happen

I expected to be able to hide "Grab a professionally designed logo in 10 minutes", Fiverr Logo Maker ad

### What actually happened

Can't dismiss or hide "Grab a professionally designed logo in 10 minutes" from **My Home**

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by wpshellbelle** [comment] 2023-03-17 18:22
User reported at 41226049-hc
User wants us to follow up at 6051457-zen

**Comment by cuemarie** [comment] 2023-03-17 22:00
📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/73688

**Closed as completed by cuemarie** 2023-03-17 22:00 UTC
Labels: Bug, [Pri] High, [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered
