### ISSUE TITLE
Instagram: There was a problem exchanging an Instagram access token for a long lived one.

### ISSUE THREAD

**Issue by kingsleyinfo** [Automattic/wp-calypso#74616] opened 2023-03-19 13:48 UTC
### Quick summary

Unable to authorize new Instagram connections via Tools > Marketing > Connections

### Steps to reproduce

1. Go to tools on an atomic or simple site
2. Click on Tools > Marketing > Connections tab
3. Click on connect Instagram.
4. Follow the on-screen prompt.

![2023-03-19 14 40 04](https://user-images.githubusercontent.com/12503321/226178988-772ec772-1a7d-4987-a673-9570dceddf64.gif)

### What you expected to happen

The connection should be completed

### What actually happened

There was an error
![kayshot-2023-03-19-14 41 51](https://user-images.githubusercontent.com/12503321/226179051-2f3a3fa8-4a87-485e-ac6a-d4ffa9d104ef.jpg)

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Appears there was a similar issue from 2 years ago:
https://github.com/Automattic/jetpack/issues/20445

**Comment by kingsleyinfo** [comment] 2023-03-19 13:51
Ticket: 6051977-zd-woothemes

**Comment by jeherve** [comment] 2023-03-20 09:21
Closing as duplicate of https://github.com/Automattic/jetpack/issues/20445

**Closed as completed by jeherve** 2023-03-20 09:21 UTC
Labels: Bug, [Pri] High, [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered
