### ISSUE TITLE
White screen when trying to open a post or page

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#67276] opened 2022-09-01 16:07 UTC
### Quick summary

We have had a few reports of people trying to edit a post/page or draft and seeing a blank white screen. We were able to see the same on the customer sites as HEs, but cannot yet reproduce it. All simple sites so far.

At least one of the posts had only the following: image block, paragraph blocks, list block. Nothing seemed odd as far as Gutenberg content.

### Steps to reproduce

1. Start at My Site > Posts
2. Open a draft post, though it seems to be very specific ones

### What you expected to happen

For the editor to open

### What actually happened

A blank white screen

### Context

Three customer reports
30236742-hc
33692594-hc
5522305-zen

### Platform (Simple, Atomic, or both?)

Simple

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

HEs helped  customers resolve the issue by going through revisions, in some cases editing the content on their behalf. Another option one customer used was to open the post in classic editor and copy the content out to a new post.

**Comment by ariel-maidana** [comment] 2022-09-01 16:09
Another case: 5524512-zd-woothemes

**Comment by rootjosh** [comment] 2022-09-01 16:12
Multiple reports in the forums. Here are three (can add more if needed):

https://wordpress.com/forums/topic/white-screen-on-death/?view=all
https://wordpress.com/forums/topic/blank-screen-of-death-trying-to-edit-draft-posts/?view=all
https://wordpress.com/forums/topic/blank-page-when-editing-portfolio-project/?view=all

**Comment by jamiepalatnik** [comment] 2022-09-01 16:32
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was not able to replicate this on my own test site or on several sites I checked from the user reports, but it sounds like some of these users were already helped with a workaround.
- I'm going to go ahead and mark this triaged to investigate further though because of the number of user reports that were quickly gathered today, and because of the severity of the issue for the users that are affected.

📌 ACTIONS
- Await author feedback
- Marked as Triaged for Quality Squad review

📌 Message to Author
- Can you share any examples where the white screen is still appearing to help investigate this? Thanks!

**Comment by jerrysarcastic** [comment] 2022-09-02 00:25
One of our forums site owners has mentioned that the issue is limited to specific blog posts, which they mention here:  https://wordpress.com/forums/topic/blank-screen-of-death-trying-to-edit-draft-posts/?view=all#post-3859747

I've asked them for more info, but I spot-checked these and was able to load them in Gutenberg without issue.

**Comment by Babylon1999** [comment] 2022-09-05 17:13
Another case here zd-5532540


I shared more browser troubleshooting steps and asked for their browser details.

**Comment by danielbachhuber** [comment] 2023-06-30 12:34
Closing this issue because it's almost a year old, doesn't have any recent reports, and doesn't have specific steps to reproduce.

**Closed as not planned by danielbachhuber** 2023-06-30 12:34 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Simple
