### ISSUE TITLE
Video Block: Videos Not Loading on Mobile Chrome

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#59867] opened 2022-01-07 18:10 UTC
### Quick summary

Some Video blocks aren't loading when you access them through Chrome on mobile.

### Steps to reproduce

1. Create a new page
2. Add some Video blocks on it
3. Check the page on mobile, using Chrome

### What you expected to happen

For the videos to load.

### What actually happened

Some videos won't load, randomly.

### Context

From chat: 33247054-hc

When testing on iOs, this is what happens on Chrome (first one isn't loading, while the second does):

![VideosNotLoading_Chrome](https://user-images.githubusercontent.com/16104522/148587467-5c8408c9-abda-44f9-aef8-b4fa9458ecce.jpg)

While it loads properly on Safari:

![VideosNotLoading_Safari](https://user-images.githubusercontent.com/16104522/148587472-de0dda87-f5fd-4ea4-b13a-74c3660b9d7b.jpeg)

### Reproducibility

Consistent

### Available workarounds?

Yes, difficult to implement

### Workaround details

You can use the _"Insert from URL"_ option on the Video block, and get the video's URL from the media library. That loads a different video player that works consistently on mobile Chrome.

**Comment by formosattic** [comment] 2022-01-25 06:23
Able to reproduce, can confirm that the first Video block won't play at all on iOS and Chrome. In my case, the Video block was just a black box.

| iOS & Chrome (What happened)  | iOS & Safari (Expected display) |
| ------------- | ------------- |
| ![image1](https://user-images.githubusercontent.com/15944096/150922122-992afa7f-7c21-4160-8cad-c84e27594863.png) | ![image3](https://user-images.githubusercontent.com/15944096/150922275-634746e8-c519-4c00-8806-59089c068832.png) |

**Comment by lupus2k** [comment] 2023-01-11 20:06
I close it because surely it was already solved since we have not been able to reproduce it.
Slack discussion: p1673410853298799/1673049033.360749-slack-C01LXBU1N21

**Closed as completed by lupus2k** 2023-01-11 20:06 UTC
Labels: Bug, [Pri] Normal
