### ISSUE TITLE
Onboarding checklist on atomic sites: Update your homepage

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#52705] opened 2021-05-10 07:51 UTC
### Task Details

The link for "Update your homepage" currently links to `/wp-admin/edit.php` without a page selected.
It should link to the editor for the homepage in calypso i.e.
`wordpress.com/page/_YOUR_SITE_/_HOMEPAGE_ID_`

Also the logic that detects when the task should be set to completed doesn't seem to be working. Once the homepage has been edited, the task should be marked as completed.

### How to test

in the wpcom codebase, in `wp-content/lib/onboarding-checklist/functions.php`, modify the `is_blog_eligible_for_dotcom_checklist` to return `true`;

Part of #50523

**Comment by roo2** [comment] 2021-05-11 02:17
We think that for keeping track of whether the homepage has been updated, we will need to (intercept the `save` event on the atomic site) and sync a flag from the atomic site to the cloud site.

We should already have access to the homepage ID

**Comment by roo2** [comment] 2021-05-13 02:41
the `save_post_page` and `update_option_page_on_front` can both trigger the task to be marked as complete

**Comment by roo2** [comment] 2021-05-19 03:32
So apart from this bug p9dueE-2SE-p2 with jetpack syncing the homepage setting, changing the homepage marks this task as completed ✅

**Comment by autumnfjeld** [comment] 2021-05-19 05:18
@deBhal My testing:

* I created a site with a business plan
* then installed a plugin (so the site becomes atomic)
* went to My Home site checklist -> Update your Home page --> Edit home page  and landed in the editor (as expected)
* went back to My Home
* ⛔  saw that Update your Home page was not checked off

Also an aside: @roo2  thought that something in the atomic sync could be flaky, sometimes syncing properly and sometimes not and as such some of these bugs might be reproducible some of the time, but not others.

**Comment by deBhal** [comment] 2021-06-04 04:03
D62239-code resolves the `save_post_page` case by listening for the `jetpack_post_saved` action and forwarding the `page` changes to the onboarding checklist.

I'm marking this complete for now, assuming that the Jetpack Crew have p9dueE-2SE-p2 and we can re-open it if it looks like we need to look into making that sync more consistent.

**Closed as completed by deBhal** 2021-06-04 04:03 UTC
Labels: [Status] In Progress, Task, [Size] L, [Feature] My Home, Triaged, Simple/Atomic Parity, My Home Pod
