### ISSUE TITLE
Free theme titled "Blockbase" requires an upgrade to the Business plan to use.

### ISSUE THREAD

**Issue by kingsleyinfo** [Automattic/wp-calypso#73106] opened 2023-02-08 15:29 UTC
### Quick summary

The free theme titled "Blockbase" is requesting for an upgrade to the Business plan before it can be used. 
Since this theme is marked as free in Calypso, it should be free to use on any plan. 

A user on the premium plan cannot use this theme, even if they were previously able to use the theme on their free site.

### Steps to reproduce

1. On a site with the Premium plan
2. Go to Appearance > Themes 
3. Search for "blockbase" and filter by Business category
4. Select the 3 dots and click on info
5. You'll see a notice requiring an upgrade

https://user-images.githubusercontent.com/12503321/217574546-2ffb5c58-f6ee-4f34-b88f-b1b48ba0e0fb.mp4

### What you expected to happen

Users on the free - Premium plan should be able to click on activate after clicking on the 3 dots.
I should also be able to activate the theme if I click on info.

### What actually happened

There is a notice to upgrade to the Business plan to make use of the theme.
Clicking on the notice opens the cart with the Business plan upgrade

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by kingsleyinfo** [comment] 2023-02-08 15:30
Issue was on chat. Now moved to ticket ZD-5940291

**Comment by youbrokesomething** [comment] 2023-02-08 16:48
Blockbase is showing up in Business, Link in Bio, Portfolio, and Store only if you search for it. It doesn't have a call to action to upgrade, but the activate option will not display on free sites. I'm guessing Blockbase isn't intended to display in search results.

**Comment by taipeicoder** [comment] 2023-06-29 09:18
As discussed in p1675875176541569-slack-C048CUFRGFQ:

Blockbase is delisted in the theme showcase. However, the dotorg version of Blockbase will still show when searching for it. The theme no longer shows as "Free" but rather "Community", with a tooltip saying that it can be installed on sites with Business plans and above.

![Screenshot 2023-06-29 at 5 15 32 PM](https://github.com/Automattic/wp-calypso/assets/797888/c186fc49-4679-442c-8b5f-8b8ce1f6985e)

Since this is expected behavior, I'll be closing this issue. Let me know if you have further questions!

**Closed as completed by taipeicoder** 2023-06-29 09:18 UTC
Labels: Bug, [Pri] Normal, [Platform] Simple
