### ISSUE TITLE
Adding a Youtube video into a Video widget

### ISSUE THREAD

**Issue by maciejpilarski** [Automattic/wp-calypso#25565] opened 2018-06-18 16:06 UTC
Adding a Youtube video into a Video widget does not work, an error message about the video format is displayed.

#### Steps to reproduce
1. Starting at URL: https://adelialauren.wordpress.com/wp-admin/widgets.php
2. Select the video widget and click on the add Video button
3. Select Insert from URL option
4. Paste the URL of the YouTube video

#### What I expected
Ad a YouTube video from URL

#### What happened instead
An error message about the video format is displayed.

#### Screenshot / Video
https://cld.wthms.co/KtR2ys

#### Context / Source

 #user-report if applicable.

**Comment by KokkieH** [comment] 2018-06-21 05:37
Duplicate of #25195

**Closed by KokkieH** 2018-06-21 05:37 UTC
Labels: Editor, [Type] Bug
