### ISSUE TITLE
Editor: [code] and [sourcecode] shortcode content loses all indentation in calypso editor

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#1023] opened 2015-11-30 06:54 UTC
What I Did: Using the calypso editor, switched to HTML mode, entered some source code using [code] or [sourcecode] shortcodes, switched back to visual editor

What I Expected: indentation (spaces/tabs) to remain in source code, as per wp-admin editor

![wp-admin](https://cloud.githubusercontent.com/assets/128826/11465248/cbd70ce0-9782-11e5-95ea-6e66c57062cd.gif)

What Actually Happened: All indentation was lost

![calypso](https://cloud.githubusercontent.com/assets/128826/11465252/d7c5a7fa-9782-11e5-896d-973a7cae63a9.gif)

Solution suggested by @aduth:

The solution here may be to simply include/port the [SyntaxHighlighter Evolved TinyMCE plugin](https://github.com/Viper007Bond/syntaxhighlighter/blob/master/syntaxhighlighter_mce-4.js), which handles the `<pre>` tag wrapping. (cc @azaozz)

**Comment by mmcelreath** [comment] 2015-12-09 18:31
I noticed the same behavior. Is there a workaround until it gets fixed?

**Comment by aduth** [comment] 2015-12-09 18:34
@mmcelreath : Here's the quoted text that was missing from the original post, detailing the current workaround:

>A workaround you may consider using is the `<pre>` tag prior to the shortcode, as this appears to keep the formatting intact.
>
>```html
><pre>[code]
>// Formatting intact
>[/code]</pre>
>```

**Comment by alisterscott** [comment] 2015-12-09 20:40
@aduth I couldn't get the workaround to work, it simply shows the [code] tag instead of rendering code.
I still use wp-admin :(

**Comment by aduth** [comment] 2015-12-11 13:10
>@aduth I couldn't get the workaround to work, it simply shows the [code] tag instead of rendering code.
I still use wp-admin :(

Are you adding the `<pre>` tag while in the HTML tab?

![pre](https://cloud.githubusercontent.com/assets/1779930/11744461/9b284e4c-9fde-11e5-9313-7c62c2c71a05.gif)

**Comment by alisterscott** [comment] 2015-12-11 21:50
The issue I have found with the workaround is the closing </pre> tag seems to get lost upon preview/display, so all following text appears pre-formatted.

Example: 

    Test here 
    <pre>[sourcecode language="javascript"]
        test.it('shows a non-empty quote', function() {
            var ralphSaysPage = new RalphSaysPage(driver, true);
            ralphSaysPage.quoteTextDisplayed().then(function(text) {
                assert.notEqual(text, '', 'Quote is empty');
            });
        });
    [/sourcecode]</pre> 
    Finish here. <em>Can't work out why this isn't displaying right?</em>

Displays as:

![preformatted](https://cloud.githubusercontent.com/assets/128826/11756341/f6f462d0-a0a4-11e5-98ef-ba0483f527a1.png)

**Comment by aduth** [comment] 2015-12-11 21:55
Thanks @alisterscott , I can confirm there's an issue since the `[sourcecode]` shortcode itself converts into a `<pre>` tag. There must be some confusion with the nested tags, as while it outputs two opening tags, there's only a single closing tag. I'll spend some more time working through the resolution, which is to bring in the `syntaxhighlighter` TinyMCE plugin. There's a work-in-progress branch at `add/1023-editor-sourcecode-indenting`, but I'm currently working through a problem with the auto-injected wrapping `<pre>` not being removed prior to save or transitioning from Visual to HTML tabs.

**Closed** 2015-12-18 13:34 UTC
Labels: Editor, [Pri] Normal, [Type] Bug
