### ISSUE TITLE
Reader: fix overflow display bug on Firefox

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#986] opened 2015-11-29 17:14 UTC
Steps to reproduce:

1. Publish a new post including a table with images in two 50% width colums
1. View the post in the Reader

<strong>Result:</strong> the table is not constrained to the content area when the post is viewed in the Reader using Firefox.

![screen shot 2015-11-29 at sun nov 29 12 13 45 pm](https://cloud.githubusercontent.com/assets/1119271/11458670/a62d13a4-9692-11e5-8bcf-77521447fbc3.png)
<sup>Seen at https://wordpress.com/read/post/feed/38371659/875724951 using Firefox 42.0 on Mac OS X 10.10.5</sup>

Example HTML

```
<table>
<tbody>
<tr>
<td valign="top" width="50%">
<h4>Control
<a href="https://design5279.files.wordpress.com/2015/11/img_0860.jpg"><img class="alignnone wp-image-9709 size-large" src="https://design5279.files.wordpress.com/2015/11/img_0860.jpg?w=660" alt="gapps-control" width="660" height="62" /></a></h4>
</td>
<td valign="top" width="50%">
<h4>Variation <a href="https://design5279.files.wordpress.com/2015/11/img_4652.jpg"><img class="alignnone wp-image-9716 size-large" src="https://design5279.files.wordpress.com/2015/11/img_4652.jpg?w=660" alt="gapps-variation" width="660" height="68" /></a></h4>
</td>
</tr>
</tbody>
</table>
```

/hat tip @stephanethomas for the original report

**Comment by alexjgustafson** [comment] 2016-03-17 13:07
Looks like this is fixed from the Mozilla end, but won't be available to users until Firefox 46. ([#](https://bugzilla.mozilla.org/show_bug.cgi?id=975632#c37)). 

FF46 is due out in April. ([#](https://blog.mozilla.org/futurereleases/2016/02/04/update-on-2016-firefox-release-schedule/))

Viewing in Firefox Developer Edition, the problem is gone:
![table-in-ffdev](https://cloud.githubusercontent.com/assets/933450/13846677/42cba252-ec1f-11e5-83c4-8d5450f99cec.png)

**Comment by lancewillett** [comment] 2016-06-02 18:33
Closing as noted above, resolved in newer Firefox versions.

**Closed by lancewillett** 2016-06-02 18:33 UTC
Labels: Reader, [Type] Bug
