### ISSUE TITLE
Site shows Coming Soon but is Public, cannot change the settings to Coming Soon

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#60561] opened 2022-01-27 16:59 UTC
### Quick summary

This simple site is public but is showing as Coming Soon in Calypso. If you try to change the Privacy settings for the site to Coming Soon, it immediately reverts to Public again.

![CleanShot 2022-01-27 at 16 52 46](https://user-images.githubusercontent.com/51966986/151406577-7f1d7e0b-5d7d-4789-a247-4b8eb2821f1b.gif)

![CleanShot 2022-01-27 at 16 53 59](https://user-images.githubusercontent.com/51966986/151406598-00fbe9d4-65dd-4443-89a3-6e821e505926.gif)

### Steps to reproduce

1. Click on Settings
2. Select Coming Soon for privacy setting
3. Click Save

### What you expected to happen

The site should switch to Coming Soon

### What actually happened

The site privacy settings don't change and the site remains Public

### Context

4725775-zen

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

No but the platform is still usable

**Comment by essleeung** [comment] 2022-02-01 09:17
Seems to be the same as this issue: https://github.com/Automattic/wp-calypso/issues/53626

**Comment by Greatdane** [comment] 2022-02-24 08:32
Closing: Duplicate of https://github.com/Automattic/wp-calypso/issues/53626

**Closed as completed by Greatdane** 2022-02-24 08:32 UTC
Labels: Bug
