### ISSUE TITLE
Missing link to attachment page from CoBlocks/Masonry block

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#35925] opened 2019-09-02 03:00 UTC
The block allows you to add a link to images' attachment page.

<img width="982" alt="Screen Shot 2019-09-02 at 03 45 55" src="https://user-images.githubusercontent.com/908665/64087623-bed37280-cd35-11e9-8fc7-120008c7d9fc.png">

However, on the front of a WP.com site, the link is missing.

<img width="982" alt="Screen Shot 2019-09-02 at 03 46 42" src="https://user-images.githubusercontent.com/908665/64087672-f510f200-cd35-11e9-8641-4319d0e3d170.png">

With a self-hosted site, the link to the attachment page is present.

<img width="979" alt="Screen Shot 2019-09-02 at 03 48 14" src="https://user-images.githubusercontent.com/908665/64087709-1c67bf00-cd36-11e9-9a53-d8e82cca7775.png">

**Comment by iamtakashi** [comment] 2019-09-02 03:05
@kwight We're thinking to release a template using Masonry block on Thursday 5th. If this bug can be resolved by then, it'd be amazing :)

**Comment by jeraldjuice** [comment] 2019-09-05 16:06
So, this is happening because the `link` attribute doesn't exist on the image objects on the frontend view of the site. It's the same reason why the Link To: Media option works - because that uses the `url` property on the image, which does exist on the frontend, whereas the Link To: Attachment option uses the `link` property. This also doesn't work for the other gallery-type Coblocks block.

That data I think comes from `getMedia()` from core data. Taking a look into that as a possible direction for a fix for this.

**Comment by kwight** [comment] 2019-09-05 19:46
This sounds like our previous KSES issues: maybe `data-link` is getting stripped by our aggressive KSES rules? Odd though, because it looks like `data-link` is whitelisted. Maybe it's something to do with `img` being contained in a `figure` (although, at a quick glance, this doesn't look like it should be a problem either).

**Comment by kwight** [comment] 2019-09-27 23:00
Any luck on this @jeraldjuice ? If there's a diff, could you mention it here ? Thanks!

**Comment by kwight** [comment] 2019-10-04 21:11
I took a look at this today. From what I can tell, this is only happening with Gutenframe, and isn't an issue in `wp-admin`, pointing to a problem with the media modal integration in `calypso-iframe-bridge-server.js`. As @jeraldjuice mentions, the `image.link` property on the gallery images isn't present. I thought this might mean that a) the `coblocks/gallery-block` block needs to be added to `imageBlocks` in `handleUpdateImageBlocks()`, and b) the `link` property needs to be handled further down in `updateMultipleImagesBlock()`, but I was unable to get it working.

**Comment by kwight** [comment] 2019-10-11 18:33
Possibly related: https://github.com/godaddy/coblocks/issues/983

**Comment by donalirl** [comment] 2019-12-05 02:07
I confirmed the link is missing when you select the image from Media Library. The link is present when select the image by Media Upload.

Test page: https://wpdoc20170704.com/masonry-clicks/

Seen at #2538791-zen

**Comment by kristarella** [comment] 2019-12-06 06:00
User advised that @donalirl 's workaround worked, but then they added descriptions to the images and the links went away again.

**Comment by kristarella** [comment] 2020-01-28 04:12
The Masonry block now has a lightbox option, which when disabled allows the Link To settings to appear:

![image](https://user-images.githubusercontent.com/2031017/73234922-50a9b380-41e0-11ea-9546-695bff204370.png)

However, when Attachment page is chosen, it does nothing. As noted above, Media File works.

**Comment by kristarella** [comment] 2020-01-28 05:24
Oh wow, I just found that this is more complicated

Found this when investigating 2661553-zen

Issues:
- Link To setting is only visible when Lightbox option (screenshot above) is off, but the link settings are still active when lightbox is on
- when Link to is "attachment page" it does nothing at all when lightbox is off, when lightbox is on the lightbox behaves as expected
- when Link to is "media file" and "open in new tab", it behaves as expected with lightbox off, with lightbox on both the lightbox and the new tab with media file open
- when Link to is "media file" it behaves as expected when lightbox is off, with lightbox on the lightbox opens briefly, and then the same tab is directed to the media file
- when there are two masonry galleries on a page, one set to use lightbox, the other no lightbox +  link to attachment page, and the Jetpack carousel is enabled, the carousel activates for gallery with lightbox off, and both the carousel and lightbox activate for the one with lightbox on

**Comment by simison** [comment] 2020-01-28 08:53
☝️ FYI @Automattic/jetpack-crew as well since Carousel was mentioned.

**Comment by WunderBart** [comment] 2020-08-26 13:20
All the issues described above by @iamtakashi and @kristarella seem to be resolved by recent CoBlocks update on Simple sites (https://github.com/Automattic/wp-calypso/issues/45033). AT sites already run the same version, so I'm closing this one.

**Closed by WunderBart** 2020-08-26 13:20 UTC
Labels: [Type] Bug
