### ISSUE TITLE
Scheduled post notifications being sent to readers before post is published

### ISSUE THREAD

**Issue by tavilla61** [Automattic/wp-calypso#91375] opened 2024-06-02 21:31 UTC
### Quick summary

User has experienced a recent change in scheduled post behavior. She has a test email to receive notifications when a scheduled post is published. Her last two posts have notified her of the post before they were actually published. She has another reader who has also told her they're receiving early notifications. 

Site: monicaflash.com
Explorer plan, simple site
Two posts she's referenced: 
* https://wordpress.com/post/monicaflash.com/7125
* https://wordpress.com/post/monicaflash.com/7178

### Steps to reproduce

I tested this on my test site.

1. created a new post and scheduled it to publish in 1 hour
2. I'm subscribed to that blog with another email address
3. Checked email to see if I was notified early, or after the post published.

### What you expected to happen

I expected to be notified early, before the post was published. 

### What actually happened

I wasn't notified early, just when the post went live. 

Still submitting since the user is experiencing the issue multiple times, and I don't see anything in their settings that they've configured incorrectly. 

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by liviopv** [comment] 2024-06-03 13:28
📌 REPRODUCTION RESULTS
- Tested on Simple – Could not reproduce

📌 FINDINGS/SCREENSHOTS/VIDEO
I scheduled a post for tomorrow and did not receive any notification.

After switching the scheduling date for today a few minutes in the future, I got the email notification when the post was published.

📌 ACTIONS
- Closed as could not replicate

**Comment by arinoch** [comment] 2024-06-09 21:17
Reopening this for 8304204-zd-a8c. Also on simple, but was previously tested and couldn't be replicated.

**Comment by liviopv** [comment] 2024-06-10 10:13
@arinoch it's the same situation as @tavilla61 case, where the user seems to be publishing the posts and then scheduling:

![CleanShot 2024-06-10 at 11 08 56@2x](https://github.com/Automattic/wp-calypso/assets/14153300/0f1c9a8c-49ba-4b88-96b4-3eef7857cb4d)

The inconsistent delay between publishing > scheduling makes me confident it's a user error, especially since I couldn't reproduce it. 

Have you been able to reproduce it yourself? What other troubleshooting steps did you take?

I'm closing this again, but please reopen it if you have consistent steps to reproduce or if you see more reports

**Comment by staproehl** [comment] 2024-06-10 17:05
Another report 8309927-zen 

User says 100% sure they did not press publish.

**Comment by kelasante** [comment] 2024-06-13 17:53
> @arinoch it's the same situation as @tavilla61 case, where the user seems to be publishing the posts and then scheduling:

Another case in 8323392-zen. The user mentioned that their Activity log automatically shows the post as published before it was scheduled. An email was sent to their subscribers shortly after with a broken link. Reopening this. Site is a free site with no plugins and uses an FSE theme (Nook). 
<img width="2282" alt="Markup 2024-06-13 at 13 50 41" src="https://github.com/Automattic/wp-calypso/assets/74204272/44cf9b25-302b-4fb3-a7b1-94cc3c8271b9">

**Comment by liviopv** [comment] 2024-06-14 09:07
@kelasante thanks for reopening, there's definitely something going on and the last customer seemed to be willing to engage, so I asked them to repeat the test.

So far, the only evidence that this is not a user error is the fact that the post mentioned in 8323392-zen doesn't have a revision saved for the time it was published, only when it was scheduled. However, the email notifications are being sent before the post is scheduled matching the "Post Published" action in the Activity Log, which confirms the post seems to be already published by the time the user tries to schedule it.

**Comment by annezazu** [comment] 2024-09-03 00:20
Checking in here as this is tagged as being related to the site editor but I'm not seeing additional reports nor any follow up around what happened with this last customer (the customer never responded to the request to replicate). 

I'm going to close this out but let's reopen if it more folks can replicate the issue to get to the bottom of it! In case it's helpful, I also tried to replicate this with a simple site using a block theme and didn't get an early notification.

**Closed as completed by annezazu** 2024-09-03 00:20 UTC
Labels: Bug, [Pri] High, [Closed] Not Reproducible, [Feature] Full Site Editor, Customer report [LEGACY], [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience
