### ISSUE TITLE
No way to show Link Manager/Blogroll links on front end

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#92857] opened 2024-07-21 13:29 UTC
### Quick summary

While this feature was [nixed](https://codex.wordpress.org/Links_Manager) in core way back in 2012, I had a user who changed their old retired theme to a new one and now their links have disappeared from the front end. I tried to find but could not find a way to display those on the front end.

Since this feature is super old but I found p1cV32-Ol-p2 and an average of 14000 users per month still access it, should we build something to help customers use it? So far only one customer has reported it.

### Steps to reproduce

I could see this on customer's site https://peteroo.com here https://peteroo31.wordpress.com/wp-admin/link-manager.php and could not find a way with blocks or shortcode to display these links. Ticket: 8471453-zd-a8c.

### What you expected to happen

Shared already.

### What actually happened

Shared already.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by simison** [comment] 2024-07-31 07:17
Normally the Links menu appears in WP.com when there are more than 10 links added there; so if it disappeared it might have something to do with calypso/wp-admin untangling.

Meanwhile, you could suggest them to use new Blogroll block instead, in which you can manage links directly in the block.

**Comment by retnonindya** [comment] 2024-08-15 07:39
📌 ACTIONS
- Triaged

Mikael has provided context and workaround. I'm going to push this issue to the Untangling team.

**Comment by mmtr** [comment] 2024-11-18 17:08
> Normally the Links menu appears in WP.com when there are more than 10 links added there; so if it disappeared it might have something to do with calypso/wp-admin untangling.

They can still access the link from the "Links > All Links" menu, so I think the issue is that the user is unable to show these links in the frontend of their site. 

This used to be possible with the "Links widget" but it was retired a few years ago in D71188-code:

> The Links widget doesn't work well and is quite cumbersome to use - as it requires creating a “[Blogroll](https://wordpress.com/support/blogroll/#add-new-links)” first. In [our docs](https://wordpress.com/support/blogroll/) we even suggest our users to use Paragraph or List blocks instead:
>
> > However, the Links option has declined in popularity and you may wish to consider other more commonly-used methods to display a blogroll or list of links. Popular methods include:
> >
> > Add a Paragraph block or List block to one of your site’s widget areas or on a new page.
> > Add a Navigation widget to your site’s sidebar or footer.
>
> The proposed change keeps the widget intact for those users who already have it on their sites. Once the widget is removed from the site, it cannot be added back again.
>
> The goal of the change is to steer our users from the old legacy widget to newer blocks (Paragraph or List blocks in this case).

This was done as part of the Legacy Widgets Migration (pdf5j4-4C-p2).

Considering that this is the expected behavior, and that we also now have [a new Blogroll block](https://wordpress.com/support/wordpress-editor/blocks/blogroll-block/) which is suppose to replace this functionality, I'm closing this one out.

**Closed as not planned by mmtr** 2024-11-18 17:08 UTC
Labels: Bug, [Feature] Calypso & wp-admin Navigation, Customer report [LEGACY], [Product] WordPress.com, [Feature Group] Content Management, [Feature] Classic Interface

**Comment by cat-og** [comment] 2024-12-06 01:38
I did run into this same issue recently. While I understand that the widget was depreciated some time ago, the existing links were working until quite recently. Our users were given no indication that these elements on their site would suddenly cease to work. The new blogroll block not only looks quite different with fewer options for customizations, it also leaves current users with no options for existing content. 

The user I spoke with today, a user of over 15 years, has 381 custom links they've been displaying on their site for years, and they're not enthusiastic about manually copying all of those to a new format with more limited display options. 

Is there any shortcode or blogroll import option that we could use to help incorporate the work our users have already put in?
