### ISSUE TITLE
Missing 

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#84825] opened 2023-12-04 15:23 UTC
### Quick summary

The help window does not have a minimum width/height.

### Steps to reproduce

1. Click the "?" at the bottom right
2. Resize the newly open window

### What you expected to happen

The window should have a minimum width and height.

### What actually happened

You can resize the window to a minimum:

<img width="341" alt="image" src="https://github.com/Automattic/wp-calypso/assets/167611/ab80b362-c6a6-416c-9cd0-0032cfc7ff33"> -> <img width="152" alt="image" src="https://github.com/Automattic/wp-calypso/assets/167611/11e0647c-9652-4423-84d9-b58ab8d0dcfd">

### Impact

All

### Available workarounds?

There is no user impact

**Comment by maciejpilarski** [comment] 2023-12-12 23:27
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I don't see any '?' at the bottom right per the provided steps. When clicking on the help center a I do see a minimum size preventing it from getting smaller.
![Markup on 2023-12-13 at 00:22:57](https://github.com/Automattic/wp-calypso/assets/9025643/82982f06-5350-4594-85bb-7d0ce00210d5)

📌 ACTIONS
– Requested author feedback

📌 Message to Author
Hi [zaerl](https://github.com/zaerl)! Please provide more detailed steps on how to reproduce the issue.

**Comment by nightnei** [comment] 2024-09-02 16:19
Also can't reproduce it, maybe it was another window 1 year ago

![Image](https://github.com/user-attachments/assets/2b7ae8a2-584c-48f3-b883-b209cc30cbe8)

I will ping @zaerl in Slack

**Comment by zaerl** [comment] 2024-09-02 16:49
@nightnei I can confirm that the window do not exist anymore. We can consider this issue as closed.

**Comment by nightnei** [comment] 2024-09-03 10:39
Closing it, since it's not relevant anymore

**Closed as completed by nightnei** 2024-09-03 10:39 UTC
Labels: Bug, [Pri] Normal, [Feature] WordPress Desktop App, Triaged, [Product] WordPress.com, [Feature Group] Other Infrastructure, Groundskeeping
