### ISSUE TITLE
Cover Block: wide width and full width alignments not rendered in editor - impacts FSE themes on sites lower than Premium Plan

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#71882] opened 2023-01-10 18:07 UTC
### Quick summary

When adding the cover block to a page layout, the floating block toolbar shows the correct alignment options, but if you choose the options for either wide width or full width, those changes are not rendered in Gutenberg.

If the page/post is published or previewed however, the block is rendered correctly on the live site.

Screencast for clarity

https://user-images.githubusercontent.com/1967448/211628202-4222005a-ad25-4809-b834-e07c2df70065.mov

### Steps to reproduce

1. add cover block
2. choose either full or wide width settings
3. Note there is no change in the editor view

### What you expected to happen

New width settings to be reflected in the editor view in Gutenberg

### What actually happened

no change in the editor, but the correct width is shown on the live site.

### Context

Discovered while conducting a webinar on how to use the cover block.

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

Tested in Google Chrome and Mozilla Firefox on my Mac.  May affect other combinations.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

None

### Workaround details

Workaround is to preview the page or publish and check on the live site.

**Comment by jerrysarcastic** [comment] 2023-01-10 18:08
Also noting that this issue may be related since it affects cover image block alignments: https://github.com/Automattic/wp-calypso/issues/71023

**Comment by tanjoymor** [comment] 2023-01-21 16:46
Another case: #39890581-hc

**Comment by jerrysarcastic** [comment] 2023-01-23 19:05
Also tested this against a vanilla .org site using Gutenberg 15.0.1 and the cover block width alignments works as expected.  The issue seems to be specific to wpcom Gutenberg

**Comment by dsas** [comment] 2023-03-13 11:05
I created a page on a Personal site that uses Zoologist. I added three cover blocks, left one as normal and set the others to wide and full and I could reproduce this issue. I upgraded to Premium and could no longer reproduce this issue.

When on the Premium plan I'm getting a whole bunch of extra inline css rules applied setting max-width, on Personal I'm not.

One of these rules is `.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > .alignwide { max-width:1128px }` i.e. set a max-width on the cover block of 1128px if it has a class of alignwide and the cover HTML element is a child of the block list.

On the Personal plan this rule isn't applied because there's an extra div wrapping the cover block. This means the cover HTML is a grandchild of the block list, not a child. This extra div doesn't have the alignwide class, so it gets the default max-width via this rule: `.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > :where(:not(.alignleft):not(.alignright):not(.alignfull)) { 664px }`

It looks like the extra div is because the cover block is counted as a premium block if the contents include a video. To that end it uses the [Jetpack paid blocks upgrade banner](https://github.com/Automattic/jetpack/blob/ddf9e08122868c07496e7e02f2b88be8d7f01019/projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/with-upgrade-banner.jsx#L84) which wraps the component and an upgrade nudge inside a div inside the editor.

**Comment by dsas** [comment] 2023-03-13 11:14
Looks like it was introduced by https://github.com/Automattic/jetpack/pull/27909 cc @BogdanUngureanu

**Comment by jerrysarcastic** [comment] 2023-03-20 23:47
Also reported in https://wordpress.com/forums/topic/desktop-width-in-block-editor-is-too-narrow/

This seems to affect the [Farrow theme](https://wordpress.com/theme/farrow) pretty badly, since the entire homepage layout is created in within a cover block.  However it's worth nothing that many WordPress.com themes use the cover block in their demo content, so this is a broken experience for users even before they add content.

**Comment by sophiegyo** [comment] 2023-03-27 09:29
This is currently happening on my Simple site when I switched to TT3:

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/36608681/227900107-6de6303a-5b7d-45ca-853d-20979308e1a4.png">

vs published page:
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/36608681/227900322-6802df35-57a0-459f-bd92-265a8ca2fc96.png">

I couldn't replicate on self-hosted, with and without Gutenberg. Seems to be specific to wpcom!

**Comment by carinapilar** [comment] 2023-04-14 17:03
I got this on 42583416-hc too, and while testing on WordPress.com I noticed that it only happens on Free and Personal sites, it worked on a Premium site - I tested with the Skatepark theme.

**Comment by cuemarie** [comment] 2023-04-18 18:43
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Activating TT3 on 4 different simple sites, I can replicate the issue everywhere except the Premium Plan site:

https://user-images.githubusercontent.com/27249804/232871771-4c7899dd-d883-49b5-a36f-c089527e9eec.mp4

- Activating Twenty Twenty One across those same sites, the Cover block responds as expected to width changes in the editor:

https://user-images.githubusercontent.com/27249804/232872614-710b5c5a-257a-49fc-8839-69609d3457a6.mp4

📌 ACTIONS
- Assigned to Apex as a block issue

📌 Message to Devs
- CC @BogdanUngureanu as well - can you take a look at @dsas 's findings [above](https://github.com/Automattic/wp-calypso/issues/71882#issuecomment-1465934433) and check if this was indeed introduced by https://github.com/Automattic/jetpack/pull/27909 ?  Thank you!

**Closed as completed** 2024-01-16 04:48 UTC
Labels: Bug, [Pri] Normal, Triaged, [Platform] Simple
