### ISSUE TITLE
Post list: All sites search never finds results

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#18269] opened 2017-09-26 13:13 UTC
#### Steps to reproduce
1. Visit https://wordpress.com/posts
1. This is the global search page. You should see posts across all your blogs.
1. Click the search icon and enter a query.
1. Nothing ever matches!

The issue occurs independent of the me/everyone toggle.

#### What I expected

See results matching my query

#### What happened instead

I always see

> No posts match your search for post.

#### Screenshot / Video

![search-bug](https://user-images.githubusercontent.com/841763/30862014-d9a5e452-a2cc-11e7-89cc-ab1615414439.gif)

#### Context / Source

Noticed while preparing https://github.com/Automattic/wp-calypso/issues/18268

Thanks to @rachelmcr who confirmed when I mentioned this issue in Slack.

**Comment by mattsherman** [comment] 2017-11-01 12:19
This is a duplicate of #12670. Clothing this one.

**Closed by mattsherman** 2017-11-01 12:19 UTC
Labels: Posts, [Type] Bug
