### ISSUE TITLE
Ad Settings: Unclear Navigation / Missing Title

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/wp-calypso#22696] opened 2018-02-22 11:55 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/my-plan/{site-url}
2. Make sure site is on either JP Premium or Professional
3. Click the "Start earning" button
4. You are taken to: https://wordpress.com/ads/settings/{site-url}

#### What I expected
To understand where in the UI I am.

#### What happened instead
1. The page seems to be missing a title to reassure me where I am
2. Nothing in the nav seems to be highlight to indicate to me how to get back here
3. I genuinely couldn't find the screen again by hunting through the nav

<img width="1272" alt="ads_settings_ _richard_s_dot_org_sandbox_ _wordpress_com" src="https://user-images.githubusercontent.com/2287740/36537172-42c87516-17c7-11e8-9d47-8f8478ccfb5f.png">

**Comment by rachelmcr** [comment] 2018-02-23 11:07
Whoa, this is a weird one. On a site that has been using Jetpack for a while, I was seeing an Ads item in the sidebar (under Configure):

![screenshot 2018-02-23 11 04 00](https://user-images.githubusercontent.com/8658164/36591270-62252a86-1889-11e8-9195-c404856220dd.png)

However, right after taking that screenshot I selected Plan in the sidebar, landing on https://wordpress.com/plans/my-plan/{site-url}, and then the Ads item disappeared from my sidebar:

![screenshot 2018-02-23 11 06 08](https://user-images.githubusercontent.com/8658164/36591353-a3ceacf0-1889-11e8-913f-62c38845916d.png)

I have navigated around Calypso and done a hard refresh, but that Ads sidebar item hasn't come back.

**Comment by tyxla** [comment] 2018-03-07 16:16
This one is really interesting, and implies some API work, which I'd love to play with. Grabbing if you don't mind @lezama 😉

**Comment by tyxla** [comment] 2018-03-07 16:44
It turns out that the `/me/sites` endpoint returns the `wordads` option properly, while the single site endpoint (`/site/:siteId`) doesn't 😞 . So when one goes to "My Plan", this issues a request to the single site endpoint, which erases the `wordads` option and hides the menu item. 

I've come up with a pretty simple diff to address this: D10740-code - updates the single site endpoint to properly return `wordads`. Testing instructions can be found there.

Other than that, the missing title suggestion is pretty simple to address in Calypso, can get to it once we resolve the API one.

**Comment by tyxla** [comment] 2018-03-07 17:44
This PR adds the title to the settings page and updates how we display buttons for consistency: #23088.

**Comment by tyxla** [comment] 2018-03-26 12:40
This one is really close to getting done - just needs a final review of D10740-code after feedback was addressed.

Do you think you can have another look @ebinnion?

**Comment by ebinnion** [comment] 2018-03-26 15:49
Accepted

**Comment by tyxla** [comment] 2018-03-27 08:34
Thank you Eric ❤️ 

With both the UI improvements and the API fix in production, I can no longer reproduce the issue. Closing.

**Closed by tyxla** 2018-03-27 08:34 UTC
Labels: Ads, FixTheFlows, Jetpack, Plans, [Pri] High, [Status] In Progress, [Type] Bug
