### ISSUE TITLE
Theme Showcase: Uploaded Themes section on Atomic site incorrectly includes non-uploaded themes, missing actual uploaded theme

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#54394] opened 2021-07-08 18:41 UTC
### Steps to reproduce the behavior

1. On a WordPress.com site with a Business plan (but not yet Atomic) go to Appearance > Themes
2. Click "Install theme"
2. Click "Continue"
3. Drag or select a theme zip file that is *not* part of the WordPress.com collection, such as [Neve](https://wordpress.org/themes/neve/)
4. Once the theme has finished installing, click Appearance > Themes to return to the showcase
5. Click the "Show all themes" button at the bottom of the "Recommended Themes section"

#### What I expected to happen

To see only the newly uploaded theme in the "Uploaded Themes" area, with a "WordPress.com Themes" section below that, displaying the WordPress.com showcase themes.

#### What actually happened

The "Uploaded themes area" shows the active theme (a non-uploaded theme) along with Twenty Twenty One.

"WordPress.com Themes" section below that displays WordPress.com showcase themes, including a second copy of Twenty Twenty One.

**Screenshot 1 -**
![WordPress_Themes_‹_My_WordPress_Site_—_WordPress_com](https://user-images.githubusercontent.com/7662449/124973255-4ad11800-dff9-11eb-8db7-aa7ff84ccdbb.jpg)

Here are some other screenshots from other HEs, showing more examples of unexpected results:

**Screenshot 2 -** shows many non-uploaded themes in the Uploaded Themes area
<img width="1156" alt="Screen Shot 2021-07-08 at 6 57 46 AM" src="https://user-images.githubusercontent.com/7662449/124973833-0bef9200-dffa-11eb-861d-4a905d291cbf.png">

**Screenshot 3 -**  shows many non-uploaded themes in the Uploaded Themes area, and shouldn't the active theme always be shown first?
![Screen Shot 2021-07-08 at 08 21 22](https://user-images.githubusercontent.com/7662449/124973839-0c882880-dffa-11eb-9bd2-81bef1f7b91b.png)

**Screenshot 4 -** shows an empty Uploaded Themes area; if there are no uploaded themes, we should probably hide the heading
![Screen Shot 2021-07-08 at 08 01 16](https://user-images.githubusercontent.com/7662449/124973835-0c882880-dffa-11eb-9782-eec44abf2b7a.png)

### Context

Found while helping WordPress.com users, but no user follow-up needed

#### Browser / OS version

Firefox 89.0.2 / Mac OS 11.4 (Big Sur)

#### Is this specific to the applied theme? Which one?

No

#### Console Error

`Error: Promised response from onMessage listener went out of scope`
`common.js:4:491`

#### Does this happen on simple or atomic sites or both?

Atomic

#### Level of impact

All Atomic

**Comment by sixhours** [comment] 2021-07-12 15:58
I noticed that as I activate themes on my Atomic site that they get added to "Uploaded Themes" even if they're WordPress.com themes. It may be worth exploring renaming that heading to something like "Previously Used Themes" (terrible, don't use that) to convey it's not just uploaded themes, it's a history of themes you've used.

Not sure why the actual uploaded themes aren't showing, though.

**Comment by kwight** [comment] 2021-07-12 21:49
Is this a regression from our work, or was it always like that?

**Comment by sixhours** [comment] 2021-07-13 14:46
> Is this a regression from our work, or was it always like that?

I believe it was like that before, since the current changes to the showcase haven't modified which themes are displayed (unless it's maybe related to search changes? But I don't think so...)

**Comment by sixhours** [comment] 2021-07-14 20:41
I think moving Uploaded themes to their own tab as suggested in #54251 and renaming it to something that better reflects its purpose (Your Themes?) would solve some of this confusion (the "duplicate" themes, the empty heading). 

I'm not able to reproduce the issue with user-uploaded themes not showing up, though.

**Comment by sixhours** [comment] 2021-07-21 15:06
This has been partly solved by moving the "uploaded" themes to a new tab called My Themes in #54572 -- the only thing left here is to figure out why the uploaded theme does not show up in the listing. I haven't been able to reproduce that part.

**Comment by sixhours** [comment] 2021-07-21 19:34
I'm closing this out in favor of #54773(which I was able to reproduce, after reading the instructions more clearly -- it has to be a non-Atomic Business site 🙃 )

**Closed as completed by sixhours** 2021-07-21 19:34 UTC
Labels: Bug, [Pri] High, Triaged, [Pod] Design Selection
