### ISSUE TITLE
Gutenberg: Featured tag not showing in editor when set to be "hidden" from site

### ISSUE THREAD

**Issue by mlaetitia** [Automattic/wp-calypso#29411] opened 2018-12-13 16:34 UTC
When a featured tag is set on a post in the Classic editor and the editor is changed to Gutenberg, the featured tag does not appear there. This only happens when, in Customizer -> Featured Content the option "Do not display tag in post details and tag clouds." is checked

#### Steps to reproduce
1. Start with a site using the Classic Editor
2. Write a post, add the tag "featured" (or any other you prefer) and Publish the post
3. Head to the Customizer -> Featured Content, add the tag you added before there and choose the option "Do not display tag in post details and tag clouds."
4. Head back to the post and choose to activate the new editor. Check the tags list, the featured one is not there: https://cld.wthms.co/FuNmC7

#### What I expected
I expected the featured tag to appear in the tags list.

#### What happened instead
The featured tag is missing.
Calypsoified: https://cld.wthms.co/FuNmC7
Gutenlypso: https://cld.wthms.co/gBLU3v

#### Browser / OS version
MacOS / Firefox

#### Screenshot / Video
Calypsoified: https://cld.wthms.co/FuNmC7
Gutenlypso: https://cld.wthms.co/gBLU3v

**Comment by arunsathiya** [comment] 2018-12-13 16:49
I can confirm I am able to reproduce this as well, both on Calypsoified Gutenberg and Gutenlypso (Gutenberg in Calypso)

Also I can confirm that this happens only when one is going from Calypso editor to Gutenberg **and** already has enabled `Do not display tag in post details and tag clouds` setting on the Customizer.

Enabling `Do not display tag in post details and tag clouds` after moving from Calypso editor to Gutenberg has no effect on this.

**Comment by mlaetitia** [comment] 2020-07-10 08:19
One more report/similar issue: 3074526-zen

**Comment by jordesign** [comment] 2021-02-03 00:36
Unable to reproduce this when adding the tag in WP-Admin Classic Editor - and then editing within Gutenberg. WPCOM Editor is now deprecated so that won't be an issue either.

Closing this as unreproducible,

**Closed by jordesign** 2021-02-03 00:36 UTC
Labels: [Closed] Not Reproducible, [Goal] Gutenberg, [Pri] Normal, [Type] Bug, wp-admin
