### ISSUE TITLE
Stats: popular day/hour empty state styling is off

### ISSUE THREAD

**Issue by meremagee** [Automattic/wp-calypso#4948] opened 2016-04-21 22:11 UTC
![](https://cloudup.com/c-Zmhct5sb1+)
#### Steps to reproduce
1. create a new WordPress.com account
2. go to stats
3. notice "most popular day and hour" modal has an overlay that doesn't match calypso styling

**Comment by designsimply** [comment] 2016-08-23 20:05
Tested and confirmed using the steps provided.

![screen shot 2016-08-23 at tue aug 23 2 03 02 pm](https://cloud.githubusercontent.com/assets/1119271/17907790/a884ffe2-693a-11e6-9c50-f672eb4c9ce7.png)
<sup>Seen at https://wordpress.com/stats/insights/trythis485.wordpress.com using Safari 9.1.2 on Mac OS X 10.11.6</sup>

**Comment by folletto** [comment] 2016-08-24 11:20
I think these pages all need a good default empty state, not a blank box with "nothing" inside.

Meanwhile however, we could just hide that entire block until the data is actually available.

**Comment by hoverduck** [comment] 2016-11-14 18:02
#bug-scrub

The styling here is still the same as seen above, and it's been almost 3 months since the last activity on the thread.  But I'll leave it open as a `Good First Change` for somebody to pick up

**Comment by alisterscott** [comment] 2017-07-18 02:33
Confirmed this is still an issue. I am tempted to close this one since there hasn't been any activity on this for some time.

**Comment by gziolo** [comment] 2017-09-16 00:21
Addressed with #18060.

**Closed by gziolo** 2017-09-16 00:21 UTC
Labels: NUX, Stats, [Status] Needs Design Review, [Type] Bug, [Type] Good First Change
