### ISSUE TITLE
Gallery block - adding new images causes previous gallery settings to be lost

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/wp-calypso#44677] opened 2020-08-05 03:07 UTC
It seems to not be possible to add new images to an existing gallery block.  Instead of placing additional images, this action *replaces* the existing images with the new images that are trying to be added.

#### Steps to reproduce

1. Create a simple test page with a gallery block (I used a block with 3 images)
2. publish the page, the return to edit it again
3. click on the gallery block, and add an image from the media library
4. once the image is added, the previous images in the gallery no longer appear.

I have seen this issue in Calypso on both my wpcom simple and Jetpack test site (wpcom Business)

Screencast of the issue in Calypso:
- wpcom simple: https://d.pr/v/eTQund
- JP site: https://d.pr/v/OVBOcd

Adding images works fine in wp-admin on both sites
- wpcom simple (wp-admin): https://d.pr/v/f9NdwA
- JP site (wp-admin): https://d.pr/v/W2UkZR

#### What I expected

- In the media modal (when picking images from the media library) I noticed that the active images in the gallery were not selected (marked 1, 2, 3) as usual.
- normally I would expect the new image I am adding to be marked '4' in the modal, and added as a 4th image in the gallery

#### What happened instead
- instead the new image selected is marked '1' and no other images are marked.  
- adding a 4th image to the gallery instead results in a 1 image gallery. The new image replaces the previous ones

#### Browser / OS version
- Mac OS 10.15.4
- Chrome 84

**Comment by jerrysarcastic** [comment] 2020-08-05 03:09
Noting here that #44326 appears to be similar, and shows odd behavior that causes the gallery block to lose images

**Comment by jerrysarcastic** [comment] 2020-08-05 03:10
Also reported in #3193520-zen by a WordPress.com user (wpcom simple site)

**Comment by Robertght** [comment] 2021-02-18 20:39
I have another case in #3735402-zen - WPCOM case.

**Comment by glendaviesnz** [comment] 2021-03-10 00:55
This is caused by the fact that the `getMediaLibrarySelectedItems` selector in `client/my-sites/media-library/content.jsx` returns empty sometimes even when gallery has items, particularly on first page load. Loading the media browser a second time usually loads the selected images as expected:

![media-bug](https://user-images.githubusercontent.com/3629020/110558923-3181a180-81a8-11eb-8eda-571a5be76dd1.gif)

**Comment by glendaviesnz** [comment] 2021-03-10 01:59
@tyxla, it looks like this issue may have originated with the update to move the media store calls to redux. The items currently in the gallery are added to the store selected items correctly [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/gutenberg/editor/calypsoify-iframe.tsx#L294), but when the image browser dialog opens the [getMediaLibrarySelectedItems](https://github.com/Automattic/wp-calypso/blob/trunk/client/gutenberg/editor/calypsoify-iframe.tsx#L294) selector returns empty, which is just a race condition I expect, as loading the media library a second time shows the items selected correctly. 

Not sure why the store doesn't emit again and cause a rerender of the media library once the selected items are added to the store - do you have any thoughts on a fix for this?

**Comment by tyxla** [comment] 2021-03-10 15:00
This is interesting 👍  Thanks for the ping @glendaviesnz!

Seems like it might be related to our recent reduxification work. I'll add this to my to-do list for tomorrow and will take a stab at it.

**Comment by tyxla** [comment] 2021-03-11 10:24
Seems like we weren't handling deselection on successful image requests properly. Here's a fix: #50982

**Comment by tyxla** [comment] 2021-03-12 09:26
Fix has been merged 🚀  Let me know if you encounter this again.

**Closed** 2021-03-12 09:26 UTC
Labels: Blocks, Media, State, [Type] Bug

**Comment by cuemarie** [comment] 2021-07-23 18:57
I've encountered this issue today with a user in chat. Is there a solution or workaround? 28653578-hc

**Comment by KirkwallDay** [comment] 2021-07-25 16:12
The work-around steps aren't that clear in the video so here's what I'm telling users that encounter this bug:

"When you click the "Media Library" button to add pictures to the Gallery, first, click "Cancel" the first time, and then click the "Media Library" button again, and this time click "Edit Gallery" first, and your previous items should be in there. Now go back to "Add to Gallery" on the left and add the pictures as normal. You will then get an option to add captions and at this point, you should see all the pictures there, and clicking "Update Gallery" should work as expected."
