### ISSUE TITLE
Layouts: Social Media Links misaligned in layout preview

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#39348] opened 2020-02-10 18:59 UTC
Chrome, MacOS. Compare the preview …

**Unexpected**

![image](https://user-images.githubusercontent.com/545779/74180441-1fc87600-4c05-11ea-96f5-7391bd4ebdf0.png)

… with the Editor and Thumbnail …

**Expected**

![image](https://user-images.githubusercontent.com/545779/74180470-31aa1900-4c05-11ea-9768-7a9b01d7a654.png)

**Comment by ianstewart** [comment] 2020-02-10 19:00
@iamtakashi @alaczek

**Comment by iamtakashi** [comment] 2020-02-11 10:17
It looks like [this CSS](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/social-links/editor.scss#L81) for the block preview is preventing it to be center-aligned.

<img width="1575" alt="Screenshot 2020-02-11 at 09 41 58" src="https://user-images.githubusercontent.com/908665/74225843-61aff580-4cb3-11ea-988b-8eb771a6e489.png">

I'm sure that's necessary for the block preview, but we can't set text alignment in the parent container to make the block centered in the preview. @jasmussen do you have any advice or any other idea that the block could do for the preview?

**Comment by jasmussen** [comment] 2020-02-11 12:29
Definitely need to find a way to refactor that away. I'll take a look.

**Comment by jasmussen** [comment] 2020-02-11 12:39
Let me know if this helps: https://github.com/WordPress/gutenberg/pull/20167

**Comment by iamtakashi** [comment] 2020-02-12 12:47
@jasmussen Thanks for taking a look at this so quickly. 

However, removing the width rule makes the situation a little better, but it still doesn't make the block centered as the `auto` side margins aren't working with it being displayed as an `inline-block` element.

![Screenshot 2020-02-12 at 12 28 37](https://user-images.githubusercontent.com/908665/74336031-6fd64280-4d95-11ea-828b-00e37eece699.png)

When I remove the display rule, it's displayed correctly, though.

![Screenshot 2020-02-12 at 12 36 09](https://user-images.githubusercontent.com/908665/74336155-a7dd8580-4d95-11ea-844a-b6c2fa92e182.png)

**Comment by jasmussen** [comment] 2020-02-12 13:16
Serendipitously, feedback on the upstream PR suggested that's good to remove entirely! So I've taken that one out.

**Comment by iamtakashi** [comment] 2020-02-12 13:54
Thank you!

**Comment by obenland** [comment] 2020-02-24 23:27
Confirmed fixed in Gutenberg 7.6.0-rc.1.

**Closed by obenland** 2020-02-24 23:27 UTC
Labels: [Goal] Page Templates, [Type] Defect
