### ISSUE TITLE
Editor: cut-pasting a link at the beginning of the line removes the link (no href)

### ISSUE THREAD

**Issue by folletto** [Automattic/wp-calypso#10669] opened 2017-01-16 18:20 UTC
![cap-](https://cloud.githubusercontent.com/assets/4389/21994555/30a4fe2c-dc18-11e6-8dd6-a34c031d64aa.gif)

#### Steps to reproduce
1. Write some text, link it
2. Cut linked text
3. Move to an empty line
4. Paste

#### What I expected

The text should be still linked.

#### What happened instead

No link showing.

#### Browser / OS version

Tested on Chrome 55 Mac.

**Comment by ryanboren** [comment] 2017-01-16 19:00
A couple of examples of this from my session notes:

"Losing href on cut/paste links"
https://test.wordpress.com/2016/11/10/session-notes-back-buttons-hidden-sites-touch-image-flow-notifications-site-switching-flow-keyboard-flow-media-section-desktop-first/

"Cutting and pasting links"
https://test.wordpress.com/2016/09/23/session-notes-rss-widget-reader-gallery-layout-inline-link-toolbar-pasting-links-macnchrome-calypso-ios-ios-app/

**Comment by iandunn** [comment] 2017-07-18 20:08
It looks like this was fixed by the upgrade to TinyMCE 4.6.3 in ad9b179b632395ecc7acf66407971a672682451b. I'm not able to reproduce it after that.

**Closed by iandunn** 2017-07-18 20:08 UTC
Labels: Editor, [Type] Bug
