### ISSUE TITLE
Like widget: clicking on the like number doesn't open the popover

### ISSUE THREAD

**Issue by TimBroddin** [Automattic/wp-calypso#85853] opened 2023-12-29 13:35 UTC
"85 likes"

Only clicking on "likes" opens it, clicking the number does nothing.

**Comment by ivan-ottinger** [comment] 2024-01-02 11:19
I am looking into this task now.

**Comment by ivan-ottinger** [comment] 2024-01-02 12:39
D133387-code is now ready for review.

**Comment by ivan-ottinger** [comment] 2024-01-03 08:47
The issue is now fixed with D133387-code and D133401-code.

**Closed as completed by ivan-ottinger** 2024-01-03 08:47 UTC
Labels: Maintenance
