### ISSUE TITLE
FSE: Jetpack "Subscription form" block doesn't render as expected on header or footer

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#35537] opened 2019-08-18 13:08 UTC
The `Subscription form` block from Jetpack does not render as expected on the header or footer sections. It displays as a shortcode instead.

Header:

<img width="843" alt="Screenshot 2019-08-18 at 18 34 51" src="https://user-images.githubusercontent.com/18581859/63224809-12e34080-c1e7-11e9-93d9-a36255c560ce.png">

Footer:

<img width="1174" alt="Screenshot 2019-08-18 at 18 35 04" src="https://user-images.githubusercontent.com/18581859/63224808-124aaa00-c1e7-11e9-9e7c-801fa4e68544.png">

Loads fine on the `Content` section.

<img width="736" alt="Screenshot 2019-08-18 at 18 35 01" src="https://user-images.githubusercontent.com/18581859/63224806-0eb72300-c1e7-11e9-930b-338f7e4ad859.png">

#### Notes:

`Mailchimp` block loads as expected on header or footer sections.

**Comment by noahtallen** [comment] 2019-08-19 22:13
Possible duplicate of https://github.com/Automattic/wp-calypso/issues/35446. If the subscription form uses the embed block under the hood it might be caused by the same thing.

**Closed** 2019-08-20 18:12 UTC
Labels: Jetpack, [Goal] Full Site Editing, [Pri] BLOCKER, [Type] Bug
