### ISSUE TITLE
Billing History: cannot edit receipt

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#2219] opened 2016-01-07 23:55 UTC
Raised by @hafizrahman 

The receipts in Calypso's Billing History (https://wordpress.com/me/billing) are not editable yet. While previously you can edit your name/email in the receipt by clicking the name and entering your own values.

A temporary solution is to use http://store.wordpress.com/billing-history/

Comment from @breezyskies 

> I went to add the name and email address to the Calypso billing history receipts, but I did not see this information available in the receipt data, so it's probably missing from the API:
> 
> ![db7b7bfc-b5b2-11e4-8f3d-00cfe441cd92](https://cloud.githubusercontent.com/assets/1119271/12186359/cf57482a-b56f-11e5-9e99-afdee6f5a563.png)
> 
> @rads if you can add that data, I can work on the UI.

Comment from @matthusby 

> In r119135-wpcom I updated the endpoint to include the name and email so they will be shown on the receipt

Screenshot of how receipts currently look for reference:

![screen shot 2016-01-07 at 18 48 04](https://cloud.githubusercontent.com/assets/1119271/12186388/26eeb276-b570-11e5-9207-e5a2102eae77.png)

**Comment by breezyskies** [comment] 2016-01-09 00:06
This appears to be a regression, as I believe it was working after @matthusby last worked on it. Taking a quick look at the data, I'm seeing this now:

<img width="212" alt="screen shot 2016-01-08 at 4 04 52 pm" src="https://cloud.githubusercontent.com/assets/3011211/12212649/bbe283a6-b621-11e5-9d34-5536e6319a37.png">

**Comment by jerrysarcastic** [comment] 2016-02-19 19:20
For reference, here is a receipt in store.wordpress.com showing the editable fields for name and email address:

<img width="575" alt="screen shot 2016-02-19 at 11 15 54 am" src="https://cloud.githubusercontent.com/assets/1967448/13186321/8d610328-d6fa-11e5-9855-1218a0d21447.png">

One common request that would be great to add is a field for VAT.  I don't think we need to expose this on the receipt, but if there is a way to add a 3rd blank field (visible only on hover?) that'd be a bonus for those users who need to add an additional line of information on their receipt

**Comment by BandonRandon** [comment] 2016-02-19 21:44
Closing as a fixed. I couldn't find where in the code this was fixed but I am able to edit a receipt by clicking the "View Receipt" link. The two fields that are editable are name and email. 
![screenshot_19-02-2016-13 40 20](https://cloud.githubusercontent.com/assets/150348/13189793/7bafa882-d70e-11e5-830f-341e525cb504.png)

@jerrysarcastic If this is not what you're seeing or I'm misunderstanding the problem feel free to re-open this. 

> One common request that would be great to add is a field for VAT. 
Can you open a new issue for this?

**Comment by kevmarsden** [comment] 2016-04-26 22:12
The "View Receipt" link no longer contains the "Billing Details" field, so it's not possible to edit receipts.  

Also, store.wordpress.com and wp-admin links both redirect to https://wordpress.com/me/billing so there aren't any alternative methods of editing a receipt.  

![screen shot 2016-04-26 at 3 03 29 pm](https://cloud.githubusercontent.com/assets/2282189/14835829/dc1c10fc-0bc0-11e6-8694-c4840b544c34.png)

**Comment by breezyskies** [comment] 2016-04-26 22:54
@kevmarsden Have you checked a receipt with a non-$0 total? I can see the billing details under my account for a test purchase that didn't use credits.

**Comment by kevmarsden** [comment] 2016-04-27 03:45
@breezyskies I have one example of a receipt for €99.00 that doesn't include the Billing Details section. More details are in ticket 2640033-t
 
I spot checked a couple other accounts and the Billing Details section does appear, so this may be a limited bug.

**Comment by BandonRandon** [comment] 2016-04-27 05:16
I can confirm the regression. The design was changed and no longer shows in a module when clicking "View Receipt". Looks like the layout was changed since I originally closed this.

**Comment by breezyskies** [comment] 2016-04-27 12:47
cc: @mtias who worked on the recent design change.

**Comment by mtias** [comment] 2016-04-27 12:50
The internals shouldn't have changed with the update.

**Comment by StefMattana** [comment] 2016-04-27 12:56
I had the same problem with another use [on this chat](https://mc.a8c.com/support-stats/feedback/chat-transcript.php?id=359050)
I [followed up ](https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=2643045)with them already – do you folks think it's something that can be fixed soon? Thanks :)

**Comment by breezyskies** [comment] 2016-04-27 13:14
cc: @peterbutler for taking a look in that case.

**Comment by melanieharari** [comment] 2016-04-29 19:40
Closing this issue again, in favor of the Trello card here: https://trello.com/c/FRfreljr/126-m-billing-history-cannot-edit-receipt

**Closed by melanieharari** 2016-04-29 19:40 UTC
Labels: Billing, [Pri] Low, [Type] Bug

**Comment by jerrysarcastic** [comment] 2016-05-05 19:50
Probably not a concern for this specific issue, but my gut tells me it is not a good practice overall to move an issue from a public Githup repo to a private Trello card.  :(

**Comment by BandonRandon** [comment] 2016-05-06 00:01
I agree with @jerrysarcastic I understand some things (like this) may require some back end code changes which cannot be made public. In that event we should keep the issue open and report back when those changes have been made. 

Today I was able to able to edit the receipts, so this seems to be fixed! :tada:

**Comment by melanieharari** [comment] 2016-05-06 02:50
Sorry about that, @jerrysarcastic. Won't do it again.
AFAIK, the issue is still open. Not all receipts are able to be edited.

**Comment by samjhamdy** [comment] 2016-07-01 20:00
There's a workaround for this in BillingDaddy. Details here: https://a8c.slack.com/archives/tickets/p1467400508004218

**Comment by rantoncuadrado** [comment] 2017-01-10 12:11
Update. New ticket with the same problem and a video showing it #2994670-t
