### ISSUE TITLE
Query Loop: Pagination on Empty Query

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#56504] opened 2021-09-23 12:36 UTC
### Quick summary

The _Query Pagination_ is still shown even when there are no results on the _Query Loop_ block.

### Steps to reproduce

1. Create a new page
2. Add the _Query Loop_ block
3. Add a filter that would result in _No results found._
4. Add the _Query Pagination_ block

### What you expected to happen

To not show any pagination on the live page, since there are no results on the query.

### What actually happened

It shows a _Next Page_ link.

This is what you see within the editor:
![QueryLoopResults1](https://user-images.githubusercontent.com/16104522/134507419-f75eb662-0539-451d-8a25-60960a82b829.png)

And on the live page:

![QueryLoopResults2](https://user-images.githubusercontent.com/16104522/134507423-51a43086-368a-45bf-90c8-4c1dff87048c.png)

The _Next Page_ link adds `?query-0-page=2` to the page's URL, and when you click on it, it changes to _Previous Page_ and _Next Page_.

**Comment by inaikem** [comment] 2021-09-28 06:33
Thanks for the report, Carina!

I was not able to replicate this on a Simple, Atomic or self-hosted test site. The screenshots below are from an Atomic sites public page and editor page respectively:

&nbsp;
![Query block no results (public)](https://user-images.githubusercontent.com/66711744/135034446-1e196dad-9443-43b1-b445-899a1075287d.png)
&nbsp;
![Query block no results (editor)](https://user-images.githubusercontent.com/66711744/135034441-e127c755-071b-4328-b811-4e6cf3cbb4e7.png)
&nbsp;

Are you still able to replicate this on your end? If so, can you please provide details of the exact filter combination you used? Maybe the pagination issue here is specific to that.

For reference, here's the code for the Query Block (and filters) I used to generate a block that would produce a ` No results found.` message 🙏

```
<!-- wp:query {"queryId":7,"query":{"perPage":1,"pages":0,"offset":0,"postType":"post","categoryIds":[],"tagIds":[],"order":"desc","orderBy":"date","author":20569242,"search":"","exclude":[],"sticky":"","inherit":false}} -->
<div class="wp-block-query"><!-- wp:post-template -->
<!-- wp:post-title {"isLink":true} /-->
```

**Note:** I used an author with no posts.

**Comment by carinapilar** [comment] 2021-09-28 13:05
The problem is with the _Query Pagination_ block within the _Query Loop_, you would want to have this structure on the page:

![PaginationBlockIssue](https://user-images.githubusercontent.com/16104522/135092307-720b3574-bcc4-444a-ade5-7ec0447eb20c.png)

Even if there are no results from the query, it shows a Next Page link:

![PaginationBlockIssue2](https://user-images.githubusercontent.com/16104522/135092410-7fa1134c-3339-4f0e-b281-e4ae2be45ab4.png)

**Comment by Robertght** [comment] 2021-11-19 09:16
Thank you @carinapilar! I can replicate this on my end as well.

**Comment by ivan-ottinger** [comment] 2021-11-24 14:05
The Query Loop Pagination block is a part of Gutenberg. One of the ways we could fix the issue is to add a check whether there are actual pages available for the pagination. If there are no pages to navigate to, the "Next Page" link wouldn't display in the front-end.

When it comes to back-end, I think it would be worth leaving the default pagination displayed there even when there are no posts to be displayed at the time. This would make sure the user can still click on the pagination block and adjust its settings (e.g. label) for the time when the new posts meeting the filter criteria are published:

![Markup on 2021-11-24 at 15:01:18](https://user-images.githubusercontent.com/25105483/143252473-9bd09f77-4385-48e4-a09a-097762369633.png)

What do you think?

---

For completeness, here is a proposed code change (I will be working on the PR for the Gutenberg repo and will then link it here as well):

```diff
--- a/packages/block-library/src/query-pagination-next/index.php
+++ b/packages/block-library/src/query-pagination-next/index.php
@@ -44,7 +44,11 @@ function render_block_core_query_pagination_next( $attributes, $content, $block
 		remove_filter( 'next_posts_link_attributes', $filter_link_attributes );
 	} elseif ( ! $max_page || $max_page > $page ) {
 		$custom_query = new WP_Query( build_query_vars_from_query_block( $block, $page ) );
-		if ( (int) $custom_query->max_num_pages !== $page ) {
+		$max_num_pages = (int) $custom_query->max_num_pages;
+		if (!$max_num_pages) {
+			return '';
+		}
+		if ( $max_num_pages !== $page ) {
 			$content = sprintf(
 				'<a href="%1$s" %2$s>%3$s</a>',
 				esc_url( add_query_arg( $page_key, $page + 1 ) ),
```

**Comment by carinapilar** [comment] 2021-11-25 10:16
That sounds great to me, thanks @ivan-ottinger! 😃

**Comment by ivan-ottinger** [comment] 2022-03-25 14:30
My PR didn't get to review, but when I tried now, I couldn't reproduce the issue anymore. → Closing this thread now.

Of course, we can still reopen in case the issue comes back. :)

**Closed as completed by ivan-ottinger** 2022-03-25 14:30 UTC
Labels: Bug, [Pri] Low
