### ISSUE TITLE
Donations: use shared membership registration methods for Payments and Donation blocks

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#44366] opened 2020-07-22 22:13 UTC
Follow up to https://github.com/Automattic/jetpack/pull/16545, let's register the Donations block in a similar manner to the Payments block. 

We ended up backing this out of https://github.com/Automattic/jetpack/pull/16545 previously due to a regression for the Payments button render_button callback never firing on a published view.

Overall key points to this issue are
* Verify if we need the custom registration checks that the Payments block added. 
* Ensure that we register blocks once, render_callbacks fire, and that we're checking against the same plan checks for Payments/Donations.

Reading further in https://github.com/Automattic/jetpack/blob/master/extensions/README.md#paid-blocks if we pass through `'plan_check'      => true,` it looks like it's trying to verify against the store product list
```php
	public static function set_availability_for_plan( $slug ) {
		$is_available = true;
		$plan         = '';
		$slug         = self::remove_extension_prefix( $slug );

		if ( defined( 'IS_WPCOM' ) && IS_WPCOM ) {
			if ( ! class_exists( 'Store_Product_List' ) ) {
				require WP_CONTENT_DIR . '/admin-plugins/wpcom-billing/store-product-list.php';
			}
			$features_data = Store_Product_List::get_site_specific_features_data();
			$is_available  = in_array( $slug, $features_data['active'], true );
			if ( ! empty( $features_data['available'][ $slug ] ) ) {
				$plan = $features_data['available'][ $slug ][0];
			}
		} elseif ( ! jetpack_is_atomic_site() ) {
			/*
			 * If it's Atomic then assume all features are available
			 * otherwise check against the Jetpack plan.
			 */
			$is_available = Jetpack_Plan::supports( $slug );
			$plan         = Jetpack_Plan::get_minimum_plan_for_feature( $slug );
		}
		if ( $is_available ) {
			self::set_extension_available( $slug );
		} else {
			self::set_extension_unavailable(
				$slug,
				'missing_plan',
				array(
					'required_feature' => $slug,
					'required_plan'    => $plan,
				)
			);
		}
	}
```

Meanwhile for Payments, we explicitly check blog stickers in `jetpack/modules/memberships/class-jetpack-memberships.php`
```php
	public static function is_enabled_jetpack_recurring_payments() {
		// For WPCOM sites.
		if ( defined( 'IS_WPCOM' ) && IS_WPCOM && function_exists( 'has_any_blog_stickers' ) ) {
			$site_id = get_current_blog_id();
			return has_any_blog_stickers( array( 'personal-plan', 'premium-plan', 'business-plan', 'ecommerce-plan' ), $site_id );
		}

		// For Jetpack sites.
		return Jetpack::is_active() && (
			/** This filter is documented in class.jetpack-gutenberg.php */
			! apply_filters( 'jetpack_block_editor_enable_upgrade_nudge', false ) || // Remove when the default becomes `true`.
			Jetpack_Plan::supports( 'recurring-payments' )
		);
	}
```

**Comment by mmtr** [comment] 2020-07-23 13:34
I think we can close this one out. As @jeherve pointed out in https://github.com/Automattic/jetpack/pull/16545#discussion_r459288579 (and expanded in p1595494181070000-slack-serenity), since the block availability depends on a simple plan check and we want to show an upgrade nudge to users on free plans, we can use the `plan_check` property when calling to `jetpack_register_block` which is the recommended way for handling paid blocks.

When using that property, blocks ineligible for the current plan won't be rendered in the frontend, but can be used in the editor if the filter `jetpack_block_editor_enable_upgrade_nudge` is active (which is the case for WP.com simple sites).

I already pushed a commit to https://github.com/Automattic/jetpack/pull/16545 using that approach (had to add a new feature to all WP.com paid plans in D46803-code), so the block behavior ended up being as follows:

**WP.com simple sites**
- Block is insertable with any plan.
- On a free plan, we'll show an upgrade nudge. Block is fully editable but won't be rendered in the frontend.
- On a paid plan, the block is fully editable and will be rendered in the frontend.

**Jetpack sites**
- Block is insertable only on paid plans. This differs from the Payments block behavior which is insertable on free plans (but replaced with an upgrade nudge), but this is the intended behavior when using `plan_check` given that `jetpack_block_editor_enable_upgrade_nudge` is disabled on JP sites, so I'd say the Payments block is an exception and should be updated to be aligned with the default behavior implemented in all other paid blocks.

**Atomic sites**
- Block is always insertable since all AT sites are on a paid plan.

**Closed by mmtr** 2020-07-23 13:34 UTC
Labels: Earn, [Type] Task
