### ISSUE TITLE
Bug: Back button on anonymous user is returning to the wrong path

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#97802] opened 2024-12-26 20:28 UTC
### Quick summary

When navigating back from the "Create your account" screen with an anonymous user, the back button always points the user to the "Let us build your site" screen.

### Steps to reproduce

https://github.com/user-attachments/assets/76f11f2a-ea68-41c6-b6ba-0fddf45364b9

### What you expected to happen

It should redirect the user back to the "Selected theme" screen.

### What actually happened

It's always redirecting the user to the "Let us build your site" screen.

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by Imran92** [comment] 2024-12-26 21:36
I was able to reproduce it following the steps mentioned

**Comment by arthur791004** [comment] 2024-12-27 05:32
@alshakero It would be great if you had time to take a look again 🙏  I'd prefer https://github.com/Automattic/wp-calypso/pull/97775, and then we can come up with a better solution. The https://github.com/Automattic/wp-calypso/pull/97786 cannot solve the issue totally since the next step after the auth may still be wrong.

**Comment by alshakero** [comment] 2024-12-27 08:52
Hi Arthur! Yes feel free to merge your PR, I don't want to delay your work. I'll look into the extraData state later.

**Comment by arthur791004** [comment] 2024-12-27 09:13
Closing it via https://github.com/Automattic/wp-calypso/pull/97775

**Closed as completed by arthur791004** 2024-12-27 09:13 UTC
Labels: Bug, [Pri] High, [Feature Group] Signup & Site Onboarding, Needs triage, [Feature] Authentication, [Feature] Site Navigation, [Experiment] AI labels added, [Status] Auto-allocated, [Status] Escalated to Product Ambassadors
