### ISSUE TITLE
Gutenberg: Loss of post content after inserting a still-uploading featured image

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#33362] opened 2019-05-27 19:01 UTC
#### Steps to reproduce

I wish I had steps to reproduce. Instead, I'll describe what happened. I am convinced this is somehow related to this previously reported issue with Pexels as I was just picking a final featured image when it seems everything broke: 

https://github.com/Automattic/wp-calypso/issues/31230

I started a draft of a post that later became this post: https://nomad.blog/2019/05/26/responsibly/

I only had the first paragraph written out. I closed out of the post and returned to some time later in the evening. Upon returning, I wrote out the rest of the post. I went to select a pexels image and ran into the previously reported error. Knowing this would happen, I clicked "remove featured image" to remove the loading pexels image and then selected it again from my media library. Video demonstration:

https://cloudup.com/cPwXlkrrG9J

After doing this, I went to preview the post but the image didn't show up still. The full content did though! This made me think the content was indeed saved properly. When I returned to the editor, I noticed that the "Save Draft" notice was loading as "Autosaving..." indefinitely. Further, the publish button was strangely almost greyed out yet still "blue" (meaning it looked like I could press it). Upon some testing, this is what happens when you hit save draft as well:

<img width="204" alt="Screen Shot 2019-05-27 at 11 59 09 AM" src="https://user-images.githubusercontent.com/26996883/58435757-e6e87100-8076-11e9-82db-5c01ff33d7d0.png">

It seems somehow I got stuck in some autosaving failure that didn't actually show a failure. Thinking just the image would get reset (note: I had previewed the post and saw the content there already) and I could shake something loose, I refreshed the page. I lost everything except the very top paragraph. 

#### Details

This is the site/post: https://nomad.blog/2019/05/26/responsibly/

I rewrote it obviously :)

**Comment by annezazu** [comment] 2019-05-27 21:03
Managed to get a screenshot on a different post of the "stuck" state:

<img width="302" alt="Screen Shot 2019-05-27 at 2 02 10 PM" src="https://user-images.githubusercontent.com/26996883/58439269-15227c80-8088-11e9-81b9-1a55434232bb.png">

Normally, this hangs for a few seconds and then goes away. In this case, it was hanging for an extended period of time (at least a minute) before I grew impatient and refreshed the page.

**Comment by annezazu** [comment] 2019-06-27 22:21
Just had this happen again but am still working to prevent data loss. I opened the same post in a new browser and found images in a very strange broken state. Here are screenshots of both the original tab with the images but the autosaving stuck state and the new tab with the broken images:

<img width="1164" alt="Screen Shot 2019-06-28 at 12 06 21 AM" src="https://user-images.githubusercontent.com/26996883/60304390-9f852700-9939-11e9-86cd-94d1e629ae3e.png">

<img width="1156" alt="Screen Shot 2019-06-28 at 12 06 26 AM" src="https://user-images.githubusercontent.com/26996883/60304393-a14eea80-9939-11e9-97a0-5123c12f7c7a.png">

**Comment by noahtallen** [comment] 2019-07-24 22:46
Hi! I'm curious if you've still been getting this issue - we've shipped some updates to the core Gutenberg plugin on wordpress.com, so I'm hoping that autosave is working more smoothly now! 🤞Though that featured images bug is still an issue, I haven't been able to reproduce the stuck autosave problem yet.

**Comment by annezazu** [comment] 2019-07-24 23:28
Still seeing some weirdness with saving particularly around using Pexels. 

**To reproduce:**

- Open a new post
- Put lorem ipsum in
- Go to featured image and select a Pexels image from the "free image library" option
- Go back to your post and just wait :)
- Witness errors

**Errors**

The preview 404s despite their being content. 
<img width="1434" alt="Screen Shot 2019-07-24 at 4 26 45 PM" src="https://user-images.githubusercontent.com/26996883/61835317-065e0900-ae30-11e9-82a0-afd8176db8fb.png">
<img width="1426" alt="Screen Shot 2019-07-24 at 4 27 08 PM" src="https://user-images.githubusercontent.com/26996883/61835318-065e0900-ae30-11e9-925e-9a0eaad45ac5.png">
<img width="1358" alt="Screen Shot 2019-07-24 at 4 27 12 PM" src="https://user-images.githubusercontent.com/26996883/61835319-065e0900-ae30-11e9-8831-ca752ce61ebd.png">

**Comment by noahtallen** [comment] 2019-07-25 00:56
Yep, I was definitely able to reproduce that! Very interesting. I'll investigate 🔍

**Comment by annezazu** [comment] 2019-07-25 03:52
Thank you! Let me know if I can help at all.

**Comment by noahtallen** [comment] 2019-07-29 22:12
A quick update: I wasn't able to find the cause of this bug during hack week, so I'm going to move this back to the backlog as we're starting a new sprint. I think the solution will be part of #31230, if you'd like to follow along there!

**Comment by gwwar** [comment] 2019-10-23 00:32
I think this is a variant of https://github.com/Automattic/wp-calypso/issues/36191 There's probably a few pathways into this, but we can at least provide a better bulletproofing/escape hatches for folks. 

 If you don't mind I'm going to close this one in favor of https://github.com/Automattic/wp-calypso/issues/36191

The detail here will help a lot. Thanks for reporting @annezazu !

**Closed by gwwar** 2019-10-23 00:32 UTC
Labels: [Goal] Gutenberg, [Type] Bug
