### ISSUE TITLE
Editor: future dated posts cause an "unsaved changes" dialog to appear after scheduling

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#17889] opened 2017-09-07 00:50 UTC
It looks like scheduling a post since publish confirmation went live created a regression around unsaved changes  - see animation of previous behaviour (currently in desktop app)

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Create a new post and future date it
3. Schedule it
4. Preview appears
5. Navigate away

#### What I expected

Navigate away

#### What happened instead

Unsaved changes dialog

#### Browser / OS version

Chrome 61.0.3163.79 on macOS

### Current Behaviour ###

![future date unsaved changes](https://user-images.githubusercontent.com/128826/30140783-48b2c3d2-93ba-11e7-80ea-7d542e57cf58.gif)

### Previous Behaviour ###

![future date unsaved changes previously](https://user-images.githubusercontent.com/128826/30140785-5163d322-93ba-11e7-8194-ab69ace4457e.gif)

**Comment by mattsherman** [comment] 2017-10-06 00:17
This is a duplicate of #9833.

Following the steps listed in this report, I was unable to consistently reproduce this. This is in line with the inconsistent reproducability of #9833, so I do not believe this to be a separate issue.

Closing this one.

**Closed by mattsherman** 2017-10-06 00:17 UTC
Labels: Editor, [Type] Bug

**Comment by alisterscott** [comment] 2018-01-31 01:50
For future reference this was because the site was set to UTC+0 and was fixed by https://github.com/Automattic/wp-calypso/pull/21944
