### ISSUE TITLE
Upload Icons in Social Media Block

### ISSUE THREAD

**Issue by helenaartmann** [Automattic/wp-calypso#88276] opened 2024-03-07 01:33 UTC
### What

Add the option to upload icons within the social media block. 

### Why

Currently, while WordPress.com supports various default social icons, there are additional social icons that are not included, such as Apple Music. If a user wishes to add an icon like Apple Music, their only option is to use an image block. However, aligning the image block with social icons poses challenges, requiring users to write extra CSS and manage separate columns. Therefore, incorporating an option to upload icons directly within the social icon block would greatly benefit users, making the process more accessible and user-friendly for everyone.

**Comment by helenaartmann** [comment] 2024-03-07 02:13
Requests: 
[7379183-zd-a8c](7379183-zd-a8c)
[7442149-zd-a8c](7442149-zd-a8c)
7379183-zd-a8c

**Comment by dsas** [comment] 2024-10-28 17:11
This is a duplicate of https://github.com/Automattic/wp-calypso/issues/61328

**Closed as not planned by dsas** 2024-10-28 17:11 UTC
Labels: [Pri] Normal, Feature Request, Customer report [LEGACY], [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks
