### ISSUE TITLE
Thumbnails for YouTube embeds look pixelated when the iframe is too small

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/wp-calypso#55468] opened 2021-08-12 17:33 UTC
### Steps to Reproduce

1. Add a Columns Block with 3 columns
2. Insert a YouTube block with its respective video on each Column
3. Ser the Columns Block to Wide Width (optional)
4. Publish and notice the YouTube Thumbnails

### What I expected to happen

For the YouTube thumbnails to look good:

![Screen Shot 2021-08-12 at 12 27 54](https://user-images.githubusercontent.com/3696121/129241539-53867477-fd90-4ba8-849a-24a6ff3aa9e4.png)

### What actually happened

The YouTube Thumbnails look pixelated:

![Screen Shot 2021-08-12 at 12 28 36](https://user-images.githubusercontent.com/3696121/129241666-c1af47fe-3377-4e0b-b2c5-df7fbef4d4d1.png)

### Context

User report: 4214633-zd-woothemes

### Operating System

macOS

### OS Version

Big Sur 11.5.1 (20G80)

### Browser

Chrome/Chromium

### Browser Version(s)

Version 92.0.4515.131 (Official Build) (x86_64)

### Is this specific to applied theme? If so, what is the theme name?

No

### Simple, Atomic or both?

Both

### Number of Users Impacted

All users

### Available Workarounds

Slack convo for reference:

p1628694966117400-slack-C01UW7SB411

Based on [this Stackoverflow article](https://stackoverflow.com/questions/57080685/youtube-embed-player-thumbnails-are-pixelated-for-small-player-but-look-fine-f). YouTube reduces the thumbnail resolution at a certain breakpoint. When running tests I found it to be **181px**. So adding this CSS code helps with the issue:

```
/* Fix for YouTube embeds  | XXXXX-zen|hc */
.page-id-XXXX .entry-content .embed-youtube iframe {
  min-height: 181px;
}
```

### Reproducibility

Consistent

**Comment by synora** [comment] 2021-08-19 00:59
Is this still happening for the user? I tested this and here's what I'm seeing within the editor: 

<img width="810" alt="Screen Shot on 2021-08-18 at 20-57-43" src="https://user-images.githubusercontent.com/10015451/129991029-0308c1e0-fd6c-40e1-b006-49948ddcce66.png">

And on the published post:
<img width="1055" alt="Screen Shot on 2021-08-18 at 20-57-51" src="https://user-images.githubusercontent.com/10015451/129991041-1060ccd3-e952-424e-ac14-043bf9521968.png">

The thumbnails are looking good for me once published.

**Comment by AtrumGeost** [comment] 2021-08-19 12:31
Hi @synora !

Thanks for checking. This is still happening on my test site:

pb330S-mO-p2

**Comment by dpasque** [comment] 2021-08-20 17:47
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by yansern** [comment] 2021-09-09 13:12
This is marked as **Won't Fix** by @Automattic/flow-patrol-create because YouTube block loading low-resolution thumbnails on narrow width are the intended behavior. The CSS fix provided might introduce more issues than it fixes (depending on the layout of the site) and we can't anticipate for all.

@AtrumGeost If this is an annoyance for the user, then just provide the custom CSS fix for the user.

**Closed as completed** 2021-09-10 11:56 UTC
Labels: Bug, [Pri] Low, Blocks, Triaged
