### ISSUE TITLE
Slug change needs to be reflected in the post/page URL section even when in draft

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#67357] opened 2022-09-04 02:04 UTC
### Quick summary

When someone changes a slug for a draft post or page in the editor, the `?p=XXX`(or `?page_id=XXX`) suffix keeps appearing in the post/page URL section until a page/post is published. 

This might be just intended. If so, this can be a feature request.

### Steps to reproduce

1. Add a new post or page.
2. Save it as a draft once.
3. Try changing a slug(permalink) for the post or page.
4. Save the change.
5. Check the URL section in the editor.

### What you expected to happen

The URL section shows the custom slug saved. 

![Screen Shot on 2022-09-04 at 10:59:50](https://user-images.githubusercontent.com/32432463/188293867-fc597949-c171-4115-a330-37fe5c427d33.png)

### What actually happened

The URL section still shows the `?page_id=XXX` suffix.

![Screen Shot on 2022-09-04 at 11:02:31](https://user-images.githubusercontent.com/32432463/188293910-ab46af24-9f50-4d2c-abc0-8bdaf64ef8b5.png)

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment] 2022-09-07 18:19
📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/66433

📌 Message to Author
- (Also, core fix in the works here: https://github.com/WordPress/gutenberg/issues/43161 )

**Closed as completed by cuemarie** 2022-09-07 18:20 UTC
Labels: Bug, [Pri] High, [Platform] Simple, [Platform] Atomic
