### ISSUE TITLE
NUX: Bad redirect to login screen during signup on wpcalypso.wordpress.com

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#16156] opened 2017-07-12 19:14 UTC
#### Steps to reproduce
1. Starting at URL (from a fresh/incognito window): https://wpcalypso.wordpress.com/start
2. Follow the steps to sign up for a Premium or Business account

#### What I expected
After creating an account I expect to be sent to the checkout page to purchase my plan

#### What happened instead
Sometimes I'm instead dropped out to the login screen, despite the fact that I am technically logged in.  If I do then log in I'm taken to the Reader as usual, and my plan is left sitting hidden in my shopping cart.

I'm only able to reproduce this problem on CircleCI with wpcalypso, where the Canary tests are run.  Prior to the work done on the new login page we had a solid workaround in the e2e tests that would check for the presence of the login screen and then strip out the `redirect_to=.....` parameter and manually reload the page.  Since that work began we no longer get the `redirect_to` parameter, so I updated the workaround to just construct the `/checkout` URL directly.

That works a little better, but it's still happening frequently.

Originally reported in p4TIVU-6cx-p2

#### Browser / OS version
Linux Chrome v57.0.2987.133

#### Context / Source
#automated-testing

**Comment by yurynix** [comment] 2017-07-13 07:08
Seems related to https://github.com/Automattic/wp-calypso/issues/15874 and #16073

**Comment by hoverduck** [comment] 2017-07-13 17:22
Also possibly related - https://github.com/Automattic/wp-calypso/issues/10738

And I've written https://github.com/Automattic/wp-calypso/issues/16199 to document a slightly different, but likely related case where a browser refresh / page reload causes the NUX flow to fall apart.

**Comment by alisterscott** [comment] 2018-07-31 05:44
I can't reproduce this any more so closing this for now

**Closed by alisterscott** 2018-07-31 05:44 UTC
Labels: Login, NUX, [Type] Bug
