### ISSUE TITLE
Button block: can't change horizontal alignment when vertical variation is selected

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/wp-calypso#52125] opened 2021-04-20 18:54 UTC
### Steps to reproduce the behavior

1. Add a button block with multiple buttons
2. Change to vertical variation
3. try to change horizontal alignment from toolbar

#### What I expected to happen
should be able to align column of buttons left, center, or right

#### What actually happened
can't change horizontal alignment when vertical variation is selected

### Context
empathy testing

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://videopress.com/v/yfu8h48W

**Comment by Robertght** [comment] 2021-05-07 05:48
I pinged @Nic-Sevic on the video above as it appears to be private for now. 

I tried to replicate this on a self-hosted website and I'm only getting Wide and Full-width alignment as horizontal alignment when the Vertical variation is used.

![image](https://user-images.githubusercontent.com/6737345/117403495-ee764d00-af10-11eb-86e5-d40b8bafa99d.png)

This seems like a core GB feature, but please correct me if I'm wrong.

cc @porada as I noticed you assigned yourself to this.

**Comment by Nic-Sevic** [comment] 2021-05-09 05:37
Sorry @Robertght! Here's the screencapture directly I'm not sure why the link is no longer working...

https://user-images.githubusercontent.com/47717887/117561679-94f15800-b0a1-11eb-99d5-8084e34a316c.mov

**Comment by porada** [comment] 2021-05-12 16:58
@Nic-Sevic — Do have any other details on the user context? Like the theme the user was running.

I’m asking primarily because I can’t reproduce this issue under the current revision of core:

https://user-images.githubusercontent.com/2060580/118014803-e163be80-b353-11eb-82ed-89c95ecb7760.mp4

**Comment by porada** [comment] 2021-05-18 13:49
I’m going to close this one now, but please feel free to reopen if the issue reoccurs.

**Closed as completed by porada** 2021-05-18 13:49 UTC
Labels: Bug, [Pri] Normal, [Status] Needs Author Reply, Blocks, Triaged, Empathy Testing
