### ISSUE TITLE
CoBlocks: Uppercase formatting doesn't work, in Paragraph or other blocks.

### ISSUE THREAD

**Issue by spencerberry** [Automattic/wp-calypso#40778] opened 2020-04-03 20:37 UTC
## Steps to reproduce

1. Paragraph block, with some text
2. Highlight that text
3. Use the little down arrow to choose "Uppercase"
4. Nothing happens
5. If you publish the page, it has the class .uppercase, but not the style

For contrast, try a WordPress.com site that isn't atomic, it works as expected.

#### Context / Source

 #user-report #2842911-zen

**Comment by lancewillett** [comment] 2020-04-04 19:30
@spencerberry Could you please add screenshots or a short GIF video to demonstrate? It helps set the context — we can see the Gutenberg UI and determine lots of important details.

Browser / OS version info also helps.

**Comment by lancewillett** [comment] 2020-04-04 19:31
It's possible this is related to recent Gutenberg updates on WordPress.com. Worth also testing on a self-hosted WP site with latest version of the Gutenberg plugin.

**Comment by lancewillett** [comment] 2020-04-04 19:34
<img width="848" alt="Screen Shot 2020-04-04 at 12 33 16" src="https://user-images.githubusercontent.com/66797/78459800-7cc63280-7670-11ea-98a1-9180eda843db.png">

I tested with Firefox 74.0.1 on macOS with an Atomic site and couldn't find the Gutenberg option for making uppercase text.

**Comment by lancewillett** [comment] 2020-04-04 19:35
I do see the control on a Simple site (same browser):

<img width="746" alt="Screen Shot 2020-04-04 at 12 35 24" src="https://user-images.githubusercontent.com/66797/78459834-cb73cc80-7670-11ea-8957-abf5da1cbbda.png">

**Comment by lancewillett** [comment] 2020-04-04 20:04
@spencerberry Tracked this down to the CoBlocks plugin — the Uppercase tool isn't from core Gutenberg, though it is a suggested change: https://github.com/WordPress/gutenberg/issues/20801

**Comment by simison** [comment] 2020-05-14 04:43
@Automattic/ajax FYI.

**Comment by iamtakashi** [comment] 2020-05-14 13:24
I can also replicate the issue in my local site with/without Gutenberg plugin, and I opened an issue in CoBlocks repo. https://github.com/godaddy-wordpress/coblocks/issues/1488

**Comment by kriskarkoski** [comment] 2020-05-19 17:52
While testing 8.1 I encountered this issue on simple sites on both 8.0 and 8.1

**Comment by davipontesblog** [comment] 2020-06-12 01:12
Noting that this is closed on CoBlocks now: godaddy-wordpress/coblocks#1488
Waiting plugin update on dotcom to fix the issue.

**Comment by WunderBart** [comment] 2020-12-21 17:25
> Noting that this is closed on CoBlocks now: [godaddy-wordpress/coblocks#1488](https://github.com/godaddy-wordpress/coblocks/issues/1488)
> Waiting plugin update on dotcom to fix the issue.

CoBlocks have been updated in WPCOM. Closing this one as I cannot reproduce the issue (both Simple and Atomic sites) 🎉

**Closed by WunderBart** 2020-12-21 17:25 UTC
Labels: Atomic, Editor, [Goal] Gutenberg, [Type] Bug
