### ISSUE TITLE
Subscriptions: Don't email deleted accounts

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#93548] opened 2024-08-15 02:05 UTC
Background: https://github.com/Automattic/wp-calypso/issues/56919, 

This issue is to split off and track a fix for the sending email part, leaving the count recalculation issue as a separate problem.

Done means:
- [x] When sending new post / follower notification emails to subscribers we need to check the receiving account hasn't been deleted. 
- [x] If the account has been deleted, don't send the email.

**Comment by miksansegundo** [comment] 2024-08-15 14:04
I haven't been able to test this because I don't receive any emails on my subscriber inbox after posting content. Maybe it's my user, or my site.

I'm going to leave it and work on another issue.

**Comment by TimBroddin** [comment] 2024-08-19 12:05
I'm taking over this ticket and I'm working on a diff that will prevent new post / comment emails from going out to deleted user accounts.

@lsl  Do we have a report on follower notification emails going out to deleted user accounts? I can't seem to replicate this.

**Comment by TimBroddin** [comment] 2024-08-19 13:02
Diff: D158732-code

**Comment by miksansegundo** [comment] 2024-08-20 10:43
Approved 👍

**Comment by miksansegundo** [comment] 2024-08-20 10:57
@TimBroddin would you be interested in giving a try to fix this [other issue](https://github.com/Automattic/wp-calypso/issues/68506) that is also related to subscribers? I am struggling to reproduce it because it seems to happen only when the subscriber's membership for paid content is renewed.

**Comment by TimBroddin** [comment] 2024-08-20 10:59
Will do, thanks for the review!

**Comment by miksansegundo** [comment] 2024-08-23 08:29
We can close this now that D158732-code is deployed to avoid emailing deleted accounts. 

The pending part for the count recalculation issue is tracked in https://github.com/Automattic/wp-calypso/issues/56919#issuecomment-2290366844

**Closed as completed by miksansegundo** 2024-08-23 08:29 UTC
Labels: [Pri] High, Groundskeeping
