### ISSUE TITLE
Follow Blog Widget: Localized links don't direct site owners to the Customizer to edit widget options

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#48849] opened 2021-01-13 07:17 UTC
Our customer's site is set to Italian. They reported that when they click on the _gestisci_ link to manage the Follow Blog widget's options, the link does not direct them to the Reader page to _Manage Following_.

Instead, it basically takes you to a _Not Found_ page.

#### Steps to reproduce the behavior

1. Go to https://economiaconamalia.com when accessing the site as site owner;
2. Click on the _gestisci_ link under the Follow Blog widget in the sidebar;
3. The page that loads at https://wordpress.com/it/following/edit appears to be a _Not Found_ page in Italian.
4. By contrast, if you browse to https://wordpress.com/following/edit/ (without the localisation string), you are directed to the correct Reader page to _Manage Following_.

#### What I expected to happen

Clicking on a localised link should redirect to the correct page in Reader.

#### What actually happened

Clicking on the localised link leads to a _Not Found_ page.

#### Context

Ticket: 3637339-zen
Site: https://economiaconamalia.com

### Browser / OS version

Tested on Firefox Developer Edition, v85.0b6 on macOS 11.1.

I believe the customer is using Chrome.

### Is this specific to the applied theme? Which one?

The user is using Independent Publisher 2, although this appears to be independent of theme. If I preview the Twenty Twenty theme using _Try & Customize_, the _gestici_ link remains https://wordpress.com/it/following/edit/

### Does this happen on simple or atomic sites or both?

The customer's site is on a WordPress.com Premium plan. I wasn't able to reproduce the equivalent edit link on a WordPress.com Business plan site.

### Is there any console output or error text?

Nothing relating to this.

### Level of impact (Does it block purchases? Does it affect more than just one site?)

This will likely affect other sites that use languages other than English.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Here is a demonstration of what happens:

![20210113_084144_screenshot](https://user-images.githubusercontent.com/2912202/104418689-fe43dd00-557f-11eb-899a-49b948a47205.gif)

**Comment by carinapilar** [comment] 2021-02-23 14:57
Reported by another user - interface set in French: 3764256-zd-woothemes - I was able to replicate with the interface set to Portuguese too.

**Comment by eoigal** [comment] 2022-12-16 17:56
I could not replicate this bug on a simple site. Can we update the steps to reproduce please?

I updated a simple site to use an old theme so I could access Widgets.
There were 2 follow widgets to choose from;

<img width="337" alt="Screenshot 2022-12-16 at 17 59 09" src="https://user-images.githubusercontent.com/5560595/208160098-7ef6c083-f764-4415-8e27-1df548c2a196.png">

Neither widget show a link when logged in as site owner to `/following/edit/`.
<img width="337" alt="Screenshot 2022-12-16 at 17 57 09" src="https://user-images.githubusercontent.com/5560595/208160196-1434678a-81d0-47f6-b208-1805ff189aa3.png">

Happy to look into this further if I can get some help in reproducing the bug.

**Comment by carinapilar** [comment] 2022-12-17 21:55
@eoigal, I wasn't able to replicate this again. The _Follow Blog_ widget isn't available anymore with the block widgets, so I tested with classic widgets, and it doesn't seem that the link is shown anymore on the widget.

It seems that the widget stopped identifying that you're logged in with an account that's already following the site, so I guess that's why the link stopped showing.

**Comment by roo2** [comment] 2023-02-02 22:28
let's close this as "can't reproduce"

**Closed as completed by roo2** 2023-02-02 22:28 UTC
Labels: Bug, [Feature] Site Settings, [Pri] High, [Feature] Reader, i18n, [Feature Group] Support, User Waiting
