### ISSUE TITLE
Widget: 'Gallery widget' loads incorrectly with plugin 'WordPress.com Editing Toolkit' enabled

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/wp-calypso#63138] opened 2022-04-28 14:13 UTC
### Quick summary

Gallery Widget content does not load correctly in the Footer when the plugin 'WordPress.com Editing Toolkit' is enabled.
Tested in Theme Alves.

### Steps to reproduce

1. Enable the plugin: WordPress.com Editing Toolkit
2. Add a Gallery Widget to the Footer 1  (theme Alves)
3. Save the widget area
4. Refresh the pages various times (Chrome)
5. Footer area will show images with a large space and large images
 
<img width="1397" alt="Screenshot on 2022-04-27 at 13-17-25" src="https://user-images.githubusercontent.com/44442769/165770890-5b787d52-7570-4c2d-bbd5-4e6a97bd8bfa.png">

### What you expected to happen

I expect the image to load correctly with the Gallery Widget layout when the plugin 'WordPress.com Editing Toolkit' is enabled.
<img width="419" alt="Screenshot on 2022-04-28 at 16-10-48" src="https://user-images.githubusercontent.com/44442769/165772102-f4fd8f37-3b58-4366-a90f-7276db3b9d36.png">

### What actually happened

Gallery Widget in Footer shows incorrect layout with the plugin 'WordPress.com Editing Toolkit' enabled. When deactivated, Gallery shows correctly.

### Context

Customer report: #5171864-zen

### Simple, Atomic or both?

Atomic

**Comment by cuemarie** [comment] 2022-05-04 18:00
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on AT ✅ 
- Theme Tested: Alves

📌 FINDINGS/SCREENSHOTS/VIDEO
- ❌ Wasn't able to replicate this. 
- I built a gallery block into Footer 1 of the Alves theme, with WordPress Editing Toolkit plugin activated. In both Firefox and Chrome, the Gallery appears as expected after numerous (5+) refreshes.

![Markup on 2022-05-04 at 10:59:27](https://user-images.githubusercontent.com/27249804/166754854-a4962165-209f-4194-bd1b-08c01adb9119.png)

- The [Gallery did appear all in a row in the Customizer's preview](https://user-images.githubusercontent.com/27249804/166755817-c720e080-0f84-4214-96a0-b218414724b4.png), but this seems to be a separate issue.


📌 ACTIONS
- Await author feedback

@rachelwinspear can you check in with the user to see if the issue is still occurring if they activate the WordPress Editing Toolkit again / are you able to replicate this issue in a test environment still?

**Comment by inaikem** [comment] 2022-06-01 03:34
Closing as unreproducible. If the issue is reported again, please test using the latest guidance provided in the comment above and reopen as needed!

**Closed as completed by inaikem** 2022-06-01 03:34 UTC
Labels: Bug, [Pri] Low, Block Widgets, [Block] Gallery
