### ISSUE TITLE
Customizer: header image not changing

### ISSUE THREAD

**Issue by daria2303** [Automattic/wp-calypso#53952] opened 2021-06-23 15:58 UTC
### Steps to reproduce the behavior

1. Go to 'Appearance > Customize > Header Image'
2. Try to change image - any method - to the suggested ones, last used, upload a a new one
3. Image doesn't change in preview or live page

#### What I expected to happen

Header image is updated

#### What actually happened
In customzier seems chanched, but it doesn't.

### Context
I am not able to reproduce on test site, but only on user's one.

#### Does this happen on simple or atomic sites or both?
Simple, not able to reproduce on test site.

#### Is there any console output or error text?

?v=2.0:16 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
just one

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
only user's site
Repeats on Safari, Chrome, Ecosia

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://github.com/Automattic/wp-calypso/issues/52182
4089324-zd-woothemes

**Comment by liviopv** [comment] 2021-07-01 10:16
@daria2303 I'm closing this as it's not a bug. What happens is that the theme will display the Featured Image of the posts marked as Featured Content on the front page, instead of the Header Image.

If there are no Featured Content posts, the Header Image displays correctly. I let the user know about this.

**Closed as completed by liviopv** 2021-07-01 10:16 UTC
Labels: Bug
