### ISSUE TITLE
Jetpack Connect: No insight into errors during autoconfig process

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/wp-calypso#18455] opened 2017-10-02 19:41 UTC
<img width="562" alt="screen-shot-2017-09-28-at-10-14-18" src="https://user-images.githubusercontent.com/831377/31095718-d1a9fc56-a787-11e7-889c-e6c83dd627c5.png">

@keoshi came across this in testing and noted that there's no real indication as to what's going on, the spinners just seem to get stuck in this state with no option to retry, skip, or cancel. Of note, all of the "stuck" items are related to VaultPress specifically.

This happened when purchasing a Professional plan for a poopy.life test site. 

cc @rickybanister

**Comment by rickybanister** [comment] 2017-10-04 17:39
There was some discussion previously about this issue. I think we are seeing this screen in a transitional state before some api-side work is finished, but perhaps luna folks can comment as to whether we have an unaddressed bug or not.

**Comment by tyxla** [comment] 2017-10-05 11:50
I was unable to reproduce that one with a poopy.life purchasing a Professional plan. But let's consider I can force it to happen again for the sake of solving any future similar cases that occur.

I think it could be useful if we display a warning/error notice somewhere if that happens. Can we get a quick draft of where we could drop an error message in this screen @rickybanister? Thanks in advance.

**Comment by rickybanister** [comment] 2017-10-05 13:59
What would the error be, what would it say? 

In the past I saw us showing a global notice error on the page when something extra strange happened. 

Ideally though, we wouldn't show an error, but rather the 'you're almost there' text and a link to chat with support. These 'errors' are most often just anomalies with configuration settings and are surmountable with the right instructions. An 'error' might be kind of overdoing it.

**Comment by tyxla** [comment] 2017-10-05 14:45
The 'you're almost there' solution with the chat button sounds good to me. Could you please share a quick mockup of how that would look?

**Comment by rickybanister** [comment] 2017-10-05 23:40
@tyxla that should be already implemented. 

Here's the original mockup:

![image](https://user-images.githubusercontent.com/437258/31257155-ef8c6bee-aa04-11e7-8b1c-8675bc3f6ba5.png)

Further reading: p6TEKc-1rT

**Comment by tyxla** [comment] 2017-10-11 10:37
That's already implemented indeed, and simulating an error brings up that screen properly. 

Can anyone help me reproduce the bug, described in this issue? I'm not able to reproduce it when purchasing a Professional plan for a poopy.life site - perhaps I'm missing something?

**Comment by keoshi** [comment] 2017-10-11 11:55
@tyxla These are the steps that got me in that view:

- Create site on poopy.life.
- Install Jetpack.
- Connect Jetpack to WordPress.com.
- Purchase the Professional plan.
- Wait for the setup to be finished.
- View hung up in that state you see above.

**Comment by tyxla** [comment] 2017-10-12 12:04
That's exactly what I tried @keoshi, but with no luck 😞  
Care to record a gif or something? Thanks so much!

**Comment by keoshi** [comment] 2017-10-12 14:59
@tyxla Went through the flow again and couldn't replicate.

I did notice paradoxal interstitial states that kept refreshing, confused me about the real status and didn't surface important info long enough:

> We can't automatically configure the Akismet and VaultPress plugins

> You will have to set up your plan manually.
> [Get help setting up]

> You are powered up, it's time to see your site.
> [Visit your site] [Ask a question]

https://www.youtube.com/watch?v=h4PoqRHI-mU

I can confirm Akismet and VaultPress were both installed and active at the end of the process.

**Comment by oskosk** [comment] 2017-10-13 12:05
I think the issue reported here in the description by @chaselivingston  is already solved. Although the last comment by @keoshi does reflect something currently happenning and indeed needs to be addressed.

**Comment by tyxla** [comment] 2018-07-16 13:57
This is still an issue, but will be ready to be closed as soon as we the checklist for Jetpack sites is ready and open to public.

**Comment by tyxla** [comment] 2019-04-12 14:37
Let's keep that open, it might be useful now that we're planning to roll out a new way to autoconfig the plugins.

**Comment by keoshi** [comment] 2019-10-18 09:10
We're not showing this anymore, closing the issue.

**Closed by keoshi** 2019-10-18 09:10 UTC
Labels: Design, [Type] Enhancement
