### ISSUE TITLE
Launch banner breaks the site HTML structure

### ISSUE THREAD

**Issue by dinhtungdu** [Automattic/wp-calypso#75425] opened 2023-04-07 11:59 UTC
### Quick summary

On atomic staging sites, in the browser dev tool, all tags that are supposed to be inside `<head>` are placed inside `<body>`.
Digging deeper, I found that the HTML markup for the launch banner is actually rendered inside <head>, which looks like the troublemaker. I only see that issue for staging sites that are coming soon (so they have the launch banner).

### Steps to reproduce

1. Log in to an atomic staging site.
2. Go to the front end of the site.
3. See the launch banner.
4. Inspect the element using browser dev tool, see all `<head>` tags are placed inside `<body>`.

### What you expected to happen

Tags inside `<head>` should be rendered correctly.

### What actually happened

Tags inside `<head>` are rendered in the `<body>`.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

<details>
<summary>Screenshots</summary>

![SCR-20230407-ppwj](https://user-images.githubusercontent.com/5423135/230605085-c091f205-ccf6-4582-9d5d-d884d280659e.jpeg)
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/5423135/230605114-d0f07d16-4ce9-49d3-ac72-4ee323e473df.png">

</details>

**Comment by dpasque** [comment] 2023-04-07 16:01
Reproduced and confirmed: this only happens on Atomic sites that aren't launched.

Moving to the build column and also pinging that team as a heads up, in case this is something that changed recently?

@Automattic/build

**Comment by danielbachhuber** [comment] 2023-04-07 18:36
It seems like it's been hooked onto `wp_head` for a really long time: https://github.com/Automattic/wpcomsh/blame/dd5e052093cb4cc7daa619fa0c7ebdd3ad50137d/private-site/private-site.php#L98-L103

I don't see any recent history for the banner itself that's relevant: https://github.com/Automattic/wpcomsh/commits/dd5e052093cb4cc7daa619fa0c7ebdd3ad50137d/private-site/logged-in-banner.php

We might be able to switch from `wp_head` to `wp_body_open()` ([ref](https://developer.wordpress.org/reference/functions/wp_body_open/)). We'd need to make sure `wp_body_open()` is used on all WPCOM themes. Unfortunately, we can't guarantee it's used on user-installed themes, but I don't think it's a huge deal that the launch banner doesn't display if `wp_body_open()` isn't used.

The alternative would be to inject the banner with JavaScript. I don't love the idea, though.

@dpasque Out of curiosity, what makes this issue `[Pri] High` vs some other priority? Given it's been broken for years, I'd like to add it as `Normal` in our backlog.

**Comment by dpasque** [comment] 2023-04-07 19:10
@danielbachhuber thank you so much for taking a look! 😄 

> @dpasque Out of curiosity, what makes this issue [Pri] High vs some other priority? Given it's been broken for years, I'd like to add it as Normal in our backlog.

I think lowering it to normal is totally fine 👍. I had kept the bot-added "high" initially just because this technically would affect every atomic user at first, and I just wanted to make sure it didn't have some worse implications I was missing, or wasn't a recent breakage/change.

**Comment by danielbachhuber** [comment] 2023-04-07 20:49
@dpasque Sounds good, thanks!

**Closed as completed** 2023-09-25 09:45 UTC
Labels: Bug, [Pri] Normal, Needs triage, [Platform] Atomic, [Status] Priority Review Triggered
