### ISSUE TITLE
WordPress.com Editing Toolkit: Coming Soon Privacy settings don't work when ETK plugin is disabled

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#79764] opened 2023-07-22 16:05 UTC
### Quick summary

On WordPress.com, Atomic sites have the ability to deactivate the WordPress.com Editing Toolkit plugin, which is required for the Coming Soon option to work. 

When the plugin is disabled and a user sets Coming Soon mode via Privacy Settings > General, Calypso saves the Privacy settings and adds the badge that the site is set to Coming Soon, but Coming Soon won't work until the WordPress.com Editing Toolkit is active. 

## Workaround 

After setting your site's Privacy Settings to Coming Soon, navigate to My Site > Plugins > and Activate the WordPress.com Editing Toolkit. 

### Steps to reproduce

1. Start with an existing Public [Atomic site](https://wordpress.com/support/hosting-configuration/#activate-hosting-configuration)
2. Navigate to Plugins > Installed Plugins > Locate WordPress.com Editing Toolkit and click Deactivate.
3. Navigate to Settings > General and select Coming Soon and save your Privacy Options. 

### What you expected to happen

I expect the WordPress.com Editing Toolkit to be activated when I enable Coming Soon via the site's Privacy Settings since that feature is dependent on the plugin being active. 

### What actually happened

The WordPress.com Editing Toolkit plugin remains disabled, and Coming Soon is not enabled on the site's frontend, even though the Calypso dashboard shows Coming Soon mode is active.

https://github.com/Automattic/wp-calypso/assets/29527450/7dd1dca9-605d-45c0-b6aa-8402ee2eb630

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Discovered while testing https://github.com/Automattic/wp-calypso/issues/79763 reported separately as they're two different flows and settings.

**Comment by cuemarie** [comment] 2023-07-24 20:00
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was unable to replicate this, as my AT test sites seem to reflect that `Coming Soon` mode is actually no longer dependent on the ETK plugin. 

#### Screenshots/Recordings

In this recording, I only have the ETK plugin disabled.  I am able to switch back and forth between Coming Soon and Public, and a logged-out browser window reflects the changes correctly:

https://github.com/Automattic/wp-calypso/assets/27249804/2743ee85-ff65-4119-9cb2-4660edfa2962

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- @ash1eygrace I'm trying to figure out where we can confirm if there was an update to the ETK that removed this dependency, and I'll report back!  If you get a moment, can you let me know if you're seeing different behavior than my test video there?

**Comment by cuemarie** [comment] 2023-07-24 20:15
Update! Found: https://github.com/Automattic/wp-calypso/pull/73249 // Internal Project: p9dueE-6jY-p2

Coming Soon is now built into `jetpack-mu-wpcom`, so it no longer relies on the ETK.

---

With that in mind, I want to address the original report expectations:

>I expect the WordPress.com Editing Toolkit to be activated when I enable Coming Soon via the site's Privacy Settings since that feature is dependent on the plugin being active.

This should not happen, given the feature migration noted above.

> What actually happened
> The WordPress.com Editing Toolkit plugin remains disabled, and Coming Soon is not enabled on the site's frontend, even though the Calypso dashboard shows Coming Soon mode is active.

Can you retest this on your site?  In my tests, Coming Soon mode was active for a logged out browser as soon as I activated it from the Settings page. 

📌 ACTIONS
- Closing as by design

**Closed as not planned** 2023-07-24 20:26 UTC
Labels: Bug, [Pri] Normal, Editing Toolkit, [Platform] Atomic
