### ISSUE TITLE
Global styles: custom "button" colors not reflected on live site

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#74223] opened 2023-03-08 18:48 UTC
### Quick summary

In the Styles pane, under **Colors**, some themes have a specific "Buttons" color area to set the text/background color for buttons. In some tested themes, the changes may or may not be reflected in the editor, and aren't reflected on the live site.

### Steps to reproduce

1. Activate a block theme – tested on Twenty Twenty-Three and Meraki.
2. Open the Site Editor (Appearance > Editor).
3. Add a Buttons block to the current template, and add text and a link to the button to make sure it appears on the live site.
4. Open the Styles pane, navigate to Colors > Buttons.
5. Set a custom background or font color. Save changes.

### What you expected to happen

Buttons should change to reflect the chosen colors, both in the editor and on the live site.

### What actually happened

In _Meraki_, the button doesn't change in either the editor or the live site. Button block-specific styles (i.e. Styles > Blocks > Button >  Colors) _do_ work in both places.

In _Twenty Twenty-Three_, the editor _does_ reflect the changes, but the live site does not. Button block-specific styles again seems to work in both places.

With the _Styles > Colors > Buttons_ styles modified only, it looks like the default colors are applied just after the custom colors in the theme CSS, causing the custom style to be overwritten.

![dvVanZ.png](https://user-images.githubusercontent.com/5630717/223806371-6852545b-5cff-450b-ac55-c1d68c64971c.png)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Tested only on Atomic so far, and only on these two themes. Reported in 6024659-zd-woothemes.

Using block-specific styles (_Styles > Blocks > Button > Colors_) seems to work as a workaround. It's not clear from a user's perspective why there's two different places to edit button colors (technically more, as there's also the _Buttons_ block, and a separate _Button_ block styles with no color options).

**Comment by dsas** [comment] 2023-03-27 10:10
See https://github.com/WordPress/gutenberg/issues/44931

**Comment by cuemarie** [comment] 2023-03-28 19:21
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on AT: Replicated
- Tested on Self-Hosted: Replicated
- Replicated on Core? **Yes**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can replicate this as described on AT site

**Self-Hosted Example**

https://user-images.githubusercontent.com/27249804/228344546-53101761-6a8e-46ad-a85f-358bb6966e2d.mov

📌 ACTIONS
- Closed as duplicate of issue  https://github.com/WordPress/gutenberg/issues/44931

📌 Message to Author
- Thanks for the link @dsas! https://github.com/WordPress/gutenberg/issues/44931 **Global Styles: Styles specificity and users expectations** - TLDR here is that GB is working as intended, but has a confusing UX due to the hierarchy of elements vs blocks.

**Closed as completed by cuemarie** 2023-03-28 19:21 UTC
Labels: Bug, [Pri] Low, [Status] Core Fix Needed, Triaged, [Platform] Atomic
