### ISSUE TITLE
[Bug]: WordPress.com media library doesn't load, redirects to https://wordpress.com/media/example.com?retry=1 which is a blank white page

### ISSUE THREAD

**Issue by purplepioneer** [Automattic/wp-calypso#59605] opened 2021-12-28 23:14 UTC
### Quick summary

When you open the media library for a site (including Jetpack connected sites) from Calypso/the WordPress.com dashboard, the media library does not load. 

You are redirected to https://wordpress.com/media/example.com?retry=1 which loads to a blank white page. 

### Steps to reproduce

1. Start at the WordPress.com dashboard/calypso https://wordpress.com/stats/day/example.com 
2. Click on "Media"
3. Media Library does not load, redirected to https://wordpress.com/media/example.com?retry=1 which is a blank page
4. Back button in browser does not reload last calypso page
5. Only way to load calypso again is to specifically revisit https://wordpress.com/stats/day/example.com

### What you expected to happen

The WordPress.com or Jetpack connected site's media library should load and render on the page correctly when you click "Media." 

### What actually happened

The WordPress.com or Jetpack connected site's media library does not load, you are redirected to https://wordpress.com/media/example.com?retry=1 which loads to a blank white page.

### Context

Customer reports which led to the behavior being confirmed by multiple JPOP and WPCOM HEs who received similar reports and were able to replicate the behavior. 

I have confirmed via my own testing that the behavior occurs using Google Chrome Version 96.0.4664.110, Safari Version 15.2 (17612.3.6.1.6), and Firefox 95.0.2 (Desktop, MacOS). 

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari

### Simple/Atomic

Simple, Atomic

### Other notes

Tickets: 
4643784-zen
4643855-zen
4643857-zen

Slack conversations:
p1640731319381600-slack-C03TY6J1A
p1640731460004700-slack-C0CMN0V97
p1640731845386600-slack-C03TY6J1A

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No and the platform is unusable

### Workaround details

Jetpack connected sites can view their media library from their site's WP Admin but WordPress.com hosted sites cannot. 

I tested on mobile, iOS 15.2 (19C57) on an iPhone 13 and was able to view the media library for one of my sites in Safari.

**Comment by JenSwish** [comment] 2021-12-28 23:27
4643880-zen

**Comment by annbingle** [comment] 2021-12-28 23:29
Reported in this as well 31840874-hc Thank you :)

**Comment by paxblueribbon** [comment] 2021-12-28 23:29
reported in 32971285-hc

**Comment by helenaartmann** [comment] 2021-12-28 23:31
reported in 29636886-hc

**Comment by metabreakr** [comment] 2021-12-28 23:32
Just wanted to chime in that for a user in 33366440-hc using `wp-admin` was a viable workaround. Shared direct link to `wp-admin/upload.php`.

**Comment by cuemarie** [comment] 2021-12-28 23:44
Reported here, Simple Site: 28199356-hc
Follow up ticket created: 4643885-zd-woothemes

`wp-admin` did not work
Switching themes to default also did not help (Tried Twenty Twenty One, Geologist, then returned them to their retired theme. No change with any themes)

**Comment by cuemarie** [comment] 2021-12-29 00:17
Reported here, Simple site: 33393939-hc
Follow up ticket here: 4643852-zd-woothemes

**Comment by sirbrillig** [comment] 2021-12-29 00:46
The error is:

> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'currentUser')

I believe this was caused by [this commit](https://github.com/Automattic/wp-calypso/pull/59594/commits/d6492c9cc3bda946c7b3604d044b6ddcc8939d1d) since apparently `state` is sometimes undefined. It should be fixed by [this commit](https://github.com/Automattic/wp-calypso/pull/59604/commits/7a1dd4cf109260eae347737737fdd5a916d8def9) now.

**Closed as completed by sirbrillig** 2021-12-29 00:46 UTC
Labels: Bug, Needs triage
