### ISSUE TITLE
Unable to save the layout dimensions with the Styles editor on Simple sites

### ISSUE THREAD

**Issue by danielk-am** [Automattic/wp-calypso#71604] opened 2022-12-31 06:03 UTC
### Quick summary

Unable to save the layout dimensions with the Styles editor on Simple sites.

<img width="2103" alt="SCR-20221231-jep" src="https://user-images.githubusercontent.com/92185881/210126814-d74b0c69-8c6e-4a3a-b481-00d21a53507e.png">

A screen recording of the issue is below.

https://user-images.githubusercontent.com/92185881/210126771-99ef3a9b-0fe5-46b8-b998-7dca253f76f1.mov

Tested on a test site on a Premium plan (can't save), and another with an eCommerce plan (can save).

### Steps to reproduce

1. Select a FSE-ready theme (tested on Skatepark and Muscat) on a simple site.
2. Go to the global Styles → Layout setting.
3. Change the content or wide values, and save.

### What you expected to happen

The custom styles with the layout dimensions to be saved.

### What actually happened

The layout dimensions automatically revert to the original.

### Context

First encountered at 5825569-zen.

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Themes tested were Skatepark, and Muscat.

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by ClassicRKR27** [comment] 2023-01-04 15:01
Just played into the ticket for this - [this is actually related to this issue from what I can tell](https://github.com/Automattic/wp-calypso/issues/67059).

**Comment by Copons** [comment] 2023-01-09 11:50
Thanks for reporting! I'm closing this as duplicate of https://github.com/Automattic/wp-calypso/issues/67059#issuecomment-1374880893, so let's move the convo there for now (not for much longer hopefully)!

**Closed as not planned by Copons** 2023-01-09 11:50 UTC
Labels: Bug, [Pri] Low, [Platform] Simple
