### ISSUE TITLE
PW Spec Migration: Empty out the quarantined run

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#61172] opened 2022-02-16 17:22 UTC
### Details

Right now, we have fragile scripts in a quarantined run so they don't disrupt the deployment process. We should revisit these scripts, see what we can stabilize, and what can be moved back out into pre-release tests or PR based tests.

**Comment by worldomonation** [comment] 2022-06-13 21:14
Duplicate of https://github.com/Automattic/wp-calypso/issues/58683.

**Closed as completed by worldomonation** 2022-06-13 21:14 UTC
Labels: Task
