### ISSUE TITLE
Add a page modal with pre-defined layouts does not load 

### ISSUE THREAD

**Issue by rinazrina** [Automattic/wp-calypso#71966] opened 2023-01-12 04:37 UTC
### Quick summary

When creating a new page, the **Add a page** modal that loads pre-defined layouts appears for a split second, then it disappears, and opens a blank page editor. 

I can reproduce this only on Archeo theme, and on simple sites. It works fine on my test Atomic site. 
This is reproducible on the user's Atomic site with Archeo theme and Gutenberg plugin active. The issue was fixed when deactivating Gutenberg. 

### Steps to reproduce

1. Activate Archeo theme 
2. Go to Pages > click Add new page
3. See if the pre-defined layout is loading

### What you expected to happen

The **Add a page** modal loads the pre-defined layouts as shown in the following screenshot: 

<img width="1276" alt="Screenshot on 2023-01-12 at 12-16-35 (1)" src="https://user-images.githubusercontent.com/33721365/211977014-608c2cb0-86ab-4e7f-8aba-4f21a7ca0a48.png">

### What actually happened

The **Add a page** modal loads for a split second and then disappears as shown in the below video: 

https://user-images.githubusercontent.com/33721365/211976389-92c17cbb-208d-450c-9f68-b356a42a8df1.mp4

### Context

User report: 2822944-hc
Follow up: #5858628-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Likely affect FSE themes. Reproduced this on Archeo and Twenty Twenty-Two, but not on Twenty-Twenty. 

### Browser, operating system and other notes

I reproduce this on Chrome. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

User can choose layouts using [Block Patterns](https://wordpress.com/support/block-pattern/). 
For Atomic site, user can deactivate Gutenberg temporarily.

**Comment by dlaurisse** [comment] 2023-01-12 10:03
5858058-zen Same issue with this ticket, replicated with other themes too, not just with Varase theme.

**Comment by kavyagokul** [comment] 2023-02-16 10:29
📌 SCRUBBING : RESULT
- Tested on Simple - Could Not Replicate 
- Tested on AT - Could Not Replicate 
- Tested on Self-hosted - Uncertain
- Replicable on Core - Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
- Unable to reproduce on Atomic and simple, on Firefox and Chrome
- Unable to test on self-hosted, because installing "WordPress.com Editing toolkit" leads to a fatal error.

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs)


📌 Message to Author
- @rinazrina There have been multiple releases of Gutenberg since this, so it's possible this was fixed along the way. Please reopen if this reoccurs/

**Closed as completed by kavyagokul** 2023-02-16 10:29 UTC
Labels: Bug, [Pri] Normal, [Platform] Simple, [Platform] Atomic
