### ISSUE TITLE
Editor: emoji don't appear in post titles in Chrome

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#997] opened 2015-11-29 19:53 UTC
Raised by @aheckler 

What I Did: Inserted an emoji in a post title.

What I Expected: The emoji to appear.

What Actually Happened: It didn't.

There is an emoji in this post title, but it's invisible:

![image](https://cloud.githubusercontent.com/assets/5512652/9398271/447ee9d4-4773-11e5-8eca-313d155e1522.png)

Notes from @kriskarkoski 

> Emoji in titles work as expected in Safari and Firefox so this is specific to Chrome. I tracked it down to the  `font-weight:600;` styling for `.editor__title[type="text"]`. Here's what it looks like when removing that line:
>
> ![screen shot 2015-10-05 at 1 40 53 pm](https://cloud.githubusercontent.com/assets/1900444/10288443/e4cbaf78-6b66-11e5-80fa-f7fbbe6c9dec.png)
>
> I'm not sure if there is anything we can do about this on our end until the corresponding [Chromium issue](https://code.google.com/p/chromium/issues/detail?id=468765) is resolved
>
> This same issue is present in the drafts drawer.
>
> Chrome:
>
> ![screen shot 2015-10-05 at 1 57 15 pm](https://cloud.githubusercontent.com/assets/1900444/10288911/9ffa6300-6b69-11e5-9da4-616638eaaa44.png)
>
> Safari:
>
![screen shot 2015-10-05 at 1 57 25 pm](https://cloud.githubusercontent.com/assets/1900444/10288914/a3dbd832-6b69-11e5-806a-9d6ea31ea276.png)
>
> In this case it's `font-weight:bold;` for `draft__title` causing the issue.

Note from @nylen 

> Nice investigation kriskarkoski !! :clap: [This Chromium issue](https://code.google.com/p/chromium/issues/detail?id=441946) is also closely related.

**Comment by blowery** [comment] 2016-02-02 21:13
Just ran into this myself. They moved the Chromium bug, still not resolved: https://code.google.com/p/chromium/issues/detail?id=501071

**Comment by lancewillett** [comment] 2016-03-09 22:40
Was able to repeat this today — bug reported by @m for [this post](https://ma.tt/2016/03/jetpack-turns-5/).

It happens for any Calypso site in my testing, WP.com and Jetpack alike, in Mac-n-Chrome:

<img width="455" alt="screen shot 2016-03-09 at 15 34 48" src="https://cloud.githubusercontent.com/assets/66797/13653087/e60f5bf2-e60c-11e5-8b41-75a6e7f11ea3.png">

<img width="442" alt="screen shot 2016-03-09 at 15 34 59" src="https://cloud.githubusercontent.com/assets/66797/13653088/e91ea582-e60c-11e5-91ab-31ee6efc6db7.png">

<img width="521" alt="screen shot 2016-03-09 at 15 35 50" src="https://cloud.githubusercontent.com/assets/66797/13653090/eb6f71ae-e60c-11e5-94a9-d4a01a45c1f8.png">

<img width="570" alt="screen shot 2016-03-09 at 15 35 55" src="https://cloud.githubusercontent.com/assets/66797/13653095/ee37cc7e-e60c-11e5-9670-0a4f1bbd0777.png">

Safari 9.0.3 (on OS X 10.11.3) looks fine:

<img width="600" alt="screen shot 2016-03-09 at 15 40 02" src="https://cloud.githubusercontent.com/assets/66797/13653159/352155ce-e60d-11e5-8b61-15a28f687899.png">

**Comment by folletto** [comment] 2016-03-11 12:33
Yep, unfortunately Chrome/Chromium hasn't fixed the issue yet. Note that has been merged into a different issue, but the problem is the same: [501071](https://bugs.chromium.org/p/chromium/issues/detail?id=501071).

**Comment by blowery** [comment] 2016-03-11 13:18
hmmmm I wonder if our case was related to the Merriweather issues... @mattmiklic ?

**Comment by folletto** [comment] 2016-03-11 13:23
As far as I checked, it's not. If you change the font to any font, including web standard ones, the issue persists:

![cap-](https://cloud.githubusercontent.com/assets/4389/13703229/5bfa9234-e78c-11e5-9eb2-16f1aa737d85.gif)

**Comment by mattmiklic** [comment] 2016-03-11 14:31
> As far as I checked, it's not. If you change the font to any font, including web standard ones, the issue persists

Yeah, I don't think it's related to the issue with locally-hosted Merriweather, since we started seeing this a few months back. From the googling I've done so far it seems like there are quite a few font rendering issues in Chrome...

**Comment by mattmiklic** [comment] 2016-03-11 14:50
I noticed that https://bugs.chromium.org/p/chromium/issues/detail?id=441946 was marked as resolved, so I checked things out in Chrome Canary (top) vs Chrome 49:

<img width="680" alt="screen shot 2016-03-11 at 9 46 40 am" src="https://cloud.githubusercontent.com/assets/1396552/13705366/857fb17a-e76e-11e5-9df5-49d32448af45.png">

So it does look like this has been fixed. Just to confirm that it's unrelated to our Merriweather issue, I tried switching back to loading WOFF first in Canary, and our bug was still present.

**Comment by lancewillett** [comment] 2016-03-11 15:59
Thanks for the notes @mattmiklic — glad to see this fixed in Canary! w00t.

Closing (I'm sure it'll come to stable soon enough).

**Closed by lancewillett** 2016-03-11 15:59 UTC
Labels: Editor, [Pri] Normal, [Type] Bug
