### ISSUE TITLE
Publicize: new Connections do not work, show errors

### ISSUE THREAD

**Issue by msilbers** [Automattic/wp-calypso#55322] opened 2021-08-10 16:39 UTC
### Steps to Reproduce

1. Start at Tools > Marketing > Connections
2. Click Connect for Facebook

### What I expected to happen

A pop up choosing which Page to connect to

### What actually happened

Instead of that popup, the pop-up shows this error:

> {"code":"rest_no_route","message":"No route was found matching the URL and request method.","data":{"status":404}}

The URL it loads is:

> https://public-api.wordpress.com/wpcom/v2/p2/connections/blocked?response_type=code&client_id=249643311490&redirect_uri=https%3A%2F%2Fpublic-api.wordpress.com%2Fconnect%2F%3Fmagic%3Dkeyring%26action%3Dverify%26kr_nonce%3D50df774310%26nonce%3D905fc63a00%26service%3Dfacebook&state=0&scope=manage_pages%2Cpublish_pages&display=popup

### Context

This was first reported by a customer but we can reproduce it. We tried with Facebook but it appears that all connections are not working, and like something may be wrong with the WordPress.com REST API?

### Operating System

macOS

### OS Version

11.4 Big Sur

### Browser

Chrome/Chromium

### Browser Version(s)

Version 92.0.4515.131 (Official Build) (x86_64)

### Is this specific to applied theme? If so, what is the theme name?

no

### Console and/or error logs

{"code":"rest_no_route","message":"No route was found matching the URL and request method.","data":{"status":404}}

### Number of Users Impacted

All users

### Reproducibility

Consistent

**Comment by kwight** [comment] 2021-08-10 17:53
Looks like no changes in Calypso to any of Marketing since April: https://github.com/Automattic/wp-calypso/commits/e5b9a0d0ef91bc8df047e52941bed1297301dbbb/client/my-sites/marketing 

I don't see any obvious commits in the SVN log in the last few hours either.

**Comment by codebykat** [comment] 2021-08-10 18:10
The `/v2/p2/connections/blocked` is somewhat suspicious. I haven't looked at this code in years but it should be redirecting to that `redirect_uri` to get authorization and it looks like something (in p2?) might be preventing a redirect.

**Comment by codebykat** [comment] 2021-08-10 18:12
https://opengrok.a8c.com/source/xref/trunk/wp-content/mu-plugins/keyring/includes/services/extended/slack.php?r=230059&mo=2283&fi=61#61

**Comment by codebykat** [comment] 2021-08-10 18:12
I found the code change that broke this - it looks like a commit to WPCOM by @unDemian related to this PR, which looks unmerged, confusingly. https://github.com/Automattic/wp-calypso/pull/55195

**Comment by kwight** [comment] 2021-08-10 18:16
Oh maybe D65209-code

**Comment by yansern** [comment] 2021-08-10 18:31
Created a quick phab fix for this. D65369-code

**Comment by kwight** [comment] 2021-08-10 18:31
Reverting with D65368-code

**Comment by radtechgh** [comment] 2021-08-10 18:48
same issue - 29936315-hc

**Comment by mihpaese** [comment] 2021-08-10 18:49
Same issue:
* https://wordpress.org/support/topic/cant-connect-to-facebook-and-twitter/
* https://wordpress.org/support/topic/cant-connect-twitter-or-mailchimp/
* https://wordpress.org/support/topic/social-media-integration-broken/

**Comment by unDemian** [comment] 2021-08-10 18:56
We've deployed a fix for this.

**Comment by kwight** [comment] 2021-08-10 19:25
Fix confirmed!

**Closed as completed by kwight** 2021-08-10 19:25 UTC
Labels: Bug, [Pri] High
