### ISSUE TITLE
Jetpack Carousel: Space Around Rounded Images Open Carousel Even If Image Has a Custom Link

### ISSUE THREAD

**Issue by upwardmomentum84** [Automattic/wp-calypso#65350] opened 2022-07-07 11:49 UTC
### Quick summary

When Jetpack Carousel feature is enabled, the space around rounded images open the image in the carousel. This happens when the image style is set to rounded.

### Steps to reproduce

1. Make sure Image Gallery Carousel option is enabled. For simple sites this is in: Settings > Media. For atomic sites this is at the top: Jetpack > Settings > Writing.
2. Add a Gallery block and some images to a page
3. Set the image style to be rounded.
4. Add a custom link to the images.
5. Update page to save changes.
6. View the live version of the page and click the white space between the images. It opens a carousel view instead of going to the link in the image.

Here is an example of where to click in the white space:

![Markup 2022-07-07 at 07 41 13](https://user-images.githubusercontent.com/93800099/177765297-04846d39-e22d-406d-a725-8587c1018519.png)

### What you expected to happen

That clicking the white space would either not link anywhere OR that it would link to the same link set for the image.

### What actually happened

The image is opened in carousel view.

### Context

HC-35866904

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

I found two options:

1. Disabled the carousel feature. 

- For simple sites - this can be done in Settings > Media > uncheck "Display images in full-size carousel slideshow".
- For atomic sites - this can be done in Jetpack > Settings > Writing > toggle off "Display images in a full-screen carousel gallery"

2. Use combination of Column blocks and Image blocks for content. Images set to rounded that have a link added function as expected.

**Comment by jamiepalatnik** [comment] 2022-07-14 15:33
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to reproduce this issue on simple, AT, and self-hosted sites. 

📌 ACTIONS
- Marked as Triaged for Quality Squad review

📌 Message to Author
 - Thanks for the clear steps to reproduce!

**Comment by mpkelly** [comment] 2022-08-04 05:08
I am looking at this one now.

**Comment by mpkelly** [comment] 2022-08-04 07:17
It looks like the fix will need to be made here in [this block of code in file jetpack-carousel.js](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/carousel/jetpack-carousel.js#L1587). 

Based on my initial analysis, both options above, navigate to a custom URL, or do nothing, should be possible. If anyone has a preference then let me know. ~~I think doing nothing is consistent with how it appears to the user.~~ I noticed that Chrome shows the custom link URL in the bottom corner, so I think we should navigate to that.

**Comment by mpkelly** [comment] 2022-08-22 10:33
This was fixed by https://github.com/Automattic/jetpack/pull/25410

**Comment by mpkelly** [comment] 2022-09-05 09:44
An [issue has been discovered](p8oabR-Vp-p2#comment-6583) when the `figcaption` is also present. It will need a small PR to fix it, so reopening this one.

**Closed as completed** 2022-09-05 16:14 UTC
Labels: Bug, [Pri] Normal, Triaged
