### ISSUE TITLE
Untranslated ETK content is cached on atomic sites

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#53853] opened 2021-06-21 04:30 UTC
Something quite strange, but consistently reproducable is happening with translations in the ETK on Atomic sites

In summary, If a site is created when the user has a certain profile language created, the ETK translations for that language will work correctly. But if the user later changes their language, the ETK content will default back to English!

Installing any _different_ build of the ETK will cause the new language to be translated correctly. Previously used languages remain correctly translated. This leads me to believe that this is some kind of caching issue 🤔 

### Steps to reproduce the behavior
Set a users language to _Spanish_ (or another language) in `/me/account`
Create a site and complete the AT process to get an atomic site.
Go to the editor ( new page )
Notice that ETK content is correctly translated to _Spanish_ ( New page template selector, welcome guide, etc ) ✅ 
Change the users language to something else in `/me/account` e.g. _Itallian_
Go back to the editor
Notice that the ETK content is no longer translated, it now defaults to english ❌ 
This seems to affect all ETK content
<img width="1274" alt="Screen Shot 2021-06-21 at 4 11 17 PM" src="https://user-images.githubusercontent.com/22446385/122706242-98385000-d2ab-11eb-9f9b-bbb9a912af27.png">
( If you were to change language back to _Spanish_, the ETK content would be translated correctly again )

Go to the plugins page and install a _different_ build of the ETK
( I get a _different_ version by making a whitespace change to ETK source and running a local build: `yarn build && zip -r etk.zip editing-toolkit-plugin`)
Go back to the editor
<img width="1038" alt="Screen Shot 2021-06-21 at 4 26 36 PM" src="https://user-images.githubusercontent.com/22446385/122707191-940d3200-d2ad-11eb-98f8-81f870b5fb7e.png">
I tested that any _different_ of the ETK will cause the new language to be translated correctly. Try again with a new language, it will not work until you upload a _different_ build of the ETK

Original investigation here: https://github.com/Automattic/wp-calypso/issues/53364#issuecomment-864640073

**Comment by deBhal** [comment] 2021-06-25 06:59
Investigation results so far:

1. The primary issue is that we're not installing the translations for the plugin on the remote site
2. It also looks like there's some mis-alignment with the locales.
3. And (unrelated to this issue except for the report) on jurassic-ninja I'm seeing an error loading the starter page templates

#### Installing the translations:

We download and serve the language packs server side on the remote site.

E.g. With the Italian and French translations installed, the `wp-content/languages/plugins` directory looks like this:

![jules_—_userb85deb50_jurassic-ninja2____apps_userb85deb50_public_wp-content_languages_plugins_—_ssh_userb85deb50_https___peaceful-giraffe_jurassic_ninja_—_146×78](https://user-images.githubusercontent.com/5952255/123380783-36415880-d5d3-11eb-8797-11a3504f2001.jpg)

When the page is loaded the plugins looks for the translations there and loads them on the server-side. If we look at the page source for the editor, we can see a number of entries like
```HTML
<script id='wp-auth-check-js-translations'>
( function( domain, translations ) {
    var localeData = translations.locale_data[ domain ] \|\| translations.locale_data.messages;
    localeData[""].domain = domain;
    wp.i18n.setLocaleData( localeData, domain );
    } )( "default", {"translation-revision-date":"2021-06-18 13:45:37+0000","generator":"GlotPress\/3.0.0-alpha.2","domain":"messages","locale_data":{"messages":{"":{"domain":"messages","plural-forms":"nplurals=2; plural=n != 1;","lang":"it"},"Your session has expired. You can log in again from this page or go to the login page.":["La tua sessione &egrave; scaduta. Puoi loggarti nuovamente da questa pagina o attraverso la pagina di login."]}},"comment":{"reference":"wp-includes\/js\/wp-auth-check.js"}} );
</script>
```
…Or at least, that's what it looks like when the translations are installed, if not we get empty translations:
```HTML
<script id='wp-auth-check-js-translations'>
    ( function( domain, translations ) {
    var localeData = translations.locale_data[ domain ] \|\| translations.locale_data.messages;
    localeData[""].domain = domain;
    wp.i18n.setLocaleData( localeData, domain );
    } )( "default", { "locale_data": { "messages": { "": {} } } } );
</script>
```

The language packs (translations) are installed for the current site locale when we install the plugin, which is why the translations are appearing (and remaining) when we install new versions of the plugin.

However, the language packs do not seem to be installed when we change the remote site locale or the remote user locale, and we don't seem to be syncing the wpcom user locale across to the remote site.

If we ssh in we can install the language packs with something like `wp language plugin install full-site-editing fr_FR` and they appear no problem, so we just need to figure out why they're not being loaded automatically.

#### All the locales

I noticed that the user on my test site has their locale set to "Site Default" rather than whatever the wpcom user has set in wordpress.com/me, but it looks like the plugin is ignoring that value anyway and loading the translations for the site locale instead.

I'm not sure yet what's happening with the site locale when an Atomic site is created,  or what locale information is synced by jetpack, but I think we'll want to sync the locale data and trigger installation of the appropriate language packs when we do.

#### Missing Starter Page Template Data

I'm seeing this in the page source of my test site, and the layout picker isn't working, but I'm not sure if it's a legitimate error or just a JN quirk yet:
```
<script id='starter-page-templates-error-js-after'>
console.warn("No data received from the vertical API. Skipped showing modal window with template selection.");
</script>
```

**Comment by deBhal** [comment] 2021-07-08 01:14
There are few different interacting issues at play:

- There's no mechanism to automatically update the translations in response to a locale change on atomic/jetpack sites, so the user may need to update their translations manually after changing the locale of their account or site.  On wpcom this is never a problem because all the locales are installed all the time. There is a cron job that sometimes installs the plugins, but it only registers site-locale changes and can have a long delay (several hours, potentially 12 or more).
![WordPress_Updates_‹_Titre_du_site_—_WordPress](https://user-images.githubusercontent.com/5952255/124845376-fa968d80-dfd9-11eb-8f3e-cfeeaf96ea02.jpg)

- While UI in general is rendered in the User Locale, the page templates are explicitly shown in the Site Language because that's what will be rendered to visitors of the site. Several related elements are rendered in the Site Language as well, and so part of the problem with the specific "Add a Page" string reported in this issue is that this section of UI is being rendered in the User Locale while most of the elements in that modal are rendered in the Site Locale. This isn't the cause of the string being untranslated, it just makes things more complicated and explains why only that specific string is untranslated when everything else is handled correctly.

- The previous point not withstanding, that specific string does seem to be missing from (some) language pack downloads. On my test site, the language pack being downloaded was https://downloads.wordpress.org/translation/plugin/full-site-editing/2.21/fr_FR.zip which is missing that specific string (and a few others). The translations installed with the "Update Translation" button do have the string, but I haven't determined what URI they're being fetched from.

So it seems like this is not an ETK issue, but an issue or question for jetpack sites and/or Atomic sites. Users may well not want us installing translations without their express permissions, so we might want something atomic-specific, or it might be best as an opt-in jetpack feature that we turn on for our sites.

I've pinged Team Global internally to take over the issue and taken the "Editing Toolkit" label off.

I'll leave the issue open for now, but they'll likely want to close it in favour of one that gets more immediately to the point.

**Closed as completed** 2022-08-26 00:54 UTC
Labels: Bug, i18n
