### ISSUE TITLE
Unsubscribed subscribers continue to receive new post email notifications

### ISSUE THREAD

**Issue by maciejpilarski** [Automattic/wp-calypso#84144] opened 2023-11-13 13:17 UTC
### Quick summary

Unsubscribed subscribers continue to receive new post email notifications even if they remove the subscription from their reader.

ZD7300806

Both unsubscribed but continue to be visible as subscribed on the user site and receive emails.
Logstash logs:

I was able to reproduce the issue on my side.

### Steps to reproduce

1. Signup at https://vikalex.life/gesundeernaehrung/#Melde_dich_an_um_Updates_zu_erhalten
2. User is added to the Newsletter subscribers
3. Unsubscribe from the site via https://wordpress.com/read/subscriptions/:
https://d.pr/i/leGzNK
4. The subscription gets removed from my Reader but I am still visible on the Subscribers list on the user site.

### What you expected to happen

Subscribers should be removed from the user site and not receive any new notifications.

### What actually happened

Both unsubscribed but continue to be visible as subscribed on the user site and receive emails.
Logstash logs.

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by liviopv** [comment] 2023-11-14 14:10
@Automattic/apex is this something you can help with?

**Comment by maciejpilarski** [comment] 2023-11-20 20:47
📌 REPRODUCTION RESULTS 
– Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
It was a bug reported created initially by me and I was able to reproduce the issue on my side.

📌 ACTIONS
– Triaged

**Comment by ebinnion** [comment] 2024-03-11 18:17
@simison - can you provide some product oversight here and then perhaps I can work with Apex to fix?

**Comment by tellisbethel** [comment] 2024-04-25 12:35
Howdy! I have a user who says they have a former subscriber who is still getting notification emails (and is rather frustrated about it). I see when the subscriber subscribed and then later unsubscribed in UserRC. They're not on the subscriber list of the user and the user's site is not in their Reader list of subscriptions. 

I don't see any sign of the former subscriber receiving posts by email from the user in logtash, while it's clear that other subscribers do. Still the former subscriber supplied a screenshot of them receiving a recent post email notification from the site! This bug sounds like it might be related. 

Ticket: [8088302-zd-a8c](https://a8c.zendesk.com/agent/tickets/8088302)

**Comment by lsl** [comment] 2024-08-15 02:24
@Automattic/vertex / @Automattic/zap is the issue here that users are subscribing via email separately from their wpcom user account or something like that?

Reading through the background of https://github.com/Automattic/wp-calypso/issues/84032 I noticed there is two ways you can be subscribed. Is that unsubscribe link being generated / actioned correctly?

**Comment by simison** [comment] 2024-08-20 10:22
@lsl WP.com and "email only" subscribers indeed get separate unsubscribe links, but they both are functioning fine and we haven't gotten recent feedback about issues with unsubscribe links. 

Considering this report is from 2023 and there's been only two cases, I don't think this is a high priority issue unless we get a fresh report that we can investigate closer what's actually going on.

**Comment by mpkelly** [comment] 2024-08-23 03:54
I tested this just now and wasn't able to reproduce it. A couple of comments:

1. Blog owners can add subscribers without any confirmation from the subscriber. Is this expected behaviour? Normally, it's polite to ask for confirmation. 
2. When I create my first newsletter post and view it, a popup asks me (the author) to subscribe. 

![image](https://github.com/user-attachments/assets/cede7196-283d-4e75-978d-fcbc4033b859)

I also note that the newsletter author/blog owner shows as a subscriber when I add my first real subscriber. Is this expected?

<img width="1045" alt="Screenshot 2567-08-23 at 10 51 22" src="https://github.com/user-attachments/assets/487666dd-1a5b-4409-bb8e-df0b04b39fc8">

**Comment by mpkelly** [comment] 2024-08-23 03:55
@maciejpilarski are you still able to reproduce this one? I think we should consider downgrading the status or even closing it down, as it seems to be fixed.

**Comment by TimBroddin** [comment] 2024-08-23 06:42
@Automattic/zap might be in a better position to answer these, but I'll try.

> I tested this just now and wasn't able to reproduce it. A couple of comments:
> 
> 1. Blog owners can add subscribers without any confirmation from the subscriber. Is this expected behaviour? Normally, it's polite to ask for confirmation.

Yes, this is per design. We assume you've obtained permission from anybody you're adding.

> 2. When I create my first newsletter post and view it, a popup asks me (the author) to subscribe.
> 
> ![image](https://private-user-images.githubusercontent.com/6851384/360785648-cede7196-283d-4e75-978d-fcbc4033b859.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTUwMzMsIm5iZiI6MTcyNDM5NDczMywicGF0aCI6Ii82ODUxMzg0LzM2MDc4NTY0OC1jZWRlNzE5Ni0yODNkLTRlNzUtOTc4ZC1mY2JjNDAzM2I4NTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDYzMjEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ4MWU3MDk1ODdjZTU0M2Y1NzgwMTM4ZWRhMDFmYTZkNDBhZjZhNDM3OGQ0ZGI2ZWJkYmUxZTc1YWM1ZGQzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oCKxSDBbO7NcMouRMou8TcIkjX58y4MIjL-1_Xs3IkI)
> 

I'm guessing we don't make an exception for the blog owner here to avoid getting support tickets saying they don't see the subscriber modal popup. 

> 
> I also note that the newsletter author/blog owner shows as a subscriber when I add my first real subscriber. Is this expected?
> 
> <img alt="Screenshot 2567-08-23 at 10 51 22" width="1045" src="https://private-user-images.githubusercontent.com/6851384/360785302-487666dd-1a5b-4409-bb8e-df0b04b39fc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTUwMzMsIm5iZiI6MTcyNDM5NDczMywicGF0aCI6Ii82ODUxMzg0LzM2MDc4NTMwMi00ODc2NjZkZC0xYTViLTQ0MDktYmI4ZS1kZjBiMDRiMzlmYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDYzMjEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI2OTkwMGU0NjgxMTFjMTJjZGJlNDJkZDNkNjg4MjYyN2E4M2QzNjA2NWQyZjFjZjU3ODM5N2E1ZGQzNTk3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jEPlnOkbit8ByHVS_vK3Bajp2GMHu74PN8Qbt_FnqN4">

I think this is expected.
We want to show a launchpad before you add your first real subscriber. If you're already subscribed yourself (default behavior) we only show you in the list after the first real subscriber is added.

I agree that this is confusing.

https://github.com/Automattic/wp-calypso/blob/dff739ed3efe7c9f4f2c7359a4de911d9ca435c6/client/my-sites/subscribers/components/subscriber-list-container/subscriber-list-container.tsx#L49-L53

**Comment by davemart-in** [comment] 2024-10-14 19:18
Moving this from The One Board to the Zap Team board to help sort out.

**Comment by simison** [comment] 2024-10-15 08:09
[All above ](https://github.com/Automattic/wp-calypso/issues/84144#issuecomment-2306130943) is working as expected;
- Add or import subscribers without confirmation emails sent to everyone; consider when you're moving from another host/mailing list provider to ours.
- The popup nudging to subscribe shows up for admins; we used to hide this, but we got tons of complaints from admins who could not test how their site and popup looked to readers.
- You as an admin are a subscriber to your own site. Not the smoothest UX but right now as expected.

Let's close this very old issue that nobody is able to replicate, and if we get fresh reports, feel free to re-open or create a new one.

**Closed as completed by simison** 2024-10-15 08:09 UTC
Labels: Bug, [Pri] Normal, [Feature] Subscriptions, [Feature] Calypso & wp-admin Navigation, Triaged, Customer report [LEGACY], [Platform] Atomic, [Status] Priority Review Triggered, Newsletters, [Product] WordPress.com, [Feature Group] User Interaction & Engagement
