### ISSUE TITLE
Nav Unification: Log out button on Me page doesn't log out user completely out of Atomic.

### ISSUE THREAD

**Issue by ajaykj** [Automattic/wp-calypso#51662] opened 2021-04-03 07:47 UTC
The Gravatar in the top-right hand section (both from Calypso and WP Admin) is now redirecting to the https://wordpress.com/me page. This causes the user to not log out completely from the site.

### Steps to reproduce the behavior

1. Go to any site in Calypso e.g. https://wordpress.com/home/
2. Click on the Gravatar in the top-right hand section
3. Click the "Log Out" button
4. Visit the homepage or any page of the previously selected site

#### What I expected to happen
WPCOM bar to not appear on the top of the site

#### What actually happened
WPCOM bar appears on the top of the site

#### Browser / OS version
Tested using Chrome 89 on macOS 11.2 and Firefox 87 on macOS Big Sur

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
Both

#### Is there any console output or error text?
No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It affects all WPCOM sites (Especially the atomic sites)

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Markup on 2021-04-03 at 13:12:20](https://user-images.githubusercontent.com/35197279/113472126-6bc82100-947e-11eb-8f08-1157ce6baaf6.png)

**Comment by sophiegyo** [comment] 2021-04-03 08:59
I had another report of this here (but specifically with Microsoft Edge - perhaps the user's other browsers have Do Not Track inactive?) : 28794205-hc

**Comment by cpapazoglou** [comment] 2021-04-08 07:29
This should be happening only on Atomic sites. You can share this link for the time being `/wp-login.php?action=logout`.

**Comment by nerdysandy** [comment] 2021-04-09 21:41
I can replicate it on my Free plan simple site too. What @ajaykj reported above is also a simple site :-/

**Comment by xpurichan** [comment] 2021-04-10 19:43
Another report in 28936281-hc.

**Comment by obenland** [comment] 2021-04-13 20:42
This should not be something that has changed with Nav Unification, should it?

**Comment by kwight** [comment] 2021-04-15 20:32
I feel like this has come up before and was a `wontfix`, the idea being that logging out here is logging you out of just WP.com, and we wouldn't want to also log them out of their Atomic WP Admin. Confusing for sure, and asking expected behaviour of users, I could see it being a 50/50 split. 🙃

**Comment by kriskarkoski** [comment] 2021-04-16 02:21
@kwight Some of the example sites here are Simple so this sounds a bit different. Perhaps something with the changes to cookies and custom domains?

In the Atomic context this is one prior report I'm aware of and the experience from February is documented there:

374-gh-Automattic/atomic

**Comment by kwight** [comment] 2021-04-19 17:10
> Some of the example sites here are Simple so this sounds a bit different.

@kriskarkoski Oh! That's just a legit bug then, and should be a separate issue.

**Comment by brandonpayton** [comment] 2021-04-26 17:11
> In the Atomic context this is one prior report I'm aware of and the experience from February is documented there:
>
> 374-gh-Automattic/atomic

Somehow, this broke for WoA sites between February 15 and today. Clicking on the user avatar no longer shows the righthand slide-in menu with a button that logs out from the single WoA site.

Users have to be able to logout from their WoA sites somehow.

**Comment by obenland** [comment] 2021-04-26 17:19
@mmtr It looks like that link was introduced in https://github.com/Automattic/jetpack/pull/18495?

**Comment by mmtr** [comment] 2021-04-27 12:53
> @mmtr It looks like that link was introduced in [Automattic/jetpack#18495](https://github.com/Automattic/jetpack/pull/18495)?

Yeah, in that PR we aligned the topbar links with the new unified admin menu links, so the user avatar redirects to `wordpress.com/me` instead of displaying a custom righthand slide-in menu. It seems that the logout button in Calypso does not close the WP Admin session on Atomic sites.

**Comment by xpurichan** [comment] 2021-04-28 15:18
Another report in 3881455-hc

**Comment by CompChris** [comment] 2021-04-28 19:14
Report in 28746602-hc

**Comment by happychait** [comment] 2021-05-02 22:19
Another report in 3909056-zen

**Comment by mmtr** [comment] 2021-05-05 15:04
Prepared a fix for this in 678-gh-Automattic/wpcomsh and D61021-code.

**Comment by mmtr** [comment] 2021-05-10 14:32
This should be fixed now that 678-gh-Automattic/wpcomsh and D61021-code have been deployed.

**Closed as completed by mmtr** 2021-05-10 14:32 UTC
Labels: Bug, [Pri] High, [Feature] Calypso & wp-admin Navigation, Triaged, Simple/Atomic Parity

**Comment by brandonpayton** [comment] 2021-05-10 16:48
Thanks for fixing this, @mmtr! The fix works well for me and should greatly reduce user confusion.
