### ISSUE TITLE
Gutenboarding: Scroll position should reset when going to style/font selection

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#40767] opened 2020-04-03 16:21 UTC
#### Steps to reproduce

1. Starting at URL: https://wpcalypso.wordpress.com/gutenboarding/design
2. Scroll down to the bottom
3. Click the design "Doyle"
4. Now you land on the font/style page and can't see the top controls

#### What I expected
When a user goes from Design to Style/Font page the scroll should reset to top

#### What happened instead
Instead, the page stays scrolled to the bottom and you can't see the top controls

#### Screenshot / Video
https://d.pr/v/d1KmXl

**Comment by alshakero** [comment] 2020-04-06 10:29
This is unreproducible since https://github.com/Automattic/wp-calypso/pull/40761 made the font/style page without scrolling. Closing as obsolete.

**Comment by sirreal** [comment] 2020-04-06 10:38
You can still get scrolls. It's easiest with the mobile view or at strange viewport sizes:

![Screen Shot 2020-04-06 at 12 37 20](https://user-images.githubusercontent.com/841763/78549924-7e742f80-7803-11ea-9fcd-42a0331eeb57.png)

**Comment by alshakero** [comment] 2020-04-06 10:43
That's right, but not right after you land!

**Comment by sirreal** [comment] 2020-04-06 11:09
You're right 🙂

**Closed by sirreal** 2020-04-06 11:09 UTC
Labels: [Pri] High, [Type] Task
