### ISSUE TITLE
Block editor: Schedule posts calendar should identify dates where other posts are scheduled

### ISSUE THREAD

**Issue by xpurichan** [Automattic/wp-calypso#42986] opened 2020-06-04 15:24 UTC
#### Summary

The classic editor provided the option to schedule a publish date for a new blog post on a calendar. When the calendar loaded it would display a circle around other dates which already had another blog post scheduled.

In the block editor we do still display a calendar for scheduling a blog post, but it doesn't identify dates where other blog posts have been scheduled.

This would be a helpful feature to add back in to the block editor, particularly for customers who schedule posts often and want to continue using this feature as we switch them to the block editor this month.

Here is what this looks like in the classic editor:
![Screen Shot 2020-06-04 at 11 19 36 AM](https://user-images.githubusercontent.com/33190975/83775871-77c43600-a655-11ea-9da8-d3448bfbc898.jpg)

In the block editor I scheduled a blog post for June 5th on this test site, but when I try and schedule another blog post we don't see a circle around June 5th, identifying it as a date where a post is already scheduled.

![Screen Shot 2020-06-04 at 11 21 15 AM](https://user-images.githubusercontent.com/33190975/83775995-a215f380-a655-11ea-9093-2034605c94a7.jpg)

#### Context / Source

#user-report in 3019645-zd

**Comment by darnelldibbles** [comment] 2020-08-14 14:59
Another request for this feature: https://wordpress.com/forums/topic/visibility-of-scheduled-posts-in-calendar/

**Comment by thehenrybyrd** [comment] 2020-08-19 10:36
Another in a chat today; the user was quite frustrated that this is no longer available (even in wp-admin) after the depreciation of the Calypso editor on WordPress.com. User report in #23406090-hc

**Comment by devNigel** [comment] 2020-08-20 04:29
I also received a query about this in a chat today. #23484613-hc

**Comment by AMcGrady** [comment] 2020-08-20 15:23
Another request for this in chat: #6557296-hc

**Comment by lakellie** [comment] 2020-08-20 15:48
Another request in #23498305-hc

**Comment by aleone89** [comment] 2020-08-20 18:07
Another request here: #23492087-hc

**Comment by Fangthewonderdog** [comment] 2020-08-24 16:47
As a WordPress user, I need this functionalty back.

**Comment by supernovia** [comment] 2020-08-24 20:02
Noting this one too
https://wordpress.com/forums/topic/calendar-no-longer-shows-all-scheduled-posts-in-block-editor/

This issue is also recorded here: 
https://github.com/WordPress/gutenberg/issues/13713

**Comment by deancroyal** [comment] 2020-08-31 15:52
Another request: [https://wordpress.com/forums/topic/publishing-future-date/](https://wordpress.com/forums/topic/publishing-future-date/)

**Comment by davemart-in** [comment] 2020-09-01 14:29
Thanks for adding this issue and +1ing each instance that we come across. This is super helpful. In order to streamline issues, I'm closing this out as a duplicate of https://github.com/Automattic/wp-calypso/issues/42986

**Closed by davemart-in** 2020-09-01 14:29 UTC
Labels: Feature request, [Pri] Normal, [Size] S

**Comment by lakellie** [comment] 2020-09-01 14:48
@davemart-in Looks like that is the same issue that was just closed here - is the correct one to report in moving forward #28567?

**Comment by davemart-in** [comment] 2020-09-01 14:54
@lakellie Yes please! They are all interlinked now, but it's easier to prioritize if we just keep one single issue open. I just picked the one that has been open the longest.

**Comment by davemart-in** [comment] 2020-09-01 14:56
And sorry, I had pasted the wrong issue above. I just updated it.
