### ISSUE TITLE
CoBlocks Carousel Block Breaking Editor When Trying to Remove

### ISSUE THREAD

**Issue by TPilgs** [Automattic/wp-calypso#73288] opened 2023-02-13 17:34 UTC
### Quick summary

The CoBlocks Carousel is causing an issue when trying to remove it from the post editor. When you add the Carousel block and subsequently try to remove it from the editor, it crashes the entire editor.

### Steps to reproduce

1. Make sure the CoBlocks plugin is active. (I tried on both Canape and Twenty Twenty themes)
2. Add a CoBlock Carousel. For mine I added three basic thumbnail images.
3. Try and remove the block via the three dots/kebab menu.
4. Watch the editor crash :D

### What you expected to happen

The block should just simply be removed.

### What actually happened

The attempted removal of the block breaks the editor.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

I had to deactivate the CoBlocks plugin to get rid of the block.

**Comment by kavyagokul** [comment] 2023-02-16 10:44
📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/71777

**Closed as completed by kavyagokul** 2023-02-16 10:44 UTC
Labels: Bug, [Pri] High, [Platform] Atomic
