### ISSUE TITLE
Themes: Consider adding previews in the theme switch modal.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#52792] opened 2021-05-12 15:03 UTC
On theme switch, users are asked if they would like to use the homepage that comes with the new theme, or keep their existing homepage content. Mentioned by @ollierozdarz and @simison in p1620813916187000-slack-C0202PMUXLJ, we could give the user a preview of what those choices would look like.

We already have an endpoint that does similar previews for signup at `/new/design`, so that could be leveraged for this exploration.

![image](https://user-images.githubusercontent.com/349751/117998193-8355bd80-b2f8-11eb-96ad-75ef596e067b.png)

**Comment by kwight** [comment] 2021-06-07 20:13
@blackjackkent This will be your project to lead starting Monday. 🚀  @onuro may or may not have some fine-tuned designs to work from; regardless, we can start with existing Calypso components for the general idea.

**Comment by onuro** [comment] 2021-06-08 23:41
Here's my take on it:

After some discussion with @ianstewart we thought creation of a support page about "theme switch homepage content" and adding the link in the modal would help avoid the long explanatory text in the modal.

**Figma file:** https://www.figma.com/file/QnkOH11BM3MoPFOFr2OTBC/Theme-Showcase-Revamp?node-id=80%3A1346

Let me know. Thanks!
![image](https://user-images.githubusercontent.com/645713/121271147-baa19500-c8cb-11eb-80c6-82a9f7fe0410.png)

**Comment by ollierozdarz** [comment] 2021-06-09 00:02
This is looking great @onuro, @ianstewart! 🙂 It could also be worth trying an exploration with the `Learn more` in the bottom bar of the modal (grouped with the 'After activation...') instead of at the top.

**Comment by onuro** [comment] 2021-06-09 00:14
> This is looking great @onuro, @ianstewart! 🙂 It could also be worth trying an exploration with the `Learn more` in the bottom bar of the modal (grouped with the 'After activation...') instead of at the top.

Thank you @ollierozdarz! I was also skeptical about the position of the "**Learn more**" link. However the content on the left bottom bar only shows up if you choose to replace content, and having the support link there as well felt too much. 

If only we could trim that bottom bar content even more, I also believe bottom bar could be a better place for the support page link.

Here's what I think options would be:

- Find a way to shrink the content on drafted homepage and add the support link - displaying only the support link on first option, and next to the drafted homepage content on the second option.
- Ignore and remove the drafted homepage content text and leave the explanation to support link, with displaying the link at all times.
- Well, expand the width of the modal :)

**Comment by ollierozdarz** [comment] 2021-06-09 00:32
> However the content on the left bottom bar only shows up if you choose to replace content, and having the support link there as well felt too much.

Ah I see. That makes sense!

Sounds like you've got some solid backup options 🙂

**Comment by kwight** [comment] 2021-06-09 14:50
Sweet! Is the bottom bar content a pattern used anywhere else in Calypso? I don't think I've seen it before. Was there a reason to not have that content below the screenshots with the Learn More link (it would seem to better fit with existing patterns)?

Nice work 👍

**Comment by kwight** [comment] 2021-06-09 17:03
The right preview should be simple, as it would be the same images used in signup, for example. The left preview may be more difficult – I assume we'll need some way of dynamically generating that image and serving it quickly (I don't know if that's something mShots does or not).

**Comment by onuro** [comment] 2021-06-09 19:30
> Was there a reason to not have that content below the screenshots with the Learn More link (it would seem to better fit with existing patterns)?

Thank you @kwight! The positioning on that content was solely a design decision. I'll populate some options for repositioning the content and the Learn More button.

**Comment by onuro** [comment] 2021-06-09 20:37
We might need to work on the wording, but here's an iteration to it:

Homepage content will be changed wit demo content:
![image](https://user-images.githubusercontent.com/645713/121424360-ec713500-c979-11eb-9483-1f012caea1b6.png)

Homepage content is going to be preserved:
![image](https://user-images.githubusercontent.com/645713/121424470-0ad73080-c97a-11eb-9e8b-7a1dfc9d9280.png)

Now we don't have to inform any more when the 1st option is selected, but thought it would be weird showing only "read more" link centered without the content. 

Let me know what you think. Thanks!

**Comment by kwight** [comment] 2021-06-09 22:31
Noice! @ianstewart any opinions on the Close cross and the checkmark? I thought I've seen existing `X`s in Calypso that are square-framed, but couldn't find anything, and I wonder if we need a wider design discussion if we add both to all modals across Calypso (or add them to just one, which seems odd too).

> Is the bottom bar content a pattern used anywhere else in Calypso?

Side note, @onuro , we _do_ use that space to the left for a Delete text link sometimes, found that in Media (and other places I'm sure):

<img width="700" alt="Screen Shot 2021-06-09 at 3 30 06 PM" src="https://user-images.githubusercontent.com/349751/121437803-ad21f480-c937-11eb-999f-b1bf95884f4a.png">

**Comment by jordesign** [comment] 2021-06-10 02:48
Pinging @donalirl in case it is decided we need to have a dedicated Support Doc for Theme Switching (mentioned above).

We've also got another open issue (https://github.com/Automattic/wp-calypso/issues/53174) in regard to closing the modal - will we cover that as part of this?

**Comment by donalirl** [comment] 2021-06-10 08:13
This would be a useful doc to create alright! I've opened an issue for it: 1125-gh-Automattic/en.support-docs-content

When would this be needed by?

**Comment by simison** [comment] 2021-06-10 08:38
@onuro This is a total nit pick and feel free to ignore:

<img width="123" alt="Screenshot 2021-06-10 at 11 22 44" src="https://user-images.githubusercontent.com/87168/121490961-312eb780-c9de-11eb-88e0-79db90d8d7bb.png">

I would just use a core or Calypso component for this to stay consistent.

Here's from Gutenberg editor:

<img width="144" alt="Screenshot 2021-06-10 at 11 26 16" src="https://user-images.githubusercontent.com/87168/121491602-c631b080-c9de-11eb-931e-8f482ebedc39.png">

<img width="263" alt="Screenshot 2021-06-10 at 11 26 57" src="https://user-images.githubusercontent.com/87168/121491598-c5991a00-c9de-11eb-9890-6bedde98247a.png">

Here's page template picker (when creating new page):

<img width="128" alt="Screenshot 2021-06-10 at 11 26 09" src="https://user-images.githubusercontent.com/87168/121491614-c8940a80-c9de-11eb-901c-756a0d9eac68.png">

Similarly, for the screenshots, I'd also look for existing similar things — but again there could be valid reasons not to bother try stay similar. Just the fact that it's selectable options might be enough. Maybe the bloc kstyle picker in Gutenberg could be inspiration? :-) Here are design picker (`/new/design`) and page template picker (when creating a new page):
 
<img width="756" alt="Screenshot 2021-06-10 at 11 29 18" src="https://user-images.githubusercontent.com/87168/121492031-2f192880-c9df-11eb-9e6c-d9036b7afd2c.png">
<img width="1640" alt="Screenshot 2021-06-10 at 11 28 49" src="https://user-images.githubusercontent.com/87168/121492081-3b9d8100-c9df-11eb-9ed4-166db7b07d25.png">

Anyway, totally up to you of course! Just food for thought.

**Comment by simison** [comment] 2021-06-10 08:42
> The right preview should be simple, as it would be the same images used in signup, for example. The left preview may be more difficult – I assume we'll need some way of dynamically generating that image and serving it quickly (I don't know if that's something mShots does or not).

@kwight Yup! You could check with team Ganon, or Luna (or Andrew & Ramon in View) for some technical examples and existing components and APIs that you can re-use. Those images in page templates & signup are dynamically generated from API, and screenshots come from mShots. I think you mostly have all the pieces around for this, and would need to combine them in a way that works as intended. Remember to mind  i18n as well (which those APIs already support).

**Comment by onuro** [comment] 2021-06-10 17:13
> @onuro This is a total nit pick and feel free to ignore:
> 
> <img alt="Screenshot 2021-06-10 at 11 22 44" width="123" src="https://user-images.githubusercontent.com/87168/121490961-312eb780-c9de-11eb-88e0-79db90d8d7bb.png">
> 
> I would just use a core or Calypso component for this to stay consistent.

Thank you @simison! I preferred rounded edges feel more friendly to users, and that's why I went with it. But for consistency sake, I updated that close button.

![image](https://user-images.githubusercontent.com/645713/121567875-bbe7d480-ca27-11eb-95b1-08d79388ab0e.png)

> Similarly, for the screenshots, I'd also look for existing similar things — but again there could be valid reasons not to bother try stay similar. Just the fact that it's selectable options might be enough. Maybe the bloc kstyle picker in Gutenberg could be inspiration? :-) Here are design picker (`/new/design`) and page template picker (when creating a new page):

The styling of the radio-card was solely a design and a11y decision with also consistency in mind. I basically applied the similar focus state style of radios into the selectable block:

![image](https://user-images.githubusercontent.com/645713/121568244-2b5dc400-ca28-11eb-8a7a-48837b71214d.png)
![image](https://user-images.githubusercontent.com/645713/121568310-3fa1c100-ca28-11eb-99ed-8f005cd42b73.png)

**Comment by onuro** [comment] 2021-06-10 17:14
Latest status with updated close button:
![image](https://user-images.githubusercontent.com/645713/121568549-7c6db800-ca28-11eb-848c-634b52cf19b0.png)

**Comment by kwight** [comment] 2021-06-14 16:12
Let's make sure we also consider mobile, and whether we can see as much as possible for the preview (there may be a hover affect for scroll, but larger previews could be useful anyways).

**Comment by kwight** [comment] 2021-06-14 16:16
Fonts also need to be considered – global styles (Gutenberg) are not theme-specific, so they should be loaded in the left preview.

**Comment by kwight** [comment] 2021-06-14 16:22
Guidance for prioritization:
* general color,
* correct content,
* accurate fonts.

**Comment by kwight** [comment] 2021-06-14 16:30
Existing docs: https://wordpress.com/support/themes/#switch-themes

**Comment by kwight** [comment] 2021-06-14 19:42
Noting that there's another related concern for this modal, which is when the user is switching from a retired theme – we don't let them know that they might not be able to get their old theme back if they switch. In fact, @Aurorum has been working on https://github.com/Automattic/wp-calypso/pull/40793 that merged this modal with a new modal for just that purpose.

We'll need to keep focussed on implementing this modal first, and shouldn't try to add any handling for retired themes yet at this point (the current sprint); let's just keep it in mind as we also evaluate further modal design possibilities. cc/ @blackjackkent @onuro @ianstewart

**Comment by mreishus** [comment] 2021-06-14 22:03
>  Those images in page templates & signup are dynamically generated from API,

Not all of them are; for example 2021 isn't, it's a png sitting in the wp-content directory.
![2021-06-14_16-53](https://user-images.githubusercontent.com/937354/121964350-0bcce100-cd31-11eb-9b35-8cb2e6c4ccfb.png)

The API behind the dynamically generated urls like this: [/v1/template/demo/barnsbury/barnsbury](https://public-api.wordpress.com/rest/v1/template/demo/barnsbury/barnsbury?font_headings=Open%20Sans&font_base=Chivo&site_title=Barnsbury&viewport_height=700&language=en&use_screenshot_overrides=true) wants themes that either
*  belong [to a hardcoded list](redacted)
* or that [have a starter site that contains a special `block-patterns-source-site` tag](redacted).

I'm guessing it has these restrictions because it uses [pattern based manipulations](redacted) and requires new themes that support that (it [gets a "PatternStore"](redacted) for a starter site?). 

Since the modal would have to work for any theme, this endpoint isn't looking like a good match to me so far.

_Edit: Redacted opengrok links, they are here: 298d2-pb_

_Edit2_: I just remembered that the theme switch modal only appears for themes that have the `auto-loading-homepage` tag, so depending on how that overlaps with the hardcoded list + `block-patterns-source-site`, maybe it's more promising. However, [2021 not working](https://public-api.wordpress.com/rest/v1/template/demo/twentytwentyone/twentytwentyone?font_headings=Open%20Sans&font_base=Chivo&site_title=Barnsbury&viewport_height=700&language=en&use_screenshot_overrides=true) still seems like a bad sign.

**Comment by simison** [comment] 2021-06-15 11:29
@mreishus sorry for not being more specific — I referred to these two interfaces, not the theme showcase —

- Go to `wordpress.com/new` and progress until design step ([see code](https://github.com/Automattic/wp-calypso/blob/1fb3c8e71c52568a41afad184dddb7bc803ff581/packages/design-picker/src/utils/available-designs.ts#L27-L43)):

    <img width="1499" alt="image" src="https://user-images.githubusercontent.com/87168/122044312-08932d00-cde5-11eb-8b81-9aef7487f42f.png">

- Create a new page and see this interface ([see code](https://github.com/Automattic/wp-calypso/blob/1fb3c8e71c52568a41afad184dddb7bc803ff581/packages/page-pattern-modal/src/components/pattern-selector-item.tsx#L23-L30)):

    <img width="1601" alt="Screenshot 2021-06-15 at 14 24 34" src="https://user-images.githubusercontent.com/87168/122044618-60319880-cde5-11eb-8f12-df588d2c7e72.png">

See also [MShotsImage component](https://github.com/Automattic/wp-calypso/tree/1fb3c8e71c52568a41afad184dddb7bc803ff581/packages/design-picker/src/components/mshots-image), which could perhaps be moved to `@automattic/components` for easier sharing.

Hope this helps! :-)

**Comment by mreishus** [comment] 2021-06-15 14:48
correct, neither of those screens are capable of displaying twentytwentyone because it does not pass the restrictions of the api:

* [/rest/v1/template/demo/balasana/balasana](https://public-api.wordpress.com/rest/v1/template/demo/balasana/balasana?font_headings=Open%20Sans&font_base=Chivo&site_title=Balasana&viewport_height=700&language=en&use_screenshot_overrides=true) - Works
* [/rest/v1/template/demo/twentytwentyone/twentytwentyone](https://public-api.wordpress.com/rest/v1/template/demo/twentytwentyone/twentytwentyone?font_headings=Open%20Sans&font_base=Chivo&site_title=Balasana&viewport_height=700&language=en&use_screenshot_overrides=true) - Error, no source site

In my investigation, this API isn't trivially modifiable to load content from arbitrary sites since it depends on patterns and pattern libraries.

Edit: Interestingly enough, mixing them does work (in one direction, twentytwentyone/balasana, not balasana/twentytwentyone):
* [/rest/v1/template/demo/twentytwentyone/balasana](https://public-api.wordpress.com/rest/v1/template/demo/twentytwentyone/balasana?font_headings=Open%20Sans&font_base=Chivo&site_title=Balasana&viewport_height=700&language=en&use_screenshot_overrides=true)
So it can apply a theme to pattern-based content (where the theme with content either belongs to a hardcoded list or has a starter site that contains a special block-patterns-source-site tag).

**Comment by onuro** [comment] 2021-06-16 11:03
Mobile options attached. There was a discussion w @ollierozdarz and @ianstewart about reducing the weight of the text content on the modal, so I'm attaching 2 iterations with more and less content; for mobile and desktop.

**Mobile - Default**(little trouble of modal height exceeding viewport limits on devices with smaller screen sizes):
![image](https://user-images.githubusercontent.com/645713/122207522-e5cb4c00-ceaa-11eb-8351-ecf1b7d34d78.png)

Mobile - Content trimmed:
![image](https://user-images.githubusercontent.com/645713/122207554-ef54b400-ceaa-11eb-84f4-58c85f3fdef0.png)

I'll also try with actual browser chromes added in mobile, which could reduce the vertical real estate we have to an even smaller limit.


Also for desktop, there's a higher length preview style applied based on some feedback from the team. Both following iterations have that change.

Desktop - Default:
![image](https://user-images.githubusercontent.com/645713/122208053-7f92f900-ceab-11eb-812a-4746f5210f5d.png)

Desktop - Content trimmed:
![image](https://user-images.githubusercontent.com/645713/122208120-96395000-ceab-11eb-9ea5-69cda90d8fd1.png)

Let me know what you think. Thanks!

**Comment by onuro** [comment] 2021-06-16 16:45
@olaolusoga suggested we could leverage additional real estate by making the modal full screen for mobile and I loved the idea:

![image](https://user-images.githubusercontent.com/645713/122260041-7e79c000-cedb-11eb-822d-118a940444d0.png)

Not sure if the modal component is ready for such an extension but had to try.

**Comment by onuro** [comment] 2021-06-16 18:51
Updated mobile w fullscreen modal component + browser chrome: Ugh...(for small device)

![image](https://user-images.githubusercontent.com/645713/122275963-f6041b00-ceec-11eb-8632-175bd39bdf03.png)

**Comment by ollierozdarz** [comment] 2021-06-17 05:05
These are looking great @onuro! Nice job  🙂

**Comment by kwight** [comment] 2021-06-17 14:45
> Updated mobile w fullscreen modal component + browser chrome: Ugh...(for small device)

Hm – I'm not sure the previews are worth it on mobile, they're very cramped. 🤔

**Comment by blackjackkent** [comment] 2021-06-17 16:28
> Hm – I'm not sure the previews are worth it on mobile, they're very cramped. 🤔

I would agree with this.

**Comment by onuro** [comment] 2021-06-17 20:57
I'm leaning towards that too, since the more device goes smaller, the more it makes no sense to have the previews anymore. 

Should we just hide the previews for mobile, let's say for <410/400px? Or do we use standard breakpoints?

**Comment by donalirl** [comment] 2021-06-18 07:45
@onuro here's the link to the new doc for the Learn More link: https://wordpress.com/support/changing-themes/

I'll add in a screenshot of the new modal once it's live.

**Comment by simison** [comment] 2021-06-18 10:26
There might be space on landscape mobile to have those, and put buttons side by side?

Would it be helpful to show a narrower mobile version of the site on mobile screens, side by side? Since the goal of screenshots is to communicate clearly what each option means, I don't think that need goes away on mobile.

**Comment by kwight** [comment] 2021-06-24 00:16
@blackjackkent can you update and close this issue please (maybe add some references to key PRs/diffs and a final screenshot or GIF)? Thanks!

**Comment by blackjackkent** [comment] 2021-06-24 16:44
Yes! This is all live now in production. The majority of the work was merged in https://github.com/Automattic/wp-calypso/pull/53796 and D63076-code, with a few tweaks following after.

Before: 

![image](https://user-images.githubusercontent.com/13437011/123301462-4a0c9200-d4e1-11eb-8426-07482541b61d.png)

After:

![image](https://user-images.githubusercontent.com/13437011/123301487-51cc3680-d4e1-11eb-9404-ab41f85f1754.png)

**Closed as completed by blackjackkent** 2021-06-24 16:44 UTC
Labels: Enhancement, [Feature Group] Appearance & Themes, [Pri] Normal, [Size] S, [Pod] Design Selection
