### ISSUE TITLE
Posts: "Write" button in toolbar doesn't recognize the current blog

### ISSUE THREAD

**Issue by zandyring** [Automattic/wp-calypso#36820] opened 2019-10-16 15:23 UTC
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/day/zandy.blog (or similar site stats page)
2. Click on the "Write" button in the header
3. You will need to select a blog from the list, despite being in the dashboard of a blog

<img width="869" alt="Screen Shot 2019-10-16 at 11 18 29 AM" src="https://user-images.githubusercontent.com/7304712/66933286-dd03e200-f006-11e9-9bb8-a2c511990fc3.png">

#### What I expected
I would have expected to be immediately able to write a post after clicking the button (similar to the experience on mobile). I think this is a sticking point because you always start on the Reader, so you must navigate to a blog to do anything, so having to choose it again feels muddy.

#### What happened instead
Instead I had one more click, which felt really like an unnecessary barrier.

#### Browser / OS version
Chrome Version 77.0.3865.120 (Official Build) (64-bit) / macOS 10.15

#### Context / Source

#reallife #dogfooding

**Comment by lancewillett** [comment] 2020-03-09 18:57
I'm not able to reproduce this on my WordPress.com Simple site lance.blog — when managing that site, and clicking the Write button in the toolbar — I'm taken directly into the editor.

When inspecting the URL for the link target in HTML source, I see `/block-editor/post/lance.blog`.

@zandyring Are you logged in as current member of that site (I know, seems obvious like a "Yes").

Looking at the code... in `client/layout/masterbar/publish.jsx#131` there's a setting for using the direct post editor for the current site if you are in the context of that site.

https://github.com/Automattic/wp-calypso/blob/master/client/layout/masterbar/publish.jsx#L131

```
// the selector is shown only if it's not 100% clear which site we are on.
// I.e, when user has more than one site, is outside the My Sites group,
// or has one of the All Sites views selected.
// otherwise start posting to the selected or primary site right away
```

This tells me there is either a bug... meaning you ARE in the context of one blog and the Calypso app state isn't accurately tracking that... or maybe somehow you were in an "all sites" view when you clicked "Write".

**Comment by kriskarkoski** [comment] 2020-03-09 19:08
I am not able to reproduce either. I tested from Stats as well as Home on a simple and Atomic site. 

@lancewillett I think this was fixed the day following this report with https://github.com/Automattic/wp-calypso/pull/36843 but wasn't connected to this issue. Closing.

**Closed by kriskarkoski** 2020-03-09 19:08 UTC
Labels: Posts, [Type] Bug
