### ISSUE TITLE
Store orders: Refund order modal doesn't always display the action buttons

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#16605] opened 2017-07-26 22:44 UTC
When I went to refund an order, the Refund and Cancel button were hidden at first view:

![screen shot 2017-07-26 at 4 41 54 pm](https://user-images.githubusercontent.com/5835847/28646925-734a9b0c-7221-11e7-8c1f-98abfff6f36c.png)

Once I scrolled down, they showed up.

**Comment by kellychoffman** [comment] 2017-07-26 22:45
@jameskoster will this be fixed by your modal changes PR?

**Comment by jameskoster** [comment] 2017-07-27 10:36
> @jameskoster will this be fixed by your modal changes PR?

Yes.

https://github.com/Automattic/wp-calypso/pull/15718

**Comment by kellychoffman** [comment] 2017-07-27 14:10
Cool! I'll close this then.

**Comment by kellychoffman** [comment] 2017-07-27 14:10
I spoke to soon. I'll leave this open so we remember to tweak the refund modal once your PR is in.

**Comment by ryelle** [comment] 2017-07-27 19:36
@kellychoffman I think this is a duplicate of #15911, closing this in favor of that issue.

**Closed by ryelle** 2017-07-27 19:36 UTC
Labels: Store, [Type] Bug
