### ISSUE TITLE
Blog Post block > Show More button not available to private sites

### ISSUE THREAD

**Issue by kylemcph** [Automattic/wp-calypso#47087] opened 2020-11-04 07:44 UTC
#### Steps to reproduce

1. Start a simple site on WordPress.com, do not set site to public.
2. Add a new page
3. Add the [Blog Posts Block](https://wordpress.com/support/wordpress-editor/blocks/blog-posts-block/)
4. Look for `Show "More" Button` option within Display Settings

#### What I expected

The `Show "More" Button` toggle option to be there.

#### What happened instead

The `Show "More" Button` toggle option does not appear. The button **does** appears when the site privacy settings are set to public.

#### Screenshot / Video

Private site screenshot: https://d.pr/i/L1evVO

Public site screenshot: https://d.pr/i/Fs7uSM

#### Context / Source

Found this while testing for #47067. It was brought to my attention the "Load More" button was loading duplicated posts, and some posts were missing. This is reproducible as well. I opened a separate issue #47086 in regards to that.

User reached out in 24794525-hc about this, follow-up ticket 3457739-zen.

**Comment by jeyip** [comment] 2020-11-11 00:25
Confirmed this problem in chrome. 

1. I added a blog posts block to a page on my website
2. I confirmed that the display settings for the blog posts block _did_ have the `Show "More" Button` toggle available
3. I set the website visibility to private in Settings > General > Privacy
4. I confirmed that the display settings for the blog posts block no longer had the `Show "More" Button` toggle available

The bug also exists when changing website visibility to coming soon. I'm on the fence, but I'm making the priority for this Normal for now because it seems like there is a workaround (toggle it on when the website goes public). I can however, see an argument being made that this is unreasonable for the user, and we might update this to priority High if necessary.

**Comment by jeyip** [comment] 2020-11-13 18:42
After more research, it looks like this is expected behavior and noted in the `Blog Posts Block` documentation 

> The Show “More” Button toggle will let you have a button at the bottom of the block that will let visitors load more posts. Note that this feature will not be available unless the site is public.

**Comment by jeyip** [comment] 2020-11-13 20:00
After more digging, there's technical reasoning behind this. https://github.com/Automattic/newspack-blocks/issues/306

Basically, when we click the load more button, it makes a request to fetch more posts. This, however, requires authorization (because it's a private site). Intuitively, I'd expect us to have the right authorization tokens already available, especially because we're already signed in and editing content. Apparently, this isn't the case, and the right authorization tokens aren't available at the right time.

**Comment by jeyip** [comment] 2020-11-13 20:06
I'm closing this bug ticket for now. 

@kylemcph, because you're closer to customers, I'd love to know if this is a problem that draws a lot of attention. If so,  we could open up another issue and frame this as a feature request. Let me know what you think!

**Closed by jeyip** 2020-11-13 20:06 UTC
Labels: Blocks, [Pri] Normal, [Type] Bug

**Comment by kylemcph** [comment] 2020-11-24 17:09
Hey @jeyip, thanks for your explanation about why the button is not displayed on private sites. I do not think this is a major issue, it is just something I came across while testing the block in #47086.
