### ISSUE TITLE
Activity Log: Master Issue for Notifications and Emails

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/wp-calypso#20521] opened 2017-12-05 18:55 UTC
Master issue to track all notifications/emails

**Download is ready**
- [x] Email #19540 
- [x] Notification #19541

**Credentials needed**
- [x] Email #19542

**Issues Detected**
- [x] Email #19610 
- [x] Notification #19612

**Update Credentials**
- [x] Email #19543
- [ ] Notification #19781

Please edit this post to add other Notifications and Emails needed

**Comment by lezama** [comment] 2018-01-26 20:26
@samhotchkiss can we close this one?

**Comment by lezama** [comment] 2018-03-14 19:36
@samhotchkiss @samhotchkiss !

**Comment by samhotchkiss** [comment] 2018-04-05 14:51
@lezama -- @rcoll is testing these, and then will close

**Comment by roccotripaldi** [comment] 2018-04-20 14:33
Closing because we've confirmed that most of these are done. if it turns out we are missing an email, or we discover that an email needs updating, let's create a specific issue.

**Closed by roccotripaldi** 2018-04-20 14:33 UTC
Labels: Activity/Rewind, Jetpack, Notifications, [Type] Task
