### ISSUE TITLE
Site Assembler: Fonts on Global Styles only following the pre-set from the Site Assembler, not the actual list available on WordPress.com

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#78605] opened 2023-06-25 09:26 UTC
### Quick summary

When choosing a font combination (Font 1 and Font 2) on Site Assembler, the fonts visible on the Global Styles will only display three fonts:
- Default
- Font 1
- Font 2

While in actuality, there are more fonts available on WordPress.com.

### Steps to reproduce

First, log in to WordPress.com and "build a theme" using Assembler flow on https://wordpress.com/themes
![Screenshot 2023-06-25 at 5 19 55 PM](https://github.com/Automattic/wp-calypso/assets/44726232/6459551b-c415-4847-8c6e-103644b5f0f2)

Second, add the patterns and set the color palette and the font. In this example, I'm using Libre Baskerville and DM Sans combination.
![Screenshot 2023-06-25 at 5 21 22 PM](https://github.com/Automattic/wp-calypso/assets/44726232/9bc6dc19-5d34-49e2-8a7e-5eb192fd7017)

Third, notice as soon as the theme is activated, we get redirected to Site Editor (this is expected.)

Fourth, on Site Editor, check the website's typography on _Styles > Typography > Text/Links/Headings/Captions/Buttons_. Notice how the font option only displays three fonts: Default, Libre Baskerville, and DM Sans.
![Screenshot 2023-06-25 at 5 23 41 PM](https://github.com/Automattic/wp-calypso/assets/44726232/ad2c944b-4fd6-4298-aed4-9f3978c38778)

### What you expected to happen

I'm expecting to see a longer list of font options. I know that Blank Canvas (the theme that being used for Assembler flow) provides more fonts.

### What actually happened

I only see three font options.

**Workaround**:

To rectify this, click the three dots next to the eye icon on the tab Styles, then click "Reset to defaults". It will bring the other fonts to the options.
![Screenshot 2023-06-25 at 5 25 22 PM](https://github.com/Automattic/wp-calypso/assets/44726232/b3c6728d-2588-44e3-871c-7c58df83d41b)

The downside is: The color palette got reset too. 

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by jp-imagines** [comment] 2023-07-05 18:39
Ran into an instance of this here: 6502037-zd-woothemes (and I was able to replicate on a test site as well).

Unfortunately, resetting just font family or typography styles isn't enough to fix the issue. You do have to reset styles to defaults.

**Comment by arthur791004** [comment] 2023-07-20 08:40
After investigation, it's weird that the font families would be overwritten if the definition of the font family in the config of the style variation contains the `name` attribute. If you go to activate the Pendant theme with any variation, you will encounter the same issue in the editor.

For example,
```js
[
  // The result would be incorrect.
  {
    "fontFamily": "Crimson Pro",
    "name": "Crimson Pro",
    "slug": "crimson-pro"
  },
  // The result is correct.
  {
    "fontFamily": "Crimson Pro",
    "slug": "crimson-pro"
  },
]
```

**Comment by arthur791004** [comment] 2023-07-21 05:35
We have resolved this issue via D116543-code temporarily and created https://github.com/Automattic/dotcom-forge/issues/3162 to address the root cause in the follow-up iteration 🙂

**Comment by csabarakasz** [comment] 2023-07-23 12:59
6568831-zd-woothemes, same issue reported. Only two fonts. 

However, the user don't seem to have the reset Style option: ![sp2Wpabb9Emz2kVTatOgGJO434D20jHoVs0BZaPu.jpg](https://github.com/Automattic/wp-calypso/assets/84539773/4c001be9-4048-4a74-86a5-b3d552a50b89)

**Comment by mdtanjid0** [comment] 2023-08-03 13:54
- [ ] 6568831-zd-woothemes - needs to be followed up.  ( Blank Canvas theme ). 

It's the same for me as @csabarakasz. I couldn't find the reset option.

**Comment by hngdny** [comment] 2023-08-28 14:18
6734866-zd-a8c – They are using workaround for now. The 'Reset to default' option is found under the 'Revision History' icon:


<img width="1278" alt="Screen Shot 2023-08-28 at 10 05 46" src="https://github.com/Automattic/wp-calypso/assets/70492744/ed78fc9c-9401-4db6-a3c4-32ad9ef3c071">

**Comment by arthur791004** [comment] 2023-08-29 07:22
Raised an issue on Gutenberg. See https://github.com/WordPress/gutenberg/issues/54008

**Comment by autumnfjeld** [comment] 2023-10-11 02:31
New Font Library integrated with Jetpack Google Fonts will fix this issue.

**Comment by autumnfjeld** [comment] 2023-11-07 00:33
Moving this to In Progress since we are waiting for the new Font Libarary.

**Comment by arthur791004** [comment] 2023-11-14 09:18
@retnonindya Hiya, I followed the steps mentioned above and the issue didn't happen anymore. I think this should be resolved by WP 6.4 & Jetpack 12.8. Could you help to confirm it again when you're available? Thank you!

**Comment by retnonindya** [comment] 2023-11-17 10:28
@arthur791004 👋  Yes! I can confirm the issue is no longer there. Thanks, Arthur!

**Comment by arthur791004** [comment] 2023-11-21 06:31
Thanks for confirming! Closing this issue as it's resolved 🎉

**Closed as completed by arthur791004** 2023-11-21 06:31 UTC
Labels: Bug, [Pri] Normal, Patterns, Customer report [LEGACY], [Platform] Simple
