### ISSUE TITLE
[Bug]: Activating Tsubaki opens a WooCommerce onboarding flow I can't escape

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#70070] opened 2022-11-16 14:13 UTC
### Quick summary

Installing the Tsubaki theme dumps me on a 'Add an address to accept payments' screen which I wasn't expecting. There is a back button at the top of this screen, it doesn't work. The back button in the browser is also broken.

There are three things going on here:
 1. I was surprised to be on some kind of setting screen without warning, other themes didn't do this.
 2. I couldn't navigate out of this screen.
 3. I didn't know whether the theme was active, there was no confirmation that it was without going to visit the front-end of the site myself.

### Steps to reproduce

 1. Have a site on a paid plan (I was testing with a simple site with a Pro plan)
 2. Go to Appearance
 3. Search for the Tsubaki theme
 4. Activate it
 5. End up on https://wordpress.com/setup/plugin-bundle/storeAddress?siteSlug=whatever.wordpress.com
 6. Press back at the top of the page
 7. Press back in the web browser

### What you expected to happen

I expected to go back to the previous page (theme info) so I could navigate to change to a different theme

Also it's unclear at this point whether the theme has actually changed or not

### What actually happened

Clicking the back button just put me on the same screen again. To be more specific pressing back and using the browser back both sent me to https://wordpress.com/setup/plugin-bundle/getCurrentThemeSoftwareSets?siteSlug=whatever.wordpress.com which instantly redirected me to https://wordpress.com/setup/plugin-bundle/storeAddress?siteSlug=whatever.wordpress.com

Additionally when I held down the back button to choose where to navigate to, all of these screens just said 'WordPress.com', which is technically correct but also useless.

### Browser

Mozilla Firefox

### Context

Exploratory testing

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by cuemarie** [comment] 2023-04-27 23:35
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described!  I had to navigate directly to WordPress.com get out of the setup for WooCommerce.  When I return to the site, it's still Simple, but Tsubaki is now active

#### Screenshots/Recordings

https://user-images.githubusercontent.com/27249804/235012340-40697fae-9e90-4dd3-bfbf-6062ad60096d.mp4

📌 ACTIONS
- Assigned to Serenity

**Comment by nelsonec87** [comment] 2023-04-28 16:25
This theme is bundled with the WooCommerce plugin. After the theme is installed, Woo is also installed and it's configuration is triggered.
The problem is that there is no warning to the user, that may just want to switch themes and then won't understand what's going on.

**Comment by andres-blanco** [comment] 2023-05-01 13:54
Confirmed this happens with all WooCommerce themes. I think this needs some design/product input. There are 2 main things to be taken in cosideration:
1. The user needs a way to know that clicking `Activate` will put them on an ecommerce upgrade flow.
2. Once on the upgrade flow, it would be comforting to have a way to bail out of that flow. The only way to do that right now is by changing the URL.

**Comment by sixhours** [comment] 2023-05-01 14:08
This may have been fixed at one point by https://github.com/Automattic/wp-calypso/pull/73690; there may be some clues in that PR as to how to fix it again.

**Comment by sixhours** [comment] 2023-05-01 17:47
> Confirmed this happens with all WooCommerce themes. I think this needs some design/product input. There are 2 main things to be taken in cosideration:

Agreed. As it is now, this isn't a bug, per se, because the WooCommerce themes will attempt to put the user through the store setup if WooCommerce is not already installed (including a move to Atomic if the site is simple). We hint at that on the individual theme screen, but it's not super clear, and it's even less clear from the main Showcase page. And we don't know if the user is choosing the theme because they want a store or they just like the design.

Some ideas:

* Activate the theme, **then** prompt the user asking if they want to do the ecommerce setup, too.
* Prompt the user before theme activation to let them know they'll be entering ecommerce setup.
* Bypass ecommerce setup for sites that don't have an ecommerce-type plan.

**Comment by sixhours** [comment] 2023-05-01 17:52
Oh, good to clarify, the lack of ability to go Back in the flow is a bug. 😅 The ecommerce setup part is confusing, but is expected.

**Comment by andres-blanco** [comment] 2023-05-09 18:55
@dsas @cuemarie we've added a fix for this in [this PR](https://github.com/Automattic/wp-calypso/pull/76474). While the experience is not optimal there's now a way to escape the flow. 

I will close this issue, we can reopen if you think it's necessary.

**Closed as completed by andres-blanco** 2023-05-09 18:55 UTC
Labels: Bug, [Pri] Normal, Triaged, [Feature Group] Customer Seller Experience, [Platform] Simple, [Theme] Tsubaki
