### ISSUE TITLE
Gutenberg: File Block

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#27640] opened 2018-10-05 02:51 UTC
Verify if a file block is serialized as expected. Note that media uploads on Chrome (local env) will be cancelled.

In addition to that, the file block URL rendered on frontend are also incorrect. The file is pointing to something like https://wpcalypso.wordpress.com/19115187-8f88-4fc7-a40e-6fe12c18b3fa which is a non-existent Calypso page.

**Comment by vindl** [comment] 2018-10-11 00:29
Just a note that this block also requires a plan - noted in related issue https://github.com/Automattic/wp-calypso/issues/27772.

**Comment by Copons** [comment] 2018-10-11 11:37
Ran a quick comparison test on the code of a post containing only a File block:

#### Gutenberg Core
```
<!-- wp:file {"id":1955,"href":"http://example.org/wordpress/wp-content/uploads/2018/10/3EcYZhBMAvVw4czcDLg9Sd0FuzQ.jpg"} -->
<div class="wp-block-file"><a href="http://example.org/wordpress/wp-content/uploads/2018/10/3EcYZhBMAvVw4czcDLg9Sd0FuzQ.jpg">3EcYZhBMAvVw4czcDLg9Sd0FuzQ</a><a href="http://example.org/wordpress/wp-content/uploads/2018/10/3EcYZhBMAvVw4czcDLg9Sd0FuzQ.jpg" class="wp-block-file__button" download="3EcYZhBMAvVw4czcDLg9Sd0FuzQ">Download</a></div>
<!-- /wp:file -->
```

#### Calypso Before Save
```
<!-- wp:file {"id":71,"href":"https://example.files.wordpress.com/2018/10/3ecyzhbmavvw4czcdlg9sd0fuzq.jpg"} -->
<div class="wp-block-file"><a href="https://example.files.wordpress.com/2018/10/3ecyzhbmavvw4czcdlg9sd0fuzq.jpg">3ecyzhbmavvw4czcdlg9sd0fuzq</a><a href="https://example.files.wordpress.com/2018/10/3ecyzhbmavvw4czcdlg9sd0fuzq.jpg" class="wp-block-file__button" download="3ecyzhbmavvw4czcdlg9sd0fuzq">Download</a></div>
<!-- /wp:file -->
```

#### Calypso After Save (broken)
```
<!-- wp:file {"id":71,"href":"https://example.files.wordpress.com/2018/10/3ecyzhbmavvw4czcdlg9sd0fuzq.jpg"} -->
<div class="wp-block-file"><a href="https://example.files.wordpress.com/2018/10/3ecyzhbmavvw4czcdlg9sd0fuzq.jpg">3ecyzhbmavvw4czcdlg9sd0fuzq</a><a href="https://example.files.wordpress.com/2018/10/3ecyzhbmavvw4czcdlg9sd0fuzq.jpg" class="wp-block-file__button">Download</a></div>
<!-- /wp:file -->
```

There are 2 obvious differences.
One is that Calypso lowercases the filename, which can be annoying, since it's then used as download label.

The other is that the download button has a `download="filename"` attribute that gets stripped.
This might be similar to the attribute pruning issue already [encountered elsewhere](https://github.com/Automattic/wp-calypso/issues/27645).

**Comment by vindl** [comment] 2018-10-18 22:44
The file block URL rendered on frontend are also incorrect. I documented this in the P2 post but I have just noticed that's not present in summary (added). The file link would point to something like `https://wpcalypso.wordpress.com/19115187-8f88-4fc7-a40e-6fe12c18b3fa` which is a non-existent Calypso page.

**Comment by Copons** [comment] 2018-10-19 10:18
Update from Guten-side (https://github.com/WordPress/gutenberg/pull/10693): we might be stuck here.
The `download` attribute removal entails UI changes, which require a design discussion first.
It might be easier to create our own version of the block, but I'm not sure how long it would take.

**Comment by vindl** [comment] 2018-10-25 00:40
Closing this issue since it's no longer reproducible. :)

**Closed** 2018-10-26 16:11 UTC
Labels: [Goal] Gutenberg, [Type] Task
