### ISSUE TITLE
Nav Unification: Calypso Loading Speed

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#49821] opened 2021-02-08 10:56 UTC
### Summary
With Nav Unification available to A12s, it's easier to spot where it impacts our workflows. For example, we have P2s that have thousand of posts, I used to open WP-Admin to access the Posts page, to work on a new/draft post, and now it's redirecting me to Calypso. I would be worried with Calypso's performance issues, one of the P2s I opened took almost 30 seconds to load the Drafts (it has 162).

### Steps to reproduce the behavior

1. Go to the WP-Admin of the We Have the Answers P2
2. Click on Posts
3. You will get redirected to Calypso
4. Click on Drafts

#### What I expected to happen
To load as fast as it used to on WP-Admin.

#### What actually happened
It took about 27 seconds to load the Drafts page.

#### Browser / OS version
Chrome 88.0.4324.146
Mac OS X 10.15.7

#### Is there any console output or error text?
API request that takes 27s seems to have this parameters: `http_envelope=1&author=&number=20&order=DESC&search=&status=draft%2Cpending&type=post&page=1`

**Comment by mmtr** [comment] 2021-02-08 12:07
Thanks for the report, @carinapilar!

While this is not a problem caused by Nav Unification, it indeed makes more prominent that Calypso has some performance issues when loading posts that should be addressed.

In the meantime, you can still access the WP Admin pages by typing directly the URL in the browser (e.g. `/wp-admin/edit.php`).

You can also enable a setting in https://wordpress.com/me/account for replacing all links with WP Admin pages (on all your sites) when possible (not all Calypso pages have a WP Admin equivalent page).

<img width="674" alt="Screen Shot 2021-02-08 at 13 04 24" src="https://user-images.githubusercontent.com/1233880/107217509-8e096980-6a0e-11eb-88f6-9c5acbacbaf7.png">

**Comment by carinapilar** [comment] 2021-02-10 21:22
> In the meantime, you can still access the WP Admin pages by typing directly the URL in the browser (e.g. /wp-admin/edit.php).

That's great to know, will keep that in mind, thanks @mmtr! :)

> You can also enable a setting in https://wordpress.com/me/account for replacing all links with WP Admin pages (on all your sites) when possible (not all Calypso pages have a WP Admin equivalent page).

Do we have more details somewhere that explains how this option should work? I tried activating on my account, and most of the menus on Calypso stop working, such as Posts and Pages for example, and when using WP-Admin, Widgets and Menus under Appearance still load the Customizer.

**Comment by mmtr** [comment] 2021-02-11 08:52
> Do we have more details somewhere that explains how this option should work?

When the toggle is enabled, the menu items with an WP Admin equivalent page will point to WP Admin.

> I tried activating on my account, and most of the menus on Calypso stop working, such as Posts and Pages for example, and when using WP-Admin, Widgets and Menus under Appearance still load the Customizer.

Was that for a site with a mapped domain? If so, that's a known issue. We added some security measurements to how the unified menu is built which introduced a regression on WP Admin links for sites with a mapped domain. Should be addressed by https://github.com/Automattic/wp-calypso/pull/49924.

**Comment by getdave** [comment] 2021-02-11 09:57
> Do we have more details somewhere that explains how this option should work?

~I'll add a stub to the documentation page PCYsg-v8B-p2 which we'll need to populate with this info~. I added a new FAQ page (PCYsg-vFf-p2#how-do-i-access-wpadmin).

This query is going to be a common question in my opinion.

**Comment by carinapilar** [comment] 2021-02-16 04:28
> Was that for a site with a mapped domain? If so, that's a known issue. We added some security measurements to how the unified menu is built which introduced a regression on WP Admin links for sites with a mapped domain. Should be addressed by #49924.

Ah, yes, it seems to be the case! Thanks, @mmtr! And thanks, @getdave for the FAQ. 🙂

**Comment by ccwalburn** [comment] 2021-02-24 18:37
Hi @mmtr Is this the issue that is tracking the Calypso Performance issues? https://github.com/Automattic/wp-calypso/issues/32159
And if so, will that get some more traction now?

**Comment by mmtr** [comment] 2021-02-25 08:29
@ccwalburn I'm not sure if it's the same issue since #32159 seems specific to JP/AT sites, and this one also affect Simple sites. It would need more investigation to confirm whether they both are part of the same issue.

> will that get some more traction now?

Im afraid I'm not in the best position to answer this, since it depends on the different roadmaps and priorities of the teams. Going to defer this to @obenland.

**Comment by obenland** [comment] 2021-03-12 00:12
Closing in favor of #32159.

I prioritized #32159 onto the Manage project board and it will be ready for dev teams to chose starting next iteration.

**Closed as completed by obenland** 2021-03-12 00:12 UTC
Labels: Bug, [Pri] Low, [Feature] Calypso & wp-admin Navigation
