### ISSUE TITLE
Themes: Logging in, then back out gives empty site selector dropdown on attempted activation

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#11766] opened 2017-03-03 23:51 UTC
Reported by @lancewillett in D4604-code:

#### Steps to reproduce
* Log into Calypso, then log out
* Go to https://wordpress.com/theme/sela
* When the page first loads, you'll see "Pick this design" — but the button changes quickly to "Activate this design"
* Click activate

#### What I expected

The button to be labelled "Pick this design", and clicking it to direct me to signup (with that theme preselected).

#### What happened instead

I got the Themes Site Selector Modal with an empty dropdown of sites.

#### Screenshot / Video

https://cloudup.com/c7-RTG9mqgH

**Comment by ockham** [comment] 2017-03-03 23:51
Sounds like we're persisting state that we don't really want... 😕

**Comment by budzanowski** [comment] 2017-03-04 13:06
Can't reproduce.
@lancewillett are you still able to reproduce?

**Comment by folletto** [comment] 2017-03-06 10:21
![cap-](https://cloud.githubusercontent.com/assets/4389/23605947/8e3e75ae-0256-11e7-9bca-567cbef76eb7.gif)

Confirmed.

Clearing IndexedDB `calypso_store` fixes it.

**Comment by folletto** [comment] 2017-03-06 10:21
Note: this isn't a priority for JetPress as we haven't yet launched M6 which is when the logged out pages are made available.

**Comment by seear** [comment] 2017-04-13 13:04
Not actually fixed by #13031. Investigating further...

**Comment by folletto** [comment] 2017-04-19 19:21
This bug was identified again in #13246, coming from https://wordpress.com/create-website/ OR https://wordpress.com/easy/. It was harder to track down as the issue was done in incognito mode, so it might be either a dirty incognito or some other kind of issue.

I tentatively closed the other issue as it's highly likely it's fixed by this one too. I'm just wondering if there's _also_ some check we could do when that condition happens, instead of relying on the absence of the data.

**Comment by folletto** [comment] 2017-04-20 16:56
Another test stumbled on the bug in #13280 (unrelated to this issue tho, they were testing another flow).

**Closed** 2017-04-20 17:00 UTC
Labels: Themes, [Type] Bug

**Comment by seear** [comment] 2017-04-20 17:14
>  I'm just wondering if there's also some check we could do when that condition happens, instead of relying on the absence of the data.

I think the themes code already does the appropriate check, which is to see if there is a current user. The root cause was the reading of user-specific persisted state when logged-out, making it appear as if there _was_ a current user, which can now never happen after #13185.

**Comment by folletto** [comment] 2017-04-21 10:20
The thing that confuses me tho is... how then the masterbar is able to detect it, but the showcase didn't?

**Comment by seear** [comment] 2017-04-24 10:20
> The thing that confuses me tho is... how then the masterbar is able to detect it, but the showcase didn't?

Masterbar and some other code will be using the older `user` lib to determine whether there is a current user, whereas the showcase is using the `getCurrentUser()` selector. Both techniques need to be reliable.

**Comment by folletto** [comment] 2017-04-24 10:22
> Both techniques need to be reliable.

...aaaand, are they now? :D

**Comment by seear** [comment] 2017-04-24 10:26
Yes, #13185 means that persisted user data can no longer be unserialized in logged-out mode, making `getCurrentUser()` reliable.
