### ISSUE TITLE
Basic importer not importing content from .com to .com sites

### ISSUE THREAD

**Issue by eamcgill90** [Automattic/wp-calypso#53358] opened 2021-06-03 01:47 UTC
I saw this issue a few times today and reported here as well: pbkcP4-iw-p2

### Steps to reproduce the behavior

1. Go to Tools > Export on any WordPress.com site
2. You can either export all content, or a portion of the content (i.e. just posts)
3. Download the backup (all xml files I tested with were populated with content)
4. Import backup into a new WordPress.com site 

#### What I expected to happen

I expected to see all content on the new site

#### What actually happened

No content was imported, or only portions of the content were imported

#### Does this happen on simple or atomic sites or both?

I believe it is affecting both per this P2: p9F6qB-6ZB-p2

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

High impact, affecting multiple sites

**Comment by kosiew** [comment] 2021-11-19 10:48
Hi @eamcgill90 ,

Thanks for reporting this and the detailed steps.

I could not reproduce this and am closing this for now. 
I tested this on cMo3x-p2 and manage the file conteents.
 
Please feel free to re-open if you have further findings to add.

**Closed as completed by kosiew** 2021-11-19 10:48 UTC
Labels: Bug, Import, Site Importer
