### ISSUE TITLE
Editor: Publish button changes to Schedule if site is UCT+0

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/wp-calypso#47935] opened 2020-12-01 20:59 UTC
It seems that whenever the site timezone is set to UTC+0, the **Publish** button automatically changes to **Schedule**. This is happening on both simple and AT sites.

#### Steps to reproduce

1. Start a new site
2. Once launched, go to Manage > Settings
3. Change the Site Timezone to UCT+0
4. Go to Site > Posts/Page and click to add a new one

#### What I expected
To see the regular **Publish** button.

#### What happened instead
Saw **Schedule** instead despite being a new post marked to be published immediately:

<img width="1385" alt="Captura de Tela 2020-12-01 às 17 54 18" src="https://user-images.githubusercontent.com/1136160/100795732-478c0300-33fe-11eb-8547-592ca4f49661.png">

#### Context / Source

#dogfooding #user-report 

Internal references: p1606849334010200-slack-C03TY6J1A and 24157452-hc

**Comment by yashitamittal11** [comment] 2020-12-02 02:45
Another report - #26046414-hc

I am also seeing the same issue on my test site. The timezone is incorrect but I have never changed the timezone and the posts were publishing fine earlier.

**Comment by ezebecke** [comment] 2020-12-02 17:05
Another report: #26058677-hc
We changed the timezone from New York to Chicago as a workaround to display the Publish button.

**Comment by lakellie** [comment] 2020-12-02 18:08
Another report: #23088523-hc

**Comment by gwensmithx** [comment] 2020-12-04 00:33
Another report: #26088576-hc

**Comment by ockham** [comment] 2020-12-04 11:59
Upstream issue: https://github.com/WordPress/gutenberg/issues/27251

**Comment by samiff** [comment] 2020-12-04 16:19
Another report: 23352618-hc

**Comment by NoHopeRadio** [comment] 2020-12-04 20:29
Another report: 25254106-hc (follow-up ticket: 3545342-zd)

**Comment by liviopv** [comment] 2020-12-06 09:54
I wasn't able to reproduce it another site, but the user on #3547540-zen was also getting a `"The editor encountered an unexpected error"` when they tried to schedule a post.

Here's the error log:

```
TypeError: r is not a function
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/9.4.1/build/components/index.js?m=1605812088h&ver=c9900a09a1a14bfbc7ad056ada53d774:1:300734
    at Bh (https://s0.wp.com/wp-content/plugins/gutenberg-core/9.4.1/vendor/react-dom.min.de439aae.js?m=1599596311h:9:8089)
    at Dj (https://s0.wp.com/wp-content/plugins/gutenberg-core/9.4.1/vendor/react-dom.min.de439aae.js?m=1599596311h:12:3529)
    at unstable_runWithPriority (https://s0.wp.com/wp-content/plugins/gutenberg-core/9.4.1/vendor/react.min.e713ea3b.js?m=1599596311h:3:3396)
    at Da (https://s0.wp.com/wp-content/plugins/gutenberg-core/9.4.1/vendor/react-dom.min.de439aae.js?m=1599596311h:7:824)
    at xb (https://s0.wp.com/wp-content/plugins/gutenberg-core/9.4.1/vendor/react-dom.min.de439aae.js?m=1599596311h:12:3284)
    at mk.Events.current (https://s0.wp.com/wp-content/plugins/gutenberg-core/9.4.1/vendor/react-dom.min.de439aae.js?m=1599596311h:14:25865)
    at Ei (https://s0.wp.com/wp-content/plugins/gutenberg-core/9.4.1/vendor/react-dom.min.de439aae.js?m=1599596311h:3:7199)
```

Switching the site's timezone fixed the issue.

**Comment by ccwalburn** [comment] 2020-12-06 15:31
Another report here: 3546893-zen

**Comment by isocialtish** [comment] 2020-12-06 22:32
We have another case 3549880-zen

**Comment by david-szabo97** [comment] 2020-12-07 19:48
Fixed in Gutenberg 9.4.2 and upcoming 9.5.x, waiting for release.

**Comment by liviopv** [comment] 2020-12-08 10:39
@david-szabo97 I got an another timezone-based error in the editor that I was not able to reproduce on a test site. In this case, the site was a Simple Site originally set to UTC-3. With that setup, opening any page or post in the Editor would lead to this error:

```
RangeError: Invalid time zone specified: -03
    at new DateTimeFormat (<anonymous>)
    at https://s0.wp.com/_static/??-eJylkd1uwyAMRl9oxM3UVtnFtGch2EqcAqZg+vP2ZVeTejdyadnf0bEN92ScRKWokHxdOBZYaitnykvrZIKv4TiMMFf2CFxMWa33cjd0rdYDR6THsJUP+B8oZZbM+jTXSpW6MU5CktKfR0qZnFXCbkQmrA+TpSrHHSJWbX9YQnd21eBNm2VlKnveGRrhtgNRVsnqBPtvOHtxlzcBjs5XbFpbAeSicKOIkiFIaNQhcOx7Vr/lhZ6/W/55/oTv8Xw4TePnYZq2F3H6SvE=:25:32977
    at me (https://s0.wp.com/_static/??-eJylkd1uwyAMRl9oxM3UVtnFtGch2EqcAqZg+vP2ZVeTejdyadnf0bEN92ScRKWokHxdOBZYaitnykvrZIKv4TiMMFf2CFxMWa33cjd0rdYDR6THsJUP+B8oZZbM+jTXSpW6MU5CktKfR0qZnFXCbkQmrA+TpSrHHSJWbX9YQnd21eBNm2VlKnveGRrhtgNRVsnqBPtvOHtxlzcBjs5XbFpbAeSicKOIkiFIaNQhcOx7Vr/lhZ6/W/55/oTv8Xw4TePnYZq2F3H6SvE=:25:33056)
    at Object.z (https://s0.wp.com/_static/??-eJylkd1uwyAMRl9oxM3UVtnFtGch2EqcAqZg+vP2ZVeTejdyadnf0bEN92ScRKWokHxdOBZYaitnykvrZIKv4TiMMFf2CFxMWa33cjd0rdYDR6THsJUP+B8oZZbM+jTXSpW6MU5CktKfR0qZnFXCbkQmrA+TpSrHHSJWbX9YQnd21eBNm2VlKnveGRrhtgNRVsnqBPtvOHtxlzcBjs5XbFpbAeSicKOIkiFIaNQhcOx7Vr/lhZ6/W/55/oTv8Xw4TePnYZq2F3H6SvE=:25:36137)
    at https://s0.wp.com/_static/??-eJylkd1uwyAMRl9oxM3UVtnFtGch2EqcAqZg+vP2ZVeTejdyadnf0bEN92ScRKWokHxdOBZYaitnykvrZIKv4TiMMFf2CFxMWa33cjd0rdYDR6THsJUP+B8oZZbM+jTXSpW6MU5CktKfR0qZnFXCbkQmrA+TpSrHHSJWbX9YQnd21eBNm2VlKnveGRrhtgNRVsnqBPtvOHtxlzcBjs5XbFpbAeSicKOIkiFIaNQhcOx7Vr/lhZ6/W/55/oTv8Xw4TePnYZq2F3H6SvE=:25:40229
    at Array.reduce (<anonymous>)
    at Fe (https://s0.wp.com/_static/??-eJylkd1uwyAMRl9oxM3UVtnFtGch2EqcAqZg+vP2ZVeTejdyadnf0bEN92ScRKWokHxdOBZYaitnykvrZIKv4TiMMFf2CFxMWa33cjd0rdYDR6THsJUP+B8oZZbM+jTXSpW6MU5CktKfR0qZnFXCbkQmrA+TpSrHHSJWbX9YQnd21eBNm2VlKnveGRrhtgNRVsnqBPtvOHtxlzcBjs5XbFpbAeSicKOIkiFIaNQhcOx7Vr/lhZ6/W/55/oTv8Xw4TePnYZq2F3H6SvE=:25:40164)
    at Object.e (https://s0.wp.com/_static/??-eJylkd1uwyAMRl9oxM3UVtnFtGch2EqcAqZg+vP2ZVeTejdyadnf0bEN92ScRKWokHxdOBZYaitnykvrZIKv4TiMMFf2CFxMWa33cjd0rdYDR6THsJUP+B8oZZbM+jTXSpW6MU5CktKfR0qZnFXCbkQmrA+TpSrHHSJWbX9YQnd21eBNm2VlKnveGRrhtgNRVsnqBPtvOHtxlzcBjs5XbFpbAeSicKOIkiFIaNQhcOx7Vr/lhZ6/W/55/oTv8Xw4TePnYZq2F3H6SvE=:25:43182)
    at Ke (https://s0.wp.com/_static/??-eJylkd1uwyAMRl9oxM3UVtnFtGch2EqcAqZg+vP2ZVeTejdyadnf0bEN92ScRKWokHxdOBZYaitnykvrZIKv4TiMMFf2CFxMWa33cjd0rdYDR6THsJUP+B8oZZbM+jTXSpW6MU5CktKfR0qZnFXCbkQmrA+TpSrHHSJWbX9YQnd21eBNm2VlKnveGRrhtgNRVsnqBPtvOHtxlzcBjs5XbFpbAeSicKOIkiFIaNQhcOx7Vr/lhZ6/W/55/oTv8Xw4TePnYZq2F3H6SvE=:25:44629)
    at ut (https://s0.wp.com/_static/??-eJylkd1uwyAMRl9oxM3UVtnFtGch2EqcAqZg+vP2ZVeTejdyadnf0bEN92ScRKWokHxdOBZYaitnykvrZIKv4TiMMFf2CFxMWa33cjd0rdYDR6THsJUP+B8oZZbM+jTXSpW6MU5CktKfR0qZnFXCbkQmrA+TpSrHHSJWbX9YQnd21eBNm2VlKnveGRrhtgNRVsnqBPtvOHtxlzcBjs5XbFpbAeSicKOIkiFIaNQhcOx7Vr/lhZ6/W/55/oTv8Xw4TePnYZq2F3H6SvE=:25:46181)
```

Switching to "São Paulo" (which is effectively UTC-3)  fixed the issue.

**Comment by david-szabo97** [comment] 2020-12-08 11:08
Thank you @liviopv ! Upstream issue for the problem you mentioned: https://github.com/WordPress/gutenberg/issues/27514

It's fixed by the same PR as this issue. So both issues will be fixed in the next release.

**Comment by adelineyaw** [comment] 2020-12-10 11:36
Another report 25250728-hc

**Comment by aisajib** [comment] 2020-12-10 11:48
Another user reported this in #26239662-hc

**Comment by ockham** [comment] 2020-12-15 13:56
Should be fixed per D53975-code which upgraded WP.com to Gutenberg 9.5.2. (Announcement post: p7DVsv-a06-p2)

**Closed as completed by ockham** 2020-12-15 13:56 UTC
Labels: Bug, [Feature] Post/Page Editor, [Pri] Normal, Customer report [LEGACY]

**Comment by ws256** [comment] 2025-02-27 07:06
I had the same problem because automatic time synchronization on the server was not configured. The time on the server differed from the current time by 2 minutes. I performed synchronization, the publish button appeared.
