### ISSUE TITLE
Legacy Author Widget not working

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/wp-calypso#77887] opened 2023-06-07 08:39 UTC
### Quick summary

The legacy author widget doesn't show on a public site

### Steps to reproduce

* Add the Legacy author widget to a classic theme via the widgets area - wp-admin/widgets.php
* It appears in the customizer in the widgets sidebar and in the preview page
* But not on the public site
* Tested with Baskerville 2 and Scratchpad. Both don't work

### What you expected to happen

It to appear

### What actually happened

It didn't appear

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

6364099-zd

**Comment by cuemarie** [comment] 2023-06-07 18:18
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Could Not Replicate**
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested on Simple with **Twenty Twenty One** and **Baskerville 2** - widget worked in both themes:
- Tested on Atomic with **Storefront**

**Simple Site, Baskerville 2**
![Markup on 2023-06-07 at 11:12:33](https://github.com/Automattic/wp-calypso/assets/27249804/d6d01e08-3f36-4721-92ff-c74db12e9f32)

**Atomic Site, Storefront**
![Markup on 2023-06-07 at 11:14:36](https://github.com/Automattic/wp-calypso/assets/27249804/1f3c0ac6-1a98-4e9c-b0bf-4dbc9ccfc652)

📌 ACTIONS
- Closed as could not replicate 

📌 Message to Author
- @rickmgithub Are there any additional details needed to reproduce this in a test environment? If not, looks like this may be specific to the user's site in some way; perhaps the legacy widget needs to be rebuilt?

**Closed as not planned by cuemarie** 2023-06-07 18:18 UTC
Labels: Bug, [Pri] Normal, Triaged, [Closed] Not Reproducible, Legacy Widgets
