### ISSUE TITLE
Editor: New Category dialog does not focus on category name

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#3449] opened 2016-02-22 02:57 UTC
## URL: 

https://wordpress.com/post/

## What I expected: 

When clicking "Add a New Category" I expect the New Category Name to have focus

## What happened instead: 

Nothing is in focus, I have to click the field to start entering text

## Steps to reproduce: 

1. Start new post
2. Expand Categories and Tags
3. Click "Add a New Category"
4. See that the new category field is not focused

## Browser / OS version: 

Safari OSX 10.11.3

## Screenshots / Video

![add new category](https://cloud.githubusercontent.com/assets/128826/13208365/beb244c6-d963-11e5-80a9-69ddfb82ae1d.gif)

**Comment by aduth** [comment] 2016-04-28 14:07
Ref: 11635-gh-calypso-pre-oss

**Comment by aduth** [comment] 2016-04-28 14:08
Duplicate of #1764 ?

**Closed** 2016-05-02 21:47 UTC
Labels: Editor, [Type] Enhancement
