### ISSUE TITLE
Navigation Block: Custom Font size does not work

### ISSUE THREAD

**Issue by poojashetty18** [Automattic/wp-calypso#47584] opened 2020-11-19 12:59 UTC
#### Steps to reproduce

1. Start by adding a Navigation block to any page or post
2. Update the font size to custom size
3. The changes are reflected in the Editor but no on the actual page

#### Browser / OS version
Tested it on Chrome. I tried switching to multiple themes but the issue is the same across themes

#### Screenshot / Video

On Editor side: <img width="1324" alt="Screenshot on 2020-11-19 at 16-40-12" src="https://user-images.githubusercontent.com/44837596/99668063-ad839c80-2a86-11eb-84ac-0a02ab025202.png">

On Actual page: 
<img width="1150" alt="Screenshot on 2020-11-19 at 16-52-20" src="https://user-images.githubusercontent.com/44837596/99669473-8cbc4680-2a88-11eb-8d8b-936ad361f1bd.png">

#### Context / Source
User report on 3494221-zd

**Comment by cathymcbride** [comment] 2020-11-19 16:53
possibly related to : p59oML-1Km-p2 ?

**Comment by jeyip** [comment] 2020-11-20 19:19
Issue confirmed for simple and atomic sites in Chrome, Firefox, Safari, and Edge 👍 Moving this into the backlog.

**Comment by jeyip** [comment] 2020-11-20 20:11
For some odd reason, when inline font size styles are applied to the nav element, the `px` suffix is stripped from the `font-size` value.

<img width="641" alt="Screen Shot 2020-11-20 at 12 10 07 PM" src="https://user-images.githubusercontent.com/5414230/99845470-8df18000-2b29-11eb-8a90-312e2fdf903a.png">

**Comment by alshakero** [comment] 2020-12-02 17:27
> For some odd reason, when inline font size styles are applied to the nav element, the px suffix is stripped from the font-size value.

Interestingly, I'm getting the opposite problem 

![image](https://user-images.githubusercontent.com/17054134/100908653-08c47e80-34cc-11eb-81e8-00d2be1c90b5.png)

**Comment by alshakero** [comment] 2020-12-02 19:37
This seems to fixed in https://github.com/WordPress/gutenberg/pull/26762, released in GB 9.4.0. Took me a whole day to figure out because I couldn't reproduce locally.

@jeyip can you by any chance confirm this is no longer an issue in 9.4.0? I can't reproduce locally on (GB#master) but some confirmation would be super helpful.

**Comment by cathymcbride** [comment] 2020-12-04 19:53
I'm not seeing it in GB 9.4.1. Closing....

**Closed by cathymcbride** 2020-12-04 19:53 UTC
Labels: Blocks, [Pri] Normal, [Type] Bug
