### ISSUE TITLE
Email Verification: Make notices better/more prominent

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93895] opened 2024-08-26 09:33 UTC
## Description 

See [context](https://wp.me/p58i-hYA/).

Several features in WP.com are blocked if the account email has not been verified, and we display notices accordingly.

![Image](https://github.com/user-attachments/assets/e47ae334-298e-4f56-a14f-af1e78442e7d)

The notice text is truncated here.
![Image](https://github.com/user-attachments/assets/3b6e23cc-928b-4b74-9f90-4342fb006e47)

There is also a scenario where the user can purchase a domain during onboarding, but then the experience breaks since they would need to verify their email.

![Image](https://github.com/user-attachments/assets/91d800dd-774c-4e64-9733-0cc9cdafcf86)

**Comment by javierarce** [comment] 2024-08-26 16:13
For the first two issues you mentioned, I think it's good that the message appears in context (obviously, in the case of the notice inside the avatar, the position is terrible), but there should be a global notice at the top.

For the third issue, the problem isn't specific to that screen. The walkthrough reveals that the problem is that we don't have (or at least aren't displaying) global notifications.

PS: I'd rename this issue to something like: "Implement global notifications for critical messages"

**Comment by davemart-in** [comment] 2024-08-26 18:20
Moving this to "Needs design"

**Comment by mmtr** [comment] 2024-09-04 11:20
@javierarce do you have any update on this?

**Comment by javierarce** [comment] 2024-09-04 17:28
Here's the P2 post I mentioned on my previous message: p9Jlb4-dYD-p2

**Comment by javierarce** [comment] 2024-09-05 13:50
After reviewing the feedback on p9Jlb4-dYD-p2, we have an accepted design proposal. Here are the screens that are relevant to this issue:

![image](https://github.com/user-attachments/assets/23c24d80-c7fe-4061-9f97-205f3b160ae3)
![image](https://github.com/user-attachments/assets/b13dbc33-8792-446b-91c4-a682b7b03d0a)
![image](https://github.com/user-attachments/assets/adb43930-3e12-4fde-b6c4-0ca0726717c0)

Here's a link to the updated Figma file: wCm5Tzb7JBaG4WNowWbjES-fi-5057_13109

PS: I'll open a new issue to handle the removal of the email change notification (wCm5Tzb7JBaG4WNowWbjES-fi-5057_20764)

**Comment by Addison-Stavlo** [comment] 2024-09-17 16:00
One PR for the dialog itself here: https://github.com/Automattic/wp-calypso/pull/94629

**Comment by Addison-Stavlo** [comment] 2024-09-17 18:21
@javierarce For the "Verify Email" button on the right side of the notice:
<img width="648" alt="Screenshot 2024-09-17 at 2 19 57 PM" src="https://github.com/user-attachments/assets/310e2c7b-3630-479f-ba2c-18159e0b308d">

Does this:
* navigate to /me/account
* open the modal
* resend the email
* other?

**Comment by javierarce** [comment] 2024-09-18 07:43
@Addison-Stavlo it should open the modal.

**Comment by Addison-Stavlo** [comment] 2024-09-18 13:32
> it should open the modal.

Thanks for clarifying. That sounds good!

**Comment by Addison-Stavlo** [comment] 2024-09-24 20:46
https://github.com/Automattic/wp-calypso/pull/94683 should resolve the rest of the items here.

**Closed as completed** 2024-10-07 13:08 UTC
Labels: Enhancement, [Pri] Normal, Fit and Finish
