### ISSUE TITLE
eCommerce plan site downgraded to Free site, blog address remains as xxxx.wpcomstaging.com

### ISSUE THREAD

**Issue by kosiew** [Automattic/wp-calypso#50558] opened 2021-02-27 03:17 UTC
### Steps to reproduce the behavior
Could not reproduce.

This happened in #3775834-zen and was [discussed here](p1614373413060000/1614372648.059400-slack-C02DQP0FP)

BRC blog_id =182818982

#### What I expected to happen
Blog address changes to xxx.wordpress.com

#### What actually happened
Blog address changes to xxx.wpcomstaging.com

#### Is this specific to the applied theme? Which one?
n/a

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
No

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Not reproduceable

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screenshot](https://d.pr/i/WJBne8+)
*if image does not load, please click on this link  : https://d.pr/i/WJBne8*

**Comment by JoshuaGoode** [comment] 2021-03-03 21:27
I believe this resolved itself and something hadn't synced up just yet. 

As for the site this happened to initially, it was deleted.

I couldn't reproduce this either. However, I'll leave it open for now to make it easier to collect additional reports. 

**Next steps:**
While we'll want to log the reports here, **_It might be best to ping the Atomic platform team if and when this happens so they can catch the issue._**

If this gets marked as stale, we can probably close it.

**Comment by obenland** [comment] 2022-02-16 18:37
Closing—it's been almost a year without additional reports.

**Closed as completed by obenland** 2022-02-16 18:37 UTC
Labels: Bug
