### ISSUE TITLE
Amazon Kindle instant preview embed returns intermittent 500 internal server error

### ISSUE THREAD

**Issue by rinazrina** [Automattic/wp-calypso#97040] opened 2024-12-04 04:00 UTC
### Quick summary

Amazon Kindle instant preview embed from https://read.amazon.com/kp/card is currently returning 500 internal server errors, but this is intermittent. Sometimes it's loading, but after a few refreshes, the error shows. 

### Steps to reproduce

1. Go to a page or post.
2. Embed an Amazon link - for example https://www.amazon.com/dp/1434827186 or https://www.amazon.com/dp/1434825345
3. Publish page/post
4. View page, there is an error on the Amazon embed - "HTTP Status 500 – Internal Server Error." Sometimes the preview is loading, but after a few refreshes, the error returns. 

### What you expected to happen

A preview of the Amazon book.

### What actually happened

An error message showed, "HTTP Status 500 – Internal Server Error"

![Image](https://github.com/user-attachments/assets/8962af6b-23f0-4f85-9c4f-773977380242)

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

I received a report from a user that some of their Amazon embeds are no longer working on their pages: 9126961-zd-a8c 

Tested this using Chrome and Safari.

**Comment by wojtekn** [comment] 2024-12-04 15:37
@Robertght I couldn't reproduce it, either.

I've checked how the embed works side, and it looks like the content is loaded using iframe from Amazon servers, e.g.:

https://leer.amazon.es/kp/card?preview=inline&linkCode=kpd&ref_=k4w_oembed_lmAM43YlF7iKWw&asin=1434825345&tag=kpembed-20

If this returned error 500, it would mean it was an intermittent issue on Amazon's side and nota  WordPress.com issue.

Here are more details about the block:
https://wordpress.org/documentation/article/amazon-kindle-embed/

**Comment by rcrdortiz** [comment] 2024-12-09 10:56
I could not reproduce the issue. The iFrame loads as expected, as @wojtekn mentioned, 500 errors would be on Amazon's side. I'm closing this issue.

**Closed as completed by rcrdortiz** 2024-12-09 10:56 UTC
Labels: Bug, [Pri] BLOCKER, Triaged, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks, [Status] Escalated to Product Ambassadors
