### ISSUE TITLE
[Bug]: Pro-rata credits calculation is wrong, leading to an unintended discount on plan upgrades

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#59353] opened 2021-12-17 13:04 UTC
### Quick summary

In INR, MXN, and PHP currencies, we offer a 20% first-year only discount. The pro-rata credits is wrongly calculated from the original price, leading to a bigger discount on plan upgrades than we intend to give. 

### Steps to reproduce

1. In INR currency, head to wordpress.com/start and purchase a Business plan, which is INR 7.680 with a 20% first-year discount.
2. In Calypso, head to Upgrades -> Plans observe that the pro-rata credits banner mentions the non-discounted price of INR 9.600, instead of the price you actually paid before which is INR 7.680. 
3. Click on "Upgrade" for the ecommerce plan
3. In the checkout page, observe the final price of the eCommerce plan.

### What you expected to happen

1. The pro-rata credits banner on Calypso's /plans page should only be for the amount paid (7,680), not for the non-discounted full price (9,600).
2. The eCommerce plan price on the checkout page should be 17,280 (annual eCom price) - 7,680 (price paid for Business plan) = INR 9600.

### What actually happened

1. The pro-rata credits banner should show the discounted price paid (INR 7680)
2. The eCommerce plan price on the checkout page should be INR 9,600, instead of INR 7680. We're losing 20% on plan upgrades without intending to do so. 

https://user-images.githubusercontent.com/1269602/146548963-2eb4bb16-6683-44ba-86c7-bc8dffd96dc8.mov

### Reproducibility

Consistent

**Comment by DavidRothstein** [comment] 2021-12-17 19:54
>The eCommerce plan price on the checkout page should be 17,280 (annual eCom price) - 7,680 (price paid for Business plan) = INR 9600.

I don't think that's correct -- that would mean the user pays a total of 17,280 to get the eCommerce plan (i.e. full price) and never receives the first-year discount at all.

The correct way to do this is to either consistently **count** the 20% discount when determining the product value for upgrades, or consistently **not count** it, but we shouldn't mix and match.  So either of these:

1. 17,280 (annual undiscounted eCommerce price) -  9,600 (annual undiscounted Business price) = INR 7,680
2. 13,824 (annual discounted eCommerce price) - 7,680 (annual discounted Business price) = INR 6,144

The first one is what the code does now.  Personally I think the second makes much more sense (because it means that in the end, the user pays 13,824 which is the same thing they would have paid to just buy the eCommerce plan with a 20% discount in the first place).  But I think either is defensible depending on what the "rules" for the first-year discount are supposed to be.  As best I can tell, the first option was a deliberate business decision (see discussion at p7DVsv-cPX-p2#comment-38858) although it could be changed.

**Comment by niranjan-uma-shankar** [comment] 2021-12-20 08:41
Thanks for the context @DavidRothstein, I understand this better. 

> Personally I think the second makes much more sense (because it means that in the end, the user pays 13,824 which is the same thing they would have paid to just buy the eCommerce plan with a 20% discount in the first place). But I think either is defensible depending on what the "rules" for the first-year discount are supposed to be. As best I can tell, the first option was a deliberate business decision 

I agree with you that the second option makes more sense, but if the first was a deliberate business decision, then I trust the decision. 

For the first option, I don't think I understand why the pro-rata credits is more than the actual money paid because I thought that there's a 1:1 match between pro-rata credits and actual money paid. How does this work when we offer flash sales? For example, the recent [Black Friday promotions offered a 50% discount on plans](https://user-images.githubusercontent.com/1269602/146737798-5007e12f-e949-470a-a416-9223a9c80e6c.png) (p5uIfZ-bH3-p2), so does purchasing such a discounted plan offer pro-rata credits for the discounted amount or the full amount? Are the pro-rata credits behaviour consistent across all types of discounted plans we offer, or should we aim for consistency?

**Comment by DavidRothstein** [comment] 2021-12-22 21:34
Pro-rated credits are based on the "value" of what the user owns, not on what they paid.  Imagine you bought a car for a really low price and then go to trade it in for a newer car later -- you'd probably be mad if the dealer said "your old car is worth $15000 to me, but I know you paid less for it originally so because of that I'm offering you less money on the trade-in".

The flash sale you linked to looks like a coupon, which isn't really part of the product "value", so I guess you could say it works more like option 1 above (but arguably it's a different thing entirely since coupons are applied against the final price in the shopping cart).  For example, if you buy a premium plan at $96 and then use a 50% coupon to upgrade it to a $300 business plan, you will pay `( $300 - $96 ) * 0.5 = $102` for the upgrade, for a total payment of $198 to get the business plan.   I don't think anyone would expect to pay `( $300 * 0.5 - $96 ) = $54` for the upgrade (for a total payment of $150 for the business plan) -- even though they _could_ actually get that price by cancelling/refunding the premium plan, if they're still within the refund window, and then using the 50% coupon on a direct business plan purchase.

**Comment by cuemarie** [comment] 2023-07-18 22:21
_This report was found during a recent backlog sweep._

📌 ACTIONS
- Closed as by design

**Closed as not planned by cuemarie** 2023-07-18 22:21 UTC
Labels: Bug, [Pri] Low
