### ISSUE TITLE
Some Brompton colors can be adjusted on Simple, but not Atomic sites

### ISSUE THREAD

**Issue by kaitohm** [Automattic/wp-calypso#49800] opened 2021-02-08 01:16 UTC
### Steps to reproduce the behavior

1. Apply Brompton theme to simple site
2. Go to WordPress.com > My Sites > Design > Customize > Colors and Backgrounds
3. Confirm how color changes also apply to header and footer areas

Screen recording: https://d.pr/i/O4njIW

Do the same on an Atomic site, and notice the colors of the header and footer do not change

Screen recording: https://d.pr/i/ZdZilz

#### What I expected to happen

Color annotations would be the same across Simple and Atomic versions of the theme.

#### What actually happened

1. Color selections apply differently to the same theme, depending on whether the site is Simple or Atomic
2. The colors chosen by a user while they were Simple are lost once the site goes Atomic

### Context

25881458-hc

#### Is this specific to the applied theme? Which one?

Brompton

#### Does this happen on simple or atomic sites or both?

Different behaviour between Simple and Atomic

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

Reported by user, but reproduced on my test sites.

#### Workaround

I sent the following code to adjust colors of header and footer on Atomic site

```
#masthead,#colophon .footer-navigation, #colophon .site-info {
  border-top-color: #0000FF;
  border-bottom-color: #0000FF;
}

#masthead, #masthead:before, #masthead:after, #colophon .footer-navigation, #colophon .site-info{
  background: #008833
}
```

**Comment by annacmc** [comment] 2021-03-25 03:28
Tested an unable to repro. On both my simple, and Atomic testing site the color changes behaved the same. There has been some refactoring of color annotations and other color palette updates to Varia child themes since this issue was opened, it seems likely the issue has been resolved in this time. 

Closing up as "[Closed] Not Reproducible" at this time, but @bsanevans feel free to re-open if you're still able to repro this.

**Closed as completed by annacmc** 2021-03-25 03:28 UTC
Labels: Bug, [Feature Group] Appearance & Themes, [Pri] Low, [Feature] Customizer, Color Schemes, [Closed] Not Reproducible

**Comment by kaitohm** [comment] 2021-03-25 05:30
I just double checked. The behavior on Atomic sites now matches Simple sites. I agree - issue has resolved itself somewhere. All good now.
