### ISSUE TITLE
Migration trial: The plans page showed 0 days in the trial

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#81063] opened 2023-08-25 08:16 UTC
The plans page showed 0 days in the trial, although the left navigation showed the correct days.

![Image](https://user-images.githubusercontent.com/1241413/263210880-029746fb-9044-4042-bba7-0a36456bbb0a.png)

**Comment by vishnugopal** [comment] 2023-08-31 09:15
Cannot reproduce. Closing!

**Closed as completed by vishnugopal** 2023-08-31 09:15 UTC
Labels: Migration Trials
