### ISSUE TITLE
Hide 1Password at importers URL input

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#64347] opened 2022-06-04 11:07 UTC
### Details

When creating a new site and choosing "import" flow, I see 1Password icon on input when the browser extension is installed

<img width="904" alt="image" src="https://user-images.githubusercontent.com/87168/171996365-a2d8192c-6423-40d9-b90a-3069f742ff8d.png">

This seems unnecessary, and there might be an easy way to disable this with an attribute.

**Comment by arunsathiya** [comment] 2022-06-04 16:25
Quick note that this seems to happen only on Google Chrome:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/18581859/172016075-0a01391d-9a26-4481-a5c9-8e139dda0847.png">

I do not see it on Firefox, which has the same 1Password extension installed:

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/18581859/172016092-78bb31e6-3c38-45a3-aa7f-9967603c785d.png">

**Comment by jimmy319** [comment] 2022-06-23 03:41
I can't reproduce this issue on my end.

<img width="1446" alt="Screen Shot 2022-06-23 at 11 37 22 AM" src="https://user-images.githubusercontent.com/1024985/175203864-6e68aaed-df6a-4807-a8e9-4b5a08009101.png">

@simison Could you help to check if this issue persists on your end?

**Comment by jimmy319** [comment] 2022-07-05 06:16
It's very likely that this issue has been fixed by the 1Password plugin. I think we can close it for now.

**Closed as completed** 2022-07-05 07:35 UTC
Labels: Task, Import
