### ISSUE TITLE
"Expand on click" is not appearing on Image blocks for some people

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/wp-calypso#90063] opened 2024-04-29 20:10 UTC
### Quick summary

Context: 8119197-zd-a8c

User realized that this option was completely missing from their `Image blocks` and they weren't sure why - after some investigation I found that I could replicate the issue on both `Atomic` and `Simple` sites, regardless of which theme I was using.

@jp-imagines was able to get it to appear on one `Simple` site, but we're not sure why: p1714412106678309-slack-C03TY6J1A

It also appears that this was an issue recently that was patched already: https://github.com/Automattic/wp-calypso/issues/89564

### Steps to reproduce

1. You may need to test this on multiple sites, but you need to add an `Image` block to a page/post
2. Try to set the `Expand on click` option that is described here: https://wordpress.com/support/wordpress-editor/blocks/image-block/#link-settings

### What you expected to happen

There should be an option showing `Expand on click` at all times.

### What actually happened

The option isn't showing at all.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by liviopv** [comment] 2024-04-30 14:54
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate
- 
📌 FINDINGS/SCREENSHOTS/VIDEO
@ClassicRKR27 this is an intentional change to avoid a conflict with Jetpack Carousel module, which customers can turn on and off from Settings > Media.

https://github.com/Automattic/jetpack/issues/32668

Once the module is disabled, the option shows up on Image Blocks. This is from the user's site:

![CleanShot 2024-04-30 at 15 52 27@2x](https://github.com/Automattic/wp-calypso/assets/14153300/fa80a38b-2a42-4787-99a4-a2ec8c9ad70a)


📌 ACTIONS
- Closed as  by design

**Closed as completed by liviopv** 2024-04-30 14:54 UTC
Labels: Bug, [Pri] High, Needs triage, Customer report [LEGACY], [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks
