### ISSUE TITLE
Logo won't save while Gutenberg plugin is activated

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/wp-calypso#54055] opened 2021-06-27 13:59 UTC
Updating the logo in the Site identity section of the Customizer won't save. It allows you to change it, and clicking **Save Changes** appears to work, but when you go to the site, or back to the Customizer afterward, the old logo is back. This does not happen if the Gutenberg plugin is deactivated.

### Steps to reproduce the behavior

1. Ensure Gutenberg plugin is activated.
2. Go to Site Identity in Customizer
3. Click Change Logo and select a new logo
4. Click Save Changes and close the Customizer
5. Go to front end of site or back to the Customizer

#### What I expected to happen
I expected to see the new logo.

#### What actually happened
I saw the old logo

(Some users report the logo disappears, instead.)

### Context
This was a user report. I haven't tested on my own site.
4095490-zen

#### Is this specific to the applied theme? Which one?

This is for the Hever theme. It can happen with any theme using a custom logo.

#### Does this happen on simple or atomic sites or both?

This was an AT site. (But happens on Simple Sites as well.)

#### Is there any console output or error text?

No

### Possible workarounds

- Select a different image and save that as the logo in the Customizer. Then go back to the Customizer again and save the image you actually want as your logo.
- Open a post/page in the editor and insert a Site Logo block. Replace the image with the desired logo and save the post. (You can delete the block from the post, or the whole post after you save it once.)
- Deactivate Gutenberg plugin (for Atomic sites)

**Comment by ccwalburn** [comment] 2021-06-27 17:38
Another case here: 30355259-hc
This site used the Baskerville 2 theme.

**Comment by donalirl** [comment] 2021-06-27 23:24
Another case #30339833-hc with a third-party theme.

**Comment by yashitamittal11** [comment] 2021-06-28 02:22
Also reported here- https://github.com/Automattic/wp-calypso/issues/54017

**Comment by jackiejade** [comment] 2021-06-28 15:28
Another case here with Veni theme and Gutenberg deactivated fixes the issue: #30369699-hc

**Comment by KirkwallDay** [comment] 2021-06-28 16:42
Another case here: 13266578-hc: Hever theme, deactivating Gutinberg worked. Tried to re-activate it after to see if they could still take advantage of the features. Reactivating the plugin removed the logo again. Advised them to leave it off.

**Comment by creativecoder** [comment] 2021-06-28 19:16
This appears to happen when the site_logo option and custom_logo theme mod get out of sync. Recent versions of Gutenberg have code to keep these in sync, but it only runs at specific times.

Example

- `site_logo` option is set to image 1
- `custom_logo` theme mod is set to image 2
- You'll see the image 1 in the customizer, because the `site_logo` (setting for the Site Logo block) overrides the `custom_logo` setting.
- But if you want your logo to be image 2, and you try to save that image in the customizer (to update the `custom_logo` setting), it won't update, because `custom_logo` is already set to image 2.
- This prevents the Gutenberg code running to update the `site_logo`, and so you're logo stays the same.

---

Two possible workarounds, until this is fixed:

1. Select a different image and save that as the logo in the Customizer. Then go back to the Customizer again and save the image you actually want as your logo.
2. Open a post/page in the editor and insert a Site Logo block. Replace the image with the desired logo and save the post. (You can delete the block from the post, or the whole post after you save it once.)

**Comment by creativecoder** [comment] 2021-06-28 19:17
^ Note that you'll need the Gutenberg plugin activated for these workarounds to take effect.

**Comment by carladoria** [comment] 2021-06-28 19:58
another case with a Simple site in 30373872-hc
xivfurniture.com 
Is there any workaround for Simple sites? Tried adding/removing/saving several images

**Comment by aisajib** [comment] 2021-06-29 00:29
Also reported in 30360146-hc - the second workaround worked (the first one didn't work since when I went back to the customizer, there were no images to begin with, and selecting another didn't do anything).

**Comment by galakhyati** [comment] 2021-06-29 09:51
Another case here:
Simple site.
Site: https://traductionsbrio.com/

**Comment by lizswafford** [comment] 2021-06-29 13:14
29967113-hc
Simple Site. 
Workaround using Site Logo Block fixed it.

**Comment by sophiegyo** [comment] 2021-06-29 14:03
Atomic site, same issue:  #30385906-hc

Logo just didn't display at all (in the Customizer, or anywhere else) with Gutenberg active.

Fixed by: deactivating Gutenberg (version 10.9.1)

**Comment by druesome** [comment] 2021-06-29 15:25
Chat: #30387014-hc

Gave them this CSS as a workaround.  Note that there has to be a site title and it must be visible on the site for this to work.

```
.selector a {
height: 80px;       
width:  400px;
white-space: nowrap;
overflow: hidden;
text-indent: -9999px;   
margin: 0 !important;
background: url(URLTOIMAGE) no-repeat;
background-size: contain;
display: inline-block;
}

```

**Comment by KirkwallDay** [comment] 2021-06-29 16:35
Another instance here: 5134826-hc. 
The workarounds didn't work. They will need to be notified when the bug is fixed.

**Comment by KirkwallDay** [comment] 2021-06-29 16:55
Another instance here: 27261916-hc
Workaround 2 worked. 

I think the workarounds only work if the site currently has a logo, with no logo before the bug occurred, they seem not to work.

**Comment by dhackneya8c** [comment] 2021-06-29 17:14
Another report: 30388973-hc
Deactivating Gutenberg worked

**Comment by AtrumGeost** [comment] 2021-06-29 21:35
Another case: 29224901-hc
Deactivating the Gutenberg plugin worked

**Comment by AtrumGeost** [comment] 2021-06-30 13:17
Got another report on a simple site: 4105602-zd-woothemes

The workaround mentioned above worked:

`Open a post/page in the editor and insert a Site Logo block. Replace the image with the desired logo and save the post. (You can delete the block from the post, or the whole post after you save it once.)`

**Comment by xpurichan** [comment] 2021-06-30 14:26
Experienced this in 30405625-hc. Deactivated Gutenberg, changed the logo, reactivated Gutenberg.

**Comment by KirkwallDay** [comment] 2021-06-30 15:02
Another instance here: 29989649-hc
Using the site-logo block work-around worked, the site had a logo before the bug occurred.

**Comment by Thelmachido** [comment] 2021-06-30 16:23
Another case here: 4103714-ZD
The below workaround worked 
`Open a post/page in the editor and insert a Site Logo block. Replace the image with the desired logo and save the post. (You can delete the block from the post, or the whole post after you save it once.)`

**Comment by kriskarkoski** [comment] 2021-06-30 18:21
4103158-zen

**Comment by aamills** [comment] 2021-06-30 19:32
Additional report 4100773-zen, advised the user on the possible work arounds.

**Comment by davipontesblog** [comment] 2021-06-30 20:09
Adding High priority on this one due to the volume of incidence so far in just three days.

**Comment by csonnek** [comment] 2021-06-30 20:32
Also reported in https://wordpress.com/forums/topic/randomly-missing-website-logo/

They had a logo set previously, so did not advise they try the workaround.

**Comment by creativecoder** [comment] 2021-06-30 20:53
Note that I'm working on the Jetpack side of this here: https://github.com/Automattic/jetpack/pull/20192

Aiming to get this into the 9.9 release next week.

**Comment by khristiansnyder** [comment] 2021-06-30 21:35
30195004-hc

site-logo block workaround was successful.

**Comment by kaitohm** [comment] 2021-07-01 07:10
4105200-zd-woothemes

site-logo block workaround was successful.

**Comment by fresatomica** [comment] 2021-07-01 09:45
Another report: https://wordpress.com/forums/topic/baskerville-2-theme-the-logo-suddenly-disappeared/

**Comment by Gilmoursa** [comment] 2021-07-01 14:42
Another report at: 30268394-hc
simple site

Caveat for Option 2, the page must be published, it doesn't work for a draft.

**Comment by ccwalburn** [comment] 2021-07-01 16:08
Another report: 4106439-zen

**Comment by kaitohm** [comment] 2021-07-02 01:55
Another report on Atomic site: 30431124-hc

Workaround 1 (selecting a different logo) did not work. Workaround 2 (changing the logo in a Site Logo block) did work.

**Comment by kaitohm** [comment] 2021-07-02 04:55
Another report: 4108979-zd-woothemes
Having the user try the workaround of changing the logo through the Site Logo block.

**Comment by fresatomica** [comment] 2021-07-02 07:40
Another report: https://wordpress.com/forums/topic/logo-disappearing-not-staying/

**Comment by davipontesblog** [comment] 2021-07-02 11:16
@mrfoxtalbot is this a duplicate of https://github.com/Automattic/wp-calypso/issues/53517?

**Comment by sguzovskaia** [comment] 2021-07-02 11:37
Another report: 30408388-hc/4108662-zen 
Advised the user on the possible workarounds.

**Comment by creativecoder** [comment] 2021-07-02 14:09
Note some users are experiencing the logo disappear when trying to save it in the Customizer--I believe that has the same cause as the logo not updating, so we're tracking that case here, as well.

**Comment by creativecoder** [comment] 2021-07-02 16:44
Gutenberg issue that seems to be part of the cause of the logo not updated (or disappearing) on WP.com: https://github.com/WordPress/gutenberg/issues/33177

**Comment by creativecoder** [comment] 2021-07-02 19:08
Gutenberg PR that addresses some more of the underlying issues: https://github.com/WordPress/gutenberg/pull/33179

**Comment by creativecoder** [comment] 2021-07-02 22:52
Note that I have a hotfix for this on Simple Sites at D63662-code.

Assuming it passes testing, it can be deployed immediately after the Jetpack release next week, on July 6th.

**Comment by villanovachile** [comment] 2021-07-03 16:25
Another report here: 29178751-hc

Workaround using site logo block resolved issue.

**Comment by JoshuaGoode** [comment] 2021-07-03 17:32
I encountered this on 28753841-hc

Not sure if it will stick but to resolve we were able to temporarily deactivate Gutenberg, set the logo in the Customizer, and then reactivate Gutenberg. 

So:

1. Deactivate Gutenberg
2. Set the logo in the customizer and Save Changes.
3. Reactivate Gutenberg

We flushed cache and tried adjusting things in the Customizer again. The logo remained.

**Comment by joweber123** [comment] 2021-07-04 02:01
Simple site - 4113750-zen

Workaround using site logo block resolved issue.

**Comment by poojashetty18** [comment] 2021-07-04 06:35
Another case: 30098382-hc
Deactivating the Gutenberg plugin worked. Reactivating it back after updating the logo was still showing the wrong logo.

**Comment by KirkwallDay** [comment] 2021-07-04 19:26
Another instance here - 4112055-zen
Workaround 2 using a site-logo block worked here.

**Comment by kaitohm** [comment] 2021-07-05 00:31
Another instance: 4115546-zd-woothemes
Asked them to try workaround 2 - replacing logo in Site Logo Block

**Comment by happychait** [comment] 2021-07-05 00:47
#1627073-hc

Applied the [Site Logo block workaround here.](https://github.com/Automattic/wp-calypso/issues/54055#issuecomment-869953902)

**Comment by kaitohm** [comment] 2021-07-05 02:37
Another instance: 4115259-zd-woothemes
Asked them to try workaround 2 - replacing logo in Site Logo Block

**Comment by fresatomica** [comment] 2021-07-05 06:22
Another report: https://wordpress.com/forums/topic/my-logo-is-disappearing/
The workaround didn't work.

**Comment by synora** [comment] 2021-07-05 13:03
4117160-zd. Deactivating Gutenberg, saving the site logo in the Customizer, then reactivating Gutenberg again worked.

**Comment by ccwalburn** [comment] 2021-07-05 15:00
30482549-hc
User's logo disappeared.
Adding the Site Logo block to a page fixed it.

**Comment by liviopv** [comment] 2021-07-05 16:42
Another 4117643-hc. Changing the Site Logo block worked.

**Comment by Nic-Sevic** [comment] 2021-07-05 16:56
another instance here: 30016318-hc
workaround provided with CSS

**Comment by joweber123** [comment] 2021-07-06 02:07
Simple site -4117408-zen

Workaround using site logo block resolved issue.

**Comment by gwensmithx** [comment] 2021-07-06 02:22
AT site - 4118278-zen
Deactivating the gutenberg plugin worked.

**Comment by zdenys** [comment] 2021-07-06 08:30
Simple Site 4118132-zd-woothemes Asked them to try the [two workarounds from above](https://github.com/Automattic/wp-calypso/issues/54055#issuecomment-869953902).

**Comment by sguzovskaia** [comment] 2021-07-06 13:44
Somewhat a similar issue: the site logo is getting re-added again after the user removes it and saves changes in Customizer.
Reproduced the issue from my end. Two workarounds from above didn't work. AT site
The user resolved it by permanently removing the logo image from the media library and it helped to remove the logo.
30496468-hc

**Comment by jartes** [comment] 2021-07-06 13:59
Another one on 30174430-hc with the Ippo theme. 

Fixed by adding the `Site logo` block, setting the logo and then removing it.

**Comment by creativecoder** [comment] 2021-07-06 19:31
D63662-code has been deployed to hotfix this issue for Simple Sites. I'm trying to get the [proper fix into Gutenberg 11.0.0](https://github.com/WordPress/gutenberg/pull/33179#issuecomment-875014402).

**Comment by creativecoder** [comment] 2021-07-07 00:35
A hotfix for Atomic sites will go out shortly, as well, which should resolve this issue for all WP.com users.

But please reopen if there are additional reports.

**Comment by poojashetty18** [comment] 2021-08-04 11:23
Another report on 30961676-hc
Simple site using Luxury theme.
Fixed by adding the Site logo block, setting the logo and then removing it.

**Comment by synora** [comment] 2021-08-04 18:52
I'm unable to replicate this on simple or Atomic sites.

**Closed as completed by synora** 2021-08-04 18:52 UTC
Labels: Bug, [Pri] High, [Feature] Customizer, User Waiting, Logo, Triaged
