### ISSUE TITLE
Broken Blocks with Mixed Classic Editor Content

### ISSUE THREAD

**Issue by carinapilar** [Automattic/wp-calypso#54939] opened 2021-07-27 19:43 UTC
### Summary
Additional paragraph tags in the post's code are breaking the block editor.

### Steps to reproduce the behavior
I wasn't able to replicate this issue on a test site yet. I checked the user's posts and found that most of them open within the Classic block, so it seems they were created with the Classic Editor. The posts that are showing the issues, have content from the block editor, so they might have been recently edited with it.

### Screenshots
The post in the editor:
![BlocksIssue1_GH](https://user-images.githubusercontent.com/16104522/127216272-257ce57b-bd77-47a5-909a-ed39df023a61.jpg)

The code for the broken content:
![BlocksIssue2_GH](https://user-images.githubusercontent.com/16104522/127216274-cebfdd44-084c-4f65-abbf-4e680e644023.jpg)

It loads in the Classic Editor:
![BlocksIssue3_GH](https://user-images.githubusercontent.com/16104522/127216281-5ae16274-0b89-4c8a-90f2-66f31f6210fe.jpg)

Reported on 4178472-zd-woothemes - explained how to use the Classic Editor to be able to edit the posts. I was also wondering if we would be able to fix the broken posts somehow for them.

**Comment by kosiew** [comment] 2021-08-02 07:15
Hi @carinapilar ,

Thanks for reporting this and the detailed steps.

To recap,

The corrupted blocks are not editable in Block Editor. They are however editable in Classic Editor.

I also took a look at post id 3417. I copied it to post id 3796 and then on each block, I clicked the 3 dots > Resolve > Convert to blocks.
The saved 3796 did not contain any errors.


I ran a search and did not see other similar issues.
Since this is not reproduceable and is an isolated case, I am closing this for now.

The workaround for the Customer is to use the Classic Editor to edit the affected posts or use Resolve > convert to blocks to salvage the content.

**Closed as completed by kosiew** 2021-08-02 07:15 UTC
Labels: Bug
