### ISSUE TITLE
Editor: post content does not save on iOS and Android Chrome

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wp-calypso#12142] opened 2017-03-14 21:55 UTC
#### Steps to reproduce
1. Using Chrome on Android or iOS, open a new incognito window at URL: https://wordpress.com/
2. Log in.
2. Click on the "post" icon in the top toolbar.
2. Begin composing a new post by adding a title, then add some text to the body.
3. Press "Save" in the header area and wait until it reads "Saved".
4. Click the URL bar and enter https://wordpress.com/ again.
5. Click the "post" icon in the top toolbar again.
6. Click the drafts number adjacent to the "post" icon in the top toolbar to show recent drafts.
7. Click the title of your draft.

#### What I expected

To see the draft with the body text and the title.

#### What happened instead

Only the title was preserved. The body text was not saved.

#### Browser / OS version

Tested in iOS Chrome (iPhone 5s) and Android Chrome (Nexus 5).

#### Context / Source

Originally reported by a person via WordPress.com support.

**Comment by sirbrillig** [comment] 2017-03-14 22:23
I was able to reproduce on iOS Chrome and Android Chrome on a new test site, but now I am not able to reproduce any more. Trying to see what may have caused it, if anything.

**Comment by Lochlaer** [comment] 2017-03-21 01:30
User has opened a new ticket and says he's still having the same problems. 

I tried replicating it on my own phone (Android 7.1.1, Google Pixel) using @sirbrillig's clear, step-by-step instructions above, but I couldn't get past the *Title*. When I tried to go to the editor box itself, the default keyboard never popped up. This is where I got stuck:

![screenshot_20170320-201528](https://cloud.githubusercontent.com/assets/6569475/24128484/39c3a076-0daa-11e7-8965-ba82d86f43bd.png)

Then I got a phone call. I took the call, and subsequently returned to my post. Voila! The toolbar showed up, and I was able to type into the editor box. I typed some text in the box and clicked SAVE. I waited a second or two until it said SAVED.

![screenshot_20170320-202352](https://cloud.githubusercontent.com/assets/6569475/24128681/792139b2-0dab-11e7-94ac-a5b573a76c49.png)

I went back to the address bar and typed in https://wordpress.com, clicked on the "post icon," selected my site, and clicked on the drafts number (1). 

![screenshot_20170320-202502](https://cloud.githubusercontent.com/assets/6569475/24128715/ad591240-0dab-11e7-9cea-f27a61bf055e.png)

I clicked on the test draft post, and my body text had disappeared. 

![screenshot_20170320-202508](https://cloud.githubusercontent.com/assets/6569475/24128743/da692a0e-0dab-11e7-95ba-1bd3e8e9c335.png)

Note: My phone just updated to the latest version of Android about half an hour before I tested this.

**Comment by timmyc** [comment] 2017-03-22 23:10
> I clicked on the test draft post, and my body text had disappeared.

In that image, it appears like something has prevented TinyMCE from loading completely - note the lack of the toolbar.  This would lead me to believe that there was either an API issue when reloading the saved draft, or perhaps an exception happened that prevented the loading from moving forward.

@Lochlaer - by chance were you able to, or did you navigate away from this screen?

**Comment by timmyc** [comment] 2017-03-22 23:24
I am not able to reproduce this issue on a Nexus 5x - however, I do see the same screen as @Lochlaer added above where the post_content has yet to load into TinyMCE - this is how it looks while TinyMCE is still initializing.

Perhaps we could use a loading indicator here to help show some progress is happening.

I did get this screen to happen more frequently by turning off WiFi on my phone and using the cellular connection instead.  I'm going to close this out, but if we get additional reports, or precise steps to re-create consistently lets reopen this.

**Closed by timmyc** 2017-03-22 23:24 UTC
Labels: Editor, [Type] Bug
