### ISSUE TITLE
i18n: Categories in vertical survey don't change when you switch to a different language.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#4741] opened 2016-04-14 12:43 UTC
#### Steps to reproduce
1. Start signup with a non-en language. For example, `/start/website/survey/ja`
2. Change the language to English by clicking "Also available in English"
#### What I expected

The categories in the survey also change to English.
#### What happened instead

Although the step header and everything change as expected, the categories stay in Japanese (or any language you started with).
#### Browser / OS version

Chrome 49.0.2623.112, Mac
#### Screenshot / Video

![screen shot 2016-04-14 at 13 41 52](https://cloud.githubusercontent.com/assets/908665/14528286/b815c14a-0246-11e6-9e7a-2be10f856f12.png)

![screen shot 2016-04-14 at 13 41 31](https://cloud.githubusercontent.com/assets/908665/14528297/c09d51ac-0246-11e6-8676-e0e0459b4af2.png)

**Comment by sirbrillig** [comment] 2016-04-14 14:18
Same as #4408 but this should probably stay because that's a PR with no associated issue.

**Comment by hoverduck** [comment] 2016-05-19 20:57
19May16 Bug Scrub

Confirmed this is still an issue, although I had slightly mixed/worse results.

The "Also available in English" link points to `https://wordpress.com/start/domains-with-premium/themes/en`.  Sometimes when clicking the link it actually updates the route / URL in the address bar, and the page loads fine (all in English, except for the title on the tab/window itself).  But sometimes it doesn't update the URL, and in that case it's an incomplete translation update, leaving some Japanese on the page.  To make it worse, once a theme is selected, console errors are spammed and the page is completely broken:

![wp-calypso-4741](https://cloud.githubusercontent.com/assets/7233112/15409329/4c84612c-1de2-11e6-9e88-ae57af28a1b5.gif)

But here's an example of everything working just fine (nothing in the JS console on this run)
![wp-calypso-4741-2](https://cloud.githubusercontent.com/assets/7233112/15409405/aaaef550-1de2-11e6-8cd5-756a4adb5e35.gif)

**Comment by lancewillett** [comment] 2016-10-10 18:24
Still waiting on a fix.

**Comment by rachelmcr** [comment] 2017-08-22 15:03
This vertical survey is no longer live. I tested with a different survey signup flow at https://wordpress.com/start/surveystep and the language switch works as expected there (and in other signup flows I checked) so I'll close this issue as there's no longer an active signup flow with this problem.

**Closed by rachelmcr** 2017-08-22 15:03 UTC
Labels: i18n, Signup, [Type] Bug
