### ISSUE TITLE
Log-in Link Form causes 504 while logged in

### ISSUE THREAD

**Issue by prettyboymp** [Automattic/wp-calypso#46652] opened 2020-10-21 17:10 UTC
#### Steps to reproduce

1. Log in to an account
2. Visit https://wordpress.com/log-in/link

#### What I expected
To be shown the form to send a log-in link to an email address or a notification that I'm already logged in.

#### What happened instead
504 Gateway Timeout

#### Context / Source
This link is sent to users who need help recovering their account.  If they are logged into a different account at the time, they are not able to use the link given.

**Comment by retrofox** [comment] 2020-10-28 18:16
I've been trying to isolate this error. The problem is the `log-in/link` URL works as expected in the dev env as well as in a calypso.live instance. I've created a draft branch just for debugging purposes. 
This is the [PR](https://github.com/Automattic/wp-calypso/pull/46806), and this is the [calypso.live branch](https://hash-bc8c56f1849b35e23c2c5c49ed515a9ceb831fbd.calypso.live/).

Here, we can confirm that [/log-in/link](https://hash-bc8c56f1849b35e23c2c5c49ed515a9ceb831fbd.calypso.live/) works as expected. At least it renders the form, avoiding the `504` error:

![image](https://user-images.githubusercontent.com/77539/97478229-6a268a00-192f-11eb-9f24-15cefa2c8c23.png)

Another thing to keep in mind if it falls down in `504` when the user is logged in. If the user isn't logged in, the form renders properly even in production.

pinging to @jsnajdr and @tyxla maybe you can help to figure out what's happening here. Thanks 🙏

**Comment by tyxla** [comment] 2020-10-29 16:17
This is being addressed in #46910.

**Closed** 2020-10-30 10:18 UTC
Labels: Login, [Pri] High, [Type] Bug
