### ISSUE TITLE
Tiled Gallery :: showing symbol ( greater than/less than ) on the frontend for the free site. 

### ISSUE THREAD

**Issue by mdtanjid0** [Automattic/wp-calypso#66876] opened 2022-08-23 16:11 UTC
### Quick summary

Adding a Tiled Gallery showing a great than/less than symbol on the frontend for the free site: 

Editor: 
<img width="2150" alt="image" src="https://user-images.githubusercontent.com/54123436/186207293-02e5b705-c339-4528-93f8-2172ff482c53.png">

Frontend: 

<img width="3314" alt="image" src="https://user-images.githubusercontent.com/54123436/186207412-940501f0-f4b0-4d96-9360-ced7cee3ba1e.png">

Example post: https://tanjidrahat.wordpress.com/2022/03/16/251/

I couldn't replicate the issue with a Biz plan: 

Example post: https://mdtanjid.blog/2021/03/19/sint-maxime-deleniti-ratione/

### Steps to reproduce

1. Add a Tiled Gallery on a **free** plan. 
2. And check on the frontend ( make sure to add some images ). 

### What you expected to happen

It shouldn't show the greater than/less than the symbol. 

### What actually happened

It's showing unexpected characters like "<" ">". 

### Context

5500220-zd

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by ahmadbaig1** [comment] 2022-08-23 16:18
Was reported at multiple places- 
https://github.com/Automattic/wp-calypso/issues/66875
https://github.com/Automattic/wp-calypso/issues/66865

Needs to be merged.

**Comment by oskosk** [comment] 2022-08-23 20:41
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/66865

Fixed in https://github.com/Automattic/jetpack/pull/25795

**Closed as completed by oskosk** 2022-08-23 20:41 UTC
Labels: Bug, [Platform] Simple
