### ISSUE TITLE
Gutenberg Blocks in comments: display toolbar over the active block

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/wp-calypso#41277] opened 2020-04-20 13:13 UTC
#### Steps to reproduce

1. Edit a comment with several blocks on a p2tenberg enabled p2
2. The toolbar for a block is displayed on top of the comment area, not on top of the block. This makes sometimes confusing and difficult to understand the block that is going to be impacted by actions in this toolbar.  
3. I'd suggest the toolbar is shown on top of the referred block.

#### What I expected
I expected this to work like for pages or posts (With the toolbar over the active block)

#### What happened instead

<img width="358" alt="Feature Requests + Our Communication | Team Neptune 2020-04-20 15-11-33" src="https://user-images.githubusercontent.com/6404071/79755429-662f0500-8319-11ea-93ea-60246c076516.png">
<img width="377" alt="Feature Requests + Our Communication | Team Neptune 2020-04-20 15-11-04" src="https://user-images.githubusercontent.com/6404071/79755432-67603200-8319-11ea-8a15-9adc945bd247.png">

#### Browser / OS version
Any

**Comment by rantoncuadrado** [comment] 2020-04-20 13:15
cc: @lancewillett

**Comment by lancewillett** [comment] 2020-04-20 15:48
Closed as duplicate of https://github.com/Automattic/p2tenberg/issues/211

**Closed by lancewillett** 2020-04-20 15:48 UTC
