### ISSUE TITLE
Group blocks `alt` text showing `[object Object]`

### ISSUE THREAD

**Issue by xavier-lc** [Automattic/wp-calypso#96079] opened 2024-11-05 16:15 UTC
### Quick summary

On the page editor, creating a group block shows javascript instead of te proper text when hovering the group types. That's because the `aria-label` attribute is not properly set.

![Image](https://github.com/user-attachments/assets/0259f13a-6007-42b9-a6b5-b77535fb63fd)
![Image](https://github.com/user-attachments/assets/8f07e166-622f-45bc-bf47-cd3b063dbdf1)
![Image](https://github.com/user-attachments/assets/7e5b6d33-1921-4538-ba16-4a66010f3856)
![Image](https://github.com/user-attachments/assets/059ab383-baa9-4e85-9967-5735d932cbd9)

### Steps to reproduce

1. Go to `/wp-admin/post-new.php?post_type=page`
2. Choose `Blank page`
3. Type `/` to choose a block
4. Choose `Group`
5. Confirm that hovering the group types shows `[object Object]`

### What you expected to happen

The group type description should be shown instead.

### What actually happened

The group types shows `[object Object]`

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by xavier-lc** [comment] 2024-11-06 15:20
@phcp huh, that's weird, I've just reproduced it on an atomic and simple site with the Chrome browser. As I mentioned on the description, I've seen it when creating a new page.

**Comment by phcp** [comment] 2024-11-06 18:40
> @phcp huh, that's weird, I've just reproduced it on an atomic and simple site with the Chrome browser. As I mentioned on the description, I've seen it when creating a new page.

Indeed, I just noticed that the atomic site I was testing is broken. I could see the error on other sites.

📌 **RESULTS**

- Could reproduce with simple sites and atomic sites.
- Could reproduce while editing posts or pages.
- Couldn't reproduce it on a self-hosted site using the same Gutenberg version.
- Tested with different locales and had the same issue.

📌 **FINDINGS**

- The last element is still being displayed correctly.
- Translations are working correctly, but the variation descriptions are somehow changed to react elements at some point. The string that should be displayed is inside the object as the prop `children`, but it's unclear where it happens.

![Image](https://github.com/user-attachments/assets/96cd9aea-ef22-434c-9b36-15b501608d29)

📌 **ACTIONS**

- Triaged.
- Keep it as High priority since it breaks accessibility and can be annoying to the users

**Comment by andregardi** [comment] 2024-11-12 00:20
I investigated that today, but not much luck.
I setup locally an older version of Calypso. I reset it to ([#85758](https://github.com/Automattic/wp-calypso/pull/85758)) the first merged PR of the year on January 1. Still got to reproduce the bug, which is enough evidence for me that this is not calypso related.

At https://github.com/WordPress/gutenberg, there is the [block editor live demo](https://wordpress.org/gutenberg/) in which I could not reproduce the bug. So, at a first look, does not seem to be related with Gutenberg.

I tried self hosted WordPress and got the same results as Paulo.
Even putting it through jurassic tube and accessing the site under wordpress.com, I was able to reproduce the issue.

I also checked that  translations for `Arrange blocks vertically`, `Arrange blocks horizontally` and `Gather blocks in a container` are not new to this version. I see this terms used on the js file at least from v18.0.0, the oldest plugin version we still keep on sandbox.

**Comment by dsas** [comment] 2024-11-18 17:12
I can't repro on a Jurassic Ninja site with the GB plugin activated. I'll try and debug on dotcom.

**Comment by dsas** [comment] 2024-11-18 22:32
> Translations are working correctly, but the variation descriptions are somehow changed to react elements at some point. The string that should be displayed is inside the object as the prop children, but it's unclear where it happens.

It happens in Jetpack-mu.

The "extra" props listed there with the descriptions: `link` and `postId` are part of [blockInfoWithVariations](https://github.com/Automattic/jetpack/blob/42e75996d689e48669c2907472eca091424f18a1/projects/packages/jetpack-mu-wpcom/src/features/wpcom-block-description-links/src/block-links-map.ts#L358). You can see that the grid variation works fine, and in your screenshot of the props, its description is a string rather than a ReactElement.

The description is [transformed into a "Learn More"](https://github.com/Automattic/jetpack/blob/42e75996d689e48669c2907472eca091424f18a1/projects/packages/jetpack-mu-wpcom/src/features/wpcom-block-description-links/index.tsx#L12) which [replaces the original description.](https://github.com/Automattic/jetpack/blob/42e75996d689e48669c2907472eca091424f18a1/projects/packages/jetpack-mu-wpcom/src/features/wpcom-block-description-links/index.tsx#L104).

This transformed "Learn More" description is intended to be used in the sidebar as a nice help link to learn more about the block, but obviously that won't work for the variations placeholder 🤔 

![Image](https://github.com/user-attachments/assets/0071a4b0-4a40-4960-9db8-29b8871ddf46)

**Comment by dsas** [comment] 2024-11-18 22:39
Bah, I tried to see if this was always a problem, and it appeared that I [reviewed the PR that added the links](https://github.com/Automattic/wp-calypso/issues/71384).

@BogdanUngureanu, can you remember if we looked at the variations placeholder on the initial PR? I'm guessing from the test instructions it was an oversight, but if not, then it might help track down when this stopped working.

**Comment by BogdanUngureanu** [comment] 2024-11-19 13:08
@dsas Sorry, I don't remember if we looked at the placeholders. :(

**Comment by dsas** [comment] 2024-11-19 22:55
Following on from my [previous comment](https://github.com/Automattic/wp-calypso/issues/96079#issuecomment-2484271945) explaining that this is due to dotcom's "Block guide" support link in descriptions.

 * The official GB API docs say that the [description field is a string](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-registration.md#description-optional)
 * [Non-string descriptions aren't searchable when finding a block](https://github.com/WordPress/gutenberg/pull/44233)
 * [Non-string descriptions were deprecated two years ago](https://github.com/WordPress/gutenberg/pull/44455) in WordPress 6.2
 * There's an [issue in GB to do this with a SlotFill](https://github.com/WordPress/gutenberg/issues/49887) and even an [implementation](https://github.com/WordPress/gutenberg/pull/66170) though it's stalled over trust issues for extenders and I'd guess is unlikely to move anytime soon.

To resolve this issue I'm planning to undo the [change which added the support links for group, row and stack blocks](https://github.com/Automattic/wp-calypso/pull/74571) only :( cc @donalirl . 

For all of the other blocks, we're arguably living on borrowed time and searching for those blocks is already broken.

If these links are important (my assumption is that they are very useful), then the correct thing to do is firstly, demonstrate the importance of this with Gutenberg, and secondly to work with them on a PR.

**Closed as completed** 2024-11-21 15:59 UTC
Labels: Bug, [Pri] High, Triaged, [Status] Priority Review Triggered, [Product] WordPress.com, [Feature Group] Editor Experience, [Feature] Core Blocks, Groundskeeping
