### ISSUE TITLE
Gutenberg in Calypso: switching back to classic Calypso editor doesn't show changes

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#29216] opened 2018-12-07 06:03 UTC
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/post/ using classic editor
2. Enter title and text and save draft
3. Switch to new editor within Calypso
4. Draft displayed
5. Make some updates
6. Switch back to classic editor

#### What I expected

Changes displayed immediately in classic editor - like it does when using wp-admin

#### What happened instead

Old contents displayed due to no page refresh

#### Browser / OS version

Chrome 70 on macOS

#### Screenshot / Video

Calypso Gutenberg ❌ 

![classic editor and calypso](https://user-images.githubusercontent.com/128826/49630395-aef26080-fa39-11e8-9aee-544f0bf41027.gif)

Calypsofy wp-admin ✅ 

![classic editor and wp-admin](https://user-images.githubusercontent.com/128826/49630389-a4d06200-fa39-11e8-811f-3517896ae6cb.gif)

**Comment by Copons** [comment] 2018-12-07 12:15
Can reproduce.
The cause is probably the same that screws up when editing with Gutenlypso different posts.
Maybe the Gutenberg autosave doesn't work properly with Calypso?

**Comment by Copons** [comment] 2018-12-12 16:02
This was not fixed by #29310.

**Closed** 2018-12-18 10:55 UTC
Labels: [Goal] Gutenberg, [Pri] High
