### ISSUE TITLE
Embed Block: Facebook Embeds are not displaying

### ISSUE THREAD

**Issue by RealCarFax** [Automattic/wp-calypso#52455] opened 2021-04-30 16:06 UTC
#### Steps to reproduce

1. Open a new page or post
2. Paste a Facebook post link into the body of the page or post

#### What I expected
The embed block will generate, it should show the post (video, image, text, etc).

#### What happened instead
The post does not display embedded on the site, the area is blank.

#### Browser / OS version
All that I have tested - Firefox 88.0 (64-bit), Safari 14.1 (16611.1.21.161.3), and Chrome 90.0.4430.93 (Official Build) (x86_64)

#### Screenshot / Video
Screenshot of our Facebook Embeds doc: https://d.pr/i/dGTVNh/SdDMeFLaYG

#### Context / Source

Originally reported in #8603828-hc but I can see this is happening elsewhere such as in our own documentation: https://wordpress.com/support/facebook-integration/facebook-embeds/

**Comment by Gilmoursa** [comment] 2021-04-30 16:20
another report in #28881839-hc

**Comment by katiebethbrown** [comment] 2021-04-30 16:21
Noticed some console errors on the support doc:

<img width="1159" alt="FBembedconsoleerrors" src="https://user-images.githubusercontent.com/42279181/116724396-d8f7a500-a99d-11eb-862f-6800854f61a4.png">

**Comment by TheSteveK** [comment] 2021-04-30 16:42
Another user report 28832836-hc

**Comment by JoshuaGoode** [comment] 2021-04-30 16:45
Reproduced on Atomic.

**Comment by JoshuaGoode** [comment] 2021-04-30 16:48
Reproduced on self-hosted.  Might not be WPCOM specific.

**Comment by aisajib** [comment] 2021-04-30 16:48
Has this been fixed? I was able to view the embed just now on the support page. 

<img width="750" alt="Screen Shot 2021-04-30 at 10 48 10 PM" src="https://user-images.githubusercontent.com/2541844/116727270-260f6180-aa06-11eb-86c5-e55d07b63b96.png">

**Comment by RealCarFax** [comment] 2021-04-30 16:50
> Has this been fixed? I was able to view the embed just now on the support page.
> 
> <img alt="Screen Shot 2021-04-30 at 10 48 10 PM" width="750" src="https://user-images.githubusercontent.com/2541844/116727270-260f6180-aa06-11eb-86c5-e55d07b63b96.png">

Strange, it still does not work for me: https://d.pr/i/BGU89t/Iunj6EqpqZ

**Comment by JoshuaGoode** [comment] 2021-04-30 16:53
Doesn't appear to be WPCOM specific. I can reproduce on self-hosted and via a manual HTML embed using their JS SDK on a non-WP site. 

Looks like Facebook's JS SDK and Social Plugins are failing: 

- https://developers.facebook.com/status/dashboard/
- https://developers.facebook.com/status/issues/492652922187445/
- https://developers.facebook.com/support/bugs/484663959337678/

**Comment by aisajib** [comment] 2021-04-30 16:53
Tried a few more things. 

* Works for me on Chrome, proxied/unproxied/incognito
* DOES NOT work on Firefox (proxied)
* Does not work on Safari (unproxied)

**Comment by aisajib** [comment] 2021-04-30 16:54
> Doesn't appear to be WPCOM specific. I can reproduce on self-hosted and via a manual HTML embed using their JS SDK on a non-WP site.
> 
> Looks like Facebook's JS SDK and Social Plugins are failing:
> 
> * https://developers.facebook.com/status/dashboard/
> * https://developers.facebook.com/status/issues/492652922187445/
> * https://developers.facebook.com/support/bugs/484663959337678/

Thanks! That explains the intermittent behavior.

**Comment by nerdysandy** [comment] 2021-04-30 17:08
Reported on #25212350-hc

**Comment by JoshuaGoode** [comment] 2021-04-30 18:12
Confirming that the Facebook embed issue is due to Facebook's outages reported at https://developers.facebook.com/status/issues/492652922187445/

This also impacts their chat embeds, official sharing buttons, page widgets, and more.

I'd expect any type of embed relying on Facebook's JS SDK and Social Plugins to have intermittent issues for now. 

If a user reports sharing buttons issues, they will want to the button style away from the official option under My Site > Tools > Marketing > Sharing Buttons

**Comment by JoshuaGoode** [comment] 2021-04-30 18:13
Official sharing button isuses reported on 29330300-hc

I worked with the user to switch the button style under My Site > Tools > Marketing > Sharing Buttons to resolve.

**Comment by synora** [comment] 2021-05-03 17:44
Embeds on https://wordpress.com/support/facebook-integration/facebook-embeds/ are working for me. 
https://developers.facebook.com/status/issues/492652922187445/ says the issue has been resolved. Closing this issiue for now but we can always reopen if needed.

**Closed as completed by synora** 2021-05-03 17:44 UTC
Labels: Bug, Triaged, [Closed] Not Reproducible
