### ISSUE TITLE
Pages: Posts Page name missing for atomic sites

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#18184] opened 2017-09-22 16:05 UTC
#### Steps to reproduce
Note: This is specific to WordPress.com Atomic sites
1. Starting at URL: WordPress.com/customize
2. Use Static Front Page to select both a Static Front Page and a Posts Page
3. Save & Publish 
4. Navigate to My Site > Site Pages
5. The first entry reads: **Blog Posts** "" page is showing your latest posts

#### What I expected
The name of the page would be displayed as on WordPress.com Simple Sites

#### What happened instead
Empty quotes were displayed instead of the page name for WordPress.com Atomic sites

#### Screenshots

WordPress.com Simple:
<img width="863" alt="screen shot 2017-09-22 at 12 02 33 pm" src="https://user-images.githubusercontent.com/13856531/30753712-23ad7962-9f8e-11e7-8ded-788f237a2c2e.png">

WordPress.com Atomic:
<img width="828" alt="screen shot 2017-09-22 at 12 01 11 pm" src="https://user-images.githubusercontent.com/13856531/30753705-1f50c982-9f8e-11e7-8fc4-709fb1ff6880.png">

#user-report in 652445-hc

**Comment by suyogyashukla** [comment] 2017-09-27 10:25
I had a user asking about ETA of the fix on HappyChat: https://mc.a8c.com/support-stats/happychat/transcript.php?id=661108

**Comment by rachelmcr** [comment] 2017-09-27 11:01
I took a quick look at this, and Simple sites have a `show_on_front` option returned by the API that is set to `posts` or `page`. When that option is set to `page`, another option `page_for_posts` returns the ID for the posts page, which is used to populate this field.

However, Atomic sites with a static front page return `false` instead of `page` for the `show_on_front` option, and don't have a `page_for_posts` option.

I also tested on a regular Jetpack site and there seems to be another API issue in that case, where the `page_for_posts` option always returns `posts` (and so sites with a static front page never show the correct information here).

**Comment by lsinger** [comment] 2017-09-27 11:06
Pinged Team Tanooki for a possible more graceful handling of the API problem on the client (/cc @mattsherman). I think the actual issue is an API problem, though.

**Comment by mattsherman** [comment] 2017-09-27 21:18
I have thought about this a bit... I agree that these are API issues, and they should be addressed in the API (@rachelmcr, have you opened API issues for these?). Since we aren't getting the correct information back from the API, I don't think there is something we can really do client-side to gracefully handle this.

But, this did bring to light a separate issue that results in similar behavior... if you set a page that doesn't have a title as the posts page, then it will show the same empty quotes. In that case, we should probably show something similar to what the customize does. I've opened a separate issue for this (https://github.com/Automattic/wp-calypso/issues/18340).

**Comment by rachelmcr** [comment] 2017-09-29 16:30
@mattsherman Thanks for the nudge! I hadn't opened API issues for these yet, so I just did (see 7939-wpcom and 7940-wpcom).

On the client side, could we remove the entire "Blog Posts" block from the Site Pages screen and show the posts page in the regular list of pages if the `show_on_front` option is to set `false`? At least that way Atomic sites will have just a list of pages there, instead of showing the Blog Posts section with empty quotes where the posts page title should be.

**Comment by gwwar** [comment] 2018-03-16 00:00
cc @jhnstn do you have any cycles for this one?

**Comment by rachelmcr** [comment] 2018-08-29 11:39
I tested and confirmed that this is resolved for Atomic sites:

![screenshot 2018-08-29 12 33 06](https://user-images.githubusercontent.com/8658164/44785120-baef9c00-ab87-11e8-8895-1759c5ee9ccb.png)

I also closed the related API issues 7939-wpcom and 7940-wpcom, which are both fixed.

**Closed by rachelmcr** 2018-08-29 11:39 UTC
Labels: API, Atomic, Pages, [Pri] High, [Type] Bug
