### ISSUE TITLE
FSE: User unable to edit templates or add new ones

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/wp-calypso#63115] opened 2022-04-27 19:47 UTC
### Quick summary

A user is not able to edit templates or add new ones. 

### Steps to reproduce

I've **not** been able to reproduce while in the user's account; I was able to add a template called "test template" to their site and edit it.

In two different browsers, they get JavaScript errors when trying to edit a template or add a new one.

Here's an example of errors they saw in Chrome when trying to create a new template:

```
TypeError: Cannot read properties of null (reading 'frameElement')
at Jm (https://tfacincinnati.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=019325bda5acdd5ffa843a51bfdb5cbc:64:1555)
at ft (https://tfacincinnati.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:43451)
at Wt (https://tfacincinnati.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:50270)
at ts (https://tfacincinnati.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:112276)
at Fr (https://tfacincinnati.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:77758)
at Dr (https://tfacincinnati.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:77686)
at Rr (https://tfacincinnati.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:77549)
at Nr (https://tfacincinnati.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:74544)
at https://tfacincinnati.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=5.9.3:1:30170
at unstable_runWithPriority (https://tfacincinnati.com/wp-content/plugins/gutenberg/build/vendors/react.min.js?ver=5.9.3:1:7430)
```

Clearing browser cache did not work.

In both Firefox and Chrome, they continuously get an error that something on the page is slowing down the browser.

There was a suspicion that perhaps it could be related to this bug: 
https://github.com/Automattic/wp-calypso/issues/62521

A colleague found it slow to open the test template after adding a navigation menu there, but it was still speedy for me.

### What you expected to happen

It should be possible to add or edit templates, without console errors.

### What actually happened

Unable to add new or edit existing templates.

### Context

customer report 

follow-up ticket: 5172572-zd-woothemes

### Available workarounds?

No and the platform is unusable

**Comment by edequalsawesome** [comment] 2022-04-27 19:52
> A colleague found it slow to open the test template after adding a navigation menu there, but it was still speedy for me.

For context, I duplicated this in Firefox (100.0b9) and Chrome (100.0.4896.127)

I had different errors than the user, though! 

![JavaScript Errors](https://user-images.githubusercontent.com/4000628/165619856-bfa9130d-852a-488e-abcd-3eb149bc0b73.png)

**Comment by Robertght** [comment] 2022-04-28 06:52
Another case in 5168368-zen

**Comment by cuemarie** [comment] 2022-05-04 17:46
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No
- Updated main description of report - No

📌 SCRUBBING
- Tested on user's site

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate the issue happening on the user's site. Site editor responded incredibly slowly, and my error reports matched Eds screenshot. I could not edit anything on the Front Page template (or open List View) due to the slow speeds.
- My browser: Firefox 100 on macOS (Catalina): https://whatismybrowser.com/w/P9Z5SPL

I was able to create a new template and delete it, but especially on the Front Page template, FireFox continued to warn me that `This page is slowing down Firefox. To speed up your browser, stop this page.`

<img width="1413" alt="Markup 2022-05-04 at 10 40 13" src="https://user-images.githubusercontent.com/27249804/166747379-99fcb52c-4fd6-417a-bd90-907fb9e816d0.png">

Deactivating `coblocks` temporarily did not resolve the issue. Will check in with OP before moving this on - seems a full plugin conflict test could help troubleshoot further

📌 ACTIONS
- Await author feedback

**Comment by cuemarie** [comment] 2022-05-04 17:48
@kathrynwp Has a full plugin conflict test been run for this? That might help us eliminate other possibilities. If we can get permission from the user to do so, I can come back to this and test again with all plugins deactivated, since I'm able to reproduce the error.

**Comment by upwardmomentum84** [comment] 2022-05-07 14:33
Just responded to the user for permission to do a plugin conflict test - 5172572-zd-woothemes

**Comment by ClassicRKR27** [comment] 2022-05-07 15:49
Providing a quick update on this - I believe this is related to the CoBlocks plugin. I deactivated it and it resolved the speed issues; there were still console errors related to it but I believe that is because the blocks were still placed on the Front Page template. When I was testing the other templates that didn't have any CoBlocks blocks, none of them showed any issues with slowdown.

I also tested deactivating the AMP and "Sheets To WP Table Live Sync" plugins and they didn't seem to have any effect on the issue.

For the inability to create new templates, I suggested that the user try clearing their DNS cache to see if that could resolve the issue for them. I didn't have any issues with creating new templates from the multiple methods I tried (directly in FSE editor/from page editor).

I'm keeping this open in case it still needs to be looked at by a developer.

**Comment by formosattic** [comment] 2022-05-09 05:06
+1 35425326-hc

Site didn't have CoBlocks. Just had GTranslated as third-party plugin.

Editor was super slow for user and I, they only managed to edit because they were very patient.
Had them clear cache, but no luck.

Error from the console:
![image1](https://user-images.githubusercontent.com/15944096/167344068-459663d4-867c-4c17-ade2-ffd82479dee4.png)

**Comment by Greatdane** [comment] 2022-05-25 05:16
They only error I see that is the same on the above reports is `wp-json/wpcom/v2/site-intent?_locale=user` 

Console log; 

```
Failed to load resource: the server responded with a status of 404 ()
/wp-json/wpcom/v2/site-intent?_locale=user:1    
```

Clicking on the error gives this information;

```
{"code":"rest_no_route","message":"No route was found matching the URL and request method.","data":{"status":404}}
```

However, I also see this error on my functioning FSE site 🤔

**Comment by Greatdane** [comment] 2022-10-06 04:44
As we have heard no more reports about this, and have been unable to reproduce the issue on another site, will close the issue for now.

**Closed as completed by Greatdane** 2022-10-06 04:44 UTC
Labels: Bug, [Pri] Normal, [Feature] Full Site Editor
