### ISSUE TITLE
Reader: Missing images for photon urls with too small a width

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#10283] opened 2016-12-27 19:13 UTC
In general, our images urls allow for query params that resize images.   The WP Reader should ideally only care about the actual image size as opposed to the resized size when checking for potential canonical image status (also when loading the image).

For example, the post 
- located at `https://wordpress.com/read/blogs/39014270/posts/9464` 
- has an image: `https://stevewsimpson.files.wordpress.com/2016/12/storied_glass_and_steel2.jpg?w=328&h=295`

While the [actual image](https://stevewsimpson.files.wordpress.com/2016/12/storied_glass_and_steel2.jpg) is quite large, the resized one only has a width of 328px which is below the Reader cutoff of 350px.  

This issue can be closed when we teach Reader to pick up on original photo sizes.

**Comment by samouri** [comment] 2016-12-27 19:18
The bug is probably a regression from: https://github.com/Automattic/wp-calypso/pull/10096

**Comment by designsimply** [comment] 2016-12-28 18:59
Closing as a duplicate of https://github.com/Automattic/wp-calypso/issues/10189.

**Closed by designsimply** 2016-12-28 18:59 UTC
Labels: Reader, [Type] Bug
