### ISSUE TITLE
[Bug]: "Add New" button on Templates page in Site Editor opens panel behind template UI

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#62052] opened 2022-03-18 10:54 UTC
### Quick summary

Clicking on the _Add New_ button in _Appearance_ > _Site Editor_ > _Templates_ opens what should be a dropdown option to create a new template behind the panel that uses the `.interface-interface-skeleton__content` class. 

### Issue in context

https://user-images.githubusercontent.com/2912202/158989282-f44758a2-6538-410e-9aec-1dc06eea1928.mp4

### Closer view

![Capture_2022-03-18 at 10 42 22](https://user-images.githubusercontent.com/2912202/158989375-f172a39c-f0da-4594-93b0-310458733f2c.gif)

### "Overlapping" element

![Capture_2022-03-18 at 10 43 25@2x](https://user-images.githubusercontent.com/2912202/158989428-fcf05ceb-8457-4923-b86c-8940a6c7dcb9.png)

### Steps to reproduce

1. Head to _Appearance_ > _Site Editor_ > _Templates_
2. Click on the _Add New_ button in the top right to toggle a dropdown to add a new template
3. See the _Add New_ panel open behind the UI below the _Add New_ button.

### What you expected to happen

I expected the _Add New_ button to toggle a panel like this:

<img width="400" alt="Markup 2022-03-17 at 11 02 25" src="https://user-images.githubusercontent.com/2912202/158989844-521a62b3-32bc-4a73-a750-97501aa7232f.png">

### What actually happened

The panel I was expecting to see is hidden, like this:

![Capture_2022-03-18 at 10 42 22](https://user-images.githubusercontent.com/2912202/158989918-8059ba22-eb95-4296-b4ac-99818c360908.gif)

### Context

Internal testing and reporting

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Simple/Atomic

Simple, Atomic

### Other notes

I noticed this in the process of reporting an issue relating to errors resulting from using the _Front Page_ option under _Add New_.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Addison-Stavlo** [comment] 2022-03-18 11:57
Thanks for creating this detailed issue report @pauljacobson !

Im going to close this issue in favor of:
* https://github.com/Automattic/wp-calypso/issues/62054
* https://github.com/WordPress/gutenberg/issues/39548

since we have duplicates in wp-calypso atm and see the root cause fixed upstream. were working to wrangle this down to dotcom though 😁

**Closed as completed by Addison-Stavlo** 2022-03-18 11:57 UTC
Labels: Bug, [Goal] Full Site Editing, [Goal] Page Templates, Needs triage

**Comment by pauljacobson** [comment] 2022-03-18 12:19
Thanks for the update @Addison-Stavlo
