### ISSUE TITLE
An unhandled error occurred creating or editing posts

### ISSUE THREAD

**Issue by villanovachile** [Automattic/wp-calypso#49086] opened 2021-01-07 19:44 UTC
#### Steps to reproduce
1. Create or edit post
2. Error produced "An unhandled error occurred"

Only seems to be occurring when editing/creating posts. User is able to view statistics and perform other actions. Issue also seems to be intermittent, as it was not occurring today but occurred yesterday. 

#### What I expected
- User expected to be able to edit/create post without issue

#### What happened instead
- Error occurred

#### App Version / OS version
App Version - 6.6.0
OS: Windows 10

#### Screenshot / Video
- Unable to provide

#### Context / Source
#3626760-zen

User provided these logs: 
[wpdesktop-2021-01-06T17.31.34.768 (1).zip](https://github.com/Automattic/wp-desktop/files/5783642/wpdesktop-2021-01-06T17.31.34.768.1.zip)

**Comment by designsimply** [comment] 2021-01-20 20:00
Thank you for reporting this! 

I tested with both v6.6.0 and v6.7.0 and found that I was able to replicate the bug as described when using v6.7.0. 

Steps to reproduce:

1. Download and install wordpress.com-win32-setup-6.7.0.exe (from [here](https://github.com/Automattic/wp-calypso/releases/tag/v6.7.0)) on Windows 10.
1. Go to My Site > Site > Posts > Add new post.
1. Observe that the post does not open in the app and the following errors appear:

On screen error:

> Unable to Use the Editor
> An unhandled error occurred. 

App logs error:

```
[2021-01-20 11:20:06.452] [desktop:boot] [info] Booting WordPress.com v6.7.0
[…]
[2021-01-20 11:22:52.586] [desktop:external-links] [info] Cannot open editor for site: {"siteId":159889361,"reason":"REASON_BLOCK_EDITOR_UNKOWN_IFRAME_LOAD_FAILURE","editorUrl":"https://madefortesting190318.wordpress.com/wp-admin/post-new.php?calypsoify=1&block-editor=1&frame-nonce=081bf3365c&origin=http%3A%2F%2F127.0.0.1%3A41050&environment-id=desktop","wpAdminLoginUrl":null,"origin":"http://made4testing0318.blog","canUserManageOptions":true}
[2021-01-20 11:22:52.586] [desktop:external-links:handle-jetpack] [error] Cannot use editor, unhandled reason: {"siteId":159889361,"reason":"REASON_BLOCK_EDITOR_UNKOWN_IFRAME_LOAD_FAILURE","editorUrl":"https://madefortesting190318.wordpress.com/wp-admin/post-new.php?calypsoify=1&block-editor=1&frame-nonce=081bf3365c&origin=http%3A%2F%2F127.0.0.1%3A41050&environment-id=desktop","wpAdminLoginUrl":null,"origin":"http://made4testing0318.blog","canUserManageOptions":true}
[2021-01-20 11:22:52.588] [desktop:external-links] [info] Using system default handler for URL: https://madefortesting190318.wordpress.com/wp-admin/post-new.php?calypsoify=1&block-editor=1&frame-nonce=081bf3365c&origin=http%3A%2F%2F127.0.0.1%3A41050&environment-id=desktop
[2021-01-20 11:22:52.588] [desktop:ipc] [info] showMySites triggered
[2021-01-20 11:22:52.588] [desktop:external-links:handle-jetpack] [info] Falling back to opening editor in browser with editor URL: 'https://madefortesting190318.wordpress.com/wp-admin/post-new.php?calypsoify=1&block-editor=1&frame-nonce=081bf3365c&origin=http%3A%2F%2F127.0.0.1%3A41050&environment-id=desktop'
[2021-01-20 11:23:24.702] [desktop:menu:help] [info] User selected 'Get Application Logs'...
```

![image](https://user-images.githubusercontent.com/1119271/105226366-20f46980-5b1d-11eb-8a21-169407668243.png)
<sup>Tested with WPDesktop 6.7.0 (exe downloaded from GitHub releases page) on Windows 10 using made4testing0318.blog logged in as testuser0313.</sup>

I also updated from v6.7.0 to v6.8.0-beta1 and the same error happens in the latest beta. 

Aside: I noticed that each time this happens, the edit session is sent to the browser as a fallback, however, that happens in the background if a browser session is already open and can be a bit hard to spot.

**Comment by nsakaimbo** [comment] 2021-01-22 18:49
Thanks for the update, @designsimply. I've been testing v6.8.0-beta1 on Windows 10 with both a Simple and Atomic site and so far am unable to reproduce this. In both cases, Gutenberg loaded just fine, and the Classic editor was redirected to an external browser when enabled.

Also worth pointing out - if you toggle between the Classic and Gutenberg editors for a site, you'll need to restart the app so the app can refresh its known state about the sites plugins. (We hope to refine this behavior in the near future.)

Just curious - are you proxied, by any chance, and does toggling your proxy affect this behavior? Just trying to brainstorm what it could be.

At the very least (even though clunky, while a more definite repro is pending,  the user's browser is being activated as a fallback.

**Comment by designsimply** [comment] 2021-01-22 19:36
Ah! I'm actually really glad you couldn't replicate it because that means it's not as bad a bug as I first thought. 

I tested with a Windows 10 virtual machine setup through VirtualBox. No proxy. I used my test site `made4testing0318.blog` which currently uses a Premium plan and the selected editor is `gutenberg` for that site for `testuser0313` for both web and mobile (I double checked this just now in the user report card for user_id 154288761). Thanks for working through troubleshooting on this one with me!

**Comment by designsimply** [comment] 2021-01-22 19:48
Moving from blocker to high priority since we've had a a user report of this but lowering priority a little because it's intermittent and/or cannot be replicated in some cases and efforts are moving toward a rewrite which we want to prioritize.

If you are experiencing this bug, please drop a comment here so we can get an idea of how many people it's happening to. The logs we have are good, but if you know how to access the developer console in the Desktop App and can spot any errors there then please include those for reference. Thank you!

**Comment by designsimply** [comment] 2021-02-26 22:56
Note: this issue was originally moved from the `wp-desktop` repo (which is no longer in use and `wp-calypso` is now where WPDesktop app issues should be filed) and today I noticed this issue is already on file at https://github.com/Automattic/wp-calypso/issues/48319 and so I am closing this one as a duplicate.

**Closed as completed by designsimply** 2021-02-26 22:56 UTC
Labels: [Pri] High, [Feature] WordPress Desktop App, Windows
