### ISSUE TITLE
[Bug]: [Block] Blog Posts Block: More posts button missing styles - incorrect syntax

### ISSUE THREAD

**Issue by aleone89** [Automattic/wp-calypso#71842] opened 2023-01-10 11:23 UTC
### Quick summary

When the Blog Post block is in use: https://wordpress.com/support/wordpress-editor/blocks/blog-posts-block/ and the More Posts button is active, this button is missing styles.

Looking at inspector tools the console shows: 

`Uncaught SyntaxError: Unexpected token '<'
`
Looking at the HTML, it looks like the code is indeed missing a `/> ` making the closing button tag problematic. 

```
<button type="button" data-next="https://public-api.wordpress.com/wpcom/v2/sites/213069933/articles?className=is-style-default&amp;showReadMore=1&amp;imageShape=square&amp;moreButton=1&amp;moreButtonText=MORE%20POSTS&amp;showAuthor=0&amp;showCategory=1&amp;postLayout=grid&amp;postsToShow=9&amp;typeScale=3&amp;postType%5B0%5D=post&amp;align=wide&amp;showExcerpt=1&amp;excerptLength=55&amp;readMoreLabel=Keep%20reading&amp;showDate=1&amp;showImage=1&amp;showCaption=0&amp;minHeight=0&amp;showAvatar=1&amp;columns=3&amp;mediaPosition=top&amp;&amp;&amp;&amp;&amp;&amp;&amp;imageScale=3&amp;mobileStack=0&amp;sectionHeader&amp;specificMode=0&amp;textColor&amp;customTextColor&amp;singleMode=0&amp;showSubtitle=0&amp;page=2">
				MORE POSTS				</button>

```

### Steps to reproduce

1. Go to page, add new 
2. Add Blog Post block, if there are 6 blog posts in the site, set to show three posts 
3. Enable the "Show Load More Posts button" 
4. Publish page

### What you expected to happen

To see the More posts button with styles as seen in the editor on the live site. 

### What actually happened

More Posts button is missing styles on the live site. 

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari

### Context

https://wordpress.com/forums/topic/display-not-matching-the-editor/?view=all

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by kavyagokul** [comment] 2023-01-10 11:45
📌 SCRUBBING : RESULT
- Tested on P2 - Replicated
- Tested on Simple - Replicated 
- Tested on AT - Replicated 
- Tested on Self-hosted - Could Not Replicate 
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Only happens on simple sites, and on Atomic sites with a block theme
- Can't reproduce on atomic sites with classic themes

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by leogermani** [comment] 2023-01-10 15:47
This issue has been fixed in https://github.com/Automattic/newspack-blocks/pull/1252

We need to sync the code on wpcom to use the latest version of the block. Let's coordinate to do this.

EDIT: And I can't confirm the missing `>` bug. Tags look good. It also looks good on the code snippet in the OP

**Closed as completed** 2023-01-11 17:52 UTC
Labels: Bug, [Pri] High, [Status] In Progress, Blocks, Triaged, [Platform] Simple, [Platform] Atomic
