### ISSUE TITLE
Unnecessary border on the Plugins page for managed plugin associated with SaaS product

### ISSUE THREAD

**Issue by NeosinneR** [Automattic/wp-calypso#81007] opened 2023-08-24 08:59 UTC
### Quick summary

There is a border between the plugin and the `MailPoet is automatically managed for you.` notice if the plugin was installed when an associated SaaS product was purchased. 

### Steps to reproduce

1. Subscribe to the MailPoet SaaS product (https://wordpress.com/plugins/mailpoet-business) - free or paid, doesn't matter
2. When completed, MailPoet plugins are automatically installed
3. Go to the Installed plugins page
4. Observe the border between the MailPoet plugin and the `MailPoet is automatically managed for you.` notice, which is not available in other managed plugins.

<img width="1682" alt="Screenshot 2023-08-24 at 10 50 21" src="https://github.com/Automattic/wp-calypso/assets/470616/4c26c53f-0115-4f6f-90ee-69d848d8627f">

### What you expected to happen

There is **no border** between the plugin info and the `${plugin} is automatically managed for you.` notice.

### What actually happened

There is **a border** between the plugin info and the `${plugin} is automatically managed for you.` notice.

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

AFAIK, MailPoet is the first usage-based SaaS product in Dotcom Marketplace, which might play a role, if it was implemented differently than other fixed-price SaaS products.

**Comment by cuemarie** [comment] 2023-08-24 22:38
📌 REPRODUCTION RESULTS
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
Tried following these steps to replicate on a self-hosted site, but couldn't sign up using my (connected) WordPress.com account.

**AT Site**

![Markup on 2023-08-24 at 15:37:18](https://github.com/Automattic/wp-calypso/assets/27249804/9739d840-a290-47b7-b95f-556867e0e80d)

📌 ACTIONS
- Triage Complete
- CC: @Automattic/bespin

**Comment by gcsecsey** [comment] 2023-08-28 14:13
I investigated this briefly, we add this notice message here: fbhepr%2Skers%2Sjcpbzfu%2Ssrngher%2Qcyhtvaf%2Sznantrq%2Qcyhtvaf.cuc%3Se%3Qr831r32r%23250%2Q272-og

I think we need to update the styling (remove the border-box) for this instance of the notice.

**Comment by JulianBustamante** [comment] 2024-08-21 21:24
Closing this issues since the plugins page was updated and the line is not showed anymore.

![Image](https://github.com/user-attachments/assets/495ef10d-a0fd-4e04-ad32-5d3c9584057c)

**Closed as completed by JulianBustamante** 2024-08-21 21:24 UTC
Labels: Bug, [Pri] Normal, [Feature] Plugins, Triaged, [Platform] Atomic, [Product] WordPress.com, [Feature Group] Other Infrastructure
